### ISSUE TITLE
PostLogoutRedirectUri "lost" when signing out using an external IdP

### ISSUE THREAD

**Issue by devlz303** [IdentityServer/IdentityServer3#1000]
I have a situation where I have a SPA that uses an IdentityServer for authentication / authorization.
This instantie of IdentityServer uses an external IdP for user authentication.
Signing in works ad expected. However, when the users signs out of the SPA, the PostLogOutRedirectUri is sent to the first IdSrv in the chain, but not passed to the external IdP.
When a client only has one PostLogOutUri configured this is not a problem, because IdSrv will pick the first configured PostLogoutRedirectUri when it's not available in the request uri.
In my situation I want to use the same client for multiple environments (development, testing, etc.) so I have configured multiple PostLogOutRedirectUri's. But when I log out, I will always return to the first configured PostLogoutRedirectUri.

I can solve this problem by configuring a client for each environment, but I don't know if that is the right solution. Is there a way to get the PostLogoutRedirectUri from SPA to the external IdSrv?

Kind regards

**Comment by devlz303** [comment]
I have probably found a solution for my situation. When I configure the external IdP using OpenIdConnectAuthentication, I use some appSettings to configure the redirecturi. At this point I can also set the desired PostLogoutRedirectUri according to the specific environment (development, testing, etc.).

But this still does not answer my question: Is it possible to get the PostLogoutRedirectUri from the SPA all the way up to the external IdP?

**Comment by brockallen** [comment]
Only if you somehow manage that state (meaning which url) across all the hops and if the upstream IdPs also allow the concept of post logout URLs.

**Comment by devlz303** [comment]
Thanks for your answer.

The problem I am facing right now is exactly what you mention. In the first hop (at the first IdentityServer) the PostLogoutRedirectUri is stored in a SignOutMessage (cookie). But in the AuthenticationController.Logout method the logged out page isn't rendered because the SignOutOfExternalIdP method is called, which in turn causes a redirect to the external IdP but without the PostLogoutRedirectUri. I think I have to set the PostLogoutRedirectUri on the ProtocolMessage in the OpenIdConnectAuthenticationNotifications.RedirectToIdentityProvider eventhandler, but I don't know how to retrieve it at this point.

**Comment by brockallen** [comment]
I've not looked into the details or mechanics to ensure this will work smoothly in IdSvr. I'll leave this open as a 1.3 item.

**Comment by devlz303** [comment]
Ok thanks

**Comment by brockallen** [comment]
Is your upstream IdP using OIDC?

**Comment by devlz303** [comment]
I think it is, but I'm not sure I really understand your question. :)
So let me explain my situation a bit more.

I have a SPA that uses the oidc.js library and this SPA is a client of an IdentityServer (let's call it IdSrv 1).
IdSrv 1 is configured to only use external authentication, using the OpenIdConnectAuthenticationMiddleware which uses an external IdentityServer (let's call this one IdSrv 2).

When a user logs in at the SPA, the request for an id_token and access_token is made at IdSrv 1. IdSrv 1 uses external authentication, so it redirecten the authentication request to IdSrv 2. After successful login the user is redirected back to IdSrv 1 which in turn redirects the user to the specified redirect_uri and eventualy ends up at the callback page of the SPA with the id_token and access_token in the hash.
So far, so good.

Now comes the tricky part. :)
In my situation I was using one client for both my development Environment and also my Test enviroment. I had multiple redirect_uri and post_logout_redirect_uri's configured for this client.
Because the SPA sends the redirect_uri and post_logout_uri in the call to IdSrv 1 this "should" work with different environments.
For the log in situation this is correct. Logout is different when using an external Identity Provider, because in this situation the LoggedOutPage at IdSrv 1 is never rendered. IdSrv 1 will instead call SignOutOfExternalIdP and redirects to IdSrv 2, but without the post_logout_redirect_uri.
Like I said in my first post, if it would be possible to get this uri in the OpenIdConnectAuthenticationNotifications.RedirectToIdentityProvider handler then I could set the ProtocolMessage.PostLogoutRedirectUri property.

I hope this is enough information for you to solve this puzzle. Maybe I want to do something which is not possible or correct. If that's the case: shoot me :)

Kind regards

**Comment by brockallen** [comment]
Yep, I understand the issues. I was just asking to see if we can leverage an upstream state param so we can round trip a cookie identifier to stash away state. I have an idea how to do this properly, but I'll push it to 2.0.

**Comment by PoyaManouchehri** [comment]
Just "seconding" this requirement. The PostLogOutRedirectUri makes it to the View Service which is great in the case of local sign-in (I can redirect the user back automatically). In the case of an external IdP though, I have no way (as far as I can tell) of accessing this URL within RedirectToIdentityProvider. My external IdP uses WSFederation so I need to be able to set WReply.

Thanks

**Comment by PoyaManouchehri** [comment]
An update and a question. I managed to get access to the `PostLogoutRedirectUri` within `RedirectToIdentityProvider` by essentially reading/decoding the `SignOutMessage` cookie. It's somewhat of a hack but it works. This can then be sent along to the external IdP with the WReply (for WSFed).

I'm still missing something though: If the post-signout Url points to the client application, that means that my external IdP would have to trust many different redirect Urls (for each client application). What would make more sense is (similar to the sign-in flow) for the external IdP to redirect back to IdentityServer, and in turn have IdentityServer redirect back the client application.

I can happily have my external IdP redirect back to "/connect/endsession" endpoint on IdentityServer with an appropriate `post_logout_redirect_uri`. The issue is that I would need to pass along the `id_token_hint` as well. Is there any way to get this value or generate it during a `RedirectToIdentityProvider` event on IdentityServer?

Not sure if I'm going about this the wrong way. There doesn't seem to be a whole lot of information about federated sign-out (at least for anything more than 1 hop). Would really appreciate some help with this.

**Comment by michaelschnyder** [comment]
facing the same problem and tried to find a solution similar to @PoyaManouchehri but with no look, id_token is missing there... 

Since we currently support only one application, I adjusted the LogoutPage with a configurable URI for Dev, Test & Prod

**Comment by brockallen** [comment]
This is slated for 2.1 -- that's when we'll provide something to help out on this issue.

**Comment by brockallen** [comment]
I pushed a branch (with a nice descriptive name) here to provide support for this: https://github.com/IdentityServer/IdentityServer3/tree/preserve_signout_message_state_when_logout_of_upstream_idp

There are a few new extension methods for you: 

1) to see if there's a signout message that is pending. this woul[d be used when you detect that you're redirecting to your IdP for signout. it's called: `GetSignOutMessageId`. That value you need to round trip. You'd use it something like this:

```
RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnectRequestType.LogoutRequest)
                        {
                            var id_token_claim = n.OwinContext.Authentication.User.Claims.FirstOrDefault(x => x.Type == "id_token");
                            if (id_token_claim != null)
                            {
                                n.ProtocolMessage.IdTokenHint = id_token_claim.Value;

                                var signOutMessageId = n.OwinContext.Environment.GetSignOutMessageId();
                                if (signOutMessageId != null)
                                {
                                    n.OwinContext.Response.Cookies.Append("state", signOutMessageId);
                                }
                            }
                        }
                        return Task.FromResult(0);
                    }
```

2) You'd need to provide a callback for post logout that runs in our pipeline to then tell IdSvr to render the logged out page (based upon the sign out message id you got earlier):

```
 coreApp.UseIdentityServer(idsrvOptions);

                coreApp.Map("/post-logout-callback", cb =>
                {
                    cb.Run(async ctx=>
                    {
                        var state = ctx.Request.Cookies["state"];
                        await ctx.Environment.RenderLoggedOutViewAsync(state);
                    });
                });
```

This is a big change. Can you try out this branch and let us know how it works. We need the feedback before we merge it in.

**Comment by devlz303** [comment]
Thanks. I will take a look a it tomorrow.

**Comment by lthib** [comment]
I elected to make use of the branch code with WS-Fed external IdPs today and this approach appears to be working well. I first set the middleware option for SignOutWreply in my AuthenticationOptions.IdentityProviders delegate to match the mapping for the handler that renders the logged out view:

```csharp
private void AddExternalProviderToApplication(IAppBuilder builder, string signInAsType, string coreDnsBindingAndPath)
{
    var wsFedOpts = new WsFederationAuthenticationOptions {
        SignInAsAuthenticationType = signInAsType,
        SignOutWreply = coreDnsBindingAndPath + "/post-logout-callback"
    };
    builder.UseWsFederationAuthentication(wsFedOpts);
}
```

I then reproduced the same mapping to handle the `post-logout-callback` path. Similar to the OIDC code provided above, I set a state cookie in the redirect to IdP notification and consumed it upon return to the callback to render the logged out view using the new extension. The redirect notification handler is provided below.

```csharp
public static Task RedirectToIdentityProviderNotificationHandler(
    RedirectToIdentityProviderNotification<WsFederationMessage, WsFederationAuthenticationOptions> n)
{
    if (n.ProtocolMessage.IsSignOutMessage)
    {
        var signOutMessageId = n.OwinContext.Environment.GetSignOutMessageId();
        if (signOutMessageId != null)
        {
            n.OwinContext.Response.Cookies.Append("state", signOutMessageId);
        }
    }

    return Task.FromResult(0);
}
```

The branch code seems solid in my individual use case and I was properly redirected to my post-logout URL after briefly observing the rendered logout page markup (as I have automatic redirect enabled).

**Comment by brockallen** [comment]
Thanks for testing it @lthib

**Comment by devlz303** [comment]
We are still using IdentityServer version 1.x in our solution, so I wasn't able to test it in this codebase.
So I have made a new solution that mimics our situation and used the branch to test it.

I can say that it is working as expected. :+1:
