### ISSUE TITLE
SignInMessageThreshold as an option?

### ISSUE THREAD

**Issue by loctanvo** [IdentityServer/IdentityServer3#1010]
We are once in a while experiencing a `400 Bad Request - Request Header too long` response from our web server. This is due to us having too many cookies, including the SignInMessage cookies. IdServer [default keeps the latest 5 SignInMessage cookies](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Configuration/Hosting/MessageCookie.cs#L221). In our case, that's not always necessary. Although I do know that I can configure our web server to accept larger request headers, we'd like to be able to control how many SignInMessage cookies are being kept.

I'm wondering if it's ok to add this option to the existing [CookieOptions](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Configuration/CookieOptions.cs)? Or, conceptually, should it rather be an option on [AuthenticationOptions](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Configuration/AuthenticationOptions.cs)? The default can still be 5 when not specified.

I can create a PR for this, if you think the idea is ok. Just let me know. The change should be fairly straightforward and backward compatible.

**Comment by brockallen** [comment]
Sure, we could make this configurable. Please PR.

**Comment by loctanvo** [comment]
Cool, will do. Hopefully I'll have some time later today/tonight to look at it.

**Comment by brockallen** [comment]
Any progress?

**Comment by brockallen** [comment]
FYI -- if you're interested in this getting into 1.3, then we need a PR soon (by end of Monday).

**Comment by johnkors** [comment]
@loctanvo has gone skiing for the weekend, but he´ll get it in by monday (european time!).

https://github.com/loctanvo/Thinktecture.IdentityServer3/commit/363dd5a7337f36980078bbae376d112b4be4e69e

**Comment by brockallen** [comment]
wat? :P

**Comment by johnkors** [comment]
hehe, @loctanvo and I are working on the same project .. i know the status of his PR :)

**Comment by brockallen** [comment]
Anyway -- we want to do 1.3 middle of next week... thus the heads up. Thx.

**Comment by loctanvo** [comment]
Sure, the fix is in my fork (but accidentally done in master, so i'll cherry pick to dev.). The fix is easy, but the it's tricky to unit test it. Will get it done before monday is over. As @johnkors pointed out, I'm on a skiing trip this weekend. 😊

**Comment by brockallen** [comment]
I was shoveling snow in my driveway today... I'm sure it's about the same as a ski weekend :P

**Comment by johnkors** [comment]
Then I just have to recommend you this norwegian best seller. ;) http://issuu.com/juritzenforlag/docs/mak_sno

**Comment by FabienDehopre** [comment]
I have the same kind of error but with the cookie OpenIdConnect.nonce
Is this related or do I need to create a separated issue?

**Comment by loctanvo** [comment]
@FabienDehopre Experiencing [this?](http://katanaproject.codeplex.com/workitem/402)

The workaround is to downgrade the OIDC middleware to version 3.0.0.

**Comment by johnkors** [comment]
Yep, it's a Katana "bug" -not an Idsrv thing. Please add a comment in @loctanvo's bug report for Katana at CodePlex so they are aware of the severity of the issue.

**Comment by FabienDehopre** [comment]
@loctanvo Indeed, that's what I'm experiencing.
@johnkors I will add a comment to the bug report.
Thanks to both of you for the quick answer

**Comment by loctanvo** [comment]
Please have a look at the pull request I issued yesterday. Any comment or feedback appreciated. Thx

**Comment by brockallen** [comment]
Merged on dev
