### ISSUE TITLE
session_state not available after keep me signed in selected

### ISSUE THREAD

**Issue by jageall** [IdentityServer/IdentityServer3#1017]
the identity server session cookie is only set if the user signs in.  If the user has selected remember me, and comes back after the browser session has ended the session cookie will never be created as the user is already authenticated. This stops session_state from being past back to the client application.

**Comment by brockallen** [comment]
fixed on dev -- please test and let me know. thx

**Comment by jageall** [comment]
will try and test it tomorrow evening
