### ISSUE TITLE
i have two clients with same client Id in this getting problem while Logout ?

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#1028]
I have opened two clients in browser with two tabs if i have log out in 1st tab it has to logout in both tab 1st and 2nd but it is not happening.

**Comment by brockallen** [comment]
You need to look into the OIDC session spec -- this allows the clients to know when the user has logged out of the OP. We do this in the "JavaScript Implicit Client - TokenManager" sample.
