### ISSUE TITLE
Adding New Claims (Roles) after Login

### ISSUE THREAD

**Issue by mohammadhammod** [IdentityServer/IdentityServer3#1031]
I am trying to add some roles after a successful login request to the user claims collection ( in addition to the original roles in the DB that are returned normally) , I am using membershipreboot with oracle, so in the CustomUser Class I am overriding the Method GetClaimsForAuthenticateResult(CustomUser account).

what I want to do is to create new claim (role) and add it to account.ClaimsCollection inside this method, is this possible ? I also tried to add directly to claimsPrincipal.Claims  (var claimsPrincipal = User as ClaimsPrincipal) with no hope since  the User is not authenticated in this stage even I thought it should be authenticated.

**Comment by brockallen** [comment]
So you want to add it to the DB or just in the AuthenticateResult which populates the user's claims in the cookie? Or do you want claims in the token(s) going back to the client apps?

**Comment by rajarameshvarma** [comment]
I have similar requirement. I would like to add more claims in the client application (not on server). These are client specific roles. I am using AD as my user source.

**Comment by brockallen** [comment]
@rajarameshvarma so then add them in your client app's code when you get the token. If you're using Katana, then there's an event for that.

**Comment by mohammadhammod** [comment]
I just want to add the Claims in the cookie , not on the DB

**Comment by brockallen** [comment]
@mohammadhammod which cookie -- idsvr's cookie or your app's cookie?

**Comment by mohammadhammod** [comment]
well I just want to be able to access them via claimsPrincipal.Claims like the other claims that were brought from the DB, not sure which kind of cookies is this

**Comment by brockallen** [comment]
In IdSvr or in your app -- I need that clarification to help. I'm guessing you mean back in your app. I think you want to override `GetClaimsFromAccount`.
