### ISSUE TITLE
Authentication by URL

### ISSUE THREAD

**Issue by poostwoud** [IdentityServer/IdentityServer3#1045]
Hi,

For my use case I'm working on authentication by URL support. Iow, the user simply clicks an uri in e.g. an email message that allows the user to login without entering their credentials.

I have created a prototype based on the MVC Owin Client (Hybrid) sample and the custom grant self host to communicate with.

I extended the sample with a "XController" class with the following implementation:

```
public class XController : Controller
{
	[Route("x/{clientid}")]
	public ActionResult UrlAuthorize(string clientid)
	{
		//*****
		var idValue = Request.QueryString["a"];
		var secretValue = Request.QueryString["b"];

		//*****
		var client = new OAuth2Client(
			new Uri("http://localhost:8090/core/connect/token"),
			"wakizashiclient",
			"secret");

		var customParams = new Dictionary<string, string>
		{
			{ "a", clientId },
			{ "b", idValue },
			{ "c", secretValue }
		};

		//***** id_token;
		//***** http://stackoverflow.com/questions/13875366/what-is-id-token-google-oauth
		//***** id_token is a JSON Web Token (JWT). If you decode it, you'll see it contains multiple assertions, including the ID of the user;

		//***** TODO:ResponseType? code id_token token?
		//***** TODO:RedirectUri/PostLogoutRedirectUri/Etc;
		var customGrantResponse = client.RequestCustomGrantAsync("url_authentication", "openid email profile read write offline_access", customParams).Result;

		//***** TODO:id_token => MvcCodeFlowClientManual.Controllers.CallbackController;
		var id_token = "";
		/*var id_tokenProperty = customGrantResponse.IdentityToken;
		var id_tokenParts = id_tokenProperty.Split('.');
		var id_token = JObject.Parse(Encoding.UTF8.GetString(Base64Url.Decode(id_tokenParts[1]))).ToString();*/
		
		//***** TODO:Validate token?
		var token = customGrantResponse.AccessToken;

		//***** Split header and claims;
		var parts = token.Split('.');
		var header = parts[0];
		var claims = parts[1];

		var headerObj = JObject.Parse(Encoding.UTF8.GetString(Base64Url.Decode(header)));
		var claimsObj = JObject.Parse(Encoding.UTF8.GetString(Base64Url.Decode(claims)));

		var claimsDictionary = claimsObj.ToObject<Dictionary<string, object>>();
		var claimsList = claimsDictionary.Select(claim => new Claim(claim.Key, claim.Value.ToString())).ToList();

		//***** Get userinfo data
		var userInfoClient = new UserInfoClient(new Uri(Constants.UserInfoEndpoint), token);
		var userInfo = userInfoClient.GetAsync().Result;
		userInfo.Claims.ToList().ForEach(ui => claimsList.Add(new Claim(ui.Item1, ui.Item2)));
		
		//***** 
		claimsList.Add(new Claim("access_token", customGrantResponse.AccessToken));
		claimsList.Add(new Claim("expires_at", DateTime.Now.AddSeconds(customGrantResponse.ExpiresIn).ToLocalTime().ToString()));
		claimsList.Add(new Claim("refresh_token", customGrantResponse.RefreshToken));
		claimsList.Add(new Claim("id_token", id_token));

		//*****
		var id = new ClaimsIdentity(claimsList, "Cookies");
		Request.GetOwinContext().Authentication.SignIn(id);

		//*****
		return Redirect("/Home/Claims");
	}
}
```

Still lots of work to do here, but currently I'm having a strange issue with requesting the user info. For some reason when retrieving the user information the GetAsync() method hangs:

```
var userInfoClient = new UserInfoClient(new Uri(Constants.UserInfoEndpoint), token);
var userInfo = userInfoClient.GetAsync().Result;	//<-- Hangs here;
userInfo.Claims.ToList().ForEach(ui => claimsList.Add(new Claim(ui.Item1, ui.Item2)));
```

The self host custom user service seems to return without any difficulties:

> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.UserInfoResponseGenerator]: 9-3-2015 16:47:09 +00:00 -- Creating userinfo response
> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.UserInfoResponseGenerator]: 9-3-2015 16:47:09 +00:00 -- Scopes in access token: email offline_access openid profile read write
> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.UserInfoResponseGenerator]: 9-3-2015 16:47:09 +00:00 -- Requested claim types: email email_verified sub name family_name given_name middle_name nickname preferred_username profile picture website gender birthdate zoneinfo locale updated_at
> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.UserInfoResponseGenerator]: 9-3-2015 16:47:09 +00:00 -- Profile service returned to the following claim types: given_name family_name email
> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.UserInfoEndpointController]: 9-3-2015 16:47:09 +00:00 -- End userinfo request
> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.UserInfoResult]: 9-3-2015 16:47:09 +00:00 -- Returning userinfo response.

Any thoughts? Thank you in advance for your answer. 

Best regards,

Peter

**Comment by leastprivilege** [comment]
You can't use .Result - use await instead.

Also this id_token was never validated. That's not allowed.
