### ISSUE TITLE
Getting claims from facebook

### ISSUE THREAD

**Issue by marcindzwonnik** [IdentityServer/IdentityServer3#1046]
Hi,

Today I spent a while on making it work, so I decided to share.

When you log in with facebook and new user is created, no matter what scopes you pass in middlware configuration - user will have only 2 claims: name and link.

This is sample soluion

            var fbConfig = new FacebookAuthenticationOptions
            {
                AuthenticationType = "Facebook",
                Caption = "Sign in with Facebook",
                SignInAsAuthenticationType = signInAsType,
                AppId = "adsf",
                AppSecret = "asdf",
                Provider = new FacebookAuthenticationProvider()
                {
                    OnAuthenticated = (context) =>
                    {
                        var meaningfulClaims = new[] {"first_name","last_name", "gender" };
                          const string XmlSchemaString = "http://www.w3.org/2001/XMLSchema#string";
                          foreach (var x in context.User)
                          {
                              var claimType = x.Key;//string.Format("urn:facebook:{0}", x.Key);
                              string claimValue = x.Value.ToString();

                              if (!meaningfulClaims.Contains(claimType)) 
                                  continue;

                              if (!context.Identity.HasClaim(claimType, claimValue))
                                  context.Identity.AddClaim(new System.Security.Claims.Claim(claimType, claimValue, XmlSchemaString, "Facebook"));

                          }

                          return Task.FromResult(0);
                      }
                }
            };

            fbConfig.Scope.Add("public_profile");
            fbConfig.Scope.Add("email");

            app.UseFacebookAuthentication(fbConfig);

Solution found here https://katanaproject.codeplex.com/workitem/82

**Comment by brockallen** [comment]
Is there a question here about IdentityServer? Your comments are more about the Katana FB middleware.

**Comment by marcindzwonnik** [comment]
No there is not. I just always start looking for an answer regarding idsrv here in issues so thought it can be usefull for someone else.

**Comment by brockallen** [comment]
Ok, thanks for the post -- it'll be in the searchable archives.
