### ISSUE TITLE
What's with the token lifetimes when using TokenManager (oidc.js)?

### ISSUE THREAD

**Issue by iltera** [IdentityServer/IdentityServer3#1047]
I am working on a sample AngularJS SPA & WebApi application and using EF for idsrv3 datastore. I am using the oidc.js file in the jsauth sample and using the same settings in there in order to renew and validate the tokens. In my trials, I realized that the value of the id_token is fixed to 300 seconds no matter what. I can change the access_token to any value I want, but for id_token, wasn't so lucky.

In my tests, I created a loop to the secured (with Authorized attribute) WebApi controller to make a get request every second and watched the logs in order to be sure of the results. In the mean time, TokenManager renewed the tokens at the last 60th second -- the default from the oidc.js file.

Here are two of the results I got with the defined configuration (in seconds):

First Try:
id_token: 70 (to wait 10 seconds before the TokenManager renews the token)
access_token: 70
Got 401 results after: 6min. 10sec. (430sec. -- 360 + 70?)

Second Try:
id_token: 300
access_token: 1200
Got 401 results after: 25min (1500sec -- 300 + 1200?)

I am trying to understand the behaviour of the token lifetimes here.
Here are some question that I am trying to get an answer for.

- Why the id_token lifetime cannot be less than 300? Is my assumption correct (these numbers are the result of the id_token being 300 second no matter what value I assign)?
- And why am I getting 401 results after a period of time? (Tokens are renewed successfuly at every access_token lifetime period -- I see the "failed" errors for the requests to the Api controller - in 1sec loop - on the console and for every access_token lifetime period also see the successful token reveived messages. I thought I wouldn't get any more access_token renewal after the id_token expiration.
- I realized that the old access_tokens stay alive until the id_token lifetime. Is that the expected behaviour? (I wait 60 seconds to try the old tokens, to make sure they are expired). I thought they could no longer be used after the access_token lifetime ends. That's why we are renewing them, right?
- With both tokens set to 70 seconds, I can see the api unauthorized errors and the successful token renewal logs after an hour. I hit F5 to refresh the page, and I don't have to login to see the successful api results on the screen. How to interpret this?

These just didn't make sense to me. Can you please clearify what to expect when these tokens time out (for id_token and access_token separately)?

I guess I had some incorrect assumptions about the lifetime of the tokens.

Sorry for the long post and thanks for reading.

**Comment by loctanvo** [comment]
I don't have answers to all your questions, but since you mention 300s... Typically, validation libraries (on the web api side) tend to allow +- 5mins in order to compensate for clock skews. Just keep that in mind.

**Comment by iltera** [comment]
But as far as I know, token validations are made on client side by the functions in oidc.js file. When I enable the logs in the oidc.js, I can see all the logs for different (.well-known/jwks, .well-known/openid-configuration and /connect/userinfo) endpoints on the server. And I didn't realized any compensations (except the one in configureTokenExpired -- there is a +1 second with a comment "register 1 second beyond expiration so we don't get into edge conditions for expiration") on client side, either.

@brockallen, @leastprivilege, can you please clearify these odd situations? I am going through the source code and trying things over and over for over a day now. Cannot pull that through anyhow :(

**Comment by brockallen** [comment]
Did you ever get your answers by looking at the code?

For us to answer a question, perhaps you can ask something more specific?
