### ISSUE TITLE
Dual failure in MVC Authentication Sample

### ISSUE THREAD

**Issue by lennane** [IdentityServer/IdentityServer3#1048]
The Sample MVC Authentication seems to have two problems right out of the box.
In  CallApiController.cs the line 
 var json = await client.GetStringAsync("https://localhost:44321/identity");
should be changed to 
var json = await client.GetStringAsync("https://localhost:44319/identity");
After that is resolved, the json object that is returned is un parseable 
Both CallApi(Client) and CallApi(User) fail with the same error.
"Unexpected character encountered while parsing value: <. Path '', line 0, position 0".

The demo is mounted at https://www.t3xfer.com bob:secret

**Comment by lennane** [comment]
More info:

Both tokens entering the CallApi look good.
Client Token:
{
 typ: "JWT",
 alg: "RS256",
 x5t: "SJTpsz1umCStNt1wzZkfgmI7zA4",
 kid: "SJTpsz1umCStNt1wzZkfgmI7zA4"
}.
{
 client_id: "mvc_service",
 scope: "sampleApi",
 iss: "https://www.t3xfer.com/identity",
 aud: "https://www.t3xfer.com/identity/resources",
 exp: 1425960318,
 nbf: 1425956718
}.
[signature]

User Token too:
{
 typ: "JWT",
 alg: "RS256",
 x5t: "SJTpsz1umCStNt1wzZkfgmI7zA4",
 kid: "SJTpsz1umCStNt1wzZkfgmI7zA4"
}.
{
 client_id: "mvc",
 scope: [
  "openid",
  "profile",
  "roles",
  "sampleApi"
 ],
 sub: "1",
 amr: "password",
 auth_time: 1425956660,
 idp: "idsrv",
 role: [
  "Geek",
  "Foo"
 ],
 iss: "https://www.t3xfer.com/identity",
 aud: "https://www.t3xfer.com/identity/resources",
 exp: 1425960260,
 nbf: 1425956660
}.
[signature]

Raw json from statement:

 var json = awaitclient.GetStringAsync("https://www.t3xfer.com/identity");

<!DOCTYPE html>
<html ng-app="app" ng-controller="LayoutCtrl">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Thinktecture IdentityServer v3</title>
    <link rel="stylesheet" href="https://www.t3xfer.com/identity/assets/styles.min.css">
</head>
<body lang="en">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
            <a href="https://www.t3xfer.com/identity">
                <span class="navbar-brand">
                    Thinktecture IdentityServer3
                </span>
            </a>
        </div>
    </div>

    <div class="welcome-page container">
        <div class="row page-header">
            <div class="col-sm-10">
                <h1>
                    Welcome to Thinktecture IdentityServer3
                    <small>(build 1.2.1.0)</small>
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-8">
                <p>
                    IdentityServer publishes a
                    <a href="https://www.t3xfer.com/identity/.well-known/openid-configuration">discovery document</a>
                    where you can find metadata and links to all the endpoints, key material, etc.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <p>
                    IdentityServer allows users to view and revoke
                    <a href="https://www.t3xfer.com/identity/permissions">application permissions</a>
                    previously granted to client applications.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <p>
                    Here are links to the 
                    <a href="https://identityserver.github.io/Documentation">documentation</a>,
                    and <a href="https://github.com/identityserver/Thinktecture.IdentityServer3.Samples">ready to use samples</a>.
                </p>
            </div>
        </div>
    </div>
</body>
</html>

**Comment by leastprivilege** [comment]
When I open the solution

https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/tree/master/source/MVC%20Authentication

the API is on port 44321. So I don't see the issue.

VS might assign different port numbers to your project - are you running into that? If yes - feel free to add a comment to the walkthrough doc.

**Comment by lennane** [comment]
Perhaps I don't understand why the different port is used. My goal is to have each sample be able to be tested on a public server that I control. I was able to modify the CallApiController as follows and it now works with the Call Api(user) but not the Call Api(Client)

private async Task<string> CallApi(string token)
        {
            var client = new HttpClient();           
            client.SetBearerToken(token);
            // Original Code from GitHub
            // var json = await client.GetStringAsync("https://localhost:44321/identity");
            // return JArray.Parse(json).ToString();            

            // However it only works for "user" info and not "client" 
            // URI corrected by adding /connect/userinfo and changed to host = www.t3xfer.com
            var json = await client.GetStringAsync("https://"+host+"/identity/connect/userinfo");
            return Newtonsoft.Json.Linq.JObject.Parse(json).ToString(Formatting.Indented);
        }

**Comment by lennane** [comment]
I think I understand why there were two different ports. 
Let me know if this is correct
You placed the MVC Authentication and the Api on two different ports so that you could directly call to the Api project by using a URI with the Api's number, that is set up during the Startup dur the Api project's initialization.
I dont think that is a good fit for an IIS website that uses only 443. 
Any input you could give would be appreciated.  
Thanks for all your help.

**Comment by leastprivilege** [comment]
If everything runs on a single port - well then run on a single port ;) It's just HTTP.
