### ISSUE TITLE
Checking requested scopes in UserService

### ISSUE THREAD

**Issue by ChrisVinall** [IdentityServer/IdentityServer3#1049]
I'm using idsrv in a scenario where some clients will not allow access until a user has registered and verified a mobile number, while other clients are happy to grant access without this requirement.

The logical thing to do would appear to be to define a scope, with clients then able to choose whether they request that scope. I'm using a custom user service that issues a partial login if a user logs in without a mobile number. Is there any way I can access the requested scopes from there and issue a full login if mobile number isn't requested, or some other way I can achieve this?

**Comment by leastprivilege** [comment]
Yea you don't have access to scopes in SignInMessage - but to clients ("some clients will not allow access until a user has registered and verified a mobile number, while other clients are happy to grant access without this requirement")

Or move the check to the application (by requesting the phone_numver_verified claim)
