### ISSUE TITLE
Custom Userservice - not only Password/Username but additional information on login screen

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1051]
Hello,

We intend to log in via Username, password and one another additional number provided on login screen.

Now IUserService 
AuthenticateLocalAsync has only Username and Password as parameters. but We need another parameter.

How can one cope with that?

**Comment by aosgo** [comment]
Would be interested in this too if we could pass additional parameters in.

**Comment by brockallen** [comment]
You can either 1) do partial logins, or 2) you can add a new input on your login page, inject the owin environment into your user service, then in your local authN method, read the form collection for the POST.

**Comment by benjaminadrom** [comment]
@brockallen you said 
" 2) you can add a new input on your login page, inject the owin environment into your user service, then in your local authN method, read the form collection for the POST."

1. Is this possible in the "AuthenticateLocalAsync"-Method? 
2. How can we get the Post values from there?
3. Do we inject the owin environment into the "AuthenticateLocalAsync"-Method or into the whole class "public class LocalRegistrationUserService : UserServiceBase ..."
Thank you
