### ISSUE TITLE
WsFederation error - No Signin id passed

### ISSUE THREAD

**Issue by gaspode44** [IdentityServer/IdentityServer3#1052]
I've followed the MVC walkthrough which worked as described with the internal identity provider, I then attempted to add external WsFederation provided by an existing STS into the mix.

I followed the instructions on the wiki for incorporating the ms owin WsFEderation middleware - my test app now correctly redirects to the STS which authenticates, builds a form which is posted back to the self hosted identity server but it displays an error:

"There was an error determining which application you are signing into. Return to the application and try again" - underneath there is a request id which looks like a guid but its mostly zeros?

When I check the log the AuthenticationController reports "No signin id passed"

I assume that our existing STS is failing to post back this signin id? - any ideas on what it should be doing?

Also unless I specify a Wreply property for the WsFederationOptions then no attempt is made to signing - what should the correct reply value be?

**Comment by gaspode44** [comment]
Additional information - I've since noticed that although I see the "error determining which application" message on the /identity/callback route
If I then navigate to the original protected route (/home/about in my case) then I find I have been authenticated and my claims which were populated by the STS are displayed

Any ideas?

**Comment by leastprivilege** [comment]
The sampels repo has a minimal ws-fed sample. Try to make that work first then go from there.

**Comment by gaspode44** [comment]
thanks - I have the following samples running
SelfHost (InMem with WS-Fed)
MvcOwinWsFederation

I can browse the client sample and login ok

I then tried to get the following working

An MVC app hosting IdentityServer on /identity as per the MvcGettingStarted walkthrough
That IdSrv is configured to have the SelfHost (InMem with WS-Fed) hosted WsFed as an identity provider (I added the MVC app as a relying party to the sample)

I noticed that the relying party config has the root host as a reply url - so I added the same - as before I'm redirected to the WsFed endpoint (from the sample) , I authenticate and am redirected back to the root - and it appears I'm not signed in?

In the this scenario what should be the reply uri be set to in the WsFed relying party config?

**Comment by leastprivilege** [comment]
replyUrl must be under /identity.

Why do you want to run IdSrv **inside** your MVC app - it is recommended to separate clients from idsrv.

**Comment by gaspode44** [comment]
I guess because the samples lead you down the route of hosting the IdSrv inside a host MVC app?

Are you suggesting it would be easier to build something more like this:

MVC app & Web API client  ----> IdSvr(in MVC) ---->  WsFed Id Provider in form of existing STS

**Comment by leastprivilege** [comment]
Well - the first paragraph says:

"For simplicity we will host IdentityServer and the client in the same web application - this is probably not a very realistic scenario, but lets you get started without making it too complicated."

I recommend running IdSrv in a separate, dedicated web application.

**Comment by gaspode44** [comment]
Thanks Dominick - I now have a sample IdSvr which points to the self host WsFed sample and a separate MVC app as a client - that all works as expected, when I switch the id provider to our existing WsFed STS I can the "no signin id" error - I suspect its the behaviour of our STS but when I examine the traffic in fiddler I can't see an obvious difference? - is the signinid extracted from the form post back or the cookie?

**Comment by leastprivilege** [comment]
sorry - no idea. do the logs show anything unusual?

**Comment by gaspode44** [comment]
Here is a section of the log after the callback from our STS

```
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Message='Authentication', Operation=DefaultHttpControllerSelector.SelectController
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Message='Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController', Operation=DefaultHttpControllerActivator.Create
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Message='Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController', Operation=HttpControllerDescriptor.CreateController
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Message='Selected action 'LoginExternalCallback(String error)'', Operation=ApiControllerActionSelector.SelectAction
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Message='The authentication filter did not encounter an error or set a principal.', Operation=HostAuthenticationAttribute.AuthenticateAsync
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Operation=HostAuthenticationAttribute.ChallengeAsync
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Operation=PreventUnsupportedRequestMediaTypesAttribute.OnAuthorizationAsync
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Message='Parameter 'error' bound to the value 'null'', Operation=ModelBinderParameterBinding.ExecuteBindingAsync
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Message='Model state is valid. Values: error=null', Operation=HttpActionBinding.ExecuteBindingAsync
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Operation=SecurityHeadersAttribute.OnActionExecutingAsync
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Operation=NoCacheAttribute.OnActionExecutingAsync
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 11/03/2015 09:07:33 +00:00 -- Callback invoked from external identity provider
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 11/03/2015 09:07:33 +00:00 -- No signin id passed
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Message='Action returned 'Thinktecture.IdentityServer.Core.Results.ErrorActionResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Operation=ApiControllerActionInvoker.InvokeActionAsync, Status=200 (OK)
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Operation=NoCacheAttribute.OnActionExecutedAsync, Status=200 (OK)
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Operation=SecurityHeadersAttribute.OnActionExecutedAsync, Status=200 (OK)
Debug: [WebApi Diagnostics]: 11/03/2015 09:07:33 +00:00 -- Operation=AuthenticationController.ExecuteAsync, Status=200 (OK)```

It looks like the principal is not getting set? - is that then causing the signinid not to be populated?

As another test I took the same config used above in the identity provider configuration and added it to the MVC Owin WsFedersation client sample and it was able to use our STS to authenticate and display the claims it issued correctly - so I guess I'm missing something in the IdSvr configuration somewhere

**Comment by leastprivilege** [comment]
It looks like the signinid is lost - IIRC we roundtrip that as wctx in WS-Fed. 

What's your external WS-Fed provider? does it support wctx? You could also inspect the http traffic to see if the signin id gets sent back.

**Comment by gaspode44** [comment]
I can see in fiddler that the wctx is being passed and its value begins WsFedOwinState= then encoded string - how should I decode to inspect?

**Comment by gaspode44** [comment]
Ok more information I added a MessageReveived notification in the id provider and was able to inspect the owin authentication properties and its dictionary - see image below the watch window is on the dictionary and highlights the signin key/value

It shows that the signin id is present in the wctx thats round tripped by our STS (which is in-house developed asp.net mvc based and works correctly with the client owin ws fed sample)

Given that signin is present in the callback  - any other reason why the authenticationcontroller is reporting it can't find it

The config is to callback to a url: /identity/callbackfromoursts
this is passed in the body of the POST the wa, wresult, wctx properties
the response to this is a 302 to identity/callback - this GET doesn;t include those properties but they are there in the Referer propertie - this looks like the same redirect when I substitute the self host wsfed sample?

![image](https://cloud.githubusercontent.com/assets/1748722/6596076/983771be-c7e8-11e4-9f76-e44aa96745ca.png)

**Comment by leastprivilege** [comment]
and is the cookie with a matching signin id present as well?

**Comment by gaspode44** [comment]
Which cookie is that in - IdSvr.WsFedTracking ?

I'm looking for the cookie thats presented when the browser posts to my /identity/mycallback endpoint?

If its not being presented which part of the chain sets it?

**Comment by gaspode44** [comment]
ok looks like the cookie SignInMessage.7099ef6d561901c1d0e1ee687d883042 is being presented back at the callback but I still get this in the log - no signin id set?

```
Debug: [HTTP Logging]: 11/03/2015 15:36:56 +00:00 -- HTTP Request
{
  "Method": {
    "Method": "GET"
  },
  "Url": "https://localhost:44300/identity/callback",
  "Headers": [
    {
      "Key": "Cache-Control",
      "Value": [
        "no-cache"
      ]
    },
    {
      "Key": "Connection",
      "Value": [
        "Keep-Alive"
      ]
    },
    {
      "Key": "Accept",
      "Value": [
        "text/html",
        "application/xhtml+xml",
        "*/*"
      ]
    },
    {
      "Key": "Accept-Encoding",
      "Value": [
        "gzip",
        "deflate"
      ]
    },
    {
      "Key": "Accept-Language",
      "Value": [
        "en-GB"
      ]
    },
    {
      "Key": "Cookie",
      "Value": [
        "SignInMessage.7099ef6d561901c1d0e1ee687d883042=HoLPKyNx3shQcZdqCfv5lRI-3ldOISsdVOgdgp_6tWjD9Wq4YuqiqR2qLaEqjFEVuGPrgsmXPiKAg67e0mbvD28kp02roXErS7pdn1YroIEUBTT-0mCJt-iGKSVw9_B3bQhpXEx6Hqeu2nW3nvU_rz5TGcUV5Y9dKsj7FFdOeHRwcu9er-QxL9wq0biA0ajAi-BlLL6EMhDhMkV6G6jgw8tmKHbE0GnKYbVelEVF9KsTYu26lSyPi22PP6eyP9MRPjmFvoQZaLBLUX2XjylavxFRDEXdnX5X5hOdeIkSv6ZutowPQFr9QN6tnhlwCdPHkJklOoc4QVrVQw63ZqA3uyirP3S_KbFzKKADaY0OuBwRDOUy8VF4yH2z3JKxPGvZtGBWZjdD1mzVSRf17x3XwpYyTNBruv8MgPqztm9cPmxtS-XMJbeT-A7V80KSKW2KvzBKFdjMnH3WZq-4pkhdv10P-WhL70aiCQM9609MpIV_JZLHKNVxY8te9MB02nNIQz-jnZkuXS2bEj0yRpQ3fJbAEAWp9d15SspjDp1mQFXPVjws7LD3Wzx7m3eMnuwIR_nkfMJTqe70xwJ92JNbkY2OGub8Gws25APe4ZHj3lSRd4gMHP9SKvqYXLz7dy-iL-Sf4bFEz-6o3_YVjsB001JR9zzDSzk97MJzSocVDsjb595TX7fCanfCIvAynlLUo2K3NyLzkuJ06kkAd5UIZol-D4lenqlmxEJxSxiVuCZacTfcglpMAPRLnQbAHNBLeLIADB-LPQJCIh9xVE6qYZx1FtyvTZMeWP5ARa2WVhh33hHH88Q3DZ2OXCV4yEZke0K5iQZRBP67EmMdwIV9GF-1r6K9khYGw9qHuoVXy7MvUKF4R_KcNpWRXR-uMQMTTvaP0qYN1sFcpqb7A12BZA; idsrv.xsrf=8C_i29VV9fC2wG2XRUN02MrhyNkbmejLCwElOS1tkGinNwPYm1SHa3hH1ojuRyH5I61daHM_uT7bfuajbTW1XU-3o98mYUDrhDnmvRDr-LU; OpenIdConnect.nonce.OpenIdConnect=WEcxQko3SW9relYxZC1Kdk9TYkcwY0VTYU5adWNqY0NoZTRLd2NSbnJ4RVVpQ0ZJN0ZIYUNRdkUxT3FzTHFSUW1Da2tDbnNDeG1zREF5aTZ3aEhNY2JKY3V3elNPWnRnTHp1ZTBoME16S1h5TU1NcVpLeHprU3BPelVLYS1ORjlhUThFYzVLaEhWZGpTbmQzOTMxbnNsVWJ0RXJzTTZ0U0l4ZHliTDk2WFZTVzV3dFFqX2FNMnh6X2pJaHpHa1QxbFFmM2tNNEdDQkYyMXdVbWJ5UjBNVHJ3STI1Qk44blhzWTNFUWdScFY3dw%3D%3D; SsoToken=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U2VjdXJpdHlDb250ZXh0VG9rZW4gcDE6SWQ9Il85OGI4YTYwMi0wYzNmLTQ3YWUtYWMwYi04NGViNGRlMjhjMzEtREU2RDcxQTM2NTI4REQzOTY5MjlERUQ2MDYxRTJGOEUiIHhtbG5zOnAxPSJodHRwOi8vZG9jcy5vYXNpcy1vcGVuLm9yZy93c3MvMjAwNC8wMS9vYXNpcy0yMDA0MDEtd3NzLXdzc2VjdXJpdHktdXRpbGl0eS0xLjAueHNkIiB4bWxucz0iaHR0cDovL2RvY3Mub2FzaXMtb3Blbi5vcmcvd3Mtc3gvd3Mtc2VjdXJlY29udmVyc2F0aW9uLzIwMDUxMiI+PElkZW50aWZpZXI+dXJuOnV1aWQ6NGZiODg2MmEtYWEwNi00MThmLTlmNDMtNGJjMDkzYjcwM2JmPC9JZGVudGlmaWVyPjxDb29raWUgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwNi8wNS9zZWN1cml0eSI+QVFBQUFOQ01uZDhCRmRFUmpIb0F3RS9DbCtzQkFBQUEzUWVxbXZCTHAwYUcxTmJodUZaOER3QUFBQUFDQUFBQUFBQURaZ0FBd0FBQUFCQUFBQUNNQmZEOS8wTmNmSFFKaWpISjBWS21BQUFBQUFTQUFBQ2dBQUFBRUFBQUFLeURlN250TjFHUVE3dXdTT1I4d0c4b0FnQUFoSjNQOXFXN1l0eXgveVV4aDNVaGhNY2ZSK3JFcFdDRUR0bHBhc3F3R2E4VE1ZYW1DengvS0JmN09ESForM3hmM1lyVGpKM1JybUFHSWd6VTliWk8vNXJ0NWtGNVdlY3pCMU54ZEkzVmRIMzJYdi96T24xMU1EZlQySUl1Z1I3NmdBa0FtRE9JMnR0R0h5QlJQSlY0M25IYVRqMlVwbGlJOUNnVzB4NkMvZXU5dFFlZnNURUlWTU4vRkF4elZiYmN5MXAzbEN6WU56STVMNHBWZU4yb2kzbS95VkNEWjRtUXRzSWNRR1lvQmM5MXF3M2N4V1BMN0tjZHZNNk8yZEFVYXkrOFRSckNVT2pKWkUwN3JYcnNjU1VjcnJocmNyQU1TQk4wRXVCQktRSUFoajE3S0RMRW1URk1RNXRvNHZGdWZyelBNS2x0dk13eWU3ckNpL0dUQ2ZOVWNpV0pQNS9RQlR2SWhIWFJQQm9qRVNxbmZzUWZHcWc5RVFWSDNEVWVOSDVadGZRYkRFLytmMks0SlRwdGNnbVI5azR5TmhzbXY0MjJPbmw4WmZaZ3N2TVdXS3M5cUxkbjVOd2Fxd3RsTGZhQnE2cEppQkw2VDdQdFVCQXVnVzRnTHQxL3ZnbFZlMVVtVWh4NUg0SjF1V2w3U00ra0s3MERwRDF0Y0gyc3pmR3VEN1o0bjh5SW01V1B3QllMeTlhRHoybFdZdUltTG0zREJBbGxuWFhLK1BjcjJYSVBUUVpoWGZoTGdySU52aXhETXFqdUtEN3prc0N2V0pPVzg4ZjBMSlFkYjJhK3FhamdLY2hXMFB2L1cwdkUvdE5IVk5ZbndTYWJVYU0wRm5OcnQzNEp0UDhIS3l2UEFGcUdQbzFIdURUcFduR0RaTTd0cTMyWnYvMDVIQkFjc2JaSTNzQVpFNEhlbTN4Z3JFdkYvZjVST1NCN2sySjFqY1pLUWRpejY2TFl5Vlg1RkFBQUFGQmRKOGRnbU5JbGpydHZuLzA4bG15MGFOVmQ8L0Nvb2tpZT48L1NlY3VyaXR5Q29udGV4dFRva2VuPg==; .AspNet.Cookies=vkst3um5Ycdx9KZlyiZLmySklZQcEdaOtHl1sG2MaWoDlHfaIuUzrxLUssJByZBUgQBUNqVLnmB3zgQXeyAJK6SFjz6TS9NFNVHDr5w-HsZW5v1QBMNG5ppWkluCvLtFGvy_HHsiZhLWZV9QdNIsvqPJc--m0UMYENv2dLwOHDE4VUyLib5MRRW6BJHZi1s-6cR7lXTMwytwst9V0qWA45-MgEQGqaKC-CauF6i4gXuBi92NJhznO0gWeytKcTGBEpP8XB6enJWaj_rNLELuAU1a7MS8gGMcqXZYeA5-v28MbYiHf5JkzZ_1AznqMvlYr5T8zbq24KNKkyV58h-LzVGgobJh6IyjkT3YncE5YxWoGPNBECfBi2XXIytt1DZzlpam7g7eRcAbyjZK1ZOzdslLWsVQ7GqEmkboEuzmkPYZlXEMvL-GdKh-F5Sil7fT_5nwWzrXVC0QykYjIrxQdUIcnsCQFPg7gqy3dACQgivK6-8_LsUNvFl_uE6HFH7CvaEBF8D_skqAZkqyDXxTvw"
      ]
    },
    {
      "Key": "Host",
      "Value": [
        "localhost:44300"
      ]
    },
    {
      "Key": "Referer",
      "Value": [
        "http://localhost:2589/Signin/Integrated?wtrealm=https%3a%2f%2flocalhost%3a44300%2f&wctx=WsFedOwinState%3dnRRfGZnLSSn69MwnHVkhsr3E4SD74ZmhYhtKtph-OwRsvE0y3y2lgJbTheD9HmufgZ4xPwBggLslLsNn9qzVnBy6HLBdfA7VM1MCU2O6K66tKAiAw3HMe7riP4v-_7UgH5ubocL7R1GzaKEtcQTPM89NeciTdi-YUWBWOw9sqflJrpx3XyMxww24LlHvkt4cL9269V4LeSS2azB4EAzrJ_Vaxfk9noylB-dBqYQZf7I&wa=wsignin1.0"
      ]
    },
    {
      "Key": "User-Agent",
      "Value": [
        "Mozilla/5.0",
        "(Windows NT 6.1; WOW64; Trident/7.0; rv:11.0)",
        "like",
        "Gecko"
      ]
    },
    {
      "Key": "DNT",
      "Value": [
        "1"
      ]
    }
  ],
  "Body": ""
}
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Message='Authentication', Operation=DefaultHttpControllerSelector.SelectController
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Message='Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController', Operation=DefaultHttpControllerActivator.Create
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Message='Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController', Operation=HttpControllerDescriptor.CreateController
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Message='Selected action 'LoginExternalCallback(String error)'', Operation=ApiControllerActionSelector.SelectAction
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Message='The authentication filter did not encounter an error or set a principal.', Operation=HostAuthenticationAttribute.AuthenticateAsync
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Operation=HostAuthenticationAttribute.ChallengeAsync
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Operation=PreventUnsupportedRequestMediaTypesAttribute.OnAuthorizationAsync
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Message='Parameter 'error' bound to the value 'null'', Operation=ModelBinderParameterBinding.ExecuteBindingAsync
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Message='Model state is valid. Values: error=null', Operation=HttpActionBinding.ExecuteBindingAsync
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Operation=SecurityHeadersAttribute.OnActionExecutingAsync
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Operation=NoCacheAttribute.OnActionExecutingAsync
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 11/03/2015 15:36:56 +00:00 -- Callback invoked from external identity provider
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 11/03/2015 15:36:56 +00:00 -- No signin id passed
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Message='Action returned 'Thinktecture.IdentityServer.Core.Results.ErrorActionResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Operation=ApiControllerActionInvoker.InvokeActionAsync, Status=200 (OK)
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Operation=NoCacheAttribute.OnActionExecutedAsync, Status=200 (OK)
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Operation=SecurityHeadersAttribute.OnActionExecutedAsync, Status=200 (OK)
Debug: [WebApi Diagnostics]: 11/03/2015 15:36:56 +00:00 -- Operation=AuthenticationController.ExecuteAsync, Status=200 (OK)
```

**Comment by gaspode44** [comment]
ok more information - debugging it seems the problem is with this call to context.Authentication.AuthenticateAsync(authenticationType); below - the value of authenticationType is "idsrv.external" but it returns null

Any pointers as to what is missing in configuration that would cause that?


```
static async Task<Microsoft.Owin.Security.AuthenticateResult> GetAuthenticationFrom(this IOwinContext context, string authenticationType)
        {
            if (context == null) throw new ArgumentNullException("context");
            if (authenticationType.IsMissing()) throw new ArgumentNullException("authenticationType");
            
            return await context.Authentication.AuthenticateAsync(authenticationType);
        }
```

**Comment by glatzert** [comment]
We got a similar Problem here. I even tried the self host sample with InMemoryUsers only and get similar results (it's not about the signin id then, but about a valid but not accepted Login of Bob or Alice).
With the source code of the identity server we tracked the problem and could not see any error in the idsrv itself, but appearantly the call to `context.Authentication.SignIn(props, id);` (AuthenticationController Line 647) does not result in the necessary cookies.
In my opinion this is a problem with cookie handling, which is mentioned here: https://katanaproject.codeplex.com/workitem/197

An interesting side note: the problem is not 100% reproducible. So some authentication attempts succeed. While an attempt from a different machine or a different browser will fail.

We'd really like to use the IdentityServer for OAuth, but currently cannot use it on neither IIS nor Selfhost.

**Comment by leastprivilege** [comment]
We have tested with both ADFS and WIF based WS-Fed token services. No issues.

Are you on the latest version? what claims do your token services emit?

**Comment by gaspode44** [comment]
Ok finally got to the bottom of this last night - as suspected it was a problem in the way I was configuring the identity provider for our STS

In order to try and "just get it working" I attempted to switch off the token validation by using this code

```
SignInAsAuthenticationType = signInAsType,
TokenValidationParameters =
                                   new TokenValidationParameters()
                                       {
                                          ValidateIssuerSigningKey =  false,
                                               
                                           ValidateAudience = false,
                                           ValidateIssuer = false                                           
                                       },

```

What I hadn't appreciated was that creating the TokenValidationParameters property without setting its AuthenticationType nulls the SigninAsAuthenticationType set on the line above - when looking at the source on codeplex  we found that the SigninAsAuthenticationType property just gets/sets the TokenValidationParameters.AuthenticationType property

The resulted in this configuration picking up the default value of "Cookies" which meant that IdSvr could never find the correct response as its looking for "idsvr.external"

my shortcut instead of just correctly configuring the cert cost me many many hours!!

This was all an issue with katana wsfederation - nothing to do with Identity Server

Not sure if there was anything that could be done in logging etc that would have helped me find it quicker...

**Comment by leastprivilege** [comment]
"my shortcut instead of just correctly configuring the cert cost me many many hours!!"

Can I quote that?

Glad you have it working!

**Comment by glatzert** [comment]
So we are still stuck with the InMemoryUser and Authentication as a whole. I made two Fiddler Session from different machines (one working, one not working) and threw it into a filebin: http://filebin.ca/1ugUt2AY7ZKl I also appended the Owin Startup File. Perhaps you have the time to take a look at it - and possibly you see the error on first glance..

**Comment by leastprivilege** [comment]
also try this
https://katanaproject.codeplex.com/wikipage?title=Debugging&referringTitle=Documentation

**Comment by gaspode44** [comment]
yes you can quote me :) - thanks for your help and patience!

**Comment by glatzert** [comment]
I tried the Katana Debug Trace - it created a file and wrote something about not beeing able to unprotect a ticket. This error vanished after I reset to X509DataProtector.

What we are seeing is that the first request after a Server restart succeeds and subsequent request from different machines can not succeed (same machine different browser works as of now).

I created two NLog Traces of the IdSrv. Look for an #### as separator: http://pastebin.com/PNWzgenC

**Comment by leastprivilege** [comment]
any updates?

**Comment by glatzert** [comment]
Yes - just did some more tests and made some changes:
I changed the Location of the application from subapplication to dedicated application / site in IIS and did not call it "oauth" in the app.Map(). And yay - i can sign on mutliple persons :)
I have no idea, why it works now, but it does and that is pretty fine :+1: 

I'll do some more tests, but i'm optimistic.
Thanks for your support, come over for a beer, if you are near Mainz.

**Comment by leastprivilege** [comment]
great. I live in Heidelberg - so be prepared ;)

**Comment by daluas** [comment]
@richardjharding: We have the same issue. What do you mean by: my shortcut instead of just correctly configuring the cert cost me many many hours
How should the cert be configured?
