### ISSUE TITLE
WepApi dbcontext is hit twice when using TokenManager in AngularJS app

### ISSUE THREAD

**Issue by iltera** [IdentityServer/IdentityServer3#1055]
Besides the issue #1047, I have another issue. I realized that when I include the access_token to the request (using TokenManager) made to the (secured or non-secured) webapi controller, the dbcontext is hit twice. In the first hit, I get
(ClaimsPrincipal)Thread.CurrentPrincipal.Identity.IsAuthorized => false
On the second one, I see the below result true and everything works as expected.
It is not affecting how the app works, though. In the browser console log I see only one request made to the webapi, so I think it has something to do with the token validation on the server side (or may be not - not sure).

I wasn't even aware of it until I put a breakpoint in the dbcontext method. But it's interesting since that's not the expected behaviour.

What is the logical exlanation for this? What is happening behind the scienes that we need to be aware of?

**Comment by leastprivilege** [comment]
any updates?

**Comment by iltera** [comment]
No, nothing new. App works normal but when debugging the controller, it bugs me to go through all the methods twice. If I remove the authorize attribute on the controller and remove the access_token from the request header, it works once and successfully. And I probably should have mentioned that it's an angular app with EF in WebApi side I am seeing that behaviour. Sample apps don't have that behaviour as they don't involve EF in WebApi, but just return simple claims. Probably should debug sample apps by involving a db and EF in them and report back.

**Comment by brockallen** [comment]
Is this a CORS issue? Is your API on a different origin than the client?

**Comment by johnkors** [comment]
What kind of Authorize attribute? Custom or the default? ResourceAuthorize? 

If custom , what kind of logic do you have?

**Comment by brockallen** [comment]
any updates to investigating if it's a CORS issue?

**Comment by iltera** [comment]
@brockallen, yes, my API was on a different domain and set all the CORS attributes to * at that time.

@johnkors, it's the mvc authorize attribute I was using. But it was the same result with ResourceAuthorization attribute.

You say that when using API which is on another domain, multiple hit on the api controllers is the expected behaviour?

**Comment by brockallen** [comment]
Perhaps, but what I was asking if the multiple hits is due to CORS -- you need to trace the HTTP requests to see if they are CORS requests that are causing your DbContext to be created multiple times.

**Comment by iltera** [comment]
It's been a few weeks. At the time, I remember that I checked the connections from the browser console logs and there were no multiple requests. I didn't check with fiddler though. I sure will check again with fiddler and write back as soon as I find some free time. Thank you!

**Comment by brockallen** [comment]
I'll close this for now. If you need to reopen, please do so.
