### ISSUE TITLE
[Question] Is it possible to get the original authorise return url into the login view?

### ISSUE THREAD

**Issue by rayph** [IdentityServer/IdentityServer3#1058]
Is there anyway to obtain the raw authorisation return url for the login page (using a custom view service)?

I.e.: The return url available in the SignInMessage and forwarded to the view service is the intermediate return url with owin context bits in it, which is not really what I'm looking for.

I would like to forward the return url into a self-registration process so that the user ultimately ends up signed in (using a custom pre-authenticate) and finally having landed where they were trying to get to in the first place rather, and not some default location.

Looking at the code it seems I would have to unpack the SignInMessage cookie data in order to reach it... or... is there a nicer way to get that url into the login view?

**Comment by brockallen** [comment]
You can pass it as a custom claim in your `AuthorizeResult` to your partial login.

**Comment by rayph** [comment]
Not sure I follow, 

Lets say I want to render links (i.e. to register) on a custom login page with a return url query string parameter that would ultimately allow the user to get back to where they came from. 

This case is for when the user ends up on a login page due to an authorize attribute but then opts to register and create an account before resuming with the authorize redirect. We have areas in an RP that simply require the user to login or register.

If I return something in PreAuthN, then the user wouldn't see the login page at all and instead would be pre-authenticated. It doesn't quite fit - or am I misunderstanding something?

**Comment by brockallen** [comment]
If you use a login page link, then as a query string is the signin query string param you can pass back to the login page to return to the login process. CHeck the login page links in the docs:

https://identityserver.github.io/Documentation/docs/configuration/authenticationOptions.html
