### ISSUE TITLE
CORS not working for /userinfo

### ISSUE THREAD

**Issue by protoforge** [IdentityServer/IdentityServer3#1059]
I'm working with the OAuthJS sample with two servers, idsvr.local and clsvr.local.  I'm receiving a 'Problem Getting Token : Network error' after authenticating and granting consent.

After acknowledging the consent screen I'm redirected back to the client application's callback.html page.  Here's a synopsis of the traffic:

- GET https://idsvr.local/ID/.well-known/openid-configuration

	HTTP/1.1 200 OK
	Cache-Control: private
	Content-Length: 1035
	Content-Type: application/json; charset=utf-8
	Server: Microsoft-IIS/8.5
	Access-Control-Allow-Origin: https://clsvr.local
	X-AspNet-Version: 4.0.30319
	X-Powered-By: ASP.NET
	Date: Wed, 11 Mar 2015 04:00:40 GMT

- GET https://idsvr.local/ID/.well-known/jwks

	HTTP/1.1 200 OK
	Cache-Control: private
	Content-Length: 2495
	Content-Type: application/json; charset=utf-8
	Server: Microsoft-IIS/8.5
	Access-Control-Allow-Origin: https://clsvr.local
	X-AspNet-Version: 4.0.30319
	X-Powered-By: ASP.NET
	Date: Wed, 11 Mar 2015 04:00:40 GMT

- OPTIONS https://idsvr.local/ID/connect/userinfo  

	HTTP/1.1 200 OK
	Allow: OPTIONS, TRACE, GET, HEAD, POST
	Server: Microsoft-IIS/8.5
	Public: OPTIONS, TRACE, GET, HEAD, POST
	X-Powered-By: ASP.NET
	Date: Wed, 11 Mar 2015 04:00:40 GMT
	Content-Length: 0

No Access-Control-Allow-Origin is in the response.

The browser javascript console reports this:

*XMLHttpRequest cannot load https://idsvr.local/ID/connect/userinfo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://clsvr.local' is therefore not allowed access.*

I'm using the nuget 1.2.1 version

**Comment by protoforge** [comment]
Setting 'load_user_profile : false' in the callback.html allows the sample to work, but I'll likely want more user information soon.

**Comment by leastprivilege** [comment]
CORS should work on the userinfo endpoint - @brockallen can you double check?

**Comment by brockallen** [comment]
Yes, it works -- just needs to be enabled.

**Comment by protoforge** [comment]
> just needs to be enabled
I'm not sure what this is referring to.  If the user profile call is enabled in the sample client, a CORS error occurs.  Does something need enabled on the server?

**Comment by brockallen** [comment]
Yes. Check the CORS docs for identity server. 

-Brock

**Comment by protoforge** [comment]
Before asking, I had already tried implementing my own ICorsPolicyService service as well as enabling what I think is the now deprecated CorsPolicy.AllowAll option.

It's probably unrelated, but this problem disappeared after I implemented my own UserStore. The OPTIONS call seems to work now.  I haven't gone back to re-validate using the in-memory user store..
