### ISSUE TITLE
Add Refresh Token and expiration date of token to Web Api Response header.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3#1061]
I want to have Refresh Token and expiration date of token in Angular app and use of those to get a refresh token via an MVC controller(Hybrid Flow).
Is is possible to attach Refresh Token to the api response?
I would not use Implicit Fow in the js app.
Thanks

**Comment by brockallen** [comment]
Can you elaborate?

**Comment by mikeandersun** [comment]
I need to get the access token in silent from js app, I know we can do this with Implicit Flow with Iframe. 
But I would not to expose some information (e.g client, scopes ,...) in the js app. 
If I have refresh token and expire date of token get new access token via call an MVC action controller.
I think I need some tweaks in IdentityServerBearerTokenAuthenticationOptions (may be add a  OAuthBearerAuthenticationProvider) .
Best,

**Comment by brockallen** [comment]
I assume you're using the TokenManager? If so, the scopes are already provided. If you're on an older version, check the dev branch.

**Comment by mikeandersun** [comment]
No, I wouldn't use TokenManager, but I want to get access token in MVC part of my application. 
I have a an action in my mvc side and want to send refresh token to it and get token from Idsrv and back it to js app, Is save in the LocalStorate  and control expiration of token via a timer.

**Comment by brockallen** [comment]
If you're using the implicit flow, then the scopes, and expires_in are part of the response params. Is this not what you're looking for? I'm still confused.

**Comment by mikeandersun** [comment]
I use Hybrid Flow. All I talk about it is that I prefer to communicate with Idsrv in MVC part of my client application and don't let the JS client part know about IdSrv .
The js part just send some parameters(e.g refresh-token ) to MVC and i have other info about the client and send an authorization request to IdSrv and get a token from it and give it to JS part of app.
I want to image angularjs part and MVC part as one client app. 
Thanks in advance

**Comment by brockallen** [comment]
So then use code flow if you don't want the JS to do any of the work. Your server side code can render the access token back to your JS.

**Comment by mikeandersun** [comment]
Ok, I need refresh token to renew the token. It come come from the JS.
Using a time to get new token is acceptable approach?

**Comment by brockallen** [comment]
I'd suggest looking over the OAuth2 spec to understand the flows.
