### ISSUE TITLE
Beginning IdServ

### ISSUE THREAD

**Issue by airomero** [IdentityServer/IdentityServer3#1062]
Hello, i'm starting with IdServer. What i haven´t found in documentation is a tutorial on how to use it (the functionalities of IdSrv). Is it possible to combine with AD (or ADFS)? What is the recomended implementation for the clients (EF, MembershipReboot, AspNetIdentity, Custom).
I hope this is the right place for this question....if it is not, please tell me where.

Thanks

**Comment by sandeepgaikwad** [comment]
Not sure what exactly you are looking for, but the samples have it all.
Even if you download,compile and run the Thinktecture IdentityServer3 code, that makes the running application as your Identity server.
If you run the 'EntityFramework ' sample that makes your IdSvr with EE

Yes, I think you can combine it with ADFS (never tried though)

Hope that helps

**Comment by brockallen** [comment]
In addition to what @sandeepgaikwad indicates... IdSvr is meant to be very flexible, so many of the answers are "yes and it depends".

**Comment by airomero** [comment]
Guys thanks, the last time i saw IdSvr it had UI to customize it......as far as i saw in the samples now it's configured through code, is that right? I'm having troubles on deciding the way authentication works in my apps and i wanted to be able to authenticate against AD or use a custom authentication....in other words a mixed solution. But i see this a little complicated right now and i think that as i'm inside an organization with AD, i'll use ADFS right now and then see alternatives like IdSvr.
Thanks a lot you guys and sorry to have bothered you.

**Comment by brockallen** [comment]
This is IdSvr3 (not IdSvr2) -- IdSvr3 is a total rewrite due to OIDC being the protocol we target (rather than WS-*).
