### ISSUE TITLE
IdSrv for older browsers (IE7/8)

### ISSUE THREAD

**Issue by sania13** [IdentityServer/IdentityServer3#1063]
Do you think IdSrv would work for older browsers (IE7/8) with custom implementation of IViewService interface? 

Anyone done that?

**Comment by johnkors** [comment]
you're in total control over the html, so yes - you can make it do whatever you want - even support IE7 :)

**Comment by jageall** [comment]
Yes, we have and yes it does, but be careful about avoiding cors. 



-----Original Message-----
