### ISSUE TITLE
[Question] Is it necessary to store StandardScopes in EF ScopeStore?

### ISSUE THREAD

**Issue by DarthZar** [IdentityServer/IdentityServer3#1064]
Is it possible to store custom scopes in EF using factory.RegisterScopeStore(efConfig) without having to manually add all the predefined StandardScopes you get from StandardScopes.All to your EF store?

**Comment by brockallen** [comment]
You could implement a scope store that aggregates from EF and in-memory.

**Comment by slafave** [comment]
Thanks for the suggestion, I will plan to do that.
