### ISSUE TITLE
Question about ViewService customization

### ISSUE THREAD

**Issue by protoforge** [IdentityServer/IdentityServer3#1066]
I have a use-case that requires modification of the available login options based on the specific client that is authenticating.

Examples: 
Client A - acme.mydomain.com wants our native authentication (a local userstore), Google, and Microsoft
Client B - foobar.mydomain.com only wants to use their ADFS site
Client C - silly.mydomain.com only wants the native userstore
Client D - insane.mydomain.com wants to use their ADFS site as well as our native userstore
etc

- Consent will likely never be required as it's our identity server and application(s).
- The login pages (the ViewService) will need skinned to match the styling of the client application.  

Customizing the view, or only portions of the view seems obvious, but I'm wondering if there are any other solutions I'm overlooking.

Is the solution discussed in https://github.com/IdentityServer/IdentityServer3/issues/645 the best option? Other suggestions?

Thanks!

**Comment by leastprivilege** [comment]
The Client has a list of allowed provider (IdentityProviderRestrictions) and AllowLocalLogin. Check the docs.

**Comment by protoforge** [comment]
Thanks!  I see the IdentityProviderRestrictions and it seems to work as expected.  But, AllowLocalLogin seems to be missing (it's in the docs though).  

I see by https://github.com/IdentityServer/IdentityServer3/issues/753 that there were some issues?

Is it in a branch I'm not seeing?
