### ISSUE TITLE
Need to not enforce client authentication during custom grant (JWT Bearer Assertion)

### ISSUE THREAD

**Issue by khaledh** [IdentityServer/IdentityServer3#1067]
We're implementing the JWT Bearer assertion authorization grant as defined in [draft-ietf-oauth-jwt-bearer](https://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer) using a custom grant in IdSrv3. Our scenario does not enforce client authentication in this grant, which is optional according to section 2.1 of the jwt bearer spec:

    Authentication of the client is optional, as described in
    Section 3.2.1 of OAuth 2.0 [RFC6749] and consequently, the
    "client_id" is only needed when a form of client authentication that
    relies on the parameter is used.
    
    The following example demonstrates an Access Token Request with a JWT
    as an authorization grant (with extra line breaks for display
    purposes only):
    
    POST /token.oauth2 HTTP/1.1
    Host: as.example.com
    Content-Type: application/x-www-form-urlencoded
    
    grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer
    &assertion=eyJhbGciOiJFUzI1NiJ9.
    eyJpc3Mi[...omitted for brevity...].
    J9l-ZhwP[...omitted for brevity...]

So as you see the example in the spec includes neither an `Authorization` header for Basic Auth nor the client_id/client_secret are present in the request body.

Unfortunately IdSrv3 enforces client authentication on the token endpoint, which conflicts with this part of the spec, and prevents us from completing our scenario properly.

Any thoughts on this?

**Comment by leastprivilege** [comment]
We do not allow anonymous access to the token endpoint - correct.

Create some dummy client credentials to get around that.

**Comment by khaledh** [comment]
But according to my understanding, there's nothing in the OAuth2 spec that says *every* client must be authenticated at the token endpoint. Section 3.2.1 (emphasis on *unauthenticated client* mine):

    Confidential clients or other clients issued client credentials MUST
    authenticate with the authorization server as described in
    Section 2.3 when making requests to the token endpoint.
    ...
    A client MAY use the "client_id" request parameter to identify itself
    when sending requests to the token endpoint.  In the
    "authorization_code" "grant_type" request to the token endpoint, an
    *unauthenticated client* MUST send its "client_id" to prevent itself
    from inadvertently accepting a code intended for a client with a
    different "client_id". ...

So is that your implementation *chooses* to be more strict than the spec, or are you interpreting the spec in a different way?

**Comment by leastprivilege** [comment]
We chose to implement it like that.

**Comment by khaledh** [comment]
OK cool. Do you have any pointers on what it will take to override the default behavior if we were to not enforce client authentication during a custom grant?

**Comment by brockallen** [comment]
Google issues a non-secret secret for those scenarios, so you could do the same -- as long as you're aware that the non-secret secret is not secret. *grin*

**Comment by leastprivilege** [comment]
You can't turn off client authentication. Feel free to use "not_a_secret" as the client secret.

**Comment by khaledh** [comment]
@brockallen I was just looking at Google's [Server to Server auth](https://developers.google.com/accounts/docs/OAuth2ServiceAccount#authorizingrequests) (switch to the HTTP/REST tab) and it seems they don't require the typical client authentication in this scenario; they rely on the `iss` claim inside the JWT token to identify the client (which is exactly what we're trying to do):

    Below is a raw dump of the HTTPS POST request used in an access token request:
    
    POST /oauth2/v3/token HTTP/1.1
    Host: www.googleapis.com
    Content-Type: application/x-www-form-urlencoded
    
    grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=eyJhi[...]7cqQ

**Comment by leastprivilege** [comment]
Again - IdentityServer requires client credentials. They can be dummy credentials - but this feature cannot be turned off.

**Comment by khaledh** [comment]
Thanks. I wasn't trying to keep the debate going. I was just responding to @brockallen's comment about Google issuing a "non-secret secret" by pointing out that Google does the jwt bearer grant without requiring the typical client authentication.

**Comment by khaledh** [comment]
Sorry to bug you again about this, but would you be open to turn `ClientValidator` into a default implementation of an `IClientValidator` interface? This would allow us to use DI to override the default behavior. It's also in line with the OAuth spec in that client password is not the only way to authenticate clients.

**Comment by leastprivilege** [comment]
OK - will look into it. But this would be v2 feature.

**Comment by leastprivilege** [comment]
Opened a new issue for that.

**Comment by khaledh** [comment]
That's great. Thanks for adding it to the roadmap.
