### ISSUE TITLE
How to get the user's access token

### ISSUE THREAD

**Issue by jsucupira** [IdentityServer/IdentityServer3#1069]
I was following the examples "Getting Started: MVC Authentication & Web APIs" It worked good for me, however I would like to be able to request the user access token without having to use the form to login.

I've tried some of the client examples like this without any success.

var oauthClient = new OAuth2Client(new Uri(Constants.TokenEndpoint), "mvc_service", "secret");
oauthClient.RequestClientCredentialsAsync("sampleApi");
TokenResponse oauthresult = oauthClient.RequestResourceOwnerPasswordAsync("bob", "secret", "sampleApi").Result;

The access token is always null.

Can anyone point me to an example, or give me a pointer on how to get it working?

Thank you,

**Comment by leastprivilege** [comment]
Check the error property. and turn on logging on the server.

**Comment by jsucupira** [comment]
The error that I get on the TokenResponse object is "unauthorized_client".
With loggin I got more details:
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 3/13/2015 6:46:09 PM +00:00 -- Client not authorized for resource owner flow

Would you know off-hand what is the settings I need to add to authorize this request?

I would appreciate any help.

**Comment by brockallen** [comment]
Change the `Flow` on the `Client` configuration to `ResourceOwner` if that's what your client type is.

**Comment by jsucupira** [comment]
That was it.  Thank you for the help.
