### ISSUE TITLE
How to configure IdentityServer for a web farm behind an F5?

### ISSUE THREAD

**Issue by slafave** [IdentityServer/IdentityServer3#1070]
We are hosting IdSrv on an IIS web farm behind an F5 for high-availability and load balancing.  What steps need to be taken to configure and optimize IdSrv for this configuration?

*F5 config*
* not using sticky sessions
* SSL terminates at the F5 public endpoint.
  * So F5-to-IIS is not SSL

*Here are the things I have noted so far*
1. Configure the machine keys as noted in #1029
2. Install the F5 SSL cert locally in the Windows Cert Store on each node to be able to reference the SSL keys
3. Set RequireSsl to false so the non-SSL F5-to-IIS traffic is accepted
4. Set PublicOrigin to the DNS of the F5 public SSL endpoint
5. Store Client, Scope, and Operational Data in EF
6. If we decide to cache results for client, scope, and user stores, consider writing a custom ICache to an L2 cache like NCache or Redis instead of using the default L1 in memory stores.

**Is there anything I am missing or that you would suggest in addition?**

Thanks!

**Comment by leastprivilege** [comment]
good points

2. Install the F5 SSL cert locally in the Windows Cert Store on each node to be able to reference the SSL keys

This is not necessary. Only the signing keys need to be available on the nodes.

**Comment by leastprivilege** [comment]
5. Store Client, Scope, and Operational Data in EF

clients/scopes only need to go to a DB if you want to be able to add/change them at runtime (without re-deploying)

operational data only needs to go to a DB if you use features like authorization codes, refresh tokens and reference tokens.

**Comment by slafave** [comment]
*Only the signing keys need to be available on the nodes.*

Understood.  For the moment, the X.509 signing cert is also the SSL cert.

Thanks for the feedback, I really appreciate it!

**Comment by leastprivilege** [comment]
I started a document - would be great if you could add some details while you go.

**Comment by slafave** [comment]
Sure, no problem.  We're in the early stages, we'll be rolling out over the next few months.  I'll add anything as we go.

Thanks!

**Comment by slafave** [comment]
The new web farms document mentions that "IdentityServer includes a data protector based on X.509 certificates (X509DataProtector) that you can set on the options class."

I can't find the X509DataProtector class.  Where is it located?

Thanks!

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/X509CertificateDataProtector.cs

**Comment by slafave** [comment]
Got it, thanks!

**Comment by tiljanssen** [comment]
I can't find the documentation page mentioned above (https://identityserver.github.io/Documentation/docs/advanced/webfarm.html)

Is it still available?

**Comment by brockallen** [comment]
https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html
