### ISSUE TITLE
IdToken, AccessToken, clientCookies, Idsrv Cookie life time

### ISSUE THREAD

**Issue by fahouassou** [IdentityServer/IdentityServer3#1071]
Hi,

I have an idsrv and a client accessing it to authenticate and authorize. I need to control the different life times.

I want per example to set that if the client exceed x times, he should be redirect to login page.

I saw many times that can be set either from the server : AccessTokenLifetime, IdentityTokenLifetime,  CookieOptions = { ExpireTimeSpan = TimeSpan.FromMinutes(i), SlidingExpiration = false }

or frm the client: max_age, CookieAuthenticationOptions= { ExpireTimeSpan = TimeSpan.FromMinutes(y), SlidingExpiration = false }

Thanks

**Comment by leastprivilege** [comment]
Yes - they all control different things. That's probably worth a documentation page. Feel free to open an issue for that in the docs repo.
