### ISSUE TITLE
Suppress Default host authentication

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/IdentityServer3#1072]
I am having a very strange problem with SuppressDefaultHostAuthentication.  My angular app is correctly passing the Bearer token to my api, but unless I comment out config.SupressDefaultHostAuthentication my ClaimsPrincipal is always anonymous.

Has anyone else had this problem before?  Here is my configuration

            JwtSecurityTokenHandler.InboundClaimTypeMap = ClaimMappings.None;

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44300/identity",
                RequiredScopes = new[] { "csRA" }
            });

            var config = new HttpConfiguration();

            config.EnableCors(new EnableCorsAttribute("*", "*", "*"));
            app.UseCors(CorsOptions.AllowAll);

            config.SuppressDefaultHostAuthentication();
            config.Filters.Add(new HostAuthenticationFilter("Bearer"));

            Bootstrapper.Bootstrap(app, config);

            app.UseWebApi(config);

            //required for Swashbuckle.  MUST be run after app.UseWebApi(config)
            app.UseStageMarker(PipelineStage.MapHandler);

**Comment by brockallen** [comment]
Your `HostAuthenticationFilter` should be correcting the damage done by `SuppressDefaultHostAuthentication`. If all this project does is web api (meaning no cookies or any other authN mechanism), then you can remove both.

**Comment by stevenfirstrowinc** [comment]
removing both worked; but why didn't adding the HostAuthenticationFilter override the SupressDefaultHostAuthentication?

**Comment by brockallen** [comment]
Not sure.

**Comment by stevenfirstrowinc** [comment]
lol!  fair enough.  If I did need to support other authN mechanisms, do I just need to put these two lines back in? 

What about to support google, etc. implementations of OAuth, same thing or would they fall into this since it's bearer tokens?

**Comment by brockallen** [comment]
Yes, but then you'd be back to the original problem. The way you had it should have worked, so we're missing something else that's not evident from the snippet you put.

The reason for wanting it is that you don't want cookies to be used/trusted when hitting your API.

**Comment by stevenfirstrowinc** [comment]
interesting...  I thought I had it working once before but thought maybe it was an environment issue (I hardcode auth in certain debug scenarios).  If my UI started sending cookies do you think that would cause the Supress and filter to kick in?  Could the lack of cookie sending be causing some kind of incorrect behavior?

**Comment by brockallen** [comment]
No I don't think so. 

-Brock

**Comment by stevenfirstrowinc** [comment]
Ok, I'll close for now because in this particular case with this particular Api those two calls are not required.  Hopefully I'll have better luck when I need it.

**Comment by stevenfirstrowinc** [comment]
I have some further issues that I think are related to this item.  Maybe.  In this same application I must support IE8 with file uploads.  The components we are using fall back to an iframe for IE8 and we are not able to set the header.  That leaves me with supporting the token on a querystring or cookies right, or are their other alternatives?  

I think in any case I will have to support
        config.SuppressDefaultHostAuthentication();
        config.Filters.Add(new HostAuthenticationFilter("Bearer"));

right?

**Comment by stevenfirstrowinc** [comment]
I thought I might be able to override the default behavior and allow cookies and/or query string by using the following that I got an idea from [Dominick](http://leastprivilege.com/2013/10/31/retrieving-bearer-tokens-from-alternative-locations-in-katanaowin/)

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44300/identity",
                RequiredScopes = new[] {"csRA"},
                Provider = new CustomOAuthBearerProvider("access_token")
            });

but my ````CustomOAuthBearerProvider```` never get's hit.  I also tried the following

            var options = new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://login.codysoft.net/identity",
                RequiredScopes = new[] {"csRA"},
                Provider = new OAuthBearerAuthenticationProvider
                {
                    OnRequestToken = context =>
                    {
                        var request = context.Request;
                        if (request.Headers.ContainsKey("Authorization"))
                            context.Token = request.Headers["Authorization"];
                        else if (request.Cookies["access_token"] != null)
                            context.Token = request.Cookies["access_token"];
                        else
                        {
                            var value = request.Query.Get("access_token");
                            if (!string.IsNullOrEmpty(value))
                            {
                                context.Token = value;
                            }
                        }
                        return Task.FromResult<object>(null);
                    }
                },
            };

            app.UseIdentityServerBearerTokenAuthentication(options);

No break points get hit here either.  My code may be incorrect but it looks as though my override of provider never get's taken.

**Comment by leastprivilege** [comment]
That might be a bug in the config extension method. Could you open an issue in the right repo?
