### ISSUE TITLE
[Question] AspNetIdentity where do accounts live?

### ISSUE THREAD

**Issue by rchatters** [IdentityServer/IdentityServer3#1073]
I'm looking to setup an MVC app (more in the future), and multiple mobile apps that will use a single sign on (with local accounts). IdentityServerV3 Looks like this will work for this. We also want to use AspNetIdentity for the accounts.

The part I'm confused about even after setting up and looking at the sample, is creating users. I would like the user account creation to live on the STS server. We would need an api call to create the users on the STS site. Then get the JWT token to use through the apps. I looked into the IdentityManager, but this looks more of a interface to create users manually. In our scenario the users would need to be created through a registration page on the MVC app or mobile apps but stored on the STS side. 

is this possible with IdentityServer?
I read that the IdentityServer is merely an authentication server. Which is fine, but where do the accounts live?

Thanks

**Comment by johnkors** [comment]
User registrations is outside the scope of idsrv, yes. You'll have to create your own functionality for that. Make use of a IUserService implementation to hook into your own user store.

**Comment by rchatters** [comment]
![identityserver v3 - network general](https://cloud.githubusercontent.com/assets/3921959/6656780/6466a5fa-cb0b-11e4-9e79-a3b29781c7a5.png)

So would this be the correct though process. The MVC apps would talk to a Private Web ApI to create/forgotpassword/login a user. The Web API goes through the IdentityServer to get a token?

Or am I way off?

**Comment by johnkors** [comment]
Most of that made sense to me :) Not sure about the arrows marked with JWT going between idrv and your Web API. What is that?

Unless your Web API is a client of another Web API, it does not need to ask for JWTs. It should only validate the incoming tokens, and there are two ways of doing that. Using crypto libs checking the signature of the signed tokens, or asking idsrv at the accesstokenvalidation endpoint.

**Comment by rchatters** [comment]
Thanks,
I think this is where I'm confusing myself.

Our Requirements are to have a single sign-on (without google/facebook etc.. until the future.) And the SSO is to house the user accounts for security purposes. 

My thought was a STS server (IdentityServerV3) to authorize. Going down that path and doing aspnetIdentity I found I was unable to register accounts remotely. So I assumed I would need a web api to handle the api calls and I would only want the api to be called by the MVC apps and ios. Which has me bouning between IdentityServer and OWIN auth server. Questioning do I need IdentityServerV3. 

Right now I have IdentityServerV3 running in a MVC app because I was unsure if it could run in a web api, where I could then build in the registration part. But it sounds like I have IdentityServerV3 setup correctly, I just need another app to handle the creation of accounts.
