### ISSUE TITLE
Where is nLogLogProvider?

### ISSUE THREAD

**Issue by srberndt** [IdentityServer/IdentityServer3#1076]
I would like to use nLog with IdentityServer and the documentation says it's supported with nLogLogProvider, but I can't find it.  Was that deprecated?

**Comment by johnkors** [comment]
It's here: https://github.com/damianh/LibLog/blob/master/src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs

**Comment by loctanvo** [comment]
No, [it's still there](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/App_Packages/LibLog.2.0/LibLog.cs#L473). It's part of LibLog.cs.
