### ISSUE TITLE
Mapping additional WsFederation claims through to client 

### ISSUE THREAD

**Issue by gaspode44** [IdentityServer/IdentityServer3#1079]
I would like to get the IdSvr to include some custom claims that are issued by our WsFederation STS

I've followed the examples for role claims by adding to the scopes configuration as per the example - http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html

And updating the client middleware config to request the "roles" scope and this works - Role claims issued by the WsFed endpoint back to IdSrv are passed onto the client

When I tried to do the same for a custom claim (in our case a claim type of AccountId) in the same way - add a scope with name "account" of type Identity and a scope claim list that includes a new ScopeClaim with name AccountId its not included in the claims returned by the IdSvr to the client

I've tried explicitly adding the claim in the Notifications in the WsFed configuration but no luck

It looks like I'm missing the config that tells IdSvr how to map that claim? - what am I missing?

**Comment by leastprivilege** [comment]
Is your user service somehow persisting those incoming custom claims?

**Comment by gaspode44** [comment]
I'm still prototyping this with the default in memory components - is that the issue - if I include the EF implementations would that help?

I couldn't understand why it was working for the role claims being issued by the WsFed endpoint and not the other scope  - is there something special about WsFed role claims that just get mapped?

Where in the core source should I look to see this being handled?

**Comment by leastprivilege** [comment]
I'd recommend you implement your own user service - AuthenticateExternal gets the external claims, GetProfile returns them to the token engine. Very helpful for learning purposes.

**Comment by gaspode44** [comment]
yep thanks that helped identify the issue - casing of the claim type string value was slightly off so it wasn't being matched when tested against the requested claims
