### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by zealouscoder** [IdentityServer/IdentityServer3#1080]
Question.  I have enabled all of the available logging options (EnableHttpLogging, EnableWebApiDiagnostics, IncludeSensitiveDataInLogs, WebApiDiagnosticsIsVerbose) and tried a little with adding my own TraceLogProvider, but I do not see client IP Address anywhere.  Is that available from Identity Server, or do I need to merge these logs with IIS logs, or another solution?

Thanks!

**Comment by brockallen** [comment]
I don't think we capture that in the logs, but we do capture IP address in the eventing system. If you enable eventing, then it will write to the logs by default.

**Comment by zealouscoder** [comment]
Excellent!  I enabled eventing and that looks like it has what I need.  Thanks, Brock!
