### ISSUE TITLE
Previously i have asked question on below link

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#1081]
https://github.com/IdentityServer/IdentityServer3/issues/979#issuecomment-75905848

after logout is done , then we have to redirect back login page(some other page) in the above link post i have got solution like it will be implemented with in 2 week.                                                                       so whether it is implemented ?

**Comment by brockallen** [comment]
It's listed on the releases:
https://github.com/IdentityServer/IdentityServer3/releases

**Comment by RajMondaz** [comment]
whether this  changes is updated on custom user service in the  Idsrv3 samples ?
 because i am using custom user service sample for idsrv3.. can i get this update on that sample..?

**Comment by brockallen** [comment]
No, but it's also in the docs: https://identityserver.github.io/Documentation/docs/configuration/authenticationOptions.html
