### ISSUE TITLE
Check session endpoint enabled, but SessionId is missing

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#1083]
Hi,

I've recently updated from 1.1.1 to 1.3.0 and have started receiving this error message:
"Check session endpoint enabled, but SessionId is missing"

I had a quick look through the source, and found its happening here:
``` c#
 if (_options.Endpoints.EnableCheckSessionEndpoint)
{
  var sessionId = _sessionCookie.GetSessionId();
  if (sessionId.IsPresent())
  {
    request.SessionId = sessionId;
  }
  else
  {
    LogError("Check session endpoint enabled, but SessionId is missing", request);
  }
}
```

If I clear all my cookies, and go to Identity Server then it never finds a session on the first authentication request, and will log this error. I don't quite understand what the check is doing, I couldn't find any info in the related issues.

It looks like I can just turn the check off, but I'm not sure what impact that will have?
I'm also not sure where to change it? Is there doco for this Check Session Endpoint?

**Comment by parkinsona** [comment]
I think I found how to turn it off, is this correct?
``` c#
    Endpoints = new EndpointOptions { EnableCheckSessionEndpoint = false},
```

Still not sure if I should turn it off though.

**Comment by brockallen** [comment]
So something's amiss. Can you trace the http traffic to see if a session id cookie is being emitted when a user logs in.

**Comment by parkinsona** [comment]
Is that the cookie named: idsvr.session?

Here's what I've noticed with my 2 RPS.

1. Manually Clear All Cookies
2. Go to RP1 click login
3. Redirected to Idsvr login page (only cookies are idsrv.xsrf & SignInMessage..... & OpenIdConnect.Nonce.OpenIdConnet) Error email is sent at this point.
4. User logins in successfully (no error email, idsvr.session cookie gets created)
5. User goes to RP2, clicks login
6. Redirects to idsvr and back to RP2 (no login screen or error email)

Seems like its only happening the very first time you go to the log in page because the idsvr.session cookie isn't created yet.

**Comment by leastprivilege** [comment]
That might be a bug. Could you open an issue in the right repo?

**Comment by leastprivilege** [comment]
Looks like a logging leftover when we re-structured the validator. I will look into it.

**Comment by parkinsona** [comment]
No worries. Am I able to turn off the check for the moment? I would like to deploy another change from this release if possible.

**Comment by leastprivilege** [comment]
fixed on dev

**Comment by parkinsona** [comment]
Thanks for the fix, does this have a release schedule?

**Comment by brockallen** [comment]
Check these:
https://github.com/IdentityServer/IdentityServer3/releases
https://github.com/IdentityServer/IdentityServer3/milestones

**Comment by parkinsona** [comment]
I can see this issue is not assigned to a milestone.
This issue was from 1.3.0, and there's no 1.3.1 yet so I assume this is still to come.

**Comment by leastprivilege** [comment]
Yes, it is not released yet. Is it urgent?

**Comment by parkinsona** [comment]
No its not urgent. I'm just trying to work out if I should disable the check, or if I just wait for the release.

**Comment by parkinsona** [comment]
Thanks for releasing this in 1.4. Its working great now :)
