### ISSUE TITLE
Username is null after authentication

### ISSUE THREAD

**Issue by rajarameshvarma** [IdentityServer/IdentityServer3#1084]
I am using IdentityServer v3 with my MVC application. Once authenticated I am trying to add additional roles as claims.  There roles will be fetched from database. For this I need username that user entered in the login page. Some how this is null.

SecurityTokenValidated = (context) =>
{
            var identity = context.AuthenticationTicket.Identity;
            var user = identity.Name; //This is null

            return Task.FromResult(0);
}

**Comment by brockallen** [comment]
Check the claims on the Identity -- your claims are in there.

**Comment by rajarameshvarma** [comment]
Thanks Allen. I am using like this 
    identity.Claims.Where(r => r.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

is there a way to simply fine this?   Below statement is not working.
    identity.Claims.Where(r => r.Type == identity.NameClaimType).FirstOrDefault();

**Comment by brockallen** [comment]
I meant put a break point and see what claims you have. Do you have any? Or is the one you want, just a diff claim type?

**Comment by rajarameshvarma** [comment]
This is the one I want and I have the required value. But I am expecting NameClaimType should refer to the type for the name claim. But these two are different. 

NameClaimType has an identifier as "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" but name is actually as a type ending with "nameidentifier"

**Comment by leastprivilege** [comment]
You can set the name claim type when constructing the ClaimsIdentity. I believe there is also a setting on the OIDC MW.
