### ISSUE TITLE
Ws-Federation with ADFS 3.0. Passive Endpoint Configuration

### ISSUE THREAD

**Issue by rowdyy1960** [IdentityServer/IdentityServer3#1089]
I have set up idsrv3 in my lab environment. I've configured the server for ws-federation to my ADFS 3.0 server. When I hit the landing point and press the button defined for active directory authentication the login box displays as expected, but when I complete authentication I fail on the endpoint redirection with a http 405 error. I've been pointing back to what I thought was the correct endpoint /wsfed?wa=wsignin1.0 configured as a ws-federation passive endpoint. I also notice that when I go to the wsfed/metadata endpoint, instead of showing an xml document I get a dialog to open or save. Is my understanding of the ws-federation documentation incorrect or perhaps the adfs configuration is the issue?

**Comment by mschulz531** [comment]
IE will show the open or save dialog...normal browsers (Chrome, Firefox) will show the JSON document directly in the browser window.

If you are referring to the endpoint defined in ADFS, what is your endpoint set to?  I know I struggled with this for awhile before I got it right.  If you are referring to the ADFS "Relying Party Trusts" properties window for your defined Relying Party, the Endpoints tab should include a URL for "WS-Federation Passive Endpoints" with a value of "https://youridentityserver.yourdomain.com/"

You should not add "wsfed" to the end of this endpoint in ADFS.

**Comment by rowdyy1960** [comment]
Thanks Michael. The "WS-Federation Passive Endpoints" is what I was referring to. I have now corrected that endpoint. The lab server was setup as a minimalist IIS server so I added chrome to the environment and found that the metadata endpoint was actually throwing an error. The network service did not have read access to the certificate in the root store (even though mmc said it did). I used the findprivatekey utility to find the physical location and granted access there and now the endpoint works.  Now I'm just down to a securitytokenhandler issue and I'm good to go.

**Comment by mschulz531** [comment]
glad I was able to help

**Comment by georgewen** [comment]
I am struggling making this to work, on the ADFS side, I have tried the WS-Federation Endpoint to be:

https://localhost:44333/core/wsfed
https://localhost:44333/core/external
https://localhost:44333/core/

but none of them work (https://localhost:44333/core/ is the id3 url), after login it went to the url I used about and endup with 500 error.

any suggestions will be much appreciated.
