### ISSUE TITLE
Question about .Net Framework 4 and Orchard

### ISSUE THREAD

**Issue by pomeh** [IdentityServer/IdentityServer3#1092]
Hi,

First of all, thanks you for building this great library. There is a lot of documentation and demos, and you're very active to the projet so it's cool :)

I have 2 simple questions:

- is the client library (Thinktecture.IdentityModel.Client) compatible with .Net Framework 4 or 3.5 ? [Nuget says it's not](http://www.nuget.org/packages/Thinktecture.IdentityModel.Client) (>= 4.5 required), so what would you recommend to work around this ?

- do you have any recommendations, experience or known issues with Orchard CMS ? I would like to change Orchard authentication/permission mechanism to use your client library and my custom OpenID Connect server.

Thanks.

**Comment by leastprivilege** [comment]
thanks.

We rely on HttpClient - hence the 4.5 requirement. Never used Orchard.

**Comment by pomeh** [comment]
Ok thanks for you answer Dominick.
