### ISSUE TITLE
Programatically revoke Token

### ISSUE THREAD

**Issue by DGoslin** [IdentityServer/IdentityServer3#1094]
Is it possible to programmatically revoke an issued token from within the Identity server? I basically have a use case whereby an admin etc has to have the ability to force token revocation. I would like to be able to perform revocation for all token types

**Comment by johnkors** [comment]
You're in full control over where you store your tokens, so yes. Create an admin GUI that reads from the same store and expose a delete button. 

No out of the box functionality from idsrv to do this, though.

**Comment by DGoslin** [comment]
Just to clarify you are referring to the **TokenHandleStore** property of the **IdentityServerServiceFactory**

I had inferred this from my look through the code, just being pedantic, thanks for the confirmation
