### ISSUE TITLE
Support for vNext

### ISSUE THREAD

**Issue by evilpilaf** [IdentityServer/IdentityServer3#1095]
I was wondering if you have in your roadmap support for adding IdServer3 in the OWIN stack that has MVC6 and vNext, or if this already works, how I can use it.

**Comment by DerAlbertCom** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNet5Host

**Comment by ehaskins** [comment]
Note that the existing sample doesn't run on .net Core, only the full framework.

**Comment by evilpilaf** [comment]
Yeah, I'm trying it on the core an it didn't work

**Comment by DerAlbertCom** [comment]
So, what you really want is support for .NET Core, not vNext

**Comment by leastprivilege** [comment]
IdSrv3 runs on ASP.NET 5 & the full .NET framework.

.NET Core is not supported right now - this would be a big change.
