### ISSUE TITLE
auth_time claim causes NullReferenceException because of bug in .NET Framework Claim cloning

### ISSUE THREAD

**Issue by sickboy** [IdentityServer/IdentityServer3#1096]
It seems auth_time claim has a property set 'json_type', which is set to Int32.

When verifying an access_token (connect/acesstokenvalidation), IdentityModel.Principal.Create calls Identity.Create,
passes in the existing claims, and ends up calling claim.Clone(..) which in turn calls a protected constructor of Claim.

The problem however is that if you try to clone a claim that has Properties, the constructor has a bug; it does not first initialize the properties dictionary:
~~~
protected Claim(Claim other, ClaimsIdentity subject)
{
    this.m_propertyLock = new object();
    if (other == null)
    {
        throw new ArgumentNullException("other");
    }
    this.m_issuer = other.m_issuer;
    this.m_originalIssuer = other.m_originalIssuer;
    this.m_subject = subject;
    this.m_type = other.m_type;
    this.m_value = other.m_value;
    this.m_valueType = other.m_valueType;
    if (other.m_properties != null)
    {
        foreach (string str in other.m_properties.Keys)
        {
            this.m_properties.Add(str, other.m_properties[str]);
        }
    }
    if (other.m_userSerializationData != null)
    {
        this.m_userSerializationData = other.m_userSerializationData.Clone() as byte[];
    }
}
~~~
(it should access this.Properties.Add instead, as the accessor takes care of initialization, or simply first initialize the m_properties)

This appears to be a bug in MS framework, but I am wondering why I seem to be one of the few people running into this with IdentityServer/Model. Any known workarounds or ?

I tried upgrading to 4.5.2, as the reference source seems to indicate that the implementation of Claim has changed: http://referencesource.microsoft.com/#mscorlib/system/security/claims/Claim.cs
However to no avail. Which makes me wonder if my system somehow uses an old mscorlib, or if the reference source is actually 4.6 perhaps or so....

Am I going crazy?

**Comment by sickboy** [comment]
Okay, I think I got it figured out. I was close, but in reverse.
I have .NET Framework 4.6, and that one has the bug in the Claim implementation...

**Comment by leastprivilege** [comment]
Have you filed a bug with Microsoft?

**Comment by sickboy** [comment]
Did; https://connect.microsoft.com/VisualStudio/feedback/details/1217925
Hope it's the correct place ;-)

**Comment by brentschmaltz** [comment]
Sorry about the inconvenience. The bug was fixed and checked in Feb, it sometimes takes a while for all the fixes to show up.
