### ISSUE TITLE
IncludeAllClaimsForUser not working with UserInfo endpoint request

### ISSUE THREAD

**Issue by ChrisVinall** [IdentityServer/IdentityServer3#1097]
Hi,

Hopefully this isn't something I'm misunderstanding...

I have my write scope defined like this (edit: there's another problem with this, that it's a resource scope, but the problem persists with an identity scope):

        new Scope
        {
            Name = "write",
            DisplayName = "Write data",
            Type = ScopeType.Resource,
            Emphasize = true,
            IncludeAllClaimsForUser = true
        },

However when I make a UserInfo request with the OIDC client, this is what happens:

[Thinktecture.IdentityServer.Core.ResponseHandling.UserInfoResponseGenerator]: 20/03/2015 1:01:53 AM +00:00 -- Creating userinfo response
[Thinktecture.IdentityServer.Core.ResponseHandling.UserInfoResponseGenerator]: 20/03/2015 1:01:53 AM +00:00 -- Scopes in access token: openid email profile read write offline_access
[Thinktecture.IdentityServer.Core.ResponseHandling.UserInfoResponseGenerator]: 20/03/2015 1:01:53 AM +00:00 -- Requested claim types: sub email email_verified name family_name given_name middle_name nickname preferred_username profile picture website gender birthdate zoneinfo locale updated_at
[Thinktecture.IdentityServer.Core.ResponseHandling.UserInfoResponseGenerator]: 20/03/2015 1:01:54 AM +00:00 -- Profile service returned to the following claim types: sub preferred_username email email_verified name given_name family_name email

It seems like I should be getting `requestedClaimTypes = null` passed to `GetProfileDataAsync` in my `UserService` but that's not what happens.

If you can confirm this is not expected behaviour, I can create a PR to address this.

**Comment by ChrisVinall** [comment]
Although it might be quicker to fix it yourself, since it involves the addition of a single line to `UserInfoResponseGenerator` :)

**Comment by mschulz531** [comment]
hmm interesting...I ran into this bug as well but didn't realize it was such an easy fix.

**Comment by ChrisVinall** [comment]
I've just noticed that my write scope, being a `Resource` scope, won't be considered by `UserInfoResponseGenerator` anyway. However, from reading the code in `UserInfoResponseGenerator`, it won't return all claims even if I do request an `Identity` scope with `IncludeAllClaimsForUser` set.

**Comment by ChrisVinall** [comment]
I'll just confirm that by actually trying it, though...

**Comment by johnkors** [comment]
How do you ask for the access token you use at the user info endpoint? What scopes do you ask for at that point? What scopes are defined for that client?

**Comment by leastprivilege** [comment]
Send a PR please so we can discuss.

**Comment by ChrisVinall** [comment]
Will do. I'm under the pump a bit at the moment so will be a few days.

**Comment by leastprivilege** [comment]
added for 1.4

**Comment by leastprivilege** [comment]
Have you tested it in 1.4?
