### ISSUE TITLE
Getting name of user

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1098]
Hi

After successful login, how to I access the name of the user from the client application? I'm trying to use the traditional User.Identity.Name property but with no luck.
Is there another, better way?

**Comment by johnkors** [comment]
How are you setting your user on the return from idsrv? Using OIDC mw from Katana? Check the claims list of your ClaimsIdentity for the name claim.

**Comment by henninga** [comment]
My idsrv config looks like this:
 var identityServerFactory = Factory.Configure();
                identityServerFactory.ConfigureUserService("Membership");

                var options = new IdentityServerOptions()
                {
                    SiteName = "Patentstyret pålogging",
                    SigningCertificate = Certificate.Get(),
                    Factory = identityServerFactory,
                    CorsPolicy = CorsPolicy.AllowAll,
                    
                    AuthenticationOptions = new AuthenticationOptions
                    {
                       
                        LoginPageLinks = new[]
                        {
                            new LoginPageLink{Text = "Register as a new user", Href = "LocalRegistration"},
                        },
                        IdentityProviders = ConfigureAdditionalIdentityProviders,

                    },
                    EventsOptions = new EventsOptions
                    {
                        RaiseSuccessEvents = true,
                        RaiseErrorEvents = true,
                        RaiseFailureEvents = true,
                        RaiseInformationEvents = true
                    }

                };

                coreApp.UseIdentityServer(options);

And the client config:

JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationType = "Cookies"
            });
            //app.UseKentorOwinCookieSaver();

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "implicitclient",
                ClientSecret = "secret",
                Authority = Constants.BaseAddress,
                RedirectUri = "http://localhost:53141/",
                ResponseType = "id_token token",
                Scope="openid email profile",
                SignInAsAuthenticationType = "Cookies"
            });

**Comment by johnkors** [comment]
Your ```User.Identity.Claims``` list should include a name claim. But it depends on your setup. I see you're asking for an id_token and an access token when doing authentication. To get the identity claims into the id_token, you need to set the the scope claims to be always included in idtoken (AlwaysIncludeInIdToken)

More info here: http://identityserver.github.io/Documentation/docs/configuration/scopesAndClaims.html

You'll have to modify the default in memory scopes list you get from the identityServerFactory. There are some available helpers : https://github.com/IdentityServer/IdentityServer3/blob/2c0ef5f7dc3be0b804d1e1734dad634dc1288fad/source/Core/Models/StandardScopes.cs#L54

**Comment by henninga** [comment]
Oh boy, rookie mistake. It seems when I originally created the factory I hardcoded the scopes there, but later added a Scopes file like in the sample projects and I've been editing that. After changing the factory I now get the correct claims.

Now it is just a matter of getting out the correct claim. Should be easier.

Thanks :)

**Comment by johnkors** [comment]
No worries, just don't patent idsrv. ;)

**Comment by henninga** [comment]
Haha, shouldn't be a problem :)

**Comment by johnkors** [comment]
Oh, and could you close this issue as well if you solved it? Thanks.
