### ISSUE TITLE
Update jwks_uri endpoint keys when signing certificates are updated.

### ISSUE THREAD

**Issue by cgoboncan-ebsi** [IdentityServer/IdentityServer3#1099]
If signing certificates are loaded outside of identityServerOptions,, e.g. loaded from somewhere in a derived tokensigningservice class, the jwks_uri endpoint is either disabled (no certificates found in idSrvOptions) or stale (certificates were loaded from idSrvOptions but the certificate store has rolled over to new certificates).

**Comment by brockallen** [comment]
Right now we don't have a service for those. If your keys are not available to IdSvr (because you implement the token signing service elsewhere), you can just use the public key part of the cert for the metadata.

**Comment by brockallen** [comment]
Since keys don't change that frequently, we'll close this issue.
