### ISSUE TITLE
ICustomRequestValidator ValidateAuthorizeRequestAsync no longer passes valid subject

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/IdentityServer3#1100]
I'm using a custom class for ICustomRequestValidator where I have overridden ValidateAuthorizeRequestAsync.  Up until v1.3 I was able to do the following

            var userid = request.Subject.FindFirst(Constants.ClaimTypes.Subject).Value;
            return ValidateHasApplicationAccess(request.ValidatedScopes.GrantedScopes, Guid.Parse(userid));

As of 1.3 request.Subject has no claims the **first time** it is called which is before the login screen is rendered.  Here is the stack trace
![call_stack_1](https://cloud.githubusercontent.com/assets/7965187/6761317/ac35a24c-cf1f-11e4-85d3-b681aebc6c0b.png)

The **second time** it is passing the subject claim.  Here is the stack trace
![call_stack_2](https://cloud.githubusercontent.com/assets/7965187/6761325/c97167ce-cf1f-11e4-9837-d703e6ecbf22.png)

Both traces look the same to me so I don't know why the subject claim isn't being passed in both.

Since this is a change between minor versions of v1, I'm not sure it's actually related to #776.  If it is an intentional change between 1.2.1 and 1.3, can you suggest and alternative until #776 is implemented?

**Comment by leastprivilege** [comment]
Due to the changes we did in the validator - the custom validator gets called before **and** after the user is authenticated.

Check for request.Subject.Identity.IsAuthenticated first before you want to check any claims.

**Comment by stevenfirstrowinc** [comment]
uh yes of course.  Thank you.
