### ISSUE TITLE
I can't seem to get a custom identity server webhost to redirect back to a webclient

### ISSUE THREAD

**Issue by CoriganSimpson** [IdentityServer/IdentityServer3#1101]
I have a webhost server with a custom user service that i can't get to redirect back to the client. I have tried both a owin middleware openidconnect client and an codeflow client but can't get the server to do anything but redirect back to itself.

After stepping through the code the returnUrl in the loginlocal function in the AuthenticationController.cs is always the server authentication endpoint url. Any help would be appreciated. Thanks.

**Comment by leastprivilege** [comment]
turn on logging and see if that helps.

**Comment by leastprivilege** [comment]
...it is normal that the returnUrl on the SignInMessage points to the authorize endpoint. So that's not your problem.

**Comment by CoriganSimpson** [comment]
I was trying to find in the identity server code where it redirects the user back to the calling client which i thought happened after the authentication. I will look some more i guess but if you have any ideas on why it wouldn't be redirecting back it would be appreciated.

**Comment by leastprivilege** [comment]
The authorize endpoint does the redirect back to the client.

**Comment by CoriganSimpson** [comment]
So i pretty much redid everything i had done... I re-downloaded the identityserver3 from source and not changing anything from default my test client works and it redirects back, everythings great. 

Then i added my custom UserService and it acts as it did before. It never redirects back to the client. So what could i possibly be doing in my UserService to have it not redirect back. I turned on logging and this is what i get.. http://paste.ubuntu.com/10663252/ If you want it some other way i can paste it somewhere else.

I dont see anything in the logs and dont really see anything thats wrong unless im like missing a dependency or something. If you want i can paste my code as its just test code...

Thanks for looking.

**Comment by leastprivilege** [comment]
From your description - something with your user service is wrong. Maybe copy the InMemoryUserService and start modifying that. Then see at which point you break the working user service.

— 
cheers
Dominick Baier


On 23 Mar 2015 at 20:30:46, Corigan Simpson (notifications@github.com) wrote:

So i pretty much redid everything i had done... I re-downloaded the identityserver3 from source and not changing anything from default my test client works and it redirects back, everythings great.

Then i added my custom UserService and it acts as it did before. It never redirects back to the client. So what could i possibly be doing in my UserService to have it not redirect back. I turned on logging and this is what i get.. http://paste.ubuntu.com/10663252/ If you want it some other way i can paste it somewhere else.

I dont see anything in the logs and dont really see anything thats wrong unless im like missing a dependency or something. If you want i can paste my code as its just test code...

Thanks for looking.

**Comment by CoriganSimpson** [comment]
Well im dumb.. I sorry to have wasted your time. I found the problem and it was in my user service isActive function. But it was pretty hard to find ;) Thanks again. I really like what you guys have done. If i can help let me know :)
