### ISSUE TITLE
n.OwinContext.Authentication.User.FindFirst("id_token") is null after cookie is expired.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3#1102]
I have a MVC client with Hybrid Flow.
I have a logout link on my view. 
It work fine until 5 minutes , but after that encourage with an Object null refrence in the following line in 
  RedirectToIdentityProvider = async n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
                            n.ProtocolMessage.IdTokenHint = idTokenHint;
                        }
}

Thanks for your points.

**Comment by leastprivilege** [comment]
Well - if the cookie is expired, you can't retrieve data from it anymore.
