### ISSUE TITLE
WCF Soap Sample

### ISSUE THREAD

**Issue by Xavina** [IdentityServer/IdentityServer3#1107]
Hello,

Is there any sample of using the Identity Server v3 with a 'classical WCF SOAP' service?

We have a mix of APIs, some implemented as a WebAPI and some as a WCF services. Is there any walkthrough of implementing the validation for a WCF Soap service?

Has it sense?

Thanks a lot.

**Comment by leastprivilege** [comment]
On my todo. too busy right now.

**Comment by Xavina** [comment]
I will do it on myself. I can send you the sample when done.

But, I need a little guidance. Is it possible? Just the basic lines....

Thanks!

**Comment by leastprivilege** [comment]
The first leg would probably use resource owner flow to reques the token. Then you would use that token together with ChannelFactory.CreateChannelWithIssuedToken (some token conversion magic is needed here).

The WCF service must use the new .NET 4.5 identity pipeline together with the JWT security token handler.

Will work - just requires some fiddling ;) have fun!

**Comment by leastprivilege** [comment]
did you make progress? Should I close this issue? Will you let us know once you have a working sample?

**Comment by Xavina** [comment]
I'm working on it.

The first aproach is to enable WS-Federation and use the 'ws2007FederationHttpBinding' binding between the WCF service and the Identity server.

The WCF client will ask for a token to the Identity server and will use it with the WCF service.

Anyway, you can close the issue, and if I make any relevant progress you can count with that sample.

Thanks!

**Comment by AlbertoCe** [comment]
Hello @Xavina ,

Have you got to a working sample ? 
It could be very helpful for me...

**Comment by Xavina** [comment]
Hello @AlbertoCe,

I've being working on it and I have a working aproach.

I would like to add a sample to the IdentityServer 3 samples, and someone must check it for correctness.

As soon as I post the sample I will let you know.

Thanks,

**Comment by leastprivilege** [comment]
I can review it.

**Comment by Xavina** [comment]
OK.

I've commit my fork to: https://github.com/Xavina/IdentityServer3.Samples/

It is not my desired solution since I can not use the 'ChannelFactory.CreateChannelWithIssuedToken'.

The implemented solution injects the token in the SOAP message header, then the server recovers the token from the header and performs a validation on the token and CurrentPrincipal.Identity.

I've been fighting with ChannelFactory.CreateChannelWithIssuedToken(), the main problem was with the binding to use. I can do the token transformation at the client side, using the WS2007FederationHttpBinding I can  send the token to the web service, and perform a validation using JwtSecurityTokenHandler, but when the code leaves the validation section there is a crash:

<InnerException>
<ExceptionType>System.IndexOutOfRangeException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
<Message>Índice fuera de los límites de la matriz.</Message>
<StackTrace>
en System.Xml.XmlBufferReader.GetChars(Int32 offset, Int32 length, Char[] chars)
en System.Xml.XmlBufferReader.GetString(Int32 offset, Int32 length)
en System.Xml.StringHandle.GetString()
en System.Xml.XmlBaseReader.ReadEndElement()
en System.ServiceModel.Security.ReceiveSecurityHeader.ExecuteFullPass(XmlDictionaryReader reader)
en System.ServiceModel.Security.StrictModeSecurityHeaderElementInferenceEngine.ExecuteProcessingPasses(ReceiveSecurityHeader securityHeader, XmlDictionaryReader reader)
en System.ServiceModel.Security.ReceiveSecurityHeader.Process(TimeSpan timeout, ChannelBinding channelBinding, ExtendedProtectionPolicy extendedProtectionPolicy)
en System.ServiceModel.Security.TransportSecurityProtocol.VerifyIncomingMessageCore(Message&amp; message, TimeSpan timeout)
en System.ServiceModel.Security.TransportSecurityProtocol.VerifyIncomingMessage(Message&amp; message, TimeSpan timeout)
</StackTrace>
<ExceptionString>System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en System.Xml.XmlBufferReader.GetChars(Int32 offset, Int32 length, Char[] chars)
   en System.Xml.XmlBufferReader.GetString(Int32 offset, Int32 length)
   en System.Xml.StringHandle.GetString()
   en System.Xml.XmlBaseReader.ReadEndElement()
   en System.ServiceModel.Security.ReceiveSecurityHeader.ExecuteFullPass(XmlDictionaryReader reader)
   en System.ServiceModel.Security.StrictModeSecurityHeaderElementInferenceEngine.ExecuteProcessingPasses(ReceiveSecurityHeader securityHeader, XmlDictionaryReader reader)
   en System.ServiceModel.Security.ReceiveSecurityHeader.Process(TimeSpan timeout, ChannelBinding channelBinding, ExtendedProtectionPolicy extendedProtectionPolicy)
   en System.ServiceModel.Security.TransportSecurityProtocol.VerifyIncomingMessageCore(Message&amp; message, TimeSpan timeout)
   en System.ServiceModel.Security.TransportSecurityProtocol.VerifyIncomingMessage(Message&amp; message, TimeSpan timeout)</ExceptionString>
</InnerException>

And a response to the client:

<MessageLogTraceRecord>
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
<s:Header>
<a:Action s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:Action>
<a:RelatesTo>urn:uuid:b20338d0-b8df-473d-baa5-d23710d99e82</a:RelatesTo>
</s:Header>
<s:Body>
<s:Fault>
<s:Code>
<s:Value>s:Sender</s:Value>
<s:Subcode>
<s:Value xmlns:a="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">a:InvalidSecurity</s:Value>
</s:Subcode>
</s:Code>
<s:Reason>
<s:Text xml:lang="es-ES">Error al comprobar la seguridad del mensaje.</s:Text>
</s:Reason>
</s:Fault>
</s:Body>
</s:Envelope>
</MessageLogTraceRecord>

And I got stucked there...

I can send you a sample, or add a new WCF sampled based on this non-functional solution.

Thanks!!!

**Comment by leastprivilege** [comment]
You can't simply set the token as a string - it must be wrapped in a BinarySecurityToken. There's more work to do ;)

**Comment by Xavina** [comment]
Hi  Dominick,

Undestood.

I have a new 'NON WORKING' implementation. It is based on a CustomBinding, that uses a 'TransportSecurityBindingElement', and a 'CustomJwtSecurityTokenHandler'.

Everything seems to work until the service tries to check the message security, when an exception is thrown.

Client receives an 'InvalidSecurity' error, checking  WCF traces show the 'IndexOutOfRangeException' that I've posted above.

It is clear to me that the security is not propertly build, but I don't know how to build it in a proper way.

Can you give me some advice?

Thank you!

**Comment by Xavina** [comment]
Hi  Dominick,

Undestood.

I have a new 'NON WORKING' implementation. It is based on a CustomBinding, that uses a 'TransportSecurityBindingElement', and a 'CustomJwtSecurityTokenHandler'.

Everything seems to work until the service tries to check the message security, when an exception is thrown.

Client receives an 'InvalidSecurity' error, checking  WCF traces show the 'IndexOutOfRangeException' that I've posted above.

It is clear to me that the security is not propertly build, but I don't know how to build it in a proper way.

Can you give me some advice?

Thank you!

**Comment by Xavina** [comment]
Hi Dominick,

I have commit a 'WORKING' implementation based on Microsoft Custom Token WCF sample (https://msdn.microsoft.com/en-us/library/ms752249%28v=vs.110%29.aspx).

Basically the AccessToken is embedded and signed, but I couldn't managed it for using the CreateChannelWithIssuedToken and embedding it in a BinaryToken.

I think this solution is acceptable under a security point of view, but I'm not sure if the service must check the token against the validation endpoint.

Thank you,

**Comment by leastprivilege** [comment]
Code?

**Comment by Xavina** [comment]
Sorry.

For the WCF API:

https://github.com/Xavina/IdentityServer3.Samples/tree/master/source/Clients/SampleWCFApiHost


For the WCF API Client:

https://github.com/Xavina/IdentityServer3.Samples/tree/master/source/Clients/WCF%20Console%20Resource%20Owner%20Flow

Thanks,

P.S: I will do some clean up when a good solution is reached.

**Comment by leastprivilege** [comment]
Hi, 

I know I am not being very helpful. But this is all too complicated.

Use TransportWithMessageCredential security mode, request a token, wrap it in a binary security token, wrap that in a GenericXmlSecurityToken und CreateWithIssuedToken.

On the server side you can use the 4.5 identity pipeline and the JwtSecurityTokenHandler. 

No custom tokens etc necessary.

**Comment by Xavina** [comment]
Hi,

Thank you very much indeed!!!

I know you are busy. I will let you know about my progress.

Thanks again!

**Comment by mderriey** [comment]
Hi @Xavina.

How is everything going?
I stumbled upon this issue as I'm looking for a way to get WCF to validate JWT tokens issued by IdentityServer.

I'd be very happy to help if you experience issues, and maybe @leastprivilege can give us some more guidance :wink: 

Just to be clear, here's what I have in mind:
 - As IdSrv3 doesn't support WS-Trust (and thus the generation of SAML tokens), we want WCF to validate JWT tokens
 - I hope WCF can validate JWT tokens locally (not round-tripping to IdSrv) thanks to `JwtSecurityTokenHandler` class

Quick questions:
 - Do we still use `ws2007FederationHttpBinding` or is it out of question?
 - I saw some examples, the one from `Auth0` being the most popular, it seems, deriving from `ServiceAuthorizationManager` to inspect the HTTP `Authorization` header and validate the token. Is this approach feasible with both SOAP and REST flavors?

Thanks to both of you

**Comment by mderriey** [comment]
I'm still chewing on this one...

What I understood from what @leastprivilege said.

As for the client side:
 - We get the JWT token from IdSrv
 - We wrap it in a XML element representing a binary security token
 - We wrap this XML element in a `GenericXmlSecurityToken`
 - Use this token as a parameter of the `CreateChannelWithIssuedToken` function of the `ChannelFactory<TChannel>` class

I have one question regarding this part:
 - Do we generate the XML element ourselves or is there a way to have it built for us?

Now for the server side:
 - We have to use the `JwtSecurityTokenHandler` class so the JWT token is recognized

Here is where I'm clueless on how to proceed. I'm not familiar with WIF, nor with complex WCF configuration.

Questions:
 - Is it possible to have WCF locally valide the JWT token?
 - Is it possible to instruct WCF that a specified scope is to be present in the token so the call can succeed?

Sorry if questions are duplicated from my previous comment

Thanks

**Comment by Xavina** [comment]
Mickaël,

I've read your messages !!!

I'm configuring something so we can work on it together, ok?

I need a little time!

Thanks!

**Comment by mderriey** [comment]
OK, thanks, I'm looking forward to it.
I've been pulling my hair on this for the last couple of days :disappointed:

**Comment by Xavina** [comment]
Hi Mickaël,

Do you have the exception and stack trace for the error?

Is WCF trace on? I mean that this message may be received at the client but the server generates it, and it could be useful checking where the exception is being generated.

Did you fork the repo? May I have access to your code?

Thanks!

**Comment by mderriey** [comment]
Hey,

I knew it wasn't such a good idea to paste code in a comment...
I'll fork the original repo tomorrow and will give you the link so you can try it on your side.

I had a look at your repo but didn't run it so I can't tell you at the moment if we are experiencing similar exceptions.

**Comment by mderriey** [comment]
Hey,

You can find my repo [here](https://github.com/mderriey/IdentityServer3.Samples/tree/wcf_jwt).
Quickly, what was modified in the Clients solution
 - Added a WCF project in the `APIs` folder
 - Added a console application project, `Console Client Credentials With Wcf`

To run it, you'll have to:
 - Start the `SelfHost (Minimal)` minimal project in the `source` folder
 - `Debug -> Start new instance` on the WCF project
 - `Debug -> Start new instance` on the console project

If you put a breakpoint in the `MyJwtSecurityTokenHandler`, it'll get hit.
I disabled the WCF traces because the log files paths in the `web.config` are absolute and may differ for you, so just enable them again if you want to.

I'll have a look at your repo.
Thanks

PS: @leastprivilege, we know you're heaps busy, but if you manage to have a quick look and make some feedback, it'll be **VERY** appreciated :wink:

**Comment by Xavina** [comment]
Perfect.

What do you think if we follow the conversation there and we come back to this thread when we found a solution?

Enable the Issues section of your fork or Gitter, so we cant discuss... ;)

Thank you!

**Comment by mderriey** [comment]
I opened the Issues section.

**Comment by Bigshooter** [comment]
Anything new on this front.  I would really like to secure my WCF services using IdentityServer3.

**Comment by Xavina** [comment]
No.

Our main problem is with WCF not with the IdentityServer.

The main problem is at server side when the security is validated, you can check mderrey or my repository for details.

Anyway, any help will be apreciated, I don't have much time right now, but someone with deep knowledge of WCF security will be a great help.

Thanks,

**Comment by leastprivilege** [comment]
I finally got some time to look into that and got it working - will post a sample soon.

**Comment by mderriey** [comment]
That's **great** news! Thanks in advance, can't wait to take a look at it.

**Comment by leastprivilege** [comment]
I just checked it into the samples repo / dev branch (clients sample).

I had the same issues with binary security token so I decided to wrap the JWT in a SAML token. works.

**Comment by Xavina** [comment]
Thanks a lot Dominick!!!!

That binary security really made me crazy!!!

If you need anything just ask!!!

**Comment by mderriey** [comment]
Thanks again, Dominick.
Out of curiosity, do you think the issue we all experienced is a bug in `JwtSecurityTokenHandler`?
If so, I'll try to file a bug where appropriate.

**Comment by leastprivilege** [comment]
I think it is a bug in WCF. The IndexOutOfRange exception happens after the JWT handler was done.

**Comment by mderriey** [comment]
OK. I thought maybe it was the way the handler used the `XmlReader` that left it in a bad state.
Nevermind.
Thanks again!

**Comment by leastprivilege** [comment]
I mean - maybe that is the case - i was fed up with that and just switched to SAML as the container format.

Maybe try it with older versions of the JWT handler....or not - and don't look back

**Comment by leastprivilege** [comment]
I did a small write up http://leastprivilege.com/2015/07/02/give-your-wcf-security-architecture-a-makeover-with-identityserver3/

**Comment by mderriey** [comment]
Thanks, it's very informative.
I linked it from the StackOverflow question in case someone can't find your post when searching the interwebz :wink:

**Comment by avmp2208** [comment]
I'm very grateful with this project thanks to all of you,
I have a litle question, so, Imagine my scenario.
I have and WCF service which I use to retrive all my data, but this services is embebed inside and dll which I named Client that is reference to an MVC application, so, I want to secure all this applicacion, for example, all my ServiceContract have to be secured, and I mean all of them, 
and my question is, which method will you recommend for me? 
How do achive this with a WCF at the middle of this?
How to retrieve Token from the WCF Service and secure my Service contracts as well? 

Best regards.

**Comment by mderriey** [comment]
Hey avmp2208,

It's a bit confusing, but from what I get you have 3 execution points:
 - The STS which is IdentityServer
 - The WCF service, protected with tokens
 - The ASP.NET MVC application, which also references an assembly named `Client`that allows you to call the WCF service

Given I got this right, the steps in your MVC application to call the WCF service would be:
 - Get a token from the STS
 - "Attach" this token to the WCF proxy
 - Call a method on the WCF proxy

Does this make sense?

**Comment by avmp2208** [comment]
That's exactly what I'd like to do, 
I haven't wrote the implementation for user store yet, so here is my problem, which the identityserver sample I'm Ok, I can use it to login user against my DB, but how could I use it to register users, changing password, and others thing about the users?, I Could build the server but, Is ther any workthough to achive this using WCF? 

Your answers Is exactly my scenario. Thanks

**Comment by mderriey** [comment]
OK.
Once again, if I get it right, I thin you want to expose user management capabilities over WCF, and you plan on having an MVC application get user input and call the WCF service to persist whatever changes have been made.

IdentityServer only deals with authenticaiton and authorization, so when it comes to creating users, changing passwords, etc... you're on your own. What I mean is that IdentityServer doesn't provide this capability.
Also, I would advise you against building your own user store, IdentityServer already supports two of them out of the box, which are [ASP.NET Identity](http://www.asp.net/identity) and Brock Allen's [MembershipReboot](https://github.com/brockallen/BrockAllen.MembershipReboot/).

So let's say you use either of them, your WCF service implementation would deal with the user store to create/update users. The same user store would be used by IdentityServer to log in/authorize users.

Does it help?

**Comment by avmp2208** [comment]
Yeah, totally mderriey, great answerd, Right now I'm planning to build my own service with the user store implementation

Thanks
Best Regards

**Comment by ferreirix** [comment]
Hey guys, sorry for my ignorance on this quite complex topic but I'm a bit lost and i'd really appreciate some guidance.

I checked out the Dominick's sample for WCF and the console client uses the resource owner flow which means that it receives a JWT as AccessToken. In my case I have a WPF using hybrid flow and I receive an AccessToken like "e973c671aaa7ab11a3af62f5e069362a". Obviously it is not a JWT. Is there a way I can get this JWT using token_endpoint: "http://idsrv.nv1.local/connect/token" or as i suspect, the hybrid flow is never supposed to return an AccessToken in the format of a JWT?

If so, should I just pass this AccessToken (e973c671aaa7ab11a3af62f5e069362a) to the WCF and let it call the IdentityServer to check if the user has the neccessary claim in order to call the WCF service?

Thank you in advance.

**Comment by mderriey** [comment]
You can get JWT tokens with Hybrid flow. If you own the IdSrv instance, you can modify that in the configuration of your client.

If you can't, you'll have to change the WCF code since at the moment it relies on the fact that the token is JWT so we can validate it locally. Another option would be to go to the I prospection endpoint to get claims from your reference - opaque - token.

**Comment by ferreirix** [comment]
Thank you @mderriey that was really helpful. 

Now I have another small issue. I'm trying to contact the instrospection endpoint and reading the doc what does it mean by the authorization code "xxxyyy" in here [https://identityserver.github.io/Documentation/docsv2/endpoints/introspection.html](url) .

I've also tried to invoke the endpoint by using the IdentityModel client library as it's documented here [https://leastprivilege.com/page/2/](url) but my InstrospectionResult always has the Error property set to True, even though my client asked for the "api1" scope when authentifying. 

Thank you for your help.

**Comment by mderriey** [comment]
Hey,

My feeling is that what missing g is the fact that the introspection endpoint requires authentication as it is mentioned on the docs you've linked to.

The credentials are the name of a scope and the secret associated with that scope - via the `ScopeSecrets` property of a `Scope`.

Also note that only the scopes that are contained in the access token can introspect the token, and that by default only the claims associated with the scope you use for authentication will be returned. If you want all the claims contained in the access token to be returned, set the `AllowUnrestrictedIntrospection` property of the scope to `true`.

Finally, use the scope name and secret in the constructor of the `IntrospectionClient`, and you should be fine.
