### ISSUE TITLE
Wrong-generated links for external providers in external login page section

### ISSUE THREAD

**Issue by mirecg** [IdentityServer/IdentityServer3#1109]
Hi, 
in the latest version of IdentityServer there are wrong generated links for external providers.
Instead of the real url, there is url pointing to `http://.../{{provider.href}}`

After looking inside the code, I found the bug with missing "ng-" prefix for href attribute in a-link element. 
In login.html there is the following html code for a-link:
`<a class="btn btn-default" href="{{provider.href}}">{{provider.text}}</a>`
it should be
`<a class="btn btn-default" ng-href="{{provider.href}}">{{provider.text}}</a>`

Thank you

**Comment by brockallen** [comment]
I am not seeing the behavior you describe.

**Comment by mirecg** [comment]
Please have a look at https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/DefaultViewService/PageAssets/login.html

**Comment by brockallen** [comment]
But when it renders into my browser I am not seeing incorrect links. Can you explain what's broken?

**Comment by mirecg** [comment]
In my browser it renders wrong. As I have described, I'm seeing {{provider.href}} in the url for external provider login. 
I have found the {{provider.href}} keyword in login.html, in which it seems it is a subsitution variable from LoginModelView class ExternalProviders enumeration.
After correcting href to ng-href it renders OK.

![image](https://cloud.githubusercontent.com/assets/11613589/6781478/4b8b9b6c-d16e-11e4-95ed-8a7caf63eb05.png)

**Comment by brockallen** [comment]
Do you have any errors in the JS? Or have you done any modifications to the HTML or JS? It's working fine with the core samples. 

The only reason to use `ng-href` is if the user clicks the link too soon before the binding is done, but in our code we are using `ng-cloak` to prevent the links from being shown so there's no real need to use `ng-href` vs just `href`. 

So I'm confused and feel like something else is going on here.

**Comment by mirecg** [comment]
Hi, your feeling was good. It pointed me at trying it in different browsers. And it's a local problem in my firefox, which is my default browser. In chrome it works fine. I'm sorry for a false bug.

The problem was in greasemonkey extension I have enabled in firefox.

Thank you

**Comment by brockallen** [comment]
No problem.
