### ISSUE TITLE
Login & automatic tests

### ISSUE THREAD

**Issue by sennaapp** [IdentityServer/IdentityServer3#1110]
My Identity Server login is working just fine when human is using it. Now I'm recording automatic UI tests that include login phase at IdentityServer. Recorded test fails at login page because login button is always disabled even after correct credentials are entered in test. Is there some security thing that prevents my automatic tests from clicking the button? And is there a way to prevent this from happening, so that my tests would pass?

**Comment by brockallen** [comment]
IIRC this sounds like the bug in chrome that auto fills the uid/pwd inputs.

**Comment by devblaz** [comment]
I have a similar issue when using some browsers on smartphones. I tried the stock Android browser (Android 4.3) and Dolphin Browser 10.3.1. When i login the first time it is working just fine. If i let the browser save my credentials and try to login again the browser does fill in uid/pwd and the login-button does not work. When i add 1 character and remove it again (workaround to get the button enabled) i can login again.

Is this really a browser issue (i don't think this will be addressed there shortly) or can a small workaround be added in IdentityServer?

**Comment by brockallen** [comment]
What would the workaround be? If you can identify something that will help, let us know.

**Comment by johnkors** [comment]
I would have thought that was due to angulars handling of the forms. Pristine-stuff. But it's been a while since we used the default views..

**Comment by jageall** [comment]
we have a similar issue with knockout. The solution used here is to leave
the button enabled, and do a check before submit.

because the bindings have not been updated due to the events not being
raised properly for autofill we force an update by querying the DOM before
doing the check.

**Comment by brockallen** [comment]
So some hack with a setTimeout checking for values might be sufficient? I dislike the fact that we have to do such things..

**Comment by devblaz** [comment]
Agreed. I guess too that it's something in Angular. But what it is the
smartest thing to do. If we report a bug in Angular no idea when it is
fixed there.

Op 13:27 DO 26 Mrt 2015 schreef Brock Allen <notifications@github.com>:

**Comment by johnkors** [comment]
Solution 1: Drop angular for the Default views, or make angular work with browser auto fill. I'll ask our frontend dev what he did, because we don't have this issue (and we're also using Angular).
Solution 2: Implement your own views.

**Comment by brockallen** [comment]
@johnkors did your front-end person have a workaround?

**Comment by johnkors** [comment]
@brockallen I believe this good old setTimeout directive trick. http://stackoverflow.com/questions/14965968/angularjs-browser-autofill-workaround-by-using-a-directive/14966711#14966711

**Comment by brockallen** [comment]
@johnkors Yea, I tried this one several months back when we had this same discussion then. I tested it and AFAICT it does not work.

**Comment by brockallen** [comment]
It has something to do with the fact that it's a password field -- the browser is preventing any JS in a timer to access the value (inside and outside of angular).

At this point the only solution is to remove the `ng-disabled="form.$invalid"` on the button.

**Comment by brockallen** [comment]
Ok, I've done this on the 1.3.1 branch.
