### ISSUE TITLE
Is it possible to skip application authorization on Implicit flows?

### ISSUE THREAD

**Issue by roryprimrose** [IdentityServer/IdentityServer3#1112]
We are looking at using ID3 for an internal website running under AD. This is so that we can use ADFS via wsFed and have ID3 wrap that into an access token for an Angular client (no server code) that talks to a Web API.

One of the issues raised is the usability of the user being forced to authorize the website to talk to the API. Given that this is an internal only system, is it possible to skip this authorization like in the ResourceOwner flow?

**Comment by leastprivilege** [comment]
Are you talking about the consent screen? If yes - this can be turned off per client configuration.

**Comment by roryprimrose** [comment]
Sweet!!!!! Thank you very much.
