### ISSUE TITLE
Bug in HashedClientSecretValidator 

### ISSUE THREAD

**Issue by saithis** [IdentityServer/IdentityServer3#1113]
I think there is a bug in the HashedClientSecretValidator.
It tries to convert the client secret from base64 and throws an exception if this fails.
Then it compares the not converted client secret with the hashed secret from the request.

So either the client secret is no base64 and the conversion fails, or it is base64 and the compare with the hashed secret fails.

**Comment by leastprivilege** [comment]
PR?

**Comment by loctanvo** [comment]
@saithis Have you actually registered any problems with it? We are using it, and it works fine. I had a look at the code, and the implementation is correct based on what I saw. The convertion to Base64 is just to check the length of the hash. After determining whether Sha256 or Sha512 is used, the comparison is based on two hashes, which again is correct. Did I miss something?

**Comment by saithis** [comment]
@loctanvo Yes, I had problems with it.
I used the OAuth2Client with "wpfsecret" as the client secret and RequestResourceOwnerPasswordAsync. 
In the identity server I tried "wpfsecret" (plain) and "048a72c1365745b5c838ba054757cadac312e9d71d141cdb6efee92281a26e7b" (sha256) as the client secret. 
Both failed with "Invalid hashing algorithm for client secret.".
With the PlainTextClientSecretValidator "wpfsecret" on both sides works.

**Comment by loctanvo** [comment]
Hmm, that's weird. How do you generate the hash? Note that the validator expects a hashed value stored on the client, but you probably have noticed that.

We are using the [Sha256() extension method](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/HashExtensions.cs#L34) to generate our hash. It ensures that the string is base64 encoded as well. That's the same method used under the hood in [`HashedClientSecretValidator`](https://github.com/IdentityServer/IdentityServer3/blob/2c0ef5f7dc3be0b804d1e1734dad634dc1288fad/source/Core/Services/Default/HashedClientSecretValidator.cs#L38), so everything works fine for us. We are saving the hashed value on the client.

**Comment by saithis** [comment]
Ok, I got it working :)
Plaintext on the client and base64(sha256(plaintext)) on the server works.
I was missing the base64(...) on the server, because the name of the Sha256() extension method is a bit misleading.

Thank for the help! :)

**Comment by loctanvo** [comment]
Cool, glad I could help. Close the issue :-) ?

**Comment by saithis** [comment]
Yes, it can be closed.
