### ISSUE TITLE
IdSrv 3 and mvc 4

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1114]
Hi

I'm trying to use IdSrv 3 with one of our applications that are running mvc 4. 
I keep getting a login loop that finally ends in "Bad Request - Request Too Long". Do you know if mvc 4 is supported?

I've added the Session_Start() method in my global asax

I tried upgrading to mvc 5 by creating a new project and copy over all the files and it works fine. However, at this time this is not a desirable solution as it creates other upgrade needs.

**Comment by loctanvo** [comment]
Can you describe your setup? Where do you get the "Request too long", MVC or IdSrv application? Are you using the OpenId Connect Middleware from Microsoft?

Everytime we've experience something similar, is due to the cookie header size being too large (too many cookies) on the request.

**Comment by loctanvo** [comment]
[Related to this](https://github.com/IdentityServer/IdentityServer3/issues/1124)?
