### ISSUE TITLE
JIT compiler encountered an internal limitation

### ISSUE THREAD

**Issue by n-alex-white** [IdentityServer/IdentityServer3#1115]
I’m investigating Identity Server 3 for potential use at our company, but I’m continually coming up against a problem – when I visit https://localhost:44301/identity/.well-known/openid-configuration I have a “JIT compiler encountered an internal limitation” error. I can’t see anything in the issues on Github about it.
 
I’m using version 1.3.0.0 of Identity Server 3 (via nuget), following through the instructions in the identity server documentation. The only change I’ve made from vanilla is loading certificate from personal certificate store rather than from file (as I couldn’t get past an ‘access denied’ message in the latter case). i.e.
 
        X509Certificate2 LoadCertificate()
        {
            //load from personal certificate store
            var store = newX509Store();
            store.Open(OpenFlags.ReadOnly);
            var cert = newX509Certificate2();
            for (int i = 0; i < store.Certificates.Count; i++) {
                if (store.Certificates[i].SerialNumber == "3506FE4F69DC22B340E9C2AF500D4659")
                    cert = store.Certificates[i];
            }
 
            return cert;
        }

I get the following error JSON back:

    {
    Message: "An error has occurred.",
    ExceptionMessage: "JIT Compiler encountered an internal limitation.",
    ExceptionType: "System.InvalidProgramException",
    StackTrace: " at System.Web.Http.HttpRouteCollection.GetVirtualPathRoot(HttpRequestContext     requestContext) at System.Web.Http.HttpRouteCollection.GetRouteData(HttpRequestMessage     request) in    c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\Default ConsentService.cs:line 0 at  System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request,  CancellationToken cancellationToken) in  c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\Default ConsentService.cs:line 0 at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage  request, CancellationToken cancellationToken) at  System.Web.Http.Owin.PassiveAuthenticationMessageHandler. <>n__FabricatedMethod3(HttpRequestMessage , CancellationToken ) in  c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\Default ConsentService.cs:line 0 at System.Web.Http.Owin.PassiveAuthenticationMessageHandler. <SendAsync>d__0.MoveNext() in  c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\Default ConsentService.cs:line 0 --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task  task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.HttpServer. <SendAsync>d__0.MoveNext() in  c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\DefaultConsentService.cs:line 0"
    }

is this a problem that anyone else has seen and resolved?

**Comment by brockallen** [comment]
Are you using the NuGets for IdSvr or are you using it from the source and building it into your own application?

**Comment by n-alex-white** [comment]
In this particular instance I downloaded the sample code for MVC Authentication, built and ran it locally and had this error.

However - I have just set up a VM with a development environment and built and run everything successfully, so this must be a problem on my local machine. Annoying, but not something worth cluttering up discussions here with, so I'll close this question.
