### ISSUE TITLE
Assets folder not registering

### ISSUE THREAD

**Issue by ltraus** [IdentityServer/IdentityServer3#1116]
Hi,

I brought down a new repository example, pulled all the required libraries; and the assets folder doesn't seem to register anything.

It's literally getting a 404 not found.  Previous examples of the code have been working but the only difference here is that I've used IIS Express to host.

I did how ever rig a custom view service secondary thinking it now required it, and that all works fine, but if i go to the root, where it has the "Welcome to Thinktecture IdentityServer"... 

No styles are loaded.

https://localhost:44303/assets/styles.min.css">

Gets a 404.

I'm about to start pulling full repo's and seeing if it breaks there, but just wanted to ask before i get down an entire repo situation if it's seen before, or a known issue with IIS Express?

**Comment by ltraus** [comment]
I shoudl have seen this.

   <modules runAllManagedModulesForAllRequests="true" />

*sigh*... can close?

**Comment by ltraus** [comment]
<modules runAllManagedModulesForAllRequests="true" />

**Comment by brockallen** [comment]
RAMMFAR!

**Comment by paulirwin** [comment]
I just ran into this same issue. Can this be added to the "Getting Started" section on the readme? I'd be happy to submit a PR if you're open to that.

**Comment by brockallen** [comment]
I thought RAMMFAR was already there in the docs somewhere.

**Comment by huysentruitw** [comment]
It's here http://identityserver.github.io/Documentation/docs/configuration/overview.html but maybe it should be added to the Getting started of Readme.md, because this is the first issue everyone is running against :)

**Comment by paulirwin** [comment]
Even a simple line like this would suffice for the Getting Started section of the readme:

> *Note:* If you're hosting in IIS, make sure you [enable RAMMFAR in your web.config file](http://identityserver.github.io/Documentation/docs/configuration/overview.html).

**Comment by leastprivilege** [comment]
Then add it :)

**Comment by mtayyab063** [comment]
i implemented SSO using identityServer3, but i am unable to load css and scripts resources for identityserver login screen. what i am missing?

**Comment by brockallen** [comment]
Any custom assets you need to serve up yourself -- for example, if you're using IIS then ensure it's deployed somewhere so that IIS can serve it up.

**Comment by mtayyab063** [comment]
Great, i got it. thanks @brockallen
