### ISSUE TITLE
idsrv cookies not cleared on logout when alternative httpCookies domain set in web.config

### ISSUE THREAD

**Issue by sickboy** [IdentityServer/IdentityServer3#1118]
With:
```<httpCookies domain=".local.something.net" httpOnlyCookies="true"/>``` in web.config.

On SignIn the cookies seem to be created with that domain set,
but when the cookies are cleared on SignOut, there is no domain specified, so it is probably assuming the actual domain, which in this case is ```auth.local.something.net```

Setup: I have 4 domains, and 4 apps hosted within the same Project (MVC, WebAPI, SignalR and IdentityServer)

Suggestion: Ability to specify explicitly which domain to use for the cookies, so that the same setting can be used across creation and destroy (Or at least on creation so that we can manually match it ourselves to the actual domain)

**Comment by brockallen** [comment]
`<httpCookies>` is an ASP.NET thing - we're on OWIN. So if it happens to use that, then perhaps it's a bug in katana.

**Comment by brockallen** [comment]
Are you looking for a domain feature on the cookies in IdSvr?

**Comment by sickboy** [comment]
@brockallen thanks for the response. Yes the ability to configure the domain would work for me as a workaround to this problem.
I am however open to other suggestions. I had a few in mind myself, some more ideal than others:
- Setup an Owin Middleware that somehow adjusts the default cookie domain used just by idsrv
- Separate ID server from the other apps

**Comment by sickboy** [comment]
I suppose the configurability of the cookie domain might be overkill. Perhaps setting it automatically statically to the domain the idsrv is hosted on might work.
As the cookies in question are supposed to only be usable by the idsrv..

**Comment by brockallen** [comment]
The problem is that IdSvr won't know the domain it's hosted on. You need to tell it with a setting if you want it to emit the domain part of the cookie.

**Comment by sickboy** [comment]
Fair point, there is PublicOrigin on IdentityServerOptions though, perhaps if one sets that, the CookieDomain should follow suit?

**Comment by sickboy** [comment]
Interesting to note; the idsrv.xsrf cookie does actually have the appropriate domain set..
Also if I inspect the headers at the end of the owin pipeline, I find that the idsrv cookies have no domain set, so it must indeed be that the default domain is still being applied by System.Web or Owin..

I'm inclined to remove the httpCookies from Web.config and instead setting the top domain specifically for the cookies that need it.

**Comment by brockallen** [comment]
Well, the comment I will make is that normally IdSvr would be hosted in its own app -- the point is to have a centralized SSO/token service (as opposed to co-hosting it with an app).

**Comment by sickboy** [comment]
Sadly I had to start setting the httpCookies domain again in web.config as the Nonce cookie was being set to the wrong domain now (and seems not configurable). So I suppose I am still in for configurable CookieDomain for idsrv ;-)

**Comment by brockallen** [comment]
Ok, I'll add a domain property to the cookie options.

**Comment by brockallen** [comment]
Ok, I started to add this and thought twice -- I'm still confused why do we need IdSvr's cookies to be cross-domain. Cross-domain cookies are to be used when you have diff apps on different subdomains that need the same cookie. I don't see that as necessary for IdentityServer.

So I think the real problem is that your hosting model for IdentityServer is not the best -- it should be hosted separately (given that the global `<httpCookies>` is somehow stepping on the Katana code). 

At least I'd say this is a bug in the Katana/System.Web layer -- perhaps you should raise it there.

**Comment by sickboy** [comment]
No problem brock, I already split my owin based hostings to a separate non-IIS worker.
Thanks for considering in any case.

**Comment by brockallen** [comment]
And that solved your issue?

**Comment by sickboy** [comment]
Yes as there was no longer a conflict of interest between cookie usages (MVC httpCookies domain vs desired Owin cookie domains for Identity server etc).

**Comment by brockallen** [comment]
Oh right -- due to the app setting in .config. Yep, glad it's now working.
