### ISSUE TITLE
How do we convert nbf and exp of AccessToken into local time

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1119]
How we convert the parameters to local time?.

**Comment by brockallen** [comment]
Those are epoch times from UTC.

**Comment by skatukojwala** [comment]
convert using ?

public static DateTime FromUnixTime(this long unixTime)
{
    var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
    return epoch.AddSeconds(unixTime);
}

public static long ToUnixTime(this DateTime date)
{
    var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
    return Convert.ToInt64((date - epoch).TotalSeconds);
}

**Comment by leastprivilege** [comment]
https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/master/source/Client.Shared/EpochTimeExtensions.cs

**Comment by skatukojwala** [comment]
Thank you for the information.
