### ISSUE TITLE
Auto consent for selected clients

### ISSUE THREAD

**Issue by dzolnjan** [IdentityServer/IdentityServer3#1120]
Is there way to have my implicit clients authenticating/authorizing against my IdSrv not having to show them consent screen and requiring to click Yes (on login)?

Might seem odd to my users needing to give explicit consent with website they already logged into.

**Comment by johnkors** [comment]
http://identityserver.github.io/Documentation/docs/configuration/clients.html (RequireConsent)

**Comment by mikeandersun** [comment]
Set RequireConsent property of client to false.

**Comment by dzolnjan** [comment]
Works, thanks.

**Comment by polkduran** [comment]
@johnkors's provided link is broken.
Here is a link from the documentation: 
http://docs.identityserver.io/en/release/reference/client.html?highlight=RequireConsent
