### ISSUE TITLE
Authentication Failure logs as an error

### ISSUE THREAD

**Issue by michaeldotknox** [IdentityServer/IdentityServer3#1122]
I'm wiring up events for our implementation using Resource Owner flow.  I noticed that user authentication failures result in an Error being logged.  Is this mainly to accommodate Pen Tests?  I want to be able to proper direct the messages so they can be properly handled.

**Comment by leastprivilege** [comment]
What would you prefer?

**Comment by michaeldotknox** [comment]
I think it depends.  If best practices says that they should be logged as an error, then I'll change my logging configuration so I can log those to a different place or in a different way.  I can certainly see why those might want to be logged that way to try to catch someone attacking the system.
But at the same time, it would be nice if that was a way to turn that off, or turn in down to a warning or even an info.  We are already capturing authentication failures and successes, so we end up logging this information twice.

**Comment by leastprivilege** [comment]
OK - so warning is OK for you?

**Comment by michaeldotknox** [comment]
Yeah, I think that would be great

**Comment by jageall** [comment]
+1 from us to

**Comment by johnkors** [comment]
aye. +1

**Comment by mschulz531** [comment]
Also consider the idea of separating the login success/failure events into an AUDIT log instead of an error or warning.

**Comment by leastprivilege** [comment]
@brockallen owns the login events. We will discuss.

**Comment by leastprivilege** [comment]
@brockallen owns the login events. We will discuss.

**Comment by brockallen** [comment]
If you're already logging this in your IdMgmt system, then perhaps just filter this event type or this event category from your event service. This is an event that should be raised, and it's certainly not a success event.

**Comment by leastprivilege** [comment]
any more comments? close?

**Comment by michaeldotknox** [comment]
I completely agree that it should be logged, and I certainly agree that it should be something above an informational event, but I'm not sure if a single login failure raises to the level of an error.  To me, an error indicates something that needs action; someone specifically tracking down the reason for the error, while a warning is something that should be watched to see if it continues before taking action.
While I certainly can log this event to another location, or even block it with a configuration change, doing that with an error makes me a little nervous when we are talking about an error event.

**Comment by brockallen** [comment]
Well, we have errors and failures. Errors are more of the things that require action. Failures and things that failed, but might not require action. Perhaps it's just mismatched semantics.

**Comment by michaeldotknox** [comment]
Agreed, but the department that will be monitoring the server is going to see error and treat it as suc, rather than see a warning and monitor the situation.

**Comment by brockallen** [comment]
Well, feel free to surface the login failure as a warning to your admin dashboard.

**Comment by michaeldotknox** [comment]
After looking at this further, and after some discussions, I think we are going to create a custom LogProvider, which will provide the granularity that we need for logging the errors coming from the TokenRequestValidator.
