### ISSUE TITLE
Accessing the ClientStore from the UserService

### ISSUE THREAD

**Issue by protoforge** [IdentityServer/IdentityServer3#1123]
There's information in the client definition that I need when authenticating users.

What's the cleanest way of accessing the registered clientstore (or cached clientstore) from a IUserService?

Thanks...

**Comment by brockallen** [comment]
Inject it as a ctor param.

**Comment by protoforge** [comment]
Very cool...  And a little scary how it automatically handled it for me...  Thanks!

        private readonly IClientStore _clients;

        public DataDoorsUserService(IClientStore clients)
        {
            _clients = clients;
        }

        private async Task<Client> GetClient(string clientId)
        {
            var client = await _clients.FindClientByIdAsync(clientId);
            return client;
        }
