### ISSUE TITLE
Does IdentityServer3 support client certificates?

### ISSUE THREAD

**Issue by tofutim** [IdentityServer/IdentityServer3#1125]
I would like to secure the communications between client and server so that even in the event of a compromised network (MITM), everything will be secured. I think client certificates would do the trick here, but I'm not exactly sure yet how to incorporate this into IdentityServer3.

**Comment by brockallen** [comment]
Is this what you're looking for?

https://github.com/IdentityServer/IdentityServer3/issues/309
