### ISSUE TITLE
Impossible to Authorize JSONP call with header Authorization

### ISSUE THREAD

**Issue by AlbertoLeon** [IdentityServer/IdentityServer3#1126]
I use a third party javascript calendar (fullcalendar) and it uses JSONP calls to fetch feeds of events.

To modify the headers of a JSONP is impossible. Because it is a dynamic hack in the DOM, as I understood.

So is there any solution or alternative? Perhaps pass the access token via query string? Thanks.

**Comment by brockallen** [comment]
You could, I suppose, but then you're leaking the tokens into those server logs. It's discouraged.
