### ISSUE TITLE
make possible to add logo icon on ExternalProviders

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#1127]
Hello,
I try to modified the default login page and i want to add custom logo icon on the  external login providers links.
if is possible like on Client model:
```
   ...
   LogoUri = "data:image/png;base64,iVB.....
   ...
```

Or how to do this if is any possibility?

**Comment by johnkors** [comment]
No, IdSrv uses only a string to represent an external provider that it gets from what middleware you've configured for it. There is no explicit model for that. You would have to map that string (i.e. "facebook", "google", "federation") to a model containing a image in your custom ViewService.

**Comment by totpero** [comment]
how to do this? have you one example please

**Comment by johnkors** [comment]
No, sorry - no sample that I know of.

**Comment by brockallen** [comment]
I'll leave this up to a custom view service.

**Comment by dapug** [comment]
I can't imagine any identity system having text only display of 3rd party sign-in. Default service is 100% useless IMO (full stop, my team cannot use it pretty much because of this one issue). Seems quite extreme to write up a custom view service just to add one property.

Can't this be a simple config option?  **LoginPageLink** should have a **Logo** property added, and then **LoginPageLinkExtensions.Render(...)** would add it.   

I would modify the source and post a pull request, however, I'm not sure where to go from here.  The biggest hurdle is, where does the user set the values?  It cant be in **IdentityServerOptions** because it is more of a property of each respective provider.  But we cannot expect to modify all the provider plugins out there, so then those would need to be extended some how, or we'd have to have IdentityServerOptions actually take a collection of ProviderName / Logo to match and stitch in the logos according to the provider names it picks up from IdentityServerOptions.

**Comment by brockallen** [comment]
Yea, all good questions @dapug. Maybe this is why it's best for custom views? :P Also, there is a id property, IIRC, on the rendered model data, so you could simply have this logic in the JS.

**Comment by dapug** [comment]
actually, I'm not seeing how it can be done in custom views either.  Even that relies on these properties coming from the LoginViewModel and AdditionalLinks collection which is part of IdSrv, not part of the custom view service.

I'm not keen on doing it as an "afterthought" in JS, though I see your point.

**Comment by woodwardmatt** [comment]
@dapug I've achieved this through overriding the login view (with a local /templates/_login.html file) then customised the html to include some font awesome implementation of the social icons:

                <ul class="list-inline" style="margin-bottom: 0;">
                    <li ng-repeat="provider in model.externalProviders">
                        <a class="btn btn-default btn-provider btn-{{provider.type}}" href="{{provider.href}}"><i class="fa fa-{{provider.type|lowercase}}"></i>&nbsp; {{provider.text}}</a>
                    </li>
                </ul>

I found that I also had to customise the DefaultViewServiceOptions & CspOptions within the IdentityServerOptions (in your startup.cs file) to enable this:

            var viewOptions = new DefaultViewServiceOptions();
            viewOptions.Stylesheets.Add("/assets/custom.css");
            viewOptions.Stylesheets.Add("https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css");
            viewOptions.CacheViews = false;
            factory.ConfigureDefaultViewService(viewOptions);

            var cspOptions = new CspOptions();
            cspOptions.Enabled = true;
            cspOptions.ScriptSrc = "'self' ajax.googleapis.com";
            cspOptions.StyleSrc = "'self' maxcdn.bootstrapcdn.com";
            cspOptions.FontSrc = "'self' maxcdn.bootstrapcdn.com";

            var options = new IdentityServerOptions
            {
             ....
             CspOptions = cspOptions,
             ....
             }

             app.UseIdentityServer(options);

End result with some customising of the CSS for colours etc was this:

![image](https://cloud.githubusercontent.com/assets/461398/11202734/46f27d80-8d3b-11e5-8c80-0cafd3446683.png)

Can't tout that I've used best practices etc as I'm still finding my way a little, but hopefully that gives you an avenue you can pursue. Hope that helps :) Any feedback on that approach @brockallen would be welcomed :)

**Comment by brockallen** [comment]
Looks great.

**Comment by merijndejonge** [comment]
Hi,
I've done a similar thing, however I'm trying _not_ to use the external references to maxcdn.bootstrapcdn.com but use embedded resources instead. 

With the DefaultViewServiceOptions approach I can simply add the css for font-awesome like so:

```
var viewOptions = new DefaultViewServiceOptions();
viewOptions.Stylesheets.Add("/Content/font-awesome.min.css");
idServerServiceFactory.ConfigureDefaultViewService(viewOptions);
```
On my local iisexpress this all works nicely however once deployed on Azure the fonts can't be found yielding a 404 error for e.g., 

- https://xxx.yyy.zzz/fonts/fontawesome-webfont.woff2?v=4.5.0 

DefaultViewServiceOptions doesn't have an option for adding fonts or other assets. So what is the appropriate way to do this?

**Comment by brockallen** [comment]
So the rest of the IdSvr embedded resources work ok, yes?

If you are doing your own embedded resources, did you enable the static file middleware that loads from embedded resources?

**Comment by merijndejonge** [comment]
I'm not sure what you mean with enable the static file middleware.

I've managed to adjust te layout of the login pages by creating a couple of templates. 
I've also successfully added bootstrap.css, fontawesome.css and a custom css using viewOptions.Stylesheets.Add.
These are all embedded resources, right?

**Comment by brockallen** [comment]
> I'm not sure what you mean with enable the static file middleware.

If you want the web server to emit files from embedded resources then you need a middleware to do this. We use the static file middleware for this.

> These are all embedded resources, right? 

Only if they're compiled into your assembly.

**Comment by merijndejonge** [comment]
OK, so given that I have a top level folder "fonts" in my solution in which the fontawesome fonts live. Can you explain what I need to do to get them served and be accessible as e.g. https://xxx.yyy.zzz/fonts/fontawesome-webfont.woff2?v=4.5.0? Or is there any documentation you can point me at?
Thanks in advance!

**Comment by brockallen** [comment]
I think what you've done should work. The browser gets what back from the server? Do a HTTP trace.

Oh, also, it might be woff2 -- if the mimetytpe is not registered, IIS issues 404 even if the file exists.

**Comment by merijndejonge** [comment]
Thanks @brockallen it was the mimetypes. I needed to add the following to the system.webServer section of my web.config:
```
      <!-- mimetypes for fontawesome fonts-->
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
```
Without the `remove` lines it didn't work.

**Comment by totpero** [comment]
@merijndejonge yes mimetypes is the problem:
http://stackoverflow.com/questions/32300578/how-to-remove-error-about-glyphicons-halflings-regular-woff2-not-found/32300611#32300611
