### ISSUE TITLE
Using CORS, Preflight  and Oauth server

### ISSUE THREAD

**Issue by alokshriram** [IdentityServer/IdentityServer3#1132]
Hi, 
I have been playing around with Identity server and the samples that are provided along with the project.  I have at this point configured my WebAPI application to host the Identity server and the app is setup to use OpenIdConnectAuthentication.  

For testing I have protected one API http://localhost:3434/api/activity/41184/event/ with the Authorize attribute.  When I browse to it from a website everything works correctly and I get the right prompts for me to Authenticate and get the correct claims back and the APIs is allowed.

If I use the JavaScriptImplicit client provided in the [sample]([https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient "Sample") repository , and first click on the Login with Access Token, things look great.  However, when I try to call the service.. I see the following error in the console of my browser.

>XMLHttpRequest cannot load http://localhost:63248/api/activity/41184/event/10. The request was >redirected to 'https://localhost:44302/identity/connect/authorize?client_id=limeadewebsite…>E3LWEwZGQtYWIyZWNkYmFkMjZlMWM3NTM1YmQtYzhhZS00ZTI1LTljYWEtMzc0ZWNmYzcyO>DMx', which is disallowed for cross-origin requests that require preflight

As per my understanding Preflight is enabled when extra headers are requested in a request, which is the case in OAuth (Authorization header).  When the WebAPI receives a request it will redirect to Identity Server to validate the token, which is the redirect.  

At this point I am not sure OAUTH is supposed to work with CORS.  What am I missing ?
Please let me know in case you need any more details around my configuration.
Any help would be appreciated.
Cheers
-alok

**Comment by johnkors** [comment]
Seems like your web app auth are doing work at your API routes. Try to separate your API from your web app auth stuff. Either by using 2 apps, or by isolating the pipelines.

**Comment by alokshriram** [comment]
@johnkors  Thanks john. I am not sure what you mean by "my web app auth is doing work at your API routes" .  Are you suggesting having one web app running OAuth Server, and the other running the WebAPI with the client part setup ?
I have tried that and ran into the same issue.  At that point I thought the reason was that the OAuth Client and Server needed to be on the same domain, which is why I put them together.

Could you clarify on what you mean by isolating the pipelines ?
thanks!!

**Comment by johnkors** [comment]
I'm saying that your authorization mechanisms for you web app is running in the part of your host belonging to your API.  I would not expect a redirect response from an API, but a 401/403. 

By isolating the pipelines, I mean make sure your authorization filters/handlers defined for MVC (if using MVC) are not run for routes defined for Web API and vice versa.

There is no requirement running the clients at the same domain as idsrv, btw.

**Comment by alokshriram** [comment]
@johnkors Thanks for your response.  It took me a little while to grok it and a couple of experiments later I fixed my issue by using BearerTokenAuthentication, which solves our WebAPI problem.  
We did have some MVC and WebAPI bits in the same pipeline, which was what was causing the issues.
Thanks for your assistance on this.
