### ISSUE TITLE
Partial Login

### ISSUE THREAD

**Issue by aosgo** [IdentityServer/IdentityServer3#1135]
Not sure if related to #1083 but since upgrading to 1.3.0 and then 1.4.0 our partial logins fail. We have a custom user service, which checks if a user account has been confirmed or if their password has expired e.g.

     if ( !localIdentity.Confirmed )
     {
                return new AuthenticateResult("/AccountConfirmation",
                    localIdentity.UserName,
                    localIdentity.UserName,
                    identityProvider: IdentityProvider.ABCinc.IdsrvV3,
                    authenticationMethod: "Password");
      }
      if ( localIdentity.HasPasswordExpired )
      {
                return new AuthenticateResult("/SelfService/ChangePassword",
                    localIdentity.UserName,
                    localIdentity.UserName,
                    identityProvider: IdentityProvider.ABCinc.IdsrvV3,
                    authenticationMethod: "Password");
      }

The ABCinc.idsrv.partial cookie is set, but it bounces back to the login page rather than redirecting to the confirmation or change password pages. 

Checking the logs I get the following...

Error: Check session endpoint enabled, but SessionId is missing { "ClientId":    "abcinc.Identity.SelfService", "ClientName": "abcinc Identity Self Service", "RedirectUri": "https://localhost:44300/", "AllowedRedirectUris": [ "https://identity.abcinc.net/", "https://localhost:44300/" ], "SubjectId": "unknown", "ResponseType": "code id_token", "ResponseMode": "form_post", "Flow": "Hybrid", "RequestedScopes": "openid profile abcinc", "State": "OpenIdConnect.AuthenticationProperties=removedforbrevity", "Nonce": "removedforbrevity", "Raw": { "client_id": "abcinc.Identity.SelfService", "redirect_uri": "https://localhost:44300/", "response_mode": "form_post", "response_type": "code id_token", "scope": "openid profile abcinc", "state": "OpenIdConnect.AuthenticationProperties=removedforbrevity", "nonce": "removedforbrevity" } }
Info: Authorize request validation success { "ClientId": "abcinc.Identity.SelfService", "ClientName": "abcinc Identity Self Service", "RedirectUri": "https://localhost:44300/", "AllowedRedirectUris": [ "https://identity.abcinc.net/", "https://localhost:44300/" ], "SubjectId": "unknown", "ResponseType": "code id_token", "ResponseMode": "form_post", "Flow": "Hybrid", "RequestedScopes": "openid profile abcinc", "State": "OpenIdConnect.AuthenticationProperties=removedforbrevity", "Nonce": "removedforbrevity", "Raw": { "client_id": "abcinc.Identity.SelfService", "redirect_uri": "https://localhost:44300/", "response_mode": "form_post", "response_type": "code id_token", "scope": "openid profile abcinc", "state": "OpenIdConnect.AuthenticationProperties=removedforbrevity", "nonce": "removedforbrevity" } }
Info: User is not authenticated. Redirecting to login.
Info: Redirecting to login page
Debug: Protecting message: {"ReturnUrl":"https://localhost:44300/identity/connect/authorize?client_id=abcinc.Identity.SelfService&redirect_uri=https%3A%2F%2Flocalhost%3A44300%2F&response_mode=form_post&response_type=code%20id_token&scope=openid%20profile%20abcinc&state=OpenIdConnect.AuthenticationProperties%3Dremovedforbrevity&nonce=removedforbrevity","ClientId":"abcinc.Identity.SelfService","AcrValues":[],"Created":635633198625833267}
Info: Start authorize request
Info: Start authorize request protocol validation
Debug: Cache hit: openid,abcinc,profile
Debug: Cache hit: abcinc.Identity.SelfService
Info: redirecting to: https://localhost:44300/SelfService/ChangePassword
Info: issuing cookie (partial login)
Info: Login credentials successfully validated by user service
Debug: Cache hit: abcinc.Identity.SelfService
Info: Login page submitted

**Comment by brockallen** [comment]
Well, cookies don't bounce you anywhere -- it must be some of your code somewhere that's doing that.

I'd be curious what claims are present in the partial login in your page ("/AccountConfirmation" for example).

**Comment by parkinsona** [comment]
This is interesting. 
After I deployed 1.4 to TEST (which is load balanced), my partial login failed initially as well.

I had to do something else, and when I came back to it, and I cleared cookies, it started working again.

**Comment by aosgo** [comment]
@brockallen There were no claims present in /AccountConfirmation

**Comment by aosgo** [comment]
@brockallen Also in this code which is on the /SelfService/ChangePassword action authentication is null

     var ctx = Request.GetOwinContext();
      var authentication = await ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType);
      if (authentication == null)
      {
                return RedirectToAction("Index", "SelfService");
       }
       return View();

**Comment by aosgo** [comment]
OK Solved. If it helps others these were the problems
   - ChangePassword needed to be under /identity so added the following route [Route("identity/ChangePassword")]
   - Cookie path is case sensitive as per app path so route has to be identity not Identity assuming app.Map("/identity", idsrvApp =>
   - I also removed authenticationMethod: "Password"
