### ISSUE TITLE
CORS problems when using AJAX from browser to WebApi

### ISSUE THREAD

**Issue by ninety7** [IdentityServer/IdentityServer3#1138]
I set up an identityServer3 1.4.0 and a separate MVC and WebApi app where some actions are protected using the [Authorize] attribute.
Once I access the protected page (eg. /Home/About), the JS makes an ajax call to another protected action (GET /Resources) and everything works fine. My problem seems to be when the identity server app gets recycled. In this case, any protected WebApi action will respond the ajax call with a 302 to redirect to the IdentityServer, which is fine. Somehow, the authentication proccess fails and this is the error message on the Javascript console:
```
XMLHttpRequest cannot load http://localhost:51705/connect/authorize?client_id=mvc&redirect_uri=http%3A…. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1423' is therefore not allowed access.
```
I enabled tracing on the IdentityServer to get more info, and this is the message I get as soon as the client makes the ajax request:
```
CORS request made for path: /connect/authorize from origin: http://localhost:1423 but rejected because invalid CORS path
```
I have also tried both default cors policy services:
```c#
var factory = InMemoryFactory.Create(
    users: Users.Get(),
    clients: Clients.Get(),
    scopes: StandardScopes.All);
var corsPolicyService = new DefaultCorsPolicyService();
corsPolicyService.AllowAll = true;
factory.CorsPolicyService = new Registration<ICorsPolicyService>(corsPolicyService);
```
Any help somebody can give me?

**Comment by johnkors** [comment]
You're using the same authorizaiton mechanisms for WebApi as MVC. Those should be seperated. In the MVC part a redirect makes sence, whereas at your API you want to return a forbidden or not authorized. Check your global filters.

**Comment by ninety7** [comment]
Forgot to mention, I'm using ASP.NET 5, so mvc==webapi. Everything is working fine, except for the CORS part.

**Comment by leastprivilege** [comment]
We haven't done any testing on ASP.NET 5 yet. If you figure it out, let us know.

**Comment by jlarmbruster** [comment]
I am getting this error. Can someone tell me why?


w3wp.exe Error: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 5/9/2015 12:35:53 AM +00:00 -- Unhandled exception
System.ArgumentException: Keyword not supported: 'id'.
   at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoo
