### ISSUE TITLE
Question: Automatic login after registration

### ISSUE THREAD

**Issue by ChrisVinall** [IdentityServer/IdentityServer3#1139]
I'm sure this has been asked before but I can't find it. I've implemented a user registration page, which currently redirects back to login after registration, preserving the original signin string. This is a pretty bad user experience and I'd rather just log them in automatically.

I found this from Brock on #809 which sounded somewhat promising:

> Have the registration system generate a nonce and put in the registration DB. Then use acr_values and pass the nonce to IdSvr. Use PreAuthenticate to verify the nonce in the DB to know the user, delete the nonce from the DB, and log the user in.

But the Authorize request has already been made, so I can't pass in new acr_values. I can't even go back to the client and instruct it to make a new request including a nonce, because I can't read SignInMessage properties in my custom MVC controller, so I don't even know which client made the Authorize request.

Any ideas?

**Comment by loctanvo** [comment]
We are doing the following:

1. The Login view also hosts the registration form.
2. When the user registers, an AJAX post is done to our api to register the new user
3. Upon successful creation in step 2, we submit the login form with the same credentials

We implemented this quite long ago, and there may be some other ways of achieving this functionality. From the top of my head, I'm thinking about two other alternatives:

1. Could you use partial sign in to redirect the user to a registration context, and then continue the login flow upon creation completed?
2. [IssueLoginCookie](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinExtensions.cs#L123) is an extension point to actually log the user in programmatically. However, last time I gave it a try, I wasn't sure where to redirect the user afterwards. In other words, the same problem as you are experiencing.

A last comment on the SignInMessage: as long as you can retrieve the cookie serverside, you just need to ensure that your apps are using the same data protector in able to unprotect the content. Have not done that myself though, so not sure if anything is internalized or not.

**Comment by brockallen** [comment]
There's also now a new API on the OWIN environment to issue the primary authentication cookie.

**Comment by ChrisVinall** [comment]
Ah thanks @loctanvo - hadn't thought of that for some reason. That seems like the simplest way forward. I'll close the issue - although it would be good if idsrv had some general way to "resume" a login based on signin ID. Not sure what the security implications of that are though.

Regarding the cookie unprotection machinery, I was doing that earlier for other purposes but have scrapped it. It requires two internal classes from idsrv core, so I had copied them out of the source into my host project to be able to use them, which felt a bit hacky.
