### ISSUE TITLE
[question]:How to use the owin extensions from a MVC controller

### ISSUE THREAD

**Issue by TheAndroidMachine** [IdentityServer/IdentityServer3#1140]
My goal is to log in the user after he/she has registered. 
I have already read this #1139 and I'm aware of the IssueLoginCookie API but I'm not sure if it is possible to use this API from inside a MVC controller.

If I map Idsrv like this:
app.Map("/identity", idsrvApp =>
{
     idsrvApp.UseIdentityServer(opts);
 });

idsrv is never started when the requests target a MVC controller. 

Running a code like this inside the MVC world:
var env = Request.GetOwinContext().Environment;
var authLogin = new AuthenticatedLogin
 { 
               ...
  };
env.IssueLoginCookie(authLogin);

will generate an exception. It also applies to the other extension methods.

Am I missing something?

**Comment by leastprivilege** [comment]
You MVC controller must run "under" the idsrv map - `[Route("identity/register")]`

Otherwise the pipeline (and the cookie) won't be in scope

**Comment by TheAndroidMachine** [comment]
It did the trick. Thanks a lot!
