### ISSUE TITLE
Client redirects to Identity server after every 2 odd minutes

### ISSUE THREAD

**Issue by sandeepgaikwad** [IdentityServer/IdentityServer3#1143]
I have been struggling with this issue for quite some time now.
Basically I am facing two issues, but before I share the issues, here is some background of my configuration:
I have Identity server as separate application and my client app redirects to this app for authentication/authorization.
I have a client with following configuration:(all standard)
flow = implicit 
IdentityTokenLifeTime=60
AccessTokenLifeTime=360
AuthorizationCodeLifeTime=300,
etc
All required methods in client are decorated with [Authorize] attribute.
Issue#1: After successful login to client, if I do not do any activity for say 2 minutes (approximately) and then hit  a action which is decorated by "[Authorize]", I can see that my browser is redirected to Identity server and then comes back, looks like it refreshes the tokens?
My question is: is this a normal behavior? 
Secondly if I keep my client ideal for hours or for entire day and the later click some link on the client, it still goes to Identity server and client is authorized implicitly. 
Ideally I would like to see the session timing out and then the login page should be presented asking for credentials. 
Is there a configuration to do this?

Issue#2: I have a report page in my client, which has several ajax calls to controller action methods of the same client (all my controller action methods are decorated with 'Authorize] attribute).
If this report page is ideal for couple of minutes and then I trigger some ajax call, the load fails with following message on browser console:
![image](https://cloud.githubusercontent.com/assets/5610277/6962403/cc78000e-d951-11e4-850c-35dcc3889913.png)
At this stage if I Cntrl+F5 my browser and then trigger the ajax call, the load succeeds.

I am sensing that this is cross domain call issue, and if that's the case, not sure how this is a CORS call. Because my ajax call is to my action method, which in turn will trigger redirect to IdSvr

**Comment by johnkors** [comment]
Issue no 1 : Normal yes, but this has to do with the Katana middleware you're using - not IdSrv. It has a default to set the client cookie lifetime to the lifte time of the id_token.
The cookie at idsrv is configurable, yes. Look for Cookie Options in the docs.

Issue 2.: Yes, you need to handle AJAX calls diffferent to a serverside call. I would use another Authorize attribute that returns 401/403 instaed and handle that in response in JavaScript accordingly. Or just handle the 302.

**Comment by sandeepgaikwad** [comment]
I changed my IdSvr to allow CORS by adding following to Global.asax:
protected void Application_BeginRequest(object sender, EventArgs e)
        {
            HttpContext.Current.Response.AddHeader("Access-Control-Allow-Origin", "*");
        }
    }

And now the browser returns following error from the ajax call:
HTTP status:200
Error: The error message is the html page of login.html with an additional information:
<script id='modelJson' type='application/json'>{&quot;errorMessage&quot;:&quot;There is an error determining which application you are signing into. Return to the application and try again.&quot;,&quot;requestId&quot;:&quot;00000000-0000-0000-3600-0080000000b9&quot;,&quot;siteUrl&quot;:&quot;http://localhost:44333/accounts/&quot;,&quot;siteName&quot;:&quot;Identity Server&quot;,&quot;currentUser&quot;:null,&quot;logoutUrl&quot;:&quot;http://localhost:44333/accounts/logout&quot;}</script>
    <script src="/accounts/assets/scripts.js"></script>

Please note that I do not get this error every time, this happens only I leave the app ideal for a minute or so.

**Comment by sandeepgaikwad** [comment]
John: I am not clear on reply #2: 
My ajax call is to a action method in my own application and not outside the application.
In above case my ajax call does not trigger controller action method instead simply returns error mentioned above.

**Comment by johnkors** [comment]
Yes, and it does this due to you using the MVC Authorize attribute on your API action/controller. You need to change this mechanism, or handle it in JavaScript. The default Authorize-attribute of MVC uses whatever authentication mechanism you have set up, and it will do a redirect to a login page (the 302 you're seeing in your AJAX req.). For MVC that makes sense. For API calls using AJAX from JavaScript it does not. So what I propose is that you use custom Authorize attribute that returns an appropriate status code instead (401/403). Make sense?

**Comment by sandeepgaikwad** [comment]
So if I understand correctly, what you are suggesting is to override the 'Authorize' attribute, right?
But still unclear how that would help, can you point me to some example?
Here is my controller action method:
[Authorize]
        public JsonResult GetData()
        {
            if (!HttpContext.CheckAccessAsync("Read", "ResourceType").Result)
            {
                throw new HttpException((int)HttpStatusCode.Forbidden, "Unauthorized Access");
            }
}
This controller method is being called from a view using ajax call.
In my controller I want to see if the user is authorized to access the method.

**Comment by sandeepgaikwad** [comment]
Let me re-phrase my question if I have made it too complicated.

I have a controller action method Index (default), which is decorated with 'Authorize'.
So whenever this controller is hit, the application redirects to IdSvr and gets the ClaimsPrincipal object.

The Index  action method returns a view. 
In this view I have "Refresh some table" button, which refreshes a specific data table on the view.
Now, "Refresh" button calls another action method 'GetData' from the same controller and the call to this action method is via ajax.
So, if I hit the controller, the view is loaded and I immediately hit this refresh button things work perfectly fine, but if I hit the controller, view is loaded and I do not do any activity for couple of minutes and then hit the "Refresh" button, then I get CORS error.

**Comment by brockallen** [comment]
On the OpenIdConnect middleware, did you set the `UseTokenLifetime` to `false`?

**Comment by sandeepgaikwad** [comment]
Nope, I am not using UseTokenLifetime = false at my client.
I also tried by setting this parameter to True, but no help.
Do you have any examples which depict this scenario?

John: I read the Cookie Options documentation, and it says the Cookie Expiration is 10 hours by default, which is good enough for me.
(note: I tried with following config at my IdSvr app:
 var options = new IdentityServerOptions
 {
                   CookieOptions = new Thinktecture.IdentityServer.Core.Configuration.CookieOptions
                        {
                            SlidingExpiration=true,
                             ExpireTimeSpan=System.DateTime.Now.AddMinutes(60);
                        },
 }

but still after a minute it tries to renew by redirecting to IdSvr, is there any means by which we can change this behavior at the middleware?

**Comment by leastprivilege** [comment]
UseTokenLifetime must be set to false - otherwise the the cookie options settings are not effective.

**Comment by sandeepgaikwad** [comment]
This works, thanks
so, if I configure the CookieOptions at IdSvr as below:
CookieOptions = new Thinktecture.IdentityServer.Core.Configuration.CookieOptions
                        {
                            SlidingExpiration=true,
                            ExpireTimeSpan=System.TimeSpan.FromHours(60),
                        },
with UseTokenLifetime =false at client,
then will my cookie expire after one hour? aafter which user will have to login again?
Thanks for your help

**Comment by leastprivilege** [comment]
IdentityServer and your application have two independent and unrelated cookies. Each are configured using the corresponding cookie options.
