### ISSUE TITLE
LogProvider.GetCurrentClassLogger may fail on x64 servers

### ISSUE THREAD

**Issue by appetere** [IdentityServer/IdentityServer3#1144]
The LibLog library seems to have an issue that means a call to `LogProvider.GetCurrentClassLogger` will sometimes fail on x64 systems.

There is an issue on the [LibLog repo](https://github.com/damianh/LibLog/issues/52) about this.

Using `LogProvider.GetLogger(string.Empty)` still works reliably, as it doesn't use the `StackFrame` class, to work out the class-name.

I can't give you an exact way of reproducing it, as it seems to depend on what optimization the compiler decides to do.  For example, everything worked fine when deployed to our Windows2012 R2, x64 servers with IdentityServer1.1 on .NET4.5.1, but now I'm using IdentityServer1.4 on .NET4.5.2 the problem exists.

If the call to `LogProvider.GetCurrentClassLogger` is made in a constructor with only a few lines of code (eg a custom IUserService implementation) I see the problem.  But if I add some conditional if/then statements into the constructor, the call will work fine.  So seems to be related to the optimizations that the compiler is able to do.

Running locally on my Windows8.1 dev machine I have never seen the problem.

**Comment by leastprivilege** [comment]
I've seen this issue - but you would not call GetCurrentClassLogger in a ctor.

You call it as part of a `private static readonly` class level declaration.

**Comment by appetere** [comment]
Ah yes, I'd created an instance-variable for the logger instead of a static-variable - thanks for pointing that out.  I'll try it again next week using a static and will close the issue if it all runs fine.

**Comment by appetere** [comment]
My calls to `GetCurrentClassLogger` now work fine when deployed to x64 server, after assigning the result to a static variable.

So, using the intended pattern, there doesn't seem to be a problem and I'm happy for this issue to be closed.

(Note that damianh at LibLog is reviewing the implementation as part of LibLog issue 52, so the LibLog code may be updated).
