### ISSUE TITLE
 Add frame-src to CspOptions and include in CSP header

### ISSUE THREAD

**Issue by dvle** [IdentityServer/IdentityServer3#1145]
Adding facebook like button with IFrame but could not specify frame-src.

Got it to work with this:
options.CspOptions.ScriptSrc = "; frame-src https://www.facebook.com;";

**Comment by brockallen** [comment]
Do you really want to include someone else's JavaScript on the login page?

**Comment by dvle** [comment]
It's a requirement from the product owner.

**Comment by brockallen** [comment]
You might want to just mention that the login page is an odd place to have something like that.

**Comment by dvle** [comment]
Certainly can.

**Comment by leastprivilege** [comment]
and with "odd" - Brock means insecure. You want to lock down your login page as much as possible.

**Comment by brockallen** [comment]
So what are we going to do with this issue?

**Comment by dvle** [comment]
Have you decided on whether or not you'll be adding support for frame-src?  I don't see a reason not to if the library already supports script-src, unless you see otherwise.

**Comment by brockallen** [comment]
I guess we can add this. IMO doing that on the login page is a bad idea, though, but I can't stop you from doing it.

**Comment by dvle** [comment]
Yeah, I agree with you, having someone else's script being able to run on your login page is not safe.

**Comment by leastprivilege** [comment]
is this still required?

**Comment by dvle** [comment]
I have little control over how it should all work :/ but as of right now, the requirement is still there and the work around is working for us to get the script on the page at the moment.  I don't know how you guys decide on what features get in; my only concern is the possibility of a future change that might break our work around if this doesn't get in.

**Comment by brockallen** [comment]
Ok, we'll add it (since you can obviously subvert it by chaning the source code).

**Comment by dvle** [comment]
Thank you.

**Comment by edwinf** [comment]
@brockallen I would request this as well.  My product owner wants to add reCaptcha to our login page and the frame source is the one piece we're missing.   (the above workaround is what we'll do in the short term).  If it would help, I can submit a PR.

**Comment by brockallen** [comment]
Done on dev
