### ISSUE TITLE
Resource owner password credentials grant. Remembering user

### ISSUE THREAD

**Issue by feina** [IdentityServer/IdentityServer3#1150]
Hi,

I want to connect an existing website to Identity Server.
The website will present its own login form to the users. The website server will authenticate the user's credentials with Identity Server using the resource owner password credentials flow. On successful login a standard session cookie will be sent to the user's browser.

When the user visits the site another day, I want to be able to recognize her without having to log in.

In this case, should the website server reconnect with Identity Server? Must the website server keep any special data from the last user visit?

Thanks

**Comment by brockallen** [comment]
You dont' get SSO with resource owner flow --- you must redirect to IdSvr if you want SSO.

**Comment by mpaul31** [comment]
hi brock

is the login page baked into the IdSvr or are we able to replace it with one of our own?

**Comment by brockallen** [comment]
Most things in IdSvr are customizable:

https://identityserver.github.io/Documentation/

**Comment by feina** [comment]
Is there any technique to handle SSO in the website server and delegate the other tasks to Identity Server?
I mean remembering the last session in the website server and then somehow contacting with IdSvr to retrieve perform some sort of validastion (for example token validation)

**Comment by leastprivilege** [comment]
IdSrv does the authentication - what happens afterwards in you local app is up to you.
