### ISSUE TITLE
IdentityServer in the Enterprise

### ISSUE THREAD

**Issue by mpaul31** [IdentityServer/IdentityServer3#1152]
Is anyone else trying to integrate the project where a single server handles authentication for all the internal apps and allows single sign on?

how are you handling logins? does each app contain a login screen or is the recommend approach to allow the identity server to expose?

any help would be greatly appreciated! :)

**Comment by leastprivilege** [comment]
You can do either way - but you will only see the full benefit of a central login system when you do a front-channel redirect to it.

This will give you SSO, support for external idps and centralized logic.

**Comment by veikkoeeva** [comment]
I'm curious about this too. We are examining a following setup:
``user browser/native application <-> reverse proxy (rp1) <-> www server (IIS, DMZ) <-> rp2 <-> backend API (IIS) <-> database (high-security zone)``.

As you can see, the connections from Internet to backend API would go through the first IIS on DMZ. The reverse proxy 2 takes traffic from internal systems (which are currently www portals using the backend API) that are mostly connected to AD (ADFS). We would like to run IdSrv on the same servers as the backend API (for the time being) and we were considering having an application specific login screen to the www application on the DMZ server and having the calls just pass-through to the backend IdSrv. Would this be a feasible scenario?

The idea here is that the various levels of access rights to the backend API are stored in the same database and not, say, in corporate AD. Then in addition to that, there also third party users that login mostly by username and a password from the Internet or then some applications may request a login and we'd like to handle these in some centralized way.

**Comment by leastprivilege** [comment]
Sure - it is just network infrastructure. Just more complicated.
