### ISSUE TITLE
Do I need OpenId Connect?

### ISSUE THREAD

**Issue by securityCurious** [IdentityServer/IdentityServer3#1153]
I want to implement authentication in a website and the corresponding API for an app to consume.

I was thinking of deploying a local Identity Server to handle authentication related tasks. However, I am told that the main feature of OpenId Connect is delegation, which I am not interested in. Right now I do not need to delegate any task to third parties.

I am thinking that I may not need the complexity of OpenId Connect for my needs. What do you think? Do I need a simpler solution?

**Comment by brockallen** [comment]
OIDC allows for tokens for authentication and for tokens to make API calls.

**Comment by leastprivilege** [comment]
OpenID Connect is not for delegation (that's more OAuth 2.0) - OIDC is for authentication.

**Comment by securityCurious** [comment]
Thanks to all. What do you think about Hawk?

**Comment by leastprivilege** [comment]
it's an authentication scheme. It's OK - but not comparable to OIDC.
