### ISSUE TITLE
Azure Active Directory Integration

### ISSUE THREAD

**Issue by ChristianRiedl** [IdentityServer/IdentityServer3#1154]
I am looking for a sample to integrate Azure AD authentication with IdentityServer.

Many thanks.

**Comment by leastprivilege** [comment]
You can use the OpenIdConnectMiddleware from MS to connect to AAD.

see https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host/Startup.cs#L137

For the AAD configuration part - check the MS docs (it is nothing special)

**Comment by ChristianRiedl** [comment]
Thank you, it is already working.
