### ISSUE TITLE
When using InvalidSignInRedirectUrl IdentityServer is still logging error messages

### ISSUE THREAD

**Issue by JPBridges** [IdentityServer/IdentityServer3#1155]
If we configure the InvalidSignInRedirectUrl (issue #1117) then we see the correct behavior if a user navigates to the login page via the back button or bookmark.

The issue is that this still renders out an error message to our logs.  These messages are so frequent that they account for about 95% of the total number of errors that our application logging.

Is there a compelling reason this should log errors?  Should it log a less severe message, or perhaps not at all if InvalidSignInRedirectUrl is configured?

**Comment by brockallen** [comment]
Well, those are just the error logs. We didn't design the error logs to be kept running in production. Would marking it as a warning be of help?

**Comment by JPBridges** [comment]
A warning would be better, and maybe informational would better still.
We're seeing this message under normal usage _a lot_ because it seems that end users want to book mark the sign in page - which seems like a valid thing for them to do.

We would probably want to keep at least the "error" level of logging from the IdentityServer running in production at least in the short term to medium term as it renders out some pretty useful information.

**Comment by brockallen** [comment]
Yep, ok -- I'll change the log level... I guess informational since we're seeing that this is a pretty common execution path.

**Comment by brockallen** [comment]
Ok, these logs were changed to Informational on the dev branch.

**Comment by JPBridges** [comment]
Thanks... we'll pick this up next version
