### ISSUE TITLE
Link to login page

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1156]
Hi

How can I link to the login screen without using the AuthorizeAttribute on the class/action?

**Comment by leastprivilege** [comment]
Using Challenge on the Katana AuthenticatioManager

**Comment by henninga** [comment]
I don't see anything on the AuthenticationManager that generates a link to the login page. Perhaps I asked the question wrong.

What I want to do is get a link to the login page that the user can click on. One way would be to create a LoginController class with a AuthorizeAttribute, but that seems like a clumsy way of doing it.

**Comment by brockallen** [comment]
In Katana, when you call Challenge on the AuthenticationManager that causes a redirect in the response for the current request -- check the Microsoft docs for more info.

**Comment by henninga** [comment]
Ahh, I see. So I do need a login controller after all?

**Comment by brockallen** [comment]
No -- you just need some endpoint in your app to trigger that redirect.

**Comment by henninga** [comment]
Thank you. I got it to work.
