### ISSUE TITLE
Need PCL OpenId Connect Samples, WebAuthenticationBroker sucks!

### ISSUE THREAD

**Issue by PeterBurke** [IdentityServer/IdentityServer3#1160]
Hi Dominick,
I watched your Dec 15 presentation London 2015. There was one point there where you paused and asked the audience: "this is really exciting isn't it". Nobody said a word, so "Oh Well". As far as I am concerned, yes it was really exciting, in fact it was awesome!

Previously I delivered an earlier release of the Identity Server, but have been away. Right now I am working in Xamarin Studio multi-targeting cross platform. Everything has to be in a PCL unless it is very low level.

Working through the examples I noted that only a few are mobile / pc apps. Of these two including a Windows Phone client use the Microsoft WebAuthenticationBroker. This is a non-portable library and so not much use for cross-platform. The remaining examples use the Thinktecture.IdentityModel.Client OAuth2Client Class. Actually this it is nice that it is in a shared library makes compiling it into a PCL very easy.

There are enough examples showing a few simple flows to be able to get started, but perhaps there is a long way to go to get complete.

The other thing I noticed is that this class is built on top of System.Net.Http. In the Xamarin world the Xamarine provide a platform specific replacement for the System.Net DLL and bundle all of the extensions with it. So the PCL I am working on should work.

The other issue is that I want to use ODATA via the Simple.Odata.Client package. ODATA offers an alternative way to interact with the Web Api REST Service. Data goes back and forth as Json and it uses a CRUD pattern. I have determined that both OAuth2Client and Simple.Odata.Client can share a common HttpClientHandler and Simple.Odata.Client will invoke Actions when exceptions like Token expiry occur allowing for renewal and reattempting.

Sorry, not much for you to do right now, but if I get it working I would like to help promote the Identity Server by contributing to this Open Source project.

**Comment by brockallen** [comment]
If/when you get some samples, we can link to them or your blog from our docs. Just let us know.
