### ISSUE TITLE
Getting IdSrv production ready

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1161]
Hi

I've got Idsrv 3 up and running in our test environments. Release to production is coming fast and I was wondering what steps/things are needed to getting it ready for production with regards to security.

For one is getting a signing cert, but do I need to add validation of the cert (client and/or server)?
Anything other I need to think about?

**Comment by johnkors** [comment]
Yes, you would want to validate who is sending your clients tokens. The signing cert can be self signed however.

There's also a short list here for recommended services to implement for production scenarios. 
https://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html

**Comment by henninga** [comment]
How do I validate who is sending client tokens?

**Comment by johnkors** [comment]
Two options: either by asking idsrv at the validation endpoints, or by using cryptolibs and the cert thumbprint of the signing cert (available at the discovery endpoint). 

If your clients are all .NET, the samples show how. Also the walkthrou in the docs has a section on this.

http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html
http://identityserver.github.io/Documentation/docs/endpoints/accessTokenValidation.html
http://identityserver.github.io/Documentation/docs/endpoints/identityTokenValidation.html
