### ISSUE TITLE
Use IdentityServer as OpenID Connect endpoint only

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer3#1162]
First of all, I'm new to OAuth2/OpenID Connect and SSO, so I can be missing a few points here.

We want to setup a single identity server as SSO point for multiple web applications and web api's. A user should be able to manage his own user account and connect with multiple external identity providers like Facebook, Google, etc.

The MVC ASP.NET Web Application template coming with VS2013 (using AspNet.Identity) seems to do this out-of-the box except that there is no OpenID Connect endpoint for generating identity and access tokens for other applications.

The problem with IdentityServer is that it seems very hard to use an ASP.NET Web Application as custom view service as the IViewService interface is Stream based.

Also if we use MVC WebApp for managing our user accounts, we need to register all our external identity providers twice (once for IdentityServer, once for our MVC WebApp).

Is there a way to integrate an MVC WebApp (with the default AspNet.Identity, login page with external identity providers, user management, two factor authentication, etc) with IdentityServer, so the latter is only used as OpenID Connect endpoint?

**Comment by brockallen** [comment]
We allow for partial logins to accommodate some of these scenarios -- check the user service docs. Also, we have a few OWIN extension methods to allow for your external pages to work with IdSvr for logging the user in. Finally, I just posted this snippet (https://github.com/IdentityServer/IdentityServer3/issues/1148#issuecomment-91231100) for helping your external pages co-located with IdSvr redirect for logins (without using OIDC).

**Comment by huysentruitw** [comment]
I would like to keep the MVC WebApp in a separate project, but then I will not be able to use it as a custom login page for the IdentityServer, is this correct?

**Comment by brockallen** [comment]
We don't directly support MVC for customizing your views, correct. There are several reasons for this.  Some people say that they have razor working. Check the archives in the issue tracker for more info on any of these.
