### ISSUE TITLE
Custom role provider

### ISSUE THREAD

**Issue by rajarameshvarma** [IdentityServer/IdentityServer3#1163]
How can I use Role provider with Identity Server. When I am trying to configure custom role provider, for all the methods, ex. public override string[] GetRolesForUser(string username), username is null.

I tried to set User using below code.
   UserPrincipal principal = new UserPrincipal(userName);
   principal.Identity = new GenericIdentity(userName);
   HttpContext.Current.User = principal;

Even tried to convert it to ClaimsPrincipal but still no luck. I am setting this in SecurityTokenValidated method of OpenIdConnectAuthenticationNotifications.

Please help.

**Comment by brockallen** [comment]
It sounds like you want to modify the claims of the user, correct? If you're in IdSvr then you implement the IUserService to indicate what claims you have for the user. if you want to add claims for the user in your app, then look into the notifications events on the middleware -- this allows you to modify the claims for the user. One of our MVC samples show this in the app.
