### ISSUE TITLE
Logout Of All Sites

### ISSUE THREAD

**Issue by flynninformz** [IdentityServer/IdentityServer3#1164]
There doesn't seem to be a way to trigger logging out of all the sites that were logged into using IdentityServer v3.  Is there a way to do this or is it in the works.  Bascially we have an application that allows different clients separate themselves with different sub domains, and in some cases entirely different domains.  When certain users have access to multiple clients they now have multiple cookies created for each domain/sub domain.  Is there a way with Idsrv V3 and OpenIdConnect to automatically trigger the logout across all of the domains and sub domains.

**Comment by leastprivilege** [comment]
We support the OpenID Connect session management spec (JS-based approach).
