### ISSUE TITLE
Need to set nuget dependencies

### ISSUE THREAD

**Issue by omidkrad** [IdentityServer/IdentityServer3#1165]
[IdentityServer3](https://www.nuget.org/packages/Thinktecture.IdentityServer3/) nuget package only shows **Owin** as dependency. So when installing this package on a new project it will fail to run because of all the other nuget dependencies that are listed in [packages.config](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/packages.config) but not set in the nuget package as dependecy. For example installing IdentityServer3 package should also install the following packages:

- Autofac
- Autofac.WebApi2
- System.IdentityModel.Tokens.Jwt

I thought that nuget package builder automatically looked in packages.config and included dependencies, but apparently it is not. This issue makes problem when deploying the project on a hosting service which tries to restore nugets and will not download/resolve those unlinked references.

If any of these are indirect dependencies through other packages, then they will need to be added to those packages.

**Comment by brockallen** [comment]
No -- we internalize all of our dependencies into our own assembly. Look at out build script.

**Comment by omidkrad** [comment]
Hi Brock, this problem is only for the nuget package. We can manually add the extra packages that are used by IdentityServer3 nuget, but since IdentityServer3 nuget dose not show those as dependencies and that our consumer project is not directly using those dependencies' APIs then the build tools cannot resolve them. Also if we add those manually then their version number may conflict with the version number of the ones used by IdentityServer3 nuget.

Another solution would be to include the source project of IdentityServer instead of it's nuget package but then we will lose all the benefits with nuget updates.

**Comment by brockallen** [comment]
I don't follow -- the NuGet does not have those dependencies. Open the DLL in reflector and have a look.

**Comment by omidkrad** [comment]
Yes, I'm saying maybe Nuget should have those dependencies. To see the problem I'm talking about, try copying the [AspNetIdentity_2fa](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity_2fa) to a new folder without the `packages` folder, build and run. It will restore nuget packages and compile but will fail at runtime due to references that were not downloaded. You have to manually add `autofac.dll`, `System.IdentityModel.Tokens.Jwt`, etc for it to run. It is not a big deal, but it would be nicer if restoring brought all the dependencies and the project could run out of the box. You might have some other considerations in how the dependencies are managed that I don't know.

**Comment by johnkors** [comment]
Did you try to install the idsrv nuget and experiencing issues, or just looking at the source and comparing it to the nuget at nuget.org? 

As Brock said, the idsrv dependencies have been ILMerged into one dll and internalized for the NuGet - hence you will not need to install any dependencies that idsrv has internally or need to fetch any dependencies that idsrv has internally during nuget restore. Or deal with conflicts. They are already in the dll in the NuGet, and internalized. You only need the single idsrv nuget.

If there's an issue with the 2fa sample project, i believe it's with the 2fa sample project - not the main idsrv nuget. Maybe a issue with any of the other nugets the 2FA sample is using? could not see what nuget it uses that would infer a implicit dep on autofac though.

**Comment by omidkrad** [comment]
OK, I see. I didn't initially get what you meant by 'internalized dependencies'. That's why the file size of `IdentityServer3.dll` that came with the nuget was larger than the one I build. I like that. The reason this happened to me was that I had made this change #1158 in IdSrv and overwrote `IdentityServer3.dll` Now I have to find a way to make it working while my change is not in the nuget yet.

So I'm closing this issue. Thanks.

**Comment by johnkors** [comment]
Ah, your own version. Did you build your own dll it with the build scripts (powershell) or just by visual studio / MSBuild? The ILMerging bits are in the build scripts, so try to use those when creating your own dll.

**Comment by omidkrad** [comment]
Good point. Watching the powershell build to complete was pretty enjoyable. I think this will work. Thanks again for your help and for this awesome library.
