### ISSUE TITLE
Get list of users endpoint?

### ISSUE THREAD

**Issue by mpaul31** [IdentityServer/IdentityServer3#1168]
is there an endpoint exposed from the identity server to the client application to call to get a list of all the users? I am thinking I am going to have idserv manage what applications the user has access too (AppClaim) then have each system implement what permissions (transformed to claims) each user can perform, so the client admin needs a list of users to choose from.

Thanks!

**Comment by brockallen** [comment]
No, that'd be something you'd need to implement.
