### ISSUE TITLE
Allow dynamic PublicOrigin 

### ISSUE THREAD

**Issue by ycrumeyrolle** [IdentityServer/IdentityServer3#1169]
I have to manage multiples PublicOrigins. 
For example :
https://authz.mycompany.com
https://authz.myothercompany.com
https://authz.mythirdcompany.com

On the public side, I have multiples origins, but on the internal side, I have only one instance.

In my case, based on the request context (for example the "host" http header provider by the reverse proxy), I will be able to select the correct origin. 
For example : 

```C#
public delegate string PublicOriginSelector(HttpContext context);

// To keep the same behavior as before
var legacyOptions = new IdentityServerOptions
{
    //...
    PublicOrigins = _ => "http://somehost";
};

// new behavior 
var options = new IdentityServerOptions
{
    //...
    PublicOrigins = context => 
    {
        switch(context.Request.Headers["host"])
            case "X" : return "http://somehost";
            case "Y" : return "http://someotherhost";
            default : return "http://somedefaulthost";
    }
};
```

**Comment by brockallen** [comment]
This would need to be done as a service. I'll leave it open as something to consider for 2.x.

**Comment by leastprivilege** [comment]
You can set it yourself as MW running before us in the pipeline

https://github.com/IdentityServer/IdentityServer3/blob/master/source%2FCore%2FExtensions%2FOwinEnvironmentExtensions.cs#L564
