### ISSUE TITLE
Single sign-in with different clients

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1170]
Hi

Is it possible to have single sign-in with different clients?
We have a number of sites that all participate in single sign-in, but I'd like to use different clients. Does that work and is it/is not recommended?

**Comment by loctanvo** [comment]
Yes, it's possible with several clients. That's actually the whole idea of having a centralized IdServer.

**Comment by henninga** [comment]
I tried this now, and it works (to some extent).
Logging in with app A authenticates app B as well. However, when I log out  (with PostLogoutRedirectUris in both clients) in app B, the redirect url and ClientName refers to app A. Is this deliberate or a bug?

**Comment by brockallen** [comment]
We implement the JavaScript approach to single signout -- check the OIDC specs.
