### ISSUE TITLE
Custom ClaimsPrincipal

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1173]
In one of our applications we set the Thread.CurrentPrincipal to a custom class we use which are set in a AuthorizationFilter. It would be to big of a rewrite right now, so as an intermediate solution I was think I could inherit from ClaimsPrincipal but I'm not sure where I'd set the new ClaimsPrincipal. It would probably work in the authz filter but it should probably be set deeper inside owin/katana?

**Comment by brockallen** [comment]
Is this a question or issue about IdentityServer?

**Comment by henninga** [comment]
Just a question of where I should set a custom ClaimsPrincipal in the client
