### ISSUE TITLE
Custom claims for a user's organization

### ISSUE THREAD

**Issue by kylegalbraith** [IdentityServer/IdentityServer3#1174]
This is more of a question that an issue that I would like some feedback on. The situation is that I want to log a user in via identity server with some scope "Api1", and this scope has a ScopeClaim for role so that I can check that not only this user is authorized but that they are in the correct role as well. 

However, the user could be apart of one or more "organizations". Because of this, I want to check that not only is this user authorized, has the correct role, but are they apart of the organization that they want access the resource in.

What is a suitable way of handling this? If it was 1:1 user to organization then I would think I could use the subject in order to uniquely verify in the endpoint that this subject can access this resource. However, what if the subject is in more than one organization? Do you duplicate the user in both organizations and simply have a different subject for each? In which case when a user changes organizations we would need to re-authenticate to make sure the user is the correct subject.

**Comment by brockallen** [comment]
You'd need to do authorization within your app.

**Comment by kylegalbraith** [comment]
I believe the authorization will need to happen within the app as well. But perhaps my question is more geared towards what is the best way to do that utilizing IS3.

A further refinement on my scenario is that Bob is a member of the org Foo in the roles contact and member. He is also a member of the org Bar in the roles contact, member, admin. My question is what would be the best way to check not only the organization, but Bob's role within that organization as well. Perhaps a custom authorization attribute like the ResourceAuthorization examples I have seen.

I did come up with this general idea that I think would work, but seems a little bit flawed to me.

                new InMemoryUser{
                    Subject = "FooOrgId-88421113", 
                    Username = "bob", Password = "bob", 
                    Claims = new Claim[]
                    {
                        new Claim(Constants.ClaimTypes.PreferredUserName, "bob"), 
                        new Claim(Constants.ClaimTypes.Role, "Contact"),
                        new Claim(Constants.ClaimTypes.Role, "Member") 
                    }
                }
                new InMemoryUser{
                    Subject = "BarOrgId-88421113", 
                    Username = "bob", Password = "bob", 
                    Claims = new Claim[]
                    {
                        new Claim(Constants.ClaimTypes.PreferredUserName, "bob"), 
                        new Claim(Constants.ClaimTypes.Role, "Contact"),
                        new Claim(Constants.ClaimTypes.Role, "Member"),
                        new Claim(Constants.ClaimTypes.Role, "Admin"), 
                    }
                }

Essentially, Bob has two records as a user, one with subject = FooOrgId-bobsId and another one with subject = BarOrgId-bobsId. This seems like an approach that would allow me to check Bob's claims with the organization id and bob's subject id to verify the access to the resource. But is this a suitable approach?

**Comment by brockallen** [comment]
Did you ever get this sorted out? Can we close the issue?
