### ISSUE TITLE
All of sudden code flow is failing.

### ISSUE THREAD

**Issue by pavanputhra** [IdentityServer/IdentityServer3#1175]
First part of authorization code where i get code from server I happening successfully.

Second part where I have to send code to get refresh token is failing. Funny part is 1 week before same code seemingly worked!

Following is the request sent

```
POST https://localhost:44301/identity/connect/token
Content-Type: application/x-www-form-urlencoded

client_secret=secret&client_id=5510121a27c44166129&redirect_uri=oob%3A%2F%2Flocalhost%2Fsearch&code=0a76554b77e72ecde41bb8c222ac9b18&grant_type=authorization_code
```

and response is with 400 status

```javascript
{
    "error": "invalid_request"
}
```

**Comment by brockallen** [comment]
What you posted won't help us at all understand the issue. Check the IdSvr debug logs for more info.

**Comment by pavanputhra** [comment]
Am not getting logs for error. If am not worng debug output should come in Visual Studio Output window right?

**Comment by brockallen** [comment]
Check the docs on how to configure logging in IdentityServer.

**Comment by pavanputhra** [comment]
I got following log. It says " User has been disabled: System.Security.Claims.ClaimsPrincipal". What does that mean?


```
 Start client validation
 [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 11-04-2015 14:08:21 +00:00 -- Client validation success
 {
  "ClientId": "5510121a27c44166129",
  "ClientName": "Android App",
  "ClientCredentialType": "FormPost"
}
[Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 11-04-2015 14:08:21 +00:00 -- Start token request validation
[Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 11-04-2015 14:08:21 +00:00 -- Start validation of authorization code token request
[Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 11-04-2015 14:08:21 +00:00 -- User has been disabled: System.Security.Claims.ClaimsPrincipal
 {
  "ClientId": "5510121a27c44166129",
  "ClientName": "Android App",
  "GrantType": "authorization_code",
  "AuthorizationCode": "894279a073511611b8db3b4dde3ff4cd"
}

: [Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController]: 11-04-2015 14:08:21 +00:00 -- End token request
0 : [Thinktecture.IdentityServer.Core.Results.TokenErrorResult]: 11-04-2015 14:08:22 +00:00 -- Returning error: invalid_request
```

**Comment by brockallen** [comment]
Sounds like IsActive on the user service returned false.

**Comment by pavanputhra** [comment]
I have written custome IUserServices implementation. I had break point in there and saw what's going on.

```csharp
public Task<bool> IsActiveAsync(ClaimsPrincipal subject)
        {
            ...
        }
```

It seems subject parameter passed to IsActiveAsync method has no claims populated!

**Comment by brockallen** [comment]
What version of IdSvr are you on?

**Comment by pavanputhra** [comment]
Version is 1.4.1

**Comment by brockallen** [comment]
Ok, something looks odd. @leastprivilege might have to take a look.

**Comment by pavanputhra** [comment]
Got fixed. There was error in storing of claims in MongoDB. Thank you @brockallen for pointing me in right direction to debug.
