### ISSUE TITLE
Exception thrown when setting TokenValidationParameters of OpenIdConnectAuthenticationOptions when using Microsoft.Owin.Security.OpenIdConnect as identity provider

### ISSUE THREAD

**Issue by davebown** [IdentityServer/IdentityServer3#1176]
I'm configuring the Open Id Connect identity provider with Azure AD in multi-tenant mode. But I need to disable the issuer validation as suggested by Microsoft examples and currently implemented in our solution without IdentityServer..

If I set the TokenValidationParameters property of the OpenIdConnectAuthenticationOptions the following exception is thrown System.Reflection.TargetInvocationException with an inner exception System.InvalidOperationException with the following message 'A default value for SignInAsAuthenticationType was not found in IAppBuilder Properties. This can happen if your authentication middleware are added in the wrong order, or if one is missing.'

We're configuring the identity provider as follows:

        public static void ConfigureAdditionalIdentityProviders(IAppBuilder app, string signInAsType)
        {

            var aad = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "aad",
                Caption = "Azure AD",
                SignInAsAuthenticationType = signInAsType,

                Authority = "https://login.windows.net/common",
                ClientId = "<client id here>",
                RedirectUri = "https://localhost:44303/idsrv/aadcb",
                TokenValidationParameters = new System.IdentityModel.Tokens.TokenValidationParameters
                {
                    ValidateIssuer = false
                }
            };

            app.UseOpenIdConnectAuthentication(aad);
        }

Identity server is initialise as follows currently:

            app.Map("/idsrv", idSrvApp =>
            {
                var idSvrFactory = Factory.Configure();
                idSvrFactory.ConfigureUserService();

                var options = new IdentityServerOptions
                {
                    SiteName = "myday authentication",
                    SigningCertificate = Certificate.Get(),
                    Factory = idSvrFactory,
                    CorsPolicy = CorsPolicy.AllowAll,
                    AuthenticationOptions = new Thinktecture.IdentityServer.Core.Configuration.AuthenticationOptions
                    {
                        IdentityProviders = ConfigureAdditionalIdentityProviders
                    },
                };

                idSrvApp.UseIdentityServer(options);
            });

**Comment by brockallen** [comment]
Does this work if you configure it in a stand alone client app trusting AAD?

**Comment by davebown** [comment]
Hi,

Yes it does we have it implemented in our current production application directly with AAD as per this example: 

https://github.com/AzureADSamples/WebApp-MultiTenant-OpenIdConnect-DotNet/blob/master/TodoListWebApp/App_Start/Startup.Auth.cs

We are hoping to implement IdentityServer3 initially with AAD but in future other providers also and to do our own OAuth properly with a new api we're developing.

**Comment by brockallen** [comment]
Given that it's Microsoft's library and not ours, i think you'll need you to do a little more debugging on your end (or contact Microsoft for support). If you discover that a certain configuration doesn't work so well with IdSvr, then we can help made adjustments on our end to help solve the problem. But AAD and the OIDC middleware does works with IdSvr in single-tenant mode (I'm unfamiliar with the multi-tenant mode).

**Comment by davebown** [comment]
Just did a comparison with our production code and in that we're doing app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType); which is not done in the Identity Server samples. 

As cookie authentication isn't in the solution I tried adding app.SetDefaultSignInAsAuthenticationType(OpenIdConnectAuthenticationDefaults.AuthenticationType); which removes the exception.

Would this cause a problem with identity server at all? What would the impact be?

**Comment by brockallen** [comment]
`SetDefaultSignInAsAuthenticationType` is the moral equivalent of setting a global variable with the name of the cookie middleware to use for all other authentication middleware (and it a crappy approach IMO). If you don't set it, then you must set the `SignInAsAuthenticationType` instead. 

With IdSvr, we are configuring the cookie middleware you need to use, and that's why we pass the name of it for you to use. If something on the OIDC middleware prevents you from setting it explicitly (and requires you to use the global/implicit `SetDefaultSignInAsAuthenticationType`) then we're going to have problems. That's why I asked you to debug into it some more to really understand why Microsoft's code is failing to honor the `SignInAsAuthenticationType` property.

**Comment by davebown** [comment]
Ok I understand that a little bit more now. Thanks for the info, do you think it's worth me logging an issue over on code plex on the Katana project about this behaviour?

One last question as a work around (hopefully a temporary one) can I just set app.SetDefaultSignInAsAuthenticationType(signInAsType) in the ConfigureAdditionalIdentityProviders delegate function? It appears to work and I'm now able to login to the permissions application using AAD provider but I wonder if this will break anything else, are their circumstances that other cookie middleware can be used?

Sorry if I appear naive, I'm a little new to this area and Katana in general.

**Comment by leastprivilege** [comment]
app.SetDefaultSignInAsAuthenticationType is like a global variable - and may have side effects.

I would recommend opening an issue on codeplex. Setting the SignInAsAuthenticationType should be sufficient. Anything else would be a bug.

**Comment by brockallen** [comment]
Any update?

**Comment by davebown** [comment]
Yes the solution after some experimentation was to move the position of the SignInAsAuthenticationType parameter in the options to the end. It seems the way the library works makes the order in which you declare the parameters important.

 var aad = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "aad",
                Caption = "Azure AD",

                Authority = "https://login.windows.net/common",
                ClientId = "<Azure AD Client Id here>",
                TokenValidationParameters = new System.IdentityModel.Tokens.TokenValidationParameters
                {
                    ValidateIssuer = false
                },
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    RedirectToIdentityProvider = (context) =>
                    {
                        // This ensures that the address used for sign in and sign out is picked up dynamically from the request
                        // this allows you to deploy your app (to Azure Web Sites, for example)without having to change settings
                        // Remember that the base URL of the address used here must be provisioned in Azure AD beforehand.
                        string appBaseUrl = context.Request.Scheme + "://" + context.Request.Host + context.Request.PathBase;
                        context.ProtocolMessage.RedirectUri = appBaseUrl + "/";
                        context.ProtocolMessage.PostLogoutRedirectUri = appBaseUrl;
                        return Task.FromResult(0);
                    }
                },
                SignInAsAuthenticationType = signInAsType
            };

            app.UseOpenIdConnectAuthentication(aad);

**Comment by brockallen** [comment]
Woah, really? That sounds either wrong or horribly broken.

**Comment by brockallen** [comment]
This sucks. I'm going to close this now and have a stiff drink.

**Comment by jageall** [comment]
oh yeah, this is totally rubbish, we came across this a while ago but i totally forgot about the horror until i read this.

**Comment by brentschmaltz** [comment]
It is a bit messy, and related to the runtime requiring the ClaimsIdentity.AuthenticationType to be coordinated with the middleware for sign-in / out.  

app.SetDefaultSignInAsAuthenticationType was used as the default if nothing else is set. I am thinking it would be a good idea remove the coupling and instead have the runtime use AuthenticationTicket.AuthenticationType which is under the control of the runtime not the layer below.

@davebown I am confused by the ordering requirement.

**Comment by brockallen** [comment]
The ordering issue is because `SignInAsAuthenticationType` property sets a property on the `TokenValidationParameters`. If he puts `TokenValidationParameters` assignment last, then the prior assignment to `SignInAsAuthenticationType` is indirectly overwritten.

**Comment by brentschmaltz** [comment]
@davebown @brockallen thanks that gives me what I need.
