### ISSUE TITLE
Multistep login flow

### ISSUE THREAD

**Issue by refref** [IdentityServer/IdentityServer3#1177]
I need following login flow:
After user logs in with username and password, 2 factor authentication verification page if 2fa acr value is present, and password change page if password is older than 90 days.

Login flow with 2fa and outdated password is:
1. Login page (username password)
2. 2fa verification code.
3. Change password.

What is the right place to check, if the password should changed, after 2fa verification is completed.

**Comment by leastprivilege** [comment]
check the 2FA sample.

**Comment by refref** [comment]
Thank you for quick answer, i have allready checked the sample, and implemented 2fa according to sample. 

In 2FA example after 2fa code verified, request is redirected to partial login return url. 
`var resumeUrl = authentication.Identity.Claims.Single(x => x.Type == Constants.ClaimTypes.PartialLoginReturnUrl).Value;`
`return Redirect(resumeUrl);`

Do i need to redirect change password url for second step?

**Comment by leastprivilege** [comment]
You can inject whatever custom workflow before returning the the resumeUrl. When you are done you hand control back over to us.

**Comment by refref** [comment]
I injected OwinEnvironmentService in my custom userservice, there i put an evironment variable, if password has been expired for user:
`_owinEnvironmentService.Environment.Add("PasswordExpired",true);`

Now i want to acces this value in my TwoFactorAuthentication Controller (MVC controller), but value is null:
`var ctx = Request.GetOwinContext();`
`var passwordExpired = ctx.Get<Boolean>("PasswordExpired");`
`	        if (passwordExpired)
	        {
		        ...`
`				return Redirect("changepwd");
		}
`


How can i pass parameters to my login workflow controllers.

**Comment by leastprivilege** [comment]
The environment is per request - and since you are doing a redirect, this will not work.

But you can add the expired information as a claim into the partial identity (the claims you put into AuthenticateResult in your user service).

**Comment by refref** [comment]
Yes, i saw this also. But question is: Will be these claims present in identity and access tokens. If yes how can i remove them in my controllers?

**Comment by leastprivilege** [comment]
by setting a new identity in your controller. Check the 2FA sample on the dev branch.

**Comment by rdzidziguri** [comment]
I could not find 2fs simple could you please post a link for it. I have similar problem we must use IdentityServer 3 and ASP.NET identity to register and handle 2FA for users. so please post a link for simple with 2FA. We also would like to force client to change their password if first time they authenticate and enable or disable OTP.

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity_2fa
