### ISSUE TITLE
Rename "assets" folder to "templates" or "views"

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#1178]

**Comment by brockallen** [comment]
chose "views". done on dev

**Comment by brockallen** [comment]
I want to change this back, since "Views" conflicts with MVC's views folder.

**Comment by brockallen** [comment]
Changed to "templates"

**Comment by diegobfernandez** [comment]
Was quite hard to figure it out. Spent some time searching the issues since I couldn't find anything that worked on docs or samples!
