### ISSUE TITLE
Allow substitution CSS per client 

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#1179]

**Comment by rdzidziguri** [comment]
Do you really think you should spend your time on this? this is such an easy to implement functionality with IdSRV3 extension points that my developers managed to make authentication screen as much client oriented as they needed (loading custom CSS, rendering custom HTML). I think there might be other good staff you could work on with Identity Server and left this for developers to customize on their own. After all you are doing a great job by providing such a enterprise level authentication server for free.

**Comment by leastprivilege** [comment]
this can be easily done in a custom (default) view service.
