### ISSUE TITLE
Resource Owner Flow vs OIDC for SPA 

### ISSUE THREAD

**Issue by rajajhansi** [IdentityServer/IdentityServer3#1183]
@brockallen, I downloaded the slides and sample code from your Boston Code Camp 23 and was trying to run the samples. Is the sample an update version of OAuthJS under IdentityServer3.Samples project? The sample shows the implicit flow but assumes that the IdentityServer3 is running (either IIS express or self host). So, I ran the Selfhost and then ran the 3_token_manager project but when I try to "Get Token", I get "No 'Access-Control-Allow-Origin' header is present on the requested resource" because the client and the server are running on different ports. I ended up adding Cors headers into config.headers property, which is used by XHR before the getJson() call but it doesn't seem to work. 

Many blog posts and even online courses are simply demonstrating using the Resource Owner Flow from SPA apps with the grant_type=password, storing the token in localstorage instead of using cookies. Your presentations clearly mention that it is really not a good use of OAuth2 and you recommend using OIDC for authentication. If everything is done on server side using ASP.NET MVC and the embedded resources that includes the razor pages for the login UI, it is straightforward and easy. Whereas in SPA (especially using AngularJs), would it be fine to provide a client url route that will launch a login dialog? Do we really need complicated flows like Hybrid Flow for the sake of supporting OIDC??

**Comment by brockallen** [comment]
Yes, the new repos are here:

https://github.com/IdentityModel/oidc-client
https://github.com/IdentityModel/oidc-token-manager

and are more formal versions of the previous OAuthS sample. Each one contains a samples folder and yes they do assume you have IdentityServer running (otherwise how would you login?).

These samples are using the implicit flow, not the resource owner password flow..

**Comment by rajajhansi** [comment]
Thank you for the links to new repos. 
Of course, I understand that the IdentityServer needs to run for the clients to talk to and the sample uses implicit flow. I ran the IdentityServer using OWIN self-host that runs on https://localhost:44433/core and updated the Authority in Startup.cs, index.html, modal.html and frame.html in oidc-token-manager project to point to https://localhost:44433/core. I'm not using localhost:44333 instead using port 44433 and have a devRoot and other required SSL certificates installed and netsh command to make sure it is accessible via HTTPS. The oidc-token-manager itself is running on http://localhost:23453/ but it tries to talk to https://localhost:44433/core and hence get that "No 'Access-Control-Allow-Origin' header is present on the requested resource" error.

**Comment by rajajhansi** [comment]
@brockallen, adding
factory.CorsPolicyService = new Registration<ICorsPolicyService>(new InMemoryCorsPolicyService(Clients.Get()));

and setting AllowedCorsOrigins property to my SPA's url did the trick :) The redirection to the login screen (which is inside embedded resources of IdentityServer), getting consent after successful authentication and then redirecting it back to my SPA's home page are working fine now. I liked displaying that login screen withing the modal dialog and also looked at the customization of the embedded resource sample. 

I'll try to leverage the modal source code to show both the login screen. Is there a way to not ask the consent since my SPA application is the only client of the backend Web API?

**Comment by johnkors** [comment]
Yep, you may disable it pr client.

http://identityserver.github.io/Documentation/docs/configuration/clients.html

**Comment by rajajhansi** [comment]
@johnkors, perfect timing. Thank you for the link. I was just setting the RequireConsent = false in the implicit client flow.
