### ISSUE TITLE
Login ReturnUrl missing path from PublicOrigin

### ISSUE THREAD

**Issue by mbubnich** [IdentityServer/IdentityServer3#1184]
When using a reverse proxy with a domain and a path as the PublicOrigin e.g. "https://proxy/auth" when authorizing a user who is not logged in (Flow.AuthorizationCode) the user is redirected to the login page and encoding the return url for the authorize endpoint into a cookie this return url when built is missing the path of the PublicOrigin. 

Once reaching the login request I authenticate the user in the PreAuthenticateAsync method and return. at this point it all breaks as the ReturnUrl is not valid. At the moment as a workaround in the PreAuthenticateAsync method I am pulling the ReturnUrl out of the SingInMessage and restore the path of the public origin.

            //fix for return uri not having the correct public origin uri embeded.
            if (!message.ReturnUrl.Contains(_environment.Environment.GetIdentityServerBaseUrl()))
            {
                var returnUri = new Uri(message.ReturnUrl);
                var hostUri = new Uri(_environment.Environment.GetIdentityServerHost());
                var finalUri = new Uri(hostUri,hostUri.PathAndQuery.TrimEnd('/') + '/' + returnUri.PathAndQuery.TrimStart('/'));
                message.ReturnUrl = finalUri.AbsoluteUri;
            }

I think the issue is a result of AuthorizeEndpointController.RedirectToLogin the combination of an existing Uri and a string in a new Uri appears to be ignoring the path in the existing Uri.

            var path = Url.Route(Constants.RouteNames.Oidc.Authorize, null).AddQueryString(parameters.ToQueryString());
            var host = new Uri(Request.GetOwinEnvironment().GetIdentityServerHost());
            var url = new Uri(host, path);

Is this a bug or am I configuring something incorrectly?

**Comment by brockallen** [comment]
I just tried to reproduce and I don't see what you describe. In the authorize controller, the redirect URL honors the configured PublicOrigin.

**Comment by mbubnich** [comment]
bellow is an example showing the issue.
with PublicOrigin 'A' i.e. no change to the origin
with PublicOrigin 'C' i.e. no path on the origin
it works correctly
however if 'B' is used the redirect URL after logging in back to the authorize endpoint is missing the path of the PublicOrigin unless the hack is enabled

ServerCode:

    using System;
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Security.Cryptography.X509Certificates;
    using System.Threading.Tasks;
    using Microsoft.Owin.Hosting;
    using Owin;
    using Thinktecture.IdentityServer.Core.Configuration;
    using Thinktecture.IdentityServer.Core.Extensions;
    using Thinktecture.IdentityServer.Core.Logging;
    using Thinktecture.IdentityServer.Core.Logging.LogProviders;
    using Thinktecture.IdentityServer.Core.Models;
    using Thinktecture.IdentityServer.Core.Services;

    namespace Server
    {
        class Program
        {
            static void Main(string[] args)
            {
                LogProvider.SetCurrentLogProvider(new ColouredConsoleLogProvider());

                using (WebApp.Start<Startup>("http://localhost:8080"))
                {
                    Console.WriteLine("press any key to exit");
                    Console.ReadKey(true);
                }
            }
        }

        internal class Startup
        {
            public void Configuration(IAppBuilder app)
            {
                var factory = InMemoryFactory.Create(
                    clients: IdsConfiguration.Clients(),
                    scopes: IdsConfiguration.Scopes()
                    );

                factory.UserService = new Registration<IUserService, UserService>();

                var options = new IdentityServerOptions
                {
                    Factory = factory,
                    SiteName = "Test Identity Server",
                    SigningCertificate = LoadCertificate(),
                    RequireSsl = false,
    #region ChangePublicOrigin
                    PublicOrigin = null                                 //A: Default (works)
                    //PublicOrigin = "http://localhost:1234/auth"       //B: New Host and path (requires hack bellow)
                    //PublicOrigin = "http://localhost:9875"            //C: New Host (works)
    #endregion
                };

                app.UseIdentityServer(options);

            }

            private X509Certificate2 LoadCertificate()
            {
                return new X509Certificate2("idsrv3test.pfx", "idsrv3test");
            }
        }

        internal static class IdsConfiguration
        {
            public static IEnumerable<Client> Clients()
            {
                return new[]
                {
                    new Client
                    {
                        ClientId = "client",
                        ClientName = "Test Client",
                        Enabled = true,
                        AccessTokenType = AccessTokenType.Jwt,
                        AccessTokenLifetime = 3600, //1 hour

                        Flow = Flows.AuthorizationCode,

                        RedirectUris = new List<string>
                        {
                            "oob://authenticated"
                        },

                        RefreshTokenUsage = TokenUsage.OneTimeOnly,
                        AbsoluteRefreshTokenLifetime = int.MaxValue,
                        SlidingRefreshTokenLifetime = 7776000, //90 days
                        RefreshTokenExpiration = TokenExpiration.Sliding,

                        ClientSecrets = new List<ClientSecret>
                        {
                            new ClientSecret("E988B0C4-80D1-4B61-A8F6-5ADC4387696C".Sha256())
                        },

                        EnableLocalLogin = false,
                        RequireConsent = false,
                    }
                };
            }

            public static IEnumerable<Scope> Scopes()
            {
                return new[]
                {
                    StandardScopes.OpenId,
                    StandardScopes.Profile,
                    StandardScopes.OfflineAccess,
                    new Scope
                    {
                        Name = "custom",
                        IncludeAllClaimsForUser = true,
                    }
                };
            }
        }

        public class UserService : IUserService
        {
            private readonly OwinEnvironmentService _environment;

            public UserService(OwinEnvironmentService environment)
            {
                _environment = environment;
            }


            public Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message)
            {
    #region Hack 
                if (false) //enable hack to get public origin with host and path changed to work.
                {
                    //fix for return uri not having the correct public origin uri embeded.
                    if (!message.ReturnUrl.Contains(_environment.Environment.GetIdentityServerBaseUrl()))
                    {
                        var returnUri = new Uri(message.ReturnUrl);
                        var hostUri = new Uri(_environment.Environment.GetIdentityServerHost());
                        var finalUri = new Uri(hostUri,
                            hostUri.PathAndQuery.TrimEnd('/') + '/' + returnUri.PathAndQuery.TrimStart('/'));
                        message.ReturnUrl = finalUri.AbsoluteUri;
                    }
                }
    #endregion

                return Task.FromResult(new AuthenticateResult("123", "testUser", identityProvider: "testProvider"));
            }

            public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
            {
                return Task.FromResult<AuthenticateResult>(null);
            }

            public Task<AuthenticateResult> AuthenticateExternalAsync(ExternalIdentity externalUser, SignInMessage message)
            {
                return Task.FromResult<AuthenticateResult>(null);
            }

            public Task SignOutAsync(ClaimsPrincipal subject)
            {
                return Task.FromResult(0);
            }

            public Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
            {
                return Task.FromResult(subject.Claims);
            }

            public Task<bool> IsActiveAsync(ClaimsPrincipal subject)
            {
                return Task.FromResult(true);
            }
        }
    }



Client Code:

    using System;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    using Thinktecture.IdentityModel.Client;

    namespace Client
    {
        // ReSharper disable once ClassNeverInstantiated.Global
        class Program
        {
            private const string RedirectUri = "oob://authenticated";

    #region ChangePublicOrigin
            private const string PublicOrigin = "http://localhost:8080";            //A
            //private const string PublicOrigin = "http://localhost:1234/auth";     //B
            //private const string PublicOrigin = "http://localhost:9875";          //C
    #endregion

            private const string InternalOrigin = "http://localhost:8080";
        

            private static Uri AuthorizeEndpointUri
            {
                get
                {
                    return new Uri(string.Format("{0}/connect/authorize",PublicOrigin));
                }
            }

            private static Uri TokenEndpointUri
            {
                get
                {
                    return new Uri(string.Format("{0}/connect/token",PublicOrigin));
                }
            }

            static void Main()
            {
                bool running;

                Console.WriteLine("press any key to get a token or 'e' to exit");

                do
                {
                    running = Console.ReadKey(true).KeyChar != 'e';

                    GetToken();

                } while (running);

            }

            private static void GetToken()
            {
                var authorizeClient = new OAuth2Client(AuthorizeEndpointUri, "client", "E988B0C4-80D1-4B61-A8F6-5ADC4387696C",OAuth2Client.ClientAuthenticationStyle.None);

                var rpUrl = authorizeClient.CreateCodeFlowUrl("client", "openid profile offline_access custom",RedirectUri);

                var accessCodeHttpResponce = RelayParty(rpUrl);

                if (accessCodeHttpResponce.StatusCode == HttpStatusCode.Found &&
                    accessCodeHttpResponce.Headers.Location != null &&
                    accessCodeHttpResponce.Headers.Location.OriginalString.StartsWith(RedirectUri))
                {
                    var accessCodeResponce = new AuthorizeResponse(accessCodeHttpResponce.Headers.Location.AbsoluteUri);

                    if (string.IsNullOrWhiteSpace(accessCodeResponce.Error))
                    {
                        var tokenClient = new OAuth2Client(new Uri(ConvertPublicUrlToInternal(TokenEndpointUri.OriginalString)), "client", "E988B0C4-80D1-4B61-A8F6-5ADC4387696C");

                        var tokenResponce = tokenClient.RequestAuthorizationCodeAsync(accessCodeResponce.Code, RedirectUri).Result;

                        Console.WriteLine(tokenResponce.AccessToken);
                    }
                    else
                    {
                        WriteError("Error Responce [{0}]", accessCodeResponce.Error);
                    }
                }
                else
                {
                    WriteError("Error Responce Code [{0}]", accessCodeHttpResponce.StatusCode);
                }
            
            }

            private static HttpResponseMessage RelayParty(string uri)
            {
                var clientHandler = new HttpClientHandler
                {
                    AllowAutoRedirect = false
                };

                var relayParty = new HttpClient(clientHandler);

                HttpResponseMessage response;
                var url = uri;

                WriteUri(url);

                do
                {
                    response = relayParty.GetAsync(ConvertPublicUrlToInternal(url)).Result;

                    if (response.StatusCode == HttpStatusCode.Found && response.Headers.Location != null)
                        url = response.Headers.Location.OriginalString;

                } while (FollowRedirect(response));

                return response;
            }

            private static string ConvertPublicUrlToInternal(string url)
            {
                var internalUrl = url.Replace(PublicOrigin, InternalOrigin);
                return internalUrl;
            }

            private static bool FollowRedirect(HttpResponseMessage response)
            {
                //not a redirect so continue
                if(response.StatusCode != HttpStatusCode.Found || response.Headers.Location == null)
                    return false;

                try
                {
                    //final redirect to thick client so do not follow.
                    if (IsDestination(response.Headers.Location.OriginalString))
                        return false;

                    //starts with public origin so follow
                    if (IsPublicOrigin(response.Headers.Location.OriginalString))
                        return true;

                    WriteError("Invalid Url, PublicOrigin not found");
                    return false;
                }
                finally
                {
                    WriteUri(response.Headers.Location.OriginalString);
                }
            }

            private static void WriteUri(string url)
            {
                if (IsDestination(url))
                {
                    Console.ForegroundColor = ConsoleColor.Yellow;
                    Console.Write(RedirectUri);
                    Console.ForegroundColor = ConsoleColor.DarkYellow;
                    Console.Write(url.Replace(RedirectUri, string.Empty));
                }
                else if (IsPublicOrigin(url))
                {
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.Write(PublicOrigin);
                    Console.ForegroundColor = ConsoleColor.DarkGreen;
                    Console.Write(url.Replace(PublicOrigin, string.Empty));
                }
                else
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    var i = 0;
                    var commonUrl = new StringBuilder();
                    while (PublicOrigin[i] == url[i])
                    {
                        commonUrl.Append(PublicOrigin[i]);
                        i++;
                    }
                    Console.Write(commonUrl.ToString());
                    Console.ForegroundColor = ConsoleColor.DarkRed;
                    Console.Write(url.Replace(commonUrl.ToString(), string.Empty));
                }
            
                Console.ResetColor();
                Console.WriteLine();
            }

            private static bool IsDestination(string url)
            {
                return url.StartsWith(RedirectUri);
            }

            private static bool IsPublicOrigin(string url)
            {
                return url.StartsWith(PublicOrigin);
            }

            private static void WriteError(string formatString, params object[] paramaters)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.Error.WriteLine(formatString,paramaters);
                Console.ResetColor();
            }

        }
    }

**Comment by brockallen** [comment]
An origin is not a URL.

**Comment by mbubnich** [comment]
so the path in the start-up class on the web server that is hosting the identity server must be the same as the path used in the reverse proxy on the PublicOrigin.

So:

    using (WebApp.Start<Startup>("http://localhost:8080"))

Becomes:

    using (WebApp.Start<Startup>("http://localhost:8080/auth"))

and

    PublicOrigin = "http://localhost:1234/auth"

Becomes:

    PublicOrigin = "http://localhost:1234"

**Comment by brockallen** [comment]
All I'm saying is that you can't use a URL for PublicOrigin. And so if you're using a proxy then the path into the proxy has to match the path that is being served up from your actual host.

**Comment by INSQL** [comment]
I'm using Thinktectures Relayserver as a Reverse Proxy in combination with Identityserver3 and encounter the same problem. In Relayserver the path to the api depends on links and keys that are customer/client specific. Do I have to match the ReturnUrl on the original system to match the Relayserver Url construct?
