### ISSUE TITLE
Strange: Accesstoken contains role claim, webapi client has it too, but in webapp role is not there?!?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1185]
I have an identityserver setup to use an other Wsfederation Identityserver for Login. The user logs in via [Authorize] on an MVC Controller. then the accesstoken is being added to the HttpRequest header to an Rest WebApi. In the RestWebapi controller one can see that the User’s role is in the claims, as intented. If I check the Principal on MVC Webapp side the user’s role is not in the claims.

 Why is that?

Here are the details:
The identityserver get configured to use another identityserver for Login. Before it generates its own token it adds role claim and name claim to the received token via SecurityTokenValidated callback as following:
```
var adfs = new WsFederationAuthenticationOptions
			{
				AuthenticationType = "Nevis",
				Caption = "Nevis",
				SignInAsAuthenticationType = p_SignInAsType,
                MetadataAddress = Configs.NevisSurrogateURI + "/wsfed/metadata",
				Wtrealm = "urn:testrp",
				Notifications = new WsFederationAuthenticationNotifications
				{
					// TODO extract this as proposed in http://identityserver.github.io/Documentation/docs/advanced/userService.html
					SecurityTokenValidated = n =>
					{
                        // later transform(enrich) the claims from Nevis with our company Service roles
						var incomingClaimsFromAdfs = n.AuthenticationTicket.Identity.Claims.ToList();
						var theExtUser = incomingClaimsFromAdfs.First(c => c.Type == Constants.ClaimTypes.Subject).Value;
                        // add this claim since NEVIS external identification results in "sub" with GUIDs
                        incomingClaimsFromAdfs.Add(new Claim(Constants.ClaimTypes.Name, theExtUser));

					    var theIdentityServerUser = Users.Get().First(u => u.Subject == theExtUser);
						var theNewUserClaims = theIdentityServerUser.Claims.Union(incomingClaimsFromAdfs).Distinct(new ClaimComparer());
                        
						var claimsIdentity = new ClaimsIdentity(theNewUserClaims, n.AuthenticationTicket.Identity.AuthenticationType);
						n.AuthenticationTicket = new AuthenticationTicket(claimsIdentity, n.AuthenticationTicket.Properties);
						return Task.FromResult(0);
					}
				}
			};
			p_App.UseWsFederationAuthentication(adfs);
```
the Tokens are here at the end of the method above:

![image](https://cloud.githubusercontent.com/assets/9887781/7115355/3ef49bee-e1e8-11e4-9e9f-ecf5cf4b66fb.png)

One can see that the role is there.

Then at the WebAppclient(Hybridflow) 
```
JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
            AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub"; //Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Subject;
            

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "CodeClient",
                Authority = Configs.IdentityAccessServiceURI,
                RedirectUri = Configs.WebAppRedirectURI,
                PostLogoutRedirectUri = Configs.WebAppPostLogoutRedirectURI,
                ResponseType = "code id_token token",
                Scope = "openid email profile offline_access WebApp",

                SignInAsAuthenticationType = "Cookies",
                
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = async n =>
                    {
                        //Access Token is automatically validated by identityserver
                        var token = n.ProtocolMessage.AccessToken;
                        n.Response.Cookies.Append("AccessToken", token, new CookieOptions(){Secure = true, HttpOnly = false});
                        n.Response.Cookies.Append("RestApiURI", Configs.RestApiURI, new CookieOptions() { Secure = true, HttpOnly = false });
                    },
In the SecurityTokenValidated callback the role is not available.
![image](https://cloud.githubusercontent.com/assets/9887781/7115366/5a9381ee-e1e8-11e4-8c66-0610c2ec8832.png)

The WebApp sends the request to the webapi like:
communicationModule.config(['$httpProvider', function ($httpProvider) {
    $httpProvider.interceptors.push(function ($q, $cookies) {
        return {
            'request': function (config) {
                config.headers['Authorization'] = 'Bearer ' + $cookies.AccessToken;
                return config;
            }
        };
    });
}]);
```

Then at the rest API:
```
public void Configuration(IAppBuilder app)
		{
			JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

			app.UseIdentityServerBearerTokenAuthentication(
				new IdentityServerBearerTokenAuthenticationOptions { Authority = Configs.IdentityAccessServiceURI, RequiredScopes = new[] { "WebApp" } });            
			app.UseResourceAuthorization(new AuthorizationManager());
		}
And in the Controller’s action:
public JToken Get()
		{
			var principal = this.Request.GetRequestContext().Principal as ClaimsPrincipal;
![image](https://cloud.githubusercontent.com/assets/9887781/7115373/6b07a1f4-e1e8-11e4-873e-4b0c2a1cf8e7.png)
```
And voila there is the role!!!
There does the role come from?!???

**Comment by brockallen** [comment]
Change the Roles scope in your IdSvr config to be RolesAlwaysInclude. That way the role is always in the id_token, as opposed to needing to make the request to the user profile endpoint.

**Comment by davidmrichter** [comment]
But it should have been working before:
I have defined a scope which I use at Webapp client side
new Scope                           {
                                  Name = "WebApp",
                                  DisplayName = "to act as Browser Application on your behalf",
                                  Type = ScopeType.Resource,
                                  Claims =
                                        new List<ScopeClaim>
                                        {
                                               new ScopeClaim(Constants.ClaimTypes.Scope, true),
                            new ScopeClaim(Constants.ClaimTypes.Name, true),
                                               new ScopeClaim(Constants.ClaimTypes.Role, true)
                                        },

Why was that not enough to get the role at webapp clientside? and why could the rest api extract the role from the very same accesstoken?

I included RolesAlwaysInclude and it works, but I do not understand why the extra Scope (including the roleclaims) set up did not suffice?

Could you give me an hint?

**Comment by brockallen** [comment]
But that's the scope for the API, not the MVC app right? You need to configure the scopes for the MVC app to also include the claims in the token (id_token in this case).

**Comment by davidmrichter** [comment]
I used the same Scope for the Webapp (the one above) and the webapi rest.
is that wrong?

**Comment by davidmrichter** [comment]
and id_token is defined as you can see in the snippets above

**Comment by brockallen** [comment]
I'm unsure where this issue is -- are you all set now?
