### ISSUE TITLE
Claim for Client app as well as backend API

### ISSUE THREAD

**Issue by sandeepgaikwad** [IdentityServer/IdentityServer3#1186]
In my setup I have a MVC app and a backend Web API.
I get all claims at login and also get access_token to be used in webapi.
I have a claim which is configured as follows:
Scope:
Scope name: ClaimforAPI
Type: 1 (resource)

ScopeClaims
Name: myclaim
AlwaysIncludeInToken:0
ScopeId: {Id of ClaimforAPI}

With this setup, when I call my webapi (with HttpClient.SetBearer), I can read the claim value, but this claim is not available in my mvc app (because its type is 1)
What I want is that this claim should be available at both, i.e. MVC app and backend web api

I tried with changing the value of AlwaysIncludeInToken to 1, but no difference.
If I set the scope type to 0 (identity), then the claim value isn't available at web api.

I believe this is possible, am I missing something obvious?

**Comment by leastprivilege** [comment]
you need an identity scope if the claim should be in the identity token.

**Comment by sandeepgaikwad** [comment]
Thanks, so if we talk about the database setup
So, does that mean there will be two scope records, and two scopeclaim records pointing to one UserClaim record?

**Comment by sandeepgaikwad** [comment]
okay, I have got this working.
Configured same scopeClaim twice, first with scopeid for Identity token claim and second with scopeid for Access token

Thanks
