### ISSUE TITLE
What is the best approach to deal with Pfx file

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1187]
Finally we are able to generate pfx file programmatically,  Our AuthSvr goes as an embedded webserver to multiple sites and we will need to generate different pfx file for different sites.  

Since IdentityServer needs Pfx File to work, we need to come up with some strategy for storing 
this Pfx file. We cannot include Pfx as a Resource into DLL for our AuthSvr. 

What is your suggestion for this situation.  I can think of following situations. 
1) Store to Cert Store ?.  We are able to pfx file using a password, but import did not need any password. 

2) Installation will Generate a Resource DLL to include this(Pfx file with password) as resource and the AuthSvr will load it from DLL. 

3) Installation will generate a pfx file with password! and the auth server will load it from the file. **** This approach is least preferred *************

**Comment by brockallen** [comment]
Do #1 -- that was the OS is managing it and can be DACL'd to a windows account running your web server.

**Comment by loctanvo** [comment]
>Our AuthSvr goes as an embedded webserver to multiple sites and we will need to generate different pfx file for different sites.

Just out of curiosity, why do you need different pfx for different sites? Are you running multiple id server installations?

**Comment by skatukojwala** [comment]
yes.every site will have its own identity server.

**Comment by skatukojwala** [comment]
Allan 

Am I creating a login to be used with deployment,install the certificate for the user and run IIS session with those credentials. Are any scripts to automate this process?. Any pointers would be great.

**Comment by brockallen** [comment]
No, I don't have anything.

**Comment by skatukojwala** [comment]
We choose to store certificate in cert store and give rights to App Pool user to Access the private key.  This is working for us.
