### ISSUE TITLE
Custom Login Authentication

### ISSUE THREAD

**Issue by moiseyo** [IdentityServer/IdentityServer3#1189]
Hello    Everyone.
I'd like to use IdentityServer3  openid  data flow and I need  to male may one Authentication screen with more than 2   fields with different that     user id /password   fields.

How I can change  login screen, model, and validation  to make then  as Middle ware or any aother ways?

Thank you

**Comment by moiseyo** [comment]
I'd like to explain I need to make customize or replace  DefaultViewService 
Thank you

**Comment by brockallen** [comment]
Yes, you would have to customize the views. This can be done either as a custom view service, or you can replace the default view service's templates. Check the docs.

**Comment by moiseyo** [comment]
I looked in Doc and did not find clear place , 
I'd appropriate if you point me to a topic or  link

**Comment by moiseyo** [comment]
Thank you
I looked in Doc and did not find clear place ,
I'd appropriate if you point me to a topic or  link


Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by johnkors** [comment]
http://identityserver.github.io/Documentation/docs/advanced/customizingViews.html
