### ISSUE TITLE
Running in `ApplicationPoolIdentity` cannot use an SSL Cert

### ISSUE THREAD

**Issue by dealproc** [IdentityServer/IdentityServer3#1190]
I'm loading an ssl cert from a base64 string with password from the app.config file:

```C#
public static X509Certificate2 Get() {
    var certificate = ConfigurationManager.AppSettings.Get("SSLCert:Certificate");
    var certificatePass = ConfigurationManager.AppSettings.Get("SSLCert:Password");

    //willBeUseForSigning
    if (string.IsNullOrWhiteSpace(certificate)) {
        throw new ConfigurationErrorsException("Certificate is missing from Application Settings");
    }
    if (string.IsNullOrWhiteSpace(certificatePass)) {
        throw new ConfigurationErrorsException("Certificate Password is missing from Application Settings");
    }
    var cert = Convert.FromBase64String(certificate);
    var certObj = new X509Certificate2(cert, certificatePass);
    return certObj;
}
```

When running on IIS with the Application Pool Identity set to `ApplicationPoolIdentity`, the app is failing with a `Keyset does not exist` error.  When I switch the application pool to be a dedicated user, such as my login into my development box, all is Ok and I'm able to decode the certificate as you would expect.  The base64 encoded certificate is a *.pfx file that has the public and private keys exported.

**Comment by dealproc** [comment]
I should add to this that I'm using the v1.3.0 packages from nuget at this point.

**Comment by leastprivilege** [comment]
a) don't you have to provide a password?
b) there are more parameters on the x509 cert ctor - something about how the priv key is extracted. I remember that in Azure Web Sites the default value did not work either (similar sandboxing account I assume)
c) use the cert store!

**Comment by loctanvo** [comment]
@dealproc Try to add `X509KeyStorageFlags.PersistKeySet` when creating the certificate to see whether that helps:

`var certObj = new X509Certificate2(cert, certificatePass, X509KeyStorageFlags.PersistKeySet);`

Generally, I agree with @leastprivilege . However, we are also using an embedded .pfx in our dev env, just so the minimize the setup required for the team members. In all other envs, we're loading from the cert store.

**Comment by jonbarthol** [comment]
@dealproc did you ever resolve this issue? I'm having a similar problem. We're hosting a site on Azure. Whenever I restart the app, I get the "Keyset does not exist" error.
