### ISSUE TITLE
How to add claims after user login in - before accesstoken gets created

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1191]
Hello,

on my identityserver instance I want to add additional Claims after the user logged in and before the accesstoken gets created.

Which callback could I use?

Thanks

**Comment by totpero** [comment]
You can extend User service, here is sample:
```C#
public class UserService : AspNetIdentityUserService<User, string>
    {
        public UserService(UserManager userMgr)
            : base(userMgr)
        {
        }

        protected override async Task<IEnumerable<Claim>> GetClaimsFromAccount(User user)
        {
            List<Claim> claims = (await base.GetClaimsFromAccount(user)).ToList();
            if (user.Email !=null && user.Email.EndsWith("@site.ro"))
            {
                claims.Add(new Claim("role", "myAdmin"));
            }
            return (IEnumerable<Claim>)claims;
        }    
    }
```

**Comment by davidmrichter** [comment]
Hello 
I am using a UserService derived from InMemoryUserService. there is no GetClaimsFromAccount to override. 

I add the claims somehow like that.
            InMemoryUser user = Enumerable.SingleOrDefault<InMemoryUser>(Enumerable.Where<InMemoryUser>((IEnumerable<InMemoryUser>)Users.Get(), (Func<InMemoryUser, bool>)(u =>
            {
                if (u.Username == username)
                    return u.Password == password;
                return false;
            })));
            if (user != null)
            {
                var n = CreateNewResult("ExtraClaim1,"ExtraClaim2", user.Subject, username, "password", "idsrv", "idsrv");
                return Task.FromResult<AuthenticateResult>(new AuthenticateResult(username, username, n.Claims, n.GetIdentityProvider(), n.GetAuthenticationMethod()));
            }
            return Task.FromResult<AuthenticateResult>((AuthenticateResult)null);

But then the extra claims are not in the accesstoken. I did define an identityScope to include those new claims, so it should basically work, right?i 
if I add the Claims to the users manually they are there.

Any idea whats wrong?

**Comment by davidmrichter** [comment]
I solved it by overrideing following method from IMemoryUserService
 public override Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
        {

**Comment by leastprivilege** [comment]
The InMemoryUserService is mostly for demo/prototyping purposes. Not for production.

You really want to write a user service from scratch - also a very enlightening process since you will learn a lot about how identityserver really works.

**Comment by davidmrichter** [comment]
Thanks a lot
