### ISSUE TITLE
WPF Client - 'error determining which application you are signing into'

### ISSUE THREAD

**Issue by wmcainsh** [IdentityServer/IdentityServer3#1192]
I have setup IdentityServer as a standalone MVC app.
I have a WPF client using hybrid flow to authenticate and gain access to an Api.

The solution works as expected with IdentityServer running on my dev machine and an internal test server but when moved to an online test server, after submitting my credentials, I first get: 

__*This page can’t be displayed...*__

When I refresh this I get:

__*There is an error determining which application you are signing into. Return to the application and try again.*__

If I browse to the IdentityServer and log in it shows that I have given permissions to the app.

What's the best way to debug this?

**Comment by loctanvo** [comment]
I would [enable logging in IdServer](http://identityserver.github.io/Documentation/docs/configuration/logging.html) to see what's wrong with the request.

>There is an error determining which application you are signing into. Return to the application and try again.

I guess that's just because you hit refresh and the authorization context (SignInMessage) already has been consumed.

**Comment by wmcainsh** [comment]
Thanks for the logging pointer.

The logging didn't show any errors but further digging identified that the url being returned from the server was too long for the WPF WebBrowser to handle.

I've changed the responseMode to form_post and managed to get this working. Are there any samples available for consuming the post response in a WPF Client as I'm not sure that I'm doing it properly?

**Comment by leastprivilege** [comment]
Yea that's a common problem unfortunately. 

Handling the form post in WPF is on my todo list for a long time now - tell me when you figured it out.

**Comment by wmcainsh** [comment]
This is what I've done to get it working...

```
private void webView_Navigating(object sender, NavigatingCancelEventArgs e)
{
    if (e.Uri.ToString().StartsWith(_callbackUri.AbsoluteUri))
    {
        var document = (IHTMLDocument3)((WebBrowser)sender).Document;
        var inputElements = document.getElementsByTagName("INPUT").OfType<IHTMLElement>();
        var resultUrl = "#";

        foreach (var input in inputElements)
        {
            resultUrl += input.getAttribute("name") + "=";
            resultUrl += input.getAttribute("value") + "&";
        }

        resultUrl = resultUrl.TrimEnd('&');

        AuthorizeResponse = new AuthorizeResponse(resultUrl);
                
        e.Cancel = true;
        this.Visibility = Visibility.Hidden;

        if (Done != null)
        {
            Done.Invoke(this, AuthorizeResponse);
        }
    }
}
```

**Comment by leastprivilege** [comment]
Is there a way to distinguish between GET (with #) and POST ? If yes this would be a nice addition to our WPF implicit client sample.

**Comment by wmcainsh** [comment]
With a POST the WebBrowser control only ever sees 'http://oob/localhost/wpfclient' for the Uri. There is no token or query which in itself may be enough of a check to determine that a post has been returned.

The code below works for me.

```
private void webView_Navigating(object sender, NavigatingCancelEventArgs e)
{
    if (e.Uri.ToString().StartsWith(_callbackUri.AbsoluteUri))
    {
        if (e.Uri.AbsoluteUri.Contains("#"))
        {
            AuthorizeResponse = new AuthorizeResponse(e.Uri.AbsoluteUri);
        }
        else
        {
            var document = (IHTMLDocument3)((WebBrowser)sender).Document;
            var inputElements = document.getElementsByTagName("INPUT").OfType<IHTMLElement>();
            var resultUrl = "#";

            foreach (var input in inputElements)
            {
                resultUrl += input.getAttribute("name") + "=";
                resultUrl += input.getAttribute("value") + "&";
            }

            resultUrl = resultUrl.TrimEnd('&');
            AuthorizeResponse = new AuthorizeResponse(resultUrl);
        }

        e.Cancel = true;
        this.Visibility = Visibility.Hidden;

        if (Done != null)
        {
            Done.Invoke(this, AuthorizeResponse);
        }
    }
}
```

**Comment by leastprivilege** [comment]
cool, Will add it.

**Comment by zsims** [comment]
For future reference, the URL (elements) should be URL encoded. Especially as the base64-encoded values can contain '=' for padding
