### ISSUE TITLE
IdentityServer3.Samples > source > Clients

### ISSUE THREAD

**Issue by brewhutch** [IdentityServer/IdentityServer3#1193]
Hello,

I've just started learning ThickTecture so absolutely new to it. I downloaded a sample of client projects as the path above. To be able to run each client project, how do I set up the Identity server? Where is a link to download the Identity server settings project?

Thanks,
Brew

**Comment by brockallen** [comment]
You should spend some time in the docs and the walk-thru:

https://identityserver.github.io/Documentation/
