### ISSUE TITLE
How to format "OpenID Connect discovery endpoint"?

### ISSUE THREAD

**Issue by brewhutch** [IdentityServer/IdentityServer3#1194]
Hello,

Here is what I see by Google Chrome (difficult to read).
![image](https://cloud.githubusercontent.com/assets/9948289/7139709/a868680a-e295-11e4-9faa-107bc4f78833.png)

Is there a way to set the format to show like below (I use PostMan).
![image](https://cloud.githubusercontent.com/assets/9948289/7139736/d3ee530e-e295-11e4-8c66-25df964cc61e.png)

Thanks,
Brew

**Comment by brockallen** [comment]
Use JSONView and please keep issues on topic -- this isn't a general help issue tracker.
