### ISSUE TITLE
How to restrict client to log in only with local account and hide all external providers. 

### ISSUE THREAD

**Issue by sania13** [IdentityServer/IdentityServer3#1195]
I went over all configuration properties for the client object and did not find how to restrict client to log in only with local account and hide all external providers. If I want to log with any external providers I can set IdentityProviderRestrictions = new List<string> () {"YourProvider"}, but how to do with local clients only.

**Comment by leastprivilege** [comment]
try

IdentityProviderRestrictions = new List () {"Local"}

**Comment by sania13** [comment]
actually proper name would be "idsrv".

IdentityProviderRestrictions = new List () {"idsrv"},


Ref. in your code:

 public const string BuiltInIdentityProvider         = "idsrv";

**Comment by leastprivilege** [comment]
Local works as well. Or any other string that does not map to an external idp.

**Comment by jeremycook** [comment]
Just a heads up, "Local" does not currently work with IdentityServer3 v2.0.0-rc1. Using "idsrv" or the equivalent constant `IdentityServer3.Core.Constants.BuiltInIdentityProvider` is working.

**Comment by raxitr** [comment]
"Local" does not work however "idsrv" works. Upon not finding the correct provider IdServer will not redirect to client application and would render login page again.
