### ISSUE TITLE
Silent Renew Token issue in IE

### ISSUE THREAD

**Issue by rimper2001** [IdentityServer/IdentityServer3#1196]
Hi, I'm using ASP.NET to host a SPA Application built with AngularJs.  I setup the ASP.NET Application with an OpenId Cookie to force authorization of the user prior to accessing the site.  Then I set up the Angular App so that it uses the oidc.js file to do a silent renew in an Iframe to get an Access Token whenever it is near Expiration.  I figured by using my ASP.NET site as the entry point, that the spa application would simply need an access token to access the APIs.  I found that in Chrome and Firefox, this works well, but when I'm on IE and the Identity Server is on a different domain than my angular application, IE will not pass the Identity Server Cookies back when it attempts to access the /connect/authorize endpoint inside of the iframe, and therefore returns "login_required" instead of a new access token.

Do you have any idea what may be the issue here?

**Comment by brockallen** [comment]
If the two hosts are in the same zone, then (according to my recollection) it should work. But you are correct -- if they're in 2 different zones, then IE won't allow that.

**Comment by rimper2001** [comment]
What do you recommend for silent refreshing our access token when our application is not on the same domain as the identity server?  Is common practice that the identity server lives on the same domain as each application?

**Comment by brockallen** [comment]
I didn't say different domain -- I said different zone. That's an IE specific feature.

**Comment by rimper2001** [comment]
You are absolutely correct.  The problem was because I'm hosting the identity server and the app I'm developing is showing up under an Intranet zone.  Thank you!  Sorry to bother you.

**Comment by brockallen** [comment]
Fixed now?

**Comment by rimper2001** [comment]
Yep thank you so much!
