### ISSUE TITLE
Recover authentication session

### ISSUE THREAD

**Issue by securityCurious** [IdentityServer/IdentityServer3#1197]
Is it possible to restablish a session to IdentityServer (get cookies set in browser) only from a token (id token or access token) ?

For example after authentication from device A, device B could also authenticate without any prompt  passing only a token (or whatever data is needed).

Thanks

**Comment by brockallen** [comment]
_Is it possible to restablish a session to IdentityServer (get cookies set in browser) only from a token (id token or access token) ?_

Most anything is possible. But that's not something we directly support.

_For example after authentication from device A, device B could also authenticate without any prompt passing only a token (or whatever data is needed)._

Well this doesn't exactly match what you asked above. If device B has the token, then why does it need to re-authenticate?

**Comment by securityCurious** [comment]
I certainly didn't expose the scenario very well.
I used the devices case to simplify my real case which is a bit more convoluted. The idea is to reestablish a session to IdSrv without authentication cookies but using previous session data (tokens for example).

The following is my real case:

I have two websites:
- Website A. Uses resource owner password flow to authenticate users with IdSrv. In this case IdSrv cannot set an authentication cookie on user's browser.
- Website B. Uses code flow to authenticate users with IdSrv. In this case IdSrv does set an authentication cookie on user's browser.

The idea is that website A, after successfully authenticating a user with resource owner password flow, could (via hidden iframe, or AJAX call) get IdSrv to start an authentication session (set the authentication cookie). This way, when user visits website B, IdSrv would automatically log her in without requiring prompting her again.

**Comment by securityCurious** [comment]
I'm told that OpenID Connect Session Management allows this functionality: I can send an authentication request with prompt=none id_token_hint with the current id_token. This would issue a new id_token and I suppose that would also create a session.
What do think of this approach?

**Comment by brockallen** [comment]
Well, if they're already logged in then they already have a session. If they're not logged in then they will need to authenticate (and if you pass prompt=none then you'll get back the login_required error).  There's no need to pass the id_token_hint given how IdSvr already works.
