### ISSUE TITLE
Request Refresh Token

### ISSUE THREAD

**Issue by juscelior** [IdentityServer/IdentityServer3#1198]
Every time I call the RequestRefreshTokenAsync method returns { " error " : " invalid_grant "}. However when I invoke the RequestResourceOwnerPasswordAsync method passing the offline_access scope returns  { "error" : " invalid_scope " }

Any idea about this error ?

**Comment by brockallen** [comment]
Enable logging in Idsvr and follow the messages for more info.

**Comment by cwdyang** [comment]
What do I need to do to enable offline_access scope? I would like to make a request to the connect/token endpoint to obtain a refresh token, i have added the offline_access scope to the client i am requesting a RT for but i keep on getting "invalid_scope", the offline_access exists in the global scope store too.

What am I missing here?
