### ISSUE TITLE
Manage ReturnUrls from client Application.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3#1199]
I work on an application that serve some a service to customers via vanity urls. In this case we have many urls (at least one url for one customer). So In my opinion an api endpoint to send return urls from  client application to Idsrv  is a nice feature to have. 
Thanks to your awesome project.

**Comment by mikeandersun** [comment]
I 'm in wrong way?

**Comment by loctanvo** [comment]
Not sure I understand you correctly. Do you want the clients to be able to dynamically register redirect uris? If so, I'm quite sure this is not going to be supported by idserver out of the box. A somewhat related discussion can be found [here](https://github.com/IdentityServer/IdentityServer3/issues/535).

If you are storing your clients' setup in a DB, there's nothing that stops you from creating an endpoint to add redirect uris. We have our custom web interface for doing these things.
