### ISSUE TITLE
How to configure MVC app with Ajax?

### ISSUE THREAD

**Issue by ninety7** [IdentityServer/IdentityServer3#1200]
I have an MVC app set up as follows:
```c#
app.UseCookieAuthentication();
app.UseOpenIdConnectAuthentication(options =>
{
    options.ClientId = "mvc";
    options.Authority = "http://localhost:51705";
    options.RedirectUri = "http://localhost:1423";
    options.ResponseType = "id_token";
    options.SignInAsAuthenticationType = "Cookies";
});
```
I also use a custom `ICorsPolicyService` implementation on the id server that returns `true` for every origin.

There are no problems at all when I access an action method marked with the `[Authorize]` attribute. I am redirected to the idserver login page, I enter my credentials, and am redirected to the requested protected page without any problem.

Some of my views perform client-side javascript calls to protected MVC controller actions, but there are times, when an ajax call is made, that the server answers with the 302 redirect to idserver's `/connect/authorize?...` page. Once a request is made to that page, the browser's js console reports:
```
XMLHttpRequest cannot load http://localhost:51705/connect/authorize?client_id=mvc&redirect_uri=... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1423' is therefore not allowed access.
```
The identity server's error message reports:
```
CORS request made for path: /connect/authorize from origin: http://localhost:1423 but rejected because invalid CORS path
```
I looked at the source code and found that `/connect/authorize` is effectively not included in the allowed CORS paths constant, so this leads me to think there is a different way I should be handling these Ajax requests. I am not an expert on the subject yet, so I may be missing something.

I have looked on the examples in the repo, as well as azure ad examples for open id connect configuration, but have not found a solution to my problem. If somebody can help me with this, I'd greatly appreciate it!

**Comment by johnkors** [comment]
There are some people with the same kind of question in this issue tracker. Search for AJAX for example. The issue is not directly related to idsrv, but how you configure your auth at the clients and especially clients that have both web and api resources.
