### ISSUE TITLE
Link external login to a user account

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer3#1201]
We have a MVC application for User Management and we want to add the ability to link external login providers (registered with IdentityServer) to the user accounts.

Normally, we would call Authentication.Challenge(properties, provider) on the OWIN context with a redirect url to our MVC application. But the IdentityServer is hosted from a different project and is not part of the User Management application.

Since we don't want to register all the external login providers twice (which would also mean we need to configure 2 applications with each provider), we're looking to reuse the LoginExternal method inside IdentityServer3 (registered at /external). But it seems to be fixed for signing in, am I correct?

Any example on how we can reuse as much as possible to link external login providers?

**Comment by johnkors** [comment]
Sure. Create an implementation that runs the external login provider middlewares, and re-use that at each client.

For instance, a implemenation of the same signature that idsrv options takes:

```
    public interface IExternalLoginConfigurator
    {
        void ConfigureExternalLogins(IAppBuilder app, string signInAsType);
    }
```

**Comment by huysentruitw** [comment]
Thank you for your answer. That was indeed my first approach. But the problem is that you need to configure 2 apps on each external provider because 2 different redirect urls will be used: one for the IdentityServer and one for the User Management webpage, f.e.: https://idsrv.myhost.com and https://manage.myhost.com. Some providers don't care about different subdomains, but for other providers the redirect url must match 100%.

**Comment by leastprivilege** [comment]
You can "remote control" IdSrv and choose the identity providers as part of the authorization request. Check the docs for acr_values.

**Comment by huysentruitw** [comment]
If I understand correctly, what you mean is: override PreAuthenticateAsync from MembershipRebootUserService, then call the authorize endpoint from the User Management webapp using a plain HTTP request (bypassing the OWIN OpenIdConnectAuthentication middleware) passing in the selected provider as additional acr_values.

If an external provider is seen in the acr_values, I will not call the base.PreAuthenticateAsync(), but instead ask for a Challenge to the external provider.

Right? :)

**Comment by huysentruitw** [comment]
Oops, just seen that I can pass the required login provider to the acr_values. I will have to try this and come back later. Any idea how I would pass the idp as part of acr_values as GET url parameters?

**Comment by huysentruitw** [comment]
Ok, so I have a "Facebook" button and when clicked I get to this controller method:

    // POST: Users/Logins
    [HttpPost]
    public async Task<ActionResult> Logins(Guid id, Guid providerId)
    {
        var provider = await providerRepository.GetById(providerId);
        if (provider == null)
            return HttpNotFound();

        var uriBuilder = new UriBuilder(Constants.Authority + "connect/authorize");
        var query = HttpUtility.ParseQueryString(uriBuilder.Query);
        query["client_id"] = Constants.ClientId;
        query["scope"] = "openid";
        query["response_type"] = "id_token token";
        query["redirect_uri"] = Constants.ClientRedirectUri;
        query["nonce"] = Guid.NewGuid().ToString();
        query["acr_values"] = "idp:" + provider.Name;
        uriBuilder.Query = query.ToString();
        var url = uriBuilder.ToString();
        return Redirect(url);
    }

Redirect goes well and I get to the consent page of IdentityServer, when I accept it gets redirected to the redirect_url with an id_token and access_token in the query string.

But before I go any further on this route, I was thinking if it isn't possible to re-use the OpenIdConnectClient middleware that is already hooked up. Therefore I created this class:

    internal class ChallengeResult : HttpUnauthorizedResult
    {
        public ChallengeResult(string provider, string redirectUri)
            : this(provider, redirectUri, null)
        {
        }

        public ChallengeResult(string provider, string redirectUri, string userId)
        {
            LoginProvider = provider;
            RedirectUri = redirectUri;
            UserId = userId;
        }

        public string LoginProvider { get; set; }
        public string RedirectUri { get; set; }
        public string UserId { get; set; }

        public override void ExecuteResult(ControllerContext context)
        {
            var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
            if (UserId != null)
                properties.Dictionary[XsrfKey] = UserId;
            //properties.Dictionary["acr_values"] = "idp:" + LoginProvider;
            context.HttpContext.GetOwinContext().Authentication.Challenge(properties);
        }
    }

And changed the controller method to:

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Logins(Guid id, Guid providerId)
        {
            var provider = await providerRepository.GetById(providerId);
            if (provider == null)
                return HttpNotFound();
            return new ChallengeResult(provider.Name, Url.Action("LinkLoginCallback", "User"), id.ToString());
        }

That looks a lot easier, but I can't figure out how I can pass the additional acr_values in this case? Any ideas?

**Comment by leastprivilege** [comment]
You need to put extra data you want to send to the middleware into the OWIN environment. The handle the RedirectToIdentityProvider notification on the middleware to retrieve the values and modify the protocol message.

**Comment by huysentruitw** [comment]
I've added `owinContext.Set("ForwardToLoginProvider", LoginProvider);` to the `ExecuteResult` method of the `ChallengeResult` class I posted earlier. Then in the `RedirectToIdentityProvider`-handler I have this:

``` C#
if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
{
    var loginProvider = n.OwinContext.Get<string>("ForwardToLoginProvider");
    if (loginProvider != null)
        n.ProtocolMessage.AcrValues = "idp:" + loginProvider;
}
```

Redirect to consent page works fine, but then an other problem arrises. I get back into this controller method:

``` C#
[HttpGet]
public async Task<ActionResult> LinkLoginCallback(Guid id)
{
    var result = await HttpContext.GetOwinContext().Authentication.AuthenticateAsync(Constants.AuthenticationType);
    if (result == null || result.Properties == null)
        return HttpNotFound("Cookie not found or incomplete");
    var entity = service.GetByID(id);
    if (entity == null)
        return HttpNotFound();
    // Need provider, provider id and claims
    //service.AddOrUpdateLinkedAccount(entity, )
    return HttpNotFound();
}
```

But, since IdentityServer3 is using MemberShip reboot, the `UserService` that derives from `MembershipRebootUserService<UserAccount>` has added the unknown external login to the user database and has transformed the `sub` claim to a local `claim`. So at the time I get back into the controller method, I don't have the original claim anymore, and a user that I don't want is already added to the database. Does this mean I also need to tweak the UserService or is this scenario forseen somehow?

**Comment by leastprivilege** [comment]
Sure - you always have to tweak the user service. Consider our implementation as templates only.

**Comment by huysentruitw** [comment]
I'm overriding `AuthenticateExternalAsync` in the `UserService : MembershipRebootUserService<UserAccount>` but first of all, the `SignInMessage` holds an empty `AcrValues` collection, is this a bug? The ´ReturnUrl` contains the part `acr_values=idp%3AFacebook`.

But when I try the code below, I'm getting a 'access_denied' error:

``` C#
public override async Task<AuthenticateResult> AuthenticateExternalAsync(ExternalIdentity externalUser, SignInMessage message)
{
    #region Hack
    // This hack intercepts requests to link external login providers to a local user account, instantiated from WebApp
    // If we detect such a request, we will forward the external claims to the callback instead of passing them through
    // the default MembershipRebootUserService<T> implementation which would create a new user instead.
    if (message.ReturnUrl.Contains("acr_values=idp%3A"))
    {
        var nameClaim = externalUser.Claims.FirstOrDefault(c => c.Type == "name");
        var name = nameClaim != null ? nameClaim.Value : "";

        return new AuthenticateResult(
            subject: externalUser.ProviderId,
            name: name,
            claims: externalUser.Claims,
            identityProvider: externalUser.Provider,
            authenticationMethod: Constants.AuthenticationMethods.External
        );
    }
    #endregion
    return await base.AuthenticateExternalAsync(externalUser, message);
}
```

![capture](https://cloud.githubusercontent.com/assets/4618744/7198639/8b69595c-e4ee-11e4-9ea7-6dbded65a411.PNG)

Also as you can see in the network log, it seems that the authorization is retried 3 times. Any idea how I can proceed?

**Comment by leastprivilege** [comment]
I'd rather say your authorize request is buggy - make sure you have a delimiter between redirectUri and acr_values.

**Comment by huysentruitw** [comment]
I believe the request is fine: if I don't override `AuthenticateExternalAsync` in the `UserService`, I get straight to the consent page and a new user is added to the database.

**Comment by huysentruitw** [comment]
Ok, it trickier then I thought, the problem was the `IsActiveAsync` method that returned false for the `Facebook` subject (because MR doesn't find that user in the db of course). Then also the default implementation of `GetProfileDataAsync` fails because of that subject.

Just wondering how you guys implemented those linked accounts. Have you ever tested something like this?

**Comment by leastprivilege** [comment]
I haven't - but I am sure you can write a little tutorial once you have it working.

you probably also want to pass another value in acr_values that indicates that you are in "linking mode".

**Comment by huysentruitw** [comment]
Security wise, is it safe to send a user ID through acr_values? If yes, I could add `acr_values=idp:<loginprovider> linking:<userId>'.

**Comment by leastprivilege** [comment]
Not sure I follow - but the actual linking should be done in the client application - not in identity server

**Comment by huysentruitw** [comment]
Well, if I can trust that value, it would make the linking process a lot easier:
* The client app calls for a `Challenge` with additional `idp:<provider>` and `linking:<userid>` in the `acr_values`
* In `UserService.AuthenticateExternalAsync()`, look for the `linking:<userid>` value
* If found, link the external account to that user and return the local subject and claims

Otherwise it can be confusing that, in one case, the local subject is returned while in the other, the external subject is returned.

Could it be added as a feature to the default `MembershipRebootUserService` ?

**Comment by leastprivilege** [comment]
You can't trust any values of course.

**Comment by huysentruitw** [comment]
@loctanvo do you mind sharing the details on how your current solution works with the partial login? Do you still use the Challenge method for invoking the authorize endpoint? How does that partial login work in this case?

**Comment by loctanvo** [comment]
@huysentruitw Sorry for not getting back to this. Have been extremely busy lately. From the top of my head, no warranties that the details are correct:

We have IdServer and a RP. Typically the user's profile page is part of this RP, where she can reset password, edit user info etc. Here I'll use Facebook as an example.

<h3>When user not signed in</h3>
The user will click "Sign in with Facebook" in IdServer, she will be taken to FB and back. In AuthenticateExternalAsync, if we can't find the FB id on any of our existing users, she will be redirected (partial redirect) to a page to create a user. We there read the partial login cookie, create a user in our DB and then resume login. After that, the user is logged in and authenticated with idserver as idp, not FB.

<h3>When user is signed in</h3>
She then goes to her profile page. She clicks "Link my FB profile". We here do a challenge *directly to FB*, bypassing IdServer. When things come back correctly, we just add the FB id to the logged in user. This is allow the user to start logging in with FB next time. Yes, we have FB-Middleware configured both at IdServer and RP.

**Comment by huysentruitw** [comment]
Thank you for your answer and time. This is also a scenario I had in mind, but don't you need to register two applications with FB then? I can imagine that the FB AppID/Secret isn't the same for IdSrv and your RP?

**Comment by loctanvo** [comment]
We are using the same FB app (appId and secret), just different redirect urls registered for the same app. It's the same team maintaining the STS and the user admin part :-) .

**Comment by huysentruitw** [comment]
Started to implement this method of sharing the identity providers. But I'm currently stuck at the point a signed in user tries to link an external account. What happens is that the local authentication ticket gets replaced with the one from the external login provider (Facebook, Twitter):

This is the controller action that initiates the linking process:

```C#
//
// POST: /Manage/LinkLogin
[HttpPost]
[ValidateAntiForgeryToken]
public ActionResult LinkLogin(string provider)
{
	// Request a redirect to the external login provider to link a login for the current user
	return new AccountController.ChallengeResult(provider, Url.Action("LinkLoginCallback", "Manage"), User.Identity.GetUserId());
}
```

But when it comes back in the `LinkLoginCallback`, the cookie has been replaced and all claims etc are replaced.

Claims before `LinkLogin`:

![image](https://cloud.githubusercontent.com/assets/4618744/7332879/d539a45a-eb57-11e4-8907-e52610a59df5.png)

Claims after `LinkLogin`, with Facebook as provider:

![image](https://cloud.githubusercontent.com/assets/4618744/7332888/1ee6d636-eb58-11e4-9ca8-2b488cc45f18.png)

Any ideas how to intercept the claims from the external provider without replacing the current authentication?

**Comment by huysentruitw** [comment]
Ok, the last problem was that I needed to configure a separate cookie for the external login providers:

I just had to add:

```C#
app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
```

and use the same `DefaultAuthenticationTypes.ExternalCookie` as `SignInAsAuthenticationType` property for all the external login providers to get things working.

Thanks guys for the great pointers :)
