### ISSUE TITLE
AccessTokenLifetime - expiration time not working

### ISSUE THREAD

**Issue by brewhutch** [IdentityServer/IdentityServer3#1202]
Hello,
I'm using a selfhost sample (IdentityServer3.Samples/source/SelfHost (Minimal)) and trying to set AccessTokenLifttime less than 5 minutes but the access token will always expire in 5 mins.

AccessTokenLifetime = 60  //want to set to expire in 1 min.

Is 5-min lifttime a minimal time?

Thanks,
Brew

**Comment by brockallen** [comment]
IIRC, the token handler allows for a 5 minute clock skew (by default). I think you can disable that.
