### ISSUE TITLE
Redirect user to application on logout

### ISSUE THREAD

**Issue by rajarameshvarma** [IdentityServer/IdentityServer3#1203]
Hi,

How to setup Identity server to redirect to application url on sign out.

I have Post Logout Redirect URL set up for the application and SignOutPrompt disabled for the Identity server. Once the user redirected to Signout endpoint i get a confirmation page saying that user is logged out. How can I redirect the user to the url configured automatically?

**Comment by loctanvo** [comment]
Have a look at the [documentation for the logout endpoint](http://identityserver.github.io/Documentation/docs/endpoints/endSession.html). You need to pass the id token to the endpoint. Not sure whether it works to not specify the logout redirect uri or not in the logout request.

Have a further look [here](http://identityserver.github.io/Documentation/docs/configuration/authenticationOptions.html). You probably want to consider these options: `EnableSignOutPrompt`, `EnablePostSignOutAutoRedirect`, `PostSignOutAutoRedirectDelay`.

**Comment by huysentruitw** [comment]
The `id_token_hint` needs to be present at logout, you can pass it in the `RedirectToIdentityProvider` callback. First, in the `SecurityTokenValidated` you add the `id_token` as a claim. Then in the `RedirectToIdentityProvider` handler, when logging out you read it back and use it as idTokenHint.

See https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs

**Comment by rajarameshvarma** [comment]
Thank you @loctanvo @huysentruitw 
My Identity Server code is little old so I have updated my code to latest bits. Not I have EnablePostSignOutRedirect. 

I have PostLogoutRedirectUri configured for the client and passing this with the request. On the Identity Server side I EnableSignOutPrompt = false, EnablePostsignOutAutoRedirect = true. Still user is not redirected back to the application.

**Comment by rajarameshvarma** [comment]
I think I found the issue. I am using a custom view service which renders the logout view instead of redirecting the user back to the client logout page. How can I overwrite the LoggedOut to redirect?

**Comment by rajarameshvarma** [comment]
Any help or suggestions on this?

**Comment by huysentruitw** [comment]
It's in the CustomViewService sample: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomViewService/CustomViewService/Content/app/loggedOut.html

**Comment by rajarameshvarma** [comment]
This one will display a link on the logged out view for the user to click on it, Is there a way to redirect automatically? One way I am thinking is to use a script that sets the location.href to the same url. But is there a better way?

**Comment by huysentruitw** [comment]
Since you need to return a `Stream` without headers, I think a scripted redirect is your only option.

**Comment by rajarameshvarma** [comment]
Okay thank you @huysentruitw

**Comment by huysentruitw** [comment]
Just came across the option `EnablePostSignOutAutoRedirect` on http://identityserver.github.io/Documentation/docs/configuration/authenticationOptions.html

Isn't that what you want?

**Comment by omayhemo** [comment]
The dead links littered throughout these threads are infuriating.
