### ISSUE TITLE
Custom ClaimsIdentityFactory not being called

### ISSUE THREAD

**Issue by shawndewet** [IdentityServer/IdentityServer3#1204]
I am running your sample UserService-AspNetIdentity to understand how custom claims can be added to the returned token.  In your class Selfhost.AspId.UserManager, the constructor has this line of code:
this.ClaimsIdentityFactory = new ClaimsFactory();
Setting a breakpoint on that line shows that it is called as expected when I run a client (the sample client I'm testing with is Mvc CodeFlowClient Manual).
However, I have also set a breakpoint on the first line of the "override CreateAsync" method of the referenced ClaimsFactory.
This breakpoint never get hit though.  What do I need to do in order to invoke that calling of this method in order to add the custom claims?
I have attached a screen shot for clarity of what code I am referring to.
![customclaims](https://cloud.githubusercontent.com/assets/1556343/7174309/05e52fec-e406-11e4-9e50-34059ad931b9.png)

**Comment by brockallen** [comment]
I think at one point we were going to use it, but then some design issue came up that we decided we shouldn't. You can always override `GetClaimsFromAccount` and use it.

**Comment by shawndewet** [comment]
Thanks Brock.  Now I'm taking a look at the implementation thereof in the AspNetIdentity server example, where I can see that the claims collection being returned to the client (in my case I'm testing the "roclient" example) as per the attached screenshot.  There is a preferred_username claim.
![serverclaims](https://cloud.githubusercontent.com/assets/1556343/7195626/32bc645a-e4c3-11e4-8bde-2228e2d255d4.png)
However, the claim is not visible on the client side:
![clientclaims](https://cloud.githubusercontent.com/assets/1556343/7195657/a1742b58-e4c3-11e4-81a7-a117e1245b5a.png)

Please advise what I am missing in order to have this peferred_username claim being propagated to the client.

**Comment by brockallen** [comment]
Is the client requesting the profile scope?

**Comment by shawndewet** [comment]
Following your question, I edited the sample client to call the profile scope:
```c#
static TokenResponse RequestToken()
{
	var client = new OAuth2Client(
	new Uri(Constants.TokenEndpoint),
	"roclient",
	"secret");

	// idsrv supports additional non-standard parameters 
	// that get passed through to the user service
	var optional = new Dictionary<string, string>
	{
		{ "acr_values", "tenant:custom_account_store1 foo bar quux" }
	};

	return client.RequestResourceOwnerPasswordAsync("etienne", "P@ssw0rd", "read write profile", optional).Result;
}
```
and edited the sample server to allow the profile scope:
```c#
new Client
{
	ClientName = "Resource Owner Flow Client",
	Enabled = true,
	ClientId = "roclient",
	ClientSecrets = new List<Secret> {
		new Secret("secret".Sha256())
	},
	Flow = Flows.ResourceOwner,
	
	AllowedScopes = new List<string>
	{ 
		"read",
		"write",
		"profile"
	},

	AccessTokenType = AccessTokenType.Jwt,
	AccessTokenLifetime = 360,
}
```

Still the access token remains as indicated in my last screenshot.  Please help.

**Comment by shawndewet** [comment]
I may be missing something fundamental here.  Even if I edit the client code above to request the "email" scope, and edit the server's Client definition code above to allow the email scope, and edit the server's "GetClaimsFromAccount" code in the screenshot above to return a hardcoded email claim, such that the claims returned by the method are:
![server claims](https://cloud.githubusercontent.com/assets/1556343/7213679/e4013fe2-e586-11e4-8dea-bab87a50248d.png)
Still the "Access Token (decoded)" response on the client remains as per the screenshot indicated above - no additional claims are returned in the access token.
Please help me understand what is going on here? What am I doing wrong?

**Comment by huysentruitw** [comment]
Those claims are later filtered in `GetProfileDataAsync` so, once breaked, step further through the code to see what's going on.

**Comment by brockallen** [comment]
profile scope only works if you're requesting a token for authentication. That sample client you're using is only getting a token to call an API, thus only resource scopes can be requested.
