### ISSUE TITLE
i have connected Idsrv3 to server database.. to load client redirect Urls.

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#1205]
if i am updating redirect  urls in the server database. it is taking time to load the new changes nearly 1 hour.

 is that any concept of time slot is there to check data base in Idrsv3. (like checking database every one hour like that)..

**Comment by brockallen** [comment]
Are you using the client store cache?

**Comment by RajMondaz** [comment]
I am  using Customer service application for Idrsv3 i am not sure whether this client store cache is there in that or not .

**Comment by brockallen** [comment]
Well, if it is, then it explains the behavior you see.

**Comment by RajMondaz** [comment]
ok ,client store cache is present in my application then how much time it
will take to update from server database

**Comment by brockallen** [comment]
How ever long you configure the cache duration.

**Comment by brockallen** [comment]
And here are the docs for that: https://identityserver.github.io/Documentation/docs/advanced/caching.html

**Comment by RajMondaz** [comment]
ok , then i will look for cache duration where  i have to make change.

Thank you.
