### ISSUE TITLE
Can't renew token in Safari browser (desktop windows)

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#1206]
Oidc.js throws error in getJSON. 

```
var xhr = new XMLHttpRequest();
xhr.open("GET", url);
xhr.responseType = "json";
```

After calling open method on xhr object can't access xhr object and it throws:

INVALID_STATE_ERR: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.

after trying to modify response type it throws 

Failed to load metadata (SYNTAX_ERR: DOM Exception 12)

Safari 5.1.7 (It's old webkit from may 2012) Can't check if it exist in new version because it's only on mac.

**Comment by brockallen** [comment]
Did you try changing the order of those two lines? I don't know if that's it...

**Comment by brockallen** [comment]
Also, the token manager and oidc client repos are here now -- so future issues should be raised there: 

https://github.com/IdentityModel/oidc-client
https://github.com/IdentityModel/oidc-token-manager

**Comment by pawepaw** [comment]
After realising that safari for windows uses old webkit (from may 2012) i abandoned it. In new version of safari (on iOS) it works fine.

Thanks for response.
