### ISSUE TITLE
WPF Client - Old IE version Script Error

### ISSUE THREAD

**Issue by wmcainsh** [IdentityServer/IdentityServer3#1207]
When the WebBrowser control opens the log in page it gets the error below:

![scripterror](https://cloud.githubusercontent.com/assets/11405829/7182995/9c77b092-e44c-11e4-85ae-14fe6bd25be8.jpg)

This is probably related to the client PC running an old version of IE. Is there a minimum browser version that is required?

**Comment by brockallen** [comment]
IIRC we support IE9 and later.
