### ISSUE TITLE
MVC Authentication sample - login not working

### ISSUE THREAD

**Issue by tomdeleu** [IdentityServer/IdentityServer3#1208]
I'm trying to get the "MVC Authentication" sample working.

* Downloaded the sample sources and opened the visual studio solution of "MVC Authentication"
* Build the sample and run both projects (API & MVC Authentication) simultaneously. (Nuget packages are downloaded, browserwindow opens etc.)
* I press "login" and login with "bob" and "secret"
* Consent form is shown and I press OK

And after that I receive the following exception: http://prntscr.com/6ufylu
Full stack trace: http://pastie.org/10096127

**Comment by brockallen** [comment]
Try from an incognito window -- i want to ensure you're not getting incorrect cookies and userids. The error is basically saying that the user you just logged in with is not in the in-memory user database. Some something's wrong about how you are being authenticated.

**Comment by tomdeleu** [comment]
Same exception, unfortunately: http://prntscr.com/6ug5fo

**Comment by brockallen** [comment]
Did you do anything to change the values of the in-memory users configuration in IdentityServer?

**Comment by tomdeleu** [comment]
No I didn't. just re-extracted the source of the samples to be sure :) Extract from ZIP, open solution, press F5, wait for NuGet and go...

**Comment by brockallen** [comment]
Yea, something's wonky then. I'll download directly from github and try to repro.

**Comment by tomdeleu** [comment]
Awesome! Thanks for the quick response :)

**Comment by brockallen** [comment]
Ah, you're using the MVC Authentication sample -- that's the self-contained sample for the walk thru. Run the clients solution instead when you're running IdentityServer from the github repo.
