### ISSUE TITLE
How to access html fields (as 'remember my login') from AuthenticateLocalAsync?

### ISSUE THREAD

**Issue by AlexSanchezN** [IdentityServer/IdentityServer3#1210]
Could you describe how to accés html defined fields (as you have in login.html 'remember my login') from IUserService methods as AuthenticateLocalAsync?

Thanks in advance

**Comment by brockallen** [comment]
You can inject into your user service the OwinEnvironmentService, which has the OWIN environment. You then wrap that with an OwinContext and use the ReadForm API.

**Comment by AlexSanchezN** [comment]
OK. Thanks!
I really appreciate the time you spend on this project
