### ISSUE TITLE
Standard items to go in an access_token

### ISSUE THREAD

**Issue by sushant2517** [IdentityServer/IdentityServer3#1211]
We are using identity server3 middleware to generate an access_token.

What we found that the access_token that gets generated is around 2 Kb in size which seems a bit bulky. On decrypting the token, we found that it has a lot of properties like the entire serialized Client object along with detailed serialized Claims collection which seems to be taking most of the space.
Is it possible to trim the token down to have only what we really need? Do these properties exist in the token as a standard best practice?

Any help in this regard is highly appreciated.

**Comment by brockallen** [comment]
_On decrypting the token, we found that it has a lot of properties like the entire serialized Client object_

this does not sound right to me. can you show us the access token?

**Comment by sushant2517** [comment]
Hi Brock,

Thanks so much for your quick response.

Here is the actual deserialized token (before signing):

{
	"Audience": "http://localhost:9000/identity/resources",
	"Issuer": "http://localhost:9000/identity",
	"CreationTime": "2015-04-17T02:57:23.6879733+00:00",
	"Lifetime": 31536000,
	"Type": "access_token",
	"Client": {
		"Enabled": true,
		"ClientId": "ES",
		"ClientSecrets": [{
			"Description": null,
			"Value": "wuWoMUQ24KZ3o2cF0OQ21hVilqmzaz4BKZM5Sx99x4E=",
			"Expiration": "2015-04-30T15:34:56.9488052+10:00",
			"ClientSecretType": null
		},
		{
			"Description": null,
			"Value": "XrtWUMic7Zk5mfT0EIXb1GOEEVLLIrH7dlvPbyF3QKE=",
			"Expiration": "2015-04-12T15:36:56.9488052+10:00",
			"ClientSecretType": null
		}],
		"ClientName": "TestClient3",
		"ClientUri": null,
		"LogoUri": null,
		"RequireConsent": true,
		"AllowRememberConsent": true,
		"Flow": 5,
		"AllowClientCredentialsOnly": false,
		"RedirectUris": [],
		"PostLogoutRedirectUris": [],
		"ScopeRestrictions": ["offline_access",
		"bFormBuilder"],
		"IdentityTokenLifetime": 300,
		"AccessTokenLifetime": 31536000,
		"AuthorizationCodeLifetime": 300,
		"AbsoluteRefreshTokenLifetime": 2592000,
		"SlidingRefreshTokenLifetime": 1296000,
		"RefreshTokenUsage": 0,
		"UpdateAccessTokenClaimsOnRefresh": false,
		"RefreshTokenExpiration": 1,
		"AccessTokenType": 0,
		"EnableLocalLogin": true,
		"IdentityProviderRestrictions": [],
		"IncludeJwtId": false,
		"Claims": [],
		"AlwaysSendClientClaims": false,
		"PrefixClientClaims": false,
		"CustomGrantTypeRestrictions": ["locksmith_grant"],
		"AllowedCorsOrigins": []
	},
	"Claims": [{
		"Issuer": "LOCAL AUTHORITY",
		"OriginalIssuer": "LOCAL AUTHORITY",
		"Properties": {
			
		},
		"Subject": null,
		"Type": "client_id",
		"Value": "ES",
		"ValueType": "http://www.w3.org/2001/XMLSchema#string"
	},
	{
		"Issuer": "LOCAL AUTHORITY",
		"OriginalIssuer": "LOCAL AUTHORITY",
		"Properties": {
			
		},
		"Subject": null,
		"Type": "scope",
		"Value": "bFormBuilder",
		"ValueType": "http://www.w3.org/2001/XMLSchema#string"
	},
	{
		"Issuer": "LOCAL AUTHORITY",
		"OriginalIssuer": "LOCAL AUTHORITY",
		"Properties": {
			
		},
		"Subject": null,
		"Type": "scope",
		"Value": "offline_access",
		"ValueType": "http://www.w3.org/2001/XMLSchema#string"
	},
	{
		"Issuer": "LOCAL AUTHORITY",
		"OriginalIssuer": "LOCAL AUTHORITY",
		"Properties": {
			
		},
		"Subject": null,
		"Type": "sub",
		"Value": "1632322",
		"ValueType": "http://www.w3.org/2001/XMLSchema#string"
	},
	{
		"Issuer": "LOCAL AUTHORITY",
		"OriginalIssuer": "LOCAL AUTHORITY",
		"Properties": {
			
		},
		"Subject": null,
		"Type": "amr",
		"Value": "locksmith_grant",
		"ValueType": "http://www.w3.org/2001/XMLSchema#string"
	},
	{
		"Issuer": "LOCAL AUTHORITY",
		"OriginalIssuer": "LOCAL AUTHORITY",
		"Properties": {
			
		},
		"Subject": null,
		"Type": "auth_time",
		"Value": "1429239443",
		"ValueType": "http://www.w3.org/2001/XMLSchema#integer"
	},
	{
		"Issuer": "LOCAL AUTHORITY",
		"OriginalIssuer": "LOCAL AUTHORITY",
		"Properties": {
			
		},
		"Subject": null,
		"Type": "idp",
		"Value": "idsrv",
		"ValueType": "http://www.w3.org/2001/XMLSchema#string"
	}],
	"Version": 3,
	"SubjectId": "1632322",
	"ClientId": "ES",
	"Scopes": ["bFormBuilder",
	"offline_access"]
}

**Comment by brockallen** [comment]
This looks very wrong. How and where are you getting this?

**Comment by sushant2517** [comment]
Hi Brock,

I think I am indeed doing it wrong. So, here is what I am actually doing:

I am basically trying to use AWS Key Management service to handle encryption for us. So, created an implementation of the TokenSigningService and IDataProtecter and inside the TokenSigningService, basically doing the following:

				public System.Threading.Tasks.Task<string> SignTokenAsync(Thinktecture.IdentityServer.Core.Models.Token token)
				{
					byte[] bytes1 = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(token));

					var encryptedData = _dataProtector.Protect(bytes1);

					return
						System.Threading.Tasks.Task.FromResult(Convert.ToBase64String(encryptedData));
				}
In the dataprotecter implementation I am using the KMS to actually encrypt this token object.

So, now after looking at the DefaultTokenSigningService more closely, looks like I should be somehow using the CreateJsonWebToken method to create the real JWTs. Would implementing SigningCredentials object for KMS be a good idea to do this?

Again, I really appreciate your help in this regard.

Thanks,
Sushant

**Comment by leastprivilege** [comment]
The purpose of the SignTokenAsync method is to turn the token object into its wire representation. You can use whatever format you want as long as your token receivers know how to validate it.

**Comment by sushant2517** [comment]
Thanks a ton for your timely response. Cheers, Sushant
