### ISSUE TITLE
Access to Context in PreAuthenticateAsync

### ISSUE THREAD

**Issue by webbkvalite** [IdentityServer/IdentityServer3#1213]
In my PreAuthenticateAsync I would need access to the IOwinContext context from the AuthenticationController. I need access to the ssl.ClientCertificate. Is that doable?

**Comment by leastprivilege** [comment]
Yes - you need to inject the OwinEnvironmentService into the ctor

**Comment by webbkvalite** [comment]
Thank you, works like a charm!
