### ISSUE TITLE
Storing email confirmation token

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1220]
Hi

I'm trying to store the email confirmation code in the database. I'm assuming the code is to be store in the Tokens table.

The call to UserManager.GenerateEmailConfirmationTokenAsync doesn't seem to store the code, which lead me to storing it myself via TokenHandleStore.StoreAsync. Is that right? If so, I need to create an instance of Token and it requires the ClientId. Is there a way to access the ClientId and/or Client instance?

If TokenHandleStore.StoreAsync is not the right way, how do I best store the confirmation token?

**Comment by mikeandersun** [comment]
No, the email confirmation tokens are deffrents from the identity tokens. 
Email confirmation sotre in your user managemt database.

**Comment by henninga** [comment]
Yeah, I've mistaken how the confirmation code works. It seems to generate it from the timestamp in the aspnet identity implementation. The code is not random and is regenerated on the fly when I verify the email code.
