### ISSUE TITLE
Thinktecture.IdentityServer.Core

### ISSUE THREAD

**Issue by HornerGrahame** [IdentityServer/IdentityServer3#1221]
It would be great if the Thinktecture.IdentityServer.Core was .net core framework based allowing the service to run without the full desktop framework.  This would also allow other platforms to make use of the IdentityServer give the .net core framework is the minimal contract for the dnx runtime.

**Comment by leastprivilege** [comment]
Will happen at some point - but has not a really high priority right now.

CoreClr is not released yet - and CoreClr on non-Windows is even further out.

**Comment by frapontillo** [comment]
Any updates on this?

**Comment by brockallen** [comment]
Not right now, no. We'll report back when we do.

**Comment by frapontillo** [comment]
@brockallen thank you!
