### ISSUE TITLE
IUserService:IsActiveAsync

### ISSUE THREAD

**Issue by brewhutch** [IdentityServer/IdentityServer3#1222]
Hi,
I'm following the code written by tjrobinson [here](https://gist.github.com/tjrobinson/0ad6c790e90d7a385eb1) to authenticate the user against AD. The problem I'm facing is when **IsActiveAsync()** gets called, the **ClaimsPrincipal** parameter does not have the value of **Name** property. It's always null.

Here is a screenshot: 
https://www.dropbox.com/s/3g43kb7y280lzdv/IsActiveAsync.JPG?dl=0

Please advise.

Thanks,
Brew

**Comment by leastprivilege** [comment]
..and what's in the claims collection?

**Comment by brewhutch** [comment]
I have **Name** and **Email**. They are added by GetProfileDataAsync(). With GetProfileDataAsync(), I can see the value of **Name** property from the subject parameter.

![image](https://cloud.githubusercontent.com/assets/9948289/7233158/a5efca0c-e74d-11e4-9f12-eba4bc205a74.png)


```
        public Task<IEnumerable<System.Security.Claims.Claim>> GetProfileDataAsync(System.Security.Claims.ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
        {
            using (var pc = new PrincipalContext(ContextType.Domain, DOMAIN))
            {
                using (var user = UserPrincipal.FindByIdentity(pc, IdentityType.SamAccountName, subject.Identity.Name))
                {
                    if (user != null)
                    {
                        var identity = new ClaimsIdentity();
                        identity.AddClaims(new[]
                        {
                            new Claim(Constants.ClaimTypes.Name, user.DisplayName),
                            new Claim(Constants.ClaimTypes.Email, user.EmailAddress)
                        });

                        if (requestedClaimTypes != null)
                            return Task.FromResult(identity.Claims.Where(x => requestedClaimTypes.Contains(x.Type)));

                        return Task.FromResult(identity.Claims);
                    }
                }
                return Task.FromResult<IEnumerable<Claim>>(null);
            }
        }
```

**Comment by brockallen** [comment]
Depending on the flow and how IdSvr is being used, you may or may not get back all the claims you returns from the user service authenticate methods. Can you describe the flow being used with the client app?

**Comment by brewhutch** [comment]
Hi Brockallen,

Everything I'm using comes from the Samples project.

**Client app:** IdentityServer3.Samples/source/Clients/ConsoleResourceOwnerClient

**Id server:** IdentityServer3.Samples/source/SelfHost (Minimal)

Brew

**Comment by brewhutch** [comment]
Hi Brockallen,

Any update on this?

Thanks,
Brew

**Comment by brockallen** [comment]
The resource owner password flow client sample is only asking for read and write scopes. You need to ask for more scopes (identity scopes) and then use the access token to get the claims via the user profile endpoint.

**Comment by brewhutch** [comment]
Hi Brockallen,

I added **IncludeAllClaimsForUser = true** to the scope and got all claims. 
Thank you for your advise. I love IdentityServer!

Brew
