### ISSUE TITLE
Login message when email is not confirmed

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1223]
Hi

This is a bit off topic from idserver, but related to security practices.

When logging in and the email is not confirmed, I've got it set up so it shows an error message that says that the email is not confirmed. 

I know that one should not show detailed messages when either username or password is wrong. Typical message would be "Either email or password is incorrect". What do you guys suggest I show when the email is not confirmed?

Since they both have the correct email and password combination, my thinking is that it isn't to bad to show the "Email is not confirmed" message, or am I wrong?

**Comment by brockallen** [comment]
It's up to you. Some people say that not showing details error messages will prevent an attacker from gleaning info about your user database, but they can also get that information from timing attacks. So I've been moving more and more to the "it's ok, show the user some details" opinion.

**Comment by henninga** [comment]
Thats my thinking as well, especially in this case since they've provided correct email and password.

Thank you
