### ISSUE TITLE
CustomGranValidator for External Login

### ISSUE THREAD

**Issue by dandresini** [IdentityServer/IdentityServer3#1224]
I Dominick,
in my project I used Identity Server v3 + Membership Reboot. I split Identity Server and User Registration in two web application. 
In  User Manager project (end User) I used Angular JS, and I created a function to  get a local access token, after validate social token request.
In identity Server I had configured a CustomGrantValidator where I passed the access token and the provider  from the User project, so I can "verify external access token", get the user and create the local access token for angularjs call.

 I inserted in Client class a new Dictionary property where I loaded the social app information (ex. for facebook: app_id, app_token), so I can verify if app of social that i use in User web application is the same  of the client id Identity Server associated. What do you think?

**Comment by leastprivilege** [comment]
OK?!

**Comment by dandresini** [comment]
https://usertravel.azurewebsites.net/
I use "external login" with my site. Then OWIN return me the "social access token" and i validated it with a call of follow url:

https://www.googleapis.com/oauth2/v1/tokeninfo?access_token={0} (Google)
https://graph.facebook.com/v2.2/debug_token?input_token={0}&access_token={1} (Facebook)
https://api.twitter.com/1.1/account/verify_credentials.json (Twitter)

If the app_id is the same of the "user client site" I call My Identity Server (https://idserver3.azurewebsites.net/idstravel/) with a  CustomGrantValidation call and I pass external access_token and provider.
In CustomGrant Validate Async Method I validate the "external access_token" with the social information stored in client class and if there's no problem i send local token.

this is my work. So I can configure multiple social app_id information and use external login in multiple site of my Group with the same client_id.

**Comment by brockallen** [comment]
Can we close this, or is there still a question?

**Comment by dandresini** [comment]
Yes, i continue to work in it
