### ISSUE TITLE
[Question] Azure AD Login Not Working

### ISSUE THREAD

**Issue by tameyer1** [IdentityServer/IdentityServer3#1225]
I have been having an issue trying to get a sample working with Azure AD as an external id provider.
I took the current MVC Authentication sample from the repository and help docs and simply tried to add in ad as an external provider.  The issue I get is when I click the Azure AD button from the sample app login screen, I am taken to the MS login.  I choose an ID I have setup in AD with access to the app and login.  Each time I am redirected back to the root of my sample app (https://localhost:44319). And that is where it stops. There are no logged exceptions or other information to indicate what the issue is.  Code wise I used the exact MVC Auth sample and after the Google auth options I added options for AD based on sample.  Google and the AD are setup in the external id providers code block.  Local logon is setup in the main Configuration method in Startup.  (The code is straight from the MVC sample). Below is how I have the AD piece defined.
     var aad = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "aad",
                Caption = "Azure AD",
                SignInAsAuthenticationType = signInAsType,
                Authority = "https://login.microsoftonline.com/<<GUID>>",
                ClientId = "<<GUID>>",
                RedirectUri = "https://localhost:44319"
             };
            app.UseOpenIdConnectAuthentication(aad);
When I am redirected back to the above Uri, I see 2 OpenIdConnect cookies (nonce.OpenIdConnect and nonce.aad) in the Request cookies.  The Logon with local userid\password and Google logon both work fine.  

Any hints on what I might have setup wrong or how to debug?  Thanks for you help.

**Comment by brockallen** [comment]
Try getting it work work in a stand-alone app, then once that works integrate it with IdSvr.

**Comment by tameyer1** [comment]
I tried it with https://github.com/AzureADSamples/WebApp-OpenIDConnect-DotNet 
Going to the same AD it works. This sample uses openid owin middleware to connect. I can try to add idsvr to that sample and see what happens.

**Comment by brockallen** [comment]
Any update?
