### ISSUE TITLE
Skip idSrv login page while using User Service

### ISSUE THREAD

**Issue by juhankki** [IdentityServer/IdentityServer3#1226]
Hi,

We are using Identity Server to pass tokens from external IP (ADFS) to clients. Since it's the only authentication method, there's no need for idSrv's login page where you can only choose ADFS and local login (not in use). I found out that by defining "EnableLocalLogin = false" in client's settings, we can skip the page.

However, now when I'm trying to implement User Service to intercept logins, check them against another DB and attach extra claims to token, it won't work anymore. Web browser goes to weird redirect loop (idSrv-ADFS) and following warning is logged:
[Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeInteractionResponseGenerator]: 20/04/2015 18:47:33 +00:00 -- User is logged in with local idp, but local logins not enabled.

**Comment by loctanvo** [comment]
Have you tried to set the `idp` in the initial authentication request? [More in the docs.](http://identityserver.github.io/Documentation/docs/endpoints/authorization.html)

**Comment by juhankki** [comment]
Thanks! That got me on right track. With that and by specifying identity provider on UserService's AuthenticateExternalAsync's AuthenticateResult it started working.

After that I found a possible bug  (maybe in Internet Explorer, since it's working fine with Chrome and Firefox) concerning fragments in return_url, but I'll open another issue about that one.
