### ISSUE TITLE
Any exmample of CustomViewService using Razor?

### ISSUE THREAD

**Issue by senseicz** [IdentityServer/IdentityServer3#1227]
Hi, 

I was wondering whether an example where Razor views are used as part of CustomViewService is available?

Also, would you please elaborate a bit on why Angular is being used with default views? Can I remove it, given I find another way of adding AntiForgeryToken to my views?

Thank you very much in advance, 

Antonin

**Comment by brockallen** [comment]
Search the archives -- this has already been discussed. Also someone had a sample or an approach to using razor.
