### ISSUE TITLE
IsActive on logout

### ISSUE THREAD

**Issue by johnkors** [IdentityServer/IdentityServer3#1231]
As part of a user deleting his/hers own account, we would like to logout the user and redirect to a sorry-you're-no-longer-a-user-page.

I tried the following:
* delete the user while the user is logged in
* then call the endsession endpoint with the ```id_token_hint``` and a valid ```post_logout_redirect_uri```

**Result** 
Seeing as the user no longer exists, the validation of the ```id_token_hint``` fails  and hence no redirect will be honored (due to a call to ```IsActive``` within the token validation). Obviously, we do need a user check in our ```IsActive``` implementation for other scenarios, so we cannot change that mechanism. I'm guessing there there is a good reason why we would want to check if the user is active when logging out, so is there any other viable option to achieve this? 

At the logout scenario, at least for us, we don't really care if the user is active or not.

**Comment by huysentruitw** [comment]
Maybe you can mark the account for removal, and remove it later?

**Comment by johnkors** [comment]
Yeah, thought about that, but I don't want the user to be able to login directly after, so any flag would have to be used in IsActive anyhow. Would prefer to avoid adding more state (and another worker to fix it).

Not using Membershipreboot.

**Comment by huysentruitw** [comment]
Keep track of the user in a `List` or `Dictionary` and remove it once you get in `SignOutAsync`?

**Comment by johnkors** [comment]
Still more state. Also, that does not play well in our environments (load balanced in azure) :)

**Comment by johnkors** [comment]
Update: We solved it by not involving the ```post_logout_redirect_uri```. Do the redirect first, then do client logout and idsrv endsession with js at the "sorry-you're-no-longer-a-user-page".
