### ISSUE TITLE
Is there a way to configure one instance of IdentityServer hosted with IIS to handle Mixed Mode authentication.  Windows & Form

### ISSUE THREAD

**Issue by kkfrosty** [IdentityServer/IdentityServer3#1232]
This is a question. 
I've been following an issue asking how to create a mixed mode environment with both Windows and forms authentication.

Until that is answered, we need the ability to do this.  The angle we're going after is creating an .aspx page that users get directed to.  We set IIS permissions to Windows only on this page and code behind determines if the user is authenticated properly.

If so we pull the windows user name.  Our app in this situation will have a matching username in our SLUser table or an association.  We pull back the user name and password hash encrypted.

At this point we need to simulate what happens with IdentityServer and UseOpenIdConnectAuthentication.  A call to Identity server that would ideally trigger the code in AuthorizationCodeReceived.  However, if that's not possible, just a way to authenticate the user in code, and then build build ClaimsIdentity so existing code which uses  HttpContext.GetOwinContext() will obtain a proper reference the ClaimsIdentity.

**Comment by loctanvo** [comment]
Not sure I entirely understand your scenario. Do you want to achieve both Windows Authentication and the centralized solution ("the OpenID Connect"-way)? Maybe you already have seen that, but further down [this discussion](https://github.com/IdentityServer/IdentityServer3/issues/1157), @leastprivilege is linking to a Windows Authentication solution [he open sourced last week](https://github.com/IdentityServer/WindowsAuthentication). Maybe that could help.

**Comment by kkfrosty** [comment]
Thanks loc,
I've never been able to get the referenced project in that link to work in our environment and started a different direction.
We have a retail application.  Some people run it from our hosted server yet some of our larger customers require the application run in their existing Windows environment.  They ask us to integrate so users in their AD don't have to type in a user name and password.
Obviously our db has our own custom user table with security objects, permissions and roles.  In this situation we mate a users windows username with a username in database.
In these cases we have a flag we set and a user tries to open our MVC application, first we see if they were authenticated via IIS using windows.  Currently we have an aspx page in which we set to allow only windows authentication which a user is directed to.  If they are authenticated, we extract the windows username and do a look up to our user table.  If we find a mated user account, then we use plan to use that account and password hash to authenticate via Identity Server which we have built a custom UserService to authenticate users.

The problem with what you linked we end up wasting too much time trying to figure out somebody elses code.  
At this point we have our Identity User credentials.  We're trying to figure out in code how to authenticate the user via Identity Server and then have it trigger AuthorizationCodeRecieved which we have defined in the Notifications property of UseOpenIdConnectAuthentication.

If not, I'm trying to figure out the endpoint on Identity Server we can call and pass username password hash.  We have figured out we can use UserManager CreateIdentityAsync to generate a ClaimsIdentity.  We then just need to populate all the claims as they get populated in AuthorizationCodeRecieved.

Here is UseOpenIdConnectAuthentication code I keep referring too.  THe AuthorizationCodeRecieved gets fired when a user enters credentials on the IdentityServers Login page.

app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
                {
                    //SmartLogixMainIdentityClientSecret
                    ClientId = ConfigurationManager.AppSettings["SLMainIdentityClientId"],
                    Authority = ConfigurationManager.AppSettings["IdentityAuthorityUrl"],
                    RedirectUri = ConfigurationManager.AppSettings["SLMainRedirectUri"],
                    PostLogoutRedirectUri = ConfigurationManager.AppSettings["SLMainPostLogoutRedirectUri"],
                    
                    //RedirectUri = "http://localhost/SLMain/",
                    //PostLogoutRedirectUri = "http://localhost/SLMain/",
                    ResponseType = ConfigurationManager.AppSettings["SLMainIdentityResponseType"],
                    Scope = ConfigurationManager.AppSettings["SLMainIdentityScopes"],

                    SignInAsAuthenticationType = "Cookies",

                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        AuthorizationCodeReceived = async n =>
                        {
                            // filter "protocol" claims
                            var _claims = new List<Claim>(from c in n.AuthenticationTicket.Identity.Claims
                                                          where c.Type != "iss" &&
                                                                c.Type != "aud" &&
                                                                c.Type != "nbf" &&
                                                                c.Type != "exp" &&
                                                                c.Type != "iat" &&
                                                                c.Type != "nonce" &&
                                                                c.Type != "c_hash" &&
                                                                c.Type != "at_hash"
                                                          select c);

                            // get userinfo data
                            var userInfoClient = new UserInfoClient(
                                new Uri(ConfigurationManager.AppSettings["IdentityUserInfoEndpoint"]),
                                n.ProtocolMessage.AccessToken);

                            //var userInfoClient = new UserInfoClient(
                            //    new Uri("https://localhost/IdentityApis/core/connect/userinfo"),
                            //    n.ProtocolMessage.AccessToken);

                            
                            var userInfo = await userInfoClient.GetAsync();
                            userInfo.Claims.ToList().ForEach(ui => _claims.Add(new Claim(ui.Item1, ui.Item2)));

                            // get access and refresh token
                            var tokenClient = new OAuth2Client(
                                new Uri(ConfigurationManager.AppSettings["IdentityTokenEndpoint"]),
                                //new Uri("https://localhost/IdentityApis/core/connect/token"),
                                ConfigurationManager.AppSettings["SLMainIdentityClientId"],
                                ConfigurationManager.AppSettings["SLMainIdentityClientSecret"]
                                );

                            var response = await tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);

                            _claims.Add(new Claim("access_token", response.AccessToken));
                            _claims.Add(new Claim("expires_at", DateTime.Now.AddSeconds(response.ExpiresIn).ToLocalTime().ToString()));
                            _claims.Add(new Claim("refresh_token", response.RefreshToken));
                            _claims.Add(new Claim("id_token", n.ProtocolMessage.IdToken));

                            n.AuthenticationTicket = new AuthenticationTicket(
                                new ClaimsIdentity(_claims.Distinct(new ClaimComparer()), 
                                    n.AuthenticationTicket.Identity.AuthenticationType), 
                                    n.AuthenticationTicket.Properties);

                            // After authentication, we need to get the SLAppUser.  
                            // Not sure if we should cache this in Session.
                            // Populate the Sid claimtype.  That will be the users UniqueId.
                            // We will have to figure out something 


                            // kkf Populate User 
                       //     var _authentication = HttpContext.Current.GetOwinContext().Authentication;

                            //var _userManager = HttpContext.Current.GetOwinContext().GetUserManager<SLAppUserManager>();

                            //// probably in the 
                            //var _user = _userManager.FindByIdAsync(_claims.First(f => f.Type == ClaimTypes.Sid).Value);
            
                        },

                        RedirectToIdentityProvider = async n =>
                        {
                            // if signing out, add the id_token_hint
                            if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                            {
                                var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
                                n.ProtocolMessage.IdTokenHint = idTokenHint;
                            }
                        },

                        
                    }

**Comment by brockallen** [comment]
You might want to look into this: https://github.com/IdentityServer/WindowsAuthentication

**Comment by kkfrosty** [comment]
Thanks Brock,

Loc already directed me to this.  With no documentation, I’ve tried to add it to our Identity Server and get everything to compile.

However, the questions I have is how does this allow mixed mode?  The goal if for users when they visit our app internally, if their AD accounts are mated, then they get authenticated in code.  Then if they come in over the internet or for customers who don’t have AD accounts, they would then see the Identity Login screen.

Users can’t be directed to a login page and have to click Windows Login or anything like that.

**Comment by brockallen** [comment]
Oh sorry -- missed that. It gets configured an an external IdP from IdSvr's perspective (using WS-Fed).

**Comment by kkfrosty** [comment]
We took the IdentityServer download and we’ve configured it to be hosted in IIS.

I added the WindowsAuthentication project to the solution and a reference to it from our IdentityServer web project.  (We renamed the project IdentityApis.  This is the web app we use to host identity server.)

Our startup.cs configuration is added to the bottom.

Based on your last email, I added Thinktecture WSFederation assembly to our IdentityApis web project.

That automatically adds the Thinktecture.IdentityServer3 dll which then causes approx. 160 ambiguous compiler errors because of the Core project.  

So I deleted Thinktecture.IdentityServer3 reference however, no the project doesn’t compile because problems such as the WsFederationServiceFactory expecting IdentityServerServiceFactory being defined Thinktecture.IdentityServer3.

I’m thinking I’m going to have to find the WS-Federation project, download it and add it to our solution and then add a reference in it to the Core project?

Having said that, I still have seen nothing as to yet as to after spending an entire day just trying to get code to compile and build and figure out what to do, that what we’re going through would even support mixed mode authentication in the first place.

If we can ever sort through all this, can you take a MVC application, in its Startup.Auth.ConfigureAuth, configure UseOpenIdConnectAuthentication.  

Then when a user opens the application, first IdentityServer will try to use WS-Federation to see if user is authenticated, if so then allow us to utilize the code we wrote for the custom UserService which we wrote for IdentityServer to authenticate the user, their identity and then kick off whatever behind the scenes something would trigger the OpenIdConnectAuthenticationNotifications AuthorizationCodeReceived Func back on the UI MVC site.

If they don’t have a valid windows account, then they get directed to the login page as normal.  They enter their credentials and if authenticated, redirected back to the UI MVC, identity is built, Claims are set and AuthenticationTicket instantiated?

 

 

  public class Startup_SLIdentityServer

    {

        public void Configuration(IAppBuilder app)

        {

            LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());

            //LogProvider.SetCurrentLogProvider(new TraceSourceLogProvider());

 

            // uncomment to enable HSTS headers for the host

            // see: https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security

            //app.UseHsts();

 

            bool _enableIdentityLogging = bool.Parse(ConfigurationManager.AppSettings["EnableIdentityLogging"]);

 

            app.Map("/core", coreApp =>

                {

                    var _factory = InMemoryFactory.Create(

                        users:   Users.Get(),

                        clients: Clients.Get(),

                        scopes:  Scopes.Get());

 

                    var _userService = new LocalUserService();

 

                    _factory.UserService = new Registration<IUserService>(resolver => _userService);

 

                    var _localClaimsProvider = new LocalClaimsProvider(_userService);

 

                    _factory.ClaimsProvider = new Registration<Core.Services.IClaimsProvider>(resolver => _localClaimsProvider);

 

                    _factory.CustomGrantValidator = 

                        new Registration<ICustomGrantValidator>(typeof(CustomGrantValidator));

 

                    _factory.ConfigureClientStoreCache();

                    _factory.ConfigureScopeStoreCache();

                    _factory.ConfigureUserServiceCache();

 

                    var idsrvOptions = new IdentityServerOptions

                    {

                        IssuerUri = ConfigurationManager.AppSettings["IdentityIssuerUri"],

                        SiteName = ConfigurationManager.AppSettings["IdentitySiteName"],

                        Factory = _factory,

                        SigningCertificate = Cert.Load(),

 

                        CorsPolicy = CorsPolicy.AllowAll,

 

                        AuthenticationOptions = new AuthenticationOptions 

                        {

                            IdentityProviders = ConfigureIdentityProviders,

                        },

 

                        LoggingOptions = new LoggingOptions

                        {

                            //EnableHttpLogging = true, 

                            //EnableWebApiDiagnostics = true,

                            //IncludeSensitiveDataInLogs = true

                        },

 

                        EventsOptions = new EventsOptions

                        {

                            RaiseFailureEvents = true,

                            RaiseInformationEvents = true,

                            RaiseSuccessEvents = true,

                            RaiseErrorEvents = true

                        }

                    };

 

                    coreApp.UseIdentityServer(idsrvOptions);

                });

 

            app.Map("/Admin",  adminApp =>

            {

 

            });

 

            app.UseWindowsAuthenticationService(new WindowsAuthenticationOptions

                {

                    IdpRealm = "urn:idp",

                    IdpReplyUrl = "https://localhost/core/was",

                    SigningCertificate = Cert.Load()

                });

        }

private void ConfigureWSFederation(IAppBuilder app, IdentityServerOptions options)

        {

            var _factory = new WsFederationServiceFactory(options.Factory);

 

            // data sources for in-memory services

            _factory.Register(new Registration<IEnumerable<RelyingParty>>(RelyingParties.Get()));

            _factory.RelyingPartyService = new Registration<IRelyingPartyService>(typeof(SLWindowsRelyingPartyService));

 

            var wsFedOptions = new WsFederationPluginOptions

            {

                IdentityServerOptions = options,

                Factory = _factory

            };

 

            app.UseWsFederationPlugin(wsFedOptions);

 

 

        }

 

        public static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)

        {

 

            var adfs = new WsFederationAuthenticationOptions

            {

                AuthenticationType = "adfs",

                Caption = "ADFS",

                SignInAsAuthenticationType = signInAsType,

                MetadataAddress = "https://adfs.leastprivilege.vm/federationmetadata/2007-06/federationmetadata.xml",

                Wtrealm = "urn:idsrv3"

            };

}

**Comment by kkfrosty** [comment]
Since there is no documentation, I'm going to post my endeavours here for others.  Note, our Identity setup, we downloaded, Thinktecture.IdentityServer3-Master.  We renamed the Host project, IdentityApis.  We are using IIS to host.  

Back to the problem, if you add the Ws-Federation module via Nuget you'll have all types of namespace problems with the Core project because of the ThinktectureServer3 assembly.  If you remove that reference, Ws-Federation is hard coded to use namespaces in ThinktectureServer3 assembly.  So we had to uninstall the Nuget package.  I downloaded the Ws-Federation project and added it to our solution.

However, when you add a reference to it, the WSFederationController has a conflict with Cores WelcomeController.

At this point we're still waiting for an answer as to whether or not it's even possibly to add Ws Federation to the Master solution and have it operate in parallel with Core.  If we ignore the welcomecontroller conflict and try to add the provider anyway, then we see an exception for multiple controllers with the same route.  (We see this by opening http://localhost/core in a browser.)

**Comment by kkfrosty** [comment]
PS.  I changed the title of this question as I think we're going down a rabbit hole with this.  We are going a different way which should be easier and I'm going to separate those questions out into a new question

**Comment by leastprivilege** [comment]
Short answer is no. 

You can link to a Windows external authN provider - but no mixed mode.

**Comment by kkfrosty** [comment]
Thank you Dominick, I thought as much.   You saved me a ton of time chasing this anymore.

We have another way of going about this which I'm typing up in another question.  Thanks again!

**Comment by lenniebriscoe** [comment]
Has this now changed with IdentityServer4 ? Its a fairly common Enterprise requirement to have one website where both internal company users can access without supplying credentials (authenticated via Windows AD) as well as external users who are required to supply them (passing around JWTs)

**Comment by leastprivilege** [comment]
yes

**Comment by lenniebriscoe** [comment]
That's good news! Any pointers on where to start with this and how it could be achieved? Any examples?
