### ISSUE TITLE
EnableLocalLogin Authentication Option not honored

### ISSUE THREAD

**Issue by gavinharriss** [IdentityServer/IdentityServer3#1233]
The EnableLocalLogin option described under http://identityserver.github.io/Documentation/docs/configuration/authenticationOptions.html does not seem to be honored. The local username and password area is still displayed on the login screen when set to false.

**Comment by loctanvo** [comment]
Is this issue related to [this](https://github.com/IdentityServer/IdentityServer3/issues/1226)?

**Comment by gavinharriss** [comment]
I don't think it's related. The login page seems to be skipped if I only have one external login provider configured. I have Google and Facebook configured now so I see the login screen again.

I do have a assets/_layout.html present to override the standard layout, just in case this could cause some DOM path to the elements to hide to become invalid (clutching at straws).

**Comment by johnkors** [comment]
It might be that this option is more of a "ShowLoginPage" than "EnableUsernamePassword" authentication. The tests does not say anything about not rendering the credentials inputs at least.

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Tests/UnitTests/Endpoints/AuthenticationControllerTests.cs#L295

**Comment by huysentruitw** [comment]
This option is working for me in with IdentityServer3 1.4.2

**Comment by brockallen** [comment]
If you've customized the view, then you need to honor the model data rendered into the view that says to not show username/password fields. Look at the samples -- they are honoring the flag in the angular code.

**Comment by johnkors** [comment]
Ah, it's hidden via js depending on the value of the loginUrl property. ```ng-show="model.loginUrl"```. 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/DefaultViewService/PageAssets/login.html#L15

**Comment by brockallen** [comment]
Yes, I call that a "RESTful UI" :)

**Comment by gavinharriss** [comment]
My humble apologies! I was using a project from IdentityServer3.Samples as my foundation and it turns out that it pulls down an out-of-date version of IdentityServer3 from NuGet. Once I pulled down the latest versions of the packages from NuGet everything works as it should.

I'm most sorry about that - rookie mistake I guess. It's great to see the level of support you guys give though - very much appreciated!
