### ISSUE TITLE
Set IdentityToken lifetime to 30 days

### ISSUE THREAD

**Issue by sandeepgaikwad** [IdentityServer/IdentityServer3#1235]
I want my identity token to last for 30 days,i.e. Once logged-in to Identity server, I do not wish to login for next 30 days. I believe this is possible.
I tried following configurations.
In DB: for the client set identitytokeLifetime = 2592000; AccessTokenLifeTime=2592000.
In IdentityServer: 
                   CookieOptions = new Thinktecture.IdentityServer.Core.Configuration.CookieOptions
                        {
                            SlidingExpiration=false,
                            ExpireTimeSpan=System.TimeSpan.FromDays(30),
                            IsPersistent=true
                        },
In Client App: 
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                ExpireTimeSpan=TimeSpan..FromDays(30),
                SlidingExpiration = false,
            });
Also "UseTokenLifetime" is set to false at the client app.

With this configuration, what I am expecting is even if I close my browser instance, my cookie will persists and I'll not be required to log in again (even after I restart my PC).
But in actual, this is not happening, as soon as I close my browser instance, my cookie is expired and I have re-login.
Cookies and site data in chrome shows *Expires: When the browsing session ends*
for .AspNet.Cookies, ASP.NET_SessionId,idsrv, idsrv.xsrf, idsvr.session
And this is reason I have re-login as soon as I restart my browser instances.

Ho can I make my cookies to persists even after browser session ends and machine restarts?
I believe this should be pretty easy to achieve.
Am I missing some configuration?

**Comment by johnkors** [comment]
* The id_token is only used to set a Principal (and create a cookie at the client), so with your setup it means you have 30 days to set a principal/cookie in your client.
* UseTokenLifetime = false means "don't set the client cookie lifetime the same as the lifetime of the id_token. 

If you're talking about persistent cookies at idsrv and not at your client, the ```IsPersistent``` property on the Cookieoptions should be it for it to be *available* for the user to decide thru the ```Remember me``` checkbox. 

If you're talking about at your client using the ms cookie middleware along with the oidc mw, you need to set some properties using the notifications api.

For example:
```
SecurityTokenValidated = async n =>
   {
      n.AuthenticationTicket.Properties.IsPersistent = true;
   }
````

**Comment by sandeepgaikwad** [comment]
Got it!
Thanks
