### ISSUE TITLE
Frozen logout

### ISSUE THREAD

**Issue by webbkvalite** [IdentityServer/IdentityServer3#1236]
Inside our Thinktecture server (server 1) we offer an external provider which is also a Thinktecture Server (server 2). Sometimes when a user wants to log out from the external provider via server 1, the process freezes. Trace logging shows no errors or warnings. Any ideas of what this could be or suggestions on where to begin to look?

**Comment by webbkvalite** [comment]
One warning that comes when it doesn't freeze is:
"CORS request made for path: /logout from origin: https://www.inloggning.net but rejected because invalid CORS path"
The setup is that the two Identityservers are installed on the same IIS and domain but with two different virtual paths, they have the same root directory, so this warning appears when https://www.inloggning.net/identity (where 'identity' is the virtual path) wants to logout the external provider at https://www.inloggning.net/siths (where 'siths' is the virtual path)

**Comment by brockallen** [comment]
Is this initiated from a JS client app?

**Comment by brockallen** [comment]
Any update?

**Comment by webbkvalite** [comment]
No, it's not from a JS app. 
I built away the problem by joining the two Identityservers now.
One possible anomaly was that the nonce-cookies for both servers were saved on the root-path and not their virtual paths, all other cookies were saved on the virtual paths.
A complicating factor is that the external provider had a "require client certificate" setting on the IIS on the "/login" -path, which triggers client/server interaction that cannot always be handled during server/server calls.

Since logs don't show anything, there are no timeouts or other errors and the freezing behavior is sporadic, I thought that the best way to proceed is to change the setup to something simpler, hence this workaround solution.

**Comment by brockallen** [comment]
Ok, can we close this then?
