### ISSUE TITLE
Fix max-age param in HSTS header

### ISSUE THREAD

**Issue by lukethenuke** [IdentityServer/IdentityServer3#1238]
According to https://tools.ietf.org/html/rfc6797#section-6.1 the Strict-Transport-Security header should have the format of "Strict-Transport-Security: max-age=123456". 

The current HSTS middleware uses "Strict-Transport-Security: max-age: 123456" (notice the : instead of = after max-age).

It should be an easy fix by changing the ":" to "=" in source/Core/Configuration/AppBuilderExtensions/UseHstsExtension.cs (45; 90). But I'm going not to incase I'm wrong :)

**Comment by brockallen** [comment]
Possibly. We've had people using it and they did not raise this as an issue.

**Comment by tajy** [comment]
Yes, it should be "=" instead of ":"

**Comment by brockallen** [comment]
Thanks for the bump. Fixed on dev.
