### ISSUE TITLE
Error 400: Bad Request - Request Too Long

### ISSUE THREAD

**Issue by sickboy** [IdentityServer/IdentityServer3#1239]
The above occurs for some users when logging in over certain systems or browsers, but not all.
Would you have some pointers to find the culprit? Thanks

**Comment by brockallen** [comment]
Check the logs and find out which request is triggering it.

**Comment by loctanvo** [comment]
@sickboy I would check whether it's due to url too long, or due to cookie header size too long. Could it be related to [this](https://github.com/IdentityServer/IdentityServer3/issues/1124)?

**Comment by brockallen** [comment]
Any update?

**Comment by sickboy** [comment]
We've applied the two workarounds mentioned in the other ticket.
After clearing cookies the problem seems to have subsided for now..
Will keep monitoring.
