### ISSUE TITLE
URL fragments are not coming when using IE, Custom User Service and when more than one scope is requested

### ISSUE THREAD

**Issue by juhankki** [IdentityServer/IdentityServer3#1240]
Hi,

I noticed that with following combination URL fragments (tokens..) are not coming after idSrv redirects to redirect_url:
- there's multiple scopes requested (more than one)
- there's custom UserService
- browser is Internet Explorer 11 (haven't tried other versions)

If I change any of those it starts working again. With those it seems to behave just like with response_mode=form_post even when I explicitly specify response_mode=fragment. This could be a bug within IE since I can't see nothing wrong with the responses Identity Server is returning (with Fiddler)

**Comment by leastprivilege** [comment]
Not exactly sure what "are not coming" means - but maybe you are hitting IE's length restriction -

https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string
