### ISSUE TITLE
Are there any client samples when using Xamarin or Xamarin.Forms?

### ISSUE THREAD

**Issue by schmitty1970** [IdentityServer/IdentityServer3#1241]
I am using Xamarin.Forms for an iOS and Android application.  Following the WPF client samples and some posts on how to use Xamarin.Auth with Xamarin.Forms, I have gotten it working on Android.  However, on iOS seems to authenticate, but then the following page does not load and I get a Frame Load error.  I know this is not really a IdentityServer3 issue, as it seems like a Xamarin.Auth issue.  It would be great to have a Xamarin.iOS and Android example (maybe not using Xamarin.Auth) to work from.  Are there any out there that you know of?  Or, have you done any or plan on doing any?
Thanks

**Comment by brockallen** [comment]
Sorry, we don't have any Xamarin samples. If you get a working sample, we'll link to it from our docs.

**Comment by schmitty1970** [comment]
No problem.  I am going to start working on one today for Xamarin.Forms.  I'll let you know when it is done.

**Comment by brockallen** [comment]
Feel free to link them here if/when you have some. I'll close this for now.
