### ISSUE TITLE
Session refreshing (OpenId Connect Session Management)

### ISSUE THREAD

**Issue by securityCurious** [IdentityServer/IdentityServer3#1242]
The authorize endpoint ignores the id_token_hint parameter. I guess that session refreshing (see: http://openid.net/specs/openid-connect-session-1_0.html#RPiframe) is not currently supported in Identity Server:

"When refreshing the session the RP would send an Authentication Request with the prompt=none parameter and an id_token_hint that contains the current id_token. The OpenID Connect RP may then issue a new id_token and return it to the RP in an Authentication Response"

Any plan on getting this feature implemented?
Thanks

**Comment by brockallen** [comment]
IdSvr implements the check session endpoint. The RP frame would be in your client application. We have a sample that shows how to do this, but it stops short at making another prompt=none request.
