### ISSUE TITLE
Difference between using ValidationMode.Local or ValidationMode.ValidationEndpoint?

### ISSUE THREAD

**Issue by danielbsig** [IdentityServer/IdentityServer3#1243]
Hi,

I tried configuring my Web API to use ValidationMode.Local, which meant I also specified the IssuerName and IssuerCertificate properties when creating the IdentityServerBearerTokenAuthenticationOptions object in app.UseIdentityServerBearerTokenAuthentication(). However, this meant that I didn't get the "sub" property in the JWT. Is this by design, or am I missing something in my configuration?

Regards,
Daníel

**Comment by leastprivilege** [comment]
You can also use local with Authority - which means you don't need to set the other config manually.

Regardless - this should not influence what type of claims you get back.

**Comment by danielbsig** [comment]
I would still have to provide the certificate, right?

**Comment by leastprivilege** [comment]
No. It is all coming from metadata.

**Comment by danielbsig** [comment]
Ok thanks. Are there any downsides to using local validation?

**Comment by leastprivilege** [comment]
well - local is local. The validation endpoint allows revoking tokens before expiration.

**Comment by danielbsig** [comment]
For some reason I'm still having this problem. The code I'm using to access the claims looks like this (called from within an ApiController derived class):

	var principal = User as ClaimsPrincipal;
	var userName = principal.Claims.Where(c => c.Type == "sub").Select(c => c.Value).FirstOrDefault();

Is there anything obviously wrong with this?

**Comment by johnkors** [comment]
What claims are there, are there any at all? You are marking your action/controller with an auth attr or using a global filter?

**Comment by danielbsig** [comment]
Yes, and the code works if I *don't* use the Local option. I'm using a global filter.

**Comment by johnkors** [comment]
And you've set the Authority of  ```IdentityServerBearerTokenAuthenticationOptions``` to what?

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/blob/master/source/AccessTokenValidation/IdentityServerAccessTokenValidationAppBuilderExtensions.cs#L67

**Comment by danielbsig** [comment]
Authority      = "https://s1.dev.xxxxxx.is/idsrv/core"

(Parts of the url changed, and it is an internal server anyway). As I said, the only thing I change is to set ValidationMode to ValidationMode.Local, and then suddenly the "sub" claim isn't accessible.

**Comment by johnkors** [comment]
By that, you mean you actually have other claims, just not the sub claim? Sounds strange..

**Comment by danielbsig** [comment]
Well, I must admit that I didn't check the other claims. No, apparently I'm not getting any claims at all.

**Comment by johnkors** [comment]
That sounds more reasonable :) Try not setting the ```TokenValidationParameters```. For local mode, I believe Authority is enough.

Also, try to remove the default claim types mapping by doing this: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/SampleAspNetWebApi/Startup.cs#L15

**Comment by danielbsig** [comment]
Ah much better! The line:

JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

did the trick (I wasn't messing with the TokenValidationParameter property at all).

Thanks!

**Comment by Davidsual** [comment]
@leastprivilege  "well - local is local. The validation endpoint allows revoking tokens before expiration."

As far I can see JWT token cannot be stored at all... and even if you try to override TokeService and store it you cannot revoke, because the endpoint use a random key for GetAsync / RemoveAsync and there is not way to override.

IMO I think it would be good to have the possibility to revoke JWT token and not just reference token.
There are plenty of scenario where server side I want to revoke immediately JWT token.

Thanks for you great work,

Davide
