### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by peske** [IdentityServer/IdentityServer3#1247]
Great work guyz, and great product, but very poor documentation. Although I'm deep in .NET (from 2002 and v1.0), and although I've spent some time in looking examples and reading your minimal documentation, I still can't catch-up, and I still don't know some basic things. For example I don't have a clue how to register new client - is there any interface for this purpose embedded in IdentityServer3 itself, how to access it, how to customize it, etc.
But I don't want just to criticize - I'm willing to help. I'm willing to start working on a documentation if you want me to step in, and if you are able to spend some minimal time in explaining things to me so that I can put that in comprehensive documentation. And don't worry - although you may think otherwise right now, I'm fast-catching guy. No developer likes to work on a documentation, so me neither, but sadly I'm good in that :), and I want to have deep understanding about a project before implementing it.
Keep in touch...

**Comment by johnkors** [comment]
What you are looking for is your own implementation of ```ClientStore```

How clients are defined:
http://identityserver.github.io/Documentation/docs/configuration/clients.html

What is extendable in identityserver3:
http://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html

How to register extensions:
http://identityserver.github.io/Documentation/docs/advanced/customServices.html

If you still feel something is missing, PRs are welcome at the documentation repo.
https://github.com/IdentityServer/Documentation
