### ISSUE TITLE
Reading forms does currently not work in the client validators

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#1248]
which breaks form body and client cert credentials

**Comment by tofutim** [comment]
How tough does this look to resolve? Anything I can do to help? Do you have a Test that you are working against?

**Comment by leastprivilege** [comment]
fixed

**Comment by tofutim** [comment]
Cool. Do you have some samples on how to implement the client certificates?

**Comment by leastprivilege** [comment]
The dev branch of the samples has a client cert client in the clients solution.

**Comment by tofutim** [comment]
I see the sample called 'Console Client Certificate Client' and the SampleAspNetWebApi. How do you have this set up in VS so that you run the client and the web app for testing?

**Comment by tofutim** [comment]
Hmm, I just have a timing issue I guess, I tried to use multiple project startup.
