### ISSUE TITLE
Startup.cs

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1249]
Hi guys

We have an MVC project loosely modelled after the one of your samples. When debugging the project, I notice that code in Startup class runs on every request, doing app.Map() every time. That surely isn't right, but I have no clue as to why it is happening. And sure enough, when I point the same IIS site to one of the sample projects, CustomUserService in this case, it only runs that same code once.

I've gone through the packages, site properties and tried to make them as similar as I could, but to no help.

Any idea what might be causing this behavior?

Thanks a lot

**Comment by johnkors** [comment]
OWIN middleware is run for every request, so this is normal behaviour.

Read more about it here: http://www.asp.net/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline
