### ISSUE TITLE
Access token validated after expired

### ISSUE THREAD

**Issue by spinlud** [IdentityServer/IdentityServer3#1251]
Hi, i have implemented an identityserver (v3) and a web api project that uses identiyserver token validation. I want to use refresh tokens to call identityserver token endpoint when access token has expired and it's time to get a new one and a new refresh token. I am using the hybrid flow.

For testing purpose i set the access token lifetime to 15 seconds in the client configuration of the identityserver, so i expect that if i call the api with the access token after 15 seconds i should get an error from the api, but this does not happen, the middleware validates the token also after it has been expired. What am i missing?

here is the client:

                new Client 
                {
                    Enabled = true,
                    ClientId = "mvc",
                    ClientName = "GenericClientApp",
                    ClientSecrets = new List<ClientSecret> {new   ClientSecret("secret".Sha256())},
                    Flow = Flows.Hybrid, 
                    RequireConsent = true,
                    
                    RedirectUris = new List<string>
                    {
                        IdentityConstants.ClientUri
                    },

                    
                    PostLogoutRedirectUris = new List<string>
                    {
                        IdentityConstants.PostLogoutUri
                    },   

                    AccessTokenLifetime = 15

                }

Here is the startup class for the web api project:

public class Startup
{
        public void Configuration(IAppBuilder app)
        {
            // plug in access token validation
             app.UseIdentityServerBearerTokenAuthentication(new             IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = IdentityConstants.IdSrv,
                RequiredScopes = new[] { "webapiscope" }
            });

            app.UseResourceAuthorization(new AuthorizationManager());
            
            app.UseWebApi(WebApiConfig.Register(new HttpConfiguration()));
        }
    }

I am using this nu-get package for token validation: Thinktecture.IdentityServer3.AccessTokenValidation

Thanks in advance for any help

**Comment by loctanvo** [comment]
Normally, the validation libraries (at least the MS one) compensate for clock skew. IIRC, 5 mins. So testing with lifetime less than 5 mins doesn't really give the effect you're looking for.

**Comment by spinlud** [comment]
Thanks for the answer. So i guess i have to assign a lifetime greater than 300 seconds at least? What are suitable values for the lifetime parameter?

**Comment by brockallen** [comment]
Lifetime of an access token depends on your security architecture.

**Comment by leastprivilege** [comment]
The JWT security token handler allows for 5 min clock skew - so what @loctanvo said ;)
