### ISSUE TITLE
Let exceptions bubble to the client

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1252]
Hi

Is it possible to let exceptions bubble up to the client. I've had several errors today that only says to the effect of "something went wrong" when logging in. I know there is logging, but when running in our test environment I think it would be beneficial to display the exception message without having to set up logging in Test.

This would of course not be displayed in production.

**Comment by leastprivilege** [comment]
No. The "visible" error will always be vague for security reasons.

You need to enable logging.

**Comment by henninga** [comment]
Ok, I will do that then :)
