### ISSUE TITLE
Best practice claims vs column data

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1253]
Hi

A bit off topic.

We need to store additional data about the user, such as name, company, organization number, preferred language, etc.
How do you guys suggest we store that data, in the users table as columns or as claim, and why? 

That data obviously needs to be sent out as claims to all our client apps, and storing it as claims makes things a bit easier.

**Comment by loctanvo** [comment]
Not completely sure what you mean by "claims or columns". Do you consider serializing the claims into one column? 

I would treat data as data, and claims are just a representation of the data. What happens the day you need another presentation of the data, eg. a user profile page or a REST api accessing the data? So, i would use columns, if i have to answer without knowing your needs.

**Comment by brockallen** [comment]
This is off topic. Perhaps ask in the issue tracker for the identity management library you're using?
