### ISSUE TITLE
1.x Changelog?

### ISSUE THREAD

**Issue by CrescentFresh** [IdentityServer/IdentityServer3#1256]
I am seeing new versions pushed up to nuget (1.4.x, now 1.5), great job! However RELEASES.md is no longer getting any updates since 1.3.

I haven't been following the issue tracker to know what has been going into each release. The closest I could find is a filter: https://github.com/IdentityServer/IdentityServer3/issues?utf8=%E2%9C%93&q=milestone%3A1.4

**Comment by brockallen** [comment]
We've not yet got our tooling sorted out for the releases.md, but we do our best to track them here: https://github.com/IdentityServer/IdentityServer3/releases

**Comment by CrescentFresh** [comment]
There it is!
