### ISSUE TITLE
Links from Excel or MSword are unauthorised

### ISSUE THREAD

**Issue by tsladev001** [IdentityServer/IdentityServer3#1257]
Hi,
I have very peculiar issue. I have made default browser as Chrome(issues with all browser). I have authenticated my application and my actions are authorized. Now I open one link which is present in MS word/MSExcel as below

https://localhost/MyApp/Employee/Requisition?id=1

The above URL will execute Edit action in my mvc controller. Whenver link is opened in MSword/excel, user is getting it as unauthenticated and 
giving page error for No sign cookie found.  

If I paste this link on browser, it is working fine. Even clicking link on outlook is working fine. 
Can you please help me with this issue?

Thanks

**Comment by brockallen** [comment]
From your web app when the user is unauthorized you need to trigger SSO. Perhaps I'm missing something?

**Comment by brockallen** [comment]
Any update or can I close this?
