### ISSUE TITLE
Is embedding access token in url a good practice?

### ISSUE THREAD

**Issue by martinknafve** [IdentityServer/IdentityServer3#1259]
I'm new to IdentityServer and OpenId Connect so please excuse my ignorance. I'm trying out the IdentityServer3 samples, the following combination specifically:

- SelfHost (Minimal)
- SampleAspNetWebApi
- JavaScript Implit Client - Simple

I follow these steps:

1) I click Get Token in the HTML/JavaScript client
2) I log on the identity server, using the user bob
3) I'm redirected back to the HTML/JavaScript client

Now, in the address field in my web browser the access_token is embedded. I know our security auditors don't like seeing sensitive data embedded in urls, because request urls will end up in server logs which may be accessible to parties which aren't fully trusted (for example if we ship data to Loggly for analysis).

First of all I wonder if I've misunderstood this. If not, how is this generally handled? Is it seen as a non-issue since access tokens are only valid for a short period of time? Or do people configure their web servers to filter out the access tokens prior to logging them?

**Comment by loctanvo** [comment]
The access token is in the URL after a # tag (fragment). These values will not be sent to the server, and will therefore not appear in the web server logs.

**Comment by martinknafve** [comment]
That makes perfect sense. I've did not consider that the content after the # was not sent to the server. Thanks!
