### ISSUE TITLE
SignInMessage from PreAuthenticate not used for Login view signin value

### ISSUE THREAD

**Issue by theit8514** [IdentityServer/IdentityServer3#1260]
I am investigating making a multi-tenant login portal for the dashboard I am working on. After looking at many samples, the CustomHRD sample seems to be like what I most want the IdentityServer to do, namely:

1. Client gets sent to IS3, no 'company' detected. Sent to 'company' select screen.
2. Client inputs company (stored as company cookie) and sent back to IS3. IS3 PreAuthenticateAsync checks for the cookie and sets message.Tenant.
3. Client logs in on Login page.
4. AuthenticateLocalAsync checks for message.Tenant and checks to see if the user exists on that Tenant.

The only problem with this is that message.Tenant in AuthenticateLocalAsync is null. I have checked that PreAuthenticateAsync is setting the correct Tenant in the message prior to returning "null".

I believe the problem lies in these two areas:
https://github.com/IdentityServer/IdentityServer3/blob/ad0e4689951f3b52302a3386917ebf8e0940fc7a/source/Core/Endpoints/AuthenticationController.cs#L115-L149

In Login, the message is translated from the signin input value. PreAuthenticateAsync is called with the message (object). Later, we send both the message (object) and message (string) to RenderLoginPage. If PreAuthenticateAsync has changed message (object), then message (object) and message (string) differ.

https://github.com/IdentityServer/IdentityServer3/blob/ad0e4689951f3b52302a3386917ebf8e0940fc7a/source/Core/Endpoints/AuthenticationController.cs#L808

When the signin value is written to the page, it is the string value only. The object value is not used whatsoever.

For repro, update the CustomHRD sample code to have this in the UserService:
````c#
        public override Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
        {
            if (string.IsNullOrWhiteSpace(message.Tenant))// message.Tenant is always null here.
            {
                return Task.FromResult<AuthenticateResult>(null);
            }

            Console.WriteLine(message.Tenant);
            return Task.FromResult<AuthenticateResult>(null);
        }

        public override Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message)
        {
            var idp = context.Request.Cookies["idp"];
            if (String.IsNullOrWhiteSpace(idp))
            {
                // no idp, so redirect
                var url = new Claim("url", context.Request.Uri.AbsoluteUri);
                var result = new AuthenticateResult("~/hrd", "hrd", "hrd", new Claim[] { url });
                return Task.FromResult(result);
            }
            else
            {
                // we have idp, so set it
                context.Response.Cookies.Append("idp", ".", new CookieOptions { Expires = DateTime.UtcNow.AddYears(-1) });
                message.Tenant = idp;
                return Task.FromResult<AuthenticateResult>(null);
            }
        }
````

**Comment by theit8514** [comment]
So a brief update after some digging into the Katana project source code. I have learned that the OpenIdConnectMessage from the client contains a AcrValues property which can be set in the RedirectToIdentityProvider notification on the OpenIdConnectAuthenticationOptions. I am still working on having it use cookies to determine if a Tenant needs to be set and redirect the client to a portal to enter said Tenant, but that's neither here nor there. I originally believed that the IdentityServer was in charge of defining the tenant, not the source application.

I will continue to investigate setting the Tenant from the source application, and if that is the recommended solution for doing so then I believe this issue can be closed.

**Comment by leastprivilege** [comment]
Yes - the client can use acr_values to send more data to idsrv. On that we natively understand is tenant. So you can use that.
