### ISSUE TITLE
ASP.net Identity VS IdentityServer3

### ISSUE THREAD

**Issue by jawadatgithub** [IdentityServer/IdentityServer3#1261]
Hopefully this is not apple to orange comparison.
 
I understand that ASP.net Identity is Identity Management Library that can be used side by side with IdentityServer3 (Identity Provider), but since ASP.net Identity is owin middleware, it can be selfhosted and act as provider/server as explained [here](http://bitoftech.net/2014/06/01/token-based-authentication-asp-net-web-api-2-owin-asp-net-identity/) _**EDIT:** OAuthAuthorizationServerProvider (katana middleware) being used to act as STS_. so please kick me in right direction to understand the differences:

1. why asp.net Identity not listed under [OpenIDConnect Libraries](http://openid.net/developers/libraries/)?
2. Is [IdentityModel Embedded STS](https://github.com/IdentityModel/Thinktecture.IdentityModel) equivalent to Asp.Net Identity?
3. Currently I assume the main reason Thinktecture developed its own Identity Management in IdentityServer3 because at that time Asp.Net Identity was not available/released yet, Is that correct?
4. if I don't have any project built with Asp.net Identity, is there any added value to use it with IdentityServer3?
5. if asp.net identity selfhosted on sub domain and used as provider, what advantages/features I lose compared with IdentityServer3?

**Edit2:** after more reading, I found Asp.net identity got nothing to do with OAuth2 or OpenIDConnect! (really surprise me if this is true!), currently I understand that OAuth2 and OpenIDConnect supported through Owin Middlewares and Asp.net Identiy can integrate with it. please confirm if this is correct?
 

thanks,

**Comment by leastprivilege** [comment]
well - it is ;)

ASP.NET Identity is an abstraction over your user storage - a database API so to speak. Not a protocol.

1. see above
2. no - it is a test WS-Federation IdP
3. we didn't - you can plug in your own idm library - e.g. asp.net identity
4. see above
5. see above

**Comment by jawadatgithub** [comment]
thanks alot,

so now its important to clarify for IdentityServer3 community the limitations of using approaches used by http://bitoftech.net/ , http://typecastexception.com/ and some codeproject articles: in brief many articles explain how to use WebApi, asp.net identity and OAuthAuthorizationServerProvider (Microsoft.Owin.Security.OAuth) to make STS. also I found [github project](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server) which extend OAuthAuthorizationServerProvider to support OpenIDConnect! its really messy/weird that MS left OpenIdConnectServerProvider out of Microsoft.Owin.Security namespace!

at first glance most people keen to the idea of using what's being provided in house (in this context by MS), but in the STS area: I think IdentityServer3 is clear Winner as it integrate the whole OIDC and OAUTH2 specs under one package/product.

I will try to sum up the limitations, but for time-being, I hope active contributors highlight some bits.

thanks again,

**Comment by jawadatgithub** [comment]
Based on the above discussion, allow me to list FAQ (Frequently Asked Questions) that should help understanding the Importance and value of IdentityServer3 to provide cutting edge security solution for REST, WebAPI, SPA and modern applications in general:

#### Q1. As of April 2015, What is the current Standard Security Framework/protocol to secure (Authenticate & Authorize) REST, WebAPI, SPA and any HTTP service in general?

**A.** [OAuth2](http://tools.ietf.org/html/rfc6749) and [OpenID Connect](http://openid.net/specs/openid-connect-core-1_0.html) standards designed to enable a third-party application to verify the identity of the End-User (Authentication) AND to obtain limited access (Authorization) to an HTTP service.

#### Q2. Why its Important to use the authorization server (STS, OP, IDP...) pattern right from the start?

**A.** Adding the concept of an authorization server to your web APIs is the recommended architecture for managing authentication and authorization ([source](http://leastprivilege.com/2014/03/24/the-web-api-v2-oauth2-authorization-server-middlewareis-it-worth-it/)). In modern Apps, targeting single platform is rare, what happens today is that developer starts with one platform then scale up to multiple platforms (mobile native apps, Smart TV app, Tablets..). so using coupled/embedded security solution is kind of obsolete approach and not recommended anymore in most cases. so its recommended to use centralized OAuth2 & OIDC STS to maintain single store of users, scopes, claims and clients information among all Apps regardless of the platform.

#### Q3. to be continued soon..

**Comment by jawadatgithub** [comment]
this issue will be closed after 48 hours if no further comments, corrections or inputs received on the above [FAQ](https://github.com/IdentityServer/IdentityServer3/issues/1261#issuecomment-96405276).

I hope its useful.

**Comment by AntiStupidity** [comment]
I think you should read more before rushing and writing FAQ. Your FAQ is missed up and indicates how confused you are. I suggest you start with a good read of Identity and Access Management for Dummies. 

Cheers.

**Comment by jawadatgithub** [comment]
Your input represent NULL added value, so its rendered useless. You are welcome to try harder.
