### ISSUE TITLE
IdentityServer for social sing sign on

### ISSUE THREAD

**Issue by apryiomka** [IdentityServer/IdentityServer3#1262]
Hello there, I am trying to figure out how to use Identity server for single sign on for social logins. The idea is that I have multiple web apps that use the same Facebook account for authorization that will be pointing to the Identity Server URL, but the web apps are running under different domains. So, I want to redirect users to the Identity Server to log in with Facebook credentials and then redirect back to the web app. I looked through the samples, I see that some of them have social networks authentication options, but I just don't see any use of them anywhere. I am bit new to the IdentityServer, I mostly used asp.net identity for my projects, but I just cannot figure out how to make it to work with social logins .

The work flow will look like Webb App -> Identity Server -> facebook -> Identity server -> web app.

Thanks,
Alex.

**Comment by loctanvo** [comment]
When you configure external providers (FB, Google etc.), these login options are displayed in the Login page. Just configure your FB app, find a server sample having FB configured, change out the key/secret and try to run a sample against that server.
