### ISSUE TITLE
Read OpenIdConnect.AuthenticationProperties from AuthenticateExternalAsync

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer3#1265]
Is there a way to read back the `OpenIdConnect.AuthenticationProperties` from the `IUserService.AuthenticateExternalAsync` method? 

I would like to get the `RedirectUri` that was passed to the `Challenge` method by the client:

```C#
var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
context.HttpContext.GetOwinContext().Set(Constants.OwinKeys.AcrValues, "idp:" + LoginProvider);
context.HttpContext.GetOwinContext().Authentication.Challenge(properties, "OpenIdConnect");
```

**Comment by leastprivilege** [comment]
those properties are encoded into the state parameter by the MW. The format is a private implementation detail of the MW in question. 

So I guess the answer is no.

**Comment by huysentruitw** [comment]
Ok, that was expected :) Thanks for your answer.
