### ISSUE TITLE
Implementing OpenID Connect Authorization Code Flow in Client Side using AngularJS

### ISSUE THREAD

**Issue by kasunkv** [IdentityServer/IdentityServer3#1266]
I've been assigned to a project where it uses IdentityServer v2 for Authentication. I have to migrate the project from IdentityServer v2 to IdentityServer v3 and implement a mechanism to get a refresh token to when authenticating to get a new access_token when the existing one expires. But this has to be done in the Client Side using AngularJS. The project uses AngularJs and ASP.net as the backend. Can the Authorization Code Flow implemented using AngularJS in the client side without any security issues ? or do i have to use the backend for this. I've been researching this for weeks now but have no answer for this.

**Comment by leastprivilege** [comment]
Technically you can do that. Code flow was never designed for being used by JS - and the usual security implications apply.

The use of implicit flow with long lived reference tokens seems to be the more appropriate approach for most situations like this.

**Comment by kasunkv** [comment]
I tried to do this using AngularJS by using oauth-ng library for Angular by modifying it slightly. I can successfully get the authorization_code and the session_state but when i send the code to the token endpoint with grant_type='authorization_code' and the redirect_url using $http.post() i get a HTTP 400 bad request error. I added the headers for handling CORS in to the web.config file (I'm using the WebHost minimal project as my Authorization Server)

**Comment by leastprivilege** [comment]
IdentityServer has its own CORS handling - check the docs.

**Comment by kasunkv** [comment]
I will go through the docs fully. But meanwhile, this is the code i'm using for the authentication in the LoginController.

```
angular.module('oidc3')
    .controller('LoginController', function ($scope, $http, $timeout, $location) {
  
    var getParamsFromUrl = function(url) {
        var splitted = url.split('?');
        splitted = splitted[1].split('&');
        var params = {};

        for (var i = 0; i < splitted.length; i++) {
            var param  = splitted[i].split('=');
            var key    = param[0];
            var value  = param[1];
            params[key] = value
        }
        return params;
    };

    var getToken = function (url, data) {
        return $http.post(url, data);
    };



    if($location.absUrl().split('?')[1]) {
        $scope.params = getParamsFromUrl($location.absUrl());

        var tokenData = {};
        tokenData.grant_type = 'authorization_code';
        tokenData.code = $scope.params.code;
        tokenData.redirect_uri = 'http://localhost:8000/login.html';

        var tokenEndpoint = 'https://localhost:44333/connect/token';

        getToken(tokenEndpoint, tokenData)
            .success(function (data, status, headers, config) {
                console.log(data);
                console.log(status);
                console.log(headers);
                console.log(config);
            }).error(function (data, status, headers, config) {
                console.log(data);
                console.log(status);
                console.log(headers);
                console.log(config);
            });
    }
});
```
I removed the CORS headers i added. But now it gets a 405 Method Not Allowed error. But with the headers added i got a response with an error ` invalid_client `. can you just give me a hint what i am doing wrong here?

**Comment by leastprivilege** [comment]
turn on logging. that will help.

**Comment by kasunkv** [comment]
Thanks Dominick, I'll try looking at the logs.
