### ISSUE TITLE
idsrv in secure area behind MQ (WebSphere) - how to authorize from public area?

### ISSUE THREAD

**Issue by MadBullfrog** [IdentityServer/IdentityServer3#1268]
Hi!

My current setup includes two areas public and secure (not connected to internet), both with websites and services. The only way to communicate between the two is MQ (WebSphere). I want to do a centralized auth. Can I put idsrv in secure area and somehow forward auth requests through MQ or should I put two idsrv instances and get them in sync on db level or whatever? 

Thank you!
Alexey Merson.

**Comment by leastprivilege** [comment]
IdSrv implements OAuth2 and OpenID Connect - they specify direct HTTP calls to the various endpoints.

If your infrastructure allows that - idsrv is good for you.
