### ISSUE TITLE
implementation of our own user database with identity server3

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1269]
Hi, 

My company has asked me to use our own user database with think tecture identity server3 to authenticate users. Could please give me some examples or samples to proceed on that. 

Thanks,
Dhanaraj

**Comment by brockallen** [comment]
Please read the docs.

**Comment by dhanutpk** [comment]
I don't want to use AspNet identity and membership Reboot. We have users, roles data with additional few more table. I have to authenticate user by using these table.

**Comment by brockallen** [comment]
That's fine. You'll still have to read the docs.

**Comment by huysentruitw** [comment]
And that brings us to 2 great examples of how to implement `IUserService`:
* [`MembershipRebootUserService`](https://github.com/IdentityServer/IdentityServer3.MembershipReboot/blob/master/source/MembershipRebootUserService/MembershipRebootUserService.cs)
* [`AspNetIdentityUserService`](https://github.com/IdentityServer/IdentityServer3.AspNetIdentity/blob/master/source/AspNetIdentityUserService/AspNetIdentityUserService.cs)

**Comment by dhanutpk** [comment]
I got you. Now i am implementing IUserService interface but problem here is when i create user from db code first approach. i am getting error, claims doesn't have key. Since claims are part of user.  Please help on the same.

**Comment by leastprivilege** [comment]
That would be an Entity Framework question - the IUserService interface is not bound to any database technology.

Closing.
