### ISSUE TITLE
Getting an error while loading new registration view

### ISSUE THREAD

**Issue by spatel2** [IdentityServer/IdentityServer3#1270]
Hi,

I want to configure identity server to display additional links. I am adding a new link "Register" on login page by adding following code.

            app.Map("/identity", idsrvApp =>
            {
                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    EnableWelcomePage = true,

                    AuthenticationOptions = new AuthenticationOptions
                    {
                        //IdentityProviders = ConfigureAdditionalIdentityProviders,
                        LoginPageLinks = new LoginPageLink[] { 
                            new LoginPageLink{
                                Text = "Register",
                                //Href = "~/localregistration"
                                Href = "LocalRegistration",
                            },
                        }
                    },
                });

Controller:

public class LocalRegistrationController : Controller
    {
        [Route("identity/LocalRegistration")]
        [HttpGet]
        public ActionResult Index(string signin)
        {
            return View();
        }

        [Route("identity/LocalRegistration")]
        [HttpPost]
        public ActionResult Index(string signin, LocalRegistrationModel model)
        {
            if (ModelState.IsValid)
            {
                //TODO: Consider user is created in the database.
                return Redirect("~/identity/" + Constants.RoutePaths.Login + "?signin=" + signin);
            }

            return View();
        }
    }

Routing attributes are also registered.

public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

            //following is needed to register route attributes of LocalRegistrationController
            routes.MapMvcAttributeRoutes();
            
            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new {controller = "Home", action = "Index", id = UrlParameter.Optional}
                );
        }

I am not sure why i am getting following error, when I click Register link.

Application exception.ToString(): System.Web.HttpException (0x80004005): This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.
   at System.Web.HttpRequest.EnsureFiles()
   at System.Web.HttpRequest.get_Files()
   at System.Web.HttpRequestWrapper.get_Files()
   at System.Web.Mvc.HttpFileCollectionValueProvider.GetHttpPostedFileDictionary(ControllerContext controllerContext)
   at System.Web.Mvc.HttpFileCollectionValueProvider..ctor(ControllerContext controllerContext)
   at System.Web.Mvc.HttpFileCollectionValueProviderFactory.GetValueProvider(ControllerContext controllerContext)
   at System.Web.Mvc.ValueProviderFactoryCollection.GetValueProvider(ControllerContext controllerContext)
   at System.Web.Mvc.ControllerBase.get_ValueProvider()

![image](https://cloud.githubusercontent.com/assets/11442178/7354872/342bd6dc-ecec-11e4-91ad-ab89aad217b4.png)

Thanks,
Sandeep

**Comment by spatel2** [comment]
I changed the registration url to following and it worked.

LoginPageLinks = new LoginPageLink[] { 
                            new LoginPageLink{
                                Text = "Register",
                                Href = "~/localregistration",
                                //Href = "LocalRegistration",
                            },

**Comment by RemotecUK** [comment]
I also had this problem and stopped it from happening by setting `EnableHttpLogging = false` in the `LoggingOptions` class. I also tried your suggestion but sadly that did not work for me. Seems to be something to do with trying to log the html stream after something else has been invoked.
