### ISSUE TITLE
ie8 support

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/IdentityServer3#1271]
hi guys,

As much as I hate to I have to support IE8 at least a little longer.  I get an error on line 254 of scripts.js

    document.getElementById("modelJson").textContent

this is of course IE8 doesn't support textContent.  I'm trying to insert a shiv using 

````
                var viewOptions = new DefaultViewServiceOptions();
                viewOptions.Scripts.Insert(0, "/Content/scripts/ieshiv.js");
                viewOptions.CacheViews = false;
                factory.ConfigureDefaultViewService(viewOptions);
````

this script get's put on the page, but it's getting written after scripts.js.  So I have 2 questions

1) can/will you support IE8 as it is still a supported browser (not for much longer I agree) and 
2) is there a way to have my custom script written first without customizing every screen?

**Comment by stevenfirstrowinc** [comment]
I should specify I'm using version 1.3

**Comment by johnkors** [comment]
There's an unmerged PR for this (#1218), but if you don't want to wait you may override any single view out of the ones given in IViewService and keep the rest as is (default). http://identityserver.github.io/Documentation/docs/advanced/customizingViews.html

**Comment by johnkors** [comment]
2) 

>In addition to being able to replace the partial views, it's also possible to replace the default layout template itself. This can be done by creating a file named _layout.html in the assets folder. The DefaultViewService will then use whatever combination of custom layout or partial views discovered on the file system to merge with the default embedded assets to render the requested view.

**Comment by stevenfirstrowinc** [comment]
I did end up going the custom layout view thank you.  I don't know why my search for IE8 didn't show the PR or I would not have opened a ticket.  I shall watch for the merge.
