### ISSUE TITLE
Quick Question on Client Configuration

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1272]
What is the usage of SlidingRefreshTokenLifetime. I see a field which RefreshTokenExpiration which specifies what type of expiration time should be used.  

What is the use of this sliding token life time.

**Comment by leastprivilege** [comment]
Well - it is exactly what it says. Sliding expiratio (up to an upper time limit) of the refresh token.

**Comment by skatukojwala** [comment]
Thank you for the clarification.
