### ISSUE TITLE
How to do signing certificate roll over?

### ISSUE THREAD

**Issue by mrkvincze** [IdentityServer/IdentityServer3#1273]
I am planning to deploy IdentityServer3 on multiple machines under IIS and use it with the client credentials flow with ValidationMode = Local from ASP.NET, also from multiple machines.
Is there a way to do a rollover of the signing certificates without having any downtime?

There are multiple problems:

- If we update the certificate only on a portion of the servers, the whole system will be in an inconsistent state, acceptance of tokens will depend on whether the load balancer sends the request to a token server with the old or the new certificate. So it seems that update of the certs should happen at the same time on all the servers.
- The "client" servers have to be restarted in order to pick up the new public key from the token servers. Until they are restarted they won't accept any tokens from the updated token server. This should be done ideally immediately to avoid downtime.

I'm sure other people have already had this problem, so it'd be great if you could point me to some documentation or guidelines about this issue.

**Comment by abhayachauhan** [comment]
Have you had a look at the documentation for Discovery?

http://identityserver.github.io/Documentation/docs/endpoints/discovery.html

Allows you to get the public key from an endpoint. There is also a secondary certificates property which I haven't looked into yet.

**Comment by leastprivilege** [comment]
When using Local - the metadata document is retrieved once a day.

The metadata doc can hold 2 keys - primary and secondary and the middleware will load and use both when present (JWTs have a key identifier that allows picking the right one).

When you start to rollover - set both keys and at some point swap primary and secondary.

**Comment by mrkvincze** [comment]
Thanks guys, that seems to be what we're after.
What does happen when the secured applications still only know about cert A, but the token serve already has cert A as primary and cert B as secondary certificates? Will it sign the tokens with both, and the secured app will know to use cert A?
And when all the apps updated their metadata and know about both certs, they can be swapped on the token server, and the secondary cert can be removed?

**Comment by leastprivilege** [comment]
Tokens are always signed with the primary cert. The middleware refreshed metadata once a day.

**Comment by mrkvincze** [comment]
Oh I see but the client can use either the primary or the secondary to verify, depending on when it has updated its metadata.
Cool, thanks for the info!
