### ISSUE TITLE
Making a request to the token endpoint does not seem to return the claims requested from the originating Authorisation request

### ISSUE THREAD

**Issue by Nysosis** [IdentityServer/IdentityServer3#1274]
I can't quite figure out why it's working this way,

If I've added all the standard scopes to my identity server scopes, then requested an authorisation token with `scope=openid profile email`, and then request an id_token from the token endpoint with my code, the profile and email claims are not returned, looking through the code, it seems to be down to the ScopeClaim.AlwaysIncludeInIdToken being false on all the ScopeClaims on the standard scopes.

Should I be expected to change those to false? Or is it something I'm missing?

**Comment by johnkors** [comment]
Are you asking for both an id_token and an access_token, or just an id_token?

**Comment by Nysosis** [comment]
Asking for an id_token:

https://localhost:44319/identity/connect/token?grant_type=authorization_code&code=[code]&redirect_uri=[redirect_uri]

**Comment by leastprivilege** [comment]
This is not how the token endpoint works - check the docs.

**Comment by Nysosis** [comment]
Ahh, sorry, my bad! I've been reading through the OIDC specs for the last 2 days and got brain frazzled, as it's referred to as the Token endpoint in the spec, but it's the /userinfo endpoint in identity server think I got a mixed up.

Cheers for setting me back on track!
