### ISSUE TITLE
multi client web api 

### ISSUE THREAD

**Issue by jack-en** [IdentityServer/IdentityServer3#1275]
Hi 
I'm coding an web service(Web Api OWIN) that has multi-client like android,ios and js clients. It will also have external logins like facebook. I'm trying to use IdentityServer3 I wrote CustomGrant for facebook, but I was confused about client secret,  should I give it to client (android,ios,js) to call ouath server, they say use implicit flow for front end but its open IdentityServer 3 login page. Is there any way to login oauth server via username , pasword and clientId via server request.

Should I write a webservice method that wraps IS3, method will keep client secret  and take username and password or fb token as a parameter and returns back access_token for outh . Is it valid way ?

**Comment by johnkors** [comment]
Resource Owner Flow. http://tools.ietf.org/html/rfc6749#section-1.3.3

**Comment by jack-en** [comment]
Should I give client secret to mobile client or js client ?

**Comment by johnkors** [comment]
Well, if you give it to a js client, I guess it wouldn't qualify as a secret anymore, right?

**Comment by jack-en** [comment]
Yes right, that is why I'm asking. But resource owner looks like need client secret , I am unable to make a request without it.

**Comment by jawadatgithub** [comment]
1. Although Implicit flow require redirectUri, it should be known that Google, Facebook, MS, Twitter, StackOverflow, GitHub, Yahoo...all follow the redirectUri concept. the main idea is any client (like web browser, native app) can't be trusted in Internet zone. in other words, if the SPA deployed in Intranet zone (on premise where all clients and users well known) (trusted environment) then its possible to honor seamless login experience over security. but since Intranet is pretty fast its still recommended to use Implicit flow for sake of consistency (would you like to make different branch of your code base if later on, same SPA need to be deployed over internet?!)

2. if you don't like the default login page, docs and samples provide all what you need to customize it.

3. maybe [this](https://gist.github.com/jawadatgithub/638c11f08ecc0d76b05c) will help clarify use-cases, pros and cons of flow types.

**Comment by jack-en** [comment]
Thank you for your answer. It's good way to protect user credential, very sensible, but I'm confused about their(facebook,twitter etc.) native apps' login screen, are they use Implicit flow on their native apps. In the documents  'access_token is short life and using refresh_token is not allowed'  is written  but native apps don't ask your password again when you logged in once.

**Comment by leastprivilege** [comment]
All clients that need to communicate with the token endpoint need a client secret - that is just a decision we made. 

Just don't treat it as a secret in your situation.

**Comment by leastprivilege** [comment]
to expand on that - 

my above comment applied to your custom grant approach. If you want to do Facebook etc login via IdentityServer - then use implicit flow.

**Comment by jawadatgithub** [comment]
Allow me to share my understanding of this issue:

>I'm confused about their(facebook,twitter etc.) native apps' login screen, are they use Implicit flow on their native apps. In the documents 'access_token is short life and using refresh_token is not allowed' is written but native apps don't ask your password again when you logged in once.

- To support long lived tokens in Implicit Flow, you have two solutions/options:
  * Keep obtaining new ones through [TokenManager JS helper library](https://github.com/IdentityModel/oidc-token-manager) that can keep renewing tokens from an iframe. (its also used in related samples). This option might not be the best choice if client not JavaScript (e.g., if native iOS app not using embedded web browser). 
  * As explained in [this issue](https://github.com/IdentityServer/IdentityServer3/issues/765) use long lived reference tokens.

I don't know which option is better: usually I see @brockallen highlight TokenManager option and @leastprivilege highlight reference token option.

Let me sum up the features of reference token as explained by brock & Dominick:

Reference tokens are just "pointers" to the token data, which is held in IdentityServer3 itself. The API would then contact IdentityServer3 to de-reference the contents behind the token. In short, it's an implementation detail of the token itself and it used as a time/space tradeoff (when compared to a JWT for example). another advantage of reference tokens is that you can revoke them centrally. Reference tokens do not need a signing certificate.

finally: in [Best way to have a long lived client](https://github.com/IdentityServer/IdentityServer3/issues/444) @brockallen  provided detailed answer.

- about Facebook, did you [check this](http://identityserver.github.io/Documentation/docs/resources/externalAuthentication.html) part of docs before going  with CustomGrant ?

**Comment by jack-en** [comment]
Yes @jawadatgithub  I checked the link about external auth but I think It is designed for Implicit flow as explained by @leastprivilege , If I choose to going with Implicit flow, I will use it. I'm still thinking about facebook and twitter native app, It doesn't look like implicit flow, how did they achieve login without implicit flow when third party apps are still using implicit follow. They may identify their app via hash key or singing cert. Am I wrong ? By the way, many thanks for long live token resources.

**Comment by jawadatgithub** [comment]
> Note: I just opened facebook app in my iPhone, and received `Session Expired` please log in again message (if you don't believe it I can share screenshot), what I try to say, its not big deal for user to login once a week or month. 

Gmail, Twitter, GitHub, facebook, ..etc. each of them has STS/OP which might be not independent component but embedded. IdentityServer3 have samples to work with local login (not clients, check samples outside clients folder). So I think it make sense to treat in-house app login differently from 3rd party apps login and that's doable in IdentityServer3, though most use cases require STS as 3rd party component, in which the product/app marketed as SaaS.

I hope this insight useful, if you need further details you are welcome.

**Comment by alexgoroshko** [comment]
@jack-en, did you solve your issue? I have the same one. I'm about create web api wrapper around the idsrv as you said above. If you have any new suggestions, let me know.
