### ISSUE TITLE
ADFS Integration

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#1276]
Hi,

I am having a problem with ADFS integration.

Here is my configuration 
                
                SiteName = "Sample IdentityServer",
                SigningCertificate = LoadCertificate(),
                IssuerUri = "https://company.domain.com", // The issue URI is the same as the app url

wsfed config 
var adfs = new WsFederationAuthenticationOptions
            {
                AuthenticationType = "adfs",
                Caption = "ADFS",
                SignInAsAuthenticationType = signInAsType,
                MetadataAddress = "https://adfs.domain.com/federationmetadata/2007-06/federationmetadata.xml",
                Wtrealm = "https://company.domain.com" //same as issueURI
            };

I have added the URI as a replying trust identifier in ADFS.  When I try and connect with external adfs provider it tries to redirect to https://domain.com/adfs/ls and throws a dns error.  Is there something obvious I am missing.

Apologies if this isn't the correct place for asking this questions.

**Comment by jawadatgithub** [comment]
this resolved [issue](https://github.com/IdentityServer/IdentityServer3/issues/893) might be related.

if not check the [43 issues related to ADFS](https://github.com/IdentityServer/IdentityServer3/search?q=ADFS&type=Issues&utf8=%E2%9C%93) as per now.

**Comment by paddyhamilton** [comment]
It transpired my ADFS set up was wrong so nothing to do with the identityserver configuration.
Thanks again.
