### ISSUE TITLE
MVC Authentication

### ISSUE THREAD

**Issue by HornerGrahame** [IdentityServer/IdentityServer3#1277]
I'm building my own MVC Authentication following the sample provided, all builds ok however the /identity/assets/.. return a 404 error in fiddler? I understand these are embedded resources and should be resolved by the thinktecture identity server assembly, but why are these failing? code it be the namespace of my MVC application? what do I need to do to resolve?

any clues would be greate

cheers
Grahame

**Comment by HornerGrahame** [comment]
This there any option to turn on helpful errors from IdentityServer ?

**Comment by jawadatgithub** [comment]
if you are using IIS, then this issue answered many times, do you have below enabled?:

>
RAMMFAR
One last thing, please don't forget to add RAMMFAR to your web.config, otherwise some of our embedded assets will not be loaded correctly by IIS:
`<system.webServer>
  <modules runAllManagedModulesForAllRequests="true" />
</system.webServer>`

**Comment by alokshriram** [comment]
@HornerGrahame Dont know if this is useful, but http://identityserver.github.io/Documentation/docs/configuration/logging.html has some information on how to setup logging with IdentityServer and how to add your own logging for custom classes.
This is a sample from my web.config 

  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="D:\IdentityServer\Trace.log" />
        <remove name="Default" />
      </listeners>
    </trace>
    <sources>
      <source name="Thinktecture.IdentityServer" switchValue="Information, ActivityTracing">
        <listeners>
          <add name="xml" type="System.Diagnostics.XmlWriterTraceListener" initializeData="trace.svclog" />
        </listeners>
      </source>
    </sources>
  </system.diagnostics>

**Comment by HornerGrahame** [comment]
I'm deploying on to an azure web role everything is working on the local IIS 10 but in azure I get issues; working to resolve will keep you updated.
