### ISSUE TITLE
Question: Could I run Identity Server under Http not Https.

### ISSUE THREAD

**Issue by alokshriram** [IdentityServer/IdentityServer3#1278]
I have a weird problem that I trying to reconcile with my use of Identity Server.  

Our environment sits behind a load-balancer which takes in Https requests, decrypts them and passes them on as http and adding a custom header to let the end point know that it was a legitimate request. 

I have identity server set and working with Https, but if I change the url to point to the http and try to get to the discovery end point, I get an ssl is required error.
http://<myhostname>:567/identity/.well-known/openid-configuration 

Is there some config/code that I can change to not require SSL on identity server ?
thanks

**Comment by huysentruitw** [comment]
The option you're looking for is `RequireSsl`. It's in the [documentation](http://identityserver.github.io/Documentation/docs/configuration/identityServerOptions.html)

**Comment by alokshriram** [comment]
@huysentruitw  Yeah just found that in the options .. note to self.. RTFM.  :)
thanks!
