### ISSUE TITLE
assets not loading

### ISSUE THREAD

**Issue by jancorluy** [IdentityServer/IdentityServer3#1279]
When the identityserver redirects to the connect url, the logon page can't load because the css and the script files are missing.

I host the identityserver inside my webapplication (for demo purposes)

**Comment by huysentruitw** [comment]
I think you're missing this in your *Web.config* file:

```xml
<system.webServer>
  <modules runAllManagedModulesForAllRequests="true" />
</system.webServer>
```

**Comment by brockallen** [comment]
Did RAMMFAR work for you?

**Comment by jancorluy** [comment]
sorry I tought I added the RAMMFAR, but I didn't the RAMMFAR indeed resolved this issue.  Thanks for your help guys!
