### ISSUE TITLE
Validating Access Token

### ISSUE THREAD

**Issue by abhayachauhan** [IdentityServer/IdentityServer3#1280]
For a resource to validate a JWT provided by a client, we have two clear options:

1. Specify the Authority property to enable middleware to request thinktecture to validate the access token every request.
2. Install the certificate pub key on each resource so it can perform local validation.

But when watching the NDC thinktecture presentation, a third option was mentioned:

3. Resource to retrieve the pub key from the thinktecture meta data end point and validate locally. It would allow us to cache it as well, and refresh it whenever an invalid token is received.
Does this sound reasonable?

Option 3 is something that would suit us best in our microservices architecture, as it allows the ease of rolling certificates and not heavily relying on thinktecture endpoint to validate.
Is this something that is inbuilt or a library someone has written ?
Or Any samples that could assist me in achieving this?

**Comment by leastprivilege** [comment]
Authority can be used with local as well - then the MW will auto-configure keys etc

**Comment by loctanvo** [comment]
@abhayachauhan Look [here for a sample](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/SampleAspNetWebApi/Startup.cs#L17). Using this middleware, unless specified differently, it'll automatically retrieve the pub key and cache it locally.
