### ISSUE TITLE
IdentityServer 3 strips out the # from AngularJS app URL

### ISSUE THREAD

**Issue by kasunkv** [IdentityServer/IdentityServer3#1281]
I have an AngularJS app that uses UI Router and the URL include a # symbol. Eg. `http://localhost:8081/#/login` I added one such url as the `RedirectUrl` for the Hybrid Flow client. But when i ran the app and after consent screen is accepted the app is redirected to `http://localhost:8081/`  . But the URL i needed to redirect was `http://localhost:8081/#/callback`.

I enabled Logging and looked at the Trace.log and found this entry.
```
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.WelcomeController]: 4/29/2015 10:00:01 AM +00:00 -- Welcome page requested
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.WelcomeController]: 4/29/2015 10:00:01 AM +00:00 -- Rendering welcome page
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]: 4/29/2015 10:00:16 AM +00:00 -- Start authorize request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]: 4/29/2015 10:00:16 AM +00:00 -- Start authorize request protocol validation
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]: 4/29/2015 10:00:16 AM +00:00 -- scope is missing
 {
  "RedirectUri": "http://localhost:8081/",
  "ResponseType": "code id_token token",
  "ResponseMode": "fragment",
  "Flow": "Hybrid",
  "RequestedScopes": "",
  "Raw": {
    "response_type": "code id_token token",
    "client_id": "oidc_hybrid",
    "redirect_uri": "http://localhost:8081/"
  }
}
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]: 4/29/2015 10:00:16 AM +00:00 -- End authorize request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.AuthorizeRedirectResult]: 4/29/2015 10:00:16 AM +00:00 -- Redirecting to: http://localhost:8081/#error=invalid_request
```

But the actual request should have been like this.

```
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.WelcomeController]: 4/29/2015 10:05:52 AM +00:00 -- Welcome page requested
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.WelcomeController]: 4/29/2015 10:05:52 AM +00:00 -- Rendering welcome page
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]: 4/29/2015 10:06:04 AM +00:00 -- Start authorize request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]: 4/29/2015 10:06:04 AM +00:00 -- Start authorize request protocol validation
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]: 4/29/2015 10:06:05 AM +00:00 -- Authorize request validation success
 {
  "RedirectUri": "http://localhost:8081/login",
  "ResponseType": "code id_token token",
  "ResponseMode": "fragment",
  "Flow": "Hybrid",
  "RequestedScopes": "openid profile email offline_access",
  "State": "1430301964797",
  "Nonce": "nonce",
  "Raw": {
    "response_type": "code id_token token",
    "client_id": "oidc_hybrid",
    "redirect_uri": "http://localhost:8081/#/login", // <- Original URL was like http://localhost:8081/login but i want the URL to be like this.
    "scope": "openid profile email offline_access",
    "state": "1430301964797",
    "nonce": "nonce"
  }
}
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeInteractionResponseGenerator]: 4/29/2015 10:06:05 AM +00:00 -- User is not authenticated. Redirecting to login.
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]: 4/29/2015 10:06:05 AM +00:00 -- End authorize request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.LoginResult]: 4/29/2015 10:06:05 AM +00:00 -- Redirecting to login page [...]
```

What seams to be the problem? Is there a way around this? I can not remove the # from the URL, so can't i use the IdentityServer with a URL that includes the #

**Comment by loctanvo** [comment]
It's nothing IdentityServer specific. [Fragments Are not Sent in HTTP Request Messages](https://blog.httpwatch.com/2011/03/01/6-things-you-should-know-about-fragment-urls/).

**Comment by huysentruitw** [comment]
I was thinking the same as @loctanvo. But sending it to IdSrv as a parameter should be possible and IdSrv should also be able to redirect to that URL. The fragment part will not be sent to the server during the redirect, but that is the thing AngularJS takes advantage of.

Can you show us the code that calls the authorize endpoint?

**Comment by huysentruitw** [comment]
I also see that you're missing the `scope`, so you probably convert the redirect URL to HTML entities, otherwise the `#` sign will be replaced by `%23` and the server would not get a truncated request.

After that, you can get into an other problem of having [multiple hash fragments](http://stackoverflow.com/questions/23170495/multiple-parameters-in-url-fragment) in the redirect URL: the AngularJS route and the token you get back). Let us know how IdentityServer handles this :)

**Comment by kasunkv** [comment]
@huysentruitw  The reason why the scope is missing is that the server strips out everything after the # and the scope is defined after the `redirect_url`. I encoded the url with JavaScript 'escape' function and now `#` is replaced by `%23` and the request is successfully processed. Thank you @loctanvo for the material on Fragment URLs and @huysentruitw , thank you for giving the suggestion to encode the URL. :)

**Comment by huysentruitw** [comment]
Small correction: It is not the server that strips the fragment part, it's the user-agent.

**Comment by kasunkv** [comment]
@huysentruitw , Yes :) its a HTTP thing ryt. Found this article via a stackoverflow question i posted.
https://blog.httpwatch.com/2011/03/01/6-things-you-should-know-about-fragment-urls/

**Comment by loctanvo** [comment]
@kasunkv in case you didn't notice, that is the same article i posted in my answer :-)

**Comment by kasunkv** [comment]
@loctanvo  Sorry bro, i got mixed up with the source.. Thanks :) :+1:

**Comment by explunit** [comment]
@kasunkv can you elaborate on how you solved this? Are you specifically including a hash in the server-side `RedirectUrl` that you send to IdentityServer3, or is your `RedirectUrl` the portion without the hash and IdentityServer3 is sending that back to you again later? I notice that the hash portion is included in the browser Url on the initial redirect to the login page.
