### ISSUE TITLE
Error notification

### ISSUE THREAD

**Issue by webbkvalite** [IdentityServer/IdentityServer3#1282]
We use the built-in identityserver tracing (Thinktecture.IdentityServer.Core.Logging.TraceSourceLogProvider). 
Where would be the best place to add an email notification of traces of LogLevel "Error" or higher?

**Comment by leastprivilege** [comment]
You can write your own log provider - check the LibLog project on Github.

**Comment by leastprivilege** [comment]
Or use a logging framework that is support by LibLog and also supportes email notifications.

**Comment by webbkvalite** [comment]
Thank you! I simply wrapped the TraceSourceLogProvider with an addition email-sender. Works like a charm.

**Comment by webbkvalite** [comment]
public class EmailLogger : ILog
    {
        private TraceSourceLogProvider traceProvider = new TraceSourceLogProvider();

        public bool Log(LogLevel logLevel, Func<string> messageFunc, Exception exception = null)
        {
            if ((logLevel == LogLevel.Fatal || logLevel == LogLevel.Error) && exception != null)
            {
                var template = new FatalErrorReportTemplate("Otimo Identity Server, Identity", exception.Message);
                SMTPSendService.SendMail("SysAdmin", OtimoIdentityServer3.Domain.OtimoSettings.SysAdminEmail, template);
            }

            var tracelogger = traceProvider.GetLogger("Custom Trace/Email Logger");
            return tracelogger.Log(logLevel, messageFunc, exception);
        }
    }
