### ISSUE TITLE
Implementation of Hybrid flow for Angular JS

### ISSUE THREAD

**Issue by DivakarPM** [IdentityServer/IdentityServer3#1283]
I need some implementation guidance, I have an AngularJS client with ASP.NET Web API on the server-side. Here are some questions:
1. I have implemented Implicit flow where I'm able to get the id_token and access_token from the IdentityServer. I would like to know if we can implement Hybrid flow that allows refresh-tokens?
2) What's the right way to handle session management on a JavaScript client?

**Comment by brockallen** [comment]
1. We have a sample that shows using a RT, but you'll have to do this from your server-side code (not your NG code). Our sample if just using MVC.

2. We have a helper library: https://github.com/IdentityModel/oidc-token-manager

**Comment by DivakarPM** [comment]
Thanks Brock..

In the video (http://www.ndcvideos.com/#/app/video/2651) you have explained that, we can achieve session management by having an iframe that contains javascript which looks for the cookie and deletes the cookie when user Signed out from the browser. 

For handling client sessions, is this the approach that you recommend or the one using MVC?

**Comment by brockallen** [comment]
That video was Dominick, not me.

We have a sample for the check session endpoint in the JS sample.
