### ISSUE TITLE
Choosing best Grant type.

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1284]
Hi All, 

I have requirement of implementing OAuth and openid connect for MVC + Webapi enterprise application to authenticate and authorize the users based on token generated. 
I need to have Access token, Refresh token and Id token but with customized login screen. 

About customized login screen : I want to have username in the first screen and password in the next screen then submit the request into the identity server. 

Thanks,
Dhanaraj

**Comment by leastprivilege** [comment]
Cool. Have fun implementing it.

(reading the docs will help)

**Comment by dhanutpk** [comment]
Are you saying that it isn't possible to customize the login screen?

**Comment by leastprivilege** [comment]
no.

**Comment by dhanutpk** [comment]
Throw some lights on that where I should look into the Identity server code base in order to customize.

**Comment by brockallen** [comment]
The best you're going to do is be able to do this sort of thing from JS (meaning hide/show) or by hooking the PreAuthN in the user service and redirect to your own entire login system and from there you can issue the primary authentication cookie via the OWIN environment extension methods.

**Comment by dhanutpk** [comment]
It would be great help, if you could modify identity server3 login screen according to my requirement and it is also one of the most common scenario now a days everybody expects.

**Comment by brockallen** [comment]
You're the first to ask for it.

**Comment by johnkors** [comment]
I've never seen one, so I'm quite interested. Can you link to a sample showing this user experience for logins?

**Comment by iltera** [comment]
First enter username, then click next, then enter password, click next... Seems like a lot of user interaction which are not fully neccessary in my opinion, and really doubt that extra mouse clicks would be a common scenario any day to come.

But, if you are really going for it, try customising the login template and change the html using ng-show / ng-hide / ng-click directives. You only need a button and show / hide on the username and password inputs. You can find the documentation about custumizing views in here: http://identityserver.github.io/Documentation/docs/advanced/customizingViews.html

Really interested what you'll come up. Hope you'll care to share it with us.

**Comment by huysentruitw** [comment]
An example of this is https://onedrive.live.com/about/nl-be/

**Comment by leastprivilege** [comment]
..but not a good one. Microsoft's live infrastructure is messed up that they need to know first if the user is a "private" user or organization (Azure AD) or Office 365 before they know to which login page to redirect. Hence the multiple screens.

**Comment by dhanutpk** [comment]
The reason why i am asking multiple screen for identity server is in place of password screen i may use email service, message services based on user user configuration. 
So that is why i am asking username/email address should be in first screen and in second screen i may have password/email service/message service in order to authenticate users and issue the tokens.

Thanks,
Dhanaraj

**Comment by leastprivilege** [comment]
So you an achieve that by using a partial login workflow and a custom login page (that hides the password field).

**Comment by dhanutpk** [comment]
yeah, I have implemented custom login page in order to achieve this functionality by extending 
Thinktecture identity server 3.

**Comment by huysentruitw** [comment]
GMail now also takes this approach:
http://techcrunch.com/2015/05/13/gmails-new-login-screens-hints-at-a-future-beyond-passwords/#.tmsnlb:fhCi
