### ISSUE TITLE
Thinktecture.IdentityServer.Core.Models

### ISSUE THREAD

**Issue by HornerGrahame** [IdentityServer/IdentityServer3#1285]
would it be possible to have the Scope, ScopeClaim and Client implement a interface contract and use this minimal contract where currently Scope, ScopeClaim and Client types are returned; this will ease the development/implementation of factory/storage providers of configuration used to drive the identityserver

**Comment by HornerGrahame** [comment]
and provide a way to extend the Scope, ScopeClaim and Client implementations moving forward

**Comment by brockallen** [comment]
Can you provide a concerte example of the motivation for this?

**Comment by HornerGrahame** [comment]
as a developer I may wish to extend the models with additional information at the logic/persistence layer; while this can be done; it would make life a lot easier if I could simply create a model which is derived from a base class or implements a contract interface instead of explicitly having to convert models.

**Comment by brockallen** [comment]
Sorry, I'm thick -- what's the concrete example? You mean in your custom extensions to IdSvr you want to be able to downcast to your custom model types (or even better all the APIs generic on your custom model types)?

**Comment by HornerGrahame** [comment]
@brockallen your far from thick; it's my poor example/explanation that is failing here.  I'll try to better translate my idea.  At present the code is strongly coupled to the claim/scope/client models etc. I would like to use my own models for example: a scope model that implements additional functionality; but still conforms to the require base model contract; so not to break any existing code implementations, an example of the additional functionality would be decoding encrypted information at runtime using a digital for a client certificate.

The reason behind these ideas is to have a identity server that is multi-tenant allowing tenant to register and trust client applications create by others and well as invite/trust users to use the client applications; while maintaining separation of configuration data via security using digital certificate for the tent   

Your correct better still would be generic APIs that accept model implementation that have base contract.

Hope that is a little better explained as I have trouble translating ideas to writing at times.

**Comment by brockallen** [comment]
Well, sorry -- I think this would be too big of a change for us. If you need related data, then our suggestion would be to build a separate DB with different tables with your custom values and then have a different repository to load these values.
