### ISSUE TITLE
Strategy of token when using client credentials flow

### ISSUE THREAD

**Issue by mderriey** [IdentityServer/IdentityServer3#1286]
Hi,

I'm in the process of securing internal web services.  
I've successfully used `Thinktecture.IdentityServer3.AccessTokenValidation`on the server-side and `Thinktecture.IdentityModel.Client` on the client-side.

I don't care about the identity of the end-user, I just want to make sure `application A` is allowed to call `web service B`. To do so, I created a Client for my `application A`, allowed it to request `WebService-B` scope, and secured the web service with this scope.

So the `application A` asks for a token with its credentials and stores it in the `Authorization` header before firing the request.

I don't know which strategy I should use:
 - Make access tokens for the `application A` short-lived and ask for one every time the application has to call the web service
 - Keep the access tokens long-lived, and have the `application A` store them somewhere until they expire, then ask for a new one

The first option makes my life easier since I don't have to worry about storing the token somewhere nor handling expired tokens related errors.
The second one puts a bit more work on the client, but **way** fewer tokens are generated.

Any advice?
Thanks in advance :smiley:
PS: Is there somewhere else you'd be more comfortable ansering this kind of questions?

**Comment by brockallen** [comment]
With client credentials, the client app needs access to the secret. So just get an access token for some amount of time and when it expires get a new one.

**Comment by mderriey** [comment]
Thanks for the anwser. I don't really get the "client app needs access 
to the secret" part. That seems obvious, it'll be stored in the app 
configuration. Are there drawbacks to requesting a new token every time 
the client app needs to access the web service?

**Comment by brockallen** [comment]
_That seems obvious, it'll be stored in the app configuration_

Right, so an access token can be obtained any time it's needed. No need to store the access token too. Get it and use it for 1 hour (or 4 hours, or 10 hours, or whatever).

**Comment by mderriey** [comment]
I may have forgotten to tell the client is a web app, so storing the access token would be necessary if I want to use it for a "long" time (2+ HTTP requests).
As long as there's no performance problem with requesting an access token each time I want to use it, I'm good.

Thanks

**Comment by brockallen** [comment]
So a typically approach is to get an access token on the server side, and then render it into each HTML page if the JS needs to use it.

**Comment by senj** [comment]
Which security risks do I have to consider if I render the token to my JS client?

**Comment by herberav** [comment]
@mderriey What strategy of token did you use? I'm wondering the same.
