### ISSUE TITLE
Would it be possible to make the RefreshTokenLifetime infinite

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1288]
In our environment our login mechanism is controlled using Cookies, we have a way to expire user login. Would it be possible to make RefreshTokenLifetime infinite?.

**Comment by jawadatgithub** [comment]
based on [docs](http://identityserver.github.io/Documentation/docs/advanced/refreshTokens.html):

In client class set:

RefreshTokenExpiration = Absolute
AbsoluteRefreshTokenLifetime = value in seconds

if you set lifetime to lets say 10 years, I think its infinite in term of usual software age.

**Comment by skatukojwala** [comment]
Sure. But I was checking to see if can set to some infinite value.

**Comment by johnkors** [comment]
Just be aware that if someone get's hold of that refreshtoken with an infinite/ "infinite" lifetime, they can misuse it the same infinite/"infinite" amount of time to get access tokens even though you've removed your cookies.

**Comment by leastprivilege** [comment]
Would `int.MaxValue` work for you? ;)

**Comment by skatukojwala** [comment]
Sure, I can use that. Thank you for the clarification.

**Comment by skatukojwala** [comment]
The software is going to be used inside a operating theater! We want to make sure that we can
the tokens can be renewed for long time.  I always had in mind about using MaxValue, which is insanely long time.  Thank you clarifying this.
