### ISSUE TITLE
Question about custom views

### ISSUE THREAD

**Issue by Blastnsmash** [IdentityServer/IdentityServer3#1290]
First, let me explain my assumptions.

I am assuming the custom views are mainly for JavaScript / browser clients. From what I have read, there isn't a secure way to get the user name and password through JavaScript and send that programmatically to the OIDP? What a website would probably like to avoid is redirecting someone to a different website in order to login (let me know how much of that is incorrect.) So, in order to make this a better user experience, I'm assuming we can customize a view and maybe present the login to the OIDP in an iframe in order to make the login experience more seamless to the user.

So, if that is the case, is it possible to present different custom views to different clients? For example, let's say I'm the ID provider for multiple websites, I want each one of the clients to specify which custom view they want to see when they request a login, logout etc.

Is this possible now? In the customviewservice example, can I say, hey I don't want a custom view give me the default view? Or, give me xyz custom view?

**Comment by brockallen** [comment]
This is a hard problem because the SSO server is shared across clients. In many scenarios it doesn't make sense to make pages client specific.

**Comment by huysentruitw** [comment]
We also have the same request for client specific login pages. Would https and resource owner password credential flow be an easier way to solve this problem?

**Comment by leastprivilege** [comment]
The view service knows how the client is - you can adjust the look and feel in any way.

**Comment by Blastnsmash** [comment]
Oh of course. Dynamically change the html based on the client that is requesting the login, logout etc. I'll hopefully look into that tomorrow maybe provide a code snippet. 

huysentruitw, can you use resource owner password credential flow via javascript? Is there a client sample? I think I overlooked it.

**Comment by Blastnsmash** [comment]
So, one way of doing this is by overriding the Render method in the CustomViewService.cs class:

    protected virtual Task<System.IO.Stream> Render(CommonViewModel model, string page, string clientName = null)
        {
            var json = Newtonsoft.Json.JsonConvert.SerializeObject(model, Newtonsoft.Json.Formatting.None, new Newtonsoft.Json.JsonSerializerSettings() { ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver() });

             string html = "";

            if (clientName == "AspecificClient")
            {
                html = LoadHtmlFromApp2(page);
                html = Replace(html, new
                {
                    siteName = Microsoft.Security.Application.Encoder.HtmlEncode(model.SiteName),
                    model = Microsoft.Security.Application.Encoder.HtmlEncode(json),
                    clientName = clientName
                });
            }
            else
            {
              html  = LoadHtml(page);
                html = Replace(html, new
                {
                    siteName = Microsoft.Security.Application.Encoder.HtmlEncode(model.SiteName),
                    model = Microsoft.Security.Application.Encoder.HtmlEncode(json),
                    clientName = clientName
                });
            }
            
            return Task.FromResult(StringToStream(html));
        }


The LoadHtmlFromApp2 function would find the directory @"content\app2". I'm not entirely sure it'd work because I don't have time to test it but something like that would probably do the trick.

**Comment by suryapratap** [comment]
```Microsoft.Security.Application.Encoder``` is internal so cannot be accessed by an external assembly

**Comment by theCuriousOne** [comment]
Maybe someone else will find helpful the answer to @suryapratap  - http://stackoverflow.com/questions/5979887/cant-include-microsoft-security-application
