### ISSUE TITLE
Is there a max size on the JWT Token?

### ISSUE THREAD

**Issue by vigsgb** [IdentityServer/IdentityServer3#1291]
Wondering if there is a max JWT size as I am running into an issue where the token is not being processed by OWIN when using the AccessTokenValidation when it gets over a certain size.

I have a client passing a token to a Web API and it works fine until that token hits a certain size.

Any Ideas?

**Comment by brockallen** [comment]
That's a URL limit, not a JWT limit.

**Comment by vigsgb** [comment]
When I debug the web api I can see the complete token being passed in the
header request it is just not being parsed or something. I see the token in
the authentication header on the context within the web api so it is making
it there. It is only about 2700 bytes long. I can take that same token and
reduce the size and it works fine. It is a size issue almost like there is
a jwt token size limit somewhere.

**Comment by delRyan** [comment]
We ran into this exact same problem. Brock is talking about URL limits because web api takes the token from the header and issues a GET request to:

https://your-identity-server/connect/accesstokenvalidation?token=your-really-long-token

If your token is too long this request will return a 404. A length of about 2020 characters will cause this to happen. A possible solution might be to add an endpoint to identity server where the token is part of the body instead of the URL, but you're really going to want to use reference tokens instead. 

So in a sense, yes there is a jwt size limit.

**Comment by leastprivilege** [comment]
But only when you are using the token validation endpoint - which does not make a lot of sense for JWTs - you can ValidationMode to Local

**Comment by vigsgb** [comment]
I will set validation mode to local as it is using the endpoint by default.
Thanks for the info

**Comment by johnkors** [comment]
> which does not make a lot of sense for JWTs 

Hi Dom, could you elaborate a bit? In another issue you recommended this approach for clients on platforms with missing crypto libs, where "local mode" is less of an option.

**Comment by leastprivilege** [comment]
Hey, 

I think my previous comment was more around using the identity token validation endpoint - e.g. when a JavaScript client does not want to implement the crypto - it can use this endpoint to validate the id token.

In the case of access tokens - i think most server environments will be able to validate JWT (certainly .NET) - in that case I would validate the tokens using the "Local" option. Or use a reference token (but that's typically for different reasons).

**Comment by vigsgb** [comment]
I switched to validation mode to local and yep that resolved the issue.   However my lack of experience using authentication makes me wonder what I should be doing for token validation and where to implement that code.   Any suggestions?

**Comment by leastprivilege** [comment]
The middleware does all that for you.

**Comment by vigsgb** [comment]
Ok thanks much appreciate the replies and info.
