### ISSUE TITLE
How to get users email on the client

### ISSUE THREAD

**Issue by apryiomka** [IdentityServer/IdentityServer3#1294]
Hi Everybody,
I am going thru examples, but I struggle to figure out one thing. I cannot see how I can get users email on the client side. I use social networks (FB, google, twitter) for authentication. My client scope says profile and email:
The client:
ResponseType = "id_token token",
Scope = "openid profile email",
SignInAsAuthenticationType = "Cookies", 
The Server:
ScopeRestrictions = new List<string>
                    { 
                        Constants.StandardScopes.OpenId,
                        Constants.StandardScopes.Profile,
                        Constants.StandardScopes.Email
                    }
I get the email on the Identity Server side and can save it in the DB. But on the client when I get token and do, say, user info, i do not receive the email  back.  How can I identify the user if i have token and user first/last names. I store users in the DB, but the users are unique by email. I need the email on the client as well because i need to identify the user. I tried to use UserInfoClient as well as OAuth2Client, but I just don't see how to get an email. I am also fine with getting, say, provider id as well. I can see the claims in the DB like this:
Id	UserId	ClaimType	ClaimValue
1	2a06268e-b72e-4f32-a15c-d6ea35db4da8	urn:google:profile	https://plus.google.com/123456789012345687890
2	2a06268e-b72e-4f32-a15c-d6ea35db4da8	given_name	myUserName
3	2a06268e-b72e-4f32-a15c-d6ea35db4da8	family_name	.
4	2a06268e-b72e-4f32-a15c-d6ea35db4da8	name	myUserName

The user is created as well, but still, how do I identify the user on the client side. I need to have the users' email.

Thanks,
Alex.

**Comment by loctanvo** [comment]
In UserService, are you mapping the email claims in the GetProfileAsync (or similar, don't remember the exact name of the method)? IIRC, the GetProfileAsync gets the list of requested claims, and you have to do the mapping and filtering yourselves.
