### ISSUE TITLE
MVC Website, Async Login Right Flow?

### ISSUE THREAD

**Issue by federicobarera** [IdentityServer/IdentityServer3#1297]
Hi,

I had a look at "Securing an MVC Website" sample, all clear.

Now assuming that, like in the demo, your identity server is hosted inside of the website, the same website where you handle user registrations, verification etc, how do you handle "ajax login boxes"?

The login box suppose to post async your details to the identity server and then save a session cookie.

I understand that this could be highly discouraged because you are actually giving your details to the client, but thinking about scenarios where the website is the main company application, you can see this technique actually widely used (you trust to insert your credentials in the same website where you registered those).

Is this as easy as use the resource owner flow from javascript (or proxing via your sever) and then save a cookie with the claims contained in the access token or you recommend a better approach?

Thanks

**Comment by leastprivilege** [comment]
The demo is a demo. Realistically you would not host IdentityServer inside the client.

**Comment by federicobarera** [comment]
Hi Dominick,

thanks for your answer and the priceless videos and examples you posted on pluralsight and leastprivilege, they are very helpful.
Is the scenario provided by my question (Login Box on website (A) sends ajax post request to Identity Server (B), gets back a token and establish a session cookie with (A)), falling into a resource owner password flow?
Can't really find anything around describing this scenario.

**Comment by leastprivilege** [comment]
Yes that would be resource owner flow - though you would not do it via Ajax - but server side.

You won't get SSO, external idps etc with that approach.

**Comment by federicobarera** [comment]
Yeah, I understand...
In house we are trying to shift our systems from old forms auth to an identity server, toughest challenge is to keep functional some ux choices made in the past, like the ajax login box described.

Thanks again for you time, I hope this answer will help other ppl with the same problem :)
