### ISSUE TITLE
Notifications handler for WebAPI UseIdentityServerBearerTokenAuthentication

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#1298]
Hi,

I am using UseIdentityServerBearerTokenAuthentication to authentication my api.
Is there something similar to the OpenIdConnectAuthenticationNotifications, that I can use with API authentication?

In my web api auth, I would like to perform some claims transformation based on the scopes that are returned from IdentityServer.

Is this possible?

**Comment by brockallen** [comment]
Just add another middleware after the bearer middleware.

**Comment by parkinsona** [comment]
Which middleware would I be using for this? Is there one  already kicking around?

**Comment by brockallen** [comment]
you can simply write your own

**Comment by parkinsona** [comment]
Thanks again Brock.
I remembered there was one written into IdentityModel. It was easy to setup.

http://leastprivilege.com/2013/09/18/claims-transformation-middleware-for-katana/

**Comment by parkinsona** [comment]
I have a question on exception handling for my claims transformations in web api.
In my transform, I throw an exception if there are any required claims missing.

This seems to render the html for error page and will send that back as the response. Is there a way to avoid this happening?

**Comment by brockallen** [comment]
For new topics, you should open new issues.

**Comment by parkinsona** [comment]
Sorry, I didn't know if it was a new topic because it was related to the original topic. I'll open a new issue.
