### ISSUE TITLE
Question regarding how tokens are passed

### ISSUE THREAD

**Issue by danielbsig** [IdentityServer/IdentityServer3#1300]
Hi,

I've got a Web API which needs to support file downloads, only authenticated users should be able to download files, and I also want to track which users have downloaded which files.

AFAIK, this is hard to do in pure Ajax, especially if one wants to support browsers other than just the bleeding edge versions. Which means I kind of have to give the user a direct download link to my API methods which allows them to download the given files. But that means that I cannot attach any HTTP headers to those links.

Wouldn't this imply that I need to use cookies for auth tokens, instead of passing them via the Authorization HTTP header?

Regards,
Daníel

**Comment by brockallen** [comment]
Cookies, or a short lived query string token.
