### ISSUE TITLE
ADFS Integration

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#1302]
Hi,
I am having problems with linking my adfs to identity server.  I am using the CustomUserService as an example.  I have my ADFS set up and can log in with an MVC app going directly to ADFS.
The problem arises when I try and add identity server.  There is something obvious I am probably missing.

Here is my config for IdServer in the sample:

 var options = new IdentityServerOptions
                {
                    IssuerUri = "https://idsrv3.com",
                    SiteName = "Thinktecture IdentityServer3 - CustomUserService",

                   SigningCertificate = Certificate.Get(),
                    Factory = factory,
                    CorsPolicy = CorsPolicy.AllowAll,
}

my WsFederationAuthenticationOptions :
 var adfs = new WsFederationAuthenticationOptions
            {
                AuthenticationType = "adfs",
                Caption = "ADFS",
                SignInAsAuthenticationType = signInAsType,
                MetadataAddress = "https://adfs.domain.com/federationmetadata/2007-06/federationmetadata.xml",
                Wtrealm = "https://idsrv3.com",
            };

I have added a Relying Party as below.

In ConfigurationURL I have enabled support for WS Passive and the url is "https://localhost:44333/" (iis express idserver url on local machine)

I have also added the Realm "https://idsrv3.com" to the trust identifiers.  
I have included a few claims and when I try to login in I get to the login page on ADFS and enter the correct credentials.  I get an error "The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used."  Is there something obvious I have missed in my relying party set up?

Thanks

**Comment by leastprivilege** [comment]
is it really https://localhost:44333/  - or /core/ at then end?

**Comment by paddyhamilton** [comment]
My stupidity.  That seems to have worked.  Silly mistake.

After I log in I get redirected back to the id server login in screen and the Invalid Account error is showing.  

I am trying to debug the ExternalRegistrationUserService but it doesnt seem to hit any other method other than PreAuthenticateAsync.

The user details are correct but I see in the log that it says 

-- no subject or unique identifier claims from external identity provider. Claims provided:

Is there something else I am missing here or it may well be something in ADFS not set up correctly?

**Comment by johnkors** [comment]
You need at least the name/sub claim sent from ADFS I believe.

https://github.com/IdentityServer/IdentityServer3/blob/e50124f4ca02175ea4011dab32a5cb7bea81bdab/source/Core/Models/ExternalIdentity.cs#L60

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/AuthenticationController.cs#L353

**Comment by paddyhamilton** [comment]
Thanks guys.  All sorted
