### ISSUE TITLE
AccessTokenValidation endpoint performance 

### ISSUE THREAD

**Issue by akiander** [IdentityServer/IdentityServer3#1303]
Even though we cache the result, the first call to the AccessTokenValidation endpoint is often 10 - 20 seconds. 

We [suspect](http://stackoverflow.com/questions/30009142/why-is-accesstokenvalidation-so-slow-on-our-identityserver3-instance), although can't confirm, that the slowness may be in the ICache implementation for ITokenHandleStore... [here](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/TokenValidator.cs#L227)

I'm wondering how I can swap out the ITokenHandleStore to test this theory in my production environment. Is there a quick way to hook up a different implementation using the factory? 

I have looked through the documentation site on Access Token Validation but didn't see exactly where this could be done.  

I have more details about this on my [stackoverflow post](http://stackoverflow.com/questions/30009142/why-is-accesstokenvalidation-so-slow-on-our-identityserver3-instance)

**Comment by johnkors** [comment]
How to register your own implementation: http://identityserver.github.io/Documentation/docs/advanced/customServices.html

List of services you may swap out for your own:
http://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html

**Comment by imperugo** [comment]
If you want to use redis, take a look here http://www.nuget.org/packages/IdentityServer3.Contrib.Cache.Redis/

**Comment by brockallen** [comment]
Can we close this?

**Comment by akiander** [comment]
You can close it. The issue ended up being [this line of code](https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/master/Source/Core.EntityFramework/Stores/BaseTokenStore.cs#L71) which happened to be the first call to the OperationalDbContext. That first call was very slow so we added some code to make that call proactively at startup so by the time the code needed to call it again, it was warmed up and performed much better.

**Comment by brockallen** [comment]
EF FTW. Thanks.
