### ISSUE TITLE
Problem with Logout in two Windows

### ISSUE THREAD

**Issue by CarlosGarciaG84** [IdentityServer/IdentityServer3#1306]
URL:
Steps to reproduce:
1- Login into the any application
2- Open the anyapplication in a second tab
3- Click on Logout in any tab
4- Click Logout in the other tab
5- An error appears

Posibility :
 [Route(Constants.RoutePaths.Oidc.EndSession, Name = Constants.RouteNames.Oidc.EndSession)]
        [HttpGet]
        public async Task<IHttpActionResult> Logout()
        {
            Logger.Info("Start end session request");

            if (!_options.Endpoints.EnableEndSessionEndpoint)
            {
                Logger.Warn("Endpoint is disabled. Aborting");
                return NotFound();
            }

            var result = await _validator.ValidateAsync(Request.RequestUri.ParseQueryString(), User as ClaimsPrincipal);
            if (result.IsError)
            {

                var messageError = _generator.CreateSignoutMessage(_validator.ValidatedRequest);
                messageError.ReturnUrl = Request.RequestUri.ParseQueryString().Get(Constants.EndSessionRequest.PostLogoutRedirectUri);
                // if anything went wrong, ignore the params the RP sent
                return new LogoutResult(messageError, Request.GetOwinEnvironment(), this._options);
            }
        
            var message = _generator.CreateSignoutMessage(_validator.ValidatedRequest);

            Logger.Info("End end session request");
            return new LogoutResult(message, Request.GetOwinEnvironment(), this._options);
        }

**Comment by brockallen** [comment]
What's the error? I just tried to reproduce this and saw no error -- everything worked as expected.

**Comment by brockallen** [comment]
No update?
