### ISSUE TITLE
Ho to align accesstoken lifetime and Browser cookie lifetime

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1307]
I have a scenario there the Webapplication(MVC OWIN) requests the accesstoken token during its own [Authorize] Attribute processing on some MVC Controller. Then the  accesstoken is used to access some RESTService.

Now her is my intented scenario:
Now if the accesstoken expires the webapplication cookie should also expire. Thus prompting the user to login again.
Is this possible to implement this with identityserver? If yes how can I adjust the Webapplication’s Cookie lifetime? How can I trigger the refresh and subsequent prompt to login again?

thank you

**Comment by brockallen** [comment]
So in your MVC app just remove your own token and make a request to IdSvr and pass the prompt=login param to IdentityServer.

**Comment by davidmrichter** [comment]
You mean "remove" - remove the Cookie?? which?

![2015_05_05_14_50_40_barto_identity_view](https://cloud.githubusercontent.com/assets/9887781/7472836/abd5f8e8-f336-11e4-8178-29576b14d57e.png)


because for the Webapp cookie authentification is used like here:

app.UseCookieAuthentication(new CookieAuthenticationOptions
			{
				AuthenticationType = "Cookies"
			});
......----.........
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
			{
SignInAsAuthenticationType = "Cookies",

**Comment by brockallen** [comment]
Yes, in your MVC app remove the cookie by calling Request.GetOwinContext().Authentication.SignOut("Cookies"). That will get the user signed out of your MVC app. 

Then when you're redirecting to IdentityServer (via the OIDC MW's Notificationas event) add the prompt param (as per our docs): https://identityserver.github.io/Documentation/docs/endpoints/authorization.html

**Comment by davidmrichter** [comment]
Isn't it possible to set the lifetime of the cookie (which the idenitityserver produces) so it expires "automatically"?
So removing the cookie by hand would not be necessary?

**Comment by brockallen** [comment]
The cookie middleware has no idea when your access tokens expire.

**Comment by davidmrichter** [comment]
Could I "teach" the middleware monitoring the cookie lifetime? 
like:
app.UseCookieAuthentication(new CookieAuthenticationOptions
			{
				AuthenticationType = "Cookies",
ExpireTimeSpan = new TimeSpan(0,0,60)
			});

**Comment by davidmrichter** [comment]
What is then the standard scenario:

The uses logs in via the webapplication. Once logged in user can work with the application(without rest calls) infinitly regardless of accesstoken lifetime? This is Because SignInAsAuthenticationType = "Cookies" right?

**Comment by brockallen** [comment]
There is no standard scenario. Every scenario has different requirements. Having said that, maybe it makes sense to start with a 10 hour cookie and access token. That will handle most end user scenarios.

**Comment by davidmrichter** [comment]
With standard you include removing the cookie in case accesstoken expired and redirecting, right?

Apart from that there is no other posibility to cope with the expiry of the accesstoken and the required re-login?

**Comment by brockallen** [comment]
Well, it's just not a common request. The user authentication lifetime is really something separate from access token lifetime. But if you want to make them the same, you can -- the lifetime of each is configurable.

**Comment by binarymist** [comment]
Where is the user authentication lifetime configured? I've only been able to find AccessTokenLifetime on Client, which of course isn't much good for allowing a user to select a "Keep me logged in" check box

**Comment by brockallen** [comment]
`AuthenticationOptions`: https://identityserver.github.io/Documentation/docsv2/configuration/authenticationOptions.html

**Comment by binarymist** [comment]
That looks to apply to cookies only? How would that apply to using reference access tokens? I'm thinking it wouldn't. Which means the only mainstreamish way of doing a remember me with ResourceOwner flow  is by doing the refresh token dance?

**Comment by brockallen** [comment]
Access tokens don't reflect the user's "logged-in-ness". If you don't want the ROPF client to need to re-authenticate the user, then issue long-lived access tokens or use refresh tokens.

**Comment by binarymist** [comment]
I'm a bit confused by your comment: 'Access tokens don't reflect the user's "logged-in-ness"'. 

If I don't call TokenClient.RequestResourceOwnerPasswordAsync I'm not logged in.
If I call TokenClient.RequestResourceOwnerPasswordAsync I receive an access and refresh token.
Validating the access token if I'm logged in yeilds a 200 with the associated claims.

Long-lived access tokens are per client rather than per user, so individual users don't get the option of whether they would like to stay logged in or not, yeah? So the only option here is the refresh token dance, yeah?

**Comment by brockallen** [comment]
Access tokens represent the client's ability to invoke an API on the user's behalf. Granted the subtle distinction is murky for ROPF scenarios.

But anyway, back to your goal -- to not re-prompt the user then use long lived access tokens (reference tokens recommended here), or use refresh tokens.
