### ISSUE TITLE
Thinktecture Identity Server 3 Logout issue

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1308]
Hi , 

I am using Identityserver3 with default values tokens lifetime but my application wasn't able to logout instead it is coming to consent screen to regenerate the access token.

**Comment by brockallen** [comment]
Did you disable `UseTokenLifetime` on the OIDC middleware?

**Comment by dhanutpk** [comment]
It works for me after setting below options in identity server. 
   EnablePostSignOutAutoRedirect = true,
                        EnableSignOutPrompt = false,
                        RememberLastUsername = true,
                        PostSignOutAutoRedirectDelay = 5,
                        CookieOptions = 
                        { 
                            ExpireTimeSpan = TimeSpan.FromMinutes(2),
                            SecureMode = CookieSecureMode.Always,
                            SlidingExpiration = false     
                        }

**Comment by brockallen** [comment]
No, I meant UseTokenLifetime in your client app.

**Comment by brockallen** [comment]
Are we all set? If so, can we close this issue?
