### ISSUE TITLE
Only one valid access token per user in resource owner flow

### ISSUE THREAD

**Issue by jack-en** [IdentityServer/IdentityServer3#1309]
Hello , when we request second time with same user credentials to the token endpoint in ID Server 3, It gives us a new access_token , but the first one is still valid, Is there any way to make it expire when we make new request with same credentials. And Are There any endpoints to check access_token's validity ?

**Comment by brockallen** [comment]
Only of the API is using the token validation endpoint and you invalidate the prior access token via the token revocation endpoint. Check the docs for details.
