### ISSUE TITLE
Storing authorization codes, refresh tokens, reference tokens in database

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1310]
Hi, 
I want to store authorization codes, refresh tokens, reference tokens in database. When i ran database migration i was able to create clients Token and consent etc but not authorization codes, refresh tokens, reference tokens tables.

**Comment by brockallen** [comment]
This is the operational data that our EF implementation supports: https://identityserver.github.io/Documentation/docs/ef/operational.html
