### ISSUE TITLE
Question about cookies

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/IdentityServer3#1315]
Hi, 
I noticed that the number of OpenIdConnect cookies is growing while the user is browse the websites.

![2015-05-06_09-52-20](https://cloud.githubusercontent.com/assets/758620/7489458/2ce668f0-f3d7-11e4-9aa6-20fac15b6b2f.jpg)

is it normal?

**Comment by leastprivilege** [comment]
Well - talk to Microsoft about that ;) They don't seem to successfully clean up their cookies.

**Comment by imperugo** [comment]
I supposed so :-)

**Comment by imperugo** [comment]
Here more info http://katanaproject.codeplex.com/workitem/402 (maybe is helpful for someone who has the same problem)
