### ISSUE TITLE
Question about AccessTokenLifetime

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/IdentityServer3#1316]
Hi, 
I've a strange situation on my environment and probably I'm not understanding something.
Looking the database the AccessTokenLifetime is 1 hour but the release token duration is just 5 minutes.

![2015-05-06_13-29-13](https://cloud.githubusercontent.com/assets/758620/7492548/493be346-f3f9-11e4-8c04-8560a6ae5fbb.jpg)

Every 5 minutes the browser has a redirect to the idsrv that release a new one and it's ok for other 5 minutes
Is it normal?

**Comment by brockallen** [comment]
Configure the OIDC middleware in your client with `UseTokenLifetime=false`

**Comment by imperugo** [comment]
I thought I did it, probably I lose that with some merge #autofail :-)
