### ISSUE TITLE
client distinguish between "Unauthorized" and "Accesstoken expired" - how?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1317]
so far always 401 Unauthorized is sent back!

How can some client distinguish between "Unauthorized" i.e. User has not enough Clearance and "Accesstoken expired"?

In the source code is
  public static Dictionary<string, HttpStatusCode> ProtectedResourceErrorStatusCodes = new Dictionary<string, HttpStatusCode>
        {
            { ProtectedResourceErrors.InvalidToken,      HttpStatusCode.Unauthorized },
            { ProtectedResourceErrors.ExpiredToken,      HttpStatusCode.Unauthorized },
            { ProtectedResourceErrors.InvalidRequest,    HttpStatusCode.BadRequest },
            { ProtectedResourceErrors.InsufficientScope, HttpStatusCode.Forbidden },
        };
        

Is there a possibility to propagate ProtectedResourceErrors.ExpiredToken?

**Comment by brockallen** [comment]
401 vs 403

**Comment by davidmrichter** [comment]
I Use somthing like that:
  [ResourceAuthorize(UserActions.READ, CATTLE)]
Yes I read your corresponding Blog entry.

I use:
MyCustomAuthorizationManager : ResourceAuthorizationManager
"If something missing" return false"

Therefore I never get 403, because false is interpreted always as unauthorized. 

How can I bring the MyCustomAuthorizationManager to return 403?

**Comment by brockallen** [comment]
Authorization manager says "yes/no" -- if the user is authenticated that means 403.
