### ISSUE TITLE
Accessing UserInfo when using the implicit flow

### ISSUE THREAD

**Issue by RobRolls** [IdentityServer/IdentityServer3#1319]
Hello,

I am using the implicit flow to acquire an access token for an AngularJS app.  The authorize request looks something like this: 

https://localhost:44300/identity/connect/authorize?response_type=token&client_id=foo&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2F%23%2Fauth%2Fgrant%23&scope=read%20write&state=abc&nonce=123

This is all working fairly well. Now I also want info about the user.  Since I can't request the id_token in the response_type up front as part of the implicit flow I was a bit stumped. 
I came across https://github.com/IdentityServer/IdentityServer3/issues/1146 which led me to believe I can use my access token to acquire my id_token.  The problem I run into when I call the UserInfo endpoint is, as per the specs http://identityserver.github.io/Documentation/docs/endpoints/userinfo.html I need the openid scope to access that endpoint. When I add the openid scope to the initial authorize request scopes I end up with an error "Requests for token response type only must include resource scopes, but no identity scopes."

I feel like I am missing some core concept here.  How can I, or even should I, access the users information when using the implicit flow?

Thanks for your time.

**Comment by brockallen** [comment]
Why no? Look at out JS samples -- we do that.

**Comment by RobRolls** [comment]
Brock,
Thanks for the response.  I now see that you are indeed requesting a response type of token_id token in the JS example.  Looking at the requests when running the example I can see the redirect after a successful login to http://localhost:23453/callback.html#id_token=eyJ0eXAiO... this same token is subsequently used as the Bearer token in the UserInfo request, which all seems to work wonderfully.  What confuses me here is the token that is returned to callback.html is labeled as the id_token.  The docs for the UserInfo endpoint say that you need an access token, but the example is passing it what is labeled as the id_token.  What type of token is being sent to callback.html?

Thanks

**Comment by brockallen** [comment]
There are possibly 2 tokens -- an id_token and an access_token. To call the user profile endpoint you use the access_token.

**Comment by RobRolls** [comment]
Much to my chagrin that was it exactly.  I was not seeing the "access_token=" in the pile output and pasting what turned out to be both tokens into a tool like jwt.io still wrote out the id_token.  Sorry to have bothered you with the second question.
