### ISSUE TITLE
Question: Admin Portal?

### ISSUE THREAD

**Issue by ltraus** [IdentityServer/IdentityServer3#1321]
I looked at IdentityServer.Entityframework.Admin and IdentityServer.Admin they've not been updated in a long time, i know everything's busy busy, but is there an intent to use one of these projects? As i've been considering maybe starting one myself.

I'm thinking the same as IdentityManager, but local administrator. Etc.  If it's the case i'd like to be involved on here?

**Comment by brockallen** [comment]
Those questions should be directed to those repos.
