### ISSUE TITLE
Max Refresh tokens by ClientID

### ISSUE THREAD

**Issue by wiseman13** [IdentityServer/IdentityServer3#1323]
In my original OAuth2 implementation I had added support for limiting the max number of active refresh tokens issued to a user for a given client. I am struggling to see how I might implement the same behavior with IdenityServer3. At the point of confirming an authorization attempt if they are at the max they are then given an option to deauth some number of active refresh tokens to make room for the new auth. 

Thank you for any insights you can provide.

**Comment by leastprivilege** [comment]
It is on our todo list - search for throttling.

This is something that has to be done inside idsrv core (or maybe usign the ICustomTokenRequestValidator for the time being).

We are pretty busy right now. So this feature has been postponed to 2.x

**Comment by kpstolk** [comment]
@leastprivilege Any updates on throttling? Is there already a feature to achieve this?

**Comment by leastprivilege** [comment]
we never implemented throttling. Not enough resources.

**Comment by brockallen** [comment]
> we never implemented throttling. Not enough resources.

seems like this is a form of throttling ;)
