### ISSUE TITLE
Use of refresh_token in MVC Hybrid sample

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer3#1324]
While evaluating the MVC Hybrid sample, I am wondering when the `refresh_token` is used? I see that it gets stored inside the AspNet cookie, but that's it.

Once signed-in, the AspNet cookie is used for authentication (for the current browser session). If the AspNet cookie expires, the OpenIdConnect authentication middleware redirects to the authentication endpoint and gets new tokens right away (probably because the idsrv.session cookie is still valid).

If both cookies have expired (AspNet and idsrv cookies), I'm simply asked to login again...

So when and where should I use the `refresh_token`?

**Comment by leastprivilege** [comment]
It is not used in the sample. Read the OAuth2 spec to understand what a refresh token is,

**Comment by huysentruitw** [comment]
I understand (or kinda :p) what it is, maybe I can rephrase my question: what would it take modify the sample so it uses access_token and refresh_token instead of the AspNet cookie?

**Comment by leastprivilege** [comment]
Cookies and tokens are unrelated ;) The refresh token is not meant to be a replacement. It is for long lived API access.

**Comment by huysentruitw** [comment]
Can I say that: for MVC, the access and refresh token don't have any added value and the id_token is only used once for creating the application cookie?

**Comment by leastprivilege** [comment]
yes

**Comment by huysentruitw** [comment]
Thanks. Moving on... :)
