### ISSUE TITLE
Validation of tokens in the Web API

### ISSUE THREAD

**Issue by DivakarPM** [IdentityServer/IdentityServer3#1325]
I need some implementation guidance, I have an AngularJS client with ASP.NET Web API on the server-side. Here are some questions: 
Will Web Api Communicates to IdentityServer for token validation or do we have handle it separately in the Web API.
Is there any sample which validates the token in the Web API.

**Comment by brockallen** [comment]
This is what you're looking for: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/SampleAspNetWebApi/Startup.cs#L17

**Comment by DivakarPM** [comment]
Thanks Brock.

Will this validation method handles token expiry. Or do we have to write custom method which checks token lifetime.

**Comment by brockallen** [comment]
Yes, it does all the token validation.

**Comment by DivakarPM** [comment]
Thank you very much Brock.. That solves my problem.
