### ISSUE TITLE
Question regarding access token expiry

### ISSUE THREAD

**Issue by aronblum** [IdentityServer/IdentityServer3#1326]
Hi,

Currently for testing purposes, I have AccessTokenLifetime set to 30 seconds for a Hybrid Flow client. I am curious what is meant to happen when the access token expires.

At the moment, I am still able to access my web api resource and navigate through the client mvc application.

I would have thought that I would no longer be able to access the api, or the mvc client once the access token expires.

Can you please clarify what SHOULD happen when an access token expires.

Thanks.

**Comment by loctanvo** [comment]
When the access token has expired, your api should return 401 Unauthorized. Keep in mind that the JWT handler allows around 5 min clock skew (which means that the access token is still valid 5 minutes after expiration time). [Have a look at these issues](https://github.com/IdentityServer/IdentityServer3/issues?utf8=%E2%9C%93&q=clock+skew) for people experiencing similar behavior.
