### ISSUE TITLE
Combine bearer token with MVC5 cookies

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer3#1327]
Say, we have a project hosting MVC and WebApi, both using the IdentityServer as SSO. For MVC, we would use the OpenIdConnect authentication middleware, while for the WebApi we would use the IdentityServer Bearer Token Authentication.

In case of MVC, I'm still having problems with the fact that the id_token is converted into an application cookie and that the tokens are no longer used. Somehow, it should be possible that the MVC controller actions validate the bearer token from IdentityServer (using the IdentityServer Bearer Token Authentication middleware) instead of the application cookie.

The problem with this is that the MVC web pages would have to set the Bearer token in the Authorization header for each request. But what if we have middleware that puts the token in a cookie and for each incoming request, validated the cookie, extracts the token and injects it into the Authorization header which is then processed by the IdentityServer Bearer Token Authentication middleware.

Might sound like a crazy idea but I wonder if this is possible and if any existing middleware can help me with this?

**Comment by brockallen** [comment]
Cookies are used because browsers send them automatically and anti-xsrf is easy for html pages. Anti-xsrf is harder for Web APIs calls, and that's why we use the authorization header w/ bearer tokens.

**Comment by huysentruitw** [comment]
What I'm asking is a way to validate the access token at an MVC controller instead of the application cookie. I'm not totally happy with the fact that the id_token/access_token is only used once to issue the application cookie. I want to validate the tokens for each call (preferably by re-using the IdentityServerBearerTokenAuthentication middleware).

**Comment by brockallen** [comment]
I guess your big problem will be to ensure the token is sent on every request from the browser -- how do you do that?

**Comment by huysentruitw** [comment]
What if we save the token in a cookie? Then, on incoming request, get the token from the cookie and inject it in the Authorization header before the IdentityServerBearerTokenAuthentication middleware?

**Comment by brockallen** [comment]
Well... you're starting to invent your own security protocols. Maybe this is fine, maybe it has a weakness. You'd have to think about it.

**Comment by huysentruitw** [comment]
I don't think this is less secure than leaving the storage of the token up to, let's say, the JavaScript client. Anyway we will probably take an other route, so this one can be closed.
Thanks!
