### ISSUE TITLE
Css and Images are not loading in IdentityServer3 custom view service sample

### ISSUE THREAD

**Issue by DivakarPM** [IdentityServer/IdentityServer3#1328]
I have implemented custom views for login using the Custom view services sample provided. But Css and Images are not loading. If i individually run the page i am able to completely get the page. But when i run it through Identityserver3, css and images are not loading.

**Comment by leastprivilege** [comment]
RAMMFAR!!!!

check the docs or the archive ;)

**Comment by DivakarPM** [comment]
I am newbie to Thinktecture identityserver3.

I have checked the documents regarding this. And i have included this code in the IdentityServerOptions

 CspOptions = new CspOptions()
                    {
                        Enabled = false,
                        ScriptSrc = "/Content/login.css",                        
                    }

But still Css and Images are not loading. 

Please help on this.

Thank you

**Comment by scottbrady91** [comment]
Enable RAMMFAR in your web.config:

<system.webServer>
    <modules runAllManagedModulesForAllRequests="true"></modules>
</system.webServer>

**Comment by DivakarPM** [comment]
Thanks Scott..

RAMMFAR  is enabled in my web config.
<modules runAllManagedModulesForAllRequests="true"></modules>

Still i am facing the same issue.

Thanks...

**Comment by jbrittan** [comment]
Are you running it as an application in a virtual directory in IIS or using IIS Express?

**Comment by johnkors** [comment]
How are you running idsrv, NuGet or from the source?

**Comment by brockallen** [comment]
All set? Can we close this?
