### ISSUE TITLE
Check session endpoint enabled, but SessionId is missing

### ISSUE THREAD

**Issue by mwereda** [IdentityServer/IdentityServer3#1329]
Hi,

When I'm calling Authorize endpoint I'm receiving "Check session endpoint enabled, but SessionId is missing" error. What's strange it happens only on one of our environments. This enviroment is server farm. On enviroments with only one server it doesn't happen - it's working fine.

I have in IS's log something like this:
``` {
  "ClientId": "someClientId",
  "RedirectUri": "https://page.domain.com",
  "AllowedRedirectUris": [
    "https://page.domain.com"
  ],
  "SubjectId": "unknown",
  "ResponseType": "id_token token",
  "ResponseMode": "form_post",
  "Flow": "Implicit",
  "RequestedScopes": "idmgr openid",
  "Nonce": "aebce44b-704a-4173-bde5-494dd1e56a68",
  "Raw": {
    "client_id": "someClientId",
    "redirect_uri": "https://page.domain.com",
    "response_mode": "form_post",
    "response_type": "id_token token",
    "scope": "idmgr openid",
    "nonce": "aebce44b-704a-4173-bde5-494dd1e56a68",
    "a": "login",
    "p": "6119e176-d3fc-4e7a-b511-f787d0020ac5"
  }
}```

I know that SubjectId should be also populated, but it's not and I don't know why.

Is there any setting on IdentityServer that would solve this problem? Any suggestions how can I solve this? :)

**Comment by leastprivilege** [comment]
I believe this was fixed. What version are you on?

**Comment by leastprivilege** [comment]
either way - this is just a wrong log entry. Not a real problem.

**Comment by mwereda** [comment]
I'm using latest version - 1.5.4

**Comment by leastprivilege** [comment]
maybe we fixed it on the 2.x branch?

**Comment by mwereda** [comment]
Is there any prerelease package on nuget for 2.x branch? I need to deploy whole solution on environent and check if it works. I don't have any access to that environment (unfortunately)

**Comment by leastprivilege** [comment]
yes - here

https://www.nuget.org/profiles/identity

but it is pre-release.

**Comment by mwereda** [comment]
It turned out that there was machine key mismatch between servers. After setting proper machine key on both servers it is working perfectly fine.

Thank you for your assistance
