### ISSUE TITLE
(For Implicit Flow)Is it possible to get tenant value (already provided for authz endpoint) when requesting user profile endpoint ?

### ISSUE THREAD

**Issue by sercangurbuz** [IdentityServer/IdentityServer3#1330]
public Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject,
            IEnumerable<string> requestedClaimTypes = null)
        {
//Here obtain the tenant value so that i can request to the correct account store
}

**Comment by brockallen** [comment]
You should emit the tenant as a claims in the Authenticate API on the user service. This claimw ill be present in the ClaimsPrincipal subject param.

**Comment by sercangurbuz** [comment]
Thnks for the reply.I have experienced that GetProfileDataAsync is being called 3 times.First of two for generating id token and access token and third one is when requesting profile endpoint from client.However only sub claim is available in ClaimsIdentity when third one is getting called.
As you said,I added tenant value as a claim on AuthenticateResult returned from AuthenticateLocalAsync,however its only available in GetProfileDataAsync for token generating not requesting profile endpoint from client.

**Comment by sercangurbuz** [comment]
Only sub claim is available when requesting user info endpoint using implicit flow ? What is the point im missing ? I would like all claims added to be available in GetProfileDataAsync.

**Comment by leastprivilege** [comment]
You need to load the claims for the data store in this case.

**Comment by leastprivilege** [comment]
To expand on that - if the client is the browser - we have the cookie and can make all the claims inside of it available. When you call the user info endpoint, this is a direct web API communication which does not involve the cookie - hence no cookie claims.
