### ISSUE TITLE
Returning claims in profile scope

### ISSUE THREAD

**Issue by CSobering** [IdentityServer/IdentityServer3#1331]
Hi,

We are using Thinktecture Identity server as OIDC Identity Provider to grant our users access to a resources provided by a third party. This third party uses the authorization code flow and uses the standard profile scope. 

In the userinfo response we want to return the subject, given name and name claims. The subject claim is retrieved by the principal.getSubjectId method, the given name is currently a default string (the same for all users). We have problems returning the name claim as the principal.getName method does not return a value at the time it is called (returns null).

We manage to store the name claim and value in the TokenStore with the Token. The userinfo endpoint reads the token from the TokenStore and then removes it. 

What we observed in 

Namespace: Core.Endpoints.UserInfoEndpointController
Method: GetUserInfo(HttpRequestMessage request)

// pass scopes/claims to profile service
var subject = tokenResult.Claims.FirstOrDefault(c => c.Type == Constants.ClaimTypes.Subject).Value;
var scopes = tokenResult.Claims.Where(c => c.Type == Constants.ClaimTypes.Scope).Select(c => c.Value);

var payload = await _generator.ProcessAsync(subject, scopes);

Is that tokenResults.Claims contains all claims we need, including the name claim. When the ProcessAsync is called, all claim information is lost. 

How can we arrange that the information from the claims in the token is preserved? 

Kind regards,
Carel Sobering

**Comment by leastprivilege** [comment]
Claims for tokens are being generated by the user service GetProfileDataAsync method. This is where you need to write code.

**Comment by CSobering** [comment]
This is the code we wrote:

```
public Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
      {
         using (var log = Logger.GetLogger(this, subject, requestedClaimTypes))
         {
            var claims = new List<Claim>();
            if (requestedClaimTypes != null)
            {
               foreach (var requestedClaimType in requestedClaimTypes)
               {
                  switch (requestedClaimType)
                  {
                     case Constants.ClaimTypes.Subject:
                        claims.Add(new Claim(requestedClaimType, subject.GetSubjectId()));
                        break;

                     case Constants.ClaimTypes.GivenName:
                        claims.Add(new Claim(requestedClaimType, "user"));
                        break;
                     case Constants.ClaimTypes.Name:
                        string displayName = subject.GetName(); //returns null the second time
                        
                        claims.Add(new Claim(requestedClaimType, displayName));
                        break;
                     default:
                        break;
                  }
               }
            }

            log.ReturnValue = claims;
            return Task.FromResult(claims.AsEnumerable());
         }
      }

```

As I understand this piece of code is called twice. The first time the Name claim is set to the desired value (and the information is stored in the TokenStore), the second time the value is no longer available. During the second time we need it to be available to return it in the userinfo response.

**Comment by leastprivilege** [comment]
The GetName method is really only used for the display name inside IdSrv.

When the userinfo call comes in - there is no cookie, so you need to retrieve the name from your data store.
