### ISSUE TITLE
Unable to cast object of type 'Autofac.Core.Lifetime.LifetimeScope' to type 'Autofac.ILifetimeScope'.

### ISSUE THREAD

**Issue by daveraine** [IdentityServer/IdentityServer3#1332]
I've updated my project from IdentityServer3 1.5.5 to 1.6.0 and am now getting the following error during my user login process:

```
System.InvalidCastException: Unable to cast object of type 'Autofac.Core.Lifetime.LifetimeScope' to type 'Autofac.ILifetimeScope'.
   at Microsoft.Owin.OwinContext.Get[T](String key)
   at Autofac.Integration.Owin.OwinContextExtensions.GetAutofacLifetimeScope(IOwinContext context)
   at Autofac.Integration.WebApi.Owin.DependencyScopeHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken )
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
```

In the call stack it originates from ThinkTecture.IdentityServer.AccessTokenValidation.dll, so apologies if this is not the correct place to raise this issue.

```
Thinktecture.IdentityServer3.AccessTokenValidation.dll!Thinktecture.IdentityServer.AccessTokenValidation.ScopeRequirementMiddleware.Invoke(System.Collections.Generic.IDictionary<string,object> env) Line 50	C#
```

My best guess is that it is related to [this commit](https://github.com/IdentityServer/IdentityServer3/commit/91d362ae13b0df8e8458a02665d6c6c77eb5ff5d), changing the way Autofac middleware is registered.

**Comment by brockallen** [comment]
Are you using IdSvr from the NuGet or from the source code?

**Comment by brockallen** [comment]
I just tried to repro the problem with a new app in VS hosting IdSvr loaded from NuGet and I don't see the error you're describing.

**Comment by daveraine** [comment]
It's from the nuget package. I'll try and create a reproduction for you but might have to be Monday when I'm back at work with access to my source code.

**Comment by daveraine** [comment]
I have managed to recreate the issue and believe I have found the cause now. I'm embedding IdentityServer in an existing WebApi project which is configured to use Autofac. Therefore I am setting the WebApi dependency resolver to use my container in my Startup.cs.

```
config.DependencyResolver = new AutofacWebApiDependencyResolver(container);
```

However, [this is already being done](https://github.com/IdentityServer/IdentityServer3/commit/91d362ae13b0df8e8458a02665d6c6c77eb5ff5d#diff-eabf679724b1db39740d70ebbc8145d9R40) from inside IdentityServer, and therefore my container is replacing the one used internally on the dependency resolver, causing the issue.

So I guess it's not recommended to embed IdentityServer inside an existing site, especially if that site is also using Autofac? Is my only option to host IdentityServer in its own site, or is there a way I can inject my registrations into the existing Autofac container so a single one can be used?

**Comment by brockallen** [comment]
Ah, I bet our internalized version of autofac is stepping on your version... we had some similar issues with some parts of Web API. Ok, I'll leave this open as a bug and figure out how to sort it. Thanks.

**Comment by daveraine** [comment]
Perfect, thanks.

I've [uploaded my reproduction of the issue here](https://github.com/daveraine/idsrv_autofac_issue) if it is of any use to you.

**Comment by huysentruitw** [comment]
I have the same problem with 1.6.0. It is because app.UseAutofacMiddleware(IoC.Container); is called twice (once in IdSrv and once in my application)

**Comment by huysentruitw** [comment]
Since Autofac is internalized during the NuGet package build, there is no simple way of merging two containers in one. `UseAutofacMiddleware` can only be called once because they keep a setting in the owin properties.

Any other ideas on how to fix this?

**Comment by bokmadsen** [comment]
I actually just outcommented `UseAutofacMiddleware` in my `Startup.cs` and it still works

**Comment by huysentruitw** [comment]
Maybe because you call it after `UseIdentityServer`? Only the first `UseAutofacMiddleware` actually does something.

**Comment by bokmadsen** [comment]
I actually called it before. I haven't tested all constructors yet, and will see if some part of my application will be missing injection

**Comment by huysentruitw** [comment]
If you call it before `UseIdentityServer` and you're using version 1.6.0, then browsing to any endpoint of the IdentityServer should result in that exception

**Comment by brockallen** [comment]
I will have a fix soon -- I'm currently traveling. Sorry for the delay

**Comment by brockallen** [comment]
Just released a 1.6.1 patch for this. Please try it and report back. Thanks.

**Comment by AnEmptyBliss** [comment]
This has resolved it for me, thanks Brock.

**Comment by brockallen** [comment]
Excellent.

**Comment by daveraine** [comment]
Resolved for me too. Thanks for such a quick fix.

**Comment by huysentruitw** [comment]
While it resolves the issue, it might not be the way you want it, right? Did you only change the name constant of the LifeTimeScope? If yes, then I would prefer to send a PR to autofac so you can register named scopes. What do you think @brockallen ?

**Comment by brockallen** [comment]
I opened an issue for this already with them. We got a little push back (https://github.com/autofac/Autofac.Owin/issues/1), so in the interest of time getting a fix out I did what I did. If I have time I could/would. If you would like to submit a PR to them then go ahead -- I'd happily use it.

**Comment by huysentruitw** [comment]
@brockallen would this one work: https://github.com/autofac/Autofac.Owin/pull/2

I think no change is needed in Autofac.WebApi.Owin right?
