### ISSUE TITLE
Configure idsrv login session lifetime per login request

### ISSUE THREAD

**Issue by scottpickard** [IdentityServer/IdentityServer3#1333]
Is there any way to configure the expiration time for the idsrv authentication cookie per login attempt, perhaps as a result of logic defined in a custom implementation of IUserService?

This would be useful for automated testing to be able to log in with a shorter timeout than we use in production.

**Comment by brockallen** [comment]
Unfortunately not from the built-in login page. We did add an extension method that would allow this from your own custom page: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinExtensions.cs#L124

**Comment by scottpickard** [comment]
What is the extension point for creating a custom login page? Implementing IViewService only allows you to override the views, but in this case we would be overriding logic in the AuthenticationController, correct?

**Comment by brockallen** [comment]
Look into the user service -- that's where you can control the user workflow.
