### ISSUE TITLE
Error while hosting idsrv in asp net web project

### ISSUE THREAD

**Issue by rdzidziguri** [IdentityServer/IdentityServer3#1340]
I have tow separate project for Asp.net Identity and one which hosts IdentityServer as I am using Asp.Net identity 2.1 I run Idsrv without any problem but when I try to redirect user to authenticate against server I get error. I do not understand how to fix this so maybe someone can help me out.

An exception of type 'Autofac.Core.DependencyResolutionException' occurred in Thinktecture.IdentityServer3.dll but was not handled in user code

Additional information: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Vtb.Identity.Core.VtbUserManager' can be invoked with the available services and parameters:

Cannot resolve parameter 'Microsoft.AspNet.Identity.IUserStore`2[Vtb.Identity.Core.VtbUser,System.Int64] store' of constructor 'Void .ctor(Microsoft.AspNet.Identity.IUserStore`2[Vtb.Identity.Core.VtbUser,System.Int64])'.

this is the error I am getting every time I try to redirect user to idsrv. Can anyone tell me what is wrong with this?

**Comment by loctanvo** [comment]
This looks like you are lacking some dependency registration in IdServer. How do you register your dependencies in IdServer? Read more about the [Service Factory in IdServer](http://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html) if you're interested. Have you looked into the [AspNetIdentity sample](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity)?

**Comment by rdzidziguri** [comment]
Okey I managed to fix the issue and its all up and running
