### ISSUE TITLE
identityserver as identity provider for AAD

### ISSUE THREAD

**Issue by martasagra** [IdentityServer/IdentityServer3#1342]
Hi!
Now I'm doing research about identityserver v3 [thinktecture]. I have the question: is it possible to use identityserver as identity provider for AAD (not AAD for identityserver)? We have couple of existed application (webapi, mvc) protected by AAD and now we would like to integrate them with identityserver.
Regards, Marta

**Comment by leastprivilege** [comment]
No. Because AAD doesn't support that.

**Comment by martasagra** [comment]
I found your plugin to WS-federation - https://identityserver.github.io/Documentation/docs/wsFederation/overview.html .  
Will this plugin give me potentialy possibility of the federation with AAD? You have wrote: "IdentityServer has support for the WS-Federation support for both acting as an identity provider as well as allowing external authentication over the WS-Federation protocol." AAD gives possibility of WS-Federation... Or maybe I don't understand something...
M.

**Comment by leastprivilege** [comment]
You can federate idsrv with AAD - but not the other way round. AAD does not support that.

**Comment by leastprivilege** [comment]
more comments or close?

**Comment by martasagra** [comment]
Ok, thank you for your replay.
