### ISSUE TITLE
Separate package for Constants

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer3#1344]
Would it make sense to create a separate project/NuGet package for IdentityServer that only contains some common stuff like the Constants?

Because now, we need to add the complete IdentityServer3 NuGet package to our application for just getting to the ClaimTypes.

What do you guys think?

**Comment by leastprivilege** [comment]
Thinktecture.IdentityModel.Client or the newer IdentityModel has the constants too.

**Comment by huysentruitw** [comment]
Great, thank you!
