### ISSUE TITLE
Problem with access_token size?

### ISSUE THREAD

**Issue by sennaapp** [IdentityServer/IdentityServer3#1345]
We are using Identity Server V3 and we have added customized authorization related claims to access token. Returning those claims from Identity Server is working fine.

The problem appears in authorization of web apis (ASP.Net WebApi 2.2), where access token is delivered in headers. Authorization is working if there are only couple of customized claims, but for few users there may be plenty of them. In that case every api seems to be returning 401. I don't find any other reason for this behaviour than the size of the token. We have used IdentityServerBearerTokenAuthenticationOptions in authorization of web apis.

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44300/",
                RequiredScopes = new[] { "testWebApi" }
            });

So can it be that there is some limitation regarding token size somewhere? We were considering to implement this authorization logic maby in some other way because of the size of token. Maby this is too much information to be handled as claims. But I would need a temporary fix for this, if I can find one.

**Comment by huysentruitw** [comment]
Would writing a custom [`JwtSecurityTokenHandler`](https://msdn.microsoft.com/en-us/library/system.identitymodel.tokens.jwtsecuritytokenhandler%28v=vs.114%29.aspx) help? You can pass your take to the `IdentityServerBearerTokenAuthenticationOptions`.

Then you can decide which claims you want to include in the token and store the other ones in a database or in memory. I think you should override `CreateToken` and `ValidateToken`, but I'm not sure...

**Comment by leastprivilege** [comment]
This has been discussed a couple of times. This is a limitation of the current access token validation endpoint - which is not needed for your scenario.

Set the validation mode to local on the middleware.

**Comment by leastprivilege** [comment]
ok?
