### ISSUE TITLE
Question: ClaimsRule Usage 

### ISSUE THREAD

**Issue by jawadatgithub** [IdentityServer/IdentityServer3#1348]
in Docs: Scope [ClaimsRule](http://identityserver.github.io/Documentation/docs/configuration/scopesAndClaims.html)
> Rule for determining which claims should be included in the token (this is implementation specific)

In samples [here](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/EntityFramework/SelfHost/Migrations/ScopeConfiguration/201502141840088_InitialCreate.cs#L23) its only case where I found usage of ClaimsRule:

```ClaimsRule = c.String(maxLength: 200),```

Can you please explain how to put `ClaimsRule` into practice? or use case where it could be useful?

**Comment by leastprivilege** [comment]
When you implement an IClaimsProvider - you could use this field to "store" some sort of hints for custom logic.

**Comment by jawadatgithub** [comment]
Thanks, I didn't find any info in OIDC specs regarding `ClaimsRule` but through google I found this interesting technet wiki:
[Understanding Claim Rule Language in AD FS 2.0 & Higher](http://social.technet.microsoft.com/wiki/contents/articles/4792.understanding-claim-rule-language-in-ad-fs-2-0-higher.aspx) 

> Claims Rules follow a basic pipeline.  The rules define which claims are accepted, processed, and eventually sent to the relying party.  Claim Rules are defined as a property of the Claims Provider Trust (incoming claims) and the Relying Party Trust (outgoing claims).

I am not sure its related, please confirm if its same concept?

**Comment by leastprivilege** [comment]
This is not really related. It is really is just an extra field that we included if someone wants to implement something like a claims rules "language".

**Comment by jawadatgithub** [comment]
Understood.
