### ISSUE TITLE
Persist Claims For External Users

### ISSUE THREAD

**Issue by pirovorster** [IdentityServer/IdentityServer3#1349]
I am new to IdentityServer. I have completed the mvc walk through and got everything working nicely. However I would like to be able to add new application specific claims to external users and persist it and then automatically add it next time.

A general use case:
UserA logs in through google. IdentityServer now needs to know in the future that this is an actual user in the system (ie I need some way to keep track of all users who has logged in though external providers). Then later some admin comes in and assigns some roles (which translates to claims) to this user. UserA logs in after that and these new claims now needs to be appended to his list of claims. 

I want to do this in the Identity Server itself so that it is transparent to the client of my server.

How do I accomplish this?

**Comment by AnEmptyBliss** [comment]
You would create a custom implementation of the IUserService and in the AuthenticateExternalAsync method (which gets called after successfully authenticating at the external provider), you would deal with persisting details of the user i.e. on a database of some kind (if they don't already exist) or retrieving details of the user (if they've previously logged on). 

Within this persistence layer you could then also add whatever claims you see fit and retrieve them as part of that same AuthenticateExternalAsync when retrieving details of a returning user.

If memory serves the CustomUserService sample pretty much contains an example of this.

**Comment by pirovorster** [comment]
Thank you for the quick response. I will have a look.
