### ISSUE TITLE
Consider a post partial API on user service

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#1353]
To allow changing the auth method (for example, from password to 2fa) or to trigger more partial logins.

PostPartialLogin perhaps

**Comment by mikeandersun** [comment]
+1
Consider abstraction of it so that can use in with MembershipReboot and ASP.NET Identity as the user service.

**Comment by brockallen** [comment]
Done on dev

**Comment by iltera** [comment]
Will there be a documentation about this soon?

**Comment by brockallen** [comment]
Ah, good reminder: https://github.com/IdentityServer/Documentation/issues/86
