### ISSUE TITLE
Any thoughts of supporting the attribute exchange extension?

### ISSUE THREAD

**Issue by justinwatkins** [IdentityServer/IdentityServer3#1354]
I haven't looked into the plugin capabilities too deeply to see how hard this would be as a complete plugin.  It would seem pretty tough to make a standard implementation of this, but having the hooks there to enable you to publish attribute meta and have an attribute interface/api would make offering this extension easier.

**Comment by leastprivilege** [comment]
Which spec is that?

**Comment by brockallen** [comment]
Can we close this?

**Comment by justinwatkins** [comment]
Yep. Its a very old spec.
