### ISSUE TITLE
LoggedOutViewModel is not populated with all fields

### ISSUE THREAD

**Issue by fekberg** [IdentityServer/IdentityServer3#1355]
I've got a custom `IViewService` and when it hits the `LoggedOut` method, only a few fields are populated on the `LoggedOutViewModel`.

It does **not** populate the following:

* ClientName
* RedirectUrl
* CurrentUser

Interestingly enough, it does set `AutoRedirect` to true/false if I change `EnablePostSignOutAutoRedirect` in the `AuthenticationOptions`.

I'm simply hitting this `/identity/connect/endsession?post_logout_redirect_uri=http://www.google.com`, I've got `http://www.google.com` added to the list of accepted post logout redirect urls.

I can't see any errors being thrown, it just doesn't populate the fields.

I verified that the redirect url is valid by doing the following:

```
var validator = new DefaultRedirectUriValidator();
            
var result = validator.IsPostLogoutRedirectUriValidAsync("http://www.google.com", Clients.Get().First()).Result;
```

Any suggestions?

**Comment by loctanvo** [comment]
Are you passing the `id_token_hint`? [Documentation on the endsession endpoint](http://identityserver.github.io/Documentation/docs/endpoints/endSession.html). With a valid id-token, IdServer will be able to tell which application the user is logging out from, and validates that the logout url is valid (as specified for that specific client).

**Comment by fekberg** [comment]
I'm not passing an `id_token_hint`, I hoped it would work without it. I'm using the OAuth 2 Implicit Flow, not OpenId Connect so I don't have an `id_token`.

I saw on a few other discussions that this is not supported yet, but that Token Revocation for OAuth 2 might come in the future.

**Comment by huysentruitw** [comment]
You are using OpenID connect, as OAuth2 doesn't define the endsession endpoint :)

**Comment by leastprivilege** [comment]
Well - OAuth2 has no concept of logout. Since you don't have an id_token - we can't automatically redirect you back.

Revocation is supported. But a bit pointless for implicit clients.

**Comment by leastprivilege** [comment]
more comments or close?

**Comment by fekberg** [comment]
Can probably close, makes sense! Thanks for the input!
