### ISSUE TITLE
Question about the right Flow

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/IdentityServer3#1356]
Hi, 
I'm working on an application that has several clients (mobile and web but both have the same problem).
The web part is a Single Page Application hosted on a CDN that will call protected APIs hosted on another domain using CORS.

The idea is to protect the APIs only to authorised Client and Users, and the security must be compliant with the following scenarios:

- anonymous users from my SPA must be able to call some service with specific scopes;
- logged users from my SPA must be able to call the APIs (scope + profile)
- not authorised client can't call my APIs

I was thinking to use Implicit flow for authenticated users and Client Credentials flow for not authenticated but for this one I should put the secret into the JS and it doesn't seem so good.

What's the best way to cover the scenarios above?

**Comment by jawadatgithub** [comment]
Client Credentials flow doesn't support End User at all. code flow & resource owner flows designed for trusted clients/environments (e.g., MVC app, Intranet environment).

so its recommended to stick with implicit and hybrid flows for Mobile and SPAs.

about Apis: if its MS web Apis, decorate with [anonymous] the methods that you want be accessed anonymously.

if Mobile is native app (differ than SPA), then define two clients in IdentityServer3.
if you want single Implicit Client to act differently in SPA and Mobile, then remember that you can define multiple redirectUris (e.g., when requesting Authorize Endpoint from SPA use RedirectURI-A, and from mobile use RedirectURI-B).

hope this help, please follow up with pending concerns, so we can resolve it.

**Comment by imperugo** [comment]
HI @jawadatgithub 
thanks for the answer. You says to decorate the action/controller with the [anonymous] attribute, but it means my APIs are not protected for that actions.

I'd like to keep my APIs always protected also for not authenticated user (session id or something like that, dunno exactly).

**Comment by johnkors** [comment]
Yeah, you I believe your right (dealing with two sets of access tokens). One on behalf of the logged in user (for example using implicit), and another for the client using client credentials. You would need to do that fetching of access tokens using client creds on the server side, though - as you already mentioned. 

In idsrv, any client can support client creds + another flow, so it's at least doable.

**Comment by jawadatgithub** [comment]
hmm, you said:

> anonymous users from my SPA must be able to call some service with specific scopes;

Anyway, I know three attributes related to access level control:

```
[Authorize]
[AllowAnonymous]
[ResourceAuthorize("action/permission", "resource")] // e.g.,[ResourceAuthorize("search", "SearchApi")]
```

 [ResourceAuthorize](http://www.nuget.org/packages/Thinktecture.IdentityModel.Owin.ResourceAuthorization.WebApi/) is Thinktecture recommended approach.

use cases:
1. if controller decorated with `[Authorize]` then all actions can't be accessed unless user authorized. if some actions need to be accessed anonymously (without authorization) then you need to explicitly decorate that actions with `[AllowAnonymous]`
2. if you want the whole controller to be accessed anonymously except certain actions then don't decorate the controller and decorated actions require authorization with `[Authorize]`
3. `ResourceAuthorize` is really the best option. learn more through docs, issues, videos...

not sure if this answers what you are trying to accomplish.

**Comment by leastprivilege** [comment]
"I was thinking to use Implicit flow for authenticated users and Client Credentials flow for not authenticated but for this one I should put the secret into the JS and it doesn't seem so good."

This is definitely not how the client credentials flow was intended. Where do you store that client credential then?

If you absolutely want that - create an "anonymous" user in idsrv and use that account to get tokens.

**Comment by imperugo** [comment]
Hi @leastprivilege 
I know that client credential is not valid for that, in fact I'm asking the best way to reach my goal. 
I'm really interested to your suggestion about "anonymous" user but, how can I manage that? 
A custom page with a silent login? Idsrv offers something for that?

**Comment by leastprivilege** [comment]
You could pass an additional acr_value to idsrv that you can read from PreAuthenticateAsync - then sign in an anonymous user. 

I am still not sure this is a good idea (haven't thought about it) - but this is how it technically would work.

**Comment by imperugo** [comment]
acr_value???
there is an example into the repo with the samples?

**Comment by brockallen** [comment]
You can read about `acr_values` here: https://identityserver.github.io/Documentation/docs/endpoints/authorization.html
