### ISSUE TITLE
UI for mobile

### ISSUE THREAD

**Issue by pirovorster** [IdentityServer/IdentityServer3#1357]
Questions using IdentityServer for Xamarin authentication:
1) If I use IdentityServer to login using google through my mobile phone does it use the google account that is stored on the phone? What happens if no account is available but google login is available(will it redirect me to a web page)? 
2) How will the consent screen then be display? Is it going to be a web page or is there some more mobile friendly way?
3) If I use a Embedded Identity will I need to use the IdentityServer login web page or is there a better mobile way?

**Comment by leastprivilege** [comment]
What is your problem with the web view? We have a lot of people using the web view and they styled it appropriately so it did look really "native" to the application.

When using the web view approach you only need to implement all logic once (login, register, external logins etc) ... and all your clients get the functionality for "free".

**Comment by brockallen** [comment]
@pirovorster all set? Can we close this?
