### ISSUE TITLE
Skipping Login and Consent view

### ISSUE THREAD

**Issue by pirovorster** [IdentityServer/IdentityServer3#1358]
I would like to know if one can implement the login and consent screen in for example a mobile app using native mobile views and then just post the result to identity server. In effect one would then have to be able to request what Identity Providers are available so that one can display it manually.

Is this possible or am I forced to go through the Identity Server's web interface to do login and consent?

**Comment by jawadatgithub** [comment]
Consent screen can be disabled from configuration as per docs.
If you happy with violating OIDC standard and recommendations, Resource Owner Password flow is the only flow that support Ajax login (but its considered security offending if the client is public/untrusted).
doing Ajax login will disable SSO feature.

as most people I had the mindset of Using seamless Ajax login user experience before I understood the security threat of doing that. So now I am happy with losing fraction of user experience as price to have solid security. I still don't know how Facebook, Twitter..etc Native mobile apps provide seamless login!? maybe they have custom flow or special endpoint!

**Comment by pirovorster** [comment]
So is it then so that you will have to go through the web page if you login
on mobile(following standards)

**Comment by jawadatgithub** [comment]
I am afraid yes, unless you implement custom flow or endpoint that support secure Ajax (yet I have no idea how to do that, and no sample currently available).

about web page, remember that in native apps you can make use of web-views (embedded web browser control), so no need to use default browser app (e.g., safari in iOS). also if you use 3rd party login like facebook, usually it's done through facebook app (I think if user not have facebook app installed then it fallback to default browser).

I hope if other members have more insight or alternatives can highlight some bits...

**Comment by pirovorster** [comment]
Do you know how easy it will be to fork it and make the other flows secure
through Ajax?

**Comment by pirovorster** [comment]
After looking at how Auth0 does it I am thinking that one might be able to
modify IS by doing the same. They also have a web login by calling:

auth0.Login(...)

Or you can say:
auth0.Login("google");
and it the preselects google skipping the visualization.

Or you can say:
auth0.Login(username,password)
and it selects the built in datastore.

One would then just expose a providers endpoint where an application can
enquire which providers are registered to it. You can even probably add it
as some form of claim. A application then has the responsibility of calling
the method with the correct parameters.

**Comment by loctanvo** [comment]
@pirovorster With Auth0, even when you specify the idprovider (or connection as they call it) to be "Google", you still need a redirect to Google. Otherwise, the user doesn't have the possiblity to enter her Google credentials. So under the hood, there must be web view doing this.

If you, from the client, want to specify the id provider to use, this is already supported in IdServer. You can bypass username/password and trigger an authentication straight to a third party provider like FB or Google.

Do you have a very strong argument for using native mobile views rather than a web view in your application like @jawadatgithub mentions? With mobile apps, you probably want the user to log in once, and stay logged in for a very long time. Using `offline_access` and `refresh token` will allow you to do this. In this way, the user almost never see the login and consent screen. When implementing the view service, you can also take custom parameters into consideration. E.g. the mobile application can send additional information causing the view service to render a tailor fit view for the mobile application.

**Comment by pirovorster** [comment]
"With Auth0, even when you specify the idprovider (or connection as they call it) to be "Google", you still need a redirect to Google. Otherwise, the user doesn't have the possiblity to enter her Google credentials. So under the hood, there must be web view doing this."
>> I was hoping that you could use the accounts on the phone to login. ie if you are already logged into the facebook app it will pick that up and wont need authentication again (even the first time). This is not true if you use the web site.

If you, from the client, want to specify the id provider to use, this is already supported in IdServer. You can bypass username/password and trigger an authentication straight to a third party provider like FB or Google.
>>How?

Do you have a very strong argument for using native mobile views rather than a web view in your application like @jawadatgithub mentions?
>>Well my concerns are that the login will be less responsive with using web views. ie the login page will first have to load before it can continue. In addition I am not sure if SSO will work with the added accounts on the phone...

**Comment by jawadatgithub** [comment]
When native app [ios/win-mobile/..] invoke web url to be rendered in browser app (or webview that switch over to browser app) redirectUri use different protocol (no http) (ms-app://, secondApp://)

**Comment by pirovorster** [comment]
I know however the pages on identityserver will still have too load. If I make it controls it will be immediate.

**Comment by jawadatgithub** [comment]
> however the pages on identityserver will still have too load. If I make it controls it will be immediate.
you mean `to load`.
as for `If I make it controls it will be immediate`, I couldn't understand or extract what you mean!
please explain it better.

**Comment by pirovorster** [comment]
Apologies, Yes the load of the login screen

**Comment by jawadatgithub** [comment]
Let me sum up:

To best of my knowledge OAuth2 and OIDC standards doesn't support OUT-OF-THE-BOX **secure AJAX login for public/untrusted clients**. the only non-custom flow that support Ajax login is Resource Owner Password Credential flow but its NOT designed for public/untrusted clients.

I think Auth0 Ajax username & password login, uses custom bits under the hood (yet I didn't find any reference). I also think Instagram doing Ajax login and many others. I suspect the main reason behind that is adopting OAuth2 before OIDC showed up.

Best Advice I can give at this stage:

Trying to understand IdentityServer3 and arrive to decision on how to complete your task WITHOUT playing with samples, reading Docs and searching previous issues is very difficult and not recommended approach _(in my point of view)_. so please pause `looking and reading` phase and start the practice phase.

**Comment by pirovorster** [comment]
Thanks for all the help. I have actually setup a solution that works.
However the stuff I am trying to do now is not in the samples(possibly for
good reason)

**Comment by zahik** [comment]
Hello @pirovorster .
I'm looking for your solution, how to use IdentityServer(4/3) to login without web interface (SSO) for facebook, twitter, google+ etc....
(i need a page with few buttons for each provider)
Can you share here your solution?
Thanks
Zahik
