### ISSUE TITLE
how to modify json response of autodiscovery endpoint 

### ISSUE THREAD

**Issue by sercangurbuz** [IdentityServer/IdentityServer3#1359]
Im using reverse proxy to redirect secure as request to internal server.obviously host name of endpoints in autodiscovery file equals to internal server ip which is not desirable.
what would be the workaround here ?

**Comment by jawadatgithub** [comment]
from [docs](http://identityserver.github.io/Documentation/docs/configuration/identityServerOptions.html) set `PublicOrigin`

**Comment by sercangurbuz** [comment]
thank you.I should have read the docs more carefully before asking. :)

**Comment by sercangurbuz** [comment]
Well,After setting the publicorigin,returnUrl was replaced with the public origin as well.Why ?

**Comment by leastprivilege** [comment]
How else should it work?

**Comment by sercangurbuz** [comment]
Lets say,return url in my authz link is http://localhost:8888/signin.My as server https:/idsrv.com which redirect requests to internal server.Autodiscovery endpoint works great here after setting publicorigin.
However after login completed returned url's host not my registred url.
**My return url I send in authz request => http://localhost:8888/home/signin**
Returned Url =>
**https:/idsrv.com**/home/signin#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InV3blZUM2pCd3J4a3BHYko1emtpQUFRM3k......

Publicorigin works great here but after login i want return teh host which i registred in as as well as what i send in athz link.

What i missing here _?

**Comment by leastprivilege** [comment]
Unless you are hitting a completely new bug - you got something wrong.

We never change the return URL - public origin is only for metadata and link generation between idsrv pages.

**Comment by jawadatgithub** [comment]
1. you are using frontend (reverse proxy) https server, its very bad to redirect to http from https (google it).
2. the idea of using frontend server yield that all internal app requests must pass through frontend, so you are defeating the purpose of your proxy if redirectURI point to internal address.
3. Naturally: redirectUri should be requested with publicOrigin so if user looked to JS code, he/she can't tell where your internal logic hosted.

**Comment by leastprivilege** [comment]
The redirectUri is the callback URI to the client. We don't touch that.

**Comment by sercangurbuz** [comment]
probably im misconfigured the reverse proxy i will focus on it,Thanks again

**Comment by sercangurbuz** [comment]
I fixed the issue,This is related to iis reverse proxy configuration.
For all who hit the same problem,the solution is

Go to the ARR proxy settings (they're hidden under IIS -> Application Request Routing Cache -> Server Proxy Settings) and uncheck the "Reverse rewrite host in response headers" checkbox. That should be enough.

http://stackoverflow.com/questions/4243959/iis-reverse-proxy-with-rewrites-cant-handle-a-redirect-from-the-server-we-proxy

Thanks,Keep up good work
