### ISSUE TITLE
SSO Mobile

### ISSUE THREAD

**Issue by pirovorster** [IdentityServer/IdentityServer3#1360]
If a user is already signed into lets say facebook on his android phone and we have an app that uses IdentityServer, will the user have to sign on again or will it some how pick up that the user is authenticated?

In addition will it use the facebook app (if installed) to authenticate or will it use the web version.

Reason why I ask is if I browse to gmail.com while I am logged in on my phone into google+ it seems to automatically pick up that I am signed in. However facebook does not.

**Comment by leastprivilege** [comment]
It won't automagically use the facebook app - you would need to write code against that API.

In case of using webviews - if the system webview and your webview share cookies - you also share the authentication session.
