### ISSUE TITLE
Custom User repository service for authentication in IdentityServer3

### ISSUE THREAD

**Issue by Prasanth37** [IdentityServer/IdentityServer3#1361]
Hi Dominick,

I am using IdentityServer3 for authenticating my MVC application via OIDC.
I have hosted IdentityServer3 and MVC as two different applications by following your github documentation.

But now I wanted to use my custom user repository service to authenticate the user. From that service I will get boolean result for authentication, based on that I need to update Users authentication info.

Can you please help me out on this. 

Thanks in advance!

**Comment by leastprivilege** [comment]
dude, check docs/samples.
