### ISSUE TITLE
IdToken through Resource owner password flow 

### ISSUE THREAD

**Issue by danutzplusplus** [IdentityServer/IdentityServer3#1362]
Hello,

I've an issue and would like to if this is just not supported, or if I'm doing something wrong.

I've a native app (winforms) and would like to perform token requests from it, using resource owner password flow (sending both client and user credentials) (implicit flow through a webview kind of works, but we don't like having to keep that webview around in order to keep the auth cookie alive).

So, the issue first with establishing identity in the native client. From what I can see IdServer V3 doesn't support issueing idtokens, even if I request openid as a scope. It issues an access token but no id token. Is this not supported? 

The second issue I forsee, (haven't reached that point yet), if the client requests an access token with certain scopes to access certain webapi services, with a refresh token you can only refresh the lifetime of that token, but not change the scopes (which sounds fine from a security point). But then what's the alternative? Either perform the request again (either asking the user again for credentials, or caching them), or make the initial access token request with all the scopes you might need? But then doesn't that make the token highly risky? (if it gets leaked it basically can access a lot of webapi services).

Worst case, I can get the identity from the access token, but then I'm left with not being able to verify the "aud" field on the token. 

Thanks, and I hope someone can clear this for me.

**Comment by jawadatgithub** [comment]
Regarding first issue: Identity Token is OIDC specs concept that's not apply to resource owner flow but in IdentityServer3 you can ask for identity scopes, then use the user endpoint to get user info.
also logout can be achieved through (quoted from @leastprivilege )
> Deleting the access token (and optionally revoke it using the revocation endpoint).

**Comment by danutzplusplus** [comment]
Ok, so if I'm using resource owner password flow I don't need to check the audience field on the token to make sure the token is meant for my particular clientid?

**Comment by leastprivilege** [comment]
The resource owner flow is the only flow in OAuth2 that is somewhat comparable to authentication (since it is a request/response call). When you get back a token you know that authentication succeeded.

You still don't know the claims of the user - that's why you can send the token to the userinfo endoint (given you have requested identity scopes).

**Comment by leastprivilege** [comment]
wrt your second question - to get a token for more or different scopes you need to make another request. I advise against caching the password of the user.

You can use reference tokens instead which can be revoked in case of leakage.

**Comment by danutzplusplus** [comment]
@leastprivilege Thanks for the clarification. 
You mention that to get the claims I have to make an extra request to the userinfo endpoint. Could this be avoided if the only claim I want is the username (which the user already entered in to perform the initial resource owner password flow request) and then just check the token signature/audience/issuer fields locally, on the winforms client?

**Comment by leastprivilege** [comment]
why would you check the token in the client? The token consumer (API) is responsible for that.

**Comment by danutzplusplus** [comment]
Well, because normally I would need to call the userinfo endpoint for the username claim. But since I already have it locally (since the user already entered to login) I would just used that. But doing that would skip the token validation that is done when calling the userinfo endpoint. So I thought I would just validate it on the client. Does that not seem good to you?

**Comment by leastprivilege** [comment]
ok

**Comment by danutzplusplus** [comment]
@leastprivilege So does that seem alright to you? Do you see any vulnerabilities and issues with my approach? Do you think it's necessary to perform the token validation on the client in this case? I'd really like some confirmation if you think this token validation is actually required or is it unnecessary?

**Comment by leastprivilege** [comment]
I would validate the token yes.

**Comment by popcatalin81** [comment]
I think I'm missing something here. 
What would be the benefit to validate a token that you just received from the IdP on the client application if the token is used to make a request to the backend service and is validated there?

In this case it seems to me that you're simply checking that the IdP has signed the token it gave you with the key it said it did.

**Comment by leastprivilege** [comment]
I wasn't sure if the op wants to use the access token at all at a service. Validating it on the client would be good developer hygiene in that case.

**Comment by danutzplusplus** [comment]
Yes, the access token in this case would also be used to call a service. But, it is also used on the client to establish identity. But since resource owner password flow doesn't support idtokens, which are the ones that should be used for establishing identity on the client, I thought about doing as much to mimic their behavior to be as safe as possible. Meaning, validating the token on the client also (signature and appropriate fields).

Without this client validation the vulnerable time-frame I see is if and from the moment the resource owner password flow request is subject to a man-in-the-middle without the client detecting it, and up until it is finally sent to the service which will validate it. And this window would be very small if all data retrieval would be from services that validate that token. But I'm not sure if we can guarantee that they all will do that. Would this be a fair assessment or am I missing something?

**Comment by leastprivilege** [comment]
You need to establish identity if you are protecting resources on the client on behalf of the user. If the client is just a "service frontend" i think it is sufficient to simply forward the token to the API and it will be validated then.
