### ISSUE TITLE
Implement sliding expiration on asp.net webapi2 + sts + angularjs application

### ISSUE THREAD

**Issue by gokulm** [IdentityServer/IdentityServer3#1363]
We have WebAPI2, Thinktecture IdentityServer and AngularJS applications hosted on IIS. Our plan is to set up the webapi2 application stateless. Here is the flow:

Users open our AngularJS application. If not logged in, they get redirected to the login page.
Users enter their credentials, and click login. The credentials get sent to the STS server. If they get authenticated, a JWT gets returned.
AngularJS saves the JWT in the localstorage
To access resources on the WebAPI, angularjs application attaches the JWT on every request.
Before attaching the JWT, it checks the JWT's expiration date. If it hasn't expired, request sent to the API; else, redirected to the login page.
We want the session to be be valid only for 30 minutes. As and when the user does something on the application, the token should slide the expiration datetime. The easiest solution could be enabling sessions for the WebAPI application, but we don't want that. Also, we don't want to get a token before every WebAPI call.

Could we implement sliding sessions/tokens in this scenario? If so, how?

Posted the same on StackOverflow - http://stackoverflow.com/questions/30243681/implement-sliding-expiration-on-asp-net-webapi2-sts-angularjs-application

**Comment by leastprivilege** [comment]
Tokens do not support sliding. You need to do the token management on the client.

See here for a helper library:

https://github.com/IdentityModel/oidc-token-manager

**Comment by gokulm** [comment]
Thanks. I'll look into it.
