### ISSUE TITLE
Generating a token for integration tests

### ISSUE THREAD

**Issue by abhayachauhan** [IdentityServer/IdentityServer3#1364]
Hey guys,

I'm trying to figure out an effective way I can generate a JWT where the test can define the claims to be added in the token for my integration tests.

The integration tests run on the in-memory OWIN server. Both the creation of JWT and accesstokenvalidation are using the same certificate,  but it keeps returning invalid token / unauthorized.

I have configured the middleware for access token validation:

            var assembly = GetType().Assembly;
            X509Certificate2 credentials;
            using (var stream = assembly.GetManifestResourceStream("XXX.CALocksmith.pfx"))
            {
                credentials = new X509Certificate2(ReadStream(stream), "XXX");
            }
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                IssuerName = "http://localhost/identity",
                IssuerCertificate = credentials,
                ValidationMode = ValidationMode.Local
            });

And I am creating the JWT in my integration tests using:

            var signer = new DefaultTokenSigningService(TestIdentityServerOptions.Create());
            var jwt = await signer.SignTokenAsync(TokenFactory.CreateAccessToken(new Client { ClientId = "roclient" }, "valid", 600));

            RequestHeaders.Add("Authorization", "Bearer " + jwt);

            return await OwinTestServer.CreateRequest(Uri)
                        .And(request => request.Content = new ObjectContent(typeof(TModel), model, new JsonMediaTypeFormatter()))
                        .And(request => RequestHeaders.ToList().ForEach((header => request.Headers.Add(header.Key, header.Value))))
                        .SendAsync(method);

    class TestIdentityServerOptions
    {
        public static IdentityServerOptions Create()
        {
            var options = new IdentityServerOptions()
            {
                IssuerUri = "http://localhost/identity",
                RequireSsl = false,
                PublicOrigin = "http://localhost/identity",
                DataProtector = new NoDataProtector()
            };

            var assembly = Assembly.Load("XXX");
            using (var stream = assembly.GetManifestResourceStream("XXX.CALocksmith.pfx"))
            {
                options.SigningCertificate = new X509Certificate2(ReadStream(stream), "XXX");
            }

            return options;
        }

I'm starting to wonder if there is a limitation with in-memory owin server and thinktecture?

**Comment by leastprivilege** [comment]
For starters enable logging.

**Comment by leastprivilege** [comment]
any more comments or close?

**Comment by abhayachauhan** [comment]
After an investigation, I found the issuer did not match on both sides. 

Thanks for the help.
