### ISSUE TITLE
Multiple Audiences in Jwt: does it makes sense?

### ISSUE THREAD

**Issue by rmbrunet** [IdentityServer/IdentityServer3#1365]
Hello,
I am trying to implement the following scenario using IdentityServer: Enterprise environment, multiple clients (web based, JavaScript, native,...) talking to multiple WebApi resources. In my mind I am representing this as a single scope "application" (no need for consent) and many audiences per client depending on the web api resources the client need to access (and controlled by the roles of the user). I forked IdentityServer3.Core and did the following changes: added a list of audiences to Client and Token; modified DefaultTokenService, DefaultTokenSigningService and TokenValidator to allow for multiple audiences in Access Token and, finally modified a couple of tests to pass (because of the change from Audience to Audiences) and added a new test to validate the multi-audience case. Currently all tests are passing. So far I have only tested the Resource Owner Password token endpoint using Postman but intent to check other cases validating the token in each of the secured WebApis.

Does all this makes any sense?

The forked repository is at: https://github.com/rmbrunet/IdentityServer3/tree/multiple_audiences

In a separate note: thank you guys for all the work in IdentityServer; I don't think that exists another real alternative for in house STS (at least in a .Net oriented environment). 

Roberto

**Comment by leastprivilege** [comment]
Well - this does not really make sense. You are rebuilding the scopes feature. Rather create multiple scopes and check them in the receiver.

**Comment by rmbrunet** [comment]
Hello Dominick,

I am not too inclined to disagree with you, but I am going to try it anyway; maybe I can convince you. These are my reasons in no particular order:

1. This is not a breaking change. I would expect to compile from my fork, drop the dll in any current implementation and it should work. Then, scopes are alive and well; no redefining there. And in an Enterprise scenario with very specific clients and resources I don't see a use case for scopes (or consent). 
2. In the generated Jwt access token aud should be the intended recipient(s) or consumers of the token. Hardly, in my opinion, can be the same IdentityServer considered the only intended recipient of the token. I am even not sure that IdentityServer needs to be one of the audiences (but that would be a breaking change).
3. JwtSecurityTokenHandler supports validation against multiple audiences out of the box Nothing special is needed.
4. Today, for the resource server to validate the token it must know three pieces of information from IdentityServer: the issuer, the Public Key and the audience (idsrvv3/resources). The last one does not feels right to me; I would prefer to use the resource own audience.       

Best Regards,

Roberto

**Comment by leastprivilege** [comment]
We had this discussion a couple of times already ;)

Here's my thinking - and the options I can offer.

OAuth2 does not use the term 'audience' (search the spec) - it instead uses the term 'scope'. Semantically they are equivalent (where and for what can the access token be used).

OAuth2 also does not specify any token type - 'audience' and the 'aud' claim are JWT specific concepts. We e.g. also support reference tokens that do not have an audience.

But still - semantically both are the same. We decided to stay true to the OAuth2 spec and use the term scope. I think you are confused that scopes are somehow tied to consent. Consent is an optional feature. First and foremost we use scopes to model resources (and to specify which client can access tokens for which scope).

I also don't see how that would be any different in an enterprise scenario. My main background is enterprise and this works just fine.

Our thinking was this - the audience of an access token are all the resources guarded by this instance of identity server (hence the 'issuername/resources' audience). The scopes are used to sub-divide that space. To be honest - this thinking was influenced by the fact that at that time the JWT handler did not support multiple 'aud' claims.

I agree with you that it is unfortunate that the Microsoft implementation does not allow to validate scopes. Ours does.

So the only 'workaround' for that is to duplicate the scope claims also as 'aud' claims - this way the MS implementation is happy (and maybe you too). This feels a bit wrong to me - but I already considered that. Certainly that would be an optional setting per client.

thoughts?

**Comment by rmbrunet** [comment]
Hello Dominick,

Thanks you for the detailed response. I won't deny potential confusion as it has happened often in the past. Let me try to make it obvious.

Lets forget about the irrelevant (to this issue) things: like Enterprise environment (where the resource really don't belong to the user but to the company; or the consent screen. It is not about these things. 

OAuth2 says nothing about audiences; but Jwt says a lot. Jwt says that the token can have multiple - or one - audiences; it also says that the recipients of the tokens should validate that they are included in the audiences and reject the token if they are not. It seems that MS implementation of JwtSecurityTokenHandler is very much following the spec. The fact that OAuth2 says nothing about audiences is, in my opinion, very good because give us freedom to fill the aud claim however we want to make Jwt happy.

I don't see scopes and audiences as semantically the same; and they don't need to be to comply with both OAuth2 and Jwt. In my mind, audiences are the identifiers of the consumers of the token; very much like the what client_id is for the client. While 'read' and 'write' would be scopes, 'some_api', 'image_server', "googleapi.com" or some GUID identifying the resource server would be audiences. The fact that the client_id is the audience in the Jwt Id token supports this point of view because the client is the consumer of the Identity Token.

Today, when validating an IdentityServer access token in a resource server (webapi, for example) I can answer the question "Is this token valid?" but I can't answer the "Is this token for me?" one. Or better said, I can't do what the Jwt spec asks me to do (validate the resource audience).

Yes, I could go and define scopes for each one of the resource servers involved (and probably put some restrictions in the Clients) and validate the corresponding claim in the consumer of the token. And it will work. But for me it doesn't feel totally right. 

Considering that multiple audiences were not available in the initial MS implementation I completely understand the necessity of using scopes to handle multiple access token consumers. But now that it is available can something be done about it? I was surprised with my little experiment that only modifying Client (and in a non-breaking backward compatible way) I could get audiences into the resulting access token. And it feels OK in the sense that the real clients (the apps no the record in IdentityServer) already know about the resource servers anyway (as they are calling them).

If you agree that the aud claim of the access token can be filled in any way we want (and still comply with both OAuth2 and Jwt specs), then it really doesn't matter if a list of audiences is attached to the client or if some particular group scopes end up in the aud claim. But do we want 'read' and 'write' to end up in the aud?

I hope I expressed my (right or wrong) ideas in a clear way and this conversation is not a waste of time for you. I am enjoying it.

Best Regards,

Roberto

**Comment by leastprivilege** [comment]
"I don't see scopes and audiences as semantically the same"

Then we disagree.

"and they don't need to be to comply with both OAuth2 and Jwt"

don't understand this part though.

"In my mind, audiences are the identifiers of the consumers of the token; very much like the what client_id is for the client. While 'read' and 'write' would be scopes, 'some_api', 'image_server', "googleapi.com" or some GUID identifying the resource server would be audiences."

Which is the same as scopes. Compare to e.g. https://developers.google.com/oauthplayground/

"Today, when validating an IdentityServer access token in a resource server (webapi, for example) I can answer the question "Is this token valid?" but I can't answer the "Is this token for me?" one. Or better said, I can't do what the Jwt spec asks me to do (validate the resource audience)."

Wrong - today the aud claim tells you if the resource belongs to the specific identity server - and the scope claims tell you the "is the token for me" part.

"Yes, I could go and define scopes for each one of the resource servers involved (and probably put some restrictions in the Clients) and validate the corresponding claim in the consumer of the token. And it will work. But for me it doesn't feel totally right."

This is how IdentityServer works. I guess you have to accept that or build your own.

As I said - I could imagine duplicating the scopes as aud claims. But that's as far as it will go. Scopes are the primary mechanism. Audiences are JWT specific.

"I was surprised with my little experiment that only modifying Client (and in a non-breaking backward compatible way) I could get audiences into the resulting access token."

and

"If you agree that the aud claim of the access token can be filled in any way we want (and still comply with both OAuth2 and Jwt specs), then it really doesn't matter if a list of audiences is attached to the client or if some particular group scopes end up in the aud claim. But do we want 'read' and 'write' to end up in the aud?"

Confuses - maybe you need to explain how your audience and token management works in your version of identity server. Or how you envision this to be done the right way.

**Comment by rmbrunet** [comment]
OK, let me see it the way you have been saying: scope = audience. 

Then, we have a list of api resources in the Scope Store and, probably, some scope restrictions in each client. 

If these **resource** scopes are included in the access token audience (as you suggested in the 'workaround') then JwtSecurityTokenHandler will validate against the audiences (IdentityServer could also validate against its own 'scope' in the validation endpoint). The issue remains of the duplication.  of the resource scope claims. it is necessary?

**Comment by leastprivilege** [comment]
No it isn't - we don't need the audience - just use the scope claims :p

**Comment by leastprivilege** [comment]
So since we are going in circles here - you still owe me an explanation of how your mechanism works - how do you request to which resources you want to have access - where does the audience value come from etc ...

**Comment by rmbrunet** [comment]
Let me try to answer your question. 

My starting points were: 

a) Trying to get a resource specific audience(s) in the token to be used in validation (and to get in line with the Jwt spec).

b) What to do in the particular case of an Enterprise environment where the client is coupled with the resources and there seems to be no need to ask for some specific scope. Furthermore, and I wasn't thinking about that, maybe you just don't want to expose the internal structure in the scope (for example in a JavaScript app). It is like saying, give me access to all the resources that this application is intended to have, without specifying them explicitly in the call.

About a), my initial idea was to store this audiences together with the Client and to use them to generate the aud in the access token. That is what I did in the fork mentioned in the initial message. I used an Audiences field in Client.cs to generate a list of audiences in the Token class and finally in the access Jwt token. This is where you said "Wrong, you should use the ScopeStore and scope restrictions". Then, today I am fine with "all Resource Scopes should go into the access token aud".  

This will work well with the current JwtSecurityTokenHandler where is no problem in a)creating a muti-audience token and b)validating one audience against the list. 

With respect to point b) above, reading OAuth it appears that the client could just omit the scope and the server should validate against some default value. Tt sounds reasonable in this case.

Regards.

**Comment by leastprivilege** [comment]
In our implementation the client has to tell us to which resources (aka scopes) he wants access to. That is not exotic at all (even if the scope parameter is optional in the spec) - compare to any other protocol like WS-Fed, SAML, WS-Trust etc.

Those requested resources will be reflected in scope claims in the access token. Maybe I am adding an option to duplicate the scope claims as aud claims. But this is not really high on the priority list right now.

**Comment by rmbrunet** [comment]
i appreciate the time you took to answer my questions.

The normal been explicit scopes, no scope would be, imo, more 'exotic'. I have seen other options. If I recall correctly Salesforce uses a 'full' scope as the Mother of All Scopes or something like that.

To be honest, I don't know if duplicating the scope claims in the audience is a good idea because introduces some uncertainty in the validation of the token. Maybe an option to copy in one place or the other (defaulting to the current one) or just leaving it like it is right now as the IdentityServer implementation is better than duplicate the claims.

Thanks again. As far as I am concern you can close this issue.

**Comment by leastprivilege** [comment]
So you agree with me now? ;)

Or do you have suggestions for improvements?

**Comment by rmbrunet** [comment]
I think there is little disagreement left. The most important thing that I have learned is that "when using OAuth with Jwt scope and audience is basically the same thing". In this respect, in the samples I would use nouns instead of verbs (**read_api** instead of **read**, **write_api** instead of **write**) just to make the equivalence totally obvious.

I also think that is unfortunate but understandable that, for historical reasons, the generated access_token only has the IdSrv3 audience. I would prefer to have a totally decoupled token validation possibility (I mean without the extra instruction of "go and validate the scope"). Maybe I am just been foolish in not liking the duplication of claims that you suggested; "duplication" is just such a bad word... but how many scope/audiences will a client have in real life? Probably not many anyway. On the other hand, probably most users are validating the tokens with the validation endpoint and any breaking change -like not duplicating- would be transparent for them. These are just thoughts, no disagreement here...

The non-mandatory/default scope in the request seems interesting to me in cases where, for whatever reason, is better not to expose the resource servers structure. But nothing is stopping me today to use GUIDs as scopes with basically the same result.

If I go back to the messages in search for some real disagreement maybe the only one is that you seems to think that JwtTokenSecurityHandler should validate scopes and I think it is just fine validating audience(s).

**Comment by rmbrunet** [comment]
Facepalm: after I capitulated in the scope==audience issue my problems dissipated. I think I can do exactly what I want by just inheriting DefaultTokenSigningService and generating the access_token with the audiences. As long as the original IDSrv3 audience is still there even the validation endpoint will work.

**Comment by rmbrunet** [comment]
Small successful test with:

<code>
    public class MyTokenSigningService : DefaultTokenSigningService {

        public MyTokenSigningService(IdentityServerOptions options) : base(options) { }

        protected override string CreateJsonWebToken(
            Thinktecture.IdentityServer.Core.Models.Token token,
            System.IdentityModel.Tokens.SigningCredentials credentials) {


            if (token.Type == Constants.TokenTypes.AccessToken) {

                var claims = new List<Claim> { new Claim(Constants.ClaimTypes.Audience, token.Audience) };

                //The resource scopes
                claims.AddRange(token.Claims.Where(c => c.Type == Constants.ClaimTypes.Scope && !Constants.ScopeToClaimsMapping.ContainsKey(c.Value)).Select( c => new Claim(Constants.ClaimTypes.Audience, c.Value)));
                //Leave the Standard Scopes
                claims.AddRange(token.Claims.Where(c => c.Type == Constants.ClaimTypes.Scope && Constants.ScopeToClaimsMapping.ContainsKey(c.Value)));
                // Rest of claims
                claims.AddRange(token.Claims.Where(c => c.Type != Constants.ClaimTypes.Scope));

                token.Audience = null;
                token.Claims = claims;
            }

            return base.CreateJsonWebToken(token, credentials);
        }

    }
</code>

**Comment by Mich-b** [comment]
Will this be revisited based on the latest draft? I quote: "The semantics of such a request are that the client is asking for a token with the requested scope that is usable at all the requested target services. Effectively, the requested access rights of the token are the cartesian product of all the scopes at all the target services."

https://tools.ietf.org/pdf/draft-ietf-oauth-token-exchange-08.pdf

**Comment by Mich-b** [comment]
To me, this implies that the actual recipient(s) of the token should be mentioned in the audience field, whereas the scope limits the actual access. The fact that the scope should be usable at all recipients implies that the target recipients cannot be simply listed as one of the scopes.

It seems that 'audience' in this new draft is consistent with the use of audience in JWT. 

Or do you see this otherwise?
