### ISSUE TITLE
Identity Server and Windows Authentication

### ISSUE THREAD

**Issue by aronblum** [IdentityServer/IdentityServer3#1366]
Hi,

I was hoping someone could direct me to an existing project that implements Windows Auth through Identity Server. Or if anyone has any tips as to where I could start with implementing this.

Thanks a lot,

Aron

**Comment by rmbrunet** [comment]
Aron, I have done something like that implementing IUserService, using PrincipalContext.ValidateCredentials for local Authenticatication and LDAP query to fill the Identity Claims.

hth

Roberto

**Comment by aronblum** [comment]
Hi Roberto,

Do you have a link to your code so I can see a sample of your implementation?

Thanks,

Aron

**Comment by rmbrunet** [comment]
Hi Aron, Probably you already resolved this but just in case I created a gist with some ADUserService implementation. The url is: https://gist.github.com/rmbrunet/6c5c2ba2b8fb03fbc359

R.

**Comment by leastprivilege** [comment]
If you want integrated authN - see here (no docs so far sorry):

https://github.com/IdentityServer/WindowsAuthentication

closing this issue.

**Comment by stefan89** [comment]
@rmbrunet would you please share your working project (with a working AD connection) with us?
