### ISSUE TITLE
In the MVC tutorial, when I UpdateContact, I get

### ISSUE THREAD

**Issue by tofutim** [IdentityServer/IdentityServer3#1369]
http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html

When I try to go to home/updatecontact, whether I am logged on or not, I get 

![2015-05-18_1734](https://cloud.githubusercontent.com/assets/157766/7693298/2e8d9910-fd84-11e4-9de1-cee64884b162.png)

		
```
[ResourceAuthorize("Write", "ContactDetails")]
		[HandleForbidden]
		public ActionResult UpdateContact()
		{
			ViewBag.Message = "Upate your contact details!";

			return View();
		}
```

**Comment by leastprivilege** [comment]
is that fixed? looks like some setup problem on your machine.
