### ISSUE TITLE
Obtain redirect url / automatically login local user after registration

### ISSUE THREAD

**Issue by gavinharriss** [IdentityServer/IdentityServer3#1370]
Question: Please can you give me a little guidance on how to automatically login a local user after registration (I've added the functionality alongside the SSO).

I've tried lots of different ideas but have not managed to find a way to do this successfully yet without getting the user to login after the registration process.

In case it helps some extra detail can be found here:
http://stackoverflow.com/questions/30228359/automatically-login-local-user-after-registration-with-identityserver3

Thanks in advance for any advice / pointers you can give me.

**Comment by brockallen** [comment]
We added an extension method for this:

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinExtensions.cs#L124

**Comment by gavinharriss** [comment]
Thanks for that - very much appreciated!
