### ISSUE TITLE
RedirectUris with callback params does not work.

### ISSUE THREAD

**Issue by rdzidziguri** [IdentityServer/IdentityServer3#1371]
In our implementation of identity server everything works as it should be. the only problem we faced with for now is the problem related to RedirectUris property of client. if we write https://localhost:44303 as one of the item for client allowed Uris when it only works if client specifies it exactly in same way. but if client uses https://localhost:44303?aditinalparam=5&item1=7&meth=ewrsdadsa identity server shows error about unauthorized client. those parameters needs to be optional so client can provide any additional parameters which should be echoed back to the client after successful authentication of the user. how can we achieve this functionality?

**Comment by brockallen** [comment]
If you need to maintain state across the redirects, then issue a cookie client side or pass data via the official state param.

**Comment by rdzidziguri** [comment]
Can you please provide some additional info abut either cookie usage as I do not have access to URL or using state param? redirection of the client back to the client app is managed automatically so I will not be able to somehow add params to redirection url to which identity server is going to redirec user to.

**Comment by brockallen** [comment]
I'd suggest reading up on your web framework on how to do that.

**Comment by rdzidziguri** [comment]
Reading up on my web framework? what do you mean its ASP.NET MVC.

**Comment by brockallen** [comment]
Ok, so then issue a cookie with MVC. Or if you're using Katana to redirect, then add your state to the properties dictionary when redirecting. Those are documented by Microsoft.

**Comment by rdzidziguri** [comment]
So your point is that there is nothing to do with identity server so Client app should to this. OK that might be acceptable if it is our own applications but we do not want to force clients to go with that way. is there any way we could implement this functionality within identity server?

**Comment by leastprivilege** [comment]
Actually the specification says you should do an exact match when validating the redirect URI. That's why the state parameter exists.

All of the "popular" OAuth2 hacks were done by bypassing too relaxed redirect URI validation. Are you really sure you want to go that way?

**Comment by rdzidziguri** [comment]
Well absolutely agree with you to make it comfortable it is not acceptable for us to reject any security of the system. What I was interested in was how state param can be used while redirecting to achiev this functionality? just put 'value=5&value8=sadsadsa&someothervalue=1" as its value? or encrypt and encode those parameters as base65 string it to achieve better security?

**Comment by leastprivilege** [comment]
You generally want to use the state parameter as a pointer to locally persisted data - e.g. a cookie.

Create a cookie with a random name - store whatever needs to be stored there - round trip the cookie name as the state parameter.

Just putting data on state has the issue that someone could potentially modify the values on the way back.

security is hard.

**Comment by leastprivilege** [comment]
Funnily - this just happened on the OAuth2 Working Group mailing list:

I think the correct answer is that clients should always assume exact redirect_uri matching, and servers should always enforce it. 

Anything else is asking for trouble.

If clients need to maintain some state the correct thing to do is use the state parameter, and not append extra path or query elements to there redirect_uri.

A significant number of security problems in the wild come from servers not enforcing this.

I may be taking an excessively hard line, but partial matching is not something we should be encouraging by making easier.

I did do a draft on a way to safely use state https://tools.ietf.org/id/draft-bradley-oauth-jwt-encoded-state-04.txt

**Comment by rdzidziguri** [comment]
I totally agree with you and because security is so hard I opened new issue here with ID 1392 as We came across some real security problem after one of our clients called as today with information about profile data being exposed and decrypted without any problems and they are using implicit flow.

**Comment by coreyperkins** [comment]
Is this why if I make an ajax call and it needs to auth/redirect again (because I've sat on the page long enough to let my session expire) it will redirect to the url in the ajax call without a query string?

Seems to make sense, I just wanted to confirm.

Thanks!

**Comment by MNF** [comment]
@leastprivilege Dominick, do you have [code example how to remember QueryString parameters to be used after redirect](https://stackoverflow.com/questions/44350529/identityserver-client-example-to-remember-querystring-parameters-after-redirect)?
