### ISSUE TITLE
Thinktecture.IdentityServer3 and Thinktecture.IdentityModel is unsigned

### ISSUE THREAD

**Issue by kishoreabhishek** [IdentityServer/IdentityServer3#1372]
Hi,

Thinktecture.IdentityServer3 and Thinktecture.IdentityModel packages downloaded from nuget are unsigned. Can you please release the signed version of these package.

**Comment by leastprivilege** [comment]
What do you mean with signed? strong names or authenticode? and why?

**Comment by kishoreabhishek** [comment]
I mean strong name. In my application, I am signing assemblies with strong name. My application is usingThinktectureIdentityServer3.dll. Strongly named assemblies can refer to only those assemblies which themseleves are strongly named. Since ThinktectureIdentityServer3 is not strongly named , I am unable to sign my assembly(which references ThinktectureIdentityServer3 ) with a strong name.

**Comment by leastprivilege** [comment]
No we won't sign our assemblies. This is a relict of the past and has no security advantages whatsoever.

**Comment by leastprivilege** [comment]
any comments or close?

**Comment by kishoreabhishek** [comment]
My comment is that strong name is used to verify the integrity of the code, strong name was never intended to provider security against hacking or modification. It is just a way to verify that the code a solution expects is same as the one present in assembly. Even Microsoft's assemblies for OWIN which are quite new are also signed so why should you not.

**Comment by leastprivilege** [comment]
You mean like CRC checking? Strong names wouldn't help here either.

Anyways strong names are a major pain especially when combined with nuget (assembly redirects on updates etc). We won't go there.

**Comment by avivanoff** [comment]
But not strong naming your assemblies, you force your clients to not strong name as well.
