### ISSUE TITLE
X509Certificate2Extensions.IsPrivateAccessAllowed() destroys PrivateKey on Mono

### ISSUE THREAD

**Issue by et1975** [IdentityServer/IdentityServer3#1373]
```csharp
 using (var pk = cert.PrivateKey)
                {
                    return true;
                }
```
Why is it "using"?!

**Comment by leastprivilege** [comment]
What does "destroy" mean?

On Windows the private key wraps a native handle - thus the cleanup.

**Comment by et1975** [comment]
The PrivateKey propery is Null after this operation. Looking at MS implementation X509Certificate2 internally keeps a reference to the instance, which implies it is meant to be reused.

**Comment by leastprivilege** [comment]
But this instance is not used anymore - so what is the issue?

**Comment by leastprivilege** [comment]
Oh I see - it is used afterwards.

Not an issue on Windows.

**Comment by et1975** [comment]
Here's an example of [MS code working with PrivateKey](http://dotnetframework.org/default.aspx/4@0/4@0/DEVDIV_TFS/Dev10/Releases/RTMRel/ndp/cdf/src/WCF/IdentityModel/System/IdentityModel/Tokens/X509AsymmetricSecurityKey@cs/1305376/X509AsymmetricSecurityKey@cs) , you'll notice, nothing is treating the object returned by the property as if is owned by the caller (i.e. disposable).

**Comment by leastprivilege** [comment]
OK. I will look into it.

**Comment by leastprivilege** [comment]
Can you confirm that removing the using statement fixes the problem?

**Comment by leastprivilege** [comment]
oh - and which Mono version is that?

**Comment by et1975** [comment]
Yes, once "using" is removed it works on mono 4.0.1. Mono 3.12 doesn't have enough in System.IdentityModel, it seems.

**Comment by et1975** [comment]
However, I've hit a subsequent discrepancy: on mono [TokenValidator]( https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/TokenValidator.cs#L153)
receives a single value for type "scope" containing all the scopes passed - "[openid ...]", instead of implied collection (one value for for each scope). Any suggestions how to address this discrepancy?

**Comment by ryan1234** [comment]
Haha. I feel like we're twins. I've run into the _exact_ same issue again! We're 3 for 3. 

http://stackoverflow.com/questions/30382464/thinktecture-insufficient-scope-error-singular-scope-claim-versus-list-of-sco

Been going crazy trying to resolve that. If I pass just "openid" it's fine. Arrays make it choke.

**Comment by leastprivilege** [comment]
That would be a pretty basic bug in mono - have you debugged it?

**Comment by ryan1234** [comment]
Working on it. Filed an issue with the MS library but doing my own investigation. Was hoping someone would beat me to it. :)

**Comment by ryan1234** [comment]
Ok submitted a PR to fix the bug. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/153.

Hopefully we can get it fixed either with the PR or someone has a better idea how to fix it.

**Comment by leastprivilege** [comment]
I pinged someone at Microsoft - maybe they prioritize it.

**Comment by ryan1234** [comment]
Working with a guy on my PR. They seem more than happy to take it assuming I can get my tests dialed. =)

**Comment by jonathankarsh** [comment]
On the original topic, removing the `using` statement.. Working on mono, we've had to apply this change to our fork of idsrv. Wanted to bump this up, looks like now that 2.0 is out, it's acceptable to raise a PR with this change in it (..?). @et1975 any chances you have capacity for this change?
My motivation is the desire to run an official build of idsrv.
Thanks

**Comment by leastprivilege** [comment]
I made the change - can you give it a try?

https://github.com/IdentityServer/IdentityServer3/commit/e786ba49086dc14c4b3e8774841a9b8f34c23287

the nuget is on myget.

**Comment by ryan1234** [comment]
We will check it out on our end in a few days. Thanks!

**Comment by jonathankarsh** [comment]
Thanks for putting this through.
OK have tried running an IdentityServer application on mono 4.0.1, 4.0.2 and 4.0.3 all successfully start up and issue JWT tokens.
I've also successfully tested a few of the sample applications / clients with this setup.

BTW I thought we could use the new `IDataProtector` feature in `IdentityServerOptions`, specifically `X509CertificateDataProtector`, but there's still some gaps in mono's System.IdentityModel preventing this option. Not an IdentityServer issue of course.

So in summary - All good!

**Comment by jonathankarsh** [comment]
Please ignore the `X509CertificateDataProtector` stuff - I thought it's new, but this was added and already discussed in the mono context ages ago, #555

**Comment by leastprivilege** [comment]
Could you do use a favour? Could you write up a beginner's guide "how to run identityserver3 v2 on mono from scratch" - either as a blog post or just an .md file?

So we can link to it from our docs. thanks!

**Comment by jonathankarsh** [comment]
Would love to, for sure, but this might be a few weeks away

**Comment by ryan1234** [comment]
Started on it, but realized we haven't made the switch to 2.0.0 yet, so running into some fun issues. Basing the work on https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNet5Host.

Getting an `ReflectionTypeLoadException: The classes in the module cannot be loaded.` error. 

The error pointed me to: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/Hosting/WebApiConfig.cs#L75. 

Curious if anyone has ideas. Otherwise going to take some serious digging.

**Comment by leastprivilege** [comment]
This is unrelated to the original issue. Open a new one.

**Comment by jonathankarsh** [comment]
@ryan1234 let me know if you've opened a new issue for this. From your exception description above I'd say this is very similar to https://github.com/IdentityServer/IdentityServer3/issues/1443, maybe that helps...

**Comment by ryan1234** [comment]
Wrote up how to run IDP v3 2.0.1 from scratch on Mono. http://softentropy.com/2015/09/20/thinktecture-identity-provider-2-0-1-on-mono/. Hope it helps.

**Comment by leastprivilege** [comment]
Thanks! Could you remove the thinktecture though?

**Comment by brockallen** [comment]
@ryan1234 Yea, that's the one point of feedback -- IdentityServer no longer has the name "thinktecture" in it anywhere anymore (and IdentityServer is not officially from the company that is thinktecture).

**Comment by ryan1234** [comment]
Sorry about that. Was a little confused I guess.  http://softentropy.com/2015/09/20/identity-provider-2-0-1-on-mono/

**Comment by leastprivilege** [comment]
and it is called IdentityServer not "identity provider"

**Comment by ryan1234** [comment]
http://softentropy.com/2015/09/20/identityserver-2-0-1-on-mono/

**Comment by leastprivilege** [comment]
thanks ;) I added it to our docs

**Comment by leastprivilege** [comment]
I would still be interested in a walkthrough for setting up IdSrv on plain Mono 4.x - no DNX -- @jonathankarsh
