### ISSUE TITLE
Redirect to login after successfull ADFS authentication

### ISSUE THREAD

**Issue by michaelbeckersgit** [IdentityServer/IdentityServer3#1374]
Hi,

I'm trying to integrate ADFS as external identity provider in my implementation of Identity server. But I'm experiencing a rather strange issue.  I think there is nothing wrong with the configuration of the WSFederation middleware because the authentication was successful. I assume this, because I enter in the AuthenticateExternalAsync with an identity with IsAuthenticated set to true and with the subject or name as I used to authenticate with.  I have other external identity providers using the same code with success.

The AuthenticateExternalAsync returns an AuthenticateResult with the subject, name, claims and the name of the provider, where the claims hold a User identity that has IsAuthenticated set to true.  After that he redirects back to to identity server (/connect/authorize/?....), but when he comes back in the AuthorizeEndpointController.Get the User property has an identity that is not authenticated and he redirects back to the login page.

Does anyone have an idea what I did wrong?

This is the log of idsrv:

Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator: Authorize request validation success
 {
  "RedirectUri": "http://xxxx/application/framework/frame/default.aspx",
  "ResponseType": "id_token token",
  "ResponseMode": "form_post",
  "Flow": "Implicit",
  "RequestedScopes": "openid ex:read ex:write ex:public ex:private",
  "State": "aHR0cDovL3RmYmVtZTAxOTcvZXhpbWl1cy5hcHBsaWNhdGlvbi9mcmFtZXdvcmsvZnJhbWUvZGVmYXVsdC5hc3B4",
  "Nonce": "892a08e379964f61839d878a6362089e",
  "Raw": {
    "client_id": "eximius.legacy",
    "response_type": "id_token token",
    "scope": "openid ex:read ex:write ex:public ex:private",
    "redirect_uri": "http://xxxx/application/framework/frame/default.aspx",
    "response_mode": "form_post",
    "state": "aHR0cDovL3RmYmVtZTAxOTcvZXhpbWl1cy5hcHBsaWNhdGlvbi9mcmFtZXdvcmsvZnJhbWUvZGVmYXVsdC5hc3B4",
    "nonce": "892a08e379964f61839d878a6362089e"
  }
}
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeInteractionResponseGenerator: User is not authenticated. Redirecting to login.
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController: End authorize request
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Results.LoginResult: Redirecting to login page
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: Login page requested
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: rendering login page
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: External login requested for provider: WSFederation
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: Triggering challenge for external identity provider
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: External login requested for provider: WSFederation
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: Triggering challenge for external identity provider
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: Callback invoked from external identity provider
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: external user provider: WSFederation, provider ID: michael.beckers
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: External identity successfully validated by user service
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: issuing cookie
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: redirecting to: http://tfbeme0197/eXimius.Api/identity/connect/authorize?client_id=eximius.legacy&response_type=id_token token&scope=openid ex:read ex:write ex:public ex:private&redirect_uri=http:%2F%2Fxxxx%2F.application%2Fframework%2Fframe%2Fdefault.aspx&response_mode=form_post&state=aHR0cDovL3RmYmVtZTAxOTcvZXhpbWl1cy5hcHBsaWNhdGlvbi9mcmFtZXdvcmsvZnJhbWUvZGVmYXVsdC5hc3B4&nonce=892a08e379964f61839d878a6362089e
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController: Start authorize request
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator: Start authorize request protocol validation
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator: Authorize request validation success
 {
  "RedirectUri": "http://xxxx/application/framework/frame/default.aspx",
  "ResponseType": "id_token token",
  "ResponseMode": "form_post",
  "Flow": "Implicit",
  "RequestedScopes": "openid ex:read ex:write ex:public ex:private",
  "State": "aHR0cDovL3RmYmVtZTAxOTcvZXhpbWl1cy5hcHBsaWNhdGlvbi9mcmFtZXdvcmsvZnJhbWUvZGVmYXVsdC5hc3B4",
  "Nonce": "892a08e379964f61839d878a6362089e",
  "Raw": {
    "client_id": "eximius.legacy",
    "response_type": "id_token token",
    "scope": "openid ex:read ex:write ex:public ex:private",
    "redirect_uri": "http://xxxx/application/framework/frame/default.aspx",
    "response_mode": "form_post",
    "state": "aHR0cDovL3RmYmVtZTAxOTcvZXhpbWl1cy5hcHBsaWNhdGlvbi9mcmFtZXdvcmsvZnJhbWUvZGVmYXVsdC5hc3B4",
    "nonce": "892a08e379964f61839d878a6362089e"
  }
}
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeInteractionResponseGenerator: User is not authenticated. Redirecting to login.
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController: End authorize request
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Results.LoginResult: Redirecting to login page
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: Login page requested
Thinktecture.IdentityServer Information: 0 : Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: rendering login page

**Comment by brockallen** [comment]
Watch the cookies to ensure they're not getting lost. If they are, then that's the thing to look into.

**Comment by michaelbeckersgit** [comment]
Problem is solved, the application endpoint in ADFS was configured with https (mandatory) and the test application was running in http.

Thanks for the quick response.
