### ISSUE TITLE
Hosting Identity server in Cloud

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1375]
Hi ,

My requirement is to deploy identity server in cloud so that it is available for multiple applications to interact with each other to get the tokens, authenticate and authorize.

Please suggest me what are the deployment steps are required for identity server work properly.

**Comment by leastprivilege** [comment]
There are no special considerations besides the normal ones.

Here's a doc page - feel free to add information to it if you run in any hosting specific problems.

https://identityserver.github.io/Documentation/docs/advanced/deployment.html

**Comment by dhanutpk** [comment]
We will be having webfarm deployment mechanism. We will be hosting identity server into two web server and web client into two web servers. To support token generation and validation token we should have synchronized machine key in all these web servers right.?

**Comment by leastprivilege** [comment]
Yes - isn't that what the doc page says?

**Comment by dhanutpk** [comment]
Thank you. :)
