### ISSUE TITLE
Federation Gateway (RP-STS)

### ISSUE THREAD

**Issue by schoesler** [IdentityServer/IdentityServer3#1376]
Hi,

We want to add SSO to a MVC web application. Login information is from multiple ADFS servers. We don't want a direct integration from Web app to ADFS. We want to build a Federation Gateway (RP-STS). In Identity server v2 this was possible (Dominick demoed this on a video). But can we do the same with version3?

Can we use the "WebHost (minimal)" example as a starting point for our gateway? The in memory factory is working, we can authenticate with the users alice and bob. But how do we make the "WebHost (minimal)" talk to our external ADFS?

Thanks

**Comment by leastprivilege** [comment]
check the docs ;)

https://identityserver.github.io/Documentation/docs/configuration/identityProviders.html
