### ISSUE TITLE
Would this be a proper way to use code flow?

### ISSUE THREAD

**Issue by rklachko** [IdentityServer/IdentityServer3#1377]
Would this be a valid way to use code flow:
Using code flow, exchanging the code into a reference token on the back channel then passing the reference token to the front channel and use it there to directly call the API (sending the reference token as Bearer token)? 
Or does it totally defeats the purpose of using code flow since the access token is kept on the front channel (user-agent).
If it's valid what would be the recommended way to pass it from back to front, and what would be the best way to store it on the front?

**Comment by leastprivilege** [comment]
you can also use straight implicit flow to get the reference token on the front channel.

**Comment by rklachko** [comment]
Would implicit flow be less secured than using the code flow as I described above (Since code flow also enables me client validation) ?

**Comment by rklachko** [comment]
I guess I'm trying to understand if I lose the security benefits of code flow, the moment I pass the access token to the front channel?

**Comment by leastprivilege** [comment]
Code flow is designed for server side applications (e.g. to enable refresh tokens). That's where all the discussion started if you remember. 

I said - i'd recommend implicit flow with reference tokens. So here we are now ;)

**Comment by rklachko** [comment]
Yep I remember :) and I perfectly understand what you're saying.

I also understand your recommendation for using implicit flow, I'm just missing the exact explanation for your recommendation. And was hoping you could clear things up by answering my previous questions:

1. Would implicit flow be less secured than using the code flow as I described above (Since code flow also enables me client validation)?

2. Does it totally defeats the purpose of using code flow since the access token is kept on the front channel (user-agent).

**Comment by leastprivilege** [comment]
Since code flow requires a client credential, it is not recommended to use it on a client device.

So you'd need to come up with some client/server work sharing. Which is totally possible - and strictly speaking a bit more secure since it requires more hops. But you'd still need to secure the client to server part somehow.

**Comment by rklachko** [comment]
Yea my intent is to exchange the auth code with a reference token on the server side (where it's safe to hold the client credentials) then pass the reference token back to the client (embedded in the html/js or maybe even on a separate ajax call from the client to the server just to retrieve the access token), and then use it to call the API directly using the access token, I might even revoke/refresh the token using the server side after a certain set of actions were performed.

I would appreciate if there is anything else you think is important to point out about the approach I described. Thanks again for clearing things up...
