### ISSUE TITLE
SoapUI - testing identityserver managed Web.Api REST service

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1378]
We have an instance of identityserver3 “protecting” some Web.Api Rest and an corresponding WebApplication.
Now we want to test solely the WebApi REST with SoapUI. In that case, what would the redirectURI be? Actually the SoapUiClient would be the redirection target. But the SoapUI Documentation http://www.soapui.org/oauth2/access-token-from-server.html has a strange URI: urn:ietf:wg:oauth:2.0:oob. This does not work, despite this entry is added to the client config.
![soapui](https://cloud.githubusercontent.com/assets/9887781/7724837/5aef1340-fef5-11e4-9d54-a38243a2b8a5.png)

Has anyone tested its identityserver3 protected RestServices with Soap UI? What settings were used for redirectURI?

**Comment by johnkors** [comment]
I haven't tested SOAP UI, but it would need to be a valid redirect uri for that client. Look for it in the docs, ```RedirectUris``` : http://identityserver.github.io/Documentation/docs/configuration/clients.html

**Comment by davidmrichter** [comment]
The docs are not helpful. This is because Postman or SoapUI are "surrogate"Browser acting like a browser withaout being one. So the issued token needs to be transered back to SoapUI or Postman. As they behave different than Browsers the documentation you mentioned is not applicable.

**Comment by johnkors** [comment]
Sure, but you still need a valid redirect uri for that specific client_id when doing code flow grant type at the token endpoint. IdSrv validates that this is a redirect uri defined for that client. 
 
http://identityserver.github.io/Documentation/docs/endpoints/token.html

```
redirect_uri (required for code grant type) <----------
```

**Comment by davidmrichter** [comment]
I am perfectly aware that this redirectURI needs to be configured in identityserver for that client.
But as redirection does not target a browser but rather a Postman/SoapUI client, I am stuck.

I need to know what CallbackURI I have to set in soapUI. this then allows SoapUI to receive the issued accesstoken and use it for subsequent calls.

**Comment by johnkors** [comment]
Right, ok. Then you would have to check with the SOAPUI people. There's a similar issue in the postman issue tracker.

**Comment by davidmrichter** [comment]
currently I switched to postman. Do you have the issue number for the postman issue tracker?

**Comment by johnkors** [comment]
There are many, but for instance : https://github.com/a85/POSTMan-Chrome-Extension/issues/22

**Comment by johnkors** [comment]
Can this issue be closed, @davidmrichter ?

**Comment by davidmrichter** [comment]
in my mvc/angular client I provided now a way to get the accesstoken by copy/paste to the postman/SoapUI.
Not fine but the issue get closed.
