### ISSUE TITLE
Cookies are washed on browser restart

### ISSUE THREAD

**Issue by sandeepgaikwad** [IdentityServer/IdentityServer3#1379]
In my client app, I have a non-protected landing page and a standard partial view _loginpartial which displays name of the logged-in user (by reading from the claims object)
Except for the landing page, rest all pages are protected, the _loginpartial is displayed on top on all pages including the landing page.
Everything works just fine, where the user name is displayed in the partial view.
But when I close and reopen the browser instance, hit the landing page, it is seen that the cookies are lost and claims object is blank, until I hit a protected resource. Upon hitting a protected resource I can see that the token is refreshed and claims object filled with claims.
How can I ensure that claims are available and I can display the logged in user name in the partial view even after a browser restart or machine restart.
I intend to have a long life time for the token. Here are my identity server cookieoption settings:
 CookieOptions = new Thinktecture.IdentityServer.Core.Configuration.CookieOptions
                        {
                            IsPersistent=true,
                            SlidingExpiration=true,
                            ExpireTimeSpan = System.TimeSpan.FromDays(30),
                        },

And here are my client app cookieoption settings:
CookieOptions = new Thinktecture.IdentityServer.Core.Configuration.CookieOptions
                {
                    AllowRememberMe=true,
                    RememberMeDuration=System.TimeSpan.FromDays(30),
                    IsPersistent=true,
                    SlidingExpiration=true,
                    ExpireTimeSpan = System.TimeSpan.FromDays(30)
                },
My observations on cookies in chrome:
When logged-in to client app, I can see following cookies:
.AspNet.Cookies
ASP.NET_SessionId
idsrv
idsrv.xsfr
idsvr.session
idsvr.username
Local Storage

When I shutdown and reopen chrome instance (close all instance), I can see following cookies:
idsrv
idsvr.username

When I hit a protected resource, I can see a request going to identity server and token is refreshed, after which claims are available in the claims object.
I am selecting the "Remember My Login" option during login.

**Comment by johnkors** [comment]
If you're using the OIDC MW from MS, you may set some properties on the Auth ticket in the notifications API.

Examplesnippet specific for Code flow, but there is a general notification called ```SecurityTokenValidated``` or something like that which you can use as well. So in your client, something along the lines of:
```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
		Notifications = new OpenIdConnectAuthenticationNotifications
		{
                  AuthorizationCodeReceived = async n =>
                  {
                     	   n.AuthenticationTicket.Properties.ExpiresUtc = dateTimeOffset.UtcNow.AddMinutes(AuthenticationTicketLifetimeInMinutes);
                     	   n.AuthenticationTicket.Properties.IsPersistent = true;
                     	   n.AuthenticationTicket.Properties.AllowRefresh = true;						
                     	   n.AuthenticationTicket.Properties.IssuedUtc = DateTimeOffset.UtcNow;
                  }
         }
    
}
```

Honestly don't remember right now why the Cookie MW option ```IsPersistent``` was not enough :S

**Comment by loctanvo** [comment]
From which cookie do you retrieve the name claim? To me, it sounds like your client app's cookie is not set to persistent in some way. If I understand you correctly, you select the "Remember me" option upon login. This ensures that the `idsrv` cookie is set persistent, which is correct according to your description.

If you are using the OIDC Middleware @johnkors is mentioning, ensure that the Cookie middleware you link it together with, has is set to issue a persistent cookie. Look at [this example](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client/Startup.cs#L20). On [line 33](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client/Startup.cs#L33) the OIDC MW is referring back to which authentication middleware is used. IIRC, one of the options for `CookieAuthenticationOptions` will control whether the it gets persisted or not.

**Comment by sandeepgaikwad** [comment]
Tried code snippet as suggested by @johnkors, but the behavior is still the same.
The MVC OWIN client sample application also has the behavior as my application.So I believe we need some other solution to the problem.
You can simulate the issue in the sample app with following steps:
1) Open the application and login with "Remember Me" option selected
You can see logged-in user name at the top right had corner
2) Close the browser, i.e. close all tabs
3) Now, open the browser and hit the application url.
You cannot see the name of the logged-in user
4) Now hit a protected resource, like "Claims" menu.
You'll see that the token is refreshed and logged-in name being displayed on top

**Comment by sandeepgaikwad** [comment]
Not sure if this is bug, a known normal behavior or due to some missing/incorrect configuration.
Some more information:
On browser restart, the Request.IsAuthenticated is false and ClaimsPrincipal object is empty, till the time we hit a protected resource (decorated by [authorize] attribute).
Once you hit a protected resource, the token is refreshed (you can see the browser is being redirected to IdSvr and everything is back to normal.

**Comment by leastprivilege** [comment]
Sure - that is perfectly normal behavior. If you want to avoid that redirect - then you need to set a persistent cookie in your own application.

**Comment by sandeepgaikwad** [comment]
Yes, My client is setting persistent cookie, set with following configuration:
Code from my client app startup.cs file:
CookieOptions = new Thinktecture.IdentityServer.Core.Configuration.CookieOptions
{
AllowRememberMe=true,
RememberMeDuration=System.TimeSpan.FromDays(30),
IsPersistent=true,
SlidingExpiration=true,
ExpireTimeSpan = System.TimeSpan.FromDays(30)
},

**Comment by leastprivilege** [comment]
..and have you set UseTokenLifetime = false on the OIDC middleware?

**Comment by sandeepgaikwad** [comment]
Yes, that's correct
 UseTokenLifetime = false,

**Comment by leastprivilege** [comment]
then I don't know what's wrong. It is def not related to identityserver. Maybe ask Microsoft on Jabbr or Codeplex. closing for now (but feel free to report back once resolved).

**Comment by loctanvo** [comment]
Just one last comment on this: @sandeepgaikwad Have you actually configured an application cookie for your client? In the code you provide to, you are showing us how you configured `Thinktecture.IdentityServer.Core.Configuration.CookieOptions` in your **client's** startup. Maybe I misunderstand something, but that doesn't make sense to me. That's is an IdentityServer option, and controls the `idsrv` cookie. If you want to not roundtrip to the IdentityServer, you need to issue a persistent cookie from your client app. That's what I tried to explain in my previous post. Maybe not too clearly written :-) .

**Comment by sandeepgaikwad** [comment]
Thanks @loctanvo,
I thought by setting cookie option in client as follows will set cookies in my client app:
CookieOptions = new Thinktecture.IdentityServer.Core.Configuration.CookieOptions
{
AllowRememberMe=true,
RememberMeDuration=System.TimeSpan.FromDays(30),
IsPersistent=true,
SlidingExpiration=true,
ExpireTimeSpan = System.TimeSpan.FromDays(30)
},

Can you please help with some code snippet on how to set/issue a persistent cookie from client app?

**Comment by johnkors** [comment]
Ah, you're confusing the cookies for idsrv with your client cookies. The CookiePptions has nothing to do with your client - it's for the IdSrv cookie.  I'm guessing you're running a client in the same host as idsrv which makes it a bit confusing. 

A sample client setup with cookies is available in the samples repo. I recommend having a go at them so you see what differs between the RP and the OP.

Client that shows usage of cookie mw and OIDC mw from MS:
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client/Startup.cs

To get persistent cookies for this type of client, I pasted a solution above.

**Comment by leastprivilege** [comment]
Ah OK - I missed that. As John said - IdSrv's cookie is unrelated to your application's cookie.

**Comment by sandeepgaikwad** [comment]
I have two separate applications for Identity Server and client app
@johnkors: I tried your solution, but still no success. I also tried with referred sample app (MVC OWIN Client), but same behavior
I might be doing something incorrect.
Appreciate if you could look at my IdSvr and client start.cs files and let me know what wrong am I doing:
Identity Server startup.cs:
 app.Map("/accounts", accountsApp =>
            {
                var options = new IdentityServerOptions
                {
                    IssuerUri = "https://www.MySTS.com",
                    SiteName = "My Identity Server",
                    RequireSsl = false,
                    SigningCertificate = Certificate.Get(),
                    Factory = Factory.Configure("MembershipReboot"),
                    CorsPolicy = CorsPolicy.AllowAll,
                    EnableWelcomePage = false,
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        EnableSignOutPrompt = false,
                        LoginPageLinks = new LoginPageLink[] 
                                {
                                    new LoginPageLink{
                                        Text="Forgot your password?",
                                        Href="ForgotPassword"
                                    }
                                },
                       CookieOptions = new Thinktecture.IdentityServer.Core.Configuration.CookieOptions
                        {
                            IsPersistent=true,
                            SlidingExpiration=true,
                            ExpireTimeSpan = System.TimeSpan.FromMinutes(ExpireTimeSpan),
                        },
                        RememberLastUsername=true,
                    }
                };
                accountsApp.UseIdentityServer(options);
          });

*Here is my client app startup.cs:*
app.UseResourceAuthorization(new AuthorizationManager());
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
	AuthenticationType = "Cookies",
});
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
ClientId = "My Client app",
UseTokenLifetime = false,
Authority = Constants.GlobalSetting.BaseAddress,  //e.g."https://localhost:44333/accounts",
RedirectUri = Constants.GlobalSetting.LandingPageUri, //e.g.  "http://localhost:52971/",
ResponseType = "id_token token",
Scope = "openid email api_claims profile general_claims roles",
SignInAsAuthenticationType = "Cookies",
Caption = "My client application",
PostLogoutRedirectUri = Constants.GlobalSetting.PostLogoutUri, // "https://localhost:52971/",
Notifications = new OpenIdConnectAuthenticationNotifications
{
SecurityTokenValidated = async n =>
{
var nid = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType);
var nam = nid.Name;
nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));
nid.AddClaim(new Claim("expires_at", DateTimeOffset.Now.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToString()));
var userInfoClient = new UserInfoClient(new Uri(n.Options.Authority + "/connect/userinfo"),n.ProtocolMessage.AccessToken);
// filter "protocol" claims
var claims = new List<Claim>(from c in n.AuthenticationTicket.Identity.Claims
                                                             where c.Type != "iss" &&
                                                                   c.Type != "aud" &&
                                                                   c.Type != "nbf" &&
                                                                   c.Type != "exp" &&
                                                                   c.Type != "iat" &&
                                                                   c.Type != "nonce" &&
                                                                   c.Type != "c_hash" &&
                                                                   c.Type != "at_hash"
                                                             select c);
var userInfo = await userInfoClient.GetAsync();
userInfo.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Item1, ui.Item2)));
var username = nid.Claims.Select(na => na.Type == "preferred_username").ToString(); ;
n.AuthenticationTicket = new AuthenticationTicket(nid, n.AuthenticationTicket.Properties);
},
AuthorizationCodeReceived = async s =>
{
	s.AuthenticationTicket.Properties.ExpiresUtc = DateTimeOffset.UtcNow.AddDays(30);
	s.AuthenticationTicket.Properties.IsPersistent = true;
	s.AuthenticationTicket.Properties.AllowRefresh = true;
	s.AuthenticationTicket.Properties.IssuedUtc = DateTimeOffset.UtcNow;
},
RedirectToIdentityProvider = async n =>
{
if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
{
var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
if (idTokenHint != null)
{
	n.ProtocolMessage.IdTokenHint = idTokenHint;
}
}
}
}
});

**Comment by leastprivilege** [comment]
You have not configured the cookie middleware

app.UseCookieAuthentication(new CookieAuthenticationOptions
{
AuthenticationType = "Cookies",
});

**Comment by sandeepgaikwad** [comment]
It's there at line 2 in my client.startup.cs

**Comment by leastprivilege** [comment]
but you need to configure more than the authN type on the options.

**Comment by sandeepgaikwad** [comment]
This is new to me. I am reading about those options, especially the Provider option.
Will explore it in couple of days and get back.

**Comment by johnkors** [comment]
You're not using code flow (you are asking for  ```ResponseType = id_token token```), so move the section you have in the ```AuthorizationCodeReceived ``` func to the ```SecurityTokenValidated``` part.

**Comment by sandeepgaikwad** [comment]
Sorry, I could not get back on this earlier.
Thanks @johnkors: Your last comment did the trick.
Setting up following persists my cookie at client side:

Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        SecurityTokenValidated = async n =>
                            {
                                n.AuthenticationTicket.Properties.ExpiresUtc =DateTime.UtcNow.AddMinutes(ExpireTimeSpan);
                                n.AuthenticationTicket.Properties.IsPersistent = true;
                                n.AuthenticationTicket.Properties.AllowRefresh = true;
                                n.AuthenticationTicket.Properties.IssuedUtc = DateTimeOffset.UtcNow;

**Comment by benaslinjenner** [comment]
AuthenticationType = "Cookies",
                CookieName = "RSMeans",
                //ExpireTimeSpan = TimeSpan.FromDays(365),

               /AuthenticationMode = AuthenticationMode.Passive,
                CookieName = DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie,
               CookiePath= ".zzzzzzzzzzzzzzzzzzzzzzzzzzx.com", //Must
                ExpireTimeSpan = TimeSpan.FromHours(2),
                SlidingExpiration = false,

Try with above configuration and it worked for me. Please set cookie path with an useful URL address
