### ISSUE TITLE
Accessing user module from Web api

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1380]
Hi, 

We have secured Web Api which allows access to protected resources if request has valid bearer token. Now I came across difficult situation, my architect is asking me to keep and access user module from API instead of calling business layer. Since API is protected by secured token I cannot consume user info directly from API. This user info will call for authentication so I will not have token in order to consume. 
Is there anyway to get user info without having token from Api.?

**Comment by jawadatgithub** [comment]
I read over 5 times and failed to understand what is your issue!? I advice to rewrite.
e.g., what do you mean by user module? user info endpoint, or something not related to IdS3...

**Comment by leastprivilege** [comment]
clarify or close
