### ISSUE TITLE
Implicit Flow Browser Back Issue

### ISSUE THREAD

**Issue by strepsil** [IdentityServer/IdentityServer3#1381]
After logging in using the Identity Provider, when a user clicks "back" from the client application, the Form Post is replayed by the provider, and the nonce is rejected.

Implicit Flow OAuth 2.0 Form Post Response Mode proscribes that this shouldn't be replayed:

> Authorization Server MUST instruct the User Agent (and any intermediaries) not to store or reuse the content of the response

http://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html#FormPostResponseMode

On this basis, I assume the identity server should not attempt to reuse the post a second time, either.

Is this a known problem?

N.B. It appears that Chrome does not attempt the repost, whereas firefox / internet explorer does.

**Comment by brockallen** [comment]
The spec means that the OP should issue the right cache control headers and we do.

**Comment by strepsil** [comment]
Thanks for your response - apologies, perhaps quoting the spec just confused matters.

I am suggesting that with the correct cache control headers in place, the identity server serves the form again, and posts a second time, with the same nonce.   The client can capture this and throw an exception, but could it not be said that the identity server is knowingly posting a nonce twice?   I appreciate it cannot assume the post has been received and the nonce processed, but since browser-back is a more likely scenario, should the server not session cache the fact it has posted this request/nonce, and if asked to replay the form subsequently, take some other course of action?

I wonder if anyone is aware of an implementation using form post response mode and a nonce that mitigates this issue?

**Comment by strepsil** [comment]
p.s. Looking at the implementation notes:

http://openid.net/specs/openid-connect-core-1_0.html#NonceNotes

..It suggests the nonce can be per-session.  However, the middleware creates / checks per-request..
