### ISSUE TITLE
Mvc tutorial clarification at WebApi section

### ISSUE THREAD

**Issue by tofutim** [IdentityServer/IdentityServer3#1383]
http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html

At "Calling the API", it was not clear which project (Api or Mvc) is referred to in adding
```
install-package Thinktecture.IdentityModel.Client
```
I know from the sample project that it should be the Api, but this should probably be notated in the doc. The following section, for CallApiController, it is not clear that this should be for the Mvc project.

**Comment by leastprivilege** [comment]
Feel free to change it

**Comment by leastprivilege** [comment]
Will you?

**Comment by tofutim** [comment]
How do I change it?

**Comment by leastprivilege** [comment]
By clicking the "edit" link?
