### ISSUE TITLE
X509Certificate2 object modification after passing through IsPrivateAccessAllowed

### ISSUE THREAD

**Issue by ryan1234** [IdentityServer/IdentityServer3#1384]
I'm running IDS v3 on OS X with Mono 4.0.1 and DNX beta4. I'm able to run the server, login, see the openid-configuration etc.

The problem is when I try to login to get a JWT issued. I get an error saying the private key of my certificate is not available.

If we imagine I have a valid certificate in a variable called `cert` ...

The problem is that the `cert.PrivateKey` value can't be cast to an RSA object. (This happens in a Mono library, specifically, <a href="https://github.com/mono/mono/blob/master/mcs/class/System.IdentityModel/System.IdentityModel.Tokens/X509AsymmetricSecurityKey.cs#L135">this line</a>.)

What I found is that before going into <a href="https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/X509Certificate2Extensions.cs#L23">X509Certificate2Extensions.cs</a>, `cert.PrivateKey` is fine. I can manually cast it as an RSA object and sign JWTs manually.

Immediately after running that extension method though, `cert.PrivateKey` is broken.

Or another way to put it ... if you remove "|| !cert.IsPrivateAccessAllowed()" from <a href="https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AppBuilderExtensions/UseIdentityServerExtension.cs#L117">here</a>, then everything is fine.

The value of IsPrivateAccessAllowed always comes back _true_, but the cert object is broken afterwards.

Any ideas? Wondering if Mono doesn't like the using statement somehow or ... ?

**Comment by loctanvo** [comment]
I guess you are running into the same issue as #1373, or?

**Comment by ryan1234** [comment]
Shoot didn't see that. Yeah same exact issue.

**Comment by leastprivilege** [comment]
OK - that seems to be either a Windows or a Mono bug (at least inconsistent behavior). And also a regression - we have people using idsrv successfully on Mono 3.x

Can you confirm that removing the using statement fixes the problem?

**Comment by ryan1234** [comment]
I can confirm. I have just that running locally to continue work while I wait for a better idea. =)

**Comment by ryan1234** [comment]
Also Mono 3.x doesn't work for me because I'm using DNX beta4. From what I remember there was an attribute/decorator that wasn't supported by a new beta4 security library and it got implemented in Mono 4.0.1. So even though I have 3.10 installed, it throws an error. =(

**Comment by leastprivilege** [comment]
living on the edge ;)
