### ISSUE TITLE
FormPostResponse.js blocked by CSP when using http behind loadbalancer

### ISSUE THREAD

**Issue by larserikfinholt** [IdentityServer/IdentityServer3#1388]
Hi!

We're running http behind our loadbalancer, and thus using RequreSSL=false, we're facing an issue with the [FormPostResponse.html](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/DefaultViewService/PageAssets/FormPostResponse.html). The form is loaded from:

    https://test.myserver.net/STSv3/connect/authorize
but script tag

    
    <script src="http://test.myserver.net/STSv3/assets/app.FormPostResponse.js"></script>
    

is blocked.

Thanks for any help
Larsi

**Comment by leastprivilege** [comment]
Have you tried adding the src into the CspOptions on IdentityServerOptions?

https://identityserver.github.io/Documentation/docs/advanced/csp.html

**Comment by larserikfinholt** [comment]
I've tried, but with no luck:

            var cspOptions = new CspOptions
            {
                Enabled = true,
                ScriptSrc = "http://test.myserver.net"
            };
            appBuilder.Map("", idsrvApp =>
            {
                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    CspOptions = cspOptions, ....

But same error (no csp header present in page). I do not see any header on the login page either (but on the login page all scripts are loaded relative). And from the FormPostTemplate.html it does not seems to include anything, but I've not gone through all code to see if the template is modified somewhere.

Should the csp header have been present on the login page? Anything else I could check?

**Comment by leastprivilege** [comment]
We'll wait for @brockallen to wake up ;)

**Comment by brockallen** [comment]
Is the `<script>` tag really rendering http, when the page is loaded over https?

**Comment by brockallen** [comment]
Also, perhaps setting the `PublicOrigin` is in order?

**Comment by larserikfinholt** [comment]
Ahhh! That was the setting I was missing. PublicOrigin did the trick. 

I should have been able to figure that out by myself. Sorry about that. 

Thanks for great support and a great product.

Larsi
