### ISSUE TITLE
IdentityServer3 and different Apps 

### ISSUE THREAD

**Issue by MartinHNielsen** [IdentityServer/IdentityServer3#1389]
Hi.
I am in the middle of an assignment where the customer wants to use IdentityServer3 as middleware between ADFS and .NET Applications. Now he asks if apps based on JAVA/PHP can be implemented smoothly as well. Has anyone experience with this? Can it be done easily?

**Comment by loctanvo** [comment]
Yes. But, it depends on what you mean by "smoothly". OpenIdConnect is HTTP-based, so everything will work. However, all samples you find here are .NET-based (or JS), so you may need to find other samples to follow. The steps to obtain a identity token or access token are the same.

**Comment by MartinHNielsen** [comment]
Ok. Thx. Actually we thought about ws-federation until now instead of OpenIdConnect. Will it be possible with that as well?

**Comment by loctanvo** [comment]
You mean whether Java/Php applications can easily integrate with WS-Fed? I think it's possible, but keep in mind that the WS-Fed standard is getting old. Not that it's broken or doesn't solve your problem, it was just designed in a time when you didn't have the same diversity of client technology as today (mobile apps, node.js etc.). OpenIdConnect is designed with today's requirements in mind, and integration from the clients' perspective is relatively straightforward. Everything communicates over HTTP.

WS-Fed also uses SAML tokens (if not always, at least very often). Parsing these can be cumbersome, and clients often rely on frameworks doing this. In OpenIdConnect, JWT is used, and if the client lacks standard crypto libraries to validate these, they can always use validation endpoints.

**Comment by leastprivilege** [comment]
You won't have much fun with WS-Fed xplat. It is pretty much rooted in the Microsoft ecosystem. OIDC was meant to solve that (amongst many other things).

**Comment by MartinHNielsen** [comment]
Well, maybe we have been a bit too focused on using ws-federation then. I understand that it is old and can be cumbersome, so I think I will dig a little deeper into OIDC compared to ws-fed. 

Thank you for the quick answers. It is much appreciated...
