### ISSUE TITLE
EnableLocalLogin allows user to login even though it is not defined as an idp in the client restriction list

### ISSUE THREAD

**Issue by rowdyy1960** [IdentityServer/IdentityServer3#1390]
I've been doing some testing in our TFS environment using IDSRV3. I noticed this in my testing and thought I'd place it here to see if it might be considered a bug. 

I have a test application client that is configured with "enableLocalLogin" = true, but I do not have the local login provider configured in the Client IDP restriction table. Just adfs. When I go to the IDSRV from the client the local login screen is displayed along with the link to adfs. If I login with a valid local user account, the user is logged in and is redirected to the login page as an authenticated user. I would have expected it to return a failure because local login is not a valid IDP for the client. Or perhaps I confusing the intended behavior of the "enableLocalLogin" flag. I've attached the trace log below with what I believe are pertinent messages in bold:

Debug: [WebApi Diagnostics]: 5/21/2015 3:02:48 PM +00:00 -- Operation=NoCacheAttribute.OnActionExecutingAsync
Debug: [WebApi Diagnostics]: 5/21/2015 3:02:48 PM +00:00 -- Operation=SecurityHeadersAttribute.OnActionExecutingAsync
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]: 5/21/2015 3:02:48 PM +00:00 -- Start authorize request
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]: 5/21/2015 3:02:48 PM +00:00 -- Start authorize request protocol validation
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]: 5/21/2015 3:02:48 PM +00:00 -- Authorize request validation success
 {
  "ClientId": "mvcSample",
  "ClientName": "mvcSample",
  "RedirectUri": "https://tfwbit-ids01.tfs.collincountytx.dev/MVC Client Sample/",
  "AllowedRedirectUris": [
    "https://tfwbit-ids01.tfs.collincountytx.dev/MVC Client Sample/",
    "http://localhost:59927/"
  ],
  "SubjectId": "0b4b0b28-f8f7-4f96-8bd5-3dbab5b06d57",
  "ResponseType": "id_token token",
  "ResponseMode": "form_post",
  "Flow": "Implicit",
  "RequestedScopes": "openid profile roles sampleApi",
  "State": "OpenIdConnect.AuthenticationProperties=JjneIsp7njxKYmg8k_xn4mUDx_6gTdRz0SxKY2xURrue7kLEmvwyHQ00ZMNTQWb1YABocm_EA2JjCFYjkQJ3TqBQcRBjj7f9medFJb7T5ia11SFBSOZLlLRJXpR4FbBqXfPqSyCjO1DPFC22imrhpaUtvjAb1Syvhh-vc-7C8eFrT3vonhgVSYIM_XEut7hjPQty8Wm01oARDTUX_o30yFfsQRDingmbonoxOPtUStRcfBFixOgy0AJ9FpD1Cu5bToO8SDnJ04svfpChI3NqzyvCcqVy1RGTiK4xTY1Wat3XgfD2_HPdKslJnraqp_SW",
  "Nonce": "635678173542014720.M2M5MDlkMmMtNjhhNi00MzQ2LWI2YzYtOTRhMDI4NWE5ZTFiYTZlMmU4MTMtZjQ0Yi00OTI1LTkyMWEtNWUzMGEwYjU1ZGI3",
  "SessionId": "72232c62c5735a9157bcc7e062273e9b",
  "Raw": {
    "client_id": "mvcSample",
    "redirect_uri": "https://tfwbit-ids01.tfs.collincountytx.dev/MVC Client Sample/",
    "response_mode": "form_post",
    "response_type": "id_token token",
    "scope": "openid profile roles sampleApi",
    "state": "OpenIdConnect.AuthenticationProperties=JjneIsp7njxKYmg8k_xn4mUDx_6gTdRz0SxKY2xURrue7kLEmvwyHQ00ZMNTQWb1YABocm_EA2JjCFYjkQJ3TqBQcRBjj7f9medFJb7T5ia11SFBSOZLlLRJXpR4FbBqXfPqSyCjO1DPFC22imrhpaUtvjAb1Syvhh-vc-7C8eFrT3vonhgVSYIM_XEut7hjPQty8Wm01oARDTUX_o30yFfsQRDingmbonoxOPtUStRcfBFixOgy0AJ9FpD1Cu5bToO8SDnJ04svfpChI3NqzyvCcqVy1RGTiK4xTY1Wat3XgfD2_HPdKslJnraqp_SW",
    "nonce": "635678173542014720.M2M5MDlkMmMtNjhhNi00MzQ2LWI2YzYtOTRhMDI4NWE5ZTFiYTZlMmU4MTMtZjQ0Yi00OTI1LTkyMWEtNWUzMGEwYjU1ZGI3"
  }
}
w3wp.exe Warning: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeInteractionResponseGenerator]: 5/21/2015 3:02:48 PM +00:00 -- **User is logged in with idp: idsrv, but idp not in client restriction list.**
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]: 5/21/2015 3:02:48 PM +00:00 -- End authorize request
Debug: [WebApi Diagnostics]: 5/21/2015 3:02:48 PM +00:00 -- Message='Action returned 'Thinktecture.IdentityServer.Core.Results.LoginResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.LoginResult]: 5/21/2015 3:02:48 **PM +00:00 -- Redirecting to login page**

**Comment by brockallen** [comment]
The IdP restriction list is meant for the external IdPs.

**Comment by pbartos** [comment]
When I enable IdentityProviderRestrictions then I get message "User is logged in with idp: idsrv, but idp not in client restriction list." on local login. This is due to fact that in ProcessClientLoginAsync is checked restriction list even the currentIdp is BuiltInIdentityProvider (idsrv).

Shouldn't be there:
`if (currentIdp != Constants.BuiltInIdentityProvider
&& request.Client.IdentityProviderRestrictions != null
&& request.Client.IdentityProviderRestrictions.Any())`

instead of current:
`if (request.Client.IdentityProviderRestrictions != null
&& request.Client.IdentityProviderRestrictions.Any())`

Thanks.

**Comment by brockallen** [comment]
@pbartos -- Mind opening up a new issue for this so we can track?

**Comment by pbartos** [comment]
Opened new issue:
[https://github.com/IdentityServer/IdentityServer3/issues/2990](https://github.com/IdentityServer/IdentityServer3/issues/2990)
