### ISSUE TITLE
Out of the box support for SSL offloading for the ConfigureIdentityServerBaseUrl method

### ISSUE THREAD

**Issue by michaelbeckersgit** [IdentityServer/IdentityServer3#1391]
Hi,

Would it be a possible to have out of the box support for SSL offloading or reverse proxy when defining the server base url, without having to specify a Public Origin in the options.  This mechanism is used at almost all our customers nowadays and it would require us to always specify this value.

If the code could just look at the X-Forward-Proto/Host headers and take those into account when building the url in each request. I can file a pull request if accepted.

Regards,

**Comment by jawadatgithub** [comment]
I remember this issue discussed many times in issues, and recommended approach was to use external owin middleware to handle X-forward requirements in case public-origin not sufficient. also few blogs already mention how to implement that as external middleware.

**Comment by michaelbeckersgit** [comment]
Yes that makes sense.
Thanks Jawad for the quick reply.

**Comment by leastprivilege** [comment]
I would prefer you post a working solution or some link a middleware that stoves the problem.

**Comment by jawadatgithub** [comment]
references:

[Reconstructing a Uri when behind an SSL terminating reverse proxy and/or load balancer](http://chwilliamson.me.uk/article/Reconstructing-a-Uri-when-behind-an-SSL-terminating-reverse-proxy-and-or-load-balancer)

[Inspect "X-Forwarded-Proto" when creating redirect URI](https://katanaproject.codeplex.com/workitem/404)

[Redirect-Uri is HTTP and not HTTPS behind Reverse Proxy](http://katanaproject.codeplex.com/discussions/577457)

https://gist.github.com/runesoerensen/921bf766b76d7573fcd4

http://stackoverflow.com/questions/24213614/appharbors-reverse-proxy-causing-issues-with-ssl-and-app-useoauthbearertokens-a
