### ISSUE TITLE
IoC/DI, IdentityServerServiceFactory Question

### ISSUE THREAD

**Issue by peske** [IdentityServer/IdentityServer3#1395]
No doubt that you've done great job with service-pluggable infrastructure and IdentityServerServiceFactory class, but... But the project seriously suffers due to the lack of the appropriate documentation (I don't like to criticize free, open-source projects, still...) Avoiding bothering you with asking for help here, I'm often spending hours in finding out how to accomplish something easy (I'm sure it is), and often ending completely lost. Luckily you are always pretty fast answering my questions here. So my question is: once a service is registered with IdentityServerServiceFactory, how can I get the reference to this service from other code. For example if we have registration like:

factory.Register(new Registration<UserAccountService>());

How can I get the reference to the registered service (UserAccountService in this case) from within some other class within the project?

UserAccountService accountService = ...?

If not documented, new service plugin mechanism, with using IoC/DI pattern, with using generic types..., becomes nightmare to track down. Often I'm feeling so lost that I would be happy to see good old spaghetti code :) The fact that you are using not so common IoC/DI container (Autofac), and custom "Registration" class approach makes things even more difficult.

Sorry for my criticism and thanks for you help! Again - the product is awesome!

**Comment by veikkoeeva** [comment]
@peske If you have time, you could document based on your experience and the more polished and thoroughly thought implementation that comes out of the question and answer. I think it'd help people in the same situation as you. I think if you ask for proof-reading and directions where to put the resulting work, I'm sure someone helps.

**Comment by peske** [comment]
@veikkoeeva Sorry, but I don't understand what you are trying to say. Probably I would find some time to participate in documentation, but at the moment I'm struggling to understand how things are working.

**Comment by loctanvo** [comment]
@peske I agree that IoC may be a bit tricky. Have you read through [the article on advaned DI](http://identityserver.github.io/Documentation/docs/advanced/di.html)? There's also a [code sample](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/DependencyInjection) for this topic.

In your case, where do you want to access `UserAccountService`? Assuming your implementation of `IUserService` has a constructor like this `public UserService(UserAccountService accountService){ }`, you need to register both `UserAccountService` and then `UserService` using IdentityServer's `Factory`.

In general, working with IoC containers, we experienced that you need to have a clear understanding of how the containers and scope works.

**Comment by brockallen** [comment]
@peske Did the docs that @loctanvo link help? Between those docs and the samples, that's all we have. The other thing to look into are the RFCs for the protocols -- if you understand those, then you understand much better how and what IdentityServer is doing.

**Comment by peske** [comment]
@loctanvo & @brockallen - Thanks for trying to help guyz!

Documentation and sample provided explain how to register service using DI implementation through "Registration" class so that they can be used internally by IdSrv, but I haven't found a way to later get a reference to registered services to use them in some other code.

I've figured out that there are actually two ways to have services accessible both internally from IdSrv, and externally:
1) Register services with other IoC container (Unity for example), and than providing factory method to Registration class, as in:

IUnityContainer container = ...
container.RegisterType<UserAccountService>(new ContainerControlledLifetimeManager());
factory.Register(new Registration<UserAccountService>(resolver => container.Resolve<UserAccountService>()));

After that reference to the service can be got as in:

IUnityContainer container = ...
UserAccountService uas = container.Resolve<UserAccountService>();

2) Simply keeping a reference to IdentityServerServiceFactory either by keeping it in public static property, or registering it with other IoC. In this case the reference can be got as in:

UserAccountService uas = factory.Registrations.First(r => r.Type == typeof(UserAccountService)).Instance;

In the first case Unity is responsible for lifetime of the service, and in the second case "Registration" class. I'm still not sure what approach to use, but I will figure it out.

It would be useful if you can just tell me about lifetime of the services registered with "Registration" class:
a) per resolve (new instance on each call)
b) request-level singleton (the same instance during single request cycle)
c) application-level singleton (the same instance during entire application lifetime)

Thanks again!

**Comment by brockallen** [comment]
Correct - our Di system is only used within IdentityServer. If you want the same things registered elsewhere you need to re-register them with the other DI system. This is partially due to the fact that there's no DI defined in the OWIN layer.

**Comment by peske** [comment]
Can you just answer me about liftime?

Thanks Brock! Great job with IdSrv!

**Comment by brockallen** [comment]
Do the docs on _Instancing with the Registration Mode_ here not explain it?

https://identityserver.github.io/Documentation/docs/advanced/di.html

**Comment by peske** [comment]
Sorry! Thanks again.
