### ISSUE TITLE
How to control tampering of access token in order to secure from multiple users. 

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1396]
Hi, 

I came across issue that we can reuse the same access token for other users by hard coding access token in startup class of own method. Could you please share me how to control tampering of access token in order to secure this access token. Pleas suggest me on issue.

Thanks,
Dhanaraj

**Comment by leastprivilege** [comment]
I have no clue what you are talking about. Please explain.

**Comment by brockallen** [comment]
The access token is either signed (if it's a JWT) or its key is stored in the IdSvr DB (reference). In either case, tampering results in an invalid token. Is this what you're asking about?

**Comment by dhanutpk** [comment]
I have used access token generated for user1 to user2 by hard coding the access token in the startup while adding to claim identity.

**Comment by brockallen** [comment]
And what's your point? If you're looking to get help, you need to be clear.

**Comment by dhanutpk** [comment]
I got answer by previous to previous comments. Thank you.
