### ISSUE TITLE
Exception Handling With Claims Transformation in WEB API

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#1397]
I have a question on exception handling for claims transformations in web api.
In my transform, I throw an exception if there are any required claims missing.

This seems to render the html for error page and will send that back as the response. Is there a way to avoid this happening?

This is the claimstranformer

``` c#
public class ClaimsTransformer
    {
        public Task<ClaimsPrincipal> Transform(ClaimsPrincipal incomingPrincipal)
         ----- hiding extra code

 if (!isValidApiScope)
            {
               // throw new Exception("No API Scope was found. Invalid request");
                throw new HttpException((int)System.Net.HttpStatusCode.Forbidden, "No API Scope was found. Invalid request");
            }


            //// go to datastore and add app specific claims
            //incomingPrincipal.Identities.First().AddClaim(
            //    new Claim("localclaim", "localvalue"));

            return Task.FromResult(incomingPrincipal);
        }
    }
```

This is the call in startup.

``` c#
//wire up claims transform through the middleware
  app.UseClaimsTransformation(new ClaimsTransformer().Transform); 
```

**Comment by brockallen** [comment]
Is the response content-type really html? Also, who knows how to handle `HttpException` --- meaning is that really the right exception to throw? Maybe different MW prior to this to ensure the right claims so you can control the HTTP response better.

**Comment by parkinsona** [comment]
Just checked the response type and it is html.
Here's the start of what its bringing back

```
HTTP/1.1 403 Forbidden
Cache-Control: private
Content-Type: text/html; charset=utf-8
Date: Tue, 26 May 2015 22:14:29 GMT
Content-Length: 5338

<!DOCTYPE html>
<html>
    <head>
        <title>This type of page is not served.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/IdentityManager' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>This type of page is not served.</i> </h2></span>

```

**Comment by brockallen** [comment]
Perhaps IIS is rendering that HTML?

**Comment by brockallen** [comment]
Any update?

**Comment by parkinsona** [comment]
Sorry, I got caught up in the signout issue I had, I forgot to respond to this one.

I got around this issue, but removing the "throw exception" in my claims transformation.
I have a claimsHelper class that looks up and returns the value of claims. If one of the claims that should have been created during transformation is not found, we throw an exception at that point. This will then throw the exception through the web api exception handlers.

Eg.
''' c#
    public static string GetApiClientCode(IPrincipal user)
        {
           
            var claim = (user.Identity as ClaimsIdentity).FindFirst(Config.Constants.ApiClientCodeClaim);

            if (claim == null)
            {
                throw new Exception("No Api Client Code claim was found. Ensure the client application has an api scope configured.");
            }
            return claim.Value;

        }
'''
