### ISSUE TITLE
User Service - Request authentication based on client

### ISSUE THREAD

**Issue by rdzidziguri** [IdentityServer/IdentityServer3#1398]
For now if one implements custom user service there are three main methods which contains information about client redirecting client for authentication. for this case I will emphasize PreAuthenticateAsync method which according to the documentation "This method gets called before the login page is shown...". this is all Okey but what if we want to categorize clients based on priority so for example if we have simple web app which allows users to do some simple staff and on the other hand there is an online banking application as they both use same identity system what we would like to to is to force client to authenticate each time when they hit online banking application while signing ins automatically if they visit simple app after they authenticate against online banking. 

I understand that this might conflict with SSO but, what can be done if business and security requirements  demand this type of security? 

IsActiveAsync method seems to be usable method for this type of scenarios but it only applies to the client while situation I describe above is directly related to the client not user and as we do not have access to the ClientId we can not determine if login screen must be presented or not.

@leastprivilege @brockallen do you have any suggestions about this?

**Comment by brockallen** [comment]
If the client app expects full authentication then use the features of the OIDC spec -- specifically prompt=login. Check the spec for more details.

**Comment by rdzidziguri** [comment]
Ok this sounds real solution. when i was reading specs I should read that part more carefully.
