### ISSUE TITLE
Adding the Authorisation manager to the OWIN pipeline in Asp.NET 5

### ISSUE THREAD

**Issue by Gujie** [IdentityServer/IdentityServer3#1399]
Hello!

I'm trying to build my own Asp.Net 5 application integrating IdSrv by following the MVC Authentication & Authorisation [tutorial] (https://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html)

However I'm stuck at this line:
```app.UseResourceAuthorization(new AuthorizationManager()); ```

In fact, UseResourceAuthorization is no longer available for objects of type IApplicationBuilder.
May I have some help to find the modern equivalent?

Thank you very much!

**Comment by johnkors** [comment]
http://blogs.msdn.com/b/webdev/archive/2014/11/14/katana-asp-net-5-and-bridging-the-gap.aspx

**Comment by Gujie** [comment]
Thanks I'll have a look
