### ISSUE TITLE
How to configure a custom "user is locked" out error message

### ISSUE THREAD

**Issue by anaratz** [IdentityServer/IdentityServer3#1401]
Hi,

I am trying to make a change to the authentication process of an application, which uses IdentityServer3 and ASP.NET Identity

Current behaviour is:
When “user lockout” behaviour is configured in Microsoft.AspNet.Identity and authentication fails (due to the user being locked out) the logon page will display the generic “InvalidUsernameOrPassword” message.

Desired Behaviour:
When a user is locked out, I want to change the error message to reflect this. E.g “You are currently locked out of the system.”

Are you able to suggest how to go about configuring this behaviour?

**Comment by brockallen** [comment]
In your user service, when you return an `AuthenticatioNResult` use the ctor with the string param that indicates an error. This error will be displayed to the user.

**Comment by rdzidziguri** [comment]
@anaratz I think it might sound like exposing extra information about user as someone who tries to access some sensitive information using users credentials if you say user is locked out you openly say, that "Hi we have this user and yeah password might be ok even username is correct but you know what :( well this user is currently locked out come back again and try again later" we I always keep simple message like wrong username or password and try to expose as little information as possible.

**Comment by anaratz** [comment]
@brockallen, thank you for the steer, we are going to try overriding AuthenticateLocalAsync in the userService and returning new AuthenticateResult("Account is locked."); if the user is locked out.

@rdzidziguri, you make a valid security point (and I have raised it with the project team for more discussion). I guess our concern was from user's perspective, since the user may have a frustrating experience if they enter correct credentials, but are not able to gain access to the system because (unknown to them) they are locked out.

**Comment by leastprivilege** [comment]
I wouldn't give any specific error message - 

either they can't remember their own password after the third try - or someone else tried to guess their password. The most natural reaction is to "reset password" which brings in your validated email address.

**Comment by johnkors** [comment]
Yeah, it's a general OWASP guideline to not convey to much information. You might do this anyhow in a registration form (this username is already taken, pick another), so other mechanisms to prevent brute forcing attacks could be in order. We chose to enforce a locked account after 10 failed attempts in sequence.

**Comment by brockallen** [comment]
Personally, assuming that the code is public, timing attacks can determine what branch in the code is being taken, so showing an error message that indicates the account is locked is not too much of an information disclosure, IMO.

**Comment by anaratz** [comment]
I now have a working solution to my question (as per brockallen's suggestion). Thanks.
Also, some very useful thoughts on security from the other contributors.

**Comment by vpetrovic** [comment]
"User is locked/not active/banned" is very useful for me as a status error message, not as description message, because I want to "lock" some data in my client application, and that data is wired with that specific user. I read about custom error information in #1035, I see it is by OpenID Connect design.
