### ISSUE TITLE
HowTo: Federated Identity - distibuted full login - refuse Login in second identity instance

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1402]
Hello,

We have one main instance of identityserver3 in (Ws)Federation with an other minor identityserver instance which is only responsible to check login credentials.

1)the minor instance only checks username and password and issues a SAML token for the main instance.
2)then the main instance receives that token and checks for further claims (fetching further userinformation from some legacy db). 
2a)if the user not having certain "rights"/claims then the user is not allowed to login all though its password and username were ok.
2b)if the user has the corresponding "rights"/claims then login is successful

PartialLogin would not be the solution since it involves some redirect AFAIK.
What is here the identityserver Standard sceario( with some example code perhaps)?

**Comment by brockallen** [comment]
Look into the `ICustomRequestValidator` -- this contains the logic if the user is allowed to obtain a token.
