### ISSUE TITLE
InMemoryUserService sufficient for AuthenticateExternalAsync - if never ever more than one external service used

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1403]
Hello,

We have one main instance of identityserver3 in (Ws)Federation with an other minor identityserver instance which is only responsible to check login credentials.
"This will never ever change" meaning no other identityprovider is being intented for use.

1)the minor instance only checks username and password and issues a SAML token for the main instance.
2)then the main instance receives that token and checks for further claims (fetching further userinformation from some legacy db). 

Now in my UserService I override AuthenticateExternalAsync  and GetProfileDataAsync.
I found that I need to store during AuthenticateExternalAsync the additional user data so that subsequent calls to GetProfileDataAsync get that data. I can do that in memory or in some persistancy store.

Now InMemory is not encouraged for production scenarios. But I do not see from my (currently limited) knowledge why I need more than InMemory implementations for my scenario.  Furthermore if some userclaims change over time I need to cleanup - that I can save using InMemory implementations.

What Do I miss?

**Comment by brockallen** [comment]
You need something persistent -- what if the server recycles or you have a web farm?

**Comment by davidmrichter** [comment]
Ok- we have no webfarm- 

but if IIS recycles ==> accesstokens once issued are still valid and can be used until expired, ==>Otherwise the new users will have to logon again ==> This is sufficient for our scenarios.

Or do I miss another UseCase?

**Comment by brockallen** [comment]
If you're keeping a list in-memory, then we really suggest you use a DB. There are some scenarios where you don't need a DB for the user service, and that's where the incoming ClaimsPrincipal has all you need. But if you're keeping state in the user service, that should be in a DB. But hey, maybe your scenario is different. *shrug*

**Comment by davidmrichter** [comment]
I found by having my own Userservice on the main idserver instance that some calls to GetProfileDataAsync the current idserver implmentation(userinfoResponseGenerator.cs) created for userinfo response a new ClaimsPrinicipal with just a sub claim. 
This was the exception which triggered the need of a backing list. otherwise we would need any persistant list, since the user data is already within the legacysystem.

Is there a way to construct calls to userinfo so that the incoming ClaimsPrinicipal is used?

**Comment by brockallen** [comment]
For most scenarios, whatever claims you return from AuthenticateXxx are passed back into GetProfile via the ClaimsPrincipal.

**Comment by davidmrichter** [comment]
But in case of userinfoResponseGenerator.cs not:

        'public async Task<Dictionary<string, object>> ProcessAsync(string subject, IEnumerable<string> scopes)
        {
            Logger.Info("Creating userinfo response");
            var profileData = new Dictionary<string, object>();
            
            var requestedClaimTypes = await GetRequestedClaimTypesAsync(scopes);
            var principal = Principal.Create("UserInfo", new Claim("sub", subject));

            IEnumerable<Claim> profileClaims;
            if (requestedClaimTypes.IncludeAllClaims)
'

Is this intented?
 We have no need for persistant userstorage since we have all the "claims" and users already in the legacy service persisted. Having another userservice persistance just for the sake of getting idserver up and running with userinfo endpoint is a duplication of data which needs to be maintened with no benefit at all.

**Comment by brockallen** [comment]
Right -- so implement your user service to connect to your legacy database.

**Comment by brockallen** [comment]
Or if you're getting all the claims you need from the external IdP, then like I said, you might get away with all the claims you need coming in via the ClaimsPrincipal to the GetProfile API. 

As for the user response generator, you're right -- there are some workflows where the ClaimsPrincipal to the GetProfile API does not have all the claims for the user from login.

**Comment by davidmrichter** [comment]
I already have a special UserService connected to the legacyprovider.

So as I have process the claims received from the externalprovider during AuthenticateExternalAsync, using userinfo forces me to persist that information in the first place to use for subsequent userinforequests, right?

Somehow this is confusing. I already have all the userdata stored in my legacyuser storage. Why then duplicate them in the userservice! This is a "smell"!
Is my scenario violating some conventions?

**Comment by brockallen** [comment]
Well, IdSvr can't know that you're in control of both and that you want them to be the same.

**Comment by davidmrichter** [comment]
I now abandoned Usage of Userinfo endpoint- then the Claimsprinicipal is always with all the claims.
