### ISSUE TITLE
IE8 issue

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/IdentityServer3#1404]
hi,

I'm having a strange issue when using actual IE8 (vs. IE8 emulation) where I get a DNS error page immediately after authentication.  Emulation works fine actually but the "real" IE8 doesn't.  I know you are not officially supporting IE8 but if you have any guidance as to the actual problem I would really appreciate any help.

![error](https://cloud.githubusercontent.com/assets/7965187/7842214/6c4618a6-0467-11e5-9fc3-90dea43afc63.jpg)

There's no error in the logs either.  Does anyone have any ideas on what would cause this?

**Comment by stevenfirstrowinc** [comment]
I should mention that I am using v1.3 with a custom login view, however when the client is a Hybrid instead of Implicit there doesn't seem to be a problem.

**Comment by brockallen** [comment]
Disable IE's "friendly" error pages.

**Comment by stevenfirstrowinc** [comment]
Get exactly the same message after unchecking Internet Options > Advanced >
Show friendly HTTP error messages.

**Comment by brockallen** [comment]
Hmm, well not sure. Not a lot to go on there....

**Comment by stevenfirstrowinc** [comment]
ugh I know.  Here is the whole log for a single request with this problem.  It appears to be happening during the redirect

16:23 [Warning] 15   AuthorizationCodeStore not configured - falling back to InMemory
16:23 [Warning] 15   TokenHandleStore not configured - falling back to InMemory
16:23 [Warning] 15   ConsentStore not configured - falling back to InMemory
16:23 [Warning] 15   RefreshTokenStore not configured - falling back to InMemory
16:23 [Information] 14   Start authorize request
16:23 [Information] 14   Start authorize request protocol validation
16:23 [Debug] 14   Cache miss: csRA
16:23 [Debug] 14   Cache miss: csRA,email,openid,profile
16:23 [Information] 14   Authorize request validation success
 {
  "ClientId": "csRA",
  "ClientName": "cs RA",
  "RedirectUri": "https://ra.codysoft.com/testsecurity.html",
  "AllowedRedirectUris": [
    "https://ra.codysoft.net/#!/",
    "https://localhost:44311/",
    "https://localhost:44311/#!/",
    "https://localhost:44311/testsecurity.html",
    "https://ra.codysoft.com/#!/",
    "https://ra.codysoft.com/testsecurity.html"
  ],
  "SubjectId": "unknown",
  "ResponseType": "id_token token",
  "ResponseMode": "fragment",
  "Flow": "Implicit",
  "RequestedScopes": "openid profile email csRA",
  "State": "111467547030851",
  "Nonce": "5843063499074818",
  "LoginHint": "tenant:tenants/Test",
  "Raw": {
    "client_id": "csRA",
    "redirect_uri": "https://ra.codysoft.com/testsecurity.html",
    "response_type": "id_token token",
    "scope": "openid profile email csRA",
    "state": "111467547030851",
    "login_hint": "tenant:tenants/Test",
    "nonce": "5843063499074818"
  }
}
16:23 [Information] 14   User is not authenticated. Redirecting to login.
16:23 [Information] 14   End authorize request
16:23 [Information] 14   Redirecting to login page
16:23 [Debug] 14   Protecting message: {"ReturnUrl":"https://login.codysoft.com/identity/connect/authorize?client_id=csRA&redirect_uri=https%3A%2F%2Fra.codysoft.com%2Ftestsecurity.html&response_type=id_token%20token&scope=openid%20profile%20email%20csRA&state=111467547030851&login_hint=tenant%3Atenants%2FTest&nonce=5843063499074818","ClientId":"csRA","LoginHint":"tenant:tenants/Test","AcrValues":[],"Created":635683549894409669}
16:23 [Information] 14   Login page requested
16:23 [Debug] 14   signin message passed to login: {
  "ReturnUrl": "https://login.codysoft.com/identity/connect/authorize?client_id=csRA&redirect_uri=https%3A%2F%2Fra.codysoft.com%2Ftestsecurity.html&response_type=id_token%20token&scope=openid%20profile%20email%20csRA&state=111467547030851&login_hint=tenant%3Atenants%2FTest&nonce=5843063499074818",
  "ClientId": "csRA",
  "IdP": null,
  "Tenant": null,
  "LoginHint": "tenant:tenants/Test",
  "DisplayMode": null,
  "UiLocales": null,
  "AcrValues": [],
  "Created": 635683549894409669
}
16:23 [Warning] 14   Not using LoginHint because EnableLoginHint is false
16:23 [Debug] 14   Cache hit: csRA
16:23 [Debug] 14   Cache hit: csRA
16:23 [Information] 14   rendering login page
16:23 [Information] 18   Login page submitted
16:23 [Debug] 18   Cache hit: csRA
16:23 [Information] 18   Login credentials successfully validated by user service
16:23 [Information] 18   issuing cookie
16:23 [Information] 18   redirecting to: https://login.codysoft.com/identity/connect/authorize?client_id=csRA&redirect_uri=https:%2F%2Fra.codysoft.com%2Ftestsecurity.html&response_type=id_token token&scope=openid profile email csRA&state=111467547030851&login_hint=tenant:tenants%2FTest&nonce=5843063499074818
16:23 [Information] 19   Start authorize request
16:23 [Information] 19   Start authorize request protocol validation
16:23 [Debug] 19   Cache hit: csRA
16:23 [Debug] 19   Cache hit: csRA,email,openid,profile
16:23 [Information] 19   Authorize request validation success
 {
  "ClientId": "csRA",
  "ClientName": "cs RA",
  "RedirectUri": "https://ra.codysoft.com/testsecurity.html",
  "AllowedRedirectUris": [
    "https://ra.codysoft.net/#!/",
    "https://localhost:44311/",
    "https://localhost:44311/#!/",
    "https://localhost:44311/testsecurity.html",
    "https://ra.codysoft.com/#!/",
    "https://ra.codysoft.com/testsecurity.html"
  ],
  "SubjectId": "30f15703-b816-47e3-93e4-95497c8b8326",
  "ResponseType": "id_token token",
  "ResponseMode": "fragment",
  "Flow": "Implicit",
  "RequestedScopes": "openid profile email csRA",
  "State": "111467547030851",
  "Nonce": "5843063499074818",
  "LoginHint": "tenant:tenants/Test",
  "Raw": {
    "client_id": "csRA",
    "redirect_uri": "https://ra.codysoft.com/testsecurity.html",
    "response_type": "id_token token",
    "scope": "openid profile email csRA",
    "state": "111467547030851",
    "login_hint": "tenant:tenants/Test",
    "nonce": "5843063499074818"
  }
}
16:23 [Information] 19   Creating Implicit Flow response.
16:23 [Debug] 19   Creating access token
16:23 [Debug] 19   Creating JWT access token
16:23 [Debug] 19   Creating identity token
16:23 [Information] 19   Getting claims for identity token for subject: 30f15703-b816-47e3-93e4-95497c8b8326
16:23 [Debug] 19   Creating JWT identity token
16:23 [Information] 19   End authorize request
16:23 [Information] 19   Redirecting to: https://ra.codysoft.com/testsecurity.html

**Comment by huysentruitw** [comment]
Strange thing is that the URL in the logs is `login.codysoft.com`, while on the screenshot it looks more like `login.codysoft.net`. Any reason for that?

**Comment by stevenfirstrowinc** [comment]
yes I moved everything to .com for testing purposes so I wouldn't interfere with my users.

**Comment by stevenfirstrowinc** [comment]
what is really weird is that the client that is Hybrid is a MVC app that has a server side post back for auth results and it works fine.  It is only the implicit client app that seems to result in this behavior.  That doesn't really make sense to me because I would assume that a 302 is a 302 regardless but perhaps IdSrv internals calls back differently?

**Comment by brockallen** [comment]
I'd suggest trying from a different environment to rule out some local DNS/host/configuration issue.

**Comment by stevenfirstrowinc** [comment]
I have a few more details and I am hoping someone can see something obvious here

here is the login form submission raw.  everything works as expected
````
Request:
POST https://login.codysoft.com/identity/login?signin=c38ab6bf0064c7459e240917238c8f2f HTTP/1.1
Accept: image/gif, image/jpeg, image/pjpeg, image/pjpeg, application/x-shockwave-flash, */*
Referer: https://login.codysoft.com/identity/login?signin=c38ab6bf0064c7459e240917238c8f2f
Accept-Language: en-us
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727)
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
Host: login.codysoft.com
Content-Length: 166
Connection: Keep-Alive
Cache-Control: no-cache
Cookie: SignInMessage.c38ab6bf0064c7459e240917238c8f2f=DSYAO4hwPUhB6G6CEIIfgOsIldg8F4Q48QJqUn458SuAxEsSl2ooAZwJ6KIhaekF8VWWr9pFaSnpt6aX52mUukccOzmePjZf4xDP5Z2XDAiqUup9YDbdU9W2cK9wHHk6EPtpS8UQFGOLljbcyDe2mi6LWgTfTENK3GR5cJQeBpcy87mCI_aTUQHyLf328t8biI40pI73JeCU0YzLF_JlQtaKWcqLJ1yYVk1ipEXN7W1WMLRZ836SVqC61e6N5WFSrdci7M8YeFn1RQxniZuwcuLwS3jbM2ydKrewfYaMPdxG3TS99fbgesTWPWd6kvY-ZY7vOgPhFvE5H3kL0ryZ_tnGlB6NO7E8_tIHi7b7wmyrUbgL3h-8be_Db4C8iYowvRT6-3acqCfd1b4SXuLahHnzbCHJBW7A8W6XgDK8MDyHlF2pg1T_lzGijVGt2rytENAFP-JqtwwP5Mw8jw2NEPrU8wAyD0Cwh67tviL6EfxDpAaIwky1adDIvmBrT5-Qky_8pWDbAY9OLCQTLVJwuIoyBXz5Fmg2EqKvtz4oaENUfpg9Kukhk6LN7CzYqlQTU_XTyf4ezW5dYbjRiiHT5Q; idsrv.xsrf=2uxpDS7bywF8Z-2VoyJ-Uhhx6Jp7n6uJ9tkZ_L9yiBmxHMIXSJ1i6l3trTqIKH5kOIB4pE7H6btfBTYKtY4D1UZVnXP4eKr3l2AVeQmU_vU
idsrv.xsrf=hoS56zXT7xWLnQYzKfhvv2nrpqpSTvT3XABwO-CXNM1onVgpK1MsGSdnVkCPqUmQLSWhhMJYCYJv94DuwSSv2AI1fcszwkGDFsUr3XEmKdk

Response:
HTTP/1.1 302 Found
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 0
Expires: -1
Location: https://login.codysoft.com/identity/connect/authorize?client_id=csRA&redirect_uri=https%3A%2F%2Fra.codysoft.com%2Ftestsecurity.html&response_type=id_token%20token&scope=openid%20profile%20email%20csRA&state=7700974972365405&login_hint=tenant%3Atenants%2FTest&nonce=7387052905724949

Server: Microsoft-IIS/7.5
Set-Cookie: SignInMessage.c38ab6bf0064c7459e240917238c8f2f=.; path=/identity; expires=Sat, 31-May-2014 16:58:19 GMT; secure; HttpOnly
Set-Cookie: idsvr.session=562bc6185f885c0e25d2254c9016746e; path=/identity; secure
Set-Cookie: idsrv.partial=; path=/identity; expires=Thu, 01-Jan-1970 00:00:00 GMT
Set-Cookie: idsrv.external=; path=/identity; expires=Thu, 01-Jan-1970 00:00:00 GMT
Set-Cookie: idsrv=UHH5LSQLWDhca3L6SCc0cSas1WJDQCMRonGBtlUn_ia9bTptDThF82Dgq1kyeQNVRtBG41bany5MFDm_Znimm64bo4RIcbtSP92g_l3t62KP08gbMa_kUuiVH8J7iy31NULHaTBmp1wZ1thPgPtR7XFB6pWFKcbXZ9Znxj3jGUPZGbiG4IagAYj-J7M4GyYpwHkbXTev7Ta_-MpRxc_aFvzfmEpEYshQapxhBnY-Xy8Ra-LAIaGzxkWjTyZuk4CXYAJMzx-kRbE1FKxGnumvWKq8rDlCpmvSZjepk0OwZnsxFlKFe_m1BCpYRRl6EbbQjGZ8W6v4w3n2JzIIkZPSyNx2lDyNtJNYVYGjT6AIs2KzIym6AFfYISaDiH3OOKeT8nFl47-eB4ZT9DDnj7R84A; path=/identity; secure; HttpOnly

X-Powered-By: ASP.NET
Date: Sun, 31 May 2015 16:58:19 GMT
````
In the working Hybrid client this redirect renders a form that get's submitted to the Hybrid client.  In Implicit client only a 302 redirect is issued.  Here is that code

 ````
Request:

GET https://login.codysoft.com/identity/connect/authorize?client_id=csRA&redirect_uri=https%3A%2F%2Fra.codysoft.com%2Ftestsecurity.html&response_type=id_token%20token&scope=openid%20profile%20email%20csRA&state=7700974972365405&login_hint=tenant%3Atenants%2FTest&nonce=7387052905724949 HTTP/1.1

Accept: image/gif, image/jpeg, image/pjpeg, image/pjpeg, application/x-shockwave-flash, */*
Referer: https://login.codysoft.com/identity/login?signin=c38ab6bf0064c7459e240917238c8f2f
Accept-Language: en-us
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727)
Accept-Encoding: gzip, deflate
Host: login.codysoft.com
Connection: Keep-Alive
Cache-Control: no-cache
Cookie: idsrv.xsrf=2uxpDS7bywF8Z-2VoyJ-Uhhx6Jp7n6uJ9tkZ_L9yiBmxHMIXSJ1i6l3trTqIKH5kOIB4pE7H6btfBTYKtY4D1UZVnXP4eKr3l2AVeQmU_vU; idsvr.session=562bc6185f885c0e25d2254c9016746e; idsrv=UHH5LSQLWDhca3L6SCc0cSas1WJDQCMRonGBtlUn_ia9bTptDThF82Dgq1kyeQNVRtBG41bany5MFDm_Znimm64bo4RIcbtSP92g_l3t62KP08gbMa_kUuiVH8J7iy31NULHaTBmp1wZ1thPgPtR7XFB6pWFKcbXZ9Znxj3jGUPZGbiG4IagAYj-J7M4GyYpwHkbXTev7Ta_-MpRxc_aFvzfmEpEYshQapxhBnY-Xy8Ra-LAIaGzxkWjTyZuk4CXYAJMzx-kRbE1FKxGnumvWKq8rDlCpmvSZjepk0OwZnsxFlKFe_m1BCpYRRl6EbbQjGZ8W6v4w3n2JzIIkZPSyNx2lDyNtJNYVYGjT6AIs2KzIym6AFfYISaDiH3OOKeT8nFl47-eB4ZT9DDnj7R84A

Response:
HTTP/1.1 302 Found
Content-Length: 0
Location: https://ra.codysoft.com/testsecurity.html#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJub25jZSI6IjczODcwNTI5MDU3MjQ5NDkiLCJpYXQiOjE0MzMwOTE0OTksImF0X2hhc2giOiJEblpnS3FfNnhNU2NueDNJeEtyU3VBIiwic3ViIjoiMzBmMTU3MDMtYjgxNi00N2UzLTkzZTQtOTU0OTdjOGI4MzI2IiwiYW1yIjoicGFzc3dvcmQiLCJhdXRoX3RpbWUiOjE0MzMwOTE0OTksImlkcCI6Imlkc3J2IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYXZhbGVudGlAY29keWVudC5jb20iLCJlbWFpbCI6ImF2YWxlbnRpQGNvZHllbnQuY29tIiwiZW1haWxfdmVyaWZpZWQiOiJmYWxzZSIsImZhbWlseV9uYW1lIjoiVmFsZW50aSIsImdpdmVuX25hbWUiOiJBbHBob25zZSIsImlzcyI6Imh0dHBzOi8vbG9naW4uY29keXNvZnQuY29tIiwiYXVkIjoiY3NSQSIsImV4cCI6MTQzMzA5MTg1OSwibmJmIjoxNDMzMDkxNDk5fQ.AqgWtNbcny7vpBliCO3vO8OiFWeuC5-_Ri1avUc_GkVjsgGl4w-_Tfku5_ZlFxPv_EOE93S8JQBk580I0iUILKEUWFtVpvxgejsWpOn50O7wLuFcJeOD3wDz5JQgeU9aIKlRIdwVWCYVvGPFTV3XpXNiDhDvwBcVoSWnRDosOjlzVaAG2A_We3Q4UXSNpiqo--DWJAyNAs_PW71wGL8xvYu44sZHEuksznLGcmE6YwX9Q1bpyVqy6DfMx_RGmNyVUPcwF1ndjTLVCFL8DDA2Kva2I10oKBxF_TNVDSPWlBxFC7Vpt27eq0DZpCyloVF5SSiTiRFsudeacIlmNyEORQ&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJjbGllbnRfaWQiOiJjc1JBIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwiY3NSQSJdLCJzdWIiOiIzMGYxNTcwMy1iODE2LTQ3ZTMtOTNlNC05NTQ5N2M4YjgzMjYiLCJhbXIiOiJwYXNzd29yZCIsImF1dGhfdGltZSI6MTQzMzA5MTQ5OSwiaWRwIjoiaWRzcnYiLCJ0ZW5hbnQiOiJkZWZhdWx0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYXZhbGVudGlAY29keWVudC5jb20iLCJlbWFpbCI6ImF2YWxlbnRpQGNvZHllbnQuY29tIiwiZW1haWxfdmVyaWZpZWQiOiJmYWxzZSIsImZhbWlseV9uYW1lIjoiVmFsZW50aSIsInRlbmFudF9pZCI6InRlbmFudHMvMSIsInJvbGUiOlsiY3NSQS5SZXNlYXJjaGVyIiwiY3NSQS5SZWd1bGF0aW9uRWRpdG9yIiwiY3NSQS5QYW5kUEVkaXRvciIsImNzUkEuSFBNU0VkaXRvciIsImNzUkEuQ29udHJhY3RFZGl0b3IiLCJjc1JBLkFuYWx5emVyIiwiY3NSQS5BZG1pbiIsIkNsaWVudEFkbWluIl0sImNzQXBwIjpbImNzU2NoZWR1bGluZyIsImNzR2xvYmFsIiwiY3NSQSIsImNzQ00iLCJjc0lNIl0sImdpdmVuX25hbWUiOiJBbHBob25zZSIsImRlcGFydG1lbnQiOiJDb21wbGlhbmNlIiwibGluZV9vZl9idXNpbmVzcyI6WyJNZWRpY2FpZCAtIFNvdXRoIENhcm9saW5hIiwiTWVkaWNhaWQgLSBMb3Vpc2lhbmEiLCJNZWRpY2FpZCAtIFRlbm5lc3NlZSIsIk1lZGljYWlkIC0gRmxvcmlkYSIsIk1lZGljYXJlIiwiQ29tbWVyY2lhbCAtIEluZGl2aWR1YWwiXSwic2VuZEVtYWlscyI6InRydWUiLCJpc3MiOiJodHRwczovL2xvZ2luLmNvZHlzb2Z0LmNvbSIsImF1ZCI6Imh0dHBzOi8vbG9naW4uY29keXNvZnQuY29tL3Jlc291cmNlcyIsImV4cCI6MTQzMzEyMDI5OSwibmJmIjoxNDMzMDkxNDk5fQ.VEWxut6-C0r4pXfuABldJBLnN9C_luXuzFjjfpipv0Z-UvRra0oYBnCsWQ-8It4vk5UxVktoe-cIrJm29Inbw_pLnZILrasjdzU7dwpuaGcPzLMg1pgv7RFjkAO-NcPjtHOn54aASOxlJpQTvve9-B2_jbqtwv5XXzYYS-jGhz3UqaARNCGsD-u-iV1qYgKU4560TVrF2lbYFXy-M42z_8R0zNYgLFzL2HoOTDe-O9fdxSnTkCn7H1qcPf85wxjo2Cs8Zz94Nc07PDXIr8WaoDmaXdO8K2gf647T00v1emaIcqbT-nVgYbZNPl8nZrLxVn0aNMaXIYj_fERsi4Xxqw&token_type=Bearer&expires_in=28800&scope=openid%20profile%20email%20csRA&state=7700974972365405

Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Sun, 31 May 2015 16:58:19 GMT
````

I would appreciate any help at all.  @brockallen we have tried this on two different domains and two different VMs (XP + IE8 & Win7 + IE8), both behave the same.  Chrome works on both those VMs.

**Comment by stevenfirstrowinc** [comment]
ok, figured this out.  my location URL is too long.  When I change the access token to a reference token all is well.  I guess I need to further limit the data I return in the JWT token or switch to reference token.  The issue is we use some of the items in the access token to determine views in the app but I do think there is probably some unnecessary data being included.

**Comment by huysentruitw** [comment]
Yeah, it's over 2800 chars while URL's in IE8 are limited to 2083. Haven't used it before, but what about the [UserInfo Endpoint](http://identityserver.github.io/Documentation/docs/endpoints/userinfo.html) ?

**Comment by stevenfirstrowinc** [comment]
ah, you mean in order to get the additional data/roles I need?  If so I think they just may work.  Thank you!

**Comment by brockallen** [comment]
Or you can use reference tokens

**Comment by stevenfirstrowinc** [comment]
reference tokens would solve for this, but I believe I'd still have to call Userinfo if I want to alter my client side views for the UI correct?  I don't think there is a way to parse reference tokens right?

**Comment by brockallen** [comment]
Reference tokens wouldn't change the client. On the API side you'd need to validate the reference token with IdSvr, but if you're already using the UseIdtntityServerBearerAuth middleware then it can already do that (and might already be doing it).

**Comment by stevenfirstrowinc** [comment]
sorry I'm probably confusing it using wrong terms.  My UI is javascript (Angular) and I currently parse the token in order to get the roles I need to hide UI elements.  I don't think I could do that with reference tokens right?  

But you are right the Api side would not have to change.

**Comment by brockallen** [comment]
if the client needs the identity of the user, than that's done via the id_token. To call an API that's done with the access token -- 2 diff tokens for diff purposes.

**Comment by stevenfirstrowinc** [comment]
perhaps this is my problem, but id_token does not include role claims correct?

**Comment by brockallen** [comment]
You can configure it to by adding a roles scope or a custom scope with a role claim.

**Comment by stevenfirstrowinc** [comment]
ok, I got that now.  Thank you.  That does still seem to bring up the total length a bit but I think we can probably live with it for a bit longer or at worst case maybe use the suggestion by @huysentruitw for userinfo endpoint 

Thank you for the help
