### ISSUE TITLE
Using a Webforms/MVC hybrid as IdentityServer Client won't redirect for authorization

### ISSUE THREAD

**Issue by chrismikec** [IdentityServer/IdentityServer3#1405]
I've got an IdentityServer setup based on the MVC walkthrough sample, only it is a standalone server with no client built-in. I moved the client code out to a separate MVC project and the two can talk no problem, and I get a redirect to a login page when I try to access an action needing authorization.

However, if I move the client code to a hybrid webformv/MVC project it does not work. When I call an action with AuthorizeAttribute, I can see that "RedirectToIdentityProvider" function gets hit, but after that I get the following exception in the global.asax Application_Error handler:

<b><i>
System.NullReferenceException: Object reference not set to an instance of an object.     at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<ApplyResponseChallengeAsync>d__c.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<ApplyResponseCoreAsync>d__b.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<ApplyResponseAsync>d__8.MoveNext()  --- End of stack trace from previous location where exception was thrown ---   
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<TeardownAsync>d__5.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()  --- End of sta
ck trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Owin.Host.SystemWeb.IntegratedPi
peline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)     at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()     at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)"
</i></b>

I turned on tracing on the IdentityServer and I get nothing so it looks like the request never gets sent. Fiddler seems to support this as I only see requests go to the server when the client is the pure MVC.

The client side code is as follows:

        app.UseOpenIdConnectAuthentication(New OpenIdConnectAuthenticationOptions() With { _
            .Authority = "https://MyMachine/MyIdentityServer/identity", _
            .ClientId = "mvc", _
            .Scope = "openid profile roles sampleApi", _
            .ResponseType = "id_token token", _
            .RedirectUri = "http://localhost/MyClient/Account/Login", _
            .SignInAsAuthenticationType = "Cookies", _
            .UseTokenLifetime = False, _
            .Notifications = New OpenIdConnectAuthenticationNotifications() With { _
                .SecurityTokenValidated = Async Function(n)
                                              Dim nid = New ClaimsIdentity(
                                                        n.AuthenticationTicket.Identity.AuthenticationType,
                                                        ClaimTypes.GivenName,
                                                        ClaimTypes.Role)

                                              ' get userinfo data
                                              Dim userInfoClient = New UserInfoClient(
                                                                    New Uri(
                                                                        n.Options.Authority + "/connect/userinfo"),
                                                                    n.ProtocolMessage.AccessToken)

                                              Dim userInfo = Await userInfoClient.GetAsync()
                                              userInfo.Claims.ToList().ForEach(Sub(ui) nid.AddClaim(New Claim(ui.Item1, ui.Item2)))

                                              ' keep the id_token for logout
                                              nid.AddClaim(New Claim("id_token", n.ProtocolMessage.IdToken))

                                              ' add access token for sample API
                                              nid.AddClaim(New Claim("access_token", n.ProtocolMessage.AccessToken))

                                              ' keep track of access token expiration
                                              nid.AddClaim(New Claim("expires_at", DateTimeOffset.Now.AddSeconds(Integer.Parse(n.ProtocolMessage.ExpiresIn)).ToString()))

                                              ' add some other app specific claim
                                              nid.AddClaim(New Claim("app_specific", "some data"))

                                              n.AuthenticationTicket = New AuthenticationTicket(nid, n.AuthenticationTicket.Properties)

                                          End Function, _
                .RedirectToIdentityProvider = Function(n)
                                                  If n.ProtocolMessage.RequestType = OpenIdConnectRequestType.LogoutRequest Then
                                                      Dim idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token")

                                                      If idTokenHint IsNot Nothing Then
                                                          n.ProtocolMessage.IdTokenHint = idTokenHint.Value
                                                      End If
                                                  End If

                                              End Function
            }
        })

The only difference I can see here is that the project was a webforms project that I added MVC to. I'm not convinced this is just due to the project type, but it is the only thing I can see.

Perhaps some other configuration thing getting in the way?

Thanks!

**Comment by brockallen** [comment]
You'll need to put some breakpoints in your callbacks to find out what's _null_.

**Comment by chrismikec** [comment]
Thanks Brock, but when you say callbacks do you mean the notifications in the OpenIdConnectAuthenticationOptions on the client? If so, I added all of the notifications (SecurityTokenValidated, AuthenticationFailed, AuthorizationCodeReceived, etc.) and put breakpoints in them all but the only one that ever gets hit is RedirectToIdentityProvider, and since the request type is not Logout it basically does nothing and exits.

If these aren't the callbacks you mean, where can I find them? I they are the ones, any further suggestions as to how to debug this?

**Comment by brockallen** [comment]
Well, the call stack above doesn't seem to provide much help, so I was assuming the exception was from somewhere in your code. If it's not then perhaps it's from Microsoft's code. Perhaps ask them.

**Comment by chrismikec** [comment]
Weird. I took a look at the OWIN code, and the origination function of that exception seems to call the RedirectToIdentityProvider notification. So, I tried removing that notification from my OpenIdConnectAuthenticationOptions (I don't think I need it anyway), and now everything works fine.

Any idea why this might be? Not a big deal for me now, but if I need to add that back in the future I would imagine I'll beb attling the same problem.

**Comment by brockallen** [comment]
So put your code back in and walk thru it line by line. It must be something in there.

**Comment by chrismikec** [comment]
Already did, no problems. The notification callback returns quite happily. As well, it is the same code that is called from the other client and it works fine. The code actually came from the IdentityServer MVC sample.

It bugged me a bit that it was a Function as opposed to Sub but we weren't returning anything, so I added a "Return Task.FromResult(0)" to the end of the callback and everything was happy again. I noticed other examples out there where people were doing this too.

Perhaps it is worth modifying the samples to add this in? No idea why the original sample code itself didn't have this problem. Perhaps some nuance in the difference between VB.NET and C#?

**Comment by brockallen** [comment]
If you return null/Nothing then I can understand the exception -- you're expected to return a valid Task.

**Comment by johnkors** [comment]
Right, then @chrismikec raises a valid question about the samples, as they don't return a valid task neither.  

https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client%20(Hybrid)/Startup.cs#L82

**Comment by brockallen** [comment]
It's because they have _async_ on the delegate.

**Comment by johnkors** [comment]
ah, duh. Thanks.

**Comment by chrismikec** [comment]
Interesting. I can put async on the delegate in VB, but the compiler gives a warning. Regardless, it works this way too.

Unfortunate side effect of running in VB.NET (not by choice I might add).

Thanks for the assistance.
