### ISSUE TITLE
AccessTokenType.Reference - selfdependent without running idserver instance?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1408]
I presumed using reference tokens any request i.e. decorated with that token in the request header results in target api consulting the idserver to extract more data of the reference(token)
But I found that I can request my api with the referencetoken in header without having a running idserverinstance required.

What do I miss?

**Comment by brockallen** [comment]
You need to use the bearer token middleware in the api to validate the access tokens.

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation

**Comment by davidmrichter** [comment]
Thats what I already have implemented. Nevertheless using the api with the (reference)token does not require an active idserver instance?!


'JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

			app.UseIdentityServerBearerTokenAuthentication(
                new IdentityServerBearerTokenAuthenticationOptions { Authority = Configs.IdentityAccessServiceURI, RequiredScopes = new[] { "MyWebApp" } });			

			app.UseResourceAuthorization(new AuthorizationManager());

**Comment by brockallen** [comment]
The `UseIdentityServerBearerTokenAuthentication` will accept the reference token and contact IdSvr to validate it. So yes, IdSvr does have to be up and running.

**Comment by davidmrichter** [comment]
ok
