### ISSUE TITLE
Get different user Claims at different tiers

### ISSUE THREAD

**Issue by akarel** [IdentityServer/IdentityServer3#1410]
What would be the best way to get different claims at different tiers of our application stack? 

For example, we have an Angular app that gets a token from Idsrv and uses it to call our protected API. At this point the only claims we want exposed are very generic (e.g. user ID, roles, etc), only what is required for the UI. The API then calls a WCF service that handles our data calls and business engines. This WCF service needs additional claims to ensure only the appropriate data is returned.

Is there an existing method for a trusted resource to acquire information about a provided user? Can I send the ID Token along? Or will I have to go the route of registering a custom service in Idsrv? I feel like I'm overlooking something obvious.

**Comment by brockallen** [comment]
You can build the concept of an 'act-as' mechanism with IdSvr -- so the first layer goes back to IdSvr to get a new token for the next API layer. You'd build this as a custom grant type, which we have some samples for.

**Comment by akarel** [comment]
I ran over the samples quickly, and I believe I get the gist of it. The second token, retrieved by the API, would include the additional claims thanks to the custom grant type, which would then be used to access the WCF layer. So our first layer (the API) would be a protected resource and a client. Is that more or less the idea?

**Comment by brockallen** [comment]
Yea. The first token would be the input (aka custom grant) to the token endpoint. Your custom grant validator would run to 'approve' the request, and a new token would be returned for the client to call the next layer in your architecture.

**Comment by akarel** [comment]
Got it. Thanks for quick replies! Much appreciated!
