### ISSUE TITLE
Enable Client Cors Service by default

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#1411]
Ensure proper lazy queries (only if Origin is present in request) & do some reasonable caching.

**Comment by brockallen** [comment]
@leastprivilege 

Ok, so yea -- starting looking at this and we're blocked since we don't have a service interface to load all the clients (or their origins). The EF implementation works by directly accessing the `DbContext` for the clients.

Perhaps we modify the `IClientStore` to have an API to load this data? Or do we do a new service interface?

Or, we could simply have the In-Mem Cors implementation auto-registered when we register the In-Mem client store? We could do the same for the EF client store as well, then.

**Comment by leastprivilege** [comment]
See my pr.

**Comment by brockallen** [comment]
So then this automatic CORS registration would only work for InMemory users/

**Comment by leastprivilege** [comment]
And there would be an extension method which does the same for ef or whatever backing store.

**Comment by brockallen** [comment]
Yep.

**Comment by brockallen** [comment]
Already done via: https://github.com/IdentityServer/IdentityServer3/pull/1433
