### ISSUE TITLE
HttpRequestMessage in IViewService

### ISSUE THREAD

**Issue by julianpaulozzi** [IdentityServer/IdentityServer3#1412]
I created successfully the location service for the views where it is allowed to change the language dynamically: [ViewLocalization](https://github.com/julianpaulozzi/IdentityServer3.Contrib.ViewLocalization).

I would like to create something lighter with static pages without getting stuck in a specific language, as the previous case does everything on the client side using angular-translate.

It would be easy only by using the "IViewService" however would have to be some way to have the "HttpRequestMessage" in order to extract some header information, specifically AcceptLanguage and maybe some cookie.

Is there any way to do it or would be possible to include it as a parameter?

**Comment by brockallen** [comment]
Inject the IOwinEnvironment service into your view service.

**Comment by julianpaulozzi** [comment]
I did not find the IOwinEnvironment but I found the OwinEnvironmentService which is injected properly.
Simple and functional, just create an instance of "OwinContext" passing this as a parameter.

Thank you, excellent job.

**Comment by brockallen** [comment]
Yep, that's what I meant :)
