### ISSUE TITLE
Override welcome page

### ISSUE THREAD

**Issue by scottrudy** [IdentityServer/IdentityServer3#1413]
I can't seem to override the welcome page using embedded assets. Is this by design?

**Comment by loctanvo** [comment]
That's currently by design and meant for development only. You can always disable it by setting `EnableWelcomePage` to `false`. [Documentation](http://identityserver.github.io/Documentation/docs/configuration/identityServerOptions.html)

Previous discussions: #942 #857

**Comment by scottrudy** [comment]
Great. Thanks for the link to the other issues, as that provides a workaround.
