### ISSUE TITLE
ImplicitClient - Updating RP cookie if idsvr session is active via OWIN

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#1414]
Hi,

We have the following scenario:

- User goes to home page for RP
- User clicks login, is redirected to idsvr, logs into idsvr and is redirected back to RP. The RP then displays menus for the authenticated user. The RP cookie will be set to 5 minutes non-sliding, idsvr cookie is sliding 1 hour.
- After 5 minutes, the RP will reauthenticate with idsvr and a new RP cookie will be issued
- The user is inactive for 10 minutes. If they click the home page (or any unsecured page), they should be able to get to the page. However, when they do, they aren't presented with their authenticated options because the RP hasn't gone back to idsvr to reauthenticate.

We are using the implicit cilent in mvc using owin.
Would it be possible to create a custom auth Attribute that does the following:

- If the user is current in idsvr it should return the token and the owin middleware creates a new RP cookie as per normal.
- If the user is not active in idsvr, no login screen is presented by idsvr. No token is returned, and the middleware treats this as an unauthorised user.

It looks like I could try calling the Authorization/Authentication Endpoint directly using the "Prompt" parameter set to none. Not sure if this is the correct approach or not. Not sure how I would call this from .net using the middleware.

any help would be great.

**Comment by brockallen** [comment]
You can tweak the login behavior by passing the prompt and max_age params to the authorize endpoint.

**Comment by parkinsona** [comment]
I'll have a look into the max_age parameter.

Is there a sample of how to call the auth endpoint from mvc?

**Comment by brockallen** [comment]
You'd modify the Protocol property in the Notifications callback (RedirectingToIdentityProvider event or whatever it's called).

**Comment by parkinsona** [comment]
It looks like prompt = "none" is the option I'm after. This is good when the idsvr session is still current.
When the idsvr session is not current, I can catch it in the AuthenticationFailed handler by doing the following:
``` c#
 AuthenticationFailed = async n =>
                                   {                                    
                                       n.HandleResponse();
                                       n.Response.Redirect("someURL");                                   
                                   },
```
The problem with this approach is that it happens for ALL requests requiring Authorization. I only want it to happen for a handful of pages.  Is there some way in RedirectToIdentityProvider to identify where the request came? I know I can check for the URI in the Request object in the context for RedirectToIdentityProvider. If I take this approach, I'd have to maintain a list of URIs that get handled this way. I also can't see a way in the AuthenticationFailed handler to know what the location of the original uri that was requested.

**Comment by brockallen** [comment]
You'd have to coordinate that logic and those flags within your own application.

**Comment by parkinsona** [comment]
I still haven't sorted out a way to fix this, I'm hoping I can get time to look at it soon.
