### ISSUE TITLE
 [Question] Redirect to external authentication

### ISSUE THREAD

**Issue by vvolkgang** [IdentityServer/IdentityServer3#1415]
Hi,

I've previously asked something similar to this [here](http://stackoverflow.com/questions/30357744/identityserver3-with-external-user-management) and [here](http://stackoverflow.com/questions/30485401/substitute-identityserver3-login-system) but I didn't asked the right questions. What I need is to authenticate the user by redirecting to an outside Login (which can be configured to callback what's necessary), ie, when required my login page should be shown, instead of  `/core/login` 

I've researched about `IUserService` and checked the samples, but I don't know how that functionality can be leveraged for this scenario, for the following reasons:

- `AuthenticateExternalAsync` requires a katana middleware implementation. Is this really necessary?
- `AuthenticateLocalAsync` would require me to do the login in the background by making a call to the server but, at least for now, this is not possible.

**Comment by brockallen** [comment]
You can handle preauthenticate in the user service and emit a partial login to redirect to your custom login page.

**Comment by vvolkgang** [comment]
@brockallen Any sample / doc that illustrates that? The [partial login documentation](https://github.com/IdentityServer/IdentityServer3/issues/1415) led me to believe it would only be another step in the normal login and not a complete redirect, addind the katana external provider requirement.

**Comment by brockallen** [comment]
Not sure we have a sample for PreAuthenticate. It's meant to bypass the login screen. You can combine that with a partial login.

**Comment by vvolkgang** [comment]
I'm not following what you mean, but i've found this, is this the [implementation](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomHrd/CustomHrd/HrdUserService.cs) you had in mind? Implementing a middleware and using the partial login to set the idp in the message?

If not, is it possible for your to provide a code example of the user service?

**Comment by brockallen** [comment]
I think that sample is a good place to start (I had forgotten about it).
