### ISSUE TITLE
No signin id passed

### ISSUE THREAD

**Issue by JeroenMX** [IdentityServer/IdentityServer3#1416]
I keep getting 'No signin id passed' / 'There is an error determining which application you are signing into' no matter what i do. I'm using Idsvr3 as primary STS with ADFS as (the only one for now) external identity provider (or that's what i want). 

This is the debug result:

<pre><code>iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 29-05-2015 12:37:05 +00:00 -- External login requested for provider: adfs
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 29-05-2015 12:37:05 +00:00 -- Triggering challenge for external identity provider
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.CorsPolicyProvider]: 29-05-2015 12:37:12 +00:00 -- CORS request made for path: /connect/token from origin: https://svr-adfs
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Services.Default.DefaultCorsPolicyService]: 29-05-2015 12:37:12 +00:00 -- AllowedOrigins configured and origin https://svr-adfs is allowed
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.CorsPolicyProvider]: 29-05-2015 12:37:12 +00:00 -- CorsPolicyService allowed origin
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 29-05-2015 12:37:12 +00:00 -- Callback invoked from external identity provider
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 29-05-2015 12:37:12 +00:00 -- No signin id passed</code></pre>

these cookies get created:
![capture](https://cloud.githubusercontent.com/assets/12659542/7882785/68508a5a-0611-11e5-91c6-e94599a4488a.PNG)

my code:

<pre><code>public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());

            AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject;
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            var options = new IdentityServerOptions
            {
                SiteName = "Embedded IdentityServer",
                SigningCertificate = LoadCertificate(),

                Factory = InMemoryFactory.Create(Users.Get(), Clients.Get(), Scopes.Get()),

                AuthenticationOptions = new AuthenticationOptions { IdentityProviders = ConfigureIdentityProviders },
                CorsPolicy = ConfigureCors("https://svr-adfs")
            };

            app.UseIdentityServer(options);
        }

        private CorsPolicy ConfigureCors(params string[] allowedHosts)
        {
            var policy = new CorsPolicy();
            allowedHosts.ForEach(p => policy.AllowedOrigins.Add(p));
            return policy;
        }
       
        private void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            const string realm = "https://localhost:44319";
            const string issuer = "http://svr-adfs/adfs/services/trust";
            const string signingCertThumbprint = "adfs cert thumbprint goes here";

            var audienceRestriction = new AudienceRestriction(AudienceUriMode.Always);
            audienceRestriction.AllowedAudienceUris.Add(new Uri(realm));

            var issuerRegistry = new ConfigurationBasedIssuerNameRegistry();
            issuerRegistry.AddTrustedIssuer(signingCertThumbprint, issuer);

            app.UseWsFederationAuthentication(
                new WsFederationAuthenticationOptions(WsFederationAuthenticationDefaults.AuthenticationType)
                {
                    AuthenticationType = "adfs",
                    Caption = "Active Directory",
                    Wtrealm = realm,
                    MetadataAddress =
                        "https://svr-adfs/federationmetadata/2007-06/federationmetadata.xml",                   
                    SignInAsAuthenticationType = signInAsType,                    
                    SecurityTokenHandlers = new SecurityTokenHandlerCollection
                    {
                        new EncryptedSecurityTokenHandlerEx(new X509CertificateStoreTokenResolver(StoreName.My,
                            StoreLocation.LocalMachine)),
                        new SamlSecurityTokenHandlerEx
                        {
                            CertificateValidator = X509CertificateValidator.None,
                            Configuration = new SecurityTokenHandlerConfiguration()
                            {
                                AudienceRestriction = audienceRestriction,
                                IssuerNameRegistry = issuerRegistry
                            }
                        }
                    }
                });
        }
}</code></pre>

**Comment by brockallen** [comment]
You say those cookies get created, but are they being passed to the login endpoint? The error is basically saying the signin message cookie is not present, so you'd have to check at the HTTP level is it's being passed.

**Comment by brockallen** [comment]
Any update?

**Comment by daluas** [comment]
Hello,

I'm facing the same issue. From time to time, identity server throws the error: "There is an error determining which application you are signing into". Looking to the trace, we found: 

w3wp.exe Information: 0 : 2017-11-27 07:15:37.370 +01:00 [Information] Rendering 204
w3wp.exe Information: 0 : 2017-11-27 07:15:42.477 +01:00 [Information] External login requested for provider: "Google"
w3wp.exe Information: 0 : 2017-11-27 07:15:42.477 +01:00 [Information] Triggering challenge for external identity provider
w3wp.exe Information: 0 : 2017-11-27 07:15:43.196 +01:00 [Information] Callback invoked from external identity provider
w3wp.exe Information: 0 : 2017-11-27 07:15:43.196 +01:00 [Information] No signin id passed
w3wp.exe Information: 0 : 2017-11-27 07:15:43.492 +01:00 [Information] CSP Report endpoint requested

Restarting IIS fixes the problem. The cookie is present in the browser.

How can we fix this issue?
