### ISSUE TITLE
app.FormPostResponse.js 404

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1417]
I'm getting 404 on this resource while running everything at localhost. I've tried enabling/disabling CspOptions, PublicOrigin is set to localhost, nothing helps. Any thoughts?

**Comment by brockallen** [comment]
You must also have RAMMFAR enabled too, right? You'd not get this far without that...

You're using IdSvr via NuGet and not from source, right?

**Comment by snothub** [comment]
I did not have RAMMFAR on identityserver. That helped. Thanks
