### ISSUE TITLE
Customer Authentication and  return URL

### ISSUE THREAD

**Issue by moiseyo** [IdentityServer/IdentityServer3#1418]
Using Sample  "User Service"  I was able to make authentication  with customized provider.

The code  i tested 
Does not return to call page 

I trued to create AuthenticateResult  3 diffrent ways and no good result 

If   I use  in memory authentication all works as expected 

What did I miss ?
------------------------------------------------

  public async override System.Threading.Tasks.Task<Thinktecture.IdentityServer.Core.Models.AuthenticateResult>
            AuthenticateLocalAsync(string username, string password, Thinktecture.IdentityServer.Core.Models.SignInMessage message)
        {
            //string file_name = @"c:\temp\short\1.ser";
            //FileStream fs = new FileStream(file_name, FileAccess.Write);

            var form = await ctx.Request.ReadFormAsync();
            var clientid = form["clientid"];
            Thinktecture.IdentityServer.Core.Models.AuthenticateResult result;

            IList<Claim> claimCollection;

            try
            {

 
                UniversalTaxSystems.Security.User CurrentUser = UniversalTaxSystems.Security.User.GetUser(Guid.Empty);
                Int32 ClientID = Int32.Parse(clientid);
                String UserName = username;
                String Password = password;
                UniversalTaxSystems.Security.UserValidateFailureReason Reason = new UniversalTaxSystems.Security.UserValidateFailureReason();
                var login = UniversalTaxSystems.Security.User.Validate(ClientID, UserName,
                    Password, ref CurrentUser, ref Reason, "xxxxx");

                if (login)
                {
                        claimCollection = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, username)
                        , new Claim(ClaimTypes.Country, "USA")
                        , new Claim(ClaimTypes.Gender, "M")
                        , new Claim(ClaimTypes.Surname, CurrentUser.LastName)
                        , new Claim(ClaimTypes.Email,CurrentUser.EmailAddress )
                        , new Claim(ClaimTypes.Role, CurrentUser.AssignedRoles.First().ToString())
                    };

                    ExternalIdentity externalidentity = new ExternalIdentity();

                
                    externalidentity.Claims = claimCollection;
                    externalidentity.Provider = "CHHSFS";
                    externalidentity.ProviderId = "cchsfs";
                    Uri redirect = new Uri(message.ReturnUrl);

                    //result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult(redirect.PathAndQuery, username, username, claimCollection);
                    result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult( username, username, claimCollection);
                  //  result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult( redirect.PathAndQuery,externalidentity);

                }
                else
                {

                    result = await base.AuthenticateLocalAsync(username + "XXXXXXX", password + "YYYYY", message);

                }

                // result = await base.AuthenticateLocalAsync("alice", "alice", message);

                //   

                //result.User.Claims = claimCollection;

                return result;
            }
            catch (Exception ext )
            {
                var mess = ext.Message;
            
            }
            return await base.AuthenticateLocalAsync(username + "XXXXXXX", password + "YYYYY", message);
        }    
 
    }
------------------------------------------------

**Comment by brockallen** [comment]
What's the error? Check the logs to find out more information.

**Comment by moiseyo** [comment]
No  errors  just    redirect   never was used.
Do you have a  sample how  how  make  redirect back  happen


Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by moiseyo** [comment]
Fo You have a Book , I'll buy it.


Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by brockallen** [comment]
Make sure you're using the correct overload of the AuthenticateResult ctor. Check the docs for details:https://identityserver.github.io/Documentation/docs/advanced/userService.html

**Comment by moiseyo** [comment]
Thank  you Alan.
Alan you are grant  programmer and  nice person.
First  : Is Azure  build with you server ?
I made a  simple   change :
-------------------------------------------------------------

//  result = new
Thinktecture.IdentityServer.Core.Models.AuthenticateResult(
redirect.PathAndQuery,externalidentity);
 return await AuthenticateExternalAsync(externalidentity, message);

=================================================

No Redirect  worked


I'm working with Hybrit Client  using  samples , and I client

in placees   underscore  I got value null  exeption:

*claims.Add(new Claim("access_token", response.AccessToken));*
claims.Add(new Claim("expires_at",
DateTime.Now.AddSeconds(response.ExpiresIn).ToLocalTime().ToString()));*claims.Add(new
Claim("refresh_token", response.RefreshToken));**claims.Ad*d(new
Claim("id_token", n.ProtocolMessage.IdToken));


May be sample is not completed


I sample  ExpenseTracker

All  Works   except I cannot   get  user info  or  user claims in client.


Thank you  for Help








Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

On Sun, May 31, 2015 at 2:04 PM, Brock Allen <notifications@github.com>
wrote:

> Make sure you're using the correct overload of the AuthenticateResult
> ctor. Check the docs for details:
> https://identityserver.github.io/Documentation/docs/advanced/userService.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3/issues/1418#issuecomment-107228816>
> .
>

﻿
using Microsoft.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Thinktecture.IdentityServer.Core.Models;
using Thinktecture.IdentityServer.Core.Services;
using Thinktecture.IdentityServer.Core.Services.InMemory;

namespace SampleApp
{
    public class UserService : InMemoryUserService
    {
        private IOwinContext ctx;

        private UniversalTaxSystems.Security.User _userLoggingIn;
        private Guid userId = Guid.Empty;

        public UniversalTaxSystems.Security.User UserLoggingIn
        {
            get
            {
                if (this._userLoggingIn == null)
                {
                    if (userId == null)
                    {
                        return null;
                    }
                    this._userLoggingIn = UniversalTaxSystems.Security.User.GetUser((Guid)userId);
                }
                return this._userLoggingIn;
            }
            set
            {
                this._userLoggingIn = value;
                if (value == null)
                {
                }
                else
                {
                    userId = value.Id;
                }
            }
        }

        public UserService(List<InMemoryUser> users, OwinEnvironmentService env)
            : base(users)
        {
            ctx = new OwinContext(env.Environment);
        }
#if sample
        public async override System.Threading.Tasks.Task<Thinktecture.IdentityServer.Core.Models.AuthenticateResult> AuthenticateLocalAsync(string username, string password, Thinktecture.IdentityServer.Core.Models.SignInMessage message)
        {
            var form = await ctx.Request.ReadFormAsync();
            var extra = form["extra"];

            return await base.AuthenticateLocalAsync(username, password, message);
        }

#else
        public async override System.Threading.Tasks.Task<Thinktecture.IdentityServer.Core.Models.AuthenticateResult>
            AuthenticateLocalAsync(string username, string password, Thinktecture.IdentityServer.Core.Models.SignInMessage message)
        {
            //string file_name = @"c:\temp\short\1.ser";
            //FileStream fs = new FileStream(file_name, FileAccess.Write);

            var form = await ctx.Request.ReadFormAsync();
            var clientid = form["clientid"];
            Thinktecture.IdentityServer.Core.Models.AuthenticateResult result;

            IList<System.Security.Claims.Claim> claimCollection = null;
            try
            {
                //ClaimsIdentity claimsIdentity = new ClaimsIdentity(claimCollection, "CustomApiKeyAuth");

                UniversalTaxSystems.Security.User CurrentUser = UniversalTaxSystems.Security.User.GetUser(Guid.Empty);
                Int32 ClientID = Int32.Parse(clientid);
                String UserName = username;
                String Password = password;
                UniversalTaxSystems.Security.UserValidateFailureReason Reason = new UniversalTaxSystems.Security.UserValidateFailureReason();
                var login = UniversalTaxSystems.Security.User.Validate(ClientID, UserName,
                    Password, ref CurrentUser, ref Reason, "xxxxx");

                if (login)
                {
                    claimCollection = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, username)
                        , new Claim(ClaimTypes.Country, "USA")
                        , new Claim(ClaimTypes.Gender, "M")
                        , new Claim(ClaimTypes.Surname, CurrentUser.LastName)
                        , new Claim(ClaimTypes.Email,CurrentUser.EmailAddress )
                        , new Claim(ClaimTypes.Role, CurrentUser.AssignedRoles.First().ToString())
                    };

                    ExternalIdentity externalidentity = new ExternalIdentity();

                    externalidentity.Claims = claimCollection;
                    externalidentity.Provider = "CCHSFS";
                    externalidentity.ProviderId = username;
                    Uri redirect = new Uri(message.ReturnUrl);

                    //result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult(redirect.PathAndQuery, username, username, claimCollection);
                    //result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult( username, username, claimCollection);
                    //  result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult( redirect.PathAndQuery,externalidentity);
                    return await AuthenticateExternalAsync(externalidentity, message);
                }
                else
                {
                    result = await base.AuthenticateLocalAsync(username + "XXXXXXX", password + "YYYYY", message);
                }

              

                return result;
            }
            catch (Exception ext)
            {
                var mess = ext.Message;
            }
            return await base.AuthenticateLocalAsync(username + "XXXXXXX", password + "YYYYY", message);
        }
#endif
    }
}

**Comment by brockallen** [comment]
I'd suggest starting with one of our working samples, and then change it to suit your environment. I can't debug all of your code pasted above.

**Comment by moiseyo** [comment]
The problem  is in code

Refused to execute inline script because it violates the following Content
Security Policy directive: "script-src 'self' ". Either the 'unsafe-inline'
keyword, a hash ('sha256-6JvZSY50qs_bPu7iYe6jF3__8vhG3Pm0xjbeljPJocY='), or
a nonce ('nonce-...') is required to enable inline execution.
(anonymous function) @ jQuery.js:3176(anonymous function) @
jQuery.js:3208(anonymous function) @ jQuery.js:4376

Thank you


Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by brockallen** [comment]
This is a CSP error. You're adding JS or CSS to the pages in IdSvr. They need to be added as external files and if from a different origin then add them to the CSP options: https://identityserver.github.io/Documentation/docs/advanced/csp.html

**Comment by moiseyo** [comment]
Grate


Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by moiseyo** [comment]
I still get  error
- response {Thinktecture.IdentityModel.Client.TokenResponse}
Thinktecture.IdentityModel.Client.TokenResponse
_httpErrorReason null string
_httpErrorstatusCode 0 System.Net.HttpStatusCode
_isHttpError false bool
AccessToken null string
Error "invalid_client" string
ExpiresIn 0 long
HttpErrorReason null string
HttpErrorStatusCode 0 System.Net.HttpStatusCode
IdentityToken null string
IsError true bool
IsHttpError false bool
+ Json {
  "error": "invalid_client"
} Newtonsoft.Json.Linq.JObject
 *Raw "{\"error\":\"invalid_client\"}" string*
RefreshToken null string
TokenType null string



Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by brockallen** [comment]
So enable logging in IdSvr to understand why you're not getting back a successful response.

**Comment by moiseyo** [comment]
Yes Allen.
Allen I'm  able to  login , navigation logic works as expected, javascript
errors gone..

Tracking  error  - in responce object  Newtonsoft.Json.Linq.JObject
 *Raw "{\"error\":\"invalid_client\"}" string*

 I created  a log full login and loginoff  may you fill find a problem an a
fly

I suspect problem with server settings


Still  is Azure
Thinktecture?


Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by moiseyo** [comment]
Ale, I got that  forget prev email

Still  is Azure
Thinktecture?



Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by brockallen** [comment]
I'm closing this thread -- if you have other questions, open new issues.
