### ISSUE TITLE
Guidance for token validation and claims in WCF service using IdentityServer

### ISSUE THREAD

**Issue by chrismikec** [IdentityServer/IdentityServer3#1419]
I'm having trouble finding any guidance as to how to use IdentityServer with WCF services.

My setup is such that I am authenticating against IdentityServer successfully via a website, then I have a series of WCF services as a service layer. I'd like to be able to use token authentication with each one, along with assigning the users claims to the Principal in the service.

I assume I have to register each WCF service as a client, but I'm not sure how to pass the token to the service, and have the service validate the token against IdentityServer.

I'm not using a wstrust binding, so I'm not sure if any of the WS-trust info or plug-in applies to me (though I could be way off base).

Any pointers are appreciated. Are there any samples or documentation for this kind of thing?

**Comment by leastprivilege** [comment]
There is no built-in support for WCF - that said - WCF can consume JWT tokens. There is another thread somewhere here with people working on that.

https://github.com/IdentityServer/IdentityServer3/issues/1107

**Comment by Bigshooter** [comment]
1107 is also closed, is there another thread still working on this or has it been abandoned at this point?

**Comment by leastprivilege** [comment]
I finally got some time to look into that and got it working - will post a sample soon.
