### ISSUE TITLE
Make ValidateAntiForgeryTokenAttribute public

### ISSUE THREAD

**Issue by B3nCr** [IdentityServer/IdentityServer3#1421]
Hi

I've create a new login view with a registration form on the view as a few others have also done. 

It works great but I can't validate an anti forgery token. 

I can't use the @HTML helper to generate the form field as done in "normal" MVC  

I cant use the anti forgery model.value in a hidden input control as I'm getting browser content security errors when I try to use set the input value.

I can't use the directive because the anti forgery attribute isn't available.

**Comment by B3nCr** [comment]
I realise it's unlikely that you'll make this public, it would be a strange addition to the API for IdSvr but perhaps extracting it as a separate package might work

**Comment by brockallen** [comment]
Are you doing MVC? MVC already has its own anti xsrf mechanism.

**Comment by B3nCr** [comment]
Hi Brock

I'm sortof using MVC but the registration form is in the _login template so
that it can login the user after the registration form has been
successfully posted.

I can't use the MVC XSRF mechanism because server side helpers don't seem
to work in the template. I'm going to try hijacking the Angular XSRF
mechanism since the login pages uses an angular app.

Thanks
Ben

**Comment by B3nCr** [comment]
I'm not getting anywhere with the Angular XSRF method because I can't set the cookie.

**Comment by B3nCr** [comment]
I've implemented my own view service which creates it's own XSRF token and injects it into the model.
