### ISSUE TITLE
Using different certificates for SSL and signing won't work

### ISSUE THREAD

**Issue by hansmaad** [IdentityServer/IdentityServer3#1422]
I'm currently using IdentityServer on the same server as my WebAPI. As `SigningCertificate` we use a self signed certificate that will be loaded from cert store in `Startup`. If I use the same certifcate in the IIS https binding everything works. 
If I use another certifcate from a CA in the IIS binding but keep the self signed certificate as `SigningCertificate` I can access the WebAPI and the token service enpoint, but the access token validation seems to fail (silently).

	 -- Start token request
	 -- Start client validation
	 -- Client validation success
	 {
	  "ClientId": "...",
	  "ClientName": "...",
	  "ClientCredentialType": "FormPost"
	}
	 -- Start token request validation
	 -- Start password token request validation
	 -- Password token request validation success.
	 -- Token request validation success
	 {
	  "ClientId": "...",
	  "ClientName": "...",
	  "GrantType": "password",
	  "Scopes": "read",
	  "UserName": "bob",
	  "AuthenticationContextReferenceClasses": []
	}
	 -- Creating token response
	 -- Processing token request
	 -- Creating access token
	 -- Creating JWT access token
	 -- End token request
	 -- Returning token response.
	 : Request, Method=GET, Url=https://localhost/.../projects/, Message='https://localhost/.../projects/'
	 : Message='Projects', Operation=DefaultHttpControllerSelector.SelectController
	 : Message='Legend.WebApi.Controllers.ProjectsController', Operation=DefaultHttpControllerActivator.Create
	 : Message='Legend.WebApi.Controllers.ProjectsController', Operation=HttpControllerDescriptor.CreateController
	 : Message='Selected action 'GetAll()'', Operation=ApiControllerActionSelector.SelectAction
	 : Message='Will use same 'JsonMediaTypeFormatter' formatter', Operation=JsonMediaTypeFormatter.GetPerRequestFormatterInstance
	 : Message='Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'', Operation=DefaultContentNegotiator.Negotiate
	 : Operation=AuthorizeAttribute.OnAuthorizationAsync, Status=401 (Unauthorized)
	 : Operation=ProjectsController.ExecuteAsync, Status=401 (Unauthorized)
	 : Operation=JsonMediaTypeFormatter.WriteToStreamAsync
	 : Operation=ServerCompressionHandler.SendAsync, Status=401 (Unauthorized)
	 : Response, Status=401 (Unauthorized), Method=GET, Url=https://localhost/.../projects/, Message='Content-type='application/json; charset=utf-8', content-length=114'
	 : Operation=ProjectsController.Dispose

Is it not possible to use different certifcates?

	app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
	{
		Authority = "https://localhost/.../idsrv"
	});
	
	var options = new IdentityServerOptions()
	{
		RequireSsl = true,
		SigningCertificate = LoadCertificate(),
		Factory = factory,
	};
	....

**Comment by leastprivilege** [comment]
SSL and signing cert are completely unrelated. Not sure what error you are seeing - but it has nothing to do with the fact you are using 2 separate certs - that's actually the recommended configuration.

**Comment by hansmaad** [comment]
Sorry, the problem is that the new certificate is not issued to localhost, but the token validation uses `https://localhost/...`. So this is more an issue about missing tracing information about the failing request.

**Comment by brockallen** [comment]
Yes, chances are that the OIDC middleware is failing when loading the metadata because SSL is failing (due to the incorrect cert). That's Microsoft's code.
