### ISSUE TITLE
JWT - nested Claims- possible?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1423]
Hello.

We think to structure the JWT as following:

{
  "GeneralInfo_A": "Xema",
  "GeneralInfo_B": "Xemab",
  "Number": "1234-5678-9012-3456",
  "Farm": {
     "FarmNumber": "123232",
    "Adress": "Farmersville",
    "Animalspecies": "Equidaes"    
  },
  "Farm": {
    "FarmNumber": "42343",
    "Adress": "NewYork",
    "Animalspecies": "Cattle"    
  },
  "Farm": {
    "FarmNumber": "55555",
    "Adress": "colchose",
    "Animalspecies": "Pigs"    
  }
}

how can we hook in into Identityservers Accesstoken generation to create nested JWT's?

Thank you

**Comment by leastprivilege** [comment]
I personally thing you are abusing tokens and put way too much information into them - looks more like application data.

That said - we only support key/value pairs, not nested data structures. If you absolutely want to have "objects" - the ITokenSigningService is the place where the actual JWT gets produced.

**Comment by davidmrichter** [comment]
and not to mention: even if one would tweak the JWT being nested -  during later deserilalize into Claims - System.Security.Claims do not have SubClaims - so one would not benefit from the nesting.

**Comment by leastprivilege** [comment]
At least not with the Microsoft JWT handler yes.
