### ISSUE TITLE
AspNetIdentity and AspNetIdentity_2fa together

### ISSUE THREAD

**Issue by eaba** [IdentityServer/IdentityServer3#1425]
Please guide me:
I want to have to different Custom UserService, one for one factor and the second for two factor authentication when the user hits an action method protected with two-factor authentication Attribute.

How can I set this up? 
Thanks

**Comment by brockallen** [comment]
You can inspect the `acr_values` (https://identityserver.github.io/Documentation/docs/endpoints/authorization.html) in the `SignInMessage` in the user service's authenticate local API. This can be used as your flag to indicate 2fa is required for this request.

**Comment by eaba** [comment]
Thanks for the quick response.
Is it possible to change the value of it to, say, 'require_2fa' when user hit the action decorated with twofactor attribute.

Kindly help with a snippet.
thanks

**Comment by eaba** [comment]
Can you also kindly help with the code snippet to make this work in the user service's authenticate local API?

**Comment by brockallen** [comment]
I don't have a sample of doing this -- you'd have to build that yourself.

**Comment by eaba** [comment]
Can you help with a pseudo code; I just need a little insight!

**Comment by brockallen** [comment]
We have other samples already using the acr_values -- look for those.

**Comment by eaba** [comment]
Please which one should I look at?

**Comment by brockallen** [comment]
Really, you don't have a tool to search?

https://github.com/IdentityServer/IdentityServer3.Samples/search?utf8=%E2%9C%93&q=acr_values

**Comment by eaba** [comment]
One of those moment when, so many things in the head, outsourcing reliefs headache!!
Thanks
