### ISSUE TITLE
Announcement on 2.0.0

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#1426]
Just to let everyone know, 2.0.0 will contain breaking changes. Here's Dom's blog post with some more info:

http://leastprivilege.com/2015/03/29/identityserver3-vnext/

In addition we have changes to the `IUserService` interface to allow for future expansion (so one breaking change now to accommodate non-breaking changes in the future). I'm sure we will have other changes as well.

We don't know a milestone yet, but it will be soon-ish. We'd like to have as many people test out the changes so we can get feedback sooner rather than later. 

We've also changed the name of the assembly and the NuGet feed, which is here: https://www.nuget.org/packages/IdentityServer3

**Comment by brockallen** [comment]
Update:

I've pushed IdentityServer3 (2.0.0-beta5) and all the other libraries (EF, MR, AspId) (2.0.0-beta1) to NuGet. 

Anyone with an existing implementation that plans to update to 2.0.0 is strongly encouraged to just test against the new versions. We're looking for as much feedback as possible in case we need to adjust anything before we release 2.0.0. 

Thanks.

**Comment by leastprivilege** [comment]
Removed TraceLog and TraceSource providers - use Serilog (or any other LibLog supported library) instead

**Comment by leastprivilege** [comment]
Removed InMemoryFactory - use new extension methods instead

**Comment by leastprivilege** [comment]
Reworked client validation - split into

* secret parsers (parse the environment and turn something into an authenticable secret)
* secret validators (validate the secret to confirm the associated id is correct)

**Comment by leastprivilege** [comment]
Reworked custom grant validators

* one custom grant validator per type
* can register multiple

**Comment by leastprivilege** [comment]
Logging:

* added support for capturing Katana logs
* removed "IncludeSensitiveData" feature

**Comment by brockallen** [comment]
Breaking changes:
* Parameters to user service interface changed to context objects
* All return values on the user service APIs moved to the context parameters 
* Script tag in the default view service layout template changed to "script.2.0.0.js"
* OWIN extensions:
 * GetIdentityServerFullLogin renamed w/ Async
 * GetIdentityServerPartialLogin renamed w/ Async
* Removed trace log and trace source provider
* New PostAuthenticateAsync added to user service. This is called prior to issuing a full login cookie for IdentityServer and allows a consolidated location to check if a partial login is needed for users logging in.

Changes
* When the Welcome page is disabled, the route will not be registered
* Added several new OWIN environment extension methods related to partial logins
* Added new URL in partial logins to restart the login process
* When IdP passed to login page then we immediately redirect to IdP, rather than redirecting to our own external login page (which then redirects to the IdP)
* Password field gets focus if username provided
* Partial logins no longer remove the primary login cookie.

Bug fixes:
* Default view service's layout html has changed slightly
 * https://github.com/IdentityServer/IdentityServer3/commit/7356981016bd86f68ef8e58658a98f042bdfe5e1
  * https://github.com/IdentityServer/IdentityServer3/commit/3db723e23bfd5b155fd937abcf991554557109d5

**Comment by snothub** [comment]
Is there a v2.0 branch for EntityFramework persistance layer I'm not seeing?

Any thoughts on upgrade procedure in a multi-server environment using EF persistance layer? We would require an in-flight upgrade procedure with no downtime, but I think this requirement should not be unusual for an operation-critical service as this is.

**Comment by brockallen** [comment]
The dev branch for EF has been update to the latest 2.0.0 (from myget). 

As for an upgrade -- that's up to your EF migrations.

**Comment by snothub** [comment]
Thanks for the reply, but that's exactly it: how can I upgrade to EF 2.0.0 and generate sensible migrations for the production env? Is the order of upgrades important (EF then IdSrv)?

**Comment by brockallen** [comment]
Our DB library use EF, but the migrations are the responsibility of the hosting app. The EF sample will show a sample DB migration, but our sample can't know what version you started with (and thus what version of the schema), so the details of that migration will be up to you to sort out.

So the EF sample is the main place to look for ideas on how to approach that: https://github.com/IdentityServer/IdentityServer3.Samples/tree/dev/source/EntityFramework. I'm working today on getting this sample (and others) up to the latest of IdSvr3 2.0.0.

**Comment by snothub** [comment]
I see. Still, after attempting a test upgrade, I get EF errors saying I should enable automatic migration and after doing so, new error saying I should enable AutomaticMigrationDataLossAllowed because the upgrade will cause data loss. Production servers and data loss sounds like an issue, is there a way around that?

**Comment by brockallen** [comment]
Sorry to keep punting on this, but you're relying upon EF for this. If it doesn't handle what you need, then don't use it. Our docs do warn that you need to think about migrations: https://identityserver.github.io/Documentation/docs/ef/migrations.html

**Comment by snothub** [comment]
Sure thing, but I've followed that very article to the letter and don't really get why EF now tells me this will cause data loss. The whole idea was to get a smooth upgrade path and not mess with the database manually.

**Comment by brockallen** [comment]
There are schema changes in 2.0.0 (as there were in various 1.x updates). I'll be getting to the EF sample soon so you can see what that migration might look like.

**Comment by snothub** [comment]
Fantastic, looking forward to it. I'm on v.1.5.0 btw.

**Comment by brockallen** [comment]
As a FYI, the EF sample (with the migrations) has been updated on dev branch.
