### ISSUE TITLE
Usage with Classic ASP?

### ISSUE THREAD

**Issue by bblunden** [IdentityServer/IdentityServer3#1427]
Hi,

We are evaluating IS3 and its ability to act as Identity Server for an existing legacy Classic ASP application.  I'm thinking this needs to be done via extensibility mode.  Does anyone have any thoughts, links, examples to share that might aid in this assessment?

Thanks, Brent

**Comment by brockallen** [comment]
I'd check here to find out what libraries are supported (classic ASP is not there):

https://openid.net/developers/libraries/

You can use IdSvr's validation endpoint as a workaround to the absence of a library for your target environments.
