### ISSUE TITLE
User Claims  on Client 

### ISSUE THREAD

**Issue by moiseyo** [IdentityServer/IdentityServer3#1428]
I have  created  my One Uses Service using   samples from Github  and Allen,  The application runs as expected Only one isue  bothering me  

I'm using  await  AuthenticateExternalAsync(ExternalIdentity externalUser, SignInMessage message)
and  it does not look like  climes  in put  in externalUser  go  to the   Client and   user  property after 
tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);
equal null , and in clemt site  I cold not  find any  clames  I assigned to  externalUser  object.

Do I need  to use different method or  another  approach..

Tthank  you

**Comment by brockallen** [comment]
AuthenticateExternal provides your user service with the claims from the external provider. You must store those. In the GetProfileData is where you retrieve those claims to include in the token.

**Comment by moiseyo** [comment]
Thank you Allen
Allen , Implemented class  derived  from   IUserService  and   situation
 got even worth
1)   GetProfileDataAsync never  was called
2)  All navigation got broken

No Javascript error  and  no  error in trace


May you can see  the problem


I'm running  Windows 7 Enterprise
Vs 2014 SP 4 , and .NET 4.51

Thank you for help



Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

On Thu, Jun 4, 2015 at 11:49 PM, Brock Allen <notifications@github.com>
wrote:

> AuthenticateExternal provides your user service with the claims from the
> external provider. You must store those. In the GetProfileData is where you
> retrieve those claims to include in the token.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3/issues/1428#issuecomment-109154904>
> .
>

﻿using Microsoft.Owin.Security.Facebook;
using Microsoft.Owin.Security.Google;
using Microsoft.Owin.Security.OpenIdConnect;
using Microsoft.Owin.Security.Twitter;
using Owin;
using SampleApp.Config;
using Thinktecture.IdentityServer.Core.Configuration;
using Thinktecture.IdentityServer.Core.Logging;
using Thinktecture.IdentityServer.Core.Services;

namespace SampleApp
{
    internal class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());

            
                app.Map("/core", coreApp =>
            {
                var factory = InMemoryFactory.Create(
                    users : Users.Get(),
                    clients: Clients.Get(),
                    scopes: Scopes.Get());

                factory.ViewService = new Registration<IViewService>(typeof(CustomViewService));
                //factory.UserService = new Registration<IUserService, UserService>();
                factory.UserService = new Registration<IUserService, ExternalUserService>();
                
                var options = new IdentityServerOptions
                {
                    //IssuerUri = "https://idsrv3.com",
                    CspOptions = new CspOptions { Enabled =false},
                    IssuerUri = "https://localhost:44333/core",
                    SiteName = "TaxWize Online",
                   
                    Endpoints=new EndpointOptions{ EnableCspReportEndpoint=false},
                    SigningCertificate = Certificate.Get(),
                    Factory = factory,
                    CorsPolicy = CorsPolicy.AllowAll,
                    AuthenticationOptions = new AuthenticationOptions {
                        IdentityProviders = ConfigureAdditionalIdentityProviders,
                      
                    },
                    EventsOptions = new EventsOptions
                    {
                        RaiseSuccessEvents = true,
                        RaiseErrorEvents = true,
                        RaiseFailureEvents = true,
                        RaiseInformationEvents = true
                    }
                };

                coreApp.UseIdentityServer(options);
            });
        }

        public static void ConfigureAdditionalIdentityProviders(IAppBuilder app, string signInAsType)
        {
            
            var google = new GoogleOAuth2AuthenticationOptions
            {
                AuthenticationType = "Google",
                SignInAsAuthenticationType = signInAsType,
                ClientId = "767400843187-8boio83mb57ruogr9af9ut09fkg56b27.apps.googleusercontent.com",
                ClientSecret = "5fWcBT0udKY7_b6E3gEiJlze"
            };
            app.UseGoogleAuthentication(google);

            var fb = new FacebookAuthenticationOptions
            {
                AuthenticationType = "Facebook",
                SignInAsAuthenticationType = signInAsType,
                AppId = "676607329068058",
                AppSecret = "9d6ab75f921942e61fb43a9b1fc25c63"
            };
            app.UseFacebookAuthentication(fb);

            var twitter = new TwitterAuthenticationOptions
            {
                AuthenticationType = "Twitter",
                SignInAsAuthenticationType = signInAsType,
                ConsumerKey = "N8r8w7PIepwtZZwtH066kMlmq",
                ConsumerSecret = "df15L2x6kNI50E4PYcHS0ImBQlcGIt6huET8gQN41VFpUCwNjM"
            };
            app.UseTwitterAuthentication(twitter);
            var aad = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "aad",
                Caption = "Azure AD",
                SignInAsAuthenticationType = signInAsType,

                Authority = "https://login.windows.net/4ca9cb4c-5e5f-4be9-b700-c532992a3705",
                ClientId = "65bbbda8-8b85-4c9d-81e9-1502330aacba",
                RedirectUri = "https://localhost:44333/core/aadcb"
            };

            app.UseOpenIdConnectAuthentication(aad);
        }
    }
}
﻿using Microsoft.Owin;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Thinktecture.IdentityServer.Core;
using Thinktecture.IdentityServer.Core.Extensions;
using Thinktecture.IdentityServer.Core.Models;
using Thinktecture.IdentityServer.Core.Services;
using Thinktecture.IdentityServer.Core.Services.InMemory;


namespace SampleApp
{
    public class ExternalUserService : IUserService
    {
        private IOwinContext ctx;
        public class CustomUser
        {
            public string Subject { get; set; }
            public string Provider { get; set; }
            public string ProviderID { get; set; }
            public List<Claim> Claims { get; set; }
        }
        
        public static List<CustomUser> Users = new List<CustomUser>();

       public  ExternalUserService ( OwinEnvironmentService env)
            
        {
            ctx = new OwinContext(env.Environment);
        }
        public Task<AuthenticateResult> AuthenticateExternalAsync(ExternalIdentity externalUser, SignInMessage message)
        {
            // look for the user in our local identity system from the external identifiers
            var user = Users.SingleOrDefault(x => x.Provider == externalUser.Provider && x.ProviderID == externalUser.ProviderId);

            if (user == null)
            {
                // user is not registered so redirect
                user = new CustomUser();
                user.Provider = externalUser.Provider;
                user.ProviderID = externalUser.ProviderId;
                user.Subject = "CCHSFS";
                user.Claims = externalUser.Claims.ToList();

               
            }

            string name = "Not Found";
            // user is registered so continue
            var xname = externalUser.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);

            
            if (xname!= null)
                name = xname.Value;
            else
            {
                xname = externalUser.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
                if (xname != null)
                {
                    name = xname.Value;
                }
            }
            //return Task.FromResult<AuthenticateResult>(new AuthenticateResult(user.Subject, name, externalUser.Claims, identityProvider: user.Provider));
            return Task.FromResult<AuthenticateResult>(new AuthenticateResult(user.Subject, name, identityProvider: user.Provider));
        }

        public async  System.Threading.Tasks.Task<AuthenticateResult>
          AuthenticateLocalAsync(string username, string password, Thinktecture.IdentityServer.Core.Models.SignInMessage message)
        {
            //string file_name = @"c:\temp\short\1.ser";
            //FileStream fs = new FileStream(file_name, FileAccess.Write);

            Task<IFormCollection> form = ctx.Request.ReadFormAsync();
            var clientid = form.Result["clientid"];
           //AuthenticateResult result;


            try
            {
                //ClaimsIdentity claimsIdentity = new ClaimsIdentity(claimCollection, "CustomApiKeyAuth");

                UniversalTaxSystems.Security.User CurrentUser = UniversalTaxSystems.Security.User.GetUser(Guid.Empty);
                Int32 ClientID = Int32.Parse(clientid);
                String UserName = username;
                String Password = password;
                UniversalTaxSystems.Security.UserValidateFailureReason Reason = new UniversalTaxSystems.Security.UserValidateFailureReason();
                var login = UniversalTaxSystems.Security.User.Validate(ClientID, UserName,
                    Password, ref CurrentUser, ref Reason, "xxxxx");

                if (login)
                {
                    IList<Claim> claimCollection = claimCollection = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, username)
                        , new Claim(ClaimTypes.Country, "USA")
                        , new Claim(ClaimTypes.Gender, "M")
                        , new Claim(ClaimTypes.Surname, CurrentUser.LastName)
                        , new Claim(ClaimTypes.Email,CurrentUser.EmailAddress )
                        , new Claim(ClaimTypes.Role, CurrentUser.AssignedRoles.First().ToString())
                    };

                    ExternalIdentity externalidentity = new ExternalIdentity();

                    externalidentity.Claims = claimCollection;
                    externalidentity.Provider = "CCHSFS";
                    externalidentity.ProviderId = username;
                    Uri redirect = new Uri(message.ReturnUrl);

                    //result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult(redirect.PathAndQuery, username, username, claimCollection);
                    //result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult( username, username, claimCollection);
                    //  result = new Thinktecture.IdentityServer.Core.Models.AuthenticateResult( redirect.PathAndQuery,externalidentity);
                    return  await AuthenticateExternalAsync(externalidentity, message);
                }
                else
                {
                    return await Task.FromResult<AuthenticateResult>(null);
                }



                
            }
            catch (Exception ext)
            {
                var mess = ext.Message;
            }
            return   await  Task.FromResult<AuthenticateResult>(null);
        }
        //public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
        //{
        //    return Task.FromResult<AuthenticateResult>(null);
        //}

        public Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
        {
            // issue the claims for the user
            var user = Users.SingleOrDefault(x => x.Subject == subject.GetSubjectId());
            if (user == null)
            {
                return Task.FromResult<IEnumerable<Claim>>(null);
            }

            return Task.FromResult(user.Claims.Where(x => requestedClaimTypes.Contains(x.Type)));
        }

        public Task<bool> IsActiveAsync(ClaimsPrincipal subject)
        {
            var user = Users.SingleOrDefault(x => x.Subject == subject.GetSubjectId());
            return Task.FromResult(user != null);
        }

        public Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message)
        {
            return Task.FromResult<AuthenticateResult>(null);
        }

        public Task SignOutAsync(ClaimsPrincipal subject)
        {
            return Task.FromResult(0);
        }
    }
}

**Comment by brockallen** [comment]
Sorry -- not sure. Follow the samples since they all work.

**Comment by moiseyo** [comment]
I ran two  clients     and found difference

The change  only in user  services  client , the same client , the same
server settings

I delighted difference,  Do you have any idea why navigation  is  diffrent


By the way  I changed in memory sample  to  own  AuthenticateExternalAsync
and  navigation got broken too.

Thank you


Working with InMemory -  correct  navigation - no User  claims

   "MachineName": "MOYSGELT"
  }
}
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Endpoints.DiscoveryEndpointController]:
6/8/2015 2:59:36 PM +00:00 -- Start discovery request*
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Endpoints.DiscoveryEndpointController]:
6/8/2015 2:59:36 PM +00:00 -- Start key discovery request*
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]:
6/8/2015 2:59:37 PM +00:00 -- Start authorize request*
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]:
6/8/2015 2:59:37 PM +00:00 -- Start authorize request protocol validation*
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]:
6/8/2015 2:59:37 PM +00:00 -- Authorize request validation success*
 {
  "RedirectUri": "http://localhost:2672/",
  "ResponseType": "code id_token token",
  "ResponseMode": "form_post",
  "Flow": "Hybrid",
  "RequestedScopes": "openid email profile read write offline
-------------------------------------------------------------------------------------------------------------------------------------
Customer user nothing  works correctly

"Context": {
    "ActivityId": "00000000-0000-0000-0500-0080020000ee",
    "TimeStamp": "2015-06-08T13:52:41.7460725+00:00",
    "ProcessId": 6816,
    "MachineName": "MOYSGELT",
 *   "RemoteIpAddress": "::1"*
  }
}
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]:
6/8/2015 1:52:41 PM +00:00 -- issuing cookie*
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]:
6/8/2015 1:52:41 PM +00:00 -- redirecting to:
https://localhost:44333/core/connect/authorize?client_id=katanaclient&redirect_uri=http:%2F%2Flocalhost:2672%2F&response_mode=form_post&response_type=code
<https://localhost:44333/core/connect/authorize?client_id=katanaclient&redirect_uri=http:%2F%2Flocalhost:2672%2F&response_mode=form_post&response_type=code>
id_token token&scope=openid email profile read write *
offline_access&state=OpenIdConnect.AuthenticationProperties%3DLnMN6FjSMu9UvMXuZing4VD1fxRVCBXI65hURVohXqPJfNe7PEiBVirtrAW5Rt0pL1BNJC33okr7WH7Zy8TB-IJlr4Ev9SrTkEFMiIvCanKg7bLTA-LxSBRC1pkySkWqqsrxDBZdXaMDUpqfHyo9TGUwK1OcKddOQ8WVtpXwXAtW-gPDiaK2Ofq8nCrqLcR2hatTU3Hoc32qcnR3EspCpA&nonce=635693683076366621.ZDRhYjcwYzYtNzFhYi00MmI3LWE1OTctYWFmN2VlOGIxMDRkM2M5YjhiODUtYzhhNC00OTMyLTg0YTMtMTY0YmNiYWIxMjEx
ii*sexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]:
6/8/2015 1:52:41 PM +00:00 -- Start authorize request*
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]:
6/8/2015 1:52:41 PM +00:00 -- Start authorize request protocol validation*
*iisexpress.exe Information: 0 :
[Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]:
6/8/2015 1:52:41 PM +00:00 -- Authorize request validation succes*s
 {


Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by moiseyo** [comment]
Hello Alan
Allan , fallow samples I found way  hoe to pass  user  claims  using
external account access .

My problem was That I tried to  implement  the same  via call local access .


Is  that possible to  make a  call  without external provider ( I have
local database )  and keep  O pent ID  authentication process after I
 validated user?

Thank you



Moisey O
Senior Application Developer
moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.
