### ISSUE TITLE
Chapet 16.  Security Considerations

### ISSUE THREAD

**Issue by rdzidziguri** [IdentityServer/IdentityServer3#1429]
If one reads specs of OpenID Connect there is a section related to security considerations which every open or Identity System should understand so my general question is about encryption of requests and other security considerations which might apply to IdSer providers. 

**16.5.  Server Response Disclosure**
> The server response might contain authentication data and Claims that include sensitive Client information. Disclosure of the response contents can make the Client vulnerable to other types of attacks. 

as a solution for this risk specs suggests to either use code response type or.

> For other Response Types, the signed response can be encrypted with the Client's public key or a shared secret as an encrypted JWT with an appropriate key and cipher. 

**QUESTION 1:**
how this second functionality is handled by IdentityServer3?

 **16.21.  Need for Encrypted Requests**
I had an question about this few days ago and we had a very interesting discussion about this with one of the community members here so here it is just another risk OpenID Connect identifies.

> In some situations, knowing the contents of an OpenID Connect request can, in and of itself, reveal sensitive information about the End-User. For instance, knowing that the Client is requesting a particular Claim or that it is requesting that a particular authentication method be used can reveal sensitive information about the End-User. OpenID Connect enables requests to be encrypted to the OpenID Provider to prevent such potentially sensitive information from being revealed. 

**QUESTION 2:**
how this is achieved within Identity Server 3 are there any examples of handling encrypted requests or does with apply to implicit flow (passing request parameters to query string as an encrypted value)?

 I think this is all very important to understand those bits of specs and the way they are implemented in different Identity Providers. as IdentityServer3 is officially certified by OpenID Connect I do not say there is something wrong with it I love this project and hope to find time to even contribute but for now those are questions which I hope to get answers from @brockallen  and @leastprivilege

**Comment by brockallen** [comment]
For Q1: Microsoft's JWT security token handler doesn't currently support encryption, so we're limited by that. I recently saw an issue on their issue tracker where they said they would like to add the support, but no timeline for it.

For Q2: Use SSL.

**Comment by rdzidziguri** [comment]
@brockallen 
For A1: What if I derive from their base class and support this functionality? in this case all I need is an extra parameter inside Clients object to indicate if that token should be encrypted or not and on global configuration some property indicating that encryption method either using some pass code or certificate.

FOR A:2 but SSL eliminates part of the risk what if we encrypt all parts of the URL so that oncly clientID is known and other sensitive parameters are encrypted so only client and provider knows how to read it? this would make implicit flow secure because when redirecting user to the provider for authentication there would be some really unreadable data passed as an parameter. I think this is exactly what they mean right?

**Comment by brockallen** [comment]
1) Yes, you'd need some config on the client to indicate that it should be encrypted as well. For asymmeteric encryption you'd also need a client cert configured.

2) I don't follow

**Comment by rdzidziguri** [comment]
@brockallen 
1: yes I agree but even if I have that config on client side how one can configure IdentityServer 3 to support encryption process? does it mean that I have to implmement [ITokenSigningService] (https://github.com/IdentityServer/IdentityServer3/blob/master/source%2FCore%2FServices%2FITokenSigningService.cs) or derive from default implementation inside identity server and add encryption to it after base class signs token?

2: what do you mean? did not you understand the point here? what I mean is that if we have URL for authentication where each parameter is openly passed as query string parameters what if only clientID was passed as an open argument inside redirect URL and other parameters like response type scopes could be provided as an encrypted string? client could encrypt those parameters either using some secret key or public certificate provided by Identity provider and after redirecting for authentication only identityServer would be able to decrypt those parameters based on client id validate them and process for authentication

**Comment by brockallen** [comment]
1> yea, something would need to get changed in IdSvr.

**Comment by leastprivilege** [comment]
You need to switch to a JWT library that supports encryption according to the JOSE spec.

Maybe try this one: https://github.com/dvsekhvalnov/jose-jwt

Would be interested in the outcome.
