### ISSUE TITLE
Update AngularJS to latest stable version

### ISSUE THREAD

**Issue by B3nCr** [IdentityServer/IdentityServer3#1434]
This issue is to discuss updating AngularJS to the latest stable version (1.3.15) as discussed on Gitter.

The latest version of AngularJS includes security fixes:
* https://github.com/angular/angular.js/blob/master/CHANGELOG.md#132-cardiovasculatory-magnification-2014-11-07
* https://github.com/angular/angular.js/blob/master/CHANGELOG.md#130-beta14-harmonious-cacophonies-2014-06-30

There is also a fix for the angular LayoutController which wasn't written in a way which would allow for minification and cause an DI error.

I've made the changes, I'll attach the pull request to this ticket.

This will also help me and others who include the registration form on the login form as the later version of angular has a better validation API.

**Comment by brockallen** [comment]
I started looking at this. Changing the minification wasn't what I was hoping for -- I did it originally that way on purpose.

Anyway, some of the pages aren't working properly -- that needs to be looked into.

**Comment by brockallen** [comment]
Done on dev -- thanks.
