### ISSUE TITLE
Client notification - how to avoid callbacks?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1437]
we have an hybrid WebAppClient 

    
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
			{

.......
Notifications = new OpenIdConnectAuthenticationNotifications
				{
					AuthorizationCodeReceived = async n =>
					{

Now our AuthorizationCodeReceived callback has become quite large and we want to transfer the callback logic into some dedicated class, where we can properly use DI and so on.

What would it be? What would be the default scenario? the identityserver samples afaik always use the callback. Something like a UserSErvice but now for the Client?

Thank you

**Comment by brockallen** [comment]
You'd have to ask Microsoft for DI for that -- it doesn't exist today. If not Microsoft, you'd have to build something yourself.
