### ISSUE TITLE
Creating a Custom set of Claims for each different Client

### ISSUE THREAD

**Issue by aronblum** [IdentityServer/IdentityServer3#1438]
Hi,

I have multiple clients, which request an assortment of differing custom Scopes/Claims and I am trying to figure out how I can somehow find the requesting Client within GetProfileDataAsync (UserService.cs). I have implemented my own ClaimsProvider and thought of maybe trying to make an overload for GetProfileDataAsync, adding in Client as a parameter, but this is proving a bit messy.

My end goal is to return differing sets of claims depending on which Client is hitting IdSrv. Currently I am just returning a single set of Claims which covers all Clients.

Does anyone have any ideas as to the best, or tidiest method of doing this? Perhaps someone knows of a method where I don't even need to implement my own ClaimsProvider.

Thanks a lot,

Aron

**Comment by brockallen** [comment]
We will be adding the `Client` as a param to the `GetProfileData` in 2.0.0.

**Comment by aronblum** [comment]
Hi Brock,

When do you expect 2.0.0 will be released? If it won't be anytime soon, do you have any suggestions for implementing this with the existing IdSrv version?

Thanks,

Aron

**Comment by brockallen** [comment]
2.0.0 -- in 1-2 months. beta4 is out: https://www.nuget.org/packages/IdentityServer3
