### ISSUE TITLE
Combining multiple user stores

### ISSUE THREAD

**Issue by errno3** [IdentityServer/IdentityServer3#1440]
Hi guys,

first of all, many thanks to the IdSrv team for the great implementation. I am currently working on our SSO solution based on the IdentityServer v3 and fighting with the following issues. We have multiple products (multi-tentant) sharing the same user store (accounts for our customers etc). On the other side we have also AD users (our employees) that should automatically login without retyping username and password. Well, I need to pass the tenant id (via client_id?). If the user is local one (AD) then he doesn't see the login screen at all; he's forwarded to the product (redirect_uri) automatically. If the user is normal one (meaning a customer user stored in the product user store) then he must login first).

I customized the ViewService (I've extended LoginViewModel: client_id is now passed to the login page) and need to pass this data to the UserService some how. Now, the first question: how would you implement the login for AD users? The second one: how to pass additional data to the UserService component?

I've found this discussion here:

http://forums.asp.net/t/2032044.aspx?Custom+User+Service+for+Thinktecture+Identity+Server+V3

However, may be there is support for this scenario now.

Thanks for any help.

Regards,
Erno

**Comment by brockallen** [comment]
So I just spent some time at a client and we were able to get their IdSvr working as a multi-tenant server. It's possible, yes. We were working with the 2.0.0 dev/branch.

**Comment by errno3** [comment]
Hi Allen,

thanks for the quick fix and response.

I saw you've changed some of the code in order to get a tenant via SignMessageIn into the IUserService. 

Is there any solution from you point of view for the scenario with the active directory users? I am not sure that custom extension of the IdSev is the best one solution.

Thanks,
Erno

**Comment by brockallen** [comment]
You can enable AD users as well -- that's just done with an external provider (same as you'd do google).

**Comment by errno3** [comment]
sorry - not sure I get the idea... Do you mean additional identity providers? Implementing custom AuthenticationOptions (like GoogleOAuth2AuthenticationOptions)? We need actually one login screen for both user stores...

**Comment by brockallen** [comment]
What I meant was if you want a local DB of user and AS users, then you use the user service's AuthenticateLocal for DB users, and for AD you'd configure something like ADFS in the external providers (and then you'd handle them in the authenticate external in the user service). 

If what you want is the username/password to work with multiple stores, you'd have to code that yourself in the AuthenticateLocal.
