### ISSUE TITLE
[QUESTION] What do external authentication providers need to callback?

### ISSUE THREAD

**Issue by vvolkgang** [IdentityServer/IdentityServer3#1441]
Hi,

I've implemented a owin authentication middleware following [Anders Abel tutorial](http://coding.abel.nu/2014/06/writing-an-owin-authentication-middleware/). What (and how) my external authentication service needs to callback on success and on error, to complete the authentication process?

I'm using `InMemoryUserService` btw.

**Comment by depl0y** [comment]
Well I configured Google to redirect to `identity/signin-google` and Microsoft to `identity/signin-microsoft` and that seems to work.

**Comment by vvolkgang** [comment]
@depl0y Thanks! It does due to the middlware implementing that functionality, how it's doing was what intrigued me

Found out that this should be dealt by the middleware in the `AuthenticationHandler.InvokeAsync()` override. This is already implemented by the 
`[DummyAuthenticationHandler.cs](https://github.com/AndersAbel/DummyOwinAuth/blob/master/DummyOwinAuth/DummyAuthenticationHandler.cs)`, the external authentication system just needs to ensure that the `state` query parameter sent [here](https://github.com/AndersAbel/DummyOwinAuth/blob/master/DummyOwinAuth/DummyAuthenticationHandler.cs#L48) is redirected back after a successful authentication, by calling `Constants.BaseAddress + Options.CallbackPath.Value` (eg: `https://mysite.com/idsrv3/core/signing-dummy?state=LongAssProtectedStringWithAllTheLoginRelatedAndNecessaryInfo`), providing all the required claims somehow. This is partly done [here](https://github.com/AndersAbel/DummyOwinAuth/blob/master/DummyOwinAuth/DummyAuthenticationHandler.cs#L24).
