### ISSUE TITLE
Issue with identifying the Client Id passed from Ajax call

### ISSUE THREAD

**Issue by vedaantees** [IdentityServer/IdentityServer3#1442]
I tried executing following ajax call to get the token
```javascript
            $.ajax(
            {
                url: "https://localhost:44300/identity/connect/token",
                data: object,
                headers: { 'Access-Control-Allow-Origin': '*' },
                crossDomain: true,
                datatype: 'json',
                type: "POST",
                beforeSend: function (xhr)
                {
                    xhr.setRequestHeader("Authorization", make_base_auth("abcdweb", "secret"));
                }
            });
```
make_base_auth encodes the string in expected format 
```javascript
'{' + clientid + '}:{' + secret + '}';
```
The client id for abcdweb is setup correctly. But I still kept getting issue as invalid_client.
I saw in output window that the ClientId is being set to 

```javascript
  "ClientId": "{abcdweb}",
  "ClientCredentialType": "Basic"
```

which should be set to abcdweb, isn't it?

Pardon my lack of knowledge as I just started working with IdentityServer3. But if this is a bug we just need to add these lines 
```javascript
            ClientId = clientId.Replace("{",string.Empty).Replace("}", string.Empty),
```
on line 172 in ClientValidator class. 

I am not sure of this is correct change and pardon me again if I am doing this incorrectly.

Can you please suggest a solution

**Comment by brockallen** [comment]
This makes no sense in your client:
`headers: { 'Access-Control-Allow-Origin': '*' },`

As for the client authentication, I'd suggest sending them as POST params (not basic auth headers since you don't seem to be doing it right).
