### ISSUE TITLE
Fix for mono.. Use Assembly.GetLoadableTypes() instead of .GetTypes()

### ISSUE THREAD

**Issue by jonathankarsh** [IdentityServer/IdentityServer3#1443]
With the change introduced in https://github.com/IdentityServer/IdentityServer3/commit/da685dfd3fd4937396c1191830cfc50a4ef634a6#diff-eabf679724b1db39740d70ebbc8145d9R71, IdentityServer started failing running on mono. Compilation works (as before, with a single warning: 'System.identitymodel.services' not resolved). The runtime exception itself however isn't seen because it occurs inside the overridden `HttpControllerTypeResolver`.

Scenario:
- Reference any IdentityServer nuget package >= 1.2 and <= 1.6.1.
- I've used an updated version of https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/SelfHost%20(Minimal)
- Tried on mono versions 3.12.1, 4.0.0 and 4.0.1
- As a shortcut used HTTP instead of HTTPS, with `RequiresSsl = false`

Symptom:
- First request to the service on `http://localhost:44333/core` gets an empty 500. No logs appears.
- Second and subsequent requests fail with unrelated exceptions:
```
/usr/src/app/source/SelfHost/bin/Release/Thinktecture.IdentityServer3.dll Error : 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 06/04/2015 07:06:54 +00:00 -- Unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Net.Http.DelegatingHandler.SendAsync (System.Net.Http.HttpRequestMessage request, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
  at System.Web.Http.HttpServer.<>n__FabricatedMethod9 (System.Net.Http.HttpRequestMessage , CancellationToken ) [0x00000] in <filename unknown>:0
  at System.Web.Http.HttpServer+<SendAsync>d__0.MoveNext () [0x00000] in <filename unknown>:0
```

Captured exceptions:
- Using [this branch] (https://github.com/jonathankarsh/IdentityServer3/tree/assembly-gettypes-show-exception), the actual exceptions from the server are:
```
Assembly.GetTypes() exception details: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0
  at Thinktecture.IdentityServer.Core.Configuration.Hosting.WebApiConfig+HttpControllerTypeResolver.GetControllerTypes (IAssembliesResolver _) [0x00000] in <filename unknown>:0
Loader exception details: System.TypeLoadException: Could not load type 'Microsoft.Owin.Security.DataProtection.DpapiDataProtector' from assembly 'Thinktecture.IdentityServer3, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'.
Loader exception details: System.TypeLoadException: Could not load type 'System.IdentityModel.Tokens.NamedKeyIssuerTokenResolver' from assembly 'Thinktecture.IdentityServer3, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'.
Loader exception details: System.TypeLoadException: Could not load type 'Thinktecture.IdentityModel.Metadata.FederationMetadata' from assembly 'Thinktecture.IdentityServer3, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'.
Loader exception details: System.TypeLoadException: Could not load type 'Thinktecture.IdentityModel.Tokens.GenericUserNameSecurityTokenHandler' from assembly 'Thinktecture.IdentityServer3, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'.
Loader exception details: System.TypeLoadException: Could not load type 'Thinktecture.IdentityModel.Tokens.HttpSaml2SecurityTokenHandler' from assembly 'Thinktecture.IdentityServer3, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'.
Loader exception details: System.TypeLoadException: Could not load type 'Thinktecture.IdentityModel.Tokens.HttpSamlSecurityTokenHandler' from assembly 'Thinktecture.IdentityServer3, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'.
Loader exception details: System.TypeLoadException: Could not load type 'Thinktecture.IdentityModel.Metadata.MetadataBasedIssuerNameRegistry' from assembly 'Thinktecture.IdentityServer3, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'.
```

Suggested fix:
- In [this branch] (https://github.com/jonathankarsh/IdentityServer3/tree/assembly-getloadabletypes), use `Assembly.GetLoadableTypes()` from Autofac's extensions, which follows guidelines set out [here] (http://haacked.com/archive/2012/07/23/get-all-types-in-an-assembly.aspx/)

**Comment by jonathankarsh** [comment]
Note "Compilation work" - I'm referring to compilation of the sample not of IdentityServer itself

**Comment by leastprivilege** [comment]
@damianh

**Comment by damianh** [comment]
Mono heh.

See if this works http://stackoverflow.com/a/7889272

**Comment by jonathankarsh** [comment]
Yes it works, that's exactly it. Phil Haack's [blog post](http://haacked.com/archive/2012/07/23/get-all-types-in-an-assembly.aspx/) references this SO answer and adds argument validation.

Autofac project adds exactly this implementation as an extension method under its `Autofac.Util` namespace, hence it's available to be used and only requires a one line change (+ using statement) in `Thinktecture.IdentityServer.Core.Configuration.Hosting.HttpControllerTypeResolver` - this is my suggested fix.

**Comment by leastprivilege** [comment]
Will look into it.

**Comment by jonathankarsh** [comment]
Thanks
Happy to raise a PR for this of course

**Comment by leastprivilege** [comment]
We postponed all mono fixes to 2.1 - once 2.0 is released I would be happy if you would send a PR.

**Comment by jonathankarsh** [comment]
Awesome, sounds good

**Comment by ryan1234** [comment]
@jonathankarsh Yeah this was the issue I was experiencing as well. I'll make sure to use 2.0.1 and not 2.0.

**Comment by jonathankarsh** [comment]
Good stuff, cheers
