### ISSUE TITLE
[Question] Is default implementation of IViewService good for Production use?

### ISSUE THREAD

**Issue by senseicz** [IdentityServer/IdentityServer3#1444]
Can anyone share experience of using default implementation of IViewService in Production environment? Given I'm planning to host IdentityServer3 core as part of MVC5 application, are there any good (and open source) implementations of IViewService?

Thank you, Antonin

**Comment by rdzidziguri** [comment]
@senseicz What do you mean under open source implementations? Custom View Service is all about your own requirements so why would someone create generic one as an open source project?  We have all our views implemented using IViewService and there are a lots of extensibility points there, for example based on client you could actually change icon u display on login screen, manipulate links which are displayed on log-in page etc. what are u particularity looking for and what is your expectations using IViewService?

**Comment by senseicz** [comment]
@rdzidziguri - primary point of my question is to get an idea if there are people running in production with default IViewService implementation. As the default ViewService is pretty much about this line: `value = value.Replace("{" + key + "}", val.ToString());` , I'd like to hear if this is causing any performance issues. 

The other part of my question is simply asking if someone with custom implementation would be willing to share their code.

**Comment by brockallen** [comment]
Well, profile it and compare it to something else. If there's a major difference, feel free to solve it and submit a PR.

**Comment by rdzidziguri** [comment]
@senseicz We did not see any issues using default implementation. not performance problems so I do not see any reasons why we should change it with something else.

**Comment by senseicz** [comment]
Thank you very much for you input. Will close this question now.
