### ISSUE TITLE
Big shoutout!

### ISSUE THREAD

**Issue by mderriey** [IdentityServer/IdentityServer3#1445]
Hey,

I am building a single web application which uses IdentityServer as well as MVC to have custom registration pages.
I was worried that using another Autofac container in the OWIN pipeline for MVC would overwrite yours and cause problems.

I tried before filing an issue, and it worked! How is that possible?
Of course you guys thought this ahead, storing _your_ container in the `idsrv:AutofacScope` property of the OWIN context, allowing us to use Autofac for other purposes, since it internally stores _its_ container in the `autofac:OwinLifetimeScope` property.

Once again, thank you, keep up the **great** work.

**Comment by huysentruitw** [comment]
That's already went a long story:
https://github.com/autofac/Autofac.Owin/issues/1

**Comment by mderriey** [comment]
Hey,

There's two things here.

First, they patched it because they have fixed property names in which they store:
 - Whether an Autofac middleware has already been registered: `AutofacMiddelwareRegistered`(as of v3.1)
 - The instance of the request-scoped container in the OWIN context: `autofac:OwinLifetimeScope`

The first ensures that only the first call to `UseAutofacMvc` is taken into account so the initial container doesn't get overwritten.

Second, what Brock and Dominick asked for was that these 2 property names were configurable so that the Autofac container they use in IdentityServer is isolated from another one (say if you use MVC in the same application hosting IdentityServer).
Some progress was made since, but the option they went with was just to embed Autofac code within the IdentityServer assembly and edit these 2 property names so you can have 2 Autofac containers in the same OWIN pipeline.

Hope I'm clear :wink:

**Comment by huysentruitw** [comment]
Well, my tests shows that you can hook up as many Autofac middlewares as you want (talking about WebAPI only here), as long as everything is added in sequence to the OWIN pipeline, the `autofac:OwinLifetimeScope` gets overridden at the correct time and it just works.

**Comment by mderriey** [comment]
OK, but still apart from the rather special case of IdentityServer, I don't see why you would want to have multiple containers in your applications.
PLus, I think it gets overwritten when going **down** the pipeline, e.g. when calling `next()`. If your outermost middleware tries to access its container after executing the request, it'll get the innermost one if I'm not mistaken. What I mean they get pushed on time but not popped.

**Comment by huysentruitw** [comment]
We have a project with multiple C# libraries that have Web API and there own `UseMyApiBlaBla()` method. Both libraries use Autofac with their own container. Then one main app maps them both:

```C#
app.Map("/a", appA => appA.UseWebApi1());
app.Map("/b", appB => appA.UseWebApi2());
```

And bam, the second library can't register Autofac anymore. I don't think this is a strange usecase.

**Comment by mderriey** [comment]
Hmm, I didn't think of that.
I think you're out of luck, unless you ILmerge Autofac in all your libraries, this [PR](https://github.com/autofac/Autofac.Owin/pull/2) would make it work since each of your libraries would reference its own version of an Autofac assembly.

**Comment by huysentruitw** [comment]
I even think that, in my example, both Web API will have a different pipeline and thus the `autofac:OwinLifetimeScope` will not be overridden. It's just that one `AutofacMiddelwareRegistered` key added to the `Properties` that breaks it.

**Comment by mderriey** [comment]
Well TBH I don't know OWIN well enough to tell you what `Map` does internally.
This would be a good use case to show Travis from the Autofac team.

**Comment by brockallen** [comment]
There are several issues in the history you should look at for this -- I don't want to rehash it here. We internalize Autofac -- it's an implementation detail and is not intended to be shared outside. This is mainly because OWIN doesn't have a standard DI system. There was a bug for a bit, yes, but is now fixed.

**Comment by mderriey** [comment]
Well at the very beginning, I opened the issue to thank you once again for the tremendous work.
It lost its initial grateful note when we discussed huysentruitw's problems, but still...
Once again, **THANK YOU**!

**Comment by huysentruitw** [comment]
Hah, didn't want to spoil this issue :v:

**Comment by mderriey** [comment]
No worries, your issue deserves attention, that's for sure, but I just wanted to highlight **this** issue was in fact a thank you note :wink:

**Comment by brockallen** [comment]
No worries to all -- thanks.
