### ISSUE TITLE
Userinfo endpoint requested claims

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1447]
I'm not getting expected behaviour on this. When I issue a request to token endpoint containing a scope with a few scope claims, those will appear in the requestedClaimTypes enumerable. However, a subsequent request to userinfo endpoint with the access token will not get anything in requestedClaimTypes, as I would expect. Not even if AlwaysIncludeInIdToken set to true as wiki states. Any idea what is causing this?

**Comment by snothub** [comment]
Bump: Any ideas on this one?

**Comment by brockallen** [comment]
What do you mean by subsequent requests to the user info endpoint? Do you mean using the same access token and simply calling it a 2nd time?

**Comment by snothub** [comment]
Yes, much like in the MVC_OWIN_Client sample (I'm using that to test now actually). 

Initial authentication is done with a set of scopes (where I added a new scope for testing). When AuthorizationCodeReceived delegate is hit, a request to UserInfoEndpoint is done with the access token where my new scope is present. However, scope claims from that scope are not included in the UserInfoEndpoint response, even if AlwaysIncludeInIdToken is set to true. The only scope claims I'm able to get in there are the "profile" scope claims. Isn't that what AlwaysIncludeInIdToken would be for?

**Comment by leastprivilege** [comment]
The userinfo endpoint will read the scopes from the access token and resolve them to the configured scope claims. These claim types will be send to the user service - which may or may not return values.

This is how it works. Use logging to follow the flow.

If you are seeing that this is not consistent over multiple calls - it is a bug.

**Comment by leastprivilege** [comment]
is this resolved?

**Comment by snothub** [comment]
I'll say yes for now :)

**Comment by tbrettallen** [comment]
@snothub I am having the same issue.

How did you resolve this?
