### ISSUE TITLE
Scopes vs. API calls

### ISSUE THREAD

**Issue by scottrudy** [IdentityServer/IdentityServer3#1448]
Just curious if there is a general guideline between getting information about a user through scopes versus getting information about a user and then using an exposed service call. For example, I could create custom claims that represent a user in a CRM repository (assuming I want every application to be able to access that information), or I could just call the CRM API from each application. Is there a general principal of what should be a claim?

**Comment by brockallen** [comment]
Exposing user info via a Web API (as opposed to an OIDC approach) opens you to a subtle attack -- check about 2 years ago the attacks on facebook's OAuth2 implementation.

**Comment by scottrudy** [comment]
Thanks @brockallen. To further clarify I am really wondering if there is a guideline of where the line should be drawn between the two. So, I may want to keep simple profile data in OIDC, but then expose a service that might show additional details. Using the CRM example, suppose I have a list of contacts for a user and that information might be useful for multiple systems. I could bring them back using claims, but I could also just expose them in a service and let them be used when needed. Thoughts?

**Comment by brockallen** [comment]
Sure, the CRM data is application data and you'll need a token to secure that API. Just don't have the app blindly trust the access token and the data coming back as authentication confirmation. Use the id_token for authentication.

**Comment by scottrudy** [comment]
Agreed on the authentication. Still where I am going is should CRM data (e.g. Contacts) be sent as claims vs. a separate call to an API, even though it can be.

**Comment by brockallen** [comment]
It feels like the CRM is app data, not necessarily identity data that goes into the id_token.

**Comment by scottrudy** [comment]
Alight, so it is more of a gut feel than a guideline. That helps. Thanks.
