### ISSUE TITLE
How to enable Forgot Password and Change Password?

### ISSUE THREAD

**Issue by vinaykasireddy** [IdentityServer/IdentityServer3#1451]
Is there any way to enable ForgortPassword and Change Password in indentity Server?

**Comment by brockallen** [comment]
You have to build those features yourself. See the user service and the login page links (in the IdSvc docs) on how to extend IdSvr.

**Comment by vinaykasireddy** [comment]
Sure. Will take a look. Thanks a lot

**Comment by tsjishan** [comment]
@vinaykasireddy any luck on the implementation? Would you please share any idea how you implemented it? thanks
