### ISSUE TITLE
Identity Server and Access Control

### ISSUE THREAD

**Issue by vnexter** [IdentityServer/IdentityServer3#1452]
I have been exploring Identity server for couple of months now, I have a basic question please forgive if I look silly :)

I have invoices for different customers in resource server (Web Api). 

I want to restrict users (read write access) to a particular customers' invoices only:

Should I issue a token with customerid, read, write claims and make resource Api to authorize access ?

or should I be doing it differently?

Many thanks

Allen

**Comment by brockallen** [comment]
Depends. But as a first stab at it, I think the token should contain enough info about the user for the API to then know how to lookup their permissions to the invoice.

**Comment by vnexter** [comment]
Thank you for your response, what I was testing to add customer Id a user wants to access as an addtional query string to Authorize end point. Then access the customerId from query string in UserService (IUserService.AuthenticateLocalAsync) available in parameter SignInMessage.ReturnUrl.

Using to CustomerId to query userstore to check claims for access type to be granted.

Is it acceptable approach?

Thanks.

**Comment by brockallen** [comment]
I'd suggest not trying to change the protocol to accommodate an application specific requirement -- you might end up introducing a security vulnerability into your app.

**Comment by vnexter** [comment]
I guess acr_values will be the best solution, do you have sample that is using this?

Many thanks.

**Comment by brockallen** [comment]
Some of the samples use acr_values -- it's also described in the docs.

**Comment by vnexter** [comment]
Thank you I got it working many thanks.

**Comment by vnexter** [comment]
Sorry to bother you again, I am able to get a token for customer X and use it via javascript app.

when a user click on the customer Y to access his invoices how would I get updated access token for api consumption ? logout and login again with new acr_values? or is there any otherway

Thanks.

**Comment by vnexter** [comment]
One possibility may be using each Customer as a scope ? would it make sense?

**Comment by brockallen** [comment]
Scopes indicate which apps have access to which APIs. It's not used for authorizing which users have access to which APIs.

**Comment by vnexter** [comment]
Thanks sorry I missed that.

Above I used customer Id in acr_values when signing user in and it is included in token issued by Idsrvr.

As acr_values are used only at initial token issue (more precisely during user authentication ?) and not taken into account on any subsequent access_token request  ?

Am I able add custom information in the access_token based on token request from implicit client.

Many thanks

**Comment by vnexter** [comment]
Anyone please ?

**Comment by brockallen** [comment]
As for acr_values -- they are sent in the authorize request. They're meant to tell the OP context information from the client about authentication. You can augment what's in the access_token by requesting scopes and adding those claims in your custom user service.
