### ISSUE TITLE
Setting a custom TokenHandler for IdentityServerBearerTokenAuthenticationOptions

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1454]
I'm attempting to set TokenHandler property of IdentityServerBearerTokenAuthenticationOptions for the UseIdentityServerBearerTokenAuthentication extension method. I've created a new class inheriting from JwtSecurityTokenHandler and trying to override CreateClaimsIdentity and ValidateToken methods to return our custom IIdentity and IPrincipal classes respectively. However, I don't see this code being hit at all. Is there something I'm missing to get this custom TokenHandler property to work?

Thanks

**Comment by leastprivilege** [comment]
Well - this might be bug. In theory our options should just pass through to the inner JWT middleware.

That said - I wouldn't use that approach for creating a custom IPrincipal. Custom IPrincipals are not supported in Katana (and will not be supported in ASP.NET 5). You base class must be ClaimsPrincipal.

If you want custom functionality/syntax based on ClaimsPrincipal for convenience - I personally would use extension methods. If you absolutely want to derive from ClaimsPrincipal - use claims transformation to set the principal (as opposed to change the token handler).

**Comment by snothub** [comment]
Sorry for being unclear, our custom classes do have ClaimsPrincipal and ClaimsIdentity as base classes. I've currently only overridden the mentioned methods to create instances of our classes based on the results of the JwtSecurityTokenHandler class. Due to legacy support issues, our code expects those classes, so plain using ClaimsPrincipal wouldn't work.

Thanks

**Comment by leastprivilege** [comment]
OK - still I would use claims transformation to set the custom type.

https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/source/Owin.ClaimsTransformation

**Comment by snothub** [comment]
I'm happy to go that route, but I don't see where I should make the code
changes. Once the middleware is called the principal is set to
ClaimsPrincipal and that's what I'm looking to change.

Any samples to look at for this?

man. 8. jun. 2015, 10.07 skrev Dominick Baier <notifications@github.com>:

**Comment by leastprivilege** [comment]
Basically what the middleware does it - it passes you the current ClaimsPrincipal - and you pass a new ClaimsPrincipal (derived class) back. Run the middleware after the token validation. 

Or simply do an app.Use inline to accomplish the same.

**Comment by snothub** [comment]
That still leaves me with the problem of having to down-cast to ClaimsPrincipal that ends up on the thread. I need our custom class derived from ClaimsPrincipal to sit on the thread in order to keep legacy happy. The signature of the middleware doesn't allow for that.

**Comment by leastprivilege** [comment]
You need to downcast anyways - don't see the problem...

**Comment by snothub** [comment]
The problem is that the legacy code throws an error when !(Thread.CurrentPrincipal is OurCustomPrincipal), and middleware doesn't allow me to return anything oher than ClaimsPrincipal which makes legacy throw up. :)

**Comment by snothub** [comment]
Upcast! I mean I have to upcast. :) Damn it.
