### ISSUE TITLE
ResourceOwner flow in combination with custom grant type

### ISSUE THREAD

**Issue by frankGuadagno** [IdentityServer/IdentityServer3#1455]
Hi guys,
I'm currently implementing the resource owner flow and I would like to add an additional authentication using a custom grant type.
In this case I saw on code that there is an explicit check that is raising an exception: it checks if the flow of the client is of type "Custom" but, of course in many case is configured as "ResourceOwner" flow.
So it seems I can configure the flow either as "ResourceOwner" or as "Custom" flow.
It seems the only strategy is to convert the resource owner flow in a custom flow.
Do you have any advice?

Thanks in advance,
Francesco

**Comment by brockallen** [comment]
If you want RO + more, then yes -- use custom.
