### ISSUE TITLE
Sample for custom authentication and authorization

### ISSUE THREAD

**Issue by stevencohn** [IdentityServer/IdentityServer3#1456]
Hi, I'm new to this so forgive me if it's right in front of my nose and I'm not seeing it but I'm looking for an example of how to implement custom authentication and authorization with IS3.  Here's the scenario.  We currently have a good old fashion C# WPF/WCF client/server database app with users and permissions defined in the db.  When a user logs in, we lookup the user/pwd in the db, load available permissions, store them in a token and off we go.  Clearly, we need to catch up with the times.

I would like to introduce IS3 as a way to mature to full compliance.  But it would be nice as a first step to still use our application API as the authentication provider and authorization provider.  There are plenty of IS3 examples that use the InMemoryFactory and even Google and other providers that we don't use.  But I can't seem to find any examples of how to implement your own providers.  Can anyone please point me in the right direction?  The more documentation or info the better! :-)

Thanks!

**Comment by brockallen** [comment]
Look into the user service -- this is the area where most of the customization work is done.
