### ISSUE TITLE
Allow the Token expiration time to vary per User.

### ISSUE THREAD

**Issue by RobRolls** [IdentityServer/IdentityServer3#1457]
All,

When creating tokens I sometimes need to vary the id and access token expiration times per User rather than per Client.  

Anyone have a recommendation for the best place to insert this functionality?  I thought I've seen this question answered before but I'm not finding it anywhere.

Thanks

**Comment by huysentruitw** [comment]
#1333 perhaps?

**Comment by RobRolls** [comment]
I though that might work too but I'm not looking for the login cookie but to actually modify the expiration on the tokens.

The best thing I can see wright now is to implement my own ITokenService and re-implement most of what the DefaultTokenService does right now. Is there a better place for this?

**Comment by brockallen** [comment]
We don't have anything at the high level abstraction for this. You will have to replace something lower level (the ITokenService sounds like the right place to start looking).

**Comment by RobRolls** [comment]
Thanks, that did the trick.
