### ISSUE TITLE
Multiple Redirect URIs/Domains on the same client with OpenId Authentication

### ISSUE THREAD

**Issue by apryiomka** [IdentityServer/IdentityServer3#1458]
Hi github community, I have a question of possibility to have multiple redirect URLs for the "same" client. This is what my current configuration looks like for the client:
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "myawesomeclient",
                RedirectUri = "https://example.com",
                ResponseType = "id_token token",
                Scope = "openid profile email",
                PostLogoutRedirectUri = "https://example.com",
                SignInAsAuthenticationType = "Cookies"
});
then my controller:
[Authorize]
public ViewResult GetSomething()
{
        return View();
}

The Identity server is configured to have multiple redirect urls. The problem came about as the same app is servicing multiple domains (via SNI where multiple domains point to the same IP and port number) and sub-domains and need to authenticate using the same client. We determine the app by the client URL from the request. Now, to authenticate the client, i need to use the proper redirect url. Say, if the web service is deployed on 127.0.0.1 IP address and i have https://example.com, https://site1.example.com, https://site2.example.com, https://example2.net, etc domains all point to the 127.0.0.1. Is there a way to configure the client to use delegate or something to pull redirect URI dynamically rather than having it configured in advance. At this point the only solution is to deploy multiple apps, each separate app for each domain, where as we need one app and to be able to handle multiple domains.

Thanks you for the advice.
Alex.

**Comment by apryiomka** [comment]
Same issue is for PostLogoutRedirectUri. Is there a way to set it dynamically based on the request? Since it is assigned during a startup? How do I do it?

Thanks,
Alex.

**Comment by brockallen** [comment]
We added a way to validate those via a callback -- look into IRedirectUriValidator. I don't recall if it's used for post logout URLs.

**Comment by apryiomka** [comment]
@brockallen, I looked at the source and see that IRedirectUriValidator is a part of the identity server, not the client. Whereas I need to configure the client. The identity server Client supports multiple redirect URLs, but what i need is to be able to provide the redirect URL from the (OWIN) client side somehow dynamically. Example: I have identity server with two clients configured: client1 - RedirectUrl: https://subdomain1.example.com,  https://subdomain2.example.com

Then I have the OWIN client app:
public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
ClientId = "client1",
RedirectUri = "https://subdomain1.example.com", //how to add https://subdomain2.example.com
ResponseType = "id_token token",
Scope = "openid profile email",
PostLogoutRedirectUri = "https://subdomain1.example.com", // how to add https://subdomain2.example.com 
SignInAsAuthenticationType = "Cookies"
});
}
}
Then I have a controller:
[Authorize]
public ViewResult GetSomething()
{
return View();
}
HOw to configure OWIN to determine the redirect URL? If the Request.Url == "https://subdomain1.example.com", it should be https://subdomain1.example.com, if Request.Url == "https://subdomain2.example.com", it should be "https://subdomain2.example.com". I cannot figure out how this can be configured on the client side...

Thanks,
alex.

**Comment by apryiomka** [comment]
the OpenIdConnectAuthenticationOptions.RedirectUri currently accepts string for the redirect. What I am looking for is to provide a delegate or something for OpenIdConnectAuthenticationOptions where the Return URI can be resolved at the runtime. Just like Identity Server Clent can have multiple Return URIs, i guess, there should be a way to allow the OWIN to pick one of those and send it to the identity server...

Thanks,
Alex.

**Comment by brockallen** [comment]
You'd change it dynamically in the Notifications property of the OIWC middleware -- look at the RedirectingToIdentityprovider callback and the notification param's Protocol property.

**Comment by apryiomka** [comment]
Just tried the below modification in the OWIN implicit client sample and it worked like a charm.
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
                {
                    ClientId = "implicitclient",
                    Authority = "https://localhost:44333/",
                    //RedirectUri = "http://localhost:2671/",
                    ResponseType = "id_token",
                    Scope = "openid email",

                    SignInAsAuthenticationType = "Cookies",

                    // sample how to access token on form (when adding the token response type)
                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        SecurityTokenValidated = async n =>
                            {
                                var token = n.ProtocolMessage.AccessToken;

                                if (!string.IsNullOrEmpty(token))
                                {
                                    n.AuthenticationTicket.Identity.AddClaim(
                                        new Claim("access_token", token));
                                }
                            }, 
                        RedirectToIdentityProvider = async n =>
                            {
                                var uri = n.Request.Uri; //to do to get the return uri
                                n.ProtocolMessage.RedirectUri = "http://localhost:2671/";
                                n.ProtocolMessage.PostLogoutRedirectUri = "http://localhost:2671/";
                            }
                    }
                });
Thanks, @brockallen, a lot, you saved my day!!!!!!
Alex.
