### ISSUE TITLE
Access to UserManager from controller

### ISSUE THREAD

**Issue by pinnprophead** [IdentityServer/IdentityServer3#1459]
I am trying to extend my working IdentityServer with the EULA on login example, however I want to use the UserManager to find and update the user in the controller.

I am creating the UserManager in the boilerplate way:

![screen shot 2015-06-08 at 3 58 05 pm](https://cloud.githubusercontent.com/assets/5665944/8045186/4682ccba-0df7-11e5-8975-6652c329ad42.png)

But I cannot figure out how to get a reference to the UserManager in the controller.

The samples create a public static array of Users...

**Comment by brockallen** [comment]
We've not designed those pieces of IdSvr to be injected or usable from outside of IdSvr.

For this, you'd just use your identity management library directly from that controller.

**Comment by pinnprophead** [comment]
Ok, although I’m not sure I get that. I would think the primary place to use the UserManager would be in controllers to update user fields, add new users after registration, etc. as in the examples.

Is it a threading concern?

**Comment by brockallen** [comment]
It's just a design thing -- this wasn't designed to be consumed generally by other things. Try it -- if you can get it to work, then great.
