### ISSUE TITLE
Single sign-on into MVC application from mobile client

### ISSUE THREAD

**Issue by jaydinslage** [IdentityServer/IdentityServer3#1460]
I'm having one heck of a time figuring out a way to handle the scenario I'm being given and would like any thoughts you might have.  Please forgive anything that isn't clear, I'm running in circles here and am fried at this point.

I have a mobile client that is authenticating with Identity Server.  It gets an id_token, access_token, and refresh_token.  This mobile client now needs to pull up our MVC client and have the MVC client logged in.  In fact, the mobile client may need to be able to load up different MVC clients depending on interaction from the user.  The mobile client and each MVC client need the ability to have different timeouts.  The mobile client will, most likely, have a very long timeout before needing to log in again, however, the MVC clients will be much shorter and each one may be different.  When the MVC clients timeout, the requirement is for the user to have to login, even if they don't have to on the mobile client. Now, the MVC clients are also standalone, meaning you can go directly to them from a browser.  

Now, the problem with using the Identity Server cookie, is that:
1. It has a single timeout across all clients.  
2. I cannot guarantee that we will not have an application or a change to the mobile application where there is no web-based interaction (meaning that there is no cookie set).

My next thought was to pass the access_token and/or the id_token into the MVC application and build the local (MVC application) cookie off of that.  From my point of view, this would mean that the MVC applications are a "resource" of the mobile application.  
This is problematic because:
1. If I just use the mobile access_token, it may expire and even if the mobile application provides the refresh_token the MVC application is a different client and cannot get a new access code using it's client ID and the mobile applications refresh token.
2. If I just pass an access_token, I will not have an id_token and cannot get one for the MVC application with just an access token.  This means that I have a problem with sign-out.
3. The MVC client is using the hybrid flow and therefore I can't get a new access_code for the user using just the client_id and client secret (since that is a different flow).  I can use a different client_id for this, but I believe that I'll lose the user level claims on the access token.

I did give some thought to using a custom grant type for the token endpoint, but there seems to be no hook-in where I can generate an id_token without actually going through the authorization endpoint.

I've searched the web up and down and just haven't really found anything that matches our requirements. So, under these conditions, what is the best course of action?

**Comment by brockallen** [comment]
How is your mobile app launching the browser for its SSO? An embedded browser, or the external system browser?

**Comment by jaydinslage** [comment]
I believe that initial implementation will be worth an embedded browser, but I'm not the one in charge of that portion, so they could change their mind. I do have the ability to offer suggestions though.

**Comment by jaydinslage** [comment]
Possibly to clarify a bit, what I'm trying to achieve is single sign-on using an access_token.  With verification of the issuer, and because our server is the only one with the private key of the certificate, the access_token should be secure.

Single sign-on in this way, I figure, can be achieved 2 different ways.  Either by allowing the MVC application to "act as" the user, using the id_token and access_token from the mobile application, or using the access_token to build up everything that is needed in the MVC application by accessing the token endpoint (or by hitting our own endpoint on identity server).

I just don't think that the Identity Server cookie can be trusted to be there in this case.  If the mobile application has a timeout of, say, 30 days, that means that the Identity Server cookie would need to be available.  If the user, for some reason, cleared cookies on their device, or if the device unloaded the browser and cleared the cookies, the MVC application would require the user to log in.

My issue is that none of these options seem to follow any OAuth or OIDC protocol and I can't imaging that I'd be the only one with this issue.  Both options above lead to their own problems.  The first is that if the access token expires before the MVC applications timeout, there is no way to get a new access token for that user.  The second one has an issue because there seems no way to get an ID token except from using the authorization endpoint or an access token for the user without the users username and password.  This leads me to wonder if there is another way that this can be accomplished?

**Comment by brockallen** [comment]
The Idsvr cookie is for IdSvr, not for the clients. Thinking about it as the cookie for all your clients, I think, makes your world a more complicated one.

As for trying to get SSO across the embedded browser for your mobile app, and the external browser for your MVC app is a platform problem. The mobile platforms don't have a great story here.

I'd have to really think hard about passing "stuff" from your mobile app to your MVC app to authenticate. There might be subtle security issues with that.

And you're right -- I don't know of any specs that have this workflow in mind. That's why I'm caution to provide suggestions -- there are probably lots of attacks against some home grown system. But then again, maybe not.

**Comment by jaydinslage** [comment]
Sorry for the late reply - tough deadlines and too busy.  I appreciate your thoughts on this.  For the sake of others and possibly any comments you may want to make, here is what I've done:

The mobile client will send their access token and identity token to the application it want to single sign-on into.  The access token is added as a bearer token in the authorization header.  This access token is validated by the client application and then a request is made to the token endpoint.
I then created a new client for the application and used the custom flow.  This allowed me to use my own custom grant type to retrieve an access token and refresh token from the token endpoint.  I implemented my own custom grant validator that validates the access token (passed as a bearer token) and the identity token (passed as an assertion/form value). Using the default token validator, I validate that the access token is valid and not expired and that the identity token is valid (currently not caring about expiration).  The subject of the access token and identity token must match and the issuer must be our identity server.

Because our identity server uses a certificate that is only on that machine, I feel confident that we will only be able to accept tokens from an application that is registered with our identity server.  In the future, I'll also add code to ensure that a client must opt-in to single sign-on (this custom grant type).

If you can think of any other checks or concerns that you have, I'd be happy to entertain them and make adjustments to ensure that this is secure.  I, also, am very leery to roll any authentication scheme myself, and I understand the risks of doing so.  This ended up being one of those "This is required" directives.

**Comment by leastprivilege** [comment]
Is there anyone who wants to add something?
