### ISSUE TITLE
Multiple redirect after login

### ISSUE THREAD

**Issue by vinayhfs** [IdentityServer/IdentityServer3#1461]
I want to know that with current identity server 3 is following scenario possible?
User redirected from site to identity server login screen. He entered his credentials then we show intermediate screen (like we have for EULA). On this screen user has option to choose where he want get redirected.
Example- Once user is authenticated he can work with 2 sites say S1 and S2. So he comes from site S1 for login on intermediate screen he choose site S2 to work with then can we redirect him to S2?
If it is possible how can we achieve this?

**Comment by brockallen** [comment]
This sounds like a client that acts as a portal.
