### ISSUE TITLE
single-sign-on browser and native application

### ISSUE THREAD

**Issue by evilgamr** [IdentityServer/IdentityServer3#1462]
Hello,
We are trying to improve the user experience with single-sign-on with indentity server between a regular browser and a native application (mainly a .net desktop application with wpf).

The existing solution using an embedded browser has the major drawback of having the user to enter again their credentials despite he has already done so in other browser-based applications.

We plan to transfer some evidence from the browser to the native application in order to allow the native application to be able to request an access_token to the identity server without requiring the user to manually authenticate himself again.

My question is both about the security concerns in this escenario and how to implement the delegated autentication in the native application.

I've read about the assertion flow and i'm not sure if can be applicable here. Another possibility can be to tweak the identity server user service.

Any advice will be appreciated,
thank you.

**Comment by leastprivilege** [comment]
Well - you could transfer the id_token to the native app. It would need to be re-validated there using (e.g. by pulling the data from the expected discovery document.

This is a bit of a hack though since strictly speaking both clients now share a client_id. But technically it would work.

**Comment by evilgamr** [comment]
Then after receiving the id_token, the native application should validate it again using the downloaded public key. 

After that, the idea is to call the authorize endpoint using the embedded browser and provide the previous id_token. The customized user service will trust the provided token and issue a new id_token with the new client_id. The user will then become logged in with the native client and will be able to request the required access token as usual.

I think the most sensitive point is when transferring the id_token between the browser and the native client. We plan to use a simple encryption using a shared key to make it harder to hack, but I don't find any good solution here.
