### ISSUE TITLE
Thinktectute identity server3 support for windows authentication.

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1463]
Hi, 

I have requirement to generate tokens without using username and password from identity server. 
Will Think tecture Id server supports windows authentication?

**Comment by leastprivilege** [comment]
We think about adding it to Core for 2.x - but in any case it will be implemented as a external identity provider. You can have that functionality today by using: 

https://github.com/IdentityServer/WindowsAuthentication

**Comment by dhanutpk** [comment]
I have downloaded source from the above link and when I ran webhost project It was generating xml file. what is next step?How to test Windows Auth? It would be great if you could please provide documentation.
How to use this library in conjunction identiity server3.?

**Comment by leastprivilege** [comment]
We don't have docs rights - the server acts as a WS-Fed STS. Add it to IdSrv as you would add ADFS.

**Comment by dhanutpk** [comment]
As you said, I have added DLL to IdSrv and configured it in startup page of IdSrv. What is the nextstep.? 
//idsrvApp.UseWindowsAuthenticationService(new WindowsAuthenticationOptions
                //{
                //    IdpRealm = "urn:idp",
                //    IdpReplyUrl = URL,

                //    SigningCertificate = LoadCertificate()
                //});
What is the nextstep.?

**Comment by leastprivilege** [comment]
You need to register it as an external identity provider - check the docs (it uses WS-Fed just like ADFS). The Windows auth server must run in a separate web app configured for windows auth.

— 
cheers
Dominick Baier


On 12 Jun 2015 at 13:31:12, dhanutpk (notifications@github.com) wrote:

As you said, I have added DLL to IdSrv and configured it in startup page of IdSrv. What is the nextstep.?
//idsrvApp.UseWindowsAuthenticationService(new WindowsAuthenticationOptions
//{
// IdpRealm = "urn:idp",
// IdpReplyUrl = URL,

            //    SigningCertificate = LoadCertificate()
            //});

What is the nextstep.?

**Comment by Eric198727** [comment]
Hi 
I'm sorry if my questions are dumb, i'm really new to this whole topic...
I registered ws-fed as external identity provider, put the url from the Selfhost windowsAuth project as Metadataadress and in the WindowsAuth project my IdServer url as ReplyUrl.
As IdServer i am using the "Simple Sample" Server.

Now How do i have to set up the client to get an acccess token with my windows user?
In the Sample the Users where InMemoryFactory, where can i get the users now for an easy example?
If this question does not belong in here, please forgive me, im very thankful for every help in the right direction.

cheers
Illu

**Comment by leastprivilege** [comment]
I don't have a proper sample right now - but this org contains the WindowsAuthentication repo. Host this in a Windows authN web application - then you can use the following code to request a token using Windows authentication:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var handler = new HttpClientHandler
        {
            UseDefaultCredentials = true
        };

        var oauthClient = new OAuth2Client(
            new Uri("https://localhost:44350/token"),
            handler);

        var result = oauthClient.RequestCustomGrantAsync("windows").Result;
    }
}
```

This will give you a JWT access token back. You then need to create a custom grant validator in your "prmary" IdSrv that converts this JWT to a new access token for your services.

**Comment by Eric198727** [comment]
hi,
thank you for your answer.
So if i undestood properly, the /token endpoint of the windows authN server should give me a jwt token when sending my default credentials, like in your snippet above?
When I try this with the Selfhosted or the IIS Webhost Project I get an "401 Unauthorized" error.

Where in the windowsauthentication project is the part where it validates the credentials and generates the token?

**Comment by leastprivilege** [comment]
Here:

https://github.com/IdentityServer/WindowsAuthentication/blob/master/source%2FWindowsAuthentication%2FConfiguration%2FWindowsAuthenticationTokenProvider.cs#L41

which only works if the application is configured for Windows authentication.

**Comment by illukarl23** [comment]
hi,
now i get the accesstoken from the windows authN server(the 401 error before, was because fiddler was running in the background...), I send the token as string to the primary idSrv per custom grant, and than i wanted to validate the token against the windows authn server, and only if the token is valid generate the idSrv token. How can i validate it, is there an endpoint for this?

Is this how you meant it when you said that i needed the custom grant validator?

Thank you!

**Comment by leastprivilege** [comment]
Yep - inside your custom grant validator you use the JwtSecurityTokenHandler from MS to validate the JWT and map to a IdSrv user.

**Comment by illukarl23** [comment]
Thank you very much, it works now :)

**Comment by PaulNorth** [comment]
I have been trying to get this working self hosted (and running as the currently logged on domain user) and found the User Identity was always null on the server.  So in case this saves anyone else's time, the solution I found was to change the AuthenticationSchemes in https://github.com/IdentityServer/WindowsAuthentication/blob/master/source/SelfHost/WindowsAuthenticationExtensions.cs#L17-18 to  AuthenticationSchemes.IntegratedWindowsAuthentication or  AuthenticationSchemes.Ntlm as per the answer to this question: https://social.msdn.microsoft.com/Forums/en-US/c2ba1e1c-3ff8-4c74-874e-2de2bcb1a4c1/httplistener-windows-authentication-fails-for-domain-account?forum=netfxnetcom.  If this rings any alarm bells I would appreciate a response :)

Thanks @leastprivilege

**Comment by phillee007** [comment]
@illukarl23 Would it be possible to share the code for your custom grant validator? Thanks

**Comment by arkoc** [comment]
Any sample for validating `access_token` granted from `WindowsAuthenticationService` in Custom Grant Validator?

**Comment by Herowin8x** [comment]
Hi all,

Please get source codes with below link
http://blog.rogue-code.org/identity-server-3-plus-windows-authentication/

Thanks author so much, this article save times about 2 days for investigation and implementation it.

Thanks
Tuan Nguyen.
