### ISSUE TITLE
Error when hosting more than 1 instance

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/IdentityServer3#1464]
I had this up and running before 1.6.1 (I believe I was at 1.4 at the time) and will grab the source later this week to try and understand what is occurring but I wanted to toss this out as an issue in case someone has already run into it.

There will be a total of 5 Idv3 instances being hosted off of this service which was a design decision that came out of a long conversation with Brock on a separate issue a while back.

In 1.6.1 when I attempt to access the Idv3 instance that is registered first, it is successful and works as expected. When the second instance is hit (testing with Postman), the exception below is thrown. They use the same redis cache and database (EF). Here is how I am wiring them up at present.

````c#
app.Map("/" + TEST.Core.Constants.Components.Inst1.IdentityServer.UriPart,
                idsrvApp => idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = CloudConfigurationManager.GetSetting("Idv3SiteName"),
                    IssuerUri = CloudConfigurationManager.GetSetting("https://127.0.0.1:21465/inst1"),
                    SigningCertificate = Cert.Load(),
                    Factory = LockdownIdentityFactory.ConfigureInst1(CloudConfigurationManager.GetSetting("DbConnection"), RedisConnectionMultiplexer.Connection),
                    CorsPolicy = CorsPolicy.AllowAll,

                    AuthenticationOptions = new AuthenticationOptions
                    {
                        CookieOptions =
                        {
                            ExpireTimeSpan = TimeSpan.FromSeconds(90),
                            SlidingExpiration = false,
                            Prefix = TEST.Core.Constants.Components.Inst1.IdentityServer.CookiePrefix
                        },
                        EnablePostSignOutAutoRedirect = true,
                        PostSignOutAutoRedirectDelay = 1

                    },
                    LoggingOptions = new LoggingOptions
                    {
                        EnableHttpLogging = true,
                        EnableWebApiDiagnostics = true,
                        IncludeSensitiveDataInLogs = true,
                        WebApiDiagnosticsIsVerbose = false
                    },
                    EventsOptions = new EventsOptions
                    {
                        RaiseFailureEvents = true,
                        RaiseInformationEvents = true,
                        RaiseSuccessEvents = true,
                        RaiseErrorEvents = true
                    }
                }));

             //Inst2
            app.Map("/" + TEST.Core.Constants.Components.Inst2.IdentityServer.UriPart,
                idsrvApp => idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = CloudConfigurationManager.GetSetting("Idv3SiteName"),
                    IssuerUri = CloudConfigurationManager.GetSetting("https://127.0.0.1:21465/inst2"),
                    SigningCertificate = Cert.Load(),
                    Factory = LockdownIdentityFactory.ConfigureInst2(CloudConfigurationManager.GetSetting("DbConnection"), RedisConnectionMultiplexer.Connection),
                    CorsPolicy = CorsPolicy.AllowAll,
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        CookieOptions =
                        {
                            ExpireTimeSpan = TimeSpan.FromSeconds(90),
                            SlidingExpiration = false,
                            Prefix = TEST.Core.Constants.Components.Inst2.IdentityServer.CookiePrefix
                        }
                    },
                    LoggingOptions = new LoggingOptions
                    {
                        EnableHttpLogging = true,
                        EnableWebApiDiagnostics = true,
                        IncludeSensitiveDataInLogs = true,
                        WebApiDiagnosticsIsVerbose = false
                    },
                    EventsOptions = new EventsOptions
                    {
                        RaiseFailureEvents = true,
                        RaiseInformationEvents = true,
                        RaiseSuccessEvents = true,
                        RaiseErrorEvents = true
                    }
                }));
````
Server Error in '/' Application.

Value cannot be null.
Parameter name: context

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: context

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[ArgumentNullException: Value cannot be null.
Parameter name: context]
   Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:0
   Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:0
   Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:0
   Thinktecture.IdentityServer.Core.Extensions.OwinExtensions.ResolveDependency(IDictionary`2 env) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Extensions\OwinExtensions.cs:246
   Thinktecture.IdentityServer.Core.Configuration.Hosting.<IsOriginAllowed>d__5.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\Hosting\CorsPolicyProvider.cs:71
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +31
   Thinktecture.IdentityServer.Core.Configuration.Hosting.<GetCorsPolicyAsync>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\Hosting\CorsPolicyProvider.cs:51
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +31
   Microsoft.Owin.Cors.<Invoke>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:0
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Owin.<<ConfigureIdentityServerIssuer>b__1>d__7.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureIdentityServerIssuerExtension.cs:49
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Owin.<<ConfigureIdentityServerBaseUrl>b__0>d__3.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureIdentityServerBaseUrlExtension.cs:43
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Owin.<<ConfigureRequestId>b__0>d__2.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureRequestIdExtension.cs:37
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Thinktecture.IdentityServer.Core.Configuration.Hosting.<Invoke>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\Hosting\RequireSslMiddleware.cs:48
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +905
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +1267
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +318
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +283
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.Rethrow() +49
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +211
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +56
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +363
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157

**Comment by jlegan** [comment]
I am still struggling to find time to work this but I tracked down where the exception is occurring.

````
internal static ILifetimeScope GetLifetimeScope(this IDictionary<string, object> env)
````
returns a null scope from the Autofac container and then the next line of code that fires is the resolving of the CorsPolicyService which explains the stack. It is unclear to me whether this was a breaking change in 1.6.x due to the autofac changes or if it is config related on my end but I do not appear to have access to the container in any instance loaded after the first. For reference, I am using Unity as the IoC container for project as a whole outside of Idv3.

**Comment by brockallen** [comment]
Oh yes -- so seems that multiple instances of IdSvr in the same pipeline are stepping on each other's item in the OWIN environment. Hmm...

**Comment by brockallen** [comment]
Ah, ok, I think I know what's happening -- AutoFac is preventing itself from being registered for the subsequent instances of IdSvr. Let me go think about it.

**Comment by brockallen** [comment]
Ok, I pushed 1.6.2 to fix this. Please test and let us know.

**Comment by jlegan** [comment]
Brock,

It appears to be working as expected. Thank you for the quick turn around on the issue.

Jim
