### ISSUE TITLE
Impersonate user

### ISSUE THREAD

**Issue by MauricioArroyo** [IdentityServer/IdentityServer3#1465]
First of all I have to say that your product is an awesome piece of code and I am grateful that you share this with the world. Thank you!

Praise aside, this is my scenario...

Our current application gives the an admin user the option to impersonate another user. (this is a kind of follow up on issue #560)

I am working on changing our authentication to use identity server and would like to include this functionality on the change.

Based on what @brockallen commented on the previous issue, I would like to validate my next steps to make sure I am not breaking any intended design on idSvr and ask a few questions out of my learning curve on IdSvr.

This is what I am thinking to do:
- In my app, the admin will have an action (selecting an username) to "Login as User".
- On click, I'll send a get request to the authentication endpoint, including the custom login_hint, for instance impersonate:username
- On the PreAuthenticateAsync, 
   - if loginHint is empty then base.PreAuthenticateAsync(message)
   - if loginHint is not empty then
          - Authenticate the caller and make sure she's an admin (this part I am not really sure how to do it yet.... How can I access the admin data? Should I include it as Bearer and validate it manually on the Preauthenticate event?)
          - If the Authentication returns null or if the identity doesn't have the claim of "Admin", then return an AuthenticateResult with error message
          - Using my injected UserManager, take the username out of login_hint and find the user
          - If I found the user and it's active create a AuthenticatedLogin (Cookies, not sure about the IdentityProvider, and the user data)
         - IssueLoginCookie for the AuthenticatedLogin
         - Return AuthenticationResult using the message.ReturnUrl and the data on AuthenticatedLogin.

Some of my questions and logic may be basic, I am still wrapping around my head on OpenId Connect, oAuth2, and IdentityServer implementation :)

Thanks in advance for your help.

**Comment by brockallen** [comment]
I'd suggest a custom `acr_values` instead. 

As for authenticating the current caller, you have the OWIN context -- use the Authenticate API against the IdentityServer primary authentication type (there's a constant for it).

The rest seems about right.

**Comment by MauricioArroyo** [comment]
Hey @brockallen, thank you for your answer.

I changed it to be an acr_value and it's working fine.
Now, I am having issues with the authentication, if you have any other tip it will be greatly appreciated.
I am trying the following line but authentication is always null. 
I enabled the Logging and the only message I am getting is "Starting IdentityManager configuration"
```javascript
var authentication = await context.Authentication.AuthenticateAsync(Thinktecture.IdentityServer.Core.Constants.PrimaryAuthenticationType);

**Comment by brockallen** [comment]
Actually, you don't even need to call Authenticate on the OWIN context -- the User property should be set. Check that.

**Comment by MauricioArroyo** [comment]
I am probably missing something trivial here :)
The context.Authentication.User is not authenticated (no claims, no Authentication Type). I am checking it and trying the AuthenticateAsync in the PreAuthenticateAsync.
I guess since I am not configuring the idSrv to use Bearer Token, it doesn't authenticate the user. I am going to try with UseJwtBearerAuthentication on the configuration of the idSrv itself and let you know.

Thanks again!

**Comment by MauricioArroyo** [comment]
Didn't work. Still not authenticated user. :( Now, how will the User be authenticated if I am in the PreAuthenticate event and never call the actual authentication (ignoring my try with the Bearer Token)?
I hope this is not a dumb question!

**Comment by brockallen** [comment]
The user should be authenticated, the cookie should be reflected there. 

Also, from your client, make sure you pass prompt=login to force getting to the login page. If the user is already authenticated then the authorization page will just return... so the prompt=login forces the login page.

**Comment by MauricioArroyo** [comment]
Thanks Brock,

My bad! I was using httpClient to authenticate again and not sending any cookie with it. I changed that for a redirect (following the samples) and now I get the authenticated user with it.
With that info I am able to get the roles, and validate the admin claim.

Now, what I was trying to do is not working (at least not as I expected). I am using the following code after validating the current caller:

```javascript
                //Log out current user
                context.Authentication.SignOut();
                //Get the claims of the user being impersonated
                var claims = await this.GetClaimsForAuthenticateResult(user);
                //Generate an Authenticated Login
                var login = new AuthenticatedLogin()
                {
                    AuthenticationMethod = "Cookies",
                    //I still don't know about this part, since the user could be a facebook user, not only IdSv
                    IdentityProvider = Thinktecture.IdentityServer.Core.Constants.BuiltInIdentityProvider,
                    Subject = user.Id,
                    Name = user.UserName,
                    Claims = claims,
                };
                //I tried generating the LoginCookie. I do the same in the registration page
                context.Environment.IssueLoginCookie(login);
                //return not null, so we stop the authentication at this point
                return await Task.FromResult(new AuthenticateResult(user.Id, user.UserName, claims));
```

If I return `Task.FromResult<AuthenticateResult>()` it goes to the login page requesting authentication which tells me (based on the comments from @brockallen about prompt login) that it shouldn't since I have a Cookie for the Authenticated user in place.

Returning the AuthenticateResult with user data It returns to my mvc application, but the 'SecurityTokenValidated' notification is not fired, and my user doesn't swtich, it is still the admin. if I go to Logout, the menu shows my impersonated user.

Again, help will be greatly appreciated.

**Comment by brockallen** [comment]
I'm not sure about the client side not working -- it's worked for me in the past.

**Comment by MauricioArroyo** [comment]
Hey Brock,

Does my logic in the code make sense? 
On the client side I am just redirecting to the Authentication end point, and expecting it to later redirect to the main page (I am using the MVC sample for this). Maybe I am missing some step here... I don't know... I am checking the identityServer code now to understand better the flow.

Thanks for all your help!

**Comment by MauricioArroyo** [comment]
Hi Brock,
I checked this issue a little bit more and realized this is not a IdentityServer issue but a Microsoft.Katana.
The OpenIdConnectAuthenticationHandler on http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs checks that the state has a group of expected properties. Actually a comment at AuthenticateCoreAsync says:  " runtime always adds state, if we don't find it OR we failed to 'unprotect' it this is not a message we should process".

I would be great to rely on the already in place authentication process of the Katana, nevertheless the pieces to handle it are not in the public interface so I decided to move to using a CallBack on a controller after the authentication call (as in one of the samples) and it worked great.

I learned a lot during this process. Thanks for all your support.

M.

PS: I will read the policy on pullrequest and upload a sample with this, in case body else needs this functionality.

**Comment by brockallen** [comment]
There's one sample of ours that shows doing the client side all manually (without the Katana OIDC middleware). It's not 100% complete, but it gives an idea.

**Comment by vijay2358** [comment]
Thanks Brockallen and MauricioArroyo,
Is that working fine you!!.. i am also having this issue.. is that fixed in middleware katana.. i am refeing that idm manager for more samples.. please help me how we can send the AuthenticatedLogin in server or client once it done what event need to call do not hit the login..

**Comment by MauricioArroyo** [comment]
Hi vijay2358,
The impersonation is working fine. The only issue I have is you can't have two simultaneous logins with the server. Once you impersonate an user that becomes you identity when accessing the idsvr again, and that seems OK. We are reevaluating the need for impersonation in our app at the moment.

I managed to handle that with the middleware using a Challenge, I can send you the sample tomorrow.

I planned on uploading a pull request with this, so maybe this is my chance to do it ;) 

I'll be glad to help you and give back some of the help I got here from Brock Allen.

**Comment by MauricioArroyo** [comment]
Hi vijay2358,
The impersonation is working fine. The only issue I have is you can't have two simultaneous logins with the server. Once you impersonate an user that becomes you identity when accessing the idsvr again, and that seems OK. We are reevaluating the need for impersonation in our app at the moment.

I managed to handle that with the middleware using a Challenge, I can send you the sample tomorrow.

I planned on uploading a pull request with this, so maybe this is my chance to do it ;) 

I'll be glad to help you and give back some of the help I got here from Brock Allen.

**Comment by vijay2358** [comment]
Thanks a lot, 
Can you please send the sample..

**Comment by MauricioArroyo** [comment]
Hi vijay2358,
Sorry for the delay.

In my scenario, we have an admin website. An authenticated admin user is able to use the "Sign in as user" action to open the main website under some regular user credentials.

In the admin site I basically have an action link to a controller in the main site, passing the username name of the user to be authenticated. 

Once in the main website (with the given username), I have something similar to this:

```javascript
public async Task<ActionResult> ImpersonateUser(string username)
{
   if (await IsValidUser(username))
   {
        //I save the username to be impersonated in the OwinContext so I can read it before sending the atuhentication request
        Request.GetOwinContext().Set("Impersonate", username);
        return new ChallengeResult("OpenIdConnect", "Redirect Url of my site");
   }

   //If the user is not valid you can return null, or an exception, that would depend on what you need.
}
```
The ChallengeResult class is an internal class derived from HttpUnauthorizedResult. IIRC I got this class from the MVC5 template.

```javascript
internal class ChallengeResult : HttpUnauthorizedResult
{
    // Used for XSRF protection when adding external logins
    private const string XsrfKey = "XsrfId";
 
    public ChallengeResult(string provider, string redirectUri)
        : this(provider, redirectUri, null)
    {
    }
 
    public ChallengeResult(string provider, string redirectUri, string userId)
    {
        LoginProvider = provider;
        RedirectUri = redirectUri;
        UserId = userId;
    }
 
    public string LoginProvider { get; set; }
    public string RedirectUri { get; set; }
    public string UserId { get; set; }
 
    public override void ExecuteResult(ControllerContext context)
    {
        var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
        if (!string.Empty(UserId))
        {
            properties.Dictionary[XsrfKey] = UserId;
        }
        context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
    }
}
```
The rest is handled in the OpenIdConnectAuthenticationOption while configuring the OWIN Middleware. You need to include the impersonation data in the request by listening for the RedirectToIdentityProvider notification, check for the impersonation flag in the owin context, and if it's there, send the AcrValue to the server with the username to impersonate.

```javascript
var openIdConnectAuthenticationOptions = new OpenIdConnectAuthenticationOptions
      {
          //... other configuration options
          Notifications = new OpenIdConnectAuthenticationNotifications
          {
              RedirectToIdentityProvider = async n =>
              {
                  if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
                  {
                      var impersonateModeUser = n.OwinContext.Get<string>("Impersonate");
                      if (!string.IsNullOrEmpty(impersonateModeUser))
                      {
                          n.ProtocolMessage.AcrValues = string.Format("{0}:{1}", "Impersonate", impersonateModeUser);
                          n.ProtocolMessage.Prompt = Constants.PromptModes.Login;
                      }
                  }
              }
          }
```

Since the call to the Identity Server will include the cookie with the admin credentials, you can validate the user Claims to make sure she is allowed to impersonate an user etc.
As BrockAllen recommendation I included the Prompt Login, to ensure the Authentication process runs all the way. 
In the PreAuthenticateAsync method of my UserService is where I check for the AcrValue and handle the authentication accordingly.

I hope it helps, let me know if there is anything else I can help you with.

**Comment by vijay2358** [comment]
Thanks a lot for providing sample, it is working from client. Now I can bale see the AcrValue in Identity server, there i need get by owin env or with context . How can I get that  AcrValue PreAuthenticateAsync

**Comment by MauricioArroyo** [comment]
The SignInMessage you get in the PreAuthenticateAsync has a property AcrValues.

**Comment by devployment** [comment]
@MauricioArroyo Interesting ticket and solution for a similar problem of mine. :+1: 

How do you deal with the fact that the login is replaced in the new tab for the other tabs that are probably open? Do you have any special handling here? 

Currently thinking about using the oidc-token-manager (https://github.com/IdentityModel/oidc-token-manager) but for what I can see that would result in nasty polling the IP.

Not entirely sure on how the session spec plays are role here. But if IIRC it might be exactly this. Notifying other applications (tabs?) that something changed on the authentication.

**Comment by devployment** [comment]
@MauricioArroyo Not a single day IdSrv does not surprise me. As I'm already using the oidc-token-manager im basically set. 

https://github.com/IdentityServer/IdentityServer3.Samples/tree/0f3a25364e1dd56fd19c7ae309f98df8ba1005b9/source/Clients/JavaScriptImplicitClient

@brockallen @leastprivilege Sorry for hijacking this ticket. But I just have to say **_THANK YOU_** for all the work and support you put in this project. It's just amazing.

**Comment by MauricioArroyo** [comment]
Hey @devployment,

If your application is based on JavaScript, I would say that's definitely the way to go. In my case it's basically an MVC app, (slowly moving toward angular though).

@vijay2358 Did it work for you?

**Comment by danda1man** [comment]
@MauricioArroyo how did you handle marking the user as impersonated?  I tried adding claims like this in PreAuthenticateAsync, but since I don't persist them to the user store, they are unavailable to the client applications.

```
List<Claim> impersonationClaims = new List<Claim>
{
     new Claim(Core.Constants.ClaimTypes.IsImpersonating, "true"),
     new Claim(Core.Constants.ClaimTypes.OriginalUserName, currentUser.UserName)
};

context.AuthenticateResult = new AuthenticateResult(impersonatedUser.Id.ToString(), impersonatedUser.UserName, impersonationClaims);
```

My work around in the client application is to check if the OwinContext username does not match the username of the incoming token and the re-add those claims within the client, but I was wondering if anyone else had a more elegant way of noting the user is being impersonated.

**Comment by MauricioArroyo** [comment]
@danda1man Sorry I didn't see this message before. I was pretty much disconnected most part of last month. 
In my case, I don't mark the user as impersonated. I add the authentication method in the user indicating that I used the guest though.

Basically on the PreAuthenticateAsync I check if the acr_value was sent indicating that I need to authenticate the user as guest. And return the result of a private method that ends up returning something like this:
  return new AuthenticateResult(
               guestUserId,
               guestUserName,
               claims,
               authenticationMethod: <MyGuessAuthenticationMethod>);

I get the UserId from the acr_values, the username, I just use the UserId to generate a generic name and in the claims parameter you can add the special claims you need, in my case I add the role of regular user.


I hope this helps, even a little bit late. (sorry again)

**Comment by MauricioArroyo** [comment]
@brockallen I would like to add this login as guest implementation in one of the samples. Seems to be useful for more people.
Should I use the clients on samples? Maybe modify one of the existing ones? What would be your recommendation?

Thanks in advance!

**Comment by brockallen** [comment]
I'd say make a sample available on your repo and we can have a look.

**Comment by segfahlt** [comment]
@MauricioArroyo I have exactly the same need. I'm just looking into the Identity Server docs now, this is basically the 3rd or 4th thread I've read.  Did you get your example solution put together?  I'd sure love to take a look at it. Would probably save me loads of research time.

**Comment by MauricioArroyo** [comment]
@segfahlt Yes, I did. Actually we released that a few weeks ago in production :). I have no problems showing that to you. I am planning on uploading that to a branch during this weekend and the next.

**Comment by segfahlt** [comment]
@MauricioArroyo  that would be awesome. I'm digging through the code now, and [think] I may be able to get it going, but it's giving me a headache. Not the code, per se, just the steep learning curve for Authentication stuff. oy.

**Comment by danda1man** [comment]
@mauricioarroyo @segfahlt, I will try and get my implementation up this weekend too

**Comment by MauricioArroyo** [comment]
Great, so Bill, you'll have two implementations to take a look and help you with your issue.

@segfahlt In case you need some guidance sooner, shot me an email (Mauricio.Arroyo@gmail.com) and we can talk over a hangout, I can show you the code.

**Comment by segfahlt** [comment]
Thanks guys!  After reading up on Identity Server for a couple hours yesterday and understanding the high level stuff, I think my scenario is a bit different.  My implementation is actually using the Token endpoint, not the Authentication endpoint. I'm thinking I still need a custom UserService, but not 100% sure of that yet.  @MauricioArroyo, the code snipped you posted above are great!, and I think I can use them to get myself going.  If not, I might have to take you up on your offer of help, which I very much appreciate.

**Comment by danda1man** [comment]
@segfahlt Was getting too complicated to pull out all of my application stuff so I just wrote up a [blog post with all of the important parts](http://djsharepoint.com/blog/2016/03/impersonation-in-identity-server-3/).

**Comment by evgenisokolov** [comment]
Hi! I'm trying to implement this approach in my Web API project and I have a problems with it.
1. I cannot find analog of ChallengeResult in web api (I cannot return ActionResult)?
2. I tried to call GET /connect/authorize?client_id=client1&scope=openid email api1&response_type=id_token token&redirect_uri=https://myapp/callback&state=abc&nonce=xyz&prompt=login directly but I cannot get current user from owin context it's looks like it's not logged in
3. I tried to hardcode current user id in PreAuthenticateAsync. I received login page in response after I set user to impersonate to context.AuthenticateResult
What I'm doing wrong?

**Comment by MauricioArroyo** [comment]
Hi @evgenisokolov,

1. I added that class myself. (I think I got it from an MVC6 project).

As for the rest. I would try to create a small project with what you have so far and troubleshoot from there. Turn on the diagnostics and see what you get.

Best regards,

Mauricio
