### ISSUE TITLE
How to access directly Login page?

### ISSUE THREAD

**Issue by xoofx** [IdentityServer/IdentityServer3#1467]
Hi,
I'm looking into IdentityServer to develop a server that would provide an account service (create, edit...etc.) with openid capabilities. 

Then I'm trying to just add a Login page and I'm a little bit stuck with this simple problem... 

For this, I would expect that I don't have to add a specific client (with claims...etc.) for the account service, as I expect it to be part of the service (what provides IdentityServer + the registration/profile page).

So for instance, I would like to rely on the already existing login page of IdentityServer. I have tried to add a "Login" page that redirects to the identityserver page using:

```C#
[AllowAnonymous]
public ActionResult Login(string returnUrl)
{
	var environment = Request.GetOwinContext().Environment;
	var url = environment.CreateSignInRequest(new SignInMessage());
	return new RedirectResult(url);
}
```
but I'm getting the error:
```
[ArgumentNullException: Value cannot be null.
Parameter name: context]
   Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:0
   Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:0
   Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:0
   Thinktecture.IdentityServer.Core.Extensions.OwinExtensions.ResolveDependency(IDictionary`2 env) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Extensions\OwinExtensions.cs:246
   Thinktecture.IdentityServer.Core.Extensions.OwinExtensions.CreateSignInRequest(IDictionary`2 env, SignInMessage message) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Extensions\OwinExtensions.cs:104
```
Is this the correct way to handle such a scenario?

**Comment by brockallen** [comment]
You're on the right track, but to use our OWIN extension methods your MVC code needs to be running in the same path in the web server as IdSvr. IOW, the IdSvr middleware needs to run before your MVC code.

**Comment by xoofx** [comment]
Ah, sorry, I'm not very familiar with OWIN, so let's simplify my problem without using MVC. Is it possible to add my own `ApiController` registered within the IdentityServer path? 

If IdentityServer is configured with:

```C#
app.Map("/core", coreApp =>
{
	var factory = Factory.Configure("DefaultConnection");
	var options = new IdentityServerOptions
	{
		SiteName = "MyWebSite",
		SigningCertificate = Certificate.Get(),
		Factory = factory,
		CorsPolicy = CorsPolicy.AllowAll,
	};
	coreApp.UseIdentityServer(options);
});
```
Is there any way to add a route to my own ApiController within "core"?

**Comment by xoofx** [comment]
Ok, found a way to add a route within the IdentityServer that will provide the login redirect above: Adding this inside the `Map("/core"`:

```C#
var httpConfiguration = new HttpConfiguration();
httpConfiguration.Routes.MapHttpRoute(
  name: "LoginRedirect",
  routeTemplate: "login2",
  defaults: new { controller = "MyLoginRedirect", action = "Index"});
coreApp.UseWebApi(httpConfiguration);
```

Not sure it is the recommended way, but at least it seems to work.
