### ISSUE TITLE
IdentityServerBearerToken and OpenIdConnect in same MVC project

### ISSUE THREAD

**Issue by rebase42** [IdentityServer/IdentityServer3#1469]
I have completed the tutorial on http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html.

However currently I have a MVC website with also a web api included. Therefore I have users that will login and servers that will use the api. So I need to use IdentityServerBearerToken and OpenIdConnect authentication. How do I tell mvc to do this?

I have tried to add the IdentityServerBearerToken authentication to the bottom of the startup Configuration. However now when a user logs in the redirection page is blank. When I again remove the IdentityServerBearerToken authentication all is fine again.

I guess I can split the api and mvc page however I don't really want to do that if another option is possible.

Here is the code of the startup:
```
string authenticationAuthorityUrl = ConfigurationManager.AppSettings["AuthenticationAuthority"];

var authenticationAuthority = authenticationAuthorityUrl;
var redirectUri = ConfigurationManager.AppSettings["RedirectUri"];

appBuilder.UseCookieAuthentication(new CookieAuthenticationOptions
{
	AuthenticationType = "Cookies"
});

appBuilder.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
	Authority = authenticationAuthority,
	ClientId = "oxygenmanagement",
	RedirectUri = redirectUri,
	PostLogoutRedirectUri = redirectUri,
	Scope = "openid oxygen oxygenmanagement oxygenapi",
	ResponseType = "id_token token",
	SignInAsAuthenticationType = "Cookies",

	Notifications = new OpenIdConnectAuthenticationNotifications
	{
		SecurityTokenValidated = async n =>
		{
			var nid = new ClaimsIdentity(
				n.AuthenticationTicket.Identity.AuthenticationType,
				Constants.ClaimTypes.GivenName,
				Constants.ClaimTypes.Role);

			n.AuthenticationTicket.Identity.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Type, ui.Value)));

			// keep the id_token for logout
			nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));

			// add access token for sample API
			nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));

			// keep track of access token expiration
			nid.AddClaim(new Claim("expires_at", DateTimeOffset.Now.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToString()));


			n.AuthenticationTicket = new AuthenticationTicket(
				nid,
				n.AuthenticationTicket.Properties);

		},
		RedirectToIdentityProvider = async n =>
		{
			if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
			{
				var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
				n.ProtocolMessage.IdTokenHint = idTokenHint;
			}
		}
	}

});

AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";
JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
appBuilder.UseResourceAuthorization(new AuthorizationManager());

appBuilder.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
{
	Authority = authenticationAuthorityUrl,
	RequiredScopes = new[] { "oxygenapi" }
});
HttpConfiguration config = new HttpConfiguration();
config.MapHttpAttributeRoutes();

appBuilder.UseWebApi(config);
```

**Comment by leastprivilege** [comment]
why do you have registered the middleware twice?

**Comment by rebase42** [comment]
That is my question. If you look at http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html. For the Web API authorization they use UseIdentityServerBearerTokenAuthentication, but for the MVC view controllers they use UseOpenIdConnectAuthentication. I have both API and View Controllers in the same MVC project. 

In essence my question is how do I secure a MVC app where I need two different flows (Implicit and ClientCredentials) for different controllers? (Obviously the web api will be used using ClientCredentials flow while the views will be used using implicit flow.

Hope I am clear in my explanation.

**Comment by leastprivilege** [comment]
In general it is a bit messy to do both APIs and MVC in the same app - you need a combination of the OIDC and bearer token middleware - as well as the SuppressDefaultHostAuthentication option and a HostAuthenticationFilter. Check the Microsoft docs.

**Comment by huysentruitw** [comment]
You're calling `UseIdentityServerBearerTokenAuthentication` twice.

**Comment by huysentruitw** [comment]
Before you call `config.MapHttpAttributeRoutes();`, you'll have to call something like:

```C#
config.SuppressDefaultHostAuthentication();
config.Filters.Add(new HostAuthenticationFilter("Bearer"));
config.Filters.Add(new AuthorizeAttribute());
```

**Comment by rebase42** [comment]
Sorry the calling twice thing was not suppose to be there. Ok I will try that. Thanks for the help.
