### ISSUE TITLE
Mixing Windows and regular authentication

### ISSUE THREAD

**Issue by infosaurus** [IdentityServer/IdentityServer3#1470]
Hi,

I have a requirement that web applications be accessible both via a formless Windows authentication and, when the user is not validly logged in to one of the recognized Windows domains, through a fallback login form.

So far I have only looked at the regular authentication via a login page in IdentityServer which works like a charm, but I haven't seen much on the web about using IdentityServer for Windows credentials based access or any other formless authentication, let alone mixing the two.

How can I go about doing this ? 

Any suggestions welcome.

**Comment by leastprivilege** [comment]
Due to the way ASP.NET/IIS works - you will never get a totally seamless experience here. You can have a "login with Windows" on the login page - that will work - eg. using ADFS or the small Windows auth STS that we have here as a repo.

**Comment by brockallen** [comment]
We'll look to see how easy this is (possibly for 2.0.0).

**Comment by dylanplecki** [comment]
Windows-based authentication can be done in-code by importing the following function from the unmanaged ADVAPI32 DLL:

```c#
using System.Runtime.InteropServices;

[DllImport("ADVAPI32.dll", EntryPoint = "LogonUserW", SetLastError = true, CharSet = CharSet.Auto)]
private static extern bool LogonUser(string lpszUsername, string lpszDomain, string lpszPassword, int dwLogonType, int dwLogonProvider, ref IntPtr phToken);
```

This can then be integrated into the `AuthenticateLocalAsync()` function in a customer UserService, using something like below:

```c#
public class MyUserService : IUserService
{
    public virtual Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
    {
        var token = IntPtr.Zero;
        var validUser = LogonUser(GetUsername(username), GetDomain(username), password, 3, 0, ref token);

        if (validUser)
        {
            // Process user claims and similar here
            // ...

            var result = new AuthenticateResult(user.Subject, GetDisplayName(user), user.Claims);
            return Task.FromResult(result);
        }

        return Task.FromResult<AuthenticateResult>(null);
    }

    [DllImport("ADVAPI32.dll", EntryPoint = "LogonUserW", SetLastError = true, CharSet = CharSet.Auto)]
    private static extern bool LogonUser(string lpszUsername, string lpszDomain, string lpszPassword, int dwLogonType, int dwLogonProvider, ref IntPtr phToken);
}
```

Where the `GetUsername()` and `GetDomain()` functions simply split the `username` argument on the first backslash, so users can type in a username such as `domain\user`.

This makes the local login form into a Windows logon form.

**Comment by brockallen** [comment]
I suspect what's really desired is to utilize integrated windows auth from IIS.

**Comment by doublej42** [comment]
I'm implementing something like this right now. 

The site I want them to log into is outside of the domain so I am using LDAP authenticate the users.
When the login page loads I can check to see if an internal openID Connect server is accessable (http://stackoverflow.com/questions/5621697/test-if-url-is-accessible-from-web-browser-i-e-make-sure-not-blocked-by-proxy-s) and if it is I can just send them there for a token and use that token to create my own token.

**Comment by leastprivilege** [comment]
closing this one.

moved to: https://github.com/IdentityServer/IdentityServer3/issues/1567
