### ISSUE TITLE
Claims valueType serialization

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1471]
What's the status of preserving the valuetype on the claims, as discussed in #266? I'm also experiencing valuetype being reverted to string and it causes me pain.

Any idea on the timeframe for this to be supported?
Thanks

**Comment by leastprivilege** [comment]
This is basically a question for Microsoft. I think int and bool is supported by the JWT handler.

**Comment by snothub** [comment]
Thanks

I've added a int claim to the access token, but can't really handle it.

Are you referring to JwtSecurityTokenHandler? That class is internal so I can't use it. Don't see anything else.

**Comment by leastprivilege** [comment]
did you use ClaimValueTypes.Int ?

**Comment by snothub** [comment]
Yes

**Comment by leastprivilege** [comment]
oh - and are you looking at the wire format - or what you get back after validating the token in the client?

**Comment by leastprivilege** [comment]
On the wire you claim should be indeed a number now. But the value type does not round trip in Microsoft's implementation.

**Comment by snothub** [comment]
Exactly. Issued access token has the value as int, but accesstokenvalidation endpoint returns it as string.

**Comment by leastprivilege** [comment]
Why do you use the validation endpoint for a JWT?

**Comment by snothub** [comment]
*I* don't. When a call is made to my api with the access token, the AccessTokenValidation middleware makes that call to the authority url.

**Comment by leastprivilege** [comment]
Set the ValidationMode to local. But this probably will still give a string. It is because the claims model in .net is based on strings really. But give it a try.

**Comment by snothub** [comment]
You were right (still string). Well, I guess we'll have to wait then. Thanks anyway.
