### ISSUE TITLE
External Authorization for idsrv

### ISSUE THREAD

**Issue by vijay2358** [IdentityServer/IdentityServer3#1472]
Hi,

This is Vijay. I’m going thru all ur samples Identity manger, Identity server v3 and Identity manger/server Membership., I am looking for identity server which will manger internal application authorization, scope of each client then permissions, but authentication will redirect to “MY company SSO” once it validated  then I will redirect to client url upon the authorization.

1.	User login  SSO login get uid for authenticate  user  identity server get validate the  client and user roles  redirect to client1, client2 and client3, if super admin can allow to , Identity server v3 manage the application and user roles and permissions.
Please provide if any samples you have.

**Comment by brockallen** [comment]
Look at our docs on external providers. And we already have lots of samples -- you just need to read the docs.
