### ISSUE TITLE
failed to hit identity server from mvc client with VS 2012 version.

### ISSUE THREAD

**Issue by dhanutpk** [IdentityServer/IdentityServer3#1473]
Hi, 

My application failed to hit identity server(vs 2012) from mvc client with visual studio version 2012. 
It works fine when we run with vs 2013.  It would be great if could help us on this issue. ?

Error is given below. 
Response status code does not indicate success: 500 (Internal Server Error).

**Comment by brockallen** [comment]
If the response is 500, then it means there was an error in IdSvr -- enable the logs and see what they say.

**Comment by brockallen** [comment]
Any update?
