### ISSUE TITLE
The Nuget Package for identityserver v3 that we are using says it is Pre-Release

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1474]
The Nuget Pacakge that we are using says it is Pre-Release.  When is the official release expected. 

https://www.nuget.org/packages/Thinktecture.IdentityServer.v3.EntityFramework.Async/1.0.1-true

**Comment by leastprivilege** [comment]
This is not one of our packages.

— 
cheers
Dominick Baier


On 10 Jun 2015 at 19:27:09, skatukojwala (notifications@github.com) wrote:

The Nuget Pacakge that we are using says it is Pre-Release. When is the official release expected.


https://www.nuget.org/packages/Thinktecture.IdentityServer.v3.EntityFramework.Async/1.0.1-true

**Comment by skatukojwala** [comment]
Which package to you suggest us to use?

**Comment by leastprivilege** [comment]
The ones from our docs
