### ISSUE TITLE
Azure ACS - specifying clientId

### ISSUE THREAD

**Issue by locutus80** [IdentityServer/IdentityServer3#1476]
First - this software is awesome, but I'm new to this and have hit a stumbling block

I don't full understand how a client is identified: I'm using the sample AspNetIdentity code and have got everything working in as much as Azure ACS is able to use the IdentityServer as an identity provider and people can sign in. My n00b mind has been expanded by getting to grips with this.

However, I am not getting any claims back other than these:

http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier 
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider
http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod 	
http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant 	

I've looked in Clients.cs and Scopes.cs from the sample, and also see in the debug trace that the clientId is null:

ebug: [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 6/11/2015 12:45:48 AM +00:00 -- signin message passed to login: {
  "ReturnUrl": "https://***REMOVED***",
  "ClientId": null,
  "IdP": null,
  "Tenant": null,
  "LoginHint": null,
  "DisplayMode": null,
  "UiLocales": null,
  "AcrValues": [],
  "Created": 635695803484346155
}

Does anyone familiar with Azure ACS know how I pass the clientId in? Or, can I set up IdentityServer to provide a set of default claims that include things like the first and last name?

Sorry for being a n00b!

**Comment by brockallen** [comment]
I don't follow -- so your app trusts ACS, and ACS trusts IdSvr? So you're not getting the right claims back to ACS or to IdSvr?

**Comment by locutus80** [comment]
Hi sorry for the delay in replying: the problem is that ACS is not getting claims from IdSvr.

I have a script that writes out the claims that come back from IdSvr and the only ones I get are:

http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier	
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress	
http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider	
http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod
http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant

**Comment by brockallen** [comment]
You'd need to configure IdSvr to issue claims to ACS, and configure ACS to pass them thru.

**Comment by leastprivilege** [comment]
sorted?
