### ISSUE TITLE
Testing Guidance (Postman)

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/IdentityServer3#1479]
Prior to moving to an OpenID Connect based authentication mechanism I used Postman extensively for testing. We leverage the Chrome desktop app and use Jetpacks which enables test builder/runners, etc...

The resource owner flow is an non issue and can be easy wired up but all of our MVC solutions use the hybrid flow as used in many of the samples. While this works great and could be used with UI testing frameworks, often I need to test the access token obtained through the hybrid flow for a subsequent call into a resource server that the MVC app leverages. 

While a bit off topic for identity server itself, has anyone successfully gotten this to work? I have a custom view service and as a result I have access to the input text boxes for the username and password fields and could hook into them to pass in test credentials but before I go down this road I was wondering what others have done in the past to support automated testing of API's protected by identity server.

**Comment by brockallen** [comment]
I always just build a command line app to get an access token and then paste it into the tool (such as postman).

**Comment by jlegan** [comment]
Pardon my ignorance but how are you scraping the user input fields and authenticating in the UI (i.e. consent screens)?

**Comment by brockallen** [comment]
I either hard code credentials into the console app (and do RO flow) or I do a popup like the WCF sample (implicit).

**Comment by jlegan** [comment]
Thanks Brock, that was what I was afraid of (and already had working). I was hoping there was a cleaner solution. I wired up the Postman Jetpack to perform mass token generation, token refreshes and API calls with the tokens. I think we will end up writing our own testing framework and leverage a runner like NUnit in the long run. Thank you for your input.
