### ISSUE TITLE
Registration support for open generics

### ISSUE THREAD

**Issue by vossad01** [IdentityServer/IdentityServer3#1480]
Has any thought been given to adding support for registering/resolving open generics?

I am working at trying to write a custom user service as suggested in IdentityServer/IdentityServer3.AspNetIdentity#34 using 'IdentityServer/IdentityServer3.AspNetIdentity
' and 'aspnet/Identity' as references.

I am currently trying to adapt the factory registrations,

    factory.UserService = new Registration<IUserService, UserService>();
    factory.Register(new Registration<UserManager>());
    factory.Register(new Registration<UserStore>());
    factory.Register(new Registration<Context>(resolver => new Context(connString)));

I find resolution fails because many ASP.NET Identity types cannot be found.  These are typically Dependency Injected and there are extension methods on `IServiceCollection` to add them (ex. AddIdentity<>).

To remedy this, I first thought to add the missing registrations to Thinktecture's DI, much like the various other DI integrations existing for MS's new framework.  I wrote a bunch of Expression tree code to call the generic-only register method with types only known as runtime.  However, I do not see a way to register the open generic types that are registered such as `OptionsManager<>` and `IOption<>`.

This seems to have created a dead-end for that attempt.  My next attempt will be to try to register everything I need against a different container and then just register creation `Func`s with IdentityServer.

**Comment by brockallen** [comment]
I'm not following. 

As for the comment about the types not being found: Doesn't the hosting app where you do the above registration reference the types/assemblies that you're registering? Or am I misunderstanding?

As for the 'open generics' comment (which I don't understand the term): Does `new Registration<IOptions<Foo>>(instance)` not work?

**Comment by brockallen** [comment]
It sounds like you're doing ASP.NET 5 -- is that right?

**Comment by vossad01** [comment]
Yep, ASP.NET 5.

The types being registered are referenced, however those types may need a lengthy number of dependencies registered in order to resolve.  These are dependencies that are often defined and implemented in the ASP.NET libraries and not implementations provided by the user/developer.

To register the default dependencies, something like the following is used: 

    IServiceCollection services = ...

    services.AddIdentity<CustomUser, CustomRole>();
                 .AddEntityFrameworkStores<Context>()
                 .AddDefaultTokenProviders();

where of those `Add*` methods are provided by ASP.NET and EntityFramework.

To integrate these registrations with Thinktecture, I have written code that looks at the `ServiceDescriptor`s in the `IServiceCollection` and adds the appropriate registrations to the `IdentityServerServiceFactory`.  

The issue I have encountered that that some of the registered types are open generic types, and I do not see how they can be registered with with the `IdentityServerServiceFactory`

Open generic types are generic types where the type parameters have not been registered.  The registration is only `IOption<>`, not `IOption<Foo>`

**Comment by brockallen** [comment]
Ok, so this really sounds unrelated to the fact you're using ASP5. Really, it's just that it's a different DI container. So search the archives -- not going to rehash it all here, but the short answer is that you'll need to set up 2 diff DI systems (or if you can have one implemented in terms of the other as you mentioned assuming the dependencies are acyclic across the two systems).

**Comment by vossad01** [comment]
I find the open generics issue as blocking* with respect to integrating with `Microsoft.Framework.DependencyInjection` which is utilized by ASP.NET 5 components and presumable other MS offerings in the future.  What I am doing amounts to registering dependencies in the same spirit as with the advice in the "Injecting custom services" section [in the documentation](http://identityserver.github.io/Documentation/docs/advanced/di.html).  I just have no control over what dependencies are being registered.

It sounds like what I was to attempt next -- handling everything through a different container and registering `Func`s -- should work based on what I am reading in the archives.

I think it is worth considering whether IdentityServer wants to interop with `Microsoft.Framework.DependencyInjection`.  If not, the `Func `-based registration will be required for ASP.NET Identity 3 and EntityFramework 7 integration.  In this case it, would seem the use of the other registration methods would become marginalized, but perhaps they already do in realistically sized applications (mine is still young).

 \* I did find I can work around the limitation by registering all of the closed generic types (ex. `IOptions<IdentityOptions>`) that are needed, but this not strictly easy to determine what these are.  This also makes the application dependent on an implementation detail that it should not need to worry about and which could be subject to change.

**Comment by brockallen** [comment]
Yea, not sure. Obviously ASPNET5 wasn't around when we did our design. Also, given how it will likely be changing in the coming months, we've deliberately not spent spent any timing trying to interop with it (other than a sample: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNet5Host). As it matures, we'll revisit this. But for now, I'll close this given that you have a workaround.

**Comment by vossad01** [comment]
Workaround code sample for sake of completeness for future readers:

```
IServiceCollection services = new ServiceCollection();

services.AddIdentity<PersistedUser, IdentityUserRole>();
// ... More registrations
services.Add(
    new ServiceDescriptor(
        typeof(IUserService),
        typeof(AspNetIdentityUserService<PersistedUser>),
        ServiceLifetime.Scoped));
// ... More registrations
IServiceProvider serviceProvider =  services.BuildServiceProvider();

factory.UserService =
    new Registration<IUserService>(
        ignored => serviceProvider.GetRequiredService<IUserService>() );
factory.Register(
    new Registration<UserManager<CustomUser>>(
        ignored => serviceProvider.GetRequiredService<UserManager<CustomUser>>() ) );
factory.Register(
    new Registration<IUserStore<CustomUser>>(
        ignored => serviceProvider.GetRequiredService<IUserStore<CustomUser>>() ) );
factory.Register(
    new Registration<DbContext>( ignored => serviceProvider.GetRequiredService<DbContext>() ) );
```
Depending on where you are putting this you may not be creating your own `ServiceCollection` or `IServiceProvider` but rather using those that have been injected.

Realistically, you could use any DI interface rather than `IServiceProvider`, but call the appropriate methods on whatever you use.  I am only showing pure `Framework.DependencyInjection` above for simplicity.  Everything being resolved need to be registered.

**Comment by huysentruitw** [comment]
I think you're code has a problem, because you're requesting all dependencies from the same container. I don't think the lifetime management can work this way.

I'm using Autofac registered at OWIN and I created an extension method to get the dependencies from the lifetimescope:

```C#
public static T ResolveFromAutofacOwinLifetimeScope<T>(this IDependencyResolver resolver)
{
    var owin = resolver.Resolve<OwinEnvironmentService>();
    var context = new OwinContext(owin.Environment);
    var scope = context.GetAutofacLifetimeScope();
    return scope.Resolve<T>();
}
```

And use it like:

```C#
factory.UserService = new Registration<IUserService>(dr => dr.ResolveFromAutofacOwinLifetimeScope<UserService>()),
```

The other advantage is that you don't have to register all your other types twice.

**Comment by vossad01** [comment]
@huysentruitw Thank you so much for pointing that out!  I am sure it would have caused an issue after running long enough.  My setup was a little different than I posted because I am using Autofac Modules, but the problem you pointed out still existed.  That also explains why I had to work around the `CancellationToken` from the `HttpContext` always being disposed.

I am using `Autofac.Dnx` so and not have `context.GetAutofacLifetimeScope()` available.  However, you did lead me to a solution.  This should work with any DI container:

```
private class ResolveFromAspNetContextRegistration<T> : Registration<T>
    where T : class
{
    public ResolveFromAspNetContextRegistration( string name = null )
        : base( GetServiceFromContext<T>, name )
    {
    }

    private static TService GetServiceFromContext<TService>( IDependencyResolver resolver )
    {
        var owin = resolver.Resolve<OwinEnvironmentService>();
        HttpContext httpContext = (HttpContext)owin.Environment["Microsoft.AspNet.Http.HttpContext"];
        var serviceProvider = httpContext.RequestServices;
        return serviceProvider.GetRequiredService<TService>();
    }
}
```

Usage is:
```
factory.UserService = new ResolveFromAspNetContextRegistration<IUserService>();
```
