### ISSUE TITLE
Oauth configuration with 3rd party oauth provider

### ISSUE THREAD

**Issue by shaneprice** [IdentityServer/IdentityServer3#1481]
I have read through the documentation and have been playing around with the samples.

I am trying to build an asp.net5 application that allows me to connect with a 3rd party (BigCommerce) oauth implementation
I have created a new vnext site with the nuget package ( "Thinktecture.IdentityServer3": "1.5.0") and have used the vnext example IdentityServer code and have it running locally without the bigcommerce bits.

My confusion lies around where in my project is the correct place to be wiring up the extra details. 

Is this a considered a new Client? I am just a little confused where I should be trying to configure this.

From their documentation the first get request made by their server looks like 
GET http://mydomain.com/core/connect/authorize?code=qr6h3thvbvag2ffq&scope=store_v2_orders&context=stores/g5cd38

I have setup a new client for bigcommerce

    var client = new Client
                {
                    ClientName = "Big Commerce",
                    Enabled = true,
                    ClientId = "ClientIDFromBigCommerce",
                    Flow = Flows.AuthorizationCode,//TODO: find out
                    RequireConsent = true,
                    RedirectUris = new List<string>()
                    {
                        "https://store-123.mybigcommerce.com"
                    },
                    ScopeRestrictions = new List<string>()
                    {
                        "store_v2_marketing",
                        "store_v2_customers",
                        "store_v2_orders",
                        "store_v2_products"
                    },
                    ClientSecrets = new List<ClientSecret>()
                    {
                        new ClientSecret("SecretFromBigCommerce")
                    },
                    },
 

When I try testing I get an error The client application made an invalid request. Its deployed on azure so I need to work on getting the logging component working so thats all the details I have regarding the error at the moment.

Or is this a case for me to be using a Custom Grant and use something similar to https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Custom%20Grants

My apologizes if I have overlooked something obviously in the documentation that explains what I am trying to do.

**Comment by brockallen** [comment]
IdentityServer is a token service for clients (your apps or other apps you're integrating with).

It sounds like you want to obtain a token for a 3rd party API (from a 3rd party OAuth2 AS) then that's different. 

How do you envision this 3rd party and IdentityServer integrating? Do you want the 3rd party to use IdentityServer for the user's authentication? 

These are the sorts of questions that need to be answered.

**Comment by shaneprice** [comment]
Right....thanks Brock for your prompt response. Ok so this might be more of me not understanding completely what IS should be used for.

There are 2 parts to users authentication withinmy integration with this 3rd party. 
**Businesses**
**Business Customers**

* A business needs to grant me permission from the 3rd parties application 
*  Once the business has granted me permission - The 3rd party application does a httpget to my identity server to the Auth Callback URI, via http://mydomain.com/core/connect/authorize?code=SOMECODE&scope=store_v2_orders&context=stores/SOMESTORE
* I then do an  httppost  https://login.bigcommerce.com/oauth2/token

```
POST /oauth2/token HTTP/1.1
Host: login.bigcommerce.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 186

client_id=236754&client_secret=m1ng83993rsq3yxg&code=qr6h3thvbvag2ffq&scope=store_v2_orders&grant_type=authorization_code&redirect_uri=https://app.example.com/oauth&context=stores/g5cd38
```
 * I get the response
```
{
  "access_token": "g3y3ab5cctiu0edpy9n8gzl0p25og9u",
  "scope": "store_v2_orders",
  "user": {
    "id": 24654,
    "email": "merchant@mybigcommerce.com"
  },
  "context": "stores/g5cd38"
}
```
* I take the details from the post response and insert into identity server?
* I then query their api and insert customers to my db generating an account and token
* A newly added user will be now able to log into my system.


My end goal is I need to be able to store the business details and also the business customers details within my application. Allowing for both the business and customers access to be able to login and use features of my application. 

Am I trying to use Identity Server for both the business and customer components where really it was only designed for the customer component of what I am trying to do?

**Comment by brockallen** [comment]
Sounds like you have an API you're trying to protect and you're using IdSvr to protect it. The access token returned to the app is then used to authenticate the call to the API.

Given that you seems a bit unsure on it all, I'd suggest you spend some time in our docs and doing the walk-thrus: https://identityserver.github.io/Documentation/docs/

**Comment by shaneprice** [comment]
Thanks I will continue to study them.

I think a long story short is the business component is really a custom OWIN OAuth Provider.

Looking at the Middleware for external Authentication > Other community contributions I think thats the approach I need to take.

Thanks for your time I really appreciate it!
