### ISSUE TITLE
Is there any way to call GetUserInfo() while creating claims principal 

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1482]
Currently our access token is kept small for a reason. We using AccessTokenValidation API in RestAPI which creates claims principal during this time we would like to call GetUserInfo api. Also these should be cached too. Do you suggest is to use cached token end point for this?

**Comment by skatukojwala** [comment]
We are currently using local validation.

**Comment by brockallen** [comment]
You can build a map of token to claims.
