### ISSUE TITLE
Should we create a vNext project?

### ISSUE THREAD

**Issue by Zenuka** [IdentityServer/IdentityServer3#1483]
We are starting our implementation of IdentityServer3 next week but should we already start with a vNext Project? If so, do you have any tips?

**Comment by leastprivilege** [comment]
Why do you want to host IdSrv in ASP.NET 5 - it is a self-contained server.

You can of course - and be prepared for untested edge cases.

**Comment by Zenuka** [comment]
We're going to run IdSrv in Azure as a website and we'll want some form of customization and extra's on top of IdSrv so we were going to add the nuget package in a ASP.NET project. I thought it might be a good idea to keep up with the new stuff and start with a vNext project. Are you expecting a lot of edge cases/issues? Or is it more like: "It should work fine..." :-)

**Comment by leastprivilege** [comment]
It is mostly like “ASP.NET 5 is still in beta, why would I use it for security sensitive stuff”. Especially in the case where you gain zero extra features.

— 
cheers
Dominick Baier


On 12 Jun 2015 at 09:01:56, Zenuka (notifications@github.com) wrote:

We're going to run IdSrv in Azure as a website and we'll want some form of customization and extra's on top of IdSrv so we were going to add the nuget package in a ASP.NET project. I thought it might be a good idea to keep up with the new stuff and start with a vNext project. Are you expecting a lot of edge cases/issues? Or is it more like: "It should work fine..." :-)
