### ISSUE TITLE
Server and API security, not sure if I got this right

### ISSUE THREAD

**Issue by depl0y** [IdentityServer/IdentityServer3#1489]
We set up an IdentityServer for a product of ours (Implicit flow). Logging in works correctly and on the product we have access to all the right information (claims).

But we would like to set up an API with a separate ClientId and Secret, to make sure the API can also stand on it's own. When a user logs in into our product, we want to call the API and let the API fetch claims for the user, for example to fetch a `Role`.

But I am not sure how to set this up. The call to the API is being done with the `OAuth2Client`, with a specified ClientID and Secret, but what do I need to get the users claims at the API.

I probably have to do a call from within my API to the IdSrv, with the current acccess token of the user? 

The more I think about it, the more I get lost at the moment. 

EDIT:
It's probably related to this issue, but I would love to see a short implementation example for this.

https://github.com/IdentityServer/IdentityServer3/issues/1410

**Comment by frankaxela** [comment]
My idea is that you need to hit the userinfo endpoint in the identity server using the access token received from the client, make sure that when you request the access token, you include the role scope as scope requested.

This is the way to add the role scope to your scopes:
http://identityserver.github.io/Documentation/docs/configuration/scopesAndClaims.html

**Comment by brockallen** [comment]
APIs don't have client ids or secrets -- clients do. So I think what you are saying is that when a user logs into your client app you want that server side code to access the user's identity information? This can be done by accessing the info in the id_token or by using an access_token to access the user profile endpoint. Which one you do depends on your scope claim configuration and/or the response_type request param from the client. So in short, either combo is possible.
