### ISSUE TITLE
It will be Thinktecture.IdentitiyModel namespaces renamed?

### ISSUE THREAD

**Issue by Condor2708** [IdentityServer/IdentityServer3#1490]
I want to know if the following packages will be renamed when the new Identity Server v3 2.0.0 will be released.
Thinktecture.IdentityModel.Core
Thinktecture.IdentityModel.Owin.ResourceAuthorization
Thinktecture.IdentityModel.Owin.ResourceAuthorization.WebAp

Thanks

**Comment by brockallen** [comment]
You're asking in the wrong repo, but the answer is 'yes eventually'.
