### ISSUE TITLE
How to setup different roles per application

### ISSUE THREAD

**Issue by curlyfro** [IdentityServer/IdentityServer3#1491]
we plan on using IdentityServer for our single sign on.  we have multiple applications with users having different roles per application.  it's not clear to me.  how do we set this up?

**Comment by jawadatgithub** [comment]
Did you run/test/play with the samples? your case should be straight forward after reading docs and play with samples.

**Comment by brockallen** [comment]
In 2.0.0 we include the client id in the call to get profile on the user service. You'd do your conditional roles in there.

**Comment by leastprivilege** [comment]
for 1.x you can achieve the same by deriving from DefaultClaimsProvider.
