### ISSUE TITLE
How to switch users while developing?

### ISSUE THREAD

**Issue by curlyfro** [IdentityServer/IdentityServer3#1492]
we need the ability to switch users from our client interface while we're in debugging mode. is there an easy way to do this? how do we do this with identity server?

**Comment by jawadatgithub** [comment]
why not simply log off UserA then log on with UserB?

**Comment by Jogai** [comment]
Use Stuntman from @khalidabuhakmeh. Available on nuget, intro blog: http://www.khalidabuhakmeh.com/use-stuntman-for-development-authentication-in-owin

**Comment by khalidabuhakmeh** [comment]
I agree, I hear good things about stuntman :)

We also just added the ability to use bearer tokens while in development so you can test APIs as well.

**Comment by curlyfro** [comment]
stuntman is perfect.  thanks :)
