### ISSUE TITLE
Is a good practice to save identity token in a cookie?

### ISSUE THREAD

**Issue by feina** [IdentityServer/IdentityServer3#1493]
In order to log out a user properly I must keep de identity token somewhere.
Is it a good practice to keep it in a cookie?
Thanks

**Comment by jawadatgithub** [comment]
If you are building SPA, then why you don't set it in Global var or use browser local storage?
if you are building classing web app (e.g., web forms) you could set it in hidden input field in master page.
by default cookie will be sent in every request! which is not good practice for identity token. identity token designed to remain in client (e.g., browser) except for auto logout feature.

**Comment by brockallen** [comment]
If you're doing server side code (like MVC) then sure. If you're doing client side only (like JS) then a variable would work.

**Comment by feina** [comment]
Thanks all
