### ISSUE TITLE
Best way to check if there is an active identity server session

### ISSUE THREAD

**Issue by feina** [IdentityServer/IdentityServer3#1494]
After a user accesses my site I need to check whether the user has an active identity server session.
If the user hasn't got an active session, the site will display normally, otherwise personalized options will appear.

I'd like this check to be performed in a seamless way, perhaps through javascript.
Which is the best way to do this?
Thanks

**Comment by brockallen** [comment]
IdentityServer supports the check session endpoint -- check the session management spec, our docs, and our samples.

**Comment by feina** [comment]
Is there any way to perform this check without using Javascript? For example using only redirects?

**Comment by brockallen** [comment]
You can make a request to the authorization endpoint where you do a prompt=none and check the response.
