### ISSUE TITLE
How To get  All Claims on Client 

### ISSUE THREAD

**Issue by moiseyo** [IdentityServer/IdentityServer3#1495]
Using EULA sample   I created server 

I passed  a few  claims 
 Claims = new List<Claim> {
                            new Claim(Constants.ClaimTypes.Name, model.Username + " " + model.ClientId),
                            new Claim(Constants.ClaimTypes.GivenName, model.Username),
                            new Claim(Constants.ClaimTypes.FamilyName, model.ClientId),
                            new Claim("ClientId", model.ClientId),
                            new Claim(ClaimTypes.Name, UserName)
                            , new Claim(ClaimTypes.Country, "USA")
                            , new Claim(ClaimTypes.Gender, "M")
                            , new Claim(ClaimTypes.Surname, CurrentUser.LastName)
                            , new Claim(ClaimTypes.Email,CurrentUser.EmailAddress )
                            , new Claim(ClaimTypes.Sid,model.ClientId)
                            , new Claim(ClaimTypes.Role,CurrentUser.Assig

and on Client I see only  name, given_name , and  family_name 

Client Scope 

 Scope = "openid email profile read write offline_access",

Server Scope 
  public static IEnumerable<Scope> Get()
        {
            return new[]
                {
                    StandardScopes.OpenId,
                    StandardScopes.Profile,
                    StandardScopes.Email,
                    StandardScopes.OfflineAccess,
                    StandardScopes.AllClaims,

                    new Scope
                    {
                        Name = "read",
                        DisplayName = "Read data",
                        Type = ScopeType.Resource,
                        Emphasize = false,
                        Claims = new List<ScopeClaim>
    {
        new ScopeClaim(Constants.ClaimTypes.Name),
        new ScopeClaim(Constants.ClaimTypes.Role)
    }
                    },
                    new Scope
                    {
                        Name = "write",
                        DisplayName = "Write data",
                        Type = ScopeType.Resource,
                        Emphasize = true,
                        Claims = new List<ScopeClaim>
    {
        new ScopeClaim(Constants.ClaimTypes.Name),
        new ScopeClaim(Constants.ClaimTypes.Role)
    }
                    }
                };
        }

What do I miss ?

Thank you 

![untitled](https://cloud.githubusercontent.com/assets/5314730/8171366/600a7f64-1385-11e5-8a94-a32a8dbd6c49.png)

**Comment by brockallen** [comment]
You use scopes to indicate what identity data you want. Sounds like you want a custom scope where you set 'include all claims for the user'. See the docs for more into.
