### ISSUE TITLE
Support for SSL offloading

### ISSUE THREAD

**Issue by iguanaware** [IdentityServer/IdentityServer3#1496]
refs #1391 

Rewriting the location after post back when SSL is off-Loaded (offloading) (reverse proxy)

I wanted to use a URL Re-Write rule, but had some trouble getting it to work.  So I turned to the pipeline to rewrite the location on 302 from the post after log in.

This is a little "hack" until a better solution comes along.

The if statements filter out other requests as best observed from fiddler.  Otherwise you could miss the one you need to rewrite and possible change redirects to other web sites.

__*Original code has been removed, see final version below*__

**Comment by brockallen** [comment]
We already support a `PublicOrigin` setting -- does that not do what you want?

Also, we're OWIN middleware, so a http module is the wrong approach for this.

**Comment by iguanaware** [comment]
I think it has nothing to do with IdentityServer.  I think the code in Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler
builds the secured resource path and stores it in state.  Then after the form post it redirects back to the secured resource (line 544)  using the http scheme not https. (line 42)

I'm going to clean up my fix for OWIN and post it.

**Comment by brockallen** [comment]
Right -- it uses whatever scheme is being used to request the client app. In short, change your client app to use SSL.

**Comment by iguanaware** [comment]
Thanks Brock!  Here is a much simpler work around.

startup.cs 
Code must be before UseOpenIdConnectAuthentication

```cs
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
         ...
            app.Use(async (Context, next) =>
            {
                if (Context.Request.Headers["X-ARR-SSL"] != null)
                {
                    Context.Request.Scheme = "https";
                }
            });
         ...
```

**Comment by brockallen** [comment]
Ok, as long as you trust your network there since you have tokens being sent around over plaintext.

**Comment by sevedubois** [comment]
I have the same problem! 

I implemented the standard Microsoft.Owin.Security.OpenIdConnect in Visual Studio 2015. It works perfectly when I test it locally, but when I deploy it to the server (SSL is off-Loaded), then I get bad request.

I have tried the above solution, added app.Use(...) before the app.UseOpenIdConnectAuthentication(...), but then I get a empty page when I run it localy as well as on the server. It even doesn't try to connect to microsoftonline anymore.

What am I doing wrong?

Here is my code of StatupAuth.cs:
`

    public partial class Startup
        {
        private static string clientId = ConfigurationManager.AppSettings["ida:ClientId"];
        private static string appKey = ConfigurationManager.AppSettings["ida:ClientSecret"];
        private static string aadInstance = ConfigurationManager.AppSettings["ida:AADInstance"];
        private static string tenantId = ConfigurationManager.AppSettings["ida:TenantId"];
        private static string postLogoutRedirectUri = ConfigurationManager.AppSettings["ida:PostLogoutRedirectUri"];

        private string authority = aadInstance + tenantId;
        // This is the resource ID of the AAD Graph API.  We'll need this to request a token to call the Graph API.
        private static string graphResourceId = "https://graph.windows.net";

        public void ConfigureAuth(IAppBuilder app)
            {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            app.UseCookieAuthentication(new CookieAuthenticationOptions());

            app.Use(async (Context, next) =>
            {
                if (Context.Request.Headers["X-ARR-SSL"] != null)
                    {
                    Context.Request.Scheme = "https";
                    }
            });

            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                    {
                    ClientId = clientId,
                    Authority = authority,
                    PostLogoutRedirectUri = postLogoutRedirectUri,
                    Notifications = new OpenIdConnectAuthenticationNotifications()
                        {
                        //
                        // If there is a code in the OpenID Connect response, redeem it for an access token and refresh token, and store those away.
                        //
                        AuthorizationCodeReceived = (context) =>
                        {
                            var code = context.Code;
                            ClientCredential credential = new ClientCredential(clientId, appKey);
                            string signedInUserID = context.AuthenticationTicket.Identity.FindFirst(ClaimTypes.NameIdentifier).Value;
                            AuthenticationContext authContext = new AuthenticationContext(authority, new ADALTokenCache(signedInUserID));
                            AuthenticationResult result = authContext.AcquireTokenByAuthorizationCode(
                            code, new Uri(HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Path)), credential, graphResourceId);
                            return Task.FromResult(0);
                        }
                        }
                    }
                );

            // This makes any middleware defined above this line run before the Authorization rule is applied in web.config
            app.UseStageMarker(PipelineStage.Authenticate);
            }
        }
`
