### ISSUE TITLE
Does ICustomRequestValidator override anything? Or just add to the pipeline?

### ISSUE THREAD

**Issue by ravisakaria** [IdentityServer/IdentityServer3#1498]
1. If I implement `ICustomRequestValidator` do I have to call some built-in method from within the `ValidateAuthorizeRequestAsync` method to avoid overriding any standard behavior?  Or does `ICustomRequestValidator` get called after the built-in logic.

2. On another note, I set a breakpoint in the `ValidateTokenRequestAsync` method, but it never gets hit.  Any idea why that would be?

3. While I'm on the topic of the custom request validator, how can I access the user's profile/claims from within these methods?

Thanks

**Comment by brockallen** [comment]
1. You register your custom implementation with the DI system.
2. Not sure.
3. The request validation (including the custom request validator) is designed to validate if the request is valid independent of the user. It's possible that the user has not yet authenticated during request validation. Can you explain what you're trying to do?
