### ISSUE TITLE
difference between endsession and logout endpoints

### ISSUE THREAD

**Issue by devblaz** [IdentityServer/IdentityServer3#1499]
There are now 2 endpoints that seem to behave the same. What is the difference between /core/connect/endsession and /core/logout?
Thanks

**Comment by jawadatgithub** [comment]
its only one endpoint, endsession is the endpoint to logout user, /core/logout? is not an endpoint. the logic required to end user session uses logout term in the code, there is html asset/resource called logout but as classes only LogoutDetails...

hope its clear.

**Comment by devblaz** [comment]
Thanks. But both url's can be called. See also Constants.RoutePaths where you can find "logout" and "connect/endsession". The last one is probably from the OpenID Connect specs. They seem to have seperate reasons to exist?

**Comment by brockallen** [comment]
The end session endpoint is defined by the OIDC session management spec. The logout page is simply our UI if the user wants to logout. The former is implemented in terms of the latter. They each do slightly different things.

**Comment by devblaz** [comment]
Thanks
