### ISSUE TITLE
question about AuthenticationController logout method

### ISSUE THREAD

**Issue by devblaz** [IdentityServer/IdentityServer3#1500]
In AuthenticationController.cs i see
"public async Task<IHttpActionResult> Logout(string id = null)"

What is the purpose of the id parameter?
The parameter is not documented but is necessary in RenderLoggedOutPage because there i find:
    var message = signOutMessageCookie.Read(id);
    var redirectUrl = message != null ? message.ReturnUrl : null;

I am trying to get the post_logout_redirect working, but it doesn't work and during debugging i seem to get stock here. The redirectUrl is not filled now and when i manually during debugging put some url in this variable the redirect works.
Any help would be appreciated.

**Comment by leastprivilege** [comment]
Do you send the id_token_hint?

https://identityserver.github.io/Documentation/docs/endpoints/endSession.html

**Comment by devblaz** [comment]
Yes i do.
proof: http://localhost:3333/core/logout?id=test&post_logout_redirect_uri=http:%2f%2fwww.nu.nl&id_token_hint=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1...<snip>...Gzk85oYt-KeS4Nb8sfmuzEX-4g97vRxH8w

In method RenderLoggedOutPage i now receive the value "test" because i added id=test in the querystring. And while debugging and changing the value of LoggedOutViewModel.RedirectUrl to an appropriate value i finally get redirected. But ofcourse something is going wrong but i don't know what.

**Comment by brockallen** [comment]
You're going to the wrong URL to signout -- you need to use the end session endpoint:

~/core/connect/endsession
