### ISSUE TITLE
Custom login page

### ISSUE THREAD

**Issue by usernameAlreadyTakenByMe** [IdentityServer/IdentityServer3#1501]
Hi I am working on customUserService sample from samples page.
I'm trying to do a custom login page with a slightly different view depending on clientId and then do a partial login with customuserservice. I'm stuck at either doing a custom html page where i dont know how to pass parameters to site in order to change the layout or change PreAuthenticateAsync method to gain control over authentication process by using async tasks to redirect to newly created login action and view in which i can't redirect to my own actions.

So the question is: how the custom login page and custom authentication process should be done. 
Thanks in advance for any clues.

**Comment by brockallen** [comment]
Sounds like doing the custom view is the right thing. You can include additional params in the `<form>` and then in your user service you can look for those (by injecting the owin environment service and reading the custom POST values). One of our samples does something like this, IIRC.

**Comment by usernameAlreadyTakenByMe** [comment]
There is one more thing: How can i handle multiple language on custom login page? I will have to render custom login, logout and so on pages with client's application language.

**Comment by brockallen** [comment]
That's what a custom view is for.
