### ISSUE TITLE
Why does ClaimsProvider expect a ClaimsPrincipal to have already been produced?

### ISSUE THREAD

**Issue by kalanbates** [IdentityServer/IdentityServer3#1502]
I am working on some custom touches for an Identity Provider based on IdS, IdM, and MembershipReboot.  I was walking through the "Custom Grants (more customization)" sample and noticed that [IClaimsProvider] expects a ClaimsPrincipal to have already been generated to be passed into GetAccessTokenClaimsAsync.

Seeing this introduced confusion into my task.  I have been operating under the assumption that the IdentityServer is generating a JWT (and only a jwt) and my Resource servers are responsible for converting that jwt into whatever representation of the principal that those servers' platforms require.  

Looking back into some of my notes when I was working from the Thinktecture.IdentityServer3 Beta source, I understood "then" that we were working with a ClaimsPrincipal on the STS, but -6 months later- now that I'm revisiting this implementation, my expectations and thought processes have changed a bit.  Now I'm curious to understand more about IClaimsProvider and the processing model that you have conceptualized.  

• Why is a ClaimsPrincipal being worked with here? 
• Where in the processing pipeline of IdentityServer is it expected to be created? 
• Since a ClaimsPrincipal is expected to already be produced, what is the purpose of `IClaimsProvider`? 
• Why does GetAccessTokenClaimsAsync not have an overload that accepts a System.IdentityModel.Tokens.Jwt?

Some design insight and guidance would be greatly appreciated

**Comment by kalanbates** [comment]
Oh...wait. Am I simply looking at the wrong extension point?  If I'm wanting to use MembershipReboot, should I instead be going through the `GetClaims(Account account)` method on my customer UserService to get raw claims?

**Comment by brockallen** [comment]
The `IClaimsProvider` is the lower level definition of how to get claims. Our default implementation uses the registered `IUserService` as a higher level abstraction. So one is low level, the other is high level.
