### ISSUE TITLE
Webapp and WebAPI delegate authorization

### ISSUE THREAD

**Issue by vectorderivative** [IdentityServer/IdentityServer3#1503]
I have an API that need security, some methods will be protected from different user roles also the API should be accesed only from authorized clients so I think Identity Server is the way to go.

The question is what would be the logic flow if I'll be accessing the API thru a web app?
The webapp will be asking for a token to IdServer and then send that token to my WebAPI and there I check if it's a valid token, get the authenticated user permissions and grant access to its authorized api methods? and that's it?

I don't know why this just doesn't get clear in my mind is there an example targeting this scenario?

**Comment by brockallen** [comment]
In addition to an id_token, the web app can also request an access_token for calling a back end API. If the web app is already doing that so the JS can call and API, and that API needs to call another API, then you can obtain a delegation token from IdenttyServer via a custom grant validator (which is an extensibility point in IdSvr that you could implement).

**Comment by vectorderivative** [comment]
Thanks, rigth now I don't need an API to call another one.
I managed to implemente a simple implicit flow and everything works just right but I'll need a login form so resource owner is the flow I'm looking for but I'm not having the expected results. I opened an issue.

Thanks again.
