### ISSUE TITLE
Operational data questions

### ISSUE THREAD

**Issue by frankaxela** [IdentityServer/IdentityServer3#1506]
Hi all,

I'm developing the Identity Server and moving to a pre-production environment. I just add the token and consent tables and have few questions about the way they work.

I've noticed that the Token table only stores the refresh token in console apps, in mvc, etc, my question is if the access token got stored in any case as i cannot see them, and how to do that if not

About the consent table, i wanted to know if is possible to store the consent provided, i guess showing the consent page, in a console app, aka ios, android or a non web related client (JS and MVC)

Thank you and congratulations for the awesome work

**Comment by brockallen** [comment]
If you change the access token to a reference token then you will see it in the DB.

I don't follow the second question.

**Comment by frankaxela** [comment]
Yeah, thanks, i figured that out, what i'm doing now is requesting for the access token and the refresh token and also changed the access token type to reference, so the token get stored.

About the second question, basically what i wanted to do is store the consent from any client who's requesting access to the API without showing the consent screen. So just providing the user credentials, the client & user doing the request are stored.
Is there any way to do this? or should i create a new service for that?
BTW, in case you're concern about me not showing the consent screen, i've added the list of data to use in the login screen, so when the user clicks login, she already knows about the data usage.

**Comment by brockallen** [comment]
I'm still not clear -- we have a setting on the Client where you can configure that consent is not required. But if that's set (so no consent is shown) we don't store that anywhere -- mainly because it doesn't make sense because the user really hasn't provided consent. 

Does that help any?

**Comment by frankaxela** [comment]
Yeah, but not 100% (i feel like im being a real pain in the ass)
The idea is to show to the user the clients that are allowed by the user to access the API, and that is done consulting the Consent table.
Now, to provide easy usage to the users, I want not to show the consent screen, and inform of the data accessed in the login screen, being an acceptance to use the data when the user logs in.
In this case the consent table should be updated with the client the user just logged in through, if not in the table before.
Then the user can consult which clients are allowed to access her data, and revoke permission, just like in your Implicit Client.

I know this is a round about to the meaning of the consents, but this is how has being designed, and couldn't do anything to change it.

**Comment by brockallen** [comment]
So you want to give the user a way to see all clients that have access to some APIs on the user's behalf? Ok, I understand that. If I were to design it, then I'd have this UI load the data from both the consent tables and the client tables (for the clients that have RequireConsent=false).

As for being able to revoke consent for the clients that have RequireConsent=false, we don't support that.

**Comment by frankaxela** [comment]
Yes, thats basically what i want to do.
The issue is how do i store consents if I'm not showing the consent screen?? I've bypass that step for usability purposes, I know is not ideal and doesn't match the OAuth 2.0, but is the way we want to do that, I guess i should code it the way i find better.

**Comment by brockallen** [comment]
You can always build your own consent store and design the semantics you want. 

One concern I'd raise -- is the client 3rd party to the OpenID Connect Server and the APIs? IOW, the reason to show consent is to give the end user control over what they're allowing the client to know about them or do on their behalf. If you automatically grant consent then the user does not have control of this and it's not a nice thing to do to the user. If, on the other hand, the client is not 3rd party then it's not the user's choice and thus revoking a previously automatic consent is odd.

Also, I guess I should have asked this at the beginning -- what are you trying to do (not how)? Are you trying to allow your users to revoke tokens in case their client (computer, tablet, phone) has been lost or compromised? That's a different thing than revoking consent. So maybe we're discussing the wrong solution.

**Comment by frankaxela** [comment]
Well, the Authorization Server is made to allow access to 3rd party clients (like an iOS, Android, script for CRM, ...), these clients would be shown in the permissions page and the access can be revoked, and also the proprietary client, which won't be stored in the consent table.

Yeah, that's what im starting to think, that maybe I will do the request to show the tokens active, the refresh token as it has a longer lifetime, and don't think in terms of consent as the authorization request is not to show the consent screen.
Then if a user wants to revoke the client access, i will remove the valid access and refresh tokens stored

**Comment by frankaxela** [comment]
I've check the token possibility and looks like the way to go

Thanks for you help Brock
