### ISSUE TITLE
Logging out when the browser cookie has expired results in being logged back in

### ISSUE THREAD

**Issue by RobRolls** [IdentityServer/IdentityServer3#1508]
We have a web forms app where we initiate a logout with the following code

```
HttpContext.Current.GetOwinContext().Authentication.SignOut(
                    new AuthenticationProperties {  },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
```

The problem I am having occurs when I've set the timeout for a particular client to be something short, lets say 5 minutes.  Meanwhile the cookie on the idsvr has a lifespan of 10 minutes.

When I click the Logout on our app and I have not timed out yet the above code is called and I see the following calls in fiddler

`GET /identity/connect/endsession?id_token_hint=eyJ0eXAiOiJKV1QiLCJhbGc...`
`GET /identity/logout?id=fda75eeac051ad50074a...`

I then see the authorize request and I am taken to the login screen.

But when I click on the logout link after more than the 5 minute timeout I still hit the `GetOwinContext().Authentication.SignOut(...)` method but now the only call I see in fiddler is the authorize call.  The endsession and logout calls never happen.  This makes sense since I am no longer authenticated.  Unfortunately, as soon as it gets to the idsvr it sees me as still being authenticated (via the cookie there I assume) and redirects me back to the page I clicked logout from and I am again authenticated.

I expect I have something misconfigured.  Any thoughts on this?

**Comment by brockallen** [comment]
I'm not exactly following the workflow, but it sounds like perhaps on the app side since you're no longer logged (due to inactivity and the cookie timing out) in that it's skipping the call to IdSvr to logout -- is that what you're saying?

**Comment by RobRolls** [comment]
That's pretty much it.  
The `Request.GetOwinContext()` portion of `Request.GetOwinContext().Authentication.SignOut();` forces a call to the authorize end point.

I ended up working around this by putting the SignOut() code in a separate Logout.aspx page so now the user is redirected to the idsvr, re-authorized, then taken back to the Logout.aspx page, and finally the sign out happens as expected.  You have to be logged in to log out.  Thanks.
