### ISSUE TITLE
Users from database

### ISSUE THREAD

**Issue by usernameAlreadyTakenByMe** [IdentityServer/IdentityServer3#1509]
Hi,
Im currently working on identityserver and i want to populate factory users in startup configuration from already created database. How it should be done in identityserver.

**Comment by usernameAlreadyTakenByMe** [comment]
Or is it better to just query database inside AuthenticateLocalAsync method?

**Comment by huysentruitw** [comment]
Yes, create your own `IUserService` or start from https://github.com/IdentityServer/IdentityServer3.AspNetIdentity/tree/master/source/AspNetIdentityUserService if you're already using AspNet.Identity

**Comment by usernameAlreadyTakenByMe** [comment]
I have done exactly like you told and everything works as expected. Thanks for a good answer.
