### ISSUE TITLE
Where shall I store external logins?

### ISSUE THREAD

**Issue by mahelm** [IdentityServer/IdentityServer3#1510]
Hi,
I want to make an MVC application in which users can register and edit their profile. Thus, this application need some sort of UserService for storing profiles. 
It shall also be possible to use external logins (starting with just Google though).
I have a number of protected actions in the application also which require some custom claims issued by IdentityServer.

I have configured an IdentityServer v3 instance and it is referenced by the MVC appliction using UseOpenIdConnectAuthentication. I use UseGoogleAuthentication to enable google authentication. Anyway, IdentityServer has its IUserService for local users so here is another user store.

Now I am a bit confused....

Q1. Where shall I persist the list of each users IdP-and-UserIdInIdP-pair? Is it in the user profile database used by my MVC application or is it in an implementation of IUserService at the IdP?

Q2. Assuming that it makes sense to handle this relationship in the IUserService. Is there someway for me to create and attach custom claims during the login phase i.e. find wich local user that corresponds to the google user logging in, and then create a token for that local user?

Best regards / Mattias Helmer

**Comment by soliveira** [comment]
Hi you can use Microsoft AspNet Identity EntityFramework: https://www.nuget.org/packages/Microsoft.AspNet.Identity.EntityFramework

This package will help you implement the persistence and claims management for your project.

**Comment by mahelm** [comment]
Hi again, 
thank you for the tip soliveira. I think have a working model of how claims are persisted and associated with users though (see below). Here is an update on my question.

* I have a db with **Users** connected to one or more **Identities** in registered **IdentityProviders** (e.g. Google). It also contains **Roles** which are associated with **Claims**, Each **User** can have one or more **Roles** and that is how the claim-collection is built during login.

* The IdentityServer instance is in a separate VS project. It is configured to accept logins from Google. My IUserService-implementation is built based on the ExternalRegistrationUserService-sample but it uses my db mentioned above to accomplish it's job. 

* I have an MVC application with protected resources. It references the IdentityServer using UseOpenIdConnectAuthentication. No references to Google or other login-providers here - by design. The actions in this project shall be protected based on the claims-collection from my db above. I need som help with this.

Everything works fine except for the fact I end up with the claims from Google in my MVC application. Is it possible to configure this setup so that I end up with my custom claims in the MVC application? How? 

Thanks in advance / Mattias Helmer

**Comment by soliveira** [comment]
Keep in mind that the claims transmitted in the token depend on those that you selected on OpenIdConnectAuthenticationOptions.Scopes:
```
 app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = options.AuthorityUrl,
                ClientId = options.ClientId,
                RedirectUri = options.RedirectUri,
                SignInAsAuthenticationType = "Cookies",
                ResponseType = "id_token token",
                Scope = "openid profile roles MyCustomScope" 
            });
```
Other thing you need to keep in mind, you can have Identity or resource Tokens, depending if you are configuring OpenID Connect or OAuth2 scopes. If your custom claims Type is Identity take a look at the property AlwaysIncludeInIdToken, by default is false. 

Check the documentation, is very extensive: http://identityserver.github.io/Documentation/docs/configuration/scopesAndClaims.html

Hope it helps

**Comment by mahelm** [comment]
Tank you, specifying Scope with UseOpenIdConnectAuthentication did it!

Best regards / Mattias
