### ISSUE TITLE
Use State parameter to prevent CSRF using OWIN

### ISSUE THREAD

**Issue by kishoreabhishek** [IdentityServer/IdentityServer3#1511]
I am using Microsoft Owin component. I use OpenIdConnectAuthenticationOptions to set the ThinktectureIdentityServer Authority URL,ClientID,Scope properties. I am unable to find a way to use State parameter under OpenIdConnectAuthenticationOptions . How do I use State parameter in this case.  A code snippet of startup.cs of my client is shown below:
var options = new OpenIdConnectAuthenticationOptions
            {
                ClientId = "testclient",
                Authority = ConfigurationManager.AppSettings["IdentityServer"],
                RedirectUri = ConfigurationManager.AppSettings["Client"],
                PostLogoutRedirectUri = ConfigurationManager.AppSettings["Client"],
                ResponseType = "code id_token token",
                Scope = "openid email profile read write offline_access 

                SignInAsAuthenticationType = "Cookies",

                Notifications = OpenIdConnectConfig.AuthenticationNotifications
            };

**Comment by huysentruitw** [comment]
I think the state is what you pass to the `AuthenticationProperties` dictionary during authentication challenge:

```C#
var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
properties.Dictionary["myStateKey"] = "myStateValue";
context.HttpContext.GetOwinContext().Authentication.Challenge(properties, authenticationType);
```

**Comment by kishoreabhishek** [comment]
I am lost here, Where do you suggest I should add these lines:
var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
properties.Dictionary["myStateKey"] = "myStateValue";
context.HttpContext.GetOwinContext().Authentication.Challenge(properties, authenticationType);

**Comment by huysentruitw** [comment]
I would suggest to create a MVC web application with authentication and search for `Authentication.Challenge`

**Comment by kishoreabhishek** [comment]
MVC web application with authentication - isthis template present only in ASP.Net MVC5

**Comment by kishoreabhishek** [comment]
ok I got this line but where do I plug this in the context of OWIN middleware

**Comment by kishoreabhishek** [comment]
Is there any middleware which is called only when AuthorizationCodeReceived event is raised

**Comment by brockallen** [comment]
If you need to round-trip state from your app to IdSvr, then do as @huysentruitw suggest. You'd populate that dictionary where you trigger the authentication request to IdSvr. Where do you do that now?

**Comment by kishoreabhishek** [comment]
I do it in Configuration method of Statrtup.cs. The code snippet is shown below:
var idSvrFactory = InMemoryFactory.Create(
                  clients: Clients.Get(),
                  scopes: Scopes.Get());
          IdentityServerOptions oIdentityServerOptions = new IdentityServerOptions
          {
             SiteName = "Test Auth Server (" + FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).ProductVersion + ")",
             SigningCertificate = Cert.Load(),
             Factory = idSvrFactory,
             CorsPolicy = CorsPolicy.AllowAll,
             AuthenticationOptions = new AuthenticationOptions
             {
                IdentityProviders = ConfigureIdentityProviders,
                EnableSignOutPrompt = false,
                EnableLocalLogin = false,
                EnablePostSignOutAutoRedirect = true,
                SignInMessageThreshold = 0
             }
          };
          return oIdentityServerOptions;

**Comment by brockallen** [comment]
This is your IdSvr config, not the client app. I'm confused.

**Comment by leastprivilege** [comment]
sorted?

**Comment by kishoreabhishek** [comment]
Well, I implemented it my way by adding an OWIN middleware which would add CSRF token to Request headers only if AuthorizationCodeReceived event is raised

**Comment by laksh-parab** [comment]
I have the same questions, I don't see OpenIdConnectAuthenticationOptions has state property. If try huysentruitw's approach then I get error 

> No owin.Environment item was found in the context.

 the Here is my client startup

`	public void Configuration(IAppBuilder app)
        {
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            var properties = new AuthenticationProperties();
            properties.Dictionary["myStateKey"] = "myStateValue";
            System.Web.HttpContext.Current.GetOwinContext().Authentication.Challenge(properties); // error here

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://localhost:44314/identity",
                Scope = "openid profile",
                ClientId = "LocalHostMvcClient",
                RedirectUri = "http://localhost:34937/",
                ResponseType = "id_token",
                SignInAsAuthenticationType = "Cookies",
	    }
}`
