### ISSUE TITLE
Tokens getting too Large for Implicit Flow

### ISSUE THREAD

**Issue by umair-ali** [IdentityServer/IdentityServer3#1512]
Hi Guys, I have been working on IdentityServer3 and I observed that my Access Token (and Identity token) is getting too large (up to 3000+ chars) in case of Implicit flow, while same server is returning access token of about 20-30 chars against Resource Owner flow. Is this issue is specific to Flows or I'm doing something wrong...???

What I'm have in my visual studio solution is 
- Separate/standalone IdentityServer server project
- Mvc Application project (using implicit flow)
- Console app (using resource owner flow)
- Web api project (gets access token from either mvc app or console app in request header)

Once I login into mvc app, it gets a pretty large access token (and identity token), but in case of console app it just returns a nice and compact one. Why is the difference here...???

**Comment by soliveira** [comment]
Hi there. Have you tried to check the token content and se what claims are served in each claim?

You can decode the token at http://jwt.io

**Comment by umair-ali** [comment]
Larger token that has been returned by implicit flow contains list of scopes, roles, claims and other generic claims like sub, nonce etc.

However, the smaller token that has been returned by resource owner flow is just a encrypted string (c7de156d80061081ee9e8a9299415ace) which is decoded correctly in jwt.io. It looks strange, this smaller token is working just fine and able to initialize the identity in web api context with all the claims.

**Comment by umair-ali** [comment]
@soliveira You also shocked me that my token is just easily decodable at jwt.io. I was considering it to be very secure, but its not. What is the catch here...??

PS: may be this is a childish question :-|

**Comment by huysentruitw** [comment]
JWT tokens are not encrypted. They are signed to prevent manipulation. So, don't put sensitive data in the token.

**Comment by soliveira** [comment]
@huysentruitw is right the token should be readable by the client, therefore is ton encrypted. The token is signed to prevent modifications  and source validation.

To prevent eavesdropping you should communicate via HTTPS.

There is no catch :)

**Comment by umair-ali** [comment]
@soliveira @huysentruitw Great thanks.

But original question is still there, why the token in Implicit flow is too large???

**Comment by ankur--bhatia** [comment]
can you paste the two tokens. I dont think they should be different. I
think you might be requested different set of claims in the two flows.

**Comment by brockallen** [comment]
If you want to shorten the URL, use reference access tokens. Check the client configuration docs for more info.

**Comment by umair-ali** [comment]
Thanks @brockallen I just got it right by using Reference token as type for my access token.

In fact, Default access_token type for Imiplict flow is JWT Token, while ResourceOwner flow, returns Reference token. I was unaware of these types, that's why I got confused. Playing with configuration did the trick.

**Comment by joseph-adam** [comment]
Hello @brockallen , I am building a implicit flow and would like to use a login that returns a JWT.  We currently have a resource password flow wired in and are attaching claims to the token on password validation.  It seems in the quickstart sample that a cookie based token is generated and sent somehow on the redirect.  This seems like a black box mechanism that happens in HttpContext.Authentication.SignInAsync.  Do you know how you would return a JWT bearer token on the http post to the login page?  Thank you for your help.
