### ISSUE TITLE
Question: How to validate access token?

### ISSUE THREAD

**Issue by pavanputhra** [IdentityServer/IdentityServer3#1513]
The framework which am using to write REST API doesn't have library to validate OAuth tokens.

Could you please tell me the algorithm to validate token, so that I can write my own validation code?

**Comment by leastprivilege** [comment]
You either need a JWT library - and they are available for pretty much any platform...or you can use the access token validation endpoint (check the docs).

**Comment by pavanputhra** [comment]
I got some JWT library for Meteor.js framework, which supports following alogrithms HS256, HS384, HS512 and RS256.

Which one does identity server uses?

**Comment by leastprivilege** [comment]
RS256
