### ISSUE TITLE
Get ClientId in GetClaimsFromAccount

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#1514]
Hello,
I use custom override of https://github.com/IdentityServer/IdentityServer3.AspNetIdentity for UserService and I try to get `ClientId` when i override `protected override async Task<IEnumerable<Claim>> GetClaimsFromAccount(User user)` because i want to filter claims from database by `ClientId`. How i can do this?
I try to do this:
```C#
....
       public string ClientId { get; set; }

        public override Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message)
        {
            if (message != null) ClientId = message.ClientId;
            return base.PreAuthenticateAsync(message);
        }
....
```
and in `GetClaimsFromAccount` i try this:
```C#
protected override async Task<IEnumerable<Claim>> GetClaimsFromAccount(User user)
{
...
 if (ClientId != null)  // do something ;
...
}
```

but `ClientId`  in `GetClaimsFromAccount` is always null.
 how i can solve my problem?

**Comment by brockallen** [comment]
The client id is available in 2.0.0 in the user service's get profile API.

**Comment by totpero** [comment]
can you get me example how to do pls?

**Comment by brockallen** [comment]
From the dev branch, here's the new user service interface:
https://github.com/IdentityServer/IdentityServer3/blob/dev/source/Core/Services/IUserService.cs#L72

and here's the `ProfileDataRequestContext`:
https://github.com/IdentityServer/IdentityServer3/blob/dev/source/Core/Models/ProfileDataRequestContext.cs#L66

**Comment by totpero** [comment]
and this will be implemented also in  Thinktecture.IdentityServer.AspNetIdentity ?

**Comment by totpero** [comment]
When 2.0.0 version will be available on nuget.org or on myget.org like prerelease ?

**Comment by brockallen** [comment]
We're doing another beta today -- it'll be available here: https://www.nuget.org/packages/IdentityServer3

**Comment by jbn566** [comment]
I am slightly confused how exactly one is suppose to get the client id from within the IUserManager.  My system has claims values that are different per client and need a way to get that info so I can set it using the ASP.NET identity

Any actual code samples would be great .
