### ISSUE TITLE
Use idsrv as external in another idsrv (oidc)

### ISSUE THREAD

**Issue by balbelias** [IdentityServer/IdentityServer3#1517]
I am little confused after reading next 2 issues: [#435](https://github.com/IdentityServer/IdentityServer3/issues/435) and [#59](https://github.com/IdentityServer/IdentityServer3/issues/59).

Did I understand right, that workflow like client -> idsrv1 -> idsrv2 -> google is not suported yet?
I tried to achieve it with next configuration:
```
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions()
            {
                Authority = "idsrv2 address",
                AuthenticationType = "openidconnect",
                Caption = "idsrv",

                ClientId = "1",
                Scope = "openid profile",
                ResponseType = "id_token token",
                RedirectUri = "???", // <== here is the problem
                PostLogoutRedirectUri = "???", // <== here is the problem

                SignInAsAuthenticationType = signInAsType,
                UseTokenLifetime = false,
            });
```
And I was not able to understand which redirect_uri should be set.

If this workflow is not supported out-of-box, is there a way to implement it myself? Somehow implementing IUserService (to be more specific, its AuthenticateExternalAsync), for example.

And when you are planning (if you do) to add that functionality out-of-box? I found link to beta3 on issue 59, but it is broken and it seems beta3 is already released.

Thanks!

**Comment by brockallen** [comment]
You can configure IdSvr (say 'A') to trust another IdSvr (say 'B'), sure. And that 'B' IdSvr can be configured to use Google.

**Comment by balbelias** [comment]
Thanks to quick response, Brock!

But what redirect_Uri should I path to idsrv 'b'? I marked that place in code sample.

Отправлено с моего Windows Phone

-----Original Message-----

**Comment by brockallen** [comment]
You'd configure that with the Katana open id connect authentication middleware. If you do nothing special, then it's the path at which the OIDC MW is registered. Otherwise you can configure a custom callback path. Check the docs from Microsoft.
