### ISSUE TITLE
Question about best practise di registrations

### ISSUE THREAD

**Issue by david-ernstsson-stratsys** [IdentityServer/IdentityServer3#1518]
Hey, 

Got a question about the di in idsrv and best practise/recommendation of how to plug idsrv and its services into a "fairly" large existing system. We may very well be missing something fundamental (either in autofac or idsrv) but we have a problem with how to best register all our (db) implementations  of the stores and services (along with their respective dependencies) that we plug into idsrv.

Now while in theory we certainly can do any of the following:
- register type-by-type every single type that we use to Registrations property available
- use some sort of reflection to accomplish the following from our existing di and autofac-container
- resolving some key services to limit the number of registrations needed

Neither of the above seems both clean and optimal from a maintenance point of view.

Any thoughts/recommendations on this? For us it would have been easier to have full access to the autofac-container but we can't see how.

**Comment by huysentruitw** [comment]
We also use Autofac and I didn't want to register all types twice either, we register our container to OWIN, like you usually do:

```C#
app.UseAutofacMiddleware(container);
```

Then, I wrote an extension method for `IDependencyResolver`:

```C#
public static class DependencyResolverExtensions
{
    public static T ResolveFromAutofacOwinLifetimeScope<T>(this IDependencyResolver resolver)
    {
        var owin = resolver.Resolve<OwinEnvironmentService>();
        var context = new OwinContext(owin.Environment);
        var scope = context.GetAutofacLifetimeScope();
        return scope.Resolve<T>();
    }
}
```

And we use it like this:

```C#
var options = new IdentityServerOptions
{
    Factory = new IdentityServerServiceFactory
    {
        ScopeStore = new Registration<IScopeStore>(dr => dr.ResolveFromAutofacOwinLifetimeScope<IScopeStore>()),
        ClientStore = new Registration<IClientStore>(dr => dr.ResolveFromAutofacOwinLifetimeScope<IClientStore>()),
        UserService = new Registration<IUserService>(dr => dr.ResolveFromAutofacOwinLifetimeScope<IUserService>()),
        //...
    },
    //...
}
```

**Comment by brockallen** [comment]
Well, in the systems I've worked with IdentityServer has its own set of dependencies and you'd only ever need those in IdSvr, so there are no redundancies there. Some things might be shared across IdSvr and another system (such as your identity management components) but those tend to be just a few, so just register those twice. 

Even if it doesn't feel terribly elegant I try to keep things simple and deliberate.

Perhaps I'm missing something, though.

**Comment by david-ernstsson-stratsys** [comment]
While we certainly (mostly at least...) do use specific services for the idsrv we still would prefer to use the same layered architecture (and naming conventions) as our other applications.  

It's not really so much a matter of redundancies but rather the fact we already have an existing architecture (like most existing systems i assume?) in place and configured autofac to support it. It would be so much easier to rely on our existing one rather than mainting its own set of dependencies for idsrv. Basically we would probably end up writing something like huysentruitw mentions above which doesn't feel optimal.

Specifically the end-user administration of the clients does share alot of di nhibernate-classes with idsrv which are injected using our existing setup.

Owell, it may not be that big of a deal just wondered if we were missing something and otherwise its a great product, keep up the good work :)

**Comment by brockallen** [comment]
Yea, sorry -- the main issue here is that OWIN doesn't have a common DI definition, and IdSvr uses Autofac as an implementation detail and thus consumers are shielded from it. Perhaps you can come up with a contrib project to allow for somehow using Autofac for the IdSvr DI registrations? :)

**Comment by david-ernstsson-stratsys** [comment]
What @huysentruitw added above works pretty elegantly, cheers!

**Comment by brockallen** [comment]
Yep, that works as long as no dependency from autofac needs a dependency from IdSvr.
