### ISSUE TITLE
WS Fed Metadata

### ISSUE THREAD

**Issue by pirovorster** [IdentityServer/IdentityServer3#1519]
So I have added ADFS authentication using the UseWsFederationAuthentication method. Where do I get the metadata file that I need to give to ADFS? 

I have tried 

https://www.mydomain.co.za/wsfed/metadata
https://www.mydomain.co.za/identity/wsfed/metadata

including some other variations to no avail.

**Comment by huysentruitw** [comment]
The metadata is hosted by the ADFS server's metadata endpoint. So it depends on the ADFS server configuration. If it's f.e. MS ADFS 3 server then the metadata endpoint will be on:

https://YourAdfsServer/FederationMetadata/2007-06/FederationMetadata.xml

**Comment by pirovorster** [comment]
No no I am aware of the adfs metadata endpoint, however adfs requires a metadata endpoint as well to setup the relying parties.

On the identityserver website they have documentation of this: http://identityserver.github.io/Documentation/docs/wsFederation/endpoints.html
however I have tried the 2 addresses as mentioned above to no avail.

This is how I understand it in any way. I know we also had to do something similar when we were still investigating azure access control.

**Comment by huysentruitw** [comment]
Have you added the WSFederation plugin? See https://github.com/identityserver/IdentityServer3.WsFederation

**Comment by brockallen** [comment]
You'd have to ask Microsoft for metadata for the RP -- that's their middleware and unrelated to IdentityServer.

**Comment by pirovorster** [comment]
Ah ok... I know there is a manual way to add relying parties as well to adfs. I will try that. Thanx guys
