### ISSUE TITLE
password grant type "invalid_client"

### ISSUE THREAD

**Issue by vectorderivative** [IdentityServer/IdentityServer3#1520]
```C#
new Client
                {
                    ClientId = "esmifavorito",
                    ClientName = "esmifavorito-client",
                    Enabled = true,
                    ClientSecrets = new List<ClientSecret>
                    {
                        new ClientSecret("esmifavorito".Sha256()) //PQ/pIgjXnBfK67kOxGxz9Eykft6CKPkPewR3jUNEkZo=
                    },

                    Flow = Flows.ResourceOwner,

                    //RequireConsent = false,
                    //AllowRememberConsent = false,
                    //ClientUri = "http",
                    RedirectUris = new List<string>
                    {
                        "https://localhost:44304",
                    },

                    ScopeRestrictions = new List<string>
                    {
                    },

                    AllowedCorsOrigins = new List<string> 
                    {
                        "https://localhost:44304",
                        "http://localhost:50655",
                        "chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm",
                        "*",
                    },

                    PostLogoutRedirectUris = new List<string>
                    {
                        "https://localhost:44304",
                    },
                    
                    AccessTokenType = AccessTokenType.Jwt,
                    IdentityTokenLifetime = 3000,
                    AccessTokenLifetime = 3600,
                    AuthorizationCodeLifetime = 300
                }
```

I have registered my client, with implicit flow it works but I need to implement a login form so I'm trying Resource owner password credentials grant.
I'm doing requests to the endpoint with Postman in Chrome (that's why I added the chrome-extension to CORS, just to see if that was the error...)

I've tried a lot of requests (using https)

```
POST /connect/token HTTP/1.1
Host: localhost:44302
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=test&password=testuser&client_id=esmifavorito&scope=write
```

```
POST /connect/token HTTP/1.1
Host: localhost:44302
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=test&password=testuser&scope=write&client_id=esmifavorito&client_secret=PQ%2FpIgjXnBfK67kOxGxz9Eykft6CKPkPewR3jUNEkZo%3D
```

```
POST /connect/token HTTP/1.1
Host: localhost:44302
Authorization: Basic ZXNtaWZhdm9yaXRvOmVzbWlmYXZvcml0bw==
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=test&password=testuser&scope=write
```

Those should have worked but I'm always getting invalid_client

The error log is empty, I don't know if I have done the tracer registration right
```C#
LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());
app.UseIdentityServer(new IdentityServerOptions
                {
                    LoggingOptions = new LoggingOptions {
                        IncludeSensitiveDataInLogs = true,
                        WebApiDiagnosticsIsVerbose = true,
                        EnableWebApiDiagnostics = true,
                        //EnableHttpLogging = true
                    },
                    SiteName = "Thinktecture IdentityServer3 - UserService-AspNetIdentity",
                    SigningCertificate = Certificate.Get(string.Format(@"{0}\bin\IdentityServer\IdentityServerEMFDev.pfx", AppDomain.CurrentDomain.BaseDirectory), "KG0yM0At"),
                    Factory = idSvrFactory,
                    CorsPolicy = CorsPolicy.AllowAll,
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        IdentityProviders = ConfigureAdditionalIdentityProviders,
                    },
                }
            );
```

With this in web.config
```xml
<trace autoflush="true"
           indentsize="4">
      <listeners>
        <add name="myListener"
             type="System.Diagnostics.TextWriterTraceListener"
             initializeData="Trace.log" />
        <remove name="Default" />
      </listeners>
    </trace>
```

The client data is correct since I have succesfuly logged in with implicit flow.
What am I missing? This is getting on my nerves, I'm reading the OAuth RFC and I don't see why this shouldn't work.

**Comment by vectorderivative** [comment]
I tried with the new version of Postman and everything is working...
I even tried using a similar tool for Firefox and the results were the same. I don't see how this is happening... I suppose it's some typo that I can't see (even tho I copied everything from old Postman to the newer)

This is the new working request

```
POST /connect/token HTTP/1.1
Host: localhost:44302
Authorization: Basic ZXNtaWZhdm9yaXRvOmVzbWlmYXZvcml0bw==
Cache-Control: no-cache
Postman-Token: fc4acc63-29f2-6a37-b92c-b62034b13c29
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=test&password=testuser&scope=write
```

I think this is no longer an issue but I don't know why...

Best regards.

**Comment by anish714** [comment]
I know the issue is closed.  But why do we need an Authorization header if grant_type is password?

**Comment by SeriousM** [comment]
> I know the issue is closed. But why do we need an Authorization header if grant_type is password?

Because it contains the client information

`ZXNtaWZhdm9yaXRvOmVzbWlmYXZvcml0bw==` contains `esmifavorito:esmifavorito`.

**Comment by udayb2014** [comment]
Is that supposed to be `client_id:client_secret`?

**Comment by SeriousM** [comment]
Yep, that's right. For more information have a look at the rfc

**Comment by UlyssesAlves** [comment]
Where does ZXNtaWZhdm9yaXRvOmVzbWlmYXZvcml0bw== comes from? Do I have to combine the client_id and client_secret together and generate a hash afterwards? If so, how do I do that?

**Comment by udayb2014** [comment]
@UlyssesAlves it's not a hash, just base64 encoding

**Comment by UlyssesAlves** [comment]
@udayb2014 Ok, but how is it assembled? I'm receiving the answer invalid_client every time I try to call the /connect/token endpoint with grant_type=password. I just want to get an access token by passing the username and password to the IdentityServer server instance, but my requests are not being successful. I've tried many different ways to make this request, but had no success yet. I enabled logging, but the logs just says the same as what is returned by the server: "invalid_client". So I'm stuck in this authentication step. Looking here and there on the internet to try to find someone who has experienced this same issue.

**Comment by udayb2014** [comment]
@UlyssesAlves So there's many ways to send your info to the id_server, and the invalid_client error can be caused by a lot of different things. Can you post a sample request and client store so I can an idea of what's going on.

Another pointer: turned out in my case, the problem was being caused by the way I was storing client secrets. By default, IdentityServer expects stored secrets to be either SHA256 or SHA512 hashes. So before I had something like this:

```
new Client
            {
                Enabled = true,
                ClientName = "stuff",
                ClientId = "stuff",
                Flow = Flows.Implicit,
                ClientSecrets = new List<Secret> { (new Secret("secret")) },
                RedirectUris = new List<string>
                {
                       ...
                }
            }
```


The the corrected version was:

new Client
            {
                Enabled = true,
                ClientName = "stuff",
                ClientId = "stuff",
                Flow = Flows.Implicit,
                ClientSecrets = new List<Secret> { (new Secret("secret".Sha256())) },
                RedirectUris = new List<string>
                {
                       ...
                }
            }
```

I was tripped up over this for a long time, and it wasn't anywhere in the docs (as far as I could tell). Of course the standard advice to check your logs still applies

**Comment by UlyssesAlves** [comment]
@udayb2014 Thanks for helping us. My secret is already being hashed as Sha256() as your last code snnipet above. I'm going to put bellow a simplified version of my code, just for the sake of demonstrating how my integration with IdentityServer looks like in my project:

First, here is how I build my IdentityServer3 configuration to be used by my Web Api project:

```
public IdentityServerOptions GetIdentityServerOptions()
        {
            return new IdentityServerOptions
            {
                SiteName = "My site name",
                RequireSsl = true,
                IssuerUri = "https://localhost:44397/identity",
                Factory = new IdentityServerServiceFactory()
                        .UseInMemoryUsers(GetUsers())
                        .UseInMemoryClients(GetClients())
                        .UseInMemoryScopes(GetScopes()),

                LoggingOptions = new LoggingOptions
                {
                    EnableHttpLogging = true,
                    EnableKatanaLogging = true,
                    EnableWebApiDiagnostics = true,
                    WebApiDiagnosticsIsVerbose = false
                }
            };
        }

private List<Client> GetClients()
        {
            var appsAsStoredInMyDatabase = GetApps();

            return appsAsStoredInMyDatabase.ConvertAll<Client>(ConvertToIdentityServerClient);
        }

private Client ConvertToIdentityServerClient(MyDomainApp app)
        {
            return new Client
            {
                Enabled = true, 
                ClientName = app.Name,
                ClientId = app.Id.ToString(), // There's only one client, whose id is "20E59DA7-3FED-46C2-B922-557540026B37"
                Flow = Flows.ResourceOwner,

                ClientSecrets = new List<Secret>
                {
                    new Secret("abc123".Sha256())
                },

                AllowedScopes = GetAllowedScopes().ToList().ConvertAll<string>(scope => scope.Name),

                AllowedCorsOrigins = new List<string>
                {
                    "*"
                }
            };
        }

private IEnumerable<Scope> GetAllowedScopes()
        {
            var customScopes = GetCustomScopes();

            return new List<Scope>
            {
                StandardScopes.OpenId,
                StandardScopes.Profile,
                StandardScopes.Roles
            }.Concat(customScopes);
        }
```

Then, here is how I've setup up IdentityServer3 in my WebApi project:

```
public void Configuration(IAppBuilder app)
{
app.Map("/identity", identityServerApp =>
            {
                identityServerApp.UseIdentityServer(GetIdentityServerOptions());
            });

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                IssuerName = "Issuer Name",
                SigningCertificate = LoadCertificate(),
                Authority = "https://localhost:44397/identity",

                ClientId = "20E59DA7-3FED-46C2-B922-557540026B37", // same Id as the one of the stored client (please see method GetClients() above).
                ClientSecret = "abc123",

                RequiredScopes = new[] { "Required-Scope" }
            });	
}

private X509Certificate2 LoadCertificate()
        {
            return new X509Certificate2(
            string.Format(@"{0}\bin\idsrv3test.pfx", AppDomain.CurrentDomain.BaseDirectory), "idsrv3test");
        }
```

Finally, here is the POST request I'm trying to execute to get an access token to authenticate my app in behalf of the user:

```
POST /identity/connect/token HTTP/1.1
Host: localhost:44397
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: 6cb32fc9-c7be-1d9b-74da-25927bc5d7f7

grant_type=password&client_id=20E59DA7-3FED-46C2-B922-557540026B37&scope=Required-Scope&client_secret=abc123&username=Ulysses&password=12345
```
Either the integration with IdentityServer3 isn't set up property, or the request is not being assembled as expected by IdentityServer3. Can you spot any mistake in my code or request? Thanks again for taking your time to help us.

**Comment by UlyssesAlves** [comment]
@udayb2014 Sorry about all that long text. I ended up checking the file log, and it indeed says that there's no client with the given ID. The problem was the GUID is loaded in lower case by C#, and I was using the GUID in uppercase as stored in my database. So now the error has changed to "invalid_grant", but I think the log will guide me now to the fixing of most erros which may apper from here on. Thanks one more time for your support.

**Comment by udayb2014** [comment]
Hi, sorry for getting back to you so late, but good to know that you found the source of the error. Looking at your client setup, I'm afraid I can't say much to help you from here. The only time I encountered was when validating access tokens through `/accesstokenvalidation`, but that doesn't look like it's relevant here.

Good luck!

**Comment by fbolafsson** [comment]
@UlyssesAlves 

your body is 

grant_type=password&client_id=20E59DA7-3FED-46C2-B922-557540026B37&scope=Required-Scope&client_secret=abc123&username=Ulysses&password=12345

Don't you have to include in the heade Authorization: Basic <Base64(20E59DA7-3FED-46C2-B922-557540026B37:abc123)>
so Authorization: Basic MjBFNTlEQTctM0ZFRC00NkMyLUI5MjItNTU3NTQwMDI2QjM3OmFiYzEyMw==

and let the body be 

grant_type=password&scope=Required-Scope&username=Ulysses&password=12345

Although I'm no expert

**Comment by udayb2014** [comment]
@fbolafsson you have the option to add it either way: https://identityserver.github.io/Documentation/docsv2/endpoints/token.html#authentication

**Comment by UlyssesAlves** [comment]
@fbolafsson I don't know, bro. Like I said [in a comment above](https://github.com/IdentityServer/IdentityServer3/issues/1520#issuecomment-287465163), enabling the logs showed me that the error was something totally different from what I thought it would be. Now my system is working and I didn't have to change anything related to IdentityServer to make it work. That is, the settings were already correct, my client application the actual culprit.

**Comment by nukec** [comment]
@UlyssesAlves ... thanks for explaining how you resolved problem.
