### ISSUE TITLE
Login page redirects to login page

### ISSUE THREAD

**Issue by iguanaware** [IdentityServer/IdentityServer3#1522]
Helpful Hint:

If you have an application that the login page seems to redirect back to the login page over and over. Check the case of the cookie path.  The Client application had a different case then IIS did.  The result was that some of the cookies where lower case and some where mixed case.  The browse is case sensitive so it was not sending the cookies to https://.../identity/connect/authorize.  And the it would redirect back to the login page with a new signin value.

```
Set-Cookie: SignInMessage.22b49f099dd6dae01cffdd1742a02240=.; path=/identity; expires=...; HttpOnly
Set-Cookie: idsvr.session=2853d3a71d950a0754301eb72987e6e6; path=/identity
Set-Cookie: idsrv.partial=; path=/Identity; expires=Thu, 01-Jan-1970 00:00:00 GMT
Set-Cookie: idsrv.external=; path=/Identity; expires=Thu, 01-Jan-1970 00:00:00 GMT
Set-Cookie: idsrv=A4B5CD...; path=/Identity; HttpOnly
```

The following log records will also be found
INFO Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator [(null)] - Authorize request validation success
INFO Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeInteractionResponseGenerator [(null)] - User is not authenticated. Redirecting to login.

The actual HTTP Traffic was (Repeating)
```
GET connect/authorize  -> 302 login
GET login              -> 200
POST login             -> 302 connect/authorize
```

**Comment by brockallen** [comment]
Wow, that's a good tip. I'll close this so for now, but it'll be in the archives when people search. Thanks.
