### ISSUE TITLE
Please provide a sample of IdentityServer or IdentityModel‏

### ISSUE THREAD

**Issue by benjaminliu** [IdentityServer/IdentityServer3#1524]
We are working on a web api project, it provide datas for android apps. We don't use third party login (like facebook login), just want user enter user name/password (stored in our database) and give him a token, user can use token to access web api. 

This may not need oauth.

Could someone help to provide us a sample with IdentityServer or IdentityModel for this scenario?

We're using Visual Studio 2013 and Asp.net Web api 2.

Owin is welcome!

**Comment by brockallen** [comment]
You should look at our sample clients project -- there is one in there for resource owner flow. 

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients

Also, have a look at our docs to help answer other questions: https://identityserver.github.io/Documentation/docs/

**Comment by benjaminliu** [comment]
Thanks Brock,  Resource owner is my solution. 

Another question, at the server side, how to custom the user name / password validation? and how to apply the token validation?

**Comment by brockallen** [comment]
For credential validation you need a custom user service -- check the docs.

**Comment by benjaminliu** [comment]
Brock, i run the CustomUserSerice and ConsoleResourceOwnerClient, but get an error: remote
 certificate is invalid. Do i need to do something about the certificate?

**Comment by brockallen** [comment]
Yes -- you need to get SSL working. There's a Pluralsight video from Dominick's Web API security course that shows how to set that up.
