### ISSUE TITLE
How do you get the users email address?

### ISSUE THREAD

**Issue by rschiefer** [IdentityServer/IdentityServer3#1525]
I have IdentityServer setup and using the MicrosoftAccountAuthentication (based on http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html) but can't figure out how to get the user's email address to come back to my client as a claim.  I've read multiple posts that say MSFT makes this harder than it should be.  I can't seem to get it working. 

I plan on adding other identity providers (Twitter and Gmail) as well.  What is the best way to include email address from all these providers in the claims list back to the client?

**Comment by brockallen** [comment]
This is not an IdentityServer question or issue. I'd suggest asking on the Microsoft forums or checking their docs.

**Comment by loctanvo** [comment]
@rschiefer No idea about MicrosoftAccountAuthentication, but if you are using Google, I think you need to specify the `email` scope in the google authentication middleware. I guess it's something similar with MS as well. 

Regarding Twitter, they are not returning the user's email address (unless they have changed their policy within the last year).

**Comment by rschiefer** [comment]
During MSFT login it asks if I approve sharing email address but still isn't passed back to the client as a claim.  What configuration changes do I need to make to the IdentityServer or client config?

**Comment by loctanvo** [comment]
But do you get it back to IdServer? Typically in `AuthenticateExternalAsync` in your implementation of IUserService? In the middleware you are using to connect to MSFT, are you able to see all the raw claims coming back (typically in some OnAuthenticated callback)?

**Comment by rschiefer** [comment]
I don't have an IUserService setup yet but did fix this by setting the Scope property on my UseOpenIdConnectAuthenticationOptions class to "opened profile email".
