### ISSUE TITLE
Assets not being loaded on build 2.0.0.116

### ISSUE THREAD

**Issue by pinnprophead** [IdentityServer/IdentityServer3#1526]
When I go to the /identity page (where identityServer is mapped) the page is displayed but the icons and css are not loaded. Where do they come from? Also where is Angular loaded from?

![image](https://cloud.githubusercontent.com/assets/5665944/8314369/c7c9e016-19ae-11e5-8eec-ef7ba4c1c7b9.png)

For example, it is trying to load img src="https://localhost:44305/identity/assets/icon.png" 

Am I missing a package?

**Comment by brockallen** [comment]
And RAMMFAR is enabled?

**Comment by pinnprophead** [comment]
Rats what a moron I am! Thank you sir!
