### ISSUE TITLE
Is there any way to send custom error information if the login fails. 

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1529]
Currently we are using Resource Owner Credentials for logging in user,  But many situation can happen with the user like user is disabled, user account got locked, user password expired.   

We implemented IUserService to integrate our login mechanism,  I would like to know if there any way of passing extra error information to client instead of "invalid_grant" error value.

**Comment by leastprivilege** [comment]
in 2.0 - the error message you return from AuthenticateResult will be sent back from resource owner requests as well.

**Comment by skatukojwala** [comment]
I am using ThinkTrcture server version 3.0

**Comment by leastprivilege** [comment]
No you don't   :)

You are using IdentityServer3 - but which version?

**Comment by skatukojwala** [comment]
we are using https://www.nuget.org/packages/Thinktecture.IdentityServer3/1.6.2

**Comment by leastprivilege** [comment]
OK - we made that change in v2 - it is currently in beta (RC end of week - release in approx 2 weeks).

https://www.nuget.org/packages/IdentityServer3/

**Comment by skatukojwala** [comment]
I don't see any release notes for this beta release https://github.com/IdentityServer/IdentityServer3/tags

Would it be possible to get a summary of changes since 1.6.2. We want to analyze on what the new changes are and how much of impact it is going to have if we upgrade.

**Comment by leastprivilege** [comment]
That's the best we have right now:

https://github.com/IdentityServer/IdentityServer3/issues/1426

**Comment by skatukojwala** [comment]
Thank you! That helps.
