### ISSUE TITLE
Seems that the selfhost(mininal) example doesn't work on mono

### ISSUE THREAD

**Issue by javagg** [IdentityServer/IdentityServer3#1530]
I just cloned the examples and build them, nothing changes.It works fine on window with .net framework, but not on mono. Using firebug, I found the client just can't connect to the server. Does any one run into the same problem？ The id3svr version is 1.6.2

**Comment by loctanvo** [comment]
Related to [this issue](https://github.com/IdentityServer/IdentityServer3/issues/1443)?

**Comment by jonathankarsh** [comment]
The "Selfhost (Minimal)" example is an example of running id3svr version 1.1.0 (as seen [here] (https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/SelfHost%20(Minimal)/SelfHost/packages.config#L7) ), that is, if you use the master branch.

There's also a dev branch for the samples repo, where Selfhost (Minimal) seems to reference a version 2.0 candidate (probably "newer" than 1.6.2).

Are you seeing anything in the logs from id3svr when trying to connect?

I was able to run a number of samples on mono so may be able to help.

**Comment by leastprivilege** [comment]
We have some open issues related to mono - check the issue tracker.

We postponed them to 2.1 - feel free to post more finding.
