### ISSUE TITLE
How to do claims transformation in ResourceOwner flow

### ISSUE THREAD

**Issue by chrismikec** [IdentityServer/IdentityServer3#1534]
Good day. I'm just trying to use IdentityServer3 for access tokens to pass to my Web API using ResourceOwner flow. I'm trying to do claims transformation to strip out some of the unnecessary claims, but I'm not sure where or how to do it.

I read the simple MVC walkthrough, but it mentioned using OIDC notification method to strip them out, and I'm not using OIDC.

I thought perhaps I could do something through my ScopeClaims on my scope, but the claims are the default ones (like exp nbf, etc.) and so I don't explicitly include them as part of my scopeClaims anyway.

Am i missing something obvious here? I am also using AspNetIdentityUserService, if that helps.

Here is some of the pertinent code (I assume).

Any help is appreciated!

        Public Sub Configuration(app As IAppBuilder)
        LogProvider.SetCurrentLogProvider(New DiagnosticsTraceLogProvider())
        AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject
        JwtSecurityTokenHandler.InboundClaimTypeMap = New Dictionary(Of String, String)()

        ' Adds a custom user service to talk to our DB
        app.Map("/admin", Function(adminApp)
                              Dim factory = New IdentityManagerServiceFactory()
                              factory.ConfigureSimpleIdentityManagerService("UserMgmt")
                              adminApp.UseIdentityManager(New IdentityManagerOptions() With {
                                  .Factory = factory
                              })
                          End Function)

        Dim idSvrFactory = Factory.Configure()
        idSvrFactory.ConfigureUserService("UserMgmt")

        app.Map("/identity", Function(idsrvApp)
                                 idsrvApp.UseIdentityServer(
                                     New IdentityServerOptions() With {
                                         .SiteName = "Embedded IdentityServer",
                                         .SigningCertificate = LoadCertificate(),
                                         .Factory = idSvrFactory,
                                         .AuthenticationOptions = New Thinktecture.IdentityServer.Core.Configuration.AuthenticationOptions() With
                                                  {
                                                      .IdentityProviders = AddressOf ConfigureIdentityProviders
                                                  }})
                             End Function)

        app.UseResourceAuthorization(New AuthorizationManager())

        app.UseCookieAuthentication(New CookieAuthenticationOptions() With {
            .AuthenticationType = "Cookies"
        })
    End Sub

    Public Shared Function [Get]() As IEnumerable(Of Client)
        Return New Client() {
            New Client() With {
                .Enabled = True,
                .ClientName = "MyClient",
                .ClientId = "My.Web.Client",
                .AccessTokenType = AccessTokenType.Jwt,
                .RefreshTokenUsage = TokenUsage.OneTimeOnly,
                .RefreshTokenExpiration = TokenExpiration.Absolute,
                .Flow = Flows.ResourceOwner,
                .ClientSecrets = New List(Of ClientSecret) From
                {
                    New ClientSecret("MySecret".Sha256())
                }
            }
        }
    End Function

    Public Shared Function [Get]() As IEnumerable(Of Scope)

        Dim scopes = New List(Of Scope)() From {
            New Scope() With {
                .Enabled = True,
                .Name = "UserMgmt.Api",
                .Description = "Access to a sample API",
                .Type = ScopeType.Resource,
                .Claims = New List(Of ScopeClaim)() From {
                    New ScopeClaim("role"),
                    New ScopeClaim("OtherStuff")
                }
            }
        }

        scopes.Add(StandardScopes.OfflineAccess)

        scopes.AddRange(StandardScopes.All)

        Return scopes
    End Function

**Comment by leastprivilege** [comment]
Claims transformation happens at the the consumer of the token.

You can use the claims transformation middleware in your API e.g.

https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/source/Owin.ClaimsTransformation
