### ISSUE TITLE
Filter roles claims by different Areas 

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#1536]
Hello,

I have create one idsrv3 server and on this server i create roles claims linked to groups and this groups is created for clients applications.
Now i have client with many Areas and i consider each area like one application in my server groups.
My problem is how i can filter roles on server by one client key or other solution. How i know on my server when one client request claims which is the client and if is area this area is my key to filter my claims by application.
 I try to implement custom `UserService` and to override `GetClaimsFromAccount` but o don't know which is the client and i try to add static property and set this property in ` public override Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message)` but after some minutes if i try to access my client, the user is logged in but all roles disappear, client call the server to get `GetClaimsFromAccount` but this time the method `PreAuthenticateAsync` is not called because this is called only when i logged in and my clientid key is empty.
How i can solve my problem?

in my clients i use this method to authenticate:
```C# 
 app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
....
				Notifications = new OpenIdConnectAuthenticationNotifications
                {
					SecurityTokenValidated = async n =>
                    {
						var userInfoClient = new UserInfoClient(
                            new Uri(
                                SetariAutentificare.Settings.AdresaServer + Constante.UserInfoEndpointServer
                                ),
                            n.ProtocolMessage.AccessToken);

                        var userInfo = await userInfoClient.GetAsync();

                        foreach (Tuple<string, string> claim in userInfo.Claims.ToList())
                        {
							switch (claim.Item1)
                            {
                               case JwtClaimTypes.Role:
                                    claims.Add(new Claim(ClaimTypes.Role, claim.Item2));
                                    break;
		....
```

**Comment by brockallen** [comment]
IdSvr doesn't know about your areas, so it'd not know how to filter the claims. One way to handle this would be to configure a new client in IdSvr for each one of your areas. Since each area is treated as a different app, this seems to make sense. The one thing I worry about is the user crossing your area boundaries and then accidentally having the wrong identity information.

**Comment by totpero** [comment]
but how to filter roles on idSrv by ClinetId ? because i have try and not works because the only way to get the ClientId in UserService is in `PreAuthenticateAsync` method and this is called only when the user try to log in, but after few minutes if i try to access my client the `GetProfileDataAsync` method is called without calling  `PreAuthenticateAsync` method and i don't know how to get the userid because the `GetProfileDataAsync` is called form `SecurityTokenValidated ->UserInfoClient` and from this i don't have any unique client identifier.
How to solve this? and next step is the areas

**Comment by totpero** [comment]
is some possibilities using to solve this using `Thinktecture.IdentityModel.Owin.ResourceAuthorization` ?

**Comment by brockallen** [comment]
Perhaps -- you can just write your own authorization to prevent this.
