### ISSUE TITLE
LIve Id and Google Authentication fails 

### ISSUE THREAD

**Issue by Kunsar** [IdentityServer/IdentityServer3#1537]
I have set up a Federated authentication to my sharepoint application using Thinktecture Identity Server v2
I have configured identity providers for google and live ID.
I get successfully redirected to the live or google login page but get the following error message:
--------------------------------------------------------
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 131.253.61.84:443 

[SocketException (0x274c): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 131.253.61.84:443]
   System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult) +8554028
   System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) +354

[WebException: Unable to connect to the remote server]
   System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context) +3571077
   System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar) +155
------------------------------------------------------------------------
In trace log I get the follwing only:
HRD Endpoint called 
HRD Selection screen displyaed
HRD Selected Live
---------------------------------------------------------------------------
I have added the Redirect URL in Live applications management as https://<fqdn of idsrv>/issue/hrd/oauth2callback

Anyone has some knowledge regarding this error ?
Thanks in advance :-)

**Comment by brockallen** [comment]
I think you're asking about IdSvr2. This is the wrong repo for that.
