### ISSUE TITLE
CORS headers on authorize endpoint

### ISSUE THREAD

**Issue by CSobering** [IdentityServer/IdentityServer3#1539]
In the OIDC authorization code flow an origin-header is set (https://www.foo.com) in the first get request from the User Agent (Application) to the system of the Relying Party. The system of the Relying Party returns a 302 redirect to the Authorization Endpoint of the Identity Server.
The application then sends a get request to the Authorization Endpoint of the Identity Server, but now the origin-header is set to ‘null’. The application expects CORS headers in the response. 

How is it possible to set the CORS headers on the response?

The application uses the XMLHttpRequest component to handle the requests and responses.

**Comment by brockallen** [comment]
So you're trying to use JS/Ajax to drive the entire login process for a user?

**Comment by CSobering** [comment]
Yes, we are trying but did not succeed yet. 

To solve (or rather work around) the issue we want to add the following ACAO header in the response (on the authorization endpoint of the identity server)

`Access-Control-Allow-Origin: *`

but only if the request contained the Origin header

`Origin: http://www.foo.com`

What is the best way to do this?

**Comment by CSobering** [comment]
BTW the XMLHttpRequest component issues the normal HTTP get requests.

**Comment by brockallen** [comment]
We will not allow that -- this means a potential attacker can trigger accepts/consent for a user without them knowing.

**Comment by CSobering** [comment]
I understand that in Identity Server CORS policies are not implemented on the authorization endpoint. Furthermore if it were implemented, we should never allow all origins.

Question remains: does this mean that we cannot use the authorization code flow to drive the login process using XMLHttpRequest when the application, identity server and relying party are not in the same domain?

**Comment by brockallen** [comment]
Like I said before -- it's not something we designed for.

What are you trying to build or do? Perhaps there's a different way to go about it.

**Comment by CSobering** [comment]
It's a long story, but I'll try.

We have an application that accesses resources provided by a third party. The application is available as a mobile app and as a web application. To enable our users with access to these resources we implemented a sign-on architecture using the OIDC authorization code flow. The third party system acts as the relying party (or OpenID Connect client). We provide the identity server that authenticates the users, which is an IdentityServer3 installation

The login process is as follows:
1. The application communicates with the third party system to find out which sign-on algortihm has to be used to sign in.
2. The third party system answers with the algorithm to be used, as well as the url to be used to login in.
3 The application attempts to login the user at the third party system using the url from the previous step. 
4. When the user is not logged in to the third party system, the relying party redirects the user to the authorization endpoint of the identity server (including the redirect_uri).
5. The identity server redirects the user to the login page, where he enters his credentials and the user is authenticated in the backend.
6. The login page redirects the user back to the authorization endpoint of the identity server.
7. The authorization endpoint redirects the user back to the relying party (using the redirect_uri of step 4), including the authorization code.
8. The relying party calls the token endpoint of the identity server to exchange the authorization code for an access token.
9. The relying party calls the userinfo endpoint of the identity server, using the access token from the previous step, to obtain profile information.

In the web application and the mobile app step 1 & 2 are carried out using web api calls, with proper CORS implementation. Steps 3 through 7 are carried out in a normal browser window. Step 8 & 9 is server to server communication. So far, there are no problems.

Now we want to introduce a different version of the application, that must be running on a dedicated device with limited capabilities. It either runs a framework using web api calls (using XMLHTTPRequest) or a browser (not both at the same time). To switch from the framework to the browser, the framework must be unloaded which makes it very difficult (if not impossible) to pass context data from one to the other. 

The approach used to build the application was to use the framework to carry out all steps in the login process. In CORS terminology, the application, the relying party and the identity server are all on different origins. 

After allowing the origin of the application in the CORS Policy of the relying party, steps 1, 2 and 3 can be carried out without any problem. The application send the `origin=widget.application.com` header, the server accepts the origin and all is fine.

In step 4 however, the relying party responds with a 302 redirect, and `location=https://login.identityserver.com/core/authorize?..`. When the application evaluates this for CORS, it includes the header `origin=null` in the request that is made to the authorization endpoint. This follows the CORS recommendation for redirects. 

This is the point where the login process breaks, as there is no CORS policy on the authorization endpoint and if ther was, it should return an  ACAO header in the response with `Access-Control-Allow-Origin: *`

**Comment by brockallen** [comment]
Given the potential security implications for now we're going to say no on this enhancement until we've spent a lot more time thinking about it. It's not something we'd want to open up willy-nilly. I'll mark as an enhancement request for 2.1.

**Comment by leastprivilege** [comment]
we decided to not allow CORS requests on the authZ endpoint.
