### ISSUE TITLE
Exchange Bearer Token for Secure HTTP-Only cookie via Web API Resource

### ISSUE THREAD

**Issue by vcarreno96** [IdentityServer/IdentityServer3#1540]
I have a JavaScript client authenticating to Identity Server using the implicit flow. Upon initial authentication, the client receives an access_token and passes to a web api backend via auth/bearer HTTP header. Everything is good on the first request, however, I need a place to store the access_token on the client to perform subsequent requests.

I would like to avoid using local storage on the client and instead use the web api backend to exchange the bearer token http header for some sort of secure cookie.

Is it possible to attach something like an SecurityTokenValidated notification to IdentityServerBearerTokenAuthentication middleware to perform such an exchange from bearer token to cookie for a web api resource?

**Comment by leastprivilege** [comment]
That would kind of defeat the purpose - you actually want to get away from cookie based authentication for APIs.

Local storage is fine.
