### ISSUE TITLE
Return Claims with RO AuthenticateLocalAsync

### ISSUE THREAD

**Issue by Suamere** [IdentityServer/IdentityServer3#1542]
My IUserService "AuthenticateLocalAsync" works perfectly.  I pretty much just do this:

    return Task.FromResult(new AuthenticateResult("Subject", userName, identityProvider: "Custom"));

What I get back is a token like so:

    {
    "access_token": "72d920646593eca09b2c078a9bf6b290",
    "expires_in": 3600,
    "token_type": "Bearer"
    }

But I want to add one more property (claim?) to that.  With Straight-Up OAuth, I would be adding claims to GrantResourceOwnerCredentials.  But I don't see how to do that with IdentityServer.

I have tried altering the Scope to "all_claims", and have tried adding claims to the constructor like so:

    return Task.FromResult(new AuthenticateResult("Subject", userName, claims: new List<Claim> { new Claim("Test", "Value") }, identityProvider: "Custom"));

But I still don't get anything back other than the generic token.

What I want to include is the Password_Created_Date from my local persistence, so that when a person is authenticated, the client can decide what to do with the password date.

**Comment by brockallen** [comment]
You issue claims from the get profile API on the user service. You request claims via scopes and the scope claims definitions.

**Comment by Suamere** [comment]
What setting do I need to set in order to hit the get profile api?  Which I *assume* is GetProfileDataAsync.  At the moment, only AuthenticateLocalAsync is hit.

At the moment, I have a ScopeStoreService : IScopeStore, which currently returns either StandardScopes.All, or StandardScopes.Profile, or StandardScopes.ProfileAlwaysInclude.

So I request with the scope "profile".  But I don't hit the GetProfileDataAsync() method

**Comment by brockallen** [comment]
What is your client code doing or look like?

**Comment by Suamere** [comment]
var client = new OAuth2Client(new Uri("https://localhost:xxxx/connect/token"), "clientID", "SecretKey");
    var returnToken = client.RequestResourceOwnerPasswordAsync("bob", "AwesomePassword", "profile").Result;

Or, I make a call in Postman with my Authorization header and the following post data:
grant_type = password
username = bob
password = AwesomePassword
scope = profile

**Comment by leastprivilege** [comment]
Profile is an identity scope i guess - this means you need to contact the userinfo endpoint afterwards.

If you want the claims inside the access token - you need to associate them with a resource scope.
