### ISSUE TITLE
Authorization with Client Credentials flow not working

### ISSUE THREAD

**Issue by Otto45** [IdentityServer/IdentityServer3#1545]
I'm trying to implement the client credentials flow to secure our api, and I can't seem to get authorization working correctly.  Right now I'm trying to get everything working locally (IIS Express),  and I'm storing the client and scope info in a database.  I tried to include all of the relevant code below, so hopefully someone can see what I may be missing.  I left out the code for my test client because I know that is set up correctly.  I had an in-memory version of identityserver3 working correctly with it earlier.

My Startup.cs file for my api looks like this:
    
    [assembly: OwinStartup(typeof(Arrests.Startup))]
    namespace Arrests
    {
      public class Startup
      {
        public void Configuration(IAppBuilder app)
        {
            // Tells our application what authorization server to use to secure the API's, and the scopes it requires
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44302/identity",
                RequiredScopes = new[] { "ArrestsApi14" }
            });

            var config = new HttpConfiguration();

            // Web API routes
            config.MapHttpAttributeRoutes();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
              app.UseWebApi(config);
            }
        }
    }

Startup.cs for my identity server:

    [assembly: OwinStartup(typeof(AuthorizationServer.Startup))]
    namespace AuthorizationServer
    {
      public class Startup
      {
          public void Configuration(IAppBuilder app)
          {
              app.Map("/identity", idsrvApp =>
              {
                  idsrvApp.UseIdentityServer(new IdentityServerOptions
                  {
                      SiteName = "API Authorization Server",
                      Factory = Factory.Configure(),
                      CorsPolicy = CorsPolicy.AllowAll
                  });
              });
          }

Configuration Classes:

Factory:

    namespace AuthorizationServer.Config
    {
      public class Factory
      {
          public static IdentityServerServiceFactory Configure()
          {
              var factory = new IdentityServerServiceFactory
              {
                  UserService = new Registration<IUserService>(), // Don't need, but mandatory for idsvr3
                  ClientStore = new Registration<IClientStore, ClientConfig>(),
                  ScopeStore = new Registration<IScopeStore, ScopeConfig>()
            };
              return factory;
            }
        }
    }

Clients:

    namespace AuthorizationServer.Config
    {
      public class ClientConfig : IClientStore
      {
          public async Task<Client> FindClientByIdAsync(string clientId)
          {

              AuthServerData data = new AuthServerData();

              var clientFromDbTask = data.Clients.FirstOrDefaultAsync(e => e.ClientId == clientId);
              await clientFromDbTask;

              var clientFromDB = clientFromDbTask.Result;
              Client client = new Client();

              if (clientFromDB == null)
              {
                  return client;
              }
              client.ClientId = clientFromDB.ClientId;
              // logic to transfer data from database model into iddvr3 Client model
             return client;
           }

Scopes:

    namespace AuthorizationServer.Config
    {
        public class ScopeConfig : IScopeStore
        {
            public async Task<IEnumerable<Scope>> FindScopesAsync(IEnumerable<string> scopeNames)
            {
              AuthServerData data = new AuthServerData();
              List<Scope> foundScopes = new List<Scope>();
              foreach (var scope in scopeNames)
              {
                  var name = scope; // Seems redundant, but avoids compiler issues in LINQ method below
                  var dbScopeTask = data.Scopes.FirstOrDefaultAsync(e => e.Name == name);
                  await dbScopeTask;

                  var dbScope = dbScopeTask.Result;
                  if (dbScope == null)
                  {
                      continue;
                  }

                  Scope scopeToAdd = new Scope();
                  scopeToAdd.Name = name;
                  // logic to create idsvr3 Scope model from db model
                  foundScopes.Add(scopeToAdd);
                }
               foundScopes.AddRange(StandardScopes.All);
            return foundScopes;
          }

         public async Task<IEnumerable<Scope>> GetScopesAsync(bool publicOnly = true)
        {
             // Very similar to above, but converting all db scopes to idsvr3 scopes
        }

**Comment by leastprivilege** [comment]
Turn on logging to get more information

**Comment by Otto45** [comment]
I placed `LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());` in the Startup.cs file for my server project, and 

    <system.diagnostics>
      <trace autoflush="true">
        <listeners>
          <add name="TextWriter"
               type="System.Diagnostics.TextWriterTraceListener"
               initializeData="c:\Trace.log" />
        </listeners>
      </trace>
    </system.diagnostics>

in my web.config file, but a trace.log is never created.  Am I missing something?

**Comment by leastprivilege** [comment]
Make sure your process has at least modify access to the location you are writing to (unlikely for the root of your drive)

**Comment by Otto45** [comment]
I overlooked that, thanks.  So the exception that gets thrown is something internal to idsvr3:

    iisexpress.exe Error: 0          [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 6/29/2015          2:25:14 PM +00:00 -- Unhandled exception
    System.InvalidOperationException: An error occurred when trying to create a controller of type     'TokenEndpointController'. Make sure that the controller has a parameterless public constructor. --->     Autofac.Core.DependencyResolutionException: No constructors on type     'Thinktecture.IdentityServer.Core.Services.IUserService' can be found with the constructor finder     'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.
       at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext     context, IEnumerable`1 parameters) in     c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGene    rator.cs:line 0

It's trying to reference a file local on ballen's computer.  Is this an error on your end?  I downloaded everything through nuget, but it appears this path may have been hardwired?

**Comment by vossad01** [comment]
The exception is thrown in Thinktecture's code which is why you see a source and line number outside your code (that is the path at compilation, not something it is looking for at runtime).

In this particular case it is thrown from the Dependency Injection infrastructure.  The registrations this infrastructure are configured in your code so it is still a problem on your end.

```
var factory = new IdentityServerServiceFactory
  {
      UserService = new Registration<IUserService>(),
      ClientStore = new Registration<IClientStore, ClientConfig>(),
      ScopeStore = new Registration<IScopeStore, ScopeConfig>()
  };
```

See your registration for `UserService`.  That is basically saying, "When I need an `IUserService`, create an instance of the type `IUserService`."  Since `IUserService` is an interface it is not possible to create a new instance of it.  A concrete type must be provided registered to allow creation.

**Comment by Otto45** [comment]
Ah, that was it, thank you.  I'm still very new to .NET and C#, so I overlooked this.
