### ISSUE TITLE
IdSrv3 2.0.0 beta problems after updatate from 1.6.2

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#1548]
Hello,

I have installed 1.6.2 version and i update nugets to 2.0.0 version rc1 because i need this feature  https://github.com/IdentityServer/IdentityServer3/issues/1514 and i make update also to https://www.nuget.org/packages/IdentityServer3.EntityFramework/2.0.0-rc1 and https://www.nuget.org/packages/IdentityServer3.AspNetIdentity/2.0.0-rc1.
After this update i rename the namespaces and i comment `CorsPolicy = CorsPolicy.AllowAll,` in options because this property was not found, and when i try to access my application i get this error:
`The client application is not known or is not authorized.` and in the log file the error is:
`[IdentityServer3.Core.Validation.ScopeValidator]: 6/27/2015 11:14:05 PM +00:00 -- Requested scope not allowed: {0}` with the same scopes form the 1.6.2 version. My client scopes is: ` Scope = "openid email roles address profile offline_access"` . I have delete all the scopes and left only  "openid" i get the same error but if i allow only "roles" i get this error: `[IdentityServer3.Core.Validation.AuthorizeRequestValidator]: 6/27/2015 11:24:31 PM +00:00 -- {0}
 {1}` The log message is not formatted. This don't  works https://github.com/IdentityServer/IdentityServer3/blob/dev/source/Core/Validation/AuthorizeRequestValidator.cs#L520

**Comment by brockallen** [comment]
2.0.0 contains some breaking changes: One includes the changes for CORS which can now be allowed via the `AllowedCorsOrigins` on the `Client` configuration. Another is that scopes must be explicitly granted to clients via `AllowedScopes` on the `Client` configuration.

**Comment by totpero** [comment]
Thanks @brockallen this was my problems. Remain only one question: What is changed in the LogProvider because i use ` LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());` and in the trace log file the log events is not OK because is write something like this  `[IdentityServer3.Core.Validation.AuthorizeRequestValidator]: 6/27/2015 11:24:31 PM +00:00 -- {0} {1}` The log message is not formatted. This don't  works https://github.com/IdentityServer/IdentityServer3/blob/dev/source/Core/Validation/AuthorizeRequestValidator.cs#L520  
The `{0}` and `{1}` is not replaced with the parameters and all my log message is like this.
`[IdentityServer3.Core.Endpoints.AuthenticationController]: 6/28/2015 8:07:45 AM +00:00 -- external user provider: {0}, provider ID: {1}`
`[IdentityServer3.Core.Endpoints.AuthenticationController]: 6/28/2015 8:07:52 AM +00:00 -- redirecting to: {0}`
...
And in dev IdentityServer3.Host.Startup.cs file :
` // setup serilog to use diagnostics trace
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Trace()
                .CreateLogger();`

**Comment by totpero** [comment]
I change the logger provider to `Serilog` and works

**Comment by leastprivilege** [comment]
I just removed the old trace providers - it is recommended to use serilog or any other liblog supported provider instead.

**Comment by kuechlerm** [comment]
How can this be closed?!
I use IdentityServer3 2.0.0-rc1 and the Logger-Output is broken like described by @totpero. And now I am suppost to use Serilog? There is no SerilogLogProvider, so how can I use that?

This is all very confusing. Documentation sometimes talks about 1.6, sometimes about 2.0, but I never know. The Branches in this Repo say nothing, nothing and Beta3, but the Nuget is a RC1.

You got me really interested in this project, but at the moment I cannot make heads or tails out of all that - especially without logging.

**Comment by leastprivilege** [comment]
You don't need a serilog provider. Simply add serilog to the host and liblog will pick it up. See the host in our core repo for an example. 

Besides that - it's pre-release. Stay on 1.x if you want current docs.

**Comment by kuechlerm** [comment]
Thanks for the quick response, that was the hint I needed.
I felt a bit forced to go to that version because of the Asp.Net Identity Integration...
