### ISSUE TITLE
AspNet Identity With IdentityServer3

### ISSUE THREAD

**Issue by raxitr** [IdentityServer/IdentityServer3#1550]
I am confused how to configure ASPNet Identity with Identity server,
 
1) Is there any guide/samples how to plug ASPNet Identity with IdSrv3? Samples talks about InMemoryUser what it looks like in case of ASPNet Identity?
2) Is it necessary to use IdentityManager with IdentityServer in order to Setup  ASPNet Identity? 
3) I can follow Startup video  (https://vimeo.com/125426951) which explains how to use Identity manager with ASPNet Identity but can't figure out how it will work in conjuction with Idserver. or What are configuration steps which will Get users from from ASPNet Identity Store. 

Apologies If I the question is answered somewhere in which case I need correct pointer to help me get started.

**Comment by brockallen** [comment]
1. https://github.com/IdentityServer/IdentityServer3.AspNetIdentity
2. No
3. They're really unrelated. They're sharing a DB, but that's all.

**Comment by raxitr** [comment]
Can't believe it would be done so easily. I am ready with my ASPNet Identity Store plugged into IdentityServer. I have a long way to go but thanks for all the work you have done and putting all the stuff so thoughtfully for everyone to follow.

You guys are awesome!!
