### ISSUE TITLE
Token Endpoint only works when using Basic Authentication

### ISSUE THREAD

**Issue by ayoung** [IdentityServer/IdentityServer3#1552]
The [documentation](http://identityserver.github.io/Documentation/docs/endpoints/token.html) says that   you can _"either pass client id and secret via Basic Authentication or add client_id and client_secret fields to the POST body"_ but I've noticed that it only works with Basic Auth. Passing client_id and secret via form POST body returns 400 Bad Request.

```c#
var uriBuilder = new UriBuilder("https", HostName);
uriBuilder.Path = TokenEndpoint;

var requestData = new []
{
    new KeyValuePair<string, string>("grant_type", "authorization_code"), 
    new KeyValuePair<string, string>("client_id", ClientId), 
    new KeyValuePair<string, string>("client_secret", "secret"), 
    new KeyValuePair<string, string>("code", code), 
    new KeyValuePair<string, string>("redirect_uri", RedirectUri), 
};

var requestContent = new FormUrlEncodedContent(requestData);

var httpClient = new HttpClient();
// uncommenting the following works just fine
// var clientCredentials =
//    Convert.ToBase64String(Encoding.UTF8.GetBytes(String.Format("{0}:{1}", ClientId, "secret")));
// httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", clientCredentials);
httpClient.DefaultRequestHeaders.Accept.Clear();
httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

var response = await httpClient.PostAsync(uriBuilder.Uri, requestContent);
// response.StatusCode == 400
```

Something wrong with my sample code there?

**Comment by ayoung** [comment]
Looked at the source code and saw [this null check](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/ClientValidator.cs#L122) that could be forcing it to bypass Basic Authentication.

**Comment by leastprivilege** [comment]
I am pretty sure this works - have used it myself quite often. If not then this would be some regression.

Turn on logging to get more info.

**Comment by ayoung** [comment]
You're right. Not sure what the issue was there but I tried it again today and it worked.
