### ISSUE TITLE
User authentication by certificate on authorize endpoint

### ISSUE THREAD

**Issue by rhagh** [IdentityServer/IdentityServer3#1553]
I am trying to implement user authentication by certificate and encountered some problems. As per this   https://github.com/IdentityServer/IdentityServer3/issues/309#issuecomment-71623036 it could be done by using PreAuthenticateAsync.

My scenario: (server side) web application is configured to require SSL and require client certificate. Now I want to use e.g. authorization code flow and redirect user agent to authorization endpoint passing certificate via acr_values to identity server in order to evaluate/validate/etc it in PreAuthenticateAsync.

However handing it over via acr_values in GET request seems to be impossible due to size limit for this parameter (300?). So I tried sending the request as a POST (which should be possible as per http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), but getting back a '405 Method Not Allowed'.

Any hints? Thank you.

**Comment by leastprivilege** [comment]
You can't simply pass the cert as a parameter. There would be no cryptographic proof that you are really the owner.

You need to use the SSL protocol to give you the cert. In your user service PreAuthN reach into the OWIN environment to retrieve the certificate.

**Comment by rhagh** [comment]
Thanks, Dom. I always felt my approach passing via acr_values is not quite right ;-) Got it working now.
