### ISSUE TITLE
Primary authn cookie is deleted on a partial signin

### ISSUE THREAD

**Issue by pmhsfelix** [IdentityServer/IdentityServer3#1554]
I've observed that the primary signin cookie ("idsrv" cookie) is deleted even on a partial signin.
However, keeping the last authn session active would be useful, namely when the partial signin goal is to connect the new external identity to the current user account. 
For instance, the redirect after partial signin can be a resource where the user is asked if she wants to connect the new external id with the current active signin. This resource would use both the primary signin and the partial signin to implement this behavior.
Even if the user aborts the partial sign in flow, it would be useful to keep the previous primary one active.

Does this make sense or am I missing something here?

Thanks
Pedro

**Comment by brockallen** [comment]
Yes, makes sense. I can try to repo (or build a sample trying to do what you want) and see if it's something we can accomodate.

**Comment by pmhsfelix** [comment]
Added a PR (https://github.com/IdentityServer/IdentityServer3/pull/1555) to illustrate the changes on the authn flow.

**Comment by brockallen** [comment]
Ok, thanks. I'll have to think thru all the workflows to make sure we didn't miss anything.

**Comment by brockallen** [comment]
Merged, thanks Pedro.
