### ISSUE TITLE
Client secret validation does not work when HTTP Logging is turned on

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#1557]
problem with body consumption i think

**Comment by brockallen** [comment]
I tried to repro w/ the Console Client Credentials Flow w/ OAuth2Client.ClientAuthenticationStyle.PostValues and EnableHttpLogging = true but could not see a problem. Is that the wrong scenario?

**Comment by jlegan** [comment]
Brock,

See my other issue we were working the other day. I believe Dominick is reporting the same behavior I am seeing.

Thanks,

Jim

**Comment by brockallen** [comment]
Ok, the recent fix for #1533 seems to have addressed this.

**Comment by leastprivilege** [comment]
yep - working for me using the lastest myget package.
