### ISSUE TITLE
Question/Discussion : Single identity with multiple user accounts

### ISSUE THREAD

**Issue by aliozgur** [IdentityServer/IdentityServer3#1558]
IdentityServer3 really rocks and the code is fun and pleasure to read.Thank you @brockallen, @leastprivilege and all contributors for such a great implementation.

Recently we've successfully implemented IdentityServer3 in our university. But there are couple of things that might be improved.

Our setup is something like this

* We have an in-house developed Student Information System (SIS) which uses Forms Authentication
* We have more than 15 web applications inside SIS
* We have two AD domains. One for students and another one for academic and administrative staff
* Each student has a single identity on AD but may have multiple student accounts in SIS
* Each staff has a single identity on AD but may have an instructor and staff account in our SIS
* We have an in-house role based access control module. Roles are attached to accounts (actually person records) not identities.
* We use external providers (Google,Twitter, Microsoft and Facebook) for authentication as well. Users can pair their AD domain accounts with external provider accounts.

For authentication we use the post fix provided in the username to identify the correct AD the user will be authenticated from. After successful authentication we query our SIS to discover which accounts are paired to the authenticated identity. 

A sample identity/account information

> Username/Identity : ali@sample.edu
> Undergraduate Student Account Id : 103610059
> Graduate Student Account Id : 108600012

Our implementation generates the following claims

> sub : ali@sample.edu
preferred_username : ali@sample.edu
SisId : Student|103610059|111
SisId : Student|108600012|11111
**Rbac roles for 103610059**
RbacRole : 11|REG|CREATE
RbacRole : 11|REG|READ
RbacRole : 11|REG|DELETE
**Rbac Roles for 108600012**
RbacRole : 11111|UREG|CREATE
RbacRole : 11111|UREG|READ
RbacRole : 11111|UREG|DELETE

For SisId claim values we use this format **{UserType}|{AccountId}|{PersonId}**

For RbacRole claim values we use this format {PersonId}|{{Module/application Code}}|{{Role Code}}**

*SisId and RbacRole claims are controlled by scopes and we define list of valid scopes for clients.*

Once the user is authenticated we have an intermediate "Choose Account" page which
displays the SisId claims and forces user to choose an account to continue. 

Single identity multiple accounts is not a problem for our own clients because

1. All our SIS web apps still use Forms Authentication the only web application communicating with IdServer is our SIS authentication app. 

2. Our own api clients can provide the active account (in our sample data 103610059 or 108600012) information as HTTP headers and our Api knows the account which the client is acting upon

But for third party clients (api, web or mobile) this one identity multiple accounts situation can be an issue, because 
1. They will need to implement their own "Choose Account" view/page or mechanism
2. Need to persist the chosen account on their side and 
3. In case of an Api client make sure that they send the active account information using HTTP headers or whatever other mechanism we support 

I'm really interested to hear your suggestions about our scenario.

**Comment by brockallen** [comment]
I didn't quite follow all of your description, but in short we know that we've not implemented the ability to have more than one account login session with IdSvr at a time. It'd be nice to have multiple, but we've just not spent the time to think about how to support it (given that it makes everything more complicated). It's not that it couldn't be done, it's just a matter or the demand for such a thing, the current implementation (and trying not to make too many major breaking changes), and our time to implement such a feature.

**Comment by kylegalbraith** [comment]
I have a follow up question scenario that is very similar to this. We need to implement something like the above, where a user's account id could be associated with one or more project id's.

So we would have something like this
```
user: foo@zapproved.com
subjectId: 456-789-321
claims {
     projectId: 45
     projectId: 46
     projectId: 50
}
```
Similar to the original question, but it sounds like @aliozgur already accomplished this. I want the user to authenticate at IdSvr, but before the authenticate result is generated, I want them to choose the project they want to access. Once they choose one I want to form the claims associated with the access token to be that projectId so then I can get that projectId right off of the ClaimsPrincipal in my API.

1) Is this possible? It seems like this is similar to what @aliozgur accomplished.
2) What do I need to inject to get a page where the user selects the project on IdSvr?
3) Once they select a project can I craft the authenticate result?

**Comment by aliozgur** [comment]
This is not possible with IdSrv since this is kind of a Domain Specific requirement. To clarify what we implemented to cover this scenario

* We have more than 20 web apps running under same domain
* We had a single login app where we were handling the authentication and generating FormsAuthentication cookies required by our apps
* All this stuff is running in a load balancing configuration

What we did was
* We implemented IdSrv and moved all authentication staff there and implemented our own Client Store, Scope Store and User Service 
* We created a new web app (lets say AuthHub) which was acting as an Implicit client to IdSrv. We plugged OpenIdConnect middleware to this application 
* LoginUrl of all legacy web apps were replaced to point to an action method on AuthHub and we kept the FormsAuthentication staff. The point is all legacy apps are still using forms authentication
* AuthHub's main responsibility is
** Authenticate the user through IdSrv and receive claims
** Upon successfull authentication check if authenticated user (identity) has more than one user accounts (in your case this is projects)
** If user has multiple accounts Present a Choose Account page  (or Choose A Project Page in your case) to the user.
** If user has single account or chooses one from the list generate the FormsAuthentication cookies
** Redirect the user to the Main Portal where all application links are listed

In your case if you have a single application (Implicit client to IdSrv) you can implement a *Choose Project*  logic/page directly in your application instead of waiting this to be implemented by IdSrv. You can use the project id claims provided by IdSrv and may be perform more checks using these claims agains your database. Upon a choice you can store the chosen project id in the session or in a secure cookie (encrypted using the machine key or other encryption techniques)

You can then implement your owm AuthorizationManager (You can find an example how to do this in IdSrv documentation) in your application and check if the choosen project id exists among the cliams provided by IdSrv. You can implement  any other authorization logic within your custom AuthorizationManager

I hope all this stuff helps you :)

**Comment by kylegalbraith** [comment]
@aliozgur thank you for the quick and in depth feedback, I believe I am coming to a clearer picture of how to accomplish my task.

A little more clarity around what we are doing:
* The implicit client is a static angular app that is registered with IdSvr with the respective callbacks
* We make use of the oidc-token-manager that @brockallen has provided to everyone and it works great! So we use the token manager in the callback to validate the tokens, and we use it to know when to sign the user out, when they are expiring, etc.

So upon reading your feedback it seems that the following would need to happen on the static implicit client:
1. User logins in at IdSvr and an AuthenticateResult is generated with all of their claims
2. This is then sent back to the callback on the implicit client
3. The callback will validate the tokens
4. Now the callback will need to make some api call to check whether there is more than one **project id** claim
5a. If project id claim == 1, then go ahead and let the user into the app because they do not need to choose
5b. Else show the projects the user is apart of and have them choose one

It is at **5b**, where I am unsure what to handle next. What I would like to do, but am unclear whether it is possible or is even best practice, is transform the claims so that once the user enters the app they have one and only **project id** claim. Based on the link you provided, the section about **claims transformation** leads me to believe I can do this. 

But do I pass something back to IdSvr that says "hey this user will be in project x", and then have IdSvr generate a new authenticate result and pass it back to the callback to do the checking again? Essentially running steps 2-5a again.

**Comment by aliozgur** [comment]
@kylegalbraith i think you should not need to run steps 2-5a again. Ensuring only one and single project is a domain specific concern and you should handle this in you angular app not IdSrv. But if you want IdSrv to generate only one Project Id claim you can redirect the client to IdSrv including the selected project id as an AcrValue then modify your userservice on IdSrv so that if you receive a project id as an AcrValue then just create a single project id claim. But i think this implementation is more complicated and requires extra IdSrv calls.

By the way, AcrValues are how we handle external account ( twitter, google etc) validation in our current setup. I have attached our External account validation fragments to provide you an idea.

Note: I'm mobile so sorry for screenshots
![image](https://cloud.githubusercontent.com/assets/799194/9360654/1e2dd03e-46a0-11e5-88b5-17b2114ba4ce.jpg)
![image](https://cloud.githubusercontent.com/assets/799194/9360657/1e632fcc-46a0-11e5-9f46-0b8656ddfa42.jpg)

**Comment by kylegalbraith** [comment]
@aliozgur thank you again for the great feedback!

I do agree that the call back to IdSvr is likely overkill. But what I am trying to get at is the ability to just pull the **project id** off of the claims principal in my api. Therefore, I would need there to only be one project id claim when they land in the api. That said, there could be something else I am missing about managing it in the angular app that I am not understanding.

If I manage it in the angular app, then I likely have to pass it along with every api call. That seems a little less than ideal depending on how it is passed. But calling back over to IdSvr likely means I need to hit an endpoint in the user service that is not currently there to transform the claims and then give the authenticate result back. This seems messy as well as you said this is pushing domain specific things into IdSvr.

**Comment by aliozgur** [comment]
You may store the selected project id in client side storage, inject this value to every request ( angular has funky interception points for this) as a custom header, then imlement a asp.net web api message handler ( i assume you use asp.net web api) and extract projectid and inject the id to the context.

**Comment by kylegalbraith** [comment]
Yes we are using web api. I think this is certainly on the right track now, so here is the flow I think that will work:
* handle the **project id** in angular
* pass it along via an interceptor to the api in a request header
* catch request coming in via a message handler
* pull the **project id** out of the header and shove it in the request context

Now when the request hits the controller you in theory could have an action filter that checks the user has access to this project. The only question that remains for me is that a user could be in different roles on a project, so how can you go about handling that.

I believe you could probably handle this in the message handler, so you know what **project id** currently is. Then in the message handler can you get at the claims principal to get the 
```
role: project id|somerole
```

**Comment by aliozgur** [comment]
So you should generate roles per project claims instead of simple role claims. In practice you can put anything inside a Claim. We put roles per app, per account in our case, you can do the same for projects. I also want to emphasize that a custom AuthorizationManager is your best friend in this scenario which you will code to handle all these authz stuff

**Comment by kylegalbraith** [comment]
Yes I just realized I made a typo in the end of that post, I meant something like this:
```
projectId|role: somerole
```
When it comes to the AuthorizationManager, this is something that is configured within my web api correct? So if I include the nuget for ResourceAuthorization I should be able to write some custom handling to check that a user is in the right role for the right resource.

**Comment by aliozgur** [comment]
Yes, AuthorizationManager needs to be implemented in your WebApi (Client) and you need to add the NuGet.

**Comment by kylegalbraith** [comment]
@aliozgur I have been working on the Authorization Manager and have come across an issue I am unsure of. If I create a message handler to pull out the project id out of the request header and stuff it into the context, I do not seem to have access to it from ResourceAuthorizationContext in the Authorization Manager.

Therefore, how would I go out checking the role claims for a project id as mentioned above.
```
projectId|role: somerole
```

**Comment by aliozgur** [comment]
@kylegalbraith, good point. 
I think you can choose one of the two of options

1. Use the imprative approach mentioned in the [Mvc Getting Started](https://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html) OR
2. Consider injecting owin context to AuthorizationManager. There are resources describing different ways to do this. You can look at [this SO answer](http://stackoverflow.com/a/27826059/995957) 

My choice would be the first option

**Comment by kylegalbraith** [comment]
@aliozgur I agree it seems that imperative approach may work. But what are your thoughts on transforming the claims pricipal inside of the message handler, per this [SO](http://stackoverflow.com/questions/21417565/claims-auth-with-owin-self-hosted-webapi). This feels a little weird, but the goal would be to take the project id out of the header, find the claims that match that project id, recreate the principal, and then pass the message though the API.

**Comment by aliozgur** [comment]
I would give that approach a shot. 
Do you use IdentityServerBearerTokenAuthentication or OpenIdConnectAuthentication? If you use IdentityServerBearerTokenAuthentication that SO may will not probably work since IdentityServerBearerTokenAuthenticationOptions do not have any Notifications like OpenIdConnectAuthenticationOptions.

**Comment by kylegalbraith** [comment]
We are using IdentityServerBearerTokenAuthentication. Not sure I understand why the approach may not work in this case because of notifications. Seems we rebuild the ClaimsPrincipal, add it onto the request context, and then call the base.

**Comment by aliozgur** [comment]
Oh yes, you are right. You will just add claims transformation as a middleware. But i'm not sure how you can get the original idsrv claims with this approach.

**Comment by kylegalbraith** [comment]
Yes, I am not sure about getting the original idsvr claims as well. I will have to see what the principal looks like after they have passed through the message handler. Perhaps copy the claims to the new principal one by one (except for the extra claims you no longer need related to project id).

**Comment by leastprivilege** [comment]
we don't support that right now - maybe this will help

https://github.com/IdentityServer/IdentityServer3/issues/2388

**Comment by JoeBrockhaus** [comment]
@aliozgur Could you provide a more insight into how to best perform claims transformation when using IdentityServerBearerTokenAuthentication? I'm looking to make my AuthorizationManager code cleaner by pushing the responsibility of fetching external data into the pipeline.
