### ISSUE TITLE
Failed Authentication notification

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#1559]
I am looking to leverage a successful or failed authentication in my client app.  I can do this easily with successful authentication through the SecurityTokenValidated in the OpenIdConnectAuthenticationNotifications but I cant seem to be able to hit the AuthenticationFailed.  I am authenticating users through the AuthenticateLocalAsync method in IDS.  
Is it possible for the client to get notified of a failed login attempt or will I need to do this in my AuthenticateLocalAsync method?

**Comment by brockallen** [comment]
So you want to track failed username/passwords? This is more the job of your identity mangement library, and not so much the token service (although, of course, one is using the other).

**Comment by paddyhamilton** [comment]
Yeah, that's what I want to do Brock.  We currently have all the Identity management in the app, so the logon screen and authentication logic was there as well.  The plan is to have a separate identity management area in time but we are not there yet.  We now redirect users to the IDS login screen and validate them with a custom user service either externally or internally.  I really want the app to be informed of failed logons so as I can have the app track them.  If this is not possible I will just have the IDS service send the successful and unsuccessful logon attempts to our db as a short term fix.
What would be your recommended approach?
Cheers

**Comment by brockallen** [comment]
Yea, maybe that's what you'll have to do. I just don't know your environment well enough. Sorry.

**Comment by paddyhamilton** [comment]
No problem.  If it helps we have IDS set up as a website and our client is a website.  We have Owin middleware configured on the client to redirect users to Identity Server where the user can logon with an external provider (ADFS) or with a local login which is their specific credentials for the application.  If authenticated we intercept the info coming back (this is in our Client) in the Owin middleware SecurityTokenValidated method and add the claims and other info returned to an AuthenticationTicket.

Its in this method where I know that the authentication has been successful.  The problem arises when the login fails on IdentityServer I have no way in the client to know this.  I thought the AuthenticationFailed method on the Owin Middleware in the Client would notify me of a failed login from IDS and I could log it from there.  The reason I want to log it from the Client app is that users need locked out if they have more that 5 failed login attempts and currently all our management is in the app.

If my explanation is confusing don't worry about it and Ill close the issue :-)

**Comment by brockallen** [comment]
Again, IdSvr isn't doing the password check -- your code is. That's ultimately where you know. So then IdSvr won't know, and certainly your client app won't know either.

**Comment by paddyhamilton** [comment]
Ok, cheers. Thanks for your help.
