### ISSUE TITLE
AccessTokenValidation "token is missing"

### ISSUE THREAD

**Issue by Condor2708** [IdentityServer/IdentityServer3#1560]
I recently updated my code with IdentityServer/AccessTokenValidation from dev branch and IdenttityServer v3 rc1. I am getting "token is missing" with every request that I making to the WebAPI.

I am working with an SPA using Implicit Flow using OIDC.js library.

Someone could point me where I can take a look to solve the problem?

**Comment by brockallen** [comment]
You need to debug your app to find out why you have this error.

**Comment by Condor2708** [comment]
I remove IdentityServer/AccessTokenValidation (dev-branch) from my code and I've added Thinktecture.IdentityServer/AccessTokenValidation. Everything is working fine.
I don't know if it is a problem with the new version of AccessTokenValidation.

**Comment by leastprivilege** [comment]
What does "token missing" mean? The dev branch version of the clients sample uses the middleware and works fine. maybe diff - and open a more specific issue.
