### ISSUE TITLE
ViewService Normalization

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/IdentityServer3#1561]
In my custom view service I have implemented a strategy to theme/skin the various pages rendered by IdentityServer. What keeps biting me is some inconsistencies that may be intentional due to the OAuth/OIDC spec but I thought i would point them out in case others had an idea or possibly for normalization in 2.x.

There are 3 ways I determine which skin to render:

1) Tenant: I can pull this from the AcrValue and it works great for the login events and is exposed by SignInMessage.

2) Client: Some clients belong to a specific customer and as a result the skin is persisted and cached, this always works for customer specific clients but is not workable for the generic clients for our MVC apps that are utilized by many customers and across many vanity and sub-domains.

3) Return URL: Works for SignOutMessage as a fallback mechanism for the Client method. In the case of case of the generic apps which have a limitless number of possible vanity and sub-domains, this option allows me to pull it out of the URI.

I also noticed on the LogOut (not LoggedOut) which I only see when not passing in an IdTokenHint, the message is missing both the ClientId and ReturlUrl values though i believe they are supposed to be populated at that point.

**Comment by brockallen** [comment]
In the 2.0.0 branch we updated the various view service APIs to accept more info about which client is making the request. Not all views can know this, but we tried to make it available everywhere possible.

**Comment by jlegan** [comment]
Part of the confusion I am seeing is the following:

If you do not pass in an IdTokenHint, the user hits the logout (not loggedout) page where they are asked for confirmation. If you pass in an IdTokenHint (per the docs), the logout page is bypassed and the user is automatically logged out (loggedout). However the default behavior at the instantiation of the identityserver instance is EnableSignOutPrompt (true).

Is there a way to ever get to "logout" with and IdTokenHint? If not, what purpose does the SignOutMessage serve since the RedirectUrl and ClientId will always be null?

**Comment by brockallen** [comment]
You user could simply browse there?

**Comment by jlegan** [comment]
Fair enough :). I assumed (likely falsely) that the call to Request.GetOwinContext().Authentication.SignOut(); was going to the logout endpoint and that identity server was making the decision to not load the logout page but rather automatically log them out.
