### ISSUE TITLE
Renewing Identity Claims Per Client

### ISSUE THREAD

**Issue by aronblum** [IdentityServer/IdentityServer3#1562]
Hi,

My scenario is that I am using IdSrv as a SSO for a range of different clients. I have noticed that depending on which client calls IdSrv first, a different set of claims will get returned based on the Scopes that said client requested.

My issue is that each client has very different requirements and scopes that it uses.

is there any way to refresh the cookie that is created when first calling IdSrv, whenever a new client is used?

So for example, lets say Client 1 with scopes profile and email first accesses IdSrv, then Client 2 with scopes profile, email and phone is accessed. When Client 2 is accessed a new cookie is generated which also includes the phone scope.

Hopefully that made sense.

Thanks!

**Comment by leastprivilege** [comment]
Why do you need the cookie to be updated. The GetProfileDataAsync method in your userservice is responsib le to return the relevant claims. Not the cookie.

**Comment by aronblum** [comment]
Hi Dominick,

I was just assuming that it's the cookie I should be changing.

The problem I am having is once the first Client authenticates, no further
clients hit the GetProfileDataAsync method.

Do you have any suggestions as to what I can do to get further clients
hitting it?

Thanks.

**Comment by leastprivilege** [comment]
GetProfileDataAsync is called for every token request.

**Comment by aronblum** [comment]
So what you're saying is that for each successive client being accessed, a
new set of claims should be returned?

For some reason this isn't happening for me.

Only the first clients claims are returned during authentication. But no
others.

**Comment by leastprivilege** [comment]
Well - I can only repeat what I already said - 

GetProfileDataAsync is called for every token request.

This is how we retrieve the claims for the tokens. They must come from somewhere.

**Comment by aronblum** [comment]
Is it maybe that I'm not requesting tokens in the right way?

**Comment by brockallen** [comment]
Put a break point in your GetProfileDataAsync and re-run your token requests to see if it's getting executed.

**Comment by leastprivilege** [comment]
progress?

**Comment by aronblum** [comment]
Still no luck. After authentication, GetProfileDataAsync is not hit again. I thought it might have been because I was working in incognito mode, but that doesn't seem to be a factor.

**Comment by leastprivilege** [comment]
Have you turned on caching?

**Comment by aronblum** [comment]
I would have thought that using Chrome in Incognito mode would disable caching automatically?

**Comment by aronblum** [comment]
Even if I explicitly disable caching in Chrome dev tools, within Incognito mode, GetProfileDataAsync still only gets hit once, during authentication only.

**Comment by leastprivilege** [comment]
I mean caching in identity server

**Comment by aronblum** [comment]
Oh... is that on automatically? I haven't enabled any caching.

**Comment by leastprivilege** [comment]
Not on by default - 

so anyways - I can ensure you that we call GetProfileDataAsync for every token request - that's how we retrieve the claims.

How are you requesting tokens?

**Comment by aronblum** [comment]
Here is an example of one of my clients startups, using a hybrid approach.

            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
            AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "abb509d3-ffcc-409f-9d56-0f39a69f68e0",
                Authority = ConfigurationManager.AppSettings["IdentityServerAddress"] + "identity",
                RedirectUri = ConfigurationManager.AppSettings["BaseAddress"],
                SignInAsAuthenticationType = "Cookies",
                ResponseType = "code id_token token",
                Scope = "openid profile roles offline_access",
                UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = async n =>
                    {
                        var userInfo = await EndPointAndTokenHelper.CallUserInfoEndpoint(n.ProtocolMessage.AccessToken);
                        var givenName = new Claim(JwtClaimTypes.GivenName, userInfo.Value<string>("given_name"));
                        var roles = userInfo.Value<JArray>("role").ToList();
                        var newIdentity = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType,
                            JwtClaimTypes.GivenName, JwtClaimTypes.Role);

                        newIdentity.AddClaim(givenName);

                        foreach (var role in roles)
                        {
                            newIdentity.AddClaim(new Claim(JwtClaimTypes.Role, role.ToString()));
                        }

                        var tokenEndPointClient =
                            new OAuth2Client(
                                new Uri(ConfigurationManager.AppSettings["IdentityServerAddress"] +
                                        "identity/connect/token"), "abb509d3-ffcc-409f-9d56-0f39a69f68e0",
                                "fb7b0444-c311-42d3-a25d-4bbe2e03ded0");

                        var tokenResponse =
                            await
                                tokenEndPointClient.RequestAuthorizationCodeAsync(n.ProtocolMessage.Code,
                                    ConfigurationManager.AppSettings["BaseAddress"]);

                        var subjectClaim = n.AuthenticationTicket.Identity
                            .FindFirst(JwtClaimTypes.Subject);

                        newIdentity.AddClaim(new Claim("sub", subjectClaim.Value));
                        newIdentity.AddClaim(new Claim("refresh_token", tokenResponse.RefreshToken));
                        newIdentity.AddClaim(new Claim("access_token", tokenResponse.AccessToken));
                        newIdentity.AddClaim(new Claim("expires_at",
                            DateTime.Now.AddSeconds(tokenResponse.ExpiresIn).ToLocalTime().ToString()));

                        n.AuthenticationTicket = new AuthenticationTicket(newIdentity, n.AuthenticationTicket.Properties);
                    }
                }
            });

Do you see anything wrong with it?

**Comment by leastprivilege** [comment]
and what's the issue now? ;)

**Comment by aronblum** [comment]
Unfortunately it's still the same issue. I thought there might be something wrong in my startup which is causing it.

**Comment by leastprivilege** [comment]
I am really not sure what your problem is - you get the claims your ask for based on the scopes. Per request.

Maybe you need to debug and check the traces if you can spot anything that gives you a hint what's going wrong.

**Comment by vijay2358** [comment]
guys,
I am getting same.. when have same user in different clients.. we are not getting new claims for another clients.. even i requested from client  owin.Authentication.Challenge();.. 

i got found the reason - idserve has enabled cache - 

public Task SetAsync(string key, T item)
        {
            var expiration = UtcNow.Add(this.duration);
            cache.Set(key, item, expiration);
            return Task.FromResult(0);
        }
------------------------------------------------------

public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var key = GetKey(context.Subject, context.RequestedClaimTypes);
            context.IssuedClaims = await cache.GetAsync(key, async () =>
            {
                await inner.GetProfileDataAsync(context);
                return context.IssuedClaims;
            });
        }


how can i remove cache from server

 await cache.GetAsync(key, async () =>

**Comment by NigeB** [comment]
I know this is an old one, but thought it might help others.

The reason is all applications on your website are using the same session cookie (ASP.NET_SessionId), which has a root cookiepath. So, you log in with client 'A' and authenticate. Now you go to client 'B', hosted on the same server, and your browser faithfully send your session cookie back. As far as your client is concerned, you're already authenticated, and it gets the info from the cookie.

You need to set a different cookie name for each application, either in the CookieAuthenticationOptions passed to UseCookieAuthentication or in web.config.

Better would be to set the cookie path (also in CookieAuthenticationOptions), as then you wouldn't be sending needless cookies to every application, but then you'll run into all sorts of problems with case sensitivity as your browser won't send it if the path doesn't match the URL case exactly.

**Comment by LeeDumond** [comment]
**OMG THANK YOU @NigeB !!!**

This has been driving me insane for the better part of two days. Your solution saved me!

The problem is that all the samples and tutorials on the Internet only demonstrate using IdentityServer with a SINGLE client app. This works great, but as many have discovered, as soon as you start trying to implement it as an SSO for multiple clients, you see this "stuck claims" issue.

It would be really helpful if the tutorials made at least some mention of this.

Anyway, thanks again friend!
