### ISSUE TITLE
Is there any Filter Attribute that I can use to prevent accessing RestAPI without Bearer Token

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1563]
At RestAPI level we are using Thinktecture Bearer Token providers to Authorize using Bearer Token.
We customized and used System.Web.Http.AuthorizeAttribute to Authorize access to any RestAPI's. 
Is there any better way of preventing someone to access RestAPI with any bearer token?.

**Comment by leastprivilege** [comment]
Use the token validation middleware together with a global authorize filter.

**Comment by skatukojwala** [comment]
We are adding System.Web.Http.AuthorizeAttribute to global filter, is this good enough?.
Or Should we also add System.Web.Mvc.AuthorizeAttribute to the filters?.

**Comment by skatukojwala** [comment]
We are already using token validation middleware  and adding System.Web.Mvc.AuthorizeAttribute to the filters is this fine or should we me adding System.Web.Http.AuthorizeAttribute too?.

**Comment by leastprivilege** [comment]
.Web is for Web API
.Mvc is for MVC

**Comment by skatukojwala** [comment]
Sure Adding this is enough right?

**Comment by leastprivilege** [comment]
Are you using Web API or MVC?

**Comment by skatukojwala** [comment]
Web API.

**Comment by leastprivilege** [comment]
Then use the Web API one.

**Comment by skatukojwala** [comment]
Apologize! I am confused.  There are two versions 
System.Web.Mvc.AuthorizeAttribute
System.Web.Http.AuthorizeAttribute 

I am guessing System.Web.Http.AuthorizeAttribute is for WebAPI ?. 

Is there a third one System.Web.AuthorizeAttribute.
