### ISSUE TITLE
Requiring certain scopes for individual routes in an api

### ISSUE THREAD

**Issue by Otto45** [IdentityServer/IdentityServer3#1565]
In the Startup.cs file for my .net web api, I specify two different scopes that are allowed to access the api.  Is it possible to require one scope or the other for the individual action methods in my controller (api routes)?  The problem I'm trying to solve is allowing two different groups of clients to use the same api (using the client credentials flow), but only allowing one group to access a certain subgroup of the routes with their scope and vice versa for the other group of clients.  Or is this type of thing not allowed and I'll have to separate the routes into their own api's?  I'd rather avoid deploying two different api's if possible, as we have a limited amount of server resources.

**Comment by leastprivilege** [comment]
We have a scope attribute that you can put on controllers. If you want it per route - create a message handler that checks the scope claims and attach it to the route.

**Comment by Otto45** [comment]
What is the scope attribute called?  I can't seem to find it.

**Comment by leastprivilege** [comment]
Using the source is probably the easiest..

https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/master/source/WebApi.ScopeAuthorization/ScopeAuthorizeAttribute.cs

**Comment by Otto45** [comment]
Ah, I didn't realize it was in the .IdentityModel repository.  Thanks, this is exactly what I needed.
