### ISSUE TITLE
Update WsFederationAuthenticationOptions at runtime

### ISSUE THREAD

**Issue by IsdYann** [IdentityServer/IdentityServer3#1566]
First of all, thanks for the good job, it's really amazing.

I would like to use a different Federation provider depending on the client application.
If 2 apps are using 2 different Azure AD, I'd like to create/modify(?) the existing WsFederationAuthenticationOptions in IUserService.PreAuthenticateAsync or in RedirectToIdentityProvider event. Is it possible? What is the right place?
It seems I don't have enough information in PreAuthenticateAsync and it's maybe too late in RedirectToIdentityProvider event: at least I did not manage to make it work as I get an Azure AD error if I only change notification.ProtocolMessage.IssuerAddress and notification.Options.MetadataAddress.

Thanks!

**Comment by leastprivilege** [comment]
you would use the acr_values parameter - check the authZ endpoint docs

**Comment by IsdYann** [comment]
I was trying to make it work using WsFederationAuthenticationNotifications. Does it mean that it's not possible using WSFederation?

I tried with OpenIdConnect using acr_values and tenant but have 2 issues:
    . I had first to disable Issuer validation with TokenValidationParameters as I always got an IDX10205 error. What's a better way to fix this?
    . after that, the process always fails in LoginExternalCallback as context.GetSignInIdFromExternalProvider() returns null. But it's strange as if I come back to the MVC app and clicks on the About action, it works immediately, I can see all my claims. Maybe it's a problem with Redirect Uri as I only use STS urls in Azure AD App config. Do I need to use the MVC app url somewhere?

**Comment by IsdYann** [comment]
Please forgot my question about WSFed, I managed to make it work with this protocol using PreAuthenticateAsync instead of Notifications.
But still blocked with OpenIdConnect... same error. Even after having activated Multi-Tenant option in Azure AD.

**Comment by IsdYann** [comment]
After many tests, I still face the same issue, both with WSFed and OpenIdConnect.
I use common endpoints  i.e.
'MetadataAddress = "https://login.windows.net/common/FederationMetadata/2007-06/FederationMetadata.xml",' for WsFed and 'Authority = "https://login.windows.net/common/",' for OpenIdConnect.
Each time the browser is redirected toward my IdentityServer instance ('RedirectUri = "https://localhost:44334/callback"'), I get a *There is an error determining which application you are signing into. Return to the application and try again.* message. However, cookies are there as if  manually go back to the Relying Party, I can access [Authorize] actions. I  tried to set the tenant in acr_values to a valid tenant_id with no success.
Like written above, the issue comes from 'context.GetSignInIdFromExternalProvider()' in LoginExternalCallback  which returns null. Is it possible to use common endpoints and do you see any place where I could be wrong in my config?
Thanks!

**Comment by brockallen** [comment]
Sorry -- you have 2 different instances of the same middleware for external authentication? If that's the case, you need to ensure they're using two different callback paths. I can't tell if that's what the issue is or not.

**Comment by IsdYann** [comment]
Thanks Brock, in fact it started to mess up when I used 2 different middleware for external authentication. I restarted from scratch using WebHost Minimal sample and used Google OpenIdConnect to authenticate. It worked fine and things started to mess up when I added Azure AD OpenIdConnect. I used SetDefaultSignInAsAuthenticationType with CookiesAuthDefault and UseCookieAuthentication. Here I got the error.
After many tests, it seemed that Cookies authentication was useless as I finally managed to make it work using OpenIdConnect as default authentication.
I also had a configuration problem with my OpenIdConnectAuthenticationOptions as I tried to use "Cookies" for SignInAsAuthenticationType as I saw many samples with it instead of signInAsType parameter (idsrv.external). I've not found anything very clear about this in the doc, is there a place where I can find more info regarding "Cookies" auth and how it works?
Anyway, you can close the discussion as for now, everything works fine.
