### ISSUE TITLE
Consider making Windows authentication built-in

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#1567]
using a similar approach to this:

https://github.com/ghalebbadran/WinodwsAuthenticationOwinMiddleware/blob/master/GbSamples.OwinWinAuth/WinAuthenticationHandler.cs

but baked in.

**Comment by Condor2708** [comment]
+1

**Comment by leastprivilege** [comment]
not going to happen. use WindowsAuthentication service instead.
