### ISSUE TITLE
Performance issue with identity server authentication

### ISSUE THREAD

**Issue by robinkilpatrick** [IdentityServer/IdentityServer3#1569]
Hello,

We're seeing all calls to identity server taking upward of 2 seconds. I've run the service through ants profiler and got the callstack below but haven't managed to figure out what the underlying delay is. Do you have any suggestions on how we could go about tracking this down? 

![image](https://cloud.githubusercontent.com/assets/3949129/8501342/70e1e1fe-219c-11e5-93c5-7f0197644727.png)

Thanks,

Robin

**Comment by leastprivilege** [comment]
I would start by simplifying things - use the InMemory stores instead and see if anything changes.

**Comment by brockallen** [comment]
I can't tell anything form the pic you posted -- that's just the deep call chain of middleware. 

What you'd really need to do is wrap each of our services with a profiling implementation. That'd let you know where each call spends its time when it's in IdSvr.

**Comment by robinkilpatrick** [comment]
Thanks both for the suggestions! I added custom services as you suggested Brock and tracked the delays down to the cipher being used. Our PasswordHashingIterationCount is set to 50,000 on our MembershipRebootConfiguration and so the logins are taking 500-600ms to complete. From what I've been reading this is probably the intention? Does this seem correct to you, and is it something we should probably leave as is? Thanks

**Comment by brockallen** [comment]
Well, that number is up to you to decide based upon how long you can handle a login. If that's too slow, then change it accordingly.
