### ISSUE TITLE
Host IdentityServer3 in Windows Service

### ISSUE THREAD

**Issue by tracsorenson** [IdentityServer/IdentityServer3#1570]
I was planning to host IdentityServer3 within a Windows Service on one of our enterprise VM Servers (Windows 2008 Server) when I release to production.  Is anyone aware of any potential conflicts/incompatibilities with IdentityServer?  Of course, I will soon know of anything obvious as I test, but thought I would ask in case anyone has tried this already.

**Comment by leastprivilege** [comment]
That's a common deployment scenario.

**Comment by tracsorenson** [comment]
Thanks.
