### ISSUE TITLE
Redirect to login page after a partial signin redirect

### ISSUE THREAD

**Issue by pmhsfelix** [IdentityServer/IdentityServer3#1571]
After a partial signin redirect, we need to redirect directly to the login page and not the the resume endpoint. However, the partial identity only has the "partial_login_return_url" which points to the resume endpoint.
There is also a "partial_login_resume_id:{id}" containing the signinId, however I don't know if we can rely on that (seems a private IdSrv implementation detail)

The usage scenario is the following:
* User authenticates on an external IdP
* IdSrv is unable to match the external IdP to an account, so redirects to a registration page with the external id.
* The registration page shows the external identity and offers two options
  * start a registration flow based on the external id claims. At the end of this flow, we just redirect to the resume point to finish authentication
  * login with another IdP. For this we need to redirect back to the login page (with the signinId). If we redirect to the resume point, it will loop back to the registration page again.

Makes sense?

**Comment by leastprivilege** [comment]
we probably need something like a "login_restart_url"

**Comment by pmhsfelix** [comment]
Currently, I've address this issue by retrieving the signin Id using
```
   partialSignInClaims.Identity.Claims.First(c => c.Type.StartsWith("partial_login_resume_id")).Value
```
and redirecting back directly to the login page with `signin` set this id.
However, since I'm using undocumented behavior I'm afraid this might break in the future.

**Comment by brockallen** [comment]
added new claim and OWIN helpers on dev branch for this for partial login restart url

**Comment by pmhsfelix** [comment]
Thanks!
