### ISSUE TITLE
Microsoft.Owin.Security.DataProtection.DpapiDataProtector didn't work on mono

### ISSUE THREAD

**Issue by javagg** [IdentityServer/IdentityServer3#1573]
I'm trying to run selfhost (mininal) example using IdentityServer3 2.0.0-rc1 (with a little changes) on mono(already worked on win!), but it reports:
Error:  System.Reflection.TargetInvocationException
  Exception has been thrown by the target of an invocation.
Error:  System.TypeLoadException
  Could not load type 'Microsoft.Owin.Security.DataProtection.DpapiDataProtector' from assembly 'Microsoft.Owin.Security, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

According to this article(written in chinese)(http://beginor.github.io/2015/04/08/using-microsoft-owin-auth-middleware-with-mono.html), it says Microsoft.Owin.Security.DataProtection.DpapiDataProtector is dependent on System.Security.Cryptography.DpapiDataProtector which implementation use some win32 function on windows, so it can't work on mono currently.

**Comment by leastprivilege** [comment]
Dpapi does not work on Mono - you need to provide your own data protector.

**Comment by leastprivilege** [comment]
http://www.ryanmelena.com/2014/10/31/thinktecture-identityserver-v3-on-mono/
