### ISSUE TITLE
Assertion Grants

### ISSUE THREAD

**Issue by manfredsteyer** [IdentityServer/IdentityServer3#1574]
Hi,

is there an extension that implements the jwt assertion described in [1]?

When dealing with such scenarios, we need JWTs with multiple audiences that point to the client in the own security Domain as well as to the auth-server in the other security domain, as [2] states: "The assertion MUST contain an Audience that identifies the authorization server as the intended audience.".

Is there a way to add additional audiences for such scenarios? Or would you just ignore this detail of the spec?

Best Wishes,
Manfred

[1] http://self-issued.info/docs/draft-ietf-oauth-jwt-bearer.html#rfc.section.2.1
[2] http://tools.ietf.org/html/rfc7521

**Comment by leastprivilege** [comment]
You can implement the ICustomGrantValidator to deal with arbitrary incoming custom grant types. Outgoing access tokens only have a single audience. We use oauth scopes to specify an "audience".

**Comment by manfredsteyer** [comment]
Thx for this quick reply. That means one could just replace the cited check for a check against a specific scope that denotes that the token can be exchanged for another token. Did I get this right?

Wishes,
Manfred

**Comment by leastprivilege** [comment]
Well - there are 2 parts to it:

- the incoming assertion must have an audience that includes the authZ server. This is up to your custom grant validator to enforce or not
- the assertion request contains a scope parameter to define what scopes the outgoing access token should have

**Comment by manfredsteyer** [comment]
I see. Thx for your quick reply.
