### ISSUE TITLE
Get All Client Scopes in GetProfileDataAsync

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#1575]
Hello, i us IdSrv3 v2.0 and i create custom UserService and in GetProfileDataAsync i want to get from  ProfileDataRequestContext all the client scopes. i want to filter user claims by client id and scopes.

**Comment by leastprivilege** [comment]
The scopes are irrelevant at this point. You have access to the client though.

If you want more control over the claims you need to implement IClaimsProvider.
