### ISSUE TITLE
External provider Token Lifetime

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#1578]
When I log into my client with an external provider (in this case ADFS 2.0) I don't get the providers Access Token expiry time back.  I just get the client default.  How do I get the providers access token expiry time?

I am using ADFS 2.0 which doesn't support OAuth2 so I am not sure if this is the problem.

Also if you log into your client with an external provider does Identity Server update claims from the external provider when you request a new access token from the refresh token?

Cheers

**Comment by leastprivilege** [comment]
I don't follow - ADFS does not have access tokens.

You configure access and identity tokens per client.

Only one question per issue please.

**Comment by paddyhamilton** [comment]
Apologies I meant SAML token.  We have a multi tenanted application and I assumed, wrongly it seems, that we could use the Token expiry from ADFS or an external provider as the access token expiry as we have 1 client and filter the providers based on tenant in a custom view service.  I assume it doesnt make sense to do this?  Would it make sense for the provider to send a claim for expiry if they wish to do so?  
Sorry if I am not making much sense, but I am trying to understand it a bit better

**Comment by leastprivilege** [comment]
a SAML token is more like an identity token not an access token - and why do you want an external provider dictate the lifetime of tokens within your system?? This is more like a client setting.

IIRC there is no easy way to do that. But I guess would be possible by replacing the ITokenSigningService - but that's pretty low level.

**Comment by paddyhamilton** [comment]
Cheers Dominick. Currently Each tenant can set their own session timeouts for inactivity. We were going to use the token expiry on the external provider as this value if they log in externally.  We will need a rethink as this probably doesn't make sense. 
As always, thanks for your help
