### ISSUE TITLE
Two-Factor Authentication with Resource Owner

### ISSUE THREAD

**Issue by jraadt** [IdentityServer/IdentityServer3#1579]
I've implemented the resource owner flow using IdentityServer and AspNetIdentity and I have a web app that authenticates using that flow.  It works great except now I'd like to add two-factor authentication.  I followed the AspNetIdentity_2fa, but it seems resource owner flow doesn't support two-factor.  Line 421 of TokenRequestValidator.cs returns an invalid grant whenever I have a user that enables two-factor.

What I would like to do is if the user enters the correct credentials the IdentityServer returns a partial login.  The web app would then ask for the two-factor code and pass that back to the IdentityServer again to fully authenticate.  Is anything like this possible?

**Comment by leastprivilege** [comment]
Resource owner flow does not support that. You could build something like that using a custom grant.

**Comment by jraadt** [comment]
Ok.  I'm trying to think this through and it seems I have a couple options.

1) I could request a token using RO flow but with a limited scope.  With valid credentials the IdentityServer sends the two-factor code and the web ui gets a token with limited scope back.  The user enters the code they receive in the web ui and along with the token the web ui sends them to the auth server to verify the token.  The piece I'm not sure about here is sending the token and key to the IdentityServer and validating them, returning a new token with more scopes.

2) Leave IdentityServer with just standard RO flow.  When the web ui gets a valid token back, it kicks off the 2 factor auth itself without using the IdentityServer.  If the correct 2 factor code is entered (verified by the web ui app), the user is given the access token originally obtained from the IdentityServer.

3) Maybe I'm just using the wrong flow.  I figured RO was right since it's an internal system that I own/trust all the pieces.  I just need 2 factor auth as well.

Any thoughts or experience you have with this is greatly appreciated.  Thanks!

**Comment by leastprivilege** [comment]
Switch to implicit flow. That's what I would recommend.

**Comment by jraadt** [comment]
I was thinking about switching to Implicit flow.  I think that would do everything, but I was concerned about not having a client secret (since it's a web ui).  Alex Bilbie scared me from Implicit (http://alexbilbie.com/2014/11/oauth-and-javascript/).  But maybe those concerns are unwarranted with IdentityServer and adding two-factor auth?

**Comment by leastprivilege** [comment]
You can safely ignore that blog post ;)

**Comment by jraadt** [comment]
Ah good to know.  Thanks for the help!
