### ISSUE TITLE
Windows User Impersonation

### ISSUE THREAD

**Issue by illukarl23** [IdentityServer/IdentityServer3#1580]
Hi,
after successfully using your WindowsAuthentication repo with identityserver3, I would need to Impersonate this windows user on whos behalf i call the api for accessing resources. At this moment i map the windows user i get with an identityserver3 user. This step would be obsolete if i want to impersonate the windows user for testing purposes, how could i achieve this?

**Comment by leastprivilege** [comment]
I don't follow. You can only impersonate Windows users - and only if you have a Windows token for them.

**Comment by illukarl23** [comment]
What i need is to get the current logged in user that wants to access the resource with a simple Client without entering Credentials, get authenticated in the IdSrv against, a Windows User database (At this point I don't know what database) and access the resources with impersonation.

What I tried is to authenticate with your windowsauthentication, then I validate the windows token i get in IdSrv and if the token is valid, exchange the windows user with an InMemory IdSrv user so that i can access my api(without impersonation). 

Now i wanted to be able to access the api with impersonation and can't see what I should do, i don't know if its even possible. 
I'm sorry if the questions seem dumb, and i thank you very much for every answer i get

**Comment by illukarl23** [comment]
After a bit of research i learned that i need WindowsIdentity to impersonate, so i tried to convert Thread.CurrentPrincipal.Identity to a WindowsIdentity, but thats unfortunately not possible, after that, I read about S4UClient.UpnLogon and thought I could get a ClaimsIdentity from Thread.CurrentPrincipal.Identity and then convert it with S4UClient to an windowsidentity but thats not possible too (the casts are not possible because CurrentPrincipal is type of System.Security.Claims.ClaimsIdentity).
My Question would be now, what do i have to do, to change my caller/API_Request so that the CurrentPrincipal.Identity is of a different type that allows me to use Impersonation?

Thank you

**Comment by leastprivilege** [comment]
Yes you can only impersonate a WindowsIdentity.

The S4UClient allows you to create a WindowsIdentity from a UPN (bob@domain.com). But you need to jump through several hoops (install and configure the ClaimsToWindowsToken service, setup Kerberos constrained delegation with protocol transition, setup UPNs) etc.

**Comment by illukarl23** [comment]
Ok,
now the problem is that I can't use the S4Client because I get a type of System.Security.Claims.Claimsidentity(WIF4.5) and not Microsoft.IdentityModel.Claims.Claimsidentity(WIF3.0) as Thread.CurrentPrincipal.Identity, and it seems that it is not possible to mix WIF3.0 with WIF4.5. Can i force identityserver somehow to make the Request with an Microsoft.IdentityModel.Claims.Claimsidentity object or is there any other Solution you can think of?

Thanks

**Comment by leastprivilege** [comment]
S4UClient takes a string and return a WindowsIdentity. Not sure what you are talking about.

**Comment by illukarl23** [comment]
I'm sorry i was confusing something.
I now add a UPN claim (I get the UPN with UserPrincipal.FindByIdentity.UserPrincipalName) in the ClaimsIdentity that gets returned by your SubjectGenerator in your WindowsAuthentication Solution, with this Claim I then create with S4UClient a WindowsIdentity for this User.

Thank your for your help.
