### ISSUE TITLE
Regarding id token persistence in cookies

### ISSUE THREAD

**Issue by DivakarPM** [IdentityServer/IdentityServer3#1582]
Hi,

I have an AngularJS client with ASP.NET Web API on the server-side, After authenticating the user according to the helper library (https://github.com/IdentityModel/oidc-token-manager)  you are storing the id token in the local storage of the browser. But we are planning to keep it in cookies. Please suggest us which is the best place to store it.

**Comment by brockallen** [comment]
Why in cookies? You don't want the token sent back on every request implicitly -- you want to do it explicitly.

**Comment by DivakarPM** [comment]
Thanks Brock..
