### ISSUE TITLE
Custom user service GetProfileDataAsync(...) call issue

### ISSUE THREAD

**Issue by errno3** [IdentityServer/IdentityServer3#1583]
Hi,

we have implemented a custom user service in order to able to log in with AD and also DB users. Our client is a browser application (implicit authorization grant). The scopes we request are: openid, profile and customscope. we are redirected to the login screen (IdSrv) and after login and redirection to our application we saw that the TokenValidator is called and here the UserService.IsActiveAsync and the GetProfileDataAsync are called for the second time. 

<code>
public Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
        {
            using (var pc = new PrincipalContext(ContextType.Domain, activeDirectoryDomain))
            {
                using (var user = UserPrincipal.FindByIdentity(pc, IdentityType.SamAccountName, subject.Identity.Name))
                {
                    if (user != null)
                    {
                        var identity = new ClaimsIdentity();
                        identity.AddClaims(new[]
                        {
                            new Claim(Constants.ClaimTypes.Name, user.DisplayName),
                            new Claim(Constants.ClaimTypes.Email, user.EmailAddress)
                        });

                        foreach (var group in user.GetAuthorizationGroups())
                        {
                            identity.AddClaim(new Claim(Constants.ClaimTypes.Role, group.Name));

                            Debug.WriteLine(group.DisplayName + " " + group.Description);
                        }

                        if (requestedClaimTypes != null)
                        {
                            return Task.FromResult(identity.Claims.Where(x => requestedClaimTypes.Contains(x.Type)));
                        }

                        return Task.FromResult(identity.Claims);
                    }
                }
                return Task.FromResult<IEnumerable<Claim>>(null);
            }
        }

        public Task<bool> IsActiveAsync(ClaimsPrincipal subject)
        {
            using (var pc = new PrincipalContext(ContextType.Domain, activeDirectoryDomain))
            {
                using (var aduser = UserPrincipal.FindByIdentity(pc, IdentityType.SamAccountName, subject.Identity.Name))
                {
                    return Task.FromResult(aduser != null);
                }
            }
        }
</code>

Here we get an exception (ArgumentNullException) cause the Subject.Identity.Name is null. We compared calls to these methods (login vs. token validation) and that are different subjects. For example, At the second call of GetProfileDataAsync Identity.Name is null and there is only one claim of type "sub". What are we doing wrong? Are we missing something?

We are using EF extension for the IdentityServer for our scopes and clients. Here also a log:

<code>
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenValidator]: 07.07.2015 13:14:38 +00:00 -- Start access token validation
'iisexpress.exe' (Managed (v4.0.30319)): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'
The thread '<No Name>' (0x2d0c) has exited with code 0 (0x0).
The thread '<No Name>' (0x2eac) has exited with code 0 (0x0).
The thread '<No Name>' (0x25f0) has exited with code 0 (0x0).
The thread '<No Name>' (0xde8) has exited with code 0 (0x0).
The thread '<No Name>' (0x2bf8) has exited with code 0 (0x0).
LibLog Error: 0 : [2015-07-07T13:17:22.5701116Z] Level=Error, Kind=End, Category='System.Web.Http.Action', Id=00000000-0000-0000-5d00-0080050000f7, Operation=ReflectedHttpActionDescriptor.ExecuteAsync, Exception=System.ArgumentNullException: Value cannot be null.
Parameter name: identityValue
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Test.STS.Web.Services.DefaultUserService.IsActiveAsync(ClaimsPrincipal subject) in ...
</code>

Thanks for any help.

Regards

**Comment by Shamae** [comment]
Encountered a similar problem.
Try using the GetName-Method in IdentityServer.Core.Extensions.
So... subject.GetName() instead of subject.Identity.Name.
Hopefully this helps!

**Comment by errno3** [comment]
Hi Shamae,

thanks for the tip. Actually we did the same but without the extensions:

<code>
bool nameEmpty = !string.IsNullOrEmpty(subject.Identity.Name);
string name = !nameEmpty ? subject.Identity.Name : subject.Claims.Where(...).FirstOrDefault().Value; // becomes subject.GetName()

!nameEmpty ? IdentityType.SamAccountName : IdentityType.Name, name)
</code>

The IsActiveAsync works now with this small workaround. However, we get the problem as the GetProfileDataAsync is called cause there is no claim of type 'name'. There is only one claim and the type is sub (value: Guid).

Thanks

**Comment by errno3** [comment]
We tried to understand the workflow of the identityserver but we still have troubles with tokenvalidator tokens that don't have always a claim of type 'name'. For example, as soon as connect/userinfo controller is called, there are many claims but none of type 'name'. Not sure how to handle this...

Thanks for any help

**Comment by errno3** [comment]
We solved the problem with the missing 'name' claim in that we check whether claims of type 'nbf' and 'exp' are available in subject.Claims and if yes we make validation: now >= nbf && now < exp. Otherwise we try to get the name from subject and query AD in order to get the user. Not sure this is the right way to solve the issue,
