### ISSUE TITLE
Exception accessing permissions page

### ISSUE THREAD

**Issue by depl0y** [IdentityServer/IdentityServer3#1588]
When I try to go to the permissions page, after logging in, I get an error page.

https://gist.github.com/depl0y/30174702915d7f3e4ace

I use the EntityFramework to store data, by using `factory.RegisterOperationalServices(efConfig);`

This creates two tables in my database, where the `Consents` table is empty and the `Tokens` table contains two records, both are for 1 user, with the same ClientId and JsonCode values, only the `Key` value is different between those records.

If I delete one of those records from the table, the error still appears, but when I delete both records the permissions page does load normally.

I set my clients that they don't need to ask for consent after logging in. I am not sure posting content of my `Tokens` table is a good idea here, might contain information I don't want posted online.

This is in 2.0.0-pre,  not sure how to tag this for it

**Comment by brockallen** [comment]
Call stack?

**Comment by brockallen** [comment]
So did you check if you have duplicates? If so you perhaps should put constraints on those columns.

**Comment by brockallen** [comment]
Any update?

**Comment by depl0y** [comment]
Sorry about that. I just returned from my holiday. Will update this ticket this week when I have time to take a look at it.

**Comment by leastprivilege** [comment]
fix? close?
