### ISSUE TITLE
On login page, if username populated put focus in password field

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#1592]

**Comment by brockallen** [comment]
fixed on dev

**Comment by snothub** [comment]
Is there a setting for this? I'm not seeing password get focus even though there is a user name there.

**Comment by brockallen** [comment]
It should just happen -- is the username being filled in from the browser, or from our code?

**Comment by snothub** [comment]
The app populates it from the cookie idsrv.username I'd imagine. I don't have any auto-fill features on in the browser (Chrome, but tested FF as well)

**Comment by brockallen** [comment]
So the setting needs to be enabled in the AuthenticationOptions as well -- maybe that's it?

**Comment by snothub** [comment]
I'm not seeing anything about that in IdentityServer3/source/Core/Configuration/AuthenticationOptions.cs. RememberLastUsername is enabled of course, that's why the user name is in the cookie to begin with.

**Comment by brockallen** [comment]
So the problem is that the last username doesn't seem to be populating the model data sent back into the page? You will have to debug into that a little more.

**Comment by snothub** [comment]
Seems like there is something wrong with the focus-if condition for the password in [login.html](https://github.com/IdentityServer/IdentityServer3/blob/133ca7db31d94abcca55221559a301310ab4bbe6/source/Core/Services/DefaultViewService/PageAssets/login.html#L31). It checks model.username which is clearly populated since it outputs the value to the username input field.

```html
<div class="form-group">
    <label for="username">Username</label>
    <input required name="username" autofocus id="username" type="text" class="form-control" placeholder="Username" ng-model="model.username" maxlength="100">
</div>
<div class="form-group">
    <label for="password">Password</label>
    <input required id="password" name="password" type="password" class="form-control" placeholder="Password" ng-model="model.password" maxlength="100" autocomplete="off" focus-if="model.username">
</div>
```

**Comment by brockallen** [comment]
Perhaps a cached JS file then? See if you can find the code in the JS that sets the focus. IIRC I did it as a directive.

 

-Brock

**Comment by snothub** [comment]
Out of office now, but I tried in incognito mode with same result earlier.
That would rule out caching.
7. sep. 2015 4.58 p.m. skrev "Brock Allen" <notifications@github.com>:

**Comment by snothub** [comment]
Ah, forget it. I didn't update the html and js files correctly for some reason. What is the right way, btw? Removing and re-adding correct nuget package didn't do it, looks like. Now I wonder how many other things I might be missing in the client part.

**Comment by brockallen** [comment]
Oh, are you doing a custom view service? Yea, you should do some diffs on the assets to see what changed.
