### ISSUE TITLE
Custom Claims from AuthenticateResult shows up in idsvr cookie

### ISSUE THREAD

**Issue by fekberg** [IdentityServer/IdentityServer3#1593]
I've got an implementation of `IUserService` in which I've implemented `AuthenticateLocalAsync`. 

Once the resource owner authenticates, I return a new `AuthenticateResult` like the following:

```
var claims = new [] {
    new Claim(Constants.ClaimTypes.Email, "mail@filipekberg.se"),
    new Claim("clientId", message.ClientId)
};

return new AuthenticateResult("mail@filipekberg.se", "fekberg", claims);
```

The above is an example, imagine that I want to set a claim that is Client + User specific. This all works, the third party that uses the idsvr gets their specific Client + User specific claim in the access token.

**However,** here is where I get a bit confused. The same claims are added to the `idsvr` cookie on the idsvr. Which means that if the same resource owner/user authenticates with multiple third parties, idsvr will keep the last `clientId` claim from the last authentication in the cookie.

I can't really see that it's a potential issue, but it leads me to believe that I am doing something that I should not.

Any advice would be much appreciated.

**Comment by leastprivilege** [comment]
The id of the current client is automatically added to the tokens. Don't put it into the cookie.

**Comment by fekberg** [comment]
@leastprivilege It's just an example, I just saw that there's `IClaimsProvider` though, so I can add my custom User + Client specific claims to that instead.

**Comment by leastprivilege** [comment]
Yep - I recommend deriving from DefaultClaimsProvider and call base first.
