### ISSUE TITLE
older applications

### ISSUE THREAD

**Issue by usernameAlreadyTakenByMe** [IdentityServer/IdentityServer3#1594]
Is it possible to secure asp.net 3.5 web applications with identityserver?. This particular app is using old castle mvc engine.

**Comment by leastprivilege** [comment]
IdentityServer is separate from your application.

**Comment by usernameAlreadyTakenByMe** [comment]
Thanks for a quick response.
I know that it is a separate application but still you need to install a few dlls from nuget such as 
install-package Microsoft.Owin.Security.Cookies
install-package Microsoft.Owin.Security.OpenIdConnect 
in order to connect application with identityserver so the question is:
Is it possible to install them w/o upgrading project to newer versions of asp.net framework?

**Comment by leastprivilege** [comment]
3.5 does not support Katana.

The samples repo has a client sample (Form Post Manual) that shows how to connect to IdSrv without Katana.

**Comment by usernameAlreadyTakenByMe** [comment]
I will search for this form post sample. Thanks.
