### ISSUE TITLE
Skipping RP iframe in session management

### ISSUE THREAD

**Issue by pbujok** [IdentityServer/IdentityServer3#1595]
We are implementing session management so that we can have the single sign out in our application. We made it similar way you made your JavaScriptImplicitClient. There there is a slight difference though. In our implementation it isn't really convenient to use RP Iframe and we moved the code from check_session.html directly to the application (accually to the part which is shared across multiple applications in our infrastructure). This way we have only OP Iframe, that is used from open id client without using second frame. Please let me know if it's safe to skip this part of the implementation?

**Comment by brockallen** [comment]
Yea, that's probably fine. Read these for more info: 
http://openid.net/specs/openid-connect-session-1_0.html
http://openid.net/specs/openid-connect-logout-1_0.html

**Comment by pbujok** [comment]
Thank you for your responses. It's perfect news!
