### ISSUE TITLE
CallContext.LogicalSetData issue

### ISSUE THREAD

**Issue by refref** [IdentityServer/IdentityServer3#1597]
Hello,

i set some data to CallContext, which i want to use later in logging.

public class Startup
{
		public void Configuration(IAppBuilder app)
		{
			app.Use((env, next) =>
			{
				CallContext.LogicalSetData("somekey","somevalue");
				return next();
			});
                        ....		
                        app.UseIdentityServer(options);
               }
}

when i want to access this data later in Log method of my custom Logger using following statement, i get null:
CallContext.LogicalGetData("somekey");

This problem happens only with thinktecture. I use same procedure with another project, which also use owin, autofac, webapi staff, it works perfectly.

**Comment by brockallen** [comment]
I'd suggest putting your key/values into the OWIN environment instead.

**Comment by refref** [comment]
How can i access then owin environment from my logger?

**Comment by brockallen** [comment]
Inject the `OwinEnvironmentService` into your ctor.

**Comment by refref** [comment]
According to your documentation I should call following in my startup class:
LogProvider.SetCurrentLogProvider(new MyCustomLogProvider());

Logging documenation: http://identityserver.github.io/Documentation/docs/configuration/logging.html

How could possibly be injected OwinEnvironmentService in my logger? It is not generated by autofac in that case, or is there another way registerin LogProvider, so that injection works.

**Comment by leastprivilege** [comment]
Logproviders are not supported anymore in 2x.

**Comment by refref** [comment]
Well, if logproviders doesnt exist anymore, how can i register my custom logger? 
When will be 2x version available as nuget package on main repository, currently the latest version is 1.6.2.

**Comment by leastprivilege** [comment]
By using any of the liblog supported logging libraries. 

V2 Rc is already on nuget.

**Comment by brockallen** [comment]
Ah sorry -- my suggestion was if you were in our registration system. Yea, for v1.x the log provider is global so it'd not be able to get that per-request info. The event services do have access to per-request data, though.

**Comment by refref** [comment]
I am confused a little bit now. If I use v2.x, do i have access per-request data from my logger? If yes, can you provide me some sample code. 
Event service doesn't solve my issue, because all logs doesn't come from event service.
Thanks

**Comment by leastprivilege** [comment]
We don’t do anything special for that - so the answer is no. Maybe a logging library like SeriLog can accomplish that.

The logging is really only meant for development time so that a developer can get a realtime insight into the inner workings.  The logs contain sensitive data and we don’t want to encourage people to store that data.

For deployment / production use we recommend events.

— 
cheers
Dominick Baier


On 9 Jul 2015 at 09:01:48, refref (notifications@github.com) wrote:

I am confused a little bit now. If I use v2.x, do i have access per-request data from my logger? If yes, can you provide me some sample code.
Event service doesn't solve my issue, because all logs doesn't come from event service.
Thanks

**Comment by refref** [comment]
Back to my original question, why data set by CallContext.LogicalSetData is lost your webapi controllers, what could be special with thinktecture. I use exactly same mechanism in another project, it works.

**Comment by leastprivilege** [comment]
I don't know.

**Comment by josephgardner** [comment]
@refref were you able to solve this issue? We are having the same problem with the CallContext getting lost only when using idsvr3.
