### ISSUE TITLE
How to add a symmetric key to the RP?

### ISSUE THREAD

**Issue by LuisSanchez** [IdentityServer/IdentityServer3#1600]
I just took a look at the [previous issue](https://github.com/IdentityServer/IdentityServer2/issues/668) but I still cannot find a way to set to the relying party the signing key... I've check the Wiki but with no luck...

I'm using:

* Thinktecture.IdentityModel
* Thinktecture.IdentityServer3
* Thinktecture.IdentityServer3.AccessTokenValidation
* Thinktecture.IdentityServer3.WsFederation

I'm checking the relying party on the wiki but it creates an inconsistency when I'm also checking this so I'm a bit confused...

Is IdentityServer3 not supporting this property anymore?

Notes:
* I had this issue previously open on [identityServer2] (https://github.com/IdentityServer/IdentityServer2/issues/852) but it didn't seem the right place.
* Theres also a question on [StackOverflow](http://stackoverflow.com/questions/31280996/identityserver3-symmetric-key-issue-on-relying-party)
* I'm also checking the samples, but the only [RP example](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/SelfHost%20(InMem%20with%20WS-Fed)/SelfHost/Config/RelyingParties.cs) is not using JWT... Or maybe is it in someother place...

Any help will be apreciated, thanks in advance!

**Comment by leastprivilege** [comment]
We don't support symmetric signing keys for we-fed. That's actually pretty uncommon. 

Use a x509 cert instead.

**Comment by LuisSanchez** [comment]
Oh I see, sorry for my low knowledge on the area, but then, how could I be able to use symmetric keys with IdentityServer3 to secure the tokens? 

The problem is that the WCF Rest that is going to recieve the tokens has a JWT handler and it only supports JwtHashAlgorithm.HS256, JwtHashAlgorithm.HS384 and JwtHashAlgorithm.HS512.

What would be your recomendation in this matter?

Thanks in advance for your time!

**Comment by leastprivilege** [comment]
In that case was-federation would be the wrong technology anyways. As I said - we don't support symmetric key. 

Either implement your own signing (not recommended), upgrade the jwt handler, or use reference token (recommended).

**Comment by LuisSanchez** [comment]
Ok, I'm trying to implement a handler for the reference token on the WCF, but It seems that there are not much examples, there are tons for WebAPI, but sadly it's not my case, could I be missing an example for a reference token handler on a WCF Rest project?

**Comment by leastprivilege** [comment]
you simply call this endpoint 

https://identityserver.github.io/Documentation/docs/endpoints/accessTokenValidation.html

There is no sample besides our middleware for web api

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/blob/master/source/AccessTokenValidation/ValidationEndpointTokenProvider.cs

**Comment by LuisSanchez** [comment]
Perfect, I'm using the endpoint you provided, looks like it could be a good solution. 
I've been trying it and I got this structure:
{
    aud: "https://idsrv3.com/resources",
    iss: "https://idsrv3.com",
    nbf: "1436452491",
    exp: "1436456091",
    client_id: "carbon",
    scope: "api1",
    sub: "bob",
    amr: "password",
    auth_time: 1436452491,
    idp: "idsrv"
}

Is there a way I can use some of this information to manually set it as a Claim and IClaimsPrincipal Object? Because, ok, the token is valid, then, what can I do with this info on my WCF project? So I wanna try to create a Claims Object (but maybe I'm thinking this all wrong)...

I have one last question, for what I understand, a Reference Token is one that keeps most if it's info on the server, but I cannot find more info about it, does it behaves like a SWT, obviously is not a SAML, but then, what it is? A structure create by the identity server? 

Sorry for my lack on knowledge in this area and thanks for your help and time!

**Comment by leastprivilege** [comment]
Yes - these are the claims - create a claims principal from them and set it. In WCF you need to do that in a ServiceAuthorizationManager and set principalPermissionMode to Custom.

**Comment by LuisSanchez** [comment]
Sorry for the long time without answering this post, this is the custom authorization that I had to implement on my WCF, hope it helps someone else:

	public class ValidateToken : ServiceAuthorizationManager
    {
        private static JavaScriptSerializer jsonSerializer = new JavaScriptSerializer();

        public override bool CheckAccess(OperationContext operationContext)
        {
            HttpRequestMessageProperty httpRequestMessage;
            object httpRequestMessageObject;

            if (operationContext.RequestContext.RequestMessage.Properties.TryGetValue(HttpRequestMessageProperty.Name, 
                                                                                      out httpRequestMessageObject))
            {
                httpRequestMessage = httpRequestMessageObject as HttpRequestMessageProperty;
                if (string.IsNullOrEmpty(httpRequestMessage.Headers["Authorization"]))
                {
                    return false;
                }

                if (!httpRequestMessage.Headers["Authorization"].StartsWith("Bearer "))
                {
                    return false;
                }
                
                string requestToken = httpRequestMessage.Headers["Authorization"].Split(' ')[1];
                if (string.IsNullOrEmpty(requestToken))
                {
                    return false;
                }

                // A successful response will return a status code of 200 and the associated claims for the token. 
                // An unsuccessful response will return a 400 with an error message.
                // It is also possible to pass a scope that is expected to be inside the token:
                // GET core/connect/accesstokenvalidation?token=<token>&expectedScope=calendar

                var client = new HttpClient();
                var json = client.GetStringAsync("https://localhost:44333/core/connect/accesstokenvalidation?token=" + requestToken);

                var headerData = jsonSerializer.Deserialize<Dictionary<string, object>>(json.Result);
                var claims = headerData.Where(kv => kv.Value != null)
                                       .Select(c => new Claim(c.Key, c.Value.ToString())).ToList();

                claims.Add(new Claim(ClaimTypes.Name, GetClaimWithFallback(claims, "name", "sub")));
                IClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(new ClaimsIdentity[] { new ClaimsIdentity(claims) });
                
                SetPrincipal(operationContext, claimsPrincipal);

                return true;
            }

            return false;
        }

        private string GetClaimWithFallback(IEnumerable<Claim> claims, params string[] claimTypes)
        {
            foreach (var claimType in claimTypes)
            {
                if (claims.Count(c => c.ClaimType == claimType) > 0)
                {
                    return claims.SingleOrDefault(c => c.ClaimType == claimType).Value;
                }
            }

            return null;
        }

        private void SetPrincipal(OperationContext operationContext, IClaimsPrincipal principal)
        {
            var properties = operationContext.ServiceSecurityContext.AuthorizationContext.Properties;

            if (!properties.ContainsKey("Principal"))
            {
                properties.Add("Principal", principal);
            }
            else
            {
                properties["Principal"] = principal;
            }
        }
    }

And the markup on the web.config is:

	<behavior name="customValidation">
	  <serviceMetadata httpGetEnabled="true" />
	  <serviceDebug includeExceptionDetailInFaults="true" />
	  <serviceAuthorization principalPermissionMode="Custom" 
							serviceAuthorizationManagerType="WcfIS3.ValidateToken, WcfIS3" />
	</behavior>
	
	...
	
	<endpointBehaviors>
	<behavior name="WcfIS3.RestBehavior">
	  <enableWebScript />
	</behavior>
	</endpointBehaviors>
	...
	
	<service name="WcfIS3.Service1" 
		   behaviorConfiguration="customValidation">
	<endpoint address="" 
			  behaviorConfiguration="WcfIS3.RestBehavior" 
			  binding="webHttpBinding" 
			  contract="WcfIS3.IService1" />
	</service>
