### ISSUE TITLE
/connect/accesstokenvalidation and CORS

### ISSUE THREAD

**Issue by vincenzo-antolini-os** [IdentityServer/IdentityServer3#1603]
Hi,
the endpoint
```
/connect/accesstokenvalidation
```
does not expose CORS headers (Access-Control-Allow-Origin...)
is it by design?

Thanks in advance.
V

**Comment by leastprivilege** [comment]
Yes - there is no reason why a JS client would want to validate an access tokens. JS apps are clients - not resources.
