### ISSUE TITLE
Question: Custom User Claims

### ISSUE THREAD

**Issue by kiran-mahadev** [IdentityServer/IdentityServer3#1604]
Hi,

I'm a newbie to security. I seek your guidance.

Some background for my question:
For each module in the application, a user can have read, write (that includes read as well) or none as privilege. So, I see this 'privilege' can be added as a Custom Scope and modules like module1, module2 (and so on)  can become Custom Scope-Claims. In that case, User-Claims can have reading that infer something like, user1 has only read privilege to module1 and the same user1 has write privilege to module2 but has no privilege for module3, etc.

In the database, we script in predefined set of module names into a table called 'privileges'.

Questions:
1. Does the above requirement description make 'privilege' a sound 'Scope' candidate?
2. if answer to question 1 is 'yes', What would be the best way to handle CRUD operations on User-Privileges, because each time there is a change to the User's privilege, the User-Claims will need to be updated accordingly?

Also, I plan to use the 'privilege' claim to control API access.

**Comment by leastprivilege** [comment]
Claims describe the identity of the user - not permissions or privileges.

You would rather handle that in your application.

**Comment by kiran-mahadev** [comment]
Thanks Dominick!
