### ISSUE TITLE
WSFederation Authenticate with multiple adfs servers

### ISSUE THREAD

**Issue by rowdyy1960** [IdentityServer/IdentityServer3#1605]
I have my identity server configured and running well. The only real issue I'm seeing right now is with wsFederation to two adfs IDP's. I have a configuration like this (real names replaced):

            var adfs = new WsFederationAuthenticationOptions
            {
                
                AuthenticationType = "adfs",
                CallbackPath = new PathString("/identityservices/identity/devadfs"),
                Caption = "domain.dev",
                SignInAsAuthenticationType = signInAsType,
                MetadataAddress = "https://adfs.domain1.dev/federationmetadata/2007-06/federationmetadata.xml",
               
                Wtrealm = "https://tfwbit-ids01.domain.dev/identityservices/identity",
                Wreply = "https://tfwbit-ids01.tfs.domain.dev/identityservices/identity/devadfs"
            
            };

            app.UseWsFederationAuthentication(adfs);

            var ccadfs = new WsFederationAuthenticationOptions
            {
                Wreply = "https://tfwbit-ids01.tfs.domain.dev/identityservices/identity/ccadfs",
                CallbackPath = new PathString("/identityservices/identity/ccadfs"),
                AuthenticationType = "ccadfs",
                Caption = "domain.prod",
                SignInAsAuthenticationType = signInAsType,
                MetadataAddress = "https://adfs.domain.prod/federationmetadata/2007-06/federationmetadata.xml",
                Wtrealm = "https://tfwbit-ids01.domain.dev/identityservices/identity"
                           };

            app.UseWsFederationAuthentication(ccadfs);

Signing in everything works just perfectly. However when I perform the signout function the the wreply returns as a 404 because the callbackpath url doesn't really exist. However, I had to configure the wsfederation endpoint trusted URL using the callback path or the signin functions won't work. Any Suggestions or ideas?

![image](https://cloud.githubusercontent.com/assets/11460347/8604435/2a3f171a-2644-11e5-8c7d-056581b5fe9e.png)

**Comment by leastprivilege** [comment]
You don't need to set the wreply. Just make sure that the callback path is in sync with the WS-Fed endpoint URL you configure in ADFS.

**Comment by rowdyy1960** [comment]
Ok Thanks. I was hoping to get adfs to go back to the identity server after logout. Right now it just sits on the adfs logout page. I was hoping the wreply would solve that problem.

**Comment by brockallen** [comment]
@rowdyy1960  so are you all set then, or do you still have an issue?

**Comment by rowdyy1960** [comment]
I am moving on to other parts of the implementation. Thanks for the assistance
