### ISSUE TITLE
Conditional IdentityProviders and Local Login options

### ISSUE THREAD

**Issue by jstrawther** [IdentityServer/IdentityServer3#1607]
I am hosting an IdentityServer3 instance that's configured for a couple of external authentication providers, and have a client web app (asp.net mvc) that uses the idSvr for authentication.  A new requirement is to differentiate between two different user types (tenants?) in the client app.  One group of users will only see the external authentication providers on the login page.  The other group of users will only see local login/password on the login page.  I'm looking for suggestions on a good approach to this.

Ideas so far:  

A) In the client app, serve 2 separate login controller actions, and in OpenIdConnectAuthenticationNotifications.RedirectToIdentityProvider notification, inspect the request URI and send the appropriate tenant name in the ProtocolMessage.AcrValues ("tenant:name") depending on which login action is used.  In IdSvr UserService.PreAuthenticateAsync method, put the tenant in the Per-Request OwinContext for easy access, and implement an IViewLoader that inspects the OwinContext and loads one of two custom login views depending on which tenant is specified.  

B) Host separate IdSvrs - one for local auth and another for external auth, and (somehow?) dynamically select the OpenIdConnect Authority in the client web app based on which login route is specified.  Perhaps this could also be done in the OIDC RedirectToIdentityProvider notification.

I'm curious about implications of either of these approaches, or whether there's a better one that i'm overlooking..

Thanks for your time.

**Comment by leastprivilege** [comment]
Use two different client ids.

**Comment by jstrawther** [comment]
Interesting!  I see now that I can configure EnableLocalLogin on a per-client basis, and that I can enter identity provider restrictions per-client as well.  I will try this out.  Thanks very much.

**Comment by jstrawther** [comment]
I'm wondering if i'm using the right approach to switch between ClientIds.  Everything seems OK until the http request comes back to the alternate, non-default ClientId.  The user is not authenticated.  If i inspect the cookies, the nonce is still present, and there is no cookie indicating successful login. When the request comes back from the default ClientId, the user is authenticated and the cookies look good. 

Is there anything special that I need to do in the client app to switch clientIDs dynamically?  Here's what i've got.  

Notifications = new OpenIdConnectAuthenticationNotifications 
                { 
                    RedirectToIdentityProvider = n =>
                        {
                            if (n.Request.Uri.ToString().Contains("/Login/Vendor"))
                            {
                                n.Options.ClientId = ConfigurationManager.AppSettings["EVendorPortalClientId"];
                                n.Options.RedirectUri = ConfigurationManager.AppSettings["EVendorPortalRedirectUri"];
                            }
                            else
                            {
                                n.Options.ClientId = ConfigurationManager.AppSettings["PortalClientId"];
                                n.Options.RedirectUri = ConfigurationManager.AppSettings["PortalRedirectUri"];
                            }
                            n.ProtocolMessage.ClientId = n.Options.ClientId;
                            n.ProtocolMessage.RedirectUri = n.Options.RedirectUri;
                            return Task.FromResult(0);
                        }
                }

Thanks so much.

**Comment by jstrawther** [comment]
Found the solution.  Changing the RedirectUri in RedirectToIdentityProvider Notification seems to cause problems with Katana, so I removed that part and only set the ClientId dynamically.  This causes an exception to be thrown when Jwt token validator tries to validate the audience, so i also needed to configure the TokenValidationParameters.ValidAudiences property to allow both of my ClientIds. 

Working version:

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = ConfigurationManager.AppSettings["IdentityServerUrl"],
                RedirectUri = ConfigurationManager.AppSettings["DefaultRedirectUri"],
                ClientId = ConfigurationManager.AppSettings["DefaultClientId"],
                ResponseType = "id_token",
                SignInAsAuthenticationType = "Cookies",
                Scope = "openid profile email phone address",
                BackchannelCertificateValidator = new AlwaysTrueCertificateValidator(),
                Notifications = new OpenIdConnectAuthenticationNotifications 
                { 
                    RedirectToIdentityProvider = n =>
                        {
                            n.Options.TokenValidationParameters.ValidAudiences = new List<string>() 
                                {  
                                    ConfigurationManager.AppSettings["DefaultClientId"], 
                                    ConfigurationManager.AppSettings["AlternateClientId"] 
                                };

                            if (n.Request.Uri.ToString().Contains("/Login/Vendor"))
                            {
                                n.ProtocolMessage.ClientId = ConfigurationManager.AppSettings["AlternateClientId"];
                            }
                            else
                            {
                                n.ProtocolMessage.ClientId = ConfigurationManager.AppSettings["DefaultClientId"];
                            }
                            return Task.FromResult(0);
                        }
                }
            });

**Comment by senj** [comment]
This is great! For the authorization code flow, I had to add the following:

```C#
AuthorizationCodeReceived = async n =>
{
                        // use the code to get the access and refresh token

                        if (new Uri(n.AuthenticationTicket.Properties.RedirectUri).AbsolutePath == "/Home/Contact")
                        {
                            ClientId = "testid";
                        }
                        else
                        {
                            ClientId = "mvc";
                        }

                        TokenClient tokenClient = new TokenClient(
                            IdentityServerUrl + "/connect/token",
                            ClientId,
                            ClientSecret);
}
```
