### ISSUE TITLE
Extend EntityFramework.Entities.Client

### ISSUE THREAD

**Issue by KautskyLozanoV** [IdentityServer/IdentityServer3#1609]
I was wondering how would I extend the Client class using EF. I would like to add some other propeties to this entity.

Any help would be appreciated.

**Comment by brockallen** [comment]
You can do that in your store implementation.

BTW, what sort of additional data are you looking for?

**Comment by KautskyLozanoV** [comment]
Ok, So I have to implement IClientStore interface but, it is tied to the Client class on Core.Models.
I think that Interface should use generics. Correct me if I'm wrong.
Ah! I want to add a creation date to the client and users

**Comment by brockallen** [comment]
I just don't see IdSvr making everythign generic on the type you want to use in your DB. IdSvr needs certain data -- you don't have to use IdSvr's classes as entities. You just need to map to them. If you need those extra values in your code running inside of IdSvr, then either downcast, or inject your custom DbContext and re-query (presumably you'll have a per-HTTP request instance in the SI system).

I feel like I'm missing something.

**Comment by KautskyLozanoV** [comment]
Ok, I'll go with the downcasting. I think it was me who was missing something.
Thanks for the help.
