### ISSUE TITLE
Getting 401 anauthorized when calling webapi.

### ISSUE THREAD

**Issue by usernameAlreadyTakenByMe** [IdentityServer/IdentityServer3#1611]
I have a project with asp.net mvc 5 implementation of identity server and a asp.net mvc 5 client in separate project also a webApi in separate project. All hosted on local iis with https enabled and generated developers certificate. Im not using roles in my project just a simple login with using custom user service custom login.html page and mvc razor views for changing passwords and other forms of authentication. And everytihng works fine. But i can't secure webapi in any way. 

This is a client which i use for webapi:

new Client
                {
                    Enabled = true,
                    ClientName = "MVC Client (service communication)",
                    ClientId = "service",
                    ClientSecrets = new List<ClientSecret>
                    {
                        new ClientSecret("secret".Sha256())
                    },

                    Flow = Flows.ClientCredentials
                }

webapi startup config:

public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://myhostname/MvcIdentityServer/core",
                RequiredScopes = new[] { "sampleApi" }
            });

            // web api configuration
            var config = new HttpConfiguration();
            config.MapHttpAttributeRoutes();

            app.UseWebApi(config);
        }
    }

mvc server scope:

new Scope
                    {
                        Enabled = true,
                        Name = "sampleApi",
                        Description = "Access to a sample API",
                        Type = ScopeType.Resource
                    }

identityserver config:

public void Configuration(IAppBuilder app)
        {
            LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());
            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;

            app.UseStaticFiles(new StaticFileOptions
            {
                RequestPath = new PathString("/core/content"),
                FileSystem = new PhysicalFileSystem("Content")
            });

            app.Map("/core", coreApp =>
                {
                    var factory = InMemoryFactory.Create(
                        users:   Users.Get(),
                        clients: Clients.Get(),
                        scopes:  Scopes.Get()
                        );
                    var userService = new TancodePartialLoginService();
                    var viewOptions = new DefaultViewServiceOptions();

                    viewOptions.Stylesheets.Add("~/Content/Site.css");
                    viewOptions.Stylesheets.Add("~/Content/Login.css");
                    
                    factory.UserService = new Registration<IUserService>(resolver => userService);
                    factory.ConfigureDefaultViewService(viewOptions);

                    var idsrvOptions = new IdentityServerOptions
                    {
                        SiteName = "Identity Server",
                        Factory = factory,
                        RequireSsl = true,
                        SigningCertificate = Cert.Load(),
                        CorsPolicy = CorsPolicy.AllowAll,

                        AuthenticationOptions = new AuthenticationOptions
                        {
                            //IdentityProviders = ConfigureIdentityProviders,
                            EnableSignOutPrompt = false,
                            EnablePostSignOutAutoRedirect = true,
                            PostSignOutAutoRedirectDelay = 40
                        },

                        LoggingOptions = new LoggingOptions
                        {
                            EnableHttpLogging = false, // true breaks mvc
                            EnableWebApiDiagnostics = true,
                            IncludeSensitiveDataInLogs = true
                        },

                        EventsOptions = new EventsOptions
                        {
                            RaiseFailureEvents = true,
                            RaiseInformationEvents = true,
                            RaiseSuccessEvents = true,
                            RaiseErrorEvents = true
                        }
                    };
                    coreApp.UseIdentityServer(idsrvOptions);
                });
        }

And client webapi calls:

[Authorize]
        public async  Task<ActionResult> Contact()
        {
            var response = await GetTokenAsync();
            var result = await CallApi(response.AccessToken);

            ViewBag.Json = result;
            return View();
        }
        
        private async Task<TokenResponse> GetTokenAsync()
        {
            var client = new OAuth2Client(
                new Uri("https://myhostname/MvcIdentityServer/core/connect/token"),
                "service",
                "secret");

            return await client.RequestClientCredentialsAsync("sampleApi");
        }

        private async Task<string> CallApi(string token)
        {
            var client = new HttpClient();
            client.SetBearerToken(token);

            var json = await client.GetStringAsync("https://myhostname/Api/identity");
            return JArray.Parse(json).ToString();
        }

If i remove authorize attribute from webapi method then i can get information from webapi. Also a gettoken async method is retriving the token and setting it as bearer in request header so the only problem is with webapi.

**Comment by leastprivilege** [comment]
compare with: 
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/SampleAspNetWebApi
