### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by usernameAlreadyTakenByMe** [IdentityServer/IdentityServer3#1613]
I have a questions about a localization. Identity server has it's own resource files. So if i add for example messages.de.resx i would be able to view messages in german. But i need a custom view for login page and on this page i would need a few buttons with change language method. And there are few things i would like to know:
1. Is there a cookie or session in identity server which contains culture value (which i would have to modify) and if there is some, where and how i can access it.
2. Is there a way to avoid using javascript functions to show translated items on custom login or logout pages.

**Comment by brockallen** [comment]
Localization is from 2 places: 1) messages from code and 2) html files. You can localize the messages via the `ILocalizationService` or check out the localization contrib project: https://johnkors.github.io/IdentityServer3.Contrib.Localization/#/. You can localize the html via a custom `IViewService`. To determine the browser's accept-language header your custom code can have the `OwinEnvironmentService` injected into it.

**Comment by usernameAlreadyTakenByMe** [comment]
Thanks for a quick answer. Sooo i would go with localization and view service there are samples so i would manage. Just one more thing. I'm still in need of a buttons changing language on the site so i would probably do it all in javascript and i will need to get to identityserver's session to change the language on button click.

**Comment by brockallen** [comment]
If you want to associate a locale with a user that they choose, then a persistent cookie is about the best thing I can think of (since half of the time when they come to the site they will be anonymous).

**Comment by usernameAlreadyTakenByMe** [comment]
Cool one last thing how can i inject OwinEnvironmentService  to localization and view services?

**Comment by leastprivilege** [comment]
by adding it to your constructor.
