### ISSUE TITLE
Active Directory providers redirecting based on user name

### ISSUE THREAD

**Issue by ltraus** [IdentityServer/IdentityServer3#1615]
So, one thing that i'm playing around with is i have a product line i want to integrate with the IdSrv.  But it has a horrible IF then else statement embedded in the logon code.

Checks the local user store for Role Type staff, and then tries to authenticate with some 5 yr old code with AD.  I think it'd be cool based on the provider type, that if you type @sitedomain.net that it would recognize that it needs to go to a certain AD and perform an external logon.

Is that possible with the current stack i don't see any concept of it, so i consider it a no no.  (The way Office 365 works with corporate accounts).

**Comment by brockallen** [comment]
This is called "home realm discovery". IdSvr allows you to handle this however you want. But it's still up to you to solve this fundamental problem.

**Comment by ltraus** [comment]
Ok, I'll have more of a poke around i couldn't see it.  But i have a few ideas how to do this now.  I swear i just couldn't think of what it was called... little hard to do research when you don't know what to search for :)
