### ISSUE TITLE
Shared login / registration pages

### ISSUE THREAD

**Issue by pinnprophead** [IdentityServer/IdentityServer3#1618]
I'm creating a "IdentityService" using IdentityServer and ASP.NET Identity.

Everything is working well: I can login using ASp.NET Identity or one of several third party services, such as Google and Facebook.  IOW, I can log into the service itself and access admin functions, etc.

If I hit the identity URLs, I can log in there and it goes against the same ASP.NET Identity database for login, however it uses the embedded login and registration pages.

What I'm wondering, is there a way to tell IdentityServer to use the same login and registration pages that ASP.NET Identity is using rather than the embedded views/controllers?

Thanks for the great work!

-Peter

**Comment by brockallen** [comment]
Yes -- check the docs and sample.
