### ISSUE TITLE
IIS Multibinding causes automatic IssuerUri to take random name

### ISSUE THREAD

**Issue by michaelschnyder** [IdentityServer/IdentityServer3#1619]
Problem: We just had the strange issue that given a WebSite in IIS with multiple bindings and no IssuerUri defined in the Options, sometimes (and somehow) not the primary Uri from the bindings was taken as the IssuerUri. As a result, all tokens got a different IssuerUri and the authentication was broken.

Workaround: After a Website Restart everything worked again.

This could probably make the IssuerUri-Property http://identityserver.github.io/Documentation/docs/configuration/identityServerOptions.html dangerous to use as soon as you have more than one binding in your IIS-Host where IdSrv lives in.

IMHO this is not directly an issue with IdSvr, probably this could be mitigated within the  [ConfigureIdentityServerIssuerExtension.cs](https://github.com/IdentityServer/IdentityServer3/blob/06ab9cf55996444c89f1aa2db61aba8646ebcf8c/source/Core/Configuration/AppBuilderExtensions/ConfigureIdentityServerIssuerExtension.cs)-File

However, for me it seems important to have a least a warning to not use the "Auto-Gessing"-Feature in combination with IIS and multiple bindings.

**Comment by brockallen** [comment]
Well, we use the request host name as the issuer if you don't specify one. This is intended to support multiple bindings and allows multi-tenancy scenarios.

**Comment by michaelschnyder** [comment]
Sure and i think that's a nice appraoch to support multi-tentancy. 

But there seems to be an issue (in combination with IIS?) which caused our IdSrv to issue with the wrong name. I watched a the Network Traffic from the SPA and the requested host was fine, but the iss was wrong. After a Website restart (IdSrv) everything was fine again.

Other ideas?

**Comment by brockallen** [comment]
Hmm, nope -- perhaps there's a bug. I'm not in front of the code now... but I'll take a look when I get a chance to see if I can understand why it might be happening.

**Comment by brockallen** [comment]
Ah, I just looked into this and yes we are automatically setting the issuer on the options on the first request from the host name.

**Comment by brockallen** [comment]
I'm going to mark this as a bug but we won't fix this in 2.0.0 which is supposed to be released this week --  it'll be part of 2.0.1 I suppose which will get released in the next month.

**Comment by brockallen** [comment]
This change causes a small, yet breaking change. We will push this to build 3.0.0.

**Comment by brockallen** [comment]
Ok, we came up with a way to keep the code backwards compat. I've made the change on this branch: https://github.com/IdentityServer/IdentityServer3/tree/dynamic_issuer_uri

Try it out and let us know how it's working for you. We want feedback before we merge this into the dev branch for release. Thx.

**Comment by brockallen** [comment]
Merged PR for fix

**Comment by pitzwong** [comment]
How does this affect IIS multibinding (multi-tenancy) on the resource server where Access Token Validation is performed?

The properties available for IdentityServerBearerTokenAuthenticationOptions indicate use of either Authority or IssuerName/SigningCertificate.  If we use Authority and specify the discovery endpoint, will the resulting IssuerUri be derived from the discovery endpoint and cannot be dynamic?  If we use IssuerName/SigningCertificate, can we make the IssuerName dynamic as well (this one does not sound easy because the only host header you have at this point is that of the resource server)?

**Comment by brockallen** [comment]
It doesn't. If you need/want something like that then I'd suggest following up in that repo.
