### ISSUE TITLE
Catching external provider error from callback url?

### ISSUE THREAD

**Issue by feina** [IdentityServer/IdentityServer3#1620]
Hi,

In my website, when a user clicks on "login with Facebook" a code flow is triggered passing acr_values=idp:Facebook to Identity Server.

If for some reason an error occurs when Identity Server authenticates with Facebook I would expect to get my website's callback endpoint called with an error parameter. However my website's callback endpoint does not get called and I get the Identity Server login page indicating that an error occurred.

How could I get my website's callback endpoint informed that an error occured while authenticating with an external identity provider?

Thanks

**Comment by brockallen** [comment]
This depends on the nature of the error -- some errors are only meant for the end user to see and Facebook won't redirect back to your app's callback. I'd suggest tracing at the HTTP level where the request is sent when the error happens.

**Comment by feina** [comment]
After some time I am taking up this issue again.
When a Facebook user denies access to Identity Server, the callback endpoint is called with the following parameter:

    http://<idServerUrl>/callback?error=access_denied#_=

I would expect Identity Server to propagate the error back to my website's callback endpoint, but this is not happening.

Is there any specific reason for not returning back the external provider error?
How could I get the error from Facebook?

Thanks

**Comment by sinithadennis** [comment]
We also has the same requirement as mentioned by feina.Can anyone please help us to understand how this can be done using IS 5.0.0 or 5.1.0?

**Comment by raban33** [comment]
To Circumvent the issue, I had written a middleware - AutoRedirectToExternalMiddleware where I tap in the request pipeline to examine if I had an error on the returning callback endpoint. the propogation of this error would be to the website which is written as a cookie to the user-agent.

The method where we need to tap this in is -  public async Task Invoke(IDictionary<string, object> env)

var  queryStringCollection = HttpUtility.ParseQueryString(context.Request.QueryString.Value);
   if (context.Request.Path.Value.StartsWith("/callback") && queryStringCollection?["error"] != null)
            {

                var tempState = GetTempState(context, "externalprovider");

                if (!string.IsNullOrWhiteSpace(tempState))
                {
                    dynamic tempData = JsonConvert.DeserializeObject<dynamic>(tempState);
                    string returnUrl = null;
                    if (null != tempData)
                        returnUrl = HttpUtility.UrlDecode(tempData.returnUrl);
                    string delimiter = returnUrl != null && returnUrl.Contains("?") ? "&" : "?";
                    string redirectUri = $"{returnUrl}{delimiter}error=EXTERNAL_ID_SIGNIN_ERROR";
                    context.Response.Redirect(redirectUri);
                    return;
                }
            }
