### ISSUE TITLE
Server to Server problem

### ISSUE THREAD

**Issue by Zarghidas** [IdentityServer/IdentityServer3#1622]
Hello everyone,

I'm developing a solution that i intercept every request on AfterReceiveRequest as IDispatchMessageInspector and i will call the Authentication and Authorization before the flow continues, but i dont want to redirect it to a callback api, i just want to get the response and continue de service flow. I've used the redirect_uri of CreateCodeFlowUrl as http://localhost/ only for test and changed all https to http, since i can't ignore the redirect_uri parameter, to try to get the AuthorizationCode on response, but no success, because it says that im not logged in and no cookies matching signid.
I'm doing something wrong probably, but anyone can help me on that ? I think i just dont need the cookies because this flow don't use MVC or login pages, only a interceptor of requests for Soap or REST and the Authentication and Authorization.  Is there something special on this approach ?  I couldn't find any sample on the project doing domething like this.

Code Sample without success returning a login failed page instead of AuthorizationCode and other parameters:

                var url = _oauth2.CreateCodeFlowUrl("client", scope: "openid profile read write", redirectUri: "http://localhost/");
                var webClient = new WebClient();
                var response = webClient.DownloadString(new Uri(url));

**Comment by brockallen** [comment]
I don't follow at all, sorry.

**Comment by brockallen** [comment]
Any clarification?
