### ISSUE TITLE
Resource Owner & Implicit client flow with MVC application 

### ISSUE THREAD

**Issue by raxitr** [IdentityServer/IdentityServer3#1623]
Here is the scenario, please help with right pointers,

* I am building an MVC application where Admin users require SSO capabilities and I have integrated Implicit client flow which works well.
* Within same application I do have public facing users for which no SSO required, so they need to be authenticated within application itself. Based on my reading resource owner user credentials flow would work best using Idserver. Following are my questions,
    * I am not clear how to integrate it within MVC web application, Resource owner only works with WebAPIs? Since it gives access token in return? How to maintain auth cookie?
    *  With Resource owner flow can my MVC website authenticate user and call the WebAPIs that are hosted separately?
		
With appreciation,
Raxit

**Comment by brockallen** [comment]
You'd need to write the login code on the MVC app, use it to get a token from IdSvr, then issue your own login cookie for the MVC app (probably using the same cookie framework you're using for your admins).

As for the token from IdSvr -- yes, resource owner would work. You can request OIDC scopes and then get the user's claims via the user profile endpoint. But I wonder why not just use the same redirect/implicit flow for the non-admin users?

**Comment by raxitr** [comment]
non-admin users are the public users of the Admin users (our clients) and Admin users can setup their public facing websites where public users would log in. Our clients do not wish to redirect non-admin users to external sites for authentication due to branding issue.

So once my MVC app authenticates will I be able to call APIs hosted separately with access token I received?

Thank you so much for answering.

**Comment by brockallen** [comment]
Yes, with resource owner flow you can use that access token to call other APIs (assuming you have the right scope).

**Comment by raxitr** [comment]
Thank you, I will try out and get back if required.

**Comment by raxitr** [comment]
Everything is working as expected but there is a twitst in the scenario. Need your advice in following,

Admin users do not need social sign in capability whereas public users need to be able to log in using social media (google and facebook). I have created two clients in Identity Server one with Identity Provider restricted to Identity Server and second with Idenity Provider restricted to Facebook and Google. 

I want to use both the implicit clients within single MVC application so that Admin users only see local login screen whereas public users will see only Social media log in options. For public users I can construct URL with acr_values and put it in my MVC app so that public users dont see Identity server. Let me know if this is possible and how to configure both clients in single MVC app.

**Comment by brockallen** [comment]
Hmm, not sure I've ever tried this scenario. I guess it this could be done as 2 client configs where you restrict local logins and allowed IdPs for each client. The other thought would be via custom HRD of some sort.

**Comment by raxitr** [comment]
I am using first approach and have configured two clients in IdServer with IdPs restriction. I am not sure how Custom HRD works, any documentation? 

Following is what I have tried and appears to be working,

1) Configured MVC app to use single client. 
2) Added MVC action with URL constructed manually which would use different client (a client with only social media IdPs). The Url has acr_values specified (facebook/google) so that it will bypass IdentityServer screens. 
3) Given call back method  which has [Authorized] attribute. I believe this would invoke Client 1's SecurityTokenValidated notification to populate the claims.
4) I get the autheticated user with required claims populated.

I know above approach is confusing. Not sure what is the downside of it?

**Comment by raxitr** [comment]
I don't seem to get it working as I put Idp restriction on the client and try to run two clients parallely one with only local login and the other with Facebook/Google. 

Is there any way I could just hide facebook/google options from login screen? 

I have tried your example CustomHrd but not quite sure how can I fit Custom HRD in my scenario explained above. 

Quoting again,


"Everything is working as expected but there is a twitst in the scenario. Need your advice in following,

Admin users do not need social sign in capability whereas public users need to be able to log in using social media (google and facebook). I have created two clients in Identity Server one with Identity Provider restricted to Identity Server and second with Idenity Provider restricted to Facebook and Google.

I want to use both the implicit clients within single MVC application so that Admin users only see local login screen whereas public users will see only Social media log in options. For public users I can construct URL with acr_values and put it in my MVC app so that public users dont see Identity server. Let me know if this is possible and how to configure both clients in single MVC app."

**Comment by brockallen** [comment]
You can hide the external IdPs from login page by setting the Caption on the middleware options to null. But this will mean they're always hidden for everyone on the login screen.

**Comment by raxitr** [comment]
Does that mean it will be hidden for all clients? Irrespective of idp r
estrictions?

**Comment by brockallen** [comment]
Yes, if you set it to null then it will never show. If you only want certain external IdPs to show for certain clients, then that's what the external provider restriction is for. Is that not working?

**Comment by brockallen** [comment]
Also, there's the `EnableLocalLogin` on the client config -- perhaps that can help? IOW, you can disable local logins for your admin client apps.

**Comment by raxitr** [comment]
Nullifying the caption did the trick for now since I am not planning to use social media login for admin users. 
However I do agree on your last point to build a custom view which reads acr values and renders view accordingly. I will implement it once rest of the stuff in my project is in order.

Thank you
