### ISSUE TITLE
resource owner and custom flow for the same client.

### ISSUE THREAD

**Issue by shtusha** [IdentityServer/IdentityServer3#1624]
I have a native mobile client that needs to support multiple ways of obtaining an access token - resource owner and custom flows.
What are my options? 
I would prefer not to create two separate clients. Do I have to implement custom flow and manually handle 'password' grant type to achieve that?

**Comment by brockallen** [comment]
What custom flows? Something outside of OIDC/OAuth2?

**Comment by shtusha** [comment]
mobile client will obtain a third party access code using a third party provided sdk (ex: Facebook) rather than obtaining it from a web view that relies on implicit flow.
Identity server has to resolve that access code to a user and return it's own access token.

standard scenario in mobile apps that want to have native username/password or FB authentication options for users.

**Comment by leastprivilege** [comment]
We only allow one flow per client - we sometimes regret that decision - but that is the way it is.

You either need 2 clients or handle both situations in your custom grant validator.

**Comment by shtusha** [comment]
Thanks for quick answers..

**Comment by wiseman13** [comment]
Any chance of making support for multiple flows a feature request? I have a similar case where there is a mobile application and a web application using the same client as they are the same from our management perspective, though I can understand the reason for the simplification.

**Comment by leastprivilege** [comment]
We will discuss this.

**Comment by RPM1984** [comment]
@leastprivilege cool! For the time being is it considered bad practice if i have a client registered as `Flows.Custom`, with two custom grant validators. 1) Facebook (exchange the FB access token for IdSrv token), 2) Password grant - simply calling into my custom user service `AuthenticateLocal`, mimicing ROPC flow.

It's easier that or two client registrations. Recommendations?

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3/issues/2433

**Comment by tcidsrv** [comment]
We are also having a similar requirement of supporting password grant and custom grant for the same client. What is advisable, should I create two clients one for each required grant or create two different custom grants one for password and other for custom grant?
