### ISSUE TITLE
Samples Error: There is an error determining which application you are signing into...

### ISSUE THREAD

**Issue by daishisystems** [IdentityServer/IdentityServer3#1625]
I receive the error 

>"There is an error determining which application you are signing into. Return to the application and try again."

when running the [CustomUserService](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService) sample. I'm running the sample out-of-thebox, without any modifications. Is there some sort of bootstrapper process that must be run?

The process flow is as follows:

1. Run the sample
2. Navigate to https://localhost:44333/core/localregistration
3. Complete the form (user: bob, password:secret, etc.
4. Submit and receive the error.

Failure occurs on this line:

    return Redirect("~/core/" + Constants.RoutePaths.Login + "?signin=" + signin);

I've also attempted to uncomment the following line:

    var userService = new LocalRegistrationUserService();

to no avail.

What value should I include as "signin"?

**Comment by leastprivilege** [comment]
You don't navigate to the registration page manually. It must be part of an authentication request.

**Comment by daishisystems** [comment]
Thanks. Is there a relevant tutorial associated with this? Trawling through the sample code to determine the correct process flow is a trial-and-error exercise.

**Comment by cabrinoob** [comment]
I have exactly the same issue when running the customUserService sample. The redirection fails with the same error message. What did you do to make it works?

Thanks

**Comment by arnoldpinto** [comment]
The CustomUserService sample is the IdSvr. You will need to use one of the supported clients that are listed in the CustomUserService\Config\Clients.cs to generate the authorization request. Sample clients are located in the Clients sub directory within source.
