### ISSUE TITLE
Updating Authentication Type after 2FA Auth (Partial Login)

### ISSUE THREAD

**Issue by aosgo** [IdentityServer/IdentityServer3#1626]
We have implemented 2FA using a Partial Login, but ideally we'd like to change the Authentication Type (amr claim) to reflect that they have used 2FA to sign-in. Possibly a dumb question but is it possible to update the Authentication Type after the user has "logged in"? The user has the option to use 2FA but it's not mandatory.

I've looked at the sample (https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity_2fa) although we don't use ASP Net Identity but our implementation is the same concept as per #249 

In this file https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/AspNetIdentity_2fa/WebHost/Controllers/TwoFactorController.cs#L51

We'd ideally like to do the following:

`**Update Authentication Type to reflect "2FA" rather than external**`
`var resumeUrl = authentication.Identity.Claims.Single(x => x.Type == Constants.ClaimTypes.PartialLoginReturnUrl).Value;`
`return Redirect(resumeUrl);`

I've tried:
`var authenticationResult = await ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType);`
`var id = new ClaimsIdentity(authenticationResult.Identity.Claims, "2FA");
var authenticationManager = ctx.Authentication;
authenticationManager.SignIn(id);
var resumeUrl = authenticationResult.Identity.Claims.Single(x => x.Type == Constants.ClaimTypes.PartialLoginReturnUrl).Value;
return Redirect(resumeUrl);`

If not any suggestions please on how to tell IdSrv that user has successfully used 2FA, then their identity would reflect this for each subsequent validation to IdSrv

**Comment by brockallen** [comment]
In 2.0.0 we have a new OWIN extension to so you can change the claims for the user's login (such as the authentication method).

**Comment by aosgo** [comment]
OK, thanks. We're on 1.6.1 at the moment, so will hang-fire for a bit. I can get round it by setting it straight away and I'll dump the "abort 2FA" option so they'll always remain on a partial until they've successfully validated the 2FA code.

**Comment by brockallen** [comment]
You can see how the code works here and do the same in your app:

https://github.com/IdentityServer/IdentityServer3/blob/dev/source/Core/Extensions/OwinEnvironmentExtensions.cs#L268

**Comment by aosgo** [comment]
OK, thanks. I've tried using

`var updatedUser = new ClaimsIdentity(Constants.AuthenticationMethods.TwoFactorAuthentication, Constants.ClaimTypes.Name, Constants.ClaimTypes.Role);
updatedUser.AddClaims(result.Identity.Claims.Where(x => x.Type != Constants.ClaimTypes.AuthenticationMethod));
updatedUser.AddClaim(new Claim(Constants.ClaimTypes.AuthenticationMethod, Constants.AuthenticationMethods.TwoFactorAuthentication));
context.Authentication.SignIn(result.Properties, updatedUser);
var resumeUrl = result.Identity.Claims.Single(x => x.Type == Constants.ClaimTypes.PartialLoginReturnUrl).Value;
return Redirect(resumeUrl);`

But the amr claim still says password and not 2fa

**Comment by brockallen** [comment]
I don't think you're using the Partial authentication type for your new cookie.

**Comment by brockallen** [comment]
All set now?

**Comment by aosgo** [comment]
No, but the business decided to make 2FA mandatory so I ended up setting it in the  AuthenticateResult in our custom user service. 

Thanks for your help anyway
