### ISSUE TITLE
How to handle session timeout at client

### ISSUE THREAD

**Issue by buddhike** [IdentityServer/IdentityServer3#1627]
Hey Folks, I have two clients running on different subdomains. For end-users though, it's essentially one app. Both of them have hyper links to each other so that user can navigate between two. They are running on two subdomains because, different infrastructure, different stacks etc. They both send their users to ID server for auth. 

I have this situation now. Users tries to go to Client-1 and gets redirected to ID server. Authenticate there, and then gets redirected to Client-1. Client-1 validates the token and sets up his own session via cookies which will expire in 10mins 

If he clicks a link that takes to Client-2. Since this is the first time he is visiting Client-2, he gets redirected to ID server. But ID server session cookie is still valid and user gets redirected back to Client-2 without seeing username/password prompt. 

User pokes around Client-2 for a while and attempts to go back to Client-1 after 15 mins. Because the cookies for Client-1 are now expired, he's taken back to ID server. However, by that time, ID server session cookie is also expired and therefore the user will see username/password prompt again. 

Is there a feature in ID server to handle this scenario? 

Thanks heaps in advance!

**Comment by brockallen** [comment]
You should set a longer session timeout at IdSvr itself -- that way the SSO lasts longer.

**Comment by buddhike** [comment]
Hi Brock, thanks for getting back to me. We thought about it. But that kind
of makes the cookie timeouts in client-1 and client-2 useless right? If the
users was not interacting with both clients we want them to see sign-in
dialog again.

Say if make I'd server timeout 20mins in this case, user can go to client-1
and then Client-2. But not interact with anything for 15mins (which is
longer than 10mins cookie time at client 1 and 2). But when he is
redirected to ID server it automatically issues the tokens....

May be its our fault that we want run the same app in two sub domains you
think? :-)

**Comment by brockallen** [comment]
Well, normally you set the cookie lifetime in the token service to be the duration of a workday -- so ~10 hours.

**Comment by buddhike** [comment]
Yeah makes sense for majority of cases. Unfortunately this particular
instance is for an app which deals with highly confidential information. We
were going to settle with a token service cookie lifetime that only lasts
for browser session. But then we have this requirement not to compromise if
the user accidentally leaves the machine he is using unattended with the
browser still open with a valid session.

The argument may sound ridiculous because if you leave the machine
unattended with a session to highly confidential data.. you can pray that
intruder does not get there before session timeout :-) but I don't know if
there is anything else web app can do about it...

Have you come across any standard patterns to solve this sort of risk?

**Comment by leastprivilege** [comment]
Hey, 

i don't quite understand the problem - if you need short timeout, do short timeouts - if you need the "productivity" of not having to log in again - you need longer timeouts. That's the way it works ;)

You can have distinct timeouts for each client as well as idsrv itself. There's not much more we can do to help you here.

**Comment by buddhike** [comment]
Thanks Dom. I thought this would be the case. I guess it would make more sense, if we had both clients in one sub domain. Just wanted to make sure there's nothing in OpenID Connect Session Management that does enable a scenario like this. 

Thanks for your time again.

**Comment by leastprivilege** [comment]
Putting them on the same domain is not the solution ;) You just can't have both - short sessions and single sign on :)

**Comment by buddhike** [comment]
I didn't mean to put ID server and Clients on the same domain. Just client-1 and client-2 run on same subdomain.

At the moment I have my id server running at:
id.myorg.com
And the two clients 
new.myorg.com
old.myorg.com

The problem is, for the end-user, new and old is just a single app. They are hosted in different subdomains because of infrastructure needs :-). We would still keep id server at id.myorg.com. However, if we run the apps in same sub domain we would not have this session expiry issue right?
e.g. 
www.myorg.com/new
www.myorg.com/old

**Comment by leastprivilege** [comment]
What a difference would that make?

**Comment by buddhike** [comment]
Because the session cookie for old and new app can be renewed as long as
the user is interacting with a yell in either app. Because they both can
see it (same sub domain). Similarly if the user attempts to access either
of them after session cookie is expired, they are taken back to ID server.
We can have a shorter lifetime on that end which will force the user sign
in again. Right? :-)

**Comment by leastprivilege** [comment]
If both apps use different technologies - how would they make sense of each others session cookies?

**Comment by buddhike** [comment]
That's a good point :-). But In this case one is asp.net forms the other is
mvc. So we could have shared http module or something like that to validate
the session cookie.

**Comment by leastprivilege** [comment]
That's a hack

**Comment by buddhike** [comment]
Absolutely dude :-). It's just a very ugly option. I don't like it at all.
But like you already pointed out, we cannot have both short sessions and
sso....
But in our situation both are desirable. Still contemplating...
I wonder if there's much written about modern ways to handle "insufficient
session expiration" problem.

**Comment by matthewlramsey** [comment]
Hey @buddyspike - can you share any updates on how you were able (or not) to get sliding App Cookies to work with logouts in Identity Server?  We have almost the exact same setup you describe (dual sites on subdomains with separate infrastructure... ASP.NET Forms on one, MVC on the other), and would really love to get shared sliding cookies to work (both apps can share a cookie to manage app session).  The goal is to simply trigger a logout when the sliding app cookie expires, but we can't seem to find the appropriate place to call `context.OwinContext.Authentication.SignOut();` - calls to this from within the outbound request notification `RedirectToIdentityProvider` do not seem to effectively logout the user, requiring the user to re-enter their credentials.  Any help or thoughts you have here would be greatly appreciated. Thanks!

**Comment by buddyspike** [comment]
@matthewlramsey The piece of work that instigated this thread never saw the light at the end of the tunnel (nothing to do with Identity Server or the technology) :-). 
But I will try to summarise  some of my notes. 

- Each app's intent to establish it's own session was complicating the matters for us. Instead, we could renew the access token as it approaches the expiry. We thought about several ways of doing this.
1. Make the client do this using a refresh token (if it had a way to store the refresh token securely). Obviously this would not be easy to do in browser based clients. Alternatively, an IDP could have an endpoint where if you invoke with a valid access token, you get a new access token with a new expiry ***.

2. Make servers do this and include the new token in some kind of a pre-agreed response header.
Server could use a refresh token. Another option is to have some kind of a trust between the backends and IDP to do this. If IDP has a token renewal endpoint as mentioned in option 1, servers could use that as well)***.

- We had a requirement to black list the sessions. We also wanted to ensure that if user logs out, he/she would not be able to use the token and invoke the servers even if it was not expired.
If these type of session invalidation matters to you, you could store log outs and black listed tokens in a cheap storage (e.g. redis cluster). Then, for each interaction, the servers will check if the token has been marked as "unusable" in that store.

Please note that this response is solely based on my experience and should not be taken as an expert advise :-). Guys working on Identity Server may have better suggestions for this. 

*** I'm not sure doing this would violate the rules of OpenID connect.
