### ISSUE TITLE
Integrate custom authentication middleware and IdSrv?

### ISSUE THREAD

**Issue by devployment** [IdentityServer/IdentityServer3#1628]
Following scenario. I have an ASP.NET MVC app that is running inside an iFrame embedded into a corporate website. The URL of the iFrame contains a token parameter.

For this received token we have a defined endpoint to call for validation, owned by the corporate website owner. The corporate expects us to POST the following to validate the token passed. This is all done using regular http calls from the server. 

```
POST /api/SSO/ HTTP/1.1
Host: api.thecompany.tld
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=validate_token&access_token=xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&user_name=user%40domain.tld
```

As result we get back something like this

```
{
"user": "{\"user_name\":\"user@domain.tld\",\"user_code\":\"1234567\"}"
}
```

We have no further information what is providing this token or what is this checking endpoint. Looks like some OAuth endpoint. But this is out of scope for now. 

Our MVC app is generally protected by IdSrv using username/password authentication against IdSrv. This authentication is used to access a Web API that drives the MVC app at the end. In the MVC app I'm using the JS OIDC client to request an bearer token against the IdSrv for the currently logged in user. This is then used to access the Web API.

To authenticate this special user that is passed by the iFrame Url, I wrote a middleware that checks for the _username_ and _token_ parameter in the request and "authenticates" against the endpoint mentioned above. This works as expected and the user is logged in "locally".

Question is now if there's a way to combine this local middleware authentication with the IdSrv authentication so that this custom middleware authenticated user is ultimately able to access the Web API protected by IdSrv?

Issue is that I cannot request the bearer token from the JS client as the local authentication is not known by IdSrv. So I get presented the default IdSrv login screen.

I hope somebody can at least kind of understand what I'm trying to explain and achieve.

**Comment by brockallen** [comment]
I've read this twice and I still don't follow. Sorry.

**Comment by devployment** [comment]
@brockallen Can imagine that. Solved the issue without some custom middleware "internally". Ticket can be closed. Thanks for reading though.:)
