### ISSUE TITLE
Can we automatically provision access token scopes for certain client ids?

### ISSUE THREAD

**Issue by n-alex-white** [IdentityServer/IdentityServer3#1629]
I can see that the client object allows us to specify allowed scopes for a client so that the client can either request any token scopes or just a subset of token scopes.

My question is whether it is possible to have some clients automatically get certain access token scopes applied, without specifically including them in the request.

For instance, supposing I have a *checkout service*, and that is going to acquire an access token for using the *payment service*. Only access tokens which contain the 'pci' scope will be accepted by the *payment service*.

Our mobile app might only request an access token with the 'pci' scope when it needs to perform a particular action on the *payment service*. 

But the *checkout service* will **always** want to have the 'pci' scope. Does it make sense that access token requests from the *checkout service* are always given the 'pci' scope automatically, based upon their client id?

The reason for asking this question is ultimately about whether we would have to change every single existing service if we wanted to introduce access token scopes for finer grained security, or if we can automatically apply certain scopes on a client id by client id basis.

Thanks

**Comment by leastprivilege** [comment]
We don't have anything like that built-in. But implementing IClaimsProvider yourself (or deriving from ours) would make that doable.

**Comment by n-alex-white** [comment]
Thanks. We'll look into doing that. if we come up with something good enough we may submit it back to you for consideration if you think it would be generally useful.
