### ISSUE TITLE
Refresh IdentityToken

### ISSUE THREAD

**Issue by fekberg** [IdentityServer/IdentityServer3#1630]
When calling `OidcClient.RefreshAccessToken` you will not receive a fresh `IdentityToken`, although looking at the JWT it does include an expiry.

Is there a reason why a new `IdentityToken` is not issued? When calling `endsession`, does it require a valid (time wise) `IdentityToken`?

Is there another way to refresh it, or is it simply unnecessary?

Thanks!

**Comment by leastprivilege** [comment]
id_tokens are not refreshed. You typically only need them once to validate them and turn them into a local identity representation in your application.

**Comment by fekberg** [comment]
Yeah that's what I figured. Only concern is: when calling `endsession` does it care if it actually expired?

**Comment by leastprivilege** [comment]
no it doesn't - expired tokens are allowed on endsession.

**Comment by fekberg** [comment]
Awesome, thank you so much!
