### ISSUE TITLE
Is OpenId Connect access token also valid OAuth 2.0 access token?

### ISSUE THREAD

**Issue by vcarreno96** [IdentityServer/IdentityServer3#1632]
My current project requires we remove OpenId Connect related code and abide by the OAuth 2.0 protocol strictly.

If I only make an implicit flow access token request using Identity Server, is it correct to say I am using this product to implement an OAuth 2.0 compliant authorization server?

**Comment by leastprivilege** [comment]
Yes

**Comment by vcarreno96** [comment]
Thank you for the clarification!
