### ISSUE TITLE
Not redireacting after login is done from idsrv3 using javascript client

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#1633]
Problem is if am login to the server after login is successful it will redirect to client application at that time  getting refreshed continuously  this is happening in server

![untitled](https://cloud.githubusercontent.com/assets/10266752/8796376/2d8431c2-2f49-11e5-97a6-33c438ba5493.png)

If i run javascript client sample in a locally. application through ssl network error for the this i found solution we have to chnage in Internet Options i will paste the image below but every time or which are the system having this problem i can't do this so i have to fix the issues through program only how can do that

![untitled1](https://cloud.githubusercontent.com/assets/10266752/8798464/4e6a200a-2f57-11e5-83a8-e36050a32da4.png)

After this internet setting changes redirecting is working correctly.

**Comment by brockallen** [comment]
Sounds like the cookie is not being set in your client app,. or the client app is triggering a 401 for some reason which triggers a request to IdSvr for authentication.

**Comment by brockallen** [comment]
Any update?

**Comment by RajMondaz** [comment]
Hi brockallen , I will be checking on Monday, currently working on some other tasks.

**Comment by brockallen** [comment]
Any update?

**Comment by RajMondaz** [comment]
Hi brockallen , I am working on this task now after SSO  login it continuously looping it is not redirect. 
I have fixed issuse but that is not the right solution.. what i have done after updating the system time (in below image) problem get solved  i don't know what was the Problem and how it is related to Idsrv 3     

Can i know what was the Problem in the Idsrv 3 where i need to change..?

![image](https://cloud.githubusercontent.com/assets/10266752/9771855/59941a0e-5756-11e5-814c-6381eced9378.png)

**Comment by brockallen** [comment]
Sounds like your app is either failing authorization even though the user is logged in, or you are not going over SSL, but the cookie is.

**Comment by RajMondaz** [comment]
in some of the system its happening like this not in every system (suppose if i have installed new Operating system or if i opening my site in new system this kind of problem i am getting)..
and i need to know how it is related to Time because if i am updating Windows time Problem getting Solved..

**Comment by brockallen** [comment]
Well, clocks do have to be synchronized w/in 5 minutes of each other for token expiration validation.

**Comment by RajMondaz** [comment]
Hi brockallen  to check the problem i have done set up with client sample and i have uploaded  to the server.

i have opened the site in the two different system  in the 1 st system Authorization response i am getting but in the second system it is not coming it is giving the error Token issued too long ago 
this error is related to what why the same login acts differently in 2 system

First System
![image](https://cloud.githubusercontent.com/assets/10266752/9787294/27957ae6-57df-11e5-874e-8004614a0535.png)

Second System
![image](https://cloud.githubusercontent.com/assets/10266752/9787281/102cf442-57df-11e5-98da-67d8d3ab5ff1.png)

**Comment by brockallen** [comment]
Yep, sounds like an expiration problem. I'm not sure why -- you'll have to debug it.

**Comment by RajMondaz** [comment]
the problem is that is if it is happening in every system then we can try find the problem it is happening in few system.


any guess on issue..?

**Comment by brockallen** [comment]
No, sorry

**Comment by RajMondaz** [comment]
Ok Thanks..

**Comment by RajMondaz** [comment]
I will try.

**Comment by vinaykasireddy** [comment]
Hi Raj & Brockallen,

We are also facing similar kind of issue. We are using oidctoken manager as client. It is saying "token is issued too long ago" and the client issues redirect all the times. 

When i tried to publish the same client and idsvr in azure they are working fine without any issues.

**Comment by brockallen** [comment]
Then the token has an issued value that was more than 5 minutes in the past. Sounds like either a clock skew or maybe there's a bug (perhaps timezone?) in the id token validation logic. Feel free to look into it further.

**Comment by vinaykasireddy** [comment]
Hi Allen,

I just fixed this issue by disabling the day light savings time. Now both client and server are having the same tine. 

However i still have few doubts on the token issuing.  What if the identity server is located in US and the client sits in Singapore (GMT + 8) ? Will this issue happen in such cases?

**Comment by brockallen** [comment]
Test it :) the times issued are epoch time. I guess the real question is if 5 minutes is too narrow of a window. Kerberos and many other protocols expect computer clocks to be within 5 minutes of one another for the protocols to work.

**Comment by brockallen** [comment]
BTW, this is really a new and unrelated issue. So please open a new issue.
