### ISSUE TITLE
Implementation of Hybrid flow for Angular JS

### ISSUE THREAD

**Issue by moharrer** [IdentityServer/IdentityServer3#1634]
I need some implementation guidance, I have an AngularJS client with ASP.NET Web API on the server-side. Here are some questions:
I have implemented Implicit flow where I'm able to get the id_token and access_token from the IdentityServer. I would like to know if we can implement Hybrid flow that allows refresh-tokens?

**Comment by brockallen** [comment]
You could -- the code would need to be sent to your server (where your secret is) and that's where you could exchange the code for a refresh token.
