### ISSUE TITLE
Access UiLocales

### ISSUE THREAD

**Issue by McCloud65** [IdentityServer/IdentityServer3#1635]
Hi there,
I am currently implementing a identity server solution where I need the possibilty to pass the user language (uilocales) to the server in order to show the login screen and related messages in the user's language. 
On the client side I can set the locale in the RedirectToIdentityProvider like this: 
       n.ProtocolMessage.UiLocales = "de"
How can I read this value in the IdentityServer? I know it is in the SignInMessage but this info is only available in the IViewService scope. I would also need this info in the ILocalizationService derived class.
Thanks for an advice.
Best regards
Jürgen

**Comment by brockallen** [comment]
The ui_locales is made available in the `SignInMessage` which is passed to both the user service and the view service.
