### ISSUE TITLE
Renewal of tokens in the javascript application on its expiry

### ISSUE THREAD

**Issue by DivakarPM** [IdentityServer/IdentityServer3#1636]
Hi 
We have implemented an application with angular js as client and web api as backend. and we are using implicit flow for this.

In the oidc-token-manager sample you have included renewTokenSilentAsync method which renews the tokens on expiry as per my understanding by configuring SilentRenewRedirectUri. Do you have any documents regarding this?

**Comment by brockallen** [comment]
Not too much as of now -- it's mainly just re-requesting the token via an iframe and since the user is still logged in the response can return a token.

**Comment by DivakarPM** [comment]
Thanks brock

1) And i observed, in this method token is getting renewed for half the life time of the token. is this valid? or can we customize the renewal time in the client.
2) Is this way of renewal of token is good or implementation of refresh tokens in the client. If it is good with refresh tokens do you have any samples for hybrid flow for javascript client.

**Comment by brockallen** [comment]
You can either do it manually, or if it's set to auto then it does it 1 min before token expiration (IIRC).

JS clients don't get refresh tokens since they're public clients (not confidential ones).

**Comment by DivakarPM** [comment]
Thanks brock..
