### ISSUE TITLE
Simplify external login entity in model exposed to CustomViewService?

### ISSUE THREAD

**Issue by pinnprophead** [IdentityServer/IdentityServer3#1637]
I have implemented the CustomViewService and am enhancing the styling on the external login buttons using the zocial styling css . The only properties exposed in the model are "text" and "href". The text property has a lot of gook in it so in order to extract a name of the external service, like "google" you have to do something like this:
provider.text.split(' ')[provider.text.split(' ').length -1].toLowerCase()

and concerned that this could be easily broken.

It would be cool if the provider had a property like "type" that would be "google" for example. Then if you wanted to build a caption like "Sign in with Google" you would build it with an Angular {{expression}}.

For example, in my case, I want the button caption to just be "Google", the class to be "zocial google" and the title to be something like "Log in using your Google account." 

I can get the job done but end up repeating the javascript expression above several times. It would seem more natural to have the object include the base service name ("type") and build longer UI strings from that.

Just a suggestion!

**Comment by brockallen** [comment]
Sure, I think we can make a change here.

**Comment by brockallen** [comment]
Done on dev
