### ISSUE TITLE
Unable to distribute IdSvr3 as part of a plugin due to requirement that assembly is copied local

### ISSUE THREAD

**Issue by PaulNorth** [IdentityServer/IdentityServer3#1638]
We currently package our services into easily updated product based add ins which involves zipping the service and its dependencies up into a single redistributable file, the files within are loaded directly from the zip file. Unfortunately when I try to start the Owin WebApp with IdSvr3 configured I am hitting an issue because line 89 of UseIdentityServerExtension calls app.UseEmbeddedFileServer(); which expects the IdentityServer3.dll to be copied to the local hard disk in order to read its FileInfo(...).LastWriteTime (see https://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.FileSystems/EmbeddedResourceFileSystem.cs >> ctor(Assembly assembly, string baseNamespace) >> _lastModified = new FileInfo(assembly.Location).LastWriteTime;). My query is: Is there a way via config to change this behaviour, and if not, would you say supporting a plugin architecture is a desired feature or is this a case of needing to refactor our existing service platform?

**Comment by leastprivilege** [comment]
@brockallen please follow up

**Comment by leastprivilege** [comment]
Paul - is this still an issue or have you resolved it?

**Comment by brockallen** [comment]
This totally fell thru the cracks -- my fault and sorry. Let us know if this is still an issue.

Let me ask - if you didn't use the embedded assets, what would you propose instead for your situation?

**Comment by PaulNorth** [comment]
This is not a burning issue at present as we are now moving to an Azure-hosted solution where the assemblies will be unzipped anyway.

If you did decide to address it; I'm not sure this would be solved by not using the embedded resources as the root cause is when the IdSvr3 assembly is itself embedded within a zip/plugin file and loaded using Assembly.Load(Byte[]) which obviously does not set the Location property.

My initial thoughts  would be to write an implementation of Microsoft.Owin.FileSystems.IFileSystem which reads the last modified date from the assembly file if Location is set, or accepts a ctor parameter / uses an arbitrary value if not.  I have browsed the Katana code and can't see any reason that this would cause any issues within Owin; however it does make me concerned about possibly circumventing part of the assembly identity which I'm sure you will know more about than me!
