### ISSUE TITLE
Question: Which is the recommended way to use Single Sign On between SPA applications?

### ISSUE THREAD

**Issue by Condor2708** [IdentityServer/IdentityServer3#1645]
I have two different SPA applications implemented using Implicit Flow with IdentityServer v3 and using the oidc-token-manager.js client library with sessionStorage for the access_token. 
I need to redirect from APP1 to APP2 using the same user identity
APP1 using WebApi1
APP2 using WebApi2

WebApi1 and WebApi2 uses Bearer Token Authentication and are defined as two different Clients in IdentityServer3.

After redirect from Application1 to Application2 I call TokenManager.redirectForToken() and a new access_token is created for Application2. Is that the right way to use SPA and SSO? Or am I missing something.

Thanks

**Comment by brockallen** [comment]
That's legal -- you're making a new request form the new client and it's sharing the SSO cookie.
