### ISSUE TITLE
About IsActiveContext

### ISSUE THREAD

**Issue by rmbrunet** [IdentityServer/IdentityServer3#1646]
Any possibility to get some Client context (ClientId, for example) in IsActiveContext? I am looking for a way to activate specific users for specific clients and IUserService.IsActiveAsync seems to be the appropriate place.

Thanks!

**Comment by leastprivilege** [comment]
done on dev - please test

@brockallen please review and test: https://github.com/IdentityServer/IdentityServer3/commit/b2a0c4a31eeda8d78d2ccb91c8c91665f5f0c579

**Comment by rmbrunet** [comment]
Cool!

**Comment by brockallen** [comment]
Seems to be working properly.
