### ISSUE TITLE
Question: IIS Express Vs IIS Hosting

### ISSUE THREAD

**Issue by kiran-mahadev** [IdentityServer/IdentityServer3#1647]
Hi,

I may be asking a question that is already answered in the past. Excuse me for the duplicate question, please.

I'm new to IdentityServer3 and Security, I was trying to extract claim information from access token in a Web API. If I run the IdentityServer3 locally it works like a charm. But, the moment I host it on IIS I don't seem to be able to extract claim content from access token. I believe, I'm missing something very obvious.

Please guide or point me to some reference. Thanks!

**Comment by brockallen** [comment]
This is not really enough info to go on -- You'd need to either do some HTTP debugging or enabled logging in IdSvr to track this down.

**Comment by kiran-mahadev** [comment]
Thanks your time Brock! As, I continued to debug it became more evident that the problem was related to SSL.
