### ISSUE TITLE
Problem running identity server in IIS

### ISSUE THREAD

**Issue by perfectphase** [IdentityServer/IdentityServer3#1648]
OK, this is a weird one and I've been fighting this all day.
We have a custom IUserService that uses partial login redirects.  We direct to a MVC controller in the same project as Identity server, and then return, all very simple.

We have this code in the post method on our controller
```c#
var ctx = Request.GetOwinContext();
var authentication = await ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType);
if (authentication == null)
{
   return View("Error");
}
```
Which works.....  as long as I let VS create the virtual directory in IIS, if I create the vdir via powershell or the IIS user interface AuthenticateAsync returns null!!
I've been through and diff'd all of IIS's config files and I can find no difference, checked the appPools, the lot I can't find any reason why it only works via VS creating the vdir in IIS.

This applies even with out the debugger attached.  I can reproduce this on multiple machines as well :(

Utterly at a loss on how to move forward on this!

Thanks

Stephen.

P.S. tried this in VS2015, VS2013-Update5, VS2013-Update4 with no other versions installed.

**Comment by brockallen** [comment]
Check the app pool? Check that it's an application and not a virtual directory?

**Comment by perfectphase** [comment]
Yep, checked all that, everything other than this one line of code seems to work, which is why I'm so confused, pages served, database access all OK.  Actually the code works in the GET from the controller (I's basically copied out of one of the external registration sample)
I'm pulling in OWIN from source to debug through it to see if I can get a hint of what's broken!

**Comment by perfectphase** [comment]
So, when I run it off the app dir created via visual studio, the GET to my controller has these cookies
SignInMessage.<GUID>
idsvr.partial
idsvr.xsrf

and the POST back contains the same.

When I create the app dir outside of VS, I get the same 3 cookies in the GET request to my controller, but I do not get them included in the POST, also the POST is missing the Location header that looks like: Location:https://dt-stephen-03.FQDN/sateonservices/identity/return?resume=b1c186ab542d0a58b7d2f8567828c667

**Comment by perfectphase** [comment]
When this works (IIS Application created by VS) the Request headers of the POST back to my controller during partial login, contain the following cookies
SignInMessage.<GUID>
idsvr.partial
idsvrxsrf

But if the IIS-Application is created outside of VS, then these cookies are missing from the request (but were present in the initial GET request.

**Comment by perfectphase** [comment]
So it turns out to be a upper/lower case issue.  We have the Identity server web application sitting inside a virtual directory so we have a URL like this https://myserver/productservices/identity
Now the import part is when our scripts & installers create the vdir, they create it as ProductServices (Upper case P & S), and if you use the new-WebApplication cmdlet or the IIS gui to create a web application under this you end up with a Virtual Path of /ProductServices/identity.  If you use VS to create the web application it uses the case you use in the properties page, so in my case this was /productservices/identity.

Now all of this should not matter, as MVC and therefore identity server do a good job of normalising this all to lower case, and this is important for cookies, as they seem to be rather touchy about case.

The only place that does not seem to normalise to lower case is Razor's Html.BeginForm that leaves the casing intact when it writes the form action attribute and hence breaks the cookies.

I have changed all my scripts and installers to create the vdir using lower case and all seems well now.

Stephen.

**Comment by perfectphase** [comment]
One finally question, is it correct that casing of the URL entered into the browser is important?  That strikes me as wrong.   If I change some of the casing of the path (not host) to uppercase, the redirect from the login page fails.

**Comment by brockallen** [comment]
Yes, URLs (other than the host name portion) are always case sensitive.

**Comment by perfectphase** [comment]
Well, you learn something every day!  How did I survive this long without knowing this! :)
