### ISSUE TITLE
Handling External Providers for a Client

### ISSUE THREAD

**Issue by lommez** [IdentityServer/IdentityServer3#1651]
I'm trying to create an Idp server that will have will many external providers. 
Is possible to register one specific external provider that will only authenticate users from just one specific client?  Because my server is allowing a user connected using an external provider to use every client.

**Comment by leastprivilege** [comment]
Yep - check the client settings in the docs.

**Comment by lommez** [comment]
You the IdentityProviderRestrictions property?
Thanks Dominick

**Comment by leastprivilege** [comment]
yes - if this is set to just one - and local login is disabled. IdSrv will automatically use the one.

**Comment by lommez** [comment]
Thank you
