### ISSUE TITLE
Would you consider more granular options for including scopes/claims in id_token?

### ISSUE THREAD

**Issue by KevinDockx** [IdentityServer/IdentityServer3#1652]
Currently (unless I'm missing something) we can either ask for all the id scopes to be included in the id_token, or none.  

Imagine the following scenario:
- A user has got 3 claims: givenname, familyname and address
- When I ask responsetype "code id_token" & scope "openid profile address", I get those claims in the id_token
- When I ask responsetype "code id_token token" & scope "openid profile address" I get an id_token without the claims, and an access token with the correct scopes so I can ask for those claims through the UserInfo endpoint

If I want to include the claims in the id_token, I can define the profile or address scope myself (instead of user StandardScopes), and set IncludeAllClaimsForUser to true.  But: if I set "IncludeAllClaimsForUser" to true for profile, the address claim is included in the id_token as well. 

Maybe a more granular approach could be useful? Ie: if I set IncludeAllClaimsForUser to true on profile, I'd expect the familyname & givenname to be included in the id token, but I wouldn't expect the address claim to be included as well.  I just want that scope in the access token so I can ask for the address later on, when I need it.

Scenario: some claims are often used throughout an app (givenname, familyname), so I'd like to get those in the id_token.  But I don't need address throughout the app, I only need those on a specific page - which is why that looks like the perfect moment to call the UserInfo endpoint with an access token that includes the address scope.

Is this a bug?  Or just an unsupported scenario?  

Tested with the Hybrid flow & MS's OpenIdConnect middleware in an MVC app.

**Comment by leastprivilege** [comment]
Not sure I follow - the "AlwaysIncludeInIdToken" flag on the ScopeClaim decides if the claim is always included or not. There are also definitions for the standard scopes that have that flag set - StandardScopes.ProfileAlwaysInclude.

The "IncludeAllClaimsForUser" is really only for a niche scenario where you want to pass through all claims of the user (e.g. when using an external provider).

**Comment by KevinDockx** [comment]
Ok, looks the scenario I'm looking for *is* supported :)  I figured "IncludeAllClaimsForUser" would only include the claims related to the Scope I set it on, which lead to my post.  But using AlwaysIncludeInIdToken at ScopeClaim level effectively solves my problem.  Tnx :)
