### ISSUE TITLE
Unexpectd forbidden exception on refresh

### ISSUE THREAD

**Issue by CockyAmoeba** [IdentityServer/IdentityServer3#1653]
We have an ASP.NET mvc site. 

All works as expected  - login and authorization. If we leave the site idle for 5 min after having logged in and refresh we get a Forbidden exception.

Our action  is attributed as follows:
    [ResourceAuthorize("Read", "MakeSearchRequest")]
    [HandleForbidden]
    [HttpPost]
    public async Task<ActionResult> MakeSearchRequest(Search searchString)
    {....}

So a refresh of the page or clicking the action button linked to this action causes the forbidden exception if idle for roughly 5min.

our startup.cs is configured  as follows for openId connect authentication:

    appBuilder.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
    {
        Authority = authenticationAuthorityUrl,
        ClientId = "sulfurwebsite",
				Scope = "openid sulfurwebsite",
				RedirectUri = redirectUri,
				PostLogoutRedirectUri = redirectUri,
				ResponseType = "id_token token",
				SignInAsAuthenticationType = "Cookies",

				Notifications = new OpenIdConnectAuthenticationNotifications
				{ 
					SecurityTokenValidated = async n =>
					{
                        
						var nid = new ClaimsIdentity(
							n.AuthenticationTicket.Identity.AuthenticationType,
							Thinktecture.IdentityServer.Core.Constants.ClaimTypes.GivenName,
							Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Role);

						n.AuthenticationTicket.Identity.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Type, ui.Value)));

						// keep the id_token for LogOff
						nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));

						// add access token for sample API
						nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));

						// keep track of access token expiration
						nid.AddClaim(new Claim("expires_at", DateTimeOffset.Now.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToString()));

						n.AuthenticationTicket = new AuthenticationTicket(
							nid,
							n.AuthenticationTicket.Properties);

						await Task.FromResult<bool>(true);

					},
					RedirectToIdentityProvider = async n =>
					{
						if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
						{
							var token = n.OwinContext.Authentication.User.FindFirst("id_token");
							if (token != null)
							{
								var idTokenHint = token.Value;
								n.ProtocolMessage.IdTokenHint = idTokenHint;
							}
						}
						await Task.FromResult<bool>(true);
					}
				}

			});

Using fiddler it seems that an authorize request is being issued to our identity server - a redirect is performed to our controller and action and forbidden is thrown. If I then navigate my browser to http://localhost:port i am re-authenticated without having to log in and all works again.... at least while not idle for roughly 5min.

Something is timing out  - but i am not sure what? Is there any advice that can be granted on this issue? 

Regards.

**Comment by leastprivilege** [comment]
Set  `UseTokenLifetime` to false - and thank Microsoft for a useful default setting.

**Comment by CockyAmoeba** [comment]
thank you leastprivilege
