### ISSUE TITLE
Urgent-Infinite Redirects between Identity Server and Website

### ISSUE THREAD

**Issue by pirovorster** [IdentityServer/IdentityServer3#1656]
We are currently having an issue where our site goes into an infinite loop between identity server and the website. I presume that this happens because it fails to set the cookie and therefore tries to login. 

Its however strange and inconsistent. It only happens for some users and sometimes it happens on all browsers for them. Other times it only happens on 1 browser and the rest works for that user. Sometimes it happens for a user on one machine but not on another using the same browser. It only started recently.

Ive read and it seems to match our issue:
https://github.com/IdentityServer/IdentityServer3/issues/648
https://github.com/IdentityServer/IdentityServer3/issues/762
however the recommended solution does not seem to help.

Any other recommended workarounds?

**Comment by huysentruitw** [comment]
I think you'll have to add some more info:
- What kind of flow are you using?
- What kind of middleware are you using for authentication on the website?

**Comment by brockallen** [comment]
This either means that 1) when the token is sent back to your client app, the client app is not issuing a local authentication cookie, or 2) the user is logged in and is hitting a page that issues a 401 and thus it's triggering authentication to the token service, which then immediately returns the user back to the client app due to SSO.

**Comment by pirovorster** [comment]
Brock, we are currently running a test and live environment. Could there be
a scenario where the cookies of test and live gets mixed up and causes this
issue? I don't see how this is possible since it also happens in incognito
mode, but I know that some of the stores also caches tokes so I am
wondering if there could be some edge case that makes this happen?

**Comment by brockallen** [comment]
Not sure -- it might be an SSL issue at the test server as well (I've seen people have the infinite redirect due to that).

**Comment by pirovorster** [comment]
Its the weirdest thing. I have 2 versions of Identity server live and test.
I have a website that authenticates using the implicit flow running on
live, test, and localhost(dev). On localhost connecting to test IS3 works.
On live connecting to test IS3 works. However test connecting to test IS3
has the infinite loop. Code bases are exactly the same.

**Comment by pirovorster** [comment]
Brock, do you know of an easy way to see why the cookie is being rejected?
Im guessing you will have to hook into OWIN somewhere?

**Comment by brockallen** [comment]
I use fiddler to debug these sorts of issues.

**Comment by brockallen** [comment]
Any update?

**Comment by pirovorster** [comment]
Hi Brock, we have solved some of the redirects but still sometimes get it.
Those that we have solved was because we were using the same domain for all
staging sites but different paths. Eg www.test.co.za/site1,
www.test.co.za/site2, etc... We changed it to be site1.test.co.za,
site2.test.co.za, etc.

This morning we are getting a infinite redirect again on one of our
sites...will have to see why.

**Comment by pirovorster** [comment]
Brock, would it be a problem if 2 websites on different domains used the
same clientId (we added both urls to the redirect urls)?

**Comment by brockallen** [comment]
No issues -- that'd work.
