### ISSUE TITLE
Question: Why the Client is null when I am calling GetProfileDataAsync from UserInfoEndpoint

### ISSUE THREAD

**Issue by Condor2708** [IdentityServer/IdentityServer3#1658]
I want to know If it is ok that the Client property is null into the ProfileDataRequestContextobject when the caller is the "UserInfoEndpoint"

Debugging my code it is accesing from three different callers
"ClaimsProviderAccessToken", "ClaimsProviderIdentityToken" and "UserInfoEndpoint"

UserInfoEndpointCaller is the only one that is having the Client object with null

Thanks

**Comment by leastprivilege** [comment]
That's a bug. 

fixed: https://github.com/IdentityServer/IdentityServer3/commit/ba8273821e5f65ebbd8710187231f7cc32992042 and https://github.com/IdentityServer/IdentityServer3/commit/b09f2f7727d27bf23a561c4a5d87313e48c01e01

thanks!

**Comment by Condor2708** [comment]
Thanks to you
Do you know if it will be published a new nuget of rc3 with the fixed bugs or the next version it will be the final release?

**Comment by leastprivilege** [comment]
I can push an RC3 now - will you test it? Would be interested if everything is working as expected

**Comment by leastprivilege** [comment]
done
