### ISSUE TITLE
How to suspend api token auth (with IS3) after initial pre-auth via authorize bearer token request?

### ISSUE THREAD

**Issue by bblunden** [IdentityServer/IdentityServer3#1659]
Hi,

We are integrating IS3 into a web app which relies on ajax calls to highly responsive apis.  We want to reduce the webapp-to-api call latency by eliminating api mw calls (for token auth from the IS3) on each request.   

We are considering performing an initial pre-auth to the api with a bearer access-token which would be be authorized by the IS3 under normal implicit flow.  After that, we would like to suspend the api mw calls to the IS3 (for token auth) and manage the session's api security via our mw.   Ideally, when the authorized access token is close to expiration we could use a refresh token to get another access token (from our mw), reauthorize with IS3, then return to our mw.

Can you please advise on the validity of this approach and on the best way to accomplish it?

Best Regards,
Brent

**Comment by leastprivilege** [comment]
I would simply enable the validation result cache on the options.

**Comment by leastprivilege** [comment]
Are you using jwts or reference tokens?

**Comment by bblunden** [comment]
Thank you for your quick response.  We are using jwts.  Does the refresh/reauth of access token in this scheme seem feasible?  Are there any considerations we should be aware of?  

Best Regards,
Brent

**Comment by leastprivilege** [comment]
caching is for reference tokens only. 

Have you set the ValidationMode to local?

**Comment by bblunden** [comment]
Yes, I set validation mode to local.  That works great!  I know by running local I loose access to token revocation prior to expiration.   Do you have a recommendation for managing token revocation while running local? 

Also, what is required for doing proper local jwts validation?  Do I need to set IssuerName and IssuerCertificate properties?  

Thanks,
Brent

**Comment by leastprivilege** [comment]
JWTs don't have a recovation feature anyways.

So either reference tokens with caching or JWTs and local.

you only need to set the authority.

https://identityserver.github.io/Documentation/docsv2/consuming/tokenValidationMiddleware.html

**Comment by bblunden** [comment]
Sounds good.  One last unrelated question... What is the best way to protect static resources with IS3?

Thanks, Brent

**Comment by leastprivilege** [comment]
you need to open a new issue for new questions.
