### ISSUE TITLE
Authorization failed after worker process reset

### ISSUE THREAD

**Issue by jrdijkstra** [IdentityServer/IdentityServer3#1660]
Hi,

We are using IdS3 for a web api. We are using the client credentials flow and access is provided by sending the access token. (reference token)
Currently the access tokens are valid for 48 hours.
However after the application pool worker process is shutdown (idle for more than 20 minutes = default setting in IIS app pool). The access token is invalid and the client can't be authorized.

Is it possible for IdS3 to authorize the access token even when the app pool worker process has ended?

Kind Regards,
Jeroen

**Comment by leastprivilege** [comment]
How are you storing the reference tokens?

**Comment by jrdijkstra** [comment]
Currently these aren't stored. It has been setup like the example: https://identityserver.github.io/Documentation/docs/overview/simplestOAuth.html

**Comment by leastprivilege** [comment]
That's why they are gone after a recycle. Check the docs on deployment.

**Comment by jrdijkstra** [comment]
Ok thanks for your responses.
