### ISSUE TITLE
ILog .DebugFormat() throws exception using SeriLog

### ISSUE THREAD

**Issue by devployment** [IdentityServer/IdentityServer3#1661]
I try to use the `.DebugFormat()` method of the ILog logger but it throws a `System.FormatException Input string was not in a correct format.` 

My configured logger is Serilog. Trying to log a structured log entry like this

`Logger.DebugFormat("Just testing: {@foo} and {@bar}", "foo", "bar");`

I'm using `v1.6.2` of IdSrv. For what I can see it uses LibLog `v2.0.1`. 

There is a ticket from @leastprivilege that sums up this exception as well, but it is related to updating LibLog to `v3.1`. https://github.com/damianh/LibLog/issues/53

Any idea why the `.DebugFormat()` method throws the exception mentioned above ?

**Comment by brockallen** [comment]
I thought the format expected {0} and {1}?

**Comment by devployment** [comment]
It's the message tamplate syntax that I used.  

https://github.com/serilog/serilog/wiki/Writing-Log-Events

Usually this works well with LibLog.

**Comment by devployment** [comment]
It w as added quite a while ago I think

https://github.com/damianh/LibLog/issues/12

**Comment by brockallen** [comment]
Well, looking at the code, it's using String.Format.

**Comment by devployment** [comment]
Ok. The @ parameterised logging was fixed a bit later

https://github.com/damianh/LibLog/pull/68
https://www.nuget.org/packages/LibLog/4.2.1

Looks like updating LibLog might help. :)

**Comment by brockallen** [comment]
We're on a newer version on dev/2.0.0 branch.

**Comment by devployment** [comment]
Ok. I'll give it a try. Are there more information about an upgrade path and possible traps?

All I found is this

http://leastprivilege.com/2015/03/29/identityserver3-vnext/

**Comment by brockallen** [comment]
Just this list: https://github.com/IdentityServer/IdentityServer3/releases/tag/2.0.0
