### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by ANEDev** [IdentityServer/IdentityServer3#1662]
Hey,
I am new about using the IdentityServer3. I have a question to the two factor authentication with IdentityServer3. Is there any example which shows me how to implement an user registration with email authentication?

Thanks a lot!

**Comment by leastprivilege** [comment]
Have a look at the custom user service samples.

**Comment by ANEDev** [comment]
Can you explain to me which part of the custom user service sample contains the email authentication, I can't find something.

**Comment by leastprivilege** [comment]
Not sure what you mean with "email authentication" - but there is a 2FA sample in the repo.

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity_2fa

**Comment by ANEDev** [comment]
I just want that a new user have to click on an activation link which he gets via mail. And that he can't login without clicking on these link.

**Comment by leastprivilege** [comment]
ok - use the sample as "inspiration".

**Comment by ANEDev** [comment]
ok thanks
