### ISSUE TITLE
Adfs login automation

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#1663]
I currently have Ids set up with our web app and it is working great. We have multiple adfs providers that users can log in with.
We now have a requirement to implement SIngle Sign On within an IPad app. The requirement is that the user would be able to select the provider from a dropdown and when they enter their domain name and password we would somehow go through Identity Server and authenticate them with their selected adfs provider (the same providers already registered in IDS) by passing their credentials directly to adfs and authenticating.  They don't want to see the adfs logon screen as its needs to be displayed within a web browser.
Is this possible and if so what is the recommended approach?

**Comment by leastprivilege** [comment]
Well - you can programmatically authenticate users with ADFS using WS-Trust. You could implement that using a custom grant at the token endpoint.

https://identityserver.github.io/Documentation/docsv2/advanced/customGrantTypes.html

The enumeration of ADFS providers for the ipad UI is nothing we provide but you would have to come up with something.

**Comment by paddyhamilton** [comment]
Thanks for the reply. I will have a look into this.
