### ISSUE TITLE
Allow Different Authentication Based on Url (Multi Tenant)

### ISSUE THREAD

**Issue by lehne** [IdentityServer/IdentityServer3#1664]
I am trying to make Identity Server provide different Authentication Options based on the URL that it is hosted on. For example, if the subdomain is *tenant1.mydomain.com* then I would look up the tenant's authentication options in a database and configure the provider.
Will the application run the Startup Configuration once per domain reliably (if I host Identity server on a url such as *tenant1.mydomain.com/identity*) or will this method not work?

<code>

    private void ConfigurePlugins(IAppBuilder pluginApp, IdentityServerOptions options)
    {
    //ideally lookup authentication options in database here
    var adfs = new WsFederationAuthenticationOptions
    {
    	AuthenticationType = "adfs",
    	Caption = "Azure AD",
    	SignInAsAuthenticationType = WsFederationAuthenticationDefaults.AuthenticationType,
    
    	MetadataAddress = "https://login.microsoftonline.com/something/federationmetadata/2007-06/federationmetadata.xml",
    	Wtrealm = "urn:https://localhost:44333"
    };
    
    pluginApp.UseWsFederationAuthentication(adfs);
    
    }
</code>

**Comment by brockallen** [comment]
I've never tried that -- the only thought I can offer is to perhaps use the overload of `Map` that accepts a delegate to choose if the branch in the middleware shoul[d be taken. In the `Map` config then you should be able to have different config for a different instance of IdSvr middleware.

**Comment by lehne** [comment]
Thank you!--I'll try that route. I haven't been able to think of another way to make it work. I'll post the code here if it works.

**Comment by lehne** [comment]
So it appears that I cannot use that to dynamically configure the system as I do not have access to the OWIN context when I need it.
```C#
    app.MapWhen(ctx => IsValidTenant(ctx), app2 =>
            {
        //no access to OWIN context here so cannot add tenant specific WsFederationAuthenticationOptions
    }
```
I will have to loop through the tenants on 'Startup' and add a 'MapWhen' for each one that is configured. When adding a Tenant, I will have to restart the application in order to add the new options. Any ideas on how to avoid that?

**Comment by brockallen** [comment]
@damianh has some code to show how to re-build the OWIN pipeline dynamically. Search his blog.

**Comment by damianh** [comment]
Have a look here
https://github.com/IdentityServer/IdentityServer3/issues/1439#issuecomment-127511093
