### ISSUE TITLE
Protecting Static Client Resources

### ISSUE THREAD

**Issue by bblunden** [IdentityServer/IdentityServer3#1665]
What is the best way to protect static resources with IS3?

**Comment by bblunden** [comment]
We are considering putting protected resources in "protected" folder and then checking for it's route in the request via our mw.  If detected, our mw would set a 401 response which would trigger the IS3 mw and cause a redirect to login page.  Does this sound like a reasonable approach?

Thanks, 
Brent

**Comment by brockallen** [comment]
Why not just check for the user being authenticated in some middleware? That sounds similar.
