### ISSUE TITLE
Google oauth not working with custom google app

### ISSUE THREAD

**Issue by dzolnjan** [IdentityServer/IdentityServer3#1666]
I'm simply trying to switch one of sample project (UserService-AspNetIdentity) from existing google app to my own.

1) I've created new app in google console and set the 'Redirect URIs' to https://localhost:44333/core/signin-google

2) replaced google clientid and secret in GoogleOAuth2AuthenticationOptions

Auth process starts ok, I get to the consent screen on google and when redirected back to app I get error message: There was an error logging into the external provider. The error message is: access_denied

http://scr.hu/0ptw/0j574

I get same error with 'MVC Authentication' sample.

When using default google app that comes with sample it works fine!
Is there something else except redirect uris in google app console that needs to be enabled perhaps?

**Comment by dzolnjan** [comment]
Replacing Twitter app with my own works fine.

**Comment by dzolnjan** [comment]
Ok, there was one more step required in google app > enabling Google+ API !

**Comment by RichardSilveira** [comment]
Thanks a lot @dzolnjan! I think that this could be documented in somewhere...

**Comment by brockallen** [comment]
> I think that this could be documented in somewhere...

Our docs accept PRs.
