### ISSUE TITLE
Resource STS / Federation Gateway with two IdentityServers v3

### ISSUE THREAD

**Issue by dturska** [IdentityServer/IdentityServer3#1667]
Thank you for creating IdentityServer.   

I have a question about Federation Gateway with two IdentityServers v3.    I watched the pluralsight course "Identity and Access Control in ASP.NET 4.5" and in particular the Federation Patterns - Federated Sign-In.  

I would like to set this up using two identityservers v3.   

I have setup an example project at https://github.com/dturska/FederationGateway2IdentityServer3. 

 I am confused with how I should code the startup.cs in the ResourceSTS project. 

Should I be configuring this:

1) In the IdentityServerOptions.AuthenticationOptions.IdentityProviers  with custom middleware like app.UseGoogleAuthentication, but for IdentityServer v3  like app.UseIdentityServerAuthentication. (does this exist?)

2) In the IdentityServerOptions.AuthenticationOptions.IdentityProviders with the Microsoft.Owin.Security.WsFederation middle ware.

3) By Using the Thinktecture.IdentityServer3.WsFederation plugin using IdentityServerOptions.PluginConfiguration. like the example SelfHost (InMem with WS-Fed) 

Thanks again

**Comment by leastprivilege** [comment]
You would use the OpenID Connect middleware to connect the resource STS to the other STS.

**Comment by brockallen** [comment]
@dturska all set?

**Comment by dturska** [comment]
Thank you for your response. I haven't had time to implement it using the OpenID Connect middleware yet, I am hoping to get back to it today or tomorrow.  I will update this with my result.

**Comment by dturska** [comment]
In the other STS would I need to define the Resource STS as a client?  If so, what flow should I use when defining the client?

**Comment by brockallen** [comment]
Yes, the R-STS is a client to the IdP-STS. It's configured as an implicit client.

**Comment by dturska** [comment]
Thank you exactly what I needed to know. This can be closed.
