### ISSUE TITLE
Question: IdentityServer3 with SQL Server Reporting Services

### ISSUE THREAD

**Issue by HJoost** [IdentityServer/IdentityServer3#1669]
Hi,

we are currently developing an Angular application that communicates with an ASP.Net WebApi. As Authentication Provider we use IdentityServer3 together with ADFS what works really well. 

Now we want to add some SSRS Reports to this project. Our favorite solution would be to do SSO for the Angular app and also use the token for the SSRS. Has anyone done this before or even better has a link refering a tutorial?

Thank you!

Helmut

**Comment by brockallen** [comment]
I have a customer that's trying to do this. I don't know SSRS works, but my recollection is that they built some custom login provider for SSRS. I don't know if they ended up being successful or not.

**Comment by aronblum** [comment]
Hey Helmut,

We are trying to implement the same thing. Any luck so far?

Cheers,

Aron

**Comment by HJoost** [comment]
Hi Aron,

we didn't start to try it yet. For now we found another solution:

Our WebApi Controller is authorized to download the Reports as PDF and the user can download the PDF via the WebApi. This is for us the easiest way, as well as it has some disadvantages. Perhaps we try it later this year.

Helmut

**Comment by sid08** [comment]
Hello,

Any luck on this? We are trying to do the same. We have implemented SSO on our application using IdentityServer3 and would like to pass on the token to ssrs reporting service to display the report without the need of authenticating again. Is it possible to pass the token to reporting service? Currently we use Windows authentication on SSRS reports.

Any help will be gladly received.

Thanks.
