### ISSUE TITLE
After application restart I'm logged into my Client Application but not in IdentityServer

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#1670]
Hello,

After application restart I'm logged into my client application but not in identity server. I'm authorized into my client application using cookie. I know that identityServer also uses cookie but probably there is also something (session state or something?) stored in memory on IdentityServer so after application restart I'm not authorized.

It might be a problem in production enviroment.

**Comment by leastprivilege** [comment]
check the docs on deployment

**Comment by pawepaw** [comment]
Did you mean this https://identityserver.github.io/Documentation/docs/advanced/deployment.html ? 
I understand that I should implement or use some caching mechanism? 

What is stored in memory cache that will be cleared and user wont be authorized?

**Comment by leastprivilege** [comment]
we are stateless unless you need a feature that requires state.

wrt to your cookie. that works. Maybe a machine key issue?

**Comment by brockallen** [comment]
@pawepaw all set?

**Comment by pawepaw** [comment]
Sorry I didn't have time to check it. I'll check it and give you result. But from what i remember I do not store anything outside of cookie.

**Comment by pawepaw** [comment]
@leastprivilege Machine key issue?

**Comment by pawepaw** [comment]
@brockallen 

I have registered custom services:
UserService, UserManager, userStore, CustomDbContext
And everything should be stored in db.

Any other clues?

**Comment by brockallen** [comment]
Check for the idsvr cookie -- it's the cookie used for authentication with IdentityServer. If it's there and an app recycle of IdSvr doesn't trust the cookie, then it sounds like a machine key issue on your host.

**Comment by brockallen** [comment]
Any update?

**Comment by pawepaw** [comment]
Yes there is idsrv cookie and i got error "login_required" on javascript silent token renew. About machine key issue, did you mean that after recycle i

I am not sure about reproduction steps but from what I observed it's something like this:

1. User is logged in into ASP.NET MVC IdentityServer client
2. Separate javascript client on the same page calls silent token renew (with success).
3. Application deployment occurs.
4. User is still logged in into MVC client and Idsrv cookie exists.
5. javascript client tries to call silent token renew (with failure - login_required error). 

IdentityServer and MVC Client are hosted on the same machine and I don't have webfarm. There is only one IdentityServer instance. 

Machine key setting - AutoGenerate,IsolateApps

**Comment by brockallen** [comment]
With silent renew you'll get an error if either the user is not logged into IdSvr or if they need to provide consent.

**Comment by pawepaw** [comment]
Ok, I found that in oidc there is 5 seconds timeout for silent renew. If application is re-deployed (or recycled) it takes more than 5 seconds to wake up.

I have to check if it's the only reason of my problem.
