### ISSUE TITLE
Service Factory Docs

### ISSUE THREAD

**Issue by timchaffee** [IdentityServer/IdentityServer3#1671]
We have IdentityServer3 working in our dev and test environment. It works great - thank you for creating it! 

We are getting ready to move to production and I have a question about this page in the docs: https://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html

We have created all the Mandatory items but it is not clear if the "Mandatory for production scenarios " items are required to be custom for production or if you can use the default in-memory implementations in production and still be secure. Does "Mandatory for production scenarios" = 

A) These are required but we gotcha covered with defaults and you can use them in production
or
B) Don't use these defaults implementation in production they are only for testing
or 
C) something else

Thanks,
Tim

**Comment by leastprivilege** [comment]
It's not about being secure - the in-memory ones are for testing - since they hold everything **in memory**.

When your server recycles or you use load balancing - this won't work.

If you don't use the feature, then you can go with the default implementations.

**Comment by timchaffee** [comment]
Thanks for the quick reply. I am going to read the CONTRIBUTING.md now :)
