### ISSUE TITLE
ADFS and WsFederation help

### ISSUE THREAD

**Issue by djodadof2** [IdentityServer/IdentityServer3#1673]
I'm having trouble getting federation with an ADFS server off the ground. What I'm trying to do is fairly simple in principle: have my IdentityServer instance operate as a Relying Party to an ADFS instance so that a client authenticating with my IdentityServer can use their ADFS server as the ultimate authenticator.

Configuring my IdentityServer seems rather trivial:

var adfs = new WsFederationAuthenticationOptions
            {
                MetadataAddress = "https://yaddayaddayadda/federationmetadata/2007-06/federationmetadata.xml",
                SignInAsAuthenticationType = signInAsType,
                Wtrealm = "Foo",
                AuthenticationType = "adfs",
                Caption = "ADFS (WsFederation)"
            };
            app.UseWsFederationAuthentication(adfs);

This works to some extent, in that the ADFS server receives the request and recognizes the wtrealm identifier and the associated RP. However the ADFS server seemingly cannot parse the rest of the request and is logging a 364 error (request is invalid).

My guess is that the ADFS server needs more configuration data from the RP, such as a metadata URL. I suppose that ultimately this is a certificate issue because there is an encrypted string in the request parameters that, if the ADFS server was unable to decrypt, would give the kind of error I'm seeing.

Does anyone have tips on this problem, or on configuring IdentityServer as a Relying Party on an ADFS server in general?

Also, I'm not tied to wsfed for this. I could use the oauth2 endpoint on the ADFS server so if there is advice on that I'd take it as well.

**Comment by brockallen** [comment]
When you use `UseWsFederationAuthentication` this means you are configuring your IdSvr3 host as a WS-Fed RP to some STS.

The requirement you describe above is what you want your IdSvr3 to be a STS to ADFS (so in short, the roles are reversed). To do this you need to use the WS-Fed plugin for IdentityServer: https://github.com/IdentityServer/IdentityServer3.WsFederation

**Comment by djodadof2** [comment]
Thanks, Brock. In fact, I do want the IdSvr3 to act as a RP and trust the ADFS.

The scenario I want is this... a client accesses a resource (a login method in this case) that is protected with Authentication with a trust to our IdSvr3. They are redirected to our IdSvr3 for authentication. On the basis of their clientID they are then redirected to  one of many ADFS servers the IdSvr3 is configured to trust (this is a multitenant scenario). The ADFS authenticates them and redirects back to our IdSvr3, now with a token. Our IdSvr3 authenticates on the basis of the ADFS' token and redirects back to the original resource, now with a token from our IdSvr3. The client now accesses the resource and logs in to the application.

The trouble I'm having is that the redirect to the ADFS produces an error there. I am misconfiguring the trust relationship where our IdSvr3 acts as a relying party and trusts the ADFS.

**Comment by brockallen** [comment]
Not sure then. Perhaps enable logging in your ADFS then check the log to see what the real problem is.

**Comment by djodadof2** [comment]
I've noticed that much of configuring trusts can be done using metadata endpoints. I've added the wsfederation plug in to IdSrv3 so that it will offer the wsfed metadata but the ADFS doesn't accept the file. Is there an easier, and better, way to have IdSrv3 offer metadata that will make federation with ADFS work?

**Comment by brockallen** [comment]
I'd suggest setting up a stand alone MVC app and getting that to work with ADFS using the WsFed middleware. Once you get that working, it should be easy to move it into IdSvr.

**Comment by djodadof2** [comment]
Any advice on configuring the ADFS server? I get an invalid request error regardless of what I've tried.

For instance, I'm guessing that the value for the WS-Federation Passive Endpoint should be along the lines of "https://myIdPserver.com/core/connect/authorize" but I really have no idea.

**Comment by brockallen** [comment]
You'd have to check w/ MSFT on that since it's their product. I remember the first time I ever set that up it took me a good number of hours to understand it all.

**Comment by djodadof2** [comment]
Update:

It turns out that the wtrealm value in a request needs to be either a legit URL or any string starting with "urn:". We were using our own string identifiers for relying parties, which the ADFS server actually understood, but then the server would reject the request anyway because the wtrealm value was "malformed".

One last thing: what is the endpoint in IdentityServer that the ADFS can use to send back its token, so that the loop gets closed and IdentityServer will generate its own token and redirect the client back to the originally requested resource?

**Comment by brockallen** [comment]
You can configure the callback path in the WsFed middleware. If you don't, then it just uses the base path of the OWIN hosting context.

**Comment by djodadof2** [comment]
Thanks, Brock. I'm not sure you understood my question.

IdSvr is acting as a relying party to an ADFS server. The client is sent to the ADFS from the IdSvr login page, authenticates with the ADFS server, and needs to be redirected back to IdSvr where the incoming claims will be used to produce a new token and redirect back to the original request. What is the endpoint for the ADFS server to redirect back to when it has finished authenticating?

**Comment by brockallen** [comment]
That's the scenario I answered. Check our samples -- we have a WS-Fed IdP configured in there. The callback URL to the RP/IdSvr is the IdSvr hosting base path.
