### ISSUE TITLE
Mixing OpenIdConnectAuthentication with Resource Credentials flow

### ISSUE THREAD

**Issue by freudj76** [IdentityServer/IdentityServer3#1674]
Hi,
Following is my setup. I have an MVC app which hosts the login screen. It supports local user sign-in as well as external idps (facebook & google). So on the login screen, you can either enter a username and password, or click on facebook or google buttons to login with external idps.

If the user uses local accounts, the following code is executed. 

    var response = await client.RequestResourceOwnerPasswordAsync(model.UserName,   model.Password, "myscope");
    var claimsIdentityFromToken =ValidateJwtToken(response.AccessToken);

This code works just fine. If the user clicks on google or facebook button, the following code is executed

    var properties = new AuthenticationProperties { RedirectUri = Url.Action("ExternalLoginCallback", "Account")};
    HttpContext.GetOwinContext().Set("LoginProvider", provider);
    HttpContext.GetOwinContext().Authentication.Challenge(properties, OpenIdConnectAuthenticationDefaults.AuthenticationType);

This successfully issues a 401 challenge, and this challenge is intercepted by the mw in the RedirectToIdentityProvider handler as follows. Here, the idp is appended to the AcrValues as follows

    RedirectToIdentityProvider = async n =>
    {
        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
        {
             var loginProvider = n.OwinContext.Get<string>("LoginProvider");
             if (loginProvider != null)
             {
                n.ProtocolMessage.AcrValues = "idp:" + loginProvider;    
             }
        }
     }

(Note that the Authority for the middleware is the IdentityServer, not the local login page)

    Authority = ConfigurationManager.AppSettings["StsAuthority"],

This works fine as well, IdentityServer skips the login dialog, takes the user to the external idp login screen, and after successful authentication, redirects.

However, there are some use cases which I am having a difficult time with. I will list them as bullet points.

1- Everything is great if the user specifically comes to the login screen. However, let's say I have an action link on an anonymous page which takes the user to a controller that needs authorization. The Authorize filter attribute issues the 401, and then this is intercepted by the middleware, and the middleware takes the user to the Identity Server login page, not the local user page. Since I need to use the local page and remote control the identity server by acr values (business requirement), this does not work for me. Catching the redirect event in RedirectToIdentityProvider and overriding the AuthorizationEndpoint did not work for me. Following is what I tried

    if (loginProvider == null)
    {
       //For test purposes, if loginprovider is not set, this is a local account login which should be using    resource owner flow with local page
        n.ProtocolMessage.AuthorizationEndpoint = "https://localhost:44301/Account/Login";
    }

What am I missing?

2 - If a local user is trying to log out, there is no need for me to go back to the identity server, I just need to clear the access token (the one given me by the resource owner flow), right? Here is how I do it.

    if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
    {
        var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
        if (idTokenHint == null)
        {
            //assume local login, since I couldnt find a way to get an idtoken with resource owner
           n.OwinContext.Authentication.SignOut();
           n.HandleResponse();
        }

    else
    {
     n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
     }    

Is this the right way to sign out locally? Call signout() and then call n. HandleResponse()?

3 - Given above code, a user using an external login is still forwarded to the identity server logout confirmation page even if the idtokenHint is populated and PostLogoutRedirectUri is set. My understanding from the doc and the issues was that these two control whether we can skip the logout confirmation page? Am I missing another thing here?

4- The more I play with this, the more I believe that mixing resource owner flow with OpenIdConnect middleware is not the best idea. Instead of using the middleware to handle most requests behind the scenes, implementing callbacks and handling them within the application gives me more control. Any opinions regarding this statement?

5 - Given the increased interest in IdentityServer (even the asp.net team is paying a lot of attention this great project), are there any plans for an another pluralsight course which is identity server centric? (I am sure you guys don't have much else to do, right :))

Thanks much again for this project and I am ready to help with documentation, samples, etc.

**Comment by brockallen** [comment]
1 -- did you try configuring the OIDC middleware as passive?
2 -- depends if you also want to log them out of the STS.
3 -- check the IdSvr logs and see what the error message is -- it might tell you why.
4 -- Mixing them is certainly not how the protocol was designed
5 -- unsure

**Comment by freudj76** [comment]
Thank you for your reply. I will switch to using callbacks instead of relying on the middleware.
