### ISSUE TITLE
Protecting root url of Single Page App

### ISSUE THREAD

**Issue by benjaminettori** [IdentityServer/IdentityServer3#1675]
Hi

this is a probably a very basic question, but I would really appreciate some guidance. I am trying to protect the root url of my application through Identity Server. Ideally I would like to redirect the user to the default IdentityServer login page. 

I am trying to protect access to the root page by using the resolve property when setting up my routes.

    $routeProvider.when('/players', {
        templateUrl: '/FrontEnd/Templates/PlayerList.html',
        controller: 'PlayerListController',
        resolve: function() {
            var deferred = $q.defer();
            deferred.resolve();
            window.location = 'https://localhost:44301/identity/connect/authorize?client_id=baseballStats&redirect_uri=https%3a%2f%2flocalhost%3a44300%2f&response_mode=form_post&response_type=id_token+token&scope=openid+profile+roles+baseballStatsApi&nonce=xyz';
            return deferred.promise;
        }
    });

This will redirect me to the login screen. However, once I log in I get the following screen.

![image](https://cloud.githubusercontent.com/assets/9013288/9026687/fdb8d0b2-3905-11e5-9278-2013f9bd4978.png)

It turns out IdentityServer is using the CONNECT verb instead of GET when redirecting to the root url of the application. 

Anybody have an idea of why that is and how to successfully redirect back to the originating url?

Thanks in advance.

**Comment by brockallen** [comment]
I'd suggest doing some more HTTP tracing. You're using this: `response_mode=form_post` which tells IdSvr to POST the token back to your client app -- I can't tell if you're getting that far or not.

**Comment by benjaminettori** [comment]
Hi Brock

thanks for your response. Here is a screen capture from fiddler. Hope it helps

![image](https://cloud.githubusercontent.com/assets/9013288/9077017/44174e9c-3af7-11e5-8070-f1627012179f.png)

**Comment by brockallen** [comment]
Not sure.

**Comment by benjaminettori** [comment]
Are there any specific code samples you could point me to showing how to use the identity/connect/authorize url correctly in my case?

Thanks!

**Comment by brockallen** [comment]
We have some samples here: https://github.com/IdentityServer/IdentityServer3.Samples

**Comment by benjaminettori** [comment]
Thanks. I saw that this was an issue with response_mode, as you mentioned
in your first post. If I remove it, I can navigate back to the application.
