### ISSUE TITLE
Add option for cookie prefix by Client

### ISSUE THREAD

**Issue by appetere** [IdentityServer/IdentityServer3#1677]
The `CookieOptions` class has a `Prefix` property.  Could the `Client` class have a similar option for an additional cookie-prefix too?

The reason for this would be for different clients, which all use the same browser, to have separate authentication sessions with IdentityServer3.

For example, in my implementation the user accesses a WebForms application through a browser, and also uses Microsoft Office Add-Ins, which use the `WebBrowser` control via WPF applications.

When using Internet Explorer, the cookies are shared, so authenticating in one application means you are also authenticated for the other applications.  I would like control over whether this side-effect is allowed or not and think a Client-specific cookie-prefix would allow this.

I have tried using the CEFSharp browser within the WPF application, which allows me to isolate the cookies by client, but there are significant deployment issues with CEFSharp (in our environment) that makes using the built-in `WebBrowser` control more desirable.

**Comment by brockallen** [comment]
I'm not sure that makes sense -- if you had a different authentication session per client then there would be no SSO (which is the main purpose of IdSvr).

**Comment by appetere** [comment]
The problems I am trying to address are consistency and security:

Consistency with different browsers:
- If the user logs into the web application using **Internet Explorer**, then the WPF application (using implicit flow via the Internet Explorer-based `WebBrowser`) is authenticated via the shared cookie and can get a token.

- If the user logs into the web application using **Chrome or Firefox**, then the WPF application will not see the auth cookie and will require the user to authenticate again.

Security:
- Some users may want to log-in the WPF Office Add-Ins (for example for a secretary to process their emails) but not log-in the web application, which contains sensitive information.  But if the auth cookies are shared, this cannot be done.

I had tried using `CEFSharp` instead of the built-in `WebBrowser` control, which solves the above issues but introduces problems during ClickOnce deployment of Add-Ins.  So I just thought that allowing each client to specify an optional cookie name prefix would be a more general solution.

**Comment by brockallen** [comment]
Are you all set on this issue?

**Comment by appetere** [comment]
No, I don't have a simple solution yet.

I would like to use the `WebBrowser` control to log-in my WPF applications, but this has a side-effect that any web applications using Internet Explorer are silently authenticated because of the IdentityServer3 auth cookies being shared, because the `WebBrowser` uses Internet Explorer underneath.

I have tried using `CefSharp` at an alternative to `WebBrowser`, but because this library *has* to be targeted to x86 or x64 and it is being used in Add-Ins for Office, where Office is usually 32-bit (but some use 64-bit) and might be running on 32-bit or 64-bit windows ... takes a breath ... it makes deployment difficult for us, and difficult for our users to select which version they need.

So I thought that sticking with `WebBrowser` would be far easier technically.  And if each Client had an optional prefix (or suffix) to the global auth-cookie name, we could avoid the side-effects described above.

**Comment by leastprivilege** [comment]
discuss/todo or wontfix?

**Comment by brockallen** [comment]
I don't think it makes sense, unless I'm still not understanding the request.

**Comment by appetere** [comment]
All users of our system will access it via a web-browser.
Many of the same users will also use Office Add-Ins to access the system, from the same PC.
Both use IdentityServer3, with the Office Add-Ins using the `WebBrowser` control.

Using any browser *except* Internet Explorer:
- If I logout in the web-browser, the Office Add-In will be unaffected & remain logged in.

But when using Internet Explorer:
- If I logout in the web-browser, the Office Add-In's session with IdentityServer3 will also be ended, because the `WebBrowser` control is basically IE and shares cookies with IE.

I did discuss this problem with Dominick many months ago, and he suggested using an alternative to `WebBrowser` such as CefSharp.  This does prevent the problem, since CefSharp has its own cookie store.

But using CefSharp in the context of VSTO / Office Add-Ins makes deployment hard, so I was keen to stick with `WebBrowser` if possible.

So if the Add-In Client could have an IdentityServer3 cookie with a different name to the browser client, the problem of shared cookies would go away.

It won't stop us using IdentityServer3 if this isn't desirable from your point of view - but it will help reduce our support calls from confused IE users!

**Comment by brockallen** [comment]
Sounds like more an issue to take up with Microsoft. Sorry.
