### ISSUE TITLE
Securing SOAP Web Services ( old .net 1.1 web services )

### ISSUE THREAD

**Issue by rezakhanmirzaee** [IdentityServer/IdentityServer3#1678]
I have a soap web service and I have to secure it using Identity server 3 . I send access token from client to my web service using soap header , then in the web service part I validate it using access token validation endpoint . If it was successful I permit the client to use web service.Is this a correct solution to my problem?
(There are samples for ASP.NET Web API and WCF but I haven't found any sample or documentation for this scenario)
Thanks

**Comment by brockallen** [comment]
I don't know of any samples that do exactly what you want. I'm sure it'd not be hard to stitch that together, though.

**Comment by rezakhanmirzaee** [comment]
I have implemented it but I don't know if the workflow that I mentioned is correct or not from security perspective . I get id_token and access_token from identity server then send access_token in soap header and in the web service I check the access_token using access token validation endpoint .

**Comment by brockallen** [comment]
Sounds legit.

**Comment by rezakhanmirzaee** [comment]
Thank you
