### ISSUE TITLE
Question: EF Sample why does it require UserService to be configured?

### ISSUE THREAD

**Issue by OutOfTouch** [IdentityServer/IdentityServer3#1679]
I am combining the EF Sample Project and the WebHost IIS sample project from IdSvr samples, I will probably have to work in what I need from the MembershipReboot example, but I really don't understand why UserService needs to be configured for Client Credentials Flow if that is all I am using?

**Comment by brockallen** [comment]
For client credentials only, you're correct.

**Comment by OutOfTouch** [comment]
I am currently getting this error: UserService not configured
I only have one scope, and one client defined, is there something I might have missed from the EF examples that I don't need.

**Comment by brockallen** [comment]
Configure a dummy one (perhaps the in-memory one). Normally you have users, so we have this requirement (albeit not 100% of the time required, as your case illustrates).

**Comment by OutOfTouch** [comment]
Ok thanks I will create a dummy one then, for now untill I add in MembershipReboot stuff later thanks man! Great API too btw.
