### ISSUE TITLE
Hook for Cascading Logout?! - Identityserver with external IdentityProvider

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1680]
Hello,

How can I force a logout cascading from the actual Identityserver to the federated IdentityProvider?

Our main IdentityServer is using an external IdentityProvider which is also an identityserver3 instance but configured using WsFederationPlugin. The WebApplication only "knows" of the IdentityServer not of the IdentityProvider.

Logout in the WebAppClient is done via:
this.Request.GetOwinContext().Authentication.SignOut("Cookies");
return this.Redirect("/");

this does not trigger logout in the IdentityProvider but only in the IdentityServer! 

How can one cascade/trigger the logout to the IdentityProvider?
Is there any example around?

Appendix: 
As I cannot find the hook to cascade I try now to call logout within the Webclient directly on the Wsfederation Plugin.
But there must be a more correct way to do it. Any hint`?

**Comment by davidmrichter** [comment]
As I cannot find the hook to cascade I try now to call logout within the Webclient directly on the Wsfederation Plugin.
But there must be a more correct way to do it. Any hint`?

**Comment by brockallen** [comment]
When you use an external IdP to authenticate, we trigger that midfdleware to signout (at the Katana layer).

**Comment by davidmrichter** [comment]
We thought that too in the beginning, but I am very sorry,  that exactly does not happen!

**Comment by brockallen** [comment]
There is a related issue for this: #1000. I'll leave this open as something to investigate for 2.1.

**Comment by davidmrichter** [comment]
Thank you for your feedback.
The issue might not apply as we have only one PostLogoutRedirectURI configured.

Here is our Client Config in our IdentityServer
 new Client
				{
					ClientName = "Browser Application Angle",
					Enabled = true,
					ClientId = "CodeClient",
					ClientSecrets = new List<ClientSecret> { new ClientSecret("secret".Sha256()) },
					Flow = Flows.Hybrid,
					ClientUri = "http://www.thinktecture.com",
					RequireConsent = false,
					AccessTokenType = AccessTokenType.Jwt,
                    AllowRememberConsent = false,
                    UpdateAccessTokenClaimsOnRefresh = false,
                    RefreshTokenUsage = TokenUsage.ReUse,
                  
					// DNS for the WebApplication
                    RedirectUris = new List<string> { Configs.WebAppRedirectURI},
					PostLogoutRedirectUris = new List<string> { Configs.WebAppRedirectURI},
				},

We found that the Logout to the external IDp is never triggered.

AuthenticationController.cs
 public async Task<IHttpActionResult> Logout(string id = null)
        {
.....
 SignOutOfExternalIdP();
  private void SignOutOfExternalIdP()
        {
            // look for idp claim other than IdSvr
            // if present, then signout of it
            var user = User as ClaimsPrincipal;
            if (user != null && user.Identity.IsAuthenticated)
            {
                var idp = user.GetIdentityProvider();
                if (idp != Constants.BuiltInIdentityProvider)
                {
                    context.Authentication.SignOut(idp);
                }
            }
        }

This is never being called all though idp claim is set to "external".
(i cannot see corresponding logs in the external Idp)

Maybe I configured something wrong:

IdentitySErverConfig to external Idp
var adfs = new WsFederationAuthenticationOptions
			{
				AuthenticationType = "Nevis",
				Caption = "Nevis",
				SignInAsAuthenticationType = p_SignInAsType,
                MetadataAddress = Configs.NevisSurrogateURI + "/wsfed/metadata",
				Wtrealm = "urn:testrp",
				


IDP (IdentityServer3 instance with WsFed Plugin) Configuration

new RelyingParty
				{
					Realm = "urn:testrp",
					Name = "OurIdentity Server 3 instance",
					Enabled = true,
                    ReplyUrl = Configs.IdentityAccessServiceURI,
					TokenType = TokenTypes.Saml2TokenProfile11,
                    // one minute so that the IdentityServer can catch up but not longer
					TokenLifeTime = 1, 
                   
Is there something missing in the config? Is there an code example for cascading logout configuration?

Thank you

**Comment by davidmrichter** [comment]
Solved it. I had on both idServer instances an overwritten UserService which was not properly done. Debugging into idserver source showed that the "names" of the both instances were not aligned.

So this is no issue neither bug.
