### ISSUE TITLE
Plugin for SimpleMembership?

### ISSUE THREAD

**Issue by GarryLenz** [IdentityServer/IdentityServer3#1681]
Is there a plugin for SimpleMembership available or in the works?

**Comment by brockallen** [comment]
No and no. If you build one, feel free to blog and we'll link to it from our docs.

**Comment by GarryLenz** [comment]
We'll use MembershipReboot if it is ready. I noticed that there is a "brockallen/BrockAllen.MembershipRoot" and "IdentityServer/IdentityServer3.MembershipReboot". Which version do you recommend that we start development with?

**Comment by brockallen** [comment]
MR is separate from IdSvr. The latter repo you mention bridges the two.
