### ISSUE TITLE
Question: SSL Cert Error with the cert in the Trusted Root and Console Client Credential Sample

### ISSUE THREAD

**Issue by OutOfTouch** [IdentityServer/IdentityServer3#1682]
I am using the Console Client Credentials  Flow from the samples to talk to my own IdSvr,
I created a cert with makecert.exe and imported it to Trusted Root Certification Authorities/Certificates both Current User and Local Computer and I am getting this error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel, The remote certificate is invalid according to the validation procedure
IE also sees it still as an untrusted Cert so I am not sure what I did wrong , I am also hosting IdSvr in IIS express. I should add that embedded the pfx into the dll.

**Comment by OutOfTouch** [comment]
I don't know why but when I went to a non embeded pfx it works.

**Comment by OutOfTouch** [comment]
Do embeeded certs just always show as not trusted?

**Comment by brockallen** [comment]
For SSL, I don't know what you mean by embedded. You configure the cert in the certificate store, then you configure http.sys/IIS with it. If it's self signed, then you also need to establish trust with it by putting the public key portion in the trusted root CAs or in trusted people.

**Comment by OutOfTouch** [comment]
I was confusing the signing cert with the ssl cert. I do have one more question: Does the signing cert need to be trusted and in the cert store or can it just be in the app bin directory?
