### ISSUE TITLE
Server sessions in Identity Server 3

### ISSUE THREAD

**Issue by tarunvd** [IdentityServer/IdentityServer3#1683]
Can I use server sessions with Id. Srv. 3 at all? 

This is related to the following response by @brockallen : 

https://github.com/IdentityModel/Thinktecture.IdentityModel/issues/132#issuecomment-127220683

I have tried this by implementing IAuthenticationSessionStore and using the implementation in app.UseCookieAuthentication() as described here :

http://www.cloudidentity.com/blog/2014/05/11/owin-protocol-middleware-cookies-and-reference-mode-sessions-we-need-your-feedback/

and here :

https://gist.github.com/vibronet/90d4646c273930ff12d4

Have done this before app.UseIdentityServer() as below :

 app.UseCookieAuthentication(
    new CookieAuthenticationOptions
  {
         SessionStore = 
         ... (an instance of IAuthenticationSessionStore implementation)

app.UseIdentityServer(options);

where options is an IdentityServerOptions object.

However, I can login from an app. (using this server) and no implemented method of IAuthenticationSessionStore gets called. 

So, is it possible to implement server sessions with Id. Srv. 3 with the above interface (with some modifications?) or is there any other way please to do this. Or is it not possible at all?

**UPDATE - About what we are trying to achieve :**

We have multiple apps. using an identity server 3 implementation for open id authentication. 
**Goals** :

**1. Cross-app consistent session sliding expiration.** So, whenever a user visits a page on any of the apps., their session must be renewed across all apps. 
Presently, there is inconsistency regarding this across apps., as the sliding expiration only renews the user's session for that app.

**2. Reduce the size of browser cookie.** We are having multiple custom claims from each app being added, making the payload on each request  heavy. 

**3. Cross-app session control**. We want to be able to kick a user out of all apps. (possibly on all of their devices)

Please also suggest if there are ways to achieve these without server sessions.
Any help would be really appreciated.
(Since this is not related to IdentityModel, I have posted the query here.)

**Comment by mvalipour** [comment]
@brockallen

IdentityServer3 does allow passing all sorts of options to be used for CookieAuth, but not session store.

https://github.com/IdentityServer/IdentityServer3/blob/06ab9cf55996444c89f1aa2db61aba8646ebcf8c/source/Core/Configuration/AppBuilderExtensions/ConfigureCookieAuthenticationExtension.cs#L40

Any hope it would support `SessionStore` to be provided on `CookieOptions`?

**Comment by brockallen** [comment]
I'll leave this open and assign to 2.1 as something to consider.

**Comment by brockallen** [comment]
We have an open PR for this: https://github.com/IdentityServer/IdentityServer3/pull/1839

Can you check if this will satisfy what you need?

**Comment by mvalipour** [comment]
@brockallen Yes that's submitted by me and it's actually linked to this issue :)

**Comment by brockallen** [comment]
Well, i was asking @tarunvd since he was the OP :) 

If the PR is what you need, then I'm looking to close this issue. We'll be accepting the PR for 2.1.

**Comment by mvalipour** [comment]
@brockallen oh my bad, it wasn't clear that we are part of the same team :)
please go ahead and close this issue if need be

**Comment by brockallen** [comment]
Ok, thanks.

**Comment by tarunvd** [comment]
@brockallen Yeah, @mvalipour had implemented what we needed in the PR #1839

Thanks a lot for attending to the issue :+1:
