### ISSUE TITLE
SSL certificate for hosting Identity Server in IIS

### ISSUE THREAD

**Issue by cloudybrain** [IdentityServer/IdentityServer3#1684]
I've been having a slew of problems trying to get this to work in a production environment. I don't see any documents, and I thought this would be real simple, but it just caused much grief and burden.

I used the MVC Authentication sample, the one that embeds IdentityServer into a web hostable mvc application, I figured this would be useful as I can grab membershipreboot sample, and embed the identityserver inside that to get a fully featured user authentication system. Of course I'd have to modify the identity server login page to include things like "forgot password/reset password" but it is what it is.

But when I tried to deploy, I realized a few things, you need a working SSL certificate otherwise cors won't work properly. You'd get ERR_INSECURE_NETWORK or something along those lines. And you need a DNS to associate with that SSL certificate.

So since I was setting up things for testing purpose (not production yet), I needed to spend a quick 10 bucks and configure my dns to point to the server that's hosting this application.

But now here's what I'm having a problem with.. IIS requires an SSL certificate in order for things to work. But identityserver also requires that same certificate as well.

    app.Map("/identity", idsrvApp =>
            {
                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Authentication Site",
                    IssuerUri = "https://irco.com",
                    SigningCertificate = Certificate.Get(),
                    Factory = idSvrFactory,
                    CorsPolicy = CorsPolicy.AllowAll
                });
            });

SigningCertificate = Certificate.Get() does two things:

which 1. either fetches from the trusted root certificate authorities (in my case, my code doesn't work on test server, but it does on my local machine.. in that it couldn't find ANY certificate).. or 2. fails safe and simply grabs a copied certificate straight from the bin folder. Code:

    static X509Certificate2 FindCertificate()
        {
            X509Store store = new X509Store(StoreLocation.LocalMachine);
            X509Certificate2 myCert;
            string certLocation = "";
            string password = "";
            try
            {
                store.Open(OpenFlags.ReadOnly);
                X509Certificate2Collection col = store.Certificates.Find(X509FindType.FindBySerialNumber, findValue, false);
                if (col.Count > 0)
                {
                    myCert = col[0];
                }
                else
                {
                    certLocation = string.Format(@"{0}\bin\IdentityServer\Server\Certificate\{1}", AppDomain.CurrentDomain.BaseDirectory, ConfigurationManager.AppSettings["CertificatePFXFileName"]);
                    password = ConfigurationManager.AppSettings["CertificatePFXPassword"];
                    myCert = new X509Certificate2(certLocation, password);
                }
                return myCert;
            }
            finally
            {
                store.Close();
            }
        }

I understand the need for SigningCertificate when I develop on my localmachine, otherwise things just break, but this code gets carried over when you deploy.. and I don't see it working if you comment out SigningCertificate. So I'm thinking it creates redundancy of putting/copying SSL certificate in two places (one handled by IIS, and the second copy handled by the application).

Can't IdentityServer simply just use the assigned certificate configured in IIS and be done with everything? Or was this purely meant to be something that was supposed to be self sustained in OWIN running from a console?

**Comment by brockallen** [comment]
Sorry you're having problems, but I think you're making it more complicated than it needs to be. You need 2 different certs: one for SSL and one for signing. You should never use the same cert for both purposes. The SSL cert is just a normal SSL cert -- this is something you'll need to figure out how to get to work with IIS and your DNS system (and is really unrelated to IdSvr). The signing cert can be a self-signed cert and needs nothing else special -- just available to IdSvr. It's recommended that you store the signing cert in the server certificate store (for proper DACLing and access control)

**Comment by OutOfTouch** [comment]
I am where @cloudybrain is on this, as I am confused to when this is deployed to IIS in a production environment where shoud IdSvr be looking for it's cert to set SigningCertificate?

**Comment by brockallen** [comment]
There are 2 certs: One is for SSL and you configure that with the hosting layer (IIS/http.sys). The other is for signing tokens -- this is the `X509Certificate2` that you need to load in code in IdSvr.

**Comment by OutOfTouch** [comment]
I think I found the answer just load the cert from the cert store but make sure you grant the account that  AppPool is running under access to the cert in the cert store with the MMC snap-in and when granting access to the cert in the cert store make sure to allow the private key to be exported. I haven't tried this yet to verify though.

**Comment by OutOfTouch** [comment]
@brockallen  Sorry Brock I misread your first post, So the cert for signing tokens is always local? 
I guess my confusion is from the examples as the same cert was used for SSL and for signing.

**Comment by brockallen** [comment]
Well, I'm not sure what you mean by local -- you need the pfx with the private key for both certs. Which example uses the same cert for both SSL and signing?

**Comment by OutOfTouch** [comment]
The Web Host minimal example seems to use the same cert for both.

**Comment by brockallen** [comment]
That sample is using IIS express as the host and IIS express' SSL cert for running over HTTPS. So it's not using the same cert for signing and SSL.

**Comment by OutOfTouch** [comment]
Ok I understand, the signing cert is completely separate and can be in the bin folder or embedded.

What would SelfHost use for SSL cert then?

**Comment by brockallen** [comment]
Self host does the same as IIS -- they both really just use http.sys under the covers.

**Comment by cloudybrain** [comment]
@OutOfTouch you can create your own signingcertificate by using makecert.exe and pvk2pfx.exe, you can do so using visual studio command line tool.. it's a simple little thing you can tack onto your project.. it creates a .cer, .pfx, .pvk. You can read more about this around the internet. But to keep things simple.. .cer + .pvk + "password" = .pfx

I was personally confused since I figured it'd be useful for development, and when you go to production, you'd use a legit one.. but brock pointed out you can still use that for signing. I'm running into new issues that is kinda of related to this issue.. but not quite. Until I find the culprit or reason I'll come back to this. But I know it has to do with DNS and SSL.

**Comment by brockallen** [comment]
Oh also - I totally forgot about this blog post I did. HTH: http://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/

**Comment by OutOfTouch** [comment]
Thanks Brock and cloudybrain,  I have already done the self signed CA cert and ssl cert creation before this, I was just confusing the SSL cert with the SigningCertificate so I was actually using the ssl cert I created to sign tokens lol.

**Comment by OutOfTouch** [comment]
@brockallen Ok I been trying all day and no luck how do I take your command for creating the signing cert so that it creates the pfx files externally and doesn't throw them into the local store?

**Comment by cloudybrain** [comment]
@OutOfTouch this is what I used:

    makecert.exe -n "CN=IdentityCARoot" -r -pe -a sha512 -len 4096 -cy authority -sv IdentityCARoot.pvk IdentityCARoot.cer
 
    pvk2pfx.exe -pvk IdentityCARoot.pvk -spc IdentityCARoot.cer -pfx IdentityCARoot.pfx -po mypassword

just change IdentityCARoot to whatever name you want for your root certificate, and mypassword to whatever password you wanna name it

it will create the files automatically for you when you run them..

**Comment by OutOfTouch** [comment]
@cloudybrain The code you posted is basically what I used to create my CARoot cert but if you check out brocks link he has another command to create the token signature cert specifies no -cy certType and also specifies a begin and enddate of the cert and he specifies the subject's key type  param  -sky signature 

[code]
makecert.exe ^
-n "CN=%1" ^
-r ^
-pe ^
-a sha256 ^
-len 2048 ^ 
-cy authority ^
-b 08/06/2015 ^
-e 08/04/2020 ^
-sky signature ^
-eku 1.3.6.1.5.5.7.3.3 ^ 
-sv %1.pvk ^
%1.cer

pvk2pfx.exe ^
-pvk %1.pvk ^
-spc %1.cer ^
-pfx %1.pfx ^
-po TestTokenSig
[/code]

**Comment by cloudybrain** [comment]
That's what I used for my signing cert though.. the SSL cert I bought from a SSL cert provider.. and things are running on my end

**Comment by OutOfTouch** [comment]
I understand but technically there are 3 certs, 1 CARoot cert, 1 SSL cert signed by your CARootCert and the cert to sign tokens, I am using my ssl cert to sign tokens but from the disussion earlier the cert to sign tokens should be a separate cert, using the SSL cert to sign tokens it all works but I wanted to change it to be proper. I did not buy an SSL cert, using all self signed certs on intranet.

**Comment by cloudybrain** [comment]
I think that's reverse, the CARoot cert is the self signing certificate, IdentityServer uses this to sign the tokens. The other cert is used for the SSL channel for IIS. 

I don't know what this means: "1 SSL cert signed by your CARootCert" 
You don't use the CARoot cert to sign your SSL cert, they are completely separate.

**Comment by OutOfTouch** [comment]
http://www.jayway.com/2014/09/03/creating-self-signed-certificates-with-makecert-exe-for-development/#comment-328593

Read that, that is what I did, and I signed my ssl cert with my CARoot cert so it will be trusted.

**Comment by cloudybrain** [comment]
Again there is really two certificates being discussed here. The third that she mentions is a client certificate. You don't sign one cert with another cert.. you assign it to a trusted authority using MMC. In the example you provided CARoot.cer is the certificate to be used for signing tokens by identityserver, it's what you're referencing in the SigningCertificate attribute in your identityserver application. ServerSSL is what is being used to handle SSL on the server.

The final one is the ClientSSL, which is what your client applications use, that is beyond the scope. You are really concerned with CARoot.pfx and ServerSSL.pfx

**Comment by OutOfTouch** [comment]
I don't use any client certs since it is beyond the scope of this.

CaRoot is the issuer of the SSLCert which means the ssl cert is signed by the CARoot cert. In your case you bought an SSL cert that is Signed by an external CA.

If you look at brocks example of what he does to create a cert to sign tokens, it appears to me he is not using a CARoot cert to do that, since I don't see cert type as one of the params, I not sure wht the default value is for -cy if not provided, he also specifies the subject's key type param -sky as signature and specifies start and enddates for the cert.

**Comment by farshid3003** [comment]
I use following script to generate my certificate:

makecert -r -pe -n "CN=CAMyIds,OU=IT,O=MyCompany,L=Istanbul,C=Turkey" -a sha512 -len 4096 -cy authority  -sv myids.pvk myids.cer
pvk2pfx.exe -pvk myids.pvk -spc myids.cer -pfx myids.pfx -po myPassword

it works on local but not on the server (IIS) when I deploy it.

Error:

The system cannot find the file specified.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Security.Cryptography.CryptographicException: The system cannot find the file specified.


Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[CryptographicException: The system cannot find the file specified.
]
   System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) +41
   System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx) +0
   System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags) +230
   System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password) +137
   Morhipo.Services.IdentityServer.Config.Certificate.Get() in C:\Projects\Morhipo.Services\src\Services\Morhipo.Services.IdentityServer\Config\Certificate.cs:13
   Morhipo.Services.IdentityServer.<>c.<Configuration>b__0_2(IAppBuilder coreApp) in C:\Projects\Morhipo.Services\src\Services\Morhipo.Services.IdentityServer\Startup.cs:111
   Owin.MapExtensions.Map(IAppBuilder app, PathString pathMatch, Action`1 configuration) +210
   Owin.MapExtensions.Map(IAppBuilder app, String pathMatch, Action`1 configuration) +131
   Morhipo.Services.IdentityServer.Startup.Configuration(IAppBuilder app) in C:\Projects\Morhipo.Services\src\Services\Morhipo.Services.IdentityServer\Startup.cs:125

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
   Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +93
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +209
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +843
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +51
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +101
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +137
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +172
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

**Comment by brockallen** [comment]
You need to debug Certificate.cs line 13 more.

**Comment by farshid3003** [comment]
It works in local and debug mode. When i use identityserver default certificate it works perfect but it does not work with mine

**Comment by farshid3003** [comment]
I got the problem:

The X509Certificate and X509Certificate2 class constructors which accept a PFX file name and a password require the caller's user account profile to be loaded.  However, ASP.NET and COM+ applications run in accounts which usually do not have the user profile loaded.

if I do these steps it works as well:

Go to IIS Manager
Go to the application pool instance
Click advanced settings
Under Process model, set Load User Profile to true

but I want to know how do you generate idsrv3test.pfx that works every where ? why mine does not work?

**Comment by brockallen** [comment]
This is what I do for self-signed certs: http://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/

**Comment by wlafrance** [comment]
Hmm, have they as of yet created a step by step guide on installing and setting up on IIS?

**Comment by brockallen** [comment]
Who is "they"? You should ask Microsoft, as that is their product.

**Comment by DoubleExposure** [comment]
Can anyone share their steps for setting up on IIS? I am running into similar problems. Thanks

**Comment by DoubleExposure** [comment]
For future reference, it turns out that the following will resolve the issue:
**Turns out there's a setting in the IIS Application Pool configuration (Application Pools > Advanced Settings) to load the user profile for the application pool identity user. When set to false, the key containers aren't accessible.**

**Comment by Vincent026** [comment]
Does anyone know if IdSvr3 will work on IIS 7.5/ Windows Server 2008 with self signed certificates? Brock writes https://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/  that SNI should be configured. SNI is not available in IIS 7.5 but perhaps it can me be ommitted resulting in some restrictions, for example that there can only be one website that uses https?.
