### ISSUE TITLE
Authentication session timeout message

### ISSUE THREAD

**Issue by ggravina** [IdentityServer/IdentityServer3#1685]
We've implemented a custom view service for login and would like to display a message to the user when they are redirected to the login due to authentication session timeout. Is there an event that's raised or another way to detect when the authentication session has timed out?

**Comment by brockallen** [comment]
"due to authentication session timeout" -- timeout where?

**Comment by ggravina** [comment]
At the Identity server. Using implicit flow.

**Comment by brockallen** [comment]
No we don't have anything like that because we don't know if they are not authenticated because they timed out, they closed the browser, or they asked to logout.

**Comment by ggravina** [comment]
Ok, np. Thanks for the quick reply!
