### ISSUE TITLE
Losing claims after ID Token exp timestamp

### ISSUE THREAD

**Issue by jstrawther** [IdentityServer/IdentityServer3#1687]
I'm having an issue where my claims are lost after 5 minutes, User.Identity.IsAuthenticated is false, and the User drops back to a WindowsPrincipal, rather than a ClaimsPrincipal.  This occurs at precisely the timestamp that is stored in the exp claim.  From what I've read, the exp claim is part of the ID Token, and shouldn't have any effect on expiration of the claims, but it seems I'm mistaken, somehow.  Do I need to do something in my client app to persist the claims?  Any clarification is greatly appreciated.

**Comment by brockallen** [comment]
In the client app are you setting `UseTokenLifetime=false` in the OIDC middleware?

**Comment by jstrawther** [comment]
I wasn't, but now I am, and that did the trick.  Thanks!
