### ISSUE TITLE
Long-Lived Access Tokens

### ISSUE THREAD

**Issue by DeveTho** [IdentityServer/IdentityServer3#1688]
Hello

Let me thank you guys first for your fantastic work. :D

Don't mind the title really: I didn't really know to formulate my issue well.
I don't know really if you can help me. I think it's more MVC and OpenID Connect in general related than IdentityServer specific.
Allow me to sketch the situation.

I use IdentityServer as an OIDC provider for authentication and authorization in multiple MVC client applications. I use the implicit flow for all of them. There are views that can be accessed anonymously, but I set a global (Resource)Authorize filter in all of them.
Now, with normal browsing, everything goes well. When the id_token expires and the user tries to access a page for which he needs to be authorized, he is redirected to the provider for the form post (if I'm not mistaken), the cookie gets set again and is redirected back to the view as a (still / again) authenticated user.
However, I also have a table that is automatically refreshed by JavaScript. The script gets the data from an action method for which the user needs to be authorized. When the id_token expires and the JavaScript tries to get data again, it gets a 302 with 'Location' set to the authorize endpoint. But since it's a script that made the call and not the browser, the redirect doesn't happen and the user stays unauthenticated and can't receive the data (until he refreshed the page manually).

Do you have any advice on how to proceed here?
Please note I'm trying to prevent a (script-based) page refresh. The page with the table and data should be able to stay for hours or even days on a screen without a page refresh.

I was personally thinking about changing the (Resource)AuthorizeAttribute so that it tries to authenticate the user in the OIDC provider (IdentityServer) without wanting to redirect, but I don't know if that's possible.
Other scenario I was thinking about is authenticating the user using JavaScript, but I don't know if it's possible to do that without a page refresh... Maybe with an iframe?

I'm just thinking out loud. I'm not a pro in this kind of stuff, but I like to learn.
If you have any more questions, please ask. And thank you very much for the help already!

**Comment by brockallen** [comment]
It's an ajax call?

**Comment by DeveTho** [comment]
It's indeed an ajax call. Just jQuery.post().

However, I think I've been able to solve the problem myself. I set `UseTokenLifeTime` to `false` and it works now.

Just to completely understand what's going on... Am I right when I say that when I hadn't set `UseTokenLifeTime` to `false`, the authentication cookie isn't usable anymore after the id_token has expired (default 300 seconds)? So you get a 401 (when accessing something marked with the (Resource)AuthorizeAttribute) and you are redirected to the authorize endpoint.

But when `UseTokenLifeTime` is `false`, the cookie is usable as long as the session lasts (user logs out or until the browser has been closed). But the id_token is expired. Is that a problem? Isn't it needed anymore then? I use for example the id_token for redirect after logout, but when I'm not mistaken it isn't a problem for that when it has already expired. And is it or isn't it a 'good practice' to set `UseTokenLifeTime` to `false`?

While writing I noticed my problem isn't completely solved. I need to use the access_token in the action method my JavaScript calls. Now that `UseTokenLifeTime` is set to `false`, I can still retrieve the access_token (from the ClaimsPrincipal), but after 5 - 6 minutes, I get 401 from the service that is called from the MVC client application with the access_token (so not in the JavaScript calls). To test, the expire date of the id_token is 30 seconds, that of the access_token 60 seconds. So I don't think it has something to do with that? *(To be honest, I expected the 401 more after 60 seconds then...)*

Thanks for the help again!

**Comment by DeveTho** [comment]
I'm wondering if I might need to change my flow to hybrid and use refresh tokens?
It's just that it doesn't make sense to me that I get the 401 after something between 5 and 6 minutes, and not after 1.

By the way, when some code might be useful...

The action method the script calls (user must be authorized) (simplified version) (`_identityClient` is an `HttpClient` with `BaseAddress` set):

```C#
[GetAccessToken]
public async Task<ActionResult> GetData(string accessToken)
{
    if (!string.IsNullOrWhiteSpace(accessToken))
        _identityClient.SetBearerToken(accessToken);

    HttpResponseMessage getDataResponse = await _identityClient.GetAsync("api/data");

    // Temporary
    getOfficeIdResponse.EnsureSuccessStatusCode();

    // Example
    string data = await getDataResponse.Content.ReadAsStringAsync();

    return Json(data);
}
```

The `GetAccessTokenAttribute`.

```C#
public class GetAccessTokenAttribute : ActionFilterAttribute
{
    public override void OnActionExecuting(ActionExecutingContext filterContext)
    {
        ClaimsPrincipal user = filterContext.HttpContext.User as ClaimsPrincipal;

        if (user == null)
            return;

        Claim accessToken = user.FindFirst("access_token");

        if (accessToken == null)
            return;

        filterContext.ActionParameters["accessToken"] = accessToken.Value;

        base.OnActionExecuting(filterContext);
    }
}
```

I don't really know how to use the refresh tokens. Am I right that I would need to change the `GetAccessTokenAttribute` to the following:

```C#
public class GetAccessTokenAttribute : ActionFilterAttribute
{
    public override void OnActionExecuting(ActionExecutingContext filterContext)
    {
        ClaimsPrincipal user = filterContext.HttpContext.User as ClaimsPrincipal;

        if (user == null)
            return;

        Claim refreshToken = 
            user.FindFirst("refresh_token");

        if (refreshToken == null)
            return;

        OAuth2Client oAuth2Client = new OAuth2Client(
            new Uri(Constants.TokenEndpoint), "clientid", "clientsecret");

        TokenResponse refreshTokenResponse =
            oAuth2Client.RequestRefreshTokenAsync(refreshToken.Value).Result;

        if (refreshTokenResponse.IsError || refreshTokenResponse.IsHttpError)
            return;

        // I probably should update the "refresh_token" claim here with an eventual new value?

        filterContext.ActionParameters["accessToken"] = refreshTokenResponse.AccessToken;

        base.OnActionExecuting(filterContext);
    }
}
```

**Comment by brockallen** [comment]
id token lifetime needs to just be long enough to convey to the client app the user's identity so it can issue its own cookie. access token lifetime has its own expiration (configurable on the client in idsvr) and that's what should be used to access APIs.

**Comment by brockallen** [comment]
refresh tokens are not really designed to allow for sliding access tokens like we can do sliding cookies.

**Comment by DeveTho** [comment]
> refresh tokens are not really designed to allow for sliding access tokens like we can do sliding cookies to keep a user logged in as they're active.

Could you tell me what refresh tokens are there for then? Because I thought it's there to 'refresh' the access token to persist the client's access to the API(s)?

How would be the best way to implement the following scenario then?
A client has a dashboard page that should be visible for hours or even days without requiring the user to do something (e.g. refreshing the page). However, the client should be able to repeatedly access an API with an access token granted by the OIDC provider (IdentityServer) during that time period.

Third and last question (for now :P ): why can I use the access token for the amount of seconds specified in `AccessTokenLifetime` + 5 minutes?

**Comment by brockallen** [comment]
They're designed for "offline" access to a resource on behalf of the user. It's sort of like a sliding access token, but it's not the original intent/design of them. It also adds a lot of complexity to your client app. IdSvr has a feature that allows the benefits of the refresh token without the pain, which is a long lived reference access token.

As for the 5m difference, it's a grace period to account for clock skews.

**Comment by DeveTho** [comment]
Thank you for the tips. :)

Are you telling me to set the `AccessTokenType` in the client configuration to `AccessTokenType.Reference` and that it then would be safe to set a high `AccessTokenLifetime` (maybe even several days)?

Although, I'm not quite sure what the difference is between the two types. I noticed that when changing the type to reference, the access token is way shorter (of course, it's a reference), but maybe my question should be more like: where does it reference to?

Obviously, also a reference access token isn't usable anymore after it has expired (and, I noticed, with that type without the 5 min grace period). But then it also isn't possible anymore to access the APIs on behalf of the user. So when the access token has expired, does that mean the user has to log out (or end the session) and log back in again?

**Comment by brockallen** [comment]
This is all part of the design process. You need to think about the use case scenarios and incorporate all the different options in IdSvr into your solution. 

Reference tokens are maintained in IdSvr's database. When validating the token at the API, the API must check with IdSvr to know if the token is valid. This is performed by the IdSvr access token middleware. 

What makes reference tokens different than JWTs is that reference tokens are revocable. That's also a feature of a refresh token.

**Comment by DeveTho** [comment]
And this revocability makes it 'safer' to prolong the lifetime to e.g. a week or even longer? I mean, there is probably a reason why by default, it's 'just' one hour.

Another minor question I had when looking at the reference tokens.
I'm using your EntityFramework implementation to store the IdentityServer configuration in a database. After your answer, I noticed the actual access tokens are stored in the 'Tokens' table. I also noticed the reference token the client actually gets is an hexadecimal string representing 16 bytes. However, I couldn't match this string with the 'Key' column, or any other column, in the table. Is the string of the reference token encrypted before being stored in the database? I couldn't find it in the source code...

**Comment by brockallen** [comment]
It's revocable for the scenarios where the user loses their mobile phone with the app that has the token or the user simply says "i don't trust the app anymore".

As for the EF question, since the access token is access we hash it in the DB in thew case where the DB is compromised.

**Comment by DeveTho** [comment]
I'm sorry, but I still have the question if it's a good practice to prolong the lifetime of a reference token. It's just that I'm very new to the identity management world and I can't always estimate very well what might be good things to do. However, I know it's dependent on the required use cases.

In the OIDC specs, the following is stated:
> Access Tokens might not be revocable by the Authorization Server. Access Token lifetimes SHOULD therefore be kept to single use or very short lifetimes.

Could you maybe give your opinion on if that can be negated for the reference tokens IdentityServer uses and that you can even use a lifetime of several days or more?

Oh, and something I just came up with. I didn't look for it yet (but I will test it for sure), but maybe you have a quick answer. Can you access an API with a (reference) access token granted to a user after that user has already logged out?

**Comment by brockallen** [comment]
Right -- that's why our bearer token middleware checks back w/ IdSvr and see if the token has been revoked and if the user has been disabled (IsActive in the user service). So a short lifetime is one way, and checking back w/ the token service to validate the reference token is another.

**Comment by DeveTho** [comment]
Thank you for all the help, Brock.

Maybe you can help me with one more thing.
For which scenarios should it be possible to revoke the access token? I'm thinking of, like you said, when the user loses his phone or in case he doesn't trust it anymore, there should be an option where he can revoke access (delete the tokens) with.
I think it must also be possible for an admin to revoke all access for a user, like that is possible in your EF CLI.
I was however also thinking about the scenarios where a user logs out or gets locked out. Because in these scenarios, the access token is still valid and thus usable. Should it be revoked then, or rather not? And when yes, what could be a good way to implement it?

**Comment by brockallen** [comment]
The permissions page is what allows the end user to do that. We don't have an admin type page, but you can build that yourself.

**Comment by DeveTho** [comment]
Thank you! :D
