### ISSUE TITLE
Authentication Failure logs as an error - Part 2

### ISSUE THREAD

**Issue by JPBridges** [IdentityServer/IdentityServer3#1690]
I know this was discussed in some detail issue #1122 but I'm still a little bit confused about what the outcome was.  I 'think' that it was decided that authentication failures aren't errors and probably should be logged as warnings but _should_ have a failure event raised - as somebody has failed to log in.
This makes sense to me as we absolutely expect people to make the occasional typo and logging errors seems excessive.

TokenRequestValidator is still logging out errors on authentication failures so is any further action pending on this - or is the answer simply to ignore those particular types of errors?

**Comment by brockallen** [comment]
I don't recall where we left it -- would have to check in the code.

**Comment by JPBridges** [comment]
Hi Brock

So TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync does:

            if (authnResult == null || authnResult.IsError || authnResult.IsPartialSignIn)
            {
                // ..
                LogError("User authentication failed: " + error);
                await RaiseFailedResourceOwnerAuthenticationEventAsync(userName, signInMessage, error);

We've got no issue with the flow but I suppose our view of errors within our logs are that something bad has happened at a system level that we should be worried about.

Maybe a LogAuthenticationFailuresAsErrors option in AuthenticationOptions?  We don't mind sending a pull request.

**Comment by brockallen** [comment]
Here it is: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/IEventServiceExtensions.cs#L176

and I read that as logging failure (not error).

**Comment by JPBridges** [comment]
Agreed... the event is fine but that method is ultimately called by... 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/TokenRequestValidator.cs#L423

Which logs out the authentication failure as an error directly before raising the failed event.

**Comment by brockallen** [comment]
The log is different than the events. Logging is designed for developer time information. Events are meant for production time information.

**Comment by JPBridges** [comment]
Okay I think that was a misconception on our part.  We're passing in a log provider to IdentityServer and watching that in production.  If the log was never meant for that purpose then that's what's causing my confusion - and freaking out our support team.

I still think the authentication failure log message is too severe but I'm happy to live with it once we get it out of our production logs.

Thanks for your help.
