### ISSUE TITLE
Can IdSrv3 handle JSON requests?

### ISSUE THREAD

**Issue by m3kan1cal** [IdentityServer/IdentityServer3#1691]
Hi guys,

I've been reviewing this solution for my team for a few days and love it so far. I'm trying to send JSON in my requests to IdSRv3 endpoints and am getting 415 Unsupported Media Type responses. Are JSON requests supported and I'm just missing how to configure support for it?

Cheers

**Comment by brockallen** [comment]
Not really -- most of the request types must me form-urlencoded since that's what the spec mandates.

**Comment by m3kan1cal** [comment]
Great, thanks for the quick response.
