### ISSUE TITLE
MVC4 + Silverlight using hybrid flow, 302 redirect problem

### ISSUE THREAD

**Issue by hanswolff** [IdentityServer/IdentityServer3#1692]
We use a Silverlight client to access an MVC4 controller that authorizes against IdentityServer3 using cookies. For the authorization of the silverlight calls we pass the ".AspNet.Cookies" cookie to each request. All Thinktecture expiration timeouts are configured to 20 minutes. In Silverlight we consume JSON results of these requests.

Our problem is that from time to time (after some expiration timeout) we receive 302 redirects instead of our expected JSON result in Silverlight. Because Silverlight has no full browser implementation we cannot cope with these 302 redirects like a full browser.

My questions:

- How can we prevent these 302 redirects without increasing the expiration timeout? (it is required that the session expires when the user is inactive)
- Can I use any of the tokens from our cookie to manually prolong the session in our controllers?

**Comment by brockallen** [comment]
Basically your design of using MVC controllers with cookies is not really the right approach in the first place. That design assumes the browser is making the request and thus a 302 will work when re-authentication is required. A proper API design would be to use API controllers for programmatic requests that return 401 when authorization is required. Then the client app can do what's needed to re-authenticate on the 401. Also, you'd use a proper access token for the APIs and not a cookie. This is what the OIDC and OAuth2 protocols (and thus IdentityServer) are about.

If you can't re-architect any of your code the way I am suggesting, then you can look for the X-Requested-With HTTP header to know if the request is a Ajax request (hopefully your sliverlight code is sending that) and prevent the 302.
