### ISSUE TITLE
Change logging timezone

### ISSUE THREAD

**Issue by brewhutch** [IdentityServer/IdentityServer3#1694]
Hi,
I'm using ``` LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());``` and this prodcues the GMT time in trace.log like this
```
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 8/7/2015 2:16:04 PM +00:00 -- Creating access token
```
Is there a way to set the timezone to EST?

Thanks

**Comment by brockallen** [comment]
This seems to be hard coded in LibLog.

**Comment by brewhutch** [comment]
Found it. 
Thank you Brock!

**Comment by brockallen** [comment]
Does LibLog have a config option to change it?

**Comment by brewhutch** [comment]
Hi Brock,
I found it under
```
IdentityServer3/source/Core/Logging/DiagnosticsTraceLogProvider.cs > Log()
```
In that method, I will have to change 
from
```
var message = string.Format("{0}: {1} -- {2}", _name, DateTimeOffsetHelper.UtcNow, messageFunc());
```
to
```
var message = string.Format("{0}: {1} -- {2}", _name, DateTimeOffsetHelper.Now, messageFunc());
```

Am I doing the right thing?

**Comment by brockallen** [comment]
Well, you can't do that if you're using IdSvr via NuGet, right?

**Comment by brewhutch** [comment]
Yes you're right.If I download the source and re-compile, is it possible? (I've not tried it yet)
Btw, where can I find LibLog if I dont want to re-compile?

**Comment by brockallen** [comment]
we compile it into our source. 

just so you're aware -- the logging is meant more for dev-time logging. if you want production info then look at the eventing system

**Comment by brewhutch** [comment]
Sounds good.
