### ISSUE TITLE
[Question] Custom Login Screen - Integrated Windows Auth with fall back. 

### ISSUE THREAD

**Issue by tombatron** [IdentityServer/IdentityServer3#1696]
I want to create a custom login screen that will attempt to authenticate a user via integrated Windows Authentication (using SPNEGO or whatever) and if that attempt fails, fall back to a forms based approach. 

The process would ideally work like this...

#### User Logged in as Valid AD User
1. User attempts to access application and is redirected to **IdentityServer**.
2. Custom logic attempts to validate user using AD credentials and succeeds. 
3. User is authenticated and redirected...

#### User Not Logged in as Valid AD User
1. User attempts to access application and is redirected to **IdentityServer**.
2. Custom logic attempts to validate user using AD credentials and fails. 
3. User is presented with a form to enter username and password.
4. User is authenticated and redirected...

I was hoping to create a custom `IUserService` implementation to achieve this, but from reading the documentation it's not obvious how this would be done. 

Am I going to have to create a custom identity provider to achieve this?

Any guidance would be greatly appreciated.

**Comment by brockallen** [comment]
That's a very hard thing to implement without some additional hint from the user or user-agent. Have you ever done this before in a stand alone ASP.NET app?

**Comment by tombatron** [comment]
I have not done this in a stand-alone ASP.NET app. 

Conceptually, something like the [OWIN-MixedAuth](https://github.com/MohammadYounes/OWIN-MixedAuth) middleware implementation get's close to what I'm trying to achieve. Though, the more I think about it, the more it sounds like what I'm trying to achieve isn't feasible in a secure fashion.

**Comment by brockallen** [comment]
We have a separate repo that helps with the integrated windows authentication -- it's here: https://github.com/IdentityServer/WindowsAuthentication/. You configure that as en external provider in your main IdSvr. In short, it seems to work much like the OWIN-MixedAuth you reference.

You still have the initial problem of how do you know which one the user should use. If they tell you, then it's easy. But doing it automatically is hard.

**Comment by tombatron** [comment]
Fair enough. Thank you for your time!
