### ISSUE TITLE
ClientCredentials and ResourceOwner with login dialog

### ISSUE THREAD

**Issue by Pondidum** [IdentityServer/IdentityServer3#1699]
We are writing a public webapi, which will be consumed by a 3rd party website.
The Api has two parts to it, one which requires client authentication (say listings of things), and one which requires user authentication (account etc).
I have been able to achieve this by using `ClientCredentials` for the listings part, and `ResourceOwner` flow for the account side (as separate `Client` objects on the api).

However, I don't want to expose usernames and passwords to the 3rd party website, but have no idea how to go about triggering the identityserver login pages from the client etc.

Also, the 3rd party is writing the site in Drupal, and I am not sure how/if that impacts how I trigger and respond to user logins.

Thanks

**Comment by loctanvo** [comment]
Your setup sounds like a quite common setup of IdentityServer use case. As you describe, it involves three parts, `IdServer`, your `WebApi` and a `Relying Party/Client`.

The standard flow would be:

1. The user accesses the `Client` and click some "Login" button
2. The `Client` redirects the user to the `IdServer`
3. The user logs in successfully at `IdServer`
4. `IdServer` redirects the user back to the `Client` with an access token
5. The `Client` uses the access token to access your `WebApi`

This way, the `Client` never sees the user credentials. It sounds like you're unsure about how to achieve the second step. It's actually just about redirecting the user to a standardized `authorize` endpoint with correctly specified parameters. Look through some of the [documentation to get started](https://identityserver.github.io/Documentation/docs/).

Regarding Drupal specifically, maybe this may be useful: https://www.drupal.org/project/openid_connect

**Comment by Pondidum** [comment]
I have been going round in circles for days (it feels like) in the documentation, but apparently your re-phrasing and set of steps was what I needed - I now have it working.

Thanks very much for the quick response.
