### ISSUE TITLE
How to request token with Client Credentials Flow in body on post?

### ISSUE THREAD

**Issue by OutOfTouch** [IdentityServer/IdentityServer3#1701]
I am trying to figure out how to request an auth token with client credentials flow using Fiddler to submit the post. I keep getting 400 error invalid header value or error invalid_client.

Here is what I am trying:

Post : https://localhost:44336/connect/token
Headers: 
User-Agent: Fiddler
Content-Type: application/x-www-form-urlencoded
Body: grant_type=client_credentials&client_id=test&client_secret=test&scope=TestAPI
Content-Length: 0
Host: localhost:44336

**Comment by brockallen** [comment]
Enable logging in IdSvr and see what it says.

**Comment by OutOfTouch** [comment]
How do I do that?

**Comment by brockallen** [comment]
You check the docs :)

**Comment by OutOfTouch** [comment]
I did on logging, but the examples are more like snippets, would be great
if there was a complete logging example.

**Comment by OutOfTouch** [comment]
Can you even tell me if what I am posing is in the correct form?

**Comment by OutOfTouch** [comment]
alright I will use the diagnostics snippet.

**Comment by OutOfTouch** [comment]
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.TokenErrorResult]: 8/10/2015 2:58:28 PM +00:00 -- Returning error: invalid_client

**Comment by OutOfTouch** [comment]
What is the default log provider used by IdSvr? How do I specify one of the logging options, like WebApiDiagnosticsIsVerbose?

**Comment by brockallen** [comment]
What version are you using?

1.x worked this way: https://identityserver.github.io/Documentation/docs/configuration/logging.html

2.0 works this way: https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

**Comment by OutOfTouch** [comment]
Nvm, I guess there is not default it what ever we want of the supported ones. I am still trying to figure out how to set the WebApiDiagnosticsIsVerbose option. I am using version IdSvrV3 so no clue which one of your docs is correct, I read the 1.0 ones since they are default on the site.

I posted the log line above, pretty much what I said already that it is invalid_client which is why I am asking the question becaue the client name is correct, what I need to know is if my format in the body of the post is correct or not.

**Comment by OutOfTouch** [comment]
Thanks for links and the help, back to my original question, I read this https://identityserver.github.io/Documentation/docsv2/endpoints/token.html
and this http://openid.net/specs/openid-connect-core-1_0.html#TokenRequest, I posted what the log said earlier but here it is again : iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.TokenErrorResult]: 8/10/2015 2:58:28 PM +00:00 -- Returning error: invalid_client

I am still not sure what I am doing wrong in the formatting of my body in the post if anything.

**Comment by brockallen** [comment]
And there's no other contextual error info in the log (such as "Start client validation" or "No client with that id found. aborting")?

**Comment by OutOfTouch** [comment]
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.WelcomeController]: 8/10/2015 2:55:26 PM +00:00 -- Welcome page requested
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.WelcomeController]: 8/10/2015 2:55:26 PM +00:00 -- Rendering welcome page
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController]: 8/10/2015 2:58:28 PM +00:00 -- Start token request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 8/10/2015 2:58:28 PM +00:00 -- Start client validation
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 8/10/2015 2:58:28 PM +00:00 -- No or malformed client credential found.
 {}
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController]: 8/10/2015 2:58:28 PM +00:00 -- End token request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.TokenErrorResult]: 8/10/2015 2:58:28 PM +00:00 -- Returning error: invalid_client

**Comment by OutOfTouch** [comment]
That is the full log.

**Comment by brockallen** [comment]
Ah yes, ok -- so it seems that the client credentials are not being passed as Basic authentication via the Authorization header. I should have caught that in your original question. Sorry.

So in the latest on 2.0.0 on dev we do have a secret parser that knows how to read from the body, but your error logs looks slightly different than the latest version. Which version of 2.0.0 are you on?

**Comment by OutOfTouch** [comment]
When you say 2.0 it confuses me I am not sure what you are referring to as 2.0 , I am using IdSvr v3

**Comment by brockallen** [comment]
IdSvr3 version 2.0.0

**Comment by OutOfTouch** [comment]
How do I tell what version IdSvrV3 is?  I see file version as 1.6.2.0 and product version as 1.6.2.0 of the dll.

**Comment by brockallen** [comment]
Ah ok -- so you're using version (or build, or release version) 1.6.2.

**Comment by OutOfTouch** [comment]
It is what I got from Nuget, think I didn't have pre-release selected I could update to version 2.0.0

**Comment by OutOfTouch** [comment]
Are you saying that IdSvr requires client credentials to be passed by Authorization Header the documentation says it can be passed in the body or the Authorization in the header.

https://identityserver.github.io/Documentation/docsv2/endpoints/token.html
Authentication

All requests to the token endpoint must be authenticated - either pass client id and secret via Basic Authentication or add client_id and client_secret fields to the POST body.

**Comment by OutOfTouch** [comment]
idk- I am more confused then when I asked the question, I just want to know how to get a token with client credentials (No Users) by posting the clientId and clientSecret in the body.

**Comment by OutOfTouch** [comment]
I am not using Postman I am using Fiddler.

**Comment by OutOfTouch** [comment]
I don't think using version 2.0 is going to work for me since I don't see 2.0 rc3 version of EF or Core.
Versions are very confusing right now as well it is hard to tell what works with what versions if you look at all the pieces.

**Comment by OutOfTouch** [comment]
I don't know what to do need to get this to work in order for a 3rd party app to be able to get a token by posting thier client ID and client secret in the body.

**Comment by brockallen** [comment]
This sample does client credentials flow: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/ConsoleClientCredentialsClient

**Comment by OutOfTouch** [comment]
I know I already ran that sample for my own testing, does me no good though if I have an app that is out of my control that needs to request a token for this flow using the Post body. I thought 1.6.2.0 was a stable version?

**Comment by brockallen** [comment]
The OAuth2 client has an extra param to pass the client creds in the body.

**Comment by brockallen** [comment]
I can double check later that it's working properly.

**Comment by OutOfTouch** [comment]
What is that extra param called all I see in 1.6.2.0 is clientAuthenticationStyle as the last param.

**Comment by OutOfTouch** [comment]
OAuth2Client.ClientAuthenticationStyle.PostValues  I think

**Comment by brockallen** [comment]
Yes

**Comment by OutOfTouch** [comment]
Can you look at my body in my first post and tell me if you see something I might be missing. Do I need to include a Header that I am not including now?

**Comment by brockallen** [comment]
It looks correct so I must be missing something. Here's the code that does the check for client credentials: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/ClientValidator.cs#L79

**Comment by OutOfTouch** [comment]
Ok the ParsePostBody method looks good to me and my property names in the body match those.
Do you know where the invalid_client message is set in this chain?

**Comment by OutOfTouch** [comment]
Wait is the code only validating client with Authorization?

// validate client credentials and client
            var client = await _clientValidator.ValidateClientAsync(parameters, Request.Headers.Authorization);
            if (client == null)
            {
                return this.TokenErrorResponse(Constants.TokenErrors.InvalidClient);
            }

**Comment by OutOfTouch** [comment]
OK I have a better question what is called after ValidateHttpRequest?

**Comment by OutOfTouch** [comment]
Yeah from what I see the ValidateHttpRequest header will call into ParseBasicAuthenticationScheme see that the header is null and there is no Basic in the header, and return false for both IsPresent and IsMalformed and then ValidateHttpRequest will fall thru to ParsePostBody

**Comment by OutOfTouch** [comment]
Can you test this scenario on your end with cliend_id and client_secret in the body? Only thing I see is the client has to be null somewhere to get that error.

**Comment by OutOfTouch** [comment]
I have looked over the repo code a few times and I can't see where it would be null since everything I am passing in looks valid and the parsing code and logic flow looks correct to me. This is a bummer since this is show a stopper for me.

**Comment by brockallen** [comment]
I just tested the 1.6.2 server w/ the client credentials samples where the credentials are sent in the POST body and it works. I'd suggest you download the code and do the same, but use your fiddler client. That way you can debug thru the server code and find out why it's failing.

**Comment by OutOfTouch** [comment]
I also can't get the 2.0 source to run correctly for me locally, I keep getting secure connection failed.

**Comment by brockallen** [comment]
Secure connection filed sounds like an SSL error.

**Comment by OutOfTouch** [comment]
Can you post the format of what you sent in your test please.

**Comment by brockallen** [comment]
I have 2 VS projects open -- one is IdSvr and the other is the Clients solution (from the sample repo). I run the "Console Client Credentials Flow" project and change the ctor param for the OAuthClient to send the credentials in the POST body.

Here's the fiddler trace of the token request:
```
POST https://localhost:44333/core/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: localhost:44333
Content-Length: 84
Expect: 100-continue
Connection: Keep-Alive

grant_type=client_credentials&scope=read+write&client_id=client&client_secret=secret
```

**Comment by OutOfTouch** [comment]
Well I found the problem it was all in how I was sending the post thru Fiddler, sigh, at least I learned some more about the IdSvr code. Dumb question but can I safely upgrade to 2.0, will other pieces like IdSvr EF and IdMgr break with 2.0, what I mean is will those be upgrade later on or I they being kept compatible with 2.0 as 2.0 is developed.

**Comment by OutOfTouch** [comment]
Thanks Brock!

**Comment by brockallen** [comment]
I'm in the process of updating all the samples and all the other projects to 2.0 today. 2.0 will be released very soon. We follow semver, so 2.0 technically has breaking changes... you may or may not seem those, depending on which interfaces and APIs you've used/customized.

**Comment by OutOfTouch** [comment]
I am using the very basic client credentials flow right now no customizations and no extensions yet, but in the future I can see a need to do some customization or extensions so I would rather do it on the latest version.

**Comment by brockallen** [comment]
I plan to release 2.0.0 sometime this week.

**Comment by DoubleExposure** [comment]
OutofTouch, what is your solution? I am having the same problem with Fiddler. Please share the details. Thanks
