### ISSUE TITLE
Access Token Cache Location for Resource Owner Without OIDC

### ISSUE THREAD

**Issue by Suamere** [IdentityServer/IdentityServer3#1702]
I've had my Identity Server up and running for a couple of months now.  I am not using OIDC.  it is a very basic implementation and super simple.  Thank you for that.

I want to change from using server memory for caching bearer tokens over to using a custom redis server.  How can I do that without using OIDC?

            var factory = InMemoryFactory.Create();
            factory.UserService = new Registration<IUserService>(resolver => ninjas.GetService<IUserService>());
            factory.ClientStore = new Registration<IClientStore>(resolver => ninjas.GetService<IClientStore>());
            factory.ScopeStore = new Registration<IScopeStore>(resolver => ninjas.GetService<IScopeStore>());

            var options = new IdentityServerOptions
            {
                Factory = factory,
                RequireSsl = false,
            };

            app.UseIdentityServer(options);

**Comment by brockallen** [comment]
You'd need to configure the proper services. See the docs on the mandatory ones: https://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html

**Comment by Suamere** [comment]
Okay, I believe the answer lies in creating a custom ITokenHandleStore and adding:

    
            factory.TokenHandleStore = new Registration<ITokenHandleStore>(resolver => ninjas.GetService<ITokenHandleStore>());

I'm working down that path right now and so far it seems correct.  If I'm totally wrong or there are some gotcha's I should know about, please let me know.  Otherwise, that seems to be the answer.

The problem is that the verbiage says "ITokenHandleStore: Implements storage and retrieval of handles for reference tokens (interface)".  I never thought that I wanted to store handles for tokens.  What it really seems to be doing is caching the tokens themselves, which is what I want.  So assuming I'm right, this is perfect.

**Comment by brockallen** [comment]
If you're using reference tokens, then you need a proper DB for them. Reddis won't do, IMO, since it's a cache and not a proper DB (or am I wrong about reddis?).

**Comment by Suamere** [comment]
Redis is thought of as an in-memory KeyValuePair Database.  But even if it isn't technically true persistence, could you elaborate on why "you need a proper DB for [token storage]"?

**Comment by brockallen** [comment]
If your cache is lost for whatever reason, then all the reference tokens, authorization codes, and/or refresh tokens will be lost and the client apps using them will no longer be able to use the aforementioned tokens/codes.

**Comment by Suamere** [comment]
Okay, just making sure that was your reason.  Typically very prudent advice and good to be on any thread with the topic of changing persistence location of the access tokens.  Thank you for mentioning it.

**Comment by brockallen** [comment]
All set on this issue then?

**Comment by OutOfTouch** [comment]
http://redis.io/topics/persistence

**Comment by Suamere** [comment]
Yes Sir!  I believe the answer lies in creating a custom ITokenHandleStore implementation.  So far it seems to be working perfectly so far.  My main confusion was that a Token Handle Store, a Storage for Handles, or a Storage for Token Handling wasn't immediately obvious as Token Storage.  With that clarification I am all good.
