### ISSUE TITLE
Ignore Welcome page route when EnableWelcomePage = false

### ISSUE THREAD

**Issue by ayoung** [IdentityServer/IdentityServer3#1704]
I've read up on the previous issues that say that overriding the welcome.html page is disabled by design. Setting `EnableWelcomePage = false` disables the welcome page from rendering and returns 404 instead. Problem with this is that it actually allocates (eats up) a route in the routing handler so that any OWIN middleware registered after IdentityServer does not have a chance to pick up that request. This is especially problematic when you have IdentityServer setup at the root and not doing anything like `app.Map("/core", coreApp => { ... }`

What I would expect `EnableWelcomePage = false` to do is to ignore the route completely; don't return a 404; don't return anything.

Looking around in the source, I think there is opportunity to do this in `WebApiConfig` where you reflectively search for all the `IHttpControllers` in `HttpControllerTypeResolver`. Then remove `WelcomeController` from that list.

**Comment by brockallen** [comment]
Yep, this was fixed in the dev/2.0.0 branch.

**Comment by ayoung** [comment]
Is that out as a nuget prerelease package or would I have to build it from source?

**Comment by brockallen** [comment]
The nuget is here: https://www.nuget.org/packages/IdentityServer3

**Comment by ayoung** [comment]
Thanks. Is v2.0 slated for release soon?

We can close this now.

**Comment by brockallen** [comment]
Yes, this week I hope to release 2.0.0.

**Comment by ayoung** [comment]
We just upgraded to 2.0.0 and found that the welcome route is still returning a 404; its not passing through like we thought it would. Is this a bug?

**Comment by brockallen** [comment]
I'll reopen so I investigate when I get a chance -- I'm traveling this week, so if you happen to get to it sooner than me, I'd appreciate the help.

**Comment by ayoung** [comment]
Ok. Just kidding. Looks like its working as expected. The request gets passed through to the next middleware. Not sure why I was getting the 404 before.
