### ISSUE TITLE
Sign Out Auto Redirect and Sign Out Prompt

### ISSUE THREAD

**Issue by RemotecUK** [IdentityServer/IdentityServer3#1706]
I'm having an issue where by if I set the following options I get automatic redirection but not a prompt to sign the user out.

    EnablePostSignOutAutoRedirect = true,
    EnableSignOutPrompt = true, 

Are these two options mutually exclusive whereby if I set to auto. redirect I don't get a sign out prompt. Ideally I would like a signout prompt and then redirection back to the chosen uri. 

Please advise. Thanks.

**Comment by brockallen** [comment]
EnableSignOutPrompt is a global setting and setting it to false just means you don't want signout prompts globally.

If a client passes the post_logout_redirect_uri and a id_token_hint on signout then this causes IdSvr to always bypass the signout prompt. The EnablePostSignOutAutoRedirect then will automatically cause the page to return to the client post logout page.

**Comment by brockallen** [comment]
All set on this issue?

**Comment by RemotecUK** [comment]
Hi, what I was looking for was the ability to display the "Do you want to sign out?" prompt and if the user clicked "yes" then return to the redirect address.

From what you are saying this is not a currently supported use case. At the moment the user is logged out automatically and then has to click a link to return to the website in a logged out state which is fine for what I am doing.

Thanks.
