### ISSUE TITLE
Question: Token signature cert when deployed to IIS doesn't work

### ISSUE THREAD

**Issue by OutOfTouch** [IdentityServer/IdentityServer3#1707]
I don't understand what I am missing but when I run locally in IIS Express the token signature cert works fine as both an embedded resource or as a content file read from the \bin folder,  but when I deploy to IIS the code in my Cert.cs bombs out when reading the token signature cert. Am I missing something? Only thing I can think of is permissions to read the file? I am using SSL with IIS Express locally and SSL in IIS with another cert for SSL.

 My cert.cs code is:
```C#
public static class Certificate
    {
       
        public static X509Certificate2 Get()
        {
            // Use this code if you do not want to embed the pfx as a resource.
            return new X509Certificate2(
                string.Format(@"{0}\bin\IdSvr\TestTokenSig.pfx", AppDomain.CurrentDomain.BaseDirectory), "TestTokenSig");
            
            //var assembly = typeof(Certificate).Assembly;

            //using (var stream = assembly.GetManifestResourceStream("TestIdentityServer.IdSvr.TestTokenSig.pfx"))
            //{
            //    return new X509Certificate2(ReadStream(stream), "TestTokenSig");
            //}

        }
        
        private static byte[] ReadStream(Stream input)
        {
            var buffer = new byte[16 * 1024];
            
            using (var ms = new MemoryStream())
            {
                int read;
                
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }
                
                return ms.ToArray();
            
            }

        }

    }
```

**Comment by loctanvo** [comment]
Do you have any more info on the Exception you get?

**Comment by OutOfTouch** [comment]
I think I figured it out though, I set ApplicationPools LoadUserProfile to true and I gave the AppPoolIdentity rights to the folder where the file is and it seems to be past that error now, I will try with embedded and see that works with this as well.
