### ISSUE TITLE
Question - Return custom error instead generic invalid_grant

### ISSUE THREAD

**Issue by Davidsual** [IdentityServer/IdentityServer3#1708]
Hi
I am trying to authenticate a user with username / password and get an access token.
I am using IdentiyServer3 + Asp.Net Identity.

If in my custom IUserService in the method Task AuthenticateLocalAsync I raise an error like:
return new AuthenticateResult("User Locked out");

the next Layer in IDS [Core/Validation/TokenRequestValidator.cs] will always override my error message with:

var authnResult = await _users.AuthenticateLocalAsync(userName, password, signInMessage);
if (authnResult == null || authnResult.IsError || authnResult.IsPartialSignIn)
{
LogError("User authentication failed");
RaiseFailedResourceOwnerAuthenticationEvent(userName, signInMessage);
return Invalid(Constants.TokenErrors.InvalidGrant);
}

How can I override this behavior?

My OAuth2Client will always receive an error message InvalidGrant.

I would like to return, a custom json to my client with error User Locked out.

Currently I am always receive the message "invalid_grant"

Thank you and compliment for your work

**Comment by brockallen** [comment]
In 2.0.0 (I don't remember if we did this on 1.x) if you return an error message in the user service AuthenticateResult it will come back in the response from a resource owner token request. For example:
```
{
  "error": "invalid_grant",
  "error_description": "Use is locked out"
}
```

**Comment by Davidsual** [comment]
Thank you for your fast answer.

I am currently working on stable version 1.6.0.0.

I will wait the version 2.0 to be released as stable.

Thank you I appreciate the big effort that you guys are putting in this project.

Davide
