### ISSUE TITLE
internal interface ILog 

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1709]
IdentityServer3.Core.Logging.ILog is now (in vNext) internal making it difficult to have custom logger implementation. I'll assume this is intentional and there is a better way, please enlighten us.

**Comment by brockallen** [comment]
We don't have loggers anymore -- we're using LibLog to abstract the logging framework. So in short, you pick a logging framework and write to that. Internally we will use whatever your host has chose (again, via the magic of LibLog). Perhaps this helps some: https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

**Comment by snothub** [comment]
Great, got it. Thanks.
