### ISSUE TITLE
Store / Revoke JWT Token

### ISSUE THREAD

**Issue by Davidsual** [IdentityServer/IdentityServer3#1711]
Hi

I am using IdentityServer 1.6 + Asp.Net Identity 2.x
Using JWT tokens.

Scenario:
I want store in database (REDIS) every JWT token when it is generated / revoked.
I can store easy when is generated (override ITokenService) but I cannot revoke.
I can invoke REVOKE endpoint without problems... but the KEY that IdentityServer pass to the repository in order to GET and REMOVE the token I cannot recognize.
It is not the token or subject id

Implementation:
I override this method; ITokenService asking to store the token once created:
_tokenHandleStore.StoreAsync  DONE

Then I override ITokenHandleStore 

I try to call from my client the endpoint  xxx/revocation
when I receive the request in the ITokenHandleStore  for revoking the token the chain of calls are 
Task<Token> GetAsync(string key)
and if it succeed  Task RemoveAsync(string key)

Problem is:
When the revoke controller is trying to GET the token stored.. is calling Task<Token> GetAsync(string key) with a KEY that I cannot understand how is generated.
Therefore it will never find anything in my storage where all token are stored.

I cannot figure out from the code in GIT how this KEY passed  GetAsync(string key) is generated in theory...the key should be the token itself...

Thanks in advantage for your time.

Davide

**Comment by Davidsual** [comment]
Below some detail of the identity server 3 1.6 classes involved

By default the JWT token is not STORED
CLASS DefaultTokenService : ITokenService


 if (token.Type == Constants.TokenTypes.AccessToken)
{
if (token.Client.AccessTokenType == AccessTokenType.Jwt)
{
Logger.Debug("Creating JWT access token");
tokenResult = await _signingService.SignTokenAsync(token);
}
else
{
Logger.Debug("Creating reference access token");
var handle = CryptoRandom.CreateUniqueId();
await _tokenHandles.StoreAsync(handle, token);
tokenResult = handle;
}
}

When try to revoke the token

 private async Task<bool> RevokeAccessTokenAsync(string handle, Client client)
{
var token = await _tokenHandles.GetAsync(handle);
if (token != null)
{
if (token.ClientId == client.ClientId)
{
await _tokenHandles.RemoveAsync(handle);

**Comment by brockallen** [comment]
JWT access tokens can't be revoked. You want reference tokens.

**Comment by Davidsual** [comment]
Thank you Allen.

Davide
