### ISSUE TITLE
Token validation not working using ValidationEndpoint

### ISSUE THREAD

**Issue by ggravina** [IdentityServer/IdentityServer3#1712]
I have a Web Api configured to use identity server bearer token authentication. With ValidationMode set to Local, all is well. However, setting ValidationMode to ValidationEndpoint always returns 401. I want to use ValidationEndpoint as I plan to use reference tokens in the future.

Following is my middleware configuration -

![image](https://cloud.githubusercontent.com/assets/8375877/9232004/43303482-40f9-11e5-8fed-b870f540d882.png)

Seems, this used to work and at some point during an upgrade it may have stopped working.

Here a my package versions -

![image](https://cloud.githubusercontent.com/assets/8375877/9232133/e116071c-40f9-11e5-961d-8c51081ab3e6.png)

**Comment by brockallen** [comment]
Not sure -- you'd have to trace the request to the token validation endpoint. Are you sure there's not something configured in the host (like authorization?)? Also, check the IdSvr logs to see if it's even getting into IdSvr.

**Comment by ggravina** [comment]
Attached, please find a trace with ValidationMode set Local and
ValidationEndpoint.

I'm not sure what you mean by "something configured in the host (like
authorization)".

**Comment by leastprivilege** [comment]
any update?
