### ISSUE TITLE
IdentityServer 3.2 - No loggers in LogProviders namespace?

### ISSUE THREAD

**Issue by eric-swann-q2** [IdentityServer/IdentityServer3#1713]
Probably missing something here...but I'm trying to hook up Serilog with the just-dropped Identity Server 3.2.  Having some issues upgrading from 1.6.2 so I'm trying to get logging working on the Identity Server Host.  But there is nothing in the namespace IdentityServer3.Core.Logging.LogProviders.  The documentation states loggers (Serilog in my case) are supported OOTB.  SerilogLogProvider appears to not exist.  Am I missing a package?  I don't see any packages specific to loggers out there.  I am setting this up using an Asp.Net 5 host project.
Any ideas appreciated.

**Comment by brockallen** [comment]
Check the samples for what you do to configure Serilog. Internally we use LibLog and it detects that you've configured Serilog and uses it.

**Comment by eric-swann-q2** [comment]
Yeah, I figured out the issue.  Liblog is not being installed for some reason.  I may have to manually add it in.  Think it's related to it being a vNext project.  It's not adding/configuring the liblog file properly.

**Comment by eric-swann-q2** [comment]
So just to elaborate a little bit:  When the LibLog nuget package is installed it does some basic setup based on how you have your project configured and loggers detected etc...  But this doesn't appear to work for an ASP.Net 5 project due to changes in how nuget packages are installed.  So I had to manually add the LibLog SerilogProvider and LogProviderBase classes to my project.  I just dropped them into my project along with one missing extension method (GetMethodPortable).  
There may be a better way to accomplish this, but this worked for me in case anybody else is struggling with this on a vNext project.

**Comment by brockallen** [comment]
Perhaps @damianh can chime in...

**Comment by damianh** [comment]
https://github.com/damianh/LibLog/issues/35#issuecomment-98544745

I can't do namespace transforms for dnx projects. I haven't figured our yet how to proceed...

**Comment by eric-swann-q2** [comment]
Thanks for the feedback guys. My approach is definitely ugly but I needed to understand why my Identity Server wasn't working after the upgrade to 3.2.  This did get the logging working and I was able to resolve my issue so I'll leave it as is until there's a better solution.
