### ISSUE TITLE
Question: Tokens cached in memory by default?

### ISSUE THREAD

**Issue by OutOfTouch** [IdentityServer/IdentityServer3#1715]
I think I already know the answer to that question as yes, so for a production environment it would be best to implement a token cache store?
Dumb question here but when is TokenStore used vs AuthorizationCodeStore? 
When a token that has been issued it is cached , and then when an app wants to validate that token it is searched for in the cache?

**Comment by brockallen** [comment]
Depending on the flow, there is different state that IdSvr has to maintain (codes for code flow, refresh tokens for code flow w/ offline access, etc.), These stores represent the persistence of them. As the docs indicate, for production scenarios you will need to have an implementation: https://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html

**Comment by OutOfTouch** [comment]
I am currently just using Client Credentials Flow so I am assuming I just need to implement ITransientDataRepository for a TokenHandleStore? What is the lifetime of the token beyond the expiration, I ask because wouldn't I have to delete tokens from the token store when they expire? Maybe I should look at implementation of a TokenHandleStore to get a better idea.

**Comment by brockallen** [comment]
So yea, for just client credentials you most likely won't need those stores, unless you use reference tokens, but reference tokens don't make a lot of sense for client credentials flow.

**Comment by OutOfTouch** [comment]
Will I need the TokenHandleStore for Client Credentials Flow for a token to be validated?

**Comment by leastprivilege** [comment]
It depends on the token type - for JWTs no - for reference tokens yes.
