### ISSUE TITLE
Resource Owner flow doesn't work using REST Client like Postman

### ISSUE THREAD

**Issue by narciero** [IdentityServer/IdentityServer3#1716]
I have setup idSrv3 and have an auth code client working using the latest version of Postman, however whenever I try to use a ResourceOwner flow client and post a request to the connect/token endpoint i get the response
{
  "error": "invalid_grant"
}

Here is my client setup:
var resourceOwnerClient = new Client
            {
                Enabled = true,
                ClientName = "ios",
                ClientId = "ios",
                Flow = Flows.ResourceOwner,
                ClientSecrets = new[] { new ClientSecret("secret".Sha512()) }.ToList()
            };
            clients.Add(resourceOwnerClient);

My request body (x-www-form-urlencoded):

grant_type=password&scope=test&username=test%40test.com&password=Test123!

And the header includes basic auth with the client id and secret, I've also tried posting the client id and secret in the form body and I get the same result. I've also tried this in Fiddler with no luck, am I missing something obvious here? I have a standalone idsvr3 implementation using the standard settings, and I'm able to use other clients through Postman's oauth2 access token feature using authorization_code.

**Comment by brockallen** [comment]
Does the resource owner password flow client sample with with your idsvr setup?

**Comment by narciero** [comment]
found the problem, an exception was getting buried in my userstore implementation, dumb mistake. thanks, great product!

**Comment by rodmjay** [comment]
just curious as to why you would need a client secret with ResourceOwner flow?  Wouldn't  it just be the username/password that you would need to authenticate?

**Comment by nukec** [comment]
@rodmjay then anyone could just do requests from postman then.
