### ISSUE TITLE
Generate Signin / Register URIs

### ISSUE THREAD

**Issue by RemotecUK** [IdentityServer/IdentityServer3#1717]
Is it possible to directly generate URIs for Identity Server's signin and register pages?

At the moment I am triggering the login flow by redirecting my user to a protected resource when they click "Login". This causes the OWIN middleware to start the authentication process.

Ideally I would like to provide two hyperlinks on my website of "Signin" and "Register" that go directly to the appropriate pages in Identity Server.

Thanks.

**Comment by brockallen** [comment]
There is no registration page in IdSvr. 

The signin link you want to build should trigger your client app's OIDC code.

**Comment by jeremy001181** [comment]
I got exactly same requirement as RemotecUK described above, there is a problem (correct me if wrong) by using above approach is customer gets redirect back to the protected page after sign in instead of the page that they click on sign in link

**Comment by RemotecUK** [comment]
Yes, what I wanted to do was just to have a link that the user clicked on to sign in without hitting a protected resource. I had a look at the implicit Javascript client from the IDS3 samples and this may provide a way to do it by building up a URI with the client id (etc) in it. Not had chance to give this a try though yet.

**Comment by RemotecUK** [comment]
I've had a chance to give this a try.
Scenario: SPA with a link/button to signin. What I want to do is when the user clicks on this link, redirect them to the Identity Server, they login and are then redirected back to my application.
I am basing this on the "JavaScript Implicit Client - Simple" client example as provided.

My application generates a URI as follows...

`https://dev.example.com/IDServerTest02.Web/identity/connect/authorize?client_id=idservertest02.web&redirect_uri=https://dev.example.com/IDServerTest02.Web/&response_type=id_token&scope=openid&state=14405970133130.9024276566553384&nonce=14405970133130.16076779528271412&prompt=login`

This works great when I paste it into the browsers address bar, however the example uses `window.location` to set the current browsers address. This generates the following error in the log file...

2015-08-26 14:53:44.9302|ERROR|Thinktecture.IdentityServer.Core.Configuration.Hosting.ErrorPageFilterAttribute|Exception accessing: /IDServerTest02.Web/identity/connect/authorize
2015-08-26 14:53:44.9462|DEBUG|WebApi Diagnostics|[2015-08-26T13:53:44.9462514Z] Level=Error, Kind=End, Category='System.Web.Http.Filters', Id=e3bc59b8-dbf1-4133-b8cc-f830d8f0f248, Operation=ErrorPageFilterAttribute.OnExceptionAsync, Status=200 (OK), Exception=System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Web.Http.HostAuthenticationFilter.<AuthenticateAsync>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:line 0

I read some other issues around this and it seems to be that the browser is closing the connection too early or something?

In any case, it is possible to generate a sign in link rather than relying on a protected resource to redirect you.

Feedback welcome if I have got something wrong.

**Comment by brockallen** [comment]
Well, our JS samples show how to build a link to "login". One is bare bones, and the other uses the oidc-token-manager library.

**Comment by RemotecUK** [comment]
The example works fine if you use a button, I had used a hyperlink `<a>` tag.

So in answer to the question about creating a link to login as opposed to redirecting from a protected resource (think `[Authorize]` attribute) - this seems to be possible by following the Javascript Client example.

Thanks.

**Comment by jeremy001181** [comment]
Hi RemotecUK

you got redirect_uri=https://dev.example.com/IDServerTest02.Web, so it will redirect your back to IDServerTest02 page after sign in, but what if you have the sign in link on another page says IDServerTest01 , do you have to register 01 with identity server 3 as well?  what if the sign in link need to be on every page of the client?
