### ISSUE TITLE
[question] Response Type

### ISSUE THREAD

**Issue by ankur--bhatia** [IdentityServer/IdentityServer3#1718]
code+idtoken -- is not matching the responsetype. We RP is redirecting the customer to the authorize endpoint using the below request.
<pre>
https://*.*.com/connect/authorize?client_id=MyCLIENTID&redirect_uri=https%3a%2f%2f*.**.com&response_mode=form_post&response_type=code+id_token&scope=openid+offline_access+profile_read&state=OpenIdConnect.AuthenticationProperties%3****&post_logout_redirect_uri=http%3a%2f%2fwww.**.com
</pre>
But for some cases -- Identity Server fails to decode the response type correctly. And hence the validation fails. 
Following is the number of times that error is happening
![authorizerequestvalidatorexception](https://cloud.githubusercontent.com/assets/907087/9247733/8f80b014-41ad-11e5-8408-f06f159b1cff.JPG)
So it is not consistent -- as in there is a particular browser/user-agent or some scenario which causes this issue. 
Anyone has experienced this in the wild.

**Comment by JPBridges** [comment]
It seems that this has been caused by small number of mobile browsers that URL encode an already encoded URL resulting in corrupted query string values.

This can be closed it's not an issue with the identity server.

**Comment by brockallen** [comment]
That's unfortunate that they do this.

**Comment by ankur--bhatia** [comment]
Yup -- the culprit user-agents were: 
<pre>
Mozilla/5.0+(Linux;+U;+Android+4.1.2;+en-gb;+C1905+Build/15.1.C.2.8)+AppleWebKit/534.30+(KHTML,+like+Gecko)+Version/4.0+Mobile+Safari/534.30    24    36.923%    
Mozilla/5.0+(Linux;+U;+Android+4.1.2;+en-gb;+GT-I9100+Build/JZO54K)+AppleWebKit/534.30+(KHTML,+like+Gecko)+Version/4.0+Mobile+Safari/534.30    11    16.923%    
crawler4j+(http://code.google.com/p/crawler4j/)+X/34972276    9    13.846%    
Mozilla/5.0+(Linux;+U;+Android+4.2.2;+en-gb;+IdeaTab+S6000-F+Build/JDQ39)+AppleWebKit/534.30+(KHTML,+like+Gecko)+Version/4.0+Safari/534.30    8    12.308%    
Mozilla/5.0+(Linux;+Android+4.4.2;+GT-I9195+Build/KOT49H)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Version/4.0+Chrome/30.0.0.0+Mobile+Safari/537.36    7    10.769%    
Mozilla/5.0+(Linux;+Android+5.0;+SM-G900F+Build/LRX21T;+wv)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Version/4.0+Chrome/44.0.2403.90+Mobile+Safari/537.36    5    7.692%    
Mozilla/5.0+(Linux;+Android+4.4.4;+D2303+Build/18.3.1.C.1.17)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Version/4.0+Chrome/33.0.0.0+Mobile+Safari/537.36
</pre>
