### ISSUE TITLE
IdServer V3 token issuance for SPA app Redirect Issues

### ISSUE THREAD

**Issue by danutzplusplus** [IdentityServer/IdentityServer3#1719]
Hello,

This is a question with regards to the way a SPA javascript app could integrate with IdServer V3 for authentication, using implicit flow. Basically, we've managed to integrate, and authentication and token issuance works ok, except for some issues we're encountering, which make it difficult for the javascript to truly behave like a SPA.

The issue is with regards to the way we have to perform the token request from the SPA. We followed the javascript sample, but this performs the request by forming a full-page reload to the IdServer token issuance url, and the IdServer responds with a Redirect back to the redirecturl, with the token as a fragment parameter. And from what I can gather this is done because it is the only for the IdServer to avoid a cross site request forgery for the token. The IdServer needs to check the redirecturl, and only pass the token to that pre-registered url. Would this a fair understanding? Which tells me that part of the token request can't be changed for the security purpose just mentioned.

The issue with this full-page load for the token request and then the redirect back to the SPA is that it forces the SPA to loose its current context, meaning users will see this reload artifact anytime the token is requested, either initially or for new token requests upon expiration.

We attempted the token request with an ajax call, hoping we would get the redirect response, and could somehow suppress the redirect, and just extract the token off the url, but no such luck, since the browser redirects without giving you a chance to stop it.

Another issue with this redirecturl, besides the full-page reload, is that it makes it hard to maintain the spa url state from before the token request. If the spa does a token request which in /app/user/viewprofile, and you perform a token request with the root url, the redirect will be to that rooturl of the spa. And the alternative of performing the token request with every local path in the SPA is also unfeasible, since it would mean registering every path in the SPA in IdServer's ClientRedirectUris table. Or is this how it should be used?

Anyways, I guess my question is, how do people usually handle these issues? I've found this IdServer documentation url: https://github.com/IdentityServer/Documentation/issues/73
It mentions that for SPA, the implicit flow is the recommended one, and that all SPA providers have learned to accept these issues. But, for example, checking the last issue I raised, the maintaining of spa routes from before token requests, on Google's mail SPA, they don't seem to be keeping the path from before the login. Is there really no decent way of handling these issues?

Thanks, and I eagerly await someone's input on this. 
Have a good one.

**Comment by brockallen** [comment]
You can trigger a pop-up window to do the authentication.

**Comment by danutzplusplus** [comment]
Yeah, I also heard about that recommendation. But I'm not sure that's feasible with my requirements. I'll check.

Also, another small question. As I mentioned, because of the redirecturl, it makes it hard to return the user to the exact url where he left from after the token is issued. So I've thought about implementing another service that verifies the redirecturl, and change the default one with this one.

The current one takes the list of pre-configured urls from the db, and checks the one the client sends against each one (the check is done for the full url). The change I would be doing is, for certain pre-configured urls, I would not be checking the full requestUrl against those ones in the db, but only the beginning part of it.

So if I've got these in the db:
https://localhost:44311/

If the client sends in any of the following:
https://localhost:44311/zone1/zone3
https://localhost:44311/zone2/zone4

These ones would also pass the check. Meaning I would be checking something similar to:
foreach(var uri in uris) 
if(requestedUri.StartWith(uri)) return true;

Do you see any issue with this change? Am I breaking some security measure I'm not noticing? Basically I would be allowing for a range of Uris to be permitted without actually needing to insert them in the db. And that range must start with that particular uri. Thanks.

**Comment by brockallen** [comment]
If you need to return the URl to a specific URL, then store that as state in your client app, and on the callback page from IdSvr you load it and return the user there.
