### ISSUE TITLE
What's the difference between IdentityServer3 and the Thinktecture IdentityServer3?

### ISSUE THREAD

**Issue by gavinbarron** [IdentityServer/IdentityServer3#1720]
I'm a little confused between these two very similar project with similar functionality and people involved.

What are the differences?
Is there any reason why I should prefer one over the other?

**Comment by brockallen** [comment]
IdenittyServer3 is version 2.0.0 of Thinktecture.IdentityServer 1.x -- we renamed it dropping the "Thinktecture" moniker.

**Comment by gavinbarron** [comment]
So, with that in mind it looks like I should be preferring the IdentityServer3 packages over the Thinktecture.IdentityServer3 from nugget?

**Comment by brockallen** [comment]
Yes

**Comment by gavinbarron** [comment]
:+1:
