### ISSUE TITLE
Incompatibility with OpenID Connect implementation of Google OAuth Client Library

### ISSUE THREAD

**Issue by estiller** [IdentityServer/IdentityServer3#1721]
Hi,
IdentityServer3 serializes the AMR claim as a single value. For example, for "In Memory" users, a default value of "password" is given for the AMR claim.
However, according to the OpenID specification (http://openid.net/specs/openid-connect-core-1_0.html#IDToken) this value should actually be serialized as an array of strings:
*_amr_  OPTIONAL. Authentication Methods References. JSON _array of strings_ that are identifiers for authentication methods used in the authentication. For instance, values might indicate that both password and OTP authentication methods were used. The definition of particular values to be used in the amr Claim is beyond the scope of this specification. Parties using this claim will need to agree upon the meanings of the values used, which may be context-specific. The amr value is an array of case sensitive strings.*

I noticed this issue as I was trying to interop my Identity Server based component with an Android Application utilizing the Google OAuth client library (https://developers.google.com/api-client-library/java/google-oauth-java-client/). When this library receives an IdToken issued by the Identity Server, it throws an exception because it expects the AMR claim to be a list of strings as stated in the OpenID Connect specification, but it instead finds a single string. In the source code of its IdToken class (https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdToken.java) you can see that the *methodsReferences* field is expected to be a list.

I have two questions:
1. Who is "right"? Which implantation should be modified seeing that they cannot be used for OpenID Connect with each other as they are right now?
2. Is there a temporary workaround I can implement in my Identity Server based component to issue the AMR claim as a list of strings with one value in it?

Thanks!

**Comment by leastprivilege** [comment]
This looks like a bug on our side. We'll see how we can fix that. Thanks for reporting.

**Comment by leastprivilege** [comment]
I have a fix here - wanna see if that works for you?
https://github.com/IdentityServer/IdentityServer3/pull/1817

**Comment by estiller** [comment]
Thanks. No problem, I can check the fix but I will only be at that customer next week so I can check it only then. I'll update once I have the result.

**Comment by estiller** [comment]
Hi,
I just checked it and it seems to be working OK. Thanks!
