### ISSUE TITLE
ClientSecretValidator

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1722]
I'm getting "Client validation failed" because this class loops through an empty collection of validators and does nothing. Is there a default validator missing or am I supposed to implement client validation myself as of v.2?

**Comment by brockallen** [comment]
Can you elaborate some more?

**Comment by snothub** [comment]
My tests are failing but it turns out it is something with the OAuth2Client (Thinktecture.IdentityModel.Client.4.0.1) and anything that ends up in RequestAsync there goes through ClientSecretValidator and fails to validate as there are no validators in the collection there.

Make any sense?

**Comment by brockallen** [comment]
Are your tests loading the entire pipeline or just referencing the class directly?

**Comment by snothub** [comment]
Integration tests, entire pipeline.

**Comment by brockallen** [comment]
So I suspect it's something changed about what we register in DI that your tests aren't doing.

**Comment by snothub** [comment]
Might very well be, are there updated samples using OAuth2Client to look at?

**Comment by snothub** [comment]
I'm still blocked by not getting past client validation when using OAuth2Client. I don't see updated samples using OAuth2Client aginst IdSrv v2, so I'm hitting a wall here.

**Comment by snothub** [comment]
Resolved, caused due to breaking changes in client configuration, Secret was missing type property.
