### ISSUE TITLE
LibLog no longer public?

### ISSUE THREAD

**Issue by slafave** [IdentityServer/IdentityServer3#1723]
We have a breaking change from 1.x to 2.x, around logging.  We're utilizing the built-in LibLog in our custom services and extension code.  I noticed there is a compiler directive LIBLOG_PUBLIC that is by default setting LIBLOG to internal.  It would be helpful if the NuGet package was compiled to LIBLOG_PUBLIC.

Unless there is a new different way to leverage and extend the built-in LibLog facility?

**Comment by brockallen** [comment]
Include LibLog in your host. I think that's always been the style with LibLog.

**Comment by slafave** [comment]
https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

That documentation page shows how to instrument your own code, via the built-in LibLog ILog interface.  We are relying on that in our current code and that code is breaking now that the ILog interface is Internal.  We currently do not include LibLog in our host.

**Comment by brockallen** [comment]
@leastprivilege worked on that part so he'd be able to explain better, but if you look at all the 2.0 samples the approach is to include serilog (or whatever your preferred logging framework) and then use that directly. IdSvr (via LibLog) will detect the logging framework you're using and use it.

If you'd like a different approach, then we certainly can discuss on this thread. Unfortunately @leastprivilege is on holiday for a couple of weeks so we won't be able to further this until his return.

**Comment by slafave** [comment]
Ok, great I'll take a look at the 2.0 samples and plan to adjust our approach accordingly. Thx!

**Comment by brockallen** [comment]
Ok, we chatted about this and will be making ILog, et al. public again.

**Comment by slafave** [comment]
Great, thanks for the heads-up!  Appreciated.

**Comment by leastprivilege** [comment]
see https://github.com/IdentityServer/IdentityServer3/commit/3f040d5bfc1ac5124872ef860952b90faf6096ab

**Comment by slafave** [comment]
Thanks!

**Comment by damianh** [comment]
@brockallen @leastprivilege Tag me whenever a LibLog question pops up ;)

@slafave Can you expand on why you are depending on it? The purpose of LibLog is to discourage such coupling...

**Comment by slafave** [comment]
@damianh We did not make an actual decision to depend on it.  We just following the guidance at https://identityserver.github.io/Documentation/docs/configuration/logging.html in the section "Instrumenting your own code".  It made sense to push our logging into the common IdentityServer logging facility.  I was unaware of LibLog or how best to use it (sorry!) until this conversation.

**Comment by damianh** [comment]
No worries :)
