### ISSUE TITLE
OpenIdConnectNotification when user already have a cookie

### ISSUE THREAD

**Issue by rajarameshvarma** [IdentityServer/IdentityServer3#1724]
I am using Identity Server v3 with OWIN/Katana in ASP.Net MVC application. I need to log some information to the database when a user login to the application. I am doing this in SecurityTokenValidated of OpenIdConnectAuthenticationNotifications. But this event does not fire if the user already have the cookie. What is the best way to do this?

**Comment by brockallen** [comment]
Do you need to do the logging in IdSvr or in the app?

**Comment by rajarameshvarma** [comment]
I need do logging in the application.

**Comment by brockallen** [comment]
Well, that's the place to do it then. Not sure why the event is not firing.

**Comment by rajarameshvarma** [comment]
it fired when I login for the first time. After that if i come to the application before the token is expires (20 mins in my case) it wont hit that event again.

**Comment by brockallen** [comment]
I don't follow... at each app when the user first authenticates then the event will fire. once you have a cookie then there's not more authentication from the token service.

**Comment by rajarameshvarma** [comment]
My bad... was under the wrong impression that one of the events will fire to validate the token.

**Comment by rajarameshvarma** [comment]
On the other hand I am trying to add custom claims in Identity Server. Below is my code for user service.

    public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
        {
            AuthenticationClient client = new AuthenticationClient("Secure");
            AuthenticationResponse respose = client.Authenticate(username, password);            

            if (respose.Status == "Success")
            {
                List<Claim> claims = new List<Claim>();
                claims.Add(new Claim("Dimain", "test"));
                if (respose.Email != "")
                {
                    claims.Add(new Claim("Email", "email"));
                }

                return Task.FromResult<AuthenticateResult>(new AuthenticateResult(username, username, claims));
            }
           else
            {
                return Task.FromResult<AuthenticateResult>(null);
            }
        }

Authentication mechanism works fine but I am not getting these claims back in my Authentication.Identity.Claims

Please let me know if I need to create this as a seperate issue.

Thanks

**Comment by brockallen** [comment]
You need to read the docs on the user user service. The GetProfile is the place to do that.

**Comment by rajarameshvarma** [comment]
Yeah.. I saw that but I will be authentication against active directory... instead of making another call i will get these values while authenticating. I thought i can send it in AuthetnicationLocalAsync as it has overloaded method. What is this overload for?

**Comment by brockallen** [comment]
Again, please check the docs first.
