### ISSUE TITLE
Can I convert reference tokens to JWTs?

### ISSUE THREAD

**Issue by rbanks54** [IdentityServer/IdentityServer3#1725]
Consider a microservices architecture where I have an API Gateway (aka reverse proxy) sitting between clients and back end APIs.

Clients get reference tokens from IdSrv and pass them to the API Gateway where they are validated by making a call to IdSrv. All well and good.

I then want the API Gateway to make calls against the internal APIs using the JWT version of the token. Since it's internal at that point, I can validate JWTs locally and avoid extra validation calls against the IdSrv. Unfortunately I can't see any way to do that with IdSrv (unless I'm blind).

Is the ability to convert a reference token to a JWT something you're looking to enable in IdSrv, maybe as an optional return from a validation call, or should I just be building JWTs myself?

**Comment by brockallen** [comment]
This is like an "act-as" or "on-behalf-of" style token. There's a OAuth2 work in progress spec for this, but in the meantime you can use the reference token as a custom grant type against the token endpoint. You'd then build a custom token validator to allow the exchange of the reference token for a full JWT.

**Comment by rbanks54** [comment]
Thanks @brockallen. I didn't realise there was a draft spec for this approach.

Let me ask the obvious question: Any thoughts on implementing the draft spec and keeping IdSrv updated as it progresses? :-)

For reference I found an AAD sample for what I'm wanting to do at https://github.com/AzureADSamples/WebAPI-OnBehalfOf-DotNet. I might have a play with converting that to use IdSrv.

**Comment by brockallen** [comment]
We have an open issue and most of it already written (and a PR even I think), but it's slated for 2.1.

**Comment by rbanks54** [comment]
@brockallen Sweet! I'll keep an eye out for it.

I love what you, @leastprivilege and others are doing by the way. Keep up the fantastic work!

**Comment by philipbjorge** [comment]
@brockallen + @rbanks54  -- Any idea what's the state on this? Is there functionality built into IdentityServer to support this use-case?
Or do I need to go down the custom grant type route?

**Comment by leastprivilege** [comment]
custom grant validator - I think there is also a sample now in the samples repo.

**Comment by philipbjorge** [comment]
Thanks @leastprivilege !

**Comment by philipbjorge** [comment]
@leastprivilege @brockallen -- I've taken a stab at a custom grant for exchanging reference tokens for JWTs. It seems to be working.
Anything stupid I might be doing?

```cs
public class ExchangeReferenceTokenGrantValidator : ICustomGrantValidator
{
    private readonly ITokenHandleStore tokens;

    public ExchangeReferenceTokenGrantValidator(ITokenHandleStore tokenStore)
    {
        tokens = tokenStore;
    }

    public async Task<CustomGrantValidationResult> ValidateAsync(ValidatedTokenRequest request)
    {
        var referenceToken = request.Raw.Get("reference_token");
        if (referenceToken == null)
        {
            return new CustomGrantValidationResult("Missing Reference Token");
        }

        var token = await tokens.GetAsync(referenceToken); // TODO: Do I need to verify if the token is expired or will it return null in that case?
        if (token == null)
        {
            return new CustomGrantValidationResult("Invalid Reference Token");
        }

        // Generate the JWT as if it was for the reference token's client
        request.Client = token.Client;
        request.Client.AccessTokenType = AccessTokenType.Jwt;
        request.Client.AlwaysSendClientClaims = true;
        return new CustomGrantValidationResult(token.SubjectId ?? token.ClientId, GrantType, token.Claims);
    }

    public string GrantType => "exchange_reference_token";
}
```


```cs
new Client
{
    ClientName = "API Gateway",
    ClientId = "api-gateway",
    Enabled = true,
    Flow = Flows.Custom,
    AllowedCustomGrantTypes = new List<string> { "exchange_reference_token" },
    AllowedScopes = new List<string>
    {
        StandardScopes.AllClaims.Name
    },
    ClientSecrets = new List<Secret>
    { 
        new Secret("secretlol".Sha256())
    }
}
```

**Comment by leastprivilege** [comment]
You can also take the TokenValidator as a dependency. That validates the token and returns the claims.

— 
cheers
Dominick Baier

On 29 February 2016 at 18:02:32, Philip Bjorge (notifications@github.com) wrote:

@leastprivilege @brockallen -- I've taken a stab at a custom grant for exchanging reference tokens for JWTs. It seems to be working.
Anything stupid I might be doing?

public class ExchangeReferenceTokenGrantValidator : ICustomGrantValidator
{
    private readonly ITokenHandleStore tokens;

    public ExchangeReferenceTokenGrantValidator(ITokenHandleStore tokenStore)
    {
        tokens = tokenStore;
    }

    public async Task<CustomGrantValidationResult> ValidateAsync(ValidatedTokenRequest request)
    {
        var referenceToken = request.Raw.Get("reference_token");
        if (referenceToken == null)
        {
            return new CustomGrantValidationResult("Missing Reference Token");
        }

        var token = await tokens.GetAsync(referenceToken); // TODO: Do I need to verify if the token is expired or will it return null in that case?
        if (token == null)
        {
            return new CustomGrantValidationResult("Invalid Reference Token");
        }

        // Generate the JWT as if it was for the reference token's client
        request.Client = token.Client;
        request.Client.AccessTokenType = AccessTokenType.Jwt;
        request.Client.AlwaysSendClientClaims = true;
        return new CustomGrantValidationResult(token.SubjectId ?? token.ClientId, GrantType, token.Claims);
    }

    public string GrantType => "exchange_reference_token";
}
new Client
{
    ClientName = "API Gateway",
    ClientId = "api-gateway",
    Enabled = true,
    Flow = Flows.Custom,
    AllowedCustomGrantTypes = new List<string> { "exchange_reference_token" },
    AllowedScopes = new List<string>
    {
        StandardScopes.AllClaims.Name
    },
    ClientSecrets = new List<Secret>
    {  
        new Secret("secretlol".Sha256())
    }
}

**Comment by aivans** [comment]
> This is like an "act-as" or "on-behalf-of" style token. There's a OAuth2 work in progress spec for this, but in the meantime you can use the reference token as a custom grant type against the token endpoint. You'd then build a custom token validator to allow the exchange of the reference token for a full JWT.

Please point to the OAuth2 spec that solves this. I am interested on the current status.

Thank you

**Comment by pi3k14** [comment]
https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-06 I would think.
