### ISSUE TITLE
Configuration issue : Unable to set up Factory (IdentityServer V3 2.0.0)

### ISSUE THREAD

**Issue by Oephre** [IdentityServer/IdentityServer3#1727]
Hi, 

I've just downloaded IdentityServer V3 2.0.0 via Nuget using the -pre command.
I am following the "Get started documentation" but i ve got a reference issue on the Factory.Create or the InMemoryFactory.Create. Seems thoses classes are missing.
I have checked all IdentityServer3 Classes but i didn't find them.

I am using VS2015 with Resharper. 
I have created an empty ASP.NET project (.Net 4.5.2)

Is there something i did wrong ?

Regards

**Comment by larrifax** [comment]
Use the `IdentityServerServiceFactory`. Example usage can be found in [this sample file](https://github.com/IdentityServer/IdentityServer3.Samples/blob/dev/source/AspNet5Host/src/IdentityServerAspNet5/Startup.cs).

**Comment by leastprivilege** [comment]
The mvc walk through has not been updated to 2.0 yet.

**Comment by Oephre** [comment]
Thank you Larrifax. 

The IdentityServer is now running with the *IdentityServerServiceFactory*.

I can continue my discovery of IdentityServer3.

The goal is to set up several mobile applications and 2 angularjs sites with a bearer token integration. So i am trying to setting up an "external" IdentityServer. 

Many thanks to the team for that excellent solution.
Regards.
