### ISSUE TITLE
SSO in test doesn't work

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1728]
Hi

I've been trying to set up single sign on for a few days now, and got it working locally.
If I login to siteA, then navigate to siteB I'm automatically logged into siteB.

However, when I publish the sites to the test environment I'm not automatically logged into siteB. I have to explicitly trigger the log in process, although I don't have to enter any credentials.

This is the client setup:
```
new Client
            {
                ClientName = name,
                Enabled = true,
                ClientId = id,
                ClientSecrets = new List<ClientSecret>{
                    new ClientSecret(secret.Sha256())
                },
                Flow = Flows.Implicit,

                RequireConsent = false,
                AllowRememberConsent = true,
                AlwaysSendClientClaims = true,
                RedirectUris = uris.ToList(),

                PostLogoutRedirectUris = uris.ToList(),
                IdentityTokenLifetime = twoWeeks,
                AccessTokenLifetime = twoWeeks,
            };
```
And the startup authentication setup for the clients is
```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = clientId,
                ClientSecret = clientSecret,
                Authority = Constants.BaseAddress,
                ResponseType = "id_token token",
                Scope = "openid email profile ordersApi",
                RedirectUri = redirectUri,
                PostLogoutRedirectUri = redirectUri,
                SignInAsAuthenticationType = "Cookies",
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = async n =>
                    {
                        var nid = new ClaimsIdentity(
                                    n.AuthenticationTicket.Identity.AuthenticationType,
                                    Thinktecture.IdentityServer.Core.Constants.ClaimTypes.GivenName,
                                    Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Role);

                        // get userinfo data
                        var userInfoClient = new UserInfoClient(
                            new Uri(n.Options.Authority + "/connect/userinfo"),
                            n.ProtocolMessage.AccessToken);

                        var userInfo = await userInfoClient.GetAsync();
                        userInfo.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Item1, ui.Item2)));

                        // keep the id_token for logout
                        nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));

                        // add access token for sample API
                        nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));

                        // keep track of access token expiration
                        nid.AddClaim(new Claim("expires_at", DateTimeOffset.Now.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToString()));

                        // add some other app specific claim
                        nid.AddClaim(new Claim("app_specific", "some data"));

                        n.AuthenticationTicket = new AuthenticationTicket(
                            nid,
                            n.AuthenticationTicket.Properties);
                    },
                    RedirectToIdentityProvider = async n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
                            n.ProtocolMessage.IdTokenHint = idTokenHint;
                        }
                    }
                }
            });
```

The test sites use SSL and locally I do not. The only relevant cookie I have is ".AspNet.Cookies". I've tried setting the cookie domain to ".site.com" but no change.

I've tried to share the clientid between siteA and siteB, and I've tried separate clientid but no change.

Using version 1.6.2

Any pointers/tips?

**Comment by brockallen** [comment]
Well, for SSO to work you need to have a an authentication session at the STS (via a cookie). Not sure, but I'd debug more at the HTTP level.

**Comment by henninga** [comment]
Hmm, it seems like .AspNet.Cookies has different values for all the sites in test. Is that correct or should the value be the same?

**Comment by henninga** [comment]
When setting the cookie domain, the .AspNet.Cookies cookie are equal, but still not automatically signed in.

Tried setting AuthenticationMode to Active but no change

**Comment by loctanvo** [comment]
I think the behavior you get locally, `automatically logged into siteB`, is rather unexpected. Unless you actively do something in SiteB to trigger an authentication, the user will need to access an authorized resource to trigger the login process.

My guess is that when you run locally, siteA and siteB are sharing the client cookie (intended or not?) due to both running on localhost. That's why the user is automatically signed into siteB as well.

**Comment by henninga** [comment]
I've suspected what you're saying, but haven't found anything that helps me/gets me further.

That being said, the cookie domain and value are now the same on both sites. My guess would be that it would automatically sign me in, but apparently not.

I have not done anything to the machine key.

**Comment by loctanvo** [comment]
How do you expect to work? (Or what is the behavior you want to achieve?)

**Comment by henninga** [comment]
What I associate with the term SSO is that once I'm logged into one site, I'm automatically logged into every site without having to take any further steps such as clicking a link/button, redirecting to the login provider, etc.

This is not happening for us. I'm able to login to every site we have with IDserver (with one idserver session), but for each site we are either automatically redirected to idserver or we have to manually click a login link. 

In essence I want to share the same login session with all our sites.

**Comment by loctanvo** [comment]
I may be wrong, but the behavior you are describing is not supported out of the box (but you can design for it). Normally, SSO means that you are logged into a centralized instance (IdServer) and therefore, the user does not need to *specify credentials* every time while the IdServer login session is still alive. SiteA and siteB still need to actively *redirect the user* to IdServer for authentication. As long as the user is logged into the IdServer, this authentication request may result in silent redirects which the user does not even recognize. But the initial redirect must be initiated from siteA or siteB, unless you have actively done something.

So, in my opinion, the behavior you describe in your Test environment is rather correct.

**Comment by henninga** [comment]
Do you have any idea why it works as I want it locally when running iis express, but running it locally in iis does not?

**Comment by loctanvo** [comment]
I still can't see anything else than a shared cookie between siteA and siteB. When you run in IIS locally (not express), are the sites running on the same domain?

**Comment by henninga** [comment]
The cookie value and cookie domain are the same
Cookie domain is set to ".somesite.com", and both sites are showing the cookie in chrome.

By domain, you mean appdomain? I've changed the app pool in IIS so they are sharing the app domain (???) and it actually works. I'm getting the behavior I'm expecting. Verified it by reverting the change, and it does not work again.

I think siteB has trouble decoding/unprotecting the authentication ticket. Been digging around the Cookie Authentication code. Not sure why though, as the cookie is the same.

**Comment by henninga** [comment]
Ok, so I've tested a bit more.

I specified the same machinekey for both sites, and it apparently works. When I log into siteA (idserver) and refresh siteB, I am automatically signed in.

Not sure if it is supposed to work like that and if there is any drawbacks to it, but at first glance it works like I want it to.

**Comment by loctanvo** [comment]
I was thinking about the url domain in my previous comment. Unless you specify a data protector for the cookie option, it'll use the machine key as default (when you are using Katana). So unless the applications are using the same machine key, you'll encounter problems decrypting the cookie. Good it worked out for you. The two applications don't need to share appdomain.

**Comment by henninga** [comment]
Thanks for your help.

The fix has been deployed and a quick test verifies that it works :smile:
