### ISSUE TITLE
Login form hosted in application instead of IdServer

### ISSUE THREAD

**Issue by sphinxy** [IdentityServer/IdentityServer3#1730]
Business requirements says that login form must be hosted in our MVC application, without any redirecting users to another domain for showing IdServer login page. So application have username and password and must transform it into ClaimsPrincipal by itself using server-side communication with IdServer. I've found two ways to do it:
 1. Use access token and userinfo endpoint
   * Call RequestResourceOwnerPasswordAsync with username and password with scope "openid bla-bla-bla" and accure access token
   * Pass access token to userinfo endpoint, get identity claims, manuallly construct ClaimsPrincipal from claims and SignIt
 2. Imitate request to IdServer's login form from application.
   * Use HttpRequest to initially call form to get antiforgery.
   * Perform a second call with username/password/antiforgery/nonce
   * Finally gets identity token and use it to create ClaimsPrincipal

Both approach seems to be a overcomplicated. Here is a questions:
 1. Why i can't get identity token without involving httpclient/browser? I understand that not using a user's browser with cookie issued for IdServer URI leads to lost SSO ability, but it's not a big problem. I'm want some kind of client.GetIdentityTokenUsername. OAuth/OpenId does not support it? Right now i can't explain to business why we have this limitation.
 2. For first approach with userinfo endpoint - why i can't just use access token to create ClaimPrincipal from it? It's works fine if i start think about by application as resource, so i'm just  create scopes with ScopeType.Resource instead of ScopeType.Identity and all seems to be fine. Now while calling userinfo I have two additional http calls - first one to userinfo inself from application and second call from IdServer to external service at least from GetProfileDataAsync (this function calls and while creating access token if i request scopes with additional claims and while creating identity  claims for userinfo calls)

**Comment by leastprivilege** [comment]
So my question would be - if you don't care about sso or the other benefits of a shared/centralized authentication flow - why do you want to use open Id connect at all?

**Comment by sphinxy** [comment]
We want to use delegated authN and claim-based authZ with one server that every app/api trust. For example usage of access token and resource authZ is webapi is awesome. 

16.08.2015, в 12:22, Dominick Baier <notifications@github.com> написал(а):

> So my question would be - if you don't care about sso or the other benefits of a shared/centralized authentication flow - why do you want to use open Id connect at all?
> 
> Sent from my iPad
>

**Comment by leastprivilege** [comment]
So this has been discussed numerous times - to get SSO you need the redirect.

Resource owner is an option - but with the known limitations.
