### ISSUE TITLE
Possible bug when enabling the HTTP Logging feature of IdentityServer

### ISSUE THREAD

**Issue by estiller** [IdentityServer/IdentityServer3#1731]
Hi,
When enabling the HTTP logging feature of IdentityServer, the *RequestResponseLogger* class is placed into action. The following is called on any operation:
```c#
var reqLog = new
{
    Method = request.Method,
    Url = request.RequestUri.AbsoluteUri,
    Headers = request.Headers,
    Body = await request.GetOwinContext().Request.ReadBodyAsStringAsync()
};
```
*HttpContent* is a forward-only stream which can be read only once. As a result of reading the content in the *Body* property initialization, the content is not available later for reading.
I noticed this as the IdentityServer login view started to fail consistently because the server couldn't read the AntiForgery token from the login form (well, it couldn't read the form at all but I didn't get that far). In *ValidateAntiForgeryTokenAttribute.cs" the following will always return an empty byte array if the HTTP logger is enabled:
```c#
// ReadAsByteArrayAsync buffers the request body stream
// we then put the buffered copy into the owin context
// so we can read it in the IsTokenValid API without 
// disturbing the actual stream in the HttpRequestMessage
// that WebAPI uses it later for model binding. #lame
var bytes = await actionContext.Request.Content.ReadAsByteArrayAsync();
var ms = new MemoryStream(bytes);
ms.Seek(0, SeekOrigin.Begin);
var ctx = new OwinContext(env);
ctx.Request.Body = ms;
```

A workaround is to disable HTTP logging.

**Comment by brockallen** [comment]
Dup of #1672

**Comment by estiller** [comment]
Hmmm... Missed that one. :)
Thanks for all the hard work in supporting IdentityServer. It's really appreciated.
