### ISSUE TITLE
Question related to collecting extra information at the consent view

### ISSUE THREAD

**Issue by shaneprice** [IdentityServer/IdentityServer3#1732]
Great project thank you!

I am trying to get some of the examples working without much joy.

Within my startup.cs I have this defined

     public void Configuration(IAppBuilder app)
        {
            var factory = InMemoryFactory.Create(
                scopes: MyScopes.Get(),
                clients: Clients.Get(),
                users: Users.Get());

          factory.ViewService = new Registration<IViewService>(typeof(CustomViewService));

            var options = new IdentityServerOptions
            {
                Factory = factory,
                RequireSsl = false,
                CorsPolicy = CorsPolicy.AllowAll,
                SigningCertificate = Certificate.Get(),
                SiteName = "Auth",
                AuthenticationOptions = new AuthenticationOptions
                {
                    IdentityProviders = ConfigureAdditionalIdentityProviders,
                    LoginPageLinks = new LoginPageLink[] {
                            new LoginPageLink{
                                Text = "Register",
                                Href = "localregistration"
                            }
                        }
                }
            };
            LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());
            app.UseIdentityServer(options);
        }

My scopes are defined like

     public static IEnumerable<Scope> Get()
        {
            return new Scope[]
            {
             
                StandardScopes.Phone,
                StandardScopes.Email,
                new Scope
                 {
                    Name = Constants.StandardScopes.Profile,
                    DisplayName = "Basic profile",
                    Description = "Your basic user profile information (first name, last name, etc.).",
                    Emphasize = true,
                    Claims = (Constants.ScopeToClaimsMapping[Constants.StandardScopes.Profile].Select(x=>new ScopeClaim{Name = x, Description = x})).ToList()
                }
             };
        }

When Im redirected to the authorize view, Im only required to provide "Your user identifier" shouldn't Phone,Email and my custom DisplayName be shown within the list?

Have I defined my scopes incorrectly or do these requirements need to be set somewhere else?

![image](https://cloud.githubusercontent.com/assets/2302683/9296429/d3bb2d50-44e0-11e5-9878-4dd970faf554.png)

Thanks again for the project

**Comment by brockallen** [comment]
The client needs to request each scope, so just include all of them in the scope param from the client.

**Comment by shaneprice** [comment]
Thanks Brock. I feel rather stupid now for not checking the js application
