### ISSUE TITLE
Antiforgery token problem.

### ISSUE THREAD

**Issue by amid0** [IdentityServer/IdentityServer3#1733]
Hello guys.

Today I've found some kind of bug with Antiforgery token.
source/Core/Configuration/Hosting/AntiForgeryToken.cs line: 117

When this token appends to the cookies ExpireDate not sets. That mean that browsers treats this key as session cookie key and delete on browser closing.

Now I have problem with it. I login on site (token added) -> reopen browser (token disappear from cookie) -> click on logout and get error "AntiForgery validation failed -- returning error page".

Please add just one more line of code Append with expire date:

context.Response.Cookies.Append(cookieName, token, new Microsoft.Owin.CookieOptions
{
     HttpOnly = true,
     Secure = secure,
     Path = path,
     Expires = DateTimeHelper.UtcNow.Add(this.options.AuthenticationOptions.CookieOptions.ExpireTimeSpan)
});

Thank you in advance.

**Comment by leastprivilege** [comment]
@brockallen resolved?

**Comment by brockallen** [comment]
Do we really want the antiforgery token persistent?

**Comment by ankur--bhatia** [comment]
did not understand the issue here. We do get antiforgery validation failed error. But have not noticed it being a problem to our customers. Hence probably this is on the logout flow which less frowned upon when not working.  Why should the antiforgery token generated while login used for logout? Is it documented way?

**Comment by brockallen** [comment]
Any submit that has some effect should use an anti-forgery token. Imagine a malicious web page that does a `<form>` POST to the logout endpoint? That's the purpose of the anti-xsrf token.
