### ISSUE TITLE
Q: "There is an error determining which application you are signing into. Return to the application and try again." 

### ISSUE THREAD

**Issue by tonyeung** [IdentityServer/IdentityServer3#1734]
I'm getting the "There is an error determining which application you are signing into. Return to the application and try again." 

Looking through the code, it seems the message gets set if the login method on the Authentication Controller gets called in IdentityServer3.Core.Endpoints

    public async Task<IHttpActionResult> Login(string signin = null)

It seems like its trying to get some value from a cookie. 
I have the external login cookie enabled, but i guess it doesn't look there?

My owin config is
```
            app.SetDefaultSignInAsAuthenticationType("External");
            var factory = new IdentityServerServiceFactory()
                            .UseInMemoryClients(Clients.Get())
                            .UseInMemoryScopes(Scopes.Get())
                            .UseInMemoryUsers(new List<InMemoryUser>());

            var cors = new InMemoryCorsPolicyService(Clients.Get());
            factory.CorsPolicyService = new Registration<ICorsPolicyService>(cors);




            var options = new IdentityServerOptions
            {
                Factory = factory,
                AuthenticationOptions = new AuthenticationOptions()
                {
                    IdentityProviders = (appBuilder, signInAsType) =>
                    {
                        Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures();
                        app.UseKentorAuthServicesAuthentication(new KentorAuthServicesAuthenticationOptions(true));
                    }
                },
                LoggingOptions = new LoggingOptions()
                {
                     EnableHttpLogging  = true,
                      EnableKatanaLogging = true,
                       EnableWebApiDiagnostics = true,
                        WebApiDiagnosticsIsVerbose = true
                }
            };

            app.UseIdentityServer(options);
```
My app.config
```

  <kentor.authServices entityId="https://localhost:13855/AuthServices" returnUrl="https://localhost:13855/ExternalLoginCallback/">
    <identityProviders>
      <add entityId="http://domain/adfs/services/trust" 
           destinationUrl="https://domain/adfs/ls/" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">

        <signingCertificate fileName="TokenSigningStaging.cer" />
      </add>
    </identityProviders>
  </kentor.authServices>

  <system.identityModel />
```

**Comment by tonyeung** [comment]
I posted the wrong owin config, edited OP with the one I'm using.

**Comment by tonyeung** [comment]
Also, I'm able to hit the SAML server, enter credentials, and the ExternalLoginCallback gets called without a problem.

**Comment by brockallen** [comment]
You need to visit the login page by way of an authorization request. #1117 provided help for users that bookmarked this page.

**Comment by tonyeung** [comment]
*You need to visit the login page by way of an authorization request*
by login page, do you mean the one on `IdentityServer3.Core.Endpoints`?
also, by authorization request, do you mean `authorization_endpoint":"https://localhost:13855/connect/authorize` (from the discovery doc when running idsvr)

Does that mean that for my redirect from the saml server, i need to point it to `/connect/authorize` instead of the endpoint I defined myself?

Thanks for looking at this. I tried to reference the source code in order to step through, but I'm not really sure how to do that with this particular project. Usually I just include the project that matches the reference name.

**Comment by brockallen** [comment]
Well, I don't really know what your setup is or what you're trying to do -- I was just answering the question about the login page. IdSvr is an OIDC server and so when a OIDC client makes an authorization request then if the user needs to authenticate they are sent to our login page anid once that's done the authorization request can continue.

**Comment by tonyeung** [comment]
I'll try to create a repro. 
All I'm trying to do is integrate Kentor SAML with IdSvr3.

**Comment by tonyeung** [comment]
what's the difference between the IdentityServer3 and Thinktecture.IdentityServer3 packages?

**Comment by tonyeung** [comment]
Okay, so here is the repro
https://github.com/tonyeung/IdSvr3AndKentorAuthServices

I'm not sure what I'm doing wrong, but based off of the sample in the docs, this is as far as i got.
Since `TokenClient` doesn't exist, i went ahead and used a `HttpClient` to try to replicate as much as I could of the sample.

However, I can't get a token to come back because of invalid scope.

**Comment by tonyeung** [comment]
okay got the client and server talking. Adding in kentor to see if i can replicate the issue i'm having.

**Comment by tonyeung** [comment]
This project reproduces my issue: https://github.com/tonyeung/IdSvr3AndKentorAuthServices

The authentication server base url will need to be replaced with whatever your localhost https is set for, but other than that, you should be able to run the projects, the console should launch firefox in private browsing, and use the authorization url that I modeled from the hybrid samples.

the firefox window will have the login page and then when you click on saml2p, you will get the error. AFAICT, there are no errors in the log other than idsvr not finding a principal.

**Comment by leastprivilege** [comment]
any update?

**Comment by tonyeung** [comment]
I've rigged some stuff for it to work. I need a couple days to get some other stuff rolled out and then I'll troubleshoot this a bit more. I have a much better idea on how the server works now so I should be able to get some good progress by end of week or early next week at the latest.

**Comment by leastprivilege** [comment]
closing for now.

**Comment by tonyeung** [comment]
So I did some poking around, and it looks like I'm running into issues with the antiforgery token right now. If I comment out the `ValidateAntiForgeryToken` then the model is null. I used a zip download from a couple weeks ago though, so I'll fork and see if it makes a difference.

**Comment by brockallen** [comment]
Might be related to the fix we put into 2.0.1 related to enabling http level logging. Do you have that enabled?

**Comment by tonyeung** [comment]
the anti forgery token issue is fixed with the update. I can also go through most of the grants now with the in mem userstore. Going to add saml as a provider now to see if its still a problem.

**Comment by tonyeung** [comment]
I got it figured out. I was over complicating things.

**Comment by anttilah** [comment]
I have the same problem with Kentor authservices. What was the problem in Your case?

**Comment by tonyeung** [comment]
getting all the settings/configurations put in correctly was the problem I had. If you configure both idsvr and kentor correctly then it should work.

**Comment by ruwanthaka** [comment]
facing the same error , but only when we are running identity server in different port that default (80 in normal or 443 with https) looks initially it reach the correct authorizationEndpoint we marked (with added port  ( ex :http://[ip of the server]:[port]/connect/authorize) but then it redirect to  http:/[ip of the server]/login?signin=[guid]) without port number. if we manually correct it in URL it gives the above error

**Comment by mtayyab063** [comment]
**There is an error determining which application you are signing into. Return to the application and try again**. i got the same error

**Comment by anttilah** [comment]
In my case the reason was that authservice lost owin context if using discovery service

**Comment by mtayyab063** [comment]
any suggestion about fixing this?

**Comment by tonyeung** [comment]
turn on all the logging. If you don't understand the logs then step through the source. idsvr doesn't return clear errors to avoid leaking potentially sensitive data. You'll have to read the logs or step through the source to really figure out what's going on.

**Comment by mtayyab063** [comment]
Ok thank you, i will try enabling logging.

**Comment by robertmuehsig** [comment]
This is a pretty old one, but I had the same issue today. I configured IdS with upper-case urls, e.g. stage.local/WebApp instead of stage.local/webapp and it turns out, that this is quite important - so maybe if anyone else has this issue, make sure that you use lower case urls.

**Comment by myaesubi** [comment]
Hi @tonyeung , @robertmuehsig 
This is an old thread, however I appreciate it a lot if you could advise of any tips on how you solved the issue with Idsrv3 & KentorIT SAML2 middleware.

In my implementation OwinContext gets lost upon successful sign in to Okta.
I have detailed out the code and logs in [https://github.com/KentorIT/authservices/issues/774](https://github.com/KentorIT/authservices/issues/774)

Thanks again,
Mamrez
