### ISSUE TITLE
Question: Only accept some external users

### ISSUE THREAD

**Issue by manfredsteyer** [IdentityServer/IdentityServer3#1735]
Hi,

when one uses IdS3 to delegate to an external Id-Provider, like ADFS, is there a way to only accept external tokens for specific users/ external tokens with claims that match specific criteria? 

Best wishes,
Manfred

**Comment by loctanvo** [comment]
Yes you can. When you implement `IUserService`, the `AuthenticateExternalAsync` will get called when the user has successfully authenticated with the external provider. Here, you can look at the claims and apply custom logic. Example: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomUserService/CustomUserService/ExternalRegistrationUserService.cs#L27

**Comment by manfredsteyer** [comment]
Great. Thanks in adv.
