### ISSUE TITLE
Redirect 302 / Remote Auth

### ISSUE THREAD

**Issue by coreyperkins** [IdentityServer/IdentityServer3#1736]
I have a small issue that I do not understand, but could be quite normal.  I setup a small asp.net mvc app to auth against a remote oidc server (also built on idsrv). Auth works, but I receive a 302 when it hits my redirect uri (I don't hit a breakpoint in that action). Following the 302 I am redirected to root. The problem with this is that I want to always hit the redirect uri, as opposed to being redirected, so I can attach some info to the session. Anybody seen this before? Should I take another approach?

<img width="479" alt="screen shot 2015-08-18 at 3 15 37 am" src="https://cloud.githubusercontent.com/assets/429696/9325842/1a3862fa-455b-11e5-83d9-3f018c5361f7.png">
<img width="607" alt="screen shot 2015-08-18 at 3 16 09 am" src="https://cloud.githubusercontent.com/assets/429696/9325848/1ff4eb46-455b-11e5-93dc-ebba82481c37.png">

**Comment by loctanvo** [comment]
I guess you trigger authentication on `/` (e.g. by using an `[Authorize]` attribute). The OpenIdConnectMiddleware keeps track of your original path, and redirects you to that path upon successful authentication. The `/account/authorize` is handled by the OIDC MW, and your controller path is never executed.

There probably are some event handlers in the OIDC MW you could hook on to apply session info.

**Comment by coreyperkins** [comment]
Correct, I do use [Authorize] on my HomeController.

**Comment by loctanvo** [comment]
Well, that's just how the middleware works. It's a nice thing that the user is redirected to where he/she initiated the authentication process. You can always handroll everything (which is not difficult). 

However, like I mentioned, there probably are hooks or options on the middleware you can specify. Have you looked into that?

**Comment by coreyperkins** [comment]
I have not gotten into the code itself. I did find CallbackPath on the OIDC options but I have yet to give it a go.

**Comment by coreyperkins** [comment]
Not sure if I am barking up the right tree or not, but I started trying to use the Notifications on the OpenIdConnectAuthenticationOptions like so:

Notifications = new OpenIdConnectAuthenticationNotifications() {
                    SecurityTokenValidated = async n => {
                        var resp = n.Response;

                        System.Web.HttpContext.Current.Session["AccessToken"] = n.ProtocolMessage.AccessToken;

                        // I got no clue if this await is correct or not...                        
                        await Task.FromResult(n);
                    },
                    SecurityTokenReceived = async n => {
                        var resp = n.Response;

                        System.Web.HttpContext.Current.Session["AccessToken"] = n.ProtocolMessage.AccessToken;

                        // I got no clue if this await is correct or not...
                        await Task.FromResult(n);
                    },
                    MessageReceived = async n => {
                        var resp = n.Response;

                        // I got no clue if this await is correct or not...
                        System.Web.HttpContext.Current.Session["AccessToken"] = n.ProtocolMessage.AccessToken;

                        await Task.FromResult(n);
                    }
                },       

This will get the access token and allow me to stick it in the session. I'm doing this so that I can pass it to the browser for API calls. The only downside so far is that these notifications only seem to get hit on the original auth with the provider. If I am debugging and restart the session it doesn't happen again. I can live with that since it only inconveniences me. This still feels like a stretch though.

**Comment by coreyperkins** [comment]
I changed up my strategy a bit. Instead of using the session I added a custom claim to hold the token, much like what is done at https://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html.

This way I can access it later in my Home/Index action to share with the client javascript application for resource calls.

This can be closed unless somebody has a better idea on how to get an access token from a backend to a client js app (without making an extra server call for the token).

**Comment by loctanvo** [comment]
We also use a custom claim and store it in the application cookie (for backend to api calls, server to server). Works well for us.

So you are making api calls directly from JS? And you retrieve the access token from the cookie?

**Comment by coreyperkins** [comment]
Yep, regarding making api calls directly from the js. I create the custom claim and add it to the identity's claims collection. Then, on the controller action I extract that and serve it up to the javascript via the ViewBag.

I hadn't thought of actually extracting it from the cookie itself in the browser. That's an interesting idea, too.

**Comment by leastprivilege** [comment]
resolved?

**Comment by coreyperkins** [comment]
Yep.
