### ISSUE TITLE
Do not hide errors when on localhost

### ISSUE THREAD

**Issue by buybackoff** [IdentityServer/IdentityServer3#1737]
Please, could you show all errors+stack trace directly in the browser when running on localhost? I have just spent too much time on "Unexpected error" after permission grant window, was trying to debug the IdSrv3 source code, until I found a conflict in JSON.NET assemblies - not directly related to IdSrv at all.

**Comment by leastprivilege** [comment]
Use logging?

**Comment by buybackoff** [comment]
Eventually I found the issue in the logs. But I see no reason to hide exceptions in localhost/debug mode. Sometimes logs were empty (on other errors)

**Comment by brockallen** [comment]
If you had version conflicts, this makes me think you're using IdSvr from source and not from NuGet -- the recommendation is to use it from NuGet.

**Comment by buybackoff** [comment]
The issue is about ease of debug, I have fixed the versions conflict very fast after I identified it.

**Comment by brockallen** [comment]
Sure, but I was simply adding a bit of additional info related to your situation.

**Comment by leastprivilege** [comment]
@brockallen todo or wontfix?

**Comment by leastprivilege** [comment]
logging is the answer. works really well for me.
