### ISSUE TITLE
Quesion: Upgrading from 1.6.2.0 to 2.0, need some clarification on class names

### ISSUE THREAD

**Issue by OutOfTouch** [IdentityServer/IdentityServer3#1739]
Hi, 

I am upgrading from 1.6.2 to 2.0, my app only used Client Credentials and EF to Sql server storage for IdSvr configuration. My questions are  I am not 100% sure which classes were moved or replaced, for example in my Factory Users.Get, Scopes.Get and Clients.Get doesn't seem to exist now as well as ToEntity.
Most of the code I am using came from the samples for 1.6.2.

These lines broke:
ConfigureClients(Clients.Get(), efConfig);

factory.Register(new Registration<List<InMemoryUser>>(Users.Get()));

I am just looking for some guidance on how to figure out how to proceed with upgrading, what replaces what so to speak.

Seems like a lot of breaking changes to me,  things like ScopeRestrictions in the Client class don't exist in the 2.0 version so I am not sure how to replace it.

**Comment by brockallen** [comment]
This list is a summary of the changes: https://github.com/IdentityServer/IdentityServer3/releases/tag/2.0.0.

Also, the samples (finally) got updated on master to be in sync with 2.0.0.

**Comment by OutOfTouch** [comment]
How do we upgrade the IdSvr config database?

**Comment by brockallen** [comment]
You need to do that migration yourself. If you're using EF, then it has migrations support. We warn people of this in the docs: https://identityserver.github.io/Documentation/docs/ef/migrations.html

As for logging, you pull in one of the logging frameworks that LibLog supports and just configure it. We then dynamically detect it and use it (again, via LibLog). Check the samples -- they are all now using serilog.

**Comment by OutOfTouch** [comment]
Ok I was wondering why we didn't have to set the LogProvider anymore.

**Comment by OutOfTouch** [comment]
I don't understand how I can add an ExceptionLogger to handle unhandled exceptions with IdSvr.

**Comment by OutOfTouch** [comment]
I am getting invalid column names when it tries to create the database, I deleted my old database and decided to start fresh rather then migrate.

**Comment by OutOfTouch** [comment]
Any ideas on how to add my own ExceptionLogger for unhanlded exceptions.
