### ISSUE TITLE
HTTP 400 status code seems odd

### ISSUE THREAD

**Issue by dachew** [IdentityServer/IdentityServer3#1740]
We're implementing IdSrv3 and have had this brought up more than a couple of times during our technical discussions: IdSrv3 returns a 400 for certain error cases, where a different 40x code seems more appropriate.

For example, when requesting a client token, if the client doesn't provide valid id & secret, IdSrv3 answers with a 400.  A 401 seems like it might be a better fit.  There are other use cases where a 400 is returned in place of a 401 or possibly a 403.

From the [w3 spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html):
> *10.4.1 400 Bad Request
The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.*

Has anybody else encountered this as an oddity?  Is it a 400 since it's a best-fit type error code that can be used for all error codes (this simplifying error handling)?

It's not an issue for our implementation, but we are curious about it.

**Comment by brockallen** [comment]
For all the OIDC protocol endpoints, we do what the spec says: http://openid.net/specs/openid-connect-core-1_0.html#TokenErrorResponse

**Comment by dachew** [comment]
@brockallen thanks, that's exactly what we are looking for.
