### ISSUE TITLE
Receiving "HTTP Error 403.14 - Forbidden" error

### ISSUE THREAD

**Issue by vaananart** [IdentityServer/IdentityServer3#1741]
I am a newbie who is trying to understand Identity Server and I got the latest master branch of the source for IdentityServer3 sample tutorial. 

As I ran through the "Creating the simplest OAuth2 Authorization Server, Client and API" section of the documentation and ran the source code against it, I am receiving the 403 error instant of 401 error as mentioned in the documentation. 

The Api part of the source code was not hitting the breakpoint placed in the TestController.Get(). How can I go about capturing the error to understand Error 403? Where can i get additional information about Error 403.

On the other hand, The Client project in the solution is able to validate the IdSrv project successfully.

Please, let me know if any additional information is require to post that can help understand and resolve this problem.

Thanks

**Comment by loctanvo** [comment]
403 normally indicates that the action is forbidden. The user is authenticated, but lacks specific rights. The most common cause is lack of scopes or specific claims that the Api requires. 401 indicates that the user is not authenticated.

Are you requiring any specific scopes in the API?

**Comment by varunjoshi12** [comment]
Hi,
I have made userlogin Web-api in php for android device and i have tested that api on hurl.it solution it works fine on hurl but it creates forbidden error from device side please help me to solve this problem.

code:

function sendResponse($status = 200, $body = '', $content_type = 'application/json') {
$status_header = 'HTTP/1.1 ' . $status . ' ' . getStatusCodeMessage($status);
header($status_header);
header('Content-type: ' . $content_type);
echo $body;
}

class socialapp {

private $db;

function __construct() {

/* $this->db = mysql_connect('localhost', 'root','');
mysql_select_db('socialworld',$this->db) or die(mysql_error()); */

}

**Comment by leastprivilege** [comment]
resolved?

**Comment by varunjoshi12** [comment]
yes, its a device side error now it is resolved
