### ISSUE TITLE
Incorrectly enforcing nonces for Hybrid Flow

### ISSUE THREAD

**Issue by jnpwly** [IdentityServer/IdentityServer3#1742]
I am pretty sure that an incorrect "fix" was made in 1.5.5, specifically in commit ae8a2cb, where the code in AuthorizeRequestValidator.cs was changed from:

                if (request.Flow == Flows.Implicit)
                {
                    // only openid requests require nonce
                    if (request.IsOpenIdRequest)
                    {
                        LogError("Nonce required for implicit flow with openid scope", request);
                        return Invalid(request, ErrorTypes.Client);
                    }
                }

to:

                if (request.Flow == Flows.Implicit ||
                    request.Flow == Flows.Hybrid)
                {
                    // only openid requests require nonce
                    if (request.IsOpenIdRequest)
                    {
                        LogError("Nonce required for implicit and hybrid flow with openid scope", request);
                        return Invalid(request, ErrorTypes.Client);
                    }
                }

Is it actually an OIDC requirement that a Hybrid Flow does need to specific a nonce on the Authorize endpoint request, or is it actually an error that IdSrv requires a nonce? My reading of the spec is that the former is correct, that a nonce is not required on the Authorize endpoint request, and that the "fix" made in 1.5.5 is actually not correct.

My pedantic reading of the spec tells me this:

* section 3.1.2.1 of the spec (here: http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) shows that the nonce is optional for an Authentication request.
* section 3.2.2.1 of the spec (here: http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthorizationEndpoint), however, shows that the nonce is *mandatory* for Implicit Flows, and finally
* section 3.3.2.1 of the spec (here: http://openid.net/specs/openid-connect-core-1_0.html#HybridAuthRequest) to me, indicates that the nonce is *optional* for Hybrid Flows.

So, I'm pretty sure the changes made in commit ae8a2cb on 8 May 2015 are actually incorrect.

Unfortunately, we recently upgraded our IdSrv nuget packages from 1.2.1 to 1.6.2, and now a specific client is no longer working.

We're going to rollback to to the v1.5.4 nuget packages, in order to revert to the pre-1.5.5 behaviour around nonces. 

Apologies if I'm making a song and dance about this, but I've had someone on my back all afternoon!

**Comment by leastprivilege** [comment]
The changes were made to pass the oidc conformance tests, so I am pretty sure that's legit. I can follow up when I am back from holidays.

**Comment by jnpwly** [comment]
No, this is *not* a valid bug; I'll close it.

Reading technical specs certainly takes a special kind of skill! 

So, where as the OIDC spec implies that nonces are *optional* for Hybrid Flows (section 3.3.2.1 of the spec here: http://openid.net/specs/openid-connect-core-1_0.html#HybridAuthRequest), reading further down the spec, in section 3.3.2.11 (http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken) it states that nonces are *required* for the ID Tokens in a Hybrid flow. That then means that, yes, you *do* have to supply a nonce when making an OIDC request.. and hence the IdSrv code *is* correct.

At the end of the day, can't really argue with the OIDC self-certification process.

**Comment by jnpwly** [comment]
And enjoy your holiday, @leastprivilege!
