### ISSUE TITLE
Question: Resource Owner Password Credential Flow

### ISSUE THREAD

**Issue by kiran-mahadev** [IdentityServer/IdentityServer3#1744]
Hi,

Just want to ensure that I'm heading in the right direction; Need your guidance.

I have Web API(s) that authorize user privileges before responding to requests.

Requirement:
I have a windows service that would have to run under an administrator's credentials (for auditing purpose). This service, will have to call the Web API(s) for data.

Selected approach:
1. I plan to implement Resource Owner Password Credentials Flow.
2. Using the administrator's credentials, I would get an access token. And, the access token will be used to call the Web API(s) where the administrator's privileges are verified.

Implementation assumptions:
1. When installing the windows service I plan to prompt for administrator's username and password so I can get an access token when the service starts and forget the user credentials.
2. Refresh token will be used to refresh token when it is time (Reference: https://github.com/IdentityServer/IdentityServer3/issues/358)

Questions:
1. What should happen when the refresh token expires? Should the windows service be stopped? Or
2. Would it be better to securely persist user credentials somehow and use that to get new token when the refresh token has expired? I know this is not a good idea though.

**Comment by brockallen** [comment]
Resource owner is for users. Client credentials is for a client app without a user. Once the token expires, then you just get a new one using the client credentials.

**Comment by kiran-mahadev** [comment]
Thanks for your time Brock!

The reason I was planning to use Resource Owner Password Credentials flow was to re-use the Web API code.

The Web API(s) I mentioned are also getting used by an AngularJS application. And on each request, the user's privilege is getting verified.

If I implement a Client credentials flow I would have:
1. Avoid verifying user's authorization in the API, when the client is a windows service; as there is no user in context. Or
2. Create new action methods in the API controllers for windows service.

Also, Is it wrong to expect a windows service to be running under an administrators credentials? Please guide.

**Comment by brockallen** [comment]
Well, I'm not sure why your API is accepting and validating credentials -- i'd expect the client app to get a token for you API instead. Maybe I don't understand your setup.

**Comment by kiran-mahadev** [comment]
I'm sorry if I confused you. Here is the complete setup:

With User Interaction -

1. We have an AngularJS client application
2. The client application talks to Web API for data
3. We have implemented Implicit Flow on the AngularJS client application. So, what gets sent to the Web API is the access token.
4. The access token holds userId and role name.
5. The Web API validates the access token and on successful validation it fetches user's privilege.
6. We have added an action filter attribute that specifies the required privilege on each action method. The filter ensures that the user requesting data is really authorized to access the same.

Without User Interaction -

1. There are certain workflows/scenarios that require the us to perform some operation(s) without any user interaction.
2. The Client application in these scenario's is the windows service.
3. The windows service also needs access to data. So, it calls the Web API(s).
4. What we plan is to add all possible privileges to an Admin user.

As a result the windows service can be run under an Admin's credentials.

Your thoughts?

**Comment by brockallen** [comment]
Ah, ok. So yea, the client app (windows service) should use client credentials flow. It'll use the access token with the API. This is the great feature -- the API always uses access tokens. The difference is that w/ the client credentials flow access token there will be no "sub" claim. But by virtue of the access token and the scope for your API you will know the client is allowed to use the API.

**Comment by kiran-mahadev** [comment]
Great! Thank you so much for your time..
