### ISSUE TITLE
Email Registration and Activation

### ISSUE THREAD

**Issue by ANEDev** [IdentityServer/IdentityServer3#1745]
Hey community,

I want to implement a process in which a user needs to activate a new account via email before it's possible to login. Is there someone who know an instruction how to realise that problem with IdentityServer3 ?

Thanks
ANE

**Comment by brockallen** [comment]
This would be up to your code to do this as part of your registration and identity management system. This is not a feature of IdSvr.

**Comment by loctanvo** [comment]
@ANEDev Like @brockallen writes, you need to handle it yourself. There are several ways of doing it, and this is just one of them:

1. Register the user, mark him/her inactive in your DB
2. When implementing `IUserService` in IdentityServer, check for this status in [`IsActiveAsync`](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/IUserService.cs#L77)

Then, you need to have your own implementation of how to activate the user's account. May be useful for you: [Samples of custom user service implementation](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService).

**Comment by ANEDev** [comment]
Thanks that was helpful
