### ISSUE TITLE
Debug into identityserver3 instance sourcecode

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1749]
Hello 

I want to debug into my Idserver3 instance running local on my IIS. The exception to debug occurs in ConfigureCookieAuthenticationExtension.cs:line 96.
IdentityServer3 is included via nuget and pdbs are available in iisexpress output folder. Visualstudio Debug - Module Window claims that the thinktecture module is loaded along with symbols.

How can one debug into the identityserver3 sources? If I open the downloaded identityserevr sources and set breakpoints they appear being disabled. If I start the identitySourcecode solution and attach to the running IIS instance also claims that symbols are not loaded.

Any hint?

**Comment by brockallen** [comment]
If I have all the code locally then I seem to be able to just open the source files and put breakpoints.
