### ISSUE TITLE
What is the optimal way to enable a client to search users in the user store backend?

### ISSUE THREAD

**Issue by zik319** [IdentityServer/IdentityServer3#1750]
I have a wpf application which is working with an Idsrv3 instance and MembershipReboot user store.
I want an authenticated user to be able to reference different users who are also registered for the app, sort of an infix search. 
The openid connect RFC (userinfo endpoint) only allows to get data about the authenticated user.

Is there a way to get all the usernames for the application using Idsrv3 current implementation?
Or perhaps I should create a separate api that works directly with the MBR db?

Thanks

**Comment by loctanvo** [comment]
You most likely need to create your own api (preferrably protected) that serves you this. This not part of the authentication concept, and therefore will not be supported by OIDC standard nor identityserver (at least I will be *very* surprise if that happens :-) ).

**Comment by zik319** [comment]
@loctanvo thanks for your answer.
I eventually created an api that works with the MBR.
