### ISSUE TITLE
Exclude all roles from being added to the token

### ISSUE THREAD

**Issue by AlbertoCe** [IdentityServer/IdentityServer3#1751]
Hi,

I'm implementing a wpf application that, after authenticating the user against Identity Server, send the token to a wcf service that will serve the requested resource.

The problem is that I'd like to not have all the user roles included in the token (it's becoming quite big), but I'd like to have the webservice retrieve them by calling the STS userinfo endpoint using the access token.

How could I achieve this behavior ?

I've tried several of your examples but every time the user complete the authentication process all his roles are included in the token (or they are excluded at all and they are not being retrievable using the user info endpoint).

Best regards,
Alberto.

**Comment by leastprivilege** [comment]
There's no easy way of doing that right now - 

you could strip the roles in the claims provider but leave the scope in.

we need to discuss that @brockallen

**Comment by leastprivilege** [comment]
Coming to think of it - in v2 the context object will tell you from which code path the GetProfileData call is made. 

You could strip the role claims for the access token, but return them if invoked from UserInfo. That's easy to do.

**Comment by leastprivilege** [comment]
have you tried it - otherwise I will close.

**Comment by AlbertoCe** [comment]
Hi,
I still have to try it, I need some more time to update IdentityServer in my solution and I hope to try it in this weekend.
Could you wait until next monday ?

**Comment by leastprivilege** [comment]
OK

**Comment by leastprivilege** [comment]
I assume this has worked. closing.
