### ISSUE TITLE
Question: problem with mvc/webapi configuration

### ISSUE THREAD

**Issue by dogcane** [IdentityServer/IdentityServer3#1752]
Hi to everybody, I'm quite new to IdentityServer and I'm struggling with a configuration/setup problem.
I've a MVC application that contains the GUI for different modules (mapped as areas). The real modules are hosted into windows services and exposed via webapi (a sort of microservices stuff).
I want to allow a user to login onto MVC application and then call the services with the current identity.

My question is....which is the best way to configure all the system? Is "IdentityServer" the right direction? I've followed

Thanks in advance!

**Comment by brockallen** [comment]
You can get an access token from IdSvr and use that to call your API.
