### ISSUE TITLE
After v2.0 upgrade, custom _xxxx.html files in the project not recognized anymore

### ISSUE THREAD

**Issue by iltera** [IdentityServer/IdentityServer3#1754]
I upgraded my IdSrv3 v1.6.2 today 2.0. Everything is working now, except the custom html pages inside "assets" folder (like "_login.html" -  But custom js and css files are all added to layout page).

Is there something we should know about for 2.0 regarding to overriding embedding assets?

**Comment by brockallen** [comment]
assets renamed to templates: https://github.com/IdentityServer/IdentityServer3/releases/tag/2.0.0

**Comment by iltera** [comment]
Yeah, I remember reading that. Somehow missed it :) Put the html files in a templates folder and everything is working again. Thanks!
