### ISSUE TITLE
Refreshing Claims After Authentication

### ISSUE THREAD

**Issue by aronblum** [IdentityServer/IdentityServer3#1757]
Hi,

The situation is that I need to refresh claims after authentication has already occurred. An example of when I require this is if a person updates their email address. Currently the DB is updated, but because claims are still their original values, any fields that are populated by the email claim still has their old email address showing.

Does anyone have any tips as to how I can solve this issue?

Cheers,

Aron

**Comment by brockallen** [comment]
You'd need to re-trigger authentication to IdentityServer from the client app.

**Comment by aronblum** [comment]
Hey Brock,

What's the best way to do that?

Cheers,

Aron

**Comment by brockallen** [comment]
Call the Katana Challenge API.

**Comment by aronblum** [comment]
Hey Brock,

Would there possibly be an example in the documentation or samples?

Cheers,

Aron

**Comment by brockallen** [comment]
Well, this is more of a question around how the microsoft code works, so you could check wiht their docs/samples. I don't know if any of ours happen to call Challenge anywhere.
