### ISSUE TITLE
Question: Using IdentityServer3 with Facebook on non-web clients such as Android/IOS and WPF Clients  

### ISSUE THREAD

**Issue by jaeyow** [IdentityServer/IdentityServer3#1758]
I have setup my IdentityServer3 and have been using it with Resource Owner Password Flow and it has been great so far. My Asp.Net client has it's own login screen with username and password, and it calls the extension method like so:

client.RequestResourceOwnerPasswordAsync("bob", "bob", "read write", optional).Result;

Now we just had this requirement to allow 3rd Party Logins using Facebook. From what I understand from the document https://identityserver.github.io/Documentation/docs/configuration/identityProviders.html, all I need is to add the required identity provider to the AuthenticationOptions. I did that with Google and that works. I imagine a similar process for Facebook.

Now the problem I have is that, in the process of logging in with Google, I need to first redirect the user to IdentityServer3 login screen, click on the Google login button, user gets redirected to Google, then gets presented the consent screen, etc, etc, until we eventually get our access token back from IdentityServer.

Question: 

How can I do this process (or is it even possible), without having to do the first redirect to the IdServer login screen. I don't really want to use that login screen, all I really want is to click the button "Google Login", to kick off the google login process.

The issue really is that it doesn't look so smooth having to initially go to another page, just to click on the "Facebook login" or "Google Login" buttons.

I want to have these 3rd Party buttons on my Login Page, and not have to redirect to my Identity server's login page.

Similar situation for mobile apps (Xamarin). We will be making an app soon, but I'm unclear how to have this External authentication process happen, yet still use my IdServer, without having the need to do the initial redirect to the IdServer login screen. As you can imagine, it will look ugly if we have to redirect first to the IdServer Login screen. 

Does that make sense, or am I missing something obvious?

**Comment by brockallen** [comment]
To use the 3rd party logins you need to do the redirect style to the IdSvr login page. Using resource owner password flow means you miss out on all the features in the token service like SSO, 2fa and federated authentication.

**Comment by jaeyow** [comment]
thanks Brock.
