### ISSUE TITLE
Custom Views Not Displaying After 2.0 Upgrade

### ISSUE THREAD

**Issue by aronblum** [IdentityServer/IdentityServer3#1759]
Hi,

I have custom views for _error.html, _layout.html, _loggedOut.html and _login.html. These are all in a folder named assets. The default views for these are being displayed after the 2.0 upgrade. I see that documentation is still pending.

In the meantime, how can I override the default views and use my custom ones again?

Cheers,

Aron

**Comment by loctanvo** [comment]
Breaking change in v.2.0.0:
[`Default view service's HTML files folder changed to "templates"`](https://github.com/IdentityServer/IdentityServer3/releases/tag/2.0.0)

Related issue: https://github.com/IdentityServer/IdentityServer3/issues/1754

**Comment by rsantosdev** [comment]
If you are using vNext, there is another issue, the default class to load views `FileSystemWithEmbeddedFallbackViewLoader` is using `AppDomain.CurrentDomain.BaseDirectory` to get the base path, what is giving the wrong path to search for views.

After digging into source code, I made my app work doint:

1 - On `Configure` method in `Startup.cs` class add a dependency to `IApplicationEnvironment` called `appEnv` or another thing you want.

2 - In the creation of viewOptions do the following:

```cs
var viewOptions = new DefaultViewServiceOptions
                {
                    CacheViews = false,
                    ViewLoader = new Registration<IViewLoader>(new FileSystemWithEmbeddedFallbackViewLoader(Path.Combine(appEnv.ApplicationBasePath, "customviews")))
                };
```

Change `customviews` to the name of your directory, you should be good to do

**Comment by brockallen** [comment]
@rsantosdev so is there a bug with the default view loader? if so, do you mind opening a new issue explaining it?

**Comment by rsantosdev** [comment]
I really dont know if it is a bug, I need to test in other scenarios, but for asp.net 5 (vNext) applications the `AppDomain.CurrentDomain.BaseDirectory` returns the foldere where dnx/dnu is hosted. Not the app directory.

I can submit a pull request tring to fix on the vNext branch if you guys want to.

**Comment by leastprivilege** [comment]
Another case of "not fully supported on asp.net 5" - but also "why would you prefer aspnet5 over katana as a host (besides for expirements)"
