### ISSUE TITLE
Very very new to this IdentityServer

### ISSUE THREAD

**Issue by sumanballapuramgh** [IdentityServer/IdentityServer3#1760]
I am very new to this IdentityServer. My requirement is quite simple. But hard to understand this IS3 while digging through it. To provide atmost security we must validate all users through ClaimsPrincipal. How about when adding/registering a new user gets into InMemoryUser list while we configure this one time? Do we need to hard push this user as Claim to InMemory List?
Also, trying to understand how can i attain multi-tenancy by this? I mean allowing user to access other sites as SSO(Single Sign-On). Response for this question would be highly appreciable.
Thanks in advance.

**Comment by brockallen** [comment]
The in-memory users are just there for testing and demo purposes. You will want a real database for your users, and you will implement a custom user service so IdSvr can use those users. Check the docs and samples.
