### ISSUE TITLE
Perform operation before logout

### ISSUE THREAD

**Issue by pbujok** [IdentityServer/IdentityServer3#1761]
I'm trying to find way to perform operation directly before the moment when authentication cookie is being  cleared. I tried to implement custom event service, but logout event is raised too late for me. I Also tried do it by overriding SignOutAsync method but this is also too late. Please let me know if have some solution for my issue. Maybe could you provide in your implementation some event like BeforeUserSignOut

**Comment by brockallen** [comment]
Does the SignOutAsync on the user service not work?

**Comment by pbujok** [comment]
Unfortunately SignOutAsync is invoked too late for me. I need to perform operation before ClearAuthenticationCookies();

``` c# 
//AuthenticationController:Logout

// I need to be able to do something in this moment
ClearAuthenticationCookies();
SignOutOfExternalIdP();

if (user != null && user.Identity.IsAuthenticated)
{
    await this.userService.SignOutAsync(user);
    var message = signOutMessageCookie.Read(id);
    eventService.RaiseLogoutEvent(user, id, message);
}
```

**Comment by brockallen** [comment]
Can you explain a bit more why?

**Comment by leastprivilege** [comment]
any update - otherwise I will close

**Comment by pbujok** [comment]
Sorry, I was busy in other tasks and forgot to write. I resolve my problem other way, so issue can be closed. Thanks.
