### ISSUE TITLE
Example to cache/store tokens in a SQL database?

### ISSUE THREAD

**Issue by stefan89** [IdentityServer/IdentityServer3#1762]
Is there an example to cache/store tokens in a SQL database instead of the in-memory default cache solution?

More info:
https://identityserver.github.io/Documentation/docs/advanced/caching.html

We want to use a SQL database to store the tokens to be sure they are stored somewhere in case the server stops working and have to be restarted.

**Comment by brockallen** [comment]
Look at our EF repo.

**Comment by stefan89** [comment]
@brockallen thanks. Works great
