### ISSUE TITLE
Lotus Domino LDAP provider

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#1763]
Hello,
I have IdSrv3 v2 and i want to integrate this with  Lotus Domino LDAP Server. 
How to configure this lotus domino LDAP like external provider in my idsrv?

**Comment by brockallen** [comment]
You'd do this integration yourself in your custom user service.

**Comment by leastprivilege** [comment]
let us know if you want to make your impl public so we can link to it from our docs
