### ISSUE TITLE
Question: How to add an ExceptionLogger to handle unhandled execeptions in IdSvr?

### ISSUE THREAD

**Issue by OutOfTouch** [IdentityServer/IdentityServer3#1764]
I am trying to figure out how I can add in an ExceptionLogger and ExceptionFilterAttribute into IdSvr so I can handle unhandled exceptions and so I can send back a custom messages. Is there a way to do this?

**Comment by leastprivilege** [comment]
This is currently not supported. All error messages are according to the specifications (plus custom description in certain cases).

Exceptions are logged via logging/eventing.

If you think it should be supported, please open a feature request with detailed description.
