### ISSUE TITLE
Token signing certificate

### ISSUE THREAD

**Issue by lenguyen89** [IdentityServer/IdentityServer3#1766]
Hello,

We used makecert to generate my own certificate for token signing. However, when we deploy our identity server to IIS 8.5, we have to turn on LoadUserProfile in the AppPool setting in order for it to work. If we leave LoadUserProfile turn off, we would get a "CryptographicException : The system cannot find the file specified." We didn't have to do this for the default certificate that come with IdentityServer3. Did we miss something when we generated our own cert?

Thanks

**Comment by brockallen** [comment]
Not sure. The default certificate is of course for demo purposes and shouldn't be used. As for your own cert -- did you deploy it to the machine certificate store?

**Comment by lenguyen89** [comment]
No I embedded it in my project dll

**Comment by brockallen** [comment]
In general it's recommended that you deploy server signing certificates to the machine certificate store -- that way you can use the OS security features for protecting it.
