### ISSUE TITLE
What is the recommended version for new project?

### ISSUE THREAD

**Issue by explunit** [IdentityServer/IdentityServer3#1767]
I see that 2.0 is released but is this the recommended version for someone starting a new project based on IdentityServer3? It appears that the documentation for v2 is largely TODO, and am I reading it correctly that none of the samples have been updated based on the 2.0 breaking changes?

**Comment by OutOfTouch** [comment]
Samples have been updated and 2.0 is the version I would use on a new project.
Brock linked on my question the breaking changes and that the samples have been updated.
https://github.com/IdentityServer/IdentityServer3/issues/1739

**Comment by explunit** [comment]
Sorry, I guess I generalized from the first sample I looked at:
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs#L42

**Comment by brockallen** [comment]
Ah sorry -- I think that's one of the few samples that was not yet updated to 2.0.0.
