### ISSUE TITLE
DefaultViewLoader on Asp.net vNext (beta 6)

### ISSUE THREAD

**Issue by rsantosdev** [IdentityServer/IdentityServer3#1768]
As per request of @brockallen I am opening this issue to explain a bug I found when creating a new project with IdentityServer3

If you are using vNext, there is another issue, the default class to load views `FileSystemWithEmbeddedFallbackViewLoader` is using `AppDomain.CurrentDomain.BaseDirectory` to get the base path, what is giving the wrong path to search for views.

The key here is that `AppDomain.CurrentDomain.BaseDirectory` returns the path of current dnx/dnu version in your path. Not the application path

After digging into source code, I made my app work doing:

1 - On `Configure` method in `Startup.cs` class add a dependency to `IApplicationEnvironment` called `appEnv` or another thing you want.

2 - In the creation of viewOptions do the following:

```cs
var viewOptions = new DefaultViewServiceOptions
                {
                    CacheViews = false,
                    ViewLoader = new Registration<IViewLoader>(new FileSystemWithEmbeddedFallbackViewLoader(Path.Combine(appEnv.ApplicationBasePath, "customviews")))
                };
```

Change `customviews` to the name of your directory, you should be good to do

**Comment by leastprivilege** [comment]
Thanks for documenting that!
