### ISSUE TITLE
IdentityServer3, ASP.NET Identity 2 and Web Farm

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1771]
We are developing IdentityServer3 and ASP.NET Identity 2 application and planning to deploy in web farm. We also want to deploy all the existing users from development to production web farm. But I don't know whether ASP.NET Identity uses machine-key to hash password. I also dunno whether IdentityServer3 uses machine-key to generate token. Do you know what algo ASP.NET Identity 2 uses to hash password and what algo IdentityServer3 uses to generate token? How to make it work in web farm scenario?

**Comment by loctanvo** [comment]
IdentityServer uses a certificate to sign the tokens. As long as you have access to the same certificate across the servers, there shouldn't be a problme. I'm quite sure ASP.NET Identity password hashing does not involve the machine key. [Looks like standard Pbkdf2, with salt](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/PasswordHasher.cs#L112).

Before deploying to a load balanced environment, you should have a quick [read through the deployment section in the documentation](http://identityserver.github.io/Documentation/docs/advanced/deployment.html).

**Comment by abcplex** [comment]
Means I have to buy a certificate or self signed will works. Note my clients are web-apis and mobile applications.

**Comment by loctanvo** [comment]
Self signed works perfectly fine for token signing. It's only for https traffic that you need certs from trusted issuer.

**Comment by abcplex** [comment]
Thanks. Also if I sync the machinekey validation and decryption keys, will I need a certificate?

**Comment by loctanvo** [comment]
Yes. That's the mechanism used by IdentityServer to sign the tokens. The private key is used for signing, while the public key is used to verify. This way, the applications/apis themselves can retrieve the public key and do the verification themselves.

**Comment by abcplex** [comment]
Thanks very informative. Just one more question, We are developing just SSO for login and register.  How many scopes/claims do I need or I need no scopes/claims?  Should they include id_token or access_token in Authorization header during sending a request to my back-end ASP.NET web-api?

**Comment by loctanvo** [comment]
>How many scopes/claims do I need or I need no scopes/claims?

The minimum of required scopes and claims are already configured for you (due to the [OIDC standard](http://openid.net/specs/openid-connect-core-1_0.html#IDToken)). As a minimum, you need to populate the `sub` claim, which identifies the current user.

>Should they include id_token or access_token in Authorization header during sending a request to my back-end ASP.NET web-api?

access_token
