### ISSUE TITLE
Difference between `AuthenticationType` `Cookie` and `ApplicationCookie`

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#1773]
Hello,
What is the difference between `AuthenticationType` `Cookie` and `ApplicationCookie` because if i set in my idsrv3:
```C#
  app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "ApplicationCookie",
                ExpireTimeSpan = TimeSpan.FromMinutes(15),
                CookieSecure = CookieSecureOption.Never
            });
```
After authenticate with success, my server enter in infinite loop.
If i change  `AuthenticationType` to `Cookie` then work.
I have external provider work with `ApplicationCookie` and my idsrv3 server is work with `Cookie`.
I try to integrate in my idsrv3 LDAP provider... this provider: https://github.com/PCFDev/Owin.Security.ActiveDirectoryLDAP

**Comment by brockallen** [comment]
You don't configure the cookie middleware in IdSvr -- you should only be doing that in the client application.
