### ISSUE TITLE
Validation and Encryption Algorithm for token?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1774]
Developing just a SSO using IdentityServer3/Web API/ASP.NET Identity. Can you guys please let me know?

1) Which algorithm IdentityServer3 uses for validation and encryption token? Can we change? If I am using IIS means IdentityServer3 uses machinekey (validation, decryption, validationKey and decryptionKey) to sign and encrypt the access_token and id_token? Will I need any certificate in this case?

2) Will the private key of certificate is used to encrypt the key or the signing and encrypting keys are separate?

3) Why there are 2 tokens access_token and id_token? What are purpose of these?

4) If anyone have any valid access_token or id_token then he can easily decry-pt it because the certificate information is available  well-known/openid-configuration?

**Comment by loctanvo** [comment]
To answer parts of your questions:

>1) Which algorithm IdentityServer3 uses for validation and encryption token? Can we change? If I am using IIS means IdentityServer3 uses machinekey (validation, decryption, validationKey and decryptionKey) to sign and encrypt the access_token and id_token? Will I need any certificate in this case?

IdentityServer uses `RSA` as default. You probably can override this behavior by implementing [`TokenSigningService`](https://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html) and/or [`TokenService`](https://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html).

>2) Will the private key of certificate is used to encrypt the key or the signing and encrypting keys are separate?

Not sure what you mean here. They are stored in the same certificate, but only public part is exposed (unless you unintentionally leak the private key).

>3) Why there are 2 tokens access_token and id_token? What are purpose of these?

Simplified, `id_token` is part of the [OpenID Connect](http://openid.net/specs/openid-connect-core-1_0.html) standard. `access_token` is part of the [OAuth2 standard](http://openid.net/developers/specs/). You can read more about this [in the documentation](https://identityserver.github.io/Documentation/docs/overview/bigPicture.html), under the section `OpenID Connect and OAuth2 – better together`.

>4) If anyone have any valid access_token or id_token then he can easily decry-pt it because the certificate information is available well-known/openid-configuration?

Yes. (I would not use the term "decrypt", but rather "verification of the token signature")

**Comment by abcplex** [comment]
Thanks. At lot of places I found that IdentityServer3 uses machinekey. Isn't it mean that IdentityServer3 by default uses machinekey.validation for signing(default is HMAC256) and machinekey.decryption for encryption(default is AES)? So you mean RSA is used for signing or encrypting? In code I found https://github.com/IdentityServer/IdentityServer3/blob/133ca7db31d94abcca55221559a301310ab4bbe6/source/Core/Constants.cs#L54

Means the resource server will use the end point to get the public key of Identity-Server. But this means that the token should be signed and encrypted using the private key? 

Finally after getting the token will resource server contact Identity-Server for token verification or it will use the public key of certficate to validate the token (in this case will the resource server use the same public key to decry-pt the token for getting the claims?).

**Comment by abcplex** [comment]
It seems IdentityServer3 uses JWT which is just a Base64 representations of claims plus hashed signature(which uses SHA256 by default) means there is no encryption/decryption. correct?

**Comment by abcplex** [comment]
Now the question is where JWT is used?

**Comment by loctanvo** [comment]
To answer parts of your questions:

>Now the question is where JWT is used?

`id_token` and `access_token` (in the case access_token is configured to be JWT and not a reference token)

>It seems IdentityServer3 uses JWT which is just a Base64 representations of claims plus hashed signature(which uses SHA256 by default) means there is no encryption/decryption. correct?

Correct. The JWT are default signed, not encrypted. The signing ensures the integrity of the JWT, ensures that the content is not tumbled with and that it is issued by your IdServer.

>At lot of places I found that IdentityServer3 uses machinekey.

Really? Remember that encryption, signing and hashing are slightly different concepts. AFAIK, IdServer only *encrypts* cookies that it uses. Default, it'll use the Owin data protector for this. If you are hosing in IIS and you use Katana (*Owin.Host.SystemWeb*), it will use the machine key under the hood. Default Owin uses DPAPI, unless this has changed.

**Comment by abcplex** [comment]
Thanks can you check this https://github.com/IdentityServer/IdentityServer3/issues/1779 Why the claims are not part of my response?
