### ISSUE TITLE
High level overview of IdentityServer3 singing/validating token process?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1777]
I have checked the documentation. It seems lot of stuffs are very confusing for me. Can someone tell me a high level way how IdentityServer3 works? From what I understand(assuming password flow),

1) Assuming that clients send valid userName/Password then Identity-Server returns JWT? By default JWT header part include HMAC256 algo, claims include access_token(and other claims) and signature is hashed using SHA256 using the key in machine.config.

2) The client will validate the JWT and send the access_token(as Authorization: Bearer access_token) to resource server.

3) The resource server will validate access_token with identity-server using https://identityserver.github.io/Documentation/docs/endpoints/accessTokenValidation.html

Is that correct?

**Comment by abcplex** [comment]
I have found that the clients get this response {"access_token":"xxx","expires_in":3600,"token_type":"Bearer"}

**Comment by abcplex** [comment]
I have also found that access_token is just random bytes RNGCryptoServiceProvider https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/master/source/Core/CryptoRandom.cs#L41

This means that the api should call the identity-server and validate the access_token. Then how the api will get the claims from identity-server.

**Comment by abcplex** [comment]
OK. So it depend upon upon Client.AccessTokenType, if reference then the access_token will be just random RNGCryptoServiceProvider bytes (and this case api need to validate this token with Identity Server). If JWT then we need SigningCertificate and no need for verification,
https://github.com/IdentityServer/IdentityServer3/blob/133ca7db31d94abcca55221559a301310ab4bbe6/source/Core/Services/Default/DefaultTokenService.cs#L189-L201

https://github.com/IdentityServer/IdentityServer3/blob/133ca7db31d94abcca55221559a301310ab4bbe6/source/Core/Services/Default/DefaultTokenSigningService.cs#L55

**Comment by loctanvo** [comment]
>So it depend upon upon Client.AccessTokenType, if reference then the access_token will be just random RNGCryptoServiceProvider bytes (and this case api need to validate this token with Identity Server).

Correct.

>If JWT then we need SigningCertificate and no need for verification

The api needs the *public* key from the SigningCertificate to be able to verify the access token locally (no round trip to IdServer), and it's still essential that the verification is done.

In case you didn't know, there is a Gitter chat room for IdServer3. If you have quick questions, that may be a more suitable place to ask them: https://gitter.im/IdentityServer/IdentityServer3 .
