### ISSUE TITLE
Not getting claims with simple setup?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1779]
# Identity Server

           var factory = InMemoryFactory.Create(
                scopes:  Scopes.Get(),
                clients: Clients.Get(),
                users:   Users.Get());

            var options = new IdentityServerOptions
            {
                Factory = factory
            };

            app.UseIdentityServer(options);

    static class Users
    {
        public static List<InMemoryUser> Get()
        {
            return new List<InMemoryUser>
            {
                new InMemoryUser
                {
                    Username = "bob",
                    Password = "secret",
                   Claims = new Claim[]
                    {
                        new Claim("name", "Alice Smith"),
                        new Claim("given_name", "Alice"),
                        new Claim("family_name", "Smith"),
                        new Claim("email", "AliceSmith@email.com"),
                        new Claim("role", "Admin"),
                        new Claim("role", "Geek"),
                        new Claim("website", "http://alice.com")
                    },
                    Subject = "1"
                }
            };
        }
    }

    static class Scopes
    {
        public static List<Scope> Get()
        {
            return new List<Scope>
            {
                StandardScopes.OpenId,
                StandardScopes.Profile,
                StandardScopes.Email,
                StandardScopes.Roles
             };
        }
    }

    static class Clients
    {
        public static List<Client> Get()
        {
            return new List<Client>
            {
                new Client
                {
                    ClientName = "Silicon on behalf of Carbon Client",
                    ClientId = "carbon",
                    Enabled = true,
                    AccessTokenType = AccessTokenType.Reference,

                    Flow = Flows.ResourceOwner,
                    ClientSecrets = new List<ClientSecret>
                    {
                        new ClientSecret("21B5F798-BE55-42BC-8AA8-0025B903DC3B".Sha256())
                    }
                }
            };
        }
    }

# Api

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://localhost:44333",
                    RequiredScopes = new[] { "openid", "profile", "email", "roles" },
                });

    [Route("test")]
    public class TestController : ApiController
    {
        public IHttpActionResult Get()
        {
            var caller = User as ClaimsPrincipal;
            return Json(caller.Claims.ToClaimsDictionary());
        }
    }

# Client

            var client = new OAuth2Client(
                new Uri("https://localhost:44333/connect/token"),
                "carbon",
                "21B5F798-BE55-42BC-8AA8-0025B903DC3B");

            var r = client.RequestResourceOwnerPasswordAsync("bob", "secret", "openid profile email roles").Result;

            var client = new HttpClient();
            client.SetBearerToken(r.AccessToken);

            Console.WriteLine(client.GetStringAsync("http://localhost:14869/test").Result);

Getting result,

{"aud":"https://localhost:44333/resources","iss":"https://localhost:44333","nbf"
:"1440493865","exp":"1440497465","client_id":"carbon","scope":["email","openid",
"profile","roles"],"sub":"1","amr":"password","auth_time":"1440493865","idp":"id
srv"}

**Comment by loctanvo** [comment]
Which sample are you running? ResourceOwnerFlow?

**Comment by abcplex** [comment]
Yes. The simplest sample. You can try and run the above sample. I have also tried by setting TokenType JWT

**Comment by brockallen** [comment]
I think you need to read up more on the ScopeClaims collections in the Scope configuration. This controls what claims go into the access token.

**Comment by abcplex** [comment]
@brockallen I changed to,

            return new List<Scope>
            {
                StandardScopes.AllClaims
             };

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://localhost:44333",
                    RequiredScopes = new[] { "all_claims" },
                });

            return client.RequestResourceOwnerPasswordAsync("bob", "secret", "all_claims").Result;

still same result,

{"client_id":"carbon","scope":"all_claims","sub":"1","amr":"password","auth_time
":"1440506864","idp":"idsrv","iss":"https://localhost:44333","aud":"https://loca
lhost:44333/resources","exp":"1440510464","nbf":"1440506864"}


How to get all users claims?

**Comment by abcplex** [comment]
@brockallen even if I try 
                 Claims = new List<ScopeClaim>
                    {                        
                        new ScopeClaim("name", alwaysInclude: true),
                        new ScopeClaim("given_name", alwaysInclude: true),
                        new ScopeClaim("family_name", alwaysInclude: true),
                        new ScopeClaim("email", alwaysInclude: true),
                        new ScopeClaim("role", alwaysInclude: true),
                        new ScopeClaim("website", alwaysInclude: true),
                    }

nothing work

**Comment by brockallen** [comment]
And that's a resource scope that the client app is requesting?

**Comment by abcplex** [comment]
Yes. To be clear I am new to Identity Server. I just need to get all the claims of the user who is trying to login. In above case these claims,

               Claims = new Claim[]
                {
                    new Claim("name", "Alice Smith"),
                    new Claim("given_name", "Alice"),
                    new Claim("family_name", "Smith"),
                    new Claim("email", "AliceSmith@email.com"),
                    new Claim("role", "Admin"),
                    new Claim("role", "Geek"),
                    new Claim("website", "http://alice.com")
                },

**Comment by brockallen** [comment]
I'd suggest starting with the samples and then try to copy over the parts of the sample that match what you need in your app. It's very hard to remote debug your app with your config.

**Comment by abcplex** [comment]
Which sample? This is your sample. Not mine. I just added some tweaks.

**Comment by brockallen** [comment]
Given the code you pasted above what's happening is that you're asking for an access token for the various OpenID Connect scopes. Your resource owner password client is getting back an access token which can then be used at the user profile endpoint. That's where you'll find your claims.

**Comment by abcplex** [comment]
Is it not possible to get claims at the same time?

**Comment by brockallen** [comment]
You can -- you just need to configure the scopes the right way and request them.

**Comment by abcplex** [comment]
This is the problem? How? Any simple sample like above? What is problem with above sample? Is Password-Resource-Owner don't support getting all the user-claims?

**Comment by brockallen** [comment]
Where do you need the claims? In the client app, or in the API you're calling with the access token?

**Comment by abcplex** [comment]
In the API. Related https://github.com/IdentityServer/IdentityServer3/issues/1784

**Comment by brockallen** [comment]
Please pick one issue and comment/ask there, and close the other. Thanks.

**Comment by abcplex** [comment]
Closing this.
