### ISSUE TITLE
Bookmarking the login page

### ISSUE THREAD

**Issue by vidarkongsli** [IdentityServer/IdentityServer3#1780]
We have an application where access to all pages requires the user to be authenticated. The application is set up using ws-fed to redirect the user to IdSrv for authentication once a user tries to access the application. The problem is that our users bookmark the login page for later use. When using the bookmark in a fresh browser instance, the NoSignInCookie error message.

Any creative ideas on how to prevent this?

**Comment by loctanvo** [comment]
Maybe you could use [`InvalidSignInRedirectUrl`](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AuthenticationOptions.cs#L145) to redirect the user to a page where she can choose which application to log in to?

Related discussion: https://github.com/IdentityServer/IdentityServer3/issues/1117

**Comment by vidarkongsli** [comment]
Brilliant, @loctanvo. I owe you one :)
