### ISSUE TITLE
Redirect to login after registration with custom information

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1781]
Hi all

After registration we're redirecting the user to login. We'd like to show a custom message like "User registered" on the login form somewhere. Before moving to idserver we'd use a query string parameter and check for that in the controller. 

Any way of doing this in idserver?

**Comment by brockallen** [comment]
You can pass custom values to the view and in your custom view you can access those custom values. I think the `ExtraData` is the property on the view model (so LoginViewModel).

**Comment by henninga** [comment]
I can't find an ExtraData property anywhere in Idserver.
Forgot to mention that I'm still on 1.6.2

**Comment by brockallen** [comment]
Ah, this was added in 2.0.

**Comment by henninga** [comment]
I see. I'll try to update to 2.0 and see how it goes.

**Comment by henninga** [comment]
I can't find an ExtraData property neither in master or dev branches. I did find a Custom property on the CommonViewModel. Is this what you where thinking of?

**Comment by brockallen** [comment]
Yes, as that's the base class for the specific pages' view models.

**Comment by henninga** [comment]
From what I can see, the LoginController does not set the Custom property in the Index method
