### ISSUE TITLE
How to get id_token using OAuth2Client or HttpClient?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1782]
I am using the following code,

           var client = new OAuth2Client(
                new Uri("https://localhost:44333/connect/token"),
                "carbon",
                "21B5F798-BE55-42BC-8AA8-0025B903DC3B");

            return client.RequestResourceOwnerPasswordAsync("bob", "secret", "api").Result;

Full code here https://github.com/IdentityServer/IdentityServer3/issues/1779

**Comment by brockallen** [comment]
See the javascript or WPF sample clients.

**Comment by abcplex** [comment]
Where to see?

**Comment by abcplex** [comment]
I have appended id_token in url like https://localhost:44333/connect/token?responsetype=token id_token

https://github.com/IdentityServer/IdentityServer3.Samples/blob/0f3a25364e1dd56fd19c7ae309f98df8ba1005b9/source/Clients/JavaScriptImplicitClient/oidc.js#L396-L400

**Comment by abcplex** [comment]
Tried this but no id_token,

           var form = new FormUrlEncodedContent(new Dictionary<string, string>
            {
                { OAuth2Constants.GrantType, OAuth2Constants.Password },
                { OAuth2Constants.UserName, "bob" },
                { OAuth2Constants.Password, "secret" },
                { OAuth2Constants.Scope, "api" },
                { OAuth2Constants.ResponseType, OAuth2Constants.IdentityToken}
            });
 
            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization =   new BasicAuthenticationHeaderValue("carbon", "21B5F798-BE55-42BC-8AA8-0025B903DC3B");
            var result = client.PostAsync(new Uri("https://localhost:44333/connect/token"), form).Result;
            var r = result.Content.ReadAsStringAsync().Result;

**Comment by brockallen** [comment]
The id_token is not returned from resource owner password flow.

**Comment by abcplex** [comment]
Ok Thanks.

**Comment by abcplex** [comment]
According to this password flow support id_token https://auth0.com/docs/protocols

**Comment by abcplex** [comment]
Another example http://xacmlinfo.org/2015/03/09/openid-connect-support-with-resource-owner-password-grant-type/

**Comment by leastprivilege** [comment]
But not according to the openid connect spec.

**Comment by abcplex** [comment]
@leastprivilege Thanks but people are saying its not explicit in spec http://stackoverflow.com/questions/26838797/openid-connect-resource-owner-password-credentials and http://stackoverflow.com/questions/24047047/does-openid-connect-support-the-resource-owner-password-credentials-grant

**Comment by abcplex** [comment]
@leastprivilege OK you mean since it is not mentioned in specs that's why you guys are not supporting this scenario. Correct?

**Comment by brockallen** [comment]
Those are custom extensions to the OIDC protocol. One of our goals is to try to be as true to the spec as possible.

**Comment by abcplex** [comment]
ok Thanks @brockallen

**Comment by tiwari-abhishek** [comment]
Hey Brock, hope you remember me :-) Its commendable that you guys stick to the specs of the protocols and do not implement things because they might be cool to have. That is what makes this product awesome!!
