### ISSUE TITLE
Already registered with us page

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3#1783]
Hi 

I am looking for a best practice for a scenario where allow customer to sign in on a AlreadyRegistered page when the customer try to register use a username that already exist.

This AlreadyRegistered page is a different page from the login page that I created using custom ViewService. For a normal login process, the customer will be redirected to the login page for authentication, which works fine, but the business want to have separate UI for scenario described above, which the page will have customer's email pre-polulated as label and only has a password textbox and submit button, and allow customer to login from there as well.

I am not sure if it's possible to have multiple login pages with idsrv, or do I have to integrate both UI to one login page and have a logic in my custom view service to render different view based on whether it's a register flow or normal login flow??

Can you suggest what the best solution please?

Regards

Ming

**Comment by brockallen** [comment]
The closest thing we have is the login_hint that we support on the authorization endpoint. This will prepopulate the username field:

https://identityserver.github.io/Documentation/docs/endpoints/authorization.html

**Comment by jeremy001181** [comment]
Thanks Allen, but that's kinda of not what I ask for, do u mean that, in
the process of registration , I should redirect the browser to
authorization endpoint in case of account already exist,then it will
further redirect browser to my custom login page , so from there I can pre
populate the username field?

**Comment by brockallen** [comment]
Well, I'm nopt suggesting anything -- i was just saying that what you described made me think of our login_hint support and I was offering it to see if it helped. I guess it's not what you need.

**Comment by leastprivilege** [comment]
any update?

**Comment by jeremy001181** [comment]
I am currently looking into whether can use IssueLoginCookie API of katana project in server side to issue authenticated cookie directly on a login post back request onto AlreadyRegistered page, I can see it would work but how can I redirect customer to where they come from after login as it won't have SignInMessage cookie all that? I guess I have to implement it myself?

**Comment by brockallen** [comment]
The IssueLoginCookie should get them logged in. There's also a CreateSignInRequest if you need to trigger the login page.

**Comment by jeremy001181** [comment]
Thanks i think that will do the job, happy to close this issue :)
