### ISSUE TITLE
How to get claims with access_token?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1784]
As we know that access_token can JWT http://stackoverflow.com/questions/29710783/may-an-oauth-2-0-access-token-be-a-jwt and IdentityServer3 support this. But how to get the user claims as a part of access_token so that it will be self contained. I need to hit userinfo end-point in order to get the claims. Why I need this? Because my production application is uses ASP.NET Identity which support roles and claims. Now my clients are IOS and Android apps which contains Login screen. The Login screens contact with my Identity-Server(resource-owner is the only possible here) to get the access-token which is JWT and then send this token to my ASP.NET Web-Api application. My web-api uses,

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://localhost:44333/core",
                    RequiredScopes = new[] { "profile", "openid" },
                });

Which is great and working. But my controller is missing role and claims info. I need this information to allow different users based on claims and roles. Please help me.

**Comment by brockallen** [comment]
You're using the wrong scopes here -- your web api should define its own scope (like our samples do -- look for the "read" and "write" scopes). In that scope definition you can configure which claims you want in the access token which will then be available in your web api.

**Comment by abcplex** [comment]
@brockallen tried with a new scope called myapi. Same thing. Here is simplest sample again,

# Identity Server

            var factory = InMemoryFactory.Create(
                scopes:  Scopes.Get(),
                clients: Clients.Get(),
                users:   Users.Get());

            var options = new IdentityServerOptions
            {
                Factory = factory,
                SigningCertificate = new X509Certificate2("idsrv3test.pfx", "idsrv3test")
            };

            app.UseIdentityServer(options);

        public static List<InMemoryUser> Get()
        {
            return new List<InMemoryUser>
            {
                new InMemoryUser
                {
                    Username = "bob",
                    Password = "secret",
                    Claims = new Claim[]
                    {
                        new Claim("name", "Alice Smith"),
                        new Claim("given_name", "Alice"),
                        new Claim("family_name", "Smith"),
                        new Claim("email", "AliceSmith@email.com"),
                        new Claim("role", "Admin"),
                        new Claim("role", "Geek"),
                        new Claim("website", "http://alice.com")
                    },
                    Subject = "1"
                }
            };
        }

        public static List<Scope> Get()
        {
            return new List<Scope>
            {
                new Scope
                {
                    Name = "myapi",
                    Type = ScopeType.Identity,
                    Emphasize = true,
                    Claims = new List<ScopeClaim>
                    {                        
                        new ScopeClaim("name", alwaysInclude: true),
                        new ScopeClaim("given_name", alwaysInclude: true),
                        new ScopeClaim("family_name", alwaysInclude: true),
                        new ScopeClaim("email", alwaysInclude: true),
                        new ScopeClaim("role", alwaysInclude: true),
                        new ScopeClaim("website", alwaysInclude: true),
                    }
                }
            };
        }

        public static List<Client> Get()
        {
            return new List<Client>
            {
                new Client
                {
                    ClientName = "Silicon on behalf of Carbon Client",
                    ClientId = "carbon",
                    Enabled = true,
                    AccessTokenType = AccessTokenType.Jwt,

                    Flow = Flows.ResourceOwner,
                    ClientSecrets = new List<ClientSecret>
                    {
                        new ClientSecret("21B5F798-BE55-42BC-8AA8-0025B903DC3B".Sha256())
                    }
                }
            };
        }

#Web Api

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://localhost:44333",
                    RequiredScopes = new[] { "myapi" },
                });

    [Route("test")]
    public class TestController : ApiController
    {
        public IHttpActionResult Get()
        {
            var caller = User as ClaimsPrincipal;
            return Json(caller.Claims.ToClaimsDictionary());
        }
    }

# Client

            var client = new OAuth2Client(
                new Uri("https://localhost:44333/connect/token"),
                "carbon",
                "21B5F798-BE55-42BC-8AA8-0025B903DC3B");
            var r = client.RequestResourceOwnerPasswordAsync("bob", "secret", "myapi").Result;
            var client = new HttpClient();
            client.SetBearerToken(r.AccessToken);
            Console.WriteLine(client.GetStringAsync("http://localhost:14869/test").Result);

**Comment by brockallen** [comment]
It needs to be a resource scope.

**Comment by abcplex** [comment]
Simply superb. Thanks

**Comment by robbaman** [comment]
@brockallen Hello Brock, sorry for getting back to this closed issue, but I ran into this as well. Your answer obviously fixed the issue, but I don't really understand why. As it's security related, I like to know why things work and why not. 

Do you happen to have a blog post or something that explains why for instance the _'Role'_ claim is not available in when using the _UseIdentityServerBearerTokenAuthentication()_ extension method when only _'Identity'_ type scopes are requested?

**Comment by brockallen** [comment]
You must understand the OIDC spec and the role (no pun intended) of scopes. Then our docs will make more sense: https://identityserver.github.io/Documentation/docsv2/configuration/scopesAndClaims.html

**Comment by robbaman** [comment]
Every time I think I have a pretty solid understanding of how it works, something like this comes along and messes it up :( Thanks anyway

**Comment by brockallen** [comment]
If you realize/understand that in OIDC you normally get two tokens (id_token and access_token) then it makes sense that each can contain different claims. Our scope config allows you to indicate which type of token you're modeling, and thus what claims go inside.

**Comment by robbaman** [comment]
Ah, I understand much better now. I thought that the scopes and claims that are returned belong to the entire authentication request and that the types of tokens requested had to do more with the actions you could perform with them rather then what claims are available for the token. I had not realized that the claims themselves also belong to a specific token. Again, thanks alot for taking the time to explain, I appreciate it.

**Comment by Astimus** [comment]
@brockallen @abcplex @robbaman Sory for returning to this questing. But, pls, how to get the access_token in webapi with BearerTokenAuthentication? Claims are empty.
I need it to use in http requests (httpClient.SetBearerToken(access_token)) to other web api. Pls, help me.

**Comment by chdev77** [comment]
Perfect!  The only issue I had was that on the IdentityServer client you have to add (myapi) scope to the AllowedScopes for the client.
