### ISSUE TITLE
Resource Scope

### ISSUE THREAD

**Issue by jonathh21** [IdentityServer/IdentityServer3#1787]
What is the correct mechanism for obtaining the claimws linked to scopes marked as 'Resource'?

I can't seem to get my claims back. If I set the scope as identity then I can get them from the UserInfo end point but as soon as I change to resource they go..

I can set it so they exist in the access token but I was expecting an endpoint that accepts the access token and returns the claims? 

Any pointers?

**Comment by brockallen** [comment]
Identity scopes are for claims in the id token. Resource scopes are for claims in the access token. If your client is requesting both id token and access token, then by default the claims that would be in the id token are instead available at the user profile endpoint unless you configure the claims to always be included in the token.

**Comment by jonathh21** [comment]
Ok, so how do you retrieve resource scoped claims that are NOT set to be in the actual token?

I.e. I am using a scope as 


new Scope
{						        
Name = "MyAdmin",
DisplayName = "MyAdmin",
Type = ScopeType.Resource,
Emphasize = true, 
Claims = new List<ScopeClaim>
{
new ScopeClaim("my_userid"),
},
},

and I am linking it to the claim

new InMemoryUser{Subject = "alice", Username = "alice", Password = "alice", 
Claims = new Claim[]
{
new Claim(Constants.ClaimTypes.GivenName, "Alice"),
new Claim(Constants.ClaimTypes.FamilyName, "Smith"),
new Claim(Constants.ClaimTypes.Email, "ChangedAliceSmith@email.com"),
new Claim(Constants.ClaimTypes.PhoneNumber, "0424 445479"), 
new Claim(Constants.ClaimTypes.Address, "12 my street"),
new Claim(Constants.ClaimTypes.PreferredUserName, "My UserName"),
new Claim("my_userid", "resource scoped claim"),
}

this claim is NOT retrieved and it is NOT in the access token.

Now it feels like along side the user is the wrong place to define a resource claim, but I just don't know where else to define it!

Also, I am expecting that like with the identity token you can specify if you want the claims to appear in the actual access token OR go and retrieve them afterward.... using something like the userinfoendpoint?

**Comment by brockallen** [comment]
As long as your user service implementation returns that claim from the get profile API, then it should be in the access token. 

As for your question about "along side the user" -- can you elaborate? These claims are for the user. If you want the client app to have separate claims, then those are configurable on the client configuration.

For access tokens, you can configure it to be a reference token, which then requires a lookup back to IdentittyServer. Check the docs for more info.
