### ISSUE TITLE
SSO authentication with identity server

### ISSUE THREAD

**Issue by pessimca** [IdentityServer/IdentityServer3#1788]
Hi

I am new to Identity Server. I have a requirement where i need to use my company SSO for authentication. I planned to use Thinktecture Identity Server for Authorization. I am doing extensive search to find some help but no success hence i am logging a request. Could you please help me to find some article which helps me to implement the solution.

I appreciate your help.

thank you

**Comment by brockallen** [comment]
Did you read the docs and/or the walk thrus? https://identityserver.github.io/Documentation/docs/

**Comment by pessimca** [comment]
Thanks Allen for your response. I was reading your docs but could not find the details about SSO. I might be missing correct section. Can you please help me to find right section. 

Thanks for all your help.

**Comment by brockallen** [comment]
The entire thing is about SSO. Here are the docs/walk thrus: https://identityserver.github.io/Documentation/docsv2/
