### ISSUE TITLE
Why Web Api invoking Identity-Server to validate JWT token?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1789]
OK guys according to this, https://identityserver.github.io/Documentation/docsv2/consuming/tokenValidationMiddleware.html, 

> The middleware will first inspect the token - if it is a JWT, token validation will be done locally (using the issuer name and key material found in the discovery document). If the token is a reference token, the middleware will use the access token validation endpoint on IdentityServer.

But why my Web Api middle-ware is invoking the Identity-Server. Here are the logs, when  Identity-Server starts,

> SelfHost.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration
.IdentityServerServiceFactory]: 8/26/2015 5:57:01 AM +00:00 -- AuthorizationCode
Store not configured - falling back to InMemory
SelfHost.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration
.IdentityServerServiceFactory]: 8/26/2015 5:57:01 AM +00:00 -- TokenHandleStore
not configured - falling back to InMemory
SelfHost.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration
.IdentityServerServiceFactory]: 8/26/2015 5:57:01 AM +00:00 -- ConsentStore not
configured - falling back to InMemory
SelfHost.vshost.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration
.IdentityServerServiceFactory]: 8/26/2015 5:57:01 AM +00:00 -- RefreshTokenStore
 not configured - falling back to InMemory
Server listening at https://localhost:44333/core. Press enter to stop

When user logged in via password flow,

> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints
.TokenEndpointController]: 8/26/2015 5:57:32 AM +00:00 -- Start token request
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validatio
n.ClientValidator]: 8/26/2015 5:57:32 AM +00:00 -- Start client validation
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validatio
n.ClientValidator]: 8/26/2015 5:57:32 AM +00:00 -- Client validation success
 {
  "ClientId": "roclient",
  "ClientName": "Resource Owner Flow Client",
  "ClientCredentialType": "Basic"
}
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validatio
n.TokenRequestValidator]: 8/26/2015 5:57:32 AM +00:00 -- Start token request val
idation
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validatio
n.TokenRequestValidator]: 8/26/2015 5:57:32 AM +00:00 -- Start password token re
quest validation
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validatio
n.TokenRequestValidator]: 8/26/2015 5:57:33 AM +00:00 -- Password token request
validation success.
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validatio
n.TokenRequestValidator]: 8/26/2015 5:57:33 AM +00:00 -- Token request validatio
n success
 {
  "ClientId": "roclient",
  "ClientName": "Resource Owner Flow Client",
  "GrantType": "password",
  "Scopes": "myapi",
  "UserName": "a1",
  "AuthenticationContextReferenceClasses": []
}
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseH
andling.TokenResponseGenerator]: 8/26/2015 5:57:33 AM +00:00 -- Creating token r
esponse
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseH
andling.TokenResponseGenerator]: 8/26/2015 5:57:33 AM +00:00 -- Processing token
 request
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]:
8/26/2015 5:57:33 AM +00:00 -- Creating access token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]:
8/26/2015 5:57:33 AM +00:00 -- Creating JWT access token
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints
.TokenEndpointController]: 8/26/2015 5:57:33 AM +00:00 -- End token request
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.T
okenResult]: 8/26/2015 5:57:33 AM +00:00 -- Returning token response.

When user send the access token to web-api,

> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints
.AccessTokenValidationController]: 8/26/2015 5:58:26 AM +00:00 -- Start access t
oken validation request
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validatio
n.TokenValidator]: 8/26/2015 5:58:26 AM +00:00 -- Start access token validation
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validatio
n.TokenValidator]: 8/26/2015 5:58:26 AM +00:00 -- Token validation success
{
  "ValidateLifetime": true,
  "AccessTokenType": "Jwt"
}
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints
.AccessTokenValidationController]: 8/26/2015 5:58:26 AM +00:00 -- End access tok
en validation request

In the last step I am not understanding why web-api invoking the Identity-Server access token validation endpoint

**Comment by davidmrichter** [comment]
As it is clearly no reference token (which would explain the api perfoming an roundtrip to the idserver) the roundtrip is not feasable unless you configured your webapi as here:

https://github.com/identityserver/IdentityServer3.AccessTokenValidation

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
    {
        Authority = "https://identity.identityserver.io",
        RequiredScopes = new[] { "api1", "api2" }
    });

I assume that this means automatic token validation.

**Comment by abcplex** [comment]
@brockallen @leastprivilege

**Comment by abcplex** [comment]
@davidmrichter I am asking why I JWT token is sending request To IdSvr

**Comment by davidmrichter** [comment]
Because normally one configures api instance with UseIdentityServerBearerTokenAuthentication, which calls
else if (options.ValidationMode == ValidationMode.ValidationEndpoint)
IdentityServerAccessTokenValidationAppBuilderExtensions.UseValidationEndpoint(app, options);
per default ValidationMode = ValidationMode.ValidationEndpoint; 

So I presume thats why your api call calls back to Idserver to validate the jwttoken

I suggest you change your api config to sthg like:
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions { Authority = Configs.IdentityAccessServiceURI, RequiredScopes = new[] { "WebApp" }, ValidationMode = ValidationMode.Local});

Then I expect no request going back to IdServer.

**Comment by abcplex** [comment]
OK Thanks means I need to set ValidationMode = ValidationMode.Local otherwise it will not work. Seems the issue is with the documentation
