### ISSUE TITLE
MissingMethod exception when login from Google, MR 8.4

### ISSUE THREAD

**Issue by BroccoliProducts** [IdentityServer/IdentityServer3#1790]
I receive a MissingMethod exception for the function CreateAccount when logging in from Google, both from a client and directly through the IdSvr user console.

Here is the log:

iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 26/08/2015 07:40:16 +00:00 -- external user provider: Google, provider ID: 117516957246407285146
A first chance exception of type 'System.MissingMethodException' occurred in mscorlib.dll
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 26/08/2015 07:40:17 +00:00 -- Unhandled exception
System.MissingMethodException: Method not found: 'System.__Canon BrockAllen.MembershipReboot.UserAccountService`1.CreateAccount(System.String, System.String, System.String, System.String, System.Nullable`1<System.Guid>, System.Nullable`1<System.DateTime>, System.__Canon)'.
   at Thinktecture.IdentityServer.MembershipReboot.MembershipRebootUserService`1.<ProcessNewExternalAccountAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Thinktecture.IdentityServer.MembershipReboot.MembershipRebootUserService`1.ProcessNewExternalAccountAsync(String tenant, String provider, String providerId, IEnumerable`1 claims)
   at Thinktecture.IdentityServer.MembershipReboot.MembershipRebootUserService`1.<AuthenticateExternalAsync>d__1c.MoveNext()

Here are the IdSvr and MR packages on my IdSvr:

  package id="BrockAllen.MembershipReboot" version="8.4.0" targetFramework="net451" 
  package id="BrockAllen.MembershipReboot.Ef" version="8.0.0" targetFramework="net451" 
  package id="IdentityManager" version="1.0.0-beta5-5" targetFramework="net451" 
  package id="IdentityManager.MembershipReboot" version="1.0.0-beta5-1" targetFramework="net451"
  package id="IdentityModel" version="1.0.0" targetFramework="net451"
  package id="IdentityServer3" version="2.0.0" targetFramework="net451"
  package id="IdentityServer3.MembershipReboot" version="2.0.0" targetFramework="net451"
  package id="Thinktecture.IdentityModel.Core" version="1.4.0" targetFramework="net451"
  package id="Thinktecture.IdentityModel.Owin.ResourceAuthorization" version="1.1.0" targetFramework="net451"
  package id="Thinktecture.IdentityModel.Owin.ResourceAuthorization.Mvc" version="2.0.0" targetFramework="net451"
  package id="Thinktecture.IdentityModel.Owin.ResourceAuthorization.WebApi" version="3.0.0" targetFramework="net451"
  package id="Thinktecture.IdentityServer3" version="1.6.2" targetFramework="net451"
  package id="Thinktecture.IdentityServer3.EntityFramework" version="1.2.1" targetFramework="net451"
  package id="Thinktecture.IdentityServer3.MembershipReboot" version="1.0.0" targetFramework="net451"

**Comment by brockallen** [comment]
You need to also update your IdentityManager nugets.

**Comment by BroccoliProducts** [comment]
Thanks for the reply.

These are listed on nuget as the latest versions of IdentityManager:

IdentityManager 1.0.0-beta5-5
Updated 11th August 2015

IdentityManager.MembershipReboot 1.0.0-beta5-1
Updated 11th August 2015

**Comment by brockallen** [comment]
Yep, those are the ones.

 

-Brock

**Comment by BroccoliProducts** [comment]
Those are the versions I have been using.  I have just cleaned, rebuilt, checked the date on the binaries in my build, they are the latest.  I still get the MissingMethod exception.

**Comment by brockallen** [comment]
And you're on MR 8.4?

**Comment by BroccoliProducts** [comment]
Yes.  MR 8.4.  MR.Ef 8.0.

**Comment by brockallen** [comment]
So I made the mistake of thinking IdentityManager was related and it's not, since your exception is coming from your IdSvr user service. 

As for the problem, I now suspect it's a mismatch in the IdSvr.MR library and MR 8.4. MR 8.4 added a new overload and I think this is the issue -- the IdSvr.MR library wasn't updated to build against MR 8.4. I'd suggest rolling back to MR 8.3.

**Comment by BroccoliProducts** [comment]
Fixed.  Thanks for your help.

**Comment by vinaykasireddy** [comment]
Hi Allen,

I am getting the below error when i tried to downgrade from 8.4.0 to 8.3.0. I cannot downgrade as i need IdentityServer3.MembershipReboot which is having following dependencies:

=> IdentityServer3 (≥ 2.0.0)
=> BrockAllen.MembershipReboot (≥ 8.4.0)
=> IdentityModel (≥ 1.0.0)

![image](https://cloud.githubusercontent.com/assets/2632995/12023046/9771b388-add0-11e5-8d62-7043be057f5a.png)

Any resolution for this?
