### ISSUE TITLE
When the Sha256 is used, when Data Protector and when certificate in IdentityServer3?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1791]
I know that access_token can be RNGCryptoServiceProvider bytes or JWT signed with the SigningCertificate. Now the question is that when machinekey is used and when the Sha256 is used and when data protector is used?

**Comment by brockallen** [comment]
JWTs are signed with the signing cert. The host protection (machine key) is used for things like cookies in IdSvr. The places you see SHA256 are used to hash secrets for storage.

**Comment by abcplex** [comment]
Means all the things of machine-key(validation/decryption/validationKey/decryptionKey) is used for generating cookies and anti-forgery token?

**Comment by brockallen** [comment]
Yes.
