### ISSUE TITLE
Get access to client list

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1792]
Hi

When validating/confirming the user email, we'd like to redirect the user to the originating site. Is there a way to get access to the current client id, as well as the client list to get the redirect url?

I guess this could be done with redirect urls as a query string parameter, but does that expose me to security holes?

**Comment by brockallen** [comment]
In what context? I don't follow.

**Comment by henninga** [comment]
Lets say that the user has just registered and we send them a confirm email. That email contains an url like http://somesite.com/confirmemail?userid=2&code=3.
Since we have multiple sites, we feel that we can't just send them to a specific site when the user has confirmed their email. We'd like to redirect them to the originating site.

I can think of two possible solutions. Either include a redirect url in the query string, or a client id. Either way, we need access to the client list to either get the redirect url or verify that the url is allowed. So my question is then, how do I get the client list in my controller action?

**Comment by leastprivilege** [comment]
Don't include a url - that will make you an open redirector.

client management - incl. what you are asking for is out scope for idsrv - simply create your own DB lookup for that.

**Comment by henninga** [comment]
Wrt client management, all I was hoping for was to get access to the client store, perhaps via injection. 

I could easily get that info by my own, but why reinvent the wheel if that functionality is already available.

**Comment by leastprivilege** [comment]
The client store is implemented by you anyways - so no - it is not already available.
