### ISSUE TITLE
id_token claim is not getting generated

### ISSUE THREAD

**Issue by kishoreabhishek** [IdentityServer/IdentityServer3#1793]
I have 2 identity servers configured -identity server 1 forwards the login request to identity server 2.
When I logout I do not see id_token claim in identity server 1. 

redirectToIdentityProviderNotification.OwinContext.Authentication.User.FindFirst("id_token")

The above line errors out because there is no id_token claim getting returned. How can I solve this

I implemented the following code in identityserver 1

public IdentityServerOptions GetIdentityServerOptions()
        {
            var idSvrFactory = InMemoryFactory.Create(
                    users: new List<InMemoryUser> { },  // GM: No longer providing any valid users
                    clients: Clients.Get(),
                    scopes: Scopes.Get());
            var userService = new MyUserService();
            idSvrFactory.UserService = new Registration<IUserService>(resolver => userService);
            IdentityServerOptions oIdentityServerOptions = new IdentityServerOptions
            {
                SiteName = "xyz"
                SigningCertificate = Cert.Load(),
                Factory = idSvrFactory,
                CorsPolicy = CorsPolicy.AllowAll,
                AuthenticationOptions = new AuthenticationOptions
                {
                    IdentityProviders = ConfigureIdentityProviders,
                    EnableSignOutPrompt = false,
                    EnableLocalLogin = false,
                    EnablePostSignOutAutoRedirect = true,
                    SignInMessageThreshold = 0
                }
            };

            //// Disable Client Permissions Endpoint
            oIdentityServerOptions.Endpoints.EnableClientPermissionsEndpoint = false;

            return oIdentityServerOptions;
        }

 public void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var fx = GetOpenIdConnectAuthenticationOptions(signInAsType);

            app.UseOpenIdConnectAuthentication(fx);
        }        

        public OpenIdConnectAuthenticationOptions GetOpenIdConnectAuthenticationOptions(string signInAsType)
        {
            OpenIdConnectAuthenticationOptions oOpenIdConnectAuthenticationOptions = new OpenIdConnectAuthenticationOptions
            {
                ClientId = "test",
                ClientSecret = ConfigurationManager.AppSettings["abcd"],
                Authority = ConfigurationManager.AppSettings["abcde"],
                RedirectUri = ConfigurationManager.AppSettings["a"],
                SignInAsAuthenticationType = signInAsType,
                Scope = "openid profile",
                ResponseType = "code id_token token",
                AuthenticationType = "fx",
                Caption = "Fx",
                Notifications = OpenIdConnectConfig.AuthenticationNotifications
            };
            return oOpenIdConnectAuthenticationOptions;
        }

       
    }
public static class OpenIdConnectConfig
    {
        public static OpenIdConnectAuthenticationNotifications AuthenticationNotifications
        {
            get
            {
                return new OpenIdConnectAuthenticationNotifications
                {
                    AuthorizationCodeReceived = async n =>
                    {
                        var claims = new List<Claim>(from c in n.AuthenticationTicket.Identity.Claims
                                                     where c.Type != "iss" &&
                                                           c.Type != "aud" &&
                                                           c.Type != "nbf" &&
                                                           c.Type != "exp" &&
                                                           c.Type != "iat" &&
                                                           c.Type != "nonce" &&
                                                           c.Type != "c_hash" &&
                                                           c.Type != "at_hash"
                                                     select c);

                        // get access and refresh token
                        claims.Add(new Claim("id_token", n.ProtocolMessage.IdToken));

                        n.AuthenticationTicket = new AuthenticationTicket(new ClaimsIdentity(claims, n.AuthenticationTicket.Identity.AuthenticationType), n.AuthenticationTicket.Properties);
                    },
                    RedirectToIdentityProvider = RedirectionToIdentityProvider
                };
            }
        }

      public static async System.Threading.Tasks.Task RedirectionToIdentityProvider(Microsoft.Owin.Security.Notifications.RedirectToIdentityProviderNotification<Microsoft.IdentityModel.Protocols.OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> redirectToIdentityProviderNotification)
        {
            await System.Threading.Tasks.Task.Run(() =>
            {
                if (redirectToIdentityProviderNotification.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnectRequestType.LogoutRequest)
                {
                    var idTokenHint = redirectToIdentityProviderNotification.OwinContext.Authentication.User.FindFirst("id_token").Value;
                    redirectToIdentityProviderNotification.ProtocolMessage.IdTokenHint = idTokenHint;
                }
            });
        }
    }

**Comment by leastprivilege** [comment]
resolved?

**Comment by kishoreabhishek** [comment]
Not yet

**Comment by leastprivilege** [comment]
Posting tons of code is not really useful.

You should check the id_token claim existence first - if it is not there, you need to debug your code.

I don't think this is an issue with identity server - or am I wrong?
