### ISSUE TITLE
jwt accesstoken lifetime vs exp claim inside the token

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1795]
I have an accesstoken issued for OpenIdConnect. In the jwt parser I can see that as claim:
exp 27.08.2015 17:35:19 
 nbf 27.08.2015 16:35:19 

I presumed that this is the lifetime of the Accesstoken in our case an jwt. 
But this is obviously not the case, since if the client sets UseTokenLifetime = true in UseOpenIdConnectAuthentication then the lifetime of the genereated AuthenticationTicket is set 5 Minutes with allowrefresh = false.

Could someone hint me as to there my presumptions are wrong?

**Comment by brockallen** [comment]
The cookie duration from that setting is driven off of the id_token, not the access token.

**Comment by davidmrichter** [comment]
How can on configure the id_token lifetime?

**Comment by brockallen** [comment]
I tend to not use UseTokenLifetime=false, then choose in my app what's appropriate for cookie lifetime.

**Comment by davidmrichter** [comment]
you mean id_token lifetime not cookielifetime, since you tend not to use  UseTokenLifetime=false, right?

**Comment by brockallen** [comment]
The id token lifetime is really just meant to give it enough time to get passed from IdSvr to the client app. Once the client app knows who the user it, it makes the decision of how long the user should be logged in. So this means each client app I decide how long I want the cookie to be good for and if I want sliding sessions.
