### ISSUE TITLE
Multi-tenant Azure AD as external provider via OpenID-Connect

### ISSUE THREAD

**Issue by dahlsailrunner** [IdentityServer/IdentityServer3#1796]
Hi guys --

I'm trying to get Azure AD set up as an external provider using an OpenID Connect setup, and I think I'm almost there.  I keep getting an error "no signin id passed" in the logs, and a callback endpoint hit with "There is an error determining which application..." in the user interface.  

Running a network trace I can see the GET coming back to connect/authorize, and a jwt signinmessage token in the cookie.  I'm expecting to have my "AuthenticateExternalAsync" method called (I have a custom user provider), but it never gets there.

I have tried the app with and without the "CallbackPath" set below, and have also tried with and without this line in the Configuration method:
    app.UseCookieAuthentication(new CookieAuthenticationOptions());

Maybe I'm just missing some real option values on the UseCookieAuth call?  Any insight or guidance would be most appreciated.

Here is my config for the external provider:
    var aad = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "AzureAD",
                Caption = "Organizational Account",
                SignInAsAuthenticationType = signInAsType,
                ClientId = ""myclientid",
                Authority = "https://login.microsoftonline.com/common/",
                //CallbackPath = new PathString("/identity/connect/authorize"),
                TokenValidationParameters = new TokenValidationParameters
                {                    
                    ValidateIssuer = false
                },                                
            };
            app.UseOpenIdConnectAuthentication(aad);

Thanks - 
Erik

**Comment by brockallen** [comment]
You need to figure out why the signin cookie is getting lost across the redirects.

**Comment by dahlsailrunner** [comment]
I'm probably misunderstanding what is needed somewhere.  I've attached the http traffic and you can see a "SignInState" response cookie coming from AAD.  Then you can see the "SignInMessage" request cookie in both the connect/authorize GET and then the callback GET.

What am I missing?

![missingcookie](https://cloud.githubusercontent.com/assets/8389867/9532300/6e4c4d30-4cd0-11e5-962f-8849ea2a8d2b.PNG)

**Comment by IsdYann** [comment]
I had to use this for TokenValidationParameters to enable AzureAD auth

                TokenValidationParameters = new TokenValidationParameters
                {
                    AuthenticationType = Constants.ExternalAuthenticationType,

                    // Without this, I get IDX10205
                    ValidateIssuer = false,
                },

hth

**Comment by dahlsailrunner** [comment]
Turns out that AuthenticationType = Constants.ExternalAuthenticationType was indeed what I was missing!!  Thanks a LOT IsdYann!
