### ISSUE TITLE
Can't get "simplest OAuth" example to work

### ISSUE THREAD

**Issue by comdw** [IdentityServer/IdentityServer3#1798]
I've created the example exactly as specified here:
https://identityserver.github.io/Documentation/docs/overview/simplestOAuth.html

My client gets the token just fine and sets it as the bearer but the WebAPI still responds with unauthorized 401 every time.

Could there be some code missing from that page?  Is there some logging I can turn on in the webapi project?

**Comment by brockallen** [comment]
In the web api project, on the 401 response check the response headers for any more info.

**Comment by comdw** [comment]
I can't hit any debug on the web api project side as it doesn't hit my controller.  Looking at the response headers on the client side, I just have this:

```
X-SourceFiles: =?UTF-8?B?YzpcVXNlcnNcbWFydGluLndha2xleVxkb2N1bWVudHNcdmlzdWFsIHN0dWRpbyAyMDEzXFByb2plY3RzXG9wZW5pZFx3ZWJhcHBcdGVzdA==?=
Date: Tue, 01 Sep 2015 09:06:42 GMT
Server: Microsoft-IIS/8.0
WWW-Authenticate: Bearer
X-Powered-By: ASP.NET
```

**Comment by comdw** [comment]
OK, seems this was an SSL problem.  This is what finally solved it for me:
https://github.com/IdentityServer/IdentityServer3.Samples/issues/166#issuecomment-136597631

Perhaps you could add a note about SSL to the walkthrough, mentioning the minimum setup required for the example to work...

**Comment by leastprivilege** [comment]
feel free to amend the documentation
