### ISSUE TITLE
Dynamically Add Claims to User During Authentication

### ISSUE THREAD

**Issue by iltera** [IdentityServer/IdentityServer3#1799]
I want to add some claims ON THE FLY, without writing any records in the database. I am using implicit flow on AngularJS client app and WebApi with BearerTokenAuthentication setup.

My implementation of GetProfileDataAsync is like this:

    public override Task GetProfileDataAsync(ProfileDataRequestContext context)
    {
        var user = db.Users.SingleOrDefault(x => x.UserName == context.Subject.Identity.Name);

        if (user != null)
        {
            var identity = new ClaimsIdentity();
            identity.AddClaims(new[]
            {
                new Claim("preferred_username", user.UserName),
                new Claim("email", user.Email)
            });

            if (context.RequestedClaimTypes != null)
            {
                var result = identity.Claims.Where(x => context.RequestedClaimTypes.Contains(x.Type));
                return Task.FromResult(result);
            }

            return Task.FromResult(identity.Claims);
        }

        return Task.FromResult<IEnumerable<Claim>>(null);
    }

I have

IncludeAllClaimsForUser = true (in Scopes table)
AlwaysIncludeInIdToken = true (for every scope claim for these scopes in ScopeClaims table)
AlwaysSendClientClaims = true (in Clients table)

With this setup I no longer get any of these requested values in OIDCTokenManager's profile attribute. When I comment this method, I have them all.

What is wrong with my approach?

**Comment by benjaminadrom** [comment]
before "return Task" 
add claims to "context.IssuedClaims" like this:
context.IssuedClaims = identity.Claims;
