### ISSUE TITLE
Swagger integration for IdentityServer API

### ISSUE THREAD

**Issue by m3kan1cal** [IdentityServer/IdentityServer3#1801]
My team has successfully developed an OAuth API based on IdentityServer3. Thank you for the awesome solution. We are now looking to generate a UI for our API documentation using the built-in XML documentation tool in Visual Studio 2015 and Swagger (Swashbuckle). 

Any ideas on where to start? We're not seeing immediately where we can create XML documentation for the endpoints exposed by IdentityServer3.

Cheers

**Comment by leastprivilege** [comment]
the docs are here (under endpoints).

https://identityserver.github.io/Documentation/docsv2/
