### ISSUE TITLE
AuthenticateResult w redirect to another application

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1802]
I'm trying to create an application for handling password change, reset and multi-factor auth, separated out from core IDP service (v.2). However, once the login has gone through and AuthenticateResult with redirect set on the context in PostAuthenticateAsync, the application doesn't see the cookies set by the IDP. Is this possible to achieve so I can separate the concerns this way?

Thanks

**Comment by brockallen** [comment]
You need to redirect back into the path for IdSvr since we set the cookie path and you need to be in IdSvr's pipeline for the cookie to be processed. See the HRD and custom user service samples.

**Comment by snothub** [comment]
Thanks, I've looked at those samples. I'm trying to have IDP sit at /identity and have a separate app under /identity/user where password stuff is handled. I find it messy to have to mix those things, specially given that the password stuff will be handled by other devs in another repository.

I've noticed the cookie path being set to /identity and resources like /identity/user/... not being able to process it. Is there a way to get this scenario to work, either by overriding the cookie path or some other way? Surely, it's a reasonable split of concerns?

**Comment by brockallen** [comment]
It's a reasonable split of concerns, yes. But it's a current technical limitation. Sorry.

**Comment by snothub** [comment]
So no way of configuring the cookie path to desired app then re-creating with IdSrv path when done? I mean, the app/UI for partial login services really doesn't belong in the core service to begin with, on top of the fact that in many cases (like mine) those would be developed in totally different context (repository, technology etc). This really sounds like a must-have improvement feature to me.

**Comment by brockallen** [comment]
It can be done, but requires some internal know-how of how cookie protection is done in katana.

**Comment by snothub** [comment]
I'm thinking an overload on AuthenticateResult where cookie path can be specified to the app taking over partial login process. Then that app accesses the cookie, deletes it and when done, creates the cookie with the correct /idsrv path (which it will know about anyway).

Is that something you guys could create support for?

**Comment by brockallen** [comment]
It's more complicated than that -- on the next request form the user you need middleware to process the cookie, and that middleware is part of IdSvr -- this is why the path issue exists in the first place. You'd need middleware to run at that other path with all the same protection config that IdSvr is setting up.

**Comment by snothub** [comment]
Ok, thanks for the details. I still hope this can be overcome somehow soon, so these things can be separated.
