### ISSUE TITLE
Refresh claims

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#1803]
Hi

When changing the user profile/claims, the current session does not change with it.

ie, if I change the name of user, it is changed in the database, but not in the claims that RP has. How can I trigger a refresh of the user claims without forcing the user to relogin?

**Comment by leastprivilege** [comment]
You need to get a new token - or re-request the claims from the user info endpoint.

**Comment by henninga** [comment]
I thought of calling the user info endpoint, but I'm unsure how I can create a new authentication ticket without triggering the notifications api.

**Comment by leastprivilege** [comment]
You don't need to do that - use the access token to call the userinfo endpoint and create a new cookie based on the outcome.

**Comment by henninga** [comment]
Is there any helper methods to create a new cookie?

**Comment by leastprivilege** [comment]
Standard Katana API on IAuthenticationManager (off the OwinContext).

**Comment by henninga** [comment]
Thanks. I've made something that feels dirty using AuthenticationManager.AuthenticateAsync and AuthenticationManager.SignIn where I replace the tokens I need to be updated.

**Comment by leastprivilege** [comment]
Why AuthenticateAsync - simply create a new ClaimsIdentity and set the cookie using SignIn..?!

**Comment by henninga** [comment]
I thought I had to set the AuthenticationProperties as well and that was the only way I cound find that instance.

Buuut I never testet it without AutenticateAsync. Seems to work without it. 

Thanks again :)
