### ISSUE TITLE
Using Office365 Federated authentication, IdentityServer and Azure Active Directory

### ISSUE THREAD

**Issue by IsdYann** [IdentityServer/IdentityServer3#1805]
It's not really a question about IdentityServer, more on Office365 and Azure but maybe someone already succeeded in doing this with IdentyServer.
After some weeks experimenting IdentityServer (which is really great), I've been able to use IdentityServer between a MVC app and WAAD using OIDC, between MVC app and ADFS using WS-Fed, between Office365 and ADFS using WS-Fed too but not between Office365 and WAAD.
If Office365 uses Cloud Identity, I would like to use Federated authentication to route to IdentyServer and route back to Azure AD for authentication. When I do that, it's correctly routed to IdentityServer which correctly route the auth to WAAD but there, it's not possible to authenticate as Azure always redirect to IdentityServer bacause of federated auth. Is it possible using a specific endpoint or a different configuration to avoid this last redirection so that WAAD really authenticates the user using Cloud identity before sending back the auth token to IdentyServer?

Thanks!

**Comment by leastprivilege** [comment]
I don't follow - but have you resolved it?

**Comment by leastprivilege** [comment]
closing - feel free to open a new issue when needed.

**Comment by IsdYann** [comment]
No solution yet. I'll update the page if I get one someday...
