### ISSUE TITLE
Is anything setting the current culture?

### ISSUE THREAD

**Issue by ayoung** [IdentityServer/IdentityServer3#1806]
For the LocalizationService, is there anything setting the current culture? So, let's say, if a browser is set to German, it would be able to localize to that language?

**Comment by ghedin** [comment]
Hi Andrew,

Check this out: https://github.com/johnkors/IdentityServer3.Contrib.Localization/pull/40 <https://github.com/johnkors/IdentityServer3.Contrib.Localization/pull/40>

It might be what you are looking for.

**Comment by ayoung** [comment]
Ok. I guess the answer to that would be no. :)

**Comment by brockallen** [comment]
You could always write your own middleware prior to IdSvr to do this.

**Comment by ayoung** [comment]
Thanks. I eventually did that.
