### ISSUE TITLE
Custom logic before token is issued by thinktecture server

### ISSUE THREAD

**Issue by mirza21** [IdentityServer/IdentityServer3#1807]
hi

I have my own authentication logic developed for validating user. If user is valid then I want to generate token in identity server. 

-> Where I can write this code in identity server.Please point me in right directrion.
-> secondly Token that is generated I want to save it inside db.Where i can caputre the token that is gerated and before it is sent to the end user.

**Comment by leastprivilege** [comment]
check the docs and samples - search for custom user service.
