### ISSUE TITLE
Creating Portal SSO with thincktecture openid connect

### ISSUE THREAD

**Issue by mirza21** [IdentityServer/IdentityServer3#1809]
I want to create a portal application named zomba that will issue jwt token for authenication

I have a javascript client X and web api hosted on http://www.A.com

I have a another javascript client Y and web api hosted on http://www.B.com

Now I want to implemnted SSO using openid connect protocol

what i want to achive is that My portal could open javascript client X and Y inside it in Iframe. Or portal can call webAPI hosted on www.A.com and www.B.com Directly.

what is expected is that

if i am logged into portal it should log me in all the other applications automatically.Applicaiotn should not prmpt me forlogin.

How this can be achived with openid connect.

Please help me with some ideas on this

I want to build entire system using thinktecture .My all entrpise product should be logged in wiht single login

**Comment by henrikniemann** [comment]
You need to work through some of the samples and read the docs. IdServer will help you do all you are asking, but it is important to understand the basics when doing security.

Docs: 
http://identityserver.github.io/Documentation/

Samples: 
https://github.com/IdentityServer/IdentityServer3.Samples/

Your JS clients must trust identity tokens from your IdServer. If they have a .Net backend take a look at https://www.nuget.org/packages/Microsoft.Owin.Security.OpenIdConnect/ or the Implicit flow samples.

Your WebAPIs must trust access tokens from your IdServer. Take a look at https://www.nuget.org/packages/IdentityServer3.AccessTokenValidation/

Portal must get access tokens from IdServer and attach these as bearer tokens to the authorization header of the call to WebAPI. Take a look at the Client Credentials flow.
