### ISSUE TITLE
Client is JS and server is VB : How to pass the token from client to server then validate it with the authentification Server service ?

### ISSUE THREAD

**Issue by tremblayEric** [IdentityServer/IdentityServer3#1810]
My front end is HTML5 + JS, i got my token on the login from the authentification Server service, the next step is to send it to my VB server then validate it with the authentification Server service to get info on the current user(ex: about the current privilege). I can't find any exemple about this implementation architecture. Any one have some exemple how to call (use, work with ...) the authentification Server service from a VB class (ex: with the token as parameter) ?

**Comment by leastprivilege** [comment]
We don't have samples in VB - check the C# samples instead.
