### ISSUE TITLE
Make public OWIN extension for Resolve<T>()

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#1811]

**Comment by MarkouskiM** [comment]
Hi Brock,
I have took a look into extensions class you mentioned 
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/InternalOwinExtensions.cs 
And I think if you would do the chages in ResolveDependecy<> method it will solve the problem

Thanks

**Comment by brockallen** [comment]
Ok, I'll get that change in for the next release.

**Comment by brockallen** [comment]
Done on dev.
