### ISSUE TITLE
There a demo working with ASP.NET 5?

### ISSUE THREAD

**Issue by alexsandro-xpt** [IdentityServer/IdentityServer3#1812]
ASP.NET 5 is a new version of ASP.NET and it's have a new Identity API. My question is if IdentityServer have support for Identity at https://github.com/aspnet/Identity

**Comment by leastprivilege** [comment]
read this first
http://leastprivilege.com/2015/07/22/the-state-of-security-in-asp-net-5-and-mvc-6-oauth-2-0-openid-connect-and-identityserver/

**Comment by alexsandro-xpt** [comment]
Interesting, I'm think about IdentityServer to working with multi-tenancy web applications and single accout to N web applications.

I'm studying IdentityServer for those cases.

Thanks
