### ISSUE TITLE
How to encrypt a token

### ISSUE THREAD

**Issue by carl-thomas** [IdentityServer/IdentityServer3#1813]
I am using tokens for all application types, native, web, server-server etc.  I need the tokens to be encrypted not just signed. 

How do I get the token encrypted and signed as I cannot have the token un-encrypted e.g. as a hash appended to the URL for the native clients.

Thanks

**Comment by leastprivilege** [comment]
You have full control over token creation when implementing ITokenSigningService.

**Comment by henrikniemann** [comment]
Take a look at these:
https://securityblog.redhat.com/2015/04/01/jose-json-object-signing-and-encryption/
http://tools.ietf.org/html/rfc7516 and 
http://tools.ietf.org/html/rfc7519

**Comment by carl-thomas** [comment]
Thanks for the feedback. I have implemented the ITokenSigningService and JOSE to encrypt the payload of the token.  I now want to send this to the validation endpoint to get it validated and send me back the token payload (so I don't have to decrypt it on the device but the response is still secure because of the SSL). I have implemented the ICustomTokenValidator and the ValidateIdentityTokenAsync method. This however does not get hit when validating. I get the error 'invalid_token'. I downloaded your source code and found the 'invalid_token' message in the ValidateJwtAsync method of the IdentityServer3.Core.Validation.TokenValidator class.  This obviously does not appear in the ICustomTokenValidator, so how do I override this to validate the token?

**Comment by carl-thomas** [comment]
I have noticed that the token gets sent to the IdentityServer3.Core.Validation.TokenValidator class, which when I call the validateidentitytoken endpoint it calls the ValidateIdentityTokenAsync function which then tries to validate the token using the ValidateJwtAsync method. If that is successful it then will call the ICustomTokenValidator.  However, it never reaches this call as it fails on the ValidateJwtAsync method. I believe that this is because the ValidateJwtAsync method is trying to open up the JWT but it cant as the payload is encrypted and hasn't ran through the ICustomTokenValidator.  

Looking at the TokenValidator class I can see that this does not implement an interface so I assume that this cannot be overridden and is hard coded into the project?

**Comment by leastprivilege** [comment]
This is only really useful for reference tokens. For JWTs the API receiving the token should do the validation. In case of encryption idsrv would also not have access to e.g. the private key of the API.
