### ISSUE TITLE
Issue with updating MVC Authentication sample to latest IdentityServer

### ISSUE THREAD

**Issue by punocchio1** [IdentityServer/IdentityServer3#1815]
I was running the Embedded MVC sample and it ran correctly on my system.

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MVC%20Authentication

I then updated the packages via NuGet to the latest version of IdentityServer 3 (2.0).

The only changes I made to the sample code were to switch to the in memory factory (in startup.cs) to the IdentityServerServiceFactory, remove the logging statement, and add AllowedScopes to the in memory Clients class.

Now, the sample will no longer display the login page when the user clicks on something that requires authentication. Instead it displays the error "The client application is not known or is not authorized."

I've double checked that the contents of client.cs seems correct, and that the querystring parameters being sent to the /authorize URL are correct.

We are writing a production app based on the approach in this sample, which naturally is exhibiting the same issues, but are trying to resolve it in this simple sample.

Thanks for any insight!

**Comment by brockallen** [comment]
Which sample is the "Embedded MVC sample"?

**Comment by leastprivilege** [comment]
That's the MVC walkthrough.

There are a couple of changes necessary - it is on my todo list.

**Comment by phillsta** [comment]
punocchio1 did you end up coming up with a resolution to this problem, I am experiencing the same thing.

**Comment by leastprivilege** [comment]
I have updated the code 

https://github.com/IdentityServer/IdentityServer3.Samples/tree/dev/source/MVC%20Authentication

the walkthrough text itself is a todo

**Comment by phillsta** [comment]
Perfect thank you. Will let you know if there are any issues. 

P.S. Awesome turnaround around time guys keep it up!!!
