### ISSUE TITLE
What is the difference between Thinktecture.IdentityServer3 and IdentityServer3?

### ISSUE THREAD

**Issue by madmagi** [IdentityServer/IdentityServer3#1816]
I am in the process of building out a REST back end for the server and in some cases I notice code I have pulled have a reference to nuget of IdentityServer3 and some have references to Thinktecture.IdentityServer3.

At first I thought they were the same thing, but I find that some objects are in one and not in the other or visa versa.  So I am not sure which of these I should be working off of?

I started by pulling the Thinktecture.IdentityServer3, T.IS3.Samples and the Thinktecture.EntityFramework projects.  Then using the EntityFramework as a model I have been doing the REST work.

If i search in Nuget they both point to the same uri, but if i include them in a project there are differences in the namespaces, i find some of the logging objects are not in the IdentityServer3 dll  and so on.

Thanks

**Comment by brockallen** [comment]
The first 2 items in the release notes mention this: 
https://github.com/IdentityServer/IdentityServer3/releases

**Comment by madmagi** [comment]
I accept the admonishment for not reading the release notes clearer :)

But let me at least ask this then - So I have pulled down the latest (as of 9/1/2015) of:
IdentityServer3
IdentityServer3.Samples
IdentityServer3.EntityFramework

It appears that the EF version has not been updated to the new namespaces, logger, etc is that correct?  Is there a better skeleton framework I should use as a template for replacing the default data handling?

Thanks so much for the great product.  We have been using a older modified version of the EF one in production for 6 months and it just rocks.  Currently we are building a whole Rights Management system back end that we are integrating the latest IS3 into, hence the questions and stumbling I have run into.

**Comment by brockallen** [comment]
The EF repo should be up to date as well.
