### ISSUE TITLE
External Provider IsActiveAsync

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#1818]
I have an ADFS provider registered with Identity Server and was wondering if there is any way that we can hook into the IsActiveAsync method, after successful ADFS logon, on our custom user service to go back to ADFS (or another external provider that the user is authenticated against) to check if the user has been disabled?
Thanks in advance

**Comment by leastprivilege** [comment]
yes. You need to implement the method.

**Comment by paddyhamilton** [comment]
Thanks, I assumed I would have to do that.  The bit I am missing is how you actually call out to the external provider and get the claims updated.

**Comment by leastprivilege** [comment]
This is not really the purpose of this method. It exists so you can check if the user is still active before we issue new tokens (e.g. despite an valid SSO cookie).

**Comment by paddyhamilton** [comment]
Ok, thats fine.  It was really a stop gap until we get full syncing between our app and ADFS.
Thanks again for the help.
