### ISSUE TITLE
JWT signature validation 

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1822]
Hello,

We use jwt and "parse" via http://jwt.io/.

Now verifying the signature of the tokens produces with your identityserver sample code inside jwt.io produces "invalid signature". On jwt.io I choose HS256 and entered the "secret" I defined for that client inside identityserver client config.

Still jwt.io claimes that signature is invalid.

Any hint as to what is wrong

**Comment by leastprivilege** [comment]
The secret is not used for signing the tokens. It's the x509 certificate and jwt.io has no support for that.
