### ISSUE TITLE
More CORS issues

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#1823]
We have an issue where there is an ajax request being made to an MVC controller action.  
There is a custom authorization attribute that validates if the user has been disabled, archived or session expired (from an in app configuration).  
In this case the user session is expired so httpcontext.Request.GetOwinContext().Authentication.SignOut(); is called.
The logout logic for openId is as follows:

 if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                            
                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                                n.ProtocolMessage.PostLogoutRedirectUri = GetRedirectUri(n.Request);
                            }
                        }
						
I get a Cors error on Identity Server.  It seems that it is trying to validate the endsession endpoint path as a valid path and this is not included in the Constants.RoutePaths.CorsPaths.
Is there a way round this at all or something I am missing?

**Comment by brockallen** [comment]
It sounds like your Ajax request is being redirected to IdSvr and that's where the cors failure happens.

**Comment by paddyhamilton** [comment]
That's definitely what is happening Brock. I have debugged it and that's where it fails. If a session expires I call the SignOut method. If you click on a non Ajax link when your session has expired then everything works fine, you are logged out and redirected back to Idsrv login page. If it's an Ajax link that's where I get the issue. It calls the end session endpoint and that's where it fails as it tries to validate the endsession endpoint path which obviously isn't in the CorsPaths.  Is there something obvious you can think of that I am not doing or doing wrong?

**Comment by brockallen** [comment]
Yes, you're using cookies to authenticate your ajax calls. You should instead be using bearer tokens.

**Comment by paddyhamilton** [comment]
That makes sense.  I am using OpenIdConnect with MVC and have it set up using cookies authentication.  What I want then is if this is an ajax request use bearer authentication?  I know this isnt specifically an Idsrv issue, but is this possible to do?  If not will I have to call the endpoint directly through my own code?
Everything is done through and MVC app so we dont have a separate API app that I could configure separately. 
These questions are probably down to my lack of understanding rather than Idsrv, so apologies.

**Comment by brockallen** [comment]
As as part of your authentication request to IdSvr, in addition to getting an id token for authentication, you can also ask for an access token for making Web API calls-- check some of our samples.

**Comment by paddyhamilton** [comment]
We aren't making any API calls as such so we don't really use access tokens.  Its really only authentication and claims transformation.  Maybe if I explain it will make more sense.
When a user logs in and they are idle for lets say 5 mins and they try and navigate to another page (non ajax call) then the code checks their expiry time claim against the current time and if they have been idle for lets say 5 mins (session time-out is set by the tenant in our app) then we call the httpcontext.Request.GetOwinContext().Authentication.SignOut(); Everything works as expected.
If however the user is inactive for the same time and clicks on an ajax link (MVC razor view specifies the ajax helper link) we use the same code and try and log the user out with the same httpcontext.Request.GetOwinContext().Authentication.SignOut(); then we get the Cors error as the user has triggered and ajax request.

**Comment by brockallen** [comment]
Aren't you doing Ajax calls? Those are APIs.

**Comment by paddyhamilton** [comment]
Yes, I am.
Ill have a look at the docs and see if I can find something that will help.
Cheers
