### ISSUE TITLE
one idserver, two clients, to only one user should log

### ISSUE THREAD

**Issue by usernameAlreadyTakenByMe** [IdentityServer/IdentityServer3#1825]
I have a question. I have an implementation of identity server with custom IUserService and when im logging in im checking in db if the user has the rights to log into specific client application and thats not a problem. The thing is when im trying to log into another application after login into previous app the identity server is not redirecting me to login page and to my own userservice, so im automatically logged in an app without checking if i have rights to it. So hte question is how can i implement such restriction?

**Comment by brockallen** [comment]
Look into the custom request validator.

**Comment by usernameAlreadyTakenByMe** [comment]
thanks so i understand that i should write my own method here which will check if the user which is requesting authentication has the rights to the system here and if not pass isError = true but the last thing i want to know is:
how can I get to the user id or login or any of such information from here or token and its claims?

**Comment by brockallen** [comment]
The current user is a param, IIRC

**Comment by leastprivilege** [comment]
does that work for you?
