### ISSUE TITLE
Redirect Url on logout

### ISSUE THREAD

**Issue by zebamba** [IdentityServer/IdentityServer3#1827]
I created a Custom Service and Custom View Service when loggin out with redirect Url it does not redirect
because the class CommonViewModel Thinktecture.IdentityServer3.dll, v1.6.0.0 does not containt the
property redirectUrl.

On app.js the variable model.redirectUrl is undefined as it is not loaded on the model.

Any thoughts?

**Comment by zebamba** [comment]
I added another setting on configuration, now it executing Task LoggedOut.

This task uses LoggedOutViewModel that contains RedirectUrl on the Class LoggedOutViewModel.

But the model on render method utilizes CommonViewModel model  that does not contains the RedirectUrl property.

I got this from your example.

Any thoughts how to fix this?

**Comment by henninga** [comment]
Not sure if this solves your problem,
http://www.aaron-powell.com/posts/2015-01-11-auto-redirect-when-logging-out.html

I'm looking for a similar solution. Want to specify the sign out redirect url, but when I do, I don't get a redirect link even.

**Comment by zebamba** [comment]
On the documentation https://identityserver.github.io/Documentation/docs/endpoints/endSession.html
says that the post_logout_redirect_uri paratemeter is the redict Url.

On the sample code https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomViewService
on the app.js this code does not redirect because the model does not load the redirect Url

        if (model.autoRedirect && model.redirectUrl) {
            if (model.autoRedirectDelay < 0) {
                model.autoRedirectDelay = 0;
            }
            window.setTimeout(function () {
                window.location = model.redirectUrl;
            }, model.autoRedirectDelay * 1000);
        }

The variable model.redirectUrl is undefined.

it seems that something on is passing that value as null and I notice that the client is also null.

Looking at:

Core/Endpoints/Connect/EndSessionController.cs and Core/Validation/EndSessionRequestValidator.cs.
Core/Results/LoggedOutActionResult.cs

Could be here.

Core/Results/LoggedOutActionResult.cs

namespace IdentityServer3.Core.Results
{
    internal class LoggedOutActionResult : HtmlStreamActionResult
    {
        public LoggedOutActionResult(IViewService viewSvc, LoggedOutViewModel model, SignOutMessage message)
            : base(async () => await viewSvc.LoggedOut(model, message))
        {
            if (viewSvc == null) throw new ArgumentNullException("viewSvc");
            if (model == null) throw new ArgumentNullException("model");
        }
    }
}

I am going to load the source project into a separated solution for troubleshooting.

**Comment by brockallen** [comment]
We only allow post logout redirects if the client also passes the id_token_hint (as per the recommendation in the OIDC session spec). Perhaps that's the issue?

**Comment by zebamba** [comment]
I am providing parameter id_token_hint on the URL as per documentation.

The model has client and redirect url null when render is called.

**Comment by brockallen** [comment]
So yea, you might have to debug up the chain to find out why they're null in the view model in your custom C# code.

**Comment by zebamba** [comment]
That is what I am going to do.

**Comment by zebamba** [comment]
I see that version 2.x has changed the name.

I may need to update and test with the new version to see if the redirect url is not null.

**Comment by leastprivilege** [comment]
any update?

**Comment by zebamba** [comment]
The Thinktecture.IdentityServer3 v1.6.2 it pass the SignOutMessage class as null values.

I tried to debug attaching the code source to a process and also tried to debug with the pdb but I could not debug the dll.

We are going to upgrade from Thinktecture.IdentityServer3 (v1.6.2) to IdentityServer3 (2.0.1).

We have to do it on next sprint as we need to plan it.

**Comment by leastprivilege** [comment]
open a new issue when needed. thanks
