### ISSUE TITLE
Multiple replyUrls for relyingParties using wsfed

### ISSUE THREAD

**Issue by david-ernstsson-stratsys** [IdentityServer/IdentityServer3#1828]
Hey,

A simple feature request for the wsfed extension:
- Support multiple reply urls for a given relying party.

From my understanding this is a quite standard implementation for idps although i understand it may not be a priority to support.

Any thoughts?

**Comment by leastprivilege** [comment]
wrong repo.

Popular IdPs like ADFS also support a single reply URL only - that said - it could be done just isn't very high on our priority list. 

Open an issue in the ws-fed repo explaining the use case.

thanks
