### ISSUE TITLE
Question on Cross site Authorization

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1829]
if we use third party Authorization Server to Authorize the user,  Do we just need to add Bearer Token handlers to RestAPI to validate the AccessTokens using third party server 

'or' 

Do we need on-premises Authorization Server to ReAuthorize user coming from third party server and do the claims transformation?.   or in other words does the AccessToken gets regenerated at the destination?.

**Comment by brockallen** [comment]
Normally APIs aren't designed to trust 3rd party authorization servers. For example, my Web APIs should not trust google's authorization servers for tokens. Also, how would google know to issue tokens for my web apis. So normally when you build an API you use your own authorization server (like IdentityServer).

Or perhaps I'm not understanding your question?

**Comment by skatukojwala** [comment]
Sure! I agree.  

We already customized your Identity server to work our authentication. Our software product goes to hospitals.  Every instance of our application uses on premises AuthSvr for authorization.  But we are working towards a scenario where one hospital needs users authenticated from different hospital almost like cross site authorization. We are also looking to Federated identity within apps hosted in the same environment which is going to be our next challenge.   BTW: Do you guys have any plans to support SAML in the future. We are doing Micro Semi architecture with lot of plug and play components using WCF, I am not sure how much OAuth supports Federated Identity, where as SAML seem to support that.

**Comment by leastprivilege** [comment]
federated identity is not a feature - it's a concept.

when you want users from different trust domains to be able to access resources (aka federation) - you need to establish trust between the oidc provider/authorization servers.

In IdentityServer you can do two things to support that

* wire up the *other* identity server as an external provider (for interactive flows)
* use the OAuth2 assertion flow (for machine to machine communication)

**Comment by skatukojwala** [comment]
Thank you for the information.

**Comment by skatukojwala** [comment]
BTW: I have some C++ implementation of OAuth Client which uses Casablanca.  I thinking of creating a C++ sample to use with
