### ISSUE TITLE
IdentityServer3 + integrated windows authentication

### ISSUE THREAD

**Issue by cellvda** [IdentityServer/IdentityServer3#1830]
I'm very new to IdentityServer3. I'm thinking of using IdentityServer3 as STS token provider to access web api.

I have an MVC application with Integrated windows authentication to call web api (in same windows domain) through token provided by IdentityServer3. I think I will have to use https://github.com/IdentityServer/WindowsAuthentication . I will be invoking web api from server (MVC application controllers) but windows login user is involved. Which flow should I use, Resource owner password flow or client credentials flow? As it is windows authentication, I believe I can only use Client Credential flow because I wont be having user password. Is my approach correct?

**Comment by leastprivilege** [comment]
is still an issue? i am not sure i follow.
