### ISSUE TITLE
The client application is not known or is not authorized.

### ISSUE THREAD

**Issue by phillsta** [IdentityServer/IdentityServer3#1832]
Hi,

I'm new to IdentityServer3 and from what I've seen it is fantastic, but for some reason i cannot get Embedded MVC to work and I've tried everything. I've copied the sample extactly and it works there but when i use identityserverv3 2.0 it breaks. 

I've set it up on IIS 8 through Visual Studio and no luck (i've also tried using iisexpress with no luck)
PLEASE HELP!!!!

Below is modified clients code and Startup code

 var client = new Client
                {
                    Enabled = true,
                    ClientName = "Autho",
                    ClientId = "mvc",
                    Flow = Flows.Implicit,

                    RedirectUris = new List<string>
                    {
                        "https://localhost/Autho"
                    }

                };

app.Map("/core", core =>
            {
                core.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Autho Ids3",
                    SigningCertificate = Certificate.Get(),
                    Factory = Factory.Configure("Autho"),
                    RequireSsl = false,
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        IdentityProviders = ConfigureAdditionalIdentityProviders,
                    },
                    LoggingOptions = new LoggingOptions
                    {
                        EnableKatanaLogging = true
                    },
                    EventsOptions = new EventsOptions
                    {
                        RaiseFailureEvents = true,
                        RaiseInformationEvents = true,
                        RaiseSuccessEvents = true,
                        RaiseErrorEvents = true
                    }
                    //CspOptions = new CspOptions
                    //{
                    //    Enabled = true,
                    //    ScriptSrc = "ajax.googleapis.com use.typekit.net",
                    //    StyleSrc = "maxcdn.bootstrapcdn.com; font-src 'self' maxcdn.bootstrapcdn.com"
                    //},
                    //  PluginConfiguration = ConfigureWsFederation
                    //EnableWelcomePage = false,
                });

            });

app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {

                Authority = "https://localhost/Centabase.Auth/core",

                ClientId = "mvc",
                ClientSecret = "secret",
                RedirectUri = "https://localhost/autho",
                ResponseType = "id_token token",
                Scope = "openid profile",

                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false,

...

**Comment by leastprivilege** [comment]
that sample only works with 1.x right now. I need to update it to 2.x ASAP

**Comment by leastprivilege** [comment]
dup of https://github.com/IdentityServer/IdentityServer3/issues/1815#issuecomment-137678593
