### ISSUE TITLE
Autofac ctor injection error

### ISSUE THREAD

**Issue by bblunden** [IdentityServer/IdentityServer3#1833]
Hi,

We have local host working well.  Now we deployed to staging servers and are receiving the below ctor injection error.  Any ideas?

Thanks, Brent 

w3wp.exe Error: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 9/4/2015 5:19:12 AM +00:00 -- Unhandled exception
System.InvalidOperationException: An error occurred when trying to create a controller of type 'AuthorizeEndpointController'. Make sure that the controller has a parameterless public constructor. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor()' on type 'UserService'. ---> Object reference not set to an instance of an object. (See inner exception for details.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OurSite.SSO.Extensions.UserService..ctor()
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
.
.
.
.

**Comment by bblunden** [comment]
Additional info...

This is our startup.cs registration section....

            app.Map(Constants.EndPoints.SecurityToken, idsrvApp =>
            {
                //TODO: Modify to db aquired w/ server caching 
                var factory = InMemoryFactory.Create(
                    clients: Clients.Get(),
                    scopes: Scopes.Get());

                //factory.ClientStore = new Registration<IClientStore>(typeof(ClientStore));
                factory.ViewService = new Registration<IViewService>(typeof(ViewService));
                factory.UserService = new Registration<IUserService, UserService>();

**Comment by jageall** [comment]
have you tried creating an instance of your user service (
OurSite.SSO.Extensions.UserService) using the default constructor? It looks
like it is the cause of the error according to the stack trace.

**Comment by bblunden** [comment]
Everything works great on localhost, so I don't think that is it.  Its just when deployed to a staging server that it becomes a problem.  I'm wondering now if there is a version difference with Autofac between localhost machine and deployment server.

**Comment by jageall** [comment]
Autofac is internalized in identityserver, so unless you are changing
identity server versions between environments it will be the same version,
do you have the code for your userservice constructor?

**Comment by bblunden** [comment]
oh, ok.

Below is the UserService constructor - it's parameterless at this point (plan to inject scpoes and claimslater to use as part of authentication process) .   Development machines are Win7 w/ VS2013.  Deployment is to 2012 server R2

    public class UserService : IUserService
    {
        public UserService() { }

        private idsvrCore.Logging.ILog logger = LogProvider.GetCurrentClassLogger();

**Comment by bblunden** [comment]
got it to work, but had to remove logging.  it was the only other thing that would be present on instantiation...  

in code block above, I removed line below ctor (and relative logging entries) ...
this one -->  private idsvrCore.Logging.ILog logger = LogProvider.GetCurrentClassLogger();

any ideas why the logger didn't work

**Comment by jageall** [comment]
The version of liblog I am looking at, logprovider should never be null and
should not throw. But it is also internal. @leastprivilege only made it
public in dev again in #4885e62
<https://github.com/IdentityServer/IdentityServer3/commit/4885e62e6879bb0aee3c516c85cfc438bebbf1c7>


Which version of IdentityServer are you using?

**Comment by bblunden** [comment]
Thinktecture.IdentityServer3.dll
Runtime Versions v4.0.30319
Version 1.6.0.0

**Comment by leastprivilege** [comment]
resolved?

**Comment by bblunden** [comment]
Never could get it to work with above logging mechanism and latest nuget of IDS3.  We modified logging mechanism to use log4net directly.  This worked for us...

private log4net.ILog _logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
