### ISSUE TITLE
Support for multiple UserService implementations

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1834]
I'm trying to get my head around setting up IdSrv v2 for handling multiple implementations of IUserService. Our system supports various types of users, currently using separate membership providers, having access to very different areas of the system.

Is that possible and are there any samples showing that?

**Comment by leastprivilege** [comment]
IdSrv is not designed for that. The client applications can give the one user service a hint though which membership system to use - check the tenant parameter in the docs

**Comment by snothub** [comment]
I was expecting an answer along those lines. Thanks.
