### ISSUE TITLE
Is there a way to resolve IUserService with a AutofacWebRequest lifetime?

### ISSUE THREAD

**Issue by dariusdamalakas** [IdentityServer/IdentityServer3#1835]
Sorry if this was raised before, and it was several times before*, but none of them seem to have the same issue that we have.

I'll try to convey my issue as best as possible. The closest example that i've found in one of the existing issuse can be found in issue [#498 ] (https://github.com/IdentityServer/IdentityServer3/issues/498#issuecomment-63350143).  Suggestion is to inject our custom implementations by providing a custom IdentityServerServiceFactory like this:

````
var yourbuilder = new ContainerBuilder();
// ...
var yourcontainer = builder.Build();

factory.UserService = Registration.RegisterFactory<IUserService>(() =>
{
    return yourcontainer.Resolve<IUserService>();
});
````

Now the issue with this approach is that for `IUserService` implementation we use repository object, and repository objects are registered as per-request instances into `AutofacWebRequest` lifetime scope.  So even if I have access to our container, we can't resolve this, because the requested lifetime scope is only per request.

Not sure what would be the good solution here. As has been multiple times said, exposing DI is not an option.

Similar issues:
* [#819 Injecting IClientStore and MessageCookie<SigninMessage> to MVC controllers] (https://github.com/IdentityServer/IdentityServer3/issues/819)
* [#197 Question: Interfacing with the AutoFac IOC container] (https://github.com/IdentityServer/IdentityServer3/issues/197)
* [#828 Getting access to the Autofac Container] (https://github.com/IdentityServer/IdentityServer3/issues/828)
* [#498 Expose Autofac ContainerBuilder for advanced registrations] (https://github.com/IdentityServer/IdentityServer3/issues/498#issuecomment-63350143)
* [#614 Make OWIN environment resolvable via DI] (https://github.com/IdentityServer/IdentityServer3/issues/614)

**Comment by brockallen** [comment]
Our Di system allows you to configure registrations as singletons, per-use, or per-http request: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/Registration.cs#L26

Is that what you're looking for?

**Comment by dariusdamalakas** [comment]
That would require to change how we currently do component registration. We have 15+ microservices all based on a minimal template, which sets up common things for the pipeline (metrics, repositories, etc). We could make an exception and duplicate our registrations by registering components second time into your Di system, since hooking into AutoFac is not an option.

We have a session-per-request-middleware, which opens up and registers an 'NHibernate.ISession'.Is there a way how we can register extra components to `AutofacWebRequest` lifetime scope?  I see there is a sample on [DependencyInjection] ( https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/DependencyInjection/SelfHost/Startup.cs ), but that shows how to register extra components during start-up sequence, and not on a per request basis.

Here's roughly what the middleware does:
````
using (var session = OpenSession())
{
          var scope = env.GetAutofacLifetimeScope();
          builder.RegisterInstance(session).As<ISession>();
          builder.Update(scope.ComponentRegistry);
          await Next.Invoke(env);
}
````

**Comment by brockallen** [comment]
This has been discussed a few times before -- search the issues for some of those other discussions. The short answer is that since OWIN doesn't define DI, it's hard to have a shared DI system across self-contained middleware.
