### ISSUE TITLE
Refreshing identity token without redirecting the browser?

### ISSUE THREAD

**Issue by Luno89** [IdentityServer/IdentityServer3#1836]
I have been told that we need a way for a user to click a button on our pages to keep themselves logged in. Redirecting the user away from their page is apparently not a possibility.... Some of the forms we have are long and while talking to customers on the phone may take longer than our timeout period. So when the user goes to submit their form their input is lost. 

This seems like it might be a similar issue to the one in <a href='https://github.com/IdentityServer/IdentityServer3/issues/666'>issue 666</a> ( i really hope you guys made that issue that number on purpose :)) 

I know its stupid but the only thing i can come up with is opening a new window via javascript, redirecting that window session to our web app, coping the '.AspNet.Cookies' cookie into local storage of the browser, and then coping that into the main session.

The only other way may be to take the input no matter what, do the authentication in code, and submit the input based on the credentials of the resulting login?

 I dont really know what im talking about or if that will work or not but if you have any ideas that would be awesome. Or just tell me im stupid for trying and i will take it my boss :) 

Thanks for all your guys' great work. We have been using IdentityServer for about a year now and plan on going live with it in a fews months. I hope to be able to start contributing at some point :)

Thanks for your time.

**Comment by brockallen** [comment]
Or you could try an iframe.

**Comment by Luno89** [comment]
So how would that work? The same origin policy prevents cross domain cookies.. right?  Would one use the postMessage function in javascript? Do you know of a demo? ill probably try messing with it today... im googling around.. Thanks again

**Comment by brockallen** [comment]
You could make an authorization request in an iframe (the same was you make it in the main window).

**Comment by Luno89** [comment]
Would this update the main page cookie like a normal redirect would? As far as i can tell it would be a different DOM scope... or is that not right?

**Comment by brockallen** [comment]
No -- the iframe goes to your server side code, it redirects to IdSvr, IdSvr issues token back to your app, your app updates the cookie.

**Comment by brockallen** [comment]
You're still subject to the user's session timing out at IdSvr, though.

**Comment by Luno89** [comment]
The IdSvr session wouldn't get reset when the app redirects to the IdSvr i kinda thought it would or is it a different session? and only the iframe would have the app's updated cookie... i would still have to update the user's main page cookie with the iframe one correct?

**Comment by brockallen** [comment]
IdSvr has its own authentication cookie different from your app. By default it's a 10 hour fixed expiration, but you can change that in the IdSvr options.

When your app redirects to IdSvr for login, it essentially renews its own authentication cookie. I thought that's what this issue was asking for?

Your app cookie would be shared across the iframe, yes -- that's why I suggested it. A way to get a new cookie without interrupting the user's main window. But to be honest -- why do you need this from IdSvr? Your app controls its own cookie and that cookie lifetime. You just need to set it to sliding expiration in your app.

**Comment by Luno89** [comment]
Sorry i guess i didn't really know what i was asking... 

What i was trying to ask is how to update the identity server user session and i had assumed that triggering a authorize request would do that. I had also assumed that the app cookie expire time would be sync'ed with the server but that makes sense that it isn't.

So all i need to do to keep a user logged in is to use an iframe to hit an authorized controller? Do you know if i can just change the expire time of the cookie in javascript and that would be the same as going to the controller and back? and we are using slidingexpiration = true. 

Sorry about all that, and thanks again

**Comment by brockallen** [comment]
So again -- do you need the user to stay logged into your app or into IdSvr?

In short, IdSvr has CookieOptions -- I'd suggest reading the docs to see what options you have available to you: https://identityserver.github.io/Documentation/docsv2/configuration/authenticationOptions.html

**Comment by Luno89** [comment]
So after messing around for a few days i figured out, i needed to stay logged into my app and not the IdSvr. 

I had assumed somehow that the IdSvr and the app used the same cookie (ex. expiring the cookie in the app would expire the cookie on the IdSvr). I realize this doesn't make sense now and that the IdSvr sets its own expiration. 

I was able to solve the issue i was trying to solve by using an ajax call to an authorized controller which i assume just resets the session time on the server as the cookie's expiration time says session. I am just using javascript to warn the user 5 mins before the cookie expires and if they click stay logged in it does an ajax call to an authorized controller in the app. 

Thanks for all your help and patience.

**Comment by tobbie** [comment]
Hello Brock.

If I set my application authcookie to expire in say 5mins, will my users be redirected to the id server login screen after the app authcookie expires.  What's the role of the Id token in all this
