### ISSUE TITLE
Console Resource Owner Flow with Refresh Token User.Identity.Name always null

### ISSUE THREAD

**Issue by atul221282** [IdentityServer/IdentityServer3#1840]
Hi Guys,

I just want to know is this is as per design or are we missing something? I know i can get the required value from claims but User.Identity.Name is more readable.

Regards,
Atul Chaudhary

**Comment by brockallen** [comment]
Create the ClaimsIdentity and pass the name claim type ctor param.

**Comment by atul221282** [comment]
well it may be frustrating for you to see question like this but I have spent a lot of time and still got question like 

Create the ClaimsIdentity - Where? It is an console app so is this is something I need to put in in memory user class. If yes then i tried it bit didn't work.

Pass the name claim - Mean pass it when we make call as below
 return _tokenClient.RequestResourceOwnerPasswordAsync
                ("admin", "1234", "openid roles name offline_access").Result;

**Comment by leastprivilege** [comment]
The access token is not meant for the client - but for the API that receives it. You typically can set the so called NameClaimType on the validating middleware.

**Comment by brockallen** [comment]
> well it may be frustrating for you to see question like this but I have spent a lot of time and still got questions below

Sure, but some of your questions are .NET framework and Katana questions not IdentityServer questions. I understand they're related, but we're 2 people and we can't do Microsoft's support job for them.

**Comment by atul221282** [comment]
Thanks Brock and Dominick for your reply and awesome work you are doing..

**Comment by atul221282** [comment]
Hi Guys,
I apologize I was using the old nuget package as per tutorial in pluralsight by Kevin and Brock was right in the first place. Adding name claim in my CustomeruserService, after insatlling IdentityServer3 nuget, did the trick. Sorry once again for asking such a stupid question.

Just posting the code so other devs can refer to though this is avalable in ur example anyways sometime lazy developer like me can endup here

Follow the CustomUserService example and in GetProfileDataAsync method as following line
userClaims.Add(new Claim("Name", "username"));

this will get set as User.Identity.Name in api
