### ISSUE TITLE
Password Flow with Security Question/Answer?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1841]
I am using,

    <package id="IdentityServer3" version="2.0.0" targetFramework="net451" />
    <package id="IdentityServer3.AspNetIdentity" version="2.0.0" targetFramework="net451" />

In this package I have class AspNetIdentityUserService and a method AuthenticateLocalAsync for checking user is valid. But how to update this to allow security question and answer. In my AspNetUsers table I have AnswerHash and QuestionId which maps to Questions table? Any help will be appreciated.

**Comment by brockallen** [comment]
Look into a partial logins (check the docs on the user service) if you want the user to go thru a custom workflow at login time.

**Comment by abcplex** [comment]
any link?

**Comment by leastprivilege** [comment]
docs.com and samples.com? :p

**Comment by abcplex** [comment]
I have found some samples but it seems there is redirect and logic is in controller. What I need is simple, the native mobile screen shows the user login screen. The user will put UserName/Password in his mobile, the UserName/Password will be validated at Identity-Server. After successful login, the native mobile user will get question from ide-server show it user. User will put answer which is again validated at ide-server, if correct then ide-server will issue JWT token. The native mobile will then send this JWT to web-api server. Web-Api server will gave the resource access. This is working very well without security Q/A. Any example of this is appreciated.

**Comment by abcplex** [comment]
Is my scenario not supported?

**Comment by leastprivilege** [comment]
dup of https://github.com/IdentityServer/IdentityServer3/issues/1844
