### ISSUE TITLE
Configurable MaxInputParamLength

### ISSUE THREAD

**Issue by mderriey** [IdentityServer/IdentityServer3#1842]
Hi,

For some reason, I need to post a password that is longer than 100 characters.
Would it be possible to make `MaxInputParamLength` on `AuthenticationController` configurable via, let's say, `IdentityServerOptions`?

If you're OK with that, I can issue a PR.
Cheers

**Comment by brockallen** [comment]
What limit are you looking for?

**Comment by mderriey** [comment]
The number of characters that can be posted back from the login form back to `AuthenticationController`.
The class defines a public `MaxInputParamLength` but can't be modified since the class is `internal`.

**Comment by brockallen** [comment]
No, I was asking what number you'd like to have instead of 100.

**Comment by mderriey** [comment]
Ah, sorry. This is not a fixed number, but it would be around 2000 characters.

**Comment by brockallen** [comment]
Hmm, I like the idea of allowing long passwords, but 2000 -- we'll have to discuss.

**Comment by mderriey** [comment]
I edited my previous comment to give some context on why I need to post
very long values.

**Comment by mderriey** [comment]
Would you be OK with me providing a PR for this issue?
If yes, do you have any advice/guidance?

**Comment by mirecg** [comment]
Don't forget to make configurable the MaxAcrValuesLength used for acr_values length limit. See #2030.

**Comment by leastprivilege** [comment]
done on dev - give it a try

**Comment by mirecg** [comment]
Setting the desired length into InputLengthRestrictions.AcrValues worked for me.
Thank you.
