### ISSUE TITLE
PostAuthenticateLocalAsync to redirect (with signin)

### ISSUE THREAD

**Issue by vindberg** [IdentityServer/IdentityServer3#1843]
Hi guys, when a user tries to login Im showing him that he still needs to confirm his email (if he hasn't).

In my UserService im overriding PostAuthenticateLocalAsync(User user, SignInMessage message)

and redirecting with a return new AuthenticateResult("~/confirmemailsendagain", user.Id, displayName);

Is it possible to add the "signin" querystring to the redirect? Im not able to access the Request context. Or could I simply create a new signin key?

Thanks a lot.

**Comment by brockallen** [comment]
Ok, I can look into it and see if that's possible. Since PostAuthN is called for all of those different scenarios, it might not be able to. Anyway, I'll look into it.

**Comment by brockallen** [comment]
Wait, so you just want to force logging in again?

**Comment by vindberg** [comment]
Im trying to show a couple of footer navigation links: "Back to login", and "Register" that needs the signin key. It would also be perfect if I could access the ClientUri :)

**Comment by brockallen** [comment]
Ok, I'll dig into it and see what can be done.

**Comment by vindberg** [comment]
Hi, for partial logins this has been fixed with the latest release 2.x. Im now using the PartialLoginRestartUrl claim:
```
var restartUrl = partialAuthentication.Identity.Claims.Single(x => x.Type == Constants.ClaimTypes.PartialLoginRestartUrl).Value;
```
Im still not sure how to get the clientUri, but im closing this issue.
Thanks.

**Comment by brockallen** [comment]
There's an extension method for that: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

Also, for your client, you can always add the client info yourself in the claims when you issue a partial login.

**Comment by vindberg** [comment]
Thanks again Brock. For the local registration page I only have a "signin" key. Can I get the clientId from that?
For external registration im not sure what to override to add it as a partial login claim?

**Comment by brockallen** [comment]
There's another extension method to get the sign in message from the signin id.

**Comment by vindberg** [comment]
Thanks, that should work. Have a good day.
