### ISSUE TITLE
Partial Login(using Security Question/Answer) with Resource-Owner Flow?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1844]
I am checking the document and reading the source but unable to find that how to enable Security Question/Answer in IdentityServer3/ASP.NET Identity. What I need is very common in native mobile apps,

1) Native mobile app will show the Login screen(native) to the user.
2) User will enter his UserName/Password and the native app will send this request to Identity-Server(send an request to /connect/token endpoint with resource-owner flow)
3) UserName/Password is checked against ASP.NET Identity and if correct then server will send a question to mobile app.
4) Mobile app will show the question to user and user will answer it. App will send this answer to server.
5) If valid answer then the server will send a JWT to client which then client can use it get resource from Web Api servers.

**Comment by leastprivilege** [comment]
We only support custom login flows via the browser.

For resource owner you would have to come up with your own implementation - e.g. a custom API and then use the 2fa code as a custom grant.

**Comment by leastprivilege** [comment]
Sorry misread that. But in essence same answer - we only allow custom flows via browser.

Resource owner is limited as pointed out in the OAuth 2.0 spec (and is therefore not even part of OpenID Connect)
