### ISSUE TITLE
SharePoint Client Object model and IdentityServer3

### ISSUE THREAD

**Issue by marijn-us** [IdentityServer/IdentityServer3#1846]
I have a SharePoint web application connected with IdentityServer3 via ws-federation.
I'd like to use the SharePoint Client Object model in a console application.
How can I get a saml token from IdentityServer3?

**Comment by leastprivilege** [comment]
WS-Federation is not designed for that. You probably need to use OAuth for that (but I also know nothing about SharePoint - so I might be wrong).

**Comment by marijn-us** [comment]
Is it possible to use OAuth to get a saml token?
In IdentityServer2 we can use WSTrust, but this isn't possible in IdentityServer3.

**Comment by leastprivilege** [comment]
No.

— 
cheers
Dominick Baier


On 8 Sep 2015 at 13:46:05, marijn-us (notifications@github.com) wrote:

Is it possible to use OAuth to get a saml token?
In IdentityServer2 we can use WSTrust, but this isn't possible in IdentityServer3.

**Comment by brockallen** [comment]
Yes, you could use a custom grant type. You'd have to implement the custom grant validator interface in IdSvr -- check the docs.

**Comment by leastprivilege** [comment]
and this will return a SAML token?

**Comment by brockallen** [comment]
No, I guess you're right -- but the ITokenService/DefaultTokenService might be something that could also be extended.

But yea -- @marijn-us I think you need to first know what security model the Sharepoint client library requires.

**Comment by marijn-us** [comment]
In IdentityServer2 its possible to get a saml token via ws-trust: https://github.com/IdentityServer/IdentityServer2/issues/65.

I can put the saml token in a cookie and use this cookie for every request.
Is it possible to get a saml token using the custom grant validator interface?

**Comment by leastprivilege** [comment]
So in theory you can create whatever tokens you like - implement the ITokenSigningService for that (which should really be called ITokenCreationService). I never tried that - so you are pretty much on your own. 

Keep us posted.

**Comment by leastprivilege** [comment]
any update - or close?

**Comment by marijn-us** [comment]
I’ve added 2 authentication providers to the SharePoint webapplication (windows + claims/identityserver).
Because 2 authentication providers are added, I can use the SharePoint client object model with a windows user and use the claims from IdentityServer.
It’s a workaround, but its working for me.


Van: Dominick Baier [mailto:notifications@github.com]
Verzonden: woensdag 23 september 2015 9:15
Aan: IdentityServer/IdentityServer3
CC: Marijn Siero
Onderwerp: Re: [IdentityServer3] SharePoint Client Object model and IdentityServer3 (#1846)


any update - or close?
