### ISSUE TITLE
Can I change the name of the idp value in the token

### ISSUE THREAD

**Issue by carl-thomas** [IdentityServer/IdentityServer3#1847]
Currently the idp value that gets sent in the token says idsrv, I would like to change this to reflect my companies name. Can/How is this done, I cannot see where I need to change this.

**Comment by leastprivilege** [comment]
You set the idp when signing in the user in the user service

**Comment by dapug** [comment]
In my user service, I tried setting the value of SignInMessage.IdP = "awesomeIdsvr" by overriding AuthenticateLocalAsync and PostAuthenticateLocalAsync, but the tokens still get set to "idsvr".  What's the trick?

**Comment by leastprivilege** [comment]
either set the idp in PreAuthenticate or pass the idp via the authz request.

**Comment by dapug** [comment]
Tried PreAuthenticate.  Throws  "There was an unexpected error".

    public override System.Threading.Tasks.Task PreAuthenticateAsync(PreAuthenticationContext context)
    {
        if (context.SignInMessage.IdP == null)
            context.SignInMessage.IdP = "Awesome";

        return base.PreAuthenticateAsync(context);
    }

**Comment by leastprivilege** [comment]
and you have an external provider called "awesome" registered in startup???

**Comment by leastprivilege** [comment]
hold on - did you switch issues?

what do you want to do now? trigger an external provider or change the value of the idp claim??=

**Comment by dapug** [comment]
actually, I am simply trying to start up the identity server as "awesome" rather than "idsvr", such that this shows up in the idp param of the id_token.  My first thought was **IdentityServerOptions** would be the place for such, just like with SiteName, but I'm missing something obvious I think.

**Comment by leastprivilege** [comment]
ah - then you need to set the identity provider on the authenticateresult that you return from AuthenticateXX in the UserService

**Comment by dapug** [comment]
I found AuthenticateResult was null, except on PostAuthenticateAsync...  so this works great, thanks!  
The following should help others with the same question.

        public override System.Threading.Tasks.Task PostAuthenticateAsync(PostAuthenticationContext context)
        {
            if (context.AuthenticateResult.User.FindFirst("idp").Value == "idsrv")
            {
                var identity = context.AuthenticateResult.User.Identity as ClaimsIdentity;
                var claim = context.AuthenticateResult.User.Claims.Where(x => x.Type == "idp").Single();
                identity.RemoveClaim(claim);

                identity.AddClaim(new Claim("idp", "awesome"));
            }

            return base.PostAuthenticateAsync(context);
        }
