### ISSUE TITLE
IdentityServer SharePoint SAML token

### ISSUE THREAD

**Issue by dvolvenl** [IdentityServer/IdentityServer3#1849]
We have a single sign on portal that uses IdentityServer and a SharePoint client application that uses the OAuth flow to retrieve a token (grant_type=authorization_code) from the token endpoint. We have received the request to provide a SAML token instead since a SAML token needs to be provided for each subsequent SharePoint request. Is this possible in IdentityServer or does that require some sort of custom code (e.g. custom grant type?) and if so, where to start? Or are SAML tokens only available through the WsFed/ADFS side of IdentityServer?

**Comment by leastprivilege** [comment]
OAuth2 / OIDC is designed for JWT. We really only emit SAML over WS-Federation.
