### ISSUE TITLE
Loginpage html

### ISSUE THREAD

**Issue by ANEDev** [IdentityServer/IdentityServer3#1850]
Hey Community,

is the loginpage of the IdentityServer3 a code generated html file or a physical html file?
If the file is physical where can I find the html file ?
If the file is code generated in which .cs file I can find the code ?

Thanks,
ANEDev

**Comment by brockallen** [comment]
I'd suggest spending some time in the docs: https://identityserver.github.io/Documentation/docsv2/advanced/customizingViews.html

**Comment by ANEDev** [comment]
Is it possible adding more html files to the identityserver with its design?

**Comment by brockallen** [comment]
I don't follow -- what are you trying to do?

**Comment by ANEDev** [comment]
I'm trying to add a registration html page to the identityserver is that possible?
If that's not possible I would like to get the layout of the login page for my registration page.

**Comment by brockallen** [comment]
you can add custom code (MVC, etc) to the same host as IdSvr -- so it's not part of IdSvr, per-se. But yes, it's common to put those two things together.

**Comment by atul221282** [comment]
As brock have mentioned you can use CustomViewService look at the Sample project. U can even downlaod the app folder(which contains all the html, JS files and CustomViewService code  from github. It gets the view on runtime and inject that view string. So just by modifying the html u can create ur own custom view but that won't include the registration page but u can create ur own one as registration doesn't belong to idsrv anyway. Correct me if I am wrong Brock

**Comment by ANEDev** [comment]
Ok thank you I will try it

**Comment by ANEDev** [comment]
Hey there, 
is it possible to influence the login process for example that users which do not confirmed there email are not able to login to the page ?

**Comment by brockallen** [comment]
In the future for new questions, please open new issues. 

For controlling the user workflow, please look at the docs for the user service: https://identityserver.github.io/Documentation/docsv2/advanced/userService.html
