### ISSUE TITLE
rememberMe doesnt work

### ISSUE THREAD

**Issue by helmas** [IdentityServer/IdentityServer3#1851]
I have configured my idsvr3 settings. And cookieOptions has been set. But however, rememberMe model property always comes as **false**. I cannot figure out why. Here is the flow that i followed:

* Redirect login page
* Try to log in with any account by getting checked rememberMe checkbox
* After login, try to logout
* Try to open login page again

All you seen will be unchecked rememberMe checkbox. LoginViewModel turns rememberMe property back as false for both situation.

1.6.2

**Comment by brockallen** [comment]
If you logout, that removes the "remember me" persistent cookie. The "remember me" setting is if the user just closes their browser without logging out.
