### ISSUE TITLE
AuthorizationCodeReceived event won't get called, if RedirectUrl has no final slash!?

### ISSUE THREAD

**Issue by mzagel** [IdentityServer/IdentityServer3#1852]
Hi there,

first of all my setup: 
On client side I've taken the MVC OWIN Client example with Hybrid Flow (from the IdSvr samples). There isn't much I customized. Some additional scopes, but that's it pretty much.
On server side I've done some customizations as well (custom client store, user service, scopes etc.).

During our first implementation steps we've used IIS Express. Locally (with IIS Express) when we are logged in, the claims page lists all supplied claims. Everything worked quite fine, until we tried to test the stuff on our servers with real IIS applications. The result was rather strange: 
1. Open the client url.
2. Click on the "Claims" Menu.
3. Redirect to the IdSvr to enter credentials.
4. Redirect to client again,
5. No errors, **but claims page is not shown**.

I was able to reproduce the exact same behaviour on my machine using the Local IIS. Actually the user is authenticated correctly on server side, but the event `AuthorizationCodeReceived` is not called. Besides no error occurs (not even within the logs).

It took me quite some time to figure out the problem, because all we changed was 
- use real IIS applications
- switch off SSL (we are behind a load balancer which takes care of SSL)
- adjust the URLs

It turned out, the problem was cased by the missing slash at the end of the RedirectUri:
`RedirectUri = "http://localhost/MvcOwinHybridClient/"`: working
`RedirectUri = "http://localhost/MvcOwinHybridClient"`: not working

Please note with IIS Express it doesn't matter at all if the slash is present or not, both scenarios work there!?

Although I can work now with this solution, I'm extremely curious and I hope someone can explain this behaviour.

Thanks for your help,
zacko

**Comment by leastprivilege** [comment]
Yep - despite MS claiming IIS and IIS Express are exactly the same - the trailing slash handling is different. I ran into that as well.

Sorry for your pain.

**Comment by mzagel** [comment]
OK, I already guessed it's not a IdSvr problem.

But what I really don't understand is, that no error occurs. When OWIN (or the IIS or whatever) has a problem with the specified URL it should throw an exception instead of just ignoring it...

**Comment by leastprivilege** [comment]
that's good feedback for Microsoft.
