### ISSUE TITLE
WCF - IdentityServer - ResourceAuthorization??

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1853]
Hello,

I investigated the WCF IdentityServer3 Example as in the blog:
http://leastprivilege.com/2015/07/02/give-your-wcf-security-architecture-a-makeover-with-identityserver3/
So in general, Once the user has the right scope in the claims, he can access all methods with OperationContract in the servicecontract.
What I miss is something like Thinktecture package "Thinktecture.IdentityModel.Owin.ResourceAuthorization". Then one could add the attribute to the Wcf Service methods. And also one could use the Checkaccess call from inside the method.

Is there anything available for WCF which allows finegrained Authorization as "Thinktecture.IdentityModel.Owin.ResourceAuthorization"?

**Comment by leastprivilege** [comment]
No. but feel free to write your own ;)

**Comment by davidmrichter** [comment]
Anything "old" from Thinktecture or others existing? like WCF Service Methods attributes for Authencation/Authorization for identityserver v1 or v2? This would help to understand the WCF So I could modify the Thinktecture.IdentityModel.Owin.ResourceAuthorization with just the WCF "part" for identityserver3.

**Comment by leastprivilege** [comment]
No sorry - I think I never did something like this for WCF.
