### ISSUE TITLE
Allow per-user scope validation

### ISSUE THREAD

**Issue by Cephei** [IdentityServer/IdentityServer3#1856]
I'm still thinking through this feature request and whether it's a proper way of doing things, but wanted to get outside input.

Scenario
An API has five resource scopes {A,B,C,D,E} that represent user privileges. Obviously not every user has every privilege.

A native client (say android) is built upon this API.  The client supports features for all operations supported by these scopes.

1. User goes to /authorize endpoint for Open ID Connect authentication.
2. They login.
3. They are presented a consent screen.
> The current consent screen displays all scopes requested by the client (A,B,C,D,E), *__even though__*, the user account only has privileges to perform {A,B,C}.

Currently, there is no service in IdSrv3 to perform a dynamic "AllowedScopeValidation".
See: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/ScopeValidator.cs#L131

The validation is fixed upon:
1. validating requested scopes come back (exist) from the scope store
2. validating the client contains __each__ scope in it's fixed AllowedScopes enumeration

This is not entirely problematic but leaves a seemingly unfriendly user experience.  The scope of the problem is that I can give consent to create an access token with privileges that I actually don't have.

Obviously, when calling the API with that access token, the back end should properly handle permissions and see that my user doesn't have those privileges.  However, this undermines the usefulness of JWT tokens.  A JWT access token that's been signed and issued can contain API privileges / scopes / roles etc.

__Instead of:__
OpenID Connect auth -> access_token -> API request -> resource -> *get user permissions from io* -> verify the access_token contains that permission -> perform action -> response
__it could be,__
OpenID Connect auth -> *get user permissions from io* -> take the set intersection of db permissions & requested scopes -> access_token -> API request -> resource -> check principal for roles or identity claims -> perform action -> response

The argument is essentially two-fold:
1. can using a JWT to encapsulate resource permissions remove the additional trip to the db or cache required at a later point in the request pipeline? (ie. domain layer validation)
2. can/should we improve the user-experience for the consent screen to display, not simply the requested scopes of the client, but the requested scopes filtered by the user's current permission set? (ie. even though my client requests admin scope rights, the consent screen is dynamically rendered - based upon what permissions I can actually give consent to.

My assumption is the following:
1. No, a JWT is not a single-source of truth and can't be because permissions are not static in most systems. As an admin I can grant and revoke a user's read,write,admin,delete (etc) rights at any time.  Therefore, I always have to check permissions lazily by taking the intersection of current user privileges and what the access token has been consented to have.
2. I'm still undecided...

**Comment by leastprivilege** [comment]
Sorry - haven't read everything - but

"An API has five resource scopes {A,B,C,D,E} that represent user privileges"

is just wrong. Sopes don't represent user privileges. They are used to model resources and can't be used for per user authorization.

**Comment by Cephei** [comment]
I may be using improper terminology. My thinking is based upon some ideas from reading about JWT.  Even github seems to use scopes as resource permissions... https://github.com/settings/tokens/new

**Comment by Cephei** [comment]
So for example,
An Android client supports admin:reporting scope. But the user really can't give consent to that scope because they're not an admin.  Why should the consent screen display it even though the client requests it?

**Comment by Cephei** [comment]
After some further thinking, it looks like if I wanted to address #2, I could filter out resource scopes based upon user privileges by simply overriding the DefaultViewService's Consent(ConsentViewModel model...).

Would still be interested to hear your opinions on this user experience - whenever you have a moment free.  From my reading, OAuth / OpenID Connect specs really don't provide any UX guidance/standards on user consent interaction.

**Comment by Cephei** [comment]
Unfortunately, I thought I could address this with subtle modifications with a custom `IViewService.Consent()` but neither `ConsentViewModel` or `ValidatedAuthorizeRequest` do not provide information concerning the current logged in user identity - only their display name.

**Comment by brockallen** [comment]
Scopes indicate what resources the client application wants access to. This is orthogonal to the user's privileges. In your API you want to ensure authorization for both.

**Comment by Cephei** [comment]
Understood, though why present the user the options to give consent to the client, access to resources the user does not have access to?

**Comment by brockallen** [comment]
Showing the consent screen only makes sense for 3rd party apps. 3rd party apps need to ask for the scopes they want the user to consent to. I agree it's a bit odd to prompt for a resource the user doesn't have access to, but generally that logic is in the API, not in IdSvr. IdSvr doesn't currently have a hook to dynamically filter those scopes on the consent page.

**Comment by Cephei** [comment]
Thanks for your response.  That actually makes perfect sense.  Working so closely with the API, I sometimes forget to shift perspective as a 3rd party developer.
