### ISSUE TITLE
Cookie Options - SecureMode

### ISSUE THREAD

**Issue by wsthesis** [IdentityServer/IdentityServer3#1857]
On a production instance running entirely on HTTPS, should the Authentication Options -> CookieOptions -> SecureMode attribute be set to Always instead of SameAsRequest?
The RequireSSL attribute remains at the default value of true.
What benefits and/or drawbacks are there to changing to Always?

The OWIN and IdentityServer documentation does not seem to really talk about pros and cons.

Thanks in advance.

**Comment by brockallen** [comment]
If you've configured IdSvr for SSL, then you won't ever get to the cookie middleware.

**Comment by wsthesis** [comment]
Ok, thanks for clarifying Brock. I think that answers my question.
