### ISSUE TITLE
Multilanguage set up

### ISSUE THREAD

**Issue by JoachimL** [IdentityServer/IdentityServer3#1858]
We are soon to deliver a multidomain solution with idsrv as the authentication mechanism. The solution is multilingual (12 languages, and counting), and we need a way to translate idsrv - both views and messages. If at all possible, I'd like to keep one idsrv domain and serve translated content based on e.g a querystring parameter. Apart from the itranslationservice, which is what I need for the strings returned from idsrv itself, how would I go about achieving this? Any ideas/suggestions/examples?

**Comment by JoachimL** [comment]
(Pressed submit too soon)
If like to keep one idsrv domain and serve translated content based on e.g a querystring parameter. Apart from the itranslationservice, which is what I need for the strings returned from idsrv itself, how would I go about achieving this? Any ideas/suggestions/examples?

**Comment by leastprivilege** [comment]
* Authorize endpoint has a parameter for locale (check docs). 
* Read that param in PreAuthenticate in UserService
* Set language cookie
* Read that cookie from your view service (using OWIN environment)
* localize all views based on language value in cookie

no sample for it - but feel free to contribute one when you have it working.

**Comment by JoachimL** [comment]
Cheers, will give it a go and get back to you with samples if successful. When succesful.

**Comment by JoachimL** [comment]
I'm actually not able to find anything re locale in the docs. Ui Locales are briefly mentioned here, though: https://identityserver.github.io/Documentation/docs/advanced/userService.html Guess I'll dig a bit in the source.

**Comment by brockallen** [comment]
I guess we don't specifically list it in our docs (I supposed because we don't do anything with it), but it's the ui_locales param: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by leastprivilege** [comment]
it's documented now.
