### ISSUE TITLE
Thinktecture.IdentityModel vs IdentityModel

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1859]
In the samples I saw Thinktecture.IdentityModel being used, In the WCF identityserver3 example I saw IdentityModel used. the later is more recent.

I gather in any case one should use IdentityModel not Thinktecture.IdentityModel, right?

**Comment by leastprivilege** [comment]
IdentityModel is the newer one - if what you need is in there, use that.

**Comment by olonga** [comment]
@leastprivilege, I did see that Thinktecture.IdentityModel is marked as deprecated. However, I am still using ScopeAuthorize attribute from this project.  Is there an alternative for this? Thanks.

**Comment by leastprivilege** [comment]
Feel free to copy the source code.

**Comment by olonga** [comment]
@leastprivilege cool. Ty.
