### ISSUE TITLE
Subclass DefaultViewService: ClientPermissions method is not virtual and cannot be overidden

### ISSUE THREAD

**Issue by jeanmaz** [IdentityServer/IdentityServer3#1860]
In the view service class, I would like to customize the custom parameters for the "Login" and "ClientPermissions" methods. I want to include new parameters in "LoginViewModel.Custom" and "ClientPermissionsViewModel.Custom" objects.

I've extended the class DefaultViewService to override the "Login" method but cannot do the the same for the "ClientPermissions" method as "ClientPermissions" is not virtual in "DefaultViewService". 

```c#
  public class DefaultViewService : IViewService
  {
        public virtual Task<Stream> Login(LoginViewModel model, SignInMessage message);
        public Task<Stream> ClientPermissions(ClientPermissionsViewModel model);
}
```

Is there any reason why the "ClientPermissions" method is not virtual ? Or is there any better approach to customize the parameters ?

**Comment by brockallen** [comment]
the lack of virtual looks like an oversight. but to fix, that's a breaking change, so it'll have to go into 3.0.

as for the custom params, where do the values come from? IdSvr won't know how to pass them.

**Comment by jeanmaz** [comment]
Ok, thanks. 

For the custom params, I want to have some custom texts for the permissions and the layout pages. In the html page, I want to bind these new properties using the custom bind property {{model.custom...}}.

The values would come from a database.

**Comment by brockallen** [comment]
So look at the "Adding custom data to the rendered view" section in the docs: https://identityserver.github.io/Documentation/docsv2/advanced/DefaultViewService.html

**Comment by leastprivilege** [comment]
added as a todo for 3.0.0
