### ISSUE TITLE
ITokenHandleStore - deserialize Token issue (Redis + Json.net)

### ISSUE THREAD

**Issue by Davidsual** [IdentityServer/IdentityServer3#1862]
Hi

I am currently using IdentityServer 3 version 2.0.1

I am trying to Store and Get the Access token from a Redis database.

Storing a Token is not an issue the token object is correctly serialized (Json.net) inside Redis database.

When IdentityServer try to GET the Token I get an error from Json.Net
```
public class TokenHandleStoreService : ITokenHandleStore
```
Method
```
        public async Task<Token> GetAsync(string key)
        {

            if (_cacheProvider.Exists(key))
            {
                return await Task.FromResult(_cacheProvider.Get<Token>(key));
            }

            return await Task.FromResult<Token>(null);
        }
```

Error Message = "Unable to find a constructor to use for type System.Security.Claims.Claim. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Claims[0].Issuer', line 1, positio...

This error simply because System.Security.Claims.Claim doesn't have a default constructor.

As far I understand (unless I write I custom serializer for Token, the Token itself cannot be stored in Redis but it works just with InMemory Implementation.

I tried different approach suggested in previous post but always with no luck

```
var tokenDeserialized = _cacheProvider.Get(ckey, typeof(object)) as Token;
```
tokenDeserialized  is always null.

Any suggestion? 
Should I create a custom serializer for the IdentityServer3.Core.Models.Token object?

**Comment by brockallen** [comment]
Your cache implementation needs to map to some simple data structure and not rely upon serializing the claim class.

**Comment by Davidsual** [comment]
Thank you Brock, I will follow your advice.

**Comment by farshid3003** [comment]
This caching does not work for users and clients with claim

Solution for user:

add a custom json converter

    public class ClaimConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return (objectType == typeof(System.Security.Claims.Claim));
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            JObject jo = JObject.Load(reader);
            string type = (string)jo["Type"];
            string value = (string)jo["Value"];
            string valueType = (string)jo["ValueType"];
            string issuer = (string)jo["Issuer"];
            string originalIssuer = (string)jo["OriginalIssuer"];
            return new Claim(type, value, valueType, issuer, originalIssuer);
        }

        public override bool CanWrite
        {
            get { return false; }
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
    }

use it like this:

        public async Task<IEnumerable<Claim>> GetAsync(string key)
        {
            var result = await cacheClient.GetAsync<object>(key);

            if (result != null)
            {
                IEnumerable<Claim> claims = JsonConvert.DeserializeObject<IEnumerable<Claim>>(result.ToString(), new ClaimConverter());
                return claims;
            }

            return await Task.FromResult<IEnumerable<Claim>>(null);
        }


and you should use it for clients as well

        public async Task<Client> GetAsync(string key)
        {
            var result = await cacheClient.GetAsync<object>(key);

            if (result != null)
            {
                Client client = JsonConvert.DeserializeObject<Client>(result.ToString(), new ClaimConverter());
                return client;
            }

            return await Task.FromResult<Client>(null);
        }
