### ISSUE TITLE
Simplest OAuth2 Walkthrough - "error": "invalid_client" returned if using Postman

### ISSUE THREAD

**Issue by alexjamesbrown** [IdentityServer/IdentityServer3#1864]
I may have set something up wrong with my postman request, but every time I try and get a token, I get    > "error": "invalid_client"

<img width="551" alt="screen shot 2015-09-09 at 23 52 49" src="https://cloud.githubusercontent.com/assets/437743/9776251/7fb81012-574e-11e5-98af-fb21866ce40f.png">

**Comment by leastprivilege** [comment]
Well - as always - check the logs.
