### ISSUE TITLE
General process of using web api as identity server and resource server

### ISSUE THREAD

**Issue by alexjamesbrown** [IdentityServer/IdentityServer3#1865]
**Web API project (/api)**
Contains Resources - Orders, Users, etc...
[AllowAnonymous] is on Users.Post to allow registration
Contains ASP.net Identity stuff to register / authenticate users

So in essence, this is my identity server, and my resource server.

I would post to /api/connect/token in order to authenticate and get a token.
I'll use password grant type, so will post the username, password, client_id, client_secret to this endpoint.

**MVC Client App (Client)**
Very lightweight. Uses HttpClient to request resorces from Web API project.
'Registration' basically consists of POSTing to the /api
Authentication will be using the IdentityClient to get a token from /api/connect/token

I realise I've over-simplified this, but does this sound about right?
Or have I missed something?

**Comment by leastprivilege** [comment]
Yes that would work. 

You might want to consider separating identityserver from the api into a separate app for future developments like api2, api3 etc..

**Comment by atul221282** [comment]
keep IdentityServer as different project and create api as resource api which will just expect user to beauthenticated and server data. For registration i will still hit my resource api as i just wan't to keep idsrv for issue tokens only as per client
