### ISSUE TITLE
Segregating multiple apis (within the same Web Api project) by scopes

### ISSUE THREAD

**Issue by indranilatcal** [IdentityServer/IdentityServer3#1866]
Hi

We have a case where there are many ASP.NET Web Apis hosted under a single project. As I understand, the only way to protect an api is to define a scope (registered with the identity server) and then list it as a required scope in the Owin startup file via IdentityServerBearerTokenAuthenticationOptions. In our case, there are many Apis (controllers & actions) under the same project. But they need to be segregated in a way such that different sets of them can be accessed (and hence protected by scopes) by clients. If I put multiple scopes for RequiredScopes, then so long as the client presents a token containing any of them, the entire api set gets accessible. What I need is if a token has 'scopea', a particular set of apis become accessible, for 'scopeb', another set is allowed access. Is it possible to achieve it someway or splitting the apis into separate projects (with an Owin startup of their own with a designated scope) is the only way out?

**Comment by brockallen** [comment]
You can check the claims for the request in each controller (or perhaps do this as an attribute) to see if it has the right scope for that controller.

**Comment by indranilatcal** [comment]
In that case I'd probably need to remove the required scope from Owin startup file so that it can get to the controllers. Is that correct?

**Comment by leastprivilege** [comment]
yes - use something like this

https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/master/source/WebApi/ScopeAuthorizeAttribute.cs

**Comment by indranilatcal** [comment]
Thx.
