### ISSUE TITLE
Enforcing authorization of Web Apis

### ISSUE THREAD

**Issue by indranilatcal** [IdentityServer/IdentityServer3#1867]
Hi

I need to enforce authorization checks for web apis based on claims issued by the identityserver. I've had a look at the 'Getting Started: MVC Authentication & Web APIs' sample, but there, all the authorization seems to be done within the client application. Is it possible to do something similar in the 'protected Web Api'? In this sample, all that protects the web api is its required scope. Is that the only protection possible or we can go to deeper levels as it has been illustrated in the client app in this example? The packages used for authorization are prefixed with Thinktecture, but I suppose I read somewhere that version 2.x of identity server has gotten rid of Thinktecture from the packages, but I don't seem to find a nuget package that deals with Authorization that is devoid of Thinktecture.

**Comment by brockallen** [comment]
Yes, you have the claims for the request (User, Client, Scopes in the access token) in the Web Api so you will can do the necessary authorization checks.

**Comment by indranilatcal** [comment]
Okay. I'd try it out then. I found a nuget package for resource authorization Thinktecture.IdentityModel.Owin.ResourceAuthorization. But for Accesstoken validation, I'm using IdentityServer3.AccessTokenValidation (this one doesn't start with ThinkTecture). Can you confirm if they are compatible or rather independent?

**Comment by leastprivilege** [comment]
yes should work.

**Comment by indranilatcal** [comment]
Thx for the prompt response.
