### ISSUE TITLE
Azure AD non-standard claims in token.

### ISSUE THREAD

**Issue by WassMM** [IdentityServer/IdentityServer3#1868]
Hello,

One of our identity provider is Microsoft and it works fine. My problem is I don't see some claims which AAD (Azure Active directory) generates for my IdentityServer token. For example, if user is in a group of AAD users then Microsoft includes the claim ["groups", my_group_id] into token - I could confirm that by requesting the token directly from AAD, but if I get token via IdentityServer then I don't see the claim. For IdentityServer scope I use:
IncludeAllClaimsForUser = true;

In general question is if external provider generate a claim how to see the claim in token from IdentityServer?

Thank you

**Comment by leastprivilege** [comment]
So it is all happening in **your** user service - I would debug the AuthenticateExternal and GetProfileData methods to figure out what is going on.

**Comment by WassMM** [comment]
And my ClaimProvider also, as I understand my "non-standard" claims must be part of values of GetStandardSubjectClaims/GetOptionalClaims methods. Anyway your answer helped a lot! Now I know a bit more about the IdentityServer. Thank you!
