### ISSUE TITLE
User access to an Api

### ISSUE THREAD

**Issue by indranilatcal** [IdentityServer/IdentityServer3#1870]
We have a scenario where an end user can be given access to an api resource. However, there's a client app in between that accesses the api on user's behalf. I'm using implicit flow (since the client app is a JS enabled browser client). The samples that I've come across (using in memory clients) is that a registered client has the api scope listed within it's AllowedScopes. So, the moment a request comes to the authorization endpoint, so long as the user is authenticated, the client gets hold of the api scope (since it has it in its allowed scope list) & can access the api. Whereas, my need is to also check whether the user has access to the api resource. Where can I add that check?

**Comment by brockallen** [comment]
You do that in the Web API.
