### ISSUE TITLE
ValidationMode.Local certificate location question

### ISSUE THREAD

**Issue by 0xYG3NIUM** [IdentityServer/IdentityServer3#1871]
I am currently using ids3 for authorizing webapi requests. ValidationMode is set to Local to avoid calling Identity Server with each API call. But in order to check the token validity API server should have the public key which is retrieved from Ids openid configuration. So how is the public key stored between API requests?

**Comment by leastprivilege** [comment]
In memory. And refreshed every 24h

**Comment by 0xYG3NIUM** [comment]
Understood. Thanks.
