### ISSUE TITLE
Detect Partial Sign In from API call

### ISSUE THREAD

**Issue by RemotecUK** [IdentityServer/IdentityServer3#1872]
My identity server is set up as follows...

Authority: `accounts.domain.com`
Registration: `accounts.domain.com/register` (MVC Controller)
API: `accounts.domain.dom/checkUser` (Web API Controller)

The flow is, the person clicks "Sign-in with Google", they sign in with Google, I recognise that I do not have this person in my local user store and I redirect them to /register. This is a SPA application that will collect registration information and whilst doing that perform a check on the user. As part of this I will do an XHR GET on /checkUser where I need the partial sign in claims to do some validation.

The problem I have is that this code is not working for me...

    [Route("checkuser")]
    public class ApiCheckController : ApiController
    {
        public async Task<IHttpActionResult> Get()
        {
            var ctx = Request.GetOwinContext();
            var authentication = await ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType);

            if (authentication == null)
            {
                return BadRequest();
            }

            return Ok(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss"));
        }
    }

The method is hit, and I have confirmed in the browser that the `idsrv.partial` cookie is passed. However the value of `authentication` is always null.

I thought maybe I need to have `UseIdentityServerBearerTokenAuthentication` in my Startup code but this does not seem to be compatible with Identity Server operating on the root of the site (the site hangs when attempting to sign in).

Is there a way to get this working so I get access to the claims passed from Google in this call? I'm guessing something is missing so that the cookie is not being read by the middleware around the controller method invocation.

The other choice I have is to make a cross origin request to `api.domain.com` to do this check, but I think that the partial sign-in cookie only works on `accounts.domain.com` so seems like a non-starter.

Thanks.

**Comment by brockallen** [comment]
Is the route `checkuser` in the same pipeline as IdSvr?

**Comment by RemotecUK** [comment]
Yes, it's in the same pipeline.

**Comment by brockallen** [comment]
So then I'm not sure -- it should be working. Do the samples that do this work for you?

**Comment by RemotecUK** [comment]
I have got around this issue by making an MVC controller return JSON for my API call. This then has access to the idsrv.partial cookie.

Is there any way to scope this cookie so that it could be available to applications on different sub domains? Then I could implement my custom registrations flow in another application which would help to keep things cleaner.

**Comment by leastprivilege** [comment]
we need to discuss @brockallen

**Comment by leastprivilege** [comment]
we can't easily scope cookies to sub domains.
