### ISSUE TITLE
The type or namespace name 'NLogLogProvider' could not be found?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1873]
Trying to add this line in application_start,

            LogProvider.SetCurrentLogProvider(new NLogLogProvider());
            app.UseIdentityServer(options);

But getting The type or namespace name 'NLogLogProvider' could not be found? Me using IdentityServer3.2.0.0

**Comment by leastprivilege** [comment]
Because it is not necessary. Read the docs.

**Comment by abcplex** [comment]
Come on. I need to enable NLog. Also putting this line in StartUp.cs make sense.

**Comment by abcplex** [comment]
Found it at https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/App_Packages/LibLog.4.2/LibLog.cs But where is it Nuget

**Comment by abcplex** [comment]
Any idea? How to add NLogLogProvider support? Is we need this package? https://www.nuget.org/packages/LibLog

**Comment by abcplex** [comment]
@leastprivilege can you please tell me how to include this in my project or should I create my own ILogProvider and Logger?

**Comment by abcplex** [comment]
Just installed https://www.nuget.org/packages/Serilog.Sinks.NLog/ and added this line in 

      Log.Logger = new LoggerConfiguration()
                .WriteTo.NLog()
                .CreateLogger();

Also added NLog.config file and set Output Copy if new

It works Thanks.
