### ISSUE TITLE
Dynamic endpoint URLs for muli-tenant support

### ISSUE THREAD

**Issue by aaronwjha** [IdentityServer/IdentityServer3#1874]
What would be the simplest way to configure endpoint URLs like:

https://[domain]/[tenantId]/connect/token

We have many tenants (1,500 to start) and will need this to work dynamically so we don't have to bring the server down to add more tenants. I've been looking at [SaasKit](http://benfoster.io/blog/saaskit-multi-tenancy-made-easy), but figured there might be a simpler solution that I'm not aware of.

**Comment by brockallen** [comment]
You'd have to do something in your host to do that dynamic mapping -- that's not an issue with IdSvr.

**Comment by aaronwjha** [comment]
I totally get that. I'm just looking for some guidance from anyone who may have already tackled this problem.

**Comment by brockallen** [comment]
The only thing I can suggest for putting the tenant in the URL is to perhaps use the conditional `Map` in katana -- never tried it, but it's what I'd try first.

**Comment by leastprivilege** [comment]
Please report back when you make progress so others can benefit from that! thanks!
