### ISSUE TITLE
Creating a branch per release

### ISSUE THREAD

**Issue by bloudraak** [IdentityServer/IdentityServer3#1875]
Would it be possible to create a branch for every release e.g. 2.0 vs 1.6?  Since 2.0 has some breaking changes, it would allow us to patch 1.6.

**Comment by brockallen** [comment]
If/when we need to patch 1.6.2 we'll fork from the prior label.

**Comment by bloudraak** [comment]
That's a very manual way of doing things and makes the workflow a tad more complex. 

The challenge comes from when you have folks like me, that builds, package and audit the source code separately. If you already have a branch for a release, the process is pretty trivial to create a pull request and submit it.  A label complicate matters. 

My suggestion is not to have a branch for each of the 1.6.0, 1.6.1, 1.6.2, 2.0.0 or 2.0.1 releases, but to have it on the major and minor versions, such as 1.6 and 2.0.  If you make it consistent across documentation, samples, plugins and the core codebase, then it will be much easier to relate the different codebases. 

Here's a couple of repos that do it well.

* https://github.com/postgres/postgres
* https://github.com/mongodb/mongo 
* https://github.com/nodejs/node
* https://github.com/docker/docker
* https://github.com/apache/httpd

Many of the Microsoft repos are just a mess.  

In the end, its about being consistent and avoiding any confusion. I'm a big fan that an official repository should only contain meaningful branch names and tags and that it should be easy to synchronize with forks and be built.  Many build system will automatically detect and build new branches without any human intervention. The same can't be said for tags.

**Comment by brockallen** [comment]
Good feedback, we'll consider it. Thanks.

// @leastprivilege

**Comment by dealproc** [comment]
In reality, they do have a branch per release (the tags).  You can check-out the tag, patch it, push the changes, and re-tag it as `1.6.{whatever}` back into the repo.

**Comment by bloudraak** [comment]
@dealproc How would that work?

Lets take a real world scenario. Lets assume we have 3 or more forks of the repository, which in turn is cloned by any number of folks.  Those forks could be private or public. Each of the forks have their own build processes and procedures before they will accept the code into their production system.  

Now, lets assume that one of the teams find a bug. Someone checks out the 1.6.2 tag of a form, creates a branch (and deleting the tag to avoid confusion), then commits to their own fork, which they build and verify. They'd like to push that change to the official repository.  (Note how human had to create a branch; it could be named anything). 

And this is where I start to cringe.  What's the effort for the official maintainers to get this fix merged with the code once its approved? I'm certainly not the one to claim minimal effort, when there's other priorities (kids, family, work deadlines).  

Even if we're adamant that we'll do it the hard way, then there is the issue of what happens downstream once the patch is applied and the branch was created.  If one of those teams use TeamCity, changes are they pinned their build to a tag 1.6.2. They will never benefit from the fix, unless they go through great lengths to design their build processes accordingly. That requires foresight. 

By contrast, if there was a 1.6 branch, the team commits it to the 1.6 branch in the fork, builds it, test it and submits a pull request to the official repository. The pull request gets approved and committed to the 1.6 branch of the official repository.  Other teams updates their forks with the official branch and their build systems pick up the change and builds it. 

Human involvement is limited to things humans do best: fix code, test, code review and update forks at a convenient time.

**Comment by bloudraak** [comment]
@dealproc I reread your suggestion. Technically, in git, a tag isn't a branch. It doesn't represent a development stream, but instead a single commit. Even the metadata stored with a tag is different than that for a branch.

**Comment by leastprivilege** [comment]
Once we are in the situation where we need to maintain multiple versions (like applying fixes to older releases), branches are more useful. Agreed.

Right now the labels good enough.

**Comment by bloudraak** [comment]
It seems we're treating this repository as the only repository of IdentityServer3 that would ever exist. If so we're totally missing out on some of the benefits of a distributed version control system, where any fork can act as an official repository within its context. 

I'm trying to patch v1.6 in my own fork (since v2.0 is a breaking change).  Simply upgrading assemblies from 1.6 to 2.0 means the code doesn't compile, nor does my application work after the upgrade. So using 2.0 is not an option at this time given aggressive deadlines. 

The lack of a branch makes matters much more complicated in terms of builds etc. on my side. I'm really not sure I want that additional overhead, considering everything else.
