### ISSUE TITLE
Handling cookie path case-sensitivity

### ISSUE THREAD

**Issue by gustafsonk** [IdentityServer/IdentityServer3#1876]
Let me start by giving a huge thanks to this project as it has saved me so much time in developing an identity management solution.

I was having a bizarre problem where the first person to visit my website sets a behavior for others but now I understand what's been happening. I was having the same symptoms and came to the same conclusion as the person mentioned in #1522. The issue is here: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AppBuilderExtensions/ConfigureCookieAuthenticationExtension.cs

The first request that comes in determines the path of the cookie, which works pretty good, but unfortunately cookie paths are case-sensitive so this can break the login functionality unless everyone uses the same casing for all requests. I was able to solve my problem by setting CookieOptions.Path = "/", which is fine for my own usage of IdSrv, but I feel like there has to be a way to improve the default behavior.

**Comment by brockallen** [comment]
Hmm, that's really Microsoft's code (@tratcher) -- we're just setting it on the first request. You'd have to ask them to get it fixed in Katana (which I'm 99% sure they won't do).

**Comment by Tratcher** [comment]
Hmm, the case sensitivity is on the client. I don't know that there's much we can do about it on the server. I think the behavior of vNext is such that you wouldn't set this property at all: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationHandler.cs#L150
