### ISSUE TITLE
Complex Authentication Workflows

### ISSUE THREAD

**Issue by bloudraak** [IdentityServer/IdentityServer3#1878]
I have a pretty complex and comprehensive authentication workflow consisting of approx. 26 steps.  I would hate to bore you with the details or the uptight requirements that come with writing a secure identity provider. Never mind the complexities of user interfaces and the esoteric technologies they are built on.  

Here are some of the details

* logging successful and erroneous requests such that malicious behavior can easily be discerned and reported.  Typically this requires that each significant event in the application be logged with an identifier  and IP addresses. In order to process this at high volume, the event has to be structured (think ETW) and easily parsed (sorry log4net doesn't cut it). 
* be adaptive to block malicious activity and offer means to unblock it automatically.  Have you ever seen what happens if you look malicious to Google? Instead of showing you a login page, it shows you a captcha.
* locking user accounts after they failed to sign in and offer automated ways to unblock it.  Showing an error message doesn't cut it. 
* go through a password reset process that may consist of several steps, especially to deal with the 20% of the users that are computer illiterate, confused or in need of assistance (think about your grandma here) 
* deal with all the accessibility stuff; yeah, it turns out that this is super important when dealing with government agencies. And we need to be more respectful of folks with disabilities, or the elderly who can no longer read 12pt fonts, or those that see red when its yellow. Oh, an those smart 20 year olds who think they know everything and don't read the 600 page manual. 
* localization. This is complex all by itself. 
* deal with complex federation scenarios. If your email address ends in example.com, automatically federate with the server over there.  
* deal with user migrations. The current identity store is ASP.NET Membership and when users sign in, authenticate them, and migrate them to a new identity store (Membership Reboot perhaps). In other cases, migrate a user who has a local account, to always use an external account (e.g. migrating from ASP.NET membership to Azure AD or ADFS).
* auditing requirements, like showing users activity on their account, or sending them an email when their passwords etc is reset, when they login.
* support legacy SSI and SSO solutions. Don't get me started, but some systems have been around before SAML and XML was even a buzzword. 
* displaying user agreements (this is pretty complex when corporations and consumers use your product)
* registration processes (darn, this gets very complex too). In one case, a person may simply complete a form with a username and password. In another case, it may require a product key (issued during a sale).
* use of toggle switches to control capabilities based on the source IP address, the user and other stuff.
* integration with external security applicants, such as IDS (Intrusion Detection Systems), IPS (Intrusion Prevent Systems), realtime monitoring and health checks (how do I know IdentityServer3 is correctly configured and "healthy"?).

I had a look at the `IUserService` and `IViewService` and overriding both are inadequate to handle the complex workflows.  In essence, the authentication workflows UX wise is too tightly coupled with IdentityServer3.

I'd like to suggest that IdentityServer3 be broken into two or more components. The first handles only the OpenID Connect Protocol and is totally void of any user interface.  What it does instead is create a set of APIs which any UX can call to complete the process.  We can then show how to integrate an existing ASP.NET MVC or WebForms application, already configured to handle authentication, with IdentityServer3.  Better yet, create "Web Application" templates thats shows how to implement  custom workflows using that API.

Then we can focus on the different UX scenarios. There can then be several implementations of the latter, namely the current implementation (which uses IUserService and/pr IViewService), one for ASP.NET MVC (with its IIS and System.Web dependencies), one for WebForms (Hell Yeah, some folks still use it), one for AngularJS and then any technology required. 

Its important to realize that self hosted own instances of an OpenID Connect Identity Provider often doesn't fly only because it lacks the integration and support of industry strength IDP and IDS systems.  So for publicly facing websites, implementing complex and comprehensive authentication UX workflows as Owin middleware is cumbersome and often a waste of time.

I know there are folks who would disagree. But if there is the price tag of a data breach is estimated to be in the millions or even billions, then one tends to be a tad more cautious and less assuming.  Sometimes, you'd rather delegate the risk somewhere else.

**Comment by leastprivilege** [comment]
If your application is that complex - the protocols would be my least concern ;)

That said - not sure if you are aware of the partial login concept and plugging in external providers - both allow to customize the authentication workflow to your hearts content.

For the other features - yes - many things are not currently present. You would probably have a hard time finding all the features in a commercial product as well.

If you think one or the other feature should be included - please open separate issues so we can discuss if/how you could add them via a PR.

thanks!
