### ISSUE TITLE
Influence the Login Process

### ISSUE THREAD

**Issue by ANEDev** [IdentityServer/IdentityServer3#1879]
Hey Community, 
I want to influence the login process with the extension that users whose do not confirmed there email are not able to login to the page. I read this documentation: "https://identityserver.github.io/Documentation/docsv2/advanced/userService.html"
But the problem is I can't recognise how to implement that. Is there any example given where I could look into ?

**Comment by loctanvo** [comment]
Hmm, so my two steps in your previous question (https://github.com/IdentityServer/IdentityServer3/issues/1745) is not clear enough?
