### ISSUE TITLE
Changing the defaultLayout

### ISSUE THREAD

**Issue by ANEDev** [IdentityServer/IdentityServer3#1880]
Hey community, 

when I am adding some elements to the LoginPageLink but the default class looks terrible.
![bild 1](https://cloud.githubusercontent.com/assets/13555497/9810076/f3b926e8-586d-11e5-92f6-630ab681d620.png)

I would like to change the class of this elements for example by changing it to the "btn btn-primary". It's the class of the Login button. Is there any possibility changing the style like its shown in the following picture? If yes can you show it to my how to implement this?

![bild 2](https://cloud.githubusercontent.com/assets/13555497/9810142/8ae11b2a-586e-11e5-9f31-1619b83830b8.png)

**Comment by brockallen** [comment]
Read the docs: https://identityserver.github.io/Documentation/docsv2/advanced/customizingViews.html
