### ISSUE TITLE
Broken IIS performance counters "Current Anonymous Users" and "Current NonAnonymous Users"

### ISSUE THREAD

**Issue by LaoR-UA** [IdentityServer/IdentityServer3#1881]
Hi team.
Recently we have found strange behavior of IIS performance counters "Current Anonymous Users" and "Current NonAnonymous Users". Both of them are showing maximum allowed value (4 billion +) after first anonymous/non-anonymous requests respectively. 
STR:
1) Download examples from https://github.com/IdentityServer/IdentityServer3.Samples/
2) Host "MVC Authentication" example project under IIS.
3) Added IIS performance counters to perfmon (instruction: http://bradkingsley.com/basic-iis-performance-statistics/)
4) Do any request to identity server (in case of example switch to "Login" tab on site header)
4.1) "Current Anonymous Users" goes sky-high in a second. It decreases per each request to identity server. 
5) Pass authentication/authorization by entering correct credentials.
5.1) "Current NonAnonymous Users" goes sky-high in a second. It decreases per each authorization/logoff request to identity server.
See screenshot attached. All other sites behave correctly. I also wave second identity server installed on local machine called "Login" and its behavior exactly the same.
![counters](https://cloud.githubusercontent.com/assets/12445633/9811095/d2d18faa-587d-11e5-89fa-9382f47e0bfb.jpg)

Looks like just identity server somehow breaks up performance counters cause no actual performance issues detected and no real connections registered.

**Comment by brockallen** [comment]
I don't follow. IdSvr doesn't do anything with perf counters and we're OWIN hosted (not IIS hosted). Perhaps it's OWIN/Katana that is affecting your per counters.

**Comment by LaoR-UA** [comment]
Yes, I understand that. But it is definitely has something to do with Identity server. 
I added simple app just to test it as well as identity server.
app.Map("/identity", idsrvApp =>
                {
                    idsrvApp.UseIdentityServer(new IdentityServerOptions
                    {
                        SiteName = "Embedded IdentityServer",
                        SigningCertificate = LoadCertificate(),

                        Factory = InMemoryFactory.Create(
                            users:   Users.Get(),
                            clients: Clients.Get(),
                            scopes:  Scopes.Get()),

                        AuthenticationOptions = new Thinktecture.IdentityServer.Core.Configuration.AuthenticationOptions
                        {
                            IdentityProviders = ConfigureIdentityProviders
                        },
						RequireSsl = false
                    });
                });

	        app.Map("/test", builder =>
	        {
				HttpConfiguration config = new HttpConfiguration();
				config.MapHttpAttributeRoutes();
		        builder.UseWebApi(config);
	        });

I mapped Welcome Page to display just "Welcome" on request "../test":
public class StartController : ApiController
	{
		[Route("")]
		[HttpGet]
		public StartPageResult Start()
		{
			return new StartPageResult(HttpContext.Current.GetOwinContext());
		}
	}
And the result also follows your pattern:

**Comment by leastprivilege** [comment]
Maybe open an issue with Microsoft / Katana for that.

**Comment by LaoR-UA** [comment]
Even if I would do that I do not know what you used inside. And as I have shown above - simple applications hosted within another self-hosted application on Owin/Katana do not break anything. The problem is hidden deep behind "UseIdentityServerExtension" or one of its inner components/middlewares (they even could be developed by Microsoft or whatever). If you cannot point out anything special then looks like no other way except to debug your code.

**Comment by leastprivilege** [comment]
OK - I have no idea what might be causing this. So yes . please debug and let us know.

**Comment by leastprivilege** [comment]
any progress?

**Comment by Quethrosar** [comment]
this happens on our servers to.
