### ISSUE TITLE
External Login - OpenIdConnect button

### ISSUE THREAD

**Issue by JanWilczak** [IdentityServer/IdentityServer3#1883]
Hi,

can you please advise me on how I could remove OpenIdConnect button that appears in ExternalLogin section in LogIn page? It was added after I added IdentityManager in the Startup. Thank you in advance!

Regards,
JW

**Comment by brockallen** [comment]
If you don't want a button to appear for an external identity provider you can set the Caption of the middleware options to null. It will still be active, just not displayed.
