### ISSUE TITLE
Q: AccessToken usage

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3#1884]
I have a situation where a tenant has a suite of applications and the authorization logic (at least for now) is still all in these applications. So using IdSrv3 for the authentication only. 
This is fine for web apps.  
Not sure what the best approach would be for the mobile apps (or other API consumers). By the book these are to be secured using access tokens, yet by definition, in my scenario the authorization is still handled by the API and the API would "only" need to know the authenticated user. 

It seems like in my case on the API side (besides trusting the issuer) I'd need to validate that:
1. It is issued to the right client (already in the token).
2. It is issued to the right tenant (this is not in the token). The id_token doesn't have the tenant either, but there the state and nonce are verified to match the request to the response.
3. It is issued for the right scope(s) (already in the token) 
4. Know who the user is to grant local rights. The access token does include subject, but (especially for external users) this won't map to a local user name and I'll need to inject another claim in the access token for that.

Am I on the right track? 
How can I have the tenant and other user claims added in the access token?

**Comment by brockallen** [comment]
You can put the tenant into the access token as a claim.

**Comment by snothub** [comment]
Can you elaborate on adding tenant to access token? I'd like the same thing but adding the claim to the Claims collection of the resource scope makes no difference.
