### ISSUE TITLE
Q: id_token validation in multi tenant environment

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3#1885]
If I get it right, when validating the id_token, state is used to tie the request to the response and the nonce is to tie the response to the token. 
In multi tenant environment though it seems that the tenant must be validated on the receive too. Otherwise somebody could intercept the auth request, change the tenant and authenticate at the IdSrv. The application would then receive a "valid" response and token (state, nonce and client matching), but it would've been for a different tenant.

Am I missing anything?
What would be the best way to handle this - echo the tenant in the id_token and match it on the receive?

**Comment by brockallen** [comment]
If that's an additional requirement, then yes.
