### ISSUE TITLE
Reading headers from reqeust after authentication

### ISSUE THREAD

**Issue by pessimca** [IdentityServer/IdentityServer3#1886]
Hi,

I am now to Identity model and Server and started learning for my project. We have SSO on my company side and we have to use it for authentication. Created a sample project and with hard-coded authentication (in Pre-AuthenticationSync) by creating identity principle which working fine. Now, i need to ready http headers and pull the authenticated user info and apply into identity principle. I tried to read http headers like below:

var headers= HttpContext.Current.Request.Headers.GetValues("uid");
if (headers!= null)
id= headers.GetValue(0).ToString();

but it always getting empty. I tried same code on other web api project which working fine. Do we have any way to read headers on Pre-Autenthication Sync or client startup class. I appreciate your help if you can give me some thought to clear my issue.

thank you.

**Comment by pessimca** [comment]
Can i read same headers on client side startup as client web api's will be SSO enabled. I am trying with OpenIdConnectAuthenticationOptions but no success. Please share your comments.

**Comment by leastprivilege** [comment]
you need to inject the OwinEnvironmentService into your user service (simply by adding it to the ctor). This gives you access to the HTTP request.

**Comment by pessimca** [comment]
I am able to read headers after OwinEnivronmentService injected into UserService but i am missing some of header values which set by my SSO authentication.
* Can i read headers setup by SSO authentication on Id Server side?
* Is any possibility to set authentication token/identity on client side so Login screen removed?
* Which is best practices to generate authentication token on Client side or id server side?

Please help me to cover this.

Thank you

**Comment by leastprivilege** [comment]
I don't follow. Please explain.

**Comment by pessimca** [comment]
Here are more details:
We have internal authentication which will take care of Authentication process and add logged-in user information to headers. We will be reading headers for logged-in user information. This is how we are processing for normal web sites. Now, we are planning to user Identity Server to Authorization and Internal Authentication to Authentication. May request get authentication by Internal Authentication process and then request Authorization from Identity Server. 

As logged-in user info carried to Identity Server on Request headers, can we read headers on Identity Server and authenticated so login page will not be displayed. I am getting null when i read headers on AuthenticationController or UserServiceBase. but, i can read on my client side with below code:

Startup.cs:
========
 app.Run(ctx =>
            {
                ctx.Response.Redirect("/idm/");
                //reading logged-in user employee id
                employeeId = ctx.Request.Headers.Get("uid");
                Log.Information("Login====Value==>" + employeeId);
                return Task.FromResult(0);
            });

Authentication Controller:
=====================
var strings = HttpContext.Current.Request.Headers.GetValues("uid");

var userName = "Empty";
if (strings != null)
   userName = strings.GetValue(0).ToString();

UserServiceBase - PreAuthenticateAsync:
===================================
 owinContext.Request.Headers.ToList().ForEach(cc =>
 {
           Logger.Info("Key====>" + cc.Key.ToString() + " || Value==>" + cc.Value[0].ToString());
  });

I tried with OwinEnvironmentService but no success. Hope this will give you some understand and give your more details about the current issue which i am facing. Please let me know how can i use my company authentication into our model. 

appreciate your help.

**Comment by leastprivilege** [comment]
This will not work that way. The user service code runs after a redirect, so the headers are gone already. 

You could write some middleware that intercepts the request and writes the data to a cookie. That's what I would try.

**Comment by pessimca** [comment]
Thanks for your response. You mean to say, i need to write a middleware class on clientside which writes the data into cookie? Do we have any example which i can refer? Please share.

**Comment by leastprivilege** [comment]
No. At the idsrv side. No samples.

**Comment by pessimca** [comment]
I tried to read headers on AuthenticationController/AuthorizationController but getting null values. Can you plz let me know which is ideal place to read headers before redirect.

**Comment by leastprivilege** [comment]
What does null mean?

Are you using the source code or the nuget package?

I recommended to write a middleware that sits in front of idsrv to capture headers not on the controllers.
