### ISSUE TITLE
Log4Net provider does not create log file if it doesn't already exist when called from IdentityServer

### ISSUE THREAD

**Issue by codesilverback** [IdentityServer/IdentityServer3#1888]
If I wire up the log like this, using the Log4Net RollingFileAppender
 
    LogProvider.SetCurrentLogProvider(new Log4NetLogProvider());
    LogProvider.GetLogger(typeof (Startup)).Log(LogLevel.Info, () => "starting up");

I don't get any logging unless the log file already exists. 
If I create the empty log file, logging works fine.

If I delete the log file, then manually invoke log4net and log something, the file gets created:

    internal class Startup
    {
        private static log4net.ILog Log = LogManager.GetLogger(typeof (Startup));

        public void Configuration(IAppBuilder app)
        {
            Log.Debug("wat? wat!? wat?!?! ");

            LogProvider.SetCurrentLogProvider(new Log4NetLogProvider());
            LogProvider.GetLogger(typeof (Startup)).Log(LogLevel.Info, () => "starting up");

I get a nice log entry: 
    2015-09-12 08:55:52,667 [1] DEBUG STSPrototype.Startup [(null)] - wat? wat!? wat?!?! 
    2015-09-12 08:55:52,724 [1] INFO  STSPrototype.Startup [(null)] - starting up

The reason this is kind of a big deal is that I would rather not have to create empty log files for my apps when deploying.  I'd rather the logging framework magically create what log files I need.

I'm sufficiently ignorant of the magic that makes logging happen to be reluctant to claim this as a bug, but it certainly isn't what I expected to happen.

**Comment by codesilverback** [comment]
Adding log4net config for clarity:
 <log4net>

    <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
      <file value="c:\junk\STSPrototype\log.txt" />
      <appendToFile value="true" />
      <rollingStyle value="Size" />
      <maxSizeRollBackups value="10" />
      <maximumFileSize value="100KB" />
      <staticLogFileName value="true" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] - %message%newline" />
      </layout>
    </appender>
    <root>
      <level value="DEBUG" />
      <appender-ref ref="RollingFileAppender" />
    </root>
  </log4net>

**Comment by leastprivilege** [comment]
I have never used Log4Net - so I don't know the answer.

This is unrelated to IdSrv.

**Comment by leastprivilege** [comment]
`LogProvider.SetCurrentLogProvider(new Log4NetLogProvider());` is actually not needed at all.
