### ISSUE TITLE
How to get additional parameters in AspNetIdentityUserService?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1889]
Hello all, I need some additional parameter for example answer in AuthenticateLocalAsync method. I have tried System.Web.HttpContext.Current.Request.Form["Answer"] but failed?

**Comment by abcplex** [comment]
Adding this line in global.asax to make the line `System.Web.HttpContext.Current.Request.Form["Answer"]`  work,

        protected void Application_BeginRequest()
        {
            var f = Request.Form;
        }

**Comment by brockallen** [comment]
You can inject the IOwinEnvironmentService into your services to access the request info.

**Comment by imranbaloch** [comment]
Any example?
