### ISSUE TITLE
User claims vs user properties

### ISSUE THREAD

**Issue by vindberg** [IdentityServer/IdentityServer3#1890]
Having successfully integrated IdentityServer3.AspnetIdentity, EntityFramework, and IdentityManager with IdentityServer3 in once solution (Thanks for the great work!). Im wondering when is it appropriate to save user related data as user claims (AspNetUserClaims) vs properties on the user (AspNetUser).

In the UserServiceBase Im able to add extra claims by overriding GetProfileDataAsync, thus I can extract information from the user object and deliver them as userclaims when authorizing.

Im asking because im currently keeping the user.Name and user "name" claim in sync. But would rather have it in one place.

**Comment by leastprivilege** [comment]
ASP.NET identity gives you both ways - it is a matter of your personal taste.

**Comment by vindberg** [comment]
Okay, thanks for the answer.
