### ISSUE TITLE
How to access the Provider and ProviderKey?

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3#1891]
Using Asp.Net Identity, I noticed that after an External Login, AspNetUserLogins table contains the **LoginProvider** and **ProviderKey** as expected (e.g.  **Facebook**, **524234234** respectively).

My application needs this info to perform additional tasks using the provider's API. This means I need the key of the external user in order to use the API of the provider (e.g. Facebook API, get users picture API call, I need the Facebook user ID/key).

The only 2 ways I know to get info on a user from IdSvr3 is through **Claims**, or through **UserInfo** Endpoint.  Rather than fill up and bloat the access token with claims, it seems getting this info from UserInfo Endpoint is ideal.  But this info is not included in that response.  

By default, this is what is returned on that endpoint:
```javascript
{
      "sub": "1175f943-cf3f-4446-ab45-781763fc00a6",
      "preferred_username": "a477cdf9eb5a44c882120779137e5f17",
      "name": "David P"
}
```
How can that be customized? And is this the best way to get the provider info as described?

**Comment by brockallen** [comment]
You'd capture the access key for the external provider in one of the events/notifications/providers in the middleware once the user has been authenticated and returned from the provider.

**Comment by dapug** [comment]
ok, what I did is capture the "id" from facebook and add as a claim on the user, as seen here: https://github.com/IdentityServer/IdentityServer3/issues/1046

I then added "id" to the "profile" Scope claims so that it is returned when asking for the profile scope.  Not sure if this is best practice, but it seemed like a reasonable approach.

**Comment by leastprivilege** [comment]
seems ok to me.
