### ISSUE TITLE
EF config doesn't work on existing database

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3#1894]
Say I have a database already created but no EF tables for Clients and Scopes.  If I try to configure EF for clients/scopes to an existing database load them from InMemory as seen in Samples/EntityFramework/, I get this exception in Factory.cs line 37  (where db context is configured.

"The model backing the 'ClientConfigurationDbContext' context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269)."

This exception is when a Schema is in place.  So I remove the schema and it gets passed the ctor of the ClientConfigurationDbContext(), but then fails on line 41  if (!db.Clients.Any()), because it cannot find the clients table because NOTHING was created (still failed to create the context).

Note: it all works fine when NO database exists and it must create it as part of this process.

**Comment by dapug** [comment]
This same exception is happening with EF configured for Operational storage, when attempting to sign in and get a token. 

{"The model backing the **'OperationalDbContext'** context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269)."}

The issue with Clients and Scopes I could work-around by allowing it to configure things on a NEW database, but this I cannot work-around because the tables for Operational stuff are not created against a new DB, but an existing one.

Also BTW, Visual Studio also complains **RequireSslMiddleware.cs source not found**.

What can be done about this?  Why is this EF stuff not able to initialize itself against an EXISTING database?

**Comment by leastprivilege** [comment]
Any solution to this? @brockallen ? Otherwise we need to close as unresolved.

**Comment by dapug** [comment]
I'm investigating this further right now. I just hit this again, and will let you know what I find.

**Comment by dapug** [comment]
ok, still not sure exactly what is causing this, but it's quite interesting.  I have this project set up to use Sql/EF for configuration and users, as mentioned above.  I point my known good IdSrv to known-good DB, everything is fine.  I have another DB set up with the exact same tables, schema (pefect match when running a compare on the DB), and I simply change the Connection String, then when I nav to the discovery doc, it throws this:

```
"Message":"An error has occurred.","ExceptionMessage":"An error occurred when trying to create a controller of type 'DiscoveryEndpointController'. Make sure that the controller has a parameterless public constructor.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\App_Packages\\LibLog.4.2\\LibLog.cs:line 0\r\n   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request) in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\App_Packages\\LibLog.4.2\\LibLog.cs:line 0\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\App_Packages\\LibLog.4.2\\LibLog.cs:line 0","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"An exception was thrown while executing a resolve operation. See the InnerException for details. ---> The model backing the 'ScopeConfigurationDbContext' context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269). (See inner exception for details.)","ExceptionType":"Autofac.Core.DependencyResolutionException","StackTrace":"   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in...

```

**Comment by brockallen** [comment]
I don't know why it behaves like this, but in my experience EF sometimes has issues depending on how you create the DB. If you let it auto create it, then you can't use migrations. And if you use migrations then you need to create it with the update-database PS command.

**Comment by dapug** [comment]
How I got here was:

-IdSvr auto created the DB.
-I filled in some client info, got IdSvr operational, works great
-I did a Schema compare and Data Compare and created a copy of the DB
-I point IdSvr to this new DB, and it chokes as mentioned.

There must be a difference between the two databases that the Compare tools cant show.

**Comment by brockallen** [comment]
It's how the migrations table is created. 

-Brock

**Comment by dapug** [comment]
SOLUTION:  

    DROP TABLE dbo.__MigrationHistory

What appears happening is, for an _unknown_ reason, EF thinks it needs to create this table.  Once that happens, you're doomed.  My scripted tables for IdSvr work fine, until EF decides to "own" it.  I am not sure how to repro the situation that causes IdSvr/EF to think it needs to track migration.

I would feel better about pushing this to production if I knew why it created the table.  We certainly cannot have that happen unexpectedly.

**Comment by dapug** [comment]
Last bit of info here:  I *think* this is how I got into this state:

 - On first launch, I pointed IdSrv to an EXISTING database (had some other tables in it already). This probably triggered it to generate _MigrationHistory table when it auto-created the tables it needed. IdSrv worked fine at this point.
 - I deleted all the tables from said DB, but NOT _MigrationHistory (i didn't notice it)
 - I re-add all the IdSrv tables myself from a script (not the same as EF creating them)

Now at this point, EF is really mad and IdSrv stops working despite the tables being legitimate (perfect schema match).  Deleting the _MigrationHistory table at this point solves it because EF again becomes unaware that there are changes it needs to track (thinks it is a fresh start).

For any DBA managing IdSrv in an existing system and database (which is most everyone, since no project other than "hobby" stuff is going to rely on auto DB generation), you should be aware of this. For instance, we script and create our DB in Sql Azure, we do not allow the apps to auto-generate the database.  This can be bad if EF "finds out" you've done that.  :)  So be sure the IdSrv tables exist with the exact required schema BEFORE you run it, or else it will try and auto-generate something and you'll be doomed.

**Comment by brockallen** [comment]
Yes, this sounds legit and echos what I mentioned earlier about EF not being happy if you try to use auto generated schema vs. schema generated from migrations scripts -- those two things seem to disagree on what goes into that migrations table.

I'm sure it'll all be fixed in the next version ;)
