### ISSUE TITLE
CorsPolicyService never gets called

### ISSUE THREAD

**Issue by tonyeung** [IdentityServer/IdentityServer3#1895]
Error I'm getting
```
2015-09-13 19:07:43,351 [5] WARN  IdentityServer3.Core.Configuration.Hosting.CorsPolicyProvider [(null)] - CORS request made for path: /AuthServices/Acs from origin: https://SamlUri but rejected because invalid CORS path
```

I'm using an implementation `public class CustomCors : ICorsPolicyService` and I put some logging to see what happens. The constructor gets called when the app starts, but the `IsOriginAllowedAsync` never gets called. it just goes straight to the cors policy provider instead. 

I've tried to use the client's `AllowedCorsOrigins` instead of registering a policy service but still no dice. I've read some post that says I'm supposed to be able to set cors on the `IdentityServerOptions` but I don't think it applies to the newest version.

What am I doing wrong?

My factory registration

            var factory = new IdentityServerServiceFactory();

            factory.CorsPolicyService = new Registration<ICorsPolicyService>(new CustomCors());
            factory.ClientStore = new Registration<IClientStore>(new ClientStore());
            factory.ScopeStore = new Registration<IScopeStore>(new ScopeStore());
            factory.UserService = new Registration<IUserService>(new UserService());

CustomCors class:

        public class CustomCors : ICorsPolicyService
        {
            private static log4net.ILog logger = log4net.LogManager.GetLogger("CustomCors");
            public CustomCors()
            {
                logger.Info("CTOR");
            }

            public Task<bool> IsOriginAllowedAsync(string origin)
            {
                logger.Info("ORIGIN FROM CustomCors");
                logger.Info(origin);
                return Task.FromResult(true);
            }
        }

**Comment by tonyeung** [comment]
I don't mind debugging it myself, but I'm not sure when or how the service gets called. i just need a file and line number.

**Comment by leastprivilege** [comment]
/Acs is not a CORS path that we handle. Why is that called?

**Comment by tonyeung** [comment]
KentorIT/authservices. this happens right after kentor unpacks the saml response

**Comment by leastprivilege** [comment]
I think that's a red herring - Kentor does not do Ajax calls.

We've seen this behavior before . e.g. Chrome seems to send CORS header if if it doesn't need to. All the log entry is saying is, there's a CORS request to an endpoint that is not one of our "CORS enabled" endpoints - thus the the CORS policy service is not invoked.

**Comment by tonyeung** [comment]
oh i see, okay, thanks
