### ISSUE TITLE
ASPNETIdentity, CustomUserService, CustomGrants for additional User Credentials

### ISSUE THREAD

**Issue by SaschaHerrmann** [IdentityServer/IdentityServer3#1896]
Hi,

i am using IdSrv3 for internal mvc/api applications.

Systems: 
Windows Domain, Active Directory, ADFS
IdentityServer3 with WSFedration and Domain Login for MVC/Web API

Used Software:
Old Database Application with own IdentityManagement, not connected to Active Directory
This old software has an SDK which we can access via WCF/Web API. But we need the user credentials for the database logon with Login and Password.

I want to somehow combine the Windows User with the User of this old application to use those database credentials on the Ressouce Web API for the old App. 
My initial idea was to provide a scope with a ScopeClaim containing the credentials as Claims.

I managed to extend the ASPNETCustomIdentity user from your example with the credentials for the old app. I try to include the credentials in the identity token provided by the IdSrv3.
But i think the identity token is not the right place for these additional credentials. I would preferably seperate the ASPNetIdentity from the old app since not every connected MVC-Application needs access to the old database. 

I am asking for an idea how to solve this. Could a CustomGrant be used to give clients with the "oldApp-Scope" a token with the credentials for the old app which would be decoded in the Web Api for the clear text credentials? I somehow do not like the idea to extend the ASPNETIdentity user for every old system with custom credentials.

I hope it is clearer what i have in mind. Thanks for any help.

Original:
 Authenticating with ADFS. This ist working fine.
We have an additonal older internal application which unfortunately is not able to authenticate via Active Directory. It has its own authentication method with username and password. 
I want to combine the windows domain user with this others system user. For that i use aspnetidentity with an extended customUser. Following your examples AspNetIdentityASPNet5/EntityFramework/CustomUserservice (pretty much all your examples).
I just cannot get my head around CustomGrants. I searched this page but i do not get it.
Is it adviced to add the additional Credentials to the customUser and ask the user at first registration (CustomUserService) for them? 
Can a customGrant used for those additional credentials and saved somewhere except at the ASPNetUser? 

Thanks

**Comment by leastprivilege** [comment]
I am not sure I understand the question.

**Comment by SaschaHerrmann** [comment]
Updated the original post.

**Comment by leastprivilege** [comment]
yea thats ugly either way. You should transmit those credentials in the back end only - so custom grant is better than identity token.
