### ISSUE TITLE
Dependency Injection Instancing

### ISSUE THREAD

**Issue by RemotecUK** [IdentityServer/IdentityServer3#1898]
Would it be possible to provide an example of how to set the instancing mode of an instance registered via Identity Server's dependency injection?

I have checked the documentation which states there is a `Mode` property on the Registration class however setting this caused a compile error. e.g.

        var x = new Registration()
        {
            Mode = 
        };

I have also looked in the latest samples but the dependency injection sample does not have an example of doing this as far as I could see.

Looking at the definition of the Registration class, I could not see a Mode property.

Happy to be corrected or pointed to the correct sample.

**Comment by leastprivilege** [comment]
Have a look at Registration<T>

**Comment by leastprivilege** [comment]
sorry - I meant `Registration<T>`
