### ISSUE TITLE
Scope length should be configurable or allow further extensible request validation.

### ISSUE THREAD

**Issue by Cephei** [IdentityServer/IdentityServer3#1899]
Currently you cannot set the max length for authorize request scopes.

See: Constants.MaxScopeLength 

According to https://tools.ietf.org/html/rfc6749#section-3.3  there is no specific size for this string length and it would be prefferable if the hosting authZ server could configure this accordingly.  I looked into implementing a custom ICustomRequestValidator but this is executed further along in the authorize request pipeline to be of any use.

Please consider this for a future iteration.  Thanks and great work on IdSrv3!

**Comment by leastprivilege** [comment]
Is the current length too restrictive for you?

**Comment by Cephei** [comment]
It's something that I could see being a potential issue, albeit not a show-stopper.  Take for example Google's use of URIs as scopes (https://developers.google.com/drive/web/scopes).  For a large API with many resources and/or the use of scopes as privileges (readonly, write per-resource), I could see this being problematic for some.

300 chars just appeared to be an arbitrary number that *may* be better suited as a default value rather than a constant limit.

**Comment by leastprivilege** [comment]
OK. We will discuss.

**Comment by leastprivilege** [comment]
opened new issue for it.
