### ISSUE TITLE
Separation of authentication server and API / login form to different servers

### ISSUE THREAD

**Issue by sunsided** [IdentityServer/IdentityServer3#1900]
I'm currently diving into ASP.NET 5 (vNext beta 7/8-nightly) with IdentityServer3 2.0.1 and having some trouble finding my way. My team and I are developing a website that should be protected by means of OAuth and OpenID Connect tokens and our goal is to separate the sign-in / token creation logic (the authentication server) from the actual usage, our website and REST API. While the authentication and API servers are implemented in C#, the frontend server is not.

So far, IdentityServer3 seems to be a sane choice. We would, however, like to outsource the login logic, so that accesses to the `/login` endpoint are actually rendered by our frontend server (the one the HTML/JavaScript guys hack together). In other words, I don't want the forms behind `/login` to be part of the IdentityServer3 server itself, as this would require the frontend logic and design to be split across two different domains.

I have seen that I could implement a custom `IViewService` following the [Customizing Views](http://identityserver.github.io/Documentation/docsv2/advanced/customizingViews.html) documentation topic, but it seems that this only allows to return document bodies and - I assume - we should likely send a redirect header rather than providing an HTML result.

**Comment by leastprivilege** [comment]
The whole point of "authentication as a service" and SSO is that the authentication logic and flow is centralized.

With the concept of partial logins (or even implementing your own "login applications") you can do whatever you want in terms of custom flows and look & feel. But we designed this to happen "on" the identityserver.

**Comment by sunsided** [comment]
But wouldn't that mean that in essence the whole site would have to be implemented on the IS3 server? With the account page I'm basically restricted to have the whole user profile management there and, with that, sort of the rest of the site? Maybe I'm just failing to see the "typical" use case.

**Comment by sunsided** [comment]
That said, we *do* want centralized authentication, but need the associated forms and views from another server.

**Comment by leastprivilege** [comment]
then you could only implement your "login application" as katana middleware itself and plug it into idsrv. But you need to implement a secure protocol between both parties.

**Comment by sunsided** [comment]
Is there an example flying around by any chance that could point me in the right direction?

**Comment by leastprivilege** [comment]
Have a look at e.g. Microsoft's authentication middleware - you'd need to implement something like a mini-OAuth implementation (similar to code flow probably).

I have no sample for that.

**Comment by immanuel-rekursv** [comment]
+1 for this. I've been brute forcing myself for more than a month now wanting to have a custom login that would cater to the "Mother Application". I can't get around going out of the Authorization flow (then login if not authenticated) happening. I just want the user to be challenged and the Authentication Ticket and Cookie to be issued. Just like how facebook does it in their primary login page.

**Comment by immanuelrosal** [comment]
+1 for this. I've been brute forcing myself for more than a month now wanting to have a custom login that would cater to the "Mother Application". I can't get around going out of the Authorization flow (then login if not authenticated) happening. I just want the user to be challenged and the Authentication Ticket and Cookie to be issued. Just like how facebook does it in their primary login page.

**Comment by leastprivilege** [comment]
progress?

**Comment by sunsided** [comment]
Wasn't this exactly what me and @immanuelrosal were asking for? :grin: As for me, I simply don't use IdentityServer3 anymore.
