### ISSUE TITLE
Identity Server with SAML

### ISSUE THREAD

**Issue by pessimca** [IdentityServer/IdentityServer3#1901]
Hi

I am looking some solution to use SAML 2.0 with Identity Server. Can anyone had any chance to create sample so i can quickly refer to get understanding. Found few articles and saying that we have to use KentorIT AuthServices to implement SAML2.0 into our Identity Server. I appreciate any help.

Thank you

**Comment by leastprivilege** [comment]
Saml idp or gateway.

**Comment by pessimca** [comment]
Do we have any doc or examples which i can refer to get better understanding? Please share.

**Comment by leastprivilege** [comment]
IdSrv support external SAML Idps via the Kentor middleware. Anders from Kentor wrote a blog post about that.
