### ISSUE TITLE
IdentityServer3 as sub-application or externalize authentication

### ISSUE THREAD

**Issue by vish-k** [IdentityServer/IdentityServer3#1902]
Hello,
I want to use OAuth2 Auth Server functionality of IdentityServer3 (Authorization Code, Implicit &  Resource Owner grants). 
I am trying to deploy IdentityServer3 as sub-application of an existing MVC application (not owin) that uses WIF and have written a custom identity provider (owin) that tries to read Principal from WIF authentication from parent app. However, I am not able to extract user principal in custom auth handler from ClaimsPrincipal.Current or HttpContext.Current.User. It is always null. My plan is to extract user principal from parent apps WIF authentication and add the claims to OWIN context.
I am deploying IdentityServer3 as sub-application (instead of using ws-fed identity provider) to avoid creating another RP on STS side.
Can you pls comment on following questions - 
1. Will IdentityServer3 work with above approach where auth is offloaded to parent app ? If so how can I extract claims/principal set by parent app WIF (non-owin) in the (owin) sub application ?

2. If above approach works, how will authentication for resource owner grant be handled ?

3. If above approach does not work, is there a way to share the RP with parent application ? so far it has not worked because of the single reply URL for ws-fed at STS.

4. Are there any examples for implementing User & Client Services using API instead of using entity framework ?

Thanks for your help.

**Comment by leastprivilege** [comment]
No. IdentityServer must do its own authentication. That's the whole point.

**Comment by vish-k** [comment]
Thanks for quick reply.

In above approach IdentityServer does have it's own authentication with the custom auth middleware that reads claims inherited from parent app authentication. I would really prefer to share the federation set up by (existing) parent app so we can add auth server without changing any STS. Anyway, pls let me know if it's not the proper approach.

Also, can you pls provide pointers on client services impl using (existing) API instead of entity framework. I could not find any example for custom client services.

**Comment by leastprivilege** [comment]
don't understand the question - you mean a custom client store? You need to implement IClientStore.

**Comment by vish-k** [comment]
Thanks. I'll check on IClientStore.
