### ISSUE TITLE
Secure mode on all IdSvr cookies

### ISSUE THREAD

**Issue by kylegalbraith** [IdentityServer/IdentityServer3#1904]
So I set the secure mode to Always, however, it appears that only the idsrv cookie has the secure flag set. The xsrf and session cookies do not appear to have it, is this because I am on an older version of identity server (1.6.1) or is this by design?

**Comment by brockallen** [comment]
Good question -- I'll look into it.

**Comment by leastprivilege** [comment]
@brockallen could you look into that - or close.

**Comment by brockallen** [comment]
Fixed on dev. Session, last username, signin/out message, and antiforgery cookies now all honor the `SecureMode` setting.
