### ISSUE TITLE
IdentityServer3 in multi-region SaaS application

### ISSUE THREAD

**Issue by programmer-pragmatic** [IdentityServer/IdentityServer3#1905]
We are building a SaaS web application which will deployed in cloud (Window Azure). It will have multiple instances in multiple regions.
All instances will be independent and will not share anything between them.
Each instance will be used by multiple tenants.
Instances name will be like NA.MyWebApp.com (for north America region), EA.MyWebApp.com (for asia region) and so on.
Each instance will have its own Identity server.
Tenant's user can go to their home instance and log in.
But client also wants a common url like 'login.MyWebApp.com' which can be used by all usesr from any tenant to login to his respective instance.

We are planning to implement something similar to following:

We can define a traffic manager in Azure, which will work on proximity. We will use 'login.MyWebApp.com' for it.
Whenever user tries to login in using 'login.MyWebApp.com', url will be resolved to the nearest instance. For ex. If he is log in from US region, this url will be resolved to NA.MyWebApp.com.
We can use ResourceOwner flow in this. When user will enter credentials and click on login button. Application will search user's home instance by looking into database. This database will be replicated in each instance which will store the tenant-instance mapping.
User credentials will be sent to his home instance's identity server and in return, system will get token.
System will generate a cookie and user will be redirected to his home instance.
Domain of the cookie will be set to '.MyWebApp.com' so that it can be shared for all instances (which are using same domain but different subdomain).
These are some initial thoughts and may not be correct/feasible. It would be great if you share your thought on this.

**Comment by leastprivilege** [comment]
sorry - didn't have to time to look into it. progress?
