### ISSUE TITLE
Thinktecture.IdentityServer.Host.Config.UserService cannot be used as type parameter 'TImpl'

### ISSUE THREAD

**Issue by ANEDev** [IdentityServer/IdentityServer3#1906]
Hey community,

I am trying to implement a WebHost with IdentityServer3. I just want to insert UserServiceExtensions but in the following image there is a error message which I can't unserstand. 

![bild 1](https://cloud.githubusercontent.com/assets/13555497/9871156/de7c793e-5b91-11e5-9353-85ae7f228a64.png)

"The type 'Thinktecture.IdentityServer.Host.Config.UserService' cannot be used as type parameter 'TImpl' in the generic type or method 'Thinktecture.IdentityServer.Core.Configuration.Registration<T,TImpl>'. There is no implicit reference conversion from 'Thinktecture.IdentityServer.Host.Config.UserService' to 'Thinktecture.IdentityServer.Core.Services.IUserService'"

For comprehension I did not bind the IdentityServer3 via nuget packages into my project, I downloaded the IdentityServer3-master and added it to my solution. I think that could be the problem because when I'm adding the nuget packages  to the project, the error message disappears. But I need the IdentityServer3-master because I want to influence some functions in it.

Is there a resolution for this problem?

**Comment by leastprivilege** [comment]
I am not sure what the problem is - but be aware that we can only really help you out if you use the nuget package. Otherwise we cannot know which modifications you did.

**Comment by ANEDev** [comment]
Ok I found the reason why I this error raised all the time. It was a problem with the IdentityServer3.AspNetIdentity. It declares its own references and one of them lead to a conflict.
