### ISSUE TITLE
Clients and allowed scopes

### ISSUE THREAD

**Issue by indranilatcal** [IdentityServer/IdentityServer3#1907]
Hi

Clients have an "allowed scopes" property. They appear to be a list of scopes a client is allowed to request. But what I find is, once a scope is listed there and it is requested by a client, it gets sent down as a scope claim with the access token. Is it possible to enforce some policy (checks) to only send down the scope claim to the requesting client when some conditions are met? What options do we have for that? Is it that we have to implement a CustomClaimsProvider (e.g. inherit the DefaultClaimsProvider & override its GetAccessTokenClaimsAsync method)?

Indranil

**Comment by leastprivilege** [comment]
That's a weird requirement - but yes - in the claims provider you have full control over the emitted claims.
