### ISSUE TITLE
Q: Long-lived access token vs. refresh token for mobile app

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3#1908]
For better user experience I don't want to ask mobile users to login to IdSrv every time. 
It seems the recommended way in this case is to use long-lived reference tokens. 
So say I issue a 30 day token and the mobile app is good for up to 30 days. And in 30 days the user will have to authenticate with IdSrv again and get another reference token (no refresh on these...right?). 
Meanwhile a refresh token can be revoked at any point and this would be the measure taken should a user become inactivated, have his right changed or when a device is lost etc.  

Is this correct?

Which flow would then fit the mobile app scenario best? 
I'm reading conflicting opinions on this one. 
On one hand mobile devices are generally deemed not as trustworthy for storing client secrets, which would eliminate the code flow. On the other hand the implicit flow would instead use the return url to confirm the client, which is not as secure and perhaps even less in mobile. 
Any recommendations? 

Thanks.

**Comment by ankur--bhatia** [comment]
We are using the refresh token to keep the customer logged in. The access
token has a short life (<1 hr) and refresh token is single use with a long
life.

In regards to flow to use in mobile -- We are using the resource owner
flow. However it has shortcomings.
1) less secure like you mentioned
2) if the customer moves on the web journey -- then he has to log in again.

In regards to the flow
We are exploring the same. I dont think resource owner flow is working for
us. It was the simplest flow to start with.
If you are authenticating a customer -- then hybrid flow can help. In the
sense, the authorization code is issue to the mobile app. But the
authorization code is then used by the application server to get the access
token and refresh token. This then can be saved on the mobile phone. This
way -- customer sign in using the idSrv login screen. And Client secret is
with the application server and not in mobile app.

But I am open for suggestions form the community.

**Comment by brockallen** [comment]
either way works (either long lived reference tokens or refresh tokens). IMO there's more effort needed in the client code for the refresh token scenario.

**Comment by Peperud** [comment]
@brockallen So which one would you recommend?
Using access tokens though, the user would have to re-authenticate with IdSrv to get a new token, while in the refresh tokens scenario, they potentially might not have to see the login screen ever again.
Am I right?

**Comment by leastprivilege** [comment]
You could issue a long lived reference token. The user does not need to re-authenticate, and he/you can revoke it at any point in time.

**Comment by leastprivilege** [comment]
https://vimeo.com/131635255

**Comment by Peperud** [comment]
@leastprivilege Thanks Dom, excellent video :+1: Looks like I'm on the right track.
Just to confirm - when you say:

> You could issue a long lived reference token. The user does not need to re-authenticate, and he/you can revoke it at any point in time.

...you mean that the user won't have to re-authenticate because the token lifetime would be potentially more than the expected lifespan of the mobile device, not because the reference token can be renewed without user re-authenticating, right?

**Comment by brockallen** [comment]
The long lived reference access token is how long you want to make it before the user has to re-authenticate.

**Comment by binarymist** [comment]
How are long lived reference access tokens made per user?

**Comment by fingermark** [comment]
@leastprivilege in your video you recommend reference tokens for mobile, but would it be acceptable to use for SPAs?  I don't understand the point of using a refresh token and short TTL access tokens when you also need immediate revocation -- it seems a reference token is all that's needed here, but I don't understand the security implications of having a long TTL reference token in an SPA.

**Comment by leastprivilege** [comment]
Sure - they are always an interesting option when you need full control over lifetime. Especially for SPAs since they cant use refresh tokens.

**Comment by fingermark** [comment]
@leastprivilege I was unaware that SPAs shouldn't use refresh tokens.  Is that because there's no safe place to store them?

**Comment by leastprivilege** [comment]
you'd need to store both the refresh token and the client credentials in the browser yes.

**Comment by jahansha** [comment]
I'm using Authorization Code Flow for a mobile client with refresh token. Should I avoid  storing the access token in between calls and instead get a new one every time..
Is there a safe way to safely  store access token on a native client or a JavaScript client?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
