### ISSUE TITLE
IIS to serve up static assets

### ISSUE THREAD

**Issue by ayoung** [IdentityServer/IdentityServer3#1909]
I'm running ID3 in the same OWIN pipeline as another web app and I would like to have IIS serve up all my static content, but ID3 requires RAMMFAR=true which effectively does not allow IIS to serve static files. If I set RAMMFAR=false, then all the embedded assets in ID3 will not be served up.

Is there a work around for this?

Thanks.

**Comment by leastprivilege** [comment]
IdSrv needs RAMMFAR because of the embedded assets. You'd need to separate the two apps.
