### ISSUE TITLE
Why is the access_token so long with OpenID connect?

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3#1910]
In the Samples, MVC CodeFlowClient requests and gets a very short access token, like "insdfihf8hwffneihfrferuhferfgj".  But then the MVC Implicit example using OpenID connect gets this monster sized token:  "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsT..."  (about 1kb in size!)

BOTH of these tokens work when calling the service.  So this left me the following questions:

1) why is it so big with OpenID (or likewise, how is the small one so small, what is in it?)
2) how did the Sample Service get so much claim data from the small access token?  (did it make an additional call to the ID server behind the scenes?)

**Comment by leastprivilege** [comment]
One is a JWT, and one a reference token.

**Comment by dapug** [comment]
ok, I totally get it now. And this is specified in the Client record. Reference is new to me, I hadn't used it in IDSvr v1.  Cool.

So it means when I call my service, it needs to call IDSvr in order to validate or get claims. Is there a way to intercept that call so I can point it to, say, a cache lookup instead?

**Comment by leastprivilege** [comment]
That's built into the token validation MW
https://identityserver.github.io/Documentation/docsv2/consuming/tokenValidationMiddleware.html
