### ISSUE TITLE
Case Insensitive check for Audience/Issuer?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#1911]
In my Identity Server I am doing,

            var options = new IdentityServerOptions
            {                
                SigningCertificate = Certificate.Get(),
                Factory = factory,
                AuthenticationOptions = new AuthenticationOptions
                {
                    IdentityProviders = ConfigureAdditionalIdentityProviders,
                }
            };
            app.UseIdentityServer(options);

In my client I am using Microsoft JWT library to validate the JWT. The problem is that some users getting exception due to case sensitive check of  audience. Can we disable it? If not can we set the audience in IdentityServerOptions? I wanna to make everything in small case both in client and server.

**Comment by leastprivilege** [comment]
Audience is derived from the issuer name. You can set that in the options.

**Comment by abcplex** [comment]
@leastprivilege  You mean if I set IssuerUri? Correct?

**Comment by leastprivilege** [comment]
yes
