### ISSUE TITLE
Issue when runAllManagedModulesForAllRequests set to true

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3#1913]
Hi 

My site has loads static file resources, and now I have got it integrated with Idsvr, everything works fine except all these static file now going through the asp.net pipelines because i have to turn on the evil flag runAllManagedModulesForAllRequests to true, this is a hit to my site's performance 

I know there is solutions to fix it by hosting all static files on a separate static domain etc.. but the complexity of doing that is out of our scope and , it's a infrastructure change which is beyond my control.

So I started to think if I can manually create those embedded idsvr static assets as physical files and save them under my site, and it doesn't work because some idsvr static asset (e.g. checksession.html) generated based on data dynamically.

Then I start thinking why cant those embedded asset have extensionless name?? like "../asset/appFormPostResponse"??

This should work with runAllManagedModulesForAllRequests=false right?

Am I the only person facing this challenge? if someone else got a good solution please share

Thanks

Ming

**Comment by leastprivilege** [comment]
IdSrv needs RAMMFAR. If that is not compatible with the surround IIS application - you need to separate them.

**Comment by jeremy001181** [comment]
Thanks for your reply, can you see my suggestion about the extensionless url cause any issues?

**Comment by leastprivilege** [comment]
why is idsrv not a web app on its own?

**Comment by jeremy001181** [comment]
it's because the way we choose to replace our legacy identity provider , instead of building a new app with idsvr from scratch, we choose to upgrade from it and put idsvr on it, it might be it's not a good approach but it is quite common right?

**Comment by leastprivilege** [comment]
not soo common - but OK. RAMMFAR is a limitation here. sorry.

**Comment by jeremy001181** [comment]
but if idsvr change to use extensionless url for assets , then we can get around this limitation right?

**Comment by leastprivilege** [comment]
maybe - we'd need to try that (or rather you). Then we'd need to figure out if that would be a breaking change or not (which influences timing).

**Comment by leastprivilege** [comment]
closing it - feel free to report back.
