### ISSUE TITLE
QUESTION: A sample with IdentityServer3 with MVC 6 and Bearer Token authentication

### ISSUE THREAD

**Issue by bastienJS** [IdentityServer/IdentityServer3#1914]
Does there exist a sample that uses the following technologies:

- IdentityServer3
- MVC6 (vNext)
- Bearer Token authentication 

I can not find one. I am glad for every link or recommendation :-)

**Comment by leastprivilege** [comment]
http://leastprivilege.com/2015/07/22/the-state-of-security-in-asp-net-5-and-mvc-6-oauth-2-0-openid-connect-and-identityserver/
