### ISSUE TITLE
ConfigureIdentityServerBaseUrlExtension - When origin not present

### ISSUE THREAD

**Issue by dylanmorley** [IdentityServer/IdentityServer3#1916]
Hi, 

Something we've noticed during our testing is there are some intermittent SecurityTokenInvalidIssuerExceptions like so, where xxx is an IP address. 

Exception type: System.IdentityModel.Tokens.SecurityTokenInvalidIssuerException
Exception message: IDX10205: Issuer validation failed. Issuer: 'https://xxx.xxx.xxx.xxx'. Did not match: validationParameters.ValidIssuer: 'null' or validationParameters.ValidIssuers: 'https://identity-env96.projects.rnd.com'.

This is because we did not explicitly set PublicOrigin on IdentityServerOptions and ConfigureIdentityServerBaseUrl is called during our application start up. When the application starts without PublicOrigin set it means it is looking at the “Host” header it is using the value from that first request.

If this request is automated (for example, perhaps it is from an azure load balancer component) and it doesn’t include the header, then from that point on the IdentityServerBasePath will be the IP address not the host value that we expect.

Obvious fix - set the PublicOrigin. But perhaps to avoid any possibility of issues, this should be a required property and throw a 'You must set the PublicOrigin for your Identity server' exception if not - thoughts?

Thanks

**Comment by leastprivilege** [comment]
That's a known issue

https://github.com/IdentityServer/IdentityServer3/issues/1619

Until fixed you need to set the public origin - or the issuer name

**Comment by dylanmorley** [comment]
Ah - sorry for the dupe.

**Comment by brockallen** [comment]
Is this still an issue? If it's a dup, let's close it please.
