### ISSUE TITLE
Using Okta as IdP within IdentityServer3 v2

### ISSUE THREAD

**Issue by dahlsailrunner** [IdentityServer/IdentityServer3#1917]
Hi -- 

I'm trying to configure IdentityServer3 (v2) to honor Okta as an Identity Provider (they only support SAML tokens).  I have configured a developer account on Okta and created an "app" within that.  Then I have added the ws fed owin package to my id server project and configured the following:

    var oktaOptions = new WsFederationAuthenticationOptions
    {
        AuthenticationType = "okta",
        Caption = "Okta",
        SignInAsAuthenticationType = signInAsType,
        MetadataAddress = "https://mydevinstance.oktapreview.com/app/mydevapp/sso/saml/metadata",
        Wtrealm = "urn:testidentity"
    };

    app.UseWsFederationAuthentication(oktaOptions);

I am getting an error: "IDX10803: Unable to create to obtain configuration from:"... the correct url for metadata

If I go to the URL it returns me metadata properly.  Any ideas on what I'm doing wrong or haven't set up properly?

Thanks - 
Erik

**Comment by leastprivilege** [comment]
WS-Fed does WS-Fed ;) You need SAML.

Try Kentor - https://coding.abel.nu/2015/01/saml2-for-thinktecture-identityserver-3-with-kentor-authservices/

**Comment by dahlsailrunner** [comment]
DOH!  Shows you what I know.  Thanks for setting me straight.

**Comment by brockallen** [comment]
Okta also supports WS-Fed.
