### ISSUE TITLE
How to enable trust between multiple identityserver3

### ISSUE THREAD

**Issue by programmer-pragmatic** [IdentityServer/IdentityServer3#1918]
We are planning to give two deployments for our application. One in US and another in China. Primary reason for multiple deployment is performance. Both deployment will have their own Identityserver (inbuilt with the application).
Each deployment will have their own users. Which means Chinese users can go to china.myapp.com and login and US users can go to us.myap.com and login into app.

But there is an additional requirement that user can go to any url (us.myapp.com and china.myapp.com) and still login to their respective app.

Now what I can imagine is, If Chines user go to US's site, he will be taken to US's identity server. This server will check if user belongs to US or not. In case of Chinese user, US's identityserver will hits Chinese server's API and checks the credentials. It will generate a token (and create a cookie) and redirect user to Chinese site.

But Chinese application is trusting its own identity server and not US's one. Can we set trust between US identityserver and Chinese identityserver, So that token/cookie generated by any identityserver is acceptable by another identity server.

**Comment by leastprivilege** [comment]
Yes - register the trusted identity server as an external idp. You can use the OpenID Connect middleware for that.

**Comment by programmer-pragmatic** [comment]
Can you please share some documentation/sample link for the same.

**Comment by leastprivilege** [comment]
Check the docs on external identity providers.

— 
cheers
Dominick Baier


On 18 Sep 2015 at 08:16:06, programmer-pragmatic (notifications@github.com) wrote:

Can you please share some documentation/sample link for the same.

**Comment by programmer-pragmatic** [comment]
Thanks Dominick,

I found the documentation. But it works differently than what I expect. If i register identity provider as external identity provider, It appears as hyperlink in external login div. Although it does allow to login using that identity provider, but user has to click it.

I want to handle it internally using some custom logic (which will check where user belongs to). In other words, I don't want to redirect user using 'user action (click)'. I want to validate him internally using code. Also SSO should be enabled with his original identity provider (which authenticates him internally).

Thanks In Advance

**Comment by leastprivilege** [comment]
You can't have both "internal" and SSO.

You can contact the other provider programmatically using the resource owner flow or you redirect (maybe automatically without showing the loging screen at all). Then you get SSO

**Comment by programmer-pragmatic** [comment]
If I contact other provider pragmatically (using resource owner) then I would not be able to get SSO on 'other provider' (which is the actual one who is authenticating). I will get SSO on provider where I entered my credentials. I want SSO on both the provider, which I feel is not feasible :( And I need tenant value to redirect it to other server. Which I don't want to do. If I redirect user without checking the credentials, any user can find out my list of tenant supported by my application.

**Comment by programmer-pragmatic** [comment]
If I can set the domain of the cookie (created by Identityserver), I can achieve this. I know we can set the cookie path, but can we also set its domain, so that it can be use with other subdomain?

**Comment by leastprivilege** [comment]
This is not recommended - every authentication session should live in its own domain. There will be side effects down the line.

We don't allow that.
