### ISSUE TITLE
DefaultClaimsProvider

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1919]
I have a number of user claims added to user. One of the resource scopes is set to include one of those claims in the access token. However, DefaultClaimsProvider adds all of those claims as soon as one of them is defined on the resource scope, which to me sounds odd.

I realize I could override this behavior, but since it's a minor thing, wouldn't [this code](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/Default/DefaultClaimsProvider.cs#L121)
````
outputClaims.AddRange(claims);
```` 
be better off like so
````
outputClaims.AddRange(claims.Where(c => additionalClaims.Contains(c.Type)));
````

**Comment by leastprivilege** [comment]
You are supposed to add your claims in the user service GetProfileData method.

Or am I missing something?

**Comment by snothub** [comment]
Right, of course. I've been back and forth with some multi-tenant stuff that I totally missed I wasn't doing the right thing in GetProfileData. I'll close this and post a new question on that. Thanks
