### ISSUE TITLE
[Question] Supporting multiple identity-types

### ISSUE THREAD

**Issue by sellotape** [IdentityServer/IdentityServer3#1920]
I have authentication and authorization working well for a client app (client credentials) and a user (implicit), and am using ResourceAuthorization on an API that the client talks to.

I now need to support multiple types of identity; let's say Customer and Employee.  Each will need to display a slightly different login screen, although for now just a different title would be fine.  Users of both identies will talk to a common API, and be authorized in a common way.

I was unsure where to double-up for this, and wanting to keep this all within a single IdentityServer instance, I have gone down the route of mapping multiple instances of IdentityServerOptions into the pipeline, like this:

	app.Map("/identity/customer", c => { c.UseIdentityServer(customerOptions); });
	app.Map("/identity/employee", c => { c.UseIdentityServer(employeeOptions); });

I currently also have a 3rd instance for client-credential flows::

	app.Map("/identity/root", c => { c.UseIdentityServer(rootOptions); });

I've got this working pretty well, sharing most of the options, stores and services, except IUserService, across the instances.  I'm using partially-customized templates for the login view, and using IdentityServerOptions.SiteName to distinguish to the user which type of identity they are authenticating as.  The latter doesn't feel quite right, but works for now.

I'd just like to sanity-check this to see whether this is what was intended by the authors?  Is there a better way?

**Comment by brockallen** [comment]
So your client app must trust 2 different copies of IdSvr? That's not normally how you do things -- have IdSvr broker the two and provide a claim that differentiates the types of users.

**Comment by sellotape** [comment]
Is there an example of this type of usage available?  Particularly showing what the client must do to specify whether the user they want authenticating is an employee or a customer (in my example, anyway), and how to display 2 different login views depending on the user type.

I guess I'm not clear on what there are two of on the IDSvr side, to support the two IUserServices, given that each IdentityServerOptions only has one.

**Comment by brockallen** [comment]
Why do you need 2 diff login screens? What's different about what the employee enters vs. the customer?

**Comment by brockallen** [comment]
Anyway, if you do need them different, then you can do HRD -- look at the HRD sample and partial login docs in the user service.

**Comment by sellotape** [comment]
Employees login using a username and password, and customers using an email address and password, so we would need to display something different to each.  I know it seems like a minor difference, but it's required.

At the back end there are completely separate credential stores for each type, and we certainly don't want the IUserService trying both for each attempt, so we need to know what type of user the client is authenticating.

There are other wrinkles I didn't add because I was trying to keep the example simple, and that I was going to ask in a separate question, for instance that the customer additionally needs to be able to authenticate using different identifiers, e.g. as well as uid/pwd, also PIN, and 2-factor.  Each identifier type would confer different claims; e.g. more for 2-factor, "normal" for uid/pwd and fewer for PIN.

**Comment by brockallen** [comment]
So yea, either custom HRD in one IdSvr, or if you want to get more complex you can have 1 IdSvr as a gateway (where you still have HRD) and then 2 other IdSvrs that each do the user service against the Db you need to use. Again, this is all to shield your app(s) from needing to juggle the 2 different IdPs.
