### ISSUE TITLE
Tenant information in Userinfo endpoint

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1921]
I would like UserInfoEndpointController to add tenant info from access token it receives and pass it on to UserInfoResponseGenerator that would then include it in the principal claims and make it available in GetProfileDataAsync in my user service.

I've already done this locally and things are working fine, would that be something to consider as a pull request?

**Comment by brockallen** [comment]
You have the subject -- isn't that enough? Meaning, are your subjects cross-tenant?

**Comment by snothub** [comment]
Yes, subjects come from different tenants and subject value can be same in
various tenants, so I'd need to know which one to go to.
18. sep. 2015 4.52 p.m. skrev "Brock Allen" <notifications@github.com>:

**Comment by brockallen** [comment]
That sounds like the wrong way to go about it (unless I'm missing some context). Normally subject is the unique ID for the user. If your token service is multi-tenant then I'd expect the same human logging into 2 different tenants to get 2 different subject identifiers.

**Comment by snothub** [comment]
Well, I'm trying to implement different user stores as tenants, but as long
as subject equals user name, those stores could contain same user names and
therefore conflict with each other.

Should I rather differentiate between subject and user name and have
subject contain a tenant prefix or something that indicates origin?

Thanks
19. sep. 2015 3.14 p.m. skrev "Brock Allen" <notifications@github.com>:

**Comment by brockallen** [comment]
username is usually specific to a tenant, yes. making subject cross-tenant makes your life easier :)

**Comment by snothub** [comment]
Good advice there. Thanks, that helped.

**Comment by LinqBeast** [comment]
What can you do here if your user name is not cross-tenant?
