### ISSUE TITLE
Multiple hosted clients connecting to the server

### ISSUE THREAD

**Issue by fahouassou** [IdentityServer/IdentityServer3#1922]
Hi Here is my scenario.

I have an identity server.   identityserver.com

I have an API website that is authentication and authorization required. This API is considered as a client for the Identity Server. 

I host this API on multiple IIS servers. Each having it s own clientid/clientsecret to allow him authenticate.

For each API server i have some users that can access with username/password

A user on IIS server xxxx.com should not be allowed to access yyyy.com.

Everything works perfect when the user try to access each IIS API separately.

But as an admin i can open xxx.com and yyy.com on the same browser and i break this rule.
I access yyy.com on one tab and xxx.com on other tab. it says that i am authenticate with user of yyy.com

Is there something i make wrong in my design ?

Thanks

**Comment by leastprivilege** [comment]
progress?
