### ISSUE TITLE
Customize authorization, token endpoints

### ISSUE THREAD

**Issue by vish-k** [IdentityServer/IdentityServer3#1924]
Hello, 
Is there a way to customize authorization, token Endpoints ?

**Comment by brockallen** [comment]
Have you read the docs?

**Comment by vish-k** [comment]
:) yes. I only found option to enable/disable particular endpoint with EndpointOptions. May be I missed it but I need to change the endpoint from default connect/authorize etc myown/authendpoint etc. Is it possible ?

**Comment by brockallen** [comment]
These are the extensibility points to look into:

https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html

**Comment by vish-k** [comment]
Sorry, I didn't understand your suggestion. 
Are you suggesting to implement ITokenService etc to change token endpoint ? I do not want to change the functionality of generating  codes/tokens... I only need to use different endpoint URL for the same functionality, 
If IdentityServer3 does not allow changing of endpoints from /connect/token, connect/authorize etc to something else then could I use IIS alias/rewrite url module ?  Are there any issues using IIS URL rewrite module ?

**Comment by brockallen** [comment]
Oh, you simply want a different URL/path? The best thing we have to offer is you can use `Map` in the OWIN pipeline to put a prefix on it.

**Comment by vish-k** [comment]
Thanks for confirming. Do you see any issues using custom alias for standard IS endpoint with IIS URL rewrite module?

**Comment by brockallen** [comment]
Never tried, so no idea if it'll work. One thing that might be a problem is that our metadata endpoint that issues metadata about our URLs -- not sure it'd know your custom mapping. 

Why do you feel the need to change the URLs? I'd like to understand better.

**Comment by leastprivilege** [comment]
all set?

**Comment by vish-k** [comment]
Yes. Thank you ! Appreciate your help.

Haven't tried IIS rewrite url module yet but this question can be closed.

On Sat, Oct 3, 2015, 5:45 AM Dominick Baier <notifications@github.com>
wrote:

> all set?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3/issues/1924#issuecomment-145231150>
> .
>
-- 

Regards,
   Vish
