### ISSUE TITLE
Setting an identityServer as external provider to another one

### ISSUE THREAD

**Issue by programmer-pragmatic** [IdentityServer/IdentityServer3#1925]
Hi,
I have created two identityservers. I want to set my second identityserver (https://identityserver2:555) as external identity provider to first one.

Once coded, it appears on login screen inside external providers. Clicking on it take to identityserver2. I am able to successfully log in there. But It does not redirect me to the page that I wanted to access. It redirects me to the page which I have mentioned in redirectUrl. Apart from that when I try to access the protected page again, it shows the login page (from identity server 1) again (also the external identity provider link). 

Clicking on identity server2 again does not show login page and redirect me to redirectUrl. Which means I have successfully login there. But somehow token from server is not used to access protected resource.

public static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var option = new OpenIdConnectAuthenticationOptions()
            {
                Authority = "https://identityserver2:555",
                ClientId = "mvc",
                Scope = "openid profile roles sampleApi",
                RedirectUri = "https://IdentityClient:444/",
                ResponseType = "id_token token",
                SignInAsAuthenticationType = signInAsType,
            };
            app.UseOpenIdConnectAuthentication(option);
        }

        public void Configuration(IAppBuilder app)
        {
                var option = new IdentityServerOptions
                {
                    SiteName = "Embedded IdentityServer",
                    SigningCertificate = LoadCertificate(),
                    Factory = new IdentityServerServiceFactory()
                                                    .UseInMemoryUsers(Users.Get())
                                                    .UseInMemoryClients(Clients.Get())
                                                    .UseInMemoryScopes(Scopes.Get()),

                    AuthenticationOptions = new AuthenticationOptions
                    {
                        //EnableLocalLogin = false,
                        IdentityProviders = ConfigureIdentityProviders
                    },
                };
                app.UseIdentityServer(option);
        }

**Comment by leastprivilege** [comment]
* client redirects to idsrv1
* idsrv 1 must redirect to idsrv2 (external provider)
* idsrv2 redirects back to idsrv1
* idsrv1 redirects back to client

**Comment by programmer-pragmatic** [comment]
I understand. Am I missing something (in code)  to achieve the same result? I was expecting this to be done by code shared above

**Comment by programmer-pragmatic** [comment]
Please help me in this. I could not find any working sample for this scenario.

**Comment by programmer-pragmatic** [comment]
I tested out Google (as external identity provider) and it worked well. It seems steps are different to use Identityserver3 as external identity provider or there might be some bug.

**Comment by programmer-pragmatic** [comment]
My bad. It was my mistake. It is working fine now. Thanks for your support.

Please close this issue.

**Comment by venkatrv** [comment]
I am also trying the similar scenario. what was the problem in your code and how it got resolved?

**Comment by snothub** [comment]
@programmer-pragmatic would you care to comment on the details of what the issue was here so others who have the same issue can get a good answer? Thanks
