### ISSUE TITLE
How can I troubleshoot the reason my identity server is down

### ISSUE THREAD

**Issue by adrashpulDA** [IdentityServer/IdentityServer3#1926]
Hello,

I configured identity server and identity manager hosted in the same app and everything was fine until I made a refactoring.
Wherever I go to /idm or /core I get 404. Tried to configure logging but nothing in there.

Appreciate any help.

**Comment by brockallen** [comment]
This is not much info to go on...

**Comment by adrashpulDA** [comment]
Never mind, I just forgot to reference Microsoft.Owin.Host.Systemweb. Removed it when cleaned up unnecessary packages.
Sorry for confusion.
