### ISSUE TITLE
Serilog logging

### ISSUE THREAD

**Issue by stephendrew** [IdentityServer/IdentityServer3#1927]
Hello,

Thanks for the awesome software.

I was wondering - and excuse me if this is a simple question - is it possible to have direct all the logging produced by IdentityServer into a specific Serilog ILogger;  I'd rather not use the global logger.

Thanks

**Comment by leastprivilege** [comment]
I don't think so - ping @damianh

**Comment by stephendrew** [comment]
The reason I ask is that I want to host two web apps within one process - one providing the identity server itself, and another providing Windows Authentication server (based on the Windows Authentication sample) but I want them to log to distinct locations.

Can you suggest an alternative solution to this (based on Serilog)?

My service host does support loading them up as separate app domains, which may be the way to go I guess....

**Comment by leastprivilege** [comment]
Statics are per app-domain - not process.

**Comment by stephendrew** [comment]
Yes, so this is a workaround for me.  Although it prevents me running the two apps without the separate app domains.

**Comment by leastprivilege** [comment]
I don't follow. You can host both in the same process (app pool). But since they are in different app domains the statics don't matter.

**Comment by stephendrew** [comment]
I'm running self hosted not in IIS...I have a service host that can run service modules - either in the main app-domain, or in isolated app-domains.  Therefore, I can only seem to split out the logging for the isolated app-domain case;  otherwise all processes using the IdentityServer code will be logging to the global logger.

**Comment by leastprivilege** [comment]
Yes - I think that's how liblog works. @damianh ?
