### ISSUE TITLE
When to use UseIdentityServerBearerTokenAuthentication

### ISSUE THREAD

**Issue by programmer-pragmatic** [IdentityServer/IdentityServer3#1928]
Please accept my apologies if this question sound dumb.
In case we are using IdentityServer3, why would we use UseIdentityServerBearerTokenAuthentication to protect our WebAPIs. We would better use 'UseOpenIdConnectAuthentication' with 'Implicit', 'Authorization code' or 'Hybrid flow'. That way we can utilize login/logout UI as well.

Can anyone share any usecase where using 'UseIdentityServerBearerTokenAuthentication' can be helpful (assuming that webAPI needs to be exposed to other client as well).

In case someone wants to use ResourceOwner flow then (I guess) he can live with 'UseIdentityServerBearerTokenAuthentication', and for any other kind of flow, he will have to use 'UseOpenIdConnectAuthentication'
Thanks In Advance

**Comment by leastprivilege** [comment]
The OpenID Connect MW is not for APIs - it is for web UIs (like MVC).

**Comment by programmer-pragmatic** [comment]
We have a single project (for MVC client and webAPI resouces). for MVC client, we will store token in cookie. Views can directly fetch data from webAPI using javascript. In this case, cookie will also travel to server side. 

1. Should we extract access_token from cookie on server side and set it to header (whenever a request is made from js)?
2. Or shall we pass id_token/access_token to client side and set them in request header at client side?

Thanks in Advance

**Comment by leastprivilege** [comment]
You should not use cookies for APIs - because XSRF

**Comment by programmer-pragmatic** [comment]
Out WebApi will use 'Bearer token authentication'. We will use cookie for our MVC application. And to protect from XSRF, we will be using, AntiForgery token.
In case of request coming to webapi from our MVC, we will first validate our cookie with AntiForgery token. And then we will extract Access_Token to invoke WebAPI. I dont think there should be any issue in this approach. What do you say?

**Comment by leastprivilege** [comment]
so why do you use tokens at all then?

**Comment by programmer-pragmatic** [comment]
We need to expose our WebAPI for external applications as well. To implement authorization at webAPI level, we need to implement OAuth 2.0. 
We don't want to use multiple technology stack to implement authentication at MVC level and authorization at webAPI level. That is why we are inclined towards OpenID Connect. We will use UseOpenIdConnectAuthentication for our MVC client. And IdentityServerBearerTokenAuthenticationOptions for WebAPI's (As shown in your 'MVC authentication & WebAPIs'.

In case of our primary application (MVC), when user will be authenticated with Identity server, we will store access_token, Id_token and refresh_token in cookie. After login, whenever browser make a request for webapi, we will fetch tokens from cookie and set in header.

This way, we would not have to manage token at client side.

**Comment by leastprivilege** [comment]
Then I would use cookies for MVC and tokens for Web API.

Use the host protection feature in web api to protect your APIs from the cookies

**Comment by programmer-pragmatic** [comment]
I appreciate your prompt replies.

You are right, cookie can be problematic. I missed out one point, currently we have used ValidateAntiForgeryToken attribute on our webapi action method. We will have to get rid of these (if we want to expose our webapi to other application). Which will make them prone to CSRF.

Now the point is, User logged-in in MVC application by entering user name and password. System returned the token and we stored them in cookie (for MVC application only). Should we pass access_token to client side, so that if browser make a request to web-api, it can pass token along with request.

**Comment by leastprivilege** [comment]
Yes - e.g. render the access token in a view as a JS variable.

**Comment by programmer-pragmatic** [comment]
Fine, We will pass access_token to client side. But where will I store refresh token? I cannot pass it to client side, right?

**Comment by leastprivilege** [comment]
browser session storage e.g.

refresh tokens are not designed for browser clients. Maybe check my talk:
https://vimeo.com/131635255

**Comment by programmer-pragmatic** [comment]
I had watched this video. By the way, I am a big fan of your work :)

I understand 'refresh token' are not designed for browser clients. Then which options should I use in this use case, where some of my pages uses MVC controller and other uses webAPI?

**Comment by programmer-pragmatic** [comment]
I got an idea. I will check at client side if access token is about to expire. If it is, I will hit my MVC server to get me new access token. In this hit, at server side, i will fetch refresh token from cookie, request new access token and return it. This way I dont have to store is at client side

**Comment by leastprivilege** [comment]
did you get the part where i mentioned "reference tokens"?

**Comment by programmer-pragmatic** [comment]
I watched that video again. You are inclined to use "reference token" in place of "refresh token". I have two queries:

1) Wouldn't validating a token from external identity server (which in internal in my case) in each request add some latency to it?
2) Assume, system assign a reference token to a user for 1 day. Now admin removes some roles from that user after 1 hour. Should system triggers some event to revoke the reference token? And is it possible? And user will have to login again at this point?

But If we were using refresh token (valid for a day), system will release access token with a validity of an hour. After an hour, system will get another access token, which will reflect updated role info. And user will not have to login again. Does it make sense?

**Comment by leastprivilege** [comment]
yes it does make sense - now you know your options. choose the one that fits the best for you.

wrt long lived tokens and claims - the general rule of thumb is - don't put claims into tokens that frequently change.

**Comment by programmer-pragmatic** [comment]
Thanks a lot. We are good to close it. But please shed some light on point 1 as well.

**Comment by leastprivilege** [comment]
wrt 1 - if you would do that on every request - probably yes. Depends on your network ;)

Our middleware has a feature to cache the claims - e.g. for 5 minutes (configurable).

**Comment by kosa-gyula-77** [comment]
@leastprivilege ,

Re your answer _render the access token in a view as a JS variable_

Isn't it a vulnerability to expose any token to JS in the user agent?

Thanks.
