### ISSUE TITLE
How to send data body using HttpClient

### ISSUE THREAD

**Issue by mohannadkhirallah** [IdentityServer/IdentityServer3#1929]
hi all
im trying to make a post request an i want to send body on that request using httpClient ?
please can you help me guys ?

**Comment by loctanvo** [comment]
What are you trying to do? From where to where? And posting what?

**Comment by mohannadkhirallah** [comment]
in the client side im trying to access an api and i want to create a message body ?
how can i do that 


![identityserverrpsot](https://cloud.githubusercontent.com/assets/10743014/10020905/f0db6f74-614d-11e5-8aa0-f73146cd5189.png)

**Comment by leastprivilege** [comment]
By using the PostAsync method. Check the HttClient docs.
