### ISSUE TITLE
Web Api, angularjs and refresh tokens

### ISSUE THREAD

**Issue by olandese** [IdentityServer/IdentityServer3#1931]
Hi, 
I'm building a browser based application which consist in a angularjs client and a web api backend. My existing users should be able to login using their username and password. 
I want to be able to authenticate the users and getting *directly* an access token which can be used by the angularjs to request api. (No auth codes etc..)
I want to use refresh tokens too. 
Which flow should I use? Implicit or Resource Owner?
Reading the documentations I came across the fact that with the implicit flow refresh tokens are not supported, but using the resource owner credentials flow I should use a client secret which in my case I think it's not safe because the angularjs app is public.
What should I do?

**Comment by programmer-pragmatic** [comment]
You should better use Implicit flow. And why do you need refresh token? If you use oidc-client, It will get you new access token using hidden iframe.

**Comment by olandese** [comment]
I want to use refresh token because my access token have a short validity (5 mins i.e.) but I don't wont to annoying the users the login again all the time(obviously). And with refresh tokens I'm also able to invalidate the token if needed when requesting a new one. 
About the oidc-client, it's my lack of knowledge about this, I didn't know the existence of it. 
With oidc, how can the angular app request a new access token  without a refresh token?

**Comment by programmer-pragmatic** [comment]
- You can get new access token without login again. Since there will be active login session with identity server, you are already logged in. redirect happens behind the scene, so user will not notice this.
- You can invalidate token with refresh token.
- you can find oidc-client here https://github.com/IdentityModel/oidc-client

**Comment by olandese** [comment]
thank you very much! 
just another question, I'm digging since days in the Idsrv source code, but I didn't saw anything where a login session is marked as active, can you explain me how does this works? I always thought that an active sessions was due to the existence of a valid access token.

**Comment by programmer-pragmatic** [comment]
I have not gone through the code, but I guess idsrv generate a auth cookie and as long as that cookie is valid, you are considered as logged in. In case of 'Resource Owner', you dont get this feature.

**Comment by brockallen** [comment]
Looks like you got your answer. I'll close. Feel free to open more issues when you have more questions.
