### ISSUE TITLE
[OIDC.JS] Token stored in local storage - XSS scripting

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#1932]
Hello,

When we store token in local storage is it some how protected against XSS scripting and identity theft? 

I made small test and copied content of local storage from one browser into another (both on different PC's so no way that I still got the same localstorage) and I was authenticated as original user.

So it's just a matter of finding XSS vulnerability and stealing localStorage to act as another user.

Or maybe I am wrong?

**Comment by leastprivilege** [comment]
Yes - true.

Use CSP to protect against XSS.

**Comment by pawepaw** [comment]
Ok so there is no other way to protect it against XSS? We just need to make our application XSS proof.

**Comment by leastprivilege** [comment]
it is called CSP.

**Comment by pawepaw** [comment]
Ok thanks.

**Comment by rafkuc** [comment]
Dominck, if we are using external library which renders inline scripts into our pages, enabling CSP may not work with it. Do you have any other suggestions around this topic or it is either your oidc.js library or the inline scripts?
