### ISSUE TITLE
Accessing HttpConfiguration

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1933]
As described in [issue #609](https://github.com/IdentityServer/IdentityServer3/issues/609), the HttpConfiguration is not made accessible. We'd like to add a few items to the MessageHandlers as well as our own IExeptionLogger implementation to the Services collection.

Any suggestions as to how to address this?

**Comment by leastprivilege** [comment]
we don't expose any of those - you need to use the source code version in that case.

**Comment by leastprivilege** [comment]
Once you start making changes to the internals - we can't support you anymore. Just a fyi.

**Comment by snothub** [comment]
I know, I really don't want to go down that path. But thanks, I suspected that was the only way. Maybe a thought for future version, then.

**Comment by snothub** [comment]
Guys, would it be possible to open up for this somehow in an official release (see original post)? I wouldn't be asking if it wasn't really important.

Thanks

**Comment by slaneyrw** [comment]
Would also be nice to get access to the dependency resolver.  You have hidden/reimplemented every single interface that could be of benefit - IHttpController, IContainer

**Comment by leastprivilege** [comment]
Since WebApi is internalized - we cannot expose those objects.

**Comment by snothub** [comment]
Ok, then how about allowing to send in something in options object to be
put in the httpconfiguration?

Den fre. 2. sep. 2016, 07.46 skrev Dominick Baier <notifications@github.com

**Comment by leastprivilege** [comment]
That would require creating adapter objects - and where do start - and where do you end.

Come up with a proposal and we can discuss it.

**Comment by snothub** [comment]
Thanks, I will try to do that. Have a few other things going on first though.

**Comment by brockallen** [comment]
Any update?

**Comment by snothub** [comment]
Not yet. :( Can you give me a few more weeks before closing?

**Comment by brockallen** [comment]
Yea, that's fine.

**Comment by snothub** [comment]
We found a way around this using custom middleware, so no need to get to the configuration object.
