### ISSUE TITLE
Use owin extentions from ApiController

### ISSUE THREAD

**Issue by Zenuka** [IdentityServer/IdentityServer3#1934]
I saw in [this question](https://github.com/IdentityServer/IdentityServer3/issues/1140) that you need to host your MVC controller "under" idsrv map. Is it possible to achieve that for an ApiController as well?
I tried it of course but unfortunately it's not as simple as making sure the route is under the same name as idsrv. Any suggestions?

**Comment by leastprivilege** [comment]
Yes - this also works for web api. Attribute routing is the easiest for that...and make sure the web api MW comes after idsrv in the pipeline.

**Comment by Zenuka** [comment]
When the WebApi is placed after idsrv in the owin pipeline my routes aren't resolved (404 errors)

**Comment by cedartreeworld** [comment]
I also have a similar scenario where I’m using ApiController (Web Api host, not MVC). I want to be able to silently log in the user after successful registration, and then to redirect back to the client app’s home page (RedirectUri).  I realize there’s an option to add a registration link to the login page using LoginPageLinks but that does not satisfy my requirement - I need to provide direct registration page for users.

On the client’s home page I have a “Sign Up” link that points to register.html which makes a form post to the registration api controller end point, with the username and password. Please note that the registration controller exists under the same url as the Identity Server host.

I’ve looked at the OWIN Extensions but not sure how to get this working. I could pass in the client_id as well into registration controller but I’m uncertain as to how to obtain a valid SignInMessage for the Redirect url. Here’s a snippet of what I’m attempting to do after successful registration:

    AuthenticatedLogin login = new AuthenticatedLogin()
    {
        IdentityProvider = IdentityServer3.Core.Constants.BuiltInIdentityProvider,
        Subject = userId,
        Name = model.Username,
    };
    Request.GetOwinContext().Environment.IssueLoginCookie(login);

    SignInMessage signInMessage = Request.GetOwinContext().Environment.GetSignInMessage(signin_id...);
    return Redirect(signInMessage.ReturnUrl);

 
Is this scenario possible to achieve?

Can anyone point me in the right direction?

**Comment by loctanvo** [comment]
@cedartreeworld Could [this discussion](https://github.com/IdentityServer/IdentityServer3/issues/1139) help you?

**Comment by Zenuka** [comment]
@leastprivilege I also tried it with a clean solution.
StartUp.cs:
```c#
public class StartUp
{
	public void Configuration(IAppBuilder app)
	{
		ConfigureIdentityServer(app);
		ConfigureWebApi(app);
	}

	private void ConfigureIdentityServer(IAppBuilder app)
	{
		app.Map("/identity", idsrv =>
		{
			var options = new IdentityServerOptions
			{
				Factory = new IdentityServerServiceFactory()
					.UseInMemoryClients(new Client[] { })
					.UseInMemoryScopes(new Scope[] { })
					.UseInMemoryUsers(new List<InMemoryUser>()),
				RequireSsl = false
			};

			idsrv.UseIdentityServer(options);
		});
	}

	private void ConfigureWebApi(IAppBuilder app)
	{
		var webApiConfig = new HttpConfiguration();
		webApiConfig.MapHttpAttributeRoutes();
		app.UseWebApi(webApiConfig);
	}
}
```
And a TestController.cs:
```c#
[Route("identity/test")]
public class TestController: ApiController
{
	[HttpGet]
	public string Get()
	{
		var owinContext = Request.GetOwinContext();
		return owinContext.Environment.GetIdentityServerHost();
	}
}
```
When I run it like this, the TestController is never hit and I get a 404 in the browser. When I configure the WebApi before idsrv, the controller is hit but I get a KeyNotFoundException ('idsrv:IdentityServerHost') on the return statement.

**Comment by leastprivilege** [comment]
You need to run in the idsrv pipeline - 

so map the Web API to /identity as well (or identity/xxx) in the OWIN pipeline

**Comment by Zenuka** [comment]
Ofcourse, makes total sense...
For anyone with the same problem, I solved it in the StartUp.cs like this:
``` c#
public class StartUp
{
	public void Configuration(IAppBuilder app)
	{
		ConfigureIdentityServer(app);
	}

	private void ConfigureIdentityServer(IAppBuilder app)
	{
		app.Map("/identity", idsrv =>
		{
			var options = new IdentityServerOptions
			{
				Factory = new IdentityServerServiceFactory()
					.UseInMemoryClients(new Client[] { })
					.UseInMemoryScopes(new Scope[] { })
					.UseInMemoryUsers(new List<InMemoryUser>()),
				RequireSsl = false
			};

			idsrv.UseIdentityServer(options);

			ConfigureWebApi(idsrv);
		});
	}

	private void ConfigureWebApi(IAppBuilder app)
	{
		var webApiConfig = new HttpConfiguration();
		webApiConfig.MapHttpAttributeRoutes();
		app.UseWebApi(webApiConfig);
	}
}
```
And left the TestController as it was.

**Comment by cedartreeworld** [comment]
Thank you @loctanvo, for pointing me to #1139, which was actually very helpful. I’ve decided to also host the registration form on the same login view. I’m able to use IssueLoginCookie to directly sign in the user after a successful registration. Thanks again for your help.

**Comment by siva524** [comment]
I am using below method to redirect to AAD in apicontroller but it is failing to do so.Is there any way to redirect properly.I am using below one.          HttpContext.Current.Request.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = "/" }, OpenIdConnectAuthenticationDefaults.AuthenticationType);
