### ISSUE TITLE
Use external identity provider for Authentication only and append access_token internally

### ISSUE THREAD

**Issue by programmer-pragmatic** [IdentityServer/IdentityServer3#1935]
Hi,

I am using an external identity provider (Google) along with my own identity server. 
My identity server works well and provide id_token and access_token.
Since roles are stored in my database and google cannot provide that, I want to use google for authentication (id_token) only. Once validated from google, I want to fetch roles my database (for authenticate user) and create an access_token for it (Before redirecting to client).
I believe it should be possible. If yes, please help me.

Thanks in advance

**Comment by davidmrichter** [comment]
I had the same challenge.
You need to write your own UserService.
In there you can do Claimstransformation.
Look for the UserService Samples..

**Comment by programmer-pragmatic** [comment]
Thanks davidmkrichter,

I will check UserService Samples.
