### ISSUE TITLE
ResourceOwner not working with ext Idp only

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1937]
Hello,

I have an instance of identityserver which is connected to some external Idp. Local Login is disabled so that everyone has to login over the external Idp.
With Hybrid Flow the identityServer communicates with the external Idp. 
With ResourceOwner Flow the identityserver does not trigger to the external Idp. instead Exception is thrown:

private async Task<ValidationResult> ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)
        {
            Logger.Info("Start password token request validation");

            // if we've disabled local authentication, then fail
            if (_options.AuthenticationOptions.EnableLocalLogin == false ||
                _validatedRequest.Client.EnableLocalLogin == false)
            {
                LogError("EnableLocalLogin is disabled, failing with UnsupportedGrantType");
                return Invalid(Constants.TokenErrors.UnsupportedGrantType);
            }
            

Here is the calling code:

var client = new OAuth2Client(
				new Uri(Configs.IdentityAccessServiceURI + Configs.IdentityAccessServiceToken_EndPoint),
				"ReportingClient",
				"secret");

			return client.RequestResourceOwnerPasswordAsync(username, password, "ReportingService").Result;

It seems that with ResourceOwnerFlow external Idps are not supported by identityServer.
Any hint?

**Comment by leastprivilege** [comment]
Ext. IdPs can be only used with the browser based flows.

**Comment by davidmrichter** [comment]
Now in our scenario we have service to service communication. And we rely solely on the external Idp. 

What can we do?

**Comment by leastprivilege** [comment]
Well - you can implement that as a custom grant. What's the external idp you need to talk to?

**Comment by davidmrichter** [comment]
Its for the time being an instance of identityserver.

**Comment by davidmrichter** [comment]
custom grant with LocalAuthentication eventually? Then I need to enable locallogin in our identityserver too.
Is it then not better to enable local login in general and disable it for the browserflow Clients?

**Comment by leastprivilege** [comment]
no - a custom grant - and it that validator you do the programmatic communication with the ext. idp.

**Comment by davidmrichter** [comment]
programatically one can achieve everything in code. 
so what is then "better"?

Custom grant which accesses ext Idp(via UserSErvice.AuthenicateLocalAsync) and locallogin is per se disabled for all clients; 
users have to use custom grants for request

or

local login enabled, all browserbased flows have localloginenabled = false,  Access to ext. Idp via UserSErvice.AuthenicateLocalAsync
users can use standard flows(grants) instead of custom grants

**Comment by leastprivilege** [comment]
You ALWAYS need to write a custom grant handler for programmatic access to ext ips - how else would we know how to talk to an arbitrary idp?
