### ISSUE TITLE
Invalid Scope issue

### ISSUE THREAD

**Issue by devscott** [IdentityServer/IdentityServer3#1939]
I have been tasked on getting a demo of using IdentityServer3 (version 2) working with a javascript client. Our client is written in aurelia, and I am using the aurelia-auth plugin for the token-based authentication. 

I am running across an error message invalid_scope within the log. Based off of other questions and documentation, my scopes are both explictly declared, but am still getting the error. Any help would be greatly apprecated

Client Configuration (aurelia-auth)
```javascript
var config = {
    //our Aurelia App Address
    baseUrl : 'http://localhost:9000/',
    providers: {
        localIdentityServer: {
            clientId: 'aureliaAppDev',
            authorizationEndpoint: 'https://localhost:44300/core/connect/authorize/',
            url: 'auth/localIdentityServer',
            redirectUri: window.location.protocol + "//" + window.location.host + "/index.html",
            scope: ['openid','profile'],
            scopePrefix: 'scope',
            scopeDelimiter: ' ',
            requiredUrlParams: ['scope'],
            display: 'popup',
            popupOptions: { width: 1020, height: 618 }
        }
    }
}

export default config;
```

IdentityServer Client:
```c#
new Client
            {
                //Resource Owner Flow Client (our web UI)
                ClientName = "aureliaAppDev",
                Enabled = true,

                ClientId = "aureliaAppDev",
                Flow = Flows.AuthorizationCode,
                AccessTokenType = AccessTokenType.Jwt,
                AllowedScopes = new List<string>
                {
                    StandardScopes.OpenId.Name,
                    StandardScopes.Profile.Name,
                    StandardScopes.Email.Name
                },
                AccessTokenLifetime = 3600,
                RequireConsent = true,
                AllowRememberConsent = true,
                RedirectUris = new List<string>
                {
                    "http://localhost:9000/index.html"
                },
                PostLogoutRedirectUris = new List<string>
                {
                    "http://localhost:9000/index.html"
             
		}
}
```

IdentityServer Log Entry:

iisexpress.exe Information: 0 : 2015-09-23 11:57:33.938 -05:00 [Information] Start authorize request
iisexpress.exe Information: 0 : 2015-09-23 11:57:33.956 -05:00 [Information] Start authorize request protocol validation
iisexpress.exe Error: 0 : 2015-09-23 11:57:33.974 -05:00 [Error] Invalid scope: "scope"
iisexpress.exe Information: 0 : 2015-09-23 11:57:33.988 -05:00 [Information] {
  "Category": "Endpoints",
  "Name": "Endpoint failure",
  "EventType": "Failure",
  "Id": 3001,
  "Message": "invalid_scope",
  "Details": {
    "EndpointName": "authorize"
  },
  "Context": {
    "ActivityId": "80000122-0000-fc00-b63f-84710c7967bb",
    "TimeStamp": "2015-09-23T16:57:33.9855972+00:00",
    "ProcessId": 18140,
    "MachineName": "devBox0101",
    "RemoteIpAddress": "127.0.0.1"
  }
}
iisexpress.exe Information: 0 : 2015-09-23 11:57:33.989 -05:00 [Information] End authorize request
iisexpress.exe Information: 0 : 2015-09-23 11:57:34.000 -05:00 [Information] Redirecting to: http://localhost:9000/index.html#error=invalid_scope

My Request String is as follows:
```
        /connect/authorize/?response_type=id_token&client_id=aureliaAppDev&redirect_uri=http://localhost:9000/index.html&scope=scope openid profile"
```

**Comment by devscott** [comment]
Please ignore. I was missing some options on the client side. Palm to forehead moment.

**Comment by sabby62** [comment]
@devscott  What options you were missing ?

**Comment by devscott** [comment]
@sabby62 I do not recall. However I do have an example of an aurelia client working with IdentityServer. You can find the [project here](https://github.com/devscott/identityServer3Example)
