### ISSUE TITLE
How to support multiple ADFS in SaaS

### ISSUE THREAD

**Issue by programmer-pragmatic** [IdentityServer/IdentityServer3#1940]
We are building a multi-tenant application. Some of the tenants already have ADFS in their premise. And they want their users to get authenticated with their ADFS.

But since our identity server's user interface will be same for all those tenants, how can we provide functionality where user opt for get validated with its companies ADFS? I believe we cannot give link like 'tenant1-ADFS', 'tenant2-ADFS', 'tenant3-ADFS' and so on. Not only this will expose all the tenants-name who are using this application but also will have usable issues. 

Generally what happens is, when you type in with your email, it checks the domain and take you to that ADFS's login page. Is it possible to achieve this with identityserver3? 

Thanks In Advance

**Comment by leastprivilege** [comment]
you can configure available idps per client, can determine the external idp to use dynamically in PreAuthenticate - or use acr_values to control which idp to use.

all documented.

**Comment by brockallen** [comment]
All set?
