### ISSUE TITLE
Make all access tokens claims available in GetProfileDataAsync when coming fro UserInfo

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#1941]

**Comment by delimited** [comment]
If I understand this correctly, does this mean that Access Tokens not containing the "openid" scope, such as a standard OAuth2 connection, would be allowed to use the UserInfo endpoint?

**Comment by leastprivilege** [comment]
no. the openid scope is required to access the userinfo endpoint

**Comment by leastprivilege** [comment]
dup
