### ISSUE TITLE
Integrating IdentityServer3 with SharePoint 2013

### ISSUE THREAD

**Issue by venh** [IdentityServer/IdentityServer3#1942]
Could you kindly provide some insight into integrating IdentityServer3 with SharePoint 2013? I would also like to know the code for the following, after the integration.
1. Generate the Token
2. Write to and Retrieve from the Token Cache
3. Re-validate the Token
4. Implementing  Sliding Sessions
5. Extending the IdentityServer3 for maintaining users and roles in a custom DB
6. Implementing Multi Tenant Scenario in IdentityServer3 for SharePoint 2013

**Comment by leastprivilege** [comment]
I don't know - did you make progress on that?

**Comment by venh** [comment]
No. Nothing as of now.
