### ISSUE TITLE
AuthorizeRequestValidator is internal - need to valid request for registration page

### ISSUE THREAD

**Issue by vindberg** [IdentityServer/IdentityServer3#1943]
Is there a way I can use AuthorizeRequestValidator in my Idp RegistrationController so that I can validate the request or do I need to duplicate the steps: 1. DefaultRedirectUriValidator, 2. client.Enabled etc.

Thanks.

**Comment by leastprivilege** [comment]
Why would you need to validate the request outside the authorization endpoint?

**Comment by vindberg** [comment]
I want to make a "Register" link (from client website) that takes you directly to the registration page on Ids with appropriate client_id, redirect_uri, and scopes so that the generated signin can be used to auto-login and redirect after registration.

Hope it makes sense.

**Comment by leastprivilege** [comment]
You would rather pass a register "hint" (via acr_values) to the authZ endpoint - and then use the PreAuthenticateAsync method in the user service to redirect to the register page. Afterwards redirect back to the resume URL to continue the flow.

**Comment by vindberg** [comment]
Thanks, that what I was looking for. So "acr" means Additional Credentials. Thanks.

**Comment by vindberg** [comment]
Im in the PreAuthenticateAsync now, but do not have the signin or owin environment to generate one using the SigninMessage :/

```
        public override Task PreAuthenticateAsync(PreAuthenticationContext context)
        {
            var arcValues = context.SignInMessage.AcrValues.ToList();
            if (arcValues.Contains("redirect_to:registration"))
            {
                context.AuthenticateResult = new AuthenticateResult("~/registration", new List<Claim>()) {  } ;
            }
            else
            {
                return base.PreAuthenticateAsync(context);
            }

            return Task.FromResult(0);
        }
```
Is there a way to get the signin querystring on the redirect authenticateresult? Or is there another way forward?

**Comment by leastprivilege** [comment]
You can inject the OwinEnvironmentService. You can also get to the resume URL from the registration page using our OWIN extension methods. They are documented.

**Comment by vindberg** [comment]
Thanks.
