### ISSUE TITLE
Error in userManager.CreateAsync(user)

### ISSUE THREAD

**Issue by ANEDev** [IdentityServer/IdentityServer3#1944]
Hello community,

I am trying to implement a registration prozess with email confirmation for my web application. I am implementing a function to the IdentityServer3.AspNetidentity service which have an equal functionality like the existant function:  protected virtual async Task<AuthenticateResult> ProcessNewExternalAccountAsync(string provider, string providerId, IEnumerable<Claim> claims) .

I get the right user context to that function. 
![bild 6](https://cloud.githubusercontent.com/assets/13555497/10076821/b6aa42c6-62dd-11e5-889a-390003a74eab.png)

But I can't access to more attribute until the id and the username.
![bild 7](https://cloud.githubusercontent.com/assets/13555497/10076844/d75b1e64-62dd-11e5-90e9-495e6a60d7dd.png)

When I just setting the id und username the userManager.CreateAsync(user) raises an exception with the following message.
![bild 3](https://cloud.githubusercontent.com/assets/13555497/10076627/bed509a0-62dc-11e5-94d4-59b9860c5e29.png)

Do you have any idea how to solve that problem?

**Comment by brockallen** [comment]
Sounds like this should be moved to this repo: https://github.com/IdentityServer/IdentityServer3.AspNetIdentity

**Comment by ANEDev** [comment]
Yes that could be right

**Comment by ANEDev** [comment]
I solved the problem
