### ISSUE TITLE
invalid_client for null secret type in v2

### ISSUE THREAD

**Issue by delRyan** [IdentityServer/IdentityServer3#1948]
In version 1.6 and below all of our client secrets were of type null. This was a non issue as IdentityServer3 correctly assumed that they were all of type "SharedSecret". After upgrading to v2 we found out that this is no longer the case and while testing we discovered that all token requests resulted in invalid_client. After updating our database so all secrets were "SharedSecret" the issue was resolved.

I'm not sure if this should be marked as a breaking change. The docs for v2 describe the 'Type' as a hint for the secret validator but it appears to be more than a hint. I also have a hunch that a 'Type' of null is now defaulted to an X509CertificateThumbprint. All of this is made a little more confusing by the fact that in v1 there are no docs for secrets.

I might have missed or misinterpreted something but i'm just looking for a little light to be spread on this issue so I can maybe update the docs- or have this included in the breaking changes section of the v2 release.

Thanks!

**Comment by leastprivilege** [comment]
Well - type of 'null' certainly sounds wrong to me.

IIRC when you new up a `Secret` - the default value for type should be `SharedSecret` - if not this would be an improvement.

It certainly seems to be a breaking change - but also a bug fix since nulls are not allowed anymore.

**Comment by delRyan** [comment]
It's looking like it may be a mapping problem in the entity framework project, i'll look into it more.
