### ISSUE TITLE
Replacing the welcome page for Identity Server v3

### ISSUE THREAD

**Issue by akiander** [IdentityServer/IdentityServer3#1949]
I added a **templates** folder to the root of my web application that is hosting Identity Server... and I put a file called **welcome.html** inside the folder but the site won't use it. Have tried restarting, recycling, clearing cache, etc but nothing seems to work. 

I added this code to the startup.cs as well but no luck: 

                var viewOptions = new DefaultViewServiceOptions();
                viewOptions.CacheViews = false;
                factory.ConfigureDefaultViewService(viewOptions);

I am able to replace the layout template by adding a **_layout.html** file to the templates folder. That works. And I can replace the login page with a file called **_login.html**. But no matter what I've tried, I can't seem to replace the welcome.html page. 

Any advice on how to debug / diagnose why it won't use my template for the welcome page?

**Comment by leastprivilege** [comment]
The welcome page is meant for developers - not end users. You can disable it and replace it completely with something else.

**Comment by akiander** [comment]
Okay I found the setting to turn this off... here: 

                var options = new IdentityServerOptions
                {
                    SiteName = "My Site",
                    EnableWelcomePage = false,
                    ...

I was confused because the welcome page is listed [here](https://github.com/IdentityServer/IdentityServer3/tree/master/source/Core/Services/DefaultViewService/PageAssets) as one of the default views so I assumed that I could replace it, but apparently it doesn't work that way. I'm all set now.

**Comment by anthonyresq** [comment]
Can I ask how exactly I replace it completely with something else? I've looked for samples and I don't see anything that works.

**Comment by brockallen** [comment]
You control the pipeline -- simply emit some html when the request arrives that matches that URL. It's just like building a web application.

**Comment by eclipsed82** [comment]
Hi everyone,

I've spent a few hours trying to create a custom welcome page. Essentially, if someone visits the base domain of identityserver (so for example, http://localhost:44333/") I would like to redirect them to one of my client apps' homepages. I have tried many things and once I get far along, I encounter an issue that lets me know it's just not the right approach. Any suggestions?

**Comment by brockallen** [comment]
Disable the welcome page on the IS options, then handle that path in your hosting app to redirect.

**Comment by eclipsed82** [comment]
Thanks, Brock. This is a self-hosted console application, so I'm not sure how to handle a path to redirect.

**Comment by brockallen** [comment]
Add a middleware.

**Comment by eclipsed82** [comment]
I tried doing the following, but this overrides my custom views (login, error, etc.)

           var fileServerOptions = new FileServerOptions
            {
                RequestPath = PathString.Empty,
                EnableDefaultFiles = true
            };

            var physicalFileSystem = new PhysicalFileSystem(@".\Content\app"); 
            fileServerOptions.StaticFileOptions.FileSystem = physicalFileSystem;  
            fileServerOptions.StaticFileOptions.ServeUnknownFileTypes = true; 
            fileServerOptions.DefaultFilesOptions.DefaultFileNames = new[] { "index.html" };

            app.UseFileServer(fileServerOptions);



My factory looks like this:
factory.UserService = new Registration<IUserService, IdentityUserService>();

            var viewOptions = new DefaultViewServiceOptions
            {
                CacheViews = false,
                ViewLoader = new Registration<IViewLoader>(new FileSystemWithEmbeddedFallbackViewLoader(Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(Directory.GetCurrentDirectory())), @"content\app\")))
            };


            factory.ViewService = new DefaultViewServiceRegistration<CustomViewService>(viewOptions);

**Comment by eclipsed82** [comment]
Hi Brock,

Just following up on this. Can you provide more details on your suggestion or feedback on my previous code snippet?

Thanks so much

**Comment by eclipsed82** [comment]
Hi Brock,

I have a middleware working. However, I'd like to have this middleware redirect the user to the IdentityServer's login page. How can I do this? Currently, I have it set to go to login, but since the redirect url doesn't specify a signin parameter value, then I of course get the IdentityServer served error page with the following error: 

There is an error determining which application you are signing into. Return to the application and try again.

**Comment by brockallen** [comment]
> However, I'd like to have this middleware redirect the user to the IdentityServer's login page

OWIN extensions: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html
