### ISSUE TITLE
AuthServer, Client Application and API as separate Entities

### ISSUE THREAD

**Issue by naturalstyl** [IdentityServer/IdentityServer3#1950]
Someone may have already asked this question,but I've yet to find an answer. Does anyone have an example(s) of hosting the Identity Server (v3) outside of web client? I've worked through the "MVC Application" project, but I just get an error with no explanation why.

![image](https://cloud.githubusercontent.com/assets/13439142/10084414/f4232c40-62c8-11e5-8446-4b96150a8d59.png)

My goal is to have the identity server, web clients and APIs as separate entities (or IIS hosted applications). Based on the "Getting Started: MVC Authentication & Web APIs" tutorial this is what I have for the following:

<h3>Id Server</h3>
<pre>
public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject;
            app.Map("/identity", idsrvApp =>
            {                
                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "External IdentityServer",
                    SigningCertificate = LoadCertificate(),
                    Factory = new IdentityServerServiceFactory()
                                .UseInMemoryUsers(Users.Get())
                                .UseInMemoryClients(Clients.Get())
                                .UseInMemoryScopes(Scopes.Get()),
                    IssuerUri = "https://localhost:44302/"
                });
            });
        }

        X509Certificate2 LoadCertificate()
        {
            return new X509Certificate2(
                string.Format(@"{0}\bin\IdServer3Practice.pfx", AppDomain.CurrentDomain.BaseDirectory), "IdServer3Practice");
        }
</pre>

<pre>
 public static class Clients
    {
        public static IEnumerable<Client> Get()
        {
            return new[]
        {
            new Client 
            {
                Enabled = true,
                ClientName = "MVC Client",
                ClientId = "mvc1",
                Flow = Flows.Implicit,

                RedirectUris = new List<string>
                {
                    "https://localhost:44301"
                },
                AllowAccessToAllScopes = true,
                PostLogoutRedirectUris = new List<string>
                {
                    "https://localhost:44301"
                }
            }
        };
        }
    }
</pre>

<pre>
  public static class Users
    {
        public static List<InMemoryUser> Get()
        {
            return new List<InMemoryUser>
            {
                new InMemoryUser
                {
                    Username = "bob",
                    Password = "secret",
                    Subject = "1",

                    Claims = new[]
                    {
                        new Claim(Constants.ClaimTypes.GivenName, "Bob"),
                        new Claim(Constants.ClaimTypes.FamilyName, "Smith"),
                        new Claim(Constants.ClaimTypes.Role, "Geek"),
                        new Claim(Constants.ClaimTypes.Role, "Foo")
                    }
                }
            };
        }
    }
</pre>

<pre>
 public static class Scopes
    {
        public static IEnumerable<Scope> Get()
        {
            var scopes = new List<Scope>
        {
            new Scope
            {
                Enabled = true,
                Name = "roles",
                Type = ScopeType.Identity,
                Claims = new List<ScopeClaim>
                {
                    new ScopeClaim("role")
                }
            }
        };

            scopes.AddRange(StandardScopes.All);

            return scopes;
        }
    }
</pre>

<h3>MVC Client Application</h3>
<pre>
 public class Startup
    {        
        public void Configuration(IAppBuilder app)
        {
            // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=316888
            AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject;
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            app.UseCookieAuthentication(new CookieAuthenticationOptions { AuthenticationType = "Cookies" });
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://localhost:44302/identity",
                ClientId = "mvc1",
                Scope = "openid profile roles",
                RedirectUri = "https://localhost:44301",
                ResponseType = "id_token",
                SignInAsAuthenticationType = "Cookies",
                PostLogoutRedirectUri = "https://localhost:44301"
            });
        }
    }
</pre>

**Comment by leastprivilege** [comment]
As always- turn on logging.

**Comment by naturalstyl** [comment]
Thank you for the quick response. As you said, logging was and is my friend. I didn't think it was that easy. Thanks again.
