### ISSUE TITLE
[Question] Requiring a role when the user logs in (as additional credential)

### ISSUE THREAD

**Issue by digitalpowers** [IdentityServer/IdentityServer3#1951]
I have a system where if the user logs in as Joe with the role "Readonly" then he will be granted access only to read things (fairly obviously) however if he logs in as Joe with the role "Administrator" then he will have access to do administrative functions. However I want him to have to relogin if he wishes to change from the Readonly role to the Administrator role so that he could potentially leave his account logged in as Readonly on a display screen or something without fear of someone hijacking his Administrator priviledges.

Now I also need to be able to log in a Web client via an implicit grant or another server via a code grant and have that service be able to use the same roles as well (while still requiring Joe to log in as the particular role if he isn't already authenticated.)

Now I have been trying to do this with IdentityServer3 but I cant seem to get the role information to be part of the authentication for the user, I tried adding an acr_value of role:ReadOnly to the token request (which then turns into an authentication request if the user is not logged in) but if they log in with the acr_value of ReadOnly and then come back to log in with the acr_value of Adminstrator it just lets them on in because they are already authenticated as the user.

Any tips on what I should be using instead of what I am doing or how I might be completely off base in this OAuth2/OpenID Connect world?

**Comment by digitalpowers** [comment]
I finally figured it out so for others who might want to do the same thing here is what I did.

First you have build a custom UserService that looks in the acr_values for extra information. Then create a claim for that extra information in the AuthenticateResult.
Second you have to override the ClaimProvider to include your custom claim set in step one in the tokens generated.
Next you need a CustomRequestValidator in order to check if a new acr_value is being set compared to the one you have stored in token being currently used.  If it has changed and you want to force the user to reauthenticate you can set 'request.PromptMode = "login";'
And that is it, using that set of steps I can now authenticate a user using 3 values (username, password, and role) and if the role requested changes I can require them to reauthenticate.

Works swimingly.

**Comment by leastprivilege** [comment]
cool!

**Comment by alhardy** [comment]
@digitalpowers I've been looking at something similar an came across this question and your solution. In your first point when you say "Then create a claim for that extra information in the AuthenticateResult" are you adding the value as a claim of type "acr" or some other custom type? When the AuthenticateResult is instantiated all protocol claims are removed (including acr) so they are not available in the ClaimProvider.

I don't think I understand acr claims correctly? My understanding is that for example if multiple acr_values are requested by the relying party and one of these matches a claim on the user, this value is added as an acr claim type in the id token.
