### ISSUE TITLE
Pre-requisites for Understanding Identity Server 3 code completely

### ISSUE THREAD

**Issue by venh** [IdentityServer/IdentityServer3#1952]
Hi,
I am trying to understand Identity Server 3 code completely and properly. I would like to know what are the pre-requisites for that. For example, I see that, you have used MVC, WIF, some design patterns, OpenID, OAuth2, OWIN, Katana and so on. Please let me know. Also, please provide some links (for blogs / tutorials / videos) to learn these pre-requisites properly and clearly.

**Comment by brockallen** [comment]
You need to understand the OIDC and OAutrh2 specs -- google is your friend for those.
