### ISSUE TITLE
Adding IdentityServer3 to an existing ASP.NET MVC 5 website

### ISSUE THREAD

**Issue by bloudraak** [IdentityServer/IdentityServer3#1954]
Suppose I created a new APS.NET Web Application in Visual Studio 2013,  select individual accounts and then customizing so that it matches your brand and handles complex registration, password reset and authentication workflows (including smart card, TFA, password). 

What steps do I take to use IdentityServer3 to make it an OpenID Connect Identity Provider?  

Most of the existing examples assume that we'll start from scratch, or that I'd like to enhance a site that already has IdentityServer3 installed and working.

**Comment by leastprivilege** [comment]
You can use the PreAuthenticateAsync method in your user service to jump to your login application instead of our default views. The use the OWIN extensions methods to interact with idsrv - and ultimately redirect back to continues the flow.

Check the docs.

**Comment by leastprivilege** [comment]
all set?

**Comment by pashute** [comment]
where in the docs?

**Comment by brockallen** [comment]
This is the docs starting page: https://identityserver.github.io/Documentation/

**Comment by jorupp** [comment]
@leastprivilege & @brockallen - I can't find anything in the docs about using PreAuthenticateAsync to go to your own auth path, and I can't find any examples on this approach.  Am I crazy for thinking this is something that'd be commonly requested and should be simple?
