### ISSUE TITLE
Setup an exprimental Identity Server with Identity Server 3

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3#1955]
It is nice to have an live experimental identity server to collaboration on client scenarios.
For my scenario i have some issues with using ASP.NET 5 and Identity Server 3. I try to publish my code on a public repository but others have not an Identity  Server to test it and help me.
Thanks

**Comment by leastprivilege** [comment]
That's a great idea - feel free to setup one and let us know so we can publish the URL.

**Comment by mikeandersun** [comment]
I try it and inform you about it. 
I have not a dedicated server, but i start it on my shared server. I think that is enough to start.
