### ISSUE TITLE
Redirect User to specified URL after Login

### ISSUE THREAD

**Issue by tejashdesai** [IdentityServer/IdentityServer3#1957]
Hello,

I have implemented SSO with SPA using IdentityServer3. It working perfectly. Now i have one scenario in which user will get an email with link. When user click the link user is redirecting to the STS. Once he/she authenticated by STS currently it redirect to the client home page instead of link given in the email. Also if session is over then user is logged out and redirect to the STS login page. After re authenticate he/she should resume where they are before logged out.

Thanks,
Tejash

**Comment by leastprivilege** [comment]
You can only redirect to the pre-defined redirect URI in config.

The way this is typically solved is to store the deep link **before** the redirect to the STS happens (e.g. session storage). After authentication, do the redirect manually in your app.

**Comment by vijay2358** [comment]
Teajsh
Do you have sample Sso in idserver3

**Comment by tejashdesai** [comment]
Thanks for your quick response. I will try this.

**Comment by tejashdesai** [comment]
@vijay2358 nope i do not have sample. I just used the below samples for SSO:

https://github.com/IdentityServer/IdentityServer3.Samples

**Comment by dprochownik** [comment]
Is there anything wrong in sending expected URL as a part of the "state"?

For example:

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions 
{
	...
	Notifications = new OpenIdConnectAuthenticationNotifications
	{
		AuthorizationCodeReceived = async n =>
		{                        
			...
			string expectedUrl;
			var protectedState = n.ProtocolMessage.State.Split('=')[1];
			var state = n.Options.StateDataFormat.Unprotect(protectedState);
			if(state.Dictionary.TryGetValue("expectedUrl", out expectedUrl)) {
				n.RedirectUri = expectedUrl;        
			}
		},
		...			
		RedirectToIdentityProvider = n =>
		{
			if(n.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
			{					      
				var expectedUrl= n.Request.Uri.ToString();

				var stateQueryString = n.ProtocolMessage.State.Split('=');
				var protectedState = stateQueryString[1];
				var unprotectedState = n.Options.StateDataFormat.Unprotect(protectedState);
				unprotectedState.Dictionary["expectedUrl"] = expectedUrl;
				n.ProtocolMessage.State = stateQueryString[0] + "=" + n.Options.StateDataFormat.Protect(unprotectedState);
			} 
			...
			return Task.FromResult(0);
		}
	}
});
```
