### ISSUE TITLE
Can a debug logger log secret values?

### ISSUE THREAD

**Issue by delRyan** [IdentityServer/IdentityServer3#1958]
I was looking to do a pr to make failure scenarios more easily debug-able on secret validators. I wanted a way to identify a secret that was being skipped for not being of the correct type or for being expired. Is the following ok?

```C#
// this validator is only applicable to shared secrets
if (secret.Type != Constants.SecretTypes.SharedSecret)
{
    Logger.Debug(string.Format("Skipping secret {0}, secret is not {1}.", secret.Value, Constants.SecretTypes.SharedSecret));
    continue;
}                
     
// check if client secret is still valid
if (secret.Expiration.HasExpired())
{
    Logger.Debug(string.Format("Skipping secret {0}, secret is expired.", secret.Value));
    continue;
}
```

Secret Description seems like a better choice but Value is the only non-nullable column.
Note: only the log statements have been added to the above code.

**Comment by leastprivilege** [comment]
The less secrets that turn up in logging the better. Is there an alternative?

**Comment by delRyan** [comment]
We could do the secret Description if that's acceptable.

**Comment by leastprivilege** [comment]
yep
