### ISSUE TITLE
Feature Request: Semantic Logging

### ISSUE THREAD

**Issue by bloudraak** [IdentityServer/IdentityServer3#1959]
Many organizations deploy sophisticated pattern matching software to detect malicious requests. Unfortunately many frameworks use simple tracing making it much more complex to detect and mitigate an attack. Those logs often do not contain sufficient context to identify an attack. IdentityServer3 is no different. 

This is a request that IdentityServer3 supports semantic logging.  Instead of writing 

    Logger.Write(Information, "The client secret is invalid")

Semantic logging would look as follows:

    EventSource.OnInvalidClientSecret(Request, Client);

For simplicity sake, the default implementation of event source can call tracing logic.  However, for the more security conscious amongst us, we could map OnInvalidClient to a ETW event with a unique id, keyword and operation.  This would allow sophisticated tools, e.g. machine learning, to analyze the events and detect something like a brute force attack.  The benefit of ETW is that I can enable logging for certain keywords etc without having to restart the application.  

Having said this, I'd also advise against the core of IdentityServer3 being dependent upon any logging framework other than that provided by the .NET framework.  Since IdentityServer3 is a security component, there is more scrutiny. If IdentityServer3 is dependent upon another framework, which fails an audit, then the auditing of IdentityServer3 too will fail.  It also complicates matters when the consumer of the framework have to consolidate numerous logging frameworks.

Instead, have the core of IdentityServer3 expose an interface that allows for semantic logging, and then offer different packages for log4net, dotnet tracing, ETW and so forth.

**Comment by leastprivilege** [comment]
Logging is for dev time - check the docs for more information.

You are looking for events - we output events and you can write your own event sink by implementing IEventService.

The defaut implementation outputs every event as JSON - other people use stacks like ELK to turn that into structured data.

If you should go down the route of ETW - it would be nice to publish the implementation as a contrib.

**Comment by leastprivilege** [comment]
there's room for improvement in the whole eventing system - if you feel that there is missing data we should discuss how to improve that.

**Comment by leastprivilege** [comment]
progress?
