### ISSUE TITLE
How to unify local and external login processes. 

### ISSUE THREAD

**Issue by bloudraak** [IdentityServer/IdentityServer3#1960]
Assume for a moment that you have a local user store backed by SQL and hundreds of external providers.  We can identify which identity store to use since each external provider is tied to the domain of an email address (e.g. bob@example.com, bob@example.org and bob@example.net represents users from three external providers). In some cases, two or more domains can be tied to a single external domain.

We can't really expect users to find the respective link or button for their external provider. So like other identity providers one approach is to request that the user enters their email address, after which can redirect them to their identity provider to sign in.

Looking at all the extension points, I'm trying to figure out how to 

* consolidate the local and external logins from a UX perspective
* configure IdentityServer3 to load external providers dynamically from a database instead of start time. It is unacceptable to restart the application after a external provider was registered. 

Any pointers where to start would be appreciated?

**Comment by leastprivilege** [comment]
The the custom HRD sample for the email mapping.

wrt to dynamic loading - that's something you have to do at the hosting layer - you need to dynamically load (or update) the OWIN pipeline. No sample - but this has been done before.

**Comment by bloudraak** [comment]
That is exactly what I was looking for. Thank you!
