### ISSUE TITLE
Always get 401"Authorization has been denied for this request" after deploy to production server

### ISSUE THREAD

**Issue by liupengf12** [IdentityServer/IdentityServer3#1961]
Everything works well on my local, after deployed to production server all the requests of WebAPI get **401**. My codes like this:
```C#
            // Identity Server
            app.Map("/identity", idsrvApp =>
            {
                var factory = new IdentityServerServiceFactory()
                    .UseInMemoryClients(Clients.Get())
                    .UseInMemoryScopes(Scopes.Get());

                factory.UserService = new Registration<IUserService>(resolver =>
                    new LocalUserService(_kernel.Get<ISecurityService>(), _kernel.Get<IWaiterService>())
                );
                factory.CorsPolicyService = new Registration<ICorsPolicyService>(new DefaultCorsPolicyService { AllowAll = true });

                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "APIs",
                    SigningCertificate = loadServerCertificate(),
                    Factory = factory,
                    LoggingOptions = new LoggingOptions { EnableHttpLogging = true }
                });
            });

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost/BabyWuyou/identity",
                ValidationMode = ValidationMode.ValidationEndpoint,
                RequiredScopes = new[] { "APIs", "offline_access" }
            });
```

After deployed to production server, I changed the "localhost" with a ip address:
Authority = "https://[***the production ip address***]/BabyWuyou/identity"

After checking the logs I found another difference: there is a POST request will happened on my local when calling the WebAPI:
2015-09-27 13:29:59.2171|DEBUG|IdentityServer3.Core.Logging.LogProviders.NLogLogProvider+NLogLogger.Log|HTTP Request
{
  "Method": "POST",
  "Url": "https://localhost/BabyWuyou/identity/connect/accesstokenvalidation",
  "Headers": {
    "Connection": [
      "Keep-Alive"
    ],
    "Content-Length": [
      "829"
    ],
    "Content-Type": [
      "application/x-www-form-urlencoded"
    ],
    "Expect": [
      "100-continue"
    ],
    "Host": [
      "localhost"
    ]
  },
  "Body": "token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InQ0enhFS1MxQlNzeEFsNk1jMTRMS2ZDVjRFayIsImtpZCI6InQ0enhFS1MxQlNzeEFsNk1jMTRMS2ZDVjRFayJ9.eyJjbGllbnRfaWQiOiJhcHBfd2FpdGVyIiwic2NvcGUiOlsiQVBJcyIsIm9mZmxpbmVfYWNjZXNzIl0sInN1YiI6IjIiLCJhbXIiOlsicGFzc3dvcmQiXSwiYXV0aF90aW1lIjoxNDQzMzMxNzk4LCJpZHAiOiJpZHNydiIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0L0JhYnlXdXlvdS9pZGVudGl0eSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0L0JhYnlXdXlvdS9pZGVudGl0eS9yZXNvdXJjZXMiLCJleHAiOjE0NDMzMzUzOTksIm5iZiI6MTQ0MzMzMTc5OX0.V2wxOfvnFMUR9Inf-GxlZyzhHvZNRJyJi0iVl4UU-96YdGizF-r45-ZcKGx7ILnf-S5_dl4Bl9URjf3leqKkIcsmjwdZJX9xVhKlsuk6PkETRM2ro3I_HDDY_PGpni3X9aDweddsleXnTMemQDqjEHOIJom9iA9fLyxwUfkB-NQ8bcgbBLO2mIH3QhUze-sVPIe-NoJ9OcUuREQBWGAqTjYQiRz0oBkqNjBbTt6vDhVqsDfbne1GLvaLNUdCIicNyUo81MzVac9-qOiOXk7arFzXk7Fpg1FOoWeECgG4nv2oHL2m3rs8XG7tB2zLi5bCfY-Tlccg4NfrE70JVJxz2w"
}
2015-09-27 13:29:59.2341|INFO|IdentityServer3.Core.Endpoints.AccessTokenValidationController|Start access token validation request

But I did not find same POST request on my production server.
Is there any special configuration I missed on my productions? What I used is Windows 2008 R2 with .NET 4.5

**Comment by leastprivilege** [comment]
Is the SSL cert trusted on the machine - otherwise your https:// connection will fail.

**Comment by leastprivilege** [comment]
all set?
