### ISSUE TITLE
Token Response

### ISSUE THREAD

**Issue by verres630** [IdentityServer/IdentityServer3#1964]
I'm trying to create Android client based on https://github.com/learning-layers/android-openid-connect.
In OIDC documentation (http://openid.net/specs/openid-connect-core-1_0.html#TokenRequest), section 3.1.3.3. says that successful token response must include id_token. 
My http request:
"grant_type" -> "refresh_token"
"refresh_token" -> "a9a8652fc7b92759b9597a7d66991682"
"scope" -> "openid profile offline_access roles sampleApi"
Response:
"token_type" -> "Bearer"
"refresh_token" -> "f438696617a97a8e99e3ecc3678f3381"
"expires_in" -> "3600"
"access_token" -> "2384b87986ff15b0bd39501940aac568"
There is no id_token and i think that it should be in response.

**Comment by leastprivilege** [comment]
if you are using a grant type of `authorization_code` that is true.

But not for refresh requests.

**Comment by verres630** [comment]
Thank you for your clarification. So there is no way to get id_token from refresh_token?

**Comment by leastprivilege** [comment]
why would you do that?

**Comment by verres630** [comment]
In the android client sample, they use refresh token to get id_token, access_token and refresh_token (https://github.com/learning-layers/android-openid-connect/blob/master/app/src/main/java/com/lnikkila/oidcsample/oidc/authenticator/Authenticator.java#L127). This sample worked fine with their OIDC server, but i had problems with IdentityServer3. I was wondering if it was client or server issue. Now i know that their OIDC server is not compatible with offical OIDC documentation. I had same problem as described here (https://github.com/IdentityServer/IdentityServer3/issues/1721) and i thought that something wrong is with idsrv3. Also they use id_token in userInfo endpoint instead of access_token. Everything now works fine, when I need id_token i must create new authorisation request.

**Comment by leastprivilege** [comment]
id_token at the user info endpoint - really? 

Yea that sounds like a really buggy implementation.
