### ISSUE TITLE
Public Key Size sanity check in UseIdentityServerExtension.DoStartupDiagnosticAsync() assumes signing algorithm = RSA.

### ISSUE THREAD

**Issue by larsw** [IdentityServer/IdentityServer3#1965]
The sanity check on the size of the signing certificate's public key w/o also checking the signing algorithm; 2048 as a minimum is all good for RSA, but it for ECDSA it would rule out all named EC curves / "key" sizes that are in use.

IMHO, the sanity check should either be removed, or checked in combination with the public key type (at least RSA/ECDSA).

**Comment by leastprivilege** [comment]
good point! 

PR?

**Comment by larsw** [comment]
I work on isolated networks at work, but I'll look into when I get back home.
