### ISSUE TITLE
Raise local login success event with claim info

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3#1966]
Hi

I am using the RaiseEvent method of IEventService to publish customer successfully logged-in event to our subscribers. 

All good except I can't figure out how to pass through other claims information apart from just subject id and name, following is the RaiseLocalLoginSuccessEvent extension method that calls IEventService.RaiseEvent method at the end of process, and as you can see the LocalLoginDetails class doesn't encapsulate authResult object which I can get claims from if it does, 

and I can't override this method in my custom EventService either, because this method is extension method.

Can you advise how can I get other claims in the RaiseEvent method? or it isn't the right place to publish logged-in event?

Thanks

```
public static void RaiseLocalLoginSuccessEvent(this IEventService events, 
            string username, string signInMessageId, SignInMessage signInMessage, AuthenticateResult authResult)
        {
            var evt = new Event<LocalLoginDetails>(
                EventConstants.Categories.Authentication,
                Resources.Events.LocalLoginSuccess,
                EventTypes.Success,
                EventConstants.Ids.LocalLoginSuccess,
                new LocalLoginDetails
                {
                    SubjectId = authResult.HasSubject ? authResult.User.GetSubjectId() : null,
                    Name = authResult.User.Identity.Name,
                    SignInId = signInMessageId,
                    SignInMessage = signInMessage,
                    PartialLogin = authResult.IsPartialSignIn,
                    LoginUserName = username
                }); 

            events.RaiseEvent(evt);
        }
```

**Comment by jeremy001181** [comment]
I committed a change to my fork [here](https://github.com/jeremy001181/IdentityServer3-1/commit/807bd85d22b06d5fa8c9b332758f6fd5e54b94ad), basically describe what I mean above

Can you advise if it makes sense please?

**Comment by leastprivilege** [comment]
May I ask why you are doing this?

**Comment by jeremy001181** [comment]
The requirement is that the site needs to be able to  publish an event to azure service bus in a event of a user logged in, so I have registered a custom event service that implements IEventService interface , and in the RaiseEvent method I can then initialize my custom event object and publish to all understream subscribers, 

There are few information (claim) I can't get from the parameter evt that pass into RaiseEvent , 

That's why I started this issue

Does it make sense to you?

**Comment by jeremy001181** [comment]
The AuthenticationController that call the static  extension method (above) to initialize evt object which then pass into RaiseEvent method of IEventService 

The evt object missing claims info I need , that is why I extend it to include whole User data so that I can get when I initialize my custom event object and publish

**Comment by jeremy001181** [comment]
Hope it makes sense

**Comment by leastprivilege** [comment]
my question was rather - why do you need the claims?

**Comment by jeremy001181** [comment]
The claim has the data I need to publish to my subscriber 

E.g how can I get gender information of the logged in customer in the RaiseEvent method?

**Comment by leastprivilege** [comment]
OK - we'll discuss that.

**Comment by leastprivilege** [comment]
I am wondering - why don't you simply emit your own event? That way it could have exactly the info **you** need. Inject the IEventService into your user service for that.

**Comment by jeremy001181** [comment]
you are right, that works.

but dont you think raising logged-in event using the built-in flow that is invoked at the end of LoginLocal action is more consistent and clean than having it multiple places?

**Comment by leastprivilege** [comment]
Sure - but where do we start and where do we end? We can only emit whatever you return in the AuthenticateResult (aka what goes into the cookie) - what if someone needs a different claim that's not there?

So I think - the best solution is to emit your own event.

**Comment by jeremy001181** [comment]
I see your point about what if someone needs a different claim that's not there, I don't have a proper answer for it.

but my request is not conflict with what you said - "We can only emit whatever you return in the AuthenticateResult" the issue is there is currently very limited information in AuthenticationResult get passing through to `evt` variable (i.e. only the sub, name and isPartialSignIn) 

![image](https://cloud.githubusercontent.com/assets/2342277/10664964/7ab33b68-78bf-11e5-89bb-79a28b397aa8.png)

**Comment by leastprivilege** [comment]
yes - and that's the way it will stay. There is also a potential that some claim is sensitive and should not end up in logs.

**Comment by jeremy001181** [comment]
ok, I see, make sense, thank you for looking into it, I will change to use what you suggest
