### ISSUE TITLE
Which NuGet package to Install?

### ISSUE THREAD

**Issue by naturalstyl** [IdentityServer/IdentityServer3#1969]
As I was refactoring some Identity Server 3 code, I noticed that there are two NuGet assemblies for Identity Server 3 (Thinktecture.IdentityServer3 (v1.6.3) and IdentityServer3 (v2.0)). Which is better to implement? I ask because I notice the documentation speaks of extension methods (like InMemory Factory) that are not in IdentityServer3 NuGet package. I wasn't sure if some things were deprecated or not. Thanks.

**Comment by brockallen** [comment]
The release notes mention this: https://github.com/IdentityServer/IdentityServer3/releases/tag/2.0.0
