### ISSUE TITLE
Generate access tokens with additional claims

### ISSUE THREAD

**Issue by francischeung** [IdentityServer/IdentityServer3#1970]
In addition to the claims related to a user's identity, I would like to include claims based on a specific resource the user is trying to access. I would like to include all the claims and have IdentityServer generate an access token. Is this possible?

**Comment by brockallen** [comment]
Look into the Claims on the Scope configuration (it's covered in the docs).

**Comment by francischeung** [comment]
I've read some docs including this one: https://identityserver.github.io/Documentation/docs/configuration/scopesAndClaims.html

What I need is to include claims related to a specific resource the user is trying to access. These claims are not stored in the identity provider and are provided by the application. Is it possible to have these "additional" claims somehow included in an access token generated by IdentityServer?

**Comment by brockallen** [comment]
You can always do claims transformation in the API layer of your app.

**Comment by francischeung** [comment]
True. That is my last resort. 

I'd rather send the appropriate claims for the requested resource in the access token when I access the API layer. That way the API layer can just interrogate the claims in the bearer token.

**Comment by brockallen** [comment]
So that's what scopes model and our scope claims config allows. 

-Brock

**Comment by francischeung** [comment]
Is there a way to extend the token service/endpoint to fetch claims from a service related to the scopes requested?

**Comment by leastprivilege** [comment]
IUserService, IClaimsProvider, ITokenService, ITokenSigningService

(in this order. from recommend to not so recommended [aka you exactly need to know what you are doing])

**Comment by AlexFree** [comment]
Sorry for comment, 
i was also looking for a possibility to add custom claim for access token. and i noticed that RequestClientCredentialsAsync method gets extra parameter. i couldn't find any info about this.
So, the question, for what this parameter exists and what can i pass thru it? thanks.
