### ISSUE TITLE
Return refresh token expiration from token endpoint

### ISSUE THREAD

**Issue by ayoung** [IdentityServer/IdentityServer3#1971]
Is there a way to return the refresh token expiration from the token endpoint?

```json
{
       "access_token":"xxxxxxxxxxxx",
       "token_type":"example",
       "expires_in":3600,
       "refresh_token":"xxxxxxxxxxxxxxxxxxxx",
       "refresh_expires_in":"15000"
}
```

**Comment by brockallen** [comment]
That's not covered in the spec and is sort of tricky anyway because it can be revoked at any time.

**Comment by ayoung** [comment]
The OAuth 2 spec allows for custom parameters in the response. http://tools.ietf.org/html/rfc6749#section-4.1.4

So I guess this is more of a question of whether ID3 allows for adding custom parameters.

**Comment by ayoung** [comment]
"it can be revoked at any time". You could say the same thing about the access_token's expires_in value, no?

**Comment by brockallen** [comment]
Sure, or if it's a reference token if can be revoked by the end user.

**Comment by leastprivilege** [comment]
we don't allow custom response parameters right now. If you think that is necessary, please open a separate issue with a feature description (and how you envision usage).
