### ISSUE TITLE
UserInfo endpoint does not recognize POST requests in IE9

### ISSUE THREAD

**Issue by jkabonick-ft** [IdentityServer/IdentityServer3#1973]
In order to do cross-domain requests in IE9, the XDomainRequest object must be used. When using this, however, my team has come across several problems. 

1) The XDomainRequest object does not allow headers to be set explicitly.
This means that we cannot set the authorization header in the GET request to be the bearer token for using the UserInfo endpoint. This lead us to do a POST to the UserInfo endpoint which is a supported operation. However this lead to the following problem.

2) The XDomainRequest does not send a ContentType header or sends ContentType of text/plain (this [post](http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx) documents some of the limitations).

The ValidateAsync method in the BearerTokenUsageValidator has the following:

    if (request.Method == HttpMethod.Post && request.Content.IsFormData())
    {
        result = await ValidatePostBodyAsync(request);
        if (result.TokenFound)
        {
            return result;
        }
    }
The `request.Content.IsFormData()` is [documented](https://msdn.microsoft.com/en-us/library/system.net.http.httpcontentformdataextensions.isformdata(v=vs.118).aspx) to return true if the content is HTML form URL-encoded data, and when using the XDomainRequest this is not the case as the ContentType is null when I'm debugging a call from IE.

The blog post I referenced above regarding the limitations of the XDomainRequest suggests parsing the request body into name-value pairs when receiving requests from XDomainRequest objects. 

Perhaps another check could be added in the ValidateAsync method for the case when the incoming request is a POST and contains a null or text/plain ContentType (however the post also mentions that as of 2014 it appeared no ContentType was being specified, so text/plain may not be needed). In addition to this, the ValidatePostBodyAsync method would need to not only check for form data via the ReadAsFormDataAsync method, but would also need to attempt to parse it into a Dictionary object if the ContentType is empty.

I will open another issue in the oidc-client/oidc-token-manager to actually use the XDomainRequest POST when interacting with the UserInfo endpoint from IE9.

**Comment by leastprivilege** [comment]
Did you fix it? Wanna discuss a PR?

**Comment by jkabonick-ft** [comment]
I didn't fix it in IdentityServer. After discussions with my team, we found that the apps we were creating didn't need to make the call to the user info endpoint so we disabled that call in the oidc-token-manager settings.
