### ISSUE TITLE
Accessing route data for a request in Web API hosted on OWIN pipeline

### ISSUE THREAD

**Issue by indranilatcal** [IdentityServer/IdentityServer3#1974]
Admittedly, this is not a question related to Id Server3, but ASP.NET Web API in general. I had a message handler wired into the Web API pipeline wherein I access some fragments of route data for a request. We try to access the routedatacollection as request.GetRequestContext().RouteData, where request is an instance of HttpRequestMessage. This works on normal hosting in IIS. But the moment, I introduce OWIN hosting for Web Api, request.GetRequestContext().RouteData gets returned as null in the message handler. Could I be missing something very basic when it comes to OWIN?

**Comment by leastprivilege** [comment]
Sorry - as you say yourself - this is unrelated to this repository.
