### ISSUE TITLE
Consider adding viewport meta tag to default layout asset

### ISSUE THREAD

**Issue by NickSykes** [IdentityServer/IdentityServer3#1975]
Using 1.6.3 making a local auth login for mobile sites is cumbersome because this tag is missing. In my case overriding _layout.html is breaking the retrieval of "scripts.2.0.0.js" for some reason - but I'm not sure if this step should necessary.

Thanks!

**Comment by brockallen** [comment]
What would it look like?

**Comment by NickSykes** [comment]
I ended up getting it to work. The version we are using was targeting scripts.js and not scripts.2.0.0.js (duh). However I think the viewport change is likely still a good one.

Since you already target and use Bootstrap the only addition would be the following to the layout.html asset:

<meta name="viewport" content="width=device-width, initial-scale=1">

That way mobile devices will scale correctly on your prebuilt assets.

Product is awesome so far, you guys have done an amazing job.

**Comment by NickSykes** [comment]
meta name="viewport" content="width=device-width, initial-scale=1"

**Comment by brockallen** [comment]
Done on dev.
