### ISSUE TITLE
Scope and Client Management Platform

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#1976]
Hello,

I wonder if there's something like identity manager for the identity server for configuring scopes and clients. I started on a project writing REST-Services for the EF-Framework (Client/Scopestore) and the views, but maybe there is already something on github I missed?

Greetings

**Comment by leastprivilege** [comment]
No - nothing so far.

**Comment by leastprivilege** [comment]
feel free to start a contrib project.
