### ISSUE TITLE
Accessing HttpContext in Custom Grant Validator

### ISSUE THREAD

**Issue by dknaack** [IdentityServer/IdentityServer3#1978]
Hey,

i need the IPAddress from the Request for validation inside a custom grant validator. 
How can i access this data? System.Web.HttpContext.Current is null and i cant figure out how to get the ip address.

thanks in advance!

**Comment by leastprivilege** [comment]
inject the OwinEnvironmentService

**Comment by dknaack** [comment]
thanks for the fast answer. Any information on how i can do it?

**Comment by dknaack** [comment]
Great! Thanks a lot!
