### ISSUE TITLE
Call to Revocation endpoint from Javascript client fails with 405

### ISSUE THREAD

**Issue by eskitek** [IdentityServer/IdentityServer3#1979]
We have an AngularJS client that is using the Resource Owner flow to authenticate against our own Identity Server. When the user logs out of the app, we'd like to revoke the access token (we are using reference tokens). Reading the advice in related issue #1337, and the Revocation endpoint documentation, it seems like this should be possible.

The issue we're running into is that the browser is pre-flighting the POST request to the Revocation endpoint with an OPTIONS request, but it doesn't seem like the Revocation endpoint allows the OPTIONS method (We get a 405 response with the message - The requested resource does not support http method 'OPTIONS'). Pre-flights to the UserInfo and Token endpoints work as expected, so it doesn't seem like we have a general OPTIONS or CORS problem.

Digging into the code a bit, it looks like only certain endpoints have CORS enabled via the CorsPaths constant, and the Revocation endpoint isn't one of them. Is this by design? If so, is it possible for a Javascript client using the Resource Owner flow to somehow revoke an access token on logout?

Many thanks in advance.

**Comment by leastprivilege** [comment]
right now this is not enabled. we need to discuss that @brockallen

**Comment by leastprivilege** [comment]
We didn't have the chance to discuss this yet - but generally speaking - I guess if we allow CORS requests to the token endpoint - we should also allow them to the revocation endpoint as well.

You are aware that you can only revoke reference tokens, yes?

**Comment by eskitek** [comment]
Yes, we are aware that only reference tokens (and refresh tokens) can be revoked. Thanks!

**Comment by leastprivilege** [comment]
OK - we will add the CORS support for the revocation endpoint. In the meanwhile you could also implement token revocation at logout time using the SignOutAsync method on the user service. Would that also work for you?

**Comment by brockallen** [comment]
Ok, done on dev. Also, I added a JS-based resource owner sample to the clients repo.

**Comment by eskitek** [comment]
Many thanks!

**Comment by sudipster** [comment]
@leastprivilege on "In the meanwhile you could also implement token revocation at logout time using the SignOutAsync method on the user service.", I need to know the client secret in order to revoke the token.. But I may not know the client secret though. It is saved as a hashed value with ids.  How is it possible to call revocation ep in SignOutAsync?

**Comment by leastprivilege** [comment]
You can directly interact with the token handler store (or even the permission store) in the user service at logout time.

**Comment by sudipster** [comment]
Thanks @leastprivilege.
