### ISSUE TITLE
How to change access token format ?

### ISSUE THREAD

**Issue by vish-k** [IdentityServer/IdentityServer3#1980]
Hello,
How do I change the access token format from the default -
{
  "aud": "https://dummy-aud",
  "iss": "https://dummy_issuer",
  "nbf": "1443812928",
  "exp": "1443816528",
  "client_id": "carbon",
  "scope": "offline_access",
  "sub": "dummy-sub",
  "amr": "password",
  "auth_time": "1443812927",
  "idp": "idsrv"
}
?

Do I need to customize access token creation (ITokenService) or  validation (ICustomTokenValidator) ?

**Comment by brockallen** [comment]
Can you elaborate what you mean?

**Comment by vish-k** [comment]
I need to change format of json returned on token validation instead of the
default json (mentioned in previous post ).

When our resource server reaches out to validate access token received from
client, we want to return a specific json that's different than the one
currently returned.

On Fri, Oct 2, 2015, 5:11 PM Brock Allen <notifications@github.com> wrote:

> Can you elaborate what you mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3/issues/1980#issuecomment-145156158>
> .
>
-- 

Regards,
   Vish

**Comment by brockallen** [comment]
Why don't you just convert it at the resource server?

**Comment by vish-k** [comment]
Resource server already works with other auth servers and in some scenarios
going to use identityserver3. Also I don't have control over resource
server customization.

Is there any hook to in identityserver3 to change json returned on token
validation?

On Fri, Oct 2, 2015, 7:40 PM Brock Allen <notifications@github.com> wrote:

> Why don't you just convert it at the resource server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3/issues/1980#issuecomment-145183921>
> .
>
-- 

Regards,
   Vish

**Comment by leastprivilege** [comment]
Not sure what you mean with format. But you can change the contents using the ITokenService and take over token creation completely in the ITokenSigningService.

**Comment by vish-k** [comment]
By format, I mean to provide following json on token validation-

{
"expires_in": "1443816528",
"claims": {list of claims},
"scope": "offline_access",
}

Instead of-
> {
> "aud": "https://dummy-aud",
> "iss": "https://dummy_issuer",
> "nbf": "1443812928",
> "exp": "1443816528",
> "client_id": "carbon",
> "scope": "offline_access",
> "sub": "dummy-sub",
> "amr": "password",
> "auth_time": "1443812927",
> "idp": "idsrv"
> }

On Sat, Oct 3, 2015, 2:40 AM Dominick Baier <notifications@github.com>
wrote:

> Not sure what you mean with format. But you can change the contents using
> the ITokenService and take over token creation completely in the
> ITokenSigningService.
>
> Sent from my iPad
>
> > On 02 Oct 2015, at 21:30, vish-k <notifications@github.com> wrote:
> >
> > Hello,
> > How do I change the access token format from the default -
> > {
> > "aud": "https://dummy-aud",
> > "iss": "https://dummy_issuer",
> > "nbf": "1443812928",
> > "exp": "1443816528",
> > "client_id": "carbon",
> > "scope": "offline_access",
> > "sub": "dummy-sub",
> > "amr": "password",
> > "auth_time": "1443812927",
> > "idp": "idsrv"
> > }
> > ?
> >
> > Do I need to customize access token creation (ITokenService) or
> validation (ICustomTokenValidator) ?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3/issues/1980#issuecomment-145210099>
> .
>
-- 

Regards,
   Vish

**Comment by leastprivilege** [comment]
ITokenSigningService then.

**Comment by vish-k** [comment]
Thanks! I had to implement ICustomTokenValidator to change the format of the json returned to resource server upon token validation.

Appreciate your help.
