### ISSUE TITLE
Using NLog as the logprovider.

### ISSUE THREAD

**Issue by gwinnem** [IdentityServer/IdentityServer3#1982]
In my previous setup of the IdentityServer I have the following:
LogProvider.SetCurrentLogProvider(new NLogLogProvider());

In the latest version of IdentityServer the NLogLogProvider class is not found.
Did it change to something else or ?

**Comment by leastprivilege** [comment]
Not necessary anymore. Check the docs.

**Comment by gwinnem** [comment]
Have checked the docs and the serilog example but not getting any further.

**Comment by leastprivilege** [comment]
it says - 

"Liblog picks up any of the following logging libraries **automatically**"
