### ISSUE TITLE
Q: Multi tenant and identity provider restrictions?

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3#1983]
In a multi tenant scenario it would be generally the tenant deciding what types of authentication are acceptable/required. 
On the other hand, the identity provider restrictions in IdSrv are per client. So if I have a single client serving multiple tenants it seems I can't limit the login choices per tenant. And it wouldn't make sense to show a tenant choices that their users are not allowed to make.

What would be the best way to handle this?

**Comment by brockallen** [comment]
We're not designed for multi-tenancy. The only thing I can suggest is a custom view service that filters the `AdditionalLinks` on the `LoginViewModel` when rendering the login page.
