### ISSUE TITLE
AlwaysInclude not giving claims in id token

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#1984]
I have a bunch of scope claims set up with alwaysInclude=true for my profile identity scope, but I'm not seeing them returned from authorize endpoint when requesting profile scope. Id token is basically unchanged.

I have verified that scope claims are set up in the database with the correct value in the column and after some source code digging I end up in the DefaultClaimsProvider.GetIdentityClaimsAsync where I see that none of the scope claims for the profile scope have correct value for AlwaysIncludeInIdToken flag.

Any idea what might be wrong here?

**Comment by brockallen** [comment]
profile scope only affects the claims in the id_token (since it's an identity scope). you need a resource scope with scope claims if you want claims in the access token.

**Comment by snothub** [comment]
I hadn't heard of it until now, so I'll have to say no, I don't have scope caching.

**Comment by brockallen** [comment]
Not sure then -- you'll have to debug it.

**Comment by snothub** [comment]
Weird, everything is suddenly normal, no idea how/why. Sorry about that.
