### ISSUE TITLE
Why is cookie option HttpOnly hard coded to false in SessionCookie?

### ISSUE THREAD

**Issue by neilcrowther** [IdentityServer/IdentityServer3#1985]
After running OWASP Zap, I get a number of alerts about the Identity Server cookie being accessible via java-script (which it considers a possible security issue).  After looking at the code it is hard coded this way, not configurable, so I assume that there must be a reason for this.  I've been Googling and looking though docs and issues but cannot find the reason why this is set to false.

Can anyone point me in the right direction so I can explain this when our site is next penetration tested and this comes up?

**Comment by leastprivilege** [comment]
The whole purpose of this cookie is to be accessed by JavaScript ;) It does not contain anything sensitive - think of it as a session "marker".

see here:
http://openid.net/specs/openid-connect-session-1_0.html

**Comment by neilcrowther** [comment]
Brilliant, that's exactly what I couldn't find (as I didn't know what to actually look for).  Thanks for the (very) fast response!
