### ISSUE TITLE
Add a cookie to track clients the user logged in

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#1986]
for HTTP based logout specs

**Comment by tillig** [comment]
I'm not sure how to vote on issues, but this would be a huge thing for me. As it stands, I'm going to have to figure out how to implement federated logout myself.

**Comment by leastprivilege** [comment]
We gonna add this feature soon (as well as the http-based logout spec).

**Comment by brockallen** [comment]
If the user has a persistent login cookie, how should it affect the client list cookie?

**Comment by brockallen** [comment]
PR started here: https://github.com/IdentityServer/IdentityServer3/pull/2096

**Comment by brockallen** [comment]
We need to issue the `sid` claim in the id_token, I think: https://openid.net/specs/openid-connect-logout-1_0.html#OPLogout

**Comment by brockallen** [comment]
I had to move clearing the session id cookie to the end session endpoint, but I don't like that. We need a better approach.

**Comment by brockallen** [comment]
done on dev
