### ISSUE TITLE
Sample which mocks headers?  

### ISSUE THREAD

**Issue by angelraffety** [IdentityServer/IdentityServer3#1987]
We found IdentityServer3 and are certain it will fulfill our needs.  As a matter of fact, we’ve proven that part in that we can read the headers in the PreAuthenticateAsync and transform it appropriately.  We have an issue with mocking requests, though.  
 
Have you ever had to mock an incoming request which will have authentication information in headers?  In the STS, we’re able to authenticate from the headers using the PreAuthenticateAsync method in a custom user service.  However, we haven’t figured out how to mock that incoming call correctly for local development. 
 
Any help would be greatly appreciated.  Please note we are not free to change the way in which we receive the authentication data.

**Comment by brockallen** [comment]
We do some of that in our unit tests. Some are better than others :/
