### ISSUE TITLE
Base64 images blocked by Content Security Policy in Firefox

### ISSUE THREAD

**Issue by iverds** [IdentityServer/IdentityServer3#1988]
I have a problem when using base64 images to display logos on the login-page.
The images are defined inn css like this:

```
background: url('data:image/png;base64,XYZ...)
```

It works in every browser except Firefox, which is blocking it with the message: 

```
Content Security Policy: The page's settings blocked the loading of a resource at data:image/png;base64, XYZ...
```

Am I doing anything wrong here, or should the content security policy settings be changed?

**Comment by vidarkongsli** [comment]
So, this occured in recent Firefox versions, right?

**Comment by iverds** [comment]
Yes. It works in version 39, and stopped working in version 40

**Comment by vidarkongsli** [comment]
This might be the culprit: https://www.mozilla.org/en-US/security/advisories/mfsa2015-91/
Updated in FF 40.

**Comment by vidarkongsli** [comment]
IdSrv sets img-src: *
It seems to me that it should be made possible to override this.

**Comment by brockallen** [comment]
FF 41 doesn't seem to have this problem

**Comment by vidarkongsli** [comment]
I upgraded FF from 40.0.3 to 41.0.1 and the problem persists

**Comment by brockallen** [comment]
Yea, I misspoke when I posted that. Does Chrome also do the same?

**Comment by vidarkongsli** [comment]
No, Chrome dos not do that, at least not in version 45.

**Comment by brockallen** [comment]
So Chrome also is lax according tot he CSP spec?

**Comment by brockallen** [comment]
@iverds I will comment here that if you use `data:image` in your CSS, then you will need to allow `data:` in the CSP. This means that if a client is registered with a logo URL and they provide a `data:image` for their logo you'll be trusting it.

**Comment by brockallen** [comment]
Ok, will this address the problem: #1991?

**Comment by brockallen** [comment]
Can anyone double check that 2.0.2 has addressed this issue?

**Comment by vidarkongsli** [comment]
Works for our solution. We have set the `CspOptions` as follows:
```c-sharp
CspOptions = new CspOptions
{
    Enabled = true,
    ImgSrc = "* data:"
    ...
}
```
This fixes the issue with `data:` urls in FF.

**Comment by brockallen** [comment]
Ok, thx for following up.

**Comment by CKGrafico** [comment]
Thanks @vidarkongsli you helped me a lot!
