### ISSUE TITLE
Q: Local authentication with multiple "blockers" for full login?

### ISSUE THREAD

**Issue by david-ernstsson-stratsys** [IdentityServer/IdentityServer3#1989]
The partial login works wonderfully when there is one and only one blocker for a successful local login and afterwards user can easily be redirected to the resume-url. However, given a simple scenario with multiple "blockers" for a full login we do not find any built-in support for and this feels like a quite common issue that should have come up for discussion at some point. 

(When looking through source code this seems to be supported when external partial login (await userService.AuthenticateExternalAsync(externalContext);) but the partial login for local authentication is missing this feature.

Anything were missing or any thoughts on this for future development?

Simple scenario:
A user has to accept latest eula -> partial login.
A user has to validate email when local registration -> partial login.

/regards, David

**Comment by brockallen** [comment]
Yep, we knew of this issue. In 2.0.0 we added a new `PostAuthenticate` where you can consolidate all of your partial login logic: 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/IUserService.cs#L55

**Comment by david-ernstsson-stratsys** [comment]
Awesome, will check it out. Recently migrated to 2.0.0.

**Comment by brockallen** [comment]
Open a new issue if you have any further issues.
