### ISSUE TITLE
Role not set on IPrincipal (Web API, AccessTokenValidation)?

### ISSUE THREAD

**Issue by KevinDockx** [IdentityServer/IdentityServer3#1990]
When using IdentityServer3.AccessTokenValidation, passing in a role claim through the access token to the API, I can inspect the ClaimsIdentity and see that there's a role claim - exactly as described in the documentation (https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html => at the very end)

However, calling IsInRole on IPrincipal, eg: this.User.IsInRole("Admin") will return false, even though the role is there.  So it looks like the role isn't set on IPrincipal, yet is in the Claims collection.

I was wondering: is this by design, or is it a bug?

**Comment by brockallen** [comment]
What's the type being used? `"role"` or `"http://schemas.microsoft.com/ws/2008/06/identity/claims/role"`

**Comment by KevinDockx** [comment]
That pointed me in the right direction!  The claim in the token is "role", but once I'm at Web API level, that's converted to "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"; so I figured that's the default JwtSecurityTokenHandler.InboundClaimTypeMap dictionary at work.  I reset that one to an empty dictionary, which fixes the problem as now the "role" claim isn't mapped to http://schemas... anymore.  

Thanks for your help! :)
