### ISSUE TITLE
Add custom output parameters from token endpoint

### ISSUE THREAD

**Issue by ayoung** [IdentityServer/IdentityServer3#1992]
This is related to #1971.

Add a feature that would allow for custom output parameters from the token endpoint as is allowed by [OAuth 2.0 section 4.1.4](http://tools.ietf.org/html/rfc6749#section-4.1.4). In that example output it illustrates an example output param called `example_parameter`.

```http
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Cache-Control: no-store
Pragma: no-cache

 {
    "access_token": "2YotnFZFEjr1zCsicMWpAA",
    "token_type": "example",
    "expires_in": 3600,
    "refresh_token": "tGzv3JOkF0XG5Qx2TlKWIA",
    "example_parameter": "example_value"
 }
```

One possible use for this would be to allow clients to discover refresh token expiration and/or absolute refresh token expiration so that clients would know when they should have to request for a new access token without any previous out-of-band or backchannel communication.

```json
 {
    "access_token": "2YotnFZFEjr1zCsicMWpAA",
    "token_type": "example",
    "expires_in": 3600,
    "refresh_token": "tGzv3JOkF0XG5Qx2TlKWIA",
    "refresh_expires_in": "15000",
    "refresh_abs_expires_in":"30000"
 }
```

**Comment by leastprivilege** [comment]
OK - then write up a proposal. Where in the pipeline should that happen, what data would need to be available at that point etc.

**Comment by ayoung** [comment]
I was looking through the source and couldn't find a clean place to implement this. Especially since `TokenResponseDto` is a static class. We would probably need to make that an `Dictionary <string, object>` where we could extend the properties dynamically.

**Comment by leastprivilege** [comment]
Sure. But where do you want to set the data?

**Comment by leastprivilege** [comment]
tracked here now: https://github.com/IdentityServer/IdentityServer3/issues/2290
