### ISSUE TITLE
I am now Upgrading from Idrsv3 ver 1.0 to 2.0.1

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#1993]
In the latest Identity server ver 2.01 where can i change the login logout page to My own design because in the Previous Idrsv3 ver 1.0 i have made changes to the login  with my custom design now those folder was not Present in the Content Folder, i think Now it is Moved to Identity Server., Now if i want to change design Part where can change those files

**Comment by brockallen** [comment]
The folder was renamed to "templates": https://github.com/IdentityServer/IdentityServer3/releases/tag/2.0.0

**Comment by RajMondaz** [comment]
Hi Brokallen , Previously i have Implemented Idrsv3 using CustomUserService for customize the login workflow But now this template Folder is there in EmbeddedAssetsViewService But in this i can't do  the customize for the login workflow.. if i want to change the design in the CustomUserService How to do that.. Because now in the latest update that view folder not there.

**Comment by brockallen** [comment]
For new questions, open new issues please. If your first question is answered, then please close the issue.

**Comment by RajMondaz** [comment]
OK.
