### ISSUE TITLE
identity server token issue

### ISSUE THREAD

**Issue by red9811** [IdentityServer/IdentityServer3#1994]
Hi,
     I'm new to identity server v3 and currently facing a critical issue. I was able to configure the server on my local machine and able to test using Simplest OAuth Walkthrough example. We moved the code onto our Dev server and getting an "Internal Server Error" while trying to generate a token. We have the SSL cert in place and i'm using the sample signing certificate "idsrv3test.pfx" located in bin directory.

Here are the logs from the logs table

HTTP Request
{
  "Method": {
    "Method": "POST"
  },
  "Url": "https://api-wsdev.cdc.gov/ets/identity/connect/token",
  "Headers": [
    {
      "Key": "Connection",
      "Value": [
        "Keep-Alive"
      ]
    },
    {
      "Key": "Authorization",
      "Value": [
        "Basic cm9jbGllbnQ6c2VjcmV0"
      ]
    },
    {
      "Key": "Expect",
      "Value": [
        "100-continue"
      ]
    },
    {
      "Key": "Host",
      "Value": [
        "api-wsdev.cdc.gov"
      ]
    }
  ],
  "Body": "grant_type=password&username=XXXX_SA&password=XXXXX&scope=XXXX"
}
Start token request
Start client validation
Unhandled exception
HTTP Response
{
  "StatusCode": "InternalServerError",
  "Headers": [],
  "Body": "{\"Message\":\"An error has occurred.\"}"
}

Do I need to configure the PFX cert on the server instead of loading from bin directory?

**Comment by brockallen** [comment]
Enable logging and see what it says.
