### ISSUE TITLE
How can i make custom design for login page if i am using CustomUserService Sample.

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#2000]
Hi Brokallen , Previously i have Implemented Idrsv3 using CustomUserService for customize the login workflow But now this template Folder is there in EmbeddedAssetsViewService But in this i can't do the customize for the login workflow.. if i want to change the design in the CustomUserService How to do that.. Because now in the latest update that view folder not there.

**Comment by brockallen** [comment]
The view service is different than the user service. The user service is where you can control the workflow. The view service is where you configure the HTML to be displayed for specific views. 

I guess I don't understand the issue you're having.
