### ISSUE TITLE
Question about Startup Ordering

### ISSUE THREAD

**Issue by ryanvgates** [IdentityServer/IdentityServer3#2002]
I experienced an issue such that depending upon the ordering of the startup class, the trusting service would throw 401 Unauthorized for legitimate access tokens. I was able to figure out the right ordering and I noticed a similar issue #1264. 

Why would the ordering matter in the startup? I have included examples below.

The below works great.

```csharp
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
{
	
	Authority = "https://localhost:44333/",
	RequiredScopes = new[] { "WritingTools" }
});

// web api configuration
var config = new HttpConfiguration();
WebApiConfig.Register(config);

app.UseWebApi(config);
```

This cases 401 Unauthorized for legitimate access tokens.

```csharp
public void Configuration(IAppBuilder app)
{

	// web api configuration
	var config = new HttpConfiguration();
	WebApiConfig.Register(config);

	app.UseWebApi(config);

	app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
	{
		
		Authority = "https://localhost:44333/",
		RequiredScopes = new[] { "WritingTools" }
	});
}
```

**Comment by leastprivilege** [comment]
Yes - order matters absolutely. Think of the Katana pipeline as a linked list of middleware. If token validation comes after web api - the web api will never see the principal.
