### ISSUE TITLE
Any real , detailed tutorial on IdentityServer3?

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer3#2003]
I have been frustrated with learning the technical details and low level implementation of the IdentityServer3 in my projects. I know this is apparently an amazing package but personally I have found the documentation not very helpful. 
Most of the examples and mini-tutorial pieces assume you know 50% of what you should know and although I can see the real professionals are using it well, for us beginners it is a hassle to get it under control.

I was wondering, is there any book, or even a commercial tutorial or whatever that can actually teach the IdentityServer3 from scratch?

**Comment by leastprivilege** [comment]
The most basic tutorials we have are the two walkthroughs in the docs.

Also check the training section in the resources.

**Comment by brockallen** [comment]
@behrooz66 One additional place to to start learning would be with the OpenID Connect (and OAuth2) specification. This is what IdentityServer targets so the more you understand the spec the more you will understand how/why/what IdentityServer is.

**Comment by behrooz66** [comment]
Thanks guys! The thing is as a new comer to this topic, I find a big gap between the stage of concepts and stage of advanced implementations. 
I can go through the documents, and easily get all the concepts. Then there are also sample codes demonstrating very simple scenarios, and suddenly the rest of them have very advanced implementations and for someone like me it is very hard to create this piece in the middle on my own. 

It might simply be my idiocy(!) as I haven't seen a lot of complains from the others, but for example I have been trying to implement a role-based authorization environment that provides access for uses both by username & password and external login for a web application client written in angular, and I haven't been able to, and it has been two weeks. 

I know it is probably my wrong approach of learning but just needed to get it out of my system!
