### ISSUE TITLE
Unity Container WebApi Sample

### ISSUE THREAD

**Issue by avmp2208** [IdentityServer/IdentityServer3#2004]
Hello guys, I hope you are all fine, this time I have a little question I guess,

I'm trying to use this project from your samples,
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/SampleAspNetWebApi
for web api services, and I'd like to use Unity as my Dependency Injection strategy and I got the nuget package Unity.WebApi so It creates a new file inside my app_start folder where we have to register our types so in my case I have just one interface like this

var container = new UnityContainer();
container.RegisterType<IDataContextAsync, LogicDbContext>(new PerResolveLifetimeManager());
container.RegisterType<IRepositoryProvider, RepositoryProvider>(new PerResolveLifetimeManager(), new InjectionConstructor(new object[] { new RepositoryFactories() }));
container.RegisterType<IUnitOfWorkAsync, UnitOfWork>(new PerResolveLifetimeManager());
container.RegisterType<IApp, AppService>();

and in my Apicontroller just one constructor 

private readonly IApp _App;
private TDataController(IApp app)
{    _App = app; }

and this my configuration method at the startup class
public void Configuration(IAppBuilder app)
{
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://localhost:44333/core",
                    RequiredScopes = new[] { "write" }
                });
			UnityConfig.RegisterComponents();
            app.UseWebApi(WebApiConfig.Register());
}

so very simple, isn't it?
But I don't know what i'm missing, because the thing is that when I try to invoke one simple action from the controller it trhows me and error:

{"Message":"An error has occurred.","ExceptionMessage":"An error occurred when trying to create a controller of type 'TDataController'. Make sure that the controller has a parameterless public constructor.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at ..................

I hope you could help with this, thanks in advance.
Bes regards

**Comment by leastprivilege** [comment]
Can we please keep the issue tracker focused on IdentityServer. thanks.
