### ISSUE TITLE
Social Login Provider Trouble

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#2005]
Hello,

my ID Server is running on IIS with following host entry:
127.0.0.1	identity.de
so the server is running on:
https://identity.de/core/

I want to use social login providers and I'm testing with google. 
I created an app, activated Google+ API and entered the redirect url:
https://identity.de/core/signin-google

I get the consent page, but then, after some seconds loading, back on the identity server, i get error: "There was an error logging into the external provider. The error message is: access_denied"

This is what i get back:
state=8kbSjSADU7rm_l4PBcMmE3JRvyMVW5tD2FjIMc5Xv28EFLcafbXaLd0qsoXBLkOFSgD5W326NilgMbk2gCejH3vb3f4L9MT7z
T9dMpWvXCe9z9vFCNM0LojXGSjAj3xE1ptUsferKA4knR7M2NX-Z8xYKbSM1V_9GZc5Hb3eo8mnNaPKHYy-K4r5XFo2kyov1JqyuMMEJ
tDCrzI4g5lYJTjbgdVk3lUY_hE2J6_DIz9-eB8EjxVvcKeYJJ8Q6Bzym9NrEGhBbUffHaZNA3vVV620dm0nYxqRGQm4BvGHlRv0Gr6rJt
ANecVzWF1-C5c3
&code=4/gc-nffdF43SeIgtwDey-bNFAwY...
&authuser=0
&prompt=consent
&session_state=ff930f62f476e280f29c5f09ba6a83215b774460..eb94#

Is it even possible to specify a redirect uri that I defined in windows host config ?
Is it normal that the session_state contains ".." ?

Thanks

**Comment by leastprivilege** [comment]
Your server must open a back-channel with Google - are outgoing connections from your server allowed?

Also Katana logging would probably reveal more details.

**Comment by senj** [comment]
Oh thank you very much. Thanks to your hint if checked the fiddler connection and my connection really got blocked.
