### ISSUE TITLE
How to use X509Certificate for ResourceOwner Flow in Two-factor authentication with username/password?

### ISSUE THREAD

**Issue by mirecg** [IdentityServer/IdentityServer3#2007]
Hi, 

I would like to ask how to implement two-factor authentication where the second factor could be X509Certificate or SMS code depending on the user.
I need to support it in several types of clients. In a web application, in a web service and in a desktop app.
1. For interactive application (web app or desktop app) it should allow authenticate with username/password with the optional X509Certificate or SMS authorization code.
2. For service type of application (WCF service) it should allow to authenticate with username/password + X509Certificate.

In noticed that for web app there should be partial login concept suitable, but I'm not familiar with it.
But how to achive the second scenario. For username/password there is option to user ResourceOwner flow. But what to use for X509Certificate or SMS for authenticating user as a second factor?

Thank you

**Comment by brockallen** [comment]
For 1 look at the ASP.NET samples that use partial logins. For 2 your client has to implement that all (and that's a good reason why resource owner password flow should be avoided if possible).

**Comment by mirecg** [comment]
Hi, that was my question, how to do it on a WCF service that should supply username/password credentials with certificate to identity server to obtain an identity token?
Can you help me with this type of scenario. Do you have some example? Or can you provide some pseudo example what should I do/call? 

Thank you

**Comment by brockallen** [comment]
Yes, we have a whole repository of samples: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients

There's a resource owner samples, for allowing the client to collect the uid/pwd. There's also a WCF samples to show how to use implicit flow from a desktop client.

**Comment by mirecg** [comment]
Hi, 

of course, I know that repository.
If I found my described scenario in the samples I wouldn't ask for help. Sorry, but this type of answers isn't very constructive.

Regarding uid/pwd, this is OK, the samples are straitforward, but any of the samples show how to request token with certificate as an additional step to uid/pwd. What I'm trying to achieve is, that we have WCF service witch has message based security with X509CertificateToken and UserNamePasswordToken, which are validated on the service against our custom repository of users and certificates. 
To have better idea about my situation, I have WCF service which is consumed by our customers. From the customer point of view, there should be no change in way they consume the service. The only change will be in the service backend where I need to replace local validation of credentials to centralized using IdentityProvider3.

**Comment by leastprivilege** [comment]
Resource owner flow does not really support 2FA. You can access client certificates (if present) by inspecting the OWIN environment. For that inject the OwinEnvironmentService into the UserService.

**Comment by mirecg** [comment]
Thank you. This is only usable if the service is secured on the transport level using client certificate. I have also case when the certificates comes at message level, where I would need to pass it to userservice in a different way.

I found in the samples acr_values parameter which could be sent with RequestResourceOwnerPasswordAsync call. Do you think this is suitable for passing the certificate to a userservice along with uid/pwd? 

Does it have limitations or specific format? According to https://identityserver.github.io/Documentation/docs/endpoints/authorization.html there is some type name:value pair format, [name1]:[value1] [name2]:[value2], where name:value pairs are separated by space character, am I right?

**Comment by leastprivilege** [comment]
No - you can't simply send a cert 

you need to prove ownership of the private key - e.g. by signing something (and make that also protected from replay attacks)

**Comment by mirecg** [comment]
Yes, you are right, but the described case the certificate can come from different security contexts:
1. from transport layer as a result of ssl client certificate authentication at some business service endpoint
2. from message layer as a result of WS-Security applied on the soap-message (signed body, tokens, ...)

In both contexts the certificate needs to be validated at the backend against user database. 

How can I achieve this without sending a certificate to IdentityServer? The trust on the supplied certificate could be made trough a trust of a client that is sending the certificate in RequestResourceOwnerPasswordAsync flow.

**Comment by leastprivilege** [comment]
I don't know -I never tried that myself.

**Comment by mirecg** [comment]
Hi, there's internal limit on the length of acr_values, which allows to pass only 300 characters.
Is it possible to get it unlimitted or to allow more charecters? If I want to transfer the whole certificate to a userservice I need the limit much higher then 300 characters. Is there any technical limitation or do you know some other way how to pass the certificate to a userservice?

**Comment by brockallen** [comment]
For new topics, please open new issues. As for your question -- we have an open issue for that I think somewhere. Please search for it and you can comment there.
