### ISSUE TITLE
How do users get authorised using IdentityServerBearerTokenAuthenticationOptions in a webAPI 2.0 application?

### ISSUE THREAD

**Issue by setiseeker** [IdentityServer/IdentityServer3#2008]
Hi,

I have a webapi 2 api and have setup an IdentityServer3 instance.

I am trying to configure the API to use Bearer tokens from the Identity Server to authenticate and authorize incoming calls to the api from 3rd party apps.

My API is configured using OWIN and the following code:
            app.UseIdentityServerBearerTokenAuthentication(new      IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://myserver.com/identityServer/core",
                AuthenticationMode = AuthenticationMode.Active,
                ValidationMode = ValidationMode.ValidationEndpoint,
                RequiredScopes = new[] { "email" }
            });

If i look at the Identity Server logs, my API is receiving the token and validating that token successfully against the Identity Server (when a client app calls) using the above code, but after that my API returns 401's. I assume something is not getting set or configured to handle this.

So my question is, how do I validate, authorize or set the claims for a token once it is received and validated by the Identity server. 

I do apologize for a question that must have a simple answer, but I believe I have missed something in the documentation or the samples about how to resolve this.

Thanks

**Comment by brockallen** [comment]
Can you debug this by putting middleware after the `UseIdentityServerBearerTokenAuthentication` to see if the `User` has been set?

**Comment by setiseeker** [comment]
Thanks for the quick reply. 

How would I set that up?

**Comment by brockallen** [comment]
Check the Katana docs from Microsoft.

**Comment by setiseeker** [comment]
Sorry for the slow reply.

I have added this code into the pipeline, just after setting up: UseIdentityServerBearerTokenAuthentication.

 app.Use((context, continuation) =>
            {
                if (context.Authentication.User != null && context.Authentication.User.Identity != null && context.Authentication.User.Identity.IsAuthenticated)
                    return continuation();
                return continuation();
            });

Authentication.User.Identity.IsAuthenticated is comming back as true, but the name is null and if I view the claims, I am not seeing anything like username or name.

I think I am misunderstanding something, just not sure what or where.

Could this be how I configure the clients or users on the server side?

Should I supply that configuration?

thanks for the help.

**Comment by setiseeker** [comment]
I have resolved my issue. 
The problem was Scopes and Scope Claims. Working through the MVC Authentication Sample Application several times highlighted my issue.

Thanks
