### ISSUE TITLE
Logout and re login with out redirection to login screen

### ISSUE THREAD

**Issue by vinayhfs** [IdentityServer/IdentityServer3#2009]
have scenario where user is already login but now he wants login with different user (say like he registered as new user). 
I am right now using OWIN environment extensions IssueCookie method for relogin as I don't want redirect user to login screen again. But in this case looks like old cookie also present and I am getting data according to old logged in user. Is there way to remove old cookie and create new without going to login screen again. Also is there way to obtain authentication ticket using extensions methods?

**Comment by brockallen** [comment]
We have some extension methods in IdSvr to issue the login cookie to IdentityServer: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinEnvironmentExtensions.cs

This means the page where the user registers or creates a new user will have to be hosted with IdSvr.

**Comment by vinayhfs** [comment]
Is there any extension method for jut log out? Which will sign out and remove cookie.
