### ISSUE TITLE
Login within MVC client without redirecting to IdSrv

### ISSUE THREAD

**Issue by ShieldPad** [IdentityServer/IdentityServer3#2010]
*Design goal*
I would like to develop an architecture where my IdentityServer (together with MembershipReboot) is hosted separately from (1) an MVC Client, (2) Eventually an iPhone application, and (3) eventually APIs. Ideally the user should not be redirected to the IdentityServer when logging in within the MVC client.

*Solution - is this OK?*
I could find several MVC Client examples within the samples repository, but they all redirected the user. Would something like the following be an OK solution or does it open up any security holes?

```C#
    public class AccountController : Controller
    {

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiforgeryToken()]
        public async Task<ActionResult> Login(string username, string password)
        {
            var token = await GetUserToken(username, password);
            var claimsIdentity = await getUserInfo(token.AccessToken);
            var id = new ClaimsIdentity(claimsIdentity.Claims, "cookies");
            Request.GetOwinContext().Authentication.SignIn(id);
            return View();
        }

        private async Task<TokenResponse> GetUserToken(string username, string password)
        {
            var client = new TokenClient(
                "https://localhost:44333/core/connect/token",
                "clientId",
                "clientSecrett");
            var response = await client.RequestResourceOwnerPasswordAsync(username, password, "openid all_claims");
            return response;
        }

        private async Task<ClaimsIdentity> getUserInfo(string token)
        {
            var client = new UserInfoClient(new Uri("https://localhost:44333/core/connect/userinfo"), token);
            var response = await client.GetAsync();
            var identity = response.GetClaimsIdentity();
            return identity;
        }
    }


```

**Comment by brockallen** [comment]
Part of SSO is redirecting the user to a centralized SSO provider. If you don't redirect the there's an approach for that (called resource owner password flow), but then you lose SSO.

**Comment by ShieldPad** [comment]
Thanks for the fast response Brock.

At the moment I don't think we'll need SSO but I will keep it in mind if the requirements change.
