### ISSUE TITLE
cross-origin requests that require preflight

### ISSUE THREAD

**Issue by vinayhfs** [IdentityServer/IdentityServer3#2011]
I am getting following error - How can I fix this error. 
I have already set CorsPolicy = CorsPolicy.AllowAll configuration.

XMLHttpRequest cannot load https://xxx.abc.com/api/SelectLogin/f3b36f89-1ef3-4fc4-8fcd-1d215d629339?_=1444391686060. The request was redirected to 'https://sso.abc.com/identity/connect/authorize?client_id=deloguenod…RjLWFmMzEtNTJmNTgyM2NlMmUzN2I0Y2U1ZmItNjNmNy00Y2IzLTg3MDMtYjViYzQyOWE5MGVm', which is disallowed for cross-origin requests that require preflight

**Comment by brockallen** [comment]
Sounds like your Ajax calls are hitting something in your app that redirects to IdSvr. For Web APIs, you need to return 401 when authorization is required.

**Comment by vinayhfs** [comment]
I am trying to call web api as you have explained in example - https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html. I am getting token as you have explained at last part of above example using  
var user = User as ClaimsPrincipal;
var token = user.FindFirst("access_token").Value;
Only difference is this token I am passing to my javascript code make web api call.

What happens if initial few request may work fine but after some time (or for different user ) request fails. It uses same token I can see this in fiddler.

I have set IdentityTokenLifetime = 360,  AccessTokenLifetime = 7200, in configuration Adding fiddler request response details blow.

Request - GET https://xxx.abc.com/api/SelectLogin/f3b36f89-1ef3-4fc4-8fcd-1d215d629339?_=1444623821254 HTTP/1.1
Host: temptest.delogue.com
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
Origin: https://efg.abc.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJjbGllbnRfaWQiOiJkZWxvZ3Vlbm9kZSIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJyb2xlcyIsInVzZXJBcGkiXSwic3ViIjoiZjNiMzZmODktMWVmMy00ZmM0LThmY2QtMWQyMTVkNjI5MzM5IiwiYW1yIjoicGFzc3dvcmQiLCJhdXRoX3RpbWUiOjE0NDQ2MjM3NTksImlkcCI6Imlkc3J2IiwiaXNzIjoiaHR0cHM6Ly9zc290ZXN0LmRlbG9ndWUuY29tL2lkZW50aXR5IiwiYXVkIjoiaHR0cHM6Ly9zc290ZXN0LmRlbG9ndWUuY29tL2lkZW50aXR5L3Jlc291cmNlcyIsImV4cCI6MTQ0NDYzMDk1OSwibmJmIjoxNDQ0NjIzNzU5fQ.UZIh0xtnQsD0qK469eD4bet4qnyqrfLkjnjJGnboVFAaAuJzw7e3GfzSuM9hiRGnzHIOERIbIAMKszq9af93zMYr2xtME7yHLWPbnYdQPLjgNQCEcgNSM7qC3gJWGzqeigS-i5L9Ks6NjkWf_Qa6HXpSLCoj_55Dduvl7wj_FaH3toaypNVdRKoXGYXBTFHE1lDYJnj5jM1EZtfMWrE2Ena-fa0pFtWbctCN_Ur9gEwxVLRXu-yFG9NsG4ZXlywJl3tSmr84124efq5PsZuy7TCt1eqxUGinVCnyaw9aaXoRqBlSN0QE6sKdtUEPO-G_GjsWOIdPjZAdbHWLk3afWw
Content-Type: application/json; charset=utf-8
Referer: https://efg.abc.com/Home/Portal
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

Response-

HTTP/1.1 302 Found
Content-Length: 61
Content-Type: application/json; charset=utf-8
Location: https://ssotest.abc.com/identity/connect/authorize?client_id=deloguenode&redirect_uri=https%3a%2f%2fxxx.abc.com%2f&response_mode=form_post&response_type=id_token+token&scope=openid+profile+roles+userApi&state=OpenIdConnect.AuthenticationProperties%3dYZep_c7pBHMzkCVCe465ZQNP4uT6F6k-OSfjSYOtd2EN8JY17Q45G-QJOzEcJaRMPkCh0IwJjGzxNBu_V4uC_F9iRmK7GgjooqcEIrrJ6P-K9hPTxAP7CjlfbF1KyeIVSff9UpJymu9HMnj3J1_ZanptPqLnwJmndv4SPI6vp0UDPK1H3z_ixjee2Www9j_QkgyWLC5-R2LR-xg4AFlFjKCOgZsouoYu3xx1UpIj83xyfVCSg5jNlSJVcqAhkBHBk1eOP-2qzN4_kGsPqRm1p2tOBmISrQqpSQ0fZePqznTBcCrBNO1aMD01be9Zz5B2&nonce=635802206216662980.YjYxZWE4NGUtY2E5My00ZmMxLWI0ZmItZTBjN2Y5NmYzYTg2ZTIwNTVmZTMtOTcwOC00MjQ5LTk0YTgtYTIzYzk2MWE0MzQ5
Server: Microsoft-IIS/7.5
Access-Control-Allow-Origin: *
Set-Cookie: OpenIdConnect.nonce.qaaOqGJ35GXdQusgWQpMCbx5Z42GwJPcTMMxQrgTOwA%3D=dkYxZ1JrbDB0SnlYR3Z5bDV1Yzh4dUd6RXBXOVdKZDB6d1BJejF6Z2thdkhCS0hQUnVIUktJaklKWGRBX2Z1czVUS3JuMjk4Q0M2a2w5Mks4NWZlMkxNelp3QmZvVUFxS09veGlReTUtRmdoM0drZ3ZQOHlnblI1NFllX2d4dFJqdTlUWTlZRHdMYWs4OXp5a3N0SUs0REpGeU5zTVZ4SXhIekJkSFZCb0NsOVlWbEM2V05ieGRzQmlYQmJFOHR5T0dJQkQ5YzhyanE4QzY1VlktbXk1d1dNSDQ3SERfUlZVSldMeFpkaEQ5Yw%3D%3D; path=/; secure; HttpOnly
X-Powered-By: ASP.NET
Date: Mon, 12 Oct 2015 04:23:40 GMT

{"Message":"Authorization has been denied for this request."}

**Comment by brockallen** [comment]
As I said, it sounds like you're using the wrong technology (cookies) in your Web API. Decouple the Web API from your MVC code so the Web API is not being affected by the cookie and OIDC middleware.
