### ISSUE TITLE
Custom Event Service

### ISSUE THREAD

**Issue by eaba** [IdentityServer/IdentityServer3#2013]
Please i need a guide on how to implement a custom event service.

I am lost. 
Thanks in advance!

**Comment by brockallen** [comment]
What are you looking to do?

**Comment by eaba** [comment]
In my app, the username will be their email address.
So in the event service i want to capture events in the Authentication category, then check the EventType to send the user email on success or failure.

I followed the DefaultEventService implementation: I got CircularReference exception. Then I added ReferenceLoopHandling.Serialize, now the browser throw "Secured connection failed".

how can i achieve this?

**Comment by brockallen** [comment]
> Then I added ReferenceLoopHandling.Serialize
Are you using IdentityServer as a NuGet or directly using the source? We don't support changing the source directly.

**Comment by eaba** [comment]
NuGet

**Comment by eaba** [comment]
Implemented IEventService following the DefaultEventService.....but did not work!

How can i achieve my aim?

**Comment by brockallen** [comment]
I guess it's unclear what's not working.

**Comment by eaba** [comment]
Okay.....Please kindly show me how i would be able to alert users on successful logins and login failures. or if you also show me how to make and properly register my custom event service, i would greatly appreciate.

Thanks!

**Comment by pawepaw** [comment]
Follow sample with custom user service. Event service can be registered in the same way https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService
