### ISSUE TITLE
Embedding custom claims in Access Token through simple IUserService

### ISSUE THREAD

**Issue by TD49** [IdentityServer/IdentityServer3#2016]
Very simple refresher question from way back on embedding custom claims into an Access Token through the UserService only (and without a custom ```IClaimsProvider``` instance this time).   Let's say we're adding a custom claim within our own implementation of ```IUserService``` (using a simplistic example):

```C#
public async Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
    context.AuthenticateResult = new AuthenticateResult("MyUsernName", "MyName",
        new List<Claim> {new Claim("MyCustomClaim", "12345")});
}
```

The above claim is assigned to a specific resource scope called "TestScope" and, per the docs, ```IncludeAllClaimsForUser``` is set to true.

```C#
new Scope 
{
    Name = "TestScope",
    DisplayName = "TestScope",
    Type = ScopeType.Resource,
    IncludeAllClaimsForUser = true,
    Emphasize = false,
    Claims = new List<ScopeClaim>
    {
          new ScopeClaim("MyCustomClaim")  
    }
};
```
When a request is made to the Token endpoint, the claim "MyCustomClaim" is still not embedded in responding JWT Access Token, regardless of the ```IncludeAllClaimsForUser``` setting.   Verified that "TestScope" was requested and was successfully embedded in the token's scope array.

NOTE:  using the stock ```DefaultClaimsProvider``` for this scenario.  Something simple we're missing here?

**Comment by TD49** [comment]
Ok, I should clarify the ```IncludeAllClaimsForUser``` comment in that I understand what it does.  

We don't need a call to ```GetProfileAsync```in this simple scenario, as the value is already available in the ```IUserService``` implementation.  Question is about embedding that original claim ```{ "MyCustomClaim", "12345" } ``` into the Access Token.

**Comment by leastprivilege** [comment]
You need to implement the GetProfileDataAsync method - this is being called by the claims provider.

Debug there to find out whats going on.

**Comment by TD49** [comment]
Seems we implemented ```GetProfileDataAsync``` for ```UserInfo``` consumption just fine, but didn't account properly for the workflow through a ```Token``` endpoint consumption.   Easy enough to handle.
