### ISSUE TITLE
Best Flow for Javascript (web) Applications

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer3#2017]
What is the best flow for a javascript application that needs to be able to authenticate and authorize users both through database stored usernames and passwords and social logins?

**Comment by leastprivilege** [comment]
This has been asked one thousand times before - but the answer is still: implicit.

**Comment by behrooz66** [comment]
Thanks, is there by any chance a sample or tutorial on this?

**Comment by leastprivilege** [comment]
of course ;) check the clients solution in the samples repo..
