### ISSUE TITLE
Partial Login with Paid Subscription model

### ISSUE THREAD

**Issue by narciero** [IdentityServer/IdentityServer3#2018]
I'm building an application that requires a paid subscription (monthly or year based subscriptions). Based on other issues i've read, it seems like partial login is what i need for new users who are signing up without a subscription, so that they go through the process of paying, accepting EULA. 

The issue i'm having is if someone who already has an account and a valid subscription logs in like 5 min before their subscription expires and they're issued an access token which has a predetermined lifetime of 6 hours. Then they're able to access the app after their subscription requires unless i perform a subscription valid check on every request. My question is should I be putting something like a paid subscription as part of partial login or is there a better method thats normally used (maybe just delegating validation of the subscription to the application itself).

I also only want the paid subscription to be required for a specific scope (the app API scope), so a user account can be created & logged in to without requiring a subscription but they wont be able to access any of the actual app's features. Thanks!

**Comment by leastprivilege** [comment]
So - technically speaking - you are saying it would be good for you to know the requested scope at login time (like in the AuthenticateLocal) method? This way you could check that the subscription lasts long enough before you issue the next 6h token.

Another option could be to switch to reference tokens, this way you could check the user's subscription periodically while validating the token (and cancel the token as well).

**Comment by narciero** [comment]
Yes, i thought about using AuthenticateLocal but then what if the person has 3 hrs left in the subscription what do I do, I'd either cut their subscription short by 3hrs (assuming 6h token) or give them extra 3 hrs. 

I think reference tokens would be best bet, that way i can validate subscription on each request. A little more overhead than id like (as i have to make call to database to check subscription) but seems like the only way to enforce using ref tokens. Would adding a subscription_expiration claim be a possibility? and just check for that claim on each request instead? It would be nice to return a custom http response indicating subscription is expired that way I can redirect to a payment page.

**Comment by leastprivilege** [comment]
you don't need to validate on each request - our middleware has caching built in - every 10 mins would be probably sufficient.

with an expiration claim you can also check directly at the resource endpoint - you could create your own middleware that encapsulates this requirement - that's what I would probably do.

**Comment by narciero** [comment]
Ok i will probably go the claim route then and add middleware to the API. I like that because it still allows a user to "login" they just cant use the protected resource, i think it makes sense to delegate that check to the resource anyways. Thanks for the help!

**Comment by narciero** [comment]
Just a followup, I created a Subscription validation middleware to check for an expiration date claim (which is a ScopeClaim part of the API Resource scope)  and I'm following a similar pattern to the ScopeRequirementMiddleware. The problem im having is that the context.Authentication.User identity doesn't contain any info/claims, its always empty..I'm registering the middleware right after I have the app.UseIdentityServerBearerTokenAuthentication  registration, which is where the ScopeRequirementMiddleware is also registered. How do I get access to the current user principal like you do in ScopeRequirementMiddleware in order to perform a claims check? I know this is more of an OWIN question but your Scope middleware is basically what im trying to replicated so any help would be great, thanks!

Here's some of the code from my Invoke method:

 var principal = context.Authentication.User;
            if (principal == null || principal.Identity == null || !principal.Identity.IsAuthenticated)
            {
                return _next(env);
            }

            // Check for non-expired subscription
            var userIdentity = context.Authentication.User.Identity as ClaimsIdentity;
            var validSubscription = this.HasValidSubscription(userIdentity);

**Comment by leastprivilege** [comment]
well - this is supposed to work (just like the scope middleware). Don't know what's wrong.
