### ISSUE TITLE
Query String and Hash when redirecting to Identity Server

### ISSUE THREAD

**Issue by KMC13** [IdentityServer/IdentityServer3#2020]
Hi,

I am not sure if this is an issue or not but hoping for some pointers. I have a basic setup Angular SPA with WebAPI backend. 

So, when a user comes to the sight I am redirecting them to the id server as per the OidcTokenManager. 

My problem is that I have some query string and hash params which are optional i.e. 

http://mysite.com?qs=1#/search/EP

When I redirect to the id server I lose these params.

I have added them to the redirect URI I pass to the OidcTokenManager but as they don't match the client RedirectUri's in the Identity Server I get an invalid client error.

Should the IdentityServer be sensitive to the QueryString and Hash in redirect uri's? Or is there an option to just match the protocol and host?

The other option I thought of was to pop them in local storage on the client before the redirect to identity server. Or put in some dynamic RedirectUri validation of my own to ignore the query string and hash in validation as per #535.

Thanks in advance.

**Comment by loctanvo** [comment]
Fragments (the part behind `#`) will not be sent to the server by the browser. You can [read more about it here](https://blog.httpwatch.com/2011/03/01/6-things-you-should-know-about-fragment-urls/). May [this issue](https://github.com/IdentityServer/IdentityServer3/issues/1281) be helpful?

**Comment by KMC13** [comment]
Thanks for the response. Not precisely but as the hash is only client side I can store that in a cookie and reinstate it when the redirect for token has completed. But that still leaves me the query string that I can't append to the URL without a refresh of the browser forcing redirect to get token again. I also have a number of sub paths which I would have to add into the allowed redirect Uri's.

I have solved this now using a custom RedirectUriValidator by just validating the request uri starts with one of the allowed redirect uri's. I could make it more specific to validate my expected params, site subpaths and hash values but I am not sure if that would give me anything. Code below.

```c#
public class BaseUriRedirectUriValidator : IRedirectUriValidator
{
    public System.Threading.Tasks.Task<bool> IsPostLogoutRedirectUriValidAsync(string requestedUri, IdentityServer3.Core.Models.Client client)
    {
        var result = client.PostLogoutRedirectUris.Contains(requestedUri);

        return Task.FromResult(result);
    }

    public System.Threading.Tasks.Task<bool> IsRedirectUriValidAsync(string requestedUri, IdentityServer3.Core.Models.Client client)
    {
        var result = false;
        foreach(var redirectUri in client.RedirectUris)
        {
            if(requestedUri.StartsWith(redirectUri, StringComparison.InvariantCultureIgnoreCase))
            {
                result = true;
                break;
            }
        }

        return Task.FromResult(result);
    }
}
```

This seems secure to me. Does anyone think otherwise?

**Comment by leastprivilege** [comment]
exact URI matches are recommended by the specs and threat models. This might look secure - but have been warned ;)

**Comment by MNF** [comment]
More details how to store QueryString to restore it after redirect see [RedirectUris with callback params does not work. #1371](https://github.com/IdentityServer/IdentityServer3/issues/1371)
