### ISSUE TITLE
Dynamic Client Registration Support for OpenID Connect

### ISSUE THREAD

**Issue by iiAuth** [IdentityServer/IdentityServer3#2021]
Is there planned support for Dynamic Client Registration for OpenID Connect for Identity Server 3 or Microsoft OWIN OAuth/OpenID Connect middleware implementation?

Is there possibility to extend Identity Server 3 to support this?

**Comment by leastprivilege** [comment]
We don't have plans to implement client registration in our core project. The design of core is that it has read-only access to the configuration store (also for minimizing attack surface).

We discussed this before and decided that this would be better implemented in a management library. This does not exist yet and we don't have the resources right now. If you want to start a contrib project - let us know.

**Comment by iiAuth** [comment]
Yes, I would like to do that.

**Comment by leastprivilege** [comment]
that would mean to re-start this repo https://github.com/IdentityServer/IdentityServer3.Admin

open an issue there please that you want to do this. thanks!

**Comment by iiAuth** [comment]
Hi Dominick,

I am very happy that I can be part of this. I also need this functionality for one project. 

Why can not we put Dynamic Client Registration as an extension to Identity Server 3? Anyway its part of both OAuth and OpenID Connect. Speaking about attack surface, it seams to me that it does not mater much where it is, if this endpoint is enabled the attack surface is the same.  It can be part of Identity Server 3, and turned of by default.

Its just small proposal. What do you think Dominick?

**Comment by leastprivilege** [comment]
We don't have plans to add client registration into core right now.

**Comment by brockallen** [comment]
Are you planning on implementing this inside of IdentityServer, or as a separate application?
