### ISSUE TITLE
OpenId JWT Authentication via JwtBearerTokenAuth Middleware

### ISSUE THREAD

**Issue by federicobarera** [IdentityServer/IdentityServer3#2023]
Hi,

having a javascript client which authenticates via openid connect (against identity server or AzureAD) using the implicit flow and receives the JWT via url fragment.
Then this token is attached in the http header while connecting the resource's api. 

Is there any OWIN middleware which supports this flow out of the box?
The OpenIdConnectMiddleware seems supporting just the POST response mode (with code / id_token) but not Http Headers.

The only way I found so far (and I don't know if correct), is to use the JwtBearerToken middleware with a custom IssuerSecurityTokenProvider.

Is this considered an acceptable flow?
Is there any other better way to do it?

```C#
	app.UseJwtBearerAuthentication(
		new JwtBearerAuthenticationOptions
		{
			AuthenticationMode = AuthenticationMode.Active,
			AllowedAudiences = new[] { audience },
			IssuerSecurityTokenProviders = new IIssuerSecurityTokenProvider[]
			{
				new OpenIdSecurityTokenProvider(stsDiscoveryEndpoint)
			},
	});
    public class OpenIdSecurityTokenProvider : IIssuerSecurityTokenProvider
    {
        public OpenIdSecurityTokenProvider(string stsDiscoveryEndpoint)
        {
            ConfigurationManager<OpenIdConnectConfiguration> configManager = new ConfigurationManager<OpenIdConnectConfiguration>(stsDiscoveryEndpoint);
            OpenIdConnectConfiguration config = configManager.GetConfigurationAsync().Result;

            _issuer = config.Issuer;
            _securityTokens = config.SigningTokens.ToList();
            
        }

        private string _issuer;
        public string Issuer
        {
            get { return _issuer; }
        }

        private IEnumerable<System.IdentityModel.Tokens.SecurityToken> _securityTokens;
        public IEnumerable<System.IdentityModel.Tokens.SecurityToken> SecurityTokens
        {
            get { return _securityTokens; }
        }
    }
```

Thanks,

Federico

**Comment by federicobarera** [comment]
Actually, I've just noticed that your IdentityServerBearerTokenAuthentication Middleware is validating Reference and JWT **access** tokens, generated by IdentityServer. You are not authenticating if posting an id_token.

AzureAD authentication middleware is authenticating the id_token. Infact is the only token retrievable via implicit grant. No scopes are coming within the claims tho.

**Comment by leastprivilege** [comment]
Yes - because thats how it works - access tokens are for APIs. Our middleware just wraps the the standard Katana JWT middleware and adds a couple of features.

**Comment by federicobarera** [comment]
So is it incorrect /bad practice that Microsoft UseWindowsAzureActiveDirectoryBearerAuthentication is authenticating the id_token?

**Comment by leastprivilege** [comment]
This middleware is also just a wrapper around the standard JWT middleware - it has the same purpose - namely validate an access token.

**Comment by federicobarera** [comment]
Thanks for the explanation. Microsoft AzureAD documentation confused me as they are using an IDToken as Access Token using the implicit grant:
(https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-scenarios/)

> Single Page Application (SPA)
[...]. In this scenario, when the user signs in, the JavaScript front end uses Active Directory Authentication Library for JavaScript (ADAL.JS) preview and the OAuth 2.0 Implicit Grant protocol to obtain an ID token (id_token) from Azure AD. The token is cached and the client attaches it to the request as the bearer token when making calls to its web API back end, which is secured using the OWIN middleware.
