### ISSUE TITLE
How do we verify if the user has Active Session?

### ISSUE THREAD

**Issue by Bala2Excel** [IdentityServer/IdentityServer3#2024]
Hi,

here is my scenario, 
 I have a JS app which uses makes a Implicit request to the IDSrv .
 IDSrv redirects back to my JS app and the redirection URL gets registered in the Browser History
 Now, the user logs out and Session cookie disappears. 
From the browser history, the user is able to click on the URL which has the token as QueryString, 
The JS application validates the token from the URL and since the token lifetime haunt expired, it has allowed the user to gain access to the application without making the user to login again.

I am trying to add additional checks to verify whether the user is logged into IDSrv however, I couldn't find any endpoints which would help me to determine that!

Am I doing something wrong? or please help me with the right direction!

**Comment by brockallen** [comment]
Are you not using the `state` param from the OIDC spec?

**Comment by Bala2Excel** [comment]
Thanks for pointing me in right direction.

Balamurugan On Tue, Oct 13, 2015 at 8:40 PM, Brock Allen < notifications@github.com [notifications@github.com] > wrote:
Are you not using the state param from the OIDC spec?

—
Reply to this email directly or view it on GitHub
[https://github.com/IdentityServer/IdentityServer3/issues/2024#issuecomment-147744666] .[https://github.com/notifications/beacon/AFmZdWTrg_QQKc_yap-k_attLeCCLJTEks5o7RZzgaJpZM4GNyV4.gif]
