### ISSUE TITLE
Custom options on login method

### ISSUE THREAD

**Issue by Vagele** [IdentityServer/IdentityServer3#2025]
I have a database with different user stores which connects a user with a specific domain. So when a user tries to login (AuthenticateLocalAsync) I have to see from which domain (uri) the call is coming in order to seek in the specific user store to see if is valid. Is there a way to have an option like that in the method AuthenticateLocalAsync? And also is there a way to have deifferent return urls depending on the calling domain?

Thanks in advance.

**Comment by leastprivilege** [comment]
You have read-only access to the clientId and returnUrl - or the client could pass an additional hint via the acr_values parameter.

**Comment by Vagele** [comment]
No I don't have read-only access. I want when the user tries to call login from e.g. subdomain.domain.com to check the subdomain part and try to find the user with a different user store (everytime will the user store will be specified from the subdomain part). And also after a successful login to redirect him to the subdomain.domain,com. I don't know which properties I have to access in order to claim these data.

**Comment by leastprivilege** [comment]
The values I described are in the SignInMessage passed into AuthenticateLocal

**Comment by Vagele** [comment]
Can I set them individually on every call?

**Comment by leastprivilege** [comment]
As I said - it is read-only for you - but based on that info you can select the right data store.

**Comment by Vagele** [comment]
There will be several subdomain.domain.com uris that will be calling the AuthenticateLocalAsync.

**Comment by leastprivilege** [comment]
right - so every subdomain could e.g. send the "subdomain" value as an acr_value - you can then parse that in the user service and take appropriate action. Maybe just give it a try...

**Comment by Vagele** [comment]
Is there any example of setting the acr_values and how to consume them?

**Comment by leastprivilege** [comment]
check the endpoint docs - they show up on SignInRequestMessage.
