### ISSUE TITLE
Are scopes mandatory for authorization code grant ?

### ISSUE THREAD

**Issue by vish-k** [IdentityServer/IdentityServer3#2026]
OAuth2 specs mention scope is optional for authorization code requests. However, IdentityServer3 gives an error "scope is missing" if I do not provide any scope with auth code request. 
I looked at ICustomRequestValidator but the scopes are validated much before ValidateAuthorizeRequestAsync/ValidateTokenRequestAsync menthod is called.
Am I missing something in IdentityServer3/client configuration ?

**Comment by leastprivilege** [comment]
scopes as mandatory - how else would you specify for which resource you need a token?

**Comment by vish-k** [comment]
Specs say scope is optional (https://tools.ietf.org/html/rfc6749#section-4.1.1 ). Auth server may use default scope if not provided by client.
Anyway, is there a way to plug-in some code (before AuthorizeRequestValidator.ValidateAsync) to add default claim if it's not provided by client so that client does not get "error=invalid_request" ?

**Comment by leastprivilege** [comment]
no - the scope is mandatory.

**Comment by vish-k** [comment]
Thanks! I assume you mean scope is mandatory for IdentityServer3.

**Comment by leastprivilege** [comment]
yes,

**Comment by vish-k** [comment]
Thanks again. Appreciate your help.
