### ISSUE TITLE
Identity Server 3 implicit grant, role based authorization

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer3#2027]
I have posted this in StackOverFlow at this address: http://stackoverflow.com/questions/33131484/identity-server-3-implicit-grant-role-based-authorization
but just copy here as well. 

I have set up the Identity Server 3 with Membership reboot database as my authorization server and have also developed a Web Api project which will be accessed by a javascript web app.

Using the implicit flow, the client is able to log in and obtain id_token and access_token. Now I have a few questions, which I would appreciate some detailed answers too:

1. What is the functionality of id_token? After obtaining it, what can I do with it?

2. The roles of the users are stored in the database as claims (like for example, the key value of "role","admin"). How do I perform the role-based authorization at this point? It seems like the id_token contains those claims but the access_token does not. When sending my access_token as Bearer along my Api request, how does the api know which roles the sending user has?

3. In a web api controller, I want to access the user's information using:

var user = User as ClaimsPrincipal;

using this code, I cannot get pretty much anything about the user; username, id, etc. Also when I use user.Claims in the controller, I have no access to the claims stored in the database. How are there two sets of claims, one in the database one in the token?!

Any extra information is greatly appreciated.

**Comment by leastprivilege** [comment]
Sorry - but you need to read the docs, do the walkthroughs and check the samples. This is really basic stuff.

**Comment by behrooz66** [comment]
I know these are basics, and please rest assured I have read the docs, looked through samples and did some walk-through. I still don't see anything wrong with asking a "basic stuff" question.

I think there would be more points into having a forum if the answer to half of the questions was a bit more than just "check the samples". From what I have been reading on internet, I am not the only one who is having trouble understanding a lot of IS stuff out of the documents.

Maybe instead of "check the docs" you can at least provide a link to the right part of the "docs" you think I am missing. Thanks!

**Comment by leastprivilege** [comment]
1. read the OpenID Connect specification (http://openid.net/specs/openid-connect-core-1_0.html)
2. read about scopes & claims (https://identityserver.github.io/Documentation/docsv2/configuration/scopesAndClaims.html)
3. see 2
