### ISSUE TITLE
Is it possible to programmatically create a sign-in request directly to a specified external login?

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3#2028]
**Today:**
I have an MVC website set up using OpenIdConnectAuthentication (just like the **OWN Hybrid Client Sample**)

This means when a page is hit that requires auth, it "automagically" redirects to the sign in page like so:
https://localhost:1234/service/login?signin=abc123

The user then chooses whether to use external or local login, as expected.

**Desired:**
I would like to **programmatically make the request to sign in** and generate a link, rather than hit a page that requires auth and "automagically" redirect.

I notice that after the above scenario, if I then click "Facebook", I am sent to this URL:
https://localhost:1234/service/**external?provider=Facebook&signin=abc123**

What I would like to do is, from my website, offer the Facebook sign-in link that, when clicked, programmatically initiate the id server request and SKIP the default login page (.../login?signin=abc123) and go STRAIGHT to the facebook signin request (.../external?provider=Facebook&signin=abc123).  I would then expect all else to be the same (successful consent creates the ID server account, redirects back to app)

In order to do this, it looks like **I simply need to request/generate the token found on the signin param** (signin=abc123).  Anyone know how to do that?

**Comment by leastprivilege** [comment]
You can use AuthorizeRequest from here
https://github.com/IdentityModel/IdentityModel

**Comment by narciero** [comment]
you can also use the custom idsrv owin environment extension, CreateSignInRequest(). So something like (in your controller):  this.Request.GetOwinContext().Environment.CreateSignInRequest() will create a url to your login page and you could extract out the signin param and use that value for external login.

**Comment by dapug** [comment]
ok, I see where you are going with these suggestions.  WRT CreateSignInRequest, I don't see that extension in IdentityModel and I wasn't expecting to have a reference to IdentityServer in the client app... ??

**Comment by dapug** [comment]
Also I'm not quite sure where or what the signin= string value is, or how AuthorizeRequest.Create() would generate such.

**Comment by narciero** [comment]
CreateSignInRequest is in IdentityServer3.Core.Extensions but you're right that shouldn't be in client app, it wont work. Maybe the sample JavaScriptImplicitClient-Simple is what you're looking for? It generates an auth url using clientId, redirectUri, etc which will bring the user to login page and redirect them back to the page of your choosing. That wont bring them straight to Facebook login but it will get them to login page without protected resource redirection.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MvcCodeFlowClientManual/Controllers/HomeController.cs#L28

**Comment by dapug** [comment]
Dom, thank you.  I see my prob.  My MVC client is configured to use Hybrid flow and currently does not do manual anything.  I see now that the initial request redirects to my id svr https://localhost:1234/service/login?signin=**abc123** and I can simply retrieve the code and reconstruct a new call to:  https://localhost:1234/service/external?provider=Facebook&signin=**abc123**

I get it now, cool!

BUT...

Is this not possible using Hybrid flow?  I didn't really want to set up the manual validation in this project.  I was hoping to generate that "signin=" param but when the work is complete and it returns to the MVC client after auth, using the EXISTING config (set up as hybrid client ID).  

I imagine mixing flows is obviously not going to fly.  So I tried using CreateSignInRequest() with clientID = "katanaclient" and it rejected it, probably because that is set up for hybrid flow. Not possible to manually initiate a hybrid flow and get this redirected signin param?

**Comment by leastprivilege** [comment]
why would you want to trigger facebook manually? that's what acr_values are for.

You always go to the authorize endpoint - nowhere else.

**Comment by dapug** [comment]
Because I have created my own "Sign Up" page wherein the user can enter fields for sign up and we handle local account creation, OR, click on a **social** link to sign in which also creates the IDSvr record if not already a user.  It doesn't make sense for them to do this in 2 steps from the sign up page ->  1) click "use social", then see IDSvr sign in page that again asks which social, 2) click FB and THEN they finally get there (yes, my UX team is hypersensitive, rightfully so).

**Comment by dapug** [comment]
Hope that made sense.  **Sign Up** is the # 1 most critical thing to not screw up in a consumer facing site.  I cannot send my users to IDSvr Sign-In page for a Sign Up process.  But we do use the IDSvr Sign-in page for...well, sign in.  :)  

The line is blurred a bit with 3rd party external because it is a "sign in" if already a user but ALSO a "sign up" if not already an app user.

**Comment by leastprivilege** [comment]
your question is: "Is it possible to programmatically create a sign-in request directly to a specified external login?"

answer yes - using acr_values

that's documented on the authZ endpoint docs

**Comment by dapug** [comment]
ok, I brushed up on acr_values, though I could not find any docs that really explain it (i literally had to tinker and look through source to figure it out).  Got it working in the MVC client as mentioned above.  Then I just make a custom call where needed, and when authentication is done, it just returns and resumes as normal using the config in Startup.

I use this to generate the URL, apply to whatever link or button I want to direct straight to FB signup, and that is all that is needed.

    var state = Guid.NewGuid().ToString("N");
    var nonce = Guid.NewGuid().ToString("N");   
   
    var request = new AuthorizeRequest(Constants.AuthorizeEndpoint);
    var startUrl = request.CreateAuthorizeUrl(
                clientId: "katanaclient",
                responseType: "code id_token token",
                scope: "openid email profile read write offline_access",
                redirectUri: "http://localhost:2672/",
                state: state,
                acrValues: "idp:Facebook",
                nonce: nonce);

Note: after sign-in, the request will NOT trigger **AuthorizationCodeReceived** and set everything you need to sign the user in, unless the **callback** is to a page that **requires auth**.  Otherwise, allowing anonymous doesn't get picked up by the middleware and you'll have to validate the token yourself. This threw me for a bit while testing.

Thanks everyone for the tips and ideas.

**Comment by kwarnke** [comment]
I have the same concerns (wanting to offer external logins from a registration page) but my client is an AngularJS SPA.  Any ideas on how to translate the solution above to the OidcTokenManager client implementation?  Is there some additional config values we can pass that will automatically kick over to the FB login?

**Comment by johnsonps08** [comment]
I'm using a similar workflow but ending up with the following error:

> Exception: Unable to unprotect the message.State.

My code looks like this:
```
var disco = await DiscoveryClient.GetAsync("http://localhost:5000");
var request = new AuthorizeRequest(disco.AuthorizeEndpoint);

var authURL = request.CreateAuthorizeUrl(
     clientId: "TestClient",
     responseType: "id_token token",
     scope: "openid profile MyAPI",
     redirectUri: "http://localhost:5002/signin-oidc",
     state: Guid.NewGuid().ToString("N"),
     nonce: Guid.NewGuid().ToString("N"),
     responseMode: "form_post"
);

return Redirect(authURL);
```

Any suggestions as to what I'm missing?
