### ISSUE TITLE
Question: How should I correctly use Reference Tokens?

### ISSUE THREAD

**Issue by RobKraft** [IdentityServer/IdentityServer3#2029]
I am trying to select the correct architecture in IdentityServer.  We are developing an Angular App that talks to the REST back end we develop.  I don't think we can pass claims (obtained from Identity Server) from the Angular App to our REST API because we have hundreds of different claims.  So I thought we would pass a "Reference Token".
If we pass a "Reference Token" from the Angular App to our REST API, should our REST API use information in the "Reference Token" to call the  IdentityServer to identify/validate the user, or should our REST API use the information in the "Reference Token" to query our database that has all user information and security details configured?

**Comment by leastprivilege** [comment]
"hundreds of different claims" doesn't sound like claims at all to me. More like application data.

Claims describe the identity of a user - you typically don't need more than 5 to (max) 10 claims. IdentityServer is authentication as a service - not application data as a service (these are called databases)

**Comment by RobKraft** [comment]
Thanks for a prompt reply.  I thought the "roles" a user was part of would qualify as claims, and I should have clarified that.  Any user may be in hundreds of different roles granting them permissions to thousands of different permissions.  Should all of these roles be part of an "Access" token?  Our application currently uses a "LogonID" and will continue to do so; if the LogonID is one of the claims, and we pass that claim from the browser app to the REST API, should the REST API use an some part of the token to look up the user from the database, or from the IDSvr, to verify that the token and LogonID match?

**Comment by brockallen** [comment]
If you're worried about token size: To make the id token smaller, you can get an access token to access the user profile endpoint to get the identity data. For the access token, you can use reference tokens which requires the API to de-reference it against IdSvr. This might be what you're looking for.

**Comment by leastprivilege** [comment]
it is generally bad style to have that many claims - also keep in mind that once these claims are in a token they cannot be changed anymore - only when the client gets a new token.

I would put minimal claims into the token and let the API load the roles that's its interested in on the server. That's called claims transformation and is common practice.
