### ISSUE TITLE
Allow unlimitted length for acr_values or make it configurable

### ISSUE THREAD

**Issue by mirecg** [IdentityServer/IdentityServer3#2030]
Hi, 

Currently the acr_values is limitted to 300 characters. Is it possible to get it unlimitted or configurable? Is there any technical limitation which doesn't allow it to be unlimitted?

I would like to use acr_values to pass the X509Certificate2 object (serialized to base64) to a UserService.
I've discussed about it in [How to use X509Certificate for ResourceOwner Flow in Two-factor authentication with username/password](https://github.com/IdentityServer/IdentityServer3/issues/2007).
The similar approach was also discussed in [User authentication by certificate on authorize endpoint](https://github.com/IdentityServer/IdentityServer3/issues/1553), but there is a case where the client certificate is being passed through TLS/SSL, which doesn't force to pass it also in acr_values.

**Comment by brockallen** [comment]
What's your intent with passing the cert? See the comment here: https://github.com/IdentityServer/IdentityServer3/issues/1553#issuecomment-117456616

**Comment by mirecg** [comment]
My intent is to support WCF security scenario where the client certificate comes from message layer (WS-Security with signature) and not from transport layer (TLS/SSL).

**Comment by brockallen** [comment]
Well, I think there's more to it than just passing the base64 representation of the cert.

**Comment by mirecg** [comment]
Hi, I'm was just kindly asking for help. I would welcome if you could come with constructive discussion.

Well, I need to solve the following case. I have public SOAP web service (using WCF) which is secured at message level using WS-Security standard. I will describe it very shortly. The soap body is signed with client certificate, which corresponds to a user in our system. The SOAP message is secured also at transport level using SSL/TLS. Currently the user is authenticated using local authentication mechanism using the client certificate against users DB. The certificate comes as BinaryToken within the soap message. Certificate goes through several layers. At WCF core, the signature of the soap body is verified, at WCF custom extension point it is validated and finally the user is identified.
I want to replace current local authentication solution with the IdentityServer as central solution for authentication. 
What would you suggest how to validate and identify user using X509 credentials?
I don't see any security concerns with "just" passing base64 representation of the certificate, which was already verified outside the IdentityServer? What about you?

Thank you

**Comment by brockallen** [comment]
Yea, sorry -- it was just more to alert to you the fact that you can't just pass the cert. Since this wasn't the main focus of the issue, I didn't elaborate.

As for the length constraint -- we have an issue (somewhere) to allow it to be configurable, so that will be possible soon-ish (I think in 2.1 is where it was slated -- I don't have the issue # offhand).

**Comment by brockallen** [comment]
Oh and so for the cert -- it needs to be used in a way to sign something to prove possession of the private key. TLS does this all for you. WCF also had a lot of that heavy lifting done internally via their libs. If you wanted to do that on your own with some parameters passed to IdSvr then you'd need to research the crypto behind those things.

**Comment by mirecg** [comment]
Hi, I'm glad that you have understood the intent of the certificate usage.

I haven't found any open issue which is about acr_values length constraint. The closest issue I've found was the [User authentication by certificate on authorize endpoint](https://github.com/IdentityServer/IdentityServer3/issues/1553).

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3/issues/1842

..and did you understand that simply transmitting a cert (aka the public key) is not secure?

or what do you mean with "already verified outside the IdentityServer" ?

**Comment by mirecg** [comment]
OK, but the #1842 is about MaxInputLength, which is unrelated to MaxAcrValuesLength.

I do understand the concerns about simply transmitting just the certificate,but my intent is to use it in a secure and trusted manner.

By "already verified outside the IdentityServer" I've ment that certificate comes from trusted context, on the service side, which has verified signature with that certificate, and the last thing it needs is to obtain identity based on that certificate from IdentityServer.

**Comment by leastprivilege** [comment]
Well - this issue is related (input length checking).

**Comment by mirecg** [comment]
It doesn't mention MaxAcrValuesLength. If you will keep in mind to solve also the limit for acr_values (MaxAcrValuesLength), I will be satisfied. 
But as I understand MaxInputParamLength is used in AuthenticationController for limiting the input length of the entered credentials (username/password) on the login screen, which is not related to acr_values. MaxAcrValuesLength is used to limit acr_values sent to authorization and token endpoints.

**Comment by leastprivilege** [comment]
easy - add a comment to the issue ;)
