### ISSUE TITLE
Validation Errors could be Warnings

### ISSUE THREAD

**Issue by njlittle** [IdentityServer/IdentityServer3#2031]
It's currently difficult to identity when IdentityServer is producing service errors instead of token validation or authentication errors.

Would it be possible to have some separation of these two kinds of errors?

**Comment by brockallen** [comment]
Do you mean in the logging or the actual HTTP response?

**Comment by njlittle** [comment]
Sorry, my description was rather short. Yes, I'm referring to the logs produced by `LibLog` which go through our supplied logging delegate.

**Comment by leastprivilege** [comment]
did you read the docs for logging? they are dev time and not meant from production logging (you will also find secrets in there which are not supposed to be logged).

**Comment by njlittle** [comment]
I'll admit that I had expected my priors to have done their homework with respect to the documentation. And yes, we had noticed the secrets. I'll do some reading and close this. Thanks for the assistance.

**Comment by njlittle** [comment]
Sorry guys, figured I should check with you if this is correct. It looks like HTTP request logging isn't subject to sensitive information scrubbing - this is totally understandable and I just wanted to check that's by design?

**Comment by leastprivilege** [comment]
yes that's by design.

**Comment by njlittle** [comment]
Many thanks!
