### ISSUE TITLE
You have not given permission to any applications, it is why?

### ISSUE THREAD

**Issue by zhangkefeng2010** [IdentityServer/IdentityServer3#2035]
When i have accessed the sample in local, display the no permissions, what happened?
Is it  configuration data?.

![image](https://cloud.githubusercontent.com/assets/7343086/10539195/c2254d72-73b2-11e5-9693-7876c8cd2a95.png)

**Comment by zhangkefeng2010** [comment]
Need to set up Clients? Users? Scopes? source path:\IdentityServer3\source\Host

**Comment by brockallen** [comment]
That page shows what consent the user has given to which client apps (and allows the user to revoke the prior consent). Has your user given consent to any apps?

**Comment by zhangkefeng2010** [comment]
How to set up?

**Comment by brockallen** [comment]
Have you followed the samples and read the docs?
