### ISSUE TITLE
How to redirect to login screen with error message from failed two factor authentication

### ISSUE THREAD

**Issue by mirecg** [IdentityServer/IdentityServer3#2036]
Hi, I'm trying 2fa scenario with client certificate as the second factor in two-factor authentication. 
I would like to handle the situation when the authentication using the 2nd factor fails, e.g. user has choosen wrong certificate. I want him to return back to login screen with displayed error that it has failed.

Looking at the AspNetIdentity_2fa sample, I don't know how to achieve this from TwoFactorController, to send the error message to login screen. There is just return Redirect(resumeUrl).

**Comment by brockallen** [comment]
We don't have a way right now to do this. You'd have to store the error somehow (perhaps via this: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinEnvironmentExtensions.cs#L268 or just your own cookie), and then use this (https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinEnvironmentExtensions.cs#L345) to start over again, which would re-trigger PreAuthn in the user service, at which point you could extract your error and inform IdSvr of it via an AuthenticateResult to get it displayed. I've never tried to do exactly what I'm suggest, so if it doesn't work let us know.

**Comment by mirecg** [comment]
Great! I was thinking about the similar flow, but I wasn't sure how to transfer the error message to UserService.PreAuthenticateAsync. Thank you. I will try.

**Comment by mirecg** [comment]
Hi, it works but the result is not very satisfying. 
Using proposed flow with passing somehow error message to PreAutheticateAsync, which in turn returns AuthenticateResult with that error message, results in showing error page with that message.

But to have nice flow for user it would be great if I could display error message on login screen, like it currently does for invalid username/password.
![image](https://cloud.githubusercontent.com/assets/11613589/10542924/d400000a-741b-11e5-9413-9c28c04d1659.png)

I would like to achieve the same for invalid certificate:
![image](https://cloud.githubusercontent.com/assets/11613589/10542948/f20e56aa-741b-11e5-87fb-04312ba37f3c.png)

**Comment by brockallen** [comment]
Pass the error message you want in the ctor of the AuthenticateResult.

**Comment by mirecg** [comment]
That's what I have done. The result is showing an general error page, instead of login page. See the screenshots in the previous post.

**Comment by brockallen** [comment]
Ah ok, then. I had forgotten that showing the general error page was the behavior. Perhaps this requires additional APIs/flags to achieve then if we pursue the approach I suggested.

Another possible approach is to trigger preauthn first to get the cert, then to handle password second. If you return errors from AuthLocale then it should keep you on the login page.

**Comment by mirecg** [comment]
Changing the order of authentication factors isn't very suitable.

I would suggest to extend the AuthenticationResult with indication what kind of error occurred, to be able to choose to shot it at login screen or at general error page. I have made some local changes at AuthenticationController to be able to proof that I can show the error from the second factor authentication at login screen.

**Comment by mirecg** [comment]
Hi, is there any chance to get this behavior into IdentityServer?

Normal flow is to enter username/password and then alternatively require the user to provide the second factor using sms code or client certificate based on some business requirements. So changing the order of authentication flow is not possible for me.
Whithout ability to display the error on login page (from second factor screen), I'm not able to migrate existing authentication solution to IdentityServer.

**Comment by brockallen** [comment]
Yep, we understand. We'll have to discuss how this would fit in if or how it would affect anything else.

**Comment by mirecg** [comment]
Do you have any news/progress about this feature? When can I expect to have this feature released?

**Comment by leastprivilege** [comment]
We don't know yet - you can follow the release planning here:

https://huboard.com/IdentityServer/IdentityServer3#/milestones

**Comment by leastprivilege** [comment]
have you worked around that - still an issue?

**Comment by mirecg** [comment]
Hi, yes. It’s still an issue for me.

**Comment by leastprivilege** [comment]
@brockallen Would a new property on the pre-authN ctx to show the login UI work for you?

**Comment by mirecg** [comment]
Yes, I think it should be OK. 
What I expect from it is that setting that property will allow redirect to login page and will respect what's in the AuthenticationResult, so that I can show the error reason what has failed, why the user was redirected, you can see the expected result on the screenshot from my previous posts.

**Comment by brockallen** [comment]
Yes, it'd be something like `UseLoginPageForError` or some other equally long name.

**Comment by mirecg** [comment]
OK, it makes sense. Thank you.

**Comment by brockallen** [comment]
Added a `ShowLoginPageOnErrorResult` to the `PreAuthenticationContext` for this on the dev branch.

**Comment by brockallen** [comment]
Added a `ShowLoginPageOnErrorResult` to the `PreAuthenticationContext` for this on the dev branch.

**Comment by mirecg** [comment]
Thank you. I have tested in my scenario and it works as expected.

**Comment by brockallen** [comment]
Excellent!
