### ISSUE TITLE
Scope permissions for an api

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#2037]
We have multiple apis performing CRUD operations on lots of different data. 

If an API handles various types of objects (customers, orders, items) and various operations on them, how would this best be described in a token? How will a token look like giving write access to customer 1 but not anything else? And equally important, how is this access verified on the API side?

I've only seen the IAppBuilder extension so far validating required scope, but that is not specific enough. I want actions in controllers to make sure that the token gives correct access to this one customer/order/item, but not any other.

**Comment by brockallen** [comment]
The token describes the caller. This is typically a combination of a user and a client. From those you have to implement authorization. Scopes in the token just tell you that the client app is authorized to be using the API (which is a coarse grained authorization check), but further authorization logic is up to your implementation.

**Comment by snothub** [comment]
Understood and agreed. What about RequiredScopes property of the options object passed to the middleware, is that either one or all if multiple scopes specified? I'm asking because an API might require one scope from one client and proceed with necessary authorization, while in another case would trust another scope with no further authorization.

**Comment by brockallen** [comment]
The required scopes at the token validation middleware is a logical "or", so it means at least one must be present.
