### ISSUE TITLE
Scrub passwords from logs

### ISSUE THREAD

**Issue by ayoung** [IdentityServer/IdentityServer3#2038]
Is there a way to scrub/sanitize the passwords when logging?

The [TokenRequestValidator logs the entire validated request](https://github.com/IdentityServer/IdentityServer3/blob/a6e2b6bdfd1516af6cd9fdc9f46a08bb23bb553e/source/Core/Validation/TokenRequestValidator.cs#L702) which includes the password. This is seen as security issue for us.

Thanks.

**Comment by brockallen** [comment]
That's why logging is only designed for development time.

**Comment by ayoung** [comment]
Not all the time though. We may want to turn logging on when debugging a production issue.

**Comment by brockallen** [comment]
If you want to send a PR, then we can log a filtered version of that data structure. Make sure to make a copy of the validated request when logging (as opposed to just nulling out the sensitive properties).

**Comment by ayoung** [comment]
Ok. Thanks. Will do. You can close this for now.

**Comment by leastprivilege** [comment]
I will split it up into several checkins (your PR included multiple concerns). thanks!
