### ISSUE TITLE
[Question] Install IdentityServer on a free Azure account

### ISSUE THREAD

**Issue by danielbsig** [IdentityServer/IdentityServer3#2040]
Hi,

Is it at all possible to install IdentityServer on an Azure machine operating under a free account? Those accounts don't support SSL. Doesn't Idsrv3 require SSL? N.b. I'm currently only thinking of using it in a dev scenario, where usernames/passwords of all users are open to everyone, and the app would be used for testing/demo purposes only.

Regards,
Daníel

**Comment by leastprivilege** [comment]
you can turn off the SSL requirement on options.
