### ISSUE TITLE
Allow for both sliding and absolute expiration on authentication cookies

### ISSUE THREAD

**Issue by tillig** [IdentityServer/IdentityServer3#2043]
I have a system where we don't want a persistent "remember me" cookie, but we do want to allow for "inactive user" timeouts (sliding expiration) as well as a top-end maximum "active" timeout (absolute expiration) on the identity server authentication cookie.

Unfortunately, the standard OWIN middleware only allows for _either_ sliding _or_ absolute expiration, and the "remember me" cookie is always persistent.

It would be nice if we could get to the cookie provider to follow the @brockallen [article here](http://brockallen.com/2014/11/18/sliding-and-absolute-expiration-with-cookie-authentication-middleware/) but it's not accessible through the `IdentityServerOptions.AuthenticationOptions.CookieOptions`.

First-class support for sliding + absolute expiration would be my preference, but I could get by if the `CookieOptions` also exposed a `Provider` property.

**Comment by brockallen** [comment]
Ideally Microsoft would have this support in their middleware. We can take a look, since I do think it's useful. But it's not specific to IdSvr.

**Comment by tillig** [comment]
Agreed, it's not IdSvr specific, but unless you have the ability to influence the middleware... :)

**Comment by tillig** [comment]
(Whoops, wrong button.)

**Comment by tillig** [comment]
For completeness, [I added an issue to the Katana repo for official support](https://katanaproject.codeplex.com/workitem/431).

**Comment by leastprivilege** [comment]
let us know if there is any update (though I doubt that MS will fix anything in Katana anymore).
