### ISSUE TITLE
How to enforce signin configuration?

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3#2044]
In AspNet Identity, there is a SignInManager and configuration.  Does IdSvr use this?  I can't seem to get anything working (such as failed attempts, lockout enforcement, etc)

**Comment by dapug** [comment]
More specifically, I have this in my IdSvr, and is registered as appropriate in ConfigureUserService:

    public class UserManager : UserManager<User, string>
    {
        public UserManager(UserStore store)
            : base(store)
        {
            this.ClaimsIdentityFactory = new ClaimsFactory();
            this.MaxFailedAccessAttemptsBeforeLockout = 5;
            this.UserLockoutEnabledByDefault = true;
            this.PasswordValidator = new PasswordValidator
            {
                RequiredLength = 8,
                //RequireNonLetterOrDigit = true,
                //RequireDigit = true,
                RequireLowercase = true,
                RequireUppercase = true,
            };
        }
    }

This has no effect.  Accounts never get locked out.   Is this not the way to configure things?

**Comment by brockallen** [comment]
That's part of the design issue with AspId, IMO -- you still have to do these sort of booking tasks yourself. Did you look at our starter/sample AspId user service implementation (in the other repo: https://github.com/IdentityServer/IdentityServer3.AspNetIdentity).

**Comment by dapug** [comment]
Yes, I am familiar with the sample there and have things set up and operable.  Are you saying that I need to put in some Override methods in UserManager? (like AccessFailedAsync?)  Even if so, it raises a question about how to hook into IdSvr events (user auth failed, etc) and how to reflect what is needed in IdSvr UI.

Is there a better data store you recommend where this stuff "just works"?  I was looking at MembershipReboot, but thought that AspId was more "future proof".

**Comment by brockallen** [comment]
I think that sort of code is in the AspId user manager we provide. 

And these checks are the same code that you'd need to write if you were building a generic MVC app that uses AspId. It makes me feel like I'm missing your question.

**Comment by dapug** [comment]
Yes, I have reviewed the source of your awesome AspNetIdentityUserService and I see where lockout should be happening.  So I'm not sure what I could be missing. I'm not seeing the expected behavior (eg. cannot get Lockout to happen).  

My UserService is wired up as follows (below), with UserManager being passed in and configured as shown (above).

    public class UserService : AspNetIdentityUserService<User, string>
    {
        public UserService(UserManager userMgr) : base(userMgr)
        {
        }
    }

**Comment by brockallen** [comment]
Try to get lockout to work in a standalone MVC app. Once you know it's working in that scenario, then map it to IdSvr. I don't have any other suggestions. Sorry.

**Comment by dapug** [comment]
Thanks brock, I'm using a standalone app, the exact sample you linked in fact. I don't expect you guys to support my projects, I just need to be sure of the limitations/expectations of the platform.

RESOLVED:

Check this out.  If you don't supply ALL the confg settings, aspnet does really crazy weird things!  Do NOT screw this up!

    this.DefaultAccountLockoutTimeSpan = TimeSpan.FromMinutes(5);

Since I didn't specify the time (in my UserManager code above), it defaulted to 0, which caused the expiration of the lockout to be immediate! Lockout would happen, but also unlock immediately.  doh.  :)

Also note, IdSvr does NOT pick these values up from web.config, despite Asp.Net supporting the following:

    <add key="UserLockoutEnabledByDefault" value="true" />
    <add key="DefaultAccountLockoutTimeSpan" value="2" />
    <add key="MaxFailedAccessAttemptsBeforeLockout" value="3" />

So be sure to set config in code like I showed, and/or use config manager to pull this in for you.

Now, if only I could get the UI to reflect an appropriate "Account is locked out. Click here to reset your password".  That's my next project...

Brock, I'll see about doing a pull request and add that UserManager config into your sample.  Maybe the docs too.  Getting lockout working is just not clear anywhere online for this, and I'd like to help out since you guys are so dang responsive and helpful in these posts.

**Comment by brockallen** [comment]
That's why you should have chosen MembershipReboot instead :P

**Comment by dapug** [comment]
ha!  Actually, I just might do that. I read up on it but just wasn't sure if we should do that for the long haul.  AspNet Membership was so weak, AspNet membership is better.  If there was an AspId Reboot...   maybe.  

The other critical thing for my team is we might (maybe) would like to migrate to AD B2C eventually (if costs are low enough), so we need to be sure we can migrate passwords without causing all our users to have to re-authenticate.

Anyway... I submitted that pull request.  Hopefully it helps others.
