### ISSUE TITLE
Resource Owner Flow, obtaining token using external provider

### ISSUE THREAD

**Issue by Alan66** [IdentityServer/IdentityServer3#2045]
In the resource owner credentials flow I know how to obtain access and refresh tokens in case of local database authentication, but what would we do if we want to obtain those tokens using external providers, such as google?

A quick hint on that would be appreciated,.

**Comment by brockallen** [comment]
That's simply not possible. You need to use the browser flows if you want to do external authentication.

**Comment by brandonyoung** [comment]
When you say "browser flows" what do you mean?  If we are providing our own login page to handle resource owner, how would we provide a google sign on for example?

**Comment by brockallen** [comment]
> When you say "browser flows" what do you mean? 

You must present the browser to the user to have them login.

> If we are providing our own login page to handle resource owner, how would we provide a google sign on for example? 

You can't, as google doesn't support the non-browser flows.

**Comment by codyskidmore** [comment]
Is it possible to use the resource owner flow with other external Idps such as ADFS or IBM WebSEAL?
