### ISSUE TITLE
Question: How to identify if user is logged in user external provider?

### ISSUE THREAD

**Issue by raxitr** [IdentityServer/IdentityServer3#2046]
What is the best way to check whether is logged in using external provider i.e. facebook, google etc.

I was thinking to add custom claim to identify OnAuthenticated callback. Is this how normally done?

**Comment by brockallen** [comment]
idp and amr claims. idp is which idp used and amr is one of these (or something custom you provide in your user service): https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Constants.cs#L503

**Comment by raxitr** [comment]
Thank you, I will post the code once I complete it just to confirm.
