### ISSUE TITLE
Using IdS behind load balancer -- issue when hitting diffent machines in a series of redirects

### ISSUE THREAD

**Issue by AndersJuul** [IdentityServer/IdentityServer3#2047]
We are using IdS and have implemented our own Handler for SSO based on Gitter example to make it use our Ping Federate server.

It works like a charm in development with a single IdS instance, but fails when we deploy to QA with a load balancer in front of a twin set of IdS servers.

Observed behavior is that we stay on the IdS oauth login page. Using the SSO login a number of times, we can 'get lucky' and hit same instance.

We are not making use of server-specific storage from request to request.

We suspected encryption of request content to be a culprit, if done differently on the two machines, but machinekey is identical and use of DataProtector made no difference.

I'm a bit at loss wrt what to examine next. Do you have any suggestions on what I should try out?

Below my startup. Thanks for any help...

BR, Anders

    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var identityServerConfiguration = new IdentityServerConfiguration();

            Logger.SetupGlobalLogger(lc =>
            {
                if (bool.Parse(identityServerConfiguration.LogToConsoleEnabled))
                {
                    lc.WriteTo.Console(LogEventLevel.Debug);
                }
                return lc;
            });

            try
            {
                app.SetLoggerFactory(new SeriLogLoggerFactory());
                app
                    .UseOAuth()
                    .UseWebDiagnostics()
                    .UseMonitoring(() => new IdentityMonitor());

                var factory = InMemoryFactory.Create(
                    Users.Get(),
                    Clients.Get(),
                    Scopes.Get());

                var consentService = new ConsentService();
                factory.ConsentService= new Registration<IConsentService>(resolver => consentService);
                
                var options = new IdentityServerOptions
                {
                    IssuerUri = identityServerConfiguration.IssuerUri,
                    SiteName = identityServerConfiguration.SiteName,
                    SigningCertificate = Certificate.Get(),
                    Factory = factory,
                    RequireSsl = false,
                    
                    LoggingOptions = new LoggingOptions
                    {
                        WebApiDiagnosticsIsVerbose = identityServerConfiguration.WebApiDiagnosticsIsVerbose
                    },
                    PublicOrigin = identityServerConfiguration.PublicHostAddress,
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        IdentityProviders = ConfigureIdentityProviders,
                        EnableLocalLogin = identityServerConfiguration.EnableLocalLogin,
                        EnableSignOutPrompt = false,
                    },
                };

                app.Map("/oauth", a => a.UseIdentityServer(options));

                Log.Information("Identity Server is up and running");
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Startup Error");
                throw;
            }
        }

        private static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var identityServerConfiguration = new IdentityServerConfiguration();

            var authorizeEndpoint = identityServerConfiguration.AuthorizeEndpoint;
            var partnerIdpId = identityServerConfiguration.PartnerIdpId;
            var targetResource = identityServerConfiguration.TargetResource;

            var agentConfig = identityServerConfiguration.GetAgentConfig();

            var agentDataProvider = new AgentDataProvider(app, new AgentProvider(), agentConfig);

            var options = new SsoAuthenticationOptions(authorizeEndpoint, partnerIdpId, targetResource,
                agentDataProvider)
            {
                Caption = "Corp SSO",
                SignInAsAuthenticationType = signInAsType
            };

            app.UseSsoAuthentication(options);
        }
    }

**Comment by leastprivilege** [comment]
anything in the logs?
IIS or self hosting?

**Comment by AndersJuul** [comment]
Hi Dominick,

It's running in IIS.

Logs are attached. Localhost goes smoothly, QA doesn't. We have tried to shut down qa machines to leave a single machine and then it goes well.

When I look at the logs I'm not able to see the problem, except it 

Kibana logs:
https://www.dropbox.com/s/ntdzogjpk551b04/localhost%20log.docx?dl=0
https://www.dropbox.com/s/gmhbnw1sso7djfu/qa%20with%20load%20balancer.docx?dl=0

(Posted as links to dropbox as I'm not allowed to attach word files).

Best regards, Anders

**Comment by leastprivilege** [comment]
Sorry - don't know what's going on. IdSrv itself works fine in load balancing.

**Comment by IDisposable** [comment]
Most likely you're setup for InProc Session storage in the web.config. When running a web farm without session pinning on the load balancer, there's no guarantee that you are hitting the same IIS machine, so the InProc session store is not present.  You need to switch to some out-of-proc session storage. https://technet.microsoft.com/en-us/library/cc754032(v=ws.10).aspx or even using NCache's drop in replacement. http://www.alachisoft.com/ncache/session-index.html or Redis http://www.brentozar.com/archive/2013/10/solving-session-state-slowndownsvideo/

Also, make sure you've got all the ```machineKey``` set the same in the web.config files. 

You can test this in a locale environment by using a web garden (e.g. multiple Worker Processes) see 
http://www.codeproject.com/Articles/114910/What-is-the-difference-between-Web-Farm-and-Web-Ga

**Comment by leastprivilege** [comment]
IdSrv does not use session store.

**Comment by AndersJuul** [comment]
@IDisposable : Good reference to web garden. I didn't know about that possibility, but I'll try to set it up.
@leastprivilege : It seems that we are using InMemoryUserService -- and in the web farm, we can see 'User is not active. Redirecting to login.'  which we do not locally. The user is active, but it appears the user is looked up in List<InMemoryUser>, which I guess could be a problem if switching between machines in the farm? Could it be a matter of us not setting a correct, non-default user service?

Best regards, Anders

2015-10-22T09:04:47.545+02:00	Redirecting to login page	Information	de6eb0b6-5235-4275-934e-6fdef8757be4	SHQA01WEBFF0101
2015-10-22T09:04:47.545+02:00	User is not active. Redirecting to login.	Information	de6eb0b6-5235-4275-934e-6fdef8757be4	SHQA01WEBFF0101
2015-10-22T09:04:47.545+02:00	Start authorize request protocol validation	Information	de6eb0b6-5235-4275-934e-6fdef8757be4	SHQA01WEBFF0101
2015-10-22T09:04:47.545+02:00	End authorize request	Information	de6eb0b6-5235-4275-934e-6fdef8757be4	SHQA01WEBFF0101
2015-10-22T09:04:47.545+02:00	Authorize request validation success
{
"ClientId"...	Information	de6eb0b6-5235-4275-934e-6fdef8757be4	SHQA01WEBFF0101
2015-10-22T09:04:47.545+02:00	Start authorize request	Information	de6eb0b6-5235-4275-934e-6fdef8757be4	SHQA01WEBFF0101
2015-10-22T09:04:47.496+02:00	redirecting to: https://qa1-accounts.contosodk.dk/oauth/connect/a...	Information	d7128171-56e9-4b75-8952-07d0b00b69e5	SHQA01WEBFF0102
2015-10-22T09:04:47.481+02:00	issuing primary signin cookie	Information	d7128171-56e9-4b75-8952-07d0b00b69e5	SHQA01WEBFF0102
2015-10-22T09:04:47.465+02:00	External identity successfully validated by user service	Information	d7128171-56e9-4b75-8952-07d0b00b69e5	SHQA01WEBFF0102
2015-10-22T09:04:47.450+02:00	external user provider: ebayCorpSSO, provider ID: 0F6FC8F4-8...	Information	d7128171-56e9-4b75-8952-07d0b00b69e5	SHQA01WEBFF0102
2015-10-22T09:04:47.418+02:00	Callback invoked from external identity provider	Information	d7128171-56e9-4b75-8952-07d0b00b69e5	SHQA01WEBFF0102

**Comment by leastprivilege** [comment]
Why are you using InMemoryUserService - this is just for demos...not for production.

**Comment by leastprivilege** [comment]
..and as the name implies stores state "in-memory"

**Comment by AndersJuul** [comment]
Ah, it was introduced when moving to IdentityServer3. I wasn't aware that it's only for demos, but of course it makes sense...

Thanks for helping out -- both of you!

**Comment by leastprivilege** [comment]
..and looking at your logs - you are doing external authentication - this def modifies the state of a user - but in-memory of course.
