### ISSUE TITLE
Content Security Policy with implicit flow and form post

### ISSUE THREAD

**Issue by Zenuka** [IdentityServer/IdentityServer3#2048]
Hi, I've set up CSP for form posts like: "form-action 'self'". Suddenly (I don't know when this issue started) my browser blocks the redirect back to the client application. The request to the authorization endpoint doesn't include response_mode=form_post so why is it performing a form post back to the client app? When I look at the blocked url it includes #id_token=[token]. Is this regular behavior? So should I add my clients to the list of allowed servers for the form-action CSP? Or is there something else wrong? Thanks for any help in advance!

**Comment by brockallen** [comment]
You're setting CSP in the client app or in IdSvr?

**Comment by Zenuka** [comment]
I've set CSP options in IdSrv

**Comment by brockallen** [comment]
Not sure -- I'd have to see it for myself to understand.

**Comment by Zenuka** [comment]
I'm going to try to reproduce it with a clean solution.

**Comment by Zenuka** [comment]
I've been able to reproduce this issue with a simple IdSrv and using the following middleware:
    public class ContentSecurityPolicyMiddleware
    {
        #region Fields
        private readonly Func<IDictionary<string, object>, Task> _next;
        private readonly string _cspString;
        #endregion

        #region Constructor(s)
        public ContentSecurityPolicyMiddleware(Func<IDictionary<string, object>, Task> next)
        {
            _next = next;

            var rules = new Dictionary<string, string>
            {
                { "default-src", "'self'" },
                { "form-action", "'self'"}
            };

            _cspString = string.Join("; ", rules.Select(r => $"{r.Key} {r.Value}"));
        }
        #endregion

        public async Task Invoke(IDictionary<string, object> env)
        {
            var context = new OwinContext(env);

            // Set the headers
            context.Response.Headers.Set("Content-Security-Policy", _cspString);
            context.Response.Headers.Set("X-Content-Security-Policy", _cspString);
            context.Response.Headers.Set("X-Webkit-CSP", _cspString);

            await _next(env);
        }
    }

And adding it to the startup.cs:
    app.Use<ContentSecurityPolicyMiddleware>();

And disable the normal CspOptions:
    CspOptions = new CspOptions { Enabled = false }

I know these aren't the standard settings but I wanted to tighten the CSP by only allowing to post forms to known other authentication servers but I guess I need to add my clients to the list as well.

**Comment by brockallen** [comment]
Relevant? https://github.com/w3c/webappsec/issues/482

**Comment by Zenuka** [comment]
Yes, I guess when returning a 302 after a post will count as a new form post for the CSP form-action. Since IdSrv posts to login then returns a 302 to authorize, which in his turn returns a 302 to the client app means I have to specify our clients in the form-action CSP.
