### ISSUE TITLE
How can I filter on a custom claim field when getting a token?

### ISSUE THREAD

**Issue by chrismikec** [IdentityServer/IdentityServer3#2049]
I am using IdentityServer successfully with a ResourceOwner flow. So I am successfully getting the user claims in a token.

However, I need to add a new column to the AspNetUserClaim table, indicating a company ID, as users can access the application as different companies from the same account (but only AS one company at a time). The user can have different claims for different companies, so I need to be able to pass in a companyId when I request the token, then have IdentityServer filter on companyId in the UserClaims to get only those claims with companyId=X.

I'm using a CustomIdentityManager with a CustomUserStore, and there is a CustomUserClaim object used by the custom context, but right now all of these are just the defaults (that is, no custom code inside them). I would imagine I could do something like  add the companyId field to the CustomUserClaim, but from there I've got no idea how I would (1) pass the companyId in when I request the token, and (2) filter based on that id.

I currently call  OAuth2Client.RequestResourceOwnerPasswordAsync to request the token.

Is this at all possible? Is there a better way to handle this?

**Comment by brockallen** [comment]
Where in your workflow does company id come in? IOW, how is it determined?

**Comment by chrismikec** [comment]
They have a default companyId on their account, so at first they are validated against this company. After they have logged in, they get prompted to find out which company they want to identify as. Once they select it, they have access to the application as that company. So, if they select a different company than their default, I want to request a new token as that company.

Does this make sense?

**Comment by brockallen** [comment]
Hmm, so they use just one uid/pwd, but when they login you want them to indicate which company?

Sounds like that might be a custom login workflow using partial logins. Then when you issue the token you send a custom claim indicating which company they selected.

Check the docs and samples for partial logins from the user service.

**Comment by chrismikec** [comment]
Sorry, I realized I left out some fundamental information here.

I am only using IdentityServerv3 to issue tokens, I am not using it for login as i have all of my own screen for that. When the user logs in on my screens, I send the username and password to IdSrv to get the token, but I am not using any screens or anything else for login.

Does this change your answer?

**Comment by brockallen** [comment]
Sorry -- you did say resource owner.

So why not indicate company in the username param and in your user service you parse it for what you need? The claims you issue from AuthenticateLocal can include the company id and then in GetProfiel you use that to filter your claims.

Another approach is to pass acr_values with the token request -- this can contain your compamny id and then you can access those in the AuthenticateLocal.

**Comment by chrismikec** [comment]
Adding company to username param sounds good. However, you have mentioned a few things I am not familiar with. Where is AuthenticateLocal and GetProfile? I don't see them mentioned anywhere in my IdentityServer implementation.

**Comment by brockallen** [comment]
Well, the user service (with those 2 methods) are the heart of your customization of IdentityServer.

**Comment by chrismikec** [comment]
Ah, thanks Brock. I wasn't overriding them as I was just using the default implementation, but I've found them now. I'll give it a go.

Thanks very much!

**Comment by chrismikec** [comment]
Actually Brock, I still have an issue here. What I was hoping to do was after the user validates their login, gets a token, then selects their company to log in as (all in that order), I was hoping to maybe use a refresh token to update the claims for the new company Id. I want to avoid having to hold on to the password across the whole login procedure because that happens first, then a whole bunch of other steps happen in between before they select their company Id. I have a refresh token, so I was hoping there was some way to hitch a company Id to this call, pluck it off on the IdSrv in the same way and filter out my claims from there.

I see that GetProfileDataAsync gets called when I request a refresh, but I was wondering if there is any way to send along a company Id here and intercept it in the same way as I was doing in AuthenticateLocalAsync? If not, is there any other way to do this other than to hold on to the password and call the AuthenticateLocalAsync again?

**Comment by brockallen** [comment]
By keeping the login in the app you're making it very difficult to use the token service the way the spec was designed and the way we designed IdSvr. I don't have a good simple answer for you. Perhaps you could get a refresh token and pass a custom param indicating that new claims are desired. The other idea is that you build a custom API protectedc by the access token that gives back the company specific claims - sort of like the user info endpoint, but based on the caller not the subject.

All in all, it sounds like you're using the wrong approach. Why not just get an access token and in the API where it's being used based upon the resource being accessed determine if the subject can access it?
