### ISSUE TITLE
Active STS, WS-Trust and ActAs tokens

### ISSUE THREAD

**Issue by mattwhetton** [IdentityServer/IdentityServer3#2050]
Hi,

We've been using the first version of identity server for a couple of years in a fairly complex environment (it authenticates desktop clients both using windows auth and username, web clients both passive and active and also token delegation to our WCF service layer). We're finally looking at upgrading and are going through feasibility.

My question is does or can Identity Server 3 work as an active/passive sts that also supports wcf and ActAs tokens for delegation?

If so are there any samples of any parts of this?! I've found WS-Federation samples, and passive windows clients but thats about it I think.

Thanks for your help

Matt

**Comment by leastprivilege** [comment]
We don't support WS-Trust anymore.

**Comment by mattwhetton** [comment]
I assume that means that you don't support active sts anymore? The Thinktecture.IdentityModel project does have ws-trust elements to it though doesnt it?

**Comment by leastprivilege** [comment]
We support the "active" flows of OAuth 2.0 like resource owner and client credentials. But not WS-Trust.
