### ISSUE TITLE
Question: 404 on connect/endsession

### ISSUE THREAD

**Issue by devscott** [IdentityServer/IdentityServer3#2053]
We have a java script client that uses a hybrid flow, and everything works well up until the point you want to log out. At logout, some users get a 404 at the endpoint connect/endsesion, where for other people everything work fine. 

The instance of IdentityServer3 (latest version as of this post) is running within IIS. Think it might be a server permission issue on had two people with the same permissions try and again one experience the 404. 

For the ones that experience the 404, if they manually browse to the connect/endsession and not include the GET parameters (id_token_hint and post_logout_redirect_uri) it logs them out successfully.

Any insights?

**Comment by brockallen** [comment]
What build of IdSvr?

**Comment by brockallen** [comment]
Also, can you test the JS client sample with your IdSvr and see if it works? https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient

**Comment by devscott** [comment]
We are using build 2.0.2

The JS Sample Client is working for a user who normally receives a 404 on logout when we use the implicit ClientID. When we use a ClientID that is setup as a hybrid flow with the JS Sample Client, things break and we notice some strange behavior in the logs. 

Basically what we are seeing is that for the Client Configuration on the Server, the flow is getting dynamically changed from a Hybrid Flow to a Implicit flow , and the client is rejected with not authorized. If this is not as intended, let me know and I can create a separate issue for this with what I am seeing in the logs. 

The implicit Flow works well for all our .NET MVC apps and I haven't heard of user having a logout issue here.  It looks like the troublesome part is the hybrid flow.

**Comment by brockallen** [comment]
> Basically what we are seeing is that for the Client Configuration on the Server, the flow is getting dynamically changed from a Hybrid Flow to a Implicit flow

Not sure what this means. 

Also, a JS client should not be using the hybrid flow -- why are you doing that?

**Comment by devscott** [comment]
I'll pull a copy of the logs for you when I get back in the office on Monday.

The particular JS client that I am using doesn't support implicit flow. From my understanding , hybrid is between implicit and AuthorizationCode. In our test environment, everything works. once we take the code to production, one some users are able to log out. My question here, is why some but not others?

**Comment by brockallen** [comment]
I still don't know why some and not others -- it seems more debugging (and looking at logs) is needed.

**Comment by dcinzona** [comment]
We are seeing this as well... could be an issue with the url being too long...

**Comment by brockallen** [comment]
If your id_token is too large, then consider not putting as many claims into it. This means changing the ScopeClaims to not be "always include".

**Comment by dcinzona** [comment]
Yup, I see that. Thanks

On Dec 31, 2015, at 9:45 AM, Brock Allen <notifications@github.com<mailto:notifications@github.com>> wrote:


If your id_token is too large, then consider not putting as many claims into it. This means changing the ScopeClaims to not be "always include".

-

**Comment by brockallen** [comment]
@devscott i noticed this has been open for a while. did you ever sort out your original problem?

**Comment by catdevnull** [comment]
Just a quick note to say that I've just been experiencing this issue too. Identity Server is running on IIS and it appears the error code was 404.14:

https://support.microsoft.com/en-us/kb/942073

A count of the full URL came in around 2900 characters - according to the KB article the default on IIS7 is 4096, as we're on IIS8 it may be smaller (or our sysadmins have configured it lower for security reasons)

Removing the all_claims scope meant the id_token was considerably shorter and the redirect worked correctly.

So it would seem the issue is definitely IIS with long id_token_hint parameters not playing nicely.

It does raise the question of - if I want all my claims (for whatever reason) what's the best way to get at them without growing the id_token? Excuse my ignorance I've only been getting up to speed with IdentityServer in the last few weeks.

Richard

**Comment by devscott** [comment]
@catdevnull glad you have found a work around. I will apply it here and see if it resolves our issue.

**Comment by dcinzona** [comment]
@catdevnull this code here adds the claims to the cookie, while not increasing the size of the id_token
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client%20(Hybrid)/Startup.cs#L41-L92

Caveat: as long as you don't have it set to always include the claim in the id_token, that is.

**Comment by catdevnull** [comment]
@dcinzona Thanks for that, I'll have a look at it!

**Comment by dcinzona** [comment]
No problem!
