### ISSUE TITLE
HTTP Status codes

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3#2056]
Apologies if this is a duplicate. 

Is there any way we can send different http status codes on invalid credentials ?

 context.AuthenticateResult = new AuthenticateResult("error");

I can only see the above implementation and I don't see how I can change the HTTP status code sent back to caller. Also is there a way to send a custom JSON back to caller on invalid credentials ?

**Comment by leastprivilege** [comment]
The OAuth2/OpenID Connect spec defines error messages and status codes.

**Comment by leastprivilege** [comment]
IOW no - you can't

**Comment by aaabdul** [comment]
Thank you. Makes sense. What other ways are there to send custom error codes back to caller ?

**Comment by leastprivilege** [comment]
None. why do you want to do that?

**Comment by aaabdul** [comment]
For example, 
error code 0001 for user disabled, 0002 for user locked, etc. So the caller user their own custom error messages based on the code provided.

**Comment by leastprivilege** [comment]
Well - you can return custom error messages (using authenticate result) - but for security reasons you shouldn't.

**Comment by aaabdul** [comment]
We have several applications using identity server and each application wants to display custom error message specific to it's domain. If identity server can return an additional property called error code along with error description (generic error message) then it would be easier for client to render their own error message. 

If this is not possible we are going to have to use error description as error code. What do you think ?

**Comment by leastprivilege** [comment]
No plans for that right now - sorry.

**Comment by leastprivilege** [comment]
But you can open a feature request with a description of how you think this should work.
