### ISSUE TITLE
Adding claim descriptions from OpenID Connect spec to the ClaimTypes constants.

### ISSUE THREAD

**Issue by dylanbeattie** [IdentityServer/IdentityServer3#2058]
Hey,

Core.Constants.ClaimTypes contains a series of string constants for many of the claim identifiers specified in the OpenID Connect specification. I'd like to add the associated description fields from the http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims to an XmlDoc <summary /> comment alongside each of these identifiers, so that IDEs with Intellisense support will display the claim field description and acceptable values. Many of these fields are self-explanatory, but in some cases it's unclear what the accepted values are - "true" vs "false", supported gender values, the exact meanings of email_verified within the context of the spec - and the fact that some date fields (birthdate) are ISO8601 strings whilst others (updated_at) are IntDate numbers of seconds since the epoch. 

I've already done this in my own fork of the project; would there be any interest in raising this as a pull request against the dev branch?

Thanks,

Dylan

**Comment by leastprivilege** [comment]
Yes please

**Comment by dylanbeattie** [comment]
https://github.com/IdentityServer/IdentityServer3/pull/2064
