### ISSUE TITLE
Remember querystrings and send them back when post bakc to RedirectUri

### ISSUE THREAD

**Issue by highsierra** [IdentityServer/IdentityServer3#2059]
Would like IdSrv3 to be able to accept and send back custom querystrings sent to the /login? upon user's successful authentication.  e,g. if my RP redirects to IdSrv3 for login with the following URL:

/login?signin=ac706458bb0df2e077c8cf7179f1eb6d&mykey=xxxxxxxxx&anotherkey=yyyyyy

I'd like the post to my RP redirectUri upon authentication to have the querystring attached as is:

<my RP>/continue.aspx?mykey=xxxxxxxxx&anotherkey=yyyyyy

**Comment by leastprivilege** [comment]
Redirect URIs are fixed. You have to use the state parameter to round trip data - but be aware that this now becomes an input validation concern for you.
