### ISSUE TITLE
IdServ with IdManager demo

### ISSUE THREAD

**Issue by fatagun** [IdentityServer/IdentityServer3#2062]
Hello,

Can you give a sample in which IdManager and IdServ working together?

Thanks.

**Comment by brockallen** [comment]
Here are two: 

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MembershipReboot
