### ISSUE TITLE
RememberMeDuration Ignored During Partial Signin

### ISSUE THREAD

**Issue by AnEmptyReece** [IdentityServer/IdentityServer3#2063]
I'm seeing a difference in the cookie expiration that gets set depending on whether a normal signin is invoked, or if a partial-signin is invoked.

For example, if I select "Remember Me" on the login screen, and then have no further interactions as part of the flow then I can see the idsrv cookie being set with a +30 days expiration as per the RememberMeDuration setting.

However, if the login flow becomes partial, i.e it invokes TFA or an EULA, then despite clicking Remember Me the idsrv cookie is only getting set with an expiration time equal to the ExpireTimeSpan settings (because I have IsPersistent set to true).

I know this isn't unique to my implementation as I've recreated in using your CustomUserService sample with the EulaAtLoginUserService.

Having a quick look at the idsrv code seems to confirm that the "Remember Me" setting does not get considered when resuming a partial signin.

Am I missing something somewhere and is this by design? Or is this a genuine issue?

If it's the latter, would an option be for you to store the "Remember Me" selection as a Claim during a partial signin and then recall (and remove) it when the partial signin is resumed?

Many thanks!

**Comment by brockallen** [comment]
I can look into it.

**Comment by brockallen** [comment]
Ok, I confirmed this bug. It's now fixed on dev. Mind trying against the myget build to confirm that it's working as expected?

Requires docs update (added new Owin extension: GetPartialLoginRememberMeAsync).

**Comment by AnEmptyReece** [comment]
Hi Brock, thanks for doing this.

I didn't think it had worked at first, but it turned out that in my partial signin logic where I am removing some of my own claims and then calling context.Authentication.SignIn(authentication.Identity), I needed to change that to also pass in the existing context.Authentication.Properties, otherwise they were not getting carried through.

**Comment by brockallen** [comment]
Yes, if you're also then taking control of the signin, you need to maintain the properties. If you use this API to issue the cookie: https://github.com/IdentityServer/IdentityServer3/blob/dev/source/Core/Extensions/OwinEnvironmentExtensions.cs#L154

then you can now query GetPartialLoginRememberMeAsync to set this property:

https://github.com/IdentityServer/IdentityServer3/blob/dev/source/Core/Models/AuthenticatedLogin.cs#L79

**Comment by AnEmptyReece** [comment]
I'm not taking control of signin per se, I set some claims in the user service that indicate certain partial elements that need to be completed, such as EULA, TFA etc. I then redirect to a custom partial controller and begin the user journey of these there. I need to remove each claim indicator as it's successfully completed - hence the call(s) to .SignIn().

At the end of all this I simply redirect to the resume partial url.

Perhaps not the most elegant of solutions but it works!

Anyway, thanks for the fix and info!
