### ISSUE TITLE
Client assertion (private_key_jwt) support

### ISSUE THREAD

**Issue by uncleyo** [IdentityServer/IdentityServer3#2065]
Hey,

I've spent some time setting up TLS certificates for client authentication and was completely disappointed with the complexity of the setup. However, I really needed some asymmetric key solution for my setup. And I wanted it to be as _standard_ as it gets.

So I've implemented the necessary extensions for the IdentityServer to add support for _private_key_jwt_ (RS256 signed tokens) client authentication method as defined in the [OIDC spec](http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication)
Still need to add some extra test coverage for the edge cases, but otherwise it is a pretty straightforward implementation.
And I didn't bother extending the metadata endpoint to indicate support for it so far (since it is kinda hardcoded and ain't easy to do from the outside).

There are no changes to the configuration necessary in the simplest case.

Here are some highlights:

- Implementation is basically about implementing the necessary ISecretParser/ISecretValidator pair.
- I reuse same existing `X509CertificateThumbprint` client secrets used for client certificate authentication.
- If client assertion token embeds `x5c` certificate key, its thumbprint is checked against client secrets and if it matches, I use it to validate the token.
- To validate tokens that only embed `x5t`, users can provide an implementation of `IClientCertificateStore`. Can add a default implementation that would use "Other People" certificate store or something like that (would appreciate an advice on this).
- Token replay protection is supported
- Tested for compatibility with at least one Java client implementation: [connect2id](http://connect2id.com/products/nimbus-oauth-openid-connect-sdk)

_Note: It should be fairly easy to add client_secret_jwt (HMAC signed tokens) method support as well, but the way I see it, it would require storing shared keys unhashed, which requires some extra consideration first, IMO._

So now my question is: would you like to have a pull request for this?

**Comment by leastprivilege** [comment]
Hey, 

cool! Yes please send a PR so I can have a look.

thanks!

**Comment by leastprivilege** [comment]
feel free to "start" the PR - meaning open a new PR - this way we can have a discussion / code review.

**Comment by uncleyo** [comment]
When I looked at the codebase from inside, I actually decided to get rid of `IClientCertificateStore` and add another secret type for base64 encoded certificates instead. Unfortunately, conversion back-and-forth is necessary to keep it in a string `Value` property, but I still think it is simpler this way.

Also, you can notice that I had to add yet another cache interface for token replay cache and that is because the existing ICache doesn't support `bool Add(...)` semantics.
