### ISSUE TITLE
Restricting logins to specific clients

### ISSUE THREAD

**Issue by thj-dk** [IdentityServer/IdentityServer3#2066]
Hi,

We have a single Identity Server and need to restrict available logins to specific clients, so only a subset of all user accounts is able to login. In our database, user accounts are mapped to customers, who has clients that needs to authenticate.

Can I ask how you would approach this, tying customer information to clients (scope?) and passing this value down through the authentication layer (using MembershipReboot).

**Comment by leastprivilege** [comment]
you have the client id in AuthenticateLocal - isn't that enough?

**Comment by thj-dk** [comment]
Sorry, I forgot to mention that customers can have more than one client. Hence a client id wouldn't be sufficient unless we should do the mapping elsewhere.

Does it make sense to use a scope? Can you configure Identity Server to always require a specific scope from a client?

**Comment by leastprivilege** [comment]
no

**Comment by leastprivilege** [comment]
if you want to enforce anything client specific at logon time - you have all the info in the SignInMessage - the rest is up to you.

**Comment by thj-dk** [comment]
But do you think it makes sense to use the scope option in OAuth? Then I'll have to figure out how to make it required.

**Comment by leastprivilege** [comment]
No - scopes model resources - not client details.
