### ISSUE TITLE
A Deeper Look at RedirectToIdentityProvider

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3#2067]
Logout questions have been raised many times in this project.  However, I wanted to bring up a different than typical perspective.

RedirectToIdentityProvider and IdTokenHint are Microsoft properties and methods in the OWIN/OpenId libraries, yet a google search results in almost entirely IdentityServer3 results.  Is this feature really only used by IdSvr?

More importantly, **RedirectToIdentityProvider** requires the **id_token**.  This is a problem because the id_token is a short lived (5 min) ONE time use token used to get you initially signed in to your client, and if stored is nothing more than **Cookie BLOAT** for the entire duration of the user using the app in their browser... that is until they decide to log out!  Suddenly the dead and otherwise useless id_token is required again.  I was not planning on storing the id_token because of the cookie payload.

Am I understanding the usefulness of id_token correctly?

I get the concerns around security, but surely there is a better way. Two things that come to mind are: 

-  1) you can ONLY redirect to Urls pre-configured in IdSvr anyway, so what is the big concern?  

-  2)  one thing I DO keep stored in the cookie is the **AccessToken** because my web client makes calls to secured APIs.  IdSvr also accepts AccessToken for its UserInfo Service.  So why wouldn't this be sufficient as the token hint?

**Comment by leastprivilege** [comment]
because spec

http://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Comment by dapug** [comment]
Yeah. Perhaps this is a change spec conversation for another forum.  I am just not excited about storing the id token, and not seeing the reason (i.e. why the open ID board saw this as the only way to accomplish this).

But I'm not as well versed in security expertise, so who am I to say? :)  I did noticed id_token_hint is "Recommended" as opposed to required.  What is the security risk of relying only on the pre-registered redirect Uris?

**Comment by leastprivilege** [comment]
And how would you know which client initiated the logout?

**Comment by dapug** [comment]
Well, that might come back to the "change spec" conversation, allow either id_token or access_token.  Both have the client_id.

**Comment by leastprivilege** [comment]
Feel free to start a conversation with the openid foundation.

**Comment by dapug** [comment]
Sounds good.  I mean, if I'm on to something here and not in left field, right?  I know we can all agree cookie payload minimization is a worthwhile thing.

**Comment by leastprivilege** [comment]
I agree that the current mechanism is not very convenient. But I don't think that the access token is a better way of doing it. 

Maybe storing the id token somewhere else than a cookie is the right way to go anyways. ...or just don't do a redirect after logout. The only safe way of logging out the is closing the browser anyways.

**Comment by dapug** [comment]
I guess we'll see where this goes!
https://getsatisfaction.com/openid/topics/need-a-better-way-to-logout-consider-access-token-as-a-token-hint

Thanks for the reality check on this one. I suspect there wont be a perfect solution ('tis the constant battle between good security and UX).

**Comment by leastprivilege** [comment]
keep us posted!
