### ISSUE TITLE
Can we host IdentityServer and its client in same process

### ISSUE THREAD

**Issue by programmer-pragmatic** [IdentityServer/IdentityServer3#2069]
We are creating one MVC web application where WebAPI part is needed to be exposed to other application. We do not want to create separate process/machine for WebAPI+IdentityServer and Web application.
I know that WebAPI and Web application can be hosted in same process, but can we host Identity server in the same process.

Thanks In Advance

**Comment by devscott** [comment]
Yes, checkout the [getting started tutorial](https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html). The tutorial does exactly that.

**Comment by UlyssesAlves** [comment]
I'm trying to map a path to Identity Server, but this is bringing me issues when I try to set the Authority of my IdentityServerBearerTokenAuthenticationOptions while configuring Server Bearer Token Authentication, because IdentityServer was not started yet when I call app.UseIdentityServerBearerTokenAuthentication(...). Below is how my code looks like:

`public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);

            HttpConfiguration httpConfiguration = new HttpConfiguration();

           httpConfiguration.Filters.Add(new AuthorizeAttribute());

            app.Map("/identity", identityServerApp =>
            {
                identityServerApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "my site name",
                    RequireSsl = false, 
                    Factory = new IdentityServerServiceFactory()
                        .UseInMemoryUsers(someUsers)
                        .UseInMemoryClients(someClients)
                        .UseInMemoryScopes(someScopes)
                });
            });

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "http://localhost:60295/identity", // Here is the problem: identity server is not loaded yet, than the code hangs until it cancels the task.

                ClientId = "api",
                ClientSecret = "api-secret",

                RequiredScopes = new[] { "api" }
            });

            app.UseWebApi(httpConfiguration);
        }
    }`

How can I set Server Bearer Token Authentication  to use my mapped Identity Server if the server has not finished loading yet?

**Comment by penleychan** [comment]
@UlyssesAlves Did you figured it out how to fix that issue? I am having the same problem. 

Regards

**Comment by UlyssesAlves** [comment]
@penleychan It's seven months since I finished the implementation of this project, so I unfortunately don't remember exactly what I did to solve that issue. 

The good news is that it worked  properly in the end, so I'll share with you my updated `Startup` class' code with the new configuration. Maybe looking at the code you may find something useful. Hope this can be helpful in some way. Sorry for not being able to help you any better.

    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.Use(async (contexto, next) =>
            {
                contexto.Response.Headers.Add("Access-Control-Allow-Origin", new[] { "*" });
                await next();
            });

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                IssuerName = "issuerName",
                SigningCertificate = LoadCertificate(),
                Authority = "https://localhost:44397/identity",
                RequiredScopes = new[] { "custom-scope" }
            });

            app.Map("/identity", identityServerApp =>
            {
                identityServerApp.UseIdentityServer(GetIdentityServerOptions(LoadCertificate()));
            });

            HttpConfiguration httpConfiguration = new HttpConfiguration();

            WebApiConfig.Register(httpConfiguration);

            app.UseWebApi(httpConfiguration);
        }

        private X509Certificate2 LoadCertificate()
        {
            return new X509Certificate2(
            string.Format(@"{0}\bin\idsrv3test.pfx", AppDomain.CurrentDomain.BaseDirectory), "idsrv3test");
        }

public IdentityServerOptions GetIdentityServerOptions(X509Certificate2 signingCertificate)
        {
            var fabricaIdentityServer = new IdentityServerServiceFactory()
                .UseInMemoryClients(GetClients())
                .UseInMemoryScopes(GetScopes());

            fabricaIdentityServer.UserService = new Registration<IUserService>(resolver => new MyUserService());

            return new IdentityServerOptions
            {
                SiteName = "Your Site Name",
                RequireSsl = true,
                SigningCertificate = signingCertificate,
                IssuerUri = "https://localhost:44397/identity",
                Factory = fabricaIdentityServer,

                LoggingOptions = new LoggingOptions
                {
                    EnableHttpLogging = true,
                    EnableKatanaLogging = true,
                    EnableWebApiDiagnostics = true,
                    WebApiDiagnosticsIsVerbose = false
                }
            };
        }
    }

**Comment by penleychan** [comment]
@UlyssesAlves Yes it did help, thanks!

In case anyone else is having this issue, in order to get both Identity Server and WebApi running on the same host, you need the `IssuerName` **and** `SigningCertificate` on `IdentityServerBearerTokenAuthenticationOptions`.

Regards
