### ISSUE TITLE
SSO is not working properly in Ipad

### ISSUE THREAD

**Issue by tejashdesai** [IdentityServer/IdentityServer3#2070]
Hi 

I have implemented SSO for 3 application. I am facing an issue in IPAD. Application1 contains link on other two application. When the link is clicked user will redirect to application2 and its working perfectly. but when i select "Open in new tab" user always redirect to the STS login page. In desktop browser its working perfectly. Why SSO is not working in IPAD?

Thanks ,
Tejash Desai

**Comment by brockallen** [comment]
Not sure -- we've not ever heard of anything like this. You'll have to do more investigation.

**Comment by tejashdesai** [comment]
This is a default behavior. Safari browser do not support this feature due to some security reason.

**Comment by brockallen** [comment]
So it doesn't support cookies across tabs?

**Comment by leastprivilege** [comment]
progress?
