### ISSUE TITLE
Always require logout confirmation (even when id token hint was passed)

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#2071]

**Comment by brockallen** [comment]
A new config setting?

**Comment by leastprivilege** [comment]
yes

**Comment by brockallen** [comment]
I think having both a per-client and a global setting is confusing (especially since we already have a global `EnableSignOutPrompt`).

I am going to add a new `RequireSignOutPrompt` setting to `AuthenticationOptions` for now.

**Comment by brockallen** [comment]
Added a new `RequireSignOutPrompt` to `Client`.
