### ISSUE TITLE
Partial Login in ResourceOwner Flow

### ISSUE THREAD

**Issue by rezakhanmirzaee** [IdentityServer/IdentityServer3#2072]
I have a client app that is written with Silverlight. For some reasons we have to use "resource owner flow" but I can't find any sample or documentation about this subject. I have another client apps those are angular based and I implemented Partial Login with IdentityServer Samples.
My scenario is for some reason user must change password after he login in the Identity server. One way is Identity server authenticate user and send access_token to client but the client force user to change his or her password using a web api endpoint but I don't know is this a correct way or not.

**Comment by leastprivilege** [comment]
partial logins are only for web based flows.
