### ISSUE TITLE
Login / Logout hangs after site restart

### ISSUE THREAD

**Issue by JWiersema** [IdentityServer/IdentityServer3#2073]
We have the following setup:
1. WebAPi Project
2. MVC Site
3. IdentityServer site

The identity provider is Azure AD.
We get the following issue:
When the three sites are started everything works fine. However, when the MVC site gets stopped and started again, it indicates you are still logged in. When you then do a logout, you do not get redirected to Azure AD but you see the IdentityServer logout screen.
When you logout there, the page hangs. However, if you reload the site, it indicates you are logged out.
When you then try a login again, the page hangs aswell. Fiddler indicates that <identityserverurl>/identity/external does not give a response. The page keeps loading and there is never a error message or timeout.

Perhaps this is all because of an invalid accesstoken..? How do we get the identityserver site to work as expected without having to restart it each time the website or api gets restarted (e.g. due to a deployment). Let us know if this indicates a certain kind of bad configuration from our side.

**Comment by brockallen** [comment]
Sounds like the bug/issue in Katana where it deadlocks trying to access the metadata. Search the katana issue tracker for the problem. Not sure they have any fixes for it, though.

**Comment by JWiersema** [comment]
Seems to be solved by the newest version of Microsoft.IdentityModel.Extensions, v1.0.2.something
