### ISSUE TITLE
IdServer DPAPI DataProtect under webfarm scenario

### ISSUE THREAD

**Issue by danutzplusplus** [IdentityServer/IdentityServer3#2074]
Hello,

This is an issue I've encountered, and would like to ask for some further feedback, if it is already known, or if anyone has encountered it.

I noticed that IdServer V3 uses the DPAPI to protect the cookies it issues. And I've encountered issues with this while hosting the IdServer V3 on multiple webservers. Issues in that apparently random, although I'm sure it's not random, either one instance or the other of the farm logges errors that it fails to decrypt cookies it receives.

From what I've read DPAPI managed it's own encryption keys, and they can't be easily synchronized across multiple webservers (am I wrong here?), to allow requests to be forwarded to any of the nodes in the farm. 

Does this mean the IdServer can't be used, at least not without some custom dataprotection that uses the same key? Or was something like this implemented in a later version? I don't currently use the latest version of IdServer (and am planning on a future update to the latest version).

Is there a configuration guide on how you would use the idserver for this scenario?

Thanks and have a good one.

**Comment by leastprivilege** [comment]
did you read the docs?

https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

**Comment by danutzplusplus** [comment]
Oops. I guess I missed that. Thanks for the link, and sorry for the useless post.

**Comment by leastprivilege** [comment]
i just wrote it for you a couple of minutes ago ;)

jk - it's been there a while.
