### ISSUE TITLE
Application_PostAuthenticateRequest occurs before IdentityServer JWT Auth?

### ISSUE THREAD

**Issue by RobKraft** [IdentityServer/IdentityServer3#2076]
I am trying to modify the "Sample Web API" project in the "clients" solution to intercept the Auth and add additional custom roles as described here: http://brockallen.com/2013/01/17/adding-custom-roles-to-windows-roles-in-asp-net-using-claims/

I place code in Application_PostAuthenticateRequest, but Request.IsAuthenticated returns false.  The next breakpoint the code hits is in the IdentityController Get() method and at that point the ClaimsPrincipal Identity Is Authenticated.

Can someone point me in the correct direction to resolve this?  I am trying to alter the Principal on thread.currentprincipal before any of the controllers use it.

Thanks in advance for your time.

**Comment by leastprivilege** [comment]
In Katana you wouldn't do it like that. Use middleware.

e.g. https://github.com/IdentityModel/Owin.ClaimsTransformation
