### ISSUE TITLE
Passwords are bad, but where should we save the Client Credentials???

### ISSUE THREAD

**Issue by mzagel** [IdentityServer/IdentityServer3#2077]
Hi,

We are currently developing several Web APIs protected with tokens from the Id Svr. Furthermore we have some internal clients (MVC Frontend, Android App, iOS App), but also many external partners who will use our interfaces. Many of the API endpoints will also be available without a user beeing logged in (via hybrid flow). But we want to have at least a basic protection using pure client credential flow for these endpoints.

In either scenario, hybrid flow and pure client credential flow, we still need the client credentials to receive tokens. The only client we have, that can really be considered to be save, is our MVC frontend application, as the client secret can be saved on a server behind our firewall. But all other clients must be considered unsave. Even our own android and iOS apps will be prone to attacks. A hacker could decompile the code and read out the credentials. But especially our partners connections must be considerd unsave.

In an ideal world I would like to get rid of passowrds at all, in this case the client credentials. I know it sounds contradictionary, we want to protect our interface at least with client credentials, but without using client credentials:-)

Is there any best practice on how to handle the credentials especially for unsave clients?

Thanks a lot for yur help.

Ciao,
Michael

**Comment by leastprivilege** [comment]
Client credentials shouldn't go on a device - or you can't treat them as confidential.

Client credentials flow is designed for machine to machine communication where the caller can save the credential in a secure manner.

**Comment by mzagel** [comment]
Yes, I see the problem, but I really don't have an idea how to solve it.

Example: For our MVC client , we need the client credentials to receive the access/refresh token (according to the sample "MVC OWIN Client (Hybrid)"):
```
Notifications = new OpenIdConnectAuthenticationNotifications
{
	AuthorizationCodeReceived = async notif =>
	{
		var claims = new List<Claim>(notif.AuthenticationTicket.Identity.Claims);

		var userInfoClient = new UserInfoClient(
			new Uri(Constants.UserInfoEndpoint),
			notif.ProtocolMessage.AccessToken);

		var userInfo = await userInfoClient.GetAsync();
		userInfo.Claims.ToList().ForEach(ui => claims.Add(new Claim(ui.Item1, ui.Item2)));

		// get access and refresh token
		var tokenClient = new OAuth2Client(
			new Uri(Constants.TokenEndpoint),
			"123456",
			"secret");

		var response = await tokenClient.RequestAuthorizationCodeAsync(notif.Code, notif.RedirectUri);

		claims.Add(new Claim("access_token", response.AccessToken));
		claims.Add(new Claim("expires_at", DateTime.Now.AddSeconds(response.ExpiresIn).ToLocalTime().ToString()));
		claims.Add(new Claim("id_token", notif.ProtocolMessage.IdToken));

		var claimsIdentity = new ClaimsIdentity(claims.Distinct(new ClaimComparer()), notif.AuthenticationTicket.Identity.AuthenticationType);
		notif.AuthenticationTicket = new AuthenticationTicket(claimsIdentity, notif.AuthenticationTicket.Properties);
	},
}
```
And for the use case, when a real user is not logged in yet, we currently request a token using the client credential flow:

```
var client = new OAuth2Client(
	new Uri(Constants.TokenEndpoint),
	"123456",
	"secret");

var token client.RequestClientCredentialsAsync("someApi").Result;
```
So that's maybe OK for our MVC application, but what should we do with our native apps or with our partners?

Is there a flow, that's more suitable?

**Comment by leastprivilege** [comment]
If you want to use a flow for native apps that requires client credentials - make sure those client can only request the minimum scopes needed for their work. Don't allow a flow where client credentials only are allowed. Also don't treat those secrets are secret.

Partners must be considered trustworthy. Again least privilege configuration is always recommended.

**Comment by mzagel** [comment]
Of course, client credentials only requests will be restricted to our basic functionality. 

So obviously there is no way to avoid saving the client credentials as long as we need to allow users to access certain endpoints without beeing logged in.

I've seen an implicit flow sample without using any client credentials. But then we will have to force the user to log in from the beginning. Maybe still a possible solution for our Android and iOS app.

There are some good articles on how flows work in general, but still it's very complex and hard to figure out which flow works best for which use case.
So, do you know any web site for OAuth/OpenID flows best practices?
It would be really helpful to have a howto-guide for certain scenarios like "for this use case it's best to implement that flow...".

**Comment by leastprivilege** [comment]
progress?

**Comment by mzagel** [comment]
Well, currently I don't see any other solution then taking client credential flow for the common functionality of our interface.

As I mentioned above: It would be great to have a howto/best practices guide for OAuth/OpenID flows. There are dozens of articles describing the flows, but can be hard to figure out the right flow for certain szenarios.
