### ISSUE TITLE
SessionId

### ISSUE THREAD

**Issue by eaba** [IdentityServer/IdentityServer3#2080]
Good day, once again!
I am trying to achieve a little thing: Access the SessionId of the "Authorize request validation success" for the current user and store it as a claim!!

Thanks

**Comment by leastprivilege** [comment]
The session id gets sent back to your client via the authorization response. From there you can store it in whatever way you want - e.g. as a claim.

**Comment by eaba** [comment]
How to access sessionId at the client is my challenge. Please how do i go about doing this at the client?
I need a guide. 
Thanks

**Comment by eaba** [comment]
Can this be taken for Session Id?: AuthenticationTicket.Properties.Dictionary[".sessionState"]

**Comment by leastprivilege** [comment]
Depends what you are planning to do with it.

The next release (2.2) will include an sid (session id) claim.

to be released soon.

**Comment by eaba** [comment]
I am planning to use if for Auditing, I was getting new SessionId for every request when i used HttpContext Session Id of MVC 5.

Can I ask for a feature?
Can you add a switch to turn on or off Multiple Sessions Per User,
For future projects, this will be useful for me.

Thanks

**Comment by leastprivilege** [comment]
I don't follow - please open a new issue for a feature request.
