### ISSUE TITLE
Page hangs on 'submit this form': /identity/connect/authorize

### ISSUE THREAD

**Issue by JWiersema** [IdentityServer/IdentityServer3#2081]
We have an issue with IdentityServer3 when coming back from the successful login at the identity provider, which is Azure AD.
When you get redirected back to <identityserverurl>/identity/connect/authorize the page keeps getting reloaded with a different token. Hundreds of requests get sent to the page in the mvc site for which you need to be authorized, giving a unauthorized exception.
After quite while you do get to the page successfully. How do we get the redirect to work in one go?

Thanks in advance!

**Comment by brockallen** [comment]
Something doesn't sound right. You'll need to do some more tracing/debugging to figure it out.

**Comment by JWiersema** [comment]
Thanks for your fast reply. The issue was because of mixing http client with https identityserver, doh!
This thread led to finding the issue: https://github.com/IdentityServer/IdentityServer3/issues/294

**Comment by brockallen** [comment]
Glad to hear you sorted it out.
