### ISSUE TITLE
Decouple Identity Server and Resource Server

### ISSUE THREAD

**Issue by dunglp** [IdentityServer/IdentityServer3#2082]
Hi all,

I am new with IdentityServer3. Could you please help me with this ? 
I was following this sample : https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html

I want to publish IdentityServer to one server and WebAPI to another server. Both have https enabled. Is that possible ? 

I can successfully publish IdentityServer. However, when I tried with WebAPI project. I got this message : "the remote certificate is invalid according to the validation procedure". 

Should I load SSL certificate to WebAPI project ? If yes, how can I do this ?
Any help would be much appreciated

**Comment by S3KCentrifugal** [comment]
I'm still relatively new to this as well, but I will try to help. 

The SSL certificate and the signing certificate are different (although they can be the same I think). The  SSL certificate is used for encrypting the transport of data, usually gets installed in IIS or the Firewall.

The signing certificate is for signing messages, it gets discovered by the resource server on startup. I'm assuming it is just used to verify messages as originating from the identity server to prevent spoofing. I'm using reference tokens though, I don't know if the signing certificate even gets used in my case. Someone can correct me if this isn't the case.

I generated my own self signed certificate, I believe using makecert. I figure if the certificate is only for signing then a trusted root authority isn't necessary, so why spend a ton of money for a verisign signing cert. Plus I can recreate new ones as often as I want.
