### ISSUE TITLE
Custom Authentication Workflow

### ISSUE THREAD

**Issue by bloudraak** [IdentityServer/IdentityServer3#2083]
I have a custom working workflow where the first step is for the user to specify their email address or username.  In the case of a username, local authentication is used. If its an email address, the domain will determine which authentication provider to use. If the domain is unrecognized, then  local authentication is used.  When local authentication is used, the next step is to request the password (amongst other things).  Once the password was successfully accepted the user is signed in. The process (whether its local or external) will have additional steps (like two factor authentication and EULA). 

When the user enters a username (e.g. "bob"), how do I ensure that the login screen already has "bob" and that it is non editable.  I'm looking at the view service example and don't see a way to pass the username along. 

Any suggestions?

**Comment by brockallen** [comment]
IIRC, the LoginViewModel has a property for pre-populating the username. This is how we do the "remember my username" feature.
