### ISSUE TITLE
Permissions web page: If no logoUri is specified, the frame for the logoUri is still displayed

### ISSUE THREAD

**Issue by jeanmaz** [IdentityServer/IdentityServer3#2084]
I noticed that when a client has no logoUri defined, the frame containing the picture frame is still displayed in the permissions web page (Internet Explorer and Chrome). Could the frame be removed if no picture URL is defined ?

![clientpictureframe ie](https://cloud.githubusercontent.com/assets/14196372/10783234/71a8478e-7d56-11e5-8b59-e601374dee2a.JPG)

**Comment by brockallen** [comment]
Fixed on dev.
