### ISSUE TITLE
How can I allow resource server to specific domain?

### ISSUE THREAD

**Issue by Jenanek** [IdentityServer/IdentityServer3#2086]
Hi,

I've found this sample: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/SampleAspNetWebApi 

I can specify the required scopes for access to API.

How can I specify access only for specific domain?

I want to create this flow:
I have a web site where I get an access token and scope for acess to API and I want to rescrict acess to API. I want to deny access from other domains.

How can I do this?

Thank you.
J.

**Comment by leastprivilege** [comment]
sorry - I don't follow.
