### ISSUE TITLE
Client and Server on the same application?

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#2087]
Is it possible that the client and server can be on the same server. I mean if I try,

 app.UseIdentityServer(options);
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
.......................................................
            });

I will get `Unable to get document from: http://...../.well-known/openid-configuration` exception. Means I will be unable to run the application. Because of this

**Comment by leastprivilege** [comment]
check the archives  -this has been answered before.

**Comment by abcplex** [comment]
@leastprivilege at least share the link :)
