### ISSUE TITLE
Login page cycles and not authenticating

### ISSUE THREAD

**Issue by mmihaylov** [IdentityServer/IdentityServer3#2091]
Hello, 

we are using IdentityServer3 and from time to time we get some interruptions in its work. We are using load balanced environment. What happens is when the user click on the Login buton, page submits and shows again. You basically cannot authenticate. The solution I found is to recycle the app pool, but this is a temp fix. 

It is hosted in IIS. We have an mvc app accessed at https://www.mydomain.wtst. I have created a sub application called IdentityServer3. With all this the URI for the IdSrv becomes 
https://www.mydomain.wtst/IdentityServer3/core .I have machine keys synced in the IdSrv sub applications. 

1. Do I have to set IssuerUri and PublicOrigin properties? What should be their values?
2. Another thing that observed is that after deployment of the root mvc application, sometimes I need to recylce the AppPool of the IdSrv. Is it possible the deployment of the root mvc app, to break the authentication workflow?

**Comment by brockallen** [comment]
And you have the machineKey element properly configured across the farm?

**Comment by mmihaylov** [comment]
Hello, 

we have 2 nodes, and for the IdSrv sub application for each of them is set 
<machineKey validationKey="3B141AC7F437AB5EDD54F24E1D2B96DD2E0552D2354D154C4503C179B5B2C09C160C9B8BB35243269FE51D2A3D192D1C8F72281E05DDFC50A42405ADC1058244" decryptionKey="26908ED5DDF31C5A46C6525FAF83D0927932ADE4356B81F7" validation="SHA1" />

Do I miss something else?

**Comment by brockallen** [comment]
Well, now that you have told everyone the keys, at some point you should change them so we can't forge cookies and other sensitive values for your app.

**Comment by brockallen** [comment]
Check the docs for the uses of those config values: https://identityserver.github.io/Documentation/docsv2/configuration/identityServerOptions.html

As for the issue, not sure. You'll need to do some more debugging.

You say you need to recycle -- perhaps that's related to the katana deadlock bug. Maybe try making them siblings, not parent/child in IIS.

**Comment by mmihaylov** [comment]
Hi, 
that's the test environment. It is not public and I can easily change it. Thanks for the suggestion. I will try that.

**Comment by brockallen** [comment]
Ok, keep us posted.

**Comment by mmihaylov** [comment]
Hello, 

so this issue happens quite randomly. I open the login page, enter my credentials, submit and then I get again the login page. The only solution I have found so far is to recycle the app pool, but this is not a solution. 

Since we are using load balancer I have set the following properties to IdentityServer app. 

RequireSsl = false
IssuerUri = https://www.mydomain.wtst/IdentityServer3/core
PublicOrigin = https://www.mydomain.wtst/

This is the fiddler log I have saved: https://drive.google.com/file/d/0B1NNodXQjif0cGg0ZHY5cm9ZeEk/view

**Comment by mmihaylov** [comment]
Hello, I did another tests today and what I found in the logs is:

1. After login page is submitted the flow breaks after the step - "Authorize request validation success." After that message I get "User is not authenticated. Redirecting to login." and again I am redirected to the login page. 

2. I performed the same login steps on our DEV environment, which is single server, not load balanced. After the "Authorize request validation success" I get some details about my request, such as  client details, redirect Uri, Response mode, Flow, State, Nonce etc. Comparing this to the information in the log file from TEST environment (which breaks), I noticed that on TEST 
 - `"SubjectId" is set to "unknown"`
 - `"SessionId"` is missing

Do you think this could be the reason for the problem? And why are these values not set?

**Comment by brockallen** [comment]
Those values are all coming from various cookies we set. So it sounds like you need to focus on why those cookies don't travel to the next page, or if they are why are they not validated/consumed.

**Comment by mmihaylov** [comment]
I read about a Katana bug, that OWIN cookies, are being deleted, because of the way System.Web treats cookies. There is a proposed solution to use KentorOwinCookieSaver. Do you think this might be the reason for this?

**Comment by brockallen** [comment]
The Katana bug comes up with you have both katana code adding cookies via OWIN, and your code adding cookies via System.Web/HttpContext -- does that describe your situation?

**Comment by mmihaylov** [comment]
Well I do use System.Web/HttpContext for setting cookies in several places of the application. 
Apart from that, I am using Microsoft.Owin.Security.OpenIdConnect and as far as I know, this Katana middleware is setting the authentication cookie. So I guess my situation is as you have described it.

**Comment by brockallen** [comment]
So try the Kentor fix. I also heard that setting a dummy variable in session in Session_Start also fixes it.

**Comment by mmihaylov** [comment]
I have already added it, but without this dummy variable. Will try it out now and see if it makes the trick.

**Comment by leastprivilege** [comment]
progress?

**Comment by mmihaylov** [comment]
Hello, unfortunately the issue still exists. It's on our production website, so it's really serious for us. let me try to provide as much as possible details: 

IS Configuration - Startup file

`app.Map(`
`"/core",`

`coreApp =>`
`{`
	`var factory = new IdentityServerServiceFactory();`
	
	var efConfig = new EntityFrameworkServiceOptions
	{
		ConnectionString = "IdSvr3Config"
	};
	
	factory.RegisterConfigurationServices(efConfig);
	factory.RegisterOperationalServices(efConfig)
	
	var cleanup = new TokenCleanup(efConfig, 30);
	cleanup.Start();                    
	
	var viewOptions = new DefaultViewServiceOptions();
	viewOptions.CacheViews = false;
	factory.ConfigureDefaultViewService(viewOptions);

	factory.CorsPolicyService = new Registration<ICorsPolicyService>(new DefaultCorsPolicyService { AllowAll = true });
	factory.UserService = new Registration<IUserService, SalesforceUserService>();

	var cookieOptions = new CookieOptions
	{
		//Set to 10 hours
		ExpireTimeSpan = TimeSpan.FromHours(int.Parse(ConfigurationManager.AppSettings["ExpireTimeSpanInHours"])),
		//Set to true
		IsPersistent = bool.Parse(ConfigurationManager.AppSettings["IsPersistent"].ToString()),
		//Set to false
		SlidingExpiration = bool.Parse(ConfigurationManager.AppSettings["SlidingExpiration"].ToString()),
		//Set to false
		AllowRememberMe = bool.Parse(ConfigurationManager.AppSettings["AllowRememberMe"].ToString()),
		//Set to 10 hours, althoug not used in case allowremmeberme is false
		RememberMeDuration = TimeSpan.FromHours(int.Parse(ConfigurationManager.AppSettings["RememberMeDurationInHours"])),
		SecureMode = CookieSecureMode.Always
	};

	var authenticationOptions = new AuthenticationOptions
	{
		LoginPageLinks = new[] 
		{
			new LoginPageLink
			{
				Text = "Create one now.",                                
				Href = ConfigurationManager.AppSettings["CreateProfileLink"].ToString()
			},
			new LoginPageLink
			{
				Text = "Forgot your password?",
				Href = ConfigurationManager.AppSettings["ForgottenPasswordLink"].ToString()
			}
		},

		CookieOptions = cookieOptions,
		EnableSignOutPrompt = false, 
		EnablePostSignOutAutoRedirect = true,
		SignInMessageThreshold = 0,
		InvalidSignInRedirectUrl = ConfigurationManager.AppSettings["InvalidSignInRedirectUrl"].ToString()
	};
	
	var loggingOptions = new LoggingOptions
	{
		//Set to false
		EnableWebApiDiagnostics = bool.Parse(ConfigurationManager.AppSettings["EnableWebApiDiagnostics"]),
		//Set to false
		WebApiDiagnosticsIsVerbose = bool.Parse(ConfigurationManager.AppSettings["WebApiDiagnosticsIsVerbose"]), 
		//Set to false
		EnableKatanaLogging = bool.Parse(ConfigurationManager.AppSettings["EnableKatanaLogging"]), 
		//Set to false
		EnableHttpLogging = bool.Parse(ConfigurationManager.AppSettings["EnableHttpLogging"]) 
	};

	var eventsOptions = new EventsOptions
	{
		//Set to false
		RaiseErrorEvents = bool.Parse(ConfigurationManager.AppSettings["RaiseErrorEvents"]),
		//Set to false
		RaiseFailureEvents = bool.Parse(ConfigurationManager.AppSettings["RaiseFailureEvents"]),
		//Set to false
		RaiseInformationEvents = bool.Parse(ConfigurationManager.AppSettings["RaiseInformationEvents"]),
		//Set to false
		RaiseSuccessEvents = bool.Parse(ConfigurationManager.AppSettings["RaiseSuccessEvents"]),
	};

	var cspOptions = new CspOptions
	{
		Enabled = true,
		StyleSrc = "'self' fonts.googleapis.com",
		FontSrc = "'self' fonts.gstatic.com fonts.googleapis.com",
		ScriptSrc = "'unsafe-inline'"
	};
	
	var options = new IdentityServerOptions
	{                        
		SiteName = ConfigurationManager.AppSettings["SiteName"],
		SigningCertificate = CertificateHelper.LoadCertificate(ConfigurationManager.AppSettings["SigningCertificateThumbprint"].ToString()),
		RequireSsl = bool.Parse(ConfigurationManager.AppSettings["RequireSsl"]),//Set to true
		Factory = factory,
		AuthenticationOptions = authenticationOptions,
		CspOptions = cspOptions,                        
		LoggingOptions = loggingOptions,
		EventsOptions = eventsOptions,
		EnableWelcomePage = false                        
	};

	//Public Origin - not set	
	
	//Issuer Uri set to https://www.mydomain.com/IdentityServer3/core
	var issuerUri = ConfigurationManager.AppSettings["IssuerUri"];
	if (!String.IsNullOrEmpty(issuerUri))
	{
		options.IssuerUri = issuerUri.ToString();
	}

	coreApp.UseIdentityServer(options);
`});`

**Comment by mmihaylov** [comment]
The website, is register as a client, using hybrid flow. id_token and access_token lifetimes are set to 10 hours. 

Here is the website setup in Startup file

`public void Configuration(IAppBuilder app)`
`{`
	`AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";`
	`JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();`
	
	app.UseKentorOwinCookieSaver();

	app.UseCookieAuthentication(new CookieAuthenticationOptions
	{
		AuthenticationType = "Cookies"
	});

	app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
	{
		ClientId = Startup.ClientId,
		//Set to "https://www.mydomain.com/IdentityServer3/core"
		Authority = Startup.IdSrvBaseUri,
		RedirectUri = Startup.RedirectUri,
		PostLogoutRedirectUri = Startup.PostLogoutUri,
		ResponseType = "code id_token token",        
		Scope = "openid profile email roles services",
		SignInAsAuthenticationType = "Cookies",
		UseTokenLifetime = true,
		Notifications = new OpenIdConnectAuthenticationNotifications
		{			
			AuthorizationCodeReceived = async n =>
			{
				var identity = n.AuthenticationTicket.Identity;
				var newIdentity = new ClaimsIdentity(identity.AuthenticationType, "name", "role");
				
				var userInfoClient = new UserInfoClient(new Uri(Startup.IdSrvUserInfoEndpoint), n.ProtocolMessage.AccessToken);
				var userInfo = await userInfoClient.GetAsync();
				userInfo.Claims.ToList().ForEach(c => newIdentity.AddClaim(new Claim(c.Item1, c.Item2)));

				newIdentity.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
				//Add access token/expires_at for the WCF Services
				newIdentity.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));
				newIdentity.AddClaim(new Claim("expires_at", DateTime.UtcNow.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToLocalTime().ToString(CultureInfo.InvariantCulture)));
				n.AuthenticationTicket = new AuthenticationTicket(newIdentity, n.AuthenticationTicket.Properties);
			},

			RedirectToIdentityProvider = async n =>
			{
				if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
				{
					var idToken = n.OwinContext.Authentication.User.FindFirst("id_token");
					if (idToken != null)
					{
						n.ProtocolMessage.IdTokenHint = idToken.Value;
					}
				}				
			}
		}
	});
}`

Following the suggestions for the katana bug, related to lost cookies, I have also added in Global.asax

` protected void Session_Start(object sender, EventArgs args)
{
	//There is a Katana bug, not keeping Cookies
	//http://stackoverflow.com/questions/20737578/asp-net-sessionid-owin-cookies-do-not-send-to-browser
	Session["Dummy"] = "SomeValue";
}`

Not really sure, if the reason is because of some inactivity of the users, because the issue happened twice on sunday. When they press login, they are retrieved sucessfully. After that I see 
`Authorize request validation success`, 
but
`"SubjectId": "unknown"` and `"SessionId"` is missing. And it starts all over again with the login page.

**Comment by mmihaylov** [comment]
Hi, 
I think I have another trace of this. After user clicks on Login, user is found and verified. Then the flow return 302 with location pointing to https://www.mywebsite.com/IdentityServer3/core/connect/authorize?client_id=... It also sends several cookies:
1. SignInMessage.03c08432a0c4c9af29045bb551e76aa0 - this one is invalidated
2. idsvr.session - this one is for the session identifier with Identity Server
3. idsrv.partial and  idsrv.external - empty, they are not used in this scenario
4. idsrv cookie. HOWEVER, I noticed that the path for it is set to path=/identityserver3/core

The following request is the actual GET of authorize. This request is to https://www.mywebsite.com/IdentityServer3/core/connect/authorize. But idsrv cookie has its path lowercase and that's why it is not send and that's why user is not authenticated and gets again the login page. 

Any idea why this happens?

**Comment by brockallen** [comment]
Ah, that's good info. So yes, URL and cookie paths are case sensitive. Perhaps the initial URL used to send the user to IdSvr has a casing typo in it (comapred to how the host is configured)? If your IdSvr being hosted in IIS?

**Comment by mmihaylov** [comment]
Yes, everything is in IIS. We have a main application, which is an MVC app. Then I have a sub application which is the IdSrv. The name of this sub application is "IdentityServer3". I have set IssuerUri  to "https://www.mywebsite.com/IdentityServer3/core". 

Also, have a look again at all of the headers, from the response above:
`Set-Cookie: SignInMessage.XXXXXXXXXXXX=.; path=/IdentityServer3/core; expires=Mon, 24-Nov-2014 11:52:44 GMT; secure; HttpOnly`

`Set-Cookie: idsvr.session=XXXXXXXXXXXX; path=/IdentityServer3/core; secure`

`Set-Cookie: idsrv.partial=; path=/identityserver3/core; expires=Thu, 01-Jan-1970 00:00:00 GMT`

`Set-Cookie: idsrv.external=; path=/identityserver3/core; expires=Thu, 01-Jan-1970 00:00:00 GMT`

`Set-Cookie: idsrv=XXXXXXXXXXXX; path=/identityserver3/core; secure; HttpOnly`

Some of them are with lowercase and some not.

**Comment by brockallen** [comment]
When those cookies are issued the paths are always drawn from the current HTTP request into IdSvr. So if the current request has  a lower case "i" (for example when returning from an external IdP) then that's the path that will be used. 

My guess is that any URLs into IdSvr you have configured elsewhere (in the client and/or in external IdPs) have mixed casing and that's causing some of these problems.

**Comment by mmihaylov** [comment]
I have checked everything that I am aware of and couldn't find anything. But, when I navigate to 
https://www.mywebsite.com/identityserver3/core/.well-known/openid-configuration

I get the following

`"issuer": "https://www.mywebsite.com/IdentityServer3/core",
"jwks_uri": "https://www.mywebsite.com/identityserver3/core/.well-known/jwks",
"authorization_endpoint": "https://www.mywebsite.com/identityserver3/core/connect/authorize",
"token_endpoint": "https://www.mywebsite.com/identityserver3/core/connect/token",
"userinfo_endpoint": "https://www.mywebsite.com/identityserver3/core/connect/userinfo",
"end_session_endpoint": "https://www.mywebsite.com/identityserver3/core/connect/endsession",
"check_session_iframe": "https://www.mywebsite.com/identityserver3/core/connect/checksession",
"revocation_endpoint": "https://www.mywebsite.com/identityserver3/core/connect/revocation"`

Again mixture of capital case and lower case. Might this be a caching issue? 
The only solution I can think of is to set explicitly everywhere (SubApplication name and all URLs) to
/identityserver3/core - only with small letters.

**Comment by brockallen** [comment]
Not sure -- let me run some tests here locally to see if I can repro the mixed casing. I won't get to it until later today.

**Comment by leastprivilege** [comment]
Delete the vdir and recreate it all lowercase. Iis ftw

**Comment by mmihaylov** [comment]
Hello Dominic, Brock, 

I have done this and will continue monitoring the systems. 
- I have recreated the virtual directory to a lowercase only
- I have changed issuer URI to lowercase as well. 
- I have updated all the clients, in order to use lowercase URL as well, when accessing IdSrv

Will let you know, if I have any updates. 
Thank you for your time and help.

**Comment by mmihaylov** [comment]
It is pretty weird, I still get plenty of errors like these

`Exception accessing: /identityserver3/core/login`
`Exception accessing: /IdentityServer3/core/login`

Even though after all these updates, there are still some request going to the uppercase one. Strange!

**Comment by brockallen** [comment]
So that incorrect casing must be coming a URL configured in some external source (either the client or in the external Idp).

**Comment by mmihaylov** [comment]
Today we had the issue again. I am thinking of creating a completely new setup 
- sub application / virtual directory name
- clients setup URIs. 

I will not use neither IdentityServer3 nor identityserver3 name but totally new - for example "is3". 

Since the path property is coming from the request, does it mean that something like this happened:
1. Starts authentication/authorization process, and the request is "/IdnetityServer3/core..."
2. Somewhere in the middle of the process a request has comes for "/idnetityserver3/core...". Is it possible this request to be from another client?
3. The last 3 cookies "get affected" by this request and have their path property set to lowercase.

**Comment by Andiego** [comment]
Hi Martin,
If you want connect with Identity Server with "RequireSsl = false", you shouldn't set "SecureMode = CookieSecureMode.Always". I had the same problem and I forgot to remove line with this (remove becaouse default value is SameAsRequest). You can read more about that on https://www.owasp.org/index.php/SecureFlag. I hope this solution will help you.

**Comment by mmihaylov** [comment]
Hi, thanks for this suggestions. I am on holiday now, but next week will try it out.

**Comment by leastprivilege** [comment]
feel free to re-open if still an issue:

**Comment by mmihaylov** [comment]
Hello, the issue does not exist anymore. At least the cycling of the login page and the need to reset the IIS. It all works fine now. I renamed the Virt Dir and other URL settings all to lowercase - identityserver3. 

However, I still get lots of errors - Error accessing /identityserver3/core/login. Since this is not breaking the functionality of the website, I think we can live with it. Thanks a lot for the help. I hope I will not reopen the issue :)
