### ISSUE TITLE
Get ClientUri in AuthenticateLocalAsync

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2092]
I try to override ```AuthenticateLocalAsync``` method and need to get ClientUri  from context (SignInMessage) because i have multiple clients with same ClientId and i need to filter this clients.
how i do this?

**Comment by brockallen** [comment]
Inject the client store into your user service's ctor and then look it up from the sign in message passed to authenticate local.

**Comment by totpero** [comment]
ok, good tx.
