### ISSUE TITLE
External provider refresh token: best practice question

### ISSUE THREAD

**Issue by CrescentFresh** [IdentityServer/IdentityServer3#2093]
I've an external provider configured in IdentityServer3 and they are giving idsvr a refresh token.

Now I would like my client application (which only knows about idsvr) to be able to get a new access token. Presuming I have both the refresh token from idsvr and the refresh token from the provider (embedded as a claim): how should my client request a token from idsvr such that idsvr in turn forwards to the external provider's `/token` endpoint?

Is that even a thing?

**Comment by brockallen** [comment]
Al you're using the external provider for is authentication. Once that's done then do you even need anything else from them? The refresh token is for getting new access tokens to call APIs, which also is unrelated to the process of authenticating to IdSvr. 

So I guess the point is -- I'd not think that you need the refresh token. Do you?

**Comment by CrescentFresh** [comment]
You know you are totally right, I missed that.

I was thinking idsvr is acting as a proxy to the provider, so if they support expiring tokens and refresh tokens idsvr should honor those.

Closing...
