### ISSUE TITLE
Authenticated User Registration

### ISSUE THREAD

**Issue by narciero** [IdentityServer/IdentityServer3#2094]
I have a new user signup link on my IdentityServer login page and that brings the user to a registration sequence within the same web app (asp.net mvc) that IdentityServer is hosted. The first step creates an account but I want to ensure to user is logged in/authenticated for the remaining steps of registration as they will be purchasing a subscription and obviously I want to make sure that purchase gets tied to their account. Right now I am storing the SignInMessage as a cookie and then use IssueLoginCookie. Would best practice be to redirect to a different site to complete registration (and have that site use OpenID connect) or should I register openid connect middleware right after I register IdentityServer (app.UseIdentityServer) so that within the same application I can use tokens from idsrv.

**Comment by brockallen** [comment]
If your registration is hosted in the host as IdSvr then it can share cookies. If you want it separate then it'd best to be a separate host/app. Either way works -- just depends on your architecture.

**Comment by babersaeed** [comment]
hmm

**Comment by narciero** [comment]
so after i register identityserver (app.UseIdentityServer)  I have  app.UseCookieAuthentication...will this be sufficient for sharing cookies?

**Comment by brockallen** [comment]
If you registration is in the same pipeline (meaning under the same path as IdSvr) then the cookie middleware is already there (in front).

**Comment by narciero** [comment]
ok, what attribute would I decorate a controller with then to ensure all of its actions require an authenticated user? [Authorize] is giving a 401. My idsrv path is the empty string (so login page lives at www.myurl.com/login?sigin=123 ) and registration is at www.myurl.com/Register

**Comment by brockallen** [comment]
You'd not do it that way. You'd use the OWIN environment extensions we have to let you know who the IdentityServer user is: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinEnvironmentExtensions.cs#L435

**Comment by narciero** [comment]
ok I see, so Id need a custom auth filter then that would perform an identity checkk using the owin extensions

**Comment by brockallen** [comment]
Yep. I think we have some sample code here that might help: https://github.com/IdentityServer/IdentityServer3.Extensions.Mvc

**Comment by narciero** [comment]
ah exactly what i was looking for, thank you!

**Comment by woodwardmatt** [comment]
@narciero I have this same query at the moment, but for simply securing an mvc controller hosted within the same pipeline as IdSrv. I'm trying to get my head around the implementation you guys are discussing above, but am a little lost. Can you share any advice on how you got it to work?

**Comment by narciero** [comment]
You will want to decorate your controller with the IdsrvFullLoginAttribute

**Comment by narciero** [comment]
That will check all incoming requests and redirect to your idsrv login page if needed (401)

**Comment by woodwardmatt** [comment]
Thanks @narciero I'll give that a blast! :) Thanks soo much for responding soo quick :)

**Comment by woodwardmatt** [comment]
Implemented and all working, thanks @narciero - For anyone else that comes across the thread, here's what I did:

- Copied the filters & infrastructure classes from https://github.com/IdentityServer/IdentityServer3.Extensions.Mvc/tree/master/source/IdentityServer3.Extensions.Mvc/IdentityServer3.Extensions.Mvc into my IdSrv project (Not sure if a nuget package is planned (or appropriate?) for these at some point - one for @brockallen maybe to answer?)

- Then on my controller I included the following decorations:

        [Authorize]
        [IdentityServerFullLoginAttribute]
        public ActionResult Index(){}

After that an unauthenticated visit for the controller prompted an authentication challenge with a redirect back to the controller once authenticated.

Job done!
