### ISSUE TITLE
LoggedOut page rendered with PostSignOutAutoRedirect enabled

### ISSUE THREAD

**Issue by tracsorenson** [IdentityServer/IdentityServer3#2097]
I have the following AuthenticationOptions set on IDSRV:
                AuthenticationOptions = new AuthenticationOptions
                {
                    EnableLocalLogin = true,
                    EnableLoginHint = true,
                    RememberLastUsername = true,
                    EnableSignOutPrompt = false,
                    EnablePostSignOutAutoRedirect = true,
                }

but the LoggedOut view is always rendered and the Model.RedirectUrl is correct and clicking does take me back to the client application.  I am using the MVC ViewService sample to display these views.
All the other options are working correctly, I am just not auto redirected back to the client.
Am I missing something..?

**Comment by brockallen** [comment]
I'd start by debugging the JS on the page.

**Comment by tracsorenson** [comment]
Thanks @brockallen!  I am using new versions of bootstrap, jquery, and angular, but added the app.js and encoder.js and render them on the LoggedOut.cshtml...and magic happened :)  auto-redirect back to my client.  Nice. Thanks again.
