### ISSUE TITLE
Invalid Account Error with IdentityServer3 and WS-Federation 

### ISSUE THREAD

**Issue by bloudraak** [IdentityServer/IdentityServer3#2098]
I implemented an authorization server using IdentityServer3 2.1.1 that asks a user for an email address and based on the domain, select an external provider.  This is implemented using a custom user service. If the domain isn't recognized, then the local logs are used.  For local logins this works fine.  However, when I use an email address that triggers external authentication, an error "Error: Invalid Account" is displayed after successfully signing into an ADFS server.

The external sign in works perfectly fine without the custom user service. 

The logs look as follows:

    iisexpress.exe Information: 0 : 2015-10-29 15:12:44.483 -07:00 [Information] Callback invoked from external identity provider
    iisexpress.exe Information: 0 : 2015-10-29 15:12:44.551 -07:00 [Information] external user provider: "94f924d6de9e46d9922004eeaff9ce54", provider ID: "bob@example.com"
    iisexpress.exe Warning: 0 : 2015-10-29 15:12:44.590 -07:00 [Warning] user service failed to authenticate external identity
    iisexpress.exe Information: 0 : 2015-10-29 15:12:44.633 -07:00 [Information] rendering login page with error message: "Invalid Account"

Its unclear why I'll see a warning "user service failed to authenticate external identity". 

The Startup class looks as follows:

    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Trace()
                .CreateLogger();
               app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            app.UseCookieAuthentication(new CookieAuthenticationOptions());

            app.Map("", idsrvApp =>
            {
                var factory = new IdentityServerServiceFactory()
                    .UseInMemoryUsers(Users.Get())
                    .UseInMemoryClients(Clients.Get())
                    .UseInMemoryScopes(Scopes.Get());

                factory.CorsPolicyService = new Registration<ICorsPolicyService>(new DefaultCorsPolicyService { AllowAll = true });
                factory.Register(new Registration<HttpContext>(resolver => HttpContext.Current));
                factory.Register(new Registration<HttpContextBase>(resolver => new HttpContextWrapper(resolver.Resolve<HttpContext>())));
                factory.Register(new Registration<HttpRequestBase>(resolver => resolver.Resolve<HttpContextBase>().Request));
                factory.Register(new Registration<HttpResponseBase>(resolver => resolver.Resolve<HttpContextBase>().Response));
                factory.Register(new Registration<HttpServerUtilityBase>(resolver => resolver.Resolve<HttpContextBase>().Server));
                factory.Register(new Registration<HttpSessionStateBase>(resolver => resolver.Resolve<HttpContextBase>().Session));

                factory.UserService = new Registration<IUserService, AuthenticationService>();

                var options = new IdentityServerOptions
                {
                    SigningCertificate = new X509Certificate2(Resources.Certificate, "idsrv3test"),
                    Factory = factory,
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        IdentityProviders = ConfigureIdentityProviders
                    },
                };
                idsrvApp.UseIdentityServer(options);
            });
        }

        private void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var realm = ConfigurationManager.AppSettings["ida:Wtrealm"];
            var adfsMetadata = ConfigurationManager.AppSettings["ida:ADFSMetadata"];
            var adfs = new WsFederationAuthenticationOptions
            {
                AuthenticationType = "94f924d6de9e46d9922004eeaff9ce54",
                Caption = "Sample",
                SignInAsAuthenticationType = signInAsType,
                MetadataAddress = adfsMetadata,
                Wtrealm = realm,
            };

            adfs.Notifications = new WsFederationAuthenticationNotifications
            {
                SecurityTokenValidated = n =>
                {
                    var filter = new NormalizingClaimsFilter();
                    var incomingClaimsFromAdfs = n.AuthenticationTicket.Identity.Claims.ToList();
                    //var incomingClaimsHasNameIdentifier =
                    //    incomingClaimsFromAdfs.Any(c => c.Type == ClaimTypes.NameIdentifier);

                    //if (incomingClaimsHasNameIdentifier)
                    //{
                    var emailClaim = incomingClaimsFromAdfs.First(c => c.Type == ClaimTypes.Email);
                    incomingClaimsFromAdfs.Add(new Claim(ClaimTypes.NameIdentifier, emailClaim.Value));
                    //}
                    //else
                    //{
                    //    throw new ApplicationException("Get ADFS to provide the NameIdentifier claim!");
                    //}

                    var normalizedClaims = filter.Filter(incomingClaimsFromAdfs);
                    var claimsIdentity = new ClaimsIdentity(normalizedClaims,
                        n.AuthenticationTicket.Identity.AuthenticationType);
                    n.AuthenticationTicket = new AuthenticationTicket(claimsIdentity, n.AuthenticationTicket.Properties);
                    return Task.FromResult(0);
                }
            };
            app.UseWsFederationAuthentication(adfs);
        }
    }

The user service class looks as follows:

    public class AuthenticationService : UserServiceBase
    {
        private readonly IOwinContext _owinContext;

        public AuthenticationService(OwinEnvironmentService env)
        {
            _owinContext = new OwinContext(env.Environment);
        }

        public override async Task PreAuthenticateAsync(PreAuthenticationContext context)
        {
            var user = await _owinContext.Environment.GetIdentityServerPartialLoginAsync();
            if (user == null)
            {
                // no idp, so do partial login to HRD page
                context.AuthenticateResult = new AuthenticateResult("~/hrd", (IEnumerable<Claim>)null);
            }
            else
            {
                // we have partial login, so look for IdP claim
                var idpClaim = user.Claims.FirstOrDefault(x => x.Type == "idp");
                if (idpClaim == null)
                {
                    context.AuthenticateResult = new AuthenticateResult("Error: no IdP claim found");
                }
                else
                {
                    var idP = idpClaim.Value;
                    if (idP != "(local)")
                    {
                        context.SignInMessage.IdP = idP;
                    }
                }
            }
        }

        public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            var user = Users.Get()
                .SingleOrDefault(x => x.Username == context.UserName && x.Password == context.Password);
            if (user != null)
            {
                context.AuthenticateResult = new AuthenticateResult(user.Subject, user.Username);
            }

            return Task.FromResult(0);
        }

        public override Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            // issue the claims for the user
            var user = Users.Get().SingleOrDefault(x => x.Subject == context.Subject.GetSubjectId());
            if (user != null)
            {
                context.IssuedClaims = user.Claims.Where(x => context.RequestedClaimTypes.Contains(x.Type));
            }

            return Task.FromResult(0);
        }
    }

The controller looks as follows

    public class AuthenticationController : Controller
    {
        [Route("hrd")]
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            // this verifies that we have a partial signin from idsvr
            var ctx = Request.GetOwinContext();
            var user = await ctx.Environment.GetIdentityServerPartialLoginAsync();
            if (user == null)
            {
                return View("Error");
            }

            return View();
        }

        [HttpPost]
        [Route("hrd")]
        public async Task<ActionResult> Index(string email)
        {
            var ctx = Request.GetOwinContext();
            var user = await ctx.Environment.GetIdentityServerPartialLoginAsync();
            if (user == null)
            {
                return View("Error");
            }

            var idp = "(local)";
            if (email.Contains("example.com"))
            {
                idp = "94f924d6de9e46d9922004eeaff9ce54";
            }

            if (string.IsNullOrWhiteSpace(idp))
            {
                ViewData["Error"] = "Unknown provider";
                return View();
            }

            var claims = user.Claims.ToList();
            claims.Add(new Claim("idp", idp));
            claims.Add(new Claim("uid", email));
            await ctx.Environment.UpdatePartialLoginClaimsAsync(claims);

            var resumeUrl = await ctx.Environment.GetPartialLoginRestartUrlAsync();
            return Redirect(resumeUrl);
        }
    }

**Comment by brockallen** [comment]
You need to implement AuthenticateExternal in your user service.

**Comment by bloudraak** [comment]
Aah. That did the trick. Thank you.

**Comment by omardelgado** [comment]
I'm currently trying to implement this, but having the same issue.  Most of the code found online is not helping much.  It might be a user service issue, since all I have is the sample external user service implementation from your samples.  All I need is a nudge in the right direction.
