### ISSUE TITLE
"Type" property of "LoginPageLink" class has been deprecated?

### ISSUE THREAD

**Issue by wdzr** [IdentityServer/IdentityServer3#2099]
Why add this property?

**Comment by brockallen** [comment]
I don't follow. What are you talking about?

**Comment by wdzr** [comment]
I mean that the "Type" property has never been used in the code. I noticed you've set this property with AuthenticationType, but the View never use it.

**Comment by brockallen** [comment]
Right, but that's ok. Some people do use it in their JS or in their custom view service.
