### ISSUE TITLE
login over several IdPs - claimtransformation in Identity server - how to manage (map) users?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#2102]
Hello,

we have configured Google and some Wsfederation service as external Idp for our identityserver instance. Once the user is authenticated we add some additional claims to the token in "our" userservice.

Now the actual login names of the users might be different. Thats why we need a "virtual" user inside identityserver which knows which external user accounts match to the internal virtual useraccount. so we can add after authentication our special claims according to the "actual" user.

Is that approach sound for coping with several external Idps?
Is there any code sample which would facilitate that implementation?
(IdentityMAnager does not come with that out of the box, it just only manages users- not mappings)

**Comment by brockallen** [comment]
Yep, that's the point of your user service and the authenticate external method. We have some existing implementations for MembershipReboot and AspNet Identity.

**Comment by davidmrichter** [comment]
There can I find "your" already existing implementations for MReboot and Aspnet Identity?

**Comment by brockallen** [comment]
Sounds like you might be missing the wealth of info from our docs: https://identityserver.github.io/Documentation/docsv2/

Specifically MR and AspID: 
https://github.com/IdentityServer/IdentityServer3.AspNetIdentity
https://github.com/IdentityServer/IdentityServer3.MembershipReboot/

Which are all under this org here in github:
https://github.com/IdentityServer/
