### ISSUE TITLE
Can client requested scopes get denied in identityserver

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#2103]
with user interaction flows the user can deny an requested scope.
with non user interaction flows only client scoperestrictions are possible. 

otherwise by default any requested scope will be put into the Id or accesstoken. 
then the client can use scope authorization to check for presence of an particular scope. This somehow limits the concept of authorization over scopes, given that actually the requested scopes are being put into the tokens regardless of user and/or client. 

is it possible to disable certain scopes for certain users and/or clients? Is there any interface/plugin in identityserver available for that purpose?

**Comment by brockallen** [comment]
Scopes are about what the client app has permission to (not the user). You use consent for third party clients and require the use of a flow that involves the browser so users can deny permissions. For trusted clients you can disable consent where it doesn't make sense.

Similar questions have been asked before, so search the issue tracker history for more info.
