### ISSUE TITLE
idp is not returned in UserInfo

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3#2104]
I am finding that the idp claim is not being returned in the UserInfo endpoint.  Is there a trick to this?

First, I assume it should be possible because it is mentioned in the docs, and because other claims I configure will show up there.  So why not idp?

docs say: "This will be included as the idp claim in the identity token and the user info endpoint"
https://identityserver.github.io/Documentation/docs/advanced/userService.html

... though I admin I'm not sure if the context of that statement applies here.

As far as the configuration, I have ScopeClaims set up to include "idp" on scopes "openid" and "profile".  No avail, no result.

**Comment by leastprivilege** [comment]
In my thinking - idp is more like a "protocol claim" like iat, exp, amr etc...

We don't return these types of claims from userinfo...

Do you think we should?

**Comment by brockallen** [comment]
And to add to what @leastprivilege said, you do get that claim in the initial id_token.

**Comment by dapug** [comment]
Yes, the id_token returns it, which is great.  There are scenarios in the apps/clients that warrant needing the idp  (show the user where they signed in from, etc), and these scenarios might be important when id_token is not available.

From what I understand, id_token is not available in these two scenarios:
 - 1) after signing in with ResourceOwner  (you only get access_token, no id_token)
 - 2) in an API call (only has access_token, so if the service needs idp for some reason...)

**Comment by brockallen** [comment]
Session ID is a browser session -- it's not applicable with resource owner flow. And the sid claim is for authentication -- so OAuth2 only is not for authentication to the client. *shrug*

**Comment by leastprivilege** [comment]
isn't idp in the access token - I thought so.

**Comment by dapug** [comment]
shoot, my mistake, idp is in the access_token, yes. Sorry, just hyper focused on UserInfo here. Reason: it seems idp is a relevant claim/property of UserInfo.  For example, preferred_username is nice, great, but where did it come from?  idp.

Being in the id_token and access_token is otherwise technically sufficient, it just seemed a natural fit for UserInfo too.
