### ISSUE TITLE
OpenId Authentication does not call POST /token - why?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#2107]
Hello,

I have some OWIN MVC client(Flow = Flows.Hybrid) configured as such:
p_App.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
			{
				ClientId = "HybridCodeClient",
				Authority = Configs.IdentityAccessServiceURI,
				RedirectUri = Configs.WebAppRedirectURI,
				PostLogoutRedirectUri = Configs.WebAppPostLogoutRedirectURI,
				ResponseType = "code id_token token",

With Fiddler I found that never any request is made like POST /token!!

GET /connect/authorize?client_id=CodeClient&redirect_uri=https%3A%2F%2Fqs-sd.dsd.ch&response_mode=form_post&response_type=code%20id_token%20token&scope=openid%20roles%20AgateUsername%20WebApp&state=OpenIdConnect.AuthenticationProperties%3DQgen0GO81sCKUfl3tG_oSuMqKj9pP-abaMrrWsDJG3S3QSTEGsBJatefqA4skB8trGPWuhdpuL-4blnTIt3F_gyJrtK7oQb8aCAeH2KKpMbphr1yKJ2Tb6DKzYllGbHHA9egcGKGA3CEXL4oNU1ZOAXwpaOXqGa8Yj_wJ8_elCY7GxKT4JKqAww&nonce=635820501640515637.jU1MTUtYzU1Yi00ZDNhLWIyMjQtZTVkMTk1MTVkZTcx HTTP/1.1

So it seems this is the call that produces the token. why? I thought only the call to the token endpoint "gives" a accesstoken!

**Comment by leastprivilege** [comment]
nope. read the spec.

**Comment by davidmrichter** [comment]
Ok yes this is according to the spec.

I was a bit confused because in Dominik's Pluralsight course it depicts not the Hybrid but the actual OpenId Flow with getting a token.
Step 2b: Token Response in 6-oauthintro-m6-openid-slides.pdf 

But hybrid flow is different from OpenIdconnect  right?
