### ISSUE TITLE
IE Support for CSP

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#2110]
Hello,

Do you support csp for IE? I see that you only apply "Content-Security-Policy" header and IE requires "X-Content-Security-Policy" http://content-security-policy.com/

https://github.com/IdentityServer/IdentityServer3/blob/01f2446543d8f0c2252d565deb615ef2f3431319/source/Core/Configuration/Hosting/SecurityHeadersAttribute.cs#L81

**Comment by brockallen** [comment]
Wow that's upsetting about IE. Yes, we can do this. Sadly it'll involve emitting the header twice on each request.

**Comment by pawepaw** [comment]
Yes it's simply emitting both Content-Security-Policy and X-Content-Security-Policy header per request.

**Comment by brockallen** [comment]
I'm on it.

**Comment by brockallen** [comment]
Done on dev.
