### ISSUE TITLE
How to access Claims in EmbebbedAssetsViewService Login.html

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#2114]
I need to Access claims  handleCallback() function. how can i get that..

**Comment by brockallen** [comment]
The user's claims? Also, what handleCallback() function?

If you need the user in your custom code, then inject the OwinEnvirnomentService and then use the OWIN extension methods to get access to the current logged in user: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by leastprivilege** [comment]
progress?
