### ISSUE TITLE
Need to protect separate tier(api endpoint) for data access of the identity server by oauth. 

### ISSUE THREAD

**Issue by somak12** [IdentityServer/IdentityServer3#2115]
Hi,
I already had a discussion on this in gitter, still I thought of raising this as an issue to keep track. 
I have set up a N-tier system and authenticated them using id server which is self hosted in a MVC application. 
In my set up the id server is fetching all its configurations and users from an API endpoint. As for example IClientStore is implemented to make rest call  to an API endpoint which returns the scopes for the id server. 
In this kind of N-tier system how is it possible to protect that API which is exposing all the configurations and the user details for the id server by oauth under the same authority? 
Please let me know if my question is not clear.

**Comment by mderriey** [comment]
Hi,

From what I get it's a bit of a chicken-and-egg problem.  
You access an API to get configuration data for IdSrv, but in the meantime want to protect this same API with IdSrv?
I'd say it's like wanting a DI container to resolve some service so you can then register it.

Am I getting this right? If so, I don't think this would be possible.

**Comment by somak12** [comment]
@mderriey  Yes you got it right. My thinking is also the same. So I got few suggestion from gitter in this regard, few of them are: 
IP whitelisting.
Service account with windows auth security.

Any other suggestions?

**Comment by mderriey** [comment]
Well it all depends on the architecture, I would say, so I'll leave this to you.  
Many things are to be taken into account:

 - are the client (IdSrv) and the API in an internal network?
 - how many clients for the API?
 - how evolutive the list of clients is?
 - how secure you want it to be?

**Comment by leastprivilege** [comment]
progress?

**Comment by somak12** [comment]
For now I have decided to protect the internal api as a private service by not exposing it to the public ip.
