### ISSUE TITLE
IdentityServer3 vs Azure Active Directory vs AWS Directory Services

### ISSUE THREAD

**Issue by RehanSaeed** [IdentityServer/IdentityServer3#2116]
I'm comparing the above three technologies and just wanted to try to find out the advantages/disadvantages and get a sense for when I should be using IdentityServer3 over the other technologies. I have three scenarios:

- Internal MVC Client to Web API
- External Phone Client to Web API
- Internal Web API to Web API

**Comment by brockallen** [comment]
Well, IdentityServer can help you with all three. I guess that's the upside of using IdSvr - it's one approach for all those scenarios.

**Comment by RehanSaeed** [comment]
Not sure about AWS but according to the [Azure Samples](https://github.com/Azure-Samples?page=3&query=active-directory&utf8=%E2%9C%93), my understanding is that it can also do all three.

A comparison of the different technologies in this area doesn't seem to exist.

**Comment by brockallen** [comment]
Well, the main thing that differentiates IdentityServer is the ability to customize and have control of the user data. SaaS products are very limited in customization because for the most part they don't let you upload arbitrary code to alter or change behavior and they often encapsulate the database of users. On the other hand, this means you have to host IdSvr (which can be cloud hosted) and build a database for your users. So if you need the control, IdSvr is a good choice.

Also, I should note that very often IdSvr is used in conjunction with other identity providers (like ADFS or AAD). IdSvr is deployed in between the apps and the ultimate IdPs, again, usually to allow the customization that the apps need.

**Comment by RehanSaeed** [comment]
Thanks @brockallen I'll try IdentityServer3 and Azure out and report back here for the benefit of others.

**Comment by mattGuima** [comment]
hi @RehanSaeed,

any updates on how you got along? I'd be very interested to know the results.

thanks :)

**Comment by RehanSaeed** [comment]
**Disclaimer**: I looked into this for use by the company I work for, who had existing infrastructure I had to cater to, so the solution I chose is skewed in that direction. Even so I've tried to give an impartial summary of my own thoughts.

# Azure Active Directory

Azure Active Directory is a hosted identity solution, so there is far less setup (especially if like me, you discover that you are already using it for Office 365). Out of the box, it provides some very nice features that can get you started very quickly.

The premium version has monitoring and reporting capabilities so you can see who is logging into your system, it has two factor authentication, an identity management website and Microsoft is monitoring logins (a bit like cloudflare for identity), so it should in theory provide some added security. However, the customization of the UI is very basic, you have to pay for the premium features and using the Azure Portal to do identity management (if you go with the free version) is kind of a pain.

The documentation is pretty good and there are samples on GitHub with Microsoft devs actively monitoring the issues which was helpful.

# IdentityServer

IdentityServer is the Swiss Army knife of Identity management. It can do everything but does require a small amount of setup and a little more knowledge of the identity space. It can do most things that I listed above and a lot more beyond.

It has to be noted that even if you are using Azure Active Directory, there may still be reasons for choosing IdentityServer which I had not initially considered. For example, if you have more than one source of user data e.g. You are using AD and also a SQL database of users, then IdentityServer can be used to point to both of these sources of user information. In theory it should also make it easier to switch from AD to something else entirely as it decouples things.

The project is actively developed, has code samples for all the authentication flows and you can get answers from the community.

# Summary

I discounted AWS Directory Services as it's very young even though the company I work for uses AWS. We also use Office 365, so I discovered that we already had an Azure Active Directory linked to an on-premises active directory server. Even so, IdentityServer is still a valid contender for reasons I explained above. We are still trialing both solutions...

What you decide to choose depends entirely on the problem you have. Which should you choose? Well, it depends on the number of developers, time, money and effort you can expend setting this up. There is no one size fits all solution.

**Comment by leastprivilege** [comment]
thanks for the write-up. that's useful!

**Comment by mattGuima** [comment]
that's fantastic! thanks so much for sharing :) you should put that on a blog post somewhere

**Comment by RehanSaeed** [comment]
At some point, I'll write this up at [rehansaeed.com](http://rehansaeed.com) with some extra info.

**Comment by mattGuima** [comment]
cool, I'll check it out

**Comment by johnkattenhorn** [comment]
This is really useful, I've just been through this reasoning myself for one of our clients e.g. They have AAD / Office 365 but we decided to go with Identity Server because it will help their migration from many user stores to one even if the final destination ends up being AAD. In our next Sprint we will be hosting Identity Server in Service Fabric so it will be interesting to see how we get on.

**Comment by iBoonz** [comment]
Don't forget the [Admin](https://github.com/IdentityServer/IdentityServer3.Admin) repo for your client and scope management ;)

**Comment by belaie** [comment]
Is there any cloud based IDaaS (Identity-as-a-service) provider which providing identityserver as a hosted service customizable instance per customer?.

**Comment by RehanSaeed** [comment]
It's a great idea. The difficulty is that there are so many extensibility points. It's basically what Azure Active Directory is.

**Comment by RehanSaeed** [comment]
I've written this up into a blog post [here](http://rehansaeed.com/azure-active-directory-versus-identity-server/).
