### ISSUE TITLE
Need more flexible registrations or access to Autofac ContainerBuilder

### ISSUE THREAD

**Issue by tillig** [IdentityServer/IdentityServer3#2117]
I'm in the process of adding some dependency registrations that will end up getting used in a custom view controller. In my specific case, it's a configuration value provider that implements five different interfaces.

In Autofac, I'd register the dependency like this:

    builder.RegisterType<ConfigurationProvider>()
            .AsImplementedInterfaces()
            .AsSelf()
            .SingleInstance();

There's really no equivalent for `AsImplementedInterfaces()` in the custom IdentityServer `Registration` object syntax. I believe I'm actually going to have to create six different registrations - one for `AsSelf()` and one for each of the five implemented interfaces. That's not super awesome if I want to give the one service a lifetime scope of singleton - I'll have six singletons.

There's also no provision I've found for setting property injection up - the `PropertiesAutowired()` registration in Autofac.

It would be nice if there was a more concrete integration with Autofac (not IL-merged?) so I could access the actual ContainerBuilder to add registrations with the full power of Autofac. Either that, or (less desirable) enhance the custom DI wrapper language to support more features.

**Comment by brockallen** [comment]
We can discuss this.

**Comment by tillig** [comment]
Thanks! I'm guessing [Autofac.Owin issue #1](https://github.com/autofac/Autofac.Owin/issues/1) for OWIN configurable lifetime scope key may play in here a bit. Let me know if there's anything I can do.

**Comment by leastprivilege** [comment]
Would you be interested in extending our `Registration<T>` to support more autofaciness?

**Comment by tillig** [comment]
Do you mean via PR?

I may be able to, but I'm curious about the design behind why everything is isolated behind the custom syntax. It implies that if you want to support more "autofaciness" the syntax concepts need to be copied over and maintained. Sort of painful, like a reverse version of what MS did with Microsoft.Extensions.DependencyInjection.

Would it be bad to decouple the DI concepts/services from Identity Server and just use Autofac directly? Or use something like Microsoft.Extensions.DependencyInjection and let folks plug in their own containers?

Not trying to be challenging, just trying to understand.

**Comment by leastprivilege** [comment]
The reason for the abstraction is that we are internalizing Autofac using ILMerge. That's why we cannot hand out the autofac container directly.

**Comment by tillig** [comment]
Why ILMerge, though? Could you get by taking Autofac as a NuGet dependency so folks could have control? Alternatively, if you don't want to tie directly to Autofac (if that's a problem for whatever reason), you could take something like Microsoft.Extensions.DependencyInjection (also not ILMerged).

**Comment by jageall** [comment]
to avoid dependency hell. If IdentityServer relies on v2 of autofac and
something else you reference relies on v1 ...

**Comment by tillig** [comment]
...then NuGet takes care of resolving it and even handles the binding redirects. This is only going to get worse with ASP.NET 5 and the framework/BCL coming in as packages.

It just seems like a lot of pain (like trying to wrap every dependency you want to expose) for not much benefit. That's why I'm trying to figure out the rationale behind it.

If it's just for dependency management, the long term plan might be to reconsider that, especially if there's a plan to work on ASP.NET 5. If it's for some other reason, I'm curious what that is.

**Comment by jageall** [comment]
you are assuming that v1 and v2 are actually compatible enough to do that
redirect, and that is often not the case

**Comment by tillig** [comment]
I guess we can disagree there. Autofac changed between v2 and v3 but v3 and v4 are still interface compatible. Newtonsoft.Json has been compatible for several major versions. Lots of things are stable even across major versions.

The question is: does the compatibility insulation around ILmerge justify the inflexibility?

Some examples of things I'd LOVE to be able to do in my IdentityServer app that we'll be really hard if you want to wrap the container:

- Singleton that gets used outside IdentityServer (eg a configuration repository used both in custom endpoints and in IdentityServer extensions)
- Metadata on registrations so I can select implementations
- DynamicProxy interceptors for AoP
- Configuration-based registrations so dependencies switch by environment

That stuff is available for free if I can control the container. If you have to extend the syntax for a wrapped container, you can do better but you still can't do the singleton registration.

Is the dependency isolation worth it?

**Comment by brockallen** [comment]
We did what @jageall says for the reasons he described, but it was for all of our dependencies. So it was simply a blanket decision.

**Comment by tillig** [comment]
OK, so it sounds like there may be a couple of options here, including potentially de-coupling Autofac.

Before we go there, one thing I'm noodling on right now is the possibility of extending the current `Registration<T>` thing to be a bit closer to the way Microsoft.Extensions.DependencyInjection works, then exposing some way to replace the implementation of the service resolver with something custom. If not overridden, a default internalized Autofac could still be used.

It'd ideally work the way MVC and other swappable dependency resolvers would work - if you want, you can replace the resolver; if not, use the one that ships. We'd probably also need to expose a way to "add registrations" for the default set of services to a resolver so if you are swapping out resolvers, you can still use the default set of services and just override the ones you want. That's where the similarity to Microsoft.Extensions.DependencyResolver comes in. The `ServiceCollection` you see in Microsoft.Extensions.DependencyResolver is sort of like `IdentityServerServiceFactory`.

The tough part is probably going to be figuring out how to express `IdentityServer3.Core.Configuration.Hosting.AutofacConfig` in a container-agnostic way. That's the set of services you'd want registered with by default with any backing container. I see there are some things like decorators and named parameters being used, though, which may make that difficult.

**Comment by tillig** [comment]
...and it [appears in IdentityServer4 this is all actually what you ended up doing](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/IdentityServerBuilderExtensions.cs) which is super awesome.

**Comment by leastprivilege** [comment]
So we are not really interested in being able to support more DI frameworks. We decided using autofac - but the fact that we internalized it - makes it an implementation detail.

So the only way to add more features to it is by adding them to `Registration<T>`.

**Comment by tillig** [comment]
OK, sounds like `Registration<T>` is my only option. Thanks for helping me understand the desires here. Let me talk to my team and see when I might be able to get some time to help out on that.

**Comment by tillig** [comment]
I'm looking at this now. How amenable are you to a change in the `Registration` interface?

For example, the notion of `AdditionalRegistrations` is confusing and will be even more confusing if there's an `AdditionalDependencyTypes` property (to fulfill things like `AsImplementedInterfaces`).

Also, the `Name` property makes sense if you only have one `DependencyType` (interface), but once you have multiple potential interfaces, naming each independently becomes more important - so mappings of implementation to interface becomes more of a dictionary construct. Your component type (`Type`) maps to one or more _pairs_ of interface + optional name.

Finally, there's a challenge with trying to have one base `Registration` that handles all three registration types of provided instance, factory method, and reflection-activated type. It appears you've already run into it: some things don't make sense in some cases. For example, you can't really specify "instance per use" on a singleton.

If I can split that into three different types and use sort of a "builder" syntax, it can provide a really nice fluent grammar that helps people do what they need to in a "pit of success" fashion, rather than being caught by a runtime exception.

I envision something like:

```csharp
var registration = RegistrationBuilder
                   .For<TImpl>()
                   .As<TInterface>()
                   .Named<TOtherInterface>("name")
                   .Singleton();
```

Obviously that won't work with the current interface.

Would something like that be OK? Or do I need to do everything without breaking the interface at all? (If that's the case, it may end up... a little messy at best. Again, consider the `AdditionalDependencies` / `AdditionalDependencyTypes` confusion.)

**Comment by brockallen** [comment]
> "pit of success"

did you use to work at Microsoft?

**Comment by tillig** [comment]
No, but I can't say I haven't been "corporatized." :wink:

**Comment by brockallen** [comment]
Also, how awful is it for you if these changes are too much?

**Comment by tillig** [comment]
It'd be pretty rough, I won't lie. I'd really like to contribute rather than totally fork, but my choices are coming down to: figure out a way to get a better registration mechanism in here; totally fork and build entirely custom; or... Well, that's where I'm at. I _really_ don't want to "own" this whole thing.

I can try doing it without breaking any interfaces (additive only), but at the cost of a potentially very confusing final interface with a lot of runtime checks (and errors) to rectify options that are mutually exclusive.

I can't go to IdentityServer 4 yet since we aren't green-lit for ASP.NET 5 (or whatever they're calling it today).

**Comment by brockallen** [comment]
Well, since we use semver, the breaking API changes wouldn't be until 3.0, which we don't even have a guess as to a planned release date. We have 2.4 on the horizon. I don't think we'll have a 2.5, but no promises.

**Comment by tillig** [comment]
Which would be better for you? Kinda confusing API but not breaking? Breaking changes with a better API? Or no change at all? I don't want to be "that guy" who forces some change the maintainers secretly don't want, but at the same time I'm kinda blocked on my project with things as they are now.

**Comment by tillig** [comment]
Change in plans: Given the challenge here (as well as some other unrelated challenges we're running into with the project) we worked and got the green light to actually do .NET Core 1.0 / ASP.NET Core 1.0 / IdentityServer4.

Yeah, it surprised the crap out of me, too. :open_mouth: 

Anyway, feel free to close this if you think it's no longer interesting to pursue. If we run into stuff or can help on IdentityServer4, you'll probably see us over there. (_You have been warned_ :wink: )

**Comment by brockallen** [comment]
Ok, see you over there.
