### ISSUE TITLE
Should I even be trying to use Identity Server?

### ISSUE THREAD

**Issue by RobKraft** [IdentityServer/IdentityServer3#2118]
We have a traditional ASP.Net app that we are converting to a REST API on the back end and also converting it to an Angular browser app.  The REST API is already mostly done because we developed it for our Android/Java mobile app.

But our security is not good.  The mobile app uses a never-expiring guid to log in.  We also have 3rd Party developers using our REST API that pass logon/pwd on every call.  So I've been trying to understand Identity Server to solve all of our needs.

I believe that our internal apps should NOT pass claims to our REST API because our security model is very sophisticated and would require hundreds or thousands of claims; so I thought we should just pass the logonID from the clients in a token, and thus we would use an Identity Token passed as a JWT.  Does that sound like a good decision?

If so, for our internal app, is there an example where we can have our current internal ASP.Net web page collect the logon and password, call the Identity Server STS, then return the identity token to our Angular client?  (I was trying this example but it is out dated and also is not using an identity token: http://www.codeproject.com/Articles/683732/Thinktecture-Identity-Server-Configuration-Customi)  

I am starting to think that I should just roll my own system since I can store "token identifiers" in the database and we write the code for all the components that would issue or validate them.  Do you think we should do that?  I know that would make it easier for us to get this project done, but I don't think it will meet our long term federation needs.

Thanks in advance for your input.

**Comment by mderriey** [comment]
Putting aside the concept of claims and tokens...

What Identity Server brings to the table is a compliant implementation of OpenID Connect. It's a thin layer built on top of OAuth2 to perform **authentication** against end users of your application. OAuth2, by itself, only embeds **authorization**.

I like to map these concepts to the differents types of tokens you can get from Identity Server:

 - Identity tokens, which you can get after to the authentication of an end user by Identity Server. These tokens hold information about the user in claims, but in no way can they be used to access protected resources
 - Access tokens, like their name implies, can be used to access such protected resources. An access token can either represent an end user or a client (most of the time an application)

I guess what I'm trying to get to is that you should ask yourself if you can identify end users and clients in your model. 

The main difference when you have end users is that you would, for example, federate one of your web application agains Identity Server. When a user wants to log in, he'll be redirected to a login page hosted by Identity Server, where he will enter his credentials, then redirected back to the application, where you'll be able to get informaiton about him (an Identity token) and potentially an Access token so you can call protected resources as this user.

When you only deal with clients, there's no login page. Typically, a client - the 3rd party developers using your API - would call an endpoint on Identity Server, passing along some credentials, and will ge tin return an Access token. This token will be passed to every subsequent request against your REST API so they can be authorized.

It looks to me that you're only in the second case. Still, it doesn't mean you should not use Identity Server, but make sure you understand that you won't deal with the *Users* part of it, but only with the *Clients* part.

I hope this makes sense and that I understood your context.

**Comment by RobKraft** [comment]
Thanks for the lengthy reply Mr Derriey.  I don't think I quite explained my context clearly enough, but I did think of one additional requirement that highlights my challenge.  The REST API must record the identity of the person performing certain actions against it; therefore the REST API cannot simply accept a token that confirms the Human User or Client App has permission to an end point, it needs to know who the person is.  So, partially for that reason also, I thought that passing an Identity Token to the REST API would be better than passing an Access Token.

**Comment by brockallen** [comment]
But the access token does have the user's identifier in it -- does that satisfy your requirement? In fact, you can put any info in the token you want.

**Comment by RobKraft** [comment]
Thanks Brock, I was not sure if access tokens or identity tokens to the REST API are best.  We definitely want to have the REST API validate the token it receives against the database or the identity server.  Can we do that easily with the Access Token?  Our REST API certainly needs the user logonID, and only the user logonID because if we passed claims we would potentially have to include thousands of claims per user.  
But I have read that using an Access token to confirm identity is "cheating", and that the OpenID protocol was created to solve the problem with Identity Tokens, which is why I have been leaning towards Identity Tokens.
Is it acceptable in some cases, perhaps such as ours, to use Access Tokens to validate the user Identity?

**Comment by brockallen** [comment]
id tokens aren't designed for APIs.

**Comment by RobKraft** [comment]
Thanks Brock, it is very helpful for me to be able to interact with experts such as yourself so that I can head my design in the right direction.  I will use an Access token and the LogonID will be a claim in it.  I think my next step will be to figure out how I want the REST API to validate that Access token.

**Comment by brockallen** [comment]
To validate the token use the bearer token validation middleware. Our API samples are using it: https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/

**Comment by RobKraft** [comment]
Thanks!

**Comment by brockallen** [comment]
Also thanks for @mderriey for the answer.
