### ISSUE TITLE
How to setup SSO between two systems, where each of them have own authentication policy, e.g. two-factor authentication based on a business situation of a local user.

### ISSUE THREAD

**Issue by mirecg** [IdentityServer/IdentityServer3#2119]
I have the following situation. I have two systems. Lets call them system A and system B. 

Both of the systems have authentication with username/password and they require second factor (SMS or Certificate) only when user has some significant business position based which is evaluated from data in system. 
So that the following can happen. 
When acccessing System A a user is autenticated for example with only username/password but when going to System B he is required to provide second factor. 

How to achieve this scenario? 

I could setup 3 instances of IdentityServer. One as SSO gateway and two other instances as external identity providers for the system A and system B. The SSO gateway would do HRD based on URL parameter which would tell to which system is user going. How can I achieve that when the user is already authenticated in system A and tries to access system B, that he needs to provide second authentication factor? I'm not sure if the described solution is the right one or this can be done in some other ways. 

Thank you.

**Comment by brockallen** [comment]
Just check the amr claim in your app -- if it's not sufficient then send the user back to IdSvr and request that authentication type via the acr_values.

**Comment by mirecg** [comment]
I don't like the idea that the app makes this decision. Is it somehow possible to have this decision on the side of IdentityServer?

**Comment by brockallen** [comment]
How would IdSvr know at what point the app needs it?

Anyway, if you can simply base it off your client then sure, you can implement that logic in your user service.

**Comment by mirecg** [comment]
I thought that there is always some handshake with IdSrv each time when the user makes some request to the app. 

The UserService is being called only during the authentication of a user. After that there is no call to UserService. So how can I force the userservice to be called even when the user is already logged in? You wrote that "if it's not sufficient then send the user back to IdSvr and request that authentication type via the acr_values."

I can see in the samples that there is SecurityTokenValidated in which the claims could be transformed. But this occurs also only once after authentication. How can I force claim transformation on each request?

**Comment by leastprivilege** [comment]
You can use middleware that runs on each request and transform claims.

**Comment by mirecg** [comment]
Hi, 

regarding the first question, how can I force the UserService to be called even if the user is already authenticated, I've found that there is a prompt(=login) parameter by using which I can force the userservice to be called again and to request 2nd factor from the user if it is required. And which factor is required, this could be driven by acr_values parameter.

**Comment by brockallen** [comment]
So in the user service you know the client app being logged into, so you could have your logic there and trigger a partial login to force 2fa if needed.

But ultimately, it's up to the client app to enforce its own requirements.

**Comment by mirecg** [comment]
Yes, you are right, meanwhile, I've already realized that the client is the one who should be responsible for enforcing the authentication requirements.

**Comment by brockallen** [comment]
Ok -- so we can close this issue now?

**Comment by mirecg** [comment]
Yes, thank you
