### ISSUE TITLE
U2F and/or two factor authentication

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/IdentityServer3#2121]
Hi, 
I was wondering if you have planned to implement U2F and/or two factor authentication?
We are thinking to use YubiKey into our extranet.

Thanks

**Comment by brockallen** [comment]
You can implement that yourself with partial logins.

**Comment by imperugo** [comment]
Any hint/link?

**Comment by brockallen** [comment]
Check the docs and samples. 
https://identityserver.github.io/Documentation/docsv2/advanced/userService.html
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService

**Comment by leastprivilege** [comment]
let us know when/if you have something to share.
