### ISSUE TITLE
terminology explanation possible correction

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2122]
at https://identityserver.github.io/Documentation/docsv2/overview/terminology.html

I think instead of:    
Identity Token: An identity token can be validated by the client.    
it may be better to say: 
Identity Token: Representing an authenticated identity. 

A token from the OP, that tells the client that an identity has been successfully authenticated by the OP. 

Also instead of:    
Access Token: An access token can be validated by a resource.
it may be better to say: 
Access Token: Representing a resource to be authorized.    
A token from the OP, usually passed on by the client to an API, according to which the API can authorize access to resources, usually restricted to authenticated identities as listed in the token.

**Comment by brockallen** [comment]
Our docs have a link to allow you to edit and submit a PR :)

**Comment by pashute** [comment]
I know, but my question is if my "correction" seems correct to you?

2015-11-05 0:16 GMT+02:00 Brock Allen <notifications@github.com>:

**Comment by leastprivilege** [comment]
done
