### ISSUE TITLE
Adding properties to the modelJason object in PageAssets of the DefaultViewService

### ISSUE THREAD

**Issue by SosaWISE** [IdentityServer/IdentityServer3#2123]
When a user clicks on the logoff link in the identity server pages it takes the user to the logedout asset page.  We have customized this page so that there is a link that will take the user back to the home page of the application that he was in.  Since right now we only have one application it would be easy to hard code the return URL.  However in the future we will be adding more we would like to add a property in the modelJason object so that we can bind it via angular JS to the page.

How is this done?  Any help would be appreciated.

**Comment by brockallen** [comment]
The client needs to send a post logout redirect URI at logout time. Many of our samples do this.

**Comment by SosaWISE** [comment]
Sorry I'm new to Identity Server.  Can you point me out to an example to look at?  Thanks.

**Comment by brockallen** [comment]
We have lots of sample client applications here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients
