### ISSUE TITLE
No cookie matching signin id found + Reverse Proxy Apache

### ISSUE THREAD

**Issue by cuongbk81** [IdentityServer/IdentityServer3#2125]
I deploy Idsv3 into: http://192.168.1.100:8181/idsv3
We config: http://mycompany.com/idsv3:
{
ProxyPass /sso http://192.168.1.100:8181/idsv3
ProxyPassReverse /sso http://192.168.1.100:8181/idsv3
ProxyPassReverseCookiePath /sso http://192.168.1.100:8181/idsv3
}
All request to http://mycompany.com/idsv3 will be redirect to http://192.168.1.100:8181/idsv3
Client config:
{
AuthorizeServer: http://mycompany.com/idsv3/core/
}
Idsv3 config:
{
 var options = new IdentityServerOptions
                {
                    SiteName = ConfigurationManager.AppSettings["SiteName"],
                    RequireSsl = false,
                    SigningCertificate = Certificate.Get(),
                    Factory = idSvrFactory,
                    PublicOrigin = "http://mycompany.com/",
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        //IdentityProviders = ConfigureIdentityProviders,
                        EnablePostSignOutAutoRedirect = true,
                        EnableSignOutPrompt = false,
                    },
                };
}
When we login from Client, it redirect to http://mycompany.com/idsv3/core/login?signin=3719c37ea2fe586c3a7ea50158836cb7 then exception: "There is an error determining which application you are signing into. Return to the application and try again". But we check log, that has information "No cookie matching signin id found". I think Idsv3 not write cookie into http://mycompany.com/ by Reverse Proxy Apache, so Idsv3 does not read all information of cookie to compare.
Please help to debug that. Thanks!

**Comment by brockallen** [comment]
I'd suggest doing some HTTP tracing between the proxy and the web server -- check how the signin cookie is issued and debug why it's not being honored by the reverse proxy.

**Comment by cuongbk81** [comment]
Thanks BrockAllen for support, I log some information:
  \"ClientId\": \"implicitclientjs\",
  \"ClientName\": \"Company login\",
  \"RedirectUri\": \"http://10.15.152.163:21575/index.html\",
  \"AllowedRedirectUris\": [
    \"http://10.15.152.163:21575/index.html\",
    \"http://10.15.152.163:21575/silent_renew.html\"
  ],
  \"SubjectId\": \"unknown\",
  \"ResponseType\": \"id_token\",
  \"ResponseMode\": \"fragment\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid\",
  \"State\": \"11391845867457424\",
  \"Nonce\": \"9550378390074187\",
  \"Raw\": {
    \"state\": \"11391845867457424\",
    \"nonce\": \"9550378390074187\",
    \"client_id\": \"implicitclientjs\",
    \"redirect_uri\": \"http://10.15.152.163:21575/index.html\",
    \"response_type\": \"id_token\",
    \"scope\": \"openid\"
  }
}"
[Information] User is not authenticated. Redirecting to login.
[Information] Authorize point host:http://mycompany.com/
[Information] Authorize point path:/idsv3/core/connect/authorize?state=11391845867457424&nonce=9550378390074187&client_id=implicitclientjs&redirect_uri=http%3A%2F%2F10.15.152.163%3A21575%2Findex.html&response_type=id_token&scope=openid
[Information] Authorize point Url:http://mycompany.com/idsv3/core/connect/authorize?state=11391845867457424&nonce=9550378390074187&client_id=implicitclientjs&redirect_uri=http:%2F%2F10.15.152.163:21575%2Findex.html&response_type=id_token&scope=openid
[Information] Authorize point  message.ReturnUrl:http://mycompany.com/idsv3/core/connect/authorize?state=11391845867457424&nonce=9550378390074187&client_id=implicitclientjs&redirect_uri=http%3A%2F%2F10.15.152.163%3A21575%2Findex.html&response_type=id_token&scope=openid
[Information] End authorize request
[Information] Redirecting to login page
[Debug] Protecting message: "{\"ReturnUrl\":\"http://mycompany.com/idsv3/core/connect/authorize?state=11391845867457424&nonce=9550378390074187&client_id=implicitclientjs&redirect_uri=http%3A%2F%2F10.15.152.163%3A21575%2Findex.html&response_type=id_token&scope=openid\",\"ClientId\":\"implicitclientjs\",\"AcrValues\":[],\"Created\":635823754395330374}"
[Information] Write Cookie Id:11437a4d2240a3bc046a22cd9352667a
[Information] Write Cookie Name:SignInMessage.11437a4d2240a3bc046a22cd9352667a
[Information] Write Cookie Data:88ToGnpoAWiTtoMMyjreqZh9CcVZtOrjt-6LytaXEWcs_Q2vGtLfPrf8zXpoTegVgghyXmj05_V_fGT5eYSQyDtmvc37XU7Soke92q3f4y6xDMBjmxNFIzhNzGedtyp72sZRo7jpTHWPMX2l9dbL0l8fnbN-nwOOwPM2u5CyQXcfGyW6WWSmrQFnq-88xncjt-u3f6nPkBV5SP6hSjMMgCj_vhw61QuecacBM8ySjcq3_dw3rlA4rzjgn6zkaaBiaMCKCzy-nGokXoXaQq5taYQsGujyWQ7NEquFTB5WL-cStbkrw-LCH97fNM-j8ueSF8GV9RjbBm7WqUHUtTY24tl2feLmqeHZX4uMNEm2xoG6gJJIP1gDAB6PQr2q2wSSUukTQMV66ij3n9QWaiWx6lVe5BmRbyyiERdq0oscMhRq9VdgXyJYNcphGFvcwlmah3kwgCkCj6G13xlWwqNuEZP16veWAbG2m2CM7leKp20
[Information] Write Cookie CookiePath:/idsv3/core
[Error] Write Cookie OK
[Error] Server:http://mycompany.com/idsv3/core/
[Information] Login page requested
[Information] Read Cookie Id:11437a4d2240a3bc046a22cd9352667a
[Information] Read Cookie Name:SignInMessage.11437a4d2240a3bc046a22cd9352667a
[Information] No cookie matching signin id found

I think cookie is write complete but Reverse Proxy Server not issue to http://mycompany.com/idsv3, then Idsv3 not Read to validate.
Pls suggest tool for trace between the proxy and the web server?
Thanks for support.

**Comment by brockallen** [comment]
Who setup your reverse proxy? I'd ask them for support on this.

**Comment by brockallen** [comment]
Ever get this solved?

**Comment by cuongbk81** [comment]
I don't fix with Reverse Proxy but Identity Server 3 work done with Nginx proxy
