### ISSUE TITLE
Question about ITokenHandleStore

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3#2127]
Can you please point me to the documentation for ITokenHandleStore ?

I am not sure when, why and what the following methods are used. 

ITokenHandleStore.GetAllAsync
ITokenHandleStore.RevokeAsync

**Comment by brockallen** [comment]
This is the only place we mention it, I think: https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html

It's for storing token data that IdSvr needs to persist.

**Comment by aaabdul** [comment]
Thanks. There are not much description about these two methods other than in the code itself. Can you please when IDS will call these two methods ?

Also when I logout (i.e. using endsession end point) I am getting the following error

IDX10709: 'jwtEncodedString' is not well formed: '7e5f9217e7076a920e65360b91cbf7e7'. The string needs to be in compact JSON format, which is of the form: '<Base64UrlEncodedHeader>.<Base64UrlEncodedPayload>.<OPTIONAL, Base64UrlEncodedSignature>'.

It's quite obvious it's because I am using reference token. Is it not possible to use log-out if I am using reference tokens instead of JWTs ?

Apologies for asking too many questions.

**Comment by brockallen** [comment]
Open a different issue for new questions.

As for when IdSvr calls it -- I'd suggest looking in the code itself if you want that level of detail. In short, IdSvr needs to store tokens from time to time and this is needed to do that.

**Comment by aaabdul** [comment]
Thank you. I will open create another question.
