### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:44333/core/.well-known/openid-configuration. (Reason: CORS request failed).

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3#2128]
![image](https://cloud.githubusercontent.com/assets/10266752/10969894/1946b854-83f1-11e5-89bd-1895f8429116.png)

**Comment by brockallen** [comment]
And what is your question?

**Comment by CBlenocwe** [comment]
Hi Brock
I am new to this and having the same Cross- Origin Request Blocked error occur.
As well as:

ERROR Error: Uncaught (in promise): Error: Network Error
h</t.prototype.getJson/</s.onerror@http://localhost:3000/node_modules/oidc-client/lib/oidc-client.min.js:1:27826
wrapFn@http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:30

Any idea why this is happening?
Thanks
