### ISSUE TITLE
How: claim transformation in userservice with data from resource protected by the same IdServer instance

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#2129]
hello there, 

we have an REST service which provides additional data about some users or other real world "entities".
this service is protected by identity server.
now in an addtional scenario we want to incorporate information provided by this service into the Accesstoken. this would take place in the userservice. but at the time the user service is called - no Token has ever been produced. But the accesstoken is precondition to access the mentioned service.

How would be the default solution for that scenario?
would it be possible in that case, assuming everything happening behind the firewall, to circumvent the authentication?

**Comment by brockallen** [comment]
So you're in IdSvr and want to call an API to get claims for a token, but the API needs to be protected by tokens from IdSvr? Sounds like a chicken and egg problem.

**Comment by davidmrichter** [comment]
exactly! But is calling some service inside the Userservice that uncommon? Only our challenge is that the service is protected by the very same IDServer which is "booting up".

So the only possibility left is to access the data from the DB directly circumventing the WebApi Controller Layer.

or could one use a versioned REST: one protected version for external calls - and one version unprotected

Would that be a sound approach?

**Comment by brockallen** [comment]
You might be able to inject the token service into your user service to gen a token on the fly to call your API, but I suspect you'll end up with circular DI references at runtime.

**Comment by davidmrichter** [comment]
I agree... 

So descision is between:
-two REST Services providing the same features but one of them unprotected behind firewall using the same businesslogic
or
-IdentityService sharing access to the same DB and Businesslogic as the actual (protected) REST Service

I lean towards the first approach..

**Comment by brockallen** [comment]
Your call at this point. I don't know enough about your whole environment.
