### ISSUE TITLE
Question - linking refresh token to access token

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3#2131]
Is there a way to link refresh token to access token ?

I am trying to implement IRefreshTokenStore. In the "RefreshToken" object there is a property for "AccessToken" but I can't seem to be find the key for it (by key I mean the one sent to ITokenHandleStore implementation).

**Comment by brockallen** [comment]
That's just something to persist along with the refresh token. IIRC in our EF implementation we just convert it all to JSON.

**Comment by aaabdul** [comment]
ok. Thanks that would work.
