### ISSUE TITLE
Is it possible to track tokens as they are issued?

### ISSUE THREAD

**Issue by BillBakerAcmOrg** [IdentityServer/IdentityServer3#2133]
Implementing a AccessTokenType.Reference, Client Credential Flow, IdSrv3. I have requirement to track/log every token issued. I hooked into the IEventService and inspected the AccessTokenIssuedDetails but can't seen the Token Issued. Is this possible?

**Comment by leastprivilege** [comment]
You would need to emit your own event. Maybe in the token service - or token handle store.

**Comment by BillBakerAcmOrg** [comment]
Thanks, 
The goal is to log the tokens along with request, and then being able to correlate with log file from the Web API site which are logging requests.
 
I implemented the ITokenHandleStore. I'm able to see the token issued, and the request (HttpContext.Current.GetOwinContext().Request). The only thing I'm missing is the access to the hashed version of the token.

**Comment by leastprivilege** [comment]
Don't use HttpContext.Current - inject the OwinEnvironmentService instead.

I don't know what "The only thing I'm missing is the access to the hashed version of the token." means.

**Comment by BillBakerAcmOrg** [comment]
Thanks for the help and the time. I corrected my code to inject the OwinEnvironmentService, thanks.

In StoreAsync the key is ZTlEySihgkmardvLE_IF4Uqk3mowcFpRor9Bz9Ee75I, when it gets to the client its 173c5849c197df4491bebba81c8a3547. I'd like to log what the client receives from within StoreAsync.

**Comment by leastprivilege** [comment]
Ah I see - the store only sees them after being hashed. You want the token creation event to contain the actual token?

**Comment by BillBakerAcmOrg** [comment]
Yes, perhaps I'm looking in the wrong place?

**Comment by leastprivilege** [comment]
Don't know - need to have a look myself.

**Comment by BillBakerAcmOrg** [comment]
Thanks, I'll take a look at it.

**Comment by BillBakerAcmOrg** [comment]
Thanks @leastprivilege it works great!

**Comment by manojsitapara** [comment]
I have the same question as @BillBakerAcmOrg  asked

> In StoreAsync the key is ZTlEySihgkmardvLE_IF4Uqk3mowcFpRor9Bz9Ee75I, when it gets to the client its 173c5849c197df4491bebba81c8a3547. I'd like to log what the client receives from within StoreAsync.

Can you please help me how to store actual reference token into the database at StoreAsync() level?

**Comment by BillBakerAcmOrg** [comment]
If I recall correctly, implement the ITokenHandleStore and access the ReferenceTokenHandle as part of the StoreAsync parameters.

**Comment by manojsitapara** [comment]
@BillBakerAcmOrg Thanks for the answer, can you please help me how can I access?

> access the ReferenceTokenHandle as part of the StoreAsync parameters.

I have tried but didn't get success. It really helps if you can post sample code snippet.
