### ISSUE TITLE
2FA is a functionality in Identity Server level not in user service level.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3#2134]
I try to use 2FA  but any user service implementation have own logic.
In my opinion generating and sending 2FA code is responsibility of an Identity server.

**Comment by brockallen** [comment]
The problem is that IdSvr doesn't mandate the identity management piece, so it can't be what enforces things like 2fa.

**Comment by mikeandersun** [comment]
There is not need to IdentityServer force identity management, just check if the 'IUserService' detect that a user enabled 2FA then generate code and send it(may get another factors in future).
I think  something like `Get2FAStatusAsync` in 'IUserService' that return a `2FAConfiguration` result that contains the `2FaMethod` and `PhoneNumber` propertites. According to the result IdentityServer generate and send the code or get another factors from user.

**Comment by brockallen** [comment]
2fa can be implemented in many ways other than phone number. And this is why it gets complicated to define these semantics into IdSvr.

**Comment by mikeandersun** [comment]
"2fa can be implemented in many ways other than phone number."
And
one log of the the way should done in IdentityServer: **Getting the 2th factor**. I talking about it.
Nowadays the must popular is send and get a code and if any identity management provide a new mechanism that needs some side effect in IdentityServer. May be in `PostAuthenticateAsync` method.
Thanks a lot for attentions

**Comment by brockallen** [comment]
Sorry, we have no plans to change the boundaries between where IdentityServer stops and the specifics of the identity management library begins.
