### ISSUE TITLE
Unauthorize method in tokenclient when deploy in IIS local [question]

### ISSUE THREAD

**Issue by taufikfadjar** [IdentityServer/IdentityServer3#2136]
I am newbie here, please give me advice.. (my english is bad)
My problem, when i deploy in "IIS Express" and after successful login with credential then call method tokenClient.RequestAuthorizationCodeAsync , it work like a charm. But when deploy in "IIS local" binding by IP and after successful login then call method tokenClient.RequestAuthorizationCodeAsync it always return unauthorize. i am sure my RedirectUri, PostLogoutRedirectUris, and Identityserver url is correct.

my configuration IdSrv

<pre>
<code>
  app.Map("/identity", idsrvApp =>
            {

                var idSvrFactory = Factory.Configure("EOEntities");
                idSvrFactory.ConfigureUserService("EOEntities");

                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = ConfigurationIdsrv.Site.Name,
                    IssuerUri = ConfigurationIdsrv.Site.Issueruri,
                    SigningCertificate = LoadCertificate(),
                    RequireSsl = ConfigurationIdsrv.Site.SLL, // false ssl
                    Factory = idSvrFactory,
                });
            });
</pre>
</code>

my configuration parties

<code>
 // use the code to get the access and refresh token
                            var tokenClient = new TokenClient(
                                EofficeConstants.TokenEndpoint,
                                "idm",
                                "secretissecret");

                            var response = await tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);
                            var id = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType);

                            var userInfo = await EndpointAndTokenHelper.CallUserInfoEndpoint(response.AccessToken);
                            var roles = userInfo.Value<JArray>("role").ToObject<JToken>();
</code>

IIs Express
----------------------
Identityserver : http://localhost:44302/ ( Identityserver url )
app party : http://localhost:44302/admin ( RedirectUri, PostLogoutRedirectUris ) <--- Identitymanager

IIS Local
--------------------
Identityserver : http://192.162.1.102/ ( Identityserver url )
app party : http://192.162.1.102/admin ( RedirectUri, PostLogoutRedirectUris ) <-- Identitymanager

screenshot in iis express
<img src="http://i.imgur.com/TCIOCPl.png?1" />

screenshot in iis local
<img src="http://i.imgur.com/JX5fugW.png?1"/>

Please give me advice, Arigatou :dancer:

**Comment by brockallen** [comment]
Not sure. A guess might be when you change the host names you have a SSL problem due to an invalid matching SSL certificate.
