### ISSUE TITLE
ClaimsPrincipal & Custom Claims

### ISSUE THREAD

**Issue by smhinsey** [IdentityServer/IdentityServer3#2137]
Apologies if this is answered elsewhere, I wasn't having much luck with my search terms.

I have a setup that's integrating Membership Reboot and Identity Server. I added custom claims in a custom user service and if I hit the UserInfo endpoint, I can see them fine. However, if I drop an [Authorize] attribute onto a controller, I only see the "core" set of claims such as scopes and not my custom ones. Can you point me in the right direction for how to wire this up?

**Comment by brockallen** [comment]
I guess I don't follow... Authorize just checks IsAuthenticated and IsInRole.

**Comment by smhinsey** [comment]
Yeah, I left some details out. If you want to be able to check the claims in User (or Request.User, etc) you need to put the Authorize attribute on the action in order for it to be populated (I think this is the case at least). When you do, it populates with some of the claims but not all of them. For example, I have a valid authenticated ClaimsIdentity under User.Identity, but its Name property is null because the name claim wasn't present. If I look at the claims, I see the "core" set such as scope, but I don't see the custom claims I added via the user service which are visible if I hit the UserInfo endpoint. Does this help clarify things? 

What I'm doing is different, but the simplest possible use case of what I'm trying to attempt would be something like where you have a controller action which reads the User.Identity.Name property and puts it in the ViewBag so you could do something like have a "Hello, User!" message in your site's badge area.

**Comment by brockallen** [comment]
This is because you did not create the ClaimsIdentity and set the NameClaimType and RoleClaimType in the ctor. See out MVC samples -- they do this.

**Comment by smhinsey** [comment]
Do you mean like around line 79 here?
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs

I don't currently have a call to UseOpenIdConnectAuthentication at all, so
I'm guessing I'll need to add one.

**Comment by brockallen** [comment]
Yep, something like that. How do you do OIDC now if you don't use that middleware?

**Comment by smhinsey** [comment]
I'm doing resource owner with and auth IIS App has a call to
UseIdentityServer while my API IIS app has a call to
UseIdentityServerBearerTokenAuthentication with the Authority pointing at
the auth server. This seems to work with the exception of these missing
custom claims, but I could still definitely be doing it wrong as this is my
first time working with Identity Server. Should I have that call after all
or something?

**Comment by brockallen** [comment]
Is the claims issue in the client app or in the API?

**Comment by smhinsey** [comment]
Let me just lay it all out, hopefully this helps clarify.

1) www.myapp.local/auth <--  calls UseIdentityServer. The only interation
with this beyond the initial authentication is to hit the identity server
UserInfo endpoint, which returns the default set of claims plus my custom
claims as defined in the IUserService.

2) www.myapp.local/api <-- calls UseIdentityServerBearerTokenAuth. I can
place a controller here and it works with Authorize, but only returns the
default set of claims and not my custom ones.

3) www.myapp.local <--- javascript-only app which obtains a bearer token
from the auth site's token endpoint and passes them to the API via an HTTP
header.

**Comment by brockallen** [comment]
So it sounds like the claims problem is in the API layer? This is odd, since when our UseIdSvrBearerToken middleware runs, it creates the ClaimsIdentity with the "name" and "role" claim types. These are configurable, BTW, on the options.

**Comment by smhinsey** [comment]
If this helps, here's the auth server setup.

            var options = new IdentityServerOptions
            {
                SiteName = siteName,
                IssuerUri = issuerUri,
                PublicOrigin = publicOrigin,
                RequireSsl = false,

                SigningCertificate = getCert(),
                Factory = factory,
                Endpoints = new EndpointOptions()
                {
                    EnableUserInfoEndpoint = true,
                    EnableDiscoveryEndpoint = true,
                    EnableAuthorizeEndpoint = true,
                    EnableTokenEndpoint = true,
                    EnableTokenRevocationEndpoint = true
                },

            };

            app.UseIdentityServer(options);

and here's the API setup.

            app.UseIdentityServerBearerTokenAuthentication(new
IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = authority,
                // I started without the next two but tried to add them
with various values, maybe this is it?
                NameClaimType = ClaimTypes.Name,
                RoleClaimType = ClaimTypes.Role,
            });

the client app is JS-only so there's nothing to show for that one.

PublicOrigin, IssuerUri, and Authority are all the same values.

**Comment by smhinsey** [comment]
Actually, you can see the full source here.
https://github.com/smhinsey/Fulcrum/tree/master/seed Hard to get used to
actually being able to link directly to a public repo for an issue like
this.

**Comment by brockallen** [comment]
Ah that's your problem -- you explicitly set:
```
NameClaimType = ClaimTypes.Name, RoleClaimType = ClaimTypes.Role,
```
So it's doing what you told it to. Omit those and see if it works better for you.

**Comment by smhinsey** [comment]
Unfortunately, I started out without them and only added them just to see
if it'd help. I just double checked and removing them doesn't fix it.

Here's where I set up the claims in the service, if this adds any
additional info:
https://github.com/smhinsey/Fulcrum/blob/master/seed/SeedComponents/Components/UserAccounts/Domain/Services/AppUserService.cs?ts=2

**Comment by smhinsey** [comment]
Just throwing this out there in case it's useful, but here are the clients
and scopes. I think I have everything as wide open as possible so I don't
think that's the issue, but I don't really know.
https://github.com/smhinsey/Fulcrum/tree/master/seed/FulcrumSeed/Infrastructure/IdentityServer3

**Comment by smhinsey** [comment]
I was eventually able to track this down by looking at the source for DefaultClaimsProvider. I noticed that GetAccessTokenClaimsAsync filters to resource scopes only and I only had one scope of type ScopeType.Identity so once I added one of type ScopeType.Resource, I was good to go.
