### ISSUE TITLE
Navigating through different application

### ISSUE THREAD

**Issue by JulienC75** [IdentityServer/IdentityServer3#2138]
Hi,

We setup 1 IDSRV and an instance of a client MVC application.

The user is not authenticated and go to https://servername/application1/, 
He is redirected to https://servername/idsrv/identity/login?signin=...
He authenticates 
He is redirected back to the application
--> Works perfectly

The problem we have is that some users are creating shortcut to https://servername/application1/moduleA/ or will receive an email to invite them to connect to a specific module to perform some action

If the user is not authenticated, he is not redirected to https://servername/idsrv/identity/login?signin=...
but an authorization exception is thrown and a custom access forbidden page is displayed

The same issue occurs when user come from another application using same IDSRV.
If user goes to https://servername/application1 
there is a brief redirection to an URL like
https://servername/idsrv/identity/connect/authorize?clientid=...&redirect_uri=...&response_mode=form_post&response_type=code+id_token+token&scope=...&state=OpenIdConnect.AuthenticationProperties%3d-Nfx1...&nonce=63...

And it works perfectly.

But this call is not made when connecting to another route of the application (example: https://servername/application1/moduleA/).

How can I implement the behaviour where user is redirected to https://servername/idsrv/identity/login?signin=... or https://servername/idsrv/identity/connect/authorize?clientid=... when he tries to access a route requiring authentication in https://servername/application1/
?

Thanks,
Julien

**Comment by brockallen** [comment]
Is ~/moduleA a different application in IIS?

**Comment by JulienC75** [comment]
https://servername/application1 is one application in IIS 

I should have named /moduleA as /controllerA/action to be clearer, sorry

**Comment by brockallen** [comment]
So in short what happens is your app returns 401 and that causes the OIDC middleware to kick in. It stores away the current URL being requested so that once all the authentication is done the user is redriected back to the page they originally requested. This is all handled by the middleware, so I'm not sure why you're running into issues.

**Comment by JulienC75** [comment]
Thank you for your answer, after searching more deeply, since we are still in an internal test environment it may be the same as described in [issue 943](https://github.com/IdentityServer/IdentityServer3/issues/943)
I'm going to test it and keep you informed.

**Comment by brockallen** [comment]
Update?
