### ISSUE TITLE
When do stores get called?

### ISSUE THREAD

**Issue by hspeedy** [IdentityServer/IdentityServer3#2139]
After getting warnings about not configured stores like ITokenHandleStore, I decided to implement
them. I try to configure this stores, but nothing is called inside my implementation. Just the warnings
inside my log have gone.

factory.TokenHandleStore = new Registration<ITokenHandleStore>(typeof(MyTokenHandleStore));

Where can I find a description for this stores (what purpose they have) and when they will be used?

**Comment by brockallen** [comment]
They're called only if you're using certain flows (like code flow, or reference tokens).
