### ISSUE TITLE
Access to Http Request In Validate

### ISSUE THREAD

**Issue by rschenkel** [IdentityServer/IdentityServer3#2140]
Is there a way to get access to the Http request and incoming principal in the delegate when using basic authentication?

In the example below I would like access to the headers and principal in the Validate call:

        private static AuthenticationConfiguration CreateAuthenticationConfiguration()
        {
            var authentication = new AuthenticationConfiguration
                {
                    ClaimsAuthenticationManager = new AuthenticationManager(),
                    RequireSsl = true,
                    EnableSessionToken = true
                };

            authentication.AddBasicAuthentication(AuthenticationService.Validate, "localhost");

            return authentication;
        }

**Comment by leastprivilege** [comment]
wong repo.
