### ISSUE TITLE
Simultaneous logins

### ISSUE THREAD

**Issue by wtischer** [IdentityServer/IdentityServer3#2141]
First of all Awesome work!
I'm currently running Idsvr with MR and using implicit the flow.

Question: I have a requirement of preventing an user from having more than one active session. In such case, the first session token should be forced to expire (or revoked). I'm guessing that attempting to revoke the token when the login is successful, just prior to the emission of the new token should be enough. (right?)

I've looked at the documentation,the source, the samples and tried implementing ITokenHandleStore and IAuthorizationCodeStore (they don't get called as explained in another question) thus I'm still unsure where to make the proper call if its possible at all. 

Which interface should I be using to accomplish this with the Implicit flow?

Thanks for you help and effort!

**Comment by brockallen** [comment]
This is quite tricky and I suspect you're omitting all your requirements. Also, when you say above "first session token should be forced to expire" -- what do you really mean there? Are you talking about the cookie in the app? Or are you talking about an access token to an API.

I know my reply here isn't very satisfactory, but 1) I don't know fully how you're using IDSvr, so I really can't given an answer, and 2) usually when people ask this they've really not fully thought through the mechanics of everything. Once they understand the mechanics then a lot of the time requirements change :)

**Comment by wtischer** [comment]
Thanks for your prompt reply! ... I see now that my question was not as clear/detailed as my mind lead me to believe :)  

So, I have an SPA.. User Bob logs in on computer A, then goes to Computer B an logs in into the SPA. he did not logoff from the SPA on computer A. The requirement says he should not be able to use the SPA in computer A without login in again.  This implies, to the best of my limited knowledge of Idsrv, that at least the session state related to the login at computer A should be altered since i know that can be detected (JavaScript Implicit Client - TokenManager sample) and the SPA can automatically logout.  

My approach so far is that.. when Bob logs in to computer B the Userservice  does its validation and then it requests the token creation. At this point my mind leads me to believe that before the creation of the new tokens, any previous ones related to Bobs user id could be changed or deleted.  Can than be done if the ITokenHandleStore implementation is registered as a singleton? Is that the right interface for the job or is my mind playing tricks on me? :)

Right now I'm using the IdSvr with just one Client, the SPA, and one WebApi, all hosted on azure. The IdSvr is based on the MR sample. 

Again, Thanks for your time :)

**Comment by brockallen** [comment]
So how would SPA on computer A detect that bob logged into SPA on computer B? The token service knows, for certain, but how would SPA on computer A? Somehow SPA A would need to be in constant contact with IdSvr to ask if the same user has a newer login elsewhere.

Also, how would an API know that access tokens issued to SPA A are no longer valid, which SPA B are? What about access tokens issued to a mobile app unrelated to SPA A or B? At each API invocation the API would have to check if the user in the token has a newer login than the one that issued this token. Also, what about refresh tokens?

It's complicated and there's nothing built into IdSvr for this.

For the access tokens, you could possibly use reference tokens and then revoke all past reference tokens (maybe just for the same client) when a user logs in again. So maybe that's good enough?

**Comment by wtischer** [comment]
Yes, that is good enough :)  Thanks! 
 I could easy deal with the rejection response at the SPA end. 

I've implemented the ITokeService so i can add the line: 

await _tokenHandles.RevokeAsync(token.SubjectId, token.ClientId);

Just before the token creation for every login.
So far the testing has been satisfactory.
Thanks for your help and time!
