### ISSUE TITLE
Error: The remote name could not be resolved

### ISSUE THREAD

**Issue by khoainv** [IdentityServer/IdentityServer3#2142]
I using sample app "MVC Authentication" EmbeddedMvc with IdentityServer3 with Debug on Visual studio 2015 then Okay not error. But when run on server iis then error:
Can you help me. very thanks

Server Error in '/' Application.
The remote name could not be resolved: 'login.ugroup.vn'
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Net.WebException: The remote name could not be resolved: 'login.ugroup.vn'

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[WebException: The remote name could not be resolved: 'login.ugroup.vn']
   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +764
   System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +78

[HttpRequestException: An error occurred while sending the request.]
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__0.MoveNext() +365

[IOException: Unable to get document from: http://login.ugroup.vn:8080/core/.well-known/openid-configuration]
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__0.MoveNext() +734
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetAsync>d__0.MoveNext() +289
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__3.MoveNext() +915

[InvalidOperationException: IDX10803: Unable to create to obtain configuration from: 'http://login.ugroup.vn:8080/core/.well-known/openid-configuration'.]
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__3.MoveNext() +1267
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.OpenIdConnect.<ApplyResponseChallengeAsync>d__c.MoveNext() +727
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<ApplyResponseCoreAsync>d__b.MoveNext() +380
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<ApplyResponseAsync>d__8.MoveNext() +494
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<TeardownAsync>d__5.MoveNext() +218
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +975
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +202
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +774
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +870
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +202
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +193
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +96
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +363
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157

**Comment by brockallen** [comment]
Sounds like a DNS issue.

**Comment by khoainv** [comment]
If run with IdentityServer3: http://login.ugroup.vn:8080/core/ => not error. But when I intergrate with MVC Embedded: http://login.ugroup.vn:8080 then error as above.

Are you have solution?

**Comment by brockallen** [comment]
Perhaps because at startup time the metadata is trying to be loaded, but you're in the middle of loading the webserver so it can't be contacted. Just a guess.

**Comment by khoainv** [comment]
That means I'll have to wait for a host fix from IdentityServer3?

**Comment by brockallen** [comment]
What for? I don't think we know what your problem is.

**Comment by khoainv** [comment]
I run sample after with Visual studio 2015 debug = > not error.
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MVC%20Authentication

But, when I deploy on IIS Server windows server 2012 => error that i said

You can access https://login.ugroup.vn:89/
after click Login using Authorize then Error.

But if I access https://login.ugroup.vn:89/identity => okay not error

Can you deploy this sample and test? You will see bug.

**Comment by khoainv** [comment]
Okay, thanks brockallen,

i think, i'm have find problem of me. it is problem of DNS. Because LAN Network of me is UGroup.vn => run DNS Internet okay but Local call => missing login.ugroup.vn.

Solution: create one Host on LAN DNS is login => Okay.

**Comment by brockallen** [comment]
Sounds like you've fixed it.

**Comment by hbulens** [comment]
@khoainv I don't understand your proposed solution, could you elaborate on what you did exactly to solve this? I am facing a similar (if not the same) problems with this. There's heaps of information online but so far no results yet.
