### ISSUE TITLE
Separated all persistence class in to a new repository.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3#2143]
With separation all persistence class in to a new repository we have more flexibility to implementing Data layers for other database servers (e.g pgsql,mysql, ...) and with without force to use Entity Framework or MR.

**Comment by AlbertoLeon** [comment]
Is already separated. EF is in other repository. Can you be more exact in your words?

**Comment by mikeandersun** [comment]
IMO, what that an repository responsible to to is doing CRUD functions on the [entities](https://github.com/IdentityServer/IdentityServer3.EntityFramework/tree/master/Source/Core.EntityFramework/Entities). So why we have to add reference to all IdentityServer3 to a data layer project implementation?!

**Comment by brockallen** [comment]
But then IdSvr would need to reference it. We wanted IdSvr to be as self contained as possible.
