### ISSUE TITLE
Custom ViewService in ASP.NET 5 /MVC6

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3#2145]
[this](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNet5Host) helps me to host IdentityServer3 in Asp.net5 and it work fine.  But when I bring my custom PageAssets
it not work. it seems that assets not compile as resource in to DLLs. Am I right?

**Comment by leastprivilege** [comment]
I think there is an issue with the base path - it points to a different directory in asp.net 5.

**Comment by mikeandersun** [comment]
I think the PageAssets not compile as embed resource. There isn't this option in the properties window of VS 2015.

**Comment by jageall** [comment]
iirc you need to specify "resourceFiles":
["yourfilesordirectories","otherfilesordirectories"] in the project.json
file

see https://github.com/aspnet/Home/wiki/Project.json-file for more info
