### ISSUE TITLE
New example of an Angular Client Implicit Flow

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer3#2146]
I just created and new example of an Angular Implicit Flow client. If you want, I could add this to your samples repository. What do you think?

http://damienbod.com/2015/11/08/oauth2-implicit-flow-with-angular-and-asp-net-5-identity-server/

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow

Greetings Damien

**Comment by leastprivilege** [comment]
Thanks! I added a link to it to our docs.
