### ISSUE TITLE
Tokens and cookies lifetimes

### ISSUE THREAD

**Issue by mmihaylov** [IdentityServer/IdentityServer3#2147]
Hello, 

I am a bit confused about the correct lifetime settings. As far as I understand we have the following configuration places:

**1. Identity Server**
*1.1. Cookie options*
expire
sliding expiration
remember me duration

*1.2 Client Configuration*
id_token lifetime
access_token lifetime

**2. Client**
*2.1 Cookie middleware*
sliding expiration
expire

*2.2 Katana middleware*
UseTokenLifetime

If I set UseTokenLifetime = true, this means that IdSrv defines cookie and token lifetimes. Cookie middleware is not used. If I have id_token set to 5 minutes, does it mean that I have to login every 5 minutes?

Another way, if I set UseTokenLifetime = false, does it means that the authentication cookie is controlled by the client's cookie middleware?

I am trying to find out, what is the best setup in order to have a 10 hour long valid login.

**Comment by leastprivilege** [comment]
UseTokeLifetime = true ignores the cookie MW configuration and sets an absolute lifetime of the cookie that is equal to the id_token lifetime.

**Comment by mmihaylov** [comment]
Thank you Dominic, 

So if I want to use SlidingExpiration, I should set UseTokeLifetime = false and configure the Cookie MW?

Is it a bad practice to set id_token lifetime to 10 hours for example (with UseTokeLifetime = true). As far as I am familiar, id_token is used only at the begging while you the access_token.

**Comment by leastprivilege** [comment]
yes.

not bad practice - since the id_token has replay protection I don't see an issue.
