### ISSUE TITLE
Question: grant_type "urn:ietf:params:oauth:grant-type:saml2-bearer" support?

### ISSUE THREAD

**Issue by dariusdamalakas** [IdentityServer/IdentityServer3#2151]
Hi,

[rfc7522 (SAML 2.0 Profile for OAuth 2.0...) ](https://tools.ietf.org/html/rfc7522) is now a [Proposed Standard](http://www.rfc-editor.org/info/rfc7522). 

I have done some searching, and could not find that any work has begun on adding grant type `"urn:ietf:params:oauth:grant-type:saml2-bearer"` to IdSrv3. There is Saml2Bearer [in Constants.cs](https://github.com/IdentityServer/IdentityServer3/blob/fc21dad08533b96a6d8672f6bc594dd8694fb2bb/source/Core/Constants.cs#L127), so at least something to start :)

We are planning of adding this anyway, so we would want to contribute this back. I guess having a `IdentityServer3.Grants.Saml2Bearer` nuget package would work best here, as this is a non default OAuth2 grant.

Planing to implement this as a `ICustomGrantValidator`, as suggested in #162.

**Comment by leastprivilege** [comment]
OK. Cool. thanks for the heads up. 

Let us know once it is done so we can link to it from our docs.

**Comment by dariusdamalakas** [comment]
@leastprivilege, @brockallen 
Here's the [project](https://github.com/Intelliflo/IdentityServer3.Saml2BearerGrant). There is also a (nuget package](https://www.nuget.org/packages/IdentityServer3.Saml2Bearer/) published. There are some rough edges, but this is working and we will soon run this in production.

**Comment by leastprivilege** [comment]
Thanks - will link it from our resources pages.

In general - we would prefer to use "IdentityServer3.Contrib.*" as a naming convention.

**Comment by dariusdamalakas** [comment]
@leastprivilege, makes sense. 

I have renamed repository, the new address is now here: https://github.com/Intelliflo/IdentityServer3.Contrib.Saml2BearerGrant.  Old url should still work like a redirect.

I'll update nuget package some time later.

**Comment by leastprivilege** [comment]
Ok - thanks!

let me know when it is updated.

— 
cheers
Dominick Baier


On 20 January 2016 at 11:42:48, Darius (notifications@github.com) wrote:

@leastprivilege, makes sense.

I have renamed repository, the new address is now here: https://github.com/Intelliflo/IdentityServer3.Contrib.Saml2BearerGrant. Old url should still work like a redirect.

I'll update nuget package some time later.

**Comment by dariusdamalakas** [comment]
@leastprivilege. Renamed.   Nuget package [here](https://www.nuget.org/packages/IdentityServer3.Contrib.Saml2Bearer/)

**Comment by leastprivilege** [comment]
done. thanks!
