### ISSUE TITLE
Recommendations for upgrading ID3 from 1.6.x to 2.x

### ISSUE THREAD

**Issue by jprogers** [IdentityServer/IdentityServer3#2152]
Our company has been building new login logic based on IdentityServer3 for the last five months. We are nearing a major rollout of the next version of our medical software, with ID3 version 1.6.x included. Is there any reason we should hesitate to upgrade to version 2.x at this time? I have looked through all the published issues, and have not seen anything that would stop us, but I wanted to check with you. 

IdentityServer3 is great. And we really appreciate your help with this question.

**Comment by leastprivilege** [comment]
2.x is the recommended version!

**Comment by CrescentFresh** [comment]
Aside from namespace changes and of course interface changes (C# interfaces I mean) switching to 2.0 was pretty straightforward. The hardest part was reworking the interface implementations that we have, as they for example took slightly different arguments or returned slightly different types. That took about a day.

If you're going to upgrade it might be easier doing it now before going live with your next major rollout that afterwards.

**Comment by jprogers** [comment]
Thank you both for your comments! Much appreciated!

**Comment by dariusdamalakas** [comment]
We've done an upgrade 1 month ago as well, was quite straightforward, nothing major, no big headscratching.
