### ISSUE TITLE
Question about /permissions and a better EnableLocalLogin flag

### ISSUE THREAD

**Issue by CrescentFresh** [IdentityServer/IdentityServer3#2154]
Our idsvr3 is configured with n external providers (we have many integration!). Each client app are configured to allow only a subset of these providers.

Examp:
Full provider list supported by our idsvr: company A auth server, company B auth server

Client 1 IdentityProviderRestrictions: company A auth server
Client 2 IdentityProviderRestrictions: company B auth server

When users of client 1 app go to login they see username/password fields and a "Sign in with Company A" button.

When users of client 1 app go to login they see username/password fields and a "Sign in with Company B" button.

There are sly developers at company A who hit idsvr3's `/permissions` url directly: they see a login screen that lists all of the providers configured (company A and company B). 

The question then, is there anyway to either:
a) disable `/permissions`?
or
2) `EnableLocalLogin=true` only for oidc flows (authorization code, hybrid, etc)?

**Comment by brockallen** [comment]
a) yes -- endpoint settings
b) you can set caption to null on the external IdP owin middleware config -- the external IdP won't show in the login HRD screen
