### ISSUE TITLE
Two factor authentication using Resource Owner Password Credential flow

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3#2155]
Is there any way we can achieve  two factor authentication using Resource Owner Password Credential flow using IdSvr ?

**Comment by brockallen** [comment]
You'd have to build that all yourself.

**Comment by aaabdul** [comment]
Thanks. Do you have an example or document somewhere that I can refer to ? Or perhaps a hint on where to start ?





On Wed, Nov 11, 2015 at 1:17 PM -0800, "Brock Allen" <notifications@github.com> wrote:
You'd have to build that all yourself.

---

**Comment by brockallen** [comment]
No, sorry.
