### ISSUE TITLE
app.FormPostResponse.js as a separate http call

### ISSUE THREAD

**Issue by ankur--bhatia** [IdentityServer/IdentityServer3#2158]
Hi Guys,

Is there a reason why we do the form submit to the releying party using two http calls instead of just bundling all contents in one response.

Cheers
Ankur

**Comment by pvasek** [comment]
I guess it's because of CSP.

https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Introducing_Content_Security_Policy
> A CSP compatible browser will then only execute scripts loaded in source files received from those whitelisted domains, ignoring all other script (including inline scripts and event-handling HTML attributes).

**Comment by brockallen** [comment]
Yes -- CSP
