### ISSUE TITLE
Invalid documentation for Customizing Views

### ISSUE THREAD

**Issue by johnsmith9264** [IdentityServer/IdentityServer3#2160]
Text: 
HTML customization
Replacing entire views

The DefaultViewService does allow for the HTML to be customized. The default views can be "overridden" by creating HTML files within an **assets** folder within the hosting applications base directory. 

Should be: not **assets** folder, but **templates** folder

**Comment by leastprivilege** [comment]
then change it...

**Comment by johnsmith9264** [comment]
Someone have just changed it...
