### ISSUE TITLE
Is Remeber Two factor authentication possible?

### ISSUE THREAD

**Issue by SathishN** [IdentityServer/IdentityServer3#2161]
I got the 2 factor authentication working using custom user service and custom view in the samples.

I want to provide an option for users to authorize the computer to remember two factor authorization, so that next time they don't need to go through two factor authentication. 

How can I do that?

any help would be appreciated.

thanks

**Comment by AnEmptyReece** [comment]
I did it by simply setting a protected cookie at identity server (that expires in 30 days, for example) and then checking for it before prompting the user with 2fa.

**Comment by brockallen** [comment]
Yea, this is something you need to manage yourself much like @AnEmptyReece suggested.

**Comment by SathishN** [comment]
Thanks for the workaround @AnEmptyReece and @brockallen.
My main goal was to make it easy as it's in Aspnet Identity implementation(using CookieAutentication).
Otherwise I need to look at options to secure the cookie.

**Comment by SathishN** [comment]
Ideally, 

I want to use the CookieAuthenticationMiddleware and CookieAuthenticationHandler to handle the TwoFactorRemember cookie as it's being handled by AspNet Identity,

E.g:
In my TwoFactorVerifyController, 

```
if (remeberMe)
{
	var rememberBrowserIdentity = context.Authentication.CreateTwoFactorRememberBrowserIdentity(user.Id.ToString());
	context.Authentication.SignIn(new AuthenticationProperties() {IsPersistent = true}, rememberBrowserIdentity);
}

var resumeUrl = userIdentity.FindFirst(Constants.ClaimTypes.PartialLoginReturnUrl).Value;

//Pass the control back to IdSvr
return Redirect(resumeUrl);
```
When I debug into IdSvr, AuthenticationController.cs,
Following method 
```
public async Task<IHttpActionResult> ResumeLoginFromRedirect(string resume)
```
in turn calls

```
IssueAuthenticationCookie(signInMessageId, authResult, rememberMe);
```
in there
```
var id = authResult.User.Identities.First();
.
.
context.Authentication.SignIn(props, id);
```
I guess this ignores my custom the TwoFactorRemember cookie authentication.

Is there a way to work around to include my custom signin as well?

**Comment by brockallen** [comment]
Why don't you check this in your user service? Inject the OwinEnvironmentService into the ctor then you can call any of your OWIN/Katana authentication APIs to check the incoming cookie.
