### ISSUE TITLE
EntityFramework namespace dependency on Core.Models namespace

### ISSUE THREAD

**Issue by Selvaticus** [IdentityServer/IdentityServer3#2168]
Hi,

Is there any reason to have the **_IdentityServer3.EntityFramework_** depend on the **_IdentityServer3.Core.Models_** namespace? Namely on enums.

For instance, the class _Client_ on **_IdentityServer3.EntityFramework_** depends on the _Flow_ enum and _AccessTokenType_ enum, from the **_Core.Models_** namespace.

This dependency makes it impossible to test the Stores by the way of mocking the DbContext, without adding a dependency for the **_IdentityServer3 nuget_**. This is not ideal for test projects or even DAL layers. If we were to use in memory data, by the way of an InMemory DbContext (i.e. a Mock) the same would happen as above.

Other way this may impose constraints is if one would want to move the InMemory data to another library/project, that project would need a dependency to the **_IdentityServer3 nuget_**, even tough it's only job is to provide data.

My question is: Will this dependency be removed in the future? Or is there another way to achieve what I described above, that I'm maybe missing?

PS: Good job with the framework, it's really good.

**Comment by brockallen** [comment]
EF needs the core project because it's converting DB entities into Core models.

**Comment by Selvaticus** [comment]
Ok, makes sense.

So every data layer using a different data framework (NHibernate, Dapper, etc) will need a dependency to the entire IdentityServer3 nuget, in order to convert DB entities into the core models. Is this right?

If this conversion was abstracted by interfaces, the dependency could be broken, and this two different components decoupled.

Is this something you see could happen in the future, or isn't worth the effort?

**Comment by leastprivilege** [comment]
I don't think it is worth the effort.

**Comment by Selvaticus** [comment]
Ok, thank you.
