### ISSUE TITLE
BearerTokenAuthentication in old .ashx file

### ISSUE THREAD

**Issue by kylegalbraith** [IdentityServer/IdentityServer3#2169]
This is a rather bizarre question, but I want to throw it out there and see if there are some other ideas people may have regarding this. We have an older application that is using a .ashx file to process requests. It has a dictionary of key value pairs that are regex to some kind of handler. When a regex is matched it calls a process request that does the work for that particular endpoint.

I want to add bearer token authentication to this and honestly I am not seeing how I can do that without converting this whole thing into a Web API OWIN application. It seems I can add a Startup file and the necssary IdSvrAuthentication setup, but then it is not clear I can add ```[Authorize]``` as I have no controller to work with.

Has anyone come across doing this? Do I need to convert over to Web API or is there a way I can handle this as is. I know this is a bizarre question, so I am really after some feedback on how/if this can be done without a lot of rework.

**Comment by uncleyo** [comment]
If you configure OWIN with RAMMFAR and all the good stuff in your asp.net application, and use https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation middleware, then by the time execution flow will reach your IHttpModule.ProcessRequest, you'll have context.User properly populated and you can simply check authentication status and any claims you need.

**Comment by kylegalbraith** [comment]
We are taking a little bit of a different approach as we get the token off the request and then ask the IdSvr accesstokenvalidation endpoint if it is valid. Is this a valid way to check that the token on the request is legitimate?

**Comment by uncleyo** [comment]
Probably it is valid, but more error prone.
Also, AccessTokenValidation middleware properly caches validation results out of the box, which is nice.
My personal preference is to force remote validation in the configuration instead of the default "both", because then it doesn't try to read the discovery document at startup.

**Comment by brockallen** [comment]
@kylegalbraith all set on this issue?

**Comment by kylegalbraith** [comment]
Yes we are all set. Making use of the token validation endpoint on IdSvr gives us the ability to wiggle this into this ashx file until we can convert this whole thing over to Owin.
