### ISSUE TITLE
Inject middleware with PluginConfiguration

### ISSUE THREAD

**Issue by Sunzhuokai** [IdentityServer/IdentityServer3#2171]
When i use PluginConfiguration to inject a middleware the pipeline stage is MapHandler,it's not the default stage because the UseEmbeddedFileServer method change the stage. I think should put the PluginConfiguration after the UseEmbeddedFileServer method.then the middleware can use in default stage

**Comment by brockallen** [comment]
Can you explain a little more the problem?

**Comment by Sunzhuokai** [comment]
I want to inject a owin middleware to check the Session,So I use the PluginConfiguration just like the below code

```csharp
identityServerOptions.PluginConfiguration = CheckSomethingInSession;


private void CheckSomethingInSession(IAppBuilder app, IdentityServerOptions options)
        {
            app.Use((context, next) =>
            {
               // the HttpContext.Current.CurrentNotification is MapHandler so the  Session is null
                var value= HttpContext.Current.Session["test"];

                // some codes

                 // the HttpContext.Current.CurrentNotification is MapHandler so the  Session is null
                HttpContext.Current.Session["test"]=DateTime.Now.ToString();
                return next();
            });
        }
```
As we know a owin middleware in the IIS integrated pipeline run at  `PreHandlerExecute` stage by default,and `Session`  initialization at `AcquireState` stage.[article](http://www.asp.net/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline)

We  can mark OMCs to execute at specific stages of the pipeline by using the 'IAppBuilder UseStageMarker()' extension method. 
the IdentityServer3 use this method in  'UseEmbeddedFileServer' extension method so the middlewares  registrated prior to ‘app.UseEmbeddedFileServer()’ are marked to execute at 'MapHandler' stage.

I think  should put the 'PluginConfiguration'  after the 'UseEmbeddedFileServer' then the middleware injected can execute at defalut stage

**Comment by leastprivilege** [comment]
Have you actually tested - e.g. with the ws-fed plugin. any issues? Or e.g. setting the pipeline marker yourself?

**Comment by leastprivilege** [comment]
we can probably move the embedded file system up - have you tried that ?

**Comment by Sunzhuokai** [comment]
I just tested put the 'PluginConfiguration' after the 'UseEmbeddedFileServer' and it works well,I can get the ‘Session’,but I didn't test others aspect

**Comment by brockallen** [comment]
Ok, I moved the static filesystem MW earlier in the pipeline -- please test on the nightly feed and let us know how it works.
