### ISSUE TITLE
Internal `CorsPolicyProvider` should take `publicOrigin` in consideration

### ISSUE THREAD

**Issue by nenadvicentic** [IdentityServer/IdentityServer3#2172]
Hi Brock,

Shouldn't `IdentityServer3.Core.Configuration.Hosting.CorsPolicyProvider` take in consideration `IdentityServer3.Core.Configuration.IdentityServerOptions.PublicOrigin` property?

When IdentityServer sits behind load balances with certificate offloading requests from outside (`https://host` -> `http://host`) are detected as CORS. 

This is current code in `v2.1.1`:

    public async Task<System.Web.Cors.CorsPolicy> GetCorsPolicyAsync(IOwinRequest request)
    {
        var path = request.Path.ToString();
        var origin = request.Headers["Origin"];

        // see if the Origin is different than this server's origin. if so
        // that indicates a proper CORS request
        var thisOrigin = request.Uri.Scheme + "://" + request.Uri.Authority;
        if (origin != null && origin != thisOrigin)
        {

 

I guess it should be something around these lines:

        var publicOrigin = request.Environment.GetIdentityServerHost();
        var thisOrigin = publicOrigin ?? request.Uri.Scheme + "://" + request.Uri.Authority;

or perhaps checking request origin against both public and current request host?

Thanks,
Nenad

**Comment by brockallen** [comment]
Yes, good idea. I'll look into this.

**Comment by brockallen** [comment]
Fixed on dev. Thanks.

**Comment by nenadvicentic** [comment]
Thank you!
