### ISSUE TITLE
Q: Multi tenancy by switching database(s) per request

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3#2173]
Want to run this by you, before going in perhaps a doomed from the start direction...

My boss had this idea for doing multi-tenancy with IdSrv3:
1.Keep a single instance of IdSrv3 with the EF backing and have a different set of configuration (Client, Operational, Scope & Users) databases for each tenant.
2. At run-time, per request, get the right "db connection" pass it over to IdSrv to serve the request according to these settings.

This is the high level idea. In an essence - use "connection strings switching" to achieve multi tenancy.

Right away the obvious issues are that  both the "connection string" and the external providers config are used when OWIN pipeline is being wired up. Any way to get them injected at runtime, per request?

**Comment by Peperud** [comment]
Yeah, switching the "connection string" per request looks doable. 
External providers aside, I wonder how/what other things will be affected though - like caching for example. 
Another thing that comes to mind is the metadata - say we have the tenants connect to their own subdomain based urls, like tenant1.IdSrv3Rocks.com, tenant2.IdSrv3Rocks.com, 
What would then be the best way to handle metadata generation to match the client urls? Is there an  extensibility point for this?

**Comment by brockallen** [comment]
Well, most people only do the switching for the user service and/or for the view service. They tend to keep the same scopes/clients across tenants. But you're right -- some of our caching keys off oc client ids, so if those were also multi-tenant then in theory you'd get cache hits. I guess you'd need to plug in your own caching that was tenant aware.

The metadata is generated dynamically based upon the incoming host name.

**Comment by Peperud** [comment]
@brockallen 
Thanks Brock, appreciate the thoughts!

> The metadata is generated dynamically based upon the incoming host name.

Unless load balancing is somehow done at dns level, this won't do much good and the "public origin" concept will has to be used, but it is a single constant value.

**Comment by brockallen** [comment]
If you need it dynamic, then set it into the OWIN environment from middleware you put in front of IdSvr. I guess your proxy server passes the host name across somehow?

**Comment by Peperud** [comment]
@brockallen 

If public origin is not set, the urls in the metadata do get generated, based on the incoming url from the request, except for the issuer. It gets stuck with whatever was the first url used (after the app domain got up I guess). Looks like a bug to me.

**Comment by brockallen** [comment]
I'm suggesting to change the incoming host header in your middleware in front of IdSvr.

**Comment by Peperud** [comment]
@brockallen 
I got that, but not sure how it applies to my last comment. 
Say I have **tenant1.myauthserver.com** & **tenant2.myauthserver.com**
Lets take an eventual load balancer proxy (that may change the host header) out of the picture. Say they all resolve by dns/hosts file to a single IIS hosted instance of IdSrv3, which does not have the public origin set and therefore will generate metadata urls based on the incoming request.

If I navigate first to (assuming IdSrv is on the *"identity"* route)  **https://tenant1.myauthserver.com/identity/.well-known/openid-configuration**, then everything in the metadata points to **tenant1**
But If I go next to **https://tenant2.myauthserver.com/identity/.well-known/openid-configuration** the metadata urls all point to **tenant2**, except the ***issuer*** is still ***"https://tenant1.myauthserver.com/identity"***

```json
{
    "authorization_endpoint": "https://tenant2.myauthserver.com/identity/connect/authorize",
    "check_session_iframe": "https://tenant2.myauthserver.com/identity/connect/checksession",
    "claims_supported": [
        "openid"
    ],
    "end_session_endpoint": "https://tenant2.myauthserver.com/identity/connect/endsession",
    "grant_types_supported": [
        "authorization_code",
        "client_credentials",
        "password",
        "refresh_token",
        "implicit"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "issuer": "https://tenant1.myauthserver.com/identity",
    "jwks_uri": "https://tenant2.myauthserver.com/identity/.well-known/jwks",
    "response_modes_supported": [
        "form_post",
        "query",
        "fragment"
    ],
    "response_types_supported": [
        "code",
        "token",
        "id_token",
        "id_token token",
        "code id_token",
        "code token",
        "code id_token token"
    ],
    "revocation_endpoint": "https://tenant2.myauthserver.com/identity/connect/revocation",
    "scopes_supported": [
        "email",
        "pay_scan"
    ],
    "subject_types_supported": [
        "public"
    ],
    "token_endpoint": "https://tenant2.myauthserver.com/identity/connect/token",
    "token_endpoint_auth_methods_supported": [
        "client_secret_post",
        "client_secret_basic"
    ],
    "userinfo_endpoint": "https://tenant2.myauthserver.com/identity/connect/userinfo"
}
```

**Comment by brockallen** [comment]
I think the issuer problem was fixed here: https://github.com/IdentityServer/IdentityServer3/issues/1619

It will be out in the next week as build 2.2.

**Comment by Peperud** [comment]
Sounds like it. Thanks.
