### ISSUE TITLE
Custom mobile Login UI

### ISSUE THREAD

**Issue by anthonyresq** [IdentityServer/IdentityServer3#2176]
We want to make a custom mobile UI instead of using the idsrv3 UI in the browser. Only local logins will be allowed

We have thought about using the resource owner flow, but that is only supposed to be used in a secure environment. Would the following scenario be considered secure, and if not how do we tweak things to make it secure?

## During registration of user
* Mobile device is assigned a unique id
* User is sent a one time pin
* User account is then created
* User is linked to the mobile device's unique id on the server

### On the mobile
* User enters username/password
* Credentials, along with the device's unique id are sent over https to an API

### On the API (Option 1)
* Using the Resource Owner Flow
* User credentials are used along with client_id and secret to authenticate user and retrieve the access token
* The token is interrogated to retrieve the subject_id
* The subject_id and device's unique id are validated to see if there is a link
* The token is then returned to the mobile phone

### On the API (Option 2)
* Using the Implicit Flow
* Simulate the browser login using [HttpClient](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx)
* fetch the login form
* get the anti forgery token out of the form
* post the anti forgery token along with the username/password in the form
* retrieve the access and identity tokens from the URL
* The token is interrogated to retrieve the subject_id
* The subject_id and device's unique id are validated to see if there is a link
* The token is then returned to the mobile phone

**Comment by leastprivilege** [comment]
Why do you want to use idsrv at all?

**Comment by anthonyresq** [comment]
Because we have multiple clients and we want to use single sign-on between our systems. The token returned to the mobile phone will be used grant access to other resources i.e. azure storage to upload photos.

If you have a better suggestion for a custom mobile login UI  that authenticates against idsrv I would love to hear it.

**Comment by brockallen** [comment]
It really sounds like you have requirements that are beyond what OIDC/OAuth2 are designed for. You can certainly use IdSvr to cover the protocol pieces, but you might need to do additional custom work to achieve what you need/want. It also sounds like you might want consulting support.
