### ISSUE TITLE
Custom ASP.NET MVC Register Page - Using GetLinksFromProviders for Social Logins

### ISSUE THREAD

**Issue by woodwardmatt** [IdentityServer/IdentityServer3#2177]
**Backstory**: I've setup Identity Server (along with MembershipReboot) successfully and have added some custom ASP.NET MVC Controllers / Views (within the same OWIN pipeline) to accommodate all identity related functions (e.g. registering, verifying emails, resetting passwords). So far, so good.

**Question**: I've created a custom Register page in place of the original 'Welcome' page for identity server and wanted to include the links for External Providers. Having scoured the [InternalOwinExtensions.cs](https://github.com/IdentityServer/IdentityServer3/blob/a6e2b6bdfd1516af6cd9fdc9f46a08bb23bb553e/source/Core/Extensions/InternalOwinExtensions.cs) (line: 108) I can see that the existing (inbuilt) login pages use the "GetLinksFromProviders" method.

Is there anyway of cleanly being able to access this routine to mimic the LoginPageLinks for the External Providers used on the (inbuilt) login pages, on my MVC pages?

**R and D**: To try and attempt this, I've essentially had to grab the following methods from the same InternalOWINExtensions.cs code and create a new class:

        public static IEnumerable<LoginPageLink> GetLinksFromProviders(IOwinContext context, string signInMessageId)
        {
            if (context == null) throw new ArgumentNullException("context");

            var types = GetExternalAuthenticationProviders(context);

            if (types != null)
            {
                return types.Select(p => new LoginPageLink
                {
                    Type = p.AuthenticationType,
                    Text = p.Caption,
                    Href = GetExternalProviderLoginUrl(context, p.AuthenticationType, signInMessageId)
                });
            }

            return Enumerable.Empty<LoginPageLink>();
        }

        public static IEnumerable<AuthenticationDescription> GetExternalAuthenticationProviders(IOwinContext context, IEnumerable<string> filter = null)
        {
            if (context == null) throw new ArgumentNullException("context");

            var types = context.Authentication.GetAuthenticationTypes().Where(x => !Constants.IdentityServerAuthenticationTypes.Contains(x.AuthenticationType));

            if (filter != null && filter.Any())
            {
                types = types.Where(x => filter.Contains(x.AuthenticationType));
            }

            return types;
        }

        public static string GetExternalProviderLoginUrl(IOwinContext context, string provider, string signinId)
        {
            if (context == null) throw new ArgumentNullException("context");
            if (String.IsNullOrWhiteSpace(provider)) throw new ArgumentNullException("provider");
            if (String.IsNullOrWhiteSpace(signinId)) throw new ArgumentNullException("signinId");

            return context.Environment.GetIdentityServerBaseUrl() + Constants.RoutePaths.LoginExternal + "?provider=" + provider + "&signin=" + signinId;
        }

I've then had to start hacking around the SignInRequests a little to create a SignInMessageId for this, which probably warrants a separate question on how best to manage SignInRequests (and extract the Message Id). I've got it working, but its starting to feel way to messy on my part and I figured it was worth asking the question before I continued with this approach.

@brockallen / @leastprivilege - Can you give me any pointers guys?

**Comment by leastprivilege** [comment]
Keep in mind that IdSrv is "authentication as a service" - you might be overdoing that a bit.

That said - `Request.GetOwinContext().Authentication.GetAvailableAuthenticationMethods()` (or similar) might be your friend.

**Comment by woodwardmatt** [comment]
Thanks for the feedback @leastprivilege :) 

(*Noted on the AaaS front. This implementation is for a brand new product, so I figured these functions have to be implemented somewhere, and in my mind they fitted best alongside the Identity features already provided by IdSrv - especially when undertaking the register & login (in one step) and cookie-sharing requirements. Still very much finding my way though!*)

Was the method you were referring to:

`Request.GetOwinContext().Authentication.GetAuthenticationTypes()`

If so, I reckon I'd end up recreating the above code as I'd need to filter it etc. to get the external types, then would need to cater for the SignInRequests too.

Only other thought I had was whether the `GetLinksFromProviders()` in InternalOwinExtensions.cs (line: 108) could be made available through `IdentityServer3.Core.Extensions`? But I don't know how viable a move that is, or what it would impact for the remainder of the IdSrv. On face value it would seem non-contentious to surface up these LoginPageLinks?

**Comment by Moonsk313** [comment]
Hi @leastprivilege,

I would like to re-open the topic, actually I'm facing the similar "issue"... 
I have a registration page in MVC where I want to display External providers (the same way than the login page).
But I can't fin a way the retrieve Links from external Providers.
It works well on my login page, so my configurations are correct..

The idea to surface up the LoginPageLinks as mentionned @woodwardmatt or making the GetLinksFromProviders available in some service would make the work...

However, if you have any other suggestion, I'll be glad to get it :)

@woodwardmatt: how did you do to get the signInMessageId?

Thanks

**Comment by brockallen** [comment]
Check the OWIN environment extensions we support: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by woodwardmatt** [comment]
@Moonsk313 sorry for the late reply, I ended up implementing a few routines to achieve the social logins. What it came down to for me was actively managing the signinmessageid in my basecontroller (where required).

Not my favourite piece of code but to get at the signinmessageid so that I could use this, I used the following routine:

        private string CreateSignInId()
        {
            //Create new Sign In Request
            var url = Request.GetOwinContext().Environment.CreateSignInRequest(new SignInMessage { ReturnUrl = Constants.ApplicationUrls.Home, ClientId = Constants.ApplicationClients.Mvc });

            //TODO: Find better way of achieving this (if it works)
            //"https://localhost:44301/login?signin=dbddd3a8f556e481773b9c2db93b42be"
            var signin = url.Split(new string[] { Constants.ActionParameters.SignIn + "=" }, StringSplitOptions.RemoveEmptyEntries).Last();

            //Add to Cookie
            Response.Cookies.Add(new HttpCookie(Constants.ActionParameters.SignIn, signin));

            return signin;
        }

Give me another shout if you need me to elaborate :) Hope that helps :)

**Comment by Moonsk313** [comment]
Thanks for your answer @woodwardmatt 

It looks that's a good start, but I have another problem..
In my MVC, my owin environment is not totally complete.
those (in the image) are missing from my environment
![image](https://cloud.githubusercontent.com/assets/15340228/11625348/afe13cd8-9cda-11e5-9c9d-a1b2a607c6be.png)
(I get those from my login page)

Should I must add something in the routing or else?

Thanks ;)
