### ISSUE TITLE
Retrieving claims from userinfo in resource owner password credentials flow

### ISSUE THREAD

**Issue by urbanhusky** [IdentityServer/IdentityServer3#2183]
Hi,

I'm using resource owner password credentials flow to support web-clients logging into a web-based application (ASP.NET MVC, WebAPI consuming WCF services). The application used forms authentication before.

I've set up the IdentityServer like so:

Clients: 
```
// human is involved
new Client
{
		ClientName = "Silicon on behalf of Carbon Client",
		ClientId = "carbon",
		Enabled = true,
		AccessTokenType = AccessTokenType.Reference,

		Flow = Flows.ResourceOwner,
		
		ClientSecrets = new List<Secret>
		{
				new Secret("21B5F798-BE55-42BC-8AA8-0025B903DC3B".Sha256())
		},

		AllowedScopes = new List<string>
		{
				"api1", 
				"openid",
				"roles",
				"profile", "email"
		},

		Claims = new List<Claim>()
		{
				new Claim(ClaimTypes.Role, "humanClientRole")
		},
		AlwaysSendClientClaims = true,
}
```

Scopes:
```
public static List<Scope> Get()
{
		var scopes = new List<Scope>
		{
				new Scope
				{
						Name = "api1",
						Type = ScopeType.Resource,
						IncludeAllClaimsForUser = true,
						Claims = new List<ScopeClaim>()
						{
								// List of user claims that should be included in the access token
								new ScopeClaim() { Name = Constants.ClaimTypes.Email, AlwaysIncludeInIdToken = true },
								new ScopeClaim() { Name = Constants.ClaimTypes.Role, AlwaysIncludeInIdToken = true },
						},
				}
		};

		scopes.AddRange(StandardScopes.All);

		return scopes;
}
```

Users:
```
public static List<InMemoryUser> Get()
{
		return new List<InMemoryUser>
		{
				new InMemoryUser
				{
						Username = "bob",
						Password = "secret",
						Subject = "1"
				},
				new InMemoryUser
				{
						Username = "alice",
						Password = "secret",
						Subject = "2",
						Claims = new List<Claim>
												 {
														 new Claim(ClaimTypes.NameIdentifier, "alice"),
														 new Claim(ClaimTypes.Email, "alice@mailinator.com")
												 }
				}
		};
}
```

Actual test-client (mostly code from the ropc client with userinfo):
```
static void Main(string[] args)
{
		Console.ReadLine();
		var response = RequestToken();
		ShowResponse(response);

		GetClaims(response.AccessToken);
		Console.ReadLine();
}

static TokenResponse RequestToken()
{
		var client = new TokenClient(
				"https://localhost:44333/connect/token",
				"carbon",
				"21B5F798-BE55-42BC-8AA8-0025B903DC3B");

		return client.RequestResourceOwnerPasswordAsync("alice", "secret", "openid email api1").Result;
}

static void GetClaims(string token)
{
		var client = new UserInfoClient(
				new Uri("https://localhost:44333/connect/userinfo"),
				token);

		var response = client.GetAsync().Result;
		var identity = response.GetClaimsIdentity();

		"\n\nUser claims:".ConsoleGreen();
		foreach (var claim in identity.Claims)
		{
				Console.WriteLine("{0}\n {1}", claim.Type, claim.Value);
		}
}
```

The only claim I get is sub:
```
Token response:
{
  "access_token": "8dfde531e08e7cc64ab4b0997154777c",
  "expires_in": 3600,
  "token_type": "Bearer"
}


User claims:
sub
 2
```
I guess I'm getting something wrong here but I'm out of ideas at this point.

**Comment by brockallen** [comment]
ClaimTypes.Email != Constants.ClaimTypes.Email

**Comment by urbanhusky** [comment]
Thanks - what are these used for respectively?
This at least yields the profile-related claims, but not custom claims - unless I specify an identity scope in which I define these claims.

**Comment by brockallen** [comment]
Also, if you want claims from the profile endpoint those have to be requested as identity scopes, not resource scopes. Resource scopes are for the web api, identity scopes are for the client app.

**Comment by urbanhusky** [comment]
Okay, using identity scopes and Constants.ClaimTypes.* instead of ClaimTypes.* works :)

Could you explain what the difference between resource and identity scopes is, or at least where I could read up on that? (I tried https://identityserver.github.io/Documentation/docsv2/configuration/scopesAndClaims.html but that didn't help me much).

**Comment by brockallen** [comment]
Maybe this helps: https://identityserver.github.io/Documentation/docsv2/overview/terminology.html

**Comment by urbanhusky** [comment]
Hm, so I would need both an identity and resource scope - one to carry the information about the user and one to restrict access to the APIs. Let me guess, UseIdentityServerBearerTokenAuthentication can check the tokens for being issued for the resource scope, while any further authorization (e.g. claims-based) could use the claims from the identity?

**Comment by brockallen** [comment]
Since you have 2 different places where the claims are needed (client and api), then yes - you need 2 different scopes for those targets. The UseIdentityServerBearerTokenAuthentication will validate the access token and the claims from the token are set into the ClaimsPrincipal that's accessible from the User in your Web API code. It will also check for the required scopes, but any authorization beyond that is up to your code, yes.

**Comment by urbanhusky** [comment]
Okay, that has helped me a lot, thanks.

I would have some more related questions though that I haven't been able to answer - should I post them here or elsewhere?

The questions would be:
I have an ASP.NET MVC and Web API application, both hosted in the same app. If I UseIdentityServerBearerTokenAuthentication and set a required scope, then no logged in user can access anything (I get a 403 with insufficient_scope). Login happens through MVC against the IdentityServer and I UseCookieAuthentication. My client is essentially an angularjs application provided through Razor views (used as a template engine for I18N etc.), migrating from forms auth.
I access the userinfo endpoint to gather the claims and save that information in the ClaimsIdentity:
``` 
var id = new ClaimsIdentity(claims, "Cookies");
Request.GetOwinContext().Authentication.SignIn(id);
```
To me, this means that the token is validated when I request it - but not afterwards. So the cookie could, in theory, contain any old information or the access token could expire and I would not notice it - because the cookie authentication is still valid.

Q: What would be the correct way to validate the (reference) token?

Q: Authorization should be possible by defining a claimsAuthenticationManager in the web.config and using a ClaimsAuthorize-attribute, or am I wrong there?

Q: Where would be the best place to implement sliding expiration on the access token? I already request a refresh token which I could use to request a new access token. I keep both tokens and the expiration time in the claims.

**Comment by brockallen** [comment]
new questions should be in new issues. also, search the issues history -- they might already be answered

**Comment by urbanhusky** [comment]
Okay, will do. Thanks again
