### ISSUE TITLE
What stores use in-memory defaults?

### ISSUE THREAD

**Issue by neilcrowther** [IdentityServer/IdentityServer3#2184]
I'm implementing default stores that just throw "not-implemented" exceptions to ensure that we don't accidentally use a store in-memory that works during development but causes problems when run on a web-farm.  After looking at https://identityserver.github.io/Documentation/docsv2/ef/operational.html I had the following:

    var factory = new IdentityServerServiceFactory
    {
        UserService             = new Registration<IUserService, UserService>(),
        ClientStore             = new Registration<IClientStore, ClientStore>(),
        ScopeStore              = new Registration<IScopeStore, ScopeStore>(),
        AuthorizationCodeStore  = new Registration<IAuthorizationCodeStore, AuthorizationCodeStore>(),
        RefreshTokenStore       = new Registration<IRefreshTokenStore, RefreshTokenStore>(),
        TokenHandleStore        = new Registration<ITokenHandleStore, TokenHandleStore>(),
        ConsentStore            = new Registration<IConsentStore, ConsentStore>()
    };

with the first three being proper implementations and the last four just throwing exceptions if called.  Are there any other stores I should be implementing if planning to deploy to multiple servers?  Or is there any documentation on other "gotchas" for web farms?

**Comment by brockallen** [comment]
I think you have the right ones covered.

**Comment by neilcrowther** [comment]
Brilliant, thanks very much.
