### ISSUE TITLE
External IdP fails after upgrade 1.6.2 -> 2.1.1 ??

### ISSUE THREAD

**Issue by synesthesia** [IdentityServer/IdentityServer3#2185]
I had a working system on Identityserver3 1.6.2, with login working from internal identities and externally against Windows Azure Active Directory.

I updated to 2.1.1, made the necessary code changes to build, migrated the database and added the new data needed in Clients tables.

But now external login fails. From the logging the code gets to [the Authentication challenge in AuthenticationController](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/AuthenticationController.cs#L321), but nothing ever returns - the browser receives the 401 but never gets re-directed to the external provider.

My external Idp config (with an added delegate for some logging)  is:

```
    private static  void ConfigureExternalIdentityProviders(IAppBuilder app, string signInAsType)
        {
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "WAAD",
                Caption = "My Caption",
                SignInAsAuthenticationType = signInAsType,
                ClientId = ConfigurationHelper.ClientId,
                ClientSecret = ConfigurationHelper.ClientSecret,
                Authority = ConfigurationHelper.Authority,
                MetadataAddress = ConfigurationHelper.MetaDataUri,
                Scope = "openid profile email roles",
                Notifications = ConfigureWaadNotifications()
            });
        }

        private static OpenIdConnectAuthenticationNotifications ConfigureWaadNotifications()
        {
            return new OpenIdConnectAuthenticationNotifications
            {
                RedirectToIdentityProvider = async ctx =>
                {
                    Trace.WriteLine(string.Format("WAAD RedirectToIdentityProvider {0}", ctx.Request.Path));
                    
                }
            };
        }
```
but I am getting no logging from the ```RedirectToIdentityProvider``` delegate , nor does a breakpoint in that delegate get hit - so I assume for some reason the middleware is not getting fired.

the change is reversible - i.e. going back to the 1.6.2 code (and reversing db migrations) I get back to a working system, and when I go back to 2.1.1 it's broken in the same way.

has anyone else had anything similar?

have I missed a fundamental change in version 2.x ?

**Comment by brockallen** [comment]
Hmm, I don't recall anything major around that area changing. Our samples pretty much look the same. I'd compare yours against our sample host in the core repo.

**Comment by brockallen** [comment]
Also, to debug, put middleware in your ConfigureExternalIdentityProviders before and after the OIDC middleware - just to see the execution thru the pipeline.

**Comment by synesthesia** [comment]
Yes I've been looking at [those](https://github.com/IdentityServer/IdentityServer3/issues/2185#issuecomment-158054022) Brock. I'm reasonably sure I haven't screwed up a config in the code change, but I suppose I should backtrack.

Your [second comment](https://github.com/IdentityServer/IdentityServer3/issues/2185#issuecomment-158054209) - not that familiar with katana - do you mean create a little logging middleware that pretends to be an external provider, or temporarily add one of the other ones e.g. facebook?

**Comment by brockallen** [comment]
So something like this:
```
private static  void ConfigureExternalIdentityProviders(IAppBuilder app, string signInAsType)
        {
            app.Use(async (ctx, next)=>{
                await next();
            });
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "WAAD",
                Caption = "My Caption",
                SignInAsAuthenticationType = signInAsType,
                ClientId = ConfigurationHelper.ClientId,
                ClientSecret = ConfigurationHelper.ClientSecret,
                Authority = ConfigurationHelper.Authority,
                MetadataAddress = ConfigurationHelper.MetaDataUri,
                Scope = "openid profile email roles",
                Notifications = ConfigureWaadNotifications()
            });
            app.Use(async (ctx, next)=>{
                await next();
            });
        }
```

Then you can put breakpoints in there before and after the await to see what the response looks like (401, etc). Also, more on katana here: https://vimeo.com/97329189

**Comment by synesthesia** [comment]
thanks will try that!

**Comment by synesthesia** [comment]
*WIP update*

The error seems to happen in ``` Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler ``` at the point where it calls to WAAD to update the metadata - line 137 of [this file](https://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs):

 ``` _configuration = await Options.ConfigurationManager.GetConfigurationAsync(Context.Request.CallCancelled);```

When that line is hit when the handler is processing the external login the call never returns. 

As far as I can see the metadata address is correct.

I have to put this down for a few days and rollback our deployed project to 1.6.2, but will update this issue when I do finally get to the bottom of it.

**Comment by brockallen** [comment]
That's a deadlock bug in katana. Check their issue tracker.

**Comment by synesthesia** [comment]
Thanks Brock - [this one](https://katanaproject.codeplex.com/workitem/409)?

**Comment by brockallen** [comment]
Yep

**Comment by synesthesia** [comment]
Thanks @brockallen for your timely pointers, for other users I can confirm that updating Microsoft.IdentityModel.Protocol.Extensions (at time of writing to 1.0.2.206221351) removed the deadlock

**Comment by brockallen** [comment]
Ah, good to hear.
