### ISSUE TITLE
Question: How do I configure and use response_modes_supported

### ISSUE THREAD

**Issue by setiseeker** [IdentityServer/IdentityServer3#2186]
On the discovery document for my server implementation, I am seeing response_modes_supported.
"response_modes_supported": [
        "form_post",
        "query",
        "fragment"
    ],

What I am not able to find is how I setup a client to use a "response_modes_supported":  to change my reply to query strings or form posts in place of fragments.

I can find where to set the response_types_supported which is on the request from the client app.

Would you mind pointing me to the correct sample or documentation regarding this.

thanks

**Comment by brockallen** [comment]
What framework are you using in the client? ASP.NET, JS, what?

**Comment by setiseeker** [comment]
we are using asp.net

thanks

**Comment by brockallen** [comment]
So then follow the examples for the MVC applications that are using the katana OIDC middleware. The OIDC middleware already uses form_post.

**Comment by setiseeker** [comment]
thank you for the fast reply.
