### ISSUE TITLE
Different Clients (with different tenants) get same claims

### ISSUE THREAD

**Issue by sercangurbuz** [IdentityServer/IdentityServer3#2187]
Hi there,
There are two clients registered as implicit flows which get autenticated using different account stores depending on tenants.

IdSrv has two clients.First id is "client1" and seconds is "client2" and my identity scope name "rotauser" includes a claim named "fullname".

There are two website as client using idsrv one of which is using client1 and the other using client2.Also sending the tenants in url.

Scenario 
1 - client1 get requested by website1 and redirected to loginpage
2 - AuthenticateLocalAsync is run and AuthenticateResult is returned with claim "fullname" as "Bob"
3 - GetProfileDataAsync is run and context.Subject.Claims **fullname = "Bob"**
4 - client1 is succesfully authenticated and redirect to return url.
5 - website1 get "fullname" claim as "Bob" thru id_token
so far so good
6 - client2 requested by website2 and redirected to loginpage
7 - AuthenticateLocalAsync run and AuthenticateResult is returned with claim "fullname" as "Alice"
8 - GetProfileDataAsync is run and context.Subject.Claims **fullname = "Alice"**
9 - website2 get "fullname" claim as "Alice" thru id_token
still so far so good
10 - After id_token in website1 has expired or deleted by me from localstorage and refresh the browser
11 - client1 get requested by website1 and **not redirected to loginpage**
12 - AuthenticateLocalAsync **not run** and obviously claims not updated.
13 - GetProfileDataAsync is run and context.Subject.Claims **fullname = "Bob"** which is not desired claims.
14 - website1 get "fullname" claim as "Alice" thru id_token which is incorrect.

Consequently,last client overwrite the claims and due to cookie authentication,other cllients get lastly updated claims.

Well,Perhaps I migth have misunderstood the conception.Please anyone let me know the right story here.
my config is 
```c#
app.Map("/identity", rotasrv =>
            {
                #region Use Entityframework
                //Set ConnectionstringName
                var efConfig = new EntityFrameworkServiceOptions
                {
                    //TODO:Get cs name from config
                    ConnectionString = "RotaIdentityDb"
                };
                //Register ClientStore ScopeStore
                var factory = new IdentityServerServiceFactory();
                factory.RegisterConfigurationServices(efConfig);
                factory.RegisterOperationalServices(efConfig);
                //Register Rota Services
                factory.RegisterRotaServices(efConfig);
                #endregion

                #region Register Services + Caching
                //UserService Register
                factory.UserService = new Registration<IUserService>(typeof(RotaUserService));
                //UserService Register
                factory.ViewService = new Registration<IViewService>(typeof(RotaViewService));
                //Caching
                //factory.ConfigureClientStoreCache();
                //factory.ConfigureScopeStoreCache();
                //TODO: App servisini cache'le
                #endregion

                #region Token Default Cleanup
                var cleanup = new TokenCleanup(efConfig, 10);
                cleanup.Start();
                #endregion

                #region Register IdentityServer
                rotasrv.UseIdentityServer(new IdentityServerOptions()
                                                               {
                                                                   SiteName = "Rota Identity Server",
                                                                   // IssuerUri = issuer,
                                                                   SigningCertificate = Certificate.Get(),
                                                                   Factory = factory,
                                                                   RequireSsl = false,
                                                                   PublicOrigin = origin,
                                                                   AuthenticationOptions = new AuthenticationOptions()
                                                                                           {
                                                                                               RememberLastUsername = true,
                                                                                               EnableSignOutPrompt = false,
                                                                                               EnablePostSignOutAutoRedirect = true                                                                                               
                                                                                           }
                                                               });
                #endregion
```

**Comment by brockallen** [comment]
If IdSvr is only hosted on one host name, then there's only one authentication cookie. To me, this is not really multi-tenant.

**Comment by sercangurbuz** [comment]
well,a couple of questions raised in my mind then;
Depending on the above scenairo,

1 - what could be solution(s) when different clients needs to legitimate itself through different storages (account stores) in idSrv ?
2 - Should i host idsrv in different servers  for per authentication type ?
3 - Can you guide me to understand what the multitenant in idsrv means ?

**Comment by sercangurbuz** [comment]
Registering application per account stores like below
app.Map("/identity", rotasrv =>...
app.Map("/identity2", rotasrv =>...

solved my issue.In this way two web apps succesfully works seperately.

However using same host,(say that /identity) Resource owner flow and implicit flow legitimate itselfs with different accounts do not interfere each others.I mean context.Subject.Claims in GetProfileDataAsync does not mixed up.

Could you confirm that 

**More than one implicit flow which legitimate itselfs with different account stores MUST be on different host name.**
**Implicit flow and resource owner flow using same host name which legitimate itselfs with different accounts do NOT MUST on different hosts.**

**Comment by brockallen** [comment]
To me, multi tenancy means two different users can login with the same username and (potentially) different passwords and they are two different users. This means you need something to distinguish them, which is the tenant identifier. Normally people use the host name for that foo.idsvr.com vs. bar.idsvr.com. Also, from the user's perspective, the different apps they use they would not expect SSO across those apps. So the multi-tenancy is just a trick to have one IdSvr hosted in the same place but it is acting as if there were two. 

If you do then make the tenant come from the host name, then the browser will also help in that it will keep two different cookies -- one for each host name, so a single human can be logged in with two different accounts at the same time.

This is just one take on multi-tenancy. Perhaps people have other thoughts/requirements, but this is how I normally think of it. 

Perhaps your idea of multi tenancy is different.
