### ISSUE TITLE
Integrating with Oracle Webgates

### ISSUE THREAD

**Issue by elryry** [IdentityServer/IdentityServer3#2188]
Would it be possible to integrate IdentityServer with an Oracle Webgate as the source of authentication?

For the unfamiliar, a Webgate is an IIS ASAPI filter that protects a given directory by redirecting a user without a session cookie to a login page, then redirecting the user back to the application with session server headers (user id, cookie value, etc.).

Here is a high-level diagram of the overall concept: https://docs.oracle.com/cd/E12530_01/oam.1014/e10356/img/aiing023.gif

The Webgate can protect a specific folder on a site (e.g. /root/protected/). Given this, and my limited knowledge around IdentityServer, would it be possible to redirect a user with no session to a protected folder, have the webgate pick it up, authenticate the user, then redirect back to the normal IdentityServer flow?

Thanks for any help!

PS - I know this doesn't seem ideal to be working with, but it's what I got.

**Comment by brockallen** [comment]
You could emulate what the windows auth integration library does: https://github.com/IdentityServer/WindowsAuthentication/

**Comment by elryry** [comment]
Thanks, looking over that project now. Will share if I can get things up and running.

**Comment by elryry** [comment]
@brockallen - I'm having some issues getting the WindowsAuthentication set up in a test project, and to be honest I'm a bit confused. Does the WindowsAuthenticationService not utilize IdentityServer at all? 

When I add:

```c#
app.UseWindowsAuthenticationService(new WindowsAuthenticationOptions
            {
                IdpRealm = "urn:idp",
                IdpReplyUrl = "https://localhost:44300/",
                SigningCertificate = this.LoadCertificate()
            });
```

to the Startup.cs file on the client, the home page of the web app just becomes an XML EntityDescriptor response.

**Comment by brockallen** [comment]
It's acting as a STS that authenticates w/ IIS' integrated windows auth. IdSvr then needs to be configured with it as an upstream IdP.
