### ISSUE TITLE
'account chooser' step in the identityserver3

### ISSUE THREAD

**Issue by phoenixjun** [IdentityServer/IdentityServer3#2189]
We are trying to use the IDentityServer3 from thinktecture as our identity server and we ran into some issue and would like to see if anyone can help on that.

We have a few existing websites in the organization and the business would like to bring in the identity server and SSO concept.  We will use identity server to manage the account for the new system but for the existing website, the account will still remain in the original system. But we will add an extra link on the existing website so that the user can login to IDP from there. Moreover, we allow the user to link their account(s) back to the original website accounts from IDP and go to the existing website from the account list on IDP.

The issue we have in the implementation is when the user login from the client website to the IDP the user might have zero account, one account or multiple accounts in the original website, we need to introduce an ‘account chooser’ type page in the flow before returning the id_token back to the client. The business would like to introduce that step on the IDP side instead of each individual website. After the investigation, we reckon this does not below to any of the existing flow (implicit, AuthorizationCode etc), and we need to customized that. We think custom flow is the way to go, however, we are not sure what is the best place to introduce that extra account selection step.

Any recommendation is welcome

**Comment by brockallen** [comment]
So this concept is something that some providers support -- like google, for instance. IdentityServer does not have native support for being logged into multiple accounts at the same time within IdentityServer -- we only support one at a time. But if you want to introduce the concept of picking an account then you can look into the partial login support we have -- this allows you to inject your own custom page into the user's login workflow and you could implement something like what you're describing.

**Comment by phoenixjun** [comment]
Hi, Thanks for your comment, we tried your suggestion but there is some issue if we put that into the partial login step that is not getting call when the login user come back again. following is the scenario:

user login to sub system website A for from IDP, the account chooser will get display
user logout from sub system (in the current implementation, the sub system does not inform IDP the client has logout)
user try to login to sub system from IDP, however since the user has login to IDP, the authentication process is bypassed the account chooser is not display

We would like the account chooser page to display all the time.

Is there any suggestion on that?

**Comment by brockallen** [comment]
You might want to do this from PreAuthenticate so the user can provide some initial identifying information.

Also, though, I see your point about not being called again if they're logged in... you might need to also handle some logic in this (which has yet to be implemented): https://github.com/IdentityServer/IdentityServer3/issues/2148

**Comment by phoenixjun** [comment]
I hope we are on the same page here. The account chooser we are trying to build is for the sub system not for the account in IDP. The user have an account in IDP, however they have different accounts in the sub system when we login from the sub system, we would like to provide the user some interface to select their account. I hope that is clear to you. Is that enhancement in #2148 going to fix that?

Also, just wondering when is the release day for release 2.3?

Thanks

**Comment by brockallen** [comment]
Check the milestone page.

**Comment by leastprivilege** [comment]
we track that as an enhancement

**Comment by brockallen** [comment]
@phoenixjun this might work for you for now: https://github.com/IdentityServer/IdentityServer3/issues/2388#issuecomment-172640121
