### ISSUE TITLE
Simplest OAuth2 Walkthrough returns 401

### ISSUE THREAD

**Issue by mleir** [IdentityServer/IdentityServer3#2190]
I can walk through the walk through and get a token 
IdSrv returns returns the token response.

The client moves from GetClientToken to CallApi supplying the response.

Returns 401:
            Console.WriteLine(client.GetStringAsync("http://localhost:14869/test").Result); 

I can remove the "config.Filters.Add(new AuthorizeAttribute());", turning off validation, and I get a response (no Authorization). 

I am new to the  Thinktecture/OAuth stuff. 
What am I doing wrong here? A push in the correct direction would be appreciated.

**Comment by brockallen** [comment]
It's very hard to tell. Perhaps enable logging to see if anything turns up.
