### ISSUE TITLE
Redirect URL after Login

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#2191]
Hello,

for my client I registered a redirect URL like this: localhost:12345
if I access localhost:12345/claims, after loggin in at identity server, i'll get a redirect to localhost:12345/claims, great!

I reviewed in fiddler, and saw a location header with this address. I think this is the information i want to change, because the redirectUrl in request query is only localhost:12345.

Can someone please explain if and where it's possible to change this information? I want to change where to exactly redirect after login. (e.g. localhost:12345/othersite).

Redirecting to another domain will not be possible because of security concerns? Or i would have to register all other possible domains (many, in this case), as redirect urls.. ?

Thanks..

**Comment by brockallen** [comment]
What are you trying to accomplish?

The redirect URI is the trusted place to send tokens, so it's a sensitive endpoint and we only allow exact matches (so no query strings, etc.).

**Comment by senj** [comment]
Let's assume a user from US comes to our webseite www.test.de/login and uses the login form. We have the restriction that users are only allowed to see their country's website. After login, I'll know from user profile that the user is from the US, so I want to redirect him to www.test.com/login. The problem is that it could also be www.test.com/somepath/login. Only the client application knows that exact URL.

I think instead of changing the redirect URL, the better solution would be to redirect him back to test.de as normal.I would globally check if language=US matches the user's language claim and if not, i can redirect the user to it's languages' website.

**Comment by brockallen** [comment]
> I think instead of changing the redirect URL, the better solution would be to redirect him back to test.de as normal.I would globally check if language=US matches the user's language claim and if not, i can redirect the user to it's languages' website.

Yep

**Comment by senj** [comment]
Thank you.
