### ISSUE TITLE
Q: How to properly handle token validation in MVC with cookie auth in resource owner flow?

### ISSUE THREAD

**Issue by urbanhusky** [IdentityServer/IdentityServer3#2193]
Hi,

I've got an ASP.NET application that I'm migrating from forms authentication to use tokens and claims (because I'll need to transport the claims down in my service hierarchy). For this reason I'm using resource owner password credentials flow and `UseCookieAuthentication`. 
So far, so good - user logs in, is authenticated via the cookie, got the claims in the user etc.

Now I want to validate the (access) token in my MVC application because I don't want to rely on the presence of a cookie alone. While the API should validate the token, it would still be possible to gain some information about the application with an expired access token because the MVC layer doesn't validate it yet.

What options do I have available in this scenario?

**Comment by leastprivilege** [comment]
you can use the access token validation endpoint (or introspection endpoint starting in v2.2) to validate the token. check the docs.

**Comment by urbanhusky** [comment]
Is there any middleware which does that for me? If not, where would be the best place and time to validate the token?

**Comment by mderriey** [comment]
Since your token lives in the cookie, I'd say the OWIN cookie authentication middleware is a good place to have the validation of the token. It exposes different _events_ where you can hook custom logic.

Fortunately, one in particular, `ValidateIdentity`, allows you to execute logic after the cookie has been validated by the middleware - so you know it's a valid cookie, but you want to make sure the token is valid, too.

The code could resemble something like:
```csharp
app.UseCookieAutnentication(new CookieAuthenticationOptions
{
    // Your options here
    Provider = new CookieAuthenticationProvider
    {
        // https://msdn.microsoft.com/en-us/library/microsoft.owin.security.cookies.icookieauthenticationprovider.validateidentity(v=vs.113).aspx#M:Microsoft.Owin.Security.Cookies.ICookieAuthenticationProvider.ValidateIdentity(Microsoft.Owin.Security.Cookies.CookieValidateIdentityContext)
        OnValidateIdentity = async context =>
        {
            // context.Identity represents the ClaimsIdentity
            // stored in the cookie

            // you could validate the token here and call
            // context.RejectIdentity() if it is not valid anymore
        }
    }
});
```

**Comment by urbanhusky** [comment]
Thank you very much, I was able to implement it like this:

```
OnValidateIdentity = async context =>
{
		if (context?.Identity?.IsAuthenticated ?? false)
		{
				var accessToken = context?.Identity?.Claims?.FirstOrDefault(x => x.Type == "access_token")?.Value;
				if (accessToken == null)
				{
						context?.RejectIdentity();
				}
				else
				{
						var client = new IntrospectionClient(
								"https://localhost:44333/connect/introspect", 
								"MyResourceScope",
								"secretForMyResourceScope"); // auth as scope, not client!
						var validationResult = await client.SendAsync(new IntrospectionRequest()
						{
								Token = accessToken
						});

						if (validationResult.IsError || !validationResult.IsActive)
						{
								context?.RejectIdentity();
						}
				}
		}
}
```

**Comment by gskidmore** [comment]
Might be a few years late but thanks for this! Exactly what I was looking for :)

**Comment by mdhalgara** [comment]
Likewise, thanks for sharing your insight.
