### ISSUE TITLE
Client claims in resource owner flow

### ISSUE THREAD

**Issue by urbanhusky** [IdentityServer/IdentityServer3#2195]
Hi,

I'd like to have per-client claims available as the claim is associated with the client the user logs in from (using resource owner password credentials flow).
I've tried adding the claim to the client and set `AlwaysSendClientClaims` but I'm not getting the claim at the userinfo endpoint (which I'm using to fetch the claims after authenticating the user).

I've set up an identity scope which contains a `ScopeClaim` for the client-claim and I am requesting this scope.
I'm also using reference tokens so I don't really have any information available other than the access token.

My current guesses are:
A) userinfo endpoint only provides user-claims
B) reference tokens don't play nice with client-claims
C) something else

**Comment by leastprivilege** [comment]
The client claims are inside the access token. The userinfo endpoint only has user claims.

**Comment by urbanhusky** [comment]
How are they inside the access token? 
I get the token like this:

```
var client = new TokenClient(
	"https://localhost:44333/connect/token",
	"webuser",
	"websecret");

var scopes = "openid profile email roles SomeIdentityScope SomeResourceScope offline_access";
var result = client.RequestResourceOwnerPasswordAsync(model.Username, model.Password, scopes);
var token = await result; 
```
At this point, the token looks like this:
```
{
  "access_token":"603f0e93513e3100b7f034e7a9991588",
  "expires_in":600,
  "token_type":"Bearer",
  "refresh_token":"b2b5654796dcca2a77919a96f38a2c22"
}
```

I defined the client-claim like this:
```
AlwaysSendClientClaims = true,                     
Claims = new List<Claim>()
{
  new Claim("IsFooClient", "false", ClaimValueTypes.Boolean) 
}
```

**Comment by urbanhusky** [comment]
P.S.: I seem to get the client claims when using the introspection endpoint. Would that be a viable option (I'm thinking of using the clientinfo and introspection endpoint and merging the resulting claims)?

**Comment by leastprivilege** [comment]
if that has everything you need. go for it.

**Comment by urbanhusky** [comment]
Unfortunately, the introspection endpoint only returns the claims of the single scope that I validate. I would have to call the introspection endpoint for each single scope I use and merge the result...
