### ISSUE TITLE
Different authentication based on request origin

### ISSUE THREAD

**Issue by elryry** [IdentityServer/IdentityServer3#2196]
I have a requirement that would require two different authentication methods depending on the request origin (where a user is logging in from). If a user is logging in from network segment A, the user should be authenticated using Windows/NTLM. If a user is logging in from network segment B, the user should be authenticated via an LDAP store.

Would something like this be possible to integrate with IdentityServer3 without a huge overhaul under the hood?

Any advice would be greatly appreciated!

**Comment by brockallen** [comment]
This would be logic you implement in your user service. To get access to the HTTP request inject the OwinEnvironmentService into your ctor.

**Comment by elryry** [comment]
Hey, @brockallen. I got this wired up, but I'm not seeing the request origin IP address. Any thoughts?

**Comment by brockallen** [comment]
Is there nothing in the request for the caller's IP address?

**Comment by elryry** [comment]
I just got this working using .NET 4.6.1 and MVC 5. I was and am still unable to get the remote IP address value using ASP.NET 5 / MVC 6. Any ideas (the attribute LocalIpAddress and RemoteIpAddress just aren't there)?

**Comment by brockallen** [comment]
Not sure -- perhaps try to repro in an ASP.NET 5 with the OWIN integration layer. Perhaps it's an ASP.NET 5 issue.

**Comment by elryry** [comment]
Alright, will do. Thanks @brockallen!
