### ISSUE TITLE
Access denied error in Cryptographic dll

### ISSUE THREAD

**Issue by harisshahid** [IdentityServer/IdentityServer3#2198]
I was trying to deploy Identity Server 3 on GoDaddy's shared hosting. I'm getting this System.Security.Cryptography.CryptographicException: Access denied. error. I know this issue is duplication of #849 and #854. But I didn't find any correct solution how to resolve this issue. 
Which steps I need to follow to up and running my server.
Your help would appreciated.

**Comment by brockallen** [comment]
You need access to the signing cert. If you're using a hosting provider, you'll need to talk to them about how to securely store a signing certificate.
