### ISSUE TITLE
Why POST method not working on accesstokenvalidation endpoint?

### ISSUE THREAD

**Issue by tomasAl** [IdentityServer/IdentityServer3#2199]
Can't use POST method  on accesstokenvalidation endpoint. When IdentityServer3 is started on .net MVC or WEB API application I'm getting: "The requested resource does not support http method 'POST': error message. Maybe somebody can give me some advice how to solve this problem?

**Comment by brockallen** [comment]
We added POST support for that in 2.0: https://github.com/IdentityServer/IdentityServer3/releases/tag/2.0.0

**Comment by tomasAl** [comment]
I have updated IdentityServer3  to 2.2 version and everything is working. Thanks!!!
