### ISSUE TITLE
Authentication problem in redirection when rendering a partial view using angular client. 

### ISSUE THREAD

**Issue by somak12** [IdentityServer/IdentityServer3#2201]
Got stuck in an issue, in the owin middleware I have used CookieAuthentication with ExpireTimeSpan of 60 seconds(for example). In the OpenIdConnectAuthenticationOptions, UseTokenLifetime is set to false.
After sometime when the cookie expires the angular client is requesting the idsvr to authenticate the user again and returning a 302 status which in turn is redirecting to the login page. Idsvr returns the error it cannot redirect to the particular application.. What did I miss?
The view is a partial view and is rendered inside of a popup. If page is refreshed its working fine as expected.
Idsvr is giving an error:
"There is an error determining which application you are signing into. Return to the application and try again."

I found few problems which are exactly similar to that of mine. Hope this will help to understand better http://stackoverflow.com/questions/31094023/redirect-to-identity-server-login-page-from-angularjs-http-web-api-request

**Comment by brockallen** [comment]
When you say "After sometime when the cookie expires the angular client is requesting the idsvr to authenticate the user again and returning a 302 status which in turn is redirecting to the login page" is this from an ajax call, or is this from the angular code redirecting the user in a visible window for authentication?

Also, as always, you should enable logging in IdSvr -- this will provide you much information for debugging.

**Comment by somak12** [comment]
Yes logging is enabled. 

Here is what it says at that point.
iisexpress.exe Information: 0 : 2015-11-23 20:03:53.656 +05:30 [Information] User is not authenticated. Redirecting to login.
iisexpress.exe Information: 0 : 2015-11-23 20:03:53.656 +05:30 [Information] End authorize request
iisexpress.exe Information: 0 : 2015-11-23 20:03:53.656 +05:30 [Information] Redirecting to login page
2015-11-23 20:03:53.657 +05:30 [Debug] Protecting message: "{\"ReturnUrl\":\"https://localhost:44307/core/connect/authorize?client_id=hybridclient&redirect_uri=https%3A%2F%2Flocalhost%3A44308%2F&response_mode=form_post&response_type=code%20id_token%20token&scope=openid%20profile%20email%20roles%20offline_access%20jomcApi%20JomcApp&state=OpenIdConnect.AuthenticationProperties%3DHBU1ZC39Unl8N196VQrjnJwzp_c86KqSQn_Ca9g1wWOcGCrjwomzpcm7tBOt5CAc3BIoby2s2BYMpv9UiNOiycjhAWpZYE9zWInLfEUgJ9O_gT7sh4_AykRMkjpGi--xWEWlx1U_Rreo8g3YAH3ERGmAKvHLx1T71yeCt9Z2WxasFr-Ukr0LgUZ_WZ8DMKmispKb5pHOv0BKZDnHLgkSClc2Bm3_-7nifJ-c5JgI4aM&nonce=635838860192171670.OGFiNjc2ODMtZmZkYy00Njg4LWFhYTYtYTk4YzBkOWNlMjE2MzUxZmI4YzgtZGNlZS00MWZjLTkwMzUtYmExNWUzNThmNWRl\",\"ClientId\":\"hybridclient\",\"AcrValues\":[],\"Created\":635838860335689878}"
iisexpress.exe Warning: 0 : 2015-11-23 20:03:53.663 +05:30 [Warning] CORS request made for path: "/login" from origin: "https://localhost:44308" but rejected because invalid CORS path
iisexpress.exe Information: 0 : 2015-11-23 20:03:53.664 +05:30 [Information] Login page requested
iisexpress.exe Information: 0 : 2015-11-23 20:03:53.664 +05:30 [Information] No cookie matching signin id found
iisexpress.exe Warning: 0 : 2015-11-23 20:04:55.388 +05:30 [Warning] CORS request made for path: "/connect/authorize" from origin: "https://localhost:44308" but rejected because invalid CORS path
iisexpress.exe Information: 0 : 2015-11-23 20:04:55.390 +05:30 [Information] Start authorize request
iisexpress.exe Information: 0 : 2015-11-23 20:04:55.390 +05:30 [Information] Start authorize request protocol validation
iisexpress.exe Information: 0 : 2015-11-23 20:04:55.467 +05:30 [Information] "Authorize request validation success"

**Comment by somak12** [comment]
Yes this is an ajax call. And the result is rendered inside of a partial view in a modal.

**Comment by brockallen** [comment]
Ajax calls should not return 302 if the user is not authenticated -- they should return 401 so the JS code can then do what's needed to get the user logged back in.

**Comment by somak12** [comment]
Yes I found this info in one of ur posts. 
But here I am facing a different scenario 
https://localhost:44307/core/connect/authorize?client_id=hybridclient&redirect_uri=https%3A%2F%2Flocalhost%3A44308%2F&response_mode=form_post&response_type=code%20id_token%20token&scope=openid%20profile%20email%20roles%20offline_access%20jomcApi%20JomcApp&state=OpenIdConnect.AuthenticationProperties%3DHBU1ZC39Unl8N196VQrjnJwzp_c86KqSQn_Ca9g1wWOcGCrjwomzpcm7tBOt5CAc3BIoby2s2BYMpv9UiNOiycjhAWpZYE9zWInLfEUgJ9O_gT7sh4_AykRMkjpGi--xWEWlx1U_Rreo8g3YAH3ERGmAKvHLx1T71yeCt9Z2WxasFr-Ukr0LgUZ_WZ8DMKmispKb5pHOv0BKZDnHLgkSClc2Bm3_-7nifJ-c5JgI4aM&nonce=635838860192171670.OGFiNjc2ODMtZmZkYy00Njg4LWFhYTYtYTk4YzBkOWNlMjE2MzUxZmI4YzgtZGNlZS00MWZjLTkwMzUtYmExNWUzNThmNWRl\",\"ClientId\":\"hybridclient\",\"AcrValues\ 
this is the call that my client is making when the cookies expires, and this is returing a 302. 
and then idserver says "There is an error determining which application you are signing into. Return to the application and try again."
Is that the expected behavior?

**Comment by brockallen** [comment]
The error from IdentityServer has to do with a missing cookie. It feels like you're losing a cookie in the series of redirects.

**Comment by somak12** [comment]
Yes I got to know of that from similar issues of missing cookie form the log file. 
And one more info I would like to share. If I copy paste the authorization link in another tab, it will work fine and render the partial view. Only causing problem when being called from the main page from with in the pop up.

**Comment by brockallen** [comment]
Is the popup in an iframe? Also, are you using IE?

**Comment by somak12** [comment]
None.

**Comment by brockallen** [comment]
Then I don't know -- you'll have to debug the HTTP level to find out where/why the cookie the authorization endpoint issues is not being sent to the login page.

**Comment by somak12** [comment]
Ok. Can you tell me what will be the name of the cookie that the authorization endpoint issues so that I can take a look?

**Comment by brockallen** [comment]
It's "idsvr" -- you should see it when you do the first successful login.

**Comment by somak12** [comment]
Thanks Brock will let u know of ne progress.

**Comment by somak12** [comment]
I have checked the network. Normally when there is an authorize request there are 3 idsrv cookies that are going with the request. they are : idsrv, idsrv.xsrf, idsrv.session along with the authentication cookie. But when the authorize request is going via the popup the cookies are not present. Now it is clear that there are missing cookies. But my question is how are these cookies going into the request? I can't find them after the user login.

**Comment by somak12** [comment]
![image](https://cloud.githubusercontent.com/assets/14160083/11361703/23f94e88-92b5-11e5-8eb9-8b57567f52ad.png)

This is the case when I refresh the page or copy paste the authorize link in other tab. 

And this happens to the authorize request when it is coming through the pop up or the partial view. 

![image](https://cloud.githubusercontent.com/assets/14160083/11361771/b1efa46c-92b5-11e5-8dd8-abb8b02c9b2a.png)

**Comment by brockallen** [comment]
Not sure -- perhaps it's something with how the popup is being done. If you navigate the main window, are the cookies sent?

**Comment by somak12** [comment]
In the main window, yes I can see all the cookies in the request? Can you tell me where the cookies are coming from i mean which end point? Cuz those idsrv cookies are not present in the browser, they only get appended to the authorize request.

**Comment by brockallen** [comment]
The cookies come from the login page. The authentication cookie needs to be present to pass the authorize endpoint.

**Comment by somak12** [comment]
In the above post if u notice, _d1 is my authentication cookie which is present in the browser after user login.  But I am not sure of the other three cookies. Idsrv, idsrv.xsrf and idsrv.session. How come they are getting appended into the request when they are not present in the browser?

**Comment by brockallen** [comment]
idsvr is IdSvr's authentication cookie. The idsvr.xsrf cookie is our XSRF protection cookie. And the idsvr.session cookie for our session management cookie for the OIDC session management spec. These are all idsvr's cookie needed for normal operation.

**Comment by somak12** [comment]
Ok. so I hope if i can just find a way to append the authentication cookie in the request it will work fine.

**Comment by brockallen** [comment]
My guess is that something about how you do the popup is causing the browser to not send the authentication cookie. That's why I asked about IE -- it has a policy that prevents cookies from being sent cross security boundaries from an iframe (not sure about popups).

**Comment by somak12** [comment]
We are using angularjs template to get our partial html view on popup. 
Here is the snippet that opens the popup view..

                   $scope.openLocation = function (selectedLocation, isedit) {
                    var templateUrl = '/Admin/LocationUpsert';

                    // clear model data every time
                    $templateCache.remove(templateUrl);

                    var modalInstance = $modal.open({
                        animation: true,
                        templateUrl: templateUrl,
                        controller: 'control.controller',
                        resolve: {
                            parentSettings: function () {
                                return {
                                    modelTitle: "Locations"
                                };
                            }
                        }
                    });

**Comment by brockallen** [comment]
Well, I don't know how $modal works.

**Comment by brockallen** [comment]
Any update, or can we close this?

**Comment by somak12** [comment]
We can close this for now. I will update of any progress.
