### ISSUE TITLE
Caching additional claims after authentication

### ISSUE THREAD

**Issue by sabby62** [IdentityServer/IdentityServer3#2203]
I am using Identity Server 3 for authentication only. Once a user is authenticated, I look for app specific claims for the authenticated user in my DB and add them to the identity before passing to the API. I have an Angular App that talks to my API. I append Authorization bearer token every time Angular App accesses the API. Once the API gets request, token is validated (using identity server validation endpoint), claims are loaded from DB. 
Loading the claims everytime angular app access API doesn't seem to be an optimal solution. Would you please suggest an optimal solution ?

**Comment by RPM1984** [comment]
+1, curious to know the advice on this.

**Comment by mderriey** [comment]
Hi,

I'd say you have 2 options:

 - Given you use JWT tokens, you could store those claims in the authorization token, so your API would have access to them via the logged-in identity
 - If this is not possible, then a cache mechanism at the API level could save you trips to the DB. I'm pretty sure I've seen a post or a comment about this by @leastprivilege or @brockallen, I'll look for it tomorrow morning.

Cheers
