### ISSUE TITLE
Feature request: Constants (OpenIdConnectDefaults) as part of package

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2204]
OK, I found the identityServer3.core.Models.StandardScopes...

  a. You need to update some of your samples to stop using literal strings, and use this. 
  b. You should add many other literals used in the examples (i.e. "read" / "write" / "id_token token" for hybrid access_token etc.)

I edited this issue. It was: 
Could you please add the constants to the IdentityServer3 package or as a separate one? 
Call them OpenIdConnectDefaults, or IdentityServerDefaults

Then we won't need to include the "Constants" project in our development enviro.

**Comment by leastprivilege** [comment]
I think we are fine. Feel free to create your own constants class for the things you need.

The Constants in the idsrv core package is meant to be used by people extending idsrv.

**Comment by pashute** [comment]
Where can I find the names of the ResponseType token types 
i.e. id_token, code id_token, id_token token etc.
and where do I find what the name of the returned tokens are? 
id_token, access_token etc. 
Is that found in any constant?

If not wouldn't it be desirable to have a IdentityModel.Defaults or IdentityServer.Defaults file with these kinds of strings?

**Comment by leastprivilege** [comment]
e.g. Constants.ResponseTypes.CodeIdToken ??

**Comment by pashute** [comment]
But that only gives "code id_token"  and that doesn't work with user-credentials auth?

We need "id_token token"  no? 

(mvc ui app with flow.implicit calling a webapi rest call. 
The IDSrv3 server is in a third VS project and runs as a standalone.)

Also where do have the token name "access_token" to store in the cookie...

Things like that.

**Comment by leastprivilege** [comment]
I am not sure I understand what you are asking for...

You want a separate package that has all the openid & oauth related constants?
