### ISSUE TITLE
Offer to rewrite MVC sample(s)

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2205]
I think separation is needed between the server code and the client consuming code for clarity. 

I saw that at least two other people had a problem with the same. 

also think a sample where the MVC is separate altogether from the server is in need. 

The docs should be updated accordingly. 

I offer to write the three MVC projects (one having the IDSrv3 OP together with the MVC client, and then two projects where those are separate from each other)

I'll write a quick documentation change as well, but leave it to you to finish that and update it correctly.

**Comment by leastprivilege** [comment]
The client samples are not meant to be end-to-end guidance. They are simple samples of how to use idsrv and apis from a given technology.

Feel free to write a fully feature and "more realistic" sample, host it on your repo and let you know so we can link to it.
