### ISSUE TITLE
Question: API failing - do I need CORS?

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2206]
I modified the app.UseOpenIdConnect in your MVC Sample startup code,   
to call an external IDSrv3 host  - a modified version of your Webhost(minimal).  

The About works perfect, calls the webhost login page, and after login redirects back to the app.  

However when the MVC calls the API (nothing modified there) the WebAPI call is failing with:     
Response status code does not indicate success: 405 (Method Not Allowed)    
On the code line: 

    var json = await client.GetStringAsync("https://localhost:44333/connect/token");  // 44321/identity");

The url is https://localhost:44319/CallApi/UserCredentials

There is nothing special configured in your MVC Sample's Idsrv3 server side code, for accepting the API's access token request although the webAPI is running on a different url (in the testing case a different port on the same IIS Express on the dev machine) 

The only diff I see is that formerly in the running sample code, the access_token was received from the idsrv3 to the same machine and url requesting it (authority and returnuri where same root, with only extra sub path to "/identity" for the idsrv3, in the example. 

You have an old post here: http://brockallen.com/2012/06/28/cors-support-in-webapi-mvc-and-iis-with-thinktecture-identitymodel/

Could CORS be the issue??

If so, where do I find the latest IdentityModel code. Should I use the Thinktecture.IdentityModel or the newer one. Are there any updates to that blog from 2012?

**Comment by brockallen** [comment]
If the calling code is MVC, then CORS is not a factor. CORS only matters when the JS in the browser is making an Ajax call cross origin.

**Comment by pashute** [comment]
The API wasn't running.  (embarrassment)
