### ISSUE TITLE
Error Logs

### ISSUE THREAD

**Issue by abhayachauhan** [IdentityServer/IdentityServer3#2210]
At the moment, I'm finding it difficult to distinguish between real errors, and bad requests in the logs.

Some context - We are trying to set up alarms based on our logs, but the Severity of error seems to be a little too trigger happy IMO.

Ie:
ERROR - Invalid client secret"ClientId": "XXX","ClientCredentialType": "FormPost"
ERROR - Invalid scopes."ClientId": "XXX","ClientName": "XXX","GrantType": "client_credentials"
ERROR - No or malformed client credential found.

These seem like bad requests to me.

Where as some are valid errors that need investigation that should trigger alarms:

ERROR - Unhandled exceptionaccess a disposed object.'System.Net.HttpListenerRequest'.
ERROR - Unhandled exceptionreading HTML form URL-encoded data stream.

Has anyone experienced this? Any way to customise the severity?

**Comment by leastprivilege** [comment]
You shouldn't use logging for setting up alarms - use events.

**Comment by abhayachauhan** [comment]
Thanks.. That looks a lot better
