### ISSUE TITLE
The client application is not known or is not authorized.(Related to 1832 and 1815)

### ISSUE THREAD

**Issue by MacarioTala** [IdentityServer/IdentityServer3#2211]
I've been trying to get IdentityServer to work and have had various levels of luck with the various samples. 

However, I've never been actually able to get the entire flow to work. (Request resource, get auth token, present token, get resource)

I'm presently trying to get the embedded MVC sample to work and it's just not cooperating. 

I've gone through Dominic's Pluralsight courses and did some fairly thorough research on my own vis-a-vis SSL.

Here's what I did:

1.) Created a root cert using makecert and installed in trusted root.
2.) created a signing cert using that root cert.
3.) used cert in #2 for signing. 

My startup class is being called and it's pretty standard:

 public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.Map("/identity", idsrvApp => idsrvApp.UseIdentityServer(new IdentityServerOptions
            {
                SiteName = "Embedded IdentityServer",
                SigningCertificate = LoadCertificate(),

                Factory = new IdentityServerServiceFactory()
                    .UseInMemoryUsers(Users.Get())
                    .UseInMemoryClients(Clients.Get())
                    .UseInMemoryScopes(StandardScopes.All),

                AuthenticationOptions = new AuthenticationOptions
                        {
                            EnablePostSignOutAutoRedirect = true
                        }
            }));

            

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://Troy1/MVCAuthenticationServer/Identity",
                ClientId = "mvc",
                RedirectUri = "https://Troy1/MVCAuthenticationServer",
                ResponseType = "id_token token",
                SignInAsAuthenticationType = "Cookies"
            });
        }

        private static X509Certificate2 LoadCertificate()
        {
            return new X509Certificate2(
                string.Format(@"D:\study\MVCGettingStarted\MVCAuthenticationServer\MVCAuthenticationServer\bin\IdentityServer\Troy1.cer"),
                "Password");
        }
    }

There is also a clients class, also fairly standard and following the walkthrough:

 public static class Clients
    {
        public static IEnumerable<Client> Get()
        {
            return new[]
        {
            new Client 
            {
                Enabled = true,
                ClientName = "MVC Client",
                ClientId = "mvc",
                Flow = Flows.Implicit,

                RedirectUris = new List<string>
                {
                    "http://Troy1/MVCAuthenticationServer"
                },

                AllowAccessToAllScopes = true
            }
        };
        }
    }

Once I try to protect the about action in the Home controller thusly:

[Authorize]
        public ActionResult About()
        {
            return View((User as ClaimsPrincipal).Claims);
        }

It tells me that "The client application is not known or is not authorized." instead of presenting me with a login screen.

I would very much like to be able to use IdentityServer3, but I'm not quite sure what I'm doing wrong.

Cheers

**Comment by kulais** [comment]
I have the same issue with WPF Hybrid Client sample given in Thinktecture samples.
When "code" passed as responsetype:"code" it throws above exception instead of login page. however it works fine when "id_token" given as responsetype. 

Appreciate if you can give some idea about reason for this issue.

**Comment by mderriey** [comment]
When using Implicit flow, the _authentication_ of the client is done by IdentityServer against 2 parameters of the authentication request:

 - the id of the client
 - the redirect URI it specifies

In your case, I can see the client is registered with IdSrv with `http://Troy1/MVCAuthenticationServer` as a redirect URI but the configuration on the MVC application specifies `https://Troy1/MVCAuthenticationServer`. You have a conflict with the schemes.

Maybe there's something else, but fixing this can't hurt.
Cheers.

**Comment by MacarioTala** [comment]
Mate. That's brilliant. It's gone further now. That issue has bugged me for a bit. Time to see what this "unexpected error" is.

Thanks again!

**Comment by vfeinman** [comment]
Similar error message, my URIs were the same but I had: 
     ResponseType = "code id_token token",
in app.UseOpenIdConnectAuthentication. 

This resulted in the same error messages: 
3001: Endpoint failure / Endpoints (Failure), Context: IdentityServer3.Core.Events.EventContext, Details: IdentityServer3.Core.Events.EndpointDetail, Message: unauthorized_client

**Comment by mderriey** [comment]
Please open a separate issue with more details - like the client configuration.

Thank you for your understanding.

**Comment by rogercoulson** [comment]
Don't forget to have a '/' on the end of all your RedirectUri's: "http://Troy1/MVCAuthenticationServer/".  This goes in your caller client redirect uri and the identity server OpenId RedirectUri as well.
It's a pretty common thing that spanked me for a solid day.
