### ISSUE TITLE
Changing Signing Certificate

### ISSUE THREAD

**Issue by nklap** [IdentityServer/IdentityServer3#2215]
Hey,

is it possible to change the signing certificate during runtime?

thanks in advance

**Comment by nklap** [comment]
typo

**Comment by brockallen** [comment]
The docs have info on cert rollover.https://identityserver.github.io/Documentation/docsv2/configuration/crypto.html

**Comment by nklap** [comment]
Yes, I'm aware of the rollover feature. I need to assign a different signing certificate depending on the endpoint called.

I need this somewhat hacky approach to avoid setting up several IDSSRV instances for ADFS Claims Provider Trusts. The trust configuration requires a unique signing certificate for each CPT. My redirection flow works like this: Client -> ADFS -> IDSRV -> IDP. The user clicks a button and directly reaches the IDP logon page without seeing any HRD screens. 

Because i can not change the signing certificate during runtime or configure multiple signing certificates for each endpoint, i'd have to setup multiple IDSRV instances to use several IDSRV CPTs in ADFS.

I hope that my description is understandable. Maybe you have an idea to work around this issue with the current IdentityServer possiblities?

**Comment by leastprivilege** [comment]
I don't we have anything that makes this possible in an easy way.

**Comment by brockallen** [comment]
If it's the same IdSvr, then why do you have multiple configured in ADFS? Maybe I don't want to know...

**Comment by nklap** [comment]
Because you said maybe, I'm going to answer your question :-).

One Claims Provider Trust in ADFS can only have 1 endpoint with 1 unique signing certificate.

So the configuration would be like:
CPT1 -> sts.whatever.com/wsfed?whr=Foo1 -> Cert1
CPT2 -> sts.whatever.com/wsfed?whr=Foo2 -> Cert2 
CPT3 -> sts.whatever.com/wsfed?whr=Foo3 -> Cert3

This wouldn't be valid
CPT1 -> sts.whatever.com/wsfed?whr=Foo1 -> Cert1
CPT2 -> sts.whatever.com/wsfed?whr=Foo2 -> Cert1
CPT3 -> sts.whatever.com/wsfed?whr=Foo3 -> Cert1

This is only to avoid the HRD screen, otherwise I would be fine with 1 endpoint, e.g. sts.whatever.com/hrd. So no issue with IdentityServer! This is just a requirement I have to fulfill.

You can close my question. I figured out a way. 

Thanks anyways guys!

**Comment by leastprivilege** [comment]
you also wanna share "your way"?
