### ISSUE TITLE
userinfo request "Checking for expected scope openid failed"

### ISSUE THREAD

**Issue by xalikoutis** [IdentityServer/IdentityServer3#2216]
I am using Flow = Flows.ResourceOwner in my identityserver.

I created a console application used client.RequestResourceOwnerPasswordAsync and i am getting the access token as expected. But when i pass it to the userinfoclient and call GetAsync , i get userinforesponse System.Net.HttpStatusCode.Forbidden.
Also the openid is in the Client scope.

iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 25/11/2015 4:01:25 μμ +00:00 -- Creating token response
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 25/11/2015 4:01:25 μμ +00:00 -- Processing token request
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 25/11/2015 4:01:25 μμ +00:00 -- Creating access token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 25/11/2015 4:01:25 μμ +00:00 -- Creating reference access token
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController]: 25/11/2015 4:01:25 μμ +00:00 -- End token request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.TokenResult]: 25/11/2015 4:01:25 μμ +00:00 -- Returning token response.
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.UserInfoEndpointController]: 25/11/2015 4:01:27 μμ +00:00 -- Start userinfo request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.UserInfoEndpointController]: 25/11/2015 4:01:27 μμ +00:00 -- Token found: AuthorizationHeader
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenValidator]: 25/11/2015 4:01:27 μμ +00:00 -- Start access token validation
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenValidator]: 25/11/2015 4:01:27 μμ +00:00 -- Checking for expected scope openid failed
{
  "ValidateLifetime": true,
  "AccessTokenType": "Reference",
  "ExpectedScope": "openid",
  "TokenHandle": "c63a930ae301d04990950b9daf9ef32c"
}
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Endpoints.UserInfoEndpointController]: 25/11/2015 4:27:44 μμ +00:00 -- insufficient_scope
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.ProtectedResourceErrorResult]: 25/11/2015 4:27:44 μμ +00:00 -- Returning error: insufficient_scope

**Comment by leastprivilege** [comment]
so what's the question?

**Comment by mderriey** [comment]
I don't know what you mean when you say _the openid is in the Client scope_, but I'm thinking that maybe the problem is that you didn't include the `openid` scope in your call to `RequestResourceOwnerPasswordAsync`.
It's not enough that the client has access to the `openid` scope, the scope needs to be associated with the token, so you explicitly have to request it.

**Comment by xalikoutis** [comment]
Ok thanks didn't know that i have to include every scope to the request. So what i did before was
var re = client.RequestResourceOwnerPasswordAsync("George", "secret", "api").Result;
In order to get other scopes
var re = client.RequestResourceOwnerPasswordAsync("George", "secret", "api openid profile roles").Result;

Thanks

**Comment by mderriey** [comment]
Glad it worked.
Just to clarify, you don't need to send **all** the scopes the client has access to when you call `RequestResourceOwnerPasswordAsync`.
`openid` is mandatory, as you can see [here](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/Connect/UserInfoEndpointController.cs#L86).
The other ones just define which claims you'll get back from the UserInfo endpoint.

Hope that helps a bit.
Cheers.

**Comment by leastprivilege** [comment]
openid is only mandatory when you want to call the userinfo endpoint.

**Comment by mderriey** [comment]
sorry I wasn't clear enough.

**Comment by weitzhandler** [comment]
Thanks to ya'll!
