### ISSUE TITLE
Requesting scopes

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#2219]
Got asked a question that had me failing to find a good answer for:

In a scenario where we don't ask for consent (our own users), why should OAuth2 clients have to specify scopes? Could IDP just assume all scopes that client is allowed to ask for (which IDP already knows) are asked for and return everything that comes with them?

**Comment by leastprivilege** [comment]
Scopes are mandatory - the client needs to specify them.

**Comment by snothub** [comment]
I'm absolutely aware of that. But the question remains: why should it be like that and not optional with everything as default? I'm not saying its wrong, but I don't have a good answer to the contrary, so I ask for assistance.

**Comment by leastprivilege** [comment]
It is just how we implemented it.

**Comment by leastprivilege** [comment]
We probably did not want "lazy" devs to use that feature to get all scopes by default ;)

**Comment by snothub** [comment]
Ah, so in theory it would possibly go, but its the conscious decision not to have that option. Great, that's useful info. Thanks
