### ISSUE TITLE
AccessViolationException when attempting to buffer response in iisexpress

### ISSUE THREAD

**Issue by Tragedian** [IdentityServer/IdentityServer3#2220]
I've encountered a very strange issue where running IdentityServer3 under IIS Express 10 causes an access violation if I try to buffer the output response. The buffering code is (seemingly) simple:

    appBuilder.Use(async (ctx, next) =>
        {
            // Intercept and buffer the output response.
            var stream = ctx.Response.Body;
            var buffer = new MemoryStream();
            ctx.Response.Body = buffer;

            // Allow the application to create a response.
            await next();

            // Restore the original stream and set the content-length.
            ctx.Response.Body = stream;
            ctx.Response.Headers["Content-Length"] = buffer.Length.ToString();

            // Copy the buffered body to the output stream.
            buffer.Seek(0, SeekOrigin.Begin);
            await buffer.CopyToAsync(stream);
        });

I've seen a variety of symptoms, depending on the machine the code is being executed from and whether there are breakpoints being hit in the code.
- Most commonly, the application returns the first response and then the IIS Express process terminates following the access violation.
- Sometimes the access violation happens before the first response is returned.
- Sometimes an initial "batch" of responses are sent (e.g. HTML and all linked resources) and then the access violation occurs.
- An exception may be captured by the Visual Studio debugger, or the process may terminate abruptly.

When an exception is caught by VS, it appears to originate from `System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()`, which is making an unmanaged call to webengine4.dll.

I've forked from the minimal WebHost example to create a simple illustration of the problem: https://github.com/Tragedian/IdentityServer3.Samples/blob/master/source/WebHost%20(minimal)

I've placed this buffering logic into other applications running Web API 2 and not had any issues, so there seems to be something more specific happening. I would love to hear any possible explanations or avenues for investigation.

**Comment by brockallen** [comment]
I think the real issue here is not IdSvr, but OWIN and Web API working (or not working) together. I think you'll get to the bottom faster if you remove IdSvr from the equation and see how this type of code works just running Web API in the OWIN pipeline.

**Comment by Tragedian** [comment]
That's where I started with my diagnostic. I created a Web API 2 application hosted in IIS Express using this same response buffering code, but I can't reproduce the symptoms.

I've even tried hosting a Web API instance alongside IdSrv in the same host container. The issue only occurred when IdSrv generated a response.

**Comment by brockallen** [comment]
So then perhaps some of our middleware is affecting what you see. We do have some places where we also do similar buffering. 

Let us know what you find.

**Comment by Tragedian** [comment]
It appears it's an issue relating to buffering in the IIS host.

By default IIS has a policy to buffer all requests. As part of the OWIN implementation, ASP.NET exposes an additional environment property "server.DisableResponseBuffering". This is an `Action` which calls back down to the IIS host. I'm not clear on what the precise details are beyond that call, but making the call causes the subsequent write to throw an access violation.

This action is invoked by the `HttpMessageHandlerAdapter` calling an implementation of the `IHostBufferPolicySelector` interface (https://msdn.microsoft.com/en-us/library/system.web.http.hosting.ihostbufferpolicyselector(v=vs.118).aspx) to determine whether to disable buffering of requests or responses. The OWIN implementation of the interface is implemented with this algorithm:

 - If the response message has no content, do not use a buffered output stream.
 - If the response message's Content-Length header has been set and has a value greater than 0, do not use a buffered output stream.
 - If the response message's Transfer-Encoding header has been set to "chunked", do not use a buffered output stream.
 - If the response message's content is `StreamContent` or `PushStreamContent`, do not use a buffered output stream.
 - Otherwise, continue to use a buffered output stream.

I can't yet explain why the choice of not buffering the response stream would cause an access violation after writing to the response stream from a different source than a `HttpResponseMessage`. Perhaps sequencing of another event, like sending headers?

The super-quick fix is to remove the "server.DisableResponseBuffering" key from the environment prior to the call into IdSrv. The ASP.NET host adapter is gracious enough to ignore the absence of the key silently, preventing the switch to unbuffered writes.

**Comment by brockallen** [comment]
So where does your issue stand?

**Comment by Tragedian** [comment]
I've not succeeded in reproducing the issue without involving IdSrv. I've tried returning lots of "unbuffered" responses from a Web API controller, but they all succeed.

I think in order to progress, I need to play with the IdSrv source, try removing middleware to see if one of them is the trigger.

**Comment by leastprivilege** [comment]
any progress? closing for now.

**Comment by Misiu** [comment]
@Tragedian @leastprivilege I found this issue when searching solution for similar problem.
Please look at those SO questions, they both show how to get AccessViolationException exception:
http://stackoverflow.com/questions/38275886/c-modifying-owin-response-stream-causes-accessviolationexception
http://stackoverflow.com/questions/40128652/logging-middleware-not-working-when-returning-httpresponsemessage-but-works-with
