### ISSUE TITLE
OAuth Redirect Uri

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer3#2221]
I'm trying to set a redirect uri for an oauth client (client credentials flow), but it's not being enforced. It's currently allowing any client to request a token regardless of whether a redirect_uri is supplied.

Is oauth redirect uri's allowed in Identity Server?

Let me know if I'm being a tool and I'm missing something.

**Comment by leastprivilege** [comment]
client cred flow does not use redirect URIs - it is a pure api req/resp communication.

**Comment by scottbrady91** [comment]
Right you are. Silly me.

So I'll need to get myself an authorization code and then get my access token that way?

**Comment by leastprivilege** [comment]
No ;) RTFS (s == spec) :p

**Comment by scottbrady91** [comment]
But they're so dull :(

No worries, I'll stop trying to be clever now and just use client credentials like normal. Thanks!
