### ISSUE TITLE
Question: implicit, code and hybrid clarifications in identityserver3

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2222]
There are some things that need clarification: 

  1. When do I use implicit, when hybrid and when code?
  2. With each flow, which response types would I typically use and request? (code, id_token, token...)  
  3. What are those response types, i.e. what are they used for (in further calls?, automatically during authentication and authorization?)  What will I typically get?
  4. When will I get those tokens or other objects together in one shot, and when do I get them in parts?

I think clarifying this will also make things clear for all future idserv3 users.  

It would be good if you add that to your documentation.

**Comment by leastprivilege** [comment]
Sure - if I would have infinite time I will do that. In the meanwhile you probably need to do your own research - e.g. read the specs, search the archives etc.

**Comment by pashute** [comment]
At least can you make a real short table:

1. Implicit - javascript browser app: 
1.1 implicit typical 
1.1.1 round1: [requesting id_token & optionally res_token] from OP
1.1.1  OP: returns id_token (authenticated user, typically: with claims)
1.1.2  OP: if requested may return resource_token
1.1.3 Client stores (in cookies) 
    Stores the id_token for logout. 
    & Stores the res_token for later use with RP

1.1.2  round2: [requesting actual resource]
second call. This time to resource server - with resource_token from round 1.1 
1.2.1 RP: resource server opens appropriate  consent form , 
1.2.2 RP: resource server responds with resources according to user consent

----

1.2 implicit non-typical: calling a REST API
1.2.1 round 1: [requesting id_token, access_token & optionally res_token]
1.2.1.1 Server based UI - opens page without authentication nor authorization
1.2.1.2 OP returns id_token (see above)
1.2.1.3 OP returns access_token (for further use when claims and other info needed)
1.2.1.4 client stores id_token for logout
1.2.1.5 client stores access_token for getting claims and other info

1.2.2. round 2 [ requesting user information ]  ***Why in two stages? *** or is this the reply from the resource server after consent? 
1.2.2.1 UI calls the REST API passing it the access_token (of type a bearer-token)
1.2.2.2 OP returns the user information .... etc. etc. and claims. 

-----------------------------------------------
To be continued...

**Comment by brockallen** [comment]
Sorry -- we just don't have all time in the world and we expect people using IdentityServer to do some research on their own.

**Comment by pashute** [comment]
Meant that I'll do it. Will finish it offline and post when done.

**Comment by brockallen** [comment]
Ok, once you have something we can link to it.
