### ISSUE TITLE
Identity Server Architecture diagram

### ISSUE THREAD

**Issue by pessimca** [IdentityServer/IdentityServer3#2223]
Can someone help me to find Identity Server Architecture diagram to understand more on. I am reading number of forms and everyone talks about ids is implementation of OpenID Connect and OAuth2.0 but not giving in depth details and diagram. I appreciate all your help if anyone can point me to correct direction.

Thank you.

**Comment by brockallen** [comment]
The docs is what we've written: https://identityserver.github.io/Documentation/docsv2/overview/bigPicture.html

**Comment by pessimca** [comment]
Thank you.
