### ISSUE TITLE
Q: Mechanism for refreshing claims for RP

### ISSUE THREAD

**Issue by woodwardmatt** [IdentityServer/IdentityServer3#2224]
**Background**: I have IdSrv self contained in project (with MembershipReboot (MR) as the id management library), in which I've included a few identity related functions (think: register, forgotten password, verify email etc.) as custom Asp.Net MVC routines. I then have my Asp.Net MVC Client (RP) as a separate project that has all routes Authorized to enforce authentication for access to any features of the client.

**Question**: Once an end user has registered they can login immediately, deferring the email verification for MR. To ensure this still happens though I prompt the user within the client to verify their email (back over in the IdSrv project). The email verification process can be undertaken by the user fine, but when they are returned to the RP the "email_verified" claim (used to hide / show the verification prompt) is still being pulled from the cookies and is now out of sync with the *actual*  user's claims. What's the simplest way of getting the claims within the cookies back in sync?

**R & D**: I've tried a couple of different approaches which haven't really given me the result I was after. First was trying, to force a sign in and thus re-issue the cookies, but this didn't work (in either the IdSrv or the RP project):

            var ctx = Request.GetOwinContext();
            var id = ctx.Authentication.User.Identities.First<ClaimsIdentity>();
            ctx.Authentication.SignIn(id);

Another approach that was suggested was to delete the authentication session / cookie and when redirecting back to the RP include a parameter so that the call to the authentication endpoint uses the "prompt=none" and thus silently re-authenticates the user and re-issues the authentication session / cookies and thus claims. This seems like a logical approach but I'm then struggling to identify the best way to delete the authentication session / cookies without using the the generic logout routine (which ultimately means the user gets taken to the logout page:

            Request.GetOwinContext().Authentication.SignOut();

Has anyone got any suggestions / thoughts for me on this issue overall? Would really value any feedback.

**Comment by brockallen** [comment]
You can re-trigger authentication from the client app, or re-isse the cookie in the client app manually.

**Comment by woodwardmatt** [comment]
Thanks for the info @brockallen :) as always really value your time / input.

Is there an example of this in any of the samples I could refer to? (I generally have a good hunt through you to see) but happy to work through the code if there's something there.

Otherwise, could I dig a little further, and ask how you'd achieve what you've suggested? For instance are you referring to the authentication.signin() approach for re-generating the cookie?

**Comment by brockallen** [comment]
Request.GetOwinContext().Authentication.Challenge("your oidc mw name")

**Comment by woodwardmatt** [comment]
@brockallen thanks Brock :) I'll shut up now and give that a blast ;) Thanks so much for the input :)

**Comment by brockallen** [comment]
No problem.

**Comment by woodwardmatt** [comment]
@brockallen - *First Bump* worked a treat, thank you soo much that has been killing me!! 

For anyone else that comes across the thread, here's the code I ended up using in my Asp.Net MVC RP/client:

                    //Challenge Authentication and redirect to current action / controller
                    var ctx = Request.GetOwinContext();
                    var properties = new AuthenticationProperties { RedirectUri = Url.Action(actionName, controllerName) };
                    ctx.Authentication.Challenge(properties, OpenIdConnectAuthenticationDefaults.AuthenticationType);
