### ISSUE TITLE
Did identityserver3 implement SSO(Single Sign On)?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2225]
I have used identityserver3 for two months. But now I have two independent MVC Site(Site A and Site B), both of them have different domain name. I want the user only sign in once when they access Site A and Site B. Does identityserver3 have SSO? If it dosn't, what's the best practices for implementing SSO using identityserver3? Can you tell me some deailed suggestion or procedure? 
Thank you very much!

**Comment by mikeandersun** [comment]
Identityserver3  design for SSO. What you did it your two independent MVC sites(site A and site B)?
What it your issue?
The sites  (A and B  ) are asp.net 5?

**Comment by leastprivilege** [comment]
SSO is one of the fundamental features of Idsrv. You'll be fine :)

**Comment by Farwell-Liu** [comment]
The Site A and Site B are different client. They have their own client Id. They are MVC5 solution.
What I expect exactly something like this: 
Firstly, I access Site A, and then browser redirect to idsrv3 ask me to login.
Secondly, I enter my username and password to login, and then I return to the Site A.
Thirdly, I want to access Site B, I expect that It don't ask me for login again. but actually the browser redirect to idsrv3 login page.

**Comment by mikeandersun** [comment]
Can you share the section of your startup.cs that configure OpenIdConnect authentication in Site A and B?

**Comment by Farwell-Liu** [comment]
private void ConfigureIdsrv3(IAppBuilder app)
        {
            //LogProvider.SetCurrentLogProvider();

            app.Map("/core", idsrvApp =>
            {
                //var factory = InMemoryFactory.Create(
                //scopes: Scopes.Get());
                //factory.ClaimsProvider = new Registration<IClaimsProvider>(typeof(CustomClaimProvider));
                //factory.UserService = new Registration<IUserService>(resolver => new CustomUserService());
                //factory.ClientStore = new Registration<IClientStore>(new CustomClientStore());

                var factory = new IdentityServerServiceFactory();
                //factory.UseInMemoryUsers(Users.Get());
                //factory.UseInMemoryClients(Clients.Get());
                factory.UseInMemoryScopes(Scopes.Get());
                factory.ClientStore = new Registration<IClientStore>(new CustomClientStore());
                factory.ViewService = new Registration<IViewService>(typeof(CustomViewService));
                var userService = new CustomUserService();
                factory.UserService = new Registration<IUserService>(resolver => userService);
                factory.ClaimsProvider = new Registration<IClaimsProvider>(typeof(CustomClaimProvider));


                var disrvOptions = new IdentityServerOptions
                {
                    SiteName = "MyTestSite",//Embedded IdentityServer
                    SigningCertificate = WebHelper.LoadX509Certificate2(),
                    RequireSsl = false,
                    Factory = factory,
                    AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
                    {
                        EnablePostSignOutAutoRedirect = true,
                        EnableSignOutPrompt = false,
                    },
                    LoggingOptions = new LoggingOptions
                    {
                        //LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());

                    },
                };
                idsrvApp.UseIdentityServer(disrvOptions);


                //AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject;
                //JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
            });

        }

**Comment by Farwell-Liu** [comment]
public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);
            //AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.NameIdentifier;

            //第一步:初始化认证中心参数
            var appKey = System.Configuration.ConfigurationManager.AppSettings["AuthCenterAppKey"];
            var appPwd = System.Configuration.ConfigurationManager.AppSettings["AuthCenterAppPwd"];
            var authUrl = System.Configuration.ConfigurationManager.AppSettings["AuthCenterUrl"];
            var callbackUrl = System.Configuration.ConfigurationManager.AppSettings["AuthCenterCallbackUrl"];
            if (string.IsNullOrEmpty(appKey) || string.IsNullOrEmpty(appPwd) || string.IsNullOrEmpty(callbackUrl) || string.IsNullOrEmpty(authUrl))
            {
                throw new Exception("appsetting中缺少AuthCenter相关的几项参数设置!");
            }
            AuthCenterManager.Initialize(appKey
                , appPwd
                , authUrl
                , callbackUrl
                , DefaultAuthenticationTypes.ApplicationCookie
                , "CurrentUserSessionKey");
}

//-----------------------------------------------------------
//this is the config of Site A. I have packaged it to an AuthCenterManager dll.

**Comment by leastprivilege** [comment]
There is no special configuration required for SSO. Check your browser tools that the "idsrv" cookie is set after first login - and sent on subsequent login requests.

I don't know what AuthCenterManager is.

**Comment by mikeandersun** [comment]
This config may be useful, use somethings like it in the `Configuration(IAppBuilder app)` of your client apps.
```
private void ConfigureOpenIdConnect(IAppBuilder app)
        {
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = ConfigurationManager.AppSettings["Authority"],
                PostLogoutRedirectUri = ConfigurationManager.AppSettings["HostName"],
                RedirectUri = ConfigurationManager.AppSettings["HostName"],
                ClientId = ConfigurationManager.AppSettings["ClientId"],
                ClientSecret = ConfigurationManager.AppSettings["secret"],
                ResponseType = "code id_token token",
                Scope = "openid profile roles read write offline_access accounts all_claims",
                AuthenticationType = "Cookies",
                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false,
            });
        }
```
HTH

**Comment by Farwell-Liu** [comment]
I have solve the problem. It's my mistake. the Site A and Site B use the different idsrv3 Server. They are www.example.com:44300 and www.example.com:44310. I did not notice this.
Now I have another problem, If I want that Site A and Site B are SSO, and Site 1 and Site 2 are SSO. but SiteA+SiteB cannot SSO with Site1+Site2.
How can I achieve this?

**Comment by leastprivilege** [comment]
Then you need different identity servers for each "SSO group"

**Comment by mikeandersun** [comment]
Please create an issue for each issue. This helps discussions on issues be useful for others.
Thanks

**Comment by Farwell-Liu** [comment]
If I have too many SSO Group(100 or more),  I think your method may have some problem.
Ok, I will create an new issue soon. 
thanks!

**Comment by mikeandersun** [comment]
Please explain about problems when you have many SSO Gruop.
You talk about many clients in one SSO group or many SSO groups?

**Comment by Farwell-Liu** [comment]
I have created a new issue here:
https://github.com/IdentityServer/IdentityServer3/issues/2228
