### ISSUE TITLE
How to stop(or close) SSO between clients by cutomer logic

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2228]
Since Identityserver3 is set to default to support SSO between client, how to stop SSO between clients by cutomer logic. 
for example, Site A and Site B are SSO(they are group 1). Site 1 and Site 2 are SSO( they are gorup 2).
I want to close SSO between group 1 and group 2. Are there any interfaces for me to achieve this.
Maybe I have many idsrv3 servers, and I deploy them as cluster for load balance.

**Comment by Farwell-Liu** [comment]
leastprivilege said:
Then you need different identity servers for each "SSO group"
---------------------------------------------------------------------------------------------------------
mikeandersun asked me:
Please explain about problems when you have many SSO Gruop.
You talk about many clients in one SSO group or many SSO groups?
---------------------------------------------------------------------------------------------------------
If I deploy different idsrv server for each "SSO Group", I think i'll have some problem:
1.Every client in different group may have different idsrv service url, If I have 100 group and then I'll have 100 idsrv service url.
2.Can not improve utilization ratio of server cluster under load balance.

**Comment by brockallen** [comment]
I'm sorry -- I am having a hard time understanding your problem.

If you have some apps (say A, B, and C) that all need to share SSO, then they need all trust the same IdentityServer at the same URL. If you have different set of apps (say D, E and F) that need their own unrelated SSO then they need to all trust the same IdentityServer at a different URL.

**Comment by Farwell-Liu** [comment]
Every year our corporatin develops dozens of projects for about 10 companies. Company 1 has site A,B and C.Compay 2 has site D,E and F.Company 3 has site G and H.I want all the companies use the same idsrv3 server url but not different url. I perfer same url to different url, because I think the way of same url can reduce maintenance workload or avoid domain name related developing work. And it may have other benefits that I haven't think of it.
      I think if idsrv3 expose a interface it will achieve my goal. I will determine if the site A and site B are belong to the same company. If they do I will open the SSO, or I will close the SSO.
      Is my idea reasonable? Thank you!

**Comment by Farwell-Liu** [comment]
Every year our corporatin develops dozens of projects for about 10 companies. Company 1 has site A,B and C.Compay 2 has site D,E and F.Company 3 has site G and H.I want all the companies use the same idsrv3 server url but not different url. I perfer same url to different url, because I think the way of same url can reduce maintenance workload or avoid domain name related developing work. And it may have other benefits that I haven't think of it.
      I think if idsrv3 expose a interface it will achieve my goal. I will determine if the site A and site B are belong to the same company. If they do I will open the SSO, or I will close the SSO.
  Is my idea reasonable? Thank you!

**Comment by leastprivilege** [comment]
It does not work this way - you can use the same idsrv instance - but you need to distinguish somehow (e.g. by URL) which "logical" idsrv is called.

**Comment by Farwell-Liu** [comment]
Thank you, I'll try it later.
