### ISSUE TITLE
Invalid markup for signout iframes?

### ISSUE THREAD

**Issue by jimmysimonsen** [IdentityServer/IdentityServer3#2229]
Hi! We're using the new signout feature in version 2.2 and it seems that only the first clients logoutUri is called in the endsessioncallback. I've investigated the generated markup in endsessioncallback and it looks like the iframe:s aren't closed correctly? Here is an example.

http://login.local/identity/connect/endsessioncallback?sid=cbad77d913cc1ad61b4cbc0c58828856;

```
<!DOCTYPE html>
<html>
<head>
    <title>SignOut</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <iframe src='http://login.local/account/logout/'>
<iframe src='http://client1.local/account/logout/'>
</body>
</html>
```
Regards,
Jimmy

**Comment by brockallen** [comment]
Done, thx.
