### ISSUE TITLE
CoreCLR (dotnet5.5) support

### ISSUE THREAD

**Issue by chaliy** [IdentityServer/IdentityServer3#2230]
Is there any plans to support dotnet5.5 (CoreCLR, .NET Core)?

**Comment by leastprivilege** [comment]
Yes :)

**Comment by chaliy** [comment]
:), do you have any specific dates? Or month? We are about to start new project and looks like we have almost everything compatible with coreclr except identityserver3.

**Comment by leastprivilege** [comment]
Beginning next year...
