### ISSUE TITLE
Thinktecture.IdentityServer3.AspNetIdentity deprecated?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#2231]
Hello 

I am using idserv3 1.6.2.

Now I need Thinktecture.IdentityServer3.AspNetIdentity intenting to use AspNetIdentityUserService.

nuget tells me: https://www.nuget.org/packages/Thinktecture.IdentityServer3.AspNetIdentity ==> deprecated

What can I do to use AspNetIdentityUserService?

**Comment by leastprivilege** [comment]
We switched to source code based packages. You could pull the source code from github and use that.

**Comment by brockallen** [comment]
The release notes are usually a good read when upgrading: https://github.com/IdentityServer/IdentityServer3/releases

**Comment by davidmrichter** [comment]
release notes do not indicate something about AspNetIdentity package...

**Comment by brockallen** [comment]
> release notes do not indicate something about AspNetIdentity package...

Right -- it's a different package and not part of IdentityServer3.
