### ISSUE TITLE
Changing CryptoProvider

### ISSUE THREAD

**Issue by Fasjeit** [IdentityServer/IdentityServer3#2235]
Hello. So I an quite new in IdentityServer. I have to change all cryptographic operation in IdentityServer. I have some classes compatible with symmetricAlgorithm, SymmetricAlgorithm and HashAlgorithm and certificates which contain keys for these algorithms. Is it possible to completely get rid of RSA/Sha in IdSrv?  If yes what classes (interfaces) do I need to look at and use (change)? Thanks in advance.

**Comment by leastprivilege** [comment]
what's the use case?

**Comment by Fasjeit** [comment]
Well, here in Russia we have to use so called "Certified Cryptography" to use in our software products. So if you want software to be used in any organization you have to use specific algorithms in specific crypto providers which are "approved" by government intelligence service. So unfortunately we can't use RSA, SHA and AES, but have to use GOST 34.10, GOST 34.11 and GOST 34.12 (28147-89) instead. It's sound quite weird but unfortunately it's real. We need to implement OpenId, but if we want to use it we have to use GOST crypto algorithms, not RSA-SHA-AES.

**Comment by Fasjeit** [comment]
In fact the Main problem is using non-RSA (and non-DSA) signing certificates

**Comment by leastprivilege** [comment]
you can implement ITokenSigningService to take over token signing. .NET itself also has a feature called CryptoMappings to exchange algorithm by config (maybe worth investigating).

**Comment by leastprivilege** [comment]
Also - the OpenID Connect spec has a list of allowed crypto algorithms - so I guess that means that you need to break the spec by purpose to use OIDC in Russia?

**Comment by Fasjeit** [comment]
Unfortunately yes - the specs have to be broken. It's real pain to break so many ready to use solutions only becouse we a not allowed to use RSA. This is our reality the government force us to live in.
Anyway thanks for targeting ITokenSigningService for me. I hope it will help.

**Comment by leastprivilege** [comment]
progress?

**Comment by Fasjeit** [comment]
Yes, kind of) Thanks for help. But more problems to come.
So I successfully managed to write custom ITokenSigningService, but have also to rewrite System.IdentityModel.Tokens.JwtSecurityTokenHandler, SignatureProviderFactory and some other classes from System.IdentityModel. So for now server works pretty nice, but unfortunately I have to change your DiscoveryEndpointController so for now it's not identityServer extension library, but a different version. But It's OK.
The current problem I am facing is how to configure WEB API properly to work with new tokens. As I understand KATANA\OWIN while using your IdentityServer3.AccessTokenValidation call JwtSecurityTokenHandler to validate token. So the last step to win is somehow change gefault JwtSecurityTokenHandler by my custom GostJwtSecurityTokenHandler, inhereted from original. As I see Microsoft.Owin.Security.Jwt.JwtBearerAuthenticationOptions have some parameter (TokenHandler) to set it, but (for now) I can't see any way to make it using IdentityServerBearerTokenAuthenticationOptions.

Can you give me an advice what should I do how to configure WebApi properly to use custom JwtSecurityTokenHandler?

**Comment by leastprivilege** [comment]
It is possible that we don't wrap that parameter. You can open a feature request issue in our access token validation repo.
