### ISSUE TITLE
Can I use the thinktexture STS for mixed mode?

### ISSUE THREAD

**Issue by KrishanGorav** [IdentityServer/IdentityServer3#2237]
Hi,
I want to configure my relying party to use STS for mixed mode (Forms + Windows) authentication.

First I will check if windows user is authenticated and that windows user is mapped to any application user in database then allow him to proceed otherwise show login screen to provide user name and password.

Is it possible? If yes then please help me understand the steps required.

Thanks & Regards,
Krishan

**Comment by brockallen** [comment]
This is complicated. The first thing for you to answer and/or understand is "what does it mean for a user to already be authenticated with windows" and "how would a web server know this". Once you've solved that problem, then you have the start to your solution. I don't know if there's a right answer.

Another topic for you to go research to help guide your requirements -- "home realm discovery". 

Having said all of that, you can use IdentityServer to broker users that use integrated windows authentication and password based authentication. It just might not work as easily as your requirement above wants.
