### ISSUE TITLE
Send and consume reference token via WCF

### ISSUE THREAD

**Issue by urbanhusky** [IdentityServer/IdentityServer3#2241]
Hi,

I'm using IdentityServer3 to provide and verify access tokens in an ASP.NET MVC/WebApi application.
This application needs to consume several WCF services.

How can I
1) send the token to the service without having to explicitly add a parameter to each contract
2) retrieve this token and verify it - the actual verification once I have the token is less of an issue,  figuring out how to/where to implement it so that each request authenticates and sets the current principal is the hard part

I've tried to set it up similar to http://leastprivilege.com/2012/10/26/using-claims-based-authorization-in-mvc-and-web-api/ but I cannot use code to configure the WCF service, I must rely on the `App.config` (due to the use of Ninject and self-hosted WCF services). I tried to migrate the services and client (i.e. the web application) from `wsHttpBinding` to `ws2007FederationHttpBinding` but so far had no luck setting this up.

I modified the sample `IdentityServerWrappedJwtHandler` to use an empty constructor (because I'd like to authenticate based on the claims) and defined it in the `App.config` like so:
```xml
<system.identityModel>
	<identityConfiguration name="identity" >
		<securityTokenHandlers>
			<clear/>
			<add type="MyService.JwtTokenSupport.IdentityServerWrappedJwtHandler, MyService"></add>
		</securityTokenHandlers>		
	</identityConfiguration>
</system.identityModel>
```

I'm creating the channel like so:
```c#
public abstract class ServiceClientBase<TService>
{

	private ChannelFactory<TService> channelFactory;

	protected ServiceClientBase()
	{
		this.channelFactory = new ChannelFactory<TService>(this.GetType().name);
	}

	public TService CreateChannel()
	{
		var tokenClaim = ClaimsPrincipal.Current.Claims.FirstOrDefault(x => x.Type == "token");
		if (tokenClaim == null)
		{
				throw new Exception("Current user is not authenticated.");
		}

		var xmlToken = WrapJwt(tokenClaim.Value);
		return this.channelFactory.CreateChannelWithIssuedToken(xmlToken);
	}
}
```

with `WrapJwt(token)` being the same as in the sample.

Any help would be greatly appreciated, I'm pretty much stuck right now.

**Comment by urbanhusky** [comment]
I managed to solve this:
* The code pretty much corresponds to the same or very similar sections in the `app.config`. So use `ws2007FederationHttpBinding` etc.
* You have to use `TransportWithMessageCredentials` security, use `https` instead of `http` on the addresses, change the mex binding to `mexHttpsBinding` (and set `<serviceMetadata httpGetEnabled="false" />`
* For development, the ports must be somewhere between `44300` and `44399` because those use the localhost certificate and users are allowed to host services there (for deployment/test, you'd have to configure them properly)
* I'm not sending a JWT but a reference token and instead of using Microsoft's JWT validator, I'm using the `IntrospectionClient` to validate the token.

**Comment by leastprivilege** [comment]
Cool. you could contribute back the introspection part to the existing sample. 

Check the token- if it contains a dot use the JwtHandler - otherwise the introspection client)
