### ISSUE TITLE
Recommended approach for federation and shared resources?

### ISSUE THREAD

**Issue by bblunden** [IdentityServer/IdentityServer3#2242]
Hi

In a nutshell, we would like to sign on to one IDS3 and gain token based access to resources protected by another IDS3.

We have IDS3 v1.6 (IDP1) providing Hybrid Flow access to multiple MVC katana UIs (clients).  These UIs provide Authorize Bearer Tokens to gain access to various protected apis (scopes).  Lets call this Installation 1. We also have installation 2 with identical UIs and apis all being protected by another IDS3 v1.6 (IDP2).  ClientID and Scope names are identical in each installation however the underlying data stores are unique.  Everything is working well for each of installation.

Now, we would like a user to sign-on to one SSO (say installation 1) and have it's clients be able to access resources from the other installation, as well as its own.  The data sources beneath the apis are different and we want to provide a "merged" data effect.  So, we would like a UI to be able to access the same scopes on each installation.

I've been reviewing AuthenticationOptions.IdentityProviders and AuthenticateExternalAsync. I believe I need to create a ConfigureAdditionalIdentityProviders method using OpenIdConnectAuthenticationOptions and extension method UseOpenIdConnectAuthentication in similar fashion to the google, facebook and twitter samples.  Are arc_values relevant for our scenario?

I'm unclear on how to authenticate with the opposing IDP too so I thought it would be good to get some feedback before setting off, perhaps in the wrong direction.  If anyone can provide insight on the following, I would appreciate it.

1. What is the best way to get access tokens from the "other" installation?
2. Is it possible to use a single access token across installations?  how?

Best Regards,
Brent

**Comment by bblunden** [comment]
Forgot to mention... we are using jwt with ValidationMode.Local

**Comment by leastprivilege** [comment]
You would need to get the access_token from the initial idsrv (using whatever flow) and then use a custom grant (in the 2nd idsrv) to convert that external access token to a new access token that your apis trust.

**Comment by palsmadal** [comment]
Hi

I'm new to IdentityServer and not sure if this is the place to ask for this, but I wonder if you have a sample on how this would work?
