### ISSUE TITLE
Question: Multiple local user services

### ISSUE THREAD

**Issue by a-tok** [IdentityServer/IdentityServer3#2243]
Hello,

Are multiple local user services allowed by default using IAppBuilder.Map("/path", ...)?

The reason that I'm asking, is that all my googling points to "no" however.. I was able to map a second local user service to a different path and it appears to be working. My concern is that this feature might go away by accident in the future versions. :)

Thank You!!!

**Comment by brockallen** [comment]
You can register multiple identity servers based upon different paths, yes. I know others have done this, but I have a vague recollection of some problems. 

What are you really trying to do?

**Comment by a-tok** [comment]
Assuming clients, scopes, etc.. are already defined to facilitate this mechanism. 
We have two applications:

app 1 - configured to authenticate through IdentityServer3 via LDAP
app 2 -  is a customer oriented portal. The users belong to a sql server db and they should be able to login into app1 using their credentials. app2 is essentially a trusted external idp for app1.

My plan is to define an end point for app2 and implement the local user service to query the db. Then I would define an external OpenIdConnectAuthentication request for app1 and point it to this endpoint.

I can as easily create a new instance of IdentityServer3 for app2, but to reduce the complexity I would prefer to keep it in the same one where I configure app1. What are the best practices in this case?

**Comment by leastprivilege** [comment]
the different apps can pass a hint to identityserver which data source to use for authentication - e.g. the tenant parameter. Check the endpoint docs.

**Comment by a-tok** [comment]
@leastprivilege - Thanks, that makes complete sense to me and I will use this method from now on. I'm still a little confused though :).  Is using IAppBuilder.Map() to define separate custom user services a big no no? Should I always use a single IdentityServer instance per user service?

**Comment by leastprivilege** [comment]
you can also host multiple idsrvs - it just seems unnecessary.

**Comment by a-tok** [comment]
Is it possible to load a signing certificate per tenant? If so, any suggestions to how would I accomplish this?

**Comment by leastprivilege** [comment]
that's a new issue.
