### ISSUE TITLE
Question: Implementing custom flows

### ISSUE THREAD

**Issue by amilsil** [IdentityServer/IdentityServer3#2244]
We are trying to implement an IdentityServer, in which after the user logs in to the IS, the user is shown a list of accounts of one subsystem, out of which she can select one. Apparently here, one IS user can have multiple accounts connected per subsystem. After selecting, the user should be redirected to the subsystem with an id_token. 

We can hook in to PostAuthenticateLocalAsync and show an intermediate accounts list page. But this page is by-passed when the user is already logged in to the IS. 

As we heard about Custom Flow, we had the hope that custom flow would equip us with ability to join custom interactions (with custom pages) and make our own flow. But, we haven't been able to find a proper example of if the custom flow can do this, or how the custom flow really works. 

Is this possible to be done with custom flow? 

Highly appreciate your suggestions.

**Comment by leastprivilege** [comment]
Once the user is logged in - the user service is not being called anymore. adding a `prompt=login` to the authN request might give you the behavior you want.
