### ISSUE TITLE
Landing page/Home page for Identity Server

### ISSUE THREAD

**Issue by phoenixjun** [IdentityServer/IdentityServer3#2245]
Hi,

We would want to build the identity management system using identityserver3 as the base. Like a portal to register, change password, etc... 

One of the requirement is to have a home page for the user like the login page. User can click to login or create new user etc. However, It seems like that the login page always expect the user comes with a login message which we don't really have when comes direct into the system.

Any suggestion about how to build that on top of the identityserver package?

Thanks

**Comment by brockallen** [comment]
The login page in IdSvr is meant for OIDC. If you want your own login page, then you can build your own login page and then use the OWIN environment extensions to log the user into IdSvr.
