### ISSUE TITLE
Session management for clients with optional login

### ISSUE THREAD

**Issue by loftum** [IdentityServer/IdentityServer3#2246]
This is a question/ feature request/ discussion on OIDC session management.
I apologize for the long text, but did not find anywhere else to post this.

We are monitoring end users' login status by implementing the RP/OP iframes as suggested here: https://openid.net/specs/openid-connect-session-1_0.html

Short version:
- Would it be reasonable for a client to send sessionState = "none" to the OP frame when no end user is logged in at the client?
- Would it make sense for the OP to return "ended" if the client does have a valid sessionState, but the OP session has ended?

Or would this lead to any security issues that we have not thought about?

Longer version:

In the draft, the RP asks the OP about current login status by sending its own session state. The OP's script returns "changed" or "unchanged" (or "error"). This works well as long as the client has a session state (the user is logged in).

But for a client A with optional login where the user is not logged in, it is hard to detect that the user has logged in on another client B: Client A does not have any sessionState in this case, and the OP script would simply return "error" for any invalid sessionState (or "changed" if the RP sends a fake sessionState).

Would it be reasonable for the OP script to do something like this?

```
var currentSessionId = getBrowserSessionId();
if (sessionState === "none")
{
  return !currentSessionId ? "unchanged" : "changed";
}
```

or would this lead to security holes? (The "none" sessionState is of course not validated/rehashed in this case).

It would also be nice if the OP script would return "ended" in the case that the client has a valid sessionState, but there is no longer a session at the OP. In that case the client would not have to do the extra authorize call to find this out itself.

**Comment by brockallen** [comment]
Yea, I suspect the spec was written the way it was to prevent leaking too much info about the state of the logged in user. Unfortunately I think the way it's written also interferes with the scenario you present.

I'd suggest providing this question/feedback to the spec committee so they can provide a definitive answer. They maybe have already considered this (but then again, maybe they haven't).
