### ISSUE TITLE
IdentityServer 3 + Sitecore !

### ISSUE THREAD

**Issue by Sivalingaamorthy** [IdentityServer/IdentityServer3#2247]
I have a requirement to implement a OWIN middleware for claims authentication on a new Sitecore 8.x project, considering IdentityServer 3 as a hostable service on the IIS to authenticate the login user. Any suggestions, inputs, thoughts to have this implementation successful ?

**Comment by leastprivilege** [comment]
never used sitecore before - but this has been done before.

**Comment by jeremy001181** [comment]
We have similar requirement as yours, instead of building sitecore on top of owin , we use JavaScript implicit flow

**Comment by leastprivilege** [comment]
any progress? closing. feel free to re-open if needed.
