### ISSUE TITLE
android app passwordless login

### ISSUE THREAD

**Issue by talarari** [IdentityServer/IdentityServer3#2251]
Hey, 
I'm developing an android app and want to protect some apis that serve user data.
my flow is a little different and i cant figure out which grant flow to use if any, and how identityServer helps me with this (maybe it doesnt?)

i want to implement something similar to SMS or EMAIL paswordless login (similar to this:
https://auth0.com/docs/connections/passwordless) but over GCM/APN.

basically this is the flow:
1. the user opens the app and hit a registration endpoint with a user name and gcm registration id
2. the server would then send a push notification to the user containing a one time password (either HOTP or TOTP)
3. the app will receive this password and hit the authorization(or token? not sure)  endpoint again with its username and one time password just received and will receive a jwt token  in return.
4. the app will attach the jwt token to the header of api requests to resource servers (multiple microservices)
5. resource servers will validate the jwt token to ensure its valid an that the requested operation is allowed under the jwt token scopes.

another thing i'm not sure about is - do the resource server apis need to contact the identityServer for each request to validate the token? 

i'm a bit lost here, this feels like it might be a custom grant, but i'm not sure how to go about this .
any help would be greatly appreciated, thanks!

**Comment by brockallen** [comment]
Maybe a custom grant type -- the TOTP is the custom grant. Only problem is that the TOTP with only 6 or so numbers is easily brute forecable, so you'd need something else I think. Just something to think about...

**Comment by talarari** [comment]
If its limited to a few minutes is it still easily brute. Forceble? 
I could also use longer TOTP since the user doesn't type it back its automatically used

**Comment by talarari** [comment]
Ok so i'm thinking custom grant flow for one time password.
i can see that i register a custom grant validator to check the one time password supplied by the client/user matches the one generated for him.

my question is: which endpoint should the client hit to start this async process, e.g : generate a one time password for the user and sent it to him.

it feels like it kind of matches the authorization endpoint (just like its starts the process with redirect to login on a form).
BUT : i don't see any extension points for that endpoint in the docs.
i was thinking of something like :
GET /connect/authorize?client_id=client1&scope=openid email api1&**response_type=one_time_password&redirect_uri=gcm:registrationId/sms:phoneNumber/email:emailAddress**

how would you go about this? create a separate endpoint?

**Comment by brockallen** [comment]
If it's programmatic then it'd be a custom endpoint. The authorize endpoint is meant for a browser.

**Comment by talarari** [comment]
if i'm using a custom endpoint and sending a one time password, does it make sense to use the resource owner credentials grant type? 
if i'm implementing a custom user service i will validate the password anyway (make sure it matches the generated one and that the ttl hasn't expired)

**Comment by brockallen** [comment]
yea, perhaps. i wasn't sure if you wanted something beyond the TOTP. if a username is passed, then you can track brute force attacks and do lockouts.

**Comment by talarari** [comment]
Thanks very helpful, I'll give it a try
