### ISSUE TITLE
Validating user identity in api request

### ISSUE THREAD

**Issue by talarari** [IdentityServer/IdentityServer3#2252]
If i have an api endpoint that looks like this

[Authorize]
[HttpGet]
public async Task<sensitiveData> GetSensitiveData(string userId)
validating the jwt token validate the issuer and audience , but where and how do i check the subject claim in the access token matches the user id requested?

should it just be part of the endpoint logic? or is there a more elegant way? some kind of middleware?

also, if my endpoint looked like this:
public async Task<sensitiveData> GetSensitiveData(string someResourceId)

what would be the best way to make sure the user requesting the resouce has access to it?
where should this permission (user to resouce) be saved? in the identity server or api?

Thanks!

**Comment by leastprivilege** [comment]
Yep write some good old C# code for that ;) You get the claims from the User property on the controller.

IdentityServer does not deal with permissions - that is app specific.
