### ISSUE TITLE
IdSrv3 auto redirect when using External Login (using "IdSrv3" version="2.2.1")

### ISSUE THREAD

**Issue by khoainv** [IdentityServer/IdentityServer3#2255]
I have apply after tip

https://github.com/IdentityServer/Documentation/issues/136

//https://github.com/IdentityServer/IdentityServer3/issues/1000
                core.Map("/post-logout-callback", cb =>
                {
                    cb.Run(async ctx =>
                    {
                        var state = ctx.Request.Cookies["state"];
                        await ctx.Environment.RenderLoggedOutViewAsync(state);
                    });
                });
https://identityserver.github.io/Documentation/docsv2/advanced/federated-post-logout-redirect.html
coreApp.Map("/signoutcallback", cleanup =>
      {
         cleanup.Run(async ctx =>
         {
            var state = ctx.Request.Cookies["state"];
            await ctx.Environment.RenderLoggedOutViewAsync(state);
         });
      });

 var signOutMessageId = n.OwinContext.Environment.GetSignOutMessageId();
                                if (signOutMessageId != null)
                                {
                                    n.OwinContext.Response.Cookies.Append("state", signOutMessageId);
                                }

But when i logout system not run.
Can you help me?

**Comment by leastprivilege** [comment]
any progress? closing. feel free to re-open if needed.
