### ISSUE TITLE
Integrating Identity Server 3 Openid Connect with CMS applications like Dotnetnuke (DNN)

### ISSUE THREAD

**Issue by radrad** [IdentityServer/IdentityServer3#2256]
I want to add Identity Server 3 v.2 to my DNN (Dotnetnuke) CMS portal so that I can have both external clients (native mobile, javascript SPA, native destkop)
my DNN Web application, access WebAPI hosted in my DNN Web application.

DNN has many extensibility points, the most important being a module which is of these types: Webforms, MVC or SPA.
DNN has its own user, roles store and permissions. Permissions to  actions in DNN web site like "view" and "edit"  modules  are assigned to roles.

Permissions in DNN can be assigned to pages (which is the container of page modules), modules (can inherit permissions from the containing page or have their own) and to files and folders that are uploaded to DNN Web application.

DNN has its own login screen for local user store and can have external login providers such as Facebook, Google etc. through DNN's authentication provider extensibility.

I need to figure out how to integrate Identity Server with its:
- Authorize Endpoint
-Token Endpoint
-UserInfo Endpoint

IdentityServer.Samples has these clients:
-Code Flow Client Demo
-Implicit Client Demo
-Hybrid Native Client Demo
-Katana Hybrid Client Demo
-Client Credentials Flow Client
-Client Credentials Flow Client with Client Certificate
-Custom Grant Client
-Resource Owner Flow Client

Which one of these clients are the best to use to integrate with DNN given my requirements? More then one?

DNN already has support for these providers:
-Facebook,
-Google,
-Live Authentication,
-Twitter and
-Library for DNN OAuth Server Support

I would like to know if Identity Server belong to this list or does even more?

How would I go about preserving DNN login page and still use Identity Server Endpoints?
Will I need to add Identity Server as yet another Authentication provider?

I would probably like to suppress consent screen for users accessing DNN WebApi using DNN Web application directly (with all types of modules),and use Identity Server's Endpoints from Native Windows and Mobile as well as clients coming from third party web sites or clients.

Is there any Identity Server 3 integration with other open source CMS applications, like Orchard, Umbraco, Kentico etc .

I would appreciate if someone will outline steps and pseudo examples on how to achieve this integration.

**Comment by leastprivilege** [comment]
I guess you need to find out if DNN has support for OpenID Connect.

**Comment by radrad** [comment]
Dominick,
I watched all your courses on pluralsight, NDC and Identity Server examples and I am really trying hard to see how would this work with a CMS web app like DNN (you can ignore this particular CMS)

I wanted to know how would I go about doing it for a CMS web application that is based on Web forms architecture without OWIN architecture as an MVC based client and a SPA client like Angularjs and native mobile app.
DNN don't have OpenID Connect implementation yet, but DNN guys just added a few days ago (what they call):
"DNN Json Web Token Authentication (JWT) library for cookie-less Mobile authentication clients"
that is implemented as a DelegatingHandler (a DNN module that can be added to the request pipeline). The module's code is here:
https://github.com/dnnsoftware/Dnn.Platform/tree/development/DNN%20Platform/Dnn.AuthServices.Jwt
They added a capability to add your own DelegatingHandler in DNN pipeline using web.config configuration section.

It would be great if you can take a quick look at these 3 classes to see what else is needed to fully add OpenID Connect functionality:
- Dnn.AuthServices.Jwt/Auth/JwtAuthMessageHandler.cs
- Components/Common/Controllers/JwtController.cs
- Dnn.AuthServices.Jwt/Services/MobileController.cs

I think the key class here is JwtAuthMessageHandler with its method:

        private void TryToAuthenticate(HttpRequestMessage request)
        {
            try
            {
                var username = _jwtController.ValidateToken(request);
                if (!string.IsNullOrEmpty(username))
                {
                    if (Logger.IsTraceEnabled) Logger.Trace($"Authenticated user '{username}'");
                    SetCurrentPrincipal(new GenericPrincipal(new GenericIdentity(username, AuthScheme), null), request);
                }
            }
            catch (Exception ex)
            {
                Logger.Error("Unexpected error in authenticating the user. " + ex);
            }
        }

From what I can see when validating a JWT token they are just using Access Token
and after it has been validated this module sets the current principal, the same way they do when using a session authentication cookie to extract the user name
HEADER:
{
  "type": "JWT",
  "alg": "HS256"
}
PAYLOAD:DATA
{
  "sub": "dnnusername",
  "nbf": 1,
  "exp": 4102444799,
  "sid": "0123456789ABCDEF"
}

DNN's Membership provider is an extension of ASP.NET Membership 2.0 and it will allow the code in WebAPI controllers to retrieve a UserInfo object by calling GetUser(int portalId, int userId)
where userId is "sub" claim from above Access Token. So I was wondering if ID token is useful at all in a CMS web app like DNN and Identity Server 3 can only be used as a pure OAuth sever.

@Dominick, Can you shed some light on this matter?
Thanks

**Comment by leastprivilege** [comment]
No I can't. OIDC is an industry standard - if DNN refuses to implement it then this is the wrong platform.

**Comment by leastprivilege** [comment]
I am closing this issue. feel free to open a new one with idsrv specific questions.
