### ISSUE TITLE
IdentityServer3.Core.Models.Client support for multiple Flows (IdentityServer3.Core.Models)

### ISSUE THREAD

**Issue by vish-k** [IdentityServer/IdentityServer3#2257]
Hello,
Why IdentityServer3.Core.Models.Client does not support multiple flows like AuthorizationCode along with Implicit ?

Is it possible to extend the model to support multiple flows ?

Thanks for your help.

**Comment by leastprivilege** [comment]
That would be a security risk since one could "downgrade" the protocol from cod to implicit by changing the response type parameter.
