### ISSUE TITLE
Chrome now refusing `data` URIs for images due to CSP

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#2260]
CSP policy only indicates 'self' and apparently now 'data:' URIs don't count as self (anymore).

**Comment by brockallen** [comment]
I'm thinking of making the sample hosts set the ImgSrc and not changing anything in core for this.

**Comment by brockallen** [comment]
removed logo from sample client config.

**Comment by CrescentFresh** [comment]
> making the sample hosts set the ImgSrc

Wait so Brock, customizers like myself can't use data: uris anymore it seems. What does the above mean as an alternative then?

**Comment by brockallen** [comment]
You can use "data:" as a ImgSrc in the CorsOptions.

**Comment by leastprivilege** [comment]
CspOptions

**Comment by brockallen** [comment]
Yes, that's what I meant... *blush*
