### ISSUE TITLE
Roles Claim Json Serialization

### ISSUE THREAD

**Issue by Nicholi** [IdentityServer/IdentityServer3#2262]
I noticed the "roles" property will serialize as a string if there is only 1 role claim for that user, but if there are multiple then it will serialize as an array. Guessing this is just the generic behavior for how IdentityServer3 handles duplicate claims with the same name, which makes perfect sense. Even though "roles" is a common claim (but not mentioned in oidc spec) couldn't we just make it always serialize as an array regardless? Or is there perhaps a more generic way to enforce a certain claim to always be treated as an array in IdentityServer config?

Since it's serializing as both now, I assume changing it to always be an array wouldn't break anything. But then you are enforcing special behavior for a non-standard claim name, so I could understand if you don't want to do that. It's just sort of problematic for consumers to need to check if property is a str or an array before handling, for such a very common claim.

**Comment by leastprivilege** [comment]
these are the rules for JSON object serialization.

**Comment by ircnelson** [comment]
I suggest this article http://www.garycrawford.co.uk/complex-claim-values-with-wif/
