### ISSUE TITLE
How to return callback calls with https always

### ISSUE THREAD

**Issue by pessimca** [IdentityServer/IdentityServer3#2264]
Hi,

We have implemented IDS successfully and it is working good. But today observed that Safari browser is not working and it is going to infinite loop for auth token. Our configuration is, we have LB with https (443)and nodes with http(80). Disable SSL and added VIP addess to IDS configuration. 

Otherbrowsers (IE, Chrome and Firefox) are working but not on Safari. did some comparisons and below are findings:
* All redirect calls are going to HTTP and then redirected to HTTPS
* These HTTP and HTTPS are working good except safari
* Safari not able to redirect and it send request back to main url and then going to infinite loop

I believe someone might have faced this issue on safari or other browsers. Could you please let me know you guys fixed this issue.

I appreciate all your help.

thank you,

**Comment by totpero** [comment]
Hi,
I use this extension https://github.com/Readify/Owin.ForceHttps to force https from http.
if is this what you want.

**Comment by pessimca** [comment]
Thanks for your suggestion.....

I added below code to resolve my issue:

OnValidateClientRedirectUri = ctx =>
{
.............
.................
 if (ctx.Request.Uri.Host.ToLower() != "localhost" && ctx.Request.IsSecure == false)
      url = url.Replace("http", "https");
.................
................}

this resolved my issue. This issue was happening mainly on safari browser and other browser are working good!!!!
