### ISSUE TITLE
What is expected implicit flow behaviour regarding access token claims?

### ISSUE THREAD

**Issue by n-alex-white** [IdentityServer/IdentityServer3#2265]
When doing implicit flow for openid connect, I post to the authorize endpoint and receive back an id token and an access token.

If I include additional scope values to request additional claims (http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims), I would expect to see those additional claims in the access token, but at the moment I see them in the id token but not in the access token.

I had expected that to be the case if no access token was issued, but when one is requested as part of the implicit flow the access token should have the additional claims, no?

Is this by design in IDS3, or is there a problem here?

Thanks

**Comment by brockallen** [comment]
Your Scope Type and the containing ScopeClaims affect which claims go into which token.

**Comment by n-alex-white** [comment]
Thanks, I'll check that out

**Comment by leastprivilege** [comment]
any progress? closing. feel free to re-open if needed.
