### ISSUE TITLE
Generating local user access token by validating external access token (Twitter)

### ISSUE THREAD

**Issue by asunchu** [IdentityServer/IdentityServer3#2266]
I m building a native mobile application and multiple web APIs to support the functionality of a native app, Im having all requests for my web APIs authenticated,so Im using IdentityServer3 with ASP.Net Identity

I want to use social login providers for my native app (Twitter and Digits), and I want the native app to take care of authenticating with Twitter, once authenticated an external access token from Twitter will be available to the native app. Now, i want provide end points in my Identity Server 3 setup to support validating external access token and generating a local access token based on user?

What would be the best way to achieve this with asp.net identity and identity server 3?

This author of this blog post, seems to be explaining exactly what I m trying to achieve, but, he is not using identityserver3 http://bitoftech.net/2014/08/11/asp-net-web-api-2-external-logins-social-logins-facebook-google-angularjs-app/

**Comment by mderriey** [comment]
IdentityServer3 has most of this, but one gotcha is that you have to use the provided login page, e.g. have some kind of web view in your native application.

Here is the flow:

 - The user wants to login to your application. a web view shows the user IdentityServer3 login page
 - The user chooses one of the external login provider you configured in IdentityServer3 with the help of OWIN middlewares
 - The user is now redirected to the login page of the chosen external login provider and logs in there
 - The external login provider redirects the user to IdentityServer3 and provides information about the user. This is the perfect time for you to handle that event in your `UserService`, and check if, let's say, the email Twitter gave you back exists in your ASP.NET Identity database. If not, you could can a new local user with the information Twitter gave based on the scopes you required
 - Now that you have a local user, IdentityServer3 logs him in automatically and redirects to your native application, providing a local access token

I think steps 1 & 2 can be omitted with the help of the [`acr_values`](https://identityserver.github.io/Documentation/docsv2/endpoints/authorization.html). One of them, `idp`, instructs IdentityServer3 to directly redirect the user to the external login provider login page, without him being presented IdSrv login page and having to click on the specific login provider button.

For the last step, if you wonder how your native application can handle an HTTP redirect, you can check [this project](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WpfClient%20(Hybrid)) in the Samples repo, more particularly [this file](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/WpfClient%20(Hybrid)/LoginWebView.xaml.cs). I don't know if iOS or Android's implementations of a web browser provide hooks like this one, though.

I had also read about the fact that an application can be registered as the default one for a protocol. The idea is to register an application for a specific protocol, let's say `my-native-application://`. One can then register the application with IdSrv with a redirect URL of `my-native-application://callback`. The OS would catch that redirect and hand it over to the registered application. I have never seen an example of that, though.

I hope this will help you.
Cheers.

**Comment by asunchu** [comment]
Thanks for the explanation mderriey, this flow would definitely work with Twitter and other login providers with an extra click from the UX perspective, but I m trying to understand how something like Digits (https://docs.fabric.io/android/digits/digits.html) would work?

**Comment by mderriey** [comment]
I didn't know about Digits, I assumed it was another login provider with OAuth support.
I had a quick look at their documentation but couldn't find anything interesting web-related.

**Comment by leastprivilege** [comment]
any progress? closing. feel free to re-open if needed.
