### ISSUE TITLE
Go to register page instead of signin page

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3#2267]
Hi

We have a requirement where needs to redirect customer to a register page after authorize endpoint instead of `identity/login`

I understand that there is no register page in identity server3, so we have implemented a Mvc register controller where is able to issue login cookie, but how can I smoothly tell the idsvr's authorize endpoint to redirect to my register URL instead of login URL?

The only way I can think of is to configure the my mvc register endpoint as a external id provider so that when the client triggers an authorize endpoint the request needs to have its idp value in acr_values

Can you advice if this approach will work please? or is there a better way to do?

Many thanks

**Comment by brockallen** [comment]
How do you know the user does not already have an account?

**Comment by jeremy001181** [comment]
We don't, but we have a login link on register page so that user can sign
in if already registered with us

The login link points to idsvr3 login URL using existing signin id that was
generated when register page loaded.

We are using embedded Mvc sample, we embedded idsvr3 in our MVC app which
has a register Mvc controller, on its GET request it generates signin id as
well as drop signinmessage cookie; on POST request it registers user and
issues login cookie and do redirect afterwards

We have requirement to show register page instead of login page if request
is from certain clients

**Comment by brockallen** [comment]
The only hook we have that I can think of right now is to do the redirect in the PreAuthN in the user service. 

Another idea is to write middleware to check the incoming URL for the login page and change it to your page instead. I think this voids any warranty though :)

**Comment by jeremy001181** [comment]
Thank you

I will look into it
