### ISSUE TITLE
Redirects to external WsFederation provider login pages stop working

### ISSUE THREAD

**Issue by mddi3** [IdentityServer/IdentityServer3#2268]
Our ID application must reach out to an external ADFS server to provide authentication. Things will work fine for a while (sometimes weeks, often only hours), but at some point, connections to the external ADFS server will stop working. Any redirect to that specific external provider are never fulfilled The remote ADFS login form never appears. 

The ID application itself is responsive, and local logins and other remote providers (like Google) continue to work. An IISReset seems to be the only way to fix the problem.

We don't know how to trigger the problem.  I have to wait for it to happen. We have a powershell script that can detect the problem, and potentially reset the server, but that's not a viable solution.

I've configured a development server for remote debugging. When the application enters this state, the only obvious symptom, or difference from how it normally operates, are multiple worker threads waiting to complete.  (screenshot attached)

![2015-12-09 09_13_00-idsvr](https://cloud.githubusercontent.com/assets/5797648/11691820/06ca3358-9e5a-11e5-8e4f-36a1da3a2d8d.png)

I've thus far had no luck in pinpointing the exact async call that is failing to complete.

Any clues on what might be the problem?  Or tips on troubleshooting?

Nuget versions:

**"Thinktecture.IdentityServer3" version="1.6.3"**
"Autofac" version="3.5.2"
"Autofac.Configuration" version="3.3.0"
"EntityFramework" version="6.0.0"
"FastMember" version="1.0.0.11"
"log4net" version="2.0.3"
"Microsoft.AspNet.Cors" version="5.0.0"
"Microsoft.AspNet.Mvc" version="4.0.30506.0"
"Microsoft.AspNet.Mvc.FixedDisplayModes" version="1.0.0"
"Microsoft.AspNet.Razor" version="2.0.30506.0"
"Microsoft.AspNet.WebApi" version="4.0.30506.0"
"Microsoft.AspNet.WebApi.Client" version="4.0.30506.0"
"Microsoft.AspNet.WebApi.Core" version="4.0.30506.0"
"Microsoft.AspNet.WebApi.WebHost" version="4.0.30506.0"
"Microsoft.AspNet.WebPages" version="2.0.30506.0"
"Microsoft.IdentityModel.Protocol.Extensions" version="1.0.0"
"Microsoft.Net.Http" version="2.0.20710.0"
"Microsoft.Owin" version="3.0.1"
"Microsoft.Owin.Cors" version="3.0.1"
"Microsoft.Owin.Host.SystemWeb" version="3.0.1"
"Microsoft.Owin.Security" version="3.0.1"
"Microsoft.Owin.Security.ActiveDirectory" version="3.0.1"
"Microsoft.Owin.Security.Cookies" version="3.0.1"
"Microsoft.Owin.Security.Facebook" version="3.0.1"
"Microsoft.Owin.Security.Google" version="3.0.1"
"Microsoft.Owin.Security.Jwt" version="3.0.1"
"Microsoft.Owin.Security.MicrosoftAccount" version="3.0.1"
"Microsoft.Owin.Security.OAuth" version="3.0.1"
"Microsoft.Owin.Security.OpenIdConnect" version="3.0.1"
"Microsoft.Owin.Security.Twitter" version="3.0.1"
**"Microsoft.Owin.Security.WsFederation" version="3.0.1"**
"Microsoft.Web.Infrastructure" version="1.0.0.0"
"Newtonsoft.Json" version="6.0.4"
"Npgsql" version="2.2.5"
"Npgsql.EntityFramework" version="2.2.5"
"Owin" version="1.0"
"System.IdentityModel.Tokens.Jwt" version="4.0.0"

**Comment by brockallen** [comment]
I suspect this is the famous deadlock bug in the Katana (ws-fed) middleware.

**Comment by mddi3** [comment]
Is this what you're referring to?

http://stackoverflow.com/questions/31243412/solving-onsendingheaders-deadlock-with-katana-openid-connect-middleware

**Comment by brockallen** [comment]
Yea, most likely. There's an official open issue w/ katana for it. In any event, I don't think this is an issue with IdSvr.

**Comment by mddi3** [comment]
I ended up changing these two dependencies on the build:

I think Microsoft.IdentityModel.Protocol.Extensions has the important change, but the updated JWT library also seemed required.

packages.config:

```xml
<package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2.206221351" targetFramework="net45" />
<package id="System.IdentityModel.Tokens.Jwt" version="4.0.2.206221351" targetFramework="net45" />
```

app/web config:
```xml
<dependentAssembly>
  <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.0.20622.1351" newVersion="4.0.20622.1351" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="Microsoft.IdentityModel.Protocol.Extensions" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-1.0.2.33" newVersion="1.0.2.33" />
</dependentAssembly>
```

Unfortunately, we currently don't have a good way of regression testing this change.

**Comment by brockallen** [comment]
Oh yes -- I think others reported that updating these references did help. Again, no good way to prove it tho.

**Comment by leastprivilege** [comment]
any progress? closing. feel free to re-open if needed.

**Comment by ciaranj** [comment]
I can confirm that the updating of that package does indeed fix this issue. (wishing I'd searched for this issue somewhat sooner, I manually tracked down the lock myself before discovering it was 'well known' *sob*)
