### ISSUE TITLE
No option to integrate Azure Active Directory with Identity Server 3

### ISSUE THREAD

**Issue by aqeelansari** [IdentityServer/IdentityServer3#2269]
I am using Identity Server for implementing single sign-on and access control. Currently I am using internal(in DB), OpenId and Google as for single sign-on and access control.We have a requirement to use Windows Azure AD users for the same.Is this possible to authenticate with Azure AD using the Identity Server, and should be able to update role and claims on Azure Active Directory? I have found one solution i.e. Graph API but it is not part of Identity Server (https://identityserver.github.io). 
Thanks in Advance.

**Comment by leastprivilege** [comment]
Azure AD is supported via the OpenID Connect middleware.

**Comment by aqeelansari** [comment]
Thanks a lot.
