### ISSUE TITLE
how to config identityserver3 as load balance?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2270]
I have two idsrv3 server running as load balance in IIS. It seems when the C# Client request the id token by sending authorization code, the idsrv3 throw an exception. I think it is because of the client connecting to another idsrv3 server. Should I config machine key in web? How do I synchronize the machine keys in web.config. Since I know less about machine key, can you tell me how to config idsr3 step by step?  Thank you very much!

**Comment by Farwell-Liu** [comment]
My machine key config in <ystem.web> is below:
    <machineKey validationKey="3AE5F1CCFAACFF1B72A7F0A281B" 
decryptionKey="ABAA84D7EC4BB56D75D" validation="SHA1" decryption="AES" />

**Comment by Farwell-Liu** [comment]
I have fixed the problem, the machine key is not a random string. it has some rules.

**Comment by brockallen** [comment]
If the original issue is solved, then close it. New questions should be in new issues.

If you have runtime errors, then enable logging in IdSvr and see what the log says.

**Comment by Farwell-Liu** [comment]
Thank you brockallen! Since I'm not sure if I have undstand the load balancer of idsrv3 correctly. Would you please answer me two questions?
1.I am using authorization code flow of idsrv3 in IIS and I have two idsrv3 server(idsrv3-A and idsrv3-B). According to my understanding,after the client receive the code, and then the client request id token from the idsrv3. Because the client request load balancer's url, it may connect to one of idsrv3-A and idsrv3-B, but idsrv3-A and idsrv3-B don't share memory,therefore it may cause an error.So besides machine key, there must be some other works need to be done(e.g. share login memory between A and B). right?
2.If I understand correctly,what are the other works I need to do. Would you give me a list please? 
I am newer here, please tell me detailedly. I really appriciate you very much!

**Comment by brockallen** [comment]
did you read this: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html and this: https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html

**Comment by Farwell-Liu** [comment]
So I need to implement my custom AuthorizationCodeStore, right?
And It seems there are already some implementations(e.g. Redis implementation),right?

**Comment by brockallen** [comment]
I think you need to read more of our docs. We mention that we already have EF implementations of those required stores.

**Comment by Farwell-Liu** [comment]
I have fixed the problem. I used redis to solve this problem.
Thank you!

**Comment by vaibhav22oct** [comment]
What exactly you did to solve the issue using redis ? I am having the same issue.
