### ISSUE TITLE
IdSrv separted from app, users needed in app

### ISSUE THREAD

**Issue by SaschaHerrmann** [IdentityServer/IdentityServer3#2272]
Hello,

i have on IdSrv3 in the network with ASPNetIdentity, ADFS and Custom UserStore. 
Multiple web apps use this server for authentication. The actual user is held by the IdSrv in its database. For some functionality in the web apps, for example mailings, i need the users in the web app. These users have to be in sync with the users of IdSrv3.
I need a little help on how this could be achieved. I know i could use a seperate IdSrv3 for the web app itself and registering the main IdSrv3 as an IdP. But this seems like overkill. Would federated signout even work in this scenario with a redirect like WebApp->IdSrv(app)->IdSrv(main)->ADFS?
Directly using the main IdSrv3-UserStore as a source for the web app users seems like breaking the separation of concerns.
Any hints much appreciated.

**Comment by mderriey** [comment]
It sounds like you need the users one way or another. Given that, I wouldn't recommend duplicating the users in a second db.
I don't see either how a second instance of IdSrv could solve the problem.

I'd rather go with an API exposing the users present in the user store. It could be itself protected by IdSrv and accessed by a client access token.

**Comment by SaschaHerrmann** [comment]
My ultimate goal is to extend the aspnetidentity with group managment and fine grained roles. Groups come from ADFS/ActiveDirectory and roles for groups are managed in the app. This way the access policy is managed where it belongs and the IdSrv3 tokens stay small. 
Maybe it is enough to just save the user somehow and resync on every login for role managment. Access policies can be done with the built-in asp.net 5 features.
Everything else can also be done with the user api at IdSrv3.
Thank you.
