### ISSUE TITLE
browser back button error

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2273]
Hello,

I have one problem with authentication process.
If one user try to login on one idsrv3 client and the user after login press browser back button hi get error.
How i can prevent this?

**Comment by brockallen** [comment]
More details, please?

**Comment by totpero** [comment]
This is my steps:
1. user try to access client: myclient1.domain.com
2. this client page require the user to be authenticated and redirect the user to idsrv page: idsrv3.domain.com;
3. the user is authenticate with success and the idsrv3 redirect to client url after.
4. Now if the user press back browser button, the user get idsrv3 error.

I solve this problem by setting ```InvalidSignInRedirectUrl = "~/"``` . this is the solution?

**Comment by brockallen** [comment]
This issue has been brought up before and discussed at length in the archive.

We added `InvalidSignInRedirectUrl` to help solve the problem, so you should set that to a URL you want the user sent to when they hit the back button and trigger this error.

**Comment by lust4life** [comment]
@brockallen  in chrome, hit back button, will lead to signin url which will trigger signin message exception, this can be solved with `InvalidSignInRedirectUrl` .
but in firefox , browser history will log the `connect/authorize` endpoint, when hit back button, which will trigger nonce missing exception (IDX10311) , how can this be processed friendly ?
i think this is the oidc middleware default implementation only use `ResponseMode => form_post`. query or fragment will not case this problem.

**Comment by leastprivilege** [comment]
Maybe open an issue with MS - they should not throw or give you a way to handle the error.
