### ISSUE TITLE
Using web api to call the stores from identityserver

### ISSUE THREAD

**Issue by j-hurst** [IdentityServer/IdentityServer3#2274]
I currently have the identityserver project setup and I have that calling custom client and scope stores.

Is there a way to separate the identityserver and the entity framework portion so I am calling the stores with a web api call?  I am asking because I have a need where the identityserver will be on one server and I would like to have the call to the client and scope stores on a separate server.

**Comment by leastprivilege** [comment]
That's absolutely possible.

**Comment by j-hurst** [comment]
Ok thanks, I will look into some more.

**Comment by j-hurst** [comment]
So I was able to get back to this, and I was going to create a class that inherits from IClientStore and then register that class for the client store.  Then that class would call the web api service to get my client.  Am I thinking of that wrong, or is that the expected way to break the call up from calling my repository directly?

Thanks for your help.

**Comment by leastprivilege** [comment]
Sounds good
