### ISSUE TITLE
AuthenticateExternalAsync does not get called in ExternalRegistrationUserService

### ISSUE THREAD

**Issue by ruslander** [IdentityServer/IdentityServer3#2277]
### Here is what I try to achieve

Context: I want to use Okta as initial source of identities and I do not need to store them on my side. The topology i'm looking to make it work is Idp initiatef workflow. [okta Idp] -> [Federated Idps] -> [sass sp]. Which comprehends following workflow "a user comes from Okta, after authorization pass [sass sp], get his email from claims or userinfo".

#### Impleamentation
I configured [okta Idp] to support SAML and enabled the attributes for `[user.email, user.firstName, user, user.lastName, user.login]`. Took as a starting point https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService/CustomUserService and made the [Federated Idps]. For SAML support configured to use Kentor.AuthServices.  

#### Where I am
Here is how I pass the authorization and getting the valid `access_token` token.

    var client = new OAuth2Client(new Uri("https://samlauth-rr-71k0j0ps.cloudapp.net/identity/connect/authorize"));
            var startUrl = client.CreateAuthorizeUrl(
                clientId: "sassrr",
                responseType: "id_token token",
                scope: "sassweb profile openid",
                redirectUri: "http://localhost:54792/Default.aspx",
                nonce: "random_nonce",
                responseMode: "form_post",
                acrValues: "idp:okta");

            Response.Redirect(startUrl, false);

#### What is the issue then ?
 I cannot get access to the email claim of userinfo to be populated. I started to debug this by registering and tracing `ExternalRegistrationUserService` calls. I was hoping that I can intercept `AuthenticateExternalAsync` and add the email claim . Unfortunately I do not see `AuthenticateExternalAsync` being called.  

 I started a thread on Kentor.AuthServices GH issue list and I was advised to come here.    

The smallest sample to illustate the issue https://github.com/ruslander/ssosaml
Captured logs [log2.txt](https://github.com/IdentityServer/IdentityServer3/files/58794/log2.txt)

Any idea how to debug this highly appreciated

Thanks
R

**Comment by mderriey** [comment]
I could be on the wrong path, but try clearing your IdSrv cookies. It could be that somewhere along the line, you still have an authentication cookie resulting in IdSrv skipping that part and logging you in straight away.

**Comment by leastprivilege** [comment]
is this still an issue? AuthenticateExternal should be called.

**Comment by venkatrv** [comment]
Hi,
I too having the same issue with latest package.
The API: AuthenticateExternalAsync, is not getting called. And GetProfileDataAsync gets called and it is failing here !!
Did anyone solved this issue?

**Comment by prabhakarreddy1234** [comment]
Even i am having the same problem, I could see external providers such as Google, Azure AD Open Id connect call `AuthenticateExternalAsync` but not through Kentor.AuthServices SAML.  Anyone fixed it ?
