### ISSUE TITLE
Adding new property in the Client model

### ISSUE THREAD

**Issue by phoenixjun** [IdentityServer/IdentityServer3#2278]
Hi,

We need to add some configuration in the Client model to support some very specific business requirement.

We are using entityframework to persist the client information from this github package

https://github.com/IdentityServer/IdentityServer3.EntityFramework.

We are wondering what is the best approach to do this? Do we need to modify the source code for that?

Thanks very much for your help.

**Comment by jeremy001181** [comment]
I had similar requirement, what i have done is i create a custom class inherit from client, , so you create your owin ClientStore and use ClientWrapper as return class in your custom FindClientByIdAsync method. like this

```
class ClientWrapper : Client
{
// your custom properties
}

class CustomClientStore: InMemoryClientStore, IClientStore
    {
        public CustomClientStore(IList<ClientWrapper> clients): base(clients)
        {
        }
        public async new Task<ClientWrapper> FindClientByIdAsync(string clientId)
        {
            return await base.FindClientByIdAsync(clientId) as ClientWrapper;
        }
    }
```

**Comment by phoenixjun** [comment]
Hi,

Thanks for your information.

It is working if you are using InMemoryClientStore,

For the entityframework storage, you need to perform mapping between database model and business model which is handle in the library. 

If you are adding a new column in the table, you need to update the models and the mapping. It is not as easy as what you describe.

**Comment by brockallen** [comment]
I'm not sure I'd recommend adding to the EF entities. I'd rather see you create related entities and link via the PK. I think you'll have an easier time maintaining that approach.
