### ISSUE TITLE
Is this a supported usecase

### ISSUE THREAD

**Issue by stocksr** [IdentityServer/IdentityServer3#2281]
I have an existing (OLD) SSO solution running on (oldapp.mydomain.com) that is currently handling logins for users and setting a cookie on .mydomain.com with the relevant details.

Assume for the purposes of this conversation that I have NO control over this application 
This application will go away at some point and be replaced with a new login sever hopefully based on ids.

My migration plan is to: 
Configure an instance of ids on (identity.mydomain.com) that defers to this older SSO solution for now
then migrate the dependent apps to use this ids
then migrate the users to the ids

It is step 1 I am having trouble with

I can run a site at identity.mydomain.com, and can read the old SSO cookie from this site. I can not figure out where in ids I hook my custom code to check the cookie and log a user in using the information I read from that cookie?

**Comment by brockallen** [comment]
It might work -- we have enough hooks in IdSvr for you to leverage the authentication of "something else" (meaning custom)... of course, the devil's in the details, but at a high level I think you can get it working.

The first extension point to look at is the PreAuthN in the user service.

**Comment by stocksr** [comment]
Many thanks, that was the pointer I needed to get it working.

In my PreAuthenticateAsync override I need access to the raw request context so I am using 

        var ctx = HttpContext.Current.GetOwinContext();

Would it not be better if the context was passed to these methods?

**Comment by leastprivilege** [comment]
Inject the OwinEnvironmentService into the class. That's the recommended way.

**Comment by stocksr** [comment]
Thanks that makes sense, However I don't think that service in the documentation.

For future reference (to help the next developer walking this path)
As I needed a strongly typed OwinContext to pass on to 3rd party code my userservice constructor is like this:

        public class CustomUserService : IUserService
        {
            private readonly OwinContext owinContext;
            public CustomUserService(OwinEnvironmentService oes)
            {
                owinContext = new OwinContext(oes.Environment);
            }
        .....

would it make sense to add a OwinContext getter on the OwinEnvironmentService?

**Comment by leastprivilege** [comment]
no it wouldn't because `OwinContext` is an internal implementation detail. The OWIN environment isn't.
