### ISSUE TITLE
Getting "Authorization denied" message when system idle for 10mins

### ISSUE THREAD

**Issue by pessimca** [IdentityServer/IdentityServer3#2283]
Hi All,

We are facing some challenge with token where it is throwing "Authorization denied" message from API's after application idle for >5mins...

As per current configuration, 
AccessTokenExpireTimeSpan = TimeSpan.FromMinutes(30)

Application is working fine if i am using continuously but failing it is idle for sometime. Verified Bearer token on request and everything looks good. Can anyone help me to fix this issue.

Thank you.

**Comment by brockallen** [comment]
JWTs or reference tokens? What do the logs say (you enabled logging, right)?

**Comment by pessimca** [comment]
I observed that the issue with client. Client is configured with loadbalancer. App is working good when I disable one node. Do we need to add any additional configuration for clients which has load balancer? 

Here is my cofiguration:

HTTPS://test-client.xxxx..com
Test-client on server A and server B

HTTPS://my-ids.xxxx.com
My-ids on server A and server B
Requiressl = false
Publicorigin =HTTPS://my-ids.xxxx.com

plz let me know if I need to add any additional configuration.

Thank you

**Comment by brockallen** [comment]
Where are you storing the access token once issued to the client? Sounds like a state management problem in your client.

**Comment by pessimca** [comment]
We are using AngularJS as UI for our application and token will be stored into local storage. It will be added to Request Header for all requests to API. We are using oidc-token-manager library to serve this.

**Comment by pessimca** [comment]
any suggestions?

**Comment by brockallen** [comment]
`OpenIdConnectAuthenticationOptions.UseTokenLifetime=false`

**Comment by pessimca** [comment]
Thanks Allen for your response. Is access token will be generated for client url or node? Currently, generated token valid on one node.  Here is my configuration on LB:

![identity_server_client_config](https://cloud.githubusercontent.com/assets/13974203/11802955/c52f7dd6-a2c3-11e5-8ea4-7332e62e27ef.png)


Please let us know if you need any additional information..

**Comment by brockallen** [comment]
Sorry -- I think I posted my last answer here, but I was thinking this was another thread. Sorry... my mistake.

**Comment by brockallen** [comment]
I'm confused now -- where is IdentityServer in this? It looks like you're using the katana OAuth2 authorization server middleware.

**Comment by pessimca** [comment]
My Identity Server app and Clients resides on both nodes. Here i showed client configurations with load balancer and proxy for understanding.

Yes.We are using Katana OAuth2 middleware. Here i am looking solution for clients which are running on multiple nodes and token sharing  between nodes. Currently, token is accepting only one node which initial request sent from. I am not sure if i am making more confusion. 

Here is simple scenario:
* Client configured on 2 nodes with LB
* Disable Node-2 and start access application
* Request will go to IDS from Node-1
* Access Token issues to Node-1 and application working fine
*Disable Node-1 and Enable Node-2
* Access application and will receive "Authorization Denied" message bcz issue token works only on Node-1


I hope this explains my issue. Please let me know if you need any additional information

**Comment by leastprivilege** [comment]
Why do you use

`app.UseOAuthAuthorizationServer(oAuthServerOptions);`
