### ISSUE TITLE
External login with google

### ISSUE THREAD

**Issue by lpranith** [IdentityServer/IdentityServer3#2285]
I had set up my project in the Google developer console with proper redirect URI,Enabled google+ API.
I am using implicit client demo and In my startup gave the proper Client ID and Secret ID.
When i authenticate via google, consent screen appears when i say allow, It shows Invalid Account.While debugging i get this error
user service failed to authenticate external identity".
Been stuck for while. Any help would be appreciated.

**Comment by brockallen** [comment]
Well, what did you put in for the code for the user service and its authenticate external implementaion?

**Comment by farzad99** [comment]
I'm new to the IdentityServer3. But there's a step-by-step instructions for one of the samples that incorporates google authentication. You might find that helpful. Here's the link:

https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html
