### ISSUE TITLE
Add extra claims to access_tokens as part of custom grant validation?

### ISSUE THREAD

**Issue by dariusdamalakas** [IdentityServer/IdentityServer3#2287]
Hi,

I have realized I have a wrong understanding of what the [AuthenticateResult.User](https://github.com/IdentityServer/IdentityServer3/blob/a6e2b6bdfd1516af6cd9fdc9f46a08bb23bb553e/source/Core/Models/AuthenticateResult.cs#L37) property is meant to be used for and what idsrv3 is doing with it. I have had a wrong impression that these claims will be added to the access_token, but this is not happening. 

Similarly, there is a same construct when working with custom grants. As part of request validation, a custom `ICustomGrantValidator` implementation must return a `CustomGrantValidationResult`, which has a [Principal](https://github.com/IdentityServer/IdentityServer3/blob/a6e2b6bdfd1516af6cd9fdc9f46a08bb23bb553e/source/Core/Validation/CustomGrantValidationResult.cs#L63) property, constructed from the claims extracted from the request.

How is 'CustomGrantValidationResult.Principal' result being used by `idsrv3`?  What I am trying to achieve here is return the extra claims passed in assertion, and want then to have back in access_token. I am a bit lost at the moment as to what options I have achieving this.

I've read through [section 3 of rfc7521](https://tools.ietf.org/html/rfc7521#section-3) but that does not speak anything about issueing access token.  Also, your documentation on custom grants clearly states that the job of custom grant validator is to [validate incoming request, and map that to  user](https://identityserver.github.io/Documentation/docsv2/advanced/customGrantTypes.html). 

Regards

**Comment by leastprivilege** [comment]
Claims for tokens are gathered in the user profile GetProfileDataAsync method. Here the principal gets passed in (e.g. from the AuthenticateResult or the custom grant validator).

**Comment by dariusdamalakas** [comment]
Oh, the amount of time spent looking into for this missing little piece makes me feel embarassed. Several hours of debugging and going through idsrv3 code, reading through rfcs and missed this. This is very helpful, indeed. Thanks alot!
