### ISSUE TITLE
Access Key Management

### ISSUE THREAD

**Issue by johncmckim** [IdentityServer/IdentityServer3#2288]
**Problem**
Access Key Management is an issue that everyone has as soon as they start offering OAuth 2.0 / OpenID secured APIs. It might not quite fit into this project, but it is closely related so I thought I'd start a discussion here.

The first issue I want to bring ups is Access Key Generation. Many APIs allow self registration and Access Key Generation (think [Google](https://console.developers.google.com/), [Twitter](https://apps.twitter.com)). However, this is not appropriate in many cases. On many occasions API Access needs to be done out-of-band to ensure only certain users can access the API. This is particularly relevant when offering endpoints that accept a token from a `client_credentials` grant.

The second issue is Access Key Delivery. Once keys are generated they need to be securely shared with the person that requested the Access Keys. If the requester is a user of the application that is simple, they login and view it. However, if the requester not a user of the application the keys need to be delivered to the requester some other way i.e. over the phone, email. That quickly becomes a maintenance issue.

**Examples**
As an example consider this scenario. An enterprise application is offering APIs to allow particular 3rd-parties to integrate with it's software. This enterprise application is installed per-client meaning that there are many installations of the software a 3rd-party can integrate with. As a such, they will need an access key per installation. Requiring the third-party to register on each installation is not realistic as they will end up with tens or hundreds of accounts to get access keys. How can an access key be generated, approved and then delivered to the third party for each installation?

Another example an ecosystem of services. An organisation may have an ecosystem of applications  want to control access to all those applications through one console (think [Google](https://console.developers.google.com)). How can that console request that the service creates an Access Key for a service and securely deliver it to the requester?

**Proposal**
The two challenges are access validation and secure key deliver.

My thinking is along these lines. The Access Request could be generated within the application or from an API and the Validation could occur within the application or against and external web service.

![key management](https://cloud.githubusercontent.com/assets/1297227/11770599/675ee3ce-a24e-11e5-9e47-a58ca6b20fbd.png)

I am not aiming for machine-to-machine key management. However, if that could be achieved securely through a system like this it could be beneficial. One particular advantage of such a system would be automatic key rotation.

I would like to implement something that works with Identity Server. Do you see any potential pitfalls or issues with that proposed solution. Do you know of any pre-existing solutions to this kind of problem?

**Comment by uncleyo** [comment]
Interesting, but I don't quite understand the process of establishing trust here.
When using `client_credentials`, client must be granted access to some scopes directly (and not on behalf of resource owner). So where can these scopes available to the client be derived from?

**Comment by johncmckim** [comment]
The responsibility of establishing trust regardless of flow occurs during the request validation. It would be the responsibility of the validation process to ensure access to a flow and scopes is trusted.

This is how I see the validation working.

**Validation Request**
The validation request needs to contain a minimum of the following:
```javascript
{
  "access_request": {
    "client_id": "identifier",
    "flow": "", // code, implicit, hybrid, client_credentials, resourceowner ect.
    "scopes": "scope1 scope2"
    "redirect_uris": []
  },
  "requester": { // whatever properties the validation process requires to identify the requester
    "name": "john doe",
    "email": "john@doe.com",
    "developer_id": "343"
  }
}
```

This information is sent to the validation service to evaluate.

**Validation Process**
The validation process validates the request and determines if it is to be trusted or not. It is the critical part that prevents unauthorised access. There could be multiple implementations of this and I'm don't want to be too prescriptive about how it should be done.

I should also point out that I don't think this has to be automated. It can and possibly should require manual review with accept / reject.

**Examples**
*Manual validation*
One way to validate the request would be to store the request for review. The reviewer would be notified when the request is made asking them to review it. They would accept or reject the request based on whether or not the request is expected and the requester known. The reviewer would need to look at the `client_id`, `flow`, `scopes` and `redirect_uris` to ensure they are valid. If it is not, they could follow up with the requester an decide later.

Once the request is approved manually, the reviewer determines how the credentials are delivered to the requester. The aim here is to ensure the reviewer has control over where the credentials are actually sent to.

*External validation*
In the developer console example, the validation process is completed through an external validation web service. In this example, developer a registers on the developer console and their access is approved or rejected there. They then request access to `foo service` through the developer console or their own system. This sends the access request to `foo service`.

To validate the request `foo service` makes a request to the developer console to validate the request. The requested is checked to ensure the 'client_id', `flow`, `scopes` and `redirect_uris` are valid for the requester. The request is either accepted or rejected. If it is accepted, the delivery method is then sent back to `foo service` which directs `foo service` on how to securely deliver the credentials to the client. i.e.

```
{
  "type: "", // email, http
  "email": "john@doe.com", // the actual email should only contain a link to view the credentials
  "uri": "http://requesterservice/credentials/accept" // something that can securely accept credentials 
}
```

**Implementation**
When it comes to implementing this, the validation process is should be an extensibility point. However, since it is extremely important I would create standard implementations that could be dropped in.

**Comment by uncleyo** [comment]
Well, I'm still not sure about some specific ideas here.

I don't quite understand why you want credentials to be sent back after validation? Why not generate them upfront on the client (be it shared secret or asymmetric key pair)? Then you only need to communicate the decision (accepted/rejected).

Also, there is a spec for [dynamic client registration](https://openid.net/specs/openid-connect-registration-1_0.html).

**Comment by johncmckim** [comment]
@uncleyo In my solution, credentials are not sent back after validation. They're never part of the validation process. The validation does only the accept or reject and tell the client where to send the credentials. Credentials should only be generated by the Identity Server.

I was unaware of [dynamic client registration](https://openid.net/specs/openid-connect-registration-1_0.html). I am more than happy to drop my ideas for an existing standard. It is pretty close to what I want I also note it was brought up in #308. I can understand that it should not make up part of the core project.

For me the implementation of that protocol would need to provide a point where a request could be accepted / rejected. It doesn't appear allow a request to be stored and approved later, but that's ok for me.

I note that in the spec it specifies a list of `grant_types` in the Client Metadata. The list includes `authorization_code`, `implicit` and `refresh_token`. It does not seem to include the other OAuth `grant_types`. I think that is pretty limiting.

I found [OAuth 2.0 Dynamic Client Registration Protocol](https://tools.ietf.org/html/rfc7591).

> This specification generalizes the
   registration mechanisms defined by "OpenID Connect Dynamic Client
   Registration 1.0" [OpenID.Registration] and used by "User Managed
   Access (UMA) Profile of OAuth 2.0" [UMA-Core] in a way that is
   compatible with both, while being applicable to a wider set of OAuth
   2.0 use cases.

There is also an extension to this, [OAuth 2.0 Dynamic Client Registration Management Protocol](http://tools.ietf.org/html/draft-ietf-oauth-dyn-reg-management-05). This adds additional endpoints to allow the client to manage their registration request.

Are there any plans or interest in implementing these specs? I imagine it would be a separate project `IdentityServer.DymanicRegistration`. I'm happy to contribute to implementing the [OAuth 2.0 Dynamic Client Registration Protocol](https://tools.ietf.org/html/rfc7591).

**Comment by uncleyo** [comment]
@johncmckim, I didn't mean credentials are part of validation, but rather why do they have to be generated by something else than the client (also, this would never work for a proper proof-of-possession based auth method implementation).
Anyway, not sure it\s relevant in context of OAuth 2.0 DCRP.

**Comment by johncmckim** [comment]
@uncleyo I'm a little confused by that. When do oauth/openid clients ever generate their own credentials? Aren't credentials generated for a oauth/openid client by the identity server and then given to that party in some way? I wasn't aiming to change that, just automate it some how. Perhaps I didn't explain my initial thoughts well enough.

Anyway, forget my initial solutions, OAuth 2.0 DCRP is what I am interested in now I know that exists. The [software statements](https://tools.ietf.org/html/rfc7591#section-2.3) would meet my needs by allowing known clients to get access to credentials.

**Comment by uncleyo** [comment]
@johncmckim, I just mean that the channel from client to DCRP (or the like) is secure already, so it's safe for credential transfer (unlike e-mail/sms). And given you use asymmetric key solution, only the public key ever needs to be transferred.
The server could validate shared secret complexity or key strength upon receiving request and reject request if it's too weak. I'm not bringing this in terms of the specification (didn't read yet), but rather conceptually.

**Comment by leastprivilege** [comment]
this sounds interesting - but I am bit lost how this relates to identity server

**Comment by johncmckim** [comment]
@leastprivilege I created an issue here, because while it might not fit exactly into this project, managing API clients is an issue everyone using this project faces. I didn't know much about this at the time, but thanks to @uncleyo, I know more about [OpenID Connect Dynamic Client Registration](http://openid.net/specs/openid-connect-registration-1_0.html) and [OAuth DCRP](https://tools.ietf.org/html/rfc7591).

If the goal of Identity Server is to provide "access control for modern web applications and APIs using protocols like OpenID Connect and OAuth2", I think the OpenID DCR and OAuth DCRP protocols are natural extensions of that.

I can see how the ideal situation for you might be for a separate OpenID DCR and OAuth DCRP implementation that integrates with IdentityServer and other solutions. However, no other implementations or those protocols exist for Asp.Net that I'm aware of.

If there's no interested in implementing OpenID DCR or OAuth DCRP that's fine. I'll need either need to create my own implementation that works with Identity Server or hope someone else does.

**Comment by leastprivilege** [comment]
DCR is interesting - but not as part of "core" identityserver. It should be a separate service/endpoint.

**Comment by johncmckim** [comment]
@leastprivilege  I agree with that.

So how does that come to be. Is there interest or scope for this to be under the IdentityServer organisation? If so, are you interested in contributions to get it going?

**Comment by leastprivilege** [comment]
Have a look at our admin repo - that's where such a service should leave - @iBoonz
