### ISSUE TITLE
Add hook to allow custom response data for token requests

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#2290]

**Comment by aaabdul** [comment]
Is it ok if I do an initial implementation of this in another git branch ?

**Comment by leastprivilege** [comment]
i am working on it

**Comment by aaabdul** [comment]
ok i will leave you to it. thanks.

**Comment by leastprivilege** [comment]
Give it a try - 

https://github.com/IdentityServer/IdentityServer3/commit/a8b545ae581c239bc00070157f0d928bd13a5202

there is a new service `ICustomTokenResponseGenerator`

**Comment by aaabdul** [comment]
Thanks. Will do.

**Comment by leastprivilege** [comment]
OK - let me know. If it is useful i can merge to dev.

**Comment by leastprivilege** [comment]
Verdict?

**Comment by aaabdul** [comment]
Sorry, didn't get a chance to try this out yet. Got occupied with work. I am free to do this tomorrow. Will check tomorrow and let you know. Is that alright ?

**Comment by leastprivilege** [comment]
OK

**Comment by aaabdul** [comment]
I had a look at the implementation and it quite good. Servers our purpose. Just wondering is there a way to get nuget package of this build using the solution ? 

I tried the build.ps1 script, but it looks like a unit test is failing. 

0
Error: 01/01/2016 13:57:43: 
At C:\github\IdentityServer3\default.ps1:56 char:2 +     .$xunit_path "$src_directory\Tests\UnitTests\bin\Release\$project ... +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception:    IdentityServer3.Tests.Conformance.Basic.ClientAuthenticationTests.Token_endpoint_supports_client_authentication_with
_basic_authentication_with_POST [FAIL]

**Comment by leastprivilege** [comment]
works on my machine ;)

But you can use the CI feed - https://www.myget.org/F/identity/

**Comment by aaabdul** [comment]
Thanks. Which version in CI has this new feature ?

**Comment by aaabdul** [comment]
Just tried to implement 2 factor auth with this feature. Ran in to following problem. 

I have a custom grant implementation called "2factor". The flow for this should be as below: 

1. Client provides client id, secret, username, password, scope and granttype 2factor. 
2. IDS creates a token with only one claim called "mem_phrase" with value of a 3 numbers (i.e. 3 random chars from memorable phrase). 
3. Using the new feature IDS sends mem_phrase = 123 along with the usual response (i.e. token, expiration, type, etc.) to the Client
4. Client gets these random chars of memorable phrase from User and sends the following back to IDS - token previously sent, client id, secret, mem_phrase (response from the user). 
5. IDS fetches the token which has one claim that tells the requested characters and it is matched with the one saved in database to the one provided by client (from user). 
6. On success IDS responds back to caller with a new token (similar to resource owner credential flow) 
7. On failure, invalid grant or something similar error message will be sent back to caller. 

With this feature, I can achieve 1, 2, but not 3, as the ICustomTokenResponseGenerator does not have access to the Token class (or I don't know how).

**Comment by leastprivilege** [comment]
I haven't heard back from you - so I assume it is working fine.

**Comment by brettmas** [comment]
Is there a similar service for implicit flow where the access token is requested/provided via the authorize endpoint?
