### ISSUE TITLE
ASP.NET 5 MVC 6 usage of IdentityProviders

### ISSUE THREAD

**Issue by AMatijevic** [IdentityServer/IdentityServer3#2292]
Hello.
I have one short question?
When I try to use IdentityProviders property in server configuration I have a problem because the property receive  Action(IAppBuilder, string) and I have IApplicationBuilder, is there a way to use
IApplicationBuilder instead of  IAppBuilder or i need to change source code?
Thanks a lot.

**Comment by leastprivilege** [comment]
IdentityServer3 runs in Katana compat mode in ASP.NET 5 - you need to use IAppBuilder

**Comment by leastprivilege** [comment]
..or simply use a non-beta host (e.g. Katana) for your security infrastructure ;)

**Comment by AMatijevic** [comment]
I try to use non-beta host but I have UserService for ASP.NET Identity 3 and now I can use any more EF7 DbContext and other parts of data project. So I think that will not work for me.
Can I somehow include or use Facebook, Google etc. providers without to define them in IdentityProviders ?
Thanks.

**Comment by leastprivilege** [comment]
This works fine - just use the Katana providers for FB and Google.

**Comment by AMatijevic** [comment]
Thanks a lot i try and everything is working perfectly now with Katana based providers.
Thanks again, you were a great help.

**Comment by leastprivilege** [comment]
cool!
