### ISSUE TITLE
Does requested scopes must be included in access token?

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3#2295]
Hi

An example of implicit flow, after customer authenticated, on the way out to client, the `DefaultClaimsProvider` add all requested scopes into access token, 

```
public virtual async Task<IEnumerable<Claim>> GetAccessTokenClaimsAsync(ClaimsPrincipal subject, Client client, IEnumerable<Scope> scopes, ValidatedRequest request)
        {
//...... omitted.....
 // add scopes
            foreach (var scope in scopes)
            {
                outputClaims.Add(new Claim(Constants.ClaimTypes.Scope, scope.Name));
            }
```

Is it by design in the spec says that access token must include scopes that were requested at the first place? or Is there any way I can filter out some requested scopes (e.g. `openid`) without implementing a CustomClaimsProvider? 

I might miss understand the spec, hope you can help

Thanks

Ming

**Comment by brockallen** [comment]
You can configure the `AlwaysInclude` property on the `ScopeClaim` to `false` (which is the default). This requires the client to use the access token to access the user profile endpoint to get the user's claims.

**Comment by leastprivilege** [comment]
In our implementation the requested scopes are always in the access token. If you want to change that, you'd need a custom claims provider.

**Comment by jeremy001181** [comment]
Thanks for quick response :)

I notice there is quite a bit logic in the `GetAccessTokenClaimsAsync` method of `DefaultClaimsProvider`, and it is not nice replicate all that in our custom provider.

Is there any reasons to include all requested scopes in access token? in the spec, I couldn't see any information regarding requested scopes value must be included in access token or something like that? if it is optional, do you think it makes more sense to output scope totally based on client configuration? or make the filter to go through all scopes as well?

Thanks

**Comment by leastprivilege** [comment]
What kind of scopes are you talking about - what's the scenario?

**Comment by jeremy001181** [comment]
it is the `openid` scope I want to remove from access token, I understand that the `openid` scope must be included in authorize request (according spec) so that it indicates this is a openid connect authentication, but the spec doesn't say it needs to be included in access token as well?

Does it make sense?

**Comment by leastprivilege** [comment]
the openid scope is what allows the client to use the userinfo endpoint.

**Comment by jeremy001181** [comment]
I see, 

okay what about other standard scopes that are identity type, like `Profile` 

if I send a authorize request like below, i would expect only `openid` and `offline_access` included in access token? as `profile` scope is identity type? and only resource type scope should be added to access token? or do i miss understand the usage of resource type scope?

```
https://www.test.com/identity/connect/authorize?
&state=8087291235434437
&nonce=16394696150509302
&client_id=implicitstubclient
&redirect_uri=http%3A%2F%2Fimplicitstubclient%2F
&response_type=id_token%20token
&scope=openid%20profile%20offline_access
```

**Comment by leastprivilege** [comment]
again - the profile (or other identity scopes) are also there for using the userinfo endpoint - they define to which identity information the client has access to.

**Comment by jeremy001181** [comment]
I am with you now, thank you.
