### ISSUE TITLE
One user not able to sign in - troubleshooting

### ISSUE THREAD

**Issue by ShieldPad** [IdentityServer/IdentityServer3#2296]
Hello,

I've set up identity server 3 in a hybrid flow (asp.net MVC application) that has been working flawless for a while. But today one recently added user has not been able to sign in and I'm wondering if you have any good ideas for troubleshooting the issue?

I've done this so far:
- I've tested signing in myself with the users credentials on various browsers and it works fine
- The user is able to sign in with his iPhone browser but not on his computer
- I asked him to enable cookies, but it didn't make any difference

Any ideas on how I can troubleshoot this? I do not have access to the users computer, as he sits in another country.

**Comment by ShieldPad** [comment]
Btw. I must also say - Identity Server is absolutely awesome!

**Comment by brockallen** [comment]
So you need to understand what's happening in your own user service, since that's where a lot of that code runs. Also, you can enable logging in IdSvr. Those are the best way to know what's happening.

**Comment by ShieldPad** [comment]
Thanks for the fast reply. Will do and will let you know (or close this) once I have more detailed information. I am using membership reboot as a user service.

**Comment by ShieldPad** [comment]
Hi, the user upgraded from internet explorer 8 to 9 and the issues disappeared. I will install the log nonetheless.

/ShieldPad

**Comment by brockallen** [comment]
Ah yes, IE8 isn't really on the supported list. I think some people have sent PRs over the last year tweaking the JS to make IE8 work, but it's not something we deliberately support.
