### ISSUE TITLE
how to implements storage and retrieval of signin request?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2297]
I have two idsrv3 server running as load balance.I am using authorization code flow and I have two idsrv3 server(idsrv3-A and idsrv3-B). The login process as below:
1. The IE request /core/connect/authorize?client_id=......, and the IE connect to the idsrv3-A.
2. And Then the IE redirect to /core/login?signin=11a1b1e955d2882be29a70a36c9c76fb
3. I enter the username and password and submit, Since the load balancer has no keeping session function, Now it may post the data to the idsrv3-B. and then it throw an error.
I have read this: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html and this: https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html
But I did not find any clue.
Would you please tell me how to solve this problem? Are there any Interface to keep the signin request like the IAuthorizationCodeStore keeping the AuthorizationCode?

**Comment by brockallen** [comment]
As with any load balanced scenario, you need to sync any key material necessary for protecting data. If you're running in ASP.NET this means configuring the `<machineKey>` element in `~/web.config`.

**Comment by Farwell-Liu** [comment]
After configured the machinekey, I have solve the problem. I have forgot to configure it in the product scenario.
Thank you brockallen very much!
