### ISSUE TITLE
Best practice for authorizing mobile device before user has registered account password

### ISSUE THREAD

**Issue by engenb** [IdentityServer/IdentityServer3#2298]
Hello,

Having a great time learning about this project.  It's been a big help to me and my team.  However, after pouring through tech talk videos (I've watched more hours of Dominick Baier in the past couple weeks than I care to admit), blogs, and docs, I got to a point where I thought it'd be wise to just ask the experts the best approach for my scenario before I go too far down the wrong rabbit hole.

The layout:
mobile clients
web server hosting SPAs <- not related to the issue but good to mention
api site (RESTful api)
IdentityServer3 (standalone, multi-tenant)

Any advice on client configs/flows/etc would be greatly appreciated as I'm still wrapping my brain around all this (newcomer to claims-based auth here) but I'll get to the point...

The mobile clients are an extension of a larger enterprise application (use case: company that wants to chat/interact directly with their customers) - this means my application knows about any and all current customers/users, updated via api from a separate system.  However, users must first go through a registration process on the phone before we authorize them for mobile access.

When a mobile user attempts registration, we're currently generating a code and texting it to their phone number on record with us (looking at MembershipReboot + Twilio to take over this responsibility btw).  Once they receive and verify the sms code, the user is now in what I'm calling a "partially authorized" state - they've verified their username and device but haven't set their password yet, so we can't log them in (or can we?).

The prior steps, sending and verifying the sms code, are invoked via anonymous endpoints.  The next step to set their password should be an authorized endpoint, but I'm not sure the appropriate security approach to do this.

The approach I'm pondering:
1a. when api verifies sms code, have my api request a bearer token from the auth server to be sent back with the verify sms code response (in a header?)
(or)
1b. when mobile client receives verify sms code success, mobile device requests bearer token from auth server to be used in next step
2. mobile client uses bearer token to set password via api
3. api uses auth server authorize endpoint with user/pass to get claims and log user in, get user-specific token?  I definitely need a user-specific ClaimsPrincipal here so I know what tenant my user belongs to.

1a feels wrong because bearer tokens generated for my api client should only be used by my api - am I correct in this?  If so, what's the right flow to grant a user (without a set password) access to my api in this scenario?

1b feels more correct, and I'd implement this via a special client that only has a scope for for the set password endpoint, but then I wonder if that will complicate the configuration of my api's token middlware, since the middleware is configured with a single cient id and secret.

Thanks for taking a look.  Any advice will be greatly appreciated.  Hoping I'm not too far off base here...

Thanks!

**Comment by engenb** [comment]
want to also comment that I have hesitations about option 1b, because anyone can hack a phone and pull the client_id and client_secret.

**Comment by brockallen** [comment]
Yes :)

**Comment by engenb** [comment]
isn't it funny how you can be stuck on something for the longest time, and as soon as you ask for help you figure it out on your own anyway?  At any rate, thanks for confirming that I'm on the right track!
