### ISSUE TITLE
Clients with Internal Urls and External url using proxy configuration

### ISSUE THREAD

**Issue by pessimca** [IdentityServer/IdentityServer3#2299]
Hi,

We have proxy server and another url on top of internal url (with LB) for client. My internal url is working good. But getting below error when i access with my proxy server url:
IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.

Here is my configurarion:
Proxy: https://my-test.xx.yyy.com (with single node)
internal:  https://my-test.yy.zzz.com (with two nodes and LB)
![identity_server_client_config](https://cloud.githubusercontent.com/assets/13974203/11802955/c52f7dd6-a2c3-11e5-8ea4-7332e62e27ef.png)

Requests will go to Proxy and will redirect to internal. Can we make dynamic "RedirectUri" so i can keep my proxy uri for external request and internal uri for internal request?

I configured ids redirects from internal url.
I am sure some one might have this issue and fix details. I appreciate all your help.

Thank you.

**Comment by pessimca** [comment]
any has any idea?

**Comment by brockallen** [comment]
Is this an IdentityServer question?

**Comment by pessimca** [comment]
Hi Allen,

I showed diagram for understanding for client configuration. My clients has installed on both nodes with LB and it has another layer (proxy) for external use. My application can be accessible from internal and external networks. Internal and external networks urls are different to show the difference. 

My IDS redirects configured on Webservers which are hosted on Node-1 and Node-2. Application is working good if i access internal urls but failing external urls due to IDS.

I am looking for client configuration help as per my requirements. I hope, explained the details about the current issue which i am facing. Please let me know if it is not clear.

Thank you.

**Comment by brockallen** [comment]
How is the client is failing? What part is not working? I don't have enough info to know how to help.

**Comment by pessimca** [comment]
Hi Allen,

Here is my two urls:

Internal: https://my-test.int.xxx.com
external: https://my-test.ext.xxx.com

I should be on internal url only When i access internal url. Application should run on internal only.
Same to external. But external requests to redirected to internal url using proxy server.

Currently, we are giving redirecturi as https://my-test.int.xxx.com so it is returning to https://my-test.int.xxx.com only. Getting below error when i use  https://my-test.ext.xxx.com
IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.

What i am looking for is, is there anyway to configure clients for internal and external with proxy with same web servers? Here is the diagram which presents my server configuration:
![2015-12-21_2200](https://cloud.githubusercontent.com/assets/13974203/11946960/711e0846-a82e-11e5-9ead-58812d02c124.png)

Hope this gives you more information.

**Comment by stevewoj** [comment]
i think you should use the same url internal and external and do a "split-brain" dns configuration

**Comment by pessimca** [comment]
Thanks stevewoj. Could you please help me to understand more on this.

**Comment by stevewoj** [comment]
you will configure only one redirect uri aka https://my-test.xxx.com with identityserver. On your internal network the dns resolves the name to your internal ip address. On the public dns the name is resolved to your proxyservers address. https://en.wikipedia.org/wiki/Split-horizon_DNS

**Comment by pessimca** [comment]
Thanks stevewoj for details. I know this process and we are using the same for external url with two different ips (one public and private). Same will be configured on DNS. Any requests from public will goes to public ip and internal goes to private ip. But there is another one on my diagram which completely internal (private) which will be accessible by internal only. 

Let me put int his way, We have two urls one is for mobile and another for desktop. mobile url will be proxyed to desktop url using proxy server. With one codebase we are running both urls except IDS redirect. Request is reaching mobile url --> Desktop --> IDS but it is going to Desktop url as part of redirecturi. But we are expecting to mobile url. That's why i am looking for dynamic redirecturi so it will understand the request and redirect to same url.

**Comment by stevewoj** [comment]
I dont understand that second part without more details.

**Comment by leastprivilege** [comment]
still an issue? feel free to re-open.
