### ISSUE TITLE
Integrate identityserver in existing ASP.NET identity application

### ISSUE THREAD

**Issue by Michaelbo** [IdentityServer/IdentityServer3#2301]
Hi,

Currently, we have the following setup:
- A front-end, which is talking to a WebAPI;
- This WebAPI contains all ASP Identity logic: login, passwordreset, getroles, etc.

Now, we want to achieve the following:
- The front-end remains
- WebAPI remains
=> We want to start providing single sign-on, using the login (front-end) and WebAPI login methods that we already have. 

Is this possible using IdentityServer? In my current tests, I have set up IdentityServer, and I am able to successfully login using the resouce owner authentication flow by connecting IdentityServer to the ASPIdentity database of my WebAPI. 

However, I'm having difficulties understanding how I should transform my existing userManager methods that are implemented in the WebAPI. Should I just leave them as they are, and use IdentityServer only for external apps (but then the login code will be redundant), or does this usermanager need to be replaced completely by identityserver?

**Comment by leastprivilege** [comment]
You can call into your existing user management login from within the Idsrv IUserService.

**Comment by mderriey** [comment]
I see 2 options:

The first one, mentioned by Dominick, is to create a custom implementation of [`IUserService`](https://github.com/IdentityServer/IdentityServer3/blob/65d23271fd1d46f9a7ac2a463767d664682ab3dc/source/Core/Services/IUserService.cs) which will talk to your API. This means that you keep your existing API methods, but you may have to *enrich* your API by creating new methods to comply with what `IUserService` needs.
Also consider that every time IdSrv has to use the user service, it will go through an HTTP request.

The second one consists of doing what you experimented, that is, use the provided ASP.NET Identity-based implementation of `IUserService`. This way IdSrv has a direct access to the database, and you have a working solution out of the box.
If you have specific logic in your API that you want to keep, it's not a problem. The [`AspNetIdentityUserService`](https://github.com/IdentityServer/IdentityServer3.AspNetIdentity/blob/2ece9371e67e3ed4d4e5dbd0f4acdc89b33da166/source/IdentityServer3.AspNetIdentity/IdentityServer3.AspNetIdentity.cs) methods are all virtual so you have a lot of control over how it behaves.
Plus, they started delivering the ASP.NET Identity user service as code so not only can you extend their implementation, but you can actually change it.
This would, I think, make your API obsolete, at least for login purposes.

I hope this helps.

**Comment by mabouchalkha** [comment]
can you give me more details oe example about the second option
thank you

**Comment by leastprivilege** [comment]
still an issue? feel free to re-open.
