### ISSUE TITLE
Is it possible to sign in from identityServer?

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#2302]
Is it possibile to sign in only to identityServer NOT from client application?

I.e: 
1. user open http://host.example/login (login page appears) 
2. user types credentials
3. user is redirected to main page http://host.example of identityServer and he is signed to identityServer.

Of course if user will navigate to another application he will be signed because he is signed to identityServer.

Is is possible somehow? Do i need to create identityServer as client or so?

**Comment by uncleyo** [comment]
Actually, if you go to http://host.example/permissions, you'll be challenged to authenticate.
So check how `ClientPermissionsController` is implemented. I suspect it's `[HostAuthentication(Constants.PrimaryAuthenticationType)]` that makes it work.

**Comment by pashute** [comment]
I'm only using IDServ3 not one of its developers. But here's my 2c:

The WebHost example has a server and client in the same project. So just make a simple (Nancy? - that would be the fastest) UI page that says thank you for logging in if logged in, and "you must login" if not. Decorate it with Authenticate, and your user would be logged  into the local app.  

The only problem is that now if you have another UI project - lets call it UI2 - how would UI2 know who it's logged in as?  In the example, when UI1 wants to call - in this case not another UI but rather a WebAPI app. UI1 uses the Client Calling middleware to set a bearer token before calling the API. 
Which you cannot do for the "standalone" UI2.

**Comment by pawepaw** [comment]
@uncleyo 
http://host.example/permissions is a good point. If i am not using permissions view i can simply display blank page or redirect.

Is there any other way to do this? Above solution smells like ugly hack.

**Comment by uncleyo** [comment]
Ok, you got me interested :)

The reason why you cannot access login page directly is because it requires a SignInMessage to work (it is stored in a cookie and that cookie is referenced in the query string).

So you need to issue a sign in request. I was wrong about `[HostAuthentication(Constants.PrimaryAuthenticationType)]` doing this.
It's actually in the controller itself, check [here](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/ClientPermissionsController.cs#L120-L129])

**Comment by pawepaw** [comment]
@uncleyo Yap. That is what i found. But by default i'd have to modify permission page or permission method in view service.

The other way would be to add new endpoint with this LoginResult().

**Comment by uncleyo** [comment]
Yep, definitely don't hack the ClientPermissionsController.

The only problem I can see is that LoginResult is internal.

**Comment by pawepaw** [comment]
Yap, thats not the matter. Bigger problem if it's possible to add new endpoint to server.

**Comment by leastprivilege** [comment]
You can add MVC pages "underneath" idsrv. 

this might be useful: https://github.com/IdentityServer/IdentityServer3.Extensions.Mvc

**Comment by pawepaw** [comment]
Thanks! that is helpful. 

So basically I should host identityServer under asp.net mvc app and add new controller. Those extensions will be helpful for authentication.
