### ISSUE TITLE
What would be the best way to manage sessions with IdSrv?

### ISSUE THREAD

**Issue by esugoi** [IdentityServer/IdentityServer3#2304]
Hello,
I started using Identity Server for a couple of weeks now. Until now I found it intuitive to setup, use and also very extensible. It is a great framework. I would like to know what would be the best choice for this scenario.

We have an OPC-UA client(desktop)\server system that is session dependent, meaning I have state for each session that I need to maintain both in client and server.
We like to create a client(web) version of it. For this I was thinking about creating an WebApi that would expose some methods to interact with this server and that could be consumed by other clients in the future. And the client(web) would be a SPA made with angular.
I would like to use an oid\oauth solution to authenticate\authorize users. But we need to keep an individual session opened for each user\token logged in the system and that is consuming this WebApi. These client sessions needs to be managed by the WebApi or IdSrv. Every call to the WebApi needs to retrieve the session using some kind of id. I was thinking about including the sessionid in the access token to retrieve the session; and create the session when the user authenticates, since I need the password for this.
What do you think of this or what would be the right direction?
Thank you!

**Comment by leastprivilege** [comment]
IdentityServer is "authentication as a service" - if you need something like a "logon session" you can use the sid claim that we emit. Anything else seems to be application specific and thus not an idsrv concern.

**Comment by esugoi** [comment]
Yes, you are right. Thank you for the quick reply. :)
Just wanted to read any comment on this scenario.

I was actually emitting the sid claim in the access token also, as a key to retrieve my application session when calling the WebApi.
Also, is there any way to known when the token is invalid (expired or revoked), so that I can dispose of my session (and possibly vice-versa) ? There is an IEventService in the IdSrv that raises some default events (when enabled), is this the right approach? Or should I customize other service(s) for this?

**Comment by leastprivilege** [comment]
there is no event for sessions going invalid. still an issue? feel free to re-open.
