### ISSUE TITLE
Claims Stay Empty API Server

### ISSUE THREAD

**Issue by bernardvoss** [IdentityServer/IdentityServer3#2305]
Hi, 

We're developing a angular / web api application. 

First we retrieve the token from Identityserver V3 and then sent the token from the angular app to our backend api. 

The api is configured like this: 

public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            Database.SetInitializer(new MigrateDatabaseToLatestVersion<CoreContext, Configuration>());

            JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();

            var config = new HttpConfiguration();
            ConfigAuth(app);
            ConfigWebApi(config);

            app.UseCors(CorsOptions.AllowAll);

            app.UseWebApi(config);

        }

        public void ConfigAuth(IAppBuilder app)
        {
            // accept access tokens from identityserver and require a scope of 'api1'
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://identity.phocabby.com:4443/identity",
                ValidationMode = ValidationMode.ValidationEndpoint,
                AuthenticationType = "Bearer",
                RequiredScopes = new[] { "api1" }
            });
        }

All our controllers are marked Authorize and give errors if we connect without a token. 

However within the controller context 

User.IsAuthenticated = false;

User.Claims --> no results. Nothing. 

Any suggestions what I am forgetting.

**Comment by leastprivilege** [comment]
My guess is you are using SuppressDefaultHostAuthentication somewhere? How does your ConfigWebApi method look like?

**Comment by bernardvoss** [comment]
You're correct I had that as part of my swagger configuration.
