### ISSUE TITLE
Utilizing IdentityServer3 With a Client Using an OAuth2 Framework

### ISSUE THREAD

**Issue by rkutz-hach** [IdentityServer/IdentityServer3#2307]
I'm part of a team developing an MVC Web API 2 web service that will execute on Azure. We'll have several client applications that will utilize the web service. We're utilizing IdentityServer 3 for authentication and authorization.

One of the client applications will run on an IOS mobile device. While there are several client OAuth2 frameworks that can be used in this environment, none of them refer to OpenIDConnect in their documentation. We ended up using p2/OAuth2 (https://github.com/p2/OAuth2).

Does using a framework on a client application that only supports OAuth2 but accessing IdentityServer3 pose any security risks that using a framework that supports both Oauth2 and  OpenIDConnect would not? Is this a good idea?

If it does pose special risks are there any recommendations on how to better approach this problem?

**Comment by brockallen** [comment]
The protocol is meant to be easy to consume. You don't even need a client-library (really) if you're just sticking with the OAuth2 side of things. See the OAUth2 RFC for the steps to be done. If you want OIDC, then you will need a JWT library and then just follow the steps in the OIDC RFC.

**Comment by kalanbates** [comment]
@rkutz-hach Have you looked into the Samples Repository?  The https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient[Javascript Implicit Client Sample] has an oidc.js library that might help you get started.

**Comment by rkutz-hach** [comment]
Thank Brock and Alan!
