### ISSUE TITLE
Resource Owner Password Credentials - SSO

### ISSUE THREAD

**Issue by liquidsnk** [IdentityServer/IdentityServer3#2308]
Hello guys, I'm pretty new to IdentityServer, OIDC, and identity providers in general but have spent some time with the documentation, samples and videos already and I'm looking at implementing it as Id Provider for a couple of internal applications (most of them are SPAs that contact a dedicated or sometimes shared API).
My initial interest is just to have SSO and a shared user data store. External providers and authorization restriction/delegation are not really a concern at the moment but I like the idea of having the options available in the future and also providing a solution based on a solid protocol and a proven implementation.
I understand that Resource Owner Password Credentials Flow is heavily discouraged mainly because the Client needs access to the user password directly. However, In my scenario all these applications will be internally owned and only available inside a secure intranet. Not to say that this avoids issues but it will at least be no different that what we currently do (individual login screens, replicated authentication logic through apps, and a shared user database) and will provide us with a way to integrate applications while we move them to an Implicit Flow or other suitable Flow.
However, the one missing requirement if using ROPC for some of these applications, is SSO. 
I've seen some answers where it is mentioned that ROPC does not provide SSO, but have not found the reasoning behind it.
I suppose an answer could be that given that the initial call on the Flow includes the user credentials there's no point on having SSO at all, but is this the only reason?
My understanding is that it would be technically feasible for ROPC to set a cookie on the OP like Implicit Flow does and then perhaps Clients can ask for a token from the OP before commencing the Flow in some other way without explicitly including credentials (as the cookie will achieve this). Or even, a second Client using Implicit Flow will already be authenticated by the initial one using ROPC.

But I also know that it being technically feasible means nothing, so some related questions are:
Is this not like so because it deviates completely form the protocol? 
Is it just the case that this scenario is so uncommon?
It sounds like more of a security risk than using ROPC as currently defined?
Is it just very very wrong?
Do you see any other issues with implementing something like this over IdentityServer?

I apologize if any of this sounds like a misunderstanding on my part and would really like to be pointed to the right direction if possible. I think that alternatively I would just need to use Implicit Flow and delay migration of some of the applications a little bit.
Thanks everyone for all your effort on this great work.

**Comment by uncleyo** [comment]
You'll not get SSO with ROPC because every application has to implement it's own login page and actual User Agent does not participate in the OAuth flow (doesn't make requests to IdSrv3, doesn't have any session there, etc...). So you'll have shared credentials between the apps, but not SSO.

Also, usually migrating the application to use claims based security is trickier than implementing one flow or the other, and this is something you'll have to do anyway. Why can't you just go with, say, Authorization Code flow in the first place?

**Comment by liquidsnk** [comment]
So, in most cases, these are completely browser-based applications that currently authenticate through FormsAuthentication with a particular API. They currently have individual login pages. 
I don't understand why do you say the user agent or IdSrv3 wouldn't be involved? Shouldn't my ROPC in this situation, if used, just be a post from my SPA to the IdSrv with the credentials? 

Migrating the applications to use claims In my case might involve changing the clients a little less than the resource APIs which would be better for me. In the future I was thinking on using the Implicit flow which seems more suited to SPAs and seemed to work well on my prototypes.
This might very well be the best option of course, but I would like to understand if what I say makes any sense or I'm terribly misguided (and how so).

**Comment by uncleyo** [comment]
Sorry, didn't realize you wanted to use ROPC from the SPA, I thought that would be the implementation of your forms auth behind the scenes to not change the client side app at all. I'd say ROPC form the SPA is even more discouraged. Just read https://tools.ietf.org/html/rfc6749#section-10.7

**Comment by brockallen** [comment]
I didn't read all fo this (lots of text), but the short question is: 

* Is the SPA highly trusted with the user's account credentials? 
* Do you need SSO?

If yes, and no, then what the hell -- use ROPF. If those answers ever change, then you will also have to change this decision.

**Comment by liquidsnk** [comment]
Hello. Sorry for the lenght :). Answers are yes and yes.
Would you agree that Implicit Flow seems like the best option going forward?
My questions are oriented at what would be the reasoning for ROPC or a similar flow to not also allow for SSO by setting a cookie while retieving the token? (And providing a way to check for that authentication beforehand).

Does that even make sense?

**Comment by liquidsnk** [comment]
@uncleyo Thanks. I think there is no sane way for me to keep using FormsAuth and achieve SSO while having the applications on different domains and not 'sharing' a cookie.
However, even having read again that part of the spec, and given that none of the applications involved in my scenario are third party, I'm just exploring if the reason for ROPC to not allow SSO is technical, related to the protocol, security reasons, etc. Since I think it migth be a nice fit for some of the apps while I migrate them to a better option if only it allowed for SSO. Hope I'm not missunderstanding things too much or wasting anybody's time.

**Comment by brockallen** [comment]
What @uncleyo said about SSO not working unless you use the browser.

So yes, if you need SSO then you need to have the browser involved. Implicit flow is the right one for your NG client.

**Comment by liquidsnk** [comment]
But I have the browser involved. Being an SPA, this RPOC call would be a CORS ajax call.
So in my mind this 'would' allow the opportunity to set a (third-party) cookie from the Token endpoint and then also check for it's presence or reject, for example, in a custom grant type.
But it's not my intention to mess with any of this and I understand your point. I guess this would probably be not in the spirit of what the Token endpoint is supposed to be and have implications I'm not really seeing while just discussing it, even for my very manageable scenario of internal apps.
Anyways, I will start by reading a little of the implementation of IdentityServer which I think may help clear a lot of my conceptual doubts and then set to use Implicit Flow as it seems like the right thing to do. Thanks for your help guys!

**Comment by brockallen** [comment]
Sure, but the token endpoint doesn't issue cookies, thus no SSO. Also, how would a 2nd client connect and re-use the prior cookie? Think about how that request would look. Do you send credentials? It doesn't make sense if there's already a cookie, but how do you know unless you make an request.

Anyway, try to prototype is yourself and you'll see :)
