### ISSUE TITLE
Active Directory

### ISSUE THREAD

**Issue by GVX111** [IdentityServer/IdentityServer3#2309]
Can i authorize in Active Directory with IdentityServer3?

**Comment by brockallen** [comment]
You can configure IdSvr to use AD or ADFS as an external identity provider, yes.

**Comment by GVX111** [comment]
can you give me some example or doc url?

**Comment by brockallen** [comment]
Check our docs on configuring external IdPs like ADFS. For AD-specific help, we then have this external IdP helper: https://github.com/IdentityServer/WindowsAuthentication. DOn't think we have a ton of docs on this, but there are samples.

**Comment by GVX111** [comment]
thank you
