### ISSUE TITLE
Whitespace passwords are not allowed?

### ISSUE THREAD

**Issue by urbanhusky** [IdentityServer/IdentityServer3#2311]
Hi,

is there a specific reason why whitespace-only passwords are not allowed (in resource owner password credentials flow)?

While I hope that I won't need that, I just found this while testing my login that uses this flow.

**Comment by leastprivilege** [comment]
you mean like "no password" ? i can't remember why we did not allow this - does it seem particularly useful to support it?

**Comment by urbanhusky** [comment]
Theoretically, a user could set a password that consists of only whitespace characters if the password policy doesn't catch that. He couldn't log in then - authentication fails with invalid_grant.

That might be more of a theoretical issue though, but it's something that I had to explicitly catch.

**Comment by brockallen** [comment]
I've not tested it, but it might be possible that the model binding is what's doing the trim.

**Comment by urbanhusky** [comment]
I think the error happens during validation, TokenRequestValidator line 377

```
var userName = parameters.Get(Constants.TokenRequest.UserName);
var password = parameters.Get(Constants.TokenRequest.Password);

if (userName.IsMissing() || password.IsMissing())
{
  LogError("Username or password missing.");
  return Invalid(Constants.TokenErrors.InvalidGrant);
}
```

**Comment by leastprivilege** [comment]
yep - thats by design.
