### ISSUE TITLE
Login page bookmark

### ISSUE THREAD

**Issue by georgeslegros** [IdentityServer/IdentityServer3#2312]
Hello,

I know that issue has been discussed many times but I cannot find anybody having the same flow as mine.
We have one web application with multiple tenants.
Each tenant is in fact a different DNS pointing to the same server. We use the dns to resolve which tenant is logging in.
We also use the tenant to fetch the proper style.

In the longer terms the plan is to have multiple applications using the same identity server and have different styles applied based everytime on client/tenant.

So the InvalidSignInRedirectUrl does not work in my case as this is a single link for all clients/tenants.

I think Idsrv should have the option to have the full information in the query string and drop the cookies. Or at least enough information to be able to recreate a valid url.

However, I could try to redirect to the proper URL if I had the possibility to inject the client and tenant information into the querystring next to signin.

Any clue how to proceed with this?

Thanks,

**Comment by cbomkamp** [comment]
:+1:

**Comment by bernardvoss** [comment]
We use a custom view service that overwrites this value based on the ClientID in the render option of the customviewservice. That way we can even sent several different clients to the same IdentityServer URL and still achieve these goals like styling or links.

This was important because we host our servers in Azure and do not want to add a seperate SSL certificate for each url when a new Tenant sign up for the service.

**Comment by georgeslegros** [comment]
I guess you misread my post. I did found how to customize the views based on cliendId and tenant information.

My problem is that if a user bookmarks the login page (lots of them are doing that) then they will hit identity server with an invalid signinmessage.

I want to be able to add at least the clientId and the tenant name in the query string which allows me to send him back to his original application (as for me it is something like https://[tenant].[client].com) which should trigger the whole auth flow.

BTW if this is any useful, I am using OpenIdConnect and the MvcViewService (enhanced) from the samples.

I did successfully test that if I add query string parameters (manually) then it does not disturb the flow and I can obviously retrieve those parameters in the Controller action. I can then pass the information to the View using the ViewBag or the ViewModel. I can then redirect and the flow kicks in. It all works nicely, I am just missing the way to add those parameters.

Actually a member of my team is working on implementing that in Idsrv and he'll probably create a pull request quite soon. I'll add the link here.

**Comment by bernardvoss** [comment]
Yep you are correct. that's a problem we are about to start implementing something similar in Februari so if you manage to finish it before then it would be nice to see the implementation.

**Comment by georgeslegros** [comment]
My colleague built something up that is working for us.
We are not sure however that it is the best way.

Actually we are using AcrValues to pass data in the following Form:
queryString:&nbsp;key:value

The problem is that we are using OpenIdConnect from the Owing Packages and we did not really want to override that package.

Is seems like AcrValue is not really done for that purpose but if you guys find a nicer way, please let us know.

Pull request reference: #2320
