### ISSUE TITLE
Question: Persistent mobile token with multiple idps - local, Azure AD, Okta

### ISSUE THREAD

**Issue by dahlsailrunner** [IdentityServer/IdentityServer3#2314]
HI -- I have a question about approach and was hoping to get a little pointer in the right direction.  I have implemented an Identity Server (latest version) and has a custom user service (for custom claims required by our functionality and services).  It currently supports local, AzureAD, and Okta identity providers.  I have updated our current website to use it (with ImplicitFlow) and it's working great!

Now I have a mobile app and want to use the same id process, but not require the user to sign in each time (but I do want to verify that they are still active each time they use the app.

I'm using Xamarin for the mobile app (which will target iOS and Android), so it has webviews/etc.  I want to get a token back (that can be refreshed / validated / etc) based on my desired requirements above.  

Should I be using a hybrid flow?  Okta has a direct access link that I could be putting into the app -- but I think that would entail bypassing the identity server entirely and doing api calls to get my claims (https://github.com/okta/okta-mobile-connect).  I do want/need to support both Azure AD and Okta as idp's but they will not have the claims I need.

Can you give a suggestion on how to lay this out?  I will be happy to blog about it or even contrib a sample to the Samples repo if you want.  note that the okta / saml piece requires Kentor's AuthServices module.

Thanks in advance for any guidance.
-Erik

**Comment by leastprivilege** [comment]
I would use long lived reference tokens. This way the user does not need to sign in again for this client - but the token validation will trigger the IsActiveAsync method on the user service.

**Comment by dahlsailrunner** [comment]
To clarify then, I would make API calls to various IdP's from within IsActiveAsync to ensure that the user is still active.  Sound right?

**Comment by brockallen** [comment]
Well... you could, but usually it's meant to check your own DB for your users to see if they're still active/enabled/allowed/whatever.

**Comment by dahlsailrunner** [comment]
Hmmm.  Here's my scenario -- I have a mobile app and users can login using a local account, an account from Okta, or from AzureAD.  This probably implies an implicit flow (right?), and I was hoping to not require them to enter their password for some extended period once they have done so correctly the first time.  But when they come back to the app (say) a week later, I still need to make sure they have a valid account within Okta / AzureAD (or locally).  So I could renew their token, but would want to only do so if their target account was still valid.  Does this make sense?

**Comment by brockallen** [comment]
Sure, and that's why I said you could do this -- it's just not the normal scenario. Though, we've been doing this long enough, I guess it's hard to say what's a normal scenario anymore...

**Comment by dahlsailrunner** [comment]
Nice.  Thanks and sounds about right.  :)
