### ISSUE TITLE
Identity stays null in Claims Transformation OWIN middleware

### ISSUE THREAD

**Issue by bernardvoss** [IdentityServer/IdentityServer3#2316]
I register my claims transformation middleware like below. However when I try to access Request.User in the owincontext  there no additional claims present. It's probably something with the order of using them but i've tried several other order for my App.USE statements and no result. 

Any suggestions ? 
 

```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://identity.phocabby.com:4443/identity",
                ValidationMode = ValidationMode.ValidationEndpoint,
                AuthenticationType = "Bearer",
                RequiredScopes = new[] { "api1" },
                EnableValidationResultCache = true 
            });
            app.Use(typeof(ClaimsTransformationMiddleWare));
```

**Comment by leastprivilege** [comment]
I don't know what your middleware is doing. Is this an IdentityServer question?

**Comment by bernardvoss** [comment]
My middleware is supposed to transform the incoming claims. However when i try to perform: 
ClaimsPrincipal localuser = (ClaimsPrincipal)context.Request.User; 

The user is empty. However when i perform the exact same call in a controller it returns the incoming identity and user. I would say it's an Identity server question because when i use facebook or google authentication directly on the application the middleware does receive the claims and is able to perform actions on them.  When switching to App.UseidentityBearerTokenAuthentication it stops working. 

My middleware looks like this : 
'''
 public class ClaimsTransformationMiddleWare : OwinMiddleware
        {

            private static ObjectCache Localcache { get { return MemoryCache.Default; } }

            public ClaimsTransformationMiddleWare(OwinMiddleware next)
        : base(next)
            {

            }

            public async override Task Invoke(IOwinContext context)
            {
                   
                        // user to transform 
                        ClaimsPrincipal localuser = (ClaimsPrincipal)context.Request.User;

                    // Start claims transformation 
                       


                await Next.Invoke(context);
            }
        }
    }
'''

**Comment by leastprivilege** [comment]
OwinContext.Authentication.User is the right place to look for an authenticated user.

**Comment by leastprivilege** [comment]
again - this is not a general Katana help forum. If your middleware is not doing what it is supposed to do, please use a different support channel.
