### ISSUE TITLE
 identity server3 support for Web Api and windows authentication

### ISSUE THREAD

**Issue by troperski** [IdentityServer/IdentityServer3#2317]
Hi! 
I have a  few questions about Identity Server 3 and how to implement Windows authentication with it. I have Web Api 2 application and I want to generate token for Windows authentication. I also want to enable external users to log in with username and password with token authentication. 

I've read this: https://github.com/IdentityServer/IdentityServer3/issues/1463 and followed these steps but something went wrong, it didn't work . :)
I downloaded https://github.com/IdentityServer/WindowsAuthentication and ran this in separate web app (I also created certificate that I loaded): 

public void Configuration(IAppBuilder app) 
{ 
    app.UseWindowsAuthenticationService(new WindowsAuthenticationOptions 
    { 
        IdpRealm = "urn:idp", 
        IdpReplyUrl = "http://localhost:14869/windows/", 
        SigningCertificate = X509.LocalMachine.My.SubjectDistinguishedName.Find("CN=sts").First() 
    }); 
}

Startup class in Web Api 2 app:
  
app.Map("/external",  coreApp =>
  {                   
        coreApp.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
        {
             Authority = "http://localhost:55334",
             ValidationMode = ValidationMode.ValidationEndpoint,
 
                RequiredScopes = new[] { "api1" }
       }); 
       var config = new HttpConfiguration();
       config.MapHttpAttributeRoutes();
      config.Filters.Add(new AuthorizeAttribute());
      coreApp.UseWebApi(config);
});       
  
 app.Map("/windows", idsrvApp =>
        {
  
       var authenticationOptions = new AuthenticationOptions()
       {
        EnableSignOutPrompt = true,
        EnablePostSignOutAutoRedirect = true,
        PostSignOutAutoRedirectDelay = 0,
        IdentityProviders = ConfigureIdentityProviders
      };
 
    
        idsrvApp.UseIdentityServer(new IdentityServerOptions
            {
                SiteName = "Embedded IdentityServer",
                SigningCertificate = LoadCertificate(),
                IssuerUri = "https://localhost:44306/",
                Factory = factory,                    
                AuthenticationOptions = authenticationOption,
                CorsPolicy = CorsPolicy.AllowAll,
                EnableWelcomePage = true
            });
  
                var config = new HttpConfiguration();
                config.MapHttpAttributeRoutes();
                config.Filters.Add(new AuthorizeAttribute());
                 coreApp.UseWebApi(config);
  
  
      });
  
private static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
{
    var adfs = new WsFederationAuthenticationOptions
    {
        AuthenticationType = "adfs",
        Caption = "Windows Account",
        SignInAsAuthenticationType = signInAsType,
        MetadataAddress = "http://localhost:6739/", 
        Wtrealm = " urn:idp"
    };
    app.UseWsFederationAuthentication(adfs);
}
·        For example,   when I call it from console app with the code below, it returns me JWT token:
                    var handler = new HttpClientHandler
                    {
                                         UseDefaultCredentials = true
                    };
 
                    var oauthClient = new OAuth2Client(
                                         new Uri("https://localhost: 6739/token"),
                                          handler);
 
                     var result = oauthClient.RequestCustomGrantAsync("windows").Result;
 
And when I run this code I get 401 unautorized:
 
       var client = new HttpClient();
      client.SetBearerToken(result.AccessToken);
 
      client.GetStringAsync("http://localhost: 14869/windows/test").Result);
 
 
How to autorize user with JWT token (that I got from Windows authentication server) on web api app?
 How to configure web api to check users that have authenticated with windows authentication server?
I searched for documentation but i didn't  find very much.  Am I missing something?

**Comment by leastprivilege** [comment]
learn markdown ;)
