### ISSUE TITLE
password in log files

### ISSUE THREAD

**Issue by evrardp** [IdentityServer/IdentityServer3#2321]
I've configured a token endpoint with IdentityServer.  The client application specify the username, password and the grant_type=password.

When the password is wrong, it appears in clear text in the log files.  It can give a good idea of what the right password can be.

Do I do something wrong, or maybe should the password be encrypted in the log files ?

Many thanks in advance for any relevant information.
Kind regards,
Pascla

**Comment by leastprivilege** [comment]
* logging is for dev time not runtime - check the docs
* show me log entry please
* which version are you on?

**Comment by evrardp** [comment]
The version I use is IdentityServer3, version=2.0.0 (https://www.nuget.org/packages/IdentityServer3/2.0.0).

I realized that even the successfull authentication are logged with the password in clear.

For successfull login (level info), the log is : 

Token request validation success
 {
  "GrantType": "password",
  "Scopes": "email openid profile roles",
  "UserName": "********",
  "AuthenticationContextReferenceClasses": [],
  "Raw": {
    "grant_type": "password",
    "username": "********",
    "password": "********",
    "scope": "openid profile email roles"
  }
}

When it fails, the log (level error) is : 

User authentication failed: <<my message coming from my user service>> 
 {
  "GrantType": "password",
  "Scopes": "email openid profile roles",
  "UserName": "********",
  "AuthenticationContextReferenceClasses": [],
  "Raw": {
    "grant_type": "password",
    "username": "*********",
    "password": "******",
    "scope": "openid profile email roles"
  }
}

Do you mean that I have to remove the logging from the Identity Server, and log my own message by handling the events described on the documentation https://identityserver.github.io/Documentation/docsv2/configuration/events.html ?

**Comment by evrardp** [comment]
I have disable the logging and subscribe to events.  

By default, the Identity Server plugs in the log4net configuration, which is great. 
What I find a little bit strange is that, by default, it logs password in clear.  

Thanks for your help.
Kind regards,
Pascal

**Comment by leastprivilege** [comment]
Passwords are scrubbed from the log files in later versions - you should upgrade. 

logging (depending on the level) will always contain sensitive datat: https://identityserver.github.io/Documentation/docsv2/configuration/logging.html
