### ISSUE TITLE
Question / Issue with securing a WebApi

### ISSUE THREAD

**Issue by jipock** [IdentityServer/IdentityServer3#2322]
Quick (and possibly dumb) Question - If I have an Identity Server configured on Server A and a WebApi configured to use that Identity Server on Server B, does Server B need to actually access Server A? Meaning, could I have my Identity Server on an intranet but the WebApi on a cloud server? I've done this scenario and I'm getting an error on my WebApi saying it can't access Server A. I didn't think it had to.

**Comment by brockallen** [comment]
Possibly -- it might for metadata or for validating reference tokens.

**Comment by leastprivilege** [comment]
How is your web api token validation configured?

**Comment by jipock** [comment]
I'm following the WebApi sample project (with some enterprise-specific changes). I don't have anything configured specifically on the WebApi project, other than the Authority (which points to the intranet server) and the RequiredScope. I imagine it is the Authority which is causing the issue, but the WebApi has to know what is a valid token. I just didn't know if that WebApi server actually needs to communicate with actual Identity Server. (Did I answer your question?)

**Comment by leastprivilege** [comment]
Well - when you set the authority, we try to contact that address at run time.

You can configure the issuer and signing cert statically as well - then the back channel connection is not required.

**Comment by jipock** [comment]
Thank you. Any chance you could point me in the general direction of that documentation? Much thanks.

 Btw- loved your Pluralsite courses. Hope you do some more in the future.

Sent from my Windows Phone

-----Original Message-----

**Comment by leastprivilege** [comment]
thanks.

that wouldn't have been too hard to find ;)

https://identityserver.github.io/Documentation/docsv2/consuming/options.html

**Comment by jipock** [comment]
Thanks. I just thought I'd ask, as it might be a bit faster.

I think this answers my question. Thanks again for everything.
________________________________

**Comment by jipock** [comment]
For those following along, This seems to be the right path. One thing I've found, however, is that you also need to set the ValidationMode to Local, in addition to adding the SigningCertificate and IssuerName. I'm running into a 401 Unauthorized issue in my local environment (separate servers, but both on the Intranet), which is likely another PEBCAK issue. The cert is definitely the same, but I might just have the IssuerName wrong. Will keep looking.
