### ISSUE TITLE
Redirect uri that contains fragment 

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3#2323]
Hi 

We have a site that setup as  implict JavaScript client using fragment response mode.

Some part of UI of some pages on the site is rendered by JavaScript based on hash fragment in the url after page loaded, And user also can sign from those pages as well, we need to populate redirect_uri with existing hash fragment so that our JavaScript on the page can render UI correctly after customer gets redirect back after sign in

But the problem is it breaks the oidc js sdk as it can't find the #id_token that is attached after other hash fragments

Can u suggest a proper solution for this please?

Thanks

Ming

**Comment by brockallen** [comment]
You can pass the string explicitly into the oidc-client library rather than letting it parse it.

**Comment by jeremy001181** [comment]
Ok thank you I will try it out

**Comment by jeremy001181** [comment]
What we have done is to extract out #id_token in the return url and restore the window.location.hash back to previous state, which it can be either with hash or without, 

All works except one scenario where we would like to return back to a url with no hash, and set window.location.hash to empty doesn't remove the '#' character from url., other than that it looks good

**Comment by brockallen** [comment]
Like this: 

Here's the route entry: https://github.com/IdentityManager/IdentityManager/blob/master/source/Core/Assets/Scripts/App/ttIdmApp.js#L16

And here's the controller that accepts the callback params and explicitly passes the hash to the oidc token manager: https://github.com/IdentityManager/IdentityManager/blob/master/source/Core/Assets/Scripts/App/ttIdmApp.js#L101
