### ISSUE TITLE
override app.js code file

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2324]
hello,

i try to modify the ```app.js``` JavaScript file and i add this in ```IdentityServerServiceFactory```:

```
var viewOptions = new DefaultViewServiceOptions();
viewOptions.Scripts.Add("/Content/app/app.js");
```
but if i inspect the page with page firebug, the file ```scripts.2.0.0.js``` contains the original ```app.js``` and the original code is executed.
For example i want to increase the autoredirect time:
```
window.setTimeout(function () {
     window.location = model.redirectUrl;
}, model.autoRedirectDelay * 1000);
```
 but i can't do this because the original code is executed first.
How i can override only  app.js not the entire bundle code ?

**Comment by brockallen** [comment]
Why don't you change the auto redirect delay with `PostSignOutAutoRedirectDelay` in the IdSvr config?

https://identityserver.github.io/Documentation/docsv2/configuration/authenticationOptions.html

**Comment by totpero** [comment]
is not only what i want to change. i add some logic on angular to add custom external providers icon on links and i want to try to create better single sing out mechanism to use autoredirect and iframes  because the iframes is not loaded and the sso don't works good.

**Comment by brockallen** [comment]
Well, since the code in that JS is crucial to our operation we never designed for removing or replacing it.

**Comment by totpero** [comment]
For example i add this :
```
app.filter('trustAsHtml', function ($sce) {
            return function (html) {
                return $sce.trustAsHtml(html);
            };
        });
```
and in login page, on error message i add this:
```<span ng-bind-html="model.errorMessage | trustAsHtml"></span>```
because i need to format error message using html from my server validation and angular not allow html.
