### ISSUE TITLE
How to prevent issuing tokens if user's email is not verified?

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer3#2325]
In the AspNetIdentity implementation, how can we prevent the IdentityServer3 to issue tokens if user's email is not verified?
I am particularly using the "Resource Owner Credentials Flow" but I believe whatever the solution is it would work for any flow.
Thanks.

**Comment by brockallen** [comment]
You implement this in your user service logic.

**Comment by behrooz66** [comment]
Any sample you could possibly refer to? Thanks

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3.AspNetIdentity/blob/master/source/IdentityServer3.AspNetIdentity/IdentityServer3.AspNetIdentity.cs
