### ISSUE TITLE
401 Error when Using Static Configuration for JWTs

### ISSUE THREAD

**Issue by jipock** [IdentityServer/IdentityServer3#2327]
I currently have a modified version of the WebAPI Authentication sample application which appears to work correctly out of the box. However, when I make some minor modifications to it to use a static configuration. The minor changes include adding the SigningCertificate and the IssuerName. I have confirmed that the SigningCertificate is bringing back a valid certificate. The IssuerName property in the certificate is "E=jsmith@aol.com,CN=Smith,OU=IT,O=AOL,L=NYC,S=NY,C=US". The Issuer name I've entered in the IdentityServerBearerTokenAuthenticationOptions property is 'jsmith@aol.com'. My issue is that when I use this, I get a 401 Unauthorized error. I'm running this in IIS Express in Admininstrator mode. I'm not sure why this is happening, as once I remove the IssuerName/Signing certificate and just use the Authority property, it works fine. However, I won't be able to do this in a production environment. Any suggestions on debugging / what might be wrong??

**Comment by brockallen** [comment]
Issuer in the token is the logical name of the token service, not the name in the signing cert.

**Comment by leastprivilege** [comment]
you can check the issuer name at the discovery endpoint.

**Comment by jipock** [comment]
Thank you, both. This solved my problem. I was wondering why the server would need the issuer name of a cert if the cert was already loaded.

Much thanks, again.

Sent from my Windows Phone
________________________________

**Comment by keshav2k5** [comment]
Can you Please add sample code for "Static Configuration for JWTs". 
below is my code it's throwing 401 unauthorized,  where i am doing wrong?

app.UseIdentityServerBearerTokenAuthentication(
                new IdentityServerBearerTokenAuthenticationOptions()
                {
                    IssuerName = "http://localhost:57120",
                    SigningCertificate = new X509Certificate2(certificate, SigningCertificatePassword),
                    DelayLoadMetadata = true
                }
            )
