### ISSUE TITLE
AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub"; in Web Api secured by IdentityServer3?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3#2329]
If I use the following:

JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

in the Startup class of a web api project secured by IdentityServer3, do I need to have this line too?

AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";

**Comment by farzad99** [comment]
Correction: 

... = new Dictionary&lt;string, string&gt;();

instead of:

... = new Dictionary();

**Comment by brockallen** [comment]
`AntiForgeryConfig.UniqueClaimTypeIdentifier` is for MVC when you use @Html.AntiForgertToken() and `[ValidateAntiForgeryToken]`.

**Comment by farzad99** [comment]
Thank you for your reply.
