### ISSUE TITLE
No connection string named 'AuthConfig'

### ISSUE THREAD

**Issue by eaba** [IdentityServer/IdentityServer3#2330]
I ran this command (Enable-Migrations -MigrationsDirectory Migrations\ClientConfiguration -ContextTypeName ClientConfigurationDbContext -ContextAssemblyName IdentityServer3.EntityFramework -ConnectionStringName AuthConfig) and I got this error message (No connection string named 'AuthConfig' could be found in the application config file).
I am hosting IdentityServer3 on a webapi 2 website!

Please kindly put me in the right direction.

Thank you!

**Comment by brockallen** [comment]
Wrong repo, I think.
