### ISSUE TITLE
Forms Authentication and OpenId Connect

### ISSUE THREAD

**Issue by malefteras** [IdentityServer/IdentityServer3#2332]
We have an architecture that involves a portal that uses forms authentication, issuing a cookie using the FormsAuthentication.SetAuthCookie method. This portal leads to many legacy applications. We are developing microservices and are using IdentityServer to provide JWT tokens. We have a custom user service in the IdentityService instance. Here's the functionality we're looking for:

Situation 1)
1.) User logs into portal, gets the auth cookie
2.) Portal consumes auth cookie, displays list of apps for user
3.) User clicks on an app that is wired to use IdentityServer as an OpenId Connect Identity Provider
4.) User is redirected to the IdentityServer - and in the PreAuthenticateSync method, it detects that it already has the auth cookie and converts it into a JWT, returning that JWT
5.) User is none the wiser and goes about their merry way

Situation 2) (almost the reverse)
1.) User navigates directly to app that uses the IdentityServer
2.) User is redirected to IdentityServer logon page, logs in, and receives JWT AND forms auth cookie
3.) User then navigates to legacy app that requires form authentication
4.) User is none the wiser and goes about their merry way

I think I have Situation 2 under control. I simply add a SetAuthCookie to the AuthenticateLocalAsync.
Situation 1 has me totally stumped. I've googled for hours. Is it even possible?

Thanks!

**Comment by brockallen** [comment]
So from your custom login page you want to trigger authentication to an app, but that app uses IdSvr (which in turn uses your custom login page)?

**Comment by malefteras** [comment]
The identity server would have its own custom login page. The goal is to eventually completely replace the portal's log in page - we just need to honor both in the transition.

**Comment by dturska** [comment]
This is how I achieved Situation 1:

1.) User logs into the portal and gets the auth cookie
2.) Portal creates a JWT token, saves it and generates a guid for reference. 
2.) Portal consumes auth cookie, displays list of apps for the user. The urls of the apps include the acr_value query parameter with the reference guid
3.) User clicks on an app that is wired to use IdentityServer as an OpenId Connect Identity Provider
4.) The user is redirected to the IdentityServer - and in the PreAuthenticateSync method, an API service on the Portal side is called passing the acr_value with the guid. (* need to handle RedirectToIdentityProvider in client as well, to include acr_value to Identity Server) 
5.) The portal API service uses the value in the acr_value to get the jwt token that was saved in the portal and returns the claims back to identity server. 
6.) The PreAuthenticateAsync method can then register the user as an external user and flow continues as normal. 
7.) User is none the wiser and goes about their merry way

Below is my PreAuthenticateAsync method

```C#
public override Task PreAuthenticateAsync(PreAuthenticationContext context)
            {
                var tokenId = string.Empty;

                if (context.SignInMessage.AcrValues.Any())
                {
                    tokenId = context.SignInMessage.AcrValues.ToList()[0].Replace("theportal:", string.Empty);
                }

                if (!string.IsNullOrEmpty(tokenId))
                {
                    var portalServiceEndpoint = context.SignInMessage.AcrValues.ToList()[1].Replace("endpoint:", string.Empty);
                      //Custom method to call api service on portal to get cliams
                    var entity = GetPortalClaimsIdentityEntityAsync(tokenId, PortalServiceEndpoint).Result;

                    if (entity == null)
                    {
                        return base.PreAuthenticateAsync(context);
                    }

                    var externalUser = new ExternalIdentity
                    {
                        Provider = "portal",
                        ProviderId = entity.Claims.First(c => c.Type == "unique_name").Value,
                        Claims = entity.TransformClaims()
                    };

                    var externalAuthenticationContext = new ExternalAuthenticationContext
                    {
                        ExternalIdentity = externalUser,
                        SignInMessage = context.SignInMessage,
                        AuthenticateResult = context.AuthenticateResult,
                    };

                    var result = AuthenticateExternalAsync(externalAuthenticationContext);

                    context.AuthenticateResult = externalAuthenticationContext.AuthenticateResult;

                    return Task.FromResult(0);
                }

                return base.PreAuthenticateAsync(context);
            }

```

Code for the client OpenId Connect middlleware (Client configured as mvc hybrid client in identity server)

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = Constants.ClientCredentials.ClientId,
                ClientSecret = Constants.ClientCredentials.ClientSecret,
                Authority = Constants.Endpoints.IdentityServerEndpoint,
                SignInAsAuthenticationType = Constants.AuthenticationTypeCookies,
                ResponseType = string.Join(" ", Constants.OpenIdConnectSettings.ResponseTypes),
                Scope = string.Join(" ", Constants.OpenIdConnectSettings.ScopesRequesting),
                ProtocolValidator = new Microsoft.IdentityModel.Protocols.OpenIdConnectProtocolValidator
                {
                    RequireNonce = true,
                },

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    RedirectToIdentityProvider = async (context) =>
                    {
                        context.ProtocolMessage.RedirectUri = Constants.Endpoints.BaseAddress;

                        context.ProtocolMessage.PostLogoutRedirectUri = Constants.Endpoints.BaseAddress;

                        var tokenId = context.Request.Query.Get("theportal");
                     
                        Guid tokenGuid;
                        var foundGuid = Guid.TryParse(tokenId, out tokenGuid);

                        if (foundGuid)
                        {
                            context.ProtocolMessage.AcrValues = $"theportal:{tokenGuid.ToString()}";                   
                        }

                        await Task.FromResult(context);
                    },

.......
```

**Comment by leastprivilege** [comment]
still an issue? feel free to re-open.
