### ISSUE TITLE
Post Logout Redirect is not working

### ISSUE THREAD

**Issue by itorian** [IdentityServer/IdentityServer3#2334]
I've a working Identity Server deployed on azure website, so it has SSL support already. When I click logout on my MVC client application, this redirects me to identity server for logout that's normal. But i need logout request to be redirected back to my MVC client application. Here's the setup I've used:

Client Startup.cs:-

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "mvcapp",
                Authority = TestMVCConstants.IdentityServer,
                RedirectUri = TestMVCConstants.TestMVCClient,
                PostLogoutRedirectUri = TestMVCConstants.TestMVCClient,
                SignInAsAuthenticationType = "Cookies",
                ResponseType = "code id_token token",
                Scope = "openid profile email roles",
                Notifications = new OpenIdConnectAuthenticationNotifications()
                {
                    SecurityTokenValidated = async n =>
                    {
                        // some codes
                    },
                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }
                        }
                        return Task.FromResult(0);
                    },
                }
            });

Client Logout Controller Action :-

        [AllowAnonymous]
        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut(new AuthenticationProperties { RedirectUri = TestMVCConstants.TestMVCClient });
            return Redirect("/");
        }

Identity Server Startup.cs (deployed on azure website):-

            app.Map("/identity", identityServerApp =>
            {
                identityServerApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "TestMVC Identity Server",
                    IssuerUri = TestMVCConstants.IdentityServerIssuerUri,

                    Factory = InMemoryFactory.Create(
                        users: Users.Get(),
                        clients: Clients.Get(),
                        scopes: Scopes.Get()),
                    SigningCertificate = LoadCertificate(),
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        IdentityProviders = ConfigureIdentityProviders,
                        EnablePostSignOutAutoRedirect = true,
                        EnableSignOutPrompt = false,
                    }
                });
            });
        }

Identity Server Client class:-

    public class Clients
    {
        public static IEnumerable<Client> Get()
        {
            return new[] { new Client {
                Enabled = true,
                ClientName = "TestMVC Identity",
                ClientId = "mvcapp",
                Flow = Flows.Hybrid,
                RequireConsent = true,
                AllowRememberConsent = true,
                RedirectUris = new List<string> { TestMVCConstants.TestMVCClient },
                PostLogoutRedirectUris = new List<string> { TestMVCConstants.TestMVCClient },
                AccessTokenType = AccessTokenType.Jwt
            } };
        }
    }

In my case TestMVCConstants.TestMVCClient is https://localhost:44304/
I'm also using Facebook, Twitter, Gooolge OAuth. I enabled logging to check issues but can't get sufficient information in log, please find attached log file. I modified azure website url in log file for security reasons. To enable this logging i'hd used following code in identity server startup configuration.

      LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());

[Trace.txt](https://github.com/IdentityServer/IdentityServer3/files/70809/Trace.txt)

Please help me to resolve the issue.

**Comment by brockallen** [comment]
It doesn't look like the id_token hint or the post logout redirect URI are being seen in the end session endpoint. Check on HTTP level if those are being sent to IdSvr in the query string.

**Comment by itorian** [comment]
@brockallen thanks for quick response. I can see idTokenHint is null. So I just updated Client Startup.cs file as given below:

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "mvcapp",
                Authority = TestMVCConstants.IdentityServer,
                RedirectUri = TestMVCConstants.TestMVCClient,
                PostLogoutRedirectUri = TestMVCConstants.TestMVCClient,
                SignInAsAuthenticationType = "Cookies",
                ResponseType = "code id_token token",
                Scope = "openid profile email roles",
                Notifications = new OpenIdConnectAuthenticationNotifications()
                {
                    SecurityTokenValidated = async n =>
                    {
			            // some codes
                        var userInfo = await EndpointAndTokenHelper.CallUserInfoEndpoint(n.ProtocolMessage.AccessToken);
                        var id_token = n.ProtocolMessage.IdToken;
                        newIdentity.AddClaim(new Claim("id_token", id_token));
			            // some codes
                    },
                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }
                        }
                        return Task.FromResult(0);
                    },
                }
            });

I added id_token in list of claims in SecurityTokenValidated callback and used this in RedirectToIdentityProvider callback. With this change logout redirection started working. Anyone facing similar issue, please follow above steps as well as this change.
Thanks.

**Comment by hargrave81** [comment]
I'm having the same issue I think, but "some code" above and below SecurityTokenValidated must be the key as I cannot solve the problem.

  I am using custom views (but literally just the copied versions from the sample).  I traced it through the IdentityServer3.DLL that the "Logout" Action in AuthenticationController receives an ID but I have been unable to step through it to read it actually getting the cookie to populate the redirectUrl, when you look at the model, its null.
 
````
public void Configuration(IAppBuilder app)
        {
            System.Web.Helpers.AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";            

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "12345678-f281-40ee-8b02-7e4ce6e72bea",                
                Authority = baseServer,   // where the identity server is
                RedirectUri = "https://local.sample.com/",  // where in this app we should land, this app has to be registed with identity server
                PostLogoutRedirectUri = "https://local.sample.com/",
                ResponseType = "code id_token token",
                Scope = "openid email profile offline_access roles",
                SignInAsAuthenticationType = "Cookies",
                

                //////////////////////// refresh token
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    AuthorizationCodeReceived = async n =>
                    {
                        var identity = n.AuthenticationTicket.Identity;                        

                        var nIdentity = new System.Security.Claims.ClaimsIdentity(identity.AuthenticationType, "email", "role");


                        var userInfoClient = new Thinktecture.IdentityModel.Client.UserInfoClient(
                            new Uri(baseServer + "/connect/userinfo"),
                            n.ProtocolMessage.AccessToken);


                        var userInfo = await userInfoClient.GetAsync();
                        userInfo.Claims.ToList().ForEach(x =>
                            nIdentity.AddClaim(new System.Security.Claims.Claim(x.Item1, x.Item2)));

                        var tokenClient = new Thinktecture.IdentityModel.Client.OAuth2Client(new Uri(baseServer + "/connect/token"), "12345678-f281-40ee-8b02-7e4ce6e72bea", "too many secrets");
                        var response = await tokenClient.RequestAuthorizationCodeAsync(n.Code, GetHomePage());

                        if (!String.IsNullOrEmpty(response.AccessToken))
                        {

                            Repositories.LoginRepository lr = new Repositories.LoginRepository();
                            var user = lr.GetBy(nIdentity.Claims.First(t => t.Type == "sub").Value);
                            Session.currentLogin = user.Login;
					

							nIdentity.AddClaim(new System.Security.Claims.Claim("access_token", response.AccessToken));
							nIdentity.AddClaim(new System.Security.Claims.Claim("id_token", response.IdentityToken));
							nIdentity.AddClaim(new System.Security.Claims.Claim("expires_at",
								DateTime.UtcNow.AddSeconds(response.ExpiresIn)
								.ToLocalTime()
								.ToString(CultureInfo.InvariantCulture)));
							nIdentity.AddClaim(new System.Security.Claims.Claim("refresh_token", response.RefreshToken));
							nIdentity.AddClaim(new System.Security.Claims.Claim("sid", n.AuthenticationTicket.Identity.FindFirst("sid").Value));


							n.AuthenticationTicket = new Microsoft.Owin.Security.AuthenticationTicket(
								nIdentity,
								n.AuthenticationTicket.Properties);
                        }
                        else
                        {
                            n.AuthenticationTicket.Properties.RedirectUri = GetOuterPage() + "app/Account/LogOff";

                        }                       
                    },
                    SecurityTokenValidated = n =>
                    {
                        var user = n.AuthenticationTicket.Identity;
                        user.AddClaim(new System.Security.Claims.Claim("access_token", n.ProtocolMessage.AccessToken));
                        user.AddClaim(new System.Security.Claims.Claim("id_token", n.ProtocolMessage.IdToken));
                        user.AddClaim(new System.Security.Claims.Claim("code", n.ProtocolMessage.Code));
                        return Task.FromResult(0);
                    },
                    RedirectToIdentityProvider = n =>
                    {
                        n.ProtocolMessage.RedirectUri = GetHomePage(); // dynamic home page for multiple subdomains
                        n.ProtocolMessage.PostLogoutRedirectUri = GetOuterPage(); // dynamic landing page for multiple subdomains
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }
                            
                        }

                        return Task.FromResult(0);
                    }
                }
                //////////////////////////////////////
            });
        }
`

**Comment by brockallen** [comment]
It's hard to say. If something's not working in your project, then you'd have to compare it to the working samples and sort out the diff.
