### ISSUE TITLE
Potential Feature Request: Custom scope without the explicit requirement of the openid scope

### ISSUE THREAD

**Issue by a-tok** [IdentityServer/IdentityServer3#2336]
Hey guys,

I'm very particular about how my code looks, and I don't know if the benefits of this "feature" would outweigh the cost in development time, but still...

Consider this scenario:
http://localhost:44333/connect/authorize?client_id=app1&scope=openid%20customScope&response_type=id_token.....

I would love to have the flexibility of creating a custom scope without explicitly specifying the openid scope.
e.g: http://localhost:44333/connect/authorize?client_id=app1&scope=customScope&response_type=id_token....
(Currently this would cause an error that the openid scope is required)
new Scope
{
      Name="customScope",
     ....
     Type = ScopeType.Identity,
     Claims = new List<ScopeClaim>
     {
          new ScopeClaim(Constants.ClaimTypes.Subject, alwaysInclude: true),
          new ScopeClaim("blah", true)
          new ScopeClaim("blah2", true)
     }
}
The custom scope itself would contain the scope claims that would normally be included with the openid scope. Perhaps if the custom scope doesn't have the subject scope claims, then it could fallback to the default check. 

What are your thoughts on that?

Thank You

**Comment by leastprivilege** [comment]
openid is required per spec.
