### ISSUE TITLE
Using ASP.NET Identity Database instead of InMemory Users with Roles

### ISSUE THREAD

**Issue by itorian** [IdentityServer/IdentityServer3#2337]
I'm trying to use ASP.NET Identity database on Identity Server instead of InMemory Users and Roles and for this I installed required packages and made following changes in IdentityServer Startup.cs file:

        public void Configuration(IAppBuilder app)
        {
            LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());

            app.Map("/identity", identityServerApp =>
            {
                var factory = new IdentityServerServiceFactory()
                                    .UseInMemoryUsers(Users.Get())
                                    .UseInMemoryClients(Clients.Get())
                                    .UseInMemoryScopes(Scopes.Get());
                factory.UserService = new Registration<IUserService>(UserServiceFactory.Create());  //UserServiceFactory defined in another class file

                identityServerApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Test MVC Server",
                    IssuerUri = TestMVCConstants.IdentityServerIssuerUri,

                    //Factory = InMemoryFactory.Create(
                    //    users: Users.Get(),
                    //    clients: Clients.Get(),
                    //    scopes: Scopes.Get()),

                    //// Using ASP.NET Identity database
                    Factory = factory,

                    SigningCertificate = LoadCertificate(),
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        IdentityProviders = ConfigureIdentityProviders,
                        EnablePostSignOutAutoRedirect = true,
                        EnableSignOutPrompt = false,
                    }
                });
            });
        }

        public static AspNetIdentityUserService<IdentityUser, string> Create()
        {
            var context = new IdentityDbContext();
            var userStore = new UserStore<IdentityUser>(context);
            var userManager = new UserManager<IdentityUser>(userStore);

            return new AspNetIdentityUserService<IdentityUser, string>(userManager);
        }

With this change I always see "The client application is not known or is not authorized" error message on Identity Server. However, this application was working great with InMemory Users and Roles. Even I double checked the client app registration which looks fine.

Any help on this is highly appreciated.

**Comment by leastprivilege** [comment]
As always - check the logs first before posting.

**Comment by itorian** [comment]
Log has no sufficient info, just this:
SnapshotHelper::RestoreSnapshotInternal SUCCESS - File.Copy
SnapshotHelper::RestoreSnapshotInternal SUCCESS - process
Tried this https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity/WebHost sample also, same issue and log.
Any other pointers?

**Comment by leastprivilege** [comment]
You are looking at the wrong logs. Check the docs.

**Comment by itorian** [comment]
Using Serilog now, here's the trace

    w3wp.exe Warning: 0 : 2015-12-24 11:18:05.974 +00:00 [Warning] AuthorizationCodeStore not configured - falling back to InMemory
    w3wp.exe Warning: 0 : 2015-12-24 11:18:05.990 +00:00 [Warning] TokenHandleStore not configured - falling back to InMemory
    w3wp.exe Warning: 0 : 2015-12-24 11:18:05.990 +00:00 [Warning] ConsentStore not configured - falling back to InMemory
    w3wp.exe Warning: 0 : 2015-12-24 11:18:05.990 +00:00 [Warning] RefreshTokenStore not configured - falling back to InMemory
    w3wp.exe Information: 0 : 2015-12-24 11:18:47.852 +00:00 [Information] Start discovery request
    w3wp.exe Information: 0 : 2015-12-24 11:18:48.602 +00:00 [Information] Start key discovery request
    w3wp.exe Information: 0 : 2015-12-24 11:18:50.361 +00:00 [Information] Start authorize request
    w3wp.exe Information: 0 : 2015-12-24 11:18:50.376 +00:00 [Information] Start authorize request protocol validation
    w3wp.exe Error: 0 : 2015-12-24 11:18:50.408 +00:00 [Error] Requested scope not allowed: "openid"
    w3wp.exe Information: 0 : 2015-12-24 11:18:50.426 +00:00 [Information] End authorize request

Most of them are working but just one error which is Requested scope not allowed: "openid". I see this is being requested by the MVC client application.
Removing this from client causes invalid_request error in client app.

**Comment by itorian** [comment]
So to resolve issue Request scope not allowed: "openid" which was found in log, I grated for client on indentity server using AllowedScopes. Here's my new client on identity server:

    public class Clients
    {
        public static IEnumerable<Client> Get()
        {
            return new[] {
                new Client {
                    Enabled = true,
                    ClientName = "Knorish Identity",
                    ClientId = KnorishConstants.KnorishWebClientId,
                    Flow = Flows.Hybrid,
                    RequireConsent = true,
                    AllowRememberConsent = true,
                    RedirectUris = new List<string> { KnorishConstants.KnorishWebClient },
                    PostLogoutRedirectUris = new List<string> { KnorishConstants.KnorishWebClient },
                    AccessTokenType = AccessTokenType.Jwt,
                    // new code below
                    AllowedScopes = new List<string>
                    {
                        "openid", "profile", "email", "roles"
                    }
                }
            };
        }
    }

I also need similar thing on server IdentityServerServiceFactory as given below:

            var scopeStore = new InMemoryScopeStore(Scopes.Get());
            factory.ScopeStore = new Registration<IScopeStore>(scopeStore);

And on the client again I need to tell server about scopes:

                // other codes
                ClientId = TestMVCConstants.TestMVCWebClientId,
                Authority = TestMVCConstants.IdentityServer,
                RedirectUri = TestMVCConstants.TestMVCWebClient,
                PostLogoutRedirectUri = TestMVCConstants.TestMVCWebClient,
                SignInAsAuthenticationType = "Cookies",
                ResponseType = "code id_token token",
                Scope = "openid profile email roles",
                // other codes

Now I've following questions:

1. Looks like overcoded in identity server. Or, should I consider IdentityServerServiceFactory scopes as global setup for identity server ?

2. I've custom fields in ASP.NET Identity database like FirstName and LastName, this cause another error:

     w3wp.exe Error: 0 : 2015-12-24 11:59:52.541 +00:00 [Error] Unhandled exception
     System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'FirstName'.
Invalid column name 'LastName'.

Now how to tell identity server about these new columns in ASP.NET Identity database?

**Comment by itorian** [comment]
Issue resolved. In Identity Server I had SimpleEntities.cs file (https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/AspNetIdentity/WebHost/AspId/SimpleEntities.cs) which includes these two custom fields. I commented to resolved the issue.
