### ISSUE TITLE
How to auto login by cookie?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2338]
Before using idsrv3, our company has an SSO server, and there are many old sites use it to SSO. But recently, our company start to use idsrv3 and we cannot sitch all the old sites to the new idsrv3 once. So I want to analyze the old SSO server's cookie when the IE request the idsrv3 to login. If it have valid cookie, and then I auto login without show a login page.
Is there any Interface in idsrv3 like IRequestLogin? or how do I to solve this problem?

**Comment by leastprivilege** [comment]
you can run code before the login page shows - IUserService.PreAuthenticateAsync

**Comment by Farwell-Liu** [comment]
I got it, Thank you very much!
