### ISSUE TITLE
Token end point response

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3#2339]
Is there anyway to add another property in the JSON response provided by token end point ?

eg: 

{
  "access_token": "4f7190800af9100b3716c5f25c5180ae",
  "expires_in": 3600,
  "token_type": "Bearer",
  "two_factor": "459"
}

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3/issues/2290
