### ISSUE TITLE
Refreshing reference access token claims

### ISSUE THREAD

**Issue by sunniejai** [IdentityServer/IdentityServer3#2340]
Hi, we were thinking of using long lived access tokens in our app (let's say 1 year), and looked into the Entity Framework option for storing the access tokens. I noticed that there's a column named JsonCode that stores all the claims.

My question is that if a user changes their username, or first name, etc do those claims become stale? And is there a easy way to refresh them?

**Comment by brockallen** [comment]
We only have something like that for refresh tokens with the `Client.UpdateAccessTokenClaimsOnRefresh` config setting.

**Comment by leastprivilege** [comment]
IOW - don't put data into tokens that might change (frequently).

That said - we have a claims update feature on our todo list - but not on the urgent one - because see above.
