### ISSUE TITLE
Adding extra field to the login page

### ISSUE THREAD

**Issue by Krishna-teja** [IdentityServer/IdentityServer3#2341]
According to our business we have three fields in login form. Is there anyway to add extra field in the login page which is used for authentication in addition to username and password?

**Comment by brockallen** [comment]
Sure, add it in the HTML, and then in your user service inject the `OwinEnvironmentService` and then read the posted value.

**Comment by Krishna-teja** [comment]
Thanks a lot.

**Comment by CesarD** [comment]
I'm trying to do as explained, by setting ng-model="model.domain" for an extra field in my login page, but when reading the request.body from the OwinEnvironmentService, it only returns the username, password and antiforgery token. No extra field present.
What am I missing?
