### ISSUE TITLE
Strange claim format issue when using reference tokens

### ISSUE THREAD

**Issue by narciero** [IdentityServer/IdentityServer3#2342]
I currently have a custom UserService (extends AspNetIdentityUserService) that overrides the GetProfileDataAsync method to add some custom claims to a user's token. One of the claims I'm adding is a date that I convert to a string using an explicit date format string "yyyy-MM-ddTHH:mm:ss.fZ" ...here's a snippet from my helper method that is called from within GetProfileDataAsync to get the custom claims

    var subscriptionExpirationClaim = new Claim(Core.Constants.ClaimTypes.SubscriptionExpirationDateUtc, subscriptionInfo.ExpirationDateUtc.HasValue ? subscriptionInfo.ExpirationDateUtc.Value.ToString(Core.Constants.DateTimeUtcFormat) : null);
    claims = claims.Concat(new[] { subscriptionExpirationClaim });

    return claims;

Now on my API I have it setup using  IdentityServer.AccessTokenValidationMiddleware and then a custom WebApi filter which checks this custom expiration date claim. When making API calls with a client that uses JWT access tokens everything works great, however when using reference tokens the strangest thing happens - the value of the expiration date claim somehow gets reformatted to a local time string with a completely different format ex) "12/25/2016 8:30:00 PM" ... I have debugged both ends (IdentityServer and the API) and IdentityServer is always creating and adding the claims the exact same way but once the API unpacks the reference token into a Principal that one claim has a different string. The strangest thing is that the claim's value is always a string (it cant be a DateTime) so I'm wondering if reference tokens are handled differently in any way as I have no problem with JWT. Thanks!

**Comment by leastprivilege** [comment]
Well - reference tokens are def. handled differently. But not sure where that difference is with regards to your specific problem.

I would use Epoch time instead.

**Comment by narciero** [comment]
Ok I'll switch to Epoch.
