### ISSUE TITLE
How do I access custom claim in client startup.cs

### ISSUE THREAD

**Issue by itorian** [IdentityServer/IdentityServer3#2344]
How do I access custom claims in client startup.cs. It was easy to access when I had InMemory list of users with roles. But now I'm using ASP.NET Identity database, custom scopes is not available on client.

**IdentityServer Startup.cs (look at authProvider, somethingCustom claims in Facebook provider OnAuthenticated):-**

    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            // Log.Logger = new LoggerConfiguration().MinimumLevel.Debug().WriteTo.Trace().CreateLogger();

            app.Map("/identity", core =>
            {
                var idSvrFactory = Factory.Configure();
                idSvrFactory.ConfigureUserService("TestMVCContext");

                var options = new IdentityServerOptions
                {
                    SiteName = "TestMVC Identity Server",
                    IssuerUri = TestMVCConstants.IdentityServerIssuerUri,
                    SigningCertificate = LoadCertificate(),
                    Factory = idSvrFactory,
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        IdentityProviders = ConfigureIdentityProviders,
                        EnablePostSignOutAutoRedirect = true,
                        EnableSignOutPrompt = false,
                    }
                };
                core.UseIdentityServer(options);
            });
        }

        private void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            app.UseFacebookAuthentication(new FacebookAuthenticationOptions
            {
                AuthenticationType = "Facebook",
                Caption = "Sign-in with Facebook",
                SignInAsAuthenticationType = signInAsType,
                AppId = "xxxxxx",
                AppSecret = "xxxxxx",
                Provider = new FacebookAuthenticationProvider()
                {
                    OnAuthenticated = (context) => {
                        context.Identity.AddClaim(new Claim("authProvider", "Facebook"));
                        context.Identity.AddClaim(new Claim("somethingCustom", "something"));
                        // TODO Future Scope: Get roles from database for OAuths
                        return Task.FromResult(context);
                    }
                }
            });
        }
        // other codes
    }

**MVC Client Startup.cs (look at authProvider, somethingCustom variables in SecurityTokenValidated):-**

    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.CreatePerOwinContext(ApplicationDbContext.Create);
            app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);
            app.CreatePerOwinContext<ApplicationSignInManager>(ApplicationSignInManager.Create);

            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
            AntiForgeryConfig.UniqueClaimTypeIdentifier = "unique_user_key";

            app.UseResourceAuthorization(new AuthorizationManager());
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = TestMVCConstants.TestMVCWebClientId,
                Authority = TestMVCConstants.IdentityServer,
                RedirectUri = TestMVCConstants.TestMVCWebClient,
                PostLogoutRedirectUri = TestMVCConstants.TestMVCWebClient,
                SignInAsAuthenticationType = "Cookies",
                ResponseType = "code id_token token",
                Scope = "openid profile email roles testmvcapi",
                Notifications = new OpenIdConnectAuthenticationNotifications()
                {
                    SecurityTokenValidated = async n =>
                    {
                        var userInfo = await EndpointAndTokenHelper.CallUserInfoEndpoint(n.ProtocolMessage.AccessToken);
                        var newIdentity = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType, JwtClaimTypes.GivenName, JwtClaimTypes.Role);

                        var authProvider = userInfo.Value<string>("authProvider");  //not found
                        var somethingCustom = userInfo.Value<string>("somethingCustom");  //not found

                        // other codes
                    }
                }
            });
        }
    }

How do I access these custom claims, I need identity server to validate everything related to user account like email id is validated, account is not blocked etc this should work with OAuths providers as well.
Is something I'm doing wrong?

**Comment by brockallen** [comment]
Do you know about the user service? That's the code you have to write.

**Comment by itorian** [comment]
Yes, i just code it work. Thanks.
