### ISSUE TITLE
question about auth endpoint acr_values 

### ISSUE THREAD

**Issue by engenb** [IdentityServer/IdentityServer3#2345]
I'm seeing that acr_values are part of the OpenId Connect authorization spec.   I see that the acr values (if satisfied) are returned as acr claims.

I'm interested in the special tenant acr value mentioned in the IdSrv auth endpoint doc.  I would expect that IdSrv needs to verify this ```tenant:name_of_tenant``` value somewhere, but I am seeing where that is.  Does this require MembershipReboot's multi-tenant features?

**Comment by brockallen** [comment]
Tenant is just a convenience for something that applications might commonly like to use. There's no requirement for it anywhere or in any way. The MR user services does take advantage of it if it's present IIRC.

**Comment by engenb** [comment]
Does MR also validate the tenant exists and has some relationship to the client requesting a token?

**Comment by brockallen** [comment]
MR knows nothing about IdSvr. Perhaps it'd be easier to look at the MR user service: https://github.com/IdentityServer/IdentityServer3.MembershipReboot/blob/master/source/IdentityServer3.MembershipReboot/IdentityServer3.MembershipReboot.cs

**Comment by engenb** [comment]
ok I think I've got it.  Tenant is a property of the user account that is additionally validated as part of authentication.

**Comment by brockallen** [comment]
Yep.

**Comment by engenb** [comment]
Thanks!
