### ISSUE TITLE
Custom page doesn't working in Asp.net 5

### ISSUE THREAD

**Issue by quantruong** [IdentityServer/IdentityServer3#2348]
Hello,
I'm creating the custom page by using LoginPageLinks option in AuthenticationOptions. But, I can't access this URL on the browser. It's display blank page and status is 404. How to do create the custom page in asp.net 5?

**Comment by leastprivilege** [comment]
I don't follow. Explain.

**Comment by quantruong** [comment]
I used Identity Server v3 on asp.net 5. And it works. Now, I need create register page.This page allow create new user. I have following this example https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService/CustomUserService.  But, it doesn't work. I access this url on browser.And I get blank page and status is 404. How to do that on asp.net 5?

**Comment by leastprivilege** [comment]
on ASP.NET 5 you need to set the path to your templates folder explicitly. IIRC that's on the DefaultViewService.

**Comment by quantruong** [comment]
Thanks @leastprivilege, Do you have any sample for that?

**Comment by leastprivilege** [comment]
@brockallen will get back to you.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3/issues/2166
