### ISSUE TITLE
Question: How to use external service for authentication

### ISSUE THREAD

**Issue by kiran-mahadev** [IdentityServer/IdentityServer3#2349]
Hi,

I seek your guidance.

BACKGROUND -
We have an application that has AngularJS on the client-side and Web API for the back-end.

REQUIREMENT -
I'm calling my application as "A" for the discussion. Application "A" is supposed be used by external users (Users who are not registered with application "A"). These external users are say from application "B".

There is no common STS between these two applications.

I'm supposed to allow users from application "B" to use application "A", only if they pass authentication from some authentication service (SOAP based) that application "B" provides.

QUESTIONS -
1. Can I create a login screen in STS to capture application "B" user credentials? And,
2. Can STS call into the SOAP service that application "B" provides to authenticate external user credentials?
OR
As, there is no common STS - I would have to create a wrapper API (on application "A") that calls authentication service of application "B". In which case -
a. I should simply authenticating my AngularJS client in the STS. Following the client application authentication - STS will return an access token to the AngularJS client.
b. The AngularJS client can then provide a screen to capture application "B" user credentials
c. Following this, it can call the wrapper API using the access token and pass the user credentials and in turn the wrapper API calls the SOAP service that application "B" provides to authenticate it's users

Regards,
Kiran

**Comment by brockallen** [comment]
1 & 2. Yes, but why would an end user trust your login page with their credentials for B?

**Comment by kiran-mahadev** [comment]
Thanks for your time Brock!

Sorry, I just didn't put enough details on my Requirements. The authentication service that I was talking about doesn't take usernames and passwords of application "B" users. Instead, it validates if the user is registered using some fields (FirstName, LastName, DOB and Last 4 of SSN).

So, I planned to create a view that accepts these 4 fields as input in application "A"

**Comment by brockallen** [comment]
Well, the answer is still yes. The place you write this logic is in the user service. Check the docs for more iinfo.

**Comment by kiran-mahadev** [comment]
Ok. Thank you very much Brock.

Wish you and your family a very happy new year 2016!!
