### ISSUE TITLE
Advice on Forms Authentication to IdSrv Implicit flow transition

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2350]
Hi guys, so i originally asked a similar question a while back, but after advice i've done lots of reading, playing around with samples, but i'm still a little stumped onto how to apply it all to my existing application.

I have a legacy MVC application which uses Forms Authentication and `[Authorize]` attributes to do authentication/authorization respectively. We are slowly rebuilding this MVC app into a SPA application page by page. e.g we add a new empty MVC action/view, which serves up a ReactJS page that calls into a REST API. Long term goal = MVC app decommissioned, and SPA app is served up by a Node backend, calling into the REST API.

I want to move to IdentityServer and ideally use Implicit flow (as this seems to be what is recommended in this scenario), but i'm struggling to figure out how to slowly transition across without breaking the legacy codebase and/or rewriting a lot of it (example: i can't use the OWIN middleware such as `app.UseOpenIdConnectAuthentication` on my MVC app, since this runs before it hits my app, and therefore will break legacy Forms Auth pages).

This is how it currently works:
1. User is presented with login page (hosted by my MVC app)
2. User enters credentials and posts to MVC server
3. Forms Authentication cookie is issued by MVC server

When visiting various authorized pages, the `[Authorize]` attribute does it job and checks the forms authentication cookie for the various roles etc. Pretty common setup.

For the **new** pages, the API that serves up the SPA pages doesn't care about Forms Auth - it just needs an access token and uses claims-based authorization.

So i need to figure out a way for the legacy web app to continue to use Forms Authentication to perform the server-side auth on the pages themselves, but also pass along an IdSrv access token to the API.

After reading about all the flows, trying demos etc...the only solution (or should i say, the one that appears to be the least painful) i've come up with is to use ROPC flow - that is, modify the above steps to be:

1. User is presented with login page (hosted by my MVC app)
2. User enters credentials and posts to MVC server
3. Server passes on user credentials to IdSrv via ROPC, gets back access token
4. Forms Authentication cookie is issued by MVC server, as well as access token stored in a cookie (because it needs to be cleared when a logout is performed).

Does it work? Sure! 

*But*, the problems are:
a) From my understanding, this isn't recommended because my web app is in the untrusted/internet zone and my client app controls the users credentials (even though it currently already does, but i want to move away from this)
b) i'll need to rewrite the frontend SPA app auth process again to use implicit flow once 100% cutover/broken away from the MVC server
c) the MVC server app knows about the access token, as it needs to clear it out when i signout. I want to decouple the forms auth from the access token to make the transition easier. Basically, the two authentication schemes are tightly coupled.

Can anyone see how i can use the implicit flow here? I'm thinking something like:

1. Uses tries to visit `/somelockeddownpage`
1. User gets redirected to IdSrv login page by MVC app, passing through `/callback` as redirectUri, as well as `/somelockeddownpage` as query string param
2. User goes through login process, is redirected back to my MVC app
3. On MVC app callback page (`/callback`), Forms Authentication cookie is issued by server to fulfill legacy requirements, as well as access token in URL fragment.
4. Frontend JS then grabs access token, stores in localStorage then redirects page to original page (`/somelockddownpage`).

This way, legacy pages don't care about the access token, and the new pages don't care about the Forms Authentication cookie. Then when the app is purely SPA, nothing needs to change. The added bonus here being my iOS app can use the same implicit flow.

Is this even possible? Has anyone done it before, and/or can point me to some examples?

There are also some gotcha's/other legacy scenarios that i have to deal with, but i'll leave them out of this question for now, unless the discussion here prompts for them.

Appreciate any advice, and sorry for the long question. Please don't tell me to go and read the OAuth docs, play with the IdSrv samples etc, as that's basically all i've been doing for the past month. I understand all the high-level concepts/flows etc - now i'm down to the specifics of how to implement them in my scenario, which i need help with. I've chosen the one i have found most suitable (ROPC), but now i'm looking for guidance on if it's the right approach, or if i can do better.

Thanks in advance.

**Comment by brockallen** [comment]
Long post -- I only got thru the first part so far: 

So in short for a while you will have an app that uses cookies and is a SPA for some pages. In this transition period I usually use the server-side Katana OIDC middleware with the cookie MW (replacing the old forms auth code). The OIDC MW will store the access token as a claims in the cookie MW claims, and I then render the access token into the SPA pages for calling the Web APIs. 

I think the trick is ditching forms auth in favor of cookie MW. I'll read the rest of your post now -- just wanted to get this thought on paper before I forgot.

**Comment by brockallen** [comment]
Ok, so yea... if possible I think the key is ditching forms auth in favor of OIDC+CookieMW. The old pages should work the same, since the ClaimsPrincipal is backwards compat with the `Identity.Name` and `IsInRole` APIs.

**Comment by RPM1984** [comment]
@brockallen thanks for your answer. So when you refer to OIDC + CookieMW, i assume you are talking about things like:

`app.UseOpenIdConnectAuthentication`
`app.UseCookieAuthentication`.

Here's where i mention the other legacy scenarios i alluded to. :smile: The one codebase handles multiple applications (think app `blue` and app `red`). I only want to update app 'blue'. The app is determined by the hostname... like a whitelabel. MW is too early on in the pipeline to differentiate. ROPC flow works, because in my MVC backend i check if the app is `blue`, if so do the IdSrv handshake, otherwise continue along.

So i don't think i can use any of the MW's. Any other advice? Can i do it without the MW, e.g the implicit flow i described?

**Comment by RPM1984** [comment]
@brockallen i've decided to only use IdSrv for the access token side of things for my legacy app. E.g the legacy app won't request identity scopes, rather only the access token for use on the API using ROPC flow. The legacy app handles authentication with Forms Auth as current. Then once legacy removed, cutover to implicit flow (identity + access tokens). Happy to close this off for now.

**Comment by RPM1984** [comment]
@brockallen sorry to comment on this again, but i have a question regarding access tokens (relating to this issue). I'm going to continue to use Forms Authentication for my authentication and use IdSrv for my authorization/API access (ROPC flow). But the issue is getting new access tokens (i'd have to keep passing U/P to token endpoint, which i can't really do). My forms authentication cookie is currently 7 days _sliding_. Can i make the access token sliding, if i'm using ROPC? I was thinking as a short-term solution i could just make the access token lifetime longer than my Forms Authentication cookie lifetime (so when the forms auth cookie expires, i re-authenticate the user and get new cookie/token), but i can't see how i can "slide" the access token if no browser involved. Possible?
