### ISSUE TITLE
Identity Server with Entity Framework Very Slow: ClientLogoURI Gotcha

### ISSUE THREAD

**Issue by iAlexanderMoon** [IdentityServer/IdentityServer3#2351]
In the samples a base64 encoded logo is used for the clients.

IdentityServer3.Samples/source/EntityFramework/SelfHost/Config/Clients.cs
               
    ClientUri = "https://identityserver.io",
    LogoUri = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUg...
                    
This results in VERY SLOW performance (Requests to serve the login page taking an average of 5 s instead of 5 ms) when using the Entity Framework Config back end.

In troubleshooting the performance botteneck I found that IdentityServer3.EntityFramework.FindClientByIdAsync is called multiple (3x) times to serve the login page which also seems strange...  I didn't dig any deeper (maybe it's necessary)... however this compounds the issue of dragging the base64 encoded image out of the database when loading the client info.

The solution is simple enough: use an actual URI instead of an embedded image or don't use one.

A warning in the documentation (Documentation/docsv2/ef/clients_scopes.html) and in the EF samples would be helpful.

**Comment by brockallen** [comment]
Yes, the client logo as a data uri. It's a sample. We don't necessarily expect people to use this approach for their own scenarios. 

Also, we do have caching support for the client and scope stores given that these are used frequently.

**Comment by elryry** [comment]
Hi @brockallen, sorry if this is a stupid question but could you point me to where there's more details on the caching support for client and scope stores as mentioned above?
