### ISSUE TITLE
User logged in notification with JavaScript implict client 

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3#2353]
Happy new year all

We have a requirement where when a user is authenticated with OP via other openid clients , our JavaScript implicit clients needs to be able to aware the user has already logged in so that when user navigates to it , it can sign user in automatically without need of clicking login button again, 

What we done to achieve this is using something similar to session change notification, we create a new endpoint in our OP to render checklogin.html which contains a iframe - if idsvr.session cookie is present in browser than it posts message to RP the user is already authenticated. Can you see any issue with this approach? Or is there a better way to achieve this?

Thanks

**Comment by brockallen** [comment]
If you want to detect if the user is already logged into the OP, then make a normal authorization request with prompt=none. Check the spec for more details.

**Comment by jeremy001181** [comment]
Thanks

One concern of this approach is performance. Because the user can be returned to any pages of the JavaScript implicit client site which means we need to make a call to authorize endpoint on page load of every pages, the site is high volume traffic and we are worry about the performance.

By having a checklogin.htm static page from OP doesn't have this issue as the page content can be cached on cdn level.

We haven't done any solid performance test as it is just at design stage, do you think if this is over think? Has anyone had similar requirement and does this have performance issue?

**Comment by brockallen** [comment]
Well, I'm just letting you know how the spec was designed to allow what you're asking for. Test it and let us know how it works out.

**Comment by jeremy001181** [comment]
Thank you we will try out this

**Comment by leastprivilege** [comment]
still an issue? feel free to re-open.
