### ISSUE TITLE
SecretValidationResult.Success / ValidationReresult.Error and .IsError

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2354]
Does setting the SecretValidationResult.Error automatically set the success to false and the isError to true?  

What about the pair of isError and Success - are they automatically dependent on each other or do I have to set them manually?  

From the code, out of the box it seems there is no connection between the two. Shouldn't there be?  
Out of the box the IsError is set to true during construction but that's it. 

IMHO 

  1. Getting Success should return !IsError and 
  2. Setting Success should set the opposite on IsError and clear the error string.  
  3. Setting IsError to false should clear the error string
  4. Setting Error string should return IsError true. 
  5. Deleting the error string (if it was not empty till now) should set IsError false
  5.

**Comment by leastprivilege** [comment]
Can't remember. Send a PR.
