### ISSUE TITLE
How to use caching for token at Identity server side?

### ISSUE THREAD

**Issue by pagidigovardhan** [IdentityServer/IdentityServer3#2358]
Hi Brockallen

As you stated :
If we use OWIN Cookie based authentication no caching is required.

My  Requirement:
My requirement is to use Redis cache at identityserver for tokens..

Is runtime caching(IdSrv3 uses) enough to serve high concurrency???

Correct me if I am not heading to right direction.. :)

**Comment by leastprivilege** [comment]
Which tokens do you want to cache?

**Comment by pagidigovardhan** [comment]
The one IdentityServer issues to the client application(MVC client)

**Comment by leastprivilege** [comment]
no. the id_token gets validated only once - and that happens locally in the client app.

**Comment by pagidigovardhan** [comment]
So did you mean..Once the id_token is issued by IdSrv, it is up to the client application how it maintains???
As you said:
the id_token gets validated only once..
 Against what this validation will be done???

**Comment by leastprivilege** [comment]
that's for reference access tokens.

**Comment by leastprivilege** [comment]
Also check the OpenID Connect spec to see how id_tokens are validated.

**Comment by pagidigovardhan** [comment]
I read the Open ID Connect spec here 
https://openid.net/specs/openid-connect-basic-1_0.html#IDTokenValidation

What I understood is..It is client app responsibility whether the token is valid issued by IdSrv
and keep(cache/persist) it with Client application level...Issuing token is the only job IdSrv will do.

If my understanding is correct.. id_token validation has to be done here???
//MVC controller
private async Task<TokenResponse> GetTokenAsync()
        {
            var client = new TokenClient(
                "https://localhost:44306/identity/connect/token",
                "mvc_service",
                "secret");
            var tokenResponse = await client.RequestResourceOwnerPasswordAsync("govardhan",     "1234", "roles");
            // ** Do id_token validation here ** 
            return tokenResponse;
        }

**Comment by leastprivilege** [comment]
resource owner flow does not issue id_tokens. Only access tokens. They are validated at the consumer side (API).

**Comment by pagidigovardhan** [comment]
How implicit flow Id_token validation will be done?
 I didn't understand when and where one time id_token validation will be done...


Will Access_token validated on every request when we consume API?
//WEB API
public void Configuration(IAppBuilder app)
        {
           
            // token validation
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44306/identity",
                RequiredScopes = new[] { "sampleApi" }
            });
}

**Comment by leastprivilege** [comment]
id_tokens are validated on the client (using some client library)
access tokens are validated at the API (using middleware - e.g. the one you show above)

**Comment by pagidigovardhan** [comment]
Thanks for your quick response...

Coming to my initial question about Caching the token 
let me tell you about my understanding after your help.

1) Token issued by IdSrv is no need of caching as its responsibility is only issuing token

2) Validating id_token is client app responsibility. Here we can use any caching mechanism to keep the token available in distributed environment.

3) Validating access_token will be done through authority endpoint 
(as shown above  
Authority = "https://localhost:44306/identity", IdSrv endpoint for access token validation)

**Comment by leastprivilege** [comment]
1) mostly
2) the id_token is only needed for validation, after that you could "forget" it. The client app is then responsible for signing the user in - eg. using a cookie
3) depends on the token type. JWTs are validated locally at the API endpoint, reference tokens are validated at idsrv.

**Comment by pagidigovardhan** [comment]
Thank you
It helps me a lot..
