### ISSUE TITLE
Configure IdentityServer as IdP in AzureAd

### ISSUE THREAD

**Issue by federicobarera** [IdentityServer/IdentityServer3#2359]
I've managed to successfully use Identity Server 3 as an external IdP in ACS (configuring the Ws-Federated Plugin).
I could not find any documentation on configuring AzureAD to federate to Identity Server (or any WS-Fed / OpenID Connect capable identity provider), with the exception of directory sync with on premise AD and ADFS.

I know that it's not exactly your responsibility to provide this type of documentation, but would be nice to know if this type of connection is possible at first, and any hints how to set it up.

Thanks,

Federico

**Comment by leastprivilege** [comment]
Azure AD does not support external IdPs.
