### ISSUE TITLE
How to access raw SignInMessage in custom login view?

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2361]
This should be a simple one..

I've overriden the default AngularJS login template by providing a `_login.html` file in the `templates` directory. Works great.

Now - how can i access the raw `SignInMessage` that's part of the URL? (e.g `https://localhost:44333/core/login?signin=<iwantthisvalue>`.

It's not in the `{{model}}` in the view that gets generated.

Do i need to:

1. Use a custom view service to set the custom value? I know you can override the `Login` method in the custom view service, but that has access to the `SignInMessage` object - i need the raw value - which i'm not sure how to retrieve.
2. Use an OWIN extension to get the query string value in the custom view service and set the custom model value?
3. Something else?

Why am i doing this? I don't want to iterate through `{{model.additionalLinks}}` to generate a link to my register page - i want to build it manually, but i need the raw `signin` value to add to the href i generate so the login flow is preserved.

Thanks!

**Comment by brockallen** [comment]
You just want the signin message id?

**Comment by RPM1984** [comment]
@brockallen correct. I want to build a link with the signin url param manually

**Comment by brockallen** [comment]
Why not just read the query string in the JS?

**Comment by RPM1984** [comment]
@brockallen yep, that's basically what i was alluding to in 2). I just thought there was a way to access it  server-side and set the value in the model. No probs, i'll pull it from the QS. Thanks.

**Comment by brockallen** [comment]
Well, server side it's also in the query string :) I guess I'm missing something...

**Comment by RPM1984** [comment]
@brockallen you're not missing anything :) i just thought there was be a way to access it properly using some built-in IdSrv API/extension, rather than doing it at the hosting layer.
