### ISSUE TITLE
IDX10803: Unable to create to obtain configuration from: 'https://localhost:21001/.well-known/openid-configuration'

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2362]
Hi,

Recently I wanted to test my working solution on some VM. 

I did create Root CA cert and service cert, installed those certificates, and bind to appropriate ports.
But the same solution seems not working for some reason.

From the browser I can access ''https://localhost:21001/.well-known/openid-configuration' (cert info says this certificate is ok, here I see Root CA, times are ok..), 

But when the service that uses token validation tries to access the server, it fails with above error. 

What could be the problem?

**Comment by brockallen** [comment]
Did you manage the private key such that the worker process identity has read access? That's a common misconfiguration issue.

**Comment by iLearnIdentityServer** [comment]
Well yes. I did install service cert (pfx) under Local Computer  personal certificates, I do have private key, and if I check private key permission I do have full access. I'm using some Admin  account.

All processes of my system can run like console (for dev purposes, debuging) or win service (for prod, in the future ), when running as console they run under current user account which is Admin account.

Anyway, as I mentioned it works from the browser.

**Comment by brockallen** [comment]
> Anyway, as I mentioned it works from the browser.

Does this mean you're using the same cert for SSL and for signing tokens? This is a bad idea -- you should use two different certs for those two different purposes.

As for the error -- perhaps enable logging  so we can see the actual exception information/details. If it says "private key not found" or somesuch, then it's a permissions issue.

**Comment by iLearnIdentityServer** [comment]
No no. 
I have separate certificate for signing tokens, this is embedded certificate.

I have Root CA cert and one Service cert used for TLS for all services. In future I will have one service cert per service.

I did enable logging, nothing bad is in log.
The only WARN that i get is - ConsentStore not configured - falling back to InMemory, because I do not have custom Consert Store at the moment.

**Comment by brockallen** [comment]
> I have separate certificate for signing tokens, this is embedded certificate.

Ok, sorry then. The comment about it working in the browser threw me -- i thought you meant SSL.

The consent store warning is unrelated, so that's fine.

Ohhh, I just re-read the issue and I think I now -- what it means is that the Web API is trying to load the metadata over SSL and it seems the SSL cert is not trusted.

**Comment by iLearnIdentityServer** [comment]
Yes I have Web API trying to load the metadata over SSL :-), that is correct.

But SSL cert is trusted for sure, I installed related Root CA cert in Trusted Root CA.

**Comment by brockallen** [comment]
But the host name being used is still "localhost" -- unless that's the host you used in the SSL cert?

**Comment by iLearnIdentityServer** [comment]
That is also correct :-)

What I see right now is that "The connection uses TLS 1.1" on this VM, but on my physical is TLS 1.2.

I'm not sure if this can be the problem.

**Comment by brockallen** [comment]
Don't know -- perhaps a way to diagnose is to manually make a HttpClient call to the metadata endpoint from an ASP.NET app so you can see the error first hand (rather than the MW hiding it).

**Comment by iLearnIdentityServer** [comment]
Do you might know why communication goes through TLS 1.1 instead through TLS 1.2?

**Comment by brockallen** [comment]
No, sorry.

**Comment by leastprivilege** [comment]
still an issue? feel free to re-open.

**Comment by ad0ran** [comment]
Hello, I'm receiving this same exception.
The project I created is just a sandbox, so I'm using it to play around with IdentityServer3. I installed the access token validation extension into the same assembly as my identity server and configured the piping like this: 

```
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string> ( );

            var factory = new IdentityServerServiceFactory
            {
                UserService = new Registration<IUserService, UserService> ( )
            };

            factory.UseInMemoryScopes (Scopes.Get ( )).UseInMemoryClients (Clients.Get ( ));
            factory.Register (new Registration<Business.Core.IUserService> (Container.Instance.Get<Business.Core.IUserService> ( )));
            factory.Register (new Registration<IUserPasswordService> (Container.Instance.Get<IUserPasswordService> ( )));
            factory.CorsPolicyService = new Registration<ICorsPolicyService> (new DefaultCorsPolicyService { AllowAll = true });

            factory.ViewService = new Registration<IViewService, DefaultViewService> ( );

            var options = new IdentityServerOptions
            {
                SiteName = "MY SITE",
                Factory = factory,
                EnableWelcomePage = true,
                RequireSsl = false
            };

            app.UseIdentityServer (options);
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "http://localhost:60518/api",
                RequiredScopes = new List<string>
                {
                    "fintracker"
                }
            });
```

So basically, I'm attempting to host my authorization and authentication in the same web api project, but I keep receiving that error.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by ad0ran** [comment]
I've moved my issue here: http://stackoverflow.com/a/37973711/1366228

**Comment by Farshidgolkarihagh** [comment]
Hi, I had this issue for over a week and this is how I resolved it: 

The problem I had was the fact that I was using the "IIS Express Development Certificate" and for some odd reason it wasn't a trusted certificate on my dev machine hence it was only broken on this particular environment. To fix it, export the IIS Express Development Certificate and import it back in to the "Trusted Root Certification Authorities"->"Certificate".
