### ISSUE TITLE
CORS policy service is never called

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2365]
I created CORS Policy Service, registered the service like all other service and stores (which) are working.

But this service is never called when making token requests from different clients.
Well this is very strange, since this was working 10 days ago, I remember that I had to add Allowed CORS origins to clients through some "portal" that I made, so the clients can get the tokens.

The clients just get their tokens...

**Comment by brockallen** [comment]
It's only called for certain endpoints: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Constants.cs#L665

**Comment by iLearnIdentityServer** [comment]
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Constants.cs#L667-L672

Yes for token endpoint. 
But in my case it is not called. The token is just returned.

What can be the reason?

**Comment by brockallen** [comment]
No `Origin` is sent in the request header?

**Comment by iLearnIdentityServer** [comment]
Found it. Dependency injection problem. My custom ICorsPolicyService had implementation instead of interface as dependency in constructor. Now sure how I change this accidentally and made mistake.

Was working before, than I somehow delete "I"
