### ISSUE TITLE
How to get partial login user sub or custom claims?

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#2366]
Hello,

I'm using partial login to redirect user if his password has expired. My endpoint for changing password is in the same application as identityServer. The only way to get ClaimsPrincipal is to call GetIdentityFromPartialSignIn() from Owin Extensions? Or am I doing something wrong and I should already have ClaimsPrincipal in HttpContext.User.Identity?

I just found out that the same happens (no  HttpContext.User.Identity has to call GetIdentityServerFullLoginAsync ) if user is accessing another custom endpoint in my identityServer host and he is already fully logged.

**Comment by brockallen** [comment]
Yes, our helper API gives you the identity from the partial login cookie (which is a diff cookie than the main authentication cookie, and this is why we provide a helper for it).

**Comment by brockallen** [comment]
If you really want the User to be populated, then there are some helpers here you might find interesting: https://github.com/IdentityServer/IdentityServer3.Extensions.Mvc

**Comment by pawepaw** [comment]
Thanks!

So user should not be populated even after full login? Because even if user is fully logged and navigate to some custom endpoint in identityServer host HttpContext.User.Identity is empty.
