### ISSUE TITLE
Extra Fragment identifier causes error in AuthorizeRequest

### ISSUE THREAD

**Issue by yvdh** [IdentityServer/IdentityServer3#2367]
Hi,
great work!
Working from from the samples I am using the WPF LoginView to Authenticate with a Google Account in an implicit flow. However, the google return post to the redirect Url contains an extra # as the last character inside that view (NOT in fiddler). This needs to be removed before creating an AuthorizeResponse, like so or  an exception gets thrown in its constructor :

  private void webView_Navigating(object sender, NavigatingCancelEventArgs e)
    {
      if (e.Uri.ToString().StartsWith(_callbackUri.AbsoluteUri))
      {
        Console.WriteLine("Obtained callback from authentication provider");
        Console.WriteLine(e.Uri.ToString());
        if (e.Uri.AbsoluteUri.Contains("#"))
        {
          // We need to strip out the trailing #?????
          AuthorizeResponse codeResponse = new AuthorizeResponse(e.Uri.AbsoluteUri.Replace("#", ""));
          this.AuthorizeResponse = codeResponse;
        }
}   
}

Bug or am I missing something?

**Comment by mderriey** [comment]
This confirms what I said in your other question. Your Google application should not return to your client application but to IdSrv.
