### ISSUE TITLE
How to perform token validation but only for certain path

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2368]
Is there a way to perform token validation but only for certain path (specific Web API method)? Or I need to write OWIN middleware for this?

UseIdentityServerBearerTokenAuthentication and IdentityServerBearerTokenAuthenticationOptions seems do not support this.

**Comment by iLearnIdentityServer** [comment]
No help for me? :'-) 
Than. I go to write OWIN middleware :-) for this.

**Comment by leastprivilege** [comment]
use the Map primitive in OWIN.

**Comment by iLearnIdentityServer** [comment]
That was my initial idea. But I was hoping that I can use IdentityServerBearerTokenAuthenticationOptions .

Let me say the background why I need this. 
I need subset of dynamic client registration from OAuth/OpenID Connect spec.
So I added one WebAPI endpoint in the same process where I run Identity Server and I want to protect this endpoint with OAuth. (I create registration tokens that I distribute to clients that will use dynamic client registration). 

So I want to do token validation, and I wanted to use UseIdentityServerBearerTokenAuthentication/IdentityServerBearerTokenAuthenticationOptions 

or something similar that is available.

But, since it is not available, I need to write middleware that will validate that token, checking both if token signature is valid and if token has already been used for registration. 

Give me couple of hours to see if this is the right way. 
I hope I will close the issue very soon.

**Comment by iLearnIdentityServer** [comment]
Thanks Dominick! 
I will be back soon.

**Comment by iLearnIdentityServer** [comment]
I have some dificulties making this to work. I tried the following

			app.Map("/connect/registerClient", x =>
			{
				HttpConfiguration config = new HttpConfiguration();
				ContainerBuilder containerBuilder = new ContainerBuilder();

				containerBuilder.RegisterType<Repository>().As<IRepository>().InstancePerRequest();
				containerBuilder.RegisterType<RegistrationTokenValidator>();
				containerBuilder.RegisterType<DynamicClientRegistrationManager>().As<IDynamicClientRegistrationManager>().InstancePerRequest();
				containerBuilder.RegisterApiControllers(Assembly.GetExecutingAssembly());

				var middlewareContainer = containerBuilder.Build();
				var resolver = new AutofacWebApiDependencyResolver(middlewareContainer);

				config.DependencyResolver = resolver;

				WebApiConfig.Register(config);

				x.UseAutofacMiddleware(middlewareContainer);
				x.UseWebApi(config);

			});

Here only OWIN middleware is called buy not API controller.

So, if i move Web api registration out of "map" and put in front of map its working, but not the middleware. 

I might be a little tired, since its almost midnight, but I'm not go to sleep until i figure this out or I passed out :-)

Any ideas what I'm doing wrong here?

**Comment by mderriey** [comment]
I don't know exactly what's going on, but you are aware that tour Web API actions would be reachable at /connect/registerClient/{controller}/{action}?
I have the feeling that `/connect/registerClient` is the URL you hit to register a client if all the config is taken out of the `Map` call.

Am I making a wrong assumption here?

**Comment by iLearnIdentityServer** [comment]
You are so right :-)
