### ISSUE TITLE
Can only get access code from external identity provider, not access token

### ISSUE THREAD

**Issue by yvdh** [IdentityServer/IdentityServer3#2369]
Hi,

I have the following use case for a pay-per-use type of client application.
- Identity server 3 with external google provider. Implicit flow (or hybrid?)
- Rest API server with Authorize on each web method
- Client apps (windows and/or mobile)
I want users to login with google credentials, and be able to pay for certain method calls. I have google credentials set up. 
All API calls work with client credentials, but that's not what I want obviously (unsecure, pay-per-use impossible). I want (I think) implicit or hybrid flow with API calls in name of the user, so I can also handle the pay-per-use using google api access in my own API method bodies.

When enabling this implicit flow I try to obtain an access token by a request into the connect/authorize endpoint using the LoginView WPF, as in the samples. 

public class Startup
  {
    public static string Url = RestCalibratorService.Startup.IdentityAuthority;
    public void Configuration(IAppBuilder app)
    {
      var options = new IdentityServerOptions
      {
        RequireSsl = false,
        Factory = new IdentityServerServiceFactory()
                      .UseInMemoryClients(Clients.Get())
                      .UseInMemoryScopes(Scopes.Get())
                      .UseInMemoryUsers(new List<InMemoryUser>()),
        AuthenticationOptions =   new AuthenticationOptions
        {
          EnablePostSignOutAutoRedirect = true,
          IdentityProviders = ConfigureIdentityProviders
        }
      };
      app.UseIdentityServer(options);
    }
    private void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
    {
      app.UseGoogleAuthentication(new GoogleOAuth2AuthenticationOptions
      {
        AuthenticationType = "Google",
        Caption = "Sign-in with Google",
        SignInAsAuthenticationType = signInAsType,
        ClientId = Google.ClientID,
        ClientSecret = Google.ClientSecret
      });
    }
  }
Except for a small problem with an extraneous fragment identifier (posted a remark for this)  I am correctly redirected to the google login page, and then again to my local redirect url after login and consent. However, this response only contains an access code, not a token. This is as described in the  Google documentation.

It is quite easy to call the token endpoint at google from the client, but that exposes the google client secret. Anyway, this works, but this token is not valid for calling my own API (although that was included in the requested scopes!). 
Ideally this would be handled on the Identity server itself, thereby keeping all the secrets safe and simplifying the client. (Sorry, but I mix VB and C# in my projects).
I feel like I am missing something fundamental. Is this at all possible?

 Private Function GetUserAccessToken(scope As String, responseType As String) As TokenResponse
    Dim authorize As AuthorizeResponse = GetUserAuthorizeResponse(scope, responseType)

    'Now get an access token using the access code
    Dim values As New Dictionary(Of String, String)
    values.Add("code", authorize.Code)
    values.Add("redirect_uri", CIPF.IdentityService.Google.RedirectUrl)
    values.Add("client_id", CIPF.IdentityService.Google.ClientID)
    values.Add("client_secret", CIPF.IdentityService.Google.ClientSecret)
    values.Add("grant_type", "authorization_code")
    Dim content As New FormUrlEncodedContent(values)
    Dim client As New HttpClient()
    'Console.WriteLine("Requesting access token using " & client.BaseAddress.ToString)
    Dim response As HttpResponseMessage = client.PostAsync(CIPF.IdentityService.Google.AccessTokenEndPoint, content).Result

    If response.IsSuccessStatusCode Then
      Return New TokenResponse(response.Content.ReadAsStringAsync().Result)
    Else
      Return Nothing
    End If
End  Function

 Private Function GetUserAuthorizeResponse(scope As String, responseType As String) As AuthorizeResponse
    'Create the authorize request and extract URl from it.
    Dim request As New AuthorizeRequest(CIPF.IdentityService.Startup.Url & "connect/authorize")
    Dim requestUri As New Uri(request.CreateAuthorizeUrl(CIPF.RestCalibratorService.Startup.ImplicitClientID,
                                                        responseType,
                                                        scope,
                                                        CIPF.IdentityService.Google.RedirectUrl,
                                                        "random_state", "random_nonce", "alice", "idp:Google b c"))
    'idp preselects the identity provider and avoids extra screens for the user to login!

    'Show web view with URL, and get result from identity provider
    Dim loginView As New CIPF.RestCalibratorClient.LoginWebView
    loginView.ShowDialog(requestUri, New Uri(CIPF.IdentityService.Google.RedirectUrl))
    Console.WriteLine("Access Code:" & loginView.AuthorizeResponse.Code)
    Return loginView.AuthorizeResponse
  End Function

**Comment by mderriey** [comment]
You shouldn't have to call Google token endpoint yourself, as this is the responsibility of the Google OWIN middleware, as you can see [here](http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationHandler.cs).

Are you sure the authorization code you get back is from Google?
Also, whar redirect URL did you specify in your Google application? It has a URL pointing to IdSrv, not to your final client application.
This way, the Google OWIN middleware will exchange the authorization code for an access token which will be turned into a `ClaimsIdentity` which will flow through IdSrv. The authentication will be considered successful and an access token from IdSrv will be sent to your client application since you use the implicit flow.

**Comment by yvdh** [comment]
Hi,
thanks for the quick response, it has pointed me in the right direction.

Not having to call the token endpoint of google myself was what I thought initially, I just implemented it client-side to check the principle.

My redirect is to the IDserver default path (base path + /signin-google). It is confusing that this is called callbackpath on the google2authenticationoptions. 

In my service unit tests I use a WPF webview similar to the one in the samples to do a service authenticated ping-pong test. Looking at the code this intercepts the callback and creates an AuthorizeResponse from it that is returned. What you are saying is  that the redirect happens TWICE (by the identity provider to the IDServer that adds the necessary claims and access token  and then reposts it) and that I was actually intercepting the wrong post (i.e. the first one instead of the second one) to create my client-side authorizeresponse.

I will check this and come back to this thread to confirm. 
Yves

If the google provider will call back to the IDserver

However, if this works I am

**Comment by yvdh** [comment]
Hi again,

I got everything working thanks to your tips. The crucial point seems to be that the first google callback URI also contains a fragment identifier at the end, causing the Webview as it was then written to break the normal IDserver flow. This normal flow includes showing an extra consent screen for accessing my own API (not the ones I want to access for the google User).

I modified the webview  navigating event handler (taken from the samples) as follows:

 ```
private void webView_Navigating(object sender, NavigatingCancelEventArgs e)
    {
      if (e.Uri.ToString().StartsWith(_callbackUri.AbsoluteUri))
      {
        Console.WriteLine("Obtained callback from authentication provider");
        Console.WriteLine(e.Uri.ToString());

        // Check for fragment after redirect url, that's the final callback.
        if (e.Uri.ToString().StartsWith(_callbackUri.AbsoluteUri + "#"))
        {
          // Second callback, from IDserver with fragment
          AuthorizeResponse codeResponse = new AuthorizeResponse(e.Uri.AbsoluteUri);
          this.AuthorizeResponse = codeResponse;
          e.Cancel = true;
          this.Visibility = Visibility.Hidden;

          if (Done != null)
          {
            Done.Invoke(this, AuthorizeResponse);
          }
        }
      }
      else
        Console.WriteLine("Navigating to " + e.Uri.ToString());
    }
 ```
Thnx!!
