### ISSUE TITLE
[Question] Licensing for IdentityServer 3

### ISSUE THREAD

**Issue by aseemflowingly** [IdentityServer/IdentityServer3#2370]
I maybe blind, but I can't seem to find the licensing restrictions for IdentityServer3 if I have to use it in an enterprise application.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3/blob/master/LICENSE

— 
cheers
Dominick Baier


On 5 January 2016 at 19:57:02, Aseem Chiplonkar (notifications@github.com) wrote:

I maybe blind, but I can't seem to find the licensing restrictions for IdentityServer3 if I have to use it in an enterprise application.
