### ISSUE TITLE
Logging in to a file using diagnosticstrace in Azure

### ISSUE THREAD

**Issue by lpranith** [IdentityServer/IdentityServer3#2371]
I was able to successfully write logs in to a file when i run the sever and client locally(using IIS) and the file is found under the path"C:\Program Files (x86)\IIS Express" .When i run both the server and client in Azure then I  could see trace messages under the storage table when i use debug message like " System.Diagnostics.Trace.TraceInformation("i am in configuration method");" but when i write in to file i cannot see that file after i remote in to the cloud machine?. Any suggestion for this?..Any other way of logging in to file?

**Comment by brockallen** [comment]
I'd suggest checking the Azure docs for this.
