### ISSUE TITLE
How can i get access to the external providers (Google, Facebook, etc) in my custom register page?

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2372]
I'm using the [MvcViewService sample](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MVC%20ViewService/MvcViewServiceSample) as the base for my IdSrv.

Notice how the custom [Login](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20ViewService/MvcViewServiceSample/Views/LogonWorkflow/Login.cshtml#L65) view has access to the `ExternalProviders` in the `LoginViewModel` (as the [custom view service](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20ViewService/MvcViewServiceSample/Services/MvcViewService.cs#L106) has passed it through).

Now, if i have a custom Register page (served by MVC) in the same IdSrv host - is there any way i can access these same properties? (e.g the `IEnumerable<LoginPageLink>` for the third party providers i've configured).

I basically want to have an MVC *partial view* with these links to be used on my login _and_ register page.

I know under the hoods IdSrv is using the MS OWIN MW, but i need to build the links the same way the login page does (e.g with the `signin` param, scopes defined by the msg etc).

I also know i could just build the link manually, e.g:

`/core/external?provider=Google&signin=c707f8a59909c6601b2b884a4ac6257d`, but then my view is hardcoded for the providers, instead of using whats plugged into the MW. So just seeing if there's a convenience IdSrv method to get the external providers.

Thanks!

**Comment by RPM1984** [comment]
@brockallen or @leastprivilege any thoughts?

**Comment by brockallen** [comment]
Something like this: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/InternalOwinExtensions.cs#L81?

**Comment by RPM1984** [comment]
@brockallen that just gives you name/type.. i was looking for the actual `LoginPageLink` that is generated by IdSrv, after passing in the providers from the MW.

E.g: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/ViewModels/LoginViewModel.cs#L74

The login page populates that and sets the `href` (e.g `/core/external?provider=Google). That's generated by IdSrv -> that's what i'm after.
