### ISSUE TITLE
Question: How do I use the same token throughout a client call to Api1, where Api1 also calls Api2?

### ISSUE THREAD

**Issue by PJPollard** [IdentityServer/IdentityServer3#2374]
I recently converted a project from IdSvr2 to IdSvr3 - both brilliant products. thanks! I have a question and I've not found a satisfactory answer from my searches... 

I have a windows client using an access token from IdSvr3 using client credentials flow; That token is passed in a request to Api1, which validates the token, and the request (to Method1) is authorized. So far so good.
Method1 in Api1 needs to call a subsequent Api2, which has exactly the same authentication configuration options as Api1 (to the point that if I called it directly from the client instead of Api1, it would work).
I'm trying to figure out the best way to call Api2 from Api1 using the token sent to Api1 - I don't want to have Api1 request its own token if I can help it.
If I manually retrieve the Bearer token from the Authorization header (from the original call) and pass this in the Authorization header to the request in API2, I guess this would work, but... is there another preferred option? Or am I missing something very obvious?

**Comment by mderriey** [comment]
If you don't want to request another token from Api1, I don't see another option but to get the token from the request headers.

**Comment by brockallen** [comment]
Either API 1 can get its own token for API 2 (via client credentials), or API 1 can use the access token for API 1 and exchange it for an access token for API 2 (via custom grant). The first approach is more of a trusted subsystem style, where the latter is more of a delegation scenario. Or do what @mderriey said, which is also called "poor man's delegation" (search for Vittorio's article on the matter for more info), but the downside is that clients who have a token fro API 1 can also call directly to API 2.

**Comment by PJPollard** [comment]
Thank you @mderriey @brockallen, most helpful!
