### ISSUE TITLE
[Question] Registering users using Aspnet Identity

### ISSUE THREAD

**Issue by aseemflowingly** [IdentityServer/IdentityServer3#2375]
The scenario is user signs up with their email/password etc. in Web App1, which passes this to the IdentityServer 3 which will register the user and generate a token for email verification or sms verification to verify the registered account.

Seems like I will have to write an implementation of IUserService. I tried to write one by inheriting from        
    
    public class UserService : AspNetIdentityUserService<CustomUser, string>

But I don't seem to see anything similar to use as you would normally get with ASp.net MVC app with individual accounts:

     var user = new ApplicationUser { UserName = model.UserName, Email = model.Email };
     var result = await UserManager.CreateAsync(user, model.Password);

or
   
    var result = await UserManager.ConfirmEmailAsync(userId, code);

Is there a sample which can explain registering the AspnetIdentity as a Identity Provider as well as using it for registering users.

**Comment by mderriey** [comment]
Registration is not the responsibility of IdSrv.
There should be no such things as a web app passing username/password to IdSrv for the registration.

What you can do is override the login page to include a register button which will navigate to a custom registration page.

Check the samples and the existing issues - even the closed ones, this has been covered already.
Cheers

**Comment by aseemflowingly** [comment]
Thanks for your reply. I have spent almost 2 hours looking through the issues before I ask this one to ensure that I am not duplicating issues. 

I have gone through this tutorial which explains how to use Aspnet Identity with IdentityServer3, but this does not explain custom registration either.
https://www.scottbrady91.com/Identity-Server/Identity-Server-3-using-ASPNET-Identity

I have looked at "AspNetIdentity" and "AspNetIdentity_2fa" samples, but these have no information regarding how to generate a email / sms verification code and validate them to complete the registration process.

I understand that Identity Server does not register users. 
But what I am asking is, if we ask Identity server to use Aspnet Identity, which does register a user, how do we access it via identity server given that it has been hosted as an MVC app.

I tried creating a UserController in the Identity Server similar to this:

    public class UserController : Controller
    {
        [Route("core/user/register")]
        [HttpPost]
        public ActionResult Register(string userId, string password, List<Claim> Claims)
        {
        }
    }
   
And then have Web App 1 call this to register a user via the UserService which inherits the AspNetIdentityUserService<CustomUser, string>

but I can't get any further since AspNetIdentityUserService has no way of registering users.

**Comment by brockallen** [comment]
User provisioning is always different in every app. If you want users to self-provision, then you need some app to do this that has write access to the same DB you're using for IdSvr. Other apps an admin will do the provisioning, and it's really the same thing -- where ever that admin app runs, it needs write access to the same DB that IdSvr uses.

Does that help?

**Comment by aseemflowingly** [comment]
Yes, it does! 

So I am pointing Identity server to SQL SERVER db using custom Application DB context and store. Registering that store and db context when registering user  service and identity management service. 
A separate web app uses asp.net identity to register users in the same database. 

However,  when I try to get an access token for a registered user,  it throws internal server error response.

**Comment by eclipsed82** [comment]
Did this get figured out yet? I'm trying to accomplish the same and can't seem to find anything on this, although it's mentioned above that this "has been covered".
