### ISSUE TITLE
Password encryption/decryption and Claims token request flow

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2376]
The user/password store of our business is separate from the Identity server store.If this assumption is right then password encryption/decryption and checks will be based on our own logic. Then the password is converted to a claims token allowing access to our Rest API. How does the password check using our data store integrate with Identity Server ? 

I am looking for a sample or some article that explains these.
1. User/password store of the business is separate. Password decryption is handled by business and then token is obtained from the identify provider.
2. If Point 1 is  wrong then I would like to look at alternatives.Does the identity provider access the user/password details of the business ? How ?

I have IdentityServer3 sample solutions. Just need a few suggestions. Moreover the business code as well as the Provider are both on Azure. Does this introduce anything new ?

**Comment by leastprivilege** [comment]
Check the docs - you need to implement IUserService.
