### ISSUE TITLE
Question: Identityserver3 and Inappbrowser in Ionic/cordova-app.

### ISSUE THREAD

**Issue by Daforest** [IdentityServer/IdentityServer3#2377]
Hi!

We are using IdentityServer3 (build 2.2.0.0) for authentication in several applications (mostly mvc). 
We've just begun development of a ionic/cordova app , and wants Identityserver to take care of login with implicit flow. 

By using cordova inappbrowser we are able to go to the authorize endpoint and login (connect/authorize). We are then redirected back (localhost/callback) and are able to get tokens from the url. 

pseudo url: connect/authorize?
client_id=xx
&redirect_uri=xx
&response_type=id_token token
&scope=openid
&state=xx
&nonce=xx

The application then uses Bearer-auth to get data from an API. Success so far!

(access) Token lifetime is now set to approximately 24 hours, and the application listens to its 'expire_in'-attribute. And after 23 hours, the user is redirected to the Authorize-endpoint for token-refresh.

The problem is, everytime the user is redirected to the endpoint, he/she is prompted to re-login. 
It lookes like the inappbrowser gets all the necessary cookies during login, and brings them along the second time. But the user is still prompted to login. 

Trace.log:

[Information] User is not authenticated. Redirecting to login.
[Information] End authorize request
[Information] Redirecting to login page

Hope there is someone here, who maybe have tried to implement something similar?

**Comment by leastprivilege** [comment]
Maybe the cookie is expired - have you set the cookie lifetime on our options?

**Comment by Daforest** [comment]
well, this happens whether 5minutes have passed, or 23 hours. So I doupt it.

**Comment by leastprivilege** [comment]
Then our authentication cookie is not sent.

**Comment by Daforest** [comment]
Inappbrowser keeps these cookies:  (login -> 1min --> login)

<img width="912" alt="screen shot 2016-01-07 at 10 48 39" src="https://cloud.githubusercontent.com/assets/2014746/12167477/9f0b664e-b52c-11e5-91f8-357cc29e442f.png">

**Comment by leastprivilege** [comment]
Sorry - then I don't know what's going on.

**Comment by Daforest** [comment]
It works flawlessly with all our other applications, so this one is kinda frustrating. Is implicit the only "accepted" flow for mobile applications, or could we consider using resource-owner?

**Comment by leastprivilege** [comment]
It's not recommended. But maybe you are giving up too early. 

try enabling HTTP and Katana logging as well - if the cookie is being sent (and arrives at idsrv) - it is really a mystery what would go wrong then.

**Comment by Daforest** [comment]
I tried navigating to the authorize-endpoint in a mobile-browser (safari):
After having logged on once, it just works. Don't quite understand why this is not the case in inappbrowser.

trace.log: 

[Information] Creating Implicit Flow response.
[Debug] Creating access token
[Debug] Creating reference access token
[Information] {
  "Category": "TokenService",
  "Name": "Access token issued",
  "EventType": "Information",
  "Id": 2000,
  "Details": {
    "TokenType": "Reference",
    "ReferenceTokenHandle": "bb711d9f69c02652cff988dd95467dab",
    "SubjectId": "XX",
    "ClientId": "XX",
    "Scopes": [
      "openid",
    ],
    "Lifetime": 86400,
    "Claims": {
      "client_id": "XX",
      "scope": [
        "openid",
      ],
      "sub": "XX",
      "auth_time": 1452151096,
      "idp": "idsrv",
      "amr": "password"
    }
  },
  "Context": {
    "ActivityId": "7006d81b-3d56-4bd4-9abd-2a6a15d2241b",
    "TimeStamp": "2016-01-07T12:09:58.3921313+00:00",
    "ProcessId": 6352,
    "MachineName": "XX",
    "RemoteIpAddress": "XX",
    "SubjectId": "XX"
  }
}
[Debug] Creating identity token
[Information] Getting claims for identity token for subject: XX
[Information] All claims rule found - emitting all claims for user.
[Debug] Creating JWT identity token
[Information] {
  "Category": "TokenService",
  "Name": "Identity token issued",
  "EventType": "Information",
  "Id": 2001,
  "Details": {
    "SubjectId": "XX",
    "ClientId": "XX",
    "Lifetime": 3600,
    "Claims": {
      "nonce": "abc",
      "iat": 1452168598,
      "at_hash": "Y-mN1WtuRhbRPPE3XI_GsA",
      "sid": "17b4fd801dc0bc241552d1838deea558",
      "sub": "XX",
      "auth_time": 1452151096,
      "idp": "idsrv",
      "amr": "password",
      "name": "XX",
      "phone_number": "",
      "mobile": "XX",
      "family_name": "XX",
      "given_name": "XX",
      "email": "XX"
    }
  },
  "Context": {
    "ActivityId": "7006d81b-3d56-4bd4-9abd-2a6a15d2241b",
    "TimeStamp": "2016-01-07T12:09:58.4077558+00:00",
    "ProcessId": 6352,
    "MachineName": "XX",
    "RemoteIpAddress": "XX",
    "SubjectId": "XX"
  }
}
[Debug] Adding client "XX" to client list cookie for subject "XX"
[Information] {
  "Category": "Endpoints",
  "Name": "Endpoint success",
  "EventType": "Success",
  "Id": 3000,
  "Details": {
    "EndpointName": "authorize"
  },
  "Context": {
    "ActivityId": "7006d81b-3d56-4bd4-9abd-2a6a15d2241b",
    "TimeStamp": "2016-01-07T12:09:58.4077558+00:00",
    "ProcessId": 6352,
    "MachineName": "XX",
    "RemoteIpAddress": "XX",
    "SubjectId": "XX"
  }
}
[Information] End authorize request
[Information] Redirecting to: http://localhost/callback

**Comment by leastprivilege** [comment]
do you keep the inapp browser "alive" between the authentication calls - or do you create new instances?

**Comment by Daforest** [comment]
@leastprivilege We managed to get it working! The auth/endpoint url was case-sensitive, and after modifying this tiny detail, we were redirected back. Thank you so much for your help!
