### ISSUE TITLE
Implement Proof Key for Code Exchange

### ISSUE THREAD

**Issue by mderriey** [IdentityServer/IdentityServer3#2378]
This issue is meant to discuss how you'd like [PKCE](https://tools.ietf.org/html/rfc7636) implemented in IdSrv.

Here are my first thoughts about it:

 - Being optional, it would take the form of a new property on `Client` specifying whether it's enabled or not
 - This property would drive the validators into checking if the additional fields are present in both the Authorization request and the Access Token request
 - The code challenge and the transformation method need to be stored and associated with the authorization code so that the code verifier can be checked when the client requests an access token. Maybe they can even be materialized as properties on the `AuthorizationCode` class?

Let me know if you've already thought about how you'd like it implemented.
Cheers

**Comment by leastprivilege** [comment]
The way we think this could work

* introduce a new flow - `AuthorizationCodeWithProofKey`
* authorize req validator checks the parameters / demands them
* extend the `AuthorizationCode` class to hold the information
* token endpoint checks everything when code + verifier gets handed in

**Comment by mderriey** [comment]
awesome, thanks!

**Comment by leastprivilege** [comment]
done on dev. thanks @mderriey
