### ISSUE TITLE
Reset of "ClientStoreCache" ?

### ISSUE THREAD

**Issue by vmary2014** [IdentityServer/IdentityServer3#2380]
We are developing an application that allows users to add tenancies (subdomains). 

Our IdS clients are stored into a database and the newly added subdomains are updated against the client into the RedirectUri / PostLogoutUri properties.

By default I believe IdS has a client cache that lasts for 5 minutes. I would like to know if there is a way to reset this cache when required (IE when a new subdomain is added) to ensure IdS then fetch the data from the Db and not the cache.

Thanks

**Comment by leastprivilege** [comment]
We don't do that by default. Only if you configure / add the cache. 

Our default implementation is a simplistic in-mem cache only, but you can provide your own implementation that also supports purging / refresh.
