### ISSUE TITLE
RequireSsl / SigningCertificate

### ISSUE THREAD

**Issue by benjaminadrom** [IdentityServer/IdentityServer3#2381]
It seems not clear to me what the difference between "RequireSsl" & "SigningCertificate" is.

<h1>We have 3 Parts:</h1>

<b>1. "IdentityServer3"</b>
which holds the IdentityServer3 (Implicit-Flow)

<b>2. GUI</b>
the "GUI" (or the website) with "OidcTokenManager.js" (https://github.com/IdentityModel/oidc-token-manager),
to login we call the "IdentityServer3" obviously.

<b>3. API </b>
(with IdentityServerBearerTokenAuthenticationOptions)
there are all the controllers  (all requests from the "GUI" goes to the "API", for example: get all own calendar-entries etc.)

<b>SSL</b>: determines the secure connection between the browser and the target (in that case the 1<---> 2), needed on the login.

<b>SigningCertificate:</b> between whom is this important? 1 <--- 2 ---> 3 ?

"API" (3) cannot start when the "SigningCertificate" is not present in "IdentityServer3" (1), so i guess it is required? But i cannot see where or why it is required?

Can i use a self-signed certificate for the "SigningCertificate"? or can we even use the certificate for the SSL?

**Comment by leastprivilege** [comment]
I am sure you checked the docs first? https://identityserver.github.io/Documentation/docsv2/configuration/crypto.html

**Comment by benjaminadrom** [comment]
Hello Dominick, thank you for the quick response!
Yes i already read this page.
But also with that i am not sure, can we use a self signed certificate (or use even use the certificate for the ssl)?

**Comment by leastprivilege** [comment]
you should use a separate certificate from SSL. self signed is fine.

**Comment by benjaminadrom** [comment]
My Usage so far:

<b>Client:</b>
ClientName = "Websuite",
ClientId = "websuite",
Flow = Flows.Implicit,
AllowedScopes = new List<string> {"openid", "user_data", "webapi"}

<b>Scope</b>
<b>var userDataScope</b> = new Scope
	{
		Name = "user_data",
		DisplayName = "User data",
		Type = ScopeType.Identity,
		IncludeAllClaimsForUser = true,
		Claims = new List<ScopeClaim>
		{new ScopeClaim("role", alwaysInclude: true)
		}
	};

<b>var webApiScope</b> = new Scope
	{
		Name = "webapi",
		DisplayName = "Web API",
		Type = ScopeType.Resource,
		Claims = new List<ScopeClaim>
		{
			new ScopeClaim("role")
		}
	};

<b>The API</b>
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = identityServerUrl,//"https://localhost:xyz", //IdentityServer-Url
                ValidationMode = ValidationMode.Local,
                RequiredScopes = new[] { "webapi" },
            });

Via the "oidcTokenManager" i define the client_id with "websuite"

---

It works fine with a self-signed cert., but how is the <b>SigningCertificate</b> coherent  with the  <b>GUI/API/IdentityServer3</b>?

Thank you

**Comment by leastprivilege** [comment]
The the private key part of signing certificate is used to sign the identity and access tokens. The public key part is used to validate the tokens. That's all it is.

**Comment by benjaminadrom** [comment]
Ok i see, but you say
<i>The public key part is used to validate the tokens</i>.

So this means the <b>API</b> does already have the "public key".
Does the key get automatically get requested with the usage of <b>IdentityServerBearerTokenAuthenticationOptions</b>, does it get extracted from the "SigningCertificate" of the IdentityServer3?

**Comment by leastprivilege** [comment]
It gets pulled from identityserver's discovery endpoint.

**Comment by benjaminadrom** [comment]
Great, thank you Dominick!
