### ISSUE TITLE
No cookie matching signin id found

### ISSUE THREAD

**Issue by LeandroPT** [IdentityServer/IdentityServer3#2383]
Hello,

I was having a problem with our current implementation of identity server.
It works perfectly with firefox/chrome, but fails with the message "No cookie matching signin id found" in the log, and on the client side fails with the message "There is an error determining which application you are signing into. Return to the application and try again.".

It was no CORS, CSP, the cookie monster... it was neither of that, and i only found it with fiddler.

The issue is that the hostname contained anunderscore and microsoft has a kb article on it...

!! WARNING !!: Server hostname contains an underscore and this response sets a cookie. Internet Explorer does not permit cookies to be set on hostnames containing underscores. See http://support.microsoft.com/kb/316112

This issue happens with Microsoft IE and Microsoft Edge, works fine with other browsers.

**Comment by brockallen** [comment]
So what are you asking for?

**Comment by LeandroPT** [comment]
Hey,

I was asking for nothing, i was expecting you to close the issue, the point of the issue was a warning for others, since i believe this will be the 1st place people will look (i did :) )

I was looking for it and found issues #1299, #463, #2125 which were unrelated.

I do not know, how many face, or will face, this issue, eventually nothing is to be done, or on AuthenticationController .Login check if the requesthost or server host has an underscore and issue a warning instead of information.

The problem was the fact it worked in others browsers except IE/Edge, and that was killing me, since it is hidden.

Thanks,
Leandro

**Comment by brockallen** [comment]
Ok, thanks for the info on the context.
