### ISSUE TITLE
Question: should IdentityServer return a non-200 http status code on Error pages?

### ISSUE THREAD

**Issue by CrescentFresh** [IdentityServer/IdentityServer3#2384]
When rendering an Error page idsvr3 is responding with 200 OK.

Specifically, this error:

    "There is an error determining which application you are signing into.
    Return to the application and try again."

The impetus for this question is that a security scanning tool we use believes that the server is responding with a valid OK response when requesting what they believe should be an expired signin id (it considers us as having an ineffective session expiration policy and vulnerable to an attacker gaining unauthorized access to the victims users's session using the old but valid and active session ID).

Example:
in phase 1 of a test the auth server redirects to `/login?signin=bce99bf4337c3e2251681fd50fc87279` and renders the login screen.
in phase 2 of the test, after clearing browser cookies, the above url is `POST`'ed to (simulating a login). The expected outcome is that the server respond with an error that the signin id is no longer valid but since the server responds with 200 OK the attack vector is still deemed a threat.

My question: would returning an http status code in the 400 range be appropriate? The flip side: is returning 200 OK actually a good thing by preventing information leakage to scanning tools (thereby requiring the tool be the one to change)?

**Comment by brockallen** [comment]
> The impetus for this question is that a security scanning tool we use believes that the server is responding with a valid OK response

Exactly why a 200 is the right thing :)
