### ISSUE TITLE
Retrieve Client and Scope settings from DB

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#2386]
Hi, 

When I setup identity server I added my clients and scopes into my web.config rather than in memory as per our discussion here (https://github.com/IdentityServer/IdentityServer3/issues/397)

Up until now this has worked quite well because we only set up new RPs occasionally.
We have some new requirements that means we may need to setup new RPs more regularly.

We could always store this information in the Database and retrieve it to create the client and scopes objects in a similar fashion. To my knowledge, this will only ever run during the startup and that only gets triggered by a change to the web.config.

Is there some way of forcing a refresh of clients and scopes configured when a database change is made? Eventually I might look at implementing a user interface for adding new Implicit Clients. It would be handy to have the ability to force a refresh of the client list from the DB when a new one is added without having to make changes on our webserver.

I understand this may not be possible, but thought I'd ask.

**Comment by brockallen** [comment]
You can always rebuild your OWIN/Katana pipeline, which will have the effect of reloading your XML config.

**Comment by malichishti** [comment]
Hi,

 @parkinsona can you share how you achieved this? as i have the same problem to solve. Were you able to rebuild OWIN pipeline, if yes, can you share how?

Thanks

**Comment by parkinsona** [comment]
@malichishti , I never found time to update my instance of idsvr to pull from the database. 

I found that work had been started on Identity Server admin.
this might help:
https://github.com/IdentityServer/IdentityServer3.Admin/issues/25
