### ISSUE TITLE
Add new hook to authorization process that runs regardless if user is authenticated

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#2388]
see https://github.com/IdentityServer/IdentityServer3/issues/2189

**Comment by kylegalbraith** [comment]
This is exactly what we are looking for. I would be interested in helping out any way I can with getting this into IdSvr.

**Comment by brockallen** [comment]
Feature question: Should this new interface/API simply allow the implementer to indicate that the login page should be shown? Is that all this is meant to allow? My sense is that the answer is "yes".

**Comment by brockallen** [comment]
Assuming the answer to the above is "yes", then I don't know if we need a dedicated interface/extension point for this -- a custom `ICustomRequestValidator` can always set `PromptMode` to `"login"` on the `ValidatedAuthorizeRequest`.

**Comment by kylegalbraith** [comment]
What I would be looking for is to have a mechanism that allows me to authenticate the user, and then show them another page that allows them to select a project they are logging into. The idea being that a user could be associated with multiple projects (stashed as claims) and I want them to select the project they are logging into so I can add just that one claim. This logic of course could be pushed onto the application to handle, but requires that the project is not layered in the claims and is thus passed to protected endpoints via another mechanism.

I am not sure this answers your question, but I thought I would throw that out to be batted around.

**Comment by brockallen** [comment]
I don't think we're in a position to develop a new partial login mechanism for the authorization process. What I was thinking was that from the custom request validator if you set the prompt to login you'd have a way to get over to the user service's PreAuthenticate at which point you could do a partial login and take over control over what you needed. The partial login could then redirect back to the return url thus completing the original authorization request/response.

**Comment by brockallen** [comment]
Since this is already possible with the approach I mentioned above, we don't need to add any additional features to support this.
