### ISSUE TITLE
Multiple clients with different ResponseTypes 

### ISSUE THREAD

**Issue by iBoonz** [IdentityServer/IdentityServer3#2391]
Hi

My project has different clients, they are all protected with the same Idsrv.
When a user authorizes with client A, the responseType is <b>id_token.</b>
When the user is navigating to Client B the responseType is <b>id_token token</b>.
Because the user already is authorized when navigating to client B, he does not need to login again, The problem I have with this flow is, that the access token is never filled in for client B.

This Notificaiton is also never fired: 
<code>
Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = n =>
                    {
                        var token = n.ProtocolMessage.AccessToken;

                        // persist access token in cookie
                        if (!string.IsNullOrEmpty(token))
                        {
                            n.AuthenticationTicket.Identity.AddClaim(
                                new Claim("access_token", token));
                        }

                        return Task.FromResult(0);
                    }
                }
</code>
Is there any standard workflow to fix this issue? Do I need to manually logout and let the user login again? Or can I request an access token via another channel?

Thanks

**Comment by leastprivilege** [comment]
If the notification isn't fired - then you probably don't even make a roundtrip to idsrv.

Make sure you give the cookies for each client a unique name - i am almost sure you accidentally re-use cookies between the clients.

**Comment by iBoonz** [comment]
Super, was looking in the wrong direction.
Issue solved. Thanks :)
