### ISSUE TITLE
How to add login page to favorites

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2392]
I use authorization code of idsrv3. when user login a applicaion, they always like adding the login page to favorites. However, it seems that after a period of time, the url is out of date and the idsrv3 will throw a exception. The url is as below:
http://login.example.com/core/login?signin=962fc95997d3701893df2529f73984b0
Are there any config or suggestion for me to solve this issue? Thank you!

**Comment by brockallen** [comment]
Yes, search the archives for the `InvalidSignInRedirectUrl` configuration property.

**Comment by Farwell-Liu** [comment]
ok, thank you!

**Comment by Farwell-Liu** [comment]
If I set the  InvalidSignInRedirectUrl configuration property, when I access the favorite url, it just redirect to the InvalidSignInRedirectUrl simply. That's not what I want.
What's I want is that, when I access the favorite url, it reponse me the login page, After I input the user name and password, it redirect to the corresponding third party application.(there may serveral third party application)
Could you help me please? thank you very much!

**Comment by brockallen** [comment]
This has been discussed several times -- check the issue tracker history. The short answer is that the OIDC protocol doesn't work this way -- this is why there's a configurable URL to redirect the user to so you can do whatever you want to

**Comment by Farwell-Liu** [comment]
I got it, Thank you brockallen!
