### ISSUE TITLE
SSO not working after browser was closed

### ISSUE THREAD

**Issue by FireFly26** [IdentityServer/IdentityServer3#2394]
Dear,

I have an issue with SSO when the browser gets closed and reopened. 

This is my scenario: I have 2 mvc webapp clients, both configured with persistent authentication tickets. 
When I log on to app A, the SSO works and I can switch to app B without having to login again. 
When I close the browser and go back to app A, I don't need to login again because of the persistent auth ticket. So far so good. :) But when I then switch to app B, I get the login screen again and the SSO is broken. 
If I reverse the order and start from app B, I get the same behaviour.

I traced the problem to the AuthorizeInteractionResponseGenerator class where on line 118 my user is not authenticated when I go from app A to app B after the browser has been closed. 

Am I doing something wrong here?

Thx for the help.
Steven.

**Comment by brockallen** [comment]
You actually have 3 cookies -- one for A, one for B, and one for IdentityServer. You need to make sure the cookie at IdentityServer is also persistent if that's what you want.

**Comment by FireFly26** [comment]
Thx, for your answer. You mention I have 3 cookies, but in fact I didn't.:) 
So I changed the default cookiename in the cookie authentication middleware for app B and now my problem is resolved. 

Many thx for the help.
Steven.
