### ISSUE TITLE
Missing nonce?

### ISSUE THREAD

**Issue by dougludlow** [IdentityServer/IdentityServer3#2396]
I'm using a variant of the [aspnet5 sample code](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNet5) and when I make an authorize request with a nonce, I'm not getting the nonce back. My understanding was that when we passed up a nonce, it would be echoed back in the response after authentication. Am I misunderstanding the flow?

Request
`http://localhost:5001/connect/authorize?client_id=[client id]&response_type=id_token%20token&redirect_uri=http:%2F%2Flocalhost:5001%2F&display=popup&state=[state]&scope=openid%20email%20profile%20api&nonce=12345`

Response
`http://localhost:5001/#id_token=[id token]&access_token=[access token]&token_type=Bearer&expires_in=3600&scope=openid%20email%20profile%20api&state=[state]&session_state=[session state]`

**Comment by brockallen** [comment]
`nonce` is returned back in the id_token. maybe you're thinking of the `state` param?

**Comment by dougludlow** [comment]
Oh, I see, I didn't realize it was returned *inside* the id_token. Thanks!
