### ISSUE TITLE
Multiple User Stores in a Single STS

### ISSUE THREAD

**Issue by LinqBeast** [IdentityServer/IdentityServer3#2397]
Any recommendations on working with multiple user stores in a single STS, say from multiple applications?  Thinking in ADFS terms here, the obvious answer is to consolidate all to one store, organized by app and create a single management interface for it, but I was hoping to be able to consume what's already in place with the multiple apps, which each already have UI's for managing their own users/perms.

**Comment by LinqBeast** [comment]
Looks like acr_values tenant value at auth/token endpoint. Guessing id/access tokens will contain value for subsequent to user service...

**Comment by LinqBeast** [comment]
One issue, when in GetProfileDataAsync() or IsActiveAsync() within my UserService, the tenant that I added as a claim in AuthenticateLocalAsync() is not always there.  GetProfileDataAsync() and IsActiveAsync() are called many times, and I need to know the tenant every to hit the correct user store.

Am I missing adding the claim back somewhere?  I do add it again in GetProfileDataAsync() when it is there.

**Comment by LinqBeast** [comment]
Talking to myself here.

Didn't have scopes set up correctly for new tenant claim.

I should help myself more often.

**Comment by brockallen** [comment]
We've both been traveling, thus the lack of interaction here.

Yes, if you have multiple DBs then you can either abstract them in your one user service, or depending on your scenario it might be possible to have different user service implementations that you can dynamically inject them into DI using the callback approach with the `Registration` class.

**Comment by brockallen** [comment]
As for your claims not always being present in the GetProfile API -- yes, it depends on the workflow.

**Comment by LinqBeast** [comment]
Didn't realize you both were off to London.  I just thought my question was dumb.  :). Should've searched github first.

Makes sense.

To get different cookies, I have to make tenant the app host name?  It can't just be different from app-level client to client?

**Comment by brockallen** [comment]
If you do that then you're really hosting multiple instances of IdSvr (different URLs) and so from each instance of IdSrv's perspective there's no concept of a tenant.

**Comment by LinqBeast** [comment]
Ahh, I thought you said in another post we could achieve multiple tenancy, multiple sessions, multiple cookies in a single STS instance by setting the tenant to the host name.

Would be appropriate to allow the user to login to multiple apps, with different claim sets/user stores, but I understand IdSvr doesn't technically support multiple sessions.

**Comment by LinqBeast** [comment]
Okay, I think I get what you mean... I could do:

app.Map("/core", ...);
app.Map("/core2", ...);

In this way, I am hosting two different instances, within a single host.

I would still use the tenant acr_value in my case, because both IdSvr instances use the same code and I key off tenant to choose the connection string.

**Comment by LinqBeast** [comment]
Don't know of another way to have a single IS instance, with multiple app DB user stores... and be able to login into both at the same time, with different cookies.

Right?

**Comment by LinqBeast** [comment]
Either way, that seems works well, albeit a little wasteful resource-wise.

**Comment by LinqBeast** [comment]
Actually, it seems to work, but after I log in the first client at /core, then the second with /core2, the second overwrites the cookie.

The tenant has to be the client URI two have two different cookies?  Obviously, something fundamental I am missing.

**Comment by LinqBeast** [comment]
Okay, I hadn't set the cookie name so, was getting the default aspnet one for each.  Setting each to something unique gave me multiple cookies.  Not sure if that is a bit cloogy, but it did work... deleting a cookie for one app does not affect the other and logging in the second app after the first does not overwrite the first (cookie)... each with their own claims.

Suggest something better?
