### ISSUE TITLE
Registering External Middleware

### ISSUE THREAD

**Issue by alhardy** [IdentityServer/IdentityServer3#2398]
We've integrated some custom pages e.g. forgot password into idsrv as owin middleware components using the idsrv's view service. Initially we were resolving dependencies using our instance of an autofac container but found that the idsrv factory allows registering dependencies with the container used internally i.e. 

```
factory.Register(new Registration<TestMiddelware>());
```

The latest idsrv3 nuget package doesn't seem to use the middleware component injected, I've referenced the core project in my solution works as expected. Is there a known bug in the latest nuget package published related to this? If so when will a package be released?

Cheers in advance.

**Comment by leastprivilege** [comment]
There is no known bug - and we never "registered external middleware". The factory registration is just a way to add more types/classes to our DI.

**Comment by alhardy** [comment]
The bit of code I'm referring to is in AutofacAppBuilderExtensions, there is a method ```UseMiddlewareFromContainer(app, container);``` which iterates all OwinMiddleware registered in the container and does an app.Use(middleware)

We've created a few custom pages, forgot password is one, using owin middleware and idsrv's ViewService. I see this as a great extensibility for this type of thing as we can have our middleware resolved using idsrv's internal autofac container using the same lifetime scope.

The problem I'm having is that any middleware I register is not invoked when referencing the latest nuget package, however if I reference the idsrv core project in the master branch my middleware is invoked as expected.

If you could direct me to a git tag or commit which the latest nuget package is build from I can debug.

**Comment by leastprivilege** [comment]
This did never work for the nuget package because of the way we internalize autofac.

**Comment by alhardy** [comment]
Hmm OK, I can't see why it wouldn't work, I suspect it has something to do with ilmerging autofac, if that's what you mean by internalize? I think it would definitely be useful for others to get this working. For now I have this working using the core assembly without having ilmerged dependencies. 

This obviously isn't ideal, I'll have to come back to soon.

**Comment by alhardy** [comment]
@leastprivilege I managed to get a chance to look into this further. 

The problem I was experiencing was because Microsoft.Owin is also ilmerged so the resolution of types inheriting OwinMiddleware could not be found.

I have a commit [here](https://github.com/domain-group/IdentityServer3/commit/8e04424c01d4efd30cce2af58e7f27052cc01029) which fixes my problem if you guys are happy to not have Microsoft.Owin ilmerged with IdentityServer3?

With this change I'm able to register my owin middleware using ```factory.Register(new Registration<MyMiddleware>())```

**Comment by brockallen** [comment]
We don't have any plans to change how we build our assembly. I know this isn't ideal for your scenario, but the change you're proposing violates our original design and packaging.

As for your web pages you are looking to build, why didn't you just use something like MVC?

**Comment by alhardy** [comment]
We've built an administration site using MR with mvc, however for custom pages related to partially authed  users we found it a nicer fit to use the viewservice you guys have built allowing us to use the same skinning approach and layout and assets as the login page, using this approach allowed access to all idsrvs DI'ed  services without having to take a servicelocator type approach using owin context extensions to resolve dependencies. To me it makes sense to follow the same concepts around this as idsrv. We have a "BaseController"  written as owin middleware which takes care of routing and rendering for us, it's very simple and works well for us. 

Also regarding using mvc, I'm not sure how that would work with the mix of pipelines (WebApi and mvc),  I mean how would resolving the same IOwinContext and other dependencies work given how it is registered with the container? We fought alot with this. 

Why did you guys go with a custom view engine rather than mvc? 

What is the primary use case for the autofac middleware stuff in idsrv as it currently is? It's not used by idsrv internally and serves no purpose to hosting applications at all? To me it's an illusion that this is an extensibility point. 

I come across other issues on github whereby users also have trouble extending idsrv by adding custom pages, I couldn't see that there was a solution or suggestion around this that fit nicely. 

I understand why you guys have ilmerged assemblies here,  but it is limiting extensibility. It seems others have questioned this also. 

What's your concern with not Ilmerging Microsoft.Owin? Assembly binding where needed in hosting applications should be fine shouldn't they? 

If you guys are really set on no dependencies other that owin, I guess I could change idsrv start up  code  and factory to allow registering "pure"  owin middleware without requiring the OwinMiddleWare base class? 

Thoughts?

**Comment by brockallen** [comment]
> Why did you guys go with a custom view engine rather than mvc? 

Because we have requirements to run outside of IIS, thus we couldn't use anything from System.Web.

What is the primary use case for the autofac middleware stuff in idsrv as it currently is? It's not used by idsrv internally and serves no purpose to hosting applications at all?

We needed DI and OWIN doesn't define anything standard. And yes, we use it all over -- it's how dependencies get injected into the various constructors of any class used in IdSvr.

> Assembly binding where needed in hosting applications should be fine shouldn't they? 

That doesn't always work in practice, thus our design decision. For example, we use Web API. Let's say we use v2 of Web API, but you want to use v1. Or vice versa. you can't just always update to the latest and things work. Same for JSON.NET, Autofac, Automapper, EF, MVC, etc.

> If you guys are really set on no dependencies other that owin, I guess I could change idsrv start up code and factory to allow registering "pure" owin middleware without requiring the OwinMiddleWare base class? 

You can do whatever you want in your host's pipeline. I guess what it boils down to is that there are some things from our DI system you want outside of our middleware, and we provide the OWIN extension method for doing that. The other approach is that if what you can setup your own DI configuration for your own middleware, in essence possibly duplicating some of the DI configuration.

**Comment by alhardy** [comment]
Regarding autofac and owin, I'm talking about the way idsrv scans for OwinMiddleWare implemented types, I'm not referring to how the autofac lifetime scope is used to provide the owin context. 

We to don't want to have a System.Web dependency either, the move to asp.net 5 for us could be done more simply by pluging in our middleware initially with minimal changes. 

Re ilmerging, I was only referring to Microsoft.Owin, I do the the benefit you've described however I don't see the big deal for this assembly. 

The path we went down initially was our own Di system, this soon became a pain to maintain and very fragile which led me to taking my current approach.  

Anyways, I guess we can just maintain our own fork for now,  I'm guessing this type of extensibility will be easier with MVC6 and potentially making use of asp.net 5's container.

**Comment by alhardy** [comment]
Re doing whatever we like in our hosts using idsrvs extensions, this still doesn't allow access to partially authed users without my 2nd last commit
