### ISSUE TITLE
Do we need a separate flow for a client that wants a custom grant?

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2399]
I have a client that _usually_ authenticates with IdSrv via ROPC flow. Works fine.

Now, a scenario has arisen where i need to log them in via their Facebook/Google credentials from the client (already established).

Reading/various answers suggests a custom grant is the correct approach here.

So i'm passing through the assertion/grant like so:
```
tokenClient.RequestAssertionAsync("assertion_facebook", "tokenfromclient", "openid roles offline_access api")
```

However, i'm getting a "Client not registerd for custom grant type" error on IdSrv:

```
Client not registered for custom grant type
 {
  "ClientId": "myclient",
  "ClientName": "My client",
  "GrantType": "assertion_facebook",
  "Raw": {
    "grant_type": "assertion_facebook",
    "assertion": "******",
    "scope": "openid roles offline_access api"
  }
}
```

Which they are:
```
AllowedCustomGrantTypes = new List<string> { "assertion_facebook  }
```

Then i see this:
```
Summary:
Gets or sets a list of allowed custom grant types when Flow is set to Custom.
```

That client is currently set to `Flows.ResourceOwner` (as mentioned).

So am i correct to assume i need a _second_ flow (`Flows.Custom`) for this client? Is there any way i combine the two into one client registration? 

Thanks

**Comment by RPM1984** [comment]
This this issue answers my question (yes, you need two flows).
https://github.com/IdentityServer/IdentityServer3/issues/1624

@brockallen @leastprivilege can i make a feature request to allow multiple flows per client, or allowing custom grants in _addition_ to the primary flow? Not sure if it makes sense/impact etc.

Happy to close this issue, or turn into feature request :blush: Thanks!

**Comment by brockallen** [comment]
Well, it's tricky -- there could be an attack if you re-use the same client for different flows.

**Comment by RPM1984** [comment]
@brockallen as in, its safer to use two client registrations than having a custom flow that handles two assertions? Advice on my scenario?

**Comment by brockallen** [comment]
> its safer to use two client registrations than having a custom flow that handles two assertions

Yes.

And for custom grant type clients, it will always need to be a separate client.

**Comment by RPM1984** [comment]
@brockallen so let's say i added another grant type called 'pw'  and just called into `AuthenticateLocal` in my custom grant validator to mimic ROPC, that is bad?

**Comment by brockallen** [comment]
No, I guess not.

**Comment by brockallen** [comment]
Also, we discussed this issue and I think we're going to change the Client config slightly to allow multiple grant types per client. We're not yet sure when/how we're going to add this (since it might be a breaking change).

**Comment by leastprivilege** [comment]
closing this one
