### ISSUE TITLE
WPF Hybrid client shows invalid page in hosted web browser when redirecting to oob://localhost/wpfclient URI is too long?

### ISSUE THREAD

**Issue by andreapoppy** [IdentityServer/IdentityServer3#2400]
Hello guys,

I have this configuration: a WinForm application is the client for IdentityServer, it hosts a WPF browser in order for the user to type username and password. For this implementation I followed the sample: "WPF Hybrid client". It happens that when the user authenticates, then the last redirect uri exceeds the maximum allowed limit (which I think is 2,083 in my wpf browser), and in the wpf browser I read the following error:

>The webpage cannot be displayed
Most likely cause:
Some content or files on this webpage require a program that you don't have installed.

This happens when I use GUIDs for the parameters STATE and NONCE (32+32 = 64 total characters), instead when I limit these to 5 chars each, then I have no problem and the last redirect is caught by the *Navigating* event handler (the length including code, tokens, state and nonce is only 2035 chars)

What do you guys think about this issue?

LOG:
```
2016-01-12 11:18:11.503 +01:00 [Information] Creating Hybrid Flow response.
2016-01-12 11:18:11.668 +01:00 [Information] Creating Implicit Flow response.
2016-01-12 11:18:11.670 +01:00 [Debug] Creating access token
2016-01-12 11:18:11.676 +01:00 [Debug] Creating JWT access token
2016-01-12 11:18:11.728 +01:00 [Debug] Creating identity token
2016-01-12 11:18:11.731 +01:00 [Information] Getting claims for identity token for subject: e4971507-7781-4b36-8006-9b6521f4eb5d
2016-01-12 11:18:11.816 +01:00 [Debug] Creating JWT identity token
2016-01-12 11:18:11.829 +01:00 [Debug] Adding client "myclient" to client list cookie for subject "e4971507-7781-4b36-8006-9b6521f4eb5d"
2016-01-12 11:18:11.851 +01:00 [Information] Redirecting to: oob://localhost/wpfclient
```

**Comment by leastprivilege** [comment]
IE has that 2 KB restriction.

You can use a response_mode of form_post instead. The WPF sample has the code how to handle that.

**Comment by andreapoppy** [comment]
Thank you! Now I understand. This solved the problem.

```
if (e.Uri.ToString().StartsWith(this.callbackUri.AbsoluteUri))
            {
                AuthorizeResponse authResponse = null;

                if (e.Uri.AbsoluteUri.Contains("#"))
                {
                    authResponse = new AuthorizeResponse(e.Uri.AbsoluteUri);
                }
                else
                {
                    var document = (IHTMLDocument3)((WPFBrowser)sender).Document;
                    var inputElements = document.getElementsByTagName("INPUT").OfType<IHTMLElement>();
                    var resultUrl = "?";

                    foreach (var input in inputElements)
                    {
                        resultUrl += input.getAttribute("name") + "=";
                        resultUrl += input.getAttribute("value") + "&";
                    }

                    resultUrl = resultUrl.TrimEnd('&');
                    authResponse = new AuthorizeResponse(resultUrl);
                }
... Continue...
```
