### ISSUE TITLE
Logging in with public/private keys instead of username/password

### ISSUE THREAD

**Issue by ResourceRefactoring** [IdentityServer/IdentityServer3#2401]
I have a native application that need to login to WebApi using public/private key pairs instead of usernames and passwords. 

Is this workflow possible in IdentiyServer? (Not necessarily out of the box, but with customization)

If so, could you please provide me with a few pointers on where to start implementing it?

**Comment by leastprivilege** [comment]
The clients sample has a client that uses a client certificate. Is that what you are looking for?
