### ISSUE TITLE
Different authentication for different clients

### ISSUE THREAD

**Issue by farshid3003** [IdentityServer/IdentityServer3#2402]
How can I understand which client is requesting for authentication in the user service
I have several application some of them are Resource owner some of them use OpenID and some use LDAP to login. I have my CustomUserManager which validate user from db but if I know the client application I can make decision to authenticate user by LDAP.

**Comment by LinqBeast** [comment]
Check the context for the client?

**Comment by farshid3003** [comment]
Yes you are right, I have LocalAuthenticationContext in AuthenticateLocalAsync method
and SignInMessage within. SignInMessage has "ClientId" and "AcrValues" which can solve my problem :)
Thank you so much

**Comment by LinqBeast** [comment]
Sure.  For me though, my user stores and clients are not always 1:1.  At the UI application level, they are, but my Web API's can be accessed by users from multiple apps.  So, tying your connection directly to the client may not always help.

**Comment by farshid3003** [comment]
What a bout this : 
in this case my users can login with ldap and username together if client has ldap available first check ldap but I cannot validate it by ldap I leave it to follow normal flow

        public override async Task AuthenticateLocalAsync(LocalAuthenticationContext ctx)
        {
            
            var username = ctx.UserName;
            var password = ctx.Password;
            var message = ctx.SignInMessage;
            if (userManager.SupportsUserPassword)
            {
                var user = await base.FindUserAsync(username);
                if (message.AcrValues?.Count() > 0)
                {
                    if (message.AcrValues.Any(c => c.StartsWith("ldap", StringComparison.InvariantCultureIgnoreCase)))
                    {
                        string ldapConnectionString = message.AcrValues.First(c => c.StartsWith("ldap=", StringComparison.InvariantCultureIgnoreCase));
                        string[] ldapProps = ldapConnectionString.Split('=').Last().Split(';');
                        string domain = ldapProps.FirstOrDefault(c => c.StartsWith("domain:", StringComparison.InvariantCultureIgnoreCase))?.Split(':').LastOrDefault() ?? "";
                        string uName = ldapProps.FirstOrDefault(c => c.StartsWith("user:", StringComparison.InvariantCultureIgnoreCase))?.Split(':').LastOrDefault() ?? "";
                        string pass = ldapProps.FirstOrDefault(c => c.StartsWith("pass:", StringComparison.InvariantCultureIgnoreCase))?.Split(':').LastOrDefault() ?? "";
                        string domainName = ldapProps.FirstOrDefault(c => c.StartsWith("domainname:", StringComparison.InvariantCultureIgnoreCase))?.Split(':').LastOrDefault() ?? "";
                        using (PrincipalContext context = new PrincipalContext(ContextType.Domain, domain, uName, pass))
                        {
                            string email = "";
                            if (username.ToLower().Contains("@"+domainName))
                            {
                                email = username;
                                username = username.ToLower().Replace("@" + domainName.ToLower(), "");
                            }
                            else
                            {
                                email = string.Format("{0}@{1}", username, domainName);
                            }
                            if (context.ValidateCredentials(username, password))
                            {
                                UserPrincipal ldUser = UserPrincipal.FindByIdentity(context, username);
                                if (user == null)
                                {
                                    user = await base.FindUserAsync(email);
                                    if (user == null)
                                    {
                                        var result = await userManager.CreateAsync(new CustomUser
                                        {
                                            UserName = username,
                                            Email = email,
                                            EmailConfirmed = true,
                                            FirstName = System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ToTitleCase(username.Split('.').First()),
                                            LastName = System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ToTitleCase(username.Split('.').Last()),
                                            UserType = 2
                                        }, password);
                                        if (result.Succeeded)
                                        {
                                            user = await FindUserAsync(username);
                                            await userManager.AddClaimAsync(user.Id, new Claim("name", ldUser.Name));
                                            await userManager.AddClaimAsync(user.Id, new Claim("role", "LdapUser"));
                                            await userManager.AddClaimAsync(user.Id, new Claim("JobTitle", ldUser.Description));
                                            await userManager.AddClaimAsync(user.Id, new Claim("JobPhone", ldUser.VoiceTelephoneNumber));

                                        }
                                    }
                                    else
                                    {
                                        user.UserName = username;
                                        user.FirstName = System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ToTitleCase(username.Split('.').First());
                                        user.LastName = System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ToTitleCase(username.Split('.').Last());
                                        await userManager.UpdateAsync(user);
                                        IList<Claim> claims = await userManager.GetClaimsAsync(user.Id);
                                        if (!claims.Any(c => c.Type == "name"))
                                        {
                                            await userManager.AddClaimAsync(user.Id, new Claim("name", ldUser.Name));
                                        }
                                        if (!claims.Any(c => c.Type == "role" && c.Value == "LdapUser"))
                                        {
                                            await userManager.AddClaimAsync(user.Id, new Claim("role", "LdapUser"));
                                        }
                                        if (!claims.Any(c => c.Type == "JobTitle"))
                                        {
                                            await userManager.AddClaimAsync(user.Id, new Claim("JobTitle", ldUser.Description));
                                        }
                                        if (!claims.Any(c => c.Type == "JobPhone"))
                                        {
                                            await userManager.AddClaimAsync(user.Id, new Claim("JobPhone", ldUser.VoiceTelephoneNumber));
                                        }
                                    }
                                }
                                if (user != null)
                                {
                                  
                                    bool passCheckResult = await userManager.CheckPasswordAsync(user, password);
                                    if (!passCheckResult)
                                    {
                                        await userManager.RemovePasswordAsync(user.Id);
                                        await userManager.AddPasswordAsync(user.Id, password);
                                    }
                                    IList<Claim> claims = await userManager.GetClaimsAsync(user.Id);
                                    if (!claims.Any(c => c.Type == "name"))
                                    {
                                        await userManager.AddClaimAsync(user.Id, new Claim("name", ldUser.Name));
                                    }
                                    if (!claims.Any(c => c.Type == "role" && c.Value == "LdapUser"))
                                    {
                                        await userManager.AddClaimAsync(user.Id, new Claim("role", "LdapUser"));
                                    }
                                    if (!claims.Any(c => c.Type == "JobTitle"))
                                    {
                                        await userManager.AddClaimAsync(user.Id, new Claim("JobTitle", ldUser.Description));
                                    }
                                    if (!claims.Any(c => c.Type == "JobPhone"))
                                    {
                                        await userManager.AddClaimAsync(user.Id, new Claim("JobPhone", ldUser.VoiceTelephoneNumber));
                                    }
                                }
                            }
                        }
                    }
                }
            }
            await base.AuthenticateLocalAsync(ctx);
        }
