### ISSUE TITLE
The checksession endpoint cannot read cookies when in an iframe

### ISSUE THREAD

**Issue by mderriey** [IdentityServer/IdentityServer3#2403]
Hi,

I'm trying to implement the check session feature in the JS walkthrough.  
The implementation is the same as the one you have in the [JS implicit client](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient).

The problem is, if I put a breakpoint in the JS code of the checksession endpoint response - which in this case is loaded in an `iframe`, `document.cookie` is empty, so the hashes don't match, and a `changed` event is fired.
If I load the checksession endpoint in a normal tab, I can get the cookie from the JS code.

It's worth noting that if I run your samples - SelfHost and the JS implicit client - the same thing happens.
I had a look in the issues but couldn't find something similar.
Have you ever come across this issue?

Cheers

**Comment by brockallen** [comment]
Is the issue HTTP in one and HTTPS in another?

**Comment by mderriey** [comment]
brilliant, thanks!

**Comment by mderriey** [comment]
closed
