### ISSUE TITLE
Custom service with external login still setting "amr" as "password"?

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2404]
Hi,

The documentation [here](https://identityserver.github.io/Documentation/docsv2/advanced/userService.html) states:

> There is also an optional authenticationMethod parameter which populates the amr claim. This can be used to indicate how the user authenticated, such as two factor authentication, or client certificates. If it is not passed, then password is assumed for local logins. For external logins, then the value of external will automatically be used to indicate an external authentication.

However, it's still setting it to "password" for my custom user service. Here's my code:

```
public override async Task AuthenticateExternalAsync(ExternalAuthenticationContext context)
{
      var user = await myrepo.GetUser();
      context.AuthenticateResult = new AuthenticateResult(user.Id.ToString(), user.Email, user.Claims);
}
```

The identity token is:

```
"idp": "idsrv",
"amr": "password"
}
```

I can set the `authenticationMethod` manually, but i thought it should default to what's in the OWIN MW (e.g `Google`). I also thought the `idp` would not be IdSrv, since Google is the one providing the identity.

Thanks

**Comment by brockallen** [comment]
So pass the right overloaded params to `AuthenticateResult` :)

**Comment by RPM1984** [comment]
All good, just that the doc suggests the default is provided. l would update the doc with a PR but not sure what to say :blush:

**Comment by brockallen** [comment]
If you pass an idp as a param, then yes, the amr is correctly set.
