### ISSUE TITLE
How to store custom data (like token)?

### ISSUE THREAD

**Issue by wziska** [IdentityServer/IdentityServer3#2405]
Hello, I'm trying to incorporate a call to our internal SSO service (not Facebook, nor Google) in order to acquire custom user token during login to identity server. My plan is to implement own IUserService in which during authentication process I'll call this SSO (passing user/pass) and get the token (it's SAML). But then I have no idea how to keep this token for further reference. 
I'll need this token for accessing some service after user is authenticated with Identity Server, so does it sound reasonable to embed this token as a custom claim? Or is it better to keep it as part of user profile?
Thanks.

**Comment by brockallen** [comment]
Sure, that would work -- the claims you issue from the user service's AuthenticateLocal are just stored in the user's authentication session cookie. So put the SAML token in as a claim, and as long as the user is logged into IdentityServer with that cookie, then you can access the SAML token from the claims.

**Comment by wziska** [comment]
Ok, thanks for the answer.
