### ISSUE TITLE
Customizing login pages

### ISSUE THREAD

**Issue by olee** [IdentityServer/IdentityServer3#2406]
Hi, I want to be able to customize my login pages with additional pages.
I looked up all the information I could find and also looked into IViewService, however I could not find a satisfying solution.

I want to add some custom (MVC) pages to the web project running IdentityServer for user registration and if possible it should use the same controller that also handles rendering of the login pages, so they can easily use the same style.

I also found [this MVC view service](https://github.com/IdentityServer/IdentityServer3.Samples/tree/dev/source/MVC%20ViewService), but it wouldn't allow me to add new pages.

Do you have some feature / recommendation on how to do this?

PS: The project uses AspIdentity as user provider and in the end should run as a single-page application. Another possibility I considered is rendering all the pages as part of the client (javascript) application and connecting to Identity Server by API calls, however I didn't find any information on how to do that.

**Comment by brockallen** [comment]
What's an example of these additional pages? I'm trying to understand the workflow you're looking to perform.

**Comment by olee** [comment]
Like I mentioned - a registration page and all the other pages that come with that.

**Comment by brockallen** [comment]
Right, so that's all possible. Have you not seen some of our samples?

I guess I'm looking for more specific problems you're having.

**Comment by olee** [comment]
That's how I perceived it.

If possible, I wanted to run the registration process in the same web context as IdentityServer and have the login views use the same resources as the registration views.
The best solution would be, if there was a way to render the login pages for IdentityServer and the additional pages I want for registration with a simple, single MVC controller.

**Comment by brockallen** [comment]
You can run these custom pages in the same host as IdentityServer.

As for re-use of the views (and I'm guessing you mainly mean the layout template), I know there's a MVC view service sample from someone -- I've never tried to use it with custom MVC pages. 

But I'm not sure you want your login page to have all of the same stuff your other pages would have -- recall that login is in the context of a user logging into a client application. If that login page has all of the links off to other pages, then your user might get de-railed during the login process.

Our default view service has the concept of a shared layout file -- you might just have to duplicate parts of your common layout in here. You can also add your custom CSS includes as well. 

Check the samples and docs for some more info.

**Comment by olee** [comment]
We just want to use those pages for login and registration, so there won't be any distracting links except "register", so that's fine.

In the end, it seems to be easier to simply adjust the templates for the default view service to match the design of the other pages. I will only have to figure out how to add generated links to actions for a button like "New User? Register here!" for example (I guess I will have to replace the IViewService then).

Thanks for the help and the information!
