### ISSUE TITLE
ASP.NET 5 Partial Login

### ISSUE THREAD

**Issue by mguerrieri** [IdentityServer/IdentityServer3#2407]
I am having trouble implementing partial login on ASP.NET 5/MVC 6.  I am basically trying to do the equivalent of the EULA setup in the CustomerUserService example.  In my controller after the user service redirects for a partial login, I can see there is a "idsrv.partial" cookie in the Request.Cookies collection, but I cannot figure out how to get an identity from that.  Since GetOwinContext() is not there in the ASP.NET 6 MVC controller, I tried doing this:

var principal = await HttpContext.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType);

but this always returns null.  I assume I am just configuring things incorrectly, or I don't have the correct middleware configured to authenticate the partial login cookie, but I am really not sure.  My config is basically (with some stuff removed):

            app.Map("", id =>
            {
                id.UseIISPlatformHandler();

                id.UseCookieAuthentication(new CookieAuthenticationOptions
                {
                    AutomaticAuthenticate = true,
                    AuthenticationScheme = IdentityServer3.Core.Constants.PartialSignInAuthenticationType
                });

                id.UseStaticFiles();

                id.UseMvc(routes =>
                {
                    routes.MapRoute(
                        name: "default",
                        template: "ccs/{controller=Home}/{action=Index}/{id?}");
                });

                var certFile = appEnv.ApplicationBasePath + $"{System.IO.Path.DirectorySeparatorChar}idsrv3test.pfx";

                var ccsIdFactory = new IdentityServerServiceFactory()
                                .UseInMemoryClients(Clients.Get())
                                .UseInMemoryScopes(Scopes.Get());

                var idsrvOptions = new IdentityServerOptions
                {
                    Factory = ccsIdFactory,
                    SigningCertificate = new X509Certificate2(certFile, "idsrv3test"),
                    RequireSsl = false,
                    SiteName = "My Site",
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        EnablePostSignOutAutoRedirect = true,
                        CookieOptions = new CookieOptions
                        {
                            AllowRememberMe = false
                        }
                    }
                };

                id.UseIdentityServer(idsrvOptions);
            });

My web app correctly gets to the login page (via the identity/connect/authorize endpoint), and the id server correctly redirects to the "EULA" controller for partial login, but I can't get the identity out of the partial login cookie from that controller.

Is there an example somewhere I can refer to for ASP.NET 5/MVC 6 with partial login?  Any help would be greatly appreciated.

**Comment by brockallen** [comment]
No, I don't have any partial login samples for ASP.NET 5 -- we've been focused on IdenittyServer4 that targets ASP.NET 5: http://leastprivilege.com/2016/01/11/announcing-identityserver-for-asp-net-5-and-net-core/
