### ISSUE TITLE
SSO HTTP clients security problem

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2410]
Hello,

I have HTTPS idsrv3 and many clients (HTTP/HTTPS) and when i try Sign Out from any client i get console security error only for HTTP clients:
On Mozilla Firefox: ```Blocked loading mixed active content "http://localhost:49998/Account/LogOut?sid=1139e5a9eae3dcc4f5a21eae2551151d"```
On Google Chrome: ```Mixed Content: The page at 'https://idsrv/identity/connect/endsessioncallback?sid=4c25c884ac307e75ece10f340b60cc57' was loaded over HTTPS, but requested an insecure resource 'http://client/'. This request has been blocked; the content must be served over HTTPS.```
On IE: ```SEC7111: HTTPS security is compromised by http://client/Account/LogOut?sid=0967337b32a32ad6261ebfd412ebb483 logout```

This error is from iframe with HTTP clients source.
The HTTPS clients SSO works but the clients logged-in with HTTP no.  

How to make works SSO for HTTP client.
How you solve this problem without forcing clients to pass on HTTPS?

**Comment by brockallen** [comment]
You need SSL for everything -- otherwise you don't have any security.

**Comment by totpero** [comment]
In ```IdentityServerOptions``` you allow ```RequireSsl``` to be False, why if is necessary everything to be SSL?
Why you allow me to set HTTP connection if is not OK?

**Comment by brockallen** [comment]
We allow disabling SSL for dev/testing or proxy server scenarios. But in a production scenario from the user's browser it should be making all calls over HTTPS to both the client app and to IdentityServer.

**Comment by totpero** [comment]
and how i can test SSO over HTTP?

**Comment by brockallen** [comment]
I'm really not understanding -- sorry. 

If you don't want to deal with SSL while testing then set the require ssl flag in IdSvr to false, and make all of your client apps just run on HTTP. Then your single signout iframes will work.

**Comment by totpero** [comment]
if i have all clients and the idsrv3 on HTTP or all to HTTPS then will work? mixing HTTP with HTTPS in this case don't work?

**Comment by brockallen** [comment]
> mixing HTTP with HTTPS in this case don't work?

Correct (at least for the single signout feature).

**Comment by totpero** [comment]
OK, good to know this.
Tx
