### ISSUE TITLE
Clarification regarding Refresh Token lifetimes

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2411]
I found my self a little confused when trying to understand the meaning of the following parameters:
-AbsoluteRefreshTokenLifetime, SlidingRefreshTokenLifetime, RefreshTokenUsage, and RefreshTokenExpiration

You someone help me understand those parameters?

**Comment by mderriey** [comment]
Let's start with the easiest.

`RefreshTokenUsage` determines if, when you use a refresh token to get a new access token, you get a new refresh token (`OneTimeOnly`) or the same one (`ReUse`). Whatever value you choose, IdSrv will send the refresh token handle back when you access the token endpoint, so the best way to avoid errors is to always replace you refresh token with the one you get back - even if they are the same.

Let's focus on the different expiration strategies, now.

`RefreshTokenExpiration.Sliding` means 2 things:

 - When the refresh token is first created, it will have a lifetime of `SlidingRefreshTokenLifetime`
 - When you use the refresh token lifetime, its new lifetime will be `now + SlidingRefreshTokenLifetime` or `creation time + AbsoluteRefreshTokenLifetime`, whichever the lower.

Quick example, let's say you have a `SlidingRefreshTokenLifetime` of `10` and a `AbsoluteRefreshTokenLifetime` of `30`:

 - The refresh token is created at time `T0`
 - You use it at time `T8` to get a new access token. Its new expiration is `T18`
 - You use it again at `T17` which makes it expire at `T27`
 - You use it once again at `T25`. Here the absolute lifetime, `T30`, is lower than the new sliding expiration, `T35`, so `T30` it is

Let's say the token lifetime can be extended, but its entire lifetime will be never be greater than the absolute lifetime.

Finally, `RefreshToken.AbsoluteRefreshTokenLifetime` doesn't involve sliding expiration, so the `SlidingRefreshTokenLifetime` is not used. The refresh token will be valid for `AbsoluterefreshTokenLifetime` after it was created.

**Comment by iLearnIdentityServer** [comment]
Thanks for the answer. 

What would be the practical benefit of using sliding refresh token expiration?

**Comment by leastprivilege** [comment]
whenever you need sliding expiration semantics ;)

**Comment by iLearnIdentityServer** [comment]
:-)

**Comment by iLearnIdentityServer** [comment]
Can you make a practical example?
