### ISSUE TITLE
Authenticating user for 2 MVC Applications and a Web API Application At Once

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3#2413]
I have already set up an IdSvr3 that authenticates a user for an MVC application and a Web API application at once. MVC app's pages make direct ajax calls to Web API. 
I need to redirect the user to another MVC app from the first MVC app. How can I authenticate the user at once for the second MVC application also when the user is authenticated for the first MVC app and the Web API?

**Comment by brockallen** [comment]
You need to do the standard redirect to the token service. Since the user is already logged into IdentityServer, then they will not be prompted to login again.

**Comment by farzad99** [comment]
Thank you Brock for your reply. I don't know how to do what you suggested so Iet me ask you a few questions so that I can get a better understanding. Let me call my applications idSvr3, mvc1, webApi, mvc2. So as I said before I know how to do authentication for mvc1, and webApi so that mvc1 html pages can make ajax calls to webApi. At some point the user clicks the "Redirect to MVC2" button that's supposed to redirect the user to an action method of a mvc2 controller that has the [Authorize] attribute. So is it at this point that I need to do the standard redirect to the token service? Which application is supposed to do the standard redirect to the token service? mvc1 or mvc2?

**Comment by brockallen** [comment]
The `[Authorize]` should automatically trigger the authentication to IdentityServer (assuming you have your katana pipeline setup the right/normal way for OIDC).

**Comment by farzad99** [comment]
I tested and verified what you said. Thank you.
