### ISSUE TITLE
Is it possible to distinguish client app on login and perform action only if user is from specific application?

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#2414]
Hello,

I need to perform action during login in identityServer only if user is from specific client application (or contains specific client claim). I couldn't find how to read client claims in UserService and if it's proper way of doing this? 

In other words I want to authorize action depending on client application. I wrote custom impersonate module and I want to enable it only for one client app. 

The only way of doing this by far is reading client from client store and reading claims but It doesn't seem to be proper way of doing this.

**Comment by brockallen** [comment]
You know the client id in the user service APIs -- it's on the context param. You can then also inject the `IClientStore` into your ctor for use in your methods.

**Comment by pawepaw** [comment]
Ok that's what i already done. I was wondering if it can be done simpler and if reading client claims from database is acceptable.

**Comment by brockallen** [comment]
Where else would they be?

**Comment by pawepaw** [comment]
You are right. Ok thanks for fast response. I'll read them from client store.
