### ISSUE TITLE
IdentityServer performance

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#2415]
Hello again,

We are preparing for deploying our system and one of our application is IdentityServer. We have some performance issues with it and we are not sure if it's because of our customization. Do you have any performance results for server (i.e login action starting at pushing login button in client app)?  Right now it takes around 3-4s fur us and even 40s on cold startup after application recycle. We wonder what results to expect? Of course it depend on machine but maybe you have some results to compare with?

**Comment by brockallen** [comment]
We don't have anything like this to share. Remember, it's just a web application, so all the standard perf things apply. For some of the DB interaction (like client and scope store) we do access the store many times, so we do have some caching helpers to help reduce those round trips. I cant speak to your custom code, of course.

If you identify something specific in IdentityServer, feel free to let us know so we can help improve it.
