### ISSUE TITLE
Limiting users access to certain clients in IdentityServer3

### ISSUE THREAD

**Issue by dgs-hassaan786** [IdentityServer/IdentityServer3#2416]
I have been implementing custom UserService service for identity server3 and reached a point where i am stucked.
the user has successfully login via SSO for client1. Now its going to login Client2 but in the user claims, client2 is not allowed. 

For the first time login AuthenticateLocalAsync method is called, but for the rest the method is not called. How could i stopped user from getting token to access the client2.

Any help?

**Comment by brockallen** [comment]
If a certain user is not allowed to get a token for a certain client you can implement that logic in the custom request validator extensibility point.

**Comment by dgs-hassaan786** [comment]
Good to see ICustomRequestValidation! till now i registered it inside my custom factory.
I have a question, i have request object inside ValidateAuthorizeRequestAsync,
but i could not find any details related user inside it?

**Comment by brockallen** [comment]
`ValidatedAuthorizeRequest.Subject`

**Comment by dgs-hassaan786** [comment]
Thanks man!

**Comment by dgs-hassaan786** [comment]
Hi brock i want to ask one more thing, I have managed to limit the users.
Now i want to provide user an to sign in with different login account. 
in my custom login page i have option
`<li class="divider" ng-show="model.loginWithDifferentAccountUrl"></li>`
but i am not receiving value for `loginWithDifferentAccountUrl`. 
Any solution?

**Comment by brockallen** [comment]
Open a new issue for that, please
