### ISSUE TITLE
ConfigureIdentityProviders towards 2 other Identityservers

### ISSUE THREAD

**Issue by jtourlamain** [IdentityServer/IdentityServer3#2417]
IdentityServer allows us to configure external identity providers (ex. Facebook, google,...) How can I add 2 external IdentityServers from clients? 
```C#
 app.UseIdentityServer(new IdentityServerOptions()
 {
        // Configure a new Factory for an External IdSrv gives errors?
       // var factory = new IdentityServerServiceFactory()     
});
```

**Comment by brockallen** [comment]
two different OIDC MWs with two different auth schemes, and make sure you configure 2 different callback paths.

**Comment by jtourlamain** [comment]
Well... I don't know what would be best. 
I need to create a mobile application which makes use of 
- A our API
- B the API of Client1 OR Client2.

Is it possible that the Mobile app redirect the user to the authorisation server of Client1 and that A our API supports the same token? 
Or do we need to setup our own IdSrv that use/redirects to the external IdentityServers of Client1 or Client2

**Comment by jtourlamain** [comment]
I tried to do the following:
Client App -> MyId3srv (to Hybrid flow). From here I can click on External ExtId3srv. On ExtId3srv I accept again a Hybrid flow client.

I'm able to authenticate, but on MyId3srv I get an error:
*There is an error determining which application you are signing into. Return to the application and try again.*

I guess the second flow needs to be another flow (like Facebook uses a client/secret). But how do you implement the flow on ExtId3srv?

**Comment by brockallen** [comment]
Your API would trust your authorization server. A customer's API (which is what I think you mean when you say "Client" -- remember the term "Client" in OAuth2 and OIDC has a specific meaning) should only trust its own authorization server. But its authorization server can federate with your identity provider.

**Comment by jtourlamain** [comment]
No, My Client is an Mobile app that needs to connect to 2 different resource servers. 1 resource server is owned by me, the other external one isn't. So, I can protect my resource server with MyIdsrv.
However, if the user id identified on the external Idsrv, I want to allow him on my own resource server (but I need not only a token but his identity as well. So OIDC is needed).

**Comment by jtourlamain** [comment]
It seems to be working from Mobile -> MyIdsrv via external UseOpenIdConnectAuthentication -> ExternalIdsrv. I can authenticate, and I return to my App with a token.

However: I can use the token towards my resource server, but not the external resource server (although the token was issued by the external Idsrv). 
Simplified it looks like:
![schema](https://github.com/jtourlamain/IdSrvTest/blob/master/schema.png?raw=true)

The external resource service uses:

```C#
app.UseIdentityServerBearerTokenAuthentication(
                new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://ExternalIdsrv.com/identity",
                    RequiredScopes = new[] { "externalscope" },
                });
```
Is it because I use 2 times the Hybrid flow that the token isn't allowed on the external resource?

**Comment by jtourlamain** [comment]
I just saw that my flow isn't correct at all. I'll start over with other flows
