### ISSUE TITLE
Login Theme

### ISSUE THREAD

**Issue by scty11** [IdentityServer/IdentityServer3#2418]
Hey,

I am currently working on a MVC project and I am using the embedded MVC with the MVC view service approach. I need to have the login view to look different depending on the request url. Its the same client but with different themes depending on the url they used. Can this be captured in some way when they are redirected to the login controller?

Can it be achieved with idsrv?

Thanks

**Comment by leastprivilege** [comment]
You can inject the OwinEnvironmentService into the view service.
