### ISSUE TITLE
Automatic Single Sign-On?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3#2419]
If I have two ASP.NET MVC applications (mvc1 and mvc2) that get their authentication from IdentitySever3 (IdSvr3), do I get automatic single sign-on? What I mean is if the user is authenticated on mvc1 and then then user is redirected to mvc2 from mvc1, is the user automatically authenticated at mvc2 without the user being presented with the login page to do one more time?

**Comment by mderriey** [comment]
Authentication happens at 3 levels:

 - mvc1
 - mvc2
 - IdentityServer

To be authenticated on mvc1, the user is redirected to IdentityServer to log in. After being authenticated on IdentityServer, he's redirected to mvc1 where he'll be signed in with a session cookie.

The first time he'll access mvc2, he won't be authenticated as long as he accesses public resources. If he tries to access a protected resource, he'll be redirected to IdentityServer where he's already authenticated. This means he will not see the login form and will automatically redirected to mvc2 where another session cookie will be created.

**Comment by farzad99** [comment]
I was able to verify what you stated. Thank you for help.
