### ISSUE TITLE
Refreshing claim

### ISSUE THREAD

**Issue by Bidou44** [IdentityServer/IdentityServer3#2421]
Hello everybody

I'm new to IdentityServer and I'm currently looking for the best way to update claims.

The problem happens when the claims are received from an external IdP, they are then automatically stored in the IdentityServer provider database but if the IdP suddenly returns other claims, they will not be updated in the DB.

How can I solve this problem?
Thanks

**Comment by leastprivilege** [comment]
Then you need to update your user service to store the updated external claims.

**Comment by Bidou44** [comment]
Ok, so if I understood you well, I need to override AuthenticateExternalAsync and, if the couple provider/providerId already exists in the Db, I need to do an update (for example, delete all claims and insert the new one).

Is that correct?

**Comment by leastprivilege** [comment]
Yes

— 
cheers
Dominick Baier


On 15 January 2016 at 09:05:58, Bidou44 (notifications@github.com) wrote:

Ok, so if I understood you well, I need to override AuthenticateExternalAsync and, if the couple provider/providerId already exists in the Db, I need to do an update (for example, delete all claims and insert the new one).

Is that correct?

**Comment by Bidou44** [comment]
Thank you!
