### ISSUE TITLE
ADFS and Cors

### ISSUE THREAD

**Issue by paddyhamilton** [IdentityServer/IdentityServer3#2422]
Hi,

I am having an issue with ADFS and Cors.  ill try and explain the problem.

We have a staging environment with ADFS configured with Idsrv and everything works as expected.  
My provider set up is as follows where adfsProvider is a record in a db:

                    AuthenticationType = adfsProvider.ProviderId,
                    Caption = adfsProvider.Caption,
                    MetadataAddress = adfsProvider.MetadataAddress,
                    Wtrealm = adfsProvider.Wtrealm,
                    SignInAsAuthenticationType = signInAsType, // this is passed into the method as a param

I haven't set up the WReply property or the CallbackPath.  As I said this works fine.  I still get the Cors error "Logger.WarnFormat("CORS request made for path: {0} from origin: {1} but rejected because invalid CORS path", path, origin);"  but the path is blank, not sure under what circumstances these are needed.  The flow still continues successfully and logs the user in.

We have just set this up in production, the only difference being that the ADFS is on a farm as opposed to a simple AD setup.  On production the flow only goes as far as logging the above error and stops.  Can the wsfed options be updated to stop this warning?  And what would cause the issue with Idsrv falling over at this point in production with no other logging?

Apologies as this is really 2 questions in 1.

Any help would be very much appreciated.

**Comment by paddyhamilton** [comment]
Ok, so just a follow up.  I understand why the callback path would be used and didn't need it as we have only 1 adfs provider.  So the only issue I have is Idsrv stopping at the cors error and not completing the login flow

**Comment by brockallen** [comment]
It sounds like you're making ajax calls to the authorization endpoint (and thus the login page)  -- is that correct? If so, then why? It's not designed for that.

**Comment by paddyhamilton** [comment]
All I have done is configured Ids with ADFS.  So the configuration for idsrv is as above and on the ADFS server I have added a WS-Fed Passive endpoint which has the url of the idsrv module e.g. https://idsrvTest.com/core and the same realm as configured in idsrv.  Does this sound correct?

**Comment by brockallen** [comment]
How are you making the request to the authorization endpoint from your client app?

**Comment by paddyhamilton** [comment]
Its an MVC app so just using the OpenIdConnectAuthenticationOptions.

    app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = IdentityServerConstants.BaseEndPoint,
                ResponseType = "code id_token token",
                Scope = "openid email profile",
                TokenValidationParameters = GetTokenValidationParameters(),
                SignInAsAuthenticationType = CookieAuthenticationDefaults.AuthenticationType,
}

**Comment by brockallen** [comment]
Right, so CORS only comes up when the code in your page is making ajax calls. It sounds like you're making ajax calls back to your server, and at some point the cookie is no longer valid. At that point, the server is issuing a 302 to the token service, and then that's eventually redirecting to ADFS's login page. ADFS doesn't emit CORS headers (and it shouldn't) and that's why you're seeing this error in your browser's console window. Does that describe what's happening?

**Comment by paddyhamilton** [comment]
Brock, I am going to turn logging on and will get back to you with the flow so as I can see exactly each step.

**Comment by paddyhamilton** [comment]
Brock, here is the main stages in the flow.  I may have misconfigured something on ADFS, but the flow still finishes.

- User logs on and isnt authenticated
- CSP report data
- Rendering 204
- Triggering challenge for external Identity Provider
- External login requested for provider: TestADFS
- CORS request made for path:  from origin: https://adfs.test.com but rejected because invalid CORS path
- External identity successfully validated by user service

**Comment by leastprivilege** [comment]
all set?

**Comment by paddyhamilton** [comment]
I still haven't figured out why this is happening, but it doesn't affect the process so will close it off
