### ISSUE TITLE
Integration with IdentityManager and IdentityServer3.Admin

### ISSUE THREAD

**Issue by devdigital** [IdentityServer/IdentityServer3#2423]
Hi, I'm looking to configure IdentityServer3 to retrieve clients/scopes from IdentityServer3.Admin and users from IdentityManager. I want to use their (RESTful) APIs rather than their underlying data stores, as this feels a better approach.

It looks as though both IdentityManager and IdentityServer3.Admin support just a single authentication method which is specified in their options as 'HostAuthenticationType'.

I want IdentityServer3 to be a trusted subsystem of both IdentityManager and IdentityServer3.Admin, and to use a client certificate for authentication.

Am I correct in thinking the only way to achieve this is to create a custom piece of Katana authentication middleware which is a composite of both the Microsoft.Owin.Security.Cookies middleware, and the Thinktecture.IdentityModel.Owin.ClientCertificates middleware, and then register that as a custom AuthenticationType that is set as the HostAuthenticationType?

Thanks.

**Comment by devdigital** [comment]
Just realised this could also be done with a custom security configuration (SecurityConfiguration option) which authenticates using the certificate middleware, and if not authenticated then falls back to the provided HostSecurityConfiguration.

**Comment by brockallen** [comment]
You should probably be asking this in the IdentityManager repo.

**Comment by devdigital** [comment]
This issue was moved to IdentityManager/IdentityManager#195
