### ISSUE TITLE
CORS-problem with Ajax-requests after session expires

### ISSUE THREAD

**Issue by kiwhen** [IdentityServer/IdentityServer3#2424]
I'm trying to use IdentityServer3 with an MVC application that handles Ajax-requests for saving and loading data. The MVC site is on a different domain than the IdentityServer. Everything works fine for a while (login, redirects, navigation and such), but if I stay idle for a few minutes and try one of the Ajax-methods (not the regular navigation-links, those work fine), I get this error in Chrome's console:

XMLHttpRequest cannot load https://identityserver.domain.com/connect/authorize?client_id=[...]. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12345' is therefore not allowed access.

I've seen dozens of threads with people having this exact same problem, but none of the solutions seem to work. I posted this on SO first, seeing as it does not appear to be a problem with IdentityServer3 itself. Here is the post:

http://stackoverflow.com/questions/34768432/cors-in-ajax-requests-against-an-mvc-controller-with-identityserver3-authorizati

The post explains in more detail what methods I've tried. In short:
- Ajax cookie authentication
- Ajax bearer token authentication
- Enabled "preflight" requests (options) in IdentityServer's startup.cs-file
- Removed the X-Requested-With-header
- AllowAll-setting in the default IdentityServer CORS provider
- Allowed all origins using a custom CORS provider

I was hoping you could set me off the right direction. As I've stated in the SO post, configuration is pretty much standard. We've got a client, a user service, cors service (at least now we do), token providers and so on.

**Comment by brockallen** [comment]
Is this your issue? http://brockallen.com/2013/10/27/using-cookie-authentication-middleware-with-web-api-and-401-response-codes/

**Comment by kiwhen** [comment]
I don't think it is. I tried this solution by adding the following to my startup.cs-file, in the MVC application:
```
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
	AuthenticationType = "Cookies",
	Provider = new CookieAuthenticationProvider
	{
		OnApplyRedirect = ctx =>
		{
			if (!IsAjaxRequest(ctx.Request))
			{
				ctx.Response.Redirect(ctx.RedirectUri);
			}
		}
	}
});
```
If I run the provided example as-is, I get stuck in an infinite redirect loop. This is caused by the authentication type, which seems to be a bit of a mismatch. Setting it to "Cookies" resolves the problem. I was also unable to provide a LoginPath, since we are using the IdentityServer. I can't provide the URL to the IdentityServer as a PathString, as far as I know.

However, with the application now running, I still get the exact same problem with my Ajax-calls as before. They work fine for 3-4 minutes, and then they suddenly start to get redirected to the IdentityServer, resulting in the CORS-error (missing header).

This is the response from the MVC application, telling my Ajax-request to redirect to IdentityServer:
```
HTTP/1.1 302 Found
Cache-Control: private
Location: https://identityserver.domain.com/connect/authorize?client_id=Bar&redirect_uri=http%3a%2f%2flocalhost%3a12345%2f&response_mode=form_post&response_type=id_token+token&scope=openid+profile+email [...]
Server: Microsoft-IIS/10.0
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
Set-Cookie: OpenIdConnect.nonce.<lots of hashed text>
X-SourceFiles: <more hashed text>
X-Powered-By: ASP.NET
Date: Mon, 18 Jan 2016 09:05:07 GMT
Content-Length: 0
```
Ajax proceeds to send this to IdentityServer:
```
GET https://identityserver.domain.com/connect/authorize?client_id=Bar&redirect_uri=http%3a%2f%2flocalhost%3a12345%2f&response_mode=form_post&response_type=id_token+token&scope=openid+profile [...]
Host: identityserver.domain.com
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://localhost:12345
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://localhost:12345/my/url
Accept-Encoding: gzip, deflate, sdch
Accept-Language: nb-NO,nb;q=0.8,no;q=0.6,nn;q=0.4,en-US;q=0.2,en;q=0.2
```
And IdentityServer responds with this:
```
HTTP/1.1 302 Found
Content-Length: 0
Location: https://identityserver.domain.com/login?signin=<id>
Server: Microsoft-IIS/8.5
Set-Cookie: SignInMessage.<hash>; path=/; secure; HttpOnly
X-Powered-By: ASP.NET
Date: Mon, 18 Jan 2016 09:05:07 GMT
```
From there I get the console error saying "XMLHttpRequest cannot load https://identityserver.domain.com/connect/authorize?client_id=Bar&blahblahblah. No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by brockallen** [comment]
Ah, also -- have you set `UseIdentityTokenLifetime=false` on the OIDC middleware? What might be happening is that the cookie is timing out after only 5 minutes.

**Comment by brockallen** [comment]
But hold on -- this makes me wonder how you're securing your web apis -- are you expecting to use the cookie for authenticating the calls into web api? You shouldn't do that (unless you also are using an anti-forgery token).

**Comment by kiwhen** [comment]
I believe you're right. I have put in `useIdentityTokenLifetime = false`, and I am no longer seeing the error after 5 minutes of idleness. Thank you!

Still, I'm interested in finding the root cause for this problem. Not that it is particularly realistic that we will have clients spending 10 hours in an idle state before moving on, but I'm just not very comfortable with this as a permanent solution. If we somehow manage to create an application that only uses Ajax, and this stays in use for 10 hours or so, the CORS-error will come back, yes?

Is there any way for the Ajax-requests to "refresh" their identity before sending anything to the MVC controller, perhaps?

(We do use anti-forgery tokens.)

**Comment by brockallen** [comment]
> Still, I'm interested in finding the root cause for this problem. 

It's because the MS OIDC MW ignores your cookie settings by default and uses the lifetime specified in the id_token. IdSvr only gives the id_token a 5m lifetime.

**Comment by kiwhen** [comment]
Oh yes, that part I understand. I was referring to the CORS-problem that occurs when the cookies does expire. In 5 minutes or 10 hours, it will still expire eventually - is there any way to refresh it using Ajax?

**Comment by brockallen** [comment]
You can set the cookie middleware to use sliding cookies. But you're right -- in theory if the users sits there long enough you may hit this problem. That's why ajax calls should be treated different and return 401 on failed authentication. The cookie approach assumes a UI that can be redirected.

**Comment by kiwhen** [comment]
Alright, I'll look into that.

Thank you very much!
