### ISSUE TITLE
Debugging invalid token at UserInfoEndpoint for hybrid flows 

### ISSUE THREAD

**Issue by codesilverback** [IdentityServer/IdentityServer3#2425]
OK, I'm stumped.  I'm doing what looks like a valid UserInfoEndpoint request but every single time I get.

ERROR IdentityServer3.Core.Validation.TokenValidator [(null)] - Checking for expected scope openid failed

How do we begin to debug this?  Is there a list of things that causes this?  

from the client, I'm requesting 

Scope="openid myapp" ;
ResponseType="code id_token token";

My client is set to use hybrid.

**Comment by stevewoj** [comment]
your client configuration on idsrv might miss openid as allowedscope

**Comment by codesilverback** [comment]
I have my client set to only have the openid scope and it fails.  

If I give it an array e.g. {"openid","myprouct","roles","token", "id_token"} I get the same error.

**Comment by stevewoj** [comment]
sure ya missing something can you post your client config and the userinfoendpoint call

**Comment by codesilverback** [comment]
Client comes from a db:  The OpenId, Profile, and Email are hardcoded and added to the values from the database.

    private static Client ClientFactory(MyCompany.Models.Authentication.RelyingParty rp)
        {
            var scopes = new List<string>
            {
                Constants.StandardScopes.OpenId,
                Constants.StandardScopes.Profile,
                Constants.StandardScopes.Email,
            };
            scopes.AddRange(rp.AllowedScopes.Split(new[]
            {
            " "},
            StringSplitOptions.RemoveEmptyEntries));

            scopes = scopes.Distinct().ToList();
            return new Client()
            {
                ClientName = rp.Url,
                ClientId = rp.Id,
                ClientSecrets = new List<Secret>()
                {
                    new Secret(rp.Secret.Sha256())
                }
                ,
                Enabled = true,
                AccessTokenType = AccessTokenType.Jwt,
                RequireConsent = false,
                RedirectUris = GetRedirectUris(rp),
                AllowAccessToAllScopes = true,
               AllowedScopes =scopes,
               IdentityProviderRestrictions = rp.IdentityProviders.ToList(),
                EnableLocalLogin = rp.IdentityProviders.Contains("local"),
               Flow=GetFlow(rp.Flow)
            };
        }


The ClientInfo call is thusly:


                SecurityTokenValidated = async n =>
                {
                    Log.DebugFormat("SecurityTokenValidated fired. Access token {0}", n.ProtocolMessage.AccessToken);

                    var id = n.AuthenticationTicket.Identity;
                    var sub = id.FindFirst(MyCompany.Authentication.Claims.ClaimTypes.OPEN_ID_CONNECT_SUB);
                    var roles = id.FindAll(ClaimTypes.Role);

                    var nid = new ClaimsIdentity(id.AuthenticationType);

                    nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));  

  var userInfoClient = new IdentityModel.Client.UserInfoClient(
                        new Uri(ConfigurationHelper.IdentConfig().IdentityProviderUrl + "/connect/userinfo"),
                        n.ProtocolMessage.AccessToken);

**Comment by stevewoj** [comment]
The calls look ok for me, from the error you get i still believe that you dont have openid scope in the accesstoken. Not in the office anymore to recheck if i remember right logging was writing the scopes on request/response to output as well would check there if its going allright. Double check if your client requests and gets openid scope.

**Comment by codesilverback** [comment]
My client (in the sense of IClientStore.FindClientById()) definitely has OpenId as a scope, since I hardcoded it into the factory method and added it to any scopes from the database.   

I have an implementation of UserServiceBase.

       public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            Log.Debug(String.Format("AuthenticateLocalAsync: Attempting authentication for clientid: {0}, returnurl {1}", context.SignInMessage.ClientId, context.SignInMessage.ReturnUrl));

            context.AuthenticateResult= AuthenticateLocal(context.UserName, context.Password, context.SignInMessage);
            
            return Task.FromResult(0);
        }

Should this be adding additional claims?

**Comment by leastprivilege** [comment]
are you on the latest version (we had exactly this bug - but it was fixed)? Also there is a userinfo client sample in the samples solution - does that work for you?

**Comment by codesilverback** [comment]
Here's my packages.config for my STS project:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.1.3" targetFramework="net452" />
  <package id="IdentityModel" version="1.3.1" targetFramework="net452" />
  <package id="IdentityServer3" version="2.3.0" targetFramework="net452" />
  <package id="MyCompany.Common" version="1.2.67" targetFramework="net452" />
  <package id="MyCompany.Common.DataAccess" version="1.0.14" targetFramework="net452" />
  <package id="Kentor.AuthServices" version="0.14.0" targetFramework="net45" />
  <package id="Kentor.AuthServices.Owin" version="0.14.0" targetFramework="net45" />
  <package id="log4net" version="2.0.5" targetFramework="net452" />
  <package id="log4net.Ext.Json.1.2.13" version="1.2.13.20140804" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Security.Facebook" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Mindscape.Raygun4Net.Core" version="5.2.0" targetFramework="net452" />
  <package id="Mindscape.Raygun4Net.Mvc" version="5.2.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="8.0.1" targetFramework="net452" />
  <package id="Owin" version="1.0" targetFramework="net45" />
  <package id="Thinktecture.IdentityModel.Client" version="4.0.1" targetFramework="net45" />
</packages>

2.3 is the latest, right?

**Comment by leastprivilege** [comment]
yes - that's true.

OK - nothing stands out (besides json.net v8 which I never tried).

Did you try the client sample with our test host?

**Comment by leastprivilege** [comment]
is this resolved?

**Comment by codesilverback** [comment]
No.  Even calling from the Javascript Implicit Client, I get the same thing.  I'm actually talking to Brock this afternoon.

Symptoms:

I can get the idtoken loaded from the javascript implicit client.  (I’m requesting the scope “openid token”).
I can get the access token loaded from the javascript implicit client.  (I’m requesting the scope “myapp”). 
When I try Login with Profile and Access token, I get a 403 invalid_scope error.  (I’m requesting the scopes “openid profile myapp.”  My client definitely has the openid scope.  In my client factory, I check for it and log.debug to ensure it is there.

So I'm still in the same boat.

**Comment by brockallen** [comment]
Ok, I think @codesilverback and I found the problem. @codesilverback if that's the case, I'll let you close this issue.

**Comment by codesilverback** [comment]
Yeah, the problem was "never override the claims service unless you really know what you are doing."

My overridden service was somehow preventing us from adding scope claims into the token.  Solution: don't do that.

**Comment by codesilverback** [comment]
Actually, to answer the "how to debug" question for future generations:  Take your access token.  Put it into jwt.io.  Note the inexplicable absence of scopes.   That's what helped Brock find the problem.
