### ISSUE TITLE
Remember me is not working with Implicit flow

### ISSUE THREAD

**Issue by tejashdesai** [IdentityServer/IdentityServer3#2426]
Hi,

I have implemented the SSO using implicit flow. there 3 applications. All have its own login page. I am using custom User service for authentication. I am creating the authresult into the "PreAuthenticateAsync" method. Also creating the cookie if the user is authenticated in the user service. Following is my Idsrv start up class:
coreApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Identity Server",
                    SigningCertificate = Certificate.Load(),
                    Factory = idSvrFactory,
                    RequireSsl = true,
                    AuthenticationOptions = new AuthenticationOptions
                    {
                        CookieOptions = new IdentityServer3.Core.Configuration.CookieOptions()
                        {
                            AllowRememberMe = true,
                            SecureMode = CookieSecureMode.Always,
                            RememberMeDuration = TimeSpan.FromDays(15),
                            SlidingExpiration = true
                        },
                        EnableSignOutPrompt = false,
                        EnablePostSignOutAutoRedirect = true,
                        PostSignOutAutoRedirectDelay = 0
                    }
                });

Following is my client startup class:
var options = new CustomOpenIdConnectAuthenticationOptions
            {
                ClientId = "Client1",
                Authority = idServBaseUri,
                RedirectUri = clientUri,
                PostLogoutRedirectUri = clientUri,
                ResponseType = "id_token token",
                Scope = "openid profile email roles",
                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false
            };

If user select the "Remember me" option on the login page and close the browser without log out then currently it always ask for login. I checked into the "SecurityTokenValidated" function of OpenIdConnectAuthenticationOptions and found that "AuthenticationTicket.Properties.IsPersistent" is always false. I donot what i am missing. Why this property is always false.
Please provide me the solution.

Thanks,
Tejash

**Comment by brockallen** [comment]
Do you have the same problem when running our samples?

**Comment by tejashdesai** [comment]
No. Its working perfectly.

**Comment by brockallen** [comment]
Ok, I asked because from the into I can't tell what's wrong. Since you have a working samples, the best thing is to compare what's different between the two.

**Comment by tejashdesai** [comment]
i have implemented the custom OpenIdConnectAuthenticationOptions. Also compared with the sample. I donot what i am missing.

**Comment by brockallen** [comment]
Sorry, not sure what else to suggest. Personally, I'd also trace all the HTTP traffic to watch the cookies to see if I could learn anymore about what's happening.

**Comment by leastprivilege** [comment]
is this resolved?

**Comment by tejashdesai** [comment]
For the work around i am setting the claims and then using that claim generating the persistence cookie in the "CreateAutheticationTicket" method of "OpenIdConnectAuthenticationOptions" class. Let me know if you have any suggestion?

**Comment by brockallen** [comment]
> For the work around i am setting the claims and then using that claim generating the persistence cookie in the "CreateAutheticationTicket" method of "OpenIdConnectAuthenticationOptions" class. Let me know if you have any suggestion?

So your original issue was that the "remember me" setting in IdSvr was not setting a persistent cookie in the MVC client application?

**Comment by brockallen** [comment]
If you have further issues/questions related to this, feel free to reopen.
