### ISSUE TITLE
Client Secret Expiration

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2428]
Is it possible to make client secret never to expire?

**Comment by mderriey** [comment]
Could you elaborate?

I think you're mistaken, client secrets never expire.

**Comment by leastprivilege** [comment]
by default they don't expire - but you can set an expiration date if you like.

**Comment by iLearnIdentityServer** [comment]
Ok. 

Thanks Mickaël, thanks Dominick.

**Comment by mderriey** [comment]
Sorry about that.
