### ISSUE TITLE
Why can't we use In Memory for Token service factory in production?

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2429]
The documentation [here](https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html) states that the `AuthorizationCodeStore`, `TokenHandleStore` etc factories are mandatory for production scenarios.

If i'm running a single instance of IdSrv hosted in IIS (no web farm/no load balancing), any reason why i _shouldn't_ use In Memory for these instances? Obviously this depends on user load, RAM etc..but just curious if we should definitively not be using the in memory store...or if people are, and it's fine.

If not - any recommendations on what to use? Database is obvious, but has anyone built a Redis implementation? If not, i'd be happy to whip a simple one up and share the code.

**Comment by leastprivilege** [comment]
because the stores will be destroyed when the process recycles.
