### ISSUE TITLE
How to get rid of namespace in claim names

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2431]
How to get rid of namespace in claim names? For example

"http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
to 
only "role"?

**Comment by brockallen** [comment]
`JwtSecurityTokenHandler.InboundClaimTypeMap.Clear()`

**Comment by iLearnIdentityServer** [comment]
Ok. 

Is there a way to tell UseIdentityServerBearerTokenAuthentication middleware to do this?

**Comment by brockallen** [comment]
Just add that as a line of code in Startup.

**Comment by iLearnIdentityServer** [comment]
Thanks!
