### ISSUE TITLE
Providing multiple Login Option to Users in CustomView IdentityServer3.

### ISSUE THREAD

**Issue by dgs-hassaan786** [IdentityServer/IdentityServer3#2437]
hi, this is the continued part of https://github.com/IdentityServer/IdentityServer3/issues/2416
 I want to ask one more thing, I have managed to limit the users.
Now I have requirement to provide user option to sign in with different login account. 
in my custom login page I have option
`<li class="divider" ng-show="model.loginWithDifferentAccountUrl"></li>`
but I am not receiving value for `loginWithDifferentAccountUrl`. 
Any solution?

**Comment by brockallen** [comment]
This value might not be present in all views. Check the view models.
