### ISSUE TITLE
Custom CORS service returns false but the call succeed 

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2438]
Maybe I get this wrong.

But I get this behavior that I'm not sure its correct, I think its not.

Basically, I've implemented custom client cors service where I check if the origin is allowed or not.
While testing, even when I return false, the call is successful and the token is returned to the caller.

Is this expected behavior?

**Comment by iLearnIdentityServer** [comment]
Just to add very important detail.

When I return true, the server add appropriate CORS related headers in the response, so that part is ok.

**Comment by brockallen** [comment]
CORS only takes place when ajax calls are made. Perhaps the client is not making any ajax calls?

**Comment by iLearnIdentityServer** [comment]
Its our friend Postman :-)

**Comment by iLearnIdentityServer** [comment]
By the way, this with out preflight

**Comment by brockallen** [comment]
Sorry, I don't know what's going on. I never use postman since that's now how real clients will be making requests.

**Comment by iLearnIdentityServer** [comment]
Postman just sent origin, nothing more than that.
IdentityServer3 custom cors service gets triggered:
- When I return true, Identity Server returns appropriate header and the token
- When I return false, Identity Server does not return header but return the token

**Comment by brockallen** [comment]
Yes, that's how CORS works.

**Comment by iLearnIdentityServer** [comment]
Ok. So basically its left up to the user agent to decide the outcome based on the presence of CORS related data in the response?

**Comment by brockallen** [comment]
Yes, the browser should not invoke any success callbacks if CORS fails. But I can't tell if postman is really using XMLHttpRequest or not to make it's HTTP calls. It's a plugin, so it could be doing native code. It's not really a real JS-based caller (again, it's a plugin so it's more like a native client).

**Comment by iLearnIdentityServer** [comment]
Thanks Allen. 

I will test more these days, just to learn and convince my self that everything is ok :-)
