### ISSUE TITLE
No owin.Environment item was found in the context in identity server logout 

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#2439]
Hi,
We recently found an issue where some users were unable to log out from a RP. When they were redirected to identity server, but were given this error message: "No owin.Environment item was found in the context."

In my idsvr setup, I do the following to remove response headers:
``` c#
 var context = Request.GetOwinContext();
context.Response.Headers.Remove("X-Powered-By");
//etc
```

Upon investigation, I found that it was only happening to users who have a lot of roles and permissions in the RP they are using. I found that if there was a particular claim (eg ROLE) with more than 35 options, then they would get the error. Otherwise they were fine. (The reason they have that many roles is that they're admins for a multi-tenancy application. ) In DEV, the number was a bit higher, but still seemed to have a certain threshold.

My guess is that when the IdTokenHint is being sent back to identityServer in the logout request, the token is too large ( > 2000 characters in DEV would break it, > 3300 in PROD). Is there a default limit on the size of the token that can be sent back?

Here is my RedirectToIdentityProvider handler
``` c#
RedirectToIdentityProvider = async n =>
                    {
                        // if signing out, add the id_token_hint
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idToken = n.OwinContext.Authentication.User.FindFirst("id_token");
                            if (idToken != null)
                            {
                                var idTokenHint = idToken.Value;
                                n.ProtocolMessage.IdTokenHint = idTokenHint;
                            }
                        }
                    },
```

**Comment by parkinsona** [comment]
If I comment out the Request.GetOwinContext() temporarily, it now returns the error:

```
The request filtering module is configured to deny a request where the query string is too long.
```

This now makes a bit more sense.
Is it recommended to increase the allowable query string size? 
Or is there something else we can put in the token hint that doesn't inlcude the entire list of roles etc, so that the request won't be so long?

**Comment by leastprivilege** [comment]
It's probably a browser limitation as well.

The end session endpoint supports POST as well - or - make your tokens smaller ;)

**Comment by parkinsona** [comment]
To make my tokens smaller, I imagine I'd have to not request my roles when I request the token, and then perform a claim lookup afterwards?

Do you have a sample of calling end session with POST? Can that still be wired up through OWIN in a similar fashion to what I have above?

**Comment by leastprivilege** [comment]
you'd have to do that manually - the OWIN MW does not support it.

**Comment by parkinsona** [comment]
Can OWIN middle ware support claims lookup? Or would that be manual too? (I can't remember the endpoint, I think its the UserInfo endpoint)

I was also reading that idTokenHint is optional in the logout endpoint, instead I'd have to pass the PostLogoutURI. Would this be another potential solution?

**Comment by leastprivilege** [comment]
The id token hint is required for the redirect back to the app after logout. If you don't need that - you don't need to send it.

The OWIN MW does not very much for you - that includes (not doing) the userinfo lookup.

**Comment by parkinsona** [comment]
I don't necessarily need the automatic redirect back to the app, but the link is required. It looks like I have to pass the id token. I understand you require the idtoken to ensure the logout request comes from a reliable source. Is there a reason the entire idtoken is required? Could something like just session or subject id used?

Is there a maximum query string length you would recommend? Is there a reason (potential vulnerability) why I wouldn't want to increase it so that my larger idtoken can be sent?

**Comment by parkinsona** [comment]
I was able to fix this by not returning the roles as part of the IdToken and making a separate call to the UserInfo Endpoint.

The role claim in the "myapp" scope set's AlwaysIncludeInIdToken to False

I updated my ResponseType and Scope options in my RP to be:
``` c#
ResponseType = "id_token token",
                Scope = "openid email profile myapp",
```

This is the SecurityTokenValidated handler
``` c#
 SecurityTokenValidated = async n =>
                    {
                        var id = n.AuthenticationTicket.Identity;

                        var userInfoClient = new UserInfoClient(
                        new Uri(n.Options.Authority + "/connect/userinfo"),
                        n.ProtocolMessage.AccessToken);

                        var userInfo = await userInfoClient.GetAsync();

                        foreach(var uiClaim in userInfo.Claims)
                        {
                            if (!id.HasClaim(uiClaim.Item1, uiClaim.Item2))
                            { 
                                id.AddClaim(new Claim(uiClaim.Item1, uiClaim.Item2));
                            }
                        }

   //Change the Name Claim Type
                        id = new ClaimsIdentity(id, null, id.AuthenticationType, ClaimConstants.Name, ClaimConstants.Role);

   //Add the id_token claim for post logout redirect
                        id.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
     n.AuthenticationTicket = new AuthenticationTicket(
                            id,
                            n.AuthenticationTicket.Properties);

                    }
```

**Comment by parkinsona** [comment]
This gives me all the same claims I had previously when creating the authenticationTicket, and reduces the size of the idToken.

I'm guessing this is probably my best option?

**Comment by leastprivilege** [comment]
looks good

**Comment by parkinsona** [comment]
Excellent. Thanks for your help and feedback. Good to get to the bottom of this issue.
Hopefully it helps someone else out there.
