### ISSUE TITLE
How to add custom reponse header in CustomViewService?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2440]
I use authorization code flow of idsrv3 in IIS.
How to add custom reponse header in CustomViewService that implement IViewService?

**Comment by brockallen** [comment]
You can always inject the `OwinEnvironmentService` into any of your services in IdSvr.

**Comment by Farwell-Liu** [comment]
I have inject  OwinEnvironmentService into my service. But this._enviroService.Environment["owin.ResponseHeaders"]  returns Microsoft.Owin.Host.SystemWeb.CallHeaders.AspNetResponseHeaders that accessibility level is internal.  I cannot add my custom response header.

**Comment by leastprivilege** [comment]
You need to wrap the environment in an `OwinContext` first

**Comment by Farwell-Liu** [comment]
perfect! thank you very much!

**Comment by brockallen** [comment]
Sorry, this is not something we're going to help with. It's not something we recommend doing.

**Comment by LeeDumond** [comment]
If you really need to do this you could always use a IHttpModule.

I had to do it on an implementation where were creating an SSO over some really old apps that used framesets. Using a module allowed us to replace the X-Frame-Options from the login page to allow it to be framed by our app.

Did it make me feel dirty? Yes. 
Would I have much rather fixed the original app to not use framesets? Yes!
Did it work? Yes. Got us out of a pretty gnarly jam.
