### ISSUE TITLE
Putting Login page in iframe

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2442]
I read that it is not allowed to put login page in iframe:
https://github.com/IdentityServer/IdentityServer3/issues/288

Is this still true?

**Comment by leastprivilege** [comment]
yes

**Comment by iLearnIdentityServer** [comment]
Ok. Where can I read about security problems that this causes? I want to learn. :-)

**Comment by leastprivilege** [comment]
a) you don't want the most important page to be hosted inside a "untrusted" page
b) click-jacking

**Comment by iLearnIdentityServer** [comment]
thanks!

**Comment by iLearnIdentityServer** [comment]
Can you tell me how you disallow this? I'm just curious. :-)

**Comment by leastprivilege** [comment]
XFO 

https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

**Comment by iLearnIdentityServer** [comment]
Thanks Dominick!

Cheers!
Take care.
