### ISSUE TITLE
ArgumentNullException in FileSystemViewLoader

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#2443]
https://github.com/IdentityServer/IdentityServer3/blob/master/source%2FCore%2FServices%2FDefaultViewService%2FFileSystemViewLoader.cs#L88

Scenario:

* layout page exists on disk
* content page does not exist on disk (and there is no embedded version of it as well)

LoadAsync does **not** return null - but throws.

**Comment by brockallen** [comment]
Something like this? 

![untitled](https://cloud.githubusercontent.com/assets/649492/12420106/7163136c-be88-11e5-961e-cf9d392576b9.png)

**Comment by brockallen** [comment]
When passing a custom name like "login.en-us".

**Comment by brockallen** [comment]
Does this need to get done for 2.4?

**Comment by leastprivilege** [comment]
no. backlog is fine

**Comment by brockallen** [comment]
Notes for myself: 
* for invalid view names, `AssetManager` should return `null`.
* `FileSystemViewLoader` should return `null` when `AssetManager` returns `null`.

**Comment by brockallen** [comment]
Fixed on dev. This change now allows you to have something like this:

```
public class FrenchViewService : DefaultViewService
{
    public FrenchViewService(DefaultViewServiceOptions config, IViewLoader viewLoader) : base(config, viewLoader)
    {
    }

    protected async override Task<Stream> Render(CommonViewModel model, string page)
    {
        var s = await base.Render(model, page + ".fr");
        if (s == null)
        {
            s = await base.Render(model, page);
        }

        return s;
    }
}
```

I suspect that's what you were going for?
