### ISSUE TITLE
Is there a way for setting path for template folder

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2447]
Is there a way for setting path for template folder where the custom views are stored?

**Comment by brockallen** [comment]
You can search the issue list to find out. Or I can give you think link here: https://github.com/IdentityServer/IdentityServer3/issues/2166

**Comment by brockallen** [comment]
The docs also cover this: https://identityserver.github.io/Documentation/docsv2/advanced/DefaultViewService.html

**Comment by iLearnIdentityServer** [comment]
Thanks. I missed that. Probably I read that page after midnight.
