### ISSUE TITLE
Clear partial authentication cookies when user service postauthenticateasync returns an error.

### ISSUE THREAD

**Issue by jdslavin** [IdentityServer/IdentityServer3#2449]
We have a use case where were doing two factor authentication and EULA processing and the user decides to cancel or not agree to the requirements of the two factor or the EULA.  In those cases we return an error from the PostAuthenticateAsync in our custom user service.  When returning an error we believe the partial login cookies should be cleared.   

We added code in a fork of IdentityServer3 to clear those cookies when the PostAuthenticateAsync returns an error.   I submitted a pull request 2448 for the changes we saw necessary to do this.

**Comment by brockallen** [comment]
Ok, thanks. I'll take a look.

**Comment by brockallen** [comment]
I'm not sure I like removing the partial cookie here -- it's only one place where an error might be displayed to the user after a partial login, but there are others. In theory, even if an error was shown, then the user could hit back in the browser to get back to the partial page. If the partial cookie were gone, then they'd be out of luck.

If you really want the partial cookie gone for your specific scenario, then you could trigger that removal yourself in your `PostAuthenticateAsync` with the OWIN extension `RemovePartialLoginCookie`: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by brockallen** [comment]
Also, if you felt strongly about the partial cookie being cleaned up sooner (for all scenarios) then I think it'd make most sense in `ResumeLoginFromRedirect`.

**Comment by jdslavin** [comment]
We actually initially looked at doing that from the PostAuthenticateAsync method but we had trouble locating the OwinContext environment which is necessary for the RemovePartialLoginCookie call.   If you can point me in a direction or example on how to do that I would really appreciate it.

**Comment by brockallen** [comment]
You can inject the `OwinEnvironmentService` into your user service's ctor and then wrap it with an `OwinContext`.

**Comment by jdslavin** [comment]
Thank you Brock, it did not even dawn on me to use the dependency injection you already have built into IdentityServer3.   We got it working that way!!  I have closed the pull request.

**Comment by brockallen** [comment]
Cool, thanks
