### ISSUE TITLE
ASP.NET 5 How to get users data from Entity Framework?

### ISSUE THREAD

**Issue by yrikturash** [IdentityServer/IdentityServer3#2450]
Hi there,
How can I get users data from Entity Framework in ASP.NET 5?
I've tried some official samples, but most of them using old version of ASP.
Best regards, Y.T.

**Comment by mderriey** [comment]
Hi,
The [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) repo is the official one for ASP.NET 5 - now called ASP.NET Core 1.0.
As far as I know, EF support hasn't be ported, I'll let a core dev tell you if it's planned.

**Comment by yrikturash** [comment]
Hm.. I see. 
Thanks for reply.

**Comment by leastprivilege** [comment]
As you probably know all "core-stuff" is a moving target right now. We will focus on porting IdentityServer "core" first (no pun intended). Afterwards all the other things.

Since everything else is just an extensibility point - you can do that yourself for now.
