### ISSUE TITLE
 re-enter credential for special scenarios

### ISSUE THREAD

**Issue by moharrer** [IdentityServer/IdentityServer3#2451]
Hi, 
is Identityserver support re-enter credential for special scenarios like change password ?
for example :
re-enter username and password for change password . Like Gmail change password flow
thanks

**Comment by brockallen** [comment]
Look into the prompt=login or max_age=xxx authorization parameters: https://identityserver.github.io/Documentation/docsv2/endpoints/authorization.html

**Comment by moharrer** [comment]
thank you very much
