### ISSUE TITLE
Q: Quick question about the discovery document?

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3#2453]
I'm building a load-balanced setup and we usually break the SSL at the load balancer. The discovery document gets generated fine, except that I need the protocol to be how the outside world sees it - `https`, not `http`. That's what the "public origin" is for...but I can't use that because of the mulitenancy-by-sub-domain setup I have. 

Is it possible to influence IdSrv3 discovery document just in regards to the generation? 

I can change the request scheme in the OWIN pipeline before it reaches IdSrv3, but I'm not sure if this is not going to mess up something downstream...

**Comment by brockallen** [comment]
We have an extension method on the OWIN environment called `SetIdentityServerOrigin` which you can use to set what we will use as the PublicOrigin, but you get to set it per-request.

**Comment by Peperud** [comment]
Thanks. That's exactly what I was looking for.

...unfortunately Kentor down the pipe doesn't have this concept implemented yet, so at least for the time being, it seems I'll have to change the request scheme anyway...
