### ISSUE TITLE
ClaimsRule + UserInfo

### ISSUE THREAD

**Issue by Cephei** [IdentityServer/IdentityServer3#2455]
There doesn't seem to be any support for claims processing rules according to a Scope's ClaimsRule in regards to UserInfo / GetProfileDataAsync.

While I can create my own custom implementation of IClaimsProvider to write custom rule processing logic, the UserInfo endpoint / UserInfoResponseGenerator does not provide any extensibility to support this.

Ideally, ProfileDataRequestContext, would provide some kind of information about the ClaimsRules for each scope but neither scope or rule information is present.  Thus, I'm left with two options:
  1. Set IncludeAllClaimsForUser to true on my scope. -> All identity claims are added to the id_token if requested (or userinfo endpoint if an access_token is requested).
  2. Explicitly list all claims for each scope.  This is more ideal but removes the dynamic claims resolution that ClaimsRule attempts to solve.

I think the problem also boils down to the inability to optimize database queries for profile information according to requested scopes.  Most likely, this impact is negligible, though I was hoping to hear your thoughts on this.  Do you think I may be missing a deeper understanding of the UserInfo aspect to OpenID Connect?

Thanks everyone!

**Comment by leastprivilege** [comment]
ClaimsRule was intended for custom IClaimsProvider implementations.
