### ISSUE TITLE
SecurityHeadersAttribute headers on DefaultViewService

### ISSUE THREAD

**Issue by vladimirlapacek** [IdentityServer/IdentityServer3#2456]
`SecurityHeadersAttribute` handles some useful HTTP headers like CSP, CTO, XFO. However, it does not seem to be applied everywhere, most most notably on the DefaultViewService. Obviously the attribute cannot be simply used there. I am rather suggesting to copy the headers into the `DefaultViewService` behaviour. Given the flexibility of the View Service, we are free to implement it ourselves, but I think that the Default implementation deserves it, too.

**Comment by brockallen** [comment]
The view service produces the HTML. Our endpoints control the entire response and that's where the headers are being set. So, in essence, any view service should be getting those response headers.

**Comment by vladimirlapacek** [comment]
Of course. I was wrong, you were right.
