### ISSUE TITLE
Custom Views From Embedded Resources

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2458]
Lets say I would like to use OWIN file server and to use EmbeddedResourceFileSystem to serve embedded views. 

There is CustomViewDirectory but in documentation it says: "By default, the custom views are located in a directory named templates within the hosting applications base directory. This can be customized by specifying the CustomViewDirectory property on the DefaultViewServiceOptions. This must be the full filesystem path to the directory."

Is it possible to use custom views that are embedded?

**Comment by brockallen** [comment]
Yes, but they'd need to be done in your own assembly. You can look at the source for IdSvr to see how we did our embedded views.

**Comment by iLearnIdentityServer** [comment]
Ok.
