### ISSUE TITLE
Filter claims

### ISSUE THREAD

**Issue by Bidou44** [IdentityServer/IdentityServer3#2459]
Is it possible to filter the claims my client is receiving?
Currently, I saw that I always have "iss", "aud", "exp", "nbf", and lot more in the token, but I would like to decide which one I output.

I tried to create a custom *IExternalClaimFilter* as well as to override the *GetClaimsFromAccount()* method (of the *UserServiceBase* class) but was not successfull until now... Setting *IncludeAllClaimsForUser=false* does also not do what I would like.

**Comment by leastprivilege** [comment]
I think you should leave that up to the client.

**Comment by Bidou44** [comment]
You mean, the server should always outputs thoses claims?

**Comment by leastprivilege** [comment]
Yes - they belong to the protocol.

— 
cheers
Dominick Baier


On 22 January 2016 at 11:12:38, Bidou44 (notifications@github.com) wrote:

You mean, the server should always outputs thoses claims?
