### ISSUE TITLE
Refresh of access token extends lifetime of other access tokens

### ISSUE THREAD

**Issue by urbanhusky** [IdentityServer/IdentityServer3#2460]
Background:
I've set up some sort of sliding expiration for access tokens because I need users to be logged out after a certain period of inactivity. I am aware that this would allow anyone with a valid token to retain access indefinitely as long as they keep querying our API.
To achieve this, I keep the refresh token as a claim in our ASP.NET MVC application (owin cookie authentication) and use it when I see that half of the lifetime of the token has been reached.

Issue:
Refreshing the token, i.e. requesting a new token by using the reference token (which is single use) yields a new access token with a new expiration date (=good). Querying the introspection endpoint now yields the new expiration date for the old token too (=bad).

Example:
The initial token:
```
token b20199ad2144d730934b22da70cc493b
exp	1453455304
nbf	1453455244
auth_time 1453455211
refresh 402d8e959a5f68131d5341c626d7aeb6 (transformed claim)
```

The token after refresh:
```
token 3db6f9348bb496f8a3f723cd6c3f25ea
exp	1453455337
nbf	1453455277
auth_time 1453455211
refresh 0e43f1a2e95986751b87b33e547211f7 (transformed claim)
```
The claims I see on the Web API (IdentityServerBearerTokenAuthentication) changed when I access it with the old token:
```
token b20199ad2144d730934b22da70cc493b
exp	1453455337
nbf	1453455277
auth_time 1453455211
```

This change obviously comes from the identity server, since I see it in the log as well:
```
2016-01-22 10:34:37,106;[22];INFO;IdentityServer3.Core.Validation.TokenValidator;Token validation success
{
  "ValidateLifetime": true,
  "AccessTokenType": "Reference",
  "TokenHandle": "b20199ad2144d730934b22da70cc493b",
  "Claims": {
    "aud": "https://localhost:44334/resources",
    "iss": "https://localhost:44334",
    "nbf": "1453455244",
    "exp": "1453455304",
    "client_id": "fooclient",
    "tokenLifetime": 60,
    "scope": [
      "Foo",
      "email",
      "offline_access",
      "openid",
      "profile",
      "roles"
    ],
    "sub": "Foo@bar.com",
    "auth_time": 1453455211,
    "idp": "idsrv",
    "amr": "password",
    "email": "Foo@bar.com",
    "name": "Foo@bar.com"
  }
};

...

2016-01-22 10:34:37,123;[21];INFO;IdentityServer3.Core.Validation.TokenRequestValidator;Token request validation success
 {
  "ClientId": "fooclient",
  "ClientName": "foo name",
  "GrantType": "refresh_token",
  "RefreshToken": "402d8e959a5f68131d5341c626d7aeb6",
  "Raw": {
    "grant_type": "refresh_token",
    "refresh_token": "402d8e959a5f68131d5341c626d7aeb6",
    "client_id": "fooclient",
    "client_secret": "foosecret"
  }
};

...

2016-01-22 10:34:37,141;[22];INFO;IdentityServer3.Core.Validation.TokenValidator;Token validation success
{
  "ValidateLifetime": true,
  "AccessTokenType": "Reference",
  "TokenHandle": "3db6f9348bb496f8a3f723cd6c3f25ea",
  "Claims": {
    "aud": "https://localhost:44334/resources",
    "iss": "https://localhost:44334",
    "nbf": "1453455277",
    "exp": "1453455337",
    "client_id": "fooclient",
    "tokenLifetime": 60,
    "scope": [
      "Foo",
      "email",
      "offline_access",
      "openid",
      "profile",
      "roles"
    ],
    "sub": "Foo@bar.com",
    "auth_time": 1453455211,
    "idp": "idsrv",
    "amr": "password",
    "email": "Foo@bar.com",
    "name": "Foo@bar.com"
  }
};
2016-01-22 10:34:40,164;[30];INFO;IdentityServer3.Core.Endpoints.IntrospectionEndpointController;Start introspection request;
2016-01-22 10:34:40,164;[30];DEBUG;IdentityServer3.Core.Validation.ScopeSecretValidator;Start scope validation;
2016-01-22 10:34:40,164;[30];DEBUG;IdentityServer3.Core.Validation.X509CertificateSecretParser;Start parsing for X.509 certificate;
2016-01-22 10:34:40,165;[22];DEBUG;IdentityServer3.Core.Validation.X509CertificateSecretParser;client_id is not found in post body;
2016-01-22 10:34:40,165;[22];DEBUG;IdentityServer3.Core.Validation.PostBodySecretParser;Start parsing for secret in post body;
2016-01-22 10:34:40,165;[22];DEBUG;IdentityServer3.Core.Validation.PostBodySecretParser;No secret in post body found;
2016-01-22 10:34:40,166;[22];DEBUG;IdentityServer3.Core.Validation.BasicAuthenticationSecretParser;Start parsing Basic Authentication secret;
2016-01-22 10:34:40,166;[22];DEBUG;IdentityServer3.Core.Validation.ScopeSecretValidator;Parser found scope secret: BasicAuthenticationSecretParser;
2016-01-22 10:34:40,166;[22];INFO;IdentityServer3.Core.Validation.ScopeSecretValidator;Scope name found: Foo;
2016-01-22 10:34:40,166;[22];DEBUG;IdentityServer3.Core.Validation.ScopeSecretValidator;Secret validator success: HashedSharedSecretValidator;
2016-01-22 10:34:40,167;[22];INFO;IdentityServer3.Core.Validation.ScopeSecretValidator;Scope validation success;
2016-01-22 10:34:40,167;[22];INFO;IdentityServer3.Core.Validation.TokenValidator;Start access token validation;
2016-01-22 10:34:40,168;[22];INFO;IdentityServer3.Core.Validation.TokenValidator;Token validation success
{
  "ValidateLifetime": true,
  "AccessTokenType": "Reference",
  "TokenHandle": "b20199ad2144d730934b22da70cc493b",
  "Claims": {
    "aud": "https://localhost:44334/resources",
    "iss": "https://localhost:44334",
    "nbf": "1453455277",
    "exp": "1453455337",
    "client_id": "fooclient",
    "tokenLifetime": 60,
    "scope": [
      "Foo",
      "email",
      "offline_access",
      "openid",
      "profile",
      "roles"
    ],
    "sub": "Foo@bar.com",
    "auth_time": 1453455211,
    "idp": "idsrv",
    "amr": "password",
    "email": "Foo@bar.com",
    "name": "Foo@bar.com"
  }
};
```

**Comment by urbanhusky** [comment]
Looking at the code I can see why this happens, but I'm still not sure what the idea behind this is? This would also only update the access token that was previously used, not any older ones?
i.e. `(access_token, refresh_token): (a1,r1), refresh: extend a1, return (a2,r2); refresh: extend a2, return (a3,r3)` - with `a1`'s lifetime not being extended?

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/ResponseHandling/TokenResponseGenerator.cs#L152

**Comment by leastprivilege** [comment]
right - you get back a new extended access tokens - older access tokens are not extended.

**Comment by urbanhusky** [comment]
I'm using reference tokens. The Bearer Token Authentication middleware uses the introspection endpoint, which yields a *new* expiration date for the old token.

**Comment by leastprivilege** [comment]
Sorry - I don't follow - 

could you explain your specific scenario and point out where you think the bug is (if it is a bug - or just unexpected behavior).

**Comment by urbanhusky** [comment]
The client requests a new token by supplying the refresh token once it notices that its access token is about to expire. After receiving the new token and refresh token, any introspection of the old token yields a *new* exp - which is the same as the new token's exp.

I would expect that the old token expiration date is unchanged when I request a new token via a refresh token.
I would see this as a bug, that the claims of the old token change (i.e. exp claim) because a client refreshes its token.

My scenario is a web application which uses Bearer Token Authentication against the API. Multiple windows could be seen as isolated clients that use the same access token (because the user only logs in once). 
If another tab or window is opened, it might cause a refresh of the token for that specific window. The other window still uses the old access token. I would expect, that without any further actions, that the access token, of the window that uses the old token, would expire and prevent access to our API. Instead both windows can access the API just fine for the duration of the new token. We have therefore extended the period in which an old token can be used by doing something which is not directly related to that token.

**Comment by brockallen** [comment]
Are you finding this with the in-memory token handle store? Or with an external DB?

**Comment by brockallen** [comment]
Ok, we wrote some tests to repro the issue. The behavior you see is due to the use of the in-memory refresh token store and would not be something you'd see in a DB-backed scenario. In any event, we did add code to address this (regardless of how the DB is done).
