### ISSUE TITLE
One time only use refresh token: new refresh token is bound to expiration of old refresh token?

### ISSUE THREAD

**Issue by urbanhusky** [IdentityServer/IdentityServer3#2461]
I'm trying to debug a weird situation in which refresh of tokens fails reliably after a certain amount of time has passed. 

```C#
RefreshTokenExpiration = TokenExpiration.Absolute,
AbsoluteRefreshTokenLifetime = (int)Math.Ceiling(Lifetimes.RefreshToken.TotalSeconds), 
RefreshTokenUsage = TokenUsage.OneTimeOnly,
```

I request a new token with the refresh token and get a new access and refresh token each. 
Is it intentional that the new refresh token expires at the same time the original refresh token would expire?
I would have expected the new refresh token to expire after `AbsoluteRefreshTokenLifetime`, not when the old token expired.

**Comment by leastprivilege** [comment]
We have tests for the refresh token handling - see if one of them hits your use case. Also feel free to add more. 

Let us know about the outcome.

**Comment by leastprivilege** [comment]
any progress?

**Comment by urbanhusky** [comment]
I'll have to look at it later, this popped up during a particular project that I'm working on some days of the week so I'll have to check that in the context of that project.

**Comment by urbanhusky** [comment]
So to clarify: the absolute refresh token lifetime is the absolute maximum which a chain of refresh tokens can be extended for? I.e. if I want to refresh a token, it will not exceed `first auth time + absolute refresh token lifetime`?

**Comment by leastprivilege** [comment]
IIRC yes.

**Comment by urbanhusky** [comment]
Okay, so that was just a wrong interpretation on my part (or at the very least, it's not documented clear enough for me).

**Comment by leastprivilege** [comment]
feel free to amend the docs
