### ISSUE TITLE
Response code 500 when password is invalid.

### ISSUE THREAD

**Issue by gwwebproof** [IdentityServer/IdentityServer3#2464]
We are receiving a http response code 500 when password is wrong in the login.
Is this correct ?

**Comment by brockallen** [comment]
No. Do you get any info in the IdSvr logs?

**Comment by gwwebproof** [comment]
Im only getting a 500 with username or password missing.
But they are both there and this only happends when the password is wrong.
Btw i am running a custom userservice so i can encapsulate the 
validation call to get more details.
Also forgot to mention i am also running asp net identity

**Comment by brockallen** [comment]
Nope, 200 on the sample host. Check your IdSvr logs for errors.

**Comment by gwwebproof** [comment]
Most likely the wrong forum i posted it in.
This is related to the asp net identity functionality.
Check image and response 500
