### ISSUE TITLE
OpenId Authentication Timeout..

### ISSUE THREAD

**Issue by techdetail** [IdentityServer/IdentityServer3#2465]
I'm trying to timeout (redirect to IP login page) my Relying party (RP1) after 30 seconds of inactivity, but after 30 seconds,  when i perform any activity, the RP1 gets redirected to Identity server and refreshes the identity token and continues to authorize the request, I tried with several settings like UseTokenLifetime  true / false & changing IdentityTokenLifetime value, but i do not get a login page unless until i explicitly click the Logout link.

Am i missing any settings ?

RP1
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                ExpireTimeSpan = new TimeSpan(0, 0, 30),
                SlidingExpiration = true
            });
  	UseTokenLifetime = false / true
IP
        IdentityTokenLifetime = 30 in IP
       Flow = Flows.Hybrid

Also i read an article which says cookie authentication is  powerless when i'm using OpenIdConnet
http://kylesonaty.com/your-cookie-options-are-powerless/

Thanks in advance..

**Comment by brockallen** [comment]
This is the point of SSO. What's you're real requirement?

**Comment by techdetail** [comment]
The user needs to be redirected to login page after X minutes of inactivity.

**Comment by brockallen** [comment]
Inactivity where? In the client app? If you need this, then send a prompt=login as part of the authorization request.

**Comment by leastprivilege** [comment]
all set?

**Comment by techdetail** [comment]
By setting CookieOption at STS server, i was able to achieve what i need, previously i was trying to set it in relying party. Thanks for your support, now it is working as expected.

code:
 	var options = new IdentityServerOptions
                {	
	   AuthenticationOptions = new AuthenticationOptions()
                    {
                        EnablePostSignOutAutoRedirect = true,
                        EnableSignOutPrompt =false,
                        CookieOptions =  new CookieOptions()
                        {
                           ** ExpireTimeSpan =TimeSpan.FromSeconds(30),**
                            SlidingExpiration = true,                            
                        }                       
                    }    
		}
