### ISSUE TITLE
Custom views location in 2.3

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2467]
In documentation for the 2.3 there is:

"Custom views location (Added in v2.4)
By default, the custom views are located in a directory named templates within the hosting applications base directory. This can be customized by specifying the CustomViewDirectory property on the DefaultViewServiceOptions. "

When is planed 2.4 release?

**Comment by brockallen** [comment]
Check the milestones.

**Comment by iLearnIdentityServer** [comment]
Great, coming soon!
