### ISSUE TITLE
BearerTokenAuthenticationOptions, PreserveAccessToken, UserInfoEndpoint and Forbidden

### ISSUE THREAD

**Issue by LinqBeast** [IdentityServer/IdentityServer3#2469]
In my WebApi configuration, I set PreserveAccessToken to 'true' within the IdentityServerBearerTokenAuthenticationOptions, get the 'token' claim in claims transformation and then try to call the UserInfoEndpoint with it, but get 'Forbidden', as such:

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = AuthorityUri,
                RequiredScopes = new[] { Config.Client.OpenIdConnectAuthenticationOptions.Scope },
                PreserveAccessToken = true
            });

app.UseClaimsTransformation(TransformClaims);

...

var accessToken = principal.FindFirst(StringHelper.Current.Lookup(eTokenResponse.Token));

            if (accessToken != null)
            {
                var userInfoClient = new UserInfoClient(new Uri(UserInfoEndpoint), accessToken.Value);
                var userInfo = await userInfoClient.GetAsync();

Ideas?

**Comment by leastprivilege** [comment]
sure - turn on logging.

**Comment by LinqBeast** [comment]
it's on.  maybe not enough.  not sure what I am looking for.  will looks again.

I am authenticating from Swagger. My guess is my client config is not set up correctly for the WebApi.

any examples where you are calling the UserEndPoint service in this manner?

**Comment by LinqBeast** [comment]
More granular logging is definitely your friend:

iisexpress.exe Error: 0 : 2016-01-23 11:42:39.966 -06:00 [Error] "Checking for expected scope openid failed"
"{
\"client_id\": \"stsapiswagger\",
...
iisexpress.exe Error: 0 : 2016-01-23 11:42:40.193 -06:00 [Error] insufficient_scope

My issue then is, that I tried to grant Swagger more scope, but since it only requests a token (and no Id_token), I get 'invalid scope' if I try to request openid like this:

c.OAuth2("oauth2")
                            .Description("OAuth2 Implicit Grant")
                            .Flow("implicit")
                            .AuthorizationUrl(AuthorizeEndpoint)
                            .TokenUrl(TokenEndpoint)
                            .Scopes(scopes =>
                            {
                                scopes.Add("stsapi", "Access STS API");
                                scopes.Add("openid", "Open Id");
                            });

If you check out Swagger's OAuth implementation, the set the response type like so:

url = dets.authorizationUrl + '?response_type=' + (flow === 'implicit' ? 'token' : 'code');

More ideas? :)

**Comment by LinqBeast** [comment]
Looks like I can modify their implementation in the config with:

CustomAsset("lib/swagger-oauth-js", thisAssembly, "Swashbuckle.SwaggerUi.CustomAssets.swagger-oauth.js");

and maybe add:

var validResponseTypes = ['code', 'token', 'id_token', 'id_token token', 'code id_token', 'code token', 'code id_token token'];

**Comment by leastprivilege** [comment]
The clients sample has a userinfo client that works.

**Comment by LinqBeast** [comment]
I've seen those examples.  Thanks.  No issue with IdentityServer and using the UserInfoEndPoint.  Seems to be a limitation with SwashBuckle, which I think I can address, per above.

Thanks for telling me to check out the logging.  Sorry. Closing.

**Comment by LinqBeast** [comment]
Reminds me of the 'ask the duck' prescription Jeff Atwood mentioned in a blog...

**Comment by LinqBeast** [comment]
http://blog.codinghorror.com/rubber-duck-problem-solving/
