### ISSUE TITLE
owinContext is null after the authentication is success.

### ISSUE THREAD

**Issue by lpranith** [IdentityServer/IdentityServer3#2471]
After the local authenticstion is success(used custom service since i used my own database) ,I get the tokens on my client side, and also after the authentication is success i display a developer registration page similar to client registration (on client side itself). When they click save button i try to redirect to a url pointing to a method on server side like"https;///localhost:44319/identity/connect/devregisteration" .

"/connect/devregisteration"  is under my own controller(DevregisterationController), when it comes to this controller, i could see that  owincontext,getcurrentdisplayname(), shows null. Also not sure how to get the signinID from owin.Environment.....Also Security.claims.climidentity.get_claims has no claim items. 

Any suggestion pointer?..would really help.

**Comment by brockallen** [comment]
For the signin id, you need to pass that as a param to your custom page, then you can use the OWIN extension to read it. We have a sample that shows replacing the built in login page with a custom one.

As for the display name -- I'm unclear if the user is logged in or not and if it's a full login or a partial login.

**Comment by lpranith** [comment]
thanks for the reply..User is logged in...via local authentication ..its a full login. Once the user has entered the credentials..i could get the tokens on the client side. Then i display the custom page .When i debug after the url is redirected back to server from the custom page ,it becomes null. 
In my controller i have the following method:
 [Route(Constants.RoutePaths.Oidc.DeveloperRegister, Name = o,.lConstants.RouteNames.Oidc.DeveloperRegister)]
         public async Task<IHttpActionResult> Get(HttpRequestMessage request)
         {
         }
When i debug the request:

request.GetOwinContext().Authentication.User.Identity
{System.Security.Claims.ClaimsIdentity}
    [System.Security.Claims.ClaimsIdentity]: {System.Security.Claims.ClaimsIdentity}
    AuthenticationType: null
    IsAuthenticated: false
    Name: null

**Comment by brockallen** [comment]
For your custom web page to see the username, you'd need to run in the same pipeline as IdSvr (and run after so the cookie middleware we use has a chance to run). From the URL you have, it looks like it's in the correct pipeline.

Also, we don't use the normal OwinContext.Authentication.User -- you should use the OWIN environment extensions. I can't tell from your initial question if you were or not. Here are the docs for them: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by lpranith** [comment]
I wanted to see whether the user is authenticated or  not so was trying to use "request.GetOwinContext().Authentication.User.Identity.IsAuthenticated". 

Also In my callback method on the client side i was trying to retrieve the signin  like
Request.GetOwinContext().Environment.ContainsKey("signInID"); It says there is no such key.

I added the key on server side like 
[Route(Constants.RoutePaths.Login)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IHttpActionResult> LoginLocal(string signin, LoginCredentials model)
        { 
            .....
              this.context.Environment["signInID"]= signin;
            .......
        }

Can you please let me know what is wrong?..can you point me to a sample where the signin as added to environment?

**Comment by brockallen** [comment]
Here's the sample that shows how to provide a custom login page outside of IdSvr: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomLoginPage

**Comment by brockallen** [comment]
If you have further issues/questions related to this, feel free to reopen.

**Comment by lpranith** [comment]
Thank you so much. It helped me to go further.

**Comment by lpranith** [comment]
I do have another question, my flow is:
Login as local user
On success show client registration page ,then in the customuserservice enter the UI details to database table.For this i have separate controller (other than authentication controller)..so once data are entered in to the database My user service will return the result to my own controller..now i have to return the tokens etc to the Client UI. I  just want to continue with normal process after the client details are entered in to the database.
If I use signInMessage.ReturnUrl, it takes me to login page again. When i just say  return Redirect("https://localhost:44319"); it shows authentication as false(User.Identity.IsAuthenticated).I am using MVC authentication module to host the identity server3.

Any suggestion would help me.

**Comment by leastprivilege** [comment]
new question - new issue.
