### ISSUE TITLE
For multi-valued response_type, order shouldn't be important.

### ISSUE THREAD

**Issue by NetChris** [IdentityServer/IdentityServer3#2472]
In ``IdentityServer3.Core.Constants.ResponseTypes`` we can see multi-valued response types like "id_token token" and "code id_token token".  The current IdentityServer3 implementation requires that the incoming raw value of response_type match one of these constant values exactly.  However, the OAuth2 spec states in [section 3.1.1](https://tools.ietf.org/html/rfc6749#section-3.1.1) that 
> Extension response types MAY contain a space-delimited (%x20) list of
> values, where the order of values does not matter (e.g., response
> type "a b" is the same as "b a").

So, for IdentityServer3, if you send "``response_type=id_token+code``" in the URL, you get an error as it expects "``response_type=code+id_token``".

If you agree that this is a needed change, I have a strategy to address this by:
* In ``AuthorizeRequestValidator.ValidateCoreParameters()`` Using the overload of ``SupportedResponseTypes.Contains()`` that takes an ``IEqualityComparer``
* Implementing that ``IEqualityComparer`` to ignore the order of multi-valued response_type strings
* When setting ValidatedAuthorizeRequest.ResponseType, use the actual value from ``SupportedResponseTypes``, not the raw value coming in on the response_type request.

Let me know and I'll put in a PR.

**Comment by leastprivilege** [comment]
Hey - 

feel free to send a PR if you think you have a nice way of solving this problem.

**Comment by brockallen** [comment]
ok PR accepted, thanks
