### ISSUE TITLE
Why can't I add custom response header in custom view?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2480]
I have create a issue here: https://github.com/IdentityServer/IdentityServer3/issues/2440#event-525357482
But it is closed by brockallen.Could you please tell me why adding custom response header is not recommended please? Is it because of security?
I have several scenarios that need to set custom response header in custom view :
1. pop login dialog box. I used iframe in dialog box, and it works well. however I set the response header X-Frame-Options in Global.asax not in custom view.
2.post_logout_redirect_uri. Since idsrv3 doesnot support before, I want to return a custom view with response header of locaion and 302 HttpStatus.
3. single sign out. I plan to use iframe to impement this function, and It also need to set X-Frame-Options header and P3P header of IE.
I think there are some other scenarios that need to set custom response header probable.
Or could you please give me some url and suggestion to help me to fix the three problem above? 
Thank you very much!

**Comment by brockallen** [comment]
Yes, it was because of security concerns. Sorry that we didn't make that more clear in the other issue.

As for questions 2 and 3 -- we do support those features. Perhaps open other issues for each if you have problems.
