### ISSUE TITLE
Reflect IdentityServer remember setting on client side

### ISSUE THREAD

**Issue by rh78** [IdentityServer/IdentityServer3#2482]
IdentityServer provides the option to "Remember My Login". I am using ASP.NET 5 Cookie Authentication through OIDC Authentication Scheme, and depending on this setting I want:

- if user chose "Remember My Login" setting in ID server, I want to generate persistent cookie client side, surviving closing and opening browser
- if user does not choose "Remember My Login", I want to have the default session based cookie which gets wiped on closing browser

I know how to set the cookie persistent, but I do not know how to sync the user choice on IdentityServer side to the client - is it being passed somewhere through expiration dates, or properties etc.?

Thanks!

**Comment by brockallen** [comment]
This is done automatically by the IdSvr login page based on the `CookieOptions` and what the user chooses.

**Comment by rh78** [comment]
Hi, thanks for your feedback. You're right, if the user chooses "Remember My Login" on IdentityServer Login Page, a NEW authentication roundtrip to IdentityServer will not show the login dialog again which is fine. But the client software (through OIDC), after logging in the first time, needs to set up a cookie as well. I need to decide if that cookie I am maintaining should live persistent or only until the user closes the browser - this way I do not need any authentication roundtrip to the identity server when the user accesses the page next time.

**Comment by brockallen** [comment]
This is up to your code in the client app. Look into the `CookieAuthenticationOptions` on the cookie middleware.

**Comment by rh78** [comment]
Hi, yes I know. But can I tell IdentityServer somehow to tell me if "Remember My Login" was checked by the user or not? This way I can dynamically adjust my cookie based on the user decision.

**Comment by brockallen** [comment]
This is not something we pass along in the token.

**Comment by rh78** [comment]
Thats sad. To a user it is hard to explain why he checks "Remember My Login" and then, on client side, this is not being recognized. But thanks for your reply and thanks for providing a really great product!

**Comment by brockallen** [comment]
Well, the point of IdentityServer is to abstract the authentication process. If the user has a persistent login at IdSvr, generally the app doesn't care. And it's ok, because when the user comes into the app on the next day, then it's a quick redirect to get them logged back in. I'd not try to sync the app's persistent cookie with IdSvr's persistent cookie.

**Comment by rh78** [comment]
Yes i agree, this would work good if user is logged in at IdSrv. However, if we always would do a redirect when entering the site, and the user is NOT logged in at IdSrv, the user would be forced to enter the credentials, even if he didnt want to log in in the first place. Or is there a possibility to do a simple auth redirect roundtrip with disabling UI of IdSrv if there is no log in in place?

**Comment by brockallen** [comment]
Yes, you can make a request from an <iframe> to the authorization endpoint passing prompt=none and this will immediaetly return success/failure.

**Comment by rh78** [comment]
hi ok that would probably work. i tried to change idsrv code to make it work by passing additional parameters and i got it actually working. is there any specific reason why you recommend not to sync the app's cookie with idsvr's persistent cookie?

**Comment by brockallen** [comment]
What do you do when the user logs out of IdSvr?

**Comment by rh78** [comment]
I see your point. so your argument is that the regular re-queries when users close and open browser make sure that credentials do not stay valid for too long time after logout, right?

**Comment by brockallen** [comment]
All I'm saying is that they're separate, yet IdSvr is the real main point of truth about the user and their login status.

**Comment by rh78** [comment]
OK thanks for your help! Its very much appreciated!
