### ISSUE TITLE
Q: Resolve LoginPageLinks at runtime/per request?

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3#2484]
I have a multi-tenant setup, and I need these be per-tenant. Is there any way to have them dynamically resolved at run-time?

**Comment by brockallen** [comment]
You could change the login model in a custom view service.

**Comment by Peperud** [comment]
@brockallen 

Thanks for the idea. 
For starters, instead of going for custom view service from scratch I inherited from `DefaultViewService`, overrode the `Login` method and changed the `AdditionalLinks property on the incoming model before calling the base Login. 
Worked fine! 

Now, tried also to add a custom css (`viewOptions.Stylesheets.Add("~/Content/my.css");`). 
And I'm getting 404 on the generated stylesheet link when the login page is rendered. The file does exist on disk (in the `[idsrvroot]/Content` folder). 
Procmon shows what appears to be `[idsrvroot]` being wrongly resolved. 
For example. I have IdSrv3 set at "identity" like this. 
`app.Map("/identity", (IAppBuilder IdSrvApp) =>`. 
There's no actual disk path segment "identity" (or perhaps this should be the fix?). 
Yet, `identity` gets included in the disk path.

What am I doing wrong?

**Comment by brockallen** [comment]
The Stylesheets list just has us add the .css to our layout template. You still need to serve up that file (we don't do it automatically). That depends on your host.

**Comment by Peperud** [comment]
Understood. 

Serving static files of the IdSrv mapped url path is not automatic. In my case, I guess, the host (IIS) kicks in and wrongly resolves the physical path while trying to serve the requested file.

Thanks!
