### ISSUE TITLE
From native app, opening a browser to a website and automatically signing in the user. Is this possible?

### ISSUE THREAD

**Issue by AdamDotNet** [IdentityServer/IdentityServer3#2485]
In reference to #1462,

I find myself wanting to go the other way: a native desktop client using hybrid flow has tokens, and I'm wondering if I can then launch a browser using those tokens to auto sign in to a website with implicit flow (issues a cookie). One thing I did was send up the access_token with the request to the website, verified against the UserInfo endpoint, and then created a cookie. But the problem is that only signs them into the one website, and totally skips the authorization endpoint which means skipping creating the single sign on cookie, so it feels like the wrong solution.

Can you send the id_token, or combination of tokens, to the authorization endpoint? What would the URL look like? When I look at AspNetIdentityUserService<TUser, TKey>, the code doesn't even reach the AuthenticateLocalAsync method without the login UI coming up, and prompt=none does not work either. So my custom code that would read an id_token or something similar and sign them in without using their username and password seeming can't even be reached.

Is this something people typically think should happen at all? Does the spec let this happen? Or are any solutions basically hacks?

**Comment by leastprivilege** [comment]
The spec has nothing for that. Every solution would be custom - and yes probably hacky.

If the web view and the system browser share cookies - you could use that feature (iOS9 and Android 5 allow this e.g.)

**Comment by AdamDotNet** [comment]
Thanks for the quick answer. I meant to get to this sooner. I'm probably not going to go down this road.
