### ISSUE TITLE
RedirectUri Rewritten Dynamically?

### ISSUE THREAD

**Issue by coreyperkins** [IdentityServer/IdentityServer3#2486]
I've ran into an issue where my redirect_uri is being changed at run-time. I have an auth server at my www alias and a client asp.net app at my test alias. If I set my redirect_uri in the configuration to the test alias when the client app tries to auth with the auth server it shows the redirect_uri pointing to the auth server and not my test server, which results in it redirecting to the wrong location.

This is deployed to Azure and everything works fine when I use the Azure cloudapp.net domain. The problem only occurs when I try to use the test alias.

My question is, are there times when the redirect_uri value is trumped due to certain circumstances? I'm trying to find something to track down.

Thanks,

Corey

**Comment by leastprivilege** [comment]
We never change the redirect_uri.

**Comment by coreyperkins** [comment]
Thanks, you confirmed my suspicions that what I am seeing is a DNS issue on our end rather than something going on in idsrv.
