### ISSUE TITLE
How to validate access token if resource endpoint is inside identityserver host

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#2487]
Hello,

I have problem with validating access token. My identityServer host has some custom MVC resource endpoint. I'd like to validate access token and require scope to this endpoint. How can i do this? I tried using access token validation middleware but it fails to start (both identityServer and accessTokenValidation middlewares are in the same app so probably identityServer didn't start yet and accessTokenValidation wanted to validate connection). 

Orgin of my problem is that I want to authenticate client application calling custom endpoint in identityServer host (MVC app). I figured out that I should configure client app to use client credential flow and call desired endpoint with access token. But now I have problem with access token validation.

Or maybe there is another option to authenticate client application?

**Comment by leastprivilege** [comment]
If idsrv and the validation middleware are in the same app you need to configure issuername and signingcert manually on the validation MW.

**Comment by pawepaw** [comment]
Great! That's working now.

Is it proper way of authenticating clients if they want to access resource in identityServer host? I'm asking because you need to make 2 calls to server (1 for token, 2 call to resource), and it could be technically done just within 1 call.

**Comment by leastprivilege** [comment]
I don't follow..

**Comment by pawepaw** [comment]
So. I host identityServer in MVC application. I extended it by adding some custom endpoints. One of my clients is using endpoint. I want to authorize this endpoint so only this client can use it. 

In my client app I have to:

1. call authentication server for access token. (client credentials flow)> 
2. call protected resource with access token.

The question is if it's possible to do within 1 call. because technically identityserver host is able to authenticate clients.

**Comment by leastprivilege** [comment]
No thats not possible. Technically idsrv does not know it is running in the same web app. And you also might change that at some point.

With client creds flow you typically cache the token on the client side, so that is not a big perf impact at all.

**Comment by pawepaw** [comment]
Ok thanks.
