### ISSUE TITLE
SSO asking for login everytime browser is closed?

### ISSUE THREAD

**Issue by dgs-hassaan786** [IdentityServer/IdentityServer3#2488]
Hi, i am facing a very strange problem. I have 3 clients apps and single sign on is working perfectly but as soon as i closed the browser and then reopen it and go to client web its redirect back to login page. I am using form post approach.  I have set the access_token time to 8 hours.

How do I manage when the browser closed and opened agained then not asked login credential but directly login if token is not expire?

    public void Configuration(IAppBuilder app)
        {
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie //"AppCookies"
            });

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "AppTempCookie",
                AuthenticationMode = AuthenticationMode.Passive
            });
     }

i was following example from https://www.scottbrady91.com/Identity-Server/Identity-Server-3-Standalone-Implementation-Part-2

and by server is configured as 

     app.Map("/core", coreApp =>
            {
                
                
                //Use This for InMemoryConfigurationStorage
                //var factory = new IdentityServerServiceFactory()
                //     .UseInMemoryUsers(Users.Get())
                //     .UseInMemoryClients(Clients.Get())
                //     .UseInMemoryScopes(Scopes.Get());
                //factory.ViewService = new Registration<IViewService>(typeof(CustomViewService));

                //Use This for Database Configuration
                var factory = Factory.Configure("IdSvr3Config");
                factory.ConfigureUserService("AspId");
                factory.ViewService = new Registration<IViewService>(typeof(CustomViewService));
                factory.CorsPolicyService = new Registration<ICorsPolicyService>(new DefaultCorsPolicyService { AllowAll = true });
                

                factory.ConfigureClientStoreCache();
                factory.ConfigureScopeStoreCache();
                factory.ConfigureUserServiceCache();

                var options = new IdentityServerOptions
                {
                    SiteName = "DGS Authorization Server",
                    RequireSsl = false,
                    SigningCertificate = Certificate.Get(),
                    Factory = factory,
                    AuthenticationOptions = new AuthenticationOptions {
                        //IdentityProviders = ConfigureAdditionalIdentityProviders,
                        EnableSignOutPrompt = false,
                        EnablePostSignOutAutoRedirect = true,                       
                    },
                    LoggingOptions = new LoggingOptions
                    {
                        EnableWebApiDiagnostics = true,
                        WebApiDiagnosticsIsVerbose = true
                    }                    
                };

                coreApp.UseIdentityServer(options);
            });

**Comment by brockallen** [comment]
Does the user check the "remember me"?

**Comment by dgs-hassaan786** [comment]
no

**Comment by brockallen** [comment]
So there's your answer.

**Comment by dgs-hassaan786** [comment]
yup and thanks again. I just integrated that feature but our UI team just neglected that tiny checkbox.
