### ISSUE TITLE
Allow redirection after failed external login

### ISSUE THREAD

**Issue by olee** [IdentityServer/IdentityServer3#2489]
Hi, I would like to redirect the user to my login page (where I show a toast notification) when he failed to login with an external login provider.
Basically something like an event that is triggered right [here](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/AuthenticationController.cs#L336)

TL;DR: I want to get rid of that error page in general.

Is this possible or is there maybe already some other way to achieve this?

**Comment by brockallen** [comment]
What do you want to happen instead? You want that error to display on the login page?

One idea is that you can always handle the callback notifications in the external authentication middleware you configure.

**Comment by olee** [comment]
Oh that sounds good.
I always tried to do something with the IdentityServer to get this done.
However I didn't think of modifying the external providers!
I will take a look at it tomorrow and reply back here if I get some usable results.
Thanks!

**Comment by olee** [comment]
Ok I got this working with the following code:
````
            app.UseFacebookAuthentication(new FacebookAuthenticationOptions
            {
                AuthenticationType = "Facebook",
                SignInAsAuthenticationType = signInAsType,
                AppId = "..................",
                AppSecret = ".........................",
                Scope =
                {
                    "public_profile",
                    "email"
                },
                Provider = new FacebookAuthenticationProvider
                {
                    OnAuthenticated = context =>
                    {
                        foreach (var x in context.User)
                            context.Identity.AddClaim(new Claim(x.Key, x.Value.ToString()));
                        return Task.FromResult(context);
                    },
                    OnReturnEndpoint = OnReturnEndpoint,
                }
            });

        /// <summary>
        /// Return endpoint for redirecting after failed external login
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        private static Task OnReturnEndpoint(ReturnEndpointContext context)
        {
            if (context.SignInAsAuthenticationType == null || context.Identity == null)
            {
                // <here I actually set some additional data which I use to show the error on the login page>
                context.RedirectUri = WebUtilities.AddQueryString("/core/login", "signin", context.Properties.Dictionary["signinid"]);
            }
            return Task.FromResult(0);
        }
````

This seems to work properly if done for every registered login provider.

**Comment by joostvz** [comment]
@olee How did you manage to display an error message on the login page?
