### ISSUE TITLE
Ref the Eula sample. How could we pass the "AcceptedEula" as a claim instead?

### ISSUE THREAD

**Issue by larserikfinholt** [IdentityServer/IdentityServer3#2490]
See example: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomUserService/CustomUserService/Controllers/EulaController.cs 
I've tried to do a

                var resumeUrl = await ctx.Environment.GetPartialLoginResumeUrlAsync();
                partial_user.AddClaim(new Claim("WorkingContext","123")); // This claim dissapear
                return Redirect(resumeUrl);

But I'm not able to retrive that claim in the CustomUserService

    public override Task GetProfileDataAsync(ProfileDataRequestContext context) 

I guess it's related to adding claims to the partial user and not a "real user", but I'm unable to find out how to do it. Hope

Btw, thanks for a great product! 

In case you wonder why I can't just store the value in the db and retrive like the other claims, here's the business scenario: After loggin in the user is promted for a "working context" that that is kept through his session. It's not an option to store this setting in the db since a user might have several browsers open with multiple working context. A "working context" is limiting what a user are allowed to do.

**Comment by brockallen** [comment]
You can update the claims in the partial login cookie with `UpdatePartialLoginClaimsAsync`: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by larserikfinholt** [comment]
Ahh.. yes thats the method. Thanks
