### ISSUE TITLE
Is there an alternate method of encypting/signing identity tokens other than x509 certificates?

### ISSUE THREAD

**Issue by msiehoff** [IdentityServer/IdentityServer3#2491]
Is there a standard way of using something other than x509  certificates (for example a symmetric key) with identity server? I’m looking to avoid the maintenance costs associated with updating certificates periodically.

From reading the documentation it looked like there is a way to use reference tokens for both access & id tokens, I saw mention of it but was unable to find any specifics on how to implement this.  

The only other option I could see was to implement a custom ITokenSigningService (which didn’t seem ideal).  I went down this path to see if it was at least possible and saw that identity tokens would not be able to be validated on logout and identity server would not redirect the user using the post logout redirect.  After digging a bit deeper I saw that this was because the EndSessionRequestValidator calls the TokenValidator, which attempts to validate the id token using an x509 certificate (which is null in my case).  I didn’t see any hooks to be able to override this (although again, it doesn’t seem like it would be a recommended approach).

Also, I’m using IdentityServer3 version 2.2.3 if the version is of any consequence.

Thanks!

**Comment by leastprivilege** [comment]
No - there is no other way supported. Reference tokens are for access tokens only. 

With symmetric keys you need to protect the key which will then require more crypto - that's why we didn't implement it.

I don't think that the overhead of key rotation for x509 is huge - you need to rotate keys anyways.

**Comment by msiehoff** [comment]
I see, that makes sense. Thank you for your help and your quick response!
