### ISSUE TITLE
Securing a Relying Party using both idsvr and external AD

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#2493]
Hi,

I found a few issues similar to what I'm trying to achieve, but nothing quite the same.
Here's my scenario.

We currently have idsvr with MembershipReboot authenticating a couple of relying parties.
A new client wishes to use one of our Relying Parties, but want to use their AD login to seamlessly access that RP. They have their own application which they log in to, that will contain a link to our Relying Party. They want to be able to click that link and be automatically logged in.

Below is what I think could work. 

- Add ADFS as an external provider in our identity server. According to the doco if we don't setup a caption, this won't appear in the standard idsvr login screen. As this login is just for 1 client, we don't want it to appear for other clients.
- In our relying party, we could check the referring URI. If it matches our cilent's application, we can add an idp hint to the authorize endpoint call. This should redirect them to their own ADFS login and then redirect them to our Relying Party.
- Client adds a link to a secured page in our Relying Party. This should force it to log in automatically.

Does it make sense or is there a better way to achieve this?
I'm not sure how I could set the idp acr_value for just some calls because I'm using OWIN middleware to handle the auth for me in the RP.
Is there a way to show the ADFS external provider link on the idsvr login page based on where they come from? Could using the tenant acr_value be used to show/hide the link?

**Comment by leastprivilege** [comment]
You can set an acr_value hint in your app on the OWIN context that can be picked up by the `RedirectToIdentityProvider` notification of the OIDC MW.

**Comment by parkinsona** [comment]
ahhhhhhhhh of course. That makes sense :)

Is what I'm proposing the recommended approach?

**Comment by parkinsona** [comment]
I just had another idea for how to achieve this.
Would it be possible for my client to redirect to the idsvr authorize endpoint with a redirectUri that is my RP ? This would save them going to the RP and then being redirected to idsvr. Might save one jump in the chain.

**Comment by leastprivilege** [comment]
i don't understand your last question. Is it related to the topic?

**Comment by parkinsona** [comment]
I probably should have closed this issue sooner.

Turns out my client was using SAML and not ADFS so the linked issues was what I was after.

The flow of the request is:
1. Client goes to RP with idp in query string
2. RP reads idp value and stores in a separate cookie for future use
3. RedirectToIdentityProvider notification in RP looks at the cookie and passes the idp to idsvr via acr values
4. Idsvr reads the acr values and redirects to clients SAML provider.
5. Saml provider returns assertion to idsvr
6. Idsvr is logged in and returns to RP.
