### ISSUE TITLE
Custom Claims missing in IdentityToken

### ISSUE THREAD

**Issue by CMIPatrickB** [IdentityServer/IdentityServer3#2494]
Hi there

After authenticating I eventually get a ClaimsPrincipal that contains some claims but none of the ones that I created myself.

My request requests the responseTypes "id_token token".
I include three scopes in my request, namely "openid", "profile", "metatool".
The openid-Scope contains the ScopeClaim "sub" with alwaysInclude = true.
The same (alwaysInclude) applies to every other ScopeClaim of the other two scopes.

When I break in my empty GetProfileDataAsync function I can see, that context.Subject.Claims contains every claim I would expect.

Do you have any idea?
Greetings
Patrick

**Comment by brockallen** [comment]
You need to assign those to the context's `IssuedClaims` -- those claims are different than the authenticated user's claims you see on `context.Subject.Claims`.

**Comment by CMIPatrickB** [comment]
Thanks for your answer.
I read that somewhere in the internet. When I try that, the redirect after authentication somehow doesn't work anymore. I'm using a WebBrowser-Control in WPF and listen on the Navigating-Event if the callback is happening. After setting the IssuedClaims there is no navigating-event with the callback-url.

**Comment by brockallen** [comment]
You should create a new collection and copy over the claims you want. Try that.

**Comment by CMIPatrickB** [comment]
I tried the following:

```c#
public Task GetProfileDataAsync(ProfileDataRequestContext context)
{
    var claims = context.Subject.Claims.Select(claim => new Claim(claim.Type, claim.Value, claim.ValueType, claim.Issuer, claim.OriginalIssuer, claim.Subject)).ToList();
    context.IssuedClaims = claims;
    return Task.FromResult(0);
}
```

The result is the same, unfortunately

1. URI: "http://localhost:3214/identity/connect/authorize?client_id=metatool&response_type=id_token+token&scope=openid+profile+metatool&redirect_uri=oob:%2F%2Fmetatool%2Fcallback&state=879caa5346184d96818cdb5a2d42095c&Nonce=3ca30f0835254bdf8d8baef8b60bcd49"
2. URI: "http://localhost:3214/identity/login?signin=ec7f1f59b77a10b94b14e03bb813f6f4"
3. URI: "http://localhost:3214/identity/login?signin=ec7f1f59b77a10b94b14e03bb813f6f4"
4. URI: "http://localhost:3214/identity/connect/authorize?client_id=metatool&response_type=id_token token&scope=openid profile metatool&redirect_uri=oob:%2F%2Fmetatool%2Fcallback&state=879caa5346184d96818cdb5a2d42095c&Nonce=3ca30f0835254bdf8d8baef8b60bcd49"
5. URI: "http://localhost:3214/identity/connect/consent?client_id=metatool&response_type=id_token token&scope=openid profile metatool&redirect_uri=oob:%2F%2Fmetatool%2Fcallback&state=879caa5346184d96818cdb5a2d42095c&Nonce=3ca30f0835254bdf8d8baef8b60bcd49"

Without the GetProfileDataAsync-problem my last URI is:
oo://metatool/callback#..........

**Comment by brockallen** [comment]
So it sounds like it is working. The last step is that the browser is redirecting to the designated redirect uri with the hash fragment with the tokens.

**Comment by CMIPatrickB** [comment]
I'd never have thought of such a URL length limitation.
That has to be the problem.

If I include only the "sub"-Claim the redirect works with a URL-length of 2034.
The maximum URL length is 2083, according to [https://support.microsoft.com/en-us/kb/208427](url)

For me that means I have to implement some service in the IdentityServer to request the users' claims.
Or do you see another approach?

Would be very kind of you if you provided me a link to information about implementing such a service.
This issue can be closed afterwards.
Thanks again for your help!, I lost almost 2 days with this problem.

**Comment by brockallen** [comment]
Yes, minimize the size of the id_token by not doing `alwaysInclude` for the scope claims, and then use the access token to hit the user profile endpoint. Also, minimize the size of the access token by using a reference token. Many of our samples show these extra steps.

**Comment by CMIPatrickB** [comment]
Thanks!
