### ISSUE TITLE
Best Practice Questions

### ISSUE THREAD

**Issue by rh78** [IdentityServer/IdentityServer3#2499]
Hi guys, thanks for providing IdSrv I love it!

I want to ask you for two hints/best practice recommendations:
1) is it possible to scale IdSrv (combined to ASP.NET Identity Framework) to several servers? If yes, do we need sticky sessions or is it working stateless?
2) actually, how much user data do you recommend to store on the identity server vs. in the application itself? We use IdSrv as identity component to our web portal, and the web portal needs data beginning from name to email notification settings to a lot of other setting stuff. Do you recommend to store everything all together on the IdSrv or do you recommend to host it "outside" and sync the data being stored duplicated (e.g. first name, last name)? is there some best practice?

thanks!

**Comment by brockallen** [comment]
> 1) is it possible to scale IdSrv (combined to ASP.NET Identity Framework) to several servers? 

Yes

> If yes, do we need sticky sessions or is it working stateless?

No, it's stateless assuming you've followed the production deployment guidance: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

> 2) actually, how much user data do you recommend to store on the identity server vs. in the application itself?

Depends. Keep data in IdSvr that's global and need to be centralized. App specific data should stay in the app.
