### ISSUE TITLE
MVC 5 authentication/authorization filters and IdentityServer3

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2500]
I am trying to understand if these two filters fit into the flow using IdentityServer3. Can I see a sample using these filters ? I am using the embedded server to test OpenIDConnect flow with WebAPI.

**Comment by brockallen** [comment]
I'm not entirely clear on what you are referring to. Can you elaborate?

**Comment by mohanr** [comment]
When the user is not authenticated I want to show the login page. After the user is authenticated and authorized he gets a claims token and gains access to the rest endpoint. Do the filters come into play only to check the rights of the user after the token is obtained ?

**Comment by brockallen** [comment]
Once the user has been logged into the MVC app, then it's normal cookie authentication from there, so yes, filters work normally.

**Comment by mohanr** [comment]
This cookie authentication after the user is logged in can be used in mobile devices too ? We target mobile and desktop browsers.

**Comment by brockallen** [comment]
A browser is a browser.
