### ISSUE TITLE
One LogoutUri but multiple RedirectUris and PostLogoutRedirectUris

### ISSUE THREAD

**Issue by 8aginski** [IdentityServer/IdentityServer3#2501]
After the LogoutUri setting was introduced, I'm not sure what the proper way to configure clients is. Your samples reuse one Client for multiple applications thanks to the possibility to provide multiple RedirectUris and PostLogoutRedirectUris. However, only one LogoutUri can be provided.

For instance let's take a look at [the sample](https://github.com/IdentityServer/IdentityServer3/blob/2.3.0/source/Host.Configuration/Config/Clients.cs#L153). Presumably HTTP-based logout works only for the https://localhost:44301/ web-application. What if I wanted to enable the same feature for applications http://localhost:2671/ and http://localhost:21575/ as well? Should I create a separate Client per application, each with one item in the RedirectUris and PostLogoutRedirectUris lists and appropriate LogoutUri?

**Comment by brockallen** [comment]
You should configure separate clients for different logical apps (for example, a MVC app should be a different client than a JS-based Angular/SPA app). The only reason you're allowed to configure different multiple redirect URIs is for things like localization (e.g. http://en.app.com and http://fr.app.com, or http://app.com/en and http://app.com/fr). Many apps only need one redirect URI.

Our samples are perhaps a bit misleading in how you'd normally do that. That's a fair criticism.

**Comment by brockallen** [comment]
We've recently reworked how we do our configuration so that there's a different client config for each client samples. HTH
