### ISSUE TITLE
Reading auth token and claims from outside .net

### ISSUE THREAD

**Issue by jstrawther** [IdentityServer/IdentityServer3#2502]
I maintain an IdentityServer3 OP and several ASP.NET MVC clients apps which all share a ClientID, machineKey and validationKey.  My colleague maintains the top-level ColdFusion website for our organization, and wants to take the first steps toward integrating our SSO into that site.  But they don't (yet) want the CF app to be a client to the IdentityServer; they only want to be able to determine that a user has already signed into one of the .NET apps, and provide a "Welcome, username" label and a logout link.  

I'm looking for some general guidance on an approach.  Not necessarily specific to ColdFusion, but more generally, is there a way to decrypt and interpret the identity cookie to extract claims without establishing the CF app as a relying party?  Thanks

**Comment by leastprivilege** [comment]
Are you talking about the cookie or the token?

The token is a standard JWT token - there are lots of libraries out there. The cookie in ASP.NET is proprietary - and unless you reverse engineer yourself - I am not aware of tool to read it outside of Katana.

**Comment by jstrawther** [comment]
The cookie.  Basically looking to support SSO between .NET and ColdFusion.
