### ISSUE TITLE
Automatically signing into Identity Server 3 using Windows Authentication

### ISSUE THREAD

**Issue by RangerDunadan** [IdentityServer/IdentityServer3#2503]
Thank you for making IdentityServer3.  It is a wonderful project!

I have been able to setup IdentityServer3 as well as a WS-Federation server running as an external provider to sign into windows.  I can allow a user to enter a username and password if they aren't part of the domain or click the Windows button in the External Login section.  This works great!

What I would like to do is have a way to ask the Identity Server to automatically try to login using Windows Authentication and then if that doesn't work then present the login screen.  For end-user support purposes it would be nice if support staff could impersonate another user --- even if their computer is part of the domain.  So perhaps being able to specify from the client (OidcManager?) what the default provider is and essentially activate it when the Identity Server Login page presents itself.  A button could be added that would change the default provider and allow the support staff to enter different credentials.

Another idea I had (I don't know if will work) is to add some new JavaScript to the Login page or override the Login page using the DefaultViewServiceOptions or DefaultViewService options.  The JavaScript would simply "click" Windows button.

Does this make sense?  Is there a better solution?  Is it possible to do what I'm suggesting?

Thank you!

Ranger

**Comment by brockallen** [comment]
You could try to make a request an in `<iframe>` from the client to IdSvr passing an `acr_values=idp:windows` and see if that returns success in a reasonable amount of time (~5s). If not, then they're not logged in via windows auth, so then you could make a normal request to IdSvr for authentication.

There might be other approaches.

**Comment by RangerDunadan** [comment]
Thank you!  This was exactly what I needed and seems to have solved the problem.

**Comment by AhmedAbouElnour** [comment]
Hi,
Thanks a lot for this project. It simplified the most complicate part of my life (Security!)
I might be coming late to the party but I'd appreciate if Ranger or Brock could leave an example.
Currently I am using the built-in html. Could you point me to a way to implement the same feature?
Thanks again!
