### ISSUE TITLE
Correct flow for an android/ios app?

### ISSUE THREAD

**Issue by spinacius** [IdentityServer/IdentityServer3#2505]
Hi there!

The picture:
1) an identity/authorization server that i control (built on IdentityServer3)
2) a mobile app that i control (android/ios)

Is implicit flow a good fit? Or should i go for client-credentials grant? (And why)?

Thanks in advance

**Comment by leastprivilege** [comment]
http://leastprivilege.com/2016/01/17/which-openid-connectoauth-2-o-flow-is-the-right-one/

**Comment by spinacius** [comment]
Thanks for the link!
