### ISSUE TITLE
Q: Resource scopes and claims

### ISSUE THREAD

**Issue by danielwertheim** [IdentityServer/IdentityServer3#2506]
I'm probably thinking all wrong here... but.

**Scenario:**

1. API e.g. *"testapi"* is defined as a `resource scope`. The API in it self needs some claims for a user, both standard claims (`openid`, `email`) and custom (`custom1`).

2. App e.g. *"myapp"* is going to make impersonated calls against *"testapi"*, so `identity token` and `access token` with scopes: `openid`, `email` and `testapi`; is requested/constructed and the access token is used to call the API.

It would be nice if you could **define** `Scope Claims` for `resource scopes`. That way, you could create reusable app specific bundles, where you see that the resource scope needs these claims, and when that scope is included to create the access token, the API can define it's resource scope as a requirement and know that the requested claim types will exist. As of now, this has to be a specific *"plain"* scope that bundles the claims.

**Comment by leastprivilege** [comment]
I am not sure I follow - you can define scope claims for resource scopes.

**Comment by danielwertheim** [comment]
Yes, but those does does not seem to be included in the token.

I have defined a resource scope with some claims. Then basically following your sample to secure a MVC application. Since I want a resource scope, I need to request with `ResourceScope="id_token token"`. Then I need to use the `access token` to lookup user info, the claims returned does not contain the claim types defined by the resource scope, only claim types defined by non resource scopes.

**Comment by brockallen** [comment]
If the client app needs the claims, those need to be modeled in an Identity scope. If the API needs the claims those need to be modeled in a Resource scope.

**Comment by danielwertheim** [comment]
You are right, when using your middleware (IdentityServer3.AccessTokenValidation) it does that.

Last Q. In that flow, I did extract the access token and used that for calling the user info endpoint, and then I didn't get all the associated claims. Is that expected behaviour?

**Comment by leastprivilege** [comment]
UserInfo is an OIDC concept - the endpoint will return all claims associated with identity scopes in the access token.
