### ISSUE TITLE
GetSignoutMessageId returns null when attempting to make Post Logout Redirect work for upstream idp

### ISSUE THREAD

**Issue by davebown** [IdentityServer/IdentityServer3#2508]
I'm attempting to following the approach written here: https://identityserver.github.io/Documentation/docsv2/advanced/federated-post-logout-redirect.html

But I have an issue when attempting to store the 'state' cookie in the RedirectToIdentityProvider delegate  as stated doesn't work because the call to GetSignOutMessageId() returns null. I can see in your code this looks for an id parameter in the query string of the logout page but i can also see this isn't being passed to the logout page in the first place. Why would this be? Is this a configuration issue?

**Comment by davebown** [comment]
Ok in the end I worked out why the id wasn't been sent being due to the Token Validation failing which was due to a dodgy implementation of IsActiveAsync in the UserService not handling the fact that some claims transformation takes place in the GetProfileDataAsync method, so while it works at login, subsequently it does not.

So now i'm getting a message id but my call to RenderLoggedOutViewAsync in my implementation of signoutcallback returns a blank screen and doesn't redirect to the requested post logout url. 

I'll keep investigating but if you have any ideas about the cause of this, i have no errors in my log4net table now!

**Comment by davebown** [comment]
Ok that didn't take long, turns out i mapped the signoutcallback handler into my root app builder rather than the identity server one. Doh!

Everything is working now. I'll close this.

**Comment by Steve887** [comment]
I'm having the same issue, but as far as I can tell my IsActiveAsync method is working correctly (using Membership Reboot).

Was there anything in particular you change in that method to get it to work?

**Comment by davebown** [comment]
Hi,

No I looked through the logic on the end session endpoint in the identity server code and realised that there would be no signoutmessage if the  EndSessionRequestValidator failed. This led me to examine my logs looking for various messages found in the code and I found the problem. You can always check through the steps carried out by https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/EndSessionRequestValidator.cs and it's various sub methods and eliminate them one by one.

I'd say likely problems are that you are not sending the id token hint or your post logout redirect uri is not specified in the client. Failing that your id token hint could be failing validation.
