### ISSUE TITLE
Database that IdentityServer3 uses

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2510]
We use Cassandra as our business DB. Does IdentityServer3 use its own DB for storing its system configuration ? Does it need a DB ? My assumption is that it doesn't and can work with our Cassadra using the 'User Service'.

**Comment by brockallen** [comment]
Please read the docs: 

https://identityserver.github.io/Documentation/docsv2/configuration/inMemory.html

https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html
