### ISSUE TITLE
SSO, show login page instead of Error page when unauthorized user try to access Clients?

### ISSUE THREAD

**Issue by dgs-hassaan786** [IdentityServer/IdentityServer3#2511]
Hi, I have been using identity server for single sign on using form post. My current scenario is that:
I have 2 Clients:

`User A`  is assigned `Client1,Client2`
`User B` is assigned `Client2` only.

The Clients are web application. As web initially renders it redirect to login page. 
The Single Sign On works perfectly for `User A`. But as soon as `User B` logins `Client2 `and tried to go to `Client1`. The authorization attributes implementation redirects it to login page for `Client1` and then `identity server` try to login the `user B` as it is already login to `Client 2`. but as the application rights are not assigned to `User B` to access `Client 1`, The identity server delivers it to error page.

I here want to implement the flow that If the Client Application rights are not assigned then the identity server show login page option rather than throwing it to error page. Same Flow as office365 to outlook.

Any help, 
thanks in advance

**Comment by leastprivilege** [comment]
Why would that be the job of the authentication service?
