### ISSUE TITLE
"Grant Type Missing" when trying to use refresh token

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2512]
Hey guys, i'm trying to hit the token endpoint to get a new token using the refresh token, but i keep getting the error `unsupported_grant_type.`

logs show: `Grant type is missing`

here's my raw request in Postman

> POST /core/connect/token?grant_type=refresh_token&refresh_token=XXX HTTP/1.1
> Host: localhost:44303
> Authorization: Basic XXX
> Accept: application/json
> Cache-Control: no-cache
> Postman-Token: 66c1fd18-6c94-6539-325d-2dcf56cd66b0
> Content-Type: application/x-www-form-urlencoded
> 

It's like it's not picking up the grant_type parameter? when i use the TokenClient library it works fine... so not sure what i'm missing...

Further debugging has found `HostDataProtector.Unprotect` throwing error "The data is invalid"... this is not logged, so the error is being swallowed, nothing being passed to parameters and it's just by chance the "grant_type" is the first thing that is checked in the `ValidateRequestAsync method`. So it's kind of a false error... (i would expect some other error to be shown, such as "no parameters").

i'm using code flow - is it because the initial token is being received via the web/redirect flow, then i'm simply trying to use that refresh token in Postman (so it's a different client?). i wouldn't think that would matter... the POST data seems fine...

Any ideas? Thanks

**Comment by brockallen** [comment]
They must be sent in the form-urlencoded body.

**Comment by RPM1984** [comment]
@brockallen what does? the URL parameters? Can you provide an example of what my request _should_ look like?

**Comment by brockallen** [comment]
https://tools.ietf.org/html/rfc6749#section-4.1.3

**Comment by RPM1984** [comment]
@brockallen got it, thanks. Worth adding a note to the [Token Endpoint](https://identityserver.github.io/Documentation/docsv2/endpoints/token.html) doco to state that? Happy to submit a PR..

**Comment by leastprivilege** [comment]
There's an example at the bottom.
