### ISSUE TITLE
working perfect on local but throws 401 when the identity server is hosted on a different server

### ISSUE THREAD

**Issue by jothikiruthika-jltasia** [IdentityServer/IdentityServer3#2513]
I have hosted my implementation of idserver in my local iis and there is a local web site consuming it. All is well on the local, but when i use the id_token from an identityserver3 hosted on a differnt server, i get a 401. From the katana logs i get the following error as a reason for the 401.

Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Warning: 0 : expired bearer token received

Below is how the authentication is wired at the website end.
app.UseJwtBearerAuthentication(
                new JwtBearerAuthenticationOptions
                {
                    AuthenticationMode = AuthenticationMode.Active,
                    AllowedAudiences = new[] { PublicClientId },
                    IssuerSecurityTokenProviders = new IIssuerSecurityTokenProvider[]
                    {
                        new OpenIdSecurityTokenProvider(OpenIdConfig)
                    },

 //TokenValidationParameters = new TokenValidationParameters() { RequireExpirationTime = false }
  });

i tried to set the RequireExpirationTime  to false in the token TokenValidationParameters , this now returns a new error - is it related to certificate used for signing? I have created a certificate and used it on the identityserver for signing the jwttokens

Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Error: 0 : Authentication failed
System.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
    (
    IsReadOnly = False,
    Count = 2,
    Clause[0] = X509ThumbprintKeyIdentifierClause(Hash = 0x9A8D62CDE2087BC8965920E3E68063B2474AFE74),
    Clause[1] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
    )
', 
token: '{"typ":"JWT","alg":"RS256","x5t":"mo1izeIIe8iWWSDj5oBjskdK_nQ","kid":"mo1izeIIe8iWWSDj5oBjskdK_nQ"}{....} at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 943
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 671
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()

**Comment by leastprivilege** [comment]
Have you tried our token validation middleware. Makes configuration much
easier
-- 
Dominick Baier

**Comment by jothikiruthika-jltasia** [comment]
No Dominick. Do u mean using app.UseIdentityServerBearerTokenAuthentication? I havent tried that yet. Will give it a shot

**Comment by jothikiruthika-jltasia** [comment]
`app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://myserver/identityserver/core",
                RequiredScopes = new[] { "openid", "roles" },
                ValidationMode = ValidationMode.Local,
            });`


my error now is : IDX10214: Audience validation failed. Audiences: 'client-id'. Did not match:  validationParameters.ValidAudience: 'https://myserver/identityserver/core/resources' or validationParameters.ValidAudiences: 'null'

**Comment by leastprivilege** [comment]
Are you sending the id_token? you need to send the access token.

**Comment by jothikiruthika-jltasia** [comment]
oops! I am sending the Id_token. I was under the impression that my access token will be used only if i have to delegate the end user's identity to another API. 

My actual flow here is ->
implicit flow. obtain the id_token through a javascript, and send it to the website. I was assuming that the id_token must be presented to the website and access token is to be used only when we need to delegate the end user's identity to another api say EmployeeApi which would be called by the website

**Comment by leastprivilege** [comment]
The id_token represents the outcome of the authentication handshake. It is the job of the authentication initiator to validate it and establish its own authentication session. Access tokens are for accessing resources.

**Comment by jothikiruthika-jltasia** [comment]
Hi Dominick, We finally figured the issue. The wire up is as below

` app.UseJwtBearerAuthentication(
                new JwtBearerAuthenticationOptions
                {
                    AuthenticationMode = AuthenticationMode.Active,
                    AllowedAudiences = new[] { PublicClientId },
                    IssuerSecurityTokenProviders = new IIssuerSecurityTokenProvider[]
                    {
                        new OpenIdSecurityTokenProvider(OpenIdConfig)
                    },
RequireExpirationTime = false }
                });`

The error that i receive is 

`Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Warning: 0 : expired bearer token received`

The same piece of code works fine, that is authentication passes when both the idserver and the web application are hosted on the server.

when we moved the idserver to a different server, the new server is behind our local machines by 6 minutes. And the value of IdentityToekLifeTime for this client in the DB is 300. When i change this value to 600, the authentication is successful. 

Please advise how to handle such scenarios when the time on the web application server and the identity server are different

**Comment by leastprivilege** [comment]
Again - you don't pass the identity token. That's for the client - not the api/backend.

By default - only a time skew of 5 minutes is allowed. You can reconfigure the MS MW somehow (somewhere on the options).

**Comment by jothikiruthika-jltasia** [comment]
Hi Dominique, the default time out can be changed in the client settings. For each client the access token life time and the identity token life time can be changed. Thanks for the pointer. 

We are now using the access tokens and things are fine. 

We are using a javascript client. We simply get the access token and utilize it. We don't use the access token at all. Is this design semantically correct? ignoring id_token, is this right or are we missing something here. Please advise

**Comment by brockallen** [comment]
> We are using a javascript client. We simply get the access token and utilize it. We don't use the access token at all.

What does this mean? You "utilize" it, but don't "use" it"? That's confusing.

**Comment by jothikiruthika-jltasia** [comment]
Corrected the typo. We just get the access token and use it. we dont use the id_token at all.

**Comment by leastprivilege** [comment]
please open a new issue for new questions.
