### ISSUE TITLE
Login using popup, <iframe> for Hybrid flow

### ISSUE THREAD

**Issue by dunglp** [IdentityServer/IdentityServer3#2514]
Hi @leastprivilege, @brockallen. Thanks for making awesome IdentityServer3. 
I am having difficulty dealing with an issue: is it possible to implement a login form using Identityserver3 in a popup or a `<iframe>` ?

Please give me some advice for this issue.
Thanks and Best Regards

**Comment by leastprivilege** [comment]
we don't allow embedding the login page into an iframe. that is a security risk.

**Comment by dunglp** [comment]
Thanks a lot @leastprivilege. 
So the only solution is redirect to IdSv. I will head this way.
