### ISSUE TITLE
[Request] Workaround for the OWIN cookie lost problem

### ISSUE THREAD

**Issue by TheAndroidMachine** [IdentityServer/IdentityServer3#2515]
As you already know there is a conflict between the OWIN Cookie API and the System.Web when it comes to handling the response cookies. Under certain circumstances the response cookies created with the OWIN API could be lost because of this bug. You can find more details here:
http://stackoverflow.com/questions/20737578/asp-net-sessionid-owin-cookies-do-not-send-to-browser
and here:
http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues&referringTitle=Documentation

There is a UseKentorOwinCookieSaver middleware that should solve the problem but I have already tried it and it only works for some cases and creates other problems.

I’m aware that it is not an IdentityServer problem but since IdentityServe relies heavily on cookies and most of us is hosting in an IIS, it would be convenient if you could provide us with a way to work around this problem. 

I would propose a path similar to the one proposed by the Katana team here:
http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues&referringTitle=Documentation

The idea is to abstract the management of the cookies with a service/interface like the ICookieManager Interface (https://msdn.microsoft.com/en-us/library/microsoft.owin.infrastructure.icookiemanager(v=vs.113).aspx) and provide a default implementation that uses the OWIN API so there is no new dependencies nor breaking changes. IdentityServer should use this service/interface everywhere when creating, reading or deleting cookies.
If someone want to host in an IIS he/she should provide and register an implementation that uses the System.Web's cookie collection.

I believe this only way we can be 100% sure, that no cookie will be lost.
Thoughts?

**Comment by brockallen** [comment]
I'd ask what types of cookies are you adding to the IdSvr pipeline from System.Web-based code?

**Comment by TheAndroidMachine** [comment]
I don’t add any cookie to the IdSrv pipeline. I only add cookies in the MVC part of the application using the OWIN API. But there is the ASP .Net Session cookie and the Affinity cookie set by Azure in the cloud. These two cookies are set with System.Web-based code and are (sometimes) causing the loss of the “OWIN response cookies” that are created in the same request.
The problem is very hard to reproduce but is definitely there. One example I cloud give you is when a user access the website for the first time. I have seen that sometimes the SignIn cookie is not returned when the IdSrv Authorize endpoint redirect to the Authentication controller. This cause of course a “There is an error determining which application you are signing into. Return to the application and try again.” error.

**Comment by brockallen** [comment]
> But there is the ASP .Net Session cookie and the Affinity cookie set by Azure in the cloud. 

Yes, so this is a http module which runs at the same time as the OWIN pipeline. That's what I Was trying to ask about.
