### ISSUE TITLE
Windows authentication as local login

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer3#2516]
Hi.
Is possible to create windows authentication as local login? I don't want to use the external logins only windows authentication.
Thanks.

**Comment by leastprivilege** [comment]
You can write code to authenticate against windows in the UserService.

**Comment by Jenan** [comment]
I have a question about architecture - Can I have an identity server and a web api on different server?

**Comment by leastprivilege** [comment]
Yes - that's the default architecture.

**Comment by Jenan** [comment]
How's web api's side can recognize that token is valid? I have to deploy to web api the certificate?
