### ISSUE TITLE
Error 400: Bad Request - Request Too Long still an issue

### ISSUE THREAD

**Issue by johnproctor** [IdentityServer/IdentityServer3#2518]
Apologies for raising this issue again.  I've followed all the advice for dealing with this issue but I'm still seeing the problem on our dev and uat environments.  We are due to go live with a new system that is using Identity Server next month.  We are on ASP.Net 4.5.

The symptom is the browser looping between the site and STS with an increasing URL until the Request Too Long error occurs.  The URL looking like:

https://uat-login.mysite.com/core/connect/authorize?client_id=darwin&redirect_uri=https%3a%2f%2fuat-site.mysite.co.uk%2fAccount%2fRedirectToDashboard&response_mode=form_post&response_type=code+id_token+token&scope=openid+email+roles+offline_access&state=OpenIdConnect.AuthenticationProperties%3dThtPVpzMyrgpX0cFLFl4iPToUPvPM10UkQpEzcoLoHwO3ha4P2ZYDUJKHYmyi4K1iV-Szd0pT7sIerkMjqMId69Cw3k3_mv9ikbszW1SFUBa__BaEdzmLR0GjNFQD4euq95SRkA6Nputzctu4vHERuCJ8HM9l3F8Z78AH7wHFLo2KOWLytiaKiT0U5zzwrGEHpi1eBFKX74qhsqpuMhUdqNEAUhYM0S90xUOUajO6tAA3Kp2yZwk0A-6jdPIdLVTz6aw8Muurw2wJbSZVcpOmw&nonce=635900019377111618.ODIyYzg0MjQtYjYxZS00NDIyLWI2Y2MtOTE1OWY0NjBhYjk2YjE1ZWQ2ZmItNjUyZC00Zjk4LWFhOWItYjIzNzRiNWU3YzRj

I have tried implementing SignInThreshold in the IdentityServerOptions:
SignInMessageThreshold = 2

I've also tried implementing a Custom Cookie Manager, as per:
http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues&referringTitle=Documentation

Is there anything else I'm missing or should be doing?  Please let me know if you need further information.

**Comment by brockallen** [comment]
SignInMessageThreshold is unrelated to the length of the URL on the authorization request.

**Comment by johnproctor** [comment]
Sorry, I must have misunderstood the effect of that setting.  However, my question still stands.  

I've downgraded Microsoft.Owin.Security.OpenIdConnect to version 3.0.0 and implemented the custom cookie manager in the client application and am still seeing the Bad Request error.

Are there any other steps I should be taking?

**Comment by brockallen** [comment]
Search the archives on URLs being too long -- we've provided guidance in the past in those questions.

**Comment by callranjithkani** [comment]
Hi,

Have you got answer, me too face this same issue, my sso proxy developed by asp.net core and few client applications also developed by core, if i try to implement 4.5.2 developed client app i faced Bad Request - Request Too Long Error, have any idea please let me know

**Comment by brockallen** [comment]
There are extensibility points in the various MS middleware for storing the state server side, rather than in the QS param. Check the MSFT docs.
