### ISSUE TITLE
Refreshing claims in Implicit Flow?

### ISSUE THREAD

**Issue by wziska** [IdentityServer/IdentityServer3#2519]
Hi, I have a quick question:
Is it possible to refresh users claims when generating a new token the same way as it's done in ProcessRefreshTokenRequestAsync with UpdateAccessTokenClaimsOnRefresh option enabled?
Basically I need to regenerate some of claims each time Javascript client (SPA) asks for a new token, but because I'm using Implicit flow I can't use refresh token, so can't use the option above.
Thanks.

**Comment by wziska** [comment]
Now I think I need something more. I want to refresh user claims, but not just for the access token, but for user logged in Id Server, so next time access token is generated I'll have updated user claims. Is it even possible to change user claims after user is authenticated?

**Comment by leastprivilege** [comment]
Every time you request a token, the `GetProfileDataAsync` method is invoked - which in turn returns the claims for the token. You have full control over that.

**Comment by wziska** [comment]
But in `GetProfileDataAsync` method `context.Subject.Claims` are already there. And I want to refresh these claims, so next time `GetProfileDataAsync` is called, I'll have new claims. Now I always get original claims generated during `AuthenticateLocalAsync` call.

**Comment by leastprivilege** [comment]
True. But the subject claims are just the claims in the cookie. You can return whatever you want from there.

To get a new cookie the user has to re-authenticate.

**Comment by wziska** [comment]
Oh, I was afraid of that :) 
But what do you mean that I can return whatever? What place are we talking about?

**Comment by wziska** [comment]
Generally what I need to achieve is to generate some data at `AuthenticateLocalAsync` (because I need user credentials) and then access, update and return this data as a claim on following create access token requests. Now it seems putting this data as a claim in Principal was not a good idea, because there is no way to update it. Do you have any idea what could be appropriate solution for such scenario?
Thanks.

**Comment by leastprivilege** [comment]
then store it in a database at authN time and retrieve when the profile data is retrieved.

**Comment by wziska** [comment]
By storing in DB you mean some custom implementation or can I use some existing Id Server features for that?

**Comment by leastprivilege** [comment]
some custom data store.

**Comment by wziska** [comment]
OK, that would work. I've already drifted away from original problem, but let me ask one more question. I'm thinking if I can use token (access or Id, not sure which one) for storing this data as custom claim. The problem is how can I access current access token when client is asking for a new one?

**Comment by leastprivilege** [comment]
Asking for a token does not involve sending the old one. All you can see is the contents of the cookie (the subject).

**Comment by wziska** [comment]
Many thanks! Now it's clear to me what happens on IdS side.
