### ISSUE TITLE
integration tests for PKCE

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#2520]

**Comment by mderriey** [comment]
Are you looking at creating integration tests as you did in the ASP.NET Core repo or an end-to-end test scenario with an authorize request followed by a token request? I'll be happy to contribute to this one, too, if that's OK.

**Comment by mderriey** [comment]
Sorry, I feel the previous message wasn't clear. Are you looking at creating a specific integration tests project like for IdSrv4 or  create such tests in the existing project?

**Comment by brockallen** [comment]
We want tests in both, but we need to start here (IdSvr3). So yes, integration tests like the ones we have here in the ~/conformance folder.
