### ISSUE TITLE
The id_token returned from code flow has audience 'identityserver/resources'.

### ISSUE THREAD

**Issue by smiket** [IdentityServer/IdentityServer3#2521]
I'm using a code flow, and after redeeming the code, I get a successful response with id token etc.
The audience in the id_token indicates it is for the identity server (e.g. idserver/resources).
However the spec says audience should be my client id - can you help me understand?
http://openid.net/specs/openid-connect-basic-1_0.html#IDToken

Thanks,
Steve

**Comment by leastprivilege** [comment]
I think you are looking at the wrong token.

**Comment by smiket** [comment]
Thank you Brock,

In the identity server log:

2016-02-03 20:14:24,954 [20] DEBUG IdentityServer3.Core.Services.Default.DefaultTokenService [(null)] - Creating JWT access token
.........
2016-02-03 20:14:24,969 [20] DEBUG IdentityServer3.Core.Services.Default.DefaultTokenService [(null)] - Creating JWT identity token
........
"Body": "{\"id_token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUz...

In my code, I construct a response object as such:
public AccessTokenResponse(JObject obj)
{
    IdToken = obj.GetValue<string>("id_token");
    AccessToken = obj.GetValue<string>("access_token");

Finally, I decrypt the id token using the cert returned from the jwks endpoint, having the matching kid.
Once the id_token is decrypted, the aud value is for identity server (not my client id).

Seem right?

**Comment by smiket** [comment]
I had a bug - you were right!
Sorry about that, and thanks for the help.
