### ISSUE TITLE
Cassandra DB for IdentityServer3

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2522]
I refer to http://weblogs.thinktecture.com/cweyer/2013/01/running-thinktecture-identityserver-v2-in-a-windows-azure-web-role-from-zero-to-hero-a-walkthrough.html. I substitute v3 for v2.The only difference I see is the DB string for Cassandra. I think I have to get the Cassandra driver and update by nuget packages and then publish to Azure. Is that right ? Is there a precedent for this type of Cassandra access ?

**Comment by leastprivilege** [comment]
I am not aware of a Cassandra implementation for IdentityServer3. But feel free to write one and put up a contrib project.

**Comment by mohanr** [comment]
My question may be based on a misconception. So I will try again based on these two points.

1. When I publish IdentityServer3 to Azure IdentityServer3 needs a DB. The link I referred to mentions SQL Server. There is a DB connection string which has to be configured. 

2. Our business DB is Cassandra. So we will use a Custom User service to connect to Cassandra to fetch user details like passwords, roles, scopes etc.

Does IdentityServer3 need SQL Server for its own purpose ? Does it need its own DB at all ?

**Comment by leastprivilege** [comment]
We don't expect any specific database technology. You need some data store for your users, configuration and state. Which one you use is totally up to you.

We have an implementation for EF. There are also some contrib projects. You can adapt to an arbitrary data store by impementing our store interfaces.

**Comment by mohanr** [comment]
So this is a basic question from a user. I don't understand.

I thought this sentence means that the server needs a SQL database.

"Let's attack the database side of things. We need a SQL database for our identity configuration and data. I am going to create a new one via the Windows Azure management portal:"

If I replace the SQL server connection string with my Cassandra connection string it wouldn't work. Is that right ?

I have a cassandra cluster in Azure. Now I am trying to publish IdentityServer3. What DB connection string should I use ?

**Comment by leastprivilege** [comment]
You are referring to a blog post about IdentityServer2 - you are in the issue tracker of IdentityServer3.

Things have changed since 2013. You need to write code now to connect to data stores (unless you find a Cassandra implementation out there).

**Comment by mohanr** [comment]
Can I see an IdentityServer3 Azure deployment guideline ?

**Comment by leastprivilege** [comment]
IdentityServer3 is just a DLL.  You build the application around it yourself and just deploy that to wherever you want as usual.

The samples repo has lots of samples how such hosts would look like. There is also a deployment section in our docs.

**Comment by mohanr** [comment]
Ok. Let me follow the same instructions to publish it as a cloud service. So if I don;t use the DB connection string it would use the supplied in-memory stores until I code my Cassandra code. Does that make sense ?

**Comment by leastprivilege** [comment]
the instruction you are referring to are outdated. I would suggest you start reading the docs and check the samples and then come back with more specific questions when they arise.
