### ISSUE TITLE
How to access claims from Handler

### ISSUE THREAD

**Issue by RaviKaruturi** [IdentityServer/IdentityServer3#2523]
I am able to get an access token containing claims from idSvr. Is it possible to access those claims(for Ex: client_id) on the resource server from an webApi Handler before hitting the controller action? If not, are there any other ways to do this?
I am able to access claims as mentioned in docs inside controller action.

**Comment by RaviKaruturi** [comment]
I am able to access claims from handler using 
request.GetOwinContext().Authentication.User.Claims
Is it the right way to access claims?

**Comment by leastprivilege** [comment]
that's OK.
