### ISSUE TITLE
UserService - Method GetProfileDataAsync not populate claims to API

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer3#2525]
I've tried to implemente the UserService for LocalLogin against to Windows Authentification. 

I downloaded the project with Indentity Server Samples (Clients) and started with project using "implicitclient" - JavaScript Implicit Client - TokenManager.

When I run all project and I loggin successfully and then I call the method for getting access token and profile Info. Access token is correctly loaded but method "GetProfileDataAsync" is called twice and secondly is context.Subject.Identity.Name NULL and in web api's side is principal.Identity.Name and Claims not contain email, name etc. (without user information).

BTW: First call of GetProfileDataAsync is absolutly correct - context.Subject.Identity.Name has right value but twice call not.

What can I change on my scenario?

```
public void Configuration(IAppBuilder app)
        {
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://localhost:44333/core",
                    RequiredScopes = new[] { "write", "email", "profile" }
                });

            app.UseWebApi(WebApiConfig.Register());
        }

[Authorize]
	public class IdentityController : ApiController
	{
		public dynamic Get()
		{
			var principal = User as ClaimsPrincipal;

			var name = principal.Identity.Name; //NULL


			return from c in principal.Claims
						 select new
						 {
							 c.Type,
							 c.Value
						 };
		}
	}
```

```
public override Task GetProfileDataAsync(ProfileDataRequestContext context)
		{
			try
			{
				using (var pc = new PrincipalContext(ContextType.Domain))
				{

					if (context.Subject.Identity.Name == null) return Task.FromResult<IEnumerable<Claim>>(null);

					using (var user = UserPrincipal.FindByIdentity(pc, IdentityType.SamAccountName, context.Subject.Identity.Name))
					{
						if (user == null) return Task.FromResult<IEnumerable<Claim>>(null);

						var identity = new ClaimsIdentity();

						identity.AddClaims(new[]
						{
						new Claim("name", user.DisplayName),
						new Claim("email", user.EmailAddress)
					});

						context.IssuedClaims = identity.Claims;

						return Task.FromResult(identity.Claims);
					}
				}
			}
			catch
			{
				return Task.FromResult<AuthenticateResult>(null);
			}
		}
```

```
public override Task GetProfileDataAsync(ProfileDataRequestContext context)
		{
			try
			{
				using (var pc = new PrincipalContext(ContextType.Domain))
				{

					if (context.Subject.Identity.Name == null) return Task.FromResult<IEnumerable<Claim>>(null);

					using (var user = UserPrincipal.FindByIdentity(pc, IdentityType.SamAccountName, context.Subject.Identity.Name))
					{
						if (user == null) return Task.FromResult<IEnumerable<Claim>>(null);

						var identity = new ClaimsIdentity();

						identity.AddClaims(new[]
						{
						new Claim("name", user.DisplayName),
						new Claim("email", user.EmailAddress)
					});

						context.IssuedClaims = identity.Claims;

						return Task.FromResult(identity.Claims);
					}
				}
			}
			catch
			{
				return Task.FromResult<AuthenticateResult>(null);
			}
		}
``

**Comment by leastprivilege** [comment]
You only have the contents of the cookie for front channel request. For back-channel requests there is no cookie and all you have is the subject id.

IIRC There is a setting called LoadUserProfile in the token manager - try turning that off.

**Comment by Jenan** [comment]
How can I only work with subject id? I need get the claims and loginname in API. Is possible in this scenario?

**Comment by leastprivilege** [comment]
The subject id must be enough to get to all additional data in your system.

**Comment by Jenan** [comment]
When I want to get user information from web api controller - is possible only with subject id? If I understand correctly then I have to save user information about user in my database? I want to contact directly from web api idsrv and get userinfo - like loginname etc.

**Comment by leastprivilege** [comment]
either you put that data into the access token directly - or you get it via the userinfo endpoint.

Either way you probably need some form of persistence for profile data.

**Comment by Jenan** [comment]
Yes, Now I correctly create new scope for API where I include the required information and I can read these information from claims on api's side. Thanks for your time.

**Comment by Jenan** [comment]
Additional question - How works mechanism of decrypt access token on api's side?

**Comment by brockallen** [comment]
> Additional question - How works mechanism of decrypt access token on api's side?

Check the docs and samples. If you have new questions, open new issues.
