### ISSUE TITLE
Okta as IdP within IdentityServer3- Saml Token Issue

### ISSUE THREAD

**Issue by breddynet** [IdentityServer/IdentityServer3#2526]
I have setup everything and i am able to call the okta from Identityserver and comeback to the return url but my saml2 token coming in formdata how to get that data in client side 

i have folllowed this help 
https://github.com/KentorIT/authservices/blob/master/doc/IdentityServer3Okta.md

function getToken() {
            var authorizationUrl = 'https://localhost:44300/identity/connect/authorize';
            var client_id = 'carbonimplicit';
            var redirect_uri = 'http://localhost:48249/index.html';
            var response_type = "token";
            var scope = "api1";
            var state = Date.now() + "" + Math.random();

            localStorage["state"] = state;

            var url =
                authorizationUrl + "?" +
                "client_id=" + encodeURI(client_id) + "&" +
                "redirect_uri=" + encodeURI(redirect_uri) + "&" +
                "response_type=" + encodeURI(response_type) + "&" +
                "scope=" + encodeURI(scope) + "&" +
                "state=" + encodeURI(state);
            window.location = url;
        }

**Comment by breddynet** [comment]
url : http://localhost:48249/index.html#access_token=d0017029438cab7c41522ff3b48704a7&token_type=Bearer&expires_in=3600&scope=api1&state=14545851285210.10643220506608486

{
  "access_token": "d0017029438cab7c41522ff3b48704a7",
  "token_type": "Bearer",
  "expires_in": "3600",
  "scope": "api1",
  "state": "14545851285210.10643220506608486"
}

access_token to be saml i can see that in formdata

**Comment by leastprivilege** [comment]
The whole point of idsrv is to bridge the protocols. We convert the SAML to a JWT/reference token.

If you want the original SAML token - why don't you use the SAML protocol directly?
