### ISSUE TITLE
How to implement IAuthenticationSessionValidator to validate against database session?

### ISSUE THREAD

**Issue by hanswolff** [IdentityServer/IdentityServer3#2527]
I'm currently implementing database authentication session handling into our Identity Server (using most recent NuGet package v2.4.0).

In order to validate the authentication cookie on identity server I need to implement an IAuthenticationSessionValidator.IsAuthenticationSessionValidAsync(ClaimsPrincipal subject).

The problem is to match the database session created with IAuthenticationSessionStoreProvider.StoreAsync(AuthenticationTicketModel ticket).

The best solution is to use a special claim to transport the session id to the ClaimsPrincipal. Is there any better way to do this?

**Comment by brockallen** [comment]
We left this pretty open, so that sounds like it would work. You'd issue some claim from your user service, and then check it in the IsAuthenticationSessionValidAsync -- the same ClaimsPrincipal you get in this method is the same one you're creating from the user service.

**Comment by hanswolff** [comment]
I have implemented the interfaces and it works like charm, thanks!

**Comment by brockallen** [comment]
Good to hear, thanks.
