### ISSUE TITLE
XHR Cors problem

### ISSUE THREAD

**Issue by spinacius** [IdentityServer/IdentityServer3#2528]
Hi!
I am trying to setup an implicit flow on a javascript client.

In the startup configuration of the IdentityServer i have enabled CORS for every origin:

```
public void Configuration(IAppBuilder app)
        {
            app.Map("/identity", idSrvApp => 
                idSrvApp.UseIdentityServer(new IdentityServerOptions()
                {
                    [..]
                    Factory = InMemoryFactory.Create(
                        users: Users.Get(),
                        clients: Clients.Get(),
                        scopes: Scopes.Get()
                    ),

                    SigningCertificate = LoadCertificate(),

                    // For cross origin request, allow all for testing
                    CorsPolicy = CorsPolicy.AllowAll,

                    [..]
                }
            ));
        }
```

I have also enabled cors for the specific client:

```
new Client
                {
                    Enabled = true,
                    ClientName = "JS OAuth Client",
                    ClientId = "js_oauth",
                    Flow = Flows.Implicit,

                    RequireConsent = true,

                    RedirectUris = new List<string>
                    {
                        "http://localhost:4500"
                    },

                    AllowedCorsOrigins = new List<string>
                    {
                        "http://localhost:4500/"
                    }  
                },

```
My problem is when i try to make an XHR requests for id_token and access_token to the authorization endpoint i get: "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4500' is therefore not allowed access. The response had HTTP status code 405."

The uri that i create for the request is correct, i pass all the required parameters: state, nonce, client_id, response_type, redirect_uri, scope. If i use this uri with a standard javascript redirect using window.location it works as expected showing the required consent view on the IdentityServer, but with XHR it gives me the CORS error reported above.

Any hint about how to fix this?

Thanks in advance, cheers!

**Comment by brockallen** [comment]
If the server returns 405, then CORS won't work regardless what you have in IdSvr (or any other CORS framework). Why are you getting 405?

**Comment by spinacius** [comment]
I had a little problem in the AJAX request, automatically passing 'OPTIONS' instead 'GET' as http method. Anyway now i'm sending a correct get request, but i get in response: '_No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4500' is therefore not allowed access'_.
I don't know what could be the problem, i've allowed all the possible origins in the IdentityServer.

**Comment by brockallen** [comment]
What endpoint in IdSvr are you trying to make an ajax call to?

**Comment by spinacius** [comment]
This is the endpoint i am using:
https://eresult-idserver.azurewebsites.net/identity/connect/authorize

This is the complete uri for the ajax call:
https://eresult-idserver.azurewebsites.net/identity/connect/authorize?state=12406110695884346&nonce=6409183445363346&client_id=js_oauth&redirect_uri=http%3A%2F%2Flocalhost%3A4500&response_type=id_token%20token&scope=openid%20profile%20api_scope

**Comment by brockallen** [comment]
Ajax calls to the authorize endpoint are not supported.

**Comment by spinacius** [comment]
Ah ok, didn't know it thanks! 
So i have to use standard redirection or there are other ways to complete the flow? I plan to set *RequireConsent = false*, so no need for the consent view.

**Comment by leastprivilege** [comment]
Yes - you need to use the "front channel".

**Comment by spinacius** [comment]
Ok, thank you for the informations!

**Comment by aliniacobv** [comment]
Did something changed in the mean time? Ajax calls to the authorize endpoint are still not supported?
Thanks.

**Comment by brockallen** [comment]
Perhaps this is an issue to open in IS4.

**Comment by udayb2014** [comment]
Is there a possible work-around for this? I want to handle the case where an ajax request is made with an expired session and the result is a redirect to the authorize endpoint.

I have configured my front-end to detect when the response to a call is a page from the identity server, but that redirect never gets followed if the IdentityServer doesn't provide the page's origin in `Access-Control-Allow-Origin`. I initially tried `Access-Control-Allow-Origin : *`, however in that case, the browser doesn't allow me to keep `Access-Control-Allow-Origin : true`.


Ideally I would like to have some way for IdentityServer to send back `Access-Control-Allow-Origin` with the request origin iff the origin is one of my clients. Is there a way this can be done, either through IIS or IdentityServer itself? I am a bit of a newbie in this, any help would be greatly appreciated :) Thanks.
