### ISSUE TITLE
Enabling Windows Authentication for specific users identified by IP

### ISSUE THREAD

**Issue by elryry** [IdentityServer/IdentityServer3#2530]
I have been looking into a solution for this for a bit now, and I'm not having much luck. My end-goal is to use IdentityServer to authenticate users who may come from a shared device (shared login, not user specific) or from a managed device (user-specific Windows domain login). I know the subset of IP addresses that managed device users would come from and would like those users to login via Windows Authentication, and I would like all other IPs to fall into a catch-all and be authenticated via local login user service.

I have two questions about this setup:

1. What is the best way to route the user to the proper authentication method? HRD Controller?
2. If I setup and configure a second instance of IdentityServer upstream of the main instance for the Windows Authentication, what is the proper client/authority relationship between those two (flow type, can I return the SAM account name to the main Idsrv and use that value as the SubjectId for GetProfileDataAsync, etc.)?

Thanks in advanced for any clarification.

**Comment by brockallen** [comment]
1. In the user service in PreAuthN if you detect the IP range then you can assign the PreAuthenticateContext's IdP property to be the name of the external authentication middleware you use for windows auth.

2. We have a separate server for handling windows auth here: https://github.com/IdentityServer/WindowsAuthentication/, and you'd use the ws-fed MW from your main IdSvr to trust it.

**Comment by elryry** [comment]
Thanks @brockallen. Overall this seems pretty simple, but with the I am running into an issue of an endless redirect loop between the main idsrv and the windows auth server (PreAuthenticateAsync sets context.SignInMessage.IdP to "windows", redirects to Windows auth server, redirects back to idsrv and is picked up by PreAuthenticateAsync again and repeat).

What is the method to getting this properly sent to AuthenticateExternalAsync after the redirect back from the Windows auth server?

**Comment by brockallen** [comment]
Once you're back from the windows IdP, it should go into the challenge response code in the authN controller.

**Comment by elryry** [comment]
I'm not seeing that behavior. The only outcome I have been able to achieve is idsrv kicking the flow back to the Windows IdP after the redirect back from Windows IdP.

**Comment by elryry** [comment]
I was able to solve this issue by following the advice from issue #901.
