### ISSUE TITLE
Custom Identity Provider with IdS3

### ISSUE THREAD

**Issue by arunmurthy** [IdentityServer/IdentityServer3#2531]
What is the best way to integrate a custom Identity Provider with IdentityServer3? Are there any sample implementations out there which I can refer?

**Comment by brockallen** [comment]
What protocol does the custom IdP use?

**Comment by arunmurthy** [comment]
Custom IdP will support OAuth2 and OpenID Connect. Thanks!

**Comment by brockallen** [comment]
So then look at our samples that show how to configure external IdPs that use OIDC.

**Comment by arunmurthy** [comment]
Thanks @brockallen. I could not find a sample which matches my use case. I think I am missing something. My requirement: I want to add an external custom identity provider to Identity Service. I don't want to replace the existing IdS3 sign-in implementation with a custom sign-in implementation.
Btw, I am looking at samples available here: https://github.com/IdentityServer/IdentityServer3.Samples

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L88

**Comment by arunmurthy** [comment]
Thanks. I think I was on the right track then. I have a custom identity provider implementation using OIDC. The problem is the redirection from IdS back to the client. Here is the flow:

1. Client A is redirected to IdS
2. IdS presents all available identity providers (custom, google, twitter etc) and custom IdP is chosen
3. User provides credentials on Custom IdP and is authenticated. Custom Idp issues an id token. Note: Custom IdP uses IdS3 for token generation
4. IdS needs to validate this token, generate a new token and send it back to Client A.

Step 4 is where I am having issues. I keep getting a invalid nonce exception when I process the OIDC messages. Exception: OpenIdConnectProtocolInvalidNonceException.

Also, in order to redirect from IdS back to the Client A, I had to write a middleware to store Client A's redirectUrl in a cookie. Given the hoops I was jumping through to make this work made me question whether I was on the right track or if there was a more straightforward implementation.

**Comment by brockallen** [comment]
Sounds like you're just fighting with Microsoft's OIDC MW. I'd suggest setting up a standalone app to use the OIDC MW with your custom IdP to get that working first.

**Comment by arunmurthy** [comment]
I did. And it works without any OIDC issues. Basically Client A talking to Custom IdP over OIDC works without any issues. When I introduce IdS in-between then I hit this MW issue. Would it help if I posted a code snippet? 
On a related note, is storing the client's redirect url in a cookie the right approach?

**Comment by brockallen** [comment]
> When I introduce IdS in-between then I hit this MW issue. 

Is everything running on localhost? I wonder if somehow the nonce cookie for the client is getting confused with the nonce cookie for IdSvr and your IdP.

>  On a related note, is storing the client's redirect url in a cookie the right approach?

I'm not clear why you're doing this. 

> Would it help if I posted a code snippet? 

Unfortunately I'm not in a position to debug this, but if others look and might offer suggestions, then go for it.

**Comment by arunmurthy** [comment]
Everything is running on localhost. I will try and host them on separate servers to see if it fixes the issue.

Reason for storing redirect url in a cookie: To remember the client redirect url in IdSrv. When the token from custom IdP is posted to IdSrv, IdSrv needs to know which client requested for a token so that it can in turn generate a token and post it back. I suspect there is a better way to do this than storing original client redirect url in a cookie.

Thanks for taking the time to look at this issue. Appreciate it.

**Comment by arunmurthy** [comment]
I sorted out the nonce issue. I am wondering what is the best way to create a new token and post it back to the client. Here is my use case again: Client -> IdSrv -> custom IdP. Custom IdP authenticated the user and posted a token back to IdSrv. Where in IdSrv should I generate a new token (using claims from the custom IdP token) and post it back to the client? 

Option 1: In the Authorize endpoint
Option 2: In the middleware - Handle OIDC messages (Notifications -> SecurityTokenValidated), generate a token, and use HandleResponse to return to the client

Or is there any other option I should consider?

**Comment by brockallen** [comment]
> Where in IdSrv should I generate a new token (using claims from the custom IdP token) and post it back to the client? 

Look into the AuthenticateExternal in the user service -- this is where this is done.

**Comment by arunmurthy** [comment]
I got this working. Thanks!

On a related question, if I want the same sequence working for authorization code flow, do I need to implement a callback in IdSrv?

Basically Client -> IdSrv -> Custom IdP. Client asks for an auth code, IdSrv redirects the user to IdP. One of these two can be done between the IdSrv and IdP:

1. Implement authorization code flow
2. Implement implicit flow. generate and return an auth code from IdSrv to the client.

Any recommendations?

**Comment by brockallen** [comment]
Did you try it? :)

**Comment by arunmurthy** [comment]
Yup. I implemented implicit flow between IdSrv and custom IdP and authorization code flow between Client and IdSrv. It works. I am not sure if that is secure and hence the question. I am thinking the right solution is to always implement authorization code flow between IdSrv and IdP irrespective of the flow between the client and IdSrv.

**Comment by brockallen** [comment]
The user service abstracts however you connect to a client and/or an external IdP. So in short, what you're doing is fine.
