### ISSUE TITLE
Q: Post Authentication View/Handler

### ISSUE THREAD

**Issue by RipalV** [IdentityServer/IdentityServer3#2532]
We have multi tenant solution and we allow user email to be part of multiple tenants.
We use CustomViewService and CustomUserService to have our custom UI and users.

I am aware of the fact that IdentityServer3 does not support multi-tenant authentication, but we have got it working by using username as combination of email and tenantId.

For letting user choose a tenant, We are thinking of making Ajax call from custom login page to get list of assigned tenant, when successful hide login controls and display available tenants and user select a tenant and submit login page.

I was wondering if there is any better way to do this. Is there any other way to have a "post authentication view", once authenticated which could allow user to choose a tenant that she wish to login with.
 
Appreciate any help in this regard.

**Comment by brockallen** [comment]
Sorry -- this slipped thru the cracks. 

So you can always do partial views to control this. You could even do a partial view from `PreAuthenticate` to always do your custom login page where you show a tenant. 

Another idea, you can show tenant on the normal login page, and then read that additional form posted value in the normal `AuthenticateLocal` method.

**Comment by RipalV** [comment]
Thank Brock Allen,

We end up making ajax call from the Login page to get list of Tenants and let user select the Tenant and later we pass selected tenant Id to AuthenticateLocal method by appending the value to the userName.
