### ISSUE TITLE
Partial login from console client

### ISSUE THREAD

**Issue by antonvasilenko** [IdentityServer/IdentityServer3#2535]
Hello, IdentityServer Team.
I want to as you about better login flow in my case.
What is the best approach to _authorize user with login and password from console client_ if I have _partial login_ on server (additionally allow user to pick tenant)? I currently have a WPF client that shows login in webBrowser control - but that's really looks bad and it's hard to fine-tune such login form.

**Comment by brockallen** [comment]
Look at the console and/or WPF samples in the sample repo.

**Comment by antonvasilenko** [comment]
Yes, I've looked at console client with ResourceOwner Flow and Wpf client with hybrid and implicit flow.
But if I have partial login, I need to have some sort or additional round-trip to the server. In case of hybrid/implicit flow it redirects me to additional pages and redirects to my custom url after all done:
```
private void LoginWithProfileAndAccessTokenButton_Click(object sender, RoutedEventArgs e)
{
    RequestToken("scopeDesktopApi openid profile offline_access", "code id_token token");
}

private void RequestToken(string scope, string responseType)
{
    var request = new AuthorizeRequest(Constant.AuthorizeEndpoint);
    var startUrl = request.CreateAuthorizeUrl(
        clientId: Constant.ClientId,
        responseType: responseType,
        responseMode: "form_post",
        scope: scope,
        redirectUri: _redirectUrl,
        state: _state,
        nonce: _nonce);

    _login.Show();
    _login.Start(new Uri(startUrl), new Uri(_redirectUrl));
} 
```

from console client it is expected to user ResourceOwner flow with code like:
static TokenResponse RequestToken()
```
{
    _tokenClient = new TokenClient(
        Constants.TokenEndpoint,
        "roclient",
        "secret");
    return _tokenClient.RequestResourceOwnerPasswordAsync
        ("bob", "bob", "read write offline_access").Result;
}
```
But with resource owner flow and usage of TokenClient, how can I handle this additional roundtrip? This TokenClient does not expect to handle redirects.

**Comment by leastprivilege** [comment]
You need the web view for that.

**Comment by antonvasilenko** [comment]
Could it be another way? What if I want not only WPF, but a console app with same partial login approach. I was thinking that it should be something like:
1. client sends his login and password with ResourceOwner flow
2. server checks for the user and sees that he has something else to ask about user (i.e. pick tenant, or organization, or enter confirmation code from mail, etc). For that server returns some predefined http status code with optional json data for a user (in my case - a list of tenants that user should pick).
3. Client handles this result, checks that it is not http OK yet, parses response body, gets additional parameters, prepares new/ updates old token request with additional data (arc) and sends it back to the server.
4. Now server has everything to generate all required tokens, so it returns the token to a client.

What do you think, is such workflow possible without dealing with webcontrols?

**Comment by brockallen** [comment]
You're inventing your own protocol at that point. 

-Brock

**Comment by antonvasilenko** [comment]
Then maybe I'm on wrong path :( I seems to me that IdentityServer3 is flexible enough to allow such scenarious. I provide state and nonce params, also some additional cookie-based sessionId can be provided by server - It seems we have everything to allow several roundtrips between server and client to allow such scenarios. It even works in case of using web-control. So why it cannot work with from console client using json.

**Comment by antonvasilenko** [comment]
Also I think I can solve it in other way, If I only be able to extend/regenerate access token for a user. Consider next scenario. Maybe that is more real to implement:
1. using resource owner flow client gets IdentityToken, and AccessToken, but with some limited set of claims (i.e. **name **and **email**) 
2. IdSrv generates such token for client. But some other business logic server (BLS) requires additional claims. 
2. Client knows he needs more claims so he reaches custom IdSrv endpoint (additional controller) to get such claims (list of tenants, that is available for a user). Current client claims set is ok for this endpoint.
3. This custom Idsrv endpoint can show list of tenants for a user (GET /tenant/) and also gets tenant choise from the user (POST /tenant/:id). *At the point it would be great, if server will extend client tokens with newly obtained claims.*
4. Client receives new tokens and continue to work with BLS with those additional claims.

Is it more in the spirit of the IdentityServer3? Otherwise, I'm out of Ideas :(

**Comment by brockallen** [comment]
> Is it more in the spirit of the IdentityServer3

IdentityServer implements OIDC and OAuth2. The embedded browser is how those protocols recommend obtaining tokens if you're not using ROPF. For an example of another app that does this, look at Visual Studio. It's a desktop app and uses an embedded browser to log you in.

If you want to extend these protocols with something custom then you can implement a custom grant validator.

**Comment by antonvasilenko** [comment]
Thank you. makes sense. Maybe I'll stick with the web browser control for now. But just to clarify it completely:
1. This custom grant validator approach refers to my algorithm from [previous comment](#issuecomment-180784057)?
2. Is it fine (or even possible) to update the access token after some extra answers from the user? Or should I just revoke previous access token and user should be forced to request new one?

**Comment by brockallen** [comment]
1. Custom grant validator extends the token endpoint and accepts an alternative form of credential and that's what's custom -- you have to have the logic to validate it. No part of the spec accommodates asking questions back and forth.

That's the beauty of the embedded browser -- it can navigate the user to any web page and ask them all of these questions you want. The browser is where the protocols allow different styles of authentication.

**Comment by antonvasilenko** [comment]
Thank you for clarification. At least it gave some direction where to move forward.
