### ISSUE TITLE
Advice on where best to implement custom "aud" logic

### ISSUE THREAD

**Issue by kalanbates** [IdentityServer/IdentityServer3#2536]
I've run into a small snag with my system architecture.  I'm trying to get IdentityServer to generate access_tokens to resources but the default behavior of the system is identifying the audience to be resources running on the same host as my security server, and I no longer want this default behavior.

So lets say that I have IdentityServer running at
`https://security.mydomain.com/core`
and I want access tokens generated for
`https://resources.mydomain.com`
or for
`https://specialresource.mydomain.com`
or for
`https://resource.otherdomain.com`

Can you see any security reason not to embed these references as resources or drop them in a config in my solution and have my TokenSigningService assign the audience during the creation of my payload rather than using the audience on the incoming Token, as I have done in the sample below?

```
protected virtual async Task<string> CreateJsonWebToken(Token token, SigningCredentials credentials)
{
   var header = CreateHeader(token, credentials); //not provided for sample
   var payload = CreatePayload(token);

   return await SignAsync(new JwtSecurityToken(header, payload));
}
protected virtual JwtPayload CreatePayload(Token token)
{
   string audience = ConfigurationManager.AppSettings["token.audience"];
   var payload = new JwtPayload(
         token.Issuer,
        ,audience
        ,null
        ,DateTime.UtcNow
        ,DateTime.UtcNow.AddSeconds(token.Lifetime));
   //blah blah blah. Other stuff.
   return payload;
}
```

```
<appSettings>
   <add key="token.audience" value="http:resources.mydomain.com" />
</appSettings>
```

**Comment by leastprivilege** [comment]
audience is just a string - in our case "the resources belonging to a certain instance of idsrv". Not at all related to a physical location.

Scopes is the mechanism to target specific resources/apis

**Comment by kalanbates** [comment]
If that is the case, then perhaps I'm misinterpreting the [OpenID Connect Implementer's Guide (draft 20)](http://openid.net/specs/openid-connect-implicit-1_0.html)  I'm looking at section 2.2 for the ID Token and for aud, it states:

> aud
REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case-sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case-sensitive string.

The way I read this, the aud on the id_token is supposed to be my client that calls idsrv, not a resource belonging to idsrv.  

So in this case, I'm interpreting this as the ClientId for my `IdentityServer3.Core.Models.Client` that I provided to my `IntentityServerServiceFactory()` at Startup.  

If I've defined my relying party's client_id as "accountmanagement", then shouldn't the audience for this token be "accountmanagement"?

Is this an incorrect interpretation?

**Comment by kalanbates** [comment]
Regarding your [audience] v [scope] statement, (you almost _certainly_ understand this more than I do, so please correct me if what I am about to say is off base)

I have been treating the [audience] as identifying within my resource service that a calling client in possession of a token is accessing my resource service through an authorized client application. I've been treating [scopes] as identifying the permissions of the service API that have been authorized as available to the relying party and consented to by the human at the end of the wire.

...have I been going about this entirely wrong??

**Comment by leastprivilege** [comment]
id_tokens have the client id as aud claim
access tokens have [issuer_name + /resources] as aud claim

**Comment by leastprivilege** [comment]
ok?
