### ISSUE TITLE
RequireSignOutPrompt and post-logout redirection back to the client application

### ISSUE THREAD

**Issue by 8aginski** [IdentityServer/IdentityServer3#2537]
When RequireSignOutPrompt is true, the _Would you like to logout of Identity Server?_ prompt doesn't contain _No_ answer. The only way to get redirected back to the client application is answering _Yes_. Can this be changed?

**Comment by brockallen** [comment]
The browser has a back button, right?

**Comment by 8aginski** [comment]
Sure, for you and me it isn't a big deal, but I wouldn't call that a particularly great UX and I can easily imagine users complaining about it.

**Comment by brockallen** [comment]
Well, it's also somewhat of a security problem -- we'd only be able to safely show the button if the caller/return app is authenticated, and so this means the id_token_hint needs to be passed. We normally bypass the prompt if the id_token_hint is passed (unless RequireSignOutPrompt is true).

Also, there's nothing in the signout spec that discusses where to return back to if the user declines, so we'd need to add a new configuration setting for the client for this one specific scenario (which is most likely different than the redirect_uri, and the post_logout_redirect_uri). 

So these are some of the reasons it's just easier to rely upon the browser's innate navigation mechanism.

**Comment by 8aginski** [comment]
> Well, it's also somewhat of a security problem -- we'd only be able to safely show the button if the caller/return app is authenticated, and so this means the id_token_hint needs to be passed. We normally bypass the prompt if the id_token_hint is passed (unless RequireSignOutPrompt is true).

This cannot be a security problem anymore than it is with _Yes_. You redirect to the client application after _Yes_ is clicked. All I'm asking about is a _No_ button redirecting to the same client application.

> Also, there's nothing in the signout spec that discusses where to return back to if the user declines, so we'd need to add a new configuration setting for the client for this one specific scenario (which is most likely different than the redirect_uri, and the post_logout_redirect_uri

I see what you mean, I didn't think about it this way. I thought about using `post_logout_redirect_uri` for that purpose but what you say makes sense too - it's "post-logout", why should it be used when no OP logout occurred?

Are there any other options left if I need this feature? Any possibility of customization of that prompt and the actions performed after clicking buttons?

**Comment by brockallen** [comment]
You can always build your own views from a custom view service. You can add the URL for the "No" to the view model's `Custom` property (https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/ViewModels/CommonViewModel.cs#L62) and then show that in the view. 

If enough people want this sort of feature, we could consider adding it, but you're the first to have ever asked. And as you can tell from my initial reaction, I dislike adding buttons to web pages to hide, replicate, or replace native browser navigation.
