### ISSUE TITLE
User claims per client

### ISSUE THREAD

**Issue by MoeHamdan** [IdentityServer/IdentityServer3#2540]
Hello

I am new to IdentityServer. I am implementing several applications that will be using the IdentityServer for authentication and authorization, and in the future other applications will be using it. I am using it along with aspnet identity, I have noticed that adding a claim to a user will make it available for all clients; i.e if a user has a claim (role:administrator) the token will contain this claim for all clients. What I want is to have the user claims defined per client. My guess is to add ClientId to the table (UserRoles), I am not sure if this is the solution that I need to go with. Does the IdentityServer supports such scenario without adding ClientId column? 

Thank you in advance!

**Comment by brockallen** [comment]
Either create custom scopes for the client with the claims you want, or implement a custom user service where you filter the claims issued based on the client id passed via the context param to GetProfileData.

**Comment by MoeHamdan** [comment]
Thanks for your reply, well that is what I was thinking of. I am actually asving clients/scopes etc.. in the database so I was thinking about adding the clientId to the UserRoles and UserClaims so when I get the claims/roles they will be filter per user per client.

**Comment by MoeHamdan** [comment]
How would I pass the clientId to my custom userservice?

**Comment by brockallen** [comment]
It's passes in the context to the various methods in the user service.

**Comment by MoeHamdan** [comment]
I was using the IdentityServer3.AspNetIdentity, I have removed it and then implemented my own. Thanks for you help. :)
