### ISSUE TITLE
Implicit flow for SPA itself

### ISSUE THREAD

**Issue by vpukhalsky** [IdentityServer/IdentityServer3#2541]
Hi, we develop a chrome extension which uses some API requiring a bearer token to be set to get access to it. The chrome extension works with both authenticated users and anonymous ones (they simply displayed much less data then) and it works just fine when we authenticate users through the identityserver instance and use access token issued for the end user (the extension acts as an implicit client). The question is - if we want the extension to get data for an anonymous user, we'd like it to still be able to get the access token from the identity server somehow. I checked all flows but looks like there is no one working similar to the implicit flow (so the client's identity is verified by the return url) and client providing its clientid (we don't want to expose our client's secret to the client code due to obvious reasons). The client credential flow doesn't work as well as it assumes server-to-server communication instead. Could you please advise what would be the best approach in our case? Many thanks in advance!

**Comment by thabart** [comment]
I'm probably wrong and I don't really like to propose workaround to fix this kind of issue :x.
If you want to retrieve an access-token for an anonymous user which can be used to retrieve user-information (role, name ...) etc... Follow those steps :
* Add a new resource owner into the table which can be used to authenticate the anonymous users
* Add a new client valid for resource-owner credentials workflow
* Modify your client to use both implicit & resource-owner credentials workflow. For more information about this flow read the doc : https://tools.ietf.org/html/rfc6749#section-1.3.3

If you want to specify which identity provider will be used to authenticate the resource-owner then you can pass the property "acr_values:idp<name ...>" into your HTTP REQUEST : https://identityserver.github.io/Documentation/docsv2/endpoints/token.html

Maybe you're wondering how to limit the access to certain operations ? After obtaining the access_token you can retrieve the user-information & check if the resource-owner has the correct role to access to the operation.
For example you can add a role for the anonymous user & an another one for the authenticated one.

**Comment by vpukhalsky** [comment]
The resource-owner flow doesn't work as it requires password still to be provided by extension when it tries to get access token for itself (end user is not yet authenticated). And as mentioned before, we would like not to store such a sensitive data on the client.

**Comment by brockallen** [comment]
> if we want the extension to get data for an anonymous user, we'd like it to still be able to get the access token from the identity server somehow

Since your software is a plugin then there's no way it can have its own credential without dynamic provisioning, thus no way to get an access token without a user participating in the authentication.

**Comment by thabart** [comment]
Based on your requirements, the credentials (login + password) of an anonymous user are not sensitive & can normally can be used by everyone to generate an access token. Those information can be stored inside your application & used to retrieve an access token via the resource owner flow : https://tools.ietf.org/html/rfc6749#section-4.3.2 (pass the user name & password to the token endpoint, retrieve the access token & pass it to your protected API).

When the protected API has received the access token (by reference / JWT), it can retrieve the resource owners claims such as the role & returns more or less information.

**Comment by brockallen** [comment]
@vpukhalsky did you come to a decision or a workaround?
