### ISSUE TITLE
Force Logout and Multiple Browser Login handling Identityserver3?

### ISSUE THREAD

**Issue by dgs-hassaan786** [IdentityServer/IdentityServer3#2542]
Hi, I am currently using IdentityServer3 for SSO. I have two questions and required assistant on that.

1) If user login for client A from browser 1 and try to login again for client A from browser 2(let consider browser 1 as chrome and browser 2 as firefox), how to restrict that user to not login from browser 2. Instead of this i want to show Custom Login error message like "You are already logged in". 

2) How do I force logout user from the identityserver3. My token type is reference.

thanks in advance

**Comment by brockallen** [comment]
1. You would have to implement this yourself somehow. This would help: https://identityserver.github.io/Documentation/docsv2/advanced/session-invalidation.html

2. We support SLO: https://identityserver.github.io/Documentation/docsv2/advanced/signout.html and token invalidation: https://identityserver.github.io/Documentation/docsv2/endpoints/revocation.html

Given that all of the answers to your questions were in the docs, I'd suggest spending some more time reading them.

**Comment by dgs-hassaan786** [comment]
Hi brock, thanks for the reply.

For Question 2) my scenario is that Admin forced logout the user. For token revocation we need token and token_hint and client secret. i have reference token in db. As admin is itself a user, here what i have done is hit a db call from the custom endpoint and deleted the access_token againts the subjectId. In this way i have achieved forced logout

Is this a right approch?

**Comment by brockallen** [comment]
Well, you can also just update the DB directly too, right? we index by subject and client.

**Comment by dgs-hassaan786** [comment]
Ah! I just messed up. After token revocation the token validation is returning 400 which is correct but at identityserver there is still a valid authentication cookie exist. 
I have an interceptor which checks the token is valid or not. On Invalid I fire method which clear the session cookie and redirect it to identityserver login page.
Now the user is redirecting but as there is a valid authentication cookie exist at identity server it's auto login it.

**Comment by brockallen** [comment]
Right, so then as I said:

> You would have to implement this yourself somehow. This would help: https://identityserver.github.io/Documentation/docsv2/advanced/session-invalidation.html

**Comment by dgs-hassaan786** [comment]
yes sir! working on it. Give me time i'll catch up later.

**Comment by brockallen** [comment]
Open a new issue if you have further questions.
