### ISSUE TITLE
Access OpenIdConnectAuthentication ApiController using HttpClient

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2543]
Hello,
I have one IdSrv3 and many clients connected using OpenIdConnect.
One of my OpenId client is implemented in Idsrv3 application because is the Admin application.
In this client i can create users, add users to groups, etc (admin operations).
In this admin client i have  [Authorize] actions in ApiController to allow other clients to create (external restricted API).
In my idSrv3 server i have implement custom UserService because i filter role claims by CleintId.

Now i want to access this admin [Authorize] client action from other OpenId MVC app client using HttpClient but how?

I set my clients to:
```
Flow = Flows.Implicit,
AllowClientCredentialsOnly = true, 
```

If i call idsrv to get adminClient AccessToken using:
```
var tokenClient = new TokenClient("idsrvtokenaddres","clientAdmin","secret");
var tokenResponse = await tokenClient.RequestClientCredentialsAsync("user_registration");
```

This return access token but if i try to access ApiController action using this access toke like this:
```
var client = new HttpClient { BaseAddress = new Uri("idsrvaddres") };
client.SetBearerToken(tokenResponse.AccessToken);
 var result = await client.GetStringAsync("api/action");
```
I get the response the idsrv3 login page.

i have try also to access this Api using current client user access token:

```
var claimsPrincipal = User as ClaimsPrincipal;
var token = claimsPrincipal.FindFirst("access_token").Value;
```
but the same problem, i get the login page.

I try to simulate this case using  [MVC Authentication sample](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MVC%20Authen) by replacing `UseIdentityServerBearerTokenAuthentication` from Api Application with `UseOpenIdConnectAuthentication` and i get also the login page in the response.

How can i access this admin client Api controller using current logged user from another openid client or how can i solve this scenario?

**Comment by totpero** [comment]
can someone help me with an idea?

**Comment by mderriey** [comment]
Your API should never return the IdSrv login page. If the call is not authorized, you should get an HTTP unauthorized response.
By the sound of it, your IdSrv setup conflicts with your WebAPI.

What is the benefit of hosting the WebAPI in the same web application as IdSrv? Try moving your WebAPI to a separate web application, it should do the trick.

Also, could you show the OWIN registrations of IdSrv and WebAPI in your project? We could try and see if something's wrong there.

Finally, you never want your WebAPI to be protected with `UseOpenIdConnectAuthentication` because in this case it's going to return the IdSrv login page which is not very useful in a WebAPI scenario. Your first try with `UseIdentityServerBearerTokenAuthentication` was correct.

**Comment by totpero** [comment]
I have my WebAPI  in the same web application as IdSrv because i start with this sample: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MVC%20Authentication .The embedded client is the Admin app (in this client app i add roles, users, groups... etc.. to my database using EF). In the same client app i create ApiController with authorize attribute but because i use `UseOpenIdConnectAuthentication` return login page.
First question:
How can i create WebApi Controller in this application: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MVC%20Authentication/EmbeddedMvc and access this authorize ApiController using `TokenClient` from another OpenId client app?

If i ask in a different way: How can i share WebApi Controllers between two clients using OpenId and access it using Httplient?

**Comment by mderriey** [comment]
OK, I think I get what's wrong.

If you have a look at [this file](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs), 2 main registrations are made.
The first one is for IdentityServer, which is mapped to the path `/identity`, which means that any requests matching this path will be processed by IdentityServer.
The second one, for the MVC application, is not mapped to a specific path, so all the requests not matching `/identity` will flow through the rest of the registrations ([L55](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs#L55) to [L124](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs#L124)).

What I think happens is that your WebAPI calls, which I guess hit `/api/action`, go through the main OWIN pipeline, in which you inserted the OpenID Connect middleware. This explains why you get IdentityServer login page.

What you should do is have a specific OWIN pipeline for you WebAPI calls, let's say by matching `/api`, in which you insert the token validation middleware.

Let me know if this is clear enough.

**Comment by totpero** [comment]
I try to map how you say the api to diferent pipeline :
first i have IdSrv map:
`app.Map("/identity", idsrvApp => idsrvApp.UseIdentityServer(options));`

after this i have my api map to my idsrv using UseIdentityServerBearerTokenAuthentication:
`app.Map("/api", ConfigureIdentityServerBearerToken);`

and after this i have owin map: 
```
 app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
      {
.....
```
but when i try to run my app with this, i get this error:
```

A task was canceled.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Threading.Tasks.TaskCanceledException: A task was canceled.

app.UseIdentityServerBearerTokenAuthentication(idsbt);



[TaskCanceledException: A task was canceled.]

[AggregateException: One or more errors occurred.]
   System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) +3632501
   System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) +11532675
   System.Threading.Tasks.Task`1.get_Result() +33
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__0.MoveNext() in c:\workspace\WilsonForDotNet45Release\src\Microsoft.IdentityModel.Protocol.Extensions\Configuration\HttpDocumentRetriever.cs:53

[IOException: Unable to get document from: https://localhost:44300/identity/.well-known/openid-configuration]
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__0.MoveNext() in c:\workspace\WilsonForDotNet45Release\src\Microsoft.IdentityModel.Protocol.Extensions\Configuration\HttpDocumentRetriever.cs:59
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.IdentityModel.Protocols.<GetAsync>d__0.MoveNext() in c:\workspace\WilsonForDotNet45Release\src\Microsoft.IdentityModel.Protocol.Extensions\Configuration\OpenIdConnectConfigurationRetriever.cs:81
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) +11532932
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__3.MoveNext() in c:\workspace\WilsonForDotNet45Release\src\Microsoft.IdentityModel.Protocol.Extensions\Configuration\ConfigurationManager.cs:198

[InvalidOperationException: IDX10803: Unable to create to obtain configuration from: 'https://localhost:44300/identity/.well-known/openid-configuration'.]
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__3.MoveNext() in c:\workspace\WilsonForDotNet45Release\src\Microsoft.IdentityModel.Protocol.Extensions\Configuration\ConfigurationManager.cs:212
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__0.MoveNext() in c:\workspace\WilsonForDotNet45Release\src\Microsoft.IdentityModel.Protocol.Extensions\Configuration\ConfigurationManager.cs:0
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   IdentityServer3.AccessTokenValidation.<<RetrieveMetadata>b__0>d__4.MoveNext() in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\Plumbing\DiscoveryDocumentIssuerSecurityTokenProvider.cs:0
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   IdentityServer3.AccessTokenValidation.AsyncHelper.RunSync(Func`1 func) in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\Plumbing\AsyncHelper.cs:34
   IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider.RetrieveMetadata() in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\Plumbing\DiscoveryDocumentIssuerSecurityTokenProvider.cs:161
   IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider..ctor(String discoveryEndpoint, IdentityServerBearerTokenAuthenticationOptions options, ILoggerFactory loggerFactory) in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\Plumbing\DiscoveryDocumentIssuerSecurityTokenProvider.cs:62
   Owin.<>c__DisplayClass9.<ConfigureLocalValidation>b__8() in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\IdentityServerBearerTokenValidationAppBuilderExtensions.cs:172
   System.Lazy`1.CreateValue() +411
   System.Lazy`1.LazyInitValue() +183
   System.Lazy`1.get_Value() +75
   Owin.IdentityServerBearerTokenValidationAppBuilderExtensions.UseIdentityServerBearerTokenAuthentication(IAppBuilder app, IdentityServerBearerTokenAuthenticationOptions options) in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\IdentityServerBearerTokenValidationAppBuilderExtensions.cs:46
   Sobis.IdentityServer.Startup.ConfigureIdentityServerBearerToken(IAppBuilder app) in D:\Sobis Dev\Sobis.IdentityServer\Sobis.IdentityServer\Startup.cs:751
   Owin.MapExtensions.Map(IAppBuilder app, PathString pathMatch, Action`1 configuration) +177
   Owin.MapExtensions.Map(IAppBuilder app, String pathMatch, Action`1 configuration) +108
   Sobis.IdentityServer.Startup.Configuration(IAppBuilder app) in D:\Sobis Dev\Sobis.IdentityServer\Sobis.IdentityServer\Startup.cs:161

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +92
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
   Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +66
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +123
   Microsoft.Owin.Host.SystemWeb.<>c__DisplayClass2.<InitializeBlueprint>b__0(IAppBuilder builder) +71
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +462
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +40
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +70
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +115
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +106
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +534
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +339
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9942412
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +90
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261
```

**Comment by totpero** [comment]
I comment the openid owin and i havee only my idsrv and identitybearertoken:
```
app.Map("/identity", idsrvApp => idsrvApp.UseIdentityServer(options));
app.Map("/api", ConfigureIdentityServerBearerToken);
```

if i comment api map server start but if i have all this two map, i get the error from up.

**Comment by mderriey** [comment]
Going through the callstack it says that the `IdentityServerBearerTken` middleware canot access the OpenID Connect metadata endpoint provided by IdentityServer at `https://localhost:44300/identity/.well-known/openid-configuration`.

Can you try to debug the app and hit this URL with a browser. VS might give you a bit more context about what happens.

**Comment by totpero** [comment]
I comment all openid connect and in my startup remain only the idsrv config and after this i have ServerBearerToken config.
I try to debug and after pass the idsrv config and enter in my ServerBearerToken , the app freez and loading and loading... and at end i get the error from previews comment.
Is problem if i have the idsrv and ServerBearerToken  in the same project?
the idsrv not initialize before ServerBearerToken?

**Comment by leastprivilege** [comment]
Yes thats a known issue - discussed here a dozen of times already. You need to configure issuer name and certificate statically on the validation middleware. as always - the docs have all the details.

**Comment by totpero** [comment]
After i set `SigningCertificate `and `IssuerName ` solve error .
Also i have set `ValidationMode = ValidationMode.ValidationEndpoint` and `Authority` and i have `Authorize ` attribute to my `ApiController ` but in Mozilla and Edge if i try to access this link ask me for windows authentication but in Chrome and IE11 the user is authenticated automatically  with windows user.
Is this normally?

**Comment by totpero** [comment]
I found why this is happen: i have windows authentication enable in my project because i use also the windows provider. How can i deal with this?
