### ISSUE TITLE
IdentityServer3 as a WebApp

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2544]
We are considering IdentityServer3 for deployment as a CloudService in Azure. Our Rest WebApi DLL's can be a separate WebApp. Are there any recommendations for this general deployment architecture ? How do users typically deploy a Rest endpoint / IdentityServer3 on the cloud ?
This may also give us an idea about how we split into microservices eventhough it is a separate topic.

**Comment by leastprivilege** [comment]
Check the docs on deploymenrt.

**Comment by mohanr** [comment]
Is it https://identityserver.github.io/Documentation/docs/advanced/deployment.html ? This is work in progress ?

**Comment by leastprivilege** [comment]
https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

**Comment by mohanr** [comment]
Thanks. I think now I understand how the basic setup works. We are going to have multiple Rest services. Not all of them are bundled in the same DLL as IdentityServer3. Moreover I think a flow diagram showing the redirect URL's and the general flow is helpful. That should be in the examples. I think.

**Comment by mohanr** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/EmbeddedAssetsViewService and a few others like this are not updated.

**Comment by brockallen** [comment]
Make sure you're viewing the v2 version of the docs. We have the old v1 docs up there since some people are still on 1.x.
