### ISSUE TITLE
Using the TokenValidator in version 2.4

### ISSUE THREAD

**Issue by neilcrowther** [IdentityServer/IdentityServer3#2545]
I have been using the Core.Validation.TokenValidator from within my own WebApi endpoint (issuing and validating authorisationcode tokens for the impersonation of users by administrators).  The endpoint needs to validate the calls it receives and it is hosted in the same service as idsvr.  

Before upgrading to 2.4 I could create an instance of the TokenValidator to use to validate incoming bearer tokens, but after updating to 2.4 I any call to ValidateAccessTokenAsync will fail as the IssuerUri  now uses an internally set AutoFac resolver, which I cannot find any way to set myself (fails as the call to content.GetAutofacLifetimeScope() returns null).

Since I do not want to duplicate all the work you have already done to issue and validate tokens I'd really like to continue using the public classes that are available, but don't see a way to do so at the moment.  

Is there any "approved" way to hook into the TokenValidator in 2.4?  I'm also using the TokenResponseGenerator to create the impersonation tokens (as grant type = AuthorizationCode), and that still seems to be workable in 2.4.

**Comment by leastprivilege** [comment]
Well - they were never supported to be used directly - but if you want to use them, you should get them from the DI container.

**Comment by neilcrowther** [comment]
That would be the ideal, but I don't know and couldn't find any way to access the DI container once I've called app.UserIdentityServer(options).  Is the configured AutoFac container available publicly somehow that I've missed?

**Comment by neilcrowther** [comment]
Just saw your retweet (and laughed).  I'm using your project in a way never intended or tested for but I'm more than happy to change! :-)  You guys are doing great work that is really appreciated!

**Comment by leastprivilege** [comment]
We have extensions methods for the OWIN environment - one is called `Resolve<T>` - this gives you access to our DI.

You need to run in the sample pipeline of course (and after "us").

**Comment by leastprivilege** [comment]
ah - yea - i also had to smile ;)

**Comment by leastprivilege** [comment]
see https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by neilcrowther** [comment]
Brilliant, I'll look at refactoring our app to run in the same pipleline (its currently in a mapped owin branch so probably won't be populated properly for your extensions).  Thanks for the pointer.

**Comment by neilcrowther** [comment]
I followed your suggestion and it both simplified my code and worked exactly as I wanted :-).  Thanks very much once again.
