### ISSUE TITLE
Registering the client details and inserting to database

### ISSUE THREAD

**Issue by lpranith** [IdentityServer/IdentityServer3#2546]
Once client details like ClientID ,Clientname, scope,redirect uri etc are entered via UI and I insert those values to azure database from my customdeveloperservice. I make use of sql server to do the database work not the entityframework.

So when the client sends the request with the above details, i see that during validation of the request ,the client ID is requested through  the method FindClientByIdAsync in the public class InMemoryClientStore. So i just made a connection in this method and obtained the Client details and loaded Client details like:
qlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        client.ClientId = reader[0].ToString();
                        Secret secret = new Secret();
                        secret.Value = reader[1].ToString();
                        client.ClientSecrets.Add(secret);
                        client.ClientName = reader[2].ToString();
                        //client.AllowedScopes.Add(reader[3].ToString());
                        client.RedirectUris.Add(reader[4].ToString());
                        if (reader[5].ToString().Contains(Flows.Implicit.ToString())) { client.Flow = Flows.Implicit; }
 
 
                    }
 
return Task.FromResult(client);

Is this ok?..Is there any other place i should take care of?..Basically the client details should come from database when ever it is requested.

**Comment by brockallen** [comment]
Yes, this is the reason for the `IClientStore` interface -- to load the client configuration information from the database. As long as you implement it and register it with our factory, then that's how IdentityServer will get all the information it needs about the client.
