### ISSUE TITLE
Local Login only for admin

### ISSUE THREAD

**Issue by Bidou44** [IdentityServer/IdentityServer3#2549]
In my application, I only have external login. I created a local account for an administrator so that he can access the administration interface **(/admin**) or the asp.net user management interface **(/manager**).

Now, since I have 1 local user (the administrator), I set the EnableLocalLogin flag to true, but the problem is that my "standard" users also see the local login screen.

Ideal would be, that on **/admin** and **/manager**, I only have the Local Account view, and otherwise, only External providers. Is that possible?

**Comment by Bidou44** [comment]
I manage to make it work with a javascript file (DefaultViewServiceOptions), but I'm not sure that this is the best solution...

**Comment by brockallen** [comment]
The `Client` config has a `EnableLocalLogin` which you would set to `false`.

**Comment by Bidou44** [comment]
That made the trick. The IdP are not hidden for the administrator, but I can live with this.... Thanks.
