### ISSUE TITLE
To add google group as claims into access token.

### ISSUE THREAD

**Issue by WassMM** [IdentityServer/IdentityServer3#2551]
I would like to use google as an identity provider (via IdentityServer3) for one of my apps. It already works fine. But, in the end, in access token I could see only claims for "profile" scope. It would be graet if I could see also groups as claims in the access token, Could you recommend how to see google groups (for example groups from Google for Education) as claims in access token? In general, is it possible? I understand that answer contains google part and IdentityServer part, I would ask advice for both.

Thank you

**Comment by brockallen** [comment]
Look into the Scope Claims configuration.

**Comment by WassMM** [comment]
About IdentityServer side - scope and claims configuration, yes, you already helped me a while ago and I know how to implement it.
A bit more about google side here:
[http://stackoverflow.com/questions/35292406/to-add-google-group-as-claims-into-a-token](url)

In general, there is no chance to get google groups value as part of token from google, if I need it I have to request google directory service using "service account" of my application.
