### ISSUE TITLE
Track which clients is used by user

### ISSUE THREAD

**Issue by henninga** [IdentityServer/IdentityServer3#2552]
Hi

How can I track which clientid is used by a user? Say I have clientA and clientB, when the user navigates to clientA I want to log that somehow.

How can I do this?

**Comment by brockallen** [comment]
You can implement the event interface to get notification from IdSvr. The one you might want is `TokenIssuedDetailsBase` which has the subject and the client: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Events/TokenService/TokenIssuedDetailsBase.cs

**Comment by henninga** [comment]
Thank you. I'll check that out.

Do I need to implement IEventService for this?

**Comment by brockallen** [comment]
Yes.
