### ISSUE TITLE
What are the security implications of UseTokenLifetime = false?

### ISSUE THREAD

**Issue by najeebzohaib** [IdentityServer/IdentityServer3#2553]
I'm new to Identity server. I've got same issue as that mentioned in https://github.com/IdentityServer/IdentityServer3/issues/1688. I see setting UseTokenLifetime = false makes this error go away:
XMLHttpRequest cannot load https://localhost:4433/identity/connect/author…XXXXWY5YmMy. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.’

My question is are we in any way degrading the security of our application? I think setting UseToken will set expiration to whatever is specified in AuthenticationOptions' ExpireTimeSpan. But when I tried it and set it to 2 minutes it doesn't work. Here's the configuration: 

 idSrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Mysite",
                    SigningCertificate = LoadCertificate(),
                    Factory = factory,
                    AuthenticationOptions = new AuthenticationOptions()
                    {
                        EnablePostSignOutAutoRedirect = true,
                        CookieOptions = new CookieOptions {
                            AllowRememberMe = false,
                            ExpireTimeSpan = new TimeSpan(
                                int.Parse(ConfigurationManager.AppSettings["authentication_cookie_timespan_hours"]),
                                int.Parse(ConfigurationManager.AppSettings["authentication_cookie_timespan_minutes"]),
                                0
                            )
                        },
                    },
                    EnableWelcomePage = false
                    
                });
            });

**Comment by brockallen** [comment]
This error is caused by your Ajax calls triggering redirects to IdSvr for login. You should not be issuing 302 responses for Ajax calls, nor should you be using cookies for authenticating ajax calls.

**Comment by najeebzohaib** [comment]
thanks for your reply Brock. Can you please point me in the right direction. What's the best way to resolve?

**Comment by brockallen** [comment]
Use access tokens for your API calls.

**Comment by najeebzohaib** [comment]
There is no API. Ajax call is to controller in same MVC client.

**Comment by najeebzohaib** [comment]
Im using ImplicitFlow

**Comment by brockallen** [comment]
Right, and that's an API call. And your server is expecting a browser to make HTTP calls that it can redirect when he user needs authentication. That's the problem -- your server is not making the distinction between the UI/browser making a request and an Ajax call making a request.

Perhaps try this: http://brockallen.com/2013/10/27/using-cookie-authentication-middleware-with-web-api-and-401-response-codes/

**Comment by najeebzohaib** [comment]
thanks for the reply. Very useful. Perhaps I didn't mentioned this earlier. the current issue isn't the first time ajax request is made to MVC controller. We've locked down the application so first step is to authenticate. Once that's done user gets in and I noticed that after default 5 minutes upon any request whether Ajax or not there is a redirect to identity server. If its non-ajax then application handles it fine and the redirect mechanism works, getting new token i guess. but with ajax I'm getting this problem. The link you pasted above is very useful but I don't think responding with 401 fixes it. Any other ideas?

**Comment by brockallen** [comment]
Well, what I'm saying is that you need to control how your app responds to failed authentication for ajax calls. You can't let them redirect to the authorization endpoint because there's no human to see the page (since it's all programmatic). 

Also, if you're using cookies for authenticating ajax calls you might be subject to CSRF attacks. 

Finally, the 5 minute issue on the cookie is because the OIDC middleware does not have the `UseTokenLifetime` option set to `false`. If you set it to false, then you can control the cookie lifetime yourself in the cookie middleware options. But you still have the possibility of the cookie timing out in an ajax call, so you still have your original problem.

**Comment by najeebzohaib** [comment]
Things make a lot of sense now. Thanks a lot Brock for your prompt replies.
