### ISSUE TITLE
Hiding External Login Panel based on Client's IP Address

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3#2556]
I need to hide the external login provider panel based on what the client's IP address is. I already figured out that in the following method in the AuthenticationController.cs of the IdentityServer project:

        `private async Task<IHttpActionResult> RenderLoginPage(SignInMessage message, string signInMessageId, string errorMessage = null, string username = null, bool rememberMe = false)`

if I do:

```
...
   loginModel.ExternalProviders = null;
   return new LoginActionResult(viewService, loginModel, message);
 }
```

then the External Login panel is not displayed. 

**Question 1. I'd like to know if there's a more elegant way of doing this.**  

**Question 2. Is there a way to get to Request.RemoteIpAddress (client's IP address) in the following method that I added in UserService.cs:**

```
public override Task PreAuthenticateAsync(PreAuthenticationContext context)
        {
            ...
            return Task.FromResult(0);
        }

```

**Comment by leastprivilege** [comment]
Yes by injecting the OwinEnvironmentService - check the archives. Has been answered a couple of times before.

**Comment by farzad99** [comment]
Thank you @leastprivilege. This is how I did it in case somebody else needs to do it:


```
public class UserService : AspNetIdentityUserService<User, string>
    {
        IOwinContext owinContext;
        public UserService(UserManager userMgr, IOwinContext context)
            : base(userMgr)
        {
            owinContext = context;
        }
...

```

**Comment by farzad99** [comment]
I think this is a better way of doing it:

```
public class UserService : AspNetIdentityUserService<User, string>
    {
        private readonly OwinContext owinContext;
        public UserService(UserManager userMgr, OwinEnvironmentService oes)
            : base(userMgr)
        {
            owinContext = new OwinContext(oes.Environment);

        }
...
```

**Comment by brockallen** [comment]
Yes, the 2nd way you show is the right approach.
