### ISSUE TITLE
Use bearer token when partially logged in

### ISSUE THREAD

**Issue by jorros** [IdentityServer/IdentityServer3#2558]
Hey guys,

I am having currently two services running (Sts and an accounts store, which is a rest service). The accounts api is set up with `UseIdentityServerBearerTokenAuthentication`. When I am using other applications and want to access the accounts api, I simply add the Bearer header with an access token to the request and it works.

Now after a user logged in for the first time I want to call a method on the accounts api, which is secured by the Authorize attribute. I am using partial login to redirect that logged in user to a restricted area inside of my Sts/Mvc application, which holds the partial login claims (I can access them), but I don't know how to make a call to my api, since I am missing the access token.

Is there a way to retrieve an access token or call my secured api with the claims of the partial logged in user?

Thank you for any help :)

**Comment by brockallen** [comment]
Partial login means your logic is not yet prepared to issue a token for the user.

**Comment by jorros** [comment]
Is there any way to generate an own token and pass it to the api without changing the logic of the api?

**Comment by brockallen** [comment]
So in the partial login part of your app, you need to get a token to call an API? You're running in the IdSvr pipeline and so you can inject the `ITokenService` to call into IdSvr directly to get a token. Or you could go thru the more formal channel and use client credentials to get one.
