### ISSUE TITLE
Parallel Login SSO from same browser Issue?

### ISSUE THREAD

**Issue by dgs-hassaan786** [IdentityServer/IdentityServer3#2559]
Hi, I have encountered an issue. I have been implementing Identityserver3 SSO using form post client method using Hybrid flow.

I have Client A and Client B.
Initially user request Client A  anonymous state redirect to SSO login page.
Also same User request Client B  anonymous state redirect to SSO login page.(in the same browser opened in new tabs).

The user logins the Client A gets access_token which is stored in authentication cookie.
Here, i have custom implementation which stops the same user to login at authentication level. 
Now user tries to login with another username and password (if valid) , the identityserver issue it  validate token using form post. 
Now problem client cookie is  overridden and the User 2 is accessing the application. The authentication cookie of User 1 is lost.

How to handle this issue

**Comment by brockallen** [comment]
I am not sure I follow. Which cookies are lost?

**Comment by dgs-hassaan786** [comment]
hi broc i am facing the following problem in my live environment.
i have 3 clients  a.abc.com, b.abc.com, c.abc.com. 
when user login for a,abc.com, session cookie is generated and placed inside user identity.

I am using Custom filter attribute inherited from Authorize attribute and inside Onauthorization method i am validating the access_token by hitting the endpoint at identityserver, if it is not validated then i am logging out the user and redirect it to login page. this  SecurityAuthorizeAttribute is used on each controller. So every time a controller hit it will call.

        public override void OnAuthorization(AuthorizationContext filterContext)
        {
            var identity = (System.Security.Claims.ClaimsIdentity)filterContext.HttpContext.User.Identity;
            IEnumerable<System.Security.Claims.Claim> claims = identity.Claims;
            HostName = filterContext.RequestContext.HttpContext.Request.Url.Host.ToLower();
            UserName = claims.GetClaimValue("email");
            WriteLog(String.Format("In Security Authorize attribute begin from user {0} for host {1}  ",UserName,HostName));

            if (filterContext == null)
            {
                throw new ArgumentNullException("filterContext");
            }
            else if (!filterContext.HttpContext.User.Identity.IsAuthenticated)
            {
                if (NotifyUrl != null)
                    filterContext.Result = new RedirectResult(NotifyUrl);
                else
                {
                    WriteLog(String.Format("Authentication is not authenticated from user {0} for host {1}  ",UserName,HostName));
                    filterContext.Result = new RedirectResult("~/Account/SignIn");
                }
            }
            else
            {
                
                if (claims.Count() > 0)
                {

                    if (ValidateToken(claims))
                    {
                        WriteLog(String.Format("Access token is Validated... for user {0} for host {1}  ",UserName,HostName));
                        ApplicationRightsHandling(filterContext, claims);
                    }
                    else
                    {
                        WriteLog(String.Format("val.AccessToken Failed logging off the user for user {0} for host {1}  ",UserName,HostName));
                        filterContext.Result = new RedirectResult("~/Account/SignOutLocal");
                    }
   
                }
            }

        }

Now After login to a.abc.com and then if i moved to b.abc.com access token validation is returning failed and user signout is calling and i am not getting a clue why identity server is issuing different token for that user. I means i am logging the access_token for a.abc.com its returning like '3c38fd187adb035d7985e08dd0363fce' and then on client b.abc.com inside onAuthorization method its returning access_token like '3dfsfd187adb035d7985e08dd0363fce'

One thing i noted on local debugging:
whenever i only type url localhost:39112, or localhost:39211
the Authorize End Point GET method at identity server is hitting automatically.
I didn't understand how it is tracking?

**Comment by joshpearce** [comment]
I think cookies can be shared across ports [1]. I've seem a lot of weird cookie issues that seem to violate the same origin policy, on localhost too. Try doing local development with some better host names, like a.localhost.com, b.localhost.com, etc. Also, less common, but when you call `app.UseCookieAuthentication(...)` make sure to set the `CookiePath` properly if you have two different apps under the same web site.

[1] http://stackoverflow.com/questions/1612177/are-http-cookies-port-specific

**Comment by brockallen** [comment]
I guess I'm still confused. Did you ever make any progress?
