### ISSUE TITLE
Require SSL error after upgrading IdentityServer3

### ISSUE THREAD

**Issue by microef** [IdentityServer/IdentityServer3#2560]
Hi, 

We have successfully implemented IdentityServer3 (v3.2.2.0) with ASP.net 5.
But we receive a 'Ssl is required' error after upgrading to v3.2.3.0 or v3.2.4.0.
We have a SSL cert and IIS requires a SSL connection.

We use these packages :
- IdentityServer3
- IdentityServer3.EntityFramework
- IdentityServer3.Integration.AspNetCore
- IdentityServer3.MembershipReboot

Changing the RequireSsl option is also not working, we've also tried to set PublicOrigin, but that didn't work either.
The problem exists on our production server with valid SSL cert and on my localhost dev environment.

Best regards,

Michael Roef

`
app.Map("/core", core =>
            {
                var idSvrFactory = Factory.Configure(connectionStringConfig);
                idSvrFactory.ConfigureCustomUserService(connectionString);

                var idsrvOptions = new IdentityServerOptions
                {
                    Factory = idSvrFactory,
                    SigningCertificate = Certificate.Get(),
                    RequireSsl = true,
                    SiteName = "**** | IdentityServer",
                    EnableWelcomePage = false,
                };

                core.UseIdentityServer(idsrvOptions);
            });`

**Comment by brockallen** [comment]
That sounds odd, and I can't think of anything that has changed related to that setting. Would you be in a position to debug this some more (perhaps by even stepping into our code).

**Comment by microef** [comment]
Oke, it seems that the OwinRequest in RequireSslMiddleware is reporting the wrong scheme.
My browser shows https://localhost:443/core and the request shows http://localhost:443/core.

It's really wierd because my IIS server doesn't listen to HTTP requests on that port.
I think it's something with ASP.net 5, because the example web project in your source works.
