### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#2561]
Hello,
is there any proposial for production ready hardware requirements?
I think they aren't high, but some numbers would be great.
Would be interesting for single machine and 2-node setup.

**Comment by brockallen** [comment]
Well, this process is no different than for any other app you build, especially since you're writing code in IdSvr. We have no idea what your code might do, so we have no ability to predict and provide recommendations. So you'll have to profile your solution yourself.

**Comment by cbomkamp** [comment]
If you're using MembershipReboot, I would suggest at least running the Password Stretching Timings utility on the proposed hardware.

We were seeing password hashes take over 3 seconds with the default config once the calendar turned over to 2016. We tend to have lower end systems, though, so YMMV.


https://github.com/brockallen/BrockAllen.MembershipReboot/tree/master/util/PasswordStretchingTimings
