### ISSUE TITLE
Save Token between applications

### ISSUE THREAD

**Issue by MartinGian** [IdentityServer/IdentityServer3#2562]
Hi,

I started using IdentityServer3 as an identity provider of two applications. These apps should have a single sign on mechanism, so IdentityServer is great for me.

I have a question about where I keep the access token, since the two applications will be in different domains, so does not work use session storage of browser.

What strategy could be used to save the token and use it from the two applications?

Thank you very much for your time.

**Comment by brockallen** [comment]
Did you not look at how the samples are doing it? They just put the access token into the claims that are put into the cookie.

**Comment by MartinGian** [comment]
Hi Brock, thanks for your answer.
Can you tell me the name of the sample where done that?
All the examples I've seen, the clients keeps the access token, I haven't seen any sample with a cookie to connect to different applications.

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client%20%28Hybrid%29/Startup.cs#L65

**Comment by MartinGian** [comment]
Thanks Brock!
