### ISSUE TITLE
Additional Property Required on `LoginCredentials` to Support Captcha on Login

### ISSUE THREAD

**Issue by ilivewithian** [IdentityServer/IdentityServer3#2563]
I have built a custom view service built on top of the `DefaultViewService`. I have also built a custom user service built on top of `UserServiceBase`. I have the requirement to add a captcha to the login UI when an individual has entered their password incorrectly more than a X times. I can trigger the display of the captcha based on the error message set in the `AuthenticateResult`, but I have no way of receiving the captcha data in my user service. 

Would you accept a PR to add a metadata property (simple a `string`) onto the `LoginCredentials` class? Or would you recommend an alternative approach for my scenario?

**Comment by brockallen** [comment]
You can add any inputs to the form and then receive them in your user service by reading the form. To access the posted form, inject the OwinEnvironmentService into you user service ctor.

**Comment by ilivewithian** [comment]
Ah yes. Perfect, thanks.
