### ISSUE TITLE
AccessTokenAuthentication for HTTP (not https) calls

### ISSUE THREAD

**Issue by acsiri** [IdentityServer/IdentityServer3#2564]
1) We have a asp.net application and we have added a OWIN Startup class to validate the AccessToken using 

 app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = System.Configuration.ConfigurationManager.AppSettings["TWIdentityServer"]                
            });

Please note that we are using legacy asmx services,

My question is can we use AccessTokenAuthentication for HTTP (not https) calls

**Comment by leastprivilege** [comment]
technically yes. Recommended - no.
