### ISSUE TITLE
Preventing Single Signon Elegantly!

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3#2565]
I have three MVC applications (mvc1, mvc2, mvc3) and a Web API service (webApi). mvc1, mvc2, mcv3, and webApi are all secured by IdSvr3 that provides local login using ASP.NET Identity and also Windows authentication for some users. mvc1, mvc2, and mv3 make ajax calls to webApi secure end points. Everything works but now I need to prevent mvc1 users from being able to do single signon to mvc2 and mvc3. How can I elegantly accomplish that? When the user logs in I can tell if it's a mvc1 user or not and I could do like a "userType, mvc1User" claim and then do 

`[ResourceAuthorize(...)] `

on every controller. But I'd like to know if there's a better way instead of having to do it for each controller?

**Comment by brockallen** [comment]
Implement authorization logic in your apps to prevent users that don't belog.

**Comment by farzad99** [comment]
OK, thank you
