### ISSUE TITLE
Link to Register Form from application to Identity server

### ISSUE THREAD

**Issue by farshid3003** [IdentityServer/IdentityServer3#2568]
I Implement a register page on the server which need signin id. how can I generate a link on my application to redirect user on this form?

        [Route("core/localregistration")]
        [HttpGet]
        public ActionResult LocalRegistration(string signin)
        {
            if (string.IsNullOrEmpty(signin))
            {
                return View("Error");
            }
            return View();
        }

**Comment by brockallen** [comment]
You only need the signin param if you want to redirect back to the login page and resume where the user left off.

**Comment by farshid3003** [comment]
I dont want to go to the login page. In my case I want put a Register button in top of website and redirect user to the register page directly. is there any way to do this ?

**Comment by brockallen** [comment]
If you're in the middle of the reg process, then you need to manage that value and then eventually return the user back to the login page passing it. If the user comes into registration outside the context of a login request, but then you want to log them in you can create a request to signin via our OWIN environment extension APIs: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html
