### ISSUE TITLE
Bearer token is not getting validated.

### ISSUE THREAD

**Issue by acsiri** [IdentityServer/IdentityServer3#2569]
1) We have a asp.net application and we have added a OWIN Startup class to validate the AccessToken using

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
{
Authority = System.Configuration.ConfigurationManager.AppSettings["TWIdentityServer"]

});

Please note that we are using legacy asmx services and identityServer is running HTTPS and legacy webservice is running under HTTP, 

Issue:-
1) We could see during debug the startup class is getting called.
2) When we make a call to legacy webservice from a TestClient by adding the Bearer token from client using Headers.Add("Bearer", "xxxxxxxxxxxxxxxxxx") where "xxxxx" is the auth_token received. We do not see those tokens are validated in the pipeline when legacy service is hit. And legacy service is running under Intergrated PipeLine mode not classic.

Is there any way in the legacy webservice to validate the token ?.

Note:-
I did tamper the bearer token to see if it validates or not. But no luck i was able to make calls :)

**Comment by brockallen** [comment]
I'd suggest adding a middleware after the access token validation MW to see if the user has been assigned to the Authentication.User on the Owin Context.

**Comment by acsiri** [comment]
1) Identity Server is able to give us the access_token,
2) To secure the legacy webservice we added a OWIN middleware in the legacy solution. Basically the solution has both legacy asmx pages and the OWIN startup class.

Now the challenge for me is , how do i secure my webmethods ?.

**Comment by brockallen** [comment]
My suggestion was to help you debug it. 

-Brock

**Comment by acsiri** [comment]
Are there any examples where legacy services are validated for their Webmethod calls using thinktecture, Kindly help us.

**Comment by brockallen** [comment]
Not ASMX, sorry.

**Comment by acsiri** [comment]
Is it possible to create a simple asp.net webservice with simple webmethod "hello world" which works with the 
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
{
Authority = System.Configuration.ConfigurationManager.AppSettings["TWIdentityServer"]

});

Thanks
Sridhar.

**Comment by leastprivilege** [comment]
I don't see a reason why this wouldn't work. ASMX is just a handler like aspx and MVC ultimately.

I don't have any free time right now. sorry. 

I will leave this open a couple more days and close if no one volunteers.

**Comment by acsiri** [comment]
Are there any other methods to validate the access-token ?.

**Comment by leastprivilege** [comment]
sure you can use the JWT security token handler from MS to validate it manually.
