### ISSUE TITLE
Using Microsoft.Owin.Security.WsFederation as an identity provider redirects to blank page

### ISSUE THREAD

**Issue by Quicksteve** [IdentityServer/IdentityServer3#2571]
Hello,

after experimenting quite a bit I can't get this to work. I have basically followed the first tutorial of the documentation and added OpenId claims to the mix (which are for some reason not in the id_token, but that is okay, I can get them from the userinfo endpoint). So far, everything worked flawlessly and I could get my claims that I programmed it. I then tried adding AD FS as an identity provider as described in your documentation, and while redirecting to it works fine, after logging in I get directed back to the URL I set in the Relying Party setup and the server returns an error 500. I get nothing in the logs.

```
[16:57:08 INF] Start authorize request
[16:57:08 INF] Start authorize request protocol validation
[16:57:08 INF] Authorize request validation success
 {
  "ClientId": "test-client",
  "ClientName": "Test Client",
  "RedirectUri": "https://test.callback.domain/callback.html",
  "AllowedRedirectUris": [
    "https://test.callback.domain/callback.html"
  ],
  "SubjectId": "unknown",
  "ResponseType": "code",
  "ResponseMode": "query",
  "Flow": "AuthorizationCode",
  "RequestedScopes": "openid profile email",
  "State": "abcdef",
  "Raw": {
    "client_id": "test-client",
    "redirect_uri": "https://test.callback.domain/callback.html",
    "response_type": "code",
    "scope": "openid profile email",
    "state": "abcdef"
  }
}
[16:57:08 INF] User is not authenticated. Redirecting to login.
[16:57:09 INF] End authorize request
[16:57:09 INF] Redirecting to login page
[16:57:09 DBG] Protecting message: {"ReturnUrl":"https://connectedmanager.nl:5002/connect/authorize?client_id=test-client&redirect_uri=https%3A%2F%2Ftest.callback.domain%2Fcallback.html&response_type=code&scope=openid%20profile%20email&state=abcdef","ClientId":"test-client","AcrValues":[],"Created":635908930282612456}
[16:57:09 INF] Login page requested
[16:57:09 DBG] signin message passed to login: {
  "ReturnUrl": "https://idsrv3:5002/connect/authorize?client_id=test-client&redirect_uri=https%3A%2F%2Ftest.callback.domain%2Fcallback.html&response_type=code&scope=openid%20profile%20email&state=abcdef",
  "ClientId": "test-client",
  "IdP": null,
  "Tenant": null,
  "LoginHint": null,
  "DisplayMode": null,
  "UiLocales": null,
  "AcrValues": [],
  "Created": 635908930282612456
}
[16:57:09 INF] rendering login page
[16:57:12 INF] External login requested for provider: Federation
[16:57:12 INF] Triggering challenge for external identity provider
```

After that, nothing in the logs.

The final response from the idsrv as a HAR can be viewed here: http://www.jsoneditoronline.org/?id=5b0d11b4cd0b17206d1f65978c27706c

Startup code:

        public void Configuration(IAppBuilder app)
        {
            var factory = new IdentityServerServiceFactory()
                .UseInMemoryClients(Clients.Get())
                .UseInMemoryScopes(Scopes.Get())
                .UseInMemoryUsers(Users.Get());

            var corsPolicy = new DefaultCorsPolicyService();
            corsPolicy.AllowAll = true;
            factory.CorsPolicyService = new Registration<IdentityServer3.Core.Services.ICorsPolicyService>(corsPolicy);

            var options = new IdentityServerOptions
            {
                Factory = factory,
                RequireSsl = true,
                SigningCertificate = Certificate.Get(),

                AuthenticationOptions =
                {
                    IdentityProviders = ConfigureIdentityProviders
                }
            };

            app.UseIdentityServer(options);
        }

        public static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            app.UseWsFederationAuthentication(
                new WsFederationAuthenticationOptions
                {
                    Wtrealm = "urn:identityServer",
                    MetadataAddress = "https://idsrv3/federationmetadata/2007-06/federationmetadata.xml",
                    AuthenticationType = WsFederationAuthenticationDefaults.AuthenticationType,
                    SignInAsAuthenticationType = signInAsType
                });
        }

Just for testing, I have successfully authenticated using the Google login option, so really not sure what is going on here.

**Comment by leastprivilege** [comment]
maybe enable katana logging on our logging options - see if that reveals more information.

**Comment by brockallen** [comment]
Any update?
