### ISSUE TITLE
How to get updated_at in the identity token?

### ISSUE THREAD

**Issue by provegard** [IdentityServer/IdentityServer3#2575]
I would like to get the `updated_at` claim in the identity token. I need to do user profile synchronization, but I want to avoid going to the profile endpoint if I don't have to. Therefore, I have added a custom Identity scope with:

`new ScopeClaim(Constants.ClaimTypes.UpdatedAt, true)`

However, It seems like DefaultClaimsProvider specifically removes the `updated_at` claim by doing:

`var claims = FilterProtocolClaims(context.IssuedClaims)`

...where one of the "protocol claims" apparently is `updated_at`.

Any way around this?

**Comment by brockallen** [comment]
You want updated_at from an external IdP?

**Comment by provegard** [comment]
No, I have implemented my own provider using IdentityServer. I want updated_at in the ID token, so that I can compare that timestamp with the timestamp of my local (cached) user profile data. If the updated_at timestamp is newer, I will fetch the profile data from the profile endpoint and update the local data.

**Comment by brockallen** [comment]
Ok, I see. Yea, I suppose that claim type is debatable. @leastprivilege objections?

**Comment by leastprivilege** [comment]
The spec says:

> Time the End-User's information was last updated. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.

**Comment by brockallen** [comment]
Right, but we filter it out before we put it into the id_token (even if the user service includes it).

**Comment by provegard** [comment]
I have worked around this for now by adding a custom claim (updated_at with a prefix), but I feel it would be cleaner to just use updated_at.

**Comment by leastprivilege** [comment]
we will discuss this.

**Comment by leastprivilege** [comment]
done on dev - for 2.5

**Comment by jkavanaghrdm** [comment]
Can the inclusion of an updated_at claim also be supported on an access token?

**Comment by leastprivilege** [comment]
Why not? Have you tried it and it doesn't work?

**Comment by jkavanaghrdm** [comment]
Yes, it doesn't work. I create it and include it in the scope claims but it gets removed and is not included in the token. I'm running IdentityServer4 1.0.0-beta1-update1. Is there a newer version I should try?

**Comment by leastprivilege** [comment]
Then this is the wrong repo for the issue. Can't remember if we changed that for 4 already.
