### ISSUE TITLE
High level architecture best Practices.

### ISSUE THREAD

**Issue by MahmoudElShazly** [IdentityServer/IdentityServer3#2576]
Hello,

I am planning to use IdentityServer as my authentication server for my application, I have:
1 - MVC app
2 - API
3- IdentitServer

My question is, what is the best practices of how to bundle them together, I saw examples of having 
1 - (MCV, IDsrv) together and the API is separate.
2 - (API , IDsrv) together and the MCVis separate.
3 - All MCV, API and IDsrv are separate.

I am planning to have mobile app to connect to API later.

Which option should I go with should I go with?, what is the pros and cons of each?

Thanks,

**Comment by leastprivilege** [comment]
everything separate is the recommended approach.

**Comment by MahmoudElShazly** [comment]
Great thanks!,

now the log in/log out/etc. pages will be owned by the IDsrv
is there any recommended way in sharing the same look and feel/styles/css  between these pages and the MVC app?

**Comment by inongogo** [comment]
I might not be the best one to comment about this but I think you could look into the [IViewService](https://identityserver.github.io/Documentation/docs/advanced/customizingViews.html) to accomplish this.

**Comment by MahmoudElShazly** [comment]
Thanks for the reply, I have looked at the sample before, and here is my understanding, I can customize the views but they still have to be hosted with the Identity Server, is thee any way to make the Identity server pulls all the css and html of those pages from the App (MVC) ?

I saw the IViewLoader, can I use this interface for this purpose?

**Comment by brockallen** [comment]
No -- it's just another web app.
