### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2577]
I have a basic idea about how WebApi routes are authorized.

I have an AngularJS project and a WebApi project in my solution. Can I authorize these AngularJS views ? Should these HTML views be served by using a _View_ class that IdentityServer3 understands ?

I refer to this https://identityserver.github.io/Documentation/docs/advanced/customizingViews.html

**Comment by leastprivilege** [comment]
this is all not the job of identityserver. idsrv does authentication. everything else is user management.

**Comment by mohanr** [comment]
I think there are too many questions. I will ask one first.

Can my HTML 5 view which is a separate webapp be authorized by Idp ( which is another WebApp project in the same solution ) ?

**Comment by leastprivilege** [comment]
that's a completely new topic. So I will close this one.

The general advice is - create a separate user management application (technology does not matter) - and make that a regular client to idsrv.
