### ISSUE TITLE
For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method. 

### ISSUE THREAD

**Issue by venkatrv** [IdentityServer/IdentityServer3#2578]
I am getting the following error when I try to use Windows Login with IdentityServer3. Any one knows how to fix this?

"For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method."

**Comment by brockallen** [comment]
No idea. Any update?

**Comment by venkatrv** [comment]
Not sure how this is resolved, but it is working fine now. May be the version I got earlier had this issue..I re downloaded the code and tried again, so far it is ok.
Thank you for the follow-up on this issue
