### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2579]
This issues https://github.com/IdentityServer/IdentityServer3/issues/2280 seems to be what we are looking for. But the discussion there isn't very clear to new users.

Is there such a sample available ? 
We want our UI to be presented by the Idp and then Idp's API calls will be used to reset the password. Can you assist ?

**Comment by brockallen** [comment]
The docs are here: https://identityserver.github.io/Documentation/docsv2/
The samples are here: https://github.com/IdentityServer/IdentityServer3.Samples

**Comment by mohanr** [comment]
Right. My confusion stems from my lack of enough knowledge of OAuth. How does the reset password flow get routed through the IDp and get stored in the business DB ? Is there a particular endpoint involved ?

**Comment by mderriey** [comment]
Password reset has nothing to do with the IdP or OAuth. IdSrv doesn't expose an endpoint to reset a password. That's out of the scope of OIDC.

When I implemented this before, IdSrv was plugged to ASP.NET Identity. So I created a Web API which exposed an endpoint to reset the password via ASP.NET Identity, since this is built-in.

**Comment by mohanr** [comment]
So if the IdP has Cassandra as the Servicefactory already configured I need to update it in the DB. This does not need ASP.NET. Right ?
Not sure what happens to the validity of the token after this.

**Comment by mderriey** [comment]
ASP.NET Identity is basically a user management system. It's backed by a database. In your case, you need to update the password wherever it's stored.

If you use reference tokens, you can invalidate them when the user changes his password. Now you have a relation between your API and IdSrv, so you'll need to host your API in the same project as IdSrv, so you can access the necessary services to invalidate the tokens when you need to.

**Comment by mohanr** [comment]
That clarification was very helpful.
