### ISSUE TITLE
asp.net legacy service + OWIN

### ISSUE THREAD

**Issue by acsiri** [IdentityServer/IdentityServer3#2580]
All,

I have a asp.net webservice and i want to protect the webmethods. How do I do ?. Are there any samples available ?.

the legacy webserive is having a file extension of .asmx and the method it contans is

 [WebMethod]
        public string HelloWorld()
        {
            return "Hello World";
        }

I have added a OWIN middleware Startup class to the same project.

 public void Configuration(IAppBuilder app)
        {
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = System.Configuration.ConfigurationManager.AppSettings["TWIdentityServer"]
              
            });

            app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);
            app.UseWebApi(WebApiConfig.Register());          
        }

The client application is setting the tokens 

 httpWebRequest.Headers.Add("Authorization", "Bearer " + access_token);

I do not see this working?. Any help would be greatly appericated.

Thanks
Sridhar.

**Comment by brockallen** [comment]
Do you have this line of code after your `UseIdentityServerBearerTokenAuthentication`:

https://github.com/IdentityServer/IdentityServer3.Samples/blob/dev/source/Clients/WebFormsClient/Startup.cs#L89

**Comment by acsiri** [comment]
do you mean  app.UseStageMarker(PipelineStage.Authenticate);

**Comment by brockallen** [comment]
Yes. Not sure if that's your problem, but it's something you probably want to configure in your legacy app using katana security middleware.

**Comment by acsiri** [comment]
Hey BrockAllen,

As per your suggestion I added a OWIN middle and always the code is passing thru. Commented out the 
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
{
Authority = System.Configuration.ConfigurationManager.AppSettings["TWIdentityServer"]

});

and added a some code:-

 app.Use(async (context, next) =>
            {
                if (context.Request.Path.Value == "/hello")
                    using (var writer = new StreamWriter(context.Response.Body))
                    {
                        await writer.WriteAsync("Hello Middleware!");
                    }
                else
                {                    
                    await next();
                }
            });

all HTTP REquests are passing thru this pipe line.

But i am not able to protect my WebMethods when i add BearerTokenAuthentication code.

**Comment by acsiri** [comment]
Does any one have solution,

**Comment by brockallen** [comment]
This should work by adding the stage marker described above.

**Comment by acsiri** [comment]
Stagemaker setting did not go positive. Any examples would be great

**Comment by brockallen** [comment]
Sorry, I don't know what the issue is then.
