### ISSUE TITLE
Getting over AAD Cookie Expiry with IdentityServer

### ISSUE THREAD

**Issue by rmmcgr** [IdentityServer/IdentityServer3#2581]
I have an ASP.NET 4 MVC 5 application that is being developed which is using Azure AD for authentication. It is not a SPA, but does use allot of AJAX to request partial views to enhance the UX.

We continually hit problems with the fact that AAD is only issuing cookies for an hour, so if you are in the middle of filling in a form and then post this to the server, while the cookie is expired, you hit AAD, but then loose the POST data after the redirect back to the application. If an AJAX request is fired off after the timeout, a 302 response is returned and that of course causes problems as well.

While we have been looking into hacks to try and get over the above problems, does all of this get solved with the use of IdentityServer hooked up to AAD as an external authentication provider?

I believe we can set the authentication cookie received from IdentityServer to a much more sensible (for our internal LOB app) value (I want 2 days).

So what I would like is:

- An un-authenticated user hits the app URL.
- A redirect occurs to IdentityServer, which in turn on seeing the user is not authenticated automatically sends them over to the AAD login page.
- The user logs in, gets redirected to IdentityServer which then issues the app a cookie with the timeout of our choosing. 
- In all of the above the user never sees an IdentityServer page (as such).

Now, what happens when the cookie, token (or whatever) that get's issued by AAD to IdentiyServer expires after the initial hour? Anything?

Will this get around the AAD cookie being only issued for an hour?

Thanks for any help/advice.

**Comment by brockallen** [comment]
If authentication ends right before a user does a normal form POST, then your app has a very hard problem to solve. Most people don't run into it often depending on how they configure their apps. IdSvr won't be any different than any other IdP in solving that problem. It's something you have to solve in your own app with your own code (as it's really unrelated to using a STS). So in short, you can't blame AAD for the problem.

As for AAD or Katana support, you should contact Microsoft.
