### ISSUE TITLE
SPA client usage of accesstoken securely

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2583]
I am trying to make sense of this.

We only see examples that get the access token and store it in the SPA and send it along in the header. What other security measures should we take ? I am assuming we have to send a secure nonce but we don't deal with cookies. How does this work ?

`
      
           Nonce Implementation Notes

           The nonce parameter value needs to include per-session state and be unguessable to 

           attackers. One method to achieve this for Web Server Clients is to store a cryptographically random

           value as an HttpOnly session cookie and use a cryptographic hash of the value as the nonce 

           parameter. In that case, the nonce in the returned ID Token is compared to the hash of the session 

           cookie to detect ID Token replay by third parties. A related method applicable to JavaScript Clients is 

           to store the cryptographically random value in HTML5 local storage and use a cryptographic hash of this value.`

**Comment by brockallen** [comment]
This is the issue track for IdentityServer issues, not general security questions.

**Comment by mohanr** [comment]
Understand. Is there a way to use a cryptographic hash of a cookie value as a nonce ?

                  (e.g) idsvr.session
