### ISSUE TITLE
DefaultTokenSigningService.CreatePayload ignores token.CreationTime

### ISSUE THREAD

**Issue by brat000012001** [IdentityServer/IdentityServer3#2584]
Hello,
CreatePayload method always sets the value of NotBefore to "UtcNow" instead of whatever the date/time specified in the token.CreationTime. Is this intentional?

**Comment by leastprivilege** [comment]
I can't remember. Might be a bug. We will look into it.

**Comment by leastprivilege** [comment]
For all practical purposes that's the same value (maybe a 1-2 ms difference) - or is there an issue?

**Comment by brat000012001** [comment]
In some cases there may be a need to have the access token back dated, for example for purposes of unit testing.

**Comment by brat000012001** [comment]
Hello Dominick,
I went ahead and created a pull request #2616 with my changes that set the JWT payload's 'nbf' and 'exp' claim values to token.CreationTime and token.CreationTime + token.Lifetime respectively instead of current time.

**Comment by leastprivilege** [comment]
do you want to redo the PR on the dev branch?

**Comment by brat000012001** [comment]
Yes, hopefully I'll get to it sometimes today

**Comment by brat000012001** [comment]
PR #2638

**Comment by leastprivilege** [comment]
done. thanks
