### ISSUE TITLE
local login and IdP Restrictions

### ISSUE THREAD

**Issue by pjirsa** [IdentityServer/IdentityServer3#2585]
It seems that local login does not work when I have IdP restrictions defined for a client. I still get local login as an option and the user is signed in. But, I never get sent to the redirect URL. Removing the IdP restrictions everything works as expected. Is there a way to specify the local login provider in the client IdP restrictions?

**Comment by brockallen** [comment]
Add `Constants.PrimaryAuthenticationType`

**Comment by pjirsa** [comment]
Thanks, @brockallen. That worked for me.

**Comment by suren4a0** [comment]
I am facing the same issue in IdentityServer4. Where should I add **Constants.PrimaryAuthenticationType**?

Thanks
