### ISSUE TITLE
SSO issue

### ISSUE THREAD

**Issue by dunglp** [IdentityServer/IdentityServer3#2589]
Have a good day, guys.

For now, I have 3 sites configured SSO. Site A is for registering user. After that, his account is pending. He can log in to site A to see the sign up progress but cannot logged in to site B until his account is approved by Super Admin.

Is there anyway to configure site A to not use SSO with site B ? Site B and site C still need SSO.
If not, can I restrict user to logged in to site B if his account is pending ? I mean in case user logged in to site A and then move to site B.

Please advice, @brockallen, @leastprivilege.
Thanks in advance.

**Comment by leastprivilege** [comment]
Add an "approved" claim to the identity token. Make all applications that care about it check that claim.

**Comment by dunglp** [comment]
Thanks @leastprivilege 

It means that we have to check that claim inside the application that care about it and do redirect to Unauthorized page. Am I correct ? Can I do it inside startup.cs ?

**Comment by leastprivilege** [comment]
that could be a possible place to do that, yes.

**Comment by dunglp** [comment]
Sorry @leastprivilege .
Can you give example for checking that claim in startup.cs and do redirect ?

**Comment by leastprivilege** [comment]
Write some Katana middleware that checks OwinContext.Authentication.User.

Similar to https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/master/source/Owin.ScopeValidation/ScopeValidationMiddleware.cs#L37

**Comment by dunglp** [comment]
Thanks @leastprivilege. I can make it worked.
