### ISSUE TITLE
sub is not persistent

### ISSUE THREAD

**Issue by nklap** [IdentityServer/IdentityServer3#2590]
Hey,

I noticed that the sub I receive from idsrv changes over time. The sub that i get from facebook is always the same.

e.g:
facebook: 494386140728138
idsrv: {sub: 0119c7dda9fa80f4140a567d3a7d46b3}

some minutes later:
facebook: 494386140728138
idsrv: {sub: 02b3a5d665cc078dad6489594431fdaa}

Is this by purpose?

**Comment by leastprivilege** [comment]
Generating the sub is your responsibility - how do you do it?

**Comment by nklap** [comment]
Ah, I haven't added any logic. I get the claims from the social provider + the sub I mentioned. I thought that idsrv passes the claims with the response.

**Comment by leastprivilege** [comment]
No - you have to implement IUserService.

**Comment by nklap** [comment]
@leastprivilege I'm wondering where the sub is coming from? I couldn't find anything in LoginExternalCallback and ExternalIdentity. Could you point me to the right direction?

Another question: Is there any dependend logic required in a custom UserService or can I just override the action I need?
