### ISSUE TITLE
Logging to Log4Net even while LoggingOptions are default (no logging enabled) and no LogProvider configured

### ISSUE THREAD

**Issue by sickboy** [IdentityServer/IdentityServer3#2591]
I am receiving logging on various levels  (info, debug, error etc) from IDSrv, which floods my own log4net and logentries.com account.
Is there some way to turn this off?

1. I have not configured a LogProvider
2. I have not configured the LoggingOptions, so the default (disabled) is active.

thanks

**Comment by leastprivilege** [comment]
Our logging picks up the logging configured in the hosting application. If you don't want that you can write "No-op" LogProvider to prohibit that.

**Comment by leastprivilege** [comment]
Will add this in 2.5 - but you can use it now already:

```csharp
namespace IdentityServer3.Core.Logging
{
    /// <summary>
    /// A no-op log provider to disable all logging
    /// </summary>
    public class NoopLogProvider : ILogProvider
    {
        public Logger GetLogger(string name)
        {
            return delegate { return false; };
        }

        public IDisposable OpenMappedContext(string key, string value)
        {
            return new NoopClass();
        }

        public IDisposable OpenNestedContext(string message)
        {
            return new NoopClass();
        }

        private class NoopClass : IDisposable
        {
            public void Dispose()
            { }
        }
    }
}
```

Set that provider using `LogProvider.SetCurrent`

**Comment by sickboy** [comment]
Thanks a lot!
