### ISSUE TITLE
Flow suggestion to Cordova(Telerik Platform)

### ISSUE THREAD

**Issue by tienw** [IdentityServer/IdentityServer3#2593]
What is the suggested/correct flow to use for mobile app using Cordova(Telerik Platform)?

I was able to connect to the identity server from a html/javascript using implicit flow, receive token and call another WebApi. Act beautifully. However, when copying exactly same code to inapp html of Cordova project. It stops working due to "not authorized", becasue the redirecturi of the cordova client needs to be specified in the configuration of IdentityServer. That make me think that do we need to configure the ip/redirecturi for each mobile app installed? I am a little confused now.

**Comment by brockallen** [comment]
You need to use the cordova plugin for the embedded browser. that's about all i know.

**Comment by tienw** [comment]
I head over cordova plugin page and cannot find any plugin for Identity Server. So I guess I have to create one from scratch? Besides that, any other solutions?

**Comment by brockallen** [comment]
There's no plugin for idsvr -- you need to load the in-app browser plugin.

**Comment by tienw** [comment]
By loading the in-app browser plugin, do you mean load the url of identityserver in the in-app browser? What would be the flow type to take in this case?

**Comment by leastprivilege** [comment]
implicit flow.

**Comment by tienw** [comment]
So

`function loginInApp()
        {
            var authorizationUrl = 'https://localhost:44300/core/connect/authorize';
            var client_id = 'implicitclient';
            var **redirect_uri** = 'http://localhost/';
            var response_type = "token";
            var scope = "openid profile email";
            var state = "";//Date.now() + "" + Math.random();

            localStorage["state"] = state;

            var url =
                authorizationUrl + "?" +
                "client_id=" + encodeURI(client_id) + "&" +
                "redirect_uri=" + encodeURI(redirect_uri) + "&" +
                "response_type=" + encodeURI(response_type) + "&" +
                "scope=" + encodeURI(scope) + "&" +
                "state=" + encodeURI(state);
            alert(url);
            var ref = window.open(url, '_blank', 'location=yes');
            ref.addEventListener('loadstart', function () { alert('loaded'); });

        }`

What value should I enter the redirect_uri, since it's a in app html (not hosted html over internet so I don't have a url for it.)

**Comment by brockallen** [comment]
You use a non-html scheme like "oob://callback/yourapp" or somesuch.

**Comment by tienw** [comment]
I also include the oob url to the client.cs of IdentityServer. Now the inapp browser become blank page after loginInApp() is called and here is the output from the visual studio 

Redirecting to: oob://callback/myapp#error=invalid_request&state=14559154593760.8142848811112344

looks like the request is invalid and being redirect back to oob url. Anyone knows why?

**Comment by brockallen** [comment]
Sorry, don't know -- I think you might need to ask the cordova folks for some help.

**Comment by cbomkamp** [comment]
I made a sample project using the Cordova inappbrowser plugin with IdSvr.  Check it out here and see if that helps.  In my case, I don't redirect back to the Cordova app, but redirect to a web application that is also a client of IdSvr.  The Cordova app checks for the hash fragment in the inappbrowser and extracts the token out of there.

https://github.com/cbomkamp/IdSvrCordovaClient

**Comment by brockallen** [comment]
Thanks @cbomkamp -- I'll check this out.

**Comment by tienw** [comment]
Thank you @cbomkamp for the sample project! I knew someone will face same situation like me when creating a Cordova. 

Your idea to pass redirectUri to another client is cool. However, how does your IdentityServer bypass your client url check so it displays the login screen instead of the message "The client application is not known or is not authorized"

P.S, I found the cordova.js files are missing when I started the index.html in your project. Would you mind to take a look of that issue?

**Comment by brockallen** [comment]
I'll close this for now, but if anyone on this thread is interested in contributing a formal Cordova sample, then it would be appreciated. Just open a new issue and/or PR on the samples repo. Thanks!

**Comment by tienw** [comment]
Thank you to @brockallen and @cbomkamp 

For now I got it working by using InAppBrowser with redirecturi value of "http://localhost", when the redirection coming back to localhost, read the authrize code and close the InAppBrowser before it display error page.

**Comment by cbomkamp** [comment]
@tienw I've updated my sample. I realized I had some broken code in there and it should be more clear now what it's doing.  Feel free to create an issue there if you need anything further.
