### ISSUE TITLE
Passing custom data in the authorization request for use on the Login page

### ISSUE THREAD

**Issue by nmeierpolys** [IdentityServer/IdentityServer3#2594]
When redirecting to the Identity Server login page to authenticate a user, is there any way to pass custom flags that I could use in a CustomViewService to control the display of the login page? For instance, when the user finishes logging out, I'd like to redirect immediately to the login page where they can log back in and show a message indicating that they have been successfully logged out. I'm envisioning a flag that gets sent with the authorization request from my client, that can then be picked up in the login template. Thanks!

**Comment by brockallen** [comment]
Flasg like `EnablePostSignOutAutoRedirect` and `PostSignOutAutoRedirectDelay`?

https://identityserver.github.io/Documentation/docsv2/configuration/authenticationOptions.html

**Comment by nmeierpolys** [comment]
I'm actually looking for a way to pass additional information to the Identity Server for the Login page. I'm already using `EnablePostSignOutAutoRedirect = true` to redirect to my application. At that point, the user doesn't have rights to do anything, so I'm immediately redirecting to the Identity Server login page.

Here's the desired workflow:
1. User clicks Log Out in my app
2. My app logs the user out via Identity Server
3. Identity Server redirects to my app so it can clear any user-specific state
4. My app redirects to the Identity Server Login page
5. The Identity Server Login page shows the message text "You have been successfully logged out" in addition to the usual username field, password field, and Login button.

**Comment by brockallen** [comment]
Why not make your post logout redirect uri hit a page in your client that's allows anonymous access?

As a side note, doing auto redirect to your app is not highly desirable due to how SLO works:  http://brockallen.com/2016/02/08/single-sign-out-and-identityserver3/

**Comment by nmeierpolys** [comment]
Thanks for the help. I considered redirecting to a page that allows anonymous access, but was trying to simplify steps for the user. That's a reasonable fall-back option if there isn't a good way to pass custom information through the authorization request to the Login page.

**Comment by brockallen** [comment]
So you can pass custom data in the acr_values -- check the authorization endpoint docs. I just worry that too much customization and clever code might end up being problematic (especially when it relates to redirecting the user -- read up on open redirect attacks).

**Comment by nmeierpolys** [comment]
Okay, I'll take a look. Thanks for all the help, and all your work on this project.
