### ISSUE TITLE
Configuring CspOptions & x-frame-options

### ISSUE THREAD

**Issue by shaneprice** [IdentityServer/IdentityServer3#2595]
First things first, I would like to thank you guys for all the hard work you have done building IdentityServer. 

I am having some troubles trying to get CSP working with my IdentityServer.

My architecture consists of
A solution containing my IdentityServer (running on https://localhost:44335)

My CspOptions configured like

```
     CspOptions = new CspOptions()
                    {
                      FrameSrc  = "https://localhost:44302 https://localhost",
                      Enabled = true,
                      ConnectSrc = "https://localhost:44302 https://localhost"

                    }
    
```

I have another solution containing the 3 projects

- An MVC application - https://localhost:44300
- A WebApi application - https://localhost:44301
- A Mvc Application with a simple index page https://localhost:44302/

The mvc app running on port 44302 only contains a view with an iframe which points to the other mvc application

```
@{
    ViewBag.Title = "Home Page";
}

My application normally only uses the MVC app port:44300 & webapi :44301 with the identity server and it works fine however....... I am connecting my application with a 3rd party application who host my application inside an iframe within their application.
I am using the simple app (port:44302) to mock using my application like it would in production.


<iframe src="https://localhost:44300" width="500px" height="500px;"></iframe>
```

When I try running the project with Firefox or chrome I get this error

> Refused to display 'https://localhost:44335/core/login?signin=70b9a81b61ed821829f44ee3ee1ed8a8' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

Running it in edge seems to work ok.
Looking in the request header I see

```
x-content-security-policy:default-src 'self'; script-src 'self' ; style-src 'self' 'unsafe-inline' ; img-src *; connect-src https://localhost:44302 https://localhost;frame-src 'self' https://localhost:44302 https://localhost; report-uri https://localhost:44335/core/csp/report
x-content-type-options:nosniff
x-frame-options:SAMEORIGIN

```

Is my problem due to the x-frame-options? - which is set to SAMEORIGIN.

Is there anyway around the problem I am having?

**Comment by brockallen** [comment]
Ah, perhaps XFO is confusing FF when you also have CSP frame-src. I can look into it (but it won't be for a few days).

**Comment by shaneprice** [comment]
Thanks Brock I appreciate your help

**Comment by merijndejonge** [comment]
Perhaps any news on this?
I'm developing a browser extension for different browsers. Unfortunately, creating and managing a new window from within a browser extension leads to all kinds of problems. Therefore I want to experiment with the option to load the login pages in an iframe. The X-Frame-Options' to 'SAMEORIGIN'. issues prevents me from doing this. I tried different settings for CspOptions  but this didn't help.
Thanks in advance for any help/suggestions/tips.

**Comment by shaneprice** [comment]
Hey Brock have you had a chance to look at this one yet?

**Comment by brockallen** [comment]
I was able to repro this. I had misread your original question and thought it worked in Chrome but not FF. Seems they're both treating this as an error. So yea, it's not surprising.

**Comment by brockallen** [comment]
I did some quick searching and I can't find anything that mentions rules about CSP overriding XFO if both are present.

**Comment by shaneprice** [comment]
Ok thank you. I will do some more research tonight and see what I can find

**Comment by brockallen** [comment]
Any update?

**Comment by jturnage** [comment]
Late to the party, but in some owasp conversation:
https://www.owasp.org/index.php/Content_Security_Policy_Cheat_Sheet
in the 'Preventing Clickjacking' section:

> A word about support. Not supported in all browsers yet, Chrome 40+ and FF 35+ support, but will also default to X-Frame-Options if it exists. Spec says, CSP should take precedence. https://w3c.github.io/webappsec/specs/content-security-policy/#frame-ancestors-and-frame-options

However that link anchor appears invalid now but I semi-trust it's there just been renamed over time.

We're in need of this also, but if the CSP will take precedence over the XFO:SameOrigin then it might meet our needs.  We need to be able to host the signin in an iframe in another domain (that's ours).
