### ISSUE TITLE
CustomViewService to render password change page

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2596]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I have updated this question after exploring further.
I have a few questions that I couldn't find in a sample. Probably not all in one place.

We want to provide a link to change password in our SPA and configure the Idp to handle it. The Idp's servicefactory already points to our Cassandra DB.

I have checked the _CustomViewService_ source and looked at the code that renders a custom view. 

1. Owin Middleware validates the token. What kind of validation in the flow ?
2. Partial login authentication check.
3. CustomViewService is invoked to render the custom page. This is a redirection
4. The custom page takes the new password and hits our controller and updates in the DB.
5. Redirect back to our home page.

I have searched other issues. Maybe an exact sample is not available ?

### Relevant parts of the log file
.
```
                At this time the code is not ready to log
```

**Comment by mohanr** [comment]
I have look at some more issues and realize that it could be a feature related to _partial login_ and _resume_. But I still couldn't get the full flow.

**Comment by brockallen** [comment]
No -- you'd just make this some other page hosted in the same place as IdentityServer. It's not something you'd run inside of IdSvr.

**Comment by mohanr** [comment]
I understand that it is hosted in the same place. It is this flow that I am trying to understand. There are two redirections.

1. Partial login authentication check.
2. CustomViewService is invoked to render the custom page. This is a redirection
3. The custom page takes the new password and hits our controller and updates in the DB.
4. Redirect back to our home page.

**Comment by mohanr** [comment]
I understand that it is hosted in the same place. It is this flow that I am trying to understand. There are two redirections.

1. User requests for Password Change page by clicking a link in the home page. 
2. Partial login authentication check.
3. CustomViewService is invoked to render the password change page. This is a redirection(http 302). _Is this correct ?_
4. The custom page takes the new password and hits our controller and updates in the DB.
5. Redirect(http 302) back to our home page. _Is this correct ?_

I am referring to these.

I am referring to this. 'Change Password' is mentioned in 'docs' but not in 'docsv2'

[http://identityserver.github.io/Documentation/docsv2/advanced/userService.html](url)
Partial login

In addition to a full login, the authentication APIs can perform a “partial login”. A partial login allows the user service to interrupt the user’s login workflow and redirect them to a custom page where they must perform some action before they can continue to login (e.g. performing 2fa, completing a registration form, or accepting a EULA).


[http://identityserver.github.io/Documentation/docs/advanced/userService.html](url)

This is useful to customize the user’s workflow before allowing them to fully login. This could be useful to force a user to fill in a registration page, change a password, or accept a EULA before letting them continue.

**Comment by brockallen** [comment]
I'd suggest getting the partial login samples working and spend time to understand how they work. Once you've done that, perhaps ask questions about those since it's a code base that I know is working.

**Comment by mohanr** [comment]
I will close this and ask specific questions.
