### ISSUE TITLE
Issue with running IdentityServer3 behind a load balancer 

### ISSUE THREAD

**Issue by idqfizz** [IdentityServer/IdentityServer3#2597]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I am working on a project where we will use the Thinktecture IdentityServer v3 as our STS. To start with we will be using the client credentials flow with reference access tokens. 

The identity server is configured as follow in the Startup.cs

```
var factory = new IdentityServerServiceFactory()
                .UseInMemoryUsers(new System.Collections.Generic.List<InMemoryUser>())
                        .UseInMemoryClients(Clients.Get())
                        .UseInMemoryScopes(Scopes.Get());

            var options = new IdentityServerOptions
            {
                Factory = factory,
                RequireSsl = bool.Parse(ConfigurationManager.AppSettings["RequireSsl"]), 
                PublicOrigin = ConfigurationManager.AppSettings["PublicOrigin"],
                IssuerUri = ConfigurationManager.AppSettings["IssuerUri"]
            }
```

Where:

- RequireSsl = false
- PublicOrigin = https://domain.com/IdentityServer
- IssuerUri = domain.com/IdentityServer/connect/token 

The Clients.cs setup is like this:

```
public class Clients
    {
        public static List<Client> Get()
        {
            return new List<Client>
            {
                new Client
                {
                    ClientName = "Trusted Internal Client",
                    Enabled = true,
                    ClientId = "trustedinternal",
                    AccessTokenType = AccessTokenType.Reference,
                    ClientSecrets = new List<Secret>
                    {
                        new Secret("somesecret".Sha256())
                    },
                    Flow = Flows.ClientCredentials,
                    AllowedScopes = new List<string>
                    {
                        "TestScope"
                    }
                }
            };
        }
    }
```

And the Scopes.cs is like this:

```
public class Scopes
    {
        public static IEnumerable<Scope> Get()
        {
            return new[]
                {
                    new Scope
                    {
                        Name = "TestScope",
                        DisplayName = "Test Scope",
                        Type = ScopeType.Resource,
                        Emphasize = false
                    } 
                };
        }
    }
```

I have this set up in our test environment and it works good. Now im trying to figure out how to make this work in the following load balanced environment. 

Machine A and B behind a F5 load balancer. Each machine have one identical identity server and one identical Web API installed.

The Web API Startup.cs is configured to use identity server as follows:

```
app.UseIdentityServerBearerTokenAuthentication(
                    new IdentityServerBearerTokenAuthenticationOptions
                    {
                        Authority = ConfigurationManager.AppSettings["AuthorityUrl"],
                        ValidationMode = ValidationMode.ValidationEndpoint,
                        RequiredScopes = new[] {"TestScope"}
                    });
```

Where:

- AuthorityUrl = https://domain.com/IdentityServer

The IdentityServer application in the IIS is also configured to use a specified validation and decryption key on both machines. So each of their Web.config contains the following entry.

```
 <system.web>
        <compilation debug="true" targetFramework="4.5" />
        <httpRuntime targetFramework="4.5" />
            <machineKey decryptionKey="296ED8C9B701E36094A6820FB0D5594E65C4971EF9A5C1FT" validationKey="325E5D1C4CC0B477A0ABBDDA78B9E39834CE821DD8C4E3BE65F167444B45F051DBD2E3A0FD9478D8E201E546C6FBD533B317A3EBC105A767D6FBCC89C55221AW" />
      </system.web>
```

Calling the Web API providing a token received from IdentityServer on machine A and the Web API validates the token against the same IdentityServer works fine. But if the token is validated against the IdentityServer on machine B, i.e. validation is done against the IdentityServer that did not create the token I get a 401 "Authorization has been denied for this request". With the following exception in the IdentityServer logs.

### Relevant parts of the log file

```
 Start access token validation request
    [Information] Start access token validation
    [Error] "Token handle not found"
    "{
      \"ValidateLifetime\": true,
      \"AccessTokenType\": \"Reference\",
      \"TokenHandle\": \"2df4a49eddcdcf9245f10a37aba89c47\"
    }"
    [Information] Returning error: invalid_token
```

Would really appreciate some input on what I have missed to make this work.

**Comment by leastprivilege** [comment]
Are you providing a persistent store for the reference tokens that is shared between your server instances?

**Comment by leastprivilege** [comment]
..and have you read:

https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

**Comment by idqfizz** [comment]
No I do not use a persistent store for the tokens. Read the document but missed the require part of operational data. As it worked for a one server setup I thought that as long as the machine keys where in sync the token created could be validated by either part.

**Comment by leastprivilege** [comment]
Right - under the covers we deploy a couple of unicorns that take care of data synchronization between your servers ;)

**Comment by idqfizz** [comment]
Thats to bad :) So correct me if im wrong but if I don't have the option to implement a persistent store I could use JWT's instead of reference tokens?

**Comment by leastprivilege** [comment]
yes you can use JWTs instead.
