### ISSUE TITLE
Application without cookies for authentication

### ISSUE THREAD

**Issue by jothikiruthika-jltasia** [IdentityServer/IdentityServer3#2598]
I have an application that doesnt use cookies for persisting the authentication information.

I request an id_token and access token from the idserver, upon successful authentication, the idserver returns the id_token and access token. Instead of using the id_token and creating the authentication cookie, I am passing the access_token as the bearer token and thus authenticating myself with the web application with every request. Is this the right approach or am i missing something? 

my problem is that I am not receiving the email, profile claims, associated with the default email and profile scopes in both the id_token and the access_token. 

I am using aspnet identity to extend the userService to create users through an api call. Is there any fundamental mistake in this approach? Please advise

**Comment by leastprivilege** [comment]
that's fine. you can use the scope configuration to define which claims goes into which token. Since you are in JavaScript you probably want to use the userinfo endpoint (using the access token) to retrieve the claims and keep the tokens small.

**Comment by jothikiruthika-jltasia** [comment]
Thank you. Just another quick question. When i add the family_name claim to the set of claims returned from GetClaimsFromAccount method, the claims returned has a diffferent name as surname. Do we have control over this name? Is there a place where this default can be changed?
