### ISSUE TITLE
Changes in IdentityProvide claim and issuer

### ISSUE THREAD

**Issue by omidkrad** [IdentityServer/IdentityServer3#2599]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
Hi, I upgraded IdentityServer nuget on my project to the latest (ver 3.2.4.1). Now when I log-in I see that some of the claims that used to be there are missing now. For example, there used to be a claim type of `"idp"` or `"http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider"` which are not available anymore. Also the issuer for the claims now shows as `"LOCAL AUTHORITY"` where used to be base address of the Identity server such as `"https://localhost:44333/core"`. Why are these gone and how can I add them again?

Thanks!

### Relevant parts of the log file

```
N/A
```

**Comment by leastprivilege** [comment]
> Now when I log-in I see that some of the claims that used to be there are missing now.
Log in to what? see where?

We still issue an idp claim - as for setting the issuer - that's not identityserver doing - that the client library. Which client library are you using?

**Comment by omidkrad** [comment]
I'm logging in to IdentityServer like in [AspNetIdentity](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity) sample and on the client side using [IdentityModel](https://www.nuget.org/packages/IdentityModel/) (1.8.0) client library.

**Comment by leastprivilege** [comment]
adding idp in userservice is totally fine. As I said - the issuer property is not set by the identityserver - that is the job of the client library.

I suggest you try our client samples and see if you can repro it there.

**Comment by brockallen** [comment]
Any progress?

**Comment by omidkrad** [comment]
I didn't get time to work more on this, but we are ignoring the issuer at the moment and looking only at the idp claim. I will close the issue. Thanks.
