### ISSUE TITLE
Thinktecture.IdentityServer.Core.Validation in 1.6.3

### ISSUE THREAD

**Issue by dknaack** [IdentityServer/IdentityServer3#2600]
Ive recently updated to version 1.6.3 coming from 1.6.2. 
Now Thinktecture.IdentityServer.Core.Validation is not available anymore. 

Where is it going and is a changelog available?

Thanks in advance!
Great work!

**Comment by leastprivilege** [comment]
The only thing that got changed in 1.6.3 is the addition of a readme file that tells you to finally update to 2.x ;)

**Comment by dknaack** [comment]
Oh ok :) Thanks!
