### ISSUE TITLE
AuthenticationOptions.CookieOptions.IsPersistent not working

### ISSUE THREAD

**Issue by aaronlt** [IdentityServer/IdentityServer3#2601]
Hi, we are using IdentityServer3 v2.4.0.0.

And it seems that option `AuthenticationOptions.CookieOptions.IsPersistent = true` doesn't work. 
Meaning emitted authentication cookie is still session based. (RememberMe option works correctly)

Think issue is here:
https://github.com/IdentityServer/IdentityServer3/blob/f7856c12791289e4864d817caeb0c38f512c68ac/source/Core/Configuration/Hosting/SessionCookie.cs#L60

I can provide PR if anyone with better knowledge of source agrees.

**Comment by brockallen** [comment]
If you present the "remember me" option to the user, then why configure `IsPersistent`? If the "remember me" is shown, then we honor the user's preference over the server config.
