### ISSUE TITLE
Server and Client in one Project

### ISSUE THREAD

**Issue by eaba** [IdentityServer/IdentityServer3#2602]
I have a Controller added to the Project hosting IdentityServer that I want to protect.
I tried something like below within same Startup class which did not work:
`app.UseIdentityServer(options);`
`app.UseIdentityServerBearerTokenAuthentication(new`
`IdentityServerBearerTokenAuthenticationOptions`
           `{`
                `Authority = WebConfigurationManager.AppSettings["Authority"],`
                `RequiredScopes = new[] { "read", "write" }`
            `});`

**Comment by leastprivilege** [comment]
"did not work" does not help.

**Comment by pianzide1117** [comment]
Now ,I am suffering this too.

**Comment by pianzide1117** [comment]
@eaba I get a solution.
`
app.UseIdentityServer(options);
app.Map("/api",apiapp=>{
apiapp.UseIdentityServerBearerTokenAuthentication(new
IdentityServerBearerTokenAuthenticationOptions
{
Authority = WebConfigurationManager.AppSettings["Authority"],
RequiredScopes = new[] { "read", "write" }
});
})

`
