### ISSUE TITLE
Getting claims in the 2nd hop

### ISSUE THREAD

**Issue by venkatrv** [IdentityServer/IdentityServer3#2604]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
I have MVC application (MVC OWIN Client (Hybrid)) calling the identity server and getting token and claims, and then calling the SampleWebAPI applicaiton by passing the access token.
here is the SampleWebAPI is called:

public async Task<ActionResult> CallApi()
        {
            var token = (User as ClaimsPrincipal).FindFirst("access_token").Value;

            var client = new HttpClient();
            client.SetBearerToken(token);

            var result = await client.GetStringAsync(Constants.AspNetWebApiSampleApi + "identity");
            ViewBag.Json = JArray.Parse(result.ToString());

            return View();
        }

But I am not receiving all the claims into SampleWebAPI. Access token supposed to contain all claims. right? it is showing only standard claims, not the one I added. Any reason?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
You need to configure `Claims` (and `ScopeClaim`s) on the web api scope if you want info for the user in your web api.
