### ISSUE TITLE
Resigning the identity token

### ISSUE THREAD

**Issue by venkatrv** [IdentityServer/IdentityServer3#2605]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
Is it possible to send identity token to IdentityServer and get re-signed token?
for example, say I have two domains: Domain1 and Domain2
Application in Domain1 need to access an application in Domain2.
I have installed one Identity server in each domain. So application in Domain1 need to talk get token from Domain2 identity server and send this token to Domain2 application. Please note that, application in Domain1 is already have a token issued from Domain1 identity server.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
No. you rather would establish trust between the identity servers. But each application needs to do its own authentication request.

**Comment by venkatrv** [comment]
Thanks for reply. Is there a mechanism to setup the relying party trust in Identityserver? (similar to ADFS)
If not, what is the best secured mechanism you can suggest for trusting idenityserver(s) each other?

**Comment by leastprivilege** [comment]
You'd setup one idsrv as a client to another - and in the other direction as an external idp.

**Comment by venkatrv** [comment]
Well, I am able to pass Domain1 claims (using Domain1 application) as a payload to Domain2 identityserver, and get the Domain2 IdentityServer token with Domain1 claims. Once Domain1 application has the Domain2 idsvr token, I am able to call Domain2 application with Domain2 idsrv token.
Domain1 application is configured as a client in Domain2 idsvr(that's how Domain1 application is able to call Domain2 identityserver)
Is there a security concern in the above approach?
