### ISSUE TITLE
Get list of users registered in IdSrv from a client

### ISSUE THREAD

**Issue by inongogo** [IdentityServer/IdentityServer3#2607]
### Question
Thanks for your fantastic job on this project and all your blog posts and presentations. I really solves a lot of peoples problems in one of the most difficult and important parts of an web application!

I got a follow up question related to the question at #1168.

My client app needs a list of all the project managers based on their claims to be able to assign them to different projects and I need to handle this situation in some way. 

One way is to implement an endpoint on the IdSrv for the client's user to request a list of users but that increases the attack surface on the STS which isn't ideal. Is this a recommended approach to implement such a feature or is there a better solution? 

Is it a better solution to manage a separate table on the client's database containing a copy of all the users to it? It requires one to duplicate the data and store and manage it in two places and that doesn't make a lot of sense.

Do you know of an implementation which has solved this issue or an example of how to to it?

Thanks!

**Comment by leastprivilege** [comment]
why do you need to duplicate the data store? just build a service that has access to the data you need.

**Comment by inongogo** [comment]
Thanks for the quick reply!
Do you mean I should implement an api (controller) on the IdentityServer that returns the users who has a certain claim or implement a service on the client that accesses the data in the database directly?

**Comment by leastprivilege** [comment]
Why does it need to be on the identityserver? do it wherever you want.

**Comment by inongogo** [comment]
Right, I should have said before that I wanted to avoid duplicate the logic concerning getting a user by claims and managing the models for the AspNet.Identity tables AspNetUsers, AspNetRoles, AspNetUserClaims, etc.
I understand that I could implement the service elsewhere but since I use Asp.net Identity and Entity Framework on the IdentityServer3 I then, as I see it, have to:
-  Manage all the models required by AspNet Identity in the application where the user lists are going to be used
-  Implement the logic in the application where the service is located to filter users by claims in order to retrieve the correct users, etc.

I was hoping to avoid this since it feels like double work.

**Comment by leastprivilege** [comment]
Your asp.net / entity model should be in a library anyways - and I am not saying you can't have the API "on" the identity server. 

What I am saying is, this API does not belong **to** identityserver - it is some additional functionality that you are providing that is not part of "authentication as a service".

**Comment by inongogo** [comment]
Ah, right. I'm having an unpresidented hard time to understand the entire flow when it comes to oauth2, openidconnect and how claims, registrations, data access and so on fits together. 

Thanks for you help!

**Comment by malichishti** [comment]
Hi @inongogo 

 Did you manage to achieve this? if yes can you guide me on how you did it? as i have a similar requirement.

Thanks

**Comment by inongogo** [comment]
Hi @malichishti ,
Sorry for my late reply. As @leastprivilege wrote, you need to write the logic to handle the listing of the users. This means that you might creat different application which interacts (read and/or writes) with the user database.

First, I thought this was a little weird and it felt like this new application was interfering with the IdentityServer´s responsibilies and it felt like a major potential security issue but then a got over it. I had trouble understanding that IdentityServer´s responsibility is only to authenticate the users. Everything else is "up for grabs", so to speak.
