### ISSUE TITLE
Sync HTTP front-channel logout implementation with spec updates

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#2608]
https://openid.net/specs/openid-connect-frontchannel-1_0.html

**Comment by leastprivilege** [comment]
done https://github.com/IdentityServer/IdentityServer3/commit/9af8f1d53dd7a8f271c05ed68b820897e50e2625

ok? @brockallen

**Comment by brockallen** [comment]
I didn't read the updates to the spec yet, so I don't know if those are right :)
