### ISSUE TITLE
Redirect to another page to resend email confirmation when email is not confirmed

### ISSUE THREAD

**Issue by youngdak** [IdentityServer/IdentityServer3#2610]
Please i need your help.
I want to redirect a user who has refused to confirm his/her email to a page where they can resend the email confirmation link whenever they login.
I tried checking for email confirmation in AuthenticateLocalAsync method in Identityserver.AspnetIdentity sample but i really don't know how to redirect the user to another page or i guess i need to implement partial login with redirect but i don't know how. Thanks for your assistance.

**Comment by brockallen** [comment]
Read the custom user service docs on partial logins.
