### ISSUE TITLE
Add an option to suppress all logging output

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#2611]
scenario: 

logging is configured at host level - but don't want to emit idsrv log output (production scenarios, eventing is used instead).

**Comment by leastprivilege** [comment]
Will add a `NoopLogProvider` and a flag on `LoggingOptions`

**Comment by leastprivilege** [comment]
Done on dev.

Add the provider - but no flag for config. Rather docs how to set it up manually:

https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

**Comment by johnkors** [comment]
Does this destroy other logproviders within the same host (for instance if hosting an mvc app side by side with idsrv) were we _do_ want logging?

 `LogProvider.SetCurrentLogProvider(new NoopLogProvider())`

**Comment by leastprivilege** [comment]
It pipes all LibLog traffic to /dev/null

**Comment by johnkors** [comment]
So it will only affect a co-hosted app if that app is also is using liblog..?

**Comment by leastprivilege** [comment]
yes

**Comment by johnkors** [comment]
ok, thanks :)
