### ISSUE TITLE
What is the best practice for storing refresh tokens for WPF and Console client side

### ISSUE THREAD

**Issue by zik319** [IdentityServer/IdentityServer3#2614]
Hi guys.
I'm using IdSrv3 (code flow) with a WPF and Console appliaction on the client size which use the same access token.
I want the user to provide the credentials only once and then just to keep the refresh token on the client side.
I've been looking at [DPAIP](https://msdn.microsoft.com/en-us/library/ms995355.aspx) and [Credential Locker](https://technet.microsoft.com/en-us/library/jj554668.aspx). However I'd like to know what is the best practice to approach my need.

p.s Thanks for all the hard work on IdSrv3 and IdSrv4.

**Comment by leastprivilege** [comment]
Every OS/Platform has some data protection service - on Windows thats DPAPI (and is easy to use from .NET). I don't know how hard it is to use CredentialLocker from plain .NET (they wrapped it in WinRT) but my understanding is, that it also uses DPAPI under the covers.

**Comment by zik319** [comment]
Thanks Dominick @leastprivilege
