### ISSUE TITLE
Question: Small scale application and IdentityServer

### ISSUE THREAD

**Issue by raxitr** [IdentityServer/IdentityServer3#2615]
I am structuring  small scale application (100 users MAX) I have kept Web API project separate than MVC project. 

My question is, Should I use identity server for user authentication so that I can use common authentication between my Web API project and MVC project? I understand Identity server has plenty of configuration option so need advice is it good idea to use IdServer or is there any alternate way to handle this? 

I am certain that I wish to keep my Web API in separate project than MVC project and use common authentication between the two and if the need arise I can expose my Web APIs to third party implementers.

**Comment by leastprivilege** [comment]
Sure - start here:

https://vimeo.com/154172925

**Comment by raxitr** [comment]
Thank you, I have done IdServer integration in the past. My concern was not to overkill the small application with IdServer setup in it. Are there any guidelines what minimum level of setup I must have for IdServer configuration?

**Comment by leastprivilege** [comment]
check the docs on deployent.

**Comment by raxitr** [comment]
Thank you
