### ISSUE TITLE
IdentityServer as RP needing access token

### ISSUE THREAD

**Issue by cbeall** [IdentityServer/IdentityServer3#2619]
In the spirit of microservices, let's say that the user store, user profile store, client store and scope store are resources outside of the OP instance. Those resources are protected and require an access token that ultimately would need to be generated by the OP.

The instance of IdentityServer would need custom IUserService, IClientStore, and IScopeStore implementations that would in effect serve as a client calling their respected resources. What would be the best way for a client living within the IdentityServer instance to obtain an access token? The client could have its own credentials, and for simplicity let's say the registration for that client and its required scopes are hardcoded in their store implementations so that an external call would not need to be made. 

It feels very heavy handed for the OP to have to make an HTTP request to itself in this scenario. The logic found in the TokenEndpointController could be ported into a small service, but I'm wondering if I'm missing a more obvious solution. 

If this is a valid use case that does not have any built in support, would it make a good candidate for a method in OwinEnvironmentExtensions? Something to the effect of:

```
public static Task<Token> GenerateAccessTokenAsync(this IDictionary<string, object> env, string clientId, string clientSecret, IEnumerable<string> scopes)
{
	...
}
```

**Comment by brockallen** [comment]
Yes, I agree.

**Comment by cbeall** [comment]
Great, thanks. Please let me know if there is any way I can help.

**Comment by leastprivilege** [comment]
I did a quick test - you can create tokens by getting the ITokenSigningService from DI like this:

```csharp
using IdentityServer3.Core.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using IdentityServer3.Core.Models;
using System.Security.Claims;

namespace Host.Configuration.Extensions
{
    class ServiceClientTokenStore : IClientStore
    {
        private readonly ITokenSigningService _signer;

        public ServiceClientTokenStore(ITokenSigningService signer)
        {
            _signer = signer;
        }

        public async Task<Client> FindClientByIdAsync(string clientId)
        {
            var token = new Token
            {
                Issuer = "https://idsrv",
                Audience = "https://idsrv/resources",
                Lifetime = (int)TimeSpan.FromMinutes(60).TotalSeconds,
                Claims = new List<Claim>
                {
                    new Claim("client_id", "client.store"),
                    new Claim("scope", "idsrv.backend.apis")
                }
            };

            // get access token for backend service
            var jwt = await _signer.SignTokenAsync(token);

            // stuff
            throw new NotImplementedException();
        }
    }
}
```

This is easy enough to do when you are "inside" idsrv (aka not on a partial logon workflow) - or you do you think we should make that even easier by providing some sort of helper method

`ClientAccessToken(string clientId, string scope)`

?

**Comment by leastprivilege** [comment]
just added this: https://github.com/IdentityServer/IdentityServer3/commit/4e56f192862a9fc26ca0c79af189a35e92d7e1ab

which turns above code into:

```csharp
using IdentityServer3.Core.Extensions;
using IdentityServer3.Core.Models;
using IdentityServer3.Core.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Host.Configuration.Extensions
{
    class ServiceClientTokenStore : IClientStore
    {
        private IDictionary<string, object> _owin;

        public ServiceClientTokenStore(OwinEnvironmentService owin)
        {
            _owin = owin.Environment;
        }

        public async Task<Client> FindClientByIdAsync(string clientId)
        {
            var jwt = await _owin.IssueClientToken("idsrv.clientstore", "idsrv.backend", 3600);

            // stuff
            throw new NotImplementedException();
        }
    }
}
```

happy?

**Comment by cbeall** [comment]
This looks like this will meet my needs. It's even cleaner than what I was proposing (there really is no need to involve a secret). Thank you for your help and for all that you both do for the community.
