### ISSUE TITLE
Exception handler for outage

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2620]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I request for some details about https://github.com/IdentityServer/IdentityServer3/issues/2012. Any code sample ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
It is not implemented yet.
