### ISSUE TITLE
Set Admin Role to User Identity

### ISSUE THREAD

**Issue by MartinGian** [IdentityServer/IdentityServer3#2621]
Hi,

I created a Custom User Service, and now I have to set an Admin role to the user identity, to then invoke a WebApi Controller having the  [Authorize(Roles = "Admin")] attribute.

How can I do?

I try the following:
```
 public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            if (context.UserName.Equals("martin") && context.Password.Equals("martin"))
                context.AuthenticateResult =
                    new AuthenticateResult(
                        subject: "martin",
                        name: "martin",
                        claims: new List<Claim> { 
                            new Claim(Constants.ClaimTypes.Role, "Admin")
                        });
            else
                context.AuthenticateResult = new AuthenticateResult("Error, username: martin, password: martin");

            return Task.FromResult(0);
        }
```

(It is a demonstration)

Can you help me? Thanks!

**Comment by joshpearce** [comment]
Don't do it in `AuthenticateLocalAsync`. Rather do it in `GetProfileDataAsync`.
    
    public Task<IEnumerable<Claims>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimsTypes = null) {
        
        // use the subject to look up your user
        var identity = new ClaimsIdentity();
        identity.AddClaim(new Claim("role", "some role"));
        // add more claims 
        identity.AddClaim(new Claim("sub", "martin"));
        identity.AddClaim(new Claim("Name", "Jim"));
        ...
        var returnClaims = identity.Claims;
        // filter claims if requested
        if (requestedClaims != null) {
            returnClaims = returnClaims.Where(c => requestedClaims.Contains(c.Type));
        }
        return Task.FromResult(returnClaims);
    }

**Comment by MartinGian** [comment]
Thanks! It worked!
