### ISSUE TITLE
Question: invalid_grant error

### ISSUE THREAD

**Issue by omidkrad** [IdentityServer/IdentityServer3#2623]
### Question
Hi, I'm trying to get a WPF app (hybrid client) to log-in with Identity Server, and I get `invalid_grant` error. From the [RFC description](https://tools.ietf.org/html/rfc6749#section-5.2):

> **invalid_grant**
The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

This is a very generic description and doesn't help at all. On the response message also I have nothing more than `{"error": "invalid_grant"}`.

[Related post](https://github.com/IdentityModel/Thinktecture.IdentityModel.45/issues/82#issuecomment-19663250)

> leastprivilege commented on Jun 18, 2013
invalid_grant typically means the username/password is incorrect.

I know username/password are correct in my case because I can use them to log-in to an MVC hybrid client.

In the log (added below) I have: `Unexpected code_verifier with Flow Hybrid` Can you please help me understand it?

Thanks!

### Relevant parts of the log file
```
iisexpress.exe Informaion: 0 : 2016-02-23 11:19:32.719 -08:00 [Information] Client validation success
iisexpress.exe Information: 0 : 2016-02-23 11:19:32.724 -08:00 [Information] Start token request validation
iisexpress.exe Information: 0 : 2016-02-23 11:19:32.728 -08:00 [Information] Start validation of authorization code token request
iisexpress.exe Error: 0 : 2016-02-23 11:19:32.732 -08:00 [Error] Unexpected code_verifier with Flow Hybrid
 {
  "ClientId": "myapp-wpf",
  "ClientName": "My Desktop Application",
  "GrantType": "authorization_code",
  "AuthorizationCode": "e4e980b7331b17c1552e64e146e961db",
  "Raw": {
    "grant_type": "authorization_code",
    "code": "4e146e961dbe4e983b7343b17c1552e6",
    "redirect_uri": "oob://myapp.com/wpf-client",
    "code_verifier": "f7a851d1c9f5d907df82ee5ad9e4fb8978bf189651b9bab06e8b39fc5d3df56e"
  }
}
iisexpress.exe Information: 0 : 2016-02-23 11:19:32.733 -08:00 [Information] End token request
2016-02-23 11:19:32.734 -08:00 [Debug] [2016-02-23T19:19:32.7345370Z] Level=Info, Kind=End, Category='System.Web.Http.Action', Id=80003284-0007-f400-b63f-84710c7967bb, Message='Action returned 'IdentityServer3.Core.Results.TokenErrorResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
iisexpress.exe Information: 0 : 2016-02-23 11:19:32.735 -08:00 [Information] Returning error: invalid_grant
```

**Comment by brockallen** [comment]
"Unexpected code_verifier with Flow Hybrid" means you're passing a code verifier for the PKCE spec. Is this intentional? If your client wants PKCE then configure it with the appropriate Flow (AuthorizationCodeWithProofKey or HybridWithProofKey).

**Comment by omidkrad** [comment]
In the call to `request.CreateAuthorizeUrl` I removed the `codeChallenge` parameter, which was created from the `verifier` field, and that fixed the error. Thank you.
