### ISSUE TITLE
CustomGrantValidationResult defaults to IsError == true

### ISSUE THREAD

**Issue by chedabob** [IdentityServer/IdentityServer3#2625]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

When using an object initializer for `CustomGrantValidationResult`, the `IsError` property is always set to true. 

`new CustomGrantValidationResult {` 
`        Principal = foo` 
`}`

It is set explicitly in the constructor for `ValidationResult`: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/ValidationResult.cs#L29

The documentation for `CustomGrantValidationResult` implies that this should be false: 
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/CustomGrantValidationResult.cs#L47-L51

The net result of this is that token validation always fails with `Invalid Grant` because this branch is hit: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/TokenRequestValidator.cs#L685-L689

Should it be possible to use an object initializer, and if so, should `IsError` be set to false in the parameterless constructor, or should it be set to false in the superclass?

**Comment by brockallen** [comment]
Why not use the ctor that indicates the success values?

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/CustomGrantValidationResult.cs#L60

**Comment by chedabob** [comment]
I am using that now and it works, but I only got there through hours of debugging and poring over the IdentityServer3 source.

If it's the case that the parameterless constructor shouldn't be used, I'd like to create a pull request to make that clear for anybody else that runs into this issue. I just want to make sure that my understanding of it is right.

**Comment by leastprivilege** [comment]
Well - the paramless ctor is not ideal - but valid if you know what you are doing. 

If I could get rid of it I probably would - but that would be a breaking change.
