### ISSUE TITLE
Query parameters are missing

### ISSUE THREAD

**Issue by malichishti** [IdentityServer/IdentityServer3#2626]
I am using Identity Server3. Upon redirect after a successful login, my query parameters on original requested url gets lost.
Example: 
Registered Client with RedirectUri: http://abc/
Flow:
Requested Url: http://abc/def?Id=10
Unauthorized, redirecting to Identity Server
Successful login 
Redirected to http://abc/def
MISSING query parameter
I'm new with this identity stuff, so please let me know if i'm assuming something wrong?

**Comment by leastprivilege** [comment]
Which client library are you using?

**Comment by malichishti** [comment]
Sorry, i forgot to mention, on the client side i'm using Microsoft OpenId Connect

**Comment by leastprivilege** [comment]
I am surprised that the query strings are no roundtripped. 

The middleware has a notification `RedirectToIdentityProvider` - in there you can store any state that you want to preserve. Maybe give that a try.

If this does not work for you - you need to consult MS documentation / forums.

**Comment by malichishti** [comment]
Thanks for the suggestion, i was wondering how to store it in `RedirectToIdentityProvider` as there is no session at that point, any ideas will be appreciated.

**Comment by brockallen** [comment]
I'd suggest double checking that the OIDC MW doesn't preserve query string params.
