### ISSUE TITLE
Problems with links from Microsoft Office Applications

### ISSUE THREAD

**Issue by ngelote** [IdentityServer/IdentityServer3#2627]
When clicking on a link in Microsoft word or other Microsoft Office applications(but not Outlook) to a MVC site protected by Identity Server the following error is displayed.
There is an error determining which application you are signing into. Return to the application and try again. 

This is a know issue with Office url prefetching and cookie based authentication but as I don't have control of the clients I need a server side fix. Here is a good description of the problem and how someone solved in a different auth system.
https://www.wimpyprogrammer.com/microsoft-office-link-pre-fetching-and-single-sign-on/ 

Is their any way to get access early enough in the pipeline to detect the http-user-agent sms-office to return http 200? 

I know that this is not really an Identity server problem but people are embedding valid links to my site in their office documents and it is hard to explain why this weird error message is showing up and I have to do a server side fix to effectively solve it.

Thanks,
Nick

**Comment by brockallen** [comment]
The issue seems to be that office assumes ws-fed as the SSO protocol where this behavior is likely acceptable. With OIDC or SAML2-P (as your link illustrates) this is an incorrect assumption. 

IMO, you should solve this by detecting that header in your app itself. The reason is that your app needs to be the one to trigger the OIDC redirect since the app needs to issue a cookie prior to leaving your app's host.

**Comment by brockallen** [comment]
FWIW: https://twitter.com/vibronet/status/702353130260791299. maybe we'll get some more inside info.

**Comment by joshpearce** [comment]
How about this:

1. Your app checks for a cookie, "im-a-real-browser" in some pre-authentication middleware.
2. If the cookie is not there, it returns a 200 page, that writes that cookie, and also has a [META](http://stackoverflow.com/questions/22551976/why-does-chrome-not-redirect-using-meta-refresh) refresh tag back to itself?
3. When the cookie is there, it proceeds as normal.

Also, some good links at the bottom of [this](http://webmasters.stackexchange.com/questions/71112/make-server-force-excel-to-hand-over-hyperlink-to-browser-without-trying-to-load) page. MS has gone so far as to write an article suggesting how SSO authors can change their entire design to support this "feature."

**Comment by brockallen** [comment]
Since this is pretty much out of our control, I'll close this.
