### ISSUE TITLE
Storage implementations for RavenDB

### ISSUE THREAD

**Issue by bjarteskogoy** [IdentityServer/IdentityServer3#2628]
I've made storage implementations using RavenDB as persistent storage.
Would be happy with getting some feedback, code review or anything useful.

The source can be found here: https://github.com/Agrando/IdentityServer.Contrib.RavenDB

**Comment by leastprivilege** [comment]
I tweeted about it.

**Comment by brockallen** [comment]
I updated the community resources docs.

**Comment by bjarteskogoy** [comment]
Added admin support as well.

**Comment by leastprivilege** [comment]
Not sure this is the right forum to "advertise" something. Did you write a blog post or similar? I am happy to tweet it.

**Comment by leastprivilege** [comment]
closing for now
