### ISSUE TITLE
You have not given permission to any applications ! permission lost !

### ISSUE THREAD

**Issue by sadeghhp** [IdentityServer/IdentityServer3#2629]
Hi, 
i have using aspnetidentity version of application. after allowing an application to use oauth and permission, where is the data that stored in database ? bacause after a while, and next time user want to loggin, he directed to oauth server and again it ask for scope permissions !
is it ok to not storing permitted data ?
it said : "You have not given permission to any applications" but i have give permissions before

**Comment by leastprivilege** [comment]
you need to implement the IConsentStore interface if you want to store permission decisions.
