### ISSUE TITLE
Is this the way to go? (anyone please)

### ISSUE THREAD

**Issue by ChristianMikkelsen** [IdentityServer/IdentityServer3#2631]
Hi All

I have read and tried nearly all of the samples.
To figure out if IS3 can be used to solve my issue.
Here is my issue/senario:
Got lots of diffrent IIS running crosssite atm. using old ASP membership, and adaptet into Identity by converting into identity cookie on the fly when loging in, so some of the newer MVC projects can use that. (works Fine).
To work with some of our customers i sync. my old membership base (there have expanded with multible layers, firms, orgs. and so on.) with thir AD each morning.
But of cuse they now want to use Federation Service. (ADFS)
So if I have understand it correctly:

I build an IS3 and configure it like this:
**Adds Clients:** For each Web/main projects/site I currently have their need to be accessed. (adds the support their offcuse)

**Q:Adds RelyingParty:** For each Customer firms ADFS their needs Access.
Right?

Q:
And i only need to use wsFederation if i want to use my own windowsADFS - as I dont want.
Or do i still need that when it is relyingParties?

Then I write a wrapper for my old membership to use CustomUsers..into Scopes and Claims.

Is it possible to connect to multible Firms ADFS like connecting to Facebook/Google and so on - thats my main issue, but think i got mixed a little up, in views of my Own ADFS or Accessing parties ADFS.

And this in sample:

                `new RelyingParty
                {
                    Realm = "urn:owinrp",
                    Enabled = true,
                    ReplyUrl = "http://localhost:10313/",
                    TokenType = TokenTypes.Saml2TokenProfile11,
                    TokenLifeTime = 1,

                    ClaimMappings = new Dictionary<string, string>
                    {
                        { "sub", ClaimTypes.NameIdentifier },
                        { "name", ClaimTypes.Name },
                        { "given_name", ClaimTypes.GivenName },
                        { "email", ClaimTypes.Email }
                    }
                }`

This is put into UseIdentityServer Via wsfed.. Plugin method

Compared to this in doc:
` 
   var adfs = new WsFederationAuthenticationOptions
   {
      AuthenticationType = "adfs",
      Caption = "ADFS",
      SignInAsAuthenticationType = signInAsType,
      MetadataAddress = "https://adfs.leastprivilege.vm/federationmetadata/2007-      06/federationmetadata.xml",
      Wtrealm = "urn:idsrv3"
    };
  app.UseWsFederationAuthentication(adfs);}
`
Is put into ServerOption without plugin?

/Christian

**Comment by leastprivilege** [comment]
I am not sure I follow - but what you call relying party looks to me like external identity providers.

IdSrv can connect to your customer's ADFS (multiple) to provider SSO/access to your applications.

**Comment by leastprivilege** [comment]
I am not sure this is a question that can be easily answered in such a forum - maybe you need some architecture consulting - let us know if we can help this way.

**Comment by ChristianMikkelsen** [comment]
Thanks yes externals identity providers, i tried both examples, the one from documentation where i could add it like google, did only have google to pick and plugins (maybe the sample i was expanding missed something but had installed the is3.wsfed.
Any way the plugin method worked from the qouted code in first message.
How to get som consulting, and whats the price?
Cuse this is a big and very different area, compared to my normal coding of analyzing engines.

**Comment by leastprivilege** [comment]
contact identity@leastprivilege.com for consulting.
