### ISSUE TITLE
Logout link or auto-redirect with ADFS via WsFederation

### ISSUE THREAD

**Issue by charettedavid** [IdentityServer/IdentityServer3#2633]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is there a way to redirect the user back to the web application after signout with ADFS?
I end up on the "logout success" page of the ADFS with no link and no auto-redirect.

Thank you

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Does ADFS support wreply (I honestly don't remember)? If so, then yes. I just recently discussed this here:

http://brockallen.com/2016/02/09/federated-sign-out-and-identityserver3/

**Comment by cbomkamp** [comment]
I may be wrong, but I think that ADFS only supports using a wreply on the same domain as the relying party (IdSvr). In my case, my client application is on a different domain than IdSvr, so I had to set the wreply to a URL on IdSvr, when then redirected back to the client application.

The code below only works if you only have a single client using ADFS.  If you have multiple client applications, you'd have to somehow determine which client you should return to after signout.

```
var adfs = new WsFederationAuthenticationOptions
{
    AuthenticationType = "adfs",
    Caption = "ADFS",
    SignInAsAuthenticationType = signInAsType,
    MetadataAddress = ConfigurationManager.AppSettings["AdfsMetadataAddress"],
    Wtrealm = ConfigurationManager.AppSettings["AdfsRealm"],
    Notifications = new WsFederationAuthenticationNotifications
                        {
                            RedirectToIdentityProvider = n =>
                                {
                                    if (n.ProtocolMessage.IsSignOutMessage)
                                    {
                                        n.ProtocolMessage.Wreply = ConfigurationManager.AppSettings["PublicOrigin"] + "/identity/clientapp/logged-out";
                                    }

                                    return Task.FromResult(0);
                                }
                        }
};
```

**Comment by brockallen** [comment]
>  If you have multiple client applications, you'd have to somehow determine which client you should return to after signout.

Maybe the docs can help: https://identityserver.github.io/Documentation/docsv2/advanced/federated-post-logout-redirect.html
