### ISSUE TITLE
Validation Endpoint - option to switch errors on/off 

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#2635]
When the validation endpoint is called with an invalid token, and error is raised in identity server. This is notifying us of bad tokens when people use expired tokens. Is it possible to have a config option to raise these as warnings instead of errors?

**Comment by brockallen** [comment]
Error in the logs, or error in the events service?

**Comment by parkinsona** [comment]
I have the following error coming out of identity server. I'm not sure if this is from the events service or not, but its coming through in my log. 

``` 
ERROR IdentityServer3.Core.Validation.TokenValidator - JWT token validation error

System.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired.
```

Here is a related request i raised in another repo. https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/74#issuecomment-182723768

**Comment by leastprivilege** [comment]
I will have a look.

But the error indicates that you are using the token validation endpoint to validate a JWT? Why are you doing that?

**Comment by parkinsona** [comment]
As we'd discussed in the issue I linked, for some reason even when I had my ValidationEndpoint set to local it was still going to identity server's validation endpoint. I've since manage to get it to just check it locally.

**Comment by leastprivilege** [comment]
I changed JWT token validation exception message from error to info.
