### ISSUE TITLE
Does the identity server support federated single sign on?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3#2637]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

# Does the identity server support federated single sign on?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
yes

**Comment by brockallen** [comment]
first!

**Comment by brockallen** [comment]
damn

**Comment by leastprivilege** [comment]
j/k no.

**Comment by leastprivilege** [comment]
no. yes.

**Comment by brockallen** [comment]
What do you mean exactly?

**Comment by leastprivilege** [comment]
I assume this answers it. Open a new issue for more specific questions.
