### ISSUE TITLE
Login Page Cycling And Show Again Even Authentication Is Successful

### ISSUE THREAD

**Issue by nomoneylee** [IdentityServer/IdentityServer3#2639]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hello,
I have a similar question like #2091: after submitting my credential in login page, login age shows again even authentication log shows successful. The log file is almost the same with that shown in #2091 . 
However, the error occurs as following steps:
1. Deploy identityserver on our production server. Let's say http://mycompany.com/authserver
2. Visit our website which needs authentication. Let's say http://mycompany.com/portal
3. portal website redirects to http://mycompany.com/authserver to acquire authentication result.
4. In http://mycompany.com/authserver/connect/login page, login succeeds and redirect back to portal.
5. After step4 is done, I visit our test portal server (let's say http://mytestserver.com/portal, the same published binaries with that deployed on production server). It also redirects to  http://mycompany.com/authserver properly. However, after login with correct credential, login page cycles and show again. The log file is the same with #2091.

Is this still an existing bug or any configuration wrong on my server?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
There is no known bug - and you need to go through **your** log files from the production server.

**Comment by nomoneylee** [comment]
Hello,
Thanks for your reply.
After checking my log file & #2091, I finally resolve this problem.
All I need to do is configure the "case-sensitive" domain name (of my authserver) in my portal site.
