### ISSUE TITLE
Accessing UserService from PartialLogin controller

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#2640]
Hi,

I am adding a partial login screen for when users come in via an external provider. This is what I'm aiming for: when an external user logs in, any of their external claims that match local userClaims will be presented on the partial login screen. The user can then choose to update their local claims with these values if they wish. (Let me know if this is a bad idea or if its done somewhere else)

As part of this I'm creating my own custom UserService, but I'm not sure if there's a better way to get the UserService in the controller.

I have the following function that gets called from a controller. Seems like i'm having to create the userService again. Is there a way to get the UserService that is loaded for IdentityServer already?

``` c#
        public static UserAccountService<UserAccount> GetUserAccountService()
        {
            if (_userService == null)
            {
                var db = new DefaultMembershipRebootDatabase("MembershipReboot");
                var repo = new SemaUserAccountRepository(db);
                _userService = new UserAccountService<UserAccount>(MembershipRebootUserServiceFactory.config, repo);
            }
            return _userService;
        }
```

**Comment by brockallen** [comment]
You can invoke our DI system from an OWIN extension: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by parkinsona** [comment]
Thanks for that link. I've made some progress from looking at how you've used it.
Here's what I have so far.

``` c#
var env = this.Request.GetOwinContext().Environment;
            var eve = env.ResolveDependency<IEventService>();
            var svc = env.ResolveDependency<IUserService>() ;
```
This returns a svc object that appears to be of type ExternalClaimsFilterUserService.
This is my factory method that creates my IUserService.

``` c#
     public static IUserService Factory(string connString)
        {
            var db = new DefaultMembershipRebootDatabase(connString);
            var repo = new DefaultUserAccountRepository(db);
            var userAccountService = new UserAccountService(config, repo);
            var userSvc = new CustomMembershipRebootUserService<UserAccount>(userAccountService, db);
            return userSvc;
        }
```

I would have thought I could have cast my IUserService to CustomMembershipRebootUserService<UserAccount> but its returning null when I try to. 
This works:
``` c#
((svc as IdentityServer3.Core.Services.Default.ExternalClaimsFilterUserService).inner as CustomMembershipRebootUserService<UserAccount>)
```

However,  that only works in a watch window. It won't let me put that into the controller code because I don't have the right assemblies included. 
Am I on the right track for retrieving the UserAccountService ?

**Comment by brockallen** [comment]
If you want custom APIs on your user service, then put a custom class in  DI and ask for that instead.

**Comment by parkinsona** [comment]
Would that be something like:

``` c#
 var svc = env.ResolveDependency<CustomMembershipRebootUserService<UserAccount>>()
```

**Comment by brockallen** [comment]
Yep.

**Comment by parkinsona** [comment]
Unfortunately, that's still returning null for me when I put in the custom class as above.

**Comment by brockallen** [comment]
Are you running after IdSvr in the OWIN pipeline? Does your registration really register the type `CustomMembershipRebootUserService<UserAccount>`?

**Comment by parkinsona** [comment]
Yeah its after idsvr in the OWIN pipeline. The object is there and I can access it via the watch window via this. However, this doesn't work when I put it in code because I get the error "The type or namespace name 'ExternalClaimsFilterUserService' does not exist in the namespace 'IdentityServer3.Core.Services.Default' (are you missing an assembly reference?)"

``` c# 
((svc as IdentityServer3.Core.Services.Default.ExternalClaimsFilterUserService).inner as CustomMembershipRebootUserService<UserAccount>)
```


This is what I'm registering in Owin:

In startup
``` c#
 var options = new IdentityServerOptions
                    {
Factory = Factory.Configure("MembershipReboot"),
}
```

In Factory.cs
``` c#
        public static IdentityServerServiceFactory Configure(string connString)
        {
            var factory = new IdentityServerServiceFactory();

            factory.UserService = new Registration<IUserService>(resolver => MembershipRebootUserServiceFactory.Factory(connString));

            var scopeStore = new InMemoryScopeStore(Scopes.Get());
            factory.ScopeStore = new Registration<IScopeStore>(resolver => scopeStore);
            var clientStore = new InMemoryClientStore(Clients.Get());
            factory.ClientStore = new Registration<IClientStore>(resolver => clientStore);

       
            return factory;
        }
```

In MembershipRebootUserServiceFactory
``` c#
    public static IUserService Factory(string connString)
        {
            var db = new DefaultMembershipRebootDatabase(connString);
            var repo = new DefaultUserAccountRepository(db);
            var userAccountService = new UserAccountService(config, repo);
            var userSvc = new CustomMembershipRebootUserService<UserAccount>(userAccountService, db);
            return userSvc;
        }
```

**Comment by brockallen** [comment]
Right, so you don't have `CustomMembershipRebootUserService<UserAccount>` registered in DI. You only have a `IUserService`:

```
factory.UserService = new Registration<IUserService>(resolver => MembershipRebootUserServiceFactory.Factory(connString));
```

So either add all the other stuff to DI, or in your MVC ask for `IUserService` and then downcast to your concrete class.

**Comment by parkinsona** [comment]
I had a feeling it might have been an IUserService being registered.
The weird thing is, when I do:
``` c#
var svc = Request.GetOwinContext().Environment.ResolveDependency<IUserService>();
```
The type returned is IdentityServer3.Core.Services.Default.ExternalClaimsFilterUserService.
I'd happily cast to that in code and retrieve my class from it, but its not letting me due to the error I included in my previous comment.

**Comment by brockallen** [comment]
Ah yes, because we wrap it using a decorator pattern. I think you'll just have to register your custom class in DI:
```
factory.Register(new Registration<YourClass>( resolver => YourFactory("connString") ) );
```

**Comment by parkinsona** [comment]
Is that in addition or instead of:
``` c# 
factory.UserService = new Registration<IUserService>(resolver => MembershipRebootUserServiceFactory.Factory(connString));
```

If I replace the above with your suggestion, then I get an error because there is no UserService configured.

I also tried the following, but ran it couldn't convert my types:
``` c#
 factory.UserService = new Registration<CustomMembershipRebootUserService<UserAccount>>(resolver => MembershipRebootUserServiceFactory.Factory(connString));
```

**Comment by brockallen** [comment]
> Is that in addition or instead of:

In addition to because other parts of the system ask for `IUserService` not `CustomMembershipRebootUserService`.

> I also tried the following, but ran it couldn't convert my types:

Your factory should change its return value to `CustomMembershipRebootUserService`

**Comment by parkinsona** [comment]
Thanks Brock, that's what I was missing. It's working for me now.
I had to rejig my Factory a bit to make use of the same UserAccountService for both DIs. Previously it was a static class, not sure if changing that will affect anything.

I now have:

``` c# 
 public class MembershipRebootUserServiceFactory
    {

        public MembershipRebootConfiguration config;
        private DefaultMembershipRebootDatabase db { get; set; }
        private DefaultUserAccountRepository repo { get; set; }
        public UserAccountService userAccountService { get; set; }
        public CustomMembershipRebootUserService<UserAccount> UserService { get; set; }

         
        
        public MembershipRebootUserServiceFactory(string connString)
        {

            config = new MembershipRebootConfiguration();
         //Extra config settings have been commented out
            db = new DefaultMembershipRebootDatabase(connString);
            repo = new DefaultUserAccountRepository(db);
            userAccountService = new UserAccountService(config, repo);
            UserService = new CustomMembershipRebootUserService<UserAccount>(userAccountService, db);
            

        }
    }
```
Then I add them to my factory like:
``` c#
 var userSvcFactory = new MembershipRebootUserServiceFactory(connString);
             factory.UserService = new Registration<IUserService>(resolver => userSvcFactory.UserService);            
             factory.Register<UserAccountService>(new Registration<UserAccountService>(resolver => userSvcFactory.userAccountService));
```

This now lets me pull out via:
``` c#
Request.GetOwinContext().Environment.ResolveDependency<UserAccountService>() ;
```

**Comment by brockallen** [comment]
Change it back to a method, because this:

```
factory.UserService = new Registration<IUserService>(resolver => userSvcFactory.UserService);
```

now means you have a singleton. that won't work well.

**Comment by parkinsona** [comment]
ok, well here's an update. I was trying to avoid recreating the repo each time, but if it needs to be static, then I can't really avoid that. Maybe I misunderstood what you meant in your last comment. 

```c#
  factory.UserService = new Registration<IUserService>(resolver => MembershipRebootUserServiceFactory.Factory(connString));
            factory.Register<UserAccountService>(new Registration<UserAccountService>(resolver => MembershipRebootUserServiceFactory.UserAccountService(connString)));
```

```c#
        public static UserAccountService UserAccountService(string connString)
        {
            var db = new DefaultMembershipRebootDatabase(connString);
            var repo = new DefaultUserAccountRepository(db);
            var userAccountService = new UserAccountService(config, repo);
            return userAccountService;
        }

        public static CustomMembershipRebootUserService<UserAccount> Factory(string connString)
        {
            var db = new DefaultMembershipRebootDatabase(connString);
            var repo = new DefaultUserAccountRepository(db);
            var userAccountService = new UserAccountService(config, repo);
            var userSvc = new CustomMembershipRebootUserService<UserAccount>(userAccountService, db);
            return userSvc;
        }
```

**Comment by brockallen** [comment]
The repo is your DB connection -- that's prolly not thread safe, thus I'd think you'd want a new one per request

**Comment by parkinsona** [comment]
That's fair enough. So it sounds like I've got something that works and is still safe.

**Comment by bhaveshmyangar** [comment]
Hi BrockAllen,

We have 2 existing MVC application like Application A, B , both application uses simple membership provider for authentication, now we want to implement Single sign-on and centralized user management using IdentityServer, could you please guide us with broad steps that we need to take in order to implement the same,

Thanks!

**Comment by parkinsona** [comment]
As this issue is closed, you're probably best opening a new one that is specific to your needs.

My rough info would be to read the getting started doco (https://identityserver.github.io/Documentation/docsv2/overview/simplestOAuth.html)

I would assume you want to use IdentityServer as your identity store and that's what you're meaning by single sign on. You would probably replace your simple membership providers in your applications and have them authenticate using identity server. In this case A & B would become relying parties (via either hybrid or impllicit client flows) to Identity Server.

The external provider stuff in this issue, is only if you were to use another provider like google to authenticate and you wanted to also allow logins using identity server.
