### ISSUE TITLE
Where I should manage token related information?

### ISSUE THREAD

**Issue by UmeshSgh** [IdentityServer/IdentityServer3#2641]
Hi,

I am pretty new with Identityserver. Recently, I have configured one Identityserver server which is linked my usermanager database and it is working as expected.

Now, we want to little improvement and we have some concern regarding where to manage token related information. After going through EF sample I got idea little bit. but, not sure either that is right approach or not?

Could you please suggest me some solution to this scenario. I am struggling a lot and at last posting here.

How we should manage the token in case server reboot ? I mean, our requirement if access_token is already generated and life time is not yet expired. If our server got restarted then it should not re-generate the token and able to authenticate with old token.

Thanks a lot your kind help.

**Comment by brockallen** [comment]
Dup of: https://github.com/IdentityServer/IdentityServer3.EntityFramework/issues/93
