### ISSUE TITLE
WsFederation token signing and decryption

### ISSUE THREAD

**Issue by charettedavid** [IdentityServer/IdentityServer3#2642]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Can someone tell if adding an ADFS via WsFederationAuthenticationOptions and give the MetadataAddress Url is token are gone be signed and decrypted using ADFS certificates (token-decrypting AND Token-signing)?

if i look to metadata.xml there is the certificates public keys and some search point in that direction but i dont find anx explicit anwser to that in IS3 docs.

Thanks

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
If you're asking how the WS-Fed Katana middleware works, then you realize that's not an identity server issue?

**Comment by charettedavid** [comment]
True, i just want to know if the WS-Fed configured in IS3 will take the certificate from metadata and sign the token exchange between them.

thanks again

**Comment by brockallen** [comment]
That's all the job of the middleware. We don't know which kind MW is being used.

**Comment by charettedavid** [comment]
Ok thanks, i will focus my search on the WS-Fed Katana middleware. 
So far its look like he gets certificate from the AD FS metadata.

Thanks
