### ISSUE TITLE
IDX10803: Unable to create to obtain configuration from: 'https://localhost:44333/core/wsfed/metadata'

### ISSUE THREAD

**Issue by Gigo314** [IdentityServer/IdentityServer3#2644]
### Question / Issue
Hi,
I'm trying to run [SelfHost (InMem with WS-Fed)](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/SelfHost%20%28InMem%20with%20WS-Fed%29) server and [MvcOwinWsFederation ](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MvcOwinWsFederation)client. What I did was:

1. Downloaded IdentityServer3.Samples.
2. Executed /Certificates/setup.ps1 script.
3. Built both projects in Visual Studio 2015 (Win 7).
4. Started SelfHost (InMem with WS-Fed). The console app is running fine without giving any errors.
5. Started MvcOwinWsFederation from Visual Studio (IIS Express) and navigated to /Claims (http://localhost:10313/Home/Claims).

First of all I'm getting _"The remote certificate is invalid according to the validation procedure."_ and after refresh _"IDX10803: Unable to create to obtain configuration from: 'https://localhost:44333/core/wsfed/metadata'."_

Any help would be appreciated :-)

**Comment by brockallen** [comment]
It sounds like you don't have your IIS Express SSL configured properly. Check MSDN for fixing that.

// @blowdart
