### ISSUE TITLE
Changing default logon messages 

### ISSUE THREAD

**Issue by ManojShenoy25** [IdentityServer/IdentityServer3#2646]
We are implementing a custom user store & custom view server.

AuthenticateLocalAsync method lets me write all the custom business logic to authenticate the user. However whenever the user performs a post without the username /password I get "Username is required" message which is correct. (I've disabled client side required attribute for the input fields). 

On debug mode the "AuthenticateLocalAsync" is method is never hit. Is there any method which would let me access to these username/password fields and let me return a custom message.  

[client side validation is turned off ]

**Comment by brockallen** [comment]
That view and endpoint are for username/password credentials. Why would you not expect a username? If you have some other authentication credentials, then you should implement a custom page for that as a partial login.

**Comment by shenoydev** [comment]
I do expect a username. But when the user posts without keying in a username / password I get a default error message e.g. "Username is required" or "Password is required"

Is there any way I could change this message ? I need to give a custom generic message for all login failures.

**Comment by joshpearce** [comment]
We needed to translate all the Views so we in ViewService's Render method, we do some string replacements on the html. That got us 95% of the way, but we still needed to translate the login error messages. Here is what we did:

    public virtual async Task<System.IO.Stream> Login( LoginViewModel model, SignInMessage message(
    {
       client = await clientStore.FindCLientByIdAsync(message.clientId);
       var name = client != null ? clientName : null;
       model.ErrorMessage = TranslateErrorMessage(model.ErrorMessage);
       return await Render(model, "login", name);
    }
All the messages can be found in: IdentityServer3\source\Core\Resources\Messages.resx

**Comment by shenoydev** [comment]
Thanks Josh. that seems to work for me. 

I can override the error messages in the login method with generic error messages.

**Comment by josencv** [comment]
Is there a built-in to do this? Because if the error message changes the translation will fail with @joshpearce  solution.

For now I'll be using a generic translated error message, but I think this is a nice-to-have feature (with very low priority).
