### ISSUE TITLE
IdSrv connecting to an external IdP RedirectUri value?

### ISSUE THREAD

**Issue by NigeB** [IdentityServer/IdentityServer3#2650]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi Dominik/Brock.

I'm trying to connect to Microsoft Azure/Live as an external IdP using OIDC, but I can't figure out what I should be setting the ReturnUri to be when I configure the OIDC Authentication middleware in IdentityServer. It all works nice, except I don't know where to redirect the Microsoft IdP back to!

The Google middleware is not a problem, as you automatically provide the '/signin-google endpoint, but where am I supposed to redirect an external OIDC provider? - Obviously it must go through IdSrv somewhere!

e.g.
```
public static void ConfigureAdditionalIdentityProviders(IAppBuilder app, string signInAsType) {
  var google = new GoogleOAuth2AuthenticationOptions{
      //......works fine
  }
  var msopenidconnect = new Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions {
                AuthenticationType = "msaccount",
                SignInAsAuthenticationType = signInAsType,
                ResponseType = "Code",
                RedirectUri="https://idsrv.mycompany.com/<WHERE??>",
                Authority = "https://login.microsoftonline.com/common/v2.0/",
                ClientId = "<ms-supplied-clientid>",
                ClientSecret = "<ms-supplied-clientsecret>"
            };
}
```
TIA!

**Comment by NigeB** [comment]
Duh! - I should be using OAuth - not OpenIdConnect.

**Comment by leastprivilege** [comment]
AAD works fine with OpenID Connect 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L123

**Comment by NigeB** [comment]
Thanks
Dominick/Brock - I've now got it working - fantastic!
I was going nuts because
a). I hadn't selected the 'Allow implicit flow' checkbox in the MS Application settings when setting up my client, and wasn't requesting an id_token. (Duh.)
b). The user service was throwing a 'username is required' error (I've got MR set up to use email address as username) and I wasn't requesting the email scope from outlook which returns preferred_username as the email in the id_token - ergo no username :-)

At least I'm a lot more familiar with the Authentication service of IdSrv now, which can only be a good thing.

BTW You guys put the big companies to shame in terms of response time to queries - Do you ever sleep???. Thanks again - fantastic product!

**Comment by leastprivilege** [comment]
Thanks ;)  You don't need to enable implicit flow for the middleware scenario.

**Comment by NigeB** [comment]
It doesn't seem to work if 'Allow implicit flow' is not set in the MS account page, so I thought I'd share the following results:
BTW I'm using login.microsoftonline.com/common/v2.0/ which doesn't appear to be quite finished.

    ResponseType | Scope | AllowImplicitFlow (in MS Account setup) | Result
    ------------------- | -------- | --------------------- | --------
    code | openid email | No | Can't find aadcb endpoint
    code | openid email | Yes | Can't find aadcb endpoint
    code id_token | openid email | No | Can't find aadcb endpoint
    code id_token | openid email | Yes | Works
