### ISSUE TITLE
Render password change page

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2651]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
The 'CustomViewService' sample shows HTML views and AngularJS code being rendered. In an actual application there is always a 'Home' page and the 'Password Change' page is part of it. Initially I thought the  'Password Change' is shown as http 302 redirection. But now it appears it can be streamed and placed wherever we want in **our** SPA. It is just that the links to change the password are all populated by using the Idp's API before streaming.

Is this correct ? 

When does the CustomViewService render a customized page ? A URI pattern is needed ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
IdentityServer does not have a password change page (by design).

**Comment by mohanr** [comment]
The flow is like this.
1. User views the Home page of the business SPA.
2. User clicks on the Change password link.
3. The Change password page which is separate from the business SPA is rendered. A partial login check is done before rendering.

No: 3 above need not be a 302 redirection. Is that correct ? I could stream this page and render it as part of my business SPA.

**Comment by brockallen** [comment]
> A partial login check is done before rendering.

I am unsure what this means.

**Comment by mohanr** [comment]
I mean this call.

`
             AuthenticateAsync(Constants.PartialSignInAuthenticationType)
`

**Comment by brockallen** [comment]
Right, so from the SPA the user comes to this change password page directly. In this case, there is no partial login. I'm not sure why you send a token along. 

Sorry but I still don't understand what you're trying to do or what the question is.

Normally a change password page is part of a client app (like any other client app) and that "change password" page simply has the ability to update the user database with the new password. It's that simple -- no need for a partial view from within IdSvr.

**Comment by mohanr** [comment]
I thought the request from the main SPA to the Change password page goes through the same validation pipeline like all other requests. I call a WebApi Route to render the Change password page as a _FileContentResult_.
Now I understand that the token is not needed here.

>>no need for a partial view from within IdSvr

I think I am beginning to understand this part. I see some code that calls AuthenticateAsync(Constants.PartialSignInAuthenticationType)  and gets the System.Security.Claims.ClaimsIdentity and fetches the GetSignInCode(). I believe that this is required only if we are sending back the URI **( embedded in the Change password page )** to redirect to the Idp's login page after changing the password.

**Comment by brockallen** [comment]
> I thought the request from the main SPA to the Change password page goes through the same validation pipeline like all other requests.

No because this part has nothing to do with IdSvr, as I said before.

If the change password SPA needs to authenticate the user, then do it like any other client.

**Comment by InnovaSmart** [comment]
IdentityServer should do the 1 thing it does well already and nothing more, for security reasons. If you are going to need a Password change page, then that needs to be apart of a Client. You will need to create a WebAPI Project (Resource) as a way to change the password within the Identity System and update the DB.

**Comment by mohanr** [comment]
I will close this for now.
