### ISSUE TITLE
Best Practices for Complex Claims?

### ISSUE THREAD

**Issue by S3KCentrifugal** [IdentityServer/IdentityServer3#2652]
This is more a question about best practices, although some guidelines on how to implement properly with Identity Server would be helpful as well. By complex claims I am referring to a claim value as an object, likely serialized JSON. For example even the OpenID connect spec has a claim type of "address" which is a json object. 

Under what situations would you justify the use of a complex object? And what would be the approach to supporting complex claims within Identity Server 3? 

**Application Scenario**
In my specific situation I have an application where users can work on behalf of different agencies. Their access level can vary depending on which agency they are working for. For instance one user may have access to Agency A and Agency B, within A the user is an admin, and within B the user can only perform basic tasks like reporting.  

Since claims are effectively just flattened out key/value lists I can't create complex relationships to say a given user, working for a given agency has a given role. Unless I create complex claims to represent a list of "agency" objects, and within these have their security levels.

You might be wondering why not just leave this level of access with the application and not part of the claims. This is one possibility I am considering, however we do have multiple applications that are disconnected but rely on the same agency information. In fact the actions users can perform can be identical but using different platforms. If possible I thought it would be simpler to include this information with the claims.

I am looking for advise though.

**Comment by joshpearce** [comment]
According to the OpenID Connect spec, a "claim" is a piece of information about an Entity. Not a piece of information about the relationship between two Entities. But, you could still put it in, if you don't expect it to change during the lifetime of the Token containing the claims. The potential problem is size -- making the token too big. But you can encode it (a:1;b:3,4:c:1,2)

> however we do have multiple applications that are disconnected but rely on the same agency information.

If your Issuer has information about the relationships but the applications do not, and cannot directly access it, perhaps you should create a Resource Server which provides that info, and let the applications make back-channel HTTP requests to get it.

**Comment by leastprivilege** [comment]
I agree with @joshpearce - claims are about identity.

That said - if your claim value must be JSON (like the address claim) - set the ClaimValueType to be `Constants.ClaimValueTypes.Json` in the Claim ctor.

**Comment by brockallen** [comment]
@S3KCentrifugal all set?
