### ISSUE TITLE
How can i get the expiry of the refresh token?

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2653]
Hey guys,

I'm setting the access/refresh tokens in a custom cookie on my web app (don't ask), with an expiry. For access tokens, i can use the `expiresIn` prop on the `TokenResponse` object, but for the refresh token, how can i get the expiry?

On my auth server, i have set it up like this:

```
RefreshTokenExpiration = TokenExpiration.Sliding,
AbsoluteRefreshTokenLifetime = sevenDays
```

So i _could_ just hardcode to 7 days in my web app, but then if it's sliding (as above), i won't ever have the actual expiry when refreshing the token?

**Comment by leastprivilege** [comment]
There is no way to query the lifetime of a refresh token - you need to try to use it, and if it fails, the user has to re-authenticate.

**Comment by brockallen** [comment]
And even if there was one provided, you'd still need to:

> you need to try to use it, and if it fails, the user has to re-authenticate

because the user might have revoked it.

**Comment by RPM1984** [comment]
Got it, thanks guys!
