### ISSUE TITLE
Question: Storing the ReturnUrl on register page

### ISSUE THREAD

**Issue by doublej42** [IdentityServer/IdentityServer3#2656]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
On my login page I have a link to register a new account that looks something like:
https://localhost:44321/Account/Register?signin=5d5ceb9833ac9263749cca7e992cb3f8
the signin value I know is part of the login cookie.

As part of the registration our users will need to check their email so I expect many to close their browsers and lose these cookies. I want to save the return url so I know what application they were logging into.

The code I'm using in my registration page to get the returnUrl is
```
var env = Request.GetOwinContext().Environment;
var signInMessage = env.GetSignInMessage(model.signin);
```

but this crashes with a null exception because in `public static object ResolveDependency(this IOwinContext context, Type type)` the line `var scope = context.GetAutofacLifetimeScope();` returns null.

I don't fully understand the use of autofac but I think I'm missing some initialization here when not hitting Identityserver pages.

Is there a better way to get the returnUrl so I can restart a flow after a browser is closed?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
On the register page you can use the signin id to query the SignInMessage and get the client id they are logging into. Store that with the user's registration and then when the complete their registration send them to the client.

https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by doublej42** [comment]
The part I was missing was that the GetSignInMessage could only be called during the identity server flows. Also the cookie was locked to the path of my identity server (/identity/) so I could not read it in /account/. My workaround was to use PreAuthenticateAsync (to grab the return url and store is in a cookie that my account controller could read (and later store in the database)



```
 public override Task PreAuthenticateAsync(PreAuthenticationContext context)
{
	var signin = _owinCtx.Request.Query.Get("signin");
	if (signin != null)
	{
		var signInMessage = _owinCtx.Environment.GetSignInMessage(signin);
		if (signInMessage != null)
		{
			var returnUrl = HttpUtility.UrlDecode(signInMessage.ReturnUrl);
			_owinCtx.Response.Cookies.Append("ReturnUrl."+ signin, returnUrl, new CookieOptions()
			{
				HttpOnly = true,
				Path = "/",
				Secure = true
			});
		}
	}
}
```

**Comment by jgestevez** [comment]
@doublej42 your solution works, but I'm getting this error

`IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.`

when redirecting back to the client after confirming the email from another browser, how do you solved this?
