### ISSUE TITLE
Add custom cookie after login

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2658]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hello, 
How can i add custom cookie on idsrv3 after login and remove on logout?
I try in my custom userservice ->PostAuthenticateAsync to add:
```HttpContext.Current.Response.Cookies.Add(new HttpCookie("aaaaaa","bbbbbb"))```
and this works .
Is ok to do like this?
and now how to remove?
in userservice ->SignOutAsync in ```HttpContext.Current.Request.Cookies``` my cookie is but how to remove it?

Tx

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
We'd suggest you use the OWIN APIs for cookies. Just inject the OwinEnvironmentService into your code and wrap it with a OwinContext.

**Comment by totpero** [comment]
I have inject ```OwinEnvironmentService```  in my custom userservice like you say .
To create cookie in ```PostAuthenticateAsync`` is OK but to delete in ```SignOutAsync``` using:
```_owinContext.Response.Cookies.Delete("key");``` nothing is happening, the cookie persist in browser and the expiration date is OK.
Where can be the problem?
Any help please.

**Comment by totpero** [comment]
I solve this problem by override the cookie because the delete method don't works.
