### ISSUE TITLE
Null context.Subject.Claims in Custom AD UserService GetProfileAsync

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2659]
- [v] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
IdentityServer3 and ActiveDirectory GetProfileAsync() failure: 

In the AuthenticateLocalAsync() I successfully validate the user/pw against the AD. 
I then can access the AD groups via a 

```
using (PrincipalContext pc =
                            new PrincipalContext(ContextType.Domain, domain, username, pw))
```

And create a list of claims, one "role" claim for each of the groups the user was found in. 

Before returning from AuthenticateLocalAsync I set the context: 

```
                    context.AuthenticateResult = new AuthenticateResult(
                                                        subject: domainAndName, // format: 'domain\name'
                                                        name: username,
                                                        claims: claims);                   // list of claims found

                    return Task.FromResult(0);

```

All runs OK. I find 12 "role" claims. The code me logs me in, on the IdentityServer.

However when I am entered into the `GetProfileDataAsync`, although the context data has the context.Subject ok, with my name and subjectID as set above, the claims are null. 

```
var claims = context.Subject.Claims as List<Claim>

```

Since I do not have the password anymore at this stage, I cannot access the AD and get the groups of the user. 

Is there any way that I can set the profile claims during the AuthenticateLocal when I have the password available, or is there some other way I should be achieving this?

**Comment by brockallen** [comment]
as List<Claims> might be the wrong cast. Is `context.Subject.Claims` null?

**Comment by pashute** [comment]
Yes. Sorry the solution is that I don't need that. I can access the groups without the username password. 

I'll do that inside the GetProfileData. Closing the question, and thanks for the quick reply!!
