### ISSUE TITLE
Partial login without setting subject and name

### ISSUE THREAD

**Issue by chrtsam** [IdentityServer/IdentityServer3#2665]
Hello,

I am trying to implement  a partial login but i  am stuck on some issues. what i am trying to do is to do a partial login without a subject and a name, and set these values in (or after) the partial login page.
The first question is where the PartialLoginResumeUrl leads? From the eula example i thought it would lead to the AuthenticateLocalAsync again but it does not(at least in my case)
The second question is how(requesting a signin?) and where(in the partial login controller or in the AuthenticateLocalAsync) should i set up the user's subject and name. The documentation says it is possible to do a partial login with only setting the claims.

When I tried setting the subject and the name from the beggining the partial login succeded, meaning that after redirecting to the resume url i got an access token.

Thank you.

**Comment by brockallen** [comment]
You can use the version of `AuthenticateResult` that accepts an `IEnumerable<Claim>`. If you have no claims, then pass `null` (you'll have to cast the `null` to the `IEnumerable<Claim>`)

**Comment by brockallen** [comment]
Ah, and from a partial once you know the user's identity you can use the OWIN extension `UpdatePartialLoginClaimsAsync`:

https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

You'll need to supply the 5 required claims: sub, name, idp, amr, and auth time -- same ones needed here: 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/IdentityServerPrincipal.cs#L47

**Comment by brockallen** [comment]
All set?

**Comment by chrtsam** [comment]
Yes. I set the 5 claims as you said and it worked.
Maybe one more question. After the redirect to the resumeUrl the process continues to the GetProfileDataAsync method and not to the AuthenticateLocalAsync. Is this normal?

**Comment by brockallen** [comment]
Yes, because you've logged the user in by setting those claims and returned the user back into the IdSvr workflow.
