### ISSUE TITLE
Protecting SPA URI properly

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2666]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I am able to protect my SPA's URI and get a token if I hit https://localhost:port1/context/connect/authorize?client_id=implicitclient&redirect_uri=http://localhost:port2/App/&response_type=token&scope=test. Now if I type my SPA's URI directly in the browser I get the page back without authorization.

I think I am missing something in this flow. Any pointers ?

The AngularJS SPA is a empty ASP.NET MVC 5 project. Should this project be configured with some type of authentication ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
I don't understand. In your SPA once you need a token send the user for authorization.

**Comment by mohanr** [comment]
I think you mean that the SPA has to be structured in such a way. When the SPA's initial workflow begins in the browser it should connect to the authorize endpoint.

**Comment by brockallen** [comment]
Sounds reasonable

**Comment by mohanr** [comment]
So I understand that the initial SPA need not be rendered using a method annotated with [Authorize]. That would change the project type.
The concern is that some of the SPA AngularJS bootstrap code comes to the browser before the Idp is hit for the token.

**Comment by brockallen** [comment]
Your authorization (or rather the code that detects if you have a token) would be client-side (after you loaded the assets for the SPA).

**Comment by mohanr** [comment]
That settles it. I will do that. Closing.
