### ISSUE TITLE
IdentityServer3 Identity and Access Tokens in production scenarios

### ISSUE THREAD

**Issue by metajoshi** [IdentityServer/IdentityServer3#2667]
Hi there, 

This isn't an issue as much as a question about Identityserver in a production scenario. I was perusing the docs trying to figure out which interface to override to handle token storage for both issued access tokens and identity tokens. 

I found the below link which recommended overriding the TokenHandleStore:

https://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html 

Clicking the TokenHandleStore interface in the link above took me to ITransientDataRepository which TokenHandleStore derives from. I implemented sprocs to store and retrieve tokens for all the corresponding functions. My question is: if I open up TokenHandleStore below, I'm seeing a slightly different implementation:

https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/master/Source/Core.EntityFramework/Stores/TokenHandleStore.cs

When building out the database table, should I only account for the fields in ITransientDataRepository or also account for the fields in TokenHandleStore? Please note that using Entity Framework here isn't an option (DB architecture is out of my control, I need to create tables and stored procedures).

Any help is appreciated.

Thank you!

**Comment by brockallen** [comment]
Well, the base of that class does the rest (since many of the token related stores are very similar).

**Comment by brockallen** [comment]
So here's the concrete interface (which I'm sure you've looked at): https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/ITokenHandleStore.cs

and it needs to store/load instances of `Token`:

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Models/Token.cs

**Comment by metajoshi** [comment]
Thanks for your prompt response. I will implement ITokenHandleStore and use below code to register the store in Startup.cs. 

factory.TokenHandleStore = new Registration<ITokenHandleStore>(typeof(TokenRepository));

Will update this thread if I run into issues.

**Comment by brockallen** [comment]
Ok, I'll close for now then.
