### ISSUE TITLE
Passing multiple ClaimsIdentity to a client application

### ISSUE THREAD

**Issue by LeeDumond** [IdentityServer/IdentityServer3#2668]
I have a question having to do with the ability to use IdentityServer to obtain a ClaimsPrincipal in a relying client, where that ClaimsPrincipal contains more than one ClaimsIdentity in its ClaimsPrincipal.Identities collection.

Populating the ClaimsPrincipal with multiple identities was basically my first idea to solve our particular domain scenario, but it’s possible this may not even be the best approach…  

Let me briefly explain:

This is part of an SSO solution for an insurance company. The company’s products are sold by independent agents. Users can log in to various client applications using the SSO.

The problem lies in the fact that some users may work for _more than one agency_. In this case, when logged into the client app, the user will have a _different_ set of permissions (claims), based on which agency they are acting on behalf of.

So for example, if they are acting on behalf of Agency A, they might have claims that lets them **view** and **create** quotes. When acting on behalf of Agency B, they may have claims that let them **view** and _**modify**_ quotes, but not create new ones.

My initial idea was to create a different identity for each Agency the user belongs to. In the client app, the ClaimsPrincipal (Thread.CurrentPrincipal) would have two identities. That way, the user could switch between these identities as desired (using a dropdown control or something like that). When they switched, the primary Identity property would be populated from the Identities collection so that the correct set of claims are being used by the app.

We have IdentityServer working fine with OWIN. In `OpenIdConnectAuthenticationNotifications `we are doing claims transformation by retrieving the user’s claims via the UserInfoEndpoint, and then passing them back via a new ClaimsIdentity in the AuthenticationTicket.  However, as far as I can see, the AuthenticationTicket constructor only allows you to specify a _single_ ClaimsIdentity to pass back to the client.

Is what I am trying to do a supported scenario? Am I missing something? Or am I just approaching this all wrong? Is there a different way we should be handling this?

Any guidance or feedback would be greatly appreciated.

**Comment by brockallen** [comment]
> where that ClaimsPrincipal contains more than one ClaimsIdentity in its ClaimsPrincipal.Identities collection

This is usually something that would be managed on the client side, and not necessarily something that an IdP would do for you. 

You could design your client to allow the user to go back to the IdP for additional identities, and then you'd have to manage those on the client side. Most of this would be custom and outside the anticipated design model of things like the Katana OIDC MW. Also, IdSvr itself does not support a single user logged in with multiple identities.

**Comment by LeeDumond** [comment]
Ok so here was an alternative idea... maybe just pass the AgencyIds that the User belongs to as claims, and have a Web API that the client could call to get the permissions by agency? Is that kind of what you're getting at here?

**Comment by brockallen** [comment]
I don't know enough about your domain model to comment. Keep in mind that identity != permissions. They do influence one another, but it's best to keep a clear separation.

**Comment by LeeDumond** [comment]
In our case "permissions" are simply a fine-grained type of Role. Role actually IS part of identity, hence the impetus to treat them the same.

We use the permissions with a PermissionAuthorizeAttribute, which is kind of a modified version of the Resource Authorization that you guys use in IdentityModel.

Has there been any thought given to perhaps having IdSvr support a single user logged in with multiple identities?

**Comment by brockallen** [comment]
> Has there been any thought given to perhaps having IdSvr support a single user logged in with multiple identities?

Yes, and as a feature it's not on the radar. Sorry.
