### ISSUE TITLE
Regarding token revocation support in 2.4.0 and identity model 1.9.1

### ISSUE THREAD

**Issue by shahjeet297** [IdentityServer/IdentityServer3#2669]
I have few doubts here as how token revocation works for example:
1. i have mvc application where user can login and token is passed to the client
2. then he logout from the application and i revoke the passed token but he still has access token in cookie as i forgot to clear it.
3. Now user tries to open cached pages and request gone to API server by the aceess token which is not expire yet.

Question: 
1. Does API allow the user to fetch the data using that token as i am using the default validation type which is endpoint validation?
2. Does API always call the identity server to validate the token?
3. how identity server identify that the passed token is revoked? Do we store the token somewhere in identity server?

**Comment by mderriey** [comment]
Hi, I'll try to answer your questions.

1. If the token was revoked in IdentityServer and the API calls the token validation endpoint to validate the token, then the token should be recognised an invalid, thus the API call being denied. In my understanding, only reference tokens can be revoked, not JWT tokens.
2. Not always. The cases I can think of where this would not happen:

 - The API self validates the tokens with the help of the metadata exposed by IdentityServer. Note this works only with JWT, self-contained tokens
 - If you choose to use the token validation endpoint, you can cache validation results. You have control over this in the [IdentityServerBearerTokenAuthenticationOptions](https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/blob/414b217ccb613b231dedcd09d08a90f774fd232a/source/AccessTokenValidation/IdentityServerBearerTokenAuthenticationOptions.cs). You can control wheter it's enabled or not - disabled by default - with the `EnableValidationResultCache` property, the duration of the result being cached with `ValidationResultCacheDuration`, and the cache implementation with `ValidationResultCache`

3. Reference tokens are stored in IdentityServer. The service you might be interested in looking at is [ITokenHandleStore](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/ITokenHandleStore.cs). Have a look at [this issue](https://github.com/IdentityServer/IdentityServer3/issues/2667) for more information on the subject.

**Comment by leastprivilege** [comment]
Only reference tokens can be revoked.

**Comment by jahansha** [comment]
One suggestion: Use the  RevocationEndpointController to Revoke the token. Make an entry in a database before returning.

When going to  ValidateAccessToken endpoint, just before returning the result, make sure that a call is made to DB to see if token was revoked.
