### ISSUE TITLE
Authenticate MVC User on Startup

### ISSUE THREAD

**Issue by SimonRoodt** [IdentityServer/IdentityServer3#2672]
I have successfully got Identity Server 3 up and running. My architecture is as follows:
* myidentityserver - running as a web host
* mywebapi - REST API serving data to different clients
* mymvcapp - an MVC application consuming mywebapi
* myspapp - a client side application consuming mywebapi

When I launch mmvcapp, and try and access an 'authorized' resource, I am directed to myidentityserver, to login and authenticate. Upon authentication I am redirected back to my application and can access the protected resource. The MVC application uses cookies too. EVERYTHING works as expected ... I'm getting idtokens and accesstokens back for use against mywebapi. HOWEVER, if I close mymvcapp down and then relaunch it, the initial evaluation of Request.IsAuthenticated returns false, even though as far as myidentitiyserver is concerned I'm still authenticated and my token is still valid. How do I get my MVC app to validate the token and then authenticate the user on startup? Do I need to explicitly store the token in a cookie? Do I need to persist it? How can I get mymvcapp to authenticate the user on startup?

My MVC configuration is as follows ...
//use cookies
 app.UseCookieAuthentication(new CookieAuthenticationOptions
 {
                //set the authentication type
                AuthenticationType = "Cookies"
}

//use idenityserver
 app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = AppSettings.IdpHost + "/identity",
                ClientId = AppSettings.AdminClientId,
                Scope = "openid profile roles olbapi", 
                ResponseType = "id_token token", 
                RedirectUri = AppSettings.AdminClientRedirect, 
                PostLogoutRedirectUri = AppSettings.AdminClientRedirect,
                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false, 

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                   SecurityTokenValidated = async n => ...                
                    RedirectToIdentityProvider = n => ...
                }

**Comment by leastprivilege** [comment]
If you want the authentication session in your app to survive restarts - you need to use persistent cookies.

**Comment by SimonRoodt** [comment]
OK. That makes sense! Two follow on questions ....
1. Would I need to store the tokens in the cookie explicitly and also explicitly extract the id_token and validate it against IdSvr when my MVC app starts up? Not sure where exactly to do this.
2. I presume IdSvr uses persistent cookies, is this correct? My idsvr is running as a separate webhosted service. If I close my browser session to my idsvr, and restart the webhost and recycle the app_pool, and then return to https://myidsvr/identity/permissions, it recognises that I am still logged in.

**Comment by leastprivilege** [comment]
1) after authentication, your app is independent of idsrv. Why would you want to validate? If you need new tokens you need to start an authN handshake
2) depends on your config.

**Comment by SimonRoodt** [comment]
1). OK. I think I understand. If I'm using a persistent cookie the MVC app framework should take care of processing my persisted cookie when returning to the app (ie Set user as authenticated). Assuming I am locking down certain resources in the app with ResourceAuthorization requiring certain claims, and assuming the tokens have expired, I presume I would need to implement a REFRESH token approach to ensure that the user claims are updated/refreshed?
2). My IdSvr config is pretty standard based on the WebHost (minimal) IdentityServer samples except that I'm using EntityFramework with SQL as the store as opposed to InMemory. It's running under an IIS website. I'm not doing anything specific with cookies in code on my IdSvr host. When I look at cookies for the site I see 3 (idsvr, idsvr.xcsrf and idsvr.session). All I can see related to session are the IIS ASP.NET session state setting in IIS, which is configured to use ASPNET Session cookies with an expiration of 20 minutes. What I want is the same behaviour in my MVC App. That is ... when closing my browser and then re-opening the mvcapp, I want it to immediately recognise I am authenticated (as IdSvr host does), as well as ensure my tokens and claims are not expired.

**Comment by brockallen** [comment]
1: refresh tokens allow you to have long term access to a web api after the user has left the app. think of an offline report running every night. but it's possible to use refresh tokens to simulate long-lived sessions. i'd prefer to see you use long lived cookies for browser apps if that's your use case. it also removes a lot of work from your mvc app of managing the refresh token.

2: i don't know how ASP.NET Session State cookies are related to any of this. but if you want long lived sessions in the browser that's where persistent cookies come in nicely.
