### ISSUE TITLE
Strong hashing of stored refresh tokens

### ISSUE THREAD

**Issue by omerlh** [IdentityServer/IdentityServer3#2673]
Hey,
I've started to work recently on adding authentication to my company app. We are going to use identity server, and use access token in the JWT format. This left only the refresh token store to be stored securely. Now, I saw that there is a decorator that hash the refresh token before passing them to my custom store, but from reading a bit over the net [(this](https://crackstation.net/hashing-security.htm) for example) it seem better to hash using PBKDF2 algorithm, which add salt and other stuff. 
My question is: 
a) How one can achieve this? When using refresh token, there is no user/password, only the token. If I use this algorithm, it mean each time I will need to do full table scan, and calculate the hash with the salt for each token in the storage. Also, this algorithm by design is cpu intensive, which make this almost impossible.
b) Should I even bother? I am worried because refresh token are the same as password - they allow the attacker to obtain access token. On the other hand, I guess that this topic was well though, and I would like to hear why the current implementation use hash only.
Thank you very much,
Omer

**Comment by leastprivilege** [comment]
b) no.

PBKDF2 is used for weak inputs (p == password). The input in our case is already a cryptographic random number.

**Comment by omerlh** [comment]
Yes, but does require the client credentials (which are required when refreshing a token) to be safe?
I am very new to this, but I guess you still can create hash table also for random value. It will be hard if the length of the refresh token is big enough...

**Comment by leastprivilege** [comment]
client credentials should generally be random numbers as well. Depending on the deployment scenario - the client credentials are stored on the client device in which case they are very secret anyways.

I would recommend you don't bother for now - and learn more about the protocols and the bigger picture.
