### ISSUE TITLE
Token Endpoint 405

### ISSUE THREAD

**Issue by TD49** [IdentityServer/IdentityServer3#2674]
We have IdSvr3 2.3.0 running on an IIS host but the Token endpoint rejects pre-flight calls from JS apps (OPTIONS call) with a 405.  I did follow the [CORS documentation](https://identityserver.github.io/Documentation/docsv2/configuration/cors.html) by registering a basic ```DefaultCorsPolicy``` with ```AllowAll``` set to true.   Also confirmed the following:

- IIS allows OPTIONS calls (setup with OPTIONSverbhandler)
- host itself responds with 200 for OPTIONS calls (except on IdSvr token and validation endpoints)

We also tested against the Samples Webhost (minimal) and added a single line to [Startup.cs](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/WebHost%20(minimal)/WebHost/Startup.cs):

```C#
factory.CorsPolicyService = new Registration<ICorsPolicyService>(new DefaultCorsPolicyService { AllowAll = true });
```
Even with the sample, we're receiving 405's when consuming the Token endpoint with an OPTIONS request both from the JS app and with a direct compose test from Fiddler.  

Anything that we missed?

**Comment by brockallen** [comment]
Maybe something from here? http://brockallen.com/2012/10/18/cors-iis-and-webdav/

**Comment by brockallen** [comment]
Any update?

**Comment by TD49** [comment]
Apologies on the delay.  Yes it's working again (as of 2.4.0).   Thanks for the WebDAV hint.
