### ISSUE TITLE
OWIN: Getting 403 after moving my WebApi to IIS

### ISSUE THREAD

**Issue by dknaack** [IdentityServer/IdentityServer3#2675]
I have a web api 2 project in a seperate assembly and hosted it inside a console application for 
testing purpose. 

Now ive created a empty mvc web application and try to host my web api inside iis.

Everything works good so far except authentication. 

I receive a 403 exception on my requests. 

This is the complete response. 

```
{
  "date": "Mon, 07 Mar 2016 18:13:18 GMT",
  "www-authenticate": "Bearer error=\"insufficient_scope\"",
  "server": "Microsoft-IIS/10.0",
  "x-powered-by": "ASP.NET",
  "access-control-allow-origin": "http://localhost:56844",
  "access-control-expose-headers": "WWW-Authenticate",
  "x-sourcefiles": "=?UTF-8?B?QzpcRGV2ZWxvcG1lbnRcYjRQYXltZW50XGJmcFxzcmNcQjRQYXltZW50LkFwaS5XZWJob3N0XG1hbmRhdGVcbWFpbA==?=",
  "content-length": "0",
  "content-type": null
}
```

**Comment by brockallen** [comment]
> www-authenticate": "Bearer error=\"insufficient_scope\"",

Does that help you in any way?

**Comment by dknaack** [comment]
Sorry but no not really. Do you some more information ?

**Comment by dknaack** [comment]
Here is the request 

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/vnd.b4payment-v1-sandbox+json' --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvaWQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvaWQvcmVzb3VyY2VzIiwiZXhwIjoxNDU3NDA1OTE3LCJuYmYiOjE0NTczNzcxMTcsImNsaWVudF9pZCI6ImRlZmF1bHQiLCJzY29wZSI6InYxLXNhbmRib3giLCJzdWIiOiIxIiwiYXV0aF90aW1lIjoxNDU3Mzc3MTE3LCJpZHAiOiJpZHNydiIsIm5hbWUiOiJCNFBheW1lbnRQU1AiLCJodHRwOi8vc2VwYS5leHByZXNzL2FwaS9wc3BJZCI6IjEiLCJhbXIiOlsicGFzc3dvcmQiXX0.RaUgajKEciGTdciDMbpv6dr88_qDMETZx5Pyn4weODXbSfYD9VDVjgByDxmR7RdpTG8YU-1Ys8kQ_7H3TLh0KQTdxrKJohYvaKObXzA-Hl25-JIQK7K_CvXHUgyKuoNaYuXzz90-1G9IaKf3tygRSn6DyQv4XMPq2bTBLfGv21qcXDaNbJiuPM70AgBpn_eWSnK-wnKa5asHwDIFquJk3MBJv2W2gB8nyOODkisfhxUQy_t3eKfds5EVdT3kqw_VFXLysXfnRdokY2VVDf51thbkfZCpnyVuGritX6Oi0T5DkCOEFuljmKfioby-YrHrOuiwBJWDJF_fJEy3mweAMQ' -d '{
  "emailAddress": "string",
  "languageCode": "string",
  "b4pId": "string"
}' 'http://localhost:56844/myendpoint'
```

**Comment by leastprivilege** [comment]
you have the wrong scope in the token. as the error message says.

**Comment by SimonRoodt** [comment]
You need to configure your IdSvr to return the necessary scope for the client calling the API. Have you got it all bundled into on application (ie MVC, API and IDSVR in one web project)? How have you configured your IDSVR Clients ?). If your API requires a certain scope or claim then the token being used when calling the API must contain this scope or claim.

**Comment by dknaack** [comment]
Yes, thank you! I had a mistake with a wrong scope. At the moment i try to test this but the request does not stop or time out.

**Comment by brockallen** [comment]
> At the moment i try to test this but the request does not succeed or time out. I am waiting...

So are you all set, or still blocked?

**Comment by dknaack** [comment]
I still have a problem. I guess i need to describe my goal and current state in more detail. 

1. What i want is a Web Api Hosted inside a Mvc Application. 

2. I want the api appear on the root path of the application because i want to host them on a "https://api.mydomain.com" instead of "https://mydomain.com/api". 

3. I want to use content negotiation to select the api (and do versioning) so i have a custom http controller selector which works (debugged it) and i use them in some other applications in production.

4. I want that mvc still works so iam able to show some content for "text/html" users using the usual mvc approach.

So i have the following to start the api. (Works in my console app)
    var apis = /* a list of Api objects describing on which formatter it should be used and the namespace where the controller could be found */
    var config = new HttpConfiguration();
    config.Formatters.Clear();
    config.MapHttpAttributeRoutes();

    /* A loop that adds all formatters i need to identify all of my api versions */

   // replace controller selector and api explorer in order to enable api versioning
   config.Services.Replace(typeof (IHttpControllerSelector), new ApiControllerSelector(config, apis));
   config.Services.Replace(typeof (IApiExplorer), new VersionedApiExplorer(config));
   app.UseWebApi(config);

**Comment by dknaack** [comment]
I just found my problem. It was a complete other thing. 

Thank you very much @brockallen ! Cant thank you enough for your support!
