### ISSUE TITLE
Reference Token Management

### ISSUE THREAD

**Issue by Grassycup** [IdentityServer/IdentityServer3#2676]
Hi, I am trying to use long lived reference token in my project using hybrid flow, I had it set up to use JWT initially, so I simply modified the client setting to use reference token instead.
I took the in memory implementation from the source ([InMemoryTokenHandleStore](https://github.com/IdentityServer/IdentityServer3/blob/a6e2b6bdfd1516af6cd9fdc9f46a08bb23bb553e/source/Core/Services/InMemory/InMemoryTokenHandleStore.cs)) of the reference token store to see how the store should behave.
I realized in the process that the reference tokens never really gets cleaned up once stored(inside the ConcurrentDictionary<string, Token> _repository), even with short expiration time.
Also, it seems that a new token gets generated everytime the authorization endpoint is hit, therefore further increasing the number of tokens being stored without being cleaned up.

Are the reference tokens supposed to stack up like this?
How would you recommend that I handle the management of the reference tokens?

**Comment by brockallen** [comment]
In our EF project we have a timer that cleans up expired tokens.

**Comment by Grassycup** [comment]
Ok that makes sense.
Thanks for the help!
