### ISSUE TITLE
Signing certificate has not private key

### ISSUE THREAD

**Issue by iLearnIdentityServer** [IdentityServer/IdentityServer3#2677]
Hi, I'm having some difficulties while making installer for Identity Server 3.

This probably is not directly related to Identity Server 3, but I would be great full if somebody can give me a hint.

Identity Server 3 is running as a Windows Service under its own user account (lets say IDP_USER).

Basically what I do is during installation process is:
1. Dynamically create password for IDP_USER
2. Dynamically create IDP_USER
3. Dynamically create 3 ceritficae:
3.1 CA certificate stored in local machine, root CAs store
3.2 Certificate for communication encryption, stored in local machine, my store. This is issued by CA above
3.3 Certificate for signing tokens (I want to avoid embedding certificate in assembly for security reasons), installed for IDP_USER in my store. This is done by performing impersonation..Certificate is issued by CA above. 
4. Then I create server and db pricipals in order to make connection to DB secure (trusted connection), At the moment good enough. 

5. Bind certificate to TCP/IP port and set url acl
6. Add IDP_USER priviledge to LogOnAsService
7. Create windows service for IDP and run it as IDP_USER.

All good except that for some reason IDP_USER can no get private key.

When I use the same steps, same API that I wrote, just not for dynamically created user account, it works.

It seems that IDP_USER is lack of some privilege. But how is it possible since I'm impersonating to IDP_USER before installing certificate?

**Comment by leastprivilege** [comment]
idp_user has the "logon as a service" privilege - and read access to the private key?

**Comment by iLearnIdentityServer** [comment]
Well idp_user for sure have "logon as a service' right, I grant this priviledge dynamically during the installation just after I create the user, otherwise service would not start and I would not be able to come to part when I have problem with private key.

So, after I create user and grant priviledge, I create CA certificate and than server certificate for communication encryption and IDP certificate for signing tokens, both issued by CA cert.

Then I install CA cert and Server cert in Local Machine in Root CA and My stores, respectively. And then I do impersonate to IDP_USER and install certificate for current user in My store. Since I'm impersonated to IDP_USER I expect that it will have access to private key, this is true if I do the same thing for my user account.

So when I login as IDP_USER (during installer testing I do trance passwords just I can debug, but later on installer will not trace this) I really see this cert installed, and there is nice message "you have private key for this certificate". But it seems that IDP_USER can not access the private key, furthermore I also can not export private key, even it is set to be exportable when certificate is created.

When I use my user account for all of this, but without impersonation, since I am who I want to be :-), all works. I can access private key, I can export.

I was expecting that IDP_USER will have access to its certificate private key, and that I do not have to look for private key location and grant access rights for that user (this looks to me as workaround)

Is this really necessary?

**Comment by iLearnIdentityServer** [comment]
Yes I checked out 
..IDP_USER\AppData\Roaming\Microsoft\SystemCertificates\My\Keys\BAA2D17CFFAC4D6042E2FAA78F990....

IDP_USER is owner and have full access rights

Some priviledge is missing.

Do you have any idea which one?

**Comment by iLearnIdentityServer** [comment]
This is difference, admin account have those additional groups:
NT AUTHORITY\Local account and member of Administrators group S-1-5-114                                      
WIN-FVEN9JQLHNF\Message Capture Users  S-1-5-21-1826645653-3098134492-4231775046-1005 
WIN-FVEN9JQLHNF\Netmon Users S-1-5-21-1826645653-3098134492-4231775046-1004 
BUILTIN\Administrators S-1-5-32-544
BUILTIN\Hyper-V Administrators S-1-5-32-578 
BUILTIN\Performance Log Users  S-1-5-32-559 

Regarding priviledges:
Privilege Name                  Description                               State   
=============================== ========================================= ========
SeIncreaseQuotaPrivilege        Adjust memory quotas for a process        Disabled
SeSecurityPrivilege             Manage auditing and security log          Disabled
SeTakeOwnershipPrivilege        Take ownership of files or other objects  Disabled
SeLoadDriverPrivilege           Load and unload device drivers            Disabled
SeSystemProfilePrivilege        Profile system performance                Disabled
SeSystemtimePrivilege           Change the system time                    Disabled
SeProfileSingleProcessPrivilege Profile single process                    Disabled
SeIncreaseBasePriorityPrivilege Increase scheduling priority              Disabled
SeCreatePagefilePrivilege       Create a pagefile                         Disabled
SeBackupPrivilege               Back up files and directories             Disabled
SeRestorePrivilege              Restore files and directories             Disabled
SeShutdownPrivilege             Shut down the system                      Disabled
SeDebugPrivilege                Debug programs                            Disabled
SeSystemEnvironmentPrivilege    Modify firmware environment values        Disabled
SeRemoteShutdownPrivilege       Force shutdown from a remote system       Disabled
SeUndockPrivilege               Remove computer from docking station      Disabled
SeManageVolumePrivilege         Perform volume maintenance tasks          Disabled
SeImpersonatePrivilege          Impersonate a client after authentication Enabled 
SeCreateGlobalPrivilege         Create global objects                     Enabled 
SeTimeZonePrivilege             Change the time zone                      Disabled
SeCreateSymbolicLinkPrivilege   Create symbolic links                     Disabled

Do you thing any of those differences can cause the problem that I have?

**Comment by iLearnIdentityServer** [comment]
Also, I found some "name collisions" when monitoring Identity Server startup
![procmon](https://cloud.githubusercontent.com/assets/16447799/13619070/848697f4-e587-11e5-8e08-7fea851a74c4.JPG)

**Comment by iLearnIdentityServer** [comment]
I found the problem.

I'm relying on platform invoke to function from Userenv.dll, advapi32.dll for user creation, user profile creation, impersonation and so on.

I just forgot to load user profile before doing impersonation.
