### ISSUE TITLE
CustomViewService Selft Hosted

### ISSUE THREAD

**Issue by avmp2208** [IdentityServer/IdentityServer3#2681]
Hello, I tried to user CustomViewService on a Selft Hosted service (windows service) using owin, but all the pages dosen´t find all style, css, even angular apps, the only data the service render is the html from the pages.

> WebApp.Start<Startup>(url);

if I try to fin a css with the full url throws 404 error 

> http://localhost/content/app/app.js

If anybody have done an example like this, I´ll appreciate

Best Regards.

**Comment by brockallen** [comment]
If you're self hosting then you need something to serve up the static files. Look into the static file middleware from Katana/Microsoft.

**Comment by avmp2208** [comment]
thanks brock, I just downloaded Microsoft.Owin.StaticFiles and call the extentions method. on the appbuilder.

`app.UseStaticFiles(); `

That was it, you can closed this question now,
Best Regards
