### ISSUE TITLE
SignInId incorrect constant value

### ISSUE THREAD

**Issue by josephgardner** [IdentityServer/IdentityServer3#2682]
[`OwinEnvironmentExtensions.GetSignInMessage()`](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinEnvironmentExtensions.cs#L438) without any arguments uses [`Constants.Authentication.SigninId`](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Constants.cs#L726) to get the query string value. However, the constant value "signinid" does not match the actual parameter name used by login, "[signin](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/LoginPageLinkExtensions.cs#L39)", and the extension always returns `null`.

Does the constant value need to be updated to "signin"?

**Comment by brockallen** [comment]
Yes, there is a mismatch. I'd say that this is a breaking change, so for now, I'd suggest passing in the name explicitly based on the context.

**Comment by johnkors** [comment]
Is it a breaking change if it's not been working in the first place? :) If we change only the extension method, and not the constant - we would be fine, wouldn't we?

**Comment by brockallen** [comment]
done
