### ISSUE TITLE
Hosting IdentityServer in a Nancy Application

### ISSUE THREAD

**Issue by pashute** [IdentityServer/IdentityServer3#2683]
Missing in the documentation: So here they are...

**Hosting IdentityServer3 in a Nancy Appliction**

IdentityServer3 hosting needs an OWIN startup class. 
So if your Nancy app is not an Owin app, all you need to do is 

1. Nuget the Nancy.Owin package

2. Add an Owin-Startup.cs class (this not just a class, after nugetting the Nancy Owin you'll find adding an OWIN Startup class in the options after right-mouse clicking on your project. 

3. Check that you are DotNet version 4.5. And Nuget Update all packages. 

4. Nuget IdentityServer3. 

5. Fill in the Startup code. 

You'll probably need also a Certificate class, and the three IDSrv3 components: Clients, Scopes and Users. 

You can use inmem to test that everything is working, and then in an advanced version configure with your actual settings / user-store / client store and perhaps scope store. 

------------------------------

This should link in to a page about securing a Nancy app against the IDSrv3, which is another issue altogether.

**Comment by brockallen** [comment]
We accept PRs on our docs.
