### ISSUE TITLE
Disable Homepage 

### ISSUE THREAD

**Issue by dknaack** [IdentityServer/IdentityServer3#2684]
Ive searched but found nothing. 

How can i deactivate the home page of the identity server 3.
I need no ui at this point.

Later i will move to identity server 4 but for now i need to deactivate the ui.
I already have implemented the IViewService to return 

                var ms = new MemoryStream();
                var sw = new StreamWriter(ms);
                sw.Write("");
                return Task.FromResult((Stream)ms);

But there is no option to disable the home page.

**Comment by leastprivilege** [comment]
EnableWelcomePage on the options.
