### ISSUE TITLE
Custom IRedirectUriValidator Question

### ISSUE THREAD

**Issue by danutzplusplus** [IdentityServer/IdentityServer3#2685]
Hello, This is more of a question than an issue.

We have a system in place where the post_logout_uri will contain some custom values. Basically we'd like to perform a more custom request from the client to the idserver, but we have to make sure the previous (if any) authentication session is cleared. So, we'd like to do that logout, and then we need a way to reinitiate the initial request after the logout. And one way we found would be to make the post_logout_uri equal to the value of the initial request.

And this is where the DefaultRedirectUriValidator will turn that down because, as you most probably know, the validator checks the full post logout uri. Would you see any issue (security or otherwise) with writing a custom IRedirectUriValidator that, for logout uris, checks that the requested logout uri just starts with the one in the db (and not the whole uri).

Or in other words, if the post_logout_uri = 'https://localhost:443/endpoint?custom_value=123', the validator will just check the 'https://localhost:443/endpoint' part.

Thanks, and have a good one.
Dan

**Comment by leastprivilege** [comment]
Why don't you store "custom_value=123" in your app and redirect to /endpoint (where the custom value gets picked up again). The less (unprotected) data you round trip - the better.

**Comment by danutzplusplus** [comment]
Hm, good point. I guess the easiest would be to store that in a protected cookie, to keep the server stateless. Thanks a bunch for the tip.
