### ISSUE TITLE
WS-Fed windows service relying party

### ISSUE THREAD

**Issue by eaba** [IdentityServer/IdentityServer3#2686]
@brockallen The WS-Fed Relying Party Sample goes like so:
```
new RelyingParty
                {
                    Realm = "urn:testrp",
                    Name = "Test RP",
                    Enabled = true,
                    ReplyUrl = "https://web.local/idsrvrp/",
                    TokenType = TokenTypes.Saml2TokenProfile11,
                    TokenLifeTime = 1,

                    ClaimMappings = new Dictionary<string,string>
                    {
                        { "sub", ClaimTypes.NameIdentifier },
                        { "given_name", ClaimTypes.Name },
                        { "email", ClaimTypes.Email }
                    }
                },
```
What I want to understand is `ReplyUrl = "https://web.local/idsrvrp/"` and `Realm = "urn:testrp"`, what will be the ReplyUrl, Realm for a Windows Service Party?
Thanks!

**Comment by brockallen** [comment]
These are configuration settings that are needed by the WS-Fed protocol.

**Comment by eaba** [comment]
Yes I understand, but I dont know what values these should be for a windows service relyingparty.

**Comment by brockallen** [comment]
If there's no human, then why are you using ws-fed? Ws-fed is a browser-based user authentication protocol.

**Comment by eaba** [comment]
I am using WCF to Sync Databases with Sync Framework!

**Comment by brockallen** [comment]
Well, you're using the wrong protocol then.

**Comment by eaba** [comment]
Okay Thanks!
