### ISSUE TITLE
External Provider: Why does OpenIdConnectMiddleware not persist the id_token to use later as a hint on logout?

### ISSUE THREAD

**Issue by ciaranj** [IdentityServer/IdentityServer3#2687]
I've seen various issues documenting this behaviour such as  #2457 and #1000 but I cannot get this to work.

If I setup the AuthorizationCodeReceived or SecurityTokenValidated handler to update the passed context's AuthenticationTicket.  By the time the RedirectToIdentityProvider callback is triggered during a logout the 'OwinContext.Authentication.User stubbonly refuses to have an id_token claim.

My OIDC notifications look like: 
```
    RedirectToIdentityProvider = n => {
        if (n.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnectRequestType.LogoutRequest) {
                             var idTokenHint  = n.OwinContext.Authentication.User.FindFirst("id_token");
                             if (idTokenHint  != null) {
                                 n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                             }
                         }
                         return Task.FromResult(0);                            
                    }
```
and
```
                    RedirectToIdentityProvider = n => {
                         if (n.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnectRequestType.LogoutRequest) {
                             var idTokenHint  = n.OwinContext.Authentication.User.FindFirst("id_token");
                             if (idTokenHint  != null) {
                                 n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                             }
                         }
                         return Task.FromResult(0);                            
                    }
```

when I step through the code I definitely have a n.ProtocolMessage.IdToken during AuthoriszationCodeReceived, but I never have the claim in n.OwinContext.Authentication.User.FindFirst .

Any assistance as to how I could debug this further would be greatly appreciated as I presume I'm doing something incredibly daft as this code seems to be all over the web (and presumably working for people!)

**Comment by ciaranj** [comment]
Observation:
If I reconfigure my IdentityServerOptions to use a DataProtector that looks like https://github.com/IdentityServer/IdentityServer3/blob/a6e2b6bdfd1516af6cd9fdc9f46a08bb23bb553e/source/Tests/UnitTests/Conformance/NoDataProtector.cs then all of a sudden the code above starts to work!

**Comment by ciaranj** [comment]
So... more information!
By swapping to a 'no-op' data protector and finding my way around the ticket data format (Gzipped, who knew!) I can peer into the cookies that are being sent to the browser.

I can see that when the 'callback' i've specified in my OpenIdConnectAuthenticationOptions completes the contents of my 'idsrv.external' cookie contains exactly the claims I expect, e.g. the id_token I've added is there (hooray?!) but this completed response is a 302 with a location header back onto the IdSrv to /callback however the response from /callback (which is another redirect to /authorize) also clears the idsrv.partial and idsrv.external cookies.

This ultimately means that when I attempt to do a logout later, there's no idsrv.external cookie present to use to get the id_token back :(  Any ideas what the hell I've managed to do to break this (or is this what you expect, the partial and external cookies to be cleared out?)

**Comment by ciaranj** [comment]
So if I build my OpenIdConnectAuthenticationNotifications to look like

```
                    AuthorizationCodeReceived = n => {
                        n.OwinContext.Response.Cookies.Append("stored_id_token",  n.ProtocolMessage.IdToken);
                        return Task.FromResult(0);
                    },
                    RedirectToIdentityProvider = n => {
                         if (n.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnectRequestType.LogoutRequest) {
                             var idTokenHint= n.Request.Cookies["stored_id_token"];
                             if (idTokenHint  != null) {
                                 n.ProtocolMessage.IdTokenHint = idTokenHint;
                                var signOutMessageId = n.OwinContext.Environment.GetSignOutMessageId();
                                if (signOutMessageId != null)
                                {
                                    n.OwinContext.Response.Cookies.Append("stored_sign_out_message", signOutMessageId);
                                }

                             }
                         }
                         return Task.FromResult(0);                            
                    }
                }
            };
```

and pair it with a new owin mapping like:
```
           app.Map("/core/myoidccb-signout", signout => signout.Run(async ctx => {
                   var state = ctx.Request.Cookies["stored_sign_out_message"];
                   await ctx.Environment.RenderLoggedOutViewAsync(state);
               }));
```

Then everything works 'ok' for me.  However I do not understand why I need to store the id_token in a cookie where none of the other existing examples suggest this is required?

**Comment by brockallen** [comment]
You're really asking questions about Microsoft's middleware. This is the wrong place for those.

**Comment by ciaranj** [comment]
Granted, but I justed wanted to make sure that my configuration of IdentityServer is correct as I appear to have needed to deviate from other examples used by people on *this* project :/

**Comment by brockallen** [comment]
If you are using an external provider to IdSvr, then in the AuthenticateExternal you can issue any claims you want and they will get persisted in the authentication cookie for IdSvr. This might include the id_token for use as the id_token_hint at signout time back to the external IdP.

**Comment by ciaranj** [comment]
Ah, ok.  So (I'm using MembershipRebootUserService) so I guess I need to override GetClaimsForAuthenticateResultAsync (so I don't end up with those claims getting stored in the claims tables). thank you.

**Comment by brockallen** [comment]
Yes, that would make sense.

**Comment by photomoose** [comment]
I, too, am having this issue. How is it possible to get the id_token from within AuthenticateExternal or GetClaimsForAuthenticateResultAsync?

**Comment by hubaksis** [comment]
@photomoose 
If you are talking about 
AuthenticateExternalAsync(ExternalAuthenticationContext context) then I did the following:
1. In the configuration of external IdentityProviders save the claim:
```
var options = new OpenIdConnectAuthenticationOptions() { 
...
Notifications = new OpenIdConnectAuthenticationNotifications
   {
...
      SecurityTokenValidated = n =>
       {
       //Making available new claim id_token_serverUID in the AuthenticateExternalAsync to 
       var id_token = n.ProtocolMessage.IdToken;
       n.AuthenticationTicket.Identity.AddClaim(new System.Security.Claims.Claim("my_parameter", id_token));
      return Task.FromResult(0);
   },
...
}
```

2. Then in the UserService, you can get if from the context.ExternalIdentity.Claims.
```
public override Task AuthenticateExternalAsync(ExternalAuthenticationContext context)
{
...
if (context.ExternalIdentity.Claims != null && context.ExternalIdentity.Claims.Where(x=>x.Type == "my_parameter").Any())
   {
       string externalIdToken = context.ExternalIdentity.Claims.Where(x => x.Type == "my_parameter").FirstOrDefault().Value;
   }
```

3. (optional) I needed these steps for the external logout (set the id_token_hint for the external server), so I added the following code into the 'Notifications' (step 1)
```
 RedirectToIdentityProvider = n =>
 {
  // if signing out, add the id_token_hint
  if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
  {
   var idTokenHint = n.OwinContext.Authentication.User.FindFirst("my_parameter");
      if (idTokenHint != null)
     {
      n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
      var signOutMessageId = n.OwinContext.Environment.GetSignOutMessageId();
      if (signOutMessageId != null)
      {
        n.OwinContext.Response.Cookies.Append("state", signOutMessageId);
      }
   }
}
return Task.FromResult(0);
}

```
