### ISSUE TITLE
Authorization_Code flow for public app?

### ISSUE THREAD

**Issue by jtithof** [IdentityServer/IdentityServer3#2688]
My understanding is that public apps (those that cannot keep a secret) should not use the authorization code flow and instead use the implicit flow. My understanding also is that as part of the initial authorization request, that public apps should send response_type = 'token' and should never send response_type = 'code'.

I've stood up an instance of IdentityServer3 and have a public app that is sending response_type = 'code' in their authorization request. In my custom IClientStore if I set the Client.Flow to Flows.AuthorizationCode, then a 'No client secret found' error is thrown upon token request. This is expected as the client does not have a secret. However, if I change the Client.Flow to Flows.Implicit, then an 'Invalid flow for client' error is thrown, presumably because the client is sending response_type='code'.

I'm not convinced this is an issue with IdentityServer3, and I feel that the client should be sending a different response type, but I wanted to be sure. Is my understanding correct? Or could I be doing something incorrectly in my IdentityServer3 setup?

**Comment by brockallen** [comment]
For code flow, even for public clients, we require a secret. Given that it's a public client then the secret really isn't secret.

**Comment by jtithof** [comment]
Thanks for the quick reply. Is there any way to override the default IdentityServer3 secret validation logic?

**Comment by brockallen** [comment]
Read up on ISecretValidator in the docs.

**Comment by jmandel** [comment]
>For code flow, even for public clients, we require a secret. Given that it's a public client then the secret really isn't secret

We agree, then, that public clients "are* allowed to use the authorization code flow. 

@brockallen do you also agree that OAuth permits the use of a code flow *without* client authentication? That is, is the current password requirement "just" an implementation limitation in IdentityServer, or does is represent your interpretation of a limitation in the OAuth spec? 

In SMART Health IT, we designed our authorization protocol as a profile on OAuth with the following properties:
 
 * avoid giving public clients anything called a "secret", because it sets false expectations and confuses developers 

 * avoid the implicit flow because it requires developers to adopt defensive practices to mitigate token injection attacks (and many developers get this wrong) 

Together, these constraints led us to use the code flow without authentication for public clients. We've documented this at http://docs.smarthealthit.org/authorization/

**Comment by brockallen** [comment]
> @brockallen do you also agree that OAuth permits the use of a code flow without client authentication? 

Yes. IdentityServer simply always requires a client secret. Google works the same way, IIRC.

When I code native clients I use the value "not_a_secret" for the secret.

**Comment by jmandel** [comment]
Sorry: what I meant to clarify was, do you agree OAuth *allows* use of the code flow without any secret (even if you don't choose/want to support that in IdentityServer)?

**Comment by brockallen** [comment]
It doesn't matter if I agree with it -- OAuth2 allows it and people use it.

**Comment by jmandel** [comment]
Sorry, we're talking past each other :-)

You're saying you support calls to `/token` that *include* an `Authorization: Basic` header where the password is a fixed non-secret secret. Gotcha, and that's fine.

I'm asking about calls to `/token` that have no `Authorization` header, and instead just identify a `client_id` (no "secret" at all) as a query parameter. This is allowed by the OAuth spec,, but not supported by IdentityServer. As far as I can tell.

**Comment by brockallen** [comment]
IdSvr can accept the client credentials either as basic auth header or in post body. In both cases, the secret is required.

**Comment by jmandel** [comment]
OK, thanks! To summarize, calling the `token` endpoint without authentication is a feature that OAuth 2.0 supports but IdentityServer does not.

Is it architecturally hard to support? Would you be likely to accept a pull request implementing that functionality if one was proposed?

**Comment by brockallen** [comment]
That's @leastprivilege decision.

**Comment by jtithof** [comment]
@leastprivilege do you have any comment on this?

**Comment by leastprivilege** [comment]
We decided to disallow anonymous calls to the token endpoint. No plans to change that.

**Comment by jmandel** [comment]
OK, that clears things up @leastprivilege.

@jtithof: it sounds like unless you want to fork/extend `IdentityServer` yourself to build support for public client (unauthenticated) access to the `token` endpoint, you won't be able to use it for your SMART on FHIR implementation.

**Comment by leastprivilege** [comment]
So yeah - you are right, strictly speaking OAuth 2.0 does not require the client secret. But we wanted to reduce the complexity of the token endpoint and the client configuration. That's why we decided to require a secret (even if it is "no secret").
