### ISSUE TITLE
Refresh AccessTokenLifeTime when refreshing the page

### ISSUE THREAD

**Issue by avmp2208** [IdentityServer/IdentityServer3#2689]
Hi, I hope you're well

     first of all thanks for this very good project, this time my question is 
    Where and how to set the refresh token parameter to refresh the access token when refreshing the page?

I have this so far.
My client config
`AllowedScopes = new List<string>
{ 
   Constants.StandardScopes.OpenId,
   Constants.StandardScopes.Profile,
   Constants.StandardScopes.Email,
   Constants.StandardScopes.OfflineAccess,
   "read",
   "write"
  },

AccessTokenType = AccessTokenType.Jwt,
AccessTokenLifetime = 20, //in seconds
SlidingRefreshTokenLifetime = 1296000, //in seconds = 15 days
RefreshTokenUsage = TokenUsage.OneTimeOnly,
RefreshTokenExpiration = TokenExpiration.Sliding`

And my startup Client config

`JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

			app.UseCookieAuthentication(new CookieAuthenticationOptions
			{
				AuthenticationType = "Cookies"
			});

			app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
			{
				ClientId = "ImplicityClient",
				Authority = Constants.BaseAddress,
				RedirectUri = Constants.UrlClient,
				PostLogoutRedirectUri = Constants.UrlClient,
				ResponseType = "id_token token",
				Scope = "openid email write offline_access",

				SignInAsAuthenticationType = "Cookies",

				Notifications = new OpenIdConnectAuthenticationNotifications
				{
					SecurityTokenValidated = async n =>
					{
						var token = n.ProtocolMessage.AccessToken;
						// persist access token in cookie
						if (!string.IsNullOrEmpty(token))
						{
							n.AuthenticationTicket.Identity.AddClaim(
								new Claim("access_token", token));
						}
						var nid = new ClaimsIdentity();
						nid.AddClaim(new Claim(@"id_token", n.ProtocolMessage.IdToken));
					},
					RedirectToIdentityProvider = n =>
					{
						// if signing out, add the id_token_hint
						if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
						{
							var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
							if (idTokenHint != null)
								n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
						}
						return Task.FromResult(0);
					},
					AuthorizationCodeReceived = async n =>
					{
						var tokenClient = new TokenClient(Constants.TokenEndpoint);
						var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);
						// use the access token to retrieve claims from userinfo
						var userInfoClient = new UserInfoClient(new Uri(Constants.UserInfoEndpoint), tokenResponse.AccessToken);
						var userInfoResponse = await userInfoClient.GetAsync();
						// create new identity
						var id = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType);
						id.AddClaims(userInfoResponse.GetClaimsIdentity().Claims);
						id.AddClaim(new Claim("access_token", tokenResponse.AccessToken));
						id.AddClaim(new Claim("expires_at", DateTime.Now.AddSeconds(tokenResponse.ExpiresIn).ToLocalTime().ToString()));
						id.AddClaim(new Claim("refresh_token", tokenResponse.RefreshToken));
						id.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
						id.AddClaim(new Claim("sid", n.AuthenticationTicket.Identity.FindFirst("sid").Value));
						n.AuthenticationTicket = new AuthenticationTicket(new ClaimsIdentity(id.Claims, n.AuthenticationTicket.Identity.AuthenticationType), n.AuthenticationTicket.Properties);
					}

				},
			});`

I can see that the refres_token grant_type doesn´t appear in the claims.
When I log on to my client the IdentityServer gives me the token and a test it waiting 20 seconds to see if it refresh automatically but it doesn´t, after refresh the page the server says "Unathorized code"

Best Regards

**Comment by brockallen** [comment]
You have to write that code yourself. Check the OAuth2 spec on the details. You can use IdentityModel to help from .NET code.

**Comment by avmp2208** [comment]
Thanks brock, but I don´t understand, means that user has to log out and log in every 20 seconds for example?? supose If I set the AccessTokenLifeTime 1 hour and the user during that hour is still working wiht out log out from the system... means that passed that hour he has to log out to get a new refreshed token?? I mean, have to be a friendly way, 

Yestearday I set up the AccessTokenLifeTime for 6 hours, and when I logged In into the system I checked Remember me Checkbox, today I get in the system and tried to use the same token and dosen´t work, even logged into the system.

sorry for my english..

Best regards.

**Comment by brockallen** [comment]
No, it means you need to refresh the access token. I'd suggest that you read the OAuth2 spec to understand this all better.
