### ISSUE TITLE
Missing AuthenticationStatement with WSFed and external authentication

### ISSUE THREAD

**Issue by sortling** [IdentityServer/IdentityServer3#2690]
Hello,

we are using IdentityServer3 with the WS-Federation Plugin as a Claims Provider Trust for AD FS, AD FS acts as the SAML2 IDP for a Shibboleth-SP. The UserService builds on IdentityServer3.AspNetIdentity, local login with username and password works fine. We've been trying to add an external authentication via AusweisApp2/nPa, but the resulting SAML2 delivered to the Shibboleth-SP is missing an AuthnStatement element and creating a Shibboleth session fails. 

I've checked the logs and found that the RequestSecurityTokenResponse(not 100% sure here) is different when authenticating externally, it's missing the AuthenticationStatement part. Here an excerpt of the log when authenticating with username and password:

```
2016-03-10 08:14:24.794 +01:00 [Debug] [2016-03-10T07:14:24.7791424Z] Level=Info, Kind=End, Category='System.Web.Http.Action', Id=7e8df6cc-b0ec-492e-b1af-7f77b95e2943, Message='Action returned 'IdentityServer3.WsFederation.Results.SignInResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
2016-03-10 08:14:24.794 +01:00 [Debug] Returning WS-Federation signin response
2016-03-10 08:14:24.810 +01:00 [Debug] [2016-03-10T07:14:24.8103838Z] Level=Info, Kind=End, Category='System.Web.Http.Action', Id=7e8df6cc-b0ec-492e-b1af-7f77b95e2943, Operation=ApiControllerActionInvoker.InvokeActionAsync, Status=200 (OK)
2016-03-10 08:14:24.810 +01:00 [Debug] [2016-03-10T07:14:24.8103838Z] Level=Info, Kind=Begin, Category='System.Web.Http.Filters', Id=7e8df6cc-b0ec-492e-b1af-7f77b95e2943, Message='Action filter for 'Get()'', Operation=SecurityHeadersAttribute.OnActionExecutedAsync, Status=200 (OK)
2016-03-10 08:14:24.810 +01:00 [Debug] [2016-03-10T07:14:24.8103838Z] Level=Info, Kind=End, Category='System.Web.Http.Filters', Id=7e8df6cc-b0ec-492e-b1af-7f77b95e2943, Operation=SecurityHeadersAttribute.OnActionExecutedAsync, Status=200 (OK)
2016-03-10 08:14:24.841 +01:00 [Debug] [2016-03-10T07:14:24.8103838Z] Level=Info, Kind=Begin, Category='System.Web.Http.Filters', Id=7e8df6cc-b0ec-492e-b1af-7f77b95e2943, Message='Action filter for 'Get()'', Operation=NoCacheAttribute.OnActionExecutedAsync, Status=200 (OK)
2016-03-10 08:14:24.841 +01:00 [Debug] [2016-03-10T07:14:24.8416359Z] Level=Info, Kind=End, Category='System.Web.Http.Filters', Id=7e8df6cc-b0ec-492e-b1af-7f77b95e2943, Operation=NoCacheAttribute.OnActionExecutedAsync, Status=200 (OK)
2016-03-10 08:14:24.841 +01:00 [Debug] [2016-03-10T07:14:24.8416359Z] Level=Info, Kind=End, Category='System.Web.Http.Controllers', Id=7e8df6cc-b0ec-492e-b1af-7f77b95e2943, Operation=WsFederationController.ExecuteAsync, Status=200 (OK)
2016-03-10 08:14:24.857 +01:00 [Debug] HTTP Response
"{
  \"StatusCode\": \"OK\",
  \"Headers\": [
    {
      \"Key\": \"X-Content-Type-Options\",
      \"Value\": [
        \"nosniff\"
      ]
    },
    {
      \"Key\": \"Cache-Control\",
      \"Value\": [
        \"no-store, no-cache, max-age=0, private\"
      ]
    },
    {
      \"Key\": \"Pragma\",
      \"Value\": [
        \"no-cache\"
      ]
    }
  ],
  \"Body\": \"<html><head><title>Working...</title></head><body><form method=\\"POST\\" name=\\"hiddenform\\" action=\\"https://my_adfs_host/adfs/ls/\\"><input type=\\"hidden\\" name=\\"wa\\" value=\\"wsignin1.0\\" /><input type=\\"hidden\\" name=\\"wresult\\" value=\\"&lt;trust:RequestSecurityTokenResponseCollection xmlns:trust=&quot;http://docs.oasis-open.org/ws-sx/ws-trust/200512&quot;>&lt;trust:RequestSecurityTokenResponse...
  
  [some lines removed for clarity, the following is missing on external login]
  
  ...&lt;saml:AuthenticationStatement AuthenticationMethod=&quot;urn:oasis:names:tc:SAML:1.0:am:password&quot; AuthenticationInstant=&quot;2016-03-10T07:14:24.701Z&quot;>&lt;saml:Subject>&lt;saml:SubjectConfirmation>&lt;saml:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:bearer&lt;/saml:ConfirmationMethod>&lt;/saml:SubjectConfirmation>&lt;/saml:Subject>&lt;/saml:AuthenticationStatement>&lt;Signature xmlns=&quot;http://www.w3.org/2000/09/xmldsig#&quot;>&lt;SignedInfo>&lt;CanonicalizationMethod Algorithm=&quot;http://www.w3.org/2001/10/xml-exc-c14n#&quot; />&lt;SignatureMethod Algorithm=&quot;http://www.w3.org/2001/04/xmldsig-more#rsa-sha256&quot; />

```
  
The resulting SAML2 Assertion passed to the Shibboleth-SP by AD FS only has the needed AuthnStatement when logging in with username/password, the following part is always missing when logging in externally:

`<AuthnStatement AuthnInstant="2016-03-08T10:10:37.153Z" SessionIndex="_1203b083-1cba-4618-a2a4-c82a3d5de221"><AuthnContext><AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</AuthnContextClassRef></AuthnContext></AuthnStatement>   `

The external authentication uses Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware and creates an Identity from a providerKey we query:

```
        protected override async Task<AuthenticationTicket> AuthenticateCoreAsync()
        {
            [some lines removed for clarity]

            var identity = new ClaimsIdentity(Options.SignInAsAuthenticationType);
            identity.AddClaim(new Claim(System.Security.Claims.ClaimTypes.NameIdentifier,
                providerKey, XmlSchemaString, Options.AuthenticationType));

            return new AuthenticationTicket(identity, properties);
      }
```
			
An entry in dbo.AspNetUserLogins referencing the external login to a local user is present.

I'm a bit at a loss on how to proceed from here, could somebody please provide some pointers on the matter.

Many thanks in advance.

**Comment by leastprivilege** [comment]
did you make progress on this?

**Comment by sortling** [comment]
In WsFederationPlugin\ResponseHandling\SignInResponseGenerator.cs in Line 180 the AuthenticationMethod is added as Claim, but only if GetAuthenticationMethod() returns "password". 

```
if (validationResult.Subject.GetAuthenticationMethod() == Constants.AuthenticationMethods.Password)
    {

        mappedClaims.Add(new Claim(ClaimTypes.AuthenticationMethod, AuthenticationMethods.Password));
        mappedClaims.Add(AuthenticationInstantClaim.Now);

    }
```
Why is this Claim only added if the AuthenticationMethod is password?

**Comment by leastprivilege** [comment]
I can't remember - would it solve your problem if we always add the authN method?

**Comment by sortling** [comment]
Okay, managed to modify SignInResponseGenerator and add the necessary claims:

```
if (validationResult.Subject.GetAuthenticationMethod() == Constants.AuthenticationMethods.Password)
    {
        mappedClaims.Add(new Claim(ClaimTypes.AuthenticationMethod, AuthenticationMethods.Password));
        mappedClaims.Add(AuthenticationInstantClaim.Now);
    }
    else if (validationResult.Subject.GetIdentityProvider() == "eid")
    {
        mappedClaims.Add(new Claim(ClaimTypes.AuthenticationMethod, AuthenticationMethods.Smartcard));
        mappedClaims.Add(AuthenticationInstantClaim.Now);
    }
```

While this does allow to successfully create a Shibboleth session, I would have to fork the WSFederationPlugin. Or is there a way to inject a custom SignInResponseGenerator? Provide the needed claims sometime during the external authentication? I can catch the missing AuthenticationMethod claim in AD FS with a claim rule and provide a default, but that won't work for the AuthenticationInstant, which is a timestamp.

**Comment by leastprivilege** [comment]
OK - first of all please open a new issue on the ws-fed repo.

**Comment by sortling** [comment]
Yes, always adding the authN method would be fine for me, thx!

I guessed the reason for conditionally adding only the password was that it's the only one present in both System.IdentityModel.Tokens.AuthenticationMethods (For WSFed) and IdentityServer3.Core.Constants.AuthenticationMethods (IdSrv3). Maybe map all AuthenticationMethods != "password" to AuthenticationMethods.Unspecified?
