### ISSUE TITLE
InvalidOperationException: IDX10803: Unable to create to obtain configuration from: Oracle Identity Federation Provider

### ISSUE THREAD

**Issue by keg7271** [IdentityServer/IdentityServer3#2691]
I am attempting to use identity server 3 with an On-premise Oracle Identity Federation server using Ws-Fed and SAML token.  I have successfully created a MVC app without identity server that correctly logs in users.  But am unable to determine how to get IS3 to function as the middle-tier in the configuration.

I have attempted to follow https://identityserver.github.io/Documentation/docsv2/configuration/identityProviders.html document to configure the identity server.

The setup is
1. IdentityServer3 hosted in Azure WebApp
2. MVC client
3. WebAPI (just an additional scope)

Scenario:
1. Browse to a secured page on the MVC client
2. Identity Server responds and prompts user for local credentials or external providers in my case On-Premise OIF and Google.
3. User clicks on-premise button to initiate authentication through OIF.
4. InvalidOperationException: IDX10803 message displayed.

The ssl cert to the metadata is trusted, don't know if it is expired, I'd assume not.
I can take the federation metadata url and paste it into a browser and it returns without issue or complaints about the certificate.

Here is the metadata url: https://devidselfserv.ul.com/fed/idp/metadata
You can paste it into a web browser and test for yourself.

What am I doing wrong?

**Comment by keg7271** [comment]
Please test it for yourself.

IS3: https://dev.identity.ul.com
Clients: https://dev-ulio-clients.azurewebsites.net - Click the Secure button under Secured Pages
Then on IS3 login page click UL button.

**Comment by leastprivilege** [comment]
We are not providing support for SAML2p. 

If you are using third party middleware to connect to your saml provider - please contact the developer/vendor of that middleware.

Or are you using the Microsoft WS-Fed middleware? If yes - that's the wrong one for SAML2

**Comment by keg7271** [comment]
Alright thank you.

**Comment by travisjs** [comment]
@leastprivilege 

> Or are you using the Microsoft WS-Fed middleware? If yes - that's the wrong one for SAML2

Why is that the wrong one?
