### ISSUE TITLE
AuthorizeResponse method does not include the model's Custom object property

### ISSUE THREAD

**Issue by jbrittan** [IdentityServer/IdentityServer3#2694]
The AuthorizeResponse method in the DefaultViewService does not include the Custom property on the model that is passed to the method.  When it goes to create a new CommonViewModel to use to format and render the page, it only includes the SiteName and SiteUrl properties from the model that is passed to it.  My layout page relies on values from the custom property and I am seeing script errors because those are missing from the model.  Thanks in advance.

**Comment by brockallen** [comment]
Ok, I see. Yep, that's a bug. I'll get a fix in.

**Comment by brockallen** [comment]
fixed on dev
