### ISSUE TITLE
Open two login page, login from first one, and then idsrv3 throw an exception

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2695]
I user idsrv3 Authorization code flow in IIS. If I open two login page continually and then I switch to the first page to login, the idsrve will throw an exception. I know that it is because of the state and nonce parameter is not match.  Since I save the two parameters in the cookie, when I access the login page secondly, the new parameter(state and nonce) cover the old ones. When the third application do login callback, it found that the parameter is not match.
What is the best way to fix this problem? Thank you very much!

**Comment by brockallen** [comment]
Your client app is the one throwing the exception, not IdSvr. It's the Katana middleware, which means you should ask Microsoft.

**Comment by Farwell-Liu** [comment]
Thank you brockallen!
Yes, I knew that the client app throw the exception not idsrv3 when validated the parameters( "state" and "nonce"). However, it is still in process of authorization flow. What's I want to know is what's the best practice to solve this problem. Save the "state" and "nonce" in DB not cookie? 
If I save the state and nonce in DB, It seems that there are many works I need to to. I need to create a table in idsrv3 application DB, and for every requst to login page the cilent app need to call idsrv3 webapi twice more to save and read  "state" and "nonce". 
Or if I ask the client app to save the "state" and "nonce" by themself, every client app need to do the same works.
Could you give me some suggestions please? Thank you for taking the time to read my words.

**Comment by brockallen** [comment]
If you don't want to use Microsoft's framework, then you can look at our sample here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MvcCodeFlowClientManual

**Comment by Farwell-Liu** [comment]
In fact, I just use this MVC CodeFlowClient Manual sample indeed. My code is copy from it. Now I found that the sample code has the same problem too. My operation step as below:
1. access the url: https://localhost:44312/, click OK button and then redirect to the login page.
2. open a new tab in IE, and then access the url: https://localhost:44312/, click OK button and then redirect to the login page.
3.  switch the IE tab to login page of step 1. and then enter bob/bob to login. IE redirect to the url:
https://localhost:44312/callback?code=e7ef2...., and show the invalid state like this: 
> State: 69c0cdd44e524d4eb94df658d5f1a0a7 (invalid) 

What's the usual practice to handle the state and nonce parameter? Thank you!

**Comment by brockallen** [comment]
Logging in with multiple tabs is a hard problem to address, thus the problems you're experiencing.
