### ISSUE TITLE
prompt=none does not show an error

### ISSUE THREAD

**Issue by fekberg** [IdentityServer/IdentityServer3#2696]
### Issue

When appending `prompt=none` to an authorization request, according to the spec it should not allow the login to be seen at all if this parameter is passed.

> The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request. The error code will typically be login_required, interaction_required, or another code defined in Section 3.1.2.6. This can be used as a method to check for existing authentication and/or consent.

Any reason I am not seeing an error?

### Reproduce:

`/connect/authorize?client_id=test_implicit&redirect_uri=redirect&response_mode=form_post&response_type=id_token&scope=openid&prompt=none`

**Comment by PinpointTownes** [comment]
(BTW, you should also see an error telling you your OIDC request is invalid as it doesn't include the mandatory `nonce` parameter, which is required when using the implicit flow: http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest)

**Comment by leastprivilege** [comment]
What are you seeing? ;)

**Comment by fekberg** [comment]
Hm. It's odd, because I am definitely sure I did see the Login Prompt. Now that I'm trying again, it's giving me a few good errors.

Must have been something weird on my end! Sorry for the false alarm. :)
