### ISSUE TITLE
Cannot get custom claims from bearer access token

### ISSUE THREAD

**Issue by dunglp** [IdentityServer/IdentityServer3#2698]
Hi @leastprivilege ,

I was trying to add custom claim named seller_id to access_token like this 

```
var preferredClaims = new[] { "given_name", "family_name", "sub", "seller_id" };
                        foreach (var claim in preferredClaims.Select(preferredClaim => n.AuthenticationTicket.Identity.FindFirst(preferredClaim)).Where(claim => claim != null))
                        {
                            id.AddClaim(claim);
                        }

n.AuthenticationTicket = new AuthenticationTicket(new ClaimsIdentity(id.Claims, n.AuthenticationTicket.Identity.AuthenticationType),
                                                                          n.AuthenticationTicket.Properties);
```

And in my API solution, I tried to get seller_id from Access_token but seems no custom claims are available here:

`((ClaimsIdentity)User.Identity).Claims`

Am I doing it wrong ? 
Thanks in advance.

**Comment by El-Wray** [comment]
Have the same problem.

**Comment by leastprivilege** [comment]
I am guessing you are doing this in your client application?

**Comment by dunglp** [comment]
Yes, @leastprivilege . 
I added custom claims in my client application, after user logged in to system. And I want to access those custom claims in my API solution.

**Comment by leastprivilege** [comment]
Well - identityserver is issuing the token - not your client app.

Check the docs on scopes and claims

**Comment by dunglp** [comment]
I already have it in GetProfileDataAsync in IdSv.

```
 var sellerId = claims.FirstOrDefault(c => c.Type.Equals("seller_id"));

            if (sellerId != null)
            {
                identity.AddClaims(new[]
                {
                    new Claim("seller_id", sellerId.Value),
                });
            }
```

` ctx.IssuedClaims = identity.Claims;`

**Comment by leastprivilege** [comment]
well - then check if the claims are really in the token. I am sure you already debugged your code.

You can use http://jwt.io to check your token.

**Comment by dunglp** [comment]
Hi @leastprivilege,

I just check my tokens.

```
AuthorizationCodeReceived = async n =>
                    {
                        // use the code to get the access and refresh token
                        var tokenClient = new TokenClient(
                            MpConstants.TokenEndpoint,
                            ConfigurationManager.AppSettings["ClientId"],
                            ConfigurationManager.AppSettings["ClientSecret"]);

                        var response = await tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);
                        
```

In response.IdentityToken I can see my seller_id, but cannot see it in response.AccessToken.
Did I miss anything ?

**Comment by leastprivilege** [comment]
probably.

**Comment by BruceHunter** [comment]
How are you getting custom claims into the system? AspNetIdentity?

**Comment by dunglp** [comment]
Yes, @BruceHunter . 
I am using IdentityServer3.AspNetIdentity.

I inserted custom claims inside `public override async Task GetProfileDataAsync(ProfileDataRequestContext ctx)`

**Comment by dunglp** [comment]
@BruceHunter do you have any idea ?
