### ISSUE TITLE
Question about the DefaultConsentService 

### ISSUE THREAD

**Issue by oclaude** [IdentityServer/IdentityServer3#2699]
Hello,

I'm sorry if this question has already asked but I don't understand the default implementation of the Consent Service.

If I configure not required scopes for a client and the user uncheck one or more scopes that he would not share, the consent is asked again at the next login. The "remember my decision" is checked of course.

By searching in source code I found that you check the intersect that could never true if a user uncheck one or more scopes.

``
var consent = await _store.LoadAsync(subject.GetSubjectId(), client.ClientId);
            if (consent != null && consent.Scopes != null)
            {
                var intersect = scopes.Intersect(consent.Scopes);
                return !(scopes.Count() == intersect.Count());
            }
``

This is may be a part of one specification but could you tell me why it's necessary to ask again the user's consent?

Thank you for your explaination.
Regards.
Olivier

**Comment by brockallen** [comment]
If the user checks "remember my consent" and the client asks for something different then the user is re-prompted.
