### ISSUE TITLE
What should I set the redirectURI for authenticating towards an openid connect server

### ISSUE THREAD

**Issue by mobilars** [IdentityServer/IdentityServer3#2700]
This question has been asked and answered several times, but I'm still not able to find the solution, so I'm sorry for being such a noob to have to ask it again.

I'm trying to set up one IdentityServer3 to authenticate towards another using OpenId connect. The user goes to ids1, and then gets redirected to ids2 for authentication, and then back to ids2 for the rest of the authorization process. It seems very simple to do from various web pages, but I'm not able to get the redirect back from ids2 to ids1, because I don't know what to put in the redirectURI field. The same question has been asked here: #1517 and answered:"If you do nothing special, then it's the path at which the OIDC MW is registered. Otherwise you can configure a custom callback path.", but I don't quite understand how to do that, and I've been trying for many hours to find out (I'm not very experienced with this framework as you can guess). 

My project is based on the "WebHost (Minimal)" code, and I've added an oauth authentication provider like this: (In this case the redirect goes back to the root of my ids1, but it gives an error message saying that POST isn't allowed, so that can't be right at least). I've tried many many other options :-) I'd really appreciate a helping hand. 

`using Microsoft.Owin;
using Owin;
using Configuration;
using IdentityServer3.Core.Configuration;
using Serilog;
using IdentityServer3.Host.Config;
using Microsoft.Owin.Security.OpenIdConnect;

[assembly: OwinStartup(typeof(WebHost.Startup))]

namespace WebHost
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Trace(outputTemplate: "{Timestamp} [{Level}] ({Name}){NewLine} {Message}{NewLine}{Exception}")
                .CreateLogger();

            var factory = new IdentityServerServiceFactory()
                        .UseInMemoryUsers(Users.Get())
                        .UseInMemoryClients(Clients.Get())
                        .UseInMemoryScopes(Scopes.Get());

            var options = new IdentityServerOptions
            {
                SigningCertificate = Certificate.Load(),
                Factory = factory,
                AuthenticationOptions = new AuthenticationOptions
                {
                    IdentityProviders = ConfigureAdditionalIdentityProviders,
                }
            };

            app.Map("", idsrvApp =>
            {
                idsrvApp.UseIdentityServer(options);
            });
        }

        public static void ConfigureAdditionalIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var openid = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "MyId",
                Caption = "My ID",
                ClientId = "codeclient",
                ClientSecret = "secret",
                Authority = "https://fhirauth.azurewebsites.net/",
                RedirectUri = "https://fhirauthorization.azurewebsites.net/",

                ResponseType = "code",
                Scope = "openid profile",

                SignInAsAuthenticationType = signInAsType,
            };
            app.UseOpenIdConnectAuthentication(openid);

        }
        }
}`

**Comment by mobilars** [comment]
It works with the following implicit-flow example, and it seems from [this post](http://www.appetere.com/Blogs/SteveM/August-2014/Getting-started-with-OpenID-Connect) that code-flow isn't supported. So I guess then I need to find some other solution. Any plans for supporting code flow? Is that a matter of the plugin rather than the IdentityServer3-implementation?

`public static void ConfigureAdditionalIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var openid = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "MyId",
                Caption = "My ID",
                ClientId = "nolib.client",
                ClientSecret = "secret",
                Authority = "https://fhirauth.azurewebsites.net/",
                RedirectUri = "https://fhirauthorization.azurewebsites.net/",

                ResponseType = "id_token",
                Scope = "openid profile",

                SignInAsAuthenticationType = signInAsType,
            };
            app.UseOpenIdConnectAuthentication(openid);

        }`

**Comment by leastprivilege** [comment]
It's a matter of the "plugin". The response must contain an id_token IIRC - so a response type of `code id_token` should work.

**Comment by mobilars** [comment]
That seems to work also, but it's then still using implicit/hybrid flow it seems? I'm only allowed to use code flow between the two identityservers, and this isn't supported by the plugin-id3 combo, right? There was some mention in a thread of another plugin that may have implemented code flow also, but I'm not sure it works with IdentityServer3 (an asp.net plugin?). 

I found this late last night: 

http://stackoverflow.com/questions/33661935/owin-middleware-for-openid-connect-code-flow-flow-type-authorizationcode 

Security concerns have made the people owning the server wanting to use code flow, to use a cilent secret + enable scenarios where the id_token itself isn't shown to the user's browser.

**Comment by leastprivilege** [comment]
The consensus is that `code id_token` is the most secure combination. This way you get a detached signature of the code (inside the id_token).

All claims can then be retrieved via the userinfo endpoint.

**Comment by mobilars** [comment]
Hmmm... OK. That'd be the c_hash? 

I think they're thinking that they don't want to rely on the redirect_url only to hand out the id_token, but would prefer having the client-secret in the flow to hand it out (maybe even a client certificate).

Will IdentityServer3 actually fetch userinfo using the userinfo-url? Or does it just rely on the id_token passed in the url?

**Comment by leastprivilege** [comment]
It is the job of the MW to do the protocol business. The MS MW does not do that by default but you can add the necessary code in a notification.

**Comment by mobilars** [comment]
OK, thanks for your help. Closing the question as I think it's answered now. Will reopen or re-ask if I need further clarification.
