### ISSUE TITLE
The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by virendra1117** [IdentityServer/IdentityServer3#2701]
Hello ,I want to use thinktecture identity server3 for SSO. I gone through the documentation.
I get the code of thinktecture identity server as authorization provider and a MVC OWIN Client (Hybrid) as client.But when I run client application and hit on claim menu i got "The remote certificate is invalid according to the validation procedure" error. I also installed idsrv3test.pfx certificate on may machine. Please give me suggestion for this issue.

**Comment by brockallen** [comment]
This is an error when you don't have SSL properly configured. Check the MSDN docs for that.
