### ISSUE TITLE
Asp.net MVC  implicit flow, calling web api with expired Access_token 

### ISSUE THREAD

**Issue by iBoonz** [IdentityServer/IdentityServer3#2702]
Hi,

I currently have a client that uses Implicit flow as authentication, and this client gets his data via another Web API that is secured with UdentityServerBearerTokenAuthentication, everything works, but when the timeout exeeds of the Acces_token I get a 401 when I fetch my data via a HttpClient. 

How should I handle this 401? Refresh tokens are not used with implicit flow, so should I expand the lifetime of the access token? 

Thanks for the info :)

**Comment by mderriey** [comment]
You can try reissuing an [authorization request](https://identityserver.github.io/Documentation/docsv2/endpoints/authorization.html) with the value `consent=none`. If the user is still logged in against IdentityServer, you'll get back a fresh set of identity and access token.

I don't really know where this should happen on the sevrer side, though. Maybe in the cookies OWIN middleware where you can expect the validity of the access token for each HTTP request on your MVC application.

@leastprivilege and @brockallen might have more insight

**Comment by iBoonz** [comment]
Hey @mderriey , thanks for the info, there are several solutions, but I don't know what solution I should use. I can do following things: 

- Increase the lifetime of the acces_token to 10 houres, so it is in sync with the Idsrv token 
- Get a client token for the MVC application via the Client Credential flow (extra call?)
- Like you said: reissuing an authorization request with the value consent=none (I should find out how   and where to put this logic ).

For the time being I increased the access_token lifetime. But I don't know if this is best practice.

**Comment by leastprivilege** [comment]
it's `prompt=none` ;)

Are you calling the web api from the server or the client?

**Comment by iBoonz** [comment]
Always from the server

- The user logs into the MVC application
- The MVC client makes the REST calls to the API client with the BEARER token of the user

**Comment by leastprivilege** [comment]
and are these calls on behalf of the logged on user? or server to server?

**Comment by iBoonz** [comment]
I need the subjectId in the Web API, so it is on behalf of the logged on user. 
Thats the main reason I dont want to use the Client Credentials Role, otherwise I need to send extra headers to the request.

**Comment by leastprivilege** [comment]
ok - and do you trust the MVC app? I mean - do you really need a token for the user - or is it good enough that the MVC app calls the API and puts the userid in the payload?

**Comment by leastprivilege** [comment]
or IOW - is the same API also being called directly by client without the MVC app in the middle?

**Comment by eaba** [comment]
In my case, having lots of webapi and a MVC front this is what I did:
I setup my MVC according to the MVC Hybrid sample.
I store the access token as a claim
At every call my user makes the access token lifetime is checked
If it has expired then we refresh the token.
Follow The MVC Hybrid SAMPLE

**Comment by iBoonz** [comment]
@leastprivilege the API can be called by different clients. the API is actually an implementation of the MembershipReboot of Brock, with extended info, like Tenant and such. 

@eaba, thanks for the info, but I don't like using the payload for the userId, It needs to be in the token. But currently this is still a possible solution.

**Comment by leastprivilege** [comment]
If you do a trusted subsystem - client credentials flow is good enough. If you need delegation because the direct caller is not fully trusted - you need the user token (with all implications around lifetime).

**Comment by iBoonz** [comment]
@leastprivilege Currently I want to keep using the Implict flow, but my client gets a 401 at some point when making API calls to another client. 

my ASP.NET MVC application, has methods with the Authorize attribute, when the user navigates to this method, the user is successfully authorized, but gets a 401 when doing an API call with the access token

So how can I refresh my access tokens, when the user stil has a valid session, that has sliding expiration. 

If I use a smaller ExpireTimespan on my client (with SlidingExpiration), and use a larger sliding expiration on my Identityserver, will my access token also be refreshed if the cookie is refreshed.

Example:
Client Cookie Authentication ( UseTokenLifetime = false)
`   app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                SlidingExpiration = true,
                ExpireTimeSpan = new TimeSpan(3,0,0),
            });`

IdSrv Cookie options
`var cookieOptions = new IdentityServer3.Core.Configuration.CookieOptions
            {
                //Set to 10 hours
                ExpireTimeSpan = TimeSpan.FromHours(10),
                //Set to true
                SlidingExpiration = true,
                //Set to 10 hours, 
                RememberMeDuration = TimeSpan.FromHours(10),
            };
`

To be clear on following items:

- **Client cookie**: Cookie that tells the client that the user has a valid session, if the session has expired the middelware wil redirect to the login page 
- **IdentityServer cookie**: Cookie that tell the Identity server that the user needs to re login, if the cookie is not expired, the user is automatically logged in 

- **id_token**: Token that is used in the client to verify if the user is who he says he is and on success create the client cookie. (thats why its only valid for 5 minutes), this is handled by the middelware with the authorize attribute

- **access_token**: a token with claims that is used to access other API resources.

**Comment by leastprivilege** [comment]
No - the access token will not get refreshed automatically.

Either extend the lifetime of the access token (you are keeping it on the server anyways). Or use hybrid flow - for 2 reasons: the access token will never get exposed to the client machine and you could use refresh tokens.
