### ISSUE TITLE
Mapping the identity from an external IDP to local

### ISSUE THREAD

**Issue by buddhike** [IdentityServer/IdentityServer3#2703]
### Question

I'm looking at an option for mapping an identity in an external IDP to an internal one. For example, a client may issue auth request with acr=idp:external_idp. External IDP requires a redirection to authenticate the user.

Once the user is authenticated at external idp, I would like him to authenticate again locally (using IdSrv login screen) so that I can map the external identity to the local one. 

Is there a neat extensibility point in IdSrv to implement this?

**Comment by leastprivilege** [comment]
I think you can do a redirect in `PostAuthenticateAsync`

**Comment by buddhike** [comment]
Thanks Dom. 

Are you thinking of redirecting the user to local endpoint in PostAuthenticateAsync?

If I include acr=idp:external_idp, IdSrv is going to execute my external IDP integration middleware. This is the part which does the redirection. When I get the callback, I would like to check if the identity from external idp has a mapping to the local one. If there's isn't a mapping, it should get the end user to login using local credentials. I could do another redirect to a login form. But I would like to reuse the login form if possible.

**Comment by leastprivilege** [comment]
ExternalAuthenticateAsync should work as well - it muss be a local form in our pipeline. Check the docs on the user service and partial logins.

**Comment by buddhike** [comment]
Great, partial login sounds like what exactly I'm after. Thanks heaps!!
