### ISSUE TITLE
Loging out of identity server

### ISSUE THREAD

**Issue by thrane** [IdentityServer/IdentityServer3#2704]
I am trying to implement identity server into an existing application so that others can use the fact that a user is logged into my system or not. 
Doing this i have setup the identity server to read information from the existing authentication system to determine if a user is logged in. This part works great.
But now i want to be able to log out of the identity server when i logout of the other system.
I have found an url that does this for me:
/connect/endsession
but i was wondering if there is a handle in the c# code i can use instead of calling this url my self?

**Comment by brockallen** [comment]
What are you looking to do? You can implement SignOut in the user service.

**Comment by thrane** [comment]
I have, but this is not getting called. I have 
Request.GetOwinContext().Authentication.SignOut(); 
in my signout function.
I use the app.Map("/oauth", i => i.UseIdentityServer(options)); in startup to configure the identity server. I have looked at app.UseOpenIdConnectAuthentication to configure the identity server, but i am not currently using it. Doesnt this require me to have the whole site using identity server? Some  of the site use classic asp auth.

**Comment by brockallen** [comment]
Ok, I think I see now --so from your external system you would need to redirect the user to IdSvr's signout endpoint. I just blogged out some of these recently, so maybe it will help:

http://brockallen.com/2016/02/08/single-sign-out-and-identityserver3/

http://brockallen.com/2016/02/09/federated-sign-out-and-identityserver3/
