### ISSUE TITLE
IdenityServer in an enterprise environment - Resolve user information across multiple databases

### ISSUE THREAD

**Issue by lexon0011** [IdentityServer/IdentityServer3#2705]
We use the IdenityServer as our central authentication provider. Now I have a general question about the IdenityServer in an enterprise environment. I try to explain it with the following example:

1. If a user was successfully authenticated, he get a token from the provider. The token includes the unique ID of the user.
2. The authenticated user send a request to a WebApi, to create a new item (e.g a new product).
3. The WebApi extract the unique ID from the token and creates the new product in the database. Additionally the new product was linked with the unique user ID (e.g as creationUserId).
4. An other user send a request to the WebApi to get all available products.
5. The WebApi create a database query to retrieve all products. Additionally the WebApi wants to convert the creationUserId of each product to the correlating username. But that is not possible, because username is stored in the identity database which is an other database one than the product database. Are there some best practices to solve this requirement?

Many thanks for your help!

Regards

**Comment by brockallen** [comment]
Include the name claim in the token then.

**Comment by lexon0011** [comment]
In that case I have to store the user information in both databases. Correct? 

So it is not easy to manage changes on the identities: For example, if the last name of a user will have changed (e.g. in a marriage), then all application-database contains outdated user information.

**Comment by brockallen** [comment]
Well, I don't know what to tell you -- I think you understand the issues and mechanics. It's not magic :)
