### ISSUE TITLE
Possible bug in ScopeSecretValidator

### ISSUE THREAD

**Issue by maxkornev** [IdentityServer/IdentityServer3#2706]
Hi
Recently i watched class ScopeSecretValidator and i think that method ValidateAsync doesn't work properly. 
Client info parsed using SecretParser this way:
`var parsedSecret = await _parser.ParseAsync(_environment.Environment);`
And then scope is defined this way:
`var scope = (await _scopes.FindScopesAsync(new[] { parsedSecret.Id })).FirstOrDefault();`
Into FindScopeAsync passed **parsedSecret.Id** that is client_id, but this method expects scope name according its signature and implementation:
```
public Task<IEnumerable<Scope>> FindScopesAsync(IEnumerable<string> scopeNames)
        {
            if (scopeNames == null) throw new ArgumentNullException("scopeNames");
            
            var scopes = from s in _scopes
                         where scopeNames.ToList().Contains(s.Name)
                         select s;

            return Task.FromResult<IEnumerable<Scope>>(scopes.ToList());
        }
```

As the result validation is always failed.

**Comment by leastprivilege** [comment]
Scopes can have secrets too.

**Comment by maxkornev** [comment]
I know that scopes can have secrets too. But when i configure my web application to use identity server  and set ClientId and ClientSecret this way:
```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
			{
				Authority = "https://localhost:44333/core",
				RequiredScopes = new[] { "UserInfo" },

				// client credentials for the introspection endpoint
				ValidationMode = ValidationMode.ValidationEndpoint,
				ClientId = "old_client",
				ClientSecret = "secret"
			});
```
I can see in debugger that parsedSecret.Id is clientid - my "old_client". I think that this is the reason why my requests to web client are always unauthorized. In identity server console i see two consequent messages
- secret id found: old_client
- no scope with that name found. aborting

Also i attach client configuration:
```
public static Client GetOldDeviceClient()
		{
			return new Client
			{
				ClientName = "Old client",
				Enabled = true,

				ClientId = "old_client",
				ClientSecrets = new List<Secret>
				{
					new Secret("secret".Sha256())
				},

				Flow = Flows.ResourceOwner,

				RequireConsent = true,
				AllowRememberConsent = true,

				AllowedScopes = new List<string>
				{
					"UserInfo"
				},

				AccessTokenType = AccessTokenType.Reference,
				AccessTokenLifetime = 90000,
				RefreshTokenUsage = TokenUsage.ReUse,
				RefreshTokenExpiration = TokenExpiration.Absolute
				
			};
		}
```
and scope configuration:
``` 
new Scope()
		        {
			        Name = "UserInfo",
			        Claims = new List<ScopeClaim>() {new ScopeClaim(Constants.ClaimTypes.Name, true),new ScopeClaim(Constants.ClaimTypes.Email, true)},
			        Type = ScopeType.Resource
		        }
```
When i dont set clientId and clientSecret in IdentityServerBearerTokenAuthenticationOptions and my request is sent in tokenvalidation endpoint instead of introspection endpoint everythink works well

**Comment by leastprivilege** [comment]
ClientId and ClientSecret refer to a scope name and a scope secret.

I know the naming is not perfect - but that how it works (and is documented).

**Comment by maxkornev** [comment]
thanks a lot, i was really my mistake

**Comment by daiduongbian44** [comment]
Hi all,
I have the same error with this log:
w3wp.exe Information: 0 : 2016-03-24 14:02:15.953 +07:00 [Information] Start introspection request
2016-03-24 14:02:15.959 +07:00 [Debug] Start scope validation
2016-03-24 14:02:15.960 +07:00 [Debug] Start parsing Basic Authentication secret
2016-03-24 14:02:15.960 +07:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
w3wp.exe Information: 0 : 2016-03-24 14:02:15.960 +07:00 [Information] Secret id found: "apidev"
w3wp.exe Information: 0 : 2016-03-24 14:02:15.964 +07:00 [Information] No scope with that name found. aborting
w3wp.exe Warning: 0 : 2016-03-24 14:02:15.964 +07:00 [Warning] Scope unauthorized to call introspection endpoint. aborting.

Where "apidev" is client_id. I don't know why :(

@maxkornev, @leastprivilege can you explain the detail how to solve that? I have got the access_token (as resource owner flow) but when use that token to call authorized Apis, always missing 401
Thanks.

**Comment by maxkornev** [comment]
Hi daiduongbian44.
According to @leastprivilege answer
> ClientId and ClientSecret refer to a scope name and a scope secret.

I pass scope name and scope secret to IdentityServerBearerTokenAuthenticationOptions instead of clientId and client secret.
Working code looks like
```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
			{
				Authority = "https://localhost:44333/core",
				RequiredScopes = new[] { "MyScope" },

				// client credentials for the introspection endpoint
				ValidationMode = ValidationMode.ValidationEndpoint,
				ClientId = "MyScope",
				ClientSecret = "ScopeSecret"
			});
```

**Comment by daiduongbian44** [comment]
Oh, awesome, but i'm wondering, when i wanna to call more than one scope, how to declare clientID and cliendSecret :D

**Comment by maxkornev** [comment]
I guess that you should use credentials of one of the required scopes

**Comment by leastprivilege** [comment]
what does "wanna to call more than one scope" mean?

**Comment by daiduongbian44** [comment]
Oh, you know, i mean, when declaring client for identityserver3, we can declare the set of scopes which that client can uses. The code looks like this:
```
AllowedScopes = new List<string> {
"apiscope1",
"apiscope2",
....
}
```

and when registering app>
```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44333/core",
                RequiredScopes = new[] { "apiscope1", "apiscope2", ... },
                ValidationMode = ValidationMode.ValidationEndpoint,
                ClientId = "?",
                ClientSecret = "?"
            });
```
In this case, what is clientid and clientSecret. Thanks all. :D

**Comment by leastprivilege** [comment]
one of them. 

The introspection response will by default only return the scope that was used for authentication (if the scope was included in the token at all). There is a scope setting `AllowUnrestrictedIntrospection` - which when enabled will return all scopes.

**Comment by daiduongbian44** [comment]
Yep. Thanks all very much! :D :D
Best and regards:
ManhNQ
