### ISSUE TITLE
UserService to check roles

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2707]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Mine is an AngularJS SPA.

I have a successfull implementation of _UserService_ and _AuthenticateLocalAsync(LocalAuthenticationContext context)_ accesses by DB.

After the successfull login the user sees a home page with a link to the_profile _page. But this profile page is governed by roles. When the user clicks the link to the profile page his roles should be checked and the page rendered. Is there a way to not show this link based on the user's claims/roles ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This is up to your Angular logic, is it not?

**Comment by mohanr** [comment]
Yes.  I can send the token with claims to another service for validation before rendering.

How does the context in GetProfileDataAsync(ProfileDataRequestContext context) get the right claims from the DB ? There is a link between my DB calls and this context I may be missing.

I have my users and claims in the DB and clients/scope in memory.

**Comment by brockallen** [comment]
Check the docs for `GetProfileDataAsync`: https://identityserver.github.io/Documentation/docsv2/advanced/userService.html. It says:

> RequestedClaimTypes: The list of claim types requested. The user service should only return claim types as indicated by this property.

**Comment by mohanr** [comment]
So if I get a claim with an improper role IsActiveAsync(IsActiveContext context) can check and possibly show an error page. Is this correct ? Is the error page display the task of the CustomViewService ?

**Comment by brockallen** [comment]
Did you change topics? I don't really understand what you're now asking. If it's a new question, open a new issue.

**Comment by mohanr** [comment]
It is the same question about how to handle improper roles in _UserService_. I am checking which one of the methods is appropriate. I have included Role as the RequestedClaimTypes.

                      `
                          public AuthenticateResult(string errorMessage);

`
does display the error on the login page itself. I am able to get the claims from my DB in _AuthenticateLocalAsync(LocalAuthenticationContext context)_

**Comment by brockallen** [comment]
> It is the same question about how to handle improper roles in UserService.

I don't know what you mean by improper roles. If you're saying that not all roles should be sent to all clients, then in the `GetProfileData` you are passed a context which contains the client id -- use that to filter the roles that you do not want for that client.

**Comment by mohanr** [comment]
GetProfileData - That is useful information.

In my case the role of the logged-in user may not allow him to proceed further. He doesn't have the role permission. So that is checked in AuthenticateLocalAsync itself ? I will close this after your comment and research this further.

**Comment by brockallen** [comment]
If you want to prevent the request to IdSvr then look at the ICustomRequestValidator -- this allows you to trigger an error at authorization time.

**Comment by mohanr** [comment]
Thanks. Closing for further research.
