### ISSUE TITLE
AspNetIdentityUserService create user in AspNetIdentity Local user store

### ISSUE THREAD

**Issue by charettedavid** [IdentityServer/IdentityServer3#2708]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I there a way to avoid External login to create Local users in my AspNetIdentity database?

The AuthenticateExternalAsync get fired at each external login since i added AspNetIdentityUserService.

Any idea?

Thank you

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
I don't follow.

**Comment by charettedavid** [comment]
Each time i sign in with an external user (ADFS) the AuthenticateExternalAsync is fired and a user record is created into AspNetIdentity Database, table "AspNetUsers"

**Comment by brockallen** [comment]
Sounds like you need to override `AuthenticateExternalAsync` and take control so it exhibits the behavior you want.

**Comment by charettedavid** [comment]
In fact i think my issue is when an external user signin a user is created in my AspNetIdentity database, but never get updated, if user add claims ou update them i never get updated claims. i looked into IdentityServer3.AspNetIdentity.AspNetIdentityUserService 
and there is no update user info method.

Is there a mecasism to implement that?

**Comment by brockallen** [comment]
It's all up to your requirements. Our default implementation was done this way because we felt that the more common scenario would be you capture the external claims only the first time. If they change in the external provider, then you have a heap of logic to deal with mismatches and it's always possible that for your app the user doesn't want automatic updates if you allow them a separate mechanism to configure their profile.

**Comment by charettedavid** [comment]
You right for some claims, but i user some others like "group" to manage some access logics. where i would add my logic without loosing all of your default implementation? 

thanks

**Comment by brockallen** [comment]
Well, the base class is included as a source file so you can inspect/learn how it works. Override any virtuals you feel makes sense, or just change the base class source.
