### ISSUE TITLE
Cannot get PostSignOUtAutoRedirect to work

### ISSUE THREAD

**Issue by cxc256** [IdentityServer/IdentityServer3#2709]
I would like Identity Server to redirect to a page in my application after a user logs out. I've configured Identity Server as follows:
`Log.Logger = new LoggerConfiguration( ).MinimumLevel.Verbose( ).WriteTo.File( @"C:\SomePath\Log.txt" ).CreateLogger( );

			var factory = new IdentityServerServiceFactory( )
				.UseInMemoryUsers( Users.Get( ) )
				.UseInMemoryClients( Clients.Get( ) )
				.UseInMemoryScopes( Scopes.Get( ) )
				;

			ICorsPolicyService corsPolicyService = new DefaultCorsPolicyService( )
			{
				AllowAll = true,
				//AllowedOrigins = new []
				//{
				//	//"https://Dev:4432",
				//	"https://dev:4432",
				//},
			};

			factory.CorsPolicyService = new Registration<ICorsPolicyService>( corsPolicyService );

			var authOptions = new AuthenticationOptions( )
			{
				EnableSignOutPrompt = false,
				EnablePostSignOutAutoRedirect = true,
			};

			app.Map( "/identity", idsrvApp =>
			{
				idsrvApp.UseIdentityServer( new IdentityServerOptions
				{
					SiteName = "IdentityServer",
					IssuerUri = "https://SecurityServerDev",
					Factory = factory,
					SigningCertificate = LoadCertificate( ),
					AuthenticationOptions = authOptions,
				} );
			} );
		}`

I have configured my application with the following:
`public void ConfigureAuth( IAppBuilder app )
		{
			JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>( );
			AntiForgeryConfig.UniqueClaimTypeIdentifier = JwtClaimTypes.Subject;

			app.UseCookieAuthentication( new CookieAuthenticationOptions
			{
				AuthenticationType = "Cookies"
			} );

			app.UseOpenIdConnectAuthentication( new OpenIdConnectAuthenticationOptions
			{
				Authority = AuthorizationConstants.IdSrvURL,
				ClientId = ConfigurationManager.AppSettings[ "ida:ClientId" ],
				RedirectUri = ConfigurationManager.AppSettings[ "ida:LoginRedirect" ],
				PostLogoutRedirectUri = ConfigurationManager.AppSettings[ "ida:PostLogoutRedirect" ],
				ResponseType = "code id_token token",

				Scope = "openid profile roles someAPI",

				SignInAsAuthenticationType = "Cookies",
				Notifications = new OpenIdConnectAuthenticationNotifications( )
				{
					SecurityTokenValidated = async n =>
					{
						var newIdentity = new ClaimsIdentity( n.AuthenticationTicket.Identity.AuthenticationType, ClaimTypes.GivenName, JwtClaimTypes.Role );

						var userInfo = await EndpointAndTokenHelper.CallUserInfoEndpoint( n.ProtocolMessage.AccessToken );

						var issuerClaim = n.AuthenticationTicket.Identity.FindFirst( JwtClaimTypes.Issuer );
						var uniqueNameClaim = n.AuthenticationTicket.Identity.FindFirst( JwtClaimTypes.Subject );
						var userName = userInfo.Value<string>( JwtClaimTypes.PreferredUserName );

						var profileClaims = new ClaimsTransformer( ).GetTake2ProfileClaims( userName );
						newIdentity.AddClaims( profileClaims );
						newIdentity.AddClaim( issuerClaim );
						newIdentity.AddClaim( uniqueNameClaim );

						try
						{
							var roles = userInfo.Value<JArray>( JwtClaimTypes.Role ).ToList2( );
							roles.ForEach( r => newIdentity.AddClaim( new Claim( JwtClaimTypes.Role, r.ToString( ) ) ) );
						}
						catch ( InvalidCastException )
						{
							var role = userInfo.Value<string>( JwtClaimTypes.Role );
							newIdentity.AddClaim( new Claim( JwtClaimTypes.Role, role.ToString( ) ) );
						}

						newIdentity.AddClaim( new Claim( "access_token", n.ProtocolMessage.AccessToken ) );
						newIdentity.AddClaim( new Claim( "id_token", n.ProtocolMessage.IdToken ) );

						n.AuthenticationTicket = new AuthenticationTicket( newIdentity, n.AuthenticationTicket.Properties );
					},
					RedirectToIdentityProvider = n =>
					{
						if ( n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest )
						{
							var id = n.OwinContext.Authentication.User.FindFirst( "id_token" );
							if ( id != null )
								n.ProtocolMessage.IdTokenHint = id.Value;
						}
						return Task.FromResult( 0 );
					}
				},
			} );

		}`

I know the post Logout URI I specify in Identity Services Client is the same as [ "ida:PostLogoutRedirect" ]

However, I never get to my application's page.

I found this in the log:
2016-03-14 17:10:10.175 -07:00 [Error] "Invalid post logout URI"
"{
  \"ClientId\": \"Take2\",
  \"ClientName\": \"Take2\",
  \"SubjectId\": \"10006abdced\",
  \"PostLogOutUri\": \"https://Dev:4432/Scripts/OauthJSClient/Logout.html\",
  \"Raw\": {
    \"post_logout_redirect_uri\": \"https://Take2Dev:4432/Scripts/DGAOauthJSClient/Logout.html\",
    \"id_token_hint\": \"eyJ0eXAiO.....Correct Token\"
  }
}"
2016-03-14 17:10:10.176 -07:00 [Information] Redirecting to logout page
2016-03-14 17:10:10.186 -07:00 [Information] Logout prompt for subject: "10006abdced"
2016-03-14 17:10:10.186 -07:00 [Information] EnableSignOutPrompt set to false, performing logout
2016-03-14 17:10:10.189 -07:00 [Information] Logout endpoint submitted
2016-03-14 17:10:10.189 -07:00 [Information] Logout requested for subject: "10039006"
2016-03-14 17:10:10.189 -07:00 [Information] Clearing cookies
2016-03-14 17:10:10.202 -07:00 [Information] rendering logged out page
2016-03-14 17:10:10.429 -07:00 [Information] End session callback requested
2016-03-14 17:10:10.432 -07:00 [Debug] No client end session iframe URLs

Can you please tell me what I am doing wrong?

**Comment by brockallen** [comment]
URI comparisons are exact string matches -- see if there's a trailing slash one one but not the other.

**Comment by cxc256** [comment]
That was it!! I had one character in the URL capitalized. Thank you!!

**Comment by stephan-simondshealth-com-au** [comment]
Hey CXC256,   Do you mind sharing your EndpointAndTokenHelper and ClaimsTransformer implementations?   I reckon your implementation is the closest to what I've seen so far. Thanks !

**Comment by cxc256** [comment]
stephan-simondshealth-com-au, the ClaimsTransformer is a hold over from a legacy app. In my security code, I only use the one method that is specific to one of our apps. Attached is the EndpointAndTokenHelper file. It was taken almost verbatim by one of Brock or Dominick's examples.
[EndpointAndTokenHelper.txt](https://github.com/IdentityServer/IdentityServer3/files/1024138/EndpointAndTokenHelper.txt)
