### ISSUE TITLE
Unexpected "#" being returned instead of "?" from /identity/connect/authorize

### ISSUE THREAD

**Issue by solo812** [IdentityServer/IdentityServer3#2710]
I am having an issue with IdentityServer returning unexpected hash"#" in the querystring that I was hoping you folks could help with. Kudos to Brock, Dominick, and the others for building a great product. I was able to pull down IdentityServer3 and get an STS running with very few issues. As part of a requirement, I have to write a SiteFinity module to use IdentityServer3 as the AuthZ/AuthN provider for Sitefinity. I pulled https://github.com/Sitefinity/Sitefinity-External-STS-Integration as a start and have replaced the mechanics to use IDSrv instead. Everything is working with exception of one small issue I cannot pin down. 

Here is the flow: 

1. Anonymous user requests Sitefinity site

2. SF Auth Plugin redirects to service with URL of "https://localhost:44300/identity/connect/authorize?client_id={guid}&scope=openid%20profile%20email%20permissions%20agencyinfo%20offline_access&response_type=code%20id_token%20token&state={state}&nonce={nonce}&redirect_uri=http%3A%2F%2Flocalhost%3A60876%2FSitefinity%2FAuthenticate%2FSWT

3. Once the redirect occurs and the request is being handled by the /identity/connect/authorize endpoint in IDServ and I log in, I get redirected back to SiteFinity with the following URL http://localhost:60876/Sitefinity/Authenticate/SWT**#**code=6d96d437d29eab366fa52a18ac17fbf9&id_token={id_token}&access_token={access_token}&token_type=Bearer&expires_in=3600&scope=openid%20profile%20email%20permissions%20agencyinfo%20offline_access&state={state}&session_state={session}

As you can see from step number 3, there is the SWT# and the hash "#" is negatively affecting the program being able to read the querystring values that follow the hash. Do you know of anyway to get the return URL to not have the "#" in the string?

I am using a Hybrid flow and not implicit. And from reading this thread, it seems as though this is expected behavior  https://github.com/IdentityServer/IdentityServer3/issues/751 in some cirumstances. 

Any help would be appreciated.

**Comment by brockallen** [comment]
You need to add `response_mode=query` as a param, as per the spec if you want the results via query string (as opposed to the default of hash fragment).

**Comment by brockallen** [comment]
Oh wait, query is invalid for this response_type (as per the spec): https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html. Only fragment or form_post is allowed.

**Comment by solo812** [comment]
Thank you. I see that I need to pull the access_token and other elements from the form post. Very helpful thanks.

**Comment by rosdi** [comment]
To future readers, response_mode parameter is ignored by [oidc-client.js](https://github.com/IdentityModel/oidc-client-jsl). Or at least I could not figure it out how to do it.

You will need to generate the query string manually.

**Comment by brockallen** [comment]
oidc-client only supports implicit, thus the behavior.
