### ISSUE TITLE
Endsession endpoint with an access_token not allowing auto redirect

### ISSUE THREAD

**Issue by Pondidum** [IdentityServer/IdentityServer3#2712]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am trying to get redirect on log out working, but am running into an issue with validating the access_token.  I am submitting the following url to logout:

```
https://localhost:44303/auth/connect/endsession?id_token_hint=the_access_token&post_logout_redirect_uri=https://localhost:44303
```

Identity servier is set to allow auto redirects:
```
idserver.UseIdentityServer(new IdentityServerOptions
{
    EnableWelcomePage = false,
    SigningCertificate = Certificate.Load(_config),
    Factory = factory,
    AuthenticationOptions =
    {
        EnableSignOutPrompt = false,
        EnablePostSignOutAutoRedirect = true
    }
});
```

And the client is defined as this:

```csharp
yield return new Client
{
    ClientName = "useraccess",
    Enabled = true,
    ClientId = "useraccess",
    Flow = Flows.Implicit,
    AllowedScopes = new List<string>
    {
        Scopes.UserApi
    },
    RequireConsent = false,
    RedirectUris = new List<string>
    {
        "https://localhost:44303"
    },
    PostLogoutRedirectUris = new List<string>
    {
        "https://localhost:44303"
    },
};
```

From the logs, it looks like identityserver is pulling the `clientId` from the `aud` property, but in the access_token, the `aud` prop is set to `https://localhost:44303/auth/resources`, which isn't a valid client...

Here is most of the idtoken deserialized:

```
{
  "iss": "https://localhost:44303/auth",
  "aud": "https://localhost:44303/auth/resources",
  "exp": 1458138880,
  "nbf": 1458135280,
  "client_id": "useraccess",
  "scope": [
    "user-api",
    "openid"
  ]
}
```

What should I change to be able to do auto logout with an access_token?

Thanks

### Relevant parts of the log file

```
2016-03-16 13:54:43.157 +00:00 [Error] "Unknown or diabled client."
"{
  \"ClientId\": \"https://localhost:44303/auth/resources\",
  \"ValidateLifetime\": false
}"
2016-03-16 13:54:43.161 +00:00 [Error] "Error validating id token hint."
"{
  \"SubjectId\": \"1\",
  \"Raw\": {
    \"id_token_hint\": \"<token here>\",
    \"post_logout_redirect_uri\": \"https://localhost:44303\"
  }
}"
```

The thing that seems weird to me is the `clientId`: it should be `useraccess` I think, but as I am giving it an access token, its using `https://localhost:44303/auth/resources` from the `aud` property.

**Comment by leastprivilege** [comment]
you need to send the id_token not the access token.

**Comment by Pondidum** [comment]
Ah I think I have it now...for anyone else who comes across this issue:

On client definition:
* add "openid" scope

On login request uri:
* add "openid" scope
* add "nonce" and generate a value

Usage:
* use the id_token for endsession endpoint
* use the access_token for authorized requests

Seems a shame we can't use the access_token for logout, but that's something for my client to deal with...
