### ISSUE TITLE
UseIdentityServerBearerTokenAuthentication to authorize mvc application

### ISSUE THREAD

**Issue by vargamat** [IdentityServer/IdentityServer3#2713]
Hi guys,

I have a mvc application what basically return views for my angular application and I also have an api. Now I have hybrid flow for MVC and implicit flow for angular application. 

Is it possible to change the MVC application to use bearer tokens instead of hybrid flow so I can just get my views as the information from api. I tried to use UseIdentityServerBearerTokenAuthentication but it seems to me that it is integrated only with web api but not with MVC

Thanks in advance

**Comment by brockallen** [comment]
Does your JS do Ajax calls back to MVC endpoints?
