### ISSUE TITLE
Extract authorization code value from callback URL

### ISSUE THREAD

**Issue by WassMM** [IdentityServer/IdentityServer3#2714]
Hello,

I have to connect an IdentityProvider with the configuration:

var myProvider = new OpenIdConnectAuthenticationOptions
{
    Authority = "https://myi-identity-provider/oauth/authorize",
    Caption = "MyProvider",
    ClientId = "client_id_value",
    ClientSecret = "client_secret_value",
    AuthenticationType = "my_authentication_type",
    SignInAsAuthenticationType = "Cookies", // Not sure about the one....
    ResponseType = "code id_token",
    Notifications = new OpenIdConnectAuthenticationNotifications
    {
        AuthorizationCodeReceived = async n =>
        {
            // I would like to be here!!! To request access_token
        },
    },
    // The string must be the same as in azure settings - with the "/" in the end.
    RedirectUri = "https://localhost/#/callback/myprovider",
}

https://localhost - my identityserver address. It works and I could login via the provider. But, the provider returns Authorization code as part of callback URL ( I am not able to change the IdentityProvider behavior) and I would like to "catch" it in AuthorizationCodeReceived  event for to request access_token but I coulnd. Documentation for the event is "Invoked after security token validation if an authorization code is present in the protocol message." - didn't help me unfortunately. So could you help me and explain how to handle it?

Thank you!

**Comment by leastprivilege** [comment]
if there is a code on the response - the notification should fire. That is not an idsrv issue - the middleware is from MS.

**Comment by WassMM** [comment]
My identity provider redirects me like this:
https://localhost/#/callback/myprovider/?status=accepted&code=4ab511167110d7a6718a98a1b9101c322a8dce50

nothing else. I am not sure how idsrv/middleware works, but is it enough that identity provider redirects me like this? No Cookies, no headers - only redirect URL.

**Comment by leastprivilege** [comment]
This is not openid connect (at least not with respect to your request). The
Microsoft mw does not work like that.
—
cheers
Dominick Baier

**Comment by WassMM** [comment]
What I need to change to get it working with OpenIdConnect? Or this is bad idea and I need to implement my owm mw for the IdentityProvider?

**Comment by leastprivilege** [comment]
Well - either the idp must be compatibel with the MS MW - or you need a different MW.

**Comment by WassMM** [comment]
I was hoping you could find something stupid in my code and I have quick solution :) Looks like I have to think about my own mw.

Thank you

**Comment by WassMM** [comment]
This is very good post which helped me a lot:
http://brockallen.com/2013/08/07/owin-authentication-middleware-architecture/

It turns out my MW is very simple to implement.
