### ISSUE TITLE
SSO using Identity server resource owner flow

### ISSUE THREAD

**Issue by pagidigovardhan** [IdentityServer/IdentityServer3#2718]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
My requirement is to use resource owner flow and the below use cases

1. user should be able to login in MVC1 app and redirects/open another MVC2 application 
 next time user doesn't require to enter credentials..

2. Once user logged into web app next time from mobile it shouldn't require any authentication.

Do you have any samples on this???
I've seen samples on federation but I am confused on SSO and Federation.

Can you please suggest me on this..

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
if you want SSO across the multiple apps, then you can't use resource owner password flow.

**Comment by prabhakarkk** [comment]
hi Brockallen,
Thanks for the response.
What is the other alternative flow to achieve SSO?

we are also trying understand, what is Identity Server Login page doing different that our Custom login(with username and password) page is not doing, Can we also follow the same flow as performed in  Identity Server Login page and achieve SSO? 

if we are going to use Identity Server Login page, is there any options to customize the look to fit into the current application theme.

**Comment by brockallen** [comment]
Any via the browser.

**Comment by pagidigovardhan** [comment]
Hi Brockallen,
I am sorry..I couldn't understand your Comment..
Can you please elaborate little more??

**Comment by brockallen** [comment]
I'd suggest reading up on the OAuth2 spec for more information about the flows.
