### ISSUE TITLE
Identity Server as an Identity Provider to ADFS?

### ISSUE THREAD

**Issue by chrolivier** [IdentityServer/IdentityServer3#2719]
### Question / Issue
Hi

Is it possible to set up Identity Server as a Identity Provider to ADFS?
I've been searching the documentation and this forum but cannot seem to find a definitive answer.

Any help would be appreciated.

**Comment by brockallen** [comment]
Yes. We have a WS-Fed plugin that can make IdSvr act as a WS-Fed IdP. See the samples or this repo: https://github.com/IdentityServer/IdentityServer3.WsFederation

**Comment by chrolivier** [comment]
Awesome. Thank you
