### ISSUE TITLE
IdSrv as a proxy of another IdSrv

### ISSUE THREAD

**Issue by mynkow** [IdentityServer/IdentityServer3#2720]
We have IdSrv-1 with resource owner flow up and running. Mobile devices use our Authority endpoint to get tokens. We have also another application with its own IdSrv-2 up and running with different user base however we do not have access to the userbase at all. Is it possible to connect somehow IdSrv-1 with IdSrv-2 so that MobileDevices can get tokens from IdSrv-2 using IdSrv-1? 

=> MobileDevice 
=> tries to autjorize against IdSrv-1 
=> IdSrv-1 forwards the call to IdSrv-2
=> IdSrv-2 authorizes properly against its userbase and returns a token to IdSrv-1
=> IdSrv-1 returns that token to the MobileDevice

**Comment by brockallen** [comment]
Sure -- you can code the `AuthentlocateLocal` in your `IUserService` any way you want.

**Comment by mynkow** [comment]
Yeah, sure. So if I want full integration (such as clients, refresh tokens, userinfo) between the two servers I have to do custom implementation of all interfaces because there is no out of the box integration. Is that correct?

**Comment by brockallen** [comment]
correct -- that's all on you. we don't have any samples that are built with that configuration in mind.

**Comment by mynkow** [comment]
Thank you for the quick answer. :+1:
