### ISSUE TITLE
Partial login

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2721]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Our use case is change password and it is done.

I am trying to understand what type of additional security measure that the _Partial login_ feature enables. I have a access token which means the Idp has logged the user in. I am not introducing another authorization workflow and partially logging in the user before continuing with the Idp's workflow.

The API Constants.ClaimTypes.PartialLoginReturnUrl could be the answer. If I have to resume after changing the password I need a resume URI. The user may resume from a URI based on his authorization level - which may have changed. Is this the basic reason why one would associate partial login with 'Change Password'.

I also think if the SPA has to redirect to the Idp's login URI after the 'Change Password' page then _signin_ id can be obtained like this. This login URI is sent back embedded in the 'Change Password' page for the SPA to redirect after changing password.

Second part : 

Is the token sufficient to make this call succeed _AuthenticationManager.AuthenticateAsync(Constants.PartialSignInAuthenticationType);_

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
> I am trying to understand what type of additional security measure that the Partial login feature enables.

It's not an additional security measure, per-se, but instead partial logins allow you to customize the user's workflow as they login to your identity management system. In short, if you want to show a custom screen to the user during their login process, that's what partial logins allow.

>  Is this the basic reason why one would associate partial login with 'Change Password'.

Only if you want to force the user to change the password after they have logged in, but before they are returned to the client application that they are trying to access.

**Comment by mohanr** [comment]
Is the token sufficient to make this call succeed AuthenticationManager.AuthenticateAsync(Constants.PartialSignInAuthenticationType);

We also need the Cookies set by the Idp. Is that correct ?
Do we send the token and use the validation middleware for _PartialSignInAuthenticationType_ ?

**Comment by brockallen** [comment]
> Is the token sufficient to make this call succeed AuthenticationManager.AuthenticateAsync(Constants.PartialSignInAuthenticationType);

I don't understand the context of this question.

**Comment by mohanr** [comment]
What is the cookie/token the SPA has to send to make AuthenticateAsync succeed ? There is no external authorization flow here. Just a WebApi call from the SPA directly. This may not be the correct usecase but I am trying to understand.

**Comment by brockallen** [comment]
None -- the SPA must redirect the user to the authorization endpoint. For SSO you do not collect the credentials in the client app -- it's about redirecting the user.

**Comment by mohanr** [comment]
I mean AuthenticationManager.AuthenticateAsync(Constants.PartialSignInAuthenticationType);
What is the cookie/token the SPA has to send to make AuthenticateAsync succeed ?

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
