### ISSUE TITLE
Including default scope w/ Clients

### ISSUE THREAD

**Issue by philipbjorge** [IdentityServer/IdentityServer3#2722]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We are using a standalone IdentityServer to issue Reference Tokens right now.
We currently have a monolithic API with endpoints that should be accessible using the reference token. Depending on the scopes associated with the token they will have access to a subset of the APIs.

The current approach I'm going with:
- Require any 3rd-party to request access to the `api` scope solely for the purpose of token introspection within our API application.
  This scope will allow introspection of all scopes
- Introspect the token with AccessTokenValidationMiddleware and the secrets
- Then at our controllers verify the more granular scopes are present in the ClaimsPrincipal

Is that the recommended approach for this scenario?

Is there a way to automatically include the `api` scope with a client so they don't have to manually request it?
One way to do that would be to implement a custom grant that exchanges the token for a token that includes the same scopes + the `api` scope but that seems a little silly.

**Comment by brockallen** [comment]
Scopes are designed to model which client has access to which APIs (independent of the user). This is if you have a scenario where certain clients (regardless of the user) should not be using certain APIs. 

You can always do your own authorization beyond this, of course.

**Comment by philipbjorge** [comment]
So I guess the question is, if a Client requests the scope `abc` is there a way that I can include the scope `xyz` implicitly?

**Comment by brockallen** [comment]
The client should ask for it. If your semantics are that abc implies access to xyz, then that's up to your scope authorization logic.

**Comment by philipbjorge** [comment]
Makes sense. Thanks!
