### ISSUE TITLE
AuthenticateLocalAsync not working

### ISSUE THREAD

**Issue by mabusall** [IdentityServer/IdentityServer3#2723]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Dears,

I have problem AuthenticateLocalAsync not called when i use custom login page, i used custom login page to fit my web site style... i don't what i miss when i post username and password it called login controller to execute my code, and i can't authenticate IdentityServer3 to get token and so on...

my question is how to get authenticated when i call custom login page using my username and password

code on server:

            var userService = new Services.CustomUsersService();
            var factory = new IdentityServerServiceFactory()
                               .UseInMemoryUsers(Users.Get())
                               .UseInMemoryClients(Clients.Get())
                               .UseInMemoryScopes(Scopes.Get());
            factory.UserService = new Registration<IUserService, Services.CustomUsersService>();

            app.Map("/identity", idsrvApp =>
            {
                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Test IdentityServer3",
                    SigningCertificate = LoadCertificate(),
                    Factory = factory,
                    AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
                    {
                        EnablePostSignOutAutoRedirect = true
                    }
                });
            });

           Public class CustomUsersService : IdentityServer3.Core.Services.Default.UserServiceBase
           {
                 OwinContext ctx;

                 public CustomUsersService(OwinEnvironmentService owinEnv)
                 {
                     ctx = new OwinContext(owinEnv.Environment);
                  }
           }

          public override Task PreAuthenticateAsync(PreAuthenticationContext context)
          {
            var id = ctx.Request.Query.Get("signin");
            context.AuthenticateResult = new AuthenticateResult("~/custom/login?id=" + id, (IEnumerable<Claim>)null);

            return Task.FromResult(0);
         }

        public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            // METHOD NOT CALLED
        }

Please Advise,
Thank you

**Comment by brockallen** [comment]
It's hard to say since we have no idea what your custom login page looks like. Check the samples for a working example.

**Comment by mabusall** [comment]
custom login page posts username and password to my controller, then my controller validate username and password from database as below:

        public ActionResult Index(string id, string username, string password)
        {
            var query =
                from u in _db.User
                where u.Username == username && u.Password == password
                select u;

            var user = query.SingleOrDefault();
            if (user != null)
            {
              // TODO: i want to tell IdentityServer3 the user is authenticated, how?
            }
            return View();
        }

i read your sample, but it's not authenticate the user by it's credentials your sample using "Subject" and "Name" as below:

            var env = Request.GetOwinContext().Environment;
            env.IssueLoginCookie(new IdentityServer3.Core.Models.AuthenticatedLogin
            {
                IdentityProvider = IdentityServer3.Core.Constants.BuiltInIdentityProvider,
                Subject = sub,
                Name = name,
            });

            var msg = env.GetSignInMessage(id);
            var returnUrl = msg.ReturnUrl;

            env.RemovePartialLoginCookie();

            return Redirect(returnUrl);

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by mapsupetran** [comment]
I am also stuck on this problem. Ok my case, I validate  the username and password within the AuthenticateLocalAsync method. It worked fine until I overridden PreAuthenticateAsync to redirect to a custom login page.
