### ISSUE TITLE
Can I keep login.html outside from Identity Server 3 application ?

### ISSUE THREAD

**Issue by amoldorkar-ezest** [IdentityServer/IdentityServer3#2724]
I developed a project using ASP.Net 5 which has 2 projects
1. Web Project
2. Identity Server 3 project

by default login page kept in Identity Server 3 application but I want to move it from Identity Server 3 to my Web Project..

How can I do this..?

**Comment by brockallen** [comment]
Dup: https://github.com/IdentityServer/IdentityServer3.Samples/issues/244

Don't open multiple issues with the same question.
