### ISSUE TITLE
Mutually Authentucated SSL

### ISSUE THREAD

**Issue by alhardy** [IdentityServer/IdentityServer3#2725]
I have a client which doesnt feel comfortable from a security point of view in posting client credentials over https so would like to use massl instead. 

In your docs, I came across using clients certs as the client creds with the client credentials flow. Does this provide the same security as massl?

**Comment by brockallen** [comment]
No idea what massl is. We can accept client certificates on the token endpoint, if that's the question. Check the samples.

**Comment by leastprivilege** [comment]
I guess it is Mutual Authenticated SSL ;) Never heard that abbreviation before though.

We support both TLS client certificates (transport authN) and signed JWTs.
