### ISSUE TITLE
Use JsonWebKey instead of X509Certificate2 in ISigningKeyService

### ISSUE THREAD

**Issue by omerlh** [IdentityServer/IdentityServer3#2727]
Hey
Today the current implementation of identity server is highly coupled to X509Certificate. In my case, I am going to store the key used for signing in HSM based solution, and the api provide me easy way to create `RSACryptoServiceProvider` or `JsonWebKey' but creating a `X509Certificate2` involve pretty [ugly](http://www.wiktorzychla.com/2012/12/how-to-create-x509certificate2.html) code. It would be great if it will be possible to remove this dependency, but I guess it will not be easy.
Thanks 
Omer

**Comment by leastprivilege** [comment]
Well - idsrv3 is designed around x509certs right now - no easy way to change that.

Why do you need to create the key material on the fly?

**Comment by omerlh** [comment]
If you are store the key in azure keyvault or in HSM, you can retrieve the public key as JsonWebKey or just the exponent and modules. I am now working on a code that will create a X509Certificate from it, but it became pretty ugly code.

**Comment by leastprivilege** [comment]
that's easy. Just read the x5c. That's the base64 representation of the x509 cert that you can pass into the `X509Certificate2` ctor.

**Comment by omerlh** [comment]
Oh, that's not so easy, look like they are not exposing it - see [this](https://github.com/Azure/azure-sdk-for-net/blob/master/src/KeyVault/Microsoft.Azure.KeyVault/WebKey/JsonWebKey.cs). Also, as I said, if I will use an HSM, than this is not an option, at least as far as I understood the pkcs11 format :)

**Comment by brockallen** [comment]
All set? Can we close.

**Comment by leastprivilege** [comment]
Wanna have a look first.

**Comment by leastprivilege** [comment]
I am fine with an extension method on Token - but it must return a string - not JwtPayload.

**Comment by omerlh** [comment]
OK, sound good. I will try and create a new PR.



On Wed, Mar 30, 2016 at 8:07 AM -0700, "Dominick Baier" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am fine with an extension method on Token - but it must return a string - not JwtPayload.

-

**Comment by leastprivilege** [comment]
don't worry - I will do it.

**Comment by omerlh** [comment]
OK, thanks!



On Wed, Mar 30, 2016 at 8:42 AM -0700, "Dominick Baier" <notifications@github.com<mailto:notifications@github.com>> wrote:


don't worry - I will do it.

-

**Comment by leastprivilege** [comment]
done on dev
