### ISSUE TITLE
Example of MVC Authentication Using AspNetIdentity 

### ISSUE THREAD

**Issue by cherylbearden** [IdentityServer/IdentityServer3#2728]
Can you give us an example like the MVC Authentication example using AspNetIdentity instead of OpenIdConnect authentication?

**Comment by leastprivilege** [comment]
Why would we do that?

**Comment by brockallen** [comment]
Since OpenIdConnect authentication is the entire purpose of this project the question is confusing.

**Comment by cherylbearden** [comment]
Sorry, I didn't realize that your project was focused mainly on OpenID connect since I saw other authentication examples out there, and the AspNetIdentity was one I was able to get to work, as well as the MVC Authentication one. 
I need to figure out a way to secure web api OData services and have been using DNN as a content management system, and securing web api services under DNN. You can run web api's under DNN, but not web api OData endpoints.  So I was looking into Identity Server.  DNN currently does not use either Asp.Net Identity or OpenIdConnect, however they may use Asp.Net Identity in the future.  
However you can also write authentication providers to use with DNN and I have written one for Shibboleth which we have been using successfully at UF for years.  So at UF we authenticate to DNN using Shibboleth. 
I am looking for a common authentication system that can be used for projects that run inside and outside of DNN. I also liked the single signon features of Identity Server.
Maybe this would work using OpenIDConnect with a DNN authentication provider for OpenID Connect.  Since I haven't taken your class yet, this is all new to me. 
Date: Mon, 21 Mar 2016 13:28:52 -0700

**Comment by brockallen** [comment]
Since OIDC extends OAuth2, you can also use IdSvr to protect your web apis. I'm not sure how DNN fits in -- I guess the question is can it stay out of the way for securing your API calls.

**Comment by cherylbearden** [comment]
I think this is the question that I meant to ask in the beginning, and I'm just learning about IdentityServer and Token Based Authentication, Owin, and Asp.Net Web API.  

In the Identity Server MVC Authentication & Authorization example, I would like to change the User data store to use an Asp.Net Identity data store rather than the InMemory data store.  Can you give me some guidance on how to do this?  So I'd still be using OpenID Connect, but hitting the Asp.Net Identity data store. Thanks.

**Comment by brockallen** [comment]
Yes, we have a sample here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity which uses this: https://github.com/IdentityServer/IdentityServer3.AspNetIdentity

Also, the docs contain these links: https://identityserver.github.io/Documentation/

**Comment by cherylbearden** [comment]
Thanks very much for the links.  I used them and was able to alter Startup.cs in the MVC Authentication example to use the AspNetIdentity store using the code below (just in case anyone else is interested):

  app.Map("/identity", idsrvApp =>
            {
                var factory = new IdentityServerServiceFactory()
                    .UseInMemoryClients(Clients.Get())
                    .UseInMemoryScopes(Scopes.Get());

                     factory.ConfigureUserService("AspId");

                var options = new IdentityServerOptions
                {
                    SiteName = "Embedded IdentityServer",
                    SigningCertificate = LoadCertificate(),

                    Factory = factory,

                    AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
                    {
                        IdentityProviders = ConfigureAdditionalIdentityProviders,
                    },                    

                    EventsOptions = new EventsOptions
                    {
                        RaiseSuccessEvents = true,
                        RaiseErrorEvents = true,
                        RaiseFailureEvents = true,
                        RaiseInformationEvents = true
                    }
                };

                idsrvApp.UseIdentityServer(options);
            });

I'm looking forward to your dev connections class and trying to get familiar with Identity Server before then!
