### ISSUE TITLE
ICustomTokenResponseGenerator not being called

### ISSUE THREAD

**Issue by dvaneven-tb** [IdentityServer/IdentityServer3#2729]
Hi,

I have following code:

```cs
var factory = new IdentityServerServiceFactory()
    .UseInMemoryUsers(Users.Get())
    .UseInMemoryClients(Clients.Get())
    .UseInMemoryScopes(Scopes.Get());

_userService = new UserService();
_customTokenResponseGenerator = new CustomTokenResponseGenerator();

factory.UserService = new Registration<IUserService>(resolver => _userService);
factory.CustomTokenResponseGenerator = new Registration<ICustomTokenResponseGenerator>(resolver => _customTokenResponseGenerator);
```

The callback in the `CustomTokenResponseGenerator` never gets called. No problem for the `UserService`.

My (implicit) flow is working perfectly, just want to add some extra data to the token response...

Am I missing something?

BTW: using external identity provider (but I'm having the same issue if I use the InMemory users)

**Comment by leastprivilege** [comment]
and are you making a request to the token endpoint??

Our core host has it wired up - you can see it working there.

**Comment by leastprivilege** [comment]
any progress?
