### ISSUE TITLE
User providing extra "claims"

### ISSUE THREAD

**Issue by svrooij** [IdentityServer/IdentityServer3#2730]
### Question
We want to user to provide / change a specific claim, as some sort of user preference. Where would we implement this. Could you point us in the right direction?
For example the users gets some claims from the identity provider. If the claim schedule-query is specified, we want to provide the user an optional page where he can change the value of this claim.
And if the claim is not specified by the idp we want to ask the user to provide this value or leave it empty. This value is completely optional, but if the user provides this he will get a better user experience.

We also want to provide a page in the identity server where a user/thirty party developer can see the claims the identity server has about him. And can provide to some application.

### Relevant parts of the log file
No log, yet :smile:

**Comment by leastprivilege** [comment]
IdSrv is authentication as a service. everything beyond that is just an "application" that you have to provide.
