### ISSUE TITLE
Trying to understand the redirect uri in wpfclient module.

### ISSUE THREAD

**Issue by lpranith** [IdentityServer/IdentityServer3#2731]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Currently i am trying to under stand the WPF client and i could see the the redirect uri as "oob://localhost/wpfclient" , i want to put a break point on the client side after the login is success on the server side but not sure where is this callback method  "localhost" (please correct me if this is not the callback method) and the wpfclient is the name of the module?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
