### ISSUE TITLE
[Question] Authenticating users with SSL Client Certificate

### ISSUE THREAD

**Issue by heraclesaraujo** [IdentityServer/IdentityServer3#2733]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

I need, as a requirement, to use a Personal Identity Certificate as credentials for the user, just like Membership Reboot allows me to relate an account to a certificate, and still allow the user to authenticate with his username and password.

My first thought is to use an extension, like windows authentication, with a custom endpoint, a custom view with a link to "login with certificate", and some web.config settings to make IIS to require a client certificate on that endpoint.

Any suggestion for a better approach? Or if there is anything that already gives me this functionality, where can I find any docs on it?

### Relevant parts of the log file

no logs... yet

**Comment by leastprivilege** [comment]
You can access client certificates from the OWIN context. If you want some custom UI around that - use a partial login. Check the samples.

**Comment by heraclesaraujo** [comment]
I need something that will bypass the username & password need if the user gives idsrv3 a certificate and I'd like to do this within idsrv3, the app can negotiate the certificate, but will still ask for a token for securing other APIs that do not use a client certificate or even are not under a HTTPS context.

Thanks Dominick, I will try something with partial login and will give you feedback as soon as I have something... This is not a priority for now, and may take about two weeks.

**Comment by leastprivilege** [comment]
You can check the cert in PreAuthenticateAsync - and sign the user in without showing a UI.
