### ISSUE TITLE
PrimaryAuthenticationType

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3#2734]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

What does this mean ? I think this uses idsrv cookie for authentication. 
           Constants.PrimaryAuthenticationType;

I think I understand this.if I am redirecting
            Constants.PartialSignInAuthenticationType;
 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by mderriey** [comment]
IdentityServer has 3 different authentication cookies as you can see [here](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AppBuilderExtensions/ConfigureCookieAuthenticationExtension.cs).

`PrimaryAuthenticationType` is associated with an authentication against the local user store, `ExternalAuthenticationType` defines an authentication against an external identity provider, like Google or Facebook.

Finally, `PartialSignInAuthenticationType` is used in case some logic requires, for example, to show the user a page before we consider them *fully authenticated*. The [documentation here](https://identityserver.github.io/Documentation/docsv2/advanced/userService.html) explains it.
