### ISSUE TITLE
Add custom form fields to FormPostResponse.html

### ISSUE THREAD

**Issue by viveksreedharan** [IdentityServer/IdentityServer3#2736]
Hello there - We have set up IdentityServer for an angular app and all works fine whilst accessed internally. The reverse proxy that we use for external access expects few hidden form fields for all POST requests. 

I have checked there are no options to add these fields directly. Are there any workarounds to add more fields to FormPostResponse.html? 

We are using CustomViewService and Hybrid Flow. Our reverse proxy does not allow url fragment, so we cant use fragment response_mode to avoid using form POST.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
