### ISSUE TITLE
Logout from android device / chrome extension

### ISSUE THREAD

**Issue by merijndejonge** [IdentityServer/IdentityServer3#2737]
Hi,
I'm using IdentityServer3 in combination with multiple login providers. Login works without any problem. Logging a user out leads to some troubles though. 

When I log out I'm not really logged out from e.g. google. This means that when I login again using IdentityServer3 I don't need to provide username/password to google.I believe this is a known issue and others have posted questions about this. Fortunately, I can always log out from google in my browser using google's web-site.

However, I'm also developing a chrome extension. The chrome extension does not get logged out when I log out from Google's web-site. I'm also developing an android app. Logging out also doesn't work here. For both systems, this effectively means that I'm unable to perform a real logout.

What is the proposed way to logout, such that during the next login the login provider will display a username/password entries? This is also needed in order to be able to switch user.

Thanks in advance for your help!

- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
