### ISSUE TITLE
Is is possible to skip the login page when the only option is a 3rd party?

### ISSUE THREAD

**Issue by shuppert** [IdentityServer/IdentityServer3#2738]
I have a scenario where a group of users will only have the ability to authenticate with a 3rd party login.  Is it possible to pass an additional parameter that would skip the login page and automatically redirect the user to the 3rd party login page and avoid having to press the button for the 3rd party?

-Scott

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
