### ISSUE TITLE
How do I send an Httprequest answer to a container using IdentityModel

### ISSUE THREAD

**Issue by cmfsantos** [IdentityServer/IdentityServer3#2739]
I have this code that is working perfectly:

    public string CallApi2(TokenResponse response)
    {
        String resp = "";
        var client = new HttpClient();
        client.SetBearerToken(response.AccessToken);
        resp=client.GetStringAsync("http://localhost:50158/test").Result;
        return resp;
    }
Now I need to put in this one working to fill the container:

var container = new Default.DataGolfeContext(new Uri(serviceUri));
That should be something like this, but it dons't work:

var container = client.GetStringAsync( new Default.DataGolfeContext(new Uri(serviceUri)));
Can somebody help me on this?

**Comment by mderriey** [comment]
To me, it looks like your `DataGolfeContext` class is a wrapper around the API you're trying to use. Under the hoods, I guess it just issues HTTP requests like your `HttpClient` does.

If your API is protected, maybe have a look if the `DataGolfeContext` class exposes a way for you to put the access token in the HTTP headers. If you tell us where this class comes from, we could have a look.

Cheers.

**Comment by cmfsantos** [comment]
Thanks mderriy i already find out how to solve the issue
