### ISSUE TITLE
SSO Question

### ISSUE THREAD

**Issue by aaronwjha** [IdentityServer/IdentityServer3#2740]
We are deploying IdentityServer as we move toward a goal of a single identity management system for multiple products that today each manage their own. All clients will use OAuth Resource Owner flow. We have a scenario where we'd like to support SSO between non-browser applications:

1. User launches app A, completes sign-in process and A is granted an identity token.
2. App A redirects to app B, passing along identity information about the signed in user

What is the proper method for app B to acquire a token without requiring an additional sign-in by the user? Does OAuth/IdSrv have a process to handle this or are we left to implement our own?

**Comment by brockallen** [comment]
The solution for SSO defined in OIDC and OAuth is to use the browser.

**Comment by aaronwjha** [comment]
The browser would certainly solve all of our problems, but unfortunately that is not possible. Anyone have any high-level suggestions on how to make this work in a secure manner?

**Comment by brockallen** [comment]
What's the requirement that mandates the use of resource owner password flow?

**Comment by aaronwjha** [comment]
We are moving to OIDC in a phased approach. Today all of our products manage their own user identities and login processes. Phase 1 is to move all identities to a single IdP and allow products to continue to own login credential collection. We do not plan on supporting any 3rd party IdPs. I think you may respond with the obvious question: 'Then why use OIDC?' We want to position ourselves in such a way that we are able to enable new products (web-based) to use auth code flow, but legacy products will likely never move away from resource owner flow.

**Comment by brockallen** [comment]
So as of now those apps don't have SSO across them, correct?

**Comment by aaronwjha** [comment]
That's correct.

**Comment by brockallen** [comment]
The OIDC spec leverages the browser for SSO. You need something shared across your two apps.

I still don't follow the reasoning from "we must use resource owner" to "we require SSO" and there's no browser in between. But I'll stop badgering you on the point.

**Comment by brockallen** [comment]
If you find some other protocol that supports this, feel free to share a link here.
