### ISSUE TITLE
External Provider callback is not HTTPS when AWS elastic load balancer terminates the HTTPS connection

### ISSUE THREAD

**Issue by jaydinslage** [IdentityServer/IdentityServer3#2741]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

We have the identity server hosted on AWS and use the elastic load balancer that is terminating the HTTPS there.  I have set the RequireSsl and PublicOrigin properties to act accordingly.  However, in the single case that we are using an external identity provider (in this case Kentor AuthServices), the "../identity/callback" URL is HTTP, not HTTPS.  As far as I can tell this is because of the following line:

            var authProp = new Microsoft.Owin.Security.AuthenticationProperties
            {
                RedirectUri = Url.Route(Constants.RouteNames.LoginExternalCallback, null)
            };

In the AuthenticationController.LoginExternal endpoint.  

Am I thinking correctly that this is an issue and if so, any suggestions on how to solve said issue?

**Comment by brockallen** [comment]
Yep, looks like a bug.

**Comment by brockallen** [comment]
BTW, in the meantime you can use the `SetIdentityServerOrigin` OWIN extension API to set the host explicitly in your own middleware prior to IdSvr in the pipeline:

https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by brockallen** [comment]
Ok, I just looked at this code -- it's not your problem I don't think. This creates the redirect path back to the page and it's relative and only used by the middleware after we've returned from the external provider, so the host name is not involved or needed.

As for your issue about the redirect URI being wrong to the external IdP... With all the Microsoft providers, IIRC, you need to set the full callback URL explicitly. So maybe this is a Kentor thing that they read the current host and use that?

**Comment by jaydinslage** [comment]
Thank you for the confirmation.  Always good to know I'm not crazy.

**Comment by jaydinslage** [comment]
I think I'm following what you are saying.  My conclusion that it was an Identity Server issue was the fact that the URL is generated and added to the authentication properties that are passed when the challenge to the external provider is called.  Kentor just echos the exact path.  I could see it being an issue in either place.  I guess my opinion would be that it would be safer if the identity server gave an explicit path, that way no issue can arise in this case. 

As far as a workaround, we've used URL rewriting to change only that URL to HTTP using an outbound rule.  We can do this because we know that we never want HTTP.

**Comment by AndersAbel** [comment]
I can confirm that this is a bug in the Kentor Middleware. See KentorIT/AuthServices#432.
