### ISSUE TITLE
After signout re-authentication not required

### ISSUE THREAD

**Issue by cdwaddell** [IdentityServer/IdentityServer3#2744]
- [X ] I read and understood how to enable [logging]

### Question / Issue

I may be missing something, but when I am using a 3rd party openid client to connect to my identityserver3 instance, I can sign out of openid then sign into a client without being challenged for a username and password. This issue doesn't happen with my own custom clients (but they use SLO).

Procedure to Recreate:
    1) Sign into a client application (in this case drupal) using our openid endpoint
    2) Sign out of the client app
    3) Sign out of openid using the logout endpoint 
    *4) optionally clear all cookies from the client app and from the openid app (session may have something in it on the client app, I am not familiar with the implementation)
    5) Click sign in using openid on the client app

What Happens:
This procedure allows me to sign in using openid without being asked to authenticate. I can see that the IsActiveAsync method is called, but the AuthenticateLocalAsync method is not.

Desired Behavior:
After signing out of open id, I would like future requests for sign in to require authentication. Do I need to do something during the SignOutAsync method to ensure that future attempts to sign in using openid will require authentication?

### Relevant parts of the log file
[SignoutLogs.txt](https://github.com/IdentityServer/IdentityServer3/files/188720/SignoutLogs.txt)

**Comment by leastprivilege** [comment]
Calling the end session endpoint clears the idsrv cookies. That's what the client initiating the logout needs to do.

**Comment by cdwaddell** [comment]
That confuses me, because in step 5 I can delete all browser cookies associated with my id server, without getting the desired behavior.

Anyway, since I do not have control over all of my client applications, is there a way that I can kill all sessions for a subject during the signoutasync?

**Comment by cdwaddell** [comment]
I discovered the cause of this issue. There was an alternate valid address to our webserver that was setup as the openid endpoint on this client. Thus the cookies were scoped to a different domain. I resolved this by disabling the alternate address in openid. Sorry to waste your time.
