### ISSUE TITLE
Connect Identity server V3 with Sharepoint 2016 - Single sign on

### ISSUE THREAD

**Issue by madhubaabu** [IdentityServer/IdentityServer3#2745]
### Question 
We have identity server V3 used inside my web application. We would like to use same identities to communicate with sharepoint 2016. Any repository or doc available on how to implement single sign on for sharepoint 2016 and Identity server V3 ?

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
