### ISSUE TITLE
IdentityServer3 integration with CAS (Central Authentication Service)

### ISSUE THREAD

**Issue by florindpreda** [IdentityServer/IdentityServer3#2751]
I'm trying to implement a Single Sign-On solution for two applications that currently use different identity providers:

- **Application A** - Custom app, written in C#.NET, have full control over it and currently uses Asp.NET Membership

- **Application B** - Off the shelf software written in Java (Pentaho), control limited to configuration only, and currently uses CAS (but also supports Integrated Windows Authentication). It acts as a CAS client and I have limited control to the CAS server.
My initial idea was to use IdentityServer3 (OpenID Connect and OAuth2) as the single sign-on solution.

**Application A** would be fairly simple to convert, but I couldn't find any solution for integrating **Application B** (CAS client) with IdentityServer3 (or any other OpenID Connect and OAuth2 implementation).

I understand they are different protocols but I would like to know if:

- This is possible and how would it be implemented at high level considering I only have full access to **Application A** and the **IdentityServer3**? What would be the effort required?

- What are the alternative solutions?

**Comment by leastprivilege** [comment]
IdSrv does not support CAS (whatever that is ;))

So maybe that's the wrong combination of tech.

**Comment by florindpreda** [comment]
Thanks for the reply. CAS is a single sign-on protocol (https://en.wikipedia.org/wiki/Central_Authentication_Service)

Generally speaking, how could I integrate IdSrv with another identity provider (which might use CAS or other protocol). Are there existing examples I could have a look at?

**Comment by leastprivilege** [comment]
You can federate idsrv with other authentication systems (aka use them as ext identity providers).

For that you need to write a Katana authentication middleware (like the Google middleware e.g.).

**Comment by florindpreda** [comment]
Will this require changes to the applications that use these other authentication systems? (e.g. adding the idsvr as trusted STS).

**Comment by leastprivilege** [comment]
yes. So if you can't change you app to use a different protocol (either OIDC, OAuth or WS-Fed) . you are out of luck.

**Comment by florindpreda** [comment]
Ok. So it seems that maybe the only sensible option in this case is to get **Application B** to use Windows Authentication instead of CAS and federate that with idsvr.

Just to confirm, is this the scenario covered in the following sample?
https://github.com/IdentityServer/WindowsAuthentication

Thanks.

**Comment by leastprivilege** [comment]
To talk to identityserver - the client applications needs support for either OpenID Connect, OAuth 2.0 or WS-Federation.

**Comment by florindpreda** [comment]
I understand. Makes sense. Thanks.
