### ISSUE TITLE
How to execute my custom middleware in idsrv3 in pipeline in the  specified pinelineSate?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2755]
I use asp.net mvc and idsrv3.  The idsrv3 was configured as below:
app.Map("/core", idsrvApp =>
            {
                    .....
                    idsrvApp.UseIdentityServer(disrvOptions);
            });
I have read the description of app.Map:
If the request path starts with the given pathMatch, execute the app configured via configuration parameter instead of continuing to the next component in the pipeline.

So I add " idsrvApp.UseMyMiddleware(); "  before "idsrvApp.UseIdentityServer(disrvOptions); ". My middleware executed, but the pipeline stage is Authenticate.

So how to execute my custom middleware in idsrv3 in the  specified pinelineSate?
Or are there any events like PreHandleRequest that I can override?
Thank you very much!

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by brockallen** [comment]
We set stage markers internally, so you can only run before or after us.

**Comment by Farwell-Liu** [comment]
How to run after idsrv3?  
If I add " idsrvApp.UseMyMiddleware(); " after "idsrvApp.UseIdentityServer(disrvOptions); ". My middleware did not execute. I think that is because of app.Map(...)
code:
app.Map("/core", idsrvApp =>
 {
 .....
 idsrvApp.UseIdentityServer(disrvOptions);
 idsrvApp.UseMyMiddleware(); 
 });

**Comment by brockallen** [comment]
run your MW prior, invoke next, then do post processing

**Comment by Farwell-Liu** [comment]
I have thought about your words again and gain, but I can't understand "then do post processing". Could you please express it in detail?
Thank you brockallen!

**Comment by brockallen** [comment]
```
app.Use(async (ctx, next)=>{
   await next();
   // your code here runs after idsvr
});
app.UseIdSvr(...);
```

**Comment by Farwell-Liu** [comment]
I got it, thank you!
