### ISSUE TITLE
Best practice for client credentials flow in service-to-service communication

### ISSUE THREAD

**Issue by benfoster** [IdentityServer/IdentityServer3#2758]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

We have an MVC web application that authenticates to IdSrv using Client Credentials flow, configured as so:

```
                new Client
                {
                    ClientName = "Fabrik Hosted Service",
                    ClientId = "hosted_service",
                    Flow = Flows.ClientCredentials,

                    ClientSecrets = new List<Secret>
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowedScopes = new List<string>
                    {
                        "api.read"
                    }
                }
```

It has read access to our API and we currently obtain a token like so:

```
        private async Task<TokenResponse> GetTokenAsync()
        {
            var client = new TokenClient(
                "http://localhost:49788/connect/token",
                "hosted_service",
                "secret");

            return await client.RequestClientCredentialsAsync("api.read");
        }
```

The issue is that the API access token is short-lived. I know I can increase it but I want to know what the best practice is here. Really I just want a never-expiring authentication token to the API.

### Relevant parts of the log file

NA

**Comment by leastprivilege** [comment]
For token living solely in the back-end - make them as long lived as you want. You can also wrap token requests nicely in an HTTP message handler.

**Comment by benfoster** [comment]
Long lived, but not permanent? Why would I wrap the requests?

**Comment by leastprivilege** [comment]
If you want to make the token-based authentication for server to server seamless, you can implement the token request process as an HTTP message handler. This way your business logic does not care at al about token lifetimes and the logic involved around it.

**Comment by benfoster** [comment]
I see, yeah that does work nicely. In that case, I may consider using this approach with refresh tokens. Are they supported with the client credentials flow?

**Comment by leastprivilege** [comment]
No. 

Why would you need a refresh token for that scenario?

**Comment by leastprivilege** [comment]
Your "refresh token" is the client secret.

**Comment by benfoster** [comment]
Okay, makes sense. So we can just check if the token has expired and re-request if necessary. 

Thanks for clarifying.

**Comment by leastprivilege** [comment]
You can even catch 401s inside the handler - request a new token and repeat the request.

**Comment by benfoster** [comment]
Final question, is ExpiresIn the expiry time in seconds from when the token was created?

So `DateTime.UtcNow.AddSeconds(token.ExpiresIn)` would give me the actual `DateTime`?

**Comment by leastprivilege** [comment]
yes
