### ISSUE TITLE
API Authentication for system where a user has multiple identities in the API applications

### ISSUE THREAD

**Issue by mikeholczer** [IdentityServer/IdentityServer3#2759]
We have a situation where we allow users to have a single login to our SaaS applications. These application are multi-tenanted and users that have access to multiple tenants still only have one login and chose which tenant (and therefore which identity) they want to be working on after authentication. We allow 3rd parties to use our OIDC system for authentication and we are looking into how to use resource scopes to allow these third parties to get an API key to our systems for the user.

As I hope I explained, the OpenID login of the user isn't specific enough to know which identity the API call should operate as. How you suggest that we solve this?

**Comment by leastprivilege** [comment]
In IdentityServer every user has exactly **one** identity - the value of the sub claim. Tenant association etc could be additional identity claims.

**Comment by mikeholczer** [comment]
So are you recommending that include the list of tenants a user has access to as a claim say called "Tenants" and then we would also have a resource claim say "SearchAPI? So clients can get a list of a tenants for the current user and know that they are allowed to access the SearchAPI. What about the case when user has access to the SearchAPI for one tenant but not another? Also, I think the API methods would have include a tenant parameter, so the caller can specify the tenant in search the call should operate.

Maybe I'm thinking about all this in a pre-OIDC state of mind, so I'd be grateful for any advice about how to setup a system in which the same physical human has access to different data and methods depending on a tenant context. Thanks.

**Comment by leastprivilege** [comment]
This is a general design/architectur question - not an issue with identityserver.

To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by mikeholczer** [comment]
For anyone interested I re-asked the question here: http://stackoverflow.com/questions/36361803/how-to-implement-oidc-delegated-web-api-access-in-a-multi-tenant-app
