### ISSUE TITLE
Using a Custom Flow for Authentication

### ISSUE THREAD

**Issue by phillsta** [IdentityServer/IdentityServer3#2760]
Hi guys,

I need help with a tricky problem and was wondering if I could a fresh perspective.

**Situation**
We have a client who has their own authentication platform which is a simple API call with a token in the Url string to retrieve user information. The issue is we need to be able to validate this token instead of a username/password.

**Required Flow**
1. Anonymous User attempts to access a secured UI with the custom token in the URL
2. User is redirected to the connect/authorize endpoint with a acr_value:idp and acr_value:token for the custom token
3. The identity server validates the custom token and redirects the user to the secured UI redirect_uri

I have been trying for days to figure out a way to bypass the login screen.

**Constraints**
Can only do GET call to connect/authorize endpoint as the Secured UI is a JavaScript app and can't store/pass through client_id and client_secret, and uses the OIDC javascript library redirect to login call.

**What I tried**
Implemented a custom AuthenticationHandler class and overridden the AuthenticateCoreAsync to get the user information using a custom grants flow.
I believe the problem lies in the ApplyResponseChallengeAsync function, I've overridden it but I'm stuck on what RedirectURL (and query string) to use to forward through to the idsvr to perform a token validation, that doesn't show a UI and essentially does a redirect back to the original redirect_uri of the secured UI.

The log entries before redirection are

- identity provider requested, redirecting to: "CustomProvider"
- External login requested for provider: "CustomProvider"
- Triggering challenge for external identity provider
- Start authorize request
- Start authorize request protocol validation
- "Authorize request validation success"
- User is not authenticated. Redirecting to login.
- End authorize request
- Redirecting to login page
- Login page requested

I've also created a custom grant validator to validate during a POST backend /connect/token call where a client id and secret can be passed through

``` 
 public class CustomGrantValidator : ICustomGrantValidator
    {
        public Task<CustomGrantValidationResult> ValidateAsync(ValidatedTokenRequest request)
        {
            // TODO: Authenticate the Custom Token
            return Task.FromResult(new CustomGrantValidationResult("1", "customGrant"));
        }

        public string GrantType => "custom_token";
    }
```

**Alt Solutions**
1 alternate solution I managed to get working was is to modify the method that authenticates a local account to validate the token and just update the idsvr UI to pass the token as the "password" and click the login button automatically if certain conditions are met.
This works but is a bit messy...

**Comment by leastprivilege** [comment]
I haven't read all of it - 

but you can bypass the login screen by handling PreAuthenticateAsync on the user service and set an AuthenticateResul.
