### ISSUE TITLE
Question: Set Login session to never expire implicit flow

### ISSUE THREAD

**Issue by raxitr** [IdentityServer/IdentityServer3#2761]
### Question 

1. I have couple of .net web clients configured with implicit flow, how do I set login session to never expire? 
2. On the session timeout login screen is displayed is it dependent on Id Token expiration?  
3. I have observed redirection is triggered to IdentityServer on Identity Token expiration and it renews session but recently it threw me to login screen, what could be the reason?

Thank you

**Comment by leastprivilege** [comment]
Every client control its own session lifetime. Make sure you set `UseTokenLifetime=false` on the MW middleware.

**Comment by raxitr** [comment]
If I set UseTokenLifetime to false then it will never redirect to the Identiyserver again to renew the session? 
I am also using access token returned from Identityserver how do I renew it upon expiration?

**Comment by leastprivilege** [comment]
If you need a new access token you need to make a roundtrip to the server somehow. You can't have both.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by raxitr** [comment]
Thank You

**Comment by raxitr** [comment]
Last question, How do I force redirection to Identitysever for Token & Session renewal?
