### ISSUE TITLE
Autofac  - System.ObjectDisposedException

### ISSUE THREAD

**Issue by rvanoord** [IdentityServer/IdentityServer3#2762]
We experience a problem with Autofac, similar to the one described in issue #2248, running Identity Server 3 on Azure.

Occasionally we get the error below. After this error occurs, services aren't instantiated and the identity server stops working completely (requires restart/redeployment).

 System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed. at Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed() at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag, Action1 configurationAction)
at Autofac.Core.Container.BeginLifetimeScope(Object tag, Action1 configurationAction) at Owin.OwinExtensions.<>c__DisplayClass0_0.<<UseAutofacMiddleware>b__0>d.MoveNext() in C:\...\ **IdentityServer\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 64**

**Comment by brockallen** [comment]
Sorry this issue slipped thru the cracks. Do you have any more info or have you done any more debugging? It's hard to tell form the little info we have.

**Comment by rvanoord** [comment]
After some more debugging it appeared that this error occurs when the
application is shutting down. I guess it's not so strange if objects are
getting disposed at that point.
