### ISSUE TITLE
Angular + Reauthenticating with refresh token

### ISSUE THREAD

**Issue by lexon0011** [IdentityServer/IdentityServer3#2764]
Hy guys,

I create a new SPA with angular and want to use the identity Server for authentication.

**What is still working:**
- The IdentityServer is up and running
- The angular app already redirects the user to the IdentityServer for entering the credentials
`window.location.href = "/connect/authorize?client_id=<ClientID>&redirect_uri=<RedirectUrl>&response_type=id_token token"&scope=openid`
- The IdentityServer redirects the user back to the angular app. The result was successfully send in the URL (id_token, access_token, expires_in, ...)

**What is still not working:**
- After the token is expired, I want to reauthenticate the user without enter the credential again 
- For this I want to check on each request, if the token is expired. If yes, I want to request the IdentiyServer for a new token. At the moment I use the Implicit flow, so I could not receive a refresh token. 
- I tried already the oidc-token-manager.js, but I get problems with the iframe (Refused to Display 'https://...' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.). 

**What is the question**
- Is it possible to use the Refresh Token in a SPA?
- If yes, which Flow is the correct on this scenario? 
- If yes, how looks the JavaScript call for requesting the refresh token and to refresh the Id token?

Thank you so much!

Regards

**Comment by brockallen** [comment]
> Is it possible to use the Refresh Token in a SPA?
no

> If yes, which Flow is the correct on this scenario? 

SPAs only use implicit

to manage token lifetime, one approach is the silent renew via the iframe. Here's a video that discusses some of this : https://vimeo.com/131636653, but maybe you've already seen it.

**Comment by lexon0011** [comment]
Thanks for your answer. I will try to get it running with the oidc token manager.

**Comment by lexon0011** [comment]
I have now implemented the oidc-token-manager into my angular 2 app. The silent renew process works  really good. I have only one problem: After about one day the silent renew process fails: `Error: login_required`

Is there an option (on server or client), where I could manage the period, where the silent renew works without further login?

Thanks!

**Comment by leastprivilege** [comment]
Silent renew works as long as the authentication session with idsrv is still valid. You can configure this in the CookieOptions in IdentityServer.

**Comment by lexon0011** [comment]
The property `ExpireTimeSpan `of `CookieOptions `sounds good. But I could not understand, how the idsrv knows, if a session is valid. There were no session informations persisted to the database.

**Comment by brockallen** [comment]
Cookies are used.

**Comment by jbkly** [comment]
@lexon0011 Any tips on how you solved your cross-origin issue with the silent renew iframe? I'm using `oidc-token-manager` and getting the same error trying to load the silent renewal in an iframe: 

```
Refused to display 'http://localhost:44333/connect/authorize?state=1241805873832687&nonce=12624…sponse_type=id_token%20token&scope=openid%20profile%20end-user&prompt=none' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

**Comment by lexon0011** [comment]
I decide to use the oidc-token-manager without an iframe. Instead of automatically renew I check the token when the route (URL) will changed. If the token is expired, I will redirect the user to the IdentityServer.

**Comment by brockallen** [comment]
You will only get that XFO error if the iframe is trying to show some UI. This means there's an error or the user is being asked to login or consent.

**Comment by robbaman** [comment]
Also note that if you use the silent refresh with a return url different than the regular post-login-url, you also need to add the silent refresh return url to the allowed redirect URI's in identityserver.

**Comment by jlouros** [comment]
> You will only get that XFO error if the iframe is trying to show some UI. This means there's an error or the user is being asked to login or consent.

Don't understand how this is possible. As soon as `iframe.src` is change, the browser will try to render any HTML in the page and fix the Response contains `X-Frame-Options: sameorigin` the iframe won't be rendered and the browser will report an error. Am I missing something here?

**Comment by brockallen** [comment]
> Don't understand how this is possible. As soon as iframe.src is changed, the browser will try to render the returned HTML in the iframe and since Response contains X-Frame-Options: sameorigin the iframe won't be rendered and the browser will report an error.

Well, test out your theory.

**Comment by jlouros** [comment]
![image](https://user-images.githubusercontent.com/587250/33179111-44714f7c-d060-11e7-9f82-8f1a627f4a69.png)

iframe.src = `http://localhost:44333/core/connect/authorize?redirect_uri=http://192.168.99.100:10133/silent.html&id_token_hint=...&prompt=none` (192.168.99.100 is assigned to a local Docker container)

Identity Server response headers:

```HTTP/1.1 200 OK
Cache-Control: no-store, no-cache, max-age=0, private
Pragma: no-cache
Content-Length: 1606
Content-Type: text/html; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
X-IoRequestId: e8fdb498-7d11-4a81-96bf-46d82b62b97c
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Date: Thu, 23 Nov 2017 14:33:31 GMT
```

silent.html file contents (although it's relevant because the browser blocks the iframe request):

``` HTML
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body>silent token refresh</body>
</html>
```

**Comment by brockallen** [comment]
but that's not what IdentityServer would return

**Comment by jlouros** [comment]
If I'm not wrong, by default XFO is enabled https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/Hosting/SecurityHeadersAttribute.cs#L54

Plus, the fact that my SPA doesn't specify `X-Frame-Options` it's irrelevant, since Identity Server is telling the browser that it can't be rendered in a iframe. 

Even though Identity Server will return 302 Redirect to `http://192.168.99.100:10133/silent.html` (my slient.html page), the request completely discarded by the browser because of specified XFO setting.

**Comment by brockallen** [comment]
Well, I'm lost on the context at this point... but test our samples. Those work, right?

**Comment by jlouros** [comment]
using https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/JavaScript%20Walkthrough  out-of-the-box that is works since API, IdentityServer and JSApp are all hosted at localhost:* 

Now the real problem is when you host JSApp in a different domain (non-localhost). It fails due to XFO rules set in IdentityServer.

**Comment by jlouros** [comment]
Yep, my bad. Trying to run tests on environments that I don't have access to IdentityServer configuration. Just missing the appropriate redirect Uris. 

> Also note that if you use the silent refresh with a return url different than the regular post-login-url, you also need to add the silent refresh return url to the allowed redirect URI's in identityserver. Otherwise you'll also get the XFO error

Sorry for the confusion.
