### ISSUE TITLE
How to Get Additional from Login Screen

### ISSUE THREAD

**Issue by Sriram143** [IdentityServer/IdentityServer3#2765]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi I Customized the Login View and I Added Some Checkbox on the login and now i want to ge this value on Customized USerService? how to get that value 

Or How to Set acr_values from The Customized Login view (from html itself)? 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This has been asked before -- check the issue tracker history. Search for injecting the OwinEnvironmentService into your user service.
