### ISSUE TITLE
RegisterConfigurationServices, RegisterOperationalServices Extentions Improvements

### ISSUE THREAD

**Issue by BruceHunter** [IdentityServer/IdentityServer3#2767]
### Issue / Feature

These extensions to do not have a way to pass in IClientConfigurationDbContext, IScopeConfigurationDbContext or IOperationalDbContext.
```
idSvrFactory.RegisterConfigurationServices(efConfig);
idSvrFactory.RegisterOperationalServices(efConfig);
```

If you wanted to turn off EF Migrations for example. You would create your own ConfigurationDbContext classes and pass them in like this.

```
idSvrFactory.Register(new Registration<IClientConfigurationDbContext>(resolver => new ClientConfigurationDbContext()));
idSvrFactory.ClientStore = new Registration<IClientStore, ClientStore>();
idSvrFactory.CorsPolicyService = new ClientConfigurationCorsPolicyRegistration(efConfig);

idSvrFactory.Register(new Registration<IScopeConfigurationDbContext>(resolver => new ScopeConfigurationDbContext()));
idSvrFactory.ScopeStore = new Registration<IScopeStore, ScopeStore>();

idSvrFactory.Register(new Registration<IOperationalDbContext>(resolver => new OperationalDbContext()));
idSvrFactory.AuthorizationCodeStore = new Registration<IAuthorizationCodeStore, AuthorizationCodeStore>();
idSvrFactory.TokenHandleStore = new Registration<ITokenHandleStore, TokenHandleStore>();
idSvrFactory.ConsentStore = new Registration<IConsentStore, ConsentStore>();
idSvrFactory.RefreshTokenStore = new Registration<IRefreshTokenStore, RefreshTokenStore>();  
```

**Comment by BruceHunter** [comment]
You would also have to create your own TokenCleanup class and return 

```
        public override IdentityServer3.EntityFramework.IOperationalDbContext CreateOperationalDbContext()
        {
            return new OperationalDbContext();
        }
```

**Comment by BruceHunter** [comment]
I can do a PR for this if you agree.

**Comment by brockallen** [comment]
I've not had time to really read this, so please hold off on any work for now please. I'd not want you to waste any time.

**Comment by brockallen** [comment]
Also, these extension methods are really from the EF project, so this is really the wrong repo.

**Comment by BruceHunter** [comment]
That's my bad putting it here.

**Comment by brockallen** [comment]
Well, IMO, the current extension methods are just saving you the few lines of code to configure the interfaces for the EF provided implementation. If you need your own, perhaps it makes more sense to just do your own extension methods for your implementation.
