### ISSUE TITLE
Secure Web API For Non Registered User

### ISSUE THREAD

**Issue by RizwanSharp** [IdentityServer/IdentityServer3#2769]
Hi There,

Thanks for a great product! We have been using Identity Server 3 with Resource Owner Credentials flow to control access to the APIs which need to determine the user's identity. We also have other APIs which we want to secure as well but without requiring users to sign up, getting token before they use the APIs. Both types of APIs are being used by the same client application (native mobile).

Thanks for any suggestions/answers in advance...

**Comment by mderriey** [comment]
Do you need any information about the user in this is there API? If not, then Client Credentials might be for you. You'll get a token that identifies the application and not the user.
