### ISSUE TITLE
Get "access_token" in Implicit Flow

### ISSUE THREAD

**Issue by abelondev** [IdentityServer/IdentityServer3#2771]
### Question / Issue

I use Implicit Flow to connect MVC Asp.net app to IdentityServer. I want implement creating users from those MVC app but I have only "id_token", but I understand I need "access_token" to access to new custom API in Identity Server.
 "access_token" is not transferred in Implicit Flow. The client doesn't keep password as well.

I use MONO and I have limitation that app.UseOpenIdConnectAuthentication( doesn't work at all.

Can I use "id_token" to get "access_token" or can I use "id_token" instead "access_token"

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
>  "access_token" is not transferred in Implicit Flow. 

Not true. Change the `response_type` to `"id_token token"`.

**Comment by abelondev** [comment]
It's true. Thanks!
