### ISSUE TITLE
Web Api Controller returns response with 401 status after successful 'Authorize request validation'

### ISSUE THREAD

**Issue by jorgecavaleiro** [IdentityServer/IdentityServer3#2772]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi,

I've setup the identity server inside the same host side by side with the web api controllers. 
Apparently all runs well in terms of the request validation, but the web api controller decorated with an [Authorize] attribute, isn't called and the server returns a 401.
When I remove the [Authorize] attribute and debug the controller method I realize that the 'HttpContext.Current' is null.

I've bee stuck with this for 2 days, so I'll really be thankful for some help. 

Here is a part of the startup.cs:

Log.Logger = new LoggerConfiguration().MinimumLevel.Debug().WriteTo.Trace().CreateLogger();

// turn off any default mapping on the JWT handler
JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                ValidationMode = ValidationMode.Local,
                IssuerName = IdentityConstants.IssuerName,
                SigningCertificate = CertificateLoader.Load(),
                RequiredScopes = new[] { "application" },
                ClientId = "implicitclient",
                ClientSecret = "MySecret".Sha256()                
            });

and the web api controller:
[Authorize]
[Route("")]
public HttpResponseMessage Get(int pageIndex = 0, int pageSize = 10, string searchTerm = null)
{
    string clientAddress = HttpContext.Current.Request.UserHostName;

### Relevant parts of the log file

iisexpress.exe Information: 0 : 2016-04-02 22:05:30.664 +01:00 [Information] Creating Implicit Flow response.
2016-04-02 22:05:30.665 +01:00 [Debug] Creating access token
2016-04-02 22:05:30.665 +01:00 [Debug] Creating JWT access token
2016-04-02 22:05:30.676 +01:00 [Debug] Adding client "implicitclient" to client list cookie for subject "admin"
iisexpress.exe Information: 0 : 2016-04-02 22:05:30.676 +01:00 [Information] End authorize request
iisexpress.exe Information: 0 : 2016-04-02 22:05:30.676 +01:00 [Information] Redirecting to: http://localhost:8284/login
iisexpress.exe Information: 0 : 2016-04-02 22:05:31.460 +01:00 [Information] Start authorize request
iisexpress.exe Information: 0 : 2016-04-02 22:05:31.460 +01:00 [Information] Start authorize request protocol validation
iisexpress.exe Information: 0 : 2016-04-02 22:05:31.461 +01:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"implicitclient\",
  \"ClientName\": \"Implicit Client\",
  \"RedirectUri\": \"http://localhost:8284/login\",
  \"AllowedRedirectUris\": [
    \"http://localhost:8284/login\"
  ],
  \"SubjectId\": \"admin\",
  \"ResponseType\": \"token\",
  \"ResponseMode\": \"fragment\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"application\",
  \"State\": \"14596311314500.13904152429074168\",
  \"SessionId\": \"283015b458f842dbd85f19103d3afa7c\",
  \"Raw\": {
    \"client_id\": \"implicitclient\",
    \"redirect_uri\": \"http://localhost:8284/login\",
    \"response_type\": \"token\",
    \"scope\": \"application\",
    \"state\": \"14596311314500.13904152429074168\"
  }
}"

**Comment by jorgecavaleiro** [comment]
Digging a little bit more, I found thar in the "ScopeRequirementMiddleware" this:
context.Authentication.AuthenticateAsync(_options.AuthenticationType) 
is returning Null

**Comment by brockallen** [comment]
Are you setting `"application"` as the required scope in the access token validation middleware?

**Comment by jorgecavaleiro** [comment]
I believe so (my knowledge is probably still basic)... In the 'UseIdentityServerBearerTokenAuthentication', I'm specifying the 'RequiredScopes = new[] { "application" },'
and that is the scope declared in the InMemory scopes:

new Scope
                {
                    Name = "application",
                    DisplayName = "Api Access",
                    Enabled = true,
                    Description = "REST Api for known applications",
                    Type = ScopeType.Resource,

                    IncludeAllClaimsForUser = true,
                    Claims = new List<ScopeClaim>
                    {
                        new ScopeClaim(Constants.ClaimTypes.Name),
                        new ScopeClaim(Constants.ClaimTypes.Id),
                        new ScopeClaim(Constants.ClaimTypes.Subject)
                    }
                }

**Comment by jorgecavaleiro** [comment]
We decided for a different approach.
For our development environments were going to launch a console application with the identity server self-hosted.
We think that will probably less tricky than hosting it side by side with our web application.

Thank you.
I'm going to close this.

**Comment by jorgecavaleiro** [comment]
Just to register some lessons learned that could be useful to others.
If after successful authentication against the authority endpoint, the user is not assigned or a  web api request immediately returns a 401, the reason could be one of the following:
1.	The scope used isn’t well configured. For instance it lacks the assignment of the claims to be included in the token. To test this the ‘IncludeAllClaimsForUser = true’, should be enough. 
2.	The middleware that validates or relies in the authority endpoint to validate the token isn’t being reached. 
One possible reason is the order of the middleware registrations in the owin startup class. The ‘UseIdentityServerBearerTokenAuthentication’ must be called before the web api controller routes configuration. This seems obvious but my problem was that I used dependency injection to resolve the several middleware from several modules.

**Comment by kriscoleman** [comment]
@jorgecavaleiro 

Thank you so much for coming back to include what you found!! I was getting 401 too until I moved my call to UseIdentityServerBearerTokenAuthentication() to the top of my Startup.cs. Thanks!!
