### ISSUE TITLE
Issue with URL Rewite 2.0 Module

### ISSUE THREAD

**Issue by avmp2208** [IdentityServer/IdentityServer3#2776]
Hi guys, I hope your're doing well.

My issue is, I have two application one of them is Identityserver which is selft hosted, and the other one is a basic application on MVC installed on IIS 8.5 and this one use URL ReWrite,

So, first I installed my identityserver and everything was to be Ok, I could log in and manage my service successfylly, but when I installed the URL Rewrite Module for my second application the identityserver gave this error

> Bad Request - Invalid Verb
> 
> HTTP Error 400. The request verb is invalid.

After that I unistalled the Url rewrite module to ensure about that and my identityserver start to operate normally.

So my question is, How to configure my self hosted IdentityServer to work along with Url Rewrite Module?

Sorry for my english.

Best regards!.

**Comment by leastprivilege** [comment]
This does not seem to be an idsrv specifc issue - 

To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
