### ISSUE TITLE
Following Tutorial...Infinite Loop..Can't Seem to identify?

### ISSUE THREAD

**Issue by ramjet69** [IdentityServer/IdentityServer3#2777]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Following MVC Getting Started Tutorial I have an infinite loop.

https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html

Forgot to add per another issue on this board I added:

CookieSecure = CookieSecureOption.Never

This made the loop stop but I shouldn't really have to go with unsecure cookies even in a tut...and if so doesn't the tut need to be corrected then with the additional information?

Going from http (default mvc start page) to https (when clicking about and redirecting to identitysertver)

### Relevant parts of the log file

```
Log, fiddler saz and source files here:
https://drive.google.com/file/d/0B8j6nOIMJE96VnpsZFFxRWtaWFk/view?usp=sharing


```

**Comment by brockallen** [comment]
The cookie secure should be marked secure, and so that fixing your problem tells me that you have it all configured for HTTPS, but your initial request to the app is over HTTP.

**Comment by ramjet69** [comment]
Thank you for taking the time to help me work through my lack of understanding.

My initial call is http and I believe that to be a common scenario...should I instead be taking someone from http to https then to https IdentityServer....like this:

http://www.abc.com
User Clicks Login

https://www.abc.com
(hidden momentary redirect)

https://www.abc.com/login
Login with IdentityServer

If this doesn't make sense it goes to show how new I am to understanding this stuff.

**Comment by brockallen** [comment]
It's just a guess, but I suspect you're getting your local cookie issued over HTTPS, but then the user is redirected back to the app over HTTP (where there's no cookie), and that start the entire process over. What you should do is if the request is HTTP, then redirect back to your own app to HTTPS. Do that earlier in the pipeline than anything else.

**Comment by ramjet69** [comment]
I'm sorry..this is interesting to me. So based upon what you said I fired up Fiddler and captured the login process. Following in Fiddler I was able to grasp what you were saying.

Sure enough I redirect to https sooner and viola.

Thank You for your patience with me.
