### ISSUE TITLE
CustomUser Service in Load Balanced Environment 

### ISSUE THREAD

**Issue by pushpindersingh** [IdentityServer/IdentityServer3#2779]
### Question / Issue
Implemented UserServiceBase

Is there any recommendations on how to setup CustomUser Service, in load balanced servers 
Claims are missing in requests from another server, They are good if we run with one server, in multiple servers  all roles - claims are disappearing. 

public class CustomUser
        {
            public string Subject { get; set; }
            public string Username { get; set; }
            public string Password { get; set; }
            public List<Claim> Claims { get; set; }
        }

        public static List<CustomUser> Users = new List<CustomUser>();

        public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
       {
              logic for fetching user details from database
       }
  
      public override Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var user = Users.SingleOrDefault(x => x.Subject == context.Subject.GetSubjectId());
            if (user != null)
            {
                context.IssuedClaims = user.Claims.Where(x =>                  context.RequestedClaimTypes.Contains(x.Type));
            }
            return Task.FromResult(0);
        }

**Comment by brockallen** [comment]
Putting `"Urgent"` in your subject line is not going to get a response sooner -- please don't do that.

**Comment by brockallen** [comment]
Here are the docs to deployment: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

If what we cover in there aren't helping you, then your problem is in something you've done in your code.

**Comment by pushpindersingh** [comment]
Brockallen - i gone through that page

Do we have some sample of implementation, do i need to use any distributed cache here for storing CustomUser List 

public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
   {
          logic for fetching user details from database 


                    CustomUser obj = new CustomUser
                    {

                        Username = userDB.Username,
                        Password = userDB.Password,
                        Subject = userDB.ID.ToString(),
                        Claims = userClaims

                    };
                    //
                    Users.Add(obj);
                    context.AuthenticateResult = new AuthenticateResult(obj.Subject, obj.Username);

   }

**Comment by BruceHunter** [comment]
Most likely your issue is the following: If you are running in IIS, you need to synchronize machine keys.

**Comment by pushpindersingh** [comment]
Recheck the logs and all the setting, SSL required was set false, User GetProfileDataAsync updated to address any missing data. back in business...
