### ISSUE TITLE
PostAuthenticateAsync redirect to custom error page

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2780]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Hello,
I add custom logic in my custom  `UserService->PostAuthenticateAsync` method and i create custom error message in `AuthenticateResult`. I want to show this error on custom page and the user logged-in to be rejected (clear partial login).
How i can do this, using injected `OwinContext` or is other way?

**Comment by totpero** [comment]
Any help?

**Comment by brockallen** [comment]
You can always issue a partial login from PostAuth and in that partial login page clear the partial login with the OWIN extensions.

**Comment by totpero** [comment]
In my `PostAuthenticateAsync `i try to rediret to custom page but don't works:
```
public override async Task PostAuthenticateAsync(PostAuthenticationContext context)
        {
            _owinContext.Response.Redirect("/myerror");
....
```
Can you provide me one example or where to search?

**Comment by brockallen** [comment]
Use the AuthenticateResult: https://identityserver.github.io/Documentation/docsv2/advanced/userService.html#authenticateresult
