### ISSUE TITLE
Multiple accounts Login from the same browser different tabs SSO?

### ISSUE THREAD

**Issue by dgs-hassaan786** [IdentityServer/IdentityServer3#2781]
### Question / Issue
Hi, i have been running throw an issue related logged in. I am using mvc formpost approach
I opened 2 tabs side by side and go to login page.
I have 2 different username and password. On both tabs i have typed the different credentials and then simultaneously press the login. Both user are now logged. but the owincookie issued at client side are overridden.
My question is how can i provide handling like hotmail as you login from 2 different tabs its provide the option:

`You're already signed in. Remain signed in with this account. or Sign out and sign in with a different account.`

**Comment by leastprivilege** [comment]
We (nor the standard MS MW) support multiple simultaneous logins.
