### ISSUE TITLE
Can't Find Documentation on UserServiceBase

### ISSUE THREAD

**Issue by cxc256** [IdentityServer/IdentityServer3#2782]
I saw in some samples the user of UserServiceBase. However, I can't find mention of that in the documentation: http://identityserver.github.io/Documentation/docsv2/

Where would I find this?

**Comment by leastprivilege** [comment]
Not sure there are docs on it. It's a base class that implements the interface with no-ops. Simply derive from it.

**Comment by cxc256** [comment]
I just looked at the code for UserServiceBase. I now understand why there is no documentation ;-). Sorry for the stupid question.
