### ISSUE TITLE
Refresh claims in an already authenticated user

### ISSUE THREAD

**Issue by chrtsam** [IdentityServer/IdentityServer3#2783]
Hey,

I am using the hybrid flow in the identity server. After the user is already logged in I want to change or add claims to the access token based on user choises. I don't want to force the user to sign out and sign in again.

I have tried to do this by using `Authentication.SignIn` and adding the new claims, but I found out that the claims get changed only on the client side and not on the identity server.
How could I change the claims on the identity server?
Is this the right way to do it?

**Comment by leastprivilege** [comment]
Only the token service (identityserver) can create access tokens - after that they are sealed.

**Comment by chrtsam** [comment]
Ok thank you,
So what is the right way to update/add claims to the access token?
Is this possible via the refresh token mechanism? if so, how?

**Comment by brockallen** [comment]
Yes, refresh tokens (since you're already doing hybrid). Check the docs, samples, and the OAuth2 rfc for more info.

**Comment by chrtsam** [comment]
I have already implemented the refresh token mechanism.
Here is a sample code where the refresh is being done.

`var tokenClient = getClient();
                var refreshToken = id.FindFirst(OAuth2Constants.RefreshToken).Value;
                if (!string.IsNullOrEmpty(refreshToken)){
                    var tokenEndpointResponse = await tokenClient.RequestRefreshTokenAsync(refreshToken);
                    if (!tokenEndpointResponse.IsError){
                        var result = from claim in id.Claims
                                     where claim.Type != OAuth2Constants.AccessToken && claim.Type != OAuth2Constants.RefreshToken && claim.Type != "expires_at" && claim.Type != "period"
                                     select claim;
                        var claims = result.ToList();
                        claims.Add(new Claim(OAuth2Constants.AccessToken, tokenEndpointResponse.AccessToken));
                        claims.Add(new Claim(OAuth2Constants.RefreshToken, tokenEndpointResponse.RefreshToken));
claims.Add(new Claim("period", "periodCode"));
                        var expiresTicks = DateTime.UtcNow.AddSeconds(tokenEndpointResponse.ExpiresIn).Ticks;
                        claims.Add(new Claim("expires_at", expiresTicks.ToString()));
                        var newIdentity = new ClaimsIdentity(claims, id.AuthenticationType);
                        var wrapper = new HttpRequestWrapper(context.Request);
                        wrapper.GetOwinContext().Authentication.SignOut(id.AuthenticationType);
                        wrapper.GetOwinContext().Authentication.SignIn(new Microsoft.Owin.Security.AuthenticationProperties { IsPersistent = true }, newIdentity);
                        return newIdentity;
                    }
                    else { }
                }`

In the sample above I am trying to add a new claim named "period" but from what I see it does not get added to the accessToken? Im i missing something?

**Comment by chrtsam** [comment]
I have already implemented the refresh token mechanism.
Here is a sample code where the refresh is being done.

`var tokenClient = getClient();
var refreshToken = id.FindFirst(OAuth2Constants.RefreshToken).Value;
if (!string.IsNullOrEmpty(refreshToken)){
	var tokenEndpointResponse = await tokenClient.RequestRefreshTokenAsync(refreshToken);
	if (!tokenEndpointResponse.IsError){
		var result = from claim in id.Claims
					 where claim.Type != OAuth2Constants.AccessToken && claim.Type != OAuth2Constants.RefreshToken && claim.Type != "expires_at" && claim.Type != "period"
					 select claim;
		var claims = result.ToList();
		claims.Add(new Claim(OAuth2Constants.AccessToken, tokenEndpointResponse.AccessToken));
		claims.Add(new Claim(OAuth2Constants.RefreshToken, tokenEndpointResponse.RefreshToken));
		claims.Add(new Claim("period", "00"));
		var expiresTicks = DateTime.UtcNow.AddSeconds(tokenEndpointResponse.ExpiresIn).Ticks;
		claims.Add(new Claim("expires_at", expiresTicks.ToString()));
		var newIdentity = new ClaimsIdentity(claims, id.AuthenticationType);
		var wrapper = new HttpRequestWrapper(context.Request);
		wrapper.GetOwinContext().Authentication.SignOut(id.AuthenticationType);
		wrapper.GetOwinContext().Authentication.SignIn(new Microsoft.Owin.Security.AuthenticationProperties { IsPersistent = true }, newIdentity);
		return newIdentity;
	}else{}
}`

In the sample above I am trying to add a new claim named "period" but from what I see it does not get added to the accessToken? Im i missing something?


Sorry for the code. I wasn't able to wrap it correctly

**Comment by brockallen** [comment]
> var wrapper = new HttpRequestWrapper(context.Request);

I don't know what this line is trying to do. Why not use `Request.GetOwinContext()...`?

**Comment by chrtsam** [comment]
Because this code is not called inside a controller i am passing the `HttpContext context` as a parameter in my method and from there i am taking the `Request`.

I was searching the docs about how to update claims in the accessToken and i wasn't able to find something specific. Is there any link or example you can point me to?

**Comment by brockallen** [comment]
If you're looking to change the claims in the cookie, what you have seems to be on the right track. If you want to change the claims in the access token, Dominick already told you that they're sealed.

**Comment by chrtsam** [comment]
Ok, so in my understading, the only way to update the claims on the access token is to force the user to sign in again?

**Comment by leastprivilege** [comment]
Claims describe the identity of the user (e.g. the user id) - does that identity change during usage of the application?

Why does the changed data need to be in the access token?

And to answer your question - to get an updated token you need to make a roundtrip to the authorize/token endpoint - yes (which does not necessarily mean the user needs to sign-in again)

**Comment by chrtsam** [comment]
Hmmmm ok. The way we implement it the user has some information such as, in which company he signs into, and that is part of his identity. But while inside the application he can change that, e.g. he has multiple companies. 

Ok thank you! i will try to look into what you suggested

**Comment by daveclarke** [comment]
@chrtsam did you resolve this issue? We're in the same situation where a user can create a new `vendor` and they then become the `owner` of that `vendor`. That information is stored as a claim and we would obviously like to associate the claim with the user without having to sign-in again.

**Comment by Napkin41** [comment]
@chrtsam @daveclarke Also interested in the outcome of this effort. Our original access token has claims within it that our Web API will use. Refreshing the access token does not include these claims. Not sure if we're just flat-out using refresh tokens in a way that is not intended, or if I'm missing something.

**Comment by Napkin41** [comment]
@chrtsam @daveclarke Also interested in the outcome of this effort. Our original access token has claims within it that our Web API uses. The refresh token lacks these claims, and so I'm not sure if we're just flat out using refresh tokens in a way that is not intended.

**Comment by AliShd** [comment]
@brockallen @chrtsam @daveclarke @Napkin41 Hi, I am also looking for the same but no luck yet. I have a company_id in the claims which can be changed and upon change I want to get a new token with updated claims, without have to sign-in again.
