### ISSUE TITLE
Long Lived Refresh Token in Resouce Owner Flow not working as expected

### ISSUE THREAD

**Issue by mbarua17** [IdentityServer/IdentityServer3#2786]
### Question / Issue
I am using a native mobile as client and using Resource Owner Password flow. As part of login, I am getting the access token along with reference_token. Any subsequent calls, I am checking the expires_in attribute and based on which I reuse the existing token(if it is active which is cached in local storage) otherwise call the token end point with grant_type :refresh_token to get new token. This works for 1-2 hours but throws "invalid_grant" error beyond couple hours. 
### Error
400 Bad Request(Invalid grant_type)

### Relevant parts of the log file
16:56:14 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log AuthorizationCodeStore not configured - falling back to InMemory
16:56:14 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log TokenHandleStore not configured - falling back to InMemory
16:56:14 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log ConsentStore not configured - falling back to InMemory
16:56:14 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log RefreshTokenStore not configured - falling back to InMemory
16:56:14 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log CORS request made for path: "/connect/token" from origin: "http://localhost:8100"
16:56:14 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log AllowAll true, so origin: "http://localhost:8100" is allowed
16:56:14 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log CorsPolicyService allowed origin
16:56:14 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log CORS request made for path: "/connect/token" from origin: "http://localhost:8100"
16:56:14 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log AllowAll true, so origin: "http://localhost:8100" is allowed
16:56:14 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log CorsPolicyService allowed origin
16:56:15 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Start token request
16:56:15 [Debug] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Start client validation
16:56:15 [Debug] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Start parsing for X.509 certificate
16:56:15 [Debug] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log client_id is not found in post body
16:56:15 [Debug] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Start parsing for secret in post body
16:56:15 [Debug] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log No secret in post body found
16:56:15 [Debug] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Start parsing Basic Authentication secret
16:56:15 [Debug] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Parser found secret: "BasicAuthenticationSecretParser"
16:56:15 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Secret id found: "trcMobile"
16:56:15 [Debug] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Secret validator success: "HashedSharedSecretValidator"
16:56:15 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Client validation success
16:56:15 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Start token request validation
16:56:15 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Start validation of refresh token request
16:56:15 [Warning] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Refresh token is invalid
 {
  "ClientId": "trcMobile",
  "ClientName": "trcMobile",
  "GrantType": "refresh_token",
  "RefreshToken": "6719a4f3320ee6fc1a3b91733a888794",
  "Raw": {
    "grant_type": "refresh_token",
    "refresh_token": "6719a4f3320ee6fc1a3b91733a888794"
  }
}
16:56:15 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log End token request
16:56:15 [Information] IdentityServer3.Core.Logging.LogProviders.SerilogLogProvider+SerilogLogger:Log Returning error: invalid_grant
```
Client configuration(Overwritten the AbsoluteRefreshTokenLifeTime, this is in memory)
 new Client
                {
                    ClientName = appClient.Name,
                    ClientId = appClient.Key,
                    Enabled = true,
                    RequireConsent = false,
                    Flow = appClient.Flow,
                    RefreshTokenUsage = TokenUsage.ReUse,
                    AbsoluteRefreshTokenLifetime = (3600 * 24 * 365),
                    SlidingRefreshTokenLifetime = (3600 * 24 * 365),
                    RefreshTokenExpiration = TokenExpiration.Sliding,
                }
Can you please clarify where I am going wrong to get a new token for the refresh token reference. Also I would like to validate my solution with the experts if this approach(Resource Owner with Refresh Token flow) is correct in the mobile app scenario as I want the users to enter credential just one time and rest of the flow is driven of refresh tokens.

**Comment by sgude** [comment]
Not sure about the reference token not working.

About the second part of your question:
There is a discussion on what to use in this issue: https://github.com/IdentityServer/IdentityServer3/issues/1908 
Also check out the vimeo link in there.

**Comment by brockallen** [comment]
Are you configuring persistent stores in the IdSvr factory as suggested in the docs?
