### ISSUE TITLE
How to check sign in status?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2787]
I use idsrv3 in iis for SSO. There is a application that not force user to sing in. But if the user signed in idsrv3, I want to display current user name in this application.
What is the best practice in this scenario?

**Comment by brockallen** [comment]
You can make an authorization request using prompt=none to get an answer back if the user is already logged in.

**Comment by Farwell-Liu** [comment]
Thank you!
