### ISSUE TITLE
Native Android App - Is OpenID Possible without browser?

### ISSUE THREAD

**Issue by neilhosey** [IdentityServer/IdentityServer3#2790]
Hi,

I am building an android application and am finding that the OpenID Connect website doesnt actually mention much about how to implement it for native mobile apps.

I dont want to be reliable on opening up a webview, or opening a browser, so im wondering is there any way to use OICD for android while still being able to design the login screen locally?

I want to have both an identity token and an access token returned, like in the implicit flow, but cant use the redirect through browser, as this degrades the UX too much!

I am looking at using resource owner flow, but can i get an identity token while using this?  If i can, then this should be enough for me, but i dont think thats what the userinfo flow returns.

Thanks
Neil

**Comment by leastprivilege** [comment]
Check the spec here.

https://tools.ietf.org/html/draft-wdenniss-oauth-native-apps-02

—
cheers
Dominick Baier

**Comment by leastprivilege** [comment]
.and to answer your question more explicitly - OpenID Connect does not specify a browser-less flow. 
Resource owner flow is possible but not recommeded.

**Comment by devmoviit** [comment]
I don't wonna expose the user to a nasty web view. That's one of the reasons for developing a native app and not using the browser to view my responsive web app.

How do we make a native login activity on the app than?
Should we create "by hand" the requests? Is it even possible?

**Comment by leastprivilege** [comment]
https://speakerdeck.com/leastprivilege/mobile-applications

Why are web views nasty? ..and of course you can create protocol messages by hand - read the spec.

Anyways - this is not an idsrv related question, please move to StackOverflow
