### ISSUE TITLE
Access token duration per scope

### ISSUE THREAD

**Issue by omerlh** [IdentityServer/IdentityServer3#2791]
Hey! I 
have a question regarding access token expiration: I have an app that I want to issue tokens for it. Now, it can request several scopes, and for each scope we define how much it is important - which translate to the duration of the access token. 
For example, let say I have 3 scopes: a, b, c. Now, I want that scopes a and b will have a duration of 1 hour, and scope c will have a duration of 1 day. I think that I can implement this with different client id and define the scopes and expiration time for each of those clients. Let say, I will have client 1 and 2. Client 1 will have scopes a and b, and duration of 1 hour. Client 2 will have scope c and access token duration of 1 day
I would like to hear your thoughts about the problem and the suggested solution.
Thanks,
Omer

**Comment by leastprivilege** [comment]
Token expiration can be only configured per client. Or you need to hook
into the token service itself to set it dynamically.

—
cheers
Dominick Baier

**Comment by omerlh** [comment]
Ok, thanks!
