### ISSUE TITLE
IdentityServer API Integration Query

### ISSUE THREAD

**Issue by lastbuilders** [IdentityServer/IdentityServer3#2792]
### Question / Issue
Hi,

I am designing an integration between a number of client environments and a REST API we are writing and wanted to run through my design in terms of the integration with IdentityServer to see if it sounds valid or if I need to go back to the drawing board (again).

The scenario is that the client API (Server) needs to request authorization to access resources we host through the API. The Client request will need to target a specific client DB though the client will typically have a number of DBs available e.g. production, UAT, test etc. 

From the many videos, blogs and websites including this one I have reviewed I believe the following. 

1. My clients are "Trusted" as this is a Server to Server implementation and a specific "User" is not involved. 

2. The grant type appropriate to this is "Client Credentials Grant"

3. My next consideration is how to differentiate the target Client DB for a given request to the API. 
To support this I plan to add a "Scope" for each client DB to the Client configuration.

4. When the Authorization request is submitted by the client they will need to specify a Scope which the REST API would validate and use to target the request to the appropriate client DB. If a client requests scopes for multiple DBs the REST API  would return an error. 

5. I also plan to use ScopeClaims to support more fine grained access such as read, delete and write

Apologies if my queries are basic but I am quite new to IdentityServer though I have done a number of SAML implementations in the past so have some experience in the area. 

One other query I have is in relation to SSL Offloading (reverse proxy) support with Identity server as this is a deployment scenario used by many of our clients.

Kind Regards,
Lastbuilders

**Comment by lastbuilders** [comment]
Hi, 

Wanted to check if anyone has any feedback on my identity server query or could recommend another forum I can raise them on? 

Thanks,
Lastbuilders

**Comment by brockallen** [comment]
Client credentials sounds right. Scopes are meant to model what access which client has to a certain surface area of an API. It's intentionally vague and left up to the API implementer to decide what exactly what means. 

For anything further perhaps consulting would be more appropriate?

**Comment by lastbuilders** [comment]
Thank you for the feedback Brock
