### ISSUE TITLE
Is it possible to integrate IS3 and forgotten password process flow utilising apsnetidentity

### ISSUE THREAD

**Issue by oakuraape** [IdentityServer/IdentityServer3#2793]
I have a implemented IS3 (working great) as our secure token service for a project we are working on. AspNetIdentity is setup as the user manager. This is all working fine. My question is, is it possible to extend IS3, in the way you can extend it for registration and change password, to manage the forgotten password flow. Or is this a feature that is outside the scope of IS3. Any pointers/examples around this would be greatly appreciated.

**Comment by brockallen** [comment]
This has been covered many times in the issue history. In short, those features should be in a separate app, but that app can be co-hosted with IdSvr.

**Comment by JakeBayford** [comment]
I'm also quite curious about this. First of all let me just say how great IdentityServer is. Very well coded and elegantly structured. Thank you for making this open source to learn from! I'm new to the world of security/ OIDC/ OAuth2.0 and still a little wet behind the ears - so please forgive the ignorance. 

I'm curious what you would recommend for local user management workflow (register/ forgot password/ manage account etc). You suggested that those features should be abstracted away to a separate app. How do you see the user journey/ work flow going if a user does not have a local account and does not want to log in with an external provider? 

Perhaps a 'register' link could be injected into the default login IdentityServer view (much like in the samples) which then takes the user to another app to register and manage their account). However once the user has registered on the separate app how would they be directed back to the IdentityServer to resume the login workflow?

**Comment by brockallen** [comment]
We already have a mechanism for adding links to the login page for things like register and reset password. Check the docs.

Again, I'd suggest searching the issue tracker history for the numerous discussions about this. If you still have questions after, then please open a new issue and say that you you your question has not yet been discussed.
