### ISSUE TITLE
Where to add the forgot password.html file in my webhosted idserver application.

### ISSUE THREAD

**Issue by jothikiruthika-jltasia** [IdentityServer/IdentityServer3#2795]
### Question 

I have configured the AuthenticationOptions to bring up a forgot password link, but I am unsure as where i should be adding the html page so that the user can key in his username for password reset? I don't have any views/any other html files in the project. I would like to know as how to map a html file to the forgot password link and where to add this html.

**Comment by brockallen** [comment]
That's up to your link, meaning the URL is your own and you are responsible for hosting those files.

**Comment by jothikiruthika-jltasia** [comment]
Thanks Brock, but what i am trying to do is take up the custom view service and add a forgotpassword.html in the content/app folder and try to link this html file to the forgot password link. Is there any way to achieve this? I guess that there might be a way to wire this new html page with the forgot password link. Is this possible?

**Comment by brockallen** [comment]
IdentityServer, by design, doesn't know about those things. It would need to be a logically separate application, but it could be co-hosted with IdSvr.
