### ISSUE TITLE
Best practise for endpoint disabling?

### ISSUE THREAD

**Issue by wilhen01** [IdentityServer/IdentityServer3#2796]
Does anyone have any guidance on best practise re: disabling endpoints? Our implementation is only using the Implicit Flow type which I believe means we can disable some of the endpoints (e.g. Token & TokenRevocation) but I'm not sure if I'm being overzealous. Is it insecure to leave the endpoints available even if we aren't using them?

**Comment by brockallen** [comment]
There's an Endpoints option: https://identityserver.github.io/Documentation/docsv2/configuration/identityServerOptions.html that you can use to disable individual endpoints.

**Comment by wilhen01** [comment]
@brockallen I already found that; I know how to disable endpoints, I'm asking for opinions on whether I should!

**Comment by brockallen** [comment]
So the answer is yes -- that's why we have those settings. If you're not using them, then don't expose them.

**Comment by wilhen01** [comment]
Is there definitive documentation as to which endpoints are required for each of the flows? I had a look but couldn't find anything exhaustive, and the Endpoints documentation listed [here](https://identityserver.github.io/Documentation/docsv2/) doesn't seem to cover every endpoint available to enable/disable?

**Comment by brockallen** [comment]
We don't, but that's a good idea for documentation. https://github.com/IdentityServer/Documentation/issues/198

**Comment by wilhen01** [comment]
OK, I guess I'll play around and work out which endpoints I can ditch one by one without breaking anything! Thanks @brockallen

**Comment by brockallen** [comment]
Yep, that's a reasonable way to start :)

**Comment by wilhen01** [comment]
For reference in case anyone is interested, the following endpoint config seems to work for us using ImplicitFlow:

```
Endpoints = new EndpointOptions
                {
                    // Enabled
                    EnableAuthorizeEndpoint = true, // used to request access tokens / auth codes. (Flows: Implicit, Authorization Code).
                    EnableCheckSessionEndpoint = true,
                    EnableClientPermissionsEndpoint = true,
                    EnableEndSessionEndpoint = true, // used for logout
                    EnableUserInfoEndpoint = true, // used to retrieve identity information about a subject
                    EnableDiscoveryEndpoint = true, // used to retrieve metadata about IdentityServer

                    // Disabled
                    EnableAccessTokenValidationEndpoint = false, // used to validate reference tokens
                    EnableCspReportEndpoint = false, // reporting endpoint for Content Security Policy
                    EnableIdentityTokenValidationEndpoint = false, // used by clients without access to crypto libs e.g. Javascript
                    EnableIntrospectionEndpoint = false, // used to validate reference tokens
                    EnableTokenEndpoint = false, // used to progrmatically request or refresh tokens (Flows: resource owner password credential, authorization code, client credentials)
                    EnableTokenRevocationEndpoint = false, // used for revoking access tokens (reference tokens only) and refresh token
                }
```
