### ISSUE TITLE
How to get custom user claim in WebAPI?

### ISSUE THREAD

**Issue by UmeshSgh** [IdentityServer/IdentityServer3#2797]
Hi brockallen,

I am trying to implement like you have suggested in other forum or tutorials. Authorization in webapi with help of Resource Authorization and good part is that I am able to make it work if I use in memory users where I have hard coded roles.

var _user = User as ClaimsPrincipal;

With help of this, User claim is available at web api level without invoking UserInfo end point.  

As per our requirement, I have implemented Usermanagerservice and authenticating the user with our local database and also implemented GetProfileDataAsync and able to retrieve UserInfo through calling respective endpoint.

My problem or clarification is that when we attach claim along with users then it is by default available in web api whereas it is not available when I am using it as custom service. I tried to assign creating some dummy claim and assign it to context.AuthenticateResult.User. but, this is readonly. So could not make it.

In that I have only one option left to invoke UserInfo end point and create a claim principal. Could you please let me know where I should call this end point. If I call it in web api filter class it means that will get call for each request. 

My requirement is web api should be stand lone secured service. Only people who are having valid token they can access certain method based on their claim info.

It will great help if you could put some light on this. 

Thank a lot for you co-operation.

FYI...

This is how my code look like:

public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
		{
			string username = context.UserName;
			string password = context.Password;
			try
			{
				UserDetails userdetails = UserValidation.ValidateUserCredetial(username);
				if (userdetails != null)
				{					
					//AD User
					if (userdetails.IsADValidation)
					{
						//Calling Generic AD service to authenticate user.
						bool isADValidated = UserValidation.ValidateUserNamePasswordByREST(username, password);

						if (isADValidated)
						{							
							context.AuthenticateResult = new AuthenticateResult(subject: userdetails.UserID.ToString() + "," + username, name: username);
						}
                                       }					
				}
			}
			catch (Exception ex)
			{
				context.AuthenticateResult = new AuthenticateResult("Error Message:" + ex.Message + "  Stack trace:" + ex.StackTrace);
				context.AuthenticateResult.User =
			}
			return Task.FromResult(0);
		}
-------------------------------------------------------------------------------------------------------
public override Task GetProfileDataAsync(ProfileDataRequestContext context)
		{
			List<Claim> _claims = new List<Claim>();
			Claim _subject = context.Subject.Claims.FirstOrDefault();
			string[] userInfo = _subject.Value.Split(',');
			_claims.Add(new Claim(Constants.ClaimTypes.Subject, "UserName:" + userInfo[1]));

//Getting some data from database and assigned it as claim			
var responsibilities = GetUserMarketResponsibilities(userInfo[0]);
			if (responsibilities != null)
			{
				_claims.Add(new Claim(Constants.ClaimTypes.Role, JsonConvert.SerializeObject(responsibilities)));
			}
			context.IssuedClaims = _claims.AsEnumerable();
			return Task.FromResult(0);
			//return null;
		}

**Comment by brockallen** [comment]
> My problem or clarification is that when we attach claim along with users then it is by default available in web api whereas it is not available when I am using it as custom service. I tried to assign creating some dummy claim and assign it to context.AuthenticateResult.User. but, this is readonly. So could not make it.

This is the part where I start to get confused in your issue. I don't see anything terribly odd about the same code you posted, except you're not filtering claims based upon the scopes requested.

**Comment by UmeshSgh** [comment]
Thanks for reply and accept my apologies. I guess, I did not ask in short my question. 

So, In short, Can defined Claims will be available at WebAPI (under User as ClaimsPrincipal) without calling UserInfo endpoint? Issue I am facing is if I call this endpoint in API then it will get invoked for each request.

FYI...
I tried using InMemory users and without having custom service then It is available at web api level. Since, there is no GetProfileDataAsync. 

Please assist me if there is any alternate option available to get user claim principal at web api level.

Thanks once again

**Comment by brockallen** [comment]
> Can defined Claims will be available at WebAPI (under User as ClaimsPrincipal) without calling UserInfo endpoint

Yes, the user's claims can be packaged into the access token by configuring the ScopeClaims on the Scope definition.

**Comment by UmeshSgh** [comment]
Thank you. It has worked. Actually, I was using persistence layer along with custom service and that is reason I was not able to figure it out. When I tried it separately I cracked the issue.

Thanks once again.
