### ISSUE TITLE
IdentityServer3 MFA 

### ISSUE THREAD

**Issue by hargrave81** [IdentityServer/IdentityServer3#2798]
### Question / Issue
I'm new to github.  I'm trying to leverage the work done with IdentityServer3.  I have a local instance running and I'm able to login, and validate users.  I have tied it all to a database and that is working as well.  Further I have customized the login screens.

Now I need to change the work flow to allow a form of MFA.  When the user logs in with a user name and password, I need it to be able to not fully log them in if the machine they are coming from is different, and rather they have to be further authenticated via SMS/email within the identity server realm.  I have gone through the interfaces and such and am not sure what the best approach is to inject this new work flow.

Thanks in advance!

**Comment by leastprivilege** [comment]
There's a 2FA sample in the samples repo.
