### ISSUE TITLE
Token validation exception

### ISSUE THREAD

**Issue by arindamdat** [IdentityServer/IdentityServer3#2799]
### Question / Issue
I get random ArgumentException from TokenValidator while validating token.
Details given below:
IdentityServer3.Core.Validation.TokenValidator – JWT token validation error System.ArgumentException: IDX10708: ‘System.IdentityModel.Tokens.JwtSecurityTokenHandler’ cannot read this string: ‘Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkVnVWdVNlJpQUVsSjNkWDlHSk52OTVHNmZyUSIsImtpZCI6IkVnVWdVNlJpQUVsSjNkWDlHSk52OTVHNmZyUSJ9.eyJpc3MiOiJodHRwOi8vd3d3LmRyaXZlZmxvLmNvbS8iLCJhdWQiOiJodHRwOi8vd3d3LmRyaXZlZmxvLmNvbS9yZXNvdXJjZXMiLCJleHAiOjE0NjM2Njc4MDcsIm5iZiI6MTQ2MTA3NTgwNywiY2xpZW50X2lkIjoiZmxvc2VsZmNsaWVudGN1c3RvbSIsInNjb3BlIjpbIm9mZmxpbmVfYWNjZXNzIiwicHJvZmlsZSIsInJlYWQtd3JpdGUiXSwic3ViIjoiMTAwMzgiLCJhdXRoX3RpbWUiOjE0NjEwNzU4MDYsImlkcCI6Ikdvb2dsZSIsIm5hbWUiOiJTYXZlIGRyaXZlSW5kaWEiLCJyb2xlIjoiQmFzaWMiLCJhbXIiOlsiZXh0ZXJuYWwiXX0.VIkoKEB0V8gIx5lggQ0T21ogfIy5coQIoXq4RRbyEkYyIAzWacgjnEjtmlmPXVEgCpTNnN043IxrzCPYTGaoOJTkMoQGdNGgJErAH40GY-O1wiTI6FrH88p09S1pq4wOTPflziU1_h8Af2rFiChP7skyGpQz-VXc5anbg34Yh4H0wIKHepPpVWPSMwkGbvGhSWxbU30wQW_axnPFi9q1s5DQyVGaRNuZDQrtuO82V7AbTIu204aLg_hZN4FER4ZMiCl2GQ_dxztGidTp9QzoO1ylbZx-ZSkdZDnQOqAFvpIhMalnC7_LX8vOuIa5shFF7AleYFV66DqGu5-Omgdf4Q’. The string needs to be in compact JSON format, which is of the form: ‘<Base64UrlEncodedHeader>.<Base64UrlEncodedPayload>.<OPTIONAL, Base64UrlEncodedSignature>’.
at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ReadToken(String tokenString)
at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
at IdentityServer3.Core.Validation.TokenValidator.<ValidateJwtAsync>d__1b.MoveNext()

**Comment by brockallen** [comment]
Sounds like the token is being modified or changed in some way as it's presented to IdSvr. I'd suggest trying to find out why.

**Comment by brockallen** [comment]
Any update?
