### ISSUE TITLE
Flow for mobile App where resource owner is not the end user but a device.

### ISSUE THREAD

**Issue by veredmeri** [IdentityServer/IdentityServer3#2802]
Hi,

Our mobile App should communicate with our Web API, but in our flow the end user is irrelevant and therefor we don't want him to enter username/password. The mobile App is getting the credentials automatically from a device it communicates with and should request for token with that credentials. the end user is not involved.

Can i use resource owner flow (take in mind that the resource owner is not the end user but some other device the mobile App is talking to and gets the user password from). If that's a bad idea, which flow should I use?

if a mobile App client use resource owner flow what should i set in the AllowedCorsOrigins?

Is it possible to extend the authentication to authenticate with some extra parameter (e.g by validating the username, password, serial number and key)?

Thanks
Vered

**Comment by leastprivilege** [comment]
If there is no concept of a user, use client credentials flow. For custom parameters use a custom grant.

The docs has more details.

**Comment by veredmeri** [comment]
Thanks Dominick,
I am not sure client credentials is right for me.
This is my senario:
My mobile App concept is to give the user information about a device it is connected to.
When a user open the App, the App is recognizing the device and retrieve 3 identifiers from it. with these 3 identifiers it should request an access token from the identity server, which validates them and provide access token. then the app will call my resource API with that token.
I chose the custom flow and implemented a custom authentication that validates the 3 identifiers against my database. 
1. Does my solution make sense?
2. For testing purposes, I created a jquery client that calls the identity server and the resource API and it all works well when i set the AllowedCorsOrigins, which seems to be mandatory, with the my jquery client uri and the resource api uri. I am just wondering if that will work on production when i have to set the AllowedCorsOrigins with the mobile App uri? which are not quite the same as a web uri? should that work?

Thanks
Vered

**Comment by leastprivilege** [comment]
CORS is a browser concept - is you mobile app running in a browser?

**Comment by veredmeri** [comment]
No.
(You are faster then the speed of light :-)

**Comment by brockallen** [comment]
All set, can we close this issue?

**Comment by veredmeri** [comment]
Does it mean that CORS is irrelevant when a mobile App request a token without using a browser (i have a custom flow)?

**Comment by brockallen** [comment]
Yes

-Brock

**Comment by brockallen** [comment]
Yes meaning correct 

-Brock

**Comment by veredmeri** [comment]
Thanks!
