### ISSUE TITLE
Get user profile on facebook login

### ISSUE THREAD

**Issue by timmynz** [IdentityServer/IdentityServer3#2803]
### Question / Issue
Im trying to setup identityserver to be able to login with facebook. All works fine except I cant retrieve any of the user info from facebook.The mvc app is expected a givenname and lastname claim. I have added a scope to public_profile but do not get it back. How do I go about getting the user info in OnAuthenticated? 

### Code

    private void ConfigureIdenityProviders (IAppBuilder app, string signInAsType)
    {

        var facebookOptions = new Microsoft.Owin.Security.Facebook.FacebookAuthenticationOptions
        {
            AuthenticationType = "Facebook",
            Caption = "Sign in with Facebook",
            SignInAsAuthenticationType = signInAsType,
            AppId = "xxxxxxxxxxxx",
            AppSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

            Provider = new Microsoft.Owin.Security.Facebook.FacebookAuthenticationProvider()
            {
                OnAuthenticated =  (context) =>
                {

                    // Problem here - there is no last_name returned
                       JToken lastname;
                    if (context.User.TryGetValue("last_name", out lastname))
                    {
                        context.Identity.AddClaim(new System.Security.Claims.Claim(IdentityServer3.Core.Constants.ClaimTypes.FamilyName, lastname.ToString()));
                    }

                    context.Identity.AddClaim(new System.Security.Claims.Claim("role", "Guest"));

                    return Task.FromResult(0);

                }

            }
        };

         facebookOptions.Scope.Add("public_profile");
        facebookOptions.Scope.Add("email");

        app.UseFacebookAuthentication(facebookOptions);

    }

**Comment by leastprivilege** [comment]
That seems to be an issue with the Microsoft middleware - maybe use their forum or StackOverflow.
