### ISSUE TITLE
Undesired Caching

### ISSUE THREAD

**Issue by EurothermSteve** [IdentityServer/IdentityServer3#2804]
We are currently using IdentityServer3 for authentication and authorization using reference tokens and
seem to be have some undesired caching of a users claims when creating a token.

The scenario is - if a user has two claims and a request is sent in to get a token then that token is created in the tokens table and contains the two claims, if a third claim is then added to that user and a request sent in to get a token then a new token is created in the tokens table but still only contains those original two claims. You either have to wait a (significant) amount of time or do an IISreset before requesting the token for it to contain that new claim.

Is there a way to stop this happening as we require it to get the latest set of claims everytime a token in requested?

**Comment by brockallen** [comment]
The `Client` has a `UpdateAccessTokenClaimsOnRefresh` setting that will update the token from the user service, but that's only for refresh tokens. I think we have an open issue somewhere to do something similar for reference tokens.
