### ISSUE TITLE
How to authorize user permissions using ClaimsAuthorizationManager

### ISSUE THREAD

**Issue by pagidigovardhan** [IdentityServer/IdentityServer3#2805]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi Domnick
My apologies for the long post here..

I have an MVC app consumes WCF service. As part of authentication and authorization 
I am using ReurceOwnerFlow to get the token, once token is received I am sending Access_token to WCF service. In WCF service  I've plugged ClaimsAuthorizationManager where I am trying to check user permissions. But AuthorizationContext doesn't give me any user scopes that I configured.

### Setting scope at Identity Server 

                new Scope
                {
                    Enabled = true,
                    DisplayName = "",
                    Name = "abc",
                    Description = "Access to a abc WCF Services",
                    Type = ScopeType.Resource,

                    Claims = new List<ScopeClaim>
                    {
                        new ScopeClaim("getac"),
                        new ScopeClaim("saveuser")
                    }
                }

### WCF Authorization manager
public class RequireAuthenticationAuthorizationManager : ClaimsAuthorizationManager
    {
        public override bool CheckAccess(AuthorizationContext context)
        {
            if (context.Principal.Identity.IsAuthenticated)
            {
                //use context.Principal.Claims and authorize
                string methodName = GetActionMethodName();
                object[] attrs = GetAllAttributes(methodName);
                return CheckUserRights(context, methodName, attrs);
            }
            return false;
        }
### WCF service
[ClaimPermission(SecurityAction.Demand,Operation= "GetAccount", Resource ="getac")]
        public Account GetAccount(string accountId)
        {

}

### WCF Client

static string GetJwtToken()
        {
            System.Net.ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
            var oauth2Client = new TokenClient(
                "https://localhost:44306/Identity/connect/token",
                "client_id",
                "secret");

           
            var tokenResponse =
               oauth2Client.RequestResourceOwnerPasswordAsync("govardhan", "1234", "abc").Result;

            
            return tokenResponse.AccessToken;
        }
### Relevant parts of the log file

```
<log goes here>
```

**Comment by mderriey** [comment]
Hey, you might want to have a look at [this thread on StackOverflow](http://stackoverflow.com/questions/30368204/how-to-use-jwt-tokens-with-wcf-and-wif).

**Comment by pagidigovardhan** [comment]
Thanks mderriey,

I referred the same, Validatetoken will validate the Client Scope(in my example it is "abc") using Access_token(SAML token),  but where is the logic written for user permission check which is part of authorization.

In my example I want to authorize whether user has access to GetAccount method or not?
ClaimsPrincipal is annotated with Operation="GetAccount"  and Resource="getac"

Will the below code is meant to do that?

class RequireAuthenticationAuthorizationManager : ClaimsAuthorizationManager
 +    {
 +        public override bool CheckAccess(AuthorizationContext context)
 +        {
 +            return context.Principal.Identity.IsAuthenticated;
 +        }
 +    } 

Please guide me if my understanding is not correct.

Thanks.

**Comment by mderriey** [comment]
Could you elaborate on your config? like the WCF service config file? I'm not certain everything is setup correctly. Thanks

**Comment by pagidigovardhan** [comment]
Here it is..
<system.identityModel>
    <identityConfiguration saveBootstrapContext="true">
      <securityTokenHandlers>
        <clear />
        <add type="WCF.IdentityAuthorization.IdentityServerWrappedJwtHandler, WCF.IdentityAuthorization" />
        <securityTokenHandlerConfiguration>
          <certificateValidation certificateValidationMode="None" />
        </securityTokenHandlerConfiguration>
      </securityTokenHandlers>
      <claimsAuthorizationManager type="WCF.IdentityAuthorization.RequireAuthenticationAuthorizationManager, WCF.IdentityAuthorization" />
    </identityConfiguration>
  </system.identityModel>

As per the reference code, it goes to RequireAuthenticationAuthorizationManager and returns true, because the client and scope is valid (context.Principal.Identity.IsAuthenticated)
This works fine. 

Sorry for my English, I'll explain my issue again :)

Where can I write logic to check user permission 
let's say User A is not accessible to GetAccount method How can I validate this?

**Comment by mderriey** [comment]
Thanks.

I'd suggest checking step by step. Are the claims associated with your `abc` scope present in:

 - The JWT token you get via the WCF client?
 - The identity that the `IdentityServerWrappedJwtHandler` generates?

Cheers

**Comment by pagidigovardhan** [comment]
This is how the abc scope is setup in Identity Server
new Scope
            {
                Enabled = true,
                DisplayName = "",
                Name = "abc",
                Description = "Access to a abc WCF Services",
                Type = ScopeType.Resource,

                Claims = new List<ScopeClaim>
                {
                    new ScopeClaim("getac"),
                    new ScopeClaim("saveuser")
                }
            }

And WCF Client gets the token like this
Once I got the token I am sending this as a bearer token (after saml wrap) to WCF service
            var oauth2Client = new TokenClient(
                "https://localhost:44306/Identity/connect/token",
                "MPCWCF",
                "secret");

            
            var tokenResponse =
               oauth2Client.RequestResourceOwnerPasswordAsync("govardhan", "1234", "abc").Result;
         
 var xmlToken = WrapJwt(tokenResponse.AccessToken);
                var binding = new WS2007FederationHttpBinding(WSFederationHttpSecurityMode.TransportWithMessageCredential);
                binding.HostNameComparisonMode = HostNameComparisonMode.Exact;
                binding.Security.Message.EstablishSecurityContext = false;
                binding.Security.Message.IssuedKeyType = SecurityKeyType.BearerKey;
                System.Net.ServicePointManager.ServerCertificateValidationCallback += (se, cert, chain, sslerror) => { return true; };
                var factory = new ChannelFactory<ServiceReference1.IConfigurationContract>(
                  binding,
                  new EndpointAddress("https://localhost/SystemConfigurationService/SystemConfigurationService.svc/SysConfig"));

                var channel = factory.CreateChannelWithIssuedToken(xmlToken);

//Calling WCF service
                var result = channel.GetAccount("test");

**Comment by pagidigovardhan** [comment]
Hi mderriey 

I got the point..seems I should call GetUserInfo endpoint to get user claims which can serve user authorization


UserInfoClient userInfoClient = new UserInfoClient(new Uri("https://localhost:44306/identity/connect/userinfo"),AccessToken);
            var userInfo = await userInfoClient.GetAsync();


But how to pass the AccessToken to userinfo endpoint, as we have saml token (SecurtyToken) in JwtTokenHandler?

**Comment by mderriey** [comment]
You didn't really answer my previous question.
Could you inspect the access token and check if the necessary claims are present? We're interested in the `getac` clain since it's the one on which the authorization on your WCF method is based.

Check for that claim just after you get the access token from IdSrv3.
If it's here, then check if it's present when the `IdentityServerWrappedJwtHandler` handles the SAML token.

Thanks

**Comment by pagidigovardhan** [comment]
Sorry Derriey..
I was not calling userifo end point earlier.. Now I am callling userinfo endpoint and adding necessary claims to access_token. That way it worked.

**Comment by brockallen** [comment]
Application authorization is really out of scope for this issue tracker.
