### ISSUE TITLE
Identity Serve 3 when cookies are disabled.

### ISSUE THREAD

**Issue by chetanrajdev1** [IdentityServer/IdentityServer3#2806]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi,

We are using Identity Server 3.0 with OpenIdconnect for our SSO requirements and it is working as expected.

But when cookies are disabled in users browsers, we are getting error from Identity Server.

In UseOpenIdConnectAuthentication settings, we are giving SignInAsAuthenticationType = "Cookies". 

Here I have some questions - 

1) What are the other options to set for SignInAsAuthenticationType?
2) Can we avoid cookies dependencies and allow users to login even though cookies are disabled in browsers?
3) Cookies are mandatory to work with OpenIdconnect configuration at server side?

Thanks,
Chetan

 
            

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
> But when cookies are disabled in users browsers, we are getting error from Identity Server.

Sure. Half the web won't work if you disable cookies, and trying to build a solution around that introduces more security threats: https://brockallen.com/2012/04/08/cookieless-session-considered-dangerous/
