### ISSUE TITLE
Automatically login window authenticated user (active directory)

### ISSUE THREAD

**Issue by tienw** [IdentityServer/IdentityServer3#2807]
Thank your for this awesome project, we use and love the IdServer3.

We are trying to figure out a way for IdentityServer to work with our new asp.net MVC project and legacy desktop app that was authenticated by Active directory. so here is the requirement: For intranet users who are window authenticated (managed by active directory) will automatically detected and login by IdentityServer without typing username and password, for external users from web, it go to the normal route where users enter username and password (managed by Asp.net Identity)

I tried to setup WS-Federation and Active Directory as external provider, However, it requires extra clicks from user to select the windows login, then enter username and password. Did I go to the right direction to achieve our requirement? if yes, how or what's the best way to customize it without intranet authenticated user to login again.

Thank you in advance

**Comment by leastprivilege** [comment]
You could check the IP address of the user in the user service - and if it's an internal user you can go directly to the AD IdP.

**Comment by tienw** [comment]
Thanks @leastprivilege for the reply

Sorry for stupid question, but how do I redirect the internal user to AD IdP from the Main IdSer? 

Here is my current IdServer setup, uses the example of [WebHost (Windows Auth)](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/WebHost%20(Windows%20Auth)), configured Asp.Net Identity on the main IdSer and configured the another external provider to use windows authentication. Everything work fine except for Windows authenticated user, I want it directly being authenticated by IdSer when login button clicked (without entering username and password)

**Comment by leastprivilege** [comment]
Check the IP address in PreAuthenticateAsync - and set the appropriate IdP on the SignInMessage for internal users.

**Comment by tienw** [comment]
It worked! Thank you @leastprivilege 

This is what I have done to make it detect internal user by ip/domain in the PreAuthenticateAsync event.

`public override async Task PreAuthenticateAsync(PreAuthenticationContext context)
        {
                string dns = Dns.GetHostName();
                string hostName = Dns.GetHostName();
                IPHostEntry host = Dns.GetHostEntry(hostName);
                string localHost = "xxx.com";

                if (host.HostName.EndsWith(localHost))
                {
                    context.SignInMessage.IdP = "windows";
                }
        }`
