### ISSUE TITLE
Using IdentityServer in a SPA and having an embeded login 

### ISSUE THREAD

**Issue by minteractive** [IdentityServer/IdentityServer3#2808]
Hi,

I am working on a mobile SPA application and interested in integrating IdentityServer 3/4 along with the oidc-token-manager client library (the user should logged into the regular site if they choose to go back to the desktop version). I saw this video http://brockallen.com/2015/06/19/demos-ndc-oslo-2015/ from Brock, and looks impressive to know how easy it is to integrate.One of the issue our team is trying to tackle as well as understand is to know if there is a way to embed the Identity Server login page within an iFrame, so as to avoid the redirect or the pop-up window to login. I see a configuration to silently renew the token which uses an iFrame and wondering if there is a similar option for the login. 

I also did some search in the issues section and found that Resource Owner Flow would be the right option, but my question then with this approach is,
1. Are we going to loose the IdSrv session management feature?
2. Does this mean that there is no SSO anymore as we are retrieving just the token and custom handle the user session (if they go back and forth between the mobile and desktop site)

I really appreciate if you can guide me in the right direction...

**Comment by brockallen** [comment]
> One of the issue our team is trying to tackle as well as understand is to know if there is a way to embed the Identity Server login page within an iFrame, so as to avoid the redirect or the pop-up window to login

This has been asked before and searchable in the archives. The short answer is no.

Resource owner flow is in the spec for porting legacy apps to the concept of a token service. It's discouraged for new apps.
