### ISSUE TITLE
Cookie Authentication: how does it work?

### ISSUE THREAD

**Issue by marconline** [IdentityServer/IdentityServer3#2809]
Hi everybody,
following the second Demo  - [https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html]
I'm trying to authenticate a user using a client that users Implicit Flow.

This client stays on a main subdomain like https://app.myapp.com. Whenever I hit this app, everything is under [Authorize] filter, so I'm redirected to the Authority endpoint (defined in UseOpenIdConnectAuthentication). I'd like this Authority endpoint to run on a different domain like https://auth.myapp.com.

The implicit flow is completed correctly, and - in the end - I see the Authorization Server posting the id_token. I cannot understand at this point what happens behind the scenes.
Can you please explain me how this "UseCookieAuthentication" works?

I see that, when my client receives the id_token, in the POST response there is a "Set-Cookie" header. Is this the authentication cookie?
I'm missing something...

Thanks,
Marco

**Comment by marconline** [comment]
I add a strange fact: I opened this question because I see, from the app codebehind, that incoming requests are not authenticated. But the same app is not redirecting me back to the login page, so I think that somewhere this apps thinks I'm logged, but in the OwinContext I'm not.

Please, give me some details.
Thanks for your help!
Marco

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
