### ISSUE TITLE
Per client requirement of scopes and claims [question]

### ISSUE THREAD

**Issue by TheJayMann** [IdentityServer/IdentityServer3#2810]
### Question

I would like to be able to have a client choose whether a scope is required (either on the client registration side, or within the client request, as I could make either way work).  I'm assuming I could do that by either making separate scopes, one that is not set as required, and one that is, or even create "virtual scopes" where the scope store would see any requests for a scope ending in, say, "-required" as a scope where the Required property is set to true.

Also, if a client has a scope set to required, and there are no claims within the user profile to match this scope, I would like to have the user sent to a profile page related to the scope in question, where the user can fill in the missing profile.

As an example of this flow, I will use the email scope and three clients, one which does not request an email, one which optionally requests and email, and one which requires an email.

First, the one which does not request an email will not use the email scope.

Second, the one which optionally requests an email will have a not required email scope, if the user does not consent to the email scope, no email address will be sent, and if the user does consent to the email scope but has no email address in his profile, no email address will be sent.

Third, the one which requires email scope, the user will be required to consent to the email scope, and, if the user does not have an email address in his profile, will first be directed to the email address profile page, where he will be required to add an email address to his profile before continuing authentication to the client.

Is this something that is supported?  If so, which services would I need to implement?

**Comment by brockallen** [comment]
This is something you'd have to figure out how to build yourself.
