### ISSUE TITLE
acrvalues missing from SignOutMessage

### ISSUE THREAD

**Issue by richmond-git** [IdentityServer/IdentityServer3#2814]
How can custom information be passed to LogOut and LoggedOut methods of the IViewService? 

Its possible to achieve this on the Login method as it uses SignInMessage object and has the acrvalues property which can be used to store custom information.

The specific problem I am trying to solve is passing tenant information from client application back to the identity server for consumption on the logout/loggedout views.

**Comment by brockallen** [comment]
The spec doesn't allow for acr_values on the signout request. If you need to remember things about the user, then you can put additional claims into the cookie at IdSvr by adding claims to the AuthenticateResult in your AuthenticateLocal method on the user service. Those would then be available at signout.

**Comment by richmond-git** [comment]
Thanks, Brock. Would you recommend using Thread.CurrentPrincipal to get the claims from within the ViewService, or is there another context available to access claims?

**Comment by brockallen** [comment]
The Subject is passed as a param to signout on the view service.

In the user service you'll have to inject the OwinEnvironmentService and then use our OWIN extensions to get the current logged in user: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html
