### ISSUE TITLE
JWT claims not updating

### ISSUE THREAD

**Issue by hamuk** [IdentityServer/IdentityServer3#2815]
I have an issue where I'm issuing a JWT token including claims from an ASP NET Identity Database. After the token is issued I change the claims in the DB but no matter what I do (aside from an IIS reset) I am always provided the old claims.

I've tried fetching a new token, deleting the token and fetching a new one, refreshing the token (including using _UpdateAccessTokenClaimsOnRefresh_), using the [access token validation endpoint](https://identityserver.github.io/Documentation/docsv2/endpoints/accessTokenValidation.html), and the [token introspection endpoint](https://identityserver.github.io/Documentation/docsv2/endpoints/introspection.html).

No matter what I only seem to get the old claims.

My client is configured like this:

```cs

new Client
{
	ClientName = "My API",
	ClientId = "myapi",
	ClientSecrets = new List<Secret> { new Secret("wasd".Sha256()) },
	UpdateAccessTokenClaimsOnRefresh = true,
	Flow = Flows.ResourceOwner,
	
	AllowedScopes = new List<string>
	{
		"openid",
		"email",
		"profile",
		"api",
		"offline_access",
		"roles"
	},

	AccessTokenLifetime = 60
}

```

Am I missing something? Is there another way to get the newest claims?. The roles in the token always seem to update so I could switch to using roles instead but I'd rather not if I could avoid it!

Cheers
Jordan

**Comment by leastprivilege** [comment]
Put a breakpoint in your GetProfileDataAsync method. Then you'll know why.

—
cheers
Dominick Baier

**Comment by hamuk** [comment]
I finally got it working!

I'm using the Asp Net Identity User Service and I followed your suggestion which did point me in the right direction. It turns out I was doing the dependency injection all wrong and a new User Manager wasn't being instantiated for each request which I believe was the issue. I've changed my DI to be more like the samples and it works fine now.

Thanks for the help
