### ISSUE TITLE
Multiple identity providers

### ISSUE THREAD

**Issue by solidstore** [IdentityServer/IdentityServer3#2817]
I am trying to add local, Windows and ADFS into the single IdentityServer project. I am using the IdentityServer.WindowsAuthentication project as the provider for Windows auth (that's in a separate web project). Both Windows and ADFS use UseWsFederationAuthentication in the IdentityServer startup code.

If they are only used individually things are working perfectly, however if both are added together the second provider not longer works and gets an error: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier

Is added two UseWsFederationAuthentication middleware the cause of these issues? And is there a way around it. 

Startup snipit:

           var options = new IdentityServerOptions
            {
                SigningCertificate = Certificate.Load(),
                Factory = Factory.Configure("IdSvr3Config"),

                AuthenticationOptions = new AuthenticationOptions
                {
                    EnableLocalLogin = Settings.Auth.EnableLocalLogin,
                    IdentityProviders = ConfigureIdentityProviders
                },
            };

            appBuilder.UseIdentityServer(options);
        }

        private void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            if (Settings.Federation.EnableWsFederationAuthentication)
            {
                var adfs = new WsFederationAuthenticationOptions
                {
                    AuthenticationType = "adfs",
                    Caption = "ADFS", 
                    SignInAsAuthenticationType = signInAsType,

                    MetadataAddress = Settings.Federation.MetadataAddress,
                    Wtrealm = Settings.Federation.Identifier
                };
                app.UseWsFederationAuthentication(adfs);
            }

            if (Settings.WindowsAuthentication.EnableWindowsAuthentication)
            { 
                var wsFederation = new WsFederationAuthenticationOptions
                {
                    AuthenticationType = "windows",
                    Caption = "Windows", 
                    SignInAsAuthenticationType = signInAsType,

                    MetadataAddress = Settings.WindowsAuthentication.MetadataAddress,
                    Wtrealm = Settings.WindowsAuthentication.Realm,                   
                };
                app.UseWsFederationAuthentication(wsFederation);
            }
        }
 

Thanks in advance

**Comment by brockallen** [comment]
You need distinct callback paths for each WsFed middleware -- they're stepping on each other.

**Comment by solidstore** [comment]
Thats great.
I added                     

CallbackPath = new PathString("/identity/adfs")
and
                    CallbackPath = new PathString("/identity/windows")
