### ISSUE TITLE
IdentityServer + Partner ADFS

### ISSUE THREAD

**Issue by Synergistic** [IdentityServer/IdentityServer3#2818]
### Question

Hi all,

 Forgive my ignorance, I'm still very new to all these concepts and I've been thrown onto this project to wade through the details.

Here is my scenario:

Organization A has several web applications they would like SSO for, the account credentials are stored in a SQL database. Organization A would like to provide a link to "jump" over to Organization B's webapp in a SSO-like fashion. Organization B utilizes ADFS 2.0.

I've got IdentityServer3 up and running locally and authenticating with InMemory users for testing purposes. We've also got a barebones local ADFS server running that utilizes our AD accounts. I've also got the minimum setup with the WS-Federation plugin. My confusing is around the roles that IdentityServer and ADFS can potentially play in this flow.

My questions: 

1. Is it possible to authenticate using IdentityServer3 (receive a token/set of claims) that could be utilized by Organization A to grant access to Organization B's webapp (that is using ADFS)?

2. If this is possible, can anyone help me formulate the "right question" for the process? I'm having trouble nailing down exactly what my next step is. I.e. Now that I have IdentityServer3 authenticating, what is my next step in getting this token in the correct "format" and passing it over to ADFS for verification?

In case question 1 isn't specific enough, here is a very general outline of what we like to happen:

- User logs in on Organization A's webapp and gets authenticated via IdentityServer3.

- User clicks a link on Organization A's webapp to make a jump over to Organization B's webapp

- Organization B's ADFS server see's the token from IdentityServer3 and doesn't prompt the user for credentials, instead just allowing them to utilize Organization B's webapp

Thank you very much,
Dan

**Comment by brockallen** [comment]
Sounds like this is more of an architecture question for your scenario, rather than an issue with IdentityServer per-se. I'll give you a short answer: there needs to be a chain of trust for SSO. So if B users need to access A apps, then A apps need to trust something that either directly or indirectly trusts B's IdP.

**Comment by Synergistic** [comment]
I apologize for that, again I'm very new to all this and it's still got me pretty confused in many aspects I don't mean to muck up your issue board. I really appreciate you taking the time to provide me that answer.

**Comment by Synergistic** [comment]
Hello again Brock,

 I figured this wasn't worthy of it's own thread but I've made some good progress since yesterday! I'm encountering {"Message":"invalid_relying_party"} when going through the ADFS server and I'm not sure what I'm doing wrong. Here is my relying party:
`                            new RelyingParty
                               {
                                   Realm = "http://asdf1.t3group.com/adfs/services/trust", 
                                   Enabled = true, 
                                   ReplyUrl = "http://asdf1.t3group.com/adfs/ls/", 
                                   TokenType = TokenTypes.Saml2TokenProfile11,
                                   TokenLifeTime = 1,
                                   ClaimMappings =
                                       new Dictionary<string, string>
                                           {
                                                { "name", ClaimTypes.Name },
                                                { "email", ClaimTypes.Email }
                                           }
                               }`
