### ISSUE TITLE
User Service

### ISSUE THREAD

**Issue by ndruda** [IdentityServer/IdentityServer3#2819]
I created a custom Use Service that authenticates username and password against domain.  I registered the user service within my IdentityServerServiceFactory.  I can hit a breakpoint within the AuthenticateLocalAsync method, step through successfully all the way to where it returns the new AuthenticateResult.  My claims match the claims defined in my scope however i get a bad request every time.

When i pull the log it says:
iisexpress.exe Information: 0 : 2016-04-27 17:13:17.646 -04:00 [Information] Welcome page requested - rendering
iisexpress.exe Information: 0 : 2016-04-27 17:13:45.694 -04:00 [Information] Start token request
2016-04-27 17:13:45.733 -04:00 [Debug] Start client validation
2016-04-27 17:13:45.735 -04:00 [Debug] Start parsing Basic Authentication secret
2016-04-27 17:13:45.735 -04:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
iisexpress.exe Information: 0 : 2016-04-27 17:13:45.736 -04:00 [Information] Secret id found: "scheduling"
2016-04-27 17:13:45.758 -04:00 [Debug] Secret validator success: "HashedSharedSecretValidator"
iisexpress.exe Information: 0 : 2016-04-27 17:13:45.758 -04:00 [Information] Client validation success
iisexpress.exe Information: 0 : 2016-04-27 17:13:45.772 -04:00 [Information] Start token request validation
iisexpress.exe Information: 0 : 2016-04-27 17:13:45.787 -04:00 [Information] Start password token request validation
iisexpress.exe Error: 0 : 2016-04-27 17:14:18.648 -04:00 [Error] User authentication failed: Invalid username or password
 
I am validating and passing back the new AuthenticateResult(user.UserID, user.DisplayName,lstClaims)

 Please Help can't figure it out.

`
public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {

            AuthenticateResult result = null;
            ActiveDirectoryUser user = null;

            try
            {
                string adName = ConfigurationManager.AppSettings["ActiveDirectoryName"];

                if (ActiveDirectoryHelper.ValidateCredentials(context.UserName, context.Password, adName))
                {
                    user = ActiveDirectoryHelper.GetActiveDirectoryUser(context.UserName, adName);

                    if (user == null)
                    {
                        throw new Exception("Error retrieving user from active directory search.  Validation occurred but domain server did not return a valid user.");
                    }

                    //BuildClaims 

                    List<Claim> lstClaims = new List<Claim>
                    {
                        new Claim(Constants.ClaimTypes.Name,string.Format("{0} {1}",user.FirstName,user.LastName)),
                        new Claim("obj_id",user.UserID.ToUpper()),
                        new Claim(Constants.ClaimTypes.Email, string.IsNullOrEmpty(user.Email) ? string.Empty : user.Email.ToLower()),
                        new Claim(Constants.ClaimTypes.GivenName,user.FirstName),
                        new Claim(Constants.ClaimTypes.FamilyName,user.LastName)

                    };

                    result = new AuthenticateResult(user.UserID, user.DisplayName,lstClaims);
                    

                }
                else
                {
                    result = new AuthenticateResult("Incorrect credentials");
                }
            }
            catch (Exception ex)
            {
                result = new AuthenticateResult(ex.Message);
            }

            return Task.FromResult(result);
        }
`

i get the error:

> Response status code does not indicate success: 400 (Bad Request).

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).

Source Error: 

Line 53: 
Line 54:             string authServerAddress = WebConfigurationManager.AppSettings["AuthorizationServerIssuerAddr"];
Line 55:             var client = new OAuth2Client(new Uri(string.Format("{0}/connect/token",authServerAddress)), "scheduling", "secret");

**Comment by mderriey** [comment]
Hey,

You need to feed the `AuthenticateResult` in the provided `LocalAuthenticationContext` and not return it. That's why the return type of the method is just `Task` and not `Task<AuthenticateResult>`.

It would look something like:
```
public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
    // All the logic
    context.AuthenticateResult = result;

    return Task.FromResult(0);
}
```

**Comment by ndruda** [comment]
Thank you that worked
