### ISSUE TITLE
Why is ClientID in the SignOutContext object not populating

### ISSUE THREAD

**Issue by Bob55** [IdentityServer/IdentityServer3#2823]
When calling the sign out endpoint from a javascript SPA, the clientID string is empty in SignOutAsync().  Is there another way to know what's initiating the sign out?

**Comment by leastprivilege** [comment]
Are you sending the id token hint?

**Comment by Bob55** [comment]
We're using reference tokens, so the client does not have an id_token. Am I missing something here?

**Comment by brockallen** [comment]
At signout time if you want to know the client then the signout needs to be authenticated in some way. Passing the origin id_token you received accomplishes that.

**Comment by Bob55** [comment]
We now request the id_token and pass that along to the sign out endpoint. ClientId gets populated as expected. Thanks everyone.
