### ISSUE TITLE
Redirect from custom ICustomRequestValidator to custom page

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2824]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Hi,
I have something like this problem https://github.com/IdentityServer/IdentityServer3/issues/2416.
I have implement my custom validator but if the user not have access i want to redirect the user to my custom page.
How can i do this?
Thanks

**Comment by brockallen** [comment]
You'd need to set the prompt=login on the validated request, then over on your custom user service issue a partial login (from PreAuthN for example).

**Comment by totpero** [comment]
This is what i want, thank you very much.
In PreAuthN  how can i know if i com from my custom request validator, using  AcrValues is OK ? or is other way?

**Comment by brockallen** [comment]
Yes, setting those would be fine.

**Comment by totpero** [comment]
Thank you very much, this solve my problem.
