### ISSUE TITLE
stolen token

### ISSUE THREAD

**Issue by mirac61** [IdentityServer/IdentityServer3#2825]
Hello, I am new oauth and Token Based Authenticaion, I started learn this protocol and authentication type. I am looking at identityserver3 and identity manager. I wonder tokens are enough secure? for example I have logged on identityServer with identity manager and storing token as local storage on my browser. When I copied it and paste another diffrent browser then I have been authenticated. so anybody can steal token and can login his own browser without user name and password. I'm so confused.

**Comment by brockallen** [comment]
That's why it's called a bearer token. If you want something more secure, then look into PoP tokens, which we just released in v2.5: https://github.com/IdentityServer/IdentityServer3/pull/2636

**Comment by mirac61** [comment]
Thank you so much fast answer Brock. I will look PoP tokens now.

**Comment by mirac61** [comment]
Any sample project contains PoP tokens method in your provided samples?

**Comment by brockallen** [comment]
Yes, the ones that say "PoP" in the names.

**Comment by mirac61** [comment]
Your example based WPF, this is necessity? Can I use same this logic on my mvc login application? For example can I transform your IdentityManager sample to PoP tokens? I want make login for my identityManager using this method as a mvc application(not embedded on exe as WPF). And I want make a common login application for all client with PoP token. My clients will be angularJs applications and each have own web apis. I know I asked so many question and maybe not all related to IdentityServer. But I think maybe you can show to me a way.

**Comment by brockallen** [comment]
In our implementation PoP must be used with code/hybrid flow. So between the MVC samples doing hybrid and the WPF samples you could piece the two together to get it working for web style apps.

**Comment by CrescentFresh** [comment]
Does an identityserver `Client` have to be explicitly configured as `Flow = Flows.AuthorizationCodeWithProofKey` or `Flow = Flows.HybridWithProofKey` to be able to exchange a code for a pop token or can I use any client configured as `Flows.AuthorizationCode`/`Flows.Hybrid`?

**Comment by brockallen** [comment]
To use PoP tokens, you need to configure the client for it. That was we can prevent downgrade attacks.
