### ISSUE TITLE
Which flow I need choice

### ISSUE THREAD

**Issue by mirac61** [IdentityServer/IdentityServer3#2826]
Hello again, I am developing an application to a large company. There are question marks in my head for IdentityServer how can I use on authentication server. That is my architecture; I have web APIs resources.(Accommodation, rental, accounting..etc). My client applications are angular applicaiton talking with own resource API).  **My first question which flow I should is that relation. (it be must protected cookie againist attack and stolen token)** . And I have a administration project, that project is a mvc and manage all definitions for API resources(now also my user management in there, I working for move to Identity manager as centralized). **And my second question which flow should use this relation.(it must be very secure to attack, aganist token or cookies vs)** And I will use your IdentitManager for manage my users on IdentityServer. I must do thats with must security.

**Comment by brockallen** [comment]
This has been asked a few times. Did you search the issue tracker history?

https://leastprivilege.com/2016/01/17/which-openid-connectoauth-2-o-flow-is-the-right-one/

**Comment by mirac61** [comment]
Oh sorry! I am at little panic. I over the project deadline :)
