### ISSUE TITLE
Entity Framework Migrations with OperationalData

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#2828]
Hey there,

I want to enable EF Migrations.
I'm following [this](https://identityserver.github.io/Documentation/docsv2/ef/migrations.html) and it works for my Client and Scope Store as I registered them from day 1.

Now I noticed I also have to target the OperationalDbContext.
I tried to add 
`factory.RegisterOperationalServices(operationalStoreConfig);
`
but this has no effect.. maybe because it's already created?
If there is no OperationalService registered, are those configurations in-memory? Or is there a connection string I can use to migrate..?

Thanks..

**Comment by brockallen** [comment]
Wrong repo -- this should be discussed in the EF repo. Please reopen there.
