### ISSUE TITLE
IdentityServer 3 Federation

### ISSUE THREAD

**Issue by Sivalingaamorthy** [IdentityServer/IdentityServer3#2829]
We have a scenario to implement identityserver3, can someone could throw some light on the implementation approach.

Company A has implemented identityserver3, to its application (App 1, App 2).
Company B has implemented identityserver3, exposes API.

Company A application (App 1) want to talk to Company B through the API. App 1 sends the token & token verification url to Company B, the Company B API validates the token using the token verification URL, allows application to access the required data.

I hope my requirement is clear. 

1. What is the best way to make the identity server talk to another identity provider to validate the token.

2. Is there any other things to be considered, when implementing above requirement.

**Comment by brockallen** [comment]
If you want Company's B's APIs to trust Company A's users, then the Company B token service must trust Company A's token service.

**Comment by Sivalingaamorthy** [comment]
Appreciate your immediate response.

1. So If as many companies (X,Y,Z) want to access the API, I need to allow/ask the company B API to trust all those, can be by configuration ! 

2. "Company's B's APIs to trust Company A's users", Will Company B Identity Provider access the users of company A, what this trust mean, how is it used, any reading reference could be helpful ?

3. Do we have any samples (code / documentation) for trusting users &  token service ?

**Comment by brockallen** [comment]
Yes, it's all possible. You need to do the research by reading the docs, the spec, and looking at our samples.

**Comment by Sivalingaamorthy** [comment]
Thanks
