### ISSUE TITLE
Seperated login project, IdentityServer, and mvc clients with SSO

### ISSUE THREAD

**Issue by mirac61** [IdentityServer/IdentityServer3#2830]
Hello, forexample I have IdentityServer as seperated project and on a sub domain. And I have mvc projects on diffrent subdomains. 
My archiceture:
Auth.domain.com(IdentityServer3)
login.domain.com
admin.domain.com
sub1.domain.com
sub2.domain.com
All logins can be only on login.domain.com and the user can surf other subdomains.(with microsoft live or google) and if logout from anywhere must be logout all subdomains. Login view on login project can be specialized for redirect url(like microsoft live, same view but diffrent logo)  And redirect previous url after login. I am currently trying this with MVC OWIN Client (Implicit) flow.  I looked at samples but I don't understand how can I do exactly.

**Comment by brockallen** [comment]
That's not a scenario we directly support. IdSvr must host the login code, unless you do a partial login.

**Comment by mirac61** [comment]
So ok we ignored seperated login project. Can I do my other scenario? When user logged on IdentityServer and will be logged same time other mvc projects ( MVC OWIN Client (Implicit) flow). And when Logged out any project will be logged out identityServer and will be missed access permission all mvc sites. (all site different subdomain). Maybe you can show  a way about that. Maybe it is easy but I so confused.

**Comment by brockallen** [comment]
So I think at this point you need to learn how the SSO protocols work, since you will have the same questions if you use IdSvr or something else.
