### ISSUE TITLE
Identity server 3 customizing web pages

### ISSUE THREAD

**Issue by Nikita2O16** [IdentityServer/IdentityServer3#2831]
Hello,
I'm using Identity server 3.How can I customize the web pages .
I tried to use the defaultViewService and add css file but I can't display the changes!

any suggestion will be appreciated.Thank you

**Comment by brockallen** [comment]
Read the docs: 
https://identityserver.github.io/Documentation/docsv2/advanced/customizingViews.html

Check the samples: 
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/DefaultViewService
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomViewService

**Comment by Nikita2O16** [comment]
Thank you for your reply, I just want  to customize the look of the pages so the defaultViewService customization is what I need to use.
I added this  code in startup.cs      
          ```
 var viewOptions = new DefaultViewServiceOptions();
  viewOptions.Stylesheets.Add("/Content/Site.css");
            viewOptions.CacheViews = false;

            var factory = new IdentityServerServiceFactory();
             factory.ConfigureDefaultViewService(viewOptions);
```
but nothing change!!

**Comment by lukos** [comment]
Did you use that same factory in your ```IdentityServerOptions``` when you called ```UseIdentityServer()```?

**Comment by Nikita2O16** [comment]
first thank you for your reply , I ended up replacing the entire html pages using CustomViewService .

**Comment by Nikita2O16** [comment]
hello, I added layout.html how can I force html pages to use it

**Comment by brockallen** [comment]
_layout.html

-Brock

**Comment by Nikita2O16** [comment]
can you give more details

**Comment by brockallen** [comment]
use the name "_layout.html", not "layout.html"

**Comment by Nikita2O16** [comment]
I did it,s not working

**Comment by Nikita2O16** [comment]
hello, I was wondering if it's possible to change tab title , for example if I click on login button instead of displaying "Submit this form" on the tab like it does now display a site name for example
