### ISSUE TITLE
Store claims before creating an account

### ISSUE THREAD

**Issue by Zenuka** [IdentityServer/IdentityServer3#2832]
Hi,
In our application a UserX must be able to give permissions (claims) to another UserY but it's possible UserY hasn't created an account or hasn't signed in yet through their own identity provider. Is there any functionality in place to handle this? For example create a record in AspNetUsers without a password so that when UserY registers (fills in his name and password) the claims are already assigned? I couldn't find anything which would help me handle this situation.
I'm thinking to store UserY and his claims in separate tables and then copy those when the user actually registers. Or does anyone else have a nice suggestion?

The goal is to invite the user to create an account and immediately after registration, the user has the appropriate rights in all our applications.

**Comment by brockallen** [comment]
You'd have to build this sort of logic yourself.

**Comment by Zenuka** [comment]
Thanks for your quick reply
