### ISSUE TITLE
Entity Framework Operational Data(Claim & Scope)  + Membership Reboot Admin 

### ISSUE THREAD

**Issue by pushpindersingh** [IdentityServer/IdentityServer3#2833]
Identity Server 3 - 
Question: I would like to map the Clients, Scopes and Claims in Entity Framework - (operational data)
with the membership reboot?  membership reboot give you an option to add the user through  /admin route.. 

But how to map  EF Operation data with Users? is there any working sample which uses both EF + membership reboot?  

is there any management screen for EF operational data? 

Thanks in advance !!

**Comment by brockallen** [comment]
Those are all just some tables in a database. Configure them to be the same one if you want.
