### ISSUE TITLE
Upgrading to version 2.5 cause a blank login page

### ISSUE THREAD

**Issue by akiander** [IdentityServer/IdentityServer3#2834]
I'm going to ask this question and then answer it myself, so this is more for documentation than anything else. 

I upgraded to Identity Server 3 version 2.5 and found out that when I navigated to the login page via /core/permissions, **that login page was empty**. No input fields to enter username or password, only the site header and an all white / blank page. 

In our case, we override the default layout file via adding a `/templates/_layout.html` file to our site so that we can adjust the header to match our corporate standards. This is done as documented under the [HTML Customization documentation](https://identityserver.github.io/Documentation/docsv2/advanced/DefaultViewService.html).

At the bottom of the _layout.html page is a script file: 

    <script src="{applicationPath}/assets/scripts.2.0.0.js"></script> 

Notice the version in the file name? Because I had updated to version 2.5, this script was no longer found, so when I changed it to match the new version, everything works now: 

     <script src="{applicationPath}/assets/scripts.2.5.0.js"></script> 

Hopefully this helps someone else.

**Comment by brockallen** [comment]
Yep, this is a good point that perhaps should be doc'd better (somewhere). Thanks.

**Comment by brockallen** [comment]
Opened a doc issue for this.
