### ISSUE TITLE
API method to register users in identityserver3

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3#2839]
Hello,

I have an API proxy that do the rest of my business login, identityserver and Android Client.

I using implicit flow with the android client.

I request an access token from idsrv then make a request including this token to contact with the api and every things works correctly.

Now i want to make an API or any way to register new user instead of the default web page so i can use this apis to create new users from my proxy apis or from my android app.

What is the better way to do that?

I Think IdentityManager https://github.com/IdentityManager/IdentityManager/wiki is the best solution for that but is it still supported as per this question its no longer supported: http://stackoverflow.com/questions/28841166/how-to-use-thinktecture-identity-manager-with-aspnetidentity

I using a CustomUserService with the default AspNet Identity system in my IdentityServer so is the solution will be using IdentityManager? and if so is it any examples on using identityServer with IdentityManager?

**Comment by lukos** [comment]
You pass in the ...UserService when creating the identity server (for instance, using ```UseInMemoryUsers```, which is where you pass your users in. Identity Server does not provide a way to add or remove these users. If you are providing your [own user service](https://identityserver.github.io/Documentation/docsv2/advanced/userService.html) then you will have to implement the creation of new users.

You might instead use one of the pre-built User Services for membershipreboot or ASP.net identity (but I don't know where they are), in which case, you would still have to provide APIs for user creation yourself.

**Comment by brockallen** [comment]
All set on this issue?

**Comment by deserthero** [comment]
yes thanks

**Comment by timmi4sa** [comment]
Hey Brock, we have deployed IdentityServer3 for one of our MVC5 apps. We had connected IdentityServer with the app's AspNetIdentity database per your tutorial, and removed the database connection string from our app. This setup works for our **existing** users. Question: I am not sure how @desethero has resolved this issue but it looks like **new** user registration (or using Login via external services like google) seems like one of the extensibility points that IdentityServer should provide. As Dominic has postulated quite a few times (and on .NET Rocks) "paraphrasing" - uninitiated developers aren't expected to get the security code right, and may/will weaken the whole IdentityServer deployment. Is there a whitepaper or blog that we can use to help provide Register User/Log-in via external service Workflow?

**Comment by brockallen** [comment]
Sorry, I don't have any whitepapers on that, but of course we're available for consulting services to assist with such things.

**Comment by timmi4sa** [comment]
Good to know Brock, thanks for the prompt reply! My team was thinking of possibly contributing to make this feature available for everyone as an opt-in functionality (provided that the feature doesn't go against an overall objective of IdentityServer).

**Comment by brockallen** [comment]
IdentityServer doesn't manage users -- your code would do that, possibly in the same host as IdentityServer, or possibly in a separate app. Feel free to blog about this and we can link to it.
