### ISSUE TITLE
Logging error Request Id

### ISSUE THREAD

**Issue by jackkjhsu** [IdentityServer/IdentityServer3#2840]
Hi,
Is there a way to log the error Request Id as shown below with SeriLog? If so, how can this be done? Thanks

![errorrequestid](https://cloud.githubusercontent.com/assets/5721138/15049842/840300d8-12be-11e6-8300-12a3622c4d7e.png)

**Comment by leastprivilege** [comment]
The event service does that - have you turned on eventing?

**Comment by jackkjhsu** [comment]
Hi Dominick,
I did turn on the `RaiseErrorEvents` from `IdentityServerOptions.EventsOptions` and registered a custom event service through the `IdentityServerServiceFactory.EventService`. The `RaiseAsync` method from my custom event class did fire as follows.
```
    public class CustomEventService : DefaultEventService {
        private static readonly ILog Logger = LogProvider.GetLogger("Events");

        public override Task RaiseAsync<T>(Event<T> evt) {
            if (evt == null) throw new ArgumentNullException("evt");
            JObject jo = JObject.FromObject(evt);
            jo.Add("RequestId", evt.Context.ActivityId);
            var json = jo.ToString(); 
            Logger.Info(json);

            return Task.FromResult(0);
        }
    }
```
As you can see, even though I created a top level property in the json object called RequestId, I could not get the RequestId value piped through to the SeriLog sink. What I ended up doing was adding a custom enricher to the SeriLog's configuration as follows. Do you see any problems doing it this way to output the RequestId to the logging mechanism?

Thanks a lot for your reply, really appreciate it.

From Startup.cs:
```
        public void Configuration(IAppBuilder app) {

            Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .Enrich.With(new RequestIdEnricher())
            .ReadFrom.AppSettings()
            .CreateLogger();
....
```
From web.config:
```
  <appSettings>
    ...
    <add key="serilog:write-to:RollingFile.pathFormat" value="C:\Logs\Log.txt" />
    <add key="serilog:write-to:RollingFile.outputTemplate" value="[{RequestId}] {Timestamp:yyyy-MMM-dd HH:mm:ss.fff} [{Level}] {Message}{NewLine:l}{Exception:l}" />
    <add key="serilog:write-to:RollingFile.restrictedToMinimumLevel" value="Error" />
  </appSettings>
```
RequestIdEnricher:
```
using System.Web;
using Serilog.Core;
using Serilog.Events;
using IdentityServer3.Core.Extensions;

namespace IdentityServerV3 {
    class RequestIdEnricher : ILogEventEnricher {
        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory) {
            string requestId = HttpContext.Current.Request.GetOwinContext()?.Environment?.GetRequestId();

            logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty("RequestId", requestId));
        }
    }
}
```

**Comment by robbaman** [comment]
Hi Dominick,

I hate to comment on a closed issue, but I'm trying to get the id that is shown on the page into the logfile, but am unable to do so. I've added a custom EventService (that just inherits from the Default one, so I can add a breakpoint) and enabled all types of logging on the `EventsOptions` object.

But then when I go to the login url without a signin id (ea https://localhost:44305/login?signin=) I get an error page stating:

> There is an error determining which application you are signing into. Return to the application and try again.
>
> Id: 800027cc-0003-e800-b63f-84710c7967bb

The Id that is shown here is never logged (the breakpoint in my custom EventService is never hit). 

Looking through the IdentityServer3 source code I also can't find any place where the EventService is used in this scenario. Is there a specific purpose for the request id that I'm missing here? I can't see the logic in showing a GUID to an end user without actually storing it in some log.

Thanks in advance.

**Comment by mainettis** [comment]
@robbaman 
It is logged.
It is the ActivityId in the Event's Context
If you look closer through jackkjhsu code you'll see it.
