### ISSUE TITLE
How would one begin to implement login flow for devices?

### ISSUE THREAD

**Issue by benjaminpaul** [IdentityServer/IdentityServer3#2841]
Hi,

We are running Identity Server 3 and have a requirement for devices with limited input capability to authenticate.

This is the same thing as Google for Devices or Facebook Login for Devices:
https://developers.google.com/identity/protocols/OAuth2ForDevices

Would anyone have any idea where I would start implementing this kind of functionality for Identity Server 3?

Thanks

**Comment by h2chch** [comment]
This could be a good starting point:
https://leastprivilege.com/2016/01/17/which-openid-connectoauth-2-o-flow-is-the-right-one/

**Comment by benjaminpaul** [comment]
Thanks, although that link is not relevant as the flow I am requesting help with does not already exist within Identity Server 3.

**Comment by brockallen** [comment]
This is the issue tracking it: https://github.com/IdentityServer/IdentityServer3/issues/2165

In short, we don't have it now.
