### ISSUE TITLE
Overflow of requests to blob.db4prdstr09a.store.core.windows.net from Identity Server

### ISSUE THREAD

**Issue by wmolyneux** [IdentityServer/IdentityServer3#2843]
Hi,

We are using Identity Server V3 and have noticed quite a lot of traffic flowing outbound to the address: 
blob.db4prdstr09a.store.core.windows.net [191.235.193.40] 

When our IT department blocked the requests Identity Server stopped workng but there is nothing indicating this request in the logs.

is there any particular reason for this? is there a way to disable these requests?

**Comment by brockallen** [comment]
What does the traffic look like? When it was blocked, what were the error logs from IdSvr?

**Comment by wmolyneux** [comment]
The traffic was just a request for that page. We had two instances of identity server running locally on two separate machines and both exerted the same behaviour.

As for the logs for the time at which the requests were blocked there is none. The 15 minute block window is clear of logs because it would seem identity stopped running.

We are going to see if we can reproduce this but are slightly concerned why IdSvr is attempting to reach out to the web.

**Comment by leastprivilege** [comment]
I would be concerned as well ;) Never seen that before and I am sure this is not IdentityServer itself.

**Comment by brockallen** [comment]
I agree -- it's odd and not something we're doing.
