### ISSUE TITLE
Angular Material

### ISSUE THREAD

**Issue by Sriram143** [IdentityServer/IdentityServer3#2844]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is It Possible to Use Angular Material instead of bootstrap ? how?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
https://identityserver.github.io/Documentation/docsv2/advanced/DefaultViewService.html

**Comment by Sriram143** [comment]
I ran through that document. and my question is in identityserver3 dll you are embedding bootstrap.js and css files and i dont want those files to be downloaded just remvoe those files and put material design js and css files and dont want ot change any layouts or html layouts. except _login.html and _welcome.html how to do this? i tired to mokeypatching but its not working and i need latest version or angulrajs 1.5.5 in this server how to add those if i add angularjs using the method in documentation i ran into an issue angular is loaded more than once.

**Comment by brockallen** [comment]
You can omit the CSS entirely by clearing the Stylesheets collection on the DefaultViewServiceOptions. As for the JS, we use that for our client-side templating. If you don't want it at all, then you're left rendering all of your own views from scratch.

**Comment by Sriram143** [comment]
Its better to have overriding the scripts and deleting css files feature so that we dont need to override and spend much time on developing our own templates.

**Comment by brockallen** [comment]
>  Its better to have overriding the scripts and deleting css files feature so that we dont need to override and spend much time on developing our own templates.

If IdentityServer were a paid product then I'd agree with you.

**Comment by Sriram143** [comment]
Can i implement this feature and send a PR?

**Comment by brockallen** [comment]
What's the benefit of your CSS framework over what's used now?
