### ISSUE TITLE
Generating encrypted token on Shared hosting environment

### ISSUE THREAD

**Issue by nikhilyk** [IdentityServer/IdentityServer3#2847]
I am attempting to host a web api on a shared hosting and need to generate a token to be served for authenticate the request. In my development environment, I had used the **makecert** option to create the certificate, and had registered it to my local IIS. 

Now how do I create the certificate and register it in a shared hosting environment.

Thank you in advance for any kind of suggestions.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
