### ISSUE TITLE
Redirect URL for android in implicit flow

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3#2848]
hello,

i am now using implicit flow with android and its works well but the redirection url in not the actual what i want.

i put the redirection URL: http:localhost/callback.html but this redirect me to page not found.

i can extract access token and id token but it seems not professional.

So how can i handle the redirect URL for native apps with implicit flow specially android.

**Comment by gustafsonk** [comment]
In Android, you can register a custom protocol for your app so you could use a redirect url that would look something like: myapp://whatever-you-want. This is how professional apps like Twitter and Facebook handle things nicely using urls that look like twitter:// and facebook://

**Comment by brockallen** [comment]
All set on this issue?

**Comment by deserthero** [comment]
yes thanks
