### ISSUE TITLE
Hybrid Flows and Refresh Token for Mobile 

### ISSUE THREAD

**Issue by HaroonSaid** [IdentityServer/IdentityServer3#2849]
Google & Azure both seems to provide the ability to get a refresh token using authorization_code grant without secret for Android &  iOS clients. 

It would be nice if we had the ability disable client secret for specific clients. 

We don't want to write different ways to handling different OpenId Connect Providers, also saying 'not_a_secret' as a secret doesn't feel right, even thou the spec says it is required. 

Ideally it would be nice if Hybrid flow just returned the refresh token too, why bother with another call. 
Can it be achieved with some custom flow?

**Comment by brockallen** [comment]
Our implementation requires client secrets. Sorry.
