### ISSUE TITLE
Question about flows and configuration

### ISSUE THREAD

**Issue by cxbxmxcx** [IdentityServer/IdentityServer3#2850]
We have a Javascript client that uses an existing OAuth token manager to request tokens via resource owner flow.  This works fine and as you would expect with IdentityServerV3.

This is the problematic part:

The javascript client access a number REST endpoints from a proprietary API through a proxy client we have secured with either implicit or hybrid flows with no success.  

The intention is to use a SSO cookie that can be used for REST endpoints since we are unable to modify the client side javascript API that calls those endpoints.

We have tried to generate the cookie after the resource owner flow is authenticated but irregardless continue to get into a redirect loop that then fills the cookie store.

I have read some comments about using resource owner and client credentials flow together but I am not sure how to generate an SSO cookie from that.

Any thoughts, suggestions or samples?

Cheers,

M

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
