### ISSUE TITLE
Feature Request: Separate the Constants

### ISSUE THREAD

**Issue by danda1man** [IdentityServer/IdentityServer3#2852]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Feature Idea
In client applications, I often have to add the entire IdentityServer3 nuget package in order to use the constants class to make sure I am using the correct string values for claim types etc (I would rather have then typed to the constants class than use strings in my application and not know if they change).  This seems a bit odd architecturally in the project to have full references to IdentityServer in client applications, so I was wondering if you had considered breaking out your constants into their own class library/nuget package?  If this is something you would consider, I can create a PR, but I don't want to waste my time if this is something you had thought about before and don't want to do.

**Comment by brockallen** [comment]
Many of these have already been moved out to IdentityModel as constants: https://github.com/IdentityModel/IdentityModel

**Comment by danda1man** [comment]
Ah, guess I have been using the old one without all of these values.  Has everything I really needed, I will assume the token endpoint url won't really change.  I wish nuget would say when a library was depracated...thanks!
