### ISSUE TITLE
Using IdentityServer3 with WebAuthenticationBroker

### ISSUE THREAD

**Issue by payamgerami** [IdentityServer/IdentityServer3#2853]
Hi all,
Has anyone used IdentityServer with WebAuthenticationBroker to implement  SSO in windows universal app (WUP)?

For some reason the broker class decides to POST! to the STS at some point and it does not see the correct redirect (in the form of ms-app://sid#tokens) that is coming from STS.

I can see in the fiddler traces that STS is indeed redirecting to the proper location in the last step:
HTTP/1.1 302 Found
Content-Length: 0
Location: ms-app://s-1-15-2-38.../#code=0bdb86...&id_token=eyJ0eX...&access_token=eyJ0e...&token_type=Bearer&expires_in=7776000&scope=openid%20offline_access%20email&state=xyz&session_state=367wnzhjdQ2r9TiX7sZmQ03y_kjBMKNVVwr6xfuByQ0.cd1e1d29ed153a7b4743bd0f51def6a3

**Comment by brockallen** [comment]
This sample does: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WinRT%20Implicit%20Client

**Comment by payamgerami** [comment]
Thank you so much Brock,
I also just realized that WebAuthenticationBroker **only** works with implicit flow (not 100% sure but based on my experiment).

So now the question is how to renew the token without asking the user to enter his/her credentials?

**Comment by brockallen** [comment]
I don't really know that API -- @leastprivilege  does.

**Comment by leastprivilege** [comment]
Works fine for me - see sample here

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

**Comment by payamgerami** [comment]
Thanks a lot.
This is great.
