### ISSUE TITLE
Oidc-Client typeScript

### ISSUE THREAD

**Issue by yusbel** [IdentityServer/IdentityServer3#2855]
Do we have a sample using angular2 and typescript?

I'm trying to implement the implicit flow using oidc-client and angular2, the code is written using Typescript.

thanks,

**Comment by brockallen** [comment]
We don't have one using Angular. oidc-client was just rewritten in ES6, FWIW. It's marked as beta on npm, but should get officially released in the next week or so.

**Comment by brockallen** [comment]
It was released today: https://github.com/IdentityModel/oidc-client-js
