### ISSUE TITLE
Logout does not work after redirect back from idserver.WindowsAutnetication

### ISSUE THREAD

**Issue by tienw** [IdentityServer/IdentityServer3#2856]
thanks for solving my last question regarding to windows authentication  #2807 

However, now the logout button does not work anymore. The redirect seems not working, the following url (identityserver.windowsauthentication) is where it stopped.

https://localhost:44371/?wtrealm=urn%3aidsrv3&wa=wsignout1.0 

any ideas?

**Comment by brockallen** [comment]
You're using our "WindowsAuthentication" library as an external IdP to IdSvr?

**Comment by tienw** [comment]
Yes.

**Comment by brockallen** [comment]
I doubt that implements signout. Also, since it's windows auth, I'd suggest preventing it from handling signout redirects by canceling it in the event/notification/provider thing.

**Comment by prevolorio** [comment]
I am also running into this redirect issue after using WindowsAuthentication.. would you mind elaborating on what you meant by the event/notification/provider thing @brockallen ?

**Comment by tboyce** [comment]
Adding this to the IdSvr WsFederationAuthenticationOptions seems to work.
```
Notifications = new WsFederationAuthenticationNotifications
                {
                    // ignore signout requests (we can't sign out of Windows)
                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.IsSignOutMessage)
                        {
                            n.HandleResponse();
                        }
                        return Task.FromResult(0);
                    }
                }
```
