### ISSUE TITLE
Client Side Token Validation

### ISSUE THREAD

**Issue by jjordy** [IdentityServer/IdentityServer3#2857]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
What is the preferred method to validate a token in a client side JavaScript app. I can successfully get a token no problem.  When  using the /accesstokenvalidation endpoint and /introspection endpoint it seems cors is turned off. I read on another issue where you said that those endpoints were specifically for server to server communication. My use case is I generate a token and save it to localstorage. and then on a page refresh or new session I check local storage for said token and want to validate that it hasnt expired. Maybe there is something simple here I am missing?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This: https://www.npmjs.com/package/oidc-client
From here: https://github.com/IdentityModel/oidc-client-js

**Comment by jjordy** [comment]
@brockallen Thanks.
