### ISSUE TITLE
IDX10311 Nonce is null

### ISSUE THREAD

**Issue by jgestevez** [IdentityServer/IdentityServer3#2860]
I implemented the solution @doublej42 [did here ](https://github.com/IdentityServer/IdentityServer3/issues/2656), I'm using it for the same scenario as him, however after I redirect to the login screen and the user logs in I'm getting this error

`IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.`

That only happens if I confirm my email using a different browser that the one I used to create a local account which have the nonce cookie saved.

any ideas?

**Comment by brockallen** [comment]
You can't start login in one browser and then complete it in another.

**Comment by jgestevez** [comment]
The thing is that I get logged in, only after IdServer redirects me back to the website I'm getting this exception, however if I refresh the website I get no error and I'm logged in to my website, any idea?

**Comment by brockallen** [comment]
> however if I refresh the website I get no error and I'm logged into my website

Is this because the prior interaction give you a cookie, or is this refresh doing a full round trip to IdSvr, and since you're already logged into IdSvr you're just completing the signin cycle?

**Comment by doublej42** [comment]
My two cents. For the brilliant  @brockallen is right but I thought I might expand on the reason. The nonce is to prevent the replay of the login request. If you don't have all the right cookies your client will not authenticate with the server. 

I don't recal how I fixed it this time but I've done it in two ways in the past.

1. Catch this exeception and force a fresh authentication at the client 

2. Notice the missing cookies on the identity server and send the use back as not authicated forcing your client to try again.

**Comment by jgestevez** [comment]
thanks, I will try catching the exception
