### ISSUE TITLE
IdentityServer3 : GetProfileDataAsync() method is not being called.

### ISSUE THREAD

**Issue by praveenupadhyay20** [IdentityServer/IdentityServer3#2861]
I am new to this concept, gone through below link.

https://identityserver.github.io/Documentation/docs/advanced/userService.html

This method is called whenever claims about the user are requested (e.g. during token creation or via the userinfo endpoint).

But, I don't know what I am missing, GetProfileDataAsync() is not getting called. I have just overridden as below.

public override Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            return base.GetProfileDataAsync(context);   
        }

Note:- AuthenticateLocalAsync method is being called properly. Only problem with GetProfileDataAsync method.

Thanks, 

- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
