### ISSUE TITLE
Tool For Scopes and Clients Management

### ISSUE THREAD

**Issue by markgmarkg** [IdentityServer/IdentityServer3#2862]
Hi,

Previous versions of IdentityServer had a nice tool for all the configurations (e.g. certificates, clients...)
I'm wondering if there is a management application for scopes, clients and other artifacts.

Thank you

**Comment by senj** [comment]
#1976

**Comment by markgmarkg** [comment]
Users management is covered with Identity Manager.
Probably, I miss something, but scopes management is not there (and other configurations)

**Comment by brockallen** [comment]
You're looking for this: https://github.com/IdentityServer/IdentityServer3.Admin

**Comment by markgmarkg** [comment]
Thank you.
