### ISSUE TITLE
Demo Self-Host minimal: Service Unavailable Error 503

### ISSUE THREAD

**Issue by PaxMeCum** [IdentityServer/IdentityServer3#2863]
Hi, 
i`m simply trying to start the SelfHost minimal demo. But when trying to access https://localhost:44333/core or https://localhost:44333/.well-known/openid-configuration via Browser (Chrome) i see the message 

> Service Unavailable - HTTP Error 503. The service is unavailable.

Accessability should be ensured by HTTP Configuration Utility

I enabled all LoggingOptions and -events possible and it seems that the browsers request doesnt even reach the service.

LoggingInformation

> 05/12/2016 10:56:26 +02:00 [Information] {
>   "Category": "Information",
>   "Name": "Signing certificate validation success",
>   "EventType": "Information",
>   "Id": 4012,
>   "Details": {
>     "SigningCertificateName": "CN=idsrv3test",
>     "SigningCertificateExpiration": "2020-01-20T23:00:00+01:00"
>   },
>   "Context": {
>     "TimeStamp": "2016-05-12T08:56:25.8802386+00:00",
>     "ProcessId": 4596,
>     "MachineName": "VMG-DEV10"
>   

> }
> }

**Comment by brockallen** [comment]
Sorry, not really enough info to go on here.
