### ISSUE TITLE
Detecting Token Revocation event

### ISSUE THREAD

**Issue by JohnMcAvinue** [IdentityServer/IdentityServer3#2865]
Hi,

We're using Identity Server 3 with Membership Reboot in an STS that will in future provide authentication for a number of applications. In one particular application that we're currently building we need to execute some business logic on a users account when they have revoked their token.

Ideally, we could detect/handle this event in the STS when we have the subject Id and dispatch an event to our internal event bus where client applications can listen for it if they need to. This way the domain and application specific logic is kept out of the STS application like it should be.

The problem is that Membership Reboot does not have a logged out event, and the calls to [IEventService.RaiseAsync](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/IEventService.cs) method when the token revocation endpoint is called do not provide the subject Id.

Would appreciate any suggestions as to how we can approach this.

Thanks

**Comment by brockallen** [comment]
Token revocation or logout?

**Comment by JohnMcAvinue** [comment]
Revocation

John

**Comment by JohnMcAvinue** [comment]
Just submitted a pull request which introduces a new event to capture when a refresh or access token has been revoked.

https://github.com/IdentityServer/IdentityServer3/pull/2923

**Comment by brockallen** [comment]
Yep, saw it. We'll take a look (most likely next week). Thx!

**Comment by brockallen** [comment]
looks like this was merged in 2.5.3
