### ISSUE TITLE
Redirecting  to login  after log-out

### ISSUE THREAD

**Issue by Vakterman** [IdentityServer/IdentityServer3#2866]
### Question
Hi,

I try to find some way for redirecting  to login page after log-out using identity server (1.4.2 version strictly). It my first experience using Identity Server and i dont' understand som moment.
Please, describe best solution for resolving it.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
