### ISSUE TITLE
IdentityServer requires scope parameter which is not present in OAuth2 request

### ISSUE THREAD

**Issue by lukos** [IdentityServer/IdentityServer3#2869]
```ValidateScopeAsync()``` in ```AuthorizeRequestValidator``` requires the ```scope``` parameter to be present in the request. In the OAuth2 spec ([RFC6749 4.1.1](https://tools.ietf.org/html/rfc6749#section-4.1.1)), ```scope``` is not required and the server is permitted to have default behaviour in this instance.

Although OpenID Connect does require the ```scope``` parameter, ```AuthorizeRequestValidator()``` should not require it to be present and if not, it continues as a normal OAuth2 request.

I have an OAuth2 client that supplies an empty string for scope and this also fails the ```IsMissing``` check..

**Comment by lukos** [comment]
Another issue related to this is that if you pass in e.g. ```scope=email```, the ```AuthorizeRequestValidator``` correctly avoids calling ```request.IsOpenIdRequest = true;``` because it is missing the ```openid``` scope but then further down, there is some logic which says that "email" is an openid scope and therefore the ```scope``` parameter must also include the ```openid``` value.

This is not true in many OAuth2 cases where fairly standard scope names are used that happen to be the same as the openid scopes. I don't see that this adds any additional functionality to the server and could probably be removed.

**Comment by brockallen** [comment]
You have an OAuth2 client -- which API is it trying to use?

In any event, our implementation does require a scope, yes.

**Comment by lukos** [comment]
connect/authorize endpoint. 

Is there any reason to require a scope for non OIC requests i.e. can the code be changed to remove the requirement?

**Comment by brockallen** [comment]
The result of a non-OIDC request is essentially an access token. Those are used to call to APIs. That was my question -- what API do you intend to pass the access token to? 

What I'm trying to do by asking you this is to hopefully make it more clear why we mandate scopes.

**Comment by lukos** [comment]
Oh, OK. Ultimately, it will call the userdata API, as the current system does for OAuth2 but at the moment, my userdata API is serviced by a separate web service so essentially I will only do the serving of the access token and/or ID token from idsrv and then pass the bearer token to the other web service. We do currently support scopes but we don't require them, in which case, it defaults to "email"

Thanks

**Comment by lukos** [comment]
So, if I get time, can I submit a PR to add a config option for "DefaultScope" that must be set if scope is missing? That would presumably be the best of both worlds?

**Comment by brockallen** [comment]
I don't think we want that. It's too presumptuous.

**Comment by lukos** [comment]
Many OAuth2 clients do not provide scope so I think it is the opposite of presumptuous - it is real life and the library in its current state will error if used for pure OAuth2 which will break a load of clients but you understand the problem so if that's your opinion, I will accept that.

**Comment by brockallen** [comment]
What should the default value be then?

If this is really a blocker for you, then put custom middleware in front of IdSvr and on the authorization/token request if you see it's missing then use OWIN and add it.

**Comment by lukos** [comment]
I wouldn't hard-code a default value, I would provide the means to set one. If it is not set in config and also not passed in, it is an error as currently. If it is set to e.g. email in the config and not passed in, it defaults to email. If it is passed in, the passed in value is used.

**Comment by brockallen** [comment]
I still think it's more complicated than that. Is this a global setting? Per-client? Authorization endpoint only? Or token endpoint only? Complexity is the enemy of security, thus my hesitation to add something like this, especially since this is the first time I can remember this being a problem. What's the client library you're using that doesn't allow scopes?

**Comment by lukos** [comment]
I have seen it in wordpress social login (based on HybridAuth). It does
support scope, it just doesn't require it (as per OAuth2 spec) so any
client that does not need to use it will not have it set. OAuth2 allows it
to be set to default per Identity Provider so it would only need setting
once for the whole server. I agree complexity is the enemy of security but
I also like adhering to specs ;-)

**Comment by brockallen** [comment]
OIDC indicates it's required: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by lukos** [comment]
Yes but only if its an openid connect request. In your
AuthorizeRequestValidator, you have:

if (request.RequestedScopes.Contains(Constants.StandardScopes.OpenId))
{
    request.IsOpenIdRequest = true;
}

Which makes me assume that your library is intended to be backwards
compatible with OAuth2 which doesn't require scope.

**Comment by brockallen** [comment]
Well, we'll just have disagree on it then. As I said earlier, you can put in your own middleware in front to add this to the incoming request for your use case.
