### ISSUE TITLE
Custom client_credentials flow

### ISSUE THREAD

**Issue by dariusdamalakas** [IdentityServer/IdentityServer3#2871]
I was halfway through finishing up my issue, but i've figured out the answer, so i'll just post this for reference.

The simplest custom client credentials flow is shown below.  Use `request.Client.Claims` to return extra claims. 
````
public Task<CustomGrantValidationResult> ValidateAsync(ValidatedTokenRequest request)
{
	request.Client.Claims.Add(new Claim("reach", "tenant"));
	return Task.FromResult(new CustomGrantValidationResult()
	{
		IsError = false,
	});
}
````

This access_token is returned:
`{"iss":"https://idsrv3.com","aud":"https://idsrv3.com resources","exp":1463068013,"nbf":1463067653,"client_id":"Subsys-tenantclientcredentials","reach":"tenant","scope":"tenant_client_credentials_client_scope"}`

Hope this is useful.

**Comment by brockallen** [comment]
I don't recall your other issue... but are you just trying to add extra claims for the client? We already have support for that on the Claims collection on the Client configuration.

**Comment by dariusdamalakas** [comment]
Well, we'll want to pass an extra `tenant_id` param to this grant, then validate this against client config / tenant white_list, and depending on that add one ore more claims. 

P.s. please close this, this is not an issue anymore.
