### ISSUE TITLE
IdentityServer as IDP for AWS Cognito

### ISSUE THREAD

**Issue by boyersnet** [IdentityServer/IdentityServer3#2874]
Has anyone integrated IdentityServer as an IDP for AWS Cognito developer identities?  If so, so you have some "words of wisdom" or examples you are willing to share?  I'm not finding much on using a javascript client with ID3 and AWS/Cognito.  I have an EC2 instance running ID3 and the javascript client connected and exchanging tokens.  I have an AWS Federated Identity Pool configured but when connecting to AWS, I'm receiving the following error from AWS.

"Invalid login token. Issuer doesn't match providerName"

TIA!

**Comment by brockallen** [comment]
Nope sorry -- never used them (and apparently no one else has) :/

**Comment by lucasklaassen** [comment]
Hey @boyersnet have you found a solution for this?

**Comment by boyersnet** [comment]
Unfortunately I never was able to get it fully working for my demo project.  Our production project is going a different direction.
