### ISSUE TITLE
How to check for the client of the user from the identityServer itself

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3#2875]
I check the documentation and the OwinMiddleWare Helper methods but i didn't found this info.

In IdintityServer itself say i create a register view to allow users from register.

Now, in the Register Action or in the level of controller, i want to check for the client_id to know from where this user come? 

How can i do that?

**Comment by brockallen** [comment]
When you're redirected to a signin link, an id param is passed. This is the signin ID. There's an OWIN extension to read the signin message from the id.

**Comment by deserthero** [comment]
great i try it and it's works correctly, but what if i want to directly request the registration page without going to the login page first?

**Comment by lukos** [comment]
@deserthero  How would you know whether to go to register or login? Unless the user is already logged in to the IdP, the IdP does not know who the user is and does not know whether they are registered or not.

**Comment by brockallen** [comment]
All set on this?

**Comment by deserthero** [comment]
ys thanks
