### ISSUE TITLE
Determining if a user is a first time login

### ISSUE THREAD

**Issue by richmond-git** [IdentityServer/IdentityServer3#2876]
What would be the best practice method of triggering code directly after a user has been logged in and redirected to the calling application, but only trigger this event once?

Scenario:

- The user accesses the application and they are redirected to identity server login page
- They enter their credentials and are redirected back to the application
- The user is autheticated, but how do we tell if they have just logged into the system for the first time

I was thinking creating a cookie during the SecurityTokenValidated event then deleting that cookie the first time the page has been accessed within the application, is there a better way of achieving the same thing?

**Comment by brockallen** [comment]
I think you have to be more clear on what this means: "they have just logged into the system for the first time".

**Comment by lukos** [comment]
Would needs to know? The Relying Party? If that is the case, it just needs to look for the Identity Provider "subject" being present in the local database. It would only be present after the user logs in for the first time.
