### ISSUE TITLE
WebAPI handling Implicit Flow and Client Credentials Flow

### ISSUE THREAD

**Issue by S3KCentrifugal** [IdentityServer/IdentityServer3#2877]
Hi,

Please consider this a continuation of 
https://github.com/IdentityServer/IdentityServer3/issues/76
https://github.com/IdentityServer/IdentityServer3/issues/67

I'll to make this as simple as possible. I have a WebAPI with multiple Single Page Application clients, using Implicit Flow. WebAPI Controller methods are secured using roles(Which are basically claims) via the [Authorize] attribute.

A new situation has come up where I need to integrate a legacy Oracle Forms 10g application with the WebAPI. The Oracle Application users are not using the Identity Provider so basically any communication from the legacy app to the web api becomes a machine to machine call.

Based on all the documentation I've read the Client Credentials flow is preferred for cases such as this. The problem of course is that clients do not have claims, or in this case roles. If all my methods are secured by roles that becomes a problem.

I've narrowed down my options to...
1. Register the Oracle Application itself as a Client, give the client claims/roles(Which I know you are not a fan of), and use Client Credentials Flow. Oracle Client calls the WebAPI with it's access token.
2. Don't use Client Credentials flow. Instead grant Oracle some kind of long lived user access token.
3. Create new WebAPI methods specifically for handling client calls, to avoid dependency on claims.

Any thoughts? Am I way off in my approach?

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by S3KCentrifugal** [comment]
Here is the corresponding stackoverflow question for reference.
[http://stackoverflow.com/questions/37280538/webapi-mixing-implicit-flow-and-client-credentials-flow](http://stackoverflow.com/questions/37280538/webapi-mixing-implicit-flow-and-client-credentials-flow)
