### ISSUE TITLE
Is it possible to implement SSO using WS Federation for .net 4.0 framework MVC Website?

### ISSUE THREAD

**Issue by pagidigovardhan** [IdentityServer/IdentityServer3#2878]
Hi Brockallen,

I am trying to implement SSO (using identity server WS Federation, let me know if this approach is wrong) my primary application is .NET 4.6.1 MVC application and I am trying to federate another .NET 4.0 MVC application.

I couldn't find the federated related nuget packages for .NET 4.0 framework.

Can you please guide me on this?

**Comment by brockallen** [comment]
Look at the client samples in our repo.
