### ISSUE TITLE
Verifying cache usage

### ISSUE THREAD

**Issue by gilm0079** [IdentityServer/IdentityServer3#2883]
I read up on the cache implementation and added the Redis contrib caching project to our Identity Server project.  I have an API controller endpoint setup so I can query Redis cache for testing.  Do you know how I can verify the IdSvr is storing objects in cache (Redis)?  I tried reusing the ConnectionMultiplexer and searching for the wildcard * and "idscache" (which as far as I can tell is the key prefix).  I'm not getting any results so I wasn't sure if I'm doing something wrong or if the cache implementation is not working.  Any thoughts?

`ICacheManager cacheClient = new RedisCacheManager(cacheConnection);`
`List<string> allKeys = cacheClient.SearchKeys("idscache").ToList();`

**Comment by leastprivilege** [comment]
I never used the redis cache extensions - but what **I** would do is:

* download the source code of the redis cache contrib
* set a breakpoint and see what's going on

**Comment by gilm0079** [comment]
Here is the best way I found to verify the cache effectiveness (in case others are looking to do so as well).  I included the Redis Contrib source project in my solution and tested the client cache.  When a client application hits the IdSvr login page it will then hit the ClientStoreCache's GetAsync and possibly the SetAsync methods.  The current Get function looks like this:

```
public Task<Client> GetAsync(string key) {
    return cacheClient.GetAsync<Client>(key);
}
```

Within here, as is, you can't inspect the return value because it is a un-resolved task at this point.  I just added another synchronous get before this and watched that.  After that I was able to verify that the get result have the Client model object coming back from the Redis cache.

Line added before return that I watched.
`var getResult = cacheClient.Get<Client>(key);`

This worked for testing cache effectiveness in development.  I don't know enough about how the cache is consumed in IdSvr, but I would think from a systems admin view it might be nice if there was somewhere visual or via api that someone could confirm that the cache is working.  

Here is what I found in testing IdSvr against different accessibility states of the Redis cache.  If the Redis cache was powered off when IdSvr started up the StackExchange.Redis.ConnectionMultiplexer would throw an exception.  I had to catch that exception and stop the factory.ConfigureScopeStoreCache registration process otherwise it would crash there as well.  So to keep IdSvr online I chose to not initialize the cache if the Redis cache was unavailable.  I also tested initializing IdSvr then bringing down the Redis cache.  If this happens the IdSvr login page does not show up when the client app requests it.

Would there need to be a timeout added to IdSvr in the ICache implementation to honor a timeout?  Or would this be something that would need to be handled by the cache contrib?  The goal would be after "x" ms (1000ms) making the cache async calls give up in IdSvr.  I'd prefer IdSvr to have a mechanism to stop the request and not trust the cache provider to handle it.  Thoughts?

**Comment by brockallen** [comment]
All set with this? Can we close?
