### ISSUE TITLE
Camel Case for WebAPI output

### ISSUE THREAD

**Issue by dunglp** [IdentityServer/IdentityServer3#2886]
Hi guys,
Hope you are doing well.

Is that possible to change default JsonFormatter to have camel case output for WebAPI ?
I tried to change but it keeps saying that "Authorization is denied for request" when I call the API.

**Comment by leastprivilege** [comment]
which output?

**Comment by dunglp** [comment]
@leastprivilege : I mean the return data of API.


`{
  "StatusCode": 200,
  "Message": "Get data successfully",
  "Status": "success",
  "Data": {
    "SellerProducts": [
      {
        "ItemID": 10,
        "CategoryID": 189
}
]
}`

This is current return data from my api.

**Comment by dunglp** [comment]
@leastprivilege : I have found out the solution. 

```
config.Formatters.Add(new JsonMediaTypeFormatter());
            config.Formatters.JsonFormatter.SerializerSettings =
            new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };
```
