### ISSUE TITLE
Question: How to customise the login journey

### ISSUE THREAD

**Issue by lukos** [IdentityServer/IdentityServer3#2887]
Currently, idsrv is very heavily wired to do ```authorize -> password login -> authenticate```, which is understandable but I really want to customize the process (not the views, which I have already done). We have a non-password (2-stage) login system so ideally we would like ```authorize -> enter email address -> login -> authenticate``` or ```authorize -> login -> 2nd page -> authenticate```

In other words, I could re-purpose your login page to be the first or the second stage in my two stage process but I can't find a way to break the link between authorize and login or login and authenticate.

If I get your login page to post to another controller for the 2nd page, I cannot easily handle validation of the email address, which you do in the ```AuthenticationController``` and which would just render the login page again with the errors if needed - I can't from my controller. There also doesn't seem to be a hook to break the ```AuthorizeEndpointController``` link to the login endpoint to allow calling a page first and *then* to call your login page (customised) but if that was possible, I could use the ```UserName``` and ```Password``` model properties to be compatible with the rest of the process.

Is this possible or planned?

Thanks

**Comment by brockallen** [comment]
You could do partial logins for all of it and completely control everything. We have a sample that might be helpful in getting you started: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomLoginPage/CustomLoginPage

**Comment by lukos** [comment]
Thanks. I will take a look.
