### ISSUE TITLE
How to call userinfo endpoint in WSFederation Authentication Notification 

### ISSUE THREAD

**Issue by pagidigovardhan** [IdentityServer/IdentityServer3#2891]
Hi Domnick,

### Question
How to call userinfo endpoint when Authentication Notification comes, I couldn't find a way to get  Access_token(also Id_Token ) to pass userinfo endpoint?
I am trying to do this way at client side

app.UseWsFederationAuthentication(new WsFederationAuthenticationOptions
            {
                MetadataAddress = idsrv + "/wsfed/metadata",
                Wtrealm = "urn:Test1rp",

                TokenValidationParameters = new TokenValidationParameters
                {
                    ValidAudience = "urn:Test1rp"
                },
                Notifications = new WsFederationAuthenticationNotifications
                {
                    SecurityTokenValidated = async n =>
                    {
                        var nid = new ClaimsIdentity(
                            n.AuthenticationTicket.Identity.AuthenticationType,
                            "name",
                            "role");

                        //TODO: Read Access_token and Id_Token 
                       //TODO: call userinfo endpoint

                        n.AuthenticationTicket = new AuthenticationTicket(
                            nid,
                            n.AuthenticationTicket.Properties);

                    },
                }
            });

**Comment by leastprivilege** [comment]
Userinfo is an OpenID Connect concept - not WS-Federation.
