### ISSUE TITLE
There was an unexpected error ! Please suggest

### ISSUE THREAD

**Issue by Sivalingaamorthy** [IdentityServer/IdentityServer3#2892]
Deployed the application (ids3 host & client) in IIS, I am able to see the login page, I entered the user name and pwd, then on submit, getting error like 

> There was an unexpected error 

(i found the same code was working in local development box, when I deployed the same code in win 2012 server getting these error )

I enabled logs and checked, found below log, can some please suggest, the reason for this error ...

### 

> 
> 2016-05-19 22:57:19.279 +10:00 [Error] Unhandled exception
> System.InvalidOperationException: IDX10614: AsymmetricSecurityKey.GetSignatureFormater( 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' ) threw an exception.
> Key: 'System.IdentityModel.Tokens.X509AsymmetricSecurityKey'
> SignatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', check to make sure the SignatureAlgorithm is supported.
> Exception:'System.Security.Cryptography.CryptographicException: Keyset does not exist
> 
> 
> If you only need to verify signatures the parameter 'willBeUseForSigning' should be false if the private key is not be available. ---> System.Security.Cryptography.CryptographicException: Keyset does not exist

**Comment by leastprivilege** [comment]
This error message means that you either don't have a private key - or no read access to it.

**Comment by Sivalingaamorthy** [comment]
Dominic how is this private key important. I have a certificate that is used for token singing and separate certificate for SSL, where am I missing. Where am I missing, any reference or inputs to understand more this private key.

**Comment by brockallen** [comment]
You can configure the DACL for the cert/private key in the MMC snapin. Right click your cert and choose "manage private keys". I think I might even show this in this video: https://vimeo.com/user28557683/review/149267099/4889e181c4.

**Comment by Sivalingaamorthy** [comment]
Thanks Brock and Dominic, I got the problem resolved. 

I hope this may help some one! The mistake I did was I created new project and I was not using private certificates. This where working in local, but problem surfaced, when it got deployed in the IIS server and when the web client was trying to access the ids3 server.

**Comment by AlexBatura** [comment]
Hi,

I am getting exactly the same error. 
I create X509Certificate2 from the byte array in the source code for IdentityServerOptions and it has a private key.
I use the same certificate file to sign my executables with Authenticode and that works fine.

Please advise
