### ISSUE TITLE
need a "Cook book" or "Recipe"

### ISSUE THREAD

**Issue by figuerres** [IdentityServer/IdentityServer3#2893]
### Question / Issue

Clients, Flows, redirects, scopes .....
I keep stumbling and I think there should be a "simple" path from a to b out there.

for example I see a need for two main items:

1) we are building an AngualrJS application that needs to have users login and have the JS code call rest web api stuff.  which parts does that need so that we can revoke access if needed, so what "flavor" is that ??
2) later we want to have an option for a customer to make an app that calls our system so we need / want to have each customer get a key that identifies them for access to the api but we still need to get an ID of a user for the audit trail of "who did that"

so does an api key really help ? if calls to the api need an authentication that lets the server determin who the caller is that is making the changes to the data ?

I can tell that a lot of good work has been done in this package, but with all the options and the nature of good security being hard to get right it still leaves a bunch of us feeling like we are trying to find a corner in a round room!

**Comment by figuerres** [comment]
I am reading but still lost, which client thing would I use for OpenID Connect on an angularjs client ??

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2016/01/17/which-openid-connectoauth-2-o-flow-is-the-right-one/

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
