### ISSUE TITLE
Different UI themes (login, logout, consent, etc.) based on the client domain

### ISSUE THREAD

**Issue by florindpreda** [IdentityServer/IdentityServer3#2897]
I'm currently implementing SSO with IdentityServer3 and I need to display the UI with different themes based on the client domain. It might be the same client with multiple domains or different clients all together.

What would be the best approach to handle this scenario?

**Comment by vindberg** [comment]
Im also looking into this. Not sure its possible in V3 since the DefaultViewService is loaded in the startup class. @leastprivilege can it be changed dynamically according to clientId?

**Comment by brockallen** [comment]
You can register your custom view service in the DI system to be a delegate. This delegate can resolve the current OWIN environment service and look at  the URL and then decide what instance of your view service to return. Your custom view service could derive from the default one, and can configure it to look in different locations for the view templates.

**Comment by vindberg** [comment]
Hi Brock, thanks for replying. Is there an example of this? I haven't worked with autofac before so unsure how to get IOwinContext registered/resolved in CustomViewService. I have it registered with success like this:

`idSvrFactory.ViewService = new DefaultViewServiceRegistration<CustomViewService>();
`
But how do I register IOwinContext into the CustomViewService class?
```
public class CustomViewService : DefaultViewService
{
	public CustomViewService(DefaultViewServiceOptions config, IViewLoader viewLoader) : base(config, viewLoader)
	{
	}
}
```
Thanks for any guidance.

**Comment by vindberg** [comment]
Nevermind, having read that the UI is .Net Core native in version 4 I will wait with further UI changes until upgrading to V4.

From my point you can close this now.

**Comment by florindpreda** [comment]
Thanks for the suggestions guys.
Fine to close for me as well.
