### ISSUE TITLE
Infinite redirect from external provider to IdSrv when using Idp in acr_values

### ISSUE THREAD

**Issue by chrtsam** [IdentityServer/IdentityServer3#2898]
Hello,
I have implemented OpenId authentication successfully and I have managed to do a login with Office 365 as an external provider. However I have question. In one scenario I redirect the user directly to the external provider, setting the idp in the acr values. The problem i face is that there is an infinite loop  from the external provider to the identity server. Only when i set the idp after the user is authenticated in the `AuthenticateExternalAsync` the flow does not continue to the `redirect url` but it keeps coming to `AuthenticateExternalAsync`

Is there something I am missing?

**Comment by brockallen** [comment]
Yes, you need to make sure you set the `idp` propery/param on the `AuthenticateResult` from your user service's `AuthnticateExternal`.

**Comment by chrtsam** [comment]
Ok, thanks. It worked!
