### ISSUE TITLE
Question: Multiple Custom User Stores

### ISSUE THREAD

**Issue by ecardinal40** [IdentityServer/IdentityServer3#2900]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I cannot find a clear answer looking through the documentation, examples, or questions on the site - if I am incorrect please direct me to the response.  In the title I said User Store I really mean User Repository.

My question is this:

Can I inject the user repository based client id?

Example 1 (different domains):

www.fakesite.com (client id: foo) --> contacts the sts to authenticate a user and based on foo it uses repository  X.

www.fakesight.com (client id: boo) --> contacts the sts to authenticate a user and based on boo it uses repository  Y.  

Example 2 (same domains):

www.fakesite.com (client id: zoo) --> contacts the sts to authenticate a user and based on zoo it uses repository  X.

www.fakesite.com (client id: goo) --> contacts the sts to authenticate a user and based on goo it uses repository Y. 

Is this possible?  If so can anyone direct me to an example of how I would accomplish it.  If it is not possible can someone give me a quick lesson on why it is not possible.

I would think in the startup you may be able to inject the multiple repositories here:

`factory.UserService = new Registration<IUserService>(typeof(CustomUserService));
 factory.Register(new Registration<IUserRepository>(userRepository));` 

but then again I may be completely wrong.

I have also thought well - I could just not register a user repository and then just write a helper function in the UserService class and in the AuthenticateLocalAsync method - where I first get the context - I could, based on client id, get the correct repository.  Would this be a horrible approach?

Thanks again and if I just flat out missed the answer to this somewhere in site or docs - I am sorry.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
You can always put a factory in DI and the factory can dynamically connect to the right repository.

**Comment by ecardinal40** [comment]
@brockallen Thank you for the response, that makes more sense to inject it.  To extend this a bit more and not to be too much of a pain.  Is it possible to make the same kind of a decision for User Store?  Decide which user store you use based on clientId.  

I saw this answer you posted in another question string.  Sorry I did not see this before but I am trying to cover all scenarios where the requirement may be we need user store to be based on clientId not just repository.

> Yes, if you have multiple DBs then you can either abstract them in your one user service, or depending on your scenario it might be possible to have different user service implementations that you can dynamically inject them into DI using the callback approach with the Registration class.

But it does not appear that the clientId is available there - it looks like (my ignorance) that the clientId first becomes available in the AuthenticateLocalAsync method.  Is that true?  Where is the first place clientId becomes available so I could inject the user store I want to use?  Do I need to override some other function somewhere?  Maybe this is simple...and I am making it too hard.

Thank you again.  You have been really helpful.

**Comment by ecardinal40** [comment]
I am guessing the only way to do this is by building a project from the source and in the AuthenticationController injecting the user service through a factory in the controller.  Is this correct?  I would not attempt to override the AuthenticationController, would I?  I don't think that last one would even work.

**Comment by brockallen** [comment]
The various APIs on the user service have the client id param. You can use those to then connect to the right DB.

**Comment by ecardinal40** [comment]
@brockallen Ok cool that seems to answer the question.  Thank you.

**Comment by DoubleExposure** [comment]
@ecardinal40 Did you resolve this? Can you share? We have the same goal as you do. Thanks

**Comment by crogle** [comment]
Same question...would you share how you set this up?
