### ISSUE TITLE
ids not persisting auth code or access tokens..

### ISSUE THREAD

**Issue by sudipster** [IdentityServer/IdentityServer3#2901]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Using entityframework for ids.  I have the following configuration for ids service factory.  However, only token that seems to be stored in Tokens table is refresh tokens.  Am I missing something so ids can start persisting tokens to sql server?

            var factory = new IdentityServerServiceFactory();
            factory.RegisterConfigurationServices(efOptions);
            factory.RegisterOperationalServices(efOptions);
            factory.RegisterScopeStore(efOptions);

            factory.ScopeStore = new Registration<IScopeStore, ScopeStore>();
            factory.ClientStore = new Registration<IClientStore, ClientStore>();

            factory.AuthorizationCodeStore = new Registration<IAuthorizationCodeStore, AuthorizationCodeStore>();
            factory.TokenHandleStore = new Registration<ITokenHandleStore, TokenHandleStore>();
            factory.RefreshTokenStore = new Registration<IRefreshTokenStore, RefreshTokenStore>();
            factory.ConsentStore = new Registration<IConsentStore, ConsentStore>();

            factory.UserService = new Registration<IUserService>(typeof(MyUserService));

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
The `RegisterXxx` extensiono methods are already setting the various stores on the factory. Setting them again after overwrites them. Perhaps this is why you're not seeing the EF ones being used?

**Comment by sudipster** [comment]
@brockallen, I actually first tried without setting auth code, token, refresh token, consent stores. Same result.

**Comment by brockallen** [comment]
Also, depends what features in IdSvr you're using. If you're using JWts, then they're never stored. Our docs cover this.
