### ISSUE TITLE
Question: How to change request path correct in AspNetIdentity sample project

### ISSUE THREAD

**Issue by billgrow1972** [IdentityServer/IdentityServer3#2902]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question 
Running the AspNetIdentity sample project. I noticed that I recieve 404 errors whenever I attempt to alter the path from the base path (ex http://localhost:44333/admin vs http://localhost:44333/tstsrvr/admin). Additionally, I changed to the Startup class to use app.mapwhen instead of app.map using the existence of the strings "core" or "admin" in the path and get the same 404 error in iisexpress when running the project in visual studio 2015. The project runs fine as is but I am wondering why there appear to be issues when the path is different or when the startup class is changed to mapwhen vs map. If I am missing something obvious please delete this question.

               app.MapWhen(context => context.Request.Path.ToString().Contains("/core"),
                core =>
                {
                    var idSvrFactory = Factory.Configure();
                    idSvrFactory.ConfigureUserService("AspId");
                    //idSvrFactory.ConfigureCustomUserService("AspId_CustomPK");

                    var options = new IdentityServerOptions
                    {
                        SiteName = "IdentityServer3 - UserService-AspNetIdentity",
                        SigningCertificate = Certificate.Get(),
                        Factory = idSvrFactory,
                        AuthenticationOptions = new AuthenticationOptions
                        {
                            IdentityProviders = ConfigureAdditionalIdentityProviders,
                        }
                    };

                    core.UseIdentityServer(options);
                  }

**Comment by brockallen** [comment]
Not sure. Any progress?

**Comment by billgrow1972** [comment]
Hi Brock. I was unsuccessful. I the end I needed to get client testing completed so I left the sample in its own site. I am sure there is a trick to make it work. Samples work great in their own sites both MR and Identity.

**Comment by brockallen** [comment]
So `MapWhen` is not the answer. I'd discourage its use.

Do you have RAMMFAR enabled? Compare the working samples to what you have.

**Comment by billgrow1972** [comment]
Hi Brock,
  Yes RAMMFAR was enabled in the default project. I ran  across a response to a similar question from Dominick from over a year ago. If I understood the answer correctly, then it seemed that at least the samples were set up to have identityserver3 deployed at the root of a website and not a subpath.  I am trying to locate it again and have been digging for about a 1/2 hour. There is so much that you guys have been doing that trying to find a single post is like looking for needle in a stack of needles.

**Comment by brockallen** [comment]
I normally suggest starting with the working samples, and then copy piece by piece over to your app to get an understanding of it all. Or you can come to one of out workshops and we can show it all from the ground up :)

**Comment by brockallen** [comment]
All set with this? Can we close?

**Comment by billgrow1972** [comment]
Yes. I don't believe the sample projects are designed to work this way. Thank you.
