### ISSUE TITLE
Unexpected character encountered while parsing value: W. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by falconmick** [IdentityServer/IdentityServer3#2903]
Hey guys!
Found out about your logger and oh boy did that solve all my problems.. until this one...

```
iisexpress.exe Information: 0 : 2016-05-21 18:52:21.873 +12:00 [Information] Creating Implicit Flow response.
iisexpress.exe Information: 0 : 2016-05-21 18:52:21.955 +12:00 [Information] Getting claims for identity token for subject: b7bdec7a-6165-4109-8193-932af1350449
iisexpress.exe Error: 0 : 2016-05-21 18:52:25.801 +12:00 [Error] Unhandled exception
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: W. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
   at Newtonsoft.Json.JsonTextReader.Read() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType) in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in
... bubbles up about a miles worth of logging, so I've removed the stuff after (can repost it)
```

I have dotpeek installed so I opened up where it's happening and strangly it's happening here (I don't see any json stuff here :s)

ClientListCookie.cs ( GetCookie(); is the issue)
```
 public IEnumerable<string> GetClients()
 {
     var value = GetCookie();
     if (String.IsNullOrWhiteSpace(value))
     {
         return Enumerable.Empty<string>();
     }
     return JsonConvert.DeserializeObject<string[]>(value, settings);
 }
```

I tried loading the json assemblies into dotpeek but for some reason I cannot get VS to show me the JSON disassembly :(

If it at all helps, here is my Client and the URL I use to start the Implicit flow:

```
new Client
{
         ClientName = "JS Client",
         Enabled = true,

         ClientId = "implicitclient",
         Flow = Flows.Implicit,

         RequireConsent = true,
         AllowRememberConsent = true,

         RedirectUris = new List<string>
         {
             "http://localhost:3000"
         },

         AllowedScopes = new List<string>
         {
             "openid", "profile", "email", "api"
         }
}
```

and the URL my JS uses decoded:

```
https://localhost:44333/core/connect/authorize
?response_type=id_token token
&client_id=implicitclient
&state=BAuMZGqDh1IQumgHFnNc6PeVH3fMXJe5BGny9Uxr
&redirect_uri=http://localhost:3000
&scope=openid profile api
&nonce=BAuMZGqDh1IQumgHFnNc6PeVH3fMXJe5BGny9Uxr
```

Any clues? sombody much earlier had a [similar problem](https://github.com/IdentityServer/IdentityServer3/issues/2226) which is why I've removed email from my scope. But I think that that isn't what you ment (but I tried it anyway)

Well anyway, I'm stumped.

Help me Obi-Wan- @brockallen  or @leastprivilege, your my only hope!

**Comment by falconmick** [comment]
```

                    new Scope
                    {
                        Name = "api",
                        DisplayName = "Api Access",
                        Type = ScopeType.Resource,
                        Emphasize = true,
                        ShowInDiscoveryDocument = false,

                        Claims = new List<ScopeClaim>
                        {
                            new ScopeClaim(Constants.ClaimTypes.Name),
                            new ScopeClaim(Constants.ClaimTypes.Role)
                        }
                    }
```

**Comment by falconmick** [comment]
Turns out I can find out what the value of the GetCookie() response is as it is crashing on the string.IsNullOrWhiteSpace(value)

The value is: WyJtdmNfaW1wbGljaXQiXQ
Which didn't match any of the strings in my OpenId connect request AND I cannot find reference to it in any of my source files.

Hope that helps

**Comment by falconmick** [comment]
My Request (as seen inside of AuthorizeEndpointController.CreateAuthorizeResponseAsync)

```
{IdentityServer3.Core.Validation.ValidatedAuthorizeRequest}
    AccessTokenRequested: true
    AuthenticationContextReferenceClasses: Count = 0
    Client: {IdentityServer3.Core.Models.Client}
    ClientId: "js"
    CodeChallenge: null
    CodeChallengeMethod: null
    DisplayMode: null
    Flow: Implicit
    IsOpenIdRequest: true
    IsResourceRequest: false
    LoginHint: null
    MaxAge: null
    Nonce: "gizBmUupItclwQioT2675vgUUXFCaTvHcysRzsXf"
    Options: {IdentityServer3.Core.Configuration.IdentityServerOptions}
    PromptMode: null
    Raw: {System.Net.Http.Formatting.Internal.HttpValueCollection}
    RedirectUri: "http://localhost:3000/index.html"
    RequestedScopes: Count = 2
    ResponseMode: "fragment"
    ResponseType: "id_token token"
    SessionId: "9c29a002258dc68febfd7cbd65486885"
    State: "gizBmUupItclwQioT2675vgUUXFCaTvHcysRzsXf"
    Subject: {System.Security.Claims.ClaimsPrincipal}
    UiLocales: null
    ValidatedScopes: {IdentityServer3.Core.Validation.ScopeValidator}
    WasConsentShown: false
```

**Comment by falconmick** [comment]
More developments. I imported the IdentityServer3 Source into my project (to make debugging easier, dotpeek is amazing, but it's not perfect) And turns out, it was the deserialize call at the bottom of the function.

Once I noticed this, I changed the value to be null, so it would invoke the path of code execution where the cookie wasn't there (I thought hey, that should be fine, of which it was) and then my other breakpoint on the setcookie came up with gold.

It's value was a json serialised string which had my client id in it. So turns out the issue was that I had a bad cookie, but how? Thats where I leave this question to anyone who's smarter than me.

**Comment by brockallen** [comment]
Hmm, ok. thanks for the info. I'll assign to @leastprivilege  since he's the PM for logging.

**Comment by leastprivilege** [comment]
@brockallen How is that logging related if it happens in GetCookie() ??

**Comment by falconmick** [comment]
@leastprivilege were you able to reproduce? The issue wasn't that GetCookie caused the exception, it was returning bad data as my cookie somehow had other data in it, which was then trying to be serialised which caused the exception.

**Comment by leastprivilege** [comment]
can you repro?

**Comment by tommabear** [comment]
I had same issue today. My bad "idsvr.clients" cookie was "WyJqc0NsaWVudCJd", which should be a JSON string like "["jsc1"]". I temporarily fixed it by clearing all the browser history. I was using the new "oidc-client.js" script, is that related?

**Comment by leastprivilege** [comment]
@brockallen interesting - we will look into that

**Comment by brockallen** [comment]
`WyJqc0NsaWVudCJd` is `[&quot;jsClient&quot;]` base64 encoded. so the question is why is that cookie getting double encoded?

**Comment by brockallen** [comment]
I guess we can manually encode the JSON ourselves to prevent this... my only concern would be running clients cookies would then be invalid. We'd have to catch failed parsing, and/or deal with 2 formats.

**Comment by brockallen** [comment]
So just for the record, I don't think this is a bug in IdSvr. I think something somewhere else is doing an additional encoding on the outbound cookie value. Ideally I'd really appreciate it if @falconmick could try to dig into it a more and see if there's something environmental involved. 

In the meantime, I submitted a PR to manually encode and gracefully deal with with existing cookies that are not encoded. Please have a look.

**Comment by brockallen** [comment]
merged.
