### ISSUE TITLE
Variable Cookie Expiry Based on User/External Provider

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#2905]
Hi,

In our implementation of IdentityServer we have multiple clients that use our applications. Some of those clients wish to have persistent cookies with differening expiry times. 
Is it possible to change the expiry time and if the cookie is persistent/session based on the user that's logged in or by the External Provider that they're logging in with. 

Also, is there a way to set my own claims after the user has logged in. For example, I would like to store the external provider the user logged in with so that it can be passed back to the Relying Party.

**Comment by brockallen** [comment]
> Also, is there a way to set my own claims after the user has logged in. 

The `AuthenticateResult` has a claims ctor param for this purpose.

**Comment by brockallen** [comment]
> Is it possible to change the expiry time and if the cookie is persistent/session based on the user that's logged in or by the External Provider that they're logging in with. 

The OWIN extension `IssueLoginCookie`: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html.

**Comment by parkinsona** [comment]
Thanks for the info.
Looks like I can modify the AuthenticateResult in AuthenticateLocalAsync & AuthenticateExternalAsync methdods of the UserService. 
Could I also do this by overriding GetClaimsFromAccount? I currently override this to return linked account claims.

I had looked at the OWIN extension, but wasn't sure where I would tell idsvr to use that instead of the normal one. Perhaps I missed the point of the extension, would it override the default issuing of the cookie?

**Comment by brockallen** [comment]
The extension would overwrite the previously issued cookie... but generally the user service result is used to gen the cookie... so it will be too soon in the user service (now that I think about it).

GetClaimsFromAccount is called from different contexts so I'd not do it there.

I don't have a great answer for you on this one... you'd have to completely replace the entire login UI and build all custom partial views for all of it.

**Comment by parkinsona** [comment]
Thanks again Brock. After discussing the options with a colleague, we think it makes more sense to force the RP to manage variable sessions in our situation. It sounds like it would be a lot easier for them to do it on their end as well, rather than customizing Idsvr's cookie issuing.
