### ISSUE TITLE
double exception logging 

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#2906]
Hello,

I've noticed that some of exceptions are logged twice. After short investigation I found that you log exception and pass it thorugh in ErrorPageFilterAttribute and it is also logged in IExceptionLogger. Shouldn't you mark it as handled somehow and prevent it from logging twice? you already handle it by logging and displaying error page.

i.e throw an exception in AuthenticateLocalAsync method. I've got it twice in logs:

IExceptionLogger:
`2016-05-23 13:27:39.6471 ERROR Unhandled exception 
 System.NotImplementedException: The method or operation is not implemented.`

ErrorPageFilterAttribute:
`2016-05-23 13:27:39.7211 ERROR Exception accessing: /login 
 System.NotImplementedException: The method or operation is not implemented.`

**Comment by brockallen** [comment]
I think it depends on where the exception is raised, and the ErrorPage filter won't know the source.

**Comment by pawepaw** [comment]
But it's misleading when analyzing logs. You can always add request data (path etc.) so source will be logged.

**Comment by brockallen** [comment]
Well, analyze all of the source in IdSvr and propose a solution or a PR to always get exactly one error in the logs regardless of all the log settings :)

**Comment by pawepaw** [comment]
Sure I understand that's global problem but it depends what information you add into exception. In this case it's only path and it can be handled globally. 

After short code analyze I think that removing logging exception from ErrorPageFilterAttribute and adding path information if exist in IExceptionLogger would be enough but i may miss something. 

I didn't find any other places in which you log exceptions and pass them through so if you want I can make pr with it.

**Comment by brockallen** [comment]
Ok, I"ll mark this as enhancement for now to track. No time in the immediate future tho.

**Comment by pawepaw** [comment]
Think that would be enough.

**Comment by brockallen** [comment]
thx, i'll take a look when i can. it won't be for at least a week tho.

**Comment by brockallen** [comment]
done
