### ISSUE TITLE
Ids3 with Angularjs

### ISSUE THREAD

**Issue by Sivalingaamorthy** [IdentityServer/IdentityServer3#2907]
I just want to hear from you, whether there is any samples / example that connects to Id3 with Angular Js (like odic_client.js) using the client controller / service . I did some research but unsuccessful, can you provide some reference if any !

The other way, am thinking is to use Js (odic_client.js) + AngularJs ... any other recommendations?

**Comment by brockallen** [comment]
No specific NG samples -- we have JS samples and it's up to you to know how to map to your JS framework.

**Comment by S3KCentrifugal** [comment]
I'm using a modified version of this library...
[https://github.com/JamesRandall/AngularJS-OAuth2](https://github.com/JamesRandall/AngularJS-OAuth2)

Works quite well. It should work right out of the box.

**Comment by Sivalingaamorthy** [comment]
Hi S3KCentrifugal,

Can you please specify what are the things you modified ? This may help me and others.

Thanks,

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
