### ISSUE TITLE
Possible implementation of OAuth2 impersonation

### ISSUE THREAD

**Issue by dzintaras** [IdentityServer/IdentityServer3#2908]
Hi,

what are your thoughts on https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-04
I know it's a draft and 4th version looks quite different from previous one (although haven't read it thoroughly yet) but we need some kind of impersonation so before jumping to implementation it would be nice to hear your voice regarding the possible standard and if/when it could find it's way into IdentityServer

**Comment by brockallen** [comment]
You can essentially already do this with a custom grant validator. But sure, at some point we might decide to make this formally supported -- depends on the trade off of work compared to just making a custom grant validator.

**Comment by brockallen** [comment]
BTW, i think we even already have custom token exchange samples.

**Comment by dzintaras** [comment]
OK thought so. Thanks for clarification
