### ISSUE TITLE
How user can manage own IdSvr account?

### ISSUE THREAD

**Issue by neTp9c** [IdentityServer/IdentityServer3#2910]
By manage i mean:
- register
- restore password
- change password
- edit personal info
- and so on

Should this functionality be on the same application or it should be on another one?

I can reproduce creation of the register page from CustomUserService sample where that page exists in same app that IdSvr is. But when i try to add yet another page (controller action) for editing personal info that user who is authenticated on IdSrv seems not authenticated inside my custom controller. And i can't understand why that happens.

Base url of IdSvr is "/" and url of my controller is "/edit". Inside my custom controller I can get user info by calling GetIdentityServerFullLoginAsync() on Environment dictionary. But i would like to use native .net authorization mechanism but User.Identity.IsAuthenticated is always false. I am just looking on ClientPermissionsController inside IdSvr and see that it uses User.Identity.IsAuthenticated and it works there. I cannot figure it out why this doesn't work for me?

I just stuck and will appreciate any advice.

**Comment by brockallen** [comment]
That's functionality you need to build in some user management app. Normally it's separate and it can write to the same DB IdSvr uses for users.

**Comment by neTp9c** [comment]
Thanks for your reply. It would be simpler for me to build independent management app. I will try it.
