### ISSUE TITLE
TokenRequestValidator logging causes token Validation to fail

### ISSUE THREAD

**Issue by fuzzlebuck** [IdentityServer/IdentityServer3#2911]
When issuing tokens LogEvent("Token request validation success") is called once the token has been successfully validated.

The LogEvent method then attempts to include the validated request object as a JSON string at which point the string.format fails with a "Input string was not in a correct format." FormatException.

This is because the JSON string contains braces { and therefore fails to format, the JSON string needs to be escaped with double braces {{ for every brace {.

The issue exists in https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/TokenRequestValidator.cs on line 915.

A quick fix is to replace:

```
private Func<string> LogEvent(string message)
{
    return () =>
    {
        var validationLog = new TokenRequestValidationLog(_validatedRequest);
        var json = LogSerializer.Serialize(validationLog);

        return string.Format("{0}\n {1}", message, json);
    };
}
```

With:

```
private Func<string> LogEvent(string message)
{
    return () =>
    {
        var validationLog = new TokenRequestValidationLog(_validatedRequest);
        var json = LogSerializer.Serialize(validationLog);

        return string.Format("{0}\n {1}", message, json.Replace("{", "{{").Replace("}", "}}"));
    };
}
```

**Comment by leastprivilege** [comment]
This does not happen always, otherwise token validation would never work? Did you work out what the exact error scenario is?

**Comment by fuzzlebuck** [comment]
I apologise, I've just spend the afternoon attempting to recreate the issue and I've found that the error was actually in my implementation of the ILogProvider, I was attempting to format the full message including the parameters into a single line for my final log like so:

```
Logger ILogProvider.GetLogger(string name)
{
        return (logLevel, messageFunc, exception, parameters) =>
        {
                if (messageFunc == null) return true;

                var message = string.format(messageFunc.Invoke(), parameters);

               ...
        }
}
```

But because the TokenRequestValidator had already formatted the message to include a json object my string format was failing.

It's still useful to have the TokenRequestValidator json output message double escaped as the messageFunc may return the parameters and an unformatted string such as 'some message {0}' separately which need to be combined on the final log output.

But I'm sorry for the red herring.

**Comment by leastprivilege** [comment]
I removed the formatting altogether.
