### ISSUE TITLE
Redirect Loop in SecurityTokenValidated

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#2912]
My open id client was working fine with one problem. After logout, user is not redirected to the web page. After search, I added these lines of code(PostLogoutRedirectUri and RedirectUri is same as client website url),

```
    var options = new OpenIdConnectAuthenticationOptions
    {
        Authority = AppSettings.Authority,
        ClientId = AppSettings.ClientId,
        Scope = AppSettings.Scope,
        ResponseType = AppSettings.ResponseType,
        RedirectUri = AppSettings.RedirectUri,
        SignInAsAuthenticationType = AppSettings.SignInAsAuthenticationType,
        UseTokenLifetime = false,
        PostLogoutRedirectUri = AppSettings.PostLogoutRedirectUri,

        Notifications = new OpenIdConnectAuthenticationNotifications()
        {
            SecurityTokenValidated = async n =>
            {
                var nid = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType,
                    ClaimTypes.GivenName
                    ,ClaimTypes.Role);

                // get userinfo data
                var userInfoClient = new UserInfoClient(
                    new Uri(n.Options.Authority + "/connect/userinfo"),
                    n.ProtocolMessage.AccessToken);

                var userInfo = await userInfoClient.GetAsync();
                userInfo.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Item1, ui.Item2)));

                // keep the id_token for logout
                nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));

                // add access token for sample API
                nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));

                // keep track of access token expiration
                nid.AddClaim(new Claim("expires_at", DateTimeOffset.Now.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToString()));

                // add some other app specific claim
                nid.AddClaim(new Claim("app_specific", "some data"));

                n.AuthenticationTicket = new AuthenticationTicket(
                    nid,
                    n.AuthenticationTicket.Properties);

            },
            RedirectToIdentityProvider = n =>
            {
                if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                {
                    var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                    if (idTokenHint != null)
                    {
                        n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                    }
                }
                return Task.FromResult(0);
            },
        }


    };
    app.UseOpenIdConnectAuthentication(options);
```

But when user log-in the redirect loop started.If I put breakpoint in SecurityTokenValidated, then system is calling this method. Means after every redirect loop,  SecurityTokenValidated is called. If I comment these events then logout not work as expected.

**Comment by brockallen** [comment]
Does that URL require an authenticated user? IOW, after logout you get sent back and then the user is required to login again immediately?

**Comment by abcplex** [comment]
What I am doing is simple. User click a link which has [Authorize] attribute then after login I get the above behaviour. PostLogoutRedirectUri and RedirectUri does not required login. It works without the above events.

**Comment by brockallen** [comment]
Not sure what the problem is. I'd suggest looking at our working samples and comparing your code to them.

**Comment by abcplex** [comment]
I fixed it using,

`userInfo.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Item1 == "role" ? ClaimTypes.Role : ui.Item1, ui.Item2)));`

But still when LogOff, Identity-Server is not redirecting to the site? @brockallen  do you know any hint, I am getting,

**Logout You are now logged out**

**Comment by brockallen** [comment]
Open a new issue for new problems, please.

**Comment by abcplex** [comment]
@brockallen but why your /connect/userinfo endpoint returns _role_ instead of _http://schemas.microsoft.com/ws/2008/06/identity/claims/role_ Also why its looping back and forth from IdSvr to client if user logged-in but missing a role or claim(which controller require).

**Comment by brockallen** [comment]
The OIDC claims are defined here: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by brockallen** [comment]
As for redirect I suspect it's an authorization problem.

**Comment by abcplex** [comment]
@brockallen I see there is no role claim. But try to understand my redirect loop problem. The claims inside n parameter (param of SecurityTokenValidated) includes the correct role and name claim key (which .Net Principal classes uses(IsInRole and Name)). But  userInfoClient.GetAsync not. Is UseOpenIdConnectAuthentication is not following the stranded?

In my controllers I have, 

`[Authorize(Role="XXX")]`

That's why adding the above check fixes the problem.
