### ISSUE TITLE
IAuthenticationSessionValidator with partial login

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#2913]
Related to issue #2148, when adding a custom claim for later validation, and then partial login flow kicks in, I seem to lose this information (along with other claims I initially add) after partial login has been completed. How and at what point should these be added in order to again be available after partial login completion?

Thanks

**Comment by brockallen** [comment]
Partial login claims are in a diff cookie than the main authentication cookie. So #2148 would not know anything about the partial claims. If you want additional claims in the main authentication cookie add them as the `claims` param on the `AuthenticateResult` from your user service.

**Comment by snothub** [comment]
Yeah, I am aware of idsrv.partial cookie. But the additional claim for session validation should be in the main cookie, right? I must be missing something here, so please have a look at the flow and correct me:
- in IUserService.AuthenticateLocalAsync, user is authenticated, all claims set
- in IUserService.PostAuthenticateAsync, there is a ClaimsPrincipal with all the correct claims, but because of 2FA -> `context.AuthenticateResult = new AuthenticateResult("/twofactor", id, name)`
- entering 2FAController Get, `authentication = await Request.GetOwinContext().Authentication.AuthenticateAsync("idsrv.partial");`
- posting to 2FAController, `user = Request.GetOwinContext().Environment.Authentication.AuthenticateAsync("idsrv.partial")`
- entering IUserService.PostAuthenticateAsync again after partial login, I see only 5 claims on the ClaimsPrincipal (sub, name, idp, auth_time, amr). **Here I am missing lots of claims set in the first step**

**Comment by brockallen** [comment]
Ah, ok, that's a slightly different workflow. I think in your PostAuthN once you're back from the partial you will have to add more claims to the AuthenticateResult that PostAuthN is producing. When we return from a partial login IIRC we only carry over the core claims we know about from the partial cookie.

**Comment by snothub** [comment]
That's what I've been trying to figure out, how to invoke IUserService to give me what I need. Looks like I have to do the whole fetch operation from the store all over again, it seems to be working now. Great stuff. See you soon in Oslo, looking forward to it...
