### ISSUE TITLE
user info question / problem

### ISSUE THREAD

**Issue by figuerres** [IdentityServer/IdentityServer3#2914]
I made a post on stak overflow but no reply yet so I will link here and ask:
https://stackoverflow.com/questions/37396409/canot-call-userinfo-due-to-invalid-scope-error

I can use the /token endpoint to authenticate / login / get a token.
now I want to get the data from the /userinfo  but it returns an error that I do not have the right scope.
tried some things to add scopes to my client and to my login but that also does not seem to work.

I am going to attach the source to my web app and try to step into the code in hopes that it will show me what I am doing that is wrong.
but some help will be good.

I am still learning this , I fixed some early errors.
 the goal is to have an angular js client app use the web app for WebAPI and Odata access first.
later we want to grant some apps access with some kind of "API KEY"  possibly.

I have asp.net identity setup and using int keys, I did that before I added identity server.
identity server is using my identity store.

I also added the ef store to allow identity server to store tokens and other settings but I think that might not be working right as I do not see any rows added to the token table after I get a token.

```

**Comment by brockallen** [comment]
Closing since you have traffic on the SO link.
