### ISSUE TITLE
GetPartialLoginResumeUrlAsync on ASP.NET Core

### ISSUE THREAD

**Issue by akamud** [IdentityServer/IdentityServer3#2915]
### How to access `GetPartialLoginResumeUrlAsync` running on ASP.NET Core (no OWIN)?

I am running IS3 on ASP.NET Core (RC1) and I need to call the method `GetPartialLoginResumeUrlAsync`, but [there is no](https://github.com/IdentityServer/IdentityServer3/blob/ea62f859ccc4a2554e73fcec544d7a34e8d31682/source/Core/Extensions/OwinEnvironmentExtensions.cs#L371) `OwinContext` for me to access. 
Is there another way to get the URL?

**Comment by brockallen** [comment]
I'm confused.

**Comment by akamud** [comment]
I want to redirect the user to an EULA page on the first login, so I'm calling 

```C#
context.AuthenticateResult = new AuthenticateResult("~/eula", user.Subject, user.Username);
``` 
after login.

This works fine, the problem is that, after the user accepts the EULA I need to redirect him to continue with the login process, from my understanding I need to call `GetPartialLoginResumeUrlAsync` to get the URL that I need to redirect to. The problem is that I am using ASP.NET Core RC1 so I don't have an `OwinContext` available to use this method.

How could I use this with ASP.NET Core?

**Comment by brockallen** [comment]
I don't understand why you're using IdSvr3 from an ASP.NET Core host. Use Katana.

**Comment by akamud** [comment]
We had a few compatibility problems with IS4 and had to downgrade temporarily.

Partial logins are not possible on IdSvr3 + ASP.NET Core then?

**Comment by brockallen** [comment]
I don't know if they're possible -- I've just not tried (or tested it).

**Comment by akamud** [comment]
I see, I believe I'll have to do this manually. Thanks!

**Comment by brockallen** [comment]
If/when you do, let us know.
