### ISSUE TITLE
The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by chazt3n** [IdentityServer/IdentityServer3#2917]
I get this error and `IDX10803: Unable to create to obtain configuration from: 'https://localhost/WebHost/.well-known/openid-configuration'.`
as well as `Unable to get document from: https://localhost/WebHost/.well-known/openid-configuration`

It's as if the IdServer is asking for a client certificate, is this the case? @leastprivilege 

It's really weird because if I continually try to access the "Claims" page from the sample by refreshing I eventually see this screen:

![image](https://cloud.githubusercontent.com/assets/3843179/15515559/5a7d0286-21b4-11e6-9244-afdb5849eabb.png)

If I'm doing something wrong and still able to access the protected page then that's a little unexpected right?

Here are the most recent logs:

> iisexpress.exe Information: 0 : 05/24/2016 09:58:16 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
iisexpress.exe Information: 0 : 05/24/2016 09:58:16 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
iisexpress.exe Information: 0 : 05/24/2016 09:58:16 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
iisexpress.exe Warning: 0 : 05/24/2016 09:58:22 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 09:58:22 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 09:58:22 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 09:58:22 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
iisexpress.exe Information: 0 : 05/24/2016 10:01:38 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
iisexpress.exe Information: 0 : 05/24/2016 10:01:38 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
iisexpress.exe Information: 0 : 05/24/2016 10:01:38 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
iisexpress.exe Warning: 0 : 05/24/2016 10:01:39 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:01:39 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:01:39 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:01:39 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
iisexpress.exe Information: 0 : 05/24/2016 10:05:35 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
iisexpress.exe Information: 0 : 05/24/2016 10:05:35 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
iisexpress.exe Information: 0 : 05/24/2016 10:05:35 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
iisexpress.exe Warning: 0 : 05/24/2016 10:05:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:05:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:05:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:05:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:19:06 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:19:06 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:19:06 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:19:06 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:21:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:21:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:21:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:21:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:23:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:23:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:23:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:23:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:34:25 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:34:25 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:34:25 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:34:25 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 10:38:06 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 10:38:10 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 12:10:42 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:10:42 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:10:42 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:10:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:10:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:10:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:10:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:10:44 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 12:18:32 -05:00 [Information] (IdentityServer3.Core.Endpoints.DiscoveryEndpointController)
 Start discovery request
w3wp.exe Information: 0 : 05/24/2016 12:23:37 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:23:37 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:23:37 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:23:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:23:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:23:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:23:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:26:07 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:26:07 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:26:07 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:26:07 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:26:07 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:26:07 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:26:07 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:26:36 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 12:29:00 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:29:00 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:29:00 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:29:00 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:29:00 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:29:00 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:29:00 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:31:18 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:31:18 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:31:18 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:31:18 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:31:18 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:31:18 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:31:18 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:31:24 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 12:40:15 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:40:15 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:40:15 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:40:15 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:40:15 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:40:15 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:40:15 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:40:46 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:01:53 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 13:01:53 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 13:01:53 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 13:01:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 13:01:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 13:01:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 13:01:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 13:01:54 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:30:51 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:30:53 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:32:11 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:32:33 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:32:56 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering

**Comment by S3KCentrifugal** [comment]
Just a quick observation, and it might be nothing.

First... It looks like you are running this locally out off IIS, and WebHost is an application directory for the identity server. So shouldn't the path be 'https://localhost/WebHost/core/.well-known/openid-configuration'

If I am wrong and you are not running it out of separate application directories, could it be that both your client and identity server are running on port 80/443. Running two websites on the same port can also cause intermittent issues like that.

**Comment by chazt3n** [comment]
@S3KCentrifugal Wow thanks for the insight, I'll check that and get right back to you

**Comment by chazt3n** [comment]
Got past this, onto a new issue :/
