### ISSUE TITLE
API Licensing / Implementation Question

### ISSUE THREAD

**Issue by HarleeDavidson** [IdentityServer/IdentityServer3#2918]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi Brock, Dominick and company, just spent the last 3 weeks getting familiar with IdentityServer3, set up an instance and ran the samples, excellent stuff. This is less of an issue, more of an implementation question.

Today we license our Web API to our customers, they build web applications targeting our web api using a static api key for each customer. 

We are developing the next release of our api and we'd like to secure it using IdentityServer for our customer's applications. We need to:

 - authenticate/authorize usage of the api by customers and their end users
 - differentiate customers requests from each other
 - make it easy to implement by customer's application developers

We would also like to support anonymous and registered end users for each customer

Are we looking in the right direction, any tips? 

Cheers!

**Comment by brockallen** [comment]
There's a client_id claim in the access tokens -- that's how you will know which client app is calling you. Of course the implication is that each customer's client app will have its own registration in IdSvr.

Doing anonymous tracking is somewhat of an oxymoron -- if you want to securely track then the client needs to be authenticated.
