### ISSUE TITLE
Cookie Authentication - Logout

### ISSUE THREAD

**Issue by j-hurst** [IdentityServer/IdentityServer3#2921]
When using cookie authentication in a MVC app, when the cookie expires how do I get the app to log out of identity server?  The behavior I see, is that it just calls my Startup class again and re-authenticates.

**Comment by brockallen** [comment]
Sure, that's how SSO works.

**Comment by j-hurst** [comment]
Thanks.  I guess I am wondering where do I make that call.  Or is it a matter of me configuring the LogoutPath in the CookieAuthenticationOptions?

If so, is that path supposed to be a path in my MVC app, or back to my idsrv?

**Comment by brockallen** [comment]
Look at the samples:
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client/Controllers/HomeController.cs#L50

this line triggers both to logout

**Comment by j-hurst** [comment]
I have that if they want to click a logout button.  What if they sit on a page until the cookie expires, and then make a server side request?  I would like to auto log them out and then send them to the login page.

**Comment by brockallen** [comment]
That's a hard problem to solve. Just because they timed out of your one app, should you decide to trigger single signout for all the other apps?

**Comment by j-hurst** [comment]
That would be ideal.  

Well let me ask a different question; if the cookie expires, what should happen?  Because based on the behavior I see it re-authenticates with the idsrv.  I guess I am wondering, is there ever a time where both the cookie and tokens are expired and the user would be redirected to the logout page or login page?

**Comment by brockallen** [comment]
> That would be ideal. 

Not sure I want my timeout in onedrive kicking me out of the azure portal :)

You have a cookie timeout in the app, and you have a cookie timeout in IDSvr. The cookie lasting a while in IdSvr is what provides SSO. If your client app needs to know the user has logged in recently then pass the max_age param. See the authorization endpoint docs.

**Comment by j-hurst** [comment]
Ha.. That's true.

That does sound like what I am possibly looking for.  Where can I set the max_age so it can be passed in?

**Comment by brockallen** [comment]
Docs: https://identityserver.github.io/Documentation/docsv2/endpoints/authorization.html

**Comment by j-hurst** [comment]
Yea I realize that it is something that gets added onto the authorization endpoint, but I was wondering where do I call the authorization from?  Does it get set in the RedirectToIdentityProvider for an authentication request?

**Comment by brockallen** [comment]
Yes, you'd do this from the notifications event in your MVC/Katana/OIDC MW code.

**Comment by j-hurst** [comment]
From more of a best practice stand point, how should I set the value for the max_age parameter?  Do I just hard code the value in there to match up with the value of the expire time span on my cookie?  Or should I grab this from somewhere?

**Comment by brockallen** [comment]
Up to you. I don't know what your policy is. max_age normally is used to express for a client that the user should have authenticated "recently". For example, maybe for a "more sensitive" part of your app the user needs to have authenticated within the past 15 mins.

**Comment by j-hurst** [comment]
Yea, that makes sense.  I have played with a few different values in there; I believe this is going to do what I am looking for.  Thanks.
