### ISSUE TITLE
Access requested scopes in GetProfileDataAsync() 

### ISSUE THREAD

**Issue by sudipster** [IdentityServer/IdentityServer3#2924]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
This may/may not make sense but there could be cases where a client may not request all the scopes he is allowed to in the ids. I can access the allowed ones via context.Client.AllowedScopes, but I would like to access requested scopes by the application in GetProfileDataAsync() so that I could only build those claims relevant to those scopes.  Is it possible to do so?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
That's what the `RequestedClaimTypes` in the `ProfileDataRequestContext` are for.

**Comment by sudipster** [comment]
Thanks.
