### ISSUE TITLE
Response Types and Response Modes

### ISSUE THREAD

**Issue by Sriram143** [IdentityServer/IdentityServer3#2925]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

How to configure Supported Responsetypes, Supported Response Models in IdentityServer 3 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
What have you tried?

**Comment by Sriram143** [comment]
I didn find any option to configure this if you have anything please share

**Comment by brockallen** [comment]
We have samples, videos, and docs: https://identityserver.github.io/Documentation/
