### ISSUE TITLE
Character # instead ? in redirect uri

### ISSUE THREAD

**Issue by arogges** [IdentityServer/IdentityServer3#2927]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

Hi to all, I'm trying to use IdentityServer3 with Magento but actually for ne it's not possible parse the uri redirected because it contains # instead ? before parameters values; it seems a trivial problem but I can't solve it

steps:
- POST on https://idserver/core/login?signin=059a1779a382daf86672f50fc2c00c7e

- 302 on https://idserver/core/connect/authorize?response_type=id_token&redirect_uri=http%3A%2F%2Fmymagentosite%3A8080%2Fscripts%2Fopenid_simple%2Ftest.php&client_id=acmi-mep-cli-webshop&nonce=d96d2279c89dc7660d478048d1b50f2c&state=81cf33c9760e1a76fa989acf3b5d0c1c&scope=openid%20profile%20email

- http://mymagentosite:8080/scripts/openid_simple/test.php#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwczovL2lkc2VydmVyZGV2LWFjbWkudGlja2V0b25lLml0L2NvcmUiLCJhdWQiOiJhY21pLW1lcC1jbGktd2Vic2hvcCIsImV4cCI6MTQ2NDAxMjcxMCwibmJmIjoxNDY0MDEyNDEwLCJub25jZSI6ImQwOTRhZjEyOTI0NmZmYWY5YzM1MjM4NDk5ODg1ZTAyIiwiaWF0IjoxNDY0MDEyNDEwLCJzaWQiOiI2ZDU4ZDRlYTY4YTYyZjgzMDFmOTdhNjZhYmE2YTdiNSIsInN1YiI6ImIxYTcwMWZjLTE4NTgtNDM0NC1iZTc1LWQyZmM0MDY2MzhmYiIsImF1dGhfdGltZSI6MTQ2NDAxMjQxMCwiaWRwIjoiaWRzcnYiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtaGFidWJAdmVnYW5zLml0IiwiZW1haWwiOiJtaGFidWJAdmVnYW5zLml0IiwiZW1haWxfdmVyaWZpZWQiOlsidHJ1ZSIsIm1oYWJ1YkB2ZWdhbnMuaXQiXSwiYmlydGhkYXRlIjoiMTIvMTAvMTk4MyAwMDowMDowMCIsInJvbGUiOiJGYW4vQ29uc3VtZXIiLCJnZW5kZXIiOiJNIiwiZ2l2ZW5fbmFtZSI6Ik1IIiwiZmFtaWx5X25hbWUiOiJNbSIsImFtciI6WyJwYXNzd29yZCJdfQ.K9O05OYFSKdjCrzZtsTigOm0jtYfETftC5L34XvJSK-Yw4Hbb5w6Js45HbLD7Y_e4wpDpmhjfsyPBL_VBwJka6KmDe38GZCYm5vwu_WxRK3Nf3wdOlpvK1vOA8oMbqSDt7mGnQGZ4kPFvuo8iyBC6LtKhrsqHu3kjaOnyJ7mxtXOORVK3KP2M2e7ZgzwUoelTBBeA-GLWtduxLjXSMnZul39Sm0x98NjlGrbJCiAlCFUxW99PifEJ9RzMrZvEGcIzmUiuEHLxzMYLNUXrUB7KwnV7qOa229iI-5H3JvXXKR8dt4YhNSgF-8dKe7GuZbTWxVUnTP6CTdMeaA8zRQaNA&scope=openid%20profile%20email&state=1564adf857735db8717c175d88e9fdfa&session_state=hZ8h8YQl7PFlqrS3cnUnDNxaNLVM82RHaa0mXpZ4sjA.1e0b74a6a50787cc96e5375a97a34ff6

**Comment by brockallen** [comment]
So contact Magento as to why they are not accepting the response.

**Comment by arogges** [comment]
Right, a workaround can be having a "pre_callback" page that take the uri, subs the # and redirect at the real "callback"

**Comment by brockallen** [comment]
All set with this? Can we close?

**Comment by arogges** [comment]
Yes, thks very much
