### ISSUE TITLE
How to setup idsrv to run via web application proxy in a preauthentication scenario

### ISSUE THREAD

**Issue by dandohotaru** [IdentityServer/IdentityServer3#2928]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

Hi,

I am having a particular cors related issue for an enterprise environment.
Let me first try to explain the environment i deal with.

wap: 

- web application proxy in dmz

adfs: 

- https://auth.domain.com
- runing on windows 2012 R2

app: 

- https://app.domain.com
- angular application
- implicit client flow

api: 

- https://api.domain.com
- rest service

auth: 

- https://sts.domain.com
- identity server
- custom cors policy service matching client allowed origins

Everything works as expected when we are in a pass through scenario for the wap.
_GET https://sts.domain.com/core/.well-known/openid-configuration
200 OK_

The moment we switch to pre authentication we get into trouble 
_GET https://sts.domain.com/core/.well-known/openid-configuration
307 Temporary Redirect_

_XMLHttpRequest cannot load https://sts.domain.com/core/.well-known/openid-configuration. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://app.domain.com' is therefore not allowed access._

**General**
Request URL:https://sts.domain.com/core/.well-known/openid-configuration
Request Method:GET
Status Code:307 Temporary Redirect
Remote Address:...

**Response Headers**
view source
Content-Length:0
Date:Thu, 26 May 2016 09:29:24 GMT
Location:https://auth.domain.com/adfs/ls?version=1.0&action=signin&realm=...
Server:Microsoft-HTTPAPI/2.0

**Request Headers**
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8,fr;q=0.6,ro;q=0.4
Cache-Control:no-cache
Connection:keep-alive
Host:sts.domain.com
Origin:https://app.domain.com
Pragma:no-cache
Referer:https://app.domain.com/login
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36

Do you happen to know how i could overcome this knowing that the preauthentication is a constraint that i can't play much with?

Thanks,
Dan

**Comment by brockallen** [comment]
We have a CORS policy service you can implement. Also, if you're using the EF implementation of the client store, the Client has a list of allowed CORS origins and our EF library implements this for you.

**Comment by dandohotaru** [comment]
Well, i do make use of the cors policy service, 
and it works as expected in the pass-through scenario 
but not the pre-auth unfortunately...

```
public Task<bool> IsOriginAllowedAsync(string origin)
        {
            var query = from client in Clients
                        from allowed in client.AllowedCorsOrigins
                        select allowed.GetOrigin();

            var result = query.Contains(origin, StringComparer.OrdinalIgnoreCase);

            var template = result
                ? "Client list checked and origin: {0} is allowed"
                : "Client list checked and origin: {0} is not allowed";
            Logger.InfoFormat(template, origin);

            return Task.FromResult(result);
        }
```

**Comment by brockallen** [comment]
Ah, ok I think I see... because it's a GET and a non-preflight CORS request, the request is routed into the server and then the authentication logic kicks in... hmm, interesting.

What I don't understand is why is your user service's PreAuthN getting called for the metadata endpoint?

**Comment by dandohotaru** [comment]
if my understanding is correct, once the url of the app is reached, 
the wap takes control and tries to authenticate via adfs
once the user is authenticated control is redirected back to the app
that eventually should start the oidc dance flow

**Comment by brockallen** [comment]
Any progress?

**Comment by dandohotaru** [comment]
Unfortunately we could not make the cors work as expected, given the constraints...
I have very little to no control over the infrastructure configuration but i highly doubt that we are the first one to have to integrate idsrvr with a corporate proxy such as microsoft wap.
You might say this a microsoft issue nevertheless, and you might be right, but i raised the issue here hoping that someone might have reached the same walls i had

Just for visualization purposes, this is what i have now in place working as expected

![image](https://cloud.githubusercontent.com/assets/1856429/16054599/227bd856-326e-11e6-8890-337513e48f14.png)

and this is the goal trying to reach with wap pre-auth on all levels but adfs

![image](https://cloud.githubusercontent.com/assets/1856429/16054616/3864cd1c-326e-11e6-979b-2879f84c6d42.png)

but the flow fails the moment pre-auth is set for idsrvr as well

![image](https://cloud.githubusercontent.com/assets/1856429/16054707/97fc3328-326e-11e6-8603-b6f5f3a4a857.png)

Cheers,
Dan

**Comment by leastprivilege** [comment]
did you ever resolve this?

**Comment by dandohotaru** [comment]
nope.
for the moment, due to security policy constraints, I am forced to keep the
application within organisation boundaries, without access from the outside
world.
i've implemented also an alternative scenario without adfs but with windows
authentication as an identity provider.
this comes with other challenges for the network infrastructure guys that
need to keep some sort reverse proxy in place, and for the moment the ball
remains in their court...
to cut things, short, no, my issue is not resolved, and i don't see a
viable solution for the time being...

**Comment by leastprivilege** [comment]
OK - sorry. Will close for now.
