### ISSUE TITLE
app.FormpostResponse Question

### ISSUE THREAD

**Issue by Sriram143** [IdentityServer/IdentityServer3#2931]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
formpost.js is submitting as Http post rather than Http GET
![image](https://cloud.githubusercontent.com/assets/4466654/15588706/1dc84a12-235d-11e6-99b9-d6e9ba1225c3.png)

whats the root cause for this?
### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
That's how the protocol works for response_mode=form_post.
https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html
