### ISSUE TITLE
Issue: Id svr with two client Local login and windows -HELP

### ISSUE THREAD

**Issue by AmitCap** [IdentityServer/IdentityServer3#2932]
Hi,
I have a requirement to get token for  two different application 
1. Local login to authenticate with login page and my service.
2. Windows user with AD Group.( As external authentication)

Both working fine to get the token but when call separably.

this issue is when i hit the id server with my login page it create the token for me and store it in local storage, but no when i run my windows authenticationn app that is not going to call the PreAuthenticateAsync method of my user service it directly going to GetProfileDataAsync to get claims? how?

please help me

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
