### ISSUE TITLE
MVC Owin Hybrid Client Sample

### ISSUE THREAD

**Issue by Sriram143** [IdentityServer/IdentityServer3#2933]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

If i change the cookie in this example identity server is not detecting the cookie and always redirecting to get the code and token.

           app.Use(async (ctx, next) =>
            {
                if (cookieAuthenticationOptions.CookiePath.Equals("/"))
                {
                    cookieAuthenticationOptions.CookiePath = ctx.Request.PathBase.Value;
                }
                await next();
            });

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
> If i change the cookie

What do you mean?

**Comment by Sriram143** [comment]
Its always redirecting to Identity server instead of showing index page.

**Comment by brockallen** [comment]
Sorry, I still don't understand. 

For help in getting started I'd suggest to use stackoverflow. Issues here are for problems with IdentityServer itself.
