### ISSUE TITLE
Enable or disable windows authentication by client

### ISSUE THREAD

**Issue by sudipster** [IdentityServer/IdentityServer3#2934]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
This post was lil bit helpful: https://github.com/IdentityServer/IdentityServer3/issues/1439 but have a bit different issue. At the moment, Clients in the intranet are automatically authenticated via windows auth. I would like to set up Clients in ids such that I could enable or disable automatic windows authentication (This is mostly for testing purpose some times developers for the client apps like to test authentication manually), so when disabled they would go the the ids login page as normally. Is there a way to do this in PreAuthenticateAsync?  I can definitely store that value outside of ids and access that via an external repository but wondering if it is possible to do this with ids pipeline somehow.

This is what my PreAuthenticateAsync looks like:
public override Task PreAuthenticateAsync(PreAuthenticationContext context)
        {
            var clientID = context.SignInMessage.ClientId;
            //Client client = GetClientDetails();
            //client.Claims
            if (IsAutomaticWinAuthEnabled(clientId))
            {
                var ipAdd = DetectIpAddress();
               
                if (NetworkHelper.IsPrivateNetworkAddress(ipAdd))
                {
                    context.SignInMessage.IdP = "windows";
                }
            }
            return Task.FromResult(0);
        }

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Most people solve this by putting 2 different versions of the IdP -- one in intranet that can do integrated, and one on internet that can accept uid/pwd credentials.
