### ISSUE TITLE
Question: SSO for existing SSO server for specific clients

### ISSUE THREAD

**Issue by hubaksis** [IdentityServer/IdentityServer3#2935]
### Question
I have a working instance of Identity Server 3 (implicit workflow) with custom UserService and MvcViewService. Everything works great. Thank you for that.

I wonder, is it possible for Identity Server for specific clients to automatically redirect requests to another identity provider? (For the simplicity let this second identity provider also be IdentityServer3, but it doen not mean that we can send auth requests for those clients directly to the second server, the point is that the first server must get the first request).

Example: Let's say we have clients **a**, **b**, **c1**, **c2**. For clients **a** and **b** everything works as usual (idsrv authenticates both). For clients **c1** and **c2** request should be **automatically** redirected to another auth server, then after user is authenticated, he is redirected back to my idsrv, idsrv sets cookie for him and user is redirected back to the application **c1**. When the same user tries to open application **c2**, my idsrv already recognises him, authorises and redirects user to **c2**. 
Thank you.

**Comment by brockallen** [comment]
If you set allowed IdPs on the client config and there's only one (and you also set allow local login to false) then IdSvr will auto redirect the user.

**Comment by hubaksis** [comment]
Thank you for your answer. To double check what I need to do is:
1. Find out how to register the second identity server 3 as a new provider in my current identity server' s startup class.
2. In a new client configuration turn off local login and set only one value to the IdentityProviderRestrictions list.
Correct?

**Comment by brockallen** [comment]
for 2, yes. i don't know what 1 is, but that's up to the external IdP.

**Comment by hubaksis** [comment]
Rephrasing number 1: do you have an example how to connect IdentityServer3 as an external identity provider? 
I found examples [here](https://identityserver.github.io/Documentation/docs/configuration/identityProviders.html) for Facebook, Google, Twitter as external identity proiders but can't find out how to connect one Identity Server 3 as external IdP for another Identity Server 3.
Thanks.

**Comment by brockallen** [comment]
> Rephrasing number 1: do you have an example how to connect IdentityServer3 as an external identity provider? 

Same as the samples, except you'll use OIDC.

**Comment by hubaksis** [comment]
I've managed to complete this task.

So, if you want to connect another IdentityServer3 as external provider, you need to use OpenId configuration.

Firstly, Startup class
```
using Microsoft.Owin.Security.OpenIdConnect;
...
//in the Configuration method
var options = new IdentityServerOptions
{
..
    AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
    {
     ...
    IdentityProviders = ConfigureIdentityProviders
    }
}

public static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
{
	var option1 = new OpenIdConnectAuthenticationOptions()
	{
		Authority = "https://ssoserver1/core",
		ClientId = "clientID",
		Scope = "openid email",
		RedirectUri = "https://localhost:44333/core/",
		ResponseType = "id_token",
		SignInAsAuthenticationType = signInAsType,
		AuthenticationType = "First", // this name will be used in the Client's IdentityProviderRestrictions
	};
	app.UseOpenIdConnectAuthentication(option1);

	var option2 = new OpenIdConnectAuthenticationOptions()
	{                   
		Authority = "https://ssoserver2/core",
		ClientId = "clientID",
		Scope = "openid email",
		RedirectUri = "https://localhost:44333/core/",
		ResponseType = "id_token",
		SignInAsAuthenticationType = signInAsType,
		AuthenticationType = "Second", // this name will be used in the Client's IdentityProviderRestrictions
	};
	app.UseOpenIdConnectAuthentication(option2);
}
```
Secondly, in the Client configuration we need to set IdentityProviderRestrictions like this
```
if (my client is using first server)
{
	client.IdentityProviderRestrictions.Add("First");
	client.EnableLocalLogin = false;
}

if (my client is using second server)
{
	client.IdentityProviderRestrictions.Add("Second");
	client.EnableLocalLogin = false;
}
```
Finally, in the UserService class we need to implement AuthenticateExternalAsync. Example is [here](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomUserService/CustomUserService/ExternalRegistrationUserService.cs).
In this method provider name ("First" or "Second") will be in the `context.ExternalIdentity.Provider` field, and user's subject claim in the `context.ExternalIdentity.ProviderId`.

When authenticating user do not forget to set `identityProvider` field
```
context.AuthenticateResult = new AuthenticateResult(<youe new user ID>, "name", identityProvider: context.ExternalIdentity.Provider);
```
or you'll get a redirect loop.

@brockallen thank you very much for your great support.
