### ISSUE TITLE
Are sliding sessions possible?

### ISSUE THREAD

**Issue by kimsagro1** [IdentityServer/IdentityServer3#2936]
We are developing an MVC application in the financial space and need to implement 20 minute sliding sessions.

Out configuration looks like this

```csharp
public class Startup
{
    public void Configuration(IAppBuilder app)
    {

        JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

        AntiForgeryConfig.UniqueClaimTypeIdentifier = IdentityModel.JwtClaimTypes.Name;

        app.UseCookieAuthentication(new CookieAuthenticationOptions
        {
            AuthenticationType = "Cookies",
            ExpireTimeSpan = new TimeSpan(0, 20, 0),
            SlidingExpiration = true
        });

        app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
        {
            ClientId = "a client",
            Authority = "identity server 3",
            RedirectUri = "some redirect url",
            SignInAsAuthenticationType = "Cookies",
            ResponseType = "code id_token token",
            Scope = "openid profile address offline_access",
            UseTokenLifetime = false,
            PostLogoutRedirectUri = "some logout url",

            Notifications = new OpenIdConnectAuthenticationNotifications()
            {
                SecurityTokenValidated = async n =>
                {
                    // get id token, access token, refresh token
                    // add to claims
                    // save authentication ticket
                },

                RedirectToIdentityProvider = async n =>
                {
                    // get id token to add as id token hint
                    if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                    {
                        var identityTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                        n.ProtocolMessage.IdTokenHint = identityTokenHint.Value;
                    }
                }
            }
        });
    }
}
```

The issue is that as soon as the cookie expires, we are automatically redirected to identity server and automatically logged in again.

I'm assuming the solution is to detect when your cookie has expired and log you out of identity server, however this poses a number of issues

1) How to detect when your cookie has expired to trigger the identity server logout
2) Even if we can solve the issue above, we no longer have access to the id_token claims which is required by identity server to transparently redirect the user to the post logout uri.

So my questions are

1) Are sliding sessions possible
2) If not, how are other people handling this scenario. We cannot be the only ones wanting to implement short session times.

**Comment by hubaksis** [comment]
I have almost the same task in the backlog. Here are some ideas we are thinking of (none of this is implemented yet, just thoughts):
1a. Set identity server cookie expire in 5 minutes. Thus you won't be automatically logged in. Cookie will expire and you will be transferred to the login page.
or
1b. Set cookie expiration in 21 minutes, and in 20 minutes of inactivity log out user with javascript. Not sure that id_token won't exist if cookie expires, but in this case cookie are still valid and id_token exists.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
