### ISSUE TITLE
Local Authentication with extra parameter

### ISSUE THREAD

**Issue by RohanSapkal** [IdentityServer/IdentityServer3#2937]
I am trying to implement custom local authentication in IdentityServer3. Usually we authenticate using username & password. I my case I have 3rd parameter 'DomainId'. Now I created custom login page  by extending DefaultViewService. In my login page I am accepting Username, Password & DomainId. For local authentication I extended base class 'UserServiceBase'.

But I am struggling to get this 3rd parameter i.e. DomainId inside 'AuthenticateLocalAsync' function. 

Could anyone help me with the right approach on how to pass extra parameter besides, username & password to local authentication method.

![login page](https://cloud.githubusercontent.com/assets/5619415/15664131/0eb04b0e-271f-11e6-911c-6ff171861383.PNG)

**Comment by leastprivilege** [comment]
Has been discussed numerous times. 

Inject the OwinEnvironmentService and read the form.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by RohanSapkal** [comment]
Hi

I injected OwinEnvironmentService into userservice but form data is coming as blanks. 

Do you have sample code to highlight how this is done? 

Appreciate your help

Thanks 
Rohan Sapkal

**Comment by ruwanthaka** [comment]
yes i also face the same problum

**Comment by RohanSapkal** [comment]
I solved this problem. Do you need sample code?

**Comment by ruwanthaka** [comment]
yes, really appreciate if you can do that.. thanks in advance , how im doing it now is concatenate  those additional param using javascript and decode it from server again . :-)

**Comment by RohanSapkal** [comment]
Will send you. Right now I don't have access to my code. Will send you as soon as possible. 

You have to use owin layer. Research on how to access form data within owin context and you will get the hint.
