### ISSUE TITLE
WsFederation ADFS callback issue

### ISSUE THREAD

**Issue by irealzDennis** [IdentityServer/IdentityServer3#2941]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi,

I am new to Identiy Server 3. I am using the IdentityServer3 source from GitHub together with the sample client (Webforms Owin implicit). I have setup my inhouse ADFS service on one of my server and added the IdentityServer3 as Relying party. I managed to run the client and get redirected to the Identity Server 3 login then to my ADFS login page. I am able to login successful but however the login successful redirection seems wrong. In my ADFS Rely party Endpoints setup , i use "https://localhost:44300/core/" as suggested in this post : [https://www.scottbrady91.com/Identity-Server/Identity-Server-3-using-WS-Federation](url). 

Subsequently i changed the Endpoint url to "https://localhost:44300/core/callback" and change the LoginExternalCallback to HTTPPost. It is able to be redirected back to my IdentityServer 3 page, however, it is unable to retrieve SignID from the Owin Context. The debugging shows the return from Owin Context Authentitcation.AuthenticateAsync("idsvr.external") is returning null value.

Please advise. thank you!

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
