### ISSUE TITLE
SPA - ImplicitFlow pass identity token to protected api.

### ISSUE THREAD

**Issue by yusbel** [IdentityServer/IdentityServer3#2942]
A question, not an issue,.

How can the identity token be passed to the protected api? - To be more specific I want to pass the identity token with the claims to the protected api so that the proteted api can do further authorization.

**Comment by kpstolk** [comment]
You cannot I believe, or at least should not: see #2015

**Comment by johnkors** [comment]
Correct. Use the access tokens for APIs (resources), but populate the access tokens with whatever identity claims you need to do your custom auth in your APIs.

You are in charge of generating the access tokens, so if you want/need it - add the userid (the `sub` claim, from the openid scope) or any roles to it. That's up to you. 

The docs have more info on how to set this up.
