### ISSUE TITLE
Remember me feature when using IdentityServer3.AspnetIdentity

### ISSUE THREAD

**Issue by dunglp** [IdentityServer/IdentityServer3#2943]
Hi,
Hope you are doing well. 
I have a question.
How can I use 'Remember me' feature when using IdentityServer3.AspnetIdentity ?

Thanks in advance.

**Comment by brockallen** [comment]
"Remember me" relates to issuing persistent cookies in the browser. It's unrelated to ASP.NET Identity.

**Comment by dunglp** [comment]
Hi @brockallen,
Thanks for your info.
I mean when user input username and password, they are standing at IdSv page. How can I know that user checked on 'Remember me' to issue a persistent cookies in my web app ?

**Comment by brockallen** [comment]
IdSvr does this for you.

**Comment by brockallen** [comment]
> I mean when user input username and password, they are standing at IdSv page. How can I know that user checked on 'Remember me' to issue a persistent cookies in my web app ?

I misunderstood your question. Let me re-answer: your app does not know. This is an implementation detail in IdSvr.

**Comment by brockallen** [comment]
All set with this? Can we close?
