### ISSUE TITLE
Client based Audience

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#2944]
Let make me very clear. I have 2 clients one is for api and another one is for web. Web uses implicit flow while api uses resource owner flow. Everythings works fine. But when client login he will get an id_token. I wanna send the id_token to my api server. But I am getting invalid audience error because the audience of both client are different. Is there is way for Identity to generate same audience for both clients? Currently, I get authority+"/resoiources" for api and ClientId for implicit flow.

**Comment by leastprivilege** [comment]
id_tokens are for the client to validate. APIs consume access tokens.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by abcplex** [comment]
I have checked access_token it include valid audience but it missing claims of users(roles and custom claims) however claims are present in id_token. What I need is simple whenever user login, I should be able to call my api using access_token(but now access_token JWT is missing claims)

**Comment by leastprivilege** [comment]
You use scopes to define which claims go into which token. Has been discussed many times before - check the docs or archives.

**Comment by abcplex** [comment]
OK thanks. But why resource owner client get all claims but implicit flow client not. Both have,

`AllowAccessToAllScopes = true,`

How to tell the Identity server to generate all claims for both clients.

**Comment by abcplex** [comment]
But note please id_token includes all claims but access_token not.

**Comment by abcplex** [comment]
@leastprivilege thanks for the pointer I added my custom scope in OpenIdConnectAuthenticationOptions.Scope on implicit flow client it works like a charm.
