### ISSUE TITLE
How to use Single sign on for two web applications and WCF service authentication&authorization to gether?

### ISSUE THREAD

**Issue by pagidigovardhan** [IdentityServer/IdentityServer3#2945]
### Question 

Hi Brockallen,

I am trying to implement SSO for two MVC applications so I have used WS-Federation, works fine. 
I can read all the user claims using WSFederationAuthenticationNotification.

Now If I want to authenticate & authorize WCF services (which MVC uses) how to do that?

How can I get the Access_token which required  for WCF service SAMLTokenHandler?

SAMLTokenHandler using discovery endpoint of openid-configuration, because this was intended to use Resource owner flow, but due to SSO I have used WS-Federation and endup in confusion.

Am I doing correctly, or mixing WS-Fed and openidconnect together?

Can you please suggest me?

**Comment by brockallen** [comment]
We have a sample that shows how WCF can use JWT bearer tokens.

**Comment by pagidigovardhan** [comment]
Thanks Brockallen for swift response..

This gives clear picture. 

Do I need to use only openidconnect (not ws-federation) if I want to use Access_token?
As I said above, I thought of implementing SSO using WS-Fed, If I can't use access_token using WS-Fed then I use openidconnect  to make SSO work..

My understanding is correct???

**Comment by brockallen** [comment]
You can use OAuth2/OIDC to get a token, and then pass it to a WCF service, yes.

**Comment by pagidigovardhan** [comment]
Thanks a lit..I am clear now. Closing this thread.
