### ISSUE TITLE
SSO with two different sites not redirecting to IdSrv

### ISSUE THREAD

**Issue by sai915213** [IdentityServer/IdentityServer3#2946]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi,

We have one site which is using thinktecture idsrv3 with hybrid flow. we have another mvc site with its own users database. want to achive sso from the mvc site without redirecting to idsrv. 

Tried with ResourceOwner got access token and claims but lost sso. 

Please anyone suggest the best approach.
  

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
For SSO you need to redirect.

**Comment by sai915213** [comment]
Thanks for quick response. 

How do we get the password back from IdSrv, so that i can auto login into my source mvc site

**Comment by brockallen** [comment]
For SSO you need to change the architecture of your MVC app to trust the SSO server. 

For other questions that relate to learning we'd suggest reading the specs, reading the docs, looking at the samples, or asking questions on StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
