### ISSUE TITLE
Implementing Sliding Expiration Across MVC and Web Api

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3#2949]
I've read some previous issues regarding logging out user after; for example, 20 minutes of inactivity. I'm pretty sure I understand the part about a mvc project but I don't know how it should be done for a web api. 

So I have a mvc project (mvc) and a web api (api) that's in another domain. I'm using implicit flow. So to logout the user after 20 minutes of inactivity in mvc I think I need to set the following in the mvc:

```
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                SlidingExpiration = true,
                ExpireTimeSpan = TimeSpan.FromMinutes(20)
            });

```
and

` UseTokenLifetime = false`

mvc pages make ajax calls to the api and I use access token for  that purpose. 

**Questions**
How can I logout the user after 20 minutes of not making any ajax calls to the api?

Also how can I stop the mvc from logging out user if the user had been making ajax calls to the api in the last 20 minutes (since  I have single page apps that the user could be in for a long time and making ajax api calls without contacting mvc)?

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
