### ISSUE TITLE
Things to consider for Identityserver3

### ISSUE THREAD

**Issue by padiqts** [IdentityServer/IdentityServer3#2950]
we are building new security solution for our organization and thinking to implement Identityserver3 for single sign on and web API security . I wanted to know is the identityserver3 supports following items:

1.	Does it support ESB security  ( Example :  ESB Adeptia)
2.	Does it support AD AND LDAP ? 
3.	Does it support Citrix XenApp environment?
4.     How is it terms of performance and scalability?

Thank you

**Comment by leastprivilege** [comment]
Yes - we support all of that. But you have to write the code to adapt to it.

IdentityServer is a framework.

**Comment by padiqts** [comment]
1.Do you have any real time implementation of this identityserver3 framework implemented as enterprise solution for single sign on and web api security in any organization?  If yes, could you list them some.

2. Do you have any sample implementation or code of authenticating app running in the  Citrix XenApp  environment. We have lots of legacy apps running in this environment.

3. Any links or reference on the user interface built around this framework?

4. How does this frawework work in virtualization and load balancing environment?

5. Any contacts email or phone to have a detailed discussions and capabilities around this framework ?

Thank you ,

**Comment by leastprivilege** [comment]
Yes - there are many real implementations of identity server - from small business to enterprise in almost all verticals. But I can't name them since this is always subject of an NDA.

We have documentation, samples and provide commercial support plans via identity@leastprivilege.com

**Comment by padiqts** [comment]
HI,

Could you please share the commercial support plans cost. Do you have a
contact number to discuss. please let me know.


Thanks
Padi

**Comment by leastprivilege** [comment]
Hi, 

please write me an email to: identity@leastprivilege.com
