### ISSUE TITLE
SHA256 - .Net 3.5 SP1 

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3#2952]
Hi, When I try to use implicit flow, I am getting the following error. I am on Windows 10 and I don't have .NET 3.5 SP1, but I do have .Net 4.5.1 and 4.6. 

From the error message the framework and platform I have should not sufficient but I am still getting the this error. This happened after I am using DataProtector option in IDS. Any help is appreciated.

**_System.NotSupportedException: ID6035: Cannot create a HashAlgorithm with name 'SHA256' using the 'System.Security.Cryptography.RSACryptoServiceProvider' crypto provider. SHA256 may require a minimum platform of Windows Server 2003 and .NET 3.5 SP1._**

**Comment by leastprivilege** [comment]
where is this error happening? in idsrv or in the token consumer?

This sounds like something we don't have control over - maybe an OS setting, or a cert not supporting SHA256?

**Comment by aaabdul** [comment]
The error happens when the client sends ids the credentials and when ids tries to render the login page. It only happens when I register data protector certificate. 

If this is the only reason I need to enable DataProtector, then I can turn it off. https://identityserver.github.io/Documentation/docs/advanced/deployment.html

It does look like it's something to do with OS or the version of .Net framework.

**Comment by brockallen** [comment]
Any progress?

**Comment by aaabdul** [comment]
Not really. It certainly looks like an operating system issue. I have turned off data protection and everything seems tof be working. I'll close this issue for now.
