### ISSUE TITLE
ClientCredentials flow and expired tokens over multiple time-delayed physical boundaries

### ISSUE THREAD

**Issue by bunceg** [IdentityServer/IdentityServer3#2953]
### Question / Issue

This is an advice question, similar to this https://github.com/IdentityServer/IdentityServer3/issues/2758

In our scenario we have an on-premise device (A) making a call to our cloud hosted service  (B). Each device belongs to a customer and each customer has a unique api-key and api-secret. These are securely held on the device.

The device uses these to authenticate via Client Credentials flow; token lasts for around 10 hours.

service B dumps the request onto a message queue.
service C takes from the queue, performs some processing and calls service D, service D calls service E.... etc.

Each service is a distinct physical boundary (think microservices) called by https.

We are using a "delegated authority" concept so that the token is passed around as a custom claim that can then be used to attach to the next request in the chain. This means each service is operating under the original device A requested authentication and has access to the custom, customer specific, claims created when device A authenticated.

We also pass the JWT token in the message as a string between service B and C and this works fine when we use it to set the bearer token in service C when it calls  service D.

My problem is what if service B doesn't process the message within 10 hours (e.g. a fault). After 10 hours the token will have expired, and service B does not have access to the credentials used by device A to re-request the token.

I thought I needed a refresh token too, but this isn't supported for Client Credentials flow. Then I thought of "cheating" and making my token last "a very long time", but then I'm not sure how I can invalidate it in a security breach. My final option is to actually pass the api-key and api-secret in the token as a claim that can then be used to re-request a new token by any service in the chain... but this feels like a security breach waiting to happen. To be honest though, so does having the refresh token as it acts like a master password anyway.

Is there any advice / best practice on this scenario?

Many thanks

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
