### ISSUE TITLE
Q: Any examples of using phonegap client with implicit flow

### ISSUE THREAD

**Issue by RipalV** [IdentityServer/IdentityServer3#2954]
### Question
We have AngularJS SPA client using oidc-client-js and working very well.

We are now looking to have it packaged with PhoneGap and trying find best way to authenticate the phonegap client. 

I have already seen post as below more relevant to oAuth and IdentityServer2 and wonder if there are any such examples of IdentityServer3 using OIDC?
http://weblogs.thinktecture.com/cweyer/2012/11/oauth2-in-thinktecture-identityserver-v2-implicit-grant-flow-with-javascript.html

What would be the best client sample from below to use for PhoneGap?
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients

**Comment by brockallen** [comment]
There is a community member with a fork of oidc-client-js that has phonegap/cordova support. There also have an outstanding PR so in a week or so we'll have that in somewhere (sample, or something).

**Comment by brockallen** [comment]
All set with this? Can we close?

**Comment by RipalV** [comment]
Thanks, happy to close it. I have managed to get it working with PhoneGap by following code from below github repository.
https://github.com/ciaranj/OIDCPhoneGapSample
