### ISSUE TITLE
Question: External Provider + Custom Claims

### ISSUE THREAD

**Issue by a-tok** [IdentityServer/IdentityServer3#2955]
Hello,

I  have added an external  ADFS provider to my idsrv instance and it seems to be working (i.e authenticating and returning claims to idsrv). I am returning given_name, family_name and email_address claims. I've setup a custom user service and once the `AuthenticateExternalAsync` is invoked I create a custom claim called "userName" and add it as an item in the claims parameter on `context.AuthenticateResult` The application itself is configured to use authorization_code flow and it returns the "userName" claim successfully when authenticated against a local db. I can't seem to figure out why the "userName", given_name, family_name, and email claims don't come back when I perform external authentication. Any help or a push in the right direction is greatly appreciated!!!

Thank you

**Comment by leastprivilege** [comment]
Whenever a claim goes into a token, it's happening in `GetProfileDataAsync` - put a breakpoint there and see what's going on.

**Comment by brockallen** [comment]
All set with this? Can we close?

**Comment by a-tok** [comment]
Sorry about that, I wrote the question right before leaving on vacation. I will check this out first thing on Monday and will let you know.

**Comment by a-tok** [comment]
Thanks for the push in the right direction guys, I use the tenant id for realm discovery and once the code hits `GetProfileDataAsync` the tenant id was null causing the base method to be called.
