### ISSUE TITLE
cross domain AD request security token

### ISSUE THREAD

**Issue by jasonrock3** [IdentityServer/IdentityServer3#2958]
I'm trying to get a token via Identity / AD.

I have a setup where there is a parent domain and two child domains.

I'm hosting the application on IIS 6. When I setup the service account on the account pool to the a user in the first child domain... I can retrieve a token for any users in that domain but I get an error on the channel.issue for users on the other child domain.

When I change the service account to the second child domain, then I can receive a token for all users on the second domain and not the first.

I'm not sure what I am doing wrong. There is full trust between domains and I'm using the FQ user name (e.g. name@domain.com)

Thank you

```
            var factory = new WSTrustChannelFactory(
                new UserNameWSTrustBinding(SecurityMode.TransportWithMessageCredential),
                IdentityServerEndpoint());

            factory.Credentials.UserName.UserName = userName;
            factory.Credentials.UserName.Password = password;

            factory.TrustVersion = TrustVersion.WSTrust13;
            factory.Credentials.SupportInteractive = false;

            factory.ConfigureChannelFactory();

            var channel = factory.CreateChannel();

            var rst = new RequestSecurityToken
            {
                RequestType = RequestTypes.Issue,
                AppliesTo = new EndpointAddress(Realm),
                KeyType = KeyTypes.Bearer
            };

            try
            {
                var genericToken = channel.Issue(rst) as GenericXmlSecurityToken;
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
