### ISSUE TITLE
How to get instances of MessageCookie<SignInMessage> and OwinEnvironmentService?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2959]
How to get MessageCookie<SignInMessage> and OwinEnvironmentService? I know that I  can inject them into the constructor of custom services in IdSvr. But now I want to use these two instances in my own class(e.g. MyHelper).
Could you please give some code example? Thank you very much!

**Comment by brockallen** [comment]
If you have access to the OWIN environment you can use the OWIN extensions: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html
