### ISSUE TITLE
How to add other third party OAuth provider in idsrv3?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2960]
How to add other third party OAuth provider(just like Google, Facebook) in idsrv3?  Are there some code example?
Thank you very much!

**Comment by figuerres** [comment]
several of the samples show how to add google / facebook and others
here is one of them
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs

just download the samples zip and look thru the code in the startup.cs and you will see them.

**Comment by Farwell-Liu** [comment]
Thank you figuerres very much!
