### ISSUE TITLE
how to handle error callback from external provider

### ISSUE THREAD

**Issue by skbelalmd** [IdentityServer/IdentityServer3#2962]
Hai,
I have implemented facebook external login as follws  

var fb = new FacebookAuthenticationOptions
            {
                AuthenticationType = "Facebook",
                SignInAsAuthenticationType = signInAsType,
                AppId = "my app Id,
                AppSecret = "my app secret",
                Provider = new FacebookAuthenticationProvider()
                {
                    OnAuthenticated = (context) =>
                    {
                        const string XmlSchemaString = "http://www.w3.org/2001/XMLSchema#string";
                        var accessToken = context.AccessToken;
                        var facebookClient = new FacebookClient(accessToken);

// making an api call to get email from facebook      
            
      dynamic myInfo = facebookClient.Get("/me?fields=email");
       context.Identity.AddClaim(new System.Security.Claims.Claim("email", myInfo.email, XmlSchemaString, "Facebook"));                        
                        foreach (var x in context.User)
                        {
                            var claimType = x.Key;//string.Format("urn:facebook:{0}", x.Key);
                            string claimValue = x.Value.ToString();
                            if (!context.Identity.HasClaim(claimType, claimValue))
                                context.Identity.AddClaim(new System.Security.Claims.Claim(claimType, claimValue, XmlSchemaString, "Facebook"));
                        }
                        return Task.FromResult(0);
                    }
                },          
            };
            fb.Scope.Add("email");
            fb.Scope.Add("public_profile");      
            app.UseFacebookAuthentication(fb);

For my application an email is required for an account.
So I make a api call to get email from facebook account and save it in the claims.

My problem is that, if a facebook account is created only using phone no, the api returns null value.
So I want to show a page where I can get input for email and associate with the account.

The similar functionality can be seen in airbnb.com when you register using a facebook account that is created only using phone number.

**Comment by brockallen** [comment]
Look into using partial logins. We discuss in the docs and show in the samples.
