### ISSUE TITLE
2FA Challenge on Authz

### ISSUE THREAD

**Issue by alhardy** [IdentityServer/IdentityServer3#2963]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question

I've implemented 2FA (SMS & Authenticator) following a similar approach to the samples i.e. extending the login flow via PostAuthenticateLocalAsync. This is fine and works well, we've also allowed users the option to "Remember this device", dropping a cookie after being successfully authenticated. This is fine as well until the user chooses to remember their username/password login but not their second factor.

What I expect to happen in this case is when the client's session cookie expires and a redirect made to the connect/authorize endpoint, the user is then again challenged for 2FA.

The approach I've started to take in implementing this is quite simple i.e. just taking a similar approach to the consent interaction.

Do you guys see this is something to contribute back? I'm assuming 2FA hasn't been implemented in Idsrvs core because it's subject to a variety of implementation e.g. SMS, Authenticator etc. Is my assumption correct? If so maybe it'd be possible to provide some type of extensibility in the AuthorizationEndpoint e.g. allow "Interactions" to be injected in some way?

**Comment by alhardy** [comment]
Hmm, thought about this some more. I guess there would be too much "custom" around 2FA to be implemented in identityserver, more so around asking for the 2nd factor on login e.g. a choice of 2FA options could be provided to the user, if 2FA is forced per client it would have to have a populate mobile number screen etc etc

**Comment by brockallen** [comment]
> I guess there would be too much "custom" around 2FA to be implemented in identityserver

Yep.
