### ISSUE TITLE
redirecting to externalregistration html page from identity/externalregistration#

### ISSUE THREAD

**Issue by mbelfer** [IdentityServer/IdentityServer3#2964]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
hi,

I am using idSrv and absolutely love it. Recently I decided to add external providers (Google, FB, Twitter) and have problem understanding how to map come up with "externalregistration" page using angular.

In CustomUser example there is a controller that has GET/POST methods mapped to core/externalregistration" url, 
```
[Route("core/externalregistration")]
        [HttpGet]
        public async Task<ActionResult> Index()
...
...

```

but I am not sure i understand how to map url to an angular html page so that my CustomViewService would read "Content/app/externalregistration.html" page and render it.

 ```
public override Task AuthenticateExternalAsync(ExternalAuthenticationContext context)
        {
        ...
        ...
         context.AuthenticateResult = new AuthenticateResult("~/externalregistration", user.Subject, name, identityProvider: user.Provider);
            return Task.FromResult(0);
        }
```

Thank you

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by mbelfer** [comment]
sorry, i also posted my question there but it was not discovered there as well ;~(
