### ISSUE TITLE
SPA, API and Microservices

### ISSUE THREAD

**Issue by johnmckinzie** [IdentityServer/IdentityServer3#2965]
### Question

I'm working on an API that is back by microservices and will be consumed by a SPA. I've read several issues that touch on  access vs id token and what should be sent where, but I'm still just a little confused.

My original thinking was that the SPA would send the access token to the API. The API would validate the token and then somehow retrieve the id token as part of that validation, then send the id token as part of the requests to the back-end microservices that need to know the end user. I was hoping to do this, so that each back-end microservices didn't have to validate.

1. Is this is a anti-pattern and if so,  should the access token w/ additional claims be used instead (this seems to be the recommendation)?
2. If this is a good approach, can you configure the In ASP.NET Core, is there a way to configure the the UseJwtBearerAuthentication middleware to automatically retrieve the id token?

Any help would be greatly appreciated.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
