### ISSUE TITLE
[InvalidOperationException: IDX10803: Unable to create to obtain configuration from: 'https://localhost:30004/core/.well-known/openid-configuration'.]

### ISSUE THREAD

**Issue by nikeshksingh** [IdentityServer/IdentityServer3#2966]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
