### ISSUE TITLE
Adding web api end points to IsSrv3

### ISSUE THREAD

**Issue by manjhari** [IdentityServer/IdentityServer3#2967]
Hi,
we have a functioning identityserver3 running and we would like to add additional functionality like resetting a users password. I read in a previous post that someone has implemented this using additional web api endpoints and aspnet identity. I am having trouble doing this myself.
I have the following code:
 app.Map("/core", idsrvApp =>
            {
                var factory = new IdentityServerServiceFactory();
...
                factory.Register(new IdentityServer3.Core.Configuration.Registration<IdentityUser>(resolver => new IdentityUser()));
                factory.Register(new IdentityServer3.Core.Configuration.Registration<UserStore<IdentityUser>>(resolver => new UserStore<IdentityUser>(resolver.Resolve<CalypsoDal>())));
                factory.Register(new IdentityServer3.Core.Configuration.Registration<UserManager>(resolver => new UserManager(resolver.Resolve<UserStore<IdentityUser>>())));
                factory.Register(new IdentityServer3.Core.Configuration.Registration<UserController>(resolver => new UserController(resolver.Resolve<UserManager>())));

...

idsrvApp.UseIdentityServer(options);
            });
            return app;

My UserController:

    public class UserController : ApiController
    {
        private readonly UserManager _userManager;

        public UserController(UserManager userManager)
        {
            _userManager = userManager;
        }
        
        [HttpPost]
        [Route("forgotpassword")]
        public IHttpActionResult Post()
        {
            //var user = _userManager.FindByNameAsync("");

            //var code = _userManager.GeneratePasswordResetTokenAsync(user.Id);

            //_userManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"");
            return Ok();
        }

}

my startup:
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            Log.Logger = new LoggerConfiguration()
                .ReadFrom.AppSettings()
                .WriteTo.Trace(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level}] ({Name}){NewLine} {Message}{NewLine}{Exception}")
                .CreateLogger();

            var httpConfig = new HttpConfiguration();
            ConfigureWebApi(httpConfig);

            app.UseIdentityServer();
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseCors(CorsOptions.AllowAll);
            app.UseWebApi(httpConfig);
        }

        private void ConfigureWebApi(HttpConfiguration config)
        {
            config.MapHttpAttributeRoutes();
            config.Routes.MapHttpRoute(
                "ForgottenPassword",
                "user/forgotpassword",
                new { controller = "User", action = "Post" });

            //var jsonFormatter = config.Formatters.OfType<JsonMediaTypeFormatter>().First();
            //jsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
        }

    }

when i try to call my user controller i get the following
An error occurred when trying to create a controller of type 'UserController'. Make sure that the controller has a parameterless public constructor.

I am a little lost as to how to do this, is there another way?

Thanks
John

**Comment by figuerres** [comment]
are you storing the user login / password in an aspnet identity table ?
if you are then you do not need to use identity server to do the password reset logic.
just create a web api controller that uses the identity api to do it.

if you are using identity to store user logins and are still stuck I can possibly give you some info.

**Comment by manjhari** [comment]
Thanks,
what I was actually after was to use the DI container in Identity server to create the objects that I needed. I had this code originally, with the idea that the user identity management would be under /admin/user/forgotpassword etc.

            app.Map("/admin", adminApp =>
            {
                var factory = new IdentityManagerServiceFactory();
                factory.Register(new IdentityManager.Configuration.Registration<CalypsoDal>(resolver => new CalypsoDal()));
                factory.Register(new IdentityManager.Configuration.Registration<UserStore<IdentityUser>>());
                factory.Register(new IdentityManager.Configuration.Registration<UserManager>());
                factory.Register(new IdentityManager.Configuration.Registration<UserController>());
                factory.IdentityManagerService = new IdentityManager.Configuration.Registration<IIdentityManagerService, IdentityManagerService>();

                adminApp.UseIdentityManager(new IdentityManagerOptions()
                {
                    Factory = factory
                });
            });

I have in the meantime created my controller without DI with the usermanager created in the controller constructor. Is there a way to do the above using the DI of identity server?

Thanks

John

**Comment by manjhari** [comment]
Hi,
actually my basic problem stems from trying ti run idsrv and idmgmt within the same site in IIS.
We would like to have the idsrv on https://myhost/core/etc.
and id magmt on https://myhost/admin/user/etc.
Functions under idmgmt would be forgotten password, registration... which are all public 
and update password which would require an oauth2 token.
Is it possible to do this or should i run both under separate IIS sites?

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
