### ISSUE TITLE
Claims providers

### ISSUE THREAD

**Issue by bjarteskogoy** [IdentityServer/IdentityServer3#2968]
Does IdentityServer in any way deal with the concept of multiple claims providers like described here: http://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims ?

**Comment by leastprivilege** [comment]
Nothing like that is built-in and that is the first time this requirement comes up. I'd need to think more about if the current extensibility would allow for that.

**Comment by bjarteskogoy** [comment]
I don't if this is exactly what I'm looking for either.
We are trying to setup IdentityServer as our new authentication system. We also have a different system for assigning software licenes to logins. I would to be able get the licenses as claims without calling into the licensing system from IdentityServer. Any other ideas on how to solve this?

**Comment by leastprivilege** [comment]
I don't follow.

**Comment by bjarteskogoy** [comment]
I'll try to explain:
We now have an IdentityServer3 up and running.

Some of the api's our application is using needs to know the user's licenses, which reside in a seperate service from IdentityServer. The api could of course check the licensing system, but I would like to be able to extend the bearer-token with more claims when needed, ilke license-claims in this case, from a seperate system from the IdentityServer. Is that possible in any way?

Was that clearer?

**Comment by leastprivilege** [comment]
sure - the GetProfileDataAsync method in your user service is where you can include arbitrary claims in your tokens.

**Comment by leastprivilege** [comment]
yes

**Comment by bjarteskogoy** [comment]
Please enlighten me :)

**Comment by leastprivilege** [comment]
As I said already - add the claims in your user service.

**Comment by leastprivilege** [comment]
all set?
