### ISSUE TITLE
audience claim in the token

### ISSUE THREAD

**Issue by kedarkdr** [IdentityServer/IdentityServer3#2969]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
why is the audience claim in the token is getting set to host\resouces. Can I configure to some string. With the current behavior I am unable to configure this idp as idp provider in amazon web identity provider.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
I think you're confusing the idp in the id_token and the aud in the access token.

**Comment by kedarkdr** [comment]
can I get id_token in resource owner flow? also is it possible to customize the valid audience for the access token.

**Comment by leastprivilege** [comment]
no and no.

you can customize the audience by implementing your own ITokenSigningService (or derive from the default one).

**Comment by kedarkdr** [comment]
thanks. 
how can I achieve similar stuff as below using IdentityServerBearerTokenAuthenticationOptions. 

            app.UseJwtBearerAuthentication(new JwtBearerAuthenticationOptions
            {
                AllowedAudiences = new[] { "http://localhost:23590/resources" },
                TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = "http://localhost:23590",
                    IssuerSigningKey = new X509SecurityKey(certificate),
                    //ValidAudience = "http://localhost:23590/resources"
                    ValidAudience = "myapp"
                }
            });

**Comment by leastprivilege** [comment]
That looks to me like you want to validate an id_token in an API. As Brock already said - that's wrong.
