### ISSUE TITLE
Is it possible to set up scenario with IdentityServer3 doing OAuth preauthentication for an Web Api protected with Windows Integrated Authentication (WIA) on premises

### ISSUE THREAD

**Issue by pisees** [IdentityServer/IdentityServer3#2970]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is it possible to set up scenario with IdentityServer3 doing OAuth preauthentication for an Web Api protected with Windows Integrated Authentication (WIA) on premises.

This would be to expose on premises Web Api to native mobile clients over the internet.

Thanks, 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Yes, we support this with our "WindowsAuthentication" repo -- search the archives, please.
