### ISSUE TITLE
ErrorDescription isn't returned in response from ICustomGrantValidator

### ISSUE THREAD

**Issue by aaronlt** [IdentityServer/IdentityServer3#2971]
### Issue
Hi,

I'm implementing ICustomGrantValidator. 

In case of errors I return something like:
```
grantValidationResult = new CustomGrantValidationResult
                    {
                        IsError = true,
                        Error = Constants.TokenErrors.InvalidRequest,
                        ErrorDescription = "Unsupported subject_token_type."
                    };
```

Trouble is ErrorDescription never gets returned as part of token endpoint response.
I tracked it down to [this line in TokenRequestValidator.cs](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/TokenRequestValidator.cs#L725).
Fixing it should be trivial:
```
// From
return Invalid(result.Error);
// To
return Invalid(result.Error, result.ErrorDescription);
```

Assuming there are no security considerations I'm not aware of can we get it fixed?
It would really make life easier for our internal developers getting more information than "InvalidRequest". 

Should I make PR for this?

**Comment by leastprivilege** [comment]
thanks - added it to the 2.5.1 milestone
