### ISSUE TITLE
Making scope optional for custom grants?

### ISSUE THREAD

**Issue by aaronlt** [IdentityServer/IdentityServer3#2972]
### Question 

Hi,

I'm aware that "scope" parameter is mandatory in IS for all grant requests (as stated in #2026).
And this is fine. But:

**Would you consider making scope optional for custom grants?**

For e.g. we have developed custom grant for integration with our legacy authorization system.
As response it returns custom "ticket" which knows nothing about scopes.
Currently we are forced to use fake scope then using this grant. 

Having scope optional would make life easier in such cases. And I think it shouldn't impact overall security to much.

**Comment by leastprivilege** [comment]
right now scope is always mandatory. We have no plans for changing that.
