### ISSUE TITLE
IdentityServer with ADFS and multiple Wreply defined at runtime

### ISSUE THREAD

**Issue by softeering** [IdentityServer/IdentityServer3#2973]
### Question / Issue
I'd like to understand if the following is possible.
We have an ASP.NET MVC / WepAPI application that we would like to integrate with our ADFS. It works well with the Microsoft.Owin.Security.WsFederation package in OWIN as long as we deploy our app to one URL (https://localhost:44300 - the URL registered in the ADFS RP as the _Relying party WS-Fed passive protocol url_ - Wreply being something like "urn:appname")
Our app can be deployed to the cloud as a self-service (new instances can be created / deployed by external teams in the company). This ends up with several different URLs hosting the app (http://appinstance1, http://appinstance2...)
We would like to avoid manually creating a new RP whenever a team deploys a new instance of the app and rather use the same ADFS RP to authenticate users in the app

I thought about integrating IdentityServer 3 and configure it to act as a FEDERATION GATEWAY with ADFS (WsFed) being the only authentication provider configured.

Questions are:
- is this even possible? (or are we limited because of ADFS here - knowing that OIDC supports multiple different Reply urls)
- if it's possible, how can we define the reply url (Wreply) at runtime?
- maybe only SAML2 supports this with ADFS? (not WS-Fed passive)

Here is the IdentityServer configuration I tried so far but it doesn't work because the Wreply value is not configured in the RP

```
public partial class Startup
	{
		public void Configuration(IAppBuilder app)
		{
			var idsrvOptions = new IdentityServerOptions
			{
				SiteName = "IdentityServer3",
				RequireSsl = false,
				EnableWelcomePage = false,
				AuthenticationOptions = new AuthenticationOptions()
				{
					EnableLocalLogin = false,
					IdentityProviders = ConfigureIdentityProviders
				},
				LoggingOptions = new LoggingOptions()
				{
					EnableHttpLogging = true,
					EnableKatanaLogging = true
				}
			};

			idsrvOptions.Factory = new IdentityServerServiceFactory()
			{
				ClientStore = new Registration<IClientStore>(new ClientStore()),
				ScopeStore = new Registration<IScopeStore>(new ScopeStore()),
				UserService = new Registration<IdentityServer3.Core.Services.IUserService>(new UserService())
			};

			app.UseIdentityServer(idsrvOptions);

			//  ConfigureAuth(app);
		}

		public static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
		{
			var adfs = new WsFederationAuthenticationOptions
			{
				AuthenticationType = "adfs",
				Caption = "ADFS",
				SignInAsAuthenticationType = signInAsType,
				MetadataAddress = "https://sso.company/federationmetadata/2007-06/federationmetadata.xml",
				Wtrealm = "urn:lpsdynamo",
				Wreply = "http://localhost:18663/",
				CallbackPath = new PathString("/")
			};
			app.UseWsFederationAuthentication(adfs);
		}
	}
```

Any hint or link to the right documentation would be appreciated (already read a lot of them on SO and the Identity Server doc but I didn't manage to find the one stating if it's possible or not)

Thanks in advance

-David

**Comment by softeering** [comment]
Finally just found this - seems not possible due to ADFS WsFed limitation
http://social.technet.microsoft.com/wiki/contents/articles/2305.ad-fs-2-0-how-to-utilize-a-single-relying-party-trust-for-multiple-web-applications-that-share-the-same-identifier.aspx

Is there a way to integrate IdentityServer in the web app to support OpenID and IdSrv would call ADFS "behind the scene" (OIDC supports multiple reply urls)

-David

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
