### ISSUE TITLE
Client upgrade from RC1 to RC2 - cookie not getting set

### ISSUE THREAD

**Issue by jessicassw** [IdentityServer/IdentityServer3#2975]
We have an IdentityServer3 implementation up and running in a test environment with multiple clients. One of the clients that was working properly with RC 1 upgraded to RC 2 this week and we are having difficulties getting the authentication/authorization process to complete. The client has a hybrid flow and we are able to retrieve the access token, authorization code, and get a refresh token from idserver but after that the client is unable to authorize because the cookie never gets set. We aren’t seeing any error messages. When the client app is unable to authorize it ends up making a call back to IdServer, but at that point the user info is missing and the only error we see in the IdServer log files is: “No or malformed client credential found. {}” Running around in circles here trying to figure out why. Do we need to make any changes to IdServer3 in order to allow for a RC 2 client? Here is the Configure code from the RC 2 Client Startup file. Any help or leads is much appreciated!!

`public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            app.UseStaticFiles();

            //// Prevent Microsoft's JWT handler from trying to map claim types to .NET's ClaimTypes class types.
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationScheme = IdentityServerConstants.authenticationScheme, //Cookies
                AutomaticAuthenticate = true,
                CookieName="Hera Cookies",
                CookieSecure = CookieSecureOption.Never
            });
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            var authOptions = new OpenIdConnectOptions()
            {
                AuthenticationScheme = "Oidc",
                SignInScheme = IdentityServerConstants.authenticationScheme, //Cookies
                Authority = Configuration["AppSettings:LoginServer"], //IdServer path
                RequireHttpsMetadata = false,
                ClientId = Configuration["AppSettings:LoginClientId"],
                AutomaticChallenge = true,
                ResponseType = "code id_token token",
                Scope = { "openid", "heraTest", "offline_access", "email" },
                SaveTokens = true,
                Events = new OpenIdConnectEvents()
                {
                    OnAuthorizationCodeReceived = async ctx =>
                    {
                        var tokenClient = new TokenClient(IdentityServerConstants.TokenEndpoint,
                                                          IdentityServerConstants.IDS3_ClientId,
                                                          IdentityServerConstants.IDS3_Secret);
                        var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(ctx.TokenEndpointRequest.Code, ctx.TokenEndpointRequest.RedirectUri);
                        var id = ctx.Ticket.Principal.Identity as ClaimsIdentity;
                        id.AddClaim(new Claim(IdentityServerConstants.refreshTokenClaimId, tokenResponse.RefreshToken));
                        await Task.FromResult(0);
                    },
                    OnTokenValidated = async ctx =>
                    {
                        // Code to Modify incoming claims
                        AugmentAuthenticationClaims(ctx);
                        await Task.FromResult(0);
                    }
                }
            };
            app.UseOpenIdConnectAuthentication(authOptions);
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Main}/{action=Index}/{id?}"
                );
            });
        }`

**Comment by brockallen** [comment]
> RC 1 upgraded to RC 2

I assume you mean ASP.NET Core here.

All of the manual stuff you're doing in the Events is/should already be done for you by the ASP.NET Core OIDC MW -- just configure the client secret and they perform all the hybrid code exchange for you.

**Comment by brockallen** [comment]
> "code id_token token"

You can also probably just do "code id_token".

**Comment by jessicassw** [comment]
Yes, I meant ASP.NET Core, old habits (relatively speaking) die hard :-)

Thanks so much for your quick response. Adding the client secret to the OpenIdConnectOptions did the trick!  Cookie came through after that without any problems.
