### ISSUE TITLE
Double check the token sent against the MVC cookie, when configured in the same app

### ISSUE THREAD

**Issue by jorgecavaleiro** [IdentityServer/IdentityServer3#2977]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Question:
I'm currently using both the "UseOpenIdConnectAuthentication" middleware for WebUI application and the "UseIdentityServerBearerTokenAuthentication" for verifying the api requests made by the application to the Web Api hosted in the same website (the JWT is sent in each api request).

In my custom AuthorizeAttribute implementation I wish to double check the openId.connnect cookies sent by the browser against the Request.Identity in order to see if the User matches.
Is this possible to implement?

Thank you very much

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
