### ISSUE TITLE
Access Request headers in custom user service

### ISSUE THREAD

**Issue by svrooij** [IdentityServer/IdentityServer3#2978]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We have a custom UserService (that works perfectly, for saving external claims to db), but for logging purposes I would like to access the x-forwarded-for header (and save the client IP in the logs).

In several questions I found that you'll need to inject the OwinContext in the userService, but I couldn't find any working samples of this.

Do you have a code sample how to declare and register it?

**Comment by brockallen** [comment]
Inject the `OwinEnvironmentService` to access the request info.

**Comment by svrooij** [comment]
Thanks @brockallen but I really have no clue how to do that. Could you send me to the right documentation page, or a sample in combination with a custom UserService

**Comment by scottbrady91** [comment]
Something like this:

```
private readonly OwinEnvironmentService environmentService;

public CustomUserService(OwinEnvironmentService environmentService) {
    this.environmentService = environmentService;
}
```

Since the `OwinEnvironmentService` is already available in the Identity Server DI container, all you need to do is add it to your UserService's constructor (this is constructor injection).

You can then use the `OwinEnvironmentService` to gain access to the OwinContext.

**Comment by FatherTime1** [comment]
I have not seen a successful implementation of this with StructureMap, could you point me in the right direction.  

I have a constructor like so

 public CustomRequestValidator(OwinEnvironmentService owinEnvironmentService)

However I am using structure map so when I configure the factory and try and locate the CustomRequestValidator I get 

StructureMap.StructureMapConfigurationException: 'No default Instance is registered and cannot be automatically determined for type 'IDictionary<String, Object>''

I am trying to let StructureMap know how to return an instance of IOwinContext to provide to the constructor for OwinEnvironmentService constructor, I think I am in a chicken and egg problem.

That Context I want is going to be created by IdentityServer,
