### ISSUE TITLE
"Refresh token too long" error on token refresh attempt

### ISSUE THREAD

**Issue by evgenisokolov** [IdentityServer/IdentityServer3#2980]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I'm using resource owner flow for my Web API application. Now I'm trying to implement some functionality basing on token refresh. It seems that /connect/token endpoint rejects my tokens, because they too long. Se below what I'm doing:

1) Get token for user sending request to /connect/token endpoint with grant type "password". Currently I'm receiving tokens of length 915 symbols.

2) Try refresh token sending request to /connect/token endpoint with grant type "refresh_token". I post refresh_token parameter with token from step 1. Then I receive an error "invalid_grant". Please see log message below

### Relevant parts of the log file

```
Refresh token too long
 {
  "ClientId": "my_client_id",
  "ClientName": "My Client Name",
  "GrantType": "refresh_token",
  "Raw": {
    "client_id": "my_client_id",
    "client_secret": "******",
    "grant_type": "refresh_token",
    "refresh_token": "my_long_long_looooong_token here"
  }
}
```

**Comment by brockallen** [comment]
Can you show us what your refresh token looks like?

**Comment by evgenisokolov** [comment]
It looks like this:
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwczovL2xvY2FsLmF1dGguY29tL2lkZW50aXR5IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbC5hdXRoLmNvbS9pZGVudGl0eS9yZXNvdXJjZXMiLCJleHAiOjE0NjU5MTcyMzAsIm5iZiI6MTQ2NTkxMzYzMCwiY2xpZW50X2lkIjoianMiLCJzY29wZSI6ImFwaSIsInN1YiI6IjFkMmExMzc4LTI5MTktNDhlMy1iNjgzLTY2YTcyMGExM2M4OSIsImF1dGhfdGltZSI6MTQ2NTkxMzYxNCwiaWRwIjoiaWRzcnYiLCJlbWFpbCI6Imdsb2JhbEBhZG1pbi5jb20iLCJwZXJtaXNzaW9ucyI6Int9IiwidXNlcl90eXBlIjoiR2xvYmFsQWRtaW4iLCJhbXIiOlsicGFzc3dvcmQiXX0.p-bK89B8P7QqGytB942RS6Rw6YPWiars8XFhr8JCq_KedbB_rDOUw6NmH7dqhkDVYbnny-ZXv4KWoc7Ib3cu9mGrKXe4xgQ_txr6vD0i4QI2iEcIr_vqqRfqxJXsbQt8MNO6BxzrH2d-deNPY-o3HfRvBgC4l5Xk8vUc3xRQiGpkV7be6KycNzWhyDEd5CNeBw9xzFNFiypD08kleuEb2cq8cUPLNQh766iV4NW3RoOQQZjFl9gYpiutzLTmQg4KkNnES1aeAAMydw2UbteuzCZNhinzhGDsyCPNX9nN6_4nkkEkAsuzpUsBNO7LYS2Gf2ovr7QuwZKFSg5hU9VkiA

My guess is that it's encoded. Am I need to decode it to refresh?

**Comment by leastprivilege** [comment]
that's not a refresh token. A refresh token is just a random number - this looks like a JWT (try to decode with http://jwt.io).

**Comment by evgenisokolov** [comment]
Thanks! But what I should pass as a refresh_token?

**Comment by leastprivilege** [comment]
the refresh token. Check the docs/spec/samples.

**Comment by leastprivilege** [comment]
all set?

**Comment by smalot** [comment]
where can I find a full doc on HEADER and POST data to refresh a given token ?
reading RFC doesn't fix the matter.

Many thanks

**Comment by leastprivilege** [comment]
What information are you missing that is not here:
https://tools.ietf.org/html/rfc6749#section-6

Sorry this is an issue tracker for identityserver - not a general purpose forum to explain specs.

Please use SO for that.
