### ISSUE TITLE
How to get the logfile up and running

### ISSUE THREAD

**Issue by rogersbrad** [IdentityServer/IdentityServer3#2981]
- [ no ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
The steps to get logging setup are not clear.  It would be nice to have them in a literal 123 format of get this, install that.  It took hours to look at logging. 

**There is no IdentityServer3 specific configuration required - you just need to configure one of the above logging frameworks in your host.

Configuring Diagnostics

The LoggingOptions class has the following settings:

EnableWebApiDiagnostics
If enabled, Web API internal diagnostic logging will be forwarded to the log provider
WebApiDiagnosticsIsVerbose
If enabled, the Web API diagnostics logging will be set to verbose
EnableHttpLogging
If enabled, HTTP requests and responses will be logged**

LoggingOptions ?  No results found.  Cannot figure out how to follow these steps.
 so far,

I installed serilog.  I try to add the code from your example into startup.cs:

**Example: Using Serilog to log to System.Diagnostics tracing
The following example wires up Serilog to log to the diagnostics trace (put that e.g. in Startup or in your hosting code):**

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Trace()    <---no, Trace gets an error
    .CreateLogger();

 
The example says this:

error, there is no Trace that accepts zero arguments.  No other information is found about Trace.  Have to take out the line Write to trace().     After some web searches? found something related to having to put info for logging into web.config, but whats there now is 

<add name="xml" type="System.Diagnostics.XmlWriterTraceListener" initializeData="C:\logs\IdMgr.svclog" />

I manually created the folder c:\logs  (was never spelled out, but it works).   but now its capturing a log file in xml 

`<E2ETraceEvent xmlns="http://schemas.microsoft.com/2004/06/E2ETraceEvent"><System xmlns="http://schemas.microsoft.com/2004/06/windows/eventlog/system"><EventID>0</EventID><Type>3</Type><SubType Name="Information">0</SubType><Level>8</Level><TimeCreated SystemTime="2016-06-14T19:39:40.4712381Z" /><Source Name="IdentityManager" /><Correlation ActivityID="{4e225428-15d0-41bf-8c46-06a5f26859d3}" /><Execution ProcessName="iisexpress" ProcessID="11952" ThreadID="1" /><Channel/><Computer>COE4761</Computer></System><ApplicationData>Owin.IdentityManagerAppBuilderExtensions: Starting IdentityManager configuration</ApplicationData></E2ETraceEvent><E2ETraceEvent xmlns="http://schemas.microsoft.com/2004/06/E2ETraceEvent"><System xmlns="http://schemas.microsoft.com/2004/06/windows/eventlog/system"><EventID>0</EventID><Type>3</Type><SubType Name="Information">0</SubType><Level>8</Level><TimeCreated SystemTime="2016-06-14T19:42:00.4672381Z" /><Source Name="IdentityManager" /><Correlation ActivityID="{8e692872-c48f-4032-b13a-c4209b844be9}" /><Execution ProcessName="iisexpress" ProcessID="12640" ThreadID="1" /><Channel/><Computer>COE4761</Computer></System><ApplicationData>Owin.IdentityManagerAppBuilderExtensions: Starting IdentityManager configuration</ApplicationData></E2ETraceEvent>`

My original question was: where does this store the data in sql on the machine.  got derailed with the requirement to understand logging and use it.

now in web.config add this to the <system.diagnostics> under listeners,    <add name="myListener"
            type="System.Diagnostics.TextWriterTraceListener"
            initializeData="C:\logs\Trace.log" />

now its making a txt file, but is not logging activity

IdentityManager Information: 0 : Owin.IdentityManagerAppBuilderExtensions: Starting IdentityManager configuration

### Relevant parts of the log file

```
<log goes here>
```

**Comment by figuerres** [comment]
in my case I had installed and configured Log4Net in my project before I added identity server. I have a very basic log4net install with a sql server table as the log store.
when I added the identity server packages to my project they logged to the log 4 net table with no added setup.
if you want more details on my setup I can post some here.
I am not sure when they did with identity server but  log4net works for me.

**Comment by brockallen** [comment]
> .WriteTo.Trace() 

This is a serilog API, so you'd have to check their docs to know what trace config is needed. Personally, I find the Microsoft trace API confusing as hell and I always have to re-learn it, so when I'm doing a quick and dirty sample with IdSvr, I use: `.WriteTo.File(@"c:\log\idsvr.txt")`.

**Comment by ThisNoName** [comment]
Install-Package Serilog.Sinks.Trace
