### ISSUE TITLE
How to integrate main functionality into an MVC project?

### ISSUE THREAD

**Issue by rogersbrad** [IdentityServer/IdentityServer3#2982]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

The sample runs and I can see 1000s of users.  Where are these stored? there is no dbContext found in the solution, no database specified.  

How much of this is required to be integrated with an existing MVC project?  I think if they just share the same database path?  Then my mvc app should detect the roles/claims and this project could be left as-is to manage them;  but what will be needed in the MVC app to make use of the roles, claims, etc that this project is able to update/modify?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by rogersbrad** [comment]
So the question was moved to SO,
https://stackoverflow.com/questions/37840130/how-to-integrate-identityserver-v3-v4-into-mvc-to-manage-user-roles-and-claims

**Comment by rogersbrad** [comment]
Brock
Its IdentityManager I needed.  Your video was nicely done, I followed it to
setup/register IM on my mvc app.  Your demo code ran, I pointed to my DB.
My mvc app should see the roles it made.  it doesnt.

Somewhere I read that IM requires HTTPS?  ok, set the filter attirbute, set
https in the IIS settings.  what else is there?    just have a blank page.
 nothing at all.  zero, connection reset, no page try the firewall?  put
the exception, 44300 port open.  no page.  search, try, search, try.  it
must work tomorrow.  up past midnite desparate.

I just want custom roles set on the users.  why so much pain.  I assuredly
dont want IM to touch logins, thats working with AD and a custom login.
 just have the one code set roles, have my mvc 'see' those roles

Im happy to post in verbose writing to help others but not sure  what to do
to make https work.  my app is kind of big, over a year on one project,
lots of files,  we have less than 100 users, maybe https makes it secure'r
but on this project its a new mvc i just spun up to test adding IM to see
roles made by the other app.

turn on https?  always blank.   web/https I just never had to ever worry
about

if you can add clues or direction or why the https is blank or how to go
forward it would be so appreciated, thanks,  Bradley
