### ISSUE TITLE
how to set idsrv3 log flush interval?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#2984]
I used serilog and config the idsrv3 log in start up as below:
Log.Logger = new LoggerConfiguration()
               .MinimumLevel.Error()
               .WriteTo.File(@"D:\Temp\idsrv3\idsrv3Log.txt")
               .CreateLogger();
But it seems that the logger write to text file for several hours. Is there some setting like:
logger.FlushInterval= TimeSpan.From(...)?
Thank you very much!

**Comment by brockallen** [comment]
That's a serilog question.
