### ISSUE TITLE
Multiple "Token handle not found" errors

### ISSUE THREAD

**Issue by MartinWa** [IdentityServer/IdentityServer3#2985]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have set up an instance of Identity Server 3 to handle our login needs. We use it both to login clients to our web server and to allow API access using tokens. Everything is working but in the logs I see many occurrences of the same error (see log below). The error is always the same and the tokenhandle is same as well. I have tried to find what is causing these problems but I have no idea. (the error message is the same as in #2597 but we are not getting any validation errors)

We are hosing the server in an Azure Webapp but we are using [EF](https://github.com/IdentityServer/IdentityServer3.EntityFramework) for persistance. I have also tested with a Redis based implementation of ICache and it does not help. The server is set up to issue JWT tokens  instead of reference tokens so I do not even know why reference token validation is being done. We do have a lot of calls to /connect/accesstokenvalidation and they all fail with response code 400. The web API is using UseIdentityServerBearerTokenAuthentication with ValidationMode = ValidationMode.Both.

Does anyone know what can cause this errors and how I can fix this?

### Relevant parts of the log file

```
[Error] "Token handle not found""{ \"ValidateLifetime\": true, \"AccessTokenType\": \"Reference\", \"TokenHandle\": \"gdb06fnReQWc4b9db38acc3805c4afE6de\" }
```

**Comment by leastprivilege** [comment]
If you don't use reference tokens - set the validation mode to local only. You can also turn off the access token validation endpoint on the EndpointOptions. Maybe this gives you a hint from where it is called.

**Comment by MartinWa** [comment]
I found the problem. It turns out I had forgotten old code when I moved to ID3. There was a WebJob calling the API using a hard coded token. Changed it to use client credentials using Thinktecture.IdentityModel.Client and now the error is gone
