### ISSUE TITLE
Post Logout Redirect Url question

### ISSUE THREAD

**Issue by solidstore** [IdentityServer/IdentityServer3#2986]
We are using IdentityServer3 in our project to replace forms authentication and its working beautifully, but we are trying to determine if a feature we had before is possible to re-implement with IdSrv.

We automatically logout users if they are idle for a period of time. Currently, we have configured a single post logout uri which is shown to the user when the logout event occurs. Is it possible to somehow maintain the url that the user was on when they went idle (including querystring).

I realize that we could add multiple post logout url (painful), but I couldn't include all the possible the querystrings.

Do you think a feature like this is possible for us to re-implement now that we are using IdentityServer?

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
