### ISSUE TITLE
how to issue identity token?

### ISSUE THREAD

**Issue by bakamaru** [IdentityServer/IdentityServer3#2988]
Hello everyone,Currently i'm trying to issue id_token for the mobile application and is ok if i choose web based authentication with consent screen but what i want to have is directly issue id_token instead of access token( may be using client crential flow or may be other still no idea).
I've tried different ways but got no luck.
Ive also found that response_type=id_token will return identity token but seems like its only possible with form post(direct) which is not needed for me.
Can any one help me achieve this? or can't happen. Please explain.
Thank you

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
