### ISSUE TITLE
access_token claims are not availible when querying the UserInfoEndpoint

### ISSUE THREAD

**Issue by Studentblanchard** [IdentityServer/IdentityServer3#2989]
### Question / Issue
Using hybrid flow.

After initial authentication, I recieve the access token and id token. The access token contains a claim `ticket`, this is great. Now I query the UserInfoEndpoint to retrieve the applicationDto claim. I do so by passing the access token as a bearer token to the endpoint. In the UserInfoEndpoint when I inspect the context and I would expect to see the claims in the access token but I do not, the only claim in the context is `sub`. I need the `ticket` claim to query the user service and retrieve the applicationDto.

My question then is, how can I get the access_tokens claims (in particular the `ticket`) in the `ProfileDataRequestContext` at the UserInfoEndpoint?

My Scopes...

```
return new List<Scope>
{
	StandardScopes.OpenId //standard scope when dealing with open id connect
	,
	StandardScopes.OfflineAccess
	,
	new Scope
	{
		Name = "app",
		DisplayName = "app",
		Type = ScopeType.Identity,
		Claims = new List<ScopeClaim>
		{
			new ScopeClaim
			{
				AlwaysIncludeInIdToken = false,
				Name = GlobalConstant.ApplicationClaim,
				Description = "Application Role Information"
			}
		},
		IncludeAllClaimsForUser = false
	},
	new Scope
	{
		Name = "AppAccess",
		DisplayName = "AppAccess",
		Type = ScopeType.Resource,
		Claims = new List<ScopeClaim>
		{
			new ScopeClaim("ticket")
		},
		IncludeAllClaimsForUser = false
	}
};

```

My Client has all scopes allowed.

### Relevant parts of the log file

```
2016-06-15 13:52:11.508 -05:00 [Information] Creating userinfo response
2016-06-15 13:52:11.513 -05:00 [Information] Scopes in access token: "app openid offline_access appAccess"
2016-06-15 13:52:11.514 -05:00 [Information] Requested claim types: "applicationDto sub"
2016-06-15 13:52:11.514 -05:00 [Debug] Getting ProfileDataAsync
2016-06-15 13:52:11.514 -05:00 [Debug] The claims in the context...
2016-06-15 13:52:11.514 -05:00 [Debug] Claims sub 783bf872-b864-4042-853d-04fbcb7a505a
2016-06-15 13:52:11.514 -05:00 [Debug] The requseted claims...
2016-06-15 13:52:11.514 -05:00 [Debug] Cliams applicationDto
2016-06-15 13:52:11.514 -05:00 [Debug] Cliams sub
2016-06-15 13:52:11.514 -05:00 [Debug] Finished ProfileDataAsync
2016-06-15 13:52:11.514 -05:00 [Information] Profile service returned to the following claim types: "sub"
2016-06-15 13:52:11.514 -05:00 [Information] End userinfo request
2016-06-15 13:52:11.516 -05:00 [Information] Returning userinfo response.
```

As you can see the only claim in the context is `sub`, where I expect to see `ticket`.

**Comment by brockallen** [comment]
Unfortunately that's not supported. I'd suggest putting the ticket into the original id_token by marking the `ScopeClaim` as "always include"

**Comment by Studentblanchard** [comment]
I see, quick follow up question then. After I query the user info endpoint, I hit the token endpoint to get a refresh token and new access token, during the process in IdSrv, it hits the same method `GetProfileDataAsync` and in this case the `ticket` is there. See log output below...

```
2016-06-15 17:53:03.089 -05:00 [Information] Creating token response
2016-06-15 17:53:03.093 -05:00 [Information] Processing authorization code request
2016-06-15 17:53:03.096 -05:00 [Debug] Creating access token
2016-06-15 17:53:03.096 -05:00 [Debug] Getting ProfileDataAsync
2016-06-15 17:53:03.096 -05:00 [Debug] The issued claims
2016-06-15 17:53:03.096 -05:00 [Debug] The claims in the context...
2016-06-15 17:53:03.096 -05:00 [Debug] Claims sub 783bf872-b864-4042-853d-04fbcb7a505a
2016-06-15 17:53:03.096 -05:00 [Debug] Claims name dev.guser
2016-06-15 17:53:03.096 -05:00 [Debug] Claims amr password
2016-06-15 17:53:03.096 -05:00 [Debug] Claims idp IBEX
2016-06-15 17:53:03.096 -05:00 [Debug] Claims auth_time 1466031181
2016-06-15 17:53:03.096 -05:00 [Debug] Claims ticket eb6a4358-8758-47c1-95fd-b523c2f95865
2016-06-15 17:53:03.404 -05:00 [Debug] The requseted claims...
2016-06-15 17:53:03.404 -05:00 [Debug] Cliams ticket
2016-06-15 17:53:03.404 -05:00 [Debug] Finished ProfileDataAsync
```

So why is the ticket there in this case but not when I query the endpoint directly?

**Comment by brockallen** [comment]
Well, the user info endpoint and token endpoint have different code paths. So one includes the claims from the access token, then other doesn't. The user into endpoint, tho, it meant to supplement the claims in the id_token for the client. The token endpoint is producing an access token which is meant for the API. So, in a sense, they are two different audiences.

**Comment by Studentblanchard** [comment]
Ok, that makes sense, I will try to complete the flow using your previous sugestion using the id_token. Thanks for your help.

**Comment by Studentblanchard** [comment]
Hi Brock, after following your suggestion I still don't have the `ticket` in the ProfileDataRequestContext. Is there any way I can have access to this claim when querying the user info endpoint? 
The new scopes look like this... 

```
return new List<Scope>
{
	StandardScopes.OpenId //standard scope when dealing with open id connect
	,
	StandardScopes.OfflineAccess
	,
	new Scope
	{
		Name = GlobalConstant.EverestScope,
		DisplayName = GlobalConstant.EverestScope,
		Type = ScopeType.Identity,
		Claims = new List<ScopeClaim>
		{
			new ScopeClaim
			{
				AlwaysIncludeInIdToken = false,
				Name = GlobalConstant.ApplicationClaim,
				Description = "Everest Role Information"
			}
		},
		IncludeAllClaimsForUser = false
	},
	new Scope
	{
		Name = GlobalConstant.EverestAccessScope,
		DisplayName = GlobalConstant.EverestAccessScope,
		Type = ScopeType.Identity,
		Claims = new List<ScopeClaim>
		{
			new ScopeClaim(GlobalConstant.TicketClaim, true)
		},
		IncludeAllClaimsForUser = true
	}
};
```

Log output 
```
2016-06-16 12:23:08.023 -05:00 [Information] Creating userinfo response
2016-06-16 12:23:08.027 -05:00 [Information] Scopes in access token: "everest openid offline_access everestaccess"
2016-06-16 12:23:08.028 -05:00 [Information] Requested claim types: "applicationDto sub ticket"
2016-06-16 12:23:08.028 -05:00 [Debug] Getting ProfileDataAsync
2016-06-16 12:23:08.028 -05:00 [Debug] Claims in Claims in the context...
2016-06-16 12:23:08.028 -05:00 [Debug]     "sub : 783bf872-b864-4042-853d-04fbcb7a505a"     
2016-06-16 12:23:08.028 -05:00 [Debug] Claims in Requested Claims...
2016-06-16 12:23:08.028 -05:00 [Debug]     "applicationDto"     
2016-06-16 12:23:08.028 -05:00 [Debug]     "sub"     
2016-06-16 12:23:08.028 -05:00 [Debug]     "ticket"     
2016-06-16 12:23:08.028 -05:00 [Debug] Claims in Issued Claims...
2016-06-16 12:23:08.028 -05:00 [Debug]     "sub : 783bf872-b864-4042-853d-04fbcb7a505a"     
2016-06-16 12:23:08.028 -05:00 [Debug] Finished ProfileDataAsync
```

**Comment by brockallen** [comment]
For the identity scope do you have a ScopeClaim with the claim type of "ticket" and "always include"?

**Comment by Studentblanchard** [comment]
This? 

```
new Scope
{
	Name = "appaccess",
	DisplayName = "appaccess",
	Type = ScopeType.Identity,
	Claims = new List<ScopeClaim>
	{
		new ScopeClaim(GlobalConstant.TicketClaim, true)
	},
	IncludeAllClaimsForUser = true
}
```

Yup

**Comment by CuongPham459** [comment]
Hi everyone,

I'm using access_token to get claims from UserInfoEndpoint but claims return null. My project which I'm building IdentityServer3 with ASP.NET Identity.

My clients....
public class Clients
    {
        public static List<Client> Get()
        {

            return new List<Client>
            {
                // no human involved
                new Client
                {
                    ClientName = "Silicon-only Client",
                    ClientId = "silicon",
                    Enabled = true,
                    AccessTokenType = AccessTokenType.Reference,

                    Flow = Flows.ClientCredentials,

                    ClientSecrets = new List<Secret>
                    {
                        new Secret("F621F470-9731-4A25-80EF-67A6F7C5F4B8".Sha256())
                    },

                    AllowedScopes = new List<string>
                    {
                        "api1"
                    },
                    AccessTokenLifetime = 300
                },

                // human is involved
                new Client
                {
                    ClientName = "Silicon on behalf of Carbon Client",
                    ClientId = "carbon",
                    Enabled = true,
                    AccessTokenType = AccessTokenType.Reference,

                    Flow = Flows.ResourceOwner,

                    ClientSecrets = new List<Secret>
                    {
                        new Secret("21B5F798-BE55-42BC-8AA8-0025B903DC3B".Sha256())
                    },

                    AllowedScopes = new List<string>
                    {
                        "api1"
                    },
                    AccessTokenLifetime = 300
                }
            };
            
        }
    }

and My Scopes.....
public class Scopes
    {
        public static List<Scope> Get()
        {
            return new List<Scope>
        {
            new Scope
            {
                Name = "api1"
            }
        };
        }
    }

And My API....
// this api works nice. It return token and somthing else.
[Route("token")]
        [HttpPost]
        public IHttpActionResult GetToken(RequiredTokenModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            else
            {
                if (string.IsNullOrEmpty(model.clientId) || string.IsNullOrEmpty(model.clientSecret) ||
                    string.IsNullOrEmpty(model.userName) || string.IsNullOrEmpty(model.password) || string.IsNullOrEmpty(model.scope))
                {
                    return BadRequest("Check required fields again.");
                }
                else
                {
                    var currentClaimsIdentity = HttpContext.Current.User.Identity as ClaimsIdentity;
                    var client = new TokenClient(
                            "https://localhost:44370/core/connect/token",
                            model.clientId,
                            model.clientSecret);
                    var result = client.RequestResourceOwnerPasswordAsync(model.userName, model.password, model.scope).Result;
                    var expirationDateAsRoundtripString =
                    DateTime.SpecifyKind(DateTime.UtcNow.AddSeconds(result.ExpiresIn), DateTimeKind.Utc).ToString("o");
                    result.Json.Add("expires_at", expirationDateAsRoundtripString);

                    return Ok(result);
                }
            }
        }

[Route("me/{token}/{username}")]
        [HttpGet]
        public async Task<IHttpActionResult> GetCurrentUser(string token, string userName)
        {

            HttpClient client = new HttpClient();
            client.SetBearerToken(token);

            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));

            var result = await _repo.GetUserInformation(userName);

            return Ok(result);
        }

How can I do to fix this?
Many thanks.

**Comment by Studentblanchard** [comment]
After trial and error, the final solution was to cache the ticket in IdSrv and use the sub value as the key, that way at the user info endpoint, 1. we always have the key to the cache (sub must be present) 2. The ticket can then be used to query the application service for more claims.

Thanks for clearing things up. Closing this now.
