### ISSUE TITLE
Claims in JWT vs Claims Transformation in Resource

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#2993]
Hey everyone! :wave:

I have an API resource, which i grant my clients (web app and iOS app) access to via a _resource scope_. 

**Question 1**: If i want to do claims-based authorization in my API (e.g a claim called `CanViewQuestions`, that only _some_ users have), should i:

a) Use IdentityServer, e.g during authentication figure out if the user has that claim and add it to the JWT
b) Just put the _subject_ (e.g userId) claim in the JWT, and look that up in the API and perform claims-transformation?

I'm currently doing b), but wondering if this should be performed by the authorization server (e.g IdSrv) itself? 

Whats the recommended approach?

**Question 2**: If i have a background service (Azure Worker specifically) that i want to also give access to my API resource, i can use _client credentials flow_ to give this service an access token. Fine. But then how can i give this service the same claim above (`CanViewQuestions`)? I basically want to have my API to ensure a given resource requires the claim `CanViewQuestions`, but i don't care if the client is the web app (e.g end user involved), or the client (no end user). If the requestor has the claim, good to go. Am i going to have to 
a) Use claims-based transformation to see if the client is the service, then just add all the claims?
b) Embed the claims in the JWT (although i've read client credentials flow doesn't support claims)
c) Something else?

Many thanks!

**Comment by leastprivilege** [comment]
IMO app/resource specific claims are handled in the app/resource not the authentication service.

**Comment by RPM1984** [comment]
@leastprivilege so i'll take that response as for Question 1 - go option b? (e.g claims transformation). If that's the case - what _should_ i put in the JWT? Just the subject?

Also - thoughts on Question 2 please?

**Comment by leastprivilege** [comment]
only one question per issue - and this is not really an IdSrv issue right?

Please use StackOverflow for general questions.

**Comment by RPM1984** [comment]
Thanks.

https://stackoverflow.com/questions/37916051/claims-in-jwt-vs-claims-transformation-in-resource
