### ISSUE TITLE
Unable to use IdentityServer3 for WebApi Autheorization.

### ISSUE THREAD

**Issue by Neerajvisma** [IdentityServer/IdentityServer3#2996]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Hi Guys,

I am having trouble authorizing my client token in my WebApi. I am pretty much stuck here. Please help. This is my code.

            _****System.IdentityModel.Tokens.JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();
           
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = ConfigurationManager.AppSettings["Authority"], // URL to IdentityServer
                RequiredScopes = new[] { "sessionapi"},
               
               
            });

             var config = new HttpConfiguration();
             config.MapHttpAttributeRoutes();
            config.Filters.Add(new AuthorizeAttribute());
            app.UseWebApi(config);****_

And, this is the exception I get while debugging.

**_IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
    (
    IsReadOnly = False,
    Count = 1,
    Clause[0] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
    )
', 
token: '{"alg":"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256","kid":"6B7ACC520305BFDB4F7252DAEB2177CC091FAAE1","typ":"JWT"}.{"nbf":1466406364,"exp":1466409964,"iss":"http://connect.acc.prov.testaws.visma.com","aud":"http://connect.acc.prov.testaws.visma.com/resources","client_id":"sessionapi","scope":"sessionapi"}'._**

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
you are using an old version of idsrv4 to create tokens. Upgrade.

**Comment by Neerajvisma** [comment]
Hi again,

We upgrade to this version : 1.0.0-beta3
We still have the same problem. Any ideas?

**Comment by leastprivilege** [comment]
check the samples. They work - then work your way backwards to your code.
