### ISSUE TITLE
Client to client authorization

### ISSUE THREAD

**Issue by daletho** [IdentityServer/IdentityServer3#2999]
### Question

Hi there, first off thanks for all the hard work and effort that you've put into this project, it has been great to work with and a big addition to the open source community.

I am in the process of implementing IdentityServer3 in our company but I am not sure of the best way to handle client to client authorization.

**This is a summary of our requirements:**
- We have multiple web site clients that our users access. These are configured using the AuthorizationCode flow. Lets call these **_WebSiteClientA_**, _**WebSiteClientB**_.
- We have multiple WebAPI clients as back end services that could be accessed by either a client (**_WebSiteClientA_**, **_WebSiteClientB_**) or a user (who has access to **WebSiteClientA** or **_WebSiteClientB_**). Lets call this **_WebAPIClientA_**.

Note: Our company owns the users identity as well as all clients.

Initially I though we could configure **_WebAPIClientA_** using the ClientCredentials flow. Then **_WebSiteClientA_** \ **_WebSiteClientB_** would be configured with the client credentials for **_WebAPIClientA_** and could generate an access token when it required access to **_WebAPIClientA_**, or alternatively generate an access token with limited scopes and hand this access token to the user so the user can access **_WebAPIClientA_** directly from the client side.

This would meet almost all our our requirements except 1 big one, we also want to be able to manage what scopes a client has access to for another client and with the approach of using the ClientCredentials flow anyone with the client credentials would be able to generate access tokens for all scopes under that client. ie **_WebSiteClientA_** should be able to generate an access token for **_WebAPIClientA_** with read & write scopes but **_WebSiteClientB_** should only be able to generate an access token for **_WebAPIClientA_** with read scopes.

In my mind the client\identity server conversation would be:
**_WebSiteClientA_** makes a request to the identity server for an access token **_WebAPIClientA_** with scope X and provides the client secret for **_WebSiteClientA_**. The identity server then says yes, you are **_WebSiteClientA_** and we can see from our records you have access to **_WebAPIClientA_** with scope X, here is an access token.

Is this possible or am I looking at this in the completely wrong way and there is maybe a better approach to meeting the requirements?

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by daletho** [comment]
Ok sorry about that, will repost on StackOverflow. Thanks!
