### ISSUE TITLE
API Resource not recognizing token from client credentials flow

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#3000]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi guys, I can't figure out how to get my API resource to recognize any claims from a client using _client credentials_ flow. The `User` in the API is just a _Windows Identity_ with **no claims**. I expected the audience/client identifier etc claims to come in.

The same API resource/auth server setup works fine for _authorization code_ flow, so it must be something missing in my client configuration, or access token validation MW?

**Client config**

```
new Client
                {
                    Enabled = true,
                    ClientName = "WQWR,
                    ClientId = "homely-wqwr,
                    Flow = Flows.ClientCredentials,
                    ClientSecrets = new List<Secret>
                    {
                        new Secret("ssh".Sha256())
                    },
                    AllowedScopes = new List<string>
                    {
                        "homely_api"
                    },
                    AccessTokenType = AccessTokenType.Jwt,
                    AccessTokenLifetime = int.MaxValue
                }
```

**API resource setup**
```
.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = WebConfig.AuthServerHost,
                    RequiredScopes = new[] { "homely_api" },
                })
```

### Relevant parts of the log file

```
22 Jun 2016 11:09:34.835 06/22/2016 11:09:42 [Information] Start token request Info
» 22 Jun 2016 11:09:34.835 06/22/2016 11:09:42 [Debug] Start client validation
» 22 Jun 2016 11:09:34.835 06/22/2016 11:09:42 [Debug] Start parsing Basic Authentication secret
» 22 Jun 2016 11:09:34.836 06/22/2016 11:09:42 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
» 22 Jun 2016 11:09:34.836 06/22/2016 11:09:42 [Information] Secret id found: "homely-wqwr" Info
» 22 Jun 2016 11:09:34.836 06/22/2016 11:09:42 [Debug] Cache miss: homely-wqwr
» 22 Jun 2016 11:09:34.836 06/22/2016 11:09:42 [Debug] Secret validator success: "HashedSharedSecretValidator"
» 22 Jun 2016 11:09:34.838 06/22/2016 11:09:42 [Information] Client validation success Info
» 22 Jun 2016 11:09:34.838 06/22/2016 11:09:42 [Information] Start token request validation Info
» 22 Jun 2016 11:09:34.838 06/22/2016 11:09:42 [Information] Start client credentials token request validation Info
» 22 Jun 2016 11:09:34.838 06/22/2016 11:09:42 [Debug] Cache miss: homely_api
» 22 Jun 2016 11:09:34.838 06/22/2016 11:09:42 [Information] Client credentials token request validation success Info
» 22 Jun 2016 11:09:34.838 06/22/2016 11:09:42 [Information] Token request validation success { "ClientId": "homely-wqwr", "ClientName": "WQWR, "GrantType": "client_credentials", "Scopes": "homely_api", "Raw": { "grant_type": "client_credentials", "scope": "homely_api" } } Info
» 22 Jun 2016 11:09:34.838 06/22/2016 11:09:42 [Information] Creating token response Info
» 22 Jun 2016 11:09:34.838 06/22/2016 11:09:42 [Information] Processing token request Info
» 22 Jun 2016 11:09:34.839 06/22/2016 11:09:42 [Debug] Creating access token
» 22 Jun 2016 11:09:34.839 06/22/2016 11:09:42 [Debug] Creating JWT access token
» 22 Jun 2016 11:09:34.839 06/22/2016 11:09:42 [Information] End token request Info
» 22 Jun 2016 11:09:34.839 06/22/2016 11:09:42 [Information] Returning token response.
```

See screenshot from my client showing claims:
![capture](https://cloud.githubusercontent.com/assets/930343/16251649/29e7a22a-386b-11e6-81a0-517bcc0f31f6.PNG)

So that proves the client is getting the correct claims, but why doesn't my API recognize it?

Relevant packages used in my API:
```
<package id="IdentityModel" version="1.2.1" targetFramework="net451" />
  <package id="IdentityModel.Owin.ClaimsTransformation" version="1.0.0" targetFramework="net451" />
  <package id="IdentityServer3.AccessTokenValidation" version="2.3.1" targetFramework="net451" />
<package id="Nancy.MSOwinSecurity" version="2.0.0" targetFramework="net451" />
```

Can anyone help? I just want my API to identify the client, so i can then performs claims transformation.

**Comment by leastprivilege** [comment]
Not sure what "recognize" means. Check the claims on your claims principal inside the API.

**Comment by RPM1984** [comment]
@leastprivilege there are no claims in the principle. E.g it's `empty`. It's like the access token validation MW doesn't do anything to the Claims Principal.

**Comment by leastprivilege** [comment]
Oh - i see the problem. Int.MaxValue is not allowed - google for year 2038 problem ;)

**Comment by RPM1984** [comment]
@leastprivilege hahah thanks. Surprisingly `int.MaxValue`works for `AbsoluteRefreshTokenLifetime`.

If this is a constraint on the access token validation MW, then shouldn't it error during token request? E.g the client got a token which is seemingly valid, but can't be decrypted by the MW?

**Comment by RPM1984** [comment]
Also how did you figure this out? I'm guessing the token is being thrown out in the access token MW, but is there any logging we can turn on to figure this out? As it stands i had no idea this was the problem.

**Comment by leastprivilege** [comment]
it seems there is no logging in the MS JWT MW for this.

int.MaxValue is always a bad idea ;)

**Comment by RPM1984** [comment]
@leastprivilege okay feel free to close this then, but i thought you might want to open another issue in case others run into the same issue. I feel like the token endpoint should _error_ if a client configuration contains `int.MaxValue`...

**Comment by leastprivilege** [comment]
yea - maybe. Not sure if other JWT validation libraries have the same problem though.

**Comment by RPM1984** [comment]
Okay i'll leave up to you to decide what to do with this issue. Thanks for your help Dom!
