### ISSUE TITLE
External Identity Provider - ADFS

### ISSUE THREAD

**Issue by smuthiya** [IdentityServer/IdentityServer3#3001]
I am looking at using IdentityServer and ADFS as External identity provider - this will enable me to use windows domain user for which I can issue jwt and the applications (WCF and WebAPI) can use this token.

Now my question is if I am using Identity Server with ADSF - then still I need to provide the 'UserService' else I get error 'User Service not configured' - because its mandatory. 

So this means I have to implement my own IUserService - which internally uses the ADFS/AD to authenticate user? - If yes then is there any sample which does this? (AD based authentication for users)

**Comment by leastprivilege** [comment]
The user service is responsible for "translating" the claims from ADFS to your domain.

You need to implement the AuthenticateExternal method.

**Comment by smuthiya** [comment]
Thanks... I have now implemented the base UserService using 'UserServiceBase' class and done the override for the AutheticateExternalAsync

However from client (Console app) I am using 'TokenClient.RequestResourceOwnerPasswordAsync' - this results in call being made to UserService.AuthenticateLocalAsync - instead of AuthenticateExternalAsync.

What I need to do on client side to get it right? (I want to use AD user name and password from client)

**Comment by brockallen** [comment]
The easiest way is to change how your client uses IdSvr for obtaining tokens. This would mean using a browser to connect to IdSvr, which would then redirect to ADFS.
