### ISSUE TITLE
How to enable Authorization in WebAPI with AD and Database

### ISSUE THREAD

**Issue by morrismendoza** [IdentityServer/IdentityServer3#3004]
### Question
I am planning to expose a host of WEB API services to my third party clients and want to use IDS3 to give them access to certain resources of my API.

1.) What is the best flow to use to give to my 3rd Party clients that i can control via Active Directory and Database (depending on who the client is)? They will not login via OID so acquiring an access token directly from the identity server is preferred.

2.) How do i control authorization to the resources expose by my WebAPI?

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
