### ISSUE TITLE
Question on Redirect Magic OIDC MW

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#3005]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
I have an MVC Hybrid Flow Client and the Identity Server.

My Client is configured with Redirect Uris:
http://localhost:56675/Customer/Callback/

In the OpenIdConnectAuthenticationOptions, I also have this redirect Uri configured.

Now if I browse the client and go to 
http://localhost:56675/Home/ShowClaims

redirect will get me to Identity Server with

### Relevant parts of the log file

```
signin message passed to login: "{
  \"ReturnUrl\": \"https://sts.identity.de/core/connect/authorize?client_id=testClient&redirect_uri=http%3A%2F%2Flocalhost%3A56675%2FCustomer%2FCallback%2F&response_mode=form_post&response_type=code%20id_token&scope=openid&state=...",
}"
```

but after login, I'm automagically on 
http://localhost:56675/Home/ShowClaims

Everything works as I wanted, so I can have one registered redirect URL on my client with multiple "return URLs" behind, but what component will make this redirect to /Home/ShowClaims?
Though I would have to do this myself on /Customer/Callback/

On my AuthorizationCodeReceived EventHandler, I can see that the protocol message still says /Customer/Callback/, but in the authorizationTicket, the redirectUrl is /Home/ShowClaims?

![untitled](https://cloud.githubusercontent.com/assets/5556013/16294672/3a2bb290-3922-11e6-816c-1831fb6a9d4f.png)

Thanks..

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
