### ISSUE TITLE
why redirect to the login page when receive login request?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#3006]
When a third party application send login request to the idsrv3, the idsrv3 redirect it to the login page. The url flow as below:
1.http://www.idsrv3.com/core/connect/authorize?client_id=abc&response_type=code&...
2.http://www.idsrv3.com/core/login/signin=...
My question is why not render the login page in the step 1? Is there any security reasons or other reasons?
Thank you very much!

**Comment by leastprivilege** [comment]
separation of concerns. One is a protocol endpoint, one the login process. They are independent.

**Comment by Farwell-Liu** [comment]
Thank you leastprivilege!
