### ISSUE TITLE
Issue with response type id_token

### ISSUE THREAD

**Issue by skbelalmd** [IdentityServer/IdentityServer3#3010]
Hai, 
I am using google and facebook external providers.
However if I use local sign in, specifying response type=id_token token gives me access token (used for apis) and id token (used when I sign out).
But when I try to get both with idp as google/facebook, it gives error.
Only the response type token is supported, and I am not able to get Id-token which prohibits the auto redirect after logout.

Is there any other way to get id-token or call the logout endpoint without an id-token.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
