### ISSUE TITLE
How to use HttpClient to request Flows.ClientCredentials service

### ISSUE THREAD

**Issue by EdenLiang** [IdentityServer/IdentityServer3#3011]
I used Idsrv with ClientCredentials flow , using IdentityModel to set TokenClient And get okenResponse to receive accesstoken , And it work well with .net.

while other group(java team) want to use it too,while they just want to use HttpClient way to get accesstoken.

then How HttpClient get accesstoken?

I tried to set HttpClient.
```
url:"xxxx/connect/token",
```
Header
```
"client_id":"xxxxx"
"client_secret":"xxxx"
"grant_type","client_credentials"
"scope":"xxxx"
```
while it always return "error": "invalid_client"

Is there some suggest?

![image](https://cloud.githubusercontent.com/assets/9131600/16334536/1a32f6ca-3a34-11e6-9a10-ba6bc82ca1fe.png)

**Comment by johnkors** [comment]
The stuff you put in as headers should rather be in the body, as `x-www-form-urlencoded` values.

**Comment by EdenLiang** [comment]
Many thanks
