### ISSUE TITLE
Reflect changes in claims of token that already sent after customer made some update

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3#3012]
One of our clients - client A uses Javascript implicit client library to authenticate with us, in the id_token that we sent back to them contains first_name, last_name information of the authenticated customer, which both value in the id token are then used for displaying on the client pages.

We also has another openid client B which customer can manage their profile information e.g. to update their first name and last name, etc...

**Problem**
After customer made changes on their profile via client B (e.g. updated first name, etc..), the new value doesn't reflect on pages of client B, that is because the id token was original received is not reflected with new value.

is there a way that the client B can notify OP side to regenerate token, which then force client A to renew the token ? or you think this is completely madness? any suggestion for resolving this issue please?

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
