### ISSUE TITLE
Setting up Multiple AuthenticationTypes - PoP and Bearer in the same Resource API

### ISSUE THREAD

**Issue by raban33** [IdentityServer/IdentityServer3#3013]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### I am using IIS hosted Web API to use both Identity Server and Resource API and it works great for Bearer AuthenticationType. However when I use pop authentication Type(as outlined below), I get the following error after sucessfully clicking on Login button - 

Error
=========================
iisexpress.exe Information: 0 : 2016-06-24 14:30:31.085 -07:00 [Information] rendering login page
iisexpress.exe Error: 0 : 2016-06-24 14:30:52.038 -07:00 [Error] AntiForgery validation failed -- returning error page

============================

Code in the Resource API Server

============================================================
JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = $"{WebExtensions.CurrentPortalUrl()}/identity", 
                AuthenticationType = "PoP",

                RequiredScopes = new[] { "offline_access", "all_claims", "write", "read" },
                // this is used to extract the access token from the pop token

                
                //ClientId = "write",
                //ClientSecret = "secret",
                TokenProvider = new OAuthBearerAuthenticationProvider
                {
                    OnRequestToken = async ctx =>
                    {
                        ctx.Token = await DefaultPopTokenProvider.GetAccessTokenFromPopTokenAsync(ctx.OwinContext.Environment);
                    }
                }
                
            });

            // this registers the middleware that does the signature validation of the request against the pop token secret
           app.UseHttpSignatureValidation();

==========================================================

### Relevant parts of the log file

```
Error
=========================
iisexpress.exe Information: 0 : 2016-06-24 14:30:31.085 -07:00 [Information] rendering login page
iisexpress.exe Error: 0 : 2016-06-24 14:30:52.038 -07:00 [Error] AntiForgery validation failed -- returning error page

============================
```

**Comment by leastprivilege** [comment]
Our PoP implementation is experimental at this point (the specs are not done yet). We don't support pop and bearer on the same API endpoint

**Comment by claq2** [comment]
I got this too when hosting both my API and IdentityServer hosted in the same app. I moved the

    app.Map("/identity", idsvrApp => ... 

lines to be before 

    JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();
    app.UseIdentityServerBearerTokenAuthentication(...

and the problem disappeared. I'm guessing something in the lines that enable PoP was intercepting the antiforgery token before IdentityServer could examine it.
