### ISSUE TITLE
Connecting to a SQL Membership Database

### ISSUE THREAD

**Issue by danielbarnes1980** [IdentityServer/IdentityServer3#3014]
## Question / Issue

I am trying to setup the example MixIt.Identity.Server and on the line var db = new DefaultMembershipRebootDatabase(this.connString) I get the following error message 

Additional information: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

And I then use another example project CustomUserAccount using the the line            

  var svc = GetUserAccountService(db); connects to the database and all works.

They are both using the exact same connection string.  Does anybody have any ideas I just want to get the example project to work in the MIxIt Project.

Thanks in Advanced

**Comment by figuerres** [comment]
Can you point to the "MixIt" project ??  I did not find it in the samples area ?
the error message is that a contention string is not right ,  is MixIt based on MembershipReboot ?
I think there are at least 2 or 3 different ways folks are going about the tables they use and perhaps you are trying to connect with different database schemas ??  
I am aware of:
MembershipReboot
Microsoft Identity  2
IdentityServer (not Microsoft)

note that the name "Identity" gets used by Microsoft to mean one thing and "Identity Server" by Least Privilege to mean something else. just one of the places that we can get confused in all this jargon.

**Comment by danielbarnes1980** [comment]
Sorry I thought it was from the official website.  Its actually from this article https://cedric-dumont.com/tutorials/identityserver-v3-membershipreboot-angularjs-webapi-2-and-mvc-mix-it-introduction/identityserver-v3-membershipreboot-angularjs-webapi-2-and-mvc-mix-it-part-1/

And I believe the error message may actually have something to do with EntitiyFramework but I do not fully undertstand Entiity Framework so need to look into that I believe

**Comment by figuerres** [comment]
Entity Framework is a way to access a data store like SQL server, the message seems to show that the connection string used is not pointing to a reachable server.  a lot of apps use EF and some can share the same connection string if they need to.

**Comment by danielbarnes1980** [comment]
I am just using a normal connection string I would use for a normal database. 

  <connectionStrings>
    <add name="CustomDatabase" connectionString="Data Source=ComputerName;Initial Catalog=DefaultMembershipRebootDatabase;Integrated Security=True;User ID=user;Password=password" providerName="System.Data.SqlClient" />
  </connectionStrings>

The database doesn't exist though so I was assuming EF would create the database for me,  I may be wrong though

Thanks very much for your continued help here.

**Comment by danielbarnes1980** [comment]
Here is the connection string
`  <connectionStrings>
    <add name="CustomDatabase" connectionString="Data Source=ComputerName;Initial Catalog=DefaultMembershipRebootDatabase;Integrated Security=True;User ID=user;Password=password" providerName="System.Data.SqlClient" />
  </connectionStrings>`

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
