### ISSUE TITLE
GetSignInIdFromExternalProvider missing with WS-Federation

### ISSUE THREAD

**Issue by null-d3v** [IdentityServer/IdentityServer3#3016]
With a WS-Federation (ADFS) external provider, I'm seeing that the signInId cannot be obtained in the LoginExternalCallback. After logging in to the ADFS server, I post to the callback URI designated by the CallbackPath and then I am 302'd to LoginExternalCallback. It is unable to acquire the signInId, but the callback post included a wctx, so I'm assuming it should have been available.

Configuration
`
var wsFederationOptions = new WsFederationAuthenticationOptions
{
    AuthenticationType = WsFederationAuthenticationDefaults.
        AuthenticationType,
    CallbackPath = new PathString("/wsfed/"),
    Caption = "TEST",
    MetadataAddress = "https://[]/federationmetadata/2007-06/federationmetadata.xml",
    ...
    SignInAsAuthenticationType = signInAsType,
    Wtrealm = "[]",
};
appBuilder.UseWsFederationAuthentication(
    wsFederationOptions);
`

Logs
`
w3wp.exe Information: 0 : 06/27/2016 10:27:29 -05:00 [Information] (IdentityServer3.Core.Endpoints.AuthenticationController)
 External login requested for provider: "Federation"
w3wp.exe Information: 0 : 06/27/2016 10:27:29 -05:00 [Information] (IdentityServer3.Core.Endpoints.AuthenticationController)
 Triggering challenge for external identity provider
w3wp.exe Information: 0 : 06/27/2016 10:27:41 -05:00 [Information] (IdentityServer3.Core.Configuration.Hosting.CorsPolicyProvider)
 CORS request made for path: "/wsfed/" from origin: "[]" but rejected because invalid CORS path
w3wp.exe Information: 0 : 06/27/2016 10:27:41 -05:00 [Information] (IdentityServer3.Core.Endpoints.AuthenticationController)
 Callback invoked from external identity provider
w3wp.exe Information: 0 : 06/27/2016 10:27:41 -05:00 [Information] (IdentityServer3.Core.Endpoints.AuthenticationController)
 No signin id passed
`

CallbackPath post
`
wa:wsignin1.0
wresult:[]
wctx:WsFedOwinState=Sfm-WZC0GoesbvS26yp3oVfgK3f03BaGZSbAujEYI3UM-xGt5XhZbgGr8UPNv8k18UTKumJk_Z7PPz8RvsKjEy0d-oReSKP74REUlxxZhLp6JUjTlq4i16hZZy0EKfZAnngjVT-AVgY2prVL9kyeZ_-7oh8cGuXslgpjt9L_9keOf4_-hOwHhy3ZZ940siDGu9tO9mIHFNR0opyaB4jtUw
`

LoginExternalCallback request
`
cookie:SignInMessage.0836b4a367e24e0864d17b575eba2715=vPpDVlK8vgTAxF3Sed_HIYVFyMFPtqDbozOX6MnxXQAPFBfRaL2P63AOn3pcSpta0IUUm8ZMthZK0U_HvlCQisfSm18yoSBeaMFy1XtV3olMuXuyzxotSF8IWuKrikc877_VyNqLlaZsL0gljRtHAbw_3AB77rh_ZwqeuBYe7rUdp5in3gQcSdembuFZ-XaCO_ij-FFGpPE5dgSkG07bRE2SNWYbM8rK4NcF66P791SFvnFrDz1eK6L4rzkbdettg789IwtzG2f2EaeIQXRU_gNHM9vY9x_Af0J9ABC_NPgizErp3OUEgGicdSEU01hbH1R_VmcrisKmYoAXmXdtF4KLWRJt4RI5Ga9jISMZjJsXgkpOIQIQ53ahBRwnN2CwdL65pyrxpAh1tlxMVZykTWuU09qw5KM767-pCvbo80QsIHq0gXd0bnW0TSCTr_i3u01bDib1R0v9gZoPWH8ShoEbFRptQ3cZsLbVa02Ef_cb7zjUY1Cj06VmpFRKoAbv0j28xSE4K3kovIfYoNoJFA; idsrv.xsrf=vX7-SR-n6IwmSrrBFNhI0IzN7sfcFC3TFxL1DGBr-uuxVKRc1cbKwZsmuWSscbAw87Xqc5pVJrX3khuc4ngYkk-xcrjz0vA9aXzeb_ma9x8;
`

**Comment by leastprivilege** [comment]
Check our Core project - there is working ADFS support in it and compare.

**Comment by null-d3v** [comment]
It appears to be a problem in how the signing certificate from ADFS is being handled. With signing turned off, everything works beautifully. I'll update with what I find in how we're handling the signing for posterity.

**Comment by leastprivilege** [comment]
did you ever resolve this?

**Comment by null-d3v** [comment]
Hey! Sorry that I've been quiet on this, I'm just pretty sure it's been a bad certificate setup on my part. With no encryption certificate, everything works great. However, when I add the encryption certificate and read it using [this](http://chris.59north.com/post/Manually-configuring-OWIN-WS-Federation-middleware-and-accepting-encrypted-tokens) configuration, the post to the CallbackPath doesn't seem to take.

A post to the CallbackPath with no certificate will set the idsrv.external cookie and the redirect to the external callback works perfectly. When the certificate is used, the post to the CallbackPath sets no cookies, so the external callback will not process any data.
