### ISSUE TITLE
Support System.IdentityModel.Tokens.Jwt 5.0.0

### ISSUE THREAD

**Issue by sandord** [IdentityServer/IdentityServer3#3017]
I've upgraded my project to the latest release of System.IdentityModel.Tokens.Jwt (5.0.0).

Now I get a runtime exception in my host:

```
Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly
'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35'.
```

**Comment by leastprivilege** [comment]
We don't load that assembly - that must come from somewhere else. Stack trace?

**Comment by sandord** [comment]
Apparently it has something to do with Bearer Token Authentication:

```
System.TypeLoadException: Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Owin.IdentityServerBearerTokenValidationAppBuilderExtensions.<>c__DisplayClass9.<ConfigureLocalValidation>b__8()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Owin.IdentityServerBearerTokenValidationAppBuilderExtensions.UseIdentityServerBearerTokenAuthentication(IAppBuilder app, IdentityServerBearerTokenAuthenticationOptions options) in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\IdentityServerBearerTokenValidationAppBuilderExtensions.cs:line 46
   at MyHost.Startup.Configuration(IAppBuilder app) in C:\MyHost\MyHost\Startup.cs:line 46
```

**Comment by leastprivilege** [comment]
Well - 5.0 means breaking change. Maybe it's not compatible with the old OWIN middleware.

**Comment by zetanet** [comment]
Same problem here after upgrading ASP.NET MVC 5 project with latest library..

Code.

 ....
        app.UseOpenIdConnectAuthentication(New OpenIdConnectAuthenticationOptions() With { 
             .ClientId = ConfigHelper.ClientId, 
             .Authority = ConfigHelper.Authority, 
             **_.TokenValidationParameters = New IdentityModel.Tokens.TokenValidationParameters With {.RoleClaimType = "roles"},_** 
....

**Comment by leastprivilege** [comment]
Well - then don't use the v5 of system.identitymodel. It's not compatible.

**Comment by twilly86** [comment]
what's the fix for this? downgrading identity model to v4?

**Comment by leastprivilege** [comment]
yes

**Comment by human3820917** [comment]
@twilly86 - Did you uninstall "System.IdentityModel.Tokens.Jwt" first before running ...

Install-Package System.IdentityModel.Tokens.Jwt -Version 4.0.2.206221351

**Comment by Steven-X** [comment]
Cannot downgrade System.IdentityModel.Tokens.Jwt to 4.0.0.x:

 'System.IdentityModel.Tokens.Jwt 4.0.3.308261200' is not compatible with 'Microsoft.IdentityModel.Protocols 2.0.0 constraint: System.IdentityModel.Tokens.Jwt (>= 5.0.0)'.			0

**Comment by Zapnologica** [comment]
I to have updated all my nuget packages. I am using Azure AD B2C and after updating I get 
`not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. `

When I run the web app.

**Comment by leastprivilege** [comment]
As said before - 5.0 is not compatible with Katana. This is a Microsoft issue.

**Comment by jellebens** [comment]
Is microsoft doing anything about this issue?

**Comment by DarkBond** [comment]
You people broke something with version 5.1.2.  Version 4.0.1 works just fine.  After upgrading, I'm getting the error message:

```
Exception thrown: 'System.TypeLoadException' in mscorlib.dll
Additional information: Could not load type 'System.IdentityModel.DateTimeUtil' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

**Comment by leastprivilege** [comment]
We? Or Microsoft ;)

5.x is not compatible with Katana 3 - it is for .NET Core going forward. You need to stay on 4.x

**Comment by brockallen** [comment]
> 5.x is not compatible with Katana 3 - it is for .NET Core going forward. You need to stay on 4.x

And you can thank Microsoft that they did not properly document this or make it at all obvious.

**Comment by DarkBond** [comment]
Who said anything about Katana 3?  I have a WCF service.  Please explain to me how this is supposed to work going forward?  Are you saying that System.IdentityModel.Tokens.Jwt is not going to support WCF (and other native-API) based applications?  What other options are there for communicating with AAD to validate credentials?

**Comment by BrianMinister** [comment]
Understanding the difference between 4.x and 5.x would have been a lot clearer if 5.x was changed to have the word core in the namespace or file name. 

I burned through a day trying to understand my issue until I spotted this thread.

**Comment by brockallen** [comment]
> I burned through a day trying to understand my issue until I spotted this thread.

Please let Microsoft know -- they need to improve.

**Comment by hitendramalviya** [comment]
Why Microsoft not doing things properly now-a-days. I was burning since last 2 days. In last I came across this issue thank god.

**Comment by AnisTss** [comment]
+1 I wasted a day trying to resolve this.
Microsoft should know about this.

**Comment by kwaxi** [comment]
Is limiting the NuGet package version for now as proposed a way to go until the root problem is solved?

**Comment by kwaxi** [comment]
See https://github.com/aspnet/AspNetKatana/issues/7 and https://github.com/aspnet/AspNetKatana/pull/21

**Comment by coreyperkins** [comment]
Microsoft has made a big mess with their dependencies as of late. This isn't the fault of the idsrv guys, but it's sure messy for those of us who use libraries like System.IdentityModel.Tokens.Jwt.

**Comment by dawistah** [comment]
Messy is the word

**Comment by ursenix** [comment]
I didn't uninstall, instead I installed using:

`Install-Package System.IdentityModel.Tokens.Jwt -Version 4.0.2.206221351`

**The results:**
Attempting to gather dependency information for package 'System.IdentityModel.Tokens.Jwt.4.0.2.206221351' with respect to project 'Amelia.API', targeting '.NETFramework,Version=v4.6'
Gathering dependency information took 1.53 min
Attempting to resolve dependencies for package 'System.IdentityModel.Tokens.Jwt.4.0.2.206221351' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'System.IdentityModel.Tokens.Jwt 5.1.4'
Resolving dependency information took 0 ms
Resolving actions to install package 'System.IdentityModel.Tokens.Jwt.4.0.2.206221351'
Resolved actions to install package 'System.IdentityModel.Tokens.Jwt.4.0.2.206221351'
Retrieving package 'System.IdentityModel.Tokens.Jwt 4.0.2.206221351' from 'nuget.org'.
Removed package 'System.IdentityModel.Tokens.Jwt.5.1.4' from 'packages.config'
Successfully uninstalled 'System.IdentityModel.Tokens.Jwt.5.1.4' from Amelia.API
Adding package 'System.IdentityModel.Tokens.Jwt.4.0.2.206221351' to folder 'C:\Projects\amelia.api\AmeliaAPI\packages'
Added package 'System.IdentityModel.Tokens.Jwt.4.0.2.206221351' to folder 'C:\Projects\amelia.api\AmeliaAPI\packages'
Added package 'System.IdentityModel.Tokens.Jwt.4.0.2.206221351' to 'packages.config'
Successfully installed 'System.IdentityModel.Tokens.Jwt 4.0.2.206221351' to Amelia.API
Removing package 'System.IdentityModel.Tokens.Jwt.5.1.4' from folder 'C:\Projects\amelia.api\AmeliaAPI\packages'
Removed package 'System.IdentityModel.Tokens.Jwt.5.1.4' from folder 'C:\Projects\amelia.api\AmeliaAPI\packages'
Executing nuget actions took 2.65 sec
Time Elapsed: 00:01:34.7684661

**Comment by nikhilsarvaiye** [comment]
It will work but then you cannot add any other authentication like open id which required jwt 5.1.2

**Comment by shyamjiniranjan** [comment]
It is working  but after degrading from jwt 5.1.2 to jwt 4.x  i am not able to validate my token because JwtSecurityTokenHandler is expecting jwt 5.1.2. Please help me to validate token in this case.

**Comment by INGCRENGIFO** [comment]
any solution?

**Comment by ederbond** [comment]
Can anyone post an example of how to Validate a JWT Token using System.IdentityModel.Tokens.Jwt version="5.1.4" ?

**Comment by ederbond** [comment]
Here is an example of how to validade a JWT Token using System.IdentityModel.Tokens.Jwt version="5.1.4":

```csharp
            protected User ValidateJwtToken(string jwtToken)
{
    if (string.IsNullOrWhiteSpace(jwtToken))
        return null;

    var token = new JwtSecurityToken(jwtToken);

    var jwtIssuerSigningToken = ConfigurationManager.AppSettings["JwtIssuerSigningToken"];
    var decodedKey = TextEncodings.Base64Url.Decode(jwtIssuerSigningToken);

    var parameters = new TokenValidationParameters
    {
        ValidAudience = "YourApp",
        IssuerSigningKey = new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(decodedKey),
        ValidIssuer = "http://localhost:9001/",
        ClockSkew = new TimeSpan(0),
        ValidateLifetime = true
    };

    Microsoft.IdentityModel.Tokens.SecurityToken validatedToken = null;
    var principal = new JwtSecurityTokenHandler().ValidateToken(token.RawData, parameters, out validatedToken);

    return new User()
    {
        Id = principal.Claims.Single(x => x.Type == "UserID").Value,
        Name = principal.Claims.Single(x => x.Type == ClaimTypes.NameIdentifier).Value,
        CustomerStatus = principal.Claims.Single(x => x.Type == ClaimTypes.Role).Value.ToEnum(CustomerStatus.Anonymous),
        Email = principal.Claims.Single(x => x.Type == ClaimTypes.Email).Value,
        SessionId = principal.Claims.Single(x => x.Type == "SessionID").Value,
    };
}
```

**Comment by pierslawson** [comment]
Looking at the exception, it appears that the latest version of System.IdentityModel.Tokens.Jwt has a hardcoded dependency on version 9 of Newtonsoft.Json. If your project references version 10 or more you will get an exception thrown containing information along the lines of ""IDX10729: Unable to decode the header". If you keep looing into the Inner Exceptions you can see the Json Extensions are failing to initialise because it cannot find Newtonsoft.Json. I got around this by redirecting the assembly binding in my web.config:

```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

I'll see if there is an open issue on the Microsoft project.

**Comment by pierslawson** [comment]
The System.IdentityModel.Tokens.Jwt assembly deliberately targets version 9 of Newtonsoft.Json:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/765
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/701

It is not clear why they decided to specifically target 9 rather than 10... or if that was the only version available at the time.
