### ISSUE TITLE
role claims not returned from userinfo endpoint

### ISSUE THREAD

**Issue by stevengopmo** [IdentityServer/IdentityServer3#3018]
hello, I'm making the following request for tokens

````
/core/connect/authorize?client_id=goPMO.Impel&redirect_uri=https:%2F%2Flocalhost%2Fauth-popup.html&response_type=id_token token&scope=openid profile email roles&state=1c959662dc684d468e114287a7cb261e&nonce=7c0da93807d545eab2286407585c3599&display=popup

````
as you can see I'm including the roles scope, but when I call the user endpoint I do not get the role claims for the user.

In the logs I see this
````
06/27/2016 23:48:54 -04:00 [Information] 15   Creating userinfo response
06/27/2016 23:48:54 -04:00 [Information] 15   Scopes in access token: "openid profile email goPMO.Impel"
06/27/2016 23:48:54 -04:00 [Information] 15   Requested claim types: "sub name family_name given_name middle_name nickname preferred_username profile picture website gender birthdate zoneinfo locale updated_at email email_verified"
06/27/2016 23:48:54 -04:00 [Information] 15   Profile service returned to the following claim types: "sub given_name family_name"
06/27/2016 23:48:54 -04:00 [Information] 15   End userinfo request

```

For some reason it looks like my roles request didn't get included in the access token buy why?

**Comment by johnkors** [comment]
How are you defining your scopes/ claims? `AlwaysIncludeInIdToken` ?

https://identityserver.github.io/Documentation/docsv2/configuration/scopesAndClaims.html

**Comment by johnkors** [comment]
Also, the `Roles` scope is pr default an identity based scope (belongs in id_token), and not a resource scope (access token). 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Models/StandardScopes.cs#L302

To get roles from the userinfo endpoint, I guess you would first need to setup a new similar scope to roles that is of the resource type, and then ask for that as well in your authorize call so it can be in the access token you provide to the user info endpoint later.

**Comment by stevengopmo** [comment]
I'm not sure why the userinfo endpoint would only return identity claims.  There's nothing about that in the docs (https://identityserver.github.io/Documentation/docsv2/endpoints/userinfo.html).  
I have my resource scope setup like this

````
new Scope
                {
                    Name = "goPMO.Impel",
                    DisplayName = "Impelx",
                    Type = ScopeType.Resource,
                    Claims = new List<ScopeClaim>
                    {
                        new ScopeClaim(Constants.ClaimTypes.Name),
                        new ScopeClaim(Constants.ClaimTypes.Role)
                    }
                }
````

**Comment by stevengopmo** [comment]
plus, why is the log saying I've only requested Scopes in access token: "openid profile email goPMO.Impel" when you can see from the original request that I've included roles?

**Comment by leastprivilege** [comment]
Userinfo is an OpenID Connect concept - OIDC deals only with identity claims.

Userinfo is just an alternative way to get to claims that would otherwise be in an identity token. Think of an optimization mechanism to keep the id token smaller (and to be able to get update identity information).

**Comment by stevengopmo** [comment]
ok so why aren't I getting the roles in the user profile then?  I changed by scope to be 

````
        public static IEnumerable<Scope> Get()
        {
            return new[]
            {
                StandardScopes.OpenId,
                StandardScopes.Profile,
                StandardScopes.Email,
                StandardScopes.Address,
                StandardScopes.OfflineAccess,
                StandardScopes.RolesAlwaysInclude,
                StandardScopes.AllClaims,

                new Scope
                {
                    Name = "goPMO.Impel",
                    DisplayName = "Impelx",
                    Type = ScopeType.Resource,
                    Claims = new List<ScopeClaim>
                    {
                        new ScopeClaim(Constants.ClaimTypes.Name),
                        new ScopeClaim(Constants.ClaimTypes.Role, true)
                    }
                }
            };
        }

````

**Comment by figuerres** [comment]
In my case I never did figure out what to do so I wrote my own server class to handle roles and gave up on Oauth / Open ID  as confusing and to complex to spend more time on right now.
all the flows and token types and client types and claim times and scopes .... I am sure somewhere it has a good reason but for the average developer it's just a big confusing layer of stuff.

**Comment by stevengopmo** [comment]
ah, stoopid on my part.  bug in our code where we didn't send request for roles.  One question outstanding though, @leastprivilege you say 

> Think of an optimization mechanism to keep the id token smaller

How can I keep the id token smaller?  It looks like I will get in userinfo whatever I got when I requested the id token because that's what is embedded in the access token.  I suppose I could just request the access token then make a call to userinfo to get the related identity claims.  Is that what you mean?

**Comment by johnkors** [comment]
1. Don't ask for many scopes while doing an implicit authorize call w/ id_token token
2. Later, ask for a access token to use for the userinfo endpoint, where you _do_ include all the scopes you need.

=> small id_token, but needs more calls to get the same userinfo data in the back channel.

This way the id_token in the implicit flow is still kept small, but you can receive the same data.

**Comment by toqueteos** [comment]
@johnkors How does one ask for an access token later one when you only have an id_token?
