### ISSUE TITLE
How does IdentityServer prevent CSRF?

### ISSUE THREAD

**Issue by zik319** [IdentityServer/IdentityServer3#3019]
I've been using IdentityServer for a while now, excellent product!
I read the RFCs however it still isn't clear to me how idSrv implements the CSRF protection.
I'd love some clarification on the issue of CSRF protection since I haven't found a write-up specific to idSrv.
Thanks

**Comment by leastprivilege** [comment]
We use the typical anti-forgery token approach - very similar to how MVC does it.
