### ISSUE TITLE
Login endpoint returns HTTP Status 200

### ISSUE THREAD

**Issue by RicardoCampos** [IdentityServer/IdentityServer3#3020]
Hi,
We have had a pen test and one of the vulnerabilities was highlighted as such:-

> When sending login credentials to the website in a POST request, the server returns an HTTP 200 response code. 
- When the server responds with this code, browsers may cache the data sent in the request. 
- This could allow a scenario in which an attacker with access to the user's workstation obtains the data from the browser's 
cache.
Suggested Remediation:
The application should return a HTTP Redirect (e.g. HTTP 302 Redirect) in response to a sensitive request. 
- This will cause the user's browser to cache the page redirected to, instead of the POST request.

Since this has been highlighted, we are under pressure to correct it. However the only way I can see to do it is to creating a custom endpoint that wraps around the Idsvr3 login endpoint and ensure that users get redirected there to log in?

I've raised this as an issue since it was a recommendation from a pen test company- it would be interesting to hear your thoughts.

**Comment by leastprivilege** [comment]
I am pretty sure we are setting no-cache headers. @brockallen knows for sure.

**Comment by brockallen** [comment]
The login endpoint typically issues a 302, not a 200. I suspect you mean the authorization endpoint. Regardless, both of these endpoints issue these response headers:

```
Cache-Control: no-store, no-cache, max-age=0, private
Pragma: no-cache
```

**Comment by RicardoCampos** [comment]
Thanks @brockallen - is this new in the 2.x branch? We are currently still running 1.x but plan to upgrade soon.

**Comment by brockallen** [comment]
Pretty sure that's been there from the beginning. You can also look at your own server (via fiddler, for example) and check.

**Comment by RicardoCampos** [comment]
I checked, I should have verified the pen testers findings. It returns 200 on the GET to /login but the POST to /login does indeed return a 302.

**Comment by brockallen** [comment]
The login page emits the same cache headers for that scenario as well. Not sure there's much else we can do for the issue reported.

**Comment by RicardoCampos** [comment]
Okay, thanks Brock. The cache headers weren't mentioned in the report; they might not have considered them.
