### ISSUE TITLE
setting CookieName in CookieAuthenticationOptions break AuthenticationType value

### ISSUE THREAD

**Issue by firez5566** [IdentityServer/IdentityServer3#3021]
In my setup I have a few applications using IdentityServer 3 since a few months. I use cookies authentication combined with OpenIdConnect authentication and everything works like a charm.
In my start.cs file in the Configuation I define CookieAuthenticationOptions objects with different AuthenticationType values, for example I have for app1

```
app.UseCookieAuthentication(new CookieAuthenticationOptions {  
   AuthenticationType = "miIdentityClientCookies"  
});
```

and for app2 I have

```
app.UseCookieAuthentication(new CookieAuthenticationOptions {
	AuthenticationType = "miWikiCookies"
});
```

If I check the cookies I can see the suffix properly set

![image](https://cloud.githubusercontent.com/assets/11734614/16413591/1c0570de-3d33-11e6-8994-c50327a7c5de.png)

Now I want to change the prefix from the default value ".AspNet" to ".miCookies". In CookieAuthenticationOptions object I set  also CookieName, here is the code

```
app.UseCookieAuthentication(new CookieAuthenticationOptions {
	CookieName = ".miCookies",
	AuthenticationType = "miIdentityClientCookies"
});
```

The prefix changes correctly but it seems that suffix is no longer used, and this create conflict between different applications. Is this the expected behavior or am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/11734614/16413733/13091796-3d34-11e6-8e04-c0e8d3d11660.png)

**Comment by brockallen** [comment]
How does this relate to IdentityServer?
