### ISSUE TITLE
ClaimsPrincipal does not return an access_token

### ISSUE THREAD

**Issue by alastair-mcdonald** [IdentityServer/IdentityServer3#3022]
Using the latest version of IdentityServer3 (https://github.com/IdentityServer/IdentityServer3) and the matching samples (https://github.com/IdentityServer/IdentityServer3.Samples) I encounter the following problem...

When using the MVC OWIN Client (Hybrid) and  MVC OWIN Client (Implicit) projects there is a consistent failure to obtain the access token from the ClaimsPrincipal.

In the HomeController for the MVC OWIN Client (Implicit) project the problematic code is :
public ActionResult Claims()
{
...
	var user = User as ClaimsPrincipal;
	var token = user.FindFirst("access_token");
	
at this point token is null meaning that "access_token" is not found, yet the claims are all present in the ClaimsPrincipal. 

It looks like ClaimsPrincipal is structured differently now but the client projects have not been updated to reflect the change? Either that or I am missing a point somewhere. I am using the projects exactly as they were downloaded - no changes to the .Net version or nuget packages. The projects built first time without an error.

A pointer in the right direction would be appreciated.

Thanks,
Alastair

**Comment by brockallen** [comment]
Yes, the implicit client is just not configured to be getting access tokens or calling the API. I coincidentally just updated it this morning to hide the buttons to call the APIs.

**Comment by alastair-mcdonald** [comment]
Why the change? Is the ClaimsPrincipal structured differently now? Is there a fix for this? Are there plans to fix the projects so they work? Surely it is not wrong in principle to use the implicit and hybrid MVC clients for API access? 

I am planning an MVC based app and am coming round to thinking I need the Hybrid flow to handle both MVC generated web pages and also jquery calls to an API. These MVC implicit and Hybrid examples seemed ideal until I hit this problem!

Which samples should I look at to get a realistic idea of what is needed?

Thanks,
Alastair

**Comment by brockallen** [comment]
If you want an access token in a MVC app, then look at the hybrid sample for a guide.

**Comment by alastair-mcdonald** [comment]
I got the MVC OWIN Client (Hybrid) example working and will look at that - thank you for your response.
