### ISSUE TITLE
How to send user profile fields such as First Name and Last Name with IdentityManger/MembershipReboot?

### ISSUE THREAD

**Issue by Pugglewuggle** [IdentityServer/IdentityServer3#3023]
- [ X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Is there any way to get the First Name and Last Name and such fields that show up in IdentityManager while using Membership Reboot as the user/claims store to come down via claims or some other method to be used in IDS clients? I have had to manually add claims for the first / last names (given_name and family_name). I do have the profile scope included in my application in both the IDS and client configuration. Authentication and everything else appears to be working nicely. Any help would be greatly appreciated.

### Relevant parts of the log file

```
<log goes here>
[I don't think a log will help with this one ;-)]
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
