### ISSUE TITLE
Problem with log out in Angularjs

### ISSUE THREAD

**Issue by mattt90** [IdentityServer/IdentityServer3#3025]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

After logging out in one tab and then rapidly switching to another tab, the relying party iframes do not load. In effect, the identity provider session is destroyed, but the relying party sessions remain active until their tokens expire.

It is believed to be caused by browser optimizations deferring JS execution when the tab is inactive, causing the iframes to fail to render.

A partial solution to this problem would be to use the iframes' onload event to defer the redirect to the post-logout URI. This would prevent the tab from redirecting too early if it became active again. However, the sessions would still be dissociate if the logout tab never became active again.

**Comment by brockallen** [comment]
This does indeed sound like a problem, but SLO is and has always been a "best effort" sort of thing. 

As for handling the iframe's onload to prevent redriect back to the RP, that;s a separate item and perhaps should be a new issue as a feature request. If you have the sample JS I'd be interested in seeing it to consider adding.

**Comment by brockallen** [comment]
Any proposals for some JS to address this issue?

**Comment by mattt90** [comment]
Sorry for the delayed response.

So to solve this issue, we used message postback in the javascript

In the client side signOutComplete page add some code like:
```javascript
<script type="text/javascript">
    window.parent.postMessage("logoutCompleted", "@Model.IdpUrl");
</script>
```

In the IdP add some javascript in the loggedOut.js:
```javascript
$window.addEventListener('message', function(e) {
                if (e.data === 'logoutCompleted') {
                    $window.location.href = redirectUrl;
                }
            });
```

We are in the process of updating our old IdP to IdentityServer3, so we only have our old IdP as a relyingParty to our new IdP, so there is some checking on the IdP's side to see if all relyingParties are signedOut.
