### ISSUE TITLE
Question: Return reason from authentication failure

### ISSUE THREAD

**Issue by eavonius** [IdentityServer/IdentityServer3#3026]
Hello,

I want to use Identity Server over an existing user store. I've found the provider classes etc. but I have a question. My primary use case is a mobile app using password grant authentication. The user account may be "locked". 

How do I return the reason why authentication failed? The username is not recognized, credentials are invalid, account is locked etc.

Thanks in advance,

Jayme

**Comment by brockallen** [comment]
In your custom user service when you create the `AuthenticateResult` you can specify an error message to show the user.

**Comment by eavonius** [comment]
Will this come back in the http response during password grant authentication? This is for a mobile a with its own login page so I need to parse something to show the message.

**Comment by leastprivilege** [comment]
the JSON response object has an error property. Check the OAuth spec.
