### ISSUE TITLE
There is an error determining which application you are signing into. Return to the application and try again

### ISSUE THREAD

**Issue by shacharon** [IdentityServer/IdentityServer3#3028]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
First, you have an excellent system that works very well.
I established flow Hibbed flow and  works nicely.
The problem started I began to custom the logon page
As long as I used on Log in Normally you produce everything works fine.
I set up my own Log in page  and

Overall, I added the following lines in
startup.cs 
 factory.UserService = new Registration <IUserService, CustomLoginPageUserService> ();

and 

 public class CustomLoginPageUserService: UserServiceBase
    {
        OwinContext ctx;
        public CustomLoginPageUserService (OwinEnvironmentService owinEnv)
        {
            ctx = new OwinContext (owinEnv.Environment);
        }

        public override Task PreAuthenticateAsync (PreAuthenticationContext context)
        {
            var id = ctx.Request.Query.Get ( "signin");
            context.AuthenticateResult = new AuthenticateResult ( "~ / login? id =" + id, (IEnumerable <Claim>) null);
            return Task.FromResult (0);
        }
    }

And I get the error I mentioned ..
"There is an error determining which application you are signing into. Return to the application and try again."

Any idea ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by Gentlehag** [comment]
what was the reason?
