### ISSUE TITLE
Question: Is there a way to check authentication without challenging for credentials if the user is not authenticated?

### ISSUE THREAD

**Issue by mistertown** [IdentityServer/IdentityServer3#3029]
Hi,

We are using IdentityServer 3 in an SSO scenario where we have 2 x MVC sites.  Logging into MVC1 successfully logs us into MVC2, but only if we hit a page that requires authentication.

If we hit the homepage on MVC2 first (which doesn't require authentication) then the header displays a Log In link, whereas what we'd actually want here is for the site to be aware that the user is authenticated even though the page itself isn't restricted by authentication.

What's the best way to achieve this? Is there a way to do a simple authentication check without the subsequent credential challenge?

Thanks :)

**Comment by brockallen** [comment]
The only way to know if you're already logged in is to "ask" and you can do this without triggering the signin -- make a request to the authorization endpoint with prompt=none.

**Comment by mistertown** [comment]
That's great, thanks for the reply Brock.  We'll give that a go!
