### ISSUE TITLE
OAuth2 broken if using scopes with same names as openid

### ISSUE THREAD

**Issue by lukos** [IdentityServer/IdentityServer3#3030]
I am testing IdSrv using an OAuth2 provider since I want to support OIC and OAuth2 clients. There is some logic which breaks in AuthorizeRequestValidator, my line 355 which says this: 

```if (_scopeValidator.ContainsOpenIdScopes && !request.IsOpenIdRequest)``` 

The problem is that the logic in ScopeValidator for ContainsOpenIdScopes is:

```if (scopeDetail.Type == ScopeType.Identity)```

In other words, if you use "email" or "profile" (or any of the other ID) scopes, IdSrv assumes you are doing OpenID Connect and need to pass "openid" scope. I don't know why this logic is here, since OAuth2 often uses "profile", "email" etc. for scopes and is not OpenID. Can this check just be removed?

**Comment by leastprivilege** [comment]
Then you need to define email or whatever as a resource scope.
