### ISSUE TITLE
How to access a claim value that was set when the user got authenticated when requesting profile data

### ISSUE THREAD

**Issue by uvita** [IdentityServer/IdentityServer3#3031]
I´ve created a sign in form that allows me to chose a company to which I will sign in, hence I have username, password and company name in my customized page. I extended the `UserServiceBase` class and overrided the `AuthenticateLocalAsync` method, setting the company Id as a claim in the AuthenticateResult.

`context.AuthenticateResult = new AuthenticateResult(authenticationResult.User.UserId.ToString(), authenticationResult.User.Username, new List<Claim> { new Claim("CompanyId", companyIdStr) });`

Then company id string is obtained from the form collection.

This is working fine so far, however, I would like to be able to set the same claim value when a request to the user info endpoint is sent and the `GetProfileDataAsync` method is called.

In order to do this, I would like to somehow bind the access_token that was generated with the company id, but I can´t see an easy way of doing this.

Is there any suggestion on how to implement what I´m looking for?

Thanks!

**Comment by leastprivilege** [comment]
The claims you return in the authenticate result go into a cookie. When calling userinfo there is no cookie and thus this claim is not available.

To make claims available on "back channels" you need to persist them e.g in a database or cache.

**Comment by uvita** [comment]
Thank you @leastprivilege for the answer.

I understand what you´re saying and I would like to persist the information in a cache as you said. However, I would like to understand how can I use the accesstoken as the key to save in the cache. I cannot use other value such as the user id, becuase the user may have different sessions with different company ids. 

So the question is how can I achieve this. (i.e. use the access token as the key to store in the cache and how can I obtain that value once the user is authenticated locally).

**Comment by leastprivilege** [comment]
your sub claim is not unique?

**Comment by uvita** [comment]
Yes, it is unique, but what would happen if the same user signs in on a different browser and chooses a different company? This would overwrite the value in the cache.
e.g. 
If a user signs in and chooses company A, I would save in the cache <User42, Company1>.

If that same user authenticates again in a different browser and wants to use a different company, I would ovewrite the value with <User42, Company2>.

This is not the behavior that I want, I would like to get the claim Company1 when requesting the user information using the access token issued on the first authentication.

Did I make myself clear?

Thank you

**Comment by leastprivilege** [comment]
Yes - basically you would want the claims from the access token used to call the userinfo endpoint available in the user service - is that correct?

**Comment by uvita** [comment]
Correct, this is (roughly speaking) what I would like to do in my custom UserService:

```
public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
	var companyId = GetCompanyFromFormCollection();
	
	var authenticationResult = _loginService.AuthenticaticateUser(context.UserName, context.Password, companyId);

	if (authenticationResult.Success)
	{
		context.AuthenticateResult = new AuthenticateResult(authenticationResult.User.UserId.ToString(), 
			authenticationResult.User.Username, 
			new List<Claim> { new Claim("CompanyId", companyId) });
		
		//Set the CompanyId used here in cache, using the accesstoken issued for this authenticate request.
	}
	else
	{
		context.AuthenticateResult = new AuthenticateResult(authenticationResult.Message);
	}

	return Task.FromResult(0);
}

public override Task GetProfileDataAsync(ProfileDataRequestContext context)
{
	// issue the claims for the user
	var subjectId = int.Parse(context.Subject.GetSubjectId());
	var user = _loginService.GetUser(subjectId);

	if (user != null)
	{
		var claims = new List<Claim>
		{
			//Set some claims here.
		};		

		//Obtain the CompanyId value that was previously stored, I could obtain the access token from the header here.

		claims.Add(new Claim("CompanyId", companyId));

		context.IssuedClaims = claims;
	}

	return Task.FromResult(0);
}
```

Thank you.

**Comment by leastprivilege** [comment]
OK - I see. We don't have that feature right now.

Added this for tracking: https://github.com/IdentityServer/IdentityServer3/issues/3036

**Comment by leastprivilege** [comment]
As a temp workaround - you could get the access token from the header and retrieve the claims manually - at this point the token is already validated.

**Comment by uvita** [comment]
Thanks @leastprivilege. Sorry for posting on this closed issue, can you please give me a hint on how can I access the claims once I have the access token in the method `GetProfileDataAsync`?

**Comment by leastprivilege** [comment]
use Microsoft's JWT library to read and parse the token.

**Comment by knabbel** [comment]
@Uvita, shouldn't you let your user select the company at the client?
Having the user authorised to act for both (or more).
The client can then cache the selected company in his session.
The UserEndpoint (and Token endpoint should (for as far as i know) just return all authorised information, and not a session determined subset.

For user interaction (when you want to have the user select the company at login page): 
Have the company selected on the login page, but sent the selected company in the redirect url to the client. Where the client (of course) checks whether the selection is valid (autorised) by matching the total set of authorised companies coming from the user endpoint.

**Comment by uvita** [comment]
Thank you @leastprivilege. I was able to grab the claims with this code:

```
var handler = new JwtSecurityTokenHandler();
var jwtSecurityToken = handler.ReadJwtToken(accessToken);
var tokenClaims = jwtSecurityToken.Claims;
```

I am not validating the token since that is alredy done before the method in the user service is called.

**Comment by uvita** [comment]
Hi @knabbel, thanks for your comment. I don´t understand quite well what is your concern with what I´m doing. Can you explain it a little bit better?

To give you a little bit of background, I have to implement the following:

- Users should be able to log in using the companies they are allowed to (If I choose a company and there is no association in the database between my user and that company I shouldn´t be allowed to log in).

- For some of the companies, the authentication may have to be done using Active Directory.

- Once a user is authenticated in one company, he/she can only view the information from that company.

Hence, this is, some how, similar to a multi tenant application and we´re using IS for authentication. So far, we didn´t find any issue with this, but I would like to understand your concern, may there´s a better way of doing things.

**Comment by knabbel** [comment]
Hi @uvita,

Thanks for your reply. 
I thought to recognize some of my own challenges in your approach.
Which is, after reading your background, not so similar.

So, after reading the background, my previous comments make no sense :(
Reading back your first post, I see my mistake.
a phrase in your question was: _I've created a sign in form that allows me to chose a company to **which** I will sign in._
I totally miss red it as if there was one word extra: _I've created a sign in form that allows me to chose a company to **FOR** which I will sign in._
So authentication on one location for all companies, and being authorized for several companies, where the user selects one.. 
Which is not your case.

My case is selecting one of many authorisations, being authorised for x resources at once.
Which is, I think, clearly a client issue/choice.

Anyway, not related to your issue :)

**Comment by olonga** [comment]
@uvita @leastprivilege 
How/where do I get the accessToken in the first place?  

----------------
Thank you @leastprivilege. I was able to grab the claims with this code:

var handler = new JwtSecurityTokenHandler();
var jwtSecurityToken = handler.ReadJwtToken(accessToken);
var tokenClaims = jwtSecurityToken.Claims;
I am not validating the token since that is alredy done before the method in the user service is called.

**Comment by uvita** [comment]
@olonga you obtain the access token by reading it from the header.

```
private string GetAccessToken()
{
	var authorizationHeaders = ctx.Request.Headers.GetValues("Authorization");
	if (authorizationHeaders != null)
	{
		var header = authorizationHeaders.First().Trim();
		if (header.StartsWith("Bearer"))
		{
			var value = header.Substring("Bearer".Length).Trim();
			if (value != null && value.Length > 0)
			{
				return value;
			}
		}
	}

	return string.Empty;
}
```

**Comment by CrescentFresh** [comment]
@uvita: FYI we've implemented this exact requirement with an additional constraint: we can't leak companies. That means a "company picker" on the login form is right out, it would show anonymous users too much information.

The way we accomplished this with Identity Server was to piggyback on to the "partial signin" concept: we show the user the standard login form and *after* signin we present them the tenants/companies they do have membership in, via partial signin mechanism. This way they get the same feature of "pick the company to log into" without showing them all companies in the system.

Further, using the `acr_values` defined by spec, if the client that wishes login already has the "company id" that they wish to log the user into they simply pass that as "tenant:<company id here>" acr value and IdentityServer automatically populates the `SignInMessage` appropriately, which is then pass to all methods in the UserService conveniently.

Hope that gives some insight into how others are implementing this sort of thing.

**Comment by djrerun** [comment]
@CrescentFresh Thank you for explaining your scenario. We have a similar situation and will probably look to implement something similar.

If you don't mind describing what your "company switch" looks like? In other words, once the user has successfully logged in and are using the application, should they decide to switch to another company, do you require them to log off and back on or are you able to send them over to the IDP with an updated `tenant` to receive a new access_token? I guess my question is, how seamless is the switch?

Thank you in advance.

**Comment by CrescentFresh** [comment]
@djrerun: currently, we require a logg off and log in again to switch companies. Not so good for the UX. We've spoken about implementing a proper "company switcher". Off the top of head I do not know exactly how to accomplish this with idsrv3, sorry.
