### ISSUE TITLE
Getting the email from a user that authenticates with external connectors in the ExternalLoginDetails object

### ISSUE THREAD

**Issue by evilpilaf** [IdentityServer/IdentityServer3#3032]
- [ X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is there a way to know the email of a user in the Login Event when it's from an external source?

The 'Name' property for a LocalLoginDetails object contains the user email but when it's an ExternalLoginDetails type of object, I can't find the email, we're using this information for audit and insights and need to know the email of a user when they access the site

**Comment by brockallen** [comment]
The "name" claim is what's used to populate the "Name" property on the `Subject` on the `AuthenticateResult`. You can set this when you create the `AuthenticateResult` in the external login in the user service. IOW, if you are consistent in setting the name claim in both local and external logins on the user service, then both events should have the email.
