### ISSUE TITLE
Active Client with Delegated Authetication

### ISSUE THREAD

**Issue by MarutiMorajkar** [IdentityServer/IdentityServer3#3034]
I have used IdentityServer3 nuget package on my authorisation Server which delegates the authentication with an external identity provider.

For Passive authentication i have implemented an ExternalRegistrationUserService to provide an additional user flows to select the tenant and organisation before the authorisation servers issues an valid token. Then have augmented the claims using an CustomClaimsProvider. Its works fine for me for fedauth and oauth mvc clients.

For active authentication i am unable to understand which flow to use to delegate the authentication to the external identity provider. I tried relating this to the samples in IdentityServer3.Samples-master but unable to understand which one to use.

From what i feel i should be using the resource owner password flow. However is there any service that i need to implement on the authorisation server that verifies the identity with the external identity server and then uses the CustomClaimsProvider to issue claims to the active client. 

Please could you suggest the flow that i should be using.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
