### ISSUE TITLE
How to customize login page in Hybrid flow ?

### ISSUE THREAD

**Issue by shacharon** [IdentityServer/IdentityServer3#3035]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi
i am using idsrv with mvc and working with Hybrid flow.
working with this flow , we got redirect to login-page in IDSRV got the token and redirect back to website with the token.
i need to change and customize the login page, implementing the iviewService not good enough, i need the layout.

how can i do it ?
is it possible ?

Thanks 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
