### ISSUE TITLE
SignInMessage from PreAuthenticate empty when AuthenticateLocalAsync

### ISSUE THREAD

**Issue by stevengopmo** [IdentityServer/IdentityServer3#3038]
Similar to issue #1260 (almost exactly) I find that the properties I set in the SignInMessage during PreAuthenticateAsync do not get carried to AuthenticateLocalAsync.  I am using the CustomHrd sample as my source.  

In my PreAuthenticateAsync the context contains the tenant claim after I set it from my controller method as expected.

````
        public override async Task PreAuthenticateAsync(PreAuthenticationContext context)
        {
            var user = await _owinContext.Environment.GetIdentityServerPartialLoginAsync();
            if (user == null)
                // no acr/tenant, so do partial login to login page
                context.AuthenticateResult = new AuthenticateResult("/core/user/login", (IEnumerable<Claim>) null);
            else
            {
                // we have partial login, so look for tenant claim
                var tenantClaim = user.Claims.FirstOrDefault(x => x.Type == "tenant");
                if (tenantClaim == null)
                    context.AuthenticateResult = new AuthenticateResult("Error: no tenant claim found");
                else
                {
                    context.SignInMessage.Tenant = tenantClaim.Value;
                    _owinContext.Environment.RemovePartialLoginCookie();
                }
            }

        }

````
but when I get to AuthenticateLocalAsync in the UserService the Tenant property of the SignInMessage message is null.  Where is it getting lost or is the Hrd not the proper example for this scenario?

From my controller action I do almost exactly as CustomHrd

````
            var ctx = Request.GetOwinContext();
            var user = await ctx.Environment.GetIdentityServerPartialLoginAsync();
            if (user == null)
                return View("Error");

            var tenant = "1";
            // add tenant value as claim back to the partial login
            var claims = user.Claims.ToList();
            claims.Add(new Claim("tenant", tenant));

            await ctx.Environment.UpdatePartialLoginClaimsAsync(claims);
            
            // find the URL to return to the login page
            var resumeUrl = await ctx.Environment.GetPartialLoginRestartUrlAsync();

            // return the the login page
            return Redirect(resumeUrl);
````
I added the "idp" claim in my code to see if it was something specific about the claim type. but the idp value is null as well.

Should I be doing something different here?

**Comment by stevengopmo** [comment]
Further information.  If I pass `acr_values: "tenant:tenants/1"` from the client the value for tenant stays all the way through.  It only seems to drop if I try and update during the PreAuthenticateAsync method.

**Comment by brockallen** [comment]
> but when I get to AuthenticateLocalAsync in the UserService the Tenant property of the SignInMessage message is null.

The SignInMessage is read from a cookie set from the authorization endpoint. Anything you set on it is not designed to be persisted across round trips (like from pre-authN to the SignInLocal).

**Comment by stevengopmo** [comment]
OK, seems it should be readonly then so as not to confuse, but I think I managed to work around it
