### ISSUE TITLE
Support for External Identity Provider using OpenID Authentication 2.0 Spec.

### ISSUE THREAD

**Issue by jachin84** [IdentityServer/IdentityServer3#3039]
I have a requirement to integrate with 3rd party for SSO. They are using the OpenID Authentication 2.0 Spec. Does Identity Server support OpenID Authentication 2.0 as an external identity provider and if not is their documentation on writing a custom provider?

**Comment by leastprivilege** [comment]
We leverage the Katana authentication middleware infrastructure. 

I am not aware of a Katana OpenID 2.0 middleware - but maybe you have better google keywords now.
