### ISSUE TITLE
Identity Token and Access Token 

### ISSUE THREAD

**Issue by nkdev89** [IdentityServer/IdentityServer3#3046]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Im looking for sample code which gets the identity token from identity server , and uses the same to get the access token. And using access token , i need to connect to the API . 

Thanks 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
check the samples repo

**Comment by nkdev89** [comment]
Im new to this , I couldnt find any sutiable sample. If im wrong please let me know which sample has it

**Comment by leastprivilege** [comment]
There's a sample called "clients" which showcases various clients requesting and using tokens.

**Comment by nkdev89** [comment]
Thanks a lot dude. I will check this and let you know
