### ISSUE TITLE
Custom flow: Passing in OAuth Token received from another identity server and presented to Authorisation server which implements id3 and expects a SAML token response

### ISSUE THREAD

**Issue by MarutiMorajkar** [IdentityServer/IdentityServer3#3047]
We have an our authorisation server which is an identity server3 which talks to an external identity server for identity and depending on the mapped user of our system issues specific claims.

We have few WebApplication and the WCF services which all understand SAML. So we used the wsfed plugin provided by you to get the SAML token. This all (passive flow) works fine.

We have few active clients running as console application that logon to the external  identity server using ROPC and get an jwt. We then want to present the JWT to our authorisation server and get a SAML token.

Please could you suggest your thoughts of how this could be achieved.

Presently we have used the custom flow on the Authorisation server which accepts the jwt passed from the external identity server, Introspects it and then issues the saml token as a claim in the jwt. This approach looks a long winding. 

The thing that we are unable to understand is if the authorisation server is configured to understand the tokens from the external identity server why does not it set the current principal if it is presented with the bearer token. if that was possible i feel using the custom grant validator in the wsfed plugin we could issue the user with SAML token.

**Comment by leastprivilege** [comment]
IdentityServer is not designed for issuing SAML tokens.
