### ISSUE TITLE
Replication or Geo sharding IdentityServer3

### ISSUE THREAD

**Issue by neilhosey** [IdentityServer/IdentityServer3#3048]
Hi,

We are going ahead with deploying IdSrv3 into production, but a question has arisen around deploying this is multiple regions around the world to offer low latency wherever our customers are.

My main questions are:
1. Is replication a good approach?
2. Is geo sharding better?
3. Is there any pitfalls or recommendations you would make around this before I start? 

EDIT: To give some context, we are deploying IdSrv3 with membershipReboot, using a SQL Server DB.

Thanks again for the help!
Neil

**Comment by leastprivilege** [comment]
Sorry - never deployed it in such a configuration. Please do a writeup/blog post on it.
