### ISSUE TITLE
IdentityModel for  .NET Framework 4.0

### ISSUE THREAD

**Issue by h2chch** [IdentityServer/IdentityServer3#3049]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

What is the alternative of IdentityModel (https://github.com/IdentityModel/IdentityModel) for ,NET Framework 4.0? The nuget package does not seem to support .NET Framework 4.0

Thank you

**Comment by leastprivilege** [comment]
What functionality do you need?

**Comment by leastprivilege** [comment]
oh and wrong repo.

**Comment by h2chch** [comment]
I am sorry I asked this in conjunction to the IdentityServer3 client. I think I have wrongly mentioned the library that I am looking for. It should be System.IdentityModel.Tokens.Jwt package for .NET Framework 4.0. Basically I want to retrieve the claims information using access token/id token. I understand this can be achieved by calling the IdP discovery endpoint. I have look through the IdentityServer3 client samples and most of the sample code use JwtSecurityTokenHandler to retrieve the claims information which is contained in System.IdentityModel.Tokens.Jwt. Unfortunately this library is not available for .NET Framework 4.0. Do you know any alternative for that?

**Comment by leastprivilege** [comment]
That is a Microsoft package. The minimum requirement for this is .NET 4.5
