### ISSUE TITLE
custom message when authentication fails

### ISSUE THREAD

**Issue by kedarkdr** [IdentityServer/IdentityServer3#3054]
Hi,

Currently we get message "message: Authorization has been denied for this request."  when authentication fails or if the token is not specified in the request header

could you please let us know if this can be customized? like we want to include additional error information apart from message to the client.

thanks

**Comment by leastprivilege** [comment]
who sends this message?

**Comment by kedarkdr** [comment]
As per my understanding it should be the owin middleware, which I believe should be from the identityserver, which is setup as below. Once the below setup is done then my understanding is that the identityserver owin middleware verifies the bearer token presence and send the above mentioned message, correct me if I am wrong

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = ConfigurationManager.AppSettings["AuthServerUrl"],
                ClientId = "clientid",
            });

**Comment by leastprivilege** [comment]
This is not identity server - this is your API. 

The error message comes from the Web API [Authorize] attribute. And per spec - a 401 doesn't need any further explanation.

If you hit app level authorization failures - emit a 403 with whatever custom error you want.
