### ISSUE TITLE
Identity Token and Access Token 

### ISSUE THREAD

**Issue by nkdev89** [IdentityServer/IdentityServer3#3055]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Im trying to understand whether there are separate request to be done to identity server to get access token using identity token. Or just a call to the identity server and the response claim will hold the both . If i need to do as i said earlier . is it possible ? (using identity token to get access token) 

If you can throw some light on it , it would be really great !

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
