### ISSUE TITLE
Client Certificate Authentication Behind a Load Balancer

### ISSUE THREAD

**Issue by andrewdmoreno** [IdentityServer/IdentityServer3#3056]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am working in an environment where Identity Server will be running on IIS behind a load balancer. SSL is terminating at the F5 and my question is whether this would prevent us from using client certificate authentication out of the box. Is there additional configuration needed for this scenario? Wondering what our options are for adhering to the client certificate authentication requirement. 

### Relevant parts of the log file
Debug output: 
- Start parsing for X.509 certificate
- X.509 certificate not found

**Comment by leastprivilege** [comment]
If SSL terminates at the F5, I don't know how that client cert would be forwarded.
