### ISSUE TITLE
Choosing an Identity Server Flow

### ISSUE THREAD

**Issue by human3820917** [IdentityServer/IdentityServer3#3058]
I remain confused as to which flow pattern to choose for my situation. My backend API is written in ASP.NET Web API v2. My client will be a javascript web application that uses jQuery to make the API calls. I want the user to submit a username and password and that's it. I do not want them to have to choose from a second screen to allow the application to view their profile and etc.. Is the Resource Owner flow the better option?

**Comment by brockallen** [comment]
https://leastprivilege.com/2016/01/17/which-openid-connectoauth-2-o-flow-is-the-right-one/

**Comment by human3820917** [comment]
Thanks for the link to the article. It seems that in my case the Implicit flow is the right choice, however, in the guides I have followed the Implicit flow still brings the user to a "Profile" page where the user is prompted if they want to share the profile information. This is the step I want to avoid. I am not dealing with a Facebook or Google login in any way. Just a username and password that is local to my application. I simply want to determine if the username/password is correct and issue a bearer token that contains the claims that are associated with the account.

**Comment by leastprivilege** [comment]
the consent page can be disabled. That's unrelated to the protocol flow.

**Comment by human3820917** [comment]
Thank you .. I did not realize that. I have been following Filip Ekberg's course on Pluralsight and it did not mention that that step could be disabled.

**Comment by human3820917** [comment]
I am looking to protect some API's that are accessed by a HTML/jQuery web application that does not have access to cookies but only local storage for storing the JWT tokens. Does it sound like the Implicit flow is the way to proceed? I just want to "nail down" the correct flow to focus on rather than wondering if I am even learning the proper flow. Thank you.

**Comment by brockallen** [comment]
Yes. If you need help then there's this library: https://github.com/IdentityModel/oidc-client-js
