### ISSUE TITLE
Optional claims defined as scopes

### ISSUE THREAD

**Issue by meharjit** [IdentityServer/IdentityServer3#3060]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

Hi Guys,
I am currently developing a web application that requires some claims to be optional.
I found a way of doing this, by requesting those claims as scopes.
An example of a request body is below (where opt is the optional claim i want in addition to the openid scope:

`Grant_Type=password&Scope=openid+opt&username=test@example.com&password=password1&client_id=my.secure.client&client_secret=my.secure.client.secret`

However the optional claims (defined as scopes) are being listed out in the scopes list.
Is there any way for us to limit which scopes are returned in the scopes array in the token?
Alternatively is there any other way to define optional claims to be passed in with the token request.

Kind Regards

Harj

**Comment by leastprivilege** [comment]
Not sure what "optional" means.

Claims hang off scopes - if you don't need the claims, don't ask for the scope.

**Comment by meharjit** [comment]
Hi Dominick,
Thanks for getting back to me.

By optional we mean, we would like to request a certain predefined scope, but in addition to that scope request one or two extra claims.

Take the example:
openid returns the claims abc and def.
But I also want claim xyz.
I could define a scope to contain abc,def and xyz. But what about when someone wants claim jhi.

We have implemented that by adding each claim we defined as "optional" as a scope with the same name.

But that claim defined as a scope gets returned in the scopes list, which we would like not to appear there.
Is there any suggestion you can offer for us to achieve this? including disregarding the solution we went with and using more of your framework?

kind regards

Harj

**Comment by leastprivilege** [comment]
Scope has a property that allows hiding it from discovery - if that is your concern.

**Comment by meharjit** [comment]
Thanks for getting back to me. I'm working with my team to find alternative "business" solutions, and make it a business concern, as opposed to an auth provider one.

**Comment by brockallen** [comment]
All set on this issue?
