### ISSUE TITLE
Web api throws "Response status code does not indicate success: 401 (Unauthorized). "

### ISSUE THREAD

**Issue by pagidi** [IdentityServer/IdentityServer3#3063]
Hi Brockallen,

Could you please correct me where it went wrong???

Webapi is throwing Response status code does not indicate success: 401 (Unauthorized).

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = ConfigurationManager.AppSettings.Get("idsrv"),
                RequiredScopes = new[] {  "sampleApi"}
            });

I checked token it contains the "sampleApi" scope. 

**WCF Service also throws** 
An error occurred when verifying security for the message.

**IdentityServer log shows:**
w3wp.exe Information: 0 : 07/13/2016 23:19:06 +05:30 [Information] (IdentityServer3.Core.Endpoints.DiscoveryEndpointController)
 Start discovery request

I tried all the possibilities but didn't work.
Am I missing any basic thing???

**Comment by brockallen** [comment]
Sorry there's not really enough info to go on here.

**Comment by brockallen** [comment]
Any progress/update?

**Comment by pagidi** [comment]
Yes I got it. This was DNS name issue with my certificate. I solved it

Thank you.

**Comment by mortenbirkelund** [comment]
Could you elaborate on what the DNS issue was? I am getting the same error
