### ISSUE TITLE
Single Signout from external Idps like google, Microsoft Account, Facebook

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3#3064]
Hello,

I used IdentityServer as STS for more than one mobile application and i using implicit flow for that, and now i want to implement Identity Server Signle signout from external accounts like google, facebook and microsoft account.

What happen now that i allow the user to signout by calling the IdentityServer logout endpoint give it id_token and Post signout redirection URI, but this only signout users from identityserver but not allow cascading or federation signout for the external account that this user come from.

I know that there is an OWIN middlewore extension method that i can use for this:

```
public void Configuration(this IAppBuilder app)
{
   app.Map("/core", coreApp =>
   {
      var factory = new IdentityServerServiceFactory();

      // ...

      coreApp.UseIdentityServer(idsrvOptions);
      
      coreApp.Map("/signoutcleanup", cleanup =>
      {
         cleanup.Run(async ctx =>
         {
            await ctx.Environment.ProcessFederatedSignoutAsync();
         });
      });
   });
}

```

but i don't understand if this the only thing i need for doing that or should i provide identity server with info related to google, Facebook, Microsoft Account Signout endpoints?

Also is there any extra step that needed in addition to call the logout endpoint from client side? for example calling this uri: https://identityserverbublicorigin/signoutcleanup/ or is it handled using identityserver?

I noted this code in my custom loggedOut.cshtml view:
 
```
foreach (var url in Model.IFrameUrls)
            {
                <iframe class="signout" src="@url" style="display: none"></iframe>
            }
```

So it's great if i can fill IFrameUrls with my external providers logout endpoint to execute them in a hidden IFrame after logout but how to do this? i will debug it now to understand  Model.IFrameUrls and if i get any info i will share it.

**Comment by brockallen** [comment]
> google, Facebook, Microsoft Account Signout endpoints

Do you know that these providers support signout?

**Comment by deserthero** [comment]
yes Facebook, Google and Microsoft support signout. I implement this feature and it works now correctly

**Comment by xmichaelx** [comment]
@deserthero 
For Google: https://accounts.google.com/logout
For Microsoft: https://login.microsoftonline.com/logout.srf

I could find a simple url which would log me out for Facebook, did you found it by any chance?

What I do in my implicit JS client is that I check in the token which IdP was used and open in iframe relevant url.

**Comment by brockallen** [comment]
I don't see `end_session_endpoint` support in here: https://accounts.google.com/.well-known/openid-configuration

**Comment by deserthero** [comment]
this may help, i write this topic weeks ago 
http://notnull.co/2016/07/14/single-sign-out-endpoints-for-external-providers-facebook-google-and-microsoft-account/
