### ISSUE TITLE
Discovery document including sub folder in wwwroot (IIS)

### ISSUE THREAD

**Issue by kylegalbraith** [IdentityServer/IdentityServer3#3066]
We deploy IdSvr behind a load balancer within AWS. When these are environments are deployed they are deployed to a sub folder (call it my_deploy) within wwwroot. A rewrite rule is then added to the Default Web Site to rewrite requests to / to go into my my_deploy folder.

This works great for all of our API's, however, we ran into a hiccup with IdSvr in that the discovery document is including the my_deploy folder in the url. For example the /.well-known/openid-configuration is actually report out /my_deploy/.well-known/openid-configuration. Any ideas on how to resolve this? Below is how the configuration is laid out...

```c#
var options = new IdentityServerOptions
{
    SiteName = "",
    SigningCertificate = Certificate.Load(),
    Factory = idsvrFactory,
    EnableWelcomePage = true,
    PublicOrigin = ConfigurationManager.AppSettings["IdSvrOrigin"],
    CspOptions = new CspOptions() { Enabled = false },
    AuthenticationOptions = new AuthenticationOptions
    {
        EnablePostSignOutAutoRedirect = true,
        CookieOptions = cookieOptions,
        LoginPageLinks = loginLinks
    },
    LoggingOptions = new LoggingOptions() { EnableWebApiDiagnostics = true }
};

app.UseIdentityServer(options);
```

**Comment by kylegalbraith** [comment]
Perhaps this is because we are missing the IssuerUri which will default to the base path?

**Comment by brockallen** [comment]
We use what the OWIN request tells us the base path is.

**Comment by kylegalbraith** [comment]
Yeah I believe the issue here is getting my deploy path correct and has abolutely nothing to do with IdentityServer. Apologies for the issue, next time I will use stackoverflow.
