### ISSUE TITLE
Not allow user login on multiple devices

### ISSUE THREAD

**Issue by chuongxl** [IdentityServer/IdentityServer3#3067]
## Not allow user login on mutilple devices at the same time.

I have an app use identity server 3  and my scenario is logging on 1 device at the same time. Mean that if user was already authorized on chrome then this user is trying to login on firefox and immidiately user sign  in firefox  we have to kick out the user session on chrome.

**Comment by brockallen** [comment]
That's not covered by the OIDC spec, so it's not something we specifically implement. You'd have to come up with your own approach for this.
