### ISSUE TITLE
Resource/Action Based Authorization

### ISSUE THREAD

**Issue by nkdev89** [IdentityServer/IdentityServer3#3068]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

im looking for sample Resource/Action Based Authorization

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
This is unrelated to identityserver. 

Have a look here:

https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/samples/OWIN/ResourceAuthorization

the code is not maintained anymore - but feel free to copy whatever you need.
