### ISSUE TITLE
Unable to host WSFederationServer on Windows 2012 R2

### ISSUE THREAD

**Issue by santoshr** [IdentityServer/IdentityServer3#3070]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We are able to get IdentityServer working with WSFederationServer locally using IISExpress. When we deploy to our Windows 2012 R2 Server, The IdentityServer works fine but the WSFederationServer fails to show the configuration file. I get a 403 - 

403 - Forbidden: Access is denied.

You do not have permission to view this directory or page using the credentials that you supplied.

**Comment by leastprivilege** [comment]
any update?

**Comment by santoshr** [comment]
We got it working on a clean VM. Still not sure what caused it to fail. Investigating.
