### ISSUE TITLE
Using other claims in Custom View Service

### ISSUE THREAD

**Issue by codehepta** [IdentityServer/IdentityServer3#3075]
Hello,
According to documentation we are using Custom View Service to modify login,logout and other related views. So far we could not figure out to get other specific claims from LogoutViewModel or ConsentViewModel. 
We also use a Custom User Service and we are sending the claims to AuthenticateResult object. 
We noticed a property named as Custom  in CommonViewModel but its value is null. 
We would like to use full names,email and custom claim in some views i mentioned above. How we could inject these to use in Custom Views? 
Thanks in advance.

**Comment by brockallen** [comment]
You can always use the `GetIdentityServerFullLoginAsync` OWIN extension method to get the current logged in user. https://identityserver.github.io/Documentation/docsv2/advanced/owin.html
