### ISSUE TITLE
Redirect url on post logout not possible if not exactly matching with the ones in the config

### ISSUE THREAD

**Issue by Moonsk313** [IdentityServer/IdentityServer3#3076]
Hi,

We have an application which works pretty well, however I'd have a question about the logout.
We don't use a page for the logout.
We would like to redirect after the logout to an url which is either having a query string, either it's actually a dynamic url.
Since for trusting those urls, we need to store in the config all **exact** post logout urls to allow the redirection (which is not feasible since we don't know them as it's totally dynamic), is there a way make that redirection possible without add them all in the table ClientPostLogoutRedirectUris but only in the scheme part of the url?

That would be nice that those urls will be trusted only in the scheme level.. (so only http://localhost:60877)

and then the redirect would work if the redirect url would be:
http://localhost:60877/what-ever/index.html
or 
http://localhost:60877?event=ghgdmslkfds456

Thanks

Regards,
Mouncef

**Comment by leastprivilege** [comment]
A very common pattern is to only have one redirect URI - but save the deep link portion in your app before you do the redirect to IS. Then on the way back you first go to your "main" redirect page and from there do the local redirect.

Another option is to add some flexibility by implementing `IRedirectUriValidator` - but be careful to not introduce open redirector behavior.

**Comment by Moonsk313** [comment]
Hello,

I agree, it's really common to have only one redirect URI, but some business requirement had to be reached.
However, I choose your solution to implement IRedirectUriValidator and it works pretty well !
I even found this article:

 [http://mvalipour.github.io/back-end/2015/07/09/identityserver3-allow-redirect-uri-subdomains/]

So, thanks for your answer ;)

regards,
Mouncef
