### ISSUE TITLE
Error: client_id is not found in post body

### ISSUE THREAD

**Issue by arifkh** [IdentityServer/IdentityServer3#3077]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I am seeing this error message in the logs. This is for an API that is secured via Client Credentials flow. However, the log entry right before it shows that there is a ClientId present. What could be the issue?

### Relevant parts of the log file
![image](https://cloud.githubusercontent.com/assets/1787012/16879421/2483294a-4a76-11e6-8101-ceb75f3fede6.png)

```
<log goes here>
```

**Comment by brockallen** [comment]
Is it being passed as the authorization header? Is the call working and just a log entry that seems odd to you?

**Comment by arifkh** [comment]
I am going to close this issue for now. I am not able to find any errors in the client application. I just happened to find this weird error while looking for something else.
