### ISSUE TITLE
Issuer uri gets appended with "/"

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer3#3079]
### Issue
In IdentityServerOptions i am specifying the Issuer URI as "https://example.com". In my token response it is returning the Issuer as "https://example.com/". Is this expected ?

**Comment by brockallen** [comment]
Probably dup of https://github.com/IdentityServer/IdentityServer3/issues/2994

**Comment by akshetty9** [comment]
Sorry. This turned out to be a mistake on our side. We defined the uri as System.Uri in Settings file. So though the string was defined as "https://example.com", it appends "/" when URI is read from the settings file.
