### ISSUE TITLE
RequireSSL in AWS behind load balancer

### ISSUE THREAD

**Issue by tstone84** [IdentityServer/IdentityServer3#3080]
I've just deployed my IdentityServer3 solution out to an AWS instance. I had IdentityServer3 configured to RequireSSL.  The problem seems that it's relatively common to have SSL running up to the AWS load balancer, then run non-SSL between the LB and IIS.  So, I set RequireSSL to false and tried again.  Now the problem seems to be that when IdentityServer tries to redirect to the sign-in page, it does so without https.  When this redirect exits and re-enters through the LB, it fails because it must be https coming into the LB.  So, it seems that IdentityServer is constructing the redirect to the sign-in page with consideration of the RequireSSL flag.  Is there anyway around this?  I'm working with my ops guy to just run SSL all the way to IIS, but i'm getting some pushback (of course).

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
