### ISSUE TITLE
EmbeddedAssetsViewService sample not working **SOLVED**

### ISSUE THREAD

**Issue by carlhoogstoel** [IdentityServer/IdentityServer3#3081]
I have, what I believe a simple problem that is driving me crazy. When I run the EmbeddedAssetsViewService sample, everything is working correctly as it should.

The only issue is that the /content/site.css is not being served.

I'm running the sample without any changes on my part. Is there any1 that can shed some light on why the css is giving a 404?
![sample](https://cloud.githubusercontent.com/assets/19626310/16987470/bb302ac2-4e8c-11e6-9d6b-1acef4346899.png)

I also tried it with a CustomViewService : DefaultViewService where the constructors code is:

`
public CustomViewService(DefaultViewServiceOptions config, IViewLoader viewLoader) : base(config, viewLoader)
 {
            config.Stylesheets.Add("~/content/site.css");
            config.CacheViews = false;

            var contentDirectory = System.Web.Hosting.HostingEnvironment.MapPath("~/Content");
            config.CustomViewDirectory = contentDirectory;
 }

but that doesn't work eather.

**Comment by brockallen** [comment]
> The only issue is that the /content/site.css is not being served.

I just loaded and ran it:

![untitled](https://cloud.githubusercontent.com/assets/649492/16992904/2c4d0acc-4e6f-11e6-9ab5-d9b68c8f0d2f.png)

**Comment by carlhoogstoel** [comment]
Indeed, I can see it. That is so strange as you can see from my screenshot I'm getting a 404. 
As it works out of the box with you, and I didn't change any code on my side, it must be my IIS configuration somehow.
What is even more strange is when I put the url in a browser, I get the OWIN startpage instead of the css content. 
Does that maybe ring a bell as to what might be wrong with my IIS configuration?

**Comment by brockallen** [comment]
Nope, no idea. Sorry

**Comment by carlhoogstoel** [comment]
@brockallen 

I found the problem. The issue for me was that, although I knew that the hostname needed to be the same as the issuer of the self-signed certificate, I used my hostfile to point 'somename' to my 127.0.0.1. That way, when I did https://somename/core, I could see the identiyserver welcome screen. This made me assume that the identity server host was running fine.

What Ididn't realise is that you cannot do it this way because it will prevent the css or extra assets to be loaded. You need to use the machinename.blalblabla.root.com as the rootname of your identityserver. In the end, as soon as I started using https://machinename.blalblabla.root.com:44333/core, all my assets started being served by IIS as expected.

Some more points for anyone running in to this issue:
1. I used IIS as web server, not the IisExpress as I find IIS easier to configure.
2. I created a self-signed certificate through the IIS interface (server -> features view -> server certificates -> create-self signed certificate)
3. Exported the certificate to a pfx file
4. Imported t through MMC in to the Trusted root certification authorities store of the local computer
5. Created a new site (not a virtual under default web site) and added a binding to https on port 44333 indicating the certificate I just made with no host name
6. did an iis reset and all worked as expected

PS: the thing most plp seem to fall over is the host name:
-> this DOES NOT mean you need to configure a host name in IIS
-> when referring to the host name, we are referring to the name of your machine
-> the name in your https://THENAMEYOUENTERHERE:44333/core is the name from your issuer/subject property of your certificate

Hope this all helps someone with the same issue

Last but not least; no, i don't understand why Identity Server would not serve my css when I used DNS resolving through my host file as I would have assumed this would work too. Maybe its something int he Identity Server framework or something with SSL, eater way, It works now.
