### ISSUE TITLE
Special Setting to request scope

### ISSUE THREAD

**Issue by human3820917** [IdentityServer/IdentityServer3#3082]
In your tutorial on IdentityServer3 and Javascript you make this statement ...

**"Once again, we don’t need to allow the client to request this new scope in this example because of the special setting, but it will be a necessary step in a real scenario."**

Can you clarify which special setting you are talking about? Can you explain a little further what change we would need to make in a Production scenario. Thank you.

P.S. and thanks for providing the tutorial.

**Comment by brockallen** [comment]
I think it's referring to: `AllowAccessToAllScopes = true`, which is not something you'd allow in prod. It's too powerful. It's better to use `AllowedScopes` and make explicit what scopes your client can request.

**Comment by human3820917** [comment]
Thank you!
