### ISSUE TITLE
Access Token is null

### ISSUE THREAD

**Issue by richardterris** [IdentityServer/IdentityServer3#3083]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I'm pretty new to IdentityServer so forgive me if this turns out to be something silly.... I have a unit test where I'm simply returning an AccessToken and logging it to the console, so I can see I'm getting it correctly. This was working fine until a while ago I had major issues on my VM and had to build them and stupidly hadn't committed all my code, so I lost things and had to recreate a lot of stuff. Now this code isn't working.

The crux of it is this: 
`var tokenResponse = tokenClient.RequestClientCredentialsAsync("applicationLogin").Result;` 
The AccessToken is null and the HttpErrorReason is 'Internal Server Error'.
There's nothing in Windows server logs to help.

- The end point seems to be correct
- The client credentials seem to be correct (Flow is set to Flows.ClientCredentials)
- Scope type is set to ScopeType.Resource

The full code in my unit test is:
`//Create a token client
            TokenClient tokenClient = new TokenClient
                (
                 Constants.AnglrStsTokenEndpoint,
                 "mycredentials",
                 Constants.MyClientSecret
                );

            var tokenResponse = tokenClient.RequestClientCredentialsAsync("applicationLogin").Result;

            if (tokenResponse.IsError)
                Console.Write(tokenResponse.Error);

            Console.Write("Access token: " + TokenHelper.DecodeAndWrite(tokenResponse.AccessToken));`

I do have <modules runAllManagedModulesForAllRequests="true"/> in my web.config

Please let me know if I can provide any further useful information to help.
Many thanks in advance!

**Comment by brockallen** [comment]
>  There's nothing in Windows server logs to help.

What do the IdentityServer logs say?

**Comment by richardterris** [comment]
Where do I find the IdentityServer logs?

**Comment by brockallen** [comment]
In the template for the issue you opened there was a link to the logging info.

**Comment by richardterris** [comment]
Hi @brockallen thanks for that; I have Serilog configured to write to LiterateConsole but nothing seems to be happening. Again, I'm new to IdentityServer so I'm not sure if I have it configured properly or not? The fact that it's a unit test shouldn't matter right? It's still firing the same request to my identity server.

The code I have in Startup.cs (having tried writing to file, console, and now LiterateConsole) is

` public void Configuration(IAppBuilder app)
        {
            app.Map("/identity", builder =>
            {
                IdentityServerServiceFactory identityServerServiceFactory = new IdentityServerServiceFactory()
                    .UseInMemoryClients(Clients.Get())
                    .UseInMemoryScopes(Scopes.Get())
                    .UseInMemoryUsers(Users.Get());

        IdentityServerOptions identityServerOptions = new IdentityServerOptions
                {
                    Factory = identityServerServiceFactory,
                    SiteName = "My App Security Token Service",
                    IssuerUri = "https://myapp.local/identity",
                    PublicOrigin = "https://myapp.local",
                    SigningCertificate = this.LoadCertificate()
                };

                builder.UseIdentityServer(identityServerOptions);

                Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Warning()
                .WriteTo.LiterateConsole()
            .CreateLogger();
            });

            LoggingOptions loggingOptions = new LoggingOptions();
            loggingOptions.EnableHttpLogging = true;
        }

         X509Certificate2 LoadCertificate()
        {
            return new X509Certificate2
                (
                string.Format(@"{0}\Certificates\idrsrv3test.pfx",
                AppDomain.CurrentDomain.BaseDirectory), "MyPassword"
                );
        }
    }`

Thanks again for your kind assistance

**Comment by richardterris** [comment]
Hi @brockallen wonder if you've had any time to look at this? I really appreciate the assistance

**Comment by leastprivilege** [comment]
Brock's on holidays. Check our samples and docs - they demonstrate how to enable logging. It's been done before ;)

Once logging is working, it will probably be pretty obvious what the problem is.

**Comment by akshetty9** [comment]
Can you change log level to Debug and move the Logger code above the statement app.Map("/identity", builder =>)... and then check the logs.

public void Configuration(IAppBuilder app)
{
Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.LiterateConsole()
                .CreateLogger();
app.Map("/identity", builder =>
{
.....
}

**Comment by richardterris** [comment]
@leastprivilege I appreciate you taking the time to respond, and I also appreciate that a lot of people maybe don't look at documentation before posting here. But, given that I included code it should be clear that I did look at a few places and tried a few things before posting that example code.

Even if you think something is simple, it isn't to all us newbies :)

**Comment by richardterris** [comment]
@akshetty9 Thanks for your reply. I've tried what you said, but in all honesty I don't even know where the logs are stored.
Can you help me any further? Many thanks!

**Comment by akshetty9** [comment]
Please use this to see the log file in the location configured C:\idsLogs.txt
Log.Logger = new LoggerConfiguration()
.MinimumLevel.Debug()
.WriteTo.File(@"C:\idsLogs.txt")
.CreateLogger();

**Comment by leastprivilege** [comment]
If you feel that this information is missing from the docs, please open an pr. Thanks

**Comment by richardterris** [comment]
I'm not really sure why this was closed because it certainly isn't resolved.
In spite of what I've said in the comments, there seems to be a perception that I haven't followed the documentation, and I need to be clear once more in saying that this isn't the case.

I have set things up exactly as per this https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

and as I asked above in a previous comment - does it matter that I'm calling this in a unit test? I don't think it should be just in case.
The log files are not being created where I'm asking them to. 

I really hope someone can actually take a couple of minutes to help, instead of jumping at any chance to tell someone they aren't following docs and closing issues.

**Comment by brockallen** [comment]
If you've configured SeriLog, can you call their logging API directly and see/find the log output?

**Comment by richardterris** [comment]
I have this in startup: `Log.Logger = new LoggerConfiguration()
              .MinimumLevel.Debug()
              .WriteTo.File(@"C:\Users\Richard Terris\Desktop\idsLogs.txt")
          .CreateLogger();`

Which isn't working. Unless I'm mistaken then 'Log' belongs to SerliLog so I assume this is what you mean.

Please, if I'm missing something then tell me, because I really am trying to follow the docs and the advice here

**Comment by richardterris** [comment]
Hey @brockallen I managed to get logging working by wrapping my test in ` using (var logger = new LoggerConfiguration()
              .MinimumLevel.Debug()
              .WriteTo.File(@"C:\Users\Richard Terris\Desktop\idsLogs.txt")
          .CreateLogger())
            {`

There may be a better solution but if it's working it's working!

I'll take a look through the log file and see if I can solve my actual problem now, and if not I'll log another issue here.

In the meantime, thanks for the assistance!

**Comment by brockallen** [comment]
No prob. Glad you have it working (and glad you figured that out -- I would not have known that was the issue).

**Comment by richardterris** [comment]
Might it be worth documenting this for other people, in case they're unit testing?

**Comment by leastprivilege** [comment]
Feel free to add that information to the logging doc page.
