### ISSUE TITLE
Audience mismatch - id_token - private/public IP Address

### ISSUE THREAD

**Issue by DonaldRecord** [IdentityServer/IdentityServer3#3085]
- [ X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Moreso a question than an issue, but I am having an issue with my Angular site getting a valid id_token from IdentityServer3. In a nutshell, my architecture is as follows:

I have three hosted projects via IIS - an AngularJS website, a WebAPI Project, and an STS Server utilizing IdentityServer3. When the website makes calls to the WebAPI, the WebAPI handles interactions with the STS Server. Since they are all on the same machine/IIS instance, the WebAPI uses the private IP Address of the STS Server. There is no problem there. However, the website makes an id_token request to the STS Server (AJAX)  using the Public IP Address and fails because of audience mismatch.

I have scanned through the IdentityServer3 documentation/source trying to find a way to essentially validate against both, and have tried a few things to no avail. One thing I tried was to set the IssuerUri and PublicOrigin properties in the IdentityServerOptions to the public IP Address, but that did not help my problem. I also tried creating an 'aud' scope claim for the two scopes that are used in the project but that did not solve my problem. What would you recommend given my situation? Please ask questions if necessary.
Thank you for taking the time to read this.

![image](https://cloud.githubusercontent.com/assets/5122103/17029006/7f3f0500-4f37-11e6-95f4-8cf249579d3f.png)

**Comment by leastprivilege** [comment]
You should set a fixed issuer name - you can do that on the `IdentityServerOptions`. This way the tokens will always use the same issuer and hence audience.

**Comment by DonaldRecord** [comment]
What property are you referring to? IssuerUri, PublicOrigin, or SiteName?

**Comment by leastprivilege** [comment]
IssuerUri

**Comment by DonaldRecord** [comment]
I changed my configuration on my public WebAPI to only use DNS for contacting the STS Server and the problem went away. Thank you for your help. (It wasn't a problem with the library, but with my configuration)
