### ISSUE TITLE
Extra pages when hosted with WIndows Service

### ISSUE THREAD

**Issue by eaba** [IdentityServer/IdentityServer3#3086]
- [* ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I want to transfer my IdentityServe3 Hosting to Windows Service from IIS, but I am finding it hard to think on how to add more pages like registration page.

This i can do with MVC, but how can such be achieved with a windows service hosted IdentityServer3.
I need a bit of a help.

Thanks!

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
