### ISSUE TITLE
Login redirect to custom domain other than the one which requested

### ISSUE THREAD

**Issue by Krishna-teja** [IdentityServer/IdentityServer3#3087]
### Question / Issue
I have a unique scenario where my users come from myapp.com, then they would be redirected to idsvr login and we have a custom field for entering district code and then after they login they need to be redirected to districtcode.myapp.com. Users will not be going directly to districtcode.myapp.com, so they don't actually come from that domain. So can I use idsvr for this scenario. 

The only way that I can think of is after they login send them back to myapp.com where they came from with districtcode as a claim and redirect them back to districtcode.myapp.com and also register districtcode.myapp.com as a valid redirecturi?

Is this the way I have to go with? or is there any other approach that I can take? 
Thank you for your time.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
