### ISSUE TITLE
Deploying IdentityServer to Live

### ISSUE THREAD

**Issue by danielbarnes1980** [IdentityServer/IdentityServer3#3088]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I have an Identity Server instance working on my local machine and can got to \core and \admin and all works great.  I have now deployed the Web application to a live environment and I just get a 404 when using \core and \admin.  

Of course there are no actual pages to address and its just a compiled DLL.

How do you I get this to work on my live environment?
 
I have the following code startup.cs

`  public void Configuration(IAppBuilder app)
    {
        LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());
        Log.Logger = new LoggerConfiguration()
           .MinimumLevel.Debug()
           .WriteTo.Trace()
           .CreateLogger();

        var connectionString = "MembershipReboot";

        app.Map("/admin", adminApp =>
        {
            var factory = new IdentityManagerServiceFactory();
            factory.Configure(connectionString);

            adminApp.UseIdentityManager(new IdentityManagerOptions()
            {
                Factory = factory
            });
        });

        app.Map("/core", core =>
        {
            var idSvrFactory = Factory.Configure();
            idSvrFactory.ConfigureCustomUserService(connectionString);

            var options = new IdentityServerOptions
            {
                SiteName = "IdentityServer3 - UserService-MembershipReboot",

                SigningCertificate = Certificate.Get(),
                Factory = idSvrFactory,
                AuthenticationOptions = new AuthenticationOptions{
                    IdentityProviders = ConfigureAdditionalIdentityProviders,
                }
            };

            core.UseIdentityServer(options);
        });
    }`

So running https://localhost:9234/Admin will load the MembershipReboot Admin Page and running https://localhost:9234/Core will load IdentityServer Front page and https://localhost:9234/core/.well-known/openid-configuration will load the configuration page but when I deploy this to the server I just get 404 when you try these links.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
