### ISSUE TITLE
Support client certificate authentication on token endpoint

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#309]
for user or client authentication? or both?

**Comment by leastprivilege** [comment]
For user authentication is can be done using PreAuthenticateAsync.

For client authentication the client validator needs to be extended. scheduled for 1.1

**Comment by leastprivilege** [comment]
Spiked and working - but postponed to 2.0 since it incurs a breaking change

see #847

**Comment by leastprivilege** [comment]
pretty much done - need some tests and better instructions for the sample

**Comment by Cont3xtSw1tch** [comment]
Do you have any samples for the user authenitcation to play around with?
