### ISSUE TITLE
Using JWT and reference tokens for the same client application.

### ISSUE THREAD

**Issue by dprochownik** [IdentityServer/IdentityServer3#3090]
Is it possible to use JWT and reference tokens for the same application?

In my situation I have MVC application which communicates with its clients using JWT tokens. 

Now I have to do integration with the third party service which is unable to perform login to IdSrv by itself, but It is possible to pass to it some temporary, short living string, which will by included in the web request to my MVC app.

The full flow:
1) Login to MVC app from web browser and get JWT Access Token
2) Get a reference Token usign currenc JWT Access Token and Pass it to the third party application
3) Perform some web request from the third party application to my Mvc app, usign reference token in the URL.
4) Invalidate used reference token

I can't use only JWT because of URL size limitations. I can't switch my app to use a reference tokens only, because I derives some benefits from JWT in the currently working clients.

So the question is: is it possible to get a reference token using valid JWT, or client secret, or anything else,, but keeping the possibility of using JWT for other MVC clients at the same time?

**Comment by leastprivilege** [comment]
If you are using our token validation middleware - you can use both token types in the same API.

**Comment by dprochownik** [comment]
I'm afraid that I didn't specify enought my question. 

I'm aware of that I can use both of those token types with yours middleware, but I'm not sure how to get a reference token in MVC appliacation which already uses JWT tokens. As I understood if I want to use a reference token I have to specify that in IdSrv at a Client level:
```
new Client {
   ...
   AccessTokenType = AccessTokenType.Reference,
}
```
But my MVC app is already registered as a client with JWT token type. Do I have to configure seperate IdSrv client with a different token type or maybe there is a possibility to get a reference token for my currently logged in MVC applicaiton?

**Comment by leastprivilege** [comment]
Ah I see - in that case you need to register a 2nd client.

**Comment by dprochownik** [comment]
Thanks for the info
