### ISSUE TITLE
"The remote certificate is invalid according to the validation procedure"

### ISSUE THREAD

**Issue by gitn00b1337** [IdentityServer/IdentityServer3#3091]
Hi, I have noticed this has been asked before but I have a certain question in particular regarding this. My full question is here: 

http://stackoverflow.com/questions/38569430/the-remote-certificate-is-invalid-according-to-the-validation-procedure

but for you guys I want to know simply why some tutorials/samples have client id & client secret within IdentityServerBearerTokenAuthenticationOptions and some don't. Am I right in saying the latest greatest does not need this? 

My setup is currently:

< package id="IdentityServer3" version="2.5.1" targetFramework="net452" />
  < package id="IdentityServer3.AccessTokenValidation" version="2.1.0" targetFramework="net452" />
  < package id="IdentityServer3.AspNetIdentity" version="2.0.0" targetFramework="net452" />

Please can someone confirm this is how it works for "UseIdentityServerBearerTokenAuthentication":

1. On load, the server will try to establish a connection with the Identity Server "box", and get the configuration details located at https://address/mapping/.well-known/openid-configuration
2. On receiving a request which needs authorizing, the request authentication header is inspected for a token
3. If the token is a JWT it inspects locally using the issuer name and key material found in the discovery doc. If it's a reference token it uses the access token validation endpoint on Identity Server

Therefore if I have a certificate on the identity server box, do I need to do something on the (in this case web API) client box to allow a SSL connection? My knowledge on this is incredibly limited. Huge thanks for reading

**Comment by gitn00b1337** [comment]
I also found this:

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/38

But I have no idea where you set the signing certificate or issuer for the bearer token options as they are not available

**Comment by gitn00b1337** [comment]
I have found these options by upgrading to latest. However, I am still unable to connect. I have set the bearer options with:

                ClientId = "api",
                ClientSecret = "secret"//,

And have the scope altered to:

new Scope
                {
                    Name = "api",
                    DisplayName = "Can call API",
                    Enabled = true,
                    Type = ScopeType.Resource,
                    ScopeSecrets = new List<Secret> { new Secret("secret".Sha256()) }
                }

I tried with and without loading the same certificate but neither work. I am unsure what issuerName is or if it's needed - the caption above says it's for if you dont want to use the discovery document (which I do). Any help at this point would be hugely appreciated as I've been stuck all day on this

**Comment by johnkors** [comment]
>But I have no idea where you set the signing certificate or issuer for the bearer token options as they are not available

How to set signing cert: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/WebHost%20(minimal)/WebHost/Startup.cs#L27

**Comment by johnkors** [comment]
>but for you guys I want to know simply why some tutorials/samples have client id & client secret within IdentityServerBearerTokenAuthenticationOptions and some don't. Am I right in saying the latest greatest does not need this?

The use of a `client_secret` depends on the flow of the client. Clients configured with implicit flow use redirect uris (amongst other things such as scopes) instead of secrets to verify the client.

**Comment by gitn00b1337** [comment]
Hi, thank you for the reply. I have since managed to get it working by upgrading latest. The bearer options then had the issuer name and signing certificate available. 

Is it correct to load the same certificate on all servers? I have copied the exact certificate from the identity server box to the web api box.

**Comment by gitn00b1337** [comment]
Now that the API server is not throwing certificate errors I am testing the jquery ajax calls to the API server. Unfortunately I am getting an OPTIONS error. Here is my request code:

     $($.ajax({
        url: "https://localhost:44356/api/Default/",
        headers: {
            "Authorization": "Bearer " + user.access_token
        },
        success: function (res) {
            logAjaxResult(res);
        },
        error: function() {
            logAjaxResult('Error');
        }
    }))

Which gives XMLHttpRequest cannot load https://localhost:44356/api/Default/. Response for preflight has invalid HTTP status code 405.

Normally this is an easy fix - I install Microsoft.AspNet.WebApi.Cors, set up a provider and allow OPTIONS through always. I can see how I would normally do this on the Identity Server box too as there is a CorsProvider you can register up. My issue however is on the API box I am using IdentityServerBearerTokenAuthenticationOptions and I see no CORs options. When I try to set up the WebAPI.cors provider though I get an error saying there are multiple origins set on the server to allow. This indicates to me (correct me if I'm wrong) that the WebApi box has somehow got the CORs settings from my identity server box that is registered as it's authority. Is this right? How do I configure to allow pre-flight requests? 

Many thanks

**Comment by leastprivilege** [comment]
that's a new issue.

To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
