### ISSUE TITLE
How to acheive single sign on with implicit and hybrid flows

### ISSUE THREAD

**Issue by Studentblanchard** [IdentityServer/IdentityServer3#3092]
### Question / Issue
I have two applications, an MVC app and a JS client, the MVC app is using the hybrid flow and the JS client uses the implicit flow. Everything works great up to this point. I can login via the MVC app, and when I navigate the JS app, we are logged in, great! Now if I try this the other way around, ie. login via JS app and then navigate over to the MVC app and we are prompted for login, not what I want. I have determined that the reason for this is that in implicit flow, there is no cookie set by IDSrv, since that flow uses bearer tokens. With hybrid flow, the cookie gets set, because it is needed by the hybrid client, and when the implicit app triggers the redirection flow, IDSrv sees the cookie, and determines that the user is logged in and issues the tokens to the JS app. 

My question is then the following...

Is setting the cookie in implicit flow the best solution to this problem? If so what configurations are needed to achieve this setup? Is this vulnerable to attacks? If so how can these be mitigated?

Here is the setup method of my SPA WebApi (ie JS implicit client)

            var config = new HttpConfiguration();

            WebApiConfig.Register(config);

            app.UseIdentityServerBearerTokenAuthentication(
                 new IdentityServerBearerTokenAuthenticationOptions
                 {
                     Authority = ConfigurationManager.AppSettings["IdentityAuthority"],
                     PreserveAccessToken = true,
                     ValidationMode = ValidationMode.ValidationEndpoint,
                     RequiredScopes = new[] { "everestAPI" }
                 });

            app.UseClaimsTransformation(new ClaimsTransformer().Transform);
            app.UseCors(CorsOptionConfig.Get());

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseWebApi(config);

            config.Filters.Add(new AuthorizeAttribute());

            GlobalConfiguration.Configuration.Filters.Add(new NHibernateSessionActionFilterAttribute());

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
