### ISSUE TITLE
Necrobot error

### ISSUE THREAD

**Issue by Zekinhaafonso** [IdentityServer/IdentityServer3#3093]
I'm trying to log in the necrobot and it's don't log's, yesterday that have working with no problem.

### Question / Issue

What appening and what i must do o solbe that? Because the pokemon go servers apears online

### Relevant parts of the log file

the error log
http://pastebin.com/frjrY8me

<log goes here>
```
the error log
http://pastebin.com/frjrY8me

**Comment by koukan118** [comment]
ああ

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
