### ISSUE TITLE
IdentityServer and MembershipReboot - same vs different projects/solutions

### ISSUE THREAD

**Issue by nosmalldreams** [IdentityServer/IdentityServer3#3096]
### Question / Issue
I've implemented MembershipReboot and IdentityServer according to the pattern from the MembershipReboot sample you've provided [here](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MembershipReboot), all in a single solution/project. I'm using a custom user store, so this made sense to me since both the user administration and the authentication functionality need to access the user store. However, I'm wondering if that's not right, based on the following:

1. Scott Brady's comment [here](http://stackoverflow.com/questions/35795394/identityserver3-custom-login-and-registration-screen): "Extra to this, the IdentityServer team recommends you consider Account Registration separate from Identity Server. It should be treated as another application."

2. Comment in the Github code for IdentityManager [here](https://github.com/IdentityManager/IdentityManager/blob/master/source/Host/Startup.cs):
```
    // this configures an embedded IdentityServer to act as an external authentication provider
    // when using IdentityManager in Token security mode. normally you'd configure this elsewhere.
```

What is considered best practice for project/solution structure for IdentityServer3 and MembershipReboot/IdentityManager? Is the reason why separation is suggested that it might be desirable to scale up / down instances of the authentication server separately from the user admin server as they could have very different user loads, or is there some other reason?

Many thanks!

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
