### ISSUE TITLE
How to configure reset password?

### ISSUE THREAD

**Issue by laksh-parab** [IdentityServer/IdentityServer3#3099]
###  Question

I have posted my question on stackoverflow but didn't get answer so asking question here
[Here is the question](http://stackoverflow.com/questions/38620224/identityserver3-how-to-configure-resetpassword)

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
