### ISSUE TITLE
Obtaining Email Through Twitter Authentication

### ISSUE THREAD

**Issue by markgmarkg** [IdentityServer/IdentityServer3#3101]
Hi,

I'm using IdentityServer3 with external authentication providers.
I manage to retrieve emails through standard scopes out of all major platforms Google, Facebook, LinkedIn, but Twitter.

Twitter requires special permission to allow "verifying" user's details (e.g. email) through additional Twitter API call.
In order to perform such a call, we need to utilize Twitter access token and Twitter access token secret that passed through TwitterAuthenticatedContext.

### Question
_What would be the right place to perform such a call?_

Should it be "OnAuthenticated" delegate in "TwitterAuthenticationProvider"? 
Although, it might become a performance bottleneck, because it'll happen all the time regardless whether we've already obtained user's email.

What additional solutions might be an alternative?

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
