### ISSUE TITLE
Logging in with Twitter doesn't work - just hangs

### ISSUE THREAD

**Issue by jonbarthol** [IdentityServer/IdentityServer3#3103]
This may be related to Issue #2360 which is closed. Twitter authentication was working for me a few weeks ago, so I'm wondering if something changed with Twitter's TLS certificates. The logging shows that the call to https://api.twitter.com/oauth/request_token is successful, but then the login page hangs for a while. The next log entry is 26 seconds later: "Clearing tokens". I tried adding every single DigiCert certificate thumbprint to the CertificateSubjectKeyIdentifierValidator list, but to no avail. We have another web application (not using IdentityServer3) that authenticates just fine with the same Twitter app. Any ideas? Thanks.

**Comment by brockallen** [comment]
This is something you should ask Microsoft. We don't support their products.

**Comment by jonbarthol** [comment]
@brockallen: I'm confused by your response.  You and @leastprivilege both responded to issue #2360 which is a similar issue. @ericgreenmix had a solution. I was hoping there was a similar solution. You do support external authentication and even have a Twitter example [here](IdentityServer3/source/Host.Configuration/IdentityServerExtension.cs) I was wondering if anyone had had the same problem. Thanks.

**Comment by brockallen** [comment]
I don't know of any solution.

**Comment by totpero** [comment]
Try this:
http://stackoverflow.com/questions/25011890/owin-twitter-login-the-remote-certificate-is-invalid-according-to-the-validati

**Comment by jonbarthol** [comment]
Thanks. I saw that post too. I think I figured it out the problem. The old DigiCert SHA2 High Assurance Server C‎A value was 5168FF90AF0207753CCCD9656462A212B859723B and expired on June 28. The new value is 01C3968ACDBD57AE7DFAFF9552311608CF23A9F9.
