### ISSUE TITLE
Scopes and Claims

### ISSUE THREAD

**Issue by DFullbrook** [IdentityServer/IdentityServer3#3104]
I'd like to ask a question to confirm my understanding of how to use Scopes and Claims. Let's say I have a User (User A with read only rights), a Windows Service (Client A with read only access), an MVC site (Client B with full access), and a Web API. I want the Web API to be accessed by Users and Clients with full access and read only access.

1. I create two Scopes "sampleApi.full and "sampleApi.read_only"
2. I create two Claims "full_access" and "read_only"
3. I configure the Web API with RequiredScopes = new[] {"sampleApi.full", "sampleApi.read_only"}

When Client A connects to the Web API, it passes an Access Token containing Scope "sampleApi.read_only" and I can use [ScopeAuthorize("sampleApi.full)] or ScopeAuthorize("sampleApi.full, sampleApi.read_only")] on my Classes and Methods to fine tune accessibility. No problem.

However, when User A logs in, then he/she "inherits" the Scopes of Client B. So the Access Token contains "sampleApi.full", "sampleApi.read_only", and Claim "read_only".

Now I have a problem at the WebApi in that I need to act differently when being called by a User. In that case I ignore the Scopes and use his/her Claims and the User gets "read_only" access which is what I want.

That being correct, it no longer makes sense  to use the ScopeAuthorize attribute, and I need a custom hybrid attribute that does something along the lines:

    If Caller is a User
         - then use Claims to determine accessibility
    Else
         - use Scopes to determine accessibility

or have I completely misunderstood?

**Comment by leastprivilege** [comment]
As explained a couple of times - scopes are not related to user authorization. check the archives or ask on SO. 



https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by DFullbrook** [comment]
Thanks, will ask on SO.
