### ISSUE TITLE
Claims Transformation at Web API

### ISSUE THREAD

**Issue by DFullbrook** [IdentityServer/IdentityServer3#3105]
I have followed the sample **MVC Authorization & Authorization** documentation and worked through coding it all up. Claims Transformation at the client side works fine ("nameidentifier" becomes "sub" etc, etc.). I then call the Web API on behalf of the User and pass the "access_token". However, when I view the claims contained in the ClaimsPrincipal at the Web API, they are not transformed. I think I'm missing a step?

**Comment by DFullbrook** [comment]
Understood. Is there any example code for doing this? Thanks.

**Comment by leastprivilege** [comment]
It works exactly the same as in MVC

**Comment by DFullbrook** [comment]
Thanks! All I needed was:

JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

in my startup in the Web API.
