### ISSUE TITLE
ResourceOwner Flow with User Account Whitelisting

### ISSUE THREAD

**Issue by Roundaround** [IdentityServer/IdentityServer3#3107]
I've recently been put in charge of developing and maintaining the IdentityServer3 SSO implementation for the nearly dozen internally-developed applications my company has created over the years.  I'm in the process of setting up clients and I found the need to create a ResourceOwner flow for a background process run by a service account.  I checked the documentation and searched through issues here on GitHub and can't find anything pertaining to a user account whitelist system. So my question is this:

Is there any way to set up a ResourceOwner-flow client that accepts login only by a whitelisted set of accounts?  If not out of the box, what classes/interfaces do I need to look into to implement such a system?  Keep in mind we have it currently hooked up to globally allow all domain accounts to authenticate, and I'd only want to restrict on this one specific client.

Any input and suggestions would be most welcome.

**Comment by Roundaround** [comment]
I should probably add that I saw the ClientCredentials flow as well, which seemed to be essentially the same as ResourceOwner except without the user identity (username & password).  Again, I have chosen the ResourceOwner flow in hopes that I might be able to restrict the client access to a specific one or two domain service accounts.

**Comment by brockallen** [comment]
If the client has no human, then client credentials is the right flow. Then on that client you configure the credentials you want to have it use. If you need multiple "accounts", then configure multiple clients.

**Comment by Roundaround** [comment]
I guess I'm at a loss here.  I can't find anything in the docs about configuring a client to use a service account's credentials.  We can't afford to leave the identity empty because the API we're securing does lookups by the user identity in its own database for local user permissions (ie filtering what it can see) - even for the service account.

Is there documentation on this somewhere and I just can't find it?

**Comment by brockallen** [comment]
There's no direct support for integrated windows auth, if that's what you mean. Your client would need some explicit credentials, such as a clientid/secret or a client certificate.
