### ISSUE TITLE
Logging client id for reporting

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer3#3111]
### Question 
I am looking at options to log client id for every request (if available), so that it can be used for reporting purpose to find out the number of request per client. Ids logs the client id for token request when LogLevel is Information. I am assuming we have to write another middleware to look for client id in FormBody/ Request header. 

Wanted to know if there anything that is already built into ids?

**Comment by brockallen** [comment]
Look into the IEventService.

https://identityserver.github.io/Documentation/docsv2/configuration/events.html
and
https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html

**Comment by akshetty9** [comment]
Thanks.
