### ISSUE TITLE
Is it possible to get the users "remember me" answer?

### ISSUE THREAD

**Issue by martinip86** [IdentityServer/IdentityServer3#3113]
FYI this is a question relating to Identity Server v1.6 - I know, we need to upgrade soon!
----

Hi guys,

Recently our team has enabled the RememberMe functionality supported within the CookieOptions: 

    new CookieOptions { AllowRememberMe = true, RememberMeDuration = TimeSpan.FromDays(30) }

This is all working great; the problem is that **we would like to know whether or not the end user has checked the remember me checkbox**. The idea being that we can pass this information on to the site we are authenticating (probably in an additional claim) so they can decide whether or not they should drop a persistent cookie on their side (we want to give them all the information so they can make an informed decision). 

Having had a read through the inner workings of the AuthenticationController's login method, all the form data looks pretty internalised:
https://github.com/IdentityServer/IdentityServer3/blob/1.6.0/source/Core/Endpoints/AuthenticationController.cs#L155

Is there an endpoint / interface / anything we may have missed in the documentation, that would allow us to get this information?  Perhaps even if there is a way of doing this in a later version of ID server (if we were to upgrade)?

Any advice, pointers would be most appreciated.

All the best.

**Comment by brockallen** [comment]
In your user service you can inject the OwinEnvironmentService and look at the posted values -- specifically the "RememberMe" value.

**Comment by brockallen** [comment]
Any progress/update?

**Comment by martinip86** [comment]
Thanks Brock, apologies I somehow missed the notification of the update! I'll have a look at this later today hopefully and get back to you.

**Comment by martinip86** [comment]
Hi Brock,

I've managed to get this all working now. Thanks a lot for the pointer.

For anyone interested I had to:

1. Register the OwinEnvironmentService in my DI container
`builder.Register(c => new OwinEnvironmentService(HttpContext.Current.GetOwinContext().Environment));`
2. Pass in the OwinEnvironmentService to the required class
` public OwinRequestDataExtractor(OwinEnvironmentService owinEnvironmentService)`
3. Read out the form data from the owin.RequestBody param
`const string owinPostBody = "owin.RequestBody";
            if (!_owinEnvironmentService.Environment.Keys.Contains(owinPostBody))
                return null;

            var owinFormData = _owinEnvironmentService.Environment[owinPostBody] as System.IO.Stream;
            if (owinFormData == null)
                return null;

            var formData = string.Empty;
            using (var sr = new System.IO.StreamReader(owinFormData))
            {
                formData = sr.ReadToEnd();
            }

            if (string.IsNullOrWhiteSpace(formData))
                return null;

            var formDataParsed = HttpUtility.ParseQueryString(formData);
            var rememberMe = formDataParsed["RememberMe"];`

**Comment by vladislav-karamfilov** [comment]
Hi, @martinip86! I have the same situation and I need to let the clients/RPs know if the user clicked the "Remember me" checkbox. I added the `OwinEnvironmentService` dependency to my `UserService`. Then I'm reading the value from the Owin request body and adding it to the claims in `PostAuthenticateLocalAsync` but the claim is not persisted when accessing the IdSvr token endpoint... Where do you store the value? 
PS I thought of storing it in the DB but I'm not sure if it's a good idea yet.
