### ISSUE TITLE
Integration with AppInsights requires the full Exception in IEventViewService

### ISSUE THREAD

**Issue by foggonda** [IdentityServer/IdentityServer3#3114]
I'm trying to integrate AppInsights into an application that uses IdentityServer3.  However because we don't have the full exception passed out as part of the [RaiseUnhandledExceptionEventAsync ](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/IEventServiceExtensions.cs#L409) method we're left with the ToString() version to try and parse back to the real exception.

Is there any reason why the actual exception that is being raised (which is passed in) isn't used as the Event<Exception> when it's ultimately raised as the event?

**Comment by johnkors** [comment]
If it's any comfort, you do have them in the logging mechanism (as opposed to the eventing system).

`LogProvider.SetCurrentLogProvider(new YourCustomLogProviderDoingStuffWithExceptions());`
