### ISSUE TITLE
The client application is not known or is not authorized. 

### ISSUE THREAD

**Issue by sankarj17** [IdentityServer/IdentityServer3#3116]
when i am working with MVC Walk through application which is  given in github Url is
https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html
Source code is given in https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Simplest%20OAuth2%20Walkthrough
i am getting the above error
that The client application is not known or is not authorized. 
Here is my code what i am using...
for this application i am trying for flow type is Implicit 

In Client file...

new Client 
                {
                    ClientName = "MVC Client",
                    ClientId = "mvc",
                    Flow = Flows.Implicit,

                    RedirectUris = new List<string>
                    {
                        "https://localhost:44319/"
                    },
                    PostLogoutRedirectUris = new List<string>
                    {
                        "https://localhost:44319/"
                    },
                    AllowedScopes = new List<string>
                    {
                        "openid",
                        "profile",
                        "roles",
                        "sampleApi"
                    }
                },

Startup file
------------

app.Map("/identity", idsrvApp =>
                {
                    idsrvApp.UseIdentityServer(new IdentityServerOptions
                    {
                        SiteName = "Embedded IdentityServer",
                        SigningCertificate = LoadCertificate(),

                        Factory = new IdentityServerServiceFactory()
                                    .UseInMemoryUsers(Users.Get())
                                    .UseInMemoryClients(Clients.Get())
                                    .UseInMemoryScopes(Scopes.Get()),

                        AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
                        {
                            EnablePostSignOutAutoRedirect = true,
                            IdentityProviders = ConfigureIdentityProviders
                        }
                    });
                });

            app.UseResourceAuthorization(new AuthorizationManager());

            app.UseCookieAuthentication(new CookieAuthenticationOptions
                {
                    AuthenticationType = "Cookies"
                });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
                {
                    Authority = "https://localhost:44319/identity",

                    ClientId = "mvc",
                    Scope = "openid profile roles sampleApi",
                    ResponseType = "id_token token",
                    RedirectUri = "https://localhost:44319/",

                    SignInAsAuthenticationType = "Cookies",
                    UseTokenLifetime = false,

                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        SecurityTokenValidated = async n =>
                            {
                                var nid = new ClaimsIdentity(
                                    n.AuthenticationTicket.Identity.AuthenticationType,
                                    Constants.ClaimTypes.GivenName,
                                    Constants.ClaimTypes.Role);

                                // get userinfo data
                                var userInfoClient = new UserInfoClient(
                                    new Uri(n.Options.Authority + "/connect/userinfo"),
                                    n.ProtocolMessage.AccessToken);

                                var userInfo = await userInfoClient.GetAsync();
                                userInfo.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Item1, ui.Item2)));

                                // keep the id_token for logout
                                nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));

                                // add access token for sample API
                                nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));

                                // keep track of access token expiration
                                nid.AddClaim(new Claim("expires_at", DateTimeOffset.Now.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToString()));

                                // add some other app specific claim
                                nid.AddClaim(new Claim("app_specific", "some data"));

                                n.AuthenticationTicket = new AuthenticationTicket(
                                    nid,
                                    n.AuthenticationTicket.Properties);
                            },

                            RedirectToIdentityProvider = n =>
                                {
                                    if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                                    {
                                        var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                                        if (idTokenHint != null)
                                        {
                                            n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                                        }
                                    }

                                    return Task.FromResult(0);
                                }
                    }

when i am using Oauth 2 through postman giving the Authorize urls and token url along with client credentials then i am getting error "The client application is not known or is not authorized. " instead of presenting me with a login screen.

please let me know what else i need to do ...
and one more thing may i know what is the process when we select Authorization code using postman OAuth 2.0 integration tools.

Thanks in advance!!!

**Comment by jonbarthol** [comment]
Try mapping your MVC client to a path other than the base URL (https://localhost:44319). For example:

app.Map("/mvc", idsrvApp =>
{
     idsrvApp.UseIdentityServerAuthentication(
          clientId: "mvc",
          redirectUri: "https://localhost:44319/mvc",
           scopes: new[]
          {
                ...
          });
});


You'll also need to change your LogoutRedirectUris and PostLogoutRedirectUris to match the new path.

**Comment by akshetty9** [comment]
Can you Enable logging and attach.

**Comment by sankarj17** [comment]
Hi jonbarthol ,
Thanks for your reply on this ..
I tried as suggested ...

**In Client File**

 new Client 
                {
                    ClientName = "MVC Client",
                    ClientId = "mvc",
                    Flow = Flows.Implicit,

                    RedirectUris = new List<string>
                    {
                        "https://localhost:44319/mvc"
                    },
                    PostLogoutRedirectUris = new List<string>
                    {
                        "https://localhost:44319/mvc"
                    },
                    AllowedScopes = new List<string>
                    {
                        "openid",
                        "profile",
                        "roles",
                        "sampleApi"
                    }
                },

**In Startup file** 

 app.Map("/mvc", idsrvApp =>
                {
                    idsrvApp.UseIdentityServer(new IdentityServerOptions
                    {
                        SiteName = "Embedded IdentityServer",
                        SigningCertificate = LoadCertificate(),
                        .................
      });
                });

 app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
                {
                    Authority = "https://localhost:44319/mvc",

                    ClientId = "mvc",
                    Scope = "openid profile roles sampleApi",
                    ResponseType = "id_token token",
                    RedirectUri = "https://localhost:44319/mvc",

                    SignInAsAuthenticationType = "Cookies",
                    UseTokenLifetime = false,

                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                       ...........................
    }
                });

same problem i am getting 
please find the attachment when i am trying from postman

Thanks in advance!!!
![oauth2 0 error](https://cloud.githubusercontent.com/assets/20815197/17397235/c4e95af6-5a54-11e6-903d-bcdd18532704.jpg)

**Comment by jonbarthol** [comment]
I couldn't get Postman to work with my implicit flow client either. I think Postman only handles Authorization Code and Client Credentials flows. Did you try routing to the https://localhost:44319/mvc in a browser? A couple things you need to change/add:

- "Authority" needs to be "https://localhost:44319/identity" not "https://localhost:44319/mvc"

- You didn't provide a ClientUri for your "mvc" client. It should be "https://localhost:44319/mvc"

Hope that helps!

**Comment by sankarj17** [comment]
thanks for reply!!!
Actually my requirement is, i need to get access token from Postman using OAuth utility 
after giving the ...
AuthorizeUrl = https://localhost:44319/identity/connect/authorize
token Url = https://localhost:44319/identity/connect/token
Client Id= codeclient
Client Secret = secret
when i invoke "Get New Access Token"
I am getting error "The client application is not known or is not authorized"

below is the client configured for Authorization code flow  in client.cs file

new Client
                {
                    ClientName = "Code Flow Client Demo",
                    ClientId = "codeclient",
                    Flow = Flows.AuthorizationCode,

                    ClientSecrets = new List<Secret>
                    {
                        new Secret("secret".Sha256())
                    },

                    RequireConsent = true,
                    AllowRememberConsent = true,

                    ClientUri = "https://identityserver.io",

                    RedirectUris = new List<string>
                    {
                        "https://localhost:44312/callback",
                    },

                    AllowedScopes = new List<string>
                    {
                        Constants.StandardScopes.OpenId,
                        Constants.StandardScopes.Profile,
                        Constants.StandardScopes.Email,
                        Constants.StandardScopes.Roles,
                        Constants.StandardScopes.OfflineAccess,
                        "read",
                        "write"
                    },

                    AccessTokenType = AccessTokenType.Reference,
                },
and in startup file ...

app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://localhost:44319/identity",

                ClientId = "mvc",
                Scope = "openid profile roles sampleApi",
                ResponseType = "id_token token",
                RedirectUri = "https://localhost:44319/",

                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                   ..........................
                        },

                        RedirectToIdentityProvider = n =>
                            {
                                if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                                {
                                    var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                                    if (idTokenHint != null)
                                    {
                                        n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                                    }
                                }

                                return Task.FromResult(0);
                            }
                }

what is the code need to be changed  in startup.cs file ?
Or 
Is there any way to work with the same application using Authorization code.
Thanks in advance!!!

**Comment by jonbarthol** [comment]
I can't get Postman to work either. Sorry.

**Comment by jonbarthol** [comment]
Actually, I think I figured it out. You need to add https://www.getpostman.com/oauth2/callback as a Redirect URI for your client.

**Comment by sankarj17** [comment]
Hi jonbarthol ,
Thanks for your reply ...
I have tried changing redirect uri to https://www.getpostman.com/oauth2/callback.
after change i am getting a blank screen and please find the attachment for your reference.
![identityservererror_mvcauthentication](https://cloud.githubusercontent.com/assets/20815197/17472779/8a458438-5d6a-11e6-9fb4-d29d93e8ff49.jpg)

**Comment by jonbarthol** [comment]
I am not sure what is causing the blank screen. Try only providing the "openid" scope.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by tamirs9876** [comment]
I had the same error and the advice from @jonbarthol did the trick:
my redirect uri was the base url `"http:localhost:57864/"` address. configuring it with another segment to `"http:localhost:57864/**home**" `solved the issue with the implicit flow.
question is why...?
