### ISSUE TITLE
Client Service Like IUserService 

### ISSUE THREAD

**Issue by nkdev89** [IdentityServer/IdentityServer3#3118]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Do you have any ClientService like IUserService? I'm interested in getting clients from Database. It would be great if there is any . 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by akshetty9** [comment]
You need to implement IClientStore for clients. https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html
https://identityserver.github.io/Documentation/docsv2/advanced/customServices.html
