### ISSUE TITLE
Inactivity timeout requiring re-authentication without logging out other clients

### ISSUE THREAD

**Issue by timscriv** [IdentityServer/IdentityServer3#3120]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I would like to implement a SPA that has an inactivity timeout that would require a user to re-authenticate before they can use the SPA again but I do not want to log out of IdentityServer because that will kick them out of any other application they may be actively using. How can I do this without making it possibly for the user to just change some JS so they never have an inactivity timeout? I am using AngularJS within an AspNet core project that will call AspNet apis that are on separate URLs.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by timscriv** [comment]
I apologize but I did ask this question on SO [here](http://stackoverflow.com/questions/38751098/identityserver-sign-out-of-one-apprequire-new-login-but-stay-signed-in-with-an) without anyone able to answer so I asked here.
