### ISSUE TITLE
REQUEST: Delete 2KM eggs

### ISSUE THREAD

**Issue by sinfuego** [IdentityServer/IdentityServer3#3121]
When you are an high enough level 2KM eggs do not deliver good pokemon. Therefore it should be nice to have config option to delete eggs of a certain type.

**Comment by lizter** [comment]
Actually, 2km eggs can hatch starter Pokemon like Squirtle, Charmander or Bulbasaur. Eggs have a higher chance to give you these pokemon with a good individual value, which you want to be as high as possible when evolving to the respective S-tier pokemon, e.g Charizard. You also get more candy from eggs than by catching them in the wild.

That being said, why you have posted this as an issue with IdentiyServer3 is beyond me. Happy to help, though!

**Comment by johnkors** [comment]
wtf :)

**Comment by johnkors** [comment]
Just submit a PR, @sinfuego !
