### ISSUE TITLE
Token logged in RaiseSuccessfulIntrospectionEndpointEventAsync event 

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer3#3122]
Question 

RaiseSuccessfulIntrospectionEndpointEventAsync event in [[line #L488)](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/IEventServiceExtensions.cs#L488)] includes the token in the event. Any reason for doing this? Logging this event will log the actual token in log files. Is this okay to do?

**Comment by leastprivilege** [comment]
We should probably show only a couple of characters..

**Comment by leastprivilege** [comment]
done
