### ISSUE TITLE
cross-site scripting

### ISSUE THREAD

**Issue by stevengopmo** [IdentityServer/IdentityServer3#3124]
Hi, 

I'm running an older version of IdSrv3 (1.3).  Recently we had a penetration & vulnerability scan and everything was really good except one issue.  I see the latest version has a library (AntiXssLibrary) for preventing such attacks, but I don't know if it is in the version I have.  Can you verify this is fixed in the latest?

> The value of the username request parameter is copied into a JavaScript expression which is not encapsulated in any quotation marks. The payload 11877;alert(1)//403 was submitted in the username parameter. This input was echoed unmodified in the application's response.

This is when the user is attempting to login and they are getting a response.

**Comment by brockallen** [comment]
Where in the rendered HTML is this an issue? I suspect it's referring to the `<script id='modelJson' type='application/json'>` element, but I think the complaint is not taking into consideration where the value is. Here is an example of where that value is rendered:

```
<script id='modelJson' type='application/json'>{&quot;loginUrl&quot;:&quot;/core/login?signin=3b671cc7dfc62cb142e68cb2ab736df2&quot;,&quot;antiForgery&quot;:{&quot;name&quot;:&quot;idsrv.xsrf&quot;,&quot;value&quot;:&quot;BeY5ZiEpNozNCJdAbgil5L3joN9bkObxGrBhJSCxeLf6UXfoM76MA-yzM02iaysCwbhXgFKHjXnMFSmvux0qWiXFuHq_Vi9p1l5p3G4QpQM&quot;},&quot;allowRememberMe&quot;:true,&quot;rememberMe&quot;:false,&quot;username&quot;:&quot;11877;alert(1)//403&quot;,&quot;externalProviders&quot;:[{&quot;type&quot;:&quot;was&quot;,&quot;text&quot;:&quot;Windows&quot;,&quot;href&quot;:&quot;https://localhost:44333/core/external?provider=was&amp;signin=3b671cc7dfc62cb142e68cb2ab736df2&quot;},{&quot;type&quot;:&quot;adfs&quot;,&quot;text&quot;:&quot;ADFS&quot;,&quot;href&quot;:&quot;https://localhost:44333/core/external?provider=adfs&amp;signin=3b671cc7dfc62cb142e68cb2ab736df2&quot;},{&quot;type&quot;:&quot;aad&quot;,&quot;text&quot;:&quot;Azure AD&quot;,&quot;href&quot;:&quot;https://localhost:44333/core/external?provider=aad&amp;signin=3b671cc7dfc62cb142e68cb2ab736df2&quot;},{&quot;type&quot;:&quot;Twitter&quot;,&quot;text&quot;:&quot;Twitter&quot;,&quot;href&quot;:&quot;https://localhost:44333/core/external?provider=Twitter&amp;signin=3b671cc7dfc62cb142e68cb2ab736df2&quot;},{&quot;type&quot;:&quot;Facebook&quot;,&quot;text&quot;:&quot;Facebook&quot;,&quot;href&quot;:&quot;https://localhost:44333/core/external?provider=Facebook&amp;signin=3b671cc7dfc62cb142e68cb2ab736df2&quot;},{&quot;type&quot;:&quot;Google&quot;,&quot;text&quot;:&quot;Google&quot;,&quot;href&quot;:&quot;https://localhost:44333/core/external?provider=Google&amp;signin=3b671cc7dfc62cb142e68cb2ab736df2&quot;}],&quot;additionalLinks&quot;:null,&quot;clientName&quot;:&quot;JavaScript Implicit Client - UserManager&quot;,&quot;clientUrl&quot;:&quot;https://identityserver.io&quot;,&quot;clientLogoUrl&quot;:null,&quot;errorMessage&quot;:&quot;Invalid username or password&quot;,&quot;requestId&quot;:&quot;80000010-0000-e700-b63f-84710c7967bb&quot;,&quot;siteUrl&quot;:&quot;https://localhost:44333/core/&quot;,&quot;siteName&quot;:&quot;IdentityServer3&quot;,&quot;currentUser&quot;:null,&quot;logoutUrl&quot;:&quot;https://localhost:44333/core/logout&quot;,&quot;custom&quot;:null}</script>
```

**Comment by stevengopmo** [comment]
It is appearing in the response to the login post

Request
`POST /identity/login?signin=4abbc1f0c8c0f1d7d26d3d366a78ece4 HTTP/1.1`

````
RK09JfAWuEyyiBTxLNLU_BSnciTfB-DiPS-
rNQmxHPtF4zs4gzFWBR90k2RucH_2L4D6XYjZ9B1ntp8PvA6RQmPzOIFIJG0i9WI&quot;},&quot;allowRememberMe&

quot;:true,&quot;rememberMe&quot;:false,&quot;username&quot;:&quot;admin11877;alert(1)//403&quot;,&quot;externa

lProviders&quot;:[],&quot;additionalLinks&quot;:[{&quot;text&quot;:&quot;Forgot

Password&quot;,&quot;href&quot;:&quot;/identity/user/forgotpassword?signin=4abbc1f0c8c0f1d7d26d3d366a
````

Looking closer at this it does appear to me it IS encapsulated in quotes (&quot;) but shouldn't the username be html encoded as well?

**Comment by brockallen** [comment]
It's JSON encoded. The XSS report you have is not taking into account how it's being rendered into the page I think. In short, if there were a vulnerability you'd see the alert pop up on the screen right?

**Comment by stevengopmo** [comment]
indeed.  the auditor was using some tool.  I'll test this myself and ensure it's not an issue.  now that I see the quotes I can argue the case anyway I think.  Thank you for your responses.
