### ISSUE TITLE
Implementing a Custom "Identity Provider" for certain Realms

### ISSUE THREAD

**Issue by Jacobeom** [IdentityServer/IdentityServer3#3125]
Hi all, 
I'm working in a certain scenario I need to solve and i'm thinking in using/extending Identity Server. 

Basically I do work in a Organization where major part of the "Web Applications" use a Ticket/Cookie solution to implement SSO. All applications are behind a certain domain "mycompany.com" using a Proxy so: **myCompany.com/A** and **myCompany.com/B** are different Web Applications but can share the Authentication Cookie (because are in the same domain) and so share the Ticket between them.  The User information (+ other ticket stuff) associated to the Ticket (existing in the Cookie) is stored in a Database and exposed via WEB Service so all applications (A,B, ....) can retrieve the actual logged user claims calling this Web Service passing the Ticket Id (contained in the Auth Cookie)

What can i say? It works, and the Org has implemented a SSO via a Shared Ticket btween all the different applications using the Proxy trick (all apps are in the same domain:mycompany.com)!!
But the company needs to move on and get a modern approach and we are thinking about replacing the Login Application **myCompany.com/Login** with Identity Service in the next way

- For Lets Say Application A and Application B keep on using a Ticket/Cookie Solution (extending the Identity Server Code)
- For new developed applications use the already OpenIdConnect Provider
- To add Sharepoint to the solution use the  IdentityServer3.WsFederation Provider
- All of this providers have to use the actual Identity Model we have built (SQL Server tables) to authenticate/retrieve claims and to issue Tickets and the Auth Cookie in case Resource requested is:  **myCompany.com/A/whatever** or**myCompany.com/B/whatever **
- Extendend Identity Server have to maintain the possibility of behave WS-Fed/Oauth2 Relying Party/Client Role (to consume other identity providers)

What do u think?....
Is it feasible to have a **custom DataMode**l and Add a new **Identity "provider"**??
Do i need to rewrite Some of the Identity Server Code? or just extending it will be enough?

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
