### ISSUE TITLE
I am not able to limit windows authentication to specific users or ADGroup

### ISSUE THREAD

**Issue by naveenkumarreddy** [IdentityServer/IdentityServer3#3127]
I am not able to limit windows authentication to specific users or ADGroup. Is there a way to do that or it is a limitation in Identity Server 3?

**Comment by brockallen** [comment]
Have you looked at the IsActive API on the user service?

**Comment by naveenkumarreddy** [comment]
Thank you brockallen for replay, I had looked into it but not I got clarity on the same. you mean the IsActiveAsync method is to verity the user from the specific user group by having active directory domain or DB right?

 using (var pc = new PrincipalContext(ContextType.Domain, DOMAIN))
            {
                using (var aduser = UserPrincipal.FindByIdentity(pc, IdentityType.SamAccountName, subject.Identity.Name))
                {
                    return Task.FromResult(aduser != null);
                }
            }

**Comment by brockallen** [comment]
Yes. That method is meant to answer the question "is the user allowed to get a token", and normally people use it to check if the user has been disabled in some way in the database, but you might be able to use it for your authorization logic.

**Comment by naveenkumarreddy** [comment]
Got it :+1: , if we are authenticating the user using AuthenticateLocalAsync method then why we need to have IsActiveAsync since we are doing the same in below method right? correct me if I am worng.
Also please let me know how can I do the same by using AthenticateExternalAsync method since I am using window authentication as external login.

 public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
        {
            try
            {
                using (var pc = new PrincipalContext(ContextType.Domain, DOMAIN))
                {
                    if (pc.ValidateCredentials(username, password))
                    {
                        using (var user = UserPrincipal.FindByIdentity(pc, IdentityType.SamAccountName, username))
                        {
                            if (user != null)
                            {
                                return Task.FromResult(new AuthenticateResult(subject: Guid.NewGuid().ToString(), name: username));
                            }
                        }
                    }

                    // The user name or password is incorrect
                    return Task.FromResult<AuthenticateResult>(null);
                }
            }
            catch
            {
                // Server error
                return Task.FromResult<AuthenticateResult>(null);
            }
        }

**Comment by brockallen** [comment]
You could also do the check there too. I wasn't sure how the user was authenticating.
