### ISSUE TITLE
Suggestion for improvement in construction of URL for Signin after redirect

### ISSUE THREAD

**Issue by RobKraft** [IdentityServer/IdentityServer3#3128]
We host our application in a web farm in the cloud behind a firewall that restricts the client IP address.  One app in the cloud talks to our Identity Server in the cloud all behind the firewall so we used localhost for the PublicOrigin of Identity Server.  We created a new client app to directly authenticate with the same Identity Server and the client app can get to the IdentityServer with our Public URL (test.Amazon.Com/IdSvr/core/connect/authorize), but the Location parameter returned by the redirect (302) URL replaces the host name with the PublicOrigin property of identity server (localhost/IdSvr/core/login?signin=...), and our client app cannot resolve localhost correctly.

I found that I can fix this problem by changing how the redirect URL is constructed to use the URL of the original request instead of the public host so now our redirect URL returns (test.Amazon.Com/IdSvr/core/login?signin=...).

This is the first change I have made to the Identity Server source code and I would like to know if you think this change is insecure or will cause other problems.

For reference, this is the change I made in the RenderLoginPage method of AuthenticationController.cs.  I do not think the change is the optimal fix that should be included in the Identity Server product, but it is the change I made so that we could test my theory.

What do you think?  Should the return URL be constructed to use the same host passed in by the client, or should it continue to use the host value configured in PublicOrigin?  I believe the product is more flexible using the host name provided by the client, but I may be overlooking a security concern.

 //SiteUrl = Request.GetIdentityServerBaseUrl(),
SiteUrl = message.ReturnUrl.Substring(0, message.ReturnUrl.IndexOf(Constants.RoutePaths.Oidc.Authorize)),

**Comment by brockallen** [comment]
Sorry, I don't quite follow -- why can't you use the PublicOrigin setting?

**Comment by RobKraft** [comment]
We set PublicOrigin to LocalHost.  We do this because our software is used in many installations that each need to control that configuration.  If we set PublicOrigin to test.amazon.com, then our internal applications will try to use test.amazon.com to get to identity server and they will fail because our Amazon firewall is configured to only allow a specific range of client IP addresses.  We can add our Amazon IP address to the firewall exception, but that IP address is somewhat dynamic and thus may change.  We can purchase/reconfigure our installations for static IP addresses from Amazon, but it will probably take us a few weeks to get those changes approved, tested, and implemented.  So, my real question, is, "Is it legitimate to use the Host value the sender used in calling core/connect/authorize as the Host for the redirect to core/login?signin?"

**Comment by brockallen** [comment]
Sure, you can do that. Off the top of my head I can't think of any issues. Doesn't mean there aren't any.

**Comment by RobKraft** [comment]
Thanks Brock!  For any other readers of this post, on IdentityServer version 3 I had to change the RedirectToLogin method of AuthorizeEndpointController.cs.  
        //var host = new Uri(Request.GetOwinEnvironment().GetIdentityServerHost());
	var host = new Uri(Url.Request.RequestUri.Authority);
