### ISSUE TITLE
/assets/app.crypto.min.js

### ISSUE THREAD

**Issue by achi2** [IdentityServer/IdentityServer3#3129]
using one of the sample clients: "JavaScript OidcClient and UserManager.csproj"

after running the project, i see in the console an error
PAGE: http://localhost/MyIDS3/connect/checksession is trying to load

<body>
    <script id="cookie-name" type="application/json">idsvr.session</script>
    **_<script src="http://localhost/MyIDS3/assets/app.crypto.min.js"></script>_**

and get a 404 error

looking at the sources if IDS3 i see that this file exists in the assets folder.

besides the 404, i don't see any errors in the console, so maybe this js requirement is not actually being used in this scenario.

any insights would be helpful.

thanks

**Comment by brockallen** [comment]
Do you have RAMMFAR enabled?

**Comment by achi2** [comment]
seems to solve the problem.   :100:
