### ISSUE TITLE
Id token shared amount multiple clients

### ISSUE THREAD

**Issue by yusbel** [IdentityServer/IdentityServer3#3130]
Brief: I have multiple web app clients using authorization code flow, each application have different key and secret but all of them use the same authorization server.

I want to add in the ID token audience field the IDs off all web apps, then share the token so that users do not need to authenticate.

Is this possible?. If yes, Do all the client need to use the same client id and secret? 

can the second web application use the id token to request an access token form the token end point?. I'm trying to use the ID token to create a session amount all web apps to do a SSO user experience.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
