### ISSUE TITLE
Redirect on Session Timeout

### ISSUE THREAD

**Issue by SamV8** [IdentityServer/IdentityServer3#3131]
In my asp.net mvc angular app I want to redirect user to login page after session expire, but the problem is that session is disabled and I have to use cookies instead. 
I set DefaultTokenLifetime and SsoCookieLifetime from 10 to 1 but after this time, when I click on some link it gives me empty template(without data) and no redirection to login page, but if I try to refresh page, than it redirects me to login page?
Why this happens and how to achieve this?

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
