### ISSUE TITLE
How does the trust work between the Authority and my Web API?

### ISSUE THREAD

**Issue by RemotecUK** [IdentityServer/IdentityServer3#3133]
My Angular JS application is using Implicit flow to gain a token from the Identity Server authority which it then uses  to call various .Net web APIs.

I have the following configuration in the API...

```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
{
    Authority = "https://login.domain.com",
    RequiredScopes = new[] 
    {
        Constants.Scopes.Api,
    }
});
```

I have checked the logs (with HTTP logging turned on) and also debugged some of the source code but cannot see how the API validates the token with the authority if this is needed. I also note that I have not specified a client id or secret for my API, or registered that data with the authority.

Questions
- Does the token need to be validated?
- If not could anyone form a token and use it to access my API?
- How does the trust relationship work between the client and the authority?

Thanks in advance.

**Comment by brockallen** [comment]
Yes, the token needs to be validated. It's unclear if you're using a JWT or a reference token, but the above MW will validate it. Trust is established via the authority property you set above. An attacker could only create their own token if they have a copy of the private key from the signing certificate.

**Comment by RemotecUK** [comment]
It's a JWT token. Could you point me to roughly where this happens? Should I expect any logging of the interaction between the client and authority? I've had a dig through the source code and placed some breakpoints in methods stemming from `IdentityServerBearerTokenValidationAppBuilderExtensions` but didn't spot anything.
Thanks.

**Comment by brockallen** [comment]
Our middleware wraps the Microsoft JWT middleware when the incoming token is a JWT. So you'd need to enable katana logging to see any logging out the process. https://identityserver.github.io/Documentation/docsv2/consuming/diagnostics.html

**Comment by RemotecUK** [comment]
Is there a reason why the client and authority don't need to exchange an id secret for this validation? I guess it's not needed. An attacker could fire tokens all day to the token validation end point but unless they have the private key they would just be noise?

**Comment by brockallen** [comment]
They only need that if the API is sending the token to the authority. There's a spec called "introspection" for this.

For JWTs, it's not needed -- the only thing the API needs is the metadata from the authority.

**Comment by RemotecUK** [comment]
On startup IIS logs show the API obtaining the metadata. 
Thanks again.
