### ISSUE TITLE
Serilog trace logging not working

### ISSUE THREAD

**Issue by yusbel** [IdentityServer/IdentityServer3#3134]
What I'm missing?

app.UseIdentityServer(new IdentityServerOptions
            {
                RequireSsl = false,
                SiteName = "Authorization Server",
                SigningCertificate = LoadCertificate(),

                Factory = new IdentityServerServiceFactory()
                                .UseInMemoryUsers(Users.Get())
                                .UseInMemoryClients(Clients.Get())
                                .UseInMemoryScopes(Scopes.Get()),

                AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
                {
                    EnablePostSignOutAutoRedirect = true,
                    IdentityProviders = ConfigureIdentityProviders
                },
                LoggingOptions = new LoggingOptions()
                {
                    EnableHttpLogging = true,
                    EnableKatanaLogging = true,
                    EnableWebApiDiagnostics = true,
                    WebApiDiagnosticsIsVerbose = true
                }
            });

Log.Logger = new LoggerConfiguration()
                            .MinimumLevel.Verbose()
                            .WriteTo.Trace()
                            .CreateLogger();

<system.diagnostics<
    <trace autoflush="true" indentsize="4"<
      <listeners<
        <add name="myListener"
              type="System.Diagnostics.TextWriterTraceListener"
              initializeData="C:\Logs\Serilog\Trace.log" <
      </listeners<
    </trace<
  </system.diagnostics<

The application have write permission to the serilog log folder.

any idea?

**Comment by brockallen** [comment]
Nope, but:

To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
