### ISSUE TITLE
No access_token received

### ISSUE THREAD

**Issue by samsopheak** [IdentityServer/IdentityServer3#3136]
Hi All,

### Question / Issue
Since last week, I've been trying to get the examples  https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNet5/src/MvcClient  to work in aspnet core rtm (targeting .net 4.6.1).

Console client works fine, but not the mvc client. It was able to authenticate against the server, however it received no token info like (access_token, id_token).

This morning, I manually compile https://github.com/IdentityServer/IdentityServer3.Integration.AspNetCore using identityserver3 dev branch https://github.com/IdentityServer/IdentityServer3/tree/dev, reference in the project and still no luck.

I have attached the log.

Any help please?

Thanks,
Sam

### Relevant parts of the log file

```
<log goes here>
```
[idspoc3.txt](https://github.com/IdentityServer/IdentityServer3/files/416433/idspoc3.txt)

**Comment by brockallen** [comment]
From the log, everything is fine on the IdSvr side. You'll need to debug into the MVC side for where the access token is. Have you configured "save tokens" on the OIDC middleware?

**Comment by samsopheak** [comment]
Hi brockallen,

Thanks for the tip, finally I managed to get the token. I had to transform the ticket prop to claim

openIdOptions.Events = new OpenIdConnectEvents()
{
	OnTicketReceived = context =>
	{
		var identity = context.Principal.Identity as ClaimsIdentity;
		if (identity != null)
		{
			var claims = context.Ticket.Properties.Items;
			foreach (var item in claims)
			{
				var key = item.Key;
				if (key.StartsWith(".") && key.LastIndexOf(".") == 0)
				{
					key = key.Replace(".", string.Empty);
				}
				else if (key.StartsWith(".Token."))
				{
					key = key.Replace(".Token.", string.Empty);
				}

				identity.AddClaim(new Claim(key, item.Value));
			}
		}
		return Task.FromResult(0);
	}
}

Thanks again,
Sam
