### ISSUE TITLE
loginWithDifferentAccountUrl force a full log out of the logged in user first.

### ISSUE THREAD

**Issue by wiseman13** [IdentityServer/IdentityServer3#3140]
- [ X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
When using the built in prompt for model.loginWithDifferentAccountUrl I noticed that this does not log out the current user until you sign in with the new credentials. I was wonder how I could setup the model.logoutUrl option so that when I call it the current user is logged out, but then it auto redirects to the authorize end point for the client and scopes that had been passed in. I am guessing this might be possible by implementing my own IViewService and customizing the Logout, but I was not sure if there was an easy way to get the clientid and scopes and redirect uri like the model.loginWithDifferentAccountUrl has, but still log out the current user.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
There's no support for that. Can you elaborate on the requirement?

**Comment by wiseman13** [comment]
Basically the business people do not like having the two links on the consent page and that when a user selects to logout from that they just end up on a default logout page. I was thinking of doing it with the logout end point by passing a redirect uri, but since this is all in the Identity Server that felt pretty dirty. I mean it is different if an application is calling the logout endpoint with a token, but this is in the middle of the auth step. Is there a way when going though the authorize is there some way to modify model.logoutUrl based on the information passed in to authorize call?

**Comment by brockallen** [comment]
If you allowed this, then someone could DOS your users by forcing them to be logged out (say via a malicious <img> or <iframe>). 

In any event, not sure if you came up with a workaround or not, but whatever you do for your requirements I think you'd have to do it by customizing the view service and the UI templates.
