### ISSUE TITLE
Cannot attach JToken or POCO to TokenResponse

### ISSUE THREAD

**Issue by bradacina** [IdentityServer/IdentityServer3#3141]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I've implemented a ICustomTokenResponseGenerator and hooked it up to IdentityServer3.
Adding base .net types to the TokenResponse.Custom dictionary correctly shows up in the TokenResponse that clients are getting.

But if I add either a JToken or my own POCO I run into trouble.

1. Attaching a JToken ( aka. when JToken is not JToken )

In my custom token response generator, I create a JToken.FromObject() and add it to the Custom dictionary. I double check that `Custom["key"] is JToken` and indeed it is. But as soon as the TokenResult.Execute() code is run, the Custom["key"] is not a JToken anymore. I suspect that has to do with the fact that there is a Newtonsoft.Json assembly internalized in IdentityServer3.dll and the two JToken types are now distinct. This will bork the Newtonsoft serialization since it relies on this particular check to correctly serialize a JToken. Newtonsoft's JProperty constructor code will think that my object is an IEnumerable (because it somehow ends up as a JObject) and thus will output an empty array at serialization time.

2. Attaching a POCO

Newtonsoft tries to directly cast the POCO to a JToken and ends up with an InvalidArgumentException stating that it doesn't know how to serialize my POCO.

Any workarounds for this? I suspect that the TokenResult.Execute() needs to introspect the values of the Custom dictionary to better handle the different object types that could come through.

Thank you.

**Comment by leastprivilege** [comment]
I can see the problem.

JToken will probably not work because of the internalization.

I guess I never designed it for such complex data - so I never tested with POCOs. Are you sure you want to return complex data here? The spec seems to never go beyond additional string key/value pairs.

I don't have the time right now to investigate - could you send a PR?

**Comment by bradacina** [comment]
Unfortunately I do have to return a POCO here. I'll look at putting together a PR.

What are your thoughts on the following solution:
I'm thinking of taking the TokenResponseDto that gets created at the top of TokenResult.Execute() and dumping its properties into a ExpandoObject or a Dictionary<string,object>, add in any <Key,Values> from the Custom dictionary, and using JsonConvert.SerializeObject() on the newly created ExpandoObject/Dictionary. This way we bypass the enitre JObject/JProperty/JToken conundrum.

**Comment by leastprivilege** [comment]
would that work for you?

https://github.com/IdentityServer/IdentityServer3/commit/dccd094e2a63961429781dabc429dfb55023f6b5

**Comment by bradacina** [comment]
It does work indeed. Well distilled. Much better than my convoluted idea. Thank you very much Dominick.
