### ISSUE TITLE
Can we use basicHttpBinding for  WCF authentication instead of WS2007FederationBinding ?

### ISSUE THREAD

**Issue by pagidi** [IdentityServer/IdentityServer3#3142]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question 
Hi Brockallen,

Can we use basicHttpBinding and nettcp binding for  WCF authentication instead of WS2007FederationBinding?

Sample suggests only ws2007FederationBinding, but I want to do for existing service which are using basicHttpBinding, is it possilbe?
otherwise there is lot of proxy changes required if I go with wsFederationbinding.

Can you suggest?

**Comment by leastprivilege** [comment]
wrong repo.
