### ISSUE TITLE
Single Logout IdentityServer3

### ISSUE THREAD

**Issue by tiwari-abhishek** [IdentityServer/IdentityServer3#3143]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have 2 ASP.NET MVC applications and I am using the OpenID middleware **UseOpenIdConnectAuthentication** to do the single sign on to both. Configuration is described as below. SSO works great. I login from application 1 and then I check if I am logged into application 2 too that connects to idserver, I can see myself logged in. Both the client applications now have the same id_token and token.

           app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "oidc",
                SignInAsAuthenticationType = "Cookie",
                Authority = "<my-idserver-url>",
                ClientId = "client1",
                RedirectUri = "https://localhost:44360",
                PostLogoutRedirectUri = "https://localhost:44360",                
                ResponseType = "id_token token",

               //scopes from config file
                Scope = ConfigurationManager.AppSettings.Get("Scope"),
                
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = n =>
                    {
                        var claims = n.AuthenticationTicket.Identity.Claims;
                        var accepted_claims = new[]{"name", "tenant", "email", "sub"};
                        var new_claims = claims.Where(x => accepted_claims.Contains(x.Type)).ToList();

                        new_claims.Add(new Claim("id_token", n.ProtocolMessage.IdToken));
                        new_claims.Add(new Claim("access_token", n.ProtocolMessage.AccessToken));

                        var ci = new ClaimsIdentity(new_claims, n.AuthenticationTicket.Identity.AuthenticationType, "email", "role");
                        n.AuthenticationTicket = new AuthenticationTicket(ci, n.AuthenticationTicket.Properties);

                        return Task.FromResult(0);
                    }

On clicking logout in the app, when the RedirectToIdentityProvider method is invoked in the clients, I am setting the id_token as the IdTokenHint as below:

            RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnectRequestType.LogoutRequest)
                        {
                            var user = n.OwinContext.Authentication.User;
                            if (user != null && user.Identity.IsAuthenticated)
                            {
                                var id_token_claim = user.Claims.FirstOrDefault(x => x.Type == "id_token");
                                if (id_token_claim != null)
                                {
                                    n.ProtocolMessage.IdTokenHint = id_token_claim.Value;
                                }
                            }
                        }
                        return Task.FromResult(0);
                    }

Problem area > Single Logout:
**Success Scenario:**
When I logout from the application 1, it redirects to idserver and logs me out and redirects me back to application 1.  On debugging I can see that the signout message in the logout method of the DefaultViewService is not null in this case. This works great.

**Failure Scenario:**
The problem is when I try to logout from application 2 instead of application 1(remember that I logged in from application 1), it does take me to the logout page at idserver, and I can logout. But it does not redirect back to the application 2 and stays on the idserver logged out page. On debugging I can see that the signout message in the logout method of the DefaultViewService is null in this case. 

Is it probably because the id_token was originally issued to the application1?

What am I missing?
Do I need to handle this kind of scenario and somehow get hold of the client in identity server, that the user used, to actually logout(application 2)? and then probably issue a new SignoutMessage and put in the postlogout redirect Url for that client?

Or I got it all wrong and this should work automatically?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by tiwari-abhishek** [comment]
**Update:** A blunder was to try this out with everything on IISExpress localhost on different ports, both clients(localhost on different ports) somehow get the same id_token and access token which shouldn't happen.

Moving out to the IIS hosting different sites(different domains even) solved this and now the applications can get their own individual id_token and access token.

I am still working on the Single Logout, exploring the iFrame approach.

**Question**
Is there a way to get a list of all the applications that a user had logged into using the identity server? I can attempt to possibly inject this information into the iFrame to avoid a static list of application cleanup urls?

**Comment by leastprivilege** [comment]
new question - new issue.
