### ISSUE TITLE
Resolve client name from request header

### ISSUE THREAD

**Issue by MaxamillionMax** [IdentityServer/IdentityServer3#3144]
Is there a way to request a connect/authorize, without client_id, instead, is it possible to use the request header (e.g. Hostname) to lookup the client_id server side?

`
https://localhost:44300/connect/authorize?client_id=consumer_name&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fpopup.html&response_type=id_token%20token&scope=openid%20profile%20tenant%20api%20email%20roles&state=a174193707684cb69201eefc2cf08800&nonce=b99d1123b7424de9bc42bf033553cdcd&display=popup
`

Thanks

**Comment by brockallen** [comment]
We implement what the spec allows.

**Comment by MaxamillionMax** [comment]
Thanks.
Am I able to override the "Authorize"? so that this enables me to get around the authorize spec requirement with a hard-coded "consumer" as client_id and also allows me to resolve the *actual* client id with other values in the request (e.g. hostname).

**Comment by brockallen** [comment]
An easier approach would be to implement middleware in front of IdSvr that adds the correct client_id query string param with the value you need/want for the authorization requests.

**Comment by MaxamillionMax** [comment]
Thanks!
That would work well, the only bad thing is that it will add another round trip to the server.  :(

**Comment by brockallen** [comment]
No -- you simply read the host (or whatever your value is) and then add the query string to the incoming request.

**Comment by MaxamillionMax** [comment]
Yes, that would require the app to go to a custom middleware endpoint first to capture the hostname and then redirect to the identity server endpoint with the correct query string?

**Comment by brockallen** [comment]
No, something like this (and the API names are not all correct here):

```
app.Use(async (ctx, next)=>{
   ctx.Request.Query.Add("client_id", "whatever");
   await next();
});
app.UseIdSvr(...);
```

**Comment by MaxamillionMax** [comment]
Ok, i see. I really appreciate for the advise, that will do the trick :)
