### ISSUE TITLE
Get Domain name 

### ISSUE THREAD

**Issue by nkdev89** [IdentityServer/IdentityServer3#3145]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I'm using Active directory authentication . How do i  know the calling client domain name to authenticate user credentials in IUserService 
 
as of now i'm hard coding domain name like below

new PrincipalContext(ContextType.Domain, "XXXX")

i tried HttpContext but no luck .

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
I don't understand. Please elaborate.

**Comment by nkdev89** [comment]
i work in a organization which has companies all over the world , Each country will have specific domain for logging into their PC . For example  for India we have domain IND and for US we have NYC . These are the domain name used for logging in the system in their respective region . Now i'm writing a identity server which uses user Service with Active Directory . 

This service will be running in US , and when i try to authenticate my user name and password. Its uses IND as Domain . When user from US uses to login they need to use NYC. 

So the Domain varies from user region to region . Now my question is there any way to detect the domain and authenticate ? 

The name of the domain or server for System.DirectoryServices.AccountManagement.ContextType.Domain.context types

**Comment by brockallen** [comment]
You need to ask the user then. Asking your OS won't help know where the user is from.

**Comment by nkdev89** [comment]
ok let me try or i will come up with solution for this
