### ISSUE TITLE
custom workflow from values passed by client

### ISSUE THREAD

**Issue by matt-iosh** [IdentityServer/IdentityServer3#3147]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I'm trying to enable custom workflow to be triggered as part of the ~/connect/authorize endpoint. I have added custom values to the acr_values parameter as a way of a client application being able to trigger these workflows.

I assumed the best place to put this would be in the PreAuthenticateAsync() method, however this is only called on login, not every time the authorize endpoint is called. i have noticed that the IsActiveAsync() method is called when authenticated but this doesnt make the acr_values passed accessible in the user service as far as i can see

i guess my question is 2 fold:

1. Is it possible to get the acr_values from the IsActiveAsync() method?
2. If not, what alternatives are there to initiate a custom workflow from a client even when authenticated?
3. Is it possible to customise the consent workflow to add additional workflow steps here?

**Comment by brockallen** [comment]
acr_values are only passed at authorization time. IsActive is called from other contexts.

The custom request validator extensibility point might be something for you to look into. It's called from the authorization endpoint. But we never designed it to allow for custom UI or UI workflows.
