### ISSUE TITLE
Identity with Dapper, or raw Ado.Net

### ISSUE THREAD

**Issue by GArrigotti** [IdentityServer/IdentityServer3#3149]
Question:

Will a version of Identity ever be implemented or forked without Entity Framework?  Where it can be implemented without Entity Framework but can be implemented with an ORM or raw ADO of our choosing?

**Comment by leastprivilege** [comment]
You don't need to fork anything - these are all extensibility points. 

You just need to implement `IScopeStore`, `IClientStore` etc with your favourite data access technology.

**Comment by ranga543** [comment]
[Click Here](https://github.com/ranga543/IdentityServer3.Dapper) to see Dapper extension for IdentityServer3 without EF and this is reference implementation of IdentityServer3.EntityFramework
