### ISSUE TITLE
Documentation Overview TODO:

### ISSUE THREAD

**Issue by allangagnon** [IdentityServer/IdentityServer3#3150]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am looking at the documentation at the following link:
https://identityserver.github.io/Documentation/docsv2/overview/jsGettingStarted.html
 
In the page there is a TODO: link to final code when in the Samples repo.

Is there a final code link in the Samples repo?

Can the documentation please be updated?

Thank & Regards
Allan F. Gagnon

**Comment by leastprivilege** [comment]
@mderriey Where's the source code?

**Comment by mderriey** [comment]
[Here](https://github.com/mderriey/idsrv-js-walkthrough/tree/dev?files=1). I initially thought that code would be integrated in the official Samples repo. Sorry about that.

**Comment by leastprivilege** [comment]
ok - thanks!

we'll update with the new walkthrough and source anyways soon I guess

**Comment by allangagnon** [comment]
Thank you very much for your time!!

**Comment by brockallen** [comment]
@mderriey we can add the code from that repo to the samples repo here -- any objections?

**Comment by mderriey** [comment]
not at all, feel free to copy the code from [the original repo](https://github.com/mderriey/IdentityServer.JsWalkthrough), put it where you think is best and update the docs :+1:

**Comment by brockallen** [comment]
ok, done. thanks.
