### ISSUE TITLE
Sliding Expiration Not working Properly

### ISSUE THREAD

**Issue by Sriram143** [IdentityServer/IdentityServer3#3151]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

How to Renew idsrv cookie. 

Application Setup in IdServer Local Login and Several Hybrid clients 

Default timeout is 20 min.

after successful login at idserver the user is getting the token and remaining process is normal.

i am setting the sliding expiration in idserver and the hybrid clients and i am using the same cookie expiration timeout in idserver  cookie options and client settings and the enabled sliding expiration in hybrid clients.

but after 20min the cookie is automatically expired and redirecting to login screen.  eventhough the user is using application.

i observed the "SubjectId": "unknown", 

Is there any setting i am missing?

### Relevant parts of the log file

```
{
  "ClientId": "test",
  "ClientName": "test",
  "RedirectUri": "https://xxxxxxx/xxxxxxl/",
  "AllowedRedirectUris": [
    "https://xxxxxxx/xxxxxxl/"
  ],
  "SubjectId": "unknown",
  "ResponseType": "code id_token",
  "ResponseMode": "form_post",
  "Flow": "Hybrid",
  "RequestedScopes": "openid test",
  "State": "OpenIdConnect.AuthenticationProperties=zjKJdyk8mHWYcaw7iln7dnsBPK3LFJIvm7boPt6rmrHkRL2NE6_PwPDu7GxfADPg2G3Gc_n0yUKwYhC_SehROHvcLo3_QFfFrXpgv7PQlI9MMx3WaChXPcQDYGI8RcZLjWkul2NVpgwvYGamjwIzH8EwW8-OhIP13Cw6JDpQCTLWxJKXNc6hSF49Q5hKgWJaM3F3J1KO4T99sMapdsMWvIdznvwe8u9zbWSJsgrwUHZUOFIfVhJnOGOKNfFGHfli0xcl9EXKGy8_qQrcm9YfqQ",
  "Nonce": "636072031911585380.N2U0ZDYyYWEtNWRjZC00Y2FjLTlmMDAtMjE1OTZkY2EyOTk2Njc3MWFiZjMtZjZlNS00Zjg0LTk3ZjctZTIwMGVlMGE0MzE5",
  "Raw": {
    "client_id": "test",
    "redirect_uri": "https://xxxxxxx/xxxxxxl/",
    "response_mode": "form_post",
    "response_type": "code id_token",
    "scope": "openid",
    "state": "OpenIdConnect.AuthenticationProperties=zjKJdyk8mHWYcaw7iln7dnsBPK3LFJIvm7boPt6rmrHkRL2NE6_PwPDu7GxfADPg2G3Gc_n0yUKwYhC_SehROHvcLo3_QFfFrXpgv7PQlI9MMx3WaChXPcQDYGI8RcZLjWkul2NVpgwvYGamjwIzH8EwW8-OhIP13Cw6JDpQCTLWxJKXNc6hSF49Q5hKgWJaM3F3J1KO4T99sMapdsMWvIdznvwe8u9zbWSJsgrwUHZUOFIfVhJnOGOKNfFGHfli0xcl9EXKGy8_qQrcm9YfqQ",
    "nonce": "636072031911585380.N2U0ZDYyYWEtNWRjZC00Y2FjLTlmMDAtMjE1OTZkY2EyOTk2Njc3MWFiZjMtZjZlNS00Zjg0LTk3ZjctZTIwMGVlMGE0MzE5"
  }
}
```

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
