### ISSUE TITLE
Current claims available in EventService implementation

### ISSUE THREAD

**Issue by garfieldos** [IdentityServer/IdentityServer3#3153]
- [x] I read and understand how to handle Events 
(http://identityserver.github.io/Documentation/docsv2/configuration/events.html)

### Question
I registered a EventService in this way:

``` C#
_factory = new IdentityServerServiceFactory();
_factory.EventService = new Registration<IEventService, EventService>();
```

Now after handling a Refresh Token event, i need to refresh some external system session. To refresh external session I need a current external session id, that is provided in user Claims. Is there any way to inject this 'current' claims to the EventService?

**Comment by garfieldos** [comment]
I created additional parameter in RefreshTokenRefreshDetails: Claims, that is enough in my case.

**Comment by leastprivilege** [comment]
still an issue?

**Comment by garfieldos** [comment]
I implement some change in RaiseSuccessfulRefreshTokenRefreshEventAsync method, that will pass claims to the raised event.
 There is pull request for this change: https://github.com/IdentityServer/IdentityServer3/pull/3187/files
