### ISSUE TITLE
Custom flow for act-as tokens

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3#3154]
As discussed in https://github.com/IdentityServer/IdentityServer3.Samples/issues/182, I'm wondering how to address the issue of an API (1) calling another API (2) with a custom grant client passing original access token in cases where API 1 really gets a request from a client with client credentials flow and therefore has no subject in the token. Passing that token to a custom grant validator will not work.

- Should API 1 know or care about the type of client calling it? I would say 'no'.
- Should custom grant validator inspect the token to see if there is a subject and react somehow if not?

Any other suggestions?

**Comment by brockallen** [comment]
Sounds like the design is a bit off.. if API2 needs a subject, but the original client doesn't have a subject then why is API2 ever really getting called? Perhaps a trusted subsystem design makes more sense since the original client doesn't have a user.

**Comment by snothub** [comment]
The issue here is that API 1 might get requests from different clients, some with subject, some with client credentials only. API 2 requires a different scope from API 1 and I'd like to handle that regardless of what tokens come in to API 1 to begin with.

**Comment by brockallen** [comment]
This is a classic problem. Some APIs are called on behalf of the user, some are not. The API needs some way to know how to know the user for the operation. If the client is trusted, then allow the user as a param. If the client is not trusted, then require the user in the access token.
