### ISSUE TITLE
Renew  access token from refresh token

### ISSUE THREAD

**Issue by LaurenceSkoropinski** [IdentityServer/IdentityServer3#3155]
we have a refresh token, and we need to get a new access token, google searchers suggest using TokenClient with url set to token_endpoint passing also clientid, clientsecret. Then use the RequestRefreshTokenAsync method passing the refresh token. This does return an access token, but I was expecting the refresh token to be returned unchanged, unfortunately it returns a new Refresh token. Is this to be expected, or is there another way to keep the refresh token unchanged(if not expired) and get a new access token from the refresh token. Have googled but have not found anything of value.

**Comment by leastprivilege** [comment]
There's a refresh token usage property on the client class (re-use vs one-time only) that control this behavior.

**Comment by garfieldos** [comment]
You need to set  Client.RefreshTokenUsage  to value TokenUsage.ReUse to achieve this goal.

```
   var client= new Client()
            {
                ClientId = "client_id",
                ClientSecrets = new List<Secret>
                {
                    new Secret("not_a_secret".Sha256(), "not_a_secret")
                },
                RefreshTokenUsage = TokenUsage.ReUse
                ...
            }
```

**Comment by LaurenceSkoropinski** [comment]
Thanks guys, that worked.
