### ISSUE TITLE
Windows Auth with no login page and uses active directory , no WFS

### ISSUE THREAD

**Issue by wlafrance** [IdentityServer/IdentityServer3#3159]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

What sample illustrates using windows active directory with IdentityServer3 that does not require a AD FS /  WSFederation?  Basically, the user goes to a URL inside a corporate domain and they are logged in since they are already logged into a machine authenticated on the domain...  

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
what's WFS?

**Comment by wlafrance** [comment]
Sorry,  we do not have a AD FS /  WSFederation server.  We connect via LDAP right now...

**Comment by leastprivilege** [comment]
e.g.

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/WebHost%20(Windows%20Auth%20All-in-One)

**Comment by totpero** [comment]
i use this: https://github.com/PCFDev/Owin.Security.ActiveDirectoryLDAP with AD and login using username and password from web.
