### ISSUE TITLE
Integration IDP3 with existing local identity

### ISSUE THREAD

**Issue by phoenixjun** [IdentityServer/IdentityServer3#3160]
we have an existing application and we store the user information in some existing tables. The business need to expose some RESTful interface to public. We are thinking to use IdentityServer3 to perform authentication/authorization. However, it is not easy to get rid of the existing user tables and the security stuff. So we are thinking if there is any interface that we can implement so that the Identityserver3 can talk to the existing user table to perform authentication.

Any comment or example will be helpful for us.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
