### ISSUE TITLE
ScopeSecretValidator when using reference token

### ISSUE THREAD

**Issue by yusbel** [IdentityServer/IdentityServer3#3162]
After receiving the access token (reference access token) my api middleware make a call to the instropection end point to get the jwt token. Unfortunate I'm getting a json response with an error message unauthortize.

2016-08-24 13:33:39.505 -04:00 [Debug] Start scope validation
2016-08-24 13:33:39.505 -04:00 [Debug] Start parsing Basic Authentication secret
2016-08-24 13:33:39.505 -04:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
2016-08-24 13:33:39.505 -04:00 [Information] Secret id found: "webapp123.hybric.flow"
2016-08-24 13:33:39.507 -04:00 [Information] No scope with that name found. aborting
2016-08-24 13:33:39.507 -04:00 [Warning] Scope unauthorized to call introspection endpoint. aborting.

look like we are searching for the scopes requested by the client application using the client application id passed to the instropection endpoint. 
Question: 

Is his correct?
Can the Id3 remember the scopes requested by the client?
Can I call the instrospection endpint using the api ClientId? - I don;t want to use the client id of the client application that requested the reference token.

Code bellow:
            // load scope
            var scope = (await _scopes.FindScopesAsync(new[] { parsedSecret.Id })).FirstOrDefault();
            if (scope == null)
            {
                await RaiseFailureEvent(parsedSecret.Id, "Unknown scope");

                Logger.Info("No scope with that name found. aborting");
                return fail;
            }

**Comment by akshetty9** [comment]
Introspection endpoint is for validation of token and not to get Jwt.  To call Introspection end point you need to pass "Scope" and "Scope secret" in the request for authentication not client id 

https://identityserver.github.io/Documentation/docsv2/endpoints/introspection.html

**Comment by yusbel** [comment]
I'm want to get the claims of the reference token from a backend api. I think the introspection end point will dereference the token.
 
http://stackoverflow.com/questions/37419951/how-to-get-claims-from-server-on-every-request-with-reference-token

**Comment by akshetty9** [comment]
If you send the reference token to instrospection endpoint with valid scope name and secret you will get the claims in the response.

public async Task ValidateValidReferenceTokenUsingIntrospectionEndPoint()
        {
            var tokenResponse = await GetTokenResponseForClientCredentialsFlow(IdsModel.AccessTokenType.Reference);

            var introspectionClient = new IntrospectionClient(
               IntrospectionEndpoint,
               "Api1",  // scope name, scope secret
               "Api1Secret");

            var response = await introspectionClient.SendAsync(new IntrospectionRequest
            {
                Token = tokenResponse.AccessToken
            });

            var jsonResult = JsonConvert.DeserializeObject<Dictionary<string, object>>(response.Raw);

            response.IsActive.Should().Be(true);
            response.IsError.Should().Be(false);

            jsonResult.Count().Should().Be(7);
            jsonResult.Should().Contain("iss", ValidIssuer);
            jsonResult.Should().Contain("aud", ValidAudience);
            jsonResult.Should().Contain("client_id", "referenceTokenClient");
            jsonResult.Should().Contain("active", true);
        }

**Comment by akshetty9** [comment]
If you send the reference token to introspection endpoint with valid scope name and secret you will get the claims in the response. You need to have the claims defined for the client on IDS
```

    public async Task ValidateValidReferenceTokenUsingIntrospectionEndPoint()
            {
                var tokenResponse = await GetTokenResponseForClientCredentialsFlow(IdsModel.AccessTokenType.Reference);
    
                var introspectionClient = new IntrospectionClient(
                   IntrospectionEndpoint,
                   "Api1",  // scope name, scope secret
                   "Api1Secret");
    
                var response = await introspectionClient.SendAsync(new IntrospectionRequest
                {
                    Token = tokenResponse.AccessToken
                });
    
                var jsonResult = JsonConvert.DeserializeObject<Dictionary<string, object>>(response.Raw);
    
                response.IsActive.Should().Be(true);
                response.IsError.Should().Be(false);
    
                jsonResult.Should().Contain("iss", ValidIssuer);
                jsonResult.Should().Contain("aud", ValidAudience);
                jsonResult.Should().Contain("client_id", "referenceTokenClient");
                jsonResult.Should().Contain("active", true);
               jsonResult.Should().Contain("client_claim1", "claim1value");
            }
```

**Comment by brockallen** [comment]
All set on this issue?
