### ISSUE TITLE
Cookie for a JWT Using Implicit Flow? 

### ISSUE THREAD

**Issue by acalbazana** [IdentityServer/IdentityServer3#3164]
Hello,

I have a situation where I'd like to exchange a cookie (issued from an SSO provider) for a JWT (issued by IdentityServer3) from a browser based (Angular) client.  

Originally, I was considering a custom grant type, but this seems to require client credentials which doesn't buy me anything.  An implicit grant flow seems to make more sense for this client.

Is there a way to bypass the IdentityServer's login screen using the implicit grant type so that I can just hit the UserService to perform validation against the incoming cookie and have it authenticate a user?  Ultimately, I'd like to have IdentityServer send a new token to my redirect_url.

I've tried overriding the PreAuthenticateAsync from UserService, but I'm not clear how to authenticate a user  to satisfy the flow.  Setting a new AuthenticateResult with a subject and name doesn't get me anywhere.

Is there another approach that I should be looking at here?  Any guidance would be greatly appreciated!

Thanks,

Alejandro

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by acalbazana** [comment]
Hi,

Thanks for the heads up.  Did this particular question move to SO, or
should I post it over there?

Alejandro

**Comment by brockallen** [comment]
You would have to ask it again on SO.
