### ISSUE TITLE
database schema issue

### ISSUE THREAD

**Issue by woodl3y** [IdentityServer/IdentityServer3#3166]
We have an application with a SQL database, and we're now planning to use IdentityServer3.  We want IdentityServer3 to use its own separate schema within the existing application database.
I have created a new SQL login, and a new schema (called "identity"), and assigned the new login as the owner of the schema, and also set the user's default schema to "identity".

Here's the IdentityServer3 setup:

```
var efConfig = new EntityFrameworkServiceOptions
	{
		ConnectionString = ConfigurationManager.ConnectionStrings["IdentityServer"].ToString(),
		Schema = "identity"
	};

factory.RegisterConfigurationServices(efConfig);
factory.RegisterOperationalServices(efConfig);
options.Factory = factory.UseInMemoryScopes(Scopes.Get())
                .UseInMemoryUsers(new List<InMemoryUser>())
                .UseInMemoryClients(Clients.Get());

app.UseIdentityServer(options);
```

I'm seeing the following exception in my logs, it seems IdentityServer3 is still trying to use the 'dbo' schema.

```
System.Data.SqlClient.SqlException (0x80131904): The specified schema name "dbo" either does not exist or you do not have permission to use it.
```

What have I missed ?  Any help would be appreciated

Thanks!

**Comment by brockallen** [comment]
This issue should be in the EF repo, not here. Please open a new issue there. Thanks.
