### ISSUE TITLE
Q: Access token type flexibility

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3#3169]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Access token type is per client. 
I have a situation, where one client should get one access token for API 1 and another for API 2. API 1 & 2 are different, on different servers, with different requirements etc. Different scopes within the access token are used by the APIs to grant/deny resource access. 
The problem is - API 1 accepts only reference tokens, and API 2 only JWT.

Short of defining two clients (to represent the same application), is there a way to handle this situation? 
Any way for the client to explicitly request one access token type or another?

**Comment by brockallen** [comment]
You'd need two different client configurations.
