### ISSUE TITLE
Q: How about multi-tenancy

### ISSUE THREAD

**Issue by marcelov2** [IdentityServer/IdentityServer3#3172]
### Question / Issue
I wonder if there is a sample or working implementation of using IdentityServer in a
multi-tenant application. I'm trying to build a multi-tenant application where the 
authentication and user management is done by an application implementing 
IdentityServer and another application (the client) authenticates against the first one.
The idea is to grab the tenant name from the URL as in http://tenant_a.acme.com and
using the tenant name (tenant_a in this case) to calculate the tenant database to use. This
calculated database will be used by the IdentityServer (to store user information and
credentials) and by the client application to save it's data.

I already have a working implementation of the above scenario, so I like to know if I am
in the right path or in a recommended path or at least, in a not too disastrous path.

Thanks.

**Comment by Peperud** [comment]
[https://github.com/IdentityServer/IdentityServer3/issues/2173]

**Comment by apideveloper** [comment]
I'll be looking into this during the week and let you know. As the other issue pointed out, this can be done via database switching. I'm looking to solve this using the same database but different application identifiers.

**Comment by marcelov2** [comment]
Thanks for the answers, I'm switching databases as stated in the other issue and seems to be working well and this is the path I prefer, as the rest of the code does not requires to know that it is in a multi-tenant environment.
