### ISSUE TITLE
Native Mobile App, Which flow

### ISSUE THREAD

**Issue by JLarue** [IdentityServer/IdentityServer3#3176]
I am helping with a design utilizing IdentityServer (IS3) that will become the STS for a new Xamarin client. 
The Dev team is pushing hard to accept the user credentials on the app, which are then passed into the IS3.  Is that possible and recommended or not?  I was recommending Implicit Grant flow but am hoping someone can shed some light on why the Dev Teams wishes can't be easily and safely met within IS3 some how?  If not explain why not.

**Comment by leastprivilege** [comment]
The dev team is wrong. In short hybrid flow with PKCE - more details here:

https://tools.ietf.org/html/draft-ietf-oauth-native-apps-03
and
https://vimeo.com/171942749

**Comment by JLarue** [comment]
Thank you for taking the time to help further educate.
