### ISSUE TITLE
Question / Partial login with bearer tokens

### ISSUE THREAD

**Issue by dmoughabghab** [IdentityServer/IdentityServer3#3179]
Question

Hey guys so basically what I was hoping to do was have a external partial login (facebook) redirect back to the app (cordova angular2) register page and then completing the registration from the app

So to elaborate
1 user opens app on phone to the login page and presses the login with facebook button 
2 new window opens and logs in with facebook identity server detects that this is a new user and passes back somesort of token so on the register api call it can remember the partial login (usually adds cookies for the partial login which would be fine except instead of redirecting I am using a popup)
3 user finishes registration on the app and finishes login

The only problem I am having is I'm not sure how to pass the partial login back to the angular2 cordova app for the register api call from the popup (InAppBrowser in Cordova jargon)

Anyway I'm new to adding questions on git hub, sorry if I did it wrong and thanks so much for your time!

**Comment by brockallen** [comment]
Why don't you do this registration in IdSvr itself? In any event, this is more of a question for stackoverflow.
