### ISSUE TITLE
How to get access token in Angular on same trip to IdentityServer - MVC, WebApi with Angular

### ISSUE THREAD

**Issue by devmoviit** [IdentityServer/IdentityServer3#3181]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

Hello experts,

### My Layout

**IdentityServer project:**
    - MVC client (**Implicit** workflow)
    - API client (**Client Credentials** workflow)

**WebApi project:**
    - Business logic and DB access
    - Requesting only an "api" scope

**MVC project:**
    - Requesting "openid profile roles api" scopes
    - Requesting "id_token token"
    - Angular app accessing secure API (currently access token is not added to header)

### What I'm doing
My MVC is getting secured correctly and ResourceAuthorize() works as expected.
I'm currently in the process of making my Angular app adding the bearer token to our API calls.

### My doubts
When accessing the MVC, the user is redirected to the IdSrv, gets logged in, then redirected back to MVC.
At this point, my Angular app gets loaded for the first time, and obviously I don't have or need the username and password.
The access token has already been issued, but I can't get my head around how/when to provide it to the Angular app.

### My Ideas
1. Inject it to my layout page using razor.
2. Switch MVC to authorization code workflow and make a second trip to IdServ requesting an access token [hmm but wait... how do I get the authorization code into angular? I guess I stayed with the same issue..??]
3. Make Angular use client credentials as well

Please point me in the right direction.
I can't seem to find which of the samples does something similar to what I need.

Thanks in advance,
Shy.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by kpstolk** [comment]
[Link to SO question](https://stackoverflow.com/questions/39278027/how-to-get-access-token-in-angular-on-same-trip-to-identityserver-mvc-webapi).
