### ISSUE TITLE
Thinking out of the box:  Perhaps using IdentityServer to function as a payment server

### ISSUE THREAD

**Issue by markchipman** [IdentityServer/IdentityServer3#3183]
Hi all: I got thinking about the parallel requirements and features that IdentityServer provides to what a payment server would require.

Use case:  you allow your customers to pay with either credit card, pre-paid debit accounts or purchase orders... but you don't want your website to deal with the payment processing at all... instead for all these cases you want transparent out-of-scope solution that can be reused for many websites.  

To accomplish this, consider how oAuth2/OpenID  flows work... a one-time token to be issued to the purchaser to that they redeem (ie akin to getting an bearer token) as the acceptance of the terms of payment (ie $100 was charged/credited to/against their credit card/debit balance or pre-authorized purchase order spending limit on file).  The tokens would be very time limited in nature (ie good for 5 minutes max). Once the payment server received the terms of payment confirmation (token) at a specified endpoint, the transaction is then performed and the purchaser would be redirected to the callback page the would show a receipt or error message if the transaction failed.

This environment would be very useful for reasons of not having the payment details (ie credit card numbers or account payment details for PO's/debit balances) be handled by the client-side system and additionally all of this would be centralized into one payment provider.  This would allow a secure way to pay for things without having to give your payment details to and particular website or webservice.   I think this could be something similar to how PayPal operates.

Anybody else see any possibilities here?  Does this sound like something that IdentityServer could be leveraged into possibly as a separate kind of project?

**Comment by leastprivilege** [comment]
While these protocols seem similar - you would be overloading some of the mechanisms.

I am not saying this cannot be done - but IdentityServer has a different focus and there are no plans to extend it beyond a pure protocol implementation of OIDC and OAuth.

I think payment and authentication are two distinct things - and you are better off with two services that focus on each of the specialities.
