### ISSUE TITLE
Claims are not returned by user info end point

### ISSUE THREAD

**Issue by naveenkumarreddy** [IdentityServer/IdentityServer3#3186]
Hi,

I am using Authorization Code flow and I am trying to get the user information using user info endpoint, but I am not getting claims. I've enabled IncludeInIdToken for some claims like name profile email and when decode Idtoken I was not able to see the above claims. 
I've tried by debugging the method GetProfileDataAsync, here I found the "Name" property coming null, since I am using the AD group I need this Name property here.

When I request for tokens by using code I am able to see the following result in Claims

![c1](https://cloud.githubusercontent.com/assets/6703476/18204279/8ce780d2-7139-11e6-8521-71587d7ca019.PNG)

and I am not able to see those claims in IdToken,

![c2](https://cloud.githubusercontent.com/assets/6703476/18204385/23ae6abc-713a-11e6-89b6-6809e5d53724.PNG)

Next, time when request using user info endpoint by using access token I am not getting any Claim except "sub" or no Name property.
![c3](https://cloud.githubusercontent.com/assets/6703476/18204453/7ff1ca30-713a-11e6-90bf-3fd25b43efbf.PNG)
![c4](https://cloud.githubusercontent.com/assets/6703476/18204479/acd59f5e-713a-11e6-91f0-39be1cef6842.PNG)

Please let me how can I get Name property when I use user info endpoint.
Thanks in advance

**Comment by naveenkumarreddy** [comment]
Hi Brock Allen,

 any update on this,
Some more information I am using CustomUserService

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
