### ISSUE TITLE
Idea: Allow for wildcard redirect, and logout uris

### ISSUE THREAD

**Issue by runes83** [IdentityServer/IdentityServer3#3188]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
Make it possible to add wildcard uris for logout and redirect for example: https://www.mydomain.com/* or https://*.mydomain.com.

This would make it simpler to offer services based on identityserver to 3 parties.

**Comment by leastprivilege** [comment]
You can implement your own redirect URI validation by implementing`IRedirectValidator`- but you've been warned ;)
