### ISSUE TITLE
Adding IdentityServer v3 as a claims provider for ADFS 3.0

### ISSUE THREAD

**Issue by sajanep** [IdentityServer/IdentityServer3#3193]
Hello Everyone,
I am kind of evaluating Identity Server as a custom STS provider for ADFS. Before that, let me list down my problem statement. 
1) In our enterprise internal users are persisted in AD and external users are in AD LDS. We are based on Windows 2012R2 server.
2) Right now the SSO implementation is based on classic Forms authentication by sharing machine keys across web applications(in each web.config). We are thinking about claims based authentication using ADFS.
As everyone knows ADFS does not provide a way to get credentials from AD LDS, we need to go for a custom STS and I found thinktecture as a popular solution. So my high level solution could be

1) Use ADFS to authenticate against AD.
2) Use idsrv3 to authenticate against AD LDS.
3) Then federate ADFS and idsrv3. This can be achieved by adding Idrsv3 as a claims provider for ADFS.
4) Application is a RP on ADFS.

So I have below questions
1) Is it possible to achieve what I am looking for with Identity Server 3?
2) I read about custom user service. I assume I need to write one for authenticate against AD LDS and overriding UserServiceBase like https://gist.github.com/devscott/9f4ece55eaf916c9c265 will do the job. In order for that do I need to embed Identity Server in a separate application or is it possible to use standalone version of Identity Server with my customization?
3) Hope my end user will get only standard ADFS login page and not the login page of Identity Server v3. Please correct me if I am wrong.

**Comment by brockallen** [comment]
1. yes
2. the user service can validate credentials and if LDS is the backend, then that's what you use.
3. yes, but you need to solve the HRD problem, and that requires architecture/design that depends on your scenario.

**Comment by sajanep** [comment]
Hello Brock,
Thanks for replying. Could you please answer the second part of my second question which is do I need to embed the identity server in another application or can use it standalone. Is it mandatory to embed the identity server in a custom application for any kind of customization? Could you please also explain what is the HRD(Home Realm Discovery)  problem here. Are you saying whenever user select the claims provider for AD LDS in standard ADFS page, he/she will get redirected to Identity server login page?

**Comment by brockallen** [comment]
IdentityServer is just a Katana middleware, so you can host it anywhere you can host Katana.
