### ISSUE TITLE
Expose a setting to set CorsPolicy.SupportsCredentials

### ISSUE THREAD

**Issue by dennisfrostlander** [IdentityServer/IdentityServer3#3195]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Could you please add a setting to control CorsPolicy.SupportsCredentials in the CorsPolicyProvider? 
I need to use a cross-domain fetch request to send the authentication cookie for access token renewal scenarios, and it wouldn't do so if you don't properly configure Access-Control-Allow-Credentials and allowed origins.

P.S. I am aware of oidc-client and its renewal scenarios, but I need to do it using other existing components.

**Comment by brockallen** [comment]
Can you elaborate what integrated credentials you're using to the IdentityServer endpoints? I'm curious...

**Comment by dennisfrostlander** [comment]
Sure, the setup is a combination of resource owner flow for getting the initial access token and subsequent access token renewal. The client is javascript, but resource owner is still preferred (identity server, login page and resources are owned by the same team, ssl is enforced, whitelisting is used for cors, etc). After the initial access token is obtained it is used to get hold of idsrv authentication cookie with sliding expiration which is then used to renew the access token every once in a while.

**Comment by brockallen** [comment]
How is the CORS credentials flag involved? Are you saying you need it for a cookie that you're expecting to be sent to the token endpoint?

**Comment by dennisfrostlander** [comment]
No, it's actually for the authentication cookie to be received when making a cross domain ajax request to get the cookie based on access token. If you don't set Access-Control-Allow-Credentials='true' on the server and send back Set-Cookie headers, they will (should) just be ignored by the browser.

**Comment by dennisfrostlander** [comment]
Or to be more correct, they will be ignored if you're making ajax request without credentials. And in order to send ajax request with credentials, you need Access-Control-Allow-Credentials on the server.

**Comment by brockallen** [comment]
Not sure if we want to do this. But in the meantime you can always put your own middleware in front and issue this header when you need to.

**Comment by dennisfrostlander** [comment]
Sure, no worries. Maybe some other time when you touch cors settings. A new middleware is exactly what I did for now.
