### ISSUE TITLE
AuthenticationOptions.EnablePostSignOutAutoRedirect logout.html and loggedOut.html themes toggle

### ISSUE THREAD

**Issue by BruceHunter** [IdentityServer/IdentityServer3#3199]
### Question

AuthenticationOptions = new AuthenticationOptions()
{
EnablePostSignOutAutoRedirect = true,
PostSignOutAutoRedirectDelay = 0,
}

Do you think we can add an option to make this page blank white and hide theme? When you have this option you get a split second flicker from one theme to another back to client logout page etc.

I have implemented my own "Content" DLL implementing IViewService and customizing each pages style. I even went so far as to upgrade angular even.

I thought adding a switch might be useful?

Otherwise, I will have to hack my content DLL and toggle the logout.html and loggedOut.html page assets theme myself based on the EnablePostSignOutAutoRedirect switch. If True show theme, if not true show white page.

What do you think?

**Comment by brockallen** [comment]
I don't follow -- why not just do what you need in your custom templates and/or view service?
