### ISSUE TITLE
IdentityServer3 Question- Profile service returned to the following claim types: ""

### ISSUE THREAD

**Issue by wlafrance** [IdentityServer/IdentityServer3#3202]
- [ Y] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have a MVC3 application that is calling my ID Server user info endpoint.
The log file shows I am hitting the endpoint and requesting the claim types I want.
But it is returning zero claims:
Profile service returned to the following claim types: ""

I believe I have a configuration issue.
I have attached my log file and a few code files.

I would appreciate any pointers to help me get past this bump.

[log-20160907.zip](https://github.com/IdentityServer/IdentityServer3/files/459204/log-20160907.zip)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by wlafrance** [comment]
I based my code from an example project.  Here is a link to it.
[the expense tracker example](https://drive.google.com/open?id=0B6uFb19P7rSNWEh5aWVoMnN4THc)

**Comment by brockallen** [comment]
Did you put a breakpoint in your user service and see what's going on?

**Comment by wlafrance** [comment]
I did put break points...  See attachment.
I see my claims and etc... But when the notification in the MVC gets the answer back, the claims are missing...
` 
// CODE IN MVC VIEWER that does not have claims
SecurityTokenValidated = async n =>
                    {
                      //var accessToken = ConfigurationManager.AppSettings("SigningCertificate");
                        var userInfo = await EndpointAndTokenHelper.CallUserInfoEndpoint(n.ProtocolMessage.AccessToken);


                        var givenNameClaim = new Claim(
                            Thinktecture.IdentityModel.Client.JwtClaimTypes.GivenName,
                            userInfo.Value<string>("given_name"));

`
[Screen Captures.zip](https://github.com/IdentityServer/IdentityServer3/files/459538/Screen.Captures.zip)

**Comment by wlafrance** [comment]
Looking at my GetProfileDataAsync method when the client calls for the profile I noticed the context is a bit different and did not have context.Subject.Identity.Name, but instead context.Subject.GetSubjectId() did.

Which is the correct approach here?
I need to get the Id which for my system in the user login name...
 UserNameToValidate = context.Subject.Identity.Name ?? context.Subject.GetSubjectId(),

@brockallen  Anyway, what I was missing was when the client called the IDSvr get profile it was actually not finding the user and thus was returning no claims for the user - so thanks Brock for pointing me in the right direction.  I am just **unsure** if context.Subject.GetSubjectId is the **preferred** approach or not.

**Comment by leastprivilege** [comment]
Subject and Name are two different things - the subject is the unique identifier of the user - the name - well - a name (not necessarily unique).

Always use the subject id to identify the user.
