### ISSUE TITLE
Receiving 401 - Unauthorized: Access is denied due to invalid credentials on production server.

### ISSUE THREAD

**Issue by jonsaxon1977** [IdentityServer/IdentityServer3#3203]
Have a solution working within both IIS Express and Local IIS Server, however when I put the solution on to our production server I am receiving 401 - Unauthorized: Access is denied due to invalid credentials when trying to access a protected resource inside of my MVC application instead of being redirected to the IdentityServer.

Any help on this would be appreciated.

Thanks in advance

**Comment by brockallen** [comment]
Not enough info here.

**Comment by jonsaxon1977** [comment]
When browsing to the MVC app under HTTP I am redirected to the IdentityServer as expected, however when browsing to the MVC app via HTTPS I receive a 401 - Unauthorized: Access is denied due to invalid credentials message.

I do have this all working over HTTPS on my local IIS box using a Self Signed Certificate, on the server I am using a certificate provided by global sign, this certificate is a wildcard certificate e.g *.mydomain.com.

Not sure if this is enough information, but don't know how to get more information about it, I do have logging enabled on the Identity Server however under HTTPS the Identity Server doesn't seem to be hit.

**Comment by brockallen** [comment]
Make sure all of you configured URLs and all for the same scheme (https).

**Comment by jonsaxon1977** [comment]
Thank brockallen I have checked and all urls are using https.

**Comment by brockallen** [comment]
Even when the user visits the site? IOW, I've seen things get confused when the user goes to http://app.com, redirected to IdSvr, and then redirected back to https://app.com

**Comment by jonsaxon1977** [comment]
The urls for the MVC application are below.

`<add key="sthmbc:Authority" value="https://applications01-dev.sthelens.gov.uk/ids/identity" />
<add key="sthmbc:RedirectUri" value="https://applications01-dev.sthelens.gov.uk/trainingbooking/" />`

`app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = ConfigurationManager.AppSettings["sthmbc:Authority"],

                ClientId = "hrtrainingBooking",
                Scope = "openid profile roles trainingBookingApi",

                RedirectUri = ConfigurationManager.AppSettings["sthmbc:RedirectUri"],
                PostLogoutRedirectUri = ConfigurationManager.AppSettings["sthmbc:RedirectUri"],
                ResponseType = "id_token token",
}`

I am accessing the site on https://applications01-dev.sthelens.gov.uk/trainingbooking.

When clicking on a secure page within the app I am receiving the 401 error instead of being redirected to the IdentityServer login page. 

If I enable everything to work under http everything works as expected when accessing the url on http://applications01-dev.sthelens.gov.uk

Not sure if this helps.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
