### ISSUE TITLE
"unsafe" being added to logout URL for custom protocols

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#3205]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have an iOS client that is trying to logout from IdSrv. When they call the endSession endpoint, they are not returned to the `post_logout_redirect_uri`. Instead, they are taken to the logout confirmation page. The link on the page shows:
> unsafe:myapp://auth/logout-callback

I'm assuming the adding of `unsafe` is the reason the user isn't automatically redirected back to the app callback.

Here's my configuration:

```
RedirectUris = new List<string>
                    {
                        "myapp://auth/login-callback"
                    },
                    PostLogoutRedirectUris = new List<string>
                    {
                        "myapp://auth/logout-callback"
                    },
```

Is this a problem with the logout redirect and custom protocols? The `login-callback` endpoint works fine when _authenticating_ (this is using Code Flow btw), so why doesn't the logout?

If i use a normal protocol (e.g `https`) it works fine.

Thanks

**Comment by brockallen** [comment]
No idea -- sounds like a platform specific issue. Can you research it and let us know what you find.
