### ISSUE TITLE
Encountering "There is an error determining which application you are signing into" when clicking protected page link from MS Word document

### ISSUE THREAD

**Issue by ironhawk911** [IdentityServer/IdentityServer3#3206]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

We just recently updated our website to use IdentityServer3 (SSO) v2.5.1. Our staff currently doing documentation for our website. However, we encounter a weird error when clicking a protected page link (e.g. https://www.vicniss.org.au/healthcare-workers/user-portal/) from MS Word document. Basically the expectation is that it should redirect to SSO login page however we are encountering the following error:

_There is an error determining which application you are signing into. Return to the application and try again._

Trying the same link directly in any web browser works as expected.

### Relevant parts of the log file

```
2016-09-08 15:08:17,387 [12] INFO  IdentityServer3.Core.Endpoints.AuthenticationController - rendering login page
2016-09-08 15:08:17,676 [15] INFO  IdentityServer3.Core.Endpoints.AuthenticationController - Login page requested
2016-09-08 15:08:17,682 [15] INFO  IdentityServer3.Core.Endpoints.AuthenticationController - No cookie matching signin id found
```

**Comment by mbulleit** [comment]
This is an issue with MS Office files assuming a different (WS-Fed) authentication protocol. When you click on a hyperlink in any MS Office file (e.g. Word, Excel, PP, etc.) you aren’t immediately passed directly to the browser as you may expect. MS Office first fetches the URL internally and if the link returns a redirect office will request the new URL and take you directly there completely bypassing the original. This means that as far as you’re concerned the first URL is never opened in a browser and the cookie is never created telling IdentityServer from where you came.

**Comment by ironhawk911** [comment]
That's make sense now. Thanks for the explanation.

**Comment by ironhawk911** [comment]
As a workaround, in web.config (of client or RP), we added a URL rewrite that detects if user-agent comes from MS Office Application (ms-office) and then redirect it a html page that automatically redirects to original link. 

FYI.

**Comment by brockallen** [comment]
Nice solution!

**Comment by hubaksis** [comment]
@ironhawk911, may I ask you to show the code of the rewrite rule and the page? Thank you.

**Comment by ironhawk911** [comment]
@hubaksis here is the IIS redirect.

`<rewrite>
	<rules>
		<rule name="MSOffice Redirect" stopProcessing="true">
			<match url="(.*)" />
			<conditions trackAllCaptures="true">
				<add input="{HTTP_USER_AGENT}~{HTTP_X-Device-User-Agent}~{HTTP_X-OperaMini-Phone-UA}" pattern="ms-office" />
				<add input="{HTTP_URL}" pattern="^(((?!ms-office\.html).)*)$" />
			</conditions>
			<action type="Redirect" url="https://{HTTP_HOST}/{C:0}.html?q={UrlEncode:{UrlDecode:{HTTP_URL}}}" appendQueryString="false" redirectType="SeeOther" />
		</rule>
	</rules>
</rewrite>`

For the page, on load the JavaScript code captures the query string (q) then pass it to meta tag to redirect it captured page.

`var redirectUrl = decodeURIComponent(getQueryString("q"));
				var meta = document.createElement('meta');
					meta.httpEquiv = "refresh";
					meta.content = "0; url=" + redirectUrl;	document.getElementById("redirect-link").href = redirectUrl;				document.getElementsByTagName('head')[0].appendChild(meta);`
