### ISSUE TITLE
JArray exists in both IdentityServer3 and Newtonsoft.Json

### ISSUE THREAD

**Issue by spackham** [IdentityServer/IdentityServer3#3207]
- [ X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
This is a run time dynamic code issue.
Yes thanks I am using logging it helped a lot.

if I am not doing something weird-(dont think I am) you have some kind of reference to the JArray in IdentityServer3 and IdentityManager nuget packages dynamically keeping NewtonSoft's <JArray.Parse()> from calling without a runtime error.

With a MVC5 app having IdentityServer3 (v 2.5.3) and IdentityManager 

I get a dynamic (run time) error:
>? JArray.Parse(jsonString);
error CS0433: The type 'JArray' exists in both 'IdentityManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'IdentityServer3, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null'

If I reference IdenityManager as a project instead of a package, I still can't access JArray.Parse with 
the run time dynamic error:

>? JArray.Parse(jsonString);
error CS0433: The type 'JArray' exists in both 'IdentityServer3, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null' and 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

If I reference them both (IdentityServer3) and (IdentityManager) as projects instead of packages, I can call JArray.Parse correctly from NewtonSoft.Json.Linq.JArray.Parse(jsonString);

### Relevant parts of the log file
Non-Really my resourceowner flow is working, but (if I am not doing something weird-dont think I am) you have some kind of reference to the JArray. 
```
             Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Verbose()
            .WriteTo.Trace()
            .CreateLogger();

            LogProvider.GetCurrentClassLogger().Log(IdentityServer3.Core.Logging.LogLevel.Info, () => "Starting IdentityServer3.AspNetIdentity");

            app.Map("/IDSrv3", IDSrv3 =>
            {
                var idSvrFactory = IDSrv3Factory.Configure();
                idSvrFactory.ConfigureUserService();
                var options = new IdentityServerOptions
                {
                    SiteName = "Mindsight OpenID Connect Service",
                    RequireSsl = true,
                    IssuerUri = "http://localhost/",
                    SigningCertificate = LoadCertificate(),

                    LoggingOptions = new LoggingOptions
                    {
                        EnableWebApiDiagnostics = true,
                        EnableHttpLogging = true,
                        WebApiDiagnosticsIsVerbose = true,
                        EnableKatanaLogging = true
                    },
                    Factory = idSvrFactory,

                    EnableWelcomePage = true
                };
                IDSrv3.UseIdentityServer(options);
            });
```

**Comment by brockallen** [comment]
Where is this exception being raised from? Some custom code? Or normal use? Can you reproduce this in the samples?
