### ISSUE TITLE
Question about cors logging

### ISSUE THREAD

**Issue by pkupilas** [IdentityServer/IdentityServer3#3208]
- [o] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have one project which is a client application where i'm using Swagger UI to get data from controllers which are in second project (server). 
I tried to enable cors as the [docs](https://identityserver.github.io/Documentation/docsv2/configuration/cors.html) says:
```
            factory.CorsPolicyService = new Registration<ICorsPolicyService>(resolver => new DefaultCorsPolicyService()
            {
                AllowedOrigins = new HashSet<string> {"http://localhost:13862"};
            });
```

 but IdentityServer doesn't use it and i got error:
(on web console:)
_Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:13862' is therefore not allowed access. The response had HTTP status code 405._
(on server console:)
_(null)             (null)               28 CORS request made for path: /api/path from origin: http://localhost:13862 but rejected because invalid CORS path_

When I enable cors like in ([source](http://enable-cors.org/server_aspnet.html)) everything is fine (i got the response from the server) except IdentityServer logs:
_(null)             (null)               28 CORS request made for path: /api/path from origin: http://localhost:13862 but rejected because invalid CORS path_
_(null)             (null)               28 CORS request made for path: /api/path from origin: http://localhost:13862 but rejected because invalid CORS path_
(yep 2 same logs)

They are come from 
appBuilder.UseIdentityServer(identityServerOptions);
and there is app.UseCors(); which is using default Constants.RoutePaths.CorsPaths so it can't be changed.
Should i worry about these logs? Might be there something which i do wrong?

**Comment by brockallen** [comment]
We only "do" CORS for the IdentityServer endpoints. If you have custom endpoints, you need your own CORS implementation.
