### ISSUE TITLE
Different login pages per relying parties

### ISSUE THREAD

**Issue by sajanep** [IdentityServer/IdentityServer3#3210]
Hello,
I am evaluating Identity Server 3. Planning to make use of WS-Federation protocol since many of my client applications are in .NET 3.5. I read about customizing login page of Identity Server here https://identityserver.github.io/Documentation/docsv2/advanced/customizingViews.html. But I would like to know is it really possible to use different(look and feel) based on the relying party. Can someway I will be able to figure about whether the request is coming from address A and render a specified HTML inside Identity Server? Or another big question could be can I use make use of Identity Server via an API model(like skipping login page of the identity server and invoke login method by supplying user name and password probably  via a post or query string).

**Comment by BruceHunter** [comment]
Actually, I did something like this. Well, it was with the ForgotPassword link showing or not showing. We had to make the location uri dynamic based on the relying client.

I have split the View changes out into it's own DLL named Blah.Host.Content.

1) Implement the IViewService
2) Bring in HttpAssets and PageAssets
3) Create AssetManager class, so that you can service back the PageAssets via server side and Map properties etc.
4) Write logic that determines the Client calling pages.

Login for example
            var client = await _clientStore.FindClientByIdAsync(message.ClientId);
            var name = client?.ClientName;
            return await Render(model, "login", name, message);

Basic idea. I hope that helps.

**Comment by sajanep** [comment]
Hello Bruce,
Thanks for the reply. Inside the sample implementation of IViewSource https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomViewService/CustomViewService/CustomViewService.cs,  I found the code
` public virtual async Task<System.IO.Stream> Login(LoginViewModel model, SignInMessage message)
        {
            var client = await clientStore.FindClientByIdAsync(message.ClientId);
            var name = client != null ? client.ClientName : null;
            return await Render(model, "login", name);
        }`
Are you suggesting by checking message.ClientId, I can select different login pages(basically html's here). If so i did not understand the need for steps you mentioned as 2 and 3. I am very new to Identity Server. Please clarify.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by hongclub** [comment]
Any solid solution on this, i want to do something like this also.
