### ISSUE TITLE
Using Azure AD B2C as external authentication for identity server (completed) and extend claim set returned to App

### ISSUE THREAD

**Issue by beejones** [IdentityServer/IdentityServer3#3211]
I developed an Openid Connect provider based on identityserver. I integrated Azure AD B2C as the external authentication for the provider. This allows me to customize the authentication experience by means of user journeys and provides me Azure AD as directory.
This all worked smoothly and is published here:
https://github.com/beejones/B2CDemoTools/tree/master/Owin%20IdentityServer3/Owin%20IdentityServer3
I now want the extend the claims returned to app by means of additional claims in the id_token. For this I wrote a simple custom user service in branch Experiment/custom-user-store.
Code
    public class UserService : UserServiceBase
    {
        public override Task AuthenticateExternalAsync(ExternalAuthenticationContext context)
        {
            var externalAuth = context.ExternalIdentity;
            var auth = new AuthenticateResult(externalAuth.ProviderId, "ronny", externalAuth.Claims, externalAuth.Provider);
            context.AuthenticateResult = auth;
            return Task.FromResult(0);
        }
    }
externalAuth.Claims contains a list of claims. 
I've experimented with this code but the net result is always the same. The id_token going back to the App does no longer contain claims. If I unregister my user service all claims are available in the id_token.
Is there something I misunderstand or should I use another mechanism to add additional claims into the id_token?

I added a branch to the published project with this custom user service called experiment/custom-user-store.
Thanks

**Comment by brockallen** [comment]
> I've experimented with this code but the net result is always the same. The id_token going back to the App does no longer contain claims.

Can you be more specific here? No longer contains any claims?

**Comment by beejones** [comment]
These are the claims in the id_token without the user service enabled:
{
  "iss": "https:\/\/b2cauth.azurewebsites.net\/identity",
  "aud": "https:\/\/login.microsoftonline.com\/te\/b2ccharm",
  "exp": 1473360664,
  "nbf": 1473360364,
  "nonce": "e5aUApGHVkxVOrz4\/FKFwQ==",
  "iat": 1473360364,
  "sid": "5ae289d3722880acbb124cb97b9fe400",
  "sub": "5ec8dee3fc1a9e82ad23c326504bbe7c",
  "auth_time": 1473360363,
  "idp": "OpenIdConnect",
  "ver": "1.0",
  "name": "Ronny",
  "emails": "ronnybj@microsoft.com",
  "acr": "b2c_1_signin",
  "oid": "a8427557-b7a5-4476-8cb7-e3f8e544ab83",
  "given_name": "Ronny",
  "family_name": "Bjones",
  "amr": [
    "external"
  ]
}

The additional claims come from the B2C tenant and are passed into identityserver. 
The scope userdetails (https://github.com/beejones/B2CDemoTools/blob/master/Owin%20IdentityServer3/Owin%20IdentityServer3/IdentityServer/Config/Scopes.cs) specifies the additional claims in order to pass them back in the id_token to the app.

When the user service is enabled in startup, the additional claims specified in the userdetails scope are no longer in the id_token.

{
  "iss": "https:\/\/b2cauth.azurewebsites.net\/identity",
  "aud": "https:\/\/login.microsoftonline.com\/te\/b2ccharm",
  "exp": 1473340164,
  "nbf": 1473339864,
  "nonce": "4pyZgb+mEg9Qm\/Gr2WnEOg==",
  "iat": 1473339864,
  "sid": "4f8e00c41d3b9958f5611836d513ae27",
  "sub": "a8427557-b7a5-4476-8cb7-e3f8e544ab83",
  "auth_time": 1473339863,
  "idp": "AzureAD",
  "amr": [
    "external"
  ]
}

**Comment by beejones** [comment]
Closed accidentally

**Comment by leastprivilege** [comment]
Claims for tokens are compiled in the user service' `GetProfileDataAsync` method.

We pass you in a context object - you get the incoming claims from the `Subject` property - and set the outgoing ones on `ClaimsIssued`.

**Comment by beejones** [comment]
Thanks.  This worked great.
I included the UserService in the master of my owin identityserver3 solution (https://github.com/beejones/B2CDemoTools/tree/master/Owin%20IdentityServer3). This might be useful for other devs.

**Comment by omayhemo** [comment]
Less than a year old and already it's a dead link.

**Comment by brockallen** [comment]
> Less than a year old and already it's a dead link.

Given that this is not the first time you've made such a complaint, I'm curious what one's to do?

**Comment by rlarno** [comment]
The code can now be found here: https://github.com/Azure-Samples/active-directory-b2c-advanced-policies/tree/master/Owin%20IdentityServer3/Owin%20IdentityServer3
