### ISSUE TITLE
Detecting impersonation in Web API app

### ISSUE THREAD

**Issue by etokarev** [IdentityServer/IdentityServer3#3213]
Hi,
I am developing a SPA + Web API apps that allow certain users (admins) to impersonate other users. I found lots of info on the topic on github and I got it almost working 

https://github.com/IdentityServer/IdentityServer3/issues/1465
https://github.com/IdentityServer/IdentityServer3/issues/2355

So my SPA passes a promp=login with acr_values containing a user name to impersonate. In PreAuthenticateAsync call I look for an impersonation request, validate the current user is admin and the username is valid, etc and return the authentication of the impersonated user.

When Web API is called it receives a access token with the identity of the impersonated user. So I can see it is Bob user instead of Alice (who is admin).  

So my question is how do I know that Bob user is being imprisoned by Alice?  I tried to include extra claims in PreAuthenticateAsync call:

```csharp
var impersonationClaims = new[]
{
	new Claim(Constants.ClaimTypes.Role, "TestRole"),
};
context.AuthenticateResult = new AuthenticateResult(impersonatedUser.Subject, impersonatedUser.Username, impersonationClaims);
```

But I do not see that role on the Web API side. Only standard roles for this user are included:

```
 {
    "Type": "email",
    "Value": "BobSmith@email.com"
  },
  {
    "Type": "role",
    "Value": "Developer"
  },
  {
    "Type": "role",
    "Value": "Geek"
  },
```

**Comment by brockallen** [comment]
The claims you issue in the XxxAuthenticateXxx methods are not the claims that go into the token. They're the claims that go into the authN cookie at IdSvr, and that influence the Subject in the GetProfile API on the user service. You can then use those claims in the Subject in GetProfile to augment the claims in the access token. See if that gets you any closer.

**Comment by etokarev** [comment]
It works now! Now I can see that TestRole in Web API calls. Here is my code snippet that gets me those additional clams I issue in the PreAuthenticateAsync method:

My User Service class inherits from InMemoryUserService for simplicity:
```csharp
        public override Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            base.GetProfileDataAsync(context);

            var roles = _owinContext.Authentication.User.FindAll(Constants.ClaimTypes.Role).ToList();
            if(roles.Any())
                context.IssuedClaims = context.IssuedClaims.Concat(roles);

            return Task.FromResult(0);
        }
```
Thank you for your help.
