### ISSUE TITLE
Identityserver SSO Question.

### ISSUE THREAD

**Issue by randy-westmoreland** [IdentityServer/IdentityServer3#3214]
Hello,

Wasn't sure where to ask this so posted this question here. I have IdentityServer v3 setup as our security token solution. We currently have it setup to redirect to an asp.net webforms project once authenticated. We currently utilize a custom clientstore to build our client redirecturis for SSO. My question is, is this the only way to implement SSO through identityserver?

Thanks!

**Comment by randy-westmoreland** [comment]
To add to the above question to make it more clear I was wondering if there was another option for SSO utilizing identityserver that didn't require the use of the client redirecturis?

**Comment by brockallen** [comment]
Yea, this is more of a SO question. Also, I'd suggest reading the specs, as they cover all the options.
