### ISSUE TITLE
Autocomplete in Android adds space in username on login page

### ISSUE THREAD

**Issue by Dulf** [IdentityServer/IdentityServer3#3217]
### Question / Issue

On some mobile phones (Samsung Galaxy for example) the keyboard offers autocomplete, but "helps" you by adding a space after the word you selected and after typing a dot.

We saw many failed logins with trailing spaces after the username or with spaces inside the username if it contained a dot, like 'john@somedomain.com ' or 'john. doe'

We fixed the trailing space by adding:
`model.Username = model.Username.Trim();`
to the LoginLocal method of the AuthenticationController, right after the 'if (model == null)' check (line 202)

Is this something that could be included in a future build?

**Comment by brockallen** [comment]
Sure.

**Comment by brockallen** [comment]
done
