### ISSUE TITLE
Client Credentials Flow with AD 

### ISSUE THREAD

**Issue by sayd-mateen** [IdentityServer/IdentityServer3#3219]
### Question / Issue
I'm trying to use the Client Credentials flow to get scopes from Active Directory. I have seen the post on how to use AD and have successfully got it working with Resource Owner Flow. I'm now trying to use it with the Client Credentials Flow using the clientID and secret to get information from Active Directory. Do you have any advice on how I could get this working?

### Active Directory example I used
https://github.com/IdentityServer/IdentityServer3/issues/995

**Comment by brockallen** [comment]
There is no user with client credentials flow, so why would you need to contact AD?

**Comment by sayd-mateen** [comment]
In the OAuth Spec:

> 1.3.4.  Client Credentials
> 
>    The client credentials (or other forms of client authentication) can
>    be used as an authorization grant when the authorization scope is
>    limited to the protected resources under the control of the client,
>    or to protected resources previously arranged with the authorization
>    server.  Client credentials are used as an authorization grant
>    typically when the client is acting on its own behalf (the client is
>    also the resource owner) or is requesting access to protected
>    resources based on an authorization previously arranged with the
>    authorization server.

I'm trying to follow a different approach where we do not use in memory clients, all client information is stored in active directory. We authenticate the client credentials with the directory as we do not want to store the client registration within the identity provider. 

In the last sentence of the OAuth paragraph we are doing the first portion, not the second. I hope this doesn't sound too confusing.

**Comment by brockallen** [comment]
So in short you want the client credentials to be validated against something custom (AD in your case)?

**Comment by sayd-mateen** [comment]
Yes that is correct.

**Comment by brockallen** [comment]
Look into implementing a `ISecretValidator`:

https://identityserver.github.io/Documentation/docsv2/configuration/secrets.html

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/ISecretValidator.cs

**Comment by sayd-mateen** [comment]
Thank you ill try it out.
