### ISSUE TITLE
Question about Client Certificate with Hybrid Flow

### ISSUE THREAD

**Issue by cabralRodrigo** [IdentityServer/IdentityServer3#3220]
I'm developing a authentication/authorization server with IdentityServer3 and everything worked fine until now.

I'm trying to verify the hybrid flow client by a `X509Certificate` instead of the hashed secret in the samples.

My question is: **How do I configure the client application to send the certificate for the authentication flow?**

I saw in the source code for [X509CertificateSecretParser.cs](https://github.com/IdentityServer/IdentityServer3/blob/68fe9f496ecbc7a10c571dc769f0fbefb8ce7fde/source/Core/Validation/X509CertificateSecretParser.cs#L61) in order to get the client certificate, the owin environment variable "ssl.ClientCertificate" must have a value, but I cannot find where this value is set, even in the Microsoft.Owin source code.

I also try to use the certificate that I'm loading on the server as the SSL certificate for the client application, but this doesn't work too.

Code for setup the client secret:

```csharp
[my client].ClientSecrets.Add(new Secret
{
    Value = Convert.ToBase64String(cert.Export(X509ContentType.Cert)),
    Type = Constants.SecretTypes.X509CertificateBase64
});
```
Code for setup de authentication of the client application:

```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
    Authority = ...,
    Scope = ...,
    ClientId = ...,
    RedirectUri = ...,
    ResponseType = "code id_token token",
    ClientSecret = "" , //What should I do with this?
    SignInAsAuthenticationType = "Cookies",
    Notifications = new OpenIdConnectAuthenticationNotifications
    {
        RedirectToIdentityProvider = ...,
        AuthorizationCodeReceived = ...
    }
});
```

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
