### ISSUE TITLE
Is it possible to have multiple User Services

### ISSUE THREAD

**Issue by JLarue** [IdentityServer/IdentityServer3#3221]
I have a two types of Authentications that I need to perform via the IS, one involves the traditional User Name and password authentication while the other is with just an account number.  I would like one screen that provides the user with both types of entry (user name/password on left, and Account number on the right).   Both of these types of users will validate to the same back end credentials store via a common security API.  My question is how would I role this with the IS User Service,  is that one US or two distinctly separate services?

**Comment by brockallen** [comment]
You'd probably need to take over all the login workflow then. We have a sample for that: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomLoginPage

**Comment by JLarue** [comment]
Yes I assumed I would have a Custom Login Page, my question is would I implement two custom User Services or in one?  If in one, how would I flow the two types of authentication patterns  (1. User Name/Password  ... 2. Account Number only)

**Comment by brockallen** [comment]
We only support one user service at a time. You could build one that was implemented in terms of the others (like an aggregator).

**Comment by JLarue** [comment]
Thanks but I do not understand what you mean by like an aggregator.  Looking at the IUserService interface and more specifically at AuthenticateLocalAsync, it has both the UserName and Password fields, So in the case of the Login by Account ID should I was thinking to pass in the Account Number into just the UserName and the set the password to "#$ByAccountNumber$#" then within the AuthenticateLocalAsync I would know to call the Account ID validation service if the password was as noted above, otherwise I would perform a straight up local authentication on backing authentication service.  Does that make sense?  Or is there a more elegant way to achieve this?

**Comment by brockallen** [comment]
You can accept more inputs on the login page and then check them in your user service. You can access the custom form params by injecting the OwinEnvironmentService into your ctor and you can read anything from the request.

**Comment by JLarue** [comment]
A much cleaner approach, thanks for your continued support, I got this now!
Cheers
