### ISSUE TITLE
Single Sing On - MVC and WebAPI 4.5

### ISSUE THREAD

**Issue by josuemb** [IdentityServer/IdentityServer3#3222]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Currently I am working in a Solution with next projects:

    IdentityServer
    Web Application
    WebApi Aplication

Until now Identity Server its authenticating Web Application pretty well, however, once a user has been successfully authenticated on (2) I need this user could authenticated on (3) with the same credentials. Since I am calling Services from (3) with JavaScript (from browser).

I tried to to with oidc-client and manually by setting "Authorization" Bearer token without any success.

So you have any idea how to deal with this?

### Relevant parts of the log file
I uploaded a complete solution on: https://github.com/josuemb/authentication-example

**Comment by brockallen** [comment]
Only suggestion would be to look at the working samples and then try to map those to your project.
