### ISSUE TITLE
How to refresh the user claim, after Profile Update?

### ISSUE THREAD

**Issue by Sivalingaamorthy** [IdentityServer/IdentityServer3#3226]
I have successfully integrated the IdentityServer3 with an APP1 with OIDC JS framework, able to Sign-in , Sign-out. Things works great.

I managed to setup User Profile page part of IdentityServer3, I can navigate from APP1 to update the user profile. Works great.

After User Profile update (say LastName), I am able to navigate back to the APP1, works great.

Now the problem is, the LastName claim in the application side is still old. I tried to call login (2) (client.createSigninRequest()) still the lastName claim is not getting refreshed.

I tried to debug the IdentityServer3 server, when I call the login (2), it doesn't hit the

GetClaimsFromAccount() method.

What is wrong here, how to refresh the claim after say profile updates. Can you throw some light, how to overcome this issue, appreciate your help.

**Comment by leastprivilege** [comment]
You can use the access token to get updated claims at the userinfo endpoint.

**Comment by Sivalingaamorthy** [comment]
I tried to check the same from the client side, but getting unauthorised error

I tried to get the user info from client side (tried with angular request but getting unauthorised error):
http://identityserver.github.io/Documentation/docsv2/endpoints/userinfo.html 

                $http.defaults.headers.common['Authorization'] = 'Bearer ' + $rootScope.accessToken; 
                $http.get(identityHostUrl() + '/connect/userinfo')
                    .then(function (response) {
                        callback(response);
                    }).success(function(data) {
            		   callback(data);
            		})
            		.error(function(data, status) {
               	           console.error('Repos error', status, data);
            		})
            		.finally(function() {
                 	  console.log("finally finished repos");
            		});;

Is it possible to request from client in the above mentioned way? is there any reference or sample available, to get the userinfo from client side ?

**Comment by Sivalingaamorthy** [comment]
I was close to finding solution, refer below link if you have any such / similar issue.

https://github.com/IdentityModel/oidc-client-js/issues/105
