### ISSUE TITLE
Keeping a link to the website in the MS Excel (the 'bookmark' issue)

### ISSUE THREAD

**Issue by hubaksis** [IdentityServer/IdentityServer3#3227]
Hi,
We have several websites (site1.com, site2.com, ...) that are using one identity server for checking user's credentials (sso.site.com)
Recently I faced an issue when a client could not open a website (https://site1.com) when he opens the link to the website (site1.com) from the MS Excel. It looked exactly like the issue with bookmarking a login page with signin token (e.g. https://sso.site.com/core/login?signin=1234567890). I checked the link - it pointed to the site1.com, not to the sso server.
After some investigation I found [this topic on StackExchange](http://superuser.com/questions/444984/excel-hyperlink-not-redirecting-properly-bug). 
Basically, it says that
>  Clicking a URL in Excel seems to open it in your default browser. But that's not really true. Before opening it in your browser, Excel first runs Microsoft Office Protocol Discovery. This uses a Windows/Internet Explorer component to determine if the URL works. (It does not identify itself as Internet Explorer, but as "User Agent: Microsoft Office Existence Discovery".) And if the results are (somehow) okay then it will open the result of that check in your default browser.

So, the browser opens the link with signin token passed from Excel without cookies. That is why the error occurs. 
In my logs I can see two requests
`/core/login?signin=123abc(Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; Win64; x64; Trident/7.0; .NET4.0E; .NET4.0C; InfoPath.3; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; ms-office)
/core/login?signin=123abc(Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
`
The first one is from Microsoft Office, the second is from the browser.

Has anyone faced this issue? I think it's pretty similar to the bookmarking a login page issue.

I can see a possible solution described in the topic [is there a way to add additional query string parameters to the response like clientid apart from signin?](https://github.com/IdentityServer/IdentityServer3/issues/1450), but it's still in review. 

`InvalidSignInRedirectUrl` and the list of all projects is not an option for me.

Are there any workarounds for this Excel issue in particular or for bookmarking a login page in general?

Thank you.

**Comment by brockallen** [comment]
Maybe this: https://github.com/IdentityServer/IdentityServer3/issues/3206

**Comment by hubaksis** [comment]
Thank you for that. It's the same. I understand that this is a standart Office behaviour.
Any workarounds so far? 
I can't see anything except adding an additional parameters like clientId to the query string to be able to redirect a user back to the original website to get a new token.

**Comment by brockallen** [comment]
I don't know. This is something that you might need to ask of Microsoft.
