### ISSUE TITLE
Custom error message not shown in login page

### ISSUE THREAD

**Issue by pankajisgarg** [IdentityServer/IdentityServer3#3228]
Hi, 
I also don't see custom error on login page. I am using IdentiyServer3 & CustomViewService sample as base and added Custom UserService.

        public override async Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
    
            // Authenticate 
            ........
            if (output.status == true)
            {
                var user = MapUser(output);
                if (Users.Count > 0)
                {
                    Users.RemoveAt(0);
                }

                Users.Add(user);
                context.AuthenticateResult = new AuthenticateResult(user.Subject, user.Username, user.Claims);
            }
            else
            {
                new AuthenticateResult("Invalid OTP, please verify and try again.");
            }
        }

But on login screen i only see generic error message i.e. "Error: Invalid username or password ".
Can you please let me know, what is missing.

I have looked at https://github.com/IdentityServer/IdentityServer3/issues/1035 but that didnt help much.

Thanks

**Comment by brockallen** [comment]
```
 new AuthenticateResult("Invalid OTP, please verify and try again.");
```
needs to be:
```
context.AuthenticateResult =  new AuthenticateResult("Invalid OTP, please verify and try again.");
```

**Comment by pankajisgarg** [comment]
Thanks brock, very silly of me.
