### ISSUE TITLE
Using IdentityServer3 with Classic ASP.NET Web Forms Application

### ISSUE THREAD

**Issue by alkreddy** [IdentityServer/IdentityServer3#3229]
We have a Classic ASP.NET Web Forms Application that used forms security. We would like leverage token based authentication and are considering IdentityServer3.
I notice that Thinktecture libraries are targeted at OWIN/Katana middle-ware based applications. How to go about using IdentityServer3 for authentication with old styled ASP.NET applications.

**Comment by leastprivilege** [comment]
Two samples here:

No OWIN middleware: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients

WebForms with OWIN:
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WebFormsClient

**Comment by etehadi** [comment]
I can not find "No OWIN middleware" sample. 
Could you show me?
your link is on all clients

**Comment by tobbie** [comment]
Hi brock.

Thanks for your work. I have successfully integrated IdServer3 to a web forms client. However I have an issue with authorization.

I want to restrict access to all pages except one. The Default page.

So In my web.config I have this.

  <system.web>
    <authentication mode="None"></authentication>
    <compilation debug="true" targetFramework="4.5.2"/>
    <httpRuntime targetFramework="4.5"/>
    <pages>
      <namespaces>
        <add namespace="System.Web.Optimization"/>
      </namespaces>
      <controls>
        <add assembly="Microsoft.AspNet.Web.Optimization.WebForms" namespace="Microsoft.AspNet.Web.Optimization.WebForms" tagPrefix="webopt"/>
      </controls>
    </pages>
    <authorization>
      <deny users="?"/>
    </authorization>
  </system.web>
  <location path="Default.aspx">
    <system.web>
      <authorization>
        <allow users="*"/>
      </authorization>
    </system.web>
  </location>

But this does not work. My web forms app is still being redirectred to the Idenity Server for login when I try to access the default page.

What am I doing wrong? Please point me in the right direction
