### ISSUE TITLE
System.InvalidOperationException: Discovery document has no configured signing key for reference tokens

### ISSUE THREAD

**Issue by mishrsud** [IdentityServer/IdentityServer3#3230]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
This is a question, I've got an instance of IdentityServer3 running which issues access tokens as expected.
The question is regarding the setup of IdentityServerBearerTokenAuthenticationOptions when I wiring-up Owin.IAppBuilder.UseIdentityServerBearerTokenAuthentication

** Using Nuget IdentityServer3.AccessTokenValidation version 2.10.0 **

```csharp
var tokenAuthenticationOptions = new IdentityServerBearerTokenAuthenticationOptions
            {
                // other properties not relevant to the question
                DelayLoadMetadata = true
            };
```
If I don't add the DelayLoadMetadata = true, I get a System.InvalidOperationException: Discovery document has no configured signing key exception - which is right because I have no certificate configured as I'm not issuing signed JWT tokens

The question is, is this the correct way to tell the middleware that it should not worry about the JWKS? (as I mentioned, the API using this config is able to introspect and retrieve the claims)
With a previous version of the Nuget - 2.9.1, I did not have to add the DelayLoadMetadata bit

**Comment by leastprivilege** [comment]
Set the validation mode to ValidationEndpoint (or similar). This means that we don't expect JWTs

**Comment by mishrsud** [comment]
@leastprivilege sweet! That works as advertised. For reference I now have this:

```csharp
var tokenAuthenticationOptions = new IdentityServerBearerTokenAuthenticationOptions
            {
                // other properties not relevant to the question
                ValidationMode = ValidationMode.ValidationEndpoint
            };
```
