### ISSUE TITLE
Error when injecting OwinEnvironmentService into IUserService

### ISSUE THREAD

**Issue by CrescentFresh** [IdentityServer/IdentityServer3#3231]
I have a custom implementation of IUserService. When I add a constructor dependency to `IdentityServer3.Core.Services.OwinEnvironmentService` the following error occurs when attempting to reach the identity server login page:

    An error occurred when trying to create a controller of type 'AuthorizeEndpointController'.
    Make sure that the controller has a parameterless public constructor.

Stacktrace:

    at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
    	in c:\\local\\identity\\server3\\Core\\source\\Core\\Validation\\HashedSharedSecretValidator.cs:line 0
    at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)
    	in c:\\local\\identity\\server3\\Core\\source\\Core\\Validation\\HashedSharedSecretValidator.cs:line 0
    at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
    	in c:\\local\\identity\\server3\\Core\\source\\Core\\Validation\\HashedSharedSecretValidator.cs:line 0

The inner exception (`Autofac.Core.Registration.ComponentNotRegisteredException`) looks relevant:

    The requested service 'Microsoft.Owin.IOwinContext' has not been registered.
    To avoid this exception, either register a component to provide the service,
    check for service registration using IsRegistered(), or use the ResolveOptional()
    method to resolve an optional dependency.

Here is my relevant IdentityServerServiceFactory setup code:

    factory.UserService = new Registration<IUserService>(typeof(CustomUserService));

Have I missed something in allowing OwinEnvironmentService to be injectable?

nuget version: 2.5.0 (I would hope to avoid upgrading at this time)

**Comment by brockallen** [comment]
Does your `CustomUserService` have any additional dependencies?

**Comment by CrescentFresh** [comment]
Yes, 3 others. They are registered with the IdentityServerServiceFactory and the service is instantiated without error when the dependency on OwinEnvironmentService is removed.

**Comment by brockallen** [comment]
Can you show your `CustomUserService` ctor list?

**Comment by CrescentFresh** [comment]
I updated the previous comment to show it. Sorry :)

**Comment by CrescentFresh** [comment]
FWIW I upgrade the idsrv3 nuget package to 2.5.4 and the error persists.

**Comment by CrescentFresh** [comment]
The token service also fails with the same inner exception ("The requested service 'Microsoft.Owin.IOwinContext' has not been registered").

The outer exception just points to a different controller:

    An error occurred when trying to create a controller of type 'TokenEndpointController'

**Comment by brockallen** [comment]
Well, something is certainly odd because it does work: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/DependencyInjection/SelfHost/MyCustomServices.cs#L31

**Comment by CrescentFresh** [comment]
That example injects it into a ClaimsProvider. However I will try a reduced example of a simplified IUserService and get back to you.

**Comment by CrescentFresh** [comment]
I modified the DependencyInjection sample to include a custom IUserService:

    public class MyUserService : IdentityServer3.Core.Services.Default.UserServiceBase
    {
        public MyUserService(OwinEnvironmentService svc)
        {
            Debug.WriteLine("MyUserService");
        }
    }

and I can successfully request tokens. I can only presume I would be able to hit the authorization endpoint.

I really don't know what I am doing wrong in my production code however.

**Comment by CrescentFresh** [comment]
Successfully reproduced: Registering a custom claims provider in singleton mode causes the runtime error "The requested service 'Microsoft.Owin.IOwinContext' has not been registered".

Simple custom user service:

    public class MyUserService : IdentityServer3.Core.Services.Default.UserServiceBase
    {
        public MyUserService(OwinEnvironmentService svc)
        {
            Debug.WriteLine("MyUserService");
        }
    }

Setup:

    factory.UserService = new Registration<IUserService, MyUserService>();
    factory.ClaimsProvider = new Registration<IClaimsProvider, MyCustomClaimsProvider>()
    {
        Mode = RegistrationMode.Singleton
    };

Specifying the singleton mode causes the runtime error.

**Comment by brockallen** [comment]
Sure, that makes sense since the Owin context is per-request.

**Comment by CrescentFresh** [comment]
When using Autofac for DI, whenever I've had a class that I'd like to use as a singleton but that may have a method that requires the "current request" I've typically made my ctor dependency of type `Func<ThePerRequestThing>`. Autofac "knows" what this means and generates a func that returns the thing automatically (autofatically har) everytime it is called.

With that in mind I'm going to try changing my custom UserService to take as its dependency `Func<OwinEnvironmentService>` and see if that works. It makes more sense to me to do it that way anyway, since in my mind the instance should be able to serve multiple concurrent requests (my implementation is stateless).

I tried this with the trivial IdentityServer3.Samples code and there were no errors. I'll report back with how it goes, but do you foresee any problems with this approach?

**Comment by brockallen** [comment]
Having a singleton have access to something that wants to be disposed after each request sounds dangerous. But if you can get it to work, then great.

**Comment by CrescentFresh** [comment]
As long as the thing returned from the Func has been registered with Autofac as "instance per request", the func that Autofac generates is smart enough not to dispose of that thing until the end of the request, and if a call to the func is made after it has been disposed it throws a descriptive error stating so. It's a nice feature actually!

I'm kind of wary of doing this however as idsrv3 does not explicitly depend on autofac and so makes no guarantees that another DI framework supports this Func paradigm, meaning that it only "works by accident".
