### ISSUE TITLE
How to get multiple scope with reference token with client_credentials flow?

### ISSUE THREAD

**Issue by subas4u** [IdentityServer/IdentityServer3#3232]
### Question / Issue
How to get multiple scope with reference token with client_credentials flow?

I'm validating the reference token using the code below, and when I check  'ClaimsPrincipal', I only get one of 3 scopes which I have setup at the IdentityServer side. If I change from reference token to Jwt token, then I'm getting all 3 scopes.

```
appBuilder.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions()
            {
                Authority = Configuration["AppSettings:AuthenticationServerAuthority"],
                ValidationMode = ValidationMode.ValidationEndpoint,
                RequiredScopes = new[] { Configuration["AppSettings:AuthenticationScopeRequired"] },
                ClientId = Configuration["AppSettings:AuthenticationClientId"],
                ClientSecret = Configuration["AppSettings:AuthenticationClientSecret"]
            });
```

**Comment by brockallen** [comment]
> How to get multiple scope with reference token with client_credentials flow?

Show the code for how the client is requesting the token.

**Comment by subas4u** [comment]
I'm using Postman to get the token. See the screenshot below.

![image](https://cloud.githubusercontent.com/assets/2606893/18552602/14f17e10-7b2b-11e6-85b6-65847e04dae8.png)

**Comment by brockallen** [comment]
Ah, ok... the Scope configuration needs to have `AllowUnrestrictedIntrospection` set to `true` to see all scopes: :https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Models/Scope.cs#L92

**Comment by subas4u** [comment]
brockallen, thank you so much. It works. Does it have any side effect? is there any reason it was False by default?

**Comment by brockallen** [comment]
Because now this API can read access token contents issued to any other scopes.

**Comment by subas4u** [comment]
Ok. Thank you.
