### ISSUE TITLE
GetIdentityServerPartialLoginAsync() returning null

### ISSUE THREAD

**Issue by CrescentFresh** [IdentityServer/IdentityServer3#3233]
In my custom IUserService I set a partial login authentication result:

    context.AuthenticateResult = new AuthenticateResult("~/../users/account-selection", "1234", "Admin");

Note the path.

My application is hosted with Microsoft.Owin.Host.SystemWeb, and I've "segmented" the core identity server from the custom pages that the application provides, as follows (Startup class):

    app.Map("/core",
        // oidc implementation gets served from this url path prefix
        appInner => ConfigureIdentityServer(appInner));

    app.Map("/users",
        // custom uis get served from this url path prefix
        appInner => ConfigureCustomUIs(appInner));

When idsrv3 issues the cookie that tracks the partial login it sets the cookie path in the http response to its own host prefix:

    Set-Cookie:idsrv.partial=<snip...>; path=/core; HttpOnly

As my custom pages are served from /users they cannot see this cookie and the call to `GetIdentityServerPartialLoginAsync()` fails (or rather, simply returns null).

I presume this is by design however I thought I would ask is there anything I can do to host a page at a path whereby `GetIdentityServerPartialLoginAsync()` would be able to function?

**Comment by brockallen** [comment]
You need to be running in the same path -- IdSvr's middleware is what's giving you the cookie authentication.

**Comment by CrescentFresh** [comment]
I think what you mean is I need to be running inside the same pipeline (which is triggered by the path), would that be more accurate?

In other words, identityserver is configured to install a bunch of middleware into the pipeline it is installed into, therefore any custom pages that wishes to integrate with this pipeline (namely, partial login in this case) must also be installed into the same pipeline.

I actually don't know how to have a custom url installed under identity server's "parent" path with Owin. Do you have a sample of this being done anywhere?

**Comment by brockallen** [comment]
Yep. For a sample, see some of our custom user service samples -- the MVC code uses attribute routing.

**Comment by CrescentFresh** [comment]
I think my problem is I am not using Asp.Net MVC to run my custom pages but rather Nancy. Ironically I don't like MVC as it installs itself into the global pipeline (thus enabling an integration such as this one by default).

**Comment by CrescentFresh** [comment]
This becomes essentially a duplicate of issue #2479
