### ISSUE TITLE
SSO - Redirect from desktop application to web form app

### ISSUE THREAD

**Issue by ddzgit** [IdentityServer/IdentityServer3#3235]
I have a desktop and a few web applications. One of the cases is that the user signs into the desktop application and, through a link is redirected to the web aplitcation without another sing-in. How to implement such a scenerio? Is it possible to do it without using a web view in a desktop app?

**Comment by leastprivilege** [comment]
The recommended approach is that the desktop app uses the system browser for authentication. This way both apps share one authentication session.

**Comment by ddzgit** [comment]
In the case when it would be enough to just redirect from a desktop app to a web app, what approach could be used?

**Comment by ThisNoName** [comment]
If your desktop is Windows, if the browser is IE or Chrome and if your SSO site can be added to trusted intranet list, you can configure using IdSvr Windows authentication.  Then you can just open a browser and it's already authenticated.   Lots of IFs, but sometime it works.

**Comment by leastprivilege** [comment]
As I said - both "apps" need to share a logon session. That could be Windows authentication as @ThisNoName states. Or anything else.

Check the NAPPS spec:

https://tools.ietf.org/html/draft-ietf-oauth-native-apps-03
