### ISSUE TITLE
Question: Is double partial redirect possible?

### ISSUE THREAD

**Issue by CrescentFresh** [IdentityServer/IdentityServer3#3236]
Question: after successful local authentication I'd like to do two partial redirects:

1 if the user requires a password reset do a partial log in to a "change password" screen
2 if the user hasn't done [required thing here] do a partial log in to the [do required thing] page (say, agree to a EULA)

And so on. 

I know how to implement each of the above in isolation, but how do I chain them, so to speak?

One thing I hope not to have to do is to have to include the logic that issues a partial redirect inside any previous step (i.e. keep separate business requirements separate). So for example, I hope I don't have to check for step 2 at the end of step 1, as the order might change, steps removed, etc and doing it that way would be brittle, if that makes sense.

**Comment by brockallen** [comment]
PostAuthenticate in the user service is where you could consolidate that logic. See if putting it there solves it for you.
