### ISSUE TITLE
IdentityServer3 - wsFederation No signin Id passed.

### ISSUE THREAD

**Issue by myaesubi** [IdentityServer/IdentityServer3#3238]
Hi,
I've setup my idp according to the AspNet Identity sample and also according to wsFederatio sample as my service provider is connecting through SAML.
My idp works as I login on the idp.

The wsFederation setup also returns the SAML metadata which with some tweaks manually, I was able to import to my service provider.
Here are the pseudo URIs that setup in the Service Provider:

**SSO Service URL**: https://idp.mydomain.com/core/login?signin=71344310edac7523d809f3010b961212

The Service Provider provides a 'Test connection' function to ensure that connection is established and I would be taken to login page. 

My log is also shows the login page is requested.

### Question / Issue
I get the 

> There is an error determining which application you are signing into. Return to the application and try again.

>  No signin id passed' error in the log.

The url that the 'test connection' hits is in the following format.

(https://idp.mydomain.com/core/login?SAMLRequest=lZJbb5wwEIX%2FCvI7.....)
Would this be the correct URL path to hit with given parameter?  and is my SSO URL setup above correct?

Thanks in advance for any help.
Mohammad

**Comment by leastprivilege** [comment]
We don't support SAML IdP functions. Whatever you do here, you are pretty much on your own.

I think there is more work necessary than "some tweaks".

**Comment by myaesubi** [comment]
Surely, it's not a simple task to take as you stated. 
I did integrate with Azure AD with the provider and learned the metadata structure required so the service provider accepts my identity provider metadata.

Given that the service provider only works with SAML, the wsFederation is not enough to support SAML on IdentityServer3? 
I need to make the decision that do I need to pursue the commercial products for this integration.

Thanks again,
Mohammad

**Comment by leastprivilege** [comment]
As I said - IdentityServer has no support for SAML. Ws-Fed is not enough.

**Comment by myaesubi** [comment]
Thank you for response again.
