### ISSUE TITLE
Infinite Redirect Loop with MVC Client on IIS/ Works fine with IISExpress

### ISSUE THREAD

**Issue by ahsonbukhari** [IdentityServer/IdentityServer3#3239]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi,

I've followed the steps for setting up the IdentityServer and WebClients provided here:

http://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html

and it all works like a charm as long as the Web Client is running on IISExpress. It goes into an infinite loop as the login screen is submitted [and scopes allowed] for a client running on IIS.

I've been stuck with it for the past few days and have tried out all solutions reported by other people having faced similar issues. None of the following reported solutions has worked for me:

- Writing up the client application from scratch
- Adding session_start to the Global.asax
- Using SystemWebCookieManager class as the cookie manager
- Setting RequireSSL to false (just to eliminate possibilities)

https://github.com/IdentityServer/IdentityServer3/issues/294
https://github.com/IdentityServer/IdentityServer3/issues/2496
http://stackoverflow.com/questions/29780627/identityserver-gets-into-infinite-loop-of-authentication

None of the above solutions have worked for me.

To reiterate, I have set up the simplest Server and Client apps following the steps in the documentation to the letter and I've got them to work perfectly _**as long as the client remains on IISExpress**_.

I wrote up a custom authorize attribute to debug the "HandleUnauthorizedRequest" method and as I had expected, the break point inside this method keeps getting hit after the login screen is submitted. The section of the log file below is also repeated once the system goes into the infinite loop. These two things indicate that the server is authenticating the client and credentials but the Authentication is not being passed to the IIS based Client.

I have written up several different client apps but run into the same issue each time. I've been using the standard ASP.NET Web Application template with an Empty application and MVC checkbox checked. One single controller and a single action method with the [Authorize] attribute on it. So no custom configurations to the client whatsoever.

### Relevant parts of the log file

```
w3wp.exe Information: 0 : 2016-09-19 16:19:54.647 +01:00 [Information] Creating Hybrid Flow response.
w3wp.exe Information: 0 : 2016-09-19 16:19:54.647 +01:00 [Information] Creating Implicit Flow response.
2016-09-19 16:19:54.647 +01:00 [Debug] Creating access token
2016-09-19 16:19:54.647 +01:00 [Debug] Creating JWT access token
2016-09-19 16:19:54.653 +01:00 [Debug] Creating identity token
w3wp.exe Information: 0 : 2016-09-19 16:19:54.653 +01:00 [Information] Getting claims for identity token for subject: 1
2016-09-19 16:19:54.653 +01:00 [Debug] Creating JWT identity token
2016-09-19 16:19:54.656 +01:00 [Debug] Adding client "mvc" to client list cookie for subject "1"
w3wp.exe Information: 0 : 2016-09-19 16:19:54.656 +01:00 [Information] End authorize request
w3wp.exe Information: 0 : 2016-09-19 16:19:54.656 +01:00 [Information] Posting to https://localhost/WebClient
2016-09-19 16:19:54.656 +01:00 [Debug] Using DefaultViewService to render authorization response HTML
w3wp.exe Information: 0 : 2016-09-19 16:19:54.791 +01:00 [Information] Start authorize request
w3wp.exe Information: 0 : 2016-09-19 16:19:54.792 +01:00 [Information] Start authorize request protocol validation
w3wp.exe Information: 0 : 2016-09-19 16:19:54.792 +01:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"mvc\",
  \"ClientName\": \"MVC Client\",
  \"RedirectUri\": \"https://localhost/WebClient\",
  \"AllowedRedirectUris\": [
    \"https://localhost/WebClient\"
  ],
  \"SubjectId\": \"1\",
  \"ResponseType\": \"code id_token token\",
  \"ResponseMode\": \"form_post\",
  \"Flow\": \"Hybrid\",
  \"RequestedScopes\": \"openid profile\",
  \"State\": \"OpenIdConnect.AuthenticationProperties=_EU6fMGWFO-4wkLpM_Xx39xQe1O9VENU370TkNjKzAQjNhghfleflRczSgMRdlm60vGpQ4sgKdVnQhJb2AwYIgKsEByMKTTq65FZnj93wOo9NclseBq5SYDcV8biersxY-g6BCjfobqX5F05LZD9rCAuXQFOjZMj6qpCsNkNPfM7zRx1o-ASGpFUM3VjOR__kJoeSLBRrgJ7A5vF00SqhMcSHmmpYGo99IE0Pxjylyc\",
  \"Nonce\": \"636098951947841518.NTA1NzIxMzYtYjAwNC00NjM5LWE1YTItZDBlZTA5Nzg0MjA4MjkyZDJkZDYtZWY2ZS00MTk4LTk2NmEtZjk2NzY2MjhhNTc3\",
  \"SessionId\": \"dcf3565c7af64736afce53327fa20cce\",
  \"Raw\": {
    \"client_id\": \"mvc\",
    \"redirect_uri\": \"https://localhost/WebClient\",
    \"response_mode\": \"form_post\",
    \"response_type\": \"code id_token token\",
    \"scope\": \"openid profile\",
    \"state\": \"OpenIdConnect.AuthenticationProperties=_EU6fMGWFO-4wkLpM_Xx39xQe1O9VENU370TkNjKzAQjNhghfleflRczSgMRdlm60vGpQ4sgKdVnQhJb2AwYIgKsEByMKTTq65FZnj93wOo9NclseBq5SYDcV8biersxY-g6BCjfobqX5F05LZD9rCAuXQFOjZMj6qpCsNkNPfM7zRx1o-ASGpFUM3VjOR__kJoeSLBRrgJ7A5vF00SqhMcSHmmpYGo99IE0Pxjylyc\",
    \"nonce\": \"636098951947841518.NTA1NzIxMzYtYjAwNC00NjM5LWE1YTItZDBlZTA5Nzg0MjA4MjkyZDJkZDYtZWY2ZS00MTk4LTk2NmEtZjk2NzY2MjhhNTc3\"
  }
}"
w3wp.exe Information: 0 : 2016-09-19 16:19:54.792 +01:00 [Information] Creating Hybrid Flow response.
w3wp.exe Information: 0 : 2016-09-19 16:19:54.792 +01:00 [Information] Creating Implicit Flow response.
2016-09-19 16:19:54.792 +01:00 [Debug] Creating access token
2016-09-19 16:19:54.792 +01:00 [Debug] Creating JWT access token
2016-09-19 16:19:54.795 +01:00 [Debug] Creating identity token
w3wp.exe Information: 0 : 2016-09-19 16:19:54.795 +01:00 [Information] Getting claims for identity token for subject: 1
2016-09-19 16:19:54.796 +01:00 [Debug] Creating JWT identity token
2016-09-19 16:19:54.799 +01:00 [Debug] Adding client "mvc" to client list cookie for subject "1"
w3wp.exe Information: 0 : 2016-09-19 16:19:54.799 +01:00 [Information] End authorize request
w3wp.exe Information: 0 : 2016-09-19 16:19:54.799 +01:00 [Information] Posting to https://localhost/WebClient
2016-09-19 16:19:54.799 +01:00 [Debug] Using DefaultViewService to render authorization response HTML

```

Could you please point me in the right direction as to what else I could try out or if someone has already managed to resolve this issue.

Much appreciated

**Comment by ahsonbukhari** [comment]
![image](https://cloud.githubusercontent.com/assets/15265349/18639477/fb652dac-7e8b-11e6-9c70-ea49c49a3a59.png)

Another thing I've noticed is that the break point in the Notifications section never gets hit when on IIS but it does get hit on IISExpress. Not sure if this is helpful.

**Comment by ThisNoName** [comment]
It was bug in Microsoft Katana or something, and they have abandoned it and moved on to the new shiny core.

[http://stackoverflow.com/questions/28559237/intermittent-redirection-loops-during-adfs-authentication/28580067#28580067](url)

**Comment by ahsonbukhari** [comment]
Hi ThisNoOne,

Thanks for your suggestion. Unfortunately it hasn't worked for me though. The reason as I've discovered through other means as well is that **Context.User.Identity.IsAuthenticated** remains "**false**", despite the fact that the server has authenticated the user.

The client context is not being updated and therefore redirects back to the server which already has a valid session and therefore redirects back to the client, and we have our infinite loop. However, if the same client is running on IISExpress, the context does get updated and Context.User.Identity.IsAuthenticated returns true.

**Comment by TimGergen** [comment]
I had a similar issue, and found it was a difference in behavior in the Microsoft.Owin.Security.OpenIdConnect library.  The OpenIdConnectAuthenticationOptions contain a setting for the callbackPath.  The documentation states this will be determined from the RedirectURI if not provided, but I have found when running under IIS, this does not get set for me.  Specifically providing the callback path in the options resolved the issue for me, as it prevented the redirect back to IdentityServer:
```

new Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions            {            
                Authority = AppSettings.IdentityServerIssuerUri,
                ClientId = "myclient",
                RedirectUri = "https://mydevserver.company.local:8088/IdentityAdmin/callback/",
                ResponseType = "id_token token",
                UseTokenLifetime = false,    
                CallbackPath = new PathString("/callback/"),               
                Scope = Constants.RequiredScopes,
SignInAsAuthenticationType = Constants.AuthType,
 }
```

**Comment by ahsonbukhari** [comment]
And we have lift off!!!

Thanks a mill TimGergen. This appears to have resolved the issue for me. It had been quite frustrating to say the least.

I appreciate the details on the background as well.

Cheers!

**Comment by srirajmadhavan** [comment]
Hi,

Having the same issue - I have the applicaiton hosted under a website in IIS as api. the Client setting looks like:

                `ClientId = "assetmanager",
                Authority = "https://nycnc.nav.us/idp/navigatoridp",
                RedirectUri = "http://localhost:1000/api/home/index/",
                //RedirectUri = "http://localhost:53028/?cid=4845",
                SignInAsAuthenticationType = "Cookies",
                ResponseType = "code id_token token",
                Scope = "openid profile toolsapi",
                CallbackPath = new PathString("/home/"),
                UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications()
                {
                 ......
`

Wanted to know if the callbackpath that i am trying out is correct or not. Any pointers?Microsoft.Owin.Security.OpenIdConnect version 3.0.1.0 in use.

**Comment by TimGergen** [comment]
Hi srirajmadhavan,

So this works in IIS Express but not in IIS?

Remember the [CallbackPath](https://msdn.microsoft.com/en-us/library/microsoft.owin.security.openidconnect.openidconnectauthenticationoptions.callbackpath(v=vs.113).aspx) is where your application will get a post after successfully authorizing the client.   My guess is that after authentication, you may be getting a post to 'http://localhost:1000/api/home/index/' since that is what you are passing in as the redirect URI; but the middleware is listening on '/home/'.  These two addresses should align.  It is possible that your application is not getting a callback at all, the redirect loop issues is tied to some other issue.

Check your logs and see if you are getting a POST to the address `http://localhost:1000/api/home/ ` after logging into Id server and what the resultant code is. 

Tim

**Comment by srirajmadhavan** [comment]
Hi Tim,

This is my loop: 

https://nycnc.nav.us/navigatoridp/login?signin=85e608d6e7225ba9a0856a7a9c1f36af POST 302

https://nycnc.nav.us/navigatoridp/connect/authorize?client_id=assetmanager&redirect_uri=http%3A%2F%2Flocalhost%3A1000%2Fapi%2Fhome%2Findex%2F&response_mode=form_post&response_type=code%20id_token%20token&scope=openid%20profile%20toolsapi&state=OpenIdConnect.AuthenticationProperties%3DAHnEvRUAH6ls55X-X1x2V-jsNhYPlHJ_y9oA4fLF2Pg0P1Igp1QTkKCvqnqWlblDzFqAlrtgaFHAI_tSwLkPzGWifvlIhcr3-OQpEuwlZ74LQcsUoLhPwdrXFG_uf05PcOACnFBulGNIstkT_LgvZs0FWzf5aaM5HPRfHbfVGv5uEJ-jeFtW-5fRypbzUh9T65vyTYjT4HlZePx-0X8K2dOZ1fw&nonce=636151601262763773.ZDQ5OGNkZTUtZmNjMS00MjE4LTg4NTQtODczZWVmZDVlOTQzZmU5NGRiNDEtYjE4NS00ZmEzLWJmMGUtNjQ5M2E3ZmFlYzBi GET 200

https://nycnc.nav.us/navigatoridp/assets/app.FormPostResponse.js GET 200

http://localhost:1000/api/home/index/  POST 302

and again goes to the IDP authorize URL. The breakpoint at SecurityTokenValidated notification is not getting hit as well. 

When i removed the callbackpath it hits the breakpoint on the SecurityTokenValidated. but with the following redirect loop:

IDP posts back to http://localhost:1000/api/home/index/ with 302 status - breakpoint hits
Redirects to http://localhost:1000/api/?cid=4845 with GET 302
Back to https://nycnc.nav.us/navigatoridp/connect/authorize?...

I think the Authorize attribute on my home/index is somehow not able to validate the IDP user.

Sriraj

**Comment by TimGergen** [comment]
I don't think the authorize attributes matter for this, because open id connect middleware will receive the request prior to your code.  

Try changing your callback path to  '/home/index/' since that is where you are posting back to and see if that stops the redirects.

Tim

**Comment by srirajmadhavan** [comment]
Still the same redirect. :(

Why I doubt Authorize attribute is because, when i created a custom authorize attribute, I could debug and see that the user identity is not set. The notification breakpoint hits and then the custom authorize attribute. Shouldnt the middleware be setting the User Identity? correct me if i am wrong.

Sriraj

**Comment by srirajmadhavan** [comment]
Hi Tim,

Finally, keeping a session start on the global.asax with callback path worked!. Is there a reason for this?

Thanks - Sriraj

**Comment by TimGergen** [comment]
So the call to the configuration of the openId connect middleware was in session start?  It should not need to be in session start - this would indicate it is being called for every session - and really it should only need to be called on app start.   I would call the configuration  methods from either the Application_Start method in global.asax, or the  [ owin startup.cs class](https://www.asp.net/aspnet/overview/owin-and-katana/owin-startup-class-detection) if your app is using that.

**Comment by srirajmadhavan** [comment]
I have the configuration in owin startup.cs only. Global.asax had regular MVC registrations.
Added Session_Start to global.asax.  Attached the start up i am using.

[Startup.txt](https://github.com/IdentityServer/IdentityServer3/files/601546/Startup.txt)

Sriraj.

**Comment by TimGergen** [comment]
I am not sure why it is not working in Startup.cs, but is in Session_Start.
However, CallbackPath property does not appear to be set in the startup.cs
you have linked.

**Comment by srirajmadhavan** [comment]
As I mentioned before - with CallbackPath, it does not hit the notifications and goes into redirect loop. Same after adding the session_start also. Hence I removed.  Will this be an issue with the way the IDP is setup?

**Comment by wlafrance** [comment]
@TimGergen  the callback trick worked.  I  had to convert an old MVC 3 application to support IdentityServer3.  I added the Session_Start code in the global and that did not fix it.  
In my Startup.cs file I had to add your suggested callback trick.  After figuring out the correct path all is well.  Thanks...

` 
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "app_jcrl",
                Authority = Constants.BaseAddress,
                RedirectUri = "https://localhost:44379/home/",
                PostLogoutRedirectUri = "https://localhost:44379/",
                ResponseType = "code id_token",
                Scope = "openid profile read write offline_access",
                CallbackPath = new PathString("/home/index/"),  **// Critical to prevent infinite loop** 
                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "role"
                },
`

**Comment by alastair-mcdonald** [comment]
I struggled with this for 2 days and finally fixed it with the [Kentor.OwinCookieSaver](https://github.com/KentorIT/owin-cookie-saver) fix, shown below in case it helps someone.

`startup.configuration()` now starts as follows...
```
app.UseKentorOwinCookieSaver();
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationType = "Cookies"
    //CookieManager = new SystemWebCookieManager(), (didn't fix it)
    //CookieSecure = CookieSecureOption.Never  (didn't fix it)
});
```
All the other proposed solutions did not work:
- [Disabling session state](http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues&referringTitle=Documentation) and using SystemWebCookieManager
- Setting CallbackPath as above
- using both http and https on the same page was not the issue
- mis-matched casing in the redirect url was not the problem e.g. https://MyServer.com/Identity in the auth server config and https://myserver.com/identity in the client app config was not the issue.
- Found useful analysis [here](https://stackoverflow.com/questions/20737578/asp-net-sessionid-owin-cookies-do-not-send-to-browser/26978166#26978166)

**Comment by Ben-Pattinson** [comment]
Another way you can have the infinite loop is if you configure everything else correctly, but you neglect to add the: 
app.UseAuthentication();
Just had this happen to me - feeling pretty silly now :)

**Comment by pvasek** [comment]
Just be careful that If your app runs inside a virtual directory (not in the site root), the `CallbackPath` must include this part as well. For example my app was running in `App1` virtual directory so I had to use:
```
CallbackPath = new PathString("/App1/callback/"), 
```

That's because in `OpenIdConnectAuthenticationHandler` is this check:

```
            // Allow login to be constrained to a specific path. Need to make this runtime configurable.
            if (Options.CallbackPath.HasValue && Options.CallbackPath != (Request.PathBase + Request.Path))
            {
                return null;
            }
```
