### ISSUE TITLE
How can I get the sid for an access token?

### ISSUE THREAD

**Issue by null-d3v** [IdentityServer/IdentityServer3#3240]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I'm currently implementing some caching at the API level. Some of this caching is dependent on the user's session with the identity provider. I believe the sid would be an adequate way to identify sessions, however it is not present on access tokens.

- Should I be using the sid to adequately identify identity provider sessions?
- Is it possible to retrieve the sid for an access token?

### Relevant parts of the log file

```
```

**Comment by null-d3v** [comment]
I see now that the DefaultClaimsProvider will filter out the sid, even when specified with a scope claim, by way of the ClaimsProviderFilterClaimTypes in FilterProtocolClaims. Is there a reason, security or spec, why the sid would be specifically included in this blacklist collection?

**Comment by brockallen** [comment]
Because normally access token lifetime is not really tied to the user's session at the OP.
