### ISSUE TITLE
Cookie/Claims issue when multiple applications hosted on the same server

### ISSUE THREAD

**Issue by ThisNoName** [IdentityServer/IdentityServer3#3241]
For the longest time, I thought authentication cookie and claims are shared per SSO session.  So I have to use Owin Middleware and ClaimsTransformation to handle app specific roles, etc.  Until Scott [pointed out](http://stackoverflow.com/questions/39277702/identityserver3-cant-update-cookie-when-apps-are-on-different-machine) it was just "a bit of a red herring" when apps are hosted on the same server.  Now I realize this issue actually lead me on a wild goose chase for several months!

Basically, if two applications are configured like this:
```
http://myserver/app1
http://yourserver/app2
```
then they have separate authentication cookies and _SecurityTokenValidated_ got hit the first time each application starts, regardless existing SSO session.  So this can be used to run app initialization process, set app specific roles and custom claims, etc. 

However, if the applications are configured on the same server
```
http://myserver/app1
http://myserver/app2
```
Then cookies are leaked between  two.  If user goes to app1 first, then app2, app2's SecurityTokenValidated are NOT hit.  And app2 can see app1's claims (this lead me to think app specific claims can only be handled in middleware using claims transformation).

So the question is, how can I keep the two applications separate when they are hosted on the same server?  Thanks.

**Comment by brockallen** [comment]
In IdSvr you can set the prefix on the authentication options: https://identityserver.github.io/Documentation/docsv2/configuration/authenticationOptions.html

For other apps you'd have to change the cookie names with whatever framework you're using.

**Comment by ThisNoName** [comment]
Thanks for the quick response.  

I saw that page and the sample,  and also look at CookiePath.  But they seem apply to all cookies from IdSvr side and don't help differentiate two apps from the same server.   It is as if SSO set client cookie by host name only.  I would imagine because client is configured with a RedirectUri, it would be able to tell http://myserver/app1 and http://myserver/app2 apart.  No?

I got a sense that this cookie is set on the client side and probably not an IdSvr issues, but I couldn't find out where.  On client side, I'm using Owin.Security.OpenIdConnect -Version 3.0.1, pretty much exactly like the sample code.  I dig through all options and couldn't find a place to set cookie name per application (like the good n old Authentication - Form - Name in web.config).

Any hint?  Really appreciated.

**Comment by brockallen** [comment]
> But they seem apply to all cookies from IdSvr side and don't help differentiate two apps from the same server. 

Correct -- this only affects cookies from IdSvr. Other app, as I said, need to be configured so they can distinguish their own cookies. If you're using Katana, then this is on the cookie authentication middleware.

**Comment by ThisNoName** [comment]
Ah, found it.  Can't believe wasting all this time trying to implement elaborated claims transformation all for missing one basic option!

BTW, I'm trying this on some intranet applications.  If we were to implement this for external application, we probably need some expert consultation time.  Not sure how this works in open source world.  Do you have any recommendations?   Thanks.

```
app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                CookieManager = new SystemWebCookieManager(),
                CookieName = "here it is"
            });
```

**Comment by brockallen** [comment]
>  If we were to implement this for external application, we probably need some expert consulting time. Not sure how this works in open source world. Do you have any recommendations? Thanks.

Not sure I follow.

**Comment by ThisNoName** [comment]
We may need someone to review our implementation and answer how-pick-proof-is-your-lock type of question.  Wonder if any of you offer consulting service.

**Comment by brockallen** [comment]
Yes: https://www.identityserver.com/
