### ISSUE TITLE
Identity and Access Control tool

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [IdentityServer/IdentityServer3#3242]
Hello,

I am trying to follow the Identity and Access Control in ASP.NET 4.5 Pluralsight training video by Dominick Baier and am using Visual Studio 2015. I can't find the Identity and Access control he is using. He is also showing the IdentityServer running. How do I run the IdentityServer. I downloaded the code from here. Thanks.

- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
This tool is long gone. For running identityserver - follow the docs and samples.
