### ISSUE TITLE
Running the IdentityServer

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [IdentityServer/IdentityServer3#3243]
I downloaded the code and trying to run the server making Host.Web as the default project. I get this:
HTTP Error 403.14 - Forbidden
The Web server is configured to not list the contents of this directory.

The url says: https://localhost:44333/

Thanks.

- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by ThisNoName** [comment]
Sample server root url is often https://localhost:44333/core

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
