### ISSUE TITLE
Mobile - 401 - unauthorized: Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by RPresley220** [IdentityServer/IdentityServer3#3245]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am trying to pull an identity token from identity server by calling it from are mobile Xamarin project. instead of returning a login or my token, it instead returns this message:

401 - unauthorized: Access is denied due to invalid credentials
You do not have permission to view this directory or page using the credentials that you supplied.

now I know that my iis authentication are added properly. I am curious if this is a Identity server issue? 

### Relevant parts of the log file

w3wp.exe Information: 0 : 2016-09-20 09:45:24.602 -04:00 [Information] ##############--  CONFIG  --#####################
w3wp.exe Information: 0 : 2016-09-20 09:45:24.602 -04:00 [Information] ## Environment Loaded : Dev
w3wp.exe Information: 0 : 2016-09-20 09:45:24.602 -04:00 [Information] ## HostName Loaded : Server
w3wp.exe Information: 0 : 2016-09-20 09:45:24.602 -04:00 [Information] ## Api Environment Loaded : https://Server/idsrvr.api/
w3wp.exe Information: 0 : 2016-09-20 09:45:24.602 -04:00 [Information] ##################################################
w3wp.exe Information: 0 : 2016-09-20 09:45:24.820 -04:00 [Information] Loading Dev Certificates
w3wp.exe Warning: 0 : 2016-09-20 09:45:24.914 -04:00 [Warning] AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2016-09-20 09:45:24.914 -04:00 [Warning] TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2016-09-20 09:45:24.914 -04:00 [Warning] ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2016-09-20 09:45:24.914 -04:00 [Warning] RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 2016-09-20 09:45:25.414 -04:00 [Information] Start authorize request
w3wp.exe Information: 0 : 2016-09-20 09:45:25.414 -04:00 [Information] Start authorize request protocol validation
w3wp.exe Information: 0 : 2016-09-20 09:45:25.570 -04:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"Client\",
  \"ClientName\": \"Client\",
  \"RedirectUri\": \"https://<Server>/<Client>.api/\",
  \"AllowedRedirectUris\": [
    \"https://Server/Client.api/\",
    \"https://Server/Client.api.proxy/\"
  ],
  \"SubjectId\": \"unknown\",
  \"ResponseType\": \"id_token token\",
  \"ResponseMode\": \"fragment\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid profile AppLevel Personal\",
  \"State\": \"0620e8674e274c5eb3380d57f30beaf9\",
  \"Nonce\": \"a4ee543422f040058f388705f9758fd0\",
  \"Raw\": {
    \"client_id\": \"<Client>\",
    \"response_type\": \"id_token token\",
    \"scope\": \"openid profile AppLevel Personal\",
    \"redirect_uri\": \"https://Server/Client.api/\",
    \"nonce\": \"a4ee543422f040058f388705f9758fd0\",
    \"state\": \"0620e8674e274c5eb3380d57f30beaf9\"
  }
}"
w3wp.exe Information: 0 : 2016-09-20 09:45:25.570 -04:00 [Information] User is not authenticated. Redirecting to login.
w3wp.exe Information: 0 : 2016-09-20 09:45:25.570 -04:00 [Information] End authorize request
w3wp.exe Information: 0 : 2016-09-20 09:45:25.570 -04:00 [Information] Redirecting to login page
2016-09-20 09:45:25.664 -04:00 [Debug] Protecting message: "{\"ReturnUrl\":\"https://Server/idsrvr/identity/connect/authorize?client_id=Client&response_type=id_token%20token&scope=openid%20profile%20AppLevel%20Personal&redirect_uri=https%3A%2F%2F<Server>%2FClient.api%2F&nonce=a4ee543422f040058f388705f9758fd0&state=0620e8674e274c5eb3380d57f30beaf9\",\"ClientId\":\"Client\",\"AcrValues\":[],\"Created\":636099759253520397}"
w3wp.exe Information: 0 : 2016-09-20 09:45:32.195 -04:00 [Information] Login page requested
2016-09-20 09:45:32.195 -04:00 [Debug] signin message passed to login: "{
  \"ReturnUrl\": \"https://Server/idsrvr/identity/connect/authorize?client_id=Client&response_type=id_token%20token&scope=openid%20profile%20AppLevel%20Personal&redirect_uri=https%3A%2F%2FServer%2FClient.api%2F&nonce=a4ee543422f040058f388705f9758fd0&state=0620e8674e274c5eb3380d57f30beaf9\",
  \"ClientId\": \"Client\",
  \"IdP\": null,
  \"Tenant\": null,
  \"LoginHint\": null,
  \"DisplayMode\": null,
  \"UiLocales\": null,
  \"AcrValues\": [],
  \"Created\": 636099759253520397
}"
w3wp.exe Information: 0 : 2016-09-20 09:45:32.211 -04:00 [Information] local login disabled for the client
w3wp.exe Information: 0 : 2016-09-20 09:45:32.211 -04:00 [Information] only one provider for client
w3wp.exe Information: 0 : 2016-09-20 09:45:32.211 -04:00 [Information] redirecting to provider URL: "https://Server/idsrvr/identity/external?provider=adfs&signin=91888efc1cac6be1a59641d7f8957c9d"
w3wp.exe Information: 0 : 2016-09-20 09:45:33.445 -04:00 [Information] External login requested for provider: "adfs"
w3wp.exe Information: 0 : 2016-09-20 09:45:33.461 -04:00 [Information] Triggering challenge for external identity provider
w3wp.exe Information: 0 : 2016-09-20 09:45:56.570 -04:00 [Information] Start authorize request
w3wp.exe Information: 0 : 2016-09-20 09:45:56.570 -04:00 [Information] Start authorize request protocol validation
w3wp.exe Information: 0 : 2016-09-20 09:45:56.570 -04:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"Client\",
  \"ClientName\": \"Client\",
  \"RedirectUri\": \"https://Server/Client.api/\",
  \"AllowedRedirectUris\": [
    \"https://Server/Client.api/\",
    \"https://Server/Client.api.proxy/\"
  ],
  \"SubjectId\": \"unknown\",
  \"ResponseType\": \"id_token token\",
  \"ResponseMode\": \"fragment\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid profile AppLevel Personal\",
  \"State\": \"2614883480ca47af9b2d3f7b1196e225\",
  \"Nonce\": \"65b0a9f537ae48958b7d49c31ac64966\",
  \"Raw\": {
    \"client_id\": \"<Client>\",
    \"response_type\": \"id_token token\",
    \"scope\": \"openid profile AppLevel Personal\",
    \"redirect_uri\": \"https://Server/Client.api/\",
    \"nonce\": \"65b0a9f537ae48958b7d49c31ac64966\",
    \"state\": \"2614883480ca47af9b2d3f7b1196e225\"
  }
}"
w3wp.exe Information: 0 : 2016-09-20 09:45:56.570 -04:00 [Information] User is not authenticated. Redirecting to login.
w3wp.exe Information: 0 : 2016-09-20 09:45:56.570 -04:00 [Information] End authorize request
w3wp.exe Information: 0 : 2016-09-20 09:45:56.570 -04:00 [Information] Redirecting to login page
2016-09-20 09:45:56.570 -04:00 [Debug] Protecting message: "{\"ReturnUrl\":\"https://Server/idsrvr/identity/connect/authorize?client_id=<Client>&response_type=id_token%20token&scope=openid%20profile%20AppLevel%20Personal&redirect_uri=https%3A%2F%2Server%2FClient.api%2F&nonce=65b0a9f537ae48958b7d49c31ac64966&state=2614883480ca47af9b2d3f7b1196e225\",\"ClientId\":\"Client\",\"AcrValues\":[],\"Created\":636099759565708951}"
w3wp.exe Information: 0 : 2016-09-20 09:45:59.649 -04:00 [Information] Login page requested
2016-09-20 09:45:59.649 -04:00 [Debug] signin message passed to login: "{
  \"ReturnUrl\": \"https://Server/idsrvr/identity/connect/authorize?client_id=Client&response_type=id_token%20token&scope=openid%20profile%20AppLevel%20Personal&redirect_uri=https%3A%2F%2F<Server>%2FClient.api%2F&nonce=65b0a9f537ae48958b7d49c31ac64966&state=2614883480ca47af9b2d3f7b1196e225\",
  \"ClientId\": \"Client\",
  \"IdP\": null,
  \"Tenant\": null,
  \"LoginHint\": null,
  \"DisplayMode\": null,
  \"UiLocales\": null,
  \"AcrValues\": [],
  \"Created\": 636099759565708951
}"
w3wp.exe Information: 0 : 2016-09-20 09:45:59.649 -04:00 [Information] local login disabled for the client
w3wp.exe Information: 0 : 2016-09-20 09:45:59.649 -04:00 [Information] only one provider for client
w3wp.exe Information: 0 : 2016-09-20 09:45:59.649 -04:00 [Information] redirecting to provider URL: "https://Server/idsrvr/identity/external?provider=adfs&signin=bfa7b1f4ca42becb65fb1c7564e1b994"
w3wp.exe Information: 0 : 2016-09-20 09:46:00.617 -04:00 [Information] External login requested for provider: "adfs"
w3wp.exe Information: 0 : 2016-09-20 09:46:00.617 -04:00 [Information] Triggering challenge for external identity provider

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
