### ISSUE TITLE
How can i set AcrValues in OpenIdConnectAuthenticationOptions

### ISSUE THREAD

**Issue by cuongtr** [IdentityServer/IdentityServer3#3246]
I have read the doc "https://identityserver.github.io/Documentation/docsv2/endpoints/authorization.html"
I would like to pass some data into AcrValues and I can't find any way to do that in OpenIdConnectAuthenticationOptions.
My client config 

               ` idsrvApp.UseCookieAuthentication(new CookieAuthenticationOptions
                {
                    AuthenticationType = "Cookies",
                    CookieName = Constants.AUTH_COOKIE_NAME
                });

                idsrvApp.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
                {
                    Authority = ConfigurationManager.AppSettings["IdentityServerEndPoint"],
                    ClientId = "06de763b-ad15-4225-a147-9f7b5da61cdf",
                    RedirectUri =ConfigurationManager.AppSettings["PaymentEndPoint"],
                    ResponseType = "id_token",
                    Scope = "openid",
                    SignInAsAuthenticationType = "Cookies",
                });`
Many Thanks.

**Comment by dariusdamalakas** [comment]
You pass acr_values when you make authorize call, not in config. Just append acr_value as query string param

**Comment by cuongtr** [comment]
Thanks for your reply but now I'm using [Authorize] to authorize my action method and I need to remove it and call by Authorize endpoint ?

**Comment by brockallen** [comment]
You need to add them on the event on the OIDC middleware. Some of our samples show this.

**Comment by cuongtr** [comment]
@brockallen sorry but I don't understand, I would like to add some additional information when redirect user to login form and I have a custom login form by "DefaultViewService" and I think property AcrValues in "SignInMessage" model is a good place to pass my additional information.

**Comment by brockallen** [comment]
In this event you can appends params to the protocol request: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client%20(Hybrid)/Startup.cs#L87

**Comment by cuongtr** [comment]
Thanks for your quick reply. I will try this

**Comment by cuongtr** [comment]
I did it , thanks again

**Comment by michaelsogos** [comment]
Hi @cuongtr can you explain what you did?
I cannot figure out how to pass tenant code.

Thanks.
