### ISSUE TITLE
Passing acr_values for implicit flow 

### ISSUE THREAD

**Issue by NovakSavic** [IdentityServer/IdentityServer3#3247]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Passing acr_values for the case of using  resource owner it easy. But for the case of implicit flow, when using custom login template, I did not figure out. I see that action of form is set to model.loginurl. This resolves to /login?signin=<some value>. If I could add here acr_values here in addition, if I could have control over related anvil arms controller... Or if I simply add one more input here to be passed when form is submitted..
What are my options here? How can I achieve this?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
You can customize the UI and add additional form elements. You can then receive those in your user service via the OwinEnvironmentService. This has been discussed many times in the issue tracker history.

**Comment by NovakSavic** [comment]
HI Alen. Thanks. Ok. I underdtand. But is there a way that this can be handled in the same way for both resource owner and implicit flow? For resource owner if I send acr_values, I can reach them in the property SignInMessage of LocalAuthenticationContext that I get when Login is called. For implicit flow I guess that I can reach them through OWIN environment. But is there a way to set acr_values so they are available in the same way as for resource owner flow?

**Comment by NovakSavic** [comment]
Speaking about acr_values, I want to pass tanant. So for resource owner flow, this is fine by passing acr_values tenant:<value>, so this is available later on as property Tenant of SignInMessage. So the same I would like to achieve implicit flow. I do not need any other custom acr_values but only Tenant. It would be great if I can handle this in the same way for all flows when user is involved, through LocalAuthenticationContext.SignInMessage.Tenant.

**Comment by brockallen** [comment]
Resource owner the UI is in the client and there is no acr_values since the client uses the token endpoint.

**Comment by NovakSavic** [comment]
Sure for resource owner UI is part of the client. Maybe I do not understand your point. But this is working, when I pass acr_values (e.g. tenant:tenant1234)  as parameter of x-www-form-urlencoded body, I get LocalAuthenticationContext.SignInMessage.Tenant set to tenant1234. Also in the source code of Identity Server 3, in TokenRequestValidator  inside ValidateResourceOwnerCredentialRequestAsync method, there is processing of acr values, exactly setting tenant and idp as well.  This is all fine for me. 

What I would like, is to have something similar for implicit flow, so I can get information from the same place, which is LocalAuthenticationContext.SignInMessage.Tenant

**Comment by brockallen** [comment]
I guess I'm the one that's not following. You want the tenant value in the custom login UI?

**Comment by NovakSavic** [comment]
Hi Allen. 

I would like to pass tenant id for both flows that I mentioned
1. In the client UI (resource owner flow). This is fine, I just pass acr_values and value (e.g. tenant:tenant1234) as an additional value of x-www-form-urlencoded body when issuing request to /connect/token. So I have this value in LocalAuthenticationContext.SignInMessage.Tenant in AuthenticateLocalAsync of my custom UserService.

2. In the custom login UI (implicit flow). But in the way, so I can get tenant value in the same way as above.

**Comment by NovakSavic** [comment]
Hi Alen. What do you sugest?

**Comment by leastprivilege** [comment]
pass the tenant as an acr_value query string parameter. check the docs.

**Comment by NovakSavic** [comment]
Yes I read docs.  As I wrote above for resource owner flow this is fine works, but for implicit flow when I use custom login page, I pass acr_values as well using AngularJS expressions, so I endup with this:

login?signin=743d95a85290aab6849402c06a878e17&acr_values=tenant:Tenant

But this value seems not to be read. So I add additional parameter in form and than read that through OwinEnvironmentService. 

So basically I need to look for tenant on two places first on SignIn message Tenant property and than inside body of request. 

So my initial question was: "How to pass acr_values through login and to read this value in the same way as for resource owner flow?"

Does Identity Server reads this as well for implicit flow?

Can you please tell me what this value of signin message means:
signin=**743d95a85290aab6849402c06a878e17**

**Comment by leastprivilege** [comment]
The acr_values is available in the UserService from the context that gets passed in.

**Comment by NovakSavic** [comment]
Yes for resource owner, but for implicit they are not initialized

**Comment by leastprivilege** [comment]
yes they are.

**Comment by NovakSavic** [comment]
So how shall I do this from _login.html page. Maybe I'm doing something wrong.
I'm doing the following:
<form name="form" method="post" action="{{model.loginUrl + '&acr_values=tenant:' + model.tenant}}">

So in the request I get this:
login?signin=743d95a85290aab6849402c06a878e17&acr_values=tenant:Tenant

But when I debug my UserService in the AuthenticateLocalAsync(LocalAuthenticationContext context)

In the context acrvalues are not initialized.

**Comment by leastprivilege** [comment]
You have to pass the acr_values to the authorize endpoint - not the login page.

**Comment by NovakSavic** [comment]
Yes I know, but I can not do that because in my case client is angular app, and since I do not know for which tenant user want to login, I can not pass this to authorize endpoint in advance, before login screen appears.
