### ISSUE TITLE
Skip Client Authorization 

### ISSUE THREAD

**Issue by nkdev89** [IdentityServer/IdentityServer3#3249]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi, I'm looking to skip the client authorization and authenticate only using the user credential , I know this is against the identity server, But my business need is in the way that API can be accessed with any type of client and API just needs a Access token from identity Server . Please let me know how can i do this ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
ClientId / Secret is required.
