### ISSUE TITLE
Best practice keep OP session alive for code client

### ISSUE THREAD

**Issue by dariusdamalakas** [IdentityServer/IdentityServer3#3250]
### Question 
I've got confused on what is the right way for code flow client to keep the OP session alive, and what is the recommended way to acquire new access tokens. Any gui

1. Should code clients request for refresh token (offline access) an use this then to request new access tokens when old one expires? 
2. The above raises a question how to keep the OP session alive. Given that RP client does not have to call /authorize endpoint, the OP session will eventually expire (whether it is 10hr default or shorter). 
3. Should instead RP detect when RP session expires, and redirect browser to /authorize to request for a new access token? 

[MvcGettingStarted](https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html) does not use refresh token, and relies on cookie middleware (which is configured with UseTokenLifetime=false) to redirect to authorize endpoint when RP cookie expires.

On the other hand, [MvcCodeFlowExample](https://github.com/IdentityServer/IdentityServer3.Samples/blob/c0f147c4f481fe77244ef4a2d5e006a4a4366c41/source/Clients/MvcCodeFlowClientManual/Controllers/AppController.cs#L46) uses refresh token to request new access token.

**Comment by leastprivilege** [comment]
Authentication session and access tokens are two different things. Generally yes - code/hybrid clients use the refresh token to get long-lived access to an API.

Why does the authentication session matter to you at this point?
