### ISSUE TITLE
Defining required scope

### ISSUE THREAD

**Issue by nburak** [IdentityServer/IdentityServer3#3251]
Hello guys, I need to get an answer for a question in my mind. I don't have enough experience for identity server 3 and  I wish you could help me. 

How to define a new scope or modify existing scopes as required. 
I need that users  can't uncheck it.

**Comment by leastprivilege** [comment]
There is a "Required" flag on the Scope class IIRC

**Comment by nburak** [comment]
Thank you very much for your help.
