### ISSUE TITLE
WS-Fed Signout Image Question

### ISSUE THREAD

**Issue by elryry** [IdentityServer/IdentityServer3#3254]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I currently have idsrv configured to redirect user off to an external provider which is a ws-fed solution. One issue I am having is, on logout, the ws-fed provider is looking for an image at  identityserver?wa=signoutcleanup1.0.

Seemed simple enough, so I implemented this code in my idsrv instance:

```
internal static async Task WsFederationLogout(IOwinContext ctx, Func<Task> next)
        {
            var queryString = ctx.Request.Query;
            var wa = queryString.Get("wa");

            if (wa != null)
            {
                if (wa == "wsignoutcleanup1.0")
                {
                    ctx.Authentication.SignOut("Cookies");
                    var response = HttpContext.Current.Response;
                    response.Cache.SetCacheability(HttpCacheability.NoCache);
                    response.ClearContent();
                    response.BinaryWrite(SignOutImage);
                    HttpContext.Current.ApplicationInstance.CompleteRequest();
                }
            }

            await next();
        }
```

and I threw it in my Startup.cs above the registration of idsrv via `app.Use(WsFederationLogout)`

My question is, after doing this I don't get the expected functionality. The idsrv landing page is still loading with the bytes "attempting" to load in with the request (not successfully, obviously).

How can I prevent the idsrv code from executing and just return my .gif file in the response? I apologize if this is more of an MVC question than an Identity Server question, but I'm not having much luck exploring anywhere else.

### Relevant parts of the log file

```
None
```

**Comment by brockallen** [comment]
If it's signout, then don't call `await next();`

**Comment by elryry** [comment]
`await next();` is only called if `wa` is null and `wa != "wsignoutcleanup1.0"`. The `HttpContext.Current.ApplicationInstance.CompleteRequest()` should prevent `await next()` from being triggered, shouldn't it?

**Comment by brockallen** [comment]
`HttpContext.Current.ApplicationInstance.CompleteRequest` is a SystemWeb thing, but you're writing OWIN middleware. Those are two different paradigms and so I have no idea how well they will play together. Just put a return after `response.BinaryWrite(SignOutImage);`.

Having said all of that, I have no idea if that's your issue.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
