### ISSUE TITLE
How to secure a custom controller method?

### ISSUE THREAD

**Issue by brinkie2004** [IdentityServer/IdentityServer3#3255]
### Situation

I have IdSrv up and running with my own repositories. Authentication works fine, as well as some custom views (registration form and reset password form). Everything runs behind '/identity', so I can access the current session bits (signin token). I have used the (community) RazorViewService so I could customize the default views.

I'm facing a problem when adding a secured method to my IdSrv. I'd like to add a view where an authenticated user (!) can change his/her password. I specifically don't want this page to be part of the client application.

I've added a ChangePassword() method to my MVC Controller and I've secured it with the [Authorize] attribute. When accessing this method, I'd like an authenticated user to be able to see the view and change his password. When unauthenticated I'd like the user to be redirected to the login page. After successful authentication I'd like him to be returned to the ChangePassword() method, to change his password.

### Question

What do I need to add/change in the IdSrv configuration to enable this scenario?

**Comment by brockallen** [comment]
Look into these and see if any help: https://github.com/IdentityServer/IdentityServer3.Extensions.Mvc

**Comment by brinkie2004** [comment]
Thanks for the pointer @brockallen. Adding the IdentityServerFullLoginAttribute to my secured controller saved me.
