### ISSUE TITLE
Unable to obtain a refresh token:

### ISSUE THREAD

**Issue by cwdyang** [IdentityServer/IdentityServer3#3257]
What do I need to do to enable offline_access scope? I would like to make a request to the connect/token endpoint to obtain a refresh token, i have added the offline_access scope to the client i am requesting a RT for but i keep on getting "invalid_scope", the offline_access exists in the global scope store too.
What am I missing here?

any help is appreciated!

the client has "offline_access" under client/scopes, have tried resourceowner / clientcredential flows.

scopes (global) contain offline_access (enabled, include all claims for user, type = 1)

e.g.
POST
https://localhost:44333/connect/token

grant_type:client_credentials
client_id:sushi
client_secret:sushi
scope:offline_access
response_type:token

RESPONSE
{
  "error": "invalid_scope"
}

**Comment by leastprivilege** [comment]
Refresh tokens don't make sense for client credentials. Try resource owner flow instead.

**Comment by cwdyang** [comment]
thanks @leastprivilege  ok will give it another crack - where can we find information on how to set up a client, what flow to use and an example of http post to request a refresh token? thanks heaps!!

**Comment by leastprivilege** [comment]
our docs, our samples and the spec.
