### ISSUE TITLE
Content Security Policy error checksession.html

### ISSUE THREAD

**Issue by crockelsET** [IdentityServer/IdentityServer3#3258]
Hi,

We have an Angular application that uses IdentityServer for authentication.  We're using oidc-client.js to manage silent refresh of tokens, this is working well other than receiving the following for line 10 of checksession.html.  

`Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-2rfe4osP7aXncYpiVqBcMTZbP4BxaWQgTOH4QMh/k2w='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
`

I've tried changing the CSP options in IdentityServer without success.  Am I missing something here?  I've searched through all issues and no-one else appears to have had the same problem.

thanks.

**Comment by brockallen** [comment]
The check session endpoint does not enable CSP. Is it your app that's emitting CSP headers, and thus preventing the check session iframe from being allowed to load/run?

**Comment by crockelsET** [comment]
Thanks for the quick response.  The Angular application is running on a different domain to our IdentityServer.  It's the request from within the iframe of that application.  Details of the error are in the attached image. 

![image](https://cloud.githubusercontent.com/assets/13238690/18877419/211381a4-84c5-11e6-9612-68acca99c0a3.png)

**Comment by brockallen** [comment]
The top level page in the browser where you get this problem -- that's your app's page, right?

**Comment by crockelsET** [comment]
Yes, that's right.

**Comment by brockallen** [comment]
So then you need to change CSP in your app to allow this.

**Comment by crockelsET** [comment]
Thanks.  In the end it was the CSP settings in our IdentityServer site that we had to change.

**Comment by mosestito** [comment]
@crockelsET I'm having the same issue here, would you please share what exactly you did at the IdenityServer side interms of CSP settings? Thanks.

**Comment by easygoingalex** [comment]
@crockelsET I'd like to know as well as @mosestito, thanks.
