### ISSUE TITLE
Get User Prinicipal authenticated in web api 

### ISSUE THREAD

**Issue by husseinsa** [IdentityServer/IdentityServer3#3259]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
 I am trying to  modify the "**IdentityServer.JsWalkthrough**"  code:

- I added an AuthorizeAttribute to the api which will trigger after passing identity server and redirect the request to API Resource

```
public override void OnAuthorization(HttpActionContext actionContext)
        {
            if (actionContext.RequestContext.Principal.Identity.IsAuthenticated)
            {
             
            }  
        }

```
In Identity Server, I have extended the UserServiceBase:

```
     public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            var user = Users.SingleOrDefault(x => x.Username == context.UserName && x.Password ==   
           context.Password);
            if (user != null)
            {

                context.AuthenticateResult = new AuthenticateResult(user.Subject, user.Username);
            }
            else
            {
                context.AuthenticateResult = new AuthenticateResult("You are not authorized to login");
            }


            return Task.FromResult(0);
        }

        public override Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            // issue the claims for the user
            var user = Users.SingleOrDefault(x => x.Subject == context.Subject.GetSubjectId());
            if (user != null)
            {
                context.IssuedClaims = user.Claims.Where(x => 
               context.RequestedClaimTypes.Contains(x.Type));
               

            }

            return Task.FromResult(0);
        }

```

 I am trying to get the user already got authenticated or passed against identity server, so i can get its subject (id) or other custom claims in order to run my custom authorization against my DB.

However, I can't get any claim from there, also the _IsAuthenticated_ property is false.

How can I do that?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest
