### ISSUE TITLE
Claims valueType serialization : Introspection endpoint

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer3#3260]
Question

nbf and exp claims are converted to string in AccessTokenValidation and Introspection response. But RFC says it should be integer. I have seen [Issue#1471](https://github.com/IdentityServer/IdentityServer3/issues/1471) and [Issue #266](https://github.com/IdentityServer/IdentityServer3/issues/266)  but they refer to JWT validation. But why are we converting to string in referece token validation ?
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/TokenValidator.cs#L334

**Comment by leastprivilege** [comment]
OK - that looks like a bug.
