### ISSUE TITLE
IdentityServer3: Local Database + Active Directory

### ISSUE THREAD

**Issue by lexon0011** [IdentityServer/IdentityServer3#3261]
### Situation
I use at the moment IdentityServer3 in combination with AspNetIdentity. Now I want to expand the authentication to the active directory. For this I want to create a checkbox on the logon screen, where the user could decide if he wants to authenticate aigainst to active directory or to the local database:

![4duxw](https://cloud.githubusercontent.com/assets/16290662/18909791/485f0520-8575-11e6-8567-62548772739b.png)

### Question

1. I require in my custom user service the information, if the checkbox for windows authentication is checked. Then I could write the following code:

```
public async override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
        // check if the option for windows authentication is set
        // Yes: Authenticate over active directory: UserPrincipal.FindByIdentity(principalContext, username)
        // No: Authenticate over local database 
}
```

1. Is this a good approach to solve my requirements or is there a better solution? I want to design it so simple as possible for the user.

Thank you for helping!!

**Comment by leastprivilege** [comment]
That would be one of way of doing it. You could also use the Windows Authentication Service as an external provider - and this way enable integrated authentication.

**Comment by lexon0011** [comment]
At the moment I implement the following solution: 
- In the `AuthenticateLocalAsync` method I check, if the user is available in the local database. 
- If the user is in the local database, I validate username and password against the local database.
- If the user is not in the local database, I validate username and password against the active directory.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
