### ISSUE TITLE
Role claims are missing when the ResponseType is "token id_token"

### ISSUE THREAD

**Issue by rchamila** [IdentityServer/IdentityServer3#3263]
Hi ,

I'm having a weird issue with identity server 3 and aspnet core mvc app, If I use response type as both token and id_token I can't see the role claims. But If I use just the id_token it works as expected. My startup open id connect configurations are as follows

`OpenIdConnectOptions options = new OpenIdConnectOptions();
options.AutomaticChallenge = true;
options.Authority = Configuration["AppSettings:IdentityServer"];
options.ClientId = "PaywiseEmployerPortal";
options.SignInScheme = "Cookies";
options.ResponseType = "token id_token"; 
options.CallbackPath = new PathString("/Employers/Employer/Index/");
options.PostLogoutRedirectUri = Configuration["AppSettings:PostLogoutRedirectUri"];
options.RequireHttpsMetadata = false;

options.Scope.Add("openid");
options.Scope.Add("roles");
options.Scope.Add("profile");

app.UseOpenIdConnectAuthentication(options);`

I'm creating new role claims and assign as follows in identity server in both AuthenticateLocalAsync and GetProfileDataAsync methods.

`public Task GetProfileDataAsync(ProfileDataRequestContext context)
{
	object providerKey = null;
	try { 
		//Build up claims, derive from membership roles  
		List<Claim> claims = new List<Claim>();

		Claim subject = context.Subject.Claims.FirstOrDefault();

		if (subject != null)
		{
			providerKey = new Guid(subject.Value);
			var member = Membership.GetUser(providerKey );
			if (member != null)
			{
				string username = member.UserName;

				claims = this.BuildProfileForUserName(member);

				//Filter out the claims that weren't requested
				if (context.RequestedClaimTypes != null)
				{
					claims = claims.Where(c => context.RequestedClaimTypes.Contains(c.Type)).ToList();
				} 
			}
		}

		context.IssuedClaims = claims.AsEnumerable();
	}
	catch (Exception ex)
	{
		log.Error(string.Format("Error getting profile data for user {0}", providerKey == null? "" : providerKey.ToString()), ex);
	}
	return Task.FromResult(0);
}

public Task IsActiveAsync(IsActiveContext context)
{
	object providerKey = null;
	try
	{
		Claim subject = context.Subject.Claims.FirstOrDefault();
		providerKey = new Guid(subject.Value);
		var member = Membership.GetUser(providerKey);

		if(member != null)
		{
			context.IsActive = !member.IsLockedOut && member.IsApproved;
		}
		else
		{
			context.IsActive = false;
		}
	}
	catch (Exception ex)
	{
		log.Error(string.Format("Error checking is active for user {0}", providerKey == null ? "" : providerKey.ToString()), ex);
	}
	return Task.FromResult(0);
}

private List<Claim> BuildProfileForUserName(MembershipUser user)
{
	List<Claim> claims = new List<Claim>();
	
	if (user != null)
	{  
		//if MembershipProvider indicates this is a client then we will Add the MobileApi Claim
		var roles = Roles.GetRolesForUser(user.UserName);
		claims.Add(new Claim("name", user.UserName));
		if (roles.Contains(ConvertRoleEnumerationToString(RoleEnumerations.Member)))
		{                 
	  
			claims.Add(new Claim("role", "Member"));
		}
		if (roles.Contains(ConvertRoleEnumerationToString(RoleEnumerations.Employer)))
		{                  
			claims.Add(new Claim("role", "Employer"));
		}
		if (roles.Contains(ConvertRoleEnumerationToString(RoleEnumerations.Staff)))
		{                   
			claims.Add(new Claim("role", "Staff"));
		}
	}  
	return claims;
}`

Could you please help me to sort this out

**Comment by brockallen** [comment]
Set GetClaimsFromUserInfoEndpoint = true on the OIDC MW options.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
