### ISSUE TITLE
How to use Identity Server 3 with Site Core 8.1 

### ISSUE THREAD

**Issue by FullyCSharped** [IdentityServer/IdentityServer3#3264]
Hi,

I am looking at using IdentityServer 3 with Sitecore 8.1. Has anybody tried it already and could help me with some pointers to start with.

Thanks
Pradeep

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest
