### ISSUE TITLE
Best Practice when to refresh tokens

### ISSUE THREAD

**Issue by Gentlehag** [IdentityServer/IdentityServer3#3265]
I made a simple test application which uses a hybrid flow to authenticate .

I store the refresh token as a claim and so i'm able to refresh tokens.

But what ist the recommended best practice when to do that?

on which event should I validate the expiration? Or should I wait for an unauthorized event ? Is there any example for this?

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest
