### ISSUE TITLE
IdentityServer-Angular

### ISSUE THREAD

**Issue by Sudkart** [IdentityServer/IdentityServer3#3266]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi Team,

I have an angular js application and i want to redirect the application to the identityserver login page.

How could i do that ?

Do i have any sample links where i can redirect the javascript application to the identityserver login page.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest
