### ISSUE TITLE
Question about invalidating the Default UserServiceCache

### ISSUE THREAD

**Issue by LeeDumond** [IdentityServer/IdentityServer3#3267]
We have a rather complex implementation where we are using IdentityServer as part of a custom front-end proxy that manages mainframe RACF authentications for our users. 

No need to go into specifics here. Suffice to say that because of some really off-the-wall scenarios we have to support, we need a way to invalidate the default in-memory cache "on demand" at **sign out**.

We are using the Katana OWIN middleware and are calling `Request.GetOwinContext().Authentication.SignOut()` from an MVC controller action. 

We need to make sure that if a user **signs out** and tries to sign in again, that the user info endpoint will always fetch fresh data and rebuild the user claims from scratch.

Is there a built-in way to do this already? I tried to access the MemoryCache instance from inside the signout controller but it appeared to be empty.

**Comment by brockallen** [comment]
So then don't use the cache, and if you need caching then build your own?

**Comment by LeeDumond** [comment]
Yes, those are both options I had considered. Just wondering if there was some other existing technique of which I was not aware. Thanks for the suggestions.

**Comment by brockallen** [comment]
I don't have the code in front of me, but I don't think we had anything too intelligent in there about the cache, other than the timeout.

**Comment by LeeDumond** [comment]
You are correct, just the timeout value

**Comment by LeeDumond** [comment]
If we implemented an API to invalidate the default caching would you guys accept it as a pull request?

**Comment by brockallen** [comment]
I guess the question is how is it triggered? Sounds more like a custom solution for your scenario. I guess give me an idea what it looks like, and if it's sufficiently general yet useful then we'd consider it.
