### ISSUE TITLE
Object Reference Error

### ISSUE THREAD

**Issue by dalefrancis88** [IdentityServer/IdentityServer3#3269]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have a client_credentials flow client that i've just added to our system. It has access to three scopes. OpenID, AllClaims and a custom one. 

I can validate against this client on the /connect/token endpoint however when i then try to use that token to get the claims from /connect/userinfo I get a NullReference exception on the UserInfoEndpointController

`   at IdentityServer3.Core.Endpoints.UserInfoEndpointController.<GetUserInfo>d__6.MoveNext() in c:\local\identity\server3\Core\source\Core\Endpoints\Connect\UserInfoEndpointController.cs:line 98
`

My question is, why would it possible be throwing this exception? is this the right endpoint to hit for claims on the client credential flow or should i switch to using jwt tokens and pull it from there?

### Relevant parts of the log file

```
<log goes here>
```
[Auth-Log.txt](https://github.com/IdentityServer/IdentityServer3/files/505345/Auth-Log.txt)

**Comment by leastprivilege** [comment]
Well - a null ref exception is clearly a bug.

But your setup does not make sense - client credentials represents a client - not a user, hence openid scope as well as userinfo does not apply.

**Comment by dalefrancis88** [comment]
Yeah, I thought as much when I was writing this out. Just wanted to check. 
I'll submit a pull request tomorrow with the bug fix since it's trivial, if you like. 

Get Outlook for iOS




On Mon, Oct 3, 2016 at 8:01 PM +1100, "Dominick Baier" <notifications@github.com> wrote:












So yea - 



this is a bug



https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/Connect/UserInfoEndpointController.cs#L98



We should code more defensively here.



But fact is, in a client credentials based token, there is no sub claim. Because there is no user.

**Comment by leastprivilege** [comment]
feel free. thanks!

**Comment by dalefrancis88** [comment]
What error should it return, invalid_grant or invalid_client ? Or maybe just a 500?
Or is this something I should check the spec for an answer?

Get Outlook for iOS




On Mon, Oct 3, 2016 at 8:49 PM +1100, "Dominick Baier" <notifications@github.com> wrote:












feel free. thanks!

**Comment by leastprivilege** [comment]
Need to do more spec research. Actually a client cred client shouldn't be able to request the openid scope in the first place.

**Comment by leastprivilege** [comment]
I just double checked - an client cred client cannot request identity scopes at the token endpoint. I think your config is somehow wrong.

**Comment by dalefrancis88** [comment]
So below is my current client credentials client. RavenClient is just a class that extends Client so that I can save it into raven with a nice id that makes it faster to load later.

So it's currently allowing two Identity scopes. It was mostly put in there for testing but i understand why it would be wrong to ask for them.

We're going to run v3 in production for a the next week or so while I upgrade/update to v4. Although its not meant to be that way, i'll check to see if it happens in v4 and I could write the code in there to throw an exception/error if a client is requested and its flow is ClientCredentials to throw and invalid_client exception, sounds good?

`

                new RavenClient
                {
                    ClientName = "Engine Client",
                    ClientId = "engine",
                    AccessTokenLifetime = int.MaxValue, // seconds
                    ClientSecrets = new List<Secret>
                    {
                        new Secret("NotTellingYou".Sha256())
                    },
                    Enabled = true,
                    Claims = new List<Claim>
                    {
                        new Claim("creditor", "creditor/1")
                    },
                    Flow = Flows.ClientCredentials,
                    AccessTokenType = AccessTokenType.Jwt,
                    AllowedScopes = new List<string>
                    {
                        "engine-api",
                        Constants.StandardScopes.OpenId,
                        Constants.StandardScopes.AllClaims
                    }
                }
`

**Comment by leastprivilege** [comment]
And how is openid scope defined?

**Comment by dalefrancis88** [comment]
OpenId is a StandardScope defined in IdentityServer3.Core.Models.StandardScopes.

**Comment by leastprivilege** [comment]
i want to see code ;)

**Comment by dalefrancis88** [comment]
so to add the scope to RavenDb I have actions that initialize on startup.

`
            scopes.Add(new RavenScope(StandardScopes.OpenId));
`

RavenScope has a constructor that takes in scope. 

`
    public class RavenScope : Scope
    {
        public RavenScope(Scope baseScope, bool isStandardScope = true)
        {
            IsStandardScope = isStandardScope;

            this.Name = baseScope.Name;
            this.AllowUnrestrictedIntrospection = baseScope.AllowUnrestrictedIntrospection;
            this.Claims = baseScope.Claims;
            this.ClaimsRule = baseScope.ClaimsRule;
            this.Description = baseScope.Description;
            this.DisplayName = baseScope.DisplayName;
            this.Emphasize = baseScope.Emphasize;
            this.Enabled = baseScope.Enabled;
            this.IncludeAllClaimsForUser = baseScope.IncludeAllClaimsForUser;
            this.Required = baseScope.Required;
            this.ScopeSecrets = baseScope.ScopeSecrets;
            this.AllowUnrestrictedIntrospection = baseScope.AllowUnrestrictedIntrospection;
            this.ShowInDiscoveryDocument = baseScope.ShowInDiscoveryDocument;
        }

        public RavenScope()
        {
        }

        public string Id => $"scope/{this.Name}";

        public bool IsStandardScope { get; set; }
    }
`

Then in the RavenScopeStore FindScopesAsync is implemented

`


        public async Task<IEnumerable<Scope>> FindScopesAsync(IEnumerable<string> scopeNames)
        {
            var items = await session.Advanced.LoadStartingWithAsync<RavenScope>("scope/");

            return items.Where(s => scopeNames.Any(n => s.Name == n));
        }
`

This is currently working for the other clients and works as long as I don't do something silly like ask for the UserInfo on a client_credentials client ;)

**Comment by leastprivilege** [comment]
you are not setting the type. It default to resource scope.

**Comment by dalefrancis88** [comment]
Ahhh that would do it :s good catch mate
