### ISSUE TITLE
JWT exp is always expired when created (daylight saving problem?)

### ISSUE THREAD

**Issue by wilson85** [IdentityServer/IdentityServer3#3275]
When my JWT token gets created, the exp field is always set to the current date/time.  If i increase the clients 'AccessTokenLifetime' then this value increases but it's always minus 1 hour.

Logically I think it must be related to daylight saving time (in England we're on +1), but i'm struggling to figure out how i can overcome this issue.  Is this a know issue, or do you have any advice on what I could check?

**Comment by lehne** [comment]
Perhaps the token is UTC?

**Comment by wilson85** [comment]
I'm using app. UseOpenIdConnectAuthentication to validate the tokens. Both servers are in the same time zone.

**Comment by wilson85** [comment]
Actually it's bearer tokens so I'm using UseIdentityServerBearerTokenAuthentication

**Comment by lehne** [comment]
I think the token just has an 'ExpiresIn' field in the response. You need to calculate the expiration from that when you receive it.
`
nid.AddClaim(new Claim("expires_at", DateTimeOffset.Now.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToString()));`

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
