### ISSUE TITLE
Resource Owner Flow: Client Secret Required?

### ISSUE THREAD

**Issue by lehne** [IdentityServer/IdentityServer3#3276]
### Question / Issue
I am using the resource owner flow in a console application. Is the client secret required? I do not want to use a client secret as it would not actually be secret (application will be installed on many users' computers). If not, how do I disable it?
When I try the following, I get an "invalid_client" error because a secret is expected (see log):
```
var client = new TokenClient(
                tokenEndpoint,
                "myClient");

var tokenResponse = await client.RequestResourceOwnerPasswordAsync(
	userName: user,
	password: pw,
	scope: "someAPI"
	);
```

### Relevant parts of the log file

```
2016-10-05 12:42:14.071 -04:00 [Information] Start token request
2016-10-05 12:42:14.247 -04:00 [Information] Parser found no secret
2016-10-05 12:42:14.262 -04:00 [Information] No client secret found
2016-10-05 12:42:14.276 -04:00 [Information] End token request
2016-10-05 12:42:14.328 -04:00 [Information] Returning error: invalid_client
```

**Comment by leastprivilege** [comment]
The client secret is required in IdentityServer3 - we changed this in 4.

The spec says that in this cases you shouldn't treat the secret as secret.

**Comment by lehne** [comment]
Ok makes sense. Thank you! I noticed it was not required in the spec for this case (and in the TokenClient overloads) so was confused, but this makes sense.
