### ISSUE TITLE
Custom login view to determine idp when username typed in

### ISSUE THREAD

**Issue by dahlsailrunner** [IdentityServer/IdentityServer3#3277]
Hi - 
I have a question regarding a set of multi-tenant applications I'm working on -- all of which I'd like to go through identity server.

Currently on one of the apps (an Id Srv Client - trusted resource) I have a login screen with username / pwd fields.  When the user types their username, I do an API call to backend store to determine their IDP.  If it's not a local account (i.e. it's like Azure Ad or Okta or something), I create an authorize url and redirect them to Id Srv with IDP set - which gets them where they need to be to authenticate.  If it *is* a local account, I wait for them to type their password and then do an authorize post with the RequestResourceOwnerPasswordAsync -- so the user in both cases never really sees Identity Server.

But now I have like 4-5 (or more) additional apps I need to write, and I'd like to just centralize this type of idp-determining right onto a custom login page of id srv. 

So the user would come in to identity server with a generic authorize url -- with redirect uri -- and then type a user name.  I would like to determine the idp at that point and reconstruct the authorize url with the idp but preserving everything else (like redirect uri / nonce / etc).

I've got some code that tries to look at the signin message:
var msg = HttpContext.Current.Request.GetOwinContext().Environment.GetSignInMessage();
var env = HttpContext.Current.Request.GetOwinContext().Environment;

msg seems to always be null.  
the "env" has a sign in message cookie but it appears encoded in some way.  

Do you have any suggestions on how to do what I'm doing?  I won't know the idp until the user provides their name -- then I have to look it up.

NOTE:  This looks like issue #1940 and I've reviewed the docs but still couldn't see an answer.  Sorry if I've missed something.

Thanks in advance - 
Erik

**Comment by brockallen** [comment]
Might be the signin param bug -- make sure you pass the right signin id param.

**Comment by dahlsailrunner** [comment]
I think I'm on the hunt now.  I was unsure about how to get the signin id param that you mentioned, but a little work in the debugger pointed me to the query string param.  

So (in case anyone else comes looking) this code now works and shows me the sign in message object:
`var signinid = HttpContext.Current.Request.QueryString["signin"];
            var msg = HttpContext.Current.Request.GetOwinContext().Environment.GetSignInMessage(signinid);`

Thanks for pointing me in the right direction.

**Comment by brockallen** [comment]
Just for reference: https://github.com/IdentityServer/IdentityServer3/issues/2682

**Comment by dahlsailrunner** [comment]
Awesome, and thanks again.  Really appreciate it.

**Comment by dahlsailrunner** [comment]
Should have thought through next steps a little more.  So I've got a custom login view using the IViewService (not much modified from your sample outside of some styling) and a user will type in a username in the "local login" box.  

When they type their username and exit, I will see via API whether they should be using an external idp.  So let's say my API returns "idp-okta".  How can I basically refresh the page with ALL of the same info except also having &idp=idp-okta in the authorize query string?  The API call is made from javascript onblur of the username.  I don't really have the owin context on the client side html -- and am not sure about including things like redirect uri, state, nonce in hidden fields or something.

Is there a better approach I should be taking?  I *don't* want them to think that they should be typing a pwd if they happen to use an external idp -- but I also can't just show a list of external idp's for them to pick from.

**Comment by dahlsailrunner** [comment]
Ok so I figured this out -- at least one way to get it done.  Here are some notes for the curious.

Turned out I didn't look carefully enough at the view service method I was looking at for starters.  The SignInMessage is an input param to the method -- so I didn't even *need* to use the OwinEnvironment extensions to get it.  Already there.  Sheesh.

I added a new string param to the custom view "Render" method for the authorize Url (default = null) and then passed message.ReturnUrl to the method for the login view.  Then modified the Render function to include that as one of the fields in the dynamic object created and passed into the Replace method.  Then modified my view to have a hidden field containing the return url - and then just append &acr_values=idp:<newidp> via jquery and redirect if I find a different idp for the user.

```csharp
public virtual async Task<Stream> Login(LoginViewModel model, SignInMessage message)
        {
            var client = await clientStore.FindClientByIdAsync(message.ClientId);
            var name = client != null ? client.ClientName : null;
            return await Render(model, "login", name, message.ReturnUrl);
        }
 protected virtual Task<Stream> Render(CommonViewModel model, string page, string clientName = null, string authorizeUrl = null)
        {
            var json = Newtonsoft.Json.JsonConvert.SerializeObject(model, Newtonsoft.Json.Formatting.None, new Newtonsoft.Json.JsonSerializerSettings() { ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver() });

            string html = LoadHtml(page);
            html = Replace(html, new
            {
                siteName = Microsoft.Security.Application.Encoder.HtmlEncode(model.SiteName),                
                model = Microsoft.Security.Application.Encoder.HtmlEncode(json),
                authorizeUrl = authorizeUrl,
                clientName = clientName
            });

            return Task.FromResult(StringToStream(html));
        }

```
And then the js function I call in onblur for the username field:
```javascript
function checkUserName() {       
        var authUrl = $('#authUrl').val();
        var usernm = $('#username').val();

        // real api call would be here..... for the conditional
        if (usernm === 'edahl') {
            authUrl += "&acr_values=idp:AzureAD";
            window.location.href(authUrl);
        }
    }

```
HTH
