### ISSUE TITLE
Integrating Identity Server 3.0 with SharePoint 2013

### ISSUE THREAD

**Issue by viveksahay** [IdentityServer/IdentityServer3#3278]
### Question / Issue

Can anyone provide guidance on how to inetegrate identity server with SharePoint 2013 on-prem website. Currently we are using form based authentication.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest
