### ISSUE TITLE
SSO and Multiple Portals

### ISSUE THREAD

**Issue by DoubleExposure** [IdentityServer/IdentityServer3#3283]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
So, like many here I have a need to authenticate a user against multiple portals. We are creating custom portals for each of our corporate customers. If user A is accessing a portal for Company A then how does the UserService handle knowing which portal to authenticate against? I want only one instance of IdentityServer3 to validate the user.
I suspect that I need to pass the name of the Domain name to the UserService. But how and where is this coding change best implemented? These portals are unique to each of our customers. Also, how is the MembershipRoot user management used for multi tenant? Are there examples for managing these users in a MultiTenant architecture?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Quick hint: look at our docs on acr_values for the authorization endpoint.

For future questions about general topics: 

To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
