### ISSUE TITLE
Question: how can I get response_type?

### ISSUE THREAD

**Issue by CrescentFresh** [IdentityServer/IdentityServer3#3284]
In my custom `IUserService` I would like to know what the response_type (id_token, id_token token, code, etc, etc) the client is asking for. It's a long story I'll avoid describing here. In a nutshell I'd like to fork some logic based on whether the client is logging in a user for the purpose of accessing api resources vs purely for knowing identity only (response_type=id_token).

I have injected `OwinEnvironmentService` into my IUserService. Is there an OWIN extension method that gets the originating request url that was made to the authorization endpoint which contains the response_type?

**Comment by brockallen** [comment]
That's in the return url in the signin message (assuming the login request came from the authorization endpoint).

**Comment by CrescentFresh** [comment]
Thanks Brock Allen!
