### ISSUE TITLE
Custom Claim Type from ADFS

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3285]
I have a couple custom claims that I get from adfs. 
Every one of the standard claims types converts to a short name except my custom claims.
example: 
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"  becomes "email"
but
"http://schemas.companyname.com/claims/CustomClaim"  does not become "custom_claim" or something to that effect.

How can I get these to be work the same, either they both use short names or neither do. I think I would prefer the short name to be used in both cases.

**Comment by brockallen** [comment]
We have an external claims filter you can add to DI. https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html

**Comment by jheckathorn** [comment]
I have my current implementation below. It seems to remove any existing filtering. Is there a way to extend the existing filter so that I can add to it?

factory.ExternalClaimsFilter = new Registration<IExternalClaimsFilter,CustomExternalClamsFilter>();

class CustomExternalClamsFilter : IExternalClaimsFilter
    {
        public IEnumerable<Claim> Filter(string provider, IEnumerable<Claim> claims)
        {
            var externalClams = claims.ToList();

            if (provider == "adfs")
            {
                var claimCustom = externalClams.FirstOrDefault(x => x.Type == "http://schemas.companyname.com/claims/CustomClaim");

                if (claimCustom  != null)
                {
                    externalClams.Remove(claimCustom);
                    externalClams.Add(new Claim("company_id", claimCustom.Value));
                }
            }
            return externalClams;
        }
    }

**Comment by jheckathorn** [comment]
I have made the following changes but I'm still getting the same result. 

factory.ExternalClaimsFilter = new Registration();

class CustomExternalClamsFilter : IExternalClaimsFilter
{
	public CustomExternalClamsFilter() : this("adfs")
	{
	}

	public CustomExternalClamsFilter(string provider) : base(provider)
	{
	}
		
	protected override IEnumerable<Claim> TransformClaims(IEnumerable<Claim> claims)
	{
		var externalClams = claims.ToList();

		var claimCustom = externalClams.FirstOrDefault(x => x.Type == "http://schemas.companyname.com/claims/CustomClaim");

		if (claimCustom  != null)
		{
			externalClams.Remove(claimCustom);
			externalClams.Add(new Claim("company_id", claimCustom.Value));
		}
			
        return externalClams;
    }
}

**Comment by brockallen** [comment]
You will have to add your claim filter into this list like this:

```
new Registration<IExternalClaimsFilter>(resolver =>
            {
                var aggregateFilter = new AggregateExternalClaimsFilter(
                    new NormalizingClaimsFilter(),
                    new FacebookClaimsFilter(),
                    new TwitterClaimsFilter(),
                    new YourClaimFilter()
                );

                return aggregateFilter;
            });
```

**Comment by jheckathorn** [comment]
Ah, got it. It works now. Thank you!
