### ISSUE TITLE
Prevent Login page from brute force attack

### ISSUE THREAD

**Issue by sadeghhp** [IdentityServer/IdentityServer3#3286]
how to use max login failed mechanism to prevent attack in login page ?
is there any way to use recaptcha in it ?
usermanager MaxFailedAccessAttemptsBeforeLockout not work !

**Comment by brockallen** [comment]
This would be implemented by your identity management library.

**Comment by sadeghhp** [comment]
but i think login page of identityserver "_/core/login?signin_" can be a target of brute force! because it has not a mechanism to protect attacks

**Comment by brockallen** [comment]
You're absolutely right. So when you implement your user service you should protect against those brute force attacks. IdentityServer does not implement the password validation itself -- you need to pick a library for that.

**Comment by totpero** [comment]
how @brockallen say you can use library like this https://github.com/stefanprodan/WebApiThrottle or can use [Using Dynamic IP Restrictions](https://www.iis.net/learn/manage/configuring-security/using-dynamic-ip-restrictions) from IIS.

**Comment by brockallen** [comment]
Those could be used in addition to a identity management library. As for the library, how about ASP.NET Identity v2.x? It contains the brute force checking code.
