### ISSUE TITLE
How to do a three legged OAuth with IdentityServer3?

### ISSUE THREAD

**Issue by gautamdhameja** [IdentityServer/IdentityServer3#3287]
### Question
We have the following scenario:
IdentityServer3 as the auth service and following are registered clients with it,
An MVC app - doing open id connect auth 
A Web API (api1)
Another Web API (api2)
Now, the requirement is to access api2 through api1 through the MVC app and the catch is that the api2 can only be accessed via api1 and mvc app only knows about api1. So, basically we are first getting logged in via the mvc app and getting a access token with claims for the user. Now we are using this access token to access the api1 also, as the mvc app has the api1 in the scopes. But, now when we access api2 via api1, using client creds flow, then these user claims are not available in api2 (may be because api2 scope is not known to mvc app which is being used for user auth).
Following flow diagram depicts the flow I tried to explain above, 
![snip_20161009005421](https://cloud.githubusercontent.com/assets/5374052/19215418/04df3f2e-8dbb-11e6-9108-2d79f1aeb15c.png)

Note: api2 can be accessed only by api1 and for the rest of the world it doesn't exist. however, we need the user claims of the user who sent the request to the mvc app.
**Is there a way to make this possible?**

**Comment by gautamdhameja** [comment]
Awesome. Thanks, @brockallen. 
I will give it a try and will update the thread with the result or any follow-up questions (if needed).

**Comment by olonga** [comment]
How can I secure api2, so it can only be accessed via act-as custom grant and not directly with an access token?

**Comment by leastprivilege** [comment]
use different scopes
