### ISSUE TITLE
Partial Login with external redirect

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#3288]
Hello,

after reading the partial login docs and multiple issues here, it's not fully clear to me if it's possible to show an external page not hosted with the identity server while doing partial login. All examples I found redirected to a controller method within the hosted application. There I have all the owin extensions and it's easy to make the partial login work.

My use case is to login at identity server, but accept EULA on a different page on a different host and continue the login process ony if EULA was accepted.

**Comment by leastprivilege** [comment]
All pages must run in the idsrv pipeline. IOW no external pages. 






On Mon, Oct 10, 2016 at 9:25 AM +0200, "senj" <notifications@github.com> wrote:












Hello,



after reading the partial login docs and multiple issues here, it's not fully clear to me if it's possible to show an external page not hosted with the identity server while doing partial login. All examples I found redirected to a controller method within the hosted application. There I have all the owin extensions and it's easy to make the partial login work.



My use case is to login at identity server, but accept EULA on a different page on a different host and continue the login process ony if EULA was accepted.

**Comment by senj** [comment]
ok, thanks
