### ISSUE TITLE
IdentityProviderRestrictions  - For clients 

### ISSUE THREAD

**Issue by smuthiya** [IdentityServer/IdentityServer3#3289]
I have multiple external identity provider configured in my IdentityServer3. (Such as Windows Authentication, Google etc) 
Now I am trying to configure a client in STS and want to configure a client to use only specific External IdP for this I am using 
Client.IdentityProviderRestrictions which is List<string>

Now my question is what string should go this this list, say for example if I want to enable  a one specific External IdP and from where I will get this string?

**Comment by leastprivilege** [comment]
The `AuthenticationType` of the external idp as configured in startup.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by smuthiya** [comment]
It works... Thanks for answering the question.
