### ISSUE TITLE
Requests for id_token response type must include identity scopes 

### ISSUE THREAD

**Issue by TarunBabbar** [IdentityServer/IdentityServer3#3290]
Hi Guys,

I am facing an issue where-in I am trying to call IdentityServer mentioned in AuthorizeEndpoint url. When I call CreateAuthorizeUrl with the below parameters, I get the error - **"Requests for id_token response type must include identity scopes"**

Could you please help me understood what might be the issue? Thanks in advance !!
~Tarun

        [HttpPost]
        public ActionResult Index(string scopes)
        {
            var state = Guid.NewGuid().ToString("N");
            var nonce = Guid.NewGuid().ToString("N");
            SetTempState(state, nonce);
            var codeChallenge = Guid.NewGuid().ToString().ToCodeChallenge();
            var request = new AuthorizeRequest(Constants.AuthorizeEndpoint);
            var url = request.CreateAuthorizeUrl(
                clientId: "myclientid",
                redirectUri: "http://localhost:11716/callback",
                responseType: "code id_token",
                scope: "openid profile email",
                state: state,
                responseMode: "form_post",
                nonce: nonce,
                codeChallenge: codeChallenge,
                codeChallengeMethod: "S256"
                );

            return Redirect(url);
        }

**Comment by brockallen** [comment]
What scopes are configured in IdSvr?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
