### ISSUE TITLE
Login success provide access token in hash url instead of query string

### ISSUE THREAD

**Issue by Sonic3R** [IdentityServer/IdentityServer3#3291]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi,

I setup identity server in my MVC project...

I have the following method:

```
public string GetLoginUrl( string redirectUrl )
      {
         if( string.IsNullOrWhiteSpace( redirectUrl ) ) {
            throw new ArgumentNullException( nameof( redirectUrl ) );
         }

         AuthorizeRequest authorizeRequest = new AuthorizeRequest("http://test.com/identity/connect/authorize");
         string state = Guid.NewGuid().ToString( "N" );
         string nonce = Guid.NewGuid().ToString( "N" );

         return authorizeRequest.CreateAuthorizeUrl( "aclientid", OidcConstants.ResponseTypes.Token,
            "myscope", redirectUrl, state, nonce );
     }
```

Let's assume that redirectUrl is index page of "http://test.com".

After success login, I have been redirected to "http://test.com/#access_token=blabla.blabla.blabla&token_type=bearer...."

There is a setting or way to have query string instead of above hash url ?

I mean, I want like "http://test.com/?access_token=blabla.blabla.blabla&token_type=bearer...."

**Comment by brockallen** [comment]
This is covered in the spec.

**Comment by Sonic3R** [comment]
If I set response_mode=query, throws and exception that is not valid value for it.

I tried response_mode=form_post, but I don't have query string
