### ISSUE TITLE
issue with JwtSecurityTokenHandler.InboundClaimFilter.Clear();

### ISSUE THREAD

**Issue by ashuthinks** [IdentityServer/IdentityServer3#3293]
I have got an error to following code -

        //This is necessary because Microsoft renames claims off spec
        var jwtSecurityTokenHandler = new JwtSecurityTokenHandler();
        jwtSecurityTokenHandler.InboundClaimTypeMap.Clear();

        // register bearer token authentication
        appBuilder.UseIdentityServerBearerTokenAuthentication(
            new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://test.wz.test.com/test",

                ValidationMode = ValidationMode.Local,

                RequiredScopes = new[] { "test" },
            });
build error is -
Severity Code Description Project File Line Suppression State
Error CS0176 Member 'JwtSecurityTokenHandler.InboundClaimTypeMap' cannot be accessed with an instance reference; qualify it with a type name instead

**Comment by brockallen** [comment]
It's static

**Comment by ashuthinks** [comment]
yes my bad , but in newer version its not, thanks
