### ISSUE TITLE
Creating implicit Flow response

### ISSUE THREAD

**Issue by nkdev89** [IdentityServer/IdentityServer3#3295]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi , 

 i'm getting strange problem after authenticating the user from active directory , After the consent screen, the page continuous getting refresh 
and the  logs in the identity server host are like below 

### Relevant parts of the log file

17:11 [INF] <>
 Creating implicit Flow response.
17:11 [INF] <>
  Getting claims for identity token for subject : HHHHHH
17:11 [INF] <>
   Posting to https://localhost:44321/

not sure what is going wrong  , Please help me with this. 

My client is just a mvc app , which uses identity server for authorization against the active directory 

```
<log goes here>
```

**Comment by nkdev89** [comment]
i'm getting the above log on continuous basis

**Comment by leastprivilege** [comment]
Sorry - not enough information to diagnose this issue.

**Comment by nkdev89** [comment]
i have fixed the issue, The actual problem was i had the client app url in http and the registered url was in Https. So the system was trying to post to Https which is not available, After fixing it , it worked .
