### ISSUE TITLE
useopenidconnectauthentication and usecookieauthentication

### ISSUE THREAD

**Issue by dimsedane** [IdentityServer/IdentityServer3#3296]
# Question

I also asked this question on stackoverflow: http://stackoverflow.com/questions/39991573/identityserver-useopenidconnectauthentication-and-usecookieauthentication-in-asp 

I have a large-ish enterprise web application that consists of multiple actual ASP.NET mvc/web api websites.

I have the authentication setup for the MVC websites very similar to the sample here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MVC%20Authentication

I have a scenario where the flow is not what I am expecting and I am hoping someone can tell my if I am doing something wrong or if my expectations are wrong.

Lets consider two web applications using the same identityserver. Lets call them App1 and App2.

When a user first arrives at App1 they are redirected to the identityserver login screen where they login and are they redirected back to App1.

When they go to the App2, they are also redirected to the identityserver, but since they are already logged in through the identity server they are sent back via the "Please Wait" screen.

So far so good, exactly what I would expect. But when the user goes back to App1 I expect that they are already authorized through a cookie on App1, but it redirects them to the identityserver and back through the "Please Wait" screen. Is that expected or is something wrong in my setup?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

**Comment by dimsedane** [comment]
I have tried stackoverflow without luck, and I was hoping this was a place where I could find someone who is familiar with IdentityServer since my questions is mostly about my understanding of the interaction between multiple applications using the same identityserver.

**Comment by brockallen** [comment]
If you're interested in professional support, please email identity@leastprivilege.com.
