### ISSUE TITLE
Why IdentityServer CookieAuthenticationOptions saves as session instead of cookie?

### ISSUE THREAD

**Issue by Sonic3R** [IdentityServer/IdentityServer3#3297]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I configured Identitytserver cookie authentication options like (in startup):

```
     app.UseCookieAuthentication( new CookieAuthenticationOptions {
        AuthenticationType = "Cookies",
        ExpireTimeSpan = TimeSpan.FromMinutes( 10 ),
        SlidingExpiration = true,
        CookieHttpOnly = true,
        CookieSecure = CookieSecureOption.SameAsRequest,
        CookiePath = "/",
        CookieName = "TEST_COOKIE"
     } );
```

I don't understand why it is saved as session ? (see below picture). I'm expected to be there a cookie with a lifetime set for 10 minutes.

[Image](https://i.stack.imgur.com/6NgTe.png)

**Comment by brockallen** [comment]
`UseCookieAuthentication` is Microsoft's code, not IdentityServer. Please ask Microsoft support or on SO.
