### ISSUE TITLE
Identity Server Client Credentials with Certificate

### ISSUE THREAD

**Issue by Sudkart** [IdentityServer/IdentityServer3#3299]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi guys,

I am trying to validate my client with client credentials using the certificate.

and in logs i am getting like certificate not found.

and i followed the below link to install certificates.

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Certificates

can you help me out to solve the issue.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
These certificates are unrelated to client credentials.

First of all you need setup proper SSL client certificates - once that is working, you can use them in IdentityServer - 

the clients sample has a cert based client - and the standard client config an example of how to register such a client.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
