### ISSUE TITLE
Identity server AD FS 3.0

### ISSUE THREAD

**Issue by falaky** [IdentityServer/IdentityServer3#3302]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am working on a SharePoint implementation with AD FS /AD as identity provider to internal employees. For external users, (lying outside AD) we plan to use Identity Server.
 
Is there a way to enable both AD FS and Identity server for same SharePoint application?  SharePoint application will provide seamless SSO connectivity for internal users and login for all external users using Identity server.
 
Under the hood, we are using AD FS and WAP for external SharePoint publishing.
 
You reply would be highly appreciated.
 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
