### ISSUE TITLE
404 response when OpenId Connect IDP returns to '.../signin-aad' endpoint in load balanced environment with no client affinity

### ISSUE THREAD

**Issue by davebown** [IdentityServer/IdentityServer3#3304]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)
### Question / Issue

We currently have identity server deployed on an azure web app but would like to deploy it to service fabric. It is currently implemented with a single OOID connect relying party to Azure AD implemented as the 'aad' authentication type.

It works fine in production on azure web apps across multiple nodes but this works on session affinity load balancing. On service fabric only when more than one instance is running, and requests round robin between servers, it does not work and 404 responses are sent when the client is redirected back from the upstream idp after login.

We have implemented custom client, scope and token persistent stores using azure table storage but haven't implemented any custom caching providers, As far as I read they only help with performance and in most instances we find a single request comes back from table storage as fast as it would from redis so haven't been concerned with this.

To make the system work at all we needed to implement a custom data protector which simply encrypts and decrypts using AES256 shared keys and iv. This was implemented because we couldn't get the X509CertificateDataProtector to work as other people have posted elsewhere (sorry i can't find issues references off hand but it's where an error is returned about SHA256 algorithm not being enable on os or something like that).

I'm not sure whether the issue lies with the OpenIdConnectAuthentication provider, the implementation my custom data protector, there is a unit test that proves the encryption works and the keys are guaranteed to be the same across all instances.

No errors are output to the logs when this 404 is generated.

What am i missing is there something generated during signin i need to cache in a distributed way so that all servers can access?

**Comment by davebown** [comment]
To be clear I'm unsure I'd prefer to use X509CertificateDataProtector but I get the following error regardless of what OS i run on:

Unhandled exception
System.NotSupportedException: ID6035: Cannot create a HashAlgorithm with name 'SHA256' using the 'System.Security.Cryptography.RSACryptoServiceProvider' crypto provider. SHA256 may require a minimum platform of Windows Server 2003 and .NET 3.5 SP1. ---> System.Security.Cryptography.CryptographicException: Keyset does not exist

I've tried multiple different certificates including the one that works for signing and I get the same result. So i wrote my own simpler implementation using AES just to try and get round the issue.

I should also say i can't rely on machine keys because it's owin based on service fabric and doesn't use IIS.

**Comment by davebown** [comment]
I don't believe the data protector is the source of the problem i just re-built the in-built one setting the algorithm of the cookie signature transformer to SHA-1. It prevents this throwing the exception above, and removes my totally custom version but alas i still get 404 on the signin endpoint when using multiple nodes.

My implementation of the data protect class is: 

` public class CustomDataProtector : IDataProtector
    {
        readonly RsaEncryptionCookieTransform _encrypt;
        readonly RsaSignatureCookieTransform _sign;

        public CustomDataProtector(X509Certificate2 certificate)
        {
            _encrypt = new RsaEncryptionCookieTransform(certificate);
            _sign = new RsaSignatureCookieTransform(certificate);
            _sign.HashName = "SHA1";         
        }

        public byte[] Protect(byte[] data, string entropy = "")
        {
            var encrypted = _encrypt.Encode(data);
            return _sign.Encode(encrypted);
        }

        public byte[] Unprotect(byte[] data, string entropy = "")
        {
            var validated = _sign.Decode(data);
            return _encrypt.Decode(validated);
        }
    }

My identity server configuration

```
  app.Map("/identity", idSrv =>
            {
                var idSvrFactory = Factory.IdentityServerServiceFactory;

                var viewOptions = new IdentityServer3.Core.Services.Default.DefaultViewServiceOptions();
                //viewOptions.Stylesheets.Add("/Content/Site.css");
                viewOptions.CacheViews = true;
                idSvrFactory.ConfigureDefaultViewService(viewOptions);

                var options = new IdentityServerOptions
                {
                    SiteName = "myday",
                    SigningCertificate = Certificate.GetSigningCertificate(),
                    Factory = idSvrFactory,
                    RequireSsl = false,
                    EnableWelcomePage = false,
                    AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
                    {
                        CookieOptions = new IdentityServer3.Core.Configuration.CookieOptions
                        {
                            SlidingExpiration = true
                        },
                        IdentityProviders = ConfigureAdditionalIdentityProviders,
                        EnablePostSignOutAutoRedirect = true,
                        EnableLocalLogin = false,
                        EnableSignOutPrompt = false
                    },
                    LoggingOptions = new LoggingOptions
                    {
                        EnableHttpLogging = false,
                        EnableWebApiDiagnostics = false,
                        WebApiDiagnosticsIsVerbose = false
                    },
                    PublicOrigin = ProviderFactory.Configuration.GetSetting("IdSrvUrl")?.Replace("/identity", ""),
                    DataProtector = new CustomDataProtector(Certificate.GetSessionEncryptionCertificate())
                };

                idSrv.UseIdentityServer(options);

               //Implemented to handle logout correctly
                idSrv.Map("/signoutcallback", cleanup =>
                {
                    cleanup.Run(async ctx =>
                    {
                        var state = ctx.Request.Cookies["signout_state"];
                        await ctx.Environment.RenderLoggedOutViewAsync(state);
                        ctx.Response.Cookies.Delete("signout_state");
                    });
                });


        public static void ConfigureAdditionalIdentityProviders(IAppBuilder app, string signInAsType)
        {            
            var idHelper = new Security.Identity.AADIdentityServerHelper(300);

            var aad = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "aad",
                Caption = "Azure AD",
                Authority = "https://login.windows.net/common",
                ClientId = ProviderFactory.Configuration.GetSetting("WAADClientId"),
                TokenValidationParameters = new System.IdentityModel.Tokens.TokenValidationParameters
                {
                    ValidateIssuer = false
                },
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    RedirectToIdentityProvider = (context) =>
                    {
                        var urlScheme = context.Request.Scheme;

                        if (context.Request.Headers["X-ARR-SSL"] != null)
                        {
                            urlScheme = "https";
                        }
                 
                        // This ensures that the address used for sign in and sign out is picked up dynamically from the request
                        // this allows you to deploy your app (to Azure Web Sites, for example)without having to change settings
                        // Remember that the base URL of the address used here must be provisioned in Azure AD beforehand.
                        context.ProtocolMessage.RedirectUri = urlScheme + "://" + context.Request.Host + "/identity/signin-aad";

                        if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var signOutMessageId = context.OwinContext.Environment.GetSignOutMessageId();

                            if (signOutMessageId != null)
                            {
                                context.OwinContext.Response.Cookies.Append("signout_state", signOutMessageId);
                                context.ProtocolMessage.PostLogoutRedirectUri = urlScheme + "://" + context.Request.Host + "/identity/signoutcallback";
                            }
                        }
                        else
                        {
                            //If we have a tenant id on the url this means that we want to get the domain hint for the tenant so they by pass HRD.
                            var signInId = context.Request.Query.Get("signin");
                            var signInMessage = context.OwinContext.Request.Environment.GetSignInMessage(signInId);

                            if (signInMessage != null && !string.IsNullOrEmpty(signInMessage.Tenant))
                            {
                                var tenantId = signInMessage.Tenant;

                                if (!string.IsNullOrEmpty(tenantId))
                                {
                                    //Lookup tenant and set domain hint.
                                    var tenant = idHelper.GetTenant(tenantId);

                                    if (tenant != null)
                                    {
                                        context.ProtocolMessage.DomainHint = tenant.AADFederatedDomain;
                                    }
                                }
                            }
                        }

                        return Task.FromResult(0);
                    }
                },
                SignInAsAuthenticationType = signInAsType
            };

            app.UseOpenIdConnectAuthentication(aad);
        }`
```

**Comment by davebown** [comment]
Implementing client affinity does actually resolve this issue but I'm just wondering if it really is necessary to run identity server or the open id connect  middleware with client affinity i.e. the server starting the login process must be the one that finishes. I'd like to avoid this if possible.

**Comment by brockallen** [comment]
If by client affinity, you mean something like sticky sessions, no -- IdentityServer has no server-side state it manages per client/user. We discuss in the docs what's necessary for load balancing: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

**Comment by davebown** [comment]
@brockallen By client affinity I do mean sticky sessions. But if I turn on 'Client affinity' on in our Application Request Routing doing the load balancing and ssl offload the cluster login works, but if I turn it off (the default) then we get the 404 problem described when IDP redirects back to IdentityServer. Is there anything you know of with OpenId Connect middleware you know of that would cause this if it's not in the core of identity server, could it be a cookie decoding problem?

**Comment by leastprivilege** [comment]
Well - that sounds more like a complaint towards the service fabric people. The SHA256 problem sounds like a problem on their end.

We have many installations - IIS and self-hosted that work just fine with load balancing and no affinity.

**Comment by davebown** [comment]
Ok thanks anyway I'll keep tinkering about, for the moment all this looks like an uphill struggle for something I thought would be simple when I set out. I'm considering going for legacy azure cloud services to get the scalability I'd hope to get from service fabric. This isn't my biggest struggle anyway, this is: http://stackoverflow.com/questions/40043198/service-fabric-stateless-identity-server-3-service-fails-under-load

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by browe** [comment]
I'm sure @davebown has found the solution by now, but for others that happen on this same issue (as I did):

The answer to his question is, yes, Owin.OIDC has its own data protector that uses a single-instance only DPAPI implementation by default. Override OpenIdConnectionAuthenticationOptions.StateDataFormat with your own multi-instance implementation to resolve.

**Comment by johnny-chan** [comment]
We've are coming across the same issue when using the recommended X509CertificateDataProtector when trying to host IdentityServer in Service Fabric. 

Unhandled exception
 System.NotSupportedException: ID6035: Cannot create a HashAlgorithm with name 'SHA256' using the 'System.Security.Cryptography.RSACryptoServiceProvider' crypto provider. SHA256 may require a minimum platform of Windows Server 2003 and .NET 3.5 SP1. ---> System.Security.Cryptography.CryptographicException: Keyset does not exist


Did @davebown managed to find a solution with service fabric in the end? I'm not sure what "Override OpenIdConnectionAuthenticationOptions.StateDataFormat with your own multi-instance implementation to resolve" really entails, is there an some sample code available?

**Comment by davebown** [comment]
@johnny-chan We didn't deploy, the only solution I found, to create a CustomDataProtector using SHA1 as the signing algorithm. This was deemed unacceptable so we maintained session affinity at our reverse proxy and use the built-in DPAPI implementation.

The security lowering example that did work: 

On identity server options object assign DataProtector = new CustomDataProtector(Certificate.GetCookieEncryptionCertificate())

The implementation of CustomDataProtector was as follows:

public class CustomDataProtector : IDataProtector
    {
        readonly RsaEncryptionCookieTransform _encrypt;
        readonly RsaSignatureCookieTransform _sign;

        public CustomDataProtector(X509Certificate2 certificate)
        {
            _encrypt = new RsaEncryptionCookieTransform(certificate);
            _sign = new RsaSignatureCookieTransform(certificate);
            _sign.HashName = "SHA1";
        }

        public byte[] Protect(byte[] data, string entropy = "")
        {
            var encrypted = _encrypt.Encode(data);
            return _sign.Encode(encrypted);
        }

        public byte[] Unprotect(byte[] data, string entropy = "")
        {
            var validated = _sign.Decode(data);
            return _encrypt.Decode(validated);
        }
    }

If you find a more secure signing algorithm than SHA1 that works in this configuration let me know. I too am intersted to understand what @browe would recommend.
