### ISSUE TITLE
404 after RenderLoggedOutViewAsync unless all wrapped in app.Map

### ISSUE THREAD

**Issue by gregfiske** [IdentityServer/IdentityServer3#3305]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

I am able to do federated post logout redirects like in the [docs](http://identityserver.github.io/Documentation/docsv2/advanced/federated-post-logout-redirect.html) including the wrapping of all inside app.Map("/core", coreApp => { etc...}).

 If I don't have that map, i.e. I want to just run app.UseIdentityServer and app.Map("/signoutcallback") at the root of startup configuration, the result of calling the signoutcallback is a 404.  The callback is getting run and there aren't any errors in the logs but it seems the pipeline isn't getting re-triggered.

Is there a way to make that work or do they have to be in that "core" map for the logout to finish?

**Comment by brockallen** [comment]
I'd have to see a HTTP trace to have more context. In short, are you sure that the federated callback and/or the redirect uri passed to the upstream IdP is really just ~/signoutcallback?

Also, we added a new flag to the AuthenticationOptions (`EnableAutoCallbackForFederatedSignout`) for it to handle the signout callback for you (so you don't have to add the ~/signoutcallback middleware and render the logged out page). 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AuthenticationOptions.cs#L103

**Comment by gregfiske** [comment]
I recorded it in Fiddler and then exported it to text. Hope that works. See attached.  I scrubbed the id_tokens and changed the names to upstream and downstream to help read it.
[no-core-mapping.txt](https://github.com/IdentityServer/IdentityServer3/files/531354/no-core-mapping.txt) (doesn't work)
[with-core-mapping.txt](https://github.com/IdentityServer/IdentityServer3/files/531355/with-core-mapping.txt) (it works)

The`post_logout_redirect_uri` sent to the upstream IdP was really just the signoutcallback. And the upstream IdP did use that. And using VS debugger, I could verify that the callback was being executed. But the ultimate response from the app was a 404.

Yes, I saw the new `EnableAutoCallbackForFederatedSignout` flag and tried it. The problem I ran into there was that the upstream IdP rejected the presented uri because it didn't exactly match as it had the ?id= query string appended. This is not insurmountable as I control the upstream IdP; it's also Identity Server and I could inject my own `IRedirectUriValidator.`

(By the way, I found I could send the signoutmessageid as "state" with the logout request and then that gets sent back by the external IdP as a query param. That way I don't have to set a "state" cookie like you showed in docs -- the signoutcallback looks for the state param and passes the value through to RenderLoggedOutViewAsync.  But, if the logout page could process a "state" param like it does "id" then that would solve this as well.)

My real question was why it works when it is all inside a Map. The docs include this detail -- I thought initially to emphasize the need to have the callback and IdSvr in the same pipeline.  But when it only started working when I moved all into the core map, then I thought there was subtlety with the Katana pipeline and IdSvr that I didn't understand.

**Comment by brockallen** [comment]
I looked but i can't tell. What does the code look like in startup for your app.Map("/signoutcallback").

**Comment by gregfiske** [comment]
app.Map("/signoutcallback", signOut =>
                {
                    signOut.Run(async ctx =>
                    {
                        var state = ctx.Request.Query["state"];
                        await ctx.Environment.RenderLoggedOutViewAsync(state);
                    });
                });

**Comment by brockallen** [comment]
I'm stumped. Sorry.

**Comment by gregfiske** [comment]
Dang it. Well, thanks anyway, Brock. I'll keep the map - maybe it will come in handy later. And hopefully others will come across this post and see the workarounds.
