### ISSUE TITLE
identity Server vs identity Manager

### ISSUE THREAD

**Issue by subzeko** [IdentityServer/IdentityServer3#3306]
Can I use identity Server vs identity Manager together?
if yes, how can I get started?

We have an existing custom users,roles db. 
* How we can migrate to identity manager?

**Comment by brockallen** [comment]
IdentityServer is unrelated to IdentityManager, and as such this is the wrong repo for this question.

IdentityManager only supports MembershipReboot and ASP.NET Identity. If your database is neither, then IdentityManager won't work for you.
