### ISSUE TITLE
API not picking identity from client credentials token

### ISSUE THREAD

**Issue by CesarD** [IdentityServer/IdentityServer3#3307]
I have configured a solution pretty much like the Simplest OAuth2 Walkthrough: IdSrvr3 + API + Console app that pulls data from API with Client Credentials flow. But the issue I'm having is that when sending the request from console to API, the response is 401 (if I remove the Authorize attribute, the User object in the API controller comes as a WindowsPrincipal instead of as a ClaimsPrincipal, with some info of my domain user logged in the computer). I have enabled logging in IdSrvr3 but it only tells me as far as the token is sent to the console (which so far succeeds), but I have no clue as to how to diagnose whatever is happening in the "validation"? of the token on the API or the injection of the identity into the ASP.NET pipeline.
Now, one of the things I changed from the sample I mentioned is that I configured tokens to be JWT instead of Reference as in the sample, but I also modified the sample to use JWT and a Signing certificate (as in most of the other samples) and it works flawlessly.... Just not in my own project.

Any hint on at least how to diagnose would be great.

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

**Comment by CesarD** [comment]
Ok, I was mainly wondering if there was some way to log whatever the IdentityServer3 middleware is doing on my WebAPI.
Should I try to keep looking for an answer somewhere else or is this something you could give a hint?

**Comment by leastprivilege** [comment]
Well - you could check the docs

https://identityserver.github.io/Documentation/docsv2/consuming/diagnostics.html

**Comment by CesarD** [comment]
Oops, guess I overlooked that when searching confusing it with some kind of alternative for the IdSrvr app instead of the middleware one. Sorry, too many hours into the mess. Thanks, man, I'll have a look.

**Comment by CesarD** [comment]
Ok, that worked to allowed me to trace what was happening.
Just so any other looking for this know: the middleware was failing to validate the token. This was due to a trust issue with the HTTPS certificate because I had my IdSrvr on IIS Express and the default setting is SSLRequired = true. I have yet to try, but I guess switching to local IIS with a self-signed certificate should fix it (or just switch SSLRequired = false while in development).

Thanks for the hint on the diagnostics link for the middleware, @leastprivilege.
