### ISSUE TITLE
Incognito nonce cookie problem

### ISSUE THREAD

**Issue by be4i** [IdentityServer/IdentityServer3#3310]
Hello,

for some unknown reason (for me) when the openid connect middleware makes the request for the idsrv for the very first time in incognito mode (chrome and firefox tested) the nonce cookie is missing so when the idsrv returns the response the user gets "IDX10311 nonce is null" error.Any ideas how to fix it ?

**Comment by brockallen** [comment]
That's a question for Microsoft.

**Comment by be4i** [comment]
Can you point me where i can post the issue please ?

**Comment by brockallen** [comment]
https://katanaproject.codeplex.com/workitem/list/basic

**Comment by be4i** [comment]
Thank you.
