### ISSUE TITLE
Facebook as an OIDC Provider is not supported yet.

### ISSUE THREAD

**Issue by olonga** [IdentityServer/IdentityServer3#3312]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
When I add Facebook as as External idp in ids using the following, I get this message from ids: "w3wp.exe Warning: 0 : 2016-10-14 15:15:11.278 -05:00 [Warning] user service returned error message: "Facebook as an OIDC Provider is not supported yet."
pp.UseFacebookAuthentication(new FacebookAuthenticationOptions
                {
                    SignInAsAuthenticationType = signInAsType,
                    AuthenticationType = client.AuthenticationType,
                    Caption = client.Caption,

                    AppId = "xxxx",
                    AppSecret = "yyyy",
                });

So am I not able to integrate ids with facebook?
### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
That error is not coming from IdentityServer.

**Comment by olonga** [comment]
Ok. I am able to integrate other ext idps such as Google, twitter, linkedIn without any problems except fb. I am not sure how to move forward here. Could you give me some hints here on hiw to troubleshoot this?  Using katana fb middleware.

**Comment by brockallen** [comment]
Try it from a stand alone MVC project and get it working there first.

**Comment by olonga** [comment]
Apologize. It was a custom error from another project.
