### ISSUE TITLE
Code Issue in AuthenticationController

### ISSUE THREAD

**Issue by cchongchong** [IdentityServer/IdentityServer3#3313]
See this line: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/AuthenticationController.cs#L788

I think we should remove "rememberMe != false &&", right? 
"
rememberMe == true ||
                    (rememberMe != false && this.options.AuthenticationOptions.CookieOptions.IsPersistent)
"

With current code, Options.AuthenticationOptions.CookieOptions.IsPersistent will never work.

**Comment by brockallen** [comment]
This allows the end user to override the setting.

**Comment by cchongchong** [comment]
@brockallen Thank you Brock, I missed the second part, the "RememberMe" is nullable, sorry about that.
