### ISSUE TITLE
[Question] access to resource scopes/claims from client side in implicit flow

### ISSUE THREAD

**Issue by blinky9** [IdentityServer/IdentityServer3#3314]
Hi, i know that resource scopes are designed for access to API resources, and in the client side, we can access to identity scopes/claims by using identity token (or UserInfoClient).
In the Implicit flow, Is it possible to access resource scopes/claims in the client side (along identity scopes)?

**Comment by brockallen** [comment]
An implicit client can request an access token for scopes, yes. Check the spec for more info.

**Comment by blinky9** [comment]
Thanks for answer.
Do you mean that use 'JwtSecurityTokenHandler.ValidateToken()' to retrieve claims from access token or there is better solution?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
