### ISSUE TITLE
Issue while fetching response

### ISSUE THREAD

**Issue by TarunBabbar** [IdentityServer/IdentityServer3#3315]
Hello All,

I saw a lot of samples on github which are explaining how to get the access token using MVC and passing it to WebAPI or WCF Service. 
To avoid testing in MVC, since I do not want any manual intervention, I am creating a Test Project  where I call the Identity Server's
Authroization/Token End point and validating the response. Below is what I am trying to do:

var url = BaseURL + "connect/authorize" +
                      "?client_id=AuthorizationClientId&response_type=code&redirect_uri=http://test" + "&scope=" + "read" +
                      "&state=b19235dec94b493eb7ace0e210d5649a&nonce=47c7b626ba6548babb5205827f81a4f0&response_mode=form_post";

```
        HttpWebRequest webRequest = (HttpWebRequest)WebRequest.CreateHttp(new Uri(url));

        webRequest.CookieContainer = new CookieContainer();
        webRequest.KeepAlive = true;
        webRequest.Method = "GET";
        webRequest.UseDefaultCredentials = true;
        webRequest.Credentials = CredentialCache.DefaultNetworkCredentials;

        HttpWebResponse webResponse = (HttpWebResponse)webRequest.GetResponse();
        AuthorizeResponse authorizeResponse = new AuthorizeResponse(webResponse.ResponseUri.ToString()); 
```

I am getting webResponse.ResponseUri as below 
[IdentityServerEndPoint]?wtrealm=urn%3aidsrv3&wctx=WsFedOwinState%3dIKXAquOTrgdJYsvUcSpYwYIU9nUo6SrHI1nh-5eK6A3yCKNRgaOZWdr0BQ0r8EYhR4iXer15qgzS4dSmeNc2RC2dBdgpIskHfDPTK0EhRoyta7gVtwRaGQtVd-LXApvosGur7v1cTHR0ZVlX9rrlNxgtBaH6W-z8N8DWRMI-QgFk0jT84qvE7YnD5lIew8hRaMnee8_CqanzszejsV-TzgbZ6B_gTA6q2dr3AVibKgEtY_AEKVc1MY8qRr2X54dd&wa=wsignin1.0

I am unable to understand why I am not getting any access_code here.

Can anybody help me, if I'm doing any mistake here? Or is there any alternative solution you could think of?
I highly appreciate your feedback, Thanks a lot in advance,

Cheers,
Tarun !

**Comment by brockallen** [comment]
That last URL looks like a ws-fed signin request. Looks like your first request to IdSvr is being redirected to an upstream ws-fed IdP.

**Comment by TarunBabbar** [comment]
Yes I too think the same, but not sure why it is happening. Could you please correct the code?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
