### ISSUE TITLE
Clear Tokens on EndSession

### ISSUE THREAD

**Issue by NovakSavic** [IdentityServer/IdentityServer3#3318]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is there a way to Clear Tokens on EndSession?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by NovakSavic** [comment]
Is there possibility to automatically clear tokens for a given client when user performs end session?
Or i have to manually clear them by calling token revocation endpoint (yes I'm working with reference tokens for this scenario)?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
