### ISSUE TITLE
How to display an external page instead of Identity Server general error page?

### ISSUE THREAD

**Issue by SuyalK** [IdentityServer/IdentityServer3#3319]
I implemented IViewService interface to display custom error page.
But for some cases I want to display an external error page.
e.g. if response_mode value is wrong in authorize endpoint, I want to display error page of the client application instead of Identity Server error page.
How can I achieve this inside custom view service's Error method?

**Comment by BruceHunter** [comment]
One thought that comes to mind is to Render your own error.html template and add an iframe to show it?  There may be another way, just my first thought. Another thought would be to have javascript fire on load of the page that redirects to another uri ? The templates render via server side.

**Comment by SuyalK** [comment]
Thanks Bruce!
As suggested by you, now I am redirecting to another URL on load of error.html page using javascript.
But I want to pass this url from server side.
So I am passing this information in Custom property of view model.

    model.Custom = new
    {
        url = "www.abc.com"
    };

But at view, I am unable to access this value.
![custom object error](https://cloud.githubusercontent.com/assets/21952442/19621886/cbf99c7c-98b9-11e6-8940-6936894fee24.jpg)

**Comment by SuyalK** [comment]
I noticed in the developer tool that there is some problem in loading AngularJS.
![angular js error](https://cloud.githubusercontent.com/assets/21952442/19621946/71cbb40e-98bb-11e6-9f65-d32b39ccb8c6.jpg)

**Comment by SuyalK** [comment]
I found the issue. ng-csp directive was missing in the <html> tag of error.html page.

![error page missing ng-csp](https://cloud.githubusercontent.com/assets/21952442/20369106/ad144238-ac70-11e6-9117-33a123996a3c.jpg)

After adding ng-csp directive is working fine:
<html ng-app="app" ng-csp ng-controller="LayoutCtrl">
