### ISSUE TITLE
ASP.NET SupportsUserSecurityStamp Login page shows model.currentUser when logged out.

### ISSUE THREAD

**Issue by BruceHunter** [IdentityServer/IdentityServer3#3320]
### Issue

layout.html - model.currentUser is populated when ASP.NET Identity Triggers SupportsUserSecurityStamp logic and a Renew Token triggers logout and clearning of cookies/sessions everywhere.

When you get redirected to the login page, you see the username and logoff under it. Why does this happen and how to fix?

**Comment by BruceHunter** [comment]
I am using the IdentityServer3.AspNetIdentity. I suspect that when InternalOwinExtensions.GetCurrentUserDisplayName is called it returns a currentUser value instead of null. I suspect that this may be a bug somewhere when the active session is cleared it doesn't clear the auth context.

**Comment by BruceHunter** [comment]
Oh, I see this feature in the nav is for the consent page. If the consent feature is off then this section should never actually show anyway! Shouldn't we add ng-show to disable this if that is true?

**Comment by brockallen** [comment]
We issue and maintain our own cookie. If you want to have our cookie ignored when the security stamp is invalidated then use the validation callback we provide on the authentication options.
