### ISSUE TITLE
when hosted in Azure Token Validation fails if Issuer Uri not set explicitly

### ISSUE THREAD

**Issue by tiwari-abhishek** [IdentityServer/IdentityServer3#3321]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I found this issue when hosting the identity server in Azure. In the normal enterprise deployment on IIS, I don't set the issuer Uri and leave it to the identity server to set it.

But somehow things change when hosting the same code in Azure. The token is issued with the name of the Azure website for identity server, but when doing Token Validation, an "invalid issuer" error is returned.

I got past that by explicitly specifying the issuer Url.

Not a big deal but might help someone who faces this when moving to Azure.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Yes, you need to set PublicOrigin: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

**Comment by tiwari-abhishek** [comment]
Thanks I missed that.
