### ISSUE TITLE
Using IdentityServer3 to authentication MVC pages it hosts

### ISSUE THREAD

**Issue by sellotape** [IdentityServer/IdentityServer3#3323]
I have some Admin MVC pages for administering the configuration of my IdentityServer3 instance (Clients, Scopes, Secrets, etc).  They are currently located in an MVC Area on the Identity Server itself, which seems to make sense.  Unsecured, they work perfectly.

I clearly need them to be secured, though, so the first thought was to use IdentityServer itself to authorize users.  Doing so, I have come across a few issues, the main one is that using an AuthenticationType of anything but those in Constants.IdentityServerAuthenticationTypes causes the "External signin" option to appear in the usual login view.  I can see in the code why it does this, so I tried using the values in Constants.IdentityServerAuthenticationTypes as the authenticationType instead.  This does - as expected - hide the External Signin options, but as those are "special values", it seems to cause other issues; e.g. duplicate values in lists that cause exceptions, etc., and at that point I started wondering whether this is the correct thing to be doing.

In my IdentityServer's Startup.cs I'm adding the UseCookieAuthentication() and UseOpenIdConnectAuthentication() middleware to do the authorization.

Is this a reasonable thing to do, or do I need to have a separate website for administering the server's configuration (which would be a pity)?  Are there some magic values I should be using to achieve this?

**Comment by brockallen** [comment]
we have a sample for this: https://github.com/IdentityServer/IdentityServer3.Extensions.Mvc/blob/master/source/IdentityServer3.Extensions.Mvc/IdentityServer3.Extensions.Mvc/Filters/IdentityServerFullLoginAttribute.cs

**Comment by sellotape** [comment]
Thanks for the swift answer.  I'll look at that and comment back.
