### ISSUE TITLE
Client Credentials from within UserService

### ISSUE THREAD

**Issue by CesarD** [IdentityServer/IdentityServer3#3324]
I need to connect to an external API to validate user credentials and get claims for user from within my custom UserService in IdSrvr, but using Client Credentials as if IdentityServer were a client to connect to another service.

What should be the approach?

First thing to come to my mind was to just make an HttpClient instance within UserService to connect to IdentityServer itself and make the request... But I don't know if there's a better/cleaner way.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

**Comment by CesarD** [comment]
Just adding this in case someone stumbles upon this issue, this was the answer:
http://stackoverflow.com/questions/40172034/client-credentials-from-within-userservice-on-identityserver3/40238529#40238529

It would be great to add this info to IdSrvr3 documentation, as I haven't seen it anywhere before.

**Comment by leastprivilege** [comment]
That's documented on the OWIN extensions page.

**Comment by CesarD** [comment]
You're right, I found it there at the bottom... I completely overlooked it as I had no idea owin was related to what I was trying to achieve (before opening this issue, I mean).
