### ISSUE TITLE
Deadlock when registering IAuthenticationSessionValidator

### ISSUE THREAD

**Issue by prochnowc** [IdentityServer/IdentityServer3#3326]
We encounter a deadlock in AuthenticationHandler.OnSendingHeaderCallback as soon as we register an imlementation of IAuthenticationSessionStoreProvider. 

This seems to be caused by this issue: http://katanaproject.codeplex.com/workitem/409
This might be fixed by updating Microsoft.Owin.Security but IdentityServer3 seems to embed this type so updating is not possible.

Are there any workarounds known ?

**Comment by leastprivilege** [comment]
We are embedding the newest version already.

Maybe you need to use the same approach as:

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/Extensions/SyncConfigurationManager.cs

**Comment by prochnowc** [comment]
But we dont use any external authentication (except Cookie which is registered by IdentityServer).
I tracked it the deadlock down to invocation of IAuthenticationSessionStoreProvider.RemoveAsync().
I think if i implement this method synchronous the deadlock will disappear. 
What do you think? will it have negative impact on performance?
How often is RemoveAsync() called? Only on sign out from idsrv?

**Comment by brockallen** [comment]
@prochnowc he meant look at implementing something like the `AsyncHelper`
