### ISSUE TITLE
Nesting token inside token for Act-As in Multi-Hop sample

### ISSUE THREAD

**Issue by CesarD** [IdentityServer/IdentityServer3#3327]
I'm working with the multi-hop sample, but testing a scenario where there could be more than a single hop like in the original sample. One of my coworkers suggested to keep the tokens between hops as a claim so eventually the last service/api could go down the hierarchy decoding each token and thus being able to track from the original user across all the clients involved in the transaction for auditing purposes.

Now, I tried with PreserveAccessToken, but as I saw later in the code, this only adds the token to the ClaimPrincipal, but never gets it into the next token to be generated for the next service.

Is there something I am missing to accomplish this? What would be the correct point in IdSrvr to configure this?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

**Comment by CesarD** [comment]
I was just looking for an extension point inside IdSrvr that would allow me to do this or at least if this is anyhow feasible, since PreserveAccessToken doesn't help me... 
Should I still ask on SO?
Thanks
