### ISSUE TITLE
Using an IdentityServer token as a means to secure access to an ASP.NET website 

### ISSUE THREAD

**Issue by mattbrooks2010** [IdentityServer/IdentityServer3#3329]
### OVERVIEW 

Apologies if I've missed something in the docs or samples. 

A lot of the written material I'm finding discusses using access tokens in order to secure access to APIs. Is it conceptually different if a token is used to secure user access to a website?

I appreciate that, because the user is present, IdentityServer3's SSO support would be an ideal approach for the scenario below. I'm interested in validating the approach in question, or otherwise determine it is unsound.

### SCENARIO

There are two websites SITE-A and SITE-B hosted on different domains.

SITE-A has a user database and uses ASP.NET Identity. It uses cookie authentication and will continue to allow users to sign in directly. 

SITE-B wants to leverage the user database at SITE-A to permit those users to sign-in. 

SITE-B wants to retain its existing login screen and user experience. 

It must be possible for users signed-in to SITE-B to automatically access SITE-A, without having to re-authenticate. The reverse flow is not required. 

Single sign-out is not required. Once authenticated, user sessions will be managed separately in SITE-A and SITE-B. 

Assume IdentityServer3 will be implemented within a new web application that has access to the user database of SITE-A. 

### ASSUMPTIONS

SITE-B represents an OAuth client. 

SITE-B can use resource owner flow to authenticate a user using the IdentityServer3 application, obtaining an ID token and an access token.

SITE-B sends authenticated users to SITE-A with one of the tokens. 

### QUESTIONS

1. Does it make sense for SITE-A to validate the token and issue an authentication cookie to keep the user signed in? Perhaps using `UseIdentityServerBearerTokenAuthentication` and a custom TokenProvider to get the token from HTTP POST data. 
2. Which token should be used at SITE-A: ID token or access token?
3. Does it make sense to model SITE-A as a scope or a client?
4. What might be the pitfalls of this approach — is it even a valid idea?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
