### ISSUE TITLE
How to implement single-sign-on(SSO) between multiple web api site using idsrv3?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#3330]
Recently our company plan to develop mobile app. The mobile app need to call several webapi sites(webapi site 1 and webapi site 2). I using idsrv3 OAuth server for SSO between multiple mvc web site. And that works well.But how to implement single-sign-on(SSO) between multiple web api site using idsrv3? I have think about it and my preconceived steps as below:

1).If not logged in webapi site 1, mobile app ask for login page from idsrv3 using OAuth2 implicit grant type.
2).The user enter username and password, then get the idsrv3 token from idsrv3 server.
3).Mobile app use the idsrv3 token to log in webapi site 1.
4).Webapi site 1 validate the idsrv3 token and get user claims from idsrv3, and then sign in and return webapi site 1 token.
5).From then on, mobile app using webapi site 1 token to access webapi site 1 every time.
6).If Mobile app want to access webapi site 2, imitate step 3 to step 5.

If I do this as above, the mobile app need to save and manage many differenct tokens. Or I should to save the idsrv3 token and user claims to the cache server in step 4, and then different webapi sites can share the idsrv3 token and user claims, and also the mobile app need to save one idsrv3 token only.
Could you please give me some suggestions? Thank you!

**Comment by ranieuwe** [comment]
Consider using a resource scope for the API access. Then include that resource scope in the token for webapi site1. Have the webapi2 check if the scope is there not to determine access (Required scopes). That way you can use the token for site1 for site2.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
