### ISSUE TITLE
How to fire refresh token event?

### ISSUE THREAD

**Issue by Farwell-Liu** [IdentityServer/IdentityServer3#3331]
I use implicit grant type. I know how to get a new access token by refresh token. But I want to know how to fire refresh token event normally? Define a Timer by javascript and check expire time every time span? when it is nearly expired, get a new access token?
Is there any good way to achieve this? Thank you!

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
