### ISSUE TITLE
How can I obtain a token in my identityserver?

### ISSUE THREAD

**Issue by iderossipinncorp** [IdentityServer/IdentityServer3#3333]
I need to obtain a token in my identityserver to call another service. The last one requires a valid token and the authority is the identityserver.
I have tried with this line:

var jwt = await HttpContext.GetOwinContext().Environment.IssueClientToken("clientId", "scopes", 3600);

but it returns:
[**ArgumentNullException: Value cannot be null.
Parameter name: context**]
   Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:0
   Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters) in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:0
   Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType) in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:0
   IdentityServer3.Core.Extensions.InternalOwinExtensions.ResolveDependency(IOwinContext context, Type type) in c:\local\identity\server3\Core\source\Core\Extensions\InternalOwinExtensions.cs:78
   IdentityServer3.Core.Extensions.InternalOwinExtensions.ResolveDependency(IOwinContext context) in c:\local\identity\server3\Core\source\Core\Extensions\InternalOwinExtensions.cs:70
   IdentityServer3.Core.Extensions.OwinEnvironmentExtensions.ResolveDependency(IDictionary`2 env) in c:\local\identity\server3\Core\source\Core\Extensions\OwinEnvironmentExtensions.cs:606
   IdentityServer3.Core.Extensions.<IssueClientToken>d__46.MoveNext() in c:\local\identity\server3\Core\source\Core\Extensions\OwinEnvironmentExtensions.cs:711
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28

could you help me please?

**Comment by johnkors** [comment]
Guesswork: You're trying to use IdentityServers extensionmethod on a OwinEnviroment that's actually outside IdentityServer.

Where are you calling ths dictionary extension method? In your own MVC controller? Or in a IdSrv service?

**Comment by iderossipinncorp** [comment]
I am calling from a MVC controller, it is inside the same project of IdSrv

**Comment by johnkors** [comment]
Ok, 

Allthought that extension method is for _any_ dictionary, I believe that extension method will only work as intended if you're calling it on a owin env dictionary in a request context part of a IdSrv request (authorize / token / userinfo). It's looking for idsrv services in the env dictionary, and those are only registered when in those request pipelines.

You'll probably end up just creating a seperate client for it, even though within the same host of idsrv.

**Comment by iderossipinncorp** [comment]
Thank you @johnkors
