### ISSUE TITLE
Detect ip address in AuthenticateLocalAsync

### ISSUE THREAD

**Issue by olonga** [IdentityServer/IdentityServer3#3334]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We have a requirement that we detect the ip address of the user authenticating to ids in AuthenticateLocalAsync method. LocalAuthenticationContext does not seem to have that info?  Any hints? Thanks.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by johnkors** [comment]
Use the `OwinEnvironmentService`.
