### ISSUE TITLE
How to enforce reenter credentials using IdentityServer3?

### ISSUE THREAD

**Issue by PrashanthShetty** [IdentityServer/IdentityServer3#3336]
I have a use case where user has to reenter credentials before saving any changes to data. How to implement this using IdentityServer3?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
