### ISSUE TITLE
Federated Identity with multiple instances of IdSrv3

### ISSUE THREAD

**Issue by rkpin** [IdentityServer/IdentityServer3#3339]
We are planning to use IdSrv3 to implement STS and would like to know if it is possible to do federated identity between multiple instances of IdSrv3  using OpenID Connect in the following use case scenario.

We have windows application running on a machine with self-contained user database. There will be multiple of these machines running in our environment. The application on these machines make API calls to a central server.  The machines running the application might lose connection to network and to support offline mode we are thinking of running a local STS( build using IdSrv3) on each of these machine and have some kind of chain of trust to central STS. When user logs in to the application, the local STS will authenticate and generate a  token and this token is then passed to Server API calls. The API running on the server should be able to trust this token just like any other token generated by Central STS. 

Is this scenario possible to implement with IdSrv3 using OpenID Connect protocol? if so can you please briefly explain how we can achieve this?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
