### ISSUE TITLE
Identity Server 3 multiple LogoutUris for same client

### ISSUE THREAD

**Issue by mihaivader** [IdentityServer/IdentityServer3#3340]
I have an MVC application which is multi tenant, differentiated by domain name:

```
app.tenant1.com

app.tenant2.com
```

And I have a single Client in IdentityServer (hybrid flow) with
with

```
RedirectUris = [http://app.tenant1.com, http://app.tenant2.com]

PostLogoutRedirectUris = [http://app.tenant1.com, http://app.tenant2.com]
```

But Logout uri only allows for a string value, not a list of strings

`LogoutUri = "http://app.tenant1.com/home/SignoutCleanup";`
My problem is that when I singout from app.tenant2.com I want the LogoutUri to be "http://app.tenant2.com/home/signoutcleanup"

Is there a way of doing this?

Thanks

PS: Is there a way to pass data to IS3 in the SingoutMessage? Similar to how we pass data in the acr_values ?

PPS: I've implemented a CustomEventService and log the user logins. Is there also a way of logging the Log out events ?

Thanks :)

EDIT:

I see that this is the url that's called in order to generate the iframes which in turn call the signout for all apps

`/core/connect/endsessioncallback`

Is there a way to intercept this url and make changes to it's response?

**Comment by brockallen** [comment]
We don't have a way right now to make this more flexible. You'd have to set the domains on the cookie on your end for this to work.
