### ISSUE TITLE
Creating trust relationship between instances of IdentityServer

### ISSUE THREAD

**Issue by CesarD** [IdentityServer/IdentityServer3#3341]
I have been looking for this in the samples but I still can't find it nor figure it out.
Could you please point me to the sample explaining this or maybe some snippet showing it?
Just to be clear: this is NOT between IdSrvr and Facebook/Microsoft/Twitter,etc... This is between 2 (or more) instances of Identity Server 3.

Thanks!

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

**Comment by CesarD** [comment]
There is already one in StackOverflow from 6 months ago that I'm following, but still no concrete answer given:

http://stackoverflow.com/questions/36563927/establishing-trust-between-identityservers

In my particular case I need to establish trust between 2 instances so I can validate from IdSrvr-A that a token generated by IdSrvr-B is valid.

**Comment by sebasunlam** [comment]
same question here, any luck?

**Comment by leastprivilege** [comment]
Brock answered your question - we don't have a sample for your particular scenario - but it is the same technique as the AAD external provider in our sample host.

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L115

In the "other" identityserver you need to register a client that represents the "first" identityserver.

**Comment by CesarD** [comment]
Yeah, that's not my question but one I found while searching before coming here to bug you, guys :)
Brock said there was on the samples, but I couldn't figure a way. 

Now with what you told me, it makes more sense... So, basically, if I get this code on my IdSrvrA

`
var idsrvb = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "idsrvB",
                Caption = "Identity Server B",
                SignInAsAuthenticationType = signInAsType,

                Authority = "https://idserverb",
                ClientId = "clientIdForIdSrvrB",
                ClientSecret = "secretforidsrvrb",
            };
            app.UseOpenIdConnectAuthentication(idsrvb);
`

And create that Client on A, if I get a token from B and perform a `tokenValidator.ValidateToken(tokenFromIdSrvB)` (i.e. in a custom grant), then that should work without problems?

Thanks a lot for all your work on this product. Perhaps if this is the right way I can later collaborate with such a sample for your samples repository?

**Comment by leastprivilege** [comment]
No - thats not how it is working.

For custom grants you need to do the validation yourself (e.g. using the MS JWT handler).

**Comment by CesarD** [comment]
Ok, I got misleaded I guess by the MultiHop sample where you validate the token with the TokenValidator.

So I should have the IdSrvrB certificate public key to validate that their tokens are valid (at least at signature level), and handle that by mean of the JwtSecurityTokenHandler, similarly to what you do inside TokenValidator?

**Comment by leastprivilege** [comment]
yes

**Comment by CesarD** [comment]
Thanks a lot for all your feedback!
