### ISSUE TITLE
Handle external login where `email` is not provided

### ISSUE THREAD

**Issue by dariusdamalakas** [IdentityServer/IdentityServer3#3343]
### Scenario
1. use Facebook social login to try log in. Request `email` info. (scope: `email`)
1. Facebook user unticks 'email', thus 'email' is not returned from external IDP. 
   FYI Same happens if user has only mobile number, but not the email. This configuration is possible with Facebook.
1. Identity server treats this as error and renders error page.  IdentityServer3 code which handles this  [here](https://github.com/IdentityServer/IdentityServer3/blob/93bc6bc9b536146b9e3fa0bed21d77283d07f788/source/Core/Endpoints/AuthenticationController.cs#L345).  Excerpt below:
````
public async Task<IHttpActionResult> LoginExternalCallback(string error = null)
 {         
            ....
            if (error.IsPresent())
            {
                ....
                return RenderErrorPage(String.Format(localizationService.GetMessage(MessageIds.ExternalProviderError), error));
}
````

### Question / Issue

1. Is there a way to detect that user is not willing to or does not have `email` info? I.e. instead of showing a generic error screen, would it be possible for idsrv to step in and perhaps using partial logins to show an extra screen where a user would be asked to enter his email?  
1. Alternatively, would it be possible to redirect back to the app and then the app could take over and display a custom error message `sorry, but we could not get all the data we need, or there was an error`.
1. Any other options of handling this?

### Relevant parts of the log file

```
2016-11-01 08:34:02,780 [35] INFO  IdentityServer3.Core.Endpoints.AuthenticationController [(null)] - Callback invoked from external identity provider
2016-11-01 08:34:02,782 [35] ERROR IdentityServer3.Core.Endpoints.AuthenticationController [(null)] - External identity provider returned error: access_denied
```

### Related / Similar issues
Both of the issues were because `Google+ API` was not enabled. 

1. https://github.com/IdentityServer/IdentityServer3/issues/2167 
1. https://github.com/IdentityServer/IdentityServer3/issues/1666

**Comment by nguyendangdung** [comment]
I currently have the same the issue here. How to customize identityserver3 that allow user enter him email address if the external IdentityProviders not return email claim?

**Comment by leastprivilege** [comment]
Check the docs for partial logins.

**Comment by dariusdamalakas** [comment]
Closing the issue. Will add more details when we've figured out the way to do this.
