### ISSUE TITLE
local and external login / custom login page / and skip home realm discovery

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3345]
I am using the CustomLoginPage as a reference for this.

In my scenario, there are both local and external user. The external users are via ADFS.

As the user hits the PreAuthenticateAsync I want to check to see if the user has already logged in via external login, ADFS, and has already selected predefined home realm. 

As I understand it, when a user selects a realm the first time it is stored in a cookie. 

My first question is how can I check for this so that I can skip straight to the external login?

If the user does not have this cookie, I want to use the custom login to ask for the company they are with and, on submit, use this to either direct the user to local login or, if they are federated with us, get the Whr value for the selected company and direct them to external login. 

I am assuming that using the custom login to do a partial login will accomplish this in part.

My second question is how do I pass the value for Whr on so that the external login can use it?

This is what I have so far.

`public override Task PreAuthenticateAsync(PreAuthenticationContext context)
{
	if (context.SignInMessage.LoginHint == null)
	{    
		var id = _owinContext.Request.Query.Get("signin");
		context.AuthenticateResult = new AuthenticateResult("~/custom/login?id=" + id, (IEnumerable<Claim>)null);
	}

	return Task.FromResult(0);
}`

`[Route("core/custom/login")]
[HttpPost]
public ActionResult Index(string id, string sub, string name, string companyName)
{
	var env = Request.GetOwinContext().Environment;
	//env.IssueLoginCookie(new IdentityServer3.Core.Models.AuthenticatedLogin
	//{
	//    Subject = sub,
	//    Name = name,
	//});

	var msg = env.GetSignInMessage(id);

	var returnUrl = msg.ReturnUrl + "&login_hint=" + Url.Encode("http://sts.someplace.com/adfs/services/trust") + "&idp=adfs";

	//env.RemovePartialLoginCookie();

	return Redirect(returnUrl);
}
`

It is not giving me the desired result.

**Comment by jheckathorn** [comment]
This is what I have so far.


public override Task PreAuthenticateAsync(PreAuthenticationContext context)
{
	if (context.SignInMessage.LoginHint == null)
	{    
		var id = _owinContext.Request.Query.Get("signin");
		context.AuthenticateResult = new AuthenticateResult("~/custom/login?id=" + id, (IEnumerable<Claim>)null);
	}

	return Task.FromResult(0);
}



[Route("core/custom/login")]
[HttpPost]
public ActionResult Index(string id, string sub, string name, string companyName)
{
	var env = Request.GetOwinContext().Environment;
	//env.IssueLoginCookie(new IdentityServer3.Core.Models.AuthenticatedLogin
	//{
	//    Subject = sub,
	//    Name = name,
	//});

	var msg = env.GetSignInMessage(id);

	var returnUrl = msg.ReturnUrl + "&login_hint=" + Url.Encode("http://sts.someplace.com/adfs/services/trust") + "&idp=adfs";

	//env.RemovePartialLoginCookie();

	return Redirect(returnUrl);
}

**Comment by jheckathorn** [comment]
I got a lot closer using the CustomHrd sample but still cannot get the desired result.

I have tried using LoginHint and Tenant to preset the whr value for adfs but neither work. 

        public override async Task PreAuthenticateAsync(PreAuthenticationContext context)
        {
            Debug.WriteLine(">>> PreAuthenticateAsync");

            //if (context.SignInMessage.LoginHint == null)
            //{    
            //    var id = _owinContext.Request.Query.Get("signin");
            //    context.AuthenticateResult = new AuthenticateResult("~/custom/login?id=" + id, (IEnumerable<Claim>)null);
            //}

            var user = await _owinContext.Environment.GetIdentityServerPartialLoginAsync();
            if (user == null)
            {
                // no idp, so do partial login to HRD page
                context.AuthenticateResult = new AuthenticateResult("~/hrd", (IEnumerable<Claim>)null);
            }
            else
            {
                // we have partial login, so look for IdP claim
                var idp_claim = user.Claims.FirstOrDefault(x => x.Type == "idp");
                if (idp_claim == null)
                {
                    context.AuthenticateResult = new AuthenticateResult("Error: no IdP claim found");
                }

                // we have partial login, so look for Tenant claim
                var tenant_claim = user.Claims.FirstOrDefault(x => x.Type == "tenant");
                if (tenant_claim == null)
                {
                    context.AuthenticateResult = new AuthenticateResult("Error: no Tenant claim found");
                }

                context.SignInMessage.IdP = idp_claim.Value;
                context.SignInMessage.Tenant = tenant_claim.Value;
                _owinContext.Environment.RemovePartialLoginCookie();
            }

        }

**Comment by jheckathorn** [comment]
This has me blocked. I could really use some help here. 

The Tenant value doesn't seem to be available to assign to Whr after redirecting to the adfs provider.

                Notifications = new WsFederationAuthenticationNotifications
                {
                    RedirectToIdentityProvider = (context) =>
                    {
                        if (context.ProtocolMessage.IsSignInMessage)
                        {
                            var tenant = context.ProtocolMessage.GetParameter("Tenant");
                            context.ProtocolMessage.Whr = tenant;
                        }

                        return Task.FromResult(0);
                    }
                }

**Comment by jheckathorn** [comment]
I found a solution. That said I would still like to know if this is the correct way to do this or not. I have a feeling there is a better way.

During the Pre Authentication, after using the uses email to determine the correct idp, I add the Tenant value to the owin context environment like so.
_owinContext.Environment.Add("Tenant",tenant);

Then with in the WsFederationAuthenticationOptions under Notifications I add the follow to RedirectToIdentityProvider.
if (context.ProtocolMessage.IsSignInMessage)
{
var tenant = context.OwinContext.Environment["Tenant"].ToString();
context.ProtocolMessage.Whr = tenant;
}

**Comment by jheckathorn** [comment]
I still need a solution to the first question. 

During pre-authentication, how do I check for the cookie that indicates the user has logged in via ADFS before so that I can direct the user straight to the ADFS login?

**Comment by brockallen** [comment]
You can inject the OwinEnvironmentService into your user service to access the OWIN context.
