### ISSUE TITLE
UseJwtBearerAuthentication  versus UseIdentityServerBearerTokenAuthentication

### ISSUE THREAD

**Issue by DoubleExposure** [IdentityServer/IdentityServer3#3346]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

What is the difference between **UseJwtBearerAuthentication** and
**UseIdentityServerBearerTokenAuthentication**?

I know that you can pass a public key to UseJwtBearerAuthentication but does UseIdentityServerBearerTokenAuthentication get the key from the Meta data (automatically) instead of requiring a manual assignment? If it does, then why use the UseJwtBearerAuthentication method at all?

**Comment by leastprivilege** [comment]
We are using Microsoft's middleware internally - but add features like metadata support, introspection and caching.
