### ISSUE TITLE
Problem in joining SSO groups for multi-site IdSrv3 implementation    

### ISSUE THREAD

**Issue by mobashar** [IdentityServer/IdentityServer3#3348]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We have several physical site locations that requires independent STS but using a common UserStore and also needs to have both site-level and cross-site SSO. We can run separate instance of IdSrv3 at each site to server local clients that works fine within a site. However, how do we configure IdSrv3 to talk to each other and share their client registration info so they also serve clients from other sites?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
You don't.

Either you have one for all - or you establish a trust between the sites.

**Comment by mobashar** [comment]
Thanks. We have established AD trust between sites and it is all playing together now.
