### ISSUE TITLE
Adding additonal claims when validating reference token

### ISSUE THREAD

**Issue by NovakSavic** [IdentityServer/IdentityServer3#3350]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is there possibility to include additional claim in response when reference token is validated?
Something similar to GetProfileDataAsync when creating access token...

### Relevant parts of the log file

```
<log goes here>
```

**Comment by NovakSavic** [comment]
It seems that all claims are there with slight difference. Let me elaborate.

 In the case when client token type is access token, I noticed that there is "NameIdentifier" claim that holds subject (unique in IDP). But in the case of reference token, the same thing I get in "sub" claim. 

So, since I have one action filter attribute where I was looking for "NameIdentifier" claim, in the case of reference token, I was not able to get it. But, now since for reference token, I can get the same info through "sub" claim, this is good enough for me.

Why do we have this behavior? Why in the case of access token, subject is set on "NameIdentifier" claim, and in case of reference token, subject is set on "sub" claim?

**Comment by leastprivilege** [comment]
Thank Microsoft for that.

https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/
