### ISSUE TITLE
requesting the "openid" scope for an access token

### ISSUE THREAD

**Issue by stevengopmo** [IdentityServer/IdentityServer3#3351]
the UserInfo endpoint documentation states 

> The UserInfo endpoint can be used to retrieve identity information about a subject. It requires a valid access token with at least the ‘openid’ scope.

but attempting to request an access token like this fails with invalid scope

`https://localhost:44334/core/connect/authorize?client_id=test.security&redirect_uri=https%3A%2F%2Flocalhost%3A44334%2Findex.html&response_type=token&scope=openid&state=6a219d777ba7424e8c1b8581e7edf9dc`

obviously it works if I also include id_token, but based on what I read it seems I should be able to request just the openid scope on access token.

**Comment by leastprivilege** [comment]
`openid` is an OpenID Connect specific scope and only makes sense in the context of an authentication request. That's why you need to request an id_token.
