### ISSUE TITLE
WIF10201: No valid key mapping found for securityToken: 'System.IdentityModel.Tokens.X509SecurityToken' and issuer

### ISSUE THREAD

**Issue by jdfreemanco** [IdentityServer/IdentityServer3#3353]
### Question / Issue
I'm using identity server v3 and the cert expired on the server. I generated a new cert in IIS, installed it in the cert store (trusted people, personal) and set the thumbprint in identity server. I installed the cert in the client application server (trusted people under certs) and updated the thumbprint in the client application. After reading the threads on the same issue I checked and double-checked the thumbprint and issuer name in identity server and client application - they both match in the identity server config and the client app config. 

However I'm still getting this error in the **client application**, I've run out of things to try.

Is there anything else I can do?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest
