### ISSUE TITLE
Javascript / Angular 2 Clients Tutorial

### ISSUE THREAD

**Issue by Gentlehag** [IdentityServer/IdentityServer3#3354]
This question is little to broad for stackoverflow thats why i'm posting it here.

is there a tutorial / documentation about bestpractices when having a javascript SPA application and how to connect it best to identity server? (With implicit flow)

**Comment by brockallen** [comment]
did you look at our samples?

**Comment by boban984** [comment]
@Gentlehag  Take a look at this presentation by @brockallen , it's an excellent description of the implicit flow and the general topic of using OIDC.

[https://i.vimeocdn.com/video/523966947_200x150.webp](https://vimeo.com/131636653) 

Also take a look at this helper lib, takes care of pretty much everything if ur using implcit flow : [Oidc js client](https://github.com/IdentityModel/oidc-client-js)
