### ISSUE TITLE
Add additional page in IDP

### ISSUE THREAD

**Issue by NovakSavic** [IdentityServer/IdentityServer3#3355]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is it possible to add additional HTML page in IDP?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Yes.

**Comment by NovakSavic** [comment]
Where can I found more info about it?

**Comment by brockallen** [comment]
the docs -- look for partial logins on the user service

**Comment by NovakSavic** [comment]
What I need is the following. I have backend service for creating the users, and initially when user is created, I geneate random password and send it to user email. When user tries to get access token with this password he will get only one claim of type permission so he can only access the endpoint to change the password. 

Do you think it is good idea that this page is part of IDP? If yes, then I would like to add this page and perform redirect to this page where user can change the password.

Or shall I keep this page out of IDP?
