### ISSUE TITLE
retrieve values a user selected after authenticating

### ISSUE THREAD

**Issue by stevengopmo** [IdentityServer/IdentityServer3#3360]
hi,

I am using PostAuthenticateLocalAsync to detect that my users need to do something interesting like select a value from a drop-down etc.  I redirect them to a page where I collect the required input, then post it back to my mvc controller.  

Other than saving those items to the database, is there anyway for me to pickup what they selected somewhere later in IdentityServer pipeline?

My initial idea was that I could plugin to where IdentityServer resumes the partial login, but I have not yet found a place for that.

**Comment by brockallen** [comment]
You can add claims to the partial login. See the OWIN extension method docs. For anything more on this issue, please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
