### ISSUE TITLE
It is possible to have a different List<LoginPageLink>() depending on the client?

### ISSUE THREAD

**Issue by ltfleming** [IdentityServer/IdentityServer3#3361]
### Question

First off, THANK YOU for doing such a fantastic job with IdentityServer, hat's off to you!!

My question is:
It is possible to have a different List<LoginPageLink>() depending on the client?

The reason I'm asking is;
I have implemented registration/PW reset/etc to a seperate client API. 
I added links on the login page of IDS pointing to the registration/PW reset/etc pages of the client site.
This is all fine.. but what I'm thinking is; 

If I add a second client API in the future, I will need a seperate registration system for that client (because I would want those clients to have a different/additional scope to access the second client API).
Then the login page links would be pointing to the wrong place. 

Is 'having a different List<LoginPageLink>() depending on the client' possible, or am I thinking about this all wrong?

**Comment by brockallen** [comment]
You'd have to make this dynamic in a custom view service. For questions on that, please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
