### ISSUE TITLE
[Question] Calling Identity Endpoint from Client WebAPI

### ISSUE THREAD

**Issue by leedjones** [IdentityServer/IdentityServer3#3362]
### Question / Issue

I’m following the MVC tutorial (https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html) and I’m at the ‘Calling the API’ section where my external WebAPI needs to call into IdentityServer.

The problem I’m having is with this code:

```
private async Task<string> CallApi(string token)
{
    var client = new HttpClient();
    client.SetBearerToken(token);

    var json = await client.GetStringAsync("https://localhost:44321/identity");
    return JArray.Parse(json).ToString();
}

```
Firstly, is the EndPoint URL above incorrect? Shouldn’t that be 

> "https://localhost:44319/identity”

?
If so, when I do call that, I just get an HTML response. In the log file I can see:
`iisexpress.exe Information: 0 : 2016-11-10 08:03:13.971 +00:00 [Information] Welcome page requested – rendering`

Im wondering then, what endpoint I should be calling and if the above is correct?

Thanks

### Relevant parts of the log file

> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.836 +00:00 [Information] Start token request
> 2016-11-10 08:03:13.845 +00:00 [Debug] Start client validation
> 2016-11-10 08:03:13.848 +00:00 [Debug] Start parsing Basic Authentication secret
> 2016-11-10 08:03:13.849 +00:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.849 +00:00 [Information] Secret id found: "mvc_service"
> 2016-11-10 08:03:13.854 +00:00 [Debug] Secret validator success: "HashedSharedSecretValidator"
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.854 +00:00 [Information] Client validation success
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.859 +00:00 [Information] Start token request validation
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.862 +00:00 [Information] Start client credentials token request validation
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.865 +00:00 [Information] Client credentials token request validation success
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.875 +00:00 [Information] Token request validation success
>  {
>   "ClientId": "mvc_service",
>   "ClientName": "MVC Client (service communication)",
>   "GrantType": "client_credentials",
>   "Scopes": "SampleApi",
>   "Raw": {
>     "grant_type": "client_credentials",
>     "scope": "SampleApi"
>   }
> }
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.877 +00:00 [Information] Creating token response
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.878 +00:00 [Information] Processing token request
> 2016-11-10 08:03:13.881 +00:00 [Debug] Creating access token
> 2016-11-10 08:03:13.886 +00:00 [Debug] Creating JWT access token
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.930 +00:00 [Information] End token request
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.934 +00:00 [Information] Returning token response.
> iisexpress.exe Information: 0 : 2016-11-10 08:03:13.971 +00:00 [Information] Welcome page requested - rendering
>

**Comment by scottbrady91** [comment]
In that tutorial port 44319 is used for IdentityServer and port 44321 is for the example API.

Therefore the 44321/identity endpoint is correct for this example (see the 'Adding a Test Controller' section which walks you through setting up this API). Did you create this API?

**Comment by leedjones** [comment]
Ah OK. Yes, I did create it, but thats in the same API as is being configured, is it not? 
So the Authority property for the IdentityServerBearerTokenAuthenticationOptions should point to its own local Identity Controller (i.e. on the client Web API)?

**Comment by leedjones** [comment]
Thanks, I did create it but didn't realise it was pointing to its local endpoint called 'identity' which was the API controller name and not the identity endpoint exposed by identity server. perhaps /identity isn't the best name for this test controller (or I'm just a clown ;) )? Had the WebAPI endpoing been called /GetClaimsAsJson or something like that then I would have understood what was going on there.

perhaps naively I just assumed anything with identity or claims or tokens needs to go back to the identity "server".

Thanks for the help on this
