### ISSUE TITLE
Windows External authentication provider is stuck after clicking on Windows External login

### ISSUE THREAD

**Issue by ittahgal** [IdentityServer/IdentityServer3#3364]
Hi, 
I configured windows authentication to be able to do Windows single sign on using the implicit mode.
First i created an WindowsAuthenticationService as a seperate web project configured:

app.UseWindowsAuthenticationService(new WindowsAuthenticationOptions()
            {
                IdpRealm = "urn:win",
                IdpReplyUrl = "https://localhost:44354/was",
                PublicOrigin = "https://localhost:44349/",
                SigningCertificate = new X509Certificate2(certificatePath, certificatePassword),
                CustomClaimsProvider = new AdditionalWindowsClaimsProvider(),
                EnableOAuth2Endpoint = true
            });

I  tested it and got to the meta data page.

afterward i added an external login provider to my identiy server implementation like this:

 private void ConfigureAdditonalIdProviders(IAppBuilder appBuilder, string signInAsType)
        {
            var windowsAuthentication = new WsFederationAuthenticationOptions()
            {
                AuthenticationType = "windows",
                Caption = "Windows",
                SignInAsAuthenticationType = signInAsType,
                MetadataAddress = "https://localhost:44349/",
                Wtrealm = "urn:win",
                Wreply = "https://localhost:44349/was"
            };

            appBuilder.UseWsFederationAuthentication(windowsAuthentication);
        }

Now, when i try to use my implicit client i get to the authentication page and i have a new Windows button showing up when i press it starts to do some kind of navigation but nothing happens and it stuck waiting for a call to finish, the call is:

https://localhost:44354/external?provider=windows&signin=bbc0c9fd0a67dff377a623f33a0b85d3

it did not hit any of my breakpoints in the windows authentication service or the identiy server IUserService implementation.
The only thing i saw that was called is in my IClientStore implementation the FindClientByIdAsync method.

any idea what did i configure wrong here?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by jpaull** [comment]
I am having the same issue. I am getting stuck with the same URL (different sign-in value, of course).

https://localhost:44317/external?provider=windows&signin=1e35170a28070a2f41f013e35929ab67

This code was working fine when using IISExpress via Visual Studio, but now I am trying to Host the Services in a Console Application according to the 'SelfHost' samples and am getting this result.

`var wsFederation = new WsFederationAuthenticationOptions
            {
                AuthenticationType = "windows",
                Caption = "Windows",
                SignInAsAuthenticationType = signInAsType,
                MetadataAddress = "https://localhost:44380",
                Wtrealm = "urn:idsrv3",
                Notifications = new WsFederationAuthenticationNotifications
                {
                    // ignore signout requests (we can't sign out of Windows)
                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.IsSignOutMessage)
                        {
                            n.HandleResponse();
                        }
                        return Task.FromResult(0);
                    }
                }
            };
            app.UseWsFederationAuthentication(wsFederation);`
