### ISSUE TITLE
Legacy ASP.NET WebForms and Callbacks

### ISSUE THREAD

**Issue by vi-jasonm** [IdentityServer/IdentityServer3#3366]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Hoping this has been asked/answered before and I just wasn't able to locate it.  We have recently spun up a new SSO server using IdentityServer3.  Now we're attempting to migrate older websites over to use this.  The current website I'm having difficulty with is an old legacy ASP.Net webforms project that supports both traditional and SSO logins.

I have my client registered as an implicit client.  In my ASPX page on Page_Load I spin up a new OAuth2Client, call CreateImplicitFlowUrl (giving it the same aspx page to callback) and then do a Response.Redirect.

I am redirected and can login, but unfortunately the SSO IdentityServer never performs the callback and there are no errors or anything that I can locate to indicate why.  I really could use some pointers as I've been tweaking and googling for over a week now without luck.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
The clients sample has both a manual MVC client - and a webforms client. Also enabling logging usually helps with diagnosing such problems.
