### ISSUE TITLE
Machine keys in a load balanced environment with reference tokens

### ISSUE THREAD

**Issue by kylegalbraith** [IdentityServer/IdentityServer3#3367]
I believe this should be a straightforward question to answer based on what I have seen in others issues. But the question is this, in a load balanced environment (i.e. more than one instance) we need to sync machine keys via the web.config. Per this documentation (https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html) it would appear that there must also be a persistence store implemented by us in order to sink reference tokens across the instances. Is my interpretation correct?

When using reference tokens with an implicit client, is it just the TokenHandleStore that I need to create? Thank you for any guidance!

**Comment by brockallen** [comment]
https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html

**Comment by kylegalbraith** [comment]
Effectively create a persistent store to house the reference tokens and then implement the data repository service to communicate with that persistent store. Can, https://github.com/IdentityServer/IdentityServer3.EntityFramework be used for using EntityFramework with the TokenHandleStore

**Comment by leastprivilege** [comment]
yes
