### ISSUE TITLE
Allow to Identity server 3 to Authenticate user from FormsAuthentication cookie

### ISSUE THREAD

**Issue by umfaruki** [IdentityServer/IdentityServer3#3368]
I have some applications and a identity server which are working perfectly fine. Couple of my old applications are still using Form based authentication and for the purpose of achieving SSO I am using machine key and domain combinations in my web.config.

`<authentication mode="Forms">
  <forms name="SSO" 
         loginUrl="http://site1.example.com/login.aspx" 
         defaultUrl="http://example.com" 
         domain="example.com" slidingExpiration="true">
  </forms>
</authentication>
<machineKey validationKey="35D679385CE8" decryptionKey="55D456A"  
  validation="HMACSHA256" decryption="AES" />`

It helps me achieve SSO.

Now the problem is after getting authenticated from webforms application if user navigates to any of my new application they got redirected to identity for login. what i want is there any way that identity server authenticate user if FormsAuthentication cookie is available. Its not possible for now to change my old applications.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
