### ISSUE TITLE
Various platforms expect different parameter names for account linking

### ISSUE THREAD

**Issue by benjaminpaul** [IdentityServer/IdentityServer3#3369]
Hi Everyone,

I have been tasked with enabling account linking to my companies user accounts via a number of different platforms and devices (Amazon Alexa, Facebook Messenger Bots etc) and one of the issues I am having is that each platform expects the callback after authentication to append the token to the query string using a different parameter name...

https://www.example.com/callback?auth_token=<AUTH_TOKEN>
https://www.example.com/callback?access_token=<AUTH_TOKEN>
https://www.example.com/callback?token=<AUTH_TOKEN>

etc etc

How would one handle this kind of scenario considering I cannot simply ask the platforms to expect a certain parameter name? Has anyone had this kind of scenario and solved it?

Thanks

**Comment by kmkatsma** [comment]
#benjaminpaul Ever find a solution for this?  Looking at identityserver and would also need to handle account linking to external platforms like this.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
