### ISSUE TITLE
php sample code for Identity Server?

### ISSUE THREAD

**Issue by tienw** [IdentityServer/IdentityServer3#3370]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question 

I had Identity Server setup for our MVC portal and Web API, now there is another new requirement: a PHP based web service also need to talk to Identity Server and get the token to access the Web API. I looked at this [document](https://github.com/IdentityServer/Documentation/issues/73) and found the suggested flow (Client Credential or Resource Owner). However, do you know the sample code for PHP to talk to Identity Server?

Thank you for your help
```

**Comment by mderriey** [comment]
Remember that Identity Server implements the OpenID Connect specification, so nothing should be really specific to Identity Server.
You can have a look at the [libraries page](http://openid.net/developers/libraries/) on the official OIDC website and look for PHP. It looks like [OpenID-Connect-PHP](https://github.com/jumbojett/OpenID-Connect-PHP) could suit your needs.
