### ISSUE TITLE
Q: Token based auth API and Javascript, can you protect other clientside files from being accessed?

### ISSUE THREAD

**Issue by FreeFrags** [IdentityServer/IdentityServer3#3372]
### Question
If you would use a similar setup as the following examples:
- Simple WebAPI
- Javascript OIDCClient and usermanager

Would it be possible to protect other clientside files from being accessed? Say for example i have a directory with certain files which you need a certain role to be able to access them.

Would it be possible to protect my SPA from being accessed before logging in?

Or is there a better solution which would have you end up with a protected api, folders/files on a server, SPA and a silent renew mechanism like there is in the OIDCClient?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
