### ISSUE TITLE
IIS 10 System.Security.Cryptography.CryptographicException: Access denied.

### ISSUE THREAD

**Issue by TDK1964** [IdentityServer/IdentityServer3#3373]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I'm current using this sample as my test bed.
[IdentityServer3.Samples/source/MembershipReboot/](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MembershipReboot)

I've assigned the correct permissions and read several other posts about this problem but I still get access denied.
I've even ran the IIS application pool as the local administrator and it still refused to play ball.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
