### ISSUE TITLE
Possibly unintended concurrency in AggregatePermissionsStore.LoadAllAsync()

### ISSUE THREAD

**Issue by hermes-del-rondo** [IdentityServer/IdentityServer3#3374]
I'm using IdentityServer3 2.5.4 with Entity Framework 6 as ORM (custom implementation, not the IdentityServer3.EntityFramework library). So far everything is working fine. But when I try to open the ~/permissions page in the browser I get the message "There was an unexpected error". The log file shows two exceptions which are arbitrarily alternating per request:

1.  `System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()...`
2. `System.ObjectDisposedException: The ObjectContext instance has been disposed and can no longer be used for operations that require a connection.
   at System.Data.Entity.Core.Objects.ObjectContext.ReleaseConnection()...`

So I added some logging statements and found out that `ITransientDataRepository<T>.GetAllAsync()` is called concurrently multiple times. Debugging showed that the code
```cs
var result =
    await stores
        .Select(x => x.LoadAllAsync(subject))
        .Aggregate(async (t1, t2) => (await t1).Union(await t2));
```
in `AggregatePermissionsStore.LoadAllAsync()` seems to be the issue.

After replacing it with
```cs
List<Consent> result = new List<Consent>();
foreach (IPermissionsStore store in stores)
{
    result.AddRange(await store.LoadAllAsync(subject).ConfigureAwait(false));
}
```
it worked fine.

Is this concurrency by intention?

**Comment by ludoAlcala** [comment]
i found same issues from my side, we are running on Azure Websites with EF 6  and SQL Azure

**Comment by brockallen** [comment]
Would MARS help in your connection string? If not, then please send a PR to address the issue.

**Comment by hermes-del-rondo** [comment]
Thank you for the response. I'll look into this as soon as I have time and submit a PR if applicable.

**Comment by tolkushkin** [comment]
Hello MARS doesn`t help. Fix worked fine.
