### ISSUE TITLE
Windows authentication with a WPF Client

### ISSUE THREAD

**Issue by ittahgal** [IdentityServer/IdentityServer3#3377]
Hi,
I am trying to find a sample for how to use windows authentication from a WPF client.
I saw all the samples that give your the external providers in the implicit flow but this not what i need.

i am trying to achive a single sign on capability for my client applications.
any idea?

Thanks.

**Comment by brockallen** [comment]
Look at the OidcClient samples: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

Beyond that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
