### ISSUE TITLE
UserInfo endpoint doesn't recognize claims created in AuthenticateLocalAsync method

### ISSUE THREAD

**Issue by penelope-v** [IdentityServer/IdentityServer3#3378]
Kindly please clarify the following case.

According to full login description in documentation (https://identityserver.github.io/Documentation/docsv2/advanced/userService.html):

```The ClaimsPrincipal that is created from the full login is then used as the Subject for the other APIs on the IUserService. These APIs are PostAuthenticateAsync, GetProfileDataAsync, IsActiveAsync, and SignOutAsync.```

But in GetProfileDataAsync method when the caller is "UserInfoEndpoint", only one claim is present in Subject property of ProfileDataRequestContext. And it is a "sub" claim.

And I'm faced with the following issue. I have custom IUserService and in AuthenticateLocalAsync method I return additional claim for principal (named "provider"):
``` 
context.AuthenticateResult = new AuthenticateResult(subject: context.UserName,
                                       name: context.UserName,
                                        claims: new List<Claim>() { new Claim("provider", provider.FullName) });
```

But this claim is not present when GetProfileDataAsync get called (for UserInfo endpoint).
Am I am missing something?

**Comment by brockallen** [comment]
No, you're not missing anything. This is a current known limitation.

**Comment by penelope-v** [comment]
Could you please clarify, whether it is planned to get rid of this limitation? Or may be it is already described anywhere?

**Comment by brockallen** [comment]
I think we have an open enhancement issue to read all the claims from the access token and make them available on the Subject to the GetProfileData API. In them mean time, you can do this yourself explicitly.

**Comment by leastprivilege** [comment]
Well - the fundamental issue is that whatever you return from Authenticate goes into a cookie.

The userinfo endpoint call is not done via the browser but is a back channel call. So no cookie.

If you want to return data from userinfo you need to store it somewhere - e.g. a database.

**Comment by penelope-v** [comment]
Ok, thank you all for your answers.
