### ISSUE TITLE
Single Post Signin Landing page for multiple apps

### ISSUE THREAD

**Issue by Studentblanchard** [IdentityServer/IdentityServer3#3379]
I have the requirement of always redirecting to the same page after the user authenticates themselves. We have 2 apps, an mvc application (hybrid client) and an angular js app (implicit client). We need to always redirect to the home page on the MVC application after a user logs in, wether they originally navigated to the implicit or hybrid client. 

I changed the redirect uri in the implicit client config to be the home page of the MVC app, that much works. Now whenever I login I'm always redirected to the expected home page. The problem is that now I can never access the implicit client, since when you navigate to the implicit client, it goes to the authorize endpoint to get the tokens, but then is redirected back to the MVC home page (since that's what the redirect uri is).

Is what I'm trying to do possible to acheive? 

It seems like I need to dynamically set the redirect uri depending on if I'm doing a full authentication of the user, or if I'm just authenticating the client. However I'm not certain on how to detect this or if it can even be done. 

Its possible that there is a simpler solution that I just can't think of too.

Thanks in advance.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by Studentblanchard** [comment]
Sorry Brock, I will post there next time. For anyone interested, I solved this by using the PostAuthenticateAsync override in the UserService. In there we can override the redirect uri in the sign in message..

       public override Task PostAuthenticateAsync(PostAuthenticationContext context)
        {
            context.SignInMessage.ReturnUrl = IdentityConfigurations.WebClientRedirectUri;

            return base.PostAuthenticateAsync(context);
        }
