### ISSUE TITLE
Client UtcOffset as a claim

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3380]
I need to find a way to grab the clients utcOffest as they are logging in and have it as a claim after the authentication process is complete.

I am not certain how to tackle this issue. Any suggestions will be greatly appreciated.

Thank you

update:
My setup most resembles the CustomHrd sample. That in mind it seemed appropriate to grab the utcOffset at the same time that I get the user email. Easy enough. The tough part is figuring out how to pass that value on from the PreAuthenticateAsync to ultimately become a claim.

Any suggestions?

**Comment by brockallen** [comment]
You can set claims on the client configuration.
