### ISSUE TITLE
Add username querystring parameter to LoginPageLink 

### ISSUE THREAD

**Issue by olonga** [IdentityServer/IdentityServer3#3382]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have added a LoginPageLink for the Forgot password url.  I would like to add the username as a querystring parameter in addition to signin.  The reason for doing this is that we directly display the security challenge question the user has previously set up plus it also relieves the user from typing his username again which he has already typed in the ids login page.  How should I move forward with this? Can I inject some custom javascript to the login page and add the username on the click event (that user has typed) to the Forgot password LoginPageLink url?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by olonga** [comment]
So far this is what I am doing and it does work. Is there a better way to do this? Thanks.
<script>
    $(function() {
        $("a[href^='<profile-mgt-site-url>/Account/ForgotPassword?signin=']")
            .off("click")
            .on("click",
                function(e) {
                    e.preventDefault();
                    //validate if the user has typed the username in the username field
                    var username = $("#username").val().trim();
                    if (username.length < 1) {
                        //Notify user: Please type username in the username field before clicking on Forgot password link.
                        return;
                    }
                    //add to querystring of the 'Forgot password?' link
                    var currHrefVal = $(this).attr('href');

                    //redirect to the new url
                    location.href = currHrefVal + "&username=" + username;
                });
    });
</script>

**Comment by olonga** [comment]
I think the issue above is taken care of. Now, I would like to prepopulate the username field in the login page of ids when the user returns back from password reset site..

**Comment by brockallen** [comment]
You can pass the username hint to IdentityServer via the login_hint OIDC param: https://identityserver.github.io/Documentation/docsv2/endpoints/authorization.html

**Comment by olonga** [comment]
Thanks.
