### ISSUE TITLE
ASP.NET Identity - Cookies still validating after signing out

### ISSUE THREAD

**Issue by downunderbrother** [IdentityServer/IdentityServer3#3385]
I have discovered an issue in my project where by authentication cookies are still able to be used after calling "Request.GetOwinContext().Authentication.SignOut()"

The project consist of a signon server utilising ASP.NET identity, mvc website and a api web service platform.

I thought things were working well, users could signin on the ASP.NET identity platform and then have access to the mvc website. The mvc website is able communicate to the web service api correctly having acceptable scope.

I think I have missed a crucial point somewhere along the way.

I seems that if I SAVE the cookies generated after a sucessfull sign on, then signout I loose access to the website as expected , although if I add the SAVED cookies back into the browser I once again have access to the site. it seems that although the cookies are being removed from the browser they are actually still usable and valid? 

any advice here would be much appreciated.

**Comment by brockallen** [comment]
that's how cookies work and that's why they set an expiration as a value inside the protected value of the cookie

**Comment by downunderbrother** [comment]
Thank you for the reply, I assume that so long as the secure flag is set on the cookies and transmitted over SSL there should not be cause for alarm, as you have stated after the 30 min timeout that was set for the expiration value they are invalidated.

**Comment by brockallen** [comment]
Yes, you should use HTTPS for everything these days. No reason to use HTTP.
