### ISSUE TITLE
Is possible to use the identityserver on same domain where is running the app?

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer3#3387]
Hello,

I want to deploy the identity server and my app to the azure cloud, but I have only one domain and one SSL certificate for - domain.com and www.domain.com.

Is possible create virtual directories on azure website and create this structure? -
https://domain.com/identity/ - for identity server
https://domain.com/app/ - for my app

Are there some limitation/problems on following solution?
Thank you.

**Comment by leastprivilege** [comment]
That's fine.
