### ISSUE TITLE
Issue token for another user

### ISSUE THREAD

**Issue by 247GradLabs** [IdentityServer/IdentityServer3#3389]
Hi
I would like to issue a token for another user from our API so we can use it to log in as that other user.
However the Resource Owner flow which would make this possible, needs a password which we don't want.
How can I make IdSrv return me a user token using not a password like in Resource Owner flow, but a secret like in Client Credentials flow instead?

I searched around in the issues here and on the web, but couldn't really find an answer.

**Comment by leastprivilege** [comment]
By implementing a custom grant. check the docs.

**Comment by 247GradLabs** [comment]
So I will basically have to write my own grant which is a mix of `password` (allowing specifying username) and `client_credentials` (allowing authentication by secret)?

Could you link me to the relevant docs or maybe there's even a sample for something like that?

**Comment by leastprivilege** [comment]
https://identityserver.github.io/Documentation/docsv2/advanced/customGrantTypes.html
and
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Custom%20Grants%20(more%20customization)
