### ISSUE TITLE
Reference Token in additional IDP endpoint

### ISSUE THREAD

**Issue by NovakSavic** [IdentityServer/IdentityServer3#3390]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I'm trying to figure out format of reference token in db and one actually returned to client.

In my DB I see something like IJe8dR27Oy8pCt3SEkeEHEjJ9DOvCtMNCmSlJ0aa7GY,
but what is returned to client is something that looks like GUID, but without dashes.

How can I convert reference token returned to client and token handle in db?

Why I do need this? Well I added additional endpoints in IDP related to dynamic client registration and configuration, and for some of endpoints I have bearer authorization schema. When setting JWT access token in Authorization header all good, but as soon as I use reference token, I get 401.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
the value in the DB is hashed for security reasons

**Comment by NovakSavic** [comment]
Ok thanks. I added additional endpoints in IDP related to dynamic client registration and configuration, and for some of endpoints I have bearer authorization schema. When setting JWT access token in Authorization header all good, but as soon as I use reference token, I get 401.

What could be the reason for this? I have my own implementation ITokenHandleStore. Everything is fine when using  reference tokens for my other services, but not for those additional endpoints in IDP.

**Comment by NovakSavic** [comment]
In regards to hashes, my problem last night was that hashes in DB was looking strange, this is the reason why I asked a question. But, I checked source code and see that you are using Base64Url.Encode from IdentityModel which removes any padding and replaces + with - and / with _.

1, Why do you perform this modifications?
2. Do you might know why reference tokens does not work for my additional IDP endpoints?

Thanks Allen

**Comment by brockallen** [comment]
Did you ever get sorted out?

**Comment by NovakSavic** [comment]
Hi Allen,

1. I did not spend time figuring out why do you perform modification of hash (+ to - and / to _). It does not make me any problems, but I would like to know. :-)

2. This was my mistake. All good with this.

Regards,
Novak

**Comment by brockallen** [comment]
1: I don't recall of the top of my head, sorry.
2: Ok, I'll close then.
