### ISSUE TITLE
Making one mvc application as server , one identityserver and one mvc client application 

### ISSUE THREAD

**Issue by rajeemaharjan1** [IdentityServer/IdentityServer3#3391]
Hi,

I have spent lots of time to make following condition .

1. My client wants to make one identityserver3. which is host in one place.
2. Second, I host another mvc application as server, Actually, customer can login from here. when it is login it should be behave like identityserver login. I want all pop procedure for login should be handle from internal. 
3. My last application should login if already identity server is login. I mean if second application will login then it should be automatically login. 

Please help me . I have spent lots of time for it.
```

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
