### ISSUE TITLE
ConfigureRequestBodyBuffer not good idea

### ISSUE THREAD

**Issue by imanad** [IdentityServer/IdentityServer3#3392]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
dear all
ConfigureRequestBodyBuffer change all request body not good idea because for example i add avatar controller that user upload his profile i surprise i see when user save image, image is corrupted and the size is increase, after i saw the code i find ConfigureRequestBodyBuffer  method make this problem.
suppose to  check the content type and do uft8 encoding for specific content types.

regards

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
We had to do this due to integration issues with Web API. We don't foresee changing it.

**Comment by imanad** [comment]
i don't understand, when i call UseIdentityServer all request when encode to utf8, how can add filter to scape utf8 encoding for costume controller?

**Comment by brockallen** [comment]
Perhaps use Map in the pipeline for your costume controller path.
