### ISSUE TITLE
Question: Remove / Revoke in IRefereshTokenStore

### ISSUE THREAD

**Issue by a-tok** [IdentityServer/IdentityServer3#3395]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

Hello,

I have implemented the `IRefreshTokenStore` interface. My implementation does persist all the token data and the apps that are in QA seem to be working correctly. However, I don't see Revoke/Remove being invoked. To setup a test, at what point in the process are the Revoke and Remove methods called?

**Comment by brockallen** [comment]
Refresh tokens are created when the client requests the offline_access scope.

**Comment by a-tok** [comment]
Yes, but at what point are they revoked/removed from the refresh token store?

**Comment by brockallen** [comment]
Depends, but by default none. As for explicit ways: the revocation endpoint is supported. Also, a UI could be built to revoke. At logout time they could be revoked. The EF library has a utility to delete expired ones.

**Comment by a-tok** [comment]
Oh, I see.  I'm not going crazy :). Thanks for the help Brock.
