### ISSUE TITLE
Registration of identity providers

### ISSUE THREAD

**Issue by eboada** [IdentityServer/IdentityServer3#3396]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I'm registering some ADFSs that I should support to authenticate in the Startup of Identity server. To do it, I'm reading the parametrization of each ADFS from a DB.

Each time that I ADD a new ADFS to the DB, I need to restart identity sever.

Is there some way to add more identity providers "on the fly" without needing to restart identity server?.

Thank you!.

**Comment by brockallen** [comment]
you can build and then rebuild your own owin pipeline.

Having said that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
