### ISSUE TITLE
External Authentication through Windows hangs when self-hosted

### ISSUE THREAD

**Issue by jpaull** [IdentityServer/IdentityServer3#3397]
Hello. I had commented on this issue here which seems to be the same as what I am encountering:

https://github.com/IdentityServer/IdentityServer3/issues/3364

But have yet to receive any response.

I am trying to implement single sign-on at my company using ADFS. I had built onto the 'WebHost' samples and got everything working through Visual Studio. Now I am trying to change the solution to be self-hosted (also borrowing from the samples).

I got everything up and running but the process hangs and never recovers when it reaches the Windows Authentication.

The URL that shows in the the browser when it hangs is https://localhost:44317/external?provider=windows&signin=1e35170a28070a2f41f013e35929ab67.

Here is the setup code for my Windows Auth project
```
var wsFederation = new WsFederationAuthenticationOptions
            {
                AuthenticationType = "windows",
                Caption = "Windows",
               SignInAsAuthenticationType = "idsrv.external",
                MetadataAddress = "https://localhost:44380",
                Wtrealm = "urn:idsrv3",
                Notifications = new WsFederationAuthenticationNotifications
                {
                    // ignore signout requests (we can't sign out of Windows)
                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.IsSignOutMessage)
                        {
                            n.HandleResponse();
                        }
                        return Task.FromResult(0);
                    }
                }
            };
            app.UseWsFederationAuthentication(wsFederation);
```

And here is the relevant excerpt from my log:

```
12:11 [Information] ()
 User is not authenticated. Redirecting to login.
12:11 [Information] ()
 End authorize request
12:11 [Information] ()
 Redirecting to login page
12:11 [Information] ()
 Login page requested
12:11 [Information] ()
 local login disabled for the client
12:11 [Information] ()
 only one provider for client
12:11 [Information] ()
 redirecting to provider URL: "https://localhost:44317/external?provider=windows&signin=ef5110411c088b5e8e7517f2b68c31d9"
12:11 [Information] ()
 External login requested for provider: "windows"
12:11 [Information] ()
 Triggering challenge for external identity provider

```

As I said before, this was working without issue when running in IIS Express. Trying to self-host it has brought about this issue. One thing to note is that all of this behavior (both good and bad) has been on my local Development environment.

Can someone please provide guidance  as to what is different about the self-hosting that would cause this issue to arise? I imagine there is some configuration change that I am missing.

**Comment by brockallen** [comment]
My guess is the Ws-Fed metadata deadlock bug/issue in the WsFed middleware.

**Comment by adimoraret** [comment]
@jpaull Did you manage to find a workaround for this?

**Comment by brockallen** [comment]
@adimoraret look at our use of this: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/Extensions/SyncConfigurationManager.cs#L9

**Comment by jpaull** [comment]
I gave up on using Windows Auth because of this very issue. I could not get it to work. I ended up going with an LDAP-based solution which is working just fine.

**Comment by brockallen** [comment]
> I gave up on using Windows Auth because of this very issue

Unfortunately it's a bug in the Microsoft ws-fed MW.
