### ISSUE TITLE
Handling 2fa with different clients

### ISSUE THREAD

**Issue by michaelbarnes** [IdentityServer/IdentityServer3#3398]
Hi There 

So I have built in the capability for our client applications to have a 2fa step, I followed the AspNetIdentity_2FA example for this. All goes good and well until I try and do this with 2 client applications. Once I have successfully 2fa with client 1 and try to do it with client 2 `GetIdentityServerPartialLoginAsync()` returns null for client two on my Index view, exactly the same as in the [example](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/AspNetIdentity_2fa/WebHost/Controllers/TwoFactorController.cs) (line 27). Please let me know what information I need to share with you in order for you to help me as I am not sure which part may cause this issue.

Thanks 

Mike

**Comment by brockallen** [comment]
You mean you're trying to do 2 partial logins at the same time?

**Comment by michaelbarnes** [comment]
Well one after the other, but I've also tried them at the same time with the same result.

**Comment by brockallen** [comment]
Partial logins are based on a single cookie middleware, so you can only have one at a time.

**Comment by michaelbarnes** [comment]
Is there some documentation as to how that works for the benefit of my understanding.
So should the one be completely logged out and then the other one sign in?

**Comment by brockallen** [comment]
Just the regular docs: https://identityserver.github.io/Documentation/docsv2/advanced/userService.html
