### ISSUE TITLE
[Question] Impersonation

### ISSUE THREAD

**Issue by felipeloest** [IdentityServer/IdentityServer3#3399]
I have read the issues about impersonation, and from what i could find so far it can be achieved. I'm not sure tho if the following could be done using it.

A user doesn't have permission to do a certain operation, but it can be done if a supervisor grant him access.

The grant would be only for that operation/request.

is this something that can be done using impersonation, or there is a better approach for this?

Thanks in advance.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by felipeloest** [comment]
Thank you.

If you have any tips for me...
https://stackoverflow.com/questions/40918320/identityserver3-user-impersonation
