### ISSUE TITLE
login to IdentityServer3 through code

### ISSUE THREAD

**Issue by myaesubi** [IdentityServer/IdentityServer3#3400]
### Question

Hello,
Would be possible to programmatically login to IdentityServer3 instance. I have a web-app inside another web app which needs silent login.

Given having the user credential to login, would it be possible?

Thanks,
Mohammad

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
