### ISSUE TITLE
Renew/keep session in Saml2 external provider

### ISSUE THREAD

**Issue by Wilsonmg** [IdentityServer/IdentityServer3#3401]
I'm wondering how to renew/keep sessions authenticated with external providers. For instance, I have an external provider who works with SAML2 (I use Kentor AuthServices to support it) and it has a session timeout of 30 minutes due to inactivity, but this provider can keep the session active up to 120 minutes  whenever it gets an authentication request (Saml AuthnRequest). After the timeout (30min for inactivity or 120 as total) the user needs to re-authenticate. 

This is the current setup:

![image](https://cloud.githubusercontent.com/assets/12584839/20837202/4d5dd0ea-b8a3-11e6-968b-55fdc454f3e1.png)

Have you faced this before, is there a nice approach for this? I'm evaluating to call the external provider whenever I refresh the IdentityServer token and how, and then how to handle the response...

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
