### ISSUE TITLE
How to revoke refreshtoken from API

### ISSUE THREAD

**Issue by madstt** [IdentityServer/IdentityServer3#3402]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi there,

I'd like to revoke a refreshtoken from the API, i.e. WebAPI. I only have the sbubjectId, not the actual refreshtoken. I use the ResourceOwner flow with JWTs.

The use case is that a user has to be deactivated from an administration page.

Is it possible? Or do I have to create a custom controller on IdentityServer host?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by j-hurst** [comment]
You can just call the revoke method from the refresh token store.

**Comment by madstt** [comment]
Yes, that is correct, but in my case the IdentityServer and the WebAPI are hosted in two different hosts. So I need somehow to call the IdentityServer for refreshtoken revocation, i.e. calling the revoke method on the refresh token store.

So I could write a custom controller on the IdentityServer host, which in turn will call the revoke method, but I there is a more correct way, I'd like to hear?

**Comment by leastprivilege** [comment]
Use the revocation endpoint.

https://identityserver.github.io/Documentation/docsv2/endpoints/revocation.html

**Comment by madstt** [comment]
That is the obvious and my initial idea, but I don't have the refreshtoken. I need to revoke a user from an administration page. It could be a user who has violated some domain rules and needs to be deactivated or a user who has cancelled his subscription...

**Comment by leastprivilege** [comment]
Then set some flag in the database that will cause your IsActiveAsync implementation to return false?

**Comment by madstt** [comment]
Of course, that's the solution... Thanks, Dom...
