### ISSUE TITLE
How to have user specific data on relying party of Identity Server?

### ISSUE THREAD

**Issue by evdjo** [IdentityServer/IdentityServer3#3403]
I have the following scenario:

- I have IdentityServer3, which uses ASP.NET Identity Users as the userstore. ASP.NET 4.5.2. 
- Then, I have a relying party, a MVC web app, that also uses ASP.NET Identity Users as its users. ASP.NET 4.5.2

Talking between the two works all well. However, I want to be able to have user specific data in my MVC web app. When IdentityServer3 sends claims to my MVC web app, it sends the unique identifier of "sub". This is basically the primary key of the user, stored in IdentitiyServer's ASP.NET users table.

A solution, I thought was to add "IdServerUserId" column in my MVC web app ASP.NET users table, and link that at sign in time. That is, let the user authenticate, then when I receive the claims from IdentityServer, look up for which user has that ID, and replace the current user's "sub" claim with the one I have in the local database. I was thinking to do this in the  OpenIdConnectAuthenticationNotifications's callback "SecurityTokenValidated".

However, I am not sure if this is the right solution, as I seem to be reinveting the wheel. Is there standard way of linking external and internal users in a MVC web app?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
