### ISSUE TITLE
Multiple authentication mode for one app

### ISSUE THREAD

**Issue by bruceliu2008** [IdentityServer/IdentityServer3#3404]
Hi IdentityServer3,
    I heard IdentityServer3 is an excellent product for asp.net mvc 5 authentication.
we have a project need to provide 3 authentication modes.
1. normal public web user registration and login, data stored in sql server;
2. internal windows users login via AD;
3. redirect from another coorporate app, since user login in the app already, so should not login again in my app.
May I know how IdentityServer can help on these three cases?

Thanks a lot.
Bruce

**Comment by brockallen** [comment]
Yes it can handle those scenarios. Some of them might require some work on your part.

**Comment by bruceliu2008** [comment]
Thanks for the prompt reply. 
For the third case, if the other app uses dB to do authentication, how identity server support it?  Seems normally wif uses AD or third party for authentication, am I correct? Is jwt json web token suitable for this case? 

Thanks in advance.

**Comment by brockallen** [comment]
This is where you get into application security architecture, which we don't provide via the issue tracker. If you're looking for consulting assistance you can contact us here: http://identityserver.io/

**Comment by UbhiTS** [comment]
Hi Bruce, I was looking for similar help for my project, did you find any sample or guidance ?
