### ISSUE TITLE
endsession endpoint 404 for user

### ISSUE THREAD

**Issue by zeuz1983** [IdentityServer/IdentityServer3#3405]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
When i hit endsession endpoint with id_token_hint and post_logout_redirect_uri gives me a 404 error, only for my user, if i hit endsession endpoint with other user works fine. Any ideas?

### Relevant parts of the log file
There is no log file, i´m logging fatal error warning and info with serilog but no log of this error, i guess is because really is no error and may be idsrv cant find my id_token?
```
<log goes here>
```

**Comment by brockallen** [comment]
Is the URL too long?

**Comment by zeuz1983** [comment]
https://authorization.spf.ar/core/connect/endsession?id_token_hint=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImI3eWlQd2JrZ3pJSzh2LXZvYVNlaFFVY3FYRSIsImtpZCI6ImI3eWlQd2JrZ3pJSzh2LXZvYVNlaFFVY3FYRSJ9.eyJpc3MiOiJodHRwczovL2F1dGhvcml6YXRpb24uc3BmLmFyL2NvcmUiLCJhdWQiOiJpZGVudGl0eU1hbmFnZXJVaSIsImV4cCI6MTQ4MDk0NDQ2MywibmJmIjoxNDgwOTQ0MTYzLCJub25jZSI6IjUwYWJlYTMzOGY4NjRmNDBiNDJiYmZjODdkOGVjNzlmIiwiaWF0IjoxNDgwOTQ0MTYzLCJhdF9oYXNoIjoiTUlpMVNQMlg0dDVZRWRCQTVmaXFsQSIsInNpZCI6IjBjZDczNDY5NzRmMDY0OGVjNmJhYWY5ZWYwMzg2M2YyIiwic3ViIjoiMzk5MTdkYWYtZGE1OC00MTZjLTg1MjItNzhkZmFiNTNhZDRjIiwiYXV0aF90aW1lIjoxNDgwOTQ0MTYyLCJpZHAiOiJpZHNydiIsImVtYWlsIjoic3BhcmRvQHNwZi5nb2IuYXIiLCJyb2xlIjpbIklkZW50aXR5U2VydmVyQWRtaW4iLCJJZGVudGl0eVNlcnZlckFkdmFuY2VkTWFuYWdlciIsIlVzZXJNYW5hZ2VyQWRtaW5pc3RyYXRvciIsIkF1dGhvcml6YXRpb25TZXJ2ZXIuQ2xpZW50TWFuYWdlckFkbWluaXN0cmF0b3IiLCJBdXRob3JpemF0aW9uU2VydmVyLlVzZXJNYW5hZ2VyQWRtaW5pc3RyYXRvci5VcGRhdGUiLCJBdXRob3JpemF0aW9uU2VydmVyLlVzZXJNYW5hZ2VyQWRtaW5pc3RyYXRvci5EZWxldGUiLCJBdXRob3JpemF0aW9uU2VydmVyLlVzZXJNYW5hZ2VyQWRtaW5pc3RyYXRvci5DcmVhdGUiLCJBdXRob3JpemF0aW9uU2VydmVyLlVzZXJNYW5hZ2VyQWRtaW5pc3RyYXRvciIsIkF1dGhvcml6YXRpb25TZXJ2ZXIuUm9sZU1hbmFnZXJBZG1pbmlzdHJhdG9yLlVwZGF0ZSIsIkF1dGhvcml6YXRpb25TZXJ2ZXIuUm9sZU1hbmFnZXJBZG1pbmlzdHJhdG9yLkNyZWF0ZSIsIkF1dGhvcml6YXRpb25TZXJ2ZXIuU2NvcGVNYW5hZ2VyQWRtaW5pc3RyYXRvci5VcGRhdGUiLCJBdXRob3JpemF0aW9uU2VydmVyLlNjb3BlTWFuYWdlckFkbWluaXN0cmF0b3IuRGVsZXRlIiwiQXV0aG9yaXphdGlvblNlcnZlci5TY29wZU1hbmFnZXJBZG1pbmlzdHJhdG9yLkNyZWF0ZSIsIkF1dGhvcml6YXRpb25TZXJ2ZXIuU2NvcGVNYW5hZ2VyQWRtaW5pc3RyYXRvciIsIkF1dGhvcml6YXRpb25TZXJ2ZXIuUm9sZU1hbmFnZXJBZG1pbmlzdHJhdG9yIiwiQXV0aG9yaXphdGlvblNlcnZlci5QYXJhbWV0cmljTWFuYWdlckFkbWluaXN0cmF0b3IiLCJBdXRob3JpemF0aW9uU2VydmVyLkNsaWVudE1hbmFnZXJBZG1pbmlzdHJhdG9yLlVwZGF0ZSIsIkF1dGhvcml6YXRpb25TZXJ2ZXIuQ2xpZW50TWFuYWdlckFkbWluaXN0cmF0b3IuRGVsZXRlIiwiQXV0aG9yaXphdGlvblNlcnZlci5DbGllbnRNYW5hZ2VyQWRtaW5pc3RyYXRvci5DcmVhdGUiLCJBdXRob3JpemF0aW9uU2VydmVyLkxvZ01hbmFnZXIiXSwibGFzdG5hbWUiOiJQYXJkbyIsImdyYWRvIjoiQXl1ZGFudGUgNMKwdGEiLCJnaXZlbm5hbWUiOiJQYXJkbywgU2ViYXN0aWFuIiwibmFtZSI6IlNlYmFzdGlhbiIsImNyZWRlbmNpYWwiOiIzNzM5OCIsImRvbWFpbm5hbWUiOiJzcGFyZG8iLCJkZXN0aW5vIjoiRGVwYXJ0YW1lbnRvIGRlIGluZm9ybcOhdGljYSB5IGNvbXVuaWNhY2lvbmVzIiwidW5pZGFkIjoiRGlyZWNjacOzbiBOYWNpb25hbCIsImRlc3Rpbm9JZCI6IjEiLCJncmFkb0lkIjoiMyIsInVuaWRhZElkIjoiMSIsImFtciI6WyJwYXNzd29yZCJdfQ.a_PgCwepKZw8Q7NCJLLOYCk0rXPRDTZtp2l_AqoyObCatkcFn1OrMaksXHoRAxvCK62_LSBtsEeI4mPUGW1wwQlfrzbtkKND5GVFu1vL1pr7ZexSx3IC_O2WVr0a-Lac6Q3T9xNDQrMLmVAS6CSUx-uTjwInW9uxBqLLG7ij39aOL7rHnN17uQQYxXKZIbzWchXvf4BPsF6kXkBi7Pa0FOQs6NmNuG9xyApEUefiFmTL8Q2X9HiBgEzrzJRDuuT1bwZa8PdsKaFaIJ2ekxPOwdJziEfaGnRxAavrGWza4j2-75EWxlVenj2-xYtM5EOO7DiTST7V_u38Nt0KZE0eFA&post_logout_redirect_uri=https%3A%2F%2Fssomanager.spf.ar%2FlogoutRedirect.html

thats the URL, doesn´t seems too long

**Comment by brockallen** [comment]
it's almost 3k, which is getting up there.... any log entries in idsvr for it?

**Comment by zeuz1983** [comment]
no there isn´t log of this particular error

**Comment by zeuz1983** [comment]
i see that the user roles are int he id_token maybe i can reduce the url if i get out the roles from there

**Comment by zeuz1983** [comment]
Done!! you can close the issue, my mistake, for anyone in the same trouble have checked the always include in token on the role scope, so all roles goes to id_token and make the url too long like brock said.
Thanks again for your time and point me in the right direction
