### ISSUE TITLE
Adding client to client list cookie for subject, question

### ISSUE THREAD

**Issue by michaelbarnes** [IdentityServer/IdentityServer3#3407]
### Question
I have two clients configured for two differenent applications. 

When I have signed in to client 1 and then try sign in to client 2 on the same browser, I am not prompted to sing in. This is not the desired behavior, the user should be asked for credentials for client 2. When I look at the logs I get the following:
`Adding client XXXX to client list cookie for subject XXXX`

My client application authentication process followed the MVC sample, using the implicit flow with a form post back.

How do I avoid this and force the user to sign in?

**Comment by brockallen** [comment]
> When I have signed in to client 1 and then try sign in to client 2 on the same browser, I am not prompted to sing in.

This is the exact desired behavior for SSO. If you want the user to re-auth, then pass the prompt param. See the docs for more info.
