### ISSUE TITLE
  Showing login: User is not authenticated when using Javascript Client in Identity Server 4

### ISSUE THREAD

**Issue by masaab** [IdentityServer/IdentityServer3#3409]
I am using Identity Server 4. I am getting **"  Showing login: User is not authenticated"**  I am trying to access my api using Javascript Client. If I understand correctly, I dont need a login to get token for my JavaScript Client application. I am following the exact steps in th documentation example 
What am I missing.

**Comment by brockallen** [comment]
> I dont need a login to get token for my JavaScript Client application

why not? you have a user, yes?

**Comment by brockallen** [comment]
Dup: https://github.com/IdentityServer/IdentityServer4/issues/557
