### ISSUE TITLE
Using smart card authentication with IdentityServer3

### ISSUE THREAD

**Issue by gesande** [IdentityServer/IdentityServer3#3410]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We'd like to use only smart card authentication in production but still allow local login in development. We will use our own user repository. I know we can use acr_values for selecting authentication provider.

What's your recommendation for achieving both ways in identityserver3, means of configuration/overrides etc?

**Comment by leastprivilege** [comment]
That's a pure host configuration - e.g. in IIS you can accept (but not require) client certificates.

In the user service (e.g. in PreAuthenticate) you can check for the existence of a cert on the TLS channel using the OWIN context.

**Comment by gesande** [comment]
We need to require client certificate (in production) since smart card middleware triggers the certification selection and asks for a pin.

How do we then separate local login vs. smart card authentication, do we need to have separate user service for local login and somehow switch to either one?

**Comment by leastprivilege** [comment]
I don't follow. This is a host concern, not identityserver.

In the user service you can check the existence of the client certificate - and act accordingly if it is present. If not - do something else.

**Comment by gesande** [comment]
I got it. We configure host (IIS) to require client certificate in production and check the existence of client certificate. In development environment we support the local login.

I tought of a solution that client would send acr_values=ipd:smartcard (or similar) on authorization call and would then be redirected to the server that actually requires client certificate (maybe another installation of a identityserver with userservice implemention requiring client certificate).

**Comment by leastprivilege** [comment]
that sounds pretty complicated to me.

**Comment by gesande** [comment]
If we configure identityserver3 host (IIS) to require client certificate it introduces a new problem since api-server is also communicating with identityserver and will require valid certificate. We would be using implicit flow (js client). Any ideas how to pass the problem?

**Comment by leastprivilege** [comment]
you can configure certificate requirements in IIS per virtual path - and you have "require" vs "accept" semantics.
