### ISSUE TITLE
How to authenticate user in javascript client application

### ISSUE THREAD

**Issue by masaab** [IdentityServer/IdentityServer3#3412]
I am following Javascript Client application [sample](http://identityserver4.readthedocs.io/en/release/quickstarts/7_javascript_client.html)  and I am receiving error user not authenticated. I could not find in the sample application where to insert my my username and password. I just followed the sample.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
