### ISSUE TITLE
SignInMessage server storage

### ISSUE THREAD

**Issue by explunit** [IdentityServer/IdentityServer3#3415]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

As mentioned in #1409, the SignInMessage cookies are quite large. For the authentication cookies we have the option of storing the full data server-side by setting `AuthenticationOptions.CookieOptions.SessionStoreProvider`. It would be very useful to have a similar option for SignInMessage storage.

**Comment by brockallen** [comment]
Thanks for the suggestion. I understand, but I don't foresee us making this change. If it helps, IdentityServer4 has improved on this issue.
