### ISSUE TITLE
User is not active error received when deploying WSFederation service

### ISSUE THREAD

**Issue by ultraplop** [IdentityServer/IdentityServer3#3417]
Hello,
I'm having an issue deploying to IIS and I'm hoping someone can help figure out whats going on or have an idea on how to better debug/troubleshoot:

My project is working when debugging within Visual Studio, however after deploying to IIS (windows 2012 server R2) I get the User is not active error when attempting to login using Windows Authentication with WS Federation.  

I have Identity Server configured to use ASP.NET Identity and everything is working fine when using the forms based login prompt and coming in directly as an ASP.NET Identity user.   If I try to login with external windows login I get the user is not active error, I am also seeing a 401 error.  Here is the request header:

GET /wsfederationservice/?wtrealm=urn%3awin&wctx=WsFedOwinState%3dg2A9uyGa21kwwkW7f6Vg8L872q_C0tkp97fCZSAaAIL2MSajmyJv3CvKottU73UKsHKHGZv4ijWzg93MoemOdj0OzrZ-R6x4xQud8WS5IJcW8akVaDCW74LLNLbjco64Ps7rQ6AZWk-uyUNmDCFfSztrDuZsE9vq26MtJCEa2ZH2VdlAT4xVFkIix-5QFcGtIFragPHTmMBRmDAbOSMAQvalmtgO4TbvIjaJl9jNOP0PaBlPJfW2EuRsYTpMS62H&wa=wsignin1.0 HTTP/1.1

If I do a get on just /wsfederationservice without the parameter it returns the metadata for the service successfully.

The WS-Federation service is its own site (sub virtual directory under the same domain as the identityserver site).  I've played around quite a bit with the virtual directory and app pool settings.  Right now its set with windows auth and anonymous enabled.  The app pool is set run as an admin account for the dev machine.

Here's the code for the ws-federation service:

`
public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            string IdentitySTS = "https://dev-auth.testcompany.com/identityserver/identity";
            string PublicOrigin = "https://dev-auth.testcompany.com/";
            string replyUrl = IdentitySTS + "/was";

            app.UseWindowsAuthenticationService(new WindowsAuthenticationOptions
                {
                    IdpRealm = "urn:win",
                    IdpReplyUrl = replyUrl,
                    PublicOrigin = PublicOrigin,
                    SigningCertificate = LoadCertificate(),
                    CustomClaimsProvider = new AdditionalWindowsClaimsProvider()
                });            
        }

        X509Certificate2 LoadCertificate()
        {
            string CertPath = "c:\\temp\\idsrv3test.pfx";
            string CertPassword = "IDSrvTest123";
            return new X509Certificate2(CertPath, CertPassword);
        }
    }
`

### Relevant parts of the log file

```
2016-12-09 12:36:25.665 -06:00 [Information] Start authorize request
2016-12-09 12:36:25.665 -06:00 [Information] Start authorize request protocol validation
2016-12-09 12:36:25.665 -06:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"TestMVCHybrid\",
  \"ClientName\": \"TestMVC (Hybrid Id)\",
  \"RedirectUri\": \"https://dev-auth.testcompany.com/testidentitymvc/\",
  \"AllowedRedirectUris\": [
    \"https://dev-auth.testcompany.com/testidentitymvc/\"
  ],
  \"SubjectId\": \"27c10e66-332d-45c9-9a42-9244cb45cb14\",
  \"ResponseType\": \"code id_token token\",
  \"ResponseMode\": \"form_post\",
  \"Flow\": \"Hybrid\",
  \"RequestedScopes\": \"openid profile address offline_access\",
  \"State\": \"OpenIdConnect.AuthenticationProperties=QLEHAyBz-u75EmfWnupxW4YK5FzcHOJmXT8ljkWx-t2M2fjJN2wjQw78yHSal7fnqoloAdCCKM0nk-txm0nxbzOPV_Yl36uZgRPMtbiKFda8CnDmGPHa0Rjy8Z6IiL1NZuyl69wj9qk-mH2mEy5VU10Qmgji5IN7PzaJ2GLwDQgGSGgp8gLokmGh78E_LTC89G_FtrfNEJ5TFTc6jEjMlEB8MSBwCQKLxdEx6OX6n3y5wRFFYmafpMGaimq_W-HSrNfX_icAmINV_Hy6OknSGA\",
  \"Nonce\": \"636169053707643045.ZDBjNWE5ZDEtYzk3OS00ZGUxLThmYzItYTgxNzYyZWY2MzM5MGMxMzI1MDMtYjhmNS00Yzk2LWJiY2ItMWFkMzBjM2JiZTM2\",
  \"SessionId\": \"582955510310ed21ba65d71db13b7406\",
  \"Raw\": {
    \"client_id\": \"TestMVCHybrid\",
    \"redirect_uri\": \"https://dev-auth.testcompany.com/testidentitymvc/\",
    \"response_mode\": \"form_post\",
    \"response_type\": \"code id_token token\",
    \"scope\": \"openid profile address offline_access\",
    \"state\": \"OpenIdConnect.AuthenticationProperties=QLEHAyBz-u75EmfWnupxW4YK5FzcHOJmXT8ljkWx-t2M2fjJN2wjQw78yHSal7fnqoloAdCCKM0nk-txm0nxbzOPV_Yl36uZgRPMtbiKFda8CnDmGPHa0Rjy8Z6IiL1NZuyl69wj9qk-mH2mEy5VU10Qmgji5IN7PzaJ2GLwDQgGSGgp8gLokmGh78E_LTC89G_FtrfNEJ5TFTc6jEjMlEB8MSBwCQKLxdEx6OX6n3y5wRFFYmafpMGaimq_W-HSrNfX_icAmINV_Hy6OknSGA\",
    \"nonce\": \"636169053707643045.ZDBjNWE5ZDEtYzk3OS00ZGUxLThmYzItYTgxNzYyZWY2MzM5MGMxMzI1MDMtYjhmNS00Yzk2LWJiY2ItMWFkMzBjM2JiZTM2\"
  }
}"
2016-12-09 12:36:25.869 -06:00 [Information] User is not active. Redirecting to login.
2016-12-09 12:36:25.869 -06:00 [Information] End authorize request
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
