### ISSUE TITLE
Introspection Endpoint case sensitive on URL/aud validation?

### ISSUE THREAD

**Issue by CesarD** [IdentityServer/IdentityServer3#3418]
I just lost half my afternoon trying to figure out why the Endpoint validation was returning that my token was inactive until I found out that the Introspection Endpoint is case sensiive on the URL you enter to hit it with, as it must match the same casing as the aud claim that the token has been issued with.

Is this intended behavior? Because is really annoying and I can't see why a URL should care on casing.

**Comment by brockallen** [comment]
URLs are case sensitive, by spec. But I can totally see your point. We actually lowercase it in our next version (IdentityServer4), so we can consider doing it here. I think this would technically be a breaking change, so we'd need to possibly wait until build 3.0.

**Comment by brockallen** [comment]
Turns out we already have an open issue for this. We'll track it there: https://github.com/IdentityServer/IdentityServer3/issues/3072

**Comment by leastprivilege** [comment]
Or set a static issuer name

**Comment by CesarD** [comment]
Oh, sorry, I didn't know about the other issue.
Regarding the static issuer name could be kind of complicated when different teams are working on different applications and maybe on the rush I'm trying to just make a request with Postman and didn't take care of the URL casing (that's pretty much what happened to me, hehe).

Do you really think of this as a breaking change? Perhaps I'm missing something (please enlight me in any case), but adding an option or just ignore the casing wouldn't be subtle and transparent?? What chance of breaking any existing code does this have?

**Comment by brockallen** [comment]
> Do you really think of this as a breaking change? 

Well, it is behavioral... but it's something we'd have to evaluate. I guess the other issue was marked for 2.6 (not 3.0).
