### ISSUE TITLE
Custom values inside GetProfileDataAsync

### ISSUE THREAD

**Issue by AlexFree** [IdentityServer/IdentityServer3#3419]
When i make request resource i have ability to get optional values
```
object optional = new { acr_values = "tenant:C810C924-BFB2-452D-AB61-045F226F5AE9" };
TokenResponse response = await client.RequestResourceOwnerPasswordAsync(model.Username, model.Password, "openid profile roles", optional);
```
```
public override async Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
	var tenantId = context.SignInMessage.Tenant;
```

But when i call to get user info i didn't have the same ability

```
UserInfoClient infoclient = new UserInfoClient("https://localhost:44340/identity/connect/userinfo");
UserInfoResponse inforesponse = await infoclient.GetAsync(response.AccessToken);
```
```
public override async Task GetProfileDataAsync(ProfileDataRequestContext context)
{
	var user = await GetUserManager(Db ???).FindByIdAsync(context.Subject.GetSubjectId());
```

So, the question is there any posibility to get some custom value (to determine what Db to use) inside GetProfileDataAsync ?

**Comment by AlexFree** [comment]
Probably i described the problem not good.
In a nutshell there is also need to pass AcrValues into GetProfileDataAsync method to have ability to determine the tenant where to find the user.

**Comment by brockallen** [comment]
acr values are present at authentication time (in AuthenticateLocal and in AuthenticateExternal). The result of authentication is a cookie with claims at IdentityServer. These claims are passed into GetProfile in most scenarios. If you want the acr values in GetProfile then issue a custom claims into the cookie from AuthenticateLocal.

**Comment by AlexFree** [comment]
i found this discussion ( https://github.com/IdentityServer/IdentityServer3/issues/3031 ) where you say that custom claims are not available from cookies.

i also made code for retrieving claim but without success as claim collection consists of one sub claim.
maybe i do smth wrong?

```
public override async Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
	var tenantId = context.SignInMessage.Tenant;
	var auxClaims = new[] { CreateClaim(KnownAcrValues.Tenant, tenantId) };
	context.AuthenticateResult = new AuthenticateResult(user.Id., user.UserName, auxClaims);
}

public override async Task GetProfileDataAsync(ProfileDataRequestContext context)
{
	var subjectId = Guid.Parse(context.Subject.GetSubjectId());
	var tenantId = context.Subject.FindFirst(KnownAcrValues.Tenant).Value; // only sub claim here
}
```

In my opinion it would be great to allow user to pass custom values to UserServiceBase methods, because they invoked outside. this will prevent you from any workarounds such as cache, cookies, db etc.

**Comment by brockallen** [comment]
We just did an update related to this: https://github.com/IdentityServer/IdentityServer3/issues/3036

**Comment by AlexFree** [comment]
I updated IS3 to latest release 2.6.0 and i started get additional claims like "auth_time, idp, amr", but i still don't have aux claim that i set in the AuthenticateLocalAsync method (example of code in my previous comment). Do i do smth wrong, point me please?

**Comment by brockallen** [comment]
Read the docs on how scopes work.
