### ISSUE TITLE
Redirection loop if user is authenticated but not authorized

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3#3420]
Hello,

I have got a small question. I use identity server and in mvc client (with openId connect middleware) I observed that when user is already authenticated but not authorized to specific page he'll be redirected back to the login page, in login page he will be automatically redirected back because he is already logged in and loop will occur. 

Is it expected behaviour? Should i simply apply fix and configure middleware and in RedirectToIdentityProvider check if user is already authenticated and prevent redirection to login page?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
