### ISSUE TITLE
OAuth2 Implict Flow, redirect_uri validation 

### ISSUE THREAD

**Issue by banias** [IdentityServer/IdentityServer3#3421]
I am trying using WebApi 2 self-hosted + identityServer3 as OAuth2 authorization server. 
I've noticed that IdentityServer does not validate redirectUri when using Implicit flow.
According to:
https://tools.ietf.org/html/rfc6749#page-31

> The authorization server validates the request to ensure that all
> required parameters are present and valid.  The authorization server
> MUST verify that the redirection URI to which it will redirect the
> access token matches a redirection URI registered by the client as
> described in Section 3.1.2.

But IdentityServer seems to validate client_id id only. 

I've briefly checked the UnitTests:

```
new Client
                {
                    ClientName = "Implicit Client",
                    Enabled = true,
                    ClientId = "implicitclient",
                    ClientSecrets = new List<Secret>
                    {
                        new Secret("secret".Sha256())
                    },

                    Flow = Flows.Implicit,
                    AllowAccessTokensViaBrowser = true,
                    AllowAccessToAllScopes = true,

                    RequireConsent = false,

                    RedirectUris = new List<string>
                    {
                        "oob://implicit/cb"
                    },
                },

...
 [Fact]
        public void GetAuthorize_UserLoggedIn_ValidatorReturnsTrue_ReturnsConsentPage()
        {
            _stubValidator.Response = true;
            Login();

            var resp = Get(Constants.RoutePaths.Oidc.Authorize + "?client_id=implicitclient&redirect_uri=http://localhost:21575/index.html&response_type=id_token&scope=openid&nonce=123");

            resp.AssertPage("consent");
        }
```

They seem to assert such behavior. 

Access tokens are returned as Uri fragment, so they shouldn't be sent to any server, therefore the redirect uri seems to be unnecessary. The RFC also claims that redirect_uri is optional in implicit grant flow, so validating it makes little sense.
Is there anything I missed/misunderstood from the RFC? What do you think about the issue? Is a bug or a feature? :)

**Comment by brockallen** [comment]
We certainly validate the redirect uri. We also have integration tests, so the test for redirect uri validation might be in there.

**Comment by banias** [comment]
Yes you're right, my bad. My tests had an accidentally matching URL in some cases and the unit test above did not cover validation.
