### ISSUE TITLE
any way to remove Bootstrap JS

### ISSUE THREAD

**Issue by ericandrewscott** [IdentityServer/IdentityServer3#3427]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Is there any way to remove the Bootstrap 3 JS from what's delivered in the scripts.js bundle? I have a different UI framework that I want to use and that Bootstrap 3 JS is interfering with it.

**Comment by brockallen** [comment]
https://identityserver.github.io/Documentation/docsv2/advanced/customizingViews.html

**Comment by ericandrewscott** [comment]
Thanks. We're already using a custom `IViewService` The alternative is for us to clone and own both the version of angular and the additional IdentityServer app script that's built off Angular and remove the core script tag from our markup.

**Comment by ericandrewscott** [comment]
I'd also like to prevent the normalize.css from loading if possible.

**Comment by brockallen** [comment]
Sorry, we don't really have anything more modular.
