### ISSUE TITLE
Return error_description during refresh token response

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#3428]
If I send,

```
POST MySite/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Blah

grant_type=refresh_token&refresh_token=Invalid_Refresh_Token
```

I will get,

`{"error":"invalid_grant"}`

How can I include error_description?

I have this class,

`public class AspNetIdentityUserService<TUser, TKey> : UserServiceBase`

**Comment by leastprivilege** [comment]
You can't. It's a refresh token request - this error only has one meaning - the refresh token is invalid.
