### ISSUE TITLE
Explicitly generating access_token response

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#3429]
Due to some business reasons, I need to explicitly generate and get the access_token response. I mean,

```
if (MyComplexBussinessRule()){
   //GetJsonResponseHere  
  // I mean this {"access_token":"......","expires_in":xx,"token_type":"Bearer","refresh_token":"xxxx"}
}

```

Is it possible?

**Comment by brockallen** [comment]
See our OWIN extensions.

**Comment by abcplex** [comment]
Can you show me some code?

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinEnvironmentExtensions.cs#L709

**Comment by abcplex** [comment]
Thanks. My bed, I am using `IdentityServer3.dll, v2.0.0.0`, I mean `packages\IdentityServer3.2.0.0\lib\net45\IdentityServer3.dll`

Any workaround other than upgrade?

**Comment by brockallen** [comment]
No, sorry.

**Comment by abcplex** [comment]
@brockallen I am planning to upgrade from https://www.nuget.org/packages/IdentityServer3/2.0.0 to latest version https://www.nuget.org/packages/IdentityServer3/2.6.0. Due to know any breaking changes? And after upgrading the above extension method will work. Because running site is in production since long time.
