### ISSUE TITLE
Windows Authentication using identity server3 with a login page

### ISSUE THREAD

**Issue by avinashlonkar** [IdentityServer/IdentityServer3#3431]
I want to implement windows authentication using identity server3. The user should get a login page to enter user credentials. The existing samples I found for identity server3 does not have a login page.
Please advise

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by totpero** [comment]
you can use something like this: https://github.com/PCFDev/Owin.Security.ActiveDirectoryLDAP, i did it and works.
