### ISSUE TITLE
Use as OpenID provider for other websites

### ISSUE THREAD

**Issue by naymore** [IdentityServer/IdentityServer3#3433]
### Question / Issue
I wonder if it is possible to use my own identity server as an OpenID provider for other well known websites such as stackoverflow.com. They allow you to sign up using your own identity provider (see https://stackoverflow.com/users/login?ssrc=head&returnurl=http%3a%2f%2fstackoverflow.com%2f) - there is a "more login options" button which lets you enter an "OpenID endpoint address".

**Now my question of course is... does it work?**
What does the link look like stackoverflow.com expects? Couldn't find any information about that. I'm still struggling with the theory behind that... doesn't the client application (e.g. stackoverflow.com) need a valid client to talk to my identityserver?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
