### ISSUE TITLE
ProfileDataRequestContext does not contain IdP or Tenant claims when available.

### ISSUE THREAD

**Issue by tbrettallen** [IdentityServer/IdentityServer3#3437]
- [ x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

While attempting to implement IUserService.GetProfileDataAsync, I discovered that the passed in context only includes the "sub" claim.

For our usage of Identity Provider, we are attempting to create a single authentication endpoint for multiple in-house applications that are all multi-tenant.

So we're using sub for UserId, IdP for the application, and tenant for the tenant.

In order to properly lookup profile data for a user, we need all three of these values.

On line 47 of IdentityServer3/source/Core/ResponseHandling/UserInfoResponseGenerator.cs

`var principal = Principal.Create("UserInfo", new Claim("sub", subject));`

This should include the claims for IdP and Tenant if they exist.

**Comment by brockallen** [comment]
we just fixed this in 2.6
