### ISSUE TITLE
QUESTION: MVC Client Application Dependencies

### ISSUE THREAD

**Issue by wlafrance** [IdentityServer/IdentityServer3#3439]
- [Y ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am upgrading a MVC 3 application and it looks like I will need to push it all the way to MVC5 to leverage the Thinktechture Identity tools in that application.  Is this correct? 

This comes from using the packages
Thinktecture.IdentityModel.Owin.ResourceAuthorization" version="1.1.0" targetFramework="net452"
Thinktecture.IdentityModel.Owin.ResourceAuthorization.Mvc" version="2.0.0" targetFramework="net452"

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
