### ISSUE TITLE
Question: is it possible to have two instances of SSO server acting as one?

### ISSUE THREAD

**Issue by hubaksis** [IdentityServer/IdentityServer3#3440]
Hi,
I have an SSO server (ID3) and would like to make it a fail-safe. That is why I would like to have several copies of this SSO server in another places which will be used in case of failure of the first instance. (The ID3 certificate is the same for them). Bonus task - manage load balancing and switch servers randomly. 

Implementation:
If the first server is down, CNAME record is switched to the second server and the second server starts to respond to the SSO queries. User doesn't know where the request is sent (unless he runs ping command and reveal the actual destination).

Some details if you know Windows Azure:
I have some cloud service instances in different regions and a traffic manager which controls which instance is active.

Issue:
If the sso server is switched to another one, a user is loosing his SSO server authorization and has to authenticate again when this user is switching to another application which has to check user's access. This happens as sso request is sent to a different server (sso's url is the same).

Question:
Is it possible to configure identity server 3 on different servers to make them accept cookies/authorization created by another server? This will help be to create a smooth fail-safe system and configure a proper load balancing.

Thank you.

**Comment by brockallen** [comment]
Yes, it's just an ASP.NET Application. We have docs on this: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

This seems to be a general question about IdentityServer - not a bug report or an issue.

In the future, please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
