### ISSUE TITLE
GetClaimsFromUserInfoEndpoint returns array of roles

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#3441]
Hello!

When using the AspNetCore **OpenIdConnectOptions** with **GetClaimsFromUserInfoEndpoint = true**,
I get the following Identity:

![image](https://cloud.githubusercontent.com/assets/5556013/21762730/ac44c9fe-d65a-11e6-90f9-728928879910.png)

I would expect that I get three "role" claims with the roles as values, but I get one "role" with an array of the roles as JSON.

Is this expected? Is there a way to validate the roles automatically in a policy?

**Comment by leastprivilege** [comment]
That's a bug in asp.net core - you need to update to 1.1

**Comment by senj** [comment]
Ah good hint, thanks for your fast reply.
