### ISSUE TITLE
No state in response at processSigninResponse

### ISSUE THREAD

**Issue by AkhilNaidu09** [IdentityServer/IdentityServer3#3444]
I am getting error in console like No state in response when i use signinRedirectCallback method, but application is working properly. can anybody help me out to fix this issue.

```
Error block

s.signinRedirectCallback().then(function() {
            e.log("Signin Redirect Callback")
        }).catch(function(t) {
            e.error(t) // **Error : No state in response**
        }),

```

**Comment by brockallen** [comment]
You will need to do some more debugging. This might be relevant? https://github.com/IdentityModel/oidc-client-js/issues/238

**Comment by brockallen** [comment]
Any update?

**Comment by RasmusRummel** [comment]
I am having the exact same issue. There were also a StackOverflow question with the same problem, but now solution, ttp://stackoverflow.com/questions/39069842/no-state-in-response-error-with-oidc-client-and-angularjs

**Comment by AkhilNaidu09** [comment]
I'm also trying to resolve this issue from long back but no progress. Can anybody help us to solve it ?

**Comment by brockallen** [comment]
Start from our OIDC JS samples and get those working first. THen make changes for what you need to do.

**Comment by RasmusRummel** [comment]
Indeed using the OIDC JS sample I was able to solve the problem (my understanding of the system was so broken that it was not a single thing that was wrong).

**Comment by brockallen** [comment]
@AkhilNaidu09 please start from the working sample.

**Comment by liujiekm** [comment]
stuck at here too

**Comment by eugyev** [comment]
I had the same error.  Issue for me was that the redirect was occuring before the hash was read.  My understanding is that it is reading the state, access token etc from the hash in the URL.  However, in my code, I called signinRedirectCallback() and a little further down there was a redirect to another URL.  The redirect happened before the signin, so when the code looked for the params in the url, it was empty.  Not sure if you have something similar but I'd make sure the params after the hash in the URL persist and see if you still have the error.

**Comment by GeekJosh** [comment]
@eugyev thanks, that helped me solve the issue in my own Vue SPA. The problem was I was using the 'created' lifecycle hook to redirect, which was not giving the browser chance to parse the Uri. I moved my redirect to 'mounted' and everything now works as expected.
