### ISSUE TITLE
Update claims / Silent re-authentication/ Request New Token

### ISSUE THREAD

**Issue by eclipsed82** [IdentityServer/IdentityServer3#3446]
### Question / Issue
If using OIDC Implicit Flow, how can we do a silent re-sign-in or ask for a new token? The goal is to re-read claims once a user's claims data has been updated in the DB.

**Comment by eclipsed82** [comment]
Similarly, how can we trigger the call of GetProfileDataAsync?

**Comment by brockallen** [comment]
Use your client library and trigger authentication.

**Comment by eclipsed82** [comment]
If the user is already logged in, how would you trigger authentication? The update of claims data is being done directly on the DB while the user is logged in, so I'd like identityserver claims to be updated as well.

**Comment by brockallen** [comment]
You use the API it exports. If that's Katana, then invoke OwinContext.Authentication.Challenge("oidc")

**Comment by hudadabbouseh** [comment]
Thanks, Brock.

I tried running the following code on the Client app: 

`var context = Request.GetOwinContext();`
`((OwinContext)context).Authentication.Challenge("oidc");`

However, after that code runs, I still have all my old claims. I call the method from an Authorized-only page, and then redirect to that same page after the code is run, which does not trigger the authentication. Essentially, it didn't seem like it triggered an authentication, and thus did not request the GetProfileDataAsync/ GetClaims methods.

**Comment by brockallen** [comment]
Not sure then. You'll have to debug on the IS side why it's not calling the get profile API.

**Comment by hudadabbouseh** [comment]
Does that code look right to you? Is there a sample out there that shows what I'm trying to do? (Updating of claims and re-authenticating to get those updated claims)

**Comment by brockallen** [comment]
Yes, and not that I'm aware of.

**Comment by hudadabbouseh** [comment]
Ok thanks. 

Once I get those claims, will cookies be updated accordingly? Here's the exact situation:

1) Logged-in user has Role A. Only users with Role B are authorized to access Client A.

2) Logged-in user tries to access Client A. Client A realizes that the user does not have Role B, so behind the scenes, we find out if they're eligible for Role B. We find they are, so we grant them the role by updating the DB data. 

3) We now want to re-read the claim so Client A is now aware that Logged-in user does in fact have Role B, so it serves the authorized pages.

Going a step further with a different scenario:
Say we want to instead switch it and the user with Role B is logged on to Client A and then there's a trigger that changes their role to Role A, thus no longer having access to Client A. After re-reading those claims, Client A needs to be aware of that change, but it's cookies might think the user is still valid/ authorized. Or am I wrong on this? 

***NOTE***
Let me note that any role/ claims data updates to the DB is done by an app called the Dashboard, which is our user management system. This system shares the Identity Server DB, which uses ASP.Net Identity.  So admins can go on and change roles for users. Or non-admin roles can go on and change their profile data such as their full name. So say they logged on to Client A and the claims they received were Joe Smith. Then they go to the Dashboard to change their name to Josh Smith - we want Client A to have the new claims. So all apps are in sync with the claims and authorization permissions.

Is the above suggestion with the Owin Authentication Challenge still the approach?

**Comment by brockallen** [comment]
> Once I get those claims, will cookies be updated accordingly

If IdentityServer issues a new token, then a new cookie will be written in your MVC app.
