### ISSUE TITLE
Id Token - Refresh Grant flow

### ISSUE THREAD

**Issue by HaroonSaid** [IdentityServer/IdentityServer3#3447]
Is there way to configure Identity Server 3 to return an Id Token (JWT) when the grant flow is refresh token.  Currently only the Access Token is returned

**Comment by leastprivilege** [comment]
No - why do you need it?

**Comment by HaroonSaid** [comment]
We have a mobile & desktop app that get Id Token from IdPs (Azure, Google and Identity Server 3).  The native apps use the Id token to get data from various micro service.  Each microservice needs the Id token to determine the identity of the user to determine what where user can do.  
Google OpenId Connect and Azure V2 both return Id Token on the refresh grant flow.  We want to use the refresh token to improve user experience in the mobile environment and not ask the user to sign in every 60 minutes.

**Comment by leastprivilege** [comment]
You use access tokens to access APIs - not identity tokens. Check the OAuth and OpenID Connect spec.

**Comment by HaroonSaid** [comment]
The Access Token doesn't contain information about users identity. Unless I am looking at the wrong place.  

The spec suggest that Id Token can also be returned:
http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse

12.2.  Successful Refresh Response

Upon successful validation of the Refresh Token, the response body is the Token Response of Section 3.1.3.3 except that it might not contain an id_token.

If an ID Token is returned as a result of a token refresh request, the following requirements apply:

its iss Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
its sub Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
its iat Claim MUST represent the time that the new ID Token is issued,
its aud Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
if the ID Token contains an auth_time Claim, its value MUST represent the time of the original authentication - not the time that the new ID token is issued,
its azp Claim Value MUST be the same as in the ID Token issued when the original authentication occurred; if no azp Claim was present in the original ID Token, one MUST NOT be present in the new ID Token, and
otherwise, the same rules apply as apply when issuing an ID Token at the time of the original authentication.

**Comment by leastprivilege** [comment]
Sure - but still it is not used to secure APIs. Access tokens are used for that.

The contents of both tokens is configurable and up to you.
