### ISSUE TITLE
Exception accessing /core/connect/authorize

### ISSUE THREAD

**Issue by prabhakarreddy1234** [IdentityServer/IdentityServer3#3448]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I am able to authenticate with username and password but after that getting the below errror. I think it is not able to create JWT token. I am using .Net 4.5.2.  System.IdentityModel.Tokens.Jwt 4.0.3.  I tried to update it to 5.1.2 but giving compilation errors.

If i enable Consent, then getting the same error at /core/connect/consent.

![image](https://cloud.githubusercontent.com/assets/1984707/21847419/bead7f88-d7f3-11e6-86d4-d35fec2fbd1a.png)

![image](https://cloud.githubusercontent.com/assets/1984707/21847435/d148f212-d7f3-11e6-8b31-0f6218c45ebe.png)

```
   var factory = new IdentityServerServiceFactory
                              {
                                  ClientStore =
                                      new Registration<IClientStore, ClientService>(
                                      "Db"),
                                  ScopeStore = new Registration<IScopeStore, ScopeService>("Db"),
                                  UserService = new Registration<IUserService>(
                                      resolver => new UserService())
                              };
            var options = new IdentityServerOptions
                              {
                                  SigningCertificate = Certificate.Load(),
                                  Factory = factory,
                                  AuthenticationOptions =
                                      new AuthenticationOptions
                                          {
                                              IdentityProviders = ConfigureIdentityProviders
                                          }
                              };

            app.Map("/core", idsrvApp => { idsrvApp.UseIdentityServer(options); });
```

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
What do you mean with "compilation errors"? are you working with the source code?

**Comment by prabhakarreddy1234** [comment]
No. I am not working with the source code.  compilation errors in my code. I think the version of .net doesn't support  System.IdentityModel.Tokens.Jwt  >5  version.   I have provided the logs for the errors which i am getting. I am not sure if those errors are related to the version  of JWT library.

**Comment by prabhakarreddy1234** [comment]
I think it is failing at _signingService.SignTokenAsync(token) line.  Can you please tell me what could be the possible fix for this.

**Comment by leastprivilege** [comment]
Why would you install the JWT nuget into an IdSrv application? It has it built-in...

**Comment by prabhakarreddy1234** [comment]
I think it has dependency on other libraries. I cannot even uninstall it. 

> Unable to uninstall 'System.IdentityModel.Tokens.Jwt.4.0.2.206221351' because 'Microsoft.IdentityModel.Protocol.Extensions.1.0.2.206221351, Microsoft.Owin.Security.OpenIdConnect.3.0.1, Thinktecture.IdentityModel.3.6.1' depend on it.	

Do you think installing JWT nuget is causing the error at CreateJwtPayload.  Also in the log it shows  "unhandled exception", If we can handle that exception and display some meaningful message then that would be great.
