### ISSUE TITLE
LoginHint is not sent to custom IdP

### ISSUE THREAD

**Issue by craigbroadman** [IdentityServer/IdentityServer3#3449]
### Question / Issue
I am trying to get the login hint sent through to an IdP but it doesn't seem to be working

I can see the value on the identity server login page, but when I click the link to an External Login the values are not sent through...

![image](https://cloud.githubusercontent.com/assets/5638263/21847833/e7903cf4-d7f5-11e6-86b9-d285fa0d0c25.png)

**Comment by brockallen** [comment]
We don't control the protocols to the external providers. You'd have to manually pass it thru when they redirect.

**Comment by craigbroadman** [comment]
Hi Brock, thanks for your response. 

Looking at the source code I can see that the login hint is contained within the SiginMessage cookie within the "Core" project. The value of this cookie is however protected, so the only way I can see to read the values out is to construct a new MessageCookie<SignInMessage> and call read. However this class only has an internal constructor.

We plan to implement identity server out of the box, using the nuget packages, hence I cannot change any code in core.

At what point in the process can I read the login hint to be able to pass it to an external idp such as google?

Thanks
Craig Broadman

**Comment by brockallen** [comment]
I provided a sample on the PR you created.

**Comment by craigbroadman** [comment]
Thank you for your response. I have tested the sample this morning and it all works as expected.
