### ISSUE TITLE
IssueLoginCookie and Partial Login

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#3450]
Hello,

after Login in PostAuthenticateLocalAsync I check for the acceptance of terms & conditions with a partial login which is working fine!

The other requirement is that after login, a user should be logged in which I achieved with
```C#
            Request.GetOwinContext()
                .Environment.IssueLoginCookie(
                    new AuthenticatedLogin
                    {
                        Name = user.UserName,
                        Subject = model.Id,
                        AuthenticationMethod = "password",
                        IdentityProvider = "local",
                        PersistentLogin = false
                    });
```

Now, is it somehow possible to make to Cookie-based sign in and also get to the PostAuthenticateLocalAsync / Partial Login somehow, or do I have to check for  T&C before issuing the cookie..?

Thanks!

**Comment by brockallen** [comment]
In the normal workflow the main authentication cookie is not issued until after PostAuthenticateLocalAsync and we issue it. If you're issuing it then you are taking over that workflow and probably should not be returning back into the IdentityServer login workflow (via the partial resume url). So in short, I think you're mixing two approachs: partial logins and total login workflow control.

**Comment by duranchen** [comment]
I took over the workflow instead of the normal workflow, and issued cookie,but  How can I set profile(id_token content)?
