### ISSUE TITLE
Adding a Reset Password Page to Mvc View Service

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3451]
I have seen the following post and added the link to AuthenticationOptions
https://stackoverflow.com/questions/31046208/identity-server-v3-custom-page-reset-password

I added the following to the LogonWorkflowController.

[HttpGet]
[Route("core/resetpassword")]
public ActionResult ResetPassword(SignInMessage message)
{
     return this.View();
}

I can see the link but clicking it return a 404.

I cannot figure out what else I need to modify in the MvcViewService and LogonWorkflowController to add the reset password page / view. 

Any assist is greatly appreciated. 

I figured out part of it (SignInMessage message) should be (string signin) 

Could still use an assist with this. To be clear, how do I leverage the signin value?

**Comment by jheckathorn** [comment]
I find deeply frustrating that the last few times I have posted here I have gotten no assistance.
I figured out my own solution however I am not convinced it is the right solution.

This is my solution:

in my custom user service:

        protected override Task<AuthenticateResult> PostAuthenticateLocalAsync(User user, SignInMessage message)
        {

            AuthenticateResult authResult = null;
            if (user.MustChangePassword)
            {
                //_owinContext.Environment.Add("Username", user.UserName);
                authResult = new AuthenticateResult("~/changePassword?username=" + user.UserName, (IEnumerable<Claim>)null);
            }

            return Task.FromResult<AuthenticateResult>(authResult);
        }

in my mvc controller: (abridged)

        [HttpGet]
        [Route("core/changePassword")]
        public ActionResult ChangePassword(string username)
        {
            var model = new ChangePasswordModel();
            model.Username = username;
            return View(model);
        }

        [HttpPost]
        [Route("core/changePassword")]
        public async Task<ActionResult> ChangePassword(ChangePasswordModel model)
        {
            if (model.NewPassword != model.ConfirmPassword)
            {
            }
            if (ModelState.IsValid)
            {
            }
            return View();
        }

**Comment by leastprivilege** [comment]
I am sorry you are frustrated. This is not a commercial support forum and we "work" here whenever time allows.
There are commercial options that include SLAs on support questions. Let me know if you are interested in that.

---
Dominick Baier

		_____________________________

**Comment by jheckathorn** [comment]
My frustration is not in the time it takes to get a response. It was with not getting one at all. 
I understand that you, and the rest of the development team, have other obligations. I also deeply appreciate the work you have done and the general thoroughness of the documentation and samples provided.

I would be intersted in commercial options. Please direct me to more information regarding these options and I will submit a request on my side to get it approved.

**Comment by leastprivilege** [comment]
Contact us directly at identity@leastprivilege.com 

---
Dominick Baier




On Fri, Jan 13, 2017 at 7:44 PM +0100, "jheckathorn" <notifications@github.com> wrote:












My frustration is not in the time it takes to get a response. It was with not getting one at all.

I understand that you, and the rest of the development team, have other obligations. I also deeply appreciate the work you have done and the general thoroughness of the documentation and samples provided.


I would be intersted in commercial options. Please direct me to more information regarding these options and I will submit a request on my side to get it approved.

**Comment by jheckathorn** [comment]
I think I may have found a bug related to the above code.

Once I redirect to the ChangePassword page, the resumeUrl as seen below throws an error when I attempt to redirect back.

var resumeUrl = await ctx.Environment.GetPartialLoginResumeUrlAsync();
return Redirect(resumeUrl);

I was unable to get a detailed description of the exception beyond a request id.

Request Id: 8000244e-0006-ec00-b63f-84710c7967bb
