### ISSUE TITLE
Where store the signing certificate in shared hosting?

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer3#3453]
I want to deploy my instance of IdentityServer v3 to the shared .net hosting and I don't how can I solve the location of the signing certificate. On my shared hosting isn't any location for upload certificates.

I've tried use the sample code for getting the certificate like this:
```cs
public static X509Certificate2 Get()
		{
			var assembly = typeof(CertificateHelpers).Assembly;
			using (var stream = assembly.GetManifestResourceStream("IdServer.Certificate.idsrv3test.pfx"))
			{
				return new X509Certificate2(ReadStream(stream), "idsrv3test");
			}
		}
```

I've tried to generate my own signing certificate like this:
```
makecert.exe ^
-n "CN=IdSrvCert" ^
-r ^
-pe ^
-a sha512 ^
-len 4096 ^
-cy authority ^
-sv IdSrvCert.pvk ^
IdSrvCert.cer

pvk2pfx.exe ^
-pvk IdSrvCert.pvk ^
-spc IdSrvCert.cer ^
-pfx IdSrvCert.pfx ^
-po P$ssw0rd
```

If I've used method for getting the certificate above I get this error:
`Exception Details: System.Security.Cryptography.CryptographicException: The system cannot find the file specified.`

But with `idsrv3test.pfx` this certificate it works fine.
How can I solve this problem?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
