### ISSUE TITLE
Stroring and using id_token for all desktop applications

### ISSUE THREAD

**Issue by vpetrovic** [IdentityServer/IdentityServer3#3454]
I am new to IdentityServer and I am exploring features that might be used in our environment. We would like to implement SSO for our desktop (WinForms) and web (ASP.NET) applications.
Is it possible to implement a scenario where user authenticates with IdentityServer only once (in first application that he wants to use)  and then use an id_token for all WinForms (and web) applications on his PC? Is there a place to store information that current user is already logged in?
It would be great if there is some documentation for this requirement.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
