### ISSUE TITLE
Client secret in resource owner flow?

### ISSUE THREAD

**Issue by mrochon** [IdentityServer/IdentityServer3#3455]
I am using the resource owner flow, which by spec only requires client secret if the auth server says so, which IDS seems to do. I am concerned that since I am using the client id/secret from a public client someone may reuse these values and get an auth token using the client credentials flow. Obviously the resource server would still need to accept such a token but if there was a validation error it might pass. Is there a way to disallow use of this client credential for client credentials flow? Is there a way to allow resource owner flow without a client secret?

**Comment by leastprivilege** [comment]
In IdentityServer3 that is a requirement - we relaxed that in IdentityServer4.
