### ISSUE TITLE
Unable to redirect back to login with resumeUrl

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3456]
I believe I may have found a bug. 
I have created a reset password option during login. I have done so as follows.

Added to AuthenticationOptions:

LoginPageLinks = new List<LoginPageLink> {
                        new LoginPageLink
                        {
                            Href = "resetpassword",
                            Text = "Reset Your Password",
                            Type = "resetpassword"
                        }
                    }

The controller is setup like so:

        [HttpGet]
        [Route("core/resetpassword")]
        public async Task<ActionResult> ResetPassword(string signin)
        {
            var model = new ResetPasswordModel()
            {
                Username = "",
                ErrorMessage = ""
            };
            return View(model);
        }

        [HttpPost]
        [Route("core/resetpassword")]
        public async Task<ActionResult> ResetPassword(ResetPasswordModel model)
        {
            var ctx = Request.GetOwinContext();

            // find the URL to continue with the process to the issue the token to the RP
            var resumeUrl = await ctx.Environment.GetPartialLoginResumeUrlAsync();
            return Redirect(resumeUrl);
        }
Nothing fancy just to the page click a button and redirect to resumeUrl.

Logs are not revealing much.

iisexpress.exe Information: 0 : 2017-01-13 16:31:56.568 -07:00 [Information] rendering login page
iisexpress.exe Information: 0 : 2017-01-13 16:32:10.437 -07:00 [Information] Callback requested to resume login from partial login
iisexpress.exe Error: 0 : 2017-01-13 16:32:10.442 -07:00 [Error] Missing AuthenticateResultClaimTypes -- rendering error page

**Comment by brockallen** [comment]
When you return (aka resume) from a partial login you are expected to have certain claims.  If you don't set them then you'll get this error. Check the docs on partial logins: https://identityserver.github.io/Documentation/docsv2/advanced/userService.html
