### ISSUE TITLE
Include id_token in response from refresh token request

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3#3458]

**Comment by leastprivilege** [comment]
tracked https://github.com/IdentityServer/IdentityServer4/pull/694

**Comment by brockallen** [comment]
done

**Comment by guwer** [comment]
What is this for? Is it possible to disable id token in refresh token response? This is strange because now it is not possible to get id token in password grant but with refresh_token grant I receive id token whether I want it or not.

**Comment by leastprivilege** [comment]
Please open a bug issue for that
