### ISSUE TITLE
Identity Server Authenticating One Application Against Another

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3461]
This may be outside the scope of Identity Server but I am hopeful that I can get some assistance here.

I want to have Identity Server authenticate one application against another. In other words, verify that one application is allowed to communicate with another regardless of the user.

Application B needs to know if Application A is allowed to make requests regardless of who the user is or if there is a user logged in at all.

Is this doable with Identity Server? If it is, can I get some direction on how to approach it?

**Comment by brockallen** [comment]
Yes, this is outside the scope of the issue tracker for IdentityServer. SO is a better place for these questions. Thanks.
