### ISSUE TITLE
Introspection Endpoint Error 405

### ISSUE THREAD

**Issue by JhDocs** [IdentityServer/IdentityServer3#3465]
Hi, I would like to validate the access token at my angular2 SPA by making a post request to the introspection endpoint and I received the following error:

`XMLHttpRequest cannot load https://localhost:44388/connect/introspect. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 405.`

I have no issue using the identity validation endpoint to retrieve the claims from my id_token. Am I not supposed to use the introspection endpoint to validate my access token from my client application?

**Comment by leastprivilege** [comment]
Access tokens are not validated at the client - but at the recipient (e.g. an API). 

That's why we didn't enable CORS for introspection.

**Comment by JhDocs** [comment]
Thanks for your quick reply, that solved my doubt.

I was trying to check if the access token stored in the localstorage is still valid before calling the userinfo endpoint. I guess I will have to make a request to userinfo endpoint and refresh the access token if the request failed.
