### ISSUE TITLE
One user access multiple clients - IdentityServer3

### ISSUE THREAD

**Issue by dsblumer** [IdentityServer/IdentityServer3#3467]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Is it possible to share the same user token between several clients ? for example:
I have a client A and a Client B, when the user loggin in the site A, the user must to access the site B, without log in again or allow the access(througth allow page).

I my case, after the user loggin in the site A, when him acces the site B, the allow page is showed up to the user allow the site B acces his profile, so after allow the site B access his profile, the site A will ask again for authorization.

I would like to keep the both sites opened in two browsers instances with only one login, and the second site authenticate automatically can you guys show me some example, how to do this ?

bellow my scenario:

I have only one Idsvr in http://localhost/sso/ 
And my clients are inhttp://localhost/sso1/ and http://localhost/sso2/ configuring using: 

### Relevant parts of the log file
new Client
                {
                    ClientId = @"SSOClient1",
                    ClientName = @"Client 1",
                    ClientSecrets = new List<Secret>
                    {
                        new Secret("userSSO".Sha256())
                    },
                    Enabled = true,
                    Flow = Flows.Hybrid,
                    RequireConsent = true,
                    AllowRememberConsent = true,
                    
                    RedirectUris = new List<string>
                    {
                        "http://localhost/sso/"
                    },
                    PostLogoutRedirectUris = new List<string>
                    {
                        "http://localhost/sso/"
                    },
                    AllowAccessToAllScopes = true,
                    AccessTokenType = AccessTokenType.Jwt
                },
                 new Client
                {
                    ClientId = @"SSOClient2",
                    ClientName = @"SSO Client 2",
                    ClientSecrets = new List<Secret>
                    {
                        new Secret("idsrv3test".Sha256())
                    },
                    Enabled = true,
                    Flow = Flows.Hybrid,
                    RequireConsent = true,
                    AllowRememberConsent = true,
                    RedirectUris = new List<string>
                    {
                        "http://localhost/sso1/"
                    },
                    PostLogoutRedirectUris = new List<string>
                    {
                        "http://localhost/sso1/"
                    },
                    AllowAccessToAllScopes = true,
                    AccessTokenType = AccessTokenType.Jwt
                },

            //The both Client code are the same, unless the userid and secret:

           AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "SSOClient1",
                Authority = IdServBaseUri,
                RedirectUri = ClientUri,
                PostLogoutRedirectUri = ClientUri,
                ResponseType = "code id_token token",
                Scope = "openid profile roles offline_access api1 api2",

                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "role"
                },

                SignInAsAuthenticationType = "Cookies",
                //UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    AuthorizationCodeReceived = async n =>
                    {
                        // use the code to get the access and refresh token
                        var tokenClient = new TokenClient(
                            TokenEndpoint,
                            "SSO",
                            "userSSO");

                        var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(
                            n.Code, n.RedirectUri);

                        if (tokenResponse.IsError)
                        {
                            throw new Exception(tokenResponse.Error);
                        }

                        // use the access token to retrieve claims from userinfo
                        var userInfoClient = new UserInfoClient(
                        new Uri(UserInfoEndpoint),
                            tokenResponse.AccessToken);

                        var userInfoResponse = await userInfoClient.GetAsync();

                        // create new identity
                        var id = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType);
                        id.AddClaims(userInfoResponse.GetClaimsIdentity().Claims);

                        id.AddClaim(new Claim("access_token", tokenResponse.AccessToken));
                        id.AddClaim(new Claim("expires_at", DateTime.Now.AddSeconds(tokenResponse.ExpiresIn).ToLocalTime().ToString()));
                        id.AddClaim(new Claim("refresh_token", tokenResponse.RefreshToken));
                        id.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                        id.AddClaim(new Claim("sid", n.AuthenticationTicket.Identity.FindFirst("sid").Value));

                        //n.AuthenticationTicket = new AuthenticationTicket(
                        //    new ClaimsIdentity(id.Claims, n.AuthenticationTicket.Identity.AuthenticationType, "name", "role"),
                        //    n.AuthenticationTicket.Properties);

                        n.AuthenticationTicket = new AuthenticationTicket(
                                    id,
                                    n.AuthenticationTicket.Properties);
                    },

                    RedirectToIdentityProvider = n =>
                    {
                        // if signing out, add the id_token_hint
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }

                        }

                        return Task.FromResult(0);
                    }
                }
            });
```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
