### ISSUE TITLE
Authorize calling client in action method of resource server

### ISSUE THREAD

**Issue by DeveTho** [IdentityServer/IdentityServer3#3471]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I'm sorry to disturb you with this, but I was wondering if someone would have suggestions for my specific use case. I'll try to explain it with my scenario as example, if that's okay.

I've got a viewer that is registered as a client (using the implicit flow) in my IdentityServer project. It's just used as a UI and doesn't contain real logic. That logic is located in a web API service that the viewer calls using the access tokens from the provider (IdentityServer).

The web API also has a register method, to create new users, and the viewer provides a, well, view for that. The thing is that I'd like to prevent the register method from being publicly available so it can only be used by specific clients specified in the IdentityServer configuration (the viewer), and I'm not sure how to achieve this. I've thought of using the [`ScopeAuthorize`](https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/master/source/WebApi.ScopeAuthorization/ScopeAuthorizeAttribute.cs) attribute, so only clients with a specific scope could access the method. Though since the register method would be called in the viewer anonymously, I don't really have an access token to send which leads to me not knowing what to send so the API could retrieve the calling client's scopes.

I hope it makes sense and thanks in advance for any helpful comments. :)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by DeveTho** [comment]
Sorry for bothering then! I'll post it there, thanks for the reply still.
