### ISSUE TITLE
Custom implemantation of MVC To Api question

### ISSUE THREAD

**Issue by walterfranssen** [IdentityServer/IdentityServer3#3472]
### Question
Hello, 
We use IdentityServer3 and we have a custom implementation of IUserService. We can login and it work fine from an mvc application. But if the mvc application needs information from an Web Api we needs to have an implementation also for this (I think). Can some one tell me witch one, or have an example for this.

Al the settings for scopes and client are oke, according to the logging :)

**Comment by brockallen** [comment]
Your  MVC app wants to call APIs? Then have it request resource scopes. Check the docs and sample for more info.
