### ISSUE TITLE
UserInfo not properly filling in requested claims.

### ISSUE THREAD

**Issue by tbrettallen** [IdentityServer/IdentityServer3#3473]
- [ x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Issue

I am having the same issue as #1447.

I have a scope defined as "data_privilege_ministry" which has two scope claims defined "data_privilege_ministry_read" and "data_privilege_ministry_write" that contains an array of ministry ids that the authenticated user has read or write access to.

Using resource owner flow with reference tokens, when I authenticate against /connect/token, it calls my override GetProfileDataAsync, passing in "data_privilege_ministry_read" and "data_privilege_ministry_write" as requested claims correctly.

However since it's a reference token, a subsequent call needs to be made to UserInfo to get the claims.

Using the returned access token, I then make a call to UserInfo. In this request, it also calls my override of GetProfileDataAsync, the log shows the "data_privilege_ministry" scope is present, but only contains the requested claim of "sub".

### Log

Attached is the log from our logging service:

![requested_claims_log](https://cloud.githubusercontent.com/assets/3762313/22155083/d6243f56-def3-11e6-9a0e-10ee3dbd5e6a.png)

**Comment by brockallen** [comment]
Are the types of your scopes identity or resource? That affects which token the claims go into.

Also, putting permissions into the claims is not the right design: https://leastprivilege.com/2016/12/16/identity-vs-permissions/

**Comment by tbrettallen** [comment]
> Are the types of your scopes identity or resource?

Thank you! Changing to Identity made it come back in UserInfo.

> putting permissions into the claims is not the right design: 

I'm attempting to localize Authentication and Authorization into one service, and since UserInfo refreshes every time it's called, and the permissions are only for client consumption (server side enforces separately), I figured UserInfo would be easy way to implement it.

I could create a new ApiController or CustomGrantType for handing UserPermissions, but CustomGrantType seems like it would be incorrect as well. ApiController however I've had issues adding a new one. Still comes up 404 even though it shows up in swagger if I add that (which surprisingly the token/userinfo endpoints do not show up in swagger).

**Comment by tbrettallen** [comment]
I have the following attempt to register the second API controller, using the example provided by @ChrisVinall in ticket #812. but it's still coming back as 404. when I try to go to localhost:44333/api/UserPermissions


```
    public class Startup
    {
        private static ILogger Log = LogManager.GetCurrentClassLogger();

        public void Configuration(IAppBuilder app)
        {
            app.Map("", ConfigureInMemory);
            //app.Map("", ConfigureEntityFramework);

            app.Map("/api", customApp =>
            {
                app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "https://localhost:44333",
                    ValidationMode = ValidationMode.ValidationEndpoint,
                    DelayLoadMetadata = true
                });
                var httpConfig = new HttpConfiguration();
                httpConfig.Services.Replace(typeof(IHttpControllerTypeResolver), new HttpControllerTypeResolver());
                WebApiConfig.Register(httpConfig, config =>
                {
                    config.Routes.MapHttpRoute(
                        name: "DefaultApi",
                        routeTemplate: "{controller}/{id}",
                        defaults: new
                        {
                            id = RouteParameter.Optional
                        }
                    );
                });
                customApp.UseWebApi(httpConfig);
            });
        }

        // <Snip>
    }
    public class HttpControllerTypeResolver : IHttpControllerTypeResolver
    {
        public ICollection<Type> GetControllerTypes(IAssembliesResolver _)
        {
            var httpControllerType = typeof(BaseApiController);
            return typeof(HttpControllerTypeResolver)
                .Assembly
                .GetTypes()
                .Where(t => t.IsClass && !t.IsAbstract && httpControllerType.IsAssignableFrom(t))
                .ToList();
        }
    }

    public class UserPermissionsController : BaseApiController
    {
        [Route("UserPermissions")]
        public object Get()
        {
            // <snip>
        }
    }
```

**Comment by brockallen** [comment]
user permissions is beyond the scope of what we can help with here on the issue tracker

**Comment by tbrettallen** [comment]
I've resolved my issue, thanks for your advice and assistance!

For future travelers, I had to flip the following, since it was matching "" before it could see and match "/api"

```
    app.Map("", ConfigureInMemory);
    app.Map("/api", customApp =>
        //<snip>
```

should have been

```
    app.Map("/api", customApp =>
        //<snip>
    app.Map("", ConfigureInMemory);
```
