### ISSUE TITLE
Conditionally set ids authentication cookie lifetime

### ISSUE THREAD

**Issue by olonga** [IdentityServer/IdentityServer3#3475]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Right now, I am statically setting CookieOptions under AuthetnicationOptions:
CookieOptions = new CookieOptions
                    {
                        ExpireTimeSpan = TimeSpan.FromHours(1)
                    };

However, I need to set the expiration duration for ids cookie for a user based on what ip address the user is coming from. For example, if the user is coming from intranet, will have lifetime of 8 hours and if from internet, will be 60 minutes.  
I set the following after the user is successfully authenticated,
context.AuthenticateResult = new AuthenticateResult(context.UserName, context.UserName/*, claims*/);
However, AuthenticateResult does not let me set any cookie related properties. Is there a way I can inject cookie lifetime options right before cookie is created? 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
You would need to do this in a custom login page. To build a 100% custom login page, you need to break out of IdentityServer's login workflow. From PreAuth in your user service, you should issue a partial login. Check the docs and samples for this.

**Comment by olonga** [comment]
Thanks @brockallen. Is there a particular sample I should look at? I looked at CustomLoginPage sample & I can follow the example but once I return to ids from the custom login page, does it not resume the normal ids login workflow? So I am not sure I understand how issuing a partial login would it help me set a custom auth cookie lifetime?

**Comment by brockallen** [comment]
Yes, this sample: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomLoginPage

**Comment by olonga** [comment]
After authenticating the user & calling issueLoginCookie (I am guessing I have to supply set of user claims here as well even though the sample does not do it, since I am taking over
ids cookie creation process), when I return to env.GetSignInMessage(id).ReturlUrl, which method of UserService does it hit, since ids still has to issue access_tokens, etc for the user?

**Comment by brockallen** [comment]
> I am guessing I have to supply set of user claims here as well even though the sample does not do it, since I am taking over ids cookie creation process

Up to you -- these claims just go into the cookie at IS. 

> when I return to env.GetSignInMessage(id).ReturlUrl, which method of UserService does it hit

The GetProfile, IsActive, and Signout (IIRC)

**Comment by olonga** [comment]
Thanks @brockallen.

**Comment by olonga** [comment]
However, I also have external identity providers listed on the login page so users could login with external accounts as well. However OwinEnv extension does not seem to have the methods to list the external providers integrated with ids though? So, I think I have to use Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes() to do this.. just wanted to confirm with you. Thanks.

**Comment by brockallen** [comment]
Yes, something like that. Check our default authentication controller code to be certain.

**Comment by olonga** [comment]
Cool. Thanks.

**Comment by olonga** [comment]
Sorry about reopening this again. After looking at AuthenticationController, it does quite a bit of things before displaying the login view which I would like to do as well in my custom login view and for some of them I need access to current instances of IClientStore & IdentityServerOptions..  For example, in order to find out IdentityProviderRestrictions or client name or logo uri, I need access to ClientStore.  Similarly, in order to see if local login is enabled for the client or to display any other extra loginPageLinks, I need access to IdentityServerOptions.. Is this possible?

**Comment by brockallen** [comment]
Yes, there's a lot of stuff happening in here. If you need the control, then you'd have to do something similar. The other idea is to put your own middleware in front of IS that re-issues the cookie as needed. I've not tried it myself -- was just an idea.

**Comment by olonga** [comment]
Thanks @brockallen. Would you care to explain a bit more.. not sure I follow.. what would that middleware be doing with the cookie? I thought I would be issuing the cookie via IssueLoginCookie method from owin extension.  How would that help me get the current instances of IClientStore or IdentityServerOptions for instance.. Thanks.

**Comment by brockallen** [comment]
> I thought I would be issuing the cookie via IssueLoginCookie method from owin extension.

I'm just saying that you can always put middleware around IS to know when it should re-issue the cookie via the OWIN extensions. I don't have the list of all of those scenarios -- you'd have to figure that one out on your own, but I bet from the URL path and inspecting the responses you could figure it out.

**Comment by olonga** [comment]
Ok.. One thing I just thought of just to make this task easier.. I could just add list of temporary claims on the partial login cookie (would have all the info I need regarding the client) which I would read from the custom login controller via Owin context.. What do you think?
context.AuthenticateResult = new AuthenticateResult("~/custom/login?id=" + _owinContext.Request.Query.Get("signin"), 
(IEnumerable<Claim>
{
  new Claim("siteName", "") //add any client info you need from custom login controller here
}));

**Comment by brockallen** [comment]
Another idea -- set a flag in the OWIN environment from the custom user service and then in this new middleware set the cookie based on the settings you need when this flag is set.

**Comment by olonga** [comment]
Yep... Thanks.
