### ISSUE TITLE
ASP.NET MVC application Identityserver jmeter test

### ISSUE THREAD

**Issue by didou000** [IdentityServer/IdentityServer3#3477]
Hello

I would like to use jmeter for performance testing on an ASP.NET MVC application. Authentication is based on Identitityserver, i can not configure jmeter, (authentification failed). I try to use windows and password login (via an http authorization manager) without sucess. In debug, i know that

`HttpContext.Current.User`

is alway empty.

I tried to capture the frames of an authentication with firefox but without result.

If someone has already done this type of tests (with jmeter or other tool) an help would be appreciated.

thanks a lot

Didier

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
