### ISSUE TITLE
Allow customization of x-frame-options header for authentication pages

### ISSUE THREAD

**Issue by garymacpherson** [IdentityServer/IdentityServer3#3478]
Has there been any progress or update on allowing the customisation of the x-frame-options header for authentication pages to allow embedding a login page in an iframe within an app?

All I can find is the update on https://github.com/IdentityServer/IdentityServer3/issues/769 of "Closing. We'll be able to once browsers have more support (like CSP2 or whatever else comes along to help)."

**Comment by leastprivilege** [comment]
Nothing has changed. It is still a security problem to embed the login page.

**Comment by Haleni888** [comment]
Most of the browsers now support either [x-frame-options ALLOW-FROM](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) or [csp2 frame-ancestors](http://caniuse.com/#feat=contentsecuritypolicy2).
Having the ability to render login page within an iframe in the client gives a significantly better user experience than popup.
Is it easier to implement using IdentityServer4 where UI is fully customized?

**Comment by garymacpherson** [comment]
So I thought it was best to put the result of my investigation here in case someone else comes looking for it.

Note: this is not an endorsement to use it, I really dislike it as a solution but it is for an internal application, business requirement, dragons ahead etc. etc.

1 Add the following to your web.config - first to add CSP headers to allow the pages to be hosted in an iframe from your specific domain. The second is to remove the blocking headers that IdSvr3 puts in.

    <system.webServer>
    <httpProtocol>
      <customHeaders>
        <add name="Content-Security-Policy" value="frame-ancestors https://*.mydomainthatiwanttohaveauthinaniframe.com" />
      </customHeaders>
    </httpProtocol>
    <rewrite>
      <outboundRules>
        <rule name="Rewrite X-Frame-Options Header" patternSyntax="Wildcard" stopProcessing="false">
          <match serverVariable="RESPONSE_X-Frame-Options" pattern="*" />
          <action type="Rewrite" value="" />
        </rule>
      </outboundRules>
    </rewrite>
    <system.webServer>

2 You now need to protect each of your pages against older browsers that ignore CSP (Stay awesome IE). You need to use the standard approach of creating a templates folder which contains new html files to replace the default ones. For pages that you never want in an iFrame you need to include - 

    <style id="antiClickjack">
        html {
            display: none !important;
        }
    </style>

    <script>
        if (self === top) {
            var antiClickjack = document.getElementById("antiClickjack");
            antiClickjack.parentNode.removeChild(antiClickjack);
        } else {
            top.location = self.location;
        }
    </script>

For pages that you want to allow in an iFrame from a specific domain, you must add the following.

    <style id="antiClickjack">
        html {
            display: none !important;
        }
    </style>

    <script>
        var getLocation = function (href) {
            var l = document.createElement("a");
            l.href = href;
            return l;
        };
        var referrer = getLocation(document.referrer);

        if(self === top) {
            var antiClickjack = document.getElementById("antiClickjack");
            antiClickjack.parentNode.removeChild(antiClickjack);
        } else {
            var myDomain= "mydomainthatiwanttohaveauthinaniframe.com";

            if ((referrer.hostname.length - referrer.hostname.indexOf(myDomain)) === myDomain.length) {
                var antiClickjack = document.getElementById("antiClickjack");
                antiClickjack.parentNode.removeChild(antiClickjack);
            } else {
                top.location = self.location;
            }
        }
    </script>

**Comment by brockallen** [comment]
> dragons ahead etc. etc.

Closing on that note :)
