### ISSUE TITLE
Identity Server with WsFederation

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer3#3481]
Hello.

I am having an issue resolving bypassing the screen when WsFederation returns back to OpenId.
Please check the following structure:
![owin](https://cloud.githubusercontent.com/assets/3589518/22213472/4bcee338-e18c-11e6-8dfc-e329b69a9562.png)

I can easily bypass openId screen by sending acr_values: idp:Federation, but when wsFederation custom sso redirects back to openId I see "please wait..." openId screen. Is it possible to bypass this screen as well here? I know wsFed has to communicate with openId logically, but I would like this to happen in background and there is not any screen displayed.

How to achieve that? I wrote more details here: http://stackoverflow.com/questions/41811424/wsfederation-to-sso-parameters-openid

**Comment by scottbrady91** [comment]
Answered on SO.
