### ISSUE TITLE
Angular2OidcClient - Javascript Client Error

### ISSUE THREAD

**Issue by DoubleExposure** [IdentityServer/IdentityServer3#3485]
I am testing the Javascript implementation of a client application titled--> Angular2OidcClient-master

The URL is as follows
`https://testidentity/core/connect/authorize?client_id=test.javascript.client&client_secret=secret&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&response_type=code%20id_token%20token&scope=openid%20profile%20read%20write%20offline_access%20testapi&state=23fdc6199f73482eaf9bce4b297e7921&nonce=0ec4b1a9274f4fbe9fa1f80b3b04d9ce`

The error message is 
**The client application is not known or is not authorized.**

The Client data is being pulled from a MembershipReboot Client table. 
The Log file says:
```
w3wp.exe Information: 0 : 2017-01-25 10:29:08.447 -06:00 [Information] End authorize request
w3wp.exe Information: 0 : 2017-01-25 10:29:12.451 -06:00 [Information] Start authorize request
w3wp.exe Information: 0 : 2017-01-25 10:29:12.451 -06:00 [Information] Start authorize request protocol validation
w3wp.exe Error: 0 : 2017-01-25 10:29:12.451 -06:00 [Error] "Invalid redirect_uri: http://localhost:4200/"
 "{
  \"ClientId\": \"test.javascript.client\",
  \"ClientName\": \"Test javaScript Client\",
  \"RedirectUri\": \"http://localhost:4200/\",
  \"AllowedRedirectUris\": [],
  \"SubjectId\": \"unknown\",
  \"Flow\": \"AuthorizationCode\",
  \"RequestedScopes\": \"\",
  \"Raw\": {
    \"client_id\": \"test.javascript.client\",
    \"client_secret\": \"secret\",
    \"redirect_uri\": \"http://localhost:4200/\",
    \"response_type\": \"code id_token token\",
    \"scope\": \"openid profile read write offline_access testapi\",
    \"state\": \"23fdc6199f73482eaf9bce4b297e7921\",
    \"nonce\": \"0ec4b1a9274f4fbe9fa1f80b3b04d9ce\"
  }
}"
```
w3wp.exe Information: 0 : 2017-01-25 10:29:12.451 -06:00 [Information] End authorize request

What would make the redirect URL invalid? This is the default URL of the test application.
Also, The Flow in the database for this client is set to Hybrid based on the following enum values.
public enum Flows
```
    {
        AuthorizationCode = 0,  //introduced in OAuth2 then extended by OIDC.
        Implicit = 1,           //introduced in OAuth2 then extended by OIDC.
        Hybrid = 2,             //introduced in OIDC
        ClientCredentials = 3,  //OIDC specs didn't extend this flow.
        ResourceOwner = 4,      //OIDC specs didn't extend this flow.
        Custom = 5,
    }
```
 But, the error above shows that the client is set to AuthorizationCode
What could I be doing wrong?

**Comment by brockallen** [comment]
You're passing http://localhost:4200/ as the redirect uri -- does that match your config for the client?

**Comment by DoubleExposure** [comment]
The client configuration is below:

```
const settings: any = {
  authority: 'https://testidentity/core',
  client_id: 'test.javascript.client',
  redirect_uri: 'http://localhost:4200/',
  post_logout_redirect_uri: 'http://localhost:4200/',
  response_type: 'code id_token token',
  scope: 'openid profile read write offline_access testapi',

  silent_redirect_uri: 'http://localhost:4200/',
  automaticSilentRenew: true,
  //silentRequestTimeout:10000,

  filterProtocolClaims: true,
  loadUserInfo: true
};
```

**Comment by brockallen** [comment]
No, in IdentityServer.

**Comment by DoubleExposure** [comment]
Image Below from database:
![javascriptidentityerror](https://cloud.githubusercontent.com/assets/922152/22301864/1c2684c6-e2f2-11e6-93cf-37e1f0212516.png)

**Comment by brockallen** [comment]
This doesn't show redirect URIs.

**Comment by DoubleExposure** [comment]
From [dbo].[ClientRedirectUris] table

![image](https://cloud.githubusercontent.com/assets/922152/22307150/974bbd64-e307-11e6-9424-80f778f346e9.png)

**Comment by brockallen** [comment]
Well, not sure then. But now that I see your other config, why is a JS client making code flow request? Why aren't you using implicit?

**Comment by DoubleExposure** [comment]
I did a test in .NET first that used Hybrid flows because I was calling an API from within the web application using the TokenClient helper class.
So, I copied what I had for the JS client. 

Now, what I just discovered is that something was wrong with the tetapi scope. I removed it from the JS client and the error went away. So now I get routed to the login page of the AuthenticationServer but then get the following error:
.exe Error: 0 : 2017-01-25 14:32:24.318 -06:00 [Error] Exception accessing: /core/login
System.NullReferenceException: Object reference not set to an instance of an object.

Could this be due to using Hybrid flow?

**Comment by brockallen** [comment]
I don't know. You'll need to check the logs and do more debugging.

**Comment by DoubleExposure** [comment]
Thanks
I found the Login error. 
Can you tell me how the following would be done in Javascript?
I need to set the tenant ID for the client. 

  ```
RedirectToIdentityProvider = n =>
                            {

                                if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
                                {
                                    n.ProtocolMessage.AcrValues = "**tenant:**" + **_TenantName**;
                                }


                                // if signing out, add the id_token_hint
                                if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                                {
                                    var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                                    if (idTokenHint != null)
                                    {
                                        n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                                    }

                                }

                                return Task.FromResult(0);
                            },

```

**Comment by brockallen** [comment]
_mgr.signinRedirect({acr_values:"tenant:foo"})

**Comment by DoubleExposure** [comment]
So, is below correct?
If you look at the code it enters the method startSigninMainWindow() but it fails on ----->this.mgr.signinRedirect
without any error.

  startSigninMainWindow() {
    alert("Inside SignInWindow"); //testing only
    this.mgr.signinRedirect({ data: "acr_values:ClientPortal1" }).then(function () {
      console.log("signinRedirect done");
    }).catch(function (err) {
      console.log(err);
    });
  }

**Comment by brockallen** [comment]
No. As I said: 

this.mgr.signinRedirect({acr_values:'tenant:ClientPortal1' })

**Comment by DoubleExposure** [comment]
Much appreciated Brock. Thanks
