### ISSUE TITLE
How do you forward query param to an external provider?

### ISSUE THREAD

**Issue by ayoung** [IdentityServer/IdentityServer3#3489]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am writing a custom OWIN Authentication Middleware to enable an External ID Provider. I am using the `acr_values` parameter to directly bypass the ID3 login screen.

We are given a `launch` code value that needs to be added to the redirect to the External IDP's Authorization Endpoint. I am first calling ID3's Auth Endpoint passing along that `launch` code as a query parameter but I don't know how to get that `launch` value back within my custom `AuthenticationHandler.ApplyResponseChallengeAsync()` method. ID3 does an extra redirect back to itself ( /login?signin=foooooo ) before `AuthenticationHandler.ApplyResponseChallengeAsync()` is called again but this time with the 401 status and the OWIN Auth Challenge. By this time, the original request with that `launch` query param is long gone.

Is there a way to get that `launch` value or pass it along to the External IDP?

**Comment by brockallen** [comment]
You can use the OWIN environment extensions to read the signin message in the event handler.

**Comment by ayoung** [comment]
Are you saying that I should embed the `launch` value into the `acr_values` or would the signin message include all the query params from the original auth endpoint request?

**Comment by brockallen** [comment]
I'm just saying anything you put in acr_values can be obtained before you redirect to the external IdP. What you do with those values at that point is up to you.

**Comment by ayoung** [comment]
Ok. So only `acr_values` are carried over to the next request, right? Just want to be clear.

**Comment by brockallen** [comment]
No, nothing is carried over by default to an external IdP. If you need to augment the params to an external IdP, then that's up to you. And if those values come from the original acr_values, then it's up to you to write that code.

**Comment by ayoung** [comment]
Got it. Thanks. I am prepared to write custom code for this. I just didn't know how to get any of the values from the original request over to the ChallengeAsync. From what you're telling me, `acr_values` is that "window" to which such values pass through.

**Comment by brockallen** [comment]
Yep, because of the extra redirect you notice the original query params are lost. So acr_values will be the best way, IMO

**Comment by ayoung** [comment]
@brockallen How do you get the SignInMessageId without parsing the query param? I'm calling `Context.Environment.GetSignInMessage()` and it returns null but if I pass in an ID there (when debugging) it will return the right one. How do I get the ID at runtime?

**Comment by brockallen** [comment]
It's a bug -- you'll have to grab the id from the query string and pass it into the other overload.

**Comment by ayoung** [comment]
I'll just update to version 2.6.0. Thanks again!

**Comment by brockallen** [comment]
let me know if it's working in 2.6 *wink*

**Comment by ayoung** [comment]
@brockallen its working

![d2a55033bd85f86fdb077fc6f1fb54db0d4543d2c1951a6b174a15d650c8ad90](https://cloud.githubusercontent.com/assets/47586/22392804/576473ce-e4b2-11e6-8ae7-e6d2501ca53f.jpg)

**Comment by brockallen** [comment]
yay

**Comment by ayoung** [comment]
The only thing is that you have to double URI encode the value otherwise it might get split up into separate acr_values when it gets parsed. Not a big deal.
