### ISSUE TITLE
Q: How to reject access to a scope based on user's claims?

### ISSUE THREAD

**Issue by dmitry606** [IdentityServer/IdentityServer3#3491]
### Question / Issue
I have API with 2 scopes: user and admin, and 2 client apps respectively. Only the admin client is allowed to request 'admin' scope. Users may be admins or not. What should I do if a user who is not an admin tries to login into the Admin page? I need to basically check if the user has 'IsAdmin' claim, and if he doesn't, then I should either deny authorization, or issue a token without 'admin' scope. Where is the best place to do such a thing?

**Comment by brockallen** [comment]
Scopes are not designed for user permissions. You should always do user-based authorization checks in the API, and if the user is not allowed return 403.

**Comment by dmitry606** [comment]
My idea is to make authorization scope-based. I want to mark some parts of my API with a custom [Authorize] attribute, something like [AdminScope]. The attribute will return 403 for users who do not have 'admin_scope' in the 'scopes' claim. Now, a user that is allowed to use 'user_api' but not 'admin_api', may try to login in the Admin page. In this case I must exclude "admin_scope" from the result token, right? Where can I do that?

**Comment by theCuriousOne** [comment]
Hey @dmitry606 
Why not using the claims for doing the authorization? 
(We have done it that way, and so far so good, but in a way it couples the Identity server with the API more than we wanted)

**Comment by dmitry606** [comment]
@theCuriousOne 
Yeah, I ended up using claims for authorization. I did not find a straightforward way in IdentityServer3 for using scopes for that, and I am not even sure it's the right thing to do.. I read somewhere that scopes should be used only for partitioning API.

**Comment by theCuriousOne** [comment]
> I read somewhere that scopes should be used only for partitioning API.

Yes @dmitry606 , I have read that to. Scopes are to say which application can access which API for example. And for access rights to a certain methods inside a single API, then use claims. That is what I have also concluded :)
