### ISSUE TITLE
Best practices for passing tokens via messaging systems

### ISSUE THREAD

**Issue by mosdevid** [IdentityServer/IdentityServer3#3492]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We recently started using IdentityServer3. There is a requirement to have the call go via a messaging system (proxy) because of network limitations, which is responsible for routing to the RS.
OAuth asks for TLS or an end to end trusted channel.
Now the message brokers are part of a trusted network, but is it a good idea to have the bearer tokens be in clear text at any point midway? Is this something we should be concerned about or trust the messaging system? Or any other recommended approach?

Thanks!

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io

**Comment by mosdevid** [comment]
Will do - thanks.
