### ISSUE TITLE
How to use login with external provider without implicit flow

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3#3493]
Hello,

I used identityserver to connect mobile app with more than one backend.

In the mobile app, i used resource owner flow for the simplicity to allow users login without any need for webview with the implicit flow.

the question here: I want to implement facebook login. What is the best way to do this? Is it required to call a url in a webview to return access token, or can i use some thing that will return access token as json for me?

Thanks

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
