### ISSUE TITLE
Q: Relation between AspNetIdentity database and IdentityServer3.EntityFramework database ?

### ISSUE THREAD

**Issue by SMRockend** [IdentityServer/IdentityServer3#3494]
I have used IdentityServer3.EntityFramework  library to keep all configuration in SQL database. Also Im using  IdentityServer3.AspNetIdentity plugin for identity management.  I cant find out how to link / map these 2 database together. I mean base on which concepts. 
I suppose i need to have UserId in Config database somehow but cant find it. I really appreciate if someone can help.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
