### ISSUE TITLE
Can I use this software for "single point" identity server

### ISSUE THREAD

**Issue by ebadollahi** [IdentityServer/IdentityServer3#3495]
I want implement a public website for public users on the internet. In this project, I want use many web base software that existing in the market like DNN, Joomla, Wordpress, eLMS, mail enable, MS Exchange, MS CRM, Skype for Business and etc. At the first step I should go to integration these software with unique "identity server". This meant, these software should be work with my "identity server" and don't use their local identities.
For this scenario, can I use your software for "single point" identity server and go to integration of above software with it?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
