### ISSUE TITLE
UseTokenLifetime vs Cookie Expires

### ISSUE THREAD

**Issue by dsblumer** [IdentityServer/IdentityServer3#3497]
> -

 [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hello everybody.

I'm little confuse about the cookie expiration vs UseTokenLifetime = true.

My MVC client is set to AccessTokenLifetime = 600 (10 minutes), i don't know why, but  each every 5 minutes, the user is redirected to "consent page" to allow access to my client MVC app.( I've already read about renew time of the JWT, but i don't understand how it's work)

I have 2 questions:

1 - How can i use the same expiration of the UseTokenLifetime without have to be redirected to the consent page each 5 minutes ? My user must to be redirected in the same time of the expiration of the AccessTokenLifetime.

2 - How can i set the ExpireTimeSpan manually in my MVC client to be different of the tokenlifetime, and after the cookie expiration, the user be redirected automatically to the consent page or authentication page ?

Can u guys explain me better and show me some example to do that ?

Thank you guys and sorry for my english, i'm from brazil.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by scottbrady91** [comment]
`UseTokenLifetime` refers to the Identity token lifetime, which is only 5 minutes long. Not the access token lifetime. An identity token is typically short lived like this, as it's only used to create the user an identity within the application (well, not only but most commonly).

Set `UseTokenLifetime` and use the cookie middleware to set cookie expiration within your client application.

**Comment by dsblumer** [comment]
Thank you @scottbrady91 .

If i use refresh_token, is there a way to renew the id_token to avoid the user be redirected to the consent page ?

I would like to use UseTokenLifetime = true and don't redirected my user to  consent page every 5 minutes.

Is this possiblem ? How can i do this ?

Thanks again
