### ISSUE TITLE
How to soft re-sign in a person in order to get tokens having updated claims?

### ISSUE THREAD

**Issue by hdahldk** [IdentityServer/IdentityServer3#3499]
### Question

I have the following business problem:
*) A person can act in one of several different business roles.
*) A person should be able to sign in with the same credentials no matter the role in which he decides to operate.
*) If the person has not been logged in before, the person will need to select the role by which he would like to operate, before he will be authorized to do role-specific actions.
*) If the person has been logged in before and a role has been chosen, the default role when logged in should be the role from his most recent login.
*) A logged in person should be able to select another role at any time.

I am using:
*) IdentityServer3.
*) IdentityServer3's integration with Asp.NET Identity via Entity Framework.

I have decided to:
*) Model the current role by setting a claim for the person via Asp.NET Identity's UserManager.

The consequence is:
*) When a person decides to select another role for his doings, there is a need to issue a new identity token and a new access token.

The inappropriate but easy approach is to:
*) When the person selects another role, just sign out the person and let the person to sign in again, where the identity token and access token will now hold the claim for the most recently chosen role.

From a business perspective, I would like to achieve:
*) After the person has selected the role for which he wants to change, i.e. by clicking a link on a web form, the person will effectively experience, that the person acts in the new role with no further sign in/sign out activities required by the user.

From a technical perspective, I would like to achieve:
*) Soft-sign out the person and soft-sign in the person. With soft-sign out I mean, that the user does not observe any sign out dialogue and with soft-sign in I mean, that the user does not observe any sign in dialogue.

My questions is:
*) Does it seem reasonable to model such a role concept via a claim?
*) How to achieve the soft-sign out and soft-sign in, I ask about? Comment: As it is still the same person, I suppose the cookie owned by IdentityServer3 can be used to soft-sign in the person. We can perhaps say, that the person should just be re-signed in using the cookie owned by IdentityServer3, but how to achieve that?

**Comment by brockallen** [comment]
This might help: https://leastprivilege.com/2016/12/16/identity-vs-permissions/

But this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
