### ISSUE TITLE
Creating an audit trail using custom event service

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3504]
I have created my own AuditEventService extending IEventService as seen in the example below.

http://developers.de/blogs/armin_kalajdzija/archive/2016/09/23/how-to-audit-login-activity-in-identityserver3.aspx

It tracks the login as designed. 

My question is, can I expand on this to track a change of password or perhaps the creation or deleting of users etc. If so, can you point me in the direction of some information on how I might accomplish this?

**Comment by brockallen** [comment]
Perhaps. The only issue I see is that you'd want to ensure event Ids defined by IdentityServer don't conflict with any custom event Ids from your custom events (such as password change, etc).
