### ISSUE TITLE
How to mimic the consequence of a cookie timing out after OpenIdConnectOptions.UseTokenLifetime = true?

### ISSUE THREAD

**Issue by hdahldk** [IdentityServer/IdentityServer3#3505]
### Question
I have tried to set OpenIdConnectOptions.UseTokenLifetime = true.
This will cause requesting new tokens from IdentityServer as the cookie expires.

Let's assume I would explicitly like to get new tokens, i.e. to achieve exactly the same as what happens when the cookie times out, I just don't want to wait for the cookie to time out.

Is there a simple call to achieve that?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
