### ISSUE TITLE
Partial login & error messages

### ISSUE THREAD

**Issue by olonga** [IdentityServer/IdentityServer3#3508]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Here is a Login flow with external provider such as Google:
https://<ids-url>/external?provider=Google  		       [Success]
https://accounts.google.com/o/auth?response_type=code 	[Success]
https://<ids-url>/signin-google?state= 			        [Success]
https://<ids-url>/callback
AuthenticateExternalAsync: new AuthenticateResult(url) is returned from since there is no internal acct linked to Google account
https://<ids-url>/custom/login?id=<siginid>   [display login page with error message]

Consider a scenario: 
idsrv with custom login page & two/more client mvc apps (App1, App2) secured by authorization code flow which can log in via External IDPs such as Google.

So, a user opens App1 and accesses a secure page and ids redirects the user to custom login page: This creates a partial login (idsrv.partial cookie). His browser shows the url such as:
https://<ids-url>/custom/login?id=<sigininid1>

Then before the  user completes the login process with App1, he opens up another browser tab and tries to log in to App2 which also redirects it to Custom login page. His browser shows the url such as:
https://<ids-url>/custom/login?id=<sigininid2>

However, This causes idsrv to overwrite/replace the previous partial login cookie (idsrv.partial) with the new one for App2, even though I can still see two cookies for SignInMessage.<sigininid1> and SignInMessage.<sigininid2>.

If the user completes the login without any problem it still works fine. However, in a case of any error (such as say the user successfully authenticated via Google, but if he does not have an internal account associated with his Google account), I need to redirect user back to the custom login page with the error (from within AuthenticateExternalAsync). Whenever this happens, I grab the url from GetPartialLoginRestartUrlAsync and redirect the user to the login page. However, since the idsrv.partial login cookie was overwritten by the second login process, App1 now will be redirected to the login url for App2, i.e. if the error event is encountered in App1 login process, App 1 will now be redirected to https://<ids-url>/custom/login?id=<sigininid2> instead of https://<ids-url>/custom/login?id=<sigininid1> which is where the external login process for App1 started from.

My problem basically here is that I don't see a way to correlate the login flow with the client within AuthenticateExternalAsync.  In the event of error with App1, I would like to return back to the
url (with signinid for App1) and not to App2.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Sounds like you should just break out of the login workflow entirely and take over control to achieve what you need.

**Comment by olonga** [comment]
Ok. I overcame this by creating a small cookie with name =  hash (clientId+remote-ip-add) & value = signin-id in PreAuthenticateAsync.
However, now I am facing another challenge that is: once user comes back to AuthenticateExternalAsync after authentication from external idp, I set the following so ids issues a auth cookie for the user:
context.AuthenticateResult = new AuthenticateResult(userInfo.UserName, userInfo.UserName, claims);
Instead of doing that can I just manually create a auth cookie with owin env extensions' IssueLoginCookie() method?

**Comment by brockallen** [comment]
I doubt you can set the IS cookie in there, because the calling code will then also set the cookie based on the AuthenticateResult.

**Comment by olonga** [comment]
Thanks @brockallen. Thinking this through, I don't think it is this important to be able to control the auth cookie timeouts when authenticating the user through an external provider.  If the user chooses to make the login session with the external provider, that will be good enough for ids, as ids will immediately issue a auth cookie as soon as it receives a valid info from external idp.  However, once the user is logged in, it's the application/client's responsibility to maintain it's own session/cookie and all it has to do is to keep the access token alive once it is granted one (via refresh) in order to call the back-end apis.
