### ISSUE TITLE
RNGCryptoServiceProvider has not been disposed

### ISSUE THREAD

**Issue by olegbaev** [IdentityServer/IdentityServer3#3511]
Hi, just wandering is there any reason why in SymmetricDataSecurity.GenerateSalt() RNGCryptoServiceProvider has not been disposed? Should we wrap it into "using" as in the code below?

public byte[] GenerateSalt()
{
	const int saltSize = 32;
	var result = new byte[saltSize];

	// Original IdSrv code - RNGCryptoServiceProvider has not been disposed
	//RNGCryptoServiceProvider.Create().GetBytes(result);

	// Suggested change
	using (var cryptoServiceProvider = RNGCryptoServiceProvider.Create())
	{
		cryptoServiceProvider.GetBytes(result);
	}
	
	return result;
}

**Comment by leastprivilege** [comment]
why?

**Comment by olegbaev** [comment]
RNGCryptoServiceProvider implements IDisposable interface. In .NET any class that implements IDisposable needs to be disposed to avoid resources leakage. 

PS: Dominick, by the way many thanks to you and everybody on the team for Identity Server - I used it for 3 years since earlier editions - great job you have done.

**Comment by leastprivilege** [comment]
We hold on to it - I think this was a perf improvement.

Thanks! Glad you like it.
