### ISSUE TITLE
idsvr.session cookie HttpOnly=false

### ISSUE THREAD

**Issue by jwtvh** [IdentityServer/IdentityServer3#3512]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

What is the reason the idsvr.session cookie is not httpOnly? 
My specific implementation requires all cookies are HttpOnly=true. Code shows it is not configurable. Will it still work when httpOnly for this cookie is set to true?

**Comment by brockallen** [comment]
It's by design. See this spec: https://openid.net/specs/openid-connect-session-1_0.html#ChangeNotification

**Comment by jwtvh** [comment]
If i understand the specs properly (but possible i don't) it is also possible to use offline storage or disable the feature?
Unfortunately one of the audit requirements is that all cookies must be httponly=true...

**Comment by brockallen** [comment]
So then you won't get the concept of single signout for SPAs. The contents are essentially all hashed, and the value is not used as an input anywhere. Don't know if that helps your rigid audit. 

As of now I don't think we have a way to prevent the session cookie from being emitted. Perhaps we should not do so if the check session endpoint is disabled.

**Comment by sreekanthmg** [comment]
I could able to make idsvr as httponly. But idsvr.session not. 
What is the difference between these 2 cookies ?
And any security issue if we dont make idsvr.session as httponly ?

**Comment by brockallen** [comment]
> And any security issue if we dont make idsvr.session as httponly

That cookie is required by the OIDC session management spec for JS/SPA clients. If you change it, you will break those types of clients.

**Comment by jwtvh** [comment]
Thanks, at least that is motivation why the cookie needs to be like it is. We don't use single signon yet, but do have a Spa client. I hope it does help for the audit that the issue and reason is explained here, will let you know. Thanks.

**Comment by brockallen** [comment]
Send the auditors the OIDC session management spec. They really can't argue with it, IMO, and my guess is that they have a simple policy on that without thinking about it or spending the time understanding how it's really being used.
