### ISSUE TITLE
GetProfileDataAsync not getting called to get user profile for 5 min!

### ISSUE THREAD

**Issue by Sivalingaamorthy** [IdentityServer/IdentityServer3#3513]
I facing a strange problem. I use oidc client for client login. I register new user in Identityserver3, I add some custom claims.

When I login, I am not getting the custom claims (user.profile.marketid & user.profile.contactuserid), but the same claims are reflection after approx. 5 min, after the user registration.

I checked the Identityserver3 server code, observed GetProfileDataAsync is not getting called for 5 min for the newly registered user.

After 5 min, I am getting custom claims.

I tried with the samples code provided (asp.net mvc implicit flow), for the same user, found that I am getting all the claims, but I am not getting the same when I use oidc client user manager for login.

I am trying to figure out what is the problem is, is it a configuration issue or what is the problem, can you suggest.

The below are my configuration of IdentityServer3

AbsoluteRefreshTokenLifetime : 2592000
AccessTokenLifetime : 3600
AuthorizationCodeLifetime : 300
ClientId : Portal
ClientName : Portal
IdentityTokenLifetime : 300
SlidingRefreshTokenLifetime : 1296000

Typical code, to get the user profile claims.

mgr.signinRedirectCallback({ data: url })
.then(function (user) {
console.log("signed in", user);
if (user.profile.marketid === undefined || user.profile.contactuserid === undefined) {

Can someone suggest, what is wrong here?

**Comment by brockallen** [comment]
Closing; Dup of this: https://github.com/IdentityModel/oidc-client-js/issues/262
