### ISSUE TITLE
Service - Service communication with certificate not working as expected

### ISSUE THREAD

**Issue by Suthin** [IdentityServer/IdentityServer3#3514]
If I host the identity server code in IIS and call from the other service always getting   "Forbidden" error, but i manged to fix the same by launching the identity server url by using WebApp.Start("url") from other app?

Is there a way to fix this issue?

Thanks,
Suthin

**Comment by brockallen** [comment]
Not enough info or context.

**Comment by Suthin** [comment]
I was playing with "Flows.ClientCredentials" by using x509 certificate validation (SecretTypes.X509CertificateThumbprint).  I used the sample code from the "IdentityServer3-master\source" and deployed the "Host.Web" to my IIS and when i use a client application and try to get the token from the service by passing the certificate always getting the "forbidden" error back, It started working if i run the launch the token service by using "Host.Console" project from the same source code.

Thanks,
Suthin

**Comment by Suthin** [comment]
Adding logs for your reference.

w3wp.exe Information: 0 : 2017-03-14 12:20:34.906 -07:00 [Information] Start token request
2017-03-14 12:20:34.918 -07:00 [Debug] Start client validation
2017-03-14 12:20:34.920 -07:00 [Debug] Start parsing Basic Authentication secret
2017-03-14 12:20:34.922 -07:00 [Debug] Start parsing for secret in post body
2017-03-14 12:20:34.922 -07:00 [Debug] No secret in post body found
2017-03-14 12:20:34.923 -07:00 [Debug] Start parsing for X.509 certificate
2017-03-14 12:20:34.924 -07:00 [Debug] X.509 certificate not found.
w3wp.exe Information: 0 : 2017-03-14 12:20:34.924 -07:00 [Information] Parser found no secret
w3wp.exe Information: 0 : 2017-03-14 12:20:34.927 -07:00 [Information] No client secret found
w3wp.exe Information: 0 : 2017-03-14 12:20:34.929 -07:00 [Information] End token request
w3wp.exe Information: 0 : 2017-03-14 12:20:34.934 -07:00 [Information] Returning error: invalid_client

**Comment by karvendan** [comment]
I also have the same issue and asked the same in http://stackoverflow.com/questions/42803108/response-error-forbidden-in-identityserver3-flows-clientcredentials

**Comment by balamanigandan** [comment]
I also have the same issue and asked the same in http://stackoverflow.com/questions/42803108/response-error-forbidden-in-identityserver3-flows-clientcredentials

**Comment by brockallen** [comment]
@Suthin all set on this issue -- can we close?

**Comment by Suthin** [comment]
Could be a self signed certificate issue, the steps were not working when i tried with self signed certificate.
