### ISSUE TITLE
Auto-logout from IdSvr when issuing access token / redirecting to client

### ISSUE THREAD

**Issue by philpowers** [IdentityServer/IdentityServer3#3515]
Is there a way, on a per-client basis, to automatically logout from IdSvr after authentication has occurred? So basically perform an internal logout from IdSvr AFTER they are authenticated but BEFORE they are redirected back to the RP/client.

I've gone through the documentation, and I think I could almost get what I want by setting the cookie expiration in the AuthenticationOptions to a very small value, but that would affect all of the clients. Can I somehow clear the cookies in PostAuthenticateAsync, etc?

**Comment by brockallen** [comment]
That's not something we have designed for, since after all, that would defeat SSO. Out of curiosity, what's the business requirement around this?

**Comment by philpowers** [comment]
For this one RP application, the intention is to use the server as more of a "centralized" authentication server rather than a SSO server. However we still want to use all the external/social IDPs that have already been configured in the server and also we want to be able to associate those accounts with the SSO accounts,, etc.

For this specific RP application, there is a major concern that most of the logins are going to happen on public machines - and the RP is more of a "sign up" app than anything else (so - one and done, after they authenticate - that's all they need).

**Comment by brockallen** [comment]
It will be tricky to do this from within IdentityServer (since it's not something we have designed for). Your best bet might be to put middleware in front of IdentityServer to remove the authN cookie for successful responses from the authorization endpoint.

**Comment by philpowers** [comment]
Hmm that might work. I'll look into doing that. Thanks for the info and suggestion.
