### ISSUE TITLE
Validate current user without redirect to login page

### ISSUE THREAD

**Issue by vitaly-koltsov** [IdentityServer/IdentityServer3#3516]
Hello,

I'm using IdentityServer3 + few MVC apps (with SSO).  It works perfect except one thing.  

So, for example I have "MVC app 1" and "MVC app 2". Apps have welcome page with header "Sign In" or "<USER_NAME> | Sign out" (depends on logged user).

User goes to "MVC app 1" -> clicks "Sign In" -> redirected to login page -> redirected back to welcome page with good "<USER_NAME>" in the header.  This is fine.

Then he goes to "MVC app 2".  He will be "Unauthorized user" until he does not click on "Sign In" in "MVC app 2" because MVC Controller does not have [Authorize] attribute and there is nothing to trigger "authorization_endpoint" to validate current user (except "SignIn" action because it has [Authorize] attribute).

I would not like to add [Authorize] attribute to MVC Controller because a user should has possibility to see "Welcome page" in both states: logged in and logged out.

Is it possible?

Thanks.

**Comment by vitaly-koltsov** [comment]
Here is a part of my source code (if it may helps):

[Server config]:

```
var options = new IdentityServerOptions {
	SiteName = "Identity Server",
	SigningCertificate = new X509Certificate2(config.CertificateFilePath, config.CertificatePassword),
	Factory = factory,
	LoggingOptions = new LoggingOptions {
		EnableHttpLogging = true,
		EnableKatanaLogging = true,
		EnableWebApiDiagnostics = true,
		WebApiDiagnosticsIsVerbose = true
	},
	AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions {
		EnablePostSignOutAutoRedirect = true,
		EnableSignOutPrompt = false
	}
};

app.Map("/identity", idsrvApp => {
	idsrvApp.UseIdentityServer(options);
});
```

[Client config]:

```
app.UseCookieAuthentication(new CookieAuthenticationOptions {
	AuthenticationType = "Cookies"
});

app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions {
	Authority = config.AuthorityUri,
	ClientId = config.Id,
	Scope = config.Scopes,
	RedirectUri = config.RedirectUri,
	PostLogoutRedirectUri = config.PostLogoutRedirectUri,
	ResponseType = "id_token",
	SignInAsAuthenticationType = "Cookies",
	UseTokenLifetime = false,
	Notifications = new OpenIdConnectAuthenticationNotifications {
		SecurityTokenValidated = n => {
			var id = n.AuthenticationTicket.Identity;

			id.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
			n.AuthenticationTicket = new AuthenticationTicket(
				   id,
				   n.AuthenticationTicket.Properties);

			return Task.FromResult(0);
		},

		RedirectToIdentityProvider = n => {
			if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest) {
				var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
				n.ProtocolMessage.IdTokenHint = idTokenHint;
			}

			return Task.FromResult(0);
		}
	}
});

AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject;
JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
```

[Client]:

```
Client client = new Client {
	ClientId = ...,
	ClientName = ...,
	Enabled = true,
	RequireConsent = false
	RedirectUris = ...,
	PostLogoutRedirectUris = ...,
	AllowedScopes = ...,
	LogoutUri = ...,
	Flow = Flows.Implicit,
	AllowRememberConsent = true,
	LogoutSessionRequired = true,
	AccessTokenType = AccessTokenType.Reference
}
```

Is there something wrong?

**Comment by aedilyan** [comment]
+ I have the same issue

**Comment by theCuriousOne** [comment]
Maybe just add [Authorize] on some methods in the controller of the MVC2 app?
(or maybe I have misunderstood)

**Comment by vitaly-koltsov** [comment]
> Maybe just add [Authorize] on some methods in the controller of the MVC2 app?
(or maybe I have misunderstood)

Do you mean do not add [Authorize] on Welcome page?  In this case a user will not see he is already logged in (I mean there will not request to authentication_endpoint)

But if I will add it to Welcome page then a user will not has ability to see Welcome page while he is logged out.


I was thinking about "Guest" user. It means that if a user is not logged in then the server authenticates him as "Guest" user (without any permissions).  And if he clicks "Sign In" (for example, marked as [Authorize(Roles = "User")]) then we should re-login him.  But i had many problems in user service's callbacks

**Comment by theCuriousOne** [comment]
Why not add in the controller a manual call to the Identity server, so in that case if the user is already logged in he will be "re-logged" if not, then do nothing just show the page. 

It might be more clear if there is a possibility to share the welcome page controller and the view where the sign in is placed?
(omit the functionality, I believe just the method names should be enough)

BTW I believe this is not an identity server problem, this is more of an architectural approach to a problem!

**Comment by vitaly-koltsov** [comment]
> manual call to the Identity server

Do you mean something like this:
```
if (User.Identity.IsAuthenticated && !User.IsInRole("User")) {
      Request.GetOwinContext().Authentication.AuthenticateAsync("Cookies");
}
```

Do you have any example for your suggestion?

Many thanks for help.

**Comment by theCuriousOne** [comment]
Sorry I don't have time for an example (current project with identity server is api based and the ui is angular), but it seems like you are on the right track.
