### ISSUE TITLE
Azure AD callback is not going to AuthenticateExternalAsync

### ISSUE THREAD

**Issue by prabhakarreddy1234** [IdentityServer/IdentityServer3#3517]
I am using `OpenID Connect` to connect to Azure ID, I can successfully authenticate in Azure and get the request coming back to the redirect uri specified in OpenID Azure AD Configuration.

```
 app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                    {
                        AuthenticationType = " TEST",
                        Caption = "Test Azure AD",
                        SignInAsAuthenticationType = signInAsType,
                        ClientId = "<client ID>",
                        Authority = "https://sts.windows.net/<tenantId>",
                        ResponseType = OpenIdConnectResponseTypes.CodeIdToken,
                        RedirectUri = "https://localhost:44392/External/Login", This is another webapi project, not identityserver host. 
                        AuthenticationMode = AuthenticationMode.Passive,
                    });
```

After succesful authentication it is redirecting back to  `https://localhost:44392/External/Login` with Code, IdToken.

Questions :
1. Does it not stop at `AuthenticateExternalAsync` method  on redirection unlike google signin ?
2.  Do i have to decode `IdToken` JWT to get user claims?
3.  In the redirection method, how do i generate `Access Token` from IdSrv3 to authorize other webapis ?
4.  Can a user have both Local Login and Multiple External logins ( Azure AD, Google etc ). In this case how does SSO works with `IDsrv3` ?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
