### ISSUE TITLE
External Provider Redirects Failing in iOS Only

### ISSUE THREAD

**Issue by elryry** [IdentityServer/IdentityServer3#3518]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I am seeing an issue in my IdentityServer3 instance where on redirection back to the /external?provider=etfs is throwing a 404 error only on iOS device browsers. This instance of idsrv has been life for quite a while and we have not experienced this issue in any Desktop or Android based browsers so far. Any ideas on what nuances the iOS browser may have with idsrv regarding this?

When I initiate the login via /permissions endpoint, the flow works fine and there is no 404 error on the /external endpoint. This only happens when initiated by the web client.

Note - the external provider is a custom ws-fed ip-sts. Navigating to sites protected directly by the provider in the iOS browser experiences no issues, so I am thinking this is a idsrv problem.

### Relevant parts of the log file

Not seeing any logs related to this error.

**Comment by pekkah** [comment]
Do you have fragment based redirects? Safari is known to drop the fragment part of the redirect away. This can be bypassed by returning a webpage that does the redirect with javascript.

**Comment by elryry** [comment]
@pekkah the error seems to have changed (on it's own?) to the following JSON response:

`{"Message":"No HTTP resource was found that matches the request URI: <domain>/external?provider=etfs'."}`

**Comment by elryry** [comment]
I was able to track this down. The external provider `ReplyTo` was set to the wrong value of /identity/external instead of /external (hence the 404). What I don't understand is why this is only affecting Safari on iOS (Safari on desktop works fine).
