### ISSUE TITLE
Update AuthenticationOptions at runtime on a per request basis

### ISSUE THREAD

**Issue by adamHarries87** [IdentityServer/IdentityServer3#3520]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I'm trying to implement multi-tenancy in IdentityServer. I want support different AuthenticationOptions for different tenants. The tenant code will be passed in the request. How do I update the supported AuthenticationOptions based on the contents of the request?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This is not supported.
