### ISSUE TITLE
Identity Server 3 issue with logging out - log out doesn't work

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer3#3521]
Hello guys. I have an issue, with little complex architecture.

Original SSO - WSFed authorization (they don't want to update to openID authorization)
Client 1 - Net 4.5
Client 2 - Net Core (net core doesn't support wsfed auth request)
Bridge SSO - Net 4.5 (to make wsfed auth request to Original SSO initiated by Client 2)

Here is architecture with my magical mspaint skills:
![architecture](https://cloud.githubusercontent.com/assets/3589518/22935387/5e2a4fa0-f2ca-11e6-8529-e711f056599e.png)

Legend:
- Client1 - application that can trigger log in and log out to SSO(box on the most top)
- SSO - it is sso which accepts wsfed and returns response in saml to the bridge
- Bridge is an intermediate SSO, because the client2 is net core app and net core doesn't support wsfed authentication(yet or ever), so we had to put intermediate bridge app to take care for  wsfed autnentication request. This app uses UseWsFederationAuthentication to authenticate towards wsfed SSO.

- Client 2 does request to bridge SSO, bridge SSO sends wsfed authorization to original SSO, then SSO sends authorizationresponse to Bridge, and if everything ok, client 2 is logged in.

Problem appears that when I log out from Client 1, it doesn't log out client 2. What am I missing? If you need code I can put all together, but out of head is this architecture supported?

SSO(wsfed) and Bridge SSO(calling wsfed SSO) in the middle and then client?

**Comment by nukec** [comment]
Ok I think I figured it out.
I enabled logging with SeriLog and when logoutcallback is made sid parameter is empty:
core/connect/endsessioncallback?sid=

Error:

> w3wp.exe Information: 0 : 2017-02-15 12:22:36.418 +00:00 [Information] End session callback requested
> 2017-02-15 12:22:36.433 +00:00 [Debug] No client end session iframe URLs

> 2017-02-15 12:22:36.386 +00:00 [Debug] [2017-02-15T12:22:36.3867557Z] Level=Info, Kind=Begin, Category='System.Web.Http.ModelBinding', Id=00000000-0000-0000-c044-0080000000ea, Operation=HttpActionBinding.ExecuteBindingAsync
> 2017-02-15 12:22:36.386 +00:00 [Debug] [2017-02-15T12:22:36.3867557Z] Level=Info, Kind=Begin, Category='System.Web.Http.ModelBinding', Id=00000000-0000-0000-c044-0080000000ea, Message='Binding parameter 'sid'', Operation=ModelBinderParameterBinding.ExecuteBindingAsync
> 2017-02-15 12:22:36.403 +00:00 [Debug] [2017-02-15T12:22:36.4035482Z] Level=Info, Kind=End, Category='System.Web.Http.ModelBinding', Id=00000000-0000-0000-c044-0080000000ea, Message='Model state is invalid. sid.String: A value is required but was not present in the request.', Operation=ModelBinderParameterBinding.ExecuteBindingAsync
> 2017-02-15 12:22:36.403 +00:00 [Debug] [2017-02-15T12:22:36.4035482Z] Level=Info, Kind=End, Category='System.Web.Http.ModelBinding', Id=00000000-0000-0000-c044-0080000000ea, Message='Model state is invalid. sid.String: A value is required but was not present in the request.', Operation=HttpActionBinding.ExecuteBindingAsync

What could be the cause that sid is not provided?

**Comment by vitaly-koltsov** [comment]
First of all, make sure you have configured "LogoutUri" and "LogoutSessionRequired = true" for all your clients.  The second property is needed to provide session id ("sid") paramter for LogoutUri.

It was descibed here:

https://identityserver.github.io/Documentation/docsv2/advanced/signout-http.html

**Comment by nukec** [comment]
I cannot use Owin in net core.

**Comment by nukec** [comment]
there is no GetOwinContext for net core

**Comment by brockallen** [comment]
Single sign-out is hard. I don't know if these posts help:

https://brockallen.com/2016/02/08/single-sign-out-and-identityserver3/
https://brockallen.com/2016/02/09/federated-sign-out-and-identityserver3/

**Comment by nukec** [comment]
I achieved logout from Client 2 which deletes session cookie manually via http request, so both clients are logged out. Client 1 I don't have access which means it has to go through correct procedure and remove cookie with iframe. In this case cookie is not removed for Client 2. Client 1 gets logged out, but Client 2 is still logged in with perserved cookie for Client 2. This one is struggle for 2 months now.

**Comment by brockallen** [comment]
This is not really a bug with IdentityServer. I suspect it's a more of a support issue/question.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
