### ISSUE TITLE
Resource owner flow logout

### ISSUE THREAD

**Issue by iderossipinncorp** [IdentityServer/IdentityServer3#3522]
### Question / Issue
Hi! I am using resource owner flow and I need to logout the user. I tried redirecting to 
/connect/endsession

but the token still active. Also I tried passing this parameters:

/connect/endsession?**id_token_hint**=...&**post_logout_redirect_uri**=xxxxxx

but I only have the access token, for that I need the id token. How can I do that?

Thanks

**Comment by brockallen** [comment]
There is no logout at IdentityServer when using the resource owner password grant.

**Comment by iderossipinncorp** [comment]
So.... How can I to discard that access_token? Do I have to wait token expiration?

**Comment by brockallen** [comment]
Does your programming environment use a garbage collector, or do you manage memory directly? If it's a JWT, you can just let it go :)

![200_s](https://cloud.githubusercontent.com/assets/649492/22942860/3d09fade-f2b9-11e6-9e00-c4816d675f98.gif)

If it's a reference token (which I'm doubting you're using), then use revocation: https://identityserver.github.io/Documentation/docsv2/endpoints/revocation.html

**Comment by iderossipinncorp** [comment]
I am coding in javascript. I obtained the access token and user info using JWT and ResourceOwner flow, but I need to revoke that token because it is in client side....

**Comment by brockallen** [comment]
Right, so set the variable to null if you're using a JWT. That's it. If you want to ensure that the end user can't use it after they've logged out, then consider using reference tokens instead. Check the docs for more info.

**Comment by iderossipinncorp** [comment]
ok....I changed the configuration to Reference tokens. I got the token and I checked the user info. 
When I try to revoke that token using this method:

`function revokeToken() {
            var xhr = new XMLHttpRequest();
            xhr.onload = function (e) {
                console.log(xhr.status);
                console.log(xhr.response);
                //getUserInfo();
            }
            xhr.open("POST", baseUrl + "revocation");
            var data = {
                token: token.access_token,
                token_type_hint: "access_token",
                //client_id: client_id,
                //client_secret:client_secret
            };
            var body = "";
            for (var key in data) {
                if (body.length) {
                    body += "&";
                }
                body += key + "=";
                body += encodeURIComponent(data[key]);
            }
            xhr.setRequestHeader("Authorization", "Basic " + btoa(client_id + ":" + client_secret));
            xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            xhr.send(body);
        }`

it returned status 200. Then I tried to check the user info with that token, and it can get the info. 
Theoretically that tokens was revoked, right?

**Comment by brockallen** [comment]
Can you paste the token in here so I can have a look?

**Comment by iderossipinncorp** [comment]
I reset the IIS and it works. but I the reference token doesn´t have claims information, right?

**Comment by brockallen** [comment]
They do. You use introspection to obtain the claims from it.
