### ISSUE TITLE
Identity Server 3 first sign in request pending forever until page refreshed

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer3#3524]
I am having an issue with IdentityServer 3. First time I try to authenticate towards IdentityServer it keeps loading the page forever, once I refresh the page it loads it immediatelly and I am logged in. On what scenario is this happening?

It looks like Client has sent the request to IdentityServer sso, but the IdentityServer sso does not respond. 
But if we refresh Client and send the request again, IdentityServer sso will respond accordingly.

When I do the request first time after visual studio starts app I see this:
![request](https://cloud.githubusercontent.com/assets/3589518/22969621/0c426112-f367-11e6-9811-06613f30a296.PNG)

So signin request is pending forever towards sso.

Then when I refresh page (F5) it does normal flow:
![requestok](https://cloud.githubusercontent.com/assets/3589518/22969664/3db50024-f367-11e6-879f-a8217ca6c48a.PNG)

**Comment by vitaly-koltsov** [comment]
not too much info.  did you check the server logs?

**Comment by nukec** [comment]
do you mean scm logs on azure?

**Comment by brockallen** [comment]
ws-fed has a deadlock in loading the metadata. check our hosting sample's ws-fed config for a workaround.

**Comment by nukec** [comment]
@brockallen where can i find that?

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L130

**Comment by nukec** [comment]
@brockallen I can't find this in net core version
