### ISSUE TITLE
Question regarding using V3 or V4

### ISSUE THREAD

**Issue by moduv5** [IdentityServer/IdentityServer3#3525]
Hi,

I'm planning using IdentityServer for my authorization server on my aps.net app and I struggle to understand if I need to use IdentityServer3 or 4

Currenlty our application is written in asp.net 4.6 and we currently use a custom login with an entity framework database.

I see that V4 is written using asp.net core and that most of the effort will be on this version for the future.

So I want to know what version should I use considering my setup. Is V4 can by use with standard asp.net 4.6 application?

If I need to go with V3, will it be simple to migrate to V4 when our code will move to asp.net core?

Thanks

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2017/01/15/platforms-where-you-can-run-identityserver4/

**Comment by moduv5** [comment]
So as I understand with your link, IdentityServer4 can be use with Asp.net 4.6. 

As of now is IdentityServer4 is as mature a V3? Will I be able to use the same functionnality. 

It seems to have less documentations about IdentityServer4. Is V4 fully compatible with V3. Will I be able to follow some documentation of V3 and apply it to V4?

I want to use IdentityServer to create an authorization server for an application that need to enable multiple type of registration specific for customer. For example:

Some customer will use our standard User/password connexion. For some customer, they will use their own active directory to connect to our application. So we need to be able to add new customer and configure their type of authorization provider (our standard connextion, AD, other provider) without impacting the other customer. Something similar to this issue: https://github.com/IdentityServer/IdentityServer3/issues/1439

I was wondering what version will better suits my needs.

**Comment by rdavisunr** [comment]
If you need to support ws-federation to external Identity Providers, you will want to be aware of this issue: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/500

**Comment by leastprivilege** [comment]
IdentityServer4 is an evolution of 3 - IOW the code base has been improved and features have been added. Our recommendation is clear - use IS4.

**Comment by moduv5** [comment]
Following the installation tutorial,  it don't seems to be compatible with asp.net 4.6. The startup class dosen't have an application service method and the app builder is not the same (IAppBuilder vs IApplicationBuilder).

**Comment by MNF** [comment]
@moduv5, you likely already figured out, but I want to clarify (from https://leastprivilege.com/2017/01/15/platforms-where-you-can-run-identityserver4/ ): IdentityServer4 is ASP.NET Core middleware – and ASP.NET Core (despite its name) runs on the full .NET Framework 4.5.x and upwards or .NET. 
But it doesn't runs on Asp.Net 4.6
