### ISSUE TITLE
IdentityServer3 as External login option

### ISSUE THREAD

**Issue by aedilyan** [IdentityServer/IdentityServer3#3526]
Hello,
I'm using IdentityServer3 + few MVC apps (with SSO). One of my MVC app I am Using Forms Authentication, The problem is I want to keep it and add IdentityServer3 as external login option like Google, Facebook external login.
Something like this:
![untitled](https://cloud.githubusercontent.com/assets/8861436/23013479/384cf708-f444-11e6-8c99-066f1f77d1b1.png)

Is it possible ?

**Comment by aedilyan** [comment]
@brockallen any idea? Thanks in advance!

**Comment by brockallen** [comment]
You should look at our samples.

**Comment by aedilyan** [comment]
@brockallen I have looked but could not find any flow or workaround to do this

**Comment by brockallen** [comment]
This registered AAD as an external provider. You'd do the same for an IdSvr instead: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L125
