### ISSUE TITLE
External  IDP Login and Tenant value

### ISSUE THREAD

**Issue by jaydinslage** [IdentityServer/IdentityServer3#3527]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

I was wondering if there is a specific reason why the tenant value from the acr_values is not added to the authentication property dictionary?  

I know that I can get this value from other sources, but it just seems to be a bit excessive to do and has taken me some time to figure out (not long, but enough).  If there is no specific reason, is it possible to have it added to the dictionary before calling Challenge?

**Comment by brockallen** [comment]
I don't follow. You must have some specific scenario in mind where you make this assumption.

**Comment by jaydinslage** [comment]
I've created my own authentication middleware for external IDP login.  I've hooked it up using the AuthenticationOptions.IdentityProviders.  It is, however, a "generic" authentication middleware.  It will handle one "idp", as in one type of idp.  No, which exact one it goes to will depend on the tenant that is passed.

I want to bypass the selection of the external idp on the login screen and go straight to the external idp; thereby using the "idp:xxxx" in the acr_values.  Since, in my case, the "idp" is a type ... like "idp:saml", I want the tenant to be the exact one, like "tenant:saml-idp-1".  I take the tenant, look it up in a database to determine if it's valid and then ship it off.  Doing it this way allows me to load the providers on the fly.

Now, there may be a few ways to get it - I'll probably go with getting the SignInMessage (since that is part of the authenticationproperties dictionary (OWIN) and pull the tenant from there; however, this just seems like a value, since the "IDP" in the acr_values is used to initiate external authentication, that should be in there.

Following?

**Comment by brockallen** [comment]
Tenant was designed to be meaningful to you as a developer, and you're using it exactly that way. As for on the return from the external IdP, automatically including it in the user's token(s) seems far reaching to me. I'm not sure I'd expect it to be in there (especially if you've not configured any scope claims for it). I guess in short, our assumptions are different. 

Anyway, once you return from the external IdP you should still have the original signin message. You can issue the tenant in the claims in the cookie at IS, then in your user service you should have those so you can issue in the tokens if you want (which I guess is the conclusion you came to).

**Comment by jaydinslage** [comment]
Gotcha, I'm following you and that's totally fine.  I'll use the signin message to pull the tenant.  

Thank you for the quick response. And, by the way, you guys really do rock. Thank you for this project; it's been a blast to learn it, OAuth, OpenID, etc, and to implement it.

**Comment by brockallen** [comment]
Thanks
