### ISSUE TITLE
Api fails to refresh access token

### ISSUE THREAD

**Issue by jheckathorn** [IdentityServer/IdentityServer3#3528]
I ran into an issue in my own application where if I called the api after the access token had expired I would get an error. In my case it appear that the api was unable to refresh the invalid access token do to a cors violation. 

I decided to compare using the samples provided to get to the bottom of the issue so I fired up the WebHost (minimal) and the Client samples. I ran the WebHost (minimal) for my identity server and I ran MVC OWIN Client (Hybrid) for my client and Sample Web API for my api. The only change I made was to set the client access token time to 10 seconds.  (AccessTokenLifetime = 10) 

I then clicked claims and logged in via alice, alice. Next I click the MVC API Call option. I then waited 10 second and then refreshed to cause the api call to occur again. I got an Unauthorized error. 

My finding is it that the sample api also seem have the same problem I have, it is unable to refresh an invalid access token. 

Has anyone else encountered this? And more importantly does anyone know how to fix this problem?

Server Error in '/' Application.

Response status code does not indicate success: 401 (Unauthorized). 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

Source Error: 

Line 36:             client.SetBearerToken(token);
Line 37: 
Line 38:             var result = await client.GetStringAsync(Constants.AspNetWebApiSampleApi + "identity");
Line 39:             ViewBag.Json = JArray.Parse(result.ToString());
Line 40: 
  

 Source File:  C:\Projects\IdentityServer3.Samples-master\source\Clients\MVC OWIN Client (Hybrid)\Controllers\HomeController.cs    Line:  38 

Stack Trace: 

[HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).]
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
   MVC_OWIN_Client.Controllers.<CallApi>d__2.MoveNext() in C:\Projects\IdentityServer3.Samples-master\source\Clients\MVC OWIN Client (Hybrid)\Controllers\HomeController.cs:38
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129

  

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1590.0

**Comment by brockallen** [comment]
> In my case it appear that the api was unable to refresh the invalid access token do to a cors violation.

In general APIs don't refresh access tokens -- clients do. Also, APIs run server side, not in a browser, so CORS is unrelated.

This doesn't really sound like a bug in IdentityServer. If you feel that it ism, can you track it down and be more specific?

**Comment by jheckathorn** [comment]
Thank you for the quick reply.

I do believe that the CORS issue was a symptom not the problem. A red herring as they say.  

It does make sense to me that the API, as you say, would not be responsible for refreshing the access token.

The question then comes, how should this be handled? As I mentioned the sample has the same issue so I cannot look to it for the answer. 

How should the client have checked and or refreshed the access token before making the API request? Is there a different sample I should be looking at for this?

**Comment by brockallen** [comment]
If you need some layer in your system to have the most up to date value for a claim, then don't put the claim in a token (since that's inherently cached/stale), and design some other way.

**Comment by jheckathorn** [comment]
Thank you for the reply. 

I don’t thinks Claims are not really the issue here. 

Usually you would have an application that is MVC and WebApi or an application that is AnjularJS and WebApi. I am stuck with one that is hybrid of both. 

The challenge for me was how do you correctly handle authentication with an application that is MCV with AnularJS presentation layer and a WebApi .

MVC generates the AngulaJS presentation layer (aka the browser side code). The AngularJS makes calls to the WebApi wich is still part the sample application. 

The WebApi cannot refresh token nor can the AngularJS presentation layout. Only the MVC can when a new view is requested. 

My solution:

I use the http interceder in Angular JS to catch requests to the api (any get or post). Before I let the request go through I make a request to a stub view and load it into a hidden iframe this triggers the MVC controller to check the access token and refresh if it can or ask the user to re-login. Then I allow the api request go through knowing the access token will be accepted by the api. 

This seems a bit hacky to me so I was trying to understand how it should have been done assuming that there must be a better, more correct, way.

**Comment by brockallen** [comment]
> Usually you would have an application that is MVC and WebApi or an application that is AnjularJS and WebApi. I am stuck with one that is hybrid of both.

Yea, that's one of the more complex scenarios to have to design for.

One approach is to just devise a mechanism for the server side to share tokens with the client side. The other is to design them as if they're separate clients and make then do all their token renewal independent of one another.

**Comment by jheckathorn** [comment]
"devise a mechanism for the server side to share tokens with the client side"
Tried this but having the client side refreshing tokens for the api without full implementing auth a second time on the client side was complicated so I gave it up. The biggest challenge was that the MVC uses a cookie with the client side so tokens are not accessible without some customization. That said it is possible.

"design them as if they're separate clients"
This occurred to me too. I was able to see how to do this for MVC and the client side but I could not figure out a way to make the api responsible for refreshing tokens.

I really appreciate your feedback. Thank you.

**Comment by brockallen** [comment]
>  This occurred to me too. I was able to see how to do this for MVC and the client side but I could not figure out a way to make the api responsible for refreshing tokens.

Design the JS side of things as if it's a SPA, and use the [oidc-client](https://github.com/IdentityModel/oidc-client-js/) JS library for the OIDC protocol (including refresh tokens).

**Comment by jheckathorn** [comment]
Ah yes. I believe I understand. I will give that a go.

Thank you again.
