### ISSUE TITLE
Authenticate the token received

### ISSUE THREAD

**Issue by sudeesh-p** [IdentityServer/IdentityServer3#3529]
I am writing a webapi that receives the identity server token from a website which uses the same identity server for authentication. Now i want to authenticate the token. I tried using the userinfo endpoint, but the issue is the scope of the token has system. Please help

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
