### ISSUE TITLE
How secure is reference tokens

### ISSUE THREAD

**Issue by ahmettaha** [IdentityServer/IdentityServer3#3530]
Hello,

I would like to be able to invalidate access tokens, so I understand that reference tokens are the way to go. So I have created reference tokens that wont expire for 10 years. I'm curious how secure are the reference tokens? How vulnerable are they for token scanning. From my understanding, with enough brute-force, one reference token should be able to match. Am I missing something?

Also, Why are scope secrets necessary and how do they work with introspect endpoint? I'm sorry, I couldn't understand this part from the docs.

Thank you.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
