### ISSUE TITLE
Stop showing Please wait view, post login before loading the app landing page

### ISSUE THREAD

**Issue by Maqsoodp** [IdentityServer/IdentityServer3#3532]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I don't want to show the "please wait..." page before it loads the application landing page.
Is there any configuration through which i hide the internediate page altogether?
### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
You can customize that page. Check the archives on the DefaultViewService.
