### ISSUE TITLE
Getting Subject ID in Claims for Client Credentials Flow

### ISSUE THREAD

**Issue by TarunVarian** [IdentityServer/IdentityServer3#3533]
Hi Guys,

I am writing verification code for STS. I need to verify the subject id returned in the claims. I am using Client Credentials Flow as below:

var client = new TokenClient(
                tokenEndpoint,
                clientId,
                clientSecret,;

TokenResponse tokenResponse = client.RequestClientCredentialsAsync(scope).Result;

When I look into the tokenResponse.AccessToken, it doesn't give me subject id.  It is possible to get sub in Client Credentials Flow?

**Comment by leastprivilege** [comment]
Client credentials flow has no user, thus no sub.

—
cheers
Dominick Baier

**Comment by TarunVarian** [comment]
I agree. Thanks for the information Dominic!!
