### ISSUE TITLE
Difference in Identity Server3 and Identity Server4 user profile claims

### ISSUE THREAD

**Issue by TarunVarian** [IdentityServer/IdentityServer3#3534]
Hi Guys,

I used a sample present in the github to test userInfo end point. Below is the difference in the claims returned on IS3 and IS4:

![user info end point - is3 is4](https://cloud.githubusercontent.com/assets/25792088/23253224/c03d6eb4-f9d9-11e6-8448-ea62edab17fb.png)

Could you please let me know why are we not getting name, instead gettting subject id in IS4?

**Comment by TarunVarian** [comment]
Hi Guys,

Did you get chance to look into this issue?

Thanks,
Tarun Babbar
Varian Medical Systems, Pune.

**Comment by leastprivilege** [comment]
You get whatever you return from the profile service.

**Comment by TarunVarian** [comment]
Hi Dominic - Thanks for the updates. 
I am still trying to figure out why does the same piece of sample code (HybridWithPKCE flow) giving different results in IS3 and IS4?

Thanks,
Tarun Babbar
Varian Medical Systems Pune.

**Comment by leastprivilege** [comment]
maybe because something has changed between the versions??

**Comment by TarunVarian** [comment]
I was calling UserInfo end point which get the name of the user. Are you saying, we can't get the name of the user by calling UserInfo endpoint?

**Comment by leastprivilege** [comment]
put a breakpoint in your profile service to see what's going on. The userinfo endpoint asks the profile service for claims based on the scopes.
