### ISSUE TITLE
Identity server LogOut - Azure AD and Local DB

### ISSUE THREAD

**Issue by BusfyP** [IdentityServer/IdentityServer3#3535]
Hello, 

I have problem with redirect from logout page in identity server 3. I just started with implementation with Identity server. I am newcomer.

![2017-02-23 13_34_20-identity server 3 - temp test](https://cloud.githubusercontent.com/assets/25980398/23259332/dc6aae88-f9cc-11e6-8eab-8fef35874fff.png)

![2017-02-23 13_34_29-identityserver3 w_ ws-federation selfhost](https://cloud.githubusercontent.com/assets/25980398/23259388/266b1784-f9cd-11e6-9f16-3d012c1a9abc.png)

My MVC application that connects to the identity server (with Relying party). 
 
### MVC StandAloneClient (https://localhost:44304):

public ActionResult SignOut()
{
            Request.GetOwinContext().Authentication.SignOut();
            return Redirect("https://localhost:44333/core/logout");
}

### Identity server (https://localhost:44333/core)

new RelyingParty
{
Realm = "https://localhost:44304/",
Name = "StandAlone Client",
Enabled = true,
ReplyUrl = "https://localhost:44304/",
TokenType = TokenTypes.Saml2TokenProfile11,
TokenLifeTime = 1,
                  
ClaimMappings = new Dictionary<string,string>
{
{ "sub", ClaimTypes.NameIdentifier },
{ "name", ClaimTypes.Name },
{ "given_name", ClaimTypes.GivenName },
{ "surname", ClaimTypes.Surname },
{ "email", ClaimTypes.Email },
{"authentication", ClaimTypes.Authentication},
{"authenticationmethod", ClaimTypes.AuthenticationMethod},
}
}

var factory = new IdentityServerServiceFactory();

            factory.RegisterConfigurationServices(entityFrameworkOptions);
            factory.RegisterOperationalServices(entityFrameworkOptions);
            factory.UserService = new Registration<IUserService>(typeof(UserServiceOptions));
            factory.Register(new Registration<IUserRepository>(userRepository));

            var options = new IdentityServerOptions
            {
                SiteName = "Identity server 3 - Temp test",

                SigningCertificate = Certificate.Get(),
                Factory = factory,
                PluginConfiguration = Configure.ConfigurePlugins,
                AuthenticationOptions = new AuthenticationOptions
                {
                    IdentityProviders = Configure.ConfigureIdentityProviders,
                    EnablePostSignOutAutoRedirect = true,
                    EnableSignOutPrompt = false,
                    PostSignOutAutoRedirectDelay = 0
                },
            };

            appBuilder.UseIdentityServer(options);

### Question / Issue
1, Please how do I redirect from LogOut page?
2, What am i doing wrong?

Thanks BusfyP.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
