### ISSUE TITLE
Load Balancing - token mismatch.

### ISSUE THREAD

**Issue by a-tok** [IdentityServer/IdentityServer3#3536]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Hello,

Here's some background info: We're in process of converting our portal to use IdentityServer for authentication. As the intermediate step we let users in using the site's login screen and then using those credentials to get the access/refresh tokens, to make sure that IdentityServer is up for the task of handling the load. The portal is behind a load balancer and is hosted on IIS. The IdentityServer is also hosted on IIS but on a different server and is a single instance.

The issue is this: John logged in to the portal on Server1 and Mary logged in to the portal on Server2 virtually at the same time. The IdentityServer retrieved their tokens correctly from the token store but for some reason it sent John's token to Mary's  session on Server2 instead of sending it to Server1, and Mary's to Server1, causing a mismatch.

Trying to replicate the issue, in QA, I've set up a jmeter test with 100 different users and just let'er rip with HTTP Requests to IdentityServer. IdentityServer performed well, the tokens matched each and every user, so I couldn't replicate the issue by calling identity server directly and flooding it with requests.

Before I request a load balancer in QA from IT. I thought I'd check with you guys first. Any thoughts that come to mind to point me in the right direction? 

Thanks

**Comment by brockallen** [comment]
Nope, not heard of anything like this before. I think you'll need to do some more debugging to locate the fundamental issue.

**Comment by a-tok** [comment]
That's both good and bad news :) I'll close the issue for now and will reopen if I find something IdentityServer related.  Thanks Brock.
