### ISSUE TITLE
Identity Server 3 Partial Login: Antiforgery token on custom view

### ISSUE THREAD

**Issue by jackkjhsu** [IdentityServer/IdentityServer3#3539]
Hi all,

I've implemented a custom `IUserService` to show a custom MVC view on partial login. On that custom view, there's a form that the user needs to fill out and submit in order to proceed. I'm trying to reuse the Antiforgery token (idsrv.xsrf) from the `LoginViewModel.AntiForgery` property. What I'd like to be able to do is as follows: 

Instead of using MVC's built-in HtmlHelper `@Html.AntiForgeryToken()`, I'd like to replace it with something like: 

    <input type="hidden" name="@Model.AntiForgery.Name" value="@Model.AntiForgery.Value" />

I'm following the CustomUserService sample and have implemented something similar to the MVC ViewService sample to customize my login page with a plain MVC view (cshtml). Can anyone tell me how I can go about reusing the `LoginViewModel.AntiForgery` on my custom view?

Thank you all.

Jack

**Comment by brockallen** [comment]
If you're submitting to your own endpoint, then you will have to use your own anti-xsrf approach. If you're submitting back to our endpoints, then you will need to include our anti-xsrf token.

**Comment by jackkjhsu** [comment]
I am submitting to my own endpoint. It would not be a big deal to use a new antiforgery token on my form view. But is there not a way to pass the Antiforgery token from the `LoginViewModel.AntiForgery` on login to my custom view? I see there's a idsrv.xsrf cookie from the browser that could potentially be extracted but I'm not sure if it's a good approach or if it could even be converted to something usable for a hidden input field on the html.

Thanks for your reply and help.

**Comment by brockallen** [comment]
No, you should use your own. Ours is internal and designed to use within our UIs.

**Comment by jackkjhsu** [comment]
Already done it. Thanks Brock.
