### ISSUE TITLE
MVC Authentication & Authorization Example

### ISSUE THREAD

**Issue by codyskidmore** [IdentityServer/IdentityServer3#3540]
See: http://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html

At the "Adding Logout" step, we add a RedirectToIdentityProvider  handler, but when you run the the app, a "Requested scope not allowed: openid" error occurs.

I believe this error happens because the allowed scopes for the client are not added until we setup an API later in the tutorial. 

```csharp
AllowedScopes = new List<string>
                {
                    "openid",
                    "profile",
                    "roles",
                    "sampleApi"
                }
```

The example was working before adding the "PostLogoutRedirectUris" part. I will submit a patch for the docs but need to know if I am missing anything before making the change.

**Comment by brockallen** [comment]
Sure, submit a PR. Thx

**Comment by brockallen** [comment]
Any update, or can we close?
