### ISSUE TITLE
Identityserver3 logout with API

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer3#3541]
Hi
              Because I am a Chinese engineer, so my English is not very good, please forgive me, I use the translation software to translate my question, could you please help me have a look, thank you very much
              Do I use the Identityserver3 SSO AccessToken, I developed an IOS application USES Flows. ResourceOwner for Token, then this Token to call my own write API, my API is to use. NET development of the Web API, I have configured Identityserver3 SSO authentication. When I click exit in the IOS mobile terminal program, I will empty my IOS apps Token Cache.
             But the company invited a third party appraisal institution test my IOS application system, they directly to intercept the Token information, then click the exit in the IOS application, the simulator + intercept Token again to invoke my API, and successfully obtain returns the result.They say this is my application security problem.I think it's because I just cleared the IOS program about the Token cache, but there is no empty IdentityServer3 Token. So they can call me API.Is there any way to empty IdentityServer3 Token?
             I watched some of your document, also saw some people in making the above questions, I saw you about # 3522 answered is the resource owner Identityserver3 is provided no exit mechanism.I may not be able to change the rest of the authentication method to use Identityserver3. How should I do ability to can from Identityserver3 empty token?thank you very much

**Comment by brockallen** [comment]
Your access token is a JWT by default. The only thing, by default, that can invalidate the JWT is the expiration. If you want to be able to close the native app and invalidate the access token, then you should consider using reference tokens. See our docs for more info: https://identityserver.github.io/Documentation/docsv2/endpoints/revocation.html

**Comment by brockallen** [comment]
This question is more of a question for stackoverflow, so please use that for further design questions. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by YINZHU2016** [comment]
@brockallen 
hello brockallen 
         i use the refrence token,and logout ,that's all right and great.but i find another question in my project.
         i set the AccessTokenLifetime =604800,but the token will timeout in 2-4 hours.not 7 days.
         i think the question is that,refrence token is a cache key in identityserver3,so when the identityserver3
         server there is no customer visit for a long time,so the identityserver3 cache will Garbage collection,
         so the refrence token is remove,resulting in AccessTokenLifetime  is not work

        https://github.com/IdentityServer/IdentityServer3/issues/3697
        Please help me how to solve this problem? use **redis/ef** for cache the token ? but i don not find any good sample
        
         My English is not particularly good, these are translation software translation, I hope you forgive me，thanks very much

**Comment by brockallen** [comment]
For different topics, open a new issue.
