### ISSUE TITLE
Oidc silent redirect fires multiple times

### ISSUE THREAD

**Issue by sreekanthmg** [IdentityServer/IdentityServer3#3543]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am currently using oidc client version "oidc-client": "^1.2.0". It works fine in my local system. But in the server, I have observed that silent redirect page fires multiple times.
Can you suggest what would be the issue

Following are the installed packages in my app
{
  "name": "ng1-template",
  "version": "1.0.0",
  "homepage": "https://github.com/angular-template/ng1-template",
  "authors": [
    "Angular Template"
  ],
  "description": "AngularJS, Typescript and Gulp template for large applications",
  "moduleType": [
    "amd"
  ],
  "license": "Apache-2",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components"
  ],
  "dependencies": {
    "angular": "~1.5.8",
    "angular-animate": "~1.5.8",
    "angular-aria": "~1.5.8",
    "angular-messages": "~1.5.8",
    "angular-sanitize": "~1.5.8",
    "angular-ui-router": "~0.3.1",
    "jquery": "~3.1.0",
    "lodash": "^4.13.1",
    "bootstrap": "^3.3.6",
    "font-awesome": "^4.6.3",
    "angular-ui-grid": "^3.2.1",
    "ng1-template-core": "^1.1.0",
    "angular-validation": "^1.4.2",
    "ngMask": "angular-mask#^3.1.1",
    "angularjs-datepicker": "^2.1.6",
    "bootstrap-ui-datetime-picker": "^2.4.3",
    "oidc-client": "^1.2.0",
    "ui-select": "angular-ui-select#0.19.3",
    "angular-toastr": "~1.6.0",
    "angular-momentjs": "^0.2.2",
    "moment-timezone": "^0.5.7",
    "semantic-ui": "2.2.6",
    "angular-file-upload": "^2.3.4",
    "ng-file-upload": "^12.0.4",
    "isteven-angular-multiselect": "4.0.0",
    "angular-file-saver": "^1.1.2"
  },
  "resolutions": {
    "angular": "1.5.8"
  }
}

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
