### ISSUE TITLE
Browser refuses to frame specified LogoutUri

### ISSUE THREAD

**Issue by muhoro** [IdentityServer/IdentityServer3#3544]
### Question / Issue
Hi, 
I am trying to implement Single Sign Out using idsvr 3, I have two client apps (MVC 5 and asp.net  core) both registered as clients and logging in works perfect

MVC 5 - Client A
Asp.NET core - Client B

When both apps are logged in and i click on the log out link on the Client B , Client A is also logged out. But on vice versa (Logging out of Client A first) Client B is not logged out. On checking on the browser's (Chrome Version 56.0.2924.87) console i get the following error

Refused to frame 'https://client_B/.myDomain.net/Signout_oidc/?sid=2adc40bd3ae432a81671118b09a' because it violates the following Content Security Policy directive: "frame-src 'self'  https://clientB.myDomain.net https://clientA.myDomain.net ".

How can I resolve this?

**Comment by brockallen** [comment]
Quick answer: Run all the apps on HTTPS. 

Going forward: This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
