### ISSUE TITLE
Deadlock with logging and authentication middleware

### ISSUE THREAD

**Issue by jaydinslage** [IdentityServer/IdentityServer3#3545]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

I've encountered an issue that I have seen referenced briefly by a few other closed issues.  The issue is that if the HTTP logging is enabled through Identity Server and I have external authentication middleware, I will encounter a deadlock as soon as I await anything.  The requirement here is that you do not add ".ConfigureAwait(false)" to the tasks.  

I reproduced this by creating Middleware, then it the ApplyResponseChallengeAsync I added the following code:
```
protected override async Task ApplyResponseChallengeAsync()
{
    await this.TestAsync()
}
```

The TestAsync method(s) are as follows
```
private async Task TestAsync()
{
    await TestAsync2();
}

private Task TestAsync2()
{
    return Task.Delay(5);
} 
```

Once the first call is made, it will never return.  This is as long as the "Delay" is still going.  If it finishes before the runtime "awaits", then everything is fine.  That's why I chose 5, but you could chose 20 to ensure that the delay is still active when the runtime "awaits" the Task. Honestly, I'm don't think that the second method (TestAsync2) is required, but I kept it since that's what I had in my code.

I've currently resolved this by disabling the HTTP logging.

Funny enough, I am using Kentor middleware and not encountering the issue.  This part has me perplexed because he does await with no issues that I can tell.  The code above, however, causes a deadlock every time. Maybe I'm crazy (possible), or am just missing something.

**Comment by jaydinslage** [comment]
I did update to the latest IdentityServer3 release version and it still occurs.

**Comment by JCBrown** [comment]
@jaydinslage is your sample code not a classic ASP.NET deadlock?

``` c#
public static class DeadlockDemo {
 private static async Task DelayAsync()  {
    await Task.Delay(1000);
  }
  // This method causes a deadlock when called in a GUI or ASP.NET context.
  public static void Test()  {
    // Start the delay.
    var delayTask = DelayAsync();
    // Wait for the delay to complete.
    delayTask.Wait();
  }
}
```
https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

I realise this is subtly different but ultimately you're still asking the `SynchronizationContext` to continue on the same thread which has been told to sleep.

**Comment by jaydinslage** [comment]
Sorry for the delay in my response, you know, so much to do.

@brockallen I've looked at the code (might have looked at it before) and I don't see anything that would cause a deadlock.  Could it be in the underlying code (reading the request or response)?  I may take a look when I get a chance to see if there's something there.

@JCBrown I'm using typical ASP.NET.  In my example, the Delay is on a different thread, not the main one.  When the Delay finishes, it would attempt to continue on the main thread, which should be fine. The provided code was just for example.  My production code has no wait like this.  Just calls to cache (REDIS), a database (MySQL) and various internal methods.  In fact, it happens no matter what I'm awaiting.  From extensive reading, the typical thing that would cause this is by using a Task.Wait() or the like, however, I don't see any of those at all and I've found no other reason.  I understand the concept about the SynchronizationContext and all that goes with it.  I would agree that most of the code we have should have the "ConfigureAwait(false)" but the project is so big that it would be very difficult to do and I would have the problem of junior developers forgetting it somewhere and then breaking it - it's fragile.

I know that this shouldn't be happening.  I've spent considerable amount of time attempting to find the cause of the deadlock and have come across no code that would be suspect.  I can only say that after banging my head for days straight trying to figure it out, I turned off HTTP logging and I don't get a deadlock.  Which is very unsatisfying to me.  I do **not** like solving an issue without identifying the cause.

**Comment by JCBrown** [comment]
@jaydinslage sounds like we're going though similar TAP related problems (large existing synchronous code base, levels of understanding in the team etc).  I understand the provided code is only an example but from what you're saying I'm still not entirely convinced you're looking in the right place...  
It's my understanding that TAP (async) ASP.NET code should still ultimately be considered as single threaded (the SynchronizationContext used by ASP.NET guarantees that).   For me this revelation came from [Introduction to Async/Await on ASP.NET - MSDN Magazine](https://msdn.microsoft.com/en-gb/magazine/dn802603.aspx)

**Comment by jaydinslage** [comment]
@JCBrown I really enjoyed that article.  It reminded me of a few things that I had not thought about in a while.  

@brockallen @JCBrown In any case, so that we can all be on the same page, I'm going to include the actual code.  I've omitted some parts because they are either irrelevant to our discussion or because they are proprietary.  The flow, though, is exactly the flow that I go through and get a deadlock.  It waits, every time, on `string _stringValue = await this._database.StringGetAsync(key);` - the call to REDIS.  I've even flipped this out for standard local .NET cache and get the same thing (except waiting on the local cache async call).

Can you see anything that might be causing the issue: that would be my fault?  I'm completely open to that possibility. As a note, this code was working. To reproduce, I turned HTTP logging back on and it deadlocked (I wanted to make sure it didn't magically fix itself - I hate when that happens).

Note: The call to `this.Options.ConfigurationStore` is a call to the class below `SamlIdentityProviderConfigurationStore`. I just didn't want to include the options class in the code.

```
    public class SamlAuthenticationHandler :
        AuthenticationHandler<SamlAuthenticationOptions>
    {
        protected override async Task ApplyResponseChallengeAsync()
        {
            if (this.Response.StatusCode != 401) { return; }

            this.LogProvider?.Verbose("SAML: Determining if unauthenticated request is for the Gallup SAML authentication middleware.");
            AuthenticationResponseChallenge _challenge = this.Helper.LookupChallenge(
                                                                        this.Options.AuthenticationType,
                                                                        this.Options.AuthenticationMode);
            if (_challenge == null) { return; }

            // Make sure that the external login request is for our middleware.
            string _idp;
            if (!_challenge.Properties.Dictionary.TryGetValue(AuthenticationPropertyKey.Idp, out _idp) ||
                !_idp.EqualsOrdinal(ExternalAuthenticationType.MySaml))
            {
                this.LogProvider?.Verbose("SAML: IDP was not found or doesn't match the requirement of this middleware.", new { Idp = _idp });
                return;
            }

            // At this point we've determined that the request for external IDP authentication using SAML is for our middleware.
            // Pull the sign-in message. This contains the tenant value that should have been sent with the IDP.
            string _signInMessageId = _challenge.Properties.Dictionary.TryGet(AuthenticationPropertyKey.SignInMessageId);
            SignInMessage _message = this.Context.Environment.GetSignInMessage(_signInMessageId);
            if (_message?.Tenant.IsEmpty() ?? true)
            {
                this.LogProvider?.Warning("SAML: The sign-in message or tenant was not found although it is required.", new { SignInMessage = _message });
                return;
            }

            // Get the SAML IDP configuration.
            SamlIdentityProviderConfiguration _configuration = await this.GetIdentityProviderAsync(_message.Tenant);

           // .. omitted code ...
        }

        private async Task<SamlIdentityProviderConfiguration> GetIdentityProviderAsync(string id)
        {          
            SamlIdentityProviderConfiguration _configuration =
                await this.Options.ConfigurationStore.GetConfigurationByClientIdAsync(id);
            if (_configuration != null) { return _configuration; }

            // .. omitted code ...
            return null;
        }
    }

    public class SamlIdentityProviderConfigurationStore
    {
        public ICacheProvider Cache { get; set; }

        public Task<SamlIdentityProviderConfiguration> GetConfigurationByClientIdAsync(string clientId)
        {
            return this.GetModelAsync(idp => idp.ClientId.EqualsOrdinal(clientId));
        }

        public virtual async Task<T> GetModelAsync(Predicate<T> predicate = null)
        {
            List<T> _models = await this.GetModelsAsync(predicate);

            if (_models.IsNullOrEmpty())
            {
                return null;
            }
            else
            {
                return _models[0];
            }
        }

        public virtual async Task<List<T>> GetModelsAsync(Predicate<T> predicate = null)
        {
            // First get the models from cache.
            List<T> _models = await this.GetModelsFromCacheAsync();

            // ... omitted code that gets from the database if the returned cache is null or empty ...
        }

        public virtual Task<List<T>> GetModelsFromCacheAsync()
        {
            return this.Cache.GetAsync<List<T>>(this.CacheKey);
        }

    }

    public class RedisCacheProvider :
        ICacheProvider,
        IDisposable
    {
        /// <summary>
        /// The REDIS data store.
        /// </summary>
        private IDatabase _database;

        public RedisCacheProvider()
        {
            string configString = null;

            configString = System.Configuration.ConfigurationManager.AppSettings[ConfigurationKey.RedisConnection].ToString();

            this._connection = ConnectionMultiplexer.Connect(configString);
            this._database = this._connection.GetDatabase(); // default databaseNumber is 0

            this.SerializationSettings = new JsonSerializerSettings
            {
                Formatting = Formatting.None,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
            };
        }

        public async Task<T> GetAsync<T>(string key)
        {
            // Get the value as a string.
            string _stringValue = await this._database.StringGetAsync(key);

            // Deserialize the object and return it.
            return this.DeserializeObject<T>(_stringValue);
        }

        protected virtual T DeserializeObject<T>(string value)
        {
            // If the value is empty, return the default value of the generic type.
            if (value.IsEmpty()) { return default(T); }

            if (typeof(T) == typeof(string))
            {
                // For string type, assuming the string has been serialized and the string will be deserialized outside this method.
                return (T)(object)value;
            }
            else
            {
                // Use Newtonsoft for deserialization.
                // NOTE: The settings contain all JSON serialization/deserialization options specified during the instantiation of this class.
                return JsonConvert.DeserializeObject<T>(value, this.SerializationSettings);
            }
        }
    }

```

**Comment by brockallen** [comment]
To really prove all of this, I'd want to isolate the HTTP logging with your sample above. IOW, build a stand alone host with our HTTP logging and the code above to illustrate how it's deadlocking.

**Comment by leonardochaia** [comment]
Hey guys, this seems like an issue we currently have, since we haven't find an actual solution.
I asked[ this question](http://stackoverflow.com/questions/39472799/iis-asp-net-webapi-deadlock-when-requesting-the-same-server) on SO a while ago.
Our current solution, is to run IdentityServer on a different IIS Application Pool than our other applications.

**Comment by brockallen** [comment]
@jaydinslage all set -- can we close?
