### ISSUE TITLE
IdentityModel, Version=2.5.1.0 UserInfoClient changed from version Version=1.0.0.0 broken in sample when upgraded

### ISSUE THREAD

**Issue by wlafrance** [IdentityServer/IdentityServer3#3548]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
The Assembly IdentityModel, Version=2.5.1.0 for IdentityModel.Client UserInfoClient
public methods have changed.. 
In the sample code MVC OWIN Client (Hybrid) startup.cs file around line 66.  
Uses Version=1.0.0.0 (IdentityModel.Client  UserInfoClient)
 // use the access token to retrieve claims from userinfo
                            var userInfoClient = new UserInfoClient(
                            new Uri(Constants.UserInfoEndpoint),
                            tokenResponse.AccessToken);

This no longer compiles when used with the new version, what should be used since the parameters for the methods have changed...
OLD VERSION
`namespace IdentityModel.Client
{
    public class UserInfoClient
    {
        public UserInfoClient(Uri endpoint, string token);
        public UserInfoClient(Uri endpoint, string token, HttpMessageHandler innerHttpMessageHandler);`

NEW VERSION
`namespace IdentityModel.Client
{
    public class UserInfoClient
    {
        public UserInfoClient(string endpoint);
        public UserInfoClient(string endpoint, HttpMessageHandler innerHttpMessageHandler);`

### Relevant parts of the log file

```
<log goes here>
```

**Comment by wlafrance** [comment]
This is what I have changed it to.  Just wondering if this is the correct approach?

`
                        // use the access token to retrieve claims from userinfo
                        var userInfoClient = new UserInfoClient(new Uri(Constants.UserInfoEndpoint).ToString());
                        //var userInfoClient = new UserInfoClient(
                        //   new Uri(Constants.UserInfoEndpoint),
                        //   tokenResponse.AccessToken);
                        var userInfoResponse = await userInfoClient.GetAsync(tokenResponse.AccessToken);  //.GetAsync();

                        // create new identity
                        var id = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType);
                        id.AddClaims(userInfoResponse.Claims);
                        //id.AddClaims(userInfoResponse.GetClaimsIdentity().Claims);`

**Comment by brockallen** [comment]
Yes, IIRC, there was a breaking change in that API. That looks about right -- I imagine it's working since there were no more follow-ups here :)
