### ISSUE TITLE
embedding a Password Change page from IdentityServer to web application using iframe

### ISSUE THREAD

**Issue by dolomiteson** [IdentityServer/IdentityServer3#3549]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi,
I am new to GitHub and Identity Server so bear with me.  I am currently working on a web application that has a Change Password link on its homepage. when the user clicks the link, the Change Password page from IdentityServer should be embedded inside the web-applications homepage using iframe. This results in a blacked-out page in chrome and an authorization issue in IE. I am not looking for direct code, but, if someone has come across this issue and has resolved it, can you help me with any resource i haven't found. All help is appreciated. 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
