### ISSUE TITLE
Pre.. and Post... AuthenticateAsync in ResourceOwner flow

### ISSUE THREAD

**Issue by Ermesx** [IdentityServer/IdentityServer3#3551]
###  Issue
I have quite custom UserService where I use almost all of available methods: `PreAuthenticateAsync`, `AuthenticateLocalAsync` and `PostAuthenticateAsync`

and in my case I add some claims in `PostAuthenticateAsync` because I have additional way to external logging which doesn't go though `AuthenticateLocalAsync` but I realize that when someone use ResourceOwner flow authentication goes only trough `AuthenticateLocalAsync`

Here is code:
`/source/Core/Validation/TokenRequestValidator.cs`
``` c#
...
    /////////////////////////////////////////////
    // authenticate user
    /////////////////////////////////////////////
    var authenticationContext = new LocalAuthenticationContext
    {
        UserName = userName,
        Password = password,
        SignInMessage = signInMessage
    };

    await _users.AuthenticateLocalAsync(authenticationContext);
    var authnResult = authenticationContext.AuthenticateResult;

    if (authnResult == null || authnResult.IsError || authnResult.IsPartialSignIn)
    {
...
```

Is it possible to make that `PreAuthenticateAsync`, `PostAuthenticateAsync` also take part in this flow ?

**Comment by brockallen** [comment]
No, as those are designed for the UI workflows. Sorry.
