### ISSUE TITLE
OutOfMemoryException on uploading large files

### ISSUE THREAD

**Issue by dmitry606** [IdentityServer/IdentityServer3#3553]
Using IdentityServer3 causes all upload requests with large files to fail with OutOfMemoryException. 

`[OutOfMemoryException: Exception of type &#39;System.OutOfMemoryException&#39; was thrown.]
   System.Text.StringBuilder.ToString() +35
   System.IO.StreamReader.ReadToEnd() +123
   Owin.&lt;&lt;ConfigureRequestBodyBuffer&gt;b__0&gt;d__2.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureRequestBodyBufferExtension.cs:18
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Owin.&lt;&lt;ConfigureIdentityServerBaseUrl&gt;b__0&gt;d__3.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureIdentityServerBaseUrlExtension.cs:43
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Owin.&lt;&lt;ConfigureRequestId&gt;b__0&gt;d__2.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureRequestIdExtension.cs:37
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155
</pre></code>
`

This line is to blame:
` var body = bodyReader.ReadToEnd();`

**Comment by brockallen** [comment]
> Using IdentityServer3 causes all upload requests with large files to fail with OutOfMemoryException.

Under what use case does this happen?
