### ISSUE TITLE
Single Sign Out with Azure AD

### ISSUE THREAD

**Issue by muhoro** [IdentityServer/IdentityServer3#3554]
How can I get Idsr to call the client's singoutCleanUp URI after the user signs out of Office 365

**Comment by brockallen** [comment]
Register the LogoutUri: https://identityserver.github.io/Documentation/docsv2/configuration/clients.html

**Comment by muhoro** [comment]
I have already registered the LogoutUri for my 2 clients.

**What works**
- I can log in to my clients application using my Office365 account
- When I sign out from any of my clients, all clients plus my Office365 accounts are signed out

**What doesn't work**
Signing out of my office365 does not sign me out of my clients applications.

**Comment by brockallen** [comment]
DOes O365 allow you to configure your signout callback URL with it? Seems more like a missing feature for O365.

**Comment by muhoro** [comment]
no it doesn't, only the redirect URL is configurable.
Is there a workaround to that?

**Comment by brockallen** [comment]
Ask Microsoft.

**Comment by Nikto08** [comment]
muhoro, how have you solved your problem? I am facing the same trouble.

**Comment by alaincroisetiere** [comment]
Azure Active Directory (O365) allow any post logout redirect uri. Set the PostLogoutRedirectUri with the ReturnUrl of SignOutMessage in the RedirectToIdentityProvider openid connect notification.

```C#
if (notification.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
{
    if (!string.IsNullOrEmpty(notification.OwinContext.Environment.GetSignOutMessageId()))
    {
        var signOutMessage = notification.OwinContext.Environment.GetSignOutMessage();
        notification.ProtocolMessage.PostLogoutRedirectUri = signOutMessage.ReturnUrl;
    }
}
```

**Comment by Nikto08** [comment]
alaincrosetiere, thank you very much for your answer. Could you explain what is this SignOutMessage? I didnt used Owin library in my code.

**Comment by alaincroisetiere** [comment]
This is an extension provide by IdSrv3 to get properties of sign out process : https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by muhoro** [comment]
Nikto08 I finally found where I could register the logout URL for my idsvr on Azure AD. 
i set up a signout endpoint and registered it on AD as directed here:
https://identityserver.github.io/Documentation/docsv2/advanced/federated-signout.html

**Comment by Nikto08** [comment]
Thanks!

**Comment by Nikto08** [comment]
muchoro, do you register it every time your prograam is executed? I don't really understand how it works.
