### ISSUE TITLE
Is there a reason for not deleting refresh token

### ISSUE THREAD

**Issue by RaviTejaKaruturi** [IdentityServer/IdentityServer3#3555]
Hi,
I have a question.
I am using _AccessTokenType.Reference_ and  _offline_access_ in my application.
As per this issue
https://github.com/IdentityServer/IdentityServer3/issues/3178

_token_type_hint = access_token:
Deletes 1 TokenHandle (access token). This will only work for clients which use AccessTokenType.Reference. If the client uses AccessTokenType.Jwt, nothing happens._
(I know that this was implemented for AccessTokenType.Jwt in 2.6)

Currently, when I sign out, it removes only access token, but not refresh token.
Why is it not removing refresh token? Is there any reason, for refresh token to be still in DB after user sign out, though sign out request was sent with _token_type_hint = access_token? 

Thanks.

**Comment by brockallen** [comment]
> Currently, when I sign out, it removes only access token, but not refresh token.

I don't follow. You can always write your own logis in the signout event on the user service to cleanup any tokens in the store that you need to based on your requirements.
