### ISSUE TITLE
Question: IdentityServer3 login with Terms of use agreement

### ISSUE THREAD

**Issue by wlafrance** [IdentityServer/IdentityServer3#3557]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I found it once before, but I can't seem to locate the example project that has the user login, them agree to a terms of use agreement before being redirected back to the client application...
Does anyone remember the project or documentation location on this?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomUserService/CustomUserService/EulaAtLoginUserService.cs
