### ISSUE TITLE
Trying to implement ICache for a ConfigureUserServiceCache, SetAsync not being called

### ISSUE THREAD

**Issue by CraigEaston** [IdentityServer/IdentityServer3#3558]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

I'm trying to implement a Custom User Service Cache since our IDServer is distributed in a Web Farm.  I am also using ExternalRegistrationUserService with wsFederationAuthentication.  I have implemented a local Cache using A SQLServer database and a front end webservice.

I have created a Class that implements  ICache<IEnumerable<Claim>>

and Register it like this:
 factory.UserService = new Registration<IdentityServer3.Core.Services.IUserService>(typeof(ExternalRegistrationUserService));
         **factory.ConfigureUserServiceCache(new Registration<IdentityServer3.Core.Services.ICache<System.Collections.Generic.IEnumerable<System.Security.Claims.Claim>>>(userCache));**

I never see the SetAsync being called? 
I DO see GetAsync being called, but since SetAsync is never called, there is nothing in the Cache.

Should I be calling SetAsync somewhere in my code on my own?  Maybe in the ExternalRegistrationUserService (Implement UserServiceBase), In the AuthenticateExternalAsync?

Here is my simplified UserCacheService Class:
public class UserCacheService : ICache<IEnumerable<Claim>>
   {
      public async Task SetAsync(string key, IEnumerable<Claim> item)
      {
         try
         {
            [MyCode]
         }
         catch (Exception ex)
         {
            throw ex;
         }
      }
      async Task<IEnumerable<Claim>> ICache<IEnumerable<Claim>>.GetAsync(string key)
      {
	 try
	 {
            [More My Code]
         }
         catch (Exception ex)
         {
            throw ex;
         }
         return foundClaims;
      }
}

The Error is my service throwing a 404 for not finding the Item in the Cache...

### Relevant parts of the log file
03/07/2017 08:56:46 -05:00 [Information] ()
 Creating Implicit Flow response.
03/07/2017 08:56:52 -05:00 [Error] ()
 Unhandled exception
System.Exception: Error calling renewal micro service: Not Found
   at SHI.IDServer1.UserCacheService.<IdentityServer3-Core-Services-ICache<System-Collections-Generic-IEnumerable<System-Security-Claims-Claim>>-GetAsync>d__1.MoveNext() in C:\Projects\IdentityServer\Development\Websites\IDServer1\IDServer1\UserCacheService.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Extensions.ICacheExtensions.<GetAsync>d__0`1.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Extensions\ICacheExtensions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Services.Caching.CachingUserService.<GetProfileDataAsync>d__6.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Services\Caching\CachingUserService.cs:line 0

**Comment by CraigEaston** [comment]
Here is my UserCacheService class definition:
Please correct me if I am wrong, but I think I declared it correctly

 public class UserCacheService **: ICache<IEnumerable<Claim>>**
   {
      public async Task SetAsync(string key, IEnumerable<Claim> item)
      {


#Also, do you see  GetProfileDataAsync  being called on your user service? It's that call's results that are being cached.

I am NOT seeing that being called.
I can step into my "AuthenticateExternalAsync",
The next breakpoint I see hit is this:
 async Task<IEnumerable<Claim>> ICache<IEnumerable<Claim>>.GetAsync(string key)

in my UserCacheService Class.

I never get into the:
 public override Task GetProfileDataAsync(ProfileDataRequestContext context)

in my ExternalRegistrationUserService

**Comment by brockallen** [comment]
It needs to be an `ICacne<IEnumerable<Claim>>`. See the type we expect on the ctor: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/Caching/CachingUserService.cs#L45

**Comment by CraigEaston** [comment]
Sorry, My post was wrong, I didn't wrap the code in code tags first time I posted.. I editied my post and it does look like you say, (I think)

**Comment by brockallen** [comment]
and for my other question? 

> Also, do you see GetProfileDataAsync being called on your user service? It's that call's results that are being cached.

**Comment by CraigEaston** [comment]
I am NOT seeing that being called.
 I can step into my "AuthenticateExternalAsync",
 The next breakpoint I see hit is this:
` async Task<IEnumerable> ICache<IEnumerable>.GetAsync(string key)

in my UserCacheService Class.

I never get into the:
` public override Task GetProfileDataAsync(ProfileDataRequestContext context)`

in my ExternalRegistrationUserService

**Comment by brockallen** [comment]
As you can see here: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/Caching/CachingUserService.cs#L113, the only time we store something in the cache is when `GetProfileDataAsync` is used.

**Comment by CraigEaston** [comment]
If I comment out the line in my Startup.cs to configure the UserServiceCache I can step into the GetProfileDataAsync.

As soon as I UN-Comment that line, the GetProfildDataAsync never gets called:

Here is code from my Startup Class, 
`` var factory = new IdentityServerServiceFactory()
            .UseInMemoryClients(SHI.IDServer1.Configuration.Clients.Get())
            .UseInMemoryScopes(SHI.IDServer1.Configuration.Scopes.Get());

       factory.UserService = new Registration<IdentityServer3.Core.Services.IUserService>(typeof(ExternalRegistrationUserService));

         **//factory.ConfigureUserServiceCache(new Registration<IdentityServer3.Core.Services.ICache<System.Collections.Generic.IEnumerable<System.Security.Claims.Claim>>>(userCache));**

**Comment by CraigEaston** [comment]
Do I need to manually call the SetAsync on my UserCacheService somewhere in my code for this to work?

**Comment by brockallen** [comment]
No, that's what our caching user service does for you. You just need to implement the `ICache<IEnumerable<Claim>>`

**Comment by CraigEaston** [comment]
I'm sorry, but I MUST be missing something simple.

I believe I did implement a class with `ICache<IEnumerable<Claim>>`
and Registered it as my UserServiceCache:

The SetAsync method in my UserCacheService is never called.  Neither is the GetProfileDataAsync method in my ExternalRegistrationUserService Class

I have these two line in my Startup.cs:
```
factory.UserService = new Registration<IdentityServer3.Core.Services.IUserService>(typeof(ExternalRegistrationUserService));
factory.ConfigureUserServiceCache(new Registration<IdentityServer3.Core.Services.ICache<System.Collections.Generic.IEnumerable<System.Security.Claims.Claim>>>(typeof(IDServer1.UserCacheService)));
```

Here is my UserCacheService Class:
```
public class UserCacheService : ICache<IEnumerable<Claim>>
   {
      public Task<IEnumerable<Claim>> GetAsync(string key)
      {
         Models.UserCacheDataModel u = new Models.UserCacheDataModel();
         IEnumerable<Claim> foundClaims = new List<Claim>();
         using (HttpClient client = new HttpClient())
         {
            client.BaseAddress = new Uri(@"http://local.micro.shi.com");
            string DownLoadString = string.Format("IDServerCache/api/UserClaimsCache/{0}", key);
            HttpResponseMessage response = client.GetAsync(DownLoadString).Result;
       if (response.IsSuccessStatusCode)
            {
               u = response.Content.ReadAsAsync<Models.UserCacheDataModel>().Result;
              foundClaims = Newtonsoft.Json.JsonConvert.DeserializeObject<IEnumerable<Claim>>(u.Claims);
            }
         }
         return Task.FromResult(foundClaims);
      }

      public Task SetAsync(string key, IEnumerable<Claim> item)
      {
         Models.UserCacheDataModel u = new Models.UserCacheDataModel();
         u.ID = Guid.Parse(key);
         u.Claims = Newtonsoft.Json.JsonConvert.SerializeObject(item);
         using (HttpClient client = new HttpClient())
         {
            client.BaseAddress = new Uri(@"http://local.micro.shi.com");
            string DownLoadString = "IDServerCache/api/UserClaimsCache";
            client.PostAsJsonAsync<Models.UserCacheDataModel>(DownLoadString, u);
         }
         return Task.FromResult(0);
      }
   }
```

**Comment by CraigEaston** [comment]
I'm am idiot !!! 

See in my 
```
public class UserCacheService : ICache<IEnumerable<Claim>>
   {
      public Task<IEnumerable<Claim>> GetAsync(string key)
      {
         Models.UserCacheDataModel u = new Models.UserCacheDataModel();
         **IEnumerable<Claim> foundClaims = new List<Claim>();**
         using (HttpClient client = new HttpClient())
```

I'm created my "foundClaims" with a new empty list of claims... and THAT is what is returned.

The only time the setAsync() gets called is if a null is returned for the claims from the cache, so set was never being called.

I changed it to initialize as null, and now I see my cache going to my database.

Now I'm just not sure what to put in my GetProfileDataAsync ??
```
 public override Task GetProfileDataAsync(ProfileDataRequestContext context)
      {
         //issue the claims for the user
         var key = GetKey(context.Subject, context.RequestedClaimTypes);
         //UserCacheService ucs = new IDServer1.UserCacheService();

         var user = Users.SingleOrDefault(x => x.Subject == context.Subject.GetSubjectId());

         if (user != null)
         {
            context.IssuedClaims = user.Claims.Where(x => context.RequestedClaimTypes.Contains(x.Type));
         }
         else
         {
            //IEnumerable<Claim> iClaims;
            //iClaims = ucs.GetAsync(key).Result;
            //context.IssuedClaims = iClaims;
         }

         return Task.FromResult(0);
      }
```

**Comment by brockallen** [comment]
So the cache issue is solved? We can close?

For your other issue, check the docs, reference implementation, or check on SO.

**Comment by CraigEaston** [comment]
Yes, we can close, I didn't realize how the cache worked (First try the get, if you don't find it, put it away then return it)

Thanks for all your help and support with this

For my other issue, I had to implement my own IUserService, and into that Inject my ExternalRegistrationUserService and my Cache Service as well as figure out how to register all that in my factory so the DI worked properly.

I'm almost there.
