### ISSUE TITLE
The client application is not known or is not authorized.

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer3#3559]
How do I see deeper what is the issue? I am trying to resolve why my client is not recognized.

I implemented serilog in Startup.cs configuration method like this:
```
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Trace()
                .CreateLogger();
```
and web.config:
```
    <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <remove name="Default"/>
        <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="c:\logs\MvcViewServiceSample.log"/>
      </listeners>
    </trace>
  </system.diagnostics>

My configuration for identityserver is this:
```
public void Configuration(IAppBuilder app)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Trace()
                .CreateLogger();

            var factory = new IdentityServerServiceFactory();

            factory.UseInMemoryClients(Clients.Get())
                .UseInMemoryScopes(Scopes.Get())
                .UseInMemoryUsers(Users.Get())
                .CorsPolicyService = new Registration<ICorsPolicyService>(new InMemoryCorsPolicyService(Clients.Get()));

            var viewOptions = new DefaultViewServiceOptions();
            viewOptions.Stylesheets.Add("/templates/authorizeresponse.css");
            viewOptions.Stylesheets.Add("/templates/images/animated-loader.gif");
            viewOptions.Stylesheets.Add("/templates/images/harmonise_logo.png"); 
            viewOptions.Stylesheets.Add("/templates/images/home-arrow.png");

            factory.ConfigureDefaultViewService(viewOptions);

            var identityServerOptions = new IdentityServerOptions
            {
                SiteName = "Digital Filing Cabinet",
                SigningCertificate = Certificate.Get(),
                Factory = factory,
                AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
                {
                    EnableSignOutPrompt = false,
                    EnablePostSignOutAutoRedirect = true,
                    PostSignOutAutoRedirectDelay = 0
                },
                LoggingOptions = new LoggingOptions()
                {
                    EnableHttpLogging = true,
                    EnableKatanaLogging = true,
                    EnableWebApiDiagnostics = true,
                    WebApiDiagnosticsIsVerbose = true
                }
            };

            app.Use<ExceptionHandlerMiddleware>();
            app.Map("/core", idsrvApp => { idsrvApp.UseIdentityServer(identityServerOptions); });
            app.Map("/signoutcleanup", cleanup =>
            {
                cleanup.Run(async ctx =>
                {
                    await ctx.Environment.ProcessFederatedSignoutAsync();
                });
            });

        }
```

Client in identityServer:
```
/////////////////////////////////////////////////////////////
                // Console Client Credentials Sample
                /////////////////////////////////////////////////////////////
                new Client
                {
                    ClientName = test SSO Client,
                    ClientId = testsso,
                    Enabled = true,
                    Flow = Flows.ClientCredentials,

                    ClientSecrets = new List<Secret>
                        {
                            new Secret("secret".Sha256()),
                            new Secret
                            {
                                Value = "61B754C541BBCFC6A45A9E9EC5E47D8702B78C29",
                                Type = Constants.SecretTypes.X509CertificateThumbprint,
                                Description = "Client Certificate"
                            },
                        },

                    AllowedScopes = new List<string>
                        {
                            "read",
                            "write"
                        },

                    Claims = new List<Claim>
                        {
                            new Claim("location", "datacenter")
                        }
                },
```

Client startup settings:
```
            // open id authencation - start
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap = new Dictionary<string, string>();

            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationScheme = "Cookies",
                CookieName = Configuration.GetSection("AppSettings:OpenIdAuthentication:CookieName").Value
            });

            var openIdConnectOptions = new OpenIdConnectOptions()
            {
                ClientId = Configuration.GetSection("AppSettings:OpenIdAuthentication:ClientId").Value,
                Authority = Configuration.GetSection("AppSettings:OpenIdAuthentication:Authority").Value,
                CallbackPath = Configuration.GetSection("AppSettings:OpenIdAuthentication:CallbackPath").Value,
                ResponseType = "id_token",
                UseTokenLifetime = false,
                SignInScheme = "Cookies",
                AuthenticationScheme = "oidc",
                AutomaticChallenge = true
            };

            openIdConnectOptions.Scope.Clear();
            openIdConnectOptions.Scope.Add("openid");
            openIdConnectOptions.Scope.Add("all_claims");

            app.UseOpenIdConnectAuthentication(openIdConnectOptions);
```

Web.config:
```
    "OpenIdAuthentication": {
      "ClientName": "test SSO Client",
      "ClientId": "testsso",
      "CookieName": "testSSO",
      "Authority": "https://localhost:44300/core/",
      "CallbackPath": "/fc"//,
      //"AcrValues": "idp:Federation"
    },
```

**Comment by brockallen** [comment]
Check the logs
