### ISSUE TITLE
Source Not Found on debugging

### ISSUE THREAD

**Issue by mainettis** [IdentityServer/IdentityServer3#3560]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I get a "Source Not Found" on call stack:
IdentityServer3.dll!Owin.SignOutMessageCookieExtension.ConfigureSignOutMessageCookie.AnonymousMethod__0(Microsoft.Owin.IOwinContext context, System.Func<System.Threading.Tasks.Task> next) Line 47
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Owin.SignOutMessageCookieExtension.<<ConfigureSignOutMessageCookie>b__0>d__5>(ref Owin.SignOutMessageCookieExtension.<<ConfigureSignOutMessageCookie>b__0>d__5 stateMachine)	Unknown

ConfigureSignOutMessageCookieExtension.cs Not Found

This does not cause an exception it just happens when I'm trying to put a break point to try and look at context for response details
i.e. = `appBuilder.Use(async (context, next) =>
            {
                await next.Invoke();
            });`

This did not seem to be an issue prior to 2.6

### Relevant parts of the log file
Source Not Found:
Locating source for 'c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureSignOutMessageCookieExtension.cs'. (No checksum.)
The file 'c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureSignOutMessageCookieExtension.cs' does not exist.
Looking in script documents for 'c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureSignOutMessageCookieExtension.cs'...
Looking in the projects for 'c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureSignOutMessageCookieExtension.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\...
...
...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureSignOutMessageCookieExtension.cs.
The debugger could not locate the source file 'c:\local\identity\server3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureSignOutMessageCookieExtension.cs'.

**Comment by brockallen** [comment]
I'm not sure I follow. The file is here: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AppBuilderExtensions/ConfigureSignOutMessageCookieExtension.cs

**Comment by mainettis** [comment]
Sorry, haven't had much time to respond.

It's just a VS debugging issue. Nothing really missing. Just no source file for the Visual Studio debugger.

Just threw me off that it popped up when just looking at  owin context. I'm no stepping in or trying to view source code. So it is weird to get an error related to https://msdn.microsoft.com/en-us/library/3sehk0fb(v=vs.140).aspx when stepping through:
`AppBuilder.Use(async (context, next) => 
     { 
          await next.Invoke(); 
     })`

I changed the title to be clearer. Don't think there is anything to do on code side.
