### ISSUE TITLE
Retrieve the current user's name in a mvc controller hosted in the same host than the IdentityServer ?

### ISSUE THREAD

**Issue by christophebourguignon** [IdentityServer/IdentityServer3#3563]
Hi everybody,
Is there a way to retrieve the current user's name in a mvc controller hosted in the same host than the IdentityServer ?

My startup code:

```
app.Map("", idsrvApp =>
		{
		   
			idsrvApp.UseIdentityServer(options);
		});
```
	
Url : http://localhost/idsrv/		

	
The Controller :

```
public class RequestController : Controller
{
		public ActionResult Index()
        {
			var context = HttpContext.Current.Request.GetOwinContext();
			var userName = context.Environment.GetCurrentUserDisplayName();
            return View();
        }
}
```

Url : http://localhost/idsrv/Request

The userName is always null but the user is well authenticated.

**Comment by brockallen** [comment]
Your code would need to be in the same path as IdentityServer and then use the OWIN extensions to load the current authenticated user.
