### ISSUE TITLE
Identity Server 3 with AppAuth-Android

### ISSUE THREAD

**Issue by JhDocs** [IdentityServer/IdentityServer3#3564]
Hi, 

Our team has implemented identity server 3 for our Angular application (implicit flow), it works nicely.

When our android developer try to implement implicit flow on our android application with the AppAuth-Android library, identity server will react with `The client application made an invalid request.`
when AppAuth-Android library encode the redirect uri from "com.uobtravelplanners.travelsmart.app/oauth2redirect" to "com.uobtravelplanners.travelsmart.app%3A%2Foauth2redirect". 

We believe that the uri failed in the following validation code:

            Uri uri;
            if (!Uri.TryCreate(redirectUri, UriKind.Absolute, out uri))
            {
                LogError("invalid redirect_uri: " + redirectUri, request);
                return Invalid(request);
            }

From the NDC video, you guys actually recommended this library for android application, do you guys face this issue before or have any idea to solve this issue? Any help would be appreciated.

**Comment by leastprivilege** [comment]
AppAuth does not do implicit flow - it does code flow with PKCE.

Also check the logs for the exact error.

**Comment by JhDocs** [comment]
Thanks for the info. 
I am sorry but I am still very new in software development, do you mind to share with me, how can I access the logs?

**Comment by JhDocs** [comment]
Thanks for the info.
