### ISSUE TITLE
Identity Server 4 in Web Farm

### ISSUE THREAD

**Issue by sreekanthmg** [IdentityServer/IdentityServer3#3565]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We have implemented id svr4 in asp.net core application and we are going live soon. But we have not tested the application in web farm scenario yet. We are using implicit flow for authentication and not using any certificate. All our web servers will be running IIS.
Any risk on deploying it in a farm scenario ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This is covered in the docs.
