### ISSUE TITLE
ios native app sample

### ISSUE THREAD

**Issue by wmcainsh** [IdentityServer/IdentityServer3#3567]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

Is there any sample code showing how to use hybrid flow in a native iphone app?

The approach I'm attempting is similar to the WPF Client Hybrid sample but using a WKWebView and trying to intercept that.

So far I have managed to display the login screen and authenticate my credentials, the server log shows that the server then sends the post with the data but I don't seem to be able to intercept that.

This is my first iphone app so I'm probably missing something obvious but haven't been able to find anything on the web to help.

**Comment by leastprivilege** [comment]
Here's the reference impl for iOS

https://github.com/openid/AppAuth-iOS

**Comment by wmcainsh** [comment]
Thanks
