### ISSUE TITLE
Issue with windows authentication

### ISSUE THREAD

**Issue by prydzewski** [IdentityServer/IdentityServer3#3570]
Hi,
When I run your Quickstart(6_AspNetIdentity) sample and try to login with external provider Negotiate or NTLM, I get a empty  site with status code some times is 403 or 400(/Account/ExternalLogin). It's look like challenge is not working like I think it should. When I go to main page I see that User is logged in but flow of log in with windows authentication is broken. Maybe someone can tell me how should work external login with Negotiate or NTML. I tried run IdentityServer with IIS and WebListener and result is the same. It's possible that it is problem with system? In my system windows authentication will be the main login provider.

**Comment by leastprivilege** [comment]
wrong repo.
