### ISSUE TITLE
Limiting user login request (successful and failed)

### ISSUE THREAD

**Issue by GajananMore** [IdentityServer/IdentityServer3#3571]
### Question
I was looking for document that will help me tracking number of login attempt (which can be successful or failure) per client, but i am empty handed and didn't got anything. can someone please guide me how can i do this in identity server 3?

**Comment by leastprivilege** [comment]
Our events could provide you with such information

https://identityserver.github.io/Documentation/docsv2/configuration/events.html

Documentation is not extensive - check the events folder in the source code
