### ISSUE TITLE
IssueLoginCookie redirects back to login screen

### ISSUE THREAD

**Issue by jpr1020** [IdentityServer/IdentityServer3#3573]
Hi,

I have a custom registration page in IdSvr and depending on the client need, they will be redirected to either login or registration screen. I have logic under "PreAuthenticateAsync" to redirect the user to registration based on client role/scope.

once the registration is completed, i need to automatically login the user and redirect to client application.
used below code to issue login cookie but the flow still takes the user back to login page rather than redirecting to client application.
var env = Request.GetOwinContext().Environment;
env.IssueLoginCookie(new IdentityServer3.Core.Models.AuthenticatedLogin
                    {
                        Subject = "Test Subject",
                        Name = model.UserName,
                        Claims = new List<System.Security.Claims.Claim>() { new System.Security.Claims.Claim("testClaim", "0") },
                        PersistentLogin = false,
                        IdentityProvider = "idp",
                        AuthenticationMethod = "amr",
                        PersistentLoginExpiration = System.DateTimeOffset.Now.AddDays(1)
                    });
var msg = env.GetSignInMessage("signinId");
return Redirect(msg.ReturnUrl);

Any thoughts on what needs to be added to make it redirect to client app?

**Comment by brockallen** [comment]
What endpoint is the msg.ReturnUrl?

**Comment by jpr1020** [comment]
Thanks for the fast response.
IsActive was returning false (I have to set subject value with user id so overridden "IsActiveAsync" returns true)
I am able to successfully return to client app.
