### ISSUE TITLE
Correct use of Hybrid/Code flow and external identity providers

### ISSUE THREAD

**Issue by sum1youno** [IdentityServer/IdentityServer3#3574]
Hi,

I am currently having some issues implementing the hybrid/code flow, using external identity providers (in this instance Google).  We have an IdentityServer3 instance set up and running, and have the resource owner and custom grant (for Facebook Connect) flows working.  However, for Google authentication, we are getting stuck at the point of exchanging the authorisation code from Google for an access token from our IdentityServer3 instance.

My current belief is that this should be possible:

1. On a mobile app, a user signs in with Google (using the Google SDK)
2. The mobile app obtains an authorization code (and id_token and access_token for Google) from Google, as part of the sign in - obtained as per [https://developers.google.com/identity/sign-in/ios/offline-access](https://developers.google.com/identity/sign-in/ios/offline-access)
3. The app then passes the authorization code to our IdentityServer3 instance - POST to the /token endpoint, grant_type=authorization_code, code=...code from google...
4. The IdentityServer3 instance/Google middleware should validate the code, contact Google and exchange the code for a valid access token - at some point we need one that is valid for our systems

Point 4 is where we are having issues - from looking through the examples and documentation, I haven't been able to find anywhere using an external authorization code in this way.  I have also seen [this post](https://github.com/IdentityServer/IdentityServer3/issues/2369) which seems to be similar, but haven't made any headway, since the Google authentication provider is set up correctly (I have successfully used an implicit-flow JS application to sign in).  From looking through the code, it seems that the token endpoint assumes that the authorization code comes from the identity server itself, and obviously can't find the code in it's store.

Have I misunderstood the hybrid flow and how the authorization code is supposed to be used? Any help would be greatly appreciated.

**Comment by brockallen** [comment]
Wrong grant type -- code is for codes issued by IdSvr. You need to implement a custom grant type to validate the stuff coming from the google sdk (like you must have with facebook?). Anyway, this is more of a SO question, not an issue here.

**Comment by sum1youno** [comment]
I was hoping that I didn't need to use a custom grant type - I have obviously got the wrong end of the stick!

Thanks for the response - and I'll be sure to post on SO instead next time.
