### ISSUE TITLE
Authenticating from a Customer's Service

### ISSUE THREAD

**Issue by j-hurst** [IdentityServer/IdentityServer3#3575]
I have a customer that has a service that needs to communicate with one my services.  My web api services are all secured with IdentityServer.

I am not seeing a way that I can provide the customer with a api call to pass in a username and password to retrieve an access token, as everything appears to expect a call from the IdentityServer login page.

Is this something custom that I would have to build?  Or is there another way I should look at this, for instance using the client credentials flow and giving the customer a secret to use?

**Comment by brockallen** [comment]
Hint: Client credentials flow. 

Having said that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
