### ISSUE TITLE
Mixed email based and non-email usernames

### ISSUE THREAD

**Issue by andrewdolg** [IdentityServer/IdentityServer3#3576]
Hello,

We're integrating IdentityServer3 with our solutions. The solution supports both plain usernames and email addresses as usernames.
EmailIsUsername lets you select only one type or the other.
Is there a way to mix both types of usernames?

Thanks,
Andrew

**Comment by brockallen** [comment]
Wrong repo. EmailIsUsername is not something in IdentityServer.
