### ISSUE TITLE
Question: Is it possible to use an authentication method other than username/password and remain within the existing AuthenticationController

### ISSUE THREAD

**Issue by garymacpherson** [IdentityServer/IdentityServer3#3577]
Just want to confirm my understanding here...

I have an IdSvr3 implementation servicing multiple different clients, one of which uses a username, password and a third custom field for authentication which I have been able to handle correctly by overriding the AuthenticateLocalAsync function inside my custom UserService.

        public override async Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            var form = await ctx.Request.ReadFormAsync();
            var thirdValue = form["thirdvalue"]
            /*.....*/
        }

My second client however, also has 3 fields required to get a valid authentication, but those fields are a unique number (like a service ticket), email address and date of birth. So while I can pick those fields up with the same approach above, obviously the IdSvr3 AuthenticationController.LoginLocal() function is validating against the values of Username and Password which I no longer have in my form.

I know that I can get around this by overriding PreAuthenticateAsync and pushing the request to my own custom AuthenticationController, however I want to confirm that this is indeed the correct process or is there some way to stay more within the functionality provided by IdSvr3 and go less rogue about the whole thing.

        public override Task PreAuthenticateAsync(PreAuthenticationContext context)
        {
            switch (context.SignInMessage.ClientId)
            {
                case "MyClientWithNoUsernameOrPasswordFields":
                    var id = ctx.Request.Query.Get("signin");
                    context.AuthenticateResult = new AuthenticateResult("~/custom/login?id=" + id, (IEnumerable<Claim>)null);
                    return Task.FromResult(0);
                default:
                    throw new Exception();
            }
        }

Essentially I am asking, is there a way to have a login form without username or password and still play within the functionality provided by IdSvr3, or am I on my own now and basically going to have to implement my own AuthenticationController?

**Comment by leastprivilege** [comment]
Have you thought about moving to IdentityServer4 - this would make your life **much** easier.

https://leastprivilege.com/2017/01/15/platforms-where-you-can-run-identityserver4/

**Comment by garymacpherson** [comment]
Yep, at this point I am searching for excuses to justify the expense to move to 4.

Does 4 specifically have improvements related to more flexible login form definitions while remaining within the provided functionality?

**Comment by leastprivilege** [comment]
In 4 you can do your whole login workflow in standard MVC

**Comment by garymacpherson** [comment]
Thanks again for the invaluable comments.
