### ISSUE TITLE
Signature validation failed with IdentityServer3

### ISSUE THREAD

**Issue by rgottumu** [IdentityServer/IdentityServer3#3581]
I am trying to set up code flow client with my IdentityServer3. I am using MVC Manual Code Flow Client from IdentityServer3 sample to test this. Client is successfully authenticated but fails to get the token with the following error.

`IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
   (
   IsReadOnly = False,
   Count = 2,
   Clause[0] = X509ThumbprintKeyIdentifierClause(Hash = 0x55649DCE78A9B0B42FDF4CC659B15156BB5C446A),
   Clause[1] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
   )
', 
token: '{"typ":"JWT","alg":"RS256","x5t":"VWSdznipsLQv30zGWbFRVrtcRGo","kid":"VWSdznipsLQv30zGWbFRVrtcRGo"}.`

Discovery document from https://localhost/.well-known/jwks

`{
keys: [
{
kty: "RSA",
use: "sig",
kid: "VWSdznipsLQv30zGWbFRVrtcRGo",
x5t: "VWSdznipsLQv30zGWbFRVrtcRGo",
e: "AQAB",
n: "ouNxssUW6dZyoqfYLnT-IsEK_h8BUHvbqJF_Quiqiu1ZjJuHSuRs8Wwew8tmZG1c8xQI64DSTYdG2jgq_T0sErOvtPs88IgUwDkV3T3wB8eNouxfcH7p_fMFDuma3KmQzAun_kshBBuod9Zhffw1XnM3QeBu5-WLcSXpXXwTj7YnIYsX3CfJvO0XojNdBW9O37KCYD8LwHtAUkSEFATOm7auhkq5iTJrH5PzzL9lziM_LaKOLvf8VueXSJg5WiKoudnNpwXBKB1fT0BdmB9wIhVymsReY6diPUrmWCucSDw5TCzi-XdBcUnxugw9jAJYJOoxh8uKlOoLHm6qsCjUHw",
x5c: [
"MIIFGjCCBAKgAwIBAgIHK0l/+2ftyDANBgkqhkiG9w0BAQsFADCBtDELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHkuY29tLCBJbmMuMS0wKwYDVQQLEyRodHRwOi8vY2VydHMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS8xMzAxBgNVBAMTKkdvIERhZGR5IFNlY3VyZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgLSBHMjAeFw0xNDEwMTgxNjUyMDBaFw0xODExMjMxNTE1MjNaMDkxITAfBgNVBAsTGERvbWFpbiBDb250cm9sIFZhbGlkYXRlZDEUMBIGA1UEAwwLKi5maGNyYy5vcmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCi43GyxRbp1nKip9gudP4iwQr+HwFQe9uokX9C6KqK7VmMm4dK5GzxbB7Dy2ZkbVzzFAjrgNJNh0baOCr9PSwSs6+0+zzwiBTAORXdPfAHx42i7F9wfun98wUO6ZrcqZDMC6f+SyEEG6h31mF9/DVeczdB4G7n5YtxJeldfBOPtichixfcJ8m87ReiM10Fb07fsoJgPwvAe0BSRIQUBM6btq6GSrmJMmsfk/PMv2XOIz8too4u9/xW55dImDlaIqi52c2nBcEoHV9PQF2YH3AiFXKaxF5jp2I9SuZYK5xIPDlMLOL5d0FxSfG6DD2MAlgk6jGHy4qU6gsebqqwKNQfAgMBAAGjggGpMIIBpTAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAOBgNVHQ8BAf8EBAMCBaAwNgYDVR0fBC8wLTAroCmgJ4YlaHR0cDovL2NybC5nb2RhZGR5LmNvbS9nZGlnMnMxLTg3LmNybDBTBgNVHSAETDBKMEgGC2CGSAGG/W0BBxcBMDkwNwYIKwYBBQUHAgEWK2h0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS8wdgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS9nZGlnMi5jcnQwHwYDVR0jBBgwFoAUQMK9J47MNIMwojPX+2yz8LQsgM4wIQYDVR0RBBowGIILKi5maGNyYy5vcmeCCWZoY3JjLm9yZzAdBgNVHQ4EFgQU3RHvG4vE3WmykX7jD56/PeLggRAwDQYJKoZIhvcNAQELBQADggEBAKvnQDKEItagRRGkrm+SHBgN2a3CVcirgehMqM/5PO1/W9MuPpB5V6oX2np44B2V133RPsRCD2ORG2QqyW409yeFzpBAlsdBBmOnp5sKxUZaKrbby1dH/k9u6B704oHOgutLXGxrG3kEnH1PIJVHDT9isM8AojuIbXbnO/E0ABUtQ324jJ21rE/6HdvULm3KHcou5nLYs1VdnDjhgffpJeghU9qwpyHlxDOyFHad56xoXM8ippS4WZGw112uwszfgrYnBXw1QZ4SqdAEjkpd9Dbaav0UBD+fkuPRjQB7xbwEyqXqjvyZeWPRGJL6WS5b89PpQMFcYJ9L/xlB1OJA3KU="
]
}
]
}`

Thanks in advance.

**Comment by rgottumu** [comment]
any help?

**Comment by brockallen** [comment]
Where are you getting this error? What context or call stack?

**Comment by rgottumu** [comment]
sorry Allen, I should have done this before. I replaced the test certificate string in the example with my cert string from discovery document. Everything works fine now. Thanks.

**Comment by supetranmp** [comment]
@rgottumu 

I am stuck with this issue right now, just want to ask how you specifically solved it from code? I've read others solved it with the same solution as you mentioned, but I don't know exactly how.
