### ISSUE TITLE
Redis For Operational Data,How to implement GetAllAsync and RevokeAsync

### ISSUE THREAD

**Issue by poweryang1990** [IdentityServer/IdentityServer3#3582]
### Question / Issue
I'm try to implement ITransientDataRepository<T> using by  redis ，but i don't know how to implement   the method named GetAllAsync and RevokeAsync,
eg
```csharp
 public class DistributedAuthorizationCodeStore : BaseStore, IAuthorizationCodeStore
    {
        public DistributedAuthorizationCodeStore(IDistributedCacheProvider distributedCache) : base(distributedCache)
        {
        }

        public Task<IEnumerable<ITokenMetadata>> GetAllAsync(string subject)
        {
            throw new NotImplementedException();
        }

        public Task<AuthorizationCode> GetAsync(string key)
        {
            return DistributedCache.GetAsync<AuthorizationCode>(MergeKey(key));
        }

        public Task RemoveAsync(string key)
        {
            return DistributedCache.RemoveAsync(MergeKey(key));
        }

        public Task RevokeAsync(string subject, string client)
        {
            throw new NotImplementedException();
        }

        public Task StoreAsync(string key, AuthorizationCode value)
        {
            return DistributedCache.SetAsync(MergeKey(key), value);
        }
    }
```

I would like to ask how to do better, if not to implement these two methods will not have any problems,
thank you!

**Comment by brockallen** [comment]
No idea about reddis, sorry. This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by poweryang1990** [comment]
thanks
