### ISSUE TITLE
Question: Get user friendly Client Application name in EULA page

### ISSUE THREAD

**Issue by wlafrance** [IdentityServer/IdentityServer3#3583]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Cross posted on Stackoverflow [ [link ](https://stackoverflow.com/questions/42840038/get-user-friendly-client-application-name-in-eula-page)]
In our login template (located in the template folder) I am referencing the following to show the application name (Client App) to the user.

`
 {{model.clientName}}
`
The client name in my instance is a user friendly name for the application. For example: FMS Reporting System The clientId could be something like: fms001.reporting which I can't use for the user. Now, once the user enters a valid user and pwd they get routed to the EULA page. I also need to display this value on this page. I was thinking this was in the owinContext but I don't see it...

`public class EULAController : Controller`
`{`
`    [Route("core/eula")]`
`    [HttpGet]`
`    public ActionResult Index()`
`    {`
`        var partialLogin = Request.GetOwinContext();`
`        // was hoping to get the clientname here????`
`        return View();`
`    }`
 
**_Question: So how do I get a hold on this value in the EULA MVC controller?_**
### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Resolve the IClientStore from DI via the OWIN extensions: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html
