### ISSUE TITLE
UseIdentityServerBearerTokenAuthentication mention list of audiences allowed

### ISSUE THREAD

**Issue by FullyCSharped** [IdentityServer/IdentityServer3#3584]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Hi,

I am trying to use a API with bearer token authentication with the following code 
```
  inner.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = authorityUrl,
                    RequiredScopes = new string[] { "someScope" },
                    DelayLoadMetadata = true,
                    SigningCertificate = Certificate.Load("sdsds", "jgVteAUFYQVsdsQXXbPMghN"),
                    TokenProvider =new ContextTokenProvider(inner)
                });

```

is there a way i can mention the list of allowed audiences here in this configuration which can be used during token validation?

**Comment by leastprivilege** [comment]
No - that's what the scopes are for.

**Comment by FullyCSharped** [comment]
@leastprivilege , I have a situation where the access token requestand the api call happens on two different url's, which is giving me an audience mismatch error during token validation

**Comment by leastprivilege** [comment]
That means your issuer URI is not stable somehow?

**Comment by FullyCSharped** [comment]
@leastprivilege , Yes

**Comment by leastprivilege** [comment]
then you need to fix that.

**Comment by FullyCSharped** [comment]
I tried using options in the above code for setting issuer name.. But no
luck... Is there a different approach

**Comment by brockallen** [comment]
> then you need to fix that.

No, he means in the token server itself.

**Comment by FullyCSharped** [comment]
@brockallen, Can u help me here with an example please

**Comment by brockallen** [comment]
I don't know what you mean. You run a token server, and you are in control of it, so you should configure it to use a consistent issuer name.
