### ISSUE TITLE
 ASP.Net MVC and WebApi authentication using Identity server

### ISSUE THREAD

**Issue by TeamAV** [IdentityServer/IdentityServer3#3586]
Hi,
I am new to Identity server and wants to secure my two apps (MVC, Webapi) using it.
I have seen the example where we can invoke the webapi from MVC action method and SetBearerToken that was issued to the the MVC application. I am referring the below sample:

https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html

This is typical example  of server to server communication where we are using access token issued to the MVC app for Web api.

 In the same scenario, I want to call webapi from Javascript client(fro ex Angular or any one) using same access token.

"I want to pass the the access token issued to the MVC application to call WebAPI from JavaScript"

How can I utilize the token that was issued to my MVC application from the JavaScript client?

Thanks

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io

**Comment by TeamAV** [comment]
Ok Thanks
