### ISSUE TITLE
Calling the GetPartialLoginResumeUrlAsync extension method results in "No partial login" exception

### ISSUE THREAD

**Issue by mehdi-mousavi** [IdentityServer/IdentityServer3#3587]
### Question / Issue - "No partial login"
I got a requirement to confirm the user's email address (before logging in) once he has been inactive for a given period of time. When I detect such a user in AuthenticateLocalAsync method, I send a verification email to his email address, and set the AuthenticateResult as follows:

```
context.AuthenticateResult = new AuthenticateResult(
    redirectPath: VerificationHelper.GetVerificationUrl(context.UserName),
    subject: userId.ToString(),
    name: context.UserName);
```

According to the [documentation](https://identityserver.github.io/Documentation/docsv2/advanced/userService.html#authenticateresult) this is supposed to create a partial login. Once the above code executes, the user is redirected to the "/verify.aspx" page where he is instructed to click on the link that has been sent to his email address (and nothing else). Once the user confirms his email address, I try to get the PartialLoginResumeUrl from the OWIN context:

`string url = Request.GetOwinContext().Environment.GetPartialLoginResumeUrlAsync().Result;`

However, the above line throws the "No partial login" exception. Am I doing something wrong? Any help would be highly appreciated.

**Comment by brockallen** [comment]
You can only use these if the partial login path is in the same pipeline as the IdentityServer middleware.

**Comment by jishnus** [comment]
Could you please provide the sample code for this.
