### ISSUE TITLE
Question related to LoginPageLinks the signin query param and server farms

### ISSUE THREAD

**Issue by wiseman13** [IdentityServer/IdentityServer3#3589]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I currently use IdenityServer3 hosted in an IIS farm behind a Microsoft ARR server. Since I do not do partial login everything from the authentication side has been stateless, but we have a forgot password link we are adding via the LoginPageLink property. I am able to receive the signin parameter and echo it back, but I am interested in understanding how that parameter is used and if there is some in memory cache object that I need to move to being backed by a database so that it will not matter which node picks up the request.

Thank you for your help.

**Comment by wiseman13** [comment]
Okay I might have answered this myself, but from what I am seeing that key is just used to look for a cookie that was stored locally so it should not matter which node is servicing the request.

**Comment by brockallen** [comment]
Yep, it's for the cookie.
