### ISSUE TITLE
Deployment options - location of clients and IdSrv

### ISSUE THREAD

**Issue by daniel-cunning** [IdentityServer/IdentityServer3#3590]
I am working on a team implementing Identity Server.  After following all documentation (that we can find), examples projects and PluralSight videos, we never got a clear picture of how this is best deployed in a production environment.

Our DMZ is behind load balancers.  As we developed this, we had assumed both the clients and the actual IdSrv site would sit in the DMZ and communicate with the database through the firewall.  There have been concerns raised however that IdSrv should sit inside the network and that our clients sit in the DMZ.  Since clients work with IdSrv by redirects, and I have seen them fail if the redirects are out-of-sync, is this deployment an option?  Is there concern about having both in the DMZ since the load balancers might have the clients communicating with "different" IdSrv sites, or does the built in caching handle that?

Thanks for any feedback/ideas.  We are currently gearing up to deploy both the client and IdSrv in the DMZ to see how it works.  If anyone knows of a good reason to do this, or something else, we would appreciate hearing it.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
