### ISSUE TITLE
wctx not returning the correct return url once user is authenticated in Identity Server 3

### ISSUE THREAD

**Issue by jschaufele** [IdentityServer/IdentityServer3#3591]
In my application after the user is authenticated i need to dynamically send them to a new location. If the user is not authenticated this work fine but if they are IDS just uses the default reply address. So it would be great if 
1. could figure out how to log them out then redirect them 
2. get IDS to respect the wctx redirect.

what i found is if the user is not authenticated IDS will use /callback and sets the /_trust post location to the correct wctx , if the person is already authenticated it just uses the default reply url

I am working SharePoint 2013 using IDS w/ its Idp and it configured with multiple authenticating providers

any help would be appreciated

**Comment by leastprivilege** [comment]
wctx is unrelated to redirects - it is a general purpose state mechanism. It might be used for redirects in your particular case.

Are you saying we are not properly round tripping the value of wctx in certain situations?

**Comment by jschaufele** [comment]
Yes - 

SharePoint uses the wctx value so it knows where the person was popped for authentication. There is a full endpoint with a querystring passed everytime it requires authentication , see below:

https://identitydev.abc.net/wsfed?wa=wsignin1.0&wtrealm=https%3a%2f%2fdev.abc.net&wctx=https%3a%2f%2fdev.abc.net%2fmeetingcentral%2fb2682b05-083f-4880-9a8a-9506dcdc76fc%2f_layouts%2f15%2fauthenticate.aspx%3fsource%3d%252fmeetingcentral%252fb2682b05%252d083f%252d4880%252d9a8a%252d9506dcdc76fc%252

If a person is sent back to IDS from SharePoint after they have been authenticated  (no logon prompt) by IDS, IDS does not use the callback endpoint and sets the location header of the URL to SharePoint with a relative URL from the wctx whereas if user authenticates for the first time (login prompt) it passed the full value of the wctx.

**Comment by leastprivilege** [comment]
So just to be clear - IS will always use the reply URL configured for the RP 

- but you are saying the wctx format is different for first time login vs SSO?

@scottbrady91 can you look into that please?

**Comment by jschaufele** [comment]
ok sure but how IS responce tx is different depending on the state of IS/user's authentication state

If there was a way for me me to override how IS used the reply transaction i'd look into it 

Thanks

**Comment by leastprivilege** [comment]
That's maybe a bug - how can we repro it so we can look into it?

**Comment by jschaufele** [comment]
All you would need to do is after having been authenticated w/ IS , use the same URL as was sent to IS and you should see the location of the response is truncated to the relative path from the wctx -

**Comment by scottbrady91** [comment]
I can't replicate this issue. In existing systems I have IdentityServer echoing the correct wctx that was passed to it by SharePoint, both on the initial authentication request and subsequent requests where the user is already authenticated.

IdentityServer always sends the SAML token back to SharePoints /_trust/default.aspx endpoint (or wherever you have the reply url configured within IdentityServer), and echoes back the same wctx that was given to it in the request. From there on any redirection/request handling is SharePoint's responsibility.

I recommend setting `UseWReply` in your TrustedIdentityTokenIssuer settings in to true. I've had strange behavior from SharePoint without this.

**Comment by jschaufele** [comment]
Thanks will look at this

Also I have some suggestions for your multitenant solution for ASP Identity / SP– not sure if you are still moving down that path – I know you had done a bit of SP work initially –

The other issue I had to overcome was signing out – I finally  was able to do this from the SP side and a call back to IDS –

All in all IDS was the right choice and appreciate all your help

If you ever have a couple minutes I’d like to ask you a couple questions – more about middleware , programming – can’t find any references and know you have solved them –

Anyway thanks

J

**Comment by leastprivilege** [comment]
Closing for now - feel free to re-open if it needs further discussion.
