### ISSUE TITLE
Having a default client to prevent the "There is an error determining which application you are signing into" error.

### ISSUE THREAD

**Issue by mehdi-mousavi** [IdentityServer/IdentityServer3#3592]
#### Question
I got a scenario in which I've to host both IdentityServer and one of it's Clients on the same domain in which the client is used to manage users. When I hit a secure page of the client, the IdSrv correctly redirects me to the login page. Here, instead of entering credentials, I intentionally remove the browser's cache so that IdSrv has no idea which client is trying to log in and hence the following error occurs:

> There is an error determining which application you are signing into. Return to the application and try again.

I would like to know whether there's a legit way to detect the above error before hitting the IViewService's Error method so that I can redirect the user to the "login page" manually.

Of course, I can do this in IViewService.Error method, however, I'd like to know if this can be detected before the execution gets there since the only way I can detect the above error within this method is to check for the model.ErrorMessage property which is not obviously a good solution. Basically, I need to have a "default" client to prevent such an error in the first place. Thank you.

**Comment by brockallen** [comment]
There's a property to allow you to trap this scenario via a redirect.

**Comment by mehdi-mousavi** [comment]
What property are you referring to? Could you please be more specific?

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AuthenticationOptions.cs#L162
