### ISSUE TITLE
Logout Page Issue

### ISSUE THREAD

**Issue by sankp** [IdentityServer/IdentityServer3#3595]
![image](https://cloud.githubusercontent.com/assets/9613276/24333241/15fd9f74-121a-11e7-98a9-21c51ceb6fc0.png)

Hello,

I am able to logout but i am not able to see click here to go back to application.
Everything is empty here.
![image](https://cloud.githubusercontent.com/assets/9613276/24333281/dd306798-121a-11e7-9ab0-e8b551b84250.png)

**Comment by brockallen** [comment]
Check the logs

**Comment by ahokkonen-dev** [comment]
Is PostLogourRedirectUrl provided and it matches with configurated one?
