### ISSUE TITLE
Can/should I host login screen in my client application?

### ISSUE THREAD

**Issue by zoehart** [IdentityServer/IdentityServer3#3599]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am very new to IdentityServer and Open ID Connect and most of what I know comes through the three walk throughs in the Overview section of the IdentityServer3 documentation. All of those samples demonstrate how to use the Authorize attribute to secure a controller action, which results in a redirect to the IdentityServer-hosted login page. Is there a viable, best (or reasonably good) practice approach that includes a client application-hosted login page, which is what my client application has always had? Put another way: my client application currently has a Login link in the top menu that goes to a client application-hosted login screen. As I move to using an IdentityServer-based authentication service, is there a model in which my client application screen captures the user's username and password and calls the authentication service to validate them? If so, is there a sample for that? If not, what is the recommended approach to a Login link in the application? 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
