### ISSUE TITLE
Implicit Flow - authorize endpoint returns tokens long after expiration without having to login

### ISSUE THREAD

**Issue by iamlekz** [IdentityServer/IdentityServer3#3600]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have an SPA that's using Implicit Flow.
AccessTokenLifetime and IdentityTokenLifetime are both set to 70 seconds.
I'm using the OIDC js library.

Upon first loading application, I call userManager.signinRedirect().
User logs in at IdentityServer and is returned to the client and all is well.

If I close the application and return later,  I detect that the user is expired and call userManager.signinRedirect(). 
When we are within the token expiration times, signinRedirect issues a request to the /authorize endpoint (with response_type: id_token token) and then redirects back to the SPA's callback with the requested tokens in the url.  

When we are beyond the expirations (even way past the 5 minute clock skew), we are still being redirected to /authorize and then back to the SPA callback with tokens. I would've expected that IdentityServer would know the client is expired and force a login again.  

Within fiddler, I can replay the request long after both the id and access expirations; the 302 location header is still routing me back to my app with valid tokens.
I notice that the cookie 'idsvr' is present and if I remove that from the request, I am forced to login.  

Why would I be able to get new tokens after expirations without having to log in again?
Is there something I should be doing in my SPA if user is expired before I call signinRedirect?

Thanks in advance!

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Access token expiration is unrelated to the user's authentication session in IdentityServer.

**Comment by iamlekz** [comment]
I figured as much but wanted to provide any relevant information.  

The identity token is expired in this scenario as well and I can still get a new token without having to login a good 20 minutes after by replaying the /authorize request in fiddler. 
Seems the cookie 'idsvr' is providing the magic that makes this happen but unless I'm missing something I'd think request would redirect to login screen.

**Comment by brockallen** [comment]
The cookie at IdSvr is the magic. The lifetime of an id_token only needs to be long enough to survive the delivery from IdSvr to the client. Once the client gets it and validates it, it must decide what it wants for user lifetime (and also take into consideration presence/use of an access_token).

**Comment by iamlekz** [comment]
Thanks for the clarification. 
The issue stemmed from the fact that Chrome is keeping session cookies around even after I close and re-open the browser.  I know this is a Chrome issue but was still surprised that the cookie could be used after such a long time.  

I do recall now in one of the NDC talks where this is mentioned in regards to Expiration.  That if the token is expired but the cookie is still valid we can still get a new token.  

So now I experimented a bit with CookieOptions and the ExpireTimeSpan property and it seems I have some control over how long the cookie is valid.  After running through some tests and setting the ExpireTimeSpan to 2 minutes with SlidingExpiration = true, the user is being forced to re-login despite still having the idSvr cookie.  

Thank you again
