### ISSUE TITLE
IAuthenticationSessionStoreProvider registration

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3#3604]
Is there a better way to do the following registration ? I am looking 

![image](https://cloud.githubusercontent.com/assets/8946667/24443801/f5b2695e-145b-11e7-8ad2-a0789ed3550e.png)

I have the following registration, which I would like to be injected to my IAuthenticationSessionStoreProvider above.

![image](https://cloud.githubusercontent.com/assets/8946667/24443811/06aa74cc-145c-11e7-8438-0fac8a65c40c.png)

**Comment by brockallen** [comment]
Yea, not a bad idea, but we'd have a problem getting an OWIN context in there (which is needed to do what you want). The cookie provider  model doesn't lend itself to that.

**Comment by aaabdul** [comment]
Suspected as much. I guess we'll have to wait for cookie model to change.
