### ISSUE TITLE
Is it a way to restrict the anonymous users requests via IdSrv3

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3#3608]
I have two angularJs applications and WebAPIs backend.
 I implement the authentication between them via IdSrv3 implicit flow.
Each JS Web App have it's IdentityServer ClientId for example 1 and 2
Some one tell me that we want to restrict the anonymous access for some of our APIs end points to only the anonymous users that come from the only 2 JS web apps and not for example from any request via fiddler or postman.
I tried to build owin middleware to handle this and i put it in a pipeline before the identityserver middleware but he tell me that the IdSrv by default can did this job?

I searched a lot but i don't find a correct approach to restrict  anonymous users  to only the users that comes from the angularjs apps?

**Comment by deserthero** [comment]
Any response

**Comment by brockallen** [comment]
If the user is anonymous, then how can you restrict them? It doesn't make sense, unless you have some way to track, verify, or authenticate them.
