### ISSUE TITLE
Using IdentityServer3 as an OpenID Connect provider with another identity server

### ISSUE THREAD

**Issue by salmonz** [IdentityServer/IdentityServer3#3609]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I am trying to use identity server as an open id connect provider to an existing identity server.

Given the flow -
Client web site > identityserver3 > open id connect provider (another identityserver3)
I expect my client web app to go to the IdS, present a list of providers, I login with that provider, and get redirected eventually to the client web app (either directly or double redirect through the identity server).

The problem I'm getting is one I login to the provider, it redirects me back to the identity server and DOES NOT redirect me back to client web site.

I am using the implicit flow and MVC C#.

Is there a working example of this? What am I missing?

**Comment by brockallen** [comment]
Check all the logs.

**Comment by salmonz** [comment]
I found that between the identity server and the identity provider, the redirect Uri must include /identity as well. e.g. https://localhost:44312/identity. All is working now.
I think having a working example in the IdentityServer3 and IdentityServer4 repos of this scenario can help others.

**Comment by rolfeisenhut** [comment]
i have the same requirement,  where can i find the complete sample?
