### ISSUE TITLE
Is it possible to let the API request a token (with the user's credentials) without redirecting the user to the IdentityServer Login Page.

### ISSUE THREAD

**Issue by Tarek-AbdelMaqsoud** [IdentityServer/IdentityServer3#3611]
Hello,
I just came across a problem that i need to know if it could be possible with IdentityServer

I have an angular Client, API, and the Identity Server for authentication
for some reason, i need to pass the user credentials two different ways, the 1st one is to be as it is, so the user can login through the IdentityServer.

The 2nd way, the user will enter his Identity, and pass it to the API, the API will create an In Memory User and pass it to the IdentityServer requesting a unique token for this specific user, without redirecting the user to the IdentityServer login page.

So the scenario can be as following 
1- Angular client will call the API endpoint
2- API will do the stuff, returning the token as a response 
3- Angular client will deal with this token with any other API endpoint, that needs authorization.

**Comment by mainettis** [comment]
Is this what you're looking for? https://identityserver.github.io/Documentation/docsv2/endpoints/token.html

**Comment by Tarek-AbdelMaqsoud** [comment]
Thanks a lot for your help, actually i have found what exactly i am looking for 

http://benfoster.io/blog/identity-server-post-registration-sign-in

Thank you :)
