### ISSUE TITLE
IdentityServer3 and MultiTenancy 

### ISSUE THREAD

**Issue by Tarek-AbdelMaqsoud** [IdentityServer/IdentityServer3#3614]
Hello, 
Does the IdentityServer3 support Multi-Tenancy ?!, if so, could you please provide a doc on how to do it

Thank you so much

**Comment by brockallen** [comment]
You must build what you think multi-tenancy means into IdSvr yourself.

**Comment by Tarek-AbdelMaqsoud** [comment]
OK, Thanks :)
