### ISSUE TITLE
Explicitly generating OAuth2 response

### ISSUE THREAD

**Issue by abcplex** [IdentityServer/IdentityServer3#3615]
I can explicitly get access_token using IssueClientToken method https://github.com/IdentityServer/IdentityServer3/issues/3429. But how can I explicitly generate the oauth2 success response. For example, currently in my app after successful authentication I am getting this response,

`{"access_token":"xxx","expires_in":3600,"token_type":"Bearer","refresh_token":"xxx"}`

and in case of failed,

`{"error":"invalid_grant","error_description":"2"}`

Please help?

**Comment by brockallen** [comment]
check the logs

**Comment by abcplex** [comment]
Sorry, I mean programmatically. Means using C# code, I can I generate the response.
