### ISSUE TITLE
JWT Access Token and Identity Token has Different Audience

### ISSUE THREAD

**Issue by FredBesterwitch** [IdentityServer/IdentityServer3#3616]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am using RequestResourceOwnerPasswordAsync("uid","pwd","openid aud email")  to authenticate to and ADFS 2016 server.

how can I get them to be the same, the identoty token is correct.

My Access Token aud and iss are different to the identity, is the ADFS wrongly configured or do I need to send more parameters ?

THANKS
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "l_OZUmitFFug_qgT4aBrvnyxm94"
}
{
  **"aud": "urn:microsoft:userinfo",
  "iss": "http://MYAUTHSERVER/adfs/services/trust",**
  "iat": 1491214875,
  "exp": 1491218475,
  "apptype": "Confidential",
  "appid": "PDLAPI",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2017-04-03T10:21:15.733Z",
  "ver": "1.0",
  "scp": "openid",
  "sub": "xBZpMT9zNKNyMjFsj4CF80crrwS/ATrfkgm4n4iYDFw="
}
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "l_OZUmitFFug_qgT4aBrvnyxm94",
  "kid": "l_OZUmitFFug_qgT4aBrvnyxm94"
}
{
  **"aud": "PDLAPI",
  "iss": "https://MYAUTHSERVER/adfs",**
  "iat": 1491214875,
  "exp": 1491218475,
  "auth_time": 1491214875,
  "sub": "xBZpMT9zNKNyMjFsj4CF80crrwS/ATrfkgm4n4iYDFw=",
  "upn": "myname@domain.com",
  "unique_name": "DonaldTrump"
}

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
This seems to be an ADFS questions. Please ask Microsoft.
