### ISSUE TITLE
System.Web.HttpException (0x80004005): Server cannot append header after HTTP headers have been sent.

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer3#3618]
I am trying to do single sign-out with ws-fed.

Getting following error:
> Url
>     /core/wsfed?wa=wsignoutcleanup1.0
> 
> System.Web.HttpException (0x80004005): Server cannot append header after HTTP headers have been sent.
>    at System.Web.HttpHeaderCollection.SetHeader(String name, String value, Boolean replace)

### Question / Issue
I am trying to do single sign off, and my code is this:
```
// remove cookies on wsignout cleanup request
            appBuilder.Use(async (ctx, next) =>
            {
                var qs = ctx.Request.Query;
                var wa = qs.Get("wa");
                if (!string.IsNullOrEmpty(wa) && wa.Equals("wsignoutcleanup1.0"))
                {
                    ctx.Authentication.SignOut("Cookies");
                    await ctx.Environment.ProcessFederatedSignoutAsync();
                }

                await next();
            });
```

Problem is that once I invoke wsignoutcleanup1.0 I get an error 

> System.Web.HttpException (0x80004005): Server cannot append header after HTTP headers have been sent.

**Comment by brockallen** [comment]
Do you need to call next if it's a signout?

**Comment by nukec** [comment]
Not really, next was there and it worked for SignOut("Cookie"); as soon as I add ProcessFederatedSignoutAsync it stops working. I can try without next.
