### ISSUE TITLE
Deploying to IIS problems

### ISSUE THREAD

**Issue by stuartbloom** [IdentityServer/IdentityServer3#3620]
Hi there, I hope someone can help me, and I apologise if this is a silly question.

Our API is working fine when running in IIS Express using Visual Studio.

Now when I deploy it to IIS I am getting some strange errors when accessing IdentityServer.if I turn off the authorize decoration on my controllers I can access them no bother.

When trying to access, for example: https://localhost/ProjectVision_api/identity/.well-known/openid-configuration, I get the following error:
![image](https://cloud.githubusercontent.com/assets/7871566/24712140/ed52e8ce-1a19-11e7-866f-723cf3fd7805.png)

If I give "everyone" permissions to that file and try again, I get:
![image](https://cloud.githubusercontent.com/assets/7871566/24712195/1b0667dc-1a1a-11e7-897b-8f9c43d84be7.png)

Are there any other settings I need to setup?  I have created a self signed certificate for initial testing, so I do get the https struck through, but that happens when accessing the API or IdentityServer.

Thanks in advance for any pointers

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by stuartbloom** [comment]
Thanks and sorry; posted there.
