### ISSUE TITLE
How to inform a specific client of an IdentityServer that it has to invalidate its own cache?

### ISSUE THREAD

**Issue by mehdi-mousavi** [IdentityServer/IdentityServer3#3623]
I got two clients, say, UserAccountsApp, and the MainApp which both are owned by the same company. The former is basically an IdentityServer "client & server" itself so that it handles generating identity tokens as well as creating new user accounts, and updating existing ones. OTOH, the MainApp is a large ASP.NET Web Forms application, which keeps the User ID, Full Name and the Email Address of those users (the very same exact users that UserAccountsApp manages) in its own data source and has been extensively addressed throughout the application.

Now, let's say that an existing user info gets updated in the UserAccountsApp. This means that the MainApp has to be "somehow" notified of that change so that it can invalidate its own cache and eventually its own data source to reflect those changes. I would like to know what's the correct approach to do that.

Any help would be highly appreciated.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
