### ISSUE TITLE
ASP.NET Identity cross check in CheckSession endpoint

### ISSUE THREAD

**Issue by slaneyrw** [IdentityServer/IdentityServer3#3625]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Hi Brock and co...

We have a scenario where a user can be locked out ( passwords, verification codes, admin hardlock, etc) and I want to notify ALL current web sessions authenticated against that user that the user is no longer valid.  We have already configured federated signout.

Scenario.

User 1 logged into client "App1" via external IdSvr site using OIDC.
User 2 attempts to log into "App1" ( or App2, ... AppN ) using same user name as User 1 above and locks the account in the IdSvr's user store ( eg. wrong password too many times ).

I want to invalidate all current sessions for this user in all Relying apps as soon as practical.

My first thought was to use the OIDC check session endpoint to verify whether the logged in User ( as available in the ASP.NET Identity cookie / Owin IAuthenticationManager ) is still valid.  But the endpoint appears to only check the user's idsrv.session cookie value against the passed values on the IFrame's message post in javascript without make any server calls ( at least after IFrame rendered for first time in user's RA ).  The application is a SPA so the IFrame is rarely re-rendered in the user's session.

Is this scenario possible using check session or will I have to implement a custom endpoint ?

I have looked into overriding the openid URL for the check session endpoint but it's hardcoded for 'connection/endsession' and I can't override using a DiscoveryOption CustomEntry.
I've tried looking for a hook when rendering the checksession HTML but the CheckSessionEndpointController directly renders HTML from the asset manager.  I also cannot seem to add a web api Filter or owin middleware to the internal pipeline to "tweak" the checksession html.

Cheers...
Rob

**Comment by brockallen** [comment]
Sorry, this is more of an architecture question -- Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by slaneyrw** [comment]
ok will do.  Disagree with the architectural statement though, I wanted to find out if there was any possibility of overriding the default behaviour of the checksession endpoint in IdSvr3

I really don't want to fork the entire codebase just to add a hook

**Comment by brockallen** [comment]
Well, in essence the question is asking for advice on how to architect around what the OIDC specs design for (and what IdentityServer implements). It's not a bug or enhancement request for IdentityServer, so that's why it's a better place for SO.
