### ISSUE TITLE
Does Identity Server 3 support 3rd party saml idp? 

### ISSUE THREAD

**Issue by derekhoang23** [IdentityServer/IdentityServer3#3627]
I have a STS server that currently can not be modified. It goes through the whole code flow where you request an authentication code, then use code flow to request openId id token and access token via token endpoint. I plan on using IdSrv3 as a proxy server to transition a saml response to an id and access token. My flow is STS(code request) -> IdSrv3 -> SAML Idp;
SAML Idp(saml response) -> IdSrv3(issue code) -> STS;
STS(token  request) -> IdSrV3(creates access token, id token based on saml response);
IdSrv3(access token, id token) -> STS

Is this possible with Identity Server 3? 
Do I need additional middleware?

Thanks

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
