### ISSUE TITLE
Clrear history after open login page giving error.

### ISSUE THREAD

**Issue by manjitsingh91** [IdentityServer/IdentityServer3#3629]
I am using identityserver3 for my angularjs and mvc appilcation and its a great product.But few days ago my client added an issue and he mentioned if we are on login page and delete the history of browser and then enter username and password then we are unable to login and its giving customerror.And in this 
in Error(ErrorViewModel model) method we are getting model.ErrorMessage ="There is an error determining which application you are signing into. Return to the application and try again." How we can handle this situation.Like we need when we are on login page and then clear history then try to login it have to reload the login page on click of submit button. I am using CustomViewService and angularjs 1 in my identityserver3 project.

**Comment by brockallen** [comment]
There is state that must be maintained from the client to the login page on IdSvr. If the user deletes their browser state, then we can't know where to send them back after login.

**Comment by manjitsingh91** [comment]
So you mean we can't delete the history?

**Comment by brockallen** [comment]
I suspect deleting the history deletes cookies, and that's where we keep this state.

**Comment by manjitsingh91** [comment]
but i have checked with auth0 and other token provider services and in these we can login after deleteing the history.How they handle this. In future can we handle this in identityserver3 or 4 ?

**Comment by manjitsingh91** [comment]
Yup i know we are storing in cookies and when we delete cookies then got this error.

**Comment by brockallen** [comment]
Depends on the context and workflow. In IdSvr4 we did work to remove many of these cookies, and for some of the workflows where something like a cookie is needed there are extensibility points where you can implement the storage to use something other than cookies.

**Comment by manjitsingh91** [comment]
but when we clear history of browser then it also remove local or session storage also.So in future versions i think you have to keep these things in mind. Its just a suggestion from my side please don't mind :)

**Comment by brockallen** [comment]
We have solutions for this in IdSvr4. In IdSvr3 we don't. Sorry.
