### ISSUE TITLE
Azure AD External Provider, Action returned Unauthorized

### ISSUE THREAD

**Issue by omayhemo** [IdentityServer/IdentityServer3#3630]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
http://stackoverflow.com/questions/43233183/identityserver3-azure-active-directory-external-provider-message-action-retur

First External Login request has the browser waiting for the response that is never returned.  This results in the errors below, visible only through logging. If I cancel the request in the browser and immediately click the button again, it works as intended, the browser is sent to the external login screen.

The relevant code is in AuthenticationController.cs Line 330
Immediately after calling context.Authentication.Challenge(authProp, provider) the method returns Unauthorized.

### Relevant parts of the log file

```

iisexpress.exe Information: 0 : 2017-04-05 08:28:09.708 -05:00 [Information] External login requested for provider: "AzureAd"
iisexpress.exe Information: 0 : 2017-04-05 08:28:09.714 -05:00 [Information] Triggering challenge for external identity provider
LibLog Information: 0 : [2017-04-05T13:28:09.7176576Z] Level=Info, Kind=End, Category='System.Web.Http.Action', Id=800000ad-0002-fb00-b63f-84710c7967bb, Message='Action returned 'System.Web.Http.Results.UnauthorizedResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
LibLog Information: 0 : [2017-04-05T13:28:09.7206611Z] Level=Info, Kind=End, Category='System.Web.Http.Action', Id=800000ad-0002-fb00-b63f-84710c7967bb, Operation=ApiControllerActionInvoker.InvokeActionAsync, Status=401 (Unauthorized)
LibLog Information: 0 : [2017-04-05T13:28:09.7216630Z] Level=Info, Kind=Begin, Category='System.Web.Http.Filters', Id=800000ad-0002-fb00-b63f-84710c7967bb, Message='Action filter for 'LoginExternal(String signin, String provider)'', Operation=NoCacheAttribute.OnActionExecutedAsync, Status=401 (Unauthorized)
LibLog Information: 0 : [2017-04-05T13:28:09.7226640Z] Level=Info, Kind=End, Category='System.Web.Http.Filters', Id=800000ad-0002-fb00-b63f-84710c7967bb, Operation=NoCacheAttribute.OnActionExecutedAsync, Status=401 (Unauthorized)
LibLog Information: 0 : [2017-04-05T13:28:09.7226640Z] Level=Info, Kind=Begin, Category='System.Web.Http.Filters', Id=800000ad-0002-fb00-b63f-84710c7967bb, Message='Action filter for 'LoginExternal(String signin, String provider)'', Operation=SecurityHeadersAttribute.OnActionExecutedAsync, Status=401 (Unauthorized)
LibLog Information: 0 : [2017-04-05T13:28:09.7236655Z] Level=Info, Kind=End, Category='System.Web.Http.Filters', Id=800000ad-0002-fb00-b63f-84710c7967bb, Operation=SecurityHeadersAttribute.OnActionExecutedAsync, Status=401 (Unauthorized)
LibLog Information: 0 : [2017-04-05T13:28:09.7246669Z] Level=Info, Kind=End, Category='System.Web.Http.Controllers', Id=800000ad-0002-fb00-b63f-84710c7967bb, Operation=AuthenticationController.ExecuteAsync, Status=401 (Unauthorized)
LibLog Information: 0 : [2017-04-05T13:28:09.7251836Z] Level=Info, Kind=End, Category='System.Web.Http.MessageHandlers', Id=800000ad-0002-fb00-b63f-84710c7967bb, Operation=PassiveAuthenticationMessageHandler.SendAsync, Status=401 (Unauthorized)
LibLog Information: 0 : [2017-04-05T13:28:09.7261856Z] Level=Info, Kind=End, Category='System.Web.Http.MessageHandlers', Id=800000ad-0002-fb00-b63f-84710c7967bb, Operation=DependencyScopeHandler.SendAsync, Status=401 (Unauthorized)
LibLog Information: 0 : [2017-04-05T13:28:09.7271879Z] Sending response, Status=401 (Unauthorized), Method=GET, Url=https://localhost:44396/identity/external?provider=AzureAd&signin=2d92dd18a6106c9b029eb8742d4117a1, Id=800000ad-0002-fb00-b63f-84710c7967bb, Message='Content-type='none', content-length=unknown'
```

**Comment by brockallen** [comment]
Sounds like the deadlock bug in the Katana OIDC MW. See our custom config manager to workaround their bug: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L130

**Comment by omayhemo** [comment]
Thanks for your response.

The example of your link seems to be related WsFed, which I'm not using for AAD, instead using OpenId.
Can I then substitute OpenIdConnectConfiguration type?  Replacing the generic as stated and feeding it the AAD MetadataUrl results in a Invalid JSON Primitive.

Any further suggestions for me?

Thanks

**Comment by brockallen** [comment]
Sorry, I forget. Try it and see if it improves the issue.

**Comment by omayhemo** [comment]
No sir, that doesn't seem to work.   I simply substituted OpenIdConnectConfiguration type for IConfigurationManager<T> instead of the WsFed as illustrated in your example.  

As soon as I click the external provider button I get the following error.

<pre><code>Invalid JSON primitive: .

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentException: Invalid JSON primitive: .

Source Error: 


Line 36:                 var cultureUi = CultureInfo.CurrentUICulture;
Line 37:                 var culture = CultureInfo.CurrentCulture;
Line 38:                 return _myTaskFactory.StartNew(() =>
Line 39:                 {
Line 40:                     Thread.CurrentThread.CurrentCulture = culture;

Source File: C:\Code\Marquis\Marquis.Id\IdExtensions\SyncConfigurationManager.cs    Line: 38 
</pre></code>

I'm hopeful someone smarter than me can get me heading in the right direction.

**Comment by omayhemo** [comment]
Ok, I found my error.  For OpenId the metadataUrl should be the AAD Authority + "/.well-known/openid-configuration"

Thanks very much for your help.

**Comment by sloukidis** [comment]
I experience the same issue and I implement the @omayhemo workaround. But i want to know if this is safe to use.
