### ISSUE TITLE
Load balance IDServer 3

### ISSUE THREAD

**Issue by vaibhav22oct** [IdentityServer/IdentityServer3#3631]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
What changes are needed in IDServer 3 to make it working with load balancer?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
docs: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html
