### ISSUE TITLE
How to pass info between OpenIdConnectAuthenticationNotifications hooks

### ISSUE THREAD

**Issue by wenchaoli** [IdentityServer/IdentityServer3#3632]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have a requirement that need to dynamic change the external IDP client credentials based on a condition, it tried to save the condition in the signin message, but when external IDP returns auth code, the original signin context seems just be gone. 

So is there any solution to save this condition during a whole external IDP authentication flow ?
How can I make use the hooks in OpenIdConnectAuthenticationNotifications ?\

Thanks a lot!

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Use the OwinContext items collection
