### ISSUE TITLE
Twitter Login hang up (in IdentityServer3)

### ISSUE THREAD

**Issue by Steffen007** [IdentityServer/IdentityServer3#3633]
Hi,

In our solution we use Microsoft.Owin.Security.Twitter for external authentification. If you click the Twitter-Button for the external authentification the application will freeze. A redirect to Twitter is expected.
If you comment out EnableHttpLogging = true (see code), it will work.

I think, it's a deadlock. Please make logging robust. ([Katana issue see here: https://github.com/aspnet/AspNetKatana/issues/51)](https://github.com/aspnet/AspNetKatana/issues/51))

Thanks,
Steffen

**Additional information:**
- Facebook works.
- last log entry: "ObtainRequestToken"
- hang up here (debug):
HttpResponseMessage response = await _httpClient.SendAsync(request, Request.CallCancelled);
_in_
private async Task<RequestToken> ObtainRequestTokenAsync(string consumerKey, string consumerSecret, string callBackUri, AuthenticationProperties properties)
_in_
class TwitterAuthenticationHandler
- tested versions: 3.0.1 and 3.1.0

**Code (Startup):**

```
public void Configuration(IAppBuilder app)
{
	// …
	app.Map("/identity", idsrvApp =>
	{
		// …
		AuthenticationOptions = IdentityServer3.Core.Configuration.AuthenticationOptions
		{
			EnablePostSignOutAutoRedirect = true,
			IdentityProviders = ConfigureIdentityProviders,
		},
		IdentityServerOptions identityServerOptions = new IdentityServerOptions 
		{
			LoggingOptions = new LoggingOptions()
				{
					EnableHttpLogging = true, // PROBLEM
					// …
				},
			AuthenticationOptions = IdentityServer3.Core.Configuration.AuthenticationOptions
			{
				EnablePostSignOutAutoRedirect = true,
				IdentityProviders = ConfigureIdentityProviders,
			},
			// …
		}
	}
}

private void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
{
	// …
	app.UseTwitterAuthentication(new TwitterAuthenticationOptions()
	{
		AuthenticationType = "Twitter",
		Caption = "Twitter",
		SignInAsAuthenticationType = signInAsType,
		ConsumerKey = "…",
		ConsumerSecret = "…",
		BackchannelCertificateValidator = new CertificateSubjectKeyIdentifierValidator(
		new[]
			{
				"90c86a986de20942a693c0115a04866a5053cf3e"
			})
	});
}
```

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
