### ISSUE TITLE
IdentityServer3 behind a Web Application Firewall

### ISSUE THREAD

**Issue by Yliche** [IdentityServer/IdentityServer3#3636]
### Question / Issue

Is it normal practice to put a Web Application Firewall in front of IdentityServer3? I don't believe the OWASP ModSecurity Core Rule Sets were designed for such apps. My understanding is you may be able to do it but have to not enforce SQL Injection or XSS rules.

I'm not sure if there is even a benefit to having a WAF in front of IdentityServer3 or not?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
