### ISSUE TITLE
Restricting what an Implicit client can request in id_token

### ISSUE THREAD

**Issue by lukos** [IdentityServer/IdentityServer3#3639]
There are certain security implications in the Implicit flow in that a request can be made by a client that is not authenticating with the IdP. I am happy with supporting the flow as long as I can restrict what claims are returned in the id token BUT it seems that idsrv will return all id claims in the id token if the response_type is id_token (i.e. the client is not going to be calling the token/userinfo endpoints).

Can I limit what is returned in the browser id_token? I don't mind if the id token from the token endpoint includes everything since the client is authenticated at this point.

Thanks

**Comment by leastprivilege** [comment]
In the user service you have all info you need - client id and caller (id token vs access token vs userinfo).

**Comment by lukos** [comment]
OK, so you're saying I can just hard-code whatever I want in GetProfileDataAsync and it isn't an idsrv config thing. Thanks.

**Comment by lukos** [comment]
This works to prevent the additional claims being returned but it seems there is no mechanism to remove the disallowed scopes from the Consent page so the user sees "Site X is requesting everything" even though we are not going to return anything.

**Comment by leastprivilege** [comment]
Well - if you don't want that an implicit client to request those claims - don't allow them.

in IS3 we allow limited control over niche scenarios like yours - in IS4 you would have more control since you provide all UI bits yourself.
