### ISSUE TITLE
Issue with prompt parameter and OpenId spec

### ISSUE THREAD

**Issue by hvanbakel** [IdentityServer/IdentityServer3#3640]
According to the spec these are the values that one can specify for the prompt parameter on the authorization endpoint (from [spec](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)) empasis mine

> prompt
> OPTIONAL. Space delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. The defined values are:
> none
> The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request. The error code will typically be login_required, interaction_required, or another code defined in Section 3.1.2.6. This can be used as a method to check for existing authentication and/or consent.
> login
> The Authorization Server **SHOULD prompt the End-User for reauthentication**. If it cannot reauthenticate the End-User, it MUST return an error, typically login_required.
> consent
> The Authorization Server SHOULD prompt the End-User for consent before returning information to the Client. If it cannot obtain consent, it MUST return an error, typically consent_required.
> select_account
> The Authorization Server SHOULD prompt the End-User to select a user account. This enables an End-User who has multiple accounts at the Authorization Server to select amongst the multiple accounts that they might have current sessions for. If it cannot obtain an account selection choice made by the End-User, it MUST return an error, typically account_selection_required.

While this works correctly, setting the prompt=login flag is the ONLY way (that I know of) to get `PreAuthenticateAsync` to fire. This is troublesome as, for example, this is one of the provided solutions for impersonation. Impersonation on the other hand normally does not require a prompt. Judging from the spec, prompt=none would be the preferred solution here but that doesn't hand over control to `PreAuthenticateAsync` and just returns a new set of tokens straight away.

Would it be possible to allow prompt=none to call the `PreAuthenticateAsync` method and, if that method does not set a valid AuthenticateResult, either return interaction_required if no user is authenticated OR return the already authenticated user?

**Comment by brockallen** [comment]
PreAuthenticateAsync is a feature of the login workflow and if the user does not need to login then PreAuthenticateAsync is not run.

If, while in the authorization endpoint, you want to force authentication (and thus PreAuthenticateAsync ) then you can implement a custom authorization request validator and just change the Prompt property on the validated authorization request object to cause the authorization pipeline to think we need to prompt. This is discussed in length in another issue asking how to do impersonation.

**Comment by hvanbakel** [comment]
While it feels like a hack, this does work. From this point on though it is no longer evident from the URI why some path is being taken.
