### ISSUE TITLE
Local login after failed external login fails

### ISSUE THREAD

**Issue by mariusandersen** [IdentityServer/IdentityServer3#3642]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have set up an IdentityServer3 where I have an external login provider for windows login.
When I click on my "quick login" button on the client it tries to login using the windows login via the provider=MiniWindowsIdp hint in the URL. This fails because I don't have access via windows login. I then log in using the local login (username and password) but when I click submit I get unexpected error message.

When I look in the log I can see that the IdP is stating "MiniWindowsIdp" when logging in but on local login it should just be "idsrv". See the log below.

Why is the IdP in the local login still saying MiniWindowsIdp?

NOTE: If I open the same IdentityServer without the provider=MiniWindowsIdp hint in the URL, it works perfectly fine to do local login.
### Relevant parts of the log file

```
w3wp.exe Information: 0 : 2017-04-19 11:27:35.602 +02:00 [Information] {
  "Category": "Authentication",
  "Name": "Local Login Success",
  "EventType": "Success",
  "Id": 1010,
  "Details": {
    ...
    "SignInMessage": {
      "ReturnUrl": "https://...&prompt&acr_values=idp%3AMiniWindowsIdp",
      "ClientId": "myclient",
      "IdP": "MiniWindowsIdp",
      "AcrValues": [],
      "Created": 636281908442997013
    },
    ...
  },
  ...
}
w3wp.exe Information: 0 : 2017-04-19 11:27:35.602 +02:00 [Information] Calling PostAuthenticateAsync on the user service
w3wp.exe Error: 0 : 2017-04-19 11:27:35.602 +02:00 [Error] IdP requested was: "MiniWindowsIdp", but the user service issued signin for IdP: "idsrv"
```

**Comment by mariusandersen** [comment]
Extra info on current versions:
IdentityServer3 version 2.6.0
IdentityServer.WindowsAuthentication version 1.1.1

I did not have this problem when using old packages:
Thinktecture.IdentityServer3 version 1.6.3
Thinktecture.IdentityServer3.WindowsAuthentication version 1.0.0

**Comment by mariusandersen** [comment]
![image](https://user-images.githubusercontent.com/3061094/26875823-d5de800e-4b83-11e7-8024-a3e31db146c5.png)
If you look at the attached image. This is after I click on a local login, after external login has failed (as expected). As you can see the context still thinks I am logging on external provider (MiniWindowsIdp) and it also has acr_calues set to the MiniWindowsIdp causing further issues if I simply hack the context.SignInMessage.IdP = "".

**Comment by brockallen** [comment]
Do your IdSvr logs help at all?
