### ISSUE TITLE
SSO / OIDC The 'Access-Control-Allow-Origin' header has a value

### ISSUE THREAD

**Issue by BenjaminWang1031** [IdentityServer/IdentityServer3#3643]
Hey,

I have 3 web sites set up to do SSO by identityserver3.
I am using oidc and I got a very weird issue:

1. Log in to site A http://www.a.com.
2. Go to site B http://www.b.com, then I'll get an error message
XMLHttpRequest cannot load https://.../.well-known/openid-configuration. The 'Access-Control-Allow-Origin' header has a value 'http://www.a.com' that is not equal to the supplied origin. Origin 'http://www.b.com' is therefore not allowed access.

but if I wait a while and refresh site B, sometimes it'll just work fine again.
I googled a lot and spent a lot of time on it but couldn't find out why.

Any thoughts?

**Comment by brockallen** [comment]
Sounds like intermittent CORS issues. For some reason the browser is not honoring or receiving the CORS response.

**Comment by BenjaminWang1031** [comment]
Anyway we can resolve this?

I've reproduced the same issue under IE/Chrome.

**Comment by brockallen** [comment]
Well, I still don't know where the real problem is. Once you sort that out and if you find that there's a bug or problem with IdentityServer that's the cause, let us know.

**Comment by BenjaminWang1031** [comment]
I don't know the root cause neither, but the only way for now maybe is to enable  cors in the webapiconfig, I made changes to IdentityServer3.Core.Configuration.Hosting.WebApiConfig file with following lines in the Configure method:

var config = new HttpConfiguration();
[WebApiConfig.txt](https://github.com/IdentityServer/IdentityServer3/files/944957/WebApiConfig.txt)


//enable cors
var cors = new EnableCorsAttribute("*", "*", "*");
config.EnableCors(cors);

And built my own version, published to our server and everything is working perfectly now, the head shows with 'Access-Control-Allow-Origin: *' which is what I expected.

Also I think we can still use customized CorsPolicyService to control the allowed origins based on this.

FYI- need to install Microsoft.AspNet.WebApi.Cors package.

Please let me know if we have a better solution. Thanks!

**Comment by BenjaminWang1031** [comment]
@brockallen The way I am handling it only works fine for a while, then I am having this issue again every day for a couple of times...

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by BenjaminWang1031** [comment]
Yes, please close this one.
