### ISSUE TITLE
Identity/Resource scope - How can client get resource claims about the user

### ISSUE THREAD

**Issue by sharppanda** [IdentityServer/IdentityServer3#3644]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question

Hi,

I have read Dominik's blog post on authentication vs permission modeling using Identity Server (https://leastprivilege.com/2016/12/16/identity-vs-permissions/). Since I am mostly using role based authorization, I am fine using IdentityServer as authentication/authorization endpoint for different client and apis.

My question is how to model Identity and Resource scopes properly? Can client know which roles are allowed for the user on specific resource? If yes, can client know only the user roles for requested resources scopes (and not all roles for all scopes).
As far as I understand the concept, if I request claims about the user via _UserInfo_ endpoint, I am receiving claims which are filtered by claimTypes listed inside requested identity scopes. That means that if client requests _roles_ scope (identity scope with _role_ claimtype), _UserInfo_ endpoint will respond with all role claims including other applications.

Let's take simple MVC example, where the MVC client communicates with API via REST.
MVC client (client) uses Cookie/OIDC Auth middleware and requests: `ResponseType = "id_token token", Scope = "openid profile api"`.
The API (resource) uses IdentityServerBearerToken Auth middleware and demands: `RequiredScopes = "api"`.
The client has UI elements which should be visible based on _api_ role. How can the roles be accessed from client, since the _UserInfo_ endpoint will only return identity scope based claims?
Should client ask the API (resource), which actions are possible? And based on the response show/hide UI elements?

Thank you for any help.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io

**Comment by sharppanda** [comment]
My appologies. Next time i'll post directly there.
link to stackoverflow: https://stackoverflow.com/questions/43582290/identity-server-identity-resource-scope-how-can-client-get-resource-claims-a
