### ISSUE TITLE
Client authentication requirement in the token endpoint doesn't exactly comply the spec

### ISSUE THREAD

**Issue by ItielBeeri** [IdentityServer/IdentityServer3#3645]
As per [section 3.2.1](https://tools.ietf.org/html/rfc6749#section-3.2.1) of OAuth2 spec,
> Confidential clients or other clients issued client credentials MUST authenticate with the authorization server as described in  Section 2.3 when making requests to the token endpoint.

But not all clients were born confidential. Public clients without secret can still make token requests, for example, in Resource Owner flow (password grant type).
However, the implementation in [TokenEndpointController](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Endpoints/Connect/TokenEndpointController.cs#L98) requires that any client will be authenticated using secret, whether or not it is confidential.
Am I missing something here? or indeed a change is needed so that only relevant clients/flows would be checked for client credentials?

**Comment by brockallen** [comment]
> Am I missing something here

https://identityserver4.readthedocs.io/en/release/reference/client.html

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Client.cs#L49

**Comment by ItielBeeri** [comment]
Thanks for the reference. So it was indeed addressed in IdentityServer4. Is there an intention to address it in IdentityServer3 too?

**Comment by brockallen** [comment]
Ah my apologies -- I misread which repo we were in... in IdSvr3 we require client secret, even if we know the client is not a confidential one. Sorry.
