### ISSUE TITLE
IdentityServer connecting to AWS Federation

### ISSUE THREAD

**Issue by guilhermecorsino** [IdentityServer/IdentityServer3#3647]
Hi everyone,

Might IdentityServer connect to AWS which uses an AD Connector  (consuming my On-Premise AD)?

I need to set up  my whole IdentityServer's enviromnent on docker, nowadays I use On-Premise AD through ADFS to connect them. I thought to create an AD Connector for connecting AWS to my AD then connect IdentityServer to AWS. It would be a great solution?
Thanks.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
