### ISSUE TITLE
How to set up a never-expiring authentication token for each of our API clients(enterprise level not user level) ?

### ISSUE THREAD

**Issue by shelbygt22** [IdentityServer/IdentityServer3#3648]
### Question / Issue
Hi all,
        I have already set up my identity server and my API with ClientCredential flow but this is working with users account and the token live shortly. What I want is to be able to generate a never-expiring authentication token for each of our API clients(enterprises level) so each of their users can use this token instead of having to have one for each of their employees.

With that said I read about refresh_token and offline_scope but in the end I still dont know how to setup the whole thing to suit my needs. Wich Flow use, scopes and how to set up my users that will be enterprises instead of enterprises users and further more how to generate a permanent token.

One more thing how to include users claims info int the generated access_token like the Email, Role, website and so on ?

Any help with exemple or anything else would be greatly apprciated !

Thanks in advance !

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
