### ISSUE TITLE
Problems allowing proxy users and non-proxy users at the same time

### ISSUE THREAD

**Issue by mariusandersen** [IdentityServer/IdentityServer3#3649]
The setup I try to accomplish is the following:
User 1 connects to https://idpserver.domain.com/IdentityServer3/
User 2 connects to https://proxy.domain.com:9000/IdentityServer3/

proxy.domain.com:9000 is pointing towards idpserver.domain.com

I know I can set the config PublicOrigin on IdentityServerOptions to "proxy.domain.com:9000" but then User 1 can no longer use the IdentityServer. Without it, User 2 can not connect.

I tried messing with the OwinEnvironmentExtensions.SetIdentityServerOrigin functionality in the Owin pipeline like this:
Owin Middleware class
```
public class HostnameMiddleware : OwinMiddleware
	{
		public HostnameMiddleware(OwinMiddleware next)
			: base(next)
		{
		}

		public override async Task Invoke(IOwinContext context)
		{
			Uri origin;
			if (context.Request.Headers.Keys.Contains("Referer"))
			{
				origin = new Uri(context.Request.Headers["Referer"]);
			}
			else
			{
				origin = new Uri("https://" + context.Request.Headers["host"]);
			}

			IdentityServer3.Core.Extensions.OwinEnvironmentExtensions.SetIdentityServerOrigin(context.Environment, origin.Scheme + "://" + origin.Authority);

			await Next.Invoke(context);
		}
	}
```
In Startup.cs Configuration():
```
app.Use(typeof(HostnameMiddleware));
```
This is messy and does not work properly with messages like "Cannot determine what application you are trying to connect to" on User 2.

I need a suggestion on how to make this work properly.

**Comment by mariusandersen** [comment]
For clarification this the implementation of the SetIdentityServerOrigin() method I am using:
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/OwinEnvironmentExtensions.cs#L565

**Comment by brockallen** [comment]
> I need a suggestion on how to make this work properly.

Usually this is solved by configuring the internal network DNS
