### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by jhougen** [IdentityServer/IdentityServer3#3651]
When you login to Identityserver the authentication cookie idsrv is stored in the browser. When the user logs out, the cookie is deleted. However, an attacker can steal the cookie and essentially use it even though the user has logged out.  

### Question
Is there anyway to detect that the user has logged out and that the idsrv cookie value (token) is no longer valid? Should we implement IAuthenticationSessionValidator to keep track of the users that are signed out? Or is this something that should belong to the application by using the id_token session_state claim?

**Comment by brockallen** [comment]
This seems to be a general question - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
