### ISSUE TITLE
Multiple application users

### ISSUE THREAD

**Issue by rwttm001** [IdentityServer/IdentityServer3#3654]
Hi,

Thanks for a product that's both technically informed and easy to pick up. I have a requirement to have database driven users and also the resources(apis) they are entitled to use. I've followed the entity framework sample to create the Identity Server tables and also the AspNet Identity sample to hook into that and now have a database containing both Identity Server and AspNet Identity tables.

My question is how should I set up users/clients/scopes in such a way that a single user can have access to one/many apis secured by Identity Server? There doesn't seem to be a relationship between users and applications in Identity Server to determine which user can access which api?

**Comment by leastprivilege** [comment]
Authorization is an application concern - not IdentityServer.

**Comment by rwttm001** [comment]
I'd like to avoid a scenario where a user registers in one app (single record in user table) but is actually able to sign in to others using the same credentials. This could happen because of a many to many record in the ClientScopes table and a client app creating a TokenClient using the same ClientId and passing in the scope when requesting a token. Maybe I need to understand Clients and Scopes better, I still don't really get how Identity Servers concept of users relates to permissions on Clients and Scopes.

In my API my data methods are protected via the Authorize header and I've wired up Identity Server in Startup.cs with the appropriate Authority and Scope.

**Comment by rwttm001** [comment]
To better describe, here's what I had in my database when I had a single client:

1 Scope - Name: Foo, Type: 1 (Resource)
1 Client - Id: 1, ClientId: Bar, Flow: 7 (Resource Owner)
1 ClientSecret - Value: *hashed secret*, Client_Id: 1
1 ClientScope: Scope: Foo, Client_Id: 1

I then added a single user to the AspNet Identity AspNetUsers table, which at this point is stand alone and has no explicitly set relationship to Identity Servers Scopes or Clients.

Using the following code I'm able to obtain a token:

```
var client = new TokenClient(
                string.Format("{0}/connect/token", AppSettings.IdentityServerUrl),
                "Bar",
                "{client-secret-guid}");

            return client.RequestResourceOwnerPasswordAsync("{username}", "{password}", "Foo").Result; 
``` 

If I then add a further:

1 Client - Id: 2, ClientId: Baz, Flow: 7 (Resource Owner)
1 ClientSecret - Value: *hashed secret*, Client_Id: 2
1 ClientScope: Scope: Foo, Client_Id: 2

In client 2 I can obtain a token for the original user as follows:

```
var client = new TokenClient(
                string.Format("{0}/connect/token", AppSettings.IdentityServerUrl),
                "Baz",
                "{client-secret-guid}");

            return client.RequestResourceOwnerPasswordAsync("{username}", "{password}", "Foo").Result;
```

Could you please talk me through an approach in setting up the Users/Clients/Scope so that I can explicitly say which user has access to which resource?

Thanks
Matt

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
