### ISSUE TITLE
IdentityServer3 & ADFS

### ISSUE THREAD

**Issue by brianwagg** [IdentityServer/IdentityServer3#3657]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is there anyone out there that has successfully implemented IdentityServer3 communicating with ADFS end to end that is willing to share some information?

I have it talking to ADFS, attempting to post back the claims after successful authentication, but I get a 405 Method Not Allowed error with the following message:
{"Message":"The requested resource does not support http method 'POST'."}

I've dug through the error logs and see various things but in looking at the WsFederationController it doesn't seem like it supports a POST to the "" route.
 
What am I missing?

Any help would be hugely appreciated!

### Relevant parts of the log file
Message='UserMessage='The requested resource does not support http method 'POST'.'', Operation=ApiControllerActionSelector.SelectAction, Status=405 (MethodNotAllowed), Exception=System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext) in c:\ballen\github\identity\IdModel\IdentityModel\source\IdentityModel.Net45\CryptoRandom.cs:line 0
   at System.Web.Http.Tracing.Tracers.HttpActionSelectorTracer.<>c__DisplayClass2.<System.Web.Http.Controllers.IHttpActionSelector.SelectAction>b__0() in c:\ballen\github\identity\IdModel\IdentityModel\source\IdentityModel.Net45\CryptoRandom.cs:line 0
   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace) in c:\ballen\github\identity\IdModel\IdentityModel\source\IdentityModel.Net45\CryptoRandom.cs:line 0

**Comment by leastprivilege** [comment]
It is used here

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L132

**Comment by brianwagg** [comment]
Yea, I saw that. I was curious if the SyncConfigurationManager is something
we need to put in our own code.
Also - I have yet to figure out how the callback actually works. Instead of
/core/adfs I wasn't using a callback and the endpoint in ADFS was just set
to hit my /identity/wsfed.

I get to ADFS, authenticate and then ADFS posts back to that endpoint,
except it can't handle a POST.
And even if it could, I'm seeing in the logs that it is planning on using a
JSON mediate formatter but ADFS is returning XML.

I've been through Scott Brady's examples, still no dice.
Another note is that I am using certs to encrypt - and I've seen other
posts about having to do something custom for that.

**Comment by brianwagg** [comment]
Also of note - I followed this article:
https://www.scottbrady91.com/Identity-Server/Identity-Server-3-using-WS-Federation

And noticed he doesn't use the Callback, and in ADFS just uses the /core endpoint.
I tried that and that's where I ran into an error decrypting the payload. 
So it may be a couple different issues or a combination of bad configuration and then no examples of how to deal with encrypted payloads?

**Comment by brianwagg** [comment]
I finally got it figured out (mostly). 
I had the endpoint in ADFS pointing back to /identity/wsfed and that apparently is wrong. I couldn't get it working with the random /identity/adfs CallbackPath either. 
But what does work (after fixing a couple other things) was having it post back to my /identity (similar to your /core in your example) and I finally got it working.

The key is - it's working without the ADFS server encrypting the claims it sends back.
I still have to re-test that piece and figure out how IDSrv is supposed to decrypt that correctly.

**Comment by brianwagg** [comment]
Correction for anyone looking at this later - 
it was: /identity/ (note the trailing slash) that worked for me as the endpoint in ADFS.
I also learned I can't use the wsfed metadata endpoint from IdSrv in ADFS. I had to manually configure otherwise it selects the wrong endpoint URL.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by brianwagg** [comment]
I haven't been able to get back to the test using the Certs with ADFS to
see if there is additional code needed or not to decrypt the payload.

Within the next 2 weeks that work should be getting done.

You can close this for now if you want and if I have further issues and
need to reach out, I can open a new one or re-open this one.

Thanks

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
