### ISSUE TITLE
Pass and add additional information to token from the client

### ISSUE THREAD

**Issue by h2chch** [IdentityServer/IdentityServer3#3658]
I want to enable the client to pass and add the passed additional data into the token. Currently I store the passed parameter (which the client pass using acr_values) into token's subject (sub)

```
public override async Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
    var subject = new Subject
	{
		User = context.UserName
	};

	if (context.SignInMessage.AcrValues != null && context.SignInMessage.AcrValues.Count() > 0)
	{
		var acrValues = context.SignInMessage.AcrValues;
		var keyValues = acrValues.Select(x => x.Split('='))
			.ToDictionary(p => p[0], p => p[1]);

		subject.Info1 = keyValues["info1"];
		subject.Info2 = keyValues["info2"];
	}
	
	var sub = JsonConvert.SerializeObject(subject);
	context.AuthenticateResult = new AuthenticateResult(sub, "fullname");
	return;
}
```

Is there any other way besides storing extra information into token's subject? Perhaps into the token's claim? I can read back the passed extra information on token's object from GetProfileDataAsync method and add them into the claims but this way is redundant because the data is already there on the subject.

~Hendra

**Comment by brockallen** [comment]
You can pass claims to the AuthenticateResult which are then passed to the user service.

**Comment by h2chch** [comment]
Hi @brockallen thanks for your quick reply. 
I have modified the code a bit to include the claims into AuthenticateResult:
```
public override async Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
        var subject = new Subject
	{
		User = context.UserName
	};

        var claims = new List<Claim>();
	if (context.SignInMessage.AcrValues != null && context.SignInMessage.AcrValues.Count() > 0)
	{
		var acrValues = context.SignInMessage.AcrValues;
		var keyValues = acrValues.Select(x => x.Split('='))
			.ToDictionary(p => p[0], p => p[1]);

		claims = new List<Claim>()
                {
                    new Claim("info1", keyValues["info1"]),
                    new Claim("info2", keyValues["info2"])
                };
	}
	
	var sub = JsonConvert.SerializeObject(subject);
	context.AuthenticateResult = new AuthenticateResult(sub, "fullname", claims);
	return;
}
```
However I am still not able to get these inserted claims back when i called user info endpoint. Is there anything that i missed? I am using Resource Owner flow to get the token.
![snapshot](https://cloud.githubusercontent.com/assets/1444973/25575595/6cc1adcc-2e8b-11e7-8aed-d122afa9d4fc.png)

Regards,
Hendra

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by h2chch** [comment]
I am still unable to get the claim back on GetProfileDataAsync() which i constructed on AuthenticateLocalAsync().

**Comment by brockallen** [comment]
Are they not on the Subject on the context param?

**Comment by h2chch** [comment]
Yes you're absolutely correct. They are contained inside Subject property. Thank you for the hint. I was able to find an [answer from stackoverflow as well](https://stackoverflow.com/questions/34107146/seeking-confirmation-that-identityserver-3-does-not-support-custom-claims-withou)
