### ISSUE TITLE
Auto redirect to external login

### ISSUE THREAD

**Issue by ahmettaha** [IdentityServer/IdentityServer3#3659]
Hello

I know that if i disable local login and just enable facebook, it will aytonredirect to facebook login without showing the login page. This is great if i enable both google and facebook, is it possible to make identity server redirect via a query prameter? So based on the query parameters i can just disolay a certain external login provider?

**Comment by brockallen** [comment]
Yes, it's described in the docs. https://identityserver.github.io/Documentation/docsv2/endpoints/authorization.html
