### ISSUE TITLE
External provider error messages on login screen / Custom LoginViewModel

### ISSUE THREAD

**Issue by IIStevowII** [IdentityServer/IdentityServer3#3660]
Hi,

I'm currently adding a external provider to the IdentityServer and the specifications want all error messages on the login view. Now i have found that for this functionality you implemented the ShowLoginPageOnErrorResult property on the PreAuthenticationContext, but this does not seem to be the case for external provider errors.

Is there a way for me to hook into the process between the user cancelling the external login and the IdentityServer showing the error page? I've tried looking at AuthenticationController.LoginExternalCallback() but I don't seem any settings/functionality to hook into before it renders the error page.

I have tried overriding IViewService.Error() method to render the Login page instead with the error message in the ErrorMessage field. That does solve my issue, but I keep hitting things when trying to create a new LoginViewModel which is needed for IViewService.Login()

- GetSignInIdFromExternalProvider is internal (I copied the code into my own project, but this feels ugly)
- Creating an AntiForgeryToken (the methods on the class are internal, again I copied the GetCookieToken() and related methods to my own project, but this feels sooooo ugly)
- Even if i do the above, I'm still left with filling the ExternalProviders and AdditionalLinks properties on the LoginViewModel, both which also use internal methods.

I understand that those internals are probably for a reason, but how does one create a LoginViewModel?
Maybe the IdentityServer could expose a ViewModelFactory which could create such view?

**Comment by joostvz** [comment]
You can handle failing login requests in the callback of the external provider middleware, see: https://github.com/IdentityServer/IdentityServer3/issues/2489#issuecomment-176143936.
