### ISSUE TITLE
Custom View

### ISSUE THREAD

**Issue by michaelbarnes** [IdentityServer/IdentityServer3#3661]
### Question 
I am trying to create custom views for the log in and other pages. However I'm running into problems when I try and submit form data back to IdentityServer. Im not sure if I am constructing the request object correctly. 

```
var params = {
  username: username,
  password: password,
  rememberMe: rememberMe,
  tokenName: model.antiForgery.value,
}

var formData = new FormData();

for (var k in params) {
  formData.append(k, params[k]);
}

var request = new Request(model.loginUrl, {
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded'
  },
  method: 'POST',
  body: formData
});
```
If I take a look at the logs I see this:
```
- No signin id passed
- AntiForgery validation failed -- returning error page
```
Could someone please guide me through the process of posting the correct data to the endpoint after the user has entered their details?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
