### ISSUE TITLE
I have configured my idsvr3 settings. And cookieOptions has been set. But however, rememberMe model property always comes as false.

### ISSUE THREAD

**Issue by heenaMahajan** [IdentityServer/IdentityServer3#3662]
I have set cookie options for "remember me" but it does not auto  filled the username and password and remember me option in centralized login page of identityserver,  if I close the browser.and Renter the url

 AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions()
                    {
                        EnablePostSignOutAutoRedirect = true,
                        RememberLastUsername=true,
                        LoginPageLinks = new List<LoginPageLink>(){
                            new LoginPageLink() {
                                 Href = "forgotpassword",
                                 Text = "Reset Your Password",
                                 Type = "forgotpassword"
                            },
                            
                       },
                        CookieOptions = new CookieOptions()
                        {

                            AllowRememberMe = true,
                            RememberMeDuration = new TimeSpan(0, 30, 0),
                            ExpireTimeSpan = TimeSpan.FromDays(30),
                            SlidingExpiration = true,
                            IsPersistent=true,
                       
                        },
                    }

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
