### ISSUE TITLE
Access Token Save in DB

### ISSUE THREAD

**Issue by shanahmed** [IdentityServer/IdentityServer3#3664]
### Question
 @scottbrady91 @leastprivilege 

Hi,
I am using thinktecture identityserver3. My question is very simple that how can i save my access token in my DB because I have a scenario in which i want to save my access token in DB. Can anyone please guide me how can i do this?
Thanks in advance.

Regards,
Shan

**Comment by brockallen** [comment]
docs: https://identityserver.github.io/Documentation/docsv2/ef/overview.html

**Comment by shanahmed** [comment]
Thanks brockallen
