### ISSUE TITLE
Multiple login endpoints in Identity server

### ISSUE THREAD

**Issue by imvigo** [IdentityServer/IdentityServer3#3666]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
Hi,

I want to create a server which supports two different types of login and thereby having separate logic for username and password verification. In a particular login scenario, only one of these two would be selected. 

Is it possible to create two different mappings such as app.Map ("/loginA") and app.Map("/loginB") in the same startup class ? Then using the authority url, a login flow would be selected (This would mean using separate identityServerFactory for these two logins and separate implementations of IViewService and IUserService) ? 

Or should I use different acr_values for two types of login and use a common implementation of IViewService and IUserService? Is there any other better way of accomplishing this ?

**Comment by brockallen** [comment]
The latter would probably be easier.

**Comment by imvigo** [comment]
Thanks for your answer. 
I was hoping that first one would make the code separated for both the logins. Also, I want to have separate UI for both logins. Apart from being a little difficult, do you see any other problem in implementing the first solution ?

**Comment by brockallen** [comment]
You could do a partial login from PreAuth in the user service and do it all yourself.

**Comment by imvigo** [comment]
But as far as I know, I think only making this change in PreAuth in UserService will not help me in getting different UI for the two types of login. Please do correct me if I am wrong.

**Comment by brockallen** [comment]
Yes, a partial login allows you to break out of the IdSvr UI workflow and do everything custom.

**Comment by imvigo** [comment]
Actually I have two different kinds of logins with absolutely no coupling between them. I will use only one of them in my client application, based on how I specify the openIdConnectAuthenticationOptions in my client application. I just want to host them together in the same app to reduce operational costs. And thereby, want to totally segregate the code written in them. So that is why I thought of using different app.Map() statements and have separate implementations of IViewService and IUserService. Do you see any problem I could have in implementing that ?

**Comment by brockallen** [comment]
I don't know -- I've never designed an instance of IdentityServer around the map idea. Technically you now have two different and distinct token services (since the URL is different for each one, and thus the issuer), so perhaps this is a problem for you.

**Comment by imvigo** [comment]
I got your point, but could you please explain the "perhaps this is a problem for you" part. Can you see any adverse practical implications this approach that might have ?

**Comment by brockallen** [comment]
Do you want one token server or two?

**Comment by imvigo** [comment]
I want two separate token server (separate issuers would be fine), but just want to host them together to reduce my operational costs.

**Comment by brockallen** [comment]
Then give it a try!
