### ISSUE TITLE
Custome error page for IdentityServer3

### ISSUE THREAD

**Issue by Yassine-Khechane** [IdentityServer/IdentityServer3#3667]
Hello, 

when somthing wrong happens withe authentication process, identityserver display a default page whith error message. it is possible to intercept the exception and display a custome error page ?

![image](https://cloud.githubusercontent.com/assets/4406602/25740211/e0ed6388-3185-11e7-8d53-8457356fb324.png)

**Comment by IIStevowII** [comment]
You can find information about this in the documentation, namely:

- https://identityserver.github.io/Documentation/docsv2/advanced/DefaultViewService.html
- https://identityserver.github.io/Documentation/docsv2/advanced/customViewService.html

In short, the easiest way is to add a folder named "templates" to your IdentityServer project and inside this folder a html file named "_error.html". This is a partial error page, in which you can use angular to access the model. For example, to show the error message you could do {{model.errorMessage}}

For an overview of available properties in the ErrorViewModel, you can look here:
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/ViewModels/ErrorViewModel.cs

For an example of how the default error partial view looks, you can look here:
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/DefaultViewService/PageAssets/error.html

**Comment by Yassine-Khechane** [comment]
I already have a modul that intercept unhandled errors and display a custome page, 
What i need is a way to know when Identity server throw an error so i can redirect to my custom error page

**Comment by IIStevowII** [comment]
The IViewService has a method called Error, which is called to display the error page. You could override this method and handle the error yourself. I think that's the only place all errors come through, so you can catch them all.

**Comment by Yassine-Khechane** [comment]
Thank you IIStevowII, it works
