### ISSUE TITLE
Client validation failed with EntityFramework ClientStore

### ISSUE THREAD

**Issue by karlpienaar** [IdentityServer/IdentityServer3#3668]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am using Entity Framework for all storage (User, Client, Scope, Operational Services etc) but my client validation consistently fails when trying a TokenClient.RequestClientCredentialsAsync().  I do store the client secret as a SHA256 hashed value.  User validation works fine.  I've set up in-memory clients and that too works fine.  In the case of in-memory, I've copied the hashed secret directly to my static GetClients() call (with no hashing in the case of a direct copy) and that also works.  I'm really at a loss here, any advice would be welcome.

### Relevant parts of the log file

```
2017-05-05 12:20:19.7155 INFO Start token request
2017-05-05 12:20:19.7340 INFO Secret id found: flash_app
2017-05-05 12:20:21.4567 INFO Secret validators could not validate secret
2017-05-05 12:20:21.4567 INFO Client validation failed.
2017-05-05 12:20:21.4567 INFO End token request
2017-05-05 12:20:21.4567 INFO Returning error: invalid_client
```

**Comment by brockallen** [comment]
Debug thru it? I don't have a better suggestion.

**Comment by karlpienaar** [comment]
Hi Brock
Thanks for the speedy reply.  I've given it a good few hours (around 12) but I've not managed to make much progress.  Would the standard logging throw a database schema mismatch error?  I have made sure I'm on the latest version according to Nuget but I'm not sure that my db schema is current.

Thanks
Karl

**Comment by brockallen** [comment]
I honestly don't know what the issue is. My suggestion was to debug theu the IdentityServer code -- perhaps at that level it would provide insight into the problem.

**Comment by karlpienaar** [comment]
Yes, that is my thinking too.  Thanks again.

**Comment by karlpienaar** [comment]
Hi Brock
Thanks for your help, I found the issue and I'm more than a little embarrassed: my ClientSecrets.Type value had a leading space...  Oh well, one lives and learns.

Regards

Karl

**Comment by brockallen** [comment]
No prob. It's always something like that :)
