### ISSUE TITLE
Can I Use IP As the identityServer url  eg:https://192.168.1.103

### ISSUE THREAD

**Issue by jiang2120031** [IdentityServer/IdentityServer3#3676]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
When I run IdenityServer3.Samples  , I change localhost to my ip ( my computer is in the workgroup not in the domain) (192.168.1.103). the error occur when I run Client example.
It seems is the certificate validation issue.
so I think  the idsrv3test.pfx  only usefull localhost .
so how can I make the idsrv3test.pfx became usefull for my Ip
------------------------------------------ code changes
 public static class Constants
    {
        //public const string BaseAddress = "https://localhost:44333/core";
        public const string BaseAddress = "https://192.168.1.103:44333/core";

-----------------------------------------
namespace SelfHost
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.Title = "IdentityServer3 SelfHost";

            Log.Logger = new LoggerConfiguration()
                .WriteTo
                .LiterateConsole(outputTemplate: "{Timestamp:HH:MM} [{Level}] ({Name:l}){NewLine} {Message}{NewLine}{Exception}")
                .CreateLogger();

            //const string url = "https://localhost:44333/core";
            const string url = "https://192.168.1.103:44333/core";
            using (WebApp.Start<Startup>(url))
            {
                Console.WriteLine("\n\nServer listening at {0}. Press enter to stop", url);
                Console.ReadLine();
            }
        }
    }
--------------------------------------------------------------------------------------
    
Client :Console Client Credentials Flow   
IdentityServer3 :SelfHost (Minimal)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
