### ISSUE TITLE
Secure Controller in IdSvr3 web host with own token

### ISSUE THREAD

**Issue by rwttm001** [IdentityServer/IdentityServer3#3677]
Hi,

Is it possible to add a custom controller (account management in my case) to my Identity Server 3 web project that is secured (effectively) by itself? Or do I need to create a standalone Web Api for User Management?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
