### ISSUE TITLE
Identityserver3 disabling admin/api

### ISSUE THREAD

**Issue by alireza267** [IdentityServer/IdentityServer3#3678]
### Question / Issue
I use identityserver3 for SSO on my applications. And i use identity manager to manage my users in URL like https://MyIdSrvDomain/admin. everything works perfect. but when i type https://MyIdSrvDomain/admin/api ,i got an authentication required panel for entering username and password! I dont know what is that! how can i disable that. my concern is about security issues .

### Here is my identitymanager configuration

```
app.Map("/admin", adminApp =>
            {
                var factory = new IdentityManagerServiceFactory();
                factory.ConfigureSimpleIdentityManagerService("AspId");
                adminApp.UseIdentityManager(new IdentityManagerOptions()
                {
                    Factory = factory,
                    SecurityConfiguration = new HostSecurityConfiguration()
                    {
                        HostAuthenticationType = "cookies",
                        AdditionalSignOutType = "oidc"
                    }
                });
            });
```

**Comment by brockallen** [comment]
Wrong project and thus repo.

**Comment by alireza267** [comment]
@brockallen  Excuse me. what do you mean by wrong project?

**Comment by brockallen** [comment]
IdentityManager is a different org/repo. This is IdentityServer.
