### ISSUE TITLE
Accessing checksession endpoint from react native client

### ISSUE THREAD

**Issue by sattaman** [IdentityServer/IdentityServer3#3679]
I am using a React Native WebView to access the checksession page, which gives me similar access to an iframe but is different. It gives me the facility to inject code into the page, which I have done this to bypass the check that the page is in an iframe and to call calculateSessionStateResult manually.

My issue is that calculateSessionStateResult is always returning 'changed', I think due to the origin I am passing in not matching the one in the cookie.

My redirects are all in the form 'com.myApp://callback'. I have tried variants around 'com.myApp://' and also the domain of id server itself but haven't managed to get anything other than 'changed' and I'm not sure how I would find out what was in the cookie.

Do you know what origin it would be expecting?

**Comment by brockallen** [comment]
For native clients you should not be using check session or oidc-client -- instead you should be using a framework for native apps. Here's a reference implementation: https://github.com/openid/AppAuth-JS
