### ISSUE TITLE
Add Custom Claims to JWT Token Data Payload

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3#3680]
I Integrate with Google Firebase using JWT access token so i generate token then validate it in Firebase side.
The Issue that this is my payload for the token:
Header:

> {
>   "typ": "JWT",
>   "alg": "RS256",
>   "x5t": "a3rMUgMFv9tPclLa6yF3zAkfquE",
>   "kid": "a3rMUgMFv9tPclLa6yF3zAkfquE"
> }

Data:

> {
>   "iss": "https://xyz.com/identity",
>   "aud": "https://xyz.com/identity/resources",
>   "exp": 1494375966,
>   "nbf": 1494372366,
>   "client_id": "42fae5e007ad",
>   "scope": [
>     "BS.Backend",
>     "email",
>     "offline_access",
>     "openid",
>     "profile",
>     "roles"
>   ],
>   "sub": "0848ccbe-f10f-4512-991e-f16268771243",
>   "auth_time": 1494372366,
>   "idp": "idsrv",
>   "preferred_username": "myusername",
>   "email": "myemail@gmail.com",
>   "given_name": "myfirstname",
>   "family_name": "mylastname",
>   "role": "NormalUser",
>   "amr": [
>     "password"
>   ]
> }
> 

But Firebase required the JWT to have uid claim which is some thing equivalent to sub here, so i want to override the jwt creation here to add some claims to the token how can i do that.

I use Resource Owner Password flow

**Comment by brockallen** [comment]
In the user service, in get profile data API, you can just add the claim, no?

**Comment by deserthero** [comment]
Yes, It works now Thanks very much

```
        public override Task GetProfileDataAsync(ProfileDataRequestContext ctx)
        {
            // Find User By Id
            if (ctx.Subject.Claims.Where(c => c.Type == "sub") != null)
            {
                var user = _userManagementService.FindByIdAsync(ctx.Subject.Claims.Where(c => c.Type == "sub").FirstOrDefault().Value);

                if (user != null)
                {
                    var issuedClaimsList = ctx.IssuedClaims.ToList();
                    issuedClaimsList.Add(new System.Security.Claims.Claim("uid", ctx.Subject.Claims.Where(c => c.Type == "sub").FirstOrDefault().Value));
                    ctx.IssuedClaims = issuedClaimsList.AsEnumerable();
                }

            }
            
            return Task.FromResult(0);

        }
```
