### ISSUE TITLE
Identity Server 3: Password Grant and Custom Grant for the same client

### ISSUE THREAD

**Issue by tcidsrv** [IdentityServer/IdentityServer3#3681]
We have a requirement of supporting password grant and custom grant for the same client. What is advisable, should I create two clients one for each required grant or create two different custom grants one for password and other for custom grant?

**Comment by ReeceWilliams7** [comment]
This is essentially what we did - registered two different clients with idsrv (albeit with hybrid flow and a custom grant). Don't think there is another way in v3, although I believe v4 supports multiple grants per client.

**Comment by leastprivilege** [comment]
We enabled that feature in v4. We currently don't have plans to back-port that (it required a bigger change under the covers).

**Comment by tcidsrv** [comment]
I have read in one of the post that mixing grants in one client can lead to security issues. Can mixing of password grant and a custom grant (which is nothing but two different identifiers for user identification) is a security risk too?

**Comment by leastprivilege** [comment]
No thats fine.

**Comment by tcidsrv** [comment]
Thank you so much for the speedy reply.
