### ISSUE TITLE
Best way to validation access token in Azure Function

### ISSUE THREAD

**Issue by RPM1984** [IdentityServer/IdentityServer3#3682]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hi,

I need to validate an access token/perform authorization in an Azure Function, that was passed along in the Authorization header by my API gateway.

Because it's a lightweight HTTP trigger (no OWIN middleware), is the best way simply to call the [Access token validation](https://identityserver.github.io/Documentation/docsv2/endpoints/accessTokenValidation.html) endpoint using a simple HTTP request and then checking the claims?

Is there any libraries/examples that i should be using instead?

TIA.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
