### ISSUE TITLE
Get Request Uri in Identityserver login page

### ISSUE THREAD

**Issue by CodePh4nt0m** [IdentityServer/IdentityServer3#3686]
I am very new to Identityserver and owin. Here is my issue. I have created an asp.net MVC application by using identityserver3 as my authentication service. I want to access the request URI inside identity server login. I have customized the login page with MVC view (by using IdentityServer3.Samples).

This is the flow. Following URL need authentication to proceed. https://www.myapp.com/customer/profile When somebody navigates to that URL it will automatically redirect to identity login page https://www.myapp.com/identity/login?signin=2207991967207c8e306a8c08b3abd3b8. After providing the correct user credentials it will redirect back to the request URL correctly, which is already handled by identityserver.

In my case, i have an another link inside the same identityserver login page, which should redirect to my own link with the request URL https://www.myapp.com/customer/profile as querystring parameter. How can I achieve this? Basically, i want to get the request URL inside login page.

**Comment by brockallen** [comment]
I'm not exactly sure what you are trying to do, but perhaps the OWIN extension APIs will help: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html
