### ISSUE TITLE
Active Directory authentication using Identityserver3

### ISSUE THREAD

**Issue by sapandeepprimecaretech** [IdentityServer/IdentityServer3#3689]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
can we do active directory authentication using identityserver3. is there any way for integration or any example you can provide me. 

We have  inhouse active directory , plus LDAP and plus some of users using ADFS  for authentication and earlier in our old application we were handling it using windows authentication enabled in IIS or implementing ADFS and consuming it. AS we have both kind of users AD users and normal users .

Please suggest any solution or  sample code. 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by CraigEaston** [comment]
These two examples should get you going:
[IDServer3 Sample: AllInOne](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/WebHost%20(Windows%20Auth%20All-in-One))

[IDServer3 Sample: WebHost](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/WebHost%20(Windows%20Auth))
