### ISSUE TITLE
I have a question about IdentityServer3  Login

### ISSUE THREAD

**Issue by YOUMINGLI** [IdentityServer/IdentityServer3#3690]
public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {

        
            if (context.UserName == "admin" && context.Password == "admin")
            {
                context.AuthenticateResult = new AuthenticateResult("/Home/Index");

               //SignIn 
              // How about the next login?

            }
            else
            {
                context.AuthenticateResult = new AuthenticateResult("something");
            }

            return Task.FromResult(0);
        }

**Comment by brockallen** [comment]
And what's the question? It looks like you're using the `AuthenticateResult` incorrectly.
