### ISSUE TITLE
GetHiddenInputTokenAsync() returns null with custom view

### ISSUE THREAD

**Issue by michaelbarnes** [IdentityServer/IdentityServer3#3691]
Hi

I have been struggling to implement my own custom views for Identity Server. The problem seems to lie with the `GetHiddenInputTokenAsync()` method. When it does 
```
var form = await context.ReadRequestFormAsync();
```

I have debugged and found it returns null for my views but does return the inputs when I use the default views.

Could someone please assist with this. I'm not sure if its because I'm using react js or i f there is a bug?

**Comment by brockallen** [comment]
These values should already be passed into your custom view service via the input models. Or is your code elsewhere?
