### ISSUE TITLE
ScopeType Resource && Identity

### ISSUE THREAD

**Issue by oreporan** [IdentityServer/IdentityServer3#3696]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Issue
We have some custom scope that is mapped to N ScopeClaims (the same way Profile is). We have come to the point where we need these claims on both the access token and the id token. 
An example of such a claim can be "role" which can be relevant for both ID and Access. 
In the current implementation I would have to create 2 different scopes, with the same ScopeClaims mapping. 
Also, before understanding this we tried to create 2 scopes in the `IScopeStore` with the same name, and give one of them `Type == ScopeType.Identity` and the other one `Type == ScopeType.Resource
` . This didn't give any errors at runtime, it just created the token but put the new Scope only on Resource (or whichever was first on the list). This is also an issue. 

This is the "Desired" result (in ScopeStore impl):

```C#
            new Scope
            {
                Name = "AccessProfile",
                Type = ScopeType.IdentityAndResource
            }
```

This should throw some kind of exception (in ScopeStore impl):
```C#
            new Scope
            {
                Name = "AccessProfile",
                Type = ScopeType.Resource
            },
            new Scope
            {
                Name = "AccessProfile",
                Type = ScopeType.Identity
            }...

```

**Comment by brockallen** [comment]
id_tokens are meant for the client. access_tokens are meant for the API(s). If each of those two different audiences need different user claims, then you need to add them in the two different scopes for the two difference contexts.
