### ISSUE TITLE
AccessTokenLifetime not work

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer3#3697]
Hello
    I set AccessTokenLifetime =604800,but when i get token,the token will timeout in 2-4 hours.
    AccessTokenLifetime can not work normally?i find more information in document ,but i don not 
   find any To solve this problem.please help me .
                                                                                                 Thanks very much
 new Client
                {
                    ClientName = Resource.IosClientName,
                    Enabled = true,
                    ClientId = HpaSystemClient.Client_BrokerIos_ShortToken.Value,
                    ClientSecrets = new List<Secret>
                    {
                        new Secret(HpaSystemClient.GetClientSecret(HpaSystemClient.Client_BrokerIos_ShortToken.Value).Sha256())
                    },

                    Flow = Flows.ResourceOwner,

                    AllowedScopes = new List<string>(Resource.SsoClientAllowedScopes) {
                        API,
                        Constants.StandardScopes.OfflineAccess },

                    AccessTokenType = AccessTokenType.Reference,
                    AccessTokenLifetime = 604800, //7days
                    AbsoluteRefreshTokenLifetime = 2592000, //30 days

                    RefreshTokenUsage = TokenUsage.OneTimeOnly,
                    RefreshTokenExpiration = TokenExpiration.Sliding
                },

**Comment by brockallen** [comment]
Can you paste your JWt in here? Also, what do the logs say when the validation fails?
