### ISSUE TITLE
Question related to keeping the IdentityServer atcive

### ISSUE THREAD

**Issue by ameykale** [IdentityServer/IdentityServer3#3700]
I am working on SSO solution and using IdentityServer 3 to provide OP/IDP.  

In my case, I will have multiple relying parties connected to the OP and if the user is logged in and active in at least one relying party, I want to keep the user active in OP/IDP as well.
To achieve this, I think at a very high level, relying party needs to send some request to OP for each activity in RP.

did some research and found out the there is something like check_session_iframe in OpenID Connect. This is primarily used by relying party to check if the session on the OP is expired. But in my cases, on every request I want RP to communicate back to Op to keep the session alive. Does IdentityServer 3 provide any endpoint so that RP can do this or do I need to use check_session_iframe and keep updating the OP session?

Any help or pointers will be helpful.

Thanks

**Comment by brockallen** [comment]
> I want to keep the user active in OP/IDP as well

This is not how the SSO protocols are designed, so you're on your own here. Why not just make a long SSO cookie at the OP?
