### ISSUE TITLE
Identity server to authenticate 2 different applications

### ISSUE THREAD

**Issue by kkfrosty** [IdentityServer/IdentityServer3#3704]
I've read some others without a clear resolution.

We're using Identity Server 3.  It's hosted with IIS.  We have a new MVC app we're building and it's configured to use UseOpenIdConnectAuthentication in the startup.Auth.cs

We use OpenIdConnectAuthenticationMotificationTypes AuthorizationCodeReceived to built where we utilize OAuth2Client RequestAuthorizationCodeAsync. to add our tokens.

Everything works.

Let's call that App1.

Our new app we're building toward integrating other company apps.  But for now, we have App2.  Our first release we'll have some functionality in App1 to interface with the backend App2 but users of that application will still login to App2.

We're going to synchronize the user databases and we've been asked to come up with a way where App2 will have a menu item added to open App1.

That's the question, from a pure authentication standpoint how would we go about doing that?

I tried adding some code to a test app simulating App2, on login, I've used Oauth2Client to make a call to RequestResourceOwnerPasswordAsync.

Then I JwtSecurityTokenHandler to build a claimsPrincipal from the accesstoken I get back from the above.

It actually works and I can call AuthenticationManager.Signin in my app2 demo and the user is authenticated.

But when clicking a link to open app1 in a new windows, it goes to the identity server login page.

A bad hack would be for app 2 to store the user name and password and pass it in an encrypted query string to a page we create in App1, take the user name and password and simulate the AuthenticationManager.Signin as I described above and I'm pretty sure it would work but really be a bad idea.

What I'd really like to do though is have users of App2 be able to authenticate their normal way and also do something to build a token or whatever is needed so when a user clicks on the App1 link they App1 opens up in a new window without them getting asked to login again.  I understand about Authorization claims etc, I just want get past authentication in either app and in those respective apps, we'll build our security claims for authorization.

Also, these applications will have different DNS domains.  App1.com and App2.com.  The idenity server will be in app1.com.

Any ideas would be GREATLY appreciated.

**Comment by CrescentFresh** [comment]
In principal having multiple applications all trust the same identity server is supported out of the box! The reason you are having trouble is this:

> I've used Oauth2Client to make a call to RequestResourceOwnerPasswordAsync

There's very little reason today to be using resource owner flow. You would only need to use it when for whatever reason a simple authorization_code flow is *not supported* in your environment. I cannot really think of a single time that would be the case. Even a custom application built for a custom device these days usually has the ability to launch a web view of some sort to interact with the identity server.

Back to your problem, when you configure a client for resource owner flow you are essentially throwing out all of the functionality of SSO that you get out of the box with identity server. Your saying "I know better about how to sign my users in than you do, idsrv3". You proceed to do all the jwt handling stuff yourself, and write your own app2-specific cookie that of course app1 *cannot  see*, as they're on different domains.

I would suggest simply having app2 login using UseOpenIdConnectAuthentication, just as app1 does. You can do this from as many applications as you like, it is ok for them all to trust the same identity server. They should each have their own client_id and can configure the middleware however they like (eg they can each use different flows, different response types, of course different redirect uris, etc). What you get out of this is that identity server will "know" when a user has already signed in and will not prompt any application (after the first that logs in) for credentials, as it stores it's own cookie during the login phase (a feature you do NOT get when using resource_owner flow).

**Comment by kkfrosty** [comment]
To be clear, App2 has is a webform authentication which will stay in place.  ResourceOwner works in another scenario so for the login of App2, I was trying to let it handle it's authentication and use the same UserName and Password to authenticate to our identity server, get it's identity, tokens etc. 

 I think the problem has to do is with App2 launching App1 into a new window.

We utilize an authentication cookie utilizing our flavor of using resourceowner with a user name and password.

```
var _tokenClient = new OAuth2Client(
                            new Uri(string.Format("{0}/connect/token", _identityCore)),
                           "ClientId",
                           "1234"
                           );

            var _response = await _tokenClient.RequestResourceOwnerPasswordAsync(userName, password, "openid email profile customAuthentication offline_access");


            if (!string.IsNullOrEmpty(_response.AccessToken))
            {
 BearerTokenMessageInspector _inspector = new BearerTokenMessageInspector();

                TokenValidationParameters _validationParameters = _inspector.CreateTokenValidationParameters();

                SecurityToken _securityToken = null;

                JwtSecurityTokenHandler _tokenHandler = new JwtSecurityTokenHandler();

                // Next call will throw the exception if the token or configuration is not valid                
                var _claimsPrincipal = _tokenHandler.ValidateToken(_response.AccessToken, _validationParameters, out _securityToken);

                var _ctx = HttpContext.GetOwinContext();
                var _authenticationManager = _ctx.Authentication;
                _authenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
                
                ClaimsIdentity _identity = new ClaimsIdentity(DefaultAuthenticationTypes.ApplicationCookie, ClaimTypes.NameIdentifier, ClaimTypes.Role);
                _identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, _claimsPrincipal.Claims.Where(c => c.Type == ClaimTypes.Sid).First().Value, "http://www.w3.org/2001/XMLSchema#string"));
                _identity.AddClaim(new Claim(ClaimTypes.Name, userName, "http://www.w3.org/2001/XMLSchema#string"));
                _identity.AddClaim(new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider", "Custom Identity", "http://www.w3.org/2001/XMLSchema#string"));
                
                var _claims = new List<Claim>(from c in _claimsPrincipal.Claims
                                              where c.Type != "scope" &&
                                                    c.Type != "client_id" &&
                                                    c.Type != "iss" &&
                                                    c.Type != "aud" &&
                                                    c.Type != "nbf" &&
                                                    c.Type != "exp" &&
                                                    c.Type != "iat" &&
                                                    c.Type != "nonce" &&
                                                    c.Type != "c_hash" &&
                                                    c.Type != "at_hash"
                                              select c);
                                
                _identity.AddClaims(_claims);

                _identity.AddClaim(new Claim("access_token", _response.AccessToken));
                _identity.AddClaim(new Claim("expires_at", DateTime.Now.AddSeconds(_response.ExpiresIn).ToLocalTime().ToString()));
                _identity.AddClaim(new Claim("refresh_token", _response.RefreshToken));

                _identity.AddClaim(new Claim("id_token", _response.AccessToken));
                
                _authenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = false }, _identity);
```
The code above works fine and gets the user logged from what I can tell just like if they go to a login page and type in Username and password.  The identity along with claims look to be identical and works in App1.

So I was thinking maybe in App 2, again we have to allow them to authenticate the way they do for that app, then with the same user name and password authenticate to our identity server, get a token.  Create a new page in App1 to receive that token and use it to verify identity and then auto login it on.

With the resource owner above, I know if I pass the user name and password over to a page in App1, run the code above, they will get logged on and work exactly like as if they would have logged on at the Identity server logon page but something I do not want to do.

Either way I can try anything with App1 but can't change App2's authentication from what it currently uses to authenticate.

**Comment by kkfrosty** [comment]
Cresent,

To summarize, what I was trying to do is allow App2 to take a user name and password that's entered at it's login screen and authenticate to the new Identity Server secondary after it authenticates to it's existing way.

If there is another way to do this with UserName and password other than ResourceOwner, I can set that up.  Or if's being able to take the token received from the ResourceOwnerPassword call and pass it to a page in App1 when a new window is opened, that would be fine as well.

**Comment by CrescentFresh** [comment]
> App2 has is a webform authentication which will stay in place

if App2 can't change to another code flow then you're dead in the water as far as out-of-the-box support goes.

> what I was trying to do is allow App2 to take a user name and password that's entered at it's login screen and authenticate to the new Identity Server secondary after it authenticates to it's existing way

And you succeeded in doing that and is what resource_owner flow is expressly good at. Just realize it comes at the cost of the benefits of using literally any other code flow, which by their very nature - that is, logging in *at the identity server itself* - would have given you what you want.

> I know if I pass the user name and password over to a page in App1

And that's *probably* where Dominic and Brock will stop reading haha. They can't help you with customizations that involve passing passwords in query string parameters,, but as far as my knowledge goes... sure that would work. But it's a giant hack of course, ripe for vulnerability. Intranet apps however can do stuff like that and often do.

**Comment by CrescentFresh** [comment]
To re-iterate (please read my original response again, it appears you didn't quite get it), if you use a code flow that has the user logging in *at the identity server itself*, you will get the desired behavior of allowing multiple applications to use the same identity server without requiring a log in for each.

What you store in your app-specific cookies has zero consequence to getting this to work: it all boils down to getting identity server to store its cookie at login time, and the only time it writes out said cookie is when you DO NOT USE resource_owner flow (or client_credentials flow, for that matter).

**Comment by kkfrosty** [comment]
I think with what I'm having to work with you've confirmed Resource Owner is my only option correct?  As far as I'm concerned passing a username and password out of the question.

Past that, is there a way to get a get a token or such from Identity Server that can be passed encrypted to a new page or something in App 1 that will verify the identity?

I'm thinking of it along the lines of an app contacts identity, get's it's tokens and needs to make a call to say a WCF server.  The WCF service uses a bearer token or such to confirm the identity.

**Comment by CrescentFresh** [comment]
Sure, if n applications all trust the same identity server then a token for one is "valid" for all.

However, think about what you're doing here:

- an access token is meant for authorizing access to a *resource server*, not necessarily applications
- when using the same access token in multiple applications you can't tell which application the token actually came from

Re point1: a resource server (think an API of some sort, a WCF service if you will) will trust a token from any application that trusts the same identity server. In other words, a token given to it from any application is validated through the back channel of the resource server -> identity server. If this validation fails, that means the token was not retrieved from the identity server and cannot be trusted. This is the mechanism built-in to https://www.nuget.org/packages/IdentityServer3.AccessTokenValidation

Re point2: passing a token around from one application to another, you must build this token verification process yourself in each application's startup as there is no package (that I'm aware of) that does this to date. It wouldn't be difficult, you can rely heavily on the classes provided by in the [IdentityModel package](https://www.nuget.org/packages/IdentityModel/) (see source https://github.com/IdentityModel/IdentityModel/tree/master/source/IdentityModel.Shared/Client)

**Comment by CrescentFresh** [comment]
Come to think of it, you can probably get away with configuring a custom IOAuthBearerAuthenticationProvider that knows about where you are passing the token from application to application, for example the query string.

Then, wrap all that up in conditional logic in application startup that configures middleware to either UseOpenIdConnectAuthentication if the token parameter is not passed in (and thus prompt for credentials) or use AccessTokenValidation otherwise.

You could re-frame this question and post it on the issue tracker at https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues instead of here.

**Comment by kkfrosty** [comment]
Yesterday I found this.
https://stackoverflow.com/questions/21925367/passing-and-verifying-the-owin-bearer-token-in-query-string-in-webapi

I haven't been able to get UseIdentityServerBearerTokenAuthentication configured in App 1.

So just to see if getting the bearer token from App2 to App1 I focused on trying to pass it in a query string.  In IE, that failed as I found out IE truncates the URL.  In Chrome, I believe I have it working.

The path is, App2 does it's authentication, takes username and password with the code I posted above and authenticates and gets a token.  I then take that token and pass it to a web page in app one for now that extracts the token from the query string.  using the same code as above as well, it verifies the token and builds an Identity and logs the user in.

Looks like it works but now I'm concerned about having the token in a query string and the security issues with that.  But at least some progress was made.  I'm definitely curious about the UseIdentityServerBearerTokenAuthentication option and if we can configure that in App1 to handle a bearer token if passed in a query string or auth header or such.

**Comment by CrescentFresh** [comment]
>  using the same code as above as well, it verifies the token

Specifically, which code are you referring to here?

**Comment by kkfrosty** [comment]
The only code I posted in this thread.  var _tokenClient = new OAuth2Client(

Again, App2 does it's authentication and I created a Client and scope in Identity for App2, it gets a token.  I then take and pass that token in a query string to a new page in app one.  It takes the token using the code I posted here and logs the user on in the new window.

Now I'm curious as to instead of the new page, I can use something like UseIdentityServerBearerTokenAuthentication
in App one to look for the token in the string or maybe a header and process the code above.  Problem is I'm not sure what assembly reference I need to add to be able to use app.UseIdentityServerBearerTokenAuthentication in my startup file in App1.

Thanks

**Comment by CrescentFresh** [comment]
> I then take and pass that token in a query string to a new page in app one

Got it. Token is passed from App 2 -> App 1, using the query string.

> It takes the token using the code I posted here and logs the user on in the new window

Are you referring to this?

    _tokenHandler.ValidateToken(_response.AccessToken, _validationParameters, out _securityToken);

**Comment by kkfrosty** [comment]
Yes, that builds the claim principal.  To help you piece this together, several years ago I created a BearerTokenMessageInspector class. (Think I got most of the code from other places, can't remember where.)

It creates the TokenValidationParameters passed into the ValidateToken class you are looking at.

I wrote this over two years ago but forgot about most of it.
https://kkfrost.wordpress.com/2015/02/23/identity-server-v3-setup/

Here is the CreateTokenValidationParameters code.

```
 // Requires Nuget-package System.IdentityModel.Tokens.Jwt
        public TokenValidationParameters CreateTokenValidationParameters()
        {
            //Can be retrieved dynamically x5c from /core/.well-known/jwks
            HttpClient _client = new HttpClient();
            // Get Json Web Key from Identity Server
            string _jwks = _client.GetStringAsync(string.Format("{0}/core/.well-known/jwks", _identityServerUrl)).Result;

            // Parse as Json Object so it can be read
            JObject _jObject = JObject.Parse(_jwks);

            // The return value is a keys array with one element
            var _x5cArray = _jObject["keys"][0]["x5c"];

            // For some reason, the xc5 is stored as an array so the first element must be used to get the xc5 value 
            // from the certificate
            string _x5c = (string)_x5cArray[0];

            var rawData = Encoding.UTF8.GetBytes(_x5c);
            var x509Certificate2 = new X509Certificate2(rawData);
            var x509SecurityToken = new X509SecurityToken(x509Certificate2);
            List<string> _validAudiences = new List<string>();

            _validAudiences.Add(string.Format("{0}/resources", _identityServerUrl));

             var _audiences = ConfigurationManager.AppSettings["IdentityServerAudiences"].Split(new Char[] { ',' });

            foreach (var audience in _audiences)
            {
                _validAudiences.Add(audience);
            }

            var parameters = new TokenValidationParameters
            {
                ValidAudiences = _validAudiences,
                //ValidAudience = string.Format("{0}/resources", _identityServerUrl),
                ValidIssuer = _identityServerUrl,
                IssuerSigningToken = x509SecurityToken
            };

            return parameters;
        }
```
Again I did this all 2 years ago when we were originally going to utilize WCF services.  But things changed and we migrated those to webapi's in our current app.  But anyway, I figured if nothing else the same concepts could be applied and at least I have something working.

But again, not sure about passing an access token in a query string.  (Actually we can't with IE because of truncation.)

**Comment by CrescentFresh** [comment]
That code is integral to validating the token. It essentially does what the access token validation package I mentioned does, it would have been helpful that you mentioned it earlier!

**Comment by kkfrosty** [comment]
I apologize.  I wear so many hats and barely get to spend any time in this I had forgotten I actually had to researched and put that code together until yesterday.

Anyway, when I started this, I wasn't thinking about sending the access token over, it's just kind of went that direction.

Now to try and get away from this custom page I implemented in the startup of App1
```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = _identityCoreUrl,
                    RequiredScopes = new[] { "openid offline_access" },
                    TokenProvider = new OAuthBearerAuthenticationProvider
                    {
                        OnRequestToken = ctx =>
                        {
                            if (String.IsNullOrWhiteSpace(ctx.Token) && ctx.Request.QueryString.HasValue)
                            {
                                NameValueCollection parsedQuery = HttpUtility.ParseQueryString(ctx.Request.QueryString.Value);
                                ctx.Token = parsedQuery["access_token"];
                            }

                            return Task.FromResult(0);
                        }
                    }
                });
```
 the OnRequestToken is running, it gets the token and assigns it to ctx.Token properly.

However, I just get an immediate 403.  Which is odd because if if it failed I'd expect it to redirect to the login page or have some ability to handle it and redirect.

Now I'm trying to figure out how to configure this properly.  Again I have this on App1, I have Authority pointing to the Core directory of our Identity server.

Once I figure that out, I'm curious as to how from App2 I can pass the token in a way so it shows up at app1 in the ctx.Token field and thus not have to use a query string.

Should I post this in the other area you suggested?

**Comment by CrescentFresh** [comment]
> I have Authority pointing to the Core directory of our Identity server.

Make sure it has "/core/" at the end already, the middleware doesn't add that in. Other than that try enabling owin middleware logging, for example https://www.nuget.org/packages/MB.Owin.Logging.Log4Net/ is simple to use.

> if if it failed I'd expect it to redirect to the login page

haha no. I mentioned previously to get this behavior you would use the "UseOpenIdConnectAuthentication" middleware. But you're trying to use access token validation instead. Ideally you could use both, and fallback to UseOpenIdConnectAuthentication if there is no token present in the request. But I don't actually know how to go about implementing something like that.

Anyway, I honestly think the code you wrote years ago to do the public key token validation is sufficient, you probably don't need UseIdentityServerBearerTokenAuthentication.

**Comment by kkfrosty** [comment]
Thanks.  it was /Core but it's what I use in UseOpenId in the same area.  It for some reason works without the end /.  Then next in the code I forgot to UrlDecode.

Correcting those and debugging the OnRequestToken is firing, getting the token.  I set a break point in our customer AuthorizeAttribute's OnAuthorization and the identity has been set with all the appropriate claims.

But then immediately, OnRequestToken fires again for some reason, doesn't have a token in the query string and then Identity is lost.  If UseOpenIdConnectAuthentication is not commented out, then now it redirects to the login page.

What I don't like what I have working is the new page, which I have to configure a location to allow everyone access to.  I'll make do if I have too but now curious as to why OnRequestToken is firing mulitple times from a single request.

**Comment by kkfrosty** [comment]
If I create a private _accessToken string in my startup and use this code.

```
 OnRequestToken = ctx =>
                        {
                            if (String.IsNullOrWhiteSpace(ctx.Token) && ctx.Request.QueryString.HasValue)
                            {
                                NameValueCollection parsedQuery = HttpUtility.ParseQueryString(ctx.Request.QueryString.Value);
                                _accessToken = HttpUtility.UrlDecode(parsedQuery["access_token"]);
                            }
                            
                            ctx.Token = _accessToken;

                            return Task.FromResult(0);
                        }
```
Then my authentication works.  However, break point in this code is getting hit 20+ times.  I started looking at the Uri in the request and I see calls such as /Content/Bootstrap.css, /Content/site.css and basically all css and script file paths we use.

After the first call where we get the token, the user is authenticated correctly with the correct permissions, why would these calls try to go through the token authentication again???  The code I added caches the access_token but I assume all these other calls is resulting in a call to validate the token and authenticate the user repeatedly.  Any ideas as to why?

**Comment by CrescentFresh** [comment]
3 things:

a) middleware runs for all requests
2) you can't "cache" tokens like that. The middleware runs per request, I presume you have multiple users past the first one that passes the first access token??
d) the package you're using is intended to be use by api resource servers, not "apps" that serve css/scripts/favicos/etc. You could use IAppBuilder.Map to restrict your middleware for only certain routes, or install an earlier middleware to ignore requests to your static files.

**Comment by kkfrosty** [comment]
I expect all the request to process.  What doesn't make sense is, the first one with the Token in the query string processes, the user is authenticated, Identity is setup.

This is in test now and I'm the only one connecting so my taken is the one that gets used during the session.  Definitely not leaving it this way, just trying to figure out what the issue is.

This code in the OnAuthorization shows Idenity correctly and authenticated.
```

public override  void OnAuthorization(System.Web.Mvc.AuthorizationContext filterContext)
        {
            base.OnAuthorization(filterContext);

            // Uncomment if we need to test Identity and claims
            var _ctx = HttpContext.Current.GetOwinContext();
            ClaimsIdentity _identity = (ClaimsIdentity)_ctx.Authentication.User.Identity;

        }

```
What doesn't make sense is why the user that was just authenticated is suddenly gone on the next request just to get .css files or such.  

Anyway, I added this:
```

                app.Use( async (context, next) =>
                {
                    if (context.Request.QueryString.HasValue)
                    {
                        if (string.IsNullOrWhiteSpace(context.Request.Headers.Get("Authorization")))
                        {
                            var queryString = HttpUtility.ParseQueryString(context.Request.QueryString.Value);
                            string token = HttpUtility.UrlDecode(queryString.Get("access_token"));

                            if (!string.IsNullOrWhiteSpace(token))
                            {
                                await AuthenticateToken(token);
                                // Try Authentication code you use in SmartTank here
                                //context.Request.Headers.Add("Authorization", new[] { string.Format("Bearer {0}", token) });
                            }
                        }
                    }

                    await next.Invoke();
                });

```

AuthenticateToken is a method with the code I first posted that validates the token set's up the ClaimIdentity.  I thought this resolved the problem but there is a timing issue.  Meaning sometimes it's like the AuthenticateToken hasn't validated the token and setup the user before whatever redirects the user to the login page from the OpenId provider.

But if you close the window and open it back app1 opens without a login page redirect.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by kkfrosty** [comment]
Yes, never got any of it to work
