### ISSUE TITLE
No Partial Login error

### ISSUE THREAD

**Issue by GeoMac1313** [IdentityServer/IdentityServer3#3706]
We have a successful implementation of IdentityServer3 ver 2.5.0.0 with external ADFS where the end user can either login local external Federation Server via a link .  We would like to make the selection automatic (instead of the user having to click on the url) based on email address using the examples provided in CustomHrd sample.  We are hitting an unexpected results in the HrdController.cs where the line

ClaimsIdentity user = await ctx.Environment.GetIdentityServerPartialLoginAsync();

Returns a null user

Also the code

await ctx.Environment.UpdatePartialLoginClaimsAsync(claims);
And
var resumeUrl = await ctx.Environment.GetPartialLoginRestartUrlAsync();

Both return the error "No partial login"

Do you have any suggestions?

**Comment by brockallen** [comment]
Make sure the partial login page runs under the same path in the pipeline as IdentityServer -- otherwise it won't have access to the partial login cookie.
