### ISSUE TITLE
Why by default any client can authenticate external IdP users?

### ISSUE THREAD

**Issue by dzintaras** [IdentityServer/IdentityServer3#3707]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Why is it default behavior for any client to be able to use any external IdP for user authentication? In corporate environment I would consider this a big flaw and would want to have control over which clients can authenticate for example employee users using MS Active Directory services. In fact I though this to be a bug initially and started reporting it this way with Pull Request almost done and just noticed commend that it's by design.

**Comment by brockallen** [comment]
Yes, by design. Perhaps your scenario has different requirements from others.

**Comment by dzintaras** [comment]
Would you consider making this configurable (by involving IdentityServerOptions) with default behaviour as it is. I would prepare a pull request. As in this situation we have no control over what client can authenticate what users - meaning internal & external clients can authenticate our own Azure accounts and this (besides no audit/control) causes as some other internal security related issues

**Comment by brockallen** [comment]
> As in this situation we have no control over what client can authenticate what users

Don't you control the config in your IdentityServer?

**Comment by dzintaras** [comment]
I create client1 (needs only 'local' accounts access) and client2(needs federation to Azure) - I setup both clients by these requirements(meaning client1 can authenticate 'local' and has no IdpRestrictions, client2 has 'local' accounts disabled and has IdpRestrictions of AzureAD) but client1 still can use federation to Azure and authenticate AD users as by default he's allowed to do so - but by my requirements he should be able to. For this to work in current setup I would have to create "fake" Idp entry in IdpRestrictions which doesn't sound like a nice solution

**Comment by brockallen** [comment]
Ok, yes, I see what you're saying. Do we really want a third config flag for this, though? IIRC we had this same debate 2 years ago...

**Comment by dzintaras** [comment]
Well not sure :) But the fact that there are properties to allow/deny local logins and external ones states that you acknowledge the need to have control over it. It's just by default every client can do everything and this means not much of a control - that's maybe good for public IdP (hence my initial question of why such default - could you lay out the gist the reasoning?). But I don't see it that well in business environment. Changing that would of course mean breaking things that is why I suggested additional setting - a bit awkward  but would satisfy both sides

**Comment by brockallen** [comment]
Well, the most secure option is to not allow logins from anywhere. :)

I'm not terribly motivated to make this change, so unless @leastprivilege chimes in and agrees with you I don't foresee it happening.

**Comment by dzintaras** [comment]
Well there's blacklisting and there's whitelisting options - currently everything is allowed what is not forbidden (from my point of view it's the best approach in security field). But probably https://github.com/IdentityServer/IdentityServer3/issues/1195 would imply that I should go think about some hacks made to client configs to achieve the effect?

Anyway amazing job with IdentityServer3
