### ISSUE TITLE
SubjectId is unknown when using load balancer

### ISSUE THREAD

**Issue by shahzad-0** [IdentityServer/IdentityServer3#3708]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

Hi,

I have an MVC client which is using cookie authentication. Both, the host application & mvc client, are under the same domain. When I try to authorize a user with the dns pointing directly to the server, everything works fine... but when the dns is pointing to the load balanced IP address (which currently only has the one server), the SubjectId disappears.

### Relevant parts of the log file

```
2017-05-24 14:34:15.297 +01:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \".......\",
  \"ClientName\": \".......\",
  \"RedirectUri\": \".......\",
  \"AllowedRedirectUris\": [
    \".......\"
  ],
  \"SubjectId\": \"unknown\",
  \"ResponseType\": \"id_token\",
  \"ResponseMode\": \"form_post\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid email\",
  \"State\": \"OpenIdConnect.AuthenticationProperties=.......\",
  \"Nonce\": \".......\",
  \"Raw\": {
    \"client_id\": \".......\",
    \"redirect_uri\": \".......\",
    \"response_mode\": \"form_post\",
    \"response_type\": \"id_token\",
    \"scope\": \"openid email\",
    \"state\": \"OpenIdConnect.AuthenticationProperties=.......\",
    \"nonce\": \".......\",
    \"x-client-SKU\": \"ID_NET\",
    \"x-client-ver\": \"1.0.40306.1554\"
  }
}"
2017-05-24 14:34:15.328 +01:00 [Information] User is not authenticated. Redirecting to login.
```

**Comment by shuppert** [comment]
@shahzad-0 Can you provide any details on how you solved this issue?  I'm running into the same issue sporadically.

**Comment by shahzad-0** [comment]
@shuppert It ended up being an issue with the load balancer. There is a 'Rewrite Support' option which, when disabled, seems to have done it for me. Hope that helps

**Comment by shuppert** [comment]
@shahzad-0 Thanks for the reply.  I think I'm running into a different issue.
