### ISSUE TITLE
SSO between ASPNET MVC 5 and ASPNET Core 2.0

### ISSUE THREAD

**Issue by DureSameen** [IdentityServer/IdentityServer3#3711]
I want to separate  (forgot password, 2FA) into separate auth project, and then If user A is login to ASPNET MVC  website then he can use aspnet core website without login and back and forth between these two website until he log out. How can I achieve this functionality?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
