### ISSUE TITLE
LOGOUT on IdServer3 Redirects to Federated external provider.

### ISSUE THREAD

**Issue by jothikiruthika-jltasia** [IdentityServer/IdentityServer3#3712]
I have configured OKTA as external IDP in my Idserver3. Logout request to the idserver redirects the user to okta screen. How to configure to show the idserver logged out page instead? I dont want the logout request to redirect to okta. our requirement is to show the idserver logged out page, with a link to go back to the applicaiton. Please help on how to configure this.

### Relevant parts of the log file

Chrome Log

1.Redirection to Logout endpoint , then below requests are foiund.

2.Request URL: MyIdserver/connect/endsession?post_logout_redirect_uri=https%3a%2f%2flocalhost%3a44301%2f&id_token_hint=YyJ9.XY3VDeUlRV1FzSzQ4VmNyVm15bkEiLCJzaWQiOiJjYmIxMTU1MGE0MmNjNTE1ODc2MzNjMzBmMzhlMjg2NyIsInN1YiI6IjVhYjM5MTNlLTllNDctNDEwMS05ZTczLTI4NjI5NDljZDVhNiIsImF1dGhfdGltZSI6MTQ5NTc3ODk1MSwiaWRwIjoid3NmZWQxIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiY2I2ZDRjMmZmYmQwNDQ2YjgxYmIwNmY2YWJjZjJmNGIiLCJlbWFpbCI6IkJhZHJpUHJhc2FkX1NyaW5pdmFzYW5Aamx0YXNpYS5jb20iLCJuYW1lIjoiQmFkcmlQcmFzYWRfU3Jpbml2YXNhbkBqbHRhc2lhLmNvbSIsImFtciI6WyJleHRlcm5hbCJdfQ.QkXmzJVB0p5LfufUpkFzvyMVlFBCiSSbE2BISHmgZssSpDkaBQo7cbP7951s51xiZ-YSm5IKwJyw8xSX7p5bHS9WTWlLNGs3s1azoCR0-bkSmcFPVRGZsBkQCrlesha1Hpw3fSc4hcyRqvcxeLOxVhzkzvVTpzRW4YQSBmkxjlr1l-q09tXMCExxq-4-iEMLuuJN3vVE16p83SeGpEtyHqNQ7Oklx3gcsZeeWfG1FhW7kECXngIQ04Q01x-tPFr88w67TYD3YnJZTrDAVdkmenhKESFg-QNliCmNiuSs8Rh5972-XkzGpdSdW9RJQkEYqwdNgLM2TS5NJnFbFpQcvg&x-client-SKU=ID_NET&x-client-ver=1.0.40306.1554
Request Method:GET
Status Code:302 Found

3.myIDserver/logout?id=8a996749ab308171ccc5789dbb764ca2

4.https://dev-201609.oktapreview.com/app/template_wsfed/exk9rxtr4j8XofpcX0h7/sso/wsfed/passive?wtrealm=urn%3aiam3&wa=wsignout1.0&wreply=https%3a%2f%2fMYIDSERVER%2flogout%2f%3fid%3d8a996749ab308171ccc5789dbb764ca2

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
