### ISSUE TITLE
Remember Me not persisted

### ISSUE THREAD

**Issue by kaspars-ozols** [IdentityServer/IdentityServer3#3713]
I have implemented user impersonation in Identity Server 3 using Implicit flow by following hints given in these issues:
https://github.com/IdentityServer/IdentityServer3/issues/560
https://github.com/IdentityServer/IdentityServer3/issues/1465

**In a nutshell:**
1) In client application- I am setting `acr_values` to pass necessary information about user to impersonate;
2) In client application - I am using `prompt=login` to ensure that control is given to my code and user is not auto logged in;
3) In server application - I use `PreAuthenticate` in my user service to detect impersonation request and set `AuthenticateResult` accordingly;

Everything works fine, except one thing - Remember Me option setting is lost during impersonation scenario. The problem is that cookies are cleared and then re-issued completely ignoring Remember Me option previously set. 

Cookie expiration settings are lost when `PreAuthenticate` kicks in and sets `AuthenicateResult` to anything else than `null`.

https://github.com/IdentityServer/IdentityServer3/blob/ad4fdccd1aec760ed31b38c4dae820ca0856a0b8/source/Core/Endpoints/AuthenticationController.cs#L147

As you can see, last optional parameter `rememberMe` is not even passed, resulting in defaults being used.

Would be great if cookie expiration would be kept as is or some extension point could be added to control that. I believe fix could be similar to what was done with `ShowLoginPageOnErrorResult`.

**Comment by kaspars-ozols** [comment]
Any update or comment (@brockallen, @leastprivilege)? Otherwise I am not sure if I have provided the necessary info and explained it in enough details. 

Just in case if have included too much information, here comes shorter summary of the issue.

**Problem:**
If `PreAuthenticate` sets `AuthenicateResult`, issued cookie is always issued for session (or whatever is specified as default in options).

**Possible solution**
I would suggest to add `IssuePermanentCookie` of type `bool?` to `PreAuthenticationContext` that would be later passed to `SignInAndRedirectAsync`. That way behaviour does not change and still allows to control cookie expiration from `PreAuthenticate`.

Also, I would be glad to contribute, just need the confirmation that this indeed is an issue and proposed fix would be viable option.

**Comment by brockallen** [comment]
It's lost most likely because prompt=login is used.
