### ISSUE TITLE
Why to register Resource server/ Relying party with IDP in OAuth

### ISSUE THREAD

**Issue by baleshkumar** [IdentityServer/IdentityServer3#3714]
This question is about inconsistencies between two different IDPs, IdentityServer3 and Azure Active Directory.

I have some experience in working with OAuth/OpenID connect. I used Thinktecture's IdentityServer3 in my last project.

You only need to register clients which want to request token from IDP but not Resource Server/ Relying parties. They just need to point to IDP and set trust to them through OWIN middleware.

In my current project, we wanted to have a look at Azure Active Directory (and B2C offering as well). Here Azure requires you to register Resource Servers/Relying parties with IDP (along with client apps). And code at Resource server makes sure that token is indented for it only (by checking the Aud attribute).

I understand that this will make the application more secure in the sense that there could be multiple Resource Servers and token generated from one Resource server will not work for another resource server.

But what I learnt from past experience is 'Aud' attribute is for ID token and ID token is used for client applications. And for Resource Server, the Access token is used. So, does that mean that this implementation is not as per standard?

Also, for all the resource servers we are building for the same customer. If I register all of them separately and have different Aud property for each of them, following use case fail:

Client requests to ResourceServer1 and passed the token to it (which is intended for it only). But to fulfil this request, ResrouceServer1 need to access ResourceServer2. Since ResourceServer2 would not entertain this token, it will fail. To make it work, we will have to keep one registration for all of the resource servers.

Just want to know your feedback on this implementation.

**Comment by brockallen** [comment]
We do have registration for resource servers -- that's what resource scopes are.

**Comment by baleshkumar** [comment]
Do you mean to say that to differentiate between two resource server's resource, different scopes should be created? So, if I have two resource servers, like Product1Resource and Product2Resource and I need to provide access to Read and Write, I will have to create scopes like Product1Resource_Read, Product1Resource_Write, Product2Resource_Read and Product2Resource_Write. Why I have to do that is because ResourceServer don't check 'Aud' attribute (and this attribute is not passed either in access token).

**Comment by brockallen** [comment]
Yes, that might be how you'd design it. And the API should check the scope for this. And if you have more than one scope for an API, then in each individual request you'd check if the right scope is being used.
