### ISSUE TITLE
SecurityTokenValidated never fires

### ISSUE THREAD

**Issue by Tian94** [IdentityServer/IdentityServer3#3716]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I'm trying to configure my Webforms application to use OIDC authentication with an hybrid flow, I've taken the Startup.cs from the WebFormsClient sample and implemented it. However after the initial logging in via Identity Server and redirected back to my application, my security token never gets validated/ claims populated. I do however receive the code and id_token in the form of POST Data on my page, I thought that this data should be immediately handled by the Notifications and populated but this doesn't seem to be the case.

 Notifications = new OpenIdConnectAuthenticationNotifications
                {                    
                    SecurityTokenValidated = async n =>
                    {

Should the code and id_token be POSTing to my page?
 If it isn't is there a way to configure my application to trigger the Notifications?

Thanks

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Do you have RAMMFAR enabled?

**Comment by Tian94** [comment]
Yes RAMMFAR is enabled.

**Comment by brockallen** [comment]
All set on this issue? Can we close?

**Comment by Tian94** [comment]
Yep found a work around. Cheers
