### ISSUE TITLE
revoking reference access token in implicit flow

### ISSUE THREAD

**Issue by Martin1980** [IdentityServer/IdentityServer3#3717]
So I've read over the documentation, and googled around a bit and can't seem to find a proper answer.

is there a way to revoke a reference access token for an implicit client?

the /revocation endpoint requires client credentials but for implict there are none.

Has anyone done this?

**Comment by brockallen** [comment]
Use dummy credentials. I know it's not ideal, but that's the current work around.

**Comment by Martin1980** [comment]
Thanks Brock,
By dummy credentials do you mean adding a secret of SharedSecret type to ClientSecrets store?

Little confused on the credentials part since the /revocation endpoint according to documentation only takes token and token_type_hint variables... trying to figure out where to read up now how to pass in correct string in the Authorization header.

Also, out of curiosity is there anything on the roadmap to address this issue for identity server 3?

I've seen another approach of revoking all the tokens on signout which I may also pursue... but I'd just like to clarify your response a little more.

**Comment by brockallen** [comment]
>  By dummy credentials do you mean adding a secret of SharedSecret type to ClientSecrets store?

Yep.

> Little confused on the credentials part since the /revocation endpoint according to documentation only takes token and token_type_hint variables... trying to figure out where to read up now how to pass in correct string in the Authorization header.

It's Basic HTTP. You can also pass the client_id client_secret in the POST body.

> Also, out of curiosity is there anything on the roadmap to address this issue for identity server 3?

Client credentials are optional in IdSvr4.

**Comment by james-kendall** [comment]
From what I can see in the documentation /revocation is the only endpoint that requires a client secret when using the implicit flow - is that right? I want to make sure that by allowing the browser to store and use a secret we are not opening up anything else

Are there plans to make the credential optional in Identity Server 3 or will that only be available in IdSvr4? We're not in a position to move to IdSvr4 any time soon.

Thanks

**Comment by brockallen** [comment]
> Are there plans to make the credential optional in Identity Server 3 or will that only be available in IdSvr4? We're not in a position to move to IdSvr4 any time soon.

Sorry, no plans.
