### ISSUE TITLE
Login with external providers

### ISSUE THREAD

**Issue by iderossipinncorp** [IdentityServer/IdentityServer3#3718]
Hi,
I have a Identity Server 3 instace running as authority in my web site. When I load the website inside a web view in an android app, I cannot login with external providers (such as Google or Facebook) but if I use a browser, everything is OK. Is there any solution for this?

If I could obtain an external token from google or facebook, how can I get a token from my identity server? Is there a web service to validate it and get the new one?

Thanks!

**Comment by brockallen** [comment]
Is this your problem: https://www.theregister.co.uk/2016/08/23/google_to_block_web_views_from_using_its_oauth/

**Comment by iderossipinncorp** [comment]
Yes, that is the problem. 
I trying to figured out if I get an google token, how can I get a token from my identity server sending my google token?

**Comment by brockallen** [comment]
The real solution is to use the OS browser. https://vimeo.com/205451987 -- skip the JS stuff and view the end half about native apps

If you instead have a google token, then use a custom grant validator to get a new token from IdSvr.
