### ISSUE TITLE
Using multiple external identity providers

### ISSUE THREAD

**Issue by rich-zilla** [IdentityServer/IdentityServer3#3720]
I have an identity server installation that uses a single external id provider. When i call the user info endpoint with a valid token, the identity server code calls the `GetProfileDataAsync` method, with an instance of `ProfileDataRequestContext` as an argument. The issue is that this argument doesnt contain any information about the origin of the users details (i.e. the initial identity provider). If i had a system that used multiple external id providers (Google and Twitter, for example), how would i know which identity provider to query for the users details? More generally, i suppose my question is what would an `IUserService` implementation look like if you were using multiple external ID providers?

**Comment by brockallen** [comment]
>  The issue is that this argument doesnt contain any information about the origin of the users details (i.e. the initial identity provider)

The claims in the Subject are the claims you issue into the login cookie. That's how you convery any necessary info from the login process into IdentityServer's token issuance process.
