### ISSUE TITLE
Within the IdentityServer, what method is producing the access token?

### ISSUE THREAD

**Issue by jausby** [IdentityServer/IdentityServer3#3723]
Within the IdentityServer, what method is producing the access token?

**Comment by brockallen** [comment]
It's complicated. What are you looking for or looking to do?

**Comment by jausby** [comment]
I'm trying to understand the architecture more. I wanted to capture the token before its sent out to the client.

-Joseph Ausby

**Comment by brockallen** [comment]
You need to elaborate so we can help. Asking "how does it all work" isn't enough to allow us to direct you.
