### ISSUE TITLE
Programmatically  generate SignIn

### ISSUE THREAD

**Issue by Yassine-Khechane** [IdentityServer/IdentityServer3#3724]
In my controller I have an action that displays the authentication form, and I would like to generate the external providers (Google / Facebook) urls , how can I generate the signIn param ?

...../identity/external?provider=Google&signin=

**Comment by brockallen** [comment]
it's in the view model in the view service.

**Comment by Yassine-Khechane** [comment]
I'm not using the view service to build urls, i'm doing it in my AccountController, i was wondering if it's possible to generate the Signin id in the contoller

**Comment by brockallen** [comment]
All set on this issue -- can we close?
