### ISSUE TITLE
Partial login returns null

### ISSUE THREAD

**Issue by Yassine-Khechane** [IdentityServer/IdentityServer3#3725]
For external authentication (Google/Facebook), I have to associate the client account with the local account, so I use partial authentication. The problem is that GetIdentityServerPartialLoginAsync returns null sometimes (when for example the viewModel is not valid and I re-display the page)

`
[HttpPost]
        public async Task<ActionResult> LinkAccount(AccountAssociationViewModel viewModel)
        {
            var partialLogin = await Request.GetOwinContext().Environment.GetIdentityServerPartialLoginAsync();

            if (partialLogin == null)
            {                
                ModelState.AddModelError(string.Empty, _applicationContext.GetMessage("identity.external.account.association.error"));

                return View("LinkAccount", viewModel);
            }

            var externalEmail = partialLogin.Claims.First(x => x.Type == IdentityServer3.Core.Constants.ClaimTypes.Email).Value;

            viewModel.Email = externalEmail;

            if (ModelState.IsValid)
            {  
				return View("LinkAccount");
			}
			.....
		}			`

**Comment by brockallen** [comment]
> The problem is that GetIdentityServerPartialLoginAsync returns null 

Not sure -- it would return null if the partial login cookie is removed.

**Comment by Yassine-Khechane** [comment]
yeah, exactly, the probleme was with the expired cookie.
Thank you
