### ISSUE TITLE
External provider and log off question

### ISSUE THREAD

**Issue by omerlh** [IdentityServer/IdentityServer3#3728]
Hey
We started to use IdentityServer in production with Google as our External Identity Provider. Everything is work well, but I thought on a scenario this morning and I am not sure what is the expected behavior. 

Let say that I have a lot of mobile application on my mobile phone, and I logged in to all those applications with my Google account. Now, if my phone is stolen I can just change my password or revoked all the sessions and know that I am logged out from all the application in my phone. But, if one of the application in my phone is using Identity Server with Google as the authentication server, it will not be logged off - as I need also to log off from Identity Server. 

So, assuming that my understanding is correct - and this is the expected behavior - I am wondering what we should do. I guess we should make it clear to the user that it is not a regular Google login (which we are not doing today, the user is only aware to the Google login), so it will be clear that in order log off he should log off through our application.

**Comment by brockallen** [comment]
Revoke the refresh tokens.

**Comment by omerlh** [comment]
But how? when? I couldn't find documentation about receiving updates from Google when the user sign-off, but probably I am missing something...

**Comment by brockallen** [comment]
We have an API (and I forget its name) to revoke clients grants -- it's what the clien permissions page uses. You can use the same, or write your own code to remove what you need from your refresh token store.
