### ISSUE TITLE
Measuring Response time for incoming requests at each endpoint

### ISSUE THREAD

**Issue by rohanbadlani** [IdentityServer/IdentityServer3#3729]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We would like to measure the response time for the incoming requests at each individual endpoint like token endpoint, userinfo endpoint. We can measure the time after the code flow reaches methods like AuthenticateLocalAsync() or GetProfileDataAsync(), but we would like to measure the end to end time that each individual request took on our server.

Can you please guide us on how to go about doing this?

Regards,
Rohan

**Comment by brockallen** [comment]
Only idea is to implement middleware in front.
