### ISSUE TITLE
Multiple re-directions happening while logging in

### ISSUE THREAD

**Issue by subbuanduri** [IdentityServer/IdentityServer3#3733]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
My web application and identity servers are published in **xxxxx.centralindia.cloudapp.azure.com**
when i am trying to access the application from different locations(mumbai,Malaysia,US,Singapore ) i am redirecting to login page . after hitting the login/submit identity server taking me to the provided redirect url . here i used the below code to process the token 
**var mgr = new OidcTokenManager(app_configuration.app_config.identity_config);
        mgr.processTokenCallbackAsync().then(function () {
            console.log("Successfully Obtained Token", mgr.access_token);
            // $("#message").text("Successfully Obtained Token", mgr.access_token);
            // debugger;
            window.location.replace(app_configuration.app_config.app_url);
        }, function (error) {
            //$("#message").text("Problem Getting Token : " + (error.message || error));
            console.log("Problem Getting Token : " + (error.message || error));
            if (mgr.expired) {
                mgr.redirectForToken();
            }
        });**
here i am getting the expired token. after multiple re-directions  i am getting the valid token. 
this problem i am facing from after-noon on-words . i did not face this problem in the morning session 
Please Help me to solve this problem 

Thanks in advance **** 
### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Not sure. It sounds more like an issue in the client side JS library. Consider upgrading to oidc-client: https://github.com/IdentityModel/oidc-client-js/
