### ISSUE TITLE
OIDC log out issue

### ISSUE THREAD

**Issue by BenjaminWang1031** [IdentityServer/IdentityServer3#3735]
I am getting this **intermittent** log out issue when calling UserManager.signoutRedirect() method.
It is working most of the time, but it'll fail sometimes...

**error details:**
Malformed JWT token
IDX10709: 'jwtEncodedString' is not well formed: 

Any ideas?
Please let me know if you need more details, thanks!

**Comment by brockallen** [comment]
Perhaps URL truncation issues?
