### ISSUE TITLE
Response message is written to log when debug is enabled

### ISSUE THREAD

**Issue by omerlh** [IdentityServer/IdentityServer3#3737]
Today I enabled debug log to check something in production and noticed that the full response is logged, including the access token. Is it on purpose? I think it should be turned off by default (even in debug). Or, even better, try to mask `access_token` and `identity_token` from the response. I can create a PR.

Thanks,
Omer

**Comment by leastprivilege** [comment]
In which exact logs - and log settings?

**Comment by omerlh** [comment]
This is in the http logging (now I noticed it can be disabled by setting `EnableHttpLogging` to false, missed that yesterday). The log is debug level, but I still think that such sensitive information (`access_token`) should be masked when written to log.
The relevant code is `ConfigureHttpLoggingExtension`, line 71.

**Comment by leastprivilege** [comment]
Well - if you enable network logging - that's what you get.
