### ISSUE TITLE
Pen Test IDSRV3 Failure - Client-Side injection

### ISSUE THREAD

**Issue by githubLewis** [IdentityServer/IdentityServer3#3739]
- [Y] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

I have recently rolled out IdentityServer v3 internally. As part of the deployment, the site has been penetration tested (using Burp I believe). It all looks reasonable except for one vulnerability which has come back as High. This is reported as "client-side template injection" and is basically passing in a payload via a certain parameter which is subsequently echoed in the response. This means that its possible to inject AngularJS expressions into the response (I'm being deliberately vague here)

While this issue remains, I cannot roll this out to live.

I doubt that we're the first to pen test so before diving into the code and trying to 'fix' this, has this been fixed before? Is it even an issue?

Happy to provide further detail if required?

**Comment by leastprivilege** [comment]
Hi, 

please contact us via identity@leastprivilege.com

**Comment by githubLewis** [comment]
Done, thanks.

Lewis

**Comment by alhardy** [comment]
If this is a real issue, can we have the details shared?

**Comment by solidstore** [comment]
I also have the results from a Burp scan, that I need to justify before release. Could you please provide details of the impact and severity this issues causes?

**Comment by etortec** [comment]
Anything to report yet about the investigation?
Can you confirm this is an actual issue?

**Comment by brockallen** [comment]
We released a patch today, and we recommend updating. We'll put out an announcement this week.
