### ISSUE TITLE
Could the AuthorizationCode be a JWT

### ISSUE THREAD

**Issue by hvanbakel** [IdentityServer/IdentityServer3#3742]
- [Y ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
From the [spec](http://openid.net/specs/openid-connect-core-1_0.html#CodeNotes):
> Some implementations may choose to encode state about the ID Token to be returned in the Authorization Code value. Others may use the Authorization Code value as an index into a database storing this state.

Given the above it would not be disallowed to generate some temporary JWT that can be read (and validated) at the token endpoint. This would alleviate the need for the entire AuthorizationCodeStore and make these requests fully stateless. Since it is a signed token we have integrity of the message so that should also not be a problem. 

In IdentityServer4 this is already possible because the id is obtained from the [AuthorizationCodeStore](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/ResponseHandling/AuthorizeResponseGenerator.cs#L209) but in IdentityServer3 this is not although it could easily be injected by putting the code to generate the id behide an injectable interface.

I was wondering if there was a reason for NOT doing this, technically (as far as I know) the clients should handle this as opaque data so this could be a nice optimization.

**Comment by brockallen** [comment]
Sure, it's possible (but then we'd need to maintain a list to prevent replays). I don't foresee this happening in IdSvr3.
