### ISSUE TITLE
Custom grants problem

### ISSUE THREAD

**Issue by vsirakova** [IdentityServer/IdentityServer3#3743]
### Question / Issue

I am trying to make custom grants work with IdentityServer 3, so I have a client with Flow.Custom and accepting that custom grant type, I have a custom grant validator registered, and I am making a POST to /connect/token with the custom grant type, parameters and Authorisation header, but I keep receiving this error from Identity Server:

> Start validation of custom grant token request
> Client does not have the custom grant type in the allowed list, therefore requested grant is not allowed.
>  {
>   "ClientId": "customclient",
>   "ClientName": "Custom Grant Client",
>   "GrantType": "assertion-fb",
>   "Raw": {
>     "assertion": "******",
>     "grant_type": "assertion-fb",
>     "scope": "api"
>   }
> }
> End token request
> Returning error: unsupported_grant_type

My client looks like this:

```
                new Client
                {
                    ClientName = "Custom Grant Client",
                    Enabled = true,
                    ClientId = "customclient",
                    ClientSecrets = new List<Secret>
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowAccessToAllCustomGrantTypes = true,

                    AllowedCustomGrantTypes = new List<string>
                    {
                        GrantTypes.ClientCredentials,
                        GrantTypes.Implicit,
                        GrantTypes.Password,
                        "assertion-fb"
                    },

                    Flow = Flows.Custom,

                     AllowedScopes = new List<string>
                    {
                         "api",
                        "read",
                        "write"
                    }
                },
```

So I have even set the `AllowAccessToAllCustomGrantTypes `to `true` but that doesn't make any difference.

I am doing the POST to the token endpoint with those parameters;

```
{
        method: 'POST',
        uri: 'https://idserver/connect/token',
        body: 'assertion=' + access_token + '&grant_type=assertion-fb&scope=api',
        headers: {
            'Content-type': 'application/x-www-form-urlencoded',
            'User-Agent': 'Request-Promise',
            'Authorization': 'Basic ' + btoa('customclient:secret')
}
```

Any ideas as to what the problem could be?

Thanks for reading!

**Comment by brockallen** [comment]
Hmm, not sure. Do our samples of custom grant types work for you?

**Comment by vsirakova** [comment]
I am trying to run the custom grant type sample, but I am getting this error when I call the /connect/token endpoint:

"The remote certificate is invalid according to the validation procedure."

I have installed the test certificates as the instructions say, but I also see that they shouldn't be needed in order to run the samples. So I am not sure what I am missing here..

**Comment by brockallen** [comment]
That's a trust issue with HTTPS -- not an IdentityServer issue.

**Comment by vsirakova** [comment]
Yes, I managed to get the sample running successfully. But my own code not really. I am wondering what the problem could be and why the custom client seems to be found but the allowed custom grant types are not there.
