### ISSUE TITLE
How to use Role Based? or Claims Based Authentication on individual methods

### ISSUE THREAD

**Issue by jausby** [IdentityServer/IdentityServer3#3744]
I am new to IdentityServer3 and need to know if there is some attribute or configuration I'm missing in order to use the Authorize attribute with a specific Role.

Just using the [Authorize] attribute on any method works, but if I try to use [Authorize (Roles = "TEST")], I get a 401 Unauthorized.  The user is definitely within that Role, using a separate application which uses ASP.Net Individual Authentication works.  

**How do I implement Role based Authorization or do I?**  I'm a bit confused with Role Based vs Claim Based.

[Authorize(Roles ="Test")] // works
public void SayHello()
{ ......

[Authorize(Roles ="TEST")] // doesn't work
public void SayHello()
{ ......

Here is a screenshot showing that I do get a valid access token, which can be used in other applications (i.e. advanced rest client, postman and etc.)

![image](https://user-images.githubusercontent.com/4376635/27192758-76ebf890-51ca-11e7-8351-11fd1daf0d6e.png)

Any help is great.  Thanks!

**Comment by brockallen** [comment]
https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/
