### ISSUE TITLE
OIDC log out, Request Url is too long[Intermittent issue]

### ISSUE THREAD

**Issue by BenjaminWang1031** [IdentityServer/IdentityServer3#3745]
When calling OIDC.UserManager.signoutRedirect() method, will get a 414 error sometimes: Request Url Too Long.

https://sso.xxx.com/connect/endsession?id_token_hint=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1Ni......&post_logout_redirect_uri=xxxxxx.

The URL about can be 18,441 characters long... Looks like the id_token_hint is the issue, I am not sure why it carries the 'id_token_hint'?

The normal log out URL should be:
https://xxx.com#id_token=eyJ0eXAiOiJKV1Qixxxxx....&token_type=Bearer&expires_in=36000&scope=openid%20profile%20email%20api&state=b83d4b9b876b4bdcac31dd6f6720e5b3&session_state=-EOR0R1McgDma6SdcigD0WweDmKI9-tZ2eF8E-evEKM.6c9768cdb6c56b41ee2cbede9178fdca

This happens intermittently, any ideas?

**Comment by brockallen** [comment]
Shorten the id_token by using the user info endpoint. This is the design in the OIDC spec.

**Comment by BenjaminWang1031** [comment]
I think the issue is not about id_token, it is why sometimes it carries the id_token_hint in the URL?

**Comment by jothikiruthika-jltasia** [comment]
BenjaminWang1031: As per the documentation, this is sent because there is some piece of code in your logout handler like the below that sends the id_token along with signout request. 
    ```
if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                            {
                                var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                                if (idTokenHint != null)
                                {
                                    n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                                }
                            }
```
You can remove this but that would result in a different logout page, it wouldn't have any links for you to return to the RP application after logout.

**Comment by alhardy** [comment]
Too many claims included in the `id_token`. Remove those you don't need to shorten.

In what cases do you need to pass along the hint on logout? https://identityserver.github.io/Documentation/docsv2/endpoints/endSession.html
