### ISSUE TITLE
Force Authoriz request

### ISSUE THREAD

**Issue by Yassine-Khechane** [IdentityServer/IdentityServer3#3746]
I have a scenario where some sensitive pages do not have to be accessible if the session remains idle for X minutes, in which case I redirect the client to the authentication page for it to authenticate itself. The problem is that I need the SignIn Id so that I can use Google/Facebook authententication.

**Comment by brockallen** [comment]
Clients don't know about the login page -- they only know about the authorization endpoint. Look into the max_age param.
