### ISSUE TITLE
Tokens not actually revoked, what am I missing here?

### ISSUE THREAD

**Issue by MartijnKooij** [IdentityServer/IdentityServer3#3747]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am trying to implement "completely signing out" in our .net MVC application but I am unsure what the best way to do this is.
Simply signing out on the client will basically only remove the cookies. When you would then restore the cookie from the time you were logged in, you are fully authenticated again.
I think I have to revoke the token, and that appears to work just fine (according to the logs), but if I have the cookie I can still access my pages that require authentication.
I tihnk I am missing something conceptually about the proces, but after 2 days of Googling for "the best practice" I am still unsure... How do you completely sign out and make it "impossible" to reuse previously valid authentication?

When or how is an access token validated once you have obtained it? After the initial authentication I don't see any communication to the IdS. Should this work automatically or is this something you would have to code yourself in the client application?

I have plenty more information if you need it. Since I am unsure of the direction I am unsure of what information to supply. So just ask.

####
Server startup
```
app.Map(
    "/core",
    coreApp =>
    {
        var options = new IdentityServerOptions
        {
            SigningCertificate = Certificates.LoadFromStore(),
            Factory = new IdentityServerServiceFactory()
                .UseInMemoryClients(Clients.Get())
                .UseInMemoryScopes(Scopes.Get()),
            AuthenticationOptions =
            {
                IdentityProviders = ConfigureIdentityProviders,
                EnableSignOutPrompt = false,
                EnablePostSignOutAutoRedirect = true
            }
        };

        options.Factory.UserService = new Registration<IUserService>(typeof(WebauthUserstore));
        options.Factory.TokenHandleStore = new Registration<ITokenHandleStore>(typeof(InMemoryTokenHandleStore));

        coreApp.UseIdentityServer(options);
    });
```
####
IdS Client definition

```
new Client
{
    ClientId = "MyClient",
    ClientName = "My Client",
    Enabled = true,
    Flow = Flows.Hybrid,
    AccessTokenType = AccessTokenType.Reference,
    ClientSecrets = new List<Secret>
    {
        new Secret("MyClient".Sha256())
    },
    RequireConsent = false,
    AllowedScopes = new List<string>
    {
        Constants.StandardScopes.OpenId,
        "CustomScopes"
    },
    EnableLocalLogin = false,
    IdentityProviderRestrictions = new List<string>{ "MyCustomIdP" }
}
```
####
Client application startup
```
var cookieAuthenticationOptions = new CookieAuthenticationOptions
{
    AuthenticationType = "Cookies",
    CookieHttpOnly = true
};

var oidcOptions = new OpenIdConnectAuthenticationOptions
{
    Authority = "https://myids.local/core",
    ClientId = "MyClient",
    RedirectUri = "https://myclient.local",
    ResponseType = "code id_token token",
    Scope = "openid MyClient",

    SignInAsAuthenticationType = "Cookies"
};
```
####
Client application invoking the revoke endpoint
```
var endpoint = "https://myids.local/core/connect/revocation";

var revocationClient = new TokenRevocationClient(endpoint, "MyClient", "MyClient");
var claimsIdentity = (ClaimsIdentity) Request.GetOwinContext().Authentication.User.Identity;
var accessToken = claimsIdentity.FindFirst("access_token").Value;

revocationClient.RevokeAccessTokenAsync(accessToken);
```
### Relevant parts of the log file

```
2017-06-20 09:45:05.205 +02:00 [Information] Start token revocation request
2017-06-20 09:45:05.205 +02:00 [Debug] Start client validation
2017-06-20 09:45:05.205 +02:00 [Debug] Start parsing Basic Authentication secret
2017-06-20 09:45:05.206 +02:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
2017-06-20 09:45:05.206 +02:00 [Information] Secret id found: "MyClient"
2017-06-20 09:45:05.207 +02:00 [Debug] Secret validator success: "HashedSharedSecretValidator"
2017-06-20 09:45:05.208 +02:00 [Information] Client validation success
2017-06-20 09:45:05.216 +02:00 [Information] End token revocation request

```

**Comment by brockallen** [comment]
> after 2 days of Googling for "the best practice"

There's no such thing as a best practice :)

Check the OIDC signout specs to know how it's supposed to work. One point is that single signout is a hard problem, and it's only "best effort".
