### ISSUE TITLE
Customize API repsonse

### ISSUE THREAD

**Issue by shanahmed** [IdentityServer/IdentityServer3#3748]
@scottbrady91 @leastprivilege

### Question / Issue
Is there any way to customize the response if user input invalid credentials or user marked locked or some scenarios like this? Please give any idea how can i do this?

**Comment by brockallen** [comment]
Create an error AuthenticateResult to provide an error in the UI to the user: https://identityserver.github.io/Documentation/docsv2/advanced/userService.html

IIRC, we don't allow custom error authorize responses from the UI.

**Comment by shanahmed** [comment]
Thanks for you reply brokkallen.

I am using ResourceOwner flow and my idea is that I have one new property in AuthenticateResult class and in error response i will populate that property. is this possible or no?

**Comment by boobun** [comment]
The `AuthenticateResult` class has a [constructor](https://github.com/IdentityServer/IdentityServer3/blob/9cd2b41fa8f48f7de46f00b67d780e0a0800cb40/source/Core/Models/AuthenticateResult.cs#L60) that takes in an error message. You will most likely need to provide implementation for [`AuthenticateLocalAsync`](https://github.com/IdentityServer/IdentityServer3/blob/9cd2b41fa8f48f7de46f00b67d780e0a0800cb40/source/Core/Services/IUserService.cs#L39) and do something like:

```c#
public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
    var loginResult = YourServiceClass.ValidateLoginRequest(context.UserName, context.Password);

    switch (loginResult.Status)
    {
    case OK:
        context.AuthenticateResult = new AuthenticateResult(loginResult.User.Id, context.UserName);
        break;
    default:
        context.AuthenticateResult = new AuthenticateResult(loginResult.Error);
        break;
    }

    return Task.FromResult(0);
}
```

Whatever your service method set as error in the loginResult.Error will be returned to the caller.

**Comment by AshishBoobun** [comment]
The `AuthenticateResult` class has a [constructor](https://github.com/IdentityServer/IdentityServer3/blob/9cd2b41fa8f48f7de46f00b67d780e0a0800cb40/source/Core/Models/AuthenticateResult.cs#L60) that takes in an error message. You will most likely need to provide implementation for [`AuthenticateLocalAsync`](https://github.com/IdentityServer/IdentityServer3/blob/9cd2b41fa8f48f7de46f00b67d780e0a0800cb40/source/Core/Services/IUserService.cs#L39) and do something like:

```c#
public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
{
    var loginResult = YourServiceClass.ValidateLoginRequest(context.UserName, context.Password);

    switch (loginResult.Status)
    {
    case OK:
        context.AuthenticateResult = new AuthenticateResult(loginResult.User.Id, context.UserName);
        break;
    default:
        context.AuthenticateResult = new AuthenticateResult(loginResult.Error);
        break;
    }

    return Task.FromResult(0);
}
```

Whatever your service method set as error in the loginResult.Error will be returned to the caller.
