### ISSUE TITLE
OwinContext not able to read cookies

### ISSUE THREAD

**Issue by johnwc** [IdentityServer/IdentityServer3#3750]
I have a custom user service that is overriding the following method. I am attempting to implement 2FA based on this [SO article.](https://stackoverflow.com/questions/36438190/two-factor-auth-with-identityserver3-remember-browser) The problem comes in when it tries to read the cookie with the call to AuthenticateAsync, it always returns null. I can see in the browser debug that the cookie is set and sent to the server. Any idea what is wrong?

        protected override async Task<AuthenticateResult> PostAuthenticateLocalAsync(User user, SignInMessage message)
        {
            if (base.userManager.SupportsUserTwoFactor)
            {
                if (await userManager.GetTwoFactorEnabledAsync(user.Id))
                {
                    var owinContext = new OwinContext(_owinEnvironmentService.Environment);
                    var result = await owinContext.Authentication.AuthenticateAsync(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie);
                    if (result == null) // This is always null, it's not able to find the cookie in the OwinContext
                    {
                        return new AuthenticateResult("~/2fa/Instructions", user.Id.ToString(), user.FullName);
                    }
                }
            }

            return await base.PostAuthenticateLocalAsync(user, message);
        }

**Update:** If I get the Owin context from within a controller, the result is not null.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by johnwc** [comment]
The value is coming back as null, seems to be a bug to me. It's not giving the expected result.
