### ISSUE TITLE
Custom Persistence Layer

### ISSUE THREAD

**Issue by pnally** [IdentityServer/IdentityServer3#3752]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
What methods do I need to be exploring in order to capture the Operational data.  Seems like when I ripped out the entity framework from the example, I don't get any tokens and consents in the context object that is passed back and forth.
Please help me see where those items are created so I can properly override the methods I need to override.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
I'd look at the code in the EF repo to get an idea on what's involved.
