### ISSUE TITLE
No matching state found in storage

### ISSUE THREAD

**Issue by BenjaminWang1031** [IdentityServer/IdentityServer3#3754]
When using OIDC to log out or log in, sometimes will get this error in the console.

**No matching state found in storage.**

Also when this happens, clean the cache or restart the browser wont help, only thing we can do is wait for a while and then it'll work.

Do we know what could be the root cause?
Do we know any workaround when this happens?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
