### ISSUE TITLE
Further development of IdentityServer3?

### ISSUE THREAD

**Issue by petteas** [IdentityServer/IdentityServer3#3755]
Hi,
Now that IdentityServer4 has been officially released and in a stable state I am wondering if you actively will be developing IdentityServer3 going on? I saw in [this](https://www.scottbrady91.com/Identity-Server/Getting-Started-with-IdentityServer-4) article that there is planned a version 3.0.0. Is that still valid?

**Comment by leastprivilege** [comment]
Don't expect any new features in IS3. We might do a v3 - but that will probably only be collection of PRs we got in the meantime.

I would recommend moving to IS4.

**Comment by petteas** [comment]
Thanks @leastprivilege
