### ISSUE TITLE
IdentityServer3 as IDP for AWS Cognito

### ISSUE THREAD

**Issue by lucasklaassen** [IdentityServer/IdentityServer3#3759]
### Question

Hey guys, just wondering if anyone has used AWS Cognito with IdentityServer3 as an OpenID Federated Identity for a user pool? I'm currently working on a Cognito project that may have to integrate with IdentityServer3 and was just wondering if anyone out there has gone through this successfully.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
