### ISSUE TITLE
Passing Access Token From Identity Provider to Relying Party

### ISSUE THREAD

**Issue by thomas-dean** [IdentityServer/IdentityServer3#3760]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question

We have an Identity Server 3 instance (*Server A*) configured as a client of another OpenID Connect identity provider on the network which is running Identity Server 3 (*Server B*) using hybrid flow. We also have a relying party which communicates with *Server A* using hybrid flow. We would like to allow the relying party to access an API which is a client of *Server B*, but not a client of *Server A*.

I understand that the correct solution to this problem is to simply have the API as a client of *Server A*. However, we have been asked to find a way to pass the `access_token` from *Server B* along to relying party, rather than just passing along the `access_token` which is generated by *Server A*.

Ideally, we could pass along the access token from *Server B* to the relying party when the relying party accesses *Server A*'s `/connect/token` endpoint with a valid authorization code. We would like for this to be accomplished by adding a claim to *Server A*'s access token which contains the access token from *Server B*.

How would you recommend we go about solving this problem?

Thank you for your time.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
