### ISSUE TITLE
Custom View Service with Custom User Service - IdentityServer3

### ISSUE THREAD

**Issue by easygoingalex** [IdentityServer/IdentityServer3#3761]
Hi there, (@brockallen)

I'm looking to implement a Custom View Service and a Custom User Service, however, I want to use custom fields on the login model (if using the custom field is at all possible?)

I notice that the AuthenticateLocalAsync method uses LocalAuthenticationContext, but this does not provide access to the Custom field of the login model, meaning I'm limited to only user name and password as login credentials. I need about 5 fields, none of which are username or password.

How can I achieve this level of customisation?

Kind Regards,
Alex

**Comment by brockallen** [comment]
You can send more form fields and in the custom user service you can inject the OWIN environment and read those form fields in the authenticate API.
