### ISSUE TITLE
Implementing client-side inactivity timer

### ISSUE THREAD

**Issue by IIStevowII** [IdentityServer/IdentityServer3#3762]
I am trying to implement an client-side inactivity timer, using the OIDC client, but am a bit unsure about the correct aproach. I have noticed that a Client has a lot of properties that determine token liftetime and how they refresh. I am using Jwt and implicit flow, which in my understanding is the only setup you can use the OIDC client with.

I have correctly implemented the OIDC client and retrieve the appropriate events when fired. But I am a bit unsure about which properties on the Client should be set in order to achieve correct behavior.

For example, I would like to end a session after 15 minutes of inactivity and give the user a warnings 5 minutes beforehand (so after 10 minutes of inactivity). What should the duration of my access token lifetime and identity token lifetime be? And what should the ExpireTimeSpan be of my IdentityServer cookie?

**Comment by jothikiruthika-jltasia** [comment]
I have a similar requirement. I have a lot of AJAX calls initiated on my web page. if the page is inactive for a while (if the page is inactive for the time period greater than identity token lifetime), then all the ajax calls fail. So i am also looking forward to implement this timeout prompt.

From what I understand, the Session time for the implicit client would be the identity token lifetime(set in the client setup in the idserver - 5 mins by default). Once this time period is reached, the session would time out. So you have to set the identity token life time to 15 min. Access token lifetime seeems to be independant of the identity token's lifetime. However i am not very sure about this.

I am also interested on the Idserver team's comment about ExpireTimeSpan be of the IdentityServer cookie?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
