### ISSUE TITLE
Refresh Token request on Custom Grant is returning invalid_grant

### ISSUE THREAD

**Issue by mhsimkin** [IdentityServer/IdentityServer3#3763]
### Question / Issue:
I have used a custom grant to get an access and refresh token.  When I go to make a request to refresh the token I'm getting an error of invalid_grant.  The refresh token is flagged as invalid.

Why would the token be invalid? How do I make it valid?

Any suggestions on how to resolve this issue?

Thanks

-marc

### Post Request Body:

```
grant_type=refresh_token&refresh_token=61fac6be0696797090185c143a972410&client_id=ClaimsMgr&client_secret=secret&win_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtMWkNwQjFVaFpDaGZkcmF0cGxFejdkY0tRYyJ9.eyJzdWIiOiJCTkhRXFxzcG15cyIsIm5hbWUiOiJCTkhRXFxzcG15cyIsImF1dGhtZXRob2QiOiJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvYXV0aGVudGljYXRpb25tZXRob2Qvd2luZG93cyIsImF1dGhfdGltZSI6IjIwMTctMDYtMjlUMTk6NDE6MDQuNzYzWiIsImlzcyI6InVybjp3aW5kb3dzYXV0aGVudGljYXRpb24iLCJhdWQiOiJ1cm46Q2xhaW1zQXV0aFNlcnZlciIsImV4cCI6MTQ5ODc2NTg2NCwibmJmIjoxNDk4NzY1MjY0fQ.wFm-LRJxZmglZB2jCOEM9fAPFRi5j7ihvF3P4xDmz1_VfoMKGXXqNU6F5fKycUWADz8uYtFaMZ3XLizBGFrIQ_GqY6OOYuQtUdzO4rVDCDEPb3TpLMu6rLQJgap-nsxksIuS3LJWbuQc55h3Wlp4eZyxUImoLEXH41F-akZRPpcgctW2SDaUkMdU4EqGzB6eKpd_XJCDtgsm8zjB0LJJ6drRhhm-5mkf3ILkhRgj6Ytfmo7R-EhhiaP5xTj51YvG1JvocW046wjBjPOXyPkYf-I_Jl3KVBwK_7sieGTgvvev3sxKOflunQfoRdwoNIiumUZu0Bfaeg-scx82zMVzWQ
```

### Relevant parts of the log file

```
IdentityServer3.Core.Endpoints.TokenEndpointController Start token request
IdentityServer3.Core.Validation.ClientSecretValidator Start client validation
IdentityServer3.Core.Validation.BasicAuthenticationSecretParser Start parsing Basic Authentication secret
IdentityServer3.Core.Validation.PostBodySecretParser Start parsing for secret in post body
IdentityServer3.Core.Validation.SecretParser Parser found secret: PostBodySecretParser
IdentityServer3.Core.Validation.SecretParser Secret id found: ClaimsMgr
IdentityServer3.Core.Validation.SecretValidator Secret validator success: HashedSharedSecretValidator
IdentityServer3.Core.Validation.ClientSecretValidator Client validation success
IdentityServer3.Core.Validation.TokenRequestValidator Start token request validation
IdentityServer3.Core.Validation.TokenRequestValidator Start validation of refresh token request
IdentityServer3.Core.Validation.TokenRequestValidator Refresh token is invalid
 {
  "ClientId": "ClaimsMgr",
  "ClientName": "Claims Manager",
  "GrantType": "refresh_token",
  "RefreshToken": "ae6e7c8fb725b758e08eb23e4117a20e",
  "Raw": {
    "grant_type": "refresh_token",
    "refresh_token": "ae6e7c8fb725b758e08eb23e4117a20e",
    "client_id": "ClaimsMgr",
    "client_secret": "******",
    "win_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtMWkNwQjFVaFpDaGZkcmF0cGxFejdkY0tRYyJ9.eyJzdWIiOiJCTkhRXFxzcG15cyIsI
m5hbWUiOiJCTkhRXFxzcG15cyIsImF1dGhtZXRob2QiOiJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvYXV0aGVudGljYXRpb25tZ
XRob2Qvd2luZG93cyIsImF1dGhfdGltZSI6IjIwMTctMDYtMjlUMjA6Mzk6MjguMTA2WiIsImlzcyI6InVybjp3aW5kb3dzYXV0aGVudGljYXRpb24iLCJhdWQiOiJ1cm46Q
2xhaW1zQXV0aFNlcnZlciIsImV4cCI6MTQ5ODc2OTM2OCwibmJmIjoxNDk4NzY4NzY4fQ.Tq31BLmfdab5ztG_sqNO-nMu-j_Rd_-nIJuw2eOMRzRmKam0L0E_2Awdjakc1a
ehmJl1bth_g0211IAm_DjIu02PiMhJr6RkWYXiLsu0osc1Ys31mMg41KNdyzspm3wf08f9pyg-E7Y4dp7Fd-zgCrQwT1skXGKEeeMdKzEu7p7JuRDZ5TGDJuq3v69jfci68o
bdteLWfHTg0k2zm4BCbS3cKz-fQ1hFmAyMUjT549Epm0fJx6n585kZ8byqhYOJP22a9pCSlBAdR9IWLa40uPx3u9Lj4YSPhws5na_Cs2QBNNpoHfs11EtdJvXEa9b_lcSS4l
aFqaxJsw8FAyon1g"
  }
}
IdentityServer3.Core.Endpoints.TokenEndpointController End token request
IdentityServer3.Core.Results.TokenErrorResult Returning error: invalid_grant
```

**Comment by brockallen** [comment]
Hmm, that log entry does not really explain much. Can you try to trace/correlate in the code to those log entries to try to discover where/why the code is rejecting it?

**Comment by mhsimkin** [comment]
I had started to debug it before I left the office.

I got as far as TokenRequestValidator.cs, ValidateRefreshTokenRequestAsync, line 558. the call

```
var refreshToken = await _refreshTokens.GetAsync(refreshTokenHandle);
```
That call seems to return null.  

I don't know why yet, I will dig into that tomorrow.

If you have some thoughts as to what is happening or where I should look, please let me know.

### Some more info:

My requirement is to make all this work from WinForm and WPF apps, without prompting the user to authenticate again, as they have access to a Windows PC on the domain.  Therefore, I never do an actual Authorize call.

I took the code from the IdentityServer3.WindowsAuthentication project and built a stand-alone self-hosted service to generate an access token from Active Directory credentials.

Once I get that access token back, I pass it as part of my custom grant request.

If the issue is with my approach, I'm open to changing to use the authorize flow.  I would just need some sort of example that does that without using a browser and input from the user.

-marc

**Comment by mhsimkin** [comment]
After debugging the code, it turns out the refresh token has expired.  In IdentityServer3.EntityFramework, BaseTokenStore, GetAsync near line 95.  There is a check to see if the refresh token has expired.  If so, GetAsync will return null.

This raises a question, is returning invalid grant the right error message or should it be returning some other error message that is more descriptive of the actual issue?

Thanks

-marc

**Comment by brockallen** [comment]
Well, the spec is very clear on what to return (and the error code is not incorrect). Perhaps better logging would help.
