### ISSUE TITLE
Understanding the access_token

### ISSUE THREAD

**Issue by jausby** [IdentityServer/IdentityServer3#3766]
I have a working IdentityServer (thanks Brock!), but I'm trying to understand the response I get after requesting an access_token using an application like Advanced Rest Client.  I get the following response below.  My question is, is this normal (reference token type) and is there a way to include an actual expire date, rather than expires_in: ?  Also, is there a way to include custom information in the response.  Any explanation or help would be greatly appreciated.

{
"access_token": "c8e62326707ca59047xxxxxxxxxxxxxx",
"expires_in": 600,
"token_type": "Bearer"
}

**Comment by brockallen** [comment]
The spec requires expires_in -- you can calculate the wall clock time yourself relative to your local time.

As for the token type -- that's a client setting if you get a JWT or a reference token. IIRC, JWT is the default.
