### ISSUE TITLE
Resource override without recompiling Core

### ISSUE THREAD

**Issue by shuppert** [IdentityServer/IdentityServer3#3767]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Is there an easy way to override a message from Messages.resx without recompiling the core assembly?  I don't want to localize to another language.  I'm just trying to override the NoSignInCookie message.  I'm hoping there is something similar to how the override HTML templates work but I didn't see anything in the Docs.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
We have an extensibility point for the messages.

**Comment by brockallen** [comment]
Here it is: https://identityserver.github.io/Documentation/docsv2/advanced/localization.html
