### ISSUE TITLE
Question - idserver and web application are in different time zones

### ISSUE THREAD

**Issue by jothikiruthika-jltasia** [IdentityServer/IdentityServer3#3768]
Hi I would like to understand the behaviour of the id_token and access_token expiry times a little better. When my IdServer is located in the UK and the Web server is in the US, and consider a user accessing the web application through browser from singapore, my id_token and access_tokens are valid for 60 mins as per the client configuration. Is this still valid or will there be issues since the idserver and web server are in different time zones?

**Comment by brockallen** [comment]
They all use unix time in the tokens.

**Comment by jothikiruthika-jltasia** [comment]
Thank You. 
I understand that the auth_time and exp values in the tokens are unix time values and upon converting them, I can clearly verify that the token validity wouldn't be affected by the difference in the RP server, client(browser) and Idserver timezones.
