### ISSUE TITLE
Not receiving refresh_token via Hybrid flow on initial request

### ISSUE THREAD

**Issue by perfectphase** [IdentityServer/IdentityServer3#3769]
[identityServerTrace.txt](https://github.com/IdentityServer/IdentityServer3/files/1123497/identityServerTrace.txt)

Hi I'm using IndentityServer3 (2.6.0) with a wpf client using Hybrid flow, and a just can't get identity server to give me a refresh_token.  The initial request has a request_type of 'code id_token token' and has offline_access in the scopes requested.  The code, identity token and access token are all returned in the response but I just can't see to make it give me the refresh token.

At this point I'm sure I'm missing something very obvious, and was hoping someone could have a look at the attached log and point me in the correct direction!

Thanks,

Stephen.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
