### ISSUE TITLE
Purpose of PreAuthenticateAsync context.SignInMessage.ReturnUrl 

### ISSUE THREAD

**Issue by MartinWa** [IdentityServer/IdentityServer3#3770]
### Question

I would like to know what application creates the login request to my login server. I thought I would use the URL of the application (same as the redirect_url) to determine this. I would like to use this URL to initiate a login instead of sending an acr value as I belive that the redirect_url is safer to use.

I thought this URL would be present in the context.SignInMessage.ReturnUrl parameter in the PreAuthenticateAsync method of the UserService. However this field contains the full request URL that initiated the call. What is the purpose of exposing this field in the SignInMessage and should I parse the redirect_uri parameter in the ReturnUrl or is there a better way to get the URL that I want.

**Comment by brockallen** [comment]
> I would like to know what application creates the login request to my login server.

The authorize endpoint.
