### ISSUE TITLE
Nonce Exception and RedirectUrl

### ISSUE THREAD

**Issue by tameyer1** [IdentityServer/IdentityServer3#3775]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
We have an application that utilizes idsvr3. Recently we opened the app up for beta testing and immediately the testers started getting the idx10311 requirenonce exception. We had not seen this type of issue during development and uat testing.  Finally, we think we solved the issue but I'm trying to puzzle out why it works and was hoping for an explanation.

The app is azure hosted. We added a vanity url (say www.mysite.com) as a cname for mysite.azurewebsites.net. The redirectUrl setup in idsvr3 and in the app configuration was mysite.azurewebsites.com. So the beta tester would go to www.mysite.com and after authentication be redirected to mysite.azurewebsites.net.  This is where *some* users would end up with the nonce exception.  After noticing this config issue we setup the redirectUrl to www.mysite.com and the issue appears to have cleared up.  

The question is why? Is it because the nonce is saved in a cookie tied to one domain and when the browser tries to send the nonce in a subsequent step it attempts to read the cookie from the the redirectUrl domain? The issue was very hard to recreate but once you got the exception you got it consistently. 
Thanks in advance

**Comment by brockallen** [comment]
Yes, sounds like that's the issue -- the nonce cookie in the MSFT MW is in a cookie, which is scoped to the host.

**Comment by tameyer1** [comment]
Thanks for the confirm. Hopefully this explanation will save others headaches.
