### ISSUE TITLE
Refresh Token revocation - all tokens for the associated subject are deleted instead the only one that was requested to revoke

### ISSUE THREAD

**Issue by olegbaev** [IdentityServer/IdentityServer3#3776]
In our scenario multiple clients (native mobile Xamarin applications) request JWT (short-living) and Refresh (long-living) tokens on the user login. 
Both tokens securely stored in the application.
Tokens SubjectId is uniquely associated with the authenticated user (let's say it is userId).
Long-living Refresh token is later revoked on a user logout.
The problem: revocation deletes ALL refresh tokens that are associated with a refresh token to be revoked as oppose to deleting only the given refresh token.
This effectively logs a user off on ALL mobile devices where they are logged in.
I am realising this is a very edge use case, however would expect that revoke only should delete the given token or as alternatively offer an option to cascade as oppose always deleting ALL tokens for the related SubjectId.

Identity Server 3 code:
-------------------------
File: \IdentityServer3\CoreAndHosting\source\Core\Endpoints\Connect\RevocationEndpointController.cs
// revoke refresh token only if it belongs to client doing the request
private async Task<bool> RevokeRefreshTokenAsync(string handle, Client client)
{
	var token = await _refreshTokens.GetAsync(handle);

	if (token != null)
	{
		if (token.ClientId == client.ClientId)
		{
			// ***************************
			// Issue: here we pass the subject only, so the underlying revoker RevokeAsync() will not have access to the original token that has to be deleted
			// and will futher delete all tokens associated with token.SubjectId
			// ***************************
			await _refreshTokens.RevokeAsync(token.SubjectId, token.ClientId);

			
Identity Server 4 code:
-------------------------
File: \Idsrv4\IdentityServer4-dev\src\IdentityServer4\ResponseHandling\TokenRevocationResponseGenerator.cs
 // revoke refresh token only if it belongs to client doing the request
private async Task<bool> RevokeRefreshTokenAsync(string handle, Client client)
{
	var token = await _refreshTokens.GetAsync(handle);

	if (token != null)
	{
		if (token.ClientId == client.ClientId)
		{
			// ***************************
			// Issue: here we pass the subject only, so the underlying revoker RevokeAsync() will not have access to the original token that has to be deleted
			// and will futher delete all tokens associated with token.SubjectId
			// ***************************
			await _refreshTokens.RevokeAsync(token.SubjectId, token.ClientId);
			await _tokenHandles.RevokeAsync(token.SubjectId, token.ClientId);
			await _events.RaiseTokenRevokedEventAsync(token.SubjectId, handle, Constants.TokenTypeHints.RefreshToken);
		}
		
Note that the standard https://tools.ietf.org/html/rfc7009 does not mandate revocation of other "siblings" refresh tokens for the giving SubjectId.

Can you please advise if the described behaviour and the implementation are intentional? If so, we can workaround.

**Comment by brockallen** [comment]
We will change this in IdentityServer4. I don't foresee this being changed here in IdentityServer3.
