### ISSUE TITLE
Inconsistent error message formats.

### ISSUE THREAD

**Issue by tbrettallen** [IdentityServer/IdentityServer3#3777]
- [ x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Error message formats are inconsistent on auth server. Mobile developer attempting to deserialize response reported issue to me and unsure if this is due to specification or an issue that should be fixed?

connect/token 

```
{
    "error": "unsupported_grant_type"
}
```

connect/accesstokenvalidation 

```
{
    "Message": "invalid_token"
}
```

or

```
{
    "Message": "Token is missing"
}
```

**Comment by brockallen** [comment]
Check the logs for the first one. The second two are self-explanatory, no?

**Comment by tbrettallen** [comment]
I understand the reasons for the messages, what I'm referring to is the structure of the error message

One uses "error" and the other uses "Message". The structure is inconsistent. Ideally they'd both use "error" or both use "Message".

Is this part of the OAuth2/OpenID spec, or something I can change, or something that would have to be changed on your side?

**Comment by brockallen** [comment]
Oh I see. The access token validation was our own home-grown thing. It's been replaced by introspection, which does have a spec.

**Comment by tbrettallen** [comment]
What would your suggestion be for how I should move forward with this?

I'm the lead on our implementation of identity server, and it's the clients that are asking me to make it consistent. Is this possible, or should I tell the client app developer to expect/check both possible properties?

**Comment by brockallen** [comment]
Introspection is preferred over the access token validation endpoint.

**Comment by tbrettallen** [comment]
In the documentation it specifies:

`Authorization: Basic xxxyyy`

Should xxxyyy also be the access token, or where does this come from? Client Key/Secret?

**Comment by brockallen** [comment]
Those are the client credentials.

**Comment by tbrettallen** [comment]
For the xxxyyy value

`Basic Client:Secret`
`Basic Client Secret`
`Basic base64encoded(Client:Secret)`
`Basic base64encoded(Client Secret)`
`Basic access_token`
`Bearer access_token`

Also tried adding an additional post value for the scope which the token has.

All of these are giving me 401 even though accesstokenvalidation works correctly.

Which API credentials are you referring to, or how do I need to structure it?

**Comment by tbrettallen** [comment]
Alright after digging through code I found out it's base64encoded(Client:Secret)

But it still doesn't appear to be working. Logs say something about a Scope secret?

`
18 Jul 2017 08:04:56.840 HTTP POST /connect/introspect responded 401 in 17ms
18 Jul 2017 08:04:56.840 Scope unauthorized to call introspection endpoint. aborting.
18 Jul 2017 08:04:56.840 No scope secret found
18 Jul 2017 08:04:56.840 1061: Client authentication failure / ClientAuthentication (Failure), Context: EventContext {"ActivityId":"b4ddaf16-7040-4355-83a0-1a0c14780244","TimeStamp":"2017-07-18T13:04:56.8403…, Details: ClientAuthenticationDetails {"ClientId":"unknown","ClientType":"Scope"}
18 Jul 2017 08:04:56.824 Parser found no secret
18 Jul 2017 08:04:56.824 client_id is not found in post body
18 Jul 2017 08:04:56.824 Start parsing for X.509 certificate
18 Jul 2017 08:04:56.824 No secret in post body found
18 Jul 2017 08:04:56.824 Start parsing for secret in post body
18 Jul 2017 08:04:56.824 Start parsing Basic Authentication secret
18 Jul 2017 08:04:56.824 Start scope validation
18 Jul 2017 08:04:56.824  Start introspection request
`

**Comment by brockallen** [comment]
The credentials are on the Scope config, not the client. The API is the scope.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
