### ISSUE TITLE
Task was Canceled Error when Calling Web API2 for downloading a file with Identityserver3

### ISSUE THREAD

**Issue by sapandeepprimecaretech** [IdentityServer/IdentityServer3#3778]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am using Identityserver3 and we have ASP.net Web API2 solution. i created a APi method as shown below to download a zip file . its returning a HTTpResponseMessage with headers and content information. But when i call the method , it gives me error. i checked network headers and we are passing  tokens  in every API call and able to call the API , but it didn't give me result back.  there is hardly any help on your forums , Please provide some insight. 

[HttpPost]
        [ActionName("TriggerDownload")]
        public Task<HttpResponseMessage> TriggerDownload(FileData fData)
        {
            try
            {
                HttpResponseMessage Response = new HttpResponseMessage();
                string path = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\" + fData.FolderName + "\\";
                if (Directory.Exists(path))
                {

                    DirectoryInfo dInfo = new DirectoryInfo(path);
                    using (ZipFile zip = new ZipFile())
                    {
                        /*Response.BufferOutput = true;
                        Response.ContentType = "application/zip";*/

                        string archiveName = string.Format("PBJ_{0}_{1}-{2}_{3}_{4}.zip", this.ClientCode, DateTime.Now.ToString("yyyy"), fData.Quarter.ToString(), DateTime.Now.ToString("yyyy-MM-dd-HHmmss"), fData.Cnt);
                        // Response.Headers.Add("content-disposition", "attachment; filename=" + archiveName);
                        MemoryStream ouStream = new MemoryStream();
                        zip.AddDirectory(path);
                        // zip.Save(archiveName);
                        zip.Save(ouStream);
                        ouStream.Close();
                        //Response.Flush()

                        Response = Request.CreateResponse(HttpStatusCode.OK);
                        Response.Content = new StreamContent(ouStream);
                        Response.Content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                        Response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");
                        Response.Content.Headers.ContentDisposition.FileName = archiveName;                        

                    }
                    foreach (FileInfo file in dInfo.GetFiles())
                    {
                        file.Delete();
                    }

                    dInfo.Delete();

                }

                return Task.FromResult(Response);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

### Relevant parts of the log file

Error is 

[TaskCanceledException: A task was canceled.]
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +11795431
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   System.Web.Http.Owin.&lt;SendResponseContentAsync&gt;d__20.MoveNext() +585
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +11795403
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   System.Web.Http.Owin.&lt;InvokeCore&gt;d__0.MoveNext() +1591
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +11795403
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   IdentityServer3.AccessTokenValidation.&lt;Invoke&gt;d__0.MoveNext() in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\Plumbing\ScopeRequirementMiddleware.cs:79
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +11795403
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Security.Infrastructure.&lt;Invoke&gt;d__0.MoveNext() +525
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +11795403
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   IdentityServer3.AccessTokenValidation.&lt;Invoke&gt;d__8.MoveNext() in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\IdentityServerBearerTokenValidationMiddleware.cs:112
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +11795403
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Mapping.&lt;Invoke&gt;d__0.MoveNext() +368
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +11795403
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.&lt;RunApp&gt;d__5.MoveNext() +170
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.&lt;DoFinalWork&gt;d__2.MoveNext() +166
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.Rethrow() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +81
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +30
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
