### ISSUE TITLE
Link to direct user to IdentityServer3 templated Register page with "signin" parameter

### ISSUE THREAD

**Issue by jausby** [IdentityServer/IdentityServer3#3780]
I have a working IdentityServer3 implementation and working MVC Client using Implicit Flow.  I recently added a user registration page within the IdentityServer3 project which is basically a controller action and enabled via startup.cs using a Register link on the server using the LoginPageLinks.

What I can't figure out is how to create a simple "Register" link on the MVC client, that redirects the user to the "Register" page on the Identity server and preserve/have the "signin" parameter.  Here is an example of the Login links Url (myIdSrv/identity/login?signin=d1c81b83...).  Where does the signin parameter and it's value come from and how is it generated?  When clicking the "Login" link on my MVC client,  I see the "signin" parameter with its value as I'm using a method that challenges the user back to the IdentityServer's "Login" ( ex. ctx.Authentication.Challenge(properties);  )  If I copy the signin parameter and value and manually paste it to the register url myIdSrv/register?sign=copiedvalue, it works and the client is recognized and is redirected back to the login page.

Basically, what I'm trying to accomplish is an UnRegistered user clicks a simple link, that properly redirects them to the IdentityServer3 with the proper Url format (as not having a proper signin value, returns the Client is unknown).  I'm trying to keep the MVC Client application from having any web.config configuration to the database.

I've also tried using this.Request.GetOwinContext().Environment.CreateSignInRequest(); to perhaps parse the Url.  But I keep getting either null errors or errors pointing to missing context parameter can't be null.

Has anyone experienced this?  Any insight or example would be great!  Please see my "Login" logic below.

` /// <summary>
        /// Redirects the user to the login page
        /// </summary>
        /// <param name="otac"></param>
        [HttpGet]
        [AllowAnonymous]
        public void LogIn(string otac = null)
        {
            try
            {
                var ctx = this.HttpContext.GetOwinContext();
                if (!string.IsNullOrEmpty(otac))
                {
                    ctx.Set("otac", otac);
                }
                var properties = new AuthenticationProperties
                {
                    RedirectUri = Url.Action("index", "home", null, Request.Url.Scheme)
                };
                ctx.Authentication.Challenge(properties);
            }
            catch (Exception ex)
            {

            }
        }`

**Comment by brockallen** [comment]
You can use the OWIN extensions to create a signin request message: https://identityserver.github.io/Documentation/docsv2/advanced/owin.html. Maybe this is what you're looking for?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
