### ISSUE TITLE
Hide Please wait view

### ISSUE THREAD

**Issue by fdocharles** [IdentityServer/IdentityServer3#3781]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

Is it possible to hide please wait page. If it is then how to do it ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
There was an enhancement a while ago for this -- check the releases and archives.
