### ISSUE TITLE
Question - Implicit flow - is it possible to extend the validity of the access token?

### ISSUE THREAD

**Issue by jothikiruthika-jltasia** [IdentityServer/IdentityServer3#3782]
### Question 
I am using Identityserver3 as my IDP. my RP is an MVC5 .net web application. The web application uses the idtoken to create its authentication cookie. It passes the access token to authenticate to a Web API over Rest calls.

My idtoken is valid for 5 minutes My access token is valid for 60 min Once the user authenticates himself, the auth_cookie lifetime is 20 minutes with sliding expiry.

My web application startup code as below -

 app.UseCookieAuthentication(new CookieAuthenticationOptions
        {
            AuthenticationType = "Cookies",
            CookieHttpOnly = true,
            CookieSecure = CookieSecureOption.Always,
            ExpireTimeSpan = TimeSpan.FromMinutes(sessionExpiryMinutes),
            SlidingExpiration = true
        });
  app.UseOpenIdConnectAuthentication(
            new OpenIdConnectAuthenticationOptions
            {
                Authority = authority,
                ClientId = clientId,
                ResponseType = responseType,
                SignInAsAuthenticationType = "Cookies",
                Scope = scope,
                RedirectUri = redirectUri,
                PostLogoutRedirectUri = redirectUri,
                UseTokenLifetime = false, .....
When the user remains idle for 20 minutes, the application cookie expires, user is redirected to identity server and new cookies are issues.

The issue comes up when the user keeps the session active and if the user is active on the 60th minute, the Access Token expires and the API that consumes this access token issues A 401 to my Web application. At this point the web application's cookie is still valid but its unable to communicate to the API since the access token is invalid. Is there a way to extend the access_token?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
