### ISSUE TITLE
Refresh token stops working

### ISSUE THREAD

**Issue by elector-zz** [IdentityServer/IdentityServer3#3784]
I am using Hybrid flow with an MVC application. Refresh token works fine locally but when I deploy the Identity server on a web host, after some time (can't figure out how long), the refresh token stops working and I get back the login page. 
My Identity server is based on your WebHost sample. 
Any idea what can cause such behavior? Or how can I investigate further?

**Comment by elector-zz** [comment]
Ok, so if anyone experiences this problem, I will write the solution I have found.
The setting that creates this problem is at IIS Application Pool. Idle timeout action needs to be set to Suspend rather then Terminate.

**Comment by brockallen** [comment]
https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
