### ISSUE TITLE
various errors in identity server3 tutorial 

### ISSUE THREAD

**Issue by RezaDel** [IdentityServer/IdentityServer3#3785]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am very new to identity server and tried to follow up with the [IdentityServer up and running](https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html)
and even watch the very fast explanation of [How to get IdentityServer3 up and running on your MVC client in .Net](https://www.youtube.com/watch?v=ekN3rSZeb3k)
but even now i am still getting an error when i try to navigate to /identity the error is [HTTP 404.The resource cannot be found.  ]
and using this code for client section  "  app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {

                Authority = "https://localhost:44395/identity",
                ClientId = "mvc",
                Scope= "openid profile roles",
                RedirectUri = "http://localhost:62362/",
                ResponseType = "id_token",

                SignInAsAuthenticationType = "Cookie"

            }); "
the other error that i get is on .UseInMemoryScopes(StandardScopes.All)  error" Standard Scopes does not contain definition for All"

as i am very new i am not sure if i am doing something wrong or if the things has changed since the tutorial for Identity server 3

**Comment by brockallen** [comment]
They evolved over time and not necessarily in concert with the IS code itself, so I believe you. We don't have any plans to update those, though, as IdentityServer3 is being deprecated in favor of IdentityServer4.
