### ISSUE TITLE
Render change password  partial view in Identityserver3 

### ISSUE THREAD

**Issue by jishnus** [IdentityServer/IdentityServer3#3788]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I am trying to implement a partial login (Change Password) but i am stuck on some issues.
I'd like a password reset page to if user password getting expired or change new one.
After login need to check and redirect to change password screen.

I have tried to implement the following code for redirecting view.

  if (userDetails.IsPasswordSingleUse)
   {
                     context.AuthenticateResult = new AuthenticateResult("/identity/ChangePassword", context.UserName, context.UserName);
                    return Task.FromResult(0);
 }

Could you please share the sample code for setup the change password in identityserver3

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
