### ISSUE TITLE
Invalid algorithm specified

### ISSUE THREAD

**Issue by pagidi** [IdentityServer/IdentityServer3#3789]
Can some one throw some light on this?

{"Message":"An error has occurred.","ExceptionMessage":"Invalid algorithm specified.\r\n","ExceptionType":"System.Security.Cryptography.CryptographicException","StackTrace":"   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)\r\n

**Comment by ashwhitmore** [comment]
It's related to Windows Security Update KB4025344 [https://github.com/IdentityServer/IdentityServer3/issues/3790](url)

**Comment by brockallen** [comment]
Dup, closing.
