### ISSUE TITLE
How to Enable SSL?

### ISSUE THREAD

**Issue by urajkovic** [IdentityServer/IdentityServer3#3791]
I created Identity Server that is using IdentityServer3 in VS 2015. It is started on http://localhost:61691/ and works great. 

### Question / Issue
I would like to enable SSL for this project. How can I do it?

I tried to set RequireSsl = true in IdentityServerOptions. In Project properties I set SSL Enabled to True and SSL URL to https://localhost:44396/. In Properties->Web->Project Url I set https://localhost:44396/.

When I start project, Startup.Configuration is not called at all. Server is not started. Nothing is written in Log file.

Should I change something else to enable SSL?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
