### ISSUE TITLE
Use Existing Idp with IdentityServer3

### ISSUE THREAD

**Issue by stefanodonofrio** [IdentityServer/IdentityServer3#3793]
Hi All.
I would like to use an existing Idp with IdentityServer3. I have read that I need a middleware to connect with it and consider it as External Provider. How can I attach this middleware in my existing Idp?

**Comment by tbrettallen** [comment]
By existing idp, are you referring to an in-house identity store, or an actual external provider such as Google / Facebook etc?

If you're referring to Google / Facebook, there should be some examples.

If you're talking about an internal identity store, create you're own UserService that inherits from UserServiceBase and override AuthenticateLocalAsync/Authenticate to process the request based on the passed in IDP in the authentication request.

**Comment by stefanodonofrio** [comment]
Thank you Allen.

I'm using an internal Identity Store. In order to use it as an External Idp, I'm using the Cookie Middleware and when I run the website the following error is showed in the logger:  
**no providers registered for client**

The Problem is that I've not found any example to do that. Can you send me some links with the example of my case? 

Thank you again and regards

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
