### ISSUE TITLE
Google SSO returns access denied after login from google account Identity Server3

### ISSUE THREAD

**Issue by osamajaved** [IdentityServer/IdentityServer3#3794]
### Question / Issue
Hi
I am trying to use Google SSO with identity server3. When I try this, Google ask for credentials, when provided and authenticated, it returns back to identity server where it throws Access_denied
https://local-passport.com/identity/callback?error=access_denied

Following are the claims I am providing
            public const string Clm_Id = "urn:google:profile";
            public const string Clm_Email = "email";
            public const string Clm_FirstName = "given_name";
            public const string Clm_LastName = "family_name";

Thinktecture.IdentityServer3 = 1.6.0.0

Can you please help me out.

Regards
Usama

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
