### ISSUE TITLE
invalid openid scope

### ISSUE THREAD

**Issue by fablacky** [IdentityServer/IdentityServer3#3795]
-  I read and understood how to manage claims and scopes (https://identityserver.github.io/Documentation/docsv2/configuration/scopesAndClaims.html)

### Question / Issue
I am setting up an OpenIdConnectAuthentication on my .netCore webApp and I'm having issues getting to the default login page of my Auth Server which still uses IdSrv3. 

You can read an extract from the log below:
2017-07-31 12:12:07.3161|INFO|IdentityServer3.Core.Endpoints.DiscoveryEndpointController|Start discovery request
2017-07-31 12:12:07.8291|INFO|IdentityServer3.Core.Endpoints.DiscoveryEndpointController|Start key discovery request
2017-07-31 12:12:08.4801|INFO|IdentityServer3.Core.Endpoints.AuthorizeEndpointController|Start authorize request
2017-07-31 12:12:08.4801|INFO|IdentityServer3.Core.Validation.AuthorizeRequestValidator|Start authorize request protocol validation
2017-07-31 12:12:08.4901|ERROR|IdentityServer3.Core.Validation.ScopeValidator|Invalid scope: openid
2017-07-31 12:12:08.4901|INFO|IdentityServer3.Core.Endpoints.AuthorizeEndpointController|End authorize request

I've included the 'openid' scope in my implementation of IScopeStore:

    public class ScopeService : IScopeStore
    {
        List<Scope> scopes = new List<Scope>
            {
                new Scope
                    {
                        Type = ScopeType.Resource,
                        DisplayName = "Web Client",
                        Name = "workstation",
                        Description = "Allow access to all api"
                    },
                StandardScopes.OpenId,
                StandardScopes.Profile,
                StandardScopes.Email
            };

        public Task<IEnumerable<Scope>> FindScopesAsync(IEnumerable<string> scopeNames)
        {
            IEnumerable<Scope> result = scopes.Where(sc => scopeNames.All(sn => sc.Name == sn));
            return Task.FromResult(result);
        }

        public Task<IEnumerable<Scope>> GetScopesAsync(bool publicOnly = true)
        {
            IEnumerable<Scope> result = scopes;
            return Task.FromResult(result);
        }
    }

I found a solution (I guess) by using a static class returning a list of scopes to use when instatiating the IdentityServerServiceFactory or even simply:

            IdentityServerServiceFactory IdSrvFactory = new IdentityServerServiceFactory()
                .UseInMemoryScopes(StandardScopes.All);

but I'd love to know why I can't use an implementation of IScopeStore.
Thank you for any information you can provide me.

**Comment by brockallen** [comment]
Did you register your store in DI?

**Comment by fablacky** [comment]
No, it was directly referenced from another assembly.
IdSrvFactory.ScopeStore = new Registration<IScopeStore, MyIdentityProvider.ScopeService>();

**Comment by brockallen** [comment]
The above registration should work -- that's what I meant about putting it in DI.

So you don't see your class' ctor ever run?

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by fablacky** [comment]
I was and currently am unable to check if at least the ctor run, but I don't think so.

**Comment by fablacky** [comment]
Sorry but after months I was finally able to resume working on this issue, when loading IdSrv I can see my scopestore gets correctly initialized in DI and its succesfully registered as I said above. Still any scope I pass from my client gets rejected as if there were no scopes on my IdSrv.
I even tried obtaining a list of scopes from my injected class and pass it as a MemoryStore on the IdSrvFactory but it still won't work..

**Comment by fablacky** [comment]
all set to be closed. sorry again
