### ISSUE TITLE
role property not always an array type

### ISSUE THREAD

**Issue by BruceHunter** [IdentityServer/IdentityServer3#3797]
### Question

ODIC :  manager.signinRedirectCallback()
ODIC : manager.getUser()
connect/userinfo: role too 

The role is not always an array type if only 1 role for the user.
If more then 1 role then it's an array. 
I find it odd that it is not always just an array even if 1 role.

            if (Array.isArray(profile.role)) {
                for (var i = 0; i < profile.role.length; i++) {
                    if (profile.role[i] === 'RoleNameHere') {
                        return true;
                    }
                }
            } else {
                if (profile.role === 'RoleNameHere') {
                    return true;
                }
            }

Why does it do this? 

I'm sure it's too late to change it now anyway.

**Comment by brockallen** [comment]
> I'm sure it's too late to change it now anyway.

Yes, you are right :)
