### ISSUE TITLE
Differentiate between OAuth scopes, one that requires user permissions and one that doesn't require user permission

### ISSUE THREAD

**Issue by AsifMushtaq** [IdentityServer/IdentityServer3#3798]
We need to differentiate between oauth scopes for the resource, one that needs user permission like `manage-user-emails` and the other which doesn't require user permission like `read-countries-list`.

The oath scopes that requires users permission should be subject to the user consent and the other resources that can be access by `client_credential` flow doesn't require user consent and doesn't need to appear on consent screen.

We need that oath scopes that require user permissons should only appear on the consent screen as oppose to all other oath scopes including the one that doesn't require user permission.

There can be two approaces. 

1. Only allow web applications clients to have oath scopes require user permission. It will help in showing only the relevent scopes on the consent screen, but it means that web application will have to have two clients one for the application logins and the other with `client_credential` flow for accessing those resouces that doesn't requires users permission.

2. Other approach can be to only show oath scope that requires user permission on the consent screen, for that one way could be to use the `Emphasize` flag on the scope, and only show the oath scope on consent screen with are marked as `Emphasize`.

**Comment by brockallen** [comment]
We only allow this based on the client's trust model to the STS (via the Client consent flag).
