### ISSUE TITLE
Global Single Sign-Out Not Working

### ISSUE THREAD

**Issue by BrandonScharf** [IdentityServer/IdentityServer3#3799]
Im having an issue with an implementation of IdentityServer3 and so far have ran into a wall. Essentially we are going to have a bunch of applications on our website, and each app will act as an RP, so I need a URL that I can call (maybe even to just wrap to the endsession endpoint), that will log me out of all of the RPs and the OP.

We have a minor customization of IdentityServer3 (essentially just custom login view) and a simple MVC client RP. I am able to connect the RP to the OP and it is able to force authorization no problem. I have also setup my own custom view/controller in the OP (/Account/Logout) that I'm trying to implement as a single point to sign out of ALL RPs and also display a custom logout message (which is why I created the Action/View). 

When I start debugging the application, below is where everything resides:
OP Site - http://localhost:16279/
OP Login URL - https://localhost:44372/identity/login?signin=....
RP Client - http://localhost:15990/

When I navigate to the RP client, I have no cookies as expected. I then click login, and Im redirected to the OP Login URL and asked to login. This creates a few cookies as expected, OpenIdConnect.nonce.....,  SignInMessages........., and an idsrv.xsrf cookie. I then login successfully and Im returned back to the RP site with the following cookies: .AspNet.Cookies, .AspNet.Cookies.C1, .AspNet.Cookies.C2 and 2 custom cookies (Custom1 and Custom2 for now).

Then, since I have implemented a logout action on the Account controller, I redirect my browser to http://localhost:16279/Account/Logout (my custom action on the OP site), which runs the below code

```
OP AccountController.cs
public ActionResult Logout()
{
    //sign out of the owin/identityserver completely
    var OwinContext = HttpContext.GetOwinContext();

    OwinContext.Authentication.SignOut("Cookies");
    OwinContext.Authentication.SignOut();

    //logic to remove/invalidate Custom1 and Custom2 cookies
}
```
At this point, I feel I should be logged out of both the OP and all RPs, however thats not the case. The URL is still http://localhost:16279/Account/Logout, and its showing my custom logout view as expected. However, upon inspecting the cookies, Im left with .AspNet.Cookies, .AspNet.Cookies.C1, and .AspNet.Cookies.C2, while my Custom1 and Custom2 cookies are gone. If I then redirect my browser back to the RP (http://localhost:15990/), I see the same 3 cookies, but the client still shows me as logged in.

If I were to instead call the RPs Home controller and Logout action, which has the below code, its able to successfully log me out of the RP and I get redirected to the following OP URL, https://localhost:44372/identity/logout?id=.......; at this point I have 2 cookies, SignMessage...... and idsrv.xsrf. If I then navigate back to the RP, I have ZERO cookies. 
```
RP HomeController.cs
public ActionResult Logout()
{
    Request.GetOwinContext().Authentication.SignOut();
    return Redirect("~/");
}
```

So although my OP and RP logout actions are pretty much running the same code, when its run on the RP side, its logging me out of the RP no problem, but when the OP runs the same code, its not actually logging me out of the OP and RP and removing all of the cookies.

Anyone know what Im missing here about why the OP isnt removing the cookies for all RPs and successfully doing a global logout?

Please let me know if additional information is needed.

**Comment by brockallen** [comment]
Because you're not triggering single signout. Your user should be visiting the end session endpoint in IdSvr to perform signout.

**Comment by BrandonScharf** [comment]
Ive tried switching our logout call to the end session endpoint, passing in the id_token, but I get a 404 error because the query string is too long. The thing I dont understand is when I call the end session endpoint using the id_token, its huge and goes through the query string, resulting in the 404. But when I have the RP Home/Logout action called, its not even passing the query string over with the id_token, yet its still making the logout/end session call somehow.

Ive also tried logging into the RP, then calling https://localhost:44372/identity/connect/endsession, and it redirects me to the logged out page https://localhost:44372/identity/logout?id=......, but when I navigate back to the RP, Im still logged in.

**Comment by brockallen** [comment]
You need to put fewer claims in the id_token then to make it smaller.

**Comment by BrandonScharf** [comment]
I cant put fewer claims in it because we need all of those claims for all of the subsequent apps. Is it possible to put the id value into a claim, and then pull that specific claim as the id to send over in the query string?

**Comment by brockallen** [comment]
Look into the user info endpoint concept.

**Comment by BrandonScharf** [comment]
Our layout requires the claims to always be there and isn't able to make a call to another endpoint, so we cant move the claims and also cant shrink it.

Is it possible to make a call to the OP Account/Logout, have the OP clear the claims out, and then use that new/current id_token as a part of the query string to call the end session endpoint. Sort of like a way to wrap the logout process while making the claims smaller? Because we know if the user has called the logout, its OK to make the claims smaller since they dont need them anymore.

**Comment by brockallen** [comment]
Anything is possible, but it would all be custom work beyond how the protocols are designed.

**Comment by BrandonScharf** [comment]
Is there not a way for the OP to have something called and have it initiate a logout of all of the RPs? Why cant the end session endpoint be called without a query string and just have it log out of all of the RPs?

**Comment by brockallen** [comment]
Normally the end session request should be authenticated. This is covered in the specs. We do have a flag to bypass it, but it's not recommended.

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AuthenticationOptions.cs#L35

**Comment by BrandonScharf** [comment]
Well if I'm authenticated and I call "https://localhost:44372/identity/connect/endsession", its redirecting me telling me Ive been logged out, but if I go back to the RP that made that call, it shows me as still logged in.

**Comment by brockallen** [comment]
Does the client have a LogoutUri configured? https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Models/Client.cs#L94

**Comment by BrandonScharf** [comment]
My client has an option for PostLogoutRedirectUri, but not LogoutUri.

**Comment by brockallen** [comment]
So that's why -- it's not coded to participate in the single singout. Check out MVC samples for a sample.

**Comment by BrandonScharf** [comment]
I dont want to have to make all of our applications have a specific piece of code to specify where to logout though, I want every RP to be able to call the OP and have the OP handle the logout. Much easier to change it in one place, not 50 (accounting for testing and re-releasing, that would be a nightmare).

We want to have our layout, the static _Layout.cshtml we push out to every app, have the logout button go to the OP logout process and have the OP handle the logout, that way each application doesnt need to worry about how to logout.

**Comment by brockallen** [comment]
Perhaps we're misunderstanding one another. I'd suggest first looking at the samples and how they implement the OIDC end session spec and how the client apps participate in that.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
