### ISSUE TITLE
LogoutCallback tries to log the user in

### ISSUE THREAD

**Issue by benaichouchem** [IdentityServer/IdentityServer3#3800]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

When we hit the Logoutcallback, and the user has already logged out, we get redirected to the login page.
The expected behavior is to be redirected to the **PostLogoutRedirectUri**

Why are we doing this? we are implementing a Signel Sign Out, and using Iframes, and the other open tabs get redirected to the login page instead of coming back to the App (we have optional login on the Apps)

### Relevant parts of the log file
```
Messages ordered from older to newer:

"Message" : "End session callback requested",
"Message" : "Start authorize request protocol validation",
"Message" : "Cache hit on Client_WEB_CLIENT",   ==> **This is the profile client not the one the user tries to logout from.**
"Message" : "Start authorize request",
"Message" : "Authorize request validation success\n
"Message" : "User is not authenticated. Redirecting to login.",
```

**Comment by brockallen** [comment]
> When we hit the Logoutcallback, and the user has already logout we get redirected to the login page.

In your client, you mean?

**Comment by benaichouchem** [comment]
Yes, good point
If I visit
https://client.site.com/Home/Signout: if the user is logged in, the redirect works fine, but if the user is already logged out, it gets stuck in the Id login page.

After checking the code, I tried to set : `RequireAuthenticatedUserForSignOutMessage = true`
but that didn't help. Any suggestions?

**Comment by brockallen** [comment]
> Yes, good point

I was just trying to clarify since I'm not really following what the issue is.

**Comment by benaichouchem** [comment]
Is the issue clearer now?

**Comment by brockallen** [comment]
Not really. It sounds like if a user is not logged into the client and they are sent to the client's post logout redirect then the client sends them to login at the STS. Is that about right?

**Comment by benaichouchem** [comment]
Almost, the problem is Identity server, doesn't redirect back to the Post logout uri if the user is not logged in.

 **Scenario one: user logged in.**

- Visit https://client.site.com/Home/Signout

- Go to the Logout page on Identity server https://loging.site.com/core/logout....

- Redirects back to https://client.site.com (PostLogoutURI)

**Scenario two: user not logged in**

- Visit https://client.site.com/Home/Signout

- Go to logout page on identity server

-  gets redirected to login page (https://login.site.com/core/login...) instead of Post Logout URI

**Comment by brockallen** [comment]
> Almost, the problem is Identity server, doesn't redirect back to the Post logout uri if the user is not logged in.

Right, because no id_token is sent to the end session endpoint, thus IdentityServer can't authenticate the request for signout, and thus doesn't know which client made the request.

**Comment by benaichouchem** [comment]
But the user is not logged in, there is no id_token, right? is there a way to fix this behavior?

**Comment by brockallen** [comment]
If the user is not even logged into the client, why would you send them to the STS for logout?

**Comment by benaichouchem** [comment]
If we have three tabs open, and the user logs out from one tab, we use the IFrame technique to log them out from the other open tabs. So in our CheckSessions code:

` window.addEventListener("message", function (e) {
                if (e.origin === params.opOrigin) {
                    if (e.data !== "unchanged") {
                        window.clearInterval(timer);
                    }
                    switch(e.data) {
                        case "changed":
                            window.location.href = "/Home/login";
                            break;
                        case "ended":
                            window.location.href = "/Home/SignOut";
                            break;
                    }
                }
            });`

**Comment by brockallen** [comment]
Well, I don't know what else to advise. I think you now understand what's happening. You'll have to decide how to handle it.

**Comment by benaichouchem** [comment]
So there is no way for Identity server to say: Hei, the user is not logged in, return?
Otherwise, should we have another endpoint where we just clear the cookies when we receive the "ended" message?

**Comment by brockallen** [comment]
> So there is no way for Identity server to say: Hei, the user is not logged in, return?

Not via OIDC. The issue here is that you want to avoid open redirect attacks.

**Comment by benaichouchem** [comment]
Ok, we settled for clearing out the cookies from the clients when we receive an ended state from the Ids.
And for login, the user has to refresh the page. Looks good.
