### ISSUE TITLE
Authentication for internal or external users

### ISSUE THREAD

**Issue by ganiths** [IdentityServer/IdentityServer3#3801]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

We currently have  requirement to support different type of authentication(windows/form) based on internal/external request. If a user from the internal network access the application then it should use windows credentials to do a seamless login. If user access from external network then it should be redirected to login. Currently we have built 2 different authentication providers each mapped to a specific path as below

  appBuilder.Map(
                @"/loginIdentity", 
                config =>
                    {
                        config.UseIdentityServer(serverOptions);
                    });

 appBuilder.Map(
                @"/windowsIdentity",
                config =>
                {
                    config.UseIdentityServer(serverOptions);
                });

Currently we do have an option to route to  appropriate redirect uri in the client application based on the internal/external request. 

But we wanted to move this logic generic and keep it in identity service as multiple client application were using this identity server and everyone would require this feature to be built in.

Is there any option where we can  route to different identity providers based on request?.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
