### ISSUE TITLE
Issuing token for API calls from third paries

### ISSUE THREAD

**Issue by nixa333** [IdentityServer/IdentityServer3#3802]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I'm new to OAuth and OpenId so googling doesn't help since I don't quite understand what exactly do I need.
Essentially my app has user accounts and I implemented IS to support logging in and everything else, that part works fine. Users have rights to access company data, for example three users could be working for AdventureWorks and they can access the data for that account. One of them could also be doing some work for other company and could access that company's data. I have a public API that users can call to work with the data if they don't want to use my GUI application. Here's where the problem is - I would like to issue sort of an API token for the **company** account, so that one of those AdventureWorks users can go into my integrations page, request a token and use that token(by sending it in request header) to call the public API directly. That token is not tied to my specific user, but rather to the company account, and anybody that has the token can use it to call the API and fetch the data for that company(In this case AdventureWorks).  How do I achieve this?

**Comment by brockallen** [comment]
Look into the client credentials flow scenario. We have lots of samples.

**Comment by nixa333** [comment]
I just realised a posted this under IS3, and intended under IS4, but I guess it's probably the same. Doesn't the client credential flow mean I'd have to define a client each time this type of token is issued(Is that how it's supposed to work)? I would like to issue a token that user can copy/paste somewhere and then use for future API calls as request header parameter, not needing to include clientid and password.

**Comment by brockallen** [comment]
The workflow is the client uses its credentials to obtain a token and that token can be used up to its expiration. This approach allows you to shutoff the client if needed (as opposed to a long-term API key approach where each API would have to do this check). Separation of concerns.

**Comment by nixa333** [comment]
Yeah but that means all my users wanting to implement API calls would need to use code like this(Implemented in their specific language), to first obtain the token

`var tokenClient = new TokenClient(disco.TokenEndpoint, "client", "secret"); 
var tokenResponse = await tokenClient.RequestClientCredentialsAsync("api1");`

and then 
`var client = new HttpClient();
client.SetBearerToken(tokenResponse.AccessToken);
var response = await client.GetAsync("http://localhost:5001/identity");`

What I want is to somehow issue them this **tokenResponse.AccessToken** so they can just use it right in the request. I want to make API call implementation for my users as simple as possible, and would probably need this "long-term API key" you mentioned. Is that possible to achieve with IS?

**Comment by brockallen** [comment]
Sorry, that's not OAuth2 then, and thus IdentityServer won't be of help.

**Comment by nixa333** [comment]
Thanks for clarifying
