### ISSUE TITLE
acr_value on challenge not transmitted to the middlware

### ISSUE THREAD

**Issue by Yassine-Khechane** [IdentityServer/IdentityServer3#3803]
Hello, 
i'm trying to challenge external providers (google/facebook) and passer extra data

in the controller :

 `[HttpPost]
public ActionResult ExternalProvider(string identityProvider)
{
    var redirectUri = "http://secure.fnac.dev/Front-DevFront/account/dashboard";
    var authenticationProperties = new AuthenticationProperties
    {
        RedirectUri = redirectUri
    };            
    authenticationProperties.Dictionary.Add("acr_values", $"idp:{identityProvider}");
    HttpContext.GetOwinContext().Set("ForwardToLoginProvider", identityProvider);
    HttpContext.GetOwinContext().Authentication.Challenge(authenticationProperties, identityProvider);
    return Content(string.Empty);            
}`

In the RedirectToIdentityProvider method i have this: 

`if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
{
    var loginProvider = context.OwinContext.Get<string>("ForwardToLoginProvider");
    if (loginProvider != null)
    {
        context.ProtocolMessage.AcrValues = "idp:" + loginProvider;
    }
}

if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest && context.OwinContext.Authentication.AuthenticationResponseChallenge != null)
{
    var authenticationPropertis = context.OwinContext.Authentication.AuthenticationResponseChallenge.Properties.Dictionary;
    if (authenticationPropertis != null)
    {
        foreach (var pair in authenticationPropertis)
        {
            context.ProtocolMessage.Parameters[pair.Key] = pair.Value;
        }
    }
}`

but i' can't get the extra params (idp that i set in the acr_values / ForwardToLoginProvider ) !

Any ideas ?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
