### ISSUE TITLE
No cookie matching signin id found

### ISSUE THREAD

**Issue by davdev82** [IdentityServer/IdentityServer3#3804]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

We are using IdServer3 (2.5.0) in Production behind a load balancer. I can confirm that all Machine Keys are 
synchronised. We are using IIS hosting and therefore we are using Microsoft.Owin.Host.SystemWeb (v 3.1.0). We are seeing a large quantities of errors in production of the form "No cookie matching signin id found".  Can you guys please help as it is causing a lot of pain for our business. I was planning to put the invalidsigninredirect url in place. But that is just another page to handle scenarios where a user tries to login to a page expecting SignInMessage cookie without first going through authorize endpoint

**Comment by brockallen** [comment]
You need to track down the reason you're getting that error. I suspect users are bookmarking the login page. That's what the `InvalidSignInRedirectUrl` is for.

**Comment by davdev82** [comment]
I agree Brock. I am not able to understand the reason for so many errors of type "No sign in id found".  Coupled with that we are getting a whole bunch of requests for "Start key discovery document".

**Comment by brockallen** [comment]
Since there's not much to go on here, I'll close. Feel free to reopen if you discover more and feel there's a bug here.

**Comment by firasr** [comment]
Getting this error message when copying a valid login URL to different browser (e.g Firefox to Chrome). How this can be resolved?

**Comment by brockallen** [comment]
> Getting this error message when copying a valid login URL to different browser (e.g Firefox to Chrome). How this can be resolved?

That's not something supported. You can upgrade to IdentityServer4 if you need to be able to switch browsers mid-login (which is a strange requirement IMO).
