### ISSUE TITLE
Issue with multiple applications using shared clientID

### ISSUE THREAD

**Issue by BrandonScharf** [IdentityServer/IdentityServer3#3805]
Im running into a weird issue with IdentityServer 3 and having multiple relying parties using the same clientID. We are trying to implement IdentityServer3 as our login process/authetication/permissions and have multiple applications on our site act as relying parties. Since we dont want to require the user to login to every single application individually, we have decided to make every RP use the same clientID. This way regardless of the URL/RP/App the user visits, if they arent authenticated, it will require them to login, and if they are already logged in, they shouldnt have to do anything. And same goes for logging out, if they log out of any RP/App on our site, it should automatically log them out of every single app on our site.

In our tests so far for a single application/RP, everything appears to be working fine, both in debug and releasing to our dev server. So then I started developing/testing 3 RPs in one solution (which also has our provider in the solution) all running on different local ports, all sharing the same clientID. Below are my 3 RPs and the relevant information for the OP. Each application has a single view that loops through the cookies/claims to display everything within them (As a way to verify the claims created, clientID/aud, as well as 2 custom cookies).

### OP
URL -  https://localhost:44372/identity

### RP 1
URL - http://localhost:15990/
Authority - https://localhost:44372/identity
ClientID - App.Local
RedirectUri - http://localhost:15990/

### RP 2
URL - http://localhost:62415/
Authority - https://localhost:44372/identity
ClientID - App.Local
RedirectUri - http://localhost:62415/

### RP 3
URL - http://localhost:62789/
Authority - https://localhost:44372/identity
ClientID - App.Local
RedirectUri - http://localhost:62789/

When I have this running locally (with all 3 in different tabs), I can go to any ONE of the above 3 RPs, login, refresh the view on the other 2 RPs that shows all of the claims/cookies, and across all 3 RPs the information is the EXACT same and I'm authenticated with no issues. Then, if I log out of any ONE RP and refresh the other 2, it shows me as logged out, as it should, again no issues.

Now on to the actual issue, which is upon deploying it to our dev server; below is the relevant information.

### OP
URL -  https://mysite.com/Auth/identity ('Auth' is the IIS app name)

### RP 1
URL - http://mysite.com/RP1/
Authority -  https://mysite.com/Auth/identity
ClientID - App.Release
RedirectUri - http://mysite.com/RP1/

### RP 2
URL - http://mysite.com/RP2/
Authority -  https://mysite.com/Auth/identity
ClientID - App.Release
RedirectUri - http://mysite.com/RP2/

### RP 3
URL - http://mysite.com/RP3/
Authority -  https://mysite.com/Auth/identity
ClientID - App.Release
RedirectUri - http://mysite.com/RP3/

I open all 3 RPs in different tabs again to the cookie/claim view. I go to any single RP to login and I can see all the cookie/claim data for that RP. Then if I refresh the cookie/claim view in the other 2 RPs, I can see my 2 custom cookies, but no identity server claim information. If I then click the login button on any of the other 2 RPs, it automatically logs me in, I can then see the cookie/claim data for that RP, but if I go back to the other/original RP and refresh the view, I no longer have claims, almost like then new RP login stole it from the previous login.

Why is it that locally, everything is working fine, but upon moving it to the server, with no other changes, suddenly RPs are stealing cookies/claims for other RPs, even though they share the exact same clientID?

How can we use IdentityServer as our login/auth process, but use multiple applications as the same client? Is this technically multi-tenancy?

Let me know if I can provide additional information and I appreciate any help we can get.

**Comment by brockallen** [comment]
Normally you'd not use the same client id for different apps. Not sure if that's your issue or not.

**Comment by BrandonScharf** [comment]
So If I have a website that uses IdentityServer as the authentication process, and on that website I have multiple applications, that would require me to have my users sign into IdentityServer every time they go to a new application, even though they are all on the same site?

**Comment by brockallen** [comment]
If they're different logic app, then yes.
