### ISSUE TITLE
Change system time/ exp is in the past

### ISSUE THREAD

**Issue by BenjaminWang1031** [IdentityServer/IdentityServer3#3807]
I know this is unusual, but after I logged in and changed the system time to make the authentication cookie expired,  logged out, I couldn't log in any more,  error says: Exp is in the past, I cleared the cache, local storage and that still didn't go away unless I change the system time back.

Any ideas?

**Comment by brockallen** [comment]
Nope, sorry.

**Comment by BenjaminWang1031** [comment]
I figured out that if you change your local time to be ahead of server time more than the authentication cookie's lifetime, you would never log in as cookie will always be expired.
