### ISSUE TITLE
Custom error message on login failure

### ISSUE THREAD

**Issue by BrandonScharf** [IdentityServer/IdentityServer3#3808]
This may be a possible question, but at this point I'm looking at it as a bug from what Ive read.

We have a login flow that is checking for expired passwords, and if the users entered password has expired, we want to return a error message in context.AuthenticateResult. We are doing this fine with other standard errors, however, for the the expired password, I want to give them a clickable link in the error to the appropriate page. When I do this in the context.AuthenticateResult errorMessage, the raw message is displayed instead of the HTML anchor tag.

Is there a way that we can allow HTML in the error message, was it not designed with this in mind, or is this a bug?

**Comment by brockallen** [comment]
It's by design. If you want to customize the view, then look into the archives or docs on doing this.
