### ISSUE TITLE
Facebook authentication not working with identity server

### ISSUE THREAD

**Issue by Arvind103** [IdentityServer/IdentityServer3#3811]
I am trying facebook authentication with indentity server. But it reurns access denied in LoginExternalCallback. What I might be doing wrong? Below is what i am doing to initialize authentication option

        var fb = new FacebookAuthenticationOptions
        {
            AuthenticationType = "Facebook",
            Caption = "Sign in with Facebook",
            SignInAsAuthenticationType = "Facebook",
            AppId = "<App-ID>",
            AppSecret = "<App-Secret>",

            BackchannelHttpHandler = new FacebookBackChannelHTTPHandler(),
        };

        fb.Scope.Add("email");
        app.UseFacebookAuthentication(fb);

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
