### ISSUE TITLE
Identity Server AccessTokenLifetime property and OIDC automaticSilentRenew

### ISSUE THREAD

**Issue by mrbbm** [IdentityServer/IdentityServer3#3812]
### Question / Issue

I would like to know which one is need to configure for Automatic Token renew, note I'm using **Identity Server Version 3.0** and **Javascript Client UI Application**

My Client configuration is

```
new Client
{
    Enabled = true,
    ClientName = "JS Client",
    ClientId = "js",
    Flow = Flows.Implicit,
    AllowedScopes = new List<string>() {
        "openid", "profile", "email", "api"
    },

    RedirectUris = new List<string>
    {
        "http://localhost:7000/popup.html",
        "http://localhost:7000/silent-renew.html"
    },

    PostLogoutRedirectUris = new List<string>
    {
        "http://localhost:7000/index.html"
    },

    AllowedCorsOrigins = new List<string>
    {
        "http://localhost:7000"
    },

    AllowAccessToAllScopes = true,
    AccessTokenLifetime = 60
},
```

The Current setup of Client re-loads the web page on every 60 Seconds AccessTokenLifetime = 60

My Javascript OIDC Configuration is

```
var settings = {
    authority: 'https://localhost:44300',
    client_id: 'js',
    popup_redirect_uri: 'http://localhost:7000/popup.html',
    silent_redirect_uri: 'http://localhost:7000/silent-renew.html',
    post_logout_redirect_uri: 'http://localhost:7000/index.html',

    response_type: 'id_token token',
    scope: 'openid profile email api',

    accessTokenExpiringNotificationTime: 4,
    automaticSilentRenew: true,

    filterProtocolClaims: true
};
```

I don't know whats the purpose of `automaticSilentRenew: true`, because **every 60 seconds it re-loads** the web application. Kindly assist me whats the actual purpose of `automaticSilentRenew: true` ? Moreover assist me whats the right way to renew the Token ?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by krishna1682** [comment]
Yes. I am also facing the similar issue as the token is getting expired based on AccessTokenLifetime and even we implemented automaticSilentRenew. Can anyone please assist on this.
