### ISSUE TITLE
Issue on redux-oidc signoutRedirect

### ISSUE THREAD

**Issue by mrbbm** [IdentityServer/IdentityServer3#3814]
### Question / Issue

I'm using Identity Server for Single Sign On, my Client application is in ReactJs embedded with Redux. I'm using redux-oidc npm node module to implement the Identity Server functionality as mentioned in [https://github.com/IdentityModel/oidc-client-js/wiki](https://github.com/IdentityModel/oidc-client-js/wiki)

My oidc config is

```
var settings = {
        authority: 'https://localhost:2025/core',
        client_id: 'TVA',
        silent_redirect_uri: 'http://localhost:3000/silent-renew.html',
        post_logout_redirect_uri: 'http://localhost:3000',
        redirect_uri: `http://localhost:3000/callback`,
        response_type: 'id_token token',
        scope: 'openid payroll',
        acr_values: `tenant:Payroll`,
        accessTokenExpiringNotificationTime: 4,
        automaticSilentRenew: true,
        filterProtocolClaims: true
    };
```

If I use the in-built method `signoutRedirect`, its again redirecting to the application's initial landing page, but if I directly trigger the end session it redirects to the Identity Server Login Page (i.e., Once the application is successfully logout, the Identity Server redirects to the root URI and then it redirects to the Login page).

**Issue: Its not Signout the application**
```

userManager.signoutRedirect()
    .catch(function (error) {
        console.error('error while signing out user', error);
    });
```

**Fine: Signout's perfectly**

const path = `https://localhost:2025/core/connect/endsession?id_token_hint=${token}&post_logout_redirect_uri=http://localhost:3000`;
document.location.href = path;

Kindly assist me how to signout using `userManager.signoutRedirect()` ???

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
