### ISSUE TITLE
Getting User ClaimsPrincipal from Middleware

### ISSUE THREAD

**Issue by rizamarhaban** [IdentityServer/IdentityServer3#3815]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Okay, everything is fine and all works beautifully. Now, I have an API that require every call should make a history list. And every API method require to pass the username to the event source Bus (*I use CQRS*). The parameter value that I have to pass is the username, i.e;

    var user = User as ClaimsPrincipal;
    var username = user.FindFirst("name").Value;

My question, is there a way to capture this first, maybe from the middleware side in the Startup (OWIN) ? Basically, if someone logged in, I would like to capture the user who logged in and pass the value to DI container so I don't have to get the ```ClaimsPrincipal``` all the time on every API method. And, yes, I can create attribute filter and decorate every method as well, but maybe there are better ways to do this.

I mean, I just want to inject the username to some settings interface so it can be use it anywhere on the project. Any other better way to do this will be helpful. I hope the question will be helpful for others as well.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by rizamarhaban** [comment]
Thanks @brockallen, will open question on Stackoverflow.
