### ISSUE TITLE
Resume partial authentication from WebApi

### ISSUE THREAD

**Issue by Yassine-Khechane** [IdentityServer/IdentityServer3#3818]
I'm using WebApi to associate an external account with a local account, is there a way to 
resume authentication from the web API?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
