### ISSUE TITLE
[QUESTION] Identity server 3 problems

### ISSUE THREAD

**Issue by Nodly** [IdentityServer/IdentityServer3#3819]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hello,

Currently I am working on Identity Server 3 configuration and I am experiencing weird problem, namely I am not able to get the token from Identity Server. I call identity server from my js app and once I log in and click "Yes allow" it throws an exception "Invalid algorithm specified". I even created my own certificates still same result - an error

Also I have tried samples from the documentation and it also doesn't work. In addition I've done in on a different computer and there it works as charm. Any idea what might be wrong here? Many thanks.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by codyskidmore** [comment]
Can you post your log output please?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
