### ISSUE TITLE
[Question] Missing idsrv.session cookie in test environment

### ISSUE THREAD

**Issue by ben-harper** [IdentityServer/IdentityServer3#3821]
Under what circumstances would the idsvr.session cookie not be present when initiating a login?  

We have two environments (QA and UAT) which we have verified to have the same code and configuration but different behaviour.  Our setup is a single identity provider app (running identity server) and an ASP.NET MVC client app using OIDC cookie authentication.  After a successful signin, the client app fails, but only in the UAT environment, because it cannot find the “sid” claim which in turn would have come from the session_state form parameter on the POST redirect, which in turn would have come from the identity server session id. 

All other cookies in the exchange appear intact in comparing the two environments.  Authentication within the identity provider is successful, but the app fails as there is no authentication.

We suspect this is an environmental or config issue but have difficulty understanding what could be at play here.

Image showing chrome network traces in QA (working) on the left and UAT (not working) on the right.
![id3 missing cookie](https://user-images.githubusercontent.com/17434217/29382244-f474df16-8299-11e7-8244-d9c06a9daa7b.jpg)

**Comment by brockallen** [comment]
Not sure, sorry.
