### ISSUE TITLE
Question: About Same identity server implementation with same users for multiple Apis

### ISSUE THREAD

**Issue by crs-84** [IdentityServer/IdentityServer3#3822]
Hello, I'm starting with IdentityServer3, I already read the documentation and wrote some examples, but there is something that I have not clear yet.

May I use one single identityServer3 instance for multiple Apis?
Using the same user store?

take this structore as an example:

![sample](https://user-images.githubusercontent.com/31079421/29383164-4e1197b4-829d-11e7-8306-c36ce0de3e2b.jpg)

Thanks a lot for your help.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
