### ISSUE TITLE
Question: client_credential flow and access_token claims customization

### ISSUE THREAD

**Issue by KristofRennen** [IdentityServer/IdentityServer3#3823]
Hi

I'm using a client_credential flow, for which I was hoping to customize the access_token claims. 
I have a custom UserService implementation and identity server has been configured using entity framework on top of a MSSQL database. When I request a token via the client_credential flow, the GetProfileDataAsync method never gets called, so I have no way to customize the access_token claims. (btw, the method get's called with I use the authcode flow from another client using openid)

I have a client set up, a scope for the api I am protecting, and a ClientScope which links both. I can successfully request a token, but whatever I try (e.g. setting up proper ScopeClaims etc), the GetProfileDataAsync still isn't called.

The only option I see right now, is to create my own DefaultClaimsProvider, where I can overwrite the GetAccessTokenClaimsAsync method. But I read somewhere in another issue, that this was not the recommended way.

Any idea?

**Comment by brockallen** [comment]
> I'm using a client_credential flow, for which I was hoping to customize the access_token claims.

Set the client claims on the client configuration.
