### ISSUE TITLE
External Website Login for Authorization Code Flow 

### ISSUE THREAD

**Issue by rohanbadlani** [IdentityServer/IdentityServer3#3825]
- [Yes] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
First, please bear with me if I don't seem to be asking the question right.

We are using Identityserver3 and we want to use external identity provider for authentication. For the authorization code flow we would want to redirect the user to an external site (not part of our identityserver). The external site provides its response to a Redirect Uri (which would be on our identityserver). We referred to ExternalProvider Sample here (https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService/CustomUserService) but it seems to be calling a local endpoint (https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomUserService/CustomUserService/ExternalRegistrationUserService.cs#L58)

Is it possible to call an external site, do the authentication for the user there, receive the response (which would include the subject and the claims) on our identityserver and return an AuthenticationResult to the user?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
