### ISSUE TITLE
Configuration of JWTBearerAuthentication Use - Disable Authority | Xamarin

### ISSUE THREAD

**Issue by JasonLeedy** [IdentityServer/IdentityServer3#3828]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Attempting to test locally:
IdSrv on localhost:5000
Api1 on localhost:5001

client Android or iPhone running on emulator.  The localhost, is as it says local, i.e. the emulator.  The host machine above, in the case of android, is now 10.0.2.2.  

So rightfully, IdSrv4  barfs on the Issuer not matching.  

Question:  Is there a way to:

if (env.IsDevelopment()) {

//   ???  Some code to config JWT to ignore the Issuer validation check  ???

}

Understood that i can publish both idrsrv and Api1 to azure - trying to stay all local machine 

Sorry if easy -  IdSrv-newbie

### Relevant parts of the log file

Bearer was not authenticated. Failure message: IDX10205: Issuer validation failed. Issuer: 'http://10.0.2.2:5000'. Did not match: validationParameters.ValidIssuer: 'http://localhost:5000' or validationParameters.ValidIssuers: 'null'.
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
