### ISSUE TITLE
CORS request made for path from origin but rejected because invalid CORS path

### ISSUE THREAD

**Issue by DFullbrook** [IdentityServer/IdentityServer3#3829]
I have seen similar issues elsewhere (e.g. https://github.com/IdentityServer/IdentityServer3/issues/2424) but I have tried many things and still get the response detailed in the title. Please see my post on SO (https://stackoverflow.com/questions/45757240/cors-request-made-for-path-from-origin-but-rejected-because-invalid-cors-path) reproduced below:

I have an ASP.NET Web Forms website (localhost:44355) using OWIN middleware and Identity Server 3 (localhost:44325) for authentication. The Website is configured for Implicit flow. On user first browsing the site, it redirects to the IdSrv login page, authenticates and returns to the main website with the user claims - great so far. Most pages make use of the Ajax UpdatePanel.

If the User Session times out and the user then clicks on any control outside the Update Panel, it redirects to the IdSrv login page, authenticates and returns correctly. Perfect.

If, however, the User Session times out and the user then clicks on a control inside the Update Panel, no redirect takes place. To the user it appears that nothing has happened. (Note: A full page refresh will then correctly redirect the user to the IdSrv login page).

At the Identity Server I get the following log:

> CORS request made for path: "/connect/authorize" from origin: "https://localhost:44355" but rejected because invalid CORS path

I have done a lot of investigation and tried a lot of things:

1. At the IdSrv, use the DefaultCorsPolicyService with AllowAll = true.
2. At the IdSrv, implement ICorsPolicyService where IsOriginAllowedAsync() always returns true.
3. At the Wesbsite, intercept the OWIN RedirectToIdentityProvider method, and try to remove the "x-requested-with", "x-microsoftajax" and "origin" headers.

Note: In example 2, the method **IsOriginAllowedAsync** is not called.

None of these have been successful (Edge, Chrome and Firefox all behave the same). Has anyone got any more ideas?

**Comment by laksh-parab** [comment]
are you able to solve this issue?

**Comment by DFullbrook** [comment]
Hi Lakshmi-parab, 
No I haven't. Frustratingly nobody seems interested in the problem!
David.

**Comment by laksh-parab** [comment]
The same issue was posted [here ](https://github.com/IdentityServer/IdentityServer3/issues/3845)

**Comment by laksh-parab** [comment]
Temporarily, i am handling the issue in global `ajaxerror` event. I don't have update panel but i do use jQuery for ajax request

```
$(document).ajaxError(function (event, jqxhr, settings, thrownError) {
            if (settings.url && settings.url.toLowerCase().indexOf('jslog') === -1) {
                if (jqxhr && jqxhr.status === 401) {
                    alert('session expired. Please close browser and login again');
                }
            }
        });
```
Also one thing i have noticed testing in VS using IISExpress vs IIS on web server. in IIS express you may not get status as `401` instead you might get `0` as status. However IIS should return 401 when user is not authenticated.

Preferably i would like server would redirect user to login page when session expires

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
