### ISSUE TITLE
Question about security in SPA application. Self hosted login form.

### ISSUE THREAD

**Issue by arthur-rizzo** [IdentityServer/IdentityServer3#3831]
Hi, I searched and read a lot of documentation but I am not still sure why I shouldnt/cant have my own form for user/password input. 

I have an Angular SPA (which I would like to have login form), an Identity Server and a bunch of microservices connected to Identity Server for authentication. I control and develop all this applications (but idsrv).

Is it really not a good idea to have user inputting login/password inside my SPA? If so, why not? Is there any workaround for making that happen and still have the benefits of having a token manager (for silent renew), etc..

I also posted a question on stackOverflow that perhaps explains my questions better:
https://stackoverflow.com/questions/45817432/is-it-possible-to-have-spa-authentication-without-redirecting-to-an-outside-logi

Thanks in advance.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
