### ISSUE TITLE
How to access session state in a custom userservice

### ISSUE THREAD

**Issue by vip8668** [IdentityServer/IdentityServer3#3832]
I need access session in a custom user service to check captcha. But when i access HttpContext.Current.Session this object is null. Please tell me how to access Session in custom userservice.
Thank!

**Comment by brockallen** [comment]
Inject the OwinEnvironmentService and access the request via the dictionary or wrap it with an OwinContext.

**Comment by vip8668** [comment]
Can you give me a sample code. I had try  
`
 OwinContext ctx;
`
` public UserService(OwinEnvironmentService owinEnv)`
` {`
`ctx = new OwinContext(owinEnv.Environment);`
`var request = ctx.Request;`
`}`
but request doesn't have Session in this.

**Comment by brockallen** [comment]
What is session? ASP.NET Session State?

**Comment by vip8668** [comment]
> What is session? ASP.NET Session State?
Yes I Use Asp.Net MVC 5.
I want to check  the generated captcha and save to the session in the previous step

**Comment by brockallen** [comment]
I think it should be available if you're in IIS.
