### ISSUE TITLE
Error de Login o autenticacion

### ISSUE THREAD

**Issue by JosueAngarita** [IdentityServer/IdentityServer3#3833]
He creado mi sitio de identity server 3 y configurado mi IIS para que lo lea correctamente, agregue los certificados y al momento de solicitar acceso a mi aplicacion, el identityserver se activa y me envia justamente a mi loguin , ingreso mis credenciales y hay al ingresar me genera un error de logueo y me muesta la siguiente pantalla.

![image](https://user-images.githubusercontent.com/31323669/29686069-36db081e-88dd-11e7-8e22-e22d10bf412a.png)

Podrian ayudarme con este error, ya que al hacerlo en mi maquina local el autentica correctamente

Gracias

**Comment by codyskidmore** [comment]
@JosueAngarita enable logging (SeriLog recommended) and post the log output. See instructions here: https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

Use Nuget to install these packages:
- Serilog
- Serilog.Sinks.Trace

Then add the web.config section as shown in the above link. This should allow you to identity the problem and fix it.

**Comment by JosueAngarita** [comment]
![image](https://user-images.githubusercontent.com/31323669/29734821-11167964-89ba-11e7-9660-6227ee49b4e1.png)
Este error se me esta generando es error de certifiacdos?

**Comment by codyskidmore** [comment]
No. Es tarde aquí. Hablaremos mañana o domingo

**Comment by codyskidmore** [comment]
Are you using IIS? If yes, what application pool account are you using? Have you set permissions on the certificate for the application pool account?

**Comment by JosueAngarita** [comment]
si claro, ya encontré la solución era un problema con el nombre en mi archivo host el cual uso para en la url escribir desarrolloptr y no mi ip faltaba una pequeña configuración,  muchas gracias por toda su ayuda

**Comment by JosueAngarita** [comment]
Esta guia me ayudo mucho, https://blog.jayway.com/2014/10/27/configure-iis-to-use-your-self-signed-certificates-with-your-application/

**Comment by codyskidmore** [comment]
De nada. No olvide cerrar la conversación, por favor.
