### ISSUE TITLE
Bad redirect uri with an IIS site

### ISSUE THREAD

**Issue by CarlosSoria** [IdentityServer/IdentityServer3#3834]
Hi,

I am working on an application with angularJS and identity server 3, I am using oauth.js to connect to identity server project.

Everything it is configured and it works as expected on the development environment, but when we create a site on IIS for example: http://localhost/foo/index.html I am not able to get the login form an the following error it shows:

The client application is not known or is not authorized.

On the browser the URL is for example: http://localhost/identityserver/core/connect/authorize?response_type=id_token+token&client_id=foo&state=Iz3YGosn1231DXbW3xwnicbRvqIr26AaWqmyrTZq%3B%3D&redirect_uri=http%3A%2F%2Flocalhost%2Findex.html&scope=openid%20profile%20extmainapi%20exttasksapi%20extfilebankapi%20extdocumentsapi&prompt=login&nonce=Iz3YGosnHu01DXbW3xwnicbRvqIr26AaWqmyrTZq

On the redirect_uri section, the uri that is going there it is incorrect because it is truncated, the redirect_uri is: http://localhost/index.html, if I change the redirect_uri on the browser to http://localhost/foo/index.html and navigate to that url I am able to access the site.

Am I missing something? The URL with more than one slash are not supported?

**Comment by brockallen** [comment]
> Am I missing something?

What do the logs tell you.

**Comment by CarlosSoria** [comment]
I was unable to activate the log probably doing something wrong there.

But after looking my code a little bit more, I was the one that was creating the redirectUri incorrectly, on my app.js file on angular I have the following:

` oauthService.redirectUri = $location.protocol() + '://' + $location.host() + port + '/index.html';`

There I was excluding the rest of the path.

I update this code to include the rest of the path

`       var pathName = $window.location.pathname;
        var pathNameIndex = pathName.indexOf('index.htm');     
        if (pathNameIndex !== -1) {
            pathName = pathName.substring(0, pathNameIndex);
        }
        if (pathName.slice(-1) !== '/') {
            pathName += '/';
        }
        oauthService.loginUrl = authConfig.loginUrl;
        oauthService.redirectUri = $location.protocol() + '://' + $location.host() + port + pathName + 'index.html';`

I think we could close this
