### ISSUE TITLE
Impersonation at Client Level

### ISSUE THREAD

**Issue by georgeslegros** [IdentityServer/IdentityServer3#3835]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I need te be able to impersonate a User at the app/client level.
The use case is as follow:
- User decides to publically share a dashboard (contains very frequently refreshed data, custom organisation, ...)
- User sends a link to someone else (that other person might not be a user of my app). The link contains the Id of the dashboard and some token to prevent people to just try things out.
- When the receiver browse to thte link we validate that the dashboard exist and that public sharing has been activated as well as the token.
- Then, based on the dashboard configuration, we need to call our API (with a Bearer token) in order to fetch the most recent data for the dashboard.

I would like to have the client app to be able to impersonnate the "owner" of the dashboard in order to be able to call the API on it's name to get the data.

I read other issues/tickets but they all mention a user impersonating another user but I could not find any evidence that it was actually possible to do what I'm looking for.

Could you drive me in the correct direction?

EDIT: I guess it's not useful to say that I don't want the receiver of the dashboard link to see any login screen, that should be completely transparent to him

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by georgeslegros** [comment]
Stackoverflow question posted [here](https://stackoverflow.com/questions/45913782/identityserver-impersonation-at-client-level).

Thanks.
