### ISSUE TITLE
No OIDC support to an upstream identity server

### ISSUE THREAD

**Issue by codyskidmore** [IdentityServer/IdentityServer3#3836]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Frequently, OIDC and OAuth2 are referenced interchangeably even though they are not the same.

I just need to confirm IdSrv3 has built in support for straight OAuth2 to an upstream identity server, and no extra configuration is required beyond what is in the documentation (and samples).
The upstream identity server does not support OIDC.

**Comment by brockallen** [comment]
Yes it's possible. You need to read the docs and samples, though, to learn how. 
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
