### ISSUE TITLE
Custom TokenHandleStore Key Uniqueness

### ISSUE THREAD

**Issue by haquex19** [IdentityServer/IdentityServer3#3838]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hello, I have a question on something I couldn't find on the docs. I have implemented a custom TokenHandleStore and a RefreshTokenStore. In the method "StoreAsync" a key is passed as an argument. Is this key guaranteed to be unique per token? Or is uniqueness considered to be key + subject?

**Comment by codyskidmore** [comment]
This might be helpful.
https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/5f132118e250f1253e4b9a96408ff74f6f7bc7b2/Source/Core.EntityFramework/Stores/RefreshTokenStore.cs

Note that the token is looked up using the key (passed as a parameter) and token type (refresh token). The Tokens table combines key and  type as a primary key.

**Comment by haquex19** [comment]
Thanks for the information. The link you provided looks like an implementation and it assumes the key is unique. I will go ahead and make the same assumption. This can be closed.
