### ISSUE TITLE
idsrv.partial cookie randomly not issued

### ISSUE THREAD

**Issue by pekkah** [IdentityServer/IdentityServer3#3839]
### Question / Issue
We have a setup with username/password login combination and a two factor authentication implemented as MVC view. We issue partial login  on  `PostAuthenticateAsync(PostAuthenticationContext context)`. We're now randomly facing a issue where the idsrv.partial login cookie is not issued or disappears so when `GetIdentityServerPartialLoginAsync` is called the return value is null. This issue seems to disappear upon IIS reset but comes back on fresh start of the application.

This issue seems to have appeared upon changing the .NET framework target to 4.6.1.

**Comment by brockallen** [comment]
Sounds like the perennial OWIN/Katana vs. ASP.NET cookie problem.

**Comment by pekkah** [comment]
It seems so. Katana 3.1.0 seems to allow changing the cookie manager implementation also providing few implementations like the system.web based one. You open for PR extending the cookieoptions to allow changing the  default one?

**Comment by brockallen** [comment]
We're no longer accepting PRs -- This repository is no longer in active development or maintenance, other than reported security vulnerabilities.

If you have questions and are seeking free support, see [here](http://docs.identityserver.io/en/release/intro/support.html#free-support) for more details.

If you require commercial support, see [here](http://docs.identityserver.io/en/release/intro/support.html#commercial-support) for more details.
