### ISSUE TITLE
Accessing HttpConfiguration

### ISSUE THREAD

**Issue by easygoingalex** [IdentityServer/IdentityServer3#3840]
I appreciate that #1933 covers this also, but was closed by the OP due to finding an OWIN solution to their problem.

I, on the other hand, could really do with access to the config. Or perhaps, have the ability to throw a pre-constructed HttpConfiguration at the Identity Server setup.

We're using an extensive shared library for diagnostics and auditing, currently none of which I can get working as it is not OWIN compatible and cannot be modified to be OWIN-centric due to its widespread use.

Having the ability to set up this stuff and then give IDS3 the pre-constructed config would, hopefully, save me a bucket load of hand cranked translation between your event service and our ETW/Event source.

It seem there is no sink for Serilog for EventSource which means, I'm stuck.

**Comment by easygoingalex** [comment]
From looking at the source, it would be as little as 2 or 3 code changes depending on how you would implement it (exc. UT):

Option a) Add "Config" to IdentityServerOptions
Option b) Add HttpConfiguration config as an optional param to "UseIdentityServer" and WebApiConfig.Configure

If not provided, the functionality remains unchanged e.g.

```
**WebApiConfig.cs**

// Option A
29:   HttpConfiguration httpConfiguration = options.Config ?? new HttpConfiguration();

//or

// Option B
27:public static HttpConfiguration Configure(IdentityServerOptions options, ILifetimeScope container, HttpConfiguration config = null)
28:{
29:   HttpConfiguration httpConfiguration = config ?? new HttpConfiguration();
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by easygoingalex** [comment]
More a suggestion to make the software a bit better by offering sightly more control to the software using Identity Server 3.
