### ISSUE TITLE
Is it possible to clean up old valid token from tokens sql table before generating new access token?

### ISSUE THREAD

**Issue by manojsitapara** [IdentityServer/IdentityServer3#3841]
I am using access token and token type is reference token with ClientCredentials flow to validate the clients with Entity Framework database. Client, scope & Secret data is stored into SQL database. Similar default implementation is done on below link
[https://github.com/IdentityServer/IdentityServer3.EntityFramework](https://github.com/IdentityServer/IdentityServer3.EntityFramework)

Now let's say first-time client request for the access token and authorization server return valid access token and it also inserts an entry into the tokens table, but due to some reason, the client has lost its access token.

Client again requests for the new access token from authorization server and again authorization server returns a valid access token to the client and also inserts the new token entry into the tokens table.

At this moment we have two valid access token for the same client.

For my scenario, one client should have only one access token, it should not have multiple valid tokens at the same time.

Is there any way to remove the older valid token from tokens table before generating the new access token? Note: I am using inbuilt entity framework support

I know there is abstract class `BaseTokenStore<T>` and it has method `RemoveAsync`, but not sure how can I use that?

There is API `TokenCleanup` which helps to clean up the expired token from tokens table, isn't there similar API which helps to clean up the older valid token from tokens table?

**Comment by brockallen** [comment]
You could do this, but you'd have to devise your own scheme for when it is triggered. You might be able to override one of our internal classes to do it as soon as the new token is created.

**Comment by manojsitapara** [comment]
Thanks for the quick reply. Can you please brief me about your suggested solution? 
Are you suggesting to use `ITokenHandleStore` by which I can implement to override all the methods? Or something different?

**Comment by brockallen** [comment]
Our interfaces might not model the kind of removal you want, so use whatever mechanism you have to get to the DB.
