### ISSUE TITLE
Change the SigninMessage Base Path

### ISSUE THREAD

**Issue by stefanodonofrio** [IdentityServer/IdentityServer3#3842]
Hi,
I would like to change the path of SignInMessage cookie.

I have something like this in the Startup class:
app.Map("/Identity", idsrvApp =>
        {
            idsrvApp.UseIdentityServer( new IdentityServerOptions{
                IssuerUri = Shared.Constants.AuthorityIdentityServer,
                SiteName = "SSO Idp",
                SigningCertificate = LoadCertificate(),
                Factory = factory});}

but I would like that the SignInMessage cookie is accessible even on "/". 

Do you have some suggestion

**Comment by brockallen** [comment]
> Do you have some suggestion

Unfortunately no, other than don't use the Map for IdentityServer.
