### ISSUE TITLE
Custom Identity Provider with IdS3 using Certificate Authentication for User

### ISSUE THREAD

**Issue by ganiths** [IdentityServer/IdentityServer3#3843]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I would like to create a custom identity provider in IDS3 that does user authentication by certificate. 

I have created a custom middleware which redirects me to a URL( protected in IIS  with require client certificate and SSL enabled). In the custom page i was able to validate the certificate and create the claims.But i could not find a way to pass those claims back to custom middleware.

Any help on this would be appreciated as i dont find any sample for doing user authentication by certificates.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
