### ISSUE TITLE
Logging with a custom logging framework based on log4net not working

### ISSUE THREAD

**Issue by githubber5** [IdentityServer/IdentityServer3#3844]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

Hello,

we use Log4Net in our web application for our logging.
But not directly. We created a custom logging-interface that abstracts all a logging framework should do. (So we can replace Log4Net with another logging framework if needed.)

The Log4Net configuration looks like this:
```
<log4net>
   <root>
      <level value="ALL" />
   </root>
   <logger name="VerboseLogger">
      <appender-ref ref="FilesAppender" />
      <level value="DEBUG" />
   </logger>
   <logger name="StandardLogger">
      <appender-ref ref="FilesAppender" />
      <level value="INFO" />
   </logger>
```
As you can see, in the root-node there is no appender or logger specified.
In our Logging-Framework we can configure the behaviour, and it works.

But with IdentityServer3 - nothing happens.

How can I use a custom Logging-Framework with IdentityServer?

I have read 
https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

But this does not helped.

I saw that I can register a custom EventService.

`factory.EventService = new Registration<IEventService, CustomEventService>();`

Explained here: https://leastprivilege.com/2015/10/22/identityserver3-logging-monitoring-using-serilog-and-seq/

After I figured out, that there are additional switches to enable EventService-Logging, it worked fine.

Is there a way to register a custom Logging-Framework for debugging?

**Update:**
I have read that creating a Serilog-Sink is a possibility, but since we have Log4Net my company will not allow another logging-framework.

It would be better if we can integrate a custom logging-framework without the necessity of another logging-framework.

Thank you for your help.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
