### ISSUE TITLE
Consulta sobre varios proyectos con un identity server3

### ISSUE THREAD

**Issue by JosueAngarita** [IdentityServer/IdentityServer3#3846]
Tengo instalado y configurado mi identityserver en un servidor y 3 proyectos adicionales se autentican con ese proyecto de seguridad, mi consulta es la siguiente porque si los 3 proyectos son independientes cuando me logueo en mi primera aplicacion automaticamente tengo acceso a las otras 3 o como hago para que mi proyecto con identityserver me mande a loguear cuando la aplicacion no sea la misma , ya que los claims que guarda son la informacion de la primera y eso me esta afectando. Gracias

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
