### ISSUE TITLE
Question: Using IdentityServer3 "side by side" with owin cookie auth?

### ISSUE THREAD

**Issue by rossiter10** [IdentityServer/IdentityServer3#3850]
Asked this on stackoverflow too, but didn't get any responses...

I'm new to SSO, so hopefully what I'm asking makes sense. So my current setup is a .NET MVC website using OWIN/cookies (`app.UseCookieAuthentication()`) and a custom user table (not ASP.NET Identity users).

So I'm wondering if I could add IdentityServer3 only for external providers, but leave all my existing user/authentication stuff as is for "local users". So I see that you can implement a custom IUserService to lookup users against your local database, and I think I got that working, but I'd like to even avoid that. And I'd like to avoid themeing the IdentityServer login screen. So something like this:

1. User hits up page with `[Authorize]` attribute.
2. User is redirected to my existing login page (not IdentityServer stuff)
3. Then my login page would have the external provider button(s) to login with external providers.

Is that possible? Or do you have to run your local users through IdentityServer3 also? I noticed I get an error if you don't provide a `IUserService `and don't use `UseInMemoryUsers()` either.

So from following various guides, I have this in my Startup.cs: `app.UseIdentityServer()`, `app.UseCookieAuthentication()`, and `app.UseOpenIdConnectAuthentication()` with Authority set to my IdentityServer endpoint.

Hopefully that made sense, Thanks!

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by rossiter10** [comment]
I did ask on SO two weeks ago and haven't got any responses :(
https://stackoverflow.com/questions/45887056/identityserver3-can-it-be-used-side-by-side-with-existing-users-authenticatio
