### ISSUE TITLE
How to call identityServer login post from my existing login controller

### ISSUE THREAD

**Issue by Ryan-Coates** [IdentityServer/IdentityServer3#3851]
### Question / Issue
Hi guys

I'm currently trying to connect my existing behaviour into IdentityServer.

What I want to happen is when I post my form back with username and password I can call my IdentityServer and authenticate in a single post request.

Are there existing helpers to support this?

Sorry If this has been asked I've been trawling around all day and haven't found anything.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
