### ISSUE TITLE
Error 400: Bad Request - Request Too Long still an issue 

### ISSUE THREAD

**Issue by callranjithkani** [IdentityServer/IdentityServer3#3855]
Hi,
Error 400: Bad Request - Request Too Long still an issue 
Have you got answer, me too face this same issue, my sso proxy developed by asp.net core 1.1 and few client applications also developed by core, if i try to implement 4.5.2 developed client app i faced Bad Request - Request Too Long Error, have any idea please let me know

- 

[ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
dup: https://github.com/IdentityServer/IdentityServer3/issues/2518
