### ISSUE TITLE
IdentityModel for IdentityServer3 Client calling IdentityServer4

### ISSUE THREAD

**Issue by DoubleExposure** [IdentityServer/IdentityServer3#3856]
I have a client application that works with IdentityServer3. I have changed the referenced information to point to IdentityServer4.  It fails with error IDX10803 below. Since both projects are based on OpenID Connection, shouldn't  IdentityServer3 IdentityModel components work when calling  IdentityServer4?

The remote certificate is invalid according to the validation procedure.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[AuthenticationException: The remote certificate is invalid according to the validation procedure.]
   System.Net.TlsStream.EndWrite(IAsyncResult asyncResult) +298
   System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar) +150

[WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.]
   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +764
   System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +78

[HttpRequestException: An error occurred while sending the request.]
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__0.MoveNext() +365

[IOException: Unable to get document from: https://qaquasaridentity4:449/.well-known/openid-configuration]
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__0.MoveNext() +734
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetAsync>d__0.MoveNext() +289
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__3.MoveNext() +915

[InvalidOperationException: IDX10803: Unable to create to obtain configuration from: 'https://qaquasaridentity4:449/.well-known/openid-configuration'.]

**Comment by brockallen** [comment]
This is a TLS trust issue with your HTTPS certificate, and not really an IdentityServer issue.

Search the archives or please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by DoubleExposure** [comment]
I just wanted ti confirm that I should not run into anything unusual using an IdentityServer3 Client components to talk to IdentityServer4 server.

**Comment by brockallen** [comment]
That should be fine. We have a repo that shows interop should work: https://github.com/IdentityServer/CrossVersionIntegrationTests
