### ISSUE TITLE
Endless loop while manually triggering Identity Server logout Url from browser History ?

### ISSUE THREAD

**Issue by mrbbm** [IdentityServer/IdentityServer3#3858]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I'm having a question, I got a Logout URL from the Browsers History

https://localhost:2025/core/logout?id=c1c646f3192dce2883f6e5e2f2ca9be8

The testing team traced this URL and tried to trigger, its causing endless redirects, whats the logic behind in this ? How to fix this ?

Moreover, in the Browsers history, we found the Login URL, it simply shows a blank screen

https://localhost:2025/core/login?signin=a84e5846c781b2bf63619efb97a76b43

How to handle these session-less URL's (Past URL's stored in Browser History with Ids) ?

Kindly assist me in this regards.

**Comment by brockallen** [comment]
dup: #3857
