### ISSUE TITLE
Error while specifying custom SigningCertificate 

### ISSUE THREAD

**Issue by Chuddeee** [IdentityServer/IdentityServer3#3859]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Hello, I have a problem with specifying custom SigningCertificate instead idsrv3test.pfx. I assign my certificate to Azure WebApp and reconfigure IdendtityServer in app, nut new app show 502 error per any request to site after deploy.

I've enabled logging but have no log entries in log files.
I don't know what is it. I'm compared idsrv3test.pfx and my pfx and found out few differences like signature algorithm(idsrv3test: sha1RSA - my certificate: sha256RSA), public key (idsrv3test: RSA (2048 Bits) - my certificate: RSA (4096 Bits)). 

Maybe it is my problem or something else?

**Comment by brockallen** [comment]
This has come up before in the archives. I don't recall the solution, but it's an azure issue not an IdentityServer issue.
