### ISSUE TITLE
Revoke all tokens from specified user

### ISSUE THREAD

**Issue by WILLYTV** [IdentityServer/IdentityServer3#3861]
(Identity Server 3)

### Question / Issue
Revoke all tokens (access_token) from specified user.
I m think cache all generated tokens and associated to specific user in application cache on identity server.
The idea is get all tokens from specific user in this cache and call revoke token operation to remove all granted access to specified user.

My requirement is revoke all access from specific user.

**Comment by brockallen** [comment]
Whatever store you're using for the reference tokens you would need to call it to delete the tokens.
