### ISSUE TITLE
Use Identity Server users to connect to Azure SQL Server

### ISSUE THREAD

**Issue by xabikos** [IdentityServer/IdentityServer3#3862]
### Question 
In a SaaS application hosted in Azure we use Identity Server as a centralized authentication/authorization place. It is a multitenant software suite and for every tenant we use a separate database, which is part of an elastic pool. For report generation reasons we would like our users to be able to connect to the database by using the same credentials as the ones in the application. 

We can connect to Azure SQL Server by using Azure Active Directory users and groups. The question is if can configure Azure Active Directory and Identity Server to support a scenario like this. To have a store that both Identity Server and Active Directory can trust. A note here is that a UI interaction cannot be part of this procedure as the BI platforms are not able to handle this workflow.

![image](https://user-images.githubusercontent.com/487416/30535845-4ac85744-9c6c-11e7-890d-08d12dcba6d1.png)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
