### ISSUE TITLE
Is it possible to load different brand templates based on client Id received via authorise url?

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer3#3863]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

I have two different clients registered. Is it possible to load different path for templates based on what clientId is received through authorise url?

If I have Microsoft client accessing SSO I want to show Microsoft logo and if I have apple client accessing I want to show Apple logo. How can I do that?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. Also, your question has been asked and discussed before so check the archives, or please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
