### ISSUE TITLE
Question: SSO for two native Apps

### ISSUE THREAD

**Issue by benaichouchem** [IdentityServer/IdentityServer3#3864]
- [*] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
Hello,

We have one App that works nicely on native (IOS, Android), and we want to add a new one that uses the same server. We have thought about:

- Each App has its own Refresh token / Access Token.

- We store the id_token in a shared account/place where both Apps can access.

**The use case is:** 

- User logs in in App 1

- User installs App 2, opens it

-  He is automatically logged in.

Question is: Does Identity server have support for getting a refresh token for App 2 by using the id_token? Do you have any recommandation on how to implement this?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
