### ISSUE TITLE
Sub claim in Client Credentials token

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer3#3865]
### Question / Issue
According to https://tools.ietf.org/html/rfc7523#section-3, a Client Credentials JWT MUST contain a sub claim with the value of client_id. (because there is no user involved)
As far as I know, this is not the case for a token requested at Identity Server 3.

Is there a reason not to follow the standard?

**Comment by senj** [comment]
Any update on this?

**Comment by leastprivilege** [comment]
You are reading the wrong spec. This is for tokens authentication the client. Not for access tokens.
