### ISSUE TITLE
401 Unauthorized when IdentityServer is deployed on IIS with a Host name

### ISSUE THREAD

**Issue by thejonamreddy** [IdentityServer/IdentityServer3#3867]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### 401 Unauthorized when IdentityServer is deployed on IIS with a Host name

Hi Team,

We are using IdentityServer3 implicit flow in our application. Here is the structure.

![image](https://user-images.githubusercontent.com/10164566/30695915-8809a238-9ef7-11e7-8b69-21bb6b417470.png)

In the above structure, the Client, ASP.NET Web API & STS are deployed as applications under the same website in IIS 8.

When the application is accessed using the machine name or the IP, everything works perfectly. However, when a host name is given to the site where the application is deployed Ex: www.xyz.com, Step 3 in the diagram fails with a 401 Unauthorized. 

We have tried debugging the issue, going through the logs etc. and so far no luck in finding the root cause.

Requesting your assistance.

Thank you,
Manoj

**Comment by KhalilMohammad** [comment]
I have the same scenario and same problem.

**Comment by brockallen** [comment]
Sounds like a deployment/environmental issue.

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
