### ISSUE TITLE
connect/token endpoint returns 405 (method not allowed) in Azure

### ISSUE THREAD

**Issue by farfush** [IdentityServer/IdentityServer3#3868]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
Have more a question than an issue.
Have IdentityServer3 in Azure as WorkerRole. Using OWIN self-hosting

CORS is throwing 405 from JS client (swagger) on connect/token endpoint in Azure. 

CORS is configured on IS3 side as **AllowAll**

It works locally with Azure simulator (use fiddler to simulate different domains) - sends OPTIONS request and received back proper headers from IS3.

Question. Did anyone face same issue with azure worker role?

**Comment by spelltwister** [comment]
I am also getting 405 after deploying to azure (in my case, an app service).  Works fine when deployed to IIS on a VM.  I'm also using OWIN.

**Comment by brockallen** [comment]
Check your azure logs.
