### ISSUE TITLE
Authenticate with Identity Server 3 as an Azure AD registered application

### ISSUE THREAD

**Issue by adamHarries87** [IdentityServer/IdentityServer3#3870]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I'm using Identity Server 3 with Azure AD middleware; it works well and I'm able to authenticate as a user via Azure AD. However, I'm trying to extend the implementation such that I can authenticate in a similar manner but as an Azure AD registered application rather than a user. The use case will involve a background application running and authenticating without user input. Has anyone managed to achieve something similar?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
