### ISSUE TITLE
Logout not working 

### ISSUE THREAD

**Issue by Yassine-Khechane** [IdentityServer/IdentityServer3#3871]
i have MVC client and identityserver3 with custom views.
in my MVC client to log out the user i invoke the action below to delete the cookies, it seems working but when i trie to access secured resources the user is automatically logged in.

`
        [HttpGet]
        public ActionResult LogoutIdentity()
        {
            if (IsAuthenticated)
            {
                Request.GetOwinContext().Authentication
                                        .SignOut(HttpContext.GetOwinContext()
                                        .Authentication.GetAuthenticationTypes()
                                        .Select(o => o.AuthenticationType).ToArray());

                Helper.ClearAllCookies();

            }
            return Redirect("home url");
        }`

**Comment by brockallen** [comment]
Not enough info.

**Comment by chris1234p** [comment]
@Yassine-Khechane your code shows you logging out of the client, however there is a session that exists on the identity server which must also be destroyed. You should redirect to the logout endpoint on the identity server instead of `Redirect("home url");`

see: https://identityserver.github.io/Documentation/docsv2/endpoints/endSession.html

**Comment by ifiwas** [comment]
I've same issue. How can i pass token_id_hint from client application ?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
