### ISSUE TITLE
Access token become invalid after the restart of the Service/IIS

### ISSUE THREAD

**Issue by nkdev89** [IdentityServer/IdentityServer3#3872]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue

I have hosted my identity Server 3 in IIS and recently Im facing an issue. And the issue is once the IIS restarts the access token issued before the restart becomes invalid after the restart . Please help or let me know how to handle this? . And it would be really helpful if someone share me a sample code.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Are you using reference tokens? Did you read about deployment considerations?

**Comment by nkdev89** [comment]
@brockallen Thanks for the quick reply, i implemented ITokenHandleStore and my issue is fixed.
