### ISSUE TITLE
POST username to password to identity server login page so application can start SSO session but without user interaction

### ISSUE THREAD

**Issue by chris1234p** [IdentityServer/IdentityServer3#3873]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Question: We have some third party applications that our users login to. Currently the third party applications POST the username and password to our application and they are logged in. We have recently implemented identityserver3 and SSO for a handful of our applications and want this functionality to continue to work. We have been trying out a few solutions and we are able to authenticate in a way similar to before by using password credentials grant, but this does not enable SSO which is something we need now. Are there any ways to achieve this? Could IdentityServer3 implement something where the credentials are POSTed directly to the identity server login page and then redirected so that the session is created but the end user does not have to login again?

Thanks

**Comment by brockallen** [comment]
IdentityServer implements XSRF to prevent this.

**Comment by chris1234p** [comment]
Is there any option to achieve SSO without the user entering the credentials directly on the IdSrv login screen?

**Comment by brockallen** [comment]
SSO is based on redirecting the user to the central SSO server.

**Comment by chris1234p** [comment]
That is fine - but is there a way to achieve SSO without the user having to enter their credentials on the identity server login screen? For example redirect to the SSO server and send their credentials or access token or something, have it start the SSO session, and then redirect back to the client app so that the session is started but no user interaction has occurred.

**Comment by brockallen** [comment]
> but is there a way to achieve SSO without the user having to enter their credentials on the identity server login screen

Not with OIDC.
