### ISSUE TITLE
Webforms + IdentityServer4

### ISSUE THREAD

**Issue by courtenayf** [IdentityServer/IdentityServer3#3875]
### Question / Issue

We have an old webforms site which has many business critical users using microsoft.aspnet.identity 2.2

We are wanting to extend the site, but will be using a microservice type architecture to do this. We want to spin up new .NET core services, but they need to be able to connect to this legacy database full of users. And by this I mean be able to share logins (so the user doesn't need to login twice btn the various microservices)

Is the best way to standup a IdentityServer (on its own somewhere - maybe hosted in AWS) which connects to this database and then allow:

1) The webforms to authenticate to it
2) Future .net core micro services can auth to it?

Currently we have this for our app:

`app.CreatePerOwinContext(ApplicationDbContext.Create);
            app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);
            app.CreatePerOwinContext<ApplicationSignInManager>(ApplicationSignInManager.Create);

            // Enable the application to use a cookie to store information for the signed in user
            // and to use a cookie to temporarily store information about a user logging in with a third party login provider
            // Configure the sign in cookie
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Account/Login"),
                SlidingExpiration = true,
                CookieName = ".AspNet.SomeName"
            });
            // Use a cookie to temporarily store information about a user logging in with a third party login provider
            app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);`

Or how is this best done?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
