### ISSUE TITLE
Multi Tenant IdSvr (single instance) with Multi Tenant Api (single instance) - needed mutiple authserver addresses

### ISSUE THREAD

**Issue by chdev77** [IdentityServer/IdentityServer3#3877]
We have IdSvr single instance with Web Api single instance that both support multi tenant.  Our web app is deployed to multiple domains with their own styling on each.  The business does not want them to be redirected to the IdSvr such as http://multiauth.identityserver.com.  They want to go from a website domain to the IdSvr using http://auth.websitedomain1.com and another would use http://auth.websitedomain2.com, etc

The issue is with the Web Api and setting up the Bearer authentication.
```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = Constants.BaseAddress,
                RequiredScopes = new[] { "cspwebapi" },

                // client credentials for the introspection endpoint
                ClientId = "cspclient",
                ClientSecret = "8BE96BA5-79F1-4FA4-8E41-6BCE7EA7090F",
            });
```

I can only specify http://multiauth.identityserver.com as the Authority and not multiple such as http://auth.websitedomain1.com and http://auth.websitedomain2.com.  The client gets a 401.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by chdev77** [comment]
Thanks again for the info
