### ISSUE TITLE
Question regarding prompt=select_account support

### ISSUE THREAD

**Issue by dzintaras** [IdentityServer/IdentityServer3#3884]
Hi,

I know IdSrv3 doesn't support prompt=select_account value and returns an error. Would it be possible to introduce its support as passing the value as part of SignInMessage with the intent to use it at custom IUserService implementation (probably in PreAuthenticateAsync/PostAuthenticateAsync methods).

The questions arises from implementing SSO solution based on impersonation by leveraging acr_values. But for external clients prompt=select_account looks like the one we should go according OIDC docs in my understanding. And would be "OIDC compliant" without custom logic. What would be your thoughts? 

Gintaras

**Comment by brockallen** [comment]
Sorry, we're not accepting any new feature requests at this time.
