### ISSUE TITLE
JWT/Signed UserInfo response

### ISSUE THREAD

**Issue by olegb2bsoft** [IdentityServer/IdentityServer3#3885]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question

Hi.
According to http://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse,  UserInfo can be in JWT format and signed. It is possible in ID3 ?

**Comment by leastprivilege** [comment]
No. And no plans of changing it. In IS4 you can take control over the rendering of the response yourself.
