### ISSUE TITLE
I could not manage the authorization role by custom userservice

### ISSUE THREAD

**Issue by ifiwas** [IdentityServer/IdentityServer3#3886]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question 
When I control the role with User.IsInRole("administrator") method is returns true.
But when I use the attribute as [Authorize(Roles="administrator"] the service returns the unauthorized error.

Could you tell me what I'm missing?

I've created custom user service as below;

`    public class UserService : UserServiceBase
    {
        public List<User> Users { get; set; }
        private AbstractDepperRepository Repository { get; }

        public UserService()
        {
            Repository = new DapperRepository("DefaultConnection");
            Users = Repository.GetAllItems<User>(Queries.AuthenticationQueries.GetAllUsers).ToList();
            foreach (var user in Users)
            {
                user.SetRepository(Repository);
            }
        }
        public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            var user = Users.SingleOrDefault(x => x.UserName == context.UserName && x.Password.GetAesDecryptedString() == context.Password);
            if (user != null)
            {
                var claims = new List<Claim>();
                if (user.Roles.Any())
                {
                    claims.AddRange(user.Roles.Select(r => new Claim(Constants.ClaimTypes.Role, r.Name)));
                }
                claims.AddRange(new[]
                {
                    new Claim(Constants.ClaimTypes.GivenName, user.FirstName??""),
                    new Claim(Constants.ClaimTypes.Email, user.Email??""),
                    new Claim(Constants.ClaimTypes.FamilyName, user.LastName??"")
                });
                user.Claims = claims;
                context.AuthenticateResult = new AuthenticateResult(user.UserId.ToString(), user.UserName, claims);
            }

            return Task.FromResult(0);
        }

        public override Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            // issue the claims for the user
            var user = Users.SingleOrDefault(x => x.UserId == Guid.Parse(context.Subject.GetSubjectId()));
            if (user != null)
            {
                context.IssuedClaims = user.Claims.Where(x => context.RequestedClaimTypes.Contains(x.Type));
            }

            return Task.FromResult(0);
        }`

Here is my OpenID connect startup code;

`  public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
            #region IdentityServer3 Startup Configuration
            var factory = new IdentityServerServiceFactory()
                   .UseInMemoryScopes(Scopes.Get());
            var clientStore = new Clients();
            var scopeStore = new Scopes();
            var userService = new UserService();
            factory.ClientStore = new Registration<IClientStore>(resolver => clientStore);
            factory.ScopeStore = new Registration<IScopeStore>(resolver => scopeStore);
            factory.UserService = new Registration<IUserService>(resolver => userService);
            app.Map("/identity", idsrvApp =>
            {
                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Favori IdentityServer",
                    SigningCertificate = Certificate.Get(),
                    Factory = factory
                });
            });
            #endregion

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://localhost:44335/identity",
                ClientId = "favoritedarikciportaliwebclient",
                //ClientSecret = "Fvr8029".Sha256(),
                RedirectUri = "https://localhost:44335/",
                ResponseType = "id_token token",
                SignInAsAuthenticationType = "Cookies",
                Scope = "openid profile roles ftpwebapi",
                UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = async n =>
                    {
                        

                        var nid = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType,
                            Constants.ClaimTypes.GivenName, Constants.ClaimTypes.Role);

                        //get user info data
                        var userInfoClient = new UserInfoClient(new Uri($"{n.Options.Authority}/connect/userinfo"),
                            n.ProtocolMessage.AccessToken);

                        var userInfo = await userInfoClient.GetAsync();
                        userInfo.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Item1, ui.Item2)));
                        var id = n.AuthenticationTicket.Identity;
                        var givenName = id.FindFirst(Constants.ClaimTypes.GivenName);
                        var familyName = id.FindFirst(Constants.ClaimTypes.FamilyName);
                        var sub = id.FindFirst("sub");
                        var roles = id.FindAll(Constants.ClaimTypes.Role);

                        if (givenName != null)
                            nid.AddClaim(givenName);
                        if (familyName != null)
                            nid.AddClaim(familyName);
                        if (sub != null)
                            nid.AddClaim(sub);
                        if (roles != null)
                            nid.AddClaims(roles);

                        //keep the id_token for logout
                        nid.AddClaim(new Claim("id_token", n.ProtocolMessage.AccessToken));

                        //add access token
                        nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));

                        //keep track access token expirtion
                        nid.AddClaim(new Claim("expires_at", n.ProtocolMessage.ExpiresIn));

                        //add some app spesific data
                        nid.AddClaim(new Claim("app_spesific", "some data"));

                        n.AuthenticationTicket = new AuthenticationTicket(nid, n.AuthenticationTicket.Properties);
                    },
                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }

                        }
                        return Task.FromResult(0);

                    }
                }

            });

        }
    }`

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Perhaps relevant: https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by ifiwas** [comment]
Hi,

Thanks for the answer. Now I'm getting roles identity claims. But there is something missing in my code. The authorization attributes still not working.

I guess I may not manage the claims transformation.

Best wishes.

**Comment by ifiwas** [comment]
Hi,

My authenticated results like below;

Why my role is like "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" ?

[
  {
    "type": "iss",
    "value": "https://localhost:44335/identity"
  },
  {
    "type": "aud",
    "value": "https://localhost:44335/identity/resources"
  },
  {
    "type": "exp",
    "value": "1508490239"
  },
  {
    "type": "nbf",
    "value": "1508486639"
  },
  {
    "type": "client_id",
    "value": "favoritedarikciportaliwebclient"
  },
  {
    "type": "scope",
    "value": "openid"
  },
  {
    "type": "scope",
    "value": "profile"
  },
  {
    "type": "scope",
    "value": "roles"
  },
  {
    "type": "scope",
    "value": "ftpwebapi"
  },
  {
    "type": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
    "value": "e599e4e9-7644-411b-b5fa-87fcd93c0775"
  },
  {
    "type": "http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant",
    "value": "1508486639"
  },
  {
    "type": "http://schemas.microsoft.com/identity/claims/identityprovider",
    "value": "idsrv"
  },
  {
    **"type": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",**
    "value": "administrator"
  },
  {
    **"type": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",**
    "value": "Api Erisim"
  },
  {
    "type": "http://schemas.microsoft.com/claims/authnmethodsreferences",
    "value": "password"
  }
]

**Comment by brockallen** [comment]
Yes, you forgot to clear the stupid jwt security token handler default inbound claim type map. It's all in the samples.

**Comment by ifiwas** [comment]
Thanks for your answer but still something missing in my project :( I got the same result again after inboudclaimstypemap cleared.

`public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject;
            **JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();**
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            #region IdentityServer3 Startup Configuration
            var factory = new IdentityServerServiceFactory()
                   .UseInMemoryScopes(Scopes.Get());
            var clientStore = new Clients();
            var scopeStore = new Scopes();
            var userService = new UserService();
            factory.ClientStore = new Registration<IClientStore>(resolver => clientStore);
            factory.ScopeStore = new Registration<IScopeStore>(resolver => scopeStore);
            factory.UserService = new Registration<IUserService>(resolver => userService);
            app.Map("/identity", idsrvApp =>
            {
                idsrvApp.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Favori IdentityServer",
                    SigningCertificate = Certificate.Get(),
                    Factory = factory,
                    AuthenticationOptions = new IdentityServer3.Core.Configuration.AuthenticationOptions
                    {
                        EnablePostSignOutAutoRedirect = true
                    }
                });
            });
            #endregion

            app.UseResourceAuthorization(new AuthorizationManager());
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://localhost:44335/identity",

                ClientId = "favoritedarikciportaliwebclient",
                Scope = "openid profile roles ftpwebapi",
                RedirectUri = "https://localhost:44335/",
                ResponseType = "id_token token",

                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated =async n =>
                    {

                        var nid = new ClaimsIdentity(
                            n.AuthenticationTicket.Identity.AuthenticationType,
                            Constants.ClaimTypes.GivenName,
                            Constants.ClaimTypes.Role);

                        // get userinfo data
                        var userInfoClient = new UserInfoClient(
                            new Uri(n.Options.Authority + "/connect/userinfo"),
                            n.ProtocolMessage.AccessToken);

                        var userInfo = await userInfoClient.GetAsync();
                        userInfo.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Item1, ui.Item2)));

                        // keep the id_token for logout
                        nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));

                        // add access token for sample API
                        nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));

                        // keep track of access token expiration
                        nid.AddClaim(new Claim("expires_at", DateTimeOffset.Now.AddSeconds(int.Parse(n.ProtocolMessage.ExpiresIn)).ToString()));

                        // add some other app specific claim
                        nid.AddClaim(new Claim("app_specific", "some data"));

                        n.AuthenticationTicket = new AuthenticationTicket(
                            nid,
                            n.AuthenticationTicket.Properties);
                    },
                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }

                        }
                        return Task.FromResult(0);

                    }
                }

            });


        }
    }`

**Comment by brockallen** [comment]
I'd suggest putting a break point in your `SecurityTokenValidated` and walking thru that code. Perhaps you're not merging the claims from the id_token and the userinfo endpoint?

**Comment by ifiwas** [comment]
Hi,

Which code should merge the claims from the id_token and the userinfo endpoint?

I've used the sample codes the following [link](https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html) 

I'think I'll rewatch pluralsight videos again :)

**Comment by brockallen** [comment]
> Which code should merge the claims from the id_token and the userinfo endpoint?

The code in the `SecurityTokenValidated` event.

**Comment by ifiwas** [comment]
Hi, I've found something missing in my web API part of my project.

UseClaimsTransformation cannot resolve. What is the missing reference?

`  app.UseClaimsTransformation(incoming =>
            {
                // either add claims to incoming, or create new principal
                var appPrincipal = new ClaimsPrincipal(incoming);
                incoming.Identities.First().AddClaim(new Claim("appSpecific", "some_value"));

                return Task.FromResult(appPrincipal);
            });`

**Comment by ifiwas** [comment]
Hi, Again.

I've downloaded sample codes and run on my pc. It works as my project. 

I've just changed Authorize attribute of IdentityController in API project. It also does not work as like my project. It gives 401 error even the user boo has the role.

![authorizeattribute](https://user-images.githubusercontent.com/23165039/31902166-8eacb7d0-b82c-11e7-9cdd-3583d8c47b9d.png)

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/
