### ISSUE TITLE
How can I change Login page navbar link

### ISSUE THREAD

**Issue by bayramucuncu** [IdentityServer/IdentityServer3#3888]
IdentitiyServer login page has a navbar. And site name link that on navbar routes user wo Welcome page. How can I  change url target url of this link? Maybe I will disable welcome page.

**Comment by brockallen** [comment]
Customize the templates, as per the docs.

**Comment by bayramucuncu** [comment]
Is there a specific  html template for every single page? Or created a master page and sub pages under it? How can I find navbar container template?

**Comment by brockallen** [comment]
Did the docs not cover it? https://identityserver.github.io/Documentation/docsv2/advanced/DefaultViewService.html
