### ISSUE TITLE
User X509 certificate

### ISSUE THREAD

**Issue by Thercy** [IdentityServer/IdentityServer3#3890]
- [X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question
I am working with IdentityServer3 and I need the user to authenticate using a X509 certificate (instead of user/pass). I am trying to achieve this through a Partial Login implementing IUserService (on the PreAuthenticateAsync), but so far it looks like there is no possible option to request this from the "PreAuthenticationContext context" (open the browser X509 user certificate store so the user selects one and proceed). However, I have read in some posts this should be available on IdentityServer3. 

Many thanks in advance!

**Comment by brockallen** [comment]
Use PreAuth, do a partial login to your own custom page, on that custom page do the Challenge to request the client/user cert, once validated then use the OWIN extension methods to issue the IdSvr cookie.

https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by Thercy** [comment]
Thanks! I do have the parts needed, but I cannot see how to put them together. Is there any example I could check on how I could use the partial login to redirect to a custom page to perform the challenge request for the certificate? 
Many thanks.

**Comment by brockallen** [comment]
Nothing exactly like what you want, but this might be the closest: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomLoginPage/CustomLoginPage

**Comment by Thercy** [comment]
Spot on! that's exactly the example project where I am currently working on.  However, at the moment I'm stuck on getting the user certificate authentication into the OWIN middleware chain from my custom login page. Guess this is the path I should go? I'll try and post with any update!

**Comment by brockallen** [comment]
> stuck on getting the user certificate authentication into the OWIN middleware chain

Well, that's unrelated to IdSvr -- you need to figure that one out separately. IIRC, there's a web,config entry to have IIS do that handshake.

**Comment by Thercy** [comment]
Cool! I'll close the ticket now. I'll try and post my findings :)
