### ISSUE TITLE
How to get all active clients for current session

### ISSUE THREAD

**Issue by GitCorne** [IdentityServer/IdentityServer3#3891]
### Question
Hi,

Is it possible to get a list of active clients for an current session? I want to notify all (active) clients when the claimvalues have to be updated, for example when some profile properties are changed (email, etc.).

I figured out that there is a simliar mechanism by single sign out. The list of iFrameUrls contains only the urls of the active clients, not all configured client applications. I can't find out how this iFrameUrls collection is populated exactly, maybe based on session cookie?

Are there other ways to update the claim of already issued id_tokens? I found something about reference tokens (and the possibility of introspection of it), but that's for access tokens, not for id_tokens.

**Comment by brockallen** [comment]
Nothing public, but here's the internal implementation: https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/Hosting/ClientListCookie.cs
