### ISSUE TITLE
Need to change the validation message when login

### ISSUE THREAD

**Issue by khadar439** [IdentityServer/IdentityServer3#3893]
hi 
I am using identity server 3 with Membership reboot
we are using the feature account Lockout on  Failed Login Attempts 
this feature is working fine but the problem is with the validation message ,
If the account is locked it should show validation like 'Your account is locked ',
but it still showing  'Invalid username or password'
can any one tell me how to change this validation message , because our requirement is to show the validation message like 'Your account is locked '

Thank you

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
