### ISSUE TITLE
Mixed authentication MVC controller

### ISSUE THREAD

**Issue by gilm0079** [IdentityServer/IdentityServer3#3894]
I have a MVC controller that I want users to access anonymously as well as if they are authenticated.  Think of it like a page that has public information on it, but if you are authenticated then you get more functionality.  Currently it was using the [AllowAnonymous] attribute to allow the users to access the controller action.  Now we are adding the logic to give more functionality to those that are authenticated.  What I'm finding is that an authenticated user's (ClaimsPrincipal)User object is not being initialized when they enter this action.  From what I'm reading the AuthorizeAttribute (or ResourceAuthorizeAttribute) has to be used to make this initialization happen.  (we use the IdSvr3 MVC ResourceAuthorize).  If I use this then I would suspect we would be blocking unauthenticated users from accessing this controller action though.  

How do we enable a request to access a controller action if they are both anonymous or authenticated (as we want the ClaimsPrincipal User in this case)?  Does the ResourceAuthorize have some overload to skip the authorization if it isn't found and continue on instead of rejecting with a 403?  or can we extend this Attribute class to allow for this in specific cases?

Hopefully this makes sense of what I'm trying to accomplish.

**Comment by gilm0079** [comment]
I don't have a ideal solution yet, but I did find a work around if anyone is having the same issue.  If I omit a MVC action filter attribute for authorization and instead put a HttpContext.CheckAccess() at the beginning of the action method before I make use of the ClaimsPrincipal User it seems to work and the CheckAccess Method doesn't force returning a 401/403 if the check fails so I can use the method for both authenticated and unauthenticated access while having access to the User object when available.

I have seen posts about putting options on a custom AuthorizeAttribute filter (not related to IdSvr) that would essentially skip Authorization on a failure instead of returning a 401/403, but I haven't tried to make a custom ResourceAuthorizeAttribute filter yet.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
