### ISSUE TITLE
Force users to login for authorization endpoint

### ISSUE THREAD

**Issue by Kahbazi** [IdentityServer/IdentityServer3#3895]
Hi, is there anyway from server side to force users to Login for every request to authorization endpoint beside using `prompt=login`?

**Comment by brockallen** [comment]
Change the cookie lifetime to be very very short in IdSvr.

**Comment by Kahbazi** [comment]
Thanks. That was my first solution, but I couldn't do this because of security issues.
This is what I write, and I really appreciate you giving your opinion about my solution.

In IdentityServer I disabled `LocalLogin` and write an external Login Provider. whenever a user login successfully via login provider I add `signinid` to user's claims and to a static `List`.

I also write a middleware and put it between IdentityServer Cookie Authentication and IdentityServer WebApi. In this middleware I get `signinid` from claims and check if it does not exists in the `List` I add the `prompt=login`  QueryString.

Do you think this is a good idea?

**Comment by brockallen** [comment]
Really not sure... I'd have to work thru your scenario. Sorry.

**Comment by Kahbazi** [comment]
ok, thanks.
