### ISSUE TITLE
IdentityServer3

### ISSUE THREAD

**Issue by satya2637** [IdentityServer/IdentityServer3#3896]
please Explain How to  implementation IdentityServer3 ,oauth2 with data stored in Entityframework

**Comment by Kahbazi** [comment]
You can check this sample https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/EntityFramework

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
