### ISSUE TITLE
Logout Problem with MvcViewService Implementation

### ISSUE THREAD

**Issue by ifiwas** [IdentityServer/IdentityServer3#3897]
Hi,

I have got a problem when I try to log out.

I've used MvcEmbeded model to the identity server authentication process.

Here is the code that I used to log out

` public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index", "Home");
        }`

Here is the result when it triggered.
Redirected to the url("https://localhost:44335/identity/logout?id=3f23f20c0368a3b805ff7e9048bf45dc")
{"Message":"An error has occurred.","ExceptionMessage":"The model item passed into the dictionary is of type 'System.Web.Mvc.HandleErrorInfo', but this dictionary requires a model item of type 'IdentityServer3.Core.ViewModels.ErrorViewModel'.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.Web.Mvc.ViewDataDictionary`1.SetModel(Object value)\r\n   at System.Web.Mvc.ViewDataDictionary..ctor(ViewDataDictionary dictionary)\r\n   at System.Web.Mvc.WebViewPage`1.SetViewData(ViewDataDictionary viewData)\r\n   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)\r\n   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)\r\n   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)\r\n   at System.Web.Mvc.Controller.ExecuteCore()\r\n   at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)\r\n   at System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext)\r\n   at FavoriTedarikciPortali.WVC.Services.MvcViewService`1.ExecuteAction(ControllerBase controller, ActionDescriptor actionDescriptor, Object model, Object message) in D:\\Source\\Favori\\DEV\\FavoriTedarikciPortali.WVC\\Services\\MvcViewService.cs:line 587\r\n   at FavoriTedarikciPortali.WVC.Services.MvcViewService`1.GenerateHtml(String actionName, Object model, Object message) in D:\\Source\\Favori\\DEV\\FavoriTedarikciPortali.WVC\\Services\\MvcViewService.cs:line 291\r\n   at FavoriTedarikciPortali.WVC.Services.MvcViewService`1.GenerateStream[TViewModel,TMessage](TViewModel model, TMessage message, String actionName, Func`1 fallbackFunc) in D:\\Source\\Favori\\DEV\\FavoriTedarikciPortali.WVC\\Services\\MvcViewService.cs:line 220\r\n   at FavoriTedarikciPortali.WVC.Services.MvcViewService`1.GenerateStream[TViewModel](TViewModel model, String actionName, Func`1 fallbackFunc) in D:\\Source\\Favori\\DEV\\FavoriTedarikciPortali.WVC\\Services\\MvcViewService.cs:line 250\r\n   at FavoriTedarikciPortali.WVC.Services.MvcViewService`1.Error(ErrorViewModel model) in D:\\Source\\Favori\\DEV\\FavoriTedarikciPortali.WVC\\Services\\MvcViewService.cs:line 192\r\n   at IdentityServer3.Core.Results.ErrorActionResult.<>c__DisplayClass2.<<.ctor>b__0>d__4.MoveNext() in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\Results\\ErrorActionResult.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer3.Core.Results.HtmlStreamActionResult.<Render>d__0.MoveNext() in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\Results\\HtmlStreamActionResult.cs:line 37\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer3.Core.Results.HtmlStreamActionResult.<GetResponseMessage>d__5.MoveNext() in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\Results\\HtmlStreamActionResult.cs:line 42\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer3.Core.Configuration.Hosting.ErrorPageFilterAttribute.<OnExceptionAsync>d__1.MoveNext() in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\Configuration\\Hosting\\ErrorPageFilterAttribute.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ExceptionFilterAttribute.<ExecuteExceptionFilterAsyncCore>d__0.MoveNext() in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\Configuration\\Hosting\\NoCacheAttribute.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\Configuration\\Hosting\\NoCacheAttribute.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\\ballen\\github\\identity\\IdSrv3\\IdentityServer3\\source\\Core\\Configuration\\Hosting\\NoCacheAttribute.cs:line 0"}

Best Regards

**Comment by brockallen** [comment]
This repository is no longer in active development or maintenance, other than reported security vulnerabilities.

If you have questions and are seeking free support, see [here](http://docs.identityserver.io/en/release/intro/support.html#free-support) for more details.

If you require commercial support, see [here](http://docs.identityserver.io/en/release/intro/support.html#commercial-support) for more details.
