### ISSUE TITLE
How to set strong password restriction

### ISSUE THREAD

**Issue by sundarkurs** [IdentityServer/IdentityServer3#3898]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
How to implement the validation for strong password restriction.

I need to set the restrictions as below,
It should have minimum of 8 characters and must contain following 3 types of characters,
lower case letters (i.e. a-z)
upper case letters (i.e. A-Z)
numbers (i.e. 0-9)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
