### ISSUE TITLE
How to sign my JWT using Firebase private key to integrate with IdentityServer

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3#3899]
I need to integrate my authentication server which is implemented using IdentityServer3 with Firebase services via JWT as described here:

[https://firebase.google.com/docs/auth/android/custom-auth](https://firebase.google.com/docs/auth/android/custom-auth)

Here google said:

> Copy the new service account's public/private key pair JSON file to your authentication server and sign the tokens with it.

Sample (Not exact) JSON file:

```
{
  "type": "service_account",
  "project_id": "xxx-c4004",
  "private_key_id": ".....",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIE.....\n-----END PRIVATE KEY-----\n",
  "client_email": ".....",
  "client_id": "....",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-.....com"
}
```

In my IdentityServer I have a resource owner client that generates JWT tokens but i signed the IdToken and the AccessToken by a .pfx file and i load it like below:

```
 /// <summary>
    /// Load the certificate that sign the Id or Jw token
    /// </summary>
    /// <returns></returns>
    private static X509Certificate2 LoadCertificate()
    {
        string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
        return new X509Certificate2(
        Path.Combine(AppDomain.CurrentDomain.BaseDirectory, ConfigMngr.GetAppSettingsValue<string>("IdSrv:SigningCertificatePath")), ConfigMngr.GetAppSettingsValue<string>("IdSrv:SigningCertificatePassword"));
    }
```
And then I assign it to the SigningCertificate property in IdentityServer OWIN configs.

I don't know how can i sign the token using the JSON file and also Google didn't describe much about that.

I created another method to exreact private key and send it as bytes to the X509Certificate2 constructor but it didn't works:
```
private static X509Certificate2 LoadJsonCert()
        {
            string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
            var jsonFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "bin\\IdentityServer\\FirebaseCert\\mycert.json");

            FirebaseJsonCert firebaseJsonCert = null;
            using (StreamReader r = new StreamReader(jsonFile))
            {
                string json = r.ReadToEnd();
                firebaseJsonCert  = JsonConvert.DeserializeObject<FirebaseJsonCert>(json);
            }

            var header = String.Format("-----BEGIN PRIVATE KEY-----");
            var footer = String.Format("-----END PRIVATE KEY-----");

            var start = firebaseJsonCert.private_key.IndexOf(header, StringComparison.Ordinal);
            if (start < 0)
                return null;

            start += header.Length;
            var end = firebaseJsonCert.private_key.IndexOf(footer, start, StringComparison.Ordinal) - start;

            if (end < 0)
                return null;

            byte[] certBuffer = Convert.FromBase64String(firebaseJsonCert.private_key.Substring(start, end));

            return new X509Certificate2(certBuffer);

        }
```
It fires an exception:

> {"Cannot find the requested object.\r\n"}

With StackTrace:

> at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertBlobType(Byte[] rawData) at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags) at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData) at ... (my code)

I tried to ask google, checking JWT original documentations about encryption and etc. Also asking on SO here: 

[https://stackoverflow.com/questions/47086254/how-to-sign-my-jwt-using-firebase-private-key-to-integrate-with-identityserver](https://stackoverflow.com/questions/47086254/how-to-sign-my-jwt-using-firebase-private-key-to-integrate-with-identityserver)

but with no chance to help.

Is it a way to give me a refrance or a way how to do this correctly?

Thanks very much

**Comment by brockallen** [comment]
This repository is no longer in active development or maintenance, other than reported security vulnerabilities.

If you have questions and are seeking free support, see [here](http://docs.identityserver.io/en/release/intro/support.html#free-support) for more details.

If you require commercial support, see [here](http://docs.identityserver.io/en/release/intro/support.html#commercial-support) for more details.
