### ISSUE TITLE
React native client example?

### ISSUE THREAD

**Issue by tienw** [IdentityServer/IdentityServer3#3905]
We recently switch from Cordova to React native. so  I am wondering if you have any sample code for react native to connect to Ideneity Server 3.0 or suggestion of using other library to do so?  Thanks

**Comment by brockallen** [comment]
This repository is no longer in active development or maintenance, other than reported security vulnerabilities.

If you have questions and are seeking free support, see [here](http://docs.identityserver.io/en/release/intro/support.html#free-support) for more details.

If you require commercial support, see [here](http://docs.identityserver.io/en/release/intro/support.html#commercial-support) for more details.
