### ISSUE TITLE
Bypass Login for LocalRegistrationUserService 

### ISSUE THREAD

**Issue by esko22** [IdentityServer/IdentityServer3#563]
Had a question to see if it possible to bypass the need to redirect a newly registered user to the login page when using a custom user service for local account creation.

I am hosting a registration page off of "/core/registration" via Nancy that successfully adds a new user and redirects to login page successfully based on the sample provided. I've had a few people complain about having to login after registering their account. I was digging around and I am not really seeing an easy way to do this similar to ProcessNewExternalAccountAsync.

I am able to successful call the AuthLocalAsync immediately after creation but it looks like I need to be able to execute something like SignInAndRedirect in AuthenitcationController , basically what the post to the login controller does.

Not sure if I am completely overlooking something obvious here but any guidance or if this is even possible would be great.

Thanks

**Comment by esko22** [comment]
Recently I was able to get some time to update to the latest and greatest...

Hit 2 snags, first one being with the code referenced above... 

The constructor on MessageCookie is now marked internal so I can't create an instance to pass into AuthenticateLocalAsync nor get my returnUrl for redirect. I know this was somewhat of a hack so is there a new approach I should be taking? 

The second issue is another awesome migration issue with MySql... I will probably never use EF with MySql ever again... I cannot begin to count the wasted hours on MySql.Data.Entity.EF6 bugs... Not your problem but just FYI,  DateTimeOffset used for expiration in the ClientSecret entity is not supported yet.

**Comment by leastprivilege** [comment]
any updated?

**Comment by esko22** [comment]
I was actually hoping to get some guidance from you guys on this...

Since the constructor on MessageCookie is now marked internal, I can't create an instance to pass into AuthenticateLocalAsync nor get my returnUrl for redirect so my previous work around for auto-login after registration does not work. I know this was somewhat of a hack so is there a new approach I should be taking?

**Comment by brockallen** [comment]
We added an extension method in 1.3 to allow you to issue the authentication cookie.

**Comment by esko22** [comment]
Got it. Thanks!

**Comment by bartbarcicki** [comment]
I'm struggling to find the extension method to issue an authentication cookie. Am I missing something obvious or was this removed?
