### ISSUE TITLE
Consider HPKP

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#758]
https://tools.ietf.org/html/draft-ietf-websec-key-pinning-21
https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning

**Comment by chliebel** [comment]
HTTP Public Key Pinning (HPKP) is an extension for HTTP that allows a client to check if the certificate used to encrypt the website's content matches a list of allowed certificate/public key fingerprints defined by the website's creator in the `Public-Key-Pinning` header. HPKP can be used to restrict HTTPS access to a certain domain to specific certificates, including intermediate or root certificates. If the certificate is changed by an attacker, the fingerprint also changes and the browser is able to detect the fraud, even if the trust path would be perfectly valid.

While HPKP is no official standard (yet!), it's already supported by Google Chrome and, in its latest release, Mozilla Firefox. HPKP was developed by some guys at Google.

Just like HSTS, HPKP headers can only be set when the page is accessed using an error-free secure connection. Furthermore, you can specify a maximum age for the HPKP entries cached by the browser or choose to include subdomains. Newer headers always update cached ones.

Quite interesting: If the browser detects a violation of this policy, it can optionally send a JSON-based report to an URL specified in the HPKP header, so the website's creator gets informed of possible fraud attempts. However, these reports can be faked or get intercepted by an attacker.

Drawbacks: The first visit of a site protected by HPKP can still be manipulated, as the client has no cached public key pins at that point of time. In addition, the user has to take care that he serves his website using the designated certificate for the duration defined in the `max-age` directive. This is especially important if the user uses the `localhost` hostname for development.

Additional links:
* https://timtaubert.de/blog/2014/10/http-public-key-pinning-explained/
* https://raymii.org/s/articles/HTTP_Public_Key_Pinning_Extension_HPKP.html

**Comment by brockallen** [comment]
Like HSTS, isn't this more of a host concern and not so much an IdSvr feature? Perhaps we should do some middleware in IdentityModel for this instead?

**Comment by chliebel** [comment]
Yes, that’s definitely the more elegant way.

**Comment by brockallen** [comment]
I think we can close this as nofix?

**Comment by leastprivilege** [comment]
yes
