### ISSUE TITLE
Move ICustomRequestValidator to a point where resulting claims are known?

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#776]

**Comment by leastprivilege** [comment]
maybe two extensibility points are needed - one before claims generation (directly after protocol validation) - one after (but possibly before any artifacts have been created - e.g. authZ codes or token handles). postponed.

**Comment by parkinsona** [comment]
2 extensibility points would be great for my needs. The "after" one makes sense to do before creating artifacts.

**Comment by parkinsona** [comment]
Did this get implemented? If so, which release includes the functionality.

**Comment by leastprivilege** [comment]
no.
