### ISSUE TITLE
Add more details to endpoint events

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#860]

**Comment by brockallen** [comment]
I started looking at this -- it seems that the validation methods are logging details, but that string needs to be captured and returned back up to the eventing system.

**Comment by brockallen** [comment]
And just to clarify -- it just seems that the `RaiseFailureEndpointEventAsync` is the main one that needs enriching -- the rest AFAICT are providing good specifics via the error param.
