### ISSUE TITLE
'address' claim handled differently in Id Token and UserInfo endpoint.

### ISSUE THREAD

**Issue by mryandot** [IdentityServer/IdentityServer3#879]
As with #872, the IdToken and UserInfo serializations differ.  In this case the `address` claim is serialized in the UserInfo endpoint as a JSON Object, as stated in the spec, but is serialized in the id token as a string containing text that would represent a JSON Object.  The spec defines `address` as a JSON Object, so I'm assuming the UserInfo encoding is correct.

### UserInfo
```Javascript
  "address": {
    "street_address": "One Hacker Way",
    "locality": "Heidelberg",
    "postal_code": 69118,
    "country": "Germany"
  },
```
### IdToken
```Javascript
  "address": "{ \"street_address\": \"One Hacker Way\", \"locality\": \"Heidelberg\", \"postal_code\": 69118, \"country\": \"Germany\" }",
```

**Comment by wiseman13** [comment]
I am seeing the same behavior. Is the issue that the address claim is not being properly serialized into the id_Token?

**Comment by leastprivilege** [comment]
I finally find some time to fix this - check this branch

https://github.com/IdentityServer/IdentityServer3/tree/EnhancedTokenSigningService

and give feedback here

https://github.com/IdentityServer/IdentityServer3/issues/2088
