### ISSUE TITLE
Replace access token validation endpoint with token introspection endpoint

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#880]
https://datatracker.ietf.org/doc/draft-ietf-oauth-introspection/

**Comment by TD49** [comment]
+1
Please confirm that IdSvr3 will NOT require a Client Id/Secret in the header for introspection requests.

**Comment by leastprivilege** [comment]
The spec says "The endpoint SHOULD also require some form of authentication to
   access this endpoint"

**Comment by TD49** [comment]
That's fine for client apps that may want to validate the token themselves.   

However, what about those API's/Token Consumers that previously used the validation endpoint to verify origin source and decode an access token?     These API's may be consumed by multiple client apps, and shouldn't have to maintain knowledge of client id/secrets.      

The only choice, if using a full JWT Access token, would be to force the API hosts to take on the public key of the token's signing cert and validate locally.  However, this still wouldn't address an API validating a reference token.   

NOTE:  we're using the RO grant

**Comment by leastprivilege** [comment]
Well - 

a) the validation endpoint will not go aways soon
b) maybe the authN requirement will be configurable
c) maybe we introduce something like scope credentials (as opposed to client credentials)

**Comment by TD49** [comment]
Interesting. Curious to see how scope credentials would work.    

Prefer POST over GET, but since IdSvr's keeping the validation endpoint live at least through 2.1, no short-term worries.

**Comment by leastprivilege** [comment]
Introspection works is being done here
https://github.com/IdentityServer/IdentityServer3/pull/1639
