### ISSUE TITLE
Do not require a subject for custom grant validation

### ISSUE THREAD

**Issue by khaledh** [IdentityServer/IdentityServer3#937]
We have a scenario where we are extending IdSrv3 to support the JWT bearer assertion authorization grant by implementing `ICustomGrantValidator` and `IClaimsProvider`. In this scenario some assertions will involve a user and some will not. For the case where a user is not involved, a trusted client is using the assertion grant flow to instruct IdSrv3 to include extra claims in the access token (e.g. a tenant id). Unfortunately, `CustomGrantValidationResult` requires a subject (technically, it's when `CustomGrantValidationResult` tries to add the `sub` claim that the `Claim` class constructor throws because we tried to pass a `null` value as the subject).

Are we trying to do something crazy, or is this a legitimate use case that IdSrv3 should support?

**Comment by brockallen** [comment]
Yes, this is somewhat of a known issue. IIRC, @leastprivilege did make some changes recently to accommodate this (or he was planning or it's still on a branch somewhere). Anyway, he'll have an answer since I've forgotten the status.

**Comment by leastprivilege** [comment]
I think I made a change and do not require sub anymore. Can't remember, need to double check.

**Comment by leastprivilege** [comment]
Ah - I remember - you can add to the client claims collection in the custom validator. I think that was the "workaround".

**Comment by khaledh** [comment]
Well, I was relying on my custom `IClaimsProvider` to transform claims, whether a user is involved or not. But basically you're saying:

1. If a user is involved, use `new CustomGrantValidationResult(subject, authenticationMethod, claims)` to establish the principal and rely on a custom `IClaimsProvider` to transform the claims
2. If a user is not involved, in the custom validator use `request.Client.Claims.Add(...)` to add claims to the access token, then use `CustomGrantValidationResult`'s empty ctor to return an empty validation result

Is that correct?

**Comment by leastprivilege** [comment]
OK - I see - you want to be able to return claims from the custom grant validator but no subject - is that right?

I can do that - but that means that that means that you must also implement the claims provider - since the claims that are being returned might not be valid for the standard pipeline. I guess you are OK with that..

**Comment by leastprivilege** [comment]
Oh hold on - why can't you use the default ctor of CustomGrantValidationResult - and set the Principal property yourself?

**Comment by khaledh** [comment]
> OK - I see - you want to be able to return claims from the custom grant validator but no subject - is that right?

Yes, for the case when there's no user involved. There's another case when a user is involved, and in that case the returned claims will include a subject.

> I can do that - but that means that that means that you must also implement the claims provider - since the claims that are being returned might not be valid for the standard pipeline. I guess you are OK with that..

I already have a custom claims provider that derives from `DefaultClaimsProvider`, which copies some claims from the principal, if set by the custom grant validator.

> Oh hold on - why can't you use the default ctor of CustomGrantValidationResult - and set the Principal property yourself?

I could do that, but looking at the non default ctor it seems to be doing more than just setting the subject; it also sets a few standard claims as well (`amr`, `idp`, `auth_time`) and I'm not sure setting those should be the responsibility of my custom grant validator.

The way I was hoping to do it to consider the custom grant validated but without setting a subject. Then leave it to the custom claims provider to copy/set any claims based on what has been decided in the custom grant validator.

**Comment by leastprivilege** [comment]
You can use the default ctor - and set whatever claims you want - it is up to the claims provider then to make sense of them.

**Comment by khaledh** [comment]
Here's what i tried:
```csharp
class JwtAssertionGrantValidator : ICustomGrantValidator {
    public Task<CustomGrantValidationResult> ValidateAsync(ValidatedTokenRequest request) {
        // lots of validation
        // ...
        // create a principal with some claims, but without a "sub" claim
        // ...
        var result = new CustomGrantValidationResult {
            Principal = principal
        };
        return Task.FromResult(result);
    }
}
```

Then in the claims provider:

```csharp
class JwtAssertionClaimsProvider : DefaultClaimsProvider {
    public override async Task<IEnumerable<Claim>> GetAccessTokenClaimsAsync(
        ClaimsPrincipal subject,
        Client client,
        IEnumerable<Scope> scopes,
        ValidatedRequest request) {

        var claims = await base.GetAccessTokenClaimsAsync(subject, client, scopes, request);
        var newClaims = claims.ToList();
        // copy/set claims as needed
        // ...
        return newClaims;
    }
}
```

However, I'm getting an exception `"sub claim is missing"` when calling the base class method `base.GetAccessTokenClaimsAsync`.

Apparently by setting the `Principal` property on `CustomGrantValidationResult` I'm implying to the framework that the principal has a `sub` claim, which is not the case. So it seems to me that no matter what, a subject is always expected, unless I set all the claims manually without relying on the base class `DefaultClaimsProvider`, which seems to be a lot of work.

**Comment by leastprivilege** [comment]
Sure - the base class assumes default behavior. You need to have your own IClaimsProvider implementation.

That's all I can offer right now. We can leave this open and add it to the todo backlog.
