### ISSUE TITLE
Welcome page doesn't allow custom view in assest directory

### ISSUE THREAD

**Issue by ambvdijk** [IdentityServer/IdentityServer3#942]
The WelcomeActionResult should derive from HtmlStreamActionResult so that it allows customizing.
Or at least it should use the ViewLoader instead of directly going for the AssetManager

**Comment by brockallen** [comment]
There are 3 different features (Scopes, Client, and Operational): 
https://identityserver.github.io/Documentation/docs/ef/overview.html
You need to opt into each one.

**Comment by ambvdijk** [comment]
Hi @brockallen, thank you for the response. 

I have been trying to replace the welcome (embedded) view with a custom one by placing an _welcome.html in my assets directory, but it doesn't get picked-up as desribed here: https://identityserver.github.io/Documentation/docs/advanced/customizingViews.html

Looking at the sources this seems to bee caused by the WelcomeActionResult which doesn't use the ViewLoader.

**Comment by brockallen** [comment]
Oh sorry -- I somehow replied to the wrong issue.

**Comment by ambvdijk** [comment]
np

**Comment by brockallen** [comment]
Ok, yes... the welcome screen was added late. We'll consider making it replaceable in vNext. For now, you can always disable it with the flag, and then provide your own page that renders at the root of your web host.

**Comment by ambvdijk** [comment]
Ah. Didn't figure out the disable feature yet! 
Should be enough to get me going.
Thanks!

**Comment by brockallen** [comment]
@leastprivilege up for discussion for 2.0

**Comment by brockallen** [comment]
Given that the welcome page can be disabled, and that a custom host can provide such a page, and that page can determine the current logged in user, I'm inclined to reject this issue in the name if not introducing more breaking APIs.

Anyone else have an opinion?

**Comment by leastprivilege** [comment]
Agreed.

**Comment by ambvdijk** [comment]
I disabled the welkome page for now. Normally a user will not visit this page, so it's a really low priority.
I don't mind closing this issue.

**Comment by brockallen** [comment]
Ok, then we're all in agreement -- we don't need to disrupt the view service with this. Thx.
