### ISSUE TITLE
Feature Request  - Show logout redirect uri, after idsvr cookie has expired

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3#964]
This is what currently happens:
1. User logs in and id_token is added to RP's claims
2. Time out expires on both RP and idsvr.
3. User clicks the logout link
4. User is not authenticated with idsvr anymore, so no id_token validation happens, therefore no redirect uris.

It would be nice if the user is presentend with the redirect URI.

Is it possible, to validate the id_token prior checking if the user is authenticated? It may be possible, that the user has expired in idsvr, but is still current in the RP. In this case, the id token would be available and can be sent through.

**Comment by leastprivilege** [comment]
Added on dev. Give it a try.

**Comment by parkinsona** [comment]
Hi Dom, it'll be a few days maybe a week before I get a chance to try this out. 
I've got some other changes I'm working on atm.
